### ISSUE TITLE
Add clone button for tasks

### ISSUE THREAD

**Issue by mehdi-belkhayat** [Dolibarr/dolibarr#10000]
Feature Request 

It would be great to have a clone button for tasks, in projects.
And so for all actions without a clone button

**Comment by paillet-mikael** [comment]
Hi 
yes good idea for task !
bye

**Comment by SylvainLegrand** [comment]
Hi,

+1 for this request.

Greetings,
Sylvain Legrand

**Comment by atm-maxime** [comment]
Feature request to keep

**Comment by atm-maxime** [comment]
Still relevant

**Comment by atm-maxime** [comment]
Still needed

**Comment by atm-maxime** [comment]
Done in v17
