### ISSUE TITLE
Bug: Error when updating to the last commit

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#10005]
# Bug
[*Erreur DB_ERROR_SYNTAX: Alter tABLE llx_c_action_trigger MODIFY COLUMN elementtype varchar(32)ALTER TABLE llx_c_field_list ADD COLUMN visible tinyint	DEFAULT 1 NOT NULL AFTER search;
Erreur de syntaxe près de 'ALTER TABLE llx_c_field_list ADD COLUMN visible tinyint	DEFAULT 1 NOT NULL AFTER' à la ligne 1*]

## Environment
- **Version**: 9.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.23-2+0~20181017082658.9+jessie~1.gbpab65a0
- **Database**: MySQL or MariaDB 5.5.5-10.0.37-MariaDB-0+deb8u1
- **URL**: /index.php?mainmenu=home&username=

**Comment by simnandez** [comment]
I can't reproduce it, maybe it is solved
