### ISSUE TITLE
Custom module Icon is not shown properly in the top menu bar

### ISSUE THREAD

**Issue by bgenere** [Dolibarr/dolibarr#10032]
# Bug
Custom module Icon is not shown properly in the top menu bar

## Environment
- **Version**: Since Dolibarr v7 I think but now get the issue with V8 and V9 (dev)

## Expected and actual behaviour
My module exists since Dolibarr V6 and has an icon that was properly displayed in both top menu bar and module list in configuration.
With the latest versions the icon is still displayed properly in module list configuration but not any more in the top menu bar.

This is the html code attached to the icon 
`<div class="mainmenu vignoble topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_vignoble"></span></div>`

The style sheet is generated this way which is obviously wrong.
`div.mainmenu.vignoble {
    background-image: url(/theme/eldy/img/menus/generic2_over.png);
}`

I have looked to the Module development documentation and the module template but did not find any new instruction regarding the use of an icon.

This is how my picto is defined in the constructor of the module, and still works perfectly except for the top menu.

`/**
		 * picto : image file used for the module
		 */
		$this->picto = 'vignoble@vignoble';`

I there anything to change in the module code or this is a bug ?

**Comment by ghost** [comment]
Yes, this is a new "feature" you should create also an icon with vignoble_over.png image

**Comment by bgenere** [comment]
Ok, I add this new file, it works.
I will have a look to the documentation to add this information.
Thanks
