### ISSUE TITLE
Bug: the default currency is automatically wrong and not 1=1

### ISSUE THREAD

**Issue by dylaw** [Dolibarr/dolibarr#10037]
# Bug

## Environment
- **Version**: 8.0.3
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: cgi-fcgi 5.6.38-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.62-0+deb8u1
- **URL**: /admin/multicurrency.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php%3Fsearch_keyword%3Ddevise%26search_version%3D

**Comment by meljaroumi** [comment]
the same probleme when creation proposal in default currency with products boutgh with other currency 
thnx to make me notified when resolved

**Comment by eldy** [comment]
Can you describe steps to reproduce ?

**Comment by atm-maxime** [comment]
No news, I close the issue
