### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Osalgueiro** [Dolibarr/dolibarr#10059]
# Bug

## Environment
- **Version**: 8.0.3
- **OS**: Linux
- **Web server**: LiteSpeed
- **PHP**: litespeed 5.6.38
- **Database**: MySQL or MariaDB 10.1.36-MariaDB-cll-lve
- **URL**: /fourn/card.php?socid=33

## Report
Module Budget is not working properly:
Cannot add Contacts because the Contact type selection is not working. It gives an "Incorrect value of parameter 2".

**Comment by atm-maxime** [comment]
Hi !
This is due to the lack of contact types for supplier price request. You can add them in your dictionnary. They have been added in the next 10 version to come (#11205).
Thanks.
