### ISSUE TITLE
Allow external site to add more than one link to the menu

### ISSUE THREAD

**Issue by ChangePlaces** [Dolibarr/dolibarr#10053]
# Feature Request
It would be nice if more than one external site can be added to the menu in the external site module.

Maybe a menu builder that allows moving menu items around and adding internal / external links can be merged together?

## Suggested implementation
I'm totally new to dolibarr so can't offer any suggestions at the moment!

**Comment by dolibarr95** [comment]
hi!
https://www.dolistore.com/fr/modules/984-Sites-externes-multiples-7-0.html
it's free (i'm not the author).
