### ISSUE TITLE
FEATURE REQUEST : ADD JSXC XMPP CLIENT FOR CHAT/FILETRANSFER/VIDEO OVER WEBRTC

### ISSUE THREAD

**Issue by mehdi-belkhayat** [Dolibarr/dolibarr#10050]
Hi, 
Can you think about adding this JSXC XMPP Chat :
https://www.jsxc.org
https://github.com/jsxc/jsxc/releases

it supports multiple features :
https://www.jsxc.org/features.html

If the stun and turn server options are set, then the filetransfer and the voice/video calls can work over webrtc.

**Comment by Jenbalco** [comment]
This is a really great proposal for internal communication and collaboration for Dolibarr. Can we please bring this request back to life? 

Thanks for the amazing platform you guys have created.
