### ISSUE TITLE
Fatal error: Call to undefined function unixtojd() in /var/www/html/htdocs/core/lib/date.lib.php on line 849

### ISSUE THREAD

**Issue by zhaoxiong123** [Dolibarr/dolibarr#10065]
Fatal error: Call to undefined function unixtojd() in /var/www/html/htdocs/core/lib/date.lib.php on line 849

**Comment by aljawaid** [comment]
#10244

**Comment by atm-maxime** [comment]
I close this one, solution has been provided in #10244
