### ISSUE TITLE
[Bug] Api Explorer doesn't work in 7.0.2

### ISSUE THREAD

**Issue by NicolasDEVOUGE** [Dolibarr/dolibarr#10060]
# Bug
When I go to to API explorer, I get error 500

## Environment
- **Version**: 7.0.2
- **OS**: Ubuntu 16.04.2 LTS
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: PHP 7.0.22-0ubuntu0.16.04.1
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-1~xenial
- **URL(s)**: https://facturation/api/index.php/explorer/#!/login/listLogin

## Expected and actual behavior

When I go to https://facturation/api/index.php/explorer/#!/login/listLogin , and I put my key on Dolikey to explore the API, I get this message on WebUI : 

500 : https://facturation/api/index.php/explorer/swagger.json

Ans the apache error log said : 

[Wed Nov 21 16:47:17.061397 2018] [:error] [pid 4058] [client 10.111.3.62:54974] PHP Fatal error:  Cannot declare class CategoryApi, because the name is already in use in /opt/datas/www/production/dolibarr/htdocs/categories/class/api_category.class.php on line 0, referer: https://facturation/api/index.php/explorer/

I have tried with another dolibarr installed from scratch, in 7.0.3 , everything is OK, is it a bug with 7.0.2 ?

Thank you !

**Comment by ghost** [comment]
Yes I confirm, the bug come from two files with different name but declare the same Class.
Fact is if you install Dolibarr with FTP by copy past, old files are keept. Should deploy by git, that assure you you have only the correct file

**Comment by ghost** [comment]
That why when you install from scratch a 7.0.3 the problem do not occurs any more

**Comment by NicolasDEVOUGE** [comment]
Hello, thank you for your response, you helped me ;)

I have deleted api_category.class.php , and now it works !
