### ISSUE TITLE
# Feature Request:  line numbers (position numbers)

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#10075]
# Feature Request

an option for supporting line numbers (position numbers) in documents

this could work automatic or manually  
for example:

Pos.           Description          Unit               VAT         Price    ....

_1_          <-   editable field  - automatic proposal but you can overwrite  

and this is also working on printing

**Comment by Rendscode** [comment]
I second com4WEBs original feature request for having position numbers in documents. Please reopen!
