### ISSUE TITLE
Spanish Translation "purchase orders"

### ISSUE THREAD

**Issue by dpuenteb** [Dolibarr/dolibarr#10080]
In Dolibarr 8.0.2, the "purcharse order" option is not translated. I attach the image. Thanks!!!

**Comment by dpuenteb** [comment]
![image](https://user-images.githubusercontent.com/214935/49002077-d8201080-f15e-11e8-90ba-86e091b4c37f.png)

**Comment by simnandez** [comment]
This affects all languages, many translations about suppliers are in English in the language file xx_XX.lang
