### ISSUE TITLE
Error Emails from 8.0.2 to 8.0.3

### ISSUE THREAD

**Issue by ajtel** [Dolibarr/dolibarr#10092]
# Bug
EMAILS CAN NOT SENT

## Environment
- **Version**: [*8.0.3*]
- **OS**: [*Linux cp.ajtel.net 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64*]
- **Web server**: [*Apache*]
- **PHP**: [*7.0.32*]
- **Database**: [*Mysql*]
- **URL(s)**: [*Affected URL(s)*]

Dolibarr ha detectado un error técnico.
Esta información puede ser útil para el diagnóstico (puede configurar la opción $dolibarr_main_prod to '1' para eliminar estas notificaciones):
Fecha: 20181128161258
Dolibarr: 8.0.3
PHP: 7.0.32
Servidor: Apache
SO: Linux cp.ajtel.net 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

URL solicitada: /facturacion/admin/mails_templates.php
Referer: https://*******/facturacion/admin/mails_emailing.php
Administrar menú: eldy_menu.php

Administrador de tipo de base de datos: mysqli
Último error en solicitud de acceso de base de datos: SELECT rowid as rowid, label, type_template, lang, fk_user, private, position, topic, joinfiles, content_lines, content, active FROM llxw5_c_email_templates WHERE entity IN (0,1) ORDER BY label ASC, lang, position LIMIT 1001
Código de retorno de error para la última petición de acceso a la base de datos: DB_ERROR_NOSUCHFIELD
Información del último error de petición de acceso de base de datos: Unknown column 'joinfiles' in 'field list'

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by ghost** [comment]
the missing column "joinfiles" exists in the table llxw5_c_email_templates from the 7.0.0. Did you miss a upgrade process between 6.0 -> 7.0. You should run 
ALTER TABLE llxw5_c_email_templates ADD COLUMN enabled varchar(255) DEFAULT '1';
ALTER TABLE llxw5_c_email_templates ADD COLUMN joinfiles varchar(255) DEFAULT '1';
ALTER TABLE llxw5_c_email_templates MODIFY COLUMN content mediumtext; 
To be sure you that the missing column will be created. The bug must exists before your 8.02->8.03 migration

**Comment by ajtel** [comment]
sorry how do i do that?

**Comment by simnandez** [comment]
rename the file at the root of your documents directory named install.lock to _install.lock

launch https://*******/install and lauch the 6.0.* -> 7.0.* update

at the end of update, rename the _install.lock to install.lock

**Comment by ajtel** [comment]
same error persist

**Comment by eldy** [comment]
Bug is related to an old previous install or migration.
