### ISSUE TITLE
REST API create thirdparty as customer fail with error ErrorCustomerCodeRequired

### ISSUE THREAD

**Issue by MatthieuTexier** [Dolibarr/dolibarr#10100]
When creating a thirdparty setting customer to "1", server returns an error ErrorCustomerCodeRequired but customer codes are created by the server.

sample command to reproduce:
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: XXXXXXXXXXX' -d '{
  "client": "1",
  "name": "TEST"
}' 'http://XXXXXXX/dolibarr/api/index.php/thirdparties'

**Comment by ghost** [comment]
IF you setup dolibarr (configuration->thirdparties) with a required customer code, it mean you should give it to the API when you set to  customer status

**Comment by eldy** [comment]
You can also set the value to 'auto' when calling API.

**Comment by MatthieuTexier** [comment]
> IF you setup dolibarr (configuration->thirdparties) with a required customer code, it mean you should give it to the API when you set to customer status

The setup is Monkey mode, codes are generated by Dolibarr, I don't want to create one by myself.

**Comment by MatthieuTexier** [comment]
> You can also set the value o 'auto' when calling API.

Thank you Laurent, it works for me too when setting "client" to "1" and "code_client" to "auto"

**Comment by MatthieuTexier** [comment]
worked on 7.0.3 but not on 8.0.3

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: XXXXXXXXXXXXXX' -d '{
 "client": "1",
 "client_code": "auto",
 "name": "customer"
}' 'http://mon_serveur/dolibarr/api/index.php/thirdparties'

fails with error
{
  "error": {
    "0": null,
    "1": "ErrorCustomerCodeRequired",
    "code": 500,
    "message": "Internal Server Error: Error creating thirdparty"
  }
}

**Comment by hichxm** [comment]
In the source code, you need to set '-1' for automatic assignment of client `code_client`. The same for `code_fournisseur`

https://github.com/Dolibarr/dolibarr/blob/1b5eb2de22ccee5377549a219d0448f1e3026117/htdocs/societe/class/societe.class.php#L862-L869 

The curl request will be like this : 
```
curl -X POST \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'DOLAPIKEY: XXXXXXXXXXXXXX' \
-d '{
    "client": "1",
    "client_code": "-1",
    "name": "customer"
}' 'http://mon_serveur/dolibarr/api/index.php/thirdparties'
```

**Comment by GenZai** [comment]
I'm on version 13.0.5

For me the key is code_client and not client_code
