### ISSUE TITLE
Feature Request : Price taxes included 

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#10102]
Hi all
As asked on the french forum
https://www.dolibarr.fr/forum/12-howto--aide/63137-prix-ttc-dans-les-formulaires

It could be nice create document (quotation etc.) directly in included taxes.
A variable exist
```php
$inputalsopricewithtax;// (0 by default, 1 to also show column with unit price including tax)
```

Where can we define this var is there an official way ?
Actually the only method I know is to add 
```php
$inputalsopricewithtax=1;
```
in core/tpl/objectline_create.tpl.php

**Comment by agrarian-cyberpunk** [comment]
I've tried to use the setting $inputalsopricewithtax=1; in the file you said, didn't work when I add the free-text item the error Unit price (excl) is requierd

**Comment by ksar-ksar** [comment]
A first step : PDF_PROPAL_SHOW_PRICE_INCL_TAX ► Display price with tax on Proposal(cyan template), Order(eratosthene template), Bill(sponge template)
