### ISSUE TITLE
REST API set thrirdparty as customer fails

### ISSUE THREAD

**Issue by MatthieuTexier** [Dolibarr/dolibarr#10101]
calling PUT "/thirdparties/{id}" with "client": "1" does not set thr thirdparty as customer

**Comment by ghost** [comment]
It work if you set do a GET "/thirdparties/{id}" copy/paste or load as object in php and change the attribute client to 1 and PUT "/thirdparties/{id}".
As everywhere in dolibarr, the update methoed need all the data of the object. Fetch -> set the object -> Update

**Comment by MatthieuTexier** [comment]
I tried this before I filled the ticket, and I did it again now using the swagger interface and it does not work.

**Comment by MatthieuTexier** [comment]
I followed Laurent advice in #10100 and set both "client" to "1" and "client_code" to "auto".
Now the record have "client" set to "1" but "client_code" is still null, how do I get it filled ?
Thanks
