### ISSUE TITLE
Token not found in db, are you sure you stored it? NoDefaultPrinterDefined

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#10106]
# Bug

## Environment
- **Version**: 8.0.3
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/compta/facture/card.php?facid=137

**Comment by ghost** [comment]
You should renew your token into /dolibarr/printing/admin/printing.php?mode=setup&driver=printgcp
