### ISSUE TITLE
BUG : Can't obtain dolistore data from modules/markeplace

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#10137]
# Bug

Since module admin page , marketplace tab a search return an error.

## Environment
- **Version**: 8.0.3
- **OS**: Debian Stretch 9.4
- **Web server**: Apache 24
- **PHP**: 7.0
- **Database**: Mariadb
- **URL(s)**: https://dolibarr/admin/modules.php?mode=marketplace

## Expected and actual behavior
```
Can not access to https://www.dolistore.com
HTTP XML response is not parsable: array ( 0 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 63, 'column' => 105, 'message' => 'CData section not finished ', 'file' => '', 'line' => 344, )), 1 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 9, 'column' => 105, 'message' => 'PCDATA invalid Char value 12 ', 'file' => '', 'line' => 344, )), 2 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 76, 'column' => 116, 'message' => 'Opening and ending tag mismatch: language line 247 and strong ', 'file' => '', 'line' => 344, )), 3 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 76, 'column' => 120, 'message' => 'Opening and ending tag mismatch: description line 247 and p ', 'file' => '', 'line' => 344, )), 4 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 62, 'column' => 9, 'message' => 'Sequence \']]>\' not allowed in content ', 'file' => '', 'line' => 356, )), 5 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 1, 'column' => 9, 'message' => 'internal error: detected an error in element content ', 'file' => '', 'line' => 356, )), )Au lieu de bascule
```

## Steps to reproduce the behavior

Search a module since modules.php?mode=marketplace

**Comment by simnandez** [comment]
I can't reproduce it. Can you provide more info?

**Comment by frederic34** [comment]
Can not access to https://www.dolistore.com
HTTP XML response is not parsable: array ( 0 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 63, 'column' => 105, 'message' => 'CData section not finished ', 'file' => '', 'line' => 2047, )), 1 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 9, 'column' => 105, 'message' => 'PCDATA invalid Char value 12 ', 'file' => '', 'line' => 2047, )), 2 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 76, 'column' => 116, 'message' => 'Opening and ending tag mismatch: language line 1949 and strong ', 'file' => '', 'line' => 2047, )), 3 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 76, 'column' => 120, 'message' => 'Opening and ending tag mismatch: description line 1949 and p ', 'file' => '', 'line' => 2047, )), 4 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 62, 'column' => 9, 'message' => 'Sequence \']]>\' not allowed in content ', 'file' => '', 'line' => 2059, )), 5 => LibXMLError::__set_state(array( 'level' => 3, 'code' => 1, 'column' => 9, 'message' => 'internal error: detected an error in element content ', 'file' => '', 'line' => 2059, )), )
