### ISSUE TITLE
Two successive overpaid invoice bug

### ISSUE THREAD

**Issue by loxK** [Dolibarr/dolibarr#10167]
# Bug
I had the case where a customer overpaid two successive invoices. When I convert the second overpaid to a discount it wrongly calculates the discount.

## Environment
- **Version**: 7.0.3 and 8.0.3
- **OS**: Ubuntu 16.04
- **Web server**: Nginx
- **PHP**: 7.0
- **Database**: Mysql

## Expected and actual behavior
First invoice: 90000, but been paid 94500, I click the button to turn the overpaid amount into a discount
Second invoice a month later: 90000 to which I applied the previous discount, so 85500 to be paid  but been paid 94500 again.
Dolibarr correctly shows me the overpaid amount of 9000, but when I convert it into a discount, the discount amount is 4500 not 9000

## Steps to reproduce the behavior
- Create an invoice for 90000
- Make a payment of 94500 for that invoice
- Convert the overpaid amount into a discount, using the dedicated button
- Create another invoice of 90000, apply the previous discount (amount ot be paid is now 90000 - 4500 = 85500)
- Make a payment of 94500 for that second invoice
- Dolibarr correctly show an overpaid amount of 9000
- Convert the overpaid amount into a discount, using the dedicated button: the discount is wrongly set to 4500 instead of 9000

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

![image](https://user-images.githubusercontent.com/136687/49349771-50a74400-f700-11e8-9a35-32cc093b2342.png)

![image](https://user-images.githubusercontent.com/136687/49349801-703e6c80-f700-11e8-9c69-269f8d67e8e1.png)

![image](https://user-images.githubusercontent.com/136687/49349823-8e0bd180-f700-11e8-9c08-d5b0edaad210.png)

**Comment by atm-maxime** [comment]
Seems fixed in 9.0.5
