### ISSUE TITLE
Expenses, empty email notification

### ISSUE THREAD

**Issue by ctsobrino** [Dolibarr/dolibarr#10176]
# Bug
Expenses email notification

## Environment
- **Version**: 8.0.3
- **OS**: Windows

## Expected and actual behavior
When an expense repot is created, an email is automatically sent to a validator. When the expense is validated another email is sent. This 2 email notifications are ok, the email has a message. The email sent when ExpenseReportWaitingForReApproval, ExpenseReportRefused or ExpenseReportCanceled are empty. Although in trips.lang there is a message, the email is sent empty. The email for the ExpenseReportPaid is sent in french. This is message I received when the expense is paid:
"Bonjour Carlos, Votre note de frais "GS2018-0007" vient d'être payée. - Payeur : ...."

## Steps to reproduce the behavior
Try to create an expense and deny, cancel or pay.

**Comment by aljawaid** [comment]
https://github.com/Dolibarr/dolibarr/commit/5daf095fc60f5bbed9fdbb3cdec8db4e109f7869#diff-0d4f3eb47790be40425238787c15f8d8 FIX Title and content of automatic email of expense report

**Comment by ctsobrino** [comment]
I have changed the file but the only change is in the subject of the email,
the message is still empty

**Comment by atm-maxime** [comment]
This is a translation issue, the messages were not present in the fr_FR lang in 8.0. Since then, these translations have been integrated in 9.0 via [transifex](https://www.transifex.com/dolibarr-association/dolibarr/translate/#fr_FR/$/105293523?q=key%3AExpenseReportRefused)
