### ISSUE TITLE
Bug: 7.0.4: Missing Translation String in Holidays

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#10170]
# Bug
The string `HOLIDAY_CREATEInDolibarr` is missing in `/comm/action/list.php?&contextpage=actioncommlist&actioncode=0&filtert=-1&showbirthday=1&usergroup=-1`

I can't find which file it is created in for me to add to the relevant `.lang` file.  I tried `agenda.lang` but it never loaded the string.

## Environment
- **Version**: [*7.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache*]
- **PHP**: [*7.0.32*]
- **Database**: [*MySQL*]
- **URL(s)**: [*/comm/action/list.php?&contextpage=actioncommlist&actioncode=0&filtert=-1&showbirthday=1&usergroup=-1*]

**Comment by atm-maxime** [comment]
I don't understand this issue as I tried to find in 7.0, 8.0 and 9.0 for HOLIDAY_CREATE or HOLIDAY_VALIDATE, and nothing seems to be creating anything with these strings
