### ISSUE TITLE
Bug : no display of stock per batch series

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#10186]
# Bug
no display of stock per batch series

## Environment
- **Version**: 7.0.5

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
When delivering products with batches or series, batch quantities are not displayed

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![stocknegatif](https://user-images.githubusercontent.com/3629675/49540706-0a550f00-f8d1-11e8-8900-40703c48db45.png)

# Feature Request

**Comment by fappels** [comment]
@philazerty fixed for 7.0.5, you can close.
