### ISSUE TITLE
Swift Mailer is only compatible with php 7.0

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#10203]
# Bug
Swift Mailer is only compatible with PHP 7.0+.
The Swift Mailer library should not be used at install/upgrade and be grayed and unselectable in the admin page if PHP version is less than 7.0

## Environment
- **Version**: 8.0.3
- **OS**: GNU/Linux Debian
- **Web server**: nginx
- **PHP**: 5.6
- **Database**: MySQL
- **URL(s)**: Any sending email and email configuration page at admin/mails.php

## Expected and actual behavior
The email should be sent.
500 error page with PHP 5.x.

## Steps to reproduce the behavior
Try to send an email with Swift Mailer as the mailing system with a PHP 5.x install.

**Comment by rdoursenaud** [comment]
Related to #10091

**Comment by ptibogxiv** [comment]
You should update your php to 7 branch. Php 5 will be deprecated in few days. With php 7. x dolibarr is more powerful and fast.
