### ISSUE TITLE
Bug: Problem with import a company - SASU

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#10226]
Version 8.0.3

Hello,

Importing a company type "SASU" doesn't seem to work.

According to the database, the type is
> select rowid,libelle from llx_c_forme_juridique;
|    56 | Soci▒t▒ par actions simplifi▒e unipersonnelle (SASU)                                  |

When I import the company as type 56, it shows "Société anonyme à directoire" type 53

The import code should have a slight mistake.

Check it with this file

[Dolibarr-Societes_Bug-08Dec2018.txt](https://github.com/Dolibarr/dolibarr/files/2676343/Dolibarr-Societes_Bug-08Dec2018.txt)

**Comment by atm-maxime** [comment]
Thanks for this feedback, but I think it's not a bug.
The data you must set in your file is not the rowid of the table, but the code corresponding to the dictionnary value. Here you have the code 59 for "SASU" (rowid 56) and the code 56 is for "Société anonyme à directoire" (rowid 53). You can find codes in the dictionnary. I know it can be confusing. Can you try like this ?
