### ISSUE TITLE
Bug: Html codes in accounting export

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#10221]
# Bug
Export of ledger has some label with HTML code for accented characters:
"R&egrave;glement salaire" instead of "Règlement salaire"
"R&egrave;glement TVA" instead of "Règlement TVA"
"Op&eacute;ration diverse" instead of "Opération diverse"

## Environment
- **Version**: 8.0.3
- **URL(s)**: /htdocs/accountancy/bookkeeping/list.php?action=export_file&&search_date_startmonth=11&search_date_startday=1&search_date_startyear=2018&search_date_endmonth=9&search_date_endday=30&search_date_endyear=2019&limit=50

**Comment by aspangaro** [comment]
Bug confirm.

Work on it

**Comment by papoteur-mga** [comment]
Merci à tous les deux.
