### ISSUE TITLE
HTML5 Validation - global corrections?

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#10237]
Question
When I decide to modify a page, first thing I do is correct any html that the validator complains about, so I can easily spot the errors I introduce.
Dolibarr has a great deal of ..align="left" or similar in many places, which I have replaced in some pages with the corresponding css, since the validator flags these as errors.
Before committing these minor changes, is there a plan to do this globally in one action?
Making these changes individually per page seems a great waste of effort when it could be done in one go.

**Comment by mwelters** [comment]
I think you should just prepare a pull request and see what happens... Eldy must have a huge workload according to all these pr's he merges and maybe no time left to read issues ...
