### ISSUE TITLE
Holiday request

### ISSUE THREAD

**Issue by ctsobrino** [Dolibarr/dolibarr#10244]
# Bug
I have Dolibarr 8.0.3 install in a server from my hosting. When I try to create a new holiday request for a couple of days, I have an empty error page. If I create different requests (single day holiday request, one for each day) it creates it ok and I can validate them. 

## Environment
- **Version**: 
- **OS**: 
- **Web server**: 
- **PHP**: 
- **Database**: mySQL
- **URL(s)**: Dolibarr/htdocs/holiday/card.php

## Expected and actual behavior
I expected the same behavior than a single day holiday request.

## Steps to reproduce the behavior
Try to create a new holiday request for a couple of days, I have an empty error page

**Comment by aljawaid** [comment]
Confirmed error in `v7.0.4` too

**Comment by aljawaid** [comment]
This is the error:
`
Fatal error: Uncaught Error: Call to undefined function unixtojd() in /home/dolibarr/public_html/core/lib/date.lib.php:804 Stack trace: #0 /home/dolibarr/public_html/core/lib/date.lib.php(879): num_public_holiday(1546732800, 1547164800, 'GB', 1) #1 /home/dolibarr/public_html/holiday/card.php(142): num_open_day(1546732800, 1547164800, 0, 1, 0) #2 {main} thrown in /home/dolibarr/public_html/core/lib/date.lib.php on line 804
`

**Comment by mwelters** [comment]
It is not a Dolibarr Problem. 
The function unixtojd() is in the php-calendar extension. 
Make sure that your hosting provider has "extension=calendar.so" enabled in your active php.ini.
You can check in dolibarr /admin/system/phpinfo.php if calendar support is enabled.

https://www.w3schools.com/php/php_ref_calendar.asp

**Comment by aljawaid** [comment]
@mwelters Thank you for the hint, that fixed the problem.  PHP Calendar extension was not installed for the correct PHP version on the server.

**Comment by mwelters** [comment]
Perfect. Please close the issue.
