### ISSUE TITLE
migration 7.0 9.0 sql issue

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#10245]
# Bug
Erreur DB_ERROR_1071: ALTER TABLE llx_emailcollector_emailcollectorfilter ADD UNIQUE INDEX uk_emailcollector_emailcollectorfilter (fk_emailcollector, type, rulevalue);
Specified key was too long; max key length is 767 bytes

## Environment
- **Version**: dolibarr 9.0 beta
- **OS**: debian
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
We should not build unique indexes on long varchar columns 

## Steps to reproduce the behavior
Migrate from 7 - 9, maybe also on fresh installs

**Comment by milamberspace** [comment]
Workaround (on mariadb 10.1):

Error DB_ERROR_1071: ALTER TABLE llx_emailcollector_emailcollectorfilter ADD UNIQUE INDEX uk_emailcollector_emailcollectorfilter (fk_emailcollector, type, rulevalue);
Specified key was too long; max key length is 767 bytes

==> before force upgrade:

MariaDB [dolibarrdb]> ALTER TABLE `llx_emailcollector_emailcollectorfilter` ROW_FORMAT=DYNAMIC;
Query OK, 0 rows affected (0.07 sec)
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [dolibarrdb]> ALTER TABLE `llx_emailcollector_emailcollectorfilter` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
Query OK, 0 rows affected (0.09 sec)               
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [dolibarrdb]> ALTER TABLE llx_emailcollector_emailcollectorfilter ADD UNIQUE INDEX uk_emailcollector_emailcollectorfilter (fk_emailcollector, type, rulevalue);
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0
