### ISSUE TITLE
RFE: import width and depth

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#10250]
Version 8.0.3

Hello,
This is a feature request.
When I import a product, I can import the length but not the width or depth.
At least with the default import template.
It would be nice to be able to import width and depth with the default template.

[Dolibarr-Produits_Bug.txt](https://github.com/Dolibarr/dolibarr/files/2688112/Dolibarr-Produits_Bug.txt)

**Comment by torvista** [comment]
There are many fields available which are not included in the example csv nor implemented in the import. You can import all the product fields but you will need to modify
htdocs/core/modules/modProduct.class.php

**Comment by mikygee** [comment]
Thank you for your answer,

Is it this line you're talking about ?
```
                $this->import_fields_array[$r]=array(
                        'p.ref'=>"Ref*",'p.label'=>"Label*",'p.description'=>"Description",'p.url'=>"PublicUrl",'p.accountancy_code_sell'=>"ProductAccountancySellCode",
                        'p.accountancy_code_buy'=>"ProductAccountancyBuyCode",'p.note'=>"Note",'p.length'=>"Length",'p.surface'=>"Surface",'p.volume'=>"Volume",
                        'p.weight'=>"Weight",'p.duration'=>"Duration",'p.customcode'=>'CustomCode','p.price'=>"SellingPriceHT",'p.price_ttc'=>"SellingPriceTTC",
                        'p.tva_tx'=>'VATRate', 'p.tosell'=>"OnSell*",'p.tobuy'=>"OnBuy*",'p.fk_product_type'=>"Type*",'p.finished'=>'Nature','p.datec'=>'DateCreation'
                );
```

I plan to check in the 9.x version

**Comment by torvista** [comment]
Yes. See my pull request, and get that same file.
It has much more information in the example csv and the code is easier to read.
https://github.com/Dolibarr/dolibarr/pull/10261

**Comment by mikygee** [comment]
Gracias Steve.
