### ISSUE TITLE
DB Error utf8_danish_ci - utf8_unicode_ci in "Turnover invoiced"

### ISSUE THREAD

**Issue by bluethumb** [Dolibarr/dolibarr#10289]
# Instructions
Bug in Acountpage in rapport "Turnover invoiced"
I think dolibarr do not like that I have "utf8_danish_ci" as mysql char setup  

Should dolibarr only use "utf8_unicode_ci" as char for mysql? And nothing else ?

# Bug
 SELECT date_format(b.doc_date,'%Y-%m') as dm, sum(b.credit) as amount_ttc FROM llx_accounting_bookkeeping as b, llx_accounting_journal as aj WHERE b.entity = 1 AND b.code_journal = aj.code AND aj.nature = 2 GROUP BY dm ORDER BY dm
---  DB_ERROR_1267

Illegal mix of collations (utf8_danish_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='

## Environment
Dato: 20181230230254
Dolibarr: 10.0.0-alpha
Niveau funktionsliste: 1
PHP: 7.3.0
Server: nginx/1.14.2
OS: Linux htlab 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
Dolibarr  10.0.0-alpha

**Comment by eldy** [comment]
Bug was fixed in recent versions of Dolibarr.

utf8_danish_ci can works, but you should have utf8_danish_ci everywhere (on all tables)
However, i recommand to use utf8_unicode_ci everywhere.

You can try to call the page /install/repair.php.
One parameter is available to auto update all tables to utf8_unicode_ci.

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
