### ISSUE TITLE
Bug: i cant change the logo 

### ISSUE THREAD

**Issue by virzillo** [Dolibarr/dolibarr#10296]
# Bug
it is impossible to change the logo or the avatr for the user.
The upload of ohter files works.
when i change the logo the name of the file is there, but it do not upload.
Thanks
## Environment
- **Version**: 8.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.1.24
- **Database**: MySQL or MariaDB 5.5.5-10.0.36-MariaDB-cll-lve
- **URL**: /user/home.php?leftmenu=users

**Comment by ksar-ksar** [comment]
Hi,

This is working on my test area.

Could you check your logs ?
May be a right problem on the directory ?

**Comment by virzillo** [comment]
Which folder i have to change?

Thanks

**Comment by mwelters** [comment]
You have to make sure your php temp/upload directory and  your document directory has sufficient permissions.
The uploaded logo goes to {document dir}/mycompany/logos

**Comment by mwelters** [comment]
Please close the issue, if your problem is solved
