### ISSUE TITLE
Feature Request: Adding a view "per resource" on agenda.

### ISSUE THREAD

**Issue by Jenbalco** [Dolibarr/dolibarr#10290]
Hi folks, 

Please review this idea and let's make it possible. I think this is very important feature that all Dolibarr users can benefit from regardless of industry or business model.

**Part I**
a)  Merge the new Assets module code and libraries with the existing Resources module

b) Move/Build the Resources module under the Inventory Top menu
 
c) Break assets data into Three main cards 

c-1) Resource Main Card = Resource REF / Label / Barcode / Type (Inventory Categories / Location (Warehouse) / Assigned to ( Group or User) / Status

c-2) Financial Card = Purchase Data / Links to Purchase Orders and/or Contracts (Support & Warranties) / Current Value / Depreciation Percentage / Accounting Account / Depreciation Account

c-3) Depreciation Card = Declination Chart Showing approximate value based on Depreciation method and percentage

**Part II** 
Add Resources Card to Inventory Products/Services to help identify the resources and that are used in the production and/or costing of  inventories (Similar to Virtual Products Model)

Resource Analyctics and reports
*  Resource Activity allocations such as Agenda Activities / Inventory/Production Activities or Projects Activities
 
 * Resources by Operational Statuses such as i.e. Available / In Maintenance Or Else (from Dictionary definitions)
 
 * Resources Declining value over time such as Quarters or Years

**Comment by ghost** [comment]
I agree with your point, and i add that :

- we should be able to consider an "asset disponibility" a service and therefore sell it in the contracts module.
- duration of services in the contract module should be synchronized and visible within the agenda.

I plan to try to code all of this.

When i have a functional but buggy code of all of that, i'll need some testing :)

**Comment by braito4** [comment]
long time ago we made this pull:
https://github.com/Dolibarr/dolibarr/pull/6233

**Comment by Jenbalco** [comment]
> long time ago we made this pull:
> #6233

@braito4 - I had a chance to look at #6233 and #7860 and they are both closed. Meanwhile the resources is still about the same, on the other hand another assets module is currently in development. I  Know most of the small business owners on here have computers, some machinery, vehicles, buildings especially already with data already entered in the current resources module would benefit tremendously from this merge. Thus if there is any room for consideration, please revisit and ask the community. Thanks!

**Comment by Jenbalco** [comment]
@eldy do you have any opinion on the possibility of this feature becoming part the core in the near future releases. I sincerely believe that this is actually possible. Thank you for the consideration!

**Comment by eldy** [comment]
Currently we have a agenda view "per user" 
Adding a page "per resource" would be welcome.
Let's start with that.

**Comment by BebZ** [comment]
Is it linked with ATM asset's module, because it is now really confusing...
what is "ATM asset", what is "ASSET", what is "RESOURCE"...
all the same ?

**Comment by atm-maxime** [comment]
All 3 are different. ATM asset module is to manage product by serial number.
Core asset module has something to do with accountancy (ask @aspangaro)
Ressource is to manage company stuff (cars, phone, rooms, ...)
At least that's how I understand it !

But I think having a per resource view on calendar is a great idea.

**Comment by Jenbalco** [comment]
@BebZ @atm-maxime @eldy -  Resources are company assets (otherwise referred to as fixed-assets) therefore tracking them on the accounting with new CORE assets module provides managers a good perspective when resources/assets have reached their life cycle for disposal and also account for depreciation.

To be honest this feature is usually a hard one to master but I will put together a diagram  and attach here in hopes that it helps to provide some clarity on the original Feature request. But I am grateful for @eldy 's consideration to this issue.

**Comment by braito4** [comment]
Also, it should be use to arrange the different spaces that the company has that they aren't asses per se, example: rooms (if i have to schedule an appointment, track the room is not occupied)
