### ISSUE TITLE
Bug 8.0.4 Supplier invoice from orders

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#10295]
# Bug
blank page when you try to create a supplier invoice from supplier orders

## Environment
- **Version**: 8.0.4
- **OS**: Ubuntu 16.04LTS - Windows 10 pro 64
- **Web server**: Apache 2.4.37
- **PHP**: 7.2.13 - 7.1.25
- **Database**: MariaDB 10.3.11
- **URL(s)**: .../fourn/commande/orderstoinvoice.php

## Expected and actual behavior
from the supplier card you want to create a invoice from one or more supplier orders.
At the end of process (the last step) doesn't work => blank page !

## Steps to reproduce the behavior
From suppler card => Bill orders button => select one or more orders and validate => fill the application for payment type, public or private notes, ... => create draft button => BLANK PAGE

## Suggested solution
from the syslog => an event may be created with the code : "AC_ORDER_SUPPLIER_CLASSIFY_BILLED" ; this is too long because the code field on llx_actioncomm should be a varchar with 32 caracters (this code contain 33 caracters).

set this field length to 128

greetings,
Sylvain Legrand.

**Comment by mistraloz** [comment]
I confirm the bug.

**Comment by futurehousestore** [comment]
I confirm that this bug still exists in v. 9.0.2

**Comment by atm-maxime** [comment]
Fixed in #11059
