### ISSUE TITLE
Bug: Inventory don't work

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#10307]
# Bug
I tried to create new inventory but nothing happens.

http://localhost/develop/product/inventory/card.php?action=create
version: dolibarr 9

**Comment by dbeniamine** [comment]
Hi,

I have the same issue with both Dolibarr `7.0.5` and `8.0.3` : when I create a new inventory from `/product/inventory/card.php?action=create&leftmenu=`, I end up on a white page at `/product/inventory/card.php` and I cannot see any inventory in `/product/inventory/list.php?leftmenu=`

**Comment by wdammak** [comment]
@dbeniamine
that's exactly my case. Thank you for confirming the bug.

**Comment by atm-maxime** [comment]
This is not a bug, it's an incomplete/unfinished feature. When your MAIN_FEATURE_LEVEL is not set to zero, you have access to experimental and in development features. A production installation must have MAIN_FEATURE_LEVEL set to 0.

**Comment by dbeniamine** [comment]
Oh indeed I put that instance on `MAIN_FEATURE_LEVEL=2` for testing purposes and forgot to reverse to 0, thanks for the answer !

**Comment by jfefe** [comment]
Fixed with https://github.com/Dolibarr/dolibarr/pull/10396

**Comment by wdammak** [comment]
@jfefe 
Many thanks!
But is the quantity field missing?
If not where we could enter the value of the product inventory?

**Comment by wdammak** [comment]
Can you describe this module? His ultimate goal?

**Comment by atm-maxime** [comment]
At first we wanted to integrate our [inventory](https://www.dolistore.com/fr/modules/500-Inventaire.html) module. Then it has been used to test the modulebuilder fonction to rewrite it to a Dolibarr standard code. But now it's not finished.
The ultimate goal is :

- Snapshot of the products stocks at the given date
- Stock value using PMP for each product
- Ability to enter for each product the real counted quantity
- Validation and regulation by stock movements creation
