### ISSUE TITLE
BUG report with multicompany

### ISSUE THREAD

**Issue by mapiolca** [Dolibarr/dolibarr#10324]
# Instructions
Generate report in supplier or costumer invoices with MULTICOMPANY.

We can view all report from all entities and not just their of the current entity.

## Environment
- **Version**: 8.0.4
- **URL(s)**: /compta/paiement/rapport.php

**Comment by atm-maxime** [comment]
Are you sure about that ? I checked how the PDF file is generated and since 2016 there's a filter by entity.

**Comment by hregis** [comment]
@mapiolca 
What is the version of muticompany ?
