### ISSUE TITLE
Feature request: update of product stock not available

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#10326]
As discussed here:
https://www.dolibarr.org/forum/12-howto-help/28659-import-new-stock-of-existing-products/reply/35770

The UPDATE of existing stock is currently not implemented.
I cannot understand why not. This seems such a basic requirement that I assume I am missing something.
Before I submit this PR, can someone confirm I am correct?
Thanks

**Comment by swedebugia** [comment]
What about exporting the list of stock, update the relevant rows in libreoffice and then import it again?

**Comment by torvista** [comment]
The export and import functions are unrelated things.
Export is intended to supply data for some other program or purpose (and so the fields should be customised to your needs).
Import is to replace manual entry (or should be).
The fields used in the exported/imported fields are not intended to mirror, as they are for different purposes.

I have not looked at this or Dolibarr further, but with hindsight, I now believe all stock updates should be based on a document movement, not brute-force imported.
Stock should come in with a supplier order, go out with an invoice.
If things do not add up, then there should be a trackable document with the manual correction.
