### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by morpheusbeing** [Dolibarr/dolibarr#10351]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
Typo in menu for Nnew contact under third parties

## Environment
Version 8.0.3
OS - Centos
apache

![image](https://user-images.githubusercontent.com/5505132/51287179-4b445580-1a31-11e9-9f30-01d271e67075.png)

**Comment by mwelters** [comment]
Already fixed in Branch develop

**Comment by laudeco** [comment]
This issue can be closed !
/cc @eldy

**Comment by frederic34** [comment]
@atm-maxime
