### ISSUE TITLE
Export tool : add more "translations" on codes

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#10363]
# Feature Request
Add "translations" for codes in export tool

## Use case
When I export my thirdparties, the file generated contains values like 0 or 1 (status), ST_NO, ST_NEVER, ... (fk_stcomm), 0,1,2,3 (customer) ... I'd like it to be the real values I have in the interface

## Suggested implementation
Replace codes by labels in exports

**Comment by atm-maxime** [comment]
Still a valid feature request

**Comment by eldy** [comment]
Another comment to test unstale

**Comment by eldy** [comment]
Another comment to test unstale

**Comment by atm-maxime** [comment]
Unstale again ;)
