### ISSUE TITLE
Variant price no accept decimal 

### ISSUE THREAD

**Issue by wavitools** [Dolibarr/dolibarr#10385]
Bug

When add a price in product variant with decimal, return  price with no decimal.
ex:  add  24,50  return my  24,00

## Environment
Version 10.0.0-alpha in local
But also in dolibarr 9.x demo can reproduce
https://demo.dolibarr.org/variants/combinations.php?id=196

**Comment by wavitools** [comment]
ok  reformulate the Issue:
if you insert decimal with this format : 22.75   (separate by point) that accept
if you insert with this format : 22,75 not accept decimal and save 22,00
https://demo.dolibarr.org/variants/combinations.php?id=196

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/10677
