### ISSUE TITLE
BUG: Default value for Extrafield of type SELECT is not working

### ISSUE THREAD

**Issue by infernet89** [Dolibarr/dolibarr#10387]
# Bug
If you create an ExtraField of type select, it won't take the default value.
Please note that the default value must be the index of the option.

## Suggested implementation
There is a small typo on **htdocs\core\class\extrafields.class.php** on line 1086.
The $key value is checked against $value instead of $default.

Just replace the line with:
**$out.= (((string) $default == (string) $key)?' selected':'');**

Already tested and working properly.

**Comment by aljawaid** [comment]
@infernet89 which version?

**Comment by infernet89** [comment]
Bug tested on 8.0.4, but it is still present on the latest version on the repository.

**Comment by infernet89** [comment]
Actually, to fix this you also need to manage the value on input, so:

```
if (!empty($value)) {
  $default=$value;
}
$out.= (((string) $default == (string) $key)?' selected':'');
```

**Comment by papoteur-mga** [comment]
> Actually, to fix this you also need to manage the value on input, so:
> 
> ```
> if (!empty($value)) {
>   $default=$value;
> }
> $out.= (((string) $default == (string) $key)?' selected':'');
> ```

Hi infernet,
where do you mean to insert this code ?
