### ISSUE TITLE
#Desing Question : What table to use to enter time on project/customer without task

### ISSUE THREAD

**Issue by delcroip** [Dolibarr/dolibarr#10392]
#Desing Question
Severals user asked me to support time entry on customer or project without task because it is over administration for them,

## Use case
Lawer wants to register time on a customer but he doesn't want to create a project for every customer

## Suggested implementation
I wanted to user the same table as the time on task (llx_projet_task_time) and to add 2 column fk_project and fk_customer but I fear that I will have to populate fk_task with something because it is a mandatory fields and I guess there is foreigner key on it.
I am not found of creating a new table because it will complexify the consolidation of the time spent by ressource.

## Question
Should I use the (llx_projet_task_time) for the time other that task ? 
if yes, can I alter the table to remove fk_task as mandatory (ie. will it create issue else where) ?
If no, what is the proposed table name so it can be aligned with futur core developement ?

**Comment by delcroip** [comment]
I think I will duplicate the llx_projet_task_time to llx_third_party_time and llx_project_time just switching the fk_task by fk_third_party and fk_project so a consolidation can be  done with UNION ALL

**Comment by eldy** [comment]
Good solution would be:
creating a generic project and generic task, so you don't have to create projet/task at each new customer.
Then add an extrafield on project_task_time with the customer. Problem: Extrafields on "time spent" are not yet implemented. But this is the good way to proceed...
