### ISSUE TITLE
[doc] @param string declared instead of int in extrafields.class.php

### ISSUE THREAD

**Issue by sowebio** [Dolibarr/dolibarr#10407]
# Bug
[* decl @param string instead of int in extrafields.class.php*]

## Environment
- **Version**: [*8.0.3*]

## Actual behavior
extrafields.class.php
150   @param  string	$size   Size/length of attribute
176, $size is passed  to create function lenght parameter
216 create function decl, $length is an int  parameter ($length=255)
really used as an int below
262 $lengthdb=$length;

## Suggested implementation
150 @param  int	$size   Size/length of attribute

**Comment by eldy** [comment]
The type is string because, it can be a numeric, but for float number, the definition is a string with 2 numeric (with add length for decimal part too)
