### ISSUE TITLE
Références de paiements invalides

### ISSUE THREAD

**Issue by Kaor** [Dolibarr/dolibarr#10417]
# Bug
```
Les références de paiements générées sont invalides.
Le format défini dans brodator est {yy}_{cccc}_R{0000} le résultat est : 19_####_R0012 
Le meme genre de format est utilisé pour les factures fournisseurs, sans soucis : 
{yy}_{cccc}_F{0000} -> 19_F009_F0033
```

## Environment
- **Version**: 8.0.3
- **OS**: Linux
- **URL(s)**: https://dolibarr/fourn/paiement/card.php?id=12

**Comment by Kaor** [comment]
on dirait que la référence dans dolibarr/htdocs/fourn/class/paiementfourn.class.php :
			$ref = $this->getNextNumRef('');
est vide.

**Comment by eldy** [comment]
Right.
Tag {cccc} is not yet support on payments. I pushed an enhancement 4b77b3ff236400431cf015210f4cfc07cf60a5e3 so we will have it in v10
