### ISSUE TITLE
Migrate the full project to PHP 7.3

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#10419]
We have to migrate all the project to at least PHP 7.2 and remove the support of the previous PHP versions.

![image](https://user-images.githubusercontent.com/3658458/51787311-87ce2a80-2170-11e9-9701-5e200b3fd7ef.png)
[Source](http://php.net/supported-versions.php)

Everybody knows that PHP 5.6 has been deprecated for a long time. But the  [composer.json](https://github.com/Dolibarr/dolibarr/blob/develop/composer.json) still supports PHP 5.3 😮. Is there a particular reason for that? Why it doesn't require PHP7.3?

If you look the graphic from WordPress, you see that PHP7.3 is quicker as any previous other versions of PHP.
![image](https://user-images.githubusercontent.com/3658458/51787474-b4834180-2172-11e9-9e12-b35f189014c8.png)
[Source](https://www.wp-tonic.com/blog/the-dos-and-donts-for-hosting-wordpress-membership-sites/)

At PHPBenelux 2019, [Rasums Lerdorf](https://twitter.com/rasmus) said that is easier to follow the versions instead of doing big steps.

Kind regards
L.

**Comment by wdammak** [comment]
Hello @laudeco
Tested with php 7.3.1on wamp without any worries.

**Comment by laudeco** [comment]
I just understood from @eldy in this video https://youtu.be/lA9SGdfvY_Q that he wants to stay on 5.6. His point is fully understandable but for the develop branch why not to migrate to PHP 7.3 directly ?

**Comment by laudeco** [comment]
Now I think I understand why nobody does that job. Actually we don't use composer, we use it for a list of packages but that's it.

We **cannot** do a _composer install / update_. Or if we do, composer will install everything and then we have to apply **manual** changes on the libraries.

So if someone knows how to use composer on this project, please let me know. I would really like to improve the stuff.

**Comment by mwelters** [comment]
> We **cannot** do a _composer install / update_. Or if we do, composer will install everything and then we have to apply **manual** changes on the libraries.

So if I understand right, the packages are modified, is this why we cannot use composer ? I hope only at some rare places...
And we dont use the composer autoloader if I understand right... but some modules load extensions. 

While looking around, I started collecting Information and already pushed to my branch, maybe it will get to the state of ready-for-merge... but cleaning up everything is really a nightmare

**Comment by laudeco** [comment]
hello @mwelters 

I totally agree with you ! Fixing this is really a nightmare !
But after the response of @eldy to the mailing list (cf below) I understand a bit more and I have an idea. I'll try to implement it this week.

> Currently we are not using composer for Dolibarr.
We made experiment with it but it brings a lot of troubles (autoload create
a lot of conflicts with other external modules that use autoload to to load
other librairi version, it install 80% of files that we do not use/need, it
needs to maintain another tool).
Currently we prefer to promote a more universal solution, based on "git
clone" to deploy/upgrade an install/version.

If you have any proposal, let me know :-)
