### ISSUE TITLE
sqlfilters doesn't work with OR operator

### ISSUE THREAD

**Issue by NicolasDEVOUGE** [Dolibarr/dolibarr#10412]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 7.0.2
- **OS**: Ubuntu 16.04.2 LTS
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: PHP 7.0.22-0ubuntu0.16.04.1
- **Database**: 10.1.26-MariaDB
- **URL(s)**: http://dolibarr.econcept.local/api/index.php/proposals

## Expected and actual behavior
In api explorer, I want to list the proposals wich have status 0 or 1 (draft or open), but only one of this status are listed, not the second.

## Steps to reproduce the behavior
USe the Api explorer, with this settings in proposals section : 

                "sortfield" => "t.rowid",
                "sortorder" => "ASC",
                "limit" => "10",
                "mode" => "1",
                "sqlfilters" => "(t.fk_statut:=:1) or (t.fk_statut:=:0)"

I have tried with OR or, same problem.

**Comment by ghost** [comment]
Did you try "t.fk_status IN (0,1)"

**Comment by JonBendtsen** [comment]
I tried both (t.date_creation IN (1696797788) + (t.date_creation IS (1696797788) results in     "message": "Bad Request: Error when validating parameter sqlfilters -> Bad syntax of the search string"


(t.date_creation:>:1696797786) and (t.date_creation:<:1696797790) results in     "message": "Not Found: No order found"
where as just having the first part (t.date_creation:>:1696797786) does give me the order I want
