### ISSUE TITLE
Faille XSS in viewimage.php ?

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#10452]
On Dolibarr 7 and 8, It is possible to transmit tags and scripts in viewimage.php

Exemple :
viewimage.php?cache=1&modulepart=mycompany&file=%3C%2Fscript%3E%3C%2FTITLE%3E%3C%2FHEAD%3E%3C%2Ftextarea%3E--%3E%3Cscript%3Ealert%28123%29%3C%2Fscript%3E%3C%21--

For block 
Line 105 on my 7.0.5. 
// Security: Delete string ../ into $original_file
$original_file = str_replace("../","/", $original_file);
//Add by Philazerty for block XSS
$original_file = strip_tags($original_file);

**Comment by eldy** [comment]
Fixed by 6121771c5fa26ecde705c091424f20aae44cb2b8
