### ISSUE TITLE
Bug: 8.0.2 Recurrent Invoice with a document model selected (Crabe or any other)

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#10453]
# Bug

## Environment
- **Version**: 8.0.2
- **OS**: Linux
- **Web server**: nginx/1.13.3
- **PHP**: fpm-fcgi 7.0.30
- **Database**: MySQL or MariaDB 5.5.5-10.3.7-MariaDB
- **URL**: /cron/list.php?&search_status=-2&contextpage=cronjoblist&sortfield=t.status,t.priority&sortorder=DESC,ASC

## Report

Point 2 could be a third party issue, but I added as additional info, maybe @SylvainLegrand can help or is just a core bug. Didn´t test if it is solved in later versions than 8.0.2.

1. Recurrent invoices. When any invoice template has selected a document model, CRABE or any other, (there is a drop-down where you can set it), this recurrent invoice will no more be run again, so the drop-down must always be blank.

2. In some cases, when using a third party document model like InfraSPackPlus 8.0.2, there is also an error for a folder that doesnt exists at root directory:
/**questionnaire**/core/modules/facture/doc/pdf_InfraSPlus-F.modules.php

**Comment by SylvainLegrand** [comment]
Hi,

One of my client found a similar problem : v8.0.4
With automatic document generation : when you want to make a payment for more than one invoice.
An error occure : the model file path wasn't found, but the path included a folder that doesn't exist anymore : "pdfevolution".

After more tests : if we switch off the automatic generation for PDF : no more problems.
If the last model used by hand to generate the document was correct : no more problems.
It's seem like Dolibarr write the last path file used to generate a PDF even if the module change or was switch off.

Greetings,
Sylvain Legrand.
