### ISSUE TITLE
Bug: Edit Extrafield Date on modul ticket 

### ISSUE THREAD

**Issue by sulfurus** [Dolibarr/dolibarr#10455]
# Bug
[*Short description*]

## Environment
- **Version**: 8.0.3 and 8.0.4
- **OS**: Linux hr215338959.reseller.mis.ovh.net 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64
- **Web server**: Apache
- **PHP**: 5.6.39-0+deb8u1
- **Database**: MariaDB 5.5.5-10.0.37-MariaDB-0+deb8u1
- **URL(s)**: ticket/card.php?id=5&action=edit_extras&attribute=timetomarket

## Expected and actual behavior
Edit the extrafield set him to 01/01/1970 or null

## Steps to reproduce the behavior
Create extrafield for module ticket (date or date/hour)
Create ticket, with those extrafield => OK
Edit this field :
- ** Date value is set to 01/01/1970
- ** Date/hour is null

**Comment by ghost** [comment]
The ticket module was into experimental state until dolibarr 10. I've juste test on Dolibarr develop branch (aka futur dolibarr 10) and it's works now
