### ISSUE TITLE
Bug: no invoice numbers in the listing

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#10464]
# Bug
When we click on the list of invoices, there is a list that appears, with the name of the companies, the date, the amount, ... but not the number
## Environment
- **Version**: 10.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.0.30-0+deb9u1
- **Database**: MySQL or MariaDB 5.5.5-10.1.37-MariaDB-0+deb9u1
- **URL**: /compta/facture/list.php?leftmenu=customers_bills&idmenu=210430

**Comment by atm-maxime** [comment]
Did you try to click on the icon on the top right of the table ? It allows you to choose which columns are displayed. Reopen this issue if needed please.
