### ISSUE TITLE
Bug: Can't Set status in Proposal (ACCEPTED/REFUSED)

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#10486]
# Bug
Hi, I can't set the status in the "Set accepted/refused" toolbox, The drop-down menu is not proposed to me
![setacceptedrefusedtoolbox](https://user-images.githubusercontent.com/8665615/52176769-b030d700-27b7-11e9-8885-ae07fa031dff.PNG)

## Environment
- **Version**: 10.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.0.33-0+deb9u1
- **Database**: MySQL or MariaDB 5.5.5-10.1.37-MariaDB-0+deb9u1
- **URL**: /comm/propal/card.php?id=2512&action=statut

## Report
I tried the web browsers FireFox, Crhome, IE, Konqueror.

**Comment by ozit** [comment]
Here is the log of the debbug 
[dolibarr.log.gz](https://github.com/Dolibarr/dolibarr/files/2831603/dolibarr.log.gz)

**Comment by eldy** [comment]
This version is 10.0, it is a development version not stable.
It has been fixed in develop branch

**Comment by ozit** [comment]
I know it a development version, when I have time, I test :-)
It 's easy to clone a VM and try the upgrade
