### ISSUE TITLE
[BUG-SOLVED] accourancy 9.0.0 - bank journalisation

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#10485]
# Bug
SQL error on bank journalisation

## Environment
- **Version**: 9.0.0 (updated from 8.0.4)
- **OS**: any

## Steps to reproduce the behavior
Just consult Accounting > bank journalisation

Url sollicitée: /accountancy/journal/bankjournal.php?mainmenu=accountancy&leftmenu=accountancy_journal&id_journal=3
Referer: http://x.xxxxx.com/accountancy/journal/purchasesjournal.php?mainmenu=accountancy&leftmenu=accountancy_journal&id_journal=2
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT payfac.fk_facture as id, f.ref as ref FROM llx_paiement_facture as payfac, llx_facture as f WHERE payfac.fk_facture = f.rowid AND payfac.fk_paiement=35
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.ref' in 'field list'

[EDIT to delete URL]

**Comment by atm-maxime** [comment]
Hey. Odd, that's because the facnumber column has been renamed into ref, but it seems that the renaming was not done on your installation. You must have plenty of errors... Can you try the upgrade again ?

**Comment by Arre8** [comment]
Hi,
I've tried to copy a fully fonctionnal 8.04 and then update to 9.0.0 :
no error on update process.

but still the same SQL error on bank journalisation.

I look in bankjournal.php on a fresh downloaded 9.0.0 and there is this SQL request : (line 1225)
		$sqlmid = 'SELECT payfac.fk_facture as id, f.ref as ref';
		$sqlmid .= " FROM ".MAIN_DB_PREFIX."paiement_facture as payfac, ".MAIN_DB_PREFIX."facture as f";
		$sqlmid .= " WHERE payfac.fk_facture = f.rowid AND payfac.fk_paiement=" . $val["paymentid"];
		$ref = $langs->transnoentitiesnoconv("Invoice");

"f.ref as ref" should be "f.facnumber as ref" ?

llx_facture 8.0.4 and llx_facture 9.0.0 are the same (exept two added field "module_source" and "pos_source")

nb : i do not have any error on consulting, creating or editing invoice.

**Comment by mwelters** [comment]
Maybe dumb hint, but:

You did run the /install migration webpage after upgrading ?

**Comment by Arre8** [comment]
no, i didn't run /install after upgrading.

After your post, to see what happen : i've tried -> no change, still the same error.

I'm not the only one to report this problem : 
https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/63592-v-9-00-erreur-ventilation-journal-treso

**Comment by mwelters** [comment]
Then the migration didnt run, weird. Check the table structure of llx_facture and change acccording to this sql:

ALTER TABLE llx_facture DROP INDEX idx_facture_uk_facnumber;
ALTER TABLE llx_facture CHANGE facnumber ref VARCHAR(30) NOT NULL;
ALTER TABLE llx_facture ADD UNIQUE INDEX uk_facture_ref (ref, entity);

If you walked through the /install wizard, it should have changed db structur thought....

**Comment by Arre8** [comment]
ok... it seems to resolve the previous error (on bank journalisation)

BUT now i've got new errors when attemping to access to invoice : 

Url sollicitée: /compta/index.php?mainmenu=billing&leftmenu=
Referer: http://x.xxxxx.com/compta/facture/card.php?action=create&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT f.facnumber, f.rowid, f.total as total_ht, f.tva as total_tva, f.total_ttc, f.ref_client, f.type, s.nom as name, s.rowid as socid, s.email, s.code_client, s.code_compta, s.code_fournisseur, s.code_compta_fournisseur FROM llx_facture as f, llx_societe as s WHERE s.rowid = f.fk_soc AND f.fk_statut = 0 AND f.entity = 1
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.facnumber' in 'field list'

OR when attemping to creat new invoice : 

Url sollicitée: /compta/facture/list.php?leftmenu=customers_bills
Referer: http://x.xxxxx.com/compta/facture/card.php?action=create&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT f.rowid as id, f.facnumber as ref, f.ref_client, f.type, f.note_private, f.note_public, f.increment, f.fk_mode_reglement, f.total as total_ht, f.tva as total_vat, f.total_ttc, f.localtax1 as total_localtax1, f.localtax2 as total_localtax2, f.datef as df, f.date_lim_reglement as datelimite, f.paye as paye, f.fk_statut, f.datec as date_creation, f.tms as date_update, s.rowid as socid, s.nom as name, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta as code_compta_client, s.code_compta_fournisseur, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, country.code as country_code, p.rowid as project_id, p.ref as project_ref, p.title as project_label, SUM(pf.amount) as dynamount_payed FROM llx_societe as s LEFT JOIN llx_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN llx_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN llx_c_departements as state on (state.rowid = s.fk_departement), llx_facture as f LEFT JOIN llx_paiement_facture as pf ON pf.fk_facture = f.rowid LEFT JOIN llx_projet as p ON p.rowid = f.fk_projet WHERE f.fk_soc = s.rowid AND f.entity IN (1) GROUP BY f.rowid, f.facnumber, ref_client, f.type, f.note_private, f.note_public, f.increment, f.fk_mode_reglement, f.total, f.tva, f.total_ttc, f.localtax1, f.localtax2, f.datef, f.date_lim_reglement, f.paye, f.fk_statut, f.datec, f.tms, s.rowid, s.nom, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta, s.code_compta_fournisseur, typent.code, state.code_departement, state.nom, country.code, p.rowid, p.ref, p.title ORDER BY f.datef DESC, f.rowid DESC LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.facnumber' in 'field list'

[EDIT to delete URL]

**Comment by mwelters** [comment]
I am quite sure your files are mixed. This is 8.0.4 query not 9.x - it still references facnumber.
Please double check your files are consistent, maybe you didnt overwrite everything with the new version while upgrading.

**Comment by Arre8** [comment]
I've tried a new upgrade (for the 3rd time).

to be sure, i have keeped only the database:

- download the 9.0.0 from sourceforge (https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/9.0.0/)
- duplicate the database (8.0.4)
- upload the 9.0.0 files into a new folder (not overwriting the 8.0.4)
- create the conf.php from the example 9.0.0 (not copying the old 8.0.4)
- rename the install.lock -> install.lock.tmp
- run /install -> no error
- rename the install.lock.tmp -> install.lock
 
and still have the same error :

Url sollicitée: /accountancy/journal/bankjournal.php?mainmenu=accountancy&leftmenu=accountancy_journal&id_journal=3
Referer: http://x.xxxxx.com/accountancy/index.php?mainmenu=accountancy&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT payfac.fk_facture as id, f.ref as ref FROM llx_paiement_facture as payfac, llx_facture as f WHERE payfac.fk_facture = f.rowid AND payfac.fk_paiement=38
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.ref' in 'field list'

Here are the requests during the upload : there's no update for a field "ref" in llx_facture.

Choix du script de migration	8.0.0-9.0.0.sql
Request 1 sql='ALTER TABLE llx_contrat_extrafields ADD INDEX idx_contrat_extrafields (fk_object);'
Request 2 sql='ALTER TABLE llx_facture_rec_extrafields ADD INDEX idx_facture_rec_extrafields (fk_object);'
Request 3 sql='ALTER TABLE llx_accounting_account DROP FOREIGN KEY fk_accounting_account_fk_pcg_version;'
Request 4 sql='ALTER TABLE llx_accounting_account MODIFY COLUMN fk_pcg_version varchar(32) NOT NULL;'
Request 5 sql='ALTER TABLE llx_accounting_system MODIFY COLUMN pcg_version varchar(32) NOT NULL;'
Request 6 sql='ALTER TABLE llx_accounting_account ADD CONSTRAINT fk_accounting_account_fk_pcg_version FOREIGN KEY (fk_pcg_version) REFERENCES llx_accounting_system (pcg_version);'
Request 7 sql='ALTER TABLE llx_facture ADD COLUMN module_source varchar(32);'
Request 8 sql='ALTER TABLE llx_facture ADD COLUMN pos_source varchar(32);'
Request 9 sql='create table llx_facture_rec_extrafields(rowid integer AUTO_INCREMENT PRIMARY KEY,tms timestamp,fk_object integer NOT NULL,import_key varchar(14)) ENGINE=innodb;'
Request 10 sql='ALTER TABLE llx_extrafields ADD COLUMN help text NULL;'
Request 11 sql='ALTER TABLE llx_extrafields ADD COLUMN totalizable boolean DEFAULT FALSE after list;'
Request 12 sql='ALTER TABLE llx_product_fournisseur_price ADD COLUMN desc_fourn text after ref_fourn;'
Request 13 sql='ALTER TABLE llx_user ADD COLUMN dateemploymentend date after dateemployment;'
Request 14 sql='ALTER TABLE llx_stock_mouvement ADD COLUMN fk_project integer;'
Request 15 sql='ALTER TABLE llx_c_action_trigger MODIFY COLUMN elementtype varchar(32);'
Request 16 sql='ALTER TABLE llx_c_field_list ADD COLUMN visible tinyint	DEFAULT 1 NOT NULL AFTER search;'
Request 17 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('COMPANY_DELETE','Third party deleted','Executed when you delete third party','societe',1);'
Request 18 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('PROPAL_DELETE','Customer proposal deleted','Executed when a customer proposal is deleted','propal',2);'
Request 19 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('ORDER_DELETE','Customer order deleted','Executed when a customer order is deleted','commande',5);'
Request 20 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('BILL_DELETE','Customer invoice deleted','Executed when a customer invoice is deleted','facture',9);'
Request 21 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('PROPOSAL_SUPPLIER_DELETE','Price request deleted','Executed when a customer proposal delete','proposal_supplier',10);'
Request 22 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('ORDER_SUPPLIER_DELETE','Supplier order deleted','Executed when a supplier order is deleted','order_supplier',14);'
Request 23 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('BILL_SUPPLIER_DELETE','Supplier invoice deleted','Executed when a supplier invoice is deleted','invoice_supplier',17);'
Request 24 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('CONTRACT_DELETE','Contract deleted','Executed when a contract is deleted','contrat',18);'
Request 25 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('FICHINTER_DELETE','Intervention is deleted','Executed when a intervention is deleted','ficheinter',35);'
Request 26 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('EXPENSE_DELETE','Expense report deleted','Executed when an expense report is deleted','expensereport',204);'
Request 27 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('HOLIDAY_VALIDATE','Expense report validated','Executed when an expense report is validated','expensereport',202);'
Request 28 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('HOLIDAY_APPROVE','Expense report approved','Executed when an expense report is approved','expensereport',203);'
Request 29 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8001', 'Aktieselvskab A/S');'
Request 30 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8002', 'Anparts Selvskab ApS');'
Request 31 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8003', 'Personlig ejet selvskab');'
Request 32 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8004', 'Iværksætterselvskab IVS');'
Request 33 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8005', 'Interessentskab I/S');'
Request 34 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8006', 'Holdingselskab');'
Request 35 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8007', 'Selskab Med Begrænset Hæftelse SMBA');'
Request 36 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8008', 'Kommanditselskab K/S');'
Request 37 sql='INSERT INTO llx_c_forme_juridique (fk_pays, code, libelle) VALUES (80, '8009', 'SPE-selskab');'
Request 38 sql='ALTER TABLE llx_payment_salary ADD COLUMN ref varchar(30) NULL after rowid;'
Request 39 sql='ALTER TABLE llx_payment_salary ADD COLUMN fk_projet integer DEFAULT NULL after amount;'
Request 40 sql='ALTER TABLE llx_payment_various ADD COLUMN ref varchar(30) NULL after rowid;'
Request 41 sql='ALTER TABLE llx_categorie ADD COLUMN ref_ext varchar(255);'
Request 42 sql='ALTER TABLE llx_paiement ADD COLUMN ext_payment_id varchar(128);'
Request 43 sql='ALTER TABLE llx_paiement ADD COLUMN ext_payment_site varchar(128);'
Request 44 sql='ALTER TABLE llx_societe ADD COLUMN twitter varchar(255) after skype;'
Request 45 sql='ALTER TABLE llx_societe ADD COLUMN facebook varchar(255) after skype;'
Request 46 sql='ALTER TABLE llx_societe ADD COLUMN instagram varchar(255) after skype;'
Request 47 sql='ALTER TABLE llx_societe ADD COLUMN snapchat varchar(255) after skype;'
Request 48 sql='ALTER TABLE llx_societe ADD COLUMN googleplus varchar(255) after skype;'
Request 49 sql='ALTER TABLE llx_societe ADD COLUMN youtube varchar(255) after skype;'
Request 50 sql='ALTER TABLE llx_societe ADD COLUMN whatsapp varchar(255) after skype;'
Request 51 sql='ALTER TABLE llx_socpeople ADD COLUMN twitter varchar(255) after skype;'
Request 52 sql='ALTER TABLE llx_socpeople ADD COLUMN facebook varchar(255) after skype;'
Request 53 sql='ALTER TABLE llx_socpeople ADD COLUMN instagram varchar(255) after skype;'
Request 54 sql='ALTER TABLE llx_socpeople ADD COLUMN snapchat varchar(255) after skype;'
Request 55 sql='ALTER TABLE llx_socpeople ADD COLUMN googleplus varchar(255) after skype;'
Request 56 sql='ALTER TABLE llx_socpeople ADD COLUMN youtube varchar(255) after skype;'
Request 57 sql='ALTER TABLE llx_socpeople ADD COLUMN whatsapp varchar(255) after skype;'
Request 58 sql='ALTER TABLE llx_adherent ADD COLUMN skype varchar(255);'
Request 59 sql='ALTER TABLE llx_adherent ADD COLUMN twitter varchar(255);'
Request 60 sql='ALTER TABLE llx_adherent ADD COLUMN facebook varchar(255);'
Request 61 sql='ALTER TABLE llx_adherent ADD COLUMN instagram varchar(255);'
Request 62 sql='ALTER TABLE llx_adherent ADD COLUMN snapchat varchar(255);'
Request 63 sql='ALTER TABLE llx_adherent ADD COLUMN googleplus varchar(255);'
Request 64 sql='ALTER TABLE llx_adherent ADD COLUMN youtube varchar(255);'
Request 65 sql='ALTER TABLE llx_adherent ADD COLUMN whatsapp varchar(255);'
Request 66 sql='ALTER TABLE llx_user ADD COLUMN skype varchar(255);'
Request 67 sql='ALTER TABLE llx_user ADD COLUMN twitter varchar(255);'
Request 68 sql='ALTER TABLE llx_user ADD COLUMN facebook varchar(255);'
Request 69 sql='ALTER TABLE llx_user ADD COLUMN instagram varchar(255);'
Request 70 sql='ALTER TABLE llx_user ADD COLUMN snapchat varchar(255);'
Request 71 sql='ALTER TABLE llx_user ADD COLUMN googleplus varchar(255);'
Request 72 sql='ALTER TABLE llx_user ADD COLUMN youtube varchar(255);'
Request 73 sql='ALTER TABLE llx_user ADD COLUMN whatsapp varchar(255);'
Request 74 sql='ALTER TABLE llx_website CHANGE COLUMN fk_user_create fk_user_creat integer;'
Request 75 sql='ALTER TABLE llx_website_page CHANGE COLUMN fk_user_create fk_user_creat integer;'
Request 76 sql='ALTER TABLE llx_website ADD COLUMN maincolor varchar(16);'
Request 77 sql='ALTER TABLE llx_website ADD COLUMN maincolorbis varchar(16);'
Request 78 sql='ALTER TABLE llx_website_page ADD COLUMN image varchar(255);'
Request 79 sql='CREATE TABLE llx_takepos_floor_tables(rowid integer AUTO_INCREMENT PRIMARY KEY,entity integer DEFAULT 1 NOT NULL,label varchar(255),leftpos float,toppos float,floor smallint) ENGINE=innodb;'
Request 80 sql='UPDATE llx_c_payment_term SET decalage = nbjour, nbjour = 0 where decalage IS NULL AND type_cdr = 2;'
Request 81 sql='UPDATE llx_holiday SET ref = rowid WHERE ref IS NULL;'
Request 82 sql='CREATE TABLE llx_emailcollector_emailcollector(rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,entity integer DEFAULT 1 NOT NULL,ref varchar(128) NOT NULL,label varchar(255),description text,host varchar(255),login varchar(128),password varchar(128),source_directory varchar(255) NOT NULL,target_directory varchar(255),datelastresult datetime,codelastresult varchar(16),lastresult varchar(255),note_public text,note_private text,date_creation datetime NOT NULL,tms timestamp NOT NULL,fk_user_creat integer NOT NULL,fk_user_modif integer,import_key varchar(14),status integer NOT NULL) ENGINE=innodb;'
Request 83 sql='ALTER TABLE llx_emailcollector_emailcollector ADD COLUMN login varchar(128);'
Request 84 sql='ALTER TABLE llx_emailcollector_emailcollector ADD INDEX idx_emailcollector_entity (entity);'
Request 85 sql='ALTER TABLE llx_emailcollector_emailcollector ADD INDEX idx_emailcollector_status (status);'
Request 86 sql='CREATE TABLE llx_emailcollector_emailcollectorfilter(rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,fk_emailcollector INTEGER NOT NULL,type varchar(128) NOT NULL,rulevalue varchar(255) NULL,date_creation datetime NOT NULL,tms timestamp NOT NULL,fk_user_creat integer NOT NULL,fk_user_modif integer,import_key varchar(14),status integer NOT NULL) ENGINE=innodb;'
Request 87 sql='CREATE TABLE llx_emailcollector_emailcollectoraction(rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,fk_emailcollector INTEGER NOT NULL,type varchar(128) NOT NULL,actionparam varchar(255) NULL,date_creation datetime NOT NULL,tms timestamp NOT NULL,fk_user_creat integer NOT NULL,fk_user_modif integer,position integer DEFAULT 0,import_key varchar(14),status integer NOT NULL) ENGINE=innodb;'
Request 88 sql='ALTER TABLE llx_emailcollector_emailcollectorfilter ADD INDEX idx_emailcollector_fk_emailcollector (fk_emailcollector);'
Request 89 sql='ALTER TABLE llx_emailcollector_emailcollectorfilter ADD CONSTRAINT fk_emailcollectorfilter_fk_emailcollector FOREIGN KEY (fk_emailcollector) REFERENCES llx_emailcollector_emailcollector(rowid);'
Request 90 sql='ALTER TABLE llx_emailcollector_emailcollectoraction ADD INDEX idx_emailcollector_fk_emailcollector (fk_emailcollector);'
Request 91 sql='ALTER TABLE llx_emailcollector_emailcollectoraction ADD CONSTRAINT fk_emailcollectoraction_fk_emailcollector FOREIGN KEY (fk_emailcollector) REFERENCES llx_emailcollector_emailcollector(rowid);'
Request 92 sql='ALTER TABLE llx_emailcollector_emailcollectorfilter ADD UNIQUE INDEX uk_emailcollector_emailcollectorfilter (fk_emailcollector, type, rulevalue);'
Request 93 sql='ALTER TABLE llx_emailcollector_emailcollectoraction ADD UNIQUE INDEX uk_emailcollector_emailcollectoraction (fk_emailcollector, type);'
Request 94 sql='ALTER TABLE llx_societe_rib ADD COLUMN comment varchar(255);'
Request 95 sql='ALTER TABLE llx_societe_rib ADD COLUMN ipaddress varchar(68);'
Request 96 sql='DROP TABLE llx_ticket_logs;'
Request 97 sql='CREATE TABLE llx_pos_cash_fence(rowid INTEGER AUTO_INCREMENT PRIMARY KEY,entity INTEGER DEFAULT 1 NOT NULL,ref VARCHAR(64),label VARCHAR(255),opening double(24,8) default 0,cash double(24,8) default 0,card double(24,8) default 0,cheque double(24,8) default 0,status INTEGER,date_creation DATETIME NOT NULL,date_valid DATETIME,day_close INTEGER,month_close INTEGER,year_close INTEGER,posmodule VARCHAR(30),posnumber VARCHAR(30),fk_user_creat integer,fk_user_valid integer,tms TIMESTAMP NOT NULL,import_key VARCHAR(14)) ENGINE=innodb;'
Request 98 sql='ALTER TABLE llx_accounting_account MODIFY COLUMN account_number varchar(32) NOT NULL;'
Exécution du script	OK

[EDIT to delete URL]

**Comment by mwelters** [comment]
You are right. The migration is missing for 8->9 
I'll prepare a pull request...

**Comment by mwelters** [comment]
Till eldy merges the commit, you can execute the following sql (you know, just for reference):

ALTER TABLE llx_facture DROP INDEX idx_facture_uk_facnumber;
ALTER TABLE llx_facture CHANGE facnumber ref VARCHAR(30) NOT NULL;
ALTER TABLE llx_facture ADD UNIQUE INDEX uk_facture_ref (ref, entity);

**Comment by Arre8** [comment]
i think you're wrong : 
if i execute your request : invoice list, invoice creation, invoice edition, invoice widget doesn't work any more.

**Comment by Arre8** [comment]
eldy has just posted a FIX : 

the database and the update process are ok (the field facnumber in llx_facture has not been renamed in 9.0.0)
you have only to correct accurancy scripts

https://github.com/Dolibarr/dolibarr/commit/456e78b7cfd15f71376abe7cfbeb45c9aaaafa9d

**Comment by atm-maxime** [comment]
Yes sorry, facnumber becomes ref in 10.0. this was a mistake in accountancy
