### ISSUE TITLE
3 mails with all invoices sent instead of 1 when sending 3 invoices from list

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#10499]
## Issue
I selected 3 invoices to be sent to the customer from the url "dolibarr/compta/facture/list.php" .
I selected the action to send the by email (top of the center of the page).
The page dolibarr/compta/facture/list.php opens again with the possibility to enter the body of the email.  At the bottom of the page the 3 invoices are still listed and selected.
So far so good.

After clicking "Send mail", a popup quickly shows a message I did not have the time to read with at least "9" in it.  And I received 3 mails, each with all 3 selected invoices.

## Expected behavior: 
Send only 1 mail with the 3 invoices as attachment.

## Correction to be made: send only 1 email, the attachements are ok.

Dolibarr version: 8.0.4 .

**Comment by mdeweerd** [comment]
Still a valid request. Commenting to keep this open.

**Comment by atm-maxime** [comment]
Hi. Did you try to reproduce with newer version?

**Comment by eldy** [comment]
Issues seems fixed with v11, so kept closed
