### ISSUE TITLE
Validation error on dictionary changes. 

### ISSUE THREAD

**Issue by finalbeta** [Dolibarr/dolibarr#10495]
# Bug
Form validation too strict on validating dictionary changes. 

## Environment
- **Version**: 8.0.3
- **OS**: Debian last stable
- **Web server**: apache
- **PHP**: 7.1
- **Database**: MySQL
- **URL(s)**: /dolibarr/admin/dict.php?id=12

## Expected and actual behavior
I want to edit the default value/sort order of payment terms. 
This can be done under Dictionaries - "Payment terms".
If should be possible to change the order values and save the row on URL /dolibarr/admin/dict.php?id=12

![image](https://user-images.githubusercontent.com/22134261/52210176-7e3a7600-2886-11e9-860e-6fcb2bca3ee8.png)
However, when saving you get an error the the name and label is required: 
![image](https://user-images.githubusercontent.com/22134261/52210198-901c1900-2886-11e9-9def-7027880f4e9c.png)

However, this is not logical since you cannot edit those two fields on this screen.  So It's impossible to change the information. 

PS: I changed what I needed by a direct DB edit (this is not a support request)

**Comment by TonchoTonchev** [comment]
I can reproduce this issue also with the current version 9.0.3. Confirm. @eldy
