### ISSUE TITLE
FEATURE - Customer account statement

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#10500]
# Feature Request
Customers sometimes as for an account statement for a given period.
They have given several reasons for this:

- The accountant asks for it;
- They want a list to be able to check their internal accounting because there is a difference;
- Other reasons I do not know.

As explained in https://www.dolibarr.fr/forum/12-howto--aide/60332-releve-et-solde-client , it is possible to print some kind of status from the list, but this does not show the VAT value nor the payment history and the final amount due.

It would be nice to be able to get an account statement for the customer (and why not likewise for a supplier).

In french we would call this a "Relevé de compte".

It exists in several other softwares:
https://debitoor.fr/blog/les-releves-de-compte-client-sur-debitoor
http://www.pme-gestion.fr/modele-lettre/modele-facture-proforma/releve-compte-client.html
https://help.sageone.com/fr_ca/accounting/extra-customer-statement.html
https://www.lineosoft.fr/documentations/le-manager/148-relance-client-et-releves-de-compte

**Comment by mdeweerd** [comment]
Still a valid request. Commenting to keep this open.

**Comment by atm-maxime** [comment]
Something like that https://www.dolistore.com/fr/modules/1195-Extrait-compte-client.html?search_query=Open-dsi&results=25 ?

**Comment by mdeweerd** [comment]
Seems to correspond.
