### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ludotechit** [Dolibarr/dolibarr#10516]
# Bug

## Environment
- **Version**: 9.0.0
- **OS**: Windows NT
- **Web server**: Apache/2.4.27 (Win64) PHP/7.1.9
- **PHP**: apache2handler 7.1.9
- **Database**: MySQL or MariaDB 5.7.19
- **URL**: /dolibarr/htdocs/comm/propal/card.php?id=1366&action=presend&mode=init

## Report

Warning: html_entity_decode() expects parameter 1 to be string, array given in C:\wamp64\www\dolibarr\htdocs\core\lib\functions.lib.php on line 5617

Warning: html_entity_decode() expects parameter 1 to be string, array given in C:\wamp64\www\dolibarr\htdocs\core\lib\functions.lib.php on line 5617

Recoverable fatal error: Object of class PropaleLigne could not be converted to string in C:\wamp64\www\dolibarr\htdocs\core\lib\functions.lib.php on line 5390

**Comment by ludotechit** [comment]
error in send mail in dolibarr still 8.0 and 9.0

**Comment by ksar-ksar** [comment]
SAme here : https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/63681-9-0-0-envoi-de-facture-par-mail

**Comment by atm-maxime** [comment]
Seems fixed to me in 8.0.6
