### ISSUE TITLE
Bug: Aucun affichage sur la page d'accueil après MAJ

### ISSUE THREAD

**Issue by andreors** [Dolibarr/dolibarr#10519]
# Bug

## Environment
- **Version**: 9.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.0.33
- **Database**: MySQL or MariaDB 5.5.62-0ubuntu0.14.04.1
- **URL**: /htdocs/index.php?mainmenu=home&leftmenu=home

**Comment by atm-maxime** [comment]
Please send your report in english and give us some extra infos...
