### ISSUE TITLE
Can't validate member registration if confirmation email is checked

### ISSUE THREAD

**Issue by michel-thomas** [Dolibarr/dolibarr#10513]
# Bug
After creating a member, I try to validate from Draft.

If I check ``Sending information email to member``, then I get the error message in red ``Mandatory setup parameters are not yet defined``.
If I don't check, validation is ok.

I control email parameters in different ways (send email from member card, test sending from Emails setup in configuration) and all is ok.

This problem appears after Dolibarr upgrade from 7.0.1 to 8.0.4. It was working in 7 version.

## Environment
- **Version**: 8.0.4
- **OS**: Debian 9.7
- **Web server**: Apache 2.4.25
- **PHP**: 7.0.33
- **Database**: MariaDB 10.1.37
- **URL(s)**: /adherents/list.php?leftmenu=members&statut=-1

**Comment by michel-thomas** [comment]
The problem was default template selection in "Configuration > Modules/Applications > Adhérents > Email".
None was selected anymore, assigning to each use case solve the problem.

**Comment by HugoPoi** [comment]
Thanks you a lot for the settings, I was goiing crazy finding this one !
