### ISSUE TITLE
Bug: Onglet commercial inaccessible

### ISSUE THREAD

**Issue by andreors** [Dolibarr/dolibarr#10524]
# Bug

## Environment
- **Version**: 9.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.0.33
- **Database**: MySQL or MariaDB 5.5.62-0ubuntu0.14.04.1
- **URL**: /htdocs/compta/index.php?mainmenu=billing&leftmenu=

**Comment by atm-maxime** [comment]
Please send your report in english and give us some extra infos...
