### ISSUE TITLE
CSS Class TabBarWithBottom is unsetting background color

### ISSUE THREAD

**Issue by atm-quentin** [Dolibarr/dolibarr#10531]
# Bug TabBarWithBottom is unsetting background color in 8.0

Why unset background color of this class ?

![image](https://user-images.githubusercontent.com/21307529/52472832-9cf58100-2b94-11e9-94d2-ae4a018afa22.png)

With only TabBar
![image](https://user-images.githubusercontent.com/21307529/52473113-4d638500-2b95-11e9-8fcf-353d318add6a.png)

With TabBar and TabBarWithBottom
![image](https://user-images.githubusercontent.com/21307529/52473065-2a38d580-2b95-11e9-92c1-b29312bad913.png)

**Comment by eldy** [comment]
This css is used for lines under a tab (for exemple to list all properties of a thirdparty under tab "Customer". And we want all properties of tab with white background. May be this is the reason but it is difficult to remember. css is modified version by version to fix each strange behaviour, one by one...
