### ISSUE TITLE
Problème affichage des rapports (comptabilité

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#10540]
La partie rapport comptable me donne l'erreur suivante : 

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20190210074251
Dolibarr: 9.0.0
Niveau de fonctionnalités: 0
PHP: 7.0.33-0+deb9u1
Server: Apache/2.4.25 (Debian)
OS: Linux ieb2 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

Url sollicitée: /compta/resultat/index.php
Referer: https://dolibarrtest.perso.net/compta/resultat/index.php?mainmenu=accountancy&leftmenu=accountancy_report
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT b.doc_ref, b.numero_compte, b.subledger_account, b.subledger_label, pcg_type, date_format(b.doc_date,'%Y-%m') as dm, sum(b.debit) as debit, sum(b.credit) as credit, sum(b.montant) as amount FROM llx_accounting_bookkeeping as b, llx_accounting_account as aa WHERE b.numero_compte = aa.account_number AND b.entity = 1 AND ( (pcg_type = 'EXPENSE') OR (pcg_type = 'INCOME')) AND fk_pcg_version = 'PCG99-BASE' AND b.doc_date >= '2015-07-01 00:00:00' AND b.doc_date <= '2019-06-30 23:59:59' GROUP BY b.doc_ref, b.numero_compte, b.subledger_account, b.subledger_label, pcg_type, dm
Code retour dernier accès en base en erreur: DB_ERROR_1267
Information sur le dernier accès en base en erreur: Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='

**Comment by ksar-ksar** [comment]
https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/61236-illegal-mix-of-collations-utf8-unicode-ci-implici#101369

**Comment by ghost** [comment]
Merci, c'est réglé
