### ISSUE TITLE
Transifex: Missing string in en_US/main.lang  (and translated)

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#10549]
The String for "Connection" in main.lang is missing in Transifex en_US and translations

In Github it exists in en_US and (for example) de_DE

For German I wanted to change it from 
"Connection=Benutzername" to 
"Connection=Anmelden" 

for the Login Form (it is used also in cashdesh and user/class/user.class.php in getNomUrl())

**Comment by eldy** [comment]
the string Connection=Login is available into main.lang resorce fo en_US language file.
So you should find it to into transifex.

**Comment by mwelters** [comment]
Sorry, I cannot find it...

![image](https://user-images.githubusercontent.com/11374733/52866946-0c90e080-3140-11e9-86ee-f003c8346555.png)

**Comment by mwelters** [comment]
Sorry, sometimes this Transifex Thingie is a little difficult in searching and finding things... found it
