### ISSUE TITLE
Bug sur journal de banque

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#10544]
Dolibarr a détecté une erreur technique.
You use an experimental or develop level of features, so please do NOT report any bugs, except if problem is confirmed moving option MAIN_FEATURES_LEVEL back to 0.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20190210155931
Dolibarr: 9.0.0
Niveau de fonctionnalités: 2
PHP: 7.0.33-0+deb9u1
Server: Apache/2.4.25 (Debian)
OS: Linux ieb5 4.9.124-xxxx-std-ipv6-64 #346072 SMP Wed Aug 29 07:53:57 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

Url sollicitée: /accountancy/journal/bankjournal.php?id_journal=3
Referer: https://dolibarr.bouddhismes.net/accountancy/journal/bankjournal.php?mainmenu=accountancy&leftmenu=accountancy_journal&id_journal=3
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT payfac.fk_facture as id, f.ref as ref FROM llx_paiement_facture as payfac, llx_facture as f WHERE payfac.fk_facture = f.rowid AND payfac.fk_paiement=1479
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.ref' in 'field list'

**Comment by atm-maxime** [comment]
I think you have a mistake in your Dolibarr files. The facnumber column has been replaced in develop version, not 9.0. Check your php file accountancy/journal/bankjournal.php, I think you don't have the one from the 9.0 package
