### ISSUE TITLE
Contacts and event

### ISSUE THREAD

**Issue by superlamparas** [Dolibarr/dolibarr#10556]
# Bug
When adding a contact with not associated third party, and then viewing the Events/Agenda, all the Events for the user that created the contact are displayed.

## Environment
- 9.0.0
- Linux
- Apache 
- MySQL

Do this...
1.  Create a contact with no associated Third Party  at 
   /htdocs/contact/card.php?leftmenu=contacts&action=create
2.  Once created go to the Events/Agenda link
  /htdocs/contact/agenda.php?id=1

Result... 
It will display all events related to the user that is creating the Contact.  

I guess it should display no events for the new Contact that just have been created.

**Comment by atm-maxime** [comment]
Seems fixed in 9.0.5
