### ISSUE TITLE
BUG: Adherent and MailmanSpip

### ISSUE THREAD

**Issue by Toumaniere** [Dolibarr/dolibarr#10551]
# Bug
Problem occurs with module Adherent and MailmanSpip, the subscription and unsubscription doesn't work properly.

## Environment
- **Version**: 9.0.1
- **OS**: Debian Stretch
- **Web server**: 2.4.25
- **PHP**: 7.0.33-0
- **Database**: MySQL 15.1
- **URL(s)**: /adherents/card.php?rowid=[*Adherent id*]

### Expected
When I change a type of Adherent, it should change the mailing list of the Adherent (and delete it from the precedent mailing list).

### Actual
When I change a type of Adherent from A to B, the mailing list is set to A.

## Steps to reproduce the behavior
Enable MailmanSpip module.
Create Adherent with a type A.
Change Adherent from type A to B.
Check mailman list members.

## Attached files (Screenshots, screencasts, dolibarr.log, debugging informations…)
My MailmanSpip configuration : 
Register URL : http://163.172.183.44:8081/cgi-bin/mailman/admin/%LISTE%/members/add?subscribees_upload=%EMAIL%&adminpw=%MAILMAN_ADMINPW%&subscribe_or_invite=0&send_welcome_msg_to_this_batch=0&notification_to_list_owner=0

Unsubscribe URL : http://163.172.183.44:8081/cgi-bin/mailman/admin/%LISTE%/members/remove?unsubscribees_upload=%EMAIL%&adminpw=%MAILMAN_ADMINPW%&send_unsub_ack_to_this_batch=0&send_unsub_notifications_to_list_owner=0

List to subscribre : TYPE:Membres:membres,TYPE:Aspirants:aspirants,TYPE:Alumnis:alumni

<img width="317" alt="capture d ecran 2019-02-12 a 09 24 41" src="https://user-images.githubusercontent.com/12683182/52621659-329c5380-2ea8-11e9-86f7-a8a397df82c8.png">

# Bug (French version)
Problème avec le module Adhérent et MailmanSpip.
L'enregistrement dans une mailing list et la suppression d'une mailing list (lorsqu'on change le type de l'adhérent) ne fonctionne pas.

## Environment
- **Version**: 9.0.1
- **OS**: Debian Stretch
- **Web server**: 2.4.25
- **PHP**: 7.0.33-0
- **Database**: MySQL 15.1
- **URL(s)**: /adherents/card.php?rowid=[*Adherent id*]

### Expected
Quand je change le type d'un adhérent de A vers B, l'adhérent est ajouté à la mailing list B et supprimé de la mailing list A.

### Actual
Quand je change le type d'un adhérent de A vers B, l'adhérent est ajouté à la mailing list A (et aucune suppression de l'ancienne mailing list).

## Steps to reproduce the behavior
Activer le module Adhérent et MailmanSpip (et configurer Mailman avec les types A et B).
Créer un type d'adhérent A et B.
Changer le type d'un adhérent de A vers B.
Vérifier les membres de la mailing list.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
My MailmanSpip configuration : 
Register URL : http://163.172.183.44:8081/cgi-bin/mailman/admin/%LISTE%/members/add?subscribees_upload=%EMAIL%&adminpw=%MAILMAN_ADMINPW%&subscribe_or_invite=0&send_welcome_msg_to_this_batch=0&notification_to_list_owner=0

Unsubscribe URL : http://163.172.183.44:8081/cgi-bin/mailman/admin/%LISTE%/members/remove?unsubscribees_upload=%EMAIL%&adminpw=%MAILMAN_ADMINPW%&send_unsub_ack_to_this_batch=0&send_unsub_notifications_to_list_owner=0

List to subscribre : TYPE:Membres:membres,TYPE:Aspirants:aspirants,TYPE:Alumnis:alumni

<img width="317" alt="capture d ecran 2019-02-12 a 09 24 41" src="https://user-images.githubusercontent.com/12683182/52621659-329c5380-2ea8-11e9-86f7-a8a397df82c8.png">

**Comment by jbonlinea** [comment]
Hi @Toumaniere  and @eldy

I've been tryig to use mailman with dolibarr without success for a while now.

**On of my core issue it that the settings I set for mailman are not saved ?!** 
I've recently reported this bug in a post on the [french forum](https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/64961-mailman-module-sauvegarder-les-parametres) and the [english forum](https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/29486-mailman-module-save-settings) (althought I reaize I've been a bit lazy in the english one)

Before that, I've looked for tutorials everywhere, asked for support and reported this issue on the[ french forum](https://www.dolibarr.fr/forum/12-howto--aide/64021-mailman-qu-en-est-il#108820) and [english forum](https://www.dolibarr.org/forum/12-howto-help/28950-mailman-where-are-we#36755) but with no luck
I encountered this issue on several dolibarr install, both V9 and V10, on three different server, one VPS running stretch [set this way](https://www.howtoforge.com/tutorial/perfect-server-debian-9-stretch-apache-bind-dovecot-ispconfig-3-1/), and two shared hosting, one at infomaniak and one at O2Switch !

---

 **could you please guys provide a simple tutorial on how to use mailman ?** 

I promiss I'll detail it and post it on both forums

It's been hours and month of fight to set it up or find a good alternative solution ! 

I'll be very very gratefull if you could unlock this up 

Regards
