### ISSUE TITLE
Adding tab to adherent from custom module

### ISSUE THREAD

**Issue by Angelinsky7** [Dolibarr/dolibarr#10576]
# Bug
Cannot a a tab to the adherent edit page from the tabs array of a custom module

## Environment
- **Version**: 9.0.0
- **OS**: Linux 0d0cdb066bdb 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: 7.2.15
- **Database**: MySQL 5.7.3

## Expected and actual behavior
A new tab called 'Title1' should be visible inside the adherent tab list, but nothing changes.

## Steps to reproduce the behavior
from what i understand i should be able to add a tab in the adherent tab list by adding this into the $this->tabs array of the modModule.class.php file 
`$this->tabs[] = array('data'=>'adherent:+tabname1:Title1:mylangfile@test001:$user->rights->test001->read:/test001/mynewtab1.php?id=__ID__');  `

**Comment by Angelinsky7** [comment]
`$this->tabs[] = array('data'=>'member:+tabname1:Title1:mylangfile@test001:$user->rights->test001->read:/test001/mynewtab1.php?id=__ID__');` has the same behavior but it should work because @line 70 of member.lib.php :  `complete_head_from_modules($conf,$langs,$object,$head,$h,'member');`

**Comment by Angelinsky7** [comment]
ok it seems that if the system does not find a traduction inside the trad file is silently crash and does not add anything.

**Comment by Angelinsky7** [comment]
we maybe could have a warning or something, no ?

**Comment by zaouich** [comment]
did you find a solution for this?

**Comment by Angelinsky7** [comment]
@zaouich if i remember correctly i think i only added translation for all added tab-item's caption, and it worked. 
What i was asking, was a warning in the log file to know what translation was missing and were.

**Comment by zaouich** [comment]
something like that? thanks for your help :
$this->tabs = array(
			'thirdparty:+tabname:TitleOfTab:automail@automail:/societe/marketting.php?id=__ID__'
		);
