### ISSUE TITLE
Rest API explorer results in an error

### ISSUE THREAD

**Issue by hussain-attari** [Dolibarr/dolibarr#10571]
Hi,

Rest API Explorer shows the error in xml that the stylesheet is missing

I initially installed Dolibarr 8.0.4 and then upgraded to Dolibarr 9.0.0 removed all the depreciated files as shown in this issue [https://github.com/Dolibarr/dolibarr/issues/7623](url)

This did not resolve the issue.

So I uninstalled Dolibarr completely and did a complete fresh install assuming that there would be some issues since I did the upgrade.

This did not work either I still get an error. Given below is the error

**For the first link [Url to get token to use API] on the Rest API page I get the error**

This XML file does not appear to have any style information associated with it. The document tree is shown below.

**For the Rest API explorer page I get the error**

{"messages":["attribute paths is not of type `object`"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (array) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/paths"},"instance":{"pointer":"/paths"}}]}

**Comment by hussain-attari** [comment]
Please help resolving this issue as I want to integrate Dolibarr with Zoho Books. This would help me complete my software requirement for my company located in India

**Comment by eoxia-jimmy** [comment]
Hi

This solution worked for me: https://github.com/Dolibarr/dolibarr/issues/7623#issuecomment-353416188

**Comment by ander-chan** [comment]
> Hi
> 
> This solution worked for me: [#7623 (comment)](https://github.com/Dolibarr/dolibarr/issues/7623#issuecomment-353416188)

Hi the GET method not work, but only \\?? was missing 
`preg_match('/index\.php\/([^\/\??]+)(.*)$/', $_SERVER["REQUEST_URI"], $reg);`
