### ISSUE TITLE
Add: subsidiary company for users/employees

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#10600]
# Feature Request
A company with several subsidiaries needs to organize its employees in its branches / subsidiaries.
This is an opportunity to add a subsidiaries table and add an id_company column to the user table?

**Comment by atm-maxime** [comment]
Something has been started in the HRM module to manage establishments. Not finished yet, you're right we should add a fk_establishment in the user card.

**Comment by wdammak** [comment]
> 
> 
> Something has been started in the HRM module to manage establishments. Not finished yet, you're right we should add a fk_establishment in the user card.

thx @maxime
so we are going to have a table establishments?

**Comment by atm-maxime** [comment]
Yes https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/hrm/class/establishment.class.php

**Comment by wdammak** [comment]
thx atm!
I tried to create an establishment with this url (/hrm/establishment/card.php?action=create) is unfortunately I have this error:
Error Field 'tms' doesn't have a default value

**Comment by atm-maxime** [comment]
As I said, not finished yet. You can test more by moving to MAIN_FEATURE_LEVEL 2 (only in a test environment !). Then activate the module.

**Comment by aspangaro** [comment]
@wdammak I try on v7-8-9 and it's functionnal for me

**Comment by wdammak** [comment]
@atm-maxime yes I am in mode dev and level = 2, I also enabled the module GRH
@aspangaro I just redo the tests and it seems that there is a bug somewhere.
[https://www.dolibarr.fr/forum/5-bugs-sur-la-version-cvs-ou-demo/62786-erreur-tms-defaut-value-sur-le-module-grh-cvs](https://www.dolibarr.fr/forum/5-bugs-sur-la-version-cvs-ou-demo/62786-erreur-tms-defaut-value-sur-le-module-grh-cvs)
thx

**Comment by wdammak** [comment]
Fixed with:
ALTER TABLE `llx_establishment` CHANGE `tms` `tms` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
it's missing the default value (was empty)

**Comment by wdammak** [comment]
I noticed another bug with the specified country!
I select Switzerland to him but he assigns me France :)
And when I come back to edit it there is empty field country
the stats also

**Comment by wdammak** [comment]
I can help?

**Comment by wdammak** [comment]
[https://github.com/Dolibarr/dolibarr/pull/10649](https://github.com/Dolibarr/dolibarr/pull/10649)

**Comment by wdammak** [comment]
/hrm/establishment/card.php?id=1
dans la fiche au lieu que le nom d'établissement s'affiche c'est l'id ...
a corriger

**Comment by wdammak** [comment]
lors d'édition la valeur du pays n'est pas retenue! et il faut a chaque fois sélectionner le pays avant de sauvegarder!

**Comment by wdammak** [comment]
lors d'édition/création d'un utilisateur on n'a pas la possibilité de spécifier à quel établissement appartient l'employé! 
/user/card.php?id=8&action=edit

**Comment by eldy** [comment]
The lose of country during edit has been fixed by 6f0f1e1163a2e67910f8f7c3ac19deb58d0c1db3

**Comment by wdammak** [comment]
thx
