### ISSUE TITLE
missed file

### ISSUE THREAD

**Issue by Darthmotion** [Dolibarr/dolibarr#10620]
# Bug
missed file on new product creating "cmeasuringunits.class.php"
error: require_once(/www/htdocs/phantom/phantomERP/core/class/cmeasuringunits.class.php): failed to open stream: No such file or directory in /www/htdocs/phantom/phantomERP/product/class/html.formproduct.class.php on line 321

## Environment
- **Version**: [*10.0.0*]
- **OS**: [*windows*]
- **Web server**: [*apache*]
- **PHP**: [*7*]
- **Database**: [*Mysql 5.5*]
- **URL(s)**: [**]

**Comment by mwelters** [comment]
This file appeared around #10559 - but it didnt end up in develop... clueless

**Comment by mwelters** [comment]
Can you close the issue ?
