### ISSUE TITLE
Bug: Donations api non found

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#10636]
# Bug

## Environment
- **Version**: 10.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Unix)
- **PHP**: fpm-fcgi 7.0.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.7-MariaDB
- **URL**: /api/index.php/donations

## Report

error 501 with message: API not found (failed to include API file)

**Comment by frederic34** [comment]
there is a mix between don, donation, donations.. perhaps need to clean?
or add code in function2.lib.php

**Comment by ptibogxiv** [comment]
it was function2.lib.php i 'll do a PR to fix it
