### ISSUE TITLE
Mail sending through SMTP (Postfix or office365) server fails

### ISSUE THREAD

**Issue by kouinkouin** [Dolibarr/dolibarr#10695]
# Bug
I am trying to send mail through SMTP server.
Whether I use "SMTP/SMTPS socket library" or "Swift Mailer socket library", through a Postfix or office365 SMTP, I get an error.

## Environment
- **Version**: 8.0.2, 8.0.3, 8.0.4 (I didn't test with 8.0.1)
- **OS**: Debian 9/Stretch (from docker image)
- **Web server**: nginx
- **PHP**: 7.1.26 (from docker image)
- **Database**: MySQL Percona 5.7
- **Docker image**: monogramm/docker-dolibarr:8.0.4-fpm
- **Dolibarr image hash:** `b971d753d0fa`

## Expected and actual behavior

When I choose the method "SMTP/SMTPS socket library", I get an error of the SMTP Postfix server:
```
Failed to send mail (sender=My Company , receiver=admin@domain.tld)
Error [120]: Ran into problems sending Mail. Response: 501 5.5.2 : Helo command rejected: Invalid name Error [120]: Ran into problems sending Mail. Response: 554 5.5.1 Error: no valid recipients Error [120]: Ran into problems sending Mail. Response: 221 2.7.0 Error: I can break rules, too. Goodbye. 
```

If I try with a Office365 SMTP (smtp.office365.com), I get:
```
Failed to send mail (sender=My Company , receiver=admin@domain.tld)
Error [120]: Ran into problems sending Mail. Response: 501 5.5.4 Invalid domain name [AM6PR03CA0010.eurprd03.prod.outlook.com] Error [126]: 'tls://smtp.office365.com' does not support authenticated connections.
```

So, I choose the method "Swift Mailer socket library", but I get another error (on both Postfix servers).

Here the error:
```
 Fatal error: Uncaught Error: Class 'Egulias\EmailValidator\Exception\CharNotAllowed' not found in /var/www/html/includes/swiftmailer/egulias/email-validator/EmailValidator/Parser/DomainPart.php:178
Stack trace:
#0 /var/www/html/includes/swiftmailer/egulias/email-validator/EmailValidator/Parser/DomainPart.php(135): Egulias\EmailValidator\Parser\DomainPart->checkNotAllowedChars(Array)
#1 /var/www/html/includes/swiftmailer/egulias/email-validator/EmailValidator/Parser/DomainPart.php(60): Egulias\EmailValidator\Parser\DomainPart->doParseDomainPart()
#2 /var/www/html/includes/swiftmailer/egulias/email-validator/EmailValidator/EmailParser.php(49): Egulias\EmailValidator\Parser\DomainPart->parse('1550585019.swif...')
#3 /var/www/html/includes/swiftmailer/egulias/email-validator/EmailValidator/Validation/RFCValidation.php(30): Egulias\EmailValidator\EmailParser->parse('1550585019.swif...')
#4 /var/www/html/includes/swiftmailer/egulias/email-validator/EmailValidator/EmailValidator.php(37): Egulias\EmailValidator\Validation\RFCVali in /var/www/html/includes/swiftmailer/egulias/email-validator/EmailValidator/Parser/DomainPart.php on line 178
```

Note on the Postfix SMTP, I get the error, and if I refresh the page (F5), the mail is sent.

If I refresh on the Office365 SMTP, I get another error:
```
Failed to send mail (sender=My Company , receiver=admin@domain.tld)
Expected response code 250 but got code '554', with message '554 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 16.55847:3A130000, 17.43559:0000000094000000000000000100000000000000, 20.52176:140F5686000010103C050000, 20.50032:140F56867F17101041050000, 0.35180:0A00AA80, 255.23226:46050000, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A000000, 16.55847:84000000, 17.43559:00000000A0010000000000001300000000000000, 20.52176:140F56860000101003000136, 20.50032:140F56867F1710100A00DA36, 0.35180:44000000, 255.23226:4800D13D, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:0A003A66, 4.21921:DC040000, 255.27962:FA000000, 255.1494:64000000, 0.38698:77090000, 0.37692:0F010480, 0.44092:00000000, 0.41232:00000000, 0.60208:05000780, 0.37136:05000780, 0.34608:00000000, 0.55056:05000780, 0.42768:37003032, 0.56112:00000000, 0.52807:31373242, 4.33016:DC040000, 7.40748:010000000000010B31343743, 7.57132:000000000000000000000000, 1.63016:32000000, 4.39640:DC040000, 8.45434:8CE098808326DC4CA7B470EECC7FFBF600373A34, 5.10786:0000000031352E32302E313632322E3030303A414D345052303830324D42323330373A34396166623264302D346339342D343935392D626235332D3664643032613033313437620000000000, 255.1750:AF000000, 255.31418:03000336, 0.22753:B4000000, 255.21817:DC040000, 4.60547:DC040000, 0.21966:0A003267, 4.30158:DC040000 [Hostname=AM4PR0802MB2307.eurprd08.prod.outlook.com] '
```

Here, my mail setup:
![screenshot_2019-02-19 setup](https://user-images.githubusercontent.com/3999492/53022235-0b6ef480-345b-11e9-95d7-135df981a558.png)

Note it's a custom domain for the Office365 email (not a "admin@outlook.com or admin@office365.com).

I don't think everything is a bug, probably I have to setup something I didn't.
If you have an idea, please let me know!

In advance, thanks for your help :) .

**Comment by kouinkouin** [comment]
Issue created on the docker repo: Monogramm/docker-dolibarr#28

**Comment by frederic34** [comment]
hello can you add https://github.com/Dolibarr/dolibarr/pull/10722 to try to find error with swiftmailer.
Do you have a special character in domain name?

**Comment by frederic34** [comment]
you can also try
https://github.com/Dolibarr/dolibarr/pull/10723/files

**Comment by kouinkouin** [comment]
It's a setup mistake indeed.
Here my post on the forum : https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/63789-envoi-de-mail-depuis-un-smtp-office365 .

To resume : 
- The Postfix server was an old SMTP, that worked with a recent Postfix server.
- The Office365 SMTP host must be domain-tld.mail.protection.outlook.com. That works better, but not ; I get the message "No mail sent. Feature is disabled by option MAIN_DISABLE_ALL_MAILS" now :-( .

I close the ticket because it is not an issue, but a setup issue.
