### ISSUE TITLE
BUG BOM: Field 'tms' doesn't have a default value

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#10709]
This is due to the default value for tms.
To foresee during the future additions of the columns in the tables and future tables.

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.

**Comment by gigarun** [comment]
Hi, i'm on v16.0.5 and got the same message while trying to activate module modEmailCollector.
