### ISSUE TITLE
Extrafields of type date not handled correctly in invoices

### ISSUE THREAD

**Issue by nlc-bb** [Dolibarr/dolibarr#10766]
# Bug
Extrafields of type date (and possibly datetime) not handled correctly in invoice module, when using non-english locale.

## Environment
- **Version**: 9.0.1
- **OS**: Debian
- **Web server**: Apache/2.4.25
- **PHP**: 7.0.19-1
- **Database**: MySQL 
- **URL(s)**: /compta/facture/card.php

## Expected and actual behavior
When filling a date extrafield in invoice detail in french environment, it is stored in english format (mm/dd/yyyy). For example, entering 12/06/2018 is saved as 06/12/2018.

## Steps to reproduce the behavior
Create a date (or datetime) extrafield in invoice detail (invoice module configuration). Create a new invoice and fill that field.

## Suggested implementation
Invoice module still uses old implementation of getOptionalsFromPost() function of ExtraFields class (/htdocs/core/class/extrafields.class.php), where data type is not passed. This problem existed already in versions 8.0.x but the dates were not stored at all (1/1/1970). So there is a progress ;-)
Callig this function the new way (first parameter as string) solved my problem. Hope there is no side effects.

## Suggested steps
Replace in /htdocs/compta/facture/card.php (line 1689 for version 9.0.1)
`$array_options = $extrafieldsline->getOptionalsFromPost($extralabelsline, $predef);`
by
`$array_options = $extrafieldsline->getOptionalsFromPost($object->table_element_line, $predef);`

and (line 2098 for version 9.0.1)
`$array_options = $extrafieldsline->getOptionalsFromPost($extralabelsline);`
by
`$array_options = $extrafieldsline->getOptionalsFromPost($object->table_element_line);`

**Comment by nlc-bb** [comment]
Continuation of issues #9474 and #9641 (versions 8.0.x)
Possible duplicate of #10648 (since there are no details mentionned) and maybe other issues related to extrafields.

**Comment by atm-maxime** [comment]
Fixed in #10803 but not in 8.0 branch yet

**Comment by atm-maxime** [comment]
Coud you confirm it's fixed please ?
