### ISSUE TITLE
# Bug [New Adherent]

### ISSUE THREAD

**Issue by webmasterproxy-media** [Dolibarr/dolibarr#10778]
# Bug
[Civility on adherent creation isnt added]

## Environment
- **Version**: [8/9/10]

- **URL(s)**: [/htdocs/adherents/card.php?leftmenu=members&action=create]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[Create a  adherent]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[https://www.dolibarr.fr/forum/510-adherentsassociation/63816-adherent-civilite]

## Use case
[Lors de la creation d un adh la civilité n est pas enregistré>>il faut modif la fiche pour enregistrer la civilité]

**Comment by aspangaro** [comment]
Already correct with PR #10308 

Please close this issue
