### ISSUE TITLE
[BUG] Extrafield line on propal

### ISSUE THREAD

**Issue by iouston** [Dolibarr/dolibarr#10771]
# Bug
- On a dolibarr's fresh installation (but after a maj too)
- I add several extrafield for lines on propal
- I set the visibility of the extrafield to 0
- When i add a line, extrafields are visible

## Environment
- **Version**: 9.0.1
- **URL(s)**: comm/propal/card.php?id=1

## [Attached files]
![2019-03-07 15_44_08-configuration du module propositions commerciales](https://user-images.githubusercontent.com/4319513/53964640-03b47e80-40f0-11e9-9d37-54d17a135856.jpg)
![2019-03-07 15_44_28-proposition commerciale](https://user-images.githubusercontent.com/4319513/53964641-03b47e80-40f0-11e9-87f3-46dabe297a83.jpg)
[*Files*]

**Comment by inoveaconseil** [comment]
Resolve in 9.0.2
