### ISSUE TITLE
External users cannot see projects

### ISSUE THREAD

**Issue by jriboux** [Dolibarr/dolibarr#10789]
# Bug
External users cannot see or access projects when assigned as contact.

## Environment
- **Version**: [9.0.1]
- **PHP**: [7.0]

## Expected and actual behavior
External users should see projects they are assigned as contact

## Steps to reproduce the behavior
- Create a contact
- Create an external user for this contact
- Create a project
- Assign contact on project

## Fix ?
It seems to be an error in htdocs/projet/class/project.class.php lines 1239 & 1247.
`$sql.= " AND ec.fk_socpeople = ".$user->id.")";`
Maybe use $user->contactid instead ?
fk_socpeople seems to be sometime a user id and sometime a contact id, this can lead to security issues.

The line 701 in `htdocs/projet/list.php` prevents the project list to be shown.

**Comment by eldy** [comment]
By definition, an external user can see only elements of its thirdparties.
Does the project you try to read have a thirdparty that is the thirdparty of the external user ?

**Comment by ukb-33** [comment]
Got same problem here with a quite fresh 10.0.0.4 install.
Tested a couple of differents config in terms of rights, and found that the first "Lire les projets et tâches (partagés ou dont vous n'êtes pas contact)" seems to be not enough event in these situation:
- external user UA, linked to company CA
- project P, created by Admin, for third party CA
- UA is mentionned as responsible for project P and associated tasks.

When UA connects, she can't see project where she is named as contact.

**Comment by ukb-33** [comment]
Environment information are mentionned in #12798

**Comment by ksar-ksar** [comment]
Have you tested with latest dolibarr version ?

**Comment by ksar-ksar** [comment]
Hello,

You can re-open the issue if it is still a BUG

**Comment by libremaster** [comment]
Could you re-open this ticket ?

The problem is in **project/class/project.class.php** :

**public function getProjectsAuthorizedForUser** : 

1/ listofprojectcontacttype

`$sql2 .= " AND ctc.source = 'internal'";`

If contact is external then this request is false because we can see 'internal', instead of 4 codes, we get two or we should have two request : one for external user and one for internal user.

2/ fk_socpeople : 

`$sql .= " AND ec.fk_socpeople = ".$user->id.")";
`
If i put this, it works but we should check if $user->contact_id is NULL: 

`$sql .= " AND ec.fk_socpeople = ".$user->contact_id.")";
`

**Comment by Dominatorr007** [comment]
yes in version 13.4 this bug still persists please fix

**Comment by wolfcreative** [comment]
14.0.5, the bug is still present 
@eldy, can you tell me how to fix this?

**Comment by rycks** [comment]
Here is the race condition @eldy :

![image](https://user-images.githubusercontent.com/1468823/167639650-af249760-be36-4e8a-9c06-59e07bf73d3e.png)

![image](https://user-images.githubusercontent.com/1468823/167639744-09356006-1131-4474-8eec-fc2307ad2e14.png)

Then in this case we can't filter only on "internal" ctc.source ...

**Comment by denisb79** [comment]
Has someone solved the issue?
I have version 15 installed and our external users can't see the progress of their projects.
Thank you so much

**Comment by xenion1987** [comment]
15.0.3 still not solved
