### ISSUE TITLE
Invoice generation : Error on substitution

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#10791]
Hello

Looks one error on  get_substitutionarray_object method from htdocs/core/class/commondocgenerator.class.php  

already_payed_all and remain_to_pay looks wrong. Value are added to sum to pay. Should be : 
```
                        $already_payed_all=-$sumdeposit - $sumcreditnote;
                        $remain_to_pay=$sumpayed + $sumdeposit + $sumcreditnote;
```
Values are yet negative sum we mus sum them not soustract.

Actually is wrong on 9.01, but looks as an old bug.

**Comment by ThieBurg** [comment]
Hi,

I confirm the problem and I've first cancelled line 383:
			$remain_to_pay=$sumpayed - $sumdeposit - $sumcreditnote;

then, I have replaced lines 445 & 446:
		$array_key.'_remain_to_pay_locale'=>price(price2num($object->total_ttc - $remain_to_pay, 'MT'), 0, $outputlangs),
		$array_key.'_remain_to_pay'=>price2num($object->total_ttc - $remain_to_pay, 'MT')

by following lines:
		$array_key.'_remain_to_pay_locale'=>price(price2num($object->total_ttc - $already_payed_all, 'MT'), 0, $outputlangs),
		$array_key.'_remain_to_pay'=>price2num($object->total_ttc - $already_payed_all, 'MT')

It seems to give the good remain_to_pay amount during the generation of the ODT document.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by ThieBurg** [comment]
Hi,
Yes, the bug still occurs with 9.0.4 version.
Not tested with 10.0.0 version.
