### ISSUE TITLE
Errors in French translations

### ISSUE THREAD

**Issue by guillaum-t** [Dolibarr/dolibarr#10797]
# Translation mistakes
Errors in French translations

## Environment
- **Version**: 9.0.0, 9.0.1
- **OS**: all
- **Web server**: all
- **PHP**: all
- **Database**: all
- **URL(s)**: 

## langs/fr_FR/admin.lang
< SupplierProposalSetup=Configuration du module Demande de tarifs forunisseurs
> SupplierProposalSetup=Configuration du module Demande de tarifs fournisseurs

## langs/fr_FR/companies.lang
< ShowCompany=Affichier tiers
> ShowCompany=Afficher tiers

**Comment by ksar-ksar** [comment]
https://www.transifex.com/dolibarr-association/dolibarr/translate/#fr_FR

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/54144976-3bdbfa00-442d-11e9-8258-72c2c18a82ba.png)

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/54180692-821c7200-449c-11e9-8f0a-28fc06537171.png)
