### ISSUE TITLE
Bug hrm/index.php SQL request literally explode in tmp on debian

### ISSUE THREAD

**Issue by Crush33** [Dolibarr/dolibarr#10819]
## Environment
- **Version**: 9.0 and 8.0
- **OS**: debian 9
- **Web server**: apache2
- **PHP**: 7
- **Database**: mariaDB latest
- **URL(s)**: /hrm/index.php

## Expected and actual behavior
the screen should display normally.

## Steps to reproduce the behavior
on Doli v9.0.0 click on "GRH" button (with a specific user) generate a HUGE non stop growing file in /tmp on debian 9 with mariadb latest version then it slow down until it crashes completly. This is due to an "order by" in the request and FROM on 4 tables. If I remove the "order by" manually, the request seems to be OK but kind of slow.

the request is in htdocs/hrm/index.php between line 323 and 332

Here are the sizes of my table :
select count(1) from llx_societe; # return 1985 rows
select count(1) from llx_societe_commerciaux; # return 2805 rows
select count(1) from llx_expensereport; # return 63 rows
select count(1) from llx_user; # return 30 rows

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/2492697/54271758-6e4b3b80-4582-11e9-8b04-1f8820ef0d23.png)

**Comment by eldy** [comment]
Do you still have trouble with 10.0 ?

**Comment by atm-maxime** [comment]
I close this issue, I checked on the 8.0.7 version and the multi table select has been changed.
