### ISSUE TITLE
Error fetching module

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#10816]
Failed to open IMAP connection {imap.hostinger.mx:993/service=imap/ssl/novalidate-cert}Entrada

please help me with this error in fetching module

**Comment by atm-maxime** [comment]
Sorry this is not an issue regarding the software but your own setup. Please look through forums or contact a Dolibarr preferred partner to help you.

**Comment by julbroa-zz** [comment]
Sorry, the introduced configuration is correct, since it is usually with which I connect and I can synchronize my mail in other clients but the problem arises because, as you can see, the module is rejecting the connection and expresses that it does so because the SSL certificate It is invalid, although it is not

**Comment by atm-maxime** [comment]
Ok, so give us more details because we don't know what module you are using, what version of Dolibarr, ... Give us screenshots also.

**Comment by julbroa-zz** [comment]
i have 9.0.3 version of dolibarr, the module is emailcollector.
this is a screenshot of the module with error specified:


![colector](https://user-images.githubusercontent.com/28205134/59153840-769fff00-8a29-11e9-9d1f-81c4bcdc3163.png)

**Comment by webrdinfo** [comment]
I have the same problem, when I collect emails, I have a 500 error, with the following error:

PHP Fatal error:  Cannot redeclare createPartArray() (previously declared in .../htdocs/emailcollector/class/emailcollector.class.php:982) in .../htdocs/emailcollector/class/emailcollector.class.php on line 982, referer: https://erp.web-rd-info.fr/admin/emailcollector_card.php?id=1&action=collect

PHP Warning:  imap_open(): Couldn't open stream {imap.web-rd-info.fr:993/service=imap/ssl/novalidate-cert}Inbox in .../htdocs/admin/emailcollector_card.php on line 394, referer: https://erp.web-rd-info.fr/admin/emailcollector_card.php

**Comment by eldy** [comment]
You are speaking about the module email collector. And your version is 9.0.*
In this version, this module is experimental.
Please check with v10 where module is stable and reopen if you have the trouble.

**Comment by julbroa-zz** [comment]
Thanks, could you explain me this parameters? 
On module Email collector section Operations to be performed by the collector
![2019-07-17](https://user-images.githubusercontent.com/28205134/62583294-387e5a80-b875-11e9-9e82-76e55ce9a24d.jpg)
