### ISSUE TITLE
French strings ressources typos (as seen in 9.0.1 branch)

### ISSUE THREAD

**Issue by sowebio** [Dolibarr/dolibarr#10827]
French strings ressources typos so issue in french...

* Remarque générale à TOUS LES MODULES :

Si l'on modifie un bouton d'état : message vert 'Configuration sauvegard*é*' au lieu de 'Configuration sauvegardée'

* MODULE Propositions commerciales fournisseurs

Typo dans titre fenêtre module
Configuration du module Demande de tarifs ***forunisseurs***

* MODULE Emails

Libellés des boutons des tests d'envoi de mails peu clairs (imho)

Suggestion...

[TESTER ENVOI] => [TESTER ENVOI TEXTE]
[TESTER ENVOI MAIL] => [TESTER ENVOI HTML]

La marge de la seconde colonne de tableau n'est pas la même, ce qui fait
que lorsqu'on passe de l'un à l'autre des tests d'envois, toute la
colonne de droite est décalée. C'est pas très beau et surtout ça gêne
pour comparer les deux fenêtres d'envoi (imho).

Si explication ci dessus pas claire alterner clic sur [TESTER ENVOI] et
[TESTER ENVOI MAIL] pour voir le truc..

* MODULE Fournisseurs / Autres options / Paramètre

Activer l'approbation en trois étapes si le montant HT est supérieur à... [?] <- Dans l'aide contextuelle, 'très faibe' au lieu de 'très faible'.

**Comment by atm-maxime** [comment]
Thanks for this, translations are managed in transifex : https://www.transifex.com/dolibarr-association/dolibarr/translate/#fr_FR

**Comment by sowebio** [comment]
Hi Maxime,

Followed the (boring and lenghty) subscribe transifex process...
Now waiting another "french language validation" step...

If you're on, I just register as "sowebio - stephane riviere"

Thanks helping me to understand the right way to contribute !

Stef

Le 13/03/2019 à 20:39, Maxime Kohlhaas a écrit :

**Comment by atm-maxime** [comment]
Hi !
Is my answer to your e-mail ok for you ?
You can close this issue.
