### ISSUE TITLE
Bug: Societe module - tab title not translated

### ISSUE THREAD

**Issue by Tim-Otte** [Dolibarr/dolibarr#10820]
# Bug
In the societe module, the tab title "Notifications" is not translated in all tabs in the detailed view. However, if the "Notifications" tab is activated, the title is translated.

## Environment
- **Version**: 9.0.1 and maybe below
- **OS**: Ubuntu 16.04.06
- **Web server**: Apache 2.4.18
- **PHP**: 7.0.33
- **Database**: MariaDB
- **URL(s)**: /dolibarr/margin/tabs/thirdpartyMargins.php?socid=1 (*not translated*), /dolibarr/societe/notify/card.php?socid=1 (*translated*)
- **Language**: de_DE

## Expected and actual behavior
*see description and URL(s)*

## Steps to reproduce the behavior
*see description and URL(s)*

## Attached files (Screenshots, screencasts, dolibarr.log, debugging informations…)
*not translated*
![image](https://user-images.githubusercontent.com/30824254/54274730-224fc500-4589-11e9-8dc5-0115b5590339.png)
*translated*
![image](https://user-images.githubusercontent.com/30824254/54274762-3a274900-4589-11e9-908b-c73eabaf2f8b.png)

**Comment by Tim-Otte** [comment]
I found out that the title is only translated in files in the **societe directory**. If the current tab is added **externally**, the _Notifications_ title is not translated.

**Comment by Tim-Otte** [comment]
Still relevant in v12

**Comment by ksar-ksar** [comment]
Still relevant in V13 ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
