### ISSUE TITLE
Composite product with Multicriteria

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#10825]
How to create and sell a product composed of several by-products instantly without creating a virtual product each time
For example, I have 400 products, + 16 criteria on the category + 12 criteria on the color + 8 criteria on the size + 5 criteria on the number of places + ....
and that some criterion are selective dependent on others and may have an impact on the price of the product....
If I should make the choice, then make the composition and study all possibilities .... I will surely be lost ....

**Comment by BebZ** [comment]
did you check Dolistore product mixer ? 
or variants in recent version of dolibarr ?
