### ISSUE TITLE
Bug: Facture class does not handle correctly discount with multicurrency

### ISSUE THREAD

**Issue by McCoy78** [Dolibarr/dolibarr#10849]
# Bug
Facture class does not handle correctly discount with multicurrency. 

## Environment
- **Version**: 7.0.3

## Expected and actual behavior
When using a deposit invoice in another invoice, the generated line does not read multicurrency values. Therefore, the 'Total without VAT' is wrong.

## Steps to reproduce the behavior
With multicurrency enabled:
- create a deposit invoice
- transform the deposit invoice as a discount using the dedicated button
At this step, the record in the table 'xxx_societe_remise_except' has the multicurrency fields set to 0
- As a concequency: use the discount on a new invoice and the 'Total without VAT' is wrong.

## Suggested implementation
In method Facture::insert_discount, on line 1700, the code does not use the good DiscountAbsolute member name.

This bug is related to the bug #10848 

## Suggested steps
Code before:
                        $facligne->multicurrency_subprice = -$remise->multicurrency_subprice);
                        $facligne->multicurrency_total_ht = -$remise->multicurrency_total_ht);
                        $facligne->multicurrency_total_tva = -$remise->multicurrency_total_tva);
                        $facligne->multicurrency_total_ttc = -$remise->multicurrency_total_ttc);

Code after:
//                        $facligne->multicurrency_subprice = -floatval($remise->multicurrency_subprice); // NOT AVAILABLE. See Bug #10848 
                        $facligne->multicurrency_total_ht = -floatval($remise->multicurrency_**amount**_ht);
                        $facligne->multicurrency_total_tva = -floatval($remise->multicurrency_**amount**_tva);
                        $facligne->multicurrency_total_ttc = -floatval($remise->multicurrency_**amount**_ttc);

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
