### ISSUE TITLE
Bug BOM t.date_valid

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#10852]
#1054 - Champ 't.date_valid' inconnu dans field list

SELECT t.rowid, t.ref, t.label, t.fk_product, t.qty, t.description, t.note_public, t.note_private, t.date_creation, t.tms, t.date_valid, t.fk_user_creat, t.fk_user_modif, t.fk_user_valid, t.import_key, t.status FROM llx_bom_bom as t WHERE t.entity IN (1) ORDER BY t.rowid ASC LIMIT 26

**Comment by ghost** [comment]
bom module was under developpement. It fix now
