### ISSUE TITLE
Feature Request - ODT Tags for localtax1_rate & localtax2_rate

### ISSUE THREAD

**Issue by hussain-attari** [Dolibarr/dolibarr#10884]
Hi,

I am trying to build a custom ODT for Invoice and Proposals however, I am stuck as I am unable to display the localtax1 rate and localtax2 rate for the products. 

Request for Tags for them. I am sure they already exists as the default crabe module generates invoice seamlessly.

Example
CGST & SGST [9/9% (C+S-18)] Need the ODT Tag for this.

**Comment by hussain-attari** [comment]
I have the latest version installed i.e. Dolibarr 9.0.1

**Comment by eldy** [comment]
I pushed a change to allow this: 9745bd1f16b69e66e8983d5876aacd6cf24d693e

**Comment by hussain-attari** [comment]
Thank you

**Comment by ksar-ksar** [comment]
Can you close it ?

**Comment by hussain-attari** [comment]
> 
> 
> Can you close it ?

Hi,

Sorry couldn't do this earlier as I was out of town.
