### ISSUE TITLE
TimeZone

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#10885]
In database, data are stored with PHP server Timezone (often defined in UTC on cloud servers but not always). It must be defined in UTC whatever is PHP timezone.
When inserting or updating fields like datec or tms, value come from dol_now so is a GMT date, so date is stored correctly in PHP server Timezone
For other fields data are converted with ->idate() during insert/update to make a string. So when done from GUI, when we insert 10:00, we have 10:00 in database even if timezone of user differs of server, so value is not PHP server timezone but user gui timezone. And if insert is done by batch on server, the same field is save with PHP server timezone (because gui timezone is not defined).

Need to change this to store the PHP server timezone always, so idate must modify date using the user gui timezone saved into session before generating sql and jdate must do the oposite. So data in database will always be server timezone.

**Comment by wdammak** [comment]
My opinion for more clarification...
To avoid any kind of confusion, the norm is to store and work only with the timezone UTC. Your server and PHP are configured in UTC and your database stores UTC dates.
default_time_zone_set("UTC");
ini_set("date.timezone", "UTC");

//mysql my.cnf
default_time_zone=+00:00

After the user has entered his dates in his timezone, it must be converted to UTC once sent to the server. Likewise, on display, the UTC dates must be converted into the user's time zone.
```

//$time_zone_from -- //get from session
function TimeZoneToUTC($datetime, $time_zone_from = 'America/New_York')
{
	$time_zone_to = 'UTC';
	$format = 'Ymd\THis\Z'; //get from session

	$newdate = new DateTime($datetime, new DateTimeZone($time_zone_from));
	$newdate->setTimeZone(new DateTimeZone($time_zone_to));
	return $newdate->format($format);
}

```
It is also important to always add an hour to your dates, even if only the date interests you.

**Comment by dpriskorn** [comment]
This seems important. Has it been fixed?

**Comment by eldy** [comment]
Some enhancement were done into v13.
