### ISSUE TITLE
[Bug] Mass action in proposals : server error

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#10908]
# Bug
Error 500 when action "cloture" is launched in proposals list on an opened proposal.
[php:error] [pid 11787] [client 127.0.0.1:45874] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Propal::cloture(), 2 passed in /var/www/html/dolibarr/htdocs/core/actions_massactions.inc.php on line 1057 and at least 3 expected in /var/www/html/dolibarr/htdocs/comm/propal/class/propal.class.php:2378\nStack trace:\n#0 /var/www/html/dolibarr/htdocs/core/actions_massactions.inc.php(1057): Propal->cloture(Object(User), 3)\n#1 /var/www/html/dolibarr/htdocs/comm/propal/list.php(241): include('/var/www/html/d...')\n#2 {main}\n  thrown in /var/www/html/dolibarr/htdocs/comm/propal/class/propal.class.php on line 2378, referer: http://localhost/dolibarr/htdocs/comm/propal/list.php?leftmenu=propals

## Environment
- **Version**: 8.0.3
- **OS**: Mageia 6
- **Web server**: apache2
- **PHP**: 7.2
- **Database**: Mariadb
- **URL(s)**: /htdocs/comm/propal/list.php

## Expected and actual behavior
No bug, but an action
I get a white page.

## Steps to reproduce the behavior
list proposals. Check one line which is with status "Validée (ouverte)" (Open).
In Action list, choose "Clôturé" (should be "Clôturer"). Press Confirmer".
Get the white page and error in log file.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by papoteur-mga** [comment]
Hello,
The 2 points are solved with version v10.0.0
