### ISSUE TITLE
Bug: truncating of account numbers

### ISSUE THREAD

**Issue by swedebugia** [Dolibarr/dolibarr#10906]
# Bug
Account number is truncated when saved.
e.g. 1910 -> 191
1930 -> 193

## Environment
- **Version**: 9.0.1
- **OS**: linux arch
- **Web server**: 1.14.2
- **PHP**: 7.3.2
- **Database**: pg
- **URL(s)**: http://dolibarr.localhost/accountancy/admin/card.php?action=create

## Expected and actual behavior
Leave the number as I type it.

## Steps to reproduce the behavior
Go to url.
Create account with one of the numbers above.
Save.
-> list of accounts show truncated number.

SQL extract looks like this:

dolibarr=> SELECT * FROM llx_accounting_account;
 rowid | entity |        datec        |            tms             | fk_pcg_version | pcg_type | pcg_subtype | account_number | account_pare
nt | label | fk_accounting_category | fk_user_author | fk_user_modif | active | import_key | extraparams 
-------+--------+---------------------+----------------------------+----------------+----------+-------------+----------------+-------------
---+-------+------------------------+----------------+---------------+--------+------------+-------------
     1 |      1 | 2019-03-22 16:30:30 | 2019-03-22 17:31:47.977903 | SE-enkel       | XXXXXX   | XXXXXX      | 191            |             
 0 | Kassa |                      0 |              1 |             1 |      1 |            | 
     2 |      1 | 2019-03-22 16:33:23 | 2019-03-22 17:33:23.063596 | SE-enkel       | XXXXXX   | XXXXXX      | 193            |             
 0 | Bank  |                      0 |              1 |               |      1 |            | 
(2 rows)

**Comment by aspangaro** [comment]
It's just an option in accouting setup module. (Manage zero...) Countries
needs zero and others no.

Please, close your issue

Le ven. 22 mars 2019 à 18:08, swedebugia <notifications@github.com> a
écrit :

**Comment by swedebugia** [comment]
Thanks for the hint!
