### ISSUE TITLE
bug on extrafield without number

### ISSUE THREAD

**Issue by jojorb** [Dolibarr/dolibarr#10910]
# Bug
`Warning: A non-numeric value encountered in /var/www/html/core/tpl/extrafields_list_print_fields.tpl.php on line 50`

when you had an extra field on a product (as a string, number or any other), create or update a product, then return to the product list, you can see this error under the header if the extra field doesn't contain any number (even if it's a string).

## Environment
- **Version**: [*docker 9.0.1*]
- **OS**: [*Debian 9.8*]
- **Web server**: [*Apache/2.4.25 (Debian)*]
- **PHP**: [*7.1.27*]
- **Database**: [*PostgreSQL 11.2 (Debian 11.2-1.pgdg90+1)*]
- **URL(s)**: [*/var/www/html/core/tpl/extrafields_list_print_fields.tpl.php on line 50*]

## Expected and actual behavior
if you enter a string that doesn't require a number, it should not display an error that your string must contain a number on the product liste.

## Steps to reproduce the behavior
create an extra field from `configuration/Modules/Applications/product` select "new attributes" and add an extra field (string, liste or any other) save it. Create or Edit a product from the product page, edit the extrafield ex `Brand` (string) with `github`. then return to the product liste, there you can see the error message.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by jojorb** [comment]
thanks @eldy i updated to Dolibarr 9.0.3 and it's working good, 9.0.4 should work too i suppose, i will not test it with v10.
last version where i get thoses errors was 9.0.1
