### ISSUE TITLE
Bug: Multicurrency entity

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#10927]
Hi !
I've just update Dolibarr 6 to Dolibarr 9
Everything is perfect but.
the fied **entity** in the table **llx_multicurrency_rate** is missing.

In dolibarr/htdocs/install/mysql/migration/3.9.0-4.0.0.sql we can read 
```sql
CREATE TABLE llx_multicurrency_rate 
( 
	rowid integer AUTO_INCREMENT PRIMARY KEY, 
	date_sync datetime DEFAULT NULL,  
	rate double NOT NULL DEFAULT 0, 
	fk_multicurrency integer NOT NULL 
) ENGINE=innodb;
```
But i'v didn't found the ALTER TABLE in the other migration sql files
```sql
ALTER TABLE llx_multicurrency_rate ADD COLUMN entity integer DEFAULT 1 NOT NULL;
```

Tks

**Comment by yorkhood** [comment]
This is issue that all the conversion rate is not set even for local conversion rate.  Hence when you create an invoice, it always show conversion rate  0 USD = 1 USD

**Comment by hregis** [comment]
@dolibarr95 
the addition of the entity field is already present in 3.9.0-4.0.0.sql !

**Comment by dolibarr95** [comment]
ok tks ;)
