### ISSUE TITLE
[Bug] Extrafields: date fields on order/propal lines 

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#10937]
# Bug
Data value of extrafields are not stored during insert and update of single line of propal or order. (I suppose also for invoice but I didn't test it)

## Environment
- **Version**: 8.0.4 - 9.0.1 - develop 10 alpha
- **URL(s)**: comm/propal/card.php?id=1 and commande/card.php
- **OS**: Debian and Mint
- **Web server**: Nginx and Apache
- **PHP**: 7.2
- **Database**: Mysql

## Use case
Try to insert an extrafields of type "Date" on propal/commande line (visibility = 1).
Create a new Order and try to insert a new line or try to update a value.
Value of extrafields will not be stored.

**Comment by inoveaconseil** [comment]
Resolve in 9.0.2

**Comment by atm-maxime** [comment]
Confirmed solved in 8.0 too
