### ISSUE TITLE
no partner contacts can be linked in the module "Commercial / price request"

### ISSUE THREAD

**Issue by khpartusch** [Dolibarr/dolibarr#10949]
# Instructions

# Bug
no partner contacts can be linked in the module "Commercial / price request"

## Environment
- **Version 9.01**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS Ubuntu 18.04.1*]
- **Web server**: [*Apche2  4.29*]
- **PHP**: [*PHP 7.2*]
- **Database**: [*MySQL 5.7.25*]
- **URL(s)**: [*supplier_proposal/contact.php?id=3*]

## Expected and actual behavior
A contact to the third party should be added.
From the list of contacts a contact should be selected, the contact type should be selected and added with "add".

## Steps to reproduce the behavior
After selecting the third party and the partner contact, a "contact type" should be selected. But the list is empty. There are entries for the contact types in the Dictionary.
When clicking on "Add" the error appears: wrong value on parameter 2.

##
![screen_shot_anfrage](https://user-images.githubusercontent.com/49170693/55360948-1a26dd80-54d6-11e9-9724-0ca68fa895c2.png)

**Comment by ATM-Marc** [comment]
See PR #11205. This can't be cleanly fixed in previous versions, it will be available in version 10.0.
