### ISSUE TITLE
Bug Dont save the information

### ISSUE THREAD

**Issue by jmsandovalp1** [Dolibarr/dolibarr#10955]
First I access to HRM > Balance of leave ( ../holiday/define_holiday.php?action=request&leftmenu= )

When I write something in the field Note and then click in the button Update, don´t save the information.

Version Dolibarr 9.0.1

**Comment by ksar-ksar** [comment]
Hi,

Bug confirmed on the demo : https://demo.dolibarr.org/holiday/define_holiday.php
Note are not saved or not diplayed (cell is allways empty)

**Comment by atm-maxime** [comment]
I checked this point. It's not a bug but I understand the confusion. This screen is here to allow you to set/modify the counters of your users. When you set a value with a note, the note is saved in the modification log. Try to change a value with a note, then go to /holiday/view_log.php.
