### ISSUE TITLE
New display for timesheet

### ISSUE THREAD

**Issue by aconits** [Dolibarr/dolibarr#10957]
# Feature Request
To resume implementation of #10899 
What about moving project and company information on each task line ? Like that we can add  more columns from project

![image](https://user-images.githubusercontent.com/10596597/55463977-6cf9b580-55fa-11e9-913e-e69da5e3545e.png)

## Suggested implementation
As standard list
![image](https://user-images.githubusercontent.com/10596597/55464015-826edf80-55fa-11e9-8768-c01318496206.png)
and keep the columns about time spent after all

**Comment by atm-maxime** [comment]
@atm-ph to close ?
