### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by garybaldi26** [Dolibarr/dolibarr#10971]
# Bug

## Environment
- **Version**: 9.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.25
- **Database**: MySQL or MariaDB 5.6.42-log
- **URL**: /dolibarr-9.0.1/htdocs/index.php?mainmenu=home

## Report
Probleme avec le menu Tiers et contact affichage tres long , liste vide, impossible de creer un nouveau

aucun message d'erreur
Slt

**Comment by ksar-ksar** [comment]
Hi,

Normally only English here, if you want French support : https://www.dolibarr.fr/forum

Without any screenshots, logs, description of the problem your issue can be treated => Useless
