### ISSUE TITLE
Error 502 Bad Gateaway after ticking module SYSLOG_CHROMEPHP

### ISSUE THREAD

**Issue by Di-Ny** [Dolibarr/dolibarr#10990]
# Bug
Getting Error 502 Bad Gateway after enabling Log module. The issue have appeared after ChromePHP was checked in the log module. The whole dolibarr application throw a 502 Error after logging page.

## Environment
- **Version**: 9.0.1
- **OS**: Debian Stretch
- **Web server**: NGinx 1.10.3
- **PHP**: 7
- **Database**: MariaDB 5.5.5-10.1.37
- **URL(s)**: *
- ChomePHP extension installed and enebaled.

## Expected and actual behavior
I would expect being able to disable this option (maybe automatically) if a problem occurs after enabling ChromePHP.

## Manual rollback
The only solution I found was disbaling the option manually in the DB: _table_ "llx_const" > _name_ "SYSLOG_HANDLERS" > update _value_  ["mod_syslog_file"] instead of ["mod_syslog_file","mod_syslog_chromephp"]

**Comment by eldy** [comment]
This log handler has been removed and replaced with module debugbar.
