### ISSUE TITLE
Bug: field 'ref' doesn't have a default value (v9.0.2) 

### ISSUE THREAD

**Issue by QuentinPetel** [Dolibarr/dolibarr#11006]
# Instructions

# Bug
At least on page /compta/bank/various_payment/card.php, when adding an entry (accounting record , book entry?) on a bank account, i get the following error message : **field 'ref' doesn't have a default value**

## Environment
- **Version**: 9.0 / 9.0.2
- **OS**: ubuntu 16.04
- **Web server**: nginx version: nginx/1.10.3 (Ubuntu)
- **PHP**: 7.1
- **Database**: mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine
- **URL(s)**:  /compta/bank/various_payment/card.php

## Expected and actual behavior
Can't add an entry (Liste écriture in french) in 

## Steps to reproduce the behavior
-> Clone project, version 9.0
-> Install
-> Create bank account
-> add a first entry => NOT WORKING : **field 'ref' doesn't have a default value**

<img width="1440" alt="Capture d’écran 2019-04-13 à 18 45 46" src="https://user-images.githubusercontent.com/16292377/56082756-deb4d900-5e1c-11e9-864d-80880935ed93.png">

**Comment by thedipeshpatel** [comment]
@eldy ,

Can you please look into this bug on priority and provide fixes as soon as possible. As this bug making struggle to a lot of clients. Please fix this immediately.

Thank you.

**Comment by aspangaro** [comment]
Problem only on fresh install

Resolve this problem with this sql request :
ALTER TABLE llx_payment_salary MODIFY COLUMN ref varchar(30) NULL;
ALTER TABLE llx_payment_various MODIFY COLUMN ref varchar(30) NULL;

**Comment by aspangaro** [comment]
https://github.com/Dolibarr/dolibarr/commit/becf096bf86742b9cb2ffc3358fc0367061b526b

**Comment by aspangaro** [comment]
@QuentinPetel Can you close this issue please ?

**Comment by QuentinPetel** [comment]
Yes, thank you @aspangaro, @eldy !
