### ISSUE TITLE
BUG: Cashcontrol list should not be paginated

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#11015]
# Bug

Cash control uses an iframe to display the bank entries, but this list is paginated which makes the iframe incomplete.

## Environment
- **Version**: 9.X
- **OS**: Debian Stretch
- **Web server**: apache2 
- **PHP**: 7.x
- **Database**: mysql
- **URL(s)**: `compta/cashcontrol/cashcontrol_card.php`, `compta/cashcontrol/report.php`

## Expected and actual behavior

All bank entries inside the period of the cash control should appear in the iframe but only the `N` first appears where `N`is the pagination limit.

## Steps to reproduce the behavior

Set your pagination limit to a small number, let say `3`, open cash control, create more bills with TakePOS than this number, close your cashcontrol and go the the cash control card. Only `3` entries appears.

## Quick and dirty fix

There is a patch for a quick and dirty fix, obviously the right solution is to remove pagination totally on `compta/cashcontrol/report.php` :
```
diff --git a/htdocs/compta/cashcontrol/report.php b/htdocs/compta/cashcontrol/report.php
index 736090bd07..c339a4730a 100644
--- a/htdocs/compta/cashcontrol/report.php
+++ b/htdocs/compta/cashcontrol/report.php
@@ -41,7 +41,7 @@ include_once 'class/cashcontrol.class.php';
 $cashcontrol= new CashControl($db);
 $cashcontrol->fetch($id);
 
-$limit = GETPOST('limit')?GETPOST('limit', 'int'):$conf->liste_limit;
+$limit=PHP_INT_MAX;
 $sortorder='ASC';
 $sortfield='b.datev,b.dateo,b.rowid';
```

**Comment by ptibogxiv** [comment]
It's not a bug... If you activated some experimental Ou develop modules, they disappeared only when you deactivated them.
