### ISSUE TITLE
MAIN_FEATURES_LEVEL

### ISSUE THREAD

**Issue by SteveS17** [Dolibarr/dolibarr#11012]
[*Disable MAIN_FEATURES_LEVEL*]

## Environment
- **Version**: [*9.0.1*]
- **OS**: [*Windows 2012 / Linux*]
- **Web server**: [*Apache/2.4.38*]
- **PHP**: [*PHP/7.3.3*]
- **Database**: [*MySQL or MariaDB 5.5.5-10.1.38-MariaDB*]
- **URL(s)**: [*Affected URL(s)*]

After activating function (1 or 2), impossible to come back in 0.
When I valid 0, in module and application, Developement, and Experimental are always display.

**Comment by ptibogxiv** [comment]
It's not a bug... If you activated some experimental Ou develop modules, they disappeared only when you deactivated them.

**Comment by atm-maxime** [comment]
I confirm, after going back to MAIN_FEATURE_LEVEL 0, experimental and development modules are not shown in the module list, unless they are still active
