### ISSUE TITLE
Feature request: sendEmailsReminder is not working

### ISSUE THREAD

**Issue by julian70400** [Dolibarr/dolibarr#11031]
# Bug
Impossible to send mails through "Envoyer des alertes agenda par e-mails" planned works.

## Environment
- **Version**: 8.0.*
- **OS**: Ubuntu 16
- **Web server**: Nginx
- **PHP**: 5.6
- **Database**: MySQL
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
I was trying to have the planed work "Envoyer des alertes agenda par e-mails" working, but no way to receive any mail.
I checked the source /dolibarr/htdocs/comm/action/class/actioncomm.class.php, especially the sendEmailsReminder method, and it appaers that this method is not totally writted !

## Steps to reproduce the behavior
Try to send mail through "Envoyer des alertes agenda par e-mails" planned works.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

```
public function sendEmailsReminder()
{
    global $conf, $langs;

    $error = 0;
    $this->output = '';
            $this->error='';

    if (empty($conf->global->AGENDA_REMINDER_EMAIL))
    {
            $langs->load("agenda");
            $this->output = $langs->trans('EventRemindersByEmailNotEnabled', $langs->transnoentitiesnoconv("Agenda"));
            return 0;
    }

    $now = dol_now();

    dol_syslog(__METHOD__, LOG_DEBUG);

    $this->db->begin();

            // TODO Scan events of type 'email' into table llx_actioncomm_reminder with status todo, send email, then set status to done



    // Delete also very old past events (we do not keep more than 1 month record in past)
            $sql = "DELETE FROM ".MAIN_DB_PREFIX."actioncomm_reminder WHERE dateremind < '".$this->db->jdate($now - (3600 * 24 * 32))."'";
            $this->db->query($sql);

            $this->db->commit();

    return $error;
}
```

**Comment by atm-maxime** [comment]
You're right, this function is not finished yet. The scheduled job exists but the options in the calendar setup page are only available with MAIN_FEATURE_LEVEL = 2 and the email sending has not been implemented yet.
