### ISSUE TITLE
[Feature Request] Generate product sheet with picture

### ISSUE THREAD

**Issue by Leboubou111** [Dolibarr/dolibarr#11039]
# Feature Request : Generate product sheet with picture

I've already done the new file with code (in attachment)
[pdf_standard.modules.php.txt](https://github.com/Dolibarr/dolibarr/files/3093936/pdf_standard.modules.php.txt)

Example :
[PRODUIT_TEST.pdf](https://github.com/Dolibarr/dolibarr/files/3093938/PRODUIT_TEST.pdf)

Modifications :
- Several aesthetic improvements
      - Added frame "Description", "Additional Information" and "Notes"
      - Framing additional information (weight, size, etc ...)
      - Change caracter size 
- Adding first product picture (same as the "Azur" template) 
      - If set MAIN_GENERATE_SHEET_PRODUCT_WITH_PICTURE to Configuration-> Miscellaneous
      - Possible to define the maximum height picture MAIN_GENERATE_SHEET_PRODUCT_HEIGHT_MAX_PICTURE in mm (default: 110mm)
      - Adaptive width  automatically
- Add URL link if set to string product
- Addition units (Kg, cm, m², etc ...)
- Adding public notes
- Information not displayed to product sheet if string empty
- Automatic page break (with pagehead, pagefoot and  $pdf->AliasNbPages()) if next element height exceeds

Work to Dolibarr 9.0.1, but i think work to older version.

Two hide options to add : ($conf->global->)
- MAIN_GENERATE_SHEET_PRODUCT_WITH_PICTURE -> Show picture to sheet product
- MAIN_GENERATE_SHEET_PRODUCT_HEIGHT_MAX_PICTURE --> Set mm max height picture (110mm by default)

And we must add a missing translations (FR or other language at your choice)
fr_FR --> "Area" --> "Surface"
fr_FR --> "Additional information" --> "Informations Supplémentaires"
fr_FR --> "Internet link product information" --> "Lien Internet Information Produit"
fr_FR --> "Note" --> "Notes"

Work to EN and FR language.

And i've remove useless code.

Please be indulgent, I'm not a developer. It's my first PHP code and I spent 3 days on it.

**Comment by Leboubou111** [comment]
The request is still relevant and not yet covered by latest stable VERSION.

**Comment by Leboubou111** [comment]
Toujours pas ajouter aux nouvelles versions... Des nouvelles ?
C'est pas faute de vouloir aider.

**Comment by BebZ** [comment]
Hello 

Is it a planned integration or it has no Pull Request so it won't be integrated in a near future ? 

Thanks

**Comment by Leboubou111** [comment]
The request is still relevant and not yet covered by latest stable VERSION.
