### ISSUE TITLE
Bug: Adding New user

### ISSUE THREAD

**Issue by killmasta93** [Dolibarr/dolibarr#11036]
Hi,
I was wondering if someone could share some light on howcome i cannot create a user. When i try adding a user it keeps going to the top page instead of adding it. i already added 2 and worked find so im not sure what happend?

Thank you 

## Environment
- **Version**: 9.0.2
- **OS**: ubuntu server 16.04
- **Web server**:  NGINX 1.10.3
- **PHP**: 7.1.28-1+ubuntu16.04.1+deb.sury.org+3
- **Database**: MySQL or MariaDB 5.5.5-10.0.38-MariaDB-0ubuntu0.16.04.1

**Comment by atm-maxime** [comment]
Hard to help you with this few informations. Do you have an error message ?
If after clicking the create button you go back on top of page but still on the creation form, good chance is that a required field is missing.
