### ISSUE TITLE
Shipment module opens wrong ODT Templates

### ISSUE THREAD

**Issue by bartiest** [Dolibarr/dolibarr#11040]
# Bug
When I upload a ODT template in the doctemplate/shipment directory it not shows in the pulldown list in shipments. Even worse, it shows the templates from the doctemplate/orders directory.

Maybe that is the reason the {line_product_options_xxx} are not filled out.

## Environment
- **Version**: 9.0.2
- **PHP**: 7.2

**Comment by atm-maxime** [comment]
Sorry I can't reproduce. Can you give us a screenshot of your setup page (/admin/expedition.php) ?
