### ISSUE TITLE
When you create a new module with modulebuilder and try to click on cancel it make a error

### ISSUE THREAD

**Issue by eucm2** [Dolibarr/dolibarr#11045]
# Bug
When you create a new module with modulebuilder and try to click on cancel it make a error

## Environment
- **Version**: 9.0
- **OS**: Ubuntu 18.04 lts
- **Web server**: Apche2
- **PHP**: PHP 7.2
- **Database**: Mysql
- **URL(s)**: All

## Steps to reproduce the behavior
1.- Create a module.
2.- in this module create a row-
3.- Clck on edit 
4.- Click on cancel

## SOLUTION
In file
modulebuilder/template/myobject_card.php
in line 125
Replace
`else $backtopage = dol_buildpath('/mymodule/myobject_card.php',1).($id > 0 ? $id : '__ID__');`
by
`else $backtopage = dol_buildpath('/mymodule/myobject_card.php?id=',1).($id > 0 ? $id : '__ID__');`

**Comment by MaslinoJ** [comment]
thanks it worked
