### ISSUE TITLE
Bug on adding documents in email form

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#11056]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
Error "Un fichier portant ce nom existe déjà" when adding a document before sending a propal

## Environment
- **Version**: 8.0.4
- **OS**: debian
- **Web server**: Apache
- **PHP**: 5.6
- **Database**: Mariadb
- **URL(s)**: comm/propal/card.php?id=362#formmail

## Expected and actual behavior
It is not possible to remove a document and add it again (because it has to be corrected before send it) 

## Steps to reproduce the behavior
On the mail form, add an additional document.
remove it (because you need to change something ...)
You can not add it again (after corrections) and get this message.

**Comment by ATM-Marc** [comment]
See PR #11195
