### ISSUE TITLE
PostgreSQL migration - Schema does not correspond

### ISSUE THREAD

**Issue by jblion** [Dolibarr/dolibarr#11057]
# Bug
Migration from MySQL to PostgreSQL fails due to schema differences.

## Environment
- **Version**: 9.0.2
- **OS**: Debian 9 Stretch
- **Web server**: Apache 2.4
- **PHP**: PHP 7.0
- **Database**: MariaDB 10.3 - PostgreSQL 11.2

## Expected and actual behavior
I wanted to migrate from MariaDB 10.3 to PostgreSQL 11.2.
I applied following FAQ article with some modifications :
https://wiki.dolibarr.org/index.php/FAQ_Migrate_my_Mysql_database_to_PostgreSQL

### With the "real" dolibarr (4.0.1 upgraded over the time to 9.0.2)

Installer crashes...

### With a fresh 9.0.2
When importing tables, I have following errors (I just write errors once): 

> ERREUR:  la colonne « accountancy_journal » de la relation « llx_bank_account » n'existe pas
> ERREUR:  la colonne « newByMonth » de la relation « llx_c_holiday_types » n'existe pas
> ERREUR:  la relation « llx_c_paiement_temp » n'existe pas
> ERREUR:  la colonne « keyword » de la relation « llx_ecm_files » n'existe pas

I should have no errors.

### With a 4.0.6 version upgraded to 9.0.2
If I start from the same original version than the MySQL's one (4.x.y) and then do all upgrades paths (5,6,7,8,9), I have only one error: 

> ERREUR:  la colonne « newByMonth » de la relation « llx_c_holiday_types » n'existe pas

And finally, I will keep that as I don't manage employees yet.

### 4.0.1 ==> 9.0.2

* Install Dolibarr 4 and upgrade it to 9.0.2 step by step
* Reset configuration file
* Run installer
* When filling database details, the page stops loading

### Fresh 9.0.2

* Install fresh dolibarr 9.0.2
* ` SELECT dol_util_triggerall(false);` 
* `select concat ('truncate table ',table_name,' cascade;') from information_schema.tables where table_schema='public' order by table_name;` and copy/paste all truncate queries
* ` psql -d d2 -f /home/vhosts/dolibarr_pgsql/documents/admin/backup/ready.sql > log.d2 2>&1` 

## Use case
Typical migration from MySQL to PostgreSQL

## Suggested implementation

* Provide the full schema as SQL for PostgreSQL (to fix issues quickly)
* Fix schema inconsistencies

**Comment by ghost** [comment]
Long time ago I develop this module https://www.dolistore.com/fr/outils-externes-et-appli-mobiles/683-Migrate-to-PostgreSQL.html I'm not sure it still accurate for this version

**Comment by jblion** [comment]
Hi, 

I tried it. It didn't work as expected.

**Comment by ghost** [comment]
I've try this :
Fresh install 4.0 on pgsql, migrate to 9.0, works fine, no crash, may be as I don't have data, it's fast and quick, and the error you get is timeout or something ?

I also try fresh install 9.0 (even develop branch) I don't get your errors.

**Comment by jblion** [comment]
Hi, 

Yes, installing a 4.0.x version and upgrade it works (almost) as expected. But when I reset the configuration file to create the PostgreSQL schema instead of the previous MySQL one, the installer pages crashed with an incomplete blank page.

With a fresh 9.0.x, the install process ended completely, but some fields were missing compared to my MySQL database.
