### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by GertMoolman** [Dolibarr/dolibarr#11087]
# Bug

## Environment
- **Version**: 9.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 5.6.40
- **Database**: MySQL or MariaDB 10.0.38-MariaDB-cll-lve
- **URL**: /compta/facture/card.php?facid=25

## Report

Adding a line to a new invoice takes for ever to load and often hangs

**Comment by simnandez** [comment]
I can not reproduce the problem, 
Can you describe the problem a bit more?
Do you have external modules installed?

**Comment by GertMoolman** [comment]
Good evening 
Thank you so much for getting back to me. 
When creating a (loading) a vender invoice when clicking on add the line adds instantly, however when creating a customer invoice when we click add it takes at least 30sec if not more to load the line same when we click on apply absolute discount and when clicking validate but all this only under customer invoices this resulting in it taking at least 3 to 4 minutes to create one invoice and like I said it’s not the case with vendor invoices. 
Thanks again 
Gert
    	
    	

    	Get Outlook for iOS
    
  




On Thu, May 9, 2019 at 8:53 PM +0200, "Juanjo Menent" <notifications@github.com> wrote:












I can not reproduce the problem,

Can you describe the problem a bit more?

Do you have external modules installed?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Dolibarr/dolibarr/issues/11087#issuecomment-491023653",
"url": "https://github.com/Dolibarr/dolibarr/issues/11087#issuecomment-491023653",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
