### ISSUE TITLE
Bug: some events loads the one day but other days the same event (to create) is forbidden 

### ISSUE THREAD

**Issue by GertMoolman** [Dolibarr/dolibarr#11085]
# Bug

## Environment
- **Version**: 9.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 5.6.40
- **Database**: MySQL or MariaDB 10.0.38-MariaDB-cll-lve
- **URL**: /comm/action/card.php?action=edit&id=258

## Report
 Bug: some events loads the one day but other days the same event (to create) is forbidden

**Comment by ghost** [comment]
Could you add more details ?

**Comment by GertMoolman** [comment]
All my users can make event entries with no issues, however one of my users will be able to make one entry just fine yet the next or another entry will give an FORBIDDEN error, this happens at random but always with the same user (only the one user seems to be affected) 

 

Thank you 

 

Gert
