### ISSUE TITLE
Display skips to another account after reconciliation.

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#11099]
# Bug
Display skips to another account after reconciliation.

## Environment
- **Version**: 8.0.3
- **OS**: Mageia 6
- **Web server**: Apache
- **PHP**: 7.2
- **Database**: MariaDB
- **URL(s)**: http://localhost/dolibarr/htdocs/compta/bank/bankentries_list.php?action=reconcile&search_conciliated=0&contextpage=banktransactionlist&ref=3887&search_account=4
After the reconciliation, the link is:
http://localhost/dolibarr/htdocs/compta/bank/bankentries_list.php?id=
## Expected and actual behavior
I have four active bank accounts.
I reconcile the account number 3887 (see ref in the link). After the action, display return to another bank account (the CIC one).
I expect it will stay on the same bank account.
The page also doesn't display the account header.
It seems that the link should have id=4 instead of id= in the url.

**Comment by papoteur-mga** [comment]
I have not tested it with recent releases. Thus, nothing says that this bug is solved.

**Comment by dpriskorn** [comment]
Update to v12 and reopen if the problem persists.
