### ISSUE TITLE
Pb in Function  showinputtype on object commonobject

### ISSUE THREAD

**Issue by kollibar** [Dolibarr/dolibarr#11104]
# Bug
There is some incoherence in the function showInputField from the object CommonObject (file /core/class/commonobject.class.php):
The parameter variable **$var** is not used and quickly replace by **$this->fields[$key]** and in the continuation of the function sometimes it's used **$var** and sometimes **$this->fields[$key]** to access to the same data.

## Environment
- **Version**: [*9.0.1*]
- **OS**: [*all*]
- **Web server**: [*all*]
- **PHP**: [*all*]
- **Database**: [*all*]
- **URL(s)**: [*NA*]

## Expected and actual behavior
The function should work with the parameter variable and not with an other data.
In my case I pass to this function a modified $var (modified from $object->fields[key]), modified to add some information about recommanded choice depending of the context, so it's not working as expected.

I think to be correct all the _$this->fields[$key]_ should be change to _$var_ and the line _$var=$this->fields[$key]_ should be removed.

[*Extract from /core/class/commonobject.class.php, start at line 5279*]
/**
 * Return HTML string to put an input field into a page
 * Code very similar with showInputField of extra fields
 *
 * @param  array   		$val	       Array of properties for field to show
 * @param  string  		$key           Key of attribute
 * @param  string  		$value         Preselected value to show (for date type it must be in timestamp format, for amount or price it must be a php numeric value)
[...]
 
function showInputField(**$val**, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0)
{
global $conf,$langs,$form;

if (! is_object($form))
{
	require_once DOL_DOCUMENT_ROOT.'/core/class/html.form.class.php';
	$form=new Form($this->db);
}

**$val=$this->fields[$key];** 

$out='';
$type='';
$param = array();
$param['options']=array();
$size =**$this->fields[$key]**['size']; 
// Because we work on extrafields
if(preg_match('/^integer:(.*):(.*)/i', **$val**['type'], $reg)){ 
    $param['options']=array($reg[1].':'.$reg[2]=>'N');
    $type ='link';
} elseif(preg_match('/^link:(.*):(.*)/i', **$val**['type'], $reg)) {
    $param['options']=array($reg[1].':'.$reg[2]=>'N');
    $type ='link';
} elseif(preg_match('/^sellist:(.*):(.*):(.*):(.*)/i', **$val**['type'], $reg)) {
    $param['options']=array($reg[1].':'.$reg[2].':'.$reg[3].':'.$reg[4]=>'N');
    $type ='sellist';
} elseif(preg_match('/varchar\((\d+)\)/', **$val**['type'],$reg)) {
    $param['options']=array();
    $type ='varchar';
    $size=$reg[1];
} elseif(preg_match('/varchar/', **$val**['type'])) {
    $param['options']=array();
    $type ='varchar';
} elseif(is_array(**$this->fields[$key]**['arrayofkeyval'])) {
    $param['options']=**$this->fields[$key]**['arrayofkeyval'];
    $type ='select';
} else {
    $param['options']=array();
    $type =**$this->fields[$key]**['type'];
}
	$label=**$this->fields[$key]**['label'];
	//$elementtype=**$this->fields[$key]**['elementtype'];	// Seems not used
	$default=**$this->fields[$key]**['default'];
	$computed=**$this->fields[$key]**['computed'];
[...]

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by dpriskorn** [comment]
$val= does not appear at all in https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/class/commonobject.class.php so this is fixed
