### ISSUE TITLE
Bug: Can not enter foreign currency in product/buyer prices correctly in Dolibarr 9.0.1

### ISSUE THREAD

**Issue by JoostParent** [Dolibarr/dolibarr#11123]
# Bug

When entering buyer prices in foreign currencies this is dealt with in a manner which I do not understand and seems to be incorrect.

## Environment

- **Version**: 9.0.1
- **OS**: Windows NT DESKTOP-MAPUB1L 6.2 build 9200 (Windows 8 Home Premium Edition) i586
- **Web Server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: 5.5.12
- **DataBase**: MySQL or MariaDB 5.0.45-community-nt

## Expected and actual behaviour

One would expect when buyer prices are entered that the price is in the selected currency for this particular product. An item price of 22.05 with a minimum order quantity gives a total minimum order price of 110.25. The entry form clearly shows local currency and this is set to Euro in this particular case. My local currency is Thai Baht. The rate for THB/EUR is also clearly shown. When the price is entered the field clearly states "Price for this min. qty (w/o discount) (currency)". with a reference to "Currency" in brackets. We than get one more field that shows the calculated value which appears to be the value entered in Euro divided by the currency rate and consequently results in a value of 3.0902954911117213. Above is shown in attached screenshot. This implies that Dolibarr is considering the price that was entered in the local currency of Thai Baht (THB) in this case and dividing it by the rate to produce a price in Euros (EUR).

![Picture 03](https://user-images.githubusercontent.com/36702122/57177121-798c5a80-6e93-11e9-9aab-2bd8f74b0a01.png)

Now it is possible that I am doing something wrong of course and if this is the case, please point out to me how to enter buyer prices correctly. However, I strongly believe that international buyer prices are dealt with incorrectly.

The below screenshot of the overview of buyer prices shows the same issue again.

![PIcture 01](https://user-images.githubusercontent.com/36702122/57177201-9d03d500-6e94-11e9-9eae-b8118af5ec14.png)

And in the products list view the price is shown wrongly yet again as seen in the below screenshot.

![Picture 02](https://user-images.githubusercontent.com/36702122/57177225-d6d4db80-6e94-11e9-8fdf-83bc529a53c4.png)

As mentioned before, I think this is a bug. Is there a fix for this?

**Comment by atm-maxime** [comment]
Can you tell us what is your system currency ?
In your example, price for 5 qty is 110.25 €, so for 5 in your currency is 3,090. Then for 1 is 22,05 €, and for 1 in your currency is 0,61806. For me the 3 screenshots are correct.

To remember, when you add a new supplier proce on a product, the price you enter is always related to the quantity.

**Comment by JoostParent** [comment]
My system currency is Thai Baht (THB).

**Comment by JoostParent** [comment]
Dear Maxime,

Thanks for your response and I appreciate the time you spend to help me.

I was confused as well and spend a long time before I posted. But let me go
through how I got to my conclusion step by step.

The starting point is obviously the set-up. I am here assuming that this
has been done ok, at least as far as setting up my home currency and
additional currencies are concerned. My home currency is the Thai Baht
(THB). And some of the additional currencies are US Dollar (USD), Euro
(EUR), Singapore Dollar (SGD) and a few others.

- The first thing you do is entering a new product. Now here I spend quite
a bit of time, but I do not see any other way that entering the price in
the currency we pay in. It would not make a lot of sense to expect the user
to calculate the price in Baht (THB) because it is the quoted price that
may change from the manufacturer and obviously because of currency exchange
rates. The entered price was 110.25 EUR for 5 pcs, which is the minimum
quantity.. You can see the exchange rate I use at that time being 35.6762
THB. This should result in a total price of 39330.30105 THB, or a pcs price
of 786.66021 THB.
- When all is entered you can see the following.

The field 'Currency' shows 'Euros (€)'. This is correct I would say.

The field 'Price for this min. qty (w/o discount) (currency)' shows
'110.25' and 'Net of tax'. This too is correct I think. The field name
clearly indicates that the value should have been entered in Euros because
of the reference to 'Euro' in the field "Currency'.

And the next field is 'Price for this min. qty (w/o discount)' with a
calculated value that is obviously derived from the euro divided by the
exchange rate. And this is where things go wrong. This should have been
multiplied by the exchange rate and not divided by the exchange rate.

The other 2 screenshots merely confirm the above. In the 2nd screenshot the
field 'Unit price (net)' is  0.61806. This too is a calculated value. In
this case it is the value from field 'Price quantity min. (net of tax)'
divided by the value of field 'Minimum Qty'. And again you can see that the
values (both) are calculated wrong in the sense that it should have been
devided by the exchage rate.

And just now while I am writing all this I am thinking by myself that I
could maybe enter the exchange rate differently. Not 35 THB/EUR, but 1/35
EUR/THB. Let me try this.

Ok, I changed the currency settings in the multi currency module. It
actually clearly states that I should have used the inverse exchange rate
from what I was using. My apologies for having bothered you with this.

However, I did notice something else though. After having changed the
exchange rate nothing changed initially. Only when I manually entered the
correct exchange rate in the form to add buyers price  the correct price
was shown. Does Dolibarr not update automatically the latest echange rates
into the product prices? I have seen that sometimes the database needs a
little time to update, this could be the case, but I am not sure.

Best Regards,

Joost Parent (Joey)

**Comment by JoostParent** [comment]
Hi Maxime,

I see on the multi currency set-up page that the first 2 lines on the top
should allow for this. the first option is:

'Use the date of the document to find the currency rate, instead of using
the latest known rate'.

and the second option is:

'When an object is created from another, keep the original rate from the
source object (otherwise use the latest known rate)'.

Both options were set to 'Yes'. When I change them to 'No', and
consequently click on the 'Modify' button they both return the original
value of 'Yes'. What am I doing wrong? This should update the product
prices to the latest exchange rate right?


Best Regards,


Joost Parent (Joey).

**Comment by atm-maxime** [comment]
Hi !
I took time to read your answers.
So yes this was an exchange rate misconfiguration, I think you entered in the setup that 1 THB = 35 EUR :)

When you change your exchange rates, Dolibarr does not recalculate the purchase prices according to the new rate. Maybe it's a feature request to propose. Can you open a new issue about that ?

If you create a supplier order, the current exchange rate is used when adding the product in the supplier order.

I had a look at your issue in the setup page. I fixed it, wait for it to be merged.

**Comment by JoostParent** [comment]
Hi Maxime,

Again thanks for your help.

I have no issue opening a new issue with a feature request. However, I am
quite new to this. Do you just want me to open a new issue here like this
issue? If there is a specific location for this, please advise me.

Regarding the set-up page. You say it is fixed. Does this mean that when I
install the next update it should be solved? Or merged as you call it? Or
am I on the wrong track altogether now?

Joey

**Comment by atm-maxime** [comment]
You can open an issue just like this one but call it "Feature Request : add an option to update all purchase prices after modifying exchange rate".

When you will install the next update the setup page should be fixed :)

Cheers.

**Comment by JoostParent** [comment]
Hi Maxime,

Ok, all clear. I am going to Japan today and will be back in a couple of
days. I will address this early next week.

Joey
