### ISSUE TITLE
Missing translation in Email of Password forgotten - 902

### ISSUE THREAD

**Issue by dolivn** [Dolibarr/dolibarr#11135]
# Bug
-User submits Password forgotten form, he gets a New Password Email without translation.

## Environment
- **Version**: 9.0.2
- **PHP**: 7.1.28

## Expected and actual behavior
-Email of 'Subject New Password' should be translation

## Steps to reproduce the behavior
-At login page >> Click Password forgotten >> File form >> Get Email without translation.
-Tested on en_US language.

**Comment by inoveaconseil** [comment]
Work for me
