### ISSUE TITLE
Error while creating Stock movement using API

### ISSUE THREAD

**Issue by mwaleedraza** [Dolibarr/dolibarr#11141]
I am facing this error while using Stock movement create API. For the other like products etc API is working well but for stock movement it shows the below error message. 

Code 503 
Message Service unavailable : Error When create stock movement .

Any help will be appreciated

**Comment by fappels** [comment]
Can you share your createStockmovementsModel parameter and dolibarr version.

**Comment by mwaleedraza** [comment]
Thanks @fappels for commenting. 

**This is what I am using for new entry** 
$newEntry = [
			"label"	=> 'a',
		];
$newEntryResult = $this->CallAPI("POST", $apiKey, $apiUrl."stockmovements/".$fk_result, 

In same way I have created products etc but for stock movement I get  this error 'Message Service unavailable : Error When create stock movement .'.

Just a note I tried to fetch all stock movement and that API works well, issue I am facing only on creation.

**Comment by fappels** [comment]
Hello @mwaleedraza,
You'r welcome. This not a bug, you are using wrong parameters
Should be 
$newEntry = [
"product_id": your product id, 
"warehouse_id": your warehouse id, 
"qty": your qty to move, 
"movementcode": a movement code string, 
"movementlabel": your movement label string
]

You don't need to put fk_product as a path parameter, is already in request data

Please close issue if solved.

**Comment by mwaleedraza** [comment]
@fappels Thanks for reply and sorry from my side for following back so late. I have used the same parameters as you have mentioned but error still persists . I have used this entry list 
 $newEntry = [
            "product_id"    => '123',
            "warehouse_id" => '34',
            "qty"    => '1',
            "lot"    => '1',
            "movementcode" => 'INV123',
            "movementlabel" => 'lbl',
            'price' => '1',
        ];

Call :             
CallAPI("POST",$apiKey,$apiUrl."stockmovements/".$fk_result,json_encode($newEntry));

I have created many tables records successful like db_categories, db_product etc but this stockmovements is not working. Help will be appreciated.

**Comment by fappels** [comment]
@mwaleedraza Are you sure the given ID and lot values exist in your database? Also see you are still using path parameter.

**Comment by mwaleedraza** [comment]
This is fixed but one question still. I added a new column in stock_mouvement table but not able to sync that column value with API ? column id I created  is ref_ext

**Comment by laudeco** [comment]
@mwaleedraza how did you add this column? Just to be sure of your process
Cheers
L.

**Comment by mwaleedraza** [comment]
@laudeco I added it directly in database, I got the solution for this I was adding it in wrong way. 

Thanks for timely response I appreciate.

**Comment by mwaleedraza** [comment]
I am closing this issue. Thanks @laudeco @fappels
