### ISSUE TITLE
Bug: deposit with stripe issue

### ISSUE THREAD

**Issue by Crush33** [Dolibarr/dolibarr#11150]
## Environment
- **Version**: 9.0.2
- **OS**: debian 9
- **Web server**: apache 2
- **PHP**: 7
- **Database**: mariadb 10

## Expected and actual behavior
Expected : Make a deposit on doli, client pay with stripe and all should work correctly.
Actual behavior : just after the payment, the client get this error message

![capt](https://user-images.githubusercontent.com/2492697/57442193-bec1db00-724b-11e9-9391-7d1503add7d8.png)

## Steps to reproduce the behavior
Make a payement with stripe on deposit

dolibarr forum thread : https://www.dolibarr.fr/forum/12-howto--aide/63475-erreur-paiement-stripe-sur-les-factures-d-accompte

**Comment by ATM-Marc** [comment]
See PR #11218
