### ISSUE TITLE
Can not create User groups

### ISSUE THREAD

**Issue by SBA18** [Dolibarr/dolibarr#11159]
Hi,
I can't create groups on Users/Groups with admin level.

Dolibarr version : 9.0.3
local test with windows 10 using laragon 4.0.12

**Comment by ksar-ksar** [comment]
Hi,

What is the meaning of "I can't" ?
You do not have the right buton or error message or what ?

**Comment by SBA18** [comment]
I have  this error : 

![1](https://user-images.githubusercontent.com/10333576/57519522-cb156900-731b-11e9-81d1-3554b0677c53.png)

I have admin level here it's

![2](https://user-images.githubusercontent.com/10333576/57519625-07e16000-731c-11e9-9664-5ec88d1dd162.png)

**Comment by benyaminl** [comment]
> I have  this error :
> 
> I have admin level here it's

Using multi company module or not?

**Comment by SBA18** [comment]
@benyaminl no, I don't use multiple company module.

**Comment by benyaminl** [comment]
> @benyaminl no, I don't use multiple company module.

Quite strange, maybe we need other people that have the same problem come here. I have no problem with the user. I have no problem on my behalf.

**Comment by SBA18** [comment]
I reinstalled and it works now. Maybe a bug from my test environment. Thanks for your support
