### ISSUE TITLE
Bank entries: not converted to account's currency

### ISSUE THREAD

**Issue by davidNDU** [Dolibarr/dolibarr#11163]
# Bug
Bank account A has currency EUR, vendor V has currency UGX, supplier invoice and payment are done in UGX. At Bank | Cash -> List entries, all the entries get summed up without a conversion of the currencies. This means UGX values are summed up with EUR values.

## Environment
- **Version**: *9.0.2*
- **OS**: *Linux*
- **Web server**: *LiteSpeed 7.2*
- **PHP**: *7.2.18*
- **Database**: *MySQL or MariaDB 10.3.14*
- **URL(s)**: *https://nduwrdc.org/dolibarr/*

## Expected and actual behavior
*Each payment in a currency different to the bank account's must be converted first.*

## Steps to reproduce the behavior
* Create bank account in EUR
* New supplier invoice with currency UGX (other than EUR (conversion <>1)
* Add 'not a predefined entry of type product' with some U.P. in UGX
* Validate invoice and enter payment (and validate)
* Look at bank entries of EUR-account

## [Attached files]
![Payment](https://user-images.githubusercontent.com/40593993/57533256-fe6ced80-7345-11e9-9be2-b93b339659f7.PNG)
![Transaction](https://user-images.githubusercontent.com/40593993/57533250-fb71fd00-7345-11e9-8168-ed5bbed7ac0b.PNG)
![Bank entries](https://user-images.githubusercontent.com/40593993/57533241-f614b280-7345-11e9-85cb-2cccedb5493b.PNG)

**Comment by ATM-Marc** [comment]
Working on it

**Comment by ATM-Marc** [comment]
Works for me

**Comment by davidNDU** [comment]
Does that mean, the problem is with the user? To me, the malfunction is repeatable. What am I doing wrong? On the bank entries I get values representing different currencies. My only work-around is to change the amount on the Transaction card.

**Comment by ATM-Marc** [comment]
When I follow your steps in 9.0.2 (account in EUR, supplier invoice in any other currency, free line with unit price in this currency), the payment and bank entry are all in EUR. Did I miss a step of your process ?

**Comment by davidNDU** [comment]
Meanwhile there was an upgrade tp 9.0.3 - the other components did not change.
Here are the steps to reproduce:
1) Create Bank account Currency=EUR
![Doli1](https://user-images.githubusercontent.com/40593993/58007363-d40ff280-7af2-11e9-96de-e4c337d52988.PNG)
2) Create Vendor with Currency=UGX
![Doli2](https://user-images.githubusercontent.com/40593993/58007366-d4a88900-7af2-11e9-9041-d8eff4bd62f6.PNG)
3) Create new invoice with Vendor where Currency=UGX
![Doli3](https://user-images.githubusercontent.com/40593993/58007367-d4a88900-7af2-11e9-97e2-db43aac1ad68.PNG)
4) Add one none-predefined product with some price and Validate 
![Doli4](https://user-images.githubusercontent.com/40593993/58007368-d5411f80-7af2-11e9-9b4c-10b26967f35b.PNG)
5) Enter payment
![Doli5](https://user-images.githubusercontent.com/40593993/58007369-d5411f80-7af2-11e9-922c-9734d7ec905f.PNG)
6) Validate payment
7) On the transaction card you can see the UGX value displayed as EUR - no convertion.
![Doli6](https://user-images.githubusercontent.com/40593993/58007372-d5d9b600-7af2-11e9-910e-6f03d64b5f76.PNG)
8) At the bank entries of the account you can see how the values are summed up, but the value in UGX is not converted to EUR, hence the sum is wrong.
![Doli7](https://user-images.githubusercontent.com/40593993/58007919-fbb38a80-7af3-11e9-8aa5-7c447e4ca843.PNG)

**Comment by ksar-ksar** [comment]
Hi,

Have you checked with new version 13 of Dolibarr ?

**Comment by davidNDU** [comment]
Just checked it with 13.0.0
The bug remained. The currencies are still mixed up and not converted

**Comment by davidNDU** [comment]
Confirmed the bug with 13.0.2

Invoice in USD
Paid with EUR account
Bank entries are mixed but not converted: EUR and USD are added up.
