### ISSUE TITLE
Required Complementary attributes - no effect in "select list" mode

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#11169]
# Bug
Required Complementary attributes seems to have no effect in "select list" mode)
the field is correctly in bold
but we can validate without selecting any value (tested on third party and product)

note : it works fine with other modes like "string"

## Environment
- tested on 8.0.4 - 9.0.2 - 9.0.3

## Expected and actual behavior
A blocking message should appear and indacte that we have to select a value for this complementary attribute.

## Steps to reproduce the behavior
- create a complementary attribute, select list on third party for example, with some values, and click on "requiered"
- create a new third party without selecting any value in the complementary attributes
-> no warning or error message

## Suggested implementation
add a blocking warning message if no value selected (like we have in "string" mode if empty for example)

**Comment by Metalicss** [comment]
We have same issue (9.0.3)

**Comment by ATM-Marc** [comment]
See PR #11202

**Comment by Arre8** [comment]
Thanks :)

Works perfectly with third parties but another user seems to have the same problem on "Members".
(both Member screen and Public self-subscription form screen)

https://www.dolibarr.fr/forum/510-adherentsassociation/64474-attributs-supplementaires-requis

**Comment by Jacques83300** [comment]
Hello,
I have updated the file htdocs/core/class/extrafields.class.php in release 9.0.3 with the changes you describe in [cd75794](https://github.com/Dolibarr/dolibarr/commit/cd75794aaac0b9e98711e707e2cfe1a595395abe) but it doesn't seem to fix the issue when using an attribute of type 'select list'. In this case, when filling a self-subcription form, no message is shown if a mandatory field with select type is not filled.

https://www.dolibarr.fr/forum/510-adherentsassociation/64474-attributs-supplementaires-requis

Thanks for your support.
