### ISSUE TITLE
API REST Explorer - impossible d'afficher les éléments

### ISSUE THREAD

**Issue by lm699** [Dolibarr/dolibarr#11172]
# Bug
Je rencontre une erreur lors du chargement de l'explorer d'api de dolibarr. Je n'ai pas d'erreur dans les logs ou même d'erreur affichée. Je suis hébergé chez OVH. J'arrive bien à générer une clé API (à condition que le mode production soit décoché). Cependant, je n'arrive pas à afficher correctement l'explorer tel que les exemples sur le site de dolibarr. C'est une installation toute fresh, moins d'un mois.

## Environment
- **Version**: [*9.0.2*]
- **OS**: [*Debian*]
- **Web server**: [*Apache 2.4*] -> serveur informations : https://apache.cloudweb-infos.hosting.ovh.net/
- **PHP**: [*7.2*] -> phpinfo complet : https://phpfpm-72.cloudweb-infos.hosting.ovh.net/
- **Database**: [*MySQL 5.7*]
- **URL(s)**: api/index.php/explorer/

## Steps to reproduce the behavior
Avoir un serveur OVH performance 2, installer dolibarr depuis github (version 9.0.2), activer le plugin API REST, se rendre sur le lien indiqué dans le module.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Capture d’écran](https://user-images.githubusercontent.com/44873905/57630895-be547780-759e-11e9-8874-45fe1fc19701.png)

Je vous remercie par avance de votre aide.

**Comment by zigastegu** [comment]
I think I had same issue.
I changed file: api/index.php
I needed to add:
![image](https://user-images.githubusercontent.com/1379063/77490142-587d8100-6e3a-11ea-8004-6cc38535501d.png)


Because URL resolution does not work in other case. It is probably server dependant. I tried:
PHP7.3, 7.4, 5.6

$SERVER_['PHP_SELF'] returns only "/api/index.php", missing /explorer

**Comment by dpriskorn** [comment]
Seems to be fixed.
