### ISSUE TITLE
invoice due date not entered correctly in bulk invoice creation

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#11185]
# Bug
[*Due date set in client card is not properly adopted in invoice in bulk creation of invoices.*]

## Environment
- **Version**: [*9.0.2*]
- **OS**: [*Ubuntu*]

## Expected and actual behavior
[*When creating invoices in bulk the invoice terms set on client level should be adopted correctly. *]

## Steps to reproduce the behavior
[*create multiple orders and select multiple orders in orderlist. Choose invoice orders from top of screen pull down menu, select validated invoices "yes". All invoices are created with due date set on same date as creation date*]

**Comment by atm-maxime** [comment]
I just tested in 9.0.4 and the behaviour is different. When you create 1 invoice from the order list, the created invoice uses the payment terms and conditions of the first order selected for the customer.

**Comment by GheeEasy** [comment]
It is about bulk action 




Andreas Giel


Ghee Easy







On Fri, May 17, 2019 at 11:42 PM +0200, "Maxime Kohlhaas" <notifications@github.com> wrote:












I just tested in 9.0.4 and the behaviour is different. When you create 1 invoice from the order list, the created invoice uses the payment terms and conditions of the first order selected for the customer.

**Comment by atm-maxime** [comment]
Yes, that's what I tried, bulk action to create an invoice for several orders. Payment terms and mode are retrieved from the first order selected, not the customer card.

**Comment by GheeEasy** [comment]
Ok strange. I will try again

**Comment by GheeEasy** [comment]
This proplem is solved. It turned out exacly for those customers I made the bulk action for payment terms where not set. sorry for the inconvenience...
