### ISSUE TITLE
Feature Request: Arrange tasks for a project or lead in Ascending or Descending order

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#11181]
# Bug
There is task card under perticular project. Now we have lots of tasks for project. We want to rearrange task in ascending or descending order by clicking the **Ref. task** or any other menu link of the task. Currently this is not available.

**Comment by atm-maxime** [comment]
You're right, currently on the project card, task tab, the task list is not sortable by clicking on the columns. But this is a feature request (function not yet implemented), not a bug.

**Comment by alsoft10** [comment]
@atm-maxime Thank you for your edit. Yeah, it's a new feature Dolibarr need to implement. I want to actively participate in Dolibarr development project as a project manager. Is this possible?

**Comment by atm-maxime** [comment]
Thanks ! If you want to help the project but don't do code, you can help by tracking issues and report them here (just like you did), by translating the software on https://www.transifex.com/dolibarr-association/dolibarr/dashboard/ or simply by promoting the software around you !
All informations here : https://wiki.dolibarr.org/index.php/Main_Page

**Comment by alsoft10** [comment]
Thank! I will follow.

**Comment by alsoft10** [comment]
Thank you very much @eldy and @atm-maxime for this wonderful project. I have requested the feature of **Arranging the tasks in ascending or descending order by clicking on the task reference column ** inside task card of a project. It is still not implemented in Dolibarr 12.0.4. I want to know whether it is going to be implemented. It's really an important features if a project has more than 10 task. On the other hand I am very experienced software developer with 11 years of core software development experience. I want to be one of the top developer for this project. I can fix this feature within 30 minutes. Let me know how to start with.

**Comment by Thierry-81** [comment]
Hi Everyone,
This feature is still not implemented in Dolibarr 15.0.1. Can you re-open this request ?
Thank you very much for your job, this erp is the best I tried for a long time !
