### ISSUE TITLE
Bug: The CSS of the box on the image seem to have failed.

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#11191]
# Bug   Pls see the picture. I try to clone a price offer but the box popping up is weird. I guess the CSS is the problem.
![Skärmklipp](https://user-images.githubusercontent.com/24247236/57936885-15bb5600-78c5-11e9-95d0-56c9905f0cc9.JPG)

## Environment
- **Version**: 9.0.3
- **OS**: Linux
- **Web server**: Apache/2.4.25
- **PHP**: apache2handler 7.2.16-1+0~20190307202415.17+stretch~1.gbpa7be82
- **Database**: MySQL or MariaDB 5.5.5-10.1.38-MariaDB-0+deb9u1
- **URL**: /azerty/htdocs/comm/propal/card.php?id=470&socid=17658&action=clone&object=propal

**Comment by atm-maxime** [comment]
Hi ! I can't reproduce on a 9.0. Which browser are you using ? Can you try on others ?

**Comment by hasse-basse** [comment]
Hi. Used it on latest version of Chrome, and it is still not working there. On your request I tried it on Edge and there the layout is fine, but somethings is sour with JS I guess, because the drop down menu for clients does not work.

**Comment by hasse-basse** [comment]
Hi again. In Firefox all is fine. About the dropdown menu in Edge, it works sometimes, sometimes not. So 

**Summary**
- Chrome layout is broken
- Edge Layout is fine but problems with drop down manu
- Firefox all is fine.

**Comment by ghost** [comment]
Unfortunately I've only see this on windows / chrome.
I've find a work around is to set into thirdparty module the option to display drop down list 1 or more caraters.
