### ISSUE TITLE
Date issue when adding a new line in an expense report

### ISSUE THREAD

**Issue by ggouzy** [Dolibarr/dolibarr#11193]
I tried to use Dolibarr's expense report feature, but I'm faced with a strange behavior.
The expenses dates displayed in the PDF document are the day before the dates I've set in the form.

If I try to edit an existing line, the date displayed changes to the day before the day I've set. And when I save it without changing date, original date came back (Link to a screencast: https://drive.google.com/open?id=1pcy-kCaAP0aWueEGgN1UYJ-ULs9ZnUaA)

![2019-05-17_17h15_45](https://user-images.githubusercontent.com/14732266/57938111-bc085b00-78c7-11e9-92cd-456e36574804.png)

![2019-05-17_17h17_23](https://user-images.githubusercontent.com/14732266/57938112-bca0f180-78c7-11e9-9671-79ae02123d57.png)

**Comment by atm-maxime** [comment]
Hi. I tried on 8.0 and 9.0 and I can't reproduce. Maybe it comes from your server setup
