### ISSUE TITLE
[BUG] default date on monthly VAT filter report 

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#11228]
# Bug
When i consult the monthly VAT report /compta/tva/index.php?leftmenu=tax_vat
the default interval date is false when your fiscal year does not begin on 01/01/2019:

example : my fiscal year begin on 01/10/2018
and today : 20/05/2019
the default interval date filter is set to 01/10/2019 - 30/09/2020
on year more than it shoulds (it should be 01/10/2018 - 30/09/2019)

## Environment
9.0.3

# Feature Request
compare the date of the actual day of consultation to adjust the default date on filter.

**Comment by papoteur-mga** [comment]
Same behaviour here and same request.
