### ISSUE TITLE
Feature Request: Security

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#11234]
# Informations
In an **old** Dolibarr version a hacker manage to place on my server some pages with tricky names (link.php for example). I don't know if it was an error in my server config or a bug in Dolibarr.

_As i done in Dolibarr to check files intergrity, what do you think about this:_

# Feature Request
Check all Dolibarr files (excluding custom I think) and if a file is not in the official list display an error/alert.

Tks for reading

**Comment by atm-maxime** [comment]
Did you use the Dolibarr file integrity check ? It's available in home > administration tools > Dolibarr infos

**Comment by dolibarr95** [comment]
Hi
Ok I thought this check only the original files list (and not all the files).

**Comment by dolibarr95** [comment]
tks ;)
