### ISSUE TITLE
Add accountancy export option for Sage50 Swiss

### ISSUE THREAD

**Issue by a-schild** [Dolibarr/dolibarr#11235]
# Feature Request
Add accountancy export option for Sage50 swiss

## Use case
In switzerland the Sage50 swiss edition is very largely used by smb companies.
Addind the option to export in this format would help spread Dolibarr in Switzerland

## Suggested implementation
Patch request follows

## Suggested steps
Apply Patch request

**Comment by a-schild** [comment]
Patch now includes text translations for switzerland and conforms to the coding styles

**Comment by atm-maxime** [comment]
Thanks for contributing !
