### ISSUE TITLE
Customer reference not added to invoice list 

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#11230]
# Bug
[customer reference not added to invoice list when creating invoices in bulk. They do apear on the invoices themselves. ]

## Environment
- **Version**: [9.0.2]
- **OS**: [Ubuntu]

## Expected and actual behavior
[customer reference should be taken over from order and be diaplayed in invoice list. ]

**Comment by atm-maxime** [comment]
The bulk invoicing of orders allows to have several orders in the same invoice. So we can't have the customer ref of the order on the invoice. But each invoice line contains the order reference and date. We should add the customer reference as well.

**Comment by GheeEasy** [comment]
We always use seporate invoices per order. On the pdf output the customers order reference is displayed correcty 
![afbeelding](https://user-images.githubusercontent.com/24621070/58710775-677fd800-83bd-11e9-8724-e893af07b1de.png)

But not in invoice card and list

![afbeelding](https://user-images.githubusercontent.com/24621070/58710836-8da57800-83bd-11e9-8ccc-fffcc47d47e2.png)

![afbeelding](https://user-images.githubusercontent.com/24621070/58710930-b88fcc00-83bd-11e9-88f3-f805d17f61c1.png)
