### ISSUE TITLE
Dobuble Product Label Fetching When Creating Invoice from Proposal

### ISSUE THREAD

**Issue by Metalicss** [Dolibarr/dolibarr#11248]
# Bug
When creating an invoice from a proposal, system is fetching also propale product labels into the product description field of the invoice.

## Environment
- **Version**: 9.0.3
- **OS**: Linux gator3262.hostgator.com 3.10.0-693.17.1.2.ELK.el6.x86_64 #1 SMP Thu Feb 8 23:35:45 MST 2018 x86_64
- **Web server**: Apache
- **PHP**: 7.1.14
- **Database**: MySQL or MariaDB 5.6.41-84.1

![Adsız](https://user-images.githubusercontent.com/26469618/58361476-c31b0480-7e97-11e9-9464-04297cae8e5b.png)

**Comment by atm-maxime** [comment]
Sorry I couldn't reproduce on my 9.0. Your screenshot shows a line in edition mode. So you have this issue after clicking on the edit line icon on your invoice ?

**Comment by hregis** [comment]
@Metalicss you use the multi-languages option ?

**Comment by Metalicss** [comment]
@atm-maxime , yes screenshot belongs to editing mode. While i was trying to print invoices i found out that product lines have dublicated product label. I checked product lines in editing mode and, as you can see in the screenshot product labels also comes into description field of facture from proposal.
@hregis , yes multi-languages option is enabled.

**Comment by Metalicss** [comment]
@atm-maxime, I've checked possible variations and find out that this problem occurs when "MAIN_PRODUCT_DISABLE_CUSTOMCOUNTRYCODE" option is set 1.
Just set this option to 1 and create a proposal. Then try to create an invoice from this proposal. You will see that the created invoice has product labels also in the description fields.
