### ISSUE TITLE
Feature customer price : add customer reference field in customer price 

### ISSUE THREAD

**Issue by lvessiller-opendsi** [Dolibarr/dolibarr#11246]
# Instructions
Add a customer reference field on product customer price (like in product supplier price with the supplier reference field)

# Feature Request
Add a new field in product customer price in order to use the customer dedicated product ref on sales objects (propal, order, shipment, invoice and contract). It's usefull when product price by customer feature is enabled.

## Use case
It's a real need when we want to save and use reference by customer

## Suggested implementation
Add a new field "ref_customer" (varchar(30) default null) in "llx_product_customer_price" and change the unique key "uk_customer_price_fk_product_fk_soc" (fk_product, fk_soc) by "uk_customer_price_fk_product_fk_soc (fk_product, fk_soc, ref_customer)

Modify "Productcustomerprice" class :
- add "ref_customer" attribute
- modify fetch(), create() and update() methods with this new field
- modify "sell price" tab of product card (form to update value of this new field)
- uses translate key "RefCustomer"

Add new fied "fk_product_customer_price" (int not null default 0) in theses tables :
- llx_propaldet
- llx_commandedet
- llx_expeditiondet
- llx_facturedet
- llx_contratdet

Modify "propal", "commande", "expedition", "facture" and "contat" classes : 
- add "fk_product_customer_price" attribute
- modify update() method with this new field

Add product price by customer reference in products lines of each commercial card (propal, commande, expedition, facture and contrat) : 
- modify "objectline_create.tpl.php" and "objectline_edit.tpl.php"

@eldy : any tips or instructions ?

**Comment by StephaneLesage** [comment]
up!
The customer ref is very nice standard feature on other ERP.
In my case, we need it just for the reference, not necessarily the price.
