### ISSUE TITLE
Paypal : Erreur sur paiement acompte

### ISSUE THREAD

**Issue by Reynald34250** [Dolibarr/dolibarr#11245]
# Instructions
Après génération d'une facture d'acompte (partielle), le lien de paiement Paypal est utilisable  "URL de paiement Online".
Le processus de paiement s'effectue correctement (avec carte CB) jusqu'au bout hormis la facture qui n'est pas classée payée dans Dolibarr !

Un message d'erreur apparaît sur la page de récapitulation du paiement, dans une info bulle rouge :
`Cannot add or update a child row: a foreign key constraint fails (`dolibarrElly`.`llx_societe_remise_except`, CONSTRAINT `fk_societe_remise_fk_user` FOREIGN KEY (`fk_user`) REFERENCES `llx_user` (`rowid`)) - sql=INSERT INTO llx_societe_remise_except (entity, datec, fk_soc, discount_type, fk_user, description, amount_ht, amount_tva, amount_ttc, tva_tx, multicurrency_amount_ht, multicurrency_amount_tva, multicurrency_amount_ttc, fk_facture_source, fk_invoice_supplier_source) VALUES (1, '2019-05-23 17:13:42', 237, 0, 0, '(DEPOSIT)', 4.28, 0, 4.28, 0, 4.28, 0, 4.28, '66', null)`

Malgré ce message, le paiement a eu lieu et l'argent a bien été déposé sur le compte paypal du vendeur.

Le paiement d'une facture totale ne pose aucun problème.

# Bug
FOREIGN KEY sur table llx_societe_remise_except en fin de paiement d'une facture d'acompte client.

## Environment
- **Version**: 9.0.1
- **OS**: Ubuntu server 18.04
- **Web server**: Apache2
- **PHP**: 7.2.17-0ubuntu0.18.04.1
- **Database**: Mysql
- **URL(s)**: [*Affected URL(s)*]

## Steps to reproduce the behavior
Création d'un acompte de facture client et paiement avec le lien "URL de paiement Online"

## [Attached files]
![erreur_doli_paypal](https://user-images.githubusercontent.com/50992425/58331655-e57e3500-7e39-11e9-95ff-991da509cfea.png)

# Feature Request

**Comment by atm-maxime** [comment]
Thanks, we saw this issue. Problem is that when the payment is made by the customer, there's no Dolibarr user logged so the data's are recorded with a user 0

**Comment by reynald34** [comment]
Is a solution considered?
Can you tell me which script php temporarily modify in order to work around this problem?
Thank you very much for your intervention.
Reynald

**Comment by Reynald34250** [comment]
Hello,
Does version 10 solve this problem?
I did not see anything in the Change Log!
Thank you so much.
