### ISSUE TITLE
Adding products to an offer or updating price in an offer cause warnings

### ISSUE THREAD

**Issue by Metalicss** [Dolibarr/dolibarr#11250]
# Bug
_**1-**_ Adding a product to an offer causes the following warnings **if the added product has a no pre-defined price**.

Warning: A non-numeric value encountered in .../htdocs/comm/propal/card.php on line 1042

Warning: Cannot modify header information - headers already sent by (output started at …/htdocs/comm/propal/card.php:1042) in ../htdocs/main.inc.php on line 1111

Warning: Cannot modify header information - headers already sent by (output started at …/htdocs/comm/propal/card.php:1042) in …/htdocs/main.inc.php on line 1114

Warning: Cannot modify header information - headers already sent by (output started at …/htdocs/comm/propal/card.php:1042) in …/htdocs/main.inc.php on line 1115

_**2-**_ Updating a product price in an offer causes the following warnings **no matter if the product has a pre-defined price or not**.

Warning: A non-numeric value encountered in …/htdocs/comm/propal/card.php on line 1161

Warning: Cannot modify header information - headers already sent by (output started at …/htdocs/comm/propal/card.php:1161) in …/htdocs/main.inc.php on line 1111

Warning: Cannot modify header information - headers already sent by (output started at …/htdocs/comm/propal/card.php:1161) in …/htdocs/main.inc.php on line 1114

Warning: Cannot modify header information - headers already sent by (output started at …/htdocs/comm/propal/card.php:1161) in …/htdocs/main.inc.php on line 1115

## Environment
- **Version**: 9.0.3
- **OS**: Linux gator3262.hostgator.com 3.10.0-693.17.1.2.ELK.el6.x86_64 #1 SMP Thu Feb 8 23:35:45 MST 2018 x86_64
- **Web server**: Apache
- **PHP**: 7.1.14
- **Database**: MySQL or MariaDB 5.6.41-84.1

**Comment by atm-maxime** [comment]
Can you give us more informations about data you're tryning to add ? The only way I can reproduce these warnings is if I enter some letters in the "discount %" input.

**Comment by Metalicss** [comment]
**First scenario:** When we try to add a predefined product into a proposal, if the product has no predefined purchase price we receive the warning below.

![Adsiz](https://user-images.githubusercontent.com/26469618/58741970-b0b94180-8428-11e9-9b5c-959565a87ab7.png)


**Second scenario:**  When we try to update the price of the added product we receive the warning below. 

![Adsiz2](https://user-images.githubusercontent.com/26469618/58741971-b6168c00-8428-11e9-832b-4006192416ac.png)


Warnings disappear after refreshing the page.
Please note that these warnings appeared after we upgraded our php to v7.1. We did not have this problem in v7.0

**Comment by Metalicss** [comment]
Hello,
Problem doesn't exist anymore after updating our php version to 7.2.

**Comment by swedebugia** [comment]
Could you close it then?
