### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by itslouisdb** [Dolibarr/dolibarr#11251]
# Bug

## Environment
- **Version**: 9.0.1
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/index.php?mainmenu=home

**Comment by atm-maxime** [comment]
Please explain.
