### ISSUE TITLE
Disabling products or services module doesn't hide them in the product/service list of a bill

### ISSUE THREAD

**Issue by AXeL-dev** [Dolibarr/dolibarr#11256]
# Bug
If you disable the services module & try to create a new bill then add some product lines to this bill, the both products & services are shown on the product list --' , i think this is not the expected behavior

## Environment
- **Version**: 8.0.2
- **OS**: Ubuntu 16.04
- **Web server**: Apache
- **PHP**: 7.3.3
- **Database**:  MariaDB 10.1.38
- **URL(s)**: http://localhost/dolibarr/htdocs/fourn/facture/card.php?facid=18

## Expected and actual behavior
The expected behavior is to not show the services or products on the bill lines form if the products or services module is disabled.

**Comment by atm-maxime** [comment]
Hi @AXeL-dev ! Thanks for this. You don't need to close manually the issue, it will close automatically when your commit reaches the develop branch, as long as you mention the issue # in the commit.

**Comment by AXeL-dev** [comment]
hey @atm-maxime, well, i wasn't sure about this, so i thought that closing it would reduce the amount of opened issues out there, anyway, thanks for the information x)
