### ISSUE TITLE
Fatal error: Uncaught Error: Unsupported operand types

### ISSUE THREAD

**Issue by sebastienserre** [Dolibarr/dolibarr#11264]
Hello,
I don't know if it's a Dolibarr or plugins bug...
I have a Fatale Error when using this:
https://www.dolistore.com/en/modules/378-shedule-paiement.html?search_query=echeancier&results=1

but the error is:

`Fatal error: Uncaught Error: Unsupported operand types in /home/sebastie/public_html/prod/dolibarr/htdocs/includes/tecnickcom/tcpdf/include/tcpdf_fonts.php:2006 Stack trace: #0 /home/sebastie/public_html/prod/dolibarr/htdocs/includes/tecnickcom/tcpdf/tcpdf.php(6306): TCPDF_FONTS::UTF8StringToArray('31 Mai 2019', NULL, Array) #1 /home/sebastie/public_html/prod/dolibarr/htdocs/includes/tecnickcom/tcpdf/tcpdf.php(5883): TCPDF->Write(0, '31 Mai 2019', '', 0, 'C', true, 0, false, true, 0, 0, NULL) #2 /home/sebastie/public_html/prod/dolibarr/htdocs/custom/echeancier/core/modules/facture/doc/pdf_echeancier.modules.php(841): TCPDF->MultiCell(38, 3, '31 Mai 2019', '', 'C') #3 /home/sebastie/public_html/prod/dolibarr/htdocs/custom/echeancier/core/modules/facture/doc/pdf_echeancier.modules.php(291): pdf_echeancier->line(Object(TCPDI), 142.98333377778, Object(stdClass)) #4 /home/sebastie/public_html/prod/dolibarr/htdocs/core/class/commonobject.class.php(4526): pdf_echeancier->write_file(Object(Facture), Object(Translate), '', 0, 0, 0 in /home/sebastie/public_html/prod/dolibarr/htdocs/includes/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2006`
So in Dolibarr Core

**Comment by atm-maxime** [comment]
Hi !
Can you unactivate the module "shedule paiement" and try again ? If you don't have the error anymore, please contact the module developer. If you do, please reopen this issue and tell us in details what you are doing in your Dolibarr.
Thanks

**Comment by sebastienserre** [comment]
The problem is encountred when I use this module, if I deactivate It, of course I haven't any problem...
BUT
The module is n't in the problem as I tryed it in a fresh install of DOlibarr and no problem...
I tried My install (file) with my DB ... Fatale Error
I tried FResh files and my DB ... Fatale Error

So I have something in my db which make the Fatale...
But I don't know what

**Comment by atm-maxime** [comment]
Somehow it seems you have an incorrect data in your db. You should turn to the module developer, maybe he already encountered this error, or to some tech guy who might help you fix it.
Thanks for sharing anyway !

**Comment by sooslaca** [comment]
I got here by google for a completely different product (not Dollibarr). Same line (2006) gives same error in same file (tcpdf_fonts.php)
It seems like tcpdf module is not compatible with latest php?

**Comment by hregis** [comment]
@sebastienserre 
first, what is your php version ?

**Comment by sebastienserre** [comment]
Hello @hregis PHP 7.3.5

**Comment by hregis** [comment]
@sebastienserre 
by testing the function tcpdf manually where is your error I have no problem with php 7.3.3
The trouble must come from elsewhere, it would be necessary to debug your module.
