### ISSUE TITLE
Warning: is_dir(): open_basedir restriction in effect. File(/56wwplbn7paujhhv) is not within the allowed path(s): (g:/dolibarr) in G:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 441Bug: 

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#11278]
# Bug

## Environment
- **Version**: 9.0.3
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/index.php?mainmenu=home&leftmenu=home

**Comment by hregis** [comment]
@diego83200 
this is a right access problem with your system, check permissions of your directories

**Comment by hregis** [comment]
@atm-maxime ah ?

**Comment by atm-maxime** [comment]
@hregis he reported the same error in the other issue
