### ISSUE TITLE
Uploaded files for two different spcial expenses can be saved in the same directory

### ISSUE THREAD

**Issue by sezio** [Dolibarr/dolibarr#11274]
# Bug
Uploaded files are shared between two different taxes as different "compta" entries have not the same type (vat, etc) and so they stock the files at the same place (documents/tax/id). 

## Environment
- **Version**: 8.0.3
- **OS**: debian 9 stretch
- **Web server**: apache
- **PHP**: php 7.0
- **Database**: MariaDB Ver 15.1 Distrib 10.1.37-MariaDB
- **URL(s)**: /compta/*

## Expected and actual behavior
Exepected behavior : files for different types of special expenses should be saved in different directories
Actual behavior : files for different types of special expenses are saved in the same directory as two types of different expenses have their own increment_id and so two different types of special expenses can have the same id

## Steps to reproduce the behavior
* create a new special expense (vat)
* upload a file 
* file is uploaded in documents/tax/1
* create a new type of special expense in the dictionaries (let's call it "new type of expense")
* create new special expense (new type of expense)
* upload a file 
* file is uploaded in documents/tax/1
* Files in the documents/tax/1 directory are shared betwwen the two special expenses created
* Files can be consulted in the two special expenses even if they are not related

# Feature Request
Save files for different types of special expenses in different directories

**Comment by philazerty** [comment]
Look this other issue : [https://github.com/Dolibarr/dolibarr/issues/11883](https://github.com/Dolibarr/dolibarr/issues/11883)
it is this mixture of files for tax, special expense and social charge.

**Comment by eldy** [comment]
This has been fixed for 11.0.2
