### ISSUE TITLE
Bug. Multiple Warnings when creating an expedition in 9.0.1

### ISSUE THREAD

**Issue by jfposi** [Dolibarr/dolibarr#11273]
# Bug
Just creating the delivery from an customer order and get warnings since the beginning, after validating...

## Environment
- **Version**: 9.0.1
- **URL(s)**: /expedition/card.php?id=50&action=confirm_valid&confirm=yes

![Captura](https://user-images.githubusercontent.com/20990871/58628238-7b520e00-82d9-11e9-9e95-8311d13e331c.JPG)

And once validated

![Captura12](https://user-images.githubusercontent.com/20990871/58628260-8d33b100-82d9-11e9-815c-431d0b7444bb.JPG)

**Comment by hregis** [comment]
@jfposi  it's just a warning, you can hide this in your php.ini

**Comment by atm-maxime** [comment]
I think this has been fixed in latest 9.0 release.
