### ISSUE TITLE
Bug: Fatal error: Call to undefined function getFormeJuridiqueLabel() in G:\dolibarr\www\dolibarr\htdocs\core\lib\payments.lib.php on line 285

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#11277]
# Bug

## Environment
- **Version**: 9.0.3
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/index.php?mainmenu=home&leftmenu=home

**Comment by atm-maxime** [comment]
Can you provide more informations ? When does this message show ? After what action ? Screenshots help :)
