### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#11287]
# Bug
Hello

stripe payment ok 
## Environment
- **Version**: 9.0.3
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/compta/facture/card.php?facid=163

**Comment by atm-maxime** [comment]
Did you open this issue just to say we can close the previous one??

**Comment by atm-maxime** [comment]
#11286
