### ISSUE TITLE
Bug: Fatal error: Call to undefined function getFormeJuridiqueLabel() in G:\dolibarr\www\dolibarr\htdocs\core\lib\payments.lib.php on line 285

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#11285]
# Bug

Hello
when i am using the ticket module on the main page i have this error message 

Fatal error: Call to undefined function getFormeJuridiqueLabel() in G:\dolibarr\www\dolibarr\htdocs\core\lib\payments.lib.php on line 285

 with the public link

https://dolicr.ddns.net/dolibarr/public/ticket/index.php

and when i am creating a new ticket i have the folowing message 

Warning: is_dir(): open_basedir restriction in effect. File(/789b486drkwvn8lb) is not within the allowed path(s): (g:/dolibarr) in G:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 441

with th folowing public link
https://dolicr.ddns.net/dolibarr/public/ticket/create_ticket.php

it was fonctional with the 8.xxx version but until the update in 9.xxx it does'nt works anymore
thanks for your reply
regards

## Environment
- **Version**: 9.0.3
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/index.php?mainmenu=home

**Comment by atm-maxime** [comment]
#11277 #11278
