### ISSUE TITLE
Notes on proposal not copied to invoice

### ISSUE THREAD

**Issue by mtbochaca** [Dolibarr/dolibarr#11282]
# Bug
*When we convert a proposal to invoice, the public and private notes of the proposal are not copied to the invoice. In old versions this was the case*

## Environment
- **Version**: [*9.0.3*]
- **OS**: [*Debian Linux 9.9*]
- **Web server**: [*Apache 2.4.25-3+deb9u7*]
- **PHP**: [*PHP 7.0.33-0+deb9u3*]
- **Database**: [*MariaDB 10.1.38-0+deb9u1*]
- **URL(s)**: [*/dolibarr/compta/facture/card.php?action=create&origin=propal*]

**Comment by atm-maxime** [comment]
Sorry, I just tried on the Dolibarr demo and it worked. When you are on the invoice creation form, both notes are filled with the values coming from the proposal.
https://demo.dolibarr.org/compta/facture/card.php?action=create&origin=propal&originid=795&socid=1394

**Comment by mtbochaca** [comment]
Problem solved. In the databases that come from old versions, you must add the parameter FACTURE_REUSE_NOTES_ON_CREATE_FROM to 1 in the Other Setup. Thanks!!!
