### ISSUE TITLE
How to include Virtual Products in Shipment Sheet and Invoice?

### ISSUE THREAD

**Issue by vinodsv91** [Dolibarr/dolibarr#11289]
# Instructions
*When I create a shipment/invoice from Customer Order, it does not include virtual products under the parent product. Could someone help me how to make it possible?*

# Bug
[*virtual product in shipment sheet and invoice*]

## Environment
- **Version**: [*9*]
- **OS**: [*Windows*]

## Expected and actual behavior
[*Virtual products must be included under each parent product*]

**Comment by atm-maxime** [comment]
I don't think this is a generic request. Most people using virtual products don't want them to appear on shipment or invoice. I suggest you turn to a specific dev.
If you just need the virtual product description to appear, why not having the details in the parent product description ?

**Comment by vinodsv91** [comment]
@atm-maxime Thanks but I am not a developer.
@eldy Please help me out

**Comment by atm-maxime** [comment]
@vinodsv91 no problem, I was not suggesting you do the dev yourself :) Here's a list of official partners https://partners.dolibarr.org

Do my suggestion work for you ?

**Comment by vinodsv91** [comment]
@atm-maxime I thought it was enabling a simpler option or code :) Anyway will look for some. I will be needing Virtual products in shipment sheet for our operators to counter check in actual before dispatch.
