### ISSUE TITLE
Virtual Products negative stock for material visibility

### ISSUE THREAD

**Issue by vinodsv91** [Dolibarr/dolibarr#11288]
# Instructions
*When I create a customer order for particular products for sale, it displays a negative value which means I have to replenish stock, but virtual products remain zero which ultimately must also be negative in virtual stock. Could someone help me with this?*

# Bug
[*virtual products*]

## Environment
- **Version**: [*9*]
- **OS**: [*Windows*]

## Expected and actual behavior
[*When an order created for mother product, virtual products stock should also go in negative, instead it remains zero *]

![VirtualProductStockDecrease](https://user-images.githubusercontent.com/51256977/58744839-bd668580-847a-11e9-9ecb-cd38a16eb64f.jpg)

**Comment by vinodsv91** [comment]
@eldy Please look on to this issue.

**Comment by atm-maxime** [comment]
@vinodsv91 I found a hidden option (not documented) that allows virtual stock calculation for product components : ORDER_ADD_ORDERS_WITH_PARENT_PROD_IF_INCDEC

Hope this helps.
