### ISSUE TITLE
Multi Currency Option Error for Manufactured Prod

### ISSUE THREAD

**Issue by vinodsv91** [Dolibarr/dolibarr#11290]
# Instructions
*I have set default currency to my company as USD.

I have created a few manufactured products by defining the unit price of each (currency could not be selected for products)

Then I add those products in the customer order.

When I create invoice against the shipment, on preview it displays the actual price but when PDF is exported seems like unit price get converted to USD based on defined local currency. But the product price entered is USD.

Could someone help to sort out?*

# Bug
[*Invoice value*]

## Environment
- **Version**: [*9*]
- **OS**: [*Windows*]

## Expected and actual behavior
[*Value on PDF must be same as in preview*]
![Invoice Error](https://user-images.githubusercontent.com/51256977/58744914-98bedd80-847b-11e9-84d1-bfa0d5c265b7.jpg)

**Comment by vinodsv91** [comment]
@eldy Identified a bug in order sheet
![Invoice currency bug](https://user-images.githubusercontent.com/51256977/58745418-716c0e80-8483-11e9-8694-633c8f01ed3f.jpg)

**Comment by atm-maxime** [comment]
Hi !
I tried just now with a new Dolibarr 9, setup with default currency USD. I created a product with $100 selling price, then an order for 5 of this product. After creating and validating the shipment, I created the invoice from the shipment and I have a correct invoice (on screen and in PDF) for $500.

I think the issue comes from your screenshot where you have a strange conversion rate. It should be one as your default currency is USD and the order currency too.

Did you change your default currency recently ? Try to force the conversion rate to 1 and check the multi-currency setup.

**Comment by vinodsv91** [comment]
Hi, @atm-maxime I wasn't able to change the conversion rate. I tried different things but doesn't work. If I turn off multi-currency, it works but the problem is I can't use other currencies.

**Comment by atm-maxime** [comment]
If you create a new order in USD, the exchange rate is 1 or 0,01918 ?
If it's 1, then it means your issue is only with this order. Otherwise give us a screenshot of your setup page.

**Comment by vinodsv91** [comment]
Hi Maxime

 

If I create new order still the exchange rate is 0.01918 USD = 1 USD. You can see below screen shot. 

![Order currency conversion error](https://user-images.githubusercontent.com/51256977/59079670-613ab000-8917-11e9-8711-a18a8ae56a63.jpg)

Below is the screen shot of Multicurrency module

![Multi Currency setup](https://user-images.githubusercontent.com/51256977/59079678-6ef03580-8917-11e9-8d31-a9d212c72d9d.jpg)

**Comment by vinodsv91** [comment]
@atm-maxime Were you able to identify the issue?

**Comment by vinodsv91** [comment]
Still relevant

**Comment by eldy** [comment]
Did you check with a recent version (Dolibarr v11) ?

**Comment by dpriskorn** [comment]
Please upgrade to a supported version (v10, v11, v12) and reopen this if the problem persists.
