### ISSUE TITLE
Add a REST API to pay Supplier Invoices

### ISSUE THREAD

**Issue by naku** [Dolibarr/dolibarr#11294]
# Feature Request
Add a REST API to play Supplier Invoices

## Suggested implementation
Currently there is a REST API to pay client Invoices: POST /invoices/{id}/payments
Please add a REST API to play suplier invoices as well: POST /supplierinvoices/{id}/payments

**Comment by zigastegu** [comment]
Do you mean?
![image](https://user-images.githubusercontent.com/1379063/77491177-59fc7880-6e3d-11ea-92c2-d64913fd69ea.png)

Please check latest version and close if this resolves request.

**Comment by naku** [comment]
Seems like it's been added in version 11, I'm resolving
