### ISSUE TITLE
Bug: Error Interventions LAY-OUT with extra fields

### ISSUE THREAD

**Issue by gpnetsolutions** [Dolibarr/dolibarr#11317]
# Instructions
After Update Dolibarr to 9.0.3, my lay-out Intervention web page looks wrong with the extra field. If i disable extra field, looks right.
( i am from 7.0.3 version, and was woking perfectly ) 

# Bug
Looks wrong lay-out intervention web page with extra field.

## Environment
- **Version**: 10.0
- **OS**: Debian 8.11
- **Web server**: PLESK
- **PHP**: 7.1.30
- **Database**: MariaDB 10.0.38
- **URL(s)**: fichinter/card.php

## Expected and actual behavior
With extra field... Lay-out looks wrong
![Captura1](https://user-images.githubusercontent.com/51674240/59213666-b398fc80-8bb5-11e9-9ea3-7e2e7869ab73.JPG)

Without extra field... looks OK!
![Captura2](https://user-images.githubusercontent.com/51674240/59213603-919f7a00-8bb5-11e9-899e-9f685137a643.JPG)

**Comment by gpnetsolutions** [comment]
Update my Dolibarr to 10.0... ( from 9.0.3 )
We continue with the same lay-out intervention error.
Thank you.

**Comment by hregis** [comment]
@gpnetsolutions i don't understand! Where is your problem?

**Comment by hregis** [comment]
@gpnetsolutions 
the data layout is a table, the title of your additional field is aligned with the "description" column

**Comment by gpnetsolutions** [comment]
@hregis Hi!
Have you read and seen my screens posted?

The correct lay-out is " Without extra field... looks OK! "

So it looked perfect including extra-field before version 9...

Of course the problem is not SERIOUS. But it is very uncomfortable to write in the small description window.
If you see when there is no extra-field, it is the correct format as it has to be. And as I was saying, before version 9, that lay-out has always been correct. With the DESCRIPTION field occupying almost the entire width of the screen.
Thank you.

**Comment by hregis** [comment]
@gpnetsolutions 
before 9 the layout is the same !!

**Comment by hregis** [comment]
@gpnetsolutions @eldy 
i send a PR https://github.com/Dolibarr/dolibarr/pull/11540

**Comment by gpnetsolutions** [comment]
@hregis 
Thanks for your attention.
If I get some time this afternoon, I do a clean installation of Dolibarr 7 for example, and I send you a screen so you can see that the Lay-out is not the same.
