### ISSUE TITLE
Installation issue using postgresql in wamp Server using dolibaarr 9.0.4 on windows 10

### ISSUE THREAD

**Issue by bidabil** [Dolibarr/dolibarr#11323]
Hi, 

I got the dolibarr using git, create the user dolibarrowner and the teste is OK.

When it comes to install, Curl is not compatible with the 7.2.18 version of PHP but the use of 7.1.29 solve the probleme.

when I try to select the pgsql (driver type) is not available for the used version of PHP. Only mysqli is available.

How to fix that ... thank you !

**Comment by atm-maxime** [comment]
If this is an issue related to your environment, you should ask for help on forums or to a Dolibarr partner https://partners.dolibarr.org.

**Comment by bidabil** [comment]
thank you very much.

but is that any instructions on web to how to set up my environment ?
