### ISSUE TITLE
Feature Request: capacity measure on product

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#11339]
Add capacity measure on product for net weight or volume (sometimes différents of integrated volume or weight which use as gross weight or volume)

Add price by default capacity (needed legal information for some business as food) ie: 5,55€/Kg or 4.33€/L and display it in card and pdf

**Comment by atm-maxime** [comment]
Can you explain the use of it ? If you use the unit on the product card (L or Kg) it means you manage your product in this unit. So the sell price is related with the unit (5,55 € / L) and the stock quantities too (150 L in stock).
If you need to define a specific unit value (i.e. box of 4 Kg) and specify a price related, I think you will have to deal with several "packaging" possibilities and prices for the same product.

**Comment by ptibogxiv** [comment]
the unit of product is a brut unit (with package) because it's use for weight/volume shipping

the capacity is the net product unity  (without package) volume, weight, size

ex soup in bottle of 1L  , tube of 5m for 25€ and so dolibarr can calcul a price by default capacity 5€/L or 5€/m
ex 1Kg net of olive  can weight 1,5kg with package

it's legal for some business ex fresh product and use it on pdf or product card for print as a supermarket you can see price, price by default capacity, barcode etc...
