### ISSUE TITLE
"Simple POS" Impossible to do an invoice with 0€

### ISSUE THREAD

**Issue by schtroll** [Dolibarr/dolibarr#11344]
# Bug
Impossible to validate an invoice when total is 0€ , I've to do that because i offert product and i have to have an invoice with 0€ for prouve this stock mouvement.
I use simple POS
Sorry for my bad english, but thanks if any people have a little solution

## Environment
- **Version**: 9.0.3
- **OS**:Ovh php server, LINUX
- **Web server**: Ovh php server LINUX
- **PHP**: 7.1.26
- **Database**: MySQL or MariaDB 5.7.21-log

**Comment by Arre8** [comment]
quote of Frensh forum (if needed) https://www.dolibarr.fr/forum/12-howto--aide/64534-simple-pos-facture-0

works fine with TakePOS -> lets see if dolibarr's strategy is to upgrade SimplePOS or totaly disable it in later version.
