### ISSUE TITLE
Bug: Unknown template 'homard' in Customer invoice template drop-down list

### ISSUE THREAD

**Issue by hameau** [Dolibarr/dolibarr#11352]
# Bug
Unknown template 'homard' in Customer invoice template drop-down list

## Environment
- **Version**: First noticed in v9.0.3 (two installations); not in v8.0.3. Installed using DoliDeb package, upgraded from earlier versions, original installation ~v3.
- **OS**: Debian 9 (stretch)
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: 7.0.33-0+deb9u3
- **Database**: MariaDB 5.5.5-10.1.38-MariaDB-0+deb9u1
- **URL(s)**: /dolibarr/compta/facture/card.php

## Expected and actual behavior
On the Card tab for a Customer invoice (/dolibarr/compta/facture/card.php) there is an unknown document template named 'homard'. Google tells me that this may be related to a third-party template pack, which has never been installed here. Attempting to generate a document with the homard template results in an error: ```Error File /usr/share/dolibarr/htdocs/core/modules/facture/doc/pdf_homard.modules.php does not exist``` – which is true, the file does not exist. The document template homard is not in the list of templates in the Invoice module setup.

A full-text search of the Dolibarr system shows no occurence of the word homard in any file, except the database backup. It exists in the database table ```llx_document_model```. I can only imagine that it was added to the database during an upgrade (v8.0.x -> 9.x ?).

This ghost template appeared between Dolibarr v8.0.3 and v9.0.3.

(To correct my local symptoms, can I simply delete the line from the database table?)

**Comment by ksar-ksar** [comment]
Hi,

Homard is the modele of the RUBIS pack.
Have installed the Rubis pack ?

I just checked that on a fresh V9.03 install there is only "crabe" for cutomer invoice template.

**Comment by hameau** [comment]
Going back through database backups, the ```llx_document-model``` entry appeared almost two years ago, but homard has never previously appeared in the list of choices for invoice generating. I have two invoice templates and I use that drop-down list a lot, only with my two custom templates available.

I have no recollection of even looking at the Rubis pack, but I might be mistaken.

I deleted the database table row, which removed the symptom. This is apparently not a Dolibarr bug – sorry for the noise.
