### ISSUE TITLE
new sql file: llx_bom_bom.sql duplicated fields.

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11365]
# Bug
CREATE TABLE llx_bom_bom(
	-- BEGIN MODULEBUILDER FIELDS
...
        **date_valid datetime NOT NULL,** 
	tms timestamp, 
	**date_valid datetime,** 
...
	-- END MODULEBUILDER FIELDS
) ENGINE=innodb;

**Comment by inoveaconseil** [comment]
Hi,

See Fix bom sql #11359
