### ISSUE TITLE
bug api invoice does not update extrafields

### ISSUE THREAD

**Issue by fbosman** [Dolibarr/dolibarr#11386]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
When updating an invoice via the Webservices Rest API the extra fields are not updated, they can be retrieved but not changed
## Environment
- **Version**: [9.04
- **OS**: ubuntu
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
update of extrafields through Rest API

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by adrienjacob** [comment]
If you mean "supplier" invoices, then I just submitted a [PR](https://github.com/Dolibarr/dolibarr/pull/13659), which solves the issue, and it got accepted. Otherwise the latest version should already work with regular invoices.
