### ISSUE TITLE
Bugs in adherents/type.php

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11393]
# Bug
[*Short description*]
The following code in type.php(in 3 places) 
****************
....
        $morphys[""] = $langs->trans("Physical & Morale");
        $morphys["phy"] = $langs->trans("Physical");
        $morphys["mor"] = $langs->trans("Morale");
...
**********************
could be fiexed with:
****************
....
        $morphys[""] = $langs->trans("MorPhy");
        $morphys["phy"] = $langs->trans("Physical");
        $morphys["mor"] = $langs->trans("Moral");
...
**********************

**Comment by aspangaro** [comment]
Already correct in v9 & v10.

Thanks to close this issue
