### ISSUE TITLE
Loan amount not reflect in bank and project

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#11395]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
Loan amount not reflect in bank and project

## Environment
- **Version**: [*9.0.3*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Loan amount not reflect in bank and project

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by atm-maxime** [comment]
Please use the issue template and give some details about what is expected... I think your issue is a feature request so only keep this section in you issue description.

**Comment by asolslk** [comment]
The loan amount keyed in the loan module is not reflected in the project, and bank entry as attached.

![loan](https://user-images.githubusercontent.com/52134143/60393474-a766e600-9b48-11e9-8f48-f4e5795bd833.JPG)
![loan2](https://user-images.githubusercontent.com/52134143/60393475-a766e600-9b48-11e9-96c2-41c2565b89c2.JPG)
![loan 3](https://user-images.githubusercontent.com/52134143/60393476-a7ff7c80-9b48-11e9-8e3e-4c9820ba65a5.JPG)
