### ISSUE TITLE
BUG list product's document with rest api not functionnal

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#11399]
/api/index.php/explorer/#!/documents/documentsRetrieveDocumentsListByElement

with api list not functionnal in v10 and 11 alpha (in v10 we only get files in root directory)

**Comment by eldy** [comment]
Are you speaking about this API ?
![image](https://user-images.githubusercontent.com/883887/62290010-89024c00-b460-11e9-82ce-3b1de8016ccd.png)

**Comment by ptibogxiv** [comment]
@eldy yes. it doesn't return the good files  (wronf directory return -> root instead of productXX directory)

**Comment by ptibogxiv** [comment]
@eldy exemple of return with product... (functionnal with other object) i set an id or ref but always return product root directory
![image](https://user-images.githubusercontent.com/3135833/62319683-d1405f00-b49e-11e9-91cc-b9bf556fac4f.png)

**Comment by fappels** [comment]
$conf->product->dir_output ... should be 
$conf->product->multidir_output[$object->entity].'/'.get_exdir(0, 0, 0, 0, $object, 'product').dol_sanitizeFileName($object->ref);

@ptibogxiv my git blames you for this ;)

**Comment by ptibogxiv** [comment]
@fappels @eldy indeed this code fix it. I will push a PR with this.
