### ISSUE TITLE
Same keyword in 3 languages files

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11391]
# Bug
["Nature="  found in 3 files]
"Nature="  found in {accountancy.lang/members.lang/products.lang},  unique name will avoid the mistake when use $lang->trans() return value.

**Comment by ogaofeng** [comment]
This issue is only solved in English language files, sorry to see that it still exists in other languages. Simply search "Nature=" and you can find many existences. 
Hint: Maybe read with both file name and keyword together will solve the problem completely.

**Comment by eldy** [comment]
If it is solved in english, it will be solved automatically for all other languages at next transifex sync for next version.
