### ISSUE TITLE
Wrong keyword in language file Type.lang.

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11401]
# Bug
You can never find key like "Physical & Morale" (ie. like line 286 in Type.lang):
*****************************************
......
			else print $langs->trans("Physical & Morale");
......
*****************************************

Hint: Use "MorPhy" instead to solve the problem.

**Comment by aspangaro** [comment]
Bug resolved in next v10.0.*. Thanks for the report. I close this issue
