### ISSUE TITLE
htdoc->fourn->class->fournisseur.facture.class.php line 2860 introduces a possible new bug

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11407]
# Bug
[*Short description*]
It's good to remove the comma at the end of line 2860, but the removal of "f.libelle as label," on the same line makes it impossible to reference $obj.label in the following code(line 2891,2892).

**Comment by atm-maxime** [comment]
which version ?

**Comment by dpriskorn** [comment]
Please upgrade to the latest version and reopen this if the problem persists.
