### ISSUE TITLE
Virtual stock value not updated on customer order

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11419]
# Bug
Virtual stock seems to do not work anymore

## Environment
- **Version**: Dolibarr 8.0.2 and same behaviour on 9.0.3
- **PHP**: 7.0.28
- **Database**: MySQL or MariaDB 5.7.14-google

## Expected and actual behavior
Virtual stock should be updated on customer order

## Steps to reproduce the behavior
Create a customer order with one product. 
Validate the customer order.
Then check the virtual stock of this product : the virtual stock value does not take into account the order quantity (however the tooltip that explains the virtual stock value displays the order quantity)

## [Attached files]
![Capture](https://user-images.githubusercontent.com/52299040/60301267-3699b100-9931-11e9-9d21-73c5d421f1f3.PNG)

**Comment by atm-maxime** [comment]
How is setup your stock module ? Can you give a screenshot ? Virtual stock calculation is related to the way your stock is increased / decreased.

**Comment by ghost** [comment]
Hi,
thanks for your reply. Please find enclosed two screenshots (for each of my isntance).
![stock9 0 3](https://user-images.githubusercontent.com/52299040/60319994-a1220f80-9978-11e9-8cd3-356a61aa06b8.PNG)
![stock8 0 2](https://user-images.githubusercontent.com/52299040/60319995-a1220f80-9978-11e9-9421-366044614faf.PNG)

**Comment by ghost** [comment]
As if the value was not computed even if all necessary information are available.

**Comment by ghost** [comment]
Hi
after modyfing the following configuration (see scrennshot), everything is ok again.
However, **I think the label "Décrémenter les stocks physiques sur validation des factures/avoirs client" is not relevant
![Capture](https://user-images.githubusercontent.com/52299040/60327740-f2d49500-998c-11e9-8ac7-4ebb70d77b4b.PNG)
...**

**Comment by atm-maxime** [comment]
This was it. If you don't tell the system when your stock are decreased, it can't compute a virtual stock.
