### ISSUE TITLE
New invoice events are missing (and not listed in the actioncomm table)

### ISSUE THREAD

**Issue by thom4parisot** [Dolibarr/dolibarr#11411]
# Instructions

Create an invoice, modify it, add a product or service and then validate it. The events history is empty.

# Bug

I expected singular operations to show up in an invoice history.
They actually used to show up but since May 22nd, no new events are added to the `actioncomm` table.

## Environment
- **Version**: `9.0.3` (I was in `8.0.0` since January, the problem appeared later on)
- **OS**: `Linux titan.o2switch.net 3.10.0-962.3.2.lve1.5.24.8.el6h.x86_64`
- **Web server**: `Apache`
- **PHP**: `7.2.19`
- **Database**: `MySQL or MariaDB 5.5.5-10.2.24-MariaDB-cll-lve`
- **URL(s)**: `compta.usinevivante.org`

## [Attached files](https://help.github.com/articles/issue-attachments) 

![image](https://user-images.githubusercontent.com/138627/60183157-00233f80-9826-11e9-9197-0e8ce3b40898.png)

Nothing is added, but this invoice is more recent…

![image](https://user-images.githubusercontent.com/138627/60183497-b8e97e80-9826-11e9-9651-00b4e120ddd6.png)

… and has been validated. They even received the invoice by email. It used to appear in the events history:

![image](https://user-images.githubusercontent.com/138627/60183558-d3235c80-9826-11e9-99bd-dc70483a3caf.png)

I'm unsure about what caused this change of behaviour. It does not seem related to a Dolibarr upgrade. What else could have altered the behaviour of registering new events in the `actioncomm` table?

**Comment by atm-maxime** [comment]
Automatic events on cards are setup in the calendar module. There's a tab to activate which events should be created regarding the action made. Give us the details of this setup

**Comment by thom4parisot** [comment]
Indeed…

I checked the setup and this module was inactive. Maybe because we did not use any of its other features.

Thanks for your help, definitely not a bug then!
