### ISSUE TITLE
Enhancement: set default shipment method in customer card

### ISSUE THREAD

**Issue by fbosman** [Dolibarr/dolibarr#11438]
# Feature Request
In the order-card the shipment method must be supplied, based on the dictionary llx_c_shipment_mode.
It is very usefull to set the default shipment method on customer level and to inherit the method in the order.

## Use case
Create an order demands a shipment method, we see that this method often depends on the whishes of the customer

## Suggested implementation
add field on customer table: llx_societe
add selector on customer card
propagate default method on order-card

## Suggested steps
add field on customer table: llx_societe
add selector on customer card
propagate default method on order-card

**Comment by atm-maxime** [comment]
I think this exists already. In the third party module setup, look at the options. One must be "Ask for delivery method on customer card" or something like that. Please close the issue if this is what you were looking for.

**Comment by fbosman** [comment]
Thanks! I must have overlooked that one, this will do the job!
