### ISSUE TITLE
Lost functionnality

### ISSUE THREAD

**Issue by inoveaconseil** [Dolibarr/dolibarr#11434]
# Instructions
The VAT report doesn't exist in the simple accounting

# Bug
htdocs/compta/stats/byratecountry.php?leftmenu=report

In French:
Le rapport de Chiffre d'affaires encaissé par taux de TVA n'est pas disponible. Ce rapport est uniquement disponible pour le chiffre d'affaires facturé.

## Environment
- **Version**: 9.0.3
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

**Comment by atm-maxime** [comment]
Sure ? Do you mean this one ?
![image](https://user-images.githubusercontent.com/2097773/61998976-4cc59900-b0b8-11e9-96e6-6ce0bb6305b4.png)

**Comment by inoveaconseil** [comment]
Yes this one, if you click on the link you have the previous sentence (In simply accounting module)

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by ksar-ksar** [comment]
Hello, no answer to the last questions since a long time.

Will be closed, but you can reopen it if the problem persist
