### ISSUE TITLE
Discussion:  internal language code

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#11457]
Hello,

with every new Dolibarr release and changes in internal description or in en_US Code
we start new with translation for every other language.

Because you are so fast with development (compliment for that!) 
we can not edit so fast the translations 
and sometime you change something in english like "supplier" to "vendor" 
which is still in german the same but we lost all the transaltions with this string. 

# Suggestion / Idea

Is it maybe possible to use an internal language  (e.g.  en_INT or  int_INT  or en_DEV ...)
       [INT for Internal or International .. , DEV for Develop]
for the internal program reference - a short technical description code
wich is not so often changed.

Or maybe to use a Number-Code for this like for example:

#1234 = short Description
or
#1234_shortDesc = short Description  

and than you change the en_US or en_INT description if necessary
but all other languages still have a translation
because refer to #1234  

With best regards
Udo Tamm

**Comment by eldy** [comment]
When we change a string into another into english language, may be therebis no need to retranslate it into another language but therebis no way to know that.
That's the reason why transifex say: the value has changed so please check also in your language if you have to change it to. In 95% of time, yes.
If not, you must click on the transifex history to say to keep using the old value.
Only the translator can say if a change of translation to reflect change on original is required or not and this may also differs forbeach language.
So i don't think we can enhance this process.
