### ISSUE TITLE
API : ajout d'un paiement 

### ISSUE THREAD

**Issue by mathieu33370** [Dolibarr/dolibarr#11459]
Bonjour,

j'utilise l'API de dolibarr pour saisir des paiements depuis une autre application.

Tout fonctionne à merveille sauf que lorsque je créé un règlement de type "Paiement en ligne", le règlement s'ajoute bien.

Je télécharge ensuite, toujours via l'API le PDF de la facture clôturée par mon règlement, et ma facture se retrouve en langue anglaise.

Il faut alors que j'aille sur la facture dans dolibarr, que je clique sur GENERER pour qu'elle revienne en français correctement.

J'ai tenté de regarder dans le code source, mais je ne trouve pas de solution.
J'ai également mis à jour Dolibarr sur la dernière version 10.0 pour voir si ce bug aurait pu être réglé, malheureusement non. C'est bien dommage.

Si quelqu'un a une idée ?

**Comment by jtraulle** [comment]
Bonjour @mathieu33370,

Merci de ne pas utiliser le Github pour demander de l'aide, le forum est fait pour cela.
Le Github ne doit être utilisé que pour rapporter des anomalies avérées ou demander des nouvelles fonctionnalités et uniquement en langue anglaise en utilisant le gabarit proposé lors de la création d'une nouvelle issue sur Github (sinon, on ne s'en sort plus ; il y a déjà 815 demandes ouvertes :roll_eyes: )  

J'ai répondu ici : https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/64681-api-ajout-d-un-paiement#112661 Au plaisir de continuer la discussion avec vous sur le fil de discussion forum.

Vous pouvez donc fermer cette issue (ça en fera toujours une de moins d'ouverte :wink:  )

**Comment by eldy** [comment]
Which version of dolibarr ?

**Comment by jtraulle** [comment]
Maybe this is related to #11693

**Comment by dpriskorn** [comment]
Update to v12 and reopen if the problem persists.
