### ISSUE TITLE
Wizard issues running sql files (rank)

### ISSUE THREAD

**Issue by dgomezleon** [Dolibarr/dolibarr#11458]
**Summary**
Since MySQL 8.0.x the word `rank` is reserved. I found that `rank` appears in several places in the Dolibarr code.

The main issue is that the line below appears in `install/mysql/tables/llx_bom_bomline.sql`:

```
 rank integer NOT NULL
```

It produces an error during the installation:

```
SQL Error DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank integer NOT NULL ) ENGINE=innodb' at line 11
```

![Screenshot 2019-07-04 at 16 57 50](https://user-images.githubusercontent.com/11521627/60675567-f7adb300-9e7c-11e9-8d23-014568931d06.png)

**Step to reproduce**
Install Dolibarr 10.0.0 with MySQL 8.0.16.

**Environment**
Linux
Apache 2.4.39
MySQL 8.0.16
PHP 7.3.6

**Comment by Evgeny1973** [comment]
You can fix this error like this::
chage rank to `rank`

 here:
htdocs/install/mysql/tables/llx_bom_bomline.sql on line 26
and
htdocs/install/mysql/migration/9.0.0-10.0.0.sql on line 255.

**Comment by eldy** [comment]
I renamed field into "position" for v10.0.1

**Comment by dgomezleon** [comment]
Thanks @eldy. Do you have an ETA for this?
