### ISSUE TITLE
Error when loading chart of account. If few accounts were not loaded, you can still enter them manually.

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#11456]
Accounting settings:
go to accountmodel

# Bug
Select active chart of accounts:  
Loading accounting chart "SKR03" 

get warning: 
Error when loading chart of account. If few accounts were not loaded, you can still enter them manually.

## Environment   (tested in a few different environments)
- **Version**: Dolibarr 8.0.x  &  Dolibarr 9.0.x
- **OS**: Linux (Debian 9)
- **Web server**: Apache 2.4.xx
- **PHP**: 7.0.xx  7.2.xx
- **Database**: MariaDB

## Expected and actual behavior
[*Verbose description*]

**Comment by com4WEB** [comment]
Warning exists also in Dolibarr 10.0.0 

And also if you use in there (chart of accounts  -  /accountancy/admin/account.php)
a searchfield you get this message:

> **Error when loading chart of accounts. If few accounts were not loaded, you can still enter them manually.**

**Comment by vaibhav3099** [comment]
Still facing this issue
