### ISSUE TITLE
E-Mail Collector with option creating a ticket, throws error

### ISSUE THREAD

**Issue by Nemtes** [Dolibarr/dolibarr#11454]
# Bug
I setup a E-Mail Collector to create a ticket when there is a new message.

## Environment
- **Version**:10
- **OS**: Ubuntu 16.04
- **Web server**: nginx/1.10.3
- **PHP**: 7.0.33
- **Database**: MariaDB 5.7.26
- **URL(s)**: https://127.0.0.1/admin/emailcollector_card.php?id=1

## Expected and actual behavior
Fetching the E-Mails works, but when I add the option to generate a ticket from the mails and fetching it again following error shows up:

`1 emails qualified, 0 emails successfully processed (for 0 record/actions done) - Error Incorrect string value: '\xFC\xDFen /...' for column 'message' at row 1`

**Comment by eldy** [comment]
Can you check what is the format/type and length of field message in your table llx_actioncomm ?

**Comment by Nemtes** [comment]
the table llx_actioncomm doesn't have a message field. 
I checked the llx_ticket table the message field is: 
`message                | text         | YES  |     | NULL`
