### ISSUE TITLE
Attribute can not be saved

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11466]
[Bug]
After editing custom price, the flag of setting price for sub company cannot be saved.

[Bug repeat]
**My URL is as follows:
http://localhost/htdocs/societe/price.php?action=edit_customer_price&socid=20&lineid=75

1. Check the "updatechildprice" checkbox, click the save button, things same to be OK. When coming back, the checkbox is not checked.

**Comment by eldy** [comment]
This is never saved. It meand that when you click on save, the price will be changed also for subcompanies. This is done when clicking save only. Itw is not a property of the price ornproduct.
