### ISSUE TITLE
Bug: Preview of documents not visible

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#11467]
# Bug

## Environment
- **Version**: 9.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.2.25-MariaDB
- **URL**: /auditorias/comm/propal/card.php?id=150

**Comment by atm-maxime** [comment]
Without informations, hard to reproduce...
I heard of some issues related to the browser settings (french forum : https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/62498-resolu-apercu#99806)

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?
