### ISSUE TITLE
10.0 bug facture changement de bloc de frappe

### ISSUE THREAD

**Issue by warnerbryce** [Dolibarr/dolibarr#11460]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
Avec la version 10.0, quelque soit le navigateur web, lorsque l'on rentre une facture, la première lettre frappée dans la case description du produit/service s'inscrit puis la deuxième passe dans produit/service prédéfinie... (idprodfournprice-container). Même en recliquant dans la case description, on ne peut taper qu'une lettre avant de repasser sur la liste produit/service prédéfinie.

## Environment
- **Version**: 10.0.0
- **OS**: Ubuntu Server 18.04.2
- **Web server**: Apache2 2.4.29
- **PHP**: 7.2.19
- **Database**: MariaDB 10.3.16
- **URL(s)**: None of your business

## Expected and actual behavior
Comme avant, taper librement dans la case description sans être redirigé ailleurs.

## Steps to reproduce the behavior
Créer une facture brouillon, avoir activé la gestion de produit/service, taper du texte dans la description d'une ligne de facture.

## Suggested steps
Plus de bug quand le module PM gestion de produits est désactivé

**Comment by eldy** [comment]
I can't reproduce. Can you try to clear your cache browser ?

**Comment by atm-maxime** [comment]
Seems to be the same as here #11492

**Comment by ojt1998** [comment]
I have posted a screenshot to #11492 which attempts to show the error recreation

**Comment by hregis** [comment]
@eldy @atm-maxime @ojt1998 @warnerbryce 

yes I confirm, this happens only with the textarea and not with CKeditor

**Comment by hregis** [comment]
@eldy @atm-maxime @warnerbryce 

the problem is in "objectline_create.tpl.php" line 281

```
<script type="text/javascript">

                $(document).ready(function(){

                        $(document).on('keypress',function(e) {
                            if ($('input:focus').length == 0) {
                                $('#idprodfournprice').select2('open');
                            }
                        });


                });
            </script>
```
