### ISSUE TITLE
Public ticket page display stripe footer message

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#11474]
# Bug

## Environment
- **Version**: 10.0.0
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/index.php?mainmenu=home

**Comment by ptibogxiv** [comment]
same as #11470 

footer ar the same for displaying company info. for moment it's link to payment footer. we need to do some changes for this
