### ISSUE TITLE
BUG: Public ticket page display PayPal footer

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#11470]
# Bug
 Public ticket page display PayPal footer

## Environment
- **Version**: 10
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

**Comment by eldy** [comment]
What do you mean with "stripe footer message" ? Do you mean javascript content dedicated to stripe ?

**Comment by futurehousestore** [comment]
Here is a forum post regarding this issue [https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/29262-public-ticket-site-shows-paypal-footer](urlhttps://www.dolibarr.org/forum/527-bugs-on-a-stable-version/29262-public-ticket-site-shows-paypal-footer)
I did close my PR for this issue because by mistake I've used a wrong file and @ptibogxiv "We introduce sale footer for standard footer public page for gdpr et safe infos for customers. For moments, footer come from payment page but we need more option for footer for all public pages"
