### ISSUE TITLE
create ticket

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#11476]
# Bug
http://dolibarr/public/ticket/create_ticket.php does'n works without a popup message of creation/confirmation
## Environment
- **Version**: 10.0.0
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/

**Comment by eldy** [comment]
Has been fixed. Will be available in 10.0.1
