### ISSUE TITLE
Sondage doesn't works with the public link

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#11478]
# Bug

## Environment
- **Version**: 10.0.0
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/index.php?mainmenu=home&leftmenu=home

**Comment by eldy** [comment]
Can't reproduce. What happen ?

**Comment by diego83200** [comment]
When I am creating a ticket with the public link The ticket is not create on dolibarr without any error and any messages for creating the ticket on the web pageEnvoyé depuis mon mobile Huawei-------- Message original --------De : Laurent Destailleur <notifications@github.com>Date : lun. 15 juil. 2019 à 18:35À : Dolibarr/dolibarr <dolibarr@noreply.github.com>Cc : diego83200 <jclauret@sfr.fr>, Author <author@noreply.github.com>Objet : Re: [Dolibarr/dolibarr] Sondage doesn't works with the public link (#11478)Can't reproduce. What happen ?

**Comment by eldy** [comment]
Fixed for 10.0.1

**Comment by diego83200** [comment]
HelloWhen this version coming out? ThanksEnvoyé depuis mon mobile Huawei-------- Message original --------De : Laurent Destailleur <notifications@github.com>Date : lun. 15 juil. 2019 à 23:41À : Dolibarr/dolibarr <dolibarr@noreply.github.com>Cc : diego83200 <jclauret@sfr.fr>, Author <author@noreply.github.com>Objet : Re: [Dolibarr/dolibarr] Sondage doesn't works with the public link (#11478)Fixed for 10.0.1
