### ISSUE TITLE
# Feature Request - Better list view for chart of accounts

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#11484]
# Feature Request

We and a lot of customers wish a improved list view
for chart of accounts
htdocs/accountancy/admin/account.php?

If you have to edit some lines it is in this list view very 
very time consuming and frustrating,
because after every edit you are back on startpage with default settings.

Nothing is saved, not the count of lines in a page,
not the page you was at least, or not a sortfilter or search.

Please can somebody implement a list view like in
products / third parties and other standard list views is already used.

best regards
Udo Tamm
com4WEB

**Comment by aspangaro** [comment]
Thanks for your report

I take this feature request, see you soon
