### ISSUE TITLE
Cannot Delete Rows within an Invoice as part of a Contract

### ISSUE THREAD

**Issue by s1kl3** [Dolibarr/dolibarr#11491]
# Bug
Cannot delete a row from an invoice being part of a contract. Pressing the delete icon doesn't result in any change.

## Environment
- **Version**: 10.0.0.4
- **OS**: Debian 10
- **Web server**: nginx 1.14.2-2
- **PHP**: 7.3.4-2
- **Database**: mariadb-server 10.3.15-1
- **URL(s)**: /compta/facture/card.php?id=56&action=ask_deleteline&lineid=149

## Expected and actual behavior
The delete button should remove the row from the invoice.

## Steps to reproduce the behavior
If I create a temporary invoice within the Commercial section and then, within the Contract section I attempt to get rid of a row by pressing the delete button, the page is updated without any deletion actually taking place.

**Comment by eldy** [comment]
On steps to reproduce. When you say "by pressing the delete", you mean you press delete on the contract line or on the invoice line ?

**Comment by s1kl3** [comment]
Sorry for the delay but the person who actually uses Dolibarr was not available. I meant when you press the delete button on the invoice line.
