### ISSUE TITLE
9.0.4 : Cloning invoice do nothing

### ISSUE THREAD

**Issue by jpyrat** [Dolibarr/dolibarr#11490]
# Bug
When I click on [Clone] (french version), the same page is displayed again with no action done.

## Environment
- **Version**: 9.0.4
- **OS**: Debian 9
- **Web Apache
- **PHP**: 7.0.33-0+deb9u3
- **Database**: MariaDB 5.5.5-10.1.38-MariaDB-0+deb9u1

**Comment by jpyrat** [comment]
This is after upgrading from 8.0.6 to 9.0.4 with php warning : #11488

**Comment by dpriskorn** [comment]
Please upgrade to a supported version (v10, v11, v12) and reopen this if the problem persists.
