### ISSUE TITLE
private attribute accessed from sub-object

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11498]
#8333 
Bug
[*Short description*]
private $connector defined in line 148 of /Applications/AMPPS/www/htdocs/includes/mike42/escpos-php/Escpos.php is accessed from line 675 of /Applications/AMPPS/www/htdocs/core/class/dolreceiptprinter.class.php

## Environment
- **Version**: 10.0.0
- **OS**: macOS

[Solution]
Change private to protected.

**Comment by eldy** [comment]
@frederic34 Can you check my fix is ok. I think you are using this feature ?

**Comment by ogaofeng** [comment]
Yes, I'd love to.
