### ISSUE TITLE
Text field misbehaves when editing an Order

### ISSUE THREAD

**Issue by s1kl3** [Dolibarr/dolibarr#11492]
# Bug
The text field to add a new row within an order under the Commercial section interferes with a selection just above which is related to the default product/services for the purchase.

## Environment
- **Version**: 10.0.0-4
- **OS**: Debian 10
- **Web server**: nginx 1.14.2-2
- **PHP**: 7.3.4-2
- **Database**: mariadb 10.3.15-1
- **URL(s)**: /fourn/commande/card.php?id=39

## Expected and actual behavior
The text field should allow insertion of text to label a new row and it shouldn't interfere with the selection field above.

## Steps to reproduce the behavior
Go into the Commercial section, create a new Order and then add a new row to the order attempting to edit its description with the text field.

**Comment by ksar-ksar** [comment]
https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/29322-supplier-order-free-text

**Comment by atm-maxime** [comment]
Can you provide more information or screenshots maybe ? I can't reproduce this on my side. I can add a row on a purchase order with a predefined product or with a free line, adding a specific description in each case works for me.

**Comment by ojt1998** [comment]
![dolibarr error](https://user-images.githubusercontent.com/53399413/62006544-b043db00-b139-11e9-82f6-1378fa4bfcf1.PNG)

This is a screenshot of the error - I posted on the forum but it looks like we're having the same issue. So as you can see free text is selected however as soon as you start typing, the loaded product selector starts trying to select

**Comment by hregis** [comment]
@s1kl3 @ojt1998 @atm-maxime @ksar-ksar 

yes I confirm, this happens only with the textarea and not with CKeditor

**Comment by hregis** [comment]
@eldy @atm-maxime @ksar-ksar @s1kl3 

the problem is in "objectline_create.tpl.php" line 281

```
<script type="text/javascript">

                $(document).ready(function(){

                        $(document).on('keypress',function(e) {
                            if ($('input:focus').length == 0) {
                                $('#idprodfournprice').select2('open');
                            }
                        });


                });
            </script>
```
