### ISSUE TITLE
Bug: not correctly assigned accounting code (sale) 

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#11493]
Bug: not correctly assigned accounting code (sale) 

## Environment
- **Version**: 8.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.25
- **PHP**: apache2handler 7.0.33-0+deb9u3
- **Database**: MySQL or MariaDB 5.5.5-10.1.38-MariaDB-0+deb9u1
- **URL**: /dolibarr/htdocs/accountancy/customer/index.php?leftmenu=accountancy_dispatch_customer&mainmenu=accountancy

the dolibarr settings: 
a) a company based in germany 
b) we have in setup company "sales tax used" set 
c) we have a complete chart of accounts (DE: SKR04) 
d) we have in acounting the three needed default accounts set - nothing more 
e) we have for all producst defined/set the four accounting code fields 
    Accounting code (sale) 
    Accounting code (sale intra-community) 
    Accounting code (sale export) 
    Accounting code (purchase) 
d) we have for all products the defined VAT (19%) and a selling price as "net of tax"

# Bug
If we now make an export " Customer invoices and invoice details"
or go to Accounting to do a "Customer invoice binding"

All lines have the the same account number from "Accounting code (sale)" - always
even if the country is outside (in EWG or Third Land) and also if there is a Sales tax ID or not.

# Question 
Is this a bug or a known unreleased feature?

**Comment by eldy** [comment]
Fixed in v10

**Comment by com4WEB** [comment]
I think there are many customers which need this functions, and a lot of them have customized setups, third party modules, which are not even adapted to v10. Most modules are just available for v9, some even just for v8. So please fix this, at least for v9.
Thank you
