### ISSUE TITLE
private function called in other objects.

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11497]
# Bug
_load_ldap_dn() is defined as private in line 2451 of /Applications/AMPPS/www/htdocs/adherents/class/adherent.class.php, but it is called in other objects,  such as  /Applications/AMPPS/www/htdocs/adherents/class/adherent_type.class.php line 515. 

## Environment
- **Version**: 10.0.0
- **OS**: mac OS

**Comment by hregis** [comment]
https://github.com/Dolibarr/dolibarr/pull/11500
