### ISSUE TITLE
ERROR agenda.lib.php

### ISSUE THREAD

**Issue by oda-alexandre** [Dolibarr/dolibarr#11501]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/core/lib/agenda.lib.php on line 472

## Environment
- **Version**: 9.0.3
- **OS**: aws ec2 ubuntu
- **Web server**: reverse proxy nginx
- **PHP**: 7.2.18
- **Database**: mysql 5.7
- **URL(s)**:  /var/www/html/core/lib/agenda.lib.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
inserer un nouveau evenement dans l'aganda cela arrive à l'enregistrement de l'evenement

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
