### ISSUE TITLE
Feature Request: support multicurrency in expense report

### ISSUE THREAD

**Issue by sam-anam1** [Dolibarr/dolibarr#11508]
Environment

Version: 10.0.0
OS: hosting
Web server: Apache
PHP: apache2
Database: MySQL or MariaDB 
URL: /htdocs/

 Feature Request
 
⁃ Enable Multi currency in EXPENSE REPORT is not appears with multicurrency module. **[it seem in DB is support multi currency rows  but there is no option when create new expense report]**

⁃ it would be great that Ticket module has an option for code CAPTCHA to “public self-ticket form” and Client "name field"

@eldy @aspangaro please please look into those for the new version please

Regards,
Sam

**Comment by toastal** [comment]
https://nostalebots.xyz

**Comment by toastal** [comment]
This still exists

Version: 22.0.2
OS: NixOS 25.11.20251006.8913c16 (Xantusia) x86_64
Web server: h2o/2.3.0-DEV
PHP: 8.3.26 (fastcgi)
Database: PostgreSQL 16.10
URL: /htdocs/
