### ISSUE TITLE
Bug: edit contact : no more title

### ISSUE THREAD

**Issue by AlainRnet** [Dolibarr/dolibarr#11503]
# Bug
After update from 9.0.2 to 10.0.0, when I edit a contact, there is nothing in title field (but I saw titles in contact list).
If I save the contact, he loses his title.

## Environment
- **Version**: 10.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.2.18
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL**: /gestion/contact/card.php?action=edit&id=152&backtopage=%2Fgestion%2Fsociete%2Fcontact.php%3Fsocid%3D61

**Comment by atm-maxime** [comment]
Hello, I can't reproduce this. Maybe it has already been fixed. Can you upgrade to 10.0.1 when it's out and let us now if you still have the issue ?

**Comment by AlainRnet** [comment]
Thank you.
I don't find 10.0.1. Do I have to download from develop branch ?

**Comment by hregis** [comment]
@AlainRnet no, 10 branch

**Comment by AlainRnet** [comment]
Thank you.
I confirm it has already been fixed.
