### ISSUE TITLE
Local variables not defined before reference

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11515]
# Bug
$total_debit , $total_credit not defined before use in line 714/715 of file:/htdocs/accountancy/bookkeeping/list.php.
---------------------
		$total_debit += $line->debit;
		$total_credit += $line->credit;
-------------------------

**Comment by atm-maxime** [comment]
Which version ?

**Comment by dpriskorn** [comment]
Please upgrade to the latest version and reopen this if the problem persists.
