### ISSUE TITLE
Feature request: stripe:setup intent

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#11523]
For v10 and later, support stripe setup intent for savings card/payment method for less 3d secure authentication later in on session or off session

**Comment by ptibogxiv** [comment]
need upgrade stripe php API to 6.40 or later

**Comment by eldy** [comment]
Upgrade done
I suggest to add a parameter to method getPaymentIntent that will be mode = 'paymentintent' or 'setupintent' and change the method to be able to return a SetupIntent. (Code should be similar for 90% of code i think)

**Comment by ptibogxiv** [comment]
@eldy thank you i will work on it (i need to read again stripe's docs which have changed again...)
