### ISSUE TITLE
Variable not defined before use

### ISSUE THREAD

**Issue by ogaofeng** [Dolibarr/dolibarr#11537]
# Bug
On line 46 of file /htdocs/admin/clicktodial.php, variable $result1 and $result2 not defined before reference.
    if ($result1 >= 0 && $result2 >= 0)

I guess the 2 lines before line 46 should be the definition of $result1 and $result2 separately?

**Comment by dorothykiz1** [comment]
Hello @ogaofeng can i work on this issue?
