### ISSUE TITLE
Support OAuth with Keycloak OpenID 

### ISSUE THREAD

**Issue by davy39** [Dolibarr/dolibarr#11541]
# Feature Request
Implement  [Keycloak](https://www.keycloak.org/) service in Oauth module.

## Use case
I'm using Keycloak (SAML & OpenID) for SSO beetween my apps like nextcloud and dokuwiki, and it's great.
I tried in vain to configure core OpenID via MAIN_AUTHENTICATION_OPENID_URL but there is no documentation about it...

## Suggested implementation
Probably the simplest would be to implement this new functionality in Oauth module. Perhaps it could be usefull to have a look on how it's done in [docuwiki](https://github.com/cosmocode/dokuwiki-plugin-oauth). Anyway, I'll definitively need some help to do so.  

Could someone please tell me how to go on with it ?

**Comment by mannp** [comment]
In general I am finding it a challenge to find info on selfhosted ERP systems that can utilise Keycloak, so any progress made here would be a great.

**Comment by n15c** [comment]
AFAIK this FR is still not implemented. 
+1

**Comment by samuk** [comment]
I'm interested in using OpenID with Dolibarr. Is this issue still live?

**Comment by pvergezac** [comment]
We are also interested in OpenID authentication with Keycloak on Dolibarr

**Comment by AlgunaPseudo** [comment]
I am really interested in using OpenID with Keycloak too. Work-in-progress?

**Comment by jeritiana** [comment]
Hi all. You may have a look at #22740 and try the suggested implementation with Keycloak. I'd be very interested in knowing if it works well or what we can do better.
