### ISSUE TITLE
"Objets référents" tabs is not showing only contact element

### ISSUE THREAD

**Issue by PlatiScript** [Dolibarr/dolibarr#11549]
# Bug
The "objet referents" tabs is not showing the contact element but showing all element (all propal, all order, ...). To correct that I've add `	$sql.= ' AND ec.fk_socpeople = '.$_GET['id']." "; `  at the line 324 in the file /contact/consumption.php 

## Environment
- **Version**: 10.0
- **OS**: Windows
- **Web server**: WAMP
- **Database**: MySQL
- **URL(s)**:  /htdocs/contact/consumption.php?id=50

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by ksar-ksar** [comment]
No answer to the last question since a long time : I close the issue.

You can reopen it if the problem persist
