### ISSUE TITLE
Tickets with public API not working

### ISSUE THREAD

**Issue by John-H-Smith** [Dolibarr/dolibarr#11543]
# Bug
Public API for tickets not working

## Environment
- **Version**: 10.0.0
- **OS**: Debian 9
- **Web server**: Apache2
- **PHP**: PHP 7.1.30-nmm1
- **Database**: MySQL 5.5.62-0+deb8u1

## Expected and actual behavior
Expected: Public API should create a new ticket.
Actual: After sending a ticket over the public API, page just reloads and no ticket has been created.

**Comment by natalieboucher** [comment]
yes, not working , just reloads
