### ISSUE TITLE
Purchase Orders not seen without permission 'Extend access to all third parties'

### ISSUE THREAD

**Issue by davidNDU** [Dolibarr/dolibarr#11545]
# Bug
Purchase orders are not seen, if the permission 'Third Parties -> Extend access to all third parties...' is not enabled

## Environment
- **Version**: *10.0.0*
- **OS**: *Linux 3.10.0-714.10.2.lve1.5.19.8.el7.x86_64*
- **Web server**: *LiteSpeed*
- **PHP**: *7.2.20*
- **Database**: *MySQL or MariaDB 10.3.16-MariaDB*
- **URL(s)**: *https://nduwrdc.org/dolibarr/*

## Expected and actual behavior
*Expected behavior would be the persmissions related to Vendors -> Read Purchase Orders, etc. are controlling if a user sees purchase orders*

## Steps to reproduce the behavior
Tick on/off  permission: _Third party - 
Extend access to all third parties (not only third parties for which that user is a sale representative).
Not effective for external users (always limited to themselves for proposals, orders, invoices, contracts, etc.).
Not effective for projects (only rules on project permissions, visibility and assignment matters)._
Check if the list at Commercial - Purchase Orders remains empty (0).

**Comment by hregis** [comment]
@davidNDU 
yes and where is the problem ?

**Comment by davidNDU** [comment]
The problem is with the unexpected behavior. I took some time to find out why a specific user wouldn't see any purchase order. From the description "Extend access to all third parties" I would not expect any relationship to purchase orders.

**Comment by hregis** [comment]
@davidNDU 
Do not put the right "Extend access to all third parties" to restrict the display of customers to commercial. If you want to give access to the supplier orders why not add this right?

**Comment by davidNDU** [comment]
@hregis 
I ran into this problem with an internal user. Why would I need to grant "Extend access to all third parties" to an internal user to let him see purchase orders?
Edit: 
But if I am the first person who struggles with this nomenclature, I guess the problem is with the user.

**Comment by hregis** [comment]
@davidNDU 
this right makes it possible to restrict the visualization of the customers assigned to the sales representatives. For the moment there is no difference in the access rights between a customer and a supplier, and a third party can be both a customer and a supplier!

**Comment by davidNDU** [comment]
Ok, I see. Thank you for the explanation. It's more clear now.
