### ISSUE TITLE
Bug - Dolibarr 10.0.0 - Supplier Invoice 

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#11578]
# Bug
in Supplier/Vendor Invoice   (/fourn/facture/card.php) 
if you add /edit a line and type in positions textarea  
the cursor jumps always to the product selection list  
    (but only without FCKeditor)

## Environment
- Dolibarr 10.0.0

**Comment by hregis** [comment]
This bug is already in 2 issues and a fix is send!

**Comment by atm-maxime** [comment]
Please close, as @hregis said, already opened twice and a fix is waiting to be merged #11460

**Comment by com4WEB** [comment]
Okay - see #11460  &  #11492
