### ISSUE TITLE
Bug: 10.0 Can create supplier order with a customer only

### ISSUE THREAD

**Issue by hregis** [Dolibarr/dolibarr#11575]
@eldy @atm-maxime 
when we create a new supplier order we have the possibility to create a new third party, the "Supplier" parameter is selected to "yes" but we can modify the choice of this drop-down list. So we can create a customer and it automatically return to the supplier order, and create a purchase order with just a customer who will not be supplier.

**Comment by eldy** [comment]
Imagine the thirdparty is modified after the supplier order is done. This will be possible too.
So it's like having created a supplier to create order and changing its status just after.
It's stupid but well, we could gray the combo but this will block situation where we want to change supplier or seller property flag.

**Comment by hregis** [comment]
@eldy 
maybe it should just check from which origin is made the request for creation of a third party and greyed out or put an alert if we change the type of third party that corresponds to this origin? Since once created, we come back to this origin!

**Comment by atm-maxime** [comment]
Or we prevent the user to change these properties from the moment there are objects related.
