### ISSUE TITLE
Supplier dispatch evolution for batch / serial

### ISSUE THREAD

**Issue by salnaSrc** [Dolibarr/dolibarr#11586]
# Instructions
Request for feature implementation

## Environment
- **version**:[*10.0.0*]
- **OS**: [*Windows*]
- **Web server**: [*XAMPP 3.7*]
- **PHP**: [*PHP 7*]
- **Database**: [*MySQL 8*]

## Expected and actual behavior
[*Optimisation for the module PRODUCTS_LOT during reception bacth*]

# Feature Request
From the supplier dispatch.php module, should be very usefull to add the possibilty to record a set of x products / lot couple in one time. Actually if we want to dispach 50 products with 50 differents serial number we have to execute 50 time the dispach process because yhe couple bacth / serial is unique. If we could enter the 50 serial number with the generation of 50 records in the batch tables it will be very usefull. 
![dispacth](https://user-images.githubusercontent.com/30660993/62047886-d043cf00-b20b-11e9-904d-8de724206a91.png)

**Comment by fappels** [comment]
Did you try to use split button, not optimal for 50 serial, but you don't need to dispatch 50 times.

![62047886-d043cf00-b20b-11e9-904d-8de724206a91](https://user-images.githubusercontent.com/4573808/62051654-19981c80-b214-11e9-9c0a-9d813e30fff5.png)

**Comment by salnaSrc** [comment]
Yes it's working with  the split button, but as you said it is not optimized, the best way should be to have a field witch it could be informed by the scan of batch / serial number. Actually i use the split button, but for supplier order with hundreds of products it is hard to do :)

 Thanks for you reply
