### ISSUE TITLE
TakePOS: Change of customer not possible

### ISSUE THREAD

**Issue by davidNDU** [Dolibarr/dolibarr#11584]
# Bug
*TakePOS module cannot alter the ThirdParty (Customer).*

## Environment
- **Version**:  *10.0.0*
- **OS**: *Linux 3.10.0-714.10.2.lve1.5.19.8.el7.x86_64*
- **Web server**: *LiteSpeed*
- **PHP**: *7.2.20*
- **Database**: *MySQL or MariaDB 10.3.16-MariaDB*

## Expected and actual behavior
- Click on Customer
- Select other customer by clicking on a line with a 'Customer' or 'Customer/Prospect'
Now I expect the customer to be changed, but it is still the default customer

## Steps to reproduce the behavior
In TakePOS:
- Click on Customer
- Select other customer by clicking on a line with a 'Customer' or 'Customer/Prospect'
- Enter product -> payment -> Look at invoice

**Comment by ptibogxiv** [comment]
+1 work only in restaurant/bar mode not in classic/shop mode

**Comment by davidNDU** [comment]
@ptibogxiv you suggest the option to change customer should only be available with restaurant/bar mode?

**Comment by ptibogxiv** [comment]
No 😊 just the bug doesn't exist in the bar / restaurant mode. I see it too but don't find it yet

**Comment by davidNDU** [comment]
With me, it is also not possible to change the customer in restaurant mode.
