### ISSUE TITLE
BUG V 10.0 : Issues adding Free-text item on an order pulls items list.

### ISSUE THREAD

**Issue by Bokal25** [Dolibarr/dolibarr#11590]
# Bug
[Greetings,
When creating a new purchase order (under the supplier tab) on version 10, you select Free-text item, type product or service and then move the cursor to the description field to fill it, the items list pops-up and you only select an item on your suppliers list ]

## Environment
- **Version**: [10]
- **OS**: [*Linux CentOS 7* ]
- **Web server**: [*Apache*]
- **PHP**: [*7.1*]
- **Database**: [*MySQL*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Not able to add a free text line for a product or a service under the supplier purchase order section*]

## Steps to reproduce the behavior
[*Open a supplier card, Go to supplier tab, Go to "Create Order", go to Create Draft, select "Free-text item, type:" and select any of the two options you got (service or product) then try entering text in the description field

Thanks*]

**Comment by hregis** [comment]
@Bokal25 please search before send an issue !!
this is already reported twice and a fix is in pull request here : https://github.com/Dolibarr/dolibarr/pull/11576

**Comment by Bokal25** [comment]
Thank you hregis, 
I did a search before sending, sorry for the reporting, I am bit new to github.

Cheers

**Comment by eldy** [comment]
Close duplicate
