### ISSUE TITLE
Bug: v10 broken feature without THIRDPARTY_SUGGEST_ALSO_ADDRESS_CREATION constant

### ISSUE THREAD

**Issue by hregis** [Dolibarr/dolibarr#11593]
@eldy 
without the constant THIRDPARTY_SUGGEST_ALSO_ADDRESS_CREATION in thirdparty card creation broke the feature for create private customer ! (particulier)

**Comment by eldy** [comment]
Fix in branch v10 for 10.0.1.
THIRDPARTY_SUGGEST_ALSO_ADDRESS_CREATION give same behaviour than in v9
Without, dolibarr does not suggest to duplicate the record into another table.
