### ISSUE TITLE
Bug: Line rang not matching if user creates invoice from delivery bill

### ISSUE THREAD

**Issue by Tim-Otte** [Dolibarr/dolibarr#11607]
# Bug
At the moment I am developing a module that reacts when a proposal is turned into an order and this is turned into an invoice. If the module has to react to the fact that a delivery note is continued into an invoice, the rang of the newly created line is not matching the rang of the proposal line.

## Environment
- **Version**: 10.0.0
- **OS**: Ubuntu 18.04 LTS (as WSL)
- **Web server**: Apache/2.4.29
- **PHP**: 7.2.19-0ubuntu0.18.04.1
- **Database**: innodb on mariadb Ver 15.1 Distrib 10.1.40

## Expected and actual behavior
_See general description_

## Steps to reproduce the behavior
_See general description_

**Comment by hregis** [comment]
@Tim-Otte 
We will need more information to help you!
your code is accessible?

**Comment by hregis** [comment]
@Tim-Otte 
did you check the dolibarr logs?

**Comment by Tim-Otte** [comment]
@hregis 
No, the code is not accessible.

I found the problem. I was wrong that the Trigger is not executed, it gets executed.

The rang of the inserted line in the invoice is not matching the rang of the previous proposal

**Comment by atm-maxime** [comment]
And I think it's normal if you don't have all the lines in the delivery. If your proposal contains 5 lines, the order too, the delivery 3 lines then the invoice 3 lines, the rang column will be different because it's only a counter starting at 1 in each document.

**Comment by Tim-Otte** [comment]
In the proposal, order and invoice the rang starts at 1, in the delivery it starts at 0. Thats the problem that should be fixed

**Comment by atm-maxime** [comment]
Yes why not fixing to have delivery start at 1 like the others. But this doesn't mean rang 1 in proposal equals rang 1 in order equals rang 1 in delivery equals rang 1 in invoice...

**Comment by Tim-Otte** [comment]
This is not the problem. My module could handle this, but not the different rang starts...

**Comment by Tim-Otte** [comment]
@eldy 
My pull request should fix this issue. The rang in the expedition line was not saved in the database.
