### ISSUE TITLE
Bug 10 LDAP contact synchronisation 

### ISSUE THREAD

**Issue by Je2fb** [Dolibarr/dolibarr#11606]
@eldy 

# Bug
The contact synchronisation is not working on the version 10

## Environment
- **Version**: 10.0.0
- **OS**: Linux Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: 7.0.33-0+deb9u3
- **Database**: MariaDB 5.5.5-10.1.38-MariaDB-0+deb9u1

## Expected and actual behavior
When we try to create or modify a user the interface get blank
In the LDAP module, when you press the Test synch button on the contacts tab no trace appear

## Steps to reproduce the behavior
Try on the LDAP module the test button in the contacts tab.

## Suggested implementation
In file contact.class.php, modify the function from private to public (line : 510)
private function _load_ldap_dn($info, $mode = 0)
To
public function _load_ldap_dn($info, $mode = 0)

**Comment by hregis** [comment]
@Je2fb this is already fix in the next release
