### ISSUE TITLE
Document Invoice PDF, add the serial number / batch informations

### ISSUE THREAD

**Issue by salnaSrc** [Dolibarr/dolibarr#11609]
## Environment
- **Version**:10.0.0
- **OS**: Windows last
- **Web server**:  XAMPP
- **PHP**: 7
- **Database**: MySQL

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, 

# Feature Request
Add the informations serial / batch on Invoice PDF document (same as expedition)

## Use case
Create an expedition with products using serial / bach number
On the document expedition pdf, the serial / Batch number are printed
it will be very interresting and usefull to have the same informations on the Invoice PDF document

**Comment by fbosman** [comment]
I just completed a new pdf-template for this issue.  Are you interested?

**Comment by zzillou** [comment]
@fbosman I would be interested in this template, is it possible to share it? In advance, thank you very much!

**Comment by fbosman** [comment]
> @fbosman I would be interested in this template, is it possible to share it? In advance, thank you very much!

Hi zzilou, I changed the template for expedition, but for this I had to change a function in pdf.lib.php. Currently I'm setting this up so the update of Dolibarr will not destroy this change.
Change: function pdf_getlinedesc($object, $i, $outputlangs, $hideref = 0, $hidedesc = 0, $issupplierline = 0)
{
	global $db, $conf, $langs;

	$idprod = (!empty($object->lines[$i]->fk_product) ? $object->lines[$i]->fk_product : false);
	$label = (!empty($object->lines[$i]->label) ? $object->lines[$i]->label : (!empty($object->lines[$i]->product_label) ? $object->lines[$i]->product_label : ''));
	$desc = (!empty($object->lines[$i]->desc) ? $object->lines[$i]->desc : (!empty($object->lines[$i]->description) ? $object->lines[$i]->description : ''));
	$ref_supplier = (!empty($object->lines[$i]->ref_supplier) ? $object->lines[$i]->ref_supplier : (!empty($object->lines[$i]->ref_fourn) ? $object->lines[$i]->ref_fourn : '')); // TODO Not yet saved for supplier invoices, only supplier orders
	$note = (!empty($object->lines[$i]->note) ? $object->lines[$i]->note : '');
	$dbatch = (!empty($object->lines[$i]->detail_batch) ? $object->lines[$i]->detail_batch : false);

	if ($issupplierline)
	{
		include_once DOL_DOCUMENT_ROOT.'/fourn/class/fournisseur.product.class.php';
		$prodser = new ProductFournisseur($db);
	}
	else
	{
		include_once DOL_DOCUMENT_ROOT.'/product/class/product.class.php';
		$prodser = new Product($db);
	}

	if ($idprod)
	{
		$prodser->fetch($idprod);
		// If a predefined product and multilang and on other lang, we renamed label with label translated
		if (!empty($conf->global->MAIN_MULTILANGS) && ($outputlangs->defaultlang != $langs->defaultlang))
		{
			$translatealsoifmodified = (!empty($conf->global->MAIN_MULTILANG_TRANSLATE_EVEN_IF_MODIFIED)); // By default if value was modified manually, we keep it (no translation because we don't have it)

			// TODO Instead of making a compare to see if param was modified, check that content contains reference translation. If yes, add the added part to the new translation
			// ($textwasmodified is replaced with $textwasmodifiedorcompleted and we add completion).

			// Set label
			// If we want another language, and if label is same than default language (we did force it to a specific value), we can use translation.
			//var_dump($outputlangs->defaultlang.' - '.$langs->defaultlang.' - '.$label.' - '.$prodser->label);exit;
			$textwasmodified = ($label == $prodser->label);
			if (!empty($prodser->multilangs[$outputlangs->defaultlang]["label"]) && ($textwasmodified || $translatealsoifmodified))     $label = $prodser->multilangs[$outputlangs->defaultlang]["label"];

			// Set desc
			// Manage HTML entities description test because $prodser->description is store with htmlentities but $desc no
			$textwasmodified = false;
			if (!empty($desc) && dol_textishtml($desc) && !empty($prodser->description) && dol_textishtml($prodser->description)) {
				$textwasmodified = (strpos(dol_html_entity_decode($desc, ENT_QUOTES | ENT_HTML401), dol_html_entity_decode($prodser->description, ENT_QUOTES | ENT_HTML401)) !== false);
			} else {
				$textwasmodified = ($desc == $prodser->description);
			}
			if (!empty($prodser->multilangs[$outputlangs->defaultlang]["description"]) && ($textwasmodified || $translatealsoifmodified))  $desc = $prodser->multilangs[$outputlangs->defaultlang]["description"];

			// Set note
			$textwasmodified = ($note == $prodser->note);
			if (!empty($prodser->multilangs[$outputlangs->defaultlang]["note"]) && ($textwasmodified || $translatealsoifmodified))  $note = $prodser->multilangs[$outputlangs->defaultlang]["note"];
		}
	}
	elseif ($object->element == 'facture' || $object->element == 'facturefourn') {
		if ($object->type == $object::TYPE_DEPOSIT) {
			$desc = str_replace('(DEPOSIT)', $outputlangs->trans('Deposit'), $desc);
		}
	}

	// Description short of product line
	$libelleproduitservice = $label;

	// Description long of product line
	if (!empty($desc) && ($desc != $label))
	{
		if ($libelleproduitservice && empty($hidedesc))
		{
			$libelleproduitservice .= '__N__';
		}

		if ($desc == '(CREDIT_NOTE)' && $object->lines[$i]->fk_remise_except)
		{
			$discount = new DiscountAbsolute($db);
			$discount->fetch($object->lines[$i]->fk_remise_except);
			$sourceref = !empty($discount->discount_type) ? $discount->ref_invoive_supplier_source : $discount->ref_facture_source;
			$libelleproduitservice = $outputlangs->transnoentitiesnoconv("DiscountFromCreditNote", $sourceref);
		}
		elseif ($desc == '(DEPOSIT)' && $object->lines[$i]->fk_remise_except)
		{
			$discount = new DiscountAbsolute($db);
			$discount->fetch($object->lines[$i]->fk_remise_except);
			$sourceref = !empty($discount->discount_type) ? $discount->ref_invoive_supplier_source : $discount->ref_facture_source;
			$libelleproduitservice = $outputlangs->transnoentitiesnoconv("DiscountFromDeposit", $sourceref);
			// Add date of deposit
			if (!empty($conf->global->INVOICE_ADD_DEPOSIT_DATE)) $libelleproduitservice .= ' ('.dol_print_date($discount->datec, 'day', '', $outputlangs).')';
		}
		elseif ($desc == '(EXCESS RECEIVED)' && $object->lines[$i]->fk_remise_except)
		{
			$discount = new DiscountAbsolute($db);
			$discount->fetch($object->lines[$i]->fk_remise_except);
			$libelleproduitservice = $outputlangs->transnoentitiesnoconv("DiscountFromExcessReceived", $discount->ref_facture_source);
		}
		elseif ($desc == '(EXCESS PAID)' && $object->lines[$i]->fk_remise_except)
		{
			$discount = new DiscountAbsolute($db);
			$discount->fetch($object->lines[$i]->fk_remise_except);
			$libelleproduitservice = $outputlangs->transnoentitiesnoconv("DiscountFromExcessPaid", $discount->ref_invoice_supplier_source);
		}
		else
		{
			if ($idprod)
			{
				if (empty($hidedesc))
				{
					if (!empty($conf->global->MAIN_DOCUMENTS_DESCRIPTION_FIRST))
					{
						$libelleproduitservice = $desc."\n".$libelleproduitservice;
					}
					else
					{
						$libelleproduitservice .= $desc;
					}
				}
			}
			else
			{
				$libelleproduitservice .= $desc;
			}
		}
	}

	// We add ref of product (and supplier ref if defined)
	$prefix_prodserv = "";
	$ref_prodserv = "";
	if (!empty($conf->global->PRODUCT_ADD_TYPE_IN_DOCUMENTS))   // In standard mode, we do not show this
	{
		if ($prodser->isService())
		{
			$prefix_prodserv = $outputlangs->transnoentitiesnoconv("Service")." ";
		}
		else
		{
			$prefix_prodserv = $outputlangs->transnoentitiesnoconv("Product")." ";
		}
	}

	if (empty($hideref))
	{
		if ($issupplierline)
		{
			if ($conf->global->PDF_HIDE_PRODUCT_REF_IN_SUPPLIER_LINES == 1)
				$ref_prodserv = $ref_supplier;
			elseif ($conf->global->PDF_HIDE_PRODUCT_REF_IN_SUPPLIER_LINES == 2)
				$ref_prodserv = $ref_supplier.' ('.$outputlangs->transnoentitiesnoconv("InternalRef").' '.$prodser->ref.')';
			else	// Common case
			{
				$ref_prodserv = $prodser->ref; // Show local ref
				if ($ref_supplier) $ref_prodserv .= ($prodser->ref ? ' (' : '').$outputlangs->transnoentitiesnoconv("SupplierRef").' '.$ref_supplier.($prodser->ref ? ')' : '');
			}
		}
		else
		{
			$ref_prodserv = $prodser->ref; // Show local ref only
		}

		if (!empty($libelleproduitservice) && !empty($ref_prodserv)) $ref_prodserv .= " - ";
	}

	if (!empty($ref_prodserv) && !empty($conf->global->PDF_BOLD_PRODUCT_REF_AND_PERIOD)) { $ref_prodserv = '<b>'.$ref_prodserv.'</b>'; }
	$libelleproduitservice = $prefix_prodserv.$ref_prodserv.$libelleproduitservice;

	// Add an additional description for the category products
	if (!empty($conf->global->CATEGORY_ADD_DESC_INTO_DOC) && $idprod && !empty($conf->categorie->enabled))
	{
		include_once DOL_DOCUMENT_ROOT.'/categories/class/categorie.class.php';
		$categstatic = new Categorie($db);
		// recovering the list of all the categories linked to product
		$tblcateg = $categstatic->containing($idprod, Categorie::TYPE_PRODUCT);
		foreach ($tblcateg as $cate)
		{
			// Adding the descriptions if they are filled
			$desccateg = $cate->description;
			if ($desccateg)
				$libelleproduitservice .= '__N__'.$desccateg;
		}
	}

	if (!empty($object->lines[$i]->date_start) || !empty($object->lines[$i]->date_end))
	{
		$format = 'day';
        $period = '';
		// Show duration if exists
		if ($object->lines[$i]->date_start && $object->lines[$i]->date_end)
		{
			$period = '('.$outputlangs->transnoentitiesnoconv('DateFromTo', dol_print_date($object->lines[$i]->date_start, $format, false, $outputlangs), dol_print_date($object->lines[$i]->date_end, $format, false, $outputlangs)).')';
		}
		if ($object->lines[$i]->date_start && !$object->lines[$i]->date_end)
		{
			$period = '('.$outputlangs->transnoentitiesnoconv('DateFrom', dol_print_date($object->lines[$i]->date_start, $format, false, $outputlangs)).')';
		}
		if (!$object->lines[$i]->date_start && $object->lines[$i]->date_end)
		{
			$period = '('.$outputlangs->transnoentitiesnoconv('DateUntil', dol_print_date($object->lines[$i]->date_end, $format, false, $outputlangs)).')';
		}
		//print '>'.$outputlangs->charset_output.','.$period;
		if (!empty($conf->global->PDF_BOLD_PRODUCT_REF_AND_PERIOD)) {
		    $libelleproduitservice .= '<b style="color:#333666;" ><em>'."__N__</b> ".$period.'</em>';
		} else {
		    $libelleproduitservice .= "__N__".$period;
		}
		//print $libelleproduitservice;
	}

	if ($dbatch)
	{
		$format = 'day';
		foreach ($dbatch as $detail)
		{
			$dte = array();
			if ($detail->eatby) $dte[] = $outputlangs->transnoentitiesnoconv('printEatby', dol_print_date($detail->eatby, $format, false, $outputlangs));
			if ($detail->sellby) $dte[] = $outputlangs->transnoentitiesnoconv('printSellby', dol_print_date($detail->sellby, $format, false, $outputlangs));
			if ($detail->batch) $dte[] = $outputlangs->transnoentitiesnoconv('printBatch', $detail->batch);
			$dte[] = $outputlangs->transnoentitiesnoconv('printQty', $detail->qty);
			$libelleproduitservice .= "__N__  ".implode(" - ", $dte);
		}
	}

	// Now we convert \n into br
	if (dol_textishtml($libelleproduitservice)) $libelleproduitservice = preg_replace('/__N__/', '<br>', $libelleproduitservice);
	else $libelleproduitservice = preg_replace('/__N__/', "\n", $libelleproduitservice);
	$libelleproduitservice = dol_htmlentitiesbr($libelleproduitservice, 1);

	return $libelleproduitservice;
}

**Comment by zzillou** [comment]
Hi fbosman! Thank you very much to share this code! 
Should I add something in the template of invoice to show the batch number in the invoice? I tried different things but it doesn't work... Thank you very much for your help!

**Comment by DATUC** [comment]
> I just completed a new pdf-template for this issue. Are you interested?

Yes realy

**Comment by DATUC** [comment]
> Hi fbosman! Thank you very much to share this code! Should I add something in the template of invoice to show the batch number in the invoice? I tried different things but it doesn't work... Thank you very much for your help!

any update

**Comment by fbosman** [comment]
Hi, attached is the template. You should place in the directory core/modules/facture/doc and enable it in the settings of the invoice module.
The code is not very nice, I'm working on a better coded version.

regards,

Frans

[pdf_ghee_1_0_crabe.modules.php.zip](https://github.com/Dolibarr/dolibarr/files/8999074/pdf_ghee_1_0_crabe.modules.php.zip)

**Comment by DATUC** [comment]
> Hi, attached is the template. You should place in the directory core/modules/facture/doc and enable it in the settings of the invoice module. The code is not very nice, I'm working on a better coded version.
> 
> regards,
> 
> Frans
> 
> [pdf_ghee_1_0_crabe.modules.php.zip](https://github.com/Dolibarr/dolibarr/files/8999074/pdf_ghee_1_0_crabe.modules.php.zip)

Ok wil test and comback

**Comment by DATUC** [comment]
Just ended the teste no change

**Comment by fbosman** [comment]
I got this line, what did you get?
<img width="579" alt="Schermafbeelding 2022-07-04 om 14 32 02" src="https://user-images.githubusercontent.com/21159625/177155697-8f54c724-ded2-4542-aedc-ddd79956b79d.png">
?
