### ISSUE TITLE
file main.lang not loaded in en_US

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#11616]
# Bug
translation keys in main.lang from en_US are not found

## Environment
- **Version**: Dolibarr 9.0.4
- **OS**: Ubuntu server 16.04
- **Web server**: Apache 2.4
- **PHP**: 7.2.20 fpm
- **Database**: MariaDB 10.3.16

## Expected and actual behavior
Whatever the template I used some translation keys are printed instead of their values (in english US).

## Steps to reproduce the behavior
I try to found the translations using the translator's module : in french or spanish i found them, but in english US nothing was returned.

Example : 'NotValidated', 'AmountInCurrency', 'PriceUHT', 'TotalHT'.

I cleared memcached and the browser's cahe many times with no effect.

**Comment by dpriskorn** [comment]
Please upgrade to a supported version (v10, v11, v12) and reopen this if the problem persists.
