### ISSUE TITLE
Bug: creation de tiers

### ISSUE THREAD

**Issue by renemuller** [Dolibarr/dolibarr#11617]
# Bug

## Environment
- **Version**: 10.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.6.42-log
- **URL**: /forscoerp/htdocs/societe/index.php?mainmenu=companies&leftmenu=

## Report
Bonjour , en version 10 , je n'ai plus la possibilité de créer un tiers type particulier avec nom , prénom , 
il n'y a plus qu'une seule possibilité de créer un tiers , dois revenir à la version 9.04 ou avez vous une solution et ou correctif
Merci d'avance

cordialemnt

**Comment by hregis** [comment]
@renemuller 
tu peux rajouter cette constante THIRDPARTY_SUGGEST_ALSO_ADDRESS_CREATION

**Comment by renemuller** [comment]
Merci , avec quelle valeur

**Comment by hregis** [comment]
avec la valeur 1

**Comment by renemuller** [comment]
c'est ce que j'ai fait et cela fonctionne merci
