### ISSUE TITLE
MAIN_MAIL_SMTPS_PW in "About Dolibar" not senstiv data

### ISSUE THREAD

**Issue by pthoelken** [Dolibarr/dolibarr#11611]
MAIN_MAIL_SMTPS_PW is in the Site "About Dolibarr" (Admin Tools -> About Dolibarr) not a senstiv object (unreadable) but this value is a password. The object "dolibarr_main_db_pass" is senstive.

**Comment by pthoelken** [comment]
no response or tagging in this case?

**Comment by atm-maxime** [comment]
Sorry, I don't understand what you want to tell us in your issue. Can you elaborate? Provide a screenshot? What you think should be done ?

Please try to follow the issue template next time.

**Comment by pthoelken** [comment]
![image](https://user-images.githubusercontent.com/12643853/65761169-95ccb480-e11e-11e9-853d-aa77bc9c3e59.png)

This is what I mean and comes from */admin/system/dolibarr.php?mainmenu=home&leftmenu=admintools_info

As you can see, in the database section form this page it is sensitive value. 
![image](https://user-images.githubusercontent.com/12643853/65761398-007df000-e11f-11e9-9b83-f9c90ad455bf.png)

**Comment by pthoelken** [comment]
@atm-maxime I hope this is information enough. Should I do a pull request in the next days to upload fixed code or would you fix this by yourself?

**Comment by cfoellmann** [comment]
@pthoelken if you have a fix for it a PR would be helpful. Just reviewing a change is far easier to do and even possible to do on the go.

**Comment by pthoelken** [comment]
I would prefer this method to hide the clear data (password) in the grid view. 

`preg_replace('/./i', '***', <PASWORD HERE>);`

I think the right file is "**admin.php**" but I can do a pull request in the next days if I have some free time for this.

**Comment by cfoellmann** [comment]
Is that the common way to hide sensitive data?
We should "copy" the way it is already handled for other data

**Comment by pthoelken** [comment]
Yes. This is the common way from Dolibarr. You can check this [here](https://github.com/Dolibarr/dolibarr/search?q=preg_replace%28%27%2F.%2Fi%27%2C&unscoped_q=preg_replace%28%27%2F.%2Fi%27%2C).

**Comment by laudeco** [comment]
@pthoelken are you doing the PR?

**Comment by pthoelken** [comment]
Yes I will do it when I have a little bit more time. Currently I'm in vacation.


-------- Ursprüngliche Nachricht --------
Betreff: Re: [Dolibarr/dolibarr] MAIN_MAIL_SMTPS_PW in "About Dolibar" not senstiv data (#11611)
Von: De Coninck Laurent
An: Dolibarr/dolibarr
Cc: Patrick Thoelken ,Mention


@pthoelken<https://github.com/pthoelken> are you doing the PR?

**Comment by laudeco** [comment]
Ok otherwise I can fix it today itself, it's why I asked the question

**Comment by pthoelken** [comment]
Yes. I'll do that if I have more free time. Currently I'm on vacation.

**Comment by pthoelken** [comment]
Okay, you can do it as well. Your choise. If you're done you can close the issue.

**Comment by pthoelken** [comment]
@laudeco Do you fix it already or should I do that in the next days?

**Comment by laudeco** [comment]
I assigned the ticket to you ;-), you said you will fix it/

**Comment by pthoelken** [comment]
Okey, Yes. I will fix it as soon as possible (currently no much free time). What should I do? PR > Fix > Push request to "develop" or in which branch should I push it?

**Comment by cfoellmann** [comment]
@pthoelken create a branch on your fork and send the PR to `develop`

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/12654

**Comment by frederic34** [comment]
but you can still view it in emails settings... input type password hide nothing
![Sélection_037](https://user-images.githubusercontent.com/3624836/70395347-0422d280-19fe-11ea-8d9b-51db7fec0cc0.png)

**Comment by hregis** [comment]
@frederic34 
yes like many things that go unencrypted but are encrypted with "https" !
what can be seen in clear locally is not necessarily visible online! ;-)
