### ISSUE TITLE
Bug when adding group to user

### ISSUE THREAD

**Issue by jige18** [Dolibarr/dolibarr#11610]
# Bug
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '9,-1)' at line 1

## Environment
DOLIBARR ENVIRONMENT
- Version: 10.0
- Operating System: Linux Wed May 15 10:40:34 CEST 2019 x86_64
- Web Server: Apache
- PHP: 7.0.33
- Database: MySQL or MariaDB 5.6.42-log
- URL(s): /user/card.php?id=5

## Expected and actual behavior
Expected: add a group to user
Actual: error message
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '8,-1)' at line 1

## Steps to reproduce the behavior
Go in user info. Go below to "Liste des Groupes for this user". Click "Add"
![image](https://user-images.githubusercontent.com/53564106/62287881-058e2e00-b453-11e9-9d36-a917efb69c82.png)

**Comment by eldy** [comment]
Did you select a group in the combo list before clicking on "Add" ?

**Comment by hregis** [comment]
yes this error appears when clicking on "add" without selecting a group

**Comment by hregis** [comment]
@eldy you correct this bug Laurent?

**Comment by jige18** [comment]
Ok, it works, thanks !

Le 1 août 2019 à 13:08, Regis Houssin <notifications@github.com> a écrit :

@eldy <https://github.com/eldy> you correct this bug Laurent?

**Comment by dpriskorn** [comment]
Closing as it seems fixed
