### ISSUE TITLE
Feature Request: TakePos change qty when reclick on product

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#11625]
Actually, when reclick on product, this will add a new ligne with the same product with qty 1 to each.

it will be better for read and more simple to increase qty when reclick on same product x times for x qty. we keep updating qty (increase or decrease) with actual process of course.

@andreubisquerra

**Comment by andreubisquerra** [comment]
In my personal opinion I think it should continue as now. What should we do if a customer buys 2 'Coca Cola' and one of them have a discount? Or if a restaurant order 2 pizzas 'Margarita' and only one has an extra kitchen note? Other POS applitation works as current TakePOS.
May be is a good idea only change the customer receipt grouping products.
What do you think?

**Comment by ptibogxiv** [comment]
@andreubisquerra yes, for receipt or invoice it will good for easy read.

A second screen for reporting to customer and/or set email on touch screen (i see a lot like this in UK) is it in project ?
it will be cool to have choice to print or email receipt / invoice 

and finally, i code stripe in dolibarr for further integration and compatibility with stripe terminal  with takepos https://stripe.com/fr/terminal (now only available in US).

Thanks for your work ;)

**Comment by ptibogxiv** [comment]
add in v12  so i close it
