### ISSUE TITLE
Batch / Serial, optimisation for the list of batch / serial

### ISSUE THREAD

**Issue by salnaSrc** [Dolibarr/dolibarr#11646]
## Environment
- **Version**: 10.0.0
- **OS**: Windows
- **Web server**: XAMPP
- **PHP**: 7
- **Database**: MySQL
- **URL(s)**: /product/stock/productlot_list.php

# Feature Request
Add localisation information for a bact / serial number

## Use case
From .../product/stock/productlot_list.php

## Suggested implementation
On the php file .../product/stock/productlot_list.php
Add a ne new colum to see where is localized each batch . serial number
- If the element is in stock just indicate the entrepot Name
- If the element is sold, indicate the client Name

Other implementation possible, on the top of the page, add the combos / lists to select directly a category / product or a specified stock (entrepot), should be very interesting for stock with lot of samples. 
![dol](https://user-images.githubusercontent.com/30660993/62537701-5d60d680-b851-11e9-8a48-c127cb3f08a2.png)

**Comment by cfoellmann** [comment]
I will keep this in mind.
Time is sparse but it would be good for us too

**Comment by cfoellmann** [comment]
I will circle back to this soon. in 15.x the serial is extended for lot and serial as separate functions
