### ISSUE TITLE
Creo que ya es hora no?

### ISSUE THREAD

**Issue by mgip** [Dolibarr/dolibarr#11654]
## Suggested implementation
Saludos, sisnceramente no se cual seria el correcto canal para comentar esto, soy usuario de Dolibarr desde hace unos años, y al dia de hoy es imprescindible hacerles la siguiente pregunta:

¿habeis considerado cambiar el frontend de Dolibarr, ya creo que esta un poco pasadito de moda no?

Hay varios "admin dashboard" tanto de pago como Metronic, o gratuitos como AdminLTE.

Creo que ya se encuentra en el punto de ponernos a trabajar en ello, no?

Muchas gracias.
PD: de necesitar colaboradores, me encuentro a vuestra completa disposicion.

**Comment by dolibarr95** [comment]
Hi
please read #9429

**Comment by atm-maxime** [comment]
Thanks for contributing, please try to participate in English ;)
