### ISSUE TITLE
Bug: Currency conversion rate USD > PEN no change PEN > USD

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#11686]
# Bug

## Environment
- **Version**: 10.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.2.16-MariaDB
- **URL**: /10416373855/fourn/facture/card.php?id=4

## Report

For example: 3.34 PEN = 1 USD
![Error](https://user-images.githubusercontent.com/53640168/62982978-74746b00-bdf3-11e9-9914-2404808b93ea.jpg)

**Comment by ptibogxiv** [comment]
cf ;) https://github.com/Dolibarr/dolibarr/pull/11676

**Comment by atm-maxime** [comment]
Hi.

Are you sure this is not a misconfiguration? With multicurrency your reference currency is always considered as 1. So if your currency is PEN and you say that 1 USD = 3.34 PEN, then you must have in your setup 1 PEN = 0,29940 USD.

So your USD invoice with total of 100 USD should calculate 334 PEN.
