### ISSUE TITLE
Minor Dashboard layout issue

### ISSUE THREAD

**Issue by Ribero** [Dolibarr/dolibarr#11680]
# Bug

## Environment
- **Version**: 10.0.1
- **OS**: Linux
- **Web server**: nginx/1.15.7
- **PHP**: fpm-fcgi 7.2.13
- **Database**: MySQL or MariaDB 5.5.5-10.3.11-MariaDB
- **URL**: /index.php?mainmenu=home&leftmenu=home

## Report
The main Dashboard (on Home Page) has a small layout issue that prevents correct alignment of different widgets:

<img width="1847" alt="Capture d’écran 2019-08-12 à 19 36 31" src="https://user-images.githubusercontent.com/2266264/62891183-59e3b880-bd45-11e9-96e2-8d4fef545530.png">

Browser used for testing : Safari Version 12.1.2 (13607.3.10) (macOS 10.13.6)

**Comment by hregis** [comment]
@Ribero You emptied the cache of your browser?

**Comment by Ribero** [comment]
Yes. Cache has been cleared before to be empty. 

Same issue on multiple computer. May be it is the same on Windows but I cannot test.

**Comment by hregis** [comment]
@Ribero @eldy 
I passed the padding-bottom from 25% to 10% but the alignment will depend on the activated modules and the size of the screen! see PR https://github.com/Dolibarr/dolibarr/pull/11681/files

![Capture d’écran 2019-08-13 à 07 12 19](https://user-images.githubusercontent.com/454387/62916955-bf15c900-bd9a-11e9-85ad-125664613551.png)

**Comment by Ribero** [comment]
Ok thanks I'll test it asap !
