### ISSUE TITLE
Bug: filter products by for sale/purchase doesn't work

### ISSUE THREAD

**Issue by wtfbrb** [Dolibarr/dolibarr#11687]
# Bug
On the product dashboard there is a list with counts of products with their for sale/for purchase counts.  Those link to the product list page like this: /product/list.php?type=0&tosell=0&tobuy=0

However it does not filter by those, my guess is because 0 is falsy.

## Environment
- **Version**: 9.0.3
- **OS**: google kubernetes engine
- **Web server**: k8s nginx load balancer
- **PHP**: 7.1.30
- **Database**: MySQL or MariaDB 5.7.14-google-log
--
- **URL(s)**:  /product/list.php?

## Expected and actual behavior
For the example it should show products not for sale or purchase.

## Steps to reproduce the behavior
On "Product area" click on any of the links in for sale/purchase counts area.

**Comment by dolibarr95** [comment]
Hi
I think it's the same on V10
she should have something like this:
```
dolibarr/product/list.php?type=0&search_tosell=1&search_tobuy=1
```
instead of 
```
dolibarr/product/list.php?type=0&tosell=1&tobuy=1
```

**Comment by dolibarr95** [comment]
ooops works for me.
