### ISSUE TITLE
Bug: Preserve user language for automatic events when using REST API

### ISSUE THREAD

**Issue by jtraulle** [Dolibarr/dolibarr#11693]
# Bug
When using the REST API to create, validate, classify orders, invoices and other Dolibarr objects and the Events module is activated, the automatically inserted events description are in English regardless of the user langage defined for the API key used to make the requests.

## Environment
- **Version**: 7.x, 8.x, 9.x, 10.x, dev
- **OS**: GNU/Linux
- **Web server**: Apache2
- **PHP**: 7.3
- **Database**: MySQL/MariaDB

## Expected and actual behavior
**Expected** : The automatically inserted events descriptions should preserve the user language defined in the user settings.
**Actual** : The automatically inserted events descriptions are in English regardless of the user language defined for the API key used to make the requests.

## Steps to reproduce the behavior
- create a user and set its language to French
- get the newly created user API key
- enable the REST API module, Thirdparties module, Orders module, Events module
- create an order using the REST API
- validate the order using the REST API
- classify the order as delivered using the REST API
- classify the order as invoiced using the REST API
- go to the newly created order in Dolibarr
- note that events description are written in English
- click on **Classer 'Non facturée'** then on **Classer 'Facturée'**
- note that the newly added automatic event description is written in French (as intended)

## Attached files
![events](https://user-images.githubusercontent.com/613615/63093191-81649c00-bf64-11e9-9293-680e211e73de.png)

**Comment by jtraulle** [comment]
Investigating into this, it seems that the API takes only into account the main app setting about language.

I tried to add 
```php
$langs=new Translate("", $conf);
if ($langs->getDefaultLang() != self::$user->conf->MAIN_LANG_DEFAULT)
{
	DolibarrApi::$lang = self::$user->conf->MAIN_LANG_DEFAULT;
}
``` 

at the end of the `__isAllowed()` function into `api_access.class.php` without luck.

**Comment by eldy** [comment]
We can also use the default language of self::$user
But it will remain the same language for all api call (the on of self::$user)

**Comment by jtraulle** [comment]
> We can also use the default language of self::$user
> But it will remain the same language for all api call (the on of self::$user)

I think this would be better.

**Comment by jtraulle** [comment]
@github-actions Do not close :)

**Comment by inoveaconseil** [comment]
Functional in v16.0.2 with swagger

![Screenshot (11)](https://user-images.githubusercontent.com/15121629/204055543-f8155651-25f6-49db-a993-c4e07f90fb38.png)
