### ISSUE TITLE
Wrong french translation for PropalClassifiedBilledInDolibarr ?

### ISSUE THREAD

**Issue by Ribero** [Dolibarr/dolibarr#11692]
# Bug

## Environment
- **Version**: 10.0.1
- **OS**: Linux
- **Web server**: nginx/1.15.7
- **PHP**: fpm-fcgi 7.2.13
- **Database**: MySQL or MariaDB 5.5.5-10.3.11-MariaDB
- **URL**: /admin/translation.php?mainmenu=home

## Report
I found that a specific automatic event regarding a proposal is probably not correctly translated :

Current _fr_FR_ translation of key **PropalClassifiedBilledInDolibarr** is "_Proposition %s classée payée_"

I Think the right translation should be something like : "_Proposition %s classée ~~payée~~ facturée_"

Of course I corrected it in my own instance of Dolibarr and I asked an access to Transifex but in the meantime I opened this issue.

**Comment by atm-maxime** [comment]
If you asked an access to transifex, wait for approval then you can apply your fix. Thanks for joining the community!

**Comment by Ribero** [comment]
For information only: I updated Transifex.
