### ISSUE TITLE
description of deleted supplier order in calendar wrong

### ISSUE THREAD

**Issue by John-H-Smith** [Dolibarr/dolibarr#11699]
# Bug
If you delete a previously created supplier order, in caldendar view there is the variable name, not a real description. Look at this image:
## Environment
- **Version**: 10.0.1
- **OS**: Ubuntu 16.04.1
- **Web server**:  Apache2
--
- **PHP**: 7.1.30-nmm1
- **Database**: MySQL or MariaDB 5.5.62-0+deb8u1

## Steps to reproduce the behavior
Create a supplier order, have events activated. Delete the order and look the details in the event.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Unbenannt](https://user-images.githubusercontent.com/18233867/63160438-0cee3380-c01e-11e9-881c-eac8d594638f.PNG)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/12139

**Comment by dpriskorn** [comment]
Seems to be fixed. Closing
