### ISSUE TITLE
Feature Request: Add a trigger to manage  links amount/invoiced when creating a payment

### ISSUE THREAD

**Issue by mgribaudo** [Dolibarr/dolibarr#11697]
# Feature Request
Hello,
I am developing a module that allows the management of multiple duedates related to an invoice.
To make it I would need a trigger at the time of the INSERT of the table llx_paiement_facture and llx_paiementfourn_facturefourn in the Paiement e  PaiementFourn classes.

I would be able to make the necessary fix in person.
I have never done this type of intervention and I ask if I can open a relative pull request.

Thanks

**Comment by atm-maxime** [comment]
I think you already have the trigger you need : https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/paiement/class/paiement.class.php#L465

**Comment by atm-maxime** [comment]
And here https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/fourn/class/paiementfourn.class.php#L279

**Comment by mgribaudo** [comment]
Hi, 
I looked at both classes but what I need here

[https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/paiement/class/paiement.class.php#L309](url)

is: 

- get the id of all the new records in the llx_paiement_facture table, with a trigger

`$result = $this->call_trigger ('PAYMENT_CUSTOMER_AMOUNT_INVOICE_CREATE', $user);`

- or perhaps (better for me) an array of properties containing all the ids

`$this->amount_invoice_id[] = $this->db->last_insert_id (MAIN_DB_PREFIX.'paiement_facture');`

Thank you

**Comment by atm-maxime** [comment]
Why don't you use the trigger I pointed out and do a simple select request with the payment ID just created ? This will give you the records of llx_paiement_facture related to the payment

**Comment by mgribaudo** [comment]
You're right, I went to the bottom of the matter and managed with some pirouettes to solve without having to go back to changes to the core.
Thank you.
