### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by s-platform** [Dolibarr/dolibarr#11701]
# Bug

## Environment
- **Version**: 10.0.1
- **OS**: Linux
- **Web server**: LiteSpeed
- **PHP**: litespeed 7.3.6
- **Database**:  5.5.5-10.2.25-MariaDB
- **URL**: /user/card.php?id=1

**Comment by atm-maxime** [comment]
Thanks for you report. Can you reopen and describe the issue ?
