### ISSUE TITLE
Interventions Get Lines API Fix

### ISSUE THREAD

**Issue by pstructures** [Dolibarr/dolibarr#11705]
# Bug
Unable to Retrieve lines of an intervention through the API

## Environment
- **Version**: 10.0.1
- **OS**: Linux varda.uksrv.co.uk 3.10.0-962.3.2.lve1.5.24.5.el7.x86_64 #1 SMP Thu Nov 22 09:42:49 EST 2018 x86_64
- **Web server**: LiteSpeed
- **PHP**: 7.3.8
- **Database**: MySQL or MariaDB 5.5.5-10.2.26-MariaDB-log-cll-lve
- **URL(s)**: API https://*******/api/index.php/interventions

## Expected and actual behavior
Expected to be able to retrieve and edit intervention lines through API.  Actually unable to.

## Steps to reproduce the behavior
Attempt to retrieve lines through API

## Suggested implementation
I have added the function getLinesArray to line 191 of fichinter.class.php and uncommented the get lines section on line 280 of api_fichinter.class.php

Code Added to line 191 of fichinter.class.php:
`	public function getLinesArray()
	{
		return $this->fetch_lines();
	}`

## Suggested steps
Implement new code as detailed above

**Comment by dpriskorn** [comment]
Can you update to v12 or look in develop and see if the problem persists?

**Comment by ksar-ksar** [comment]
Hello,

No answer to the above question since a long time.

If the problem persist you can re-open the issue.
