### ISSUE TITLE
TakePOS: Total including VAT or Total excluding VAT

### ISSUE THREAD

**Issue by lyc-ghub** [Dolibarr/dolibarr#11718]
Dear Dolibarr team,
On the TakePOS interface, the first line of the left table shows:
Total including VAT Discount Qty Total excluding VAT
In reality, the "Total excluding VAT" column displays the prices including VAT.
Thank you.
Best regards,

**Comment by ptibogxiv** [comment]
fix here https://github.com/Dolibarr/dolibarr/pull/11737

;)

**Comment by lyc-ghub** [comment]
Hello ptibogxiv,

Thanks. Good news! :)

Best regards,
