### ISSUE TITLE
TakePOS, bug: payment with several payment methods

### ISSUE THREAD

**Issue by lyc-ghub** [Dolibarr/dolibarr#11719]
Dear Dolibarr team,
By making a payment in TakePOS with (at least) two means of payment, if the last amount exceeds the expected amount, the interface correctly indicates the amount to be returned. Nevertheless, the system records the amount paid by the customer (without taking into account the difference remitted), and therefore creates an invoice whose payment exceeds its actual value.
So Dolibarr **10.0.1** does not close it, and it is then necessary to add a manual entry of the difference to be able to close it.
Thank you.
Best regards,

**Comment by andreubisquerra** [comment]
Solved in https://github.com/Dolibarr/dolibarr/pull/12191

**Comment by lyc-ghub** [comment]
Thank you.
Best regards,
