### ISSUE TITLE
Bug: date de facturation postérieure à la date du jour

### ISSUE THREAD

**Issue by WhilelM** [Dolibarr/dolibarr#11714]
# Bug

## Environment
- **Version**: 9.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: apache2handler 7.3.4-2
- **Database**: MySQL or MariaDB 5.5.5-10.3.15-MariaDB-1
- **URL**: /htdocs/fourn/facture/card.php

## Report

Lorsque l'on enregistre une facture fournisseur dont la date de facturation est postérieure à la date du jour, Dolibarr nous affiche un message d'attention indiquant "Attention, la date de facturation est antérieur à la date actuelle". Il faudrait le modifier pour indiquer à la place "Attention, la date de facturation est postérieure à la date actuelle"

**Comment by atm-maxime** [comment]
Hi ! Thanks for contributing, translation are done on transifex. You can check if this has been already fixed or subscribe to post your own fix.
Cheers !
