### ISSUE TITLE
Feature request: TakePOS, add some new stats on the cash register closure lists page. 

### ISSUE THREAD

**Issue by lyc-ghub** [Dolibarr/dolibarr#11745]
Dear Dolibarr Team,
In my opinion, it could be useful to add on the cash register closure lists page some simple stats in order to obtain a quick and full view, directly on Dolibarr (**10.0.1**), of the sales revenue of each closure (generally, each passed day).
More explicitly, I could suggest to add a column directly showing, for _cash, the difference between the line final cash and the line opening cash_. By extension, it could also be interesting to add a new column, _totalling all received payments for each line_.
By extension again, a _new line_ could be added to _cumulate_ each sales revenue column by payment type (and also the total).
Finally, why not, a special line (which could be distinguished from others by a slightly different aesthetic) could be added to show the _current sales revenue_, before closing. The aim would be to know the current (daily) sales status, if sales are in real time in accordance with what is expected.
The final idea is to know, at a glance, the daily and monthly sales, and to be able to compare them quickly.

```
... opening - closing -  cash  - cheque -  card  - total  ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
TOTAL                   xxxxxx - xxxxxx - xxxxxx - xxxxxx


=== CURRECT TakePOS ===
... opening - closing -  cash  - cheque -  card  - total  ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
===                 ===
```

Thank you.
Best regards,

**Comment by lyc-ghub** [comment]
Dear Dolibarr Team,
A filter per month could also be very useful (_the idea remains to simplify the accounting and to quickly know the state of sales and its history_).

```
Filter : [year] / [month]

... opening - closing -  cash  - cheque -  card  - total  ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
TOTAL                   xxxxxx - xxxxxx - xxxxxx - xxxxxx


=== CURRECT TakePOS ===
... opening - closing -  cash  - cheque -  card  - total  ...
...  xxxxxx - xxxxxxx - xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
===                 ===
```

Or, simpler still, a page dedicated to sales statistics :

```
Filter : [year] / [month]

       ...   cash  - cheque -  card  - TOTAL  ...
       ...  xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
       ...  xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
       ...  xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
       ...  xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
       ...  xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
TOTAL       xxxxxx - xxxxxx - xxxxxx - xxxxxx


===                  CURRECT TakePOS                  ===
       ...   cash  - cheque -  card  - TOTAL  ...
       ...  xxxxxx - xxxxxx - xxxxxx - xxxxxx ...
===                                                   ===
```

Thank you.
Best regards,

**Comment by denis-poncereau** [comment]
I think it's a good idea to improve this cash closure control feature. The closure has to be done daily to check the received payments (see if there is a difference).
It is also good to have monthly stats (or even better, between two dates to have month, week, etc. easily), on a separate page maybe ?
Your tables on your second post seem good to me !
What do you mean by "currect" ?
Other question : how are deposits managed ? If you make a put cash on you bank account, it doesn't appear on the cash control ticket, but it should, right ?

**Comment by lyc-ghub** [comment]
By "currect," I mean... a typing error, then copy and paste propagating that error.
It's not "currect", but "current", i.e. a table that summarizes "live" the day's sales, without having to wait for the closing. The aim is to know the current (daily) sales status, if sales are in real time in accordance with what is expected.

As for deposits, a simple way is to make internal transfers from a "cash" box to a "deposit"/"bank" box, in order to start every day with the same initial cash amount.

**Comment by denis-poncereau** [comment]
Ok, in France we call those "live" or intermediary controls "tickets X" ou "X de caisse" and the definitive daily control "ticket Z" or "Z de caisse". the Z are the one that will be recorded into accountancy. So they basically have the same features but the Z has to be correct to be recorded while the X is temporary.

Agreed for the deposit, the fact is that they currently do not appear on the cash control page (tested).
The best would be to manage them from the POS (_my drawer is full, I remove X€ to put them in the bank/safe (other account in Dolibarr)_). Even the cash control page should be accessible by the POS interface I think.

**Comment by kslom1** [comment]
Agree with the above suggestions.  Using 12.0.1 currently.
