### ISSUE TITLE
Discussion: Autobuild doxygen doc using Travis-CI cron and GitHub pages

### ISSUE THREAD

**Issue by jtraulle** [Dolibarr/dolibarr#11759]
Related to #7618

Related to https://www.dolibarr.fr/forum/11-suggestionsnouvelles-fonctionnalites/63601-besoin-doxygen

It would be great if we could have on https://doxygen.dolibarr.org/ the latest version of the develop branch and the supported versions of Dolibarr.

It is possible to use the free GitHub pages feature that allow to host statically generated sites like the output of Doxygen.

The Doxygen output could be regenerated automatically using Travis-CI.

See https://gist.github.com/vidavidorra/548ffbcdae99d752da02 for example.

Moreover, it is to be noted that currently available doc on https://doxygen.dolibarr.org/ misses Inheritance and Collaboration diagrams on the classes pages. This should also be resolved.

If you are interested, I can look at it on a test repo :wink:

**Comment by eldy** [comment]
Yes, i am interested. Best if we can redirect domain doxygen.dolibarr.org to the github pages.

**Comment by jtraulle** [comment]
I have started something here using Travis-CI and the deploy mechanism that they provide to publish to GitHub Pages.

https://jtraulle.github.io/dolibarr/index.html (targets develop branch as source for the generated doxygen doc and output to gh-pages branch)

To be continued :wink:

**Comment by jtraulle** [comment]
I have made good progress about automating this with Travis-CI.

Here is the .travis.yml file : https://github.com/jtraulle/dolibarr-doxygen/blob/master/.travis.yml

I am encountering difficulties with the hosting part as GitHub Page build fails (presumably because of the size of the repo).

I have tried hosting at Netlify as an alternative but the build also fails here : https://app.netlify.com/sites/dolibarr-doxygen/deploys/5d67c2828977cec9c42437de

I have emailed both support (GitHub and Netlify) to try to have more info about the build failures. Apart from the size (repo is about 400M compressed files), I do not know what could be wrong.

I have done a quick math and generated Doxygen docs for a version is about 250M each. As of now, when processing all the tags, we have currently 117 tags in the dolibarr/dolibarr repo => max size of generated content should not exceed  250M * 117 = 30G

For info, current limit for GitHub pages is 1Go and for Netlify it is 100G soft (so this should definitely be good with Netlify).

In the meantime, it can be checked out using Statically CDN here :
https://cdn.statically.io/gh/jtraulle/dolibarr-doxygen/gh-pages/index.html

I will let you know what both support said.

**Comment by jtraulle** [comment]
Also find out https://zeit.co ; will try that also 😉

**Comment by jtraulle** [comment]
I finally come to the conclusion that generating all versions tags was wrong (and probably useless anyway) => more than 800K files.

I reached an acceptable compromise by generating **develop**, and last tagged versions of **v10**, **v9**, **v8** and **v7**.

Generation and push to GitHub takes about 10 minutes (and some more minutes to be processed and available online as GitHub pages). This is done with TravisCI (an example of a build here : https://travis-ci.org/jtraulle/dolibarr-doxygen/builds/579443935)

The result can be checked out here : https://jtraulle.github.io/dolibarr-doxygen

@eldy Is it possible for you to create a new repository named `doc` or `docs` or `doxygen` into the `dolibarr` organisation on GitHub and grant me write access on this particular repository ?

When this is done, I will give you the instructions to alter the DNS of subdomain doxygen to point to the GitHub pages :wink:

**Comment by jtraulle** [comment]
I have tried locally Doxygen 1.8.16 to generate PDF offline version of the doc from LaTeX and it is working great but I have noticed that some classes are not properly documented anymore with this version.

I have opened an issue upstream at doxygen/doxygen#7243

**Comment by jtraulle** [comment]
The issue is solved.

Here is an example of a generated PDF file for develop (5196 pages) :
[dolibarr-develop.pdf](https://github.com/Dolibarr/dolibarr/files/3567147/dolibarr-develop.pdf)

I will see to add it to the TravisCI job :slightly_smiling_face:

**Comment by jtraulle** [comment]
This has been deployed on https://doxygen.dolibarr.org
