### ISSUE TITLE
Add ability to show linked object reference in list view

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#11779]
# Feature Request
When we list commercial proposals, it would be a good idea to have the ability to show directly in list view the attached command, or whatever dolibar native object.

## Use case
I come from ERP that locks workflows. When I list my proposals (signed ones), I can directly show if i managed to task the command.

## Suggested implementation
Select all Ref. From native objects that are linked and show them in a tab view. Or, you wan simply show a boolean that explicit if linked objects are linked, and show them line by line by a mouseover.

## Suggested steps
You can ask me why I suggest this feature. But I think it is a good idea not to let people follow non linear workflows if you want dolibarr to step forward. I like its free-in-mind commercial way, but, it let me drop some precious time asking if i already done thinks in time.

**Comment by jtraulle** [comment]
It would be interesting but I am skeptical about the performance issue that could occur ...

Calling `fetchObjectLinked()` on each line of list table (object) would add a bunch of SQL queries.

**Comment by matDOTviguier** [comment]
For sure it would.
