### ISSUE TITLE
[REST API] /products or /products/{id} doesn't return pictures

### ISSUE THREAD

**Issue by QuentinPetel** [Dolibarr/dolibarr#11782]
# Feature Request
Right now, when fetching a product i cannot get the images i previously linked to my product through the REST API. Is there a way to get the pictures displayed in Dolibarr for the products ? Am i missing something ?

## Use case
I would like to get the url of the images linked to a product in Dolibarr on the output of the request for this product. To avoid doing this into another administration site.

## Suggested implementation
GET /products
```
[
    // ...
    {
         'ref': 'toto'
         'label': 'Toto'
         // ...
         'img(s)': [
               'https::dolibarr_url/path_to_image_1' ,
               'https::dolibarr_url/path_to_image_2' ,
         ]
    },
    // ...
]
```

**Comment by ptibogxiv** [comment]
It was fixed in dev and v10 version

**Comment by ptibogxiv** [comment]
I've posted it few weeks https://github.com/Dolibarr/dolibarr/pull/11620

**Comment by QuentinPetel** [comment]
Will your patch be in 10.0.2 ?

**Comment by ptibogxiv** [comment]
yes, but you need to call with document API for get image or PDF or other linked document to a product as other object in dolibarr.

**Comment by QuentinPetel** [comment]
Yes, i checked your patch and the issue #11399 ! Thank you.
