### ISSUE TITLE
Feature request: Dolibarr Logo & FontAwesome

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#11784]
# Instructions
I know this is not the right place but just to let the Dolibarr users know:

**Give a chance to Dolibarr logo to be in Font Awesome!**

# Feature Request
We can add the Dolibarr logo in Font Awesome lib.
**Up vote and add comments to give a chance to our logo.**

Here is the link to Font Awesome Github page :

https://github.com/FortAwesome/Font-Awesome/issues/15397

## Use case
```html
<!--
It could be something like that to display a Dolibarr logo (as it done for Worpress...).
-->
<i class="fab fa-dolibarr"></i>
```
**Wonderful isn't it?**

## Why
Because Dolibarr use Font Awesome.
I think it could be usefull for our ERP and other website menu...

## Suggested steps

- [x] Add an icon request in Github/Font Awesome (My job)
- [x] Accept / Label the request  in Github/Font Awesome (Font Awesome job)
- [x] Invit the community to upvote / comment this request (Dolibarr community job)
- [ ] Design publish the logo (Font Awesome job)
- [ ] Use the icon and enjoy

Tks for reading

**Comment by dolibarr95** [comment]
Hi 
Today 17 thumbs up.
Please continue to support our ERP !!!

**Comment by dolibarr95** [comment]
Tks to : 

@ptibogxiv
@philazerty
@defrance
@aspangaro
@atm-maxime
@delthair
@altatof
@arre8
@SylvainLegrand
@jtraulle
@papoteur-mga
@futurehousestore
@ariffidaali
@ksar-ksar
@inoveaconseil
@hregis
@fappels 
@pcworxstech
@matDOTviguier
@atm-john
@cfoellmann
@tryphon28
@DGCarramona
@frederic34
@wdammak

**Comment by wdammak** [comment]
easy with 100% css 
`<i class="fa fa-dolibarr fa-5x"></i>`

>.fa-dolibarr{
  color: #235481;
  background: currentColor;
  height: 150px;
  width: 150px;
  position: relative;
}
.fa-dolibarr:before{
  content: '';
  position: absolute;
  left: 19%;
  top: 17%;
  width: 25%;
  height: 25%;
  border: solid 30px white;
  border-radius: 0% 200% 200% 0% / 0% 180% 180% 0%;
}
.fa-dolibarr:after{
  content: '';
  position: absolute;
  left: 19%;
  top: 17%;
  width: 5px;
  height: 25%;
  border-bottom: solid 60px currentColor;
  margin-left: 30px; 
}

rendering: [http://jsfiddle.net/zv4t6ha1/](http://jsfiddle.net/zv4t6ha1/)

**Comment by dolibarr95** [comment]
@wdammak +1

**Comment by eldy** [comment]
Really tricky. I will add the definition into a theme to see if it can be used/useful
