### ISSUE TITLE
Right to delete a document on propal and other element

### ISSUE THREAD

**Issue by iouston** [Dolibarr/dolibarr#11788]
# Feature Request
add a permission on each object to delete the uploaded files

## Use case
In dolibarr 9 and +
You can delete a uploaded file only if you have the delete object right.
I'm thinkins that it's not good beacause you can have the permission to delete a file but not the entire propal. It's quite different.

**Comment by dpriskorn** [comment]
is this still a needed feature for you?

**Comment by iouston** [comment]
Yes i would have this feature and i'm thinking that it will be great for the soft

**Comment by iouston** [comment]
I still think that this feature would be necessary for a software like dolibarr.

**Comment by iouston** [comment]
still needed
