### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Nightbutterly** [Dolibarr/dolibarr#11791]
[Emailing.pdf](https://github.com/Dolibarr/dolibarr/files/3556388/Emailing.pdf)
# Bug

## Environment
- **Version**: 10.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.2.21
- **Database**: MySQL or MariaDB 5.5.60-0+deb7u1-log
- **URL**: /comm/mailing/cibles.php?id=245

**Comment by jtraulle** [comment]
You should report the warnings directly into the issue description.
Please, remove the attachment as it contains personal information from third parties (email addresses).

**Comment by eldy** [comment]
Fixed by 66a9fabd06ee295870a8b14039d801a730816021
