### ISSUE TITLE
using build/docker fails with database error

### ISSUE THREAD

**Issue by dseichter** [Dolibarr/dolibarr#11815]
did the following steps:
clone dolibar repo from github
run composer install
run docker-compose up of build/docker

the installer appears, but stopped with the following message:
```
Warning: mysqli::__construct(): (HY000/2002): Connection refused in /var/www/html/core/db/mysqli.class.php on line 205
Connection refused
The database connection failed: the host or super user parameters must be wrong.

Go back and check/correct the parameters.
```
used root/root, created a database user within phpmyadmin, etc. but nothing worked.
switched to branch 10.0 and the same issue.

Do you have any hint?

Running on Linux Mint 19, no firewall for local services. Is there something missing?

**Comment by tuxgasy** [comment]
Check if conf/config.php already exists. If yes, check if database informations is OK.

**Comment by dseichter** [comment]
just clone repo again and will try to checkfor the files today.

additional note: 
in my "old" cloned repository, there was just copied the conf.example.php to conf.php, but no credentials set up. Will try it with new clone today.

**Comment by tuxgasy** [comment]
Remove conf.php file and go to http://0.0.0.0/install to start the installation.

**Comment by dseichter** [comment]
I found the solution:
using docker, sockets not working :( 
added to **docker-compose.yml** the ports to listen to:
```
mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dolibarr
    ports:
        - "3306:3306"
```

and need to use the IP address of the docker container for mariadb (in my case 172.17.0.2). Now it workes!

see my config
```
$dolibarr_main_url_root='http://127.0.0.1';
$dolibarr_main_document_root='/var/www/html';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/html/custom';
$dolibarr_main_data_root='/var/www/html/documents';
$dolibarr_main_db_host='172.17.0.2';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='dolibarr';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='root';
$dolibarr_main_db_pass='root';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
```
should be updated in the readme file and fixed in docker-compose.yml (if no one had another solution).

**Comment by tuxgasy** [comment]
You do not need to expose mariaDB port. In conf.php file, set **mariadb** as database host.

**Comment by dseichter** [comment]
thank you, that also worked. Ok, can anyone add this to the documentation or should I do this by changing and creating a pull request?!

**Comment by dseichter** [comment]
after this issue is merged, I think we can close that issue.
