### ISSUE TITLE
Changed labels of vacations not shown in vacation type (drop-down-list)

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11826]
# Instructions
The labels of the standard vacations/holiday can be changed, but the change is not shown in the drop-down-list of the vacation type on the new vacation request page

# Bug
The build-in types `LEAVE_OTHER` , `LEAVE_PAID`  and `LEAVE_SICK` show always the same label (maybe from the translation file)

## Environment
- **Version**: 10.0.1 
- **OS**: Windows NT DOLIBARR 6.2 build 9200 (Windows Server 2012 Standard Edition) i586
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL(s)**: `/dolibarr/holiday/card.php?mainmenu=hrm&leftmenu=holiday&action=request`

## Expected and actual behavior
Show the 
changed labels for `LEAVE_OTHER` , `LEAVE_PAID` and `LEAVE_SICK in the drop-down-list of the vacation type on the new vacation request page

## Steps to reproduce the behavior
* Change the label of the vacations/holiday
* Create a new vacation request
* Select the vacation type

## Attached files
**Settings: vacation types**
![2019-09-05 11_29_39-Dolibarr – Opera](https://user-images.githubusercontent.com/17874713/64331214-b21f7a80-cfd2-11e9-8129-8ba3ed571c29.png)

**Page: new vacation request**
![2019-09-05 11_30_10-Urlaub](https://user-images.githubusercontent.com/17874713/64331267-c5324a80-cfd2-11e9-8304-ad6c6a298b4d.png)

**Comment by atm-maxime** [comment]
To change label translations, you should use Home > Setup > Translations. The labels shown in the dropdown list are the translated labels, not the labels you modified in the dictionary.

**Comment by ghost** [comment]
okay, thanks

--> closed as not a bug
