### ISSUE TITLE
Missing not null restraint in table

### ISSUE THREAD

**Issue by swedebugia** [Dolibarr/dolibarr#11828]
# Bug
missing db restraint in table llx_commande_fournisseurdet

## Environment
- **Version**: 9.0.1
- **Database**: POSTGRES

## Expected and actual behavior
db should warn when trying to insert NULL in product_type, it does not

**Comment by eldy** [comment]
Can you describe which dolibarr feature or api try to insert null into table ?

**Comment by swedebugia** [comment]
Hi, I inserted the a line manually and afterwards got an error in Dolibarr about the value being NULL. For this reason I would prefer the database to have warned me.

(the reason to insert it manually into the db was that I had 25 lines on the purchase order and it was very tedious to insert it one line at a time in Dolibarr)

**Comment by dpriskorn** [comment]
in v12 the standard value is 0, maybe this is good enough?

**Comment by eldy** [comment]
I still not find the feature or api in dolibarr that use null to insert.
Can you describe which dolibarr screen you use (url and screenshot) that tries to insert null into table ?

**Comment by dpriskorn** [comment]
Oh, sorry for being unclear.  I inserted it manually via a db  query from my python script.

**Comment by ksar-ksar** [comment]
Hello,

Still relevant ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
