### ISSUE TITLE
Bug:  creating third party - selection table for default language too small to see

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#11833]
# Bug

when creating a new business partner (third parties)
the selection table of default language is so small you can not see the content

## Environment
- **Version**: 10.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Univention)
- **PHP**: apache2handler 7.0.33-0+deb9u3
- **Database**: MySQL or MariaDB 5.5.5-10.1.38-MariaDB-0+deb9u1
- **URL**: /_test/dolitest10/htdocs/societe/index.php?mainmenu=companies&leftmenu=

## Report

when creating a new business partner (third parties)
the selection table of default language is so small you can not see the content

**Comment by atm-maxime** [comment]
Works for me on 10.0.2 :
![image](https://user-images.githubusercontent.com/2097773/64923363-8a51c300-d7d9-11e9-927e-5e02df07ae0b.png)
Can you tell us which browser you're using and/or give us a screenshot ?

**Comment by com4WEB** [comment]
Hello, 

I see now, it only happens in Dolibarr 10 if the external module
'Personal View' is activated. 

If i deactivate this, it shows again the full table widt. 

So I think it is no Dolibarr Bug. 

Am 15.09.2019 16:55, schrieb Maxime Kohlhaas:

> Works for me on 10.0.2 :
> [1]
> Can you tell us which browser you're using and/or give us a screenshot ? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://user-images.githubusercontent.com/2097773/64923363-8a51c300-d7d9-11e9-927e-5e02df07ae0b.png
[2]
https://github.com/Dolibarr/dolibarr/issues/11833?email_source=notifications&amp;email_token=AKCCGNAJGROUS24IROSGNPDQJZEGRA5CNFSM4IUHK632YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6XSMXA#issuecomment-531572316
[3]
