### ISSUE TITLE
Default account errors - missing warning or check

### ISSUE THREAD

**Issue by swedebugia** [Dolibarr/dolibarr#11840]
# Bug
Is detailed here in the warning I set up my top to accounts to 3000 and 4000 respectively. That resulted in a situation where all the reports report mixed results.
See https://wiki.dolibarr.org/index.php/Module_Accounting#Default_accounts

## Environment
- **Version**: 9.0.1

## Expected and actual behavior
Dolibarr should warn or refuse to let me save when any of the top 3 accounts in bold is the same as any of the ones below.

**Comment by eldy** [comment]
Can be addressed by adding a check that default accounts are different if set.
