### ISSUE TITLE
[BUG?] Only 3 connection from 3 PC possible at same time (Windows Server 2019)

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11851]
Hello,

I have the problem that only three connection from 3 different PC are possible at same time (3 users can use Dolibarr at same time). When the fourth try to access to Dolibarr he get no answer.

Only when another of the three users make a new request (e.g. click a link in Dolibarr) the fourth user see the login screen.

The debug bar in Dolibarr itself say that the answer take only up to 3 seconds and Wireshark say that the request is immediately on the server.

So it seems to be that the problem is somewhere between the request on Apache and the answer from Dolibarr, PHP or Apache ?

I have checkt that `xdebug` is deactivate and I have activate the cache for static resources, but I have see no improvements.

Have anyone an idea how can i fix this problem?
Sincere regards

*Environment and Software* 
* Windows Server 2019 Standard 1809
* Dolibarr: 10.0.1 (via DoliWamp, used language: German)
* Apache: 2.4.9 (from DoliWamp)
* PHP: 5.5.12  (from DoliWamp)
* MySQL: 5.0.45 (from DoliWamp)

**Comment by hregis** [comment]
@TobiasSekan 
it does not come from Dolibarr!
you have to check the configuration of Apache, 
maybe a limit too low of simultaneous connections

**Comment by ghost** [comment]
@hregis You are right. 👍 
I have found the problem is that Apache don't close any connection and reach the maximum connections after a short time. Currently I don't now why the connections will not be closed., but is good for further investigation into this problem.

-> ticket closed as not a bug

**Comment by hregis** [comment]
@TobiasSekan 
check this parameters 

```
ServerLimit
StartServers
MaxClients
MinSpareThreads
MaxSpareThreads
ThreadsPerChild
```

**Comment by ghost** [comment]
I have test a few value combinations that i have found in a few forums, but i have seen no significant improvement.

But I think the biggest Problem is the extrem outdated Apache version in the [DoliWampPackage](https://sourceforge.net/projects/dolibarr/files/) for Windows. The version is 2.4.9 and is over 5 years old.

In the next days I start to test a fresh installation with the current [WampServer](http://www.wampserver.com/en/)
