### ISSUE TITLE
Bug stats on project tasks

### ISSUE THREAD

**Issue by sam-anam1** [Dolibarr/dolibarr#11856]
Dolibarr: 10.0.1
Level of features: 0
PHP: 7.2
Server: Apache/2.4.25
OS: Linux
htdocs/projet/class/tasksstats.class.php 

**Bug**

it shows for external users end with read user project permission .

Dolibarr has detected a technical error
Requested URL: /htdocs/projet/tasks/stats/index.php?leftmenu=projects
Referer: /htdocs/projet/index.php?mainmenu=project&leftmenu=
Menu manager: eldy_menu.php

**Modules/Applications**: user, product, accounting, service, stock, projet, resource, ecm, categorie, multicurrency, bookmark, workflow, export, opensurvey, notification, mailing, emailcollector, cron, socialnetworks, paypal, clicktodial, holiday, expensereport, adherent, societe, propal, commande, contrat, ficheinter, ticket, agenda, fournisseur, supplier_proposal, facture, tax, salaries, loan, banque, prelevement, margin
**Database type manager**: mysqli
Latest database access request error: SELECT date_format(t.datec,'%m') as dm, COUNT(t.rowid) as nb FROM llx_projet_task as t INNER JOIN llx_projet as p ON p.rowid = t.fk_projet INNER JOIN llx_societe_commerciaux as sc ON sc.fk_soc=t.fk_soc AND sc.fk_user=2 WHERE t.entity IN (1) AND p.fk_soc=2 AND t.datec BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' GROUP BY dm ORDER BY dm DESC

**Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 't.fk_soc' in 'on clause'**

**Comment by byque** [comment]
It also shows for non-admin users with read user project permission. I found a bypass by activating the user permission to extend access to third parties.
![dolibarr_fix](https://user-images.githubusercontent.com/8848953/67319926-32426680-f4d3-11e9-918d-47a69c87a9c7.png)

**Comment by aweher** [comment]
Same here after upgrading to from 16.0.3 to 16.0.4

**Modules/Applications:** user, contrat, supplier_proposal, tax, categorie, fckeditor, multicurrency, product, mailing, geoipmaxmind, oauth, receiptprinter, gravatar, propal, partnership, paymentbybanktransfer, prelevement, productbatch, stock, expedition, projet, eventorganization, bookmark, notification, ficheinter, reception, agenda, banque, barcode, cron, ecm, expensereport, opensurvey, printing, resource, salaries, service

**Database type manager:** `mysqli`

**Latest database access request error:** `SELECT product.ref, COUNT(product.ref) as nb, SUM(tl.total_ht) as total, AVG(tl.total_ht) as avg FROM erp_propal as p, erp_propaldet as tl, erp_product as product INNER JOIN erp_societe_commerciaux as sc ON p.fk_soc = sc.fk_soc AND sc.fk_user = 2 WHERE p.entity IN (1) AND p.rowid = tl.fk_propal AND tl.fk_product = product.rowid AND p.datep BETWEEN '2023-01-01 00:00:00' AND '2023-12-31 23:59:59' GROUP BY product.ref ORDER BY nb DESC`

**Return code for latest database access request error:** DB_ERROR_NOSUCHFIELD

**Information for latest database access request error:** Unknown column 'p.fk_soc' in 'on clause'
