### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Nightbutterly** [Dolibarr/dolibarr#11863]
# Bug

Warning: A non-numeric value encountered in /homepages/46/d178172534/htdocs/Euro-ERP-CRM/htdocs/commande/card.php on line 936

Warning: Cannot modify header information - headers already sent by (output started at /homepages/46/d178172534/htdocs/Euro-ERP-CRM/htdocs/commande/card.php:936) in /homepages/46/d178172534/htdocs/Euro-ERP-CRM/htdocs/main.inc.php on line 1146

Warning: Cannot modify header information - headers already sent by (output started at /homepages/46/d178172534/htdocs/Euro-ERP-CRM/htdocs/commande/card.php:936) in /homepages/46/d178172534/htdocs/Euro-ERP-CRM/htdocs/main.inc.php on line 1149

Warning: Cannot modify header information - headers already sent by (output started at /homepages/46/d178172534/htdocs/Euro-ERP-CRM/htdocs/commande/card.php:936) in /homepages/46/d178172534/htdocs/Euro-ERP-CRM/htdocs/main.inc.php on line 1150

## Environment
- **Version**: 10.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.9
- **Database**: MySQL or MariaDB 5.5.60-0+deb7u1-log
- **URL**: /commande/card.php?id=1586

**Comment by aspangaro** [comment]
It's not a bug, you have a problem with your installation. In your message, you have an htdocs directory in another htdocs directory...

Please check your installation or call a prefered partner to help you.

Have a nice Day ;)

**Comment by hregis** [comment]
@Nightbutterly @aspangaro 
i send a PR #11870
