### ISSUE TITLE
Transifex strings not equal to en_US files in the repo

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#11875]
I am trying to fix up all the translation issues I can find based on de_DE but Transifex is not up-to-date.

Following example:
`ReductionShort` is in the code base, in en_US https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/langs/en_US/bills.lang#L287 and de_DE https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/langs/de_DE/bills.lang#L287
But the string is not in the transifex db.

How is syncing handled? The string I mention above must have been added manually, right?

To my understanding syncing needs to be done this way:

1. Add string to /langs/en_US/<filename>.lang in the repo

1. Sync `en_US` -> `transifex`

1. export `transifex` -> /langs/`non-en_US`/filename.lang

That needs to happen on a trigger or at least daily.
If it happened daily the evolution of the translations would be tracked in git alongside the UI changes

**Comment by eldy** [comment]
Yes syncing is done that way:

Add string to /langs/en_US/.lang in the repo

Sync en_US -> transifex (but sync is not done in real time and may be delayed of several weeks)

export transifex -> /langs/non-en_US/filename.lang

**Comment by eldy** [comment]
I added a cron to sync every weeks. Updating more frequently may generates too many alerts to developers, asking them to translate new strings every day, so weekly seems a better frequency.
