### ISSUE TITLE
UI string 'Customer'

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#11877]
# Bug
I an issue with the string `Customer` in the frontend.
It will not be displayed in German (de_DE) unless I add a custom translation in the settings.

Otherwise all instances of "Customer" are not translated.
Examples: Select field on the add new thirdparty, select field for the thirdparty type on the list page, tab on the thirdparty details page.

The issue consists for all languages except `fr_FR`! I am unsure about `en_US` since the key equals the output.

in `langs/de_DE/`
these exist:
```
Customer=Kunde
Customers=Kunden
```

I invested 3 hours now to find an error in the php code. But I cannot find an issue there.

Curious thing:
When I set the thirdparty to prospect+customer the tab on the card.php is half-translated (red). The string `ProspectCustomer=Interessent / Kunde` (green) from the same .lang file is picked up properly.
See image:
![Anmerkung 2019-09-12 132630](https://user-images.githubusercontent.com/1256090/64780701-5ff5d080-d561-11e9-93b9-977f3eb8de9f.png)

## Environment
- **Version**: current-master (~10.0.1)

## Expected and actual behavior
Translation is used from the .lang file

**Comment by laudeco** [comment]
This has been fixed in the next version since it's, I guess, not really a bug. But, more one missing feature.

**Comment by cfoellmann** [comment]
There needs to be an automated way to fetch all the strings to allow translators to use transifex reliably.
Missing the "Customer" in an ERP or CRM is a very major problem in my eyes-

**Comment by laudeco** [comment]
Yes but it gonna work on the V11 since when I use the dutch language I see the correct translation. So for me this is already done.
