### ISSUE TITLE
[BUG] E-Mail in tool-tip of a vendor is always empty on the start page

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11879]
# Bug
E-Mail in tool-tip of a vendor is always empty on the start page

![2019-09-12 14_23_19-Start - Dolibarr 10 0 2 – Opera](https://user-images.githubusercontent.com/17874713/64783961-596b5700-d569-11e9-8448-e27bf87baa41.png)

Vendor page

![2019-09-12 14_23_35-Aischmann GbR - Karte – Opera](https://user-images.githubusercontent.com/17874713/64783966-5a9c8400-d569-11e9-84dd-05a20a0faf51.png)

## Environment
- **Version**: 10.0.2
- **OS**: Windows NT DOLIBARR 10.0 build 17763 (Windows Server 2016) AMD64
- **Web server**: Apache/2.4.39 (Win64) PHP/7.2.18
- **PHP**: 7.2.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.14-MariaDB
- **URLs**: `dolibarr/index.php?mainmenu=home&leftmenu=home`

## Actual behavior
E-Mail in tool-tip of a vendor is empty on start page

![2019-09-12 14_23_19-Start - Dolibarr 10 0 2 – Opera](https://user-images.githubusercontent.com/17874713/64783961-596b5700-d569-11e9-8448-e27bf87baa41.png)

## Expected behaviour 
Show the E-Mail of the vendor in each vendor tool-tip (same behaviour on the vendor page)

![2019-09-12 14_23_56-Geschäftspartner – Opera](https://user-images.githubusercontent.com/17874713/64784109-9f281f80-d569-11e9-9bbc-5cdb0b2a2205.png)

## Steps to reproduce the behavior
1. Add a vendor 
2. Add a E-Mail address to the vendor
3. Open the start page
4. Hover over the vendor

**Comment by atm-maxime** [comment]
Confirmed, several widget boxes on the homepage don't display details on the thirdparty.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/11923 for box contacts

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/11924 for box supplier

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/12314 for box propal
