### ISSUE TITLE
When there is only one bank account, select it by default

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#11878]
# Instructions
* When there is only one bank account in the system. When you try to enter one payment on bill, expense note, ... the system should select this one by default.

# Feature Request
Select by default the only bank account when only one exists. The empty bank account should be possible since this field is not a required field.

## Use case
* On bill creation
* On payment of bill, expense note, ...

**Comment by manu-p** [comment]
Same request please.

**Comment by manu-p** [comment]
Here, in french : https://www.dolibarr.fr/forum/t/compte-bancaire-par-defaut/32480/5

I hope this feature is implemented, one day! :-)

**Comment by laudeco** [comment]
Definitely I'll, without it it's time consuming!!

L.
