### ISSUE TITLE
Inconsistencies with the configuration of the custom referent element of a project when you try to remove one element

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#11881]
On the page of the elements of a project : http://dolibarr.loc/projet/element.php?id=6

When you add a custom referent, you can give the key _"project_field"_. This field says which column stores the link with the project.

![image](https://user-images.githubusercontent.com/3658458/64790356-414e0480-d576-11e9-828a-52bed2b98ab5.png)

But, when you try to unlink the element (cf the screenshot), the method _remove_element_ of the project doesn't take that property into account.
```
/**
	 *    Associate element to a project
	 *
	 *    @param	string	$tableName			Table of the element to update
	 *    @param	int		$elementSelectId	Key-rowid of the line of the element to update
	 *    @return	int							1 if OK or < 0 if KO
	 */
	function remove_element($tableName, $elementSelectId)
	{
        // phpcs:enable
		$sql="UPDATE ".MAIN_DB_PREFIX.$tableName;

		if ($TableName=="actioncomm")
		{
			$sql.= " SET fk_project=NULL";
			$sql.= " WHERE id=".$elementSelectId;
		}
		else
		{
			$sql.= " SET fk_projet=NULL";
			$sql.= " WHERE rowid=".$elementSelectId;
		}

		dol_syslog(get_class($this)."::remove_element", LOG_DEBUG);
		$resql=$this->db->query($sql);
		if (!$resql) {
			$this->error=$this->db->lasterror();
			return -1;
		}else {
			return 1;
		}
	}
```

The bug is present in all versions I guess, at least on the latest one it is. I propose to fix that issue on the version 10.

kind regards
L.

**Comment by hregis** [comment]
@laudeco with what type of element?

**Comment by laudeco** [comment]
@hregis doesn't matter the type of the custom element (here it's one of mine custom module ). The problem doesn't come from the element itself but more from the project module.

When you configure your element, you set the column that store th link between the object and the project. This column is correctly used by the fetch. but, not by the remove link
