### ISSUE TITLE
[BUG] opensurvey module (sondage) - shifted Answers

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#11882]
# Bug
On a date survey comporting answers, when adding new date before or between answers : date of the answers following the date added are shifted.

## Environment
- tested on 10.0.x (https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/65061-opensurvey-decalage-resultats)

- **URL(s)**: /opensurvey/results.php?ajoutsujet=.......

**Comment by jbyvosges** [comment]
Same problem for me.

**Comment by jbyvosges** [comment]
The problem persists. Apparently it has not been resolved
