### ISSUE TITLE
[BUG] files for special expenses and tax is in same directorie

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#11883]
# Bug
When uploading a file on a tax, the file is stored in documents/tax/ID_tax
When uploading a file on a social charge, the file stored in documents/tax/ID_social_charge
It's the same directorie while different numbering.

## Environment
Dolibarr v9.0.5
Php 7.2
Centos 7.5

## Steps to reproduce the behavior
For example I have a VAT payment (id 97) and I find the file of the charge that carries the same id and vice versa 

On forum : https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/65062-bug-melange-dans-les-fichiers-taxes-et-charges#115215

**Comment by eldy** [comment]
This has been fixed for 11.0.2
