### ISSUE TITLE
[Bug] Some PDF print options doesn't work for supplier orders

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11888]
# Bug
Some of the PDF options have no visible effects on the PDF generation for supplier orders

## Environment
- **Version**: 10.0.2
- **OS**: Windows NT DOLIBARR 10.0 build 17763 (Windows Server 2016) AMD64
- **Web server**: Apache/2.4.39 (Win64) PHP/7.2.18
- **PHP**: 7.2.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.14-MariaDB

## Actual behavior
1. `Hide all information related to Sales Tax / VAT` is activate the tax and VAT is shown in PDF.
2. `Hide products description` is activate the product description is shown in PDF.
3. `Add more details into footer ...` is set to `No additional details in footer` the CEO is shown in the PDF footer.

## Expected behavior
1.When `Hide all information related to Sales Tax / VAT` is activate don't show the tax and VAT in the PDF.
2. When `Hide products description` is activate don't show product description in PDF
3. When `Add more details into footer ...` is set to `No additional details in footer` don't show the CEO in the PDF footer

**Comment by ToniTen** [comment]
I had a similar issue with VAT, and part of the problem, for me, was that most documents (and the wiki page for setup/other) said the relevant configuration was MAIN_GENERATE_DOCUMENTS_WITHOUT_VAT_COLUMN but supplier order used MAIN_GENERATE_DOCUMENTS_WITHOUT_VAT. I set both and it seems to work as intended
