### ISSUE TITLE
[Request] Add ODT template support for document models in "Vendor module"

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11904]
# Feature Request
It would be nice, when you can add support for ODT templates for document models in the "Vendor module"

## Use case
Companies (and users) will use his own document style for all documents inside the company.  So they need the same style for the purchase and vendor documents.

## Suggested implementation
Add ODT template support for document models in `Vendor module` for Purchase orders,  Vendor invoices and Vendor payments

## Suggested steps
1. ODT support for document model of purchase orders
2. ODT support for document model of vendor invoices
3. ODT support for document model of vendor payments

**Comment by Tim-Otte** [comment]
#11769 should implement the first suggested step.
I think I could do the same for the other steps.
