### ISSUE TITLE
Automated compute surface and volume if not filled

### ISSUE THREAD

**Issue by lvessiller-opendsi** [Dolibarr/dolibarr#11916]
# Instructions
In product card when you modify lenght, width or heigth, it automatically calculate surface and then you will obtain weird values in surface field in this card.

# Bug
If you crate or modify a product card with length, height and length values : it automatically calculate surface value but you have not the good value.

## Environment
- **Version**: develop, Dolibarr v10
- **URL(s)**: "product/card.php"

## Steps to reproduce the behavior
Create a new product and set 
- length = 10
- width = 11
- height = 12
And validate, you will see "110 -1" in this new product card instead to have "110 m2".
You have the same thing in edition mode.

[*Files*]
![Issue-Product-Calculate-Surface](https://user-images.githubusercontent.com/45359511/65028033-a7060c00-d93b-11e9-9ab9-e118b3e4f03d.png)

# Remark
Before you have unit scale saved in database and now you have unit id

**Comment by Tim-Otte** [comment]
It seems that an attempt has been made to display the unit of the area, but an error occurs when retrieving the label, which is usually returned as -1 in Dolibarr.

**Comment by lvessiller-opendsi** [comment]
You have this problem even if you change units in edit mode. So you should have the good label with unit you selected but you have  "-1" instead of "m2".

**Comment by futurehousestore** [comment]
The same problem is with other measure units (if the products are imported from e-commerce such as prestashop)

**Comment by lvessiller-opendsi** [comment]
No it's a new product from Dolibarr (no import). You can easily reproduce this bug by creating a new product and set theeses values : 
- length = 10
- width = 11
- height =12

**Comment by laudeco** [comment]
It's because since the volume has not be filled in (manually), the volume_units is not taken into account and thus the value is _NULL_ in the DB.

The fix:
* When the computation of one field is done, make sure to persist the volume units too.
