### ISSUE TITLE
[Request] Add more filters for "Contacts/addresses" for this third-parties

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11917]
# Feature Request
Currently on the tab `Contacts/Addresses`  on a `Third-Party` the contact and addresses has only a filter for the attribute name. It would be nice when we can use/ have filter for `Job position` and `Address / Phone / Email` too. 

![Opera Momentaufnahme_2019-09-17_113022_dolibarr](https://user-images.githubusercontent.com/17874713/65029924-e3873700-d93e-11e9-90bf-7b78e7d0446e.png)

## Use case
1. User like to use more than one filter for contacts and addresses of a third-party direct in `Contacts/Addresses` tab.
2. User like to filter contacts and addresses of a third-party by `job position` direct in `Contacts/Addresses` tab.

## Suggested steps
1. Add a filter for `Job position` in the `Contacts/Addresses` tab of a third-party
2. Add a filter for `Address / Phone / Email` in the `Contacts/Addresses` tab of a third-party

**Comment by laudeco** [comment]
We can add them, but you can also go on the list of all the contacts to search about the job description / the address ;-).

Kind regards
L.

**Comment by laudeco** [comment]
Btw I'm on it. 
Since it's a new feature it will not be for the V10
