### ISSUE TITLE
Variants: Listing products very slow when hiding product variants

### ISSUE THREAD

**Issue by code-chicken** [Dolibarr/dolibarr#11928]
# Bug
Very slow display when "Hide products variant in the products selector" set to yes

## Environment
- **Version**: 9.0.4
- **OS**: Linux vm-dolibarr-test 4.19.66-gentoo #1 SMP Thu Aug 22 19:53:01 CEST 2019 x86_64
- **Web server**: nginx/1.16.1
- **PHP**: 7.3.8
- **Database**: MySQL or MariaDB 5.5.5-10.2.22-MariaDB-log
- **URL(s)**: /product/list.php?leftmenu=product&type=0

## Expected and actual behavior
Expected: Show list in the same speed as without the setting "Hide products variant in the products selector"
Actual: List of products is only shown after a very long delay (6 seconds for displaying 26 items out of a database with about 5000 items)

## Steps to reproduce the behavior
1. Change settings for **Hide products variant in the products selector** in module **Product Variants** to **yes**
2. In the Products/Services tab, click on _List_ in the left menu

## Suggested solution
Add an index for the field `fk_product_child` in the table `llx_product_attribute_combination`.
In our environment, this shortened the display duration from 6 seconds to 0.2 seconds.

**Comment by eldy** [comment]
Index has been introduced into Dolibarr v10 so i close the ticket
