### ISSUE TITLE
Keyword "To" is not included in translation catalog for mails

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#11937]
# Bug
The file core/actions_massactions.inc.php include the keyword "To" for translation. However langs/en_US/mails.lang doesn't include this keyword which is not translated.
Ex in French: 
  | Auto | Mail envoyé par xxxx To xxxx

## Environment
- **Version**: at least 8.0.3 and develop
- **URL(s)**: htdocs/compta/facture/card.php when the invoice has been sent by email and agenda module is active.

https://github.com/Dolibarr/dolibarr/blob/b30c55a2ee610bbe0176000b49ce9d10a06e6d1f/htdocs/core/actions_massactions.inc.php#L487

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/12167
