### ISSUE TITLE
Task list shows only one element

### ISSUE THREAD

**Issue by sotcet** [Dolibarr/dolibarr#11930]
# Bug
Task list shows only one element

## Environment
- **Version**: 10.0.2
- **OS**: Ubuntu
- **Web server**: Apache
- **PHP**: 7
- **Database**: MySQL
- **URL(s)**: <domain>/dolibarr/project/tasks/list.php

## Expected and actual behavior
Projects > Task Activities > List should show the list of all tasks. However, only one task is shown in the list (different ones, but always only one). At top it shows the correct number of tasks for the current filter (in parentheses), but no matter what filters it shows only one task.

## Steps to reproduce the behavior
Go to Projects > Task Activities > List. 
Error in firefox console by list.php: 

> Eine Notification-Anfrage kann nur in einem sicheren Kontext gestartet werden. (A notification request can only be started in a secure context.)

**Comment by laudeco** [comment]
Sorry I can't reproduce the issue. 
i'm on the right URL.

**Comment by atm-maxime** [comment]
As said by @laudeco , I can't reproduce either. Can you update to 10.0.4 and reopen if needed ?
