### ISSUE TITLE
Feature request : Replace img by css

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#11931]
Dolibarr uses FontAwesome (as it done for top menu icons), so insead of loading some png we can use some css instead.

# Feature Request
Replace some png icons by css

## Example

dolibarr/admin/index.php

### Html

we have :
```html
<table class="centpercent notopnoleftnoright" style="margin-bottom: 6px;">
<tbody>
 <tr>
  <td class="nobordernopadding widthpictotitle opacityhigh valignmiddle">
   <img src="/dolibarr/theme/eldy/img/title_setup.png" alt="" class="valignmiddle widthpictotitle pictotitle">
  </td>
  <td class="nobordernopadding valignmiddle">
   <div class="titre inline-block">Configuration</div>
  </td>
 </tr>
</tbody>
</table>
```
we can do:
```html
<table class="centpercent notopnoleftnoright" style="margin-bottom: 6px;">
<tbody>
 <tr>
  <td class="nobordernopadding widthpictotitle opacityhigh valignmiddle">
   <i class="fas fa-tools fa-2x"></i>
  </td>
  <td class="nobordernopadding valignmiddle">
   <div class="titre inline-block">Configuration</div>
  </td>
 </tr>
</tbody>
</table>
```

### Screenshots
we have :
![png](https://user-images.githubusercontent.com/24292300/65227652-52909700-dac9-11e9-8f22-5b43ab4abcfb.png "sceenshot with png")

we can do:
![css](https://user-images.githubusercontent.com/24292300/65227668-5d4b2c00-dac9-11e9-90b1-194382d3f9d4.png "sceenshot with css")

Tks for reading

**Comment by aspangaro** [comment]
#11963 Not so easy but done

**Comment by dolibarr95** [comment]
tks a lot !!!!!

**Comment by dolibarr95** [comment]
I wait for the merge then I will add :
```php
elseif ($pictowithoutext == 'title_home') {
    $fakey = 'fa-home';
    $fasize = '2.4em';
 }
```
