### ISSUE TITLE
Bug: error message when deleting/updating a link in salary card

### ISSUE THREAD

**Issue by toufikoj** [Dolibarr/dolibarr#11946]
# Bug
After creating a link in salary card, I have a popup error message when deleting/updating the link. Message : Cannot delete link "xxx".

## Environment
- **Version**: 10.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.30
- **URL**: /compta/salaries/card.php?id=65

**Comment by laudeco** [comment]
There is no links on the v10.0.2 on the salary card. What do you mean by "links" ?
