### ISSUE TITLE
Member subscription ERROR; Unknown column 'd.ref' in 'field list'

### ISSUE THREAD

**Issue by aymangabir** [Dolibarr/dolibarr#11940]
# Bug
To add a subscription to a member, once you tab the the subscription an error page shows up;
Xdebug: user triggered in D:\wamp64\www\dolibarr_100\htdocs\core\lib\functions.lib.php on line 3823

Dolibarr: 10.0.2
Level of features: 0
PHP: 7.1.29
Server: Apache/2.4.39 (Win64) PHP/7.1.29
OS: Windows NT AGF-PC 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) AMD64
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

Requested URL: /dolibarr_100/custom/adherentsplus/subscription.php?rowid=2
Referer: http://localhost/dolibarr_100/adherents/card.php?rowid=2&save_lastsearch_values=1
Menu manager: eldy_menu.php

Modules/Applications: user, projet, resource, categorie, fckeditor, supplier_proposal, bookmark, modulebuilder, import, export, takepos, tawkto, adherentsplus, oauth, comptabilite, hrm, expensereport, propal, notification, mailing, contrat, expedition, ficheinter, ticket, workflow, adherent, agenda, barcode, commande, don, ecm, facture, fournisseur, holiday, opensurvey, printing, salaries, societe, service, variants, website, tax, loan, banque, prelevement, margin, product, stock
Database type manager: mysqli
Latest database access request error: SELECT d.rowid, d.ref, d.ref_ext, d.civility as civility_code, d.firstname, d.lastname, d.societe as company, d.fk_soc, d.fk_parent, d.statut, d.public, d.address, d.zip, d.town, d.note_private, d.note_public, d.email, d.skype, d.twitter, d.facebook, d.linkedin, d.phone, d.phone_perso, d.phone_mobile, d.login, d.pass, d.pass_crypted, d.photo, d.fk_adherent_type, d.morphy, d.entity, d.datec as datec, d.tms as datem, d.datefin as datefin, d.datecommitment as datecommitment, d.birth as birthday, d.datevalid as datev, d.country, d.state_id, d.model_pdf, c.rowid as country_id, c.code as country_code, c.label as country, dep.nom as state, dep.code_departement as state_code, t.libelle as type, t.subscription as subscription, u.rowid as user_id, u.login as user_login FROM llx_adherent_type as t, llx_adherent as d LEFT JOIN llx_c_country as c ON d.country = c.rowid LEFT JOIN llx_c_departements as dep ON d.state_id = dep.rowid LEFT JOIN llx_user as u ON d.rowid = u.fk_member WHERE d.fk_adherent_type = t.rowid AND d.rowid=2
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'd.ref' in 'field list'

Message: Unknown column 'd.ref' in 'field list'
XDebug informations:
File: D:\wamp64\www\dolibarr_100\htdocs\custom\adherentsplus\subscription.php
Line: 0
Function: {main}

## Expected and actual behavior
[Open the subscription page of the member]

## Steps to reproduce the behavior
[click on subscrition tab within the member card]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Not sure this is a Dolibarr core issue. You seem to be using an external module called adherentplus ? You should ask the developer about this error.

**Comment by aymangabir** [comment]
Thank you, sorry for the inconvenience

**Comment by atm-maxime** [comment]
No worries, thanks for participating !
