### ISSUE TITLE
Assign a contact to several third parties

### ISSUE THREAD

**Issue by Heuser98** [Dolibarr/dolibarr#11960]
#11899 Feature Request
In the card of a third party in Dolibarr 10.0.1 it is possible to assign a contact/address for this third party. However some contacts may also be a contact in an other third party. For example, a member of a mother company may also be a member of the board of daughter companies, or a member of a governmet may have a consulting contract with a company.
So it is neccesary to assign a contact to more than one third party.

## Use case
Enter the data of a contact person.
Assign that contact to several third parties with different roles.

## Suggested implementation
Add a new table in the database to assign contacts to third parties like assigning categories to third partie.s

**Comment by nbald** [comment]
+1

**Comment by nbald** [comment]
I can pay 500eur bounty for this

**Comment by edupulpillo** [comment]
+1

**Comment by papoteur-mga** [comment]
Hello,
This is also discussed here in forum.
https://www.dolibarr.fr/forum/t/plusieurs-tiers-pour-le-meme-contact/28933
It seems that this request is frequent. It should be time to go in this way.

**Comment by mimifred** [comment]
+1

**Comment by conformist66** [comment]
+1 I'm an electrician who services multiple sites.  It's a pain for me when I have customer who has multiple sites and I need to create the same contact repeatedly.  I have the Google plugin too in Dolibarr which creates the contact for me (repeatedly) in my Google contacts.

**Comment by JSDLacoste** [comment]
+1

**Comment by ksar-ksar** [comment]
Hello,

A work around #19859

**Comment by romain-neil** [comment]
hello, I start to feel requiring this feature, any news on this ?

**Comment by edupulpillo** [comment]
It seems not yet

**Comment by whp-jeffm** [comment]
I think this would be a great feature to have! I am using dolibarr version 18.04 and I still can't figure out how to do this.

**Comment by VegeVamp** [comment]
+1

**Comment by jbergmeier** [comment]
+1

**Comment by compact729** [comment]
+1

**Comment by edupulpillo** [comment]
+1

**Comment by maxkes** [comment]
+1
