### ISSUE TITLE
Emailing no attachment sent by script command

### ISSUE THREAD

**Issue by Je2fb** [Dolibarr/dolibarr#11974]
# Bug
When you have an attachement in emailing and you want to send it throught the script command, the attachment is not sent.

## Environment
- **Version**: 10.0.2
- **OS**: Linux vps581349 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: 7.0.33-0+deb9u3
- **Database**: MariaDB 5.5.5-10.1.41-MariaDB-0+deb9u1

**Comment by laudeco** [comment]
What do you mean by 
> script command 

Cheers
L.

**Comment by eldy** [comment]
Are you speaking about the script to send mass emailing ?

**Comment by Je2fb** [comment]
Yes, the script called in command line.
