### ISSUE TITLE
[Bug] List "Oldest x not completed actions" show actions with `Not applicable`

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11973]
# Bug
The list "Oldest x not completed actions" show all actions with the `Status / Percentage` of `Not applicable` when the event is longer as one day.

![2019-09-26 13_53_20-Commercial area – Opera](https://user-images.githubusercontent.com/17874713/65766874-7b013c80-e12c-11e9-965d-5b56dbc5d149.png)

![2019-09-26 13_57_15-Agenda – Opera](https://user-images.githubusercontent.com/17874713/65766877-7e94c380-e12c-11e9-9415-a61f73a28000.png)

## Environment
- **Version**: 10.0.2
- **OS**: Windows NT DOLIBARR 10.0 build 17763 (Windows Server 2016) AMD64
- **Web server**: Apache/2.4.39 (Win64) PHP/7.2.18
- **PHP**: 7.2.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.14-MariaDB
- **URL(s)**: `http://dolibarr/dolibarr/comm/index.php?mainmenu=commercial&leftmenu=`

## Actual behavior
List "Oldest x not completed actions" show actions with the `Status / Percentage` of `Not applicable`.

## Expected behavior
List "Oldest x not completed actions" should only show actions with the `Status / Percentage` of 0 to 99 percent.

## Steps to reproduce the behavior
1. Create a event/action
2. Choose a date that is longer as one day
3. Go to page `Commercial`
4. Look at `Oldest 10 not completed actions`

**Comment by laudeco** [comment]
actually it's logical, all events with percentage between 0 and 100 are displayed + all event with an end date in the future.

Which behaviour do you expect?

L.

**Comment by ghost** [comment]
Hello,

I have expected that events/actions with the `Status/Percentage` of `Not applicable` only shown in the calendar and not in a "to-do" list.

The idea is to use events for holidays of the employees the company (longer as one day) .
So that the employees can see which employee take holidays in the next time to make correct work planing.

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by ghost** [comment]
Hello, I see no changes on this in v12
