### ISSUE TITLE
Bug Facture consolidée (plusieurs commandes)

### ISSUE THREAD

**Issue by younesnr** [Dolibarr/dolibarr#11976]
Bonjour tt le monde,

Il me parait qu'il y'a un petit bug relatif à la création de facture consolidée, càd, une facture pour plusieurs commandes en même temps (tte les commande du même tier par exemple ):
le pb c'est que je peut facturer les même commandes plusieurs fois (à chauqe fois un nouveau numéro de facture est crée).

NB: ce pb est constaté seulement si je passe par l'écran de liste de toute les commandes, puis je sélectionne les commandes à facturer (je peux refaire le process n fois sans aucun msg d'alerte). si non, si je passe par la fiche du tier, puis je clique sur le bouton 'Facturer Commandes' alors la il m'affiche un écran filtré où n'est possible de facturer que les commandes qui ne sont pas encore traité (facturée).

Tout est expliqué dans les prise d'écran attaché (elles sont ordonnées de 1 à 7 avec des commentaire dedans).

j'espère que j'étais clair, merci de votre retour.

Younes
![n1](https://user-images.githubusercontent.com/6017449/65786474-9c732000-e14e-11e9-845b-9ce34d016b0d.png)
![n2](https://user-images.githubusercontent.com/6017449/65786475-9c732000-e14e-11e9-93f5-4ccd2fa0c135.png)
![n3](https://user-images.githubusercontent.com/6017449/65786476-9c732000-e14e-11e9-966e-48e5bb72c409.png)
![n4](https://user-images.githubusercontent.com/6017449/65786477-9d0bb680-e14e-11e9-9bdf-809bc213beda.png)
![n5](https://user-images.githubusercontent.com/6017449/65786478-9d0bb680-e14e-11e9-86f7-e5f4cf0a55ff.png)
![n6](https://user-images.githubusercontent.com/6017449/65786479-9d0bb680-e14e-11e9-8dbd-94d0f4426dfb.png)
![n7](https://user-images.githubusercontent.com/6017449/65786480-9da44d00-e14e-11e9-9526-85662ff5295c.png)

**Comment by younesnr** [comment]
Hello,  any news or update ? Am I missing some thing ?

thanks in advance for your answer...

**Comment by atm-maxime** [comment]
Hi. Why would you create invoices from the order list without filtering on the "invoiced" column just to have non invoiced orders ?
And there's no problem for me to have 2 invoices linked to the same order, if the first has been cancelled by a credit note for example...

Thanks for participating in the community, please use English for further communication ;)

**Comment by dpriskorn** [comment]
Update to v12 and reopen if the problem persists.
