### ISSUE TITLE
Bug Loss of product volume units on update Dolibarr 9.0 to 10.0

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#11979]
When updating from Dolibarr 9.0 to 10.0, we lose product volume units (and may be others units).

**Comment by laudeco** [comment]
Do you still see it on the card of the product ?
![image](https://user-images.githubusercontent.com/3658458/65867611-05d57780-e377-11e9-83f4-98e176fe05b9.png)

**Comment by tuxgasy** [comment]
The volume unit is empty on the card of product. After edit and set the correct unit then I see it.

On Dolibarr 10, volume units are now linked to a dictionary.

**Comment by laudeco** [comment]
I confirm the issue, I'm investigating it and try to find one fix.

**Comment by tuxgasy** [comment]
Since Dolibarr 10, volume units use dictionary units. But old data is not migrated.

**Comment by eldy** [comment]
It should be fixed in 10.0 branch.
Need to wait 10.0.3 to get fixes.

**Comment by eldy** [comment]
v10.0.3 has been released
