### ISSUE TITLE
Allow 0 as amount of VAT declaration [10.x.x] >

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#11983]
# Feature Request
Allow 0 as amount of VAT declaration

## Use case
Implement this fonctionnality will allow users to store PDF proof of declaration as attached file;
including when the amount to pay is 0 (or negative but not recovered -> reported in next declaration without treatment in dolibarr)

## Suggested implementation
create an hidden parameter to allow that.

example for 10.0.2 :
in \compta\tva\card.php
replace line 116
if (empty($object->amount))
by
if (empty($object->amount) && empty($conf->global->MAIN_ALLOW_ZERO_VAT_IN_DECLARATION))

or something like that...

**Comment by AlainG95** [comment]
Please take care this option is available without modification for the VAT but not yet for company tax amount.
Thanks
