### ISSUE TITLE
Bug Units scale is never loaded

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#11980]
It's fixed in dev branch but it should be fixed also in version 10.0

See PR #11531

**Comment by tuxgasy** [comment]
@eldy I do a PR if need.

**Comment by laudeco** [comment]
So this is fixed right ?

**Comment by tuxgasy** [comment]
Yes but it's fixed only in dev branch but not in version 10.0. Why close this issue ?

**Comment by laudeco** [comment]
Ok sorry! 
We should always fix in the earliest version with the bug and not in the dev branch.

**Comment by eldy** [comment]
Done into 10.0 too now
