### ISSUE TITLE
FIX : rester en mode rapprochement lors du choix d'une limite de page personnalisée

### ISSUE THREAD

**Issue by clCglAvt** [Dolibarr/dolibarr#11985]
Sujet
rester en mode rapprochement lors du choix d'une limite de page personnalisée
Détail
Quand je change le nombre de lignes dans la page, l'écran affiché n'est plus en mode 'rapprochement
Correction
voir le fichier bankentries_list.php possédant les correction sur un V10.0.1
[bankentries_list.zip](https://github.com/Dolibarr/dolibarr/files/3667351/bankentries_list.zip)
Environnement
Dolibar V10.0.1

Windows 10
Appache 2.4.9 et Mysql 5.0.45

**Comment by laudeco** [comment]
Hello @clCglAvt  
I cannot reproduce that issue, when I change the number of elements on the page I remain on the "rapprochement" view. Could you give more details or I'll close that issue

Thanks

Cheers
L.

PS: Since Dolibarr is international please post your message in English

**Comment by dpriskorn** [comment]
No further details given. Closing. Feel free to reopen with details.
