### ISSUE TITLE
Holidays module needs php-calendar but doesn't check that the server has it

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#11989]
#Bug
Asking for holiday more than one day gives a blank page.
In PHP logs, I get:
[php:error] [pid 10098] [client 127.0.0.1:41200] PHP Fatal error:  Uncaught Error: Call to undefined function easter_date() in /var/www/html/dolibarr-test/htdocs/core/lib/date.lib.php:663\nStack trace:\n#0 /var/www/html/dolibarr-test/htdocs/core/lib/date.lib.php(946): num_public_holiday(1569801600, 1569974400, 'FR', 1)\n#1 /var/www/html/dolibarr-test/htdocs/holiday/card.php(301): num_open_day(1569801600, 1569974400, 0, 1, 0)\n#2 {main}\n  thrown in /var/www/html/dolibarr-test/htdocs/core/lib/date.lib.php on line 663, referer: http://localhost/dolibarr-test/htdocs/holiday/card.php?id=1&action=edit&error=datefin

## Environment
- **Version**: v10.0.0
- **Web server**: Apache
- **PHP**: 7.3
- **URL(s)**: /htdocs/holiday/card.php?id=1&action=edit&error=datefin

**Comment by ksar-ksar** [comment]
Hello,

You have one missing library in your php installation : php-calendar

Run a `sudo apt-get install php-calendar`

**Comment by papoteur-mga** [comment]
@ksar-ksar You're right.
But in this case, either installation or module activation has to check that php-calendar is enabled.
Common user has just a blank page to diagnose that the installation missed a module.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/11996

**Comment by papoteur-mga** [comment]
Thanks Frédéric.
When this check occurs? At installation?

**Comment by frederic34** [comment]
Yes at install, it's just information
