### ISSUE TITLE
Add company address to PDF footers

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12006]
# Feature Request
The company's registered office address on PDF footers (enabled via /admin/pdf.php ) does not include the country for the company. Please add it after the city name

## Use case
In my use case, we do not include the company info on the PDF header, and instead rely on the footer for this. Not having the country listed there makes it considerably harder to conduct international trade.

## Suggested implementation
Modify /htdocs/core/lib/pdf.lib.php to change the function pdf_pagefoot to also include the country when $showdetails==1 or $showdetails==3

**Comment by laudeco** [comment]
The PR is there ;-) thanks for the suggestion.
