### ISSUE TITLE
Bug: Forgotten "," before FROM in sql request " SELECT e.rowid, e.ref, e.statut, e.lieu, e.address, e.zip, e.town, e.fk_pays, e.fk_parent, SUM(p.pmp * ps.reel) as estimatedvalue, SUM(p.price * ps.reel) as sellvalue, SUM(ps.reel) as stockqty**,** FROM llx_entrepot "

### ISSUE THREAD

**Issue by karouani** [Dolibarr/dolibarr#12008]
# Bug
Forgotten "," before FROM in sql request " SELECT e.rowid, e.ref, e.statut, e.lieu, e.address, e.zip, e.town, e.fk_pays, e.fk_parent, SUM(p.pmp * ps.reel) as estimatedvalue, SUM(p.price * ps.reel) as sellvalue, SUM(ps.reel) as stockqty**,** FROM llx_entrepot "

## Environment
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20191001150152
Dolibarr: 11.0.0-alpha
Niveau de fonctionnalités: 0
PHP: 7.3.9
Server: LiteSpeed
OS: Linux serveur90.heberjahiz.com 3.10.0-962.3.2.lve1.5.26.3.el7.x86_64 #1 SMP Wed Aug 14 08:29:59 EDT 2019 x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0

Url sollicitée: /product/stock/list.php?leftmenu=
Referer: http://xxxxxxx/product/index.php?mainmenu=products&leftmenu=
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, gourma, expensereport, banque, product, stock, facture, fournisseur, salaries, societe, variants, margin, debugbar, bookmark, resource, categorie
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT e.rowid, e.ref, e.statut, e.lieu, e.address, e.zip, e.town, e.fk_pays, e.fk_parent, SUM(p.pmp * ps.reel) as estimatedvalue, SUM(p.price * ps.reel) as sellvalue, SUM(ps.reel) as stockqty, FROM llx_entrepot as e LEFT JOIN gourma_product_stock as ps ON e.rowid = ps.fk_entrepot LEFT JOIN llx_product as p ON ps.fk_product = p.rowid WHERE e.entity IN (1) GROUP BY e.rowid, e.ref, e.statut, e.lieu, e.address, e.zip, e.town, e.fk_pays, e.fk_parent ORDER BY e.ref ASC LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM gourma_entrepot as e LEFT JOIN gourma_product_stock as ps ON e.rowid = ps.f' at line 1

## Steps to reproduce the behavior
Add after line 115 : $sql=preg_replace('/, $/', '', $sql);
$sql=substr($sql, 0, -1);

**Comment by maitrepylos** [comment]
Bonjour, il y a une virgule entre le dernier attribut et le from 
` as stockqty, FROM`

**Comment by karouani** [comment]
oui je sais juste vous informer pour la corriger dans la version 11

**Comment by laudeco** [comment]
The fix is there ;-)

**Comment by laudeco** [comment]
Fix in the pr #12022
