### ISSUE TITLE
[Request] Show product count of product categories

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#12019]
# Feature Request
Hello, I would be helpfully when we can see the count of products in the category view of a product category and the product category overview.

## Use case
A user need a short overview of the count of products of one or more product categories.

## Suggested implementation

**In the product category overview**

![2019-10-02 15_07_19-Products_Services tags_categories area – Opera](https://user-images.githubusercontent.com/17874713/66047068-61466780-e527-11e9-8b4b-4b211b4cb6b8.png)

**In the product category**

![2019-10-02 15_07_42-Tags_categories – Opera](https://user-images.githubusercontent.com/17874713/66047062-5ee40d80-e527-11e9-8226-5b8005c26a60.png)

**Comment by laudeco** [comment]
We can do that but it slows down the query. So I propose to enable that based on a config on the module.

What do you think ? is it acceptable for you?

**Comment by ghost** [comment]
@laudeco 
Hello,

Yes, that would be quite enough. 👍

**Comment by ghost** [comment]
Added with #13009
