### ISSUE TITLE
Dear developer community

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#12028]
Dear contributors, maintainers, and others involved,

I really like dolibarr and also its legacy codebase. I am from the WordPress world so I know what long backwards compatibility means.
But I also know what can help bring contributors together.

It seems there are discussions here in the issues that take up much time and could be handled far easier in a chat room.

I just tried to find out if `dolibarr.slack.com` was available and accidentally registered it. So if one/some of the maintainers of the project is open to the idea of a (official) slack for developers of dolibarr, I am happy to sign over the slack team `dolibarr`.

I will also look into providing the self-service registration to make the team "public" for everyone.

Cheers,
Chris

@changeplaces @eldy @laudeco

**Comment by laudeco** [comment]
You have to invite us independently because we have to have an account.
It's an awesome idea btw!

**Comment by cfoellmann** [comment]
there are some solutions to make it public.
Simply put: You have to set up a very simple web app to provide a form. You put in your email and you get an invite mail for the dolibarr slack

https://join.slack.com/t/dolibarr/shared_invite/enQtNzY5NTg2MTk4NjQyLWZlOThmMzUyMzc2NzI0MTk0MTIxYjBhYTI0YTBjYjZiZDZhMzBhMGMxZGQ2MWI5NDZmZTE5MDM2OGE1M2U3NWM is only valid for 30 days

**Comment by laudeco** [comment]
didn't know :D we cannot know everything on the internet ;-)

**Comment by laudeco** [comment]
Didn't we have an IRC for developers? I cannot remember now.
Anyway, since it's a good idea maybe you can post it to the dev mailing list.

**Comment by cfoellmann** [comment]
@laudeco I would like this to be adopted officially.
So I hope to get some reaction from a maintainer.

**Comment by laudeco** [comment]
then it's only @eldy because I don't think I have the required level ;-)

**Comment by ChangePlaces** [comment]
I've moved on to bigger and better things. I noticed in my thread asking about change, the core developer showed up after I said I was done, (avoiding all discussion about improving dolibarr) and gave a sob story. 

Dolibarr needs completely rewriting with a better core team to allow others to take it forwards, not give excuses why it shouldn't. 

Honestly, I probably wouldn't even bother forking it.

**Comment by cfoellmann** [comment]
@ChangePlaces I can understand you.
If you have found a good fit that is great.

**Comment by cfoellmann** [comment]
Ping @com4WEB

**Comment by eldy** [comment]
The dolibarr foundation has the idea to abandon the mailing-list since a long time.
May be slack may be a solution to replace this.
Well, we can have a try on it. Can you move property of dolibarr.slack.com to the Dolibarr foundation team :  contact@dolibarr.org ? This is not the code development team that manage the tools around dolibarr, but the dolibarr foundation.

**Comment by eldy** [comment]
> I've moved on to bigger and better things. I noticed in my thread asking about change, the core developer showed up after I said I was done, (avoiding all discussion about improving dolibarr) ...

Can you mention the issue number of this chat ?

**Comment by cfoellmann** [comment]
@eldy you need to register via the link above and the mentioned email.
I can only transfer ownership to existing members

**Comment by eldy** [comment]
@cfoellmann And to be an existing members, we need to be invited. Can your send invitation to 
contact@dolibarr.org ?

**Comment by cfoellmann** [comment]
The link above would have had the same effect but the invite mail is out

**Comment by eldy** [comment]
contact@dolibarr.org is now a member.

**Comment by cfoellmann** [comment]
the slack is transfered. The dolibarr assoc. is the primary owner now.
You have to check https://dolibarr.slack.com/admin to demote me further. But I am offering to help administer the slack if you like

**Comment by ksar-ksar** [comment]
Hi @eldy 

Do you recommend to use slack ?
Can we make announcement on forums, make a news on dolibarr.org and put it on the Wiki ?

Thanks.

**Comment by dolibit-ut** [comment]
Zulip is a similar and very nice open-source alternative. Maybe we take a look on this.
