### ISSUE TITLE
Create ticket not possible since 10.0.2

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#12043]
# Bug
Read, update and delete a ticket are working fine. However, create a new ticket does not work on 10.2. Click on create a new ticket (following the link below)  

.../dolibarr/htdocs/ticket/new.php?action=create_ticket&idmenu=59&mainmenu=ticket&leftmenu=

Display a white screen, no error message.

## Environment
- **Version**: 10.0.2
- **OS**: Debian
- **URL(s)**: .../dolibarr/htdocs/ticket/new.php?action=create_ticket&idmenu=59&mainmenu=ticket&leftmenu=

## Steps to reproduce the behavior
Click create new ticket

**Comment by ksar-ksar** [comment]
Hi,

htdocs/ticket/new.php doesn't exist in 10.0.2
See : https://github.com/Dolibarr/dolibarr/tree/10.0/htdocs/ticket

It's a old file.

Normaly to create a new ticket you should go to : /ticket/card.php?action=create

**Comment by eldy** [comment]
Try to disable module ticket and enable module again. This may clean your old menu entries.
