### ISSUE TITLE
Replenishment ignores vendor descriptions

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12044]
# Bug
If you enable "Add a feature to define the descriptions of products defined by the vendors in addition to descriptions for customers" in /product/admin/product.php. This information is automatically added on purchase orders when adding the lines. However, if the lines are added by the replenishment process, customer description is used instead.

## Environment
- **Version**: 9.0.4 (this issue is also present in 10.0.2)
- **OS**: Ubuntu 18.04
- **Web server**: Apache/2.4.29 (Ubuntu) 
- **PHP**: 7.2.19-0ubuntu0.18.04.2
- **Database**: 5.5.5-10.1.41-MariaDB-0ubuntu0.18.04.1
- **URL(s)**: /product/admin/product.php; /product/stock/replenish.php

## Expected and actual behavior
If you enable "Add a feature to define the descriptions of products defined by the vendors in addition to descriptions for customers" in /product/admin/product.php, you can define a per vendor description for each product at /product/fournisseurs.php. This information is automatically added on purchase orders when adding the lines. However, if the lines are added by the replenishment process, customer description is used instead. It should use the vendor description instead

We use this feature because we need to provide suppliers with information that is not relevant on customer orders, or in a different format to what customers expect. Also, different vendors use different names for the same product, and we include this information here.

## Steps to reproduce the behavior
- Enable "Add a feature to define the descriptions of products defined by the vendors in addition to descriptions for customers" in /product/admin/product.php
- Create a product that is both sold and purchased. Make sure you have a default warehouse, and that there is a "Stock limit for alert" and a "Desired Stock"
- Add a description to the product on the product's main card
- Go to Buying Prices, and click on "Add buying price". Fill all the required data
- Also fill "Vendor description for the product" and save.
- Use the replenishment feature to create an order for the product.
- Observe that the line has the description from the main product card and not the per vendor description.

**Comment by atm-maxime** [comment]
Hi ! Thanks for your contribution and this detailed issue. I fixed it, waiting to be merged.
Cheers
