### ISSUE TITLE
Missing translation : ClassifyReception

### ISSUE THREAD

**Issue by actarus314** [Dolibarr/dolibarr#12055]
# Bug
Missing translation (at least into French) for the key "ClassifyReception" in the supplier order management.

## Environment
- **Version**: 10.0.2
- **URL(s)**: https://ndm.tld/fourn/commande/card.php?id=xxx

## Attached files
![image](https://user-images.githubusercontent.com/54531618/66308362-413bed00-e907-11e9-9e35-2bc3b82d23c6.png)

**Comment by frederic34** [comment]
string has been added, you have to wait a transifex sync
https://github.com/Dolibarr/dolibarr/commit/04adbd8c80d8bd532a76e942dc4358b2acc17d57
