### ISSUE TITLE
[Request] Add create third party button on new ticket page

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#12082]
# Feature Request
Add a `create third party` button to the new ticket page.

`http://dolibarr/dolibarr/ticket/card.php?action=create&idmenu=102&mainmenu=ticket&leftmenu=`

## Use case
User want to easy added a missing third party when they create a new ticket.

## Suggested implementation
![2019-10-10 09_11_10-Create ticket – Opera](https://user-images.githubusercontent.com/17874713/66547168-ee4c7a80-eb3e-11e9-9a1f-236c1c173995.png)

**Comment by arthurmod** [comment]
Still no button for add third party
