### ISSUE TITLE
Add hook "printFieldFrom" for additionnal JOIN 

### ISSUE THREAD

**Issue by Bruce77** [Dolibarr/dolibarr#12087]
### Feature Request
This hook should be implemented on all lists (list.php) for add LEFT_JOIN

### Use case
Developper can use this hook into her modules

### Suggested implementation
Add this
$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldListFrom',$parameters);    // Note that $action and $object may have been modified by hook
$sql.=$hookmanager->resPrint;
Before this
$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldListSelect',$parameters);    // Note that $action and $object may have been modified by hook
$sql.=$hookmanager->resPrint;

**Comment by llimz** [comment]
+1

I need it too to add a LEFT JOIN into the products list.
