### ISSUE TITLE
Unable to use AUTH PLAIN (and other) for smtp

### ISSUE THREAD

**Issue by Shnoulle** [Dolibarr/dolibarr#12098]
# Bug
Usage of smtp server is restricted to AUTH LOGIN.

## Environment
- **Version**: 10.0.1 (tested) but [current develop](https://github.com/Dolibarr/dolibarr/blob/c21224ef96932cd86a3fdcbd70800b25749c19b8/htdocs/core/class/smtps.class.php#L501) seems to have same issue.
- **OS**: Debian9 
- **Web server**: apache (not relevant)
- **PHP**: not relevant
- **Database**: not relevant
- **URL(s)**: none ? `/admin/mails.php`

## Expected and actual behavior

Using any smtp server can be allowed, SMTP protocol have way to get the allowed authentification method. 

A lot can be accepted CRAM-MD5, LOGIN, … even none (AUTH by IP)

## Steps to reproduce the behavior
Get a smtp server with PLAIN or CRAM-MD5 login and try to use it (i can offer dev account for PLAIN)

## Related project (FLOSS code).
https://github.com/PHPMailer/PHPMailer/blob/63344e6baa12f4f91c8f228fc4d0cb3366e53834/src/SMTP.php#L469

**Comment by Shnoulle** [comment]
I can make a pull request for AUTH PLAIN (or AUTH LOGIN) but need to know if it's a bug or a feature ? (can make for CRAM-MD5 too, but can not check)
Same fix can be done for develop and older version. I use an hacked 10 version to fix it.

:)

**Comment by eldy** [comment]
Nor a bug nor a feature : 
Just that nobody has submitted any PR to support this. Your PR is welcome (preferred on develop branch).

**Comment by Shnoulle** [comment]
OK , develop branch => feature :) 

I setup develop to test :)

**Comment by Shnoulle** [comment]
https://github.com/Dolibarr/dolibarr/pull/12175
