### ISSUE TITLE
Bug: can't remove contacts within contacts/addresse tab of proposal

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#12108]
# Bug
No more trash can

## Environment
- **Version**: 11.0.0-alpha
- **OS**: Windows NT
- **Web server**: Apache/2.4.39 (Win64) PHP/7.1.29
- **PHP**: apache2handler 7.1.29
- **Database**: MySQL or MariaDB 5.7.26
- **URL(s)**: /dolibarr_dev/comm/propal/contact.php?id=3

**Comment by frederic34** [comment]
@grandoc you don't have unlink button?
![Sélection_019](https://user-images.githubusercontent.com/3624836/66716767-f40dbe80-edd1-11e9-8f99-89982433331b.png)

**Comment by grandoc** [comment]
Yes that's the point

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last version of code, so I close the issue.
