### ISSUE TITLE
[BUG] Dashboard - Ticket creation time is +4 hours.

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#12114]
# Bug
The creation time of a tickets is shown with +4 hours on the dashboard.
Affected widgets `Latest 5 created tickets` and `Latest 5 modified tickets`.
(testet with English and German language setting)

**Ticket card**

![2019-10-14 08_07_29-Ticket card – Opera](https://user-images.githubusercontent.com/17874713/66732033-8eb1e000-ee5a-11e9-8483-d3418089cd80.png)

**Dashboard**

![2019-10-14 08_10_17-Home - Dolibarr 10 0 2 – Opera](https://user-images.githubusercontent.com/17874713/66732056-a8ebbe00-ee5a-11e9-9874-ebbccbe6540d.png)

## Environment
- **Version**: 10.0.2
- **OS**: Windows NT DOLIBARR 10.0 build 17763 (Windows Server 2016) AMD64
- **Web server**: Apache/2.4.39 (Win64) PHP/7.2.18
- **PHP**: 7.2.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.14-MariaDB
- **URL(s)**: `http://dolibarr/dolibarr/index.php?mainmenu=home&leftmenu=home`

![2019-10-14 08_17_16-About Dolibarr – Opera](https://user-images.githubusercontent.com/17874713/66732187-20b9e880-ee5b-11e9-9174-a4de16d1c9f7.png)

## Actual behavior
The creation time of a tickets is shown with +4 hours on the dashboard.

## Expected behavior
Show correct creation time of a ticket on the dashboard widgets.

## Steps to reproduce the behavior
1. Create a new ticket
2. Go to dashboard
3. Compare the time stamp

**Comment by eldy** [comment]
Did you create the ticket from the public interface ?

**Comment by ghost** [comment]
@eldy 

Hello,

No, the public interface is deactivated and the ticket was created from the internal page.

**Comment by eldy** [comment]
Can you give:
- value of php timezone
- server timezone
- borwser timezone
you have ?

**Comment by ghost** [comment]
Hello,

since the daylight saving time change, the gap between the times are only +2 hours (from +4).

PHP: de-DE, Europe/Berlin, Version 7.2.18
Server: de-DE, Europe/Berlin, Windows Server 2019
Browser: de-DE, (should be Europe/Berlin from OS Windows 10)
Dolibar: most in de-DE, Europe/Berlin via MAIN_SERVER_TZ

**Admin Tools -> About Dolibarr -> Localization parameters**

![Opera Momentaufnahme_2019-11-12_080628_dolibarr](https://user-images.githubusercontent.com/17874713/68650168-97163d00-0524-11ea-9483-a1f32ed8d7eb.png)

**Admin Tools -> About PHP -> date**

![2019-11-12 08_18_58-Dolibarr – Opera](https://user-images.githubusercontent.com/17874713/68650423-46ebaa80-0525-11ea-8aa7-390e763e0835.png)
