### ISSUE TITLE
Add units fields to product export

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#12152]
# Bug
Missing units fields in product export while we can import them.

## Environment
- **Version**: 10
- **OS**: Debian 9
- **Web server**: Apache2
- **PHP**: PHP 7
- **Database**: Mariadb 10
- **URL(s)**: /exports/export.php

**Comment by eldy** [comment]
Will be available with v11

**Comment by atm-maxime** [comment]
I think the units translations are missing
