### ISSUE TITLE
TakePOS: Customer relative discount not taken into account when adding a product

### ISSUE THREAD

**Issue by Toge-lab** [Dolibarr/dolibarr#12170]
When adding a new product line in TakePOS, the relative discount of the selected customer is not taken as discount and the discount in the line stays by default at 0.

To change this, I have replaced the following line in the file 

> \takepos\invoice.php 
after `if ($action == "addline")`

```
$idoflineadded = $invoice->addline($prod->description, $price, 1, $tva_tx, $prod->localtax1_tx, $prod->localtax2_tx, $idproduct, $prod->remise_percent, '', 0, 0, 0, '', $price_base_type, $price_ttc, $prod->type, -1, 0, '', 0, 0, null, 0, '', 0, 100, '', null, 0);`
```
by

```
$customer = new Societe($db);
$customer->fetch($invoice->socid); // to replace $prod->remise_percent in the next line by $customer->remise_percent
$idoflineadded = $invoice->addline($prod->description, $price, 1, $tva_tx, $prod->localtax1_tx, $prod->localtax2_tx, $idproduct, $customer->remise_percent, '', 0, 0, 0, '', $price_base_type, $price_ttc, $prod->type, -1, 0, '', 0, 0, null, 0, '', 0, 100, '', null, 0);
```
To be honnest, I'm not sure that a better solution would not be to take the selected customer into account when calling the product class but I don't know directly if it's possible.

**Comment by andreubisquerra** [comment]
@Togeole,  you are absolutely right
Solved with https://github.com/Dolibarr/dolibarr/pull/12278

**Comment by Toge-lab** [comment]
Perfect, thansk a lot :)
