### ISSUE TITLE
Mail notification for new ticket

### ISSUE THREAD

**Issue by Nicofol** [Dolibarr/dolibarr#12182]
In Dolibarr 10.0.2, when a user opens a new ticket from the public interface or the administrator assigns a new ticket to an agent, the notification of mail sent by the system contains only the trackID and not the ticket number. It would be clearer if there was also the ticket number in the mail.

**Comment by scarcamo-eyg** [comment]
Solve in 10.0.6 or 11 version I think
Trying new releases I've seen that working pretty well.
Regards.

**Comment by Nicofol** [comment]
I've tried in 11 version and only the trackID will appear in the mail message. Can you share more infos pls?
