### ISSUE TITLE
Products with desactivated sales are always selectable in customer documents

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#12184]
# Bug
On the customer documents (proposals, order or invoices) you can select all products whatever they are enabled for sale or not.

## Environment
- **Version**: 10.0.2

## Expected and actual behavior
In previous releases, when a product was disabled for sale, it disappeared from the select list in client documents. to avoid the sale of an obsolete product.
In Dolibarr 10.0.2 all products are shown, even those that are disabled for sale !

## Explanations found
file "../htdocs/core/tpl/objectline_create.tpl.pp" lines 254 and 258 :
`...$buyer->price_level, -1, 2,...` should be `...$buyer->price_level, 1, 2,...`

Greetings,
Sylvain Legrand.

**Comment by atm-maxime** [comment]
Hi. I guess it has already been seen and fixed #12088. Can you check ?

**Comment by SylvainLegrand** [comment]
Hi,
You're right.

Greetings
Sylvain Legrand.
