### ISSUE TITLE
Implement returns from customer or to vendor

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12200]
# Feature Request
Implement a workflow for both customer returns, and returns to vendor

## Use case
Currently Dolibarr has no way to track customer returns to the company nor returns to vendor. For customer returns, you can correct stock and create a credit note, but for returns to vendor, there's no way to create a delivery note to send with the goods.

## Suggested implementation

1. Customer returns
  - Add a button on both the shipment card and the order card, for process returns
  - A customer return is like a customer shipment but in the other direction, it could be just a customer shipment with a different numbering pattern and negative quantities
 - Add a checkbox on the validate return process in case you want to reduce the order quantity (depending on if the customer wants a refund or a replacement)

2. Returns to vendor
 - Add a button to both vendor order and vendor receptions, for process returns
 - A return to vendor is like a vendor reception, but in the other direction. It could be implemented as simply a vendor reception with negative quantities. Print documents should display positive quantities though, but that could be handled in the code that produces the PDF/ODT
 - Add a check box on the validate return process in case you want to reduce the order quantity (depending on if the vendor will offer a refund or a replacement)

**Comment by dolibarr95** [comment]
Hi!
Could be the same request I think.
#8797

**Comment by alibler** [comment]
We hope that the official can provide this function. No system lacks such an important function. Why haven't added this function for so many years? The return module that needs to be paid separately is too low-end to meet the normal business needs!!!

**Comment by alibler** [comment]
It's a similar request, but why hasn't dolibarr officially provided this basic function for so many years? Axel dev development of the return module is very simple! His return module doesn't have the function of tracking the order in the regular ERP system at all.

How do you realize the process management of sales return or purchase return?

**Comment by dolibarr95** [comment]
Hello
We do it manually (stock movement, contact the supplier etc)

**Comment by alibler** [comment]
It’s really not a good idea, manual operation will not be able to record related processes in the system.

**Comment by dolibarr95** [comment]
Hello
I know that's not a good idea but while waiting for this function i have to do some tricks.

**Comment by aljawaid** [comment]
Dolistore alternative: https://github.com/Dolibarr/dolibarr/issues/16491#issuecomment-953632888

**Comment by YannisWell** [comment]
Regarding the issue of sales returns and procurement returns, this problem has been ongoing for six years since its submission and the core functional requirement remains unresolved. Dear official engineers, when can we expect this issue to be addressed?
https://github.com/Dolibarr/dolibarr/issues/16491
