### ISSUE TITLE
BUG: Incorrect rounding type (Purchase Order -> Supplier Invoice)

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#12248]
# Bug
When creating a Vendor Invoice from Purchase Order in foreign currency the product price is incorrectly recalculated. Recalculation is done after price rounding. 

In my case in product Buying Prices tab
Product A has a **Price (Currency) For This Qty. (No Discount)** price of 4.40 and the **Currency Conversion Rate** equals 4.8 so the **Price Quantity Minimum** is 0.9166666666666667

## Environment
- **Version**: 10.0.3
- **OS**: Linux server2.turro.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.2.27-MariaDB
- **URL(s)**: /htdocs/fourn/facture/card.php

## Expected and actual behavior
Actual behaviour: 0.92x4.8=4.42
Expected behaviour: 0.9166666666666667x4.8=4.40

## Steps to reproduce the behavior
Create Purchase Order (In Vendor's Currency) then create an Invoice from that Purchase order.

**Comment by futurehousestore** [comment]
![1](https://user-images.githubusercontent.com/28427270/69440579-00762700-0d41-11ea-85fe-db80d1dcceeb.JPG)
![2](https://user-images.githubusercontent.com/28427270/69440583-02d88100-0d41-11ea-85c1-e9dec6dae405.JPG)

**Comment by futurehousestore** [comment]
Still exist in version 11.0.0

**Comment by futurehousestore** [comment]
Related to #13128

**Comment by futurehousestore** [comment]
Same issue after upgrade to version 13.0.0

**Comment by ksar-ksar** [comment]
Hello,

What is your setup of "Limits and accuracy" ?

**Comment by futurehousestore** [comment]
Hi @ksar-ksar,
That's my setup but I think the bug is fixed in v. 13.0.1 but I'll be able to test it properly next week ![limits](https://user-images.githubusercontent.com/28427270/109354204-5b1bfe00-7875-11eb-9b87-a6c30a6c19d8.PNG)
