### ISSUE TITLE
Impossible to remove a client from a tag/categorie 

### ISSUE THREAD

**Issue by NicolasDEVOUGE** [Dolibarr/dolibarr#12266]
# Bug
Hello, we have a problem with deleting tags from societe , We got the error described below.

## Environment
- **Version**: 10.0.2
- **OS**: Ubuntu server 18.04
- **Web server**: Apache/2.4.38
- **PHP**: 7.2.24-0ubuntu0.19.04.1
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-1~xenial
- **URL(s)**: /categories/viewcat.php?id=794&type=&removeelem=50095

## Expected and actual behavior
Error from Dolibarr :

> Dolibarr a détecté une erreur technique.
> Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
> Date: 20191030141503
> Dolibarr: 10.0.2
> Niveau de fonctionnalités: 0
> PHP: 7.2.24-0ubuntu0.19.04.1
> Server: Apache/2.4.38 (Ubuntu)
> OS: Linux dolibarr 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64
> UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.107
> 
> Url sollicitée: /categories/viewcat.php?id=794&type=&removeelem=50095
> Referer: https://facturation.esrv.fr/categories/viewcat.php?id=794&type=2
> Gestionnaire de menu: eldy_menu.php
> 
> Modules/Applications: user, maintenance, smsdecanet, expensereport, notification, ldap, api, mycyberoffice, externsite, webservices, sav, product, banque, propal, cyberoffice, contrat, ficheinter, fckeditor, econcept, externalsite, stock, expedition, categorie, productbatch, resource, mydoli, agenda, comptabilite, barcode, commande, ecm, facture, fournisseur, holiday, opensurvey, printing, salaries, societe, service, gravatar, bookmark, clicktodial, ticket, projet, import, export, tax, prelevement, margin

Error from log : 
```

Interfaces::run_triggers action=CATEGORY_UNLINK Files found: 13, Files launched: 7, Done: 0, Failed:
1 - Nb of error string returned in this->errors = 0
```

## Steps to reproduce the behavior
Delete TAG from client card, or edit tag and delete client from tag card

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/3789104/dolibarr.log)

**Comment by eldy** [comment]
Do you have module mailmanspip enabled ?
