### ISSUE TITLE
When creating invoice, TakePos doesn't take into account buying price, cost price or PMP for margins.

### ISSUE THREAD

**Issue by iaoranamoa** [Dolibarr/dolibarr#12315]
Version Dolibarr 10.1
When using TakePos it makes a ticket for the customer and creates **an invoice** for records and accounting.
When you have set up the margins module, it is because you want to use it.

TakePos is getting data from product but is not getting the buying price or Cost price or PMP to fill the invoice which is used by dolibarr to calculate the margins.

\takepos\invoice.php Line 100 : $invoice->addline($prod->description, $prod->price, 1, $prod->tva_tx, $prod->localtax1_tx, $prod->localtax2_tx, $idproduct, $prod->remise_percent, '', 0, 0, 0, '', $prod->price_base_type, $prod->price_ttc, $prod->type, - 1, 0, '', 0, 0, null, 0, '', 0, 100, '', null, 0)

It works when you use the normal invoice function.

I'm not good enough in coding to pull a request.

Regards

**Comment by cistelsa** [comment]
you must enter the file \ takepos \ invoice.php inside the if "if ($ action ==" addline ")
{"
this code

`$sql1="SELECT price FROM ".MAIN_DB_PREFIX."product_fournisseur_price WHERE fk_product='$idproduct'";
    $preciocompra = $db->query($sql1);
    $row1 = $db->fetch_array ($preciocompra);
    $resultado=$row1[0];`

Then look for this code and enter $resultado in replacement of one of the zeros.
`$invoice->addline($prod->description, $price, 1, $tva_tx, $prod->localtax1_tx, $prod->localtax2_tx, $idproduct, $prod->remise_percent, '', 0, 0, 0, '', $price_base_type, $price_ttc, $prod->type, -1, 0, '', 0, 0, null, $resultado, '', 0, 100, '', null, 0);
    $invoice->fetch($placeid);`

**Comment by sarksloane** [comment]
@cistelsa please show to me how to fix this issue(no buying price and no margin), I'm using the new version of dolibarr v11 and new takePOS as well..Thanks..

**Comment by sarksloane** [comment]
@iaoranamoa did you fix this issue?

**Comment by andreubisquerra** [comment]
Solved with commit https://github.com/Dolibarr/dolibarr/pull/13544
