### ISSUE TITLE
BUG :  upgrade to v11, adherent_type_lang

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#12310]
Request 117 sql='create table llx_adherent_type_lang(rowid integer AUTO_INCREMENT PRIMARY KEY,fk_type integer DEFAULT 0 NOT NULL,lang varchar(5) DEFAULT 0 NOT NULL,label varchar(255) NOT NULL,description text,email text,import_key varchar(14) DEFAULT NULL)ENGINE=innodb;'
--
Erreur DB_ERROR_1813: create table llx_adherent_type_lang(rowid integer AUTO_INCREMENT PRIMARY KEY,fk_type integer DEFAULT 0 NOT NULL,lang varchar(5) DEFAULT 0 NOT NULL,label varchar(255) NOT NULL,description text,email text,import_key varchar(14) DEFAULT NULL)ENGINE=innodb;Tablespace for table '`demo`.`llx_adherent_type_lang`' exists. Please DISCARD the tablespace before IMPORT

**Comment by eldy** [comment]
Can't reproduce. Is it on mysql or pgsql ?

**Comment by ptibogxiv** [comment]
Mysql with Maria db

**Comment by eldy** [comment]
Can you provide a screenshot ? I can't reproduce with same database version on last develop.

**Comment by ptibogxiv** [comment]
![image](https://user-images.githubusercontent.com/3135833/68392942-2dd0ab80-016b-11ea-8314-d648ea6d7a75.png)
@eldy

**Comment by ptibogxiv** [comment]
personnal error server fixed
