### ISSUE TITLE
issue invoicetemplate manual creation

### ISSUE THREAD

**Issue by Crush33** [Dolibarr/dolibarr#12320]
# Bug
- From the screen /dolibarr/compta/facture/invoicetemplate_list.php click on "create bill" at the end of the line
- the /dolibarr/compta/facture/card.php?action=create&socid=XXX&fac_rec=YYY screen opens
- fill out the invoice creation form (by changing the particular third and the date) and then at the bottom "create draft"
- the invoice is created but no field has changed and it remained on the third party who owns the model and not passed on the third party that I entered in the form.

found on v8 v9 and v10

## Environment
- **Version**: 10
- **OS**: debian 9
- **Web server**: apache2
- **PHP**: php7
- **Database**: maria10
- **URL(s)**: /dolibarr/compta/facture/invoicetemplate_list.php
/dolibarr/compta/facture/card.php?action=create&socid=XXX&fac_rec=YYY

**Comment by eldy** [comment]
Is it an invoice with a recurring rule (a frequency to repeat the invoice) or not ?

**Comment by Crush33** [comment]
**without** frequency
