### ISSUE TITLE
Sepa xml payment files fail to download

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12339]
# Bug
After generating the XML files for sepa direct debit, when trying to download, the browser stalls and ultimately fails

## Environment
- **Version**: 9.0.4
- **OS**: Linux X86:64 on OVH shared hosting. Linux version 4.14.127-ovh-vps-grsec-zfs-classid
- **Web server**: Apache, provided by OVH shared hosting
- **PHP**: 7.0.33
- **Database**: MYSQL v.5.6
- **URL(s)**: /compta/prelevement/card.php

## Expected and actual behavior
Expected behaviour: 
When clicking on the sepa xml payment files, the browser (tested on both firefox and chrome) starts trying to download and eventually reports that the download failed. Checking the logs provides no useful information, and shows no errors. The file can be checked by SSH-ing to the server. I've attached server log and dolibarr logs with sensitive information redacted

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[apache.log](https://github.com/Dolibarr/dolibarr/files/3808554/apache.log)
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/3808555/dolibarr.log)

**Comment by eldy** [comment]
May be a pb with your antispam ?
The log apache.log say the file was correctly download by browser.
Note that you can find the file into directory documents/prelevement/receipts

**Comment by ToniTen** [comment]
Thanks Eldy for the reply. I know I can find those there, but the problem is, the person that needs to download the xml files and deal with the banks can't be trusted with ftp access to the server. I know that the logs show that the download was a success, but the file is not downloaded.

To make sure that it wasn't an issue with my browser, I fired up a virtual machine where I installed Dolibarr and there was no problem at all. I think it could be that OVH shared hosting configuration is problematic. I tried downloading the file and then uploading it to an invoice as an extra document, and it still has the same issue. File permissions seem fine. Maybe there's something that needs changing on the htaccess files, but Dolibarr doesn't use those that I can see (other than to block access to the documents directory). I also seem to be unable to download the dolibarr.log from /admin/syslog.php.

**Comment by ToniTen** [comment]
Digging further, and checking network traffic with developer console, the file is being correctly downloaded, but it seems that the browser is somewhat confused  and thinks the download failed when it actually succeeded.

[response-headers.txt](https://github.com/Dolibarr/dolibarr/files/3808945/response-headers.txt)

The content is correctly displayed in the response tab, under response payload, meaning that my best conjecture is that the server is not closing the connection correctly? 

EDIT: The plot deepens. as clicking on the link to the xml file but not accepting the download gives "/tmp/mozilla_axis0/CHW3CeOy.asc.part could not be saved, because the source file could not be read.

Try again later, or contact the server administrator."

**Comment by eldy** [comment]
Is trouble only for the sepa xml file ?

**Comment by ToniTen** [comment]
it happens with the sepa file and with the log. Not with pdf or odt files. It happens with uploaded text files too (including xml and plain text files). If I was a guessing man, I feel it has to do with how the system handles text as opposed to binary files, but I can't be sure.

EDIT, sorry hit submit and close instead of just submit.

**Comment by eldy** [comment]
You probably right when you say it has to do with how the system handles text as opposed to binary files. But i don't see any reason for that. Looks more like a problem into the webserver setup ?

**Comment by ToniTen** [comment]
This is shared hosting, so I don't really have access to the webserver setup. I know that on the same hosting, on a Drupal 7 installation, I can download text files without issues, so there must be something that Dolibarr does differently. I'm not familiar enough with the code for Dolibarr to know what is the issue or how to further help debug it, but I am working on it. Any pointers? Anything I can try to find to help you find the source of the bug?

**Comment by ToniTen** [comment]
After some testing, I found out that if I disable gzip compression globally (via a SetEnv .htaccess rule), I can download no problem, but that obviously plays merry hell with performance. I'm trying to add a rule only for the sepa XML files (unsuccessfully so far), but at least I know what the issue is.

**Comment by ToniTen** [comment]
I spent a while researching .htaccess and this seems to work to disable gzip compression for sepa xml and log files, so they can be downloaded from the web interface. If you're facing this issue, adding this file to the root of your htdocs dir will fix it, at the cost of disabling compression for them. This is not a proper fix, but rather a workaround that lets me get on with my other work. This won't fix the issue for other text files uploaded to the EDM subsystem, but you can adapt it easily to make it work for them too.

[htaccess.txt](https://github.com/Dolibarr/dolibarr/files/3831687/htaccess.txt) rename this file to .htaccess when adding it to your dolibarr install, or paste the contents if you already have an .htaccess file. Github won't let me upload the file otherwise.

I however have no clue why this causes issues while serving gzip compressed html files does not.

**Comment by ToniTen** [comment]
The issue persists with the latest Dolibarr. The workaround described in https://github.com/Dolibarr/dolibarr/issues/12339#issuecomment-552465228 still works too, and I have yet to find the actual cause

**Comment by ksar-ksar** [comment]
Hello,

This is not related to Dolibarr itself but due to hosting
