### ISSUE TITLE
Adherent validation with notification

### ISSUE THREAD

**Issue by Givrix** [Dolibarr/dolibarr#12355]
Hello,

On a fresh install of 10.0.3, when trying to validate a new adherent it fails with a red popup "Click here to set mandatory setting" (or like, I translate it from french). Clicking it does nothing !
I finally realized that in Adherent settings->Emails, SendingEmailOnMemberValidation was disabled by default.
Enabling it solves the issue.

**Comment by Givrix** [comment]
Yes it's a duplicate of this closed thread, https://github.com/Dolibarr/dolibarr/issues/10513
But it may be user-friendly to fix this...

**Comment by eldy** [comment]
What do you mean ?
The message say that your setup is not complete when it is not, because the system can't guess which email you want to send. So it ask you to set it. This looks to be the expected behaviour. Which king of fix do you expect ?

**Comment by Givrix** [comment]
What I mean is explicit :
- The notification is not clear at all to what is misconfigured.
- It says click here but it's non clickable.
- All other messages are set by default, why not this one? The preset exists but is not selected.
Does all of this is intended ? Why ?
I can certainly make the fix and submit it in a fork.

**Comment by dpriskorn** [comment]
Update to v12 and reopen if the problem persists.
