### ISSUE TITLE
Extra fields values are not updated on invoice creation from invoice template

### ISSUE THREAD

**Issue by hminet** [Dolibarr/dolibarr#12361]
# Bug
The values entered in the additional fields on customer invoice creation pre-form (only from an invoice template) are not kept. The auto-calculated fields are not calculated as well.

## Environment
- **Version**: 10.0.1
- **OS**: Debian 9 running TinyCP on a virtual machine on PVE
- **Web server**: Apache/2.4.25 
- **PHP**: PHP 7
- **Database**: MySQL or MariaDB 5.5.5-10.1.37-MariaDB-0+deb9u1
- **URL(s)**: https://intranet/dolibarr/compta/facture/card.php?action=create&socid=76&fac_rec=10

## Steps to reproduce the behavior
- Define some additional fields on the invoice entity (eg: "Serial number")
- Create a customer invoice and convert it into an invoice template
- Manually issue a new invoice from the invoice template with the "create invoice" button (same behaviour if invoice in auto-generated from the recurring invoices CRON job)

## Screenshots

1. Issue a new invoice from the invoice template :

<img width="1621" alt="Capture d’écran 2019-11-06 à 13 50 01" src="https://user-images.githubusercontent.com/57443810/68301507-635c9280-00a0-11ea-975c-a8d38b05b4ac.png">

2. Populate some of the extra fields :

<img width="1635" alt="Capture d’écran 2019-11-06 à 13 55 14" src="https://user-images.githubusercontent.com/57443810/68301508-635c9280-00a0-11ea-90b3-37bba13b32a6.png">

3. The value entered in the extra fields is not kept : 
And the auto-calculated fields are not calculated as they should : 

<img width="1642" alt="Capture d’écran 2019-11-06 à 13 57 57" src="https://user-images.githubusercontent.com/57443810/68301509-635c9280-00a0-11ea-9c5f-14378a98637c.png">

4. When manually editing any extra field, the the auto-calculated fields are calculated properly : 

<img width="1642" alt="Capture d’écran 2019-11-06 à 14 07 27" src="https://user-images.githubusercontent.com/57443810/68301506-635c9280-00a0-11ea-8d1a-5489edd0f043.png">

**Comment by hminet** [comment]
I use Dolibarr for my business since 2013 and I'm very happy with it, thank you guys for this very nice software. This is my first issue reported on GitHub and on Dolibarr, i hope everything has been properly reported. Otherwise please let me know...

I saw everyone is speaking english here mais je suis francophone à la base si besoin de creuser davantage le problème je peux répondre en FR/EN.

Now as my business growned i wanted to go one step further and automatisate some recurring invoices. The template invoice functionnality is very great but I mandatory need my extra fields to be working and calculated for my accounting so for the moment this is a blocking issue to me and i cannot fully rely on this functionnality in production.

Many thanks for your help.

**Comment by hminet** [comment]
OK i have found where the problem is...

**File : /htdocs/compta/facture/class/facture.class.php (line 388)**
`		    $this->array_options=$_facrec->array_options;
`

This actually force overwrites the values of the extra fields on my single invoice with them of the source template invoice.

But if there is no template invoice additional fields defined on the customer invoice entity, it replaces all my values defined on the single invoice with an empty array...

So basically, if you want an extra field to be copied from one template invoice into the invoices made from this template, you have to define the same additional field on **both INVOICE entity and INVOICE TEMPLATE entity**.  **And you have to set it once in the invoice template** so that the additional field entry is made in the database even if the value is empty but now the template has one additional field defined and it will trigger the creation and calculation of the additional fields on the single invoice made out of the templace invoice.

This is a good deal but the problem is that it replaces the **whole** options array, erasing the additional fields from the invoice if they are not existing in the template invoice as well...

So instead of : 

`		    $this->array_options=$_facrec->array_options;
`

I think a better approach would be to set by default (**on the pre-form - "create" --not "add"-- screen of the invoice from template**) the values of the additional fields by default with those set on the invoice template (if the extra field exists on the customer invoice model and is defined). Otherwise leave the invoice extra field default value.

Up to the user to modify the values on this particular invoice before to click on "Create draft" if needed.

But whenever is present in the template invoice in the extra fields, after we click on the "Create draft" button on the pre-form, it only makes the single invoice with what has been entered here.

So that, depending on the configuration of your template invoice, you could only set some values to be recopied each time an invoice is issued from the template and up to the user to populate the other fields on each single invoice if needed.

What do you think of this approach ?

NB : the problem still need to be solved in the CRON calling the **createRecurringInvoices** function in **file : /htdocs/compta/facture/class/facture_rec.class.php (line 1073)**

**Comment by eldy** [comment]
When you create an invoice from a template, all data known come from the template. So you must have the extrafields information stored into template.
Did you try to create the same extrafields (with same key) on template invoice ?

**Comment by hminet** [comment]
Hi ! Thank you for your reply !

Indeed all the values set on the single invoice come from the template invoice if i set the same extra fields. I did not tried before.
 
But then why are the extra fields (invoice entity's extra fields) shown for modification in the pre-form before the invoice is saved as draft ? What is the meaning of showing these fields if they are going to be overwritted anyway ? :-)

If i put a value in the additional field on the pre-form before the invoice is saved as draft (we still speak about an invoice made out of a template) it is not taken into account as once the invoice is made all the additional fields values (of the single invoice) are replaced by the values of the invoice template... 

And worse : if i've set a custom field on the pre-form of my single invoice and that this extra field does not exist on my template invoice... it is simply skipped... as the code simply replaces the WHOLE array... instead of MERGING them ?

Finally this is a non-sense as if you specify some values in the pre-form you expect them to be taken into account on the generated invoice ? Isn't ?

And if it is a calculated field, it is not computed at all excepted if you have set it in the template invoice entity with the same key as you suggested... I use a calculated field to calculate a SEPA structured communication automatisate my bank reconciliation...

The actual behaviour has sense (excepted for the calculated fields which should always be calculated whenever they exist on the invoice template or not) in case the single invoice is made by the CRON (recurring invoices cron job) as the user is not present and the invoices are generated in batch by the job... Then YES, this is useful to overwrite all the custom fields with those of the template as the user is not present to review them during the creation...

So, as the invoice generation from template from the GUI is handled in **/compta/facture/card.php** and from the CRON in **/compta/facture/class/facture-rec.class.php**, would it not be a good idea to have two separate behaviour depending of the context ?

- **If the recurring invoice is issued by an user from the web GUI :**

Deactivate the line 

**File : /htdocs/compta/facture/class/facture.class.php (line 388)**
`$this->array_options=$_facrec->array_options;
`

And in the file **/compta/facture/card.php** (on $action=='create') :

Fill-in the extra fields in the invoice creation pre-form by default with the values set in the template (if they have been set in the template otherwise leave empty). And finally save the issued invoice with the values (even the empty ones) the user has entered (or left as by default) in the pre-form (values from $_POST).

- **If the recurring invoice is made by the CRON job (without user presence)**

Copy the extra fields values from the template onto the generated invoice (as it is the case for the moment).

I think this could be an **improvement** to the workflow template invoice -> invoice, as sometime the users will want to change the values of the extra fields on the issued invoice and not always rely on those set by default in the template. They could be modified afterwards once the invoice is issued, OK, but that's more clicks :-)

But in both cases (GUI/CRON) the autocalculated fields that are not calculated remains an issue...

Many thanks for your help.

**Comment by hminet** [comment]
I did another test...

Even if I follow your instructions (make the same extra field in the invoice template entity).
When i make an invoice template, if I have an auto-calculated field, it is not computed on the invoice template. Therefore i need to edit another extra field on the template invoice (even if i leave it empty) but trigging the edit_extrafields action does the job and launch the auto-calculation of the extra fields...

If i don't do that the auto-calculated fields are also not calculated on the generated invoices from the template as well...

This because the extra fields values are not inserted in the database for the template invoice.
And as each time a recurring invoice is made out of the template the extra fields are copied from the template to the recurring invoice : they are not present in the generated invoice as well...

**Comment by fbosman** [comment]
I think you should look at https://github.com/Dolibarr/dolibarr/pull/11436
This is an option that stores calculated fields in the database, but has a drawback: the calculation is only done when the object is changed, when a field is changed on which the calculation depends and that field does not belong to the object the calculation is not refreshed and may render an erroneous result.

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

> Op 11 nov. 2019 om 22:09 heeft hminet <notifications@github.com> het volgende geschreven:
> 

﻿
I did another test...

Even if I follow your instructions (make the same extra field in the invoice template entity).
When i make an invoice template, if I have an auto-calculated field, it is not computed on the invoice template. Therefore i need to edit another extra field on the template invoice (even if i leave it empty) but trigging the edit_extrafields action does the job and launch the auto-calculation of the extra fields...

If i don't do that the auto-calculated fields are also not calculated on the generated invoices from the template as well...

This because the extra fields values are not inserted in the database for the template invoice.
And as each time a recurring invoice is made out of the template the extra fields are copied from the template to the recurring invoice : they are not present in the generated invoice as well...

**Comment by hminet** [comment]
Hello Frans,

Thank you for your suggestion however the problem would remains the same even with your commits as the computed fields are only calculated if there is a line inserted in the database in the tables : 

- For a template invoice : **"llx_facture_rec_extrafields"**
- For a regular invoice : **"llx_facture_rec_extrafields"**

Otherwise the calculated fields are never calculated until you manually modify one extra field (which triggers the function `$this->insertExtraFields();` i suppose... didn't check yet...

I think a good idea would be to call this function once the template invoice is saved in order to insert a line with all the additional fields in **"llx_facture_rec_extrafields"** and allow the auto-calculation of the extra fields if required. Just like it was already the case with the regular invoices... @eldy what do you think of this ?
