### ISSUE TITLE
Bug: You have an error in your SQL syntax, htdocs/compta/bank/various_payment/card.php (v 10.0.3)

### ISSUE THREAD

**Issue by WhilelM** [Dolibarr/dolibarr#12363]
# Bug
When adding an entry [nouvelle écriture] on a bank account, i get the following error message : 

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '€, '3', '', 'Avance RNR STDV', '47', '', 98, 6, '2019-11-06 18:51:33', NULL, 1' at line 1

## Environment
- **Version**: 10.0.3
- **OS**: Linux lrv 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.11-1~deb10u1
- **Database**: MariaDB 5.5.5-10.3.17-MariaDB-0+deb10u1-log
- **URL(s)**: https://dolibarr.laressourcerieverte.com/htdocs/compta/bank/various_payment/card.php

## Expected and actual behavior
Form validated and entry added 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
https://nc.laressourcerieverte.com/index.php/s/GKDLkYfDTaiMKbX

**Comment by aspangaro** [comment]
Hello, 

It's work for me, maybe a problem with migration from other version.

You have the field subledger_account in llx_payment_various in your database ?

If no, execute this sql request :
ALTER TABLE llx_payment_various ADD COLUMN subledger_account varchar(32);
