### ISSUE TITLE
Add supplier number to customers

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12387]
# Feature Request
Add a field for supplier number to customers. This field is assigned us by the customer, and is different from both Customer Code and Vendor Code. This number should then be displayed in the documents. A similar feature could also be added for vendor supplied customer codes, where the vendor asings us a customer code.

## Use case
Many customers assign us a supplier number (or code, can be alphanumeric) and request that this number appears in all the documents we send them. If this number is nor present some customers will raise issue with that and delay processing the documents. 

## Suggested implementation
- Add a field to the customer tab of the third party to hold this supplier number
- Show this field after the current customer code in the page heads

**Comment by ToniTen** [comment]
As for why the Customer Code/Vendor Code can't be used for this, the reason is simple, these fields are unique columns. While the chance of two separate customers assigning you the same number is slim, sometimes a single customer represents multiple companies (as in subdivisions of the company are their own company with their own VAT ID), and they share a supplier list, and thus assign you the same number.

**Comment by ToniTen** [comment]
This feature is still relevant. Yes, you can add a custom field for this purpose, but getting it working properly requires editing the PDF documents and so is not an option for everybody.

**Comment by ksar-ksar** [comment]
Hi,

Why don't you use extrafields ?

**Comment by ToniTen** [comment]
> Why don't you use extrafields ?

I am using Extrafields. I edited the PDF templates to include it. However, I feel this is a common enough thing that it should be included by default in Dolibarr
