### ISSUE TITLE
Add an API endpoint to retrieve company informations

### ISSUE THREAD

**Issue by corentin59** [Dolibarr/dolibarr#12384]
# Feature Request
Add an API endpoint to retrieve company informations
admin/company.php?mainmenu=home

**Comment by c3do** [comment]
Are you using the API Rest? There is an endpoint named "thirdparties".

**Comment by corentin59** [comment]
Yes I use REST API,

But I dont' want thirds but my company/organization informations.
![image](https://user-images.githubusercontent.com/2035983/68528204-022afe00-02f0-11ea-86b9-06a75dc61019.png)

**Comment by c3do** [comment]
Ce sont des informations statiques. Je doute qu'il y ait un grand intérêt à ce qu'on puisse récupérer ces informations depuis l'API. Non pas que vous en ayez pas besoin, mais juste que ça semble vraiment très spécifique à vos besoins, et qu'il est très peu probable que ce soit développé un jour, sauf si vous connaissez quelqu'un qui puisse le faire.

**Comment by corentin59** [comment]
:)
En effet, c'est certainement spécifique à notre besoin, on utilise beaucoup les ERP Dolibarr et nous développons d'autres applications qui peuvent s'y connecter dans un contexte multi-organisation. Cet endpoint permettra de contextualiser les briques appelantes qui sont elles aussi multi-organisations.

Je peux développer cet endpoint, pensez vous qu'il soit préférable de le développer en module ou de le mettre dans le core ? Si vous avez un peu de docs ou quelques conseils pour démarrer le développement d'un endpoint je suis preneur, sinon je peux m'inspirer d'autres endpoint. Si c'est statique je pense qu'il y aura qu'une méthode GET ?

Selon vous quel doit être le nom du endpoint /company, /organization ?

**Comment by c3do** [comment]
Personnellement, je vous répond en tant que développeur amateur. Mais, il faudrait voir si @eldy est d'accord avec ma réponse. Je pense qu'il suffirait d'ajouter un endpoint GET /const/{name} (par exemple) dans le fichier htdocs/api/class/api_setup.class.php, qui me semble le plus approprié. Et cette endpoint permettrait d'aller chercher la valeur de n'importe quelle constante dans la table llx_const. ça ne devrait pas être très compliqué à coder. Il faut juste voir s'il existe des droits d'accès pour la lecture des constantes et vérifier si l'utilisateur à les droits nécessaires avant de lui retourner la valeur. Voilà, personnellement, ce que je ferai. Et je ferai un pull request pour l'intégrer aux futures versions de dolibarr, pour que tout le monde puisse en profiter, et ne pas avoir à refaire les modifs plus tard :)

**Comment by corentin59** [comment]
Merci pour la réponse, pour compléter je pensais faire /consts (pluriel), sans paramètre la liste des constantes, avec, on remonte la constante. Si on ne la trouve pas erreur 404.

**Comment by c3do** [comment]
Dans ce cas, il vous faudrait les deux points.
- GET /consts : pour la liste des constantes
- GET /consts/{name} : pour avoir la valeur d'une constante bien précise.
En gardant le nom au pluriel pour suivre la logique des autres endpoints.

**Comment by corentin59** [comment]
En phase !!
@eldy pouvons nous avoir ton avis sur le nommage + intérêt + sécurité ?

**Comment by ptibogxiv** [comment]
je vais regarder pour faire quelque chose ;) juste ces info ce n'ets pas plus sensible que d'autres à récupérer

**Comment by c3do** [comment]
C'est sûr. Mais penses générique. Un point d'accès générique comme décrit ci-dessus pourra certainement servir à plus de personnes que juste avoir les infos d'une entité. Et ce sera même peut-être plus simple à implémenter :)

**Comment by ptibogxiv** [comment]
premier jet express https://github.com/Dolibarr/dolibarr/pull/12525 api basique car existe pour ceux qui ont le module multicompany ;)

**Comment by c3do** [comment]
effectivement, 4 lignes :smile:

**Comment by ptibogxiv** [comment]
après il faut voir avec @hregis comment et si il peut / veut  inclure et  fusionner l'API de récupération de son module dans le core. Mais déjà ce mini code est efficace ;)

**Comment by ptibogxiv** [comment]
> effectivement, 4 lignes 😄

la qualité prime à la quantité 🤙

**Comment by ptibogxiv** [comment]
PR validé et intégré en v11, merci de fermer cet issue :)
