### ISSUE TITLE
Better look of forms

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#12392]
I tried to create one company and the form is very long and at first sight it is discouraging to continue!
In my opinion a better presentation can only improve the user experience! the current state as if we are facing a form of posts during a delivery of a package! :)

Example:
![image](https://user-images.githubusercontent.com/26695620/68498833-21764c80-0258-11ea-8e3d-aeaf46832c00.png)

**Comment by wdammak** [comment]
vs
![image](https://user-images.githubusercontent.com/26695620/68499338-40291300-0259-11ea-9be1-2ccef61e1801.png)

**Comment by aspangaro** [comment]
👍 Where the original image comes from, I'm interested

**Comment by wdammak** [comment]
> 
> 
> +1 Where the original image comes from, I'm interested

The picture is that of another ERP
If Bootstrap will integrate we can do better!
