### ISSUE TITLE
Permissions for users is a blank page

### ISSUE THREAD

**Issue by OussamaSefrioui** [Dolibarr/dolibarr#12411]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[* The permissions page is blank when wanting to add or modify permissions for any user. even if connected with SuperAdmin Account*]

## Environment
- **Version**: [*10*]
- **OS**: [*Linux Ubuntu*]
- **Web server**: [*Apache*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*List of different permissions*]

## Steps to reproduce the behavior
[*afetr clicking on permissions*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Just tested in 10.0.4 and it works for me
