### ISSUE TITLE
[BUG] account label not updated in accounting_bookkeeping / blocking issue for FEC export

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#12450]
Hi,

the field label_compte in accounting_bookkeeping stay null
while creating new Social/fiscal taxes. 
-> FEC export is not correct
(i have not checked for other Special expenses)

## Environment
- **Version**: 10.0.3 (and before ?)
- **OS**: any
- **Web server**: any
- **PHP**: any

Example :

![image](https://user-images.githubusercontent.com/13518576/68937284-65a7a680-079c-11ea-8955-7fe0d536bf2e.png)

**Comment by aspangaro** [comment]
#12457

**Comment by Arre8** [comment]
tested : it works !
thanks a lot :)
