### ISSUE TITLE
Add bootstrap when you need in some module

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#12459]
main.inc.php
function top_htmlhead($head, $title = '', $disablejs = 0, $disablehead = 0, $arrayofjs = '', $arrayofcss = '', $disablejmobile = 0, $disablenofollow = 0, $bootstrap = 0)

```
if ($bootstrap)
{
            print '<!-- Includes CSS for Bootstrap -->'."\n";
            print '<link rel="stylesheet" type="text/css" href="'.DOL_URL_ROOT.'/theme/common/bootstrap/bootstrap.min.css'.($ext?'?'.$ext:'').'">'."\n";
}
```
The same applies to bootstrap.min.js

**Comment by altairis-tof** [comment]
why dont you make a PR instead of creating another issue ?

**Comment by wdammak** [comment]
@altatof il faut des mois et des mois pour un PR soit valider! il faut aussi attendre la disponibilité et le bon jour d'eldy... donc à laisser tomber!

**Comment by eldy** [comment]
Currently there is no problem about availability to validate PRs. If a PR stay a long time in the pipe, the reason is most often in the quality, the needs of process, the lack of consensus or the requirements of a community working on project than into the "bon jour" of someone. Please take a note at the CONTRIBUTING file to know more information about how Merge process works and requirements to have a PR merged. This is an extract:

> Pull Request (PR) process is the process to submit a change (enhancement, bug fix, ...) into the code of the project. There is some rules to know and 
> a process to follow to optimize the chance to have PRs merged efficiently...
> 
> When submitting a pull request, use same rule as Commits for the message.
> If your pull request only contains 1 commit, GitHub will be smart enough to fill it for you.
> Otherwise, please be a bit verbose about what you're providing.
> 
> Your Pull Request (PR) must pass the Continuous Integration checks and code quality checks.
> Also, some code changes need a prior approbation:
> 
> * if you want to include a new external library (into htdocs/includes directory), please ask before to the project manager (@eldy) to see if such a library can be accepted.
> 
> * if you add a new table, you must first create a page on https://wiki.dolibarr.org/index.php/Category:Table_SQL (copy an existing page changing its name to see it into this index page). Then ask the project manager (@eldy) if the new data model you plan to add is compatible with curent and future works in progress and can be accepted as you suggest.
> 
> Once a PR has been submitted, you may need to wait for its integration. It is common that the project leader let the PR open for a long delay to allow every developer discuss about the PR (A label is added in such a case).
> 
> If the label of PR start with "WIP" (Work In Progress), it will not be analyzed (until you change the label of PR).
> 
> If your PR has errors reported by the Continuous Integration Platform, it means your PR is not valid and nothing will be done with it. It will be kept open to allow developers to fix this, or it may be closed several month later. Don't expect anything on your PR if you have such errors, you MUST first fix the Continuous Integration error to have it taken into consideration. 
> 
> If the PR is valid, and is kept open for a long time, a tag will also be added on the PR to describe the status of your PR and why the PR is kept open. By putting your mouse on the tag, you will get a full explanation of the tag/status that explain why your PR has not been integrated yet.
> In most cases, it gives you information of things you have to do to have the PR taken into consideration (for example a change is requested, a conflict is expected to be solved, some questions were asked). If you have a yellow, red flag of purple flag, don't expect to have your PR validated. You must first provide the answer the tag ask you. The majority of open PR are waiting an action of the author of the PR.
> 
> Statistics on Dolibarr project shows that around 95% of submitted PR are reviewed and tagged with a label. Average answer delay is also one of the best among Open source project (just few days before having the Answer Tag set). This is one of the most important ratio of answered PR in Open Source world for a major project. Don't expect the core team to reach the 100%. A so high ratio is very rare on an Open Source project and with the increasing popularity of Dolibarr, this ratio will probably decrease in future to a more common level. 
>

**Comment by wdammak** [comment]
@eldy
Taking the example of warehouse management, three or two years ago I listed the limits and the necessary functionalities and are missing! I tried to advance this subject but staying in a dead end so I gave up ... fortunately in recent weeks I have seen that things are starting to change for warehouse management
If things started 2 years ago (even if the PR are not fully developed) you should have saved a lot of time and dealt with other subjects!

It's the same for the management of multi-companies sooner or later the ERP would be in the need to have this functionality in native, it is therefore necessary to decide as soon as possible or to include an existing module after the agreement from its author or develop it natively!

Best regards

**Comment by ksar-ksar** [comment]
Hi @wdammak 

Would you make a PR for this ?
