### ISSUE TITLE
Error importing to llx_accounting_bookkeeping

### ISSUE THREAD

**Issue by ericdes** [Dolibarr/dolibarr#12460]
Attached is the import file I'm trying to import to Dolibarr 10.0.3
[Payes 2019-10.xlsx](https://github.com/Dolibarr/dolibarr/files/3854254/Payes.2019-10.xlsx)

Importation fails with message:

* Ligne 2    > Field 'label_compte' doesn't have a default value* Ligne 3    > Field 'label_compte' doesn't have a default value* Ligne 4    > Field 'label_compte' doesn't have a default value* Ligne 5    > Field 'label_compte' doesn't have a default value* Ligne 6    > Field 'label_compte' doesn't have a default value* Ligne 7    > Field 'label_compte' doesn't have a default value* Ligne 8    > Field 'label_compte' doesn't have a default value* Ligne 9    > Field 'label_compte' doesn't have a default value* Ligne 10    > Field 'label_compte' doesn't have a default value* Ligne 11    > Field 'label_compte' doesn't have a default value* Ligne 12    > Field 'label_compte' doesn't have a default value* Ligne 13    > Field 'label_compte' doesn't have a default value* Ligne 14    > Field 'label_compte' doesn't have a default value* Ligne 15    > Field 'label_compte' doesn't have a default value* Ligne 16    > Field 'label_compte' doesn't have a default value
--

**Comment by avignat** [comment]
Same here version 11.0.3 with a CSV file

**Comment by avignat** [comment]
Any updates ?

**Comment by ksar-ksar** [comment]
Hello,

Still the case in V13 ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
