### ISSUE TITLE
PHP error on index.php

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#12480]
Warning: in_array() expects parameter 2 to be array, null given in /volume2/web/dolibarr/htdocs/index.php on line 680

with external user

dolibarr v11/dev

**Comment by inoveaconseil** [comment]
I can't reproduce this bug. Can you verify ?

**Comment by ptibogxiv** [comment]
i confirm  with last PR of this afternoon... present only for external user not internal or admin.
![image](https://user-images.githubusercontent.com/3135833/69905233-f55e6f00-13b0-11ea-9721-96f59c3dbae4.png)

**Comment by ptibogxiv** [comment]
fix in https://github.com/Dolibarr/dolibarr/pull/12725
