### ISSUE TITLE
Allow multiple logos, and allow selecting which one to use in different places

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12489]
# Feature Request
Right now, there is only one logo one can upload to Dolibarr and it gets used everywhere. It would be useful to be able to have multiple logos and use them in different contexts.

## Use case
The company that I work for has vastly different logos on their documents for marketing oriented documents (such as proposals and order confirmations) as opposed to financial oriented documents (invoices). Supplier orders have a completely different logo too. Different logos could be used in the same document type (e.g. in a proposal) to push a sub-brand or another. 

Right now, I've been uploading the logos manually to the web server to documents/mycompany/logos, and editing the PDF generating files to hardcode the logos (including duplicating some of the documents to have the same document with alternative logos) but that's not sustainable.

**Comment by elarifr** [comment]
i have on the dolistore an ExtraCGV module that allow you to define custom logo for propal / order / invoice and an extra field can be used as a slogan / mission in the header company name
