### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by noprianto** [Dolibarr/dolibarr#12491]
# Bug

## Environment
- **Version**: 9.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.4.39 (Win64) PHP/7.2.18
- **PHP**: apache2handler 7.2.18
- **Database**: MySQL or MariaDB 5.7.26
- **URL**: /doli9/admin/boxes.php?mainmenu=home

**Comment by atm-maxime** [comment]
Sorry your issue contains no description...
