### ISSUE TITLE
[10.0.3] Cannot validate expeditions

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#12506]
# Bug
User cannot validate expedition after migration between 4.0.0 and 10.0.3

## Environment
- **Version**: 10.0.3
- **Web server**: Apache
- **PHP**: 7.3
- **URL(s)**: /expedition/card.php?id=X

## Expected and actual behavior
We want to access to validate button. But class "butActionRefused" are set on this button

## Steps to reproduce the behavior
User have all right on
![image](https://user-images.githubusercontent.com/6638868/69548879-79bb8700-0f98-11ea-9431-14a639178cbe.png)
Advanced Perms is enabled.
![image](https://user-images.githubusercontent.com/6638868/69548914-93f56500-0f98-11ea-9334-52aba37c9378.png)
And button is disabled.
When i disable Advanced Perms, it works.  
In expedition/card.php, $user->rights->expedition->creer is correctly read, but $user->rights->expedition->shipping_advance->validate isn't.

**Comment by atm-maxime** [comment]
Hey. I just tested with 10.0.4 and I can't reproduce. Even with advanced right activated, if I have validation right on shipment module, the button is available.
