### ISSUE TITLE
Bug : global search (search_all) don't search in project description

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#12507]
# Instructions
# Bug
global search (search_all) don't search in project description

## Environment
- **Version**: All versions including trunk

## Expected and actual behavior
I'd guess that global search will search in project description, but no ..

## solution
in develop/htdocs/projet/list.php, line #117, add
'p.description'=>"Description",

I suggest too that description would be displayed in project ref popup in the list.
For that, in develop/htdocs/projet/list.php:
- add ,p.description in sql on line #291
- on line #724, replace 
    print $object->getNomUrl(1);
    with
    print $object->getNomUrl(1,'',0,$obj->description);

**Comment by atm-maxime** [comment]
Hello. The search engine is based on predefined searchable fields. Currently the description field is not one of them. So thanks for submitting a feature request.
As for your idea of displaying the description in the tooltip, it's a great idea, maybe on product and other objects too. Can you open a separate feature request ?
