### ISSUE TITLE
Crabe template only show one linked object on invoice but others exists

### ISSUE THREAD

**Issue by dgfmdrv** [Dolibarr/dolibarr#12541]
# Bug
Crabe template only shows one linked object on the invoice but others exist:
![image](https://user-images.githubusercontent.com/1451834/69749784-8df3b580-114b-11ea-8cda-47aecbbd56fb.png)

![image](https://user-images.githubusercontent.com/1451834/69749875-b24f9200-114b-11ea-89bd-a7e617a6e667.png)

## Environment
- **Version**: 10.0.3
- **OS**: FROM php:7.2-apache container
- **Web server**: Apache
- **PHP**: 7.2
- **Database**: MariaDB 
- **URL(s)**:

## Expected and actual behavior
I would like to concatenate all linked objects (order and ref). 

I added more log to pdf_writeLinkedObjects function to debug it (error_log line). 
```
... core]$ sudo vi ./lib/pdf.lib.php
function pdf_writeLinkedObjects(&$pdf, $object, $outputlangs, $posx, $posy, $w, $h, $align, $default_font_size)
{
        $linkedobjects = pdf_getLinkedObjects($object, $outputlangs);
        if (! empty($linkedobjects))
        {
                foreach($linkedobjects as $linkedobject)
                {
                        error_log("1 ".$linkedobject["ref_value"]);

                    $reftoshow = $linkedobject["ref_title"].' : '.$linkedobject["ref_value"];
                    if (! empty($linkedobject["date_value"]))
                    {
                        $reftoshow .= ' / '.$linkedobject["date_value"];
                    }

                        $posy+=3;
                        $pdf->SetXY($posx, $posy);
                        $pdf->SetFont('', '', $default_font_size - 2);
                        $pdf->MultiCell($w, $h, $reftoshow, '', $align);
                }
        }

        return $pdf->getY();
}
```
When I click on to generate invoice pdf again, on error_log file I can see three new lines. 
```
1 CO1909-0003 (PC11952)
1 CO1909-0003 (PC11952)
1 CO1909-0003 (PC11952)
```
I don't understand why this happens. Why three lines? and repeated?

In the same way, I tried to add more log to pdf_getLinkedObjects function (errr_log line) here: 
```
function pdf_getLinkedObjects($object, $outputlangs)
                [...]
                elseif ($objecttype == 'commande' || $objecttype == 'supplier_order')
                {
                        $outputlangs->load('orders');
                        foreach($objects as $elementobject)
                        {
                                $linkedobjects[$objecttype]['ref_title'] = $outputlangs->transnoentities("RefOrder");
                                $linkedobjects[$objecttype]['ref_value'] = $outputlangs->transnoentities($elementobject->ref) . ($elementobject->ref_client ? ' ('.$elementobject->ref_client.')' : '') . ($elementobject->ref_supplier ? ' ('.$elementobject->ref_supplier.')' : '');
                                $linkedobjects[$objecttype]['date_title'] = $outputlangs->transnoentities("OrderDate");
                                $linkedobjects[$objecttype]['date_value'] = dol_print_date($elementobject->date, 'day', '', $outputlangs);

                                error_log("3 ".$linkedobjects[$objecttype]['ref_value']);
                        }
                }
               [...]
```
The output is:
```
3 CO1911-0025 (PC11950),
3 CO1911-0024 (PC11949),
3 CO1911-0023 (PC11948),
3 CO1909-0004 (PC11953),
3 CO1909-0003 (PC11952),
1 CO1909-0003 (PC11952),
3 CO1911-0025 (PC11950),
3 CO1911-0024 (PC11949),
3 CO1911-0023 (PC11948),
3 CO1909-0004 (PC11953),
3 CO1909-0003 (PC11952),
1 CO1909-0003 (PC11952),
3 CO1911-0025 (PC11950),
3 CO1911-0024 (PC11949),
3 CO1911-0023 (PC11948),
3 CO1909-0004 (PC11953),
3 CO1909-0003 (PC11952),
1 CO1909-0003 (PC11952),
```

**Someone can help and tell me if this is the expected result?**

## Steps to reproduce the behavior
I have five customer orders from a customer. I selected all and click on facture orders:
![image](https://user-images.githubusercontent.com/1451834/69750543-4c640a00-114d-11ea-9f46-2a72bd907dca.png)

**Comment by atm-maxime** [comment]
Try with error_log("1 ".$linkedobject**['commande']**["ref_value"]);
Anyway, currently Dolibarr displays only one linked object on top of the PDF document. This should maybe evolve to have nothing on the top (if there are too many links, we can't display them all in the PDF header), but have them as line "titles" for example. But this would be a feature request :)
