### ISSUE TITLE
VAT for EU customers (international)

### ISSUE THREAD

**Issue by xabitrigo** [Dolibarr/dolibarr#12557]
# Bug
International buys should allow VAT types for both the origin and destination countries. According to this: https://europa.eu/youreurope/citizens/consumers/shopping/vat/ both cases are possible.

I'm trying to add a supplier invoice (with French SIREN) that used a Spanish VAT for the invoice, and I'm unable to do so.

## Environment
- **Version**: [*10.0.0*]
- **OS**: [*Ubuntu 16.04 LTS*]
- **Web server**: [*Apache/2.4.18 (Ubuntu)*]
- **PHP**: [*7.0.33-0ubuntu0.16.04.7*]
- **Database**: [*MySQL or MariaDB 5.7.28-0ubuntu0.16.04.2*]
- **URL(s)**: [*/fourn/facture/card.php?facid=113*]

## Expected and actual behavior
Display the VAT for the seller and buyer countries

## Steps to reproduce the behavior
Only the seller country VATs are available

**Comment by xabitrigo** [comment]
Just as a workaround, I've had to add the Spanish VAT to France in the  llx_c_tva dictionary.

**Comment by simnandez** [comment]
Try adding the hidden option SERVICE_ARE_ECOMMERCE_200238EC, more info at https://wiki.dolibarr.org/index.php/Setup_Other#Services_Module

**Comment by xabitrigo** [comment]
Sorry to bump this back. This seems to be working for predefined products, but not for free-text items.

What I was expecting was to be able to select the VAT to apply on a free item from the list of VATs of the destination country. Instead I can only select the VAT from the origin country, even after using SERVICE_ARE_ECOMMERCE_200238EC.

**Comment by ErikRakhorst** [comment]
One year further and still no solution. The behavior is still as described above. 
It works for predefined products, but not if you modify a line or add a custom product.

**Comment by PascalB67** [comment]
I'm just reviving the topic, it's starting to become blocking.
It is not possible to attribute a European VAT on a product, it no longer works on a product defined in 20.03
I need to find an alternative solution because I'm stuck.
Thank you
