### ISSUE TITLE
Adding VAT with a Code to a free line of contract will set the VAT value to 0%

### ISSUE THREAD

**Issue by code42fr** [Dolibarr/dolibarr#12617]
# Bug

Adding VAT with a Code to a free line of contract will set the VAT value to 0%

# Environment

* Version: [7.0.5], [9.0.4], [10.0.1]
* OS: Linux
* Web Server: nginx/1.14.0
* PHP: 7.2.5-1+ubuntu18.04.1+deb.sury.org+1
* Database: MySQL or MariaDB 5.7.28-0ubuntu0.18.04.4
* URL(s): /contrat/card.php?id=x

# Expected and actual behavior

Applying the VAT to a free line should be at the VAT value but is set at 0%.
This bug is present when the VAT as a Code.

# Steps to reproduce the behavior

* Create a VAT with a Code (In the example, VAT is set to 20% with the Code TVA)

![Capture d’écran 2019-12-03 à 16 31 26](https://user-images.githubusercontent.com/9167207/70064824-70f73080-15ea-11ea-87fa-dbc3e31c2570.png)

![Capture d’écran 2019-12-03 à 16 33 27](https://user-images.githubusercontent.com/9167207/70064962-a7cd4680-15ea-11ea-9b16-d9bbb75ddd5f.png)

* Then add a free line to a contract using the VAT with a Code.

![Capture d’écran 2019-12-03 à 16 37 40](https://user-images.githubusercontent.com/9167207/70065340-4063c680-15eb-11ea-8368-063e56dd2537.png)

* VAT for the line should be at 20% but is set to 0%

![Capture d’écran 2019-12-03 à 16 39 33](https://user-images.githubusercontent.com/9167207/70065531-933d7e00-15eb-11ea-96df-7394a3f45527.png)

**Comment by atm-maxime** [comment]
@aspangaro how should behave this kind of lines ?
