### ISSUE TITLE
Add total to statistics

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12614]
# Feature Request
When checking the statistics for all products with a given tag, it would be most useful to have a total displayed.

## Use case
When checking product statistics at /product/stats/card.php you can see, for either all products or for a given tag, how many units per month are in proposals/sales orders/invoices/... (when displaying "Statistics for sum of qty of products/services") in a given year. This is very handy, but if there was a total for the whole year next or under the graph, or a separate widget with the totals for the years in each document type, it would be a good tool for year to year planning.

**Comment by ptibogxiv** [comment]
already push ;)
https://github.com/Dolibarr/dolibarr/pull/12476

**Comment by ToniTen** [comment]
Sorry I didn't see it. This is great, was there another feature request for this that I missed? This is waiting to be merged and targets :develop I hope it lands in time for V11. Closing the FR since it seems that it's exactly what I suggested
