### ISSUE TITLE
Convert flag image in SVG for enhacement

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#12624]
for more better, compliant, modern and beautiful, it will be fantastic to convert flag image in svg

for example with this library

https://github.com/lipis/flag-icon-css

**Comment by dolibarr95** [comment]
Hi !
Love flat-icon-css too

https://github.com/Dolibarr/dolibarr/issues/9429#issuecomment-536478518

**Comment by ptibogxiv** [comment]
Always need it
