### ISSUE TITLE
Display of SendingMethod in Forms not correct

### ISSUE THREAD

**Issue by RCBT-DB** [Dolibarr/dolibarr#12623]
# Bug
[*Display of SendingMethod (table llx_c_shipment_mode) in Forms not correct*]

## Environment
- **Version**: [*10.0.2*]
- **OS**: [*Linux regcell01 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64*]
- **Web server**: [*Apache/2.4.25 (Debian)*]
- **PHP**: [*7.0.33-0+deb9u5*]
- **Database**: [*MySQL or MariaDB 5.5.5-10.1.41-MariaDB-0+deb9u1*]
- **URL(s)**: [*https://cockpit.regcell-biotech.com/comm/propal/card.php?id=3*]

## Expected and actual behavior
Display of SendingMethod in Forms not correct. Instead of showing the text description the technical name is displayed

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![2019-12-04 12_01_56-Angebot und 6 weitere Seiten ‎- Microsoft Edge](https://user-images.githubusercontent.com/58511270/70137428-2af3a880-168e-11ea-8545-90c62c970255.jpg)
*]

**Comment by ksar-ksar** [comment]
Hi,

I think this is linked to a translation issue.
You language translation package is not complete.
What language are you using ?

**Comment by RCBT-DB** [comment]
![2019-12-09 08_09_15-Einstellungen und 1 weitere Seite ‎- Microsoft Edge](https://user-images.githubusercontent.com/58511270/70414821-78d82a00-1a5b-11ea-8682-90751cab2e85.jpg)
Sounds possible to me, I guess swiss-german is not so common ...

**Comment by RCBT-DB** [comment]
Can we use part of the german translation ?

**Comment by RCBT-DB** [comment]
> Hi,
> I think this is linked to a translation issue.
> You language translation package is not complete.
> What language are you using ?

de_CH

**Comment by RCBT-DB** [comment]
> Hi,
> I think this is linked to a translation issue.
> You language translation package is not complete.
> What language are you using ?

So it should not be classified as bug, I guess ...

**Comment by ksar-ksar** [comment]
I confirm that the key 
SendingMethod=Versandart
is missing on the de_CH, but it is on the de_DE

You can add it on the dictionary

And any help is welcomed on : https://www.transifex.com/dolibarr-association/dolibarr/
![image](https://user-images.githubusercontent.com/35605507/70454559-ecedee80-1aaa-11ea-8db1-736f2ce2838a.png)

**Comment by RCBT-DB** [comment]
> I confirm that the key
> SendingMethod=Versandart
> is missing on the de_CH, but it is on the de_DE
> You can add it on the dictionary
> And any help is welcomed on : https://www.transifex.com/dolibarr-association/dolibarr/

As far as I understand it's not mising in our system:
![2019-12-10 00_38_26-Einstellungen und 33 weitere Seiten ‎- Microsoft Edge](https://user-images.githubusercontent.com/58511270/70482778-bf269b00-1ae6-11ea-966c-c762d175beea.jpg)

**Comment by atm-maxime** [comment]
Hi ! Yes the translation is missing. You created a new sending method in the dictionnary with the code "CATCH-OF". In the translation screen, you should add a translation with the key "SendingMethodCATCH-OF" for each language you use.
Standard keys are translated in de_CH, and when missing, de_DE are used. But for custom data, you need to add your own translations :)

**Comment by syrinx75** [comment]
I had the same problem with Dolibarr 17.0.2. In the expedition method added in the Dictionary, the code shouldn't contain a space char. If there is a space,  the word 'SendingMethodXXX' will appear.
