### ISSUE TITLE
Warning: Use of undefined constant i - assumed 'i' (this will throw an Error in a future version of PHP) in /var/www/html/expedition/card.php on line 696

### ISSUE THREAD

**Issue by ayoppa** [Dolibarr/dolibarr#12628]
Missing $

https://github.com/Dolibarr/dolibarr/blob/a7571054f06b4ca289b500a2c5a149044760ed38/htdocs/expedition/card.php#L696

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/12642
