### ISSUE TITLE
DebugBar module - Javascript error in Dolidroid

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#12641]
# Bug
Since Debugbar Module was added to Dolibarr, when activated, an error is shown everytime a page loads, but **only happen on Dolidroid** developed by @eldy.

*Lo siento, no soy programador, así que no puedo sugerir ninguna solución.*

## Environment
- **Version**: Since Debugbar is added to Dolibarr (*Viewed from Ver 9*)
- **OS**: Linux 4.4.59
- **Web server**: nginx/1.15.7
- **PHP**: 7.0.33
- **Database**: 5.5.5-10.3.11-MariaDB
- **URL(s)**: All in Dolidroid

## Expected and actual behavior
Attached image with error everytime a page is loaded.

## Steps to reproduce the behavior
Activate Debugbar when using Dolidroid
## Attached files

**Error in Dolidroid**
![debugbar](https://user-images.githubusercontent.com/15174724/70358380-80d87400-1879-11ea-8e3b-8610a088b725.jpg)

**..\includes\DebugBar\Resources\debugbar.js**
![dbugbar](https://user-images.githubusercontent.com/15174724/70359321-eb8aaf00-187b-11ea-90c3-b5faacf77182.jpg)

**Comment by ksar-ksar** [comment]
Hi,

Thanks for the report.
But it is linked to an external module, that is not supported by the Dolibarr project.

Please contact the dolidroid developper.

**Comment by PlanPc** [comment]
Thanks @ksar-ksar I will do.

@eldy is one of the main developers of Dolibarr, and the only one of Dolidroid, I think.

Being a problem that only occurs with Debugbar, I just thought that it did not meet some kind of programming standard that the other modules do.
