### ISSUE TITLE
Bug: Error after add consultation du patient

### ISSUE THREAD

**Issue by krichah** [Dolibarr/dolibarr#12656]
# Bug
Warning: count(): Parameter must be an array or an object that implements Countable in ...\htdocs\dolimed\cabinetmed\consultations.php on line 1251

## Environment
- **Version**: 9.0.5
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.11
- **PHP**: apache2handler 7.3.11
- **Database**: MySQL or MariaDB 5.5.5-10.4.8-MariaDB
- **URL**: /dolimed/cabinetmed/consultations.php?socid=1

**Comment by atm-maxime** [comment]
Same as in #12655 , this is an issue about an external module. You should close the issues here and report them to the module developer. Thanks.

**Comment by krichah** [comment]
OK, thanks

**Comment by dpriskorn** [comment]
closing
