### ISSUE TITLE
Bug: liste des consultations

### ISSUE THREAD

**Issue by krichah** [Dolibarr/dolibarr#12655]
# Bug

Warning: count(): Parameter must be an array or an object that implements Countable in \htdocs\mydoctor\cabinetmed\listconsult.php on line 370

## Environment
- **Version**: 9.0.5
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.11
- **PHP**: apache2handler 7.3.11
- **Database**: MySQL or MariaDB 5.5.5-10.4.8-MariaDB
- **URL**: /mydoctor/admin/ihm.php?mainmenu=home&leftmenu=setup

**Comment by atm-maxime** [comment]
Hmm, I think the "mydoctor" module is not a standard one. You should contact the developer concerned. @eldy is it dolimed ?

**Comment by krichah** [comment]
yes is dolimed

**Comment by krichah** [comment]
mydoctor is my folder name

**Comment by dpriskorn** [comment]
Not related to core. Closing
