### ISSUE TITLE
Ticket email notification is empty with custom fields

### ISSUE THREAD

**Issue by wneron** [Dolibarr/dolibarr#12653]
Hello everyone,

I have installed the ticket module with some custom fields.

The problem is that the custom fields are shown as “/custom” into the email

Is there any solution or php code to add to make it work properly ?

FYI: I have a programmer and I am willing to make it work, I just don’t know where to start about this issue thanks a lot for everyone telling me where to look …

Thanks
![problemdolibarr](https://user-images.githubusercontent.com/43225321/70391133-dd35b380-199f-11ea-9b34-253b9f296c86.png)

**Comment by wneron** [comment]
Do you know what to do? Thank you

I have found the code that is responsible of the problem;

File: interface_50_modTicket_TicketEmail.class

Location: \dolibarr\htdocs\core\triggers\

Line : 203

`	/* Send email to admin */
		            $subject = '['.$conf->global->MAIN_INFO_SOCIETE_NOM.'] '.$langs->transnoentities('TicketNewEmailSubjectAdmin');
		            $message_admin= $langs->transnoentities('TicketNewEmailBodyAdmin', $object->track_id)."\n\n";
		            $message_admin.='<ul><li>'.$langs->trans('Title').' : '.$object->subject.'</li>';
		            $message_admin.='<li>'.$langs->trans('Type').' : '.$object->type_label.'</li>';
		            $message_admin.='<li>'.$langs->trans('Category').' : '.$object->category_label.'</li>';
		            $message_admin.='<li>'.$langs->trans('Severity').' : '.$object->severity_label.'</li>';
		            $message_admin.='<li>'.$langs->trans('From').' : '.( $object->email_from ? $object->email_from : ( $object->fk_user_create > 0 ? $langs->trans('Internal') : '') ).'</li>';
		            // Extrafields
		            if (is_array($object->array_options) && count($object->array_options) > 0) {
		                foreach ($object->array_options as $key => $value) {
		                      $message_admin.='<li>'.$langs->trans($key).' : '.$value.'</li>';
		                }
		            }
		            $message_admin.='</ul>';`

**Comment by wneron** [comment]
Do you know what to do? Thank you

I have found the code that is responsible of the problem;

File: create_ticket.php

Location: \dolibarr\htdocs\public\ticket

Line : 241

` // Send email to TICKET_NOTIFICATION_EMAIL_TO

        $sendto = $conf->global->TICKET_NOTIFICATION_EMAIL_TO;

        if ($sendto)
        {
            $subject = '[' . $conf->global->MAIN_INFO_SOCIETE_NOM . '] ' . $langs->transnoentities('TicketNewEmailSubjectAdmin');
            $message_admin = $langs->transnoentities('TicketNewEmailBodyAdmin', $object->track_id) . "\n\n";
            $message_admin .= '<ul><li>' . $langs->trans('Title') . ' : ' . $object->subject . '</li>';
            $message_admin .= '<li>' . $langs->trans('Type') . ' : ' . $object->type_label . '</li>';
            $message_admin .= '<li>' . $langs->trans('Category') . ' : ' . $object->category_label . '</li>';
            $message_admin .= '<li>' . $langs->trans('Severity') . ' : ' . $object->severity_label . '</li>';
            $message_admin .= '<li>' . $langs->trans('From') . ' : ' . $object->origin_email . '</li>';

            if (is_array($extrafields->attributes[$object->table_element]['label']))
            {
            	foreach($extrafields->attributes[$object->table_element]['label'] as $key => $val)
            	{
            		$enabled = 1;
            		if ($qualified && isset($extrafields->attributes[$object->table_element]['list'][$key]))
            		{
            			$enabled = dol_eval($extrafields->attributes[$object->table_element]['list'][$key], 1);
            		}
            		$perms = 1;
            		if ($perms && isset($extrafields->attributes[$object->table_element]['perms'][$key]))
            		{
            			$perms = dol_eval($extrafields->attributes[$object->table_element]['perms'][$key], 1);
            		}

            		$qualified=true;
            		if (empty($enabled) || $enabled == 2) $qualified = false;
            		if (empty($perms)) $qualified = false;
            		if ($qualified) $message_admin .= '<li>' . $langs->trans($key) . ' : ' . $value . '</li>';
            	}
            }

            $message_admin .= '</ul>';
            $message_admin .= '<p>' . $langs->trans('Message') . ' : <br>' . $object->message . '</p>';
            $message_admin .= '<p><a href="' . dol_buildpath('/ticket/card.php', 2) . '?track_id=' . $object->track_id . '">' . $langs->trans('SeeThisTicketIntomanagementInterface') . '</a></p>';

            $from = $conf->global->MAIN_INFO_SOCIETE_NOM . '<' . $conf->global->TICKET_NOTIFICATION_EMAIL_FROM . '>';
            $replyto = $from;

            $message_admin = dol_nl2br($message_admin);

            if (!empty($conf->global->TICKET_DISABLE_MAIL_AUTOCOPY_TO)) {
                $old_MAIN_MAIL_AUTOCOPY_TO = $conf->global->MAIN_MAIL_AUTOCOPY_TO;
                $conf->global->MAIN_MAIL_AUTOCOPY_TO = '';
            }
            include_once DOL_DOCUMENT_ROOT . '/core/class/CMailFile.class.php';
            $mailfile = new CMailFile($subject, $sendto, $from, $message_admin, $filepath, $mimetype, $filename, $sendtocc, '', $deliveryreceipt, -1);
            if ($mailfile->error || $mailfile->errors) {
                setEventMessages($mailfile->error, $mailfile->errors, 'errors');
            } else {
                $result = $mailfile->sendfile();
            }
            if (!empty($conf->global->TICKET_DISABLE_MAIL_AUTOCOPY_TO)) {
                $conf->global->MAIN_MAIL_AUTOCOPY_TO = $old_MAIN_MAIL_AUTOCOPY_TO;
            }
        }
    }`

**Comment by ksar-ksar** [comment]
Hi,

Can you send a copy of the configuration of these extrafields ?
What type are they ?

Thanks

**Comment by wneron** [comment]
The solution is the code bellow in file "dolibarr\www\dolibarr\htdocs\public\ticket\create_ticket.php"


Add the code bellow and edit to fit your need at line 258 and success ! :-)


`// Send email to TICKET_NOTIFICATION_EMAIL_TO

                $sendto = $conf->global->TICKET_NOTIFICATION_EMAIL_TO;

                if ($sendto)
                {
	                $subject = '[' . $conf->global->MAIN_INFO_SOCIETE_NOM . '] ' . $langs->transnoentities('TicketNewEmailSubjectAdmin');
	                $message_admin = $langs->transnoentities('TicketNewEmailBodyAdmin', $object->track_id) . "\n\n";
	                $message_admin .= '<ul><li>' . $langs->trans('Title') . ' : ' . $object->subject . '</li>';
	                $message_admin .= '<li>' . $langs->trans('Type') . ' : ' . $object->type_label . '</li>';
	                $message_admin .= '<li>' . $langs->trans('Category') . ' : ' . $object->category_label . '</li>';
	                $message_admin .= '<li>' . $langs->trans('Severity') . ' : ' . $object->severity_label . '</li>';
	                $message_admin .= '<li>' . $langs->trans('From') . ' : ' . $object->origin_email . '</li>';
					
					
					//SOLUTION
					$conn = mysqli_connect(localhost,dbuser,password,dbname);
					
					$querry = 'SELECT * FROM llx_ticket_extrafields WHERE fk_object = '. $id;
					$resultat = mysqli_query($conn,$querry);
					
					if ($resultat->num_rows > 0) {
						// output data of each row
						while($row = $resultat->fetch_assoc()) {
							 $message_admin .= "<li>Nom : ". $row['nom'] . "</li><li>Entreprise : ". $row['entreprise'] . "</li><li>Téléphone : ". $row['telephone'] . "</li><li>Poste : ". $row['poste']. "</li>";
						}
					}







	                if (is_array($extrafields->attributes[$object->table_element]['label']))
	                {
	                	foreach($extrafields->attributes[$object->table_element]['label'] as $key => $val)
						{
	               		$enabled = 1;
	                		if ($qualified && isset($extrafields->attributes[$object->table_element]['list'][$key]))
	                		{
	              			$enabled = dol_eval($extrafields->attributes[$object->table_element]['list'][$key], 1);
	                 		}
	                 		$perms = 1;
	                 		if ($perms && isset($extrafields->attributes[$object->table_element]['perms'][$key]))
	                 		{
	                			$perms = dol_eval($extrafields->attributes[$object->table_element]['perms'][$key], 1);
	                		}

	                		$qualified=true;
	                		if (empty($enabled) || $enabled == 2) $qualified = false;
	                		if (empty($perms)) $qualified = false;
	                		if ($qualified) $message_admin .= '';
							// original = if ($qualified) $message_admin .= '<li>' . $langs->trans($key) . ' : ' . $value . '</li>';
	                	}
	                }
`
