### ISSUE TITLE
Social networks not clickable on thirdparty and contact cards

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#12678]
![image](https://user-images.githubusercontent.com/11922840/70526619-48bb8480-1b4a-11ea-8850-ad3c716c1d1d.png)

![image](https://user-images.githubusercontent.com/11922840/70526623-4ce7a200-1b4a-11ea-9be0-edc7262e28f8.png)

**Comment by ksar-ksar** [comment]
Hello,

Version ?

**Comment by RomainDeschamps** [comment]
Hello @ksar-ksar 

Version 11 beta

**Comment by frederic34** [comment]
only skype links where clickable before, we need to enhance dol_print_socialnetworks

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists or have a look in the code at develop?

**Comment by RomainDeschamps** [comment]
> 
> 
> Can you update to v12 and see if the problem persists or have a look in the code at develop?

Hello @egils-consulting 

Exactly the same in V12 and develop.

**Comment by aspangaro** [comment]
I propose this code to add link on social networks : 

https://github.com/Dolibarr/dolibarr/pull/14724

**Comment by RomainDeschamps** [comment]
Hello @aspangaro,

It seems the URL saved in the dictionnary for each social network is not used with your commit

**Comment by frederic34** [comment]
@RomainDeschamps 
https://github.com/Dolibarr/dolibarr/pull/15741

It works on members, contacts, thirdparty and users

**Comment by RomainDeschamps** [comment]
@frederic34  👍🏻 !
