### ISSUE TITLE
No way to configure like the wiki says on module ticket

### ISSUE THREAD

**Issue by eoyarzabal** [Dolibarr/dolibarr#12686]
On module ticket: [https://wiki.dolibarr.org/index.php/Module_Ticket](https://wiki.dolibarr.org/index.php/Module_Ticket) the second image shows more "PARAMS" than the actual on 10.0.1.

The "Restrict to display to tickets assigned to the current user" option is what I need because NOW all the people who has access to read tickets can see all areas.

**Comment by ksar-ksar** [comment]
Hi,

Sorry but I do not see images on the wiki page.

Ticket will anyway evolve a lot on V11 that should be released soon !

**Comment by eoyarzabal** [comment]
Thank you for the reply!
BTW, Is there a way to see the changelog?
Or a way to test V11?

**Comment by atm-maxime** [comment]
Hi ! Changelog is here https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog
To test v11, you can go on dolibarr website, download section, and click the link "Click here to download development snapshot from github"
