### ISSUE TITLE
Turnover invoiced Error Multi-company

### ISSUE THREAD

**Issue by Nicolas90000** [Dolibarr/dolibarr#12688]
# Bug
When editing the Revenue billed if you use the MultiCompagny module and you have more than one company the accumulation is multiplied by the number of companies

## Environment
- **Version**: 10.0.1
- **OS**: UBUNTU 16.04
- **Web server**: Apache
- **PHP**: 7.0.33
- **Database**: MySQL or MariaDB 5.7.26
- **URL(s)**: compta/stats/index.php?leftmenu=accountancy_report&modecompta=BOOKKEEPING
/compta/resultat/index.php?mainmenu=accountancy&leftmenu=accountancy_report

## Reason of the issue
Code references are based on the branch 10.0.

In the file /compta/stats/index.php L.197
$sql.= " AND b.code_journal = aj.code AND aj.nature = 2 **AND aj.entity=".$conf->entity ;**

In the file /compta/resultat/index.php L.819
$sql.= " WHERE b.numero_compte = aa.account_number AND b.entity = ".$conf->entity.**" AND aa.entity = ".$conf->entity;**

**Comment by ksar-ksar** [comment]
Hi,

MultiCompagny is an external module, not supported here.
You need to contact the developer.

**Comment by Nicolas90000** [comment]
Hi

Yes, but the accounting code should take into account the entities


Nicolas

**Comment by hregis** [comment]
@Nicolas90000 
i send a PR to fix this https://github.com/Dolibarr/dolibarr/pull/12695
