### ISSUE TITLE
Thirdpartie selection

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#12687]
# Bug
The user only sees my thirdpartie
I want to add an event from the calendar or new document I can not select thirdparties

## Environment
- **Version**: [10.0.3]
- **OS**: [Debian 9]
- **Web server**: [Apache/2.4.25]
- **PHP**: [7.0.33-0]
- **Database**: [MySQL or MariaDB 5.5.5-10.1.41-MariaDB-0]
- **URL(s)**: [/comm/action/index.php?idmenu=32475&mainmenu=agenda&leftmenu=]

## Expected and actual behavior
Have the list of my thirdpartie to create the event or new document.

## Steps to reproduce the behavior
Go on agenda or document with the right to see only his thirdpartie.
If I add the event or document of the thirdpartie form it works

Option Thirdpartie:
Displays the customer / vendor address information (pick list or drop-down list)
Third parties will appear with the following name format: "The Big Company corp. - 21, rue du saut 123456 Big town - USA" au lieu de "The Big Company corp".

Sécurity
See only my Third parties

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

Erreur afficher

`Dolibarr a détecté une erreur technique.Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):Date: 20191211082541Dolibarr: 10.0.3Niveau de fonctionnalités: 0PHP: 7.0.33-0+deb9u6Server: Apache/2.4.25 (Debian)OS: Linux srv 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36Url sollicitée: /comm/action/index.php?idmenu=32475&mainmenu=agenda&leftmenu=Referer: http://192.168.1.20/index.php?mainmenu=homeGestionnaire de menu: eldy_menu.phpModules/Applications: user, api, listes, clicktodial, socialnetworks, stock, expedition, propal, product, blockedlog, ficheinter, mailing, categorie, agenda, barcode, zenfusionmaps, commande, ecm, facture, fournisseur, holiday, societe, service, variants, resource, bookmark, import, export, fckeditor, modulebuilder, quicknotes, workflow, notification, ticketType gestionnaire de base de données: mysqliRequête dernier accès en base en erreur: SELECT s.rowid, s.nom as name, s.name_alias, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.address, s.zip, s.town, dictp.code as country_code FROM llx_societe as s, llx_societe_commerciaux as sc LEFT OUTER JOIN llx_c_country as dictp ON dictp.rowid=s.fk_pays WHERE s.entity IN (1) AND s.rowid = sc.fk_soc AND sc.fk_user = 39 ORDER BY nom ASCCode retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELDInformation sur le dernier accès en base en erreur: Unknown column 's.fk_pays' in 'on clause`
--

**Comment by bb2a** [comment]
Resolv in V11

**Comment by atm-maxime** [comment]
Hi @bb2a .
I think this issue has been solved in V11 here : #14940

**Comment by BB2A-Anthony** [comment]
> Hi @bb2a .
> I think this issue has been solved in V11 here : #14940

@atm-maxime Ok
