### ISSUE TITLE
parameters['currentcontext'] always 'main' if  hook is set to 'all'

### ISSUE THREAD

**Issue by elarifr** [Dolibarr/dolibarr#12717]
in dolibar 10.0.4
i have created a module with builder and mod i set hook to 'all'

in the class\action i hook to
public function addMoreActionsButtons($parameters, &$object, &$action, $hookmanager)

but when i go to any card page  the value of parameters[currentcontext] is always 'main'
parameters Array ( [context] => thirdpartydao:fileslib:searchform:leftblock:toprightmenu:main:propalcard:globalcard [currentcontext] => main ) 

if in mod i define all hooks and remove 'all'
//'all',
'actioncard', 'contactcard', 'contractcard', 'deliverycard', 'expeditioncard', 'invoicecard', 'invoicesuppliercard', 'ordercard', 'ordersuppliercard',
'propalcard', 'productcard', 'stockproductcard', 'supplier_proposalcard', 'suppliercard', 'thirdpartycard',

the value of currentcontxt is correct (propalcard here)
parameters Array ( [context] => thirdpartydao:fileslib:searchform:leftblock:toprightmenu:main:propalcard:globalcard [currentcontext] => propalcard ) 

## Expected and actual behavior
parameters[currentcontext] should not be the real context where the hook is called from ? 
 
did i misunderstand the use of parameters[currentcontext] ?

**Comment by Daviid-P** [comment]
I want to bring this up again, in my case I have my module's hook contexts set up like this.

![image](https://user-images.githubusercontent.com/7734808/214820583-c0d79505-d25a-4e2f-953d-219594d2f415.png)

And when the debugger reaches this line https://github.com/Dolibarr/dolibarr/blob/d36acc63dd68aa2d8382ab4044d848a87ed46456/htdocs/accountancy/bookkeeping/list.php#L1165

it seems like currentcontext is set to `main`, I thought I could just press F5 and the debugger would stop again there and current context would be `bookkeepinglist`

![image](https://user-images.githubusercontent.com/7734808/214820887-64fa5016-d481-462f-8660-0b2c28c9aae1.png)


Should hooks execute once per context? Should the current context be set to the most specific?

@eldy
