### ISSUE TITLE
Rest API Product Variante

### ISSUE THREAD

**Issue by eoxia-jimmy** [Dolibarr/dolibarr#12741]
# Feature Request

Can we get/post/put product variante with Rest API ?

I didn't see /variants/class/api_product_variant.class.php

can i implemented the route by myself ?

**Comment by zigastegu** [comment]
Maybe this?
![image](https://user-images.githubusercontent.com/1379063/77491470-253cf100-6e3e-11ea-8f12-b65c5e0fad0e.png)

**Comment by dpriskorn** [comment]
Its already implemented it seems. Closing
