### ISSUE TITLE
Bug: wrong doctemplates path for supplier proposals

### ISSUE THREAD

**Issue by dnutan** [Dolibarr/dolibarr#12756]
# Bug
Wrong suppliers proposals doctemplates path constant declaration

## Environment
- **Version**: 10.0.4
- **OS**: CentOS 7.7.1908
- **Web server**: Apache/2.4.6 (CentOS)
- **PHP**: 7.2.24
- **Database**: 5.5.64-MariaDB
- **URL(s)**: /admin/supplier_proposal.php

## Expected and actual behavior
* **Expected:** On **Price requests suppliers documents models** section, default **ODT templates** field value shall be set to `DOL_DATA_ROOT/doctemplates/supplier_proposals`
* **Actual:** default **ODT templates** field value is set to `DOL_DATA_ROOT/doctemplates/supplier_proposal`. 
Warning message: `Directory /var/lib/dolibarr/documents/doctemplates/supplier_proposal not found (Bad path, wrong permissions or access denied by PHP openbasedir or safe_mode parameter)`

## Steps to reproduce the behavior
1. Enable **Vendor Commercial Proposals** module
2. Access module's **Setup**: **ODT templates** pre-filled with wrong (misspelled) path

## Suggested solution
* **Cause**: name mismatch between directory creation from docs array (at [install step1](https://github.com/Dolibarr/dolibarr/blob/f85899742b1536ef8455bd9ab0f82ae6702dc9dd/htdocs/install/step1.php#L488)) and hard-coded value on [modSupplierProposal.class.php](https://github.com/Dolibarr/dolibarr/blob/b79831ec39c7178902131aed7dc36b3ca9e153ff/htdocs/core/modules/modSupplierProposal.class.php#L96).
* **Suggested solution:** fix misspelled path on [modSupplierProposal.class.php](https://github.com/Dolibarr/dolibarr/blob/9.0/htdocs/core/modules/modSupplierProposal.class.php#L95), replacing `/supplier_proposal` with `/supplier_proposals`. From dolibarr 9.0 onward, according to the directory name change introduced at [/install/step1.php](https://github.com/Dolibarr/dolibarr/blob/9.0/htdocs/install/step1.php#L487)
* **Considerations**: probably only suitable for new installs.

**Comment by atm-maxime** [comment]
I don't see the names mismatching, in both the links you propose we have supplier_proposal without an "s". The "supplier_proposals" value is only used in install step 1 because that's where the doctemplates source are (htdocs/doctemplates/supplier_proposals). Maybe it has already been fixed but your installation has been done when it wasn't.

**Comment by dnutan** [comment]
Thanks for looking into it. It was a new 10.0.4 install. Tried again with a new clean install from develop branch (12.0.0-alpha) and had the same problem:
![odt templates for supplier proposals](https://user-images.githubusercontent.com/15559754/71556011-18715280-2a33-11ea-8400-f69488c63a5e.png)

`DOL_DATA_ROOT/doctemplates/supplier_proposal/` does not exist.
`DOL_DATA_ROOT/doctemplates/supplier_proposals/` exists and has `template_supplier_proposal.odt` (created/copied from install step1), but module code points to directory path without `s`.

Module code is supposed to copy ODT template file from `install` doctemplates to matching dir in `documents` but neither source nor destination directory exist:
https://github.com/Dolibarr/dolibarr/blob/b79831ec39c7178902131aed7dc36b3ca9e153ff/htdocs/core/modules/modSupplierProposal.class.php#L218

On other modules I perceive similar code discrepancy, but could be me misinterpreting how it works and the purpose of directories (ex. `/doctemplates/shipment` vs `/doctemplates/shipments` ...) as I'm not familiar with the internals. Maybe what I interpret as code duplicity/discrepancy is there to support multiple versions of dolibarr.

**Comment by dnutan** [comment]
Thanks for the fix. Did a code search and maybe [modReception.class.php](https://github.com/Dolibarr/dolibarr/blob/66a288a343f8a98cb33a2a209c0347c8c3687cad/htdocs/core/modules/modReception.class.php#L254) and [modStock.class.php](https://github.com/Dolibarr/dolibarr/blob/b79831ec39c7178902131aed7dc36b3ca9e153ff/htdocs/core/modules/modStock.class.php#L374) are affected as well.
