### ISSUE TITLE
Major Bug on 10.0.5 in html.formmargin.php

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#12760]
# Bug
Major Bug on 10.0.5 in html.formmargin.php introduced in commit 538921f47977c56cbf9aadbdb87bc60b705f6f5a 

Reported on french [forum](https://www.dolibarr.fr/forum/t/fatal-error-class-facture-not-found-in-html-formmargin-class-php-on-line-101/31383/2)

## Environment
- **Version**: [*10.0.5*]

**Comment by ptibogxiv** [comment]
Same bug on order card

**Comment by fappels** [comment]
Also reported on [dolibarr.org forum](https://www.dolibarr.org/forum/t/upgrade-to-10-0-5-missing-line-items-sales-orders/18306)

**Comment by ptibogxiv** [comment]
fix in https://github.com/Dolibarr/dolibarr/pull/12763

**Comment by fappels** [comment]
@ptibogxiv just noticed already PR made by @ATM-Marc https://github.com/Dolibarr/dolibarr/pull/12755

**Comment by ptibogxiv** [comment]
> @ptibogxiv just noticed already PR made by @ATM-Marc #12755

In this case quote PR of the fix 😉

**Comment by atm-maxime** [comment]
#12765

**Comment by fappels** [comment]
Fixed by https://github.com/Dolibarr/dolibarr/pull/12755
@eldy don't think merge https://github.com/Dolibarr/dolibarr/pull/12751 was necessary, no need to require facture class for proposals and orders. Hope 10.0.6 will be released soon, forums are spamming bug report.
