### ISSUE TITLE
TimeSheet Report not working

### ISSUE THREAD

**Issue by scarcamo-eyg** [Dolibarr/dolibarr#12766]
When trying to see a report from timesheet module per project or per user, appears 
"This website is currently temporarly offline. This may be due to a maintenance operation. Current status of operation are on next line" message

**Comment by atm-maxime** [comment]
Without any further information, this is gonna be hard to tell if this is really a Dolibarr issue or if it's related to an external module or your own Dolibarr environment... Did you try forums to ask for help before declaring this a Dolibarr issue ?

**Comment by scarcamo-eyg** [comment]
Hi, thank four your comments, It is a new installation of Dolibarr 10.0.4, I will do a workaround again to check that.

**Comment by scarcamo-eyg** [comment]
After upgrade to 10.0.6 timesheet report works fine.
Closing the issue.
Thanks
