### ISSUE TITLE
Ticket Public ID with choosen format

### ISSUE THREAD

**Issue by scarcamo-eyg** [Dolibarr/dolibarr#12767]
The public ticket ID is always an random string like "gmxex1axoole3jp3", would be great to be able to choose the proper format, for example; only numbers in format 123456789, to customer could get in a easy way the info related to the ticket

**Comment by manu-971** [comment]
The ref is already an easy way for customers to identify a ticket. But until now the ref is not very visible for customers. PR #12762 add the ref in the subject mail and in the notification message when a customer create a ticket.

**Comment by scarcamo-eyg** [comment]
Thanks you.

**Comment by atm-maxime** [comment]
@scarcamo-eyg don't forget to close issues when it's ok for you
