### ISSUE TITLE
After Installing dollibar Successfully I can not log in

### ISSUE THREAD

**Issue by adnredwan77** [Dolibarr/dolibarr#12779]
# No Default Credentials for first use
[*I've followed the instructions to install dollibar, and it installed successfully , but no default credentials created, the llx_user table is empty , so where can I found the default login credentials?*]

## windows shared hosting server
- **Version**: [* Dolibarr 12.0.0-alpha*]
- **OS**: [*windws server shared hosting*]
- **Web server**: [*iis*]
- **PHP**: [*PHP 7.3*]
- **Database**: [*Maria DB V10.3.17*]
- **URL(s)**: [*dollibarr.sanadc.com*]

**Comment by adnredwan77** [comment]
I'm trying to install dolibarr 11.0 after finishing installation I get the error 404 page not found
and not redirected to the login screen
so I can not find default credentials

**Comment by adnredwan77** [comment]
I've entered it form the database and it works.

**Comment by atm-maxime** [comment]
@adnredwan77 the last step of installation process is to choose the first login / pass to create. If you couldn't go there, it's normal you don't have a first user in the table. The real issue is the 404 error you got
