### ISSUE TITLE
Xls import template file not found

### ISSUE THREAD

**Issue by lesnake** [Dolibarr/dolibarr#12785]
Attempting to download accounting import xlsx template file results into web browser message "file not found".
The following page contains two lines : one for csv, one for xlsx :
http://localhost/dolibarr/imports/import.php?step=2&datatoimport=accounting_2&excludefirstline=1&separator=%2C&enclosure=%22

Csv file is ok.
xlsx is not found with link : 
http://localhost/dolibarr/imports/emptyexample.php?format=xlsx&datatoimport=accounting_2&excludefirstline=1&separator=,&enclosure="

Dolibarr 10.0.5, ubuntu 19.10 x64, french (might be important because csv file name contains french words)

**Comment by StephaneLesage** [comment]
Same here with Dolibarr 12.0.1, debian, french.

**Comment by StephaneLesage** [comment]
If found the reason: xlsx files need the php zip module.

@eldy 
Please add explicit message on the export pages.
Please also add the dependency in the linux packages (at least it's missing on debian).

**Comment by ksar-ksar** [comment]
A FIX has been posted, could you check if it is ok now ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
