### ISSUE TITLE
Bug: Gestion des marges

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#12795]
# Bug

## Environment
- **Version**: 10.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.13
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL**: /admin/modules.php?mode=common&page_y=973

## Report

Le module de gestion des marges entraine l'erreur de script si activé.

**Comment by atm-maxime** [comment]
Already fixed #12760
And #12793 duplicate
Could you please close your 3 identical issues ?
