### ISSUE TITLE
Bug: Propal

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#12794]
# Bug

## Environment
- **Version**: 10.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.13
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL**: /comm/propal/card.php?id=74

## Report

Fatal error: Uncaught Error: Class 'Facture' not found in /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/core/class/html.formmargin.class.php:101 Stack trace: #0 /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/core/class/html.formmargin.class.php(206): FormMargin->getMarginInfosArray(Object(Propal), false) #1 /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/comm/propal/card.php(2384): FormMargin->displayMarginInfos(Object(Propal)) #2 {main} thrown in /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/core/class/html.formmargin.class.php on line 101

**Comment by atm-maxime** [comment]
Already fixed #12760
And #12793 duplicate
