### ISSUE TITLE
Multicompany c'est pour quand en Natif!?

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#12801]
C'est pour quand la gestion des multicompany en natif? car la grande majorité des PME des années 2000 optent à séparer leurs locaux sous formes de filaires avec des statuts juridiques indépendants pour des fins fiscaux et comptable que gérer toutes les filaires avec le même statut juridique et une centralisation de stock et de comptabilité. Cela évitera aux sociétés les conséquences des fuites/risques/sanctions fiscaux très lourdes en cas d'erreur humain ou logiciel....
Un ERP est généralement fait pour cet objectif!

**Comment by hregis** [comment]
@wdammak 
et vous me donner combien pour ça ?

**Comment by mapiolca** [comment]
Achetez le module, et ainsi vous l’aurez, ça permettra également de soutenir son développeur.

**Comment by wdammak** [comment]
@mapiolca pour l'instant je n'ai adopté dolibarr à aucune société car il ne répond pas encore à très nombreux besoins et je suis qu'un simple supporteur!
Je ne demande pas que vous sacrifiez votre travail mais je m'adresse au core du projet et le besoin essentiel de cette fonctionnalité! dans un ERP! (En tout cas, il doit y avoir plusieurs options et pas qu'un seul!)
Si pour tester un ERP, il faut installer une 10ène de module ça n'encourage pas de l'adopter dans les multicompany car la stabilité de l'ERP ne dépend plus de son écosystème mais ...
Quant au module, que je ne connais pas encore, je pourrais le soutenir! Si vous me permettez, pensez à opter pour des couches payantes en proposant le core en open, cela va multiplier(surtout en **multi**company!) les opportunités d'avoir des clients que détenir une solution pour un cercle fermé!  Par expérience, vous allez avoir beaucoup de demande de support et de développement spécifique comme le reporting, les statistiques, forcasting, BI, ETL, l'inter-reporting,.... 
Bref, j'ai fait une simple demande au core de dolibarr et ça reste qu'un avis personnel! 
Cordialement

**Comment by mapiolca** [comment]
@wdammak , je comprend, malheureusement je ne suis pas sûr que le core de Dolibarr aie pour objectif de développer et couvrir tous les besoins, la plus part des contributeurs sont des utilisateurs indépendants, de même que ce qui développent des modules. Il faudra du temps pour que l'ERP couvre tous les besoins que vous présentez. Le core de Dolibarr est entièrement gratuit, et propose une base solide pour les utilisateurs lambdas. Après pour des besoins spécifiques ou qui peuvent être à terme intégrés au core, je invite à vous adresser à des développeurs indépendants qui vont pouvoir, en suivant votre cahier des charges, vous développer une solution qui répondra parfaitement à vos besoins. Cela se fait souvent, le dévelopeur vous fait une remise ou un appel à soutien, afin d'amortir les frais de développement et rendre le code open-source. M. Houssin ( @hregis ) qui développe le module Multicompany, et s'échine à rendre son intégration la plus limpide possible, se fera certainement un plaisir d'étudier votre besoin et y répondre en fonction.

**Comment by dolibarr95** [comment]
Hello
If the author is ok we could create a crowdfunding 😇
https://www.dolibarr.fr/forum/t/module-multi-activite/8228/19

**Comment by hregis** [comment]
@wdammak @dolibarr95 @mapiolca 

à l'origine le Multicompany avait été développé directement dans le cœur de Dolibarr, puis, par soucis de simplicité, Laurent m'avait demandé d'en faire un module à part.
Pour le moment c'est très bien comme ça, de plus ça permet de tester ou d'améliorer les différents hook présent dans Dolibarr.
L'accès au dépôt git du module Multicompany est exclusivement réservé aux développeurs en me faisant une demande.
Vous pouvez me contacter par téléphone pour en discuter.

**Comment by dolibarr95** [comment]
Hi bot !
