### ISSUE TITLE
Stuck on login screen

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#12800]
# Bug
When I come back to the tab with dolibarr, I have to reconnect. After entering credentials, the login screen come back again, without message.
At this step, if I delete the previous URL to access the dolibarr root, home page is displyed.
## Environment
- **Version**: develop (v11.0.0 alpha)
- **OS**: Mageia 7
- **Web server**: [*Webserver type and version*]
- **PHP**: 7.3
- **URL(s)**: for example after the login http://localhost/dolibarr-test/htdocs/compta/facture/card.php?action=create&leftmenu=&mainmenu=home displays again the login screen.

## Expected and actual behavior
Previoully opened page should be displayed.
Login screen is however displayed

**Comment by papoteur-mga** [comment]
I have updated to actual 11.0.0 branch and this is still the case.
To reproduce:
Open a page in Dolibarr.
Stay with the opened for a long time, for example one day.
Update the page, login screen is displyed.
Enter credentials.
Still login screen.

**Comment by papoteur-mga** [comment]
When finally accessing to the home page, I got a warning:
Unset POST by CSRF protection in main.inc.php (POST for this token was already done or was done by a not allowed web page with a wrong token).
$_SERVER[REQUEST_URI] = /dolibarr-test/htdocs/admin/defaultvalues.php?mainmenu=home $_SERVER[REQUEST_METHOD] = POST GETPOST(token) = 97b1a0b2933e88f825a2ea4cdbc3079b $_SESSION[token] =

**Comment by choybe** [comment]
similar to me after update 11.0

**Comment by choybe** [comment]
setting in htdocs/conf to $dolibarr_nocsrfcheck='1';
solved my problem for now , but I would prefer to return to my old config $dolibarr_nocsrfcheck='0';
An other strange observation I made on DB 11.0 with $dolibarr_nocsrfcheck='0'; behaves difefrent in firefox and chromium - with chromium I can still get access with $dolibarr_nocsrfcheck='0'; in firtefox not.   Only when set htdocs/conf to $dolibarr_nocsrfcheck='1'; all works fine again.

**Comment by homer8173** [comment]
try in a private navigation on firefox.
If it work, you can clean your cache

**Comment by papoteur-mga** [comment]
It seems to work.
Thank for your tip. Even with years of using this application, I can be caught with such a behaviour :/
