### ISSUE TITLE
REST API Thirdparties - Id commercial

### ISSUE THREAD

**Issue by manugre** [Dolibarr/dolibarr#12803]
REST API Thirdparties - Id commercial 
API allawys give NULL even if it should not

https://www.dolibarr.fr/forum/t/rest-api-thirdparties-id-commercial/28770

**Comment by eldy** [comment]
This properties commercial_id will never be filled because there is several sales representative for one thirdparty. To get sales representative, you must use the API getSalesRepresentatives() availabel with v11 (released in january 2020)
