### ISSUE TITLE
Set multiprice data via REST API

### ISSUE THREAD

**Issue by SamKTaylor** [Dolibarr/dolibarr#12812]
# Feature Request
It seems that you are currently unable to set multiprice data via the REST API.

## Use case
automating price updates

## Suggested implementation
Check for key in request data and set multiprice data from it, something along the lines of 

        foreach ($request_data as $field => $value) {
            if($key == "multiprices"){
                $this->product->multiprice = json_decode($value);
            }else{
                $this->product->$field = $value;
           }
        }

in "/htdocs/product/class/api_products.class.php" on line 248
Would need checks to see if the feature is enabled that I am not familiar with

## Suggested steps
do the thing, test it works

**Comment by dpriskorn** [comment]
Hi. I have some python code that can do this if you are interested. Feel free to contact me at egils@riseup.net

**Comment by dpriskorn** [comment]
I currently do this via SQL
```
def insert_multiprice(
        product_id, brutto_price1, brutto_price2, vat,
):
    conn = db_connect()
    # Create a cursor object
    cur = conn.cursor()
    query = sql.SQL("INSERT INTO public.llx_product_price " +
                    "(fk_product, price, price_ttc, tva_tx, " +
                    "date_price, price_base_type, price_level," +
                    "fk_user_author) " +
                    "VALUES (%s,%s,%s,%s,now(),'TTC',%s,1)")
    # exec for each pricelevel:
    cur.execute(query, (
        product_id, int(brutto_price1) / 1.25, brutto_price1, vat, 1
    ))
    cur.execute(query, (
        product_id, int(brutto_price2) / 1.25, brutto_price2, vat, 2
    ))
    cur.close()
    try:
        conn.commit()
    except ConnectionError:
        print("Could not commit to db")
    print("Multiprice added.")
    db_disconnect(conn)
```

**Comment by ruemmlernet** [comment]
[**API: create and update product multiprices** #18080](https://github.com/Dolibarr/dolibarr/issues/18080)
