### ISSUE TITLE
extrafields API - get possible values for 'sellist' fields

### ISSUE THREAD

**Issue by dvasseur** [Dolibarr/dolibarr#12813]
# Extrafields API - get possible values for 'sellist' fields, and maybe others types

I'm using the /setup/extrafields API to retrieve an extra fields list and would like to also retrieve the possible values for each field.

Right now, API result is:
```
["myfield"]=>
  ["type"]=> "sellist"
  ["param"]=>
    ["options"]=>
      ["table_name:label_field_name:key_field_name"]=>NULL
```
My goal is to have this:
```
["myfield"]=>
  ["type"]=>"sellist"
  ["param"]=>
    ["options"]=>
      ["table_name:label_field_name:key_field_name"]=> {
        ["1", '"Value1"],
        ["2", '"Value2"],
        ["3", '"Value3"]
      }
```
(probably not exactly like this but you've got the idea...)

I've searched a little bit into the code and found only 2 functions which build this list: 

 * https://github.com/Dolibarr/dolibarr/blob/57bbac2015466023fe0b5a6de6d91d6c5e449310/htdocs/core/class/commonobject.class.php#L5575
 * https://github.com/Dolibarr/dolibarr/blob/20b52db5b8112b025116c6f2b81f1bab5061723a/htdocs/core/class/extrafields.class.php#L970

But the result is sent as HTML content and, even if I don't really know which params I should pass to this function, parsing HTML to extract the plain values looks like a bad idea.

Is there a better way to to this ? I could create my own parser in the API file but using an existing one would be better !

**Comment by dpriskorn** [comment]
Seems like a good idea to me, if I understood you correctly. Better than making an endpoint/extrafields on every other endpoint, which means editing lots of files, keeping it in one place instead.

I suggest you create a new function in dolibarr/htdocs/core/class/extrafields.class.php doing what you want and send a pull request. 
I would like the endpoint to return the value for a key for a given row in the extrafields:
Say I want to insert into the extrafield sello_id on llx_commande_extrafields where fk_account=1:
I then first GET to find out if there is already a value:
/extrafields/{endpoint}/{extrafield-name}/{id}
say /extrafields/orders/sello_id/1 and get
Response<404>
I then POST this to /extrafields/orders/sello_id/1:
{
"value": 12345,
}
And get Response<200>

The endpoint needs to map from our endpoints to the table names:
thirdparties -> societe,
orders -> commande,
...

(in case anyone wonders what Sello is: https://sello.io/)
