### ISSUE TITLE
External modules are not being deployed

### ISSUE THREAD

**Issue by Ahuahuachi** [Dolibarr/dolibarr#12820]
# Bug
When using the form to send and deploy an external app/module, the following error shows up: "The module package seems to have a wrong format.
Dir not found: /xxx/xxx/xxx/dolibarr/documents/admin/temp/module_[modulename]-1.0.dir/[modulename]
/xxx/xxx/xxx/dolibarr/documents/admin/temp/module_[modulename]-1.0.dir/htdocs/[modulename]"

Edit: The external module was compiled by the Module Builder module

## Environment
- **Version**: 10.0.5, 10.0.6
- **OS**: Ubuntu 19.10 and Linux Webhosting
- **Web server**: PHP 7.3.11-0ubuntu0.19.10.1 Development Server, Apache/2.4.39
- **PHP**: 7.3.11-0ubuntu0.19.10.1, 7.3.3
- **Database**: MySQL 8.0.18-0ubuntu0.19.10.1, MySQL or MariaDB 5.5.61-38.13-log
- **URL(s)**: htdocs/admin/modules.php

## Expected and actual behavior
Upload and deployment of external module

## Steps to reproduce the behavior
1. Go to Setup->Modules/Applications->Deploy/install external app/module
2. Select the zip file of the module
3. Hit send

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Captura de 2020-01-08 13:52:41](https://user-images.githubusercontent.com/8353891/72011758-1e7be600-3220-11ea-8cef-8ea625d4e19b.png)

**Comment by eldy** [comment]
Can you provide the tree we can find inside the zip of your module. Does your module follow this rules:
https://wiki.dolibarr.org/index.php/Modules_-_Packaging_rules_and_Dolistore_validation_rules

**Comment by Ahuahuachi** [comment]
I don't see anything out of the packaging rules. I think i'm following everything right.
This is the tree structure of the zip file:
![image](https://user-images.githubusercontent.com/8353891/72376040-de5eac80-36d2-11ea-9826-4f9e8d6c3f98.png)

**Comment by eldy** [comment]
Try to introduce a directory with the name of the module at the root of the zip and all your directories on your screenshot must be inside this directory.

**Comment by Ahuahuachi** [comment]
Thanks @eldy, it worked. But then I think the bug is in the Module Builder module because the zip file was compiled by it.

**Comment by eldy** [comment]
Right.
I fixed it for 10.0.7 and higher.
