### ISSUE TITLE
Move to Framework

### ISSUE THREAD

**Issue by FlorianPaumier** [Dolibarr/dolibarr#12825]
Bonjour, 
Je me demandais si un passage progressif vers un framework (symfony 4 / laravel 6)

## Use case
Utilisation des systèmes de cloud ou facilitation de la debug. 

## Suggested steps
 - Voir si cela est possible
 - Combien de temps
 - Comment faire le transfert

**Comment by ksar-ksar** [comment]
Hi,

A good start : https://github.com/Dolibarr/dolibarr/issues/10054
