### ISSUE TITLE
Import of product prices does not contain all fields, When import values greater than 1000 system convert it to 1 and round it

### ISSUE THREAD

**Issue by EddTamuse** [Dolibarr/dolibarr#12826]
# Bug
[*Import of product prices does not contain all fields*]

## Environment
- **Version**: [*9.0.1 but maybe older and newer versions*]
- **OS**: [*Windows Server 2016*]
- **Web server**: [*XAMPP 3.2.2*]
- **PHP**: [*5.6.34*]
- **Database**: [*10.1.37-MariaDB*]
- **URL(s)**: [*"dolibarpath/htdocs/imports/import.php?step=2&datatoimport=produit_supplierprices&format=csv&excludefirstline=1&separator=%2C&enclosure="
"dolibarpath/htdocs/product/fournisseurs.php"*]

## Expected and actual behavior
[*Expected:
-Fill csv file, upload from Import and get all the data loaded into Buying prices tab
-When system detects thousands for USA configuration(decimal point instead comma), the unit price is divided and rounded.
-"Applied prices from" should be auto generated with import date 
-An event should be generated by the system to indicate who modified the price and when with import tool or via product card.

Actual:
-Fill csv file, upload from Import and get some data loaded into Buying prices tab, other data is not loaded, because there is no field to recognize by the system.
-When system detects thousands for USA configuration(decimal point instead comma), the price keeps as imported, also must be imported to "Unit price (net) (currency)" instead "Unit price (net)" the last one must be generated automatically.
-"Applied prices from" keeps null
-No events in product card
*]

## Steps to reproduce the behavior
[*From Tools->New Import->Product or Service->Supplier prices (of products or services) the import file does not contain all necessary fields to make the importation
-Tax Rate code (sp.default_vat_code) is not necessary but is in the template
-"Currency" is not in template file and is required
-"Delivery delay in days" is not in template file and is required
-"Vendor reputation" is not in template file and is required
-"Applied prices from" is not in template file and is required *]

## Reference files
[*![massiveimportproductprices](https://user-images.githubusercontent.com/38297997/72082303-3190c380-32bd-11ea-99ed-365348b17aaa.png)
All the arrows point to a missing or wrong value in the product card->buying prices tab

Attached an example of import with the issue
[importexample.zip](https://github.com/Dolibarr/dolibarr/files/4041224/importexample.zip)*]

**Comment by john-botella** [comment]
Hi

Can you give the exact price value stored in the import file (including space, symbole comas...) ?

It can be a number formatting issue because not all countries use same thousand or decimal separators.

**Comment by ksar-ksar** [comment]
Hi,

Issue is still present ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
