### ISSUE TITLE
lower than symbols followed by line breaks result in missing text in public notes field on PDFs

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#12838]
# Bug
If you have lower than symbols (&lt;) in a public notes field in a document such as a proposal, invoice, etc, anything between the lower than symbol and the end of the line does not appear in the generated PDF file despite being valid HTML

## Environment
- **Version**: 9.0.4. Issue persists in available online demo at https://demo.dolibarr.org/
- **OS**: Ubuntu 18.04
- **Web server**: apache
- **PHP**: 7.2.19
- **Database**: MySQL 5.6.43
- **URL(s)**: /comm/propal/card.php, 

## Expected and actual behavior
Expected behavior: Properly escaped lower than (<, escaped as & lt ;) in notes fields should appear as normal characters in PDF files, and not cause HTML parsing to fail.
Actual behavior: Placing a properly escaped lower than symbol in the public notes field followed more text and then a line break (&lt; br /&gt; ) causes an issue where nothing between the lower than symbol and line break (both included) appear in the PDF. This is most likely caused by the text being considered invalid html. However, the text is valid HTML and is properly displayed in the notes tab.

## Steps to reproduce the behavior

1. Create a proposal or invoice (other documents are likely affected, but these two have been shown to trigger the bug
2. In the notes field, go to source, and put the following text 
```
Lorem ipsum &lt; dolor sit amet,<br />
consectetur adipiscing elit, sed do eiusmod tempor incididunt
```
This was generated with the WYSIWYG editor, not typed manually, but it's given as the html source to make it easier to reproduce
3. Generate the pdf. Note that the lower than symbol is missing, and so are the words dolor sit amet and the line break

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Screenshot - 130120 - 12:21:31](https://user-images.githubusercontent.com/55888212/72252459-90c53f80-35ff-11ea-8a20-cc4668896f1d.png)
![Screenshot - 130120 - 12:22:21](https://user-images.githubusercontent.com/55888212/72252468-96bb2080-35ff-11ea-9905-bf9a0abc12d3.png)
![Screenshot - 130120 - 12:23:02](https://user-images.githubusercontent.com/55888212/72252478-9a4ea780-35ff-11ea-9bf4-ee696e2deae0.png)
[(PROV492).pdf](https://github.com/Dolibarr/dolibarr/files/4053288/PROV492.pdf)

**Comment by eldy** [comment]
I can't reproduce on demo.dolibarr.org
Can you provide the url of page where we can see the problem with < char ?

**Comment by ToniTen** [comment]
The screenshots and the generated PDF are from this document on demo.dolibarr.org

https://demo.dolibarr.org/comm/propal/card.php?id=492

I made sure to reproduce everything I found on the demo site since it should make it easier to identify the root cause

EDIT: I just realized that despite me trying to use either the actual character '<' and the HTML escape '& lt ;' (without spaces) separately in the original post, html outside of code tags was converted for display, making it slightly less convenient to read. It should be obvious what I mean, however.
