### ISSUE TITLE
can not get the customer name on Receipt using takepos 

### ISSUE THREAD

**Issue by kaushalbjoshi** [Dolibarr/dolibarr#12836]
using the latest version of dolibarr ----- 10.0.6 
senarion 

open take pos terminal --- 
add a product to sell --
select the customer from the customer list ---
take payment ---
print receipt ---- there is no customer name in receipt 

while if i go to billing and payment and pull a pdf recipt --- it show every thing 

can there be a parameter that can be added to recipt.php to get the name of customer on recipt 

 on header parameter ----
__MYCOMPANY_FULLADDRESS__ ------- give the full address 
__THIRDPARTY_NAME__   this print as is  --- have used all combination of substitution-variables and parser listed and can find from doli wiki ---

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by ksar-ksar** [comment]
Hi,

No answer on the last question.

I close it, you can re-open if the problem persist
