### ISSUE TITLE
product price import error "Field ‹ tva_tx › doesn’t have a default value"

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#12831]
# Bug
When you try to import some product price you receive this answer "Field ‹ tva_tx › doesn’t have a default value"

## Environment
- **Version**: All Dolibarr version until 8.0.4

## Explanations
In the database, for the table "llx_product_price" the field "tva_tx" has no default value and does not allow a null value => hence the SQL error return because this field is not asked therefore not informed.

## Proposed solution
In the file "…/htdocs/core/modules/modProduct.class.php" add a new line after 672 with this `'pr.tva_tx'=>'PriceLevelVATRate',`
Then, the tva_key field appears again, so it can be filled.

**Comment by eldy** [comment]
A fix was done for v11 (default value is set to 0) with
ALTER TABLE llx_product_price MODIFY COLUMN tva_tx double(6,3) DEFAULT 0 NOT NULL;

**Comment by hasse-basse** [comment]
Same problem on 16.0.3. I tried to run` ALTER TABLE llx_product_price MODIFY COLUMN tva_tx double(6,3) DEFAULT 0 NOT NULL;
`
but it didn't change anything.

**Comment by hasse-basse** [comment]
I'm on MariaDB.

**Comment by hasse-basse** [comment]
USER ERROR.

Keep it closed
