### ISSUE TITLE
Bank journal issue 

### ISSUE THREAD

**Issue by yorkhood** [Dolibarr/dolibarr#12833]
#12066 Bug
[*Short description*]

## Environment
- **Version**: 10.0.6
- **OS**: CentOS8
- **Web server**: Apache/2.4.37 (centos)
- **PHP**: PHP 7.2.11 (cli)
- **Database**: mysql 8.0.17
- **URL(s)**: /accountancy/journal/bankjournal.php?mainmenu=accountancy&leftmenu=accountancy_journal&id_journal=3

## Steps to reproduce the behavior
1)  Go to  Bank|Cash 
2) Add two financial account  Bank_A and Bank_B 
3) Make an "Internal Transfer" from Bank_A to Bank_B 
4) Go to Accounting 
5) Go to Bank journal 

![image](https://user-images.githubusercontent.com/26512905/72203673-afb1bd80-34a9-11ea-9273-77e64d43707c.png)

**Comment by aspangaro** [comment]
Hello,

You simply did not fill in the clearing account in the default account configuration in the accounting module.

**Comment by eldy** [comment]
The error message could be modified to be more clear in such a case, to point to the setup page.
