### ISSUE TITLE
Send mail from contact card no registered event (Envoie mail depuis fiche contact pas d’événement inscrits) 

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#12845]
# Bug
When sending an email from a contact card there is no trace of sending it, no event creation.

Lorsque l'on envoie une mail depuis une fiche contact il n'y a pas de trace de l'envoie pas de création d'événement.

## Expected and actual behavior

Have a writing of the mail in the events as on a third file.

Avoir une écriture du mail dans les événements comme sur une fiche tiers.

## Steps to reproduce the behavior

Contact form send EMAIL no event created on the third party file.

Fiche contact envoyer EMAIL pas d'événement créer sur la fiche tiers.

**Comment by atm-quentin** [comment]
Hello ! Can you please specify the dolibarr version in which you have encountered this problem ?

**Comment by BB2A-Anthony** [comment]
> Hello ! Can you please specify the dolibarr version in which you have encountered this problem ?

I tested in V14 the the problem persists

I dont have a event

![image](https://user-images.githubusercontent.com/34568357/103875182-68690780-50d2-11eb-96d4-a84ad8206bdc.png)

**Comment by BB2A-Anthony** [comment]
For me is résolve in V14
