### ISSUE TITLE
API REST v10: upload de document pour "client", "adhérent" et "contact"

### ISSUE THREAD

**Issue by RAYBAUDI** [Dolibarr/dolibarr#12852]
# Feature Request
Pouvoir uploader des documents pour "client", "adhérent" et "contact" via API REST (v10)

## Use case
Pouvoir intégrer l'image/logo des fiches client, adhérent et contact via l'API REST mais également joindre par exemple des documents PDF relatifs à ces tiers

**Comment by dpriskorn** [comment]
Hi could you translate to English?

**Comment by RAYBAUDI** [comment]
Feature Request
Ability to upload documents for "client", "member" and "contact" via REST API (v10)

Use case
Be able to integrate the image / logo of customer, member and contact files via the REST API but also attach, for example, PDF documents relating to these third parties

**Comment by BebZ** [comment]
Hello, 
Yes it could be useful, but I don't know if there are solutions for this ?
Do you have a working example of REST API Upload ? 

Thanks
