### ISSUE TITLE
Adding a dictionary to list banks

### ISSUE THREAD

**Issue by tlse-vins** [Dolibarr/dolibarr#12864]
# Feature Request
The idea is to add a dictionary with the list of banks to facilitate entry when cashing checks.

## Use case
To facilitate entry when cashing checks.

**Comment by atm-maxime** [comment]
Hi. Did you try to activate the bank module ?

**Comment by tlse-vins** [comment]
Bonjour, même en activant le module banque, cette amélioration ne figure pas dans Dolibarr.
Le but serait de rajouter un dictionnaire avec le nom des banques afin de faciliter la saisie des chèques en ayant un menu à choix sur la page "Saisie d'un règlement reçu du client".

**Comment by atm-maxime** [comment]
Ok understood now. Don't you think it will be hard to keep this list up to date since there are so many different banks ?

**Comment by tlse-vins** [comment]
L'idée n'est pas d'avoir 150 banques dans un menu deroulant, on ne gagnera pas de temps bien au contraire. 
C'est de mettre les banques qui reviennent le plus souvent, dans mon cas c'est entre 15 et 20.
Et comme tout dictionnaire il faudrait pouvoir avoir la possibilité d'en rajouter.

**Comment by atm-maxime** [comment]
Of course a dictionary would be the right way of doing it. This just means that everytime a bank is not in the list, the person who wants to record the check won't be able to and will have to call and wait for the Dolibarr administrator.

**Comment by tlse-vins** [comment]
Je n'avais pas cette notion en tête car je suis l'admin de mon Dolibarr.
Je ne sais pas si c'est réalisable, mais dans le pire des cas; est il possible de rajouter une banque dans le dictionnaire lors de la saisie de l'encaissement.

Si non, il faudra mettre la liste des banques par pays (en France environs 60) les activer ou non.

**Comment by tlse-vins** [comment]
Je reviens sur ce sujet pas pour savoir si c'est possible mais pour savoir quand.
Voici un lien avec la liste des banques en France.
[liste banques](http://www.quellebanquechoisir.fr/banques/france.html)

Voici comment Laurent Destailleur à créer son fichier llx_c_banques.sql

```
CREATE TABLE llx_c_banques (
  rowid             integer AUTO_INCREMENT PRIMARY KEY,
  code              varchar(8) NOT NULL,
  label             varchar(64) NOT NULL,
  active            smallint DEFAULT 1  NOT NULL
) ENGINE=innodb;
```

**Comment by hregis** [comment]
Je ne pense pas que ce soit judicieux de les classer par pays car une banque peut être dans le monde entier... de plus un client dans un pays peut avoir une banque dans un autre pays...
Sinon pour une question pratique je verrais plus un dictionnaire vivant... on commence à entrer le nom d'une banque, la liste déroulante propose des choix, et si le nom de la banque n'existe pas, le nom écrit sera utilisé.
ou plutôt un dictionnaire qui se construit en fonction de l'historique de ce qui a déjà été entré... comme sur le principe des villes...

**Comment by atm-maxime** [comment]
I agree with @hregis, I think it would be better to have an autocompletion on this field just like the zip/city in the third-party card, based on banks already used on previous checks. A dictionary seems too heavy to maintain for me. Just like if we wanted to have a dictionary of cities.

**Comment by tlse-vins** [comment]
C'est une bonne idée.
Est ce que c'est quelque chose de complexe à mettre en place?

**Comment by atm-maxime** [comment]
No I think it's not complex. But as for everything, someone has to volonteer to develop this feature, and I don't think many people asked about it. Maybe by funding a freelance ?

**Comment by tlse-vins** [comment]
Cela fait des années que j'avais mis un sujet sur le forum sans jamais eu de retour sur la faisabilité.
Je ne savais pas qu'il valait mieux créer une issue sur GitHub.

https://www.dolibarr.fr/forum/t/ajouter-un-dictionnaire/12696

**Comment by atm-maxime** [comment]
Forum is the best place to discuss about functionalities with other members of the community. But once a new feature seems relevant and interesting for several people, it can be created on GitHub to be available to any person contributing on GitHub. But even then, it will have to wait for someone to pick up the task.

**Comment by atm-maxime** [comment]
Where did you find the llx_c_banques.sql file ??

**Comment by tlse-vins** [comment]
C'est dans le module Dolimed que Laurent Destailleur avait développé.
