### ISSUE TITLE
Dolibarr: Critical issues

### ISSUE THREAD

**Issue by kelbixgroup** [Dolibarr/dolibarr#12869]
Support

Can you please assist as to why we are facing some issues?

I will like to Edit the title of the Password reset in the template: https://prnt.sc/qolbwf

Please assist with how to locate the email template files. 

Also I am unable to create ticket, 
1.	This public ticket, https://prnt.sc/qo9nmk    the user is registered on the system (see proof: https://prnt.sc/qo9oar)
2.	Even when Admin tries to create a ticket, it cannot be created: https://prnt.sc/qo9olq

Can you please advise?

Regards.

Adeshina Olaoye

**Comment by eldy** [comment]
Translation string can be edited from menu Home - Setup - Translation

For other point it seems to be fixed in v11. Please reopen ticket once v11 has been released if not
