### ISSUE TITLE
FIX : required option not considered in extrafields type "sellist"

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#12863]
# Bug
Even if "required" is checked for an sellist extrafield, an empty value is proposed top of select box

## Environment
All versions

## Fix
`Line #1275 of htdocs/core/class/extrafield.class.php (github trunk) : 

replace 

 $out .= '&lt;option value="0"&gt;&nbsp;&lt;/option&gt;';

by

 if (!$required) $out .= '&lt;option value="0"&gt;&nbsp;&lt;/option&gt;'; 

Same replacement on line #1328
`

**Comment by cfoellmann** [comment]
The same issue is for type `link`.
I add a `link` field with `required = 1` to commande_fournisseur but it does not require it. users can create without selecting. In my case users

**Comment by ksar-ksar** [comment]
Hello,

Have you checked with the newest version of Dolibarr ?

**Comment by cfoellmann** [comment]
my issue is still in the 13.0 branch

**Comment by Hystepik** [comment]
It seems to be fixed in version 13.0.3 so I close the issue.
Feel free to reopen if not.

**Comment by cfoellmann** [comment]
We have a field (class User) "internal recipient"  with required = 1 attached to supplier orders but I can still create a draft without selecting a user.

**Comment by Hystepik** [comment]
Are you in the last update of 13.0.3 ?

**Comment by cfoellmann** [comment]
I am on branch `13.0` from 2021-05-31

**Comment by cfoellmann** [comment]
This issue is still present in 15.x but as a workaround you can set the requirement by overwriting it here `admin/defaultvalues.php?mode=mandatory`
