### ISSUE TITLE
Strange behavior ODT in Shipment module

### ISSUE THREAD

**Issue by bartiest** [Dolibarr/dolibarr#12873]
Version Dolibarr: 10.0.6 and 11.0 beta

I use ODT templates to generate files. In the templates I use extra fields like
`{line_product_options_artiest}`

When I generate a file in the Sales Order module it fills out the fields correctly.
When I use the same file in the Shipment module the extra fields aren’t filled out at all

What can cause this behavior?

I attached a zip with the files from:

1. The Sales Order output
2. The Shipment output
3. The ODT template

[Files.zip](https://github.com/Dolibarr/dolibarr/files/4073447/Files.zip)

**Comment by ksar-ksar** [comment]
Link to : https://github.com/Dolibarr/dolibarr/issues/9183

Seems that the corrected in V7 is not working ? : https://github.com/Dolibarr/dolibarr/pull/9284/

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by ksar-ksar** [comment]
Hello,

No update since last question.
If the problem persist you can re-open the issue

**Comment by ksar-ksar** [comment]
Correction : #16583
