### ISSUE TITLE
Plan comptable associatif 2020

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#12871]
@aspangaro 

nouveau plan comptable pour les assos ;)

http://www.anc.gouv.fr/files/live/sites/anc/files/contributed/ANC/1.%20Normes%20fran%C3%A7aises/Reglements/2018/Reglt_2018_06/Reglt_2018-06_Association.pdf

**Comment by aspangaro** [comment]
Merci @ptibogxiv je regarde ça dès que possible.
