### ISSUE TITLE
no salen Cuando agregas nuevos campos al modulo lotes/series en dolibarr 

### ISSUE THREAD

**Issue by soyyopercy** [Dolibarr/dolibarr#12880]
Agrege 2 campos  importantes entrafiles para lotes/series estan salen cuando  al modificar el stock .
la version que esta usando es dolibarr 10.3  y hice una prueba con 10.6 y sale igual no esta corrigido.

**Comment by ksar-ksar** [comment]
Hi,

Thanks, but could your translate to english ?
Also could you please give more details ?

Thanks

**Comment by dpriskorn** [comment]
Please upgrade to the latest version and reopen this if the problem persists (preferably with an english explanation).
