### ISSUE TITLE
Missing some setting of "Commercial proposal documents models - Other options -  Path to documents - notification" on module Proposals only

### ISSUE THREAD

**Issue by boucha91** [Dolibarr/dolibarr#12886]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Same issue happen before. To only module proposal settings was disappeared too. It same method was fixed before on changelog (FIX Regression of 10.0.5 to create/edit proposals and orders.) but still not fixed on module configuration of proposal settings only  *]

## Environment
- **Version**: [*10.0.6, but Version installation initial was 5.0.4 *]
- **OS**: [*Linux*]
- **Web server**: [*Webhost, LiteSpeed*]
- **PHP**: [*7.4.1*]
- **Database**: [*MySQL or MariaDB 10.3.21-MariaDB-cll-lve*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Same issues happen when you fix it from 10.0.5 to 10.0.6 as (FIX Regression of 10.0.5 to create/edit proposals and orders.)*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
I can't reproduce any trouble on setup page of proposal. Can you provide a screenshot ?

**Comment by boucha91** [comment]
Alright, 
 
This is our issue image ![Issue](https://user-images.githubusercontent.com/60036962/73123345-72602c00-3f8f-11ea-9fc1-65c0558e87d9.jpg) | (version installation initial | 5.0.4 -  Version actuelle de Dolibarr (Programs) | 10.0.6 - version dernière mise à jour (Base de données) | 10.0.6)

And this is our demo fresh installed ![Supposed](https://user-images.githubusercontent.com/60036962/73123354-82780b80-3f8f-11ea-90d1-6c7509960c3e.jpg) | (version installation initial | 10.0.5 -  Version actuelle de Dolibarr (Programs) | 10.0.6 - version dernière mise à jour (Base de données) | 10.0.6)

And Everything looks fine for now except this small bug as I never edit core files on dolibarr, even though I check integrity files.

**Comment by boucha91** [comment]
It's seems another image has a clue of error message appeared after changing v7.4 PHP to v7.3 PHP
![Annotation 2020-01-27 155159](https://user-images.githubusercontent.com/60036962/73184598-01e71580-411d-11ea-81bc-52a4d7326d3b.jpg)

It's seem problem close to be solved when I downgrade PHP version. I wonder why didn't showing up these message error on v7.4

"pdf_t1" might be the option I was testing it recently called "MAIN_ADD_PDF_BACKGROUND" value "t1.pdf", but seems that option not worked for me then I restored as default was

**Comment by boucha91** [comment]
I guess I figure out the problem. I delete this file path "core/modules/propale/doc/pdf_t1.modules.php" and it was fixed the issue, but I don't know why exactly was created and I doubt "MAIN_ADD_PDF_BACKGROUND" was the reason for this bug

**Comment by eldy** [comment]
I confirm that MAIN_ADD_PDF_BACKGROUND is not the origin of trouble.
pdf_t1.modules is not an official file of Dolibarr, probably provided by an external module, so i close the ticket
