### ISSUE TITLE
bug droits d'accès au module TakePOS

### ISSUE THREAD

**Issue by deraulca** [Dolibarr/dolibarr#12896]
# Bug
Once the TakePos module is activated, even people who do not have access rights have the icon and can access it (same for groups).

## Environment
- **Version**: 10.0.6
- **OS**: Windows server 2012 r2
- **Web server**: Microsoft-IIS/8.5
- **PHP**: 7.3.10
- **Database**:  libmysql - mysqlnd 5.0.12

## Steps to reproduce the behavior
- Configuration - Modules/applications
- Activate PdV TakePOS 
- For a user or a group, forbid him the rights to the module
- Connect with this user
===> the PdV button still appears and is accessible

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
- "cuisine" account does not have the rights
![image](https://user-images.githubusercontent.com/60102510/72738145-4284e300-3ba1-11ea-82f4-8dbc598deeea.png)
- logged in with this account, access is still available
![image](https://user-images.githubusercontent.com/60102510/72738223-66482900-3ba1-11ea-9169-8a6e26cb7dcb.png)

Thanks
Cordialement

**Comment by ksar-ksar** [comment]
Hi,

Thanks, but could your translate to english ?

Thanks

**Comment by deraulca** [comment]
Bonjour,
It's OK
Thanks
