### ISSUE TITLE
Bug: Changement de client ineffectif depuis facture modèle 

### ISSUE THREAD

**Issue by WhilelM** [Dolibarr/dolibarr#12894]
# Bug

## Environment
- **Version**: 10.0.6
- **OS**: Linux
- **Web server**: Apache/2.2.22 (Debian)
- **PHP**: apache2handler 5.6.40-1~dotdeb+7.1
- **Database**: MySQL or MariaDB 5.5.47-0+deb6u1-log
- **URL**: /compta/facture/list.php?restore_lastsearch_values=1

## Report

Bonjour,

Lors de la création d'une facture depuis un modèle de facture, le changement de client sur la page "Nouvelle facture" n'est pas prise en compte et le brouillon de facturé généré reprend le client initial du modèle.
Le comportement attendu serait que le client retenu soit bien celui sélectionné lors de la création de la facture.

**Comment by ksar-ksar** [comment]
Hi,

Thanks, but could your translate to english ?

Thanks

**Comment by WhilelM** [comment]
Bug: Can't change client invoice when generated from template invoice #12894 

When I create an invoice from template invoice, I choose another client in "New invoice" page but it is forced on original client template invoice in the draft generated.
I would like the client invoice draft to be the one I choose.

**Comment by eldy** [comment]
This has been fixed in v11
