### ISSUE TITLE
Files with double spaces in the filename are not downloadable

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#12900]
Reproduceable: upload any file with double spaces in the name and Dolibarr will respond with something similiar like this:

    ErrorFileDoesNotExists: 984/fil med dubbla space.txt

(the actual filename for the above file is "fil  med dubbla space.txt").

The root cause for this problem is in htdocs/core/lib/functions.lib.php, function dol_string_nohtmltag():

    while (strpos($temp, "  "))
    {
        $temp = str_replace("  ", " ", $temp);
    }

This removes the double spaces from the filename, even if the file has been uploaded with the double spaces.

There are many solutions to this problem, but I think the best one is to simply avoid having spaces at all in filenames. Perhaps by replacing SPC with "_" or similiar.

**Comment by eldy** [comment]
This seems to be fixed in future v11, so i close the ticket.
