### ISSUE TITLE
Bug: User login with credentials from self-subscription form fails

### ISSUE THREAD

**Issue by Heuser98** [Dolibarr/dolibarr#12908]
# Bug
After validation of a new user by Admin comming in via self-subscription form can not log in with his credentials given in self-subscrotion form. 

## Environment
- **Version**: 10.0.6
- **OS**: Linux h2web54 4.9.0-0.bpo.9-amd64 #1 SMP Debian 4.9.168-1+deb9u3~deb8u1 (2019-06-17) x86_64
- **Web server**: Apache
- **PHP**: 7.3.13
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: https://patientenkompass.com/

## Expected and actual behavior
expected: user can login with Username and PW he selected in Public self-subscription form
actual: login fails with these credentials

## Steps to reproduce the behavior
1. Log in as Admin
2. go to Member, Member Types, New: Add new member type
3. go to Setup, Modules, Members, setup, Public self-subscription form: enable the public website with self-subscription form
4. Klick link to Public self-subscription form
5. Enter mandatory fields and safe, note cedntials used.
6. go to Members Dashboard, klick on latest entry in Latest 5 modified members
7. click validate
8. click Create a User and validate Login to create
9. log off
10. try to log in with credentials of new user: 
error message username or password wrong

**Comment by eldy** [comment]
Confirmed: When creating a user from a member, the password was reset to another value when it should not.
