### ISSUE TITLE
Expense Report date in stats

### ISSUE THREAD

**Issue by michel-thomas** [Dolibarr/dolibarr#12910]
# Bug
Statistics for expense reports consider the validation/approbal date instead of period.

## Environment
- **Version**: 10.0.6
- **OS**: Debian 10
- **Web server**: Apache 2.4
- **PHP**: 7.3
- **Database**: MariaDB 10.3.18
- **URL(s)**: https://mydomain.com/expensereport/stats/index.php?leftmenu=expensereport&mainmenu=hrm

## Expected and actual behavior
I notice the problem with expense reports for the period of December 19 which been validated in January 20. Reports shows these expense in 2020 instead of 2019.

**Comment by eldy** [comment]
Note sure this is a bug. In most cases an expense report is paid only when it is validated. So if we want to know the amount of expense report really validated and to pay, we need validation date.
But i understand in other situation, we may also want to have report on the start date of period.
This may be addressed by the future generic report feature of Dolibarr.

**Comment by michel-thomas** [comment]
Okay. Thanks for the status.

I will wait for new version and check if it fit my needs.

FYI the module [Pivot Reports](https://www.dolistore.com/fr/modules/1132-Pivot-Reports--Tableaux-crois--s-dynamiques-pour-Dolibarr-.html) gives by default the expense reports by period date, based on `llx_expensereport.date_debut`.
