### ISSUE TITLE
BUG: Negative input stock value in the warehouse

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#12920]
# Bug
Negative input stock value in the warehouse if the product stock is negative

## Environment
- **Version**: 10.0.7
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: /htdocs/product/stock/list.php?mainmenu=products&idmenu=42268

## Expected and actual behavior
If the product price in the warehouse list is negative it is impossible to see how much the products in the warehouse are worth, therefore the price on the list, in this case, should be 0

## Steps to reproduce the behavior
create negative quantity for a product a check the warehouse list

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![stock](https://user-images.githubusercontent.com/28427270/73015047-32743a00-3e13-11ea-8063-8f5a342fc370.JPG)

**Comment by eldy** [comment]
If you have a negative value of stock, the value and the movement should also be negative. 
The movement because the value decrease. And the final value because we have to expense money to fill the hole (if we sell more than what we have temporary in stock for example).

**Comment by futurehousestore** [comment]
Thanks Eldy, I get your point and it makes sense. In this case, I think I should do a feature request to add an option to split negative stock and positive stock to be able to see the actual stock input price without negative values and the other way round.

**Comment by futurehousestore** [comment]
Fixed in version 13. Thank you.
