### ISSUE TITLE
PHP 5.4 or greater keeps warning on file "error_log" with function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by boucha91** [Dolibarr/dolibarr#12931]
I found these warnings after I viewed on file called "error_log" of webhost flooded a lot since I changed to php 7.x in every time using dolibarr.

Its keep saying 
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /home/csmmaroc/public_html/demo/main.inc.php on line 53

![error_log_demo](https://user-images.githubusercontent.com/60036962/73124347-b147af00-3f9a-11ea-98c0-b1957a6f99e5.jpg)

**Comment by ksar-ksar** [comment]
Hi,

get_magic_quotes_gpc this function has been DEPRECATED as of PHP 7.4.0.
https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

And as indicated there : https://wiki.dolibarr.org/index.php/Prerequisite
Min. required version: 5.5.0+ (requires functions like DateTimeZone.getOffset, php-intl), Max 7.3.*

Dolibarr is not yet compatible 7.4.

**Comment by boucha91** [comment]
Ah I was so dump, it was only deprecated for v7.4 as I checked by v7.3 and nothing was reported to that warning. Thank you man I appreciated for your help

**Comment by ksar-ksar** [comment]
You are welcome !

Could you close the issue ?
