### ISSUE TITLE
Incorrect date format in ODT invoice with {object_date} after automatic invoice creation

### ISSUE THREAD

**Issue by bjoern86** [Dolibarr/dolibarr#12933]
# Bug
After automatic invoice creation with .odt template the variable {object_date} is replaced with the invoice date but in wrong format: 01/25/2020 instead of 25.01.2020 (which would be the correct format). This error only occurs with recurring invoices which are created as draft and then created automatically. I also tried {object_date_locale} as workaround but this var is not available.

## Environment
- **Version**: 10.0.6
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.3
- **Database**: mysql 5.7.18

## Expected and actual behavior
Render variable {object_date} with invoice date in correct local format 25.01.2020

## Steps to reproduce the behavior
see above

**Comment by eldy** [comment]
A fix related to this was introduced for v11.0.1.
It would be interesting to know if pb still occurs with future v11.0.1

**Comment by bjoern86** [comment]
thank you @eldy fix in v11.0.1 works for me.

**Comment by bjoern86** [comment]
Update 12.0.4 fixes issue #14245 for me.
@eldy: But now, after generating invoices automatically, I get the wrong formats again (01/25/2020 instead of 25.01.2020 and 123.45 € instead of 123,45 €). If I gererate the invoice manually the formats ar fine...

**Comment by ok-ttc** [comment]
The issue still persists.
