### ISSUE TITLE
Question: REST API agenda PUT method

### ISSUE THREAD

**Issue by jribal** [Dolibarr/dolibarr#12945]
Hi, I'm using dolibarr 10.0.6 and I looking for a way to update an agenda/.

I looked into [this file](https://github.com/Dolibarr/dolibarr/blob/10.0.6/htdocs/comm/action/class/api_agendaevents.class.php) and found the update function is commented.

I uncommented as in [this post](https://www.dolibarr.org/forum/t/agendaevents-put-update-method-not-working/17834) then I had to comment the line `$sql.= ", fk_user_mod = ".$user->id;` in [actioncomm.class.php](https://github.com/Dolibarr/dolibarr/blob/10.0.6/htdocs/comm/action/class/actioncomm.class.php)

managed to make an update.

Is there a reason for the update function to be commented ?
Is the function safe to use ?

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue (v11)
