### ISSUE TITLE
Making TakePOS create "tickets" instead of "invoices" -> Use its own numbering rule + add mandatory info for invoice on ticket

### ISSUE THREAD

**Issue by denis-poncereau** [Dolibarr/dolibarr#12948]
# Making TakePOS create "tickets" instead of "invoices"
TakePOS is creating invoices (like in the back-office) but when printing the page doesn't have the required information of an invoice (it is rather a receipt or ticket). It would be better to have a different numbering (object reference) to distinguish it from invoices. I think it more correct for accountancy to separate real invoices (created in back-office, with the legal form) from simple tickets (created by TakePOS and printed as simple receipts).
![Capture du 2020-01-28 17-10-23](https://user-images.githubusercontent.com/59958069/73283663-c0756980-41f3-11ea-992b-106e87fb98fa.png)

## Use case
When validating a sale in TakePOS, the object created is the same as an invoice, but with a different reference.

## Suggested steps
- Use a different numbering system for sales made with TakePOS (ex : TCnnnn instead of FAnnnn, with a separate list of 'nnnn')
- Make a separate list for tickets and invoices (filtering by reference)

**Comment by denis-poncereau** [comment]
To start and test it, I've created a function `getNextTicketRef()` in the `takepos/invoice.php` file. It gets the last ref based on a 'TCnnnn' model to return the new ref that is used as `$force_number` to the `Facture::validate()` function.
The ticket now has a TC0001 number !
What about adding this possibility to the TakePOS module ?
![Capture du 2020-01-31 16-34-53](https://user-images.githubusercontent.com/59958069/73552019-bd72b700-4447-11ea-8e65-4b50455edc88.png)
![Capture du 2020-01-31 16-35-26](https://user-images.githubusercontent.com/59958069/73552048-cebbc380-4447-11ea-9ee8-d5f0a917d39e.png)

**Comment by atm-maxime** [comment]
Good idea. The takepos module must then have a setup with a numbering module asking for the numbering format, and use the same system as in invoice numbering module. But also leave the possibility to keep the same numbering as the invoices.
