### ISSUE TITLE
Translate field VAT ID in Dolibarr interface and output

### ISSUE THREAD

**Issue by willyotto** [Dolibarr/dolibarr#12940]
In the settings>my company page, the contacts page and on every pdf output(invoices, offers) there is mentioned "VAT ID" I want to translate that in my language.
I searched the Whole directory of Dolibarr, database included, I cannot find where to change this!
Can anyone help me with this one?

**Comment by ksar-ksar** [comment]
Hi,

On 'langs\en_US\companies.lang' : 

- VATIntra=VAT ID
- VATIntraShort=VAT ID

So if you go to Setup->Translation you can overwrite the two keys

**Comment by willyotto** [comment]
Hi there

 

Thank you for your response. How does this exactly work, overwriting keys, does it have to be in a special format, …

 

Kind regards

 

Willy

 

 

Van: ksar <notifications@github.com> 
Verzonden: dinsdag 28 januari 2020 14:18
Aan: Dolibarr/dolibarr <dolibarr@noreply.github.com>
CC: willyotto <willy@groencreaties.be>; Author <author@noreply.github.com>
Onderwerp: Re: [Dolibarr/dolibarr] Translate field VAT ID in Dolibarr interface and output (#12940)

 

Hi,

On 'langs\en_US\companies.lang' :

*	VATIntra=VAT ID
*	VATIntraShort=VAT ID

So if you go to Setup->Translation you can overwrite the two keys

**Comment by Tim-Otte** [comment]
Hi @willyotto,

you can overwrite translations like this:

1. Go to **Home**
2. Click on **Instellingen**
3. Click on **Vertaling**.
4. Now you should see a table with some inputs in the first row
5. Select in the combobox _Taal (en_US, es_MX, ...)_ the language (i think you are from belgium, so the value should be _nl_BE - Nederlands (België)_. In the second input _Key_ insert the value _VATIntra_. In the third input _Weergeven nieuwe vertaal string_ insert the translated text. Now click on the button labeled _Toevoegen_ to override the translation with your desired translation.
6. Repeat step 5 with the key value _VATIntraShort_.
7. Done. Now the vat id should be translated correctly.

**Comment by willyotto** [comment]
Thank you Tim, this helps me.

 

Grts

 

Willy

 

Van: Tim Otte <notifications@github.com> 
Verzonden: donderdag 13 februari 2020 9:49
Aan: Dolibarr/dolibarr <dolibarr@noreply.github.com>
CC: willyotto <willy@groencreaties.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Dolibarr/dolibarr] Translate field VAT ID in Dolibarr interface and output (#12940)

 

Hi @willyotto <https://github.com/willyotto> ,

you can overwrite translations like this:

1.	Go to Home
2.	Click on Instellingen
3.	Click on Vertaling.
4.	Now you should see a table with some inputs in the first row
5.	Select in the combobox Taal (en_US, es_MX, ...) the language (i think you are from belgium, so the value should be nl_BE - Nederlands (België). In the second input Key insert the value VATIntra. In the third input Weergeven nieuwe vertaal string insert the translated text. Now click on the button labeled Toevoegen to override the translation with your desired translation.
6.	Repeat step 5 with the key value VATIntraShort.
7.	Done. Now the vat id should be translated correctly.
