### ISSUE TITLE
Italian address displaying wrong

### ISSUE THREAD

**Issue by fabrizio-deskside** [Dolibarr/dolibarr#12971]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Italian Province displaying ID on documents instead of Code*]

## Environment
- **Version**: [*10.0.6*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Solution
[*modify functions.lib this way for country IT, instead of state_id you should put state_code as below.*]

elseif (in_array($object->country_code, array(‘IT’))) // IT: tile firstname name\n address lines \n zip (Code Departement) \n country
{
$ret .= ($ret ? $sep : ‘’ ).$object->zip;
$ret .= ($object->town?(($object->zip?’ ‘:’’).$object->town):’’);
$ret .= ($object->state_code?(’ (’.($object->state_code).’)’):’’);
}

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
