### ISSUE TITLE
Bug: the hidden option SUPPLIER_ORDER_CAN_UPDATE_BUYINGPRICE_DURING_RECEIPT does not work.

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#12972]
# Bug

When placing an order with the supplier, and once the receipt is made, it is expected that it will update the buying price, however, the buying price of the product remains the same indicated in the product file instead of the price indicated in the supplier order as expected.

I have activated the experimental module "Reception", in case the activation of said hidden option was related to said module, performed the purchase and reception process and the results have been the same.

## Environment
- **Version**: 11.0.0
- **OS**: Linux (OpenSUSE Leap 15.1)
- **Web server**: Apache
- **PHP**: apache2handler 7.2.5
- **Database**: MySQL or MariaDB 5.5.5-10.2.29-MariaDB
- **URL(s)**: localhost

**Comment by eldy** [comment]
Currently I don't think this is an expected behavior to have the buying price automatically updated. 
This may be interesting to have this so i qualified this as a feature request to introduce this as an option.
It may be a checkbox "Update supplier prices" when we validate the purchase order.

**Comment by JuanBrillo** [comment]
Hello, I really thought that the function of the hidden variable was as indicated. I imagine that you then update the purchase price indicated in the supplier's order form.

Even so, I consider it very important to add the function that I have explained, since, currently, for companies that do not have people dedicated to constantly updating product prices (most of them) it is difficult for them to request a quote from the supplier without having to updated prices, and then have to modify 1 to 1 on each product before launching the order and invoice. Whereas if the purchase price in the product sheet is updated whenever you receive the product, you know the most up-to-date price directly.

Please implement this feature in version 13 or later, as the current form wastes a lot of time.

Kind regards, and congratulations on Dolibarr as a whole.
