### ISSUE TITLE
Bug: Dolibarr 11.0.0 - activate Module Shipments

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#12984]
# Bug

when you activate the module *Shipments* at first after new dolibarr setup
it shows menue *Services* - but with error message of no access

 
activation of module Shipments activated automatically also the modules
Sales Orders and Third Parties - nothing more
but it shows then also Menu Services - with no activated module of this group

![activated only module shipment - this results](https://user-images.githubusercontent.com/45215329/73540220-a45e0c00-442f-11ea-8228-afe7614a9b72.png)

![activated menue services but with error message](https://user-images.githubusercontent.com/45215329/73540294-d40d1400-442f-11ea-87e9-1a9ba2d59619.png)

## Environment
- **Version**: 11.0.0
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.2.27-1+0~20200123.34+debian9~1.gbp63c0bc
- **Database**: MySQL or MariaDB 5.5.5-10.1.41-MariaDB-0+deb9u1
- **URL(s)**: /dolibit/demo/original/dolibarr11/htdocs/admin/ihm.php?mainmenu=home&leftmenu=setup

**Comment by atm-maxime** [comment]
Yes right, and I think this issue is also there in previous versions. Maybe shipment module must also activate the product module because a shipment cannot be done without products. And then the product/service menu will land on the right homepage.

**Comment by eldy** [comment]
Currently it is possible to make order and shipment with free product, that's why module product is not a dependency. I fixed the problem by changing tests on restrictedArea
