### ISSUE TITLE
invoice number format does not apply

### ISSUE THREAD

**Issue by herrdeh** [Dolibarr/dolibarr#12985]
Whatever structure I choose in admin > settings > modules > invoices (I tried "mars" and "mercure RE {yy}-{0000}" in countless variants - in the odt invoice I always get the actual invoice number, but not the desired format.

Meaning: 
In mercure, what should be "RE 20-0004" is just "4".
in mars, what should be "FA0501-0015" ist just "15". 

I asked at the [forum](https://www.dolibarr.org/forum/t/odt-template-invoice-wrong-number-formats/18398), but did not get help for this issue.

Local installation of 10.0.6 at ubuntu linux.

Cheers,
Wolf

**Comment by atm-maxime** [comment]
Can you give the odt model and the PDF generated by Dolibarr crabe ?

**Comment by herrdeh** [comment]
Wow - such a quick reply!
ODT template and invoice examples in pdf (crabe) and odt are here in my [dropbox](https://www.dropbox.com/sh/mwt5fl2u58h7y60/AACHSkIuARx7K2oQaP_XVXuZa?dl=0)

In pdf crabe, the format is correct, the invoice number is not - should be "RE 20-0030", but is "RE 20-0003".

**Comment by atm-maxime** [comment]
Ok that's simple, you must use {object_ref} and not {object_id}. This id is a database technical I'd of the object. What you want to use is the ref. Don't forget to close the issue if it's ok for you.

**Comment by herrdeh** [comment]
I tried that several times, it never worked... - till today. Weird. But now solved. Thank you. I'll close this case - but I opened another [here](https://github.com/Dolibarr/dolibarr/issues/12993), which is related very much.
