### ISSUE TITLE
BOM Bill of Materials -> pdf_avalue.modules.php does not exist

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#12994]
# Bug
Validate a BOM Bill of Materials. 
Error File /htdocs/core/modules/bom/doc/pdf_avalue.modules.php does not exist

## Environment
- **Version**: 11.0
- **OS**: Ubuntu 16.04
- **Web server**: Apache2
- **PHP**: 7.2
- **Database**: MySQL
- **URL(s)**: bom/bom_card.php?id=8&action=confirm_validate&confirm=yes&token=%242y%2410%24hsAxYJefZ%2FbR%2FNkjhw2fuO9onT8M%2Fr5F0v8qeu7wy.6APCDsIb2F.

## Expected and actual behavior
the file should be available and not generating an error.

## Steps to reproduce the behavior
Create a bill of Material
Add products
Validate the BOM

**Comment by eldy** [comment]
Don't you install a v11 before it was released as stable ?
Did you did a fresh install or a migration ? From which version ?
What is your setup in setup of module BOM ?

**Comment by erikvanberkum** [comment]
I was running on 10.6 and upgraded on 2020-02-02 to versions 11.0
BOM was activated already in 10.6
In version 11.0 i have activated MO 

I checked in my install the file pdf_avalue.modules.php is not their. 
I checked the zipfile and i cant find this file. 
I checked github and i am also unable to find this file. 

Not sure what i am doing wrong

BOM setup see below

![bom-setup](https://user-images.githubusercontent.com/7335299/73645261-4b55d880-46ba-11ea-966b-c5e83189df89.PNG)

**Comment by eldy** [comment]
The problem is here
"BOM was activated already in 10.6"
This feature was experimental in v10, and the trouble you get is the result of using a not stable feature, even if trouble occurs after migrating in v10
If module is enabled for first time in v11, there is no trouble. Try to click on "default" for the document template that exists and problem should disappear.

**Comment by erikvanberkum** [comment]
that was the trick,

 click on "default"

 thank you
