### ISSUE TITLE
describe tags for odt templates

### ISSUE THREAD

**Issue by herrdeh** [Dolibarr/dolibarr#12993]
[This pages](https://wiki.dolibarr.org/index.php/Create_an_ODT_document_template#Tags) gives a good description how to create a custom template. But it lacks a description of tags. Programmers are free to create interesting names like "object_multicurrency_total_ttc_locale" - but as they mix English and French language, it's nearly impossible to understand what they actually mean.
So please - to avoid stupid questions in the forums and silly mistakes - take that half hour it may need and complete the list of tag descriptions.
Thanks a lot in advance.

**Comment by ksar-ksar** [comment]
Hi,

Most of them are quiet easy to understand, for the rest there is some explanations.
I don't see french on it.

Could you be more specific on what you do not understand ?

**Comment by herrdeh** [comment]
Yes, I can. Well - this is my inability, other people may not understand other things.  I marked (to me) missing explanations with a "#" and missing explanations to the concept with "##". Esp. in the latter case, a few links could make life so much easier... (:
Thank you so much for your care!

`Company/foundation information

{mycompany_logo} : Your company logo
{mycompany_name} : Your company name
{mycompany_address} : Your company address
{mycompany_zip} : Your company zip
{mycompany_town} : Your company town
{mycompany_country} : Your company country (label)
{mycompany_country_code} : Your company country (code: FR, US, IT...)
{mycompany_state} : Your company state (label)	#
{mycompany_state_code} : Your company state (code)	##
{mycompany_phone}
{mycompany_fax}
{mycompany_email}
{mycompany_web}
{mycompany_barcode}
{mycompany_capital}
{mycompany_juridicalstatus}
{mycompany_managers}
{mycompany_idprof1}	##
{mycompany_idprof2}	##
{mycompany_idprof3}	##
{mycompany_idprof4}	##
{mycompany_idprof5}	##
{mycompany_idprof6}	##
{mycompany_vatnumber} : Your company VAT number
{mycompany_object}	#
{mycompany_note_private} : Your company private note


Customers, prospects or suppliers information

{company_name} : Customer or Supplier company name
{company_name_alias}	##
{company_address}
{company_zip}
{company_town}
{company_country} : Customer or Supplier company country (label)
{company_country_code} : Customer or Supplier company country (code: FR, US, IT...)
{company_state}
{company_state_code}
{company_phone}
{company_fax}
{company_email}
{company_web}
{company_barcode}	#
{company_customercode} :	##
{company_suppliercode} :	##
{company_customeraccountancycode} :	##
{company_supplieraccountancycode} :	##
{company_capital}
{company_juridicalstatus}
{company_outstanding_limit}	#
{company_idprof1}	##
{company_idprof2}	##
{company_idprof3}	##
{company_idprof4}	##
{company_idprof5}	##
{company_idprof6}	##
{company_vatnumber} :
{company_note_public} :
{company_note_private} :
{company_default_bank_iban}
{company_default_bank_bic}

Extra fields:
{company_options_xxx} : Value of extra field (where xxx is code of extra field)

Contacts
It is the tags for contact of invoice for invoices (type BILLING), contact of proposal for proposals (type CUSTOMER), contact of order for sale orders (type CUSTOMER). There is not tags for delivery contact.

### What is the difference between "customers" and "contacts" ? A link to the explanation would be helpful.

{contact_fullname}
{contact_lastname}
{contact_firstname}
{contact_address}
{contact_zip}
{contact_town}
{contact_state_id}
{contact_state_code}
{contact_state}
{contact_country_id}
{contact_country_code}
{contact_country}
{contact_poste}	#
{contact_socid}	#
{contact_statut}	#
{contact_code}	#
{contact_email}
{contact_jabberid}
{contact_phone_pro}	#
{contact_phone_perso}	#
{contact_phone_mobile}
{contact_fax}
{contact_birthday}
{contact_default_lang}
{contact_note_public}
{contact_note_private}

Extra fields:
{contact_options_xxx} : Value of extra field (where xxx is code of extra field)

User information

### What is a "user", distinguished to "contact" and "customer". A link to the explanation would be helpful.

{myuser_lastname}
{myuser_firstname}
{myuser_fullname}
{myuser_phone}
{myuser_fax}
{myuser_mobile}
{myuser_address}
{myuser_login}
{myuser_email}
{myuser_zip}
{myuser_town}
{myuser_country}
{myuser_country_code}	#
{myuser_state}
{myuser_state_code}
{myuser_logo}
{myuser_job}
{myuser_web}

Other information

{current_date}
{current_datehour}
{current_server_date}
{current_server_datehour}
{current_date_locale}	# The "locale" concept should be explained somewhere. Link?
{current_datehour_locale}	#
{current_server_date_locale}	#
{current_server_datehour_locale}	#

{__(XXX)__} = Translated value of a translation key XXX - Note: Translation must be inside a language file that was previously loaded with $langs->load("languagefile")
{__[XXX]__} = Value of constant XXX

Object information (invoice, commercial proposal, order, ...)

{object_id}	#
{object_ref}	#
{object_ref_ext}	#
{object_ref_customer}	#
{object_ref_supplier}	#
{object_note_private}
{object_note_public}
or
{object_note}	#

Dates
{object_hour}
{object_date}
{object_date_rfc}	#
{object_date_creation}
{object_date_modification}
{object_date_validation}
{object_date_limit} : Specific to invoices	#
{object_date_end} : Specific to proposals : End date of validity of proposal
{object_date_delivery_planed} : Specific to order	#
{object_date_close}

Amounts (numeric data):

### These are really hard! - A non-french person will never guess what "ht" and "ttc" is, they are even hard to google from abroad.

{object_total_ht}	#
{object_total_vat}	#
{object_total_localtax1}	# (what is "localtax" in opposition to "VAT"?
{object_total_localtax2}	#
{object_total_ttc}	#
{object_total_discount_ht}	#
{object_total_vat_x} (is vat total for rate x. x can be for example 20, 8.5, 5.99 ...}	#

Amounts (in output language format):
{object_total_ht_locale} 
{object_total_vat_locale} 
{object_total_localtax1_locale}
{object_total_localtax2_locale}
{object_total_ttc_locale}
{object_total_discount_ht_locale}
{object_total_vat_locale_x.x} (is vat total for rate x. x can be for example 20.000, 8.500, 5.990 ...}

Multicurrency: ##
{object_multicurrency_code}	#
{object_multicurrency_tx}	#
{object_multicurrency_total_ht}	#
{object_multicurrency_total_tva}	#
{object_multicurrency_total_ttc}	#
{object_multicurrency_total_ht_locale}	#
{object_multicurrency_total_tva_locale}	#
{object_multicurrency_total_ttc_locale}	#

Specific to invoices :
{object_payment_mode}
{object_payment_mode_code}
{object_payment_term}	#
{object_payment_term_code}	#
{object_source_invoice_ref}	#
{object_already_payed} : Amount already payed (numeric)
{object_already_deposit}	#
{object_already_creditnote}	#
{object_already_payed_all}	#
{object_remain_to_pay} : Remaining to pay amount (numeric)
{object_already_payed_locale} : Amount already payed (output language format)
{object_already_deposit_locale}
{object_already_creditnote_locale}
{object_already_payed_all_locale}
{object_remain_to_pay_locale} : Remaining to pay amount (output language format)

Specific to Projects :
{object_project_ref}	#
{object_project_title}
{object_project_description}
{object_project_date_start}
{object_project_date_end}

Specific to Shipments :
{object_date_delivery}
{object_hour_delivery} 
{object_tracking_number}
{object_tracking_url}
{object_shipping_method}
{object_weight}
{object_width}
{object_height}
{object_depth}
{object_size}

Extra fields:
{object_options_xxx} : Value of extra field (where xxx is code of extra field)

Lines of object

This is how to use arrays for lines of objects (invoices, commercial proposal, orders, etc...). You must create your array in the document and use a begin and end tag to define a line of the array. The line will then be repeated as much as required during generation.

[!-- BEGIN row.lines --]
...
[!-- END row.lines --]

If you want to display it not in tables row but in block lines :

[!-- BEGIN lines --]
...
[!-- END lines --]

Then, you can use following tags into your line:

{line_fulldesc}	#
{line_product_ref}	#
{line_product_ref_fourn}	#
{line_product_label}	#
{line_product_type}	#
{line_desc}	#
{line_vatrate}	#
{line_localtax1_rate} (V10)	#
{line_localtax2_rate} (V10)	#
{line_up}	#
{line_up_locale}	#
{line_qty}
{line_discount_percent}
{line_price_ht}	#
{line_price_ht_locale}	#
{line_price_vat}	#
{line_price_vat_locale}	#
{line_price_ttc}	#
{line_price_ttc_locale}	#
{line_date_start}
{line_date_start_locale}
{line_date_start_rfc}	#
{line_date_end}
{line_date_end_locale}
{line_date_end_rfc}
{line_unit} : Needs PRODUCT_USE_UNITS to 1	#
{line_unit_short} : Needs PRODUCT_USE_UNITS to 1	#

Multicurrency :
{line_multicurrency_code}	#
{line_multicurrency_subprice}	#
{line_multicurrency_total_ht}	#
{line_multicurrency_total_tva}	#
{line_multicurrency_total_ttc}	#
{line_multicurrency_subprice_locale}	#
{line_multicurrency_total_ht_locale}	#
{line_multicurrency_total_tva_locale}	#
{line_multicurrency_total_ttc_locale}	#

Specific to Shipments :
{line_qty_shipped}
{line_qty_asked}
{line_weight}
{line_length}
{line_surface}
{line_volume}

Extra fields:
{line_options_xxx} : Value of extra field (where xxx is code of extra field)
{line_product_options_xxx} : If the line is a product, Value of the Product extra filed (where xxx is code of Product extra field)

This an example of what you may have in your office suite: Line for document generation.png
For project documents

For document about projects and task, you also have

{tasktime_rowid}	#
{tasktime_task_date}
{tasktime_task_duration}
{tasktime_task_duration_sec}
{tasktime_note}	#
{tasktime_fk_user}	#
{tasktime_user_name}
{tasktime_user_first}
{tasktime_fullcivname}	#
`

**Comment by herrdeh** [comment]
I can offer a translation into German, when the English version is available...

**Comment by vudinhhung88** [comment]
if I have created an extra field within the “societe” module, with its code being “cusdebt,” representing the outstanding debt amount that a customer has yet to pay me. Now, what tag should I use to display it in the invoice ODT file?

I’ve tried using {contact_options_cusdebt} and {company_options_cusdebt}, but it didn’t work.
