### ISSUE TITLE
Erreur migration base de donnée from 10.0.6 to 11 with postgresql

### ISSUE THREAD

**Issue by andrela** [Dolibarr/dolibarr#12992]
Hello,
After the migration script from 10 to 11 sql which is OK an clicking the button Suivant, here is the error message i receive
I'am on debian 9 with postgresql and i should precise that it's non bloquant because i don't use all the thirdparty contact fields

Dolibarr a détecté une erreur technique. You use an experimental or develop level of features, so please do NOT  report any bugs, except if problem is confirmed moving option  MAIN_FEATURES_LEVEL back to 0. Voici les informations qui pourront aider au diagnostic (Vous pouvez  fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques  notifications): Date: 20200201185356 Dolibarr: 11.0.0 Niveau de fonctionnalités: 2 PHP: 7.0.33-0+deb9u6 Serveur: Apache/2.4.25 (Debian) OS: Linux agricool 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0  Url sollicitée: /doli9/htdocs/install/upgrade2.php?versionfrom=10.0.0&versionto=11.0.0 Referer:  http://192.168.1.6/doli9/htdocs/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=10.0.0&versionto=11.0.0 Gestionnaire de menu:   Modules/Applications: stockmanagement, syslog, user, expedition,  tax, banque, product, stock, comptabilite, categorie, import, export,  cashdesk, blockedlog, takepos, agenda, barcode, commande, ecm, facture,  fournisseur, societe Type gestionnaire de base de données: pgsql Requête dernier accès en base en erreur: SELECT rowid,  socialnetworks, skype, twitter, facebook, linkedin, instagram, snapchat,  googleplus, youtube, whatsapp FROM llx_user WHERE  skype IS NOT NULL OR  skype !="" OR twitter IS NOT NULL OR twitter !="" OR facebook IS NOT  NULL OR facebook!="" OR linkedin IS NOT NULL OR linkedin!="" OR  instagram IS NOT NULL OR instagram!="" OR snapchat IS NOT NULL OR  snapchat!="" OR googleplus IS NOT NULL OR googleplus!="" OR youtube IS  NOT NULL OR youtube!="" OR whatsapp IS NOT NULL OR whatsapp!="" Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX Information sur le dernier accès en base en erreur: ERREUR:   42601: identifiant délimité de longueur nulle sur ou près de « ""  »\nLINE 1: ...FROM llx_user WHERE  skype IS NOT NULL OR skype !="" OR  twit...\n                                                              ^\nLOCATION:  scanner_yyerror, scan.l:1128  Migration des champs de réseaux sociaux utilisateurs (Users)
--
 
Dolibarr a détecté une erreur technique. You use an experimental or develop level of features, so please do NOT  report any bugs, except if problem is confirmed moving option  MAIN_FEATURES_LEVEL back to 0. Voici les informations qui pourront aider au diagnostic (Vous pouvez  fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques  notifications): Date: 20200201185356 Dolibarr: 11.0.0 Niveau de fonctionnalités: 2 PHP: 7.0.33-0+deb9u6 Serveur: Apache/2.4.25 (Debian) OS: Linux agricool 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0  Url sollicitée: /doli9/htdocs/install/upgrade2.php?versionfrom=10.0.0&versionto=11.0.0 Referer:  http://192.168.1.6/doli9/htdocs/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=10.0.0&versionto=11.0.0 Gestionnaire de menu:   Modules/Applications: stockmanagement, syslog, user, expedition,  tax, banque, product, stock, comptabilite, categorie, import, export,  cashdesk, blockedlog, takepos, agenda, barcode, commande, ecm, facture,  fournisseur, societe Type gestionnaire de base de données: pgsql Requête dernier accès en base en erreur: SELECT rowid,  socialnetworks, skype, twitter, facebook, linkedin, instagram, snapchat,  googleplus, youtube, whatsapp FROM llx_adherent WHERE  skype IS NOT  NULL OR skype!="" OR twitter IS NOT NULL OR twitter!="" OR facebook IS  NOT NULL OR facebook!="" OR linkedin IS NOT NULL OR linkedin!="" OR  instagram IS NOT NULL OR instagram!="" OR snapchat IS NOT NULL OR  snapchat!="" OR googleplus IS NOT NULL OR googleplus!="" OR youtube IS  NOT NULL OR youtube!="" OR whatsapp IS NOT NULL OR whatsapp!="" Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX Information sur le dernier accès en base en erreur: ERREUR:   42601: identifiant délimité de longueur nulle sur ou près de « ""  »\nLINE 1: ...M llx_adherent WHERE  skype IS NOT NULL OR skype!="" OR  twit...\n                                                              ^\nLOCATION:  scanner_yyerror, scan.l:1128  Migration des champs de réseaux sociaux utilisateurs (Members)
Dolibarr a détecté une erreur technique. You use an experimental or develop level of features, so please do NOT  report any bugs, except if problem is confirmed moving option  MAIN_FEATURES_LEVEL back to 0. Voici les informations qui pourront aider au diagnostic (Vous pouvez  fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques  notifications): Date: 20200201185356 Dolibarr: 11.0.0 Niveau de fonctionnalités: 2 PHP: 7.0.33-0+deb9u6 Serveur: Apache/2.4.25 (Debian) OS: Linux agricool 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0  Url sollicitée: /doli9/htdocs/install/upgrade2.php?versionfrom=10.0.0&versionto=11.0.0 Referer:  http://192.168.1.6/doli9/htdocs/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=10.0.0&versionto=11.0.0 Gestionnaire de menu:   Modules/Applications: stockmanagement, syslog, user, expedition,  tax, banque, product, stock, comptabilite, categorie, import, export,  cashdesk, blockedlog, takepos, agenda, barcode, commande, ecm, facture,  fournisseur, societe Type gestionnaire de base de données: pgsql Requête dernier accès en base en erreur: SELECT rowid,  socialnetworks, jabberid, skype, twitter, facebook, linkedin, instagram,  snapchat, googleplus, youtube, whatsapp FROM llx_socpeople WHERE   jabberid IS NOT NULL OR jabberid!="" OR skype IS NOT NULL OR skype!=""  OR twitter IS NOT NULL OR twitter!="" OR facebook IS NOT NULL OR  facebook!="" OR linkedin IS NOT NULL OR linkedin!="" OR instagram IS NOT  NULL OR instagram!="" OR snapchat IS NOT NULL OR snapchat!="" OR  googleplus IS NOT NULL OR googleplus!="" OR youtube IS NOT NULL OR  youtube!="" OR whatsapp IS NOT NULL OR whatsapp!="" Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX Information sur le dernier accès en base en erreur: ERREUR:   42601: identifiant délimité de longueur nulle sur ou près de « ""  »\nLINE 1: ...ocpeople WHERE  jabberid IS NOT NULL OR jabberid!="" OR  skyp...\n                                                              ^\nLOCATION:  scanner_yyerror, scan.l:1128  Migration des champs de réseaux sociaux utilisateurs (Contacts)
Dolibarr a détecté une erreur technique. You use an experimental or develop level of features, so please do NOT  report any bugs, except if problem is confirmed moving option  MAIN_FEATURES_LEVEL back to 0. Voici les informations qui pourront aider au diagnostic (Vous pouvez  fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques  notifications): Date: 20200201185356 Dolibarr: 11.0.0 Niveau de fonctionnalités: 2 PHP: 7.0.33-0+deb9u6 Serveur: Apache/2.4.25 (Debian) OS: Linux agricool 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0  Url sollicitée: /doli9/htdocs/install/upgrade2.php?versionfrom=10.0.0&versionto=11.0.0 Referer:  http://192.168.1.6/doli9/htdocs/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=10.0.0&versionto=11.0.0 Gestionnaire de menu:   Modules/Applications: stockmanagement, syslog, user, expedition,  tax, banque, product, stock, comptabilite, categorie, import, export,  cashdesk, blockedlog, takepos, agenda, barcode, commande, ecm, facture,  fournisseur, societe Type gestionnaire de base de données: pgsql Requête dernier accès en base en erreur: SELECT rowid,  socialnetworks, skype, twitter, facebook, linkedin, instagram, snapchat,  googleplus, youtube, whatsapp FROM llx_societe WHERE  skype IS NOT NULL  OR skype!="" OR twitter IS NOT NULL OR twitter!="" OR facebook IS NOT  NULL OR facebook!="" OR linkedin IS NOT NULL OR linkedin!="" OR  instagram IS NOT NULL OR instagram!="" OR snapchat IS NOT NULL OR  snapchat!="" OR googleplus IS NOT NULL OR googleplus!="" OR youtube IS  NOT NULL OR youtube!="" OR whatsapp IS NOT NULL OR whatsapp!="" Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX Information sur le dernier accès en base en erreur: ERREUR:   42601: identifiant délimité de longueur nulle sur ou près de « ""  »\nLINE 1: ...OM llx_societe WHERE  skype IS NOT NULL OR skype!="" OR  twit...\n                                                              ^\nLOCATION:  scanner_yyerror, scan.l:1128  Migration des champs de réseaux sociaux utilisateurs (Thirdparties)

Thanks for dolibarr 11
André

**Comment by woidi** [comment]
Hi eldy,
you fixed only the first of the four occurrences of this psql syntax error:
/usr/share/dolibarr/htdocs/install/upgrade2.php
```
FROM '.MAIN_DB_PREFIX.'user WHERE skype IS NOT NULL OR skype <> ''";
FROM '.MAIN_DB_PREFIX.'adherent WHERE  skype IS NOT NULL OR skype!=""';
FROM '.MAIN_DB_PREFIX.'socpeople WHERE  jabberid IS NOT NULL OR jabberid!=""';
FROM '.MAIN_DB_PREFIX.'societe WHERE  skype IS NOT NULL OR skype!=""';
```
line 5027 of upgrade2.php in function migrate_users_socialnetworks()
there's another syntax error using double quotes for text in psql, resulting in
```
ERROR: 42703: column "[]" does not exist
LINE 1: UPDATE llx_user SET socialnetworks="[]", skype=null, twitter...
```
regards W.
