### ISSUE TITLE
10.0.6: list of projects via Project "Modify" for existing proposal

### ISSUE THREAD

**Issue by 2dig4it** [Dolibarr/dolibarr#12999]
# Background
Dolibarr 10.0.6 / stable release | --> seems to be still the case in "devel" git release? (I did only a quick check)

# Brief description
Example: I have a commercial proposal, project support is enabled. I can select one of the available projects. It is correctly saved for the proposal.
BUG/ISSUE: when afterwards modifying via "MODIFY" in the list I can not select anything else, only the original project or nothing. Permissions are correct. 

For me this is also in other modules an issue (i.e., I want to change an entry in the agenda). 

In: dolibarr/htdocs/comm/propal/card.php/ :100:

#This is the current situation

#10.X: user can not select any other project, if no project is selected (i.e., accident) we can not change anything:
#$morehtmlref.=$formproject->select_projects($object->socid, $object->fk_project, 'projectid', $maxlength, 0, 1, 0, 1, 0, 0, '', 1); 

It should be: 
**$formproject->select_projects( -1, ... **	

so that the list of projects is returned to select from

#para 1: -1  --> list to select from and make changes / note: I did not check, what the other parameters should be
$morehtmlref.=$formproject->select_projects(-1, $object->fk_project, 'projectid', $maxlength, 0, 1, 0, 1, 0, 0, '', 1); 

Issue is in source code:
![screenshot](https://user-images.githubusercontent.com/60577290/73611334-3b1dfa80-45e1-11ea-983f-5a3e31d378a6.JPG)

#What I don't understand
In online shared testing environment: 

* https://www.dolibarr.org/onlinedemo 

it is no issue ?!? 
--> in an existing proposal the associated project can be modified. Do they have their own version,

**Comment by eldy** [comment]
I can't reproduce bot with 10.0.6 and nay other version. Do you use external modules ? Did you enabled hidden options ?
Can you test with v11 ?

**Comment by 2dig4it** [comment]
This is a quick follow up. I'm working on it and it is not forgotten. Issue remains with new versions.

** STEPs done: 
* I have my productive version 10.X (no transition yet). The issue is there. I now how to fix it (for me) in the source code. I spent half a Sunday. The issue for me resides everywhere you can pick projects. On initial creation everything is fine. When you want to change a project afterwards it is only blank.
* in the last days I have added a testing version of Dolibarr 11.0, which uses the latest data from version 10.X --> the issue exists for me (stable official release, not from repo, I use the old skin from 9.0, not the new one)
* in the last days I have added a clean-testing version of Dolibarr 11.0  (stable official release, not from repo): I'm adding a bit of data. Some other issues prevented quick progress. 
**Backgroundinformation:
* side information: my Dolibarr (I use the zipped version) runs on a normal webhoster (webspace with PHP & Co.) --> STRAATO
* Server info (via Dolibarr)
** Version | Apache/2.4.41 (Unix)
** PHP_OS | SunOS
** Version | SunOS localhost 5.10 Generic_150401-49 i86pc

** NOT SO IMPORTANT PERSONAL BACKGROUND INFORMATION:
I'm working a while now (1+ year) with Dolibarr from user perspective. Want to use it as new ERP in my company. Still in the process of careful transition to replace old (partially self programmed solutions). I'm planning to spend a bit of time and resources for the project. 
<<<

**Comment by 2dig4it** [comment]
> Do you use external modules?
** NO **

> Did you enabled hidden options ?
** YES, if hidden options are those under: https://wiki.dolibarr.org/index.php/Setup_Other **

This is a list (please give a hint, if there is an easier way to create a dump)
![dolibarr_issue_projects_config_productiveuse](https://user-images.githubusercontent.com/60577290/74047391-8e70be00-49d0-11ea-8a03-e68830ad6428.JPG)


> Can you test with v11 ?
Yes. *I can NOT reproduce with v11 and a clean install. I Can reproduce with v11 and migrated data from v10 (productive installation)*

*In case of testing with v11 in a clean install* (in my environment which is a hosted webspace)* I have the issue that I can not assign a project to a proposal (list is there, projects are disabled - visible but not selectable). So I can not reach the point, allowing further tests for this current issue, without editing in the database. 
Note: projects are *public, and I'm logged in in Dolibarr as Sysadmin*.

![dolibarr_issue_projects_not_chooseable](https://user-images.githubusercontent.com/60577290/74046951-ccb9ad80-49cf-11ea-998a-28a880b21a95.JPG)

**Comment by 2dig4it** [comment]
**I disabled experimental features and set MAIN_FEATURES_LEVEL to 0 in the hidden options** 

Afterwards **it works in 11.0** - the list of projects is shown and I can another project via Modify for an existing proposal.

So in dependence of issue treatment - this issue could also be closed (if behavior with MAIN_FEATURES_LEVEL=1) is not of relevance.
