### ISSUE TITLE
Email - Language inconsistencies in body

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#12990]
# Bug
When using a language different than the client's language (for example user interface in English, customer default being french), the email is created in two languages (English and french).

## Environment
- **Version**: 10.0.3 (although I am sure it happened in previous versions as well)
- **OS**: Ubuntu Server 18.04 LTS
- **Web server**: Apache 2.4.9
- **PHP**: PHP 7.2
- **Database**: MySQL 5.7
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Actual: I use Dolibarr in English. My customers are mostly either speaking french or Spanish, with a few English speakers lost in the middle. When mails are generated by dolibarr (proposal, invoices, etc...), the mail created from the templates picks up both my language and the customer language to populate the body of the mail.
Expected: the entire mail should be in the customer language.

## Steps to reproduce the behavior
Connect to Dolibarr in one language (English for example)
Create an invoice for a customer with french as a default language.
Click the send by mail button, ans the body will be filled in two languages. English will be used for salutations (Hello) and goodbyes (Sincerely), while the rest of the text will be in french. 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Selection_052](https://user-images.githubusercontent.com/5640062/73595261-dac28680-4516-11ea-82db-012b51f89841.png)

**Comment by eldy** [comment]
Can you provide a screenshot of your email template (home - setup - email tempaltes) ?
Does this template contains the text __(Hello)__ at the top to ask to show the Translated string "Hello" ?

**Comment by dom-breizh** [comment]
I do not use custom templates, just the ones included by default in Dolibarr. But here is the screenshot anyway.
![FireShot Capture 022](https://user-images.githubusercontent.com/5640062/73664322-7bdc4900-469f-11ea-9cb8-096a5738c164.png)
