### ISSUE TITLE
How to assign resources to events?

### ISSUE THREAD

**Issue by BryanLHY** [Dolibarr/dolibarr#13003]
According to [this page](https://www.dolibarr.org/57-documentation/features/219-events), "You can also activate the module Resource so you can assign resources to your events." 

I have activated all 3 modules (i.e. Projects or Leads, Events/Agenda, Resources) under "Projects/Collaborative work". I have also created projects and added resources. But, I cannot find where I can assign resources to events.

Here is a screenshot of the interface when trying to add a new event.
![Screenshot 2020-02-03 at 11 36 43 AM](https://user-images.githubusercontent.com/53143180/73623864-7ec44300-4679-11ea-85e8-a88895718558.png)

**Comment by eldy** [comment]
Once event is created, just go on tab "Resources".

**Comment by BryanLHY** [comment]
@eldy Thank you.
