### ISSUE TITLE
A non-numeric value encountered in /htdocs/core/class/commonobject.class.php on line 6689

### ISSUE THREAD

**Issue by laurantines** [Dolibarr/dolibarr#13007]
#12432 Bug
Warning: A non-numeric value encountered in /htdocs/core/class/commonobject.class.php on line 6689

`$out .= $extrafields->showSeparator($key, $this, ($colspan + 1));`

3 parameters are sent in showSeparator function, but the last one is left over.

```
public function showSeparator($key, $object)
	{
		global $langs;

		$out = '<tr class="trextrafieldseparator trextrafieldseparator'.$key.'"><td colspan="2"><strong>';
		$out.= $langs->trans($this->attributes[$object->table_element]['label'][$key]);
		$out.= '</strong></td></tr>';
		return $out;
	}
```

## Environment
- **Version**: 11.0

**Comment by RubenRuCh** [comment]
I have version 11.0 but we have different things there...

In commonobject.class.php I have:

`$out .= $extrafields->showSeparator($key, $this, ($colspan + 1));`


But in extrafields.class.php (where showSeparator is declared) I have this:

> 	public function showSeparator($key, $object, $colspan = 2)
	{
		global $langs;

		$out = '<tr id="trextrafieldseparator'.$key.'" class="trextrafieldseparator trextrafieldseparator'.$key.'"><td colspan="'.$colspan.'"><strong>';
		$out .= $langs->trans($this->attributes[$object->table_element]['label'][$key]);
		$out .= '</strong></td></tr>';

        $extrafield_param = $this->attributes[$object->table_element]['param'][$key];
        if (!empty($extrafield_param) && is_array($extrafield_param)) {
            $extrafield_param_list = array_keys($extrafield_param['options']);

            if (count($extrafield_param_list) > 0) {
                $extrafield_collapse_display_value = intval($extrafield_param_list[0]);
                if ($extrafield_collapse_display_value == 1 || $extrafield_collapse_display_value == 2) {
                	// Set the collapse_display status to cookie in priority or if ignorecollapsesetup is 1, if cookie and ignorecollapsesetup not defined, use the setup.
                	$collapse_display = ((isset($_COOKIE['DOLCOLLAPSE_'.$object->table_element.'_extrafields_'.$key]) || GETPOST('ignorecollapsesetup', 'int')) ? ($_COOKIE['DOLCOLLAPSE_'.$object->table_element.'_extrafields_'.$key] ? true : false) : ($extrafield_collapse_display_value == 2 ? false : true));
                    $extrafields_collapse_num = $this->attributes[$object->table_element]['pos'][$key];

                    $out .= '';
                    $out .= '<script type="text/javascript">';
                    $out .= 'jQuery(document).ready(function(){';
                    if ($collapse_display === false) {
                        $out .= '   jQuery("#trextrafieldseparator'.$key.' td").prepend("<span class=\"cursorpointer fa fa-plus-square\"></span>&nbsp;");'."\n";
                        $out .= '   jQuery(".trextrafields_collapse'.$extrafields_collapse_num.'").hide();'."\n";
                    } else {
                    	$out .= '   jQuery("#trextrafieldseparator'.$key.' td").prepend("<span class=\"cursorpointer fa fa-minus-square\"></span>&nbsp;");'."\n";
                    	$out .= '   document.cookie = "DOLCOLLAPSE_'.$object->table_element.'_extrafields_'.$key.'=1; path='.$_SERVER["PHP_SELF"].'"'."\n";
                    }
                    $out .= '   jQuery("#trextrafieldseparator'.$key.'").click(function(){'."\n";
                    $out .= '       jQuery(".trextrafields_collapse'.$extrafields_collapse_num.'").toggle(300, function(){'."\n";
                    $out .= '           if (jQuery(".trextrafields_collapse'.$extrafields_collapse_num.'").is(":hidden")) {'."\n";
                    $out .= '               jQuery("#trextrafieldseparator'.$key.' td span").addClass("fa-plus-square").removeClass("fa-minus-square");'."\n";
                    $out .= '               document.cookie = "DOLCOLLAPSE_'.$object->table_element.'_extrafields_'.$key.'=0; path='.$_SERVER["PHP_SELF"].'"'."\n";
                    $out .= '           } else {'."\n";
                    $out .= '               jQuery("#trextrafieldseparator'.$key.' td span").addClass("fa-minus-square").removeClass("fa-plus-square");'."\n";
                    $out .= '               document.cookie = "DOLCOLLAPSE_'.$object->table_element.'_extrafields_'.$key.'=1; path='.$_SERVER["PHP_SELF"].'"'."\n";
                    $out .= '           }'."\n";
                    $out .= '       });';
                    $out .= '   });';
                    $out .= '});';
                    $out .= '</script>';
                }
            }
        }

		return $out;
	}


I don't know why do you have a different extrafields.class.php file. Did you fresh install Dolibarr or did you update from v10?

**Comment by laurantines** [comment]
I updated from v10.

**Comment by RubenRuCh** [comment]
Could you try a fresh install and tell if the problem persist? Maybe the problem come from an incorrect update process. I just checked and in 11.0 of github everything it's okay.

**Comment by dpriskorn** [comment]
Reopen if still a problem after update to v12.

**Comment by MCMDevCorp** [comment]
Still present in 12.0.3 - commonobject.class.php on line 7145
$out .= $extrafields->showSeparator($key, $this, (**$colspan** + 1));
seems that $colspan is not-numeric, changing it to fixed value e.g. 1 does the trick (dirty workaround) a fix would be nice.

**Comment by manu-p** [comment]
Hi, same bug for me on a 13.0.1.

Same volatile workaround as mentioned by @MCMDevCorp  or, initialize `$colspan` to int 0 instead of `''` at line 6810.

Please re-open the issue and solve it.
