### ISSUE TITLE
Not able to backup MariaDB database

### ISSUE THREAD

**Issue by grossbouff** [Dolibarr/dolibarr#13019]
# Bug
Not able to backup MariaDB database : error message and file .err is created

## Environment
- **Version**: 11.0
- **OS**: Windows NT DESKTOP-1AJM5V0 10.0 build 18362 (Windows 10) AMD64
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.1
- **PHP**: Php 7.4.1
- **Database**: MariaDB 10.4.11
- **URL(s)**: dolibarr/admin/tools/dolibarr_export.php

## Expected and actual behavior
Not sure if MariaDB is an approved configuration, but everything is working correctly except when I try to backup the database (dolibarr/admin/tools/dolibarr_export.php), the result is the following : 
- error file is generated (...sql.gz.err) - but the result file is correct
- red error message displayed with the following content : Erreur : -- MariaDB dump 10.17 Distrib 10.4.11-MariaDB, for Win64 (AMD64)

I would suggest following fix in core/class/utils.class.php (or a better way of doing it...)
`				if ($ok && ( preg_match('/^-- MySql/i', $errormsg) || preg_match('/^-- MariaDB/i', $errormsg))) $errormsg = ''; // Pas erreur`
instead of
`				if ($ok && preg_match('/^-- MySql/i', $errormsg)) $errormsg = ''; // Pas erreur
`

At least for me my backups are now ok.

Hope it helps

**Comment by MadFlasher** [comment]
Same problem with 10.0.6 since upgrade MariaDB
Ubuntu 18.04 - 5.5.5-10.4.12-MariaDB-1:10.4.12+maria~bionic-log
From stock MariaDB (Ubuntu source) no error

grossbouff patch perfect here !
