### ISSUE TITLE
Changing a user login (Nutzernamen) after creation and saving - input field length issue in new default skin theme:eldy

### ISSUE THREAD

**Issue by 2dig4it** [Dolibarr/dolibarr#13028]
# Bug (or wanted change??)

In 11.0 are longer usernames not allowed anymore? For example: Dolibarr Versions prior 11 (10 and 9) it was possible to have the following name (side info: login/username equals email address in my usecase):
XXXXXXXXX.sauer@domain.de
123456789.12345@123456.78

Step (1): Due to bug-hunt in another issue, I did a clean install of 11.0 and added some simple data, I a new user. I added the user with a short user name (login) Sauer (actually by accident)
Step (2) Afterwards, I wanted to change to the longer username (basically email address). 

The maximum length in the input field (see screenshot) was this, longer length is not allowed.
123456789.12345@123456.7
(no longer inputs possible in input field)

![dolibarr_bug_issue](https://user-images.githubusercontent.com/60577290/73797105-62c2bd80-47af-11ea-8f09-9bd8b77edf9b.JPG)

## Environment
- **Version**:  11.0 / 10.X? / NOT: 9.X

Additional information can be supplied on request.

**Comment by hregis** [comment]
@2dig4it 
you must put the email address in the "email" field, you can use the login OR the email address on the login page!

**Comment by 2dig4it** [comment]
@hregis: I am sorry, I try to be more specific. I meant the allowed number of characters for a login name (field length).

In order to recreate:
1. create a new user with login: 
abcdefghijklmnopqrstuvwxyz1234567890

this is possible, user can be created. See screenshot.
![step1_user_created](https://user-images.githubusercontent.com/60577290/73948652-898d0b00-48f9-11ea-8d96-25dd4861d5da.JPG)

2. Trying to modify this users login - there is than a limit of the max. allowed characters.
I have to change to a shorter name. Is not logical since step 1 was possible.

Sideinformation:
In my usecase - I can not modify a user login in accordance to a naming convention, already established in the company
