### ISSUE TITLE
__AMOUNT_FORMATED__ formatted incorrectly

### ISSUE THREAD

**Issue by paddatrapper** [Dolibarr/dolibarr#13025]
The`__AMOUNT_FORMATED__` variable substitution incorrectly places the currency symbol after the amount. In en_ZA locale, the correct formatting should be R 23,000.00, while, the variable is substituted as 23,000.00 R. This is also an issue within the UI, where pop-ups and other places where formatted amounts are shown (For example the invoice card).

## Environment
- **Version**: 11.0.0
- **OS**: Ubuntu (Docker/Kubernetes)
- **Web server**: Apache behind Nginx reverse proxy
- **PHP**: 7.3.14
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB-1:10.4.10+maria~bionic
- **URL(s)**: https://example.com/compta/facture/card.php

**Comment by lyza1000** [comment]
Hi... 
Does this variable work in any version of Dolibarr?

**Comment by paddatrapper** [comment]
I'm not sure

**Comment by derran666** [comment]
Hi, has any one found a fix for this as yet?

**Comment by paddatrapper** [comment]
Still present

**Comment by paddatrapper** [comment]
A potential solution here would be to add another formatted variable with no currency, then the user can add the currency in the template in the correct location. `__AMOUNT__` does not work here, as it does not round to the required number of decimal places (123.00000000 is not really helpful to the client).

The new variable could be used as:

```
R __AMOUNT_EXCL_CURRENCY_FORMATED__
```

Which would then render as `R 123.45`

**Comment by paddatrapper** [comment]
It is still present

**Comment by paddatrapper** [comment]
Still present

**Comment by dpnullvoid** [comment]
Same in  es_CL locale, the correct formatting should be $ 109.862, while, the variable is substituted as $109862.00000000
Env

```
    Version: 18.0.3 
    OS: CloudLinux 3.10.0-962.3.2.lve1.5.81.el7.x86_64
    Web server: Apache
    PHP: 7.2
    Database: MySQL or MariaDB 10.6.16-MariaDB-cll-lve
```

**Comment by PsyCrow-code** [comment]
Works fine on version 19
PHP: 8.1
es_MX

**Comment by kkhelifa-opendsi** [comment]
It's correct on develop (version 21)

Setup -> Company/Organization :
![image](https://github.com/user-attachments/assets/ab4e68f8-bc39-4fd9-aeea-85fbf9d3c101)

Setup -> Display :
![image](https://github.com/user-attachments/assets/cc0bc221-caf8-48df-bbf3-32628e1b9b51)

Setup -> emails -> email templates :
![image](https://github.com/user-attachments/assets/9d8cb48b-770f-45b9-89e5-6ee261f89075)

New commercial proposal :
![image](https://github.com/user-attachments/assets/e4bebbd0-c994-4c28-9444-04cdd361923e)
![image](https://github.com/user-attachments/assets/644b9084-f060-4290-b494-6920f90287e0)

It's also good es_CL with dollards currency
