### ISSUE TITLE
Sometimes MAIN_GENERATE_DOCUMENTS_HIDE_REF is ignored

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#13055]
# Bug
Although I have MAIN_GENERATE_DOCUMENTS_HIDE_REF set to 1, I have most of the time invoices with reference of services included.
When this is the case, Regenerate the PDF in the invoice card produces a PDF which is in the line of to the directive.

## Environment
- **Version**: v 8.0.3
- **PHP**: 7.3
- **Database**: MariaDB

## Expected and actual behavior
The PDF should follow the directive in any cases.

## Steps to reproduce the behavior
Set the PDF behaviour to hide reference of products.
Create a proposal with registered services.
Accept it, Create an invoice from the proposal. Valid the invoice. Open the PDF. It doesn't follow the directive.

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
