### ISSUE TITLE
Searching for extrafields of type "select" in list view not working

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#13058]
# Bug
Searching for extrafields of type "select" in list view not working

## Environment
- **Version**: all versions
- **OS**: n/a
- **Web server**: n/a
- **PHP**: all versions
- **Database**: n/a
- **URL(s)**: all list views (list.php)

## Expected and actual behavior
Searching for values of extrafield "select" requires to enter the id instead of the text

## Steps to reproduce the behavior
1. Create an extrafield with type "select" (e.g. in contacts)
2. Param of extrafield could be e.g.
   1,first entry
   2,second entry
3. Add values to the new extrafield of some contacts 
4. Open list view with extrafield (in this example contact/list.php)
5. Enable the new extrafield
6. Search for a value (e.g. "first")

No results are shown.

Expected behavior would be to find all entries matching the search string.

**Comment by eldy** [comment]
In v10, the behaviour was to search on the key.
So if extrafield is 
1,first entry
2,second entry
You must search on 1 and 2.
This is not really good, but it was first step before v11 where we introduced the dropdown combo where we need to search on id.

This behaviour must be kept in v10 as an "implemented like this on purpose ti prepare future".
I keep the ticket open if problem still occurs in v11.0.1 
To check but i don't think so.
