### ISSUE TITLE
https:// usage in combination with PROPOSAL_ALLOW_EXTERNAL_DOWNLOAD (possibly other modules with *_ALLOW_EXTERNAL_DOWNLOAD)

### ISSUE THREAD

**Issue by 2dig4it** [Dolibarr/dolibarr#13057]
Running Dolibarr (11.0 and 10.X) on a website using **https://** and enabled option **PROPOSAL_ALLOW_EXTERNAL_DOWNLOAD** the generated link (for external direct download of i.e., of a proposal) use **http://**.

This external download link is not working. Adding the **s** resolves the issue.

This was testet with the proposal module (only) and could also affect invoices and others.

See attached image (yellow marking).
![dolibarr_https_issue](https://user-images.githubusercontent.com/60577290/74045520-34bac480-49cd-11ea-8b1b-ec63718998e3.JPG)

**Comment by eldy** [comment]
You probably have a bad setup in your conf/conf.php file.
Do you have the url with s into this config file ?

**Comment by edupulpillo** [comment]
I have observed the same problem with the links generated using the feature "share via link" of files attached to a Proposal or invoice. 
As eldy suggest, updating the url in conf/conf.php $dolibarr_main_url_root='https://... the problem is fixed.

**Comment by 2dig4it** [comment]
It was the bad setup in conf/conf.php $dolibarr_main_url_root=https://...

Cause of the event chain leading to the observed behavior (possibly):
* initial installation on http://... webspace
* after some time of usage changed to https:// website version (SSL upgrade)
* could use https:// website version with bad conf/conf.php setting (see above) in productive version
* issue became noticeable in productive version when PROPOSAL_ALLOW_EXTERNAL_DOWNLOAD was not working

--> so closed, maybe a small automatic check helpful in the future?
