### ISSUE TITLE
Assigning a user to a warehouse is no longer possible in V11

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#13062]
# Bug
Assigning a user to a warehouse is no longer possible in V11

## Steps to reproduce the behavior
On a user it was possible to assign a warehouse this is no longer the case in V11

Sur un utilisateur il etait possible d'affecter un entrepot ce n'est plus le cas dans la V11

It is urgent we use it in certain documents and know where the user is physically

C'est urgent nous l'utilison dans certain documents et savoir ou est l'utilisateur phisiquement

**Comment by eldy** [comment]
It seems the feature to have a warehouse into a user card is not used anywhere in code.
For this reason, the field has been hidden by a constant USER_DEFAULT_WAREHOUSE that you can set to 1 in home-setup-const to retrieve the field visible.
Can you describe what is your use case that need such a field by default and that can't be implemented with an extrafield ?

**Comment by BB2A-Anthony** [comment]
I use in documents and i add a code is using for default warehouse in order
