### ISSUE TITLE
Add "already paid" or/and "remaining" in Loans table

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#13099]
## Feature Request
Add "already paid" or/and "remaining" in Loans table dolibarr/htdocs/loan/list.php

## Use case
A quicker way to see the loan balance in the main table (no need to go to each loan to see the amount already paid)

## Suggested implementation
Add "already paid" or/and "remaining" in Loans table

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by futurehousestore** [comment]
Not implemented yet.

**Comment by atm-maxime** [comment]
I guess it's still needed, we must also have the remaining capital calculated and stored. I guess it's a value needed for accountancy
