### ISSUE TITLE
BUG: Left menu not visible on small screen (mobile)

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#13098]
## Bug
The left menu is not visible on mobile devices (tested on iPhone 6S Plus and iPhone XR)

## Environment
- **Version**: 11.0.0, 10.0.7 (previous versions 10.0.1, 10.0.2, etc. also affected but it was working in version 9.0.x or 8.0.x)
- **OS**: Linux server2.turro.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.2.27-MariaDB
- **URL(s)**: /htdocs/fourn/facture/card.php

## Expected and actual behavior
Expected: left menu visible and accessible
Actual: left menu not visible/accessible on mobile devices in vertical and horizontal mode

## Steps to reproduce the behavior
log in to your dolibarr on mobile devices such as iPhone 6S Plus or iPhone XR

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![IMG_1444](https://user-images.githubusercontent.com/28427270/74391263-8dd68e00-4dfb-11ea-811a-7c44c4f0a61e.jpg)
![IMG_1445](https://user-images.githubusercontent.com/28427270/74391264-8f07bb00-4dfb-11ea-9997-b3552169138d.jpg)

**Comment by eldy** [comment]
On the second screenshot everything looks as expected. The left menu is hidden and you can see it by clicking on the hamburger picto.
The first screenshot looks strange. What is the device for first one ? What is the browser / version ?

**Comment by futurehousestore** [comment]
Thanks @eldy yes with the second screenshot (vertical view) I made a mistake (the hamburger picto is not visible in version 10 but it works in version 11). The first screenshot (horizontal) is from iPhone XR Safari on iOS 13.3.1. The CSS error applies for both v10 and v11. In horizontal view in version 11 I can see new Open Items table but as you can see on the screenshot it isn't as it should be. In horizontal view in version 10 I cannot see Open Items table. In both versions the rest of the widgets are not visible (white page) but when you scroll down to the bottom of the page you can see the note which you can see in Desktop version if you don't add the install.lock file. Below screenshots from v10.
![1](https://user-images.githubusercontent.com/28427270/74434884-408a0900-4e5b-11ea-9f6d-382026c4e601.PNG)
![2](https://user-images.githubusercontent.com/28427270/74434893-4384f980-4e5b-11ea-9706-60b6a4cfe31d.PNG)
![3](https://user-images.githubusercontent.com/28427270/74434899-44b62680-4e5b-11ea-9487-d2fa1b0610fd.PNG)
![4](https://user-images.githubusercontent.com/28427270/74434903-45e75380-4e5b-11ea-95c2-46a3cc583429.PNG)

**Comment by eldy** [comment]
Do you login to your phone and rotate to be horizontal after ?
Can you try this. Logout - Rotate so screen is horizontal - Then login.  Is it better ?
Also can you try to go on Home -  Admin tools - Info browser. What do you have on field "Layout (phone/tablet/classic)"

**Comment by futurehousestore** [comment]
I did as you advised. I did rotate the screen before logging in and it looks much better and the widgets are visible but it's not fully responsive (most of the widgets are not fully visible)
v11
![IMG_1510](https://user-images.githubusercontent.com/28427270/74466049-6d0b4880-4e8e-11ea-8cc1-94bc1aa8ede7.PNG)

![IMG_1511](https://user-images.githubusercontent.com/28427270/74466053-6f6da280-4e8e-11ea-8438-dacf516bba52.PNG)

![IMG_1512](https://user-images.githubusercontent.com/28427270/74466057-71376600-4e8e-11ea-85e6-a4277746cbee.PNG)

v10
![IMG_1514](https://user-images.githubusercontent.com/28427270/74466074-785e7400-4e8e-11ea-88e8-897f24347387.PNG)

v10 after zooming out (zooming out with two fingers)

![IMG_1515](https://user-images.githubusercontent.com/28427270/74466118-91ffbb80-4e8e-11ea-9c13-d2b1dd131b4b.PNG)

**Comment by eldy** [comment]
Look strange.
I do not experience any troubles with other devices. Can you clear your browser cache ?
Someone else has same trouble with Iphone XR ?

**Comment by futurehousestore** [comment]
I think I know what causes the problem. @eldy delete install.lock file and try it once again on your mobile phone. When I was testing it I didn't have the install.lock file created but when I created it and refreshed the site it all looks good now.

**Comment by eldy** [comment]
And what if you restore the install.lock file ? and refresh again ?

**Comment by futurehousestore** [comment]
If you restore install.lock then all looks good as on the desktop.

**Comment by eldy** [comment]
So i close ticket
