### ISSUE TITLE
Bug permission utilisateur pour modifier son profil/son mot de passe.

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#13094]
# Bug
Les permissions "Créer/modifier ses propres informations utilisateur" et "Modifier son propre mot de passe" ne permettent pas à un utilisateur de modifier son profil / son mot de passe.

## Environment
- **Version**: 11.0.0
- **OS**: Debian 10
- **Web server**: Apache2 2.4.38
- **PHP**: 7.4.2
- **Database**: MariaDB 10.3.22
- **URL(s)**: /user/card.php?id=2

## Expected and actual behavior
J'ai voulu mettre les droits à l'utilisateur de modifier son profil ainsi que son mot de passe via les permissions d'un groupe. Malheureusement, l'utilisateur ne peut pas modifier son profil malgré les permissions.
Le seul moyen pour qu'il puisse modifier son profil est d'avoir la permission de modifier TOUS les profils.

## Steps to reproduce the behavior
- Créer un groupe
- Créer un utilisateur
- Ajouter les permissions au groupe : "Créer/modifier ses propres informations utilisateur" et "Modifier son propre mot de passe"
- Ajouter l'utilisateur au groupe
- Se connecter avec l'utilisateur
- Aller sur /user/card.php?id=2
- Modifier son profil
- Enregistrer

L'erreur arrive après avoir cliqué sur le bouton enregistrer.
Erreur qui indique que la personne n'a pas les droits/ n'est pas authentifié...
Je n'ai plus l'erreur sous les yeux étant repassé sur la version précédente en vitesse.

**Comment by ghost** [comment]
Bonjour, les modifications ont-elles été merged dans la branch 11.0.0 ? Car j'ai voulu refaire le test en local avec la version 11.0.0 et je vois que le bug est toujours présent.
![image](https://user-images.githubusercontent.com/56432016/74424460-48917b00-4e52-11ea-82cb-6365995c0870.png)
![image](https://user-images.githubusercontent.com/56432016/74424491-5810c400-4e52-11ea-867c-26cc33485286.png)

**Comment by 00-Null** [comment]
Je viens de voir qu'il ne s'agissait que de commits :(. Avez-vous une date probable d'un push ?

**Comment by ghost** [comment]
Problème résolu dans la version 11.0.1. Merci pour l'update ! 👍
