### ISSUE TITLE
Add the B2B scheme for SEPA payments

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#13105]
# Feature Request
Right now, SEPA direct debit only works with the Core scheme, since that's what all entities offering SEPA direct debit must offer. However, Business to Business (B2B) transactions have access to a different scheme for faster payments.

## Suggested implementation
-There needs to be two extra modes for the account: B2B FRST and B2B RCUR
-Mandate text is slightly different, you can check the official translations for the B2B mandates [here](https://www.europeanpaymentscouncil.eu/other/sepa-b2b-dd-mandate-translations) 
-XML files need to replace <LclInstrm><Cd>CORE</Cd></LclInstrm> with <LclInstrm><Cd>B2B</Cd></LclInstrm> (maybe some other changes are required, not an expert here)

**Comment by lmag** [comment]
I confirm we improve the standard Dolibarr pdf for SEPA.
We should have 2 types of SEPA : 

- [ ] [SEPA Core Direct Debit](https://www.cfonb.org/sites/www.cfonb.org/files/documents/1.%20Brochure%20Pr%C3%A9l%C3%A8vement%20SEPA%20SDD%20Core%20V9.0%20version%20de%20Juin%202023_0.pdf) Version 9.0
Applicable à partir du 19 novembre 2023 
- [ ] [SEPA BUSINESS TO BUSINESS DIRECT DEBIT](https://www.cfonb.org/sites/www.cfonb.org/files/documents/5.%20Brochure%20Pr%C3%A9l%C3%A8vement%20SEPA%20Business%20to%20Business%20Direct%20Debit%20%28B2B%29%20V7.0%20de%20Juin%202023_0.pdf) Version 7.0 Applicable à partir du 19 novembre 2023
- [ ] put the good text link to BtoB see in page 45/53

Field missing 
- [ ] Add text for french CNIL in page 44/55
- [ ] Add Email of DPO

Links
https://www.cfonb.org/sepa/le-sepa

**Comment by priojk** [comment]
I would like to reopen this point and to enable B2B as well as CORE. Regarding the XML a validation checker indicated that it's indeed just a change in this one XML field, which is required (apart from the formalities regarding the mandate).

In addition it's now possible according to the SEPA standard to only use RCUR (without an initial FRST), which makes life much simpler.
