### ISSUE TITLE
Probleme export compta FEC, Quadra)

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#13107]
Problème d'accent rencontré lors de l'export du grand liste au format Quatratus en V11.0.0

Des accents peuvent apparaitre dans la denière colonne du fichier Quadra qui est un champ pouvant contenir des refs autres que numeriques.

J’ai donc modifié accountancyexport.class.php à la ligne 531 de:

`$Tab['num_piece3'] = substr(self::trunc($data->doc_ref, 20), -10);`

en

`$Tab['num_piece3'] = str_pad(self::trunc(dol_string_unaccent(substr(self::trunc($data->doc_ref, 20), -10)), 30), 30);
`

Cordialement,
Kévin

**Comment by atm-maxime** [comment]
Thanks for this info, please use English to report and share issues.
