### ISSUE TITLE
SQL error on produit marges PGSQL

### ISSUE THREAD

**Issue by devzhr** [Dolibarr/dolibarr#13102]
# Bug
[*SQL error on produit marges*]

## Environment
- **Version**: 9.0.4
- **OS** : debian 10 
- **Web server**: nginx/1.14.0
- **PHP**: 7.4.1
- **Database**: PostgreSQL 12.1
--
- **URL(s)**: http://localhost:90/margin/tabs/productMargins.php?id=1

## Expected and actual behavior
[*ERREUR: 42883: la fonction if(boolean, integer, integer) n'existe pas\nLINE 1: ...statut, f.type, sum(d.total_ht) as selling_price, IF(f.type ...\n ^\nHINT: Aucune fonction ne correspond au nom donné et aux types d'arguments.\nVous devez ajouter des conversions explicites de type.\nLOCATION: ParseFuncOrColumn, parse_func.c:528*]

**Comment by eldy** [comment]
Do you have trouble with 11.0.1 ?

**Comment by devzhr** [comment]
i don't have 11.0.1 i have 9.0.4

**Comment by devzhr** [comment]
I found the solution is:
 ```
$sql.= " IF(f.type = 2, -1, 1) * sum(d.qty) as qty,";						// not always positive in case of Credit note
 $sql.= " IF(f.type = 2, -1, 1) * sum(d.qty * d.buy_price_ht) as buying_price,";			// not always positive in case of Credit note
 $sql.= " IF(f.type = 2, -1, 1) * sum(abs(d.total_ht) - (d.buy_price_ht * d.qty)) as marge" ;	// not always positive in case of Credit note
```
with :

```php
$sql.= " ".$db->ifsql('f.type = 2', -1, 1)." * sum(d.qty) as qty,";						// not always positive in case of Credit note
$sql.= " ".$db->ifsql('f.type = 2', -1, 1)." * sum(d.qty * d.buy_price_ht * (d.situation_percent / 100)) as buying_price,"; // not always positive in case of Credit note
$sql.= " ".$db->ifsql('f.type = 2', -1, 1)." * sum(abs(d.total_ht) - (d.buy_price_ht * d.qty * (d.situation_percent / 100))) as marge"; // not always positive in case of Credit note
```
