### ISSUE TITLE
Erreur lors de l'inscription des paiements divers (journal de tresorerie) dans le grand livre

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#13108]
Bonjour,

J'ai constaté depuis la V10.0.6 que lors de l'inscription de lignes de "paiement divers" dans le grand livre, des erreurs aparraissement.

Lorsque l'on relance l’inscription dans le grand livre (après les messages d’erreur), la ventilation s’effectue, mais avec des erreurs dans les comptes (ventilés au mauvais endroit).

a la ligne 666 du bankjournal.php j’ai modifié:

`$bookkeeping->numero_compte = $tabpay[$obj->rowid][« account_various »];`

en

`$bookkeeping->numero_compte = $tabpay[$key][« account_various »];`

Desormais, plus d’erreur lors de l’inscription, et les operations sont ventilées sur les bons comptes dans le GL.

**Comment by atm-maxime** [comment]
Thanks for this info, please use English to report and share issues.
If you have the skills, you can push your code modifications through a pull request.

**Comment by eldy** [comment]
PR has been included into 11.0 branch.
