### ISSUE TITLE
Add "instructions" for the company logo in company setup

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#13117]
# Feature Request
It would be nice to add the note about the supported size of logos in to /dolibarr/htdocs/admin/company.php?mainmenu=home&leftmenu=setup&idmenu=39267
At the moment even original Dolibarr logo is too big 
<img width="811" alt="Screenshot 2020-02-14 at 22 05 23" src="https://user-images.githubusercontent.com/28427270/74571789-209b3800-4f76-11ea-969d-d8bacefc0034.png">

## Use case
The specified size on question mark hover would help to get to right logo size in first go.  

## Suggested implementation/steps
Add supported size in the question mark box. At the moment these question mark boxes contain only "png, jpg"
<img width="553" alt="Screenshot 2020-02-14 at 21 55 32" src="https://user-images.githubusercontent.com/28427270/74571460-c0a49180-4f75-11ea-9cb9-3d47950a4c6f.png">

**Comment by eldy** [comment]
Whatever is the size of logo, you should not have overlapping.
Can you try with dolibarr 11.0.2 (soon released).

**Comment by futurehousestore** [comment]
Still not implemented in version 13.0.1
