### ISSUE TITLE
Account transactions - unable to select all lines to reconcile them at once

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#13116]
# Bug
Account transactions - unable to select all lines to reconcile them at once. This option (click on one tick box to select all) was available in version 10 but it's gone in version 11

## Environment
- **Version**: 11.0.1
- **OS**: Linux server2.turro.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.2.27-MariaDB
- **URL(s)**: /dolibarr/htdocs/compta/bank/bankentries_list.php?action=reconcile&sortfield=b.datev,b.dateo,b.rowid&sortorder=asc,asc,asc&search_conciliated=0&contextpage=banktransactionlist&id=3&search_account=3

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
<img width="1425" alt="Screenshot 2020-02-14 at 21 39 07" src="https://user-images.githubusercontent.com/28427270/74569914-702c3480-4f73-11ea-9e97-737856e887fa.png">

**Comment by eldy** [comment]
Click on the button "Reconcile" on top of the list so you will switch into the view to make the reconciliation and the checkbox will appear.

**Comment by futurehousestore** [comment]
It doesn't work for me even in the demo https://drive.google.com/open?id=1hwq-U7YfqoCDEG-J0kDGTX61iw92z_WS

**Comment by futurehousestore** [comment]
Am I really the only one who has this issue? I have checked on version 11 and 12, on Chrome and Opera, on my server and in the Demo and the bug exists in both versions but works fine in version 10

**Comment by futurehousestore** [comment]
Still not fixed in version 13.

**Comment by eldy** [comment]
> It doesn't work for me even in the demo https://drive.google.com/open?id=1hwq-U7YfqoCDEG-J0kDGTX61iw92z_WS

In the video we can see that if no line is selected, reconciliation try return a message and at the end, when a line is selected, in this case, reconciliation is done correctly. This is the expected behaviour. So what's wrong ?

**Comment by futurehousestore** [comment]
In version 10 after clicking on RECONCILE, there was an option to select all lines
![version10](https://user-images.githubusercontent.com/28427270/98455274-5ddbd180-2166-11eb-851d-67198070f597.PNG)
In version 11, 12 and 13 after clicking on RECONCILE, the option to select all lines is not there and the lines need to be selected one by one
![version12](https://user-images.githubusercontent.com/28427270/98455288-7c41cd00-2166-11eb-9efd-74a035f212ac.PNG)

**Comment by futurehousestore** [comment]
Fixed in version 13 beta
