### ISSUE TITLE
Payment discrepancy in payments with multicurrency

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#13128]
# Bug
Just made a payment to my supplier today and used the available in version 11 option to input the payment in original currency. Unfortunately, there is some discrepancy and the calculated amount in Dolibarr currency is different than the amount paid in original currency (please, check the images below) 

## Environment
- **Version**: 11.0.1
- **OS**: Linux server2.turro.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.2.27-MariaDB
- **URL(s)**: /dolibarr/htdocs/fourn/facture/paiement.php?facid=371&action=create&accountid=3

## Expected and actual behavior
The amount paid and input into "Payment amount, original currency" was 197.44zl which gave the £39.85 "Already paid" (the currency exchange rate is set to £1 = 4.95zl) and the calculated amount in pounds is incorrect. The amount in Dolibarr currency should be £39.89 (197.44/4.95=39.8868687)

## Steps to reproduce the behavior
Set the supplier currency in multicurrency module, create a supplier invoice from the purchase order, go to created supplier invoice and enter payment using supplier currency "Payment amount, original currency"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![dolibarr currency rate](https://user-images.githubusercontent.com/28427270/74670625-7869b700-51a1-11ea-8629-40fd53ce0d5b.JPG)
![dolibarr currency](https://user-images.githubusercontent.com/28427270/74670629-7b64a780-51a1-11ea-8f35-f29b4e9dcf15.JPG)

**Comment by eldy** [comment]
Can you provide the detail of each payment ? (the array visible on the invoice for this line)

**Comment by futurehousestore** [comment]
Is that what you mean? 
![1](https://user-images.githubusercontent.com/28427270/74798219-11452300-52c5-11ea-9030-d77641c6c690.png)
I'm also uploading other screenshots
![2](https://user-images.githubusercontent.com/28427270/74798721-67ff2c80-52c6-11ea-9ffc-0bf4311155ab.png)
![3](https://user-images.githubusercontent.com/28427270/74798674-4a31c780-52c6-11ea-859c-44ff3442475d.png)
I think the problem may be caused by incorrect rounding up (or lack of rounding up of exchange rate value). The total for the invoice is 1110.80zl (supplier currency) and exchange rate is 4.95zl = £1 so the total in pounds should be £224.40 and not £224.19 (what gives an exchange rate at 4.954725902)
![4](https://user-images.githubusercontent.com/28427270/74798821-c0cec500-52c6-11ea-8bdf-748f62f5bd59.png)
I do use CurrencyLayer API in Multi-currency setup and the exchange rate could been set before as 4.954725902 (I don't remember exactly and I have manually rounded it up recently to 4.95)

**Comment by futurehousestore** [comment]
At the moment I have set MAIN_MULTICURRENCY_ALLOW_SYNCHRONIZATION to 0 and changed the multicurrency_tx (multicurrency rate) in llx_product_fournisseur_price table to have them all set as 4.95. I think that should fix the problem in my system but the bug still exists if MAIN_MULTICURRENCY_ALLOW_SYNCHRONIZATION is set to 1 and the exchange rate has 8 decimals.
