### ISSUE TITLE
Watermark text in pdf documents is not over pictures, and should be in the foreground

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#13120]
# Bug description
The watermark text in pdf documents is not over pictures, if a picture is in placed in the public notes of a document. The watermark text should be over any another content present in the pdf document, in the foreground.

## Steps to reproduce the behavior
1. Write a text in Setup/Other Setup in the parameter PROPALE_DRAFT_WATERMARK
1. Write a draft of a customer proposal and write a public note on it inserting an image in the note
1. Observe that the watermark text is hidden behind the image in the pdf file generated.

## Environment
- **Version**: [*11.0.1*]
- **OS**: [*Linux*]
- **Web server**: [*Apache*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

**Comment by edupulpillo** [comment]
The issue still is present in v13.0.0

**Comment by edupulpillo** [comment]
The issue still is present in v14.0.0

**Comment by edupulpillo** [comment]
Is possible to fix this problem to make tyhe watermark be in foreground off all the another existing images present in the document ?

**Comment by atm-maxime** [comment]
Watermark is now printed on pdf after the pagefoot, so it's the last thing printed on the page, so it's over everything else.

**Comment by edupulpillo** [comment]
BUt it should be the last printed but in the background of all the text,
