### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by mapiolca** [Dolibarr/dolibarr#13132]
# Feature Request
Possibility to create a dark mode linked to each theme synchronized with time zone sunset/sunrise.

**Comment by dolibarr95** [comment]
Hello
We can do it just by creating a module with a specific javascript and css nothing else.
Javascript change the css regarding the current hour.

**Comment by mapiolca** [comment]
Yes sure, but ideally, we can update the eldy or md themes to give this option for all users without specific module.

**Comment by dolibarr95** [comment]
So we have to generate the style.css.php file regarding the hour and change the link from 
```html
<link rel="stylesheet" type="text/css" href="/dolibarr10/theme/eldy/style.css.php?lang=fr_FR&amp;theme=eldy&amp;userid=20&amp;entity=1&amp;layout=classic&version=10.0.1">
```
to
```html
<link rel="stylesheet" type="text/css" href="/dolibarr10/theme/eldy/style.css.php?lang=fr_FR&amp;theme=eldy&amp;userid=20&amp;entity=1&amp;layout=classic&version=10.0.1&t=1582100197">
```
By adding the var t (current timestamp or big random number or else) css always reload at each page (and not loaded from cache).
 _This var is no usefull for the css file it's just a trick for the cache_

**Comment by VoidScute** [comment]
oh yes a dark mod can be cool :D

**Comment by caos30** [comment]
I've a really cool dark theme for Doli 5.x to 10.x (i'm working these days on Doli 11.x):

[https://www.dolistore.com/en/skins/1171-DARK-theme-IMASDEWEB-10.html](https://www.dolistore.com/en/skins/1171-DARK-theme-IMASDEWEB-10.html)

[https://www.dolistore.com/en/skins/1182-DARK-theme-pack-IMASDEWEB-X.html](https://www.dolistore.com/en/skins/1182-DARK-theme-pack-IMASDEWEB-X.html)

I did it not for the day time (night vs. light-day) but for my poor sight (cataract) and the only way i can work is with interfaces of dark background ;-)

![DARKTHEME_tabs_screenshot](https://user-images.githubusercontent.com/1767547/75621677-677f5500-5b54-11ea-8308-ae8fddd0dc04.png)

[May-2021 edited] Note: i've been updating the module to last versions of Dolibarr (currently 13.x).

**Comment by ksar-ksar** [comment]
Hello 

In V13 : NEW: can use parameter ?THEME_DARKMODEENABLED=2 for a preview of theme in dark mode

https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog#L264

**Comment by daraelmin** [comment]
@ksar-ksar is it possible to activate the dark mode theme for only zone user or does it qffect be the default theme ?

**Comment by daraelmin** [comment]
> @ksar-ksar is it possible to activate the dark mode theme for only zone user or does it qffect be the default theme ?

There's a Bug witch permit a work around for that feature :

if a custom color is define for the menu bar... The dark mode is desactivate.

So we can activate it, then choose a custom color for everyone. The dark mode is desactivate by the custom color so the member who wants to activate it just have to set the custom color to default.

Don't fix the bug please ;-)

**Comment by daraelmin** [comment]
Just to centralize, here are the reference of some other bug/enhancement of the darkmode I've found :

#17116 - white background in dark mode
#17114 - unreadable display of module activated in dark mode

**Comment by BB2A-Anthony** [comment]
Good job for dark mode.

it is possible to activate it per user?
