### ISSUE TITLE
Missing check number on bank entry.

### ISSUE THREAD

**Issue by Bagu** [Dolibarr/dolibarr#13148]
# Bug
The bank entry does not include the check numbers.

## Environment
- **Version**: 11.0.1
- **Web server**: Apache 2.4.41
- **PHP**: Php 7.4.3
- **Database**: Mariadb 10.4.12
- **URL(s)**: 
compta/paiement/cheque/card.php?leftmenu=customers_bills_checks&action=new
compta/bank/line.php?rowid=xxxxx

## Expected and actual behavior
Enter a check number and a bank name and submit.
When go on compta/bank/line.php?rowid= the check number is not shown
When go on compta/paiement/cheque/card.php?leftmenu=customers_bills_checks&action=new there is no check number in the list

**Comment by eldy** [comment]
Fixed in branch v11. Will be availble with v11.0.2
