### ISSUE TITLE
Configuring logo to appear on the receipt, error does not result.

### ISSUE THREAD

**Issue by cistelsa** [Dolibarr/dolibarr#13149]
I have always used the logo on the receipt, I was using takepos the old one that came in java, I updated with the dolibarr 11, so what I do is use a user signature with the logo since my tikets printer receives html, I configure The variable __USER_SIGNATURE__ leaves all the text but the image does not, I have tried with an image of the server with a local image and it has not worked, how can I solve this  @andreubisquerra 
![1b0389ee-f894-4754-9022-66eb3cd4976a](https://user-images.githubusercontent.com/17438992/74887501-1481f280-5349-11ea-97a8-4506191bf0f5.jpg)
?

**Comment by andreubisquerra** [comment]
If you are using TakePOS connector you must use the absolute url of the image. Although it is difficult to detect the problem without doing some tests.

**Comment by cistelsa** [comment]
![image](https://user-images.githubusercontent.com/17438992/74980285-2a9dba80-53fe-11ea-8015-2e0f3fd47018.png)
In the image above I have the option of personalized receipts enabled, I have a variable configured. __USER_SIGNATURE__



![image](https://user-images.githubusercontent.com/17438992/74980351-4dc86a00-53fe-11ea-8d69-96bc21e7b98a.png)
Here I configure the user's signature to appear in the variable used



![image](https://user-images.githubusercontent.com/17438992/74980377-591b9580-53fe-11ea-809f-7c282713084c.png)
The HTML configuration is shown here, which in the image has a public link of the logo which is https://www.chicasg.com/images/logo-m.png



![image](https://user-images.githubusercontent.com/17438992/74981286-ffb46600-53ff-11ea-98d5-350ea5ee7a48.png)
I click on ticketpos and the result is as follows



![image](https://user-images.githubusercontent.com/17438992/74980448-7cdedb80-53fe-11ea-938f-2ab2f95d0eff.png)
that's how it looks by clicking on ticketpos



![image](https://user-images.githubusercontent.com/17438992/74981539-705b8280-5400-11ea-93b2-708b6773e013.png)
In the takepos I click on print both physical printer and .xps file and the result is as follows:



![image](https://user-images.githubusercontent.com/17438992/74980588-c0d1e080-53fe-11ea-96d9-faf43b5cced5.png)
as an .xps file



![1b0389ee-f894-4754-9022-66eb3cd4976a](https://user-images.githubusercontent.com/17438992/74980676-e4952680-53fe-11ea-9e4d-0083f4e2e59d.jpg)
as a physical ticket

It concludes the problem is not the printer, can it be the Takepos connector?

**Comment by andreubisquerra** [comment]
I think this issue is not a bug. Contact us for support.
Thank you!
