### ISSUE TITLE
Dictionary payment methods fails to save new entry 

### ISSUE THREAD

**Issue by jongerli** [Dolibarr/dolibarr#13140]
# Bug
[Dictionary payment methods adding new method fails]

## Environment
- **Version**: [11.0.1]
- **OS**: [Windows server 2012]
- **Web server**: [Microsoft-IIS/8.5]
- **PHP**: [7.2.7]
- **Database**: [MariaDB 9.5.0.5196]
- **URL(s)**: [admin/dict.php]

## Expected and actual behavior
[One may enter a new payment method into the list and chooses to save it. The list is expanded with the new entry afterwards.

One enters a new payment method into the list and the save button is pressed. After that an error is thrown: Database fout bij laatste verzoek: INSERT INTO llx_c_paiement (id,code,libelle,type,entity,active) VALUES(52,'IDEAL','Ideal','2','BadFirstParameterForGETPOST',1)
Retourcode voor de meest recente fout bij het toegangsverzoek voor de database: DB_ERROR_1366
Informatie voor de meest recente database-toegangsverzoekfout: Incorrect integer value: 'BadFirstParameterForGETPOST' for column 'entity' at row 1]

## Steps to reproduce the behavior
[Try to enter a new payment method into the list and it should fail.]

**Comment by eldy** [comment]
Seems fixed in 11.0 branch so should be available in 11.0.2
