### ISSUE TITLE
v11.x - Accountancy plan : the new accountancy plan is not loaded after submit

### ISSUE THREAD

**Issue by fx2300** [Dolibarr/dolibarr#13146]
# Instructions
# Bug
The javascript in charge to change the ''valid_change_chart' flag doesn't set it to 1 change it
File : accountancy/admin/account.php (line 105 and 275 to 292)

## Environment
- **Version**: 11.x
- **OS**: Darwin 14.5.0
- **Web server**: Apache/2.4.41 (Unix)
- **PHP**: 7.0.33
- **Database**: MYSQL 5.7.29
- **Browser**: firefox 72.0

**Comment by eldy** [comment]
Did you click on button "Change and Load" with the mouse ?

**Comment by fx2300** [comment]
Of course I clicked on the submit button…

In the debug bar after having submited the form the POST variable 'valid_change_chart' is always posted with 0 as value…
Javascript is allowed for my dolibbarr install. There's no log in the console when submiting the form, according to what the javascript is supposed to log, for instance line 281:

`console.log("chartofaccounts focus = "+$("#chartofaccounts").is(":focus"));`

So the 'valid_change_chart' is never set to 1 and the new accounting plan account list can't be loaded…
To make it works on my local dolibarr install I hacked this piece of javascript in account.php to make it set 'valid_change_chart' to 1 before submiting the form with an onclick event on the button… And then the accounting plan loads as expected…

**Comment by joanlouis** [comment]
yes I confirm the bug on safari and Firefox Mac it work on chrome

**Comment by eldy** [comment]
Tested on firefox linux, seems ok.
Seems specific to Safari+Firefox on MAC only.

**Comment by eldy** [comment]
Don't you have javascript error in console BEFORE you click on the submit button ?

**Comment by hregis** [comment]
@eldy @fx2300 

what is the utility of this javascript ??

`if ($("#change_chart").is(":focus"))`

`#change_chart` is the button !!
If you click on the button you will necessarily validate the change! Why check this?

`#valid_change_chart` is useless either! is always value 1 no ?

```
<script type="text/javascript">
			$(document).ready(function () {
		    	$("#searchFormList").on("submit", function (e) {
					//event.preventDefault();
				    //var form = this;
					console.log("chartofaccounts focus = "+$("#chartofaccounts").is(":focus"));
					console.log("change_chart focus = "+$("#change_chart").is(":focus"));
					if ($("#change_chart").is(":focus"))
					{
						console.log("We set valid_change_chart to 1");
						$("#valid_change_chart").val(1);
					}
					//form.submit();
					return true;
			    });
			});
	    	</script>';
```

**Comment by hregis** [comment]
@eldy look my PR #13188

**Comment by fx2300** [comment]
@hregis @eldy 
Yes thanks for your PR: I couldn't figure out what this flag ('valid_change_chart') was intended to do…
I. e.: why a js event should be required here, after the user has submitted the form, if the js actually doesn't perform any data checking ?

**Comment by hregis** [comment]
@fx2300 @eldy 

I think this code should have been used before,
as it has apparently been changed in the meantime

**Comment by eldy** [comment]
If you remove the flat valid_change_chart, each time, you will type "enter" to make a simple filter on the list, you will trigger the loading/replacing of all accounts in database.
We need this to make to flag a variable each time we click on the button "Change And Load" and only when we click this, not any other field, and when we type "Enter" and the focus was on this button "Change And Load" too.
Say differently, we must load and change chart of account only if you click on field or set explicitely focus on it before typing enter. Any other case, we must not.

**Comment by hregis** [comment]
@fx2300 @eldy 

i send a fix, split form and remove javascript #13188

**Comment by joanlouis** [comment]
the js console return : change_chart focus = false
I don't understand why

**Comment by joanlouis** [comment]
my fix is not clean but it works and don't have side effects

**Comment by hregis** [comment]
@joanlouis  thanks but same problem with Firefox for MAC OS !

**Comment by joanlouis** [comment]
my fix is ok now @hregis test it and it is ok for us on macOS.  @eldy can you confirm it is ok on linux to ?
