### ISSUE TITLE
DatePropal non prise en compte dans les propositions/devis

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#13166]
Dolibarr 11.0.1

DatePropal n'est pas pris en compte dans la traduction par les scripts PHP :

- htdocs/comm/propal/card.php

- htdocs/comm/propal.php

- htdocs/core/modules/propale/doc/pdf_azur.modules.php

À la place c'est la clé Date qui est codée.

Éventuellement idem dans d'autres scripts. Peut-être idem pour les factures et autres documents.

**Comment by atm-maxime** [comment]
Can you give us screenshots ? I don't see any "DatePropal" on propal card or PDF. By the way, htdocs/comm/propal.php doesn't exist in 11.0.

**Comment by manu-p** [comment]
Non, il n'y a pas de DatePropal dans les scripts, et c'est bien ça le problème. 
À la place, il y a Date. 
Or dans les traductions, pour la date de proposition, on trouve DatePropal avec pour libelle "Date de proposition".

Donc, en remplaçant Date par DatePropal dans ces scripts, le libellé proposé ou choisi en remplacement est pris en compte et correctement affiché à l'écran et dans les PDF générés.

htdocs/comm/propal.php n'existe pas dans 11.0 ? Alors c'est un "résidu" d'une version précédente qui n'a pas été supprimé par la mise à jour de Dolibarr. Il y en a peut-être d'autres comme ça.

**Comment by gmilad** [comment]
Bonsoir,

> Donc, en remplaçant Date par DatePropal dans ces scripts, le libellé proposé ou choisi en remplacement est pris en compte et correctement affiché à l'écran et dans les PDF générés.

Il faut donc proposer une pull-request avec les modifications à faire.

> htdocs/comm/propal.php n'existe pas dans 11.0 ? Alors c'est un "résidu" d'une version précédente qui n'a pas été supprimé par la mise à jour de Dolibarr. Il y en a peut-être d'autres comme ça.

Oui un résidu depuis la version 4.
De mémoire il doit exister un script qui permet de savoir les fichiers à supprimer mais je ne le retrouve plus, j'ai juste trouvé une information dans un sujet du forum Fr qui parle d'un affichage lors de la procédure de mise à jour des fichiers à supprimer.

Sinon dans la procédure de mise à jours il est conseillé de supprimer les fichiers du serveur :

[Étape 4 - Supprimez l'ancienne version sur le serveur](https://wiki.dolibarr.org/index.php/Installation_-_Mise_%C3%A0_jour#.C3.89tape_4_-_Supprimez_l.27ancienne_version_sur_le_serveur)

Cordialement,
Gaëtan.

**Comment by manu-p** [comment]
OK closed without resolution...

**Comment by ksar-ksar** [comment]
Hi,

This not a bug, could be a feature request if you like, but you are the only one to request it, so low chance to have it.

**Comment by manu-p** [comment]
Not a bug? Alright, I don't think it's a feature request. Let's take a minute to understand please.

For instance, in core/modules/propale/doc/pdf_azur.modules.php at line 1528 where is this line:
`$pdf->MultiCell(100, 3, $outputlangs->transnoentities("Date")." : ".dol_print_date($object->date, "day", false, $outputlangs, true), '', 'R');`

You can notice that "**Date**" is used, while there's no "Date" entry in langs/fr_FR/propal.lang... (So Date is used in the PDF header, which remains acceptable).

And at line 1533, we find:
`$pdf->MultiCell(100, 3, $outputlangs->transnoentities("DateEndPropal")." : ".dol_print_date($object->fin_validite, "day", false, $outputlangs, true), '', 'R');`

**DateEndPropal** has got an entry in .lang files.

Now, **DatePropal** also gets an entry in .lang files!

So then, just try to replace Date with DatePropal in line 1528 and see what's happening in the newly generated PDF file: the correct translation, i.e. "Date de proposition", is properly printed in the header, instead of "Date".

As I mentioned in the 1st post, this seems to affect other scripts such as:
- htdocs/comm/propal/card.php
- htdocs/comm/propal.php

And maybe others, I've not been further investigating.

@gmilad 
> Il faut donc proposer une pull-request avec les modifications à faire.

Sorry, I'm not a developper. Being able to open a script file and (more or less) understand lines of code doesn't make a developper. Not my job (since 88).

So call it a feature request or a bug, it looks like there are some mismatch in these script codes.
Thanks for reading.

**Comment by atm-maxime** [comment]
Hi. I checked your issue and fixed it. I think it hasn't been seen before, because the title "Date" works correctly everywhere, mening it depends on context. So on the proposal card, list and PDF, the user now it's the proposal date. But it's cleaner to use DatePropal.
