### ISSUE TITLE
Balance is not shown in paypemt reconciliation screen

### ISSUE THREAD

**Issue by ArnaudHocevar** [Dolibarr/dolibarr#13174]
# Bug
Bank reconciliation: The balance is never shown

## Environment
- **Version**: 11.0.1
- **OS**: Linux debian 
- **Web server**: Apache 2.4.35
- **PHP**: PHP 7.3.6
- **Database**: Mysql 5.7.23

## Expected and actual behavior
When attempting to reconcile bank entries, the Balance field is never populated.
Only one account is filtered, and the entries are sorted by value date

## Steps to reproduce the behavior
Go to the bank tab, then click on reconcile. When sorting by value date the current balance does not show up.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/7395597/75090037-2341f280-555f-11ea-8e39-647acf0917ae.png)

**Comment by eldy** [comment]
Put your mouse on the ? above the title "balance". What do you see ?

**Comment by eldy** [comment]
Can you try to reconcile at least 1 line and tell if the column is then filled for other lines ?

**Comment by ArnaudHocevar** [comment]
I've tried playing around with the filters, changing the value date sorting, etc but it still doesn't fill the balance column.
Any logs I can look into ?
![image](https://user-images.githubusercontent.com/7395597/75751371-9e0cc980-5d26-11ea-8136-b4f990aea6af.png)

**Comment by SylvainLegrand** [comment]
I found the same issue.
Dolibarr v11.0.3.

One more thing : the bank reconciliation column doesn't appear (no check box).

Best regards.
Sylvain.

**Comment by ksar-ksar** [comment]
Hi,

Could you check with the latest dolibarr version (V13) ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
