### ISSUE TITLE
No link between supplier order and invoice supplier

### ISSUE THREAD

**Issue by WebAuxilium** [Dolibarr/dolibarr#13187]
# Bug
When you create an order from the supplier order there is no automatic link between order and invoice with dolibarr V11
see post : https://www.dolibarr.fr/forum/t/liee-commande-fournisseur-et-facture-fournisseur/32069
## Environment
- **Version**: [*V11.0.0*]

## Expected and actual behavior
[*Create an invoice from supplier order, validate the invoice => the order number is not shown on the link section*]

**Comment by jrgonzalezrios** [comment]
I am having the same issue. Maybe we could join issues.
Duplicate of #13147 @

**Comment by eldy** [comment]
Duplicate of #13147
