### ISSUE TITLE
 Warning: count(): Parameter must be an array or an object that implements Countable in ...htdocs/dolibarr/htdocs/fichinter/card.php on line 288

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#13196]
# Bug
À la création d'une fiche d'intervention à partir d'un ticket:

Warning: count(): Parameter must be an array or an object that implements Countable in /homepages/18/d319076814/htdocs/dolibarr/htdocs/fichinter/card.php on line 288

Warning: Cannot modify header information - headers already sent by (output started at /homepages/18/d319076814/htdocs/dolibarr/htdocs/fichinter/card.php:288) in /homepages/18/d319076814/htdocs/dolibarr/htdocs/main.inc.php on line 1133

Warning: Cannot modify header information - headers already sent by (output started at /homepages/18/d319076814/htdocs/dolibarr/htdocs/fichinter/card.php:288) in /homepages/18/d319076814/htdocs/dolibarr/htdocs/main.inc.php on line 1137

Warning: Cannot modify header information - headers already sent by (output started at /homepages/18/d319076814/htdocs/dolibarr/htdocs/fichinter/card.php:288) in /homepages/18/d319076814/htdocs/dolibarr/htdocs/main.inc.php on line 1138

## Environment
- **Version**: [*11.0.1*]

Cependant, l'intervention est créée.

**Comment by eldy** [comment]
Fixed for 11.0.2
