### ISSUE TITLE
Bug: method form->formconfirm() returns "Cannot modify header information.. " error when executed from doActions hook

### ISSUE THREAD

**Issue by dvdwalker** [Dolibarr/dolibarr#13207]
# Bug
Method form->formconfirm() returns "Cannot modify header information.. " error when executed from doActions hook.

I'm including a new action button to select a third party on a custom module and want to use the formconfirm() method. On button click:
- the page reloads
- no dialog box is displayed
- html for the dialog box is included on the page
- Console log shows error: Uncaught ReferenceError: $ is not defined, Uncaught ReferenceError: jQuery is not defined
- Apache log shows error:
PHP Warning:  Cannot modify header information - headers already sent by (output started at C:\\xampp56\\htdocs\\dolibarr10\\custom\\googlecontactssync\\class\\actions_googlecontactssync.class.php:110) in C:\\xampp56\\htdocs\\dolibarr10\\main.inc.php on line 1147, referer: http://localhost/dolibarr10/societe/card.php?socid=5

## Environment
- **Version**: 10.0.0 and 11.0.1
- **OS**: Xampp instalation on Windows 10 (64bits)
- **Web server**: [*Webserver type and version*]
- **PHP**: 7.1.32

## Steps to reproduce the behavior
To reproduce: duplicate "Merge" button and action on custom module using addMoreActionsButtons and doActions hooks. Test the new implemented button

**Comment by hregis** [comment]
Hi, It is an external module, it would be necessary to see the source code to be able to answer.

**Comment by dvdwalker** [comment]
Hi, I added an example module that adds a new button on the Societe card -> card tab. On the below link are the functions addMoreActionsButtons and doActions that shows the button and manage the action respectively:

https://github.com/dvdwalker/dolibarr/blob/develop/htdocs/custom/bugexample/class/actions_bugexample.class.php

**Comment by eldy** [comment]
In your code you make "print" (so instruction to format the result) into a hook doAction (so the part to execute "silently" actions). All print must occurs after all actions are done. This is the reason why you get the PHP error. This is the expected bahaviour.
If you want to show a confirm popup, you must add it into a hook dedicated for output of page (so executed after the /* View */ comment of page.

**Comment by hregis** [comment]
@dvdwalker 

you can add all in "addMoreActionsButtons"


```
public function addMoreActionsButtons($parameters, &$object, &$action, $hookmanager)
{
	global $conf, $user, $langs;

	$error = 0; // Error counter

	/* print_r($parameters); print_r($object); echo "action: " . $action; */
	if (in_array($parameters['currentcontext'], array('thirdpartycard')))
		// do something only for the context 'somecontext1' or 'somecontext2'
	{
           if ($action == 'mergenew') {
		$formnew = new Form($db);
		$formquestion = array(
		     array(
			'name' => 'soc_origin',
			'label' => $langs->trans('MergeOriginThirdparty'),
			'type' => 'other',
			'value' => $formnew->select_company('', 'soc_origin', 's.rowid <> '.$object->id, 'SelectThirdParty', 0, 0, array(), 0, 'minwidth200')
			)
		);

		print $formnew->formconfirm($_SERVER["PHP_SELF"]."?socid=".$object->id, $langs->trans("MergeThirdparties"), $langs->trans("ConfirmMergeThirdparties"), "confirm_merge", $formquestion, 'no', 1, 250);
            }
		// Do what you want here...
		// You can for example call global vars like $fieldstosearchall to overwrite them, or update database depending on $action and $_POST values.
	print '<a class="butAction" href="'.$_SERVER["PHP_SELF"].'?socid='.$object->id.'&amp;action=mergenew">'.$langs->trans("Merge New").'</a>'."\n";

	}

.......................

```

**Comment by dvdwalker** [comment]
Got it ;) I added the actio on addMoreActionsButtons as suggested and work like a charm. Many thanks for your guidance @eldy and @hregis .
