### ISSUE TITLE
Bug: pdf viewer inside dolibarr

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#13206]
heoll

i am going to inform you tha the embeded pdf viewer inside dolibarr does not print the information present in footer but we can see the information in the embeded pdf viewer on the screen

thank you 
regards

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 11.0.1
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL(s)**: /dolibarr/compta/facture/card.php?id=213&action=confirm_valid&confirm=yes

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by john-botella** [comment]
Can you give a screen shot ?

**Comment by john-botella** [comment]
Hi can you give me your Web-browser ?
Because there was a firefox issue with PDF integration configuration making PDF view in Web-browser sometime weird.
Can you try with Chromium or Chrome and give me feedback ?

Normally this is corrected in last firefox version.

**Comment by ksar-ksar** [comment]
Could you see if the last Firefox version fix it ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
