### ISSUE TITLE
readme / textfile for internal comments or discussions

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#13214]
Hello,

is it useful to add a text file directly in the directories
for 'internal' comments or discussions?
These files will not be published to Sourceforge packages.

 e.g.  .internal   or  .comment  or  .discussion 

For suggestions and ideas about structure of folders and content of helpfiles and to discuss them.
(not for Dolibarr requests)

Or how do you handle that?

With best regards
Udo Tamm

**Comment by eldy** [comment]
Any internal discussion are done using:
- the forum "developping on dolibarr" 
- or a ticket on github (github if official tool for all development interaction)

Other topic than develop are done on forums

**Comment by dolibit-ut** [comment]
My idea was/is to have a direct view / a direct link the issue.
So if i want change a file/folder name or the folder structure or want to add something there (not code) it could helpful maybe.

**Comment by atm-maxime** [comment]
GitHub issues are the way we discuss / communicate about code and structure and bugs and feature requests, etc.
Only personal issues or help request are not here but on forums as @aspangaro said.
