### ISSUE TITLE
Takepos cannot make discounts and change units in the same line.

### ISSUE THREAD

**Issue by mtbochaca** [Dolibarr/dolibarr#13221]
# Bug
When we apply a discount on a takepos sale line, the price and units cannot be changed.
It also happens the other way around, when you change the price, you can no longer change the discount or the units.

## Environment
- **Version**: 11.0.1
- **OS**: GNU/Debian Linux 10.3
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.14 - FPM/FastCGI
- **Database**: MariaDB 5.5.5-10.3.22
- **URL(s)**: 

## Expected and actual behavior
The 3 values in the same sales line should be able to be modified.

## Steps to reproduce the behavior
When you change a value, the other buttons stop working.

**Comment by javierybar** [comment]
I can't reproduce this issue. Working fine for me. Can you explain detailed steps to reproduce this issue?

**Comment by mtbochaca** [comment]
I have found that the problem is in the focus. Once you have done one of the operations, you must click on the article row again. Then it works properly. If the article is not clicked it does not work.

**Comment by denis-poncereau** [comment]
Yes, the working of those functions is a bit tricky, I think it could be solved by a better visual management : The active button should be displayed in a different color, like the selected line.
The value being modified (price, quantity or discount) should also be displayed differently to show it is being modified.
