### ISSUE TITLE
403 Forbidden dolibarr 11.0.1 fusion PDF two factures

### ISSUE THREAD

**Issue by devzhr** [Dolibarr/dolibarr#13239]
# Bug
*403 Forbidden dolibarr 11.0.1*

## Environment
- **Version**: [*11.0.1*]
- **OS**: [*Linux*]
- **Web server**: [*LiteSpeed*]
- **PHP**: [*7.4.3*]
- **Database**: [*MySQL or MariaDB 10.2.31-MariaDB*]
- **URL(s)**: [*http://localhost:90/compta/facture/list.php#show_files*]

**Comment by hregis** [comment]
@ZM2Dev 
it would take a little more information to understand and solve your problem!

**Comment by devzhr** [comment]
tell me what information do you want

**Comment by hregis** [comment]
@ZM2Dev 
check write rights of your "documents" directory

**Comment by devzhr** [comment]
0755

**Comment by goncoolio** [comment]
Where is Documents directory
