### ISSUE TITLE
Module Product - Tab Extra Fields (Supplier Price)

### ISSUE THREAD

**Issue by Sylvain089** [Dolibarr/dolibarr#13235]
#12213 Bug
Backup value in the database - Products Module - Tab "Extra fields (Supplier price).

## Environment
- **Version**: [*Dolibarr: 11.0.1*]
- **OS**: [*Linux - Installation on Synology NAS directly*]
- **Web server**: [*nginx / 1.15.7*]
- **PHP**: [*PHP 5.6.40*]
- **Database**: [*MariaDB 10: MariaDB 5.5.5-10.3.21-MariaDB *]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Dear All
We can add new extra field in the tab "Extra field (Supplier  Price), and this extrafield is backup the extra field in the database. 
This extra field appears in the tab "Purchase Price" on the "Product" file, we can fill it, but the value of this field is not backup in the database, it's always stay blank, even if we check "required" in the definition of the extra field.
I tried with different type of "extra field" (Numeric, Decimal ...) and the same result, the extra field is created, but the value is not backup.

I'm able to translate the label of this extra field in the module "Translation". That means the extra field works.

I put my question on the French Forum, and Gaetan advice me to open an issue.
For information, if we create an extra field in tab "Extra Fields" of the module "Products", the backing of value works.

We can't reproduce the bug on the "demo on-line", because this tab "Extra Fields (Supplier Price)" appears in Dolibarr 11.0.1

Thanks for your help,
Sylvain

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Dolibarr - 11 0 1 - Products module - Extra fields (Spullier proce) - 2020-02-29 13-54-12](https://user-images.githubusercontent.com/55165532/75608032-4559e880-5afc-11ea-9d9a-b91a6ada5906.png)
![Dolibarr 11 0 1  - Products module - Extra field Supplier Price - Detail - 2020-02-29 13-58-37](https://user-images.githubusercontent.com/55165532/75608025-32471880-5afc-11ea-8d7e-091e905a30de.png)
![Dolibarr 11 0 1 - Translation module - 2020-02-29 13-55-22](https://user-images.githubusercontent.com/55165532/75608007-15124a00-5afc-11ea-9e20-fb3e504d93b3.png)
![Dolibarr 11 0 1 - Product file - 2020-02-29 13-56-26](https://user-images.githubusercontent.com/55165532/75608014-28bdb080-5afc-11ea-9bc9-16ecc09690f9.png)
![Dolibarr 11 0 1 - Product File Details - 2020-02-29 13-57-12](https://user-images.githubusercontent.com/55165532/75608018-2d826480-5afc-11ea-9ec5-6457237f55fa.png)

**Comment by Sylvain089** [comment]
Dear All,

Link on French forum : [https://www.dolibarr.fr/forum/t/module-produits-attribut-supplementaires-prix-fournisseur/32154](url)

Thanks,
Sylvain

**Comment by Sylvain089** [comment]
Dear All,

It doesn't work in version 11.0.3.

In the table "llx_product_fournisseur_price_extrafields", the extrafields is created, but the value attached to the product is not saved. :( 

Thanks for your help,
Regards,
Sylvain

**Comment by ksar-ksar** [comment]
Hello,

Still the case with V13 ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant

**Comment by FiXor** [comment]
Hello everyone

Have you found a solution for this bug. I am in 13.0.2 and the bug is still present.

Thanks for your help
Pierre
