### ISSUE TITLE
Bug: Supplier code not showing.

### ISSUE THREAD

**Issue by GuyVermont** [Dolibarr/dolibarr#13247]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Impossible to create a supplier.
The supplier code box is not showing, thus impossible to save a new supplier*]

## Environment
- **Version**: 11.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: apache2handler 7.2.27-6+ubuntu16.04.1+deb.sury.org+1
- **Database**: MySQL or MariaDB 5.5.5-10.0.38-MariaDB-0ubuntu0.16.04.1
- **URL(s)**: /societe/card.php

## Expected and actual behavior
[*Automatic supplier code being proposed*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*
![image](https://user-images.githubusercontent.com/31744699/75666583-53337900-5c76-11ea-9492-a66b32975b5a.png)
*]

**Comment by hregis** [comment]
@GuyVermont 

is the "Vendors" module activated and does your user have read rights on suppliers?
Also tell me if the "Vendor Commercial Proposals" module is also activated and the user has read rights?

**Comment by GuyVermont** [comment]
Vendors and purchase management module is not activated. 
Vendor Commercial proposals is activated.
Yes, user is admin with full rights

**Comment by hregis** [comment]
@GuyVermont 
try to active "Vendors" module, it should even be mandatory to make supplier commercial proposals!
