### ISSUE TITLE
Takepos Recipt only print Default Customer name used in take pos terminal setup 

### ISSUE THREAD

**Issue by kaushalbjoshi** [Dolibarr/dolibarr#13244]
# Bug

take pos receipt do not print the chosen customer name instead only print the default name that you use at module configuration specifically at the terminal configuration  

## Environment
- **Version**: [*11.0.1)*]
- **OS**: [*windows *]
- **Web server**: [*wamp 3.2.0*]
- **PHP**: [*7.3.12*]
- **Database**: [*MySQL Version: 5.7.28 *]

## Expected and actual behavior
use the customer in take pos from the list --- take payment and print receipt/ ticket get customer name on ticket and actual behavior is irrespective of any customer choose it only print the default customer that you use at the terminal setting  

## Steps to reproduce the behavior
choose any other customer from the take pos terminal and try printing the recipt it do not change the customer --- even if you choose no customer in terminal setting it will print blank

**Comment by andreubisquerra** [comment]
To show customer on the receipt you must enable "Custom Receipt" from TakePOS setup. Than enable "Show customer" in receipt tab.

**Comment by kaushalbjoshi** [comment]
thanks for info ,,, same was done but issue is that if you choose any customer from the customer tab it shows on the takepos ,,,,,both customer name and warehouse but when you print the ticket ( receipt) it only print the name of customer that we have choose as default customer at the terminal setup of take pos -- if you dont choose any default customer in take pos terminal setup that no matter what customer you choose from the customer tab it do not print the customer name -- just blank

**Comment by javierybar** [comment]
Tested on Dolibarr 11 and working fine for me. Customer is printed on receipt.

**Comment by kaushalbjoshi** [comment]
> Tested on Dolibarr 11 and working fine for me. Customer is printed on receipt.

thanks dear -- which version exactly 11.0.0 ? can you please send me the environment details like php and mysql etc 

i even use take pos connector ---- and still only the default customer which we selected at the time of take pos setup is printing -- setup done is setupmodule ---> takepos----> on recipt 
![image](https://user-images.githubusercontent.com/47893938/76165245-6dac9d00-6123-11ea-8455-508441415c47.png)

![image](https://user-images.githubusercontent.com/47893938/76165216-39d17780-6123-11ea-8548-29d3d2bcbdd3.png)

![image](https://user-images.githubusercontent.com/47893938/76165261-8cab2f00-6123-11ea-8f60-ad8ac6cc33af.png)

**Comment by kaushalbjoshi** [comment]
Anyone here to help this - i have a latest version installed in my hosting and still the issue same way in takepos receipt the only default customer name come no matter what you choose  - even if you choose customer from customer list   -- in billing it show the chosen customer correctly  --- if you check the invoice in billing and payment

**Comment by ksar-ksar** [comment]
Hello,

Have you tried the latest V13 ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
