### ISSUE TITLE
New payment terms not showing up

### ISSUE THREAD

**Issue by danigamba** [Dolibarr/dolibarr#13257]
# Bug
Added payment terms in Dictionaries > llx_c_payment_term, correctly stored in mariadb but not showing up in the terms list.

## Environment
- **Version**: 11.0.1
- **OS**: Ubuntu 18.04 LTS
- **Database**:  MariaDB 10.1.44
- **Language**: Italian

## Solution
Setting "entity" to 1 in the database corrects the behaviour and items are correctly showed

**Comment by eldy** [comment]
How did you add the record into table llx_c_payment_term ?
By direct sql insert or from the web interface ?

**Comment by ksar-ksar** [comment]
Hello,

Could you answer to eldy and try with a newer version of Dolibarr ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
