### ISSUE TITLE
Cannot upload a bank statement / Impossible de téléverser un relevé bancaire

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#13255]
Dolibarr 11.0.1

Uploading a PDF bank statement does not work.
Moreover, by linking URL of the PDF bank statement, this statement is linked to all statements in Dolibarr.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Le téléversement d'un relevé bancaire PDF ne fonctionne pas.
De plus, en liant l'URL du relevé bancaire PDF, ce relevé se trouve lié à tous les relevés dans Dolibarr.

**Comment by manu-p** [comment]
Just reproduced on 3 different installations.

In french :

1.     Banques | Caisses
2.     Cliquer sur le nom du compte
3.     onglet Relevés
4.     cliquer sur le numéro du relevé bancaire
5.     onglet Fichiers joints
6.     Ajouter un nouveau fichier/document
7.     Parcourir… choisir le fichier PDF du relevé et Envoyer fichier

**Comment by atm-maxime** [comment]
Already fixed in #13175 will be in next minor release

**Comment by manu-p** [comment]
Le fix concerne le 1er point, le 2nd n'est pas corrigé. Quand on lie une URL a un relevé, cette URL est liée à tous les relevés.

The fix addresses the 1st point, the 2nd is not corrected. When an URL is linked to a bank statement, it is then linked to all bank statements.

**Comment by ksar-ksar** [comment]
Hi,

Do you check with the V13 ?

**Comment by manu-p** [comment]
Thanks @ksar-ksar 

Still the same thing in 13.0.1 with linked URLs: an URL linked to a a bank statement is then linked to all others, in addition to any other previously existing linked URL(s).

[Fr] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Pareil en 13.0.1 avec les "Fichiers et documents liés" : en liant une URL à un relevé bancaire, celle-ci se retrouve liée à tous les autres relevés, en ajout d'éventuelle(s) URL liée(s) existante(s).

**Comment by manu-p** [comment]
The 2nd point initially mentioned as "by linking URL of the PDF bank statement, this statement is linked to all statements in Dolibarr" is still **not** corrected since last year...

**Comment by atm-maxime** [comment]
I pushed some code taht remove the ability to add a link to a bank statement. For now a bank statement is not a real object in Dolibarr, only a reference associated to bank records, so it can't have links related.

**Comment by atm-maxime** [comment]
This issue is not fixable for now. A bank statement is not a real object in database, simply a statement associated to bank records, so it can't have its own links and it's the links of the bank account that are showed

**Comment by manu-p** [comment]
Poor man's fix: remove the feature! :-(
