### ISSUE TITLE
New Payment Term - Table llx_c_payment_term - Error Insert query - From file "dict.php"

### ISSUE THREAD

**Issue by Sylvain089** [Dolibarr/dolibarr#13265]
# Bug
Error when I create a new payment term in tab "Dictionaries" - 2 two bugs :
- 1st bug : with the standard file from dolibarr 11.0.1 : dict.php
- 2nd bug : with the standard file from the new file of this GitHub

## Environment
- **Version**: [*11.0.1*]
- **OS**: [*Linux NAS_DG 3.10.105 #24922 SMP Wed Jul 3 16:37:05 CST 2019 x86_64*]
- **Web server**: [*nginx/1.15.7*]
- **PHP**: [*5.6.40*]
- **Database**: [*MariadDB 10 - MySQL or MariaDB 5.5.5-10.3.21-MariaDB*]
- **URL(s)**: [*dolibarr/htdocs/admin/dict.php?id=12*]

## Expected and actual behavior

- 1st bug :When I try to insert a new payment term with the standard "dict.php" (from dolibarr 11.0.1): I received an error message : DB_ERROR_1366 - Bug the column "entity'.
Please see the screenshot : Dolibarr 11.0.1 - Error Insert llx_c_payment_term - 2020-03-03 15-12-10.png

- 2nd bug : I took the file "dict.php" from the GitHub of this web site. 
Please see the screenshot : Dolibarr 11.0.1 - Error Insert llx_c_payment_term - New dict file -2020-03-03 15-20-32.png
- I received a new error message - and I had a bug in the sql insert query :
INSERT INTO llx_c_payment_term (code,libelle,libelle_facture,nbjour,type_cdr,decalage,sortorder,entity,active) VALUES('30DENDMONTH15','30 jours fin de mois le 15','Règlement à 30 jours fin de mois le 15','30','1','15','15,'1',1)
=> I removed the quote on '15 -> 15 for the "sortorder" column, and the both quote on '1' -> 1 for the "entity" column", and the query works in phpMyAdmin (MariaDB 10) : 
INSERT INTO llx_c_payment_term (code,libelle,libelle_facture,nbjour,type_cdr,decalage,sortorder,entity,active) VALUES('30DENDMONTH15','30 jours fin de mois le 15','Règlement à 30 jours fin de mois le 15','30','1','15',15,1,1)

The value can be insert into the table.

I hope to be clear, the issue is in the "dict.php" file, for the table "llx_c_payment_term".

Thanks for your help,
Regards
Sylvain

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Dolibarr 11 0 1 - Error Insert llx_c_payment_term - 2020-03-03 15-12-10](https://user-images.githubusercontent.com/55165532/75786881-37a79b80-5d66-11ea-84e2-f1e777c7aff5.png)
![Dolibarr 11 0 1 - Error Insert llx_c_payment_term - New dict file -2020-03-03 15-20-32](https://user-images.githubusercontent.com/55165532/75786905-3ecea980-5d66-11ea-9387-a4f2156acd72.png)
![Dolibarr 11 0 1 - Query Insert corrected - llx_c_payment-term - 2020-03-03 15-43-13](https://user-images.githubusercontent.com/55165532/75786932-48581180-5d66-11ea-9939-511f8e3a8e8f.png)

**Comment by fappels** [comment]
Fix PR made: #13258

**Comment by Sylvain089** [comment]
Hi Francis,

I've done the modification in the file "dict.php", and the issue is solved.
Many thanks,

Regards
Sylvain
