### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by gnovaro** [Dolibarr/dolibarr#13268]
# Instructions
Add dockerfile and docker-compose.yml

# Feature Request
Add docker support

## Use case
I think we can base in Dockerfile from another php project

## Suggested implementation
orangehrm/orangehrm

## Suggested steps
Copy based file, change and test

**Comment by guidouil** [comment]
Isn't it already [supported](https://github.com/Dolibarr/dolibarr/tree/develop/build/docker) ?

**Comment by alexanderadam** [comment]
@guidouil apart from building my own: Is _any_ of [those images at Docker Hub](https://hub.docker.com/search?q=dolibarr&type=image&sort=updated_at&order=desc) the official image? :thinking: 
Or is it hosted somewhere else?

**Comment by cgarnier** [comment]
Is there an official build on docker hub ?
