### ISSUE TITLE
Bug: pdf preview

### ISSUE THREAD

**Issue by diego83200** [Dolibarr/dolibarr#13269]
Hello

just a little email for saying you that the built in preview pdf mode in dollibarr doesn't work anymore until the last udpdate
thank you
regards

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 11.0.1
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL(s)**: /dolibarr/comm/action/card.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Can you provide a screenshot of full page you get ?

**Comment by diego83200** [comment]
Helloclose the ticket this is a browser bugThanksEnvoyé depuis mon téléphone Huawei-------- Message original --------De : Laurent Destailleur <notifications@github.com>Date : jeu. 5 mars 2020 à 00:45À : Dolibarr/dolibarr <dolibarr@noreply.github.com>Cc : diego83200 <jclauret@sfr.fr>, Author <author@noreply.github.com>Objet : Re: [Dolibarr/dolibarr] Bug: pdf preview (#13269)Can you provide a screenshot of full page you get ?
