### ISSUE TITLE
Bug: Remise fixes

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#13267]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 11.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.15
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: /compta/facture/card.php?facid=120&action=valid

## Expected and actual behavior
[*Verbose description*]
Field Prix unitaire HT cannot be negative on this type of invoice. If you need to add a discount line, just create the discount first (from field 'Remise fixe' in thirdparty card) and apply it to the invoice. You can also ask your admin to set option FACTURE_ENABLE_NEGATIVE_LINES to 1 to allow the old behaviour.
## Steps to reproduce the behavior
[*Verbose description*]

Losque vous voulez appliquer une reduction correspondant à une facture d'acompte sur une facture standard, ce message d'erreur apparait au moment de la validaiton de la facture.
On ne peut pas ajouter de montant négatif sur les factures, le même message apparait si on passe en manuel.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

![2020-03-03_17-22-39](https://user-images.githubusercontent.com/58973675/75796482-ffa75500-5d73-11ea-9e38-9e9c54a181c4.jpeg)

**Comment by eldy** [comment]
Can you repost the screenshot showing all the invoice record (we need to see the popup with deposit invoice and to see the type and label of product for the line -5115.76)

**Comment by fpav** [comment]
Franck PAVAN
Eurocom SARL
6, Chemin des Garennes
31260 TOUILLE
T : +33 661 573 000
fpa@red-limo.com
French Partner of iRisk www.irisk.com
