### ISSUE TITLE
Incorrect display of notes when converting a budget to an invoice

### ISSUE THREAD

**Issue by mtbochaca** [Dolibarr/dolibarr#13277]
# Bug
If the WYSIWYG editor module is disabled, when converting a quote to invoice, special characters in notes (internal or external) are converted to html notation.

## Environment
- **Version**: 11.0.1
- **OS**: Debian 10.3 4.19.98-1 (2020-01-26) x86_64
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.14-1~deb10u1 FPM/FastCGI
- **Database**: MariaDB 5.5.5-10.3.22
- **URL(s)**: /compta/facture/card.php?action=create&origin=propal&originid=11&socid=1

## Expected and actual behavior
The notes should be copied exactly the same from the budget to the invoice.

## Steps to reproduce the behavior
1- Desactivate module WYSIWYG editor
2- Creat a budget with a internal or external note with especial characters. Ex: 

>  Instal·lació des del cantó 

3- Convert the budget to an invoice
4- The notes in the invoice are:

> Instal&amp;middot; laci&ampoacute; del cant&ampoacute;

I've solved the problem by modifying this code from /htdocs/compta/facture/card.php from lines 3437:
`

	// Private note
	if (empty($user->socid))
	{
		print '<tr>';
		print '<td class="tdtop">';
		print $form->textwithpicto($langs->trans('NotePrivate'), $htmltext);
		print '</td>';
		print '<td valign="top" colspan="2">';
		//$doleditor = new DolEditor('note_private', $note_private, '', 80, 'dolibarr_notes', 'In', 0, false, true, ROWS_3, '90%');
		//print $doleditor->Create(1);
		print '<textarea name="note_private" wrap="soft" cols="70" rows="'.ROWS_3.'">'.$note_private.'</textarea>';
		print '</td></tr>';
	}`
But I think this is not a good solution because activating the WYSIWYG editor module will fail again.

**Comment by eldy** [comment]
Are you able to edit the note to restore correct characters once invoice has been generated ?
Do you have trouble if wysiwyg module is on or only when off ?

**Comment by mtbochaca** [comment]
> Are you able to edit the note to restore correct characters once invoice has been generated ?

Yes, the note can be corrected without any problems

> Do you have trouble if wysiwyg module is on or only when off ?

Only when off. Notes are working properly when the module is activated.

**Comment by eldy** [comment]
Can you confirm that you use the hidden option FACTURE_REUSE_NOTES_ON_CREATE_FROM ?

**Comment by mtbochaca** [comment]
> Can you confirm that you use the hidden option FACTURE_REUSE_NOTES_ON_CREATE_FROM ?

Yes, option FACTURE_REUSE_NOTES_ON_CREATE_FROM is enabled.
![Captura de 2020-03-12 14-56-59](https://user-images.githubusercontent.com/25686532/76529017-facc5a80-6471-11ea-82a7-ab8b1a8fff50.png)
