### ISSUE TITLE
CSS file too long truncated by server cache

### ISSUE THREAD

**Issue by caos30** [Dolibarr/dolibarr#13270]
## Problem
A week ago i almost became crazy trying to discover why the CSS file of the eldy theme was being truncated at server: the file was being loaded on browser not full, but missing the last 20Kb of the file!! You know, the usual is to be problems of web browser cache and CSS style-sheet files, but in this case the problem was caused by the server.

After 10 days searching a clear explanation of why server was truncating that file (the main CSS file of the Dolibarr theme) and without being able to find an answer, i decided to work in a solution avoiding the problem on the server.

I must add to the context of the problem that this "bug" appeared just after migrate my dolibarr sites to a new VPS. Until that migration, some of those dolibarr instances were working fine during the last 2 years, even updating from the old v. 5.0.4 until the 10.0.6. The migration consisted in a copy+paste of the physical files and a minor change on the file conf.php regarding the absolute paths on serve. Because the database is on an external MYSQL server, just like in the original hosting.

During these 10 days of unsuccessful work i found that the CSS file of the eldy theme is dynamically created with PHP, with a call to something like this:

`/htdocs/theme/eldy/style.css.php?lang=es_ES&theme=eldy&userid=1&entity=1&layout=classic&version=10.0.6`

## Solution (workaround in fact)

I checked that the problem was with the server cache because in the access.log file of Apache i could see that effectively the file was being delivered to browser sometimes. The exception were when i loaded it from browser using CTRL+F5, which as you know send to the server a request forcing to skip caches (web browser and server caches).

So, i decided to make a workaround: modify the `style.css.php` file to generate a physical CSS file and returning to the web browser a tiny CSS content like `@import (url_fo/the_physical/file.css);` and voilà! this works as a charm :-)

In fact i refined the PHP script to regenerate this CSS file each 12 hours. Although is not the ideal timing. I would like to make the PHP script smart enough to know if there were changes on the settings of the theme for the current user visiting Dolibarr since the last time the CSS file was generated. In fact, i use an smart md5 formula to generate different CSS files fro each combination of user/theme/entity/language. 

I recognise that currently my code is the fastest possible. I means, it's very fast to check only if the last modification date of the physical file is older than 12 hours, and if it is then regenerate the file.

## The code of my patch

So, i would like to share with you my 15 lines of PHP code to be inserted on the file:

` /htdocs/theme/eldy/style.css.php `

where you must replace the line #238 :

`require __DIR__ . '/global.inc.php';`

By this piece:

```
/* 
 * Use the REQUEST_URI to generate a unique filename for this: THEME & LANGUAGE & USER_ID & ENTITY & LAYOUT & VERSION combination
 * 
 * md5('/htdocs/theme/dark_imasdeweb_10/style.css.php?lang=es_ES&theme=dark_imasdeweb_10&userid=1&entity=1&layout=classic&version=10.0.6')
 * 
 * generates something like this: 
 * 
 * f8026944d073f412cd71e568a1be8cf0
 * 
 */
  
	$css_filename = md5($_SERVER['REQUEST_URI']).'.css'; 

// time passed since creation/modification of the CSS file
	if (file_exists(DOL_DOCUMENT_ROOT.'/public/theme/common/'.$css_filename)){
		$ts_last_modification = filemtime(DOL_DOCUMENT_ROOT.'/public/theme/common/'.$css_filename);
	}else{
		$ts_last_modification = 0;
	}

// recreate the CSS file if the file doesn't exists or it was created more than 12 hours ago
	if (time() - $ts_last_modification > 12*3600){
		
		ob_start( ); // begin an OUTPUT thread
		require __DIR__ . '/global.inc.php';
		$output = ob_get_clean( ); // get the content outputed by global.inc.php
		ob_start( ); // continue with the previous OUTPUT thread
		
		file_put_contents( DOL_DOCUMENT_ROOT.'/public/theme/common/'.$css_filename , $output);
		@chmod( DOL_DOCUMENT_ROOT.'/public/theme/common/'.$css_filename , 0777);
		
	}

// we only render the import of that CSS file
	print "\n\n".'@import "'.DOL_URL_ROOT.'/public/theme/common/'.$css_filename.'";'."\n\n";

```

Maybe you will ask that i make a fork and afterwards a PR... but sincerely, i don't know if the core-developers of Dolibarr will want this change. I recognise that it is not a close perfect solution, but it fixes some buggies behaviours of the current CSS generation system:

- Definitively it SOLVE the problem with PHP server caches. The current eldy theme is UNUSABLE in environments of my VPS (which it's a very standard configuration... so i suspect that maybe a recent update on PHP or Apache will cause the same problem on people installing Dolibarr on new servers!
- With my patch we now have a CSS physical file which is very faster loaded and very easier cached by servers.

But i know that i don't know enough about "Dolibarr framework" to understand if the PHP generation of CSS need to be always with each call or not. So, for this reason i shared all this with you in a "bug issue" ticket.

The last reason: i was not able to find someone with the same problem here in Github or in Dolibarr official forum :-| so... maybe as i told above, a recent update on apache/php is causing this problem recently. I don't know. By the way, i wanted to explain here all my problem and workaround.

@eldy i hope this contribution will be hepful.

**Comment by eldy** [comment]
Having a server that truncates CSS is very strange.
Do you have errors reported in your apache error log ?

**Comment by caos30** [comment]
No @eldy i have none error reported. In fact, is not exact as you said it: is not a CSS file being truncated, but a **PHP output file containing CSS code**. As you know: `style.css.php` is the file called by web browser.

I  want to remark this difference because it seems that the interference is caused by a PHP cache, for example OPcache. Although during my research about this problem i disabled this OPcache (is the native PHP cache for version +7.x) but the problem continue happening.

Sincerely... i abandoned my attempts to understand which piece of software was truncating that "php content" cached. Believe me: i made a live chat with provider, wrote a support ticket and WASTE a lot of hours/days trying to discover this. And i'm on this business before 2k year, so i'm not a newbie ;-)

So, the only true facts i can assure are:
- the output of that style.css.php was being truncated by too long
- once i implemented this patch which dump the content on a real CSS file, the truncation disappears (obviously)

In fact, i tried before an intermediate solution: i modified the style.css.php to return the half content of the global.inc.php (160kb become converted into 2 parts of about 80kb) and inserted at top of that 80Kb of first CSS returned to browser the line @import(style.css.php?....part=2) to then insert there a second call to server to generate the rest 80Kb of the CSS.

Hey, and this worked too! i means, this demonstrated that the problem is of "length" of the output PHP. Sincerely, i don't feel very well knowing that maybe a cache of my server can truncate some PHP outputs... so i will continue investigating this question.

But certainly, it must be fixed on Dolibarr themes, don't you think so? 

In fact, my solution to dump the CSS content to a physical CSS file is more fast and optimal regarding to CPU process. We know that the CSS file of the Dolibarr theme almost NEVER change.

This take to me to another point: i think that maybe a good final solution would be to modify the controller of the "environment settings" on Dolibarr to make this dump always that a change is made by the user. What do you think? 

I suppose that you had a good reason to not do it so in the beginning. Please, tell me, i would like to know. And i think that more people are interested in improve as possible this question of the CSS management and theming in Dolibarr.

Note: i made this [DARK THEME](https://www.dolistore.com/en/skins/1182-DARK-theme-pack-IMASDEWEB-X.html) (on Dolistore) a few months ago. I don't have any problem if you wants to add it to the official Dolibarr distribution, beside Eldy and MD ;-) Sincerely... only 4 people has bought it, but probably more people would use it. In my case due my poor sight (brightness on screen don't let me see anything). I'm working these days on make the the theme compatible with Dolibarr 11.0. Some things on Dashboard has changed, for example. I'm on it.

**Comment by caos30** [comment]
I was re-thinking about your question regarding the apache error log. I think that maybe you don't understood this: when i called on browser the link

`/htdocs/theme/eldy/style.css.php?lang=es_ES&theme=eldy&userid=1&entity=1&layout=classic&version=10.0.6`

It loaded fine (entire). But: 

- If i key pressed F5 then the file loaded truncated. 
- If i key pressed CTRL+F5 then it was loaded again entire
- if i key pressed again F5 then again it loaded truncated

Meanwhile, monitoring the apache access log file, it showed that effectively each time the file was being returned but sometimes partially and sometimes entire (corresponding to the rendered on web browser). Meanwhile, not error on apache error log.

Another detail: if you did the same operations on another web browser (chrome, firefox, etc...) the point of truncating changed slightly. I suppose that it depended on the length of the headers of the output being cached. I don't know.

But -for finish- i would put in clear that there is no problem with the PHP file (regarding errors). Let me insist, it seems a problem with the length and the cache system. I agree that this shouldn't happen. But it happened to me... so probably it will happen other people.

**Comment by caos30** [comment]
After do the next test i am very much calmer now: i have listed on my Dolibarr instance the last 250 invoices and i saved the outputed HTML content on a text file, and its size is more than 600kb. The good new is that the truncation never happen in this case. I means, the list always is being loaded entire, although i've tried to re-load the content through several ways (F5, CTRL+F5, re-visiting the link, the section, bla bla...). 

So it leave me more calm. 
Anyway, i would insist in modify the CSS generation system in a way like the proposed above in my first comment. But, you're the boss my friend ;-)

Cheers!

**Comment by eldy** [comment]
This is still strange. There is no reason that reducing size of CSS solve any trouble. Recommendation by most Web leader are event to merge CSS in one instead of several one. Also the CSS for theme has an average common size. The change should fix by a "side effect" but the root cause of trouble is still unknown for me.
Note: We do not include more themes by default, because we experienced this in the past, and if a theme is included by default, it must be maintained a each version and before the release is done and experience has proved this never happen, so we prefer to keep number of theme available by default as low as possible.

**Comment by caos30** [comment]
Yes @eldy strange but it happened, hehehe. Anyway, my proposal has been explained here, and then you can retrieve it later in the future if you need it :-)

Regarding include other themes in the official distribution... i perfectly understand what you say. But, would it be possible to -at least- integrate an option on the current Eldy theme to enable "dark mode". I means that i've invested a lot of hours (weeks?) to CONVERT your Eldy theme to dark mode. In other words: my theme is NOT A NEW THEME, is a complement of your. In fact, i only worked intensively on your CSS.

So let me insist: could i add to Eldy theme this new feature of "enable dark mode" option, and taking profit of my work accomplished until now. Sincerely, the work to maintain this later is minimal.

In fact, it make use of the settings of the eldy theme. About colours i preferred to work only with these:

- the top navigation bar background-color as MAIN COLOR for bold fonts and buttons and links and some titles
- some special buttons use the "inverted colour" of the MAIN COLOR
- the other colours are: different blacks/greys/whites
- for some complex objects (popup calendar, WYSIWYG editor, graphic statistics, etc..) it run enough well the CSS filter invert() !! Please check the screenshots on Dolistore, although i've improved some elements during the last months. And in fact, sincerely, there are still some things that i probably have not found.
[https://www.dolistore.com/en/skins/1182-DARK-theme-pack-IMASDEWEB-X.html](https://www.dolistore.com/en/skins/1182-DARK-theme-pack-IMASDEWEB-X.html)

![Screenshot_2020-03-12 Dolibarr](https://user-images.githubusercontent.com/1767547/76553665-b204a980-6451-11ea-88c3-47af8bffd68a.png)

Anyway, please don't hesitate. I know that it's not very very very necessary to have a dark mode in Dolibarr, but it's a modern feature, and for some people even needed, like me, due to poor sight, so an **accessibility feature**!

I'm more calm knowing that you listened my offer. But obviously you have the last decision and i respect it with the most respect i can. Thanks for be there!

**Comment by caos30** [comment]
Reading again my last comment, i realize that probably the best thing is that i put my dark theme on Github. i've seen that other opensource projects work in this way: the different modules and apps which are free has its own repository on Github, apart of the CORE of the project. 

In this way also, you can focus the effort of the collaborators interested on one module/theme on another and the core of the project don't convert in a huge monster, and you minimize the risk to integrate a PULL REQUEST damaging something of the core. Well, although it could be possible too, but in an indirect way... like it can happen with whatever module you add to Dolibarr.

**Comment by dpriskorn** [comment]
Hi. Thanks for writing about this obscure error. I never took the time to learn Apache which is IMO a legacy web server. I use nginx exclusively and its really nice and I have never had a situation like the one you describe. Is there a reason why you are using Apache?
Regarding dark theme I use a plugin for the my palemoon browser and that works well also for Dolibarr so IMO a new theme is not needed.

**Comment by dpriskorn** [comment]
@eldy I suggest we recommend avoiding Apache in the readme based on this. WDYT?

**Comment by caos30** [comment]
> Regarding dark theme I use a plugin for the my palemoon browser and that works well also for Dolibarr so IMO a new theme is not needed.

Due to my visual deficiency i also use extensions like Dark Reader or Invert Colours in my browsers. So i know very well what are talking you about.

But said this, let me to argue the convenience of have a dark theme:

1) The quality of the visual result is very much better. Compare a native dark theme with an automatic algorithm is the same like to compare your written opinion of a book you read or the abstract done by a GTP-3 like algorithm. I'm sorry, but the difference in quality is significant. Take in account that you're talking with a person who does really has problems to read websites with bright backgrounds! so, i think that i have a experienced opinion, as user.

2) Is faster (sometimes dramatically faster) to have a native dark them than to have a browser extension which once loaded the webpage then parse the HTML DOM and CSS and apply rules of transformation FOR EACH click you do or whatever popup that emerge. Believe me, the experience is quite disappointing using Dark Reader with web-interfaces using large and rich tables, wysiwig editors, etc... So, for CMS admin panels (like Dolibarr) is quite better a native dark theme.

3). At least my dark themes are quite simple: to enable it only must add the class "dark" to the html node of the webpage, and have on the CSS standard file at the end of the no-dark theme a set of rules changing "a few" colors for borders, backgrounds and fonts... sometimes even CANVAS elements).

4) Last but not less important, major of users has not a "dark web browser extension" installed. So, for example, i install my dark theme for all my customers. Making Dolibarr more elegant (in my opinion, but Facebook, Android and others are making dark themes more popular), more comfortable for the eyes, and more eco-friendly (you know). Being sincere, a few number of customers ask me to enable to them the standard bright theme. I suppose that it's more an inertial phenomenon o a matter of personal preferences. But what i try to say in this fourth point is that having a dark theme you can provide an excellent experience of a dark theme to any user without need to install nothing in their browsers.

I'm sorry by the extension of my reply, but i hope you maybe now see more clearly why some people like me see the utility of having a **native dark theme**. :-)

To close this comment, i would like to say that in my CMS (my own PHP CMS) i added a few years ago a button in the top-right corner to add/remove the "dark" class to the ```<body>````HTML node, so the user can enable disable the dark mode instantly without refresh page. The magic is done by a few CSS rules in the standard CSS file for the selector ```html.dark```.

Cheers.

**Comment by eldy** [comment]
An experimental option exists in v12 to have the theme eldy to be a dark theme. Contributions are welcome to test it and to include the option into setup of selection of theme.

**Comment by dpriskorn** [comment]
Thanks for takibg the time give us arguments. I think they are valid. Have you uploaded the css somewhere yet?
See also #14414

**Comment by dpriskorn** [comment]
@eldy I think having a slide switch is in the titlebar or menu is a good idea. Forcing the user to go to setup is a bad idea, because you need it often when adjusting lighting etc.
