### ISSUE TITLE
global parameter: MAIN_DIMENSION_DEFAULT_UNIT

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#13281]
# Feature Request

a global variable MAIN_DIMENSION_DEFAULT_UNIT to set

**Comment by atm-maxime** [comment]
A bit more explanation about what you want to achieve with this option ?

**Comment by dolibit-ut** [comment]
Sorry, i forgot this completely - it was all in my head only ...

Explanation:
a global parameter to preset a unit for   Length x Width x Height   
use in product/card.php  ...

**Comment by eldy** [comment]
Why don't you use the available feature "Default values" (home - setup - default values) available in v10 and + and that should works for any field, any form ?

**Comment by dolibit-ut** [comment]
> 
> 
> Why don't you use the available feature "Default values" (home - setup - default values) available in v10 and + and that should works for any field, any form ?

In this special key it is also a good idea.

But two points:
1. With a global definition I can use this preset in any adaption forms and ways - not only in product/card.php
    And I think this way is more elegant. I dont know why. 

2. The default value is not really working with dropdown lists / selet files - like the way I tried that.  
    I think in this case the problem is in front of the screen, I know ;-)

   So for this case as example I tried this line:
  
    Url:       product/card.php 
    Field:    size_units 
    Value:   CM    (or  cm)   

    no effect
