### ISSUE TITLE
BUG: Unable to work with XLSX files - php-xml is not installed, but this is not reported

### ISSUE THREAD

**Issue by ERP-Academia** [Dolibarr/dolibarr#13294]
# Bug
- **php-xml** is not reported missing in **Admin Tools** > **About PHP**
- Also https://github.com/Dolibarr/dolibarr/issues/11443 reports that this check is not performed upon install

## Environment
- **Version**: [*11.0.2*]

## Expected and actual behavior
I try to download from **Tools** > **Import Assistant** > **New Import** > **Third-parties and their properties** > **Excel 2007 | Download template file with field content information**

And I get the following in the apache error log:
```
PHP Fatal error:  Class 'XMLWriter' not found in /var/www/html/test1/dolibarr/htdocs/includes/phpoffice/phpexcel/Classes/PHPExcel/Shared/XMLWriter.php on line 44
```

**Comment by eldy** [comment]
I pushed a warning for 11.0.3
