### ISSUE TITLE
Option Close order to status "All products received" automatically if all products are received. Not working 

### ISSUE THREAD

**Issue by jrgonzalezrios** [Dolibarr/dolibarr#13299]
Bug

In a Purchase Order, from the Commerce module, when using the "Item Receipts" area the "Close order to status "All products received" automatically if all products are received." does not automatically sets the order to "All products received" and leaves the order as "Partially received"
When indeed all products where received.
Environment

    Version: 11.0.1
    OS: Linux
    Web server: Nginx/1.15.8
    PHP: 7.3.9
    Database: MySql 7.7.27

Expected and actual behavior

When all products where received and the option "Close order to status "All products received" automatically if all products are received." is marked as "selected" the order status should change to "All products Received" without the need of changing it manually.

Steps to reproduce the behavior

Create a Vendor's purchase order.
Validate order
Make order
Go to Item Receipts area: mark option "Close order to status "All products received" automatically if all products are received." as selected
Set all products with the spectated quantity
Click "Dispatch"

**Comment by eldy** [comment]
Can you try with 11.0.3 ? If you still have the problem, can you tell if you have enabled the "Reception" module or not ?

**Comment by jrgonzalezrios** [comment]
Hi, I updated to 11.0.3 and the problem remains unresolved.

Here is an example using the latest version.

https://pasteboard.co/J0AYPBd.png

**Comment by jrgonzalezrios** [comment]
Hi, I still have the issue with version 11.0.3. I came to realize this happens when the purchase order has a Free-text service as a line.

**Comment by atm-maxime** [comment]
Yes all lines must have been received, so if your order contains service lines or free lines, it won't close automatically.

**Comment by eldy** [comment]
May be we can enhance this to take into account only products and not services ?

**Comment by atm-maxime** [comment]
Hi @jrgonzalezrios !
Can you check with latest versions ? I just tested on a 11.0.5 and making a reception of a purchase order containing product and services does close the PO to All product received.
