### ISSUE TITLE
Module Timesheet manuals on Wiki gives 404

### ISSUE THREAD

**Issue by jeliasson** [Dolibarr/dolibarr#13307]
# Bug
The manuals on the Timesheet module on the Wiki does not exist (404).

https://wiki.dolibarr.org/upload/b/bd/Module_timesheet.pdf
https://wiki.dolibarr.org/upload/4/45/Module_timesheet_2.0.pdf

## Expected and actual behavior
200 OK, and see docss.

## Steps to reproduce the behavior
1. Go to Wiki for [Timesheet Module](https://wiki.dolibarr.org/index.php/Module_Timesheet)
2. Click Manuals
3. Click one of the manuals

**Comment by eldy** [comment]
I removed the links.
This module seems to be abandoned in favor of the feature available by default in Dolibarr. Page has been updated.

**Comment by julbroa-zz** [comment]
Whats is the default feature available in Dolibarr??

**Comment by eldy** [comment]
Timesheet in Dolibarr is a feature provided in last versions by the "Project" module.
