### ISSUE TITLE
Purchase order entry with predefined product and price won't select price (NaN)

### ISSUE THREAD

**Issue by jongerli** [Dolibarr/dolibarr#13313]
# Bug
[Purchase order entry fails defined price]

## Environment
- **Version**: [11.0.2]
- **OS**: [Windows server 2012]
- **Web server**: [IIS 8.5.9600.16384]
- **PHP**: [PHP 7.2]
- **Database**: [MariaDB  10.3]
- **URL(s)**: [...l/fourn/commande/card.php]

## Expected and actual behavior
[When entering orderlines into a purchase order, one expects to select a pre-defined product with the price. But in the price field the value "NaN" Not a Number is placed by Dolibarr and when the orderline is saved, no price is in the record.
In version 11.0.1 this worked all right.]

## Steps to reproduce the behavior
[Try to enter an orderline into a purchase order and the price is put into the orderline also.]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by erikvanberkum** [comment]
Same issue:
Dolibarr 11.02
Ubuntu 16.04 server
Apache Server
mySQL

**Comment by hregis** [comment]
@jongerli @erikvanberkum 

try my fix #13315

**Comment by erikvanberkum** [comment]
> 
> 
> @jongerli @erikvanberkum
> 
> try my fix #13315

this fix works thanks,

**Comment by jongerli** [comment]
This fix didn't work as expected. The product price, in my case € 79,50 was cut off and only the "79" was placed in the product-price field.
