### ISSUE TITLE
Vendor Price Request does not show Selected currency 

### ISSUE THREAD

**Issue by JESSTOFUNK** [Dolibarr/dolibarr#13312]
# Bug
When creating a Price request with multicurrency active, dolibarr asks for the currency to use on the price request, when you create the document Dolibarr prints the system currency instead the currency selected. The document prints the price in the selected (foreign) currency and text of currency in ude as local, but price and currency doen't match.

## Environment
- **Version**: 11.01
- **OS**: linux
- **Web server**: Apache
- **PHP**: 5.6.30 
- **Database**: MySQL or MariaDB 5.6.41-84.1

## Expected and actual behavior
Expected: When you have multicurrency and you request a price list to a vendor, select a currency from vendor (Example: Euro when you use US Dollars.), when you create the PDF must say "Currency: Euro" instead printing "US Dollar".

Actual: When you have multicurrency and you request a price list to a vendor, select a currency from vendor (Example: Euro when you use US Dollars.), when you create the PDF it says "Currency: Dollar" 
 but prices are in "Euro".

## Create a Vendor Price Request with a different currency than yours

![issue doli](https://user-images.githubusercontent.com/61986181/76243187-8c7f6200-61fd-11ea-8b28-c0cc668732cb.PNG)

**Comment by ksar-ksar** [comment]
Hi,

Can you try with V13 ?

**Comment by JESSTOFUNK** [comment]
Hi, I was not using this feature due to this erros. I have verified in V13 is corrected.

Thank you.

Closing issue.
