### ISSUE TITLE
Add tel and fax in warehouse card

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#13319]
# Add tel and fax in warehouse card
information tel and fax in warehouse card

## Use case
use for the users and in documents

**Comment by dolibit-ut** [comment]
I think that information is not usually needed at the warehouse itself, 
and you can add this with stock extrafields.

**Comment by eldy** [comment]
Fax is probably a field not enough used to be included by default but it can be added by an extrafields. Phone may be useful in addition with existing address.

**Comment by BB2A-Anthony** [comment]
Yes Phone for expedition document and other
