### ISSUE TITLE
Create Order on a Vendor, select predefined product causes NaN in Unit Price column (source code show a TODO not treated causing this bug)

### ISSUE THREAD

**Issue by seledev** [Dolibarr/dolibarr#13342]
# Bug
In the file core/tpl/objectline_create.tpl.php, line 771, 
There is a TODO not treated causing a display of "NaN" in a field Tax Free Unit price

## Environment
- **Version**: 11.0.2
- **OS**: Linux
- **Web server**: apache
- **PHP**: 5.6
- **Database**: mysql
- **URL(s)**: https://<mydolibarr_domain_name>/fourn/commande/card.php?id=<ID>

## Expected and actual behavior
When you go on a vendor of a Third-Party, if you create an order and add a predefined product it will not filled Unit Price, but instead it will filled with "NaN".

## Steps to reproduce the behavior
When looking to a Third-party, then go to Vendor Tab.
Click "create order"
Click "create draft"
In "Add new line" section, choose the radio button "Predefined products/services to purchase", and select a product with a price.
The column "U.P. (net)" will be filled with "NaN".

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![screenshot_dolibarr_bug_up_nan](https://user-images.githubusercontent.com/62111968/76545778-a97c9500-648a-11ea-9697-fa07e7f2ba52.png)

**Comment by eldy** [comment]
A fix is ready for 11.0.3 and should be released soon.

**Comment by seledev** [comment]
Great

Thanks
