### ISSUE TITLE
v12.x - Rename bank recept does nothing

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#13346]
# Bug
Rename bank recept has no effect

## Environment
- **Version**: 11.0.2
- **OS**: Debian 10.3
- **Web server**: Nginx 1.17.9
- **PHP**: PHP 7.3.14
- **Database**: PostgreSQL 11.7
- **URL(s)**: /install/upgrade2.php?versionfrom=11.0.0&versionto=11.0.0

## Expected and actual behavior
Expected -> Rename bank recept should reorder in the new position
Actual -> Rename bank recept has no effect

## Steps to reproduce the behavior
Create a bank recept with one value
Try to rename and clic on rename
No change

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![ScreenRename](https://user-images.githubusercontent.com/11213740/76706393-69feb480-66e7-11ea-9aaa-150d085ead9e.png)

**Comment by ludovicandrieux** [comment]
Still present in 11.0.3

**Comment by ludovicandrieux** [comment]
Still present in 12.0.1

**Comment by ksar-ksar** [comment]
Hi,

Do you try with V13 ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant

**Comment by ludovicandrieux** [comment]
Hi,
It's OK with 13.0.4.
Thanks
