### ISSUE TITLE
Added Conditions de règlement not visible in the listing

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#13343]
# Bug
I try to add new payment conditions but they do not become visible in the listing neither on the admin pages or when I try to use them in a qoutation, but if I save one payment condtion and then try to repeat what I just did because it is not visible in the listing, then I have the message that it does already exisit. "Enregistrement déjà existant"

## Environment
- **Version**: 11.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.25
- **PHP**: fpm-fcgi 7.4.3
- **Database**: MySQL or MariaDB 5.5.5-10.1.44-MariaDB-0+deb9u1
- **URL(s)**: /azerty/htdocs/admin/dict.php?id=12

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by hasse-basse** [comment]
I had the problem in 11.0.1
I have today tested in 11.0.3 and it works as it should.

Thanks

Hans
