### ISSUE TITLE
Bug: Input of the time spent on a task with too small input fields

### ISSUE THREAD

**Issue by oboisse** [Dolibarr/dolibarr#13373]
# Instructions

# Bug
When you want to input a time spent on a task, either via the projetct or the Human ressource menu, the input fields for the number of hours and minutes are too small to see anything.

## Environment
- **Version**: 11.0.2
- **OS**: Linux Ubuntu SMP
- **Web server**: Apache/2.4.7 (Ubuntu)
- **PHP**: cgi-fcgi 5.6.40-5+ubuntu14.04.1+deb.sury.org+1
- **Database**: MySQL or MariaDB 5.5.62-0ubuntu0.14.04.1
- **URL(s)**: /dolibarr/htdocs/index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Can you provide a screenshot ?

**Comment by oboisse** [comment]
Here it is for a screen resolution 1920x1080 ...
![Capture](https://user-images.githubusercontent.com/62300250/77168116-93d52400-6ab7-11ea-8cc0-6348a215bf5c.JPG)

**Comment by oboisse** [comment]
... and for a resolution of 1280X1024
![Capture](https://user-images.githubusercontent.com/62300250/77168277-d991ec80-6ab7-11ea-879d-c709c81ff74d.JPG)

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by eldy** [comment]
Do you use firefox ? If yes, i think (but not sure) that trouble is fixed in latest version.

**Comment by dpriskorn** [comment]
Can anyone reproduce this?

**Comment by oboisse** [comment]
Hi,

I use Firefox and with the new version it works fine.

 

 

Cordialement

 



 

 

De : Laurent Destailleur <notifications@github.com> 
Envoyé : vendredi 7 août 2020 15:05
À : Dolibarr/dolibarr <dolibarr@noreply.github.com>
Cc : oboisse <oboisse@tenor-pmo.fr>; Author <author@noreply.github.com>
Objet : Re: [Dolibarr/dolibarr] Bug: Input of the time spent on a task with too small input fields (#13373)

 

Do you use firefox ? If yes, i think (but not sure) that trouble is fixed in latest version.
