### ISSUE TITLE
Updating the journal code does not update code_journal in the llx_accounting_bookkeeping table 

### ISSUE THREAD

**Issue by pangoSE** [Dolibarr/dolibarr#13389]
Dolibarr 9.0.1
A sql query like the one below should be run IMO
update "llx_accounting_bookkeeping" set "code_journal" = "new_code" where "code_journal" = "old_code"

Why? Because if the code has been changed it is not possible to sort by journal code in dolibarr ledger and get all entries. This makes it harder to generate an annual report e.g.

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: pgsql
- **URL(s)**: http://dolibarr.localhost/accountancy/admin/journals_list.php?id=35

**Comment by eldy** [comment]
Sorry i don't understand the trouble. May be a screenshot can help.

**Comment by ksar-ksar** [comment]
Hello,

Not clear for me, and is it still relevant with V13 ?

**Comment by dpriskorn** [comment]
This can be closed IMO. The reporter can reopen with more information if still an issue.
