### ISSUE TITLE
Bug : Discount on already paid invoice impossible (#13303)

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#13387]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Resolution proposed is not resolving the issue, we still have an error message : 

Total of lines can't be negative for a given VAT rate.

Can't validate the invoice with down payment retrieval.

## Environment
- **Version**: 11.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.15
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: /compta/facture/card.php?facid=123&action=valid&page_y=432

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Can you test with 11.0.3 ?

**Comment by fpav** [comment]
I tested 11.0.3 and correction was not in place, I corrected my card.php file myself and replaced it in order to make it work.

Best regards,


Franck PAVAN
Eurocom SARL

**Comment by fpav** [comment]
Solved by https://github.com/Dolibarr/dolibarr/commit/88d98acbba9ec104192083e6c349b8508ca95320
