### ISSUE TITLE
MultiCurrency Total in PDF Report

### ISSUE THREAD

**Issue by Fantomas34** [Dolibarr/dolibarr#13385]
# Bug
When Multi-currency module is ON, Total excluding tax per line remains in the base currency.
This problem is visible in all PDF models from the proposal to the invoice through the order.
Total Net excluding tax is OK.

In PDF model Source AZUR (v7): 
Total ht is assigned on line 555
`$total_excl_tax = pdf_getlinetotalexcltax($object, $i, $outputlangs, $hidedetails);`

but there is no parameter management : **$conf->multicurrency->enabled**

Propal : AZUR model
Order : EINSTEIN model
Invoice : CRABE model

## Environment
- **Version**: V7....
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.2
- **Database**: Mysql 5.6

## Expected and actual behavior
Total Line in $ currency and not in local currency € on total HT.

## Steps to reproduce the behavior
activate module Multicurrency, then make propal in the new currency.

**Comment by ksar-ksar** [comment]
Hi,

Does this issue appear on newest version of Dolibarr (V13) ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
