### ISSUE TITLE
Comment not saved on "Supplier order" > Makeorder

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#13382]
# Bug
New `Supplier Order` > `action=makeorder` : `Comment` not being saved/recorded anywhere

## Environment
- **Version**: develop, 11.x
- **OS**: ubuntu
- **Web server**: nginx
- **PHP**: 7.2
- **Database**: MariaDB
- **URL(s)**: /fourn/commande/card.php?id=X&action=makeorder#makeorder

## Expected and actual behavior
I set date+time and method + `comment`. `Comment` field is optional but the value is not saved anywhere.
It should be saved in the generated task attached to 

## Steps to reproduce the behavior
Create a new `supplier order`.
Approve.
Make Order.
Fill "makeorder" form with comment.

Comment can not be found anywhere afterwards

**Comment by jrgonzalezrios** [comment]
Same is happening to me. The comment is nowhere to be shown afterwards.

**Comment by cfoellmann** [comment]
Thanks @eldy for the quick fix.

I am not sure if the "comment" for the whole card is the right place to save this.
This comment is quick to change and can not be recognized as following the workflow history.

Maybe it can be added to the event that is generated.
