### ISSUE TITLE
Complementary attributes (invoices) not saved - Sale Order

### ISSUE THREAD

**Issue by jrgonzalezrios** [Dolibarr/dolibarr#13384]
# Bug
In a Sale Order from the Commerce module for a customer: when creating a new Invoice of the order, whenever I set data in any complementary attributes (previously defined by me) it is not saved in data base.

## Environment
- **Version**: 11.0.1
- **OS**: Ubuntu Linux
- **Web server**: Nginx/1.15.8
- **PHP**: 7.3.9
- **Database**: MySql 7.7.27

## Expected and actual behavior
Setting data in the complementary attribute should be saved

## Steps to reproduce the behavior
Create a Complementary attribute from the Setup -> modules -> Invoices -> Complementary Attributes -> NEW ATTRIBUTE

Create a Sale order in the Commerce module
From the Sale Order, create a draft of an Invoice.
Set data in the previously created Complementary Attribute.
The new created Invoice will not have the data saved.

**Comment by eldy** [comment]
Do you still have the trouble with 11.0.3 ?

**Comment by jrgonzalezrios** [comment]
Thanks it is working correctly in the new version 11.0.3. Thanks for your time and support!
