### ISSUE TITLE
Zero Product stock in table product_stock

### ISSUE THREAD

**Issue by mandeepmavi** [Dolibarr/dolibarr#13393]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Zero Product stock in table product_stock after resiving Purchase order, even no stock in Warehouse, can see quantity in Related Items in Total Quantity, I think insert command from htdocs\product\stock\class\mouvementstock.class.php not working

## Environment
- **Version**: [11.0.3]
- **OS**: [Windows 10]
5.7.26 - MySQL

**Comment by atm-maxime** [comment]
Can you show your stock module setup ?
Did you use the product reception tab on your purchase order?

**Comment by mandeepmavi** [comment]
opps Changed MYSQL Database to utf8_unicode_ci, everything working now, install is  also smoth now.

**Comment by atm-maxime** [comment]
Ok I close your issue then. Thanks for contributing!
