### ISSUE TITLE
ErrorPaymentInBothCurrency

### ISSUE THREAD

**Issue by zietbukuel** [Dolibarr/dolibarr#13390]
# Bug
Cannot register payment to provider in a different currency. The amount spent on was on USD, but my main currency is PEN. The invoice is in USD and the payment I'm trying to register is also in USD and I'm getting ErrorPaymentInBothCurrency and I cannot register the payment.

## Environment
- **Version**: 11.0.2
- **OS**: Ubuntu 18.04
- **Web server**: nginx/1.16.1
- **PHP**: 7.3.15-3+ubuntu18.04.1+deb.sury.org+1
- **Database**: MySQL or MariaDB 5.5.5-10.4.12-MariaDB-1:10.4.12+maria~bionic-log
- **URL(s)**: fourn/facture/paiement.php?facid=9&action=create&accountid=1

## Expected and actual behavior
Allow the system to register a payment.

## Steps to reproduce the behavior
Enable multicurrency, create an invoice in the secondary currency and register a payment.

**Comment by futurehousestore** [comment]
Hi,
That's not a bug it is just an incorrect way of entering payments. Please check the video to see how it should be done. You need to use one currency or the other and you cannot input two currencies at once https://1drv.ms/v/s!AkCF1g4VB-lZhwCFyVYDnj71XfYm?e=q7mDGC
