### ISSUE TITLE
DirectPayment in TakPOS KO with table selection

### ISSUE THREAD

**Issue by ssa75012** [Dolibarr/dolibarr#13396]
# Bug
[*Short description*]

## Environment
- **Version**: [11.0.3]
- **OS**: [Linux SSADDUR0 4.4.59+ #24922 SMP PREEMPT Mon Aug 19 12:13:37 CST 2019 x86_64]
- **Web server**: [Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141]
- **PHP**: [*7.3.11*]
- **Database**: [*MariaDB 5.5.62-MariaDB*]
- **URL(s)**: [*http://192.168.1.20/dolibarrdev/takepos/takepos.php?idmenu=107&mainmenu=takepos&leftmenu=*]

Takepos with restaurant option valid
Select a table (in menu Emplacement) for example table1
Select one product.
Click in the button "direct Payment"
Display "missing 3 euros" "not pay" what ever the amont of the bill.

Working fine if table is not selected.

**Comment by andreubisquerra** [comment]
Thank you @ssa75012 
Is solved with https://github.com/Dolibarr/dolibarr/pull/13402

**Comment by ssa75012** [comment]
I just download and install the last version of the dev version.
Nothing change same issue

![Capture](https://user-images.githubusercontent.com/48380395/78072866-1efbc700-73a0-11ea-8c73-c2433fe35f00.PNG)
![Capture2](https://user-images.githubusercontent.com/48380395/78072879-2327e480-73a0-11ea-8e49-ca3571f1e768.PNG)

**Comment by javierybar** [comment]
For me now is working fine!
@ssa75012 remember avoid download the archive file in github, download with cloning the repository

**Comment by ksar-ksar** [comment]
Hello,

Does it work with the newest version of Dolibarr (V13) ?

**Comment by ksar-ksar** [comment]
Hi,

You can re-open the issue if it is still relevant
