### ISSUE TITLE
Bug: Impossible to introduce discount for down payment received

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#13391]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Impossible to apply a fixed discount to an invoice

## Environment
- **Version**: 11.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.15
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: /compta/facture/card.php?facid=123&action=valid&page_y=440

## Expected and actual behavior
After payment of preliminary down payment invoices, the prelimary fixed discount shall be applied but it fails to be validated and an error message appear
## Steps to reproduce the behavior
Save any fixed discount for a customer and apply it to any invoice, when validate the invoice, error message will appear.
![2020-03-21_12-29-59](https://user-images.githubusercontent.com/58973675/77225473-b460b500-6b6f-11ea-9e1b-1b5484cff8d0.jpeg)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Should have been fixed in 10.0.3

**Comment by fpav** [comment]
Not yet, still active in 11.0.3 as you can see here

- **Version**: 11.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.15
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: /expensereport/card.php?id=15

![2020-03-23_18-20-49](https://user-images.githubusercontent.com/58973675/77344375-5da3d880-6d33-11ea-92be-a22ee64b5739.jpeg)
![2020-03-23_18-20-49](https://user-images.githubusercontent.com/58973675/77344377-5ed50580-6d33-11ea-976b-90c5c9b8071a.jpeg)
