### ISSUE TITLE
REST API  url resolutin does not work, WORKAROUND

### ISSUE THREAD

**Issue by zigastegu** [Dolibarr/dolibarr#13418]
# Bug
REST API  url resolutin does not work in my case.
Have a workaround.

How to check if it would work also for others?

## Error when no workaround
{"messages":["attribute paths is not of type `object`"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (array) does not match any allowed primitive type (allowed: [\"object\"])","schema":

## Environment
- **Version**: [checked only on 11.0.3]
- **PHP**: [7.4.3, 7.3, 5.6]
- **URL(s)**: [api/index.php/explorer]

## Attached files
**WORKAROUND**
![image](https://user-images.githubusercontent.com/1379063/77490570-81eadc80-6e3b-11ea-836e-1dcd1dbfd939.png)

**Comment by zigastegu** [comment]
$SERVER_['PHP_SELF'] returns only "/api/index.php", missing /explorer
["SERVER_SOFTWARE"]=> string(6) "Apache"

Hm, should have checked other issues:
https://github.com/Dolibarr/dolibarr/issues/11172
https://github.com/Dolibarr/dolibarr/issues/7623

This also works in my case:
**$url = $_SERVER['SCRIPT_NAME'].$_SERVER[PATH_INFO];**

**Comment by zigastegu** [comment]
$SERVER_['PHP_SELF'] returns only "/api/index.php", missing /explorer

**Comment by zigastegu** [comment]
["SERVER_SOFTWARE"]=> string(6) "Apache"

**Comment by zigastegu** [comment]
Hm, should have checked other, closed issues:
https://github.com/Dolibarr/dolibarr/issues/7623

**Comment by eldy** [comment]
Can you confirm this patch https://github.com/Dolibarr/dolibarr/commit/4e774139964d8d213ed6fab67140ac0083ba37cf works for you ?

**Comment by zigastegu** [comment]
Thank you for fast replay.
Didn't work, because of regex. When I replaced $ with / it worked.
String compare works too.
After this changes it works for me, but hopefully works for others too.

**Patch:**
needs renaming to patch.diff
[patch.diff.txt](https://github.com/Dolibarr/dolibarr/files/4383963/patch.diff.txt)

**Comment by eldy** [comment]
/ was added
