### ISSUE TITLE
Sort imports and exports list by alphabetical order

### ISSUE THREAD

**Issue by atm-gauthier** [Dolibarr/dolibarr#13427]
# Feature Request
Some Dolibarr users think it would be more simple to get standard imports and exports list sorted by alphabetical order for quick access

## Use case
Go to menu Tools->new export or new import

## Suggested implementation
use a simple php function usort() ?

**Comment by atm-maxime** [comment]
Still relevant

**Comment by atm-maxime** [comment]
Still relevant
