### ISSUE TITLE
Increase `batch` length

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#13423]
# Feature Request
Increase `batch` fields in the database.
Currently `varchar(30)` to `varchar(64)` or even `varchar(128)`

## Use case
we need longer batches than the `varchar(30)` currently used.

## Suggested implementation
I am currently testing only changing the table fields. Seems to work so far.

## Suggested steps
add changes to the mysql updates for 12.x

**Comment by cfoellmann** [comment]
batches were increased to 128 in https://github.com/Dolibarr/dolibarr/commit/e937b227217d3546e5acf95727a26091ae4751da
But it seems to be missing the migration/update path

**Comment by fappels** [comment]
Just a remark, keep in mind if once you want to generate GS1-128 barcodes you are limited to 20 chars for lot and serial numbers.

**Comment by cfoellmann** [comment]
we buy raw material products with vendor serial numbers as QR or RFID codes.
Those are longer than 30 all the time
