### ISSUE TITLE
Categories date_modification  always null when API GET /categories

### ISSUE THREAD

**Issue by fabienlege** [Dolibarr/dolibarr#13434]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
date_modification and date_creation are always null for categories in API GET

## Environment
- **Version**: 11.0.3
- **OS**: Linux Sabre-15 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: 7.3.16-1+ubuntu18.04.1+deb.sury.org+1
- **Database**: MySQL or MariaDB 5.7.29-0ubuntu0.18.04.1
- **URL(s)**: localhost
## Expected and actual behavior
- create a thirdparty category
- run `curl -X GET --header 'Accept: application/json' --header 'DOLAPIKEY: bH24qfN5cgqCi4I3Wt05jiZTM3P78NmR' 'https://localhost/htdocs/api/index.php/categories?sortfield=t.rowid&sortorder=ASC'`
 - search for date_creation or date_modification : it's null
 - Try to edit this category via API with PUT category endpoint and set a date_modification.
 - PUT correctly return the good date_modification
 - retry a GET /categories : date_modification is null

**Comment by eldy** [comment]
Data is empty because information is not yet stored in database.
I added the field to store information for v12. Still waiting dev to change code to fill and read fields now...

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/13575
