### ISSUE TITLE
BUG: objectonoff.php and MAIN_DIRECT_STATUS_UPDATE does not work with generic objects.

### ISSUE THREAD

**Issue by catrielr** [Dolibarr/dolibarr#13464]
## Bug description
Just check that,
If elements is generic it comes out by default.

`if ($element == 'societe' && in_array($field, array('status')))
{
	$result = restrictedArea($user, 'societe', $id);
}
elseif ($element == 'product' && in_array($field, array('tosell', 'tobuy', 'tobatch')))
{
	$result = restrictedArea($user, 'produit|service', $id, 'product&product', '', '', 'rowid');
}
else
{
	accessforbidden("Bad value for combination of parameters element/field.", 0, 0, 1);
	exit;
}`

## Environment
- **Version**: [*11.0.3*]

**Comment by atm-maxime** [comment]
I'm not sure I understand. This file is used to set status on thirdpary or product when hidden option MAIN_DIRECT_STATUS_UPDATE is active. And if element is not 'societe' or 'product' it returns an access forbidden. What do you find wrong here ?
If you want it to work with other object, this file must be modified.

**Comment by catrielr** [comment]
Hi atm-maxime, I am developing a module, which list of items, that can be activated or deactivated.
For this I use this function.

`print ajax_object_onoff($loan_static, 'active', 'active', 'On', 'Off');`

and that function executes an ajax:
`                 $.get( "'.DOL_URL_ROOT.'/core/ajax/objectonoff.php", {
                    action: \'set\',
                    field: \''.$field.'\',
                    value: \'1\',
                    element: \''.$object->element.'\',
                    id: \''.$object->id.'\'
                },`

and that's where the problem is, `$element` is not "societe" or "product" and exit with
`accessforbidden("Bad value for combination of parameters element/field.", 0, 0, 1);`

**Comment by atm-maxime** [comment]
Yes ok understood. Then it's not a bug but a feature request because the MAIN_DIRECT_STATUS_UPDATE option only works with societe and product for now. And the objectonoff.php file makes checks before doing the action. I'm not sure how to add a way to work with other modules...

**Comment by eldy** [comment]
I added a change that may allow the use of objectonoff for external modules without breaking security.
Test are welcome.
