### ISSUE TITLE
Bug: Payment allocation issue

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#13472]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
I use a payment woocommerce plugin and Splash to populate my ERP Dolibarr. After a completed payment on the website, an invoice and a Purchase Order are automatically generated in addition to the payment made.
Payment is not allocated to any bank account although 2 bank accounts are available? Is there a parameter to setup differently?

## Environment
- **Version**: 11.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: /compta/facture/card.php?facid=32

## Expected and actual behavior
Payment shall be allocated to default bank account but it is not.

## Steps to reproduce the behavior
Difficult to reproduce unless you buy anything on the website.
![2020-04-01_18-34-26](https://user-images.githubusercontent.com/58973675/78162634-70ab5c80-7447-11ea-9c62-b75f6a2a4266.jpeg)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by fpav** [comment]
I forgot to mention that the non allocation of the payment to the bank prevent the payment to be written inside the bank account although the payment is in the system.

**Comment by eldy** [comment]
Pb here seems to be in splash sync module since the bank account is correctly field when using Dolibarr interface.

**Comment by fpav** [comment]
You are right, I solved it by modification of the parameters in splash module!
