### ISSUE TITLE
REST API return inconsistancies

### ISSUE THREAD

**Issue by ATM-Marc** [Dolibarr/dolibarr#13478]
While working on an upcoming pull request for the REST API that fixes incorrect API return on some endpoints (success test is written as `if ($object->create())` while it should be `if ($object->create() > 0)`), I noticed incosistancies in the way JSON responses are created, depending on the endpoint.

Some success responses are just the id of the object, some are the complete object ; some error responses are just `false`, some other throw detailed `RestException`s that are converted to comprehensive error objects usable by the API client.

This is not easy for outside users as, as far as I know, this is not documented outside of the API classes, and even for "Dolibarr-ers", because PHPDoc tags are not always consistent with the code.

So, what do you think would be the best way to fix this ? I'd like to fix this in 9.0+, but in a way, clients have been developped with the current behaviour in mind, so I guess it should be a PR in develop branch ?

**Comment by atm-maxime** [comment]
Ping @eldy

**Comment by eldy** [comment]
This is some rules that follows 80% of API, so rules that we must follow:
* For API to create, return must be ID of object created. If you found an API that do something else, you can fix it.
* No API should return "false". Such API should return instead a RestException (40x or 50x depending on case). If you find a "return false" in an API response, you can fix this.

Also, phpdoc tags are often forget. They should list the different possible values of RestException.

**Comment by ATM-Marc** [comment]
Just a heads-up, I'm still working on this fix.

I'm just giving this the required time to tidy everything up to good standards, including PHPDoc tags.

I'm encountering other side problems : dol_print_error() calls inside business classes that mess up API responses (I guess I will do a separate PR for this before this one), and some API calls for lists not even checking the access right for the given object...

**Comment by eldy** [comment]
dol_print_error() can be replaced with a $this->error and return -1 if this is done inside a class.
dol_print_error() is welcome only on rendering pages.

**Comment by dpriskorn** [comment]
I see no pull requests references here. How did it go?
@eldy are your statements above documented in the wiki?

**Comment by ksar-ksar** [comment]
Hi,

Any news on this one ?
