### ISSUE TITLE
Code enhancement: shippings without orders

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#13476]
separate shipping from orders : have a real dedicated expeditiondet table with all the information instead of the only fk_commandedet field.
many goals : allow to ship product without order is the main; better management of shippings for pdfs, external modules, etc

**Comment by altairis-tof** [comment]
this is still relevant; i will work on it in next months.

**Comment by altairis-tof** [comment]
i did not have resources to do it but i think it is a big feature missing in Dolibarr.

**Comment by josett225** [comment]
Hi There
This is still a required feature for several businesses. 
Let me know if we could help.
