### ISSUE TITLE
[DOLIBARR] [REST API] /products or /products/{id} doesn't return pictures 

### ISSUE THREAD

**Issue by RDHimni** [Dolibarr/dolibarr#13488]
Right now, when fetching a product i cannot get the images i previously linked to my product through the REST API. Is there a way to get the pictures displayed in Dolibarr for the products ? Am i missing something ?

**Comment by ptibogxiv** [comment]
Use document api, you'll get picture, pdf or anyting else associâtes with an object

**Comment by RDHimni** [comment]
> Use document api, you'll get picture, pdf or anyting else associâtes with an object
@ptibogxiv document api required "hashp" for get the Image .
 DOL_URL_ROOT.'/document.php?hashp=sharekey'

**Comment by ptibogxiv** [comment]
/api/index.php/explorer/#!/documents/documentsRetrieveDocumentsListByElement

will return picture  pdf or else in bas64 format, api can't send files, need convert it in base64 then you can decode it in your application

**Comment by RDHimni** [comment]
> /api/index.php/explorer/#!/documents/documentsRetrieveDocumentsListByElement
> 
> will return picture pdf or else in bas64 format, api can't send files, need convert it in base64 then you can decode it in your application

thank you @ptibogxiv but what i should set in the "modulepart" field .
![Capture](https://user-images.githubusercontent.com/50507265/78363882-d8cf7f00-75bc-11ea-8e17-8199384e9d5a.PNG)

**Comment by ptibogxiv** [comment]
product or produit (dolibarr was french at the beginning) it's module name of the element that you want

**Comment by RDHimni** [comment]
@ptibogxiv 
![Capture](https://user-images.githubusercontent.com/50507265/78366449-ceaf7f80-75c0-11ea-9d98-ffe71cbd2969.PNG)

such i have a product that id = 2 
![image](https://user-images.githubusercontent.com/50507265/78366600-ff8fb480-75c0-11ea-8487-6c9eee1050d7.png)

**Comment by ptibogxiv** [comment]
user with api have the right to see product ? it's focntionnal for me in v11 et v12 and i use it on live production website

test with the internal rest api explorer, it's easy,

**Comment by RDHimni** [comment]
@ptibogxiv 
ahe yes i have v10

**Comment by ptibogxiv** [comment]
so you need upgrade, it's work only with v11+

**Comment by awsv-dev** [comment]
If this solution still works for you, you can see my solution at the end of the comments:
 |
 |
v
https://github.com/Dolibarr/dolibarr/issues/20558
