### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by lesslie-hub** [Dolibarr/dolibarr#13487]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 12.0.0-alpha
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.3
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.4.11-MariaDB
- **URL(s)**: /updatedoli/htdocs/admin/company.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Description of bug is empty
