### ISSUE TITLE
Bug: The total balance doesnt balance with the detail listing for the bank

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13498]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
The total balance show in the bank account list does not equal to the value show in the details listing for the same bank.

## Environment
- **Version**: 11.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /compta/bank/bankentries_list.php?id=1

## Expected and actual behavior
Bank balance in the bank list shall be same as the balance in the list summary

## Steps to reproduce the behavior
unsure

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Capture](https://user-images.githubusercontent.com/52134143/78464272-067e0a80-771a-11ea-98c4-509b04a0c9f3.PNG)
![Capture1](https://user-images.githubusercontent.com/52134143/78464273-07af3780-771a-11ea-9421-5e4cd2329f66.PNG)

**Comment by lesslie-hub** [comment]
![image](https://user-images.githubusercontent.com/58374555/78838350-4719a480-79f6-11ea-9d73-6748a2568037.png)

**Comment by lesslie-hub** [comment]
the asset is not working

**Comment by asolslk** [comment]
> the asset is not working

May I know how you get the asset in the system?
