### ISSUE TITLE
Complimentary line attributes whose type is "date" for an order can not be set

### ISSUE THREAD

**Issue by jakobgurn** [Dolibarr/dolibarr#13502]
# Environment
- **Version**: 11.0.3
- **OS**: Debian 10 aarch64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.4.4 aarch64
- **Database**: MariaDB 10.4.12 
- Running in docker containers on a Raspberry Pi 4 (4GB) running Ubuntu 19.10 ARM64

## Expected and actual behavior
Expected: When setting a value of type date for an order line it should get set
Actual: After hitting Save the page reloads, price and other values correctly saved but additional attribute of type date not (still NULL)

## Steps to reproduce the behavior
1. Create an additional attribute for order lines of type date
2. Try to set the added attribute to a value for a line

**Comment by atm-maxime** [comment]
Can you give a screenshot of the value you're entering ? It works for me on 11.0.3

![image](https://user-images.githubusercontent.com/2097773/79069869-f47c0900-7cd1-11ea-82a2-6dacc646f803.png)

**Comment by atm-maxime** [comment]
Seemed already declared and solved : #13384

**Comment by jakobgurn** [comment]
Hi,

I attached screenshots of the value I try to set (manually or via date picker) and the result (installation is in german). 

I'll try to get a development environment ready in the next days to further isolate the problem.

Thanks for looking into it and all the best,
Jakob

![grafik](https://user-images.githubusercontent.com/15279923/79159078-b963fd80-7dd7-11ea-995e-732d78ef8489.png)

![grafik](https://user-images.githubusercontent.com/15279923/79159110-cb45a080-7dd7-11ea-8429-732aeab5438d.png)

**Comment by jakobgurn** [comment]
Confirmed on a new installation: it does not work for me in 11.0.3, but works with the current development version.

Again thanks for looking into it!
