### ISSUE TITLE
550 Maximum line length exceeded when sending emails

### ISSUE THREAD

**Issue by jongerli** [Dolibarr/dolibarr#13510]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
550 Maximum line length exceeded when sending emails

## Environment
- **Version**: 10, 11.0.3
- **OS**: Windows server 2012R2
- **Web server**: IIS 8.5
- **PHP**: 7.2
- **Database**: MariaDB  10.3
- **URL(s)**: ../compta/facture/ ../propale/facture/ etc.

## Expected and actual behavior
When sending an email from Dolibarr one has the ability to add a signatue and a company logo to it. The email is accepted by the mailserver of the receiver of the email.

## Steps to reproduce the behavior
Some emailservers reject the email from Dolibarr because of the length of the image (bas64) which is in the signature. So a lot of servers work fine but some of them give the error message:
i.e. this server returns an error host mx1.cab-solutions.de [38.128.97.252]
SMTP error from remote mail server after end of data:
550 Maximum line length exceeded (see RFC 5322 2.1.1). 
This behaviour sometimes occurs with specific mailservers.

Is there a way to work around this problem or must one reduce the seize of the image in the signature in Dolibarr to comply with the length of the line (max 500)?]

**Comment by frederic34** [comment]
@jongerli what is your conf for sending email? PHP Mail, SMTP/SMTPS or Swiftmailer?

**Comment by jongerli** [comment]
We use SMTP for e-mailing in Dolibarr. We tried several and all gave the same result.

**Comment by fredso68** [comment]
Is this topic solved? I have the same problems but I can't see further notices on this topic. Noob, sorry

**Comment by ksar-ksar** [comment]
Hello,

Could you check with V13 ?

**Comment by fredso68** [comment]
Thanks. I will.

Fred

Verzonden vanuit Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by jongerli** [comment]
I have been testing the issue with Dolibarr version 13.0.1 on our demo [instance ](https://try.dolibar.nl) and it seems to work correct now. Tested [mailservers:](url)
- Gmail
- KPN (Dutch telecom)
- hMailServer

Due to practical reasons I was not able to test with the server mx1.cab-solutions.de.
But I think the issue can be closed.

@Fred: Can you test please?

**Comment by fredso68** [comment]
Hi Theo,

I will.

Fred

Verzonden vanuit Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by jongerli** [comment]
After some more testing on version 13.0.2 by Fred and me we still encounter the same error:
Remote host said: 550 Maximum line length exceeded (see RFC 5322 2.1.1).
Problem not solved yet.

**Comment by oriolfuentes** [comment]
Hi, I am having te same behaviour on Dolibarr  17.0.

Is there any workarround to solve this problem?

Thanks

Example:

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [xxx@xxx.com](mailto:xxxx@xxxx.com)
    host mx10.profesionalhosting.com [212.63.111.240]
    SMTP error from remote mail server after end of data:
    550 Maximum line length exceeded (see RFC 5322 2.1.1).


Reporting-MTA: dns; inti.informaticabcn.com

Action: failed
Final-Recipient: [rfc822;xxxx@xxxx.com](mailto:rfc822;xxxx@xxxxx.com)
Status: 5.0.0
Remote-MTA: dns; mx10.profesionalhosting.com
Diagnostic-Code: smtp; 550 Maximum line length exceeded (see RFC 5322 2.1.1).

**Comment by rubenkon** [comment]
And also from release Dolibarr 16.0.4. I see the same issue.

Solution is probably to remove the image when this problem occurs....
