### ISSUE TITLE
BUG: Public interface -  filed name is “statut” instead of “status”.

### ISSUE THREAD

**Issue by jukyyy** [Dolibarr/dolibarr#13519]
# Bug
Public interface -  field name is “statut” should be “status”.

## Environment
- **Version**: 110.0.3
- **OS**: Linux Debian 10.3
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.14-1~deb10u1
- **Database**: MariaDB 5.5.5-10.3.22-MariaDB-0+deb10u1
- **URL(s)**: /public/ticket/list.php

## Expected and actual behavior
Field name is “statut” should be “status”.

## Steps to reproduce the behavior
navigate to: /public/ticket/list.php

**Comment by philazerty** [comment]
Hi, 
Patch for public/ticket/list.php line 211 : `// Definition of fields for list
        $arrayfields = array(
            't.datec' => array('label' => $langs->trans("Date"), 'checked' => 1),
            't.date_read' => array('label' => $langs->trans("TicketReadOn"), 'checked' => 0),
            't.date_close' => array('label' => $langs->trans("TicketCloseOn"), 'checked' => 0),
            't.ref' => array('label' => $langs->trans("Ref"), 'checked' => 1),
        	//'t.track_id' => array('label' => $langs->trans("IDTracking"), 'checked' => 0),
        	't.fk_statut' => array('label' => $langs->trans("**Status**"), 'checked' => 1),
            't.subject' => array('label' => $langs->trans("Subject"), 'checked' => 1),
            'type.code' => array('label' => $langs->trans("Type"), 'checked' => 1),
            'category.code' => array('label' => $langs->trans("Category"), 'checked' => 1),
            'severity.code' => array('label' => $langs->trans("Severity"), 'checked' => 1),
            't.progress' => array('label' => $langs->trans("Progression"), 'checked' => 0),
            //'t.fk_contract' => array('label' => $langs->trans("Contract"), 'checked' => 0),
            't.fk_user_create' => array('label' => $langs->trans("Author"), 'checked' => 1),
            't.fk_user_assign' => array('label' => $langs->trans("AssignedTo"), 'checked' => 0),`
