### ISSUE TITLE
Installation errors 12.0 at fresh install

### ISSUE THREAD

**Issue by davidNDU** [Dolibarr/dolibarr#13516]
# Bug
During a fresh install, an error message will come up when processing
htdocs/install/mysql/tables/llx_blockedlog.sql
After the sql-file is corrected (see below), there are two more error messages

## Environment
- **Version**: 12.0.0-alpha
- **OS**: Linux 3.10.0-714.10.2.lve1.5.19.8.el7.x86_64
- **Web server**: LiteSpeed 
- **PHP**: 7.2.29
- **Database**: 10.3.22-MariaDB

## Expected and actual behavior
htdocs/install/mysql/tables/llx_blockedlog.sql:
`	object_version varchar(32) DEFAULT '';
	certified integer
) ENGINE=innodb;`

After placing a ',' for the ';' there are two more errors:
`Create foreign keys and indexes for table llx_categorie_website_page.key Request 499 : ALTER TABLE llx_categorie_website_page ADD PRIMARY KEY pk_categorie_website_page (fk_categorie, fk_websitepage) | SQL Error DB_ERROR_1072 Key column 'fk_websitepage' doesn't exist in table
-- | --
Create foreign keys and indexes for table llx_categorie_website_page.key Request 501 : ALTER TABLE llx_categorie_website_page ADD INDEX idx_categorie_website_page_fk_website_page (fk_websitepage) | SQL Error DB_ERROR_1072 Key column 'fk_websitepage' doesn't exist in table`

But those errors will still allow proceding 'Next Step ->'
## Steps to reproduce the behavior
[*Verbose description*]

**Comment by davidNDU** [comment]
Also this error shows up:
`SQL Error : DB_ERROR_NOSUCHFIELD - UPDATE llx_c_country SET eec = 1 WHERE code IN ('AT','BE','BG','CY','CZ','DE','DK','EE','ES','FI','FR','GB','GR','HR','NL','HU','IE','IM','IT','LT','LU','LV','MC','MT','PL','PT','RO','SE','SK','SI','UK'); - Unknown column 'eec' in 'field list'`

**Comment by eoxia-jimmy** [comment]
Open this file https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/tables/llx_blockedlog.sql in your ftp, and replace semicolon at line 36 to a coma.

I think it just a typing error.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/13577
https://github.com/Dolibarr/dolibarr/pull/13578
