### ISSUE TITLE
TakePOS order notes not working

### ISSUE THREAD

**Issue by javierybar** [Dolibarr/dolibarr#13521]
# Bug
TakePOS order notes not working with last versions.
I can't find why doesn't work

@andreubisquerra can you help me?

**Comment by andreubisquerra** [comment]
Order notes use extrafields. You need create 'order_notes' complementary attribute line in invoices.

**Comment by javierybar** [comment]
Great! Now works!

**Comment by andreubisquerra** [comment]
@eldy we need more fields for TakePOS (many in a medium-term). For example order notes, change...
What do you think is the best way? 
1. Add extrafields. But the native modules don't use it.
2. Add fields to the llx_commande / llx_commandedet tables.
3. Add specific tables, for example llx_takepos_order_notes
4. Other way

Thanks Laurent for all your work.

**Comment by eldy** [comment]
@andreubisquerra Can you provide a list of fields you miss ?
The order note is for me already the "private note" (if this is information we don't want to be seen by customer on invoice)

**Comment by andreubisquerra** [comment]
@eldy the "private note" as order invoice note is right for me. But we need order notes for each line or use an extrafield.
Then to print the change on the receipt it might be enough to add a field in "llx_bank" with the field 'received'. And we can calculate the change.
I will need many more fields in the medium or long term, some examples:
- Print level (drink, starter, main curses, deserts...)
- Predefined notes by category
- Supplement category by category
- Save some data in the invoice: place, number of people

If you decide how to add this data, I can create them myself to prevents overloading you.

**Comment by eldy** [comment]
You can start with this:
- Add field "private_note" on the lines of orders and/or invoices. Edit/Read of this field would be done by TakePos only and may be open from interface with a hidden constant later.
- For notes on category, you can also introduce a field "private_note" and "public_note" with a tab "Notes" like any other object.

Then i suggest your to create one ticket per tables where you want to add data and suggest some fields name you want to add to table.
