### ISSUE TITLE
Module Builder: pdf_standard.modules.php missing

### ISSUE THREAD

**Issue by davidNDU** [Dolibarr/dolibarr#13520]
# Bug
This is to follow up on #13482 
`Message: Error File /home/public_html/doliTEST3/htdocs/lims/core/modules/lims/doc/pdf_standard.modules.php does not exist`

## Environment
- **Version**: 12.0.0-alpha
- **OS**: Linux 3.10.0-714.10.2.lve1.5.19.8.el7.x86_64
- **Web server**: LiteSpeed
- **PHP**: 7.2.29
- **Database**: MySQL or MariaDB 10.3.22-MariaDB

## Expected and actual behavior
Not sure what to expect. Should I place some version of _pdf_standard.modules.php_ from another directory?
If I copy this file: core/modules/product/doc/pdf_standard.modules.php
to directory home/public_html/doliTEST3/htdocs/lims/core/modules/lims/doc/
it results in this error: 
`Warning: count(): Parameter must be an array or an object that implements Countable in /home/nduwrdco/public_html/doliTEST3/htdocs/custom/lims/core/modules/lims/doc/pdf_standard.modules.php on line 175`

## Steps to reproduce the behavior
Object created with module builder.
Creation of new entry (CREATE) with status 'Draft'.
A click on 'VALIDATE' will result in this error message.
(The ID is now correct.)

**Comment by ksar-ksar** [comment]
Hello,

Could you check if the stable V12 close the bug ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
