### ISSUE TITLE
$form->editfieldkey() broken

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#13527]
# Bug
The function `$form->editfieldkey` used for notes, cost_price and many others is broken in `develop` as of 2020-04-08

## Environment
- **Version**: `develop` as of 2020-04-08

## Expected and actual behavior
"inline" option to edit field

## Steps to reproduce the behavior
look at the notes tab of a product. There is no way to activate the edit function

**Comment by atm-maxime** [comment]
Hi !
Sorry I can't reproduce with a fresh develop. But I have WYSIWYG activated.
Can you provide screenshot ?

**Comment by cfoellmann** [comment]
Works in current `develop` branch again
