### ISSUE TITLE
[BUG] Dashboard and the famous error "Could not draw pie with labels contained inside canvas"

### ISSUE THREAD

**Issue by ma0dubois** [Dolibarr/dolibarr#13534]
# Bug
On the Dashboard i've this error: "Could not draw pie with labels contained inside canvas".
![image](https://user-images.githubusercontent.com/17147012/78794091-91c5fd00-79b3-11ea-8913-9d9eca094d57.png)

So when i add this into the code of `core\boxes\box_graph_product_distribution.php` (~line 280):
```php
$i = 0; $tot = count($data3); $legend = array();
$truncsize = 5;
if ($tot >= 5) {
	$truncsize = 4;
}
while ($i <= $tot)
{
	$data3[$i][0] = dol_trunc($data3[$i][0], $truncsize); // Required to avoid error "Could not draw pie with labels 
contained inside canvas"
	$legend[] = $data3[$i][0];
	$i++;
}
```

I've a good graph  :-)
![image](https://user-images.githubusercontent.com/17147012/78794590-4102d400-79b4-11ea-8b98-e8af1c3c8e1d.png)

## Environment
- **Version**: 11.0.2
- **OS**: Linux 9df7d5ed6419 3.16.0-10-amd64 #1 SMP Debian 3.16.72-1 (2019-08-13) x86_64
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: 7.1.33
- **Database**: 5.5.5-10.4.10-MariaDB-1:10.4.10+maria~bionic

**Comment by atm-maxime** [comment]
I'm afraid your fix will not work everytime. You're mixing $tot which contains the number of products (which might be 500) and the trunc which is here to trunc the product ref to 5 digits max.
My guess is that this graphs should only show the 5 top products and have a "other" pie slice.

**Comment by eldy** [comment]
This problem is definetly fixed by changing the graphical engine (from jflot to chartjs). This is available for v12. You must wait v12 to have a complete fix.
