### ISSUE TITLE
Add a REST API to manage Taxes

### ISSUE THREAD

**Issue by naku** [Dolibarr/dolibarr#13538]
# Feature Request
Add a REST API to manage taxes

## Suggested implementation
Currently there is a REST API to pay client Invoices: /invoices and /supplierinvoices
Please add a REST API to list, add, pay taxes as well: POST /taxes/...

This is equivalent to the page /compta/paiement_charge.php

**Comment by naku** [comment]
Analog to how you implemented #11294 in version 11

**Comment by robochift** [comment]
_the request is still relevant and not yet covered by latest stable version_

Reopening this because I'm also interested.
The table already exist, we would just need the route `GET /setup/dictionary/taxes`
