### ISSUE TITLE
Add a REST API to manage Salaries

### ISSUE THREAD

**Issue by naku** [Dolibarr/dolibarr#13539]
# Feature Request
Add a REST API to manage salaries

## Suggested implementation
Currently there is a REST API to pay Invoices: /invoices and /supplierinvoices
Please add a REST API to list, add, pay salaries as well: POST /salaries /...

This is equivalent to the page /salaries/list.php, salaries/card.php...

**Comment by ma0dubois** [comment]
Hi,

Why don't develop your own module for that ?

**Comment by naku** [comment]
> Hi,
> 
> Why don't develop your own module for that ?

Why develop a seperate module for that? Salaries are part of core Dolibarr and it would be consistent with the rest of the API

**Comment by dpriskorn** [comment]
Would you be willing to give it a try? Try looking and copy pasting from a similar api class and submit a pull request. It should not be that hard and I can help you if you get stuck.
