### ISSUE TITLE
field thirdpartie s.price_level missing on import tool

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#13589]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Missing Field s.price_level on import tools (Case Product MultiPrice)

## Environment
- **Version**: [11.0.3] and [12.x]
- **OS**: [Linux]
- **Web server**: [Apache/2.2.34 (Unix)]
- **PHP**: [7.4.2]
- **Database**: [MYSqli 5.7.26]
- **URL(s)**: [/imports/import.php?step=5&format=csv&datatoimport=societe_1&filetoimport=...]

## Expected and actual behavior
[*Verbose description*]
Unable to find s.price_level field during importation process. This is important when product multiprice is selected and used. In the meantime, the exportation process is delivering more fields than during importation. One of them is s.price_level.

## Steps to reproduce the behavior

[Importation description :
Activate MultiPrice product on module Products configuration
Use importation tool process after creating a CSV ThirdParties file 

This import file file could be generated using the following :
To test s.price_level exportation 
Create products with several prices
Create ThirdParty with price_level value
Use exportation tool process to validate that s.price_level is exported.]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[*Files*]

**Comment by eldy** [comment]
What is the name of the "importable dataset" you used to import price level ?
Did you use "Customer prices (of products or services, multi-prices)" ?

**Comment by josett225** [comment]
@eldy for now I did not use the import tool "Prix clients (des produits ou services, multi-prix)" as I created directly 2 products with 7 sales prices each. I used only "Tiers (sociétés/institutions/particuliers) et attributs" and I could not find the price_level field on the import screen (see screenshots attached). However this field is there when exporting (see field 41 "Niveau de prix" on 3 screenshot). For your information, I am trying to migrate 1500 third parties that are B2C and B2B customers from another ERP. These B2B customers are Distributors and Resellers. Let me know if you need more information.

<img width="1318" alt="Capture d'écran 2020-04-13 16 22 12" src="https://user-images.githubusercontent.com/57623859/79127915-f661cd00-7da2-11ea-96c2-2f0eb43bc577.png">

<img width="1196" alt="Capture d'écran 2020-04-13 16 17 20" src="https://user-images.githubusercontent.com/57623859/79127736-b6024f00-7da2-11ea-9d25-6bf1ef741ee2.png">

<img width="1312" alt="Capture d'écran 2020-04-13 16 18 01" src="https://user-images.githubusercontent.com/57623859/79127742-bac70300-7da2-11ea-91bd-ca28bccb57bb.png">

**Comment by josett225** [comment]
@eldy  let me add that the export file I created is coming from another dolibarr installation 11.0.3. I used this file to import using a version 12. The screenshots are coming from v12.

**Comment by eldy** [comment]
If you used the "Tiers (sociétés/institutions/particuliers) et attributs", you want find the price_level field.
Because 1 thirdparty can have several price_level and several price. So you can't store this into one field. So to import prices "per level", you must first import third parties, then using the import profile "Customer prices (of products or services, multi-prices)" to import the price for each price_level.

For export, field is present, but if you add it, it will duplicate the line as often as there is price_level for each export. Exploding one line into several is possible but Inserting several lines into one is not possible, this is why you can't have it into import. You must import in 2 steps.

**Comment by josett225** [comment]
@eldy if I understand correctly a third party can get only one price_level (see screenshot) depending of the level of price we want to allocate it at one period of time : he cannot get 2 or more at the same time. Well I don't see it in the third party card; i can modify it but I cannot add several prices level. Of course if we want to give him a better price (or worst price), we have to change it in its third party card. For now I want to import the value 1,2,3,4,5,6 or 7 for each third party as we already setup several pricing level for resellers from Public Price to Platinum (see screenshot). The Third party database I am importing has already existing price_levels in place.
As you can see on  the screenshot, I did also a proposal draft. Automatically the price_level used is 3-Club2 at 80€. This is exactly the behavior we are expecting.

<img width="1227" alt="Capture d'écran 2020-04-13 17 46 10" src="https://user-images.githubusercontent.com/57623859/79135904-5e6ae000-7db0-11ea-8b47-60059fa8e0c2.png">
<img width="1213" alt="Capture d'écran 2020-04-13 17 46 39" src="https://user-images.githubusercontent.com/57623859/79135907-6034a380-7db0-11ea-861e-c2911cae9df1.png">
<img width="1207" alt="Capture d'écran 2020-04-13 17 52 54" src="https://user-images.githubusercontent.com/57623859/79135911-61fe6700-7db0-11ea-97ff-519accf64b63.png">

**Comment by eldy** [comment]
Sorry i made a mistake between "products" and "thirdparties". Yes, thirdparty can have only 1 price_level and should be available in import. I pushed a fix for v11.0.4
