### ISSUE TITLE
Modify variants of products

### ISSUE THREAD

**Issue by KGBob** [Dolibarr/dolibarr#13588]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*I create some variants of products, when i want to modify, i click SAVE or CANCEL i return to 'localhost/dolibarr/', and all others links begin with my host 'kgbob.fr/dolibarr/*]

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
You already opened this issue and I fixed it. See #13576

**Comment by KGBob** [comment]
Its not the same bug, thisone is with Save and Cancel buttons.

**Comment by KGBob** [comment]
Je vais le corriger tout seul pour moi, mais ça serait bien que les autres profitent aussi.

**Comment by eldy** [comment]
If you fixed it yourself, can you paste your fix here ?
Or can you also provide more information on how to reproduce the bug ?

**Comment by dpriskorn** [comment]
What version is this about?

**Comment by dpriskorn** [comment]
This is before v12 was released. Please upgrade to the latest version and reopen this if the problem persists.
