### ISSUE TITLE
user can't access list of projects

### ISSUE THREAD

**Issue by suged** [Dolibarr/dolibarr#13594]
11.0.3
project list doesn't display list of projects for which the user has read rights
line 711 of projet/list.php
there is a comment that seems relevant : why this ?
$userAccess = $object->restrictedProjectArea($user); // why this ?
if you replace this by $userAccess=1; the list seems to be displayed properly

**Comment by eldy** [comment]
The test check that the user has permission to read all project and if not that he is assigned to the project.
Can you reproduce the trouble on demo.dolibarr.org ?

**Comment by suged** [comment]
on the demo site, David has rights to display all projects (not only his) so I don't know how to reproduce.

**Comment by eldy** [comment]
You can try with user pcurie / pcurie

**Comment by suged** [comment]
it works with pcurie but he has read AND CREATE rights
my user has only read rights (if I add create rights to my user then the list works)

**Comment by eldy** [comment]
I removed permission create on pcurie.
I still can read projet list. Can you check ?

**Comment by suged** [comment]
I see... I don't understand. must be something else then... will try to find out.

**Comment by suged** [comment]
I can't figure out the problem..
the user is a listed contact on 1 project
on the project home page, under "last modified projects" the project is listed and accessible
on the "list" page, on top of the page I see Projets (1) = the number of projects is correct
but the list underneith is empty...

**Comment by suged** [comment]
> 

> my user has only read rights (if I add create rights to my user then the list works)

and I was wrong on this, sorry. even when user has create the list is empty

**Comment by suged** [comment]
OK. I found.
for the list to work, which uses restrictedProjectArea() the code of the role of the contact on the project must begin with PROJECT
I had added new roles in the dictionnary which had other code names, hence the problem.

Sorry if this was documented somewhere, I missed the warning.
