### ISSUE TITLE
code in proposal don´t work

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#13599]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
creation of code in proposal section don{t work correctly. When insert cccc part of code, system say "incorrect mask"

## Environment
- **Version**: 11
- **OS**: Linux us-imm-web16.main-hosting.eu 3.10.0-962.3.2.lve1.5.26.5.el6h.x86_64 #1 SMP Wed Sep 18 09:47:35 EDT 2019 x86_64
- **Web server**: LiteSpeed
- **PHP**: 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.2.24-MariaDB
- **URL(s)**: /htdocs/admin/propal.php

## Expected and actual behavior
Expected: How help describe, i expect that when I add cccc code in mask of proposal this code was be acepted
## Steps to reproduce the behavior
add cccc code to proposal mask predefined

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![2020-04-13](https://user-images.githubusercontent.com/28205134/79163034-e0084100-7da3-11ea-970b-fff50afed21b.png)

**Comment by atm-maxime** [comment]
PDid you try {cccc}{0000} ? I think you need to separate the code and the counter, just as dd mm and yy are separated.

**Comment by ksar-ksar** [comment]
Hello,

Could you try the above reply ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
