### ISSUE TITLE
Complementary attributes in new Credit Note are not prefilled - From Purchase Order/Invoice

### ISSUE THREAD

**Issue by jrgonzalezrios** [Dolibarr/dolibarr#13600]
# Bug
In a Purchase Order from the Commerce module for a vendor: when creating a new Credit Note from the Purchase Order's invoice,  complementary attributes (previously defined by me) are not set when creating the draft. It will save the complementary attribute if set manually, but they should be pre-filled just as when creating a regular invoice.

## Environment
- **Version**: 11.0.3
- **OS**: Ubuntu Linux
- **Web server**: Nginx/1.15.8
- **PHP**: 7.3.9
- **Database**: MySql 7.7.27

## Expected and actual behavior
Complementary attributes from a Purchase's Invoice should be pre-filled (copied) from the Invoice, when creating a Credit Note, to avoid human errors.

## Steps to reproduce the behavior
Create a Complementary attribute from the Setup -> modules -> Invoices -> Complementary Attributes -> NEW ATTRIBUTE

Create a Purchase order in the Commerce module, create an invoice.
Set data in the previously created Complementary Attribute.
From the Purchase Order's invoice, create a draft of a Credit Note.
In the wizard of a new Credit Note from the invoice, it will not have the data added in the complementary attribute of the Invoice. If manually settled, I will be saved. But It should be prefilled automatically.

**Comment by jrgonzalezrios** [comment]
Hi! this behavior stills in the latest version 11.0.4:

When creating a Credit note from a Purchase Invoice to a Vendor, exactly when using URL:

/fourn/facture/card.php?socid=4&fac_avoir=131&action=create&type=2

Complementary attributes are not being pre-filled with the same complementary attributes as the Invoice. (When creating an invoice from a Purchase Order, the complementary attributes are correctly prefilled)

**Comment by atm-maxime** [comment]
Are you sure complementary attributes should have the same value on credit note as on the invoice? Some examples, I have a "date of transfer to accountancy" that should not be copied, or a "date send"... May be options have to be added on complementary attributes to define this. Also when cloning, should we keep the value or not ? This would be a useful feature request.

**Comment by ksar-ksar** [comment]
Hi,

Could you check if it is still the case in V13 ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
