### ISSUE TITLE
[Request/Discus] can we change output folders for supplier invoices?

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#13607]
# Feature Request
Hello, can we change where documents are stored for supplier invoices?

currently it typical used 
```php
get_exdir($object->id, 2, 0, 0, $object, 'invoice_supplier');
```
so the result is
```
/documents/fournisseur/facture/1/0/SI2004-0001/
```
can we replace this, so that the result is the same as the most modules, like
```
/documents/fournisseur/facture/SI2004-0001/
```

<img width="347" alt="2020-04-14 14_17_30-api_documents class php - dolibarr - Visual Studio Code" src="https://user-images.githubusercontent.com/17874713/79224060-c7a72d80-7e5a-11ea-9189-d58b4b02ce58.png">

**Comment by Daviid-P** [comment]
Was this actually completed? Or just dropped?
+1 from me to dropping this format.
