### ISSUE TITLE
translation error :  "chèque" instead of "vérifier"

### ISSUE THREAD

**Issue by YoungFrog** [Dolibarr/dolibarr#13616]
I have fr_BE on my Accept Languages.
On the "add new third-party" form, the link "Chèque" should be "Vérifier" :

![image](https://user-images.githubusercontent.com/944076/79334455-a14bc580-7f20-11ea-9129-15aa68116504.png

In the fr_FR locale, it is correctly defined as "Vérifier":
https://github.com/Dolibarr/dolibarr/blob/cbe682582edf4c3724302fb0fb1ebff477e00b83/htdocs/langs/fr_FR/companies.lang#L342

But in my fr_BE locale, it is wrong:
https://github.com/Dolibarr/dolibarr/blob/cbe682582edf4c3724302fb0fb1ebff477e00b83/htdocs/langs/fr_BE/companies.lang#L3

Removing that line from the fr_BE locale works for me.

**Comment by dpriskorn** [comment]
Please fix it here: https://www.transifex.com/dolibarr-association/dolibarr/
Not related to core. Closing

**Comment by YoungFrog** [comment]
Thanks for the pointer.
However I don't know how transifex works and it seems they want me to create an account before doing anything else. I find that overkill. Let's hope someone else will fix the error.

**Comment by dpriskorn** [comment]
Accounts are mandatory, yes.
