### ISSUE TITLE
assign project on each line of invoice

### ISSUE THREAD

**Issue by suged** [Dolibarr/dolibarr#13619]
the same way each line of an expense report can be assigned to a different project
it would be nice to be able to do the same for lines of invoices
(useful for people who use projects as a simple analytics key)

**Comment by suged** [comment]
I still think it would be a great feature

**Comment by Hexor38** [comment]
I'm waiting this feature.
It would be very very usefull in our case

**Comment by Hexor38** [comment]
still interested by this
