### ISSUE TITLE
Hello everyone, I am a beginner in developing Android applications and I have a problem that I did not understand, please help me .

### ISSUE THREAD

**Issue by RDHimni** [Dolibarr/dolibarr#13628]
I am developing an application on Android Studio
When I put the application in the emulator it works well, but in the real phone the design flips

thats in emulator:
![Capture2](https://user-images.githubusercontent.com/50507265/79377657-4df76880-7f5c-11ea-9b5c-5222b896975c.PNG)
![Capture](https://user-images.githubusercontent.com/50507265/79377668-50f25900-7f5c-11ea-94d1-7c62fad0957a.PNG)

and thats in reale phone "infinix":
![Screenshot_٢٠٢٠٠٤١٥-١٩٣٠١١](https://user-images.githubusercontent.com/50507265/79377508-1983ac80-7f5c-11ea-9aaa-8c533de461bc.png)
![Screenshot_٢٠٢٠٠٤١٥-١٩٣٤٥٤](https://user-images.githubusercontent.com/50507265/79377533-23a5ab00-7f5c-11ea-909b-bf4e8f9d63d9.png)

**Comment by atm-maxime** [comment]
Hi !
I suggest you to go on Dolibarr forums to seek help with this. The GitHub is here to share code and issues about Dolibarr core, no to help developers on their specific developments.
Thanks for contributing to the community anyway !
