### ISSUE TITLE
TAKEPOS Bug paiement window under Firefox V75

### ISSUE THREAD

**Issue by iaoranamoa** [Dolibarr/dolibarr#13629]
# Bug
With Firefox V75 the display in the paiement window is mixed up
@andreubisquerra can you make a fix?

Best regards

## Environment
- **Version**: 11.0.3 only version tested

![image](https://user-images.githubusercontent.com/35940936/79388191-a2c8cc80-7fb8-11ea-97ae-58d4ae20317c.png)

**Comment by andreubisquerra** [comment]
This bug is solved in develop (Next Dolibarr 12)
