### ISSUE TITLE
Generate ODT invoice in ODT format with warning:Invalid argument supplied for foreach() in /home/gamescom/erp/GHT/core/class/commondocgenerator.class.php on line 301

### ISSUE THREAD

**Issue by cc-33** [Dolibarr/dolibarr#13630]
# Bug
After upgraded to 11.0.3 and a page with warning message is appeared when generate invoice in ODT format under the "Invoice" function.

## Environment
- **Version**: [11.0.3]
- **OS**: [Linux]
- **Web server**: [Apache]
- **PHP**: [7.3]
- **Database**: [Percona Server]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Warning: Invalid argument supplied for foreach() in /home/gamescom/erp/GHT/core/class/commondocgenerator.class.php on line 301

Warning: Cannot modify header information - headers already sent by (output started at /home/gamescom/erp/GHT/core/class/commondocgenerator.class.php:300) in /home/gamescom/erp/GHT/core/actions_builddoc.inc.php on line 103

## Steps to reproduce the behavior
Generate invoice in ODT format under the Invoice function

**Comment by cc-33** [comment]
I have added a conditional state to check the "if(!empty($extrafields->attributes[$object->table_element]['label']))" before the foreach operation and warning page disappeared.

Please let me know if it is OK.

The change is as below:
// Retrieve extrafields
		require_once DOL_DOCUMENT_ROOT . '/core/class/extrafields.class.php';
		$extrafields = new ExtraFields($this->db);
		$extrafields->fetch_name_optionals_label($object->table_element, true);
		$object->fetch_optionals();
===> condition add to check before the foreach operation
		if(!empty($extrafields->attributes[$object->table_element]['label'])){
			foreach($extrafields->attributes[$object->table_element]['label'] as $key => $label)
			{
				if ($extrafields->attributes[$object->table_element]['type'][$key] == 'price')
				{
					$object->array_options['options_' . $key] = price($object->array_options ['options_' . $key], 0, $outputlangs, 0, 0, - 1, $conf->currency);
				}
				elseif($extrafields->attributes[$object->table_element]['type'][$key] == 'select' || $extrafields->attributes[$object->table_element]['type'][$key] == 'checkbox')
				{
					$object->array_options['options_' . $key] = $extrafields->attributes[$object->table_element]['param'][$key]['options'][$object->array_options['options_' . $key]];
				}
				$array_contact = array_merge($array_contact, array($array_key.'_options_' . $key => $object->array_options['options_'. $key]));
			}
		}
		return $array_contact;

**Comment by ksar-ksar** [comment]
Hello,

Could you check if it is OK on V13 ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
