### ISSUE TITLE
Error mass mailing from thirdparty list (massaction)

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#13635]
# Bug
Mass mailing doesn't work when I try to send mail from thirdparty list with "massaction".
It happens when I select more then 1 recipient. Error gets:

## Environment
- **Version**: Dolibarr 10.x / 11.x / 12.x dev
- **OS**: Linux Mint / Debian
- **Web server**: Apache / Nginx
- **PHP**: 7.x
- **Database**: Mysql

## Steps to reproduce the behavior
1. Select more then one recipient with email in thirdparty list
2. Click on mass action Send Email into select
3. Click on Send mail button in form

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
I get this error:
![immagine](https://user-images.githubusercontent.com/1215488/79433538-884d1e00-7fcd-11ea-8557-19cb86e6d7a6.png)

## More Informations from code of actions_massactions.inc.php
$sendto variable is empty during process to fill all fields to send email.

**Comment by eldy** [comment]
I have fixed thing recently. Are you sure pb is still present with last develop version ?

**Comment by aschio** [comment]
with last pull done on Dolibarr 12.x alpha problem is fixed. Thanks
