### ISSUE TITLE
Fallo dolibarr TPV

### ISSUE THREAD

**Issue by albertosaanchz** [Dolibarr/dolibarr#13638]
Hola buenas, me sale este fallo en mi dolibarr cuando realizo una venta en TPV

Warning: count(): Parameter must be an array or an object that implements Countable in /homepages/35/d776888227/htdocs/clickandbuilds/dolibarr/Gestion_Ecopapis/mycyberoffice/core/triggers/interface_90_mycyberoffice_Cust.class.php on line 646

Warning: Cannot modify header information - headers already sent by (output started at /homepages/35/d776888227/htdocs/clickandbuilds/dolibarr/Gestion_Ecopapis/mycyberoffice/core/triggers/interface_90_mycyberoffice_Cust.class.php:646) in /homepages/35/d776888227/htdocs/clickandbuilds/dolibarr/Gestion_Ecopapis/cashdesk/validation_verif.php on line 366

La línea 646 es :
if (count($object->linkedObjectsIds['commande']) > 0)

Uso php 7.4, haber si alguien puede ayudarme, muchas gracias.

**Comment by ksar-ksar** [comment]
Hi,

The problem is comming from the module mycyberoffice.
This is not a core module => Ask the developper of the module.

**Comment by franknag** [comment]
Hey Alberto,

Por casualidad tu modulo de mycyberoffice es el que envia de dolibarr a prestashop?

**Comment by albertosaanchz** [comment]
Si, efectivamente y el TPV sigue fallando al terminar una compra.

**Comment by franknag** [comment]
Tuve muchos problemas con una version antigua que aun uso, pero el soporte del desarrollador no es muy bueno y no ofrece demos, lo tuve que reparar por mi cuenta y fue todo un dolor de cabeza, si quieres compártelo y te ayudo porque el mío no tiene gestión o actualización de ordenes

**Comment by dpriskorn** [comment]
Not related to core. Closing
