### ISSUE TITLE
Ticket entry Subject and Message should allow special characters like "

### ISSUE THREAD

**Issue by cc-33** [Dolibarr/dolibarr#13632]
# Bug
[Ticket entry Subject and Message should allow special characters like "]

## Environment
- **Version**: [11.0.3]
- **OS**: [Linux]
- **Web server**: [Apache]
- **PHP**: [7.3

## Expected and actual behavior
[Should allow charters like " (double quotation mark) to be entered in the Subject and Message field. When there is e.g. " (double quotation mark) in the text, repeatedly ask for filling the field ]

## Steps to reproduce the behavior
[When work with a creation of Ticket, the "Subject" and "Message" will repeatedly as to fill in when character like " (double quotation mark) is in the text typed.]

**Comment by eldy** [comment]
With future v12, " is allowed into message. They are removed from subject but just removed, rest of text is kept and it doe not ask value repeatedly.

**Comment by john-botella** [comment]
See #14833 #15017
PR : https://github.com/Dolibarr/dolibarr/pull/15892  https://github.com/Dolibarr/dolibarr/pull/15894

**Comment by ksar-ksar** [comment]
Hello,

Could check if V12 or 13 are correcting the bug ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
