### ISSUE TITLE
file install/mysql/tables/llx_c_shipment_package_type misses sql extensions

### ISSUE THREAD

**Issue by lespacedunmatin** [Dolibarr/dolibarr#13646]
# Bug
Hello,

I'm installing a fresh 11.0.3 with mysql.
In install/mysql/tables, the file llx_c_shipment_package_type has no extension.

## Environment
- **Version**: 11.0.3
- **OS**: All
- **Web server**: All
- **PHP**: All
- **Database**: Mysql
- **URL(s)**: install

**Comment by lespacedunmatin** [comment]
And the first line of the file seems to be an invalid comment (missing a space after ```--```).

**Comment by frederic34** [comment]
Renamed in V11
https://github.com/Dolibarr/dolibarr/pull/13666

Add in migration for V12
https://github.com/Dolibarr/dolibarr/pull/13667
