### ISSUE TITLE
Italian legal form Società occulta incorrectly commented in install/mysql/data/llx_c_forme_juridique.sql

### ISSUE THREAD

**Issue by lespacedunmatin** [Dolibarr/dolibarr#13647]
# Bug
In file htdocs/install/mysql/data/llx_c_forme_juridique.sql, line 198, we found `--INSERT INTO llx_c_forme_juridique (code,fk_pays,libelle,isvatexempted,active) VALUES ('314',3,'Società occulta',0,1);`, wich is a malformed comment in MySQL 5.7.23. But according to italian wikipedia, Società occulta might be a valid form, So I wonder if the comment is a mistake or not. Comment introduced by @eldy in 9913e87.

**Comment by eldy** [comment]
what do you mean with 
"is a malformed comment in MySQL 5.7.23" ?

**Comment by ksar-ksar** [comment]
Hello,

Could you answer to the question above ?

**Comment by lespacedunmatin** [comment]
In https://dev.mysql.com/doc/refman/5.7/en/comments.html, i read : "the `-- ` (double-dash) comment style requires the second dash to be followed by at least one whitespace or control character".

I think that I was getting errors message because the comment lacks this following whitespace.
