### ISSUE TITLE
Bug: Project's Overview - Loan linked automatically on every project

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13651]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Once created a loan, it is automatically linked to every project which is not correct. The payment of loan does not show in project too.

![Capture](https://user-images.githubusercontent.com/52134143/79638033-079d4600-81b6-11ea-88ca-798710ca0c1d.PNG)

The project does not show in drop down list, only show 2 projects but i have 3 in the list are open status.

![project](https://user-images.githubusercontent.com/52134143/79638121-7da1ad00-81b6-11ea-97d9-f510db8aa1cd.PNG)

## Environment
- **Version**: 11.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /projet/element.php?id=5&action=unlink&tablename=loan&elementselect=4&page_y=1887.199951171875

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
I think this is fixed in branch v11 for futur 11.0.4. Feedback will be welcome once 11.0.4 is released
