### ISSUE TITLE
Bug: Miscellaneous payments type

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13652]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Miscellaneous payments type display wrongly. its show payment type short instead of bank transfer.

![payment](https://user-images.githubusercontent.com/52134143/79641674-92d50680-81cb-11ea-8397-d7fd72d888ae.PNG)

## Environment
- **Version**: 11.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /compta/bank/various_payment/list.php?leftmenu=tax_various&mainmenu=billing

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Can't reproduce with future v12
