### ISSUE TITLE
Bug load langs of external module on cronjob

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#13668]
Since Dolibarr 9, when [run cronjob](https://github.com/Dolibarr/dolibarr/blob/9.0/htdocs/cron/class/cronjob.class.php#L953), it tries to load 2 times module langs. But the 2nd loading has no effect even if no lang file found for the 1st.

So for an external module, the lang file is never loaded on cronjob.

What is the better PR ?
- load only once module lang like previous versions
- or fix translate.class.php to allow load **'module'** and **'module@module'**

## Environment
- **Version**: Dolibarr 9 to 11
- **URL(s)**: /cron/card.php?id=**__ID\_**

**Comment by atm-maxime** [comment]
See discussion here #12213

**Comment by eldy** [comment]
Your cron method must load itsleft language file of module. So should make langs->load("module@module");
But be carefull that $langs object is loaded and that the language you want to use is set with $langs->setDefaultLang(...)  BEFORE you make the langs->load.

**Comment by tuxgasy** [comment]
I already do that. But before my class and method are called, the class [Cronjob](https://github.com/Dolibarr/dolibarr/blob/9.0/htdocs/cron/class/cronjob.class.php#L1069) do that $langs->load('mymodule'). So do $langs->load('mymodule@mymodule') after has no effect.

**Comment by ksar-ksar** [comment]
Hi,

A FIX has been introduced in V11, could you check if now it is working ?

**Comment by tuxgasy** [comment]
Hi,

Yes, I close this issue.
