### ISSUE TITLE
unable to add more than 9 pictures in product card at once

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#13672]
# Bug
[impossible to add 10 pictures and more on product card at the same time]

## Environment
Version: [11.0.3] and [12.x]
OS: [Linux]
Web server: [Apache/2.2.34 (Unix)]
PHP: [7.4.2]
Database: [MYSqli 5.7.26]
URL(s):[http://.../product/document.php?id=1]

## Expected and actual behavior
[When trying to add 10 files (pictures) in the product tab then nothing happens with no error message. With 9 and less it works fine in both version 11 and 12]

## Steps to reproduce the behavior
[go to product card, select attach files, select 10 pictures files and then send files. Nothing happens. Thy with 9 or less. 
Fyi : I added this variable : PRODUCT_MAX_VISIBLE_PHOTO = 10 ► Show a maximum number of product photos (as thumbnails) on the product main card. Example, setting this constant to '5' will show the first five product photos found on the product card.]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[*Files*]

**Comment by bmamine** [comment]
Hello;
I tried to reproduce the some error, but the operation succed without error! 

![#13672b](https://user-images.githubusercontent.com/6966925/79867430-d8612180-83cd-11ea-9b5a-1731a0ed145e.png)

![#13672a](https://user-images.githubusercontent.com/6966925/79867412-d4350400-83cd-11ea-97f3-745fb0e8bd46.png)

**Comment by josett225** [comment]
Thanks for your test and feedback. I did several other test with Safari and updating my Firefox. It is ok now. I close the ticket.
