### ISSUE TITLE
BUG: Sort order on ticket severity, based on severity "pos" field instead of actual severity id

### ISSUE THREAD

**Issue by jukyyy** [Dolibarr/dolibarr#13675]
# Bug
[Sort order on ticket severity, based on severity pos field instead of actual severity value]
Pos field is dedicated to define sort order of severities

## Environment
- **Version**: [11.0.3]
- **OS**: [Linux Debian 10]
- **Web server**: [Apache/2.4.38]
- **PHP**: [7.3.14]
- **Database**: [MariaDB 5.5.5]
- **URL(s)**: [/ticket/list.php]

## Expected and actual behavior
[*Clicking on severity column label sorts ticket by actual severity*]

## Steps to reproduce the behavior
[*Clicking on severity column label sorts ticket by severity_code string*]

**Comment by ksar-ksar** [comment]
Hello,

Have you tried on V13 ?
