### ISSUE TITLE
Replenishment -add a total count on top of page

### ISSUE THREAD

**Issue by pcworxstech** [Dolibarr/dolibarr#13698]
# Feature Request
Drop down choice on Replenishment screen for viewing how many items per page

## Use case
On most screens in Dolibarr, next to how many pages, there is a drop down allowing the change of how many items viewed per page. This helps when printing information from the screen to the printer and to view more items than is set by default settings in global setup.

## Suggested implementation
Have a drop down next to page number. Also show how many pages like other screens do in "list" for Sales Orders, Purchase Orders... etc. 

## Suggested steps
See screenshots
![replen_option](https://user-images.githubusercontent.com/54542571/79992945-2c2d4280-8482-11ea-8e1e-26833f37dfa6.jpg)
![order_list](https://user-images.githubusercontent.com/54542571/79992952-2e8f9c80-8482-11ea-8e2e-385585c3e821.jpg)

**Comment by atm-maxime** [comment]
Hi. Thanks for your feedback.
Because this page is basically a form with many inputs, if we display more lines there's a risk that the server wouldn't allow too many inputs (php limits, max_input_vars and max_post_size).
So I think we shouldn't allow to display more lines.

**Comment by pcworxstech** [comment]
That makes sense. 
 Is there any chance that it could display the page count at the top so the user knows how many pages there are total??

**Comment by atm-maxime** [comment]
Yes why not. Let's leave your feature request, just rename it like : add a total count on top of replenishment page.
