### ISSUE TITLE
search is very long on supplier orders (tested on v10)

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#13707]
Hello, when i try to search on supplier orders from the Search left menu, it is very long and i have to kill the process in mysql ! 
Indexes seem to be ok; no problem with search on customer orders that seems to be coded the same way.
If i remove the fields note_public, note_private and product description in the $searchall array , the search is done without trouble.

**Comment by eldy** [comment]
How many entry do you have in table llx_commande_fournisseur ?

**Comment by altairis-tof** [comment]
about 7000 in commande_fournisseur where it is slow and about 27000 in commande where i's quick

**Comment by eldy** [comment]
With the log file, can you identify the SQL request(s) that is long ?

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by BebZ** [comment]
I confirm looking for a supplier order from the search menu takes dozens of
minutes and sometimes crashes

I don't think it is updated in V11 or V12

Le ven. 7 août 2020 à 11:19, Egils Consulting <notifications@github.com> a
écrit :

**Comment by ksar-ksar** [comment]
Hello,

Could you check in V13 ?
