### ISSUE TITLE
Error  23502 when creating manufacturing order

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#13702]
# Bug
When I create a manufacturing order from a BOM which has a few entries the error 23502 pops up and no manufacturing order was created. The exact message is: 
**ERROR: 23502: null value in column 'tms' violates not-null constraint DETAIL: Failing row contains (12, , 1, null, 1, 3, null, null, null, 2020-04-22 20:31:09, null, null, 1, null, null, null, null, 0, 69, null, null, 7, null). SCHEMA NAME: public TABLE NAME: llx_mrp_mo COLUMN NAME: tms LOCATION: ExecConstraints, execMain.c:1736**

## Environment
- **Version**: 11.0.3
- **OS**: Debian buster
- **Web server**: Apache
- **PHP**: 7
- **Database**: Postgresql

**Comment by eldy** [comment]
This should be fixed with v12 where manufacturing order become stable.

**Comment by aedart** [comment]
Unfortunately this appears not be be resolved in version 12.0.2, using postgres database.
Could you please release a patch to fix this asap?

Error that I receive, when attempting to create a manufacturing order:

```
ERROR: 23502: null value in column 'tms' violates not-null constraint DETAIL: Failing row contains (6, , 1, For in-house development test, 2, 2, null, null, null, 2020-09-01 09:45:12, null, null, 1, null, null, null, null, 0, 1, 2020-09-01 11:44:00, 2020-09-01 11:44:00, 1, null). SCHEMA NAME: public TABLE NAME: llx_mrp_mo COLUMN NAME: tms LOCATION: ExecConstraints, execMain.c:1960
```

**Comment by eldy** [comment]
Can you try to run this 3 commandes on your postgres database ?
CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_mrp_mo FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_mrp_mo_extrafields FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_mrp_production FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();

**Comment by aedart** [comment]
Hi @eldy 
Thanks for your reply. I resolved the issue by switching to MariaDB and avoid the evt. trouble of running on a database, which might not be as supported, as perhaps otherwise claimed by Dolibarr (_nothing dubious intended hereby_).
The solution worked and I'm rather satisfied with the system - thanks :)

**Comment by esteveboix** [comment]
Hi @eldy ,

I'm experiencing the same issue. I tried to add the triggers you suggested, but the database already have them applied, in all those 3 tables. I'm on 12.0.4.

`ERROR:  trigger "update_customer_modtime" for relation "llx_mrp_mo" already exists
SQL state: 42710`

The message is the same for every table.

Regards,
Esteve
