### ISSUE TITLE
Error with thousands separator dot, when editing product line.

### ISSUE THREAD

**Issue by maosquare** [Dolibarr/dolibarr#13705]
# Bug
[Error with thousands separator dot, when editing product line.]

## Environment
- **Version**: [*11.0.3*]
- **OS**: [*Linux*]
- **Web server**: [*Apache*]
- **PHP**: [*7.4.4*]
- **Database**: [*MySQL or MariaDB 5.5.5-10.1.44-MariaDB-cll-lve*]
- **URL(s)**: [*/dolibarr/htdocs/compta/facture/card.php?*] and others...

## Expected and actual behavior
[*When you need to edit a product or service line, you must delete the thousands separator point. Otherwise, the values are changed.The system confuses the dot char with the comma char.

Affected ID lines "price_ht" and "buying_price*]

## Screen Captures

Previous to edit product price

![1 Antes](https://user-images.githubusercontent.com/63565579/80055404-287fd700-84e7-11ea-9423-359a786df681.PNG)

After edit product price, without delete dot char

![despues](https://user-images.githubusercontent.com/63565579/80055466-52d19480-84e7-11ea-9dcc-1e1f55705747.PNG)

Manual edit dot char

![antes corregido](https://user-images.githubusercontent.com/63565579/80055501-667cfb00-84e7-11ea-87f6-1464fab56193.PNG)

Result editing dot char

![despues corregido](https://user-images.githubusercontent.com/63565579/80055521-7399ea00-84e7-11ea-8a5f-1458f3b1b3f4.PNG)

**Comment by maosquare** [comment]
I've solved, Fail configure limits and decimals

**Comment by gavrielzs** [comment]
how did you solve it? thanks!

**Comment by gavrielzs** [comment]
> I've solved, Fail configure limits and decimals 

how did you solve it? thanks!
