### ISSUE TITLE
Unable to set extrafields on societe via module triggers

### ISSUE THREAD

**Issue by nervo** [Dolibarr/dolibarr#13708]
# Bug
This commit (https://github.com/Dolibarr/dolibarr/commit/7108f68db9928344824f0238c6d22d5c517870ba) removed the societe insertExtraFields hooks, which was the only way to set extrafields via a module.
Right now, the`COMPANY_MODIFY` trigger is runned just after the `insertExtraFields()` call, so that any extra fields modifications appearing into the trigger won't be taken into account.

## Environment
- **Version**: 10.0.3
- **OS**: Linux
- **Web server**: Apache 2.4.10
- **PHP**: 5.6.40
- **Database**: MySQL 5.5.62
- **URL(s)**: `/societe/card.php?socid=xxx`

**Comment by altairis-tof** [comment]
hello,
you have a trigger in the insertExtraFields() function with a extrafieldaddupdate context.
so you have to define a trigger with something like 
`if ($action == 'COMPANY_MODIFY' && ! empty($object->context['extrafieldaddupdate']))
{
}`

**Comment by altairis-tof** [comment]
furthermore, if you need to use a hook, you still can use the doActions() hook.

**Comment by eldy** [comment]
Because this PR makes a lot of change into architecture, it will be included in v12. Others PR have been done for this. Please check everything is ok with develop branch so it will be ready for v12.

**Comment by nervo** [comment]
@eldy it's not a PR, it's just an issue :)

As far as i can see, `insertExtraFields` need a `trigger` parameter to trig something (https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/class/commonobject.class.php), this parameter is not defined when called in societe update (https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/societe/class/societe.class.php#L1398)

Do i miss something ?

**Comment by eldy** [comment]
Sorry. It's me.
Well, so my answer should be "Fix should be ready for v12".
Yes, for company update there is no parameter on insertExtraFields because the trigger to say that a field on company record (common or extra) is called later by the call_trigger()...

**Comment by nervo** [comment]
@eldy for sure, `call_trigger` is called right after `insertExtraFields` but that's too late to update extrafields, that's exactly why i have opened this issue :)

Correct me if i'm wrong, but i don't get what exactly in your pr could solve this, you just change the "if" statement (https://github.com/Dolibarr/dolibarr/commit/72c6ac1c7263dcc73aed38f8da1a71faf386c5ee#diff-0d854268fb06979ab0c5274687f2e78dR1396) :)

**Comment by nervo** [comment]
Ok, just for the record, one could simply work around this issue manually calling `insertExtraFields()` on societe object.
