### ISSUE TITLE
A basket to manage ecommerce on website module

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#13711]
A basket on the website, this must be an order in draft state in base. Like sales on the POS which have a module_source field which inform 'takepos' or' simplepos "when the invoice or order has been generated by the POS module, it will also be necessary to supply the module_source field with 'website' when the basket is a basket. In the 'pos_source' field, the POS modules put the terminal ID, it will be necessary to set 'session ID @ website ID ''
A website is a kind of POS.
The customer, as for the POS must be, either a generic customer defined in configuration (for the case where the basket is filled without being connected to the website), or a third party created when the user creates his account and if he is connected.

= About session management =
The website is already running in session, but without a known login. We must therefore add a step to protect the basket pages. To protect pages that must be protected into a session, we can just add an include into pages. For exemple for page, we can create a page index_private.php
into the directory of website, like we do for the index.php or wrapper.php page that is generated in all websites directories.

This page should contains:

if (! defined("MAIN_AUTHENTICATION_MODE")) define('MAIN_AUTHENTICATION_MODE', $websitekey);

just after the line 
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;

Then the include of master should be replaced by an include of main.inc.php (this will call a redirect to a login if not login, and the set of MAIN_AUTHENTICATION_MODE allow to have another session id than the one used for backoffice).

= About storing accounts
Adding constant WEBSITE_USE_WEBSITE_ACCOUNTS to 1 make a new table available to store accounts of a website for a thirdparty (so the login and pass to the website).
A tab is also available on the thirdparty record to administer it from backoffice.

**Comment by dolibarr95** [comment]
Hello

_Just to share my opinion/work_
For my business I've create a online shop (b2b only). This one is full connected to Dolibarr.

| Shop  | Dolibarr |
| ------------- | ------------- |
| Add item to cart  | Add item to prov proposal  |
| Validate cart  |  Validate proposal (available 1 month)  |
| Sign proposal and pay  | Sign proposal and create prov order  |

About the users : I register them on Dolibarr add them to a specific group and disabled them (so they can not connect to Dolibarr).

About payment : All can pay by card. Some of them can pay later (at reception) by bank transfer.

About session : they are differents of Dolibarr

**Comment by ptibogxiv** [comment]
I used draft order with pos_source and module_source with my doliconnect module. Already functionnal.

Another thing to do, better intégration of stripe for order:more automation, can do payment with later validation (within 7 Day) or can do payment on invoicing (need more savings of default stripe payment tmode with other internal customer's bank account)

**Comment by BebZ** [comment]
Hello courageous ecommerce pioneers :) !
I like the idea of @dolibarr95 that stores the baskets in a prov proposal :)
How do you handle if the customers leaves the website for some days and comes back, he can find its prov/basket, or create a new one ? old baskets/prov are deleted with a cron ?
If you can give us an insight of your b2b only website, I am in the same case....
Magento2 is pissing me off, and my customers are really looking for a basic add to cart and history solution...
No need of SEO... transactional emails etc... all this bullshit makes ecommerce platforms so impossible if you manage juste 500 customers regularly...

Thanks in advance !

**Comment by dolibarr95** [comment]
Hello @BebZ 
The prov stay as long as the customer did not validate it. Once validated he has 30 days to sign it (or it become unsigned quotation and disapers from his quote list).
There is no cron only a check at his connection, change quote satus (of +30days only) from validated to unsigned.
To sign it he have to register his PO number (Réf. client in french) and pay (now or later depending of the customer).

Actually all my shop contains personnal functions but I would like to change everything by using the Dolibarr API
There is no backoffice in my store everyhing is managed from Dolibarr.

**Comment by BebZ** [comment]
Wow, a dream "b2b" shop ! 

If there is no back office, that's sooo much more lightweight :)

Do you plan to share it  / sell it ? give it an overview ? 

We know Dolibarr API very well (SOAP and REST)... we used SOAP and recoded all ecommerceng with REST...

if you need help, we have hands and brains :)

we can recode it iif you wish and and push you all the code in live :)

**Comment by dolibarr95** [comment]
since I am not a Dolibarr dev  I avoid to share my work (there must be al lot of error in my code), but I share all my tips (eg:https://www.dolibarr.fr/forum/t/api-envoi-de-colis-avec-tnt-ups-fedex-gls-dpd-etc/29563).
My store is not so standard because it has a lot of exotic funtion (maintenance sheet, nomenclatures).
Tks for your help.

**Comment by BebZ** [comment]
Snif... We are not Dolibarr devs too... just users with development skills, like you seem to be.
We often help each others by email and with crowdfunding with Jeffinfo (module accounting) 
Because all our specific needs does not match the community needs :)

**Comment by dolibarr95** [comment]
I will try to open my work to other, but first i have to clean a little my work...

**Comment by priojk** [comment]
Are there any news on this topic? I am currently using a custom solution (not a true cart), where a validated order (not a proposal) gets created, when a B2B customer wants to purchase something. I noted that starting from Dolibarr version 15.0, there is new functionality included in core to automatically record a successful online payment, which is related to this order, and to automatically create the respective invoice, which makes the overall transaction much easier.

**Comment by BebZ** [comment]
@dolibarr95 should keep us updated if he had time to update his work ... We proposed him help but maybe there is too sensitive data insid his module ? Or just not-well-finished ?
Thanks in advance

**Comment by dolibarr95** [comment]
Hello
@BebZ my ecommerce website is fully connected to Dolibarr but to much customised. It's a oscaro.com like website : 
User inform his machine serial number (as a licence plate) the he acced to the spare parts.

What I have to do
1. I would like to rewrite my code by using Dolibarr API (actually I use rewrited simplified class).
2. The I have to delete all my custom module links

**Comment by priojk** [comment]
Could still be useful.
