### ISSUE TITLE
overwrite_translation don't work.

### ISSUE THREAD

**Issue by code42fr** [Dolibarr/dolibarr#13718]
overwriting translation tables with a new module don't work.

Tested on Dolibarr 9.x, 10.x, 11.x

Maybe, we could create a new function into the DolibarrModules.class or in the function insert_module_parts !

**Comment by eldy** [comment]
Yes the table this->overwrite_translation in external module is not yet implemented.
A new function call into DolibarrModules is welcome.

**Comment by code42fr** [comment]
Let's go

**Comment by priojk** [comment]
This issue is still relevant.
