### ISSUE TITLE
[Dolibarr] how to get product stock by warehouse ?

### ISSUE THREAD

**Issue by RDHimni** [Dolibarr/dolibarr#13739]

**Comment by altairis-tof** [comment]
at the bottom of the stock tab of the product card ?

**Comment by altairis-tof** [comment]
or by function nb_products() of the entrepot.class.php in product/stock/class

**Comment by altairis-tof** [comment]
please be more specific if you want a good answer ;-)

**Comment by RDHimni** [comment]
@altatof  thank you for answer but my questio is how to get product quantuty by warehouse usin rest api

**Comment by dpriskorn** [comment]
Did you mean via REST? It's probably not implemented yet. You are welcome to send a pull request.
