### ISSUE TITLE
Allow the Cloning/Sharing/Sync of a list of categories between entities.

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#13748]
## Feature Request
The possibility to select the entities that can share the same tags/categories tree, maybe very useful, and very easy to implement, just declaring a category tree assigned to one or several entities: (products, customers, suppliers, contacts or members...) but maintaining the copy of their separated categories tree for each entity.

## Use case
For example: Vendors and products have the same Tags/categories for us, since we use the categories to find the potential suppliers of a product.
Our vendors of power supplies, have the tag "power supplies", and also in the product categories, exist the tag "power supplies" to filter all the products of the catalogue that are power supplies.
This means, that every time we add a one new category in vendors, need to add the same new category in products manually.

## Suggested implementation
In the setup configuration of the Tags/Categories module, add a configuration option "sync list of categories between entities" allowing to select: products, customers, suppliers, contacts or members (or any new entity that the module will support)
Then a list of "Syncs" between entities can be generated.
Sync1: Suppliers, products
Sync2: Customers, contacts
Sync3...
Then every time a new tag/category is deleted/added/updated, the action should be performed in all the entities belonging the "sync". (In my example: Add to supplier a new tag, will also add it in products. And viceversa: every time a new tag will be added in products, will be added in suppliers.

**Comment by edupulpillo** [comment]
Nobody think is interesting this feature?

**Comment by edupulpillo** [comment]
This allows to do not neede to repeat the same labelling of categories, if are needed the same between different entities.

**Comment by hregis** [comment]
@edupulpillo
This is for multicompany module?

**Comment by edupulpillo** [comment]
Not necessary, even in the same company is very useful to sync for example the tree of tags used for Products/suppliers, since a lot of times is useful to have the same classification.
Example:
Computers
- Desktop
- Laptop
- Gaming
Having same tags in products and suppliers of that products,

In any case for multicompany, also is a good point.

**Comment by edupulpillo** [comment]
Nobody thinks is useful ?
