### ISSUE TITLE
Modifying Extrafields checkbox throws an error

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#13753]
# Bug
If you edit an extrafield of type checkbox you get a database error in the log.

## Environment
- **Version**: 11.0.4 from git
- **OS**: Linux debian 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 from bitnami VM
- **Web server**: Apache from Bitnami VM
- **PHP**: 7.3.13
- **Database**: MySQL or MariaDB 5.7.28
- **URL(s)**: /admin/expeditiondet_extrafields.php

## Expected and actual behavior
Editing an extrafield should not cause any issues. Editing an extrafield of type checkbox results in a database error as it tries to delete an index that doesn't seem to exist

## Steps to reproduce the behavior
- Go to the Expeditions module (tested on this module, I assume similar issues happen in every module, but I can only confirm it in Expeditions)
- Create an extra field of type checkbox
- Click to edit the extrafield, no need to change anything
- Check the log

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[dolibarr-9.log](https://github.com/Dolibarr/dolibarr/files/4538519/dolibarr-9.log)

**Comment by eldy** [comment]
Go on setup of extra fields. Did the checkbox "unique" is checked ?

**Comment by ToniTen** [comment]
No. All fields were left in their default values other than "Label or translation key", "Attribute code", and "Type"

EDIT: It might not be relevant, but the database was upgraded from dolibar 10.0.6 initial install to current git

**Comment by eldy** [comment]
If would be intersting to know if trouble occurs with an extra field created after migration

**Comment by ToniTen** [comment]
Yes it happens. I made this extrafield from scratch to test this (I noticed the issue while dealing with another issue that was actually the fault of my custom php document code and that I was fixing when migrating from dolibarr 9 to 11) efc is **e**xtra **f**ields **c**heckbox, because I could not think of a better acronym, and I reproduced it on a mostly clean bitnami vm that I use for testing,

**Comment by ToniTen** [comment]
I tested this on a clean bitnami VM I just downloaded and the issue appeared right away:
Steps to reproduce:

- Download bitnami vm for dolibar (v. 11.0.3-1 from https://bitnami.com/stack/dolibarr/virtual-machine)
- Enable debug logs and any module that you want to add a checkbox to
- Set debug level to 3 (ERR) and purge debug logs (not necessary, but makes it more evident)
- Go to a module setup, go to complementary attributes, and add a new attribute (name and code are irrelevant) set type to Boolean (one checkbox), leave everything else at default.
- edit the attribute, don't change anything, save it
- check your log to see the two lines with the error

**Comment by dpriskorn** [comment]
Can someone reproduce this on v12?

**Comment by egils-consulting** [comment]
Can someone reproduce this on v12?

**Comment by ksar-ksar** [comment]
Hi,

Could you check on V13 also ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
