### ISSUE TITLE
Phpmyadmin in Doliwamp - Upgrade not performed

### ISSUE THREAD

**Issue by Kouamgossi** [Dolibarr/dolibarr#13755]
HI
![image](https://user-images.githubusercontent.com/62134771/80358086-696f4700-886b-11ea-9b5c-13a777a731b3.png)
I have upgraded my doliwamp from  10.0.3 to 11.0.2 but still failed to get the embedded phpmyadmin updated
It seems that doliwamp newer versions do not upgrade phpmyadmin. can someone help on the process  to achieve phpmyadmin update from version 4 to version 5.0.2
The trick that consists In placing the new  unzipped  version in the php directory and changing the alias path is unfortunately not working. 
BR

**Comment by ksar-ksar** [comment]
Hi,

Could you check with newer versions (V13) ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
