### ISSUE TITLE
Add background image to member card

### ISSUE THREAD

**Issue by jymaire** [Dolibarr/dolibarr#13750]
# Bug
I would like to add some fancy background image to member cards. I wanted to use the variable ADHERENT_CARD_BACKGROUND to do this but it was commented some years ago by this commit https://github.com/Dolibarr/dolibarr/commit/e3a79d87037e31a9e8599ab1996dda8868c3e807

Is there any reason to leave this piece of code commented?

Thanks for the work you are doing on this software

**Comment by atm-arnaud** [comment]
@eldy  New feature here
