### ISSUE TITLE
Add import feature for BoM

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#13763]
# Feature Request
Right now, there's no way to import BoM for products into Dolibarr. Given that even minute variations, that would normally be handled by product variants, can result in quite different BoMs, this means they must be added by hand, one after another.

For example, my company has a single product, that, once you account for all possible variations, results in 12288 references. Up to now, we have not had the BoMs into the system (since the was no stable BoM functionality), and manually adjusted stock levels for the parts periodically, but we were looking into integrating our workflow into the system. Problem is, even at 5 minutes per 40+ part BoM, we would be looking at 1024 man/hours to take something that we have the listings for and introduce it into the system. This is also just one product among many. Importing all the variants into Dolibarr was quick and painless, via CSV import, and I expect that I'm not alone in this situation, from those that need BoM and Manufacturing Orders.

**Comment by StephaneLesage** [comment]
+1
There is Export, but no Import.
I will not be able to migrate from our current ERP with hundreds of BOMs.

**Comment by jerome-vinay** [comment]
+1 we need this feature to improve ergonomics.
