### ISSUE TITLE
Calcul montant temps consommé incorrect dans facture générée

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#13769]
## Bug
Soit un utilisateur « lambda » au « Tarif horaire moyen » de 10€ (fiche utilisateur)
lambda est impliqué sur une tâche TK du projet PJ.
Il impute 2h puis 1h sur cette tâche TK.

Au niveau de l’onglet « Temps consommé » de la fiche du projet PJ, je vois bien les deux lignes d’imputation de 2h puis 1h sur la tâche TK.

Je sélectionne ces deux lignes et crée une facture (PROVn), et me rends sur la fiche de cette facture.

Je découvre qu’elle contient une ligne :

Temps consommés : 03:00 pour un PU HT de 30€ et Qté 3, soit 90€

C’est faux puisque le tarif horaire est de 10€ et qu’on facture 3h, soit 30€.

Par ailleurs, comment obtenir mieux que "Temps consommé : ..." comme ligne de facture et y afficher le nom du projet et de la ou les tâches sur le(s)quelle(s) ce temps aura été consommé ?

## Environment
- **Version**: *11.0.3*

**Comment by manu-p** [comment]
Let's try it in English... for  for a better welcome, perhaps?

Let's says a user X is at the "Average hourly rate" of 10€ (user file).
X is involved on a TK task of the PJ project.
He allocates 2h then 1h on this TK task.

In the "Time consumed" tab of the PJ project sheet, I can clearly see the two allocation lines of 2h then 1h on the TK task.

I select these two lines and create an invoice (PROVn), and go to the record of this invoice.

I discover that it contains a line:

Consumed time: 03:00 for a PU HT of 30€ and Qty 3, that is 90€.

That's not true since the hourly rate is 10€ and we charge 3 hours, or 30€.

Moreover, how to get better than "Time consumed: ..." as an invoice line and display the name of the project and the task(s) on which this time will have been consumed?

Translated with www.DeepL.com/Translator (free version)

**Comment by atm-maxime** [comment]
Hi !
You're very welcome :)
I'm sure someone will check your issue and fix it. Just a little patience.
Cheers

**Comment by lmag** [comment]
Bonjour,

Il me semble que le fonctionnement est un peu différent:
Si tu pointes 2 heures, puis 1 heures
Lorsque tu lances la facture si tu souhaites un coût horaire spécifique il faudra choisir un service avec un prix et une unité de temps par exemple
service 1 : 70€ pour 1 heure
service 2 : 90€ pour 1 heure
Dans ce cas tu pourrais faire ta facture en 2 étapes
2 heures pour le service 1 à 70 euros soit 1*2*70 140€
puis sur la prov généré
1 heures pour le service 2 à 90€ 1*1*90€ soit 90€
Je n'ai pas vu de bug sur ce fonctionnement.
Si tu ne choisi rien il prendra ton taux horaire dans ce cas la quantité risque de te poser problème.

Cheers

**Comment by ksar-ksar** [comment]
Hello,

The answer of @lmag is the good one I think
