### ISSUE TITLE
BUG View Product STOCK  With Batch management and Accept negative Stock value

### ISSUE THREAD

**Issue by eric97410** [Dolibarr/dolibarr#13765]
# Instructions
# Bug
IN view /product/stock/product.php?id=x When we have batch management and accept negative stock.
If you have compensation mouvements between two different batch number , the real stock are 0 , but the real view of stock are wrong 

proposition of correction in joint file product.php

## Environment
- **Version**: [11.0.3]
- **OS**: [All]
- **Web server**: [*All]
- **PHP**: [All]
- **Database**: [*Database type and version*]
- **URL(s)**: /product/stock/product.php?id=x

[product.zip](https://github.com/Dolibarr/dolibarr/files/4546200/product.zip)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

Could you check with V13 ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
