### ISSUE TITLE
MO cannot be deleted

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#13766]
# Bug
When trying to delete a MO it results in an error

```
Table 'wus_erp_production.llx_mrp_mo_extrafields' doesn't exist
```

**Comment by atm-maxime** [comment]
Hi !
I just tried on a 11.0.4 and develop version and I don't get this error. Can you refresh your install and tell us what version you're on ?

**Comment by cfoellmann** [comment]
I am on the develop branch for some time.
Already ran „install/„ multiple times.

Maybe the table creation in the sql update is buggy?
I will have a look tomorrow

**Comment by cfoellmann** [comment]
In my install I had this table `llx_mrp_myobject_extrafields` when I rename this one to `llx_mrp_mo_extrafields` it works.
Maybe I initialized the sql in a bad state of the `develop` branch
