### ISSUE TITLE
Bug Dolibarr don't include jquery flotcharts lib

### ISSUE THREAD

**Issue by indelog** [Dolibarr/dolibarr#13773]
Dolibarr

# Bug
It seem the class `Dolgraph` can draw charts with use [jquery flot](https://www.flotcharts.org/). But when we try to enable it by setting the global conf variable `MAIN_JS_GRAPH` to `jflot` no more graphics appear on the pages which displaying one.

In the hader genration of the page, Dolibarr try to include script for this location : 

* `doldev/includes/jquery/plugins/flot/jquery.flot.js`
* `doldev/includes/jquery/plugins/flot/jquery.flot.pie.js`
* `doldev/includes/jquery/plugins/flot/jquery.flot.stack.js`

but this files are not present.

The library not seem present in `composer.json` file.

## Environment
- **Version**: developement installed with git clone

**Comment by ATM-Nicolas** [comment]
Can you please specify more precisely the dolibarr version in which you have encountered this problem ?

**Comment by indelog** [comment]
I re-try it with the version 13.0 of Dolibarr (actually in beta) and i have the same problem.

I get this message from the javascript console : 

```
Uncaught TypeError: $.plot is not a function
```
I searched for the js plugin file in the code and i not found anything. For testing purpose i got the jflot lib with `npm install flot` (it seem has no other mean to get distribuable js) and i included it in the html. It work but some chart type like pie does not work (i got a black square rather the chart).

The use of Jflot is it deprecated in Dolibarr ?

**Comment by l00ptr** [comment]
I have the same problem after upgragin from Dolibarr 11 to 13.
