### ISSUE TITLE
Variants : No Permissions

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#13770]
Adding, modifying or removing anything from `variants` can a bad influence on working with the ERP.
There need to be permissions controlling access for users.

**Comment by ATM-Nicolas** [comment]
Can you please specify the dolibarr version in which you have encountered this problem ?

**Comment by cfoellmann** [comment]
current `develop` branch - 13.0-beta

**Comment by edupulpillo** [comment]
Seems that the module variants do not have implemented the permissions system yet.

**Comment by ksar-ksar** [comment]
For me it is a feature request not a Bug

**Comment by edupulpillo** [comment]
Is any improvement present about this topic in version 15.0.x ?

**Comment by cfoellmann** [comment]
@edupulpillo nothing so far.
I havent had the time for it since we dropped usage of variants I might not have any way to get this in anytime soon
