### ISSUE TITLE
Deletion of users fails because of MySQL foreign key constraint

### ISSUE THREAD

**Issue by buesma** [Dolibarr/dolibarr#13771]
# Bug
I tried to delete some old users. This worked for most of them, but some produced the error "User cannot be deleted. Maybe it is associated to Dolibarr entities.". On the cards of the users no associations were visible. 

So I looked into the dolibarr.log and found following error: 
`DoliDBMysqli::query SQL Error message: DB_ERROR_CHILD_EXISTS Cannot delete or update a parent row: a foreign key constraint fails ('dolibarr'.'llx_socpeople', CONSTRAINT 'fk_socpeople_fk_user_creat') REFERENCES 'llx_user' ('rowid'))`

This appears to be the same problem for all users which created one or more new contacts. The ids of the users which can not be delete were found in `llx_socpeople` under `fk_user_creat`. The user itself does not have a contact it corresponds to.

The properties of the foreign key in MySQL were (as defined in `htdocs/install/mysql/tables/llx_socpeople.key.sql`):
`
Foreign Key: fk_socpeople_user_creat_user_rowid
Definition:
Target llx_user (fk_user_creat → rowid) 
On Update RESTRICT 
On Delete RESTRICT`

I fixed the issue for us by deleting this constraint and replacing it by a new one with:
`ALTER TABLE dolibarr.llx_socpeople 
add Constraint fk_socpeople_user_creat_user_rowid 
foreign key (fk_user_creat) references llx_user (rowid)
ON DELETE set null;`

This approach is similar to the deletion of a user which was created from a contact. (Compare htdocs/user/class/user.class.php l. 1068)

## Environment
- **Version**: 10.0.4
- **OS**: Debian 8.11
- **Web server**: Apache 2.4.10
- **PHP**: 7.2.25-1
- **Database**: MySQL 5.7.29
- **URL(s)**: /user/card.php

## Expected and actual behavior
- Expected: User is deleted
- Actual: Error in Dolibarr GUI "User cannot be deleted. Maybe it is associated to Dolibarr entities." and error in dolibarr.log (see above)

## Steps to reproduce the behavior
- Manually create a new user
- Log in as this new user
- Create a contact with this new user
- Log out 
- Try to delete the new user

**Comment by ksar-ksar** [comment]
Hello,

I don't see the issue, if the user has created something, you can delete it.
This is normal.

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.

**Comment by chroniclesoft** [comment]
I use dolibarr very 13.2, and I experience this same issue. Its frustrating. 

Another one is "Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.". This shows when you intend to update an account. The error is linked with vcard
