### ISSUE TITLE
What happened to "build_class_from_table.php" ?

### ISSUE THREAD

**Issue by nervo** [Dolibarr/dolibarr#13784]
Wiki is talking about a `build_class_from_table.php` class to generate a php class from a sql table located in `dev/skeletons` (https://wiki.dolibarr.org/index.php/D%C3%A9veloppement_module#G.C3.A9n.C3.A9rer_la_classe_PHP_DAO_d.27acc.C3.A8s_aux_tables)

But `dev/skeletons` only contains a `README.md` claiming that
```
Files and tools were moved into htdocs/modulebuilder/template
```

Ok, so, `htdocs/modulebuilder/template` does not contain any `build_class_from_table.php` and, looking in git history, it was removed in this "look and feel" (?!?) commit: https://github.com/Dolibarr/dolibarr/commit/be439f62522815c29e3f3e8e006508d98a02057d

Do i miss something ?

**Comment by eldy** [comment]
The wiki section https://wiki.dolibarr.org/index.php?title=D%C3%A9veloppement_module#G.C3.A9n.C3.A9rer_la_classe_PHP_DAO_d.27acc.C3.A8s_aux_tables has been updated.
