### ISSUE TITLE
Translation of services not fully applied in bill when PDF generated through API

### ISSUE THREAD

**Issue by ro78** [Dolibarr/dolibarr#13783]
# Bug
I have multiple services registered in Dolibarr in French, with English (US) translations for few customers speaking English. But when the PDF file of bill is generated from the API, only the description is in English, not label which remains in French.

## Environment
- **Version**: 11.0.3
- **OS**: Debian 10.3
- **Web server**: Apache 2.4.38
- **PHP**: PHP 7.3.14
- **Database**: MariaDB 10.3.22
- **URL(s)**: /documents/builddoc

## Expected and actual behavior
Actual behavior: French label of service and English description of service
Expected: English label of service AND English description of service

## Steps to reproduce the behavior
Configure a service in French.
Add English (US) translation.
Create a new customer with EN(US) default language.
Create a bill for this customer, add this service to bill and create the PDF with API /documents/builddoc API (translation is well applied if bill is created from the GUI).

PHP call: CallDOAPI("PUT", "/documents/builddoc", json_encode(array("modulepart"=>"invoice", "original_file"=>$facnumber."/".$facnumber.".pdf", "doctemplate"=>"crabe", "langcode"=>"en_US")));

The "langcode" parameter is well taken into account because if I use "fr_FR", the PDF is fully in French, and if I revert it to "en_US", it's almost in English except service label.

Screenshot of translated service & result in bill attached.

<img width="566" alt="2020-05-01_132017" src="https://user-images.githubusercontent.com/3236640/80802258-2d135200-8baf-11ea-81d7-a45debc35267.png">
<img width="532" alt="2020-05-01_131901" src="https://user-images.githubusercontent.com/3236640/80802259-2dabe880-8baf-11ea-81d4-07262f6db81d.png">

**Comment by ro78** [comment]
Nobody?

**Comment by eldy** [comment]
I tested with 12.0.1 and i do no experience the trouble

**Comment by ro78** [comment]
I confirm I still have the issue on 12.0.1. Can it be related to the fact that I've upgraded, months after months, from 4.0.1 up to 12.0.1 ?
Can we be in contact to show you how easily I can reproduce in remote session or somehow?

Here is how I reproduce quickly with 12.0.1:
- create a draft invoice with services that have both FR and EN translation for a EN customer
- generate the PDF from web interface: OK
- generate the PDF from PHP class (see code below): French description instead of English

```
$facnumber="(PROV645)";
CallDOAPI("PUT", "/documents/builddoc", json_encode(array("modulepart"=>"invoice", "original_file"=>$facnumber."/".$facnumber.".pdf", "doctemplate"=>"crabe", "langcode"=>"en_US")));
```

**Comment by ksar-ksar** [comment]
Hi,

Could you check with V13 ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.

**Comment by ro78** [comment]
Not fixed :(

**Comment by ro78** [comment]
I'm available (in English or French) for reproduction on my system.

**Comment by ro78** [comment]
I'm available (in English or French) for reproduction on my system.

**Comment by atm-maxime** [comment]
Hi @ro78 !
I just tried to reproduce with a 13.0.5 version and it works fine for me. Using the API with en_US or en_GB, the invoice generated file displays the right translations of my product. What is the answer of your API call ? Did you try on a fresh Dolibarr install with no other module that might cause the trouble ?

**Comment by ro78** [comment]
@atm-maxime I'm now on 16.0.2 and I still have this issue.

I still issue this API call:
`CallDOAPI("PUT", "/documents/builddoc", json_encode(array("modulepart"=>"invoice", "original_file"=>$facnumber."/".$facnumber.".pdf", "doctemplate"=>"crabe", "langcode"=>"en_US")));`

All the PDF generated is in English, except product name. If I reopen this invoice in the web interface, select the same model (crabe) and English (US) language, then the product name switches to English. It's really only related to API.

I have no special modules enabled, and I'm still available (in English or French) for a reproduction in live on my system.
