### ISSUE TITLE
Reminder on event agenda missing and email not sent

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#13791]
# Bug
[*Missing Reminder fields and emails sent on event agenda. (Let me know if I have to split these 2 issues)*]

## Environment

    Version: [11.0.3] and [12.x]
    OS: [Linux]
    Web server: [Apache/2.2.34 (Unix)]
    PHP: [7.4.2]
    Database: [MYSqli 5.7.26]
    URL(s): [.../comm/action/index.php?idmenu=7&mainmenu=agenda&leftmenu=]

## Expected and actual behavior
[*After email configuration and schedule jobs fully functional, reminder agenda configuration done, as stated in this latest config menu : Enable event reminder by emails (### remind option/delay can be defined on each event). Note: Module Scheduled jobs must be enabled and correctly setup to have reminder sent at the correct frequency., the remind OptionDelay is not available on any event action. Also after creating 3 events and running the schedule jobs either manually or thru a contab, there is no email reminders sent. What is expected : be able to set reminders to any event and be able to receive email alerts*]

## Steps to reproduce the behavior
[*
- Configure email, 

- configure Schedule Jobs module, 

- configure agenda module, 

- create 3 events, try to find reminder options.

- Run Schedule jobs manually*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*
<img width="1192" alt="Capture d'écran 2020-05-02 17 16 24" src="https://user-images.githubusercontent.com/57623859/80869344-3a5c3980-8ca0-11ea-8f92-fc03842fbc07.png">
<img width="1178" alt="Capture d'écran 2020-05-02 17 30 43" src="https://user-images.githubusercontent.com/57623859/80869346-3defc080-8ca0-11ea-9b24-f91d6a9fdfc7.png">
<img width="1174" alt="Capture d'écran 2020-05-02 17 30 54" src="https://user-images.githubusercontent.com/57623859/80869349-40eab100-8ca0-11ea-96c3-b4da0264ea7f.png">
<img width="1171" alt="Capture d'écran 2020-05-02 17 31 31" src="https://user-images.githubusercontent.com/57623859/80869350-434d0b00-8ca0-11ea-9b4d-15576628cc4c.png">
<img width="1364" alt="Capture d'écran 2020-05-02 17 33 11" src="https://user-images.githubusercontent.com/57623859/80869353-47792880-8ca0-11ea-9c84-e06b35ed275d.png">
<img width="1160" alt="Capture d'écran 2020-05-02 17 33 44" src="https://user-images.githubusercontent.com/57623859/80869355-48aa5580-8ca0-11ea-8423-0b2d54641f66.png">

*]

**Comment by atm-maxime** [comment]
Hi ! Thanks for contributing. See #11031 which is the same issue I think. If so, please close yours and we'll keep one issue to track the subject.

**Comment by josett225** [comment]
Hi @atm-maxime,

I understood what I did, MAIN_FEATURES_LEVEL was at level 2, moving it to 0 removes the reminder menu in agenda module. However I still get the Send agenda reminders by emails in the schedule jobs card. Does it means it is supposed to generate something or it doesn't work either?

**Comment by atm-maxime** [comment]
If you read the issue I pointed out, it says that this feature is not yet complete, that's why it's in feature level 2. And the emails are the missing part.

**Comment by josett225** [comment]
Ok thanks I closed my request linked with #11031
