### ISSUE TITLE
Unable to save values in Notifications module config

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#13792]
# Bug
[*Save values does not work on notification module configuration*]

## Environment
Version: [12.x : last version]
OS: [Linux]
Web server: [Apache/2.2.34 (Unix)]
PHP: [7.4.2]
Database: [MYSqli 5.7.26]
URL(s): [.../admin/notification.php]

## Expected and actual behavior
[*Keep Fields after saving*]

## Steps to reproduce the behavior
[*feed any field on Notification Menu then save*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*
<img width="1170" alt="Capture d'écran 2020-05-02 17 40 09" src="https://user-images.githubusercontent.com/57623859/80870006-fc611480-8ca3-11ea-8ecc-0ff5b3843316.png">
<img width="1157" alt="Capture d'écran 2020-05-02 17 40 50" src="https://user-images.githubusercontent.com/57623859/80870012-0420b900-8ca4-11ea-9a32-eb0876d2718b.png">

*]

**Comment by eldy** [comment]
Fixed in develop
