### ISSUE TITLE
Hey everyone dolibarr forum #android

### ISSUE THREAD

**Issue by RDHimni** [Dolibarr/dolibarr#13800]
[Dolibarr] i have devloped an application android for dolibarr .
so my application is to handling stock in my dolibarr using REST API.
issue is : my application not want connet to rest api in android devices that andoid version more to 7.0.0

thats my gradle:app :
apply plugin: 'com.android.application’

android {
** compileSdkVersion 29**
** buildToolsVersion “29.0.3”**
** defaultConfig {**
** applicationId “com.example.logine”**
** minSdkVersion 15**
** targetSdkVersion 29**
** versionCode 1**
** versionName “1.0”**
** testInstrumentationRunner “androidx.test.runner.AndroidJUnitRunner”**
** }**
** buildTypes {**
** release {**
** minifyEnabled false**
** proguardFiles getDefaultProguardFile(‘proguard-android-optimize.txt’), ‘proguard-rules.pro’**
** }**
** }**
}

dependencies {
** implementation fileTree(dir: ‘libs’, include: [’*.jar’])**
** implementation ‘androidx.appcompat:appcompat:1.1.0’**
** implementation ‘androidx.constraintlayout:constraintlayout:1.1.3’**
** implementation ‘com.android.volley:volley:1.1.1’**
** testImplementation ‘junit:junit:4.12’**
** androidTestImplementation ‘androidx.test.ext:junit:1.1.1’**
** androidTestImplementation ‘androidx.test.espresso:espresso-core:3.2.0’**
}

**Comment by eldy** [comment]
This does not seems to be a bug related to dolibarr but to an android development.
Recent android have a security that does not allow external acces if url is not a https.
Does your dolibarr is hosted on a server with a https link ? Does the certificate is valid ?

**Comment by RDHimni** [comment]
@eldy thank you for your reply, Yes my dolibarr hosted on a server with an http link.

**Comment by atm-maxime** [comment]
So as @eldy said, this most likely comes from your webserver. Android needs it to be on https and not http.
