### ISSUE TITLE
Tax remains 21% when entering product prices but vendor tax is 0%

### ISSUE THREAD

**Issue by jongerli** [Dolibarr/dolibarr#13802]
# Bug
Purchase product price tax issue

## Environment
- **Version**: 11.0.2 11.0.3
- **OS**: Server 2012
- **Web server**: IIS 
- **PHP**: 7.2
- **Database**: MySQL

## Expected and actual behavior
When entering a purchase price for a vendor abroad one expects to to see the product TAX field remains 0% because this is setup for the vendor. But the local high tax-rate is always displayed in the field.

## Steps to reproduce the behavior
Enter a (new) purchase price for a product, the tax-field is filled with the high local tax 21 %. Choosing the supplier, the VAT remains at 21% while this should be 0% VAT for a vendor abroad. While it does say: "VAT rate (for this supplier / this product)"

**Comment by eldy** [comment]
Can you provide a screenshot to know about which edit page your are speaking about

**Comment by jongerli** [comment]
[issue-13802.pdf](https://github.com/Dolibarr/dolibarr/files/4591869/issue-13802.pdf)
Vendor - Purchase prices - add new, then tax is 21% should be 0

**Comment by eldy** [comment]
The tax suggested by default is the tax if the seller sell in its country. Its own vat tax rate. So 21.
I think it is later, when you will use the price for a purchase order or a supplier invoice that the rule on countries will be checked and the vat will be switched automatically to 0. But this must be confirmed.

**Comment by ksar-ksar** [comment]
Hello,

Have you checked the above statement ?
Also did you try the upgrade to newer versions of Dolibarr ?
