### ISSUE TITLE
Docker: Your PHP installation does not support GD graphical functions.

### ISSUE THREAD

**Issue by mcastillof** [Dolibarr/dolibarr#13807]
# Bug
While using dolibarr/build/docker files to run Dolibarr, there is no support for GD in PHP, due to missing packages in the apt-get line in the Dockerfile.

The following message was shown while the image was built and also while the container was started:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/gd.so (libpng16.so.16: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/gd.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

## Environment
- **Version**: release 11.0.3
- **OS**: Host system is Debian testing
- **Web server**: apache (php:7.2-apache, dolibarr/build/docker/Dockerfile)
- **PHP**:  php:7.2-apache (dolibarr/build/docker/Dockerfile) 
- **Database**: mariadb:latest (dolibarr/build/docker/mariadb/Dockerfile) 
- **URL(s)**: https://d.coders.cl/install/check.php

## Expected and actual behavior

The expected behavior was the GD test in the "Prerequisites check" in the installation to be OK. It instead shows "Your PHP installation does not support GD graphical functions. No graphs will be available."

## Steps to reproduce the behavior
You can reproduce the behavior by following the steps in dolibarr/build/docker/README.md, that is:
```
export HOST_USER_ID=$(id -u)
cd build/docker
docker-compose up
```
And then, you should go to the URL of the service created, and click in "next step", where you will se the checks.

## Attached files
Log while building the image when running docker-compose up: [build.log](https://github.com/Dolibarr/dolibarr/files/4575503/build.log)

## Fix
To solve the problem, I had to change some packages in dolibarr/build/docker/Dockerfile:
```
diff -u dolibarr/build/docker/Dockerfile new/Dockerfile 
--- dolibarr/build/docker/Dockerfile	2020-05-04 10:45:24.877530658 -0400
+++ new/Dockerfile	2020-05-04 11:26:01.158206184 -0400
@@ -3,7 +3,7 @@
 ENV HOST_USER_ID 33
 ENV PHP_INI_DATE_TIMEZONE 'UTC'
 
-RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libldap2-dev zlib1g-dev libicu-dev g++\
+RUN apt-get update && apt-get install -y libpng16-16 libpng-dev libjpeg62-turbo libjpeg62-turbo-dev libldap2-dev zlib1g-dev libicu-dev g++\
 	&& rm -rf /var/lib/apt/lists/* \
 	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
 	&& docker-php-ext-install gd \
@@ -13,7 +13,7 @@
         && docker-php-ext-install calendar \
         && docker-php-ext-configure intl \
         && docker-php-ext-install intl \
-        && apt-get autoremove --purge -y libjpeg-dev libldap2-dev zlib1g-dev libicu-dev g++
+        && apt-get autoremove --purge -y libpng-dev libjpeg62-turbo-dev libldap2-dev zlib1g-dev libicu-dev g++
 
 RUN mkdir /var/documents
 RUN chown www-data /var/documents
```

**Comment by bsene** [comment]
Hello,

I've add a PR [here](https://github.com/Dolibarr/dolibarr/pull/13941) 
Thanks to @mcastillof for the detailed informations.
