### ISSUE TITLE
Invoice Status not changed after applying credit note - Purchase Invoice

### ISSUE THREAD

**Issue by jrgonzalezrios** [Dolibarr/dolibarr#13809]
#Bug
Applying a Credit Note to an Unpaid invoice leaves the Invoice as "started" and if the total amount is zero 0.00 it should set the invoice as "paid".

## Environment
- **Version**: 11.0.3
- **OS**: Ubuntu
- **Web server**: Nginx
- **PHP**: 7.2
- **Database**: Mysql
- **URL(s)**: /fourn/facture/card.php

## Expected and actual behavior
After paying the total amount of an invoice with a credit note, it should set it to "paid".

## Steps to reproduce the behavior
Create a Purchase order. Create an invoice from the Purchase Order. Create a Credit note and set it as "Credit available". Use this credit in the unpaid invoice. Apply it, (to reproduce this bug, it should cover, exactly the total amount and leave it in a zero balance)

**Comment by jrgonzalezrios** [comment]
Checking the source code I found the reason:

https://github.com/Dolibarr/dolibarr/blob/4c04ace9d8305da6e4bdca000ae8d333f2ba5217/htdocs/core/tpl/object_discounts.tpl.php#L55

Could you explain the reason for this? What if I need to apply an absolute discount from the Vendor, while adding payments?

Scenario: Validated Invoice
The total amount is $1,000
I as a customer send a payment to the vendor of $100: the invoice remains as "unpaid" with a balance of $900.
By this time, I arranged a discount with my vendor, because I found some damages in the product. At this point I could apply an Absolute discount, and keep paying the remaining.

**Comment by jrgonzalezrios** [comment]
Hi! this behavior remains in latest version 11.0.4. After applying a credit not to an unpaid Purchase Invoice: if the balance is zero, it should set Invoice automatically as Paid.

**Comment by atm-maxime** [comment]
It's not a bug I think, only a workflow that hasn't been developed. Same on customer invoice. Same when creating a payment on an invoice before the option was added as a checkbox at bottom of payment creation form.

**Comment by ksar-ksar** [comment]
Hello,

Could you try with newer versions ?
