### ISSUE TITLE
Invoice reference not able in mail model

### ISSUE THREAD

**Issue by nagoz** [Dolibarr/dolibarr#13826]
When I want to personalize a mail model, I can't find the invoice reference in the variables.

Is it possible to add the variable

**Comment by atm-maxime** [comment]
Hi. Did you try __REF__ ?

**Comment by atm-maxime** [comment]
Hi !
Did you ask the question on Dolibarr forums ?
The variable is __REF__

**Comment by nagoz** [comment]
Hi !
No I don't ask the forum. I hadn't find my answer on the forum.
Thanks for your answer, it works.
Sorry for the Feature request, I will send message in the future on the forum.
Regards
