### ISSUE TITLE
add an SQL ORDER BY clause for exports

### ISSUE THREAD

**Issue by anotherjo** [Dolibarr/dolibarr#13839]
# Feature Request
'Order By' Clause addition on exports from the 'Tools' menu

## Use case
when performing exports the user is given the choice to :
- select fields
- apply filters on those fields
- give those fields the expected order 
so he can in the end generate an output (csv, excel,..) almost ready to use.
Also the exports shows for authorized users the exact SQL command ; nevertherless this SQL command cannot be tuned or reused except directly from SQL server. 

## Suggested implementation
in order to give the end user a fully ready to use output, it should be relevant to allow during  the different steps the possibility to sort data in the needed order.

## Suggested steps
during 'step 4' users should have available an additionnal 'sorted by' option (together with 'position' one) which should be available for each field ; it should be set by default to 'not sorted' with the option to chose 'asc' or 'desc' in the drop down list

**Comment by dpriskorn** [comment]
Sounds like a good idea. Would you like to try coding it?

**Comment by anotherjo** [comment]
> Sounds like a good idea. Would you like to try coding it?

If ones tell me how I could try, why not. I've basic skill in php, do not know if this would be enough. please let me know where I could find the 'guide' to proceed with this test. Thanks
