### ISSUE TITLE
Bug: No value on U.P. and U.P(inc Tax) when input the value from U.P (currency)

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13835]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
No value on U.P. and U.P(inc Tax) when input the value from U.P (currency). the rest are working well such as total value.

## Environment
- **Version**: 11.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.3
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.4.11-MariaDB
- **URL(s)**: /boconen/htdocs/supplier_proposal/card.php?id=63

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="1017" alt="Capture" src="https://user-images.githubusercontent.com/52134143/81208780-29922780-9002-11ea-8f9a-3ab9383aaec2.PNG">

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
