### ISSUE TITLE
Bug: Unit not showing up in the BOM

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13831]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 11.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.3
- **PHP**: apache2handler 7.4.3
- **Database**: MySQL or MariaDB 5.5.5-10.4.11-MariaDB
- **URL(s)**: /boconen/htdocs/bom/bom_card.php?id=1

## Expected and actual behavior
[*Verbose description*]
Unit should show in the unit column

## Steps to reproduce the behavior
[*Verbose description*]
add product into the BOM will show the error

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="802" alt="Capture" src="https://user-images.githubusercontent.com/52134143/81188466-ea56dd00-8fe7-11ea-8416-34a153ad108f.PNG">

**Comment by atm-maxime** [comment]
I checked it out and issue comes from the fact that the unit is not stored on the BOM line, but unit selection is available while adding line.
I think unit should not be selected on the BOM line, and the unit of the product should be shown. What do you think ?

**Comment by asolslk** [comment]
i think it can select from the product and display here which seem better and easy to understand

**Comment by dpriskorn** [comment]
Is this also a problem in v12?

**Comment by RomainDeschamps** [comment]
Hello !

Yes, still here :  

![image](https://user-images.githubusercontent.com/11922840/89630819-2a0bba00-d8a0-11ea-95a1-9a21daf8b6cd.png)

**Comment by ksar-ksar** [comment]
Hi,

Could you try the fix above or the upgrade to last V13.0.2 or V12.0.5 ?
