### ISSUE TITLE
Bug: Bank cannot be change on the Supplier proposal after generated the PROV

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13834]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
When creating the supplier proposal in the system, bank cannot be change on the Supplier proposal after generated the PROV.

## Environment
- **Version**: 11.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.3
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.4.11-MariaDB
- **URL(s)**: /boconen/htdocs/supplier_proposal/card.php?id=62

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="511" alt="Capture" src="https://user-images.githubusercontent.com/52134143/81202539-5726a300-8ff9-11ea-96ba-d71062ea99a2.PNG">

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by ksar-ksar** [comment]
Hi,

Did you try the upgrade to V12 or V13 ?
