### ISSUE TITLE
COMMERCIAL PROPOSITION does not work with PostgreSQL

### ISSUE THREAD

**Issue by devzhr** [Dolibarr/dolibarr#13830]
# Bug
[* if I am of an intervention and I would like to create a commercial proposal. *]

## Environment
- **Version**: [*9.0.4*]
- **OS**: [*Linux*]
- **Web server**: [*nginx/1.16.1*]
- **PHP**: [*7.4.1*]
- **Database**: [*PostgreSQL 12.1 (Debian 12.1-1.pgdg90+1)*]
- **URL(s)**: [*http://dolibarr.local/fichinter/card.php?id=20*]

## Expected and actual behavior
[*Requête dernier accès en base en erreur: INSERT INTO llx_element_element (fk_source, sourcetype, fk_target, targettype) VALUES (16, 'fichinter', 21, 'propal')
Code retour dernier accès en base en erreur: DB_ERROR_RECORD_ALREADY_EXISTS
Information sur le dernier accès en base en erreur: ERROR: 23505: duplicate key value violates unique constraint "idx_element_element_idx1"\nDETAIL: Key (fk_source, sourcetype, fk_target, targettype)=(16, fichinter, 21, propal) already exists.\nSCHEMA NAME: public\nTABLE NAME: llx_element_element\nCONSTRAINT NAME: idx_element_element_idx1\nLOCATION: _bt_check_unique, nbtinsert.c:570*]

**Comment by ksar-ksar** [comment]
Hello,

Have you tried with newer versions of Dolibarr ?

Also Dolibarr V9 is not compatible with PHP 7.4.
It is 7.3 maximum : https://wiki.dolibarr.org/index.php?title=Releases
