### ISSUE TITLE
Fixed - Better format of number on Doli Graph

### ISSUE THREAD

**Issue by dolivn** [Dolibarr/dolibarr#13837]
# Bug 
* Y-axis and tooltip have number's format is not good.
Example: 
1000000000 is a not good format
After fixing: It will be 1,000,000,000. This format must be better

## Environment
- **Version**: 11.0.4

## How we fix:
/**
 *	\file       htdocs/core/class/dolgraph.class.php
 *  \ingroup    core
 *	\brief      File for class to generate graph
 */

line 1072:
bug:  showTooltip_'.$tag.'(item.pageX, item.pageY, item.series.label + "<br>" + z + " => " + y);
fixed: showTooltip_'.$tag.'(item.pageX, item.pageY, item.series.label + "<br>" + z + " => " + Intl.NumberFormat().format(y));

line 1114:
bug:  $this->stringtoshow .= ', yaxis: { min: '.$this->MinValue.', max: '.($this->MaxValue).' }'."\n";
fixed: $this->stringtoshow .= ', yaxis: { min: '.$this->MinValue.', max: '.($this->MaxValue).', tickFormatter: function (val, axis) { return Intl.NumberFormat().format(val)} }'."\n";

**Comment by caoleviettien** [comment]
@dolivn - checked. It's worked !

**Comment by dolivn** [comment]
![image](https://user-images.githubusercontent.com/38345243/81251861-8a475180-904e-11ea-9476-2aa815a846d2.png)
