### ISSUE TITLE
Suggest: change the ticket message to HTML Input

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13833]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Change the message to HTML text field will be much more easy on capturing the input and details.

## Environment
- **Version**: 11.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.3
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.4.11-MariaDB
- **URL(s)**: /boconen/htdocs/ticket/card.php?action=create&idmenu=21620&mainmenu=ticket&leftmenu=

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="884" alt="Capture" src="https://user-images.githubusercontent.com/52134143/81200963-3fe6b600-8ff7-11ea-9365-4eafbcc66407.PNG">

**Comment by atm-maxime** [comment]
Hi !
Did you activate the wysiwyg module ?

**Comment by asolslk** [comment]
ah! saw it. Thank you sir
