### ISSUE TITLE
Table llx_c_ziptown is empty - No automated data entry for Postal Code / City

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#13849]
# Bug
I am not sure it is a bug or a missing feature... Table llx_c_ziptown is empty. I was expecting the field postal code and city in the third party interface to be filled semi automatically... The postal code field being read and picked from the llx_c_ziptown table, and the city field being populated from the choice made in the previous field. But that does not occur.   

## Environment
- **Version**: 11.0.1 (But that was the same in prior versions)
- **OS**: Ubuntu Server 18.04 LTS
- **Web server**: Apache2
- **PHP**: PHP 7.2
- **Database**: MySQL 5.7
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
 I was expecting the field postal code and city in the third party interface to be filled semi automatically... The postal code field being read and picked from the llx_c_ziptown table, and the city field being populated from the choice made in the previous field. But that does not occur.   

## Steps to reproduce the behavior
Choose your country in the third party creation page, go back to the postal code field, and nothing appears.

**Comment by matDOTviguier** [comment]
I confirm the table is empty in at least one installation from scratch in 12.0
