### ISSUE TITLE
Bug:  Products / Services turnover quarterly before tax	is wrong

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13846]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Products / Services turnover quarterly before tax	is wrong when there is progressive payment to the same invoice, the amount taken in Dolibarr is the product amount, which shall be the amount that payment are made / receive to the product.

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /product/index.php?mainmenu=products&leftmenu=

## Expected and actual behavior
[*Verbose description*]
should display the data in the payment amount made / received instead of the product amount.

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="451" alt="Capture" src="https://user-images.githubusercontent.com/52134143/81378327-b1c71880-9139-11ea-91e6-118d13d7ad90.PNG">
<img width="446" alt="Capture" src="https://user-images.githubusercontent.com/52134143/81378523-04a0d000-913a-11ea-830c-621791db4ad3.PNG">

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by asolslk** [comment]
Yea, still showing in v12
