### ISSUE TITLE
v11.x - HTML Char in PDF Expense Report

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#13859]
# Bug
When we download the PDF for a expense report, we have a bug in the status. We get an HTML char.

## Environment
- **Version**: 11.0.4
- **OS**: Debian 10.3
- **Web server**: Nginx 1.17.9
- **PHP**: PHP 7.3.14
- **Database**: PostgreSQL 11.7
- **URL(s)**: /compta/bank/account_statement_document.php?account=1&num=202002

## Expected and actual behavior
Expected : "Approuvé"
Actual : "Approuv&amp;eacute;"

## Steps to reproduce the behavior
Create a expense report
Submit it
Accept it
You have the problem in french

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[NF0001-2004.pdf](https://github.com/Dolibarr/dolibarr/files/4604171/NF0001-2004.pdf)
File has been clean before upload

**Comment by atm-maxime** [comment]
Seems to be a duplicate of #13611 ?
Should have been fixed in 11.0.4. Can you check ?

**Comment by ludovicandrieux** [comment]
You are right.
It was generated by a 11.0.3.
With a refresh, it's clean.
Thanks
