### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by nid-ibrahim** [Dolibarr/dolibarr#13856]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 11.0.3
- **OS**: Darwin
- **Web server**: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.4.2 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.24.0
- **PHP**: apache2handler 7.4.2
- **Database**:  5.7.26
- **URL(s)**: /CONTA/GRAFIK_MA/index.php?mainmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
I think you forgot to add a description of the issue you're facing....

**Comment by eldy** [comment]
Closed. No description of bug.
