### ISSUE TITLE
Canadian Tax/Accounting Help

### ISSUE THREAD

**Issue by mandeepmavi** [Dolibarr/dolibarr#13851]
Version 11.0.3

Hi Friends, I was trying to set up Accounting/Tax for my store in Alberta, Canada.
I had one chart of account, But now using Eldy's https://github.com/Dolibarr/dolibarr/pull/13613

Need help with setup. We have 6 kind of different Tax rates.
1, GST -> 5%
2, GST + PST -> 5% + 6%
3, GST + PST -> 5% + 7%
4, HST -> 13%
5, HST -> 15%
6, GST + QST -> 5% + 9.975%

I did this following https://wiki.dolibarr.org/index.php/VAT_calculation_and_rounding_rules#For_Canada

I selected accnunting accounts in VAT setup, But unable to get Collected tax report.

But while prossecing order I have to select Tax mannualy, i it possible that Tax change with buyers shipping Address.

What is difference between Vat account and Tax Account under accounting setup.

**Comment by atm-maxime** [comment]
Hi @mandeepmavi 
Sorry you didn't get an answer sooner and I hope you found your answer since then. If you seek help to setup your Dolibarr, the right place is on forums or to contact a Dolibarr expert.
Here on GitHub we deal with issues and feature requests.
