### ISSUE TITLE
Add new currency

### ISSUE THREAD

**Issue by seckt0r** [Dolibarr/dolibarr#13853]
# Feature Request
Since the list of available currencies is not complete (missing Angola Kwanza - AOA, at least), the option to manually include a custom currency would be helpful.

**Comment by atm-maxime** [comment]
Hi ! I think you can add a currency directly in the currency dictionary. On top of the list there's a form to add a currency. Does this work for you ?

**Comment by seckt0r** [comment]
Yes, it did work. I forgot to check the dictionary option.
Thanks!
