### ISSUE TITLE
v11.x - Name folder cut in dol_compress_dir

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#13858]
# Bug
[*Short description*]
When plugin use the dol_compress_dir with relativePath, this function cut the first char of the first folder 
The problem is here : https://github.com/Dolibarr/dolibarr/blob/cd4c19f363f24f42692ab3dc3d1c82df8daf126a/htdocs/core/lib/files.lib.php#L2167
It's shound not have a "+1" at the end of the line

## Environment
- **Version**: 11.0.4
- **OS**: Debian 10.3
- **Web server**: Nginx 1.17.9
- **PHP**: PHP 7.3.14
- **Database**: PostgreSQL 11.7
- **URL(s)**: /compta/bank/account_statement_document.php?account=1&num=202002

## Expected and actual behavior
For exemple, a plugin wants to compress the folder /home/test/exemple/
When i open the zip, i get "xemple" for the first folder

## Steps to reproduce the behavior
Create a folder /home/test/exemple/
Put a file in this folder
Call dol_compress_dir('/home/test/exemple/','/home/test/a.zip')
Open zip, you will obtain a folder "xemple" and your file inside this cut folder

**Comment by atm-maxime** [comment]
Hi !
I think that's because your first parameter should not end by "/". The function recursively goes through all subdirectories and files, so when it does the substring on "PATH/file" with PATH + 1 that's to start after the /. So PATH should not finish by the /.

**Comment by ludovicandrieux** [comment]
Hi,
I can confirm that remove the "/" at the end changes nothing.

**Comment by atm-maxime** [comment]
I tried again, here's what I've got :
![image](https://user-images.githubusercontent.com/2097773/83974424-80cf3480-a8ed-11ea-8808-c8ade692762c.png)
![image](https://user-images.githubusercontent.com/2097773/83974444-9cd2d600-a8ed-11ea-8519-d70ef177158e.png)

Then
![image](https://user-images.githubusercontent.com/2097773/83974452-a9572e80-a8ed-11ea-895b-9633c79bcfa7.png)
![image](https://user-images.githubusercontent.com/2097773/83974459-b70cb400-a8ed-11ea-90a7-aa2f2e17ee2c.png)

**Comment by ludovicandrieux** [comment]
Hi Maxime,

Thanks for reply.
I reproduce the bug.

That's what i send :
![2020-06-08_094721](https://user-images.githubusercontent.com/11213740/84005289-32fa1100-a96d-11ea-9d5c-cefb6b542194.png)

That's what i get :
![2020-06-08_094733](https://user-images.githubusercontent.com/11213740/84005316-3b524c00-a96d-11ea-88ba-1a534ceb388c.png)

IMHO : That's a bug when you add or not the / at the end will change or not the name of the first folder.
What do you think about that ?
