### ISSUE TITLE
Paybox module

### ISSUE THREAD

**Issue by fred-gb** [Dolibarr/dolibarr#13865]
# Bug
Impossible de faire un paiement par le module Paybox. 

## Environment
- **Version**: 11.0.3
- **OS**: Ubuntu 18.04
- **Web server**: nginx version: nginx/1.14.0 (Ubuntu)
- **PHP**: 7.2
- **Database**: mariadb 10.3
- **URL(s)**: https://xxxxxxxxxxxxx/public/payment/newpayment.php

## Expected and actual behavior
Message d'erreur sur site de Paybox quand on clique sur payer avec carte de crédit
```
Message:


            Error while proceeding authentication with HMAC key     
Request Parameters:


            array (
  'controller' => 'index',
  'action' => 'index',
  'module' => 'default',
  'PBX_IDENTIFIANT' => 'xxxxxxx',
  'PBX_MODE' => '1',
  'PBX_SITE' => 'xxxxxxxxxx',
  'PBX_RANG' => '01',
  'PBX_TOTAL' => '999',
  'PBX_DEVISE' => '978',
  'PBX_CMD' => 'TAG=your_tag.PM=paybox',
  'PBX_PORTEUR' => 'xxxxxxxxxxxxx',
  'PBX_RETOUR' => 'montant:M;ref:R;auto:A;trans:T',
  'PBX_EFFECTUE' => 'https://xxxxxxxxxx/public/payment/paymentok.php?tag=your_tag&fulltag=TAG%3Dyour_tag.PM%3Dpaybox&&e=1',
  'PBX_ANNULE' => 'https://xxxxxxxxxx/public/payment/paymentko.php?tag=your_tag&fulltag=TAG%3Dyour_tag.PM%3Dpaybox&&e=1',
  'PBX_REFUSE' => 'https://xxxxxxxxxx/public/payment/paymentko.php?tag=your_tag&fulltag=TAG%3Dyour_tag.PM%3Dpaybox&&e=1',
  'PBX_TXT' => ' ',
  'PBX_BKGD' => '#FFFFFF',
  'PBX_WAIT' => '2000',
  'PBX_LANGUE' => 'FRA',
  'PBX_OUTPUT' => 'E',
  'PBX_SOURCE' => 'HTML',
  'PBX_TYPEPAIEMENT' => 'CARTE',
  'PBX_HASH' => 'sha512',
  'PBX_TIME' => '2020-05-04T14:16:11Z',
  'PBX_HMAC' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
)  
```   

## Steps to reproduce the behavior
Juste configurer le plugin dans la partie configuration.

**Comment by fred-gb** [comment]
Bonjour,
Mise à jour de Dolibarr 12.0.3 effectuée. 
Toujours même problème de module Paybox.

**Comment by eldy** [comment]
I'm afraid, we don't have any maintainer for the paybox module.
Did you try to use stripe instead. Commission may be higher but registration is free, and it is maintained.
You can also hire a freelance to fix the trouble on current module, for example on https://www.codeur.com

**Comment by fred-gb** [comment]
Thanks, this time, It's clear.

And sorry, but I won't subscribe to stripe, precisely because is higher and Paybox works with my others systems/sites.

I will ask a freelance.

Thanks.

**Comment by jcpaybox** [comment]
Hi everyone, maybe we can help out with this ?

@eldy can we get in touch in order for me to understand what we need to do to solve the issue ?
feel free to contact us at : modules-paybox @ verifone.com

kind regards.

**Comment by fred-gb** [comment]
Hello, 
I hope you can help us.
Next by mail.
Thanks

**Comment by ksar-ksar** [comment]
Hello @eldy

The paybox module is not working anymore since several versions, can you make it "depreciated" ?

**Comment by dolibarr95** [comment]
Hello 🙂
A related topic on the french forum :
https://www.dolibarr.fr/forum/t/erreur-paiement-3ds-v2/44826
