### ISSUE TITLE
I want to update the real stock in my dolibarr by Rest Api but it not want be change :

### ISSUE THREAD

**Issue by RDHimni** [Dolibarr/dolibarr#13860]
### **thate my real stock of product id=1  before update :**
![image](https://user-images.githubusercontent.com/50507265/81486843-0496f200-9258-11ea-84b1-71d14cf99064.png)

**### **and this is my request for update the real stock from 38 to 25:****
![image](https://user-images.githubusercontent.com/50507265/81486883-5b9cc700-9258-11ea-937d-e09a099fbdf9.png)
### **and this is result it not want change:**
![image](https://user-images.githubusercontent.com/50507265/81486909-9f8fcc00-9258-11ea-9272-bf0bfbab323f.png)

**Comment by eldy** [comment]
stock_reel is no a "intrinsic" properties of product but a de-normalized value for performance purpose.
If you want to update the real stock, it must call API to make a stock movement (add or decrease).
This field "stock_reel" will be updated automatically.
