### ISSUE TITLE
TakePOS sugestion

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#13863]
Hi Team just a suggestion about the new interface on V12 concerning the finder

![POS](https://user-images.githubusercontent.com/26550824/81503112-bf1b0900-92d9-11ea-9dad-3ab430fd7ee5.png)

**Comment by DATUC** [comment]
Came we have a clean interface like
![POS](https://user-images.githubusercontent.com/26550824/81503368-25ecf200-92db-11ea-9a82-215cf5358075.png)

**Comment by andreubisquerra** [comment]
The finder is located on the top in Dolibarr 12. Similar to your picture. I hope you like it.
![takepos12big](https://user-images.githubusercontent.com/28452516/82345960-2a5d8d00-99f6-11ea-86fe-e698f88a1b0f.JPG)

**Comment by DATUC** [comment]
Hi @andreubisquerra i have done the taste on V12 and i wanted to figure out the fact that the actual position of the finder is not good comparing that to mamy other POS solutions and also the user appreciation, the store where i use to do the demo on testing enviroment and all user ask if ther is a possibilitie to change the finder position.
Excuse my poor English

**Comment by DATUC** [comment]
Hi the request is still waited it concer the finder barr position on the interface

**Comment by altairis-tof** [comment]
a solution would be to have movable blocks by drag&drop...

**Comment by altairis-tof** [comment]
we have also made a PR to hide categories since they are not always usable (no category or  two many categories) : https://github.com/Dolibarr/dolibarr/pull/19527
another one to show category description  : https://github.com/Dolibarr/dolibarr/pull/19525
and another to show SKUs (product references) : https://github.com/Dolibarr/dolibarr/pull/19521
to come : category search PR and sell only product with stock PR
(PRs by @altairis-melina)

**Comment by andreubisquerra** [comment]
I am working on an improved search engine which also autocompletes with a list of products. I will be ready shortly.

**Comment by altairis-tof** [comment]
> I am working on an improved search engine which also autocompletes with a list of products. I will be ready shortly.

thanks for the information @andreubisquerra ;-) 

What about Melina Pull requests then ? it always take lot of time to push on develop branch so i hope it was not useless.

**Comment by andreubisquerra** [comment]
Melina Pull requests is aproved for me!
Thank you @altairis-tof & @altairis-melina

**Comment by eldy** [comment]
@andreubisquerra Can you mention ID of ticket you validated for Melina Pull requests (this may save me time) ;-)

**Comment by andreubisquerra** [comment]
#19527 #19525 #19521 aproved for me
