### ISSUE TITLE
Bulk Import of images for any product

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#13883]
# Feature Request
[*Bulk import of several images per product (variable product included)*]

## Use case
[*today we have to add manually images for each product. Also this does not work for variables products. This is not possible when you are more than 50 products not only at creation but also to updates. We believe this could benefit Dolibarr to add an image import feature (if not done during product importation) that could attach several images to the right product at creation but also during updates*]

## Suggested implementation
[*As done in several other solutions, an image column where we could either reference several URLs or either several filenames store in a specific drive location separated by a semicolon or comma depending of the CSV column separator will be a must to fill Dolibarr images products. Another aspect is to add image feature for variable products as today the child cannot get a specific images. *]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by bleepalcloud** [comment]
I hope this will be implemented in future.
