### ISSUE TITLE
Passage d'information dans l'URL impossible avec le module site web

### ISSUE THREAD

**Issue by Ostrochibi** [Dolibarr/dolibarr#13888]
Bonjour à tous,

Je suis en train de développer un site web avec le module site web intégrer à la V11.0.2 Ce module est vraiment pratique cependant une action basique me manque, passer des info dans l’URL.
Je m’explique. Dolibarr génère un lien interne avec un « & » comme d’habitude qui passe des info dans l’URL mais cette adresse n’est pas utilisé lors de la création des liens de navigation et n’est pas éditable complètement à la création de la page ( pas de :id, c’est remplacé par -id). Le module, ou tout du moins le seul template trouvable, utilise des route en .php où je peux ajouter "&id=’.$object->ref.’ qui se transforme bien en « &id=0024 » par exemple mais qui ne correspond jamais à une route connu.

Je suis donc bloqué au moment de récupérer mes informations entre les pages. Je code en MEAN stack habituellement alors je sais pas trop comment faire, d’habitude j’ai pas de page et j’ai des service pour passer les infos entre les composant. Existe t’il quelque chose de similaire avec php qui est déjà intégrer dans le module site internet ou dans le template fourni que je ne connais pas.

J'espère que je poste ce problème au bonne endroit. Dans le cas contraire, merci de m'indiquer l'emplacement approprié.

**Comment by eldy** [comment]
Can you provide examples. It will be easier to understand.
If you have in you web site a page called    mypage.php?keyparam=abc.
Then into page mypage, you can get param keyparam doing GETPOST('keyparam'). You will get 'abc'.
Note: module website is very new in v11 and has been a lot of enhanced into v12 (soon available).

**Comment by Ostrochibi** [comment]
I try to do that soon. I gonna put link of my website ASAP. I just need to clean it a little.

**Comment by Ostrochibi** [comment]
Hi,

I close this thread because i solved the issue. I change the alias field and not the tittle field wich is the issue.
