### ISSUE TITLE
Bug: no line break

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#13886]
All the text is on the same line :
Bonjour Vous trouverez ci-joint la facture FA2005-1194 Vous pouvez cliquer sur le lien ci-dessous pour effectuer votre paiement si ce n'est déjà fait.  Sincèrement ---------------------- Philippe Grand Treasurer of the association - Trésorier de l'association Dolibarr
## Environment
- **Version**: 12.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: apache2handler 5.6.40-26+ubuntu16.04.1+deb.sury.org+1
- **Database**: MySQL or MariaDB 5.5.5-10.0.38-MariaDB-0ubuntu0.16.04.1
- **URL(s)**: /compta/facture/card.php?facid=1276&action=presend&mode=init

**Comment by frederic34** [comment]
@grandoc can you edit your message to remove the link to the invoice

**Comment by Langlais115** [comment]
@grandoc 
I can't reproduce the issue on my side.
Do you use any template or any specific settings?
Can you please provide the steps to reproduce the issue?

**Comment by eldy** [comment]
This often occurs when you have a text template that is concatenated with a html content. Result is a html content but the part from text has new line only so is visible like a space in a html context.
When you need to contact text (not html or html) and text (not html or html), you must use dol_concat so result will always be correct.

**Comment by grandoc** [comment]
It's on Dolibarr foundation instance....
