### ISSUE TITLE
Can't acces to product extrafield with odt template.

### ISSUE THREAD

**Issue by Ostrochibi** [Dolibarr/dolibarr#13898]
I don't gonna explain more this issue, i just post the resolution.

Remplace the file doc_generic_product_odt.modules.php in core/modules/product/doc by the following. I think the commented text was the issue but i am not sure.

https://github.com/Ostrochibi/dolibarr-fix

That's it for now.

Have a nice day

**Comment by Ostrochibi** [comment]
If anyone can put this issue to solved. I am noob and i dont know how to do it :).

**Comment by dpriskorn** [comment]
Could you submit a pull request?

**Comment by ksar-ksar** [comment]
Hello,

Working for me on V13.0.2
