### ISSUE TITLE
VAT/Sales Tax inclusion in total

### ISSUE THREAD

**Issue by rpe1313** [Dolibarr/dolibarr#13892]
# Bug
When Margins Module is turned on, some invoices/quotes do not included taxes in the total for the document. This occurs ONLY when costs have not been entered into the product or the service. Tax is listed as non-recoverable.

## Environment
- **Version**: 11.0.4
- **OS**: Centos 7
- **Web server**: Apache 2.4
- **PHP**: 7.3
- **Database**: 5.6.42

## Expected and actual behavior
Sales tax (VAT) to be included in total when Margins Module is enabled but costs have not been entered.

## Steps to reproduce the behavior
Must have Margins Module enabled.
Create Service/Product without cost entered
Create new quote/invoice. Assign Service/Product to document and review in PDF

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case for newer versions of Dolibarr (V13) ?

**Comment by guiltekmdion** [comment]
Hi, we have the same problem. VAT is empty when we activate this module since the 18.0
