### ISSUE TITLE
Variant labels overwritten by parent label

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#13908]
# Bug
Reported by adeoexpo
J’utilise les variantes et il y a un problème :
Je crée l’article « père » avec 16 variantes.
Comme la présentation du champs « Libellé » n’est pas terrible sur la variante, je le modifie à chaque fois - OK
Mais, si par malheur, je change quelque chose dans la fiche de l’article « père » après la création des variables, Dolibarr change instantanément TOUS les libellés des variables, les réécrivant comme à leur origine !
Translation:
I'm using the variants and there's a problem:
I create the article "parent" with 16 variants.
As the presentation of the "Label" field is not very good on the variant, I modify it each time - OK
But, if by misfortune, I change something in the "parent" article after creation of variables, Dolibarr instantaneously change ALL labels of variants, rewriting them as at their origin!

## Environment
- **Version**: 11.0.4

## Expected and actual behavior
Preserve variant labels

**Comment by Langlais115** [comment]
I can reproduce the issue in **v13.0.0-alpha** as well.
