### ISSUE TITLE
Miss first line in new page (propal)

### ISSUE THREAD

**Issue by loundor** [Dolibarr/dolibarr#13909]
Hi, I've a problem with Dolibarr 11.0.4 (was same with 11.0.3), when I generate my propal in PDF and there is more that one page, all next pages have the first line in transparant or don't exist. I have see some issues about that (pdf_standard.modules.php) but nothing work. Somepeople have this a solution about that? I'had try to generate PDF with another template but same problem. I give you some screenshot.. Thx for your reply.
![pb1](https://user-images.githubusercontent.com/24739245/82261581-90e39c00-995f-11ea-852c-9986eb730eb6.jpg)
![pb](https://user-images.githubusercontent.com/24739245/82261590-98a34080-995f-11ea-8147-b06d3c02240a.jpg)

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by loundor** [comment]
Hi thx for your reply. I do the update to v12 and always the same. I had try to change the template, but nothing work.The first line is here but in white. I see some post about that and try that but don't work..

**Comment by atm-maxime** [comment]
What is the PDF model you're using ? If it's the standard "azur" model that's definitely a big, if it's another, this concerns the developer of the model you're using. If you generate with the azur model you also have the issue ?

**Comment by loundor** [comment]
Hello, I tried with azure, and it's the same problem. I have more template/model, and always same problem. I report picture later..

**Comment by atm-maxime** [comment]
Seems to me that the model you're using has been customized. Your "titles" are displayed differently than a standard option line.

**Comment by loundor** [comment]
> Seems to me that the model you're using has been customized. Your "titles" are displayed differently than a standard option line.

Yes right but with azure model (original file) the problem is here. I will add some screenshots the next days with original model.

**Comment by BebZ** [comment]
Hello you should use the ATM module "sub total" to display differently the lines and group/ungroup the lines as desired ;)

https://www.dolistore.com/fr/modules/345-Sous-total.html

**Comment by ksar-ksar** [comment]
Hello,

Work for me, there is no missing lines with the default template and V13
