### ISSUE TITLE
No option to hide VAT ID

### ISSUE THREAD

**Issue by r9guy** [Dolibarr/dolibarr#13906]
# Instructions
there is no option to hide VAT ID in generated PDF document's footer.

## Use case
in GCC countries it is permitted 

1. not to use VAT if company is new , 

2.its turnover is below a threshold. 

 in second case the VAT ID is available with federal tax authority, but it must not be mentioned on any document.

## Suggested implementation
implement an option in Setup->PDF to hide footer VAT ID

**Comment by eldy** [comment]
You should have already both features.
Check setup in home - setup - company and home - setup - pdf

**Comment by r9guy** [comment]
Dear @eldy 
the issue is that then in PDF VAT generation is disabled there's still no way to hide the VAT number in footer and in own contact.
the scenario is : I de register from VAT as law asked me to, I still have VAT number so I will not remove it from from the system, but I am told not use use vat until further notice.
currently if the VAT number in professional fields of the company & Home is defined, it always apears on the footer of generated pdf, and in own contact block
