### ISSUE TITLE
Data Base Error with latest version of app

### ISSUE THREAD

**Issue by adispennette** [Dolibarr/dolibarr#13910]
> Dolibarr has detected a technical error.
> This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
> Date: 20200519024210
> Dolibarr: 11.0.4
> Level of features: 0
> PHP: 7.2.30
> Server: Apache
> OS: Linux  SMP Thu Mar 26 08:20:27 EDT 2020 x86_64
> UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0
> 
> Requested URL: /crm/accountancy/admin/productaccount.php
> Referer: /crm/accountancy/index.php?leftmenu=accountancy_admin
> Menu manager: eldy_menu.php
> 
> Modules/Applications: user, expensereport, contrat, expedition, tax, prelevement, accounting, agenda, commande, deplacement, don, facture, fournisseur, opensurvey, societe, service, mailing, export, import, projet, cashdesk, banque, propal, stock, product, adherent
> Database type manager: mysqli
> Latest database access request error: SELECT p.rowid, p.ref, p.label, p.description, p.tosell, p.tobuy, p.accountancy_code_sell, p.accountancy_code_sell_intra, p.accountancy_code_sell_export, p.accountancy_code_buy, p.tms, p.fk_product_type as product_type, aa.rowid as aaid FROM doli_product as p LEFT JOIN doli_accounting_account as aa ON p.accountancy_code_sell = aa.account_number AND aa.fk_pcg_version = 'US-BASE' WHERE p.entity IN (1) AND aa.account_number IS NULL ORDER BY p.ref ASC LIMIT 26
> Return code for latest database access request error: DB_ERROR_1267
> Information for latest database access request error: Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='
> 

## Expected and actual behavior
Not sure as I just upgraded to the latest version from a very old version.

## Steps to reproduce the behavior

1. after upgrade click accountancy
2. in the list of setup steps select the last one
3. See Error Above

**Comment by adispennette** [comment]
So I had to update the doli_product table to set the collation to utf8_general_ci.  I'm not sure what the unforeseen consequences are going to be of doing this. but for now it works.  I have already seen that there are other utf8_unicode_ci columns in the db so I guess I will just update them as I find them.

**Comment by adispennette** [comment]
Going through the more of the tables there are numerous Collation across tables.  I don't know if that is intentional but it seems like its probably a bug. The majority seem to be `Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='` but there seem to be others as well.  The initial log I posted above is not on all the screens when the error occurs so I don't know all the columns that are affected in other tables.
To reproduce the latest go to:
Accounting -> Expense report binding -> Lines to bind
Expected: A UI that has things to be bound
actual is:
<img width="1137" alt="Screen Shot 2020-05-19 at 6 25 45 PM" src="https://user-images.githubusercontent.com/9353714/82394542-33525c80-99fe-11ea-8362-db4b1e904f3d.png">

**Comment by dpriskorn** [comment]
Could you add more information? What version did you upgrade from? Which database system?

**Comment by MartinFulgueiras** [comment]
Hi, same issue here...

Dolibarr ha detectado un error técnico.
Esta información puede ser útil para el diagnóstico (puede configurar la opción $dolibarr_main_prod to '1' para eliminar estas notificaciones):
Fecha: 20200922215753
Dolibarr: 12.0.2 - https://www.dolibarr.org
Nivel de funciones: 0
PHP: 7.3.21
Server: Apache
OS: Linux quince.serverpe.com 3.10.0-714.10.2.lve1.5.12.el7.x86_64 #1 SMP Fri Feb 2 00:27:48 EST 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

URL solicitada: /blablablabla_bla/compta/resultat/index.php?mainmenu=accountancy&leftmenu=accountancy_report
Referer: https://www.blabla_bla.comt/blablablabla_bla/accountancy/index.php?mainmenu=accountancy&leftmenu=
Gestor de menú: eldy_menu.php

Módulos: user, loan, hrm, notification, stock, ficheinter, contrat, clicktodial, adherent, supplier_proposal, tax, multicurrency, export, expedition, incoterm, banque, productbatch, product, projet, import, mailing, margin, propal, workflow, bookmark, fckeditor, categorie, accounting, agenda, barcode, commande, ecm, expensereport, facture, fournisseur, holiday, printing, resource, salaries, societe, service
Tipo de gestor de base de datos: mysqli
Último error en solicitud de acceso de base de datos: SELECT b.doc_ref, b.numero_compte, b.subledger_account, b.subledger_label, pcg_type, date_format(b.doc_date,'%Y-%m') as dm, sum(b.debit) as debit, sum(b.credit) as credit, sum(b.montant) as amount FROM llxrc_accounting_bookkeeping as b, llxrc_accounting_account as aa WHERE b.entity = 1 AND aa.entity = 1 AND b.numero_compte = aa.account_number AND ( (pcg_type = 'EXPENSE') OR (pcg_type = 'INCOME')) AND fk_pcg_version = 'PCG08-PYME' AND b.doc_date >= '2017-01-01 00:00:00' AND b.doc_date <= '2020-12-31 23:59:59' GROUP BY b.doc_ref, b.numero_compte, b.subledger_account, b.subledger_label, pcg_type, dm
Código de retorno de error para la última petición de acceso a la base de datos: DB_ERROR_1267
Información del último error de petición de acceso de base de datos: Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='

**Comment by aspangaro** [comment]
You can use the script include to repare and align your db with utf8_unicode_ci.
Just add "/install/repair.php?force_utf8_on_tables=confirmed" at the end of the url when your connect to dolibarr home
