### ISSUE TITLE
time selector is too small

### ISSUE THREAD

**Issue by altairis-agnes** [Dolibarr/dolibarr#13919]
# Bug
`<input class="flat maxwidth50 inputhour" placeholder="H" type="number" min="0" size="1" name="durationhour" value="">`
Change size to 10, not 1
Idem for hours or min.

## Environment
- **Version**: *v12alpha*
- **URL(s)**: 
* htdocs/bom/bom_card.php?leftmenu=bom&action=create
* htdocs/projet/activity/perday.php
* ...

## [Attached files]
![BOM_-_2020-05-19_11 33 18](https://user-images.githubusercontent.com/418114/82310436-ad65ef80-99c4-11ea-8730-28a26a362673.png)
![BOM_-_2020-05-19_11 32 49](https://user-images.githubusercontent.com/418114/82310454-b48cfd80-99c4-11ea-957f-a3708134a3fd.png)

**Comment by atm-adrien** [comment]
Hello, 
I don't have this problem in version 12.0, so I think this has been fixed in 12.0

**Comment by ksar-ksar** [comment]
Hello,

Work for me on V13
