### ISSUE TITLE
Cannot add a new OF

### ISSUE THREAD

**Issue by altairis-agnes** [Dolibarr/dolibarr#13927]
# Bug
When the "create" button is clicked, the following error message is displayed. The OF is not created. 
*Cannot add or update a child row: a foreign key constraint fails (`doli12`.`llx_mrp_mo`, CONSTRAINT `fk_mrp_mo_fk_user_creat` FOREIGN KEY (`fk_user_creat`) REFERENCES `llx_user` (`rowid`))*

## Environment
- **Version**: 12.0
- **URL(s)**: /htdocs/mrp/mo_card.php

**Comment by eldy** [comment]
I can't reproduce. Do you still have trouble with last version of branch v12 ?

**Comment by dpriskorn** [comment]
Please upgrade to the latest version and reopen this if the problem persists.
