### ISSUE TITLE
Time is different on agenda page for 3rd party vs event card

### ISSUE THREAD

**Issue by operakadabra** [Dolibarr/dolibarr#13926]
From https://dolibarr.xxxxxxx.com/societe/agenda.php?socid=62 (shows 9:43am)

![Screenshot from 2020-05-19 10-51-17](https://user-images.githubusercontent.com/41698037/82360796-c1a6ee00-99be-11ea-814b-3960f1465fc3.png)

from https://dolibarr.xxxxxxx.com/comm/action/card.php?id=11393 (shows 10:43am)

![Screenshot from 2020-05-19 10-52-34](https://user-images.githubusercontent.com/41698037/82360918-f31fb980-99be-11ea-9d12-4906b91547f8.png)

**Comment by hregis** [comment]
What is the good time for you?

**Comment by operakadabra** [comment]
The one on the agenda page (10:43am). Thanks.

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?
