### ISSUE TITLE
Triage de la liste des tâches (Progession calculée)

### ISSUE THREAD

**Issue by jsbrassard** [Dolibarr/dolibarr#13933]
Il est possible de trier par ordre croissant la majorité des colonnes de la liste (Ref. tâche, étiquette, date de début, tiers, charge de travail, etc.) mais pas la progression calculée.

---

It's not possible to sort by ascending/descinding order the colomn "Calculated progress" in **Task list** under the project ->Tasks/activities -> list tab

**Comment by dpriskorn** [comment]
Please translate to english

**Comment by jsbrassard** [comment]
> Please translate to english

It's not possible to sort by ascending/descinding order the colomn "Calculated progress" in **Task list** under the project ->Tasks/activities -> list tab

**Comment by dpriskorn** [comment]
Version? Tried updating to v12?

**Comment by jsbrassard** [comment]
I'm on 12.0.1
and the problem is still present
![image](https://user-images.githubusercontent.com/51123237/89646117-23be1380-d889-11ea-94a3-b8c97a3fb655.png)
