### ISSUE TITLE
MRP: include recipe and recursive BOM's

### ISSUE THREAD

**Issue by fbosman** [Dolibarr/dolibarr#13930]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request
Enhance the new MRP with some ISA-95 aspects; Recipe and recursion

## Use case
In order to use the MRP we need a more sophisticated model. Now we have a BOM, the product-decomposition, and the MO, manufactor order. In order to control the proces we need a recipe which defines a composition of MF's, with order and dependencies, to enable the management of complex production processes.

## Suggested implementation
Introduce the recipe object which contains lines and rules attached to MO's.
Relate the recipes to the BOM-object for complex production
Enhance the MO-code so that if a composite product needed in the BOM has no stock a sub-MO is issued.
Create the possibility to administer the progress in time and in completed MO's.

## Suggested steps
I can work on this solution for a customer, but I would like to have it incorporated in the core MRP

**Comment by BebZ** [comment]
Hello @fbosman 
I hope you can develop this model, everyone would need (and we would need it too)
Do you have an e-mail where i can contact you and maybe share the dev costs ?

**Comment by atm-maxime** [comment]
#17715 is a detailed feature request for the "recipe" part

**Comment by fbosman** [comment]
Indeed, a very good start, this one can be closed

**Comment by atm-maxime** [comment]
You can keep it open, for the recursive BOM feature request. It's needed 😉

**Comment by mschamp** [comment]
I would also really like to have the possibility to have recursive BOM.
