### ISSUE TITLE
Doliwamp is outdated

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#13949]
Dear developers,

We all agree that Doliwamp is outdated with old php version, very poor performances and bad user experience.
Except if I'm wrong, the generation script of the Doliwamp is not part of any repository, so we can't propose any improvements.

Do you think it is possible to release the script that generate the Doliwamp in order for the community to be able to upgrade it ?

Thanks a lot.

Link to #13344

**Comment by hregis** [comment]
Go to /build/exe/doliwamp/

**Comment by ksar-ksar** [comment]
Hi,

Thanks for the answer, but this is only one part of the tool.
You have only some custom scripts and conf but not the full package.
For exemple you can move from php 5.4 to 7.2 with only /build/exe/doliwamp/

Or may be i do not understand the way it is built ?

**Comment by ksar-ksar** [comment]
Hi,

I continu my investigations, if anyone can help it will be great !

In the /build/exe/doliwamp/ you have two generation scripts : 

1.  https://github.com/Dolibarr/dolibarr/blob/develop/build/exe/doliwamp/Makefile 
   Seems to use old code and MINGW : I think this script is not in use.
2. https://github.com/Dolibarr/dolibarr/blob/develop/build/exe/doliwamp/doliwamp.iss
   This one is based on InnoSetup  and seems to be the actual one ?

On the doliwamp.iss there is paths to be included in the archive : 

1. Source: "C:\Program Files\Wamp\apps\phpmyadmin4.1.14\*.*"; DestDir: "{app}\apps\phpmyadmin4.1.14"; Flags: ignoreversion recursesubdirs; Excludes: "config.inc.php,wampserver.conf,*.log,*_log,darkblue_orange"
2. Source: "C:\wamp64\bin\apache\apache2.4.41\*.*"; DestDir: "{app}\bin\apache\apache2.4.41"; Flags: ignoreversion recursesubdirs; Excludes: "php.ini,httpd.conf,wampserver.conf,*.log,*_log"
3. Source: "C:\wamp64\bin\php\php7.3.12\*.*"; DestDir: "{app}\bin\php\php7.3.12"; Flags: ignoreversion recursesubdirs; Excludes: "php.ini,phpForApache.ini,wampserver.conf,*.log,*_log"
4. Source: "C:\wamp64\bin\mariadb\mariadb10.4.10\*.*"; DestDir: "{app}\bin\mariadb\mariadb10.4.10"; Flags: ignoreversion recursesubdirs; Excludes: "my.ini,data\*,wampserver.conf,*.log,*_log,MySQLInstanceConfig.exe"

All theses files are not includes in the /build/exe/doliwamp/
So we are not able to update/upgrade the DOLIWAMP.

Could you make theses files availlable in the repository ?

Note : I'm quiet surprised that there is a "Copyright (C) 2008-2020 Laurent Destailleur (NLTechno), Fabian Rodriguez (Le Goût du Libre)" in that file .... All the Dolibarr project is supposed to be GNU ?  https://github.com/Dolibarr/dolibarr/blob/develop/build/exe/doliwamp/doliwamp.iss#L35

**Comment by davidNDU** [comment]
When I started using DoliWAMP I saw the struggle with old PHP and that I could not use the latest development version (maybe I am wrong with this, but I couldn't see it back then) I decided to use WAMPServer 3.2.0 instead and simply pull dolibarr from github. Works out fine.

**Comment by ksar-ksar** [comment]
Hi,

Thanks @davidNDU , we all do that.
My concern is that 90% of new comers to Dolibarr start with Doliwamp....
An then either quiet Dolibarr because it is not working well or start to discuss the issue on the forums, where we always say the same thing : Do not use Doliwamp.

It would be good if Doliwamp would be upgraded to have a decent tool.

**Comment by ksar-ksar** [comment]
Link to #13755 , #13344 , #14036

Still no news on that ?
Doliwamp is really a painful tool...

**Comment by isoscent** [comment]
> 
> Dear developers,
> 
> We all agree that Doliwamp is outdated with old php version, very poor performances and bad user experience.
> Except if I'm wrong, the generation script of the Doliwamp is not part of any repository, so we can't propose any improvements.
> 
> Do you think it is possible to release the script that generate the Doliwamp in order for the community to be able to upgrade it ?
> 
> Thanks a lot.
> 
> Link to #13344

Sir; Your update will be a failure because You might need to consider this Factor below:
1. System Hardware
2. The SQL DB and the  version that the User has been installing(MySQL, MariaDB, Oracle, MSSQL ,,etc..) 
3. PHP version that the particular user is being used and to be used.
4. Hosting system, Is it? IIS version?, Apache Tomcat verions?, Ngix version?, Open Resty version?, Apache HTTP verions?, Passenger version? 
5. Your Program is useless, since, from inside of Dolibarr and Installation alone you can do it. So?

I tested your apps several times. I tried it also on Dolibarr 12 on how it will run. the Answer is nothing. Do not worry I will post here the Snapshot, the Results of running your apps. 

Now, may I request If you can help us build the Installer that the Dolibarr can work with MSSQL or Oracle then that would be a big Contributions to the community.

Thank you. Your work has been greatly appreciated.

**Comment by dpriskorn** [comment]
> Note : I'm quiet surprised that there is a "Copyright (C) 2008-2020 Laurent Destailleur (NLTechno), Fabian Rodriguez (Le Goût du Libre)" in that file .... All the Dolibarr project is supposed to be GNU ? https://github.com/Dolibarr/dolibarr/blob/develop/build/exe/doliwamp/doliwamp.iss#L35

I think you misunderstood how copyright works. GNU uses copyright law to help keep the 4 freedoms. You should always state you name and year on something you create. That does not influence the license but your ability to claim the work as yours.
This is needed when e.g. dealing with gpl violations.
