### ISSUE TITLE
Bug: Contact Card - Translation no shown

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#13946]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Found the translation on the contact card under the default contact/address are not properly shown or translated.

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /contact/card.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

<img width="518" alt="Capture" src="https://user-images.githubusercontent.com/52134143/82626427-63764700-9c1a-11ea-9415-9be81afb9808.PNG">

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by asolslk** [comment]
cant see anymore as i had updated manually myself, just to let the team know there is a minor issue. not important, you can close it
