### ISSUE TITLE
Module Builder Objet From existing table create no files

### ISSUE THREAD

**Issue by elarifr** [Dolibarr/dolibarr#13957]
Hi
In module builder (11.04) , in objet tab, when you try to create from existing table 
(Construire la chaîne du tableau de structure d'une table existante), the builer display only array code without any dolibarr menu/gui to return to module builder feature and create no files

is it normal feature ou bug or just not finished ?

i want to make from module builder a new object bank2 from an existing table (llx_bank) , does it mean i have to recreate new object / table llx_bank2 from module builder and then hack file to use llx_bank instead of the created llx_bank2  
 
Fr ////////////////////////////////
depuis module builder, l'option 
Construire la chaîne du tableau de structure d'une table existante
affiche seulement la chaîne du tableau brute dans le meme onglet du module builder sans afficher les menu ni environnement de dolibarr sans créer les fichiers nécessaire.

est ce le fonctionnement prévu ou un bug ou pas finalisé ? 

je veux dans module builder creer les fichiers nécessaire a un nouvel objet bank2 et utiliser la table existante llx_bank. faut'il recreer toute la structue de llx_bank dans une nouvelle table bank2 pour generer les fichiers adequats et ensuite remodifier pour utiliser llx_bank... 

elarifr

**Comment by davidNDU** [comment]
What do you want to achieve with the new object? The new object created by the module builder has it's own class with data stored to a table. You can access any other table from dolibarr, of course.
