### ISSUE TITLE
Public event

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#13953]
Currently, it's only possible to assign someone to a project.

If the user has the access "to only see events where he is tagged in" he won't see the event if he isn't tagged in.

When you have a lot of users in your organisation and you want to make an event for everyone. The only solution is to assign that event to everyone. That solution takes time for the user.

It would be great to make an event public (like everyone is assigned to that ticket).

**Comment by atm-maxime** [comment]
Or to add a shortcut to add all users from a group to an event ?

**Comment by laudeco** [comment]
sorry @atm-maxime but it's not a solution, imagine ...

You add a new user you expect that new user sees the event without any human action.
