### ISSUE TITLE
An event of a project shouldn't be visible by everyone

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#13952]
# Bug
When you have an event linked to a project.  
That project is only visible by the contact of the project.
The event should only be visible by the member of that project.

## Expected and actual behaviour
Currently, the event is visible by everyone on the calendar view. 
The event should only be visible by the member of the project.

Even a member, that has access for seeing all the events and that is **not** a member of the project shouldn't see this event.

## Steps to reproduce the behaviour
* Create a project with a visibility only for the contacts of the project.
* Create an event assigned to that project

**Comment by atm-maxime** [comment]
Hi @laudeco !
Not sure I agree on this. If user has permission to see all events, there shouldn't be other restrictions. I'd like to know that an invoice has been sent to the customer event if I don't have permission to see invoices. Same for projects then...

**Comment by laudeco** [comment]
I would agree for automatic events.
But not for manual event such as Call, Meeting and so on ...

How do you do an event only visible by the member of a project?

**Comment by atm-maxime** [comment]
Even for manual events I'd like to see it even if I can't read the linked object.
Currently there's no way to restrict access to an event based on the linked object, project or other.

**Comment by laudeco** [comment]
Hi,

Indeed, and for me, that's an issue. It's not normal that you can see the event if you cannot see the linked resource. Whatever resource it is.

I don't know what the other thinks about that.

By the way, @atm-maxime thanks for the debate! It's like that that we can improve the tool.

Cheers
L.

**Comment by laudeco** [comment]
Hi @atm-maxime I think I know the solution to that problem ;-)


What if we add an hidden config that hide the event for which the user cannot access the resource ? 

This config would override the read all event access and the assigned event too (btw it wouldn't be logical to select an assignee which is not part of the project)

What do you think about that solution?

Cheers 
L.
