### ISSUE TITLE
Replacement invoices are not handled correctly in accountancy

### ISSUE THREAD

**Issue by guillaumematheron** [Dolibarr/dolibarr#13955]
# Bug
When FACTURE_DEPOSITS_ARE_JUST_PAYMENTS is NOT set, then replacement invoices are not shown on page accountancy/customer/lines.php

## Environment
I believe this bug was introduced in 545c2207b2, and persists to this day on the master branch. These lines : 
```php
if (! empty($conf->global->FACTURE_DEPOSITS_ARE_JUST_PAYMENTS)) {
        $sql .= " AND f.type IN (" . Facture::TYPE_STANDARD . "," . Facture::TYPE_REPLACEMENT . "," . Facture::TYPE_CREDIT_NOTE . "," . Facture::TYPE_SITUATION . ")";
} else {
        $sql .= " AND f.type IN (" . Facture::TYPE_STANDARD . "," . Facture::TYPE_STANDARD . "," . Facture::TYPE_CREDIT_NOTE . "," . Facture::TYPE_DEPOSIT . "," . Facture::TYPE_SITUATION . ")";
}
```

Should probably read : 
```php
if (! empty($conf->global->FACTURE_DEPOSITS_ARE_JUST_PAYMENTS)) {
        $sql .= " AND f.type IN (" . Facture::TYPE_STANDARD . "," . Facture::TYPE_REPLACEMENT . "," . Facture::TYPE_CREDIT_NOTE . "," . Facture::TYPE_SITUATION . ")";
} else {
        $sql .= " AND f.type IN (" . Facture::TYPE_STANDARD . "," . Facture::TYPE_REPLACEMENT . "," . Facture::TYPE_CREDIT_NOTE . "," . Facture::TYPE_DEPOSIT . "," . Facture::TYPE_SITUATION . ")";
}
```

Notice in the enumeration, `TYPE_STANDARD` is mentioned twice in the current code.

**Comment by ATM-Nicolas** [comment]
Can you please specify the dolibarr version in which you have encountered this problem ?

**Comment by guillaumematheron** [comment]
I'm not sure what was the version number at the time, I was working directly with master.

But it looks like this bug is still present today : [https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/accountancy/customer/lines.php#L199](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/accountancy/customer/lines.php#L199)
