### ISSUE TITLE
How Install/Insert Script Code

### ISSUE THREAD

**Issue by MyBlissIT** [Dolibarr/dolibarr#13964]
I have just come across this useful page of Dolibarr Scripts, but I do not know how to make use of these scripts on my Dolibarr installation.

Do I create a new module and just copy and paste the code?
This is the link: https://doxygen.dolibarr.org/develop/d5/d01/email__unpaid__invoices__to__customers_8php_source.html

**Comment by ksar-ksar** [comment]
Hi,

Please continu in the forum : https://www.dolibarr.org/forum/t/how-install-insert-script-code/19063
GIT is not the place to get HELP.
