### ISSUE TITLE
GPAO OF

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#13963]
# Bug
GPAO OF not working

## Environment
- **Version**: Dolibarr version(s) 11.0.4 and dev 12
- **OS**: Windows 10 Pro
- **Web server**: AMPPS v 3.9 
- **Web server**: Apache v 2.4.41
- **PHP**: 7.3.11
- **Database**: 8.0.18
- **URL(s)**: localhost/erpv12/mrp/mo_card.php

## Expected and actual behavior
Hi have well created an BMO great's and validated, but when trying to create an OF i have some issue
1- Not able to link a TIERS
2- Can a project be automatically created and validated for any new OF?
3- Date automatically drop back to 01/01/1970 on the OF
4- When trying to create the OF have this error "Column 'tms' cannot be null''
OF initial config
![OF1](https://user-images.githubusercontent.com/26550824/82761676-2c5b8d80-9df4-11ea-9143-a70b9e8e84fc.png)
OF error page
![OF2](https://user-images.githubusercontent.com/26550824/82761679-2ebde780-9df4-11ea-8eff-26c9c68a85ca.png)

**Comment by DATUC** [comment]
I Have done the same tests on a shared web hosting server and everything is ok on Dolibarr V11.0.4
But problem still remain on local hosting environment using AMPPS and XAMP

**Comment by FHenry** [comment]
Module is not accessible with MAIN_FEATURES_LEVEL=0, you must have force MAIN_FEATURES_LEVEL to 1 or more. 
It's ok to test feature under development, but report bug on it isn't so relevant, except if you want to make a pull request to fix them.
I've just try on a fresh 11.0 and 12.0_alpha (not for production uses) and this problem does not appears, on a local LAMP environment

As you said, it a local hosting environment problem using AMPPS and XAMP problem, not a Dolibarr bug.
Check your database local engine configuration and compare with your hosting database configuration.

**Comment by DATUC** [comment]
Finally got a solution, use MariaDB not MySQL on MySQL the problem remain "Column ‹ tms › cannot be null" but when using MariaDB the GPAO modul work well.
Tks
