### ISSUE TITLE
Advance money feature in expense module 

### ISSUE THREAD

**Issue by sunshuvo** [Dolibarr/dolibarr#13960]
Dear Team,

I have a feature request that, is it possible to request for advance money for a future expense which will be paid in advance and will be adjusted under the same request as an expense. If refund then back to account and if over expense that will be paid.

Thank you

**Comment by atm-maxime** [comment]
Hi ! Thanks for your feedback. Seems to be an interesting feature request. But I don't see how to achieve this. Any ideas @aspangaro ?
Cheers

**Comment by sunshuvo** [comment]
Hi, thank you to show interest on my request. If you can achieve this it will be usefull for everyone. Because most of the company give advance money for the expense.
Tarikul

**Comment by philippe-opendsi** [comment]
Hi,
Maybe we must have in the module a new special type of expense like "Advance" on which you can have a payment. The amount of this advance (and other possibly) should be kept on the user and proposed and applied on futur expense in order to be refund (like credit note on invoice).

**Comment by atm-maxime** [comment]
Yes good idea ! More like a deposit I think because this advance is a positive expense note. There's a lot of work to achieve that. It took some time to add supplier credit note managed like on the customer side...

**Comment by sunshuvo** [comment]
> Hi,
> Maybe we must have in the module a new special type of expense like "Advance" on which you can have a payment. The amount of this advance (and other possibly) should be kept on the user and proposed and applied on futur expense in order to be refund (like credit note on invoice).

HI Philippe, thanks for your reply. I got your point, that there has an alternative way to. But didn't understand that how to use that. Could you please give me a brief of that procedure?

**Comment by philippe-opendsi** [comment]
Hi
This alternative way I described, has to be developed in Dolibarr :-) . For the moment I'm not sure there's a way to handle that simply.

**Comment by sunshuvo** [comment]
> Hi
> This alternative way I described, has to be developed in Dolibarr :-) . For the moment I'm not sure there's a way to handle that simply.

Ohh got it. Thank you.
