### ISSUE TITLE
Bug: Accounting Account Code : Field 'Accounting account' is required

### ISSUE THREAD

**Issue by w4cdev** [Dolibarr/dolibarr#13961]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Field 'Accounting account' is required*]

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.4.6
- **Database**:  10.1.45-MariaDB
- **URL(s)**: /dolibar/admin/perms.php?pid=76&action=add&page_y=800&page_y=800

## Expected and actual behavior
[*Verbose description*]
Tried all values inserted and later with adding Accounting account code, but cannot figure out where is the relevant input to be inserted. If left blank, it returns the Error: "Field '**Accounting account' is required**"

The accounting code is no where reported by manual insertion nor accepted from any other input value so that it can be called from relevant field counter.

## Steps to reproduce the behavior
[*Verbose description*]
(https://user-images.githubusercontent.com/43088623/82757659-8d3c9300-9dff-11ea-9c62-dcec1b7fc265.png)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Screenshot_3 Dolibarr Accounting account code error](https://user-images.githubusercontent.com/43088623/82757683-bc530480-9dff-11ea-96eb-578e019ecb98.png)

[*Files*]

**Comment by dpriskorn** [comment]
What are you trying to do? Can you update to v12 and see if the problem persists?

**Comment by erwinpalma** [comment]
I have the same issue with the version 12.0.1

How to reproduce the issue?

- Access to bank | Cash
- Select a "Bank Account"
- Click on "Bank Entries" --> "Add entry"
- try to add an Pyment
- Fill the fields and select an Accounting Account that exist and then click on Create account
![image](https://user-images.githubusercontent.com/30660343/105886782-1b11f300-600b-11eb-8621-92db07290834.png)

**Comment by ksar-ksar** [comment]
Hello,

Still there in V13 ?

**Comment by erwinpalma** [comment]
Now that the pre-release is available I am gonna test it again, I will let you know the results

**Comment by erwinpalma** [comment]
I have tested the Dolibarr 14 Beta (Freeze) and it looks like that works.

I was investigating and the issue is related with **ACCOUNTING (DOUBLE ENTRY)**, with the **ACCOUNTING (SIMPLIFIED)** the issue is not presented.

My workaround was creating another entry into the **account accounting** and do not use the default one
