### ISSUE TITLE
Can't use prépayment invoice

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#13971]
Hi

I'm not sure if it is a bug or if I have made a mistake, but pls have a look at the attached screenshot. I made a Facture d'acompte but when I try to use it and is going to validate the final invoice it complain and says "Le total des lignes ne peut pas être négatif pour un taux de TVA donné"

Is it me messing it up, and if so, what is wrong, or is it a bug?

![facture-d-acompte](https://user-images.githubusercontent.com/24247236/82890023-d8fc5300-9f4b-11ea-9e57-71d381696d6e.jpg)

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.25
- **PHP**: fpm-fcgi 7.2.31-1+0~20200514.41+debian9~1.gbpe2a56b
- **Database**: MySQL or MariaDB 5.5.5-10.1.44-MariaDB-0+deb9u1
- **URL(s)**: /azerty/htdocs/compta/facture/card.php?facid=278&action=valid&page_y=1000

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hi,

GitHub is not the place for support.
Please do to forum : https://www.dolibarr.fr/forum/

have a look on : https://www.dolibarr.fr/forum/t/facture-acompte/27338/7
and : https://wiki.dolibarr.org/index.php/Module_Factures_Clients#Acomptes

**Comment by hasse-basse** [comment]
Thanks, I had use for the links, but it had been up running for me, some settings changed with an update, but I don't know what update.
