### ISSUE TITLE
Translation of State/Province field in HTML select list is wrong

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#13978]
# Bug
Some Italian provinces have same "code_departement" as Langs Keys. 
Example:
MO = Modena --> is translated as "Manufacturing Order"
IM = Imola --> is translated as "Instant Messaging"

## Environment
- **Version**: tested on 11.x but a I think all versions

## [Attached files]
![immagine](https://user-images.githubusercontent.com/1215488/83012507-cb160300-a01b-11ea-9024-6d5148fc82a4.png)

**Comment by aschio** [comment]
![image](https://user-images.githubusercontent.com/1215488/119946756-44319880-bf97-11eb-96ad-abddbb752baf.png)

Bug is still present on Dolibarr 14.0.0 beta

**Comment by soerpoers** [comment]
Hey @aschio – is it not possible that you register on transifex and adjust the translation? then this "bug" can finally be checked off. i myself translate for german and unfortunately do not know italian, so it does not make much sense if i would do it there. thank you

**Comment by aschio** [comment]
MO - "MODENA" is now ok, but IM --> "Instant Messaging" is not ok. I didn't find key to translate it...Do you know it?

**Comment by aschio** [comment]
I found key: "IM" but it is used in takepos module into phone.php. I can't translate it as italian city "Imperia". What do you suggest?

**Comment by soerpoers** [comment]
Which category? But didn't you suggest Imola?

**Comment by aschio** [comment]
Imperia not Imola sorry... :)
If I put "Imperia" as translation of "IT" key, in takepos module "IT" translation would be wrong.

To fix all, we would have to use 2 different key.

**Comment by soerpoers** [comment]
Can it be that you just have to put it in the glossary of transifex as an alternative?

**Comment by aschio** [comment]
Translation Bug on IM = IMPERIA is still there
