### ISSUE TITLE
Keep filled fields when there's an error submitting a vendor price

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#13975]
# Feature Request
When you miss a required field while completing a vendor price, and hit submit, the page will reload in a blank state, since it was submitted to the server and the server rejected it. This means you've got to fill all the data again from scratch. Keeping the data there would be a big time save.

## Use case
When non-technical staff use this program (sales/purchasing people) we can't expect them to have the full technical expertise from IT staff. They will often forget to fill every required field. When this happens, the form reloads in a blank state, and they have to start anew. They often request that when they make a mistake, the program should warn them, but not force them to start anew.

## Suggested implementation
Implement client side validation for forms. This doesn't need to be full validation, just checking that all required fields are filled before submission.

**Comment by dpriskorn** [comment]
Sounds like a good idea. Does Dolibarr use jQuery?
Where is the current js code located?

**Comment by dpriskorn** [comment]
still relevant?
