### ISSUE TITLE
A Vulnerability security External users

### ISSUE THREAD

**Issue by sam-anam1** [Dolibarr/dolibarr#13983]
Hello @eldy I hope you all are well, 

The external users can sending an emails from their login dashboard, which must not allow to the external customers to send emails to themself or to anyone as they was able to show print page button or downloads PDF.

We acutely made permissions for list of groups to our clients and we gives only permissions for those modules only 
(- Read & create customer orders,
        • Read customer invoices, 
        • Read projects and tasks, 
        • Read third parties linked to user, 
        • See & Modify tickets ) 

notice the ticket module it doesn't even shows in the users end yet to users portal while we activated in Group permissions or even in user permissions.

The goal was only that clients can view their  projects, invoices or making order, ticket for supporting from one place!

We found that the customers can and be able to send emails, to would behaving our/system email. and we tested with 10~12 Version,  and we think the external users on the Dolibarr system shouldn’t have right to use or send emails by that buttons on any of modules.

I have had created issue in GitHub earlier 2018, but wasn’t solved yet.

However I have attached pictures from the user portal for more clarification.

Thank you for your attention to this matter, 

![image0](https://user-images.githubusercontent.com/6969182/83066222-62577680-a06d-11ea-8bfc-6388458056e3.PNG)
![image1](https://user-images.githubusercontent.com/6969182/83066242-697e8480-a06d-11ea-90b4-6a9ab0b2369c.PNG)
![image2](https://user-images.githubusercontent.com/6969182/83066251-6be0de80-a06d-11ea-8c67-8917fc451d55.PNG)
![image3](https://user-images.githubusercontent.com/6969182/83066255-6e433880-a06d-11ea-8866-839fe3dfca8e.PNG)
![image4](https://user-images.githubusercontent.com/6969182/83066265-713e2900-a06d-11ea-98ac-0cbda505e015.PNG)
![image5](https://user-images.githubusercontent.com/6969182/83066273-74391980-a06d-11ea-9be1-43206f62fcd3.PNG)
![image6](https://user-images.githubusercontent.com/6969182/83066278-769b7380-a06d-11ea-943c-20cd40f7e491.PNG)
![image7](https://user-images.githubusercontent.com/6969182/83066293-7b602780-a06d-11ea-9192-bf179cd358af.PNG)

**Comment by eldy** [comment]
Creating an event may be something useful, even for an external user. It can be used to save something done or todo, or a remind for tracking reasons.

However, i agree that feature to send email for external user may be disabled for external user...

**Comment by ToniTen** [comment]
Actually, it would also be interesting to restrict access to emails from the server for internal users. Not every user needs to be able to send emails from Dolibarr!

For example, we use an external accountant, who we want to give access to the all invoices (this he needs to be an internal user, not an external user), but we don't want to give him access to sending emails in the name of the company. We don't want to give him access to sending emails from his own user, either!

**Comment by sam-anam1** [comment]
> Creating an event may be something useful, even for an external user. It also so same something done, a remind for tracking reasons.
> 
> However, i agree that feature to send email for external user may be disabled for external user...
@eldy 

True, but I think for **EVENT** should be appeared if the event/agenda module allowed when admin gives permissions to the users / groups.. that's make sense to me. but looks like the event is stuck.

**Comment by sam-anam1** [comment]
And one more thing.. it would be greatly appreciated if possible to split the **(add/edit)** 
for users permissions, 

which we can allow the customers to create an orders/projects, or **TICKET** but customers can't edit (close or open) the previous orders or **tickets**!.

**Comment by eldy** [comment]
This ticket is still open with no progression because it contains to many different topics (s with no chance to being processed by any body, so i close it in hope to have instead several smaller ticket (on for each minor change) to increase chance to have it processed by a contributor...
