### ISSUE TITLE
Bug: Sales Journal Registration

### ISSUE THREAD

**Issue by fcarll** [Dolibarr/dolibarr#13982]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When trying to journalize the Sales Journal, I keep getting  "Account for VAT not defined (Sale)" for one of my Sales Orders. 

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: apache2handler 7.2.31-1+ubuntu16.04.1+deb.sury.org+1
- **Database**: MySQL or MariaDB 5.7.30-0ubuntu0.16.04.1
- **URL(s)**: /accountancy/journal/sellsjournal.php?id_journal=1

## Expected and actual behavior
The only time this problem has manifested itself was on a Sales Order that had more than one item that is taxed. When I create a dummy sales order with only one taxed item [using the same sales tax definition] there is no problem.

## Steps to reproduce the behavior
Have a sales order with two items that are taxed.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Dolibarr#1](https://user-images.githubusercontent.com/58856710/83057802-68296980-a025-11ea-966d-2db369b660bd.JPG)

**Comment by atm-maxime** [comment]
Did you check the setup to link an account to the 5.917 tax ? Seems to me that it's just a missing setup...

**Comment by fcarll** [comment]
That was the first thing that I tried. I have several other tax rates defined in the VAT Dictionary  [see attached}

**Comment by atm-maxime** [comment]
Sorry I don't see any attachment. Can you post your screenshot on github ?
