### ISSUE TITLE
api_thirdparties got an Error in its sql

### ISSUE THREAD

**Issue by RafTim** [Dolibarr/dolibarr#13994]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Error in SQL Syntax near 'societe'

## Environment
- **Version**: 12.0
- **OS**: linux
- **Web server**: Dolibarr REST API
- **PHP**: 7.4.6
- **Database**: mariadb
- **URL(s)**: https://doliurl.comain/api/index.php/thirdparties

## Expected and actual behavior
Expected: Get Thirdparties, 
actual: Error in SQL Syntax 

## Steps to reproduce the behavior
[*Verbose description*]
curl -X GET --header 'Accept: application/json' --header 'DOLAPIKEY: PERSONALKEY' 'https://doliurl.comain/api/index.php/thirdparties?sortfield=t.rowid&sortorder=ASC&limit=100'

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hi,

Could you confirm that the FIX is ok ?
