### ISSUE TITLE
Computed field on product cannot fetch object

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#13997]
Hello, 

## Short description

I had an issue while reloading a Product object in a computed field : the product list stopped right before displaying the said computed field of the first product.

After a few tests it seems that it was due to the part `reloadedobj->fetch($obj->rowid)`

## long description

I had a computed field showing TTC price, the faulty computed field was 

```php
(($reloadedobj = new Product($db)) && ($reloadedobj->fetch($obj->rowid) > 0)) ? $reloadedobj->price*(1+$reloadedobj->tva_tx/100) : 0
```
After a few test i determined that the issue was due to the `$reloadedobj->fetch(...)` statement, replacing `$obj->rowid` by an existing rowid was not fixing the issue, doing the fetch on an other object `Societe` for instance "worked".

Avoiding the fetch statement with this field is working :

```php
(($reloadedobj = $db->fetch_object($db->query('SELECT * FROM '.MAIN_DB_PREFIX.'product as p WHERE rowid = '.$obj->rowid))) && $reloadedobj->rowid > 0) ? $reloadedobj->price_ttc : 0
```
Also commenting the line 2159 of `htdocs/product/class/product.class.php`:

```php
$this->fetch_optionals();
```
Seems to fix the issue althought it does not looks like a good idea.

I also tried it on a Dolibarr 11.0.4 instance with a totally different database : both version works while the line `this->fetch_optionals()` is still there, so either there was a change on this method or the issue is due to one of the extrafields on this instance.

The faulty extrafield is the only computed extrafield, there is a screenshot of all the extrafields on the faulty instance:

![image](https://user-images.githubusercontent.com/2989133/83187051-d2c5cc80-a12d-11ea-8c61-51f32c31fa3f.png)

## Technical info

+ Dolibarr : 10.0.7
+ Apache : Apache/2.4.38 (Debian)
+ php : 7.3.14-1~deb10u1
+ OS : Debian GNU/Linux 10

**Comment by ksar-ksar** [comment]
Hi,

Have you tried $object instead of $obj ?
`reloadedobj->fetch($object->rowid)`

**Comment by dbeniamine** [comment]
> Have you tried $object instead of $obj ?
> `reloadedobj->fetch($object->rowid)`

Yes, the problem is not from `$object->rowid` but on the fetch, actually I had a problem `$obj` VS `$object` : the workaround proposed above was working on lists but not on cards, so there is the current version:

```php
(($reloadedobj = $db->fetch_object($db->query('SELECT * FROM '.MAIN_DB_PREFIX.'product as p WHERE rowid = '.$obj->id ? $obj->id : ($obj->rowid ? $obj->rowid : $object->id)))) && $reloadedobj->rowid > 0) ? $reloadedobj->price_ttc : 0
```

**Comment by dpriskorn** [comment]
I suggest making a copy of the instance and upgrading that to see if it solves the issue.

**Comment by dbeniamine** [comment]
It works fine on 12.0.1 on a test instance where I whas able to reproduce the bug for 11.x, so I guess we can close the issue, I'll reopen if needed
