### ISSUE TITLE
Paying taxes or salary with different currency -> Report "Accounting year result" wrong

### ISSUE THREAD

**Issue by alexolait** [Dolibarr/dolibarr#14018]
# Bug
Report "Accouting year result" wrong when we pay taxes or salaries with other currency than the default

## Environment
- **Version**: 10.0.3
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 5.7
- **Database**: MySql 5.7.27
- **URL(s)**: [*Affected URL(s)*]
compta/sociales/card.php?action=create
compta/resultat/index.php?leftmenu=report&mainmenu=accountancy
## Expected and actual behavior
When we pay tax with different currency account the report "Accounting year result" is wrong
We cannot select currency when we pay taxes, even if you select your account with the good currency (not the default"

I have account with differnt currencies, and when i pay taxes without the default currency account, the amount of default currency is debited. So the report is wrong because Dolbarr use the default currency.

## Steps to reproduce the behavior
Add taxe
Select your account not with the default currency of dolibarr and add the taxe
Report will be wrong, because there is no conversion because amount is debited with a wrong currency.
This is the same problem with salaries

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
Addin taxes page
![Annotation 2020-06-01 182013](https://user-images.githubusercontent.com/22803868/83435697-94cdee80-a434-11ea-928f-924608199fd1.png)

Details report page
![Annotation 2020-06-01 182351](https://user-images.githubusercontent.com/22803868/83436038-19b90800-a435-11ea-8693-3e3a2fbccd46.png)

**Comment by ksar-ksar** [comment]
Hello,

Could you check with newer versions of Dolibarr (V13) ?

**Comment by alexolait** [comment]
Hello Ksar,
We upgraded Dolibarr in 13.0.2 but the problem still here

**Comment by alexolait** [comment]
We still have the same problem even in 14.0.2
When we pay taxes or salaries, the amount doensn't follow the bank account currency but stay with the default currency of Dolibarr
Example: 
Dolibarr work by default with Dollar
We have 2 account, one in € and one in $
I have to pay 1000€ for an employee
When i fill in the salary fileds i have to write the amount (it's not possible to precise the currency: so it's the default currency)
Next i select account to register the paiement, and if the account is not with the default currency of Dolibarr, all financial statistics will be wrong. All the expenses are in default currency with wrong amount, there is no conversion

**Comment by tescsonaa** [comment]
Hello, 
Got the same problem. Also, the Miscellaneous payments is missing in the report.

**Comment by lmag** [comment]
Still available in 17-beta
![image](https://user-images.githubusercontent.com/3288514/204113044-b31faa5f-76b5-426f-a2d0-275485ed303e.png)

**Comment by alexolait** [comment]
Bug toujours présent
