### ISSUE TITLE
v13.x - Crash when show stats for tasks for an external user

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#14023]
# Bug
When an external users show stats in tasks, there is a crash

## Environment
- **Version**: 12.0.1
- **OS**: Debian 10.4
- **Web server**: nginx 1.19.0
- **PHP**: 7.3.14
- **Database**: PostgreSQL 11.7
- **URL(s)**: /projet/tasks/stats/index.php?leftmenu=projects

## Expected and actual behavior
Expected : When an user see the page stats for tasks, it's ok.
Actual : There is a crash. You can see attachment at the end of this report.

## Steps to reproduce the behavior
Admin :
Create an external user
Create an project
Put this user in this project
Close project

User external :
Connect
See the page stats of tasks

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[taches-ko.pdf](https://github.com/Dolibarr/dolibarr/files/4718634/taches-ko.pdf)

**Comment by ludovicandrieux** [comment]
Still present in 12.0.1

**Comment by ksar-ksar** [comment]
Hello,

Could you check on V12.0.5 or V13.0.2 ?

**Comment by ludovicandrieux** [comment]
Hello,

I test on 13.0.4 and there is always this bug.
![2021-07-28_163903](https://user-images.githubusercontent.com/11213740/127342093-67419300-3462-45f4-90e5-a1d384d55e17.png)

**Comment by ksar-ksar** [comment]
Hello,

The `fk_soc `should be in the table `llx_ticket`, it is there since the begning.
Could you check the `llx_ticket` table to see if  `fk_soc ` exist ?

**Comment by ludovicandrieux** [comment]
Hello
Here informations you asked
I am on PostgreSQL 11.12 and my first Dolibarr is 10.0.0
![2021-07-28_193303](https://user-images.githubusercontent.com/11213740/127369704-644c8163-d8eb-47e6-af49-79829ad42168.png)

**Comment by ludovicandrieux** [comment]
> Hello,
> 
> The `fk_soc `should be in the table `llx_ticket`, it is there since the begning.
> Could you check the `llx_ticket` table to see if `fk_soc ` exist ?

Hi
I take time to see the bug and the problem is in llx_projet_task and not in llx_ticket as you ask first.
The describe of llx_projet_task confirms that colum doesn't exist. Peuharps a problem at the creation with Postgres ?

![image](https://user-images.githubusercontent.com/11213740/129030130-1922bb00-233b-424d-a435-d5a90f7edb3c.png)

**Comment by ludovicandrieux** [comment]
Closed with posterior bug #18375
