### ISSUE TITLE
Unchecked extrafield checkboxes will not be updated when not checked

### ISSUE THREAD

**Issue by Tim-Otte** [Dolibarr/dolibarr#14020]
# Bug
If you try to uncheck an extrafield checkbox in the product supplier prices it will not be updated. In html, unchecked checkboxes will not be sent in the request, so the backend does not know the value has changed.

I propose to fix this issue like in this StackOverflow answer: https://stackoverflow.com/a/1992745. If you prepend a hidden input field with the same name as the checkbox, the correct value will be used by the backend.

## Environment
- **Version**: develop
- **OS**: Ubuntu 18.04.4 LTS
- **Web server**: Apache/2.4.29
- **PHP**: PHP 7.2.24-0ubuntu0.18.04.6
- **Database**: mysql  Ver 15.1 Distrib 10.1.44-MariaDB
- **URL(s)**: At least /product/fournisseurs.php?id=???&socid=???&action=update_price&rowid=???

**Comment by ksar-ksar** [comment]
Hi,

Could you check on actual stable version V13 ?
