### ISSUE TITLE
Supplier dispatch "receipt"

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#14024]
# Feature Request
This would be useful when you receive products from a supplier to have a "receipt card"
that have the same behaviour as customer "shipment card"

I saw that the behaviour of supplier and customer stock movements are getting closer, but I would like to know if it is a future implementation.

Example of use cases : 

When your supplier invoices you 2 different supplier orders on a same invoice, you have to manually link one of the supplier orders to the invoice and re-type all the products linked to the second order.

You can create supplier invoices based on "receipt card", same behaviour when you invoice your customer shipments (like one ATM consulting module I guess named expéditions facturables or invoiceable shipments).

**Comment by dpriskorn** [comment]
Hi Bebz. I just added handling of supplier orders and invoices to my Dolibarr Python API. It can help you avoid the manual typing and linking you describe. Please contact me if you are interested at egils@riseup.net.

**Comment by atm-maxime** [comment]
Hi @BebZ 
The new "Reception" module answer your request, am I right ?
;)

**Comment by BebZ** [comment]
True ! Thanks for pointing me out this was a subject not closed :) Well done
I did not test yet : 
Create supplier invoices based on 2 "receipts cards", same behaviour when you invoice your customer shipments (like one ATM consulting module I guess named expéditions facturables or invoiceable shipments

did you ? 

Cheers !

**Comment by atm-maxime** [comment]
No you're right, this is not possible yet to create one invoice for several selected receptions. But it's also not possible on the customer side with shipments (apart from our ship 2 bill module).
