### ISSUE TITLE
Bug: Dolibarr 12.0.0-beta  don't load chart of accounts SKR03 (DE)

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#14033]
# Bug
New Dolibarr 12.0.0-beta don't load anymore the right chart of accounts type SKR03, 
only (3) accounts. 
At Dolibarr 11 and earlier it works and it loads (2572) accounts.
 
(always testet on same system as brand new installation)

## Environment
- **Version**: 12.0.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.2.31-1+0~20200514.41+debian9~1.gbpe2a56b
- **Database**: MySQL or MariaDB 5.5.5-10.1.44-MariaDB-0+deb9u1
- **URL(s)**: /dolibit/test/intern/dolibit-12/htdocs/admin/ihm.php?mainmenu=home

**Comment by eldy** [comment]
SKR03 should be ok with v12 but i had to disable most lines of SKR04 because the field account_parent is wrong into the file llx_accounting_account_de.sql that define list of accounts for SKR04.
