### ISSUE TITLE
Unique serial number

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#14039]
I don't know what is the expected behavior of the serial number feature in dolibarr 11.0.3  but when I assign a serial number to a product in stock and sell the product via sales order and ship that I can assign the same serial number again. Is there any way to handle unique serial numbers to keep track of products even when they are sold?

**Comment by dolibit-ut** [comment]
Hello, I think it is not a bug. The standard series / batch module does not have many functions and tries to work a little bit for a wide range of applications. Not everybody has unique serial numbers, others use that module for lots/batches ...

If you have higher demands on the use of serial numbers, you should look around in the dolistore. 
I also bought an extra module there.

Or you try it with ExtraFields at the standard module: 
You can add a field and define this as unique.
