### ISSUE TITLE
MAIN_PDF_PROPAL_USE_ELECTRONIC_SIGNING	doesn't work

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#14038]
# Bug
The hidden option MAIN_PDF_PROPAL_USE_ELECTRONIC_SIGNING does not work, in all the versions that I have tried, it has not worked in any, the last one, version 12.0.0 (alpha). The link is added correctly in the proposals tab, and when you click on the link, you will be directed correctly to the indicated page. However, both in version 8.0.4, as in 9.0.1, or 10.0.4, as well as alpha version 12, in none is added any button, drop-down list, option, to approve or reject propals. So we consider that either the module has not been finished (that is why it is still a hidden option), or it has an error. In any case, I wanted to report it in case the developers were unaware of this situation.

A cordial greeting.

Juan Brillo

la opcion oculta MAIN_PDF_PROPAL_USE_ELECTRONIC_SIGNING no funciona, en todas las versiones que he probado, no ha funcionado en ninguna, la ultima, la version 12.0.0 (alpha). Se añade correctamente el enlace en la pestaña de propuestas, y al hacer clic en el enlace, se dirige correctamente a la pagina indicada. No obstante, tanto en la version 8.0.4, como en la 9.0.1, o la 10.0.4, asi como la version alpha 12, en ninguna se agrega ningun boton, lista desplegable, opcion, para aprobar o rechazar los presupuestos. Por lo que consideramos que o bien el modulo no se ha terminado (por eso de que aun es una opcion oculta), o bien tiene un error. En cualquier caso, queria reportarlo por si los desarrolladores desconocian esta situacion

Un cordial saludo.

Juan Brillo

## Environment
- **Version**: 8.0.4, 9.0.1, 10.0.4, 12.0.0]
- **OS**: OpenSUSE 42.3, OpenSUSE Leap 15.1
- **Web server**: Apache
- **PHP**: 5.6.40, 7.2.5
- **Database**: MariaDB 5.5.5-10.0.35, MariaDB 5.5.5-10.2.31
- **URL(s)**: localhost

**Comment by eldy** [comment]
A hidden "option" are in fact "development option". It means the feature is not yet finished to be developed, so it is not working yet.
This feature will be  implemented in a future version.
