### ISSUE TITLE
[Request] Can be get a separate Repository for Dolibarr issues?

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#14046]
Hello,

I have notice that the UBlock repository here in Github, have moved his issues to separate Repository. 

https://github.com/gorhill/uBlock/issues/3726

The reason is to give the community users more rights on it, without breaking the rights on the code Repository.

IMHO I think that where a good idea for Dolibarr too.

With this more users can can do cool stuff, like
* Issues: add/remove tags, close, re-open, (edit headline), (self-)assignment, ...
* Milestones: (create milestones), move issues into and between it, backlog, ...
* Project: create custom todo's for each users, epic project/module goals, move issues into and between it.
* Later: add GitHub actions to automatically tag (new) issues

@eldy 
What do you think about it?

**Comment by eldy** [comment]
What happen if you make a commit in main repository with Close #ID-OF-ISSUE ?

I suppose this breaks this very important feature ?

Also what is the goal ? the points you mention seems already possible today ?
 - Users can already add tag Bug or Feature when creating an issue, and we don't really need other "open" tags for the moment as we experience this already in the past and we know that if a tag is not mandatory, it is often not filled so not reliable and useless)
- We do not use project (this may change but for which purpose ?) and if we do, we can use it in main project.
- We already have automatic github actions to tag and close automatically issues, no need to have a separated repository for that.
