### ISSUE TITLE
Breaking change inside files library on Dolibarr 11.x

### ISSUE THREAD

**Issue by AXeL-dev** [Dolibarr/dolibarr#14050]
Hello,

while trying to fix an issue related to dolibarr 11.x on one of my modules, i noticed that some parts of code in `files.lib.php` have been commented for no valuable reason. You can find the related parts of code just below:

https://github.com/Dolibarr/dolibarr/blob/5dd9f4e4c4e8b5a950ecd20549b0825c4421415f/htdocs/core/lib/files.lib.php#L2971-L2984

So i was really wondering, is there any checks done by the team when accepting pull requests from other developers or when proceeding to a breaking change? 'cause commenting code like that with no explanation (at least a comment line explaining the reason) & with no verification will mainly lead to more breaking changes & more bugs..

Finally, i'm not here to complain but i think that some checks should be done on each new release to avoid that kind of dumb issues. I also recommend to get back those parts of code 'cause many modules using the `perm` or `subperm` parameters when doing a request to [`viewimage.php`](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/viewimage.php) file might be concerned.

Thanks for the great job anyway.

**Comment by atm-maxime** [comment]
Hi @AXeL-dev !
Thanks for your feedback. You say there's no valuable reason for this change. Did you check the PR / commit that introduced this ? I found that this doesn't come from a PR but from this commit done by @eldy : d465101ae379cf19496914bcb1c75a25800763a1
So I think asking him the valuable reason would be a good start if the commit is not explicit enough.

Of course pull requests are reviewed before merging. Sorry if this change bothered you, sometime we can miss things...

@eldy can you explain the change you made here ?

**Comment by AXeL-dev** [comment]
Hey @atm-maxime !

Thanks for your kind answer. Well, i certainly didn't take time to verify the origin of the change, but anyway, i'll try to check that with @eldy, thanks again.

> Of course pull requests are reviewed before merging. Sorry if this change bothered you, sometime we can miss things...

That's okay, we all mess up sometimes.

**Comment by eldy** [comment]
Yes, this part of code is a serious security hole allowing anybody to bypass any permissions on modules by providing the permission the attacker want to check on url.
If an url request permission for module abc to have access to files of module abc, permission must be done according to module abc and not according to a key provided by user itself.

**Comment by AXeL-dev** [comment]
@eldy I'm still not fully convinced, can you please provide an example? For me, since we must mandatory provide the `modulepart` parameter, there is no way to access another module files without having the permissions you're providing in the parameters.
