### ISSUE TITLE
[ TakePos ] Mixed-content error

### ISSUE THREAD

**Issue by pierrejego** [Dolibarr/dolibarr#14055]
# Bug
[*TakePos Connecter Https error*]

## Environment
- **Version**: [*11.03*]
- **OS**: [*Debian9*]
- **Web server**: [*Apache*]
- **PHP**: [*PHP 7.2*]
- **Database**: [*Mysql*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
On our instance, we have pass Dolibarr over https, but call to takepos printer is in http, this result to an error http over https, Mixed Content : This request has been blocked; the content must be served over HTTPS. 

## Steps to reproduce the behavior

Open takepos 
dolibarr/htdocs/takepos/takepos.php?idmenu=38&mainmenu=takepos&leftmenu=
Click on "ouvrir le tiroir caisse"
Nothing appends and an error occurs in browser console

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
*https://github.com/Dolibarr/dolibarr/blob/ab176cd078135980a6943a96330f9c522a57fe5f/htdocs/takepos/index.php#L636
*https://github.com/Dolibarr/dolibarr/blob/ab176cd078135980a6943a96330f9c522a57fe5f/htdocs/takepos/invoice.php#L643
*https://github.com/Dolibarr/dolibarr/blob/ab176cd078135980a6943a96330f9c522a57fe5f/htdocs/takepos/invoice.php#L632*

To tempory fix the issue we allow mixed content in https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

**Comment by eldy** [comment]
@andreubisquerra Did the takepos connector support https call ?
If yes, we can replace all
  url: 'http://<?php print $conf->global->TAKEPOS_PRINT_SERVER; ?>:8111/print',
into
  url: '//<?php print $conf->global->TAKEPOS_PRINT_SERVER; ?>:8111/print',

**Comment by andreubisquerra** [comment]
TakePOS connector does not support https.
And there is no plan to support it.
Because my proposal is to discontinue TakePOS connector in Dolibarr 13 and set 'Receipt Printer' module as stable.
I think it is better replace TakePOS connector by 'Receipt Printer'
In my opinion 'Receipt Printer' module is more stable, with more possibilities, more compatible and easier to use and customize.
What do you think @eldy ?

**Comment by eldy** [comment]
If know better this pointthan me.
So solution, before receipt printer is ok, is the workaround to tempory fix the issue by allowing mixed content as explained here https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

**Comment by andreubisquerra** [comment]
Solved with new TakePOS connector avaiable from Dolibarr 13
https://github.com/Dolibarr/dolibarr/pull/15376
