### ISSUE TITLE
Allow due date for invoices to be blank

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#14065]
## Use case
When an invoice is fully paid before the actual invoice is generated (either against a deposit invoice, or through credit) is is interesting to not have a due date on the invoice documents. In my case, we use FACTURE_DEPOSITS_ARE_JUST_PAYMENTS to make deposit invoices into payments, so this is doubly useful.

The problem is, when trying to set the due date to blank, the system complains that due date can't be earlier than invoice date.

**Comment by atm-maxime** [comment]
Problem is that, at least in France, the due date is a mandatory information to have on the invoice...

**Comment by ToniTen** [comment]
Even if it was paid before the invoice date? I guess you could have this option hidden behind a setup other flag, I guess.

**Comment by dpriskorn** [comment]
I think it is the same in SE. Invoices need a due date.
