### ISSUE TITLE
Import assistant for Bill of Material (BOM)

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#14069]
# Feature Request

an import function for bill of materials (BOM)

**Comment by StephaneLesage** [comment]
+1
There is Export, but no Import.
I will not be able to migrate from our current ERP

**Comment by cococococococo** [comment]
I agree, a ton of modules being developped for stuff we don't need but BOM IMPORT is inexistant and just a must !

**Comment by schwartauch** [comment]
+1
it would help a lot to import csv files to BOM
