### ISSUE TITLE
Bug: Project Opportunity staatus in version 11.04

### ISSUE THREAD

**Issue by p-abella** [Dolibarr/dolibarr#14063]
# Bug
When Opportunities is active on projects, opportunity statuses are not loaded into project creation form

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 5.6.40
- **Database**: MySQL or MariaDB 10.3.23-MariaDB
- **URL(s)**: /dolibarr/projet/card.php?leftmenu=projects&action=create

## Expected and actual behavior
On creating opportunity projects, the opportunity status is not shown on the project creation form, it is not shown on the project list screen, and is not added into the project database record.

## Steps to reproduce the behavior
The Opportunity status is not presented on the opportunity creation form, neither on the  open opportunities list.

## Report
I modified 2 files in order to get the opportunities working:
dolibarr/projet/card.php
dolibarr/core/class/html.formprojet.class.php

Modifications made:
dolibarr/projet/card.php: line  163:
//PAB+ (opp_status must be recovered from form fields)
//         $object->opp_status      = $opp_status;
           $object->opp_status      = GETPOST('opp_status');
//PAB-

dolibarr/core/class/html.formprojet.class.php: line  628:
//PAB+ (position is not a field of c_lead_status table)
//          $sql.= " ORDER BY position";
            $sql.= " ORDER BY rowid";
//PAB-

dolibarr/core/class/html.formprojet.class.php: line  639:
//PAB+ (a final quotation is missed in select name)
//         $sellist = '<select class="flat oppstatus'.($morecss?' '.$morecss:'').'" id="'.$htmlname.'" name="'.$htmlname.'>';
            $sellist = '<select class="flat oppstatus'.($morecss?' '.$morecss:'').'" id="'.$htmlname.'" name="'.$htmlname.'">';
//PAB-

**Comment by eldy** [comment]
In you comment you say position is not a field of c_lead_status table
According to code and sql of v11. It is.
Are your sure you are speaking about the default feature opportunity and not the opportunity of an external module ?
Also, i can't reproduce the bug with v11.

**Comment by p-abella** [comment]
I recheck all the code and databases.
I seems the update (I'm not sure which one) did not update all the tables.
My llx_c_lead_status table does not have the position field.
My only clue is that on the table data, beside the absence of the position field, the record with rowid=2 has the followind fields
rowid=2
code='CIFF'
label='Chiffrage'
instead as the record defined in the installation tables:
rowid=2
code='QUAL'
label='Qualification'
My clue is that on some of the updates, the update of the llx_c_lead_status table was forgotten

**Comment by dpriskorn** [comment]
Try updating to v12 if the problem persists.
