### ISSUE TITLE
we can't disconnect on md theme

### ISSUE THREAD

**Issue by defrance** [Dolibarr/dolibarr#14076]
The new box present on eldy theme are not present on md mode theme
so we cant' disconnect on it

**Comment by ksar-ksar** [comment]
Hi,

Seems to have a fix here : https://www.dolibarr.fr/forum/t/dolibarr-v12-theme-md-disparition-du-bouton-de-deconnexion-aka-logout-contournement/33534/3

On file /usr/share/dolibarr/htdocs/theme/md/dropdown.inc.php#150
Comment the line « display: none »
