### ISSUE TITLE
Error when rounding the total line on documents / V 11.0.4

### ISSUE THREAD

**Issue by maho001** [Dolibarr/dolibarr#14079]
If the Flag MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND = 1 then the Totalline will not be rounded correctly, if the rule is 0.05

![image](https://user-images.githubusercontent.com/8641194/84563431-d70ffd80-ad5b-11ea-861f-1e76aaee146e.png)

**Comment by eldy** [comment]
If MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND is off and rule is 0.05 do you have trouble or only with combination
MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND set + rule of rounding = 0.05 ?

**Comment by maho001** [comment]
Hi eldy,

only with combination MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND set + rule of rounding = 0.05
