### ISSUE TITLE
Ref. commençant par SEE ne s'affichant pas sur les devis

### ISSUE THREAD

**Issue by NobleCathare** [Dolibarr/dolibarr#14071]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When a reference starts with "SEE", it is impossible to find the product when writing a quote. When I change the reference, for example PSEE, the problem is solved.

## Environment
- **Version**: 11.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.2.30
- **Database**: MySQL or MariaDB 5.6.47-log
- **URL(s)**: Confidential

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by Langlais115** [comment]
@NobleCathare 
I can't reproduce the issue. [result screenshot](https://i.imgur.com/HfIamvb.png)
Can you please provide more details on how to reproduce the issue?

**Comment by atm-maxime** [comment]
Can't reproduce either on a 11.0.5
