### ISSUE TITLE
Bug: Default approval did not apply to the draft expenses report

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14070]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
During creation of expenses report, the default approval did not apply to the draft expenses report. Suspect SQL not inserted.

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /expensereport/card.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![1](https://user-images.githubusercontent.com/52134143/84330369-c9bb0d80-abb9-11ea-82cf-5aafe7a3c294.PNG)
![2](https://user-images.githubusercontent.com/52134143/84330377-ce7fc180-abb9-11ea-88da-1dfc3a469a14.PNG)

**Comment by eldy** [comment]
Did you set the hidden option EXPENSEREPORT_DEFAULT_VALIDATOR_UNCHANGEABLE ?

**Comment by asolslk** [comment]
Hi Eldy, yes, it was set value to 1.
