### ISSUE TITLE
The member form does not send email 

### ISSUE THREAD

**Issue by FeliceCor** [Dolibarr/dolibarr#14082]
[video_dolibarr.mkv.zip](https://github.com/Dolibarr/dolibarr/files/4776489/video_dolibarr.mkv.zip)

 I am using Dolibarr version 11.0.4 installed on shared linux server.
The member form fails when sending email from the member tab as can be seen from the attached video screen attachment.
While from the third party module it works ok

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /htdocs/admin/ihm.php?mainmenu=home&leftmenu=setup

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
I tested with futur 11.0.5 and can't reproduce. Feedback once v11.0.5 has been released is welcome...

**Comment by ksar-ksar** [comment]
Hi,

Any feedback with newer versions of Dolibarr ?
