### ISSUE TITLE
Bug: Dolibarr 11 - with setting: PRODUCT_USE_UNITS 

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#14086]
# Bug
With setting  **PRODUCT_USE_UNITS**  a lot of commercial transactions dont work anymore.
You can only create a process up to the draft (PROV), but not edit it further.

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.2.31-1+0~20200514.41+debian9~1.gbpe2a56b
- **Database**: MySQL or MariaDB 5.5.5-10.1.44-MariaDB-0+deb9u1
- **URL(s)**: /dolibit/demo/htdocs/fourn/commande/card.php?ref=%28PROV3%29

**Comment by edupulpillo** [comment]
It seems that occurs in all the vendor proposals, purchase orders and vendor invoices.
In the part of the customer side, everything seems to work fine.

**Comment by dpriskorn** [comment]
Is this solved after upgrading to v12?

**Comment by edupulpillo** [comment]
After updating to the version 12.0.2 is working well in my side, (Sorry i did not check it in previous 12.0.0 and 12.0.1)

**Comment by dolibit-ut** [comment]
Thank you, i will test it soon.
