### ISSUE TITLE
TakePOS not working as before

### ISSUE THREAD

**Issue by gotttlieb** [Dolibarr/dolibarr#14087]
# Bug
[*Direct Payment disapeared TakePOS and payment without cuantity dosn't work*]

## Environment
- **Version**: [*10.0.7*]
- **OS**: [*Ubuntu 18.04.4 LTS*]
- **Web server**: [*Apache/2.4.29 (Ubuntu)*]
- **PHP**: [*PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11)*]
- **Database**: [*mysql  Ver 15.1 Distrib 10.4.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2*]
- **URL(s)**: [*localhost/dolibarr/takepos/takepos.php*]

## Expected and actual behavior
[*When click to payment, if no cuantity is set, get the same behaviour as before, and set the same amount that is requested, and set the bill to payed *]

## Steps to reproduce the behavior
[*Try to create a payment and don't set the cuantity [Direct payment has desapered]*]

**Comment by eldy** [comment]
I think this has been fixed into v11 :
A new option "Direct cash payment button" is available in setup pages. to retreive this feature.

**Comment by dpriskorn** [comment]
close this
