### ISSUE TITLE
Dolibarr 12.0.0-beta ReceptionValidated missing Origin Ref

### ISSUE THREAD

**Issue by pcworxstech** [Dolibarr/dolibarr#14094]
# Bug
Purchase Order ref number is not listed in "Origin" column. 
![reception_missing_origin_link](https://user-images.githubusercontent.com/54542571/84819479-0f2a7100-afe6-11ea-9a67-417761e9f780.jpg)

## Environment
- **Version**: Test bed -v12.0 beta
- **OS**: Ubuntu 18.04.4 LTS
- **Web server**: [*Apache*]
- **PHP**: 7.2.24
- **Database**: MariaDB 5.5.5-10.1.44-MariaDB-0ubuntu0.18.04.1
- **URL(s)**: https://www.trimmill.com/dolibarr_old/product/stock/movement_list.php?idproduct=2035

## Expected and actual behavior
Previous edition 11.0.3 had the Purchase Order Reception number listed in the Origin column. 

## [Attached files]
See attached highlighted picture.

**Comment by ksar-ksar** [comment]
Hello,

Could you check with V12.0.5 or V13.0.2 ?
