### ISSUE TITLE
Payment invoice breaks down on Other Settings: MAIN_ADD_PDF_BACKGROUND

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#14108]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
After adding payment to invoice system returns error:
Warning: file_get_contents(/logo1.pdf): failed to open stream: No such file or directory in /var/www/html/dolibarr-7.0.0/htdocs/includes/tcpdi/tcpdi.php on line 120
TCPDF_PARSER ERROR: Empty PDF data.

I tempory fixet the error by deleting my other setting: MAIN_ADD_PDF_BACKGROUND
This is also the reason for the breakdown.

## Environment
- **Version**:  12.0.0
- **OS**: Linux UBUNTU 16
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**:7.0.33-29+ubuntu16
- **Database**: MySQL or MariaDB 5.7.30-0ubuntu0.16.04.1

## Expected and actual behavior
Set invoice to paid and add payment to invoice.

## Steps to reproduce the behavior
Make an setting in MAIN_ADD_PDF_BACKGROUND

**Comment by fappels** [comment]
Hallo Klaas,

Seems to be introduced here on 11: https://github.com/Dolibarr/dolibarr/pull/11168
@hregis $conf->mycompany->multdir_output does not seem to exist?

**Comment by eldy** [comment]
What was the value of MAIN_ADD_PDF_BACKGROUND ?
Did you try to put a full path of file into this var ?

**Comment by KlaasOl** [comment]
It worked in 11.0.4 After I updated to version 12.0.0 it did not work any longer.
My setting in the field was: logo1.pdf
Changing it to the whole path did not make it work.

**Comment by ksar-ksar** [comment]
Hello,

Have you check in newer Dolibarr versions?
