### ISSUE TITLE
Bug: Product error on the pop up hover

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14111]
# Bug
1. Barcode not showing in the product popup during the mouse hover even the input is in place.
2. Accounting code show wrongly under the Sales - Intra Community
3. How to enable the Sales - Intra Community accounting code selection?

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /product/list.php?restore_lastsearch_values=1&type=0

![product](https://user-images.githubusercontent.com/52134143/85433270-c14dd400-b5b6-11ea-92b7-662792181941.png)
![saes](https://user-images.githubusercontent.com/52134143/85433795-8ef0a680-b5b7-11ea-8a7b-226182a8beb8.PNG)

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by asolslk** [comment]
Yes, still there

**Comment by dpriskorn** [comment]
Can you find the place in the source that generates this popup? If yes, please share a link to the line and I will take a look. (Clicking the line number gives access to a menu)

**Comment by ksar-ksar** [comment]
Have you checked with V13 ?
