### ISSUE TITLE
Infinite loop usinf branch and parent company !

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#14119]
# Bug
You can create an infinite loop between a branch and its parent company

## Environment
- **Version**: all versions

## Expected and actual behavior
If you select a parent company for a third party, you are able to define it as the parent company of its parent company.
Then, by updating the customer price of the branch from the price of the parent company, you create an infinite loop!

## Solution
Add this lines in ../htdocs/societe/class/societe.class.php (line 3005 to 3017 for Dolibarr 11.0.4) under function set_parent() :
`
// InfraS add begin (to avoid infinite loop)
$sqlverif	= 'SELECT s.parent';
$sqlverif	.= ' FROM '.MAIN_DB_PREFIX.'societe as s';
$sqlverif	.= ' WHERE rowid = '.$id;
$resqlverif	= $this->db->query($sqlverif);
if ($resqlverif)
{
	$obj_verif	= $this->db->fetch_object($resqlverif);
	setEventMessages('la maison mère choisie est déjà filiale de ce tiers', null, 'warnings');
	if ($obj_verif->parent != '')	return -1;
}	// if ($resqlverif)
// InfraS add end
`

Best regards.
Sylvain.

**Comment by eldy** [comment]
Does the fix work if the you select a parent company that has child of a child of a child (whatever is the level) ? Or does hte protection works only for for level 1 or 2 ?

**Comment by SylvainLegrand** [comment]
My first fix only works for 1 level.
I apologize for this mistake.
Here is the fix that works whatever the level :
`
    // phpcs:disable PEAR.NamingConventions.ValidFunctionName.ScopeNotCamelCaps
	/**
	 *    Define parent commany of current company
	 *
	 *    @param	int		$id     Id of thirdparty to set or '' to remove
	 *    @return	int     		<0 if KO, >0 if OK
	 */
    public function set_parent($id)
	{
        // phpcs:enable
		if ($this->id)
		{
			// InfraS cange (to avoid infinite loop)
			$sameparent				= $this->get_parents($id, $this->id);
			if ($sameparent < 0)	return -1;
			elseif ($sameparent == 1)
			{
				setEventMessages('la maison mère choisie est déjà filiale de ce tiers', null, 'warnings');
				return -1;
			}	// elseif ($sameparent == 1)
			else
			{
				$sql	= 'UPDATE '.MAIN_DB_PREFIX.'societe SET parent = '.($id > 0 ? $id : 'null').' WHERE rowid = '.$this->id;
				dol_syslog(get_class($this).'::set_parent', LOG_DEBUG);
				$resql	= $this->db->query($sql);
				if ($resql)
				{
					$this->parent	= $id;
					return 1;
				}	// if ($resql)
				else	return -1;
			}	// else	// elseif ($sameparent == 1)
		}	// if ($this->id)
		else return -1;
	}

    // phpcs:disable PEAR.NamingConventions.ValidFunctionName.ScopeNotCamelCaps
	/**
	 *    Search parent commany of current company
	 *
	 *    @param	int		$idparent	Id of thirdparty to check
	 *    @param	int		$idchild	Id of thirdparty to compare to
	 *    @return	int     		<0 if KO, 0 if OK or 1 if at some level a parent company was the child to compare to
	 */
    public function get_parents($idparent, $idchild)
	{
        // phpcs:enable
		$sql	= 'SELECT s.parent';
		$sql	.= ' FROM '.MAIN_DB_PREFIX.'societe as s';
		$sql	.= ' WHERE rowid = '.$idparent;
		$resql	= $this->db->query($sql);
		if ($resql)
		{
			$obj	= $this->db->fetch_object($resql);
			
			if ($obj->parent == '')				return 0;
			elseif ($obj->parent == $idchild)	return 1;
			else								$sameparent	= $this->get_parents($obj->parent, $idchild);
			return $sameparent;
		}	// if ($resql)
		else	return -1;
	}
`

As you can see I rewrote the "set_parent" function and added a new function named "get_parents".

Best regards,
Sylvain

**Comment by SylvainLegrand** [comment]
No, I apologize for that.

Here is a patch that works whatever the level : 
`
    public function set_parent($id)
	{
        // phpcs:enable
		if ($this->id)
		{
			// InfraS cange (to avoid infinite loop)
			$sameparent				= $this->get_parents($id, $this->id);
			if ($sameparent < 0)	return -1;
			elseif ($sameparent == 1)
			{
				setEventMessages('la maison mère choisie est déjà filiale de ce tiers', null, 'warnings');
				return -1;
			}	// elseif ($sameparent == 1)
			else
			{
				$sql	= 'UPDATE '.MAIN_DB_PREFIX.'societe SET parent = '.($id > 0 ? $id : 'null').' WHERE rowid = '.$this->id;
				dol_syslog(get_class($this).'::set_parent', LOG_DEBUG);
				$resql	= $this->db->query($sql);
				if ($resql)
				{
					$this->parent	= $id;
					return 1;
				}	// if ($resql)
				else	return -1;
			}	// else	// elseif ($sameparent == 1)
		}	// if ($this->id)
		else return -1;
	}

    public function get_parents($idparent, $idchild)
	{
        // phpcs:enable
		$sql	= 'SELECT s.parent';
		$sql	.= ' FROM '.MAIN_DB_PREFIX.'societe as s';
		$sql	.= ' WHERE rowid = '.$idparent;
		$resql	= $this->db->query($sql);
		if ($resql)
		{
			$obj	= $this->db->fetch_object($resql);
			
			if ($obj->parent == '')				return 0;
			elseif ($obj->parent == $idchild)	return 1;
			else								$sameparent	= $this->get_parents($obj->parent, $idchild);
			return $sameparent;
		}	// if ($resql)
		else	return -1;
	}
`

This patch add a new function named "get_parents".

Best regards.
Sylvain

**Comment by dpriskorn** [comment]
Could you submit a pull request with your patch?
