### ISSUE TITLE
Optional fields

### ISSUE THREAD

**Issue by isoscent** [Dolibarr/dolibarr#14129]
![optional fields](https://user-images.githubusercontent.com/8207126/85762104-72be4800-b724-11ea-969d-c516782a6aeb.jpg)

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by dpriskorn** [comment]
How is this different from extrafields? I have a lot of extrafields on my products e.g. picture_url, main_supplier_codename, etc.

**Comment by dpriskorn** [comment]
User unresponsive and we already have the suggested functionality with our extrafields.

**Comment by dpriskorn** [comment]
Closing, feel free to reopen if you can answer my question above
