### ISSUE TITLE
Features is gon

### ISSUE THREAD

**Issue by isoscent** [Dolibarr/dolibarr#14128]
<img width="960" alt="COAver11" src="https://user-images.githubusercontent.com/8207126/85748510-2d484d80-b719-11ea-99e2-c991ff46b4ae.png">
<img width="960" alt="COAver12" src="https://user-images.githubusercontent.com/8207126/85748523-2faaa780-b719-11ea-8ed5-0d61532718e5.png">

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Yes. The value in this column was not used by Dolibarr, so useless. So it has been removed.

**Comment by isoscent** [comment]
Mr. Eldy as you can see it on the picture how useful it is. Well It is okay as you said it has been removed. Thank you Sir

**Comment by dpriskorn** [comment]
Please close this.
