### ISSUE TITLE
Impossible de valider une facture avec une valeur négative pour un taux de TVA donné

### ISSUE THREAD

**Issue by sleprestre** [Dolibarr/dolibarr#14134]
Bonjour,
Pour le contexte : il m'est nécessaire d'ajouter des remises fixes avec TVA à 0% (remise gouvernementales). Cela doit apparaître sur la même facture que les travaux pour être conforme.

Comme l'illustre la capture d'écran suivante, il est impossible de valider la facture avec une ligne de remise fixe à 0% de TVA appliquée.

La remise fixe a préalablement été créée dans le TIers, puis utilisée dans la facture.

Dolibarr 11.0.4, bug reproduit sur une autre installation à l'identique. À dispo pour vous donner les détails nécessaires.

Merci d'avance de votre aide
Sébastien
![c92792bb](https://user-images.githubusercontent.com/65352241/85828293-53590680-b788-11ea-871f-70906dc17a48.png)

**Comment by eldy** [comment]
This has been fixed in v12.
Will be also available with v11.0.5
