### ISSUE TITLE
Bug: Paiement pour multiples clients rattachés à une même maison mère

### ISSUE THREAD

**Issue by jnoel974** [Dolibarr/dolibarr#14138]
# Bug
Il y a un soucis de création d'écritures bancaires et comptables lors de la saisie d'un paiement attaché à des factures de client multiples faisant partis de la même maison mère.

## Environment
- **Version**: 12.0.0
- **OS**: Linux
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: apache2handler 7.3.19-1+0~20200612.60+debian10~1.gbp6c8fe1
- **Database**: PostgreSQL 11.7 (Debian 11.7-0+deb10u1)
- **URL(s)**: /compta/bank/bankentries_list.php

## Actual behavior
La saisie du paiement se fait bien, mais lorsqu'on regarde les écritures en banque le paiement apparaît en double (pour chacun des clients en fait) (cf la capture sur les écritures en banque).
Le solde du compte bancaire n'affiche plus du tout le bon montant non plus.
Lorsqu'on regarde le journal de banque, les écritures se retrouve aussi en double et leur montant est également doublé (cf capture sur le journal de banque)

## Steps to reproduce the behavior
* Avoir deux clients attachés à la même maison mère
* Saisir un paiement regroupant des factures des deux clients
* Aller voir les écritures bancaires et le journal de banque

### Le paiement :
![Paiement](https://user-images.githubusercontent.com/57910727/85841889-d2ae0080-b7af-11ea-8779-8dd223c788fd.png)
### Les écritures en banque :
![Compte - Ecritures](https://user-images.githubusercontent.com/57910727/85841901-d772b480-b7af-11ea-80e4-cd2a5a74b852.png)
### Le journal de banque :
![Journal de trésorerie](https://user-images.githubusercontent.com/57910727/85841913-d9d50e80-b7af-11ea-93cd-3784b4488fe2.png)

**Comment by dpriskorn** [comment]
Could you please translate this to english? (the pictures are fine as they are)

**Comment by ksar-ksar** [comment]
Could you check if newer versions (V12.0.5 or V13.0.2) correct it ?
