### ISSUE TITLE
Dolibarr 12.0.0-alpha - Upgrade problem - Events in Projects

### ISSUE THREAD

**Issue by truefriend-cz** [Dolibarr/dolibarr#14149]
# Bug
Upgrade problem - Events list in Projects

## Environment
- **Version**: 12.0.0-alpha (committed 88cf904)
- **Database**: MySQL

## Expected and actual behavior
If upgrade from 11.x or 12.0.0 versions to 12.0.0-aplha then not view Events in Projects (lines is empty).

## Steps to reproduce the behavior
**in versions 11.x, 12.0.0**
1. Open Projects
2. Scroll down
3. Where is Events by Project is show normally

**After upgrade to version 12.0.0-alpha:**
1. Open Projects
2. Scroll down
3. Where is Events by Project is show events as empty lines (no names, no next items)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

**Events list (3) after upgrade (version 12.0.0-alpha):**

![Tasks](https://user-images.githubusercontent.com/7845691/86074369-1c376d80-ba86-11ea-92c3-9846971f4008.png)

**Comment by dpriskorn** [comment]
Can you update to the newest v12 and see if the problem persists?
