### ISSUE TITLE
Unable to upload an document in DMS/ECM

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#14148]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
After updating from 11.0.4 to 12.0.0. it is not possible to upload an document in DMS/ECM

## Environment
- **Version**: 12.0.0
- **OS**: LINUX 
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**:7.0.33-29+ubuntu16
- **Database**: MySQL or MariaDB 5.7.30-0ubuntu0.16.04.1
- **URL(s)**: [SERVER]/htdocs/ecm/index.php

## Expected and actual behavior
Possibility to upload an document. Got refused. Seems that I to have no rights to write. I got administrator rights.

## Steps to reproduce the behavior
Trying to upload an document. System does no accept due rights.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![afbeelding](https://user-images.githubusercontent.com/43514101/86022228-596e1200-ba2a-11ea-9c1c-8963a115d110.png)

**Comment by Metalicss** [comment]
Same problem when you try to upload a file in import module.

**Comment by dpriskorn** [comment]
> Same problem when you try to upload a file in import module.
Do you have the same problem? Is this a confirmation?

**Comment by dpriskorn** [comment]
> Possibility to upload an document. Got refused. Seems that I to have no rights to write. I got administrator rights.

Could you please add the log module to Dolibarr and include the relevant ERR lines from the log to help us debug?

**Comment by dpriskorn** [comment]
Cannot confirm. I also recently updated from 9->10->11->12. I just enabled ECM, created a directory and uploaded a file without any problems.
Can someone using v11 add ECM, upload a file, upgrade and try uploading a file too reproduce?

**Comment by Metalicss** [comment]
Problem solved after updating to dolibarr V12.0.2
