### ISSUE TITLE
Bug: MO number cannot be set and error was display.

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14153]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
MO number cannot be set and error was display without much details

## Environment
- **Version**: 12.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /comm/propal/card.php?id=65&save_lastsearch_values=1

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/86123371-f6ed4280-bb0b-11ea-8576-ccfd93b02910.PNG)

**Comment by dpriskorn** [comment]
Please add the logging module and add the output here.
