### ISSUE TITLE
Bug: Unit under the product display wrongly

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14152]
# Bug
Unit under the product display wrongly which showing unitEA instead of EA

## Environment
- **Version**: 12.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /product/card.php?id=123

![Capture](https://user-images.githubusercontent.com/52134143/86122817-028c3980-bb0b-11ea-80a1-e580007d9397.PNG)

**Comment by dpriskorn** [comment]
What does EA mean?

**Comment by asolslk** [comment]
EACH

**Comment by dpriskorn** [comment]
can someone reproduce this?

**Comment by asolslk** [comment]
Under the dictionary, measuring units, added EA2 as a new unit, and the result show EA2 as well.

![1](https://user-images.githubusercontent.com/52134143/89708255-e4d2af80-d9a7-11ea-9180-e2bc65c52887.JPG)
![2](https://user-images.githubusercontent.com/52134143/89708271-0cc21300-d9a8-11ea-97e1-f907a015e026.JPG)
![3](https://user-images.githubusercontent.com/52134143/89708274-10ee3080-d9a8-11ea-833b-f6b83dbd8ab3.JPG)
![4](https://user-images.githubusercontent.com/52134143/89708404-61b25900-d9a9-11ea-8278-845a519f6458.JPG)

**Comment by dpriskorn** [comment]
Congratulations! The pull request LGTM 😀

**Comment by asolslk** [comment]
Thanks for guidance.. Will help as much as i could. I am not expert

**Comment by ksar-ksar** [comment]
Hello,

Could you check on newer Dolibarr versions ?
