### ISSUE TITLE
Tax calculation can lead to wrong totals on 100% deposit invoices

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#14166]
# Bug
Tax calculation is done per line and rounded as per https://wiki.dolibarr.org/index.php/VAT_calculation_and_rounding_rules. However, when making a deposit invoice with a single line "deposit" worth 100% of the total, this can lead to differences between the totals of the two invoices.

## Environment
- **Version**: 11.0.4-12.0.0
- **OS**: OVH shared linux hosting (Linux webm332.cluster003.gra.hosting.ovh.net 4.14.154-ovh-vps-grsec-zfs-classid #1 SMP Wed Nov 13 11:24:26 CET 2019 x86_64) , reproduced in a Bitnami VM with Debian 10 (Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64)
- **Web server**: OVH shared linux hosting Apache, reproduced in a Bitnami VM with Debian 10 (2.4.43)
- **PHP**: OVH shared linux hosting PHP (7.2.31), reproduced in a Bitnami VM with Debian 10 (7.3.19)
- **Database**: OVH shared linux hosting database (MySQL or MariaDB 5.6.48-log), reproduced in a Bitnami VM with Debian 10 (MySQL or MariaDB 5.7.30)

## Expected and actual behavior
When you make a deposit invoice worth 100% of the total, you expect total with tax to be equal to the one of the originating order. However, due to the way that Dolibar calculated tax, the totals differ. This can result in small differences between deposits and invoice totals. 100% deposit invoices should take the tax totals from the order, instead of recalculating tax.

## Steps to reproduce the behavior
This is an example that displays this issue. This assumes Spanish VAT (21%) for the tax:
Create an order with 3 lines, all with 21% tax, 1 unit, and the following prices: 487.50, 18.75, 15. Total without tax should be 521.25. Tax will be 109.47. Total with tax should be 630.72.
Create a deposit invoice for 100% of the total. This will create a single line worth 512.25 without tax. Total without tax will be 512.25. Tax will be 109.46. Total with tax will be 630.71.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[CO2007-0002.pdf](https://github.com/Dolibarr/dolibarr/files/4858655/CO2007-0002.pdf)
[AC2007-0001.pdf](https://github.com/Dolibarr/dolibarr/files/4858654/AC2007-0001.pdf)

**Comment by ksar-ksar** [comment]
Hello,

You can try to use MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND
https://wiki.dolibarr.org/index.php?title=Setup_Other

**Comment by ToniTen** [comment]
I created a new VM to re-test this, and re-created the documents from the original report. This was tested on Dolibar 13

Setting MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND to 1 causes the total with tax for the order to be 630.71 and so matches the deposit invoice.

However, this option is not enabled by default, Setup Other clearly has this notice

> Some options are not visible in the interface (often because they are deprecated or are beta features). In most cases you do not need these functions and their use may make the application unstable. 

and so most people won't ever think about this until they are faced with a similar situation
