### ISSUE TITLE
Bug: ECM - Unable to upload file into the folder

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14167]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Unable to upload file into the folder. Verified the access right of the user, all was enabled and the user is an administrator, and the FTP to see the folder write, the right set at 775.

## Environment
- **Version**: 12.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**:  5.6.40-84.0-log
- **URL(s)**: /ecm/index.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/86263014-2e82ea00-bbf3-11ea-910e-e4986d98caea.PNG)

**Comment by ksar-ksar** [comment]
Hi,

You try to import ?
Link to that https://github.com/Dolibarr/dolibarr/pull/14126 ?
