### ISSUE TITLE
dolibarr 12.0.0 expedition (shipment) cant get extra_value

### ISSUE THREAD

**Issue by 1ocate** [Dolibarr/dolibarr#14161]
# Bug
dolibarr 12.0.0 expedition (shipment) cant get extra_value from 'Sales Orders'

## Environment
- **Version**: dolibarr 12.0.0
- **OS**: 3.10.0-1127.8.2.el7.x86_64
- **Web server**: nginx/1.14.2
- **PHP**: 5.6.40
- **Database**: mysql 5.7
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
when make shipment, from 'Sales Orders' line extra value can't get.
but if make invoice  get extra value.
 
## Steps to reproduce the behavior
[*Verbose description*]
Sales Orders -> add service or product -> shipment 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![Screen Shot 2020-07-01 at 15 09 54](https://user-images.githubusercontent.com/29521447/86220214-73842d80-bbad-11ea-87cd-650151916109.png)

when make shipment cant' get extra value.
![Screen Shot 2020-07-01 at 15 10 06](https://user-images.githubusercontent.com/29521447/86220209-6ff0a680-bbad-11ea-8adb-1afae2cd1a8e.png)

I tested 11.4, 11.5 all have this bug

**Comment by dpriskorn** [comment]
Can you update to v12 and see if the problem persists?

**Comment by dpriskorn** [comment]
I don't understand what you mean by extra value. Could you elaborate?
