### ISSUE TITLE
Dolibarr 12 When I import products from access denied

### ISSUE THREAD

**Issue by vincenzoriggi** [Dolibarr/dolibarr#14175]
# Bug
[*When I import products from access denied*]

## Environment
- **Version**: [*12.0.0*]
- **OS**: [*Linux*]
- **Web server**: [*Apache*]
- **PHP**: [*7.2.31*]
- **Database**: [*MySQL*]

**Comment by ksar-ksar** [comment]
Hi,

Corrected here : https://github.com/Dolibarr/dolibarr/pull/14126

**Comment by vincenzo-riggi** [comment]
> Hi,
> 
> 
> 
> Corrected here : https://github.com/Dolibarr/dolibarr/pull/14126

Sorry I hadn't seen that the topic had already been covered.  
Thank you very much
