### ISSUE TITLE
E-mail delivery follow-up doesnt work any longer

### ISSUE THREAD

**Issue by smartdavidle** [Dolibarr/dolibarr#14174]
# Bug
When using  __CHECK_READ__  to track e-mail delivery for mass e-mailing, the "read" status doesn't work any longer.

## Environment
- **Version**: [11.0.4]
- **OS**: [Linux, OVH hosted]
- **Web server**: [Apache]
- **PHP**: [7.2.31]
- **Database**: [MySQL]

## Expected and actual behavior
I've created an e-mail campaign, included "__CHECK_READ__" in the mail-text and sent the e-mails, works fine. Once the e-mails have been sent, the individual e-mail status changes to "sent", but does not change to "read" once the receiver has opened the mail.

**Comment by ksar-ksar** [comment]
Hello,

Have you checked in the source of the email that the URL for the check is good and accessible by non-registered people ?
