### ISSUE TITLE
Deposit with stripe issue

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#14178]
# Bug
Stripe issue for deposit (like #11218 #11150)

## Environment
**Version**: 9.0.x to 12.0.x

## Expected and actual behavior
When a customer uses Stripe to pay a deposit, an SQL error occurs.
Deposit creation fails due to an empty user ID.

## Solution
On file './htdocs/core/class/discount.class.php' under function 'create' the line `$userid = $tmpinvoice->fk_user_author;` should be changed to `$userid = $tmpinvoice->user_author;`

Best regards,
Sylvain.

**Comment by ksar-ksar** [comment]
Hello,

This has been fixed normally, can you check on newer dolibarr versions ?
