### ISSUE TITLE
Bug on Limits and accuracy

### ISSUE THREAD

**Issue by gavrielzs** [Dolibarr/dolibarr#14181]
# Bug
Cannot modify the Max. decimals for unit prices, Max. decimals for total prices and Max. decimals for prices shown on screen

## Environment
- **Version**: [*12.0.0*]
- **OS**: [*CentOS 7*]
- **Web server**: [*LiteSpeed*]
- **PHP**: [*7.2.31*]
- **Database**: [*mysqli (10.1.44-MariaDB)*]
- **URL(s)**: [*admin/limits.php*]

**Comment by philippec78** [comment]
Same bug

MAIN_MAX_DECIMALS_UNIT
MAIN_MAX_DECIMALS_TOT
MAIN_MAX_DECIMALS_SHOWN
MAIN_ROUNDING_RULE_TOT

Is not present in db "llx_const"

Workaround:
- Add line in db ("llx_const" - same as Dolibarr 11)
- Use limits.php from Dolibarr 11

**Comment by loxK** [comment]
Confirmed.

But the best workaround is to add the constant in the admin constant screen: htdocs/admin/const.php

I looked at the code it seems that they added a sort of "limits per currencies feature" that broke single currency limits editing.

**Comment by loxK** [comment]
@eldy I can fix it but need information. How is it supposed to work ?

We have three cases:

### 1) no multicurrency

In that case do we want the currency appended to the constants names ? (eg. MAIN_MAX_DECIMALS_TOT_EUR) 
Or do we want the global constants names without the currency code ? (eg. MAIN_MAX_DECIMALS_TOT)

### 2) multi-currency with MULTICURRENCY_USE_LIMIT_BY_CURRENCY enabled

I suppose in that case we want the constants named *with* the currency appended (eg. MAIN_MAX_DECIMALS_TOT_EUR)

### 3) multi-currency with MULTICURRENCY_USE_LIMIT_BY_CURRENCY disabled
I suppose, in that case, we want the constants named *without* the currency appended (eg. MAIN_MAX_DECIMALS_TOT)
