### ISSUE TITLE
Bug: Contact/Address types element missing

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14185]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
The dictionary of the Contact/Address types element for the ticket and ticketsup missing when editing.

## Environment
- **Version**: 12.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /admin/dict.php?sortfield=element&sortorder=&rowid=155&code=SUPPORTTEC&&id=11&action=edit&page_y=1892.3519287109375

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/86527227-86f60800-becf-11ea-99e8-e87f25493174.PNG)

**Comment by dpriskorn** [comment]
Can someone reproduce this?

**Comment by atm-jpb** [comment]
reproduced on 12.0.4 
- URL(s): /admin/dict.php?sortfield=element&sortorder=&rowid=155&code=SUPPORTTEC&&id=11&action=edit&page_y=1892.3519287109375
![cc](https://user-images.githubusercontent.com/68547382/103760949-267a8b80-5016-11eb-8d2a-b2c7a57c5ab2.png)

**Comment by atm-jpb** [comment]
PR : https://github.com/Dolibarr/dolibarr/pull/15904
