### ISSUE TITLE
Cannot translate "Suspended" on tickets status

### ISSUE THREAD

**Issue by gavrielzs** [Dolibarr/dolibarr#14182]
# Bug
Cannot translate "Suspended" on tickets status.

## Environment
- **Version**: [*12.0.0*]
- **OS**: [*CentOS 7*]
- **Web server**: [*LiteSpeed*]
- **PHP**: [*7.2.31*]
- **Database**: [*mysqli (10.1.44-MariaDB)*]
- **URL(s)**: [*ticket/index.php*]

**Comment by dpriskorn** [comment]
Screenshot? Where are you trying to translate it?
