### ISSUE TITLE
Bug: Translation not working for contacts

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14184]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Translation not working for contacts even the dictionary had been setup in English, need to rewrite the database.

## Environment
- **Version**: 12.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /contact/card.php?id=5&action=edit

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/86527099-22867900-bece-11ea-8af3-9de060c7ea21.PNG)

**Comment by dpriskorn** [comment]
Hi, Could you please stop opening blank issues and press "bug" if bug report from now on? Its a hassle adding the bug label to all your issues. Thanks

**Comment by ksar-ksar** [comment]
Hello,

Could you check on newer dolibarr versions ?

**Comment by asolslk** [comment]
Expired
