### ISSUE TITLE
Default dates are in the future in balance report

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#14197]
# Bug
When fiscal year starts in September, default range for balance report starts in October of the current year, thus in the future.

## Environment
- **Version**: V8, V11.0.4
- **URL(s)**: htdocs/accountancy/bookkeeping/balance.php?mainmenu=accountancy&leftmenu=accountancy_accountancy

## Expected and actual behavior
I expect that the dates are from October 2019 to September 2020 when asking in July 2020
![image](https://user-images.githubusercontent.com/5154580/86812232-14c42580-c07f-11ea-9ff1-653d955f57fe.png)

**Comment by papoteur-mga** [comment]
Thanks for this :)

**Comment by ksar-ksar** [comment]
You are welcome ;-)

I hope that the FIX above had fixed the issue.

If not we can re-open it of course!
