### ISSUE TITLE
Implement Wordpress like filter and action hooks

### ISSUE THREAD

**Issue by loxK** [Dolibarr/dolibarr#14195]
# Feature Request

WordPress filters and actions hook are yet simple but very powerful. It could really ease module and core development and open a lot of possibilities.

People already made libraries out of this proven stable concept: https://packagist.org/packages/voku/php-hooks

I know about Dolibarr hooks system but it is overcomplicated to use and much less flexible.

For references:
- https://developer.wordpress.org/plugins/hooks/
- https://codex.wordpress.org/Plugin_API#Hooks:_Actions_and_Filters

**Comment by cfoellmann** [comment]
I am thinking about this for some time now.
All the screens are very unflexible in Dolibarr. Real hooks would make it easier to extend and far more "automagical"

**Comment by loxK** [comment]
It would give great flexibility.
