### ISSUE TITLE
Add filters to the warehouse contents listing (same filters as the product listing)

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#14194]
# Feature Request
/product/list.php has filters on the products, but /product/stock/card.php doesn't have them. Add the filters from products to this last page

## Use case
When checking stock in a warehouse, it is often useful to check only a subset of the products. Implementing filters as in the Products page would make this easy. Also, if the totals at the bottom of the table are calculated based on the current filter, it also serves to evaluate the value of that subset.

**Comment by jrgonzalezrios** [comment]
Hi! I agree with you, it would very useful to have complementary attributes that you have in products to be able to sort them, so you can know how much money you have invested in such type of brand for example.

Maybe by adding complementary attributes to Warehouse "lines" would help, as by now you can only add complementary attributes to the Warehouse details.
