### ISSUE TITLE
SQL error when upgrading from 11 > 12

### ISSUE THREAD

**Issue by Timh1970** [Dolibarr/dolibarr#14204]
# Bug
When upgrading from 11 > 12 when checking the database I get error:
Error DB_ERROR_42804: ALTER TABLE llx_extrafields MODIFY COLUMN printable integer DEFAULT 0;
ERROR: 42804: column "printable" cannot be cast automatically to type integer HINT: You might need to specify "USING printable::integer". LOCATION: ATPrepAlterColumnType, tablecmds.c:9677

## Environment
- **Version**: 12
- **OS**: Debian
- **Web server**: Apache 2.4
- **PHP**: 
- **Database**: Postgresql 11
- **URL(s)**: [install/upgrade.php?action=upgrade&selectlang=en_GB&versionfrom=11.0.0&versionto=12.0.0]

## Steps to reproduce the behavior
Update from 11 to 12

Server connection : localhost | OK
-- | --
Database connection : xxxxxxxxxxxx | OK
Database server version | 11.7 (Debian 11.7-0+deb10u1)
Please be patient...
 
Choose migration script | 11.0.0-12.0.0.sql
Request 1 sql='UPDATE llx_c_units set scale = 3600 where code  = 'H' and unit_type = 'time';'
Request 2 sql='UPDATE llx_c_units set scale = 86400 where code = 'D' and unit_type = 'time';'
Request 3 sql='create table  llx_commande_fournisseur_dispatch_extrafields(rowid            integer  AUTO_INCREMENT PRIMARY KEY,tms              timestamp,fk_object         integer NOT NULL,import_key       varchar(14))ENGINE=innodb;'
Request 4 sql='ALTER TABLE  llx_commande_fournisseur_dispatch_extrafields ADD INDEX  idx_commande_fournisseur_dispatch_extrafields (fk_object);'
Request 5 sql='UPDATE llx_accounting_system SET fk_country = NULL, active = 0 WHERE pcg_version = 'SYSCOHADA';'
Request 6 sql='create table  llx_c_shipment_package_type(rowid        integer  AUTO_INCREMENT PRIMARY  KEY,label        varchar(50) NOT NULL,description	 varchar(255),active        integer DEFAULT 1 NOT NULL,entity       integer DEFAULT 1 NOT  NULL)ENGINE=innodb;'
Request 7 sql='create table  llx_facturedet_rec_extrafields(rowid            integer AUTO_INCREMENT  PRIMARY KEY,tms              timestamp,fk_object        integer NOT  NULL,import_key       varchar(14))ENGINE=innodb;'
Request 8 sql='ALTER TABLE llx_facturedet_rec_extrafields ADD INDEX idx_facturedet_rec_extrafields (fk_object);'
Request 9 sql='ALTER TABLE llx_facture_rec MODIFY COLUMN titre varchar(200) NOT NULL;'
Request 10 sql='create table  llx_mrp_mo_extrafields(rowid                     integer AUTO_INCREMENT  PRIMARY KEY,tms                       timestamp,fk_object                  integer NOT NULL,import_key                varchar(14))  ENGINE=innodb;'
Request 11 sql='ALTER TABLE llx_mrp_mo_extrafields ADD INDEX idx_fk_object(fk_object);'
Request 12 sql='delete from llx_const where name  in ('PROJECT_HIDE_TASKS', 'MAIN_BUGTRACK_ENABLELINK',  'MAIN_HELP_DISABLELINK') and entity = 0;'
Request 13 sql='ALTER TABLE llx_bom_bom MODIFY COLUMN duration double(24,8);'
Request 14 sql='ALTER TABLE llx_prelevement_bons ADD COLUMN type varchar(16) DEFAULT 'debit-order';'
Request 15 sql='ALTER TABLE llx_ecm_files MODIFY COLUMN src_object_type varchar(64);'
Request 16 sql='ALTER TABLE llx_document_model MODIFY COLUMN type varchar(64);'
Request 17 sql='DROP INDEX ix_fk_product_stock;'
Request 18 sql='ALTER TABLE llx_actioncomm DROP COLUMN punctual;'
Request 19 sql='DELETE FROM llx_menu where module='supplier_proposal';'
Request 20 sql='UPDATE llx_website SET lang = 'en' WHERE lang like 'en_%';'
Request 21 sql='UPDATE llx_website SET lang = 'fr' WHERE lang like 'fr_%';'
Request 22 sql='UPDATE llx_website SET lang = 'es' WHERE lang like 'es_%';'
Request 23 sql='UPDATE llx_website SET lang = 'de' WHERE lang like 'de_%';'
Request 24 sql='UPDATE llx_website SET lang = 'it' WHERE lang like 'it_%';'
Request 25 sql='UPDATE llx_website SET lang = 'pt' WHERE lang like 'pt_%';'
Request 26 sql='UPDATE llx_website_page SET lang = 'en' WHERE lang like 'en_%';'
Request 27 sql='UPDATE llx_website_page SET lang = 'fr' WHERE lang like 'fr_%';'
Request 28 sql='UPDATE llx_website_page SET lang = 'es' WHERE lang like 'es_%';'
Request 29 sql='UPDATE llx_website_page SET lang = 'de' WHERE lang like 'de_%';'
Request 30 sql='UPDATE llx_website_page SET lang = 'it' WHERE lang like 'it_%';'
Request 31 sql='UPDATE llx_website_page SET lang = 'pt' WHERE lang like 'pt_%';'
Request 32 sql='ALTER TABLE llx_website ADD COLUMN lang varchar(8);'
Request 33 sql='ALTER TABLE llx_website ADD COLUMN otherlang varchar(255);'
Request 34 sql='ALTER TABLE llx_website_page ADD COLUMN author_alias varchar(64);'
Request 35 sql='UPDATE llx_rights_def SET perms =  'order_advance', subperms = 'close' WHERE module = 'commande' AND perms =  'cloturer';'
Request 36 sql='UPDATE llx_rights_def SET perms =  'propal_advance', subperms = 'close' WHERE module = 'propale' AND perms =  'cloturer';'
Request 37 sql='ALTER TABLE llx_holiday_users DROP INDEX uk_holiday_users;'
Request 38 sql='ALTER TABLE llx_holiday_users ADD UNIQUE INDEX uk_holiday_users(fk_user, fk_type);'
Request 39 sql='ALTER TABLE llx_ticket ADD COLUMN import_key varchar(14);'
Request 40 sql='ALTER TABLE llx_ticket ADD UNIQUE uk_ticket_ref (ref, entity);'
Request 41 sql='ALTER TABLE llx_ticket ADD INDEX idx_ticket_entity (entity);'
Request 42 sql='ALTER TABLE llx_ticket ADD INDEX idx_ticket_fk_soc (fk_soc);'
Request 43 sql='ALTER TABLE llx_ticket ADD INDEX idx_ticket_fk_user_assign (fk_user_assign);'
Request 44 sql='ALTER TABLE llx_ticket ADD INDEX idx_ticket_fk_project (fk_project);'
Request 45 sql='ALTER TABLE llx_ticket ADD INDEX idx_ticket_fk_statut (fk_statut);'
Request 46 sql='UPDATE llx_c_regions set nom = 'Centre-Val de Loire' WHERE fk_pays = 1 AND code_region = 24;'
Request 47 sql='insert into llx_c_regions  (fk_pays,code_region,cheflieu,tncc,nom) values (1, 27, '21231', 0,  'Bourgogne-Franche-Comté');'
Request 48 sql='insert into llx_c_regions (fk_pays,code_region,cheflieu,tncc,nom) values (1, 28, '76540', 0, 'Normandie');'
Request 49 sql='insert into llx_c_regions  (fk_pays,code_region,cheflieu,tncc,nom) values (1, 32, '59350', 4,  'Hauts-de-France');'
Request 50 sql='insert into llx_c_regions (fk_pays,code_region,cheflieu,tncc,nom) values (1, 44, '67482', 2, 'Grand Est');'
Request 51 sql='insert into llx_c_regions  (fk_pays,code_region,cheflieu,tncc,nom) values (1, 75, '33063', 0,  'Nouvelle-Aquitaine');'
Request 52 sql='insert into llx_c_regions (fk_pays,code_region,cheflieu,tncc,nom) values (1, 76, '31355', 1, 'Occitanie');'
Request 53 sql='insert into llx_c_regions  (fk_pays,code_region,cheflieu,tncc,nom) values (1, 84, '69123', 1,  'Auvergne-Rhône-Alpes');'
Request 54 sql='UPDATE llx_c_departements set fk_region = 27 WHERE fk_region = 26 OR fk_region = 43;'
Request 55 sql='UPDATE llx_c_departements set fk_region = 28 WHERE fk_region = 25 OR fk_region = 23;'
Request 56 sql='UPDATE llx_c_departements set fk_region = 32 WHERE fk_region = 22 OR fk_region = 31;'
Request 57 sql='UPDATE llx_c_departements set fk_region = 44 WHERE fk_region = 21 OR fk_region = 41 OR fk_region = 42;'
Request 58 sql='UPDATE llx_c_departements set fk_region = 75 WHERE fk_region = 54 OR fk_region = 74 OR fk_region = 72;'
Request 59 sql='UPDATE llx_c_departements set fk_region = 76 WHERE fk_region = 73 OR fk_region = 91;'
Request 60 sql='UPDATE llx_c_departements set fk_region = 84 WHERE fk_region = 82 OR fk_region = 83;'
Request 61 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 21;'
Request 62 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 22;'
Request 63 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 23;'
Request 64 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 25;'
Request 65 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 26;'
Request 66 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 31;'
Request 67 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 41;'
Request 68 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 42;'
Request 69 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 43;'
Request 70 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 54;'
Request 71 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 72;'
Request 72 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 73;'
Request 73 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 74;'
Request 74 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 82;'
Request 75 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 83;'
Request 76 sql='DELETE FROM llx_c_regions WHERE fk_pays = 1 AND code_region = 91;'
Request 77 sql='ALTER TABLE llx_bookmark DROP INDEX uk_bookmark_url;'
Request 78 sql='ALTER TABLE llx_bookmark DROP INDEX uk_bookmark_title;'
Request 79 sql='ALTER TABLE llx_bookmark MODIFY COLUMN url TEXT;'
Request 80 sql='ALTER TABLE llx_bookmark ADD UNIQUE uk_bookmark_title (fk_user, entity, title);'
Request 81 sql='ALTER TABLE llx_societe_rib MODIFY COLUMN owner_address  varchar(255);'
Request 82 sql='ALTER TABLE llx_societe_rib MODIFY COLUMN default_rib smallint NOT NULL DEFAULT 0;'
Request 83 sql='ALTER TABLE llx_societe_rib ADD COLUMN stripe_account varchar(128);'
Request 84 sql='create table llx_object_lang(rowid           integer AUTO_INCREMENT PRIMARY KEY,fk_object      integer       DEFAULT 0 NOT NULL,type_object    varchar(32)  NOT NULL,property        varchar(32)  NOT NULL,lang           varchar(5)   DEFAULT 0 NOT  NULL,value          text,import_key varchar(14) DEFAULT  NULL)ENGINE=innodb;'
Request 85 sql='ALTER TABLE llx_object_lang ADD UNIQUE INDEX uk_object_lang (fk_object, type_object, property, lang);'
Request 86 sql='CREATE TABLE  llx_categorie_actioncomm(fk_categorie integer NOT NULL,fk_actioncomm  integer NOT NULL,import_key varchar(14)) ENGINE=innodb;'
Request 87 sql='ALTER TABLE llx_categorie_actioncomm ADD PRIMARY KEY pk_categorie_actioncomm (fk_categorie, fk_actioncomm);'
Request 88 sql='ALTER TABLE llx_categorie_actioncomm ADD INDEX idx_categorie_actioncomm_fk_categorie (fk_categorie);'
Request 89 sql='ALTER TABLE llx_categorie_actioncomm ADD INDEX idx_categorie_actioncomm_fk_actioncomm (fk_actioncomm);'
Request 90 sql='ALTER TABLE  llx_categorie_actioncomm ADD CONSTRAINT  fk_categorie_actioncomm_categorie_rowid FOREIGN KEY (fk_categorie)  REFERENCES llx_categorie (rowid);'
Request 91 sql='ALTER TABLE  llx_categorie_actioncomm ADD CONSTRAINT  fk_categorie_actioncomm_fk_actioncomm FOREIGN KEY (fk_actioncomm)  REFERENCES llx_actioncomm (id);'
Request 92 sql='ALTER TABLE llx_accounting_account ADD COLUMN labelshort varchar(255) DEFAULT NULL after label;'
Request 93 sql='ALTER TABLE llx_subscription ADD COLUMN fk_user_creat   integer DEFAULT NULL;'
Request 94 sql='ALTER TABLE llx_subscription ADD COLUMN fk_user_valid   integer DEFAULT NULL;'
Request 95 sql='UPDATE llx_c_forme_juridique set libelle = 'SRL - Société à responsabilité limitée' WHERE code = '201';'
Request 96 sql='ALTER TABLE llx_c_country ADD COLUMN eec integer;'
Request 97 sql='UPDATE llx_c_country SET eec = 1  WHERE code IN  ('AT','BE','BG','CY','CZ','DE','DK','EE','ES','FI','FR','GB','GR','HR','NL','HU','IE','IM','IT','LT','LU','LV','MC','MT','PL','PT','RO','SE','SK','SI','UK');'
Request 98 sql='INSERT INTO llx_accounting_system  (fk_country, pcg_version, label, active) VALUES (  1, 'PCG18-ASSOC',  'French foundation chart of accounts 2018', 1);'
Request 99 sql='INSERT INTO llx_accounting_system  (fk_country, pcg_version, label, active) VALUES (  1, 'PCGAFR14-DEV',  'The developed farm accountancy french plan 2014', 1);'
Request 100 sql='INSERT INTO llx_accounting_system  (fk_country, pcg_version, label, active) VALUES ( 41, 'AT-BASE', 'Plan  Austria', 1);'
Request 101 sql='create table  llx_c_ticket_resolution(rowid			integer AUTO_INCREMENT PRIMARY  KEY,entity		integer DEFAULT 1,code			varchar(32)				NOT NULL,pos			 varchar(32)				NOT NULL,label			varchar(128)			NOT NULL,active		integer  DEFAULT 1,use_default	integer DEFAULT 1,description	 varchar(255))ENGINE=innodb;'
Request 102 sql='ALTER TABLE llx_c_ticket_resolution ADD UNIQUE INDEX uk_code (code, entity);'
Request 103 sql='INSERT INTO  llx_c_ticket_resolution (code, pos, label, active, use_default,  description) VALUES('SOLVED',   '10', 'Solved',    1, 0, NULL);'
Request 104 sql='INSERT INTO  llx_c_ticket_resolution (code, pos, label, active, use_default,  description) VALUES('CANCELED', '50', 'Canceled',  1, 0, NULL);'
Request 105 sql='INSERT INTO  llx_c_ticket_resolution (code, pos, label, active, use_default,  description) VALUES('OTHER',    '90', 'Other',     1, 0, NULL);'
Request 106 sql='DELETE FROM llx_const WHERE name = __ENCRYPT('DONATION_ART885')__;'
<b>Request 107 sql='ALTER TABLE llx_extrafields MODIFY COLUMN printable integer DEFAULT 0;'</b>
<b>Error DB_ERROR_42804: ALTER TABLE llx_extrafields MODIFY COLUMN printable integer DEFAULT 0;ERROR:  42804: column "printable" cannot be cast automatically to type integer HINT:  You might need to specify "USING printable::integer". LOCATION:  ATPrepAlterColumnType, tablecmds.c:9677</b>
Request 108 sql='ALTER TABLE llx_extrafields ADD COLUMN printable integer DEFAULT 0;'
Request 109 sql='UPDATE llx_const SET name =  'INVOICE_USE_RETAINED_WARRANTY' WHERE name =  'INVOICE_USE_SITUATION_RETAINED_WARRANTY';'
Request 110 sql='ALTER TABLE llx_accounting_account DROP COLUMN pcg_subtype;'
Request 111 sql='ALTER TABLE llx_product ADD COLUMN accountancy_code_buy_intra varchar(32) AFTER accountancy_code_buy;'
Request 112 sql='ALTER TABLE llx_product ADD COLUMN accountancy_code_buy_export varchar(32) AFTER accountancy_code_buy_intra;'
Request 113 sql='ALTER TABLE llx_entrepot ADD COLUMN fax varchar(20) DEFAULT NULL;'
Request 114 sql='ALTER TABLE llx_entrepot ADD COLUMN phone varchar(20) DEFAULT NULL;'
Request 115 sql='ALTER TABLE llx_accounting_account ADD COLUMN reconcilable tinyint DEFAULT 0 NOT NULL after active;'
Request 116 sql='ALTER TABLE llx_categorie MODIFY type integer NOT NULL DEFAULT 1;'
Request 117 sql='ALTER TABLE llx_societe_remise_except ADD COLUMN vat_src_code varchar(10) DEFAULT '';'
Request 118 sql='ALTER TABLE llx_blockedlog MODIFY COLUMN object_data mediumtext;'
Request 119 sql='ALTER TABLE llx_blockedlog ADD COLUMN object_version varchar(32) DEFAULT '';'
Request 120 sql='ALTER TABLE llx_product_lot MODIFY COLUMN batch varchar(128);'
Request 121 sql='ALTER TABLE llx_product_batch MODIFY COLUMN batch varchar(128);'
Request 122 sql='ALTER TABLE llx_expeditiondet_batch MODIFY COLUMN batch varchar(128);'
Request 123 sql='ALTER TABLE llx_commande_fournisseur_dispatch MODIFY COLUMN batch varchar(128);'
Request 124 sql='ALTER TABLE llx_stock_mouvement MODIFY COLUMN batch varchar(128);'
Request 125 sql='ALTER TABLE llx_mrp_production MODIFY COLUMN batch varchar(128);'
Request 126 sql='ALTER TABLE llx_mrp_production MODIFY qty real NOT NULL DEFAULT 1;'
Request 127 sql='create table  llx_categorie_website_page(fk_categorie  	integer NOT  NULL,fk_website_page   integer NOT NULL,import_key    	 varchar(14))ENGINE=innodb;'
Request 128 sql='ALTER TABLE  llx_categorie_website_page ADD PRIMARY KEY pk_categorie_website_page  (fk_categorie, fk_website_page);'
Request 129 sql='ALTER TABLE llx_categorie_website_page ADD INDEX idx_categorie_website_page_fk_categorie (fk_categorie);'
Request 130 sql='ALTER TABLE llx_categorie_website_page ADD INDEX idx_categorie_website_page_fk_website_page (fk_website_page);'
Request 131 sql='ALTER TABLE  llx_categorie_website_page ADD CONSTRAINT  fk_categorie_website_page_categorie_rowid FOREIGN KEY (fk_categorie)  REFERENCES llx_categorie (rowid);'
Request 132 sql='ALTER TABLE  llx_categorie_website_page ADD CONSTRAINT  fk_categorie_website_page_website_page_rowid FOREIGN KEY  (fk_website_page) REFERENCES llx_website_page (rowid);'
Request 133 sql='ALTER TABLE llx_categorie ADD COLUMN date_creation	datetime;'
Request 134 sql='ALTER TABLE llx_categorie ADD COLUMN tms     		timestamp;'
Request 135 sql='ALTER TABLE llx_categorie ADD COLUMN fk_user_creat	integer;'
Request 136 sql='ALTER TABLE llx_categorie ADD COLUMN fk_user_modif	integer;'
Request 137 sql='ALTER TABLE llx_commandedet ADD  CONSTRAINT fk_commandedet_fk_commandefourndet FOREIGN KEY  (fk_commandefourndet) REFERENCES llx_commande_fournisseurdet (rowid);'
Request 138 sql='ALTER TABLE llx_prelevement_facture_demande ALTER COLUMN fk_facture DROP NOT NULL;'
Request 139 sql='ALTER TABLE llx_prelevement_facture_demande ADD COLUMN fk_facture_fourn INTEGER NULL;'
Request 140 sql='ALTER TABLE llx_prelevement_facture ALTER COLUMN fk_facture DROP NOT NULL;'
Request 141 sql='ALTER TABLE llx_prelevement_facture ADD COLUMN fk_facture_fourn INTEGER NULL;'
Request 142 sql='ALTER TABLE llx_menu MODIFY COLUMN module varchar(255);'
Request 143 sql='UPDATE llx_actioncomm SET fk_action = 50 where fk_action = 40 AND code = 'TICKET_MSG';'
Request 144 sql='ALTER TABLE llx_emailcollector_emailcollector ADD COLUMN hostcharset varchar(16) DEFAULT 'UTF-8';'
Request 145 sql='ALTER TABLE llx_adherent_type MODIFY subscription varchar(3) NOT NULL DEFAULT '1';'
Request 146 sql='ALTER TABLE llx_adherent_type MODIFY vote varchar(3) NOT NULL DEFAULT '1';'
Request 147 sql='UPDATE llx_prelevement_facture_demande SET entity = 1 WHERE entity IS NULL;'
Request 148 sql='ALTER TABLE llx_prelevement_facture_demande ADD INDEX idx_prelevement_facture_demande_fk_facture (fk_facture);'
Request 149 sql='ALTER TABLE  llx_prelevement_facture_demande ADD INDEX  idx_prelevement_facture_demande_fk_facture_fourn (fk_facture_fourn);'
Request 150 sql='insert into  llx_c_tva(rowid,fk_pays,taux,recuperableonly,note,active) values (721,  72,    '0','0','VAT Rate 0',1);'
Request 151 sql='insert into  llx_c_tva(rowid,fk_pays,taux,recuperableonly,localtax1,localtax1_type,note,active)  values (722, 72,   '18','0', '0.9', '1', 'VAT Rate 18+0.9', 1);'
Script processing

**Comment by Timh1970** [comment]
Got around this by:

ALTER TABLE "public"."llx_extrafields" ALTER COLUMN "printable" DROP DEFAULT;
ALTER TABLE "public"."llx_extrafields" ALTER COLUMN "printable" SET DEFAULT 0,ALTER COLUMN "printable" TYPE integer USING CASE WHEN FALSE THEN 0 ELSE 1 END;

And then re-ran the upgrade.

**Comment by jerome-duchene** [comment]
workaround also works for me

**Comment by papoteur-mga** [comment]
See also #14142  #14240 and https://www.dolibarr.fr/forum/t/erreur-dans-le-script-de-mise-a-jour-en-v12-0/33376

**Comment by dpriskorn** [comment]
This has been fixed with https://github.com/Dolibarr/dolibarr/commit/48adeb9dd751e5818e7af3f540f04af617e95fc0 please close this.

**Comment by fpoulain** [comment]
I got on my side
```
Erreur DB_ERROR_1118: ALTER TABLE llx_societe_rib ADD COLUMN stripe_account varchar(128);
Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```
when doing the 11->12 migrations. I skipped it but the column hasn't been defined in database. I am getting the same error if I manually try to create the column in db.

How do you think about it?

**Comment by jerome-duchene** [comment]
For the v13, I have this table structure.

![image](https://user-images.githubusercontent.com/17760168/114565742-dbee5800-9c71-11eb-8373-b2e418dc00cd.png)

Maybe some columns have be downsized to allow creating the new column.
