### ISSUE TITLE
Bug: Product label cannot use special character

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14203]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Found the product label cannot use the special character such as " that represent inch and ' represent feet.

## Environment
- **Version**: 12.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /product/card.php?id=130

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/86943370-f5112800-c178-11ea-849d-40d413db0982.PNG)

**Comment by dpriskorn** [comment]
Confirmed on v12

**Comment by john-botella** [comment]
See #14833 #15017
PR : https://github.com/Dolibarr/dolibarr/pull/15892  https://github.com/Dolibarr/dolibarr/pull/15894
