### ISSUE TITLE
Deactivate eatby + sellby

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#14200]
# Feature Request
Disable the fields `eatby` and `sellby` for products.

## Use case
We do not use any of these fields and it is always better to hide fields via php and not css or even change core files

## Suggested implementation
Add constants `PRODUCT_DISABLE_EATBY` and `PRODUCT_DISABLE_SELLBY`.
If these are `1` selects for these days are skipped in php

I will start a PR for this.
If anyone could help test for missing occurrences it would be most helpful

**Comment by StephaneLesage** [comment]
+1
We don't use these dates.
