### ISSUE TITLE
Can't translate 'Tickets' at one project

### ISSUE THREAD

**Issue by saosangmo** [Dolibarr/dolibarr#14208]
# Bug
*Can not translate 'tickets' tab at one project*

## Environment
- **Version**: [*12.0.1*]
- **OS**: [*MacOS 10.15.5 (19F101)*]
- **Web server**: [*Apache/2.4.41*]
- **PHP**: [*PHP 7.1.32*]
- **Database**: [* MariaDB 10.4.8*]
- **URL(s)**: [*projet/card.php?id=24*]

## Screen Shot
<img width="1202" alt="Screen Shot 2020-07-09 at 23 52 43" src="https://user-images.githubusercontent.com/4606931/87068286-8b0f8600-c23f-11ea-8369-b398cf42430e.png">

**Comment by ksar-ksar** [comment]
Hi,

What is your language ?
THis is most probably because the translation is not complete for your language.
You can help translating in : https://www.transifex.com/dolibarr-association/dolibarr/dashboard/

**Comment by saosangmo** [comment]
I use Vietnamese.

**Comment by saosangmo** [comment]
@ksar-ksar I have check mains.lang in Vietnamese package.
`SearchIntoTickets=Vé`
It is translated into Vietnamese.

I also search the whole English package but there is only one string: SearchIntoTickets=Tickets
