### ISSUE TITLE
Bug: Editing intervention does not save wysiwyg format

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#14210]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.2.16-MariaDB
- **URL(s)**: /fichinter/card.php?id=1

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by lmag** [comment]
Exact : 
![image](https://user-images.githubusercontent.com/3288514/96778516-1aeecf80-13ec-11eb-9a83-c8f841dff976.png)

**Comment by ksar-ksar** [comment]
Hello,

Normally fixed in newer Dolibarr versions, could you check ?

**Comment by leninrivas** [comment]
It's fixed in new version.
