### ISSUE TITLE
Add after discount unit price to cards and documents with prices

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#14212]
# Feature Request
All cards and documents that include prices feature the following columns (Names based on English UK UI language):

Description | VAT | U.P. (Net) | Qty | Disc. | Cost price | Total (excl.).

Nowhere is unit price after discount included. It would be useful to add it.

## Use case
It's often interesting to control unit price after discount price for sales agents, specially when competing against other businesses, specially when  the number of units in your proposal and in your competitor's proposal is not necessarily the same. This column should be added both to the cards and the documents (maybe hidden under an option in the relevant modules configuration page, or a setup other one?). For documents, it can be calculated in the document template, so it's less problematic, but adding it to the cards is far more complex for the end user.

**Comment by dpriskorn** [comment]
That would be nice 👍
