### ISSUE TITLE
Implement drop shipping functionality

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#14233]
# Feature Request
As per the [Wikipedia](https://en.wikipedia.org/wiki/Drop_shipping), "Drop shipping is a supply chain management method in which the retailer does not keep goods in stock but instead transfers its customer's orders and shipment details to either the manufacturer, another retailer, or a wholesaler, who then ships the goods directly to the customer."

## Use case
Customer C orders Product P from you. Product A is sold by Cendor V. However, instead of V shipping the goods to your warehouse, and then you shipping those goods to C, V ships the goods directly to C.

## Suggested implementation
- Create a new type of 3rd party contact on purchase orders "Order Delivery Contact" that will be the address that the order shall be shipped to. As usual, this contact can be from any 3rd party so long as you first select the first party.
- Modify the PDF templates for supplier order to include this information
- Add a button to generate drop shipping supplier orders to orders. Pressing this button will create new purchase orders for the products in the order, and copy the Customer Shipping Contact from the sales order as the purchase order Order Delivery Contact

**Comment by boardnick0815** [comment]
Hello AxisAutomation, Hello Dolibarr developers,

Especially for businesses dealing with large / heavy goods this would be a great feature.
I would also be happy to see this feature being added to dolibarr!

**Comment by elsp1991** [comment]
Hello All, 
The way I am implementing that is I create a warehouse with the name of the **V**endor and then when I do a shipping. I modified my UPS module to the following setup:

Shipper: my Company
ShipTo: **C**lient
ShipFrom: the Warehouse that corresponds to **V**endor

ShipFrom is used by UPS as pickup location and return address in case the shipment has a return label attached. ShipFrom is not required and if is not setted the Shipper's address is used for pickup. In case of a return shipment is required
This way I can track the movements related to this Vendor and the vendor's name and address is not visible generally on the labels.
The nice thing about this of shipments is that when you create a shippment you have to always select a warehouse to ship from so the behavior fits the current implementation.

But for this to be perfect we need a bit better Warehouse parameters for example:

- state/region is missing from the warehouse address attributes
- there is no name attribute (I currently use the description) That would be the name of the pickup location
- A user that is the contact of the warehouse (used for att. name in the shipFrom)
- A dolibarr vendor that is linked to the warehouse maybe
- a way to handle pickups

**Comment by agarcina** [comment]
We do have the Dropshipping module. You can reach us at http://unboxerp.com

**Comment by hregis** [comment]
Quelqu'un d'autre veut faire ça pub !!!!
