### ISSUE TITLE
Fetch_thirdparty was not done before

### ISSUE THREAD

**Issue by rockincent** [Dolibarr/dolibarr#14239]
# Bug
When an sales order is made and a product is added or the status is changed to Validate or Modify I get the following error (products still get added and status still change):

Requested URL: /commande/card.php?id=754&action=confirm_modif&confirm=yes&token=b76949e3bdd41450ca15be5a3a38aa96b74f488e&idwarehouse=1
Referer: https://mydomain.com/commande/card.php?id=754&action=modif
Menu manager: eldy_menu.php

Modules/Applications: user, agenda, barcode, cron, commande, ecm, facture, fournisseur, printing, resource, bookmark, societe, emailcollector, service, cyberoffice, mycyberoffice, datapolicy, contrat, product, stock, projet, banque, splash, api, webservices, zenfusionmaps, otp, socialnetworks, categorie, fckeditor, mailing, workflow, import, export, skype, oauth
Message: Error: Method printObjectLine was called on an object and object->fetch_thirdparty was not done before

## Environment
Dolibarr: 12.0.1 - https://www.dolibarr.org
Level of features: 0
PHP: 7.3.18
Server: Apache/2
OS: Linux web0098.zxcs.nl 3.10.0-962.3.2.lve1.5.32.el7.x86_64 #1 SMP Fri Feb 28 07:18:51 EST 2020 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36]

## Steps to reproduce the behavior
- Create Sales Order
- Add Predefined product

**Comment by hansemschnokeloch** [comment]
Hi, same bug here, but it occurs only if the option "multilanguage support" is enabled in Home>Setup>Display.

**Comment by notaufnahme** [comment]
I have the same problem. Even an update to 12.0.2 does not fix the error.

**Comment by gimitech** [comment]
I have the same problem. Even an update to 12.0.3 does not fix the error if the option "multilanguage support" is enabled in Home>Setup>Display.

**Comment by code-chicken** [comment]
I had the same problem. I spent several hours trying to find out what is different to release 11 resulting in this behaviour - unfortunately without success.

For now, the following patch works at least for 12.0.3, which shouldn't have any negative side effects. Hope this helps...

```
--- htdocs/commande/card.php	(date 1602190679537)
+++ htdocs/commande/card.php	(date 1602190679537)
@@ -1921,6 +1921,7 @@
 		$author = new User($db);
 		$author->fetch($object->user_author_id);
 
+        $object->fetch_thirdparty();
 		$res = $object->fetch_optionals();
 
 		$head = commande_prepare_head($object);
```
