### ISSUE TITLE
ExtraFields for Products Customer (Prices)

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#14231]
# Feature Request
please add ExtraFields for Customer Products (Prices) 

## Suggested implementation
add a table
llx_products_customer_price_extrafields 
or 
llx_products_customer_extrafields
or
llx_customer_products_extrafields

add a php form
/dolibarr/product/admin/product_customer_extrafields.php

**Comment by dpriskorn** [comment]
What is the usecase for this?

**Comment by dolibit-ut** [comment]
To add comments or second price or customer ref. to this
