### ISSUE TITLE
Allow selecting the warehouse purchase orders should be delivered to

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#14235]
# Feature Request
Add a "destination warehouse" to purchase orders.

## Use case
Currently, the warehouse the products of an order go to is set during order reception. The only address you see in the purchase order is the main address for the company! This is fine when the warehouses are part of the same building complex as the main address for the company. but what if the company offices are in a different location than the warehouse? what if a company has warehouses in different cities? How does the company communicate with the supplier that the order should be shipped to a different warehouse?

## Suggested implementation
- Add a "destination warehouse" drop down on purchase orders. This is populated with the warehouses defined under "/product/stock/index.php"
- Modify the PDF templates to include this information.
- Default to this warehouse when receiving goods for that order

**Comment by fbosman** [comment]
I implemented this using an extra-field on purchase orders, populated with the available warehouses.
In the pdf the default warehouse-adress is taken in case the extra-field is not populated.

Frans

Op 14 jul. 2020 om 10:31 heeft AxisAutomation <notifications@github.com> het volgende geschreven:

﻿
Feature Request

Add a "destination warehouse" to purchase orders.

Use case

Currently, the warehouse the products of an order go to is set during order reception. The only address you see in the purchase order is the main address for the company! This is fine when the warehouses are part of the same building complex as the main address for the company. but what if the company offices are in a different location than the warehouse? what if a company has warehouses in different cities? How does the company communicate with the supplier that the order should be shipped to a different warehouse?

Suggested implementation

Add a "destination warehouse" drop down on purchase orders. This is populated with the warehouses defined under "/product/stock/index.php"
Modify the PDF templates to include this information.
Default to this warehouse when receiving goods for that order

**Comment by ToniTen** [comment]
Thanks Frans for the suggestion

Sure, I can do that, and then fight the PDF template to display it. I indeed am doing that already. However, the issue is that I feel this should be available by default, and not something each implementation needs to do from scratch.

**Comment by fbosman** [comment]
I agree

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 14 jul. 2020 om 10:50 heeft AxisAutomation <notifications@github.com> het volgende geschreven:

﻿
Thanks Frans for the suggestion

Sure, I can do that, and then fight the PDF template to display it. I indeed am doing that already. However, the issue is that I feel this should be available by default, and not something each implementation needs to do from scratch.
