### ISSUE TITLE
Upgrade to 12.01 from 12.0 crash

### ISSUE THREAD

**Issue by p-abella** [Dolibarr/dolibarr#14241]
![Screenshot_2020-07-14 Dolibarr install or upgrade_2](https://user-images.githubusercontent.com/37841162/87462522-168d6c00-c5de-11ea-91a9-6ad228a88a8e.png)
![Screenshot_2020-07-14 Dolibarr install or upgrade](https://user-images.githubusercontent.com/37841162/87462535-1ab98980-c5de-11ea-8590-bc2611ed37e7.png)

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Update procedure to go to version 12.01 from 12.0 crashes on updating database tables

## Environment
- **Version**: 12.0
- **OS**: Lubuntu 20.04 
- **Web server**: Apache/2.4.41 (Ubuntu) 
- **PHP**: PHP version: 7.4.7 
- **Database**: MySQL 8.0.20-0ubuntu0.20.04.1 - (Ubuntu) 
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Automatic update procedure should update tables if required

## Steps to reproduce the behavior
I have copied the Dolibarr 12.0.1 files into the Dolibarr server directory, and when loading the dolibarr page, the update procedure starts updating the required issues.
This procedure crashes trying to add some constraints because those are already implemented in the referenced tables (see attached pictures).
The errors are:
1.- Error DB_ERROR_1826: ALTER TABLE dolibarr_categorie_actioncomm ADD CONSTRAINT fk_categorie_actioncomm_fk_actioncomm FOREIGN KEY (fk_actioncomm) REFERENCES dolibarr_actioncomm (id);
Duplicate foreign key constraint name 'fk_categorie_actioncomm_fk_actioncomm'
2.- Error DB_ERROR_1826: ALTER TABLE dolibarr_categorie_actioncomm ADD CONSTRAINT fk_categorie_actioncomm_categorie_rowid FOREIGN KEY (fk_categorie) REFERENCES dolibarr_categorie (rowid);
Duplicate foreign key constraint name 'fk_categorie_actioncomm_categorie_rowid'
3.- Error DB_ERROR_1826: ALTER TABLE dolibarr_categorie_actioncomm ADD CONSTRAINT fk_categorie_actioncomm_fk_actioncomm FOREIGN KEY (fk_actioncomm) REFERENCES dolibarr_actioncomm (id);
Duplicate foreign key constraint name 'fk_categorie_actioncomm_fk_actioncomm'
4.- Error DB_ERROR_1826: ALTER TABLE dolibarr_categorie_website_page ADD CONSTRAINT fk_categorie_website_page_website_page_rowid FOREIGN KEY (fk_website_page) REFERENCES dolibarr_website_page (rowid);
Duplicate foreign key constraint name 'fk_categorie_website_page_website_page_rowid'
5.- Error DB_ERROR_1826: ALTER TABLE dolibarr_categorie_website_page ADD CONSTRAINT fk_categorie_website_page_website_page_rowid FOREIGN KEY (fk_website_page) REFERENCES dolibarr_website_page (rowid);
Duplicate foreign key constraint name 'fk_categorie_website_page_website_page_rowid'
6.- Error DB_ERROR_1826: ALTER TABLE dolibarr_commandedet ADD CONSTRAINT fk_commandedet_fk_commandefourndet FOREIGN KEY (fk_commandefourndet) REFERENCES dolibarr_commande_fournisseurdet (rowid);
Duplicate foreign key constraint name 'fk_commandedet_fk_commandefourndet'

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by loxK** [comment]
It happens to me too on MySQL 8
