### ISSUE TITLE
Allow excluding directories when building a package

### ISSUE THREAD

**Issue by Ahuahuachi** [Dolibarr/dolibarr#14249]
# Feature Request
Allow to exclude directories at build package tab in Module Builder

## Use case
When creating a module, always creates a zip with bin folder (other versions of the same module) making it always an incremental file
Some times it doesn't makes sense to include .git folder or other IDE exclusive directories

**Comment by dpriskorn** [comment]
How is this related to Dolibarr?

**Comment by Ahuahuachi** [comment]
Dolibarr has a Module Builder module that allows anyone to build new modules

**Comment by rycks** [comment]
I've got the same problem :-) and looking for a solution !
