### ISSUE TITLE
Cron Jobs Fail to Execute Schedule Jobs because of hardcoded path name

### ISSUE THREAD

**Issue by git-putz** [Dolibarr/dolibarr#14243]
I scheduled the following command to run in cron to execute my scheduled jobs in Dolibarr

php -q ../scripts/cron/cron_run_jobs.php [key] admin [cronjobid]

I get this error
PHP Fatal error:  require_once(): Failed opening required '/var/www/websitedir/scripts/cron/../../htdocs/master.inc.php' (include_path='.:/usr/share/php') in /var/www/websitedir/scripts/cron/cron_run_jobs.php on line 45

It appears the htdocs directory name is a hardcoded path in that php file:
require_once $path."../../htdocs/master.inc.php";

 On my webserver that the htdocs directory is a different name so I had to manually change the path in cron_run_jobs.php to reflect the correct path name. 

Could this line in the file be changed to use a variable for the webserver root directory instead so that it doesn't need to be manually changed?

**Comment by ksar-ksar** [comment]
Hi,

There is no easy way to do that and the script is working with the normal dolibarr environment.
I d'ont think it could be fixed.

**Comment by git-putz** [comment]
If you go into the Dolibarr site, and click Admin Tools, About Web Server, there is a field called "Web server's root directory"  This reflects the correct path on my web server where dolibarr is located.  Would it be possible to call that path in the php file or pass that data into a variable and instead use that for the path to the php file?
