### ISSUE TITLE
Total VAT rate is not displayed if there is no item with this specific VAT rate in ODT invoice

### ISSUE THREAD

**Issue by berndbaringhorst** [Dolibarr/dolibarr#14250]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[Total VAT rate is not displayed if there is no item with this specific VAT rate in ODT invoice]

## Environment
- **Version**: [12.0.1]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[In germany we have new temporary VAT rates, so I added these VAT rates in my company details. In the ODT template I used these tags to call the total VAT amounts:

{object_total_vat_locale_5} €
{object_total_vat_locale_16} €

As long as there is at least one item, the corresponding total VAT is displayed. But if there is for example not one item with 5%, the total is showed as "{object_total_vat_locale_5} €".]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hi,

Have you tried to use 
`[!-- IF {my_var} --]
Print this text if {my_var} is true (can be any value but null/0/empty string)
[!-- ELSE {my_var} --]
Or print this if it's false (null/0/empty string)
[!-- ENDIF {my_var} --]`

**Comment by berndbaringhorst** [comment]
> Hi,
> 
> Have you tried to use
> `[!-- IF {my_var} --] Print this text if {my_var} is true (can be any value but null/0/empty string) [!-- ELSE {my_var} --] Or print this if it's false (null/0/empty string) [!-- ENDIF {my_var} --]`

Hi ksar-ksar, thank you very much for your reply!

Unfortunately I am very far away from being able to adapt everything beyond copying the basic tags for my ODT. Do I use this in the same field in my ODT? Would I do it like this (example for the 5% VAT)?

[!-- IF {object_total_vat_locale_5} --] 0,00 € [!-- ELSE {object_total_vat_locale_5} --] {object_total_vat_locale_5} € [!-- ENDIF {my_var} --]

**Comment by dpriskorn** [comment]
Try it. It looks like it could work.

**Comment by berndbaringhorst** [comment]
> Try it. It looks like it could work.

Unfortunaltely this does not work.

When there is 5% vat, the result in the generated invoice is:  
0,00 € [!-- ELSE 101,25 --] 101,25 € [!-- ENDIF {my_var} --]

When there is no position with 5% vat, the result is:
[!-- IF --] 0,00 € [!-- ELSE --] € [!-- ENDIF {my_var} --]

I honestly hav no too much of a clue about this.
Any help is appreciated.

Thanks in advance!!

**Comment by eldy** [comment]
The use of the [-- IF --] does not work because the substitution of variables are done before doing the analyze of conditions.

**Comment by eldy** [comment]
For the tag {object_total_..._x}, if there is no amount for the vat rate x, the key is not replaced. So you can use the condition syntax to show 0 instead of the key when value is not defined:

[!-- IF {object_total_..._x} --]
{object_total_..._x}
[!-- ELSE {object_total_..._x} --]
0
[!-- ENDIF {object_total_..._x} --]

Warning:  To be sure this part of code does not contains hidden text (added silently by LibreOffice for versioning/tracking change purpose), you must select all the code section, make a right click an select the feature "Remove direct formatting" (not doing this may make the code section not working).
