### ISSUE TITLE
Custom Fields appear twice

### ISSUE THREAD

**Issue by bosss7** [Dolibarr/dolibarr#14254]
# Bug
After creating a custom field, the field appears twice. Tested on Products module

## Environment
- **Version**: 12.0.1
- **OS**: Ubuntu 18.04 LTS
- **Web server**: Apache2
- **PHP**: 7.2
- **Database**: MySQL 5.7
- **URL(s)**: product/card.php?leftmenu=product&action=create&type=0

## Expected and actual behavior
Create a custom field and only see one.

## Steps to reproduce the behavior
create a custom field in products, go to create a new product and see the result.

[*Files*]
![image](https://user-images.githubusercontent.com/68312879/87844813-8fedcd00-c904-11ea-9918-ff1afccb59f0.png)

**Comment by dpriskorn** [comment]
Can someone confirm this?

**Comment by bosss7** [comment]
My Apologies. I just realised I was using an external module (customfields) which appears to have been discontinued and is not a part of the dolibarr core.
Disregard.
