### ISSUE TITLE
Extrafields: Display on PDF includes 3 options 0/1/2 according to the help tip, but the database column is boolean

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14265]
# Bug
see title

## Environment
- **Version**: 12
- **Database**: pg
- **URL(s)**: http://dolibarr.localhost/admin/supplierorder_extrafields.php?action=create#newattrib

## Expected and actual behavior
I expected an integer column but found a boolean true/false column. I recently upgraded from 9.0 

## Steps to reproduce the behavior
create an extrafield and hover over the tooltip questionmark
run
\d llx_extrafields
                                            Tabell "public.llx_extrafields"
     Kolumn     |             Typ             | Jämförelse | Nullbar  |         
           Standard                    
----------------+-----------------------------+------------+----------+---------
---------------------------------------
 rowid          | integer                     |            | not null | nextval(
'llx_extrafields_rowid_seq'::regclass)
 name           | character varying(64)       |            | not null | 
 entity         | integer                     |            | not null | 1
 elementtype    | character varying(64)       |            | not null | 'member'
::character varying
 label          | character varying(255)      |            | not null | 
 type           | character varying(8)        |            |          | 
 size           | character varying(8)        |            |          | NULL::ch
aracter varying
 fieldcomputed  | text                        |            |          | 
 fielddefault   | character varying(255)      |            |          | 
 fieldunique    | integer                     |            |          | 0
 fieldrequired  | integer                     |            |          | 0
 perms          | character varying(255)      |            |          | 
 enabled        | character varying(255)      |            |          | 
 pos            | integer                     |            |          | 0
 alwayseditable | integer                     |            |          | 0
 param          | text                        |            |          | 
 list           | character varying(255)      |            |          | '1'::cha
racter varying
 langs          | character varying(64)       |            |          | 
 fk_user_author | integer                     |            |          | 
 fk_user_modif  | integer                     |            |          | 
 datec          | timestamp without time zone |            |          | 
 tms            | timestamp without time zone |            | not null | now()
 help           | text                        |            |          | 
 totalizable    | boolean                     |            |          | false
 printable      | boolean                     |            |          | false

**Comment by eldy** [comment]
Field "printable" should be "integer" with v12.
Is it a first install ?
If a version migrated, don't you get any error when making the migration process ?

**Comment by dpriskorn** [comment]
Upgraded from v9 14 days ago. Used git to checkout v10, v11 and then v12. Got 1 database error that I reported here: https://github.com/Dolibarr/dolibarr/issues/14256 and that's probably what is causing this.

**Comment by dpriskorn** [comment]
I just ran this, which I think fixed my issue.
dolibarr=> alter table llx_extrafields ALTER COLUMN printable DROP DEFAULT;
dolibarr=> alter table llx_extrafields ALTER COLUMN printable TYPE integer USING printable::integer;
dolibarr=> alter table llx_extrafields ALTER COLUMN printable SET DEFAULT 0;

It now looks right in http://dolibarr.localhost/product/admin/product_extrafields.php
