### ISSUE TITLE
Bug: Unable to change the the limit

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14260]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Unable to change the the limit, tried several time on saving but it dont capture.

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /admin/limits.php?mainmenu=home&leftmenu=setup

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/87858954-5482eb00-c964-11ea-8156-4b2182ff77c9.JPG)

**Comment by dpriskorn** [comment]
What limit are you trying to change?

**Comment by eldy** [comment]
Fixed with 16d486e2114ce38d34b5b8b0da9bd88a05568d7a
