### ISSUE TITLE
Feature request: REST API for image upload

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14262]
# Feature Request
I would like to upload product images/users/etc with a filename and a base64 encoded string and let dolibarr take care of resizing and adding them to the system.

I tried investigating how dolibarr handles image uploads and found:
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/lib/images.lib.php
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/actions_linkedfiles.inc.php

Its a little unclear to me how dolibarr connects the file on disk with the database tables.
I found the table llx_ecm_files which is updated here:
https://github.com/Dolibarr/dolibarr/blob/e5688e264130f61b0be41618f1491d7514500d35/htdocs/core/actions_linkedfiles.inc.php#L248

How does dolibarr connects between products and ecm_files?

## Use case
Bulk or scripted upload of images.

## Suggested implementation
Pseudocode:
* extend product api with products/{id}/image endpoint
* accept post json with: 
{
"filename": "test.jpg",
"base64":
"iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABmJLR0QA/wD
AAgiwVAAwCAzHEPAABk0P8HHc4tw3+6bkQAAAAASUVORK5CYII="
}
* decode the base64 using https://www.php.net/manual/fr/function.base64-decode.php
* call this method to generate thumbnails, etc. $upload_dir="produit"+"/"+"ref", file is passed as an array it seems* https://github.com/Dolibarr/dolibarr/blob/e5688e264130f61b0be41618f1491d7514500d35/htdocs/core/lib/files.lib.php#L1509
* call this method to create an entry in ecm_files: https://github.com/Dolibarr/dolibarr/blob/e5688e264130f61b0be41618f1491d7514500d35/htdocs/ecm/class/ecmfiles.class.php#L119

* See here how to generate an array if needed: https://github.com/Dolibarr/dolibarr/blob/e5688e264130f61b0be41618f1491d7514500d35/htdocs/core/actions_linkedfiles.inc.php#L29

## Suggested steps
Write the php code based on the pseudocode above.  Might be a good idea to add some kind of size check after decoding, before accepting the file.

**Comment by egils-consulting** [comment]
I think I found the function which loads the file from ecm_files:
https://github.com/Dolibarr/dolibarr/blob/e5688e264130f61b0be41618f1491d7514500d35/htdocs/core/lib/files.lib.php#L222

Dolibarr takes the ref and constructs a filepath of the current product card and looks it up in ecm_files and then displays what it finds. I don't know what happens if there are more than one image, but that doesn't matter to get it working.

**Comment by dpriskorn** [comment]
There is GPL-3 code here that perhaps could help 
https://github.com/fappels/dolibarrextdirect/blob/c890cdd49da400a47b51b037b37e3f902ea6a365/extdirect/class/ExtDirectProduct.class.php#L1802
