### ISSUE TITLE
Calculate/Sum the Time(in hours) of the events in Tickets - by projects and Third-party

### ISSUE THREAD

**Issue by linkspatrocinados** [Dolibarr/dolibarr#14267]
# Feature Request
Calculate/Sum the Time(in hours) of the events in Tickets - by Projects and Third-parties (filter by months/years)

## Use case
We can open tickets to Third-parties / Projects, its important to know how much time its spend on tickets events. 
How can i see a list of all Third-parties or Projects with the time spend on events resolving issues on Tickets?
In witch Third-parties or Projects the support team that resolve the tickets, spend more time(events in tickets)?
in each Third-parties and Projects:
- on the Tickets tab appear the total time of the events (inside each ticket)
- on the Events/agenda Tab apear in the list the total time spend (in hours) of the event.
- on each Project inside Time Spend tab include the events inside tickets.
On Tickets side bar, apear in left side bar the option of list of Third-parties and Project with resume (nr of tickets, time of all tickets (from open to closed), time spend to resolve (time of the events inside all tickets), all this with a filter by a select period or by month and year.

**Comment by BebZ** [comment]
Hello the optional module ticketsup should make what you need, there is a time calculation I guess on time spent...
Check on dolistore

**Comment by linkspatrocinados** [comment]
I checked but its not what was request
