### ISSUE TITLE
SQL error on new supplier credit note

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#14263]
# Bug
If you set the hidden option INVOICE_CREDIT_NOTE_STANDALONE to 1 and try to create a new supplier credit note a sql error occured.

## Environment
- **Version**: 11.0.x

## Expected and actual behavior
You need to create a supplier credit note whithout any source invoice.

## Steps to reproduce the behavior
1. set the hidden option INVOICE_CREDIT_NOTE_STANDALONE to 1
1. start for a new supplier credit note without source invoice (let the field blank)
1. try to add it

## Solution
Change the file ../htdocs/fourn/class/fournisseur.facture.class.php on line 420 (v11.0.5)
from `$sql.= ", ".(isset($this->fk_facture_source)?$this->fk_facture_source:"NULL");`
to `$sql .= ", ".($this->fk_facture_source ? "'".$this->db->escape($this->fk_facture_source)."'" : "null");`

Best regards,
Sylvain Legrand.

**Comment by dpriskorn** [comment]
Thanks for reporting this and providing a solution. Could you create a pull request for this?
