### ISSUE TITLE
Bug: negative value in an invoice 

### ISSUE THREAD

**Issue by yorkhood** [Dolibarr/dolibarr#14261]
# Bug
I have an invoice which I want to added negative value such as discount 
The scenario is,  the supplier offers me $150 discount and I offer $100 discount to my customer.  
I create a product item called discount, and add it to the invoice, with price -100 and cost -150.  
The price calculation is correct, it deduct 100 from the total value. However, the cost calculation is wrong, instead of deduction, it adds 150 to the total cost.  I guess in the formula, absolute value for cost is used.  

Please see the attached screenshot for details.  

## Environment
- **Version**: 12.0.1
- **OS**: CentOS 8
- **Web server**: Apache 1.2
- **PHP**: 7
- **Database**: MySQL 8
- **URL(s)**: compta/facture/card.php?id=84#line_173

![image](https://user-images.githubusercontent.com/26512905/87873604-8db76b80-c9f5-11ea-975b-a15277321af9.png)

**Comment by eldy** [comment]
To make commercial discount, you must not create a physical product. it is not.
Just create a "discount" with the link "absolute discount" on the thirdparty record. Then when your invoice is in draft status, your are able to "consume" the discount".

**Comment by atm-maxime** [comment]
And yet many users use a service called "discount" to have an accountancy code and statistics about discounts...
