### ISSUE TITLE
Sending email if there's error during cron processing

### ISSUE THREAD

**Issue by atm-quentin** [Dolibarr/dolibarr#14266]
# Sending email if there's error during cron processing
When cron running every short period , we sometimes dont check if cron ran well, sending an email allow us to be warned

## Use case
You launch cron, it's getting error, you receive an email with the cron output

## Suggested implementation
If conf is activated and cron send error code then send mail to error mail

## Suggested steps
- Create conf
- Check if email is filled
- If cron send an error code, send email with output and in subject Error Cron "name of cron"

**Comment by atm-quentin** [comment]
@atm-john @atm-maxime @ATM-Nicolas @atm-lena @atm-gauthier @atm-greg @atm-florianm

**Comment by atm-maxime** [comment]
Still wanted 😊

**Comment by atm-quentin** [comment]
@eldy

**Comment by atm-maxime** [comment]
Still would be useful
