### ISSUE TITLE
Configuration des limites et précisions : impossble de changer les valeurs

### ISSUE THREAD

**Issue by maxoghana** [Dolibarr/dolibarr#14272]
Bonsoir,

J'essaye de changer les limites et précisions dans la partie configuration mais j'ai beau changer les paramètres, lorsque je clique ensuite sur "enregistrer", les changeùents ne sont pas pris en compte et je me retrouve avec les anciennes valeurs des paramètres
Je suis en 12.0.1

Est ce un bug ?

**Comment by ksar-ksar** [comment]
Hi,

On GitHub you should use English only.
For French, go to https://www.dolibarr.fr/forum/

**Comment by eldy** [comment]
This has been fixed. Should be available with 12.0.2 soon
