### ISSUE TITLE
Bug CSRF and importation

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#14278]
If the hidden option MAIN_SECURITY_CSRF_WITH_TOKEN is enabled, when running the import simulation (step 5), we get the message:
```
Access by POST method refused by CSRF protection in main.inc.php. Token not provided. If you access your server behind a proxy using url rewriting, you might check that all HTTP header is propagated (or add the line $dolibarr_nocsrfcheck=1 into your conf.php file or MAIN_SECURITY_CSRF_WITH_TOKEN to 0 into setup).
```

This bug affects Dolibarr 11 and earlier versions. Between Dolibarr 10 and 11, the implementation of the CSRF changed. How can I fix it? I do 2 PR?

## Environment
- **Version**: Dolibarr 10 & 11
- **OS**: All
- **Web server**: All
- **PHP**: All
- **Database**: All
- **URL(s)**: /imports/import.php

**Comment by eldy** [comment]
Because MAIN_SECURITY_CSRF_WITH_TOKEN is not yet a stable official option (still in dev in v10, v11, v12), PR for develop is enough.

**Comment by tuxgasy** [comment]
Already fixed in dev.
