### ISSUE TITLE
modules stop appearing working

### ISSUE THREAD

**Issue by ajtel** [Dolibarr/dolibarr#14280]
berfore update from 11.x.x version to 12.0.0 some modules appear in blcak, expamle quotes... i have qoutoes in some customers, if i open it still white the main scree like no module has nothing...  any idea?

**Comment by ksar-ksar** [comment]
Hi,

It is quiet unclear what is happening to you.
We need more details, screenshots logs, etc...

Could you create a topic on the forum ?
https://www.dolibarr.org/forum/

Thanks

**Comment by ajtel** [comment]
ASI SE VE EL RESULTADO EN MODO DESARROLLO COMO LO ENVIA EN EL MODULO QUE NO FUNCIONA



------------

<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex,nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="Dolibarr Development Team">
<link rel="shortcut icon" type="image/x-icon" href="/facturacion/viewimage.php?cache=1&modulepart=mycompany&file=logos%2Fthumbs%2FAJ-SINRECORTES_mini.jpg"/>
<link rel="manifest" href="/facturacion/theme/eldy/manifest.json.php" />
<meta name="theme-color" content="rgb(46,74,150)">
<title>Cotizaci&oacute;n</title>

<link rel="stylesheet" type="text/css" href="/facturacion/includes/jquery/css/base/jquery-ui.css?layout=classic&amp;version=12.0.1">
<link rel="stylesheet" type="text/css" href="/facturacion/includes/jquery/plugins/jnotify/jquery.jnotify-alt.min.css?layout=classic&amp;version=12.0.1">
<link rel="stylesheet" type="text/css" href="/facturacion/includes/jquery/plugins/select2/dist/css/select2.css?layout=classic&amp;version=12.0.1">

<link rel="stylesheet" type="text/css" href="/facturacion/theme/common/fontawesome-5/css/all.min.css?layout=classic&amp;version=12.0.1">
<link rel="stylesheet" type="text/css" href="/facturacion/theme/common/fontawesome-5/css/v4-shims.min.css?layout=classic&amp;version=12.0.1">

<link rel="stylesheet" type="text/css" href="/facturacion/theme/eldy/style.css.php?lang=es_MX&amp;theme=eldy&amp;userid=1&amp;entity=1&amp;layout=classic&amp;version=12.0.1&amp;revision=21">

<link rel="stylesheet" type="text/css" href="/facturacion/h2g2/css/h2g2.css.php?lang=es_MX&amp;theme=eldy&amp;userid=1&amp;entity=1&amp;layout=classic&amp;version=12.0.1&amp;revision=21">

<link rel="stylesheet" type="text/css" href="/facturacion/h2g2/css/c42location.css.php?lang=es_MX&amp;theme=eldy&amp;userid=1&amp;entity=1&amp;layout=classic&amp;version=12.0.1&amp;revision=21">

<link rel="stylesheet" type="text/css" href="/facturacion/h2g2/css/leaflet.css">

<link rel="stylesheet" type="text/css" href="/facturacion/timesheet/core/css/timesheet.css">

<link rel="stylesheet" type="text/css" href="/facturacion/?lang=es_MX&amp;theme=eldy&amp;userid=1&amp;entity=1&amp;layout=classic&amp;version=12.0.1&amp;revision=21">

<script src="/facturacion/includes/jquery/js/jquery.min.js?layout=classic&amp;version=12.0.1"></script>
<script src="/facturacion/includes/jquery/js/jquery-ui.min.js?layout=classic&amp;version=12.0.1"></script>
<script src="/facturacion/includes/jquery/plugins/tablednd/jquery.tablednd.min.js?layout=classic&amp;version=12.0.1"></script>
<script src="/facturacion/includes/jquery/plugins/jnotify/jquery.jnotify.min.js?layout=classic&amp;version=12.0.1"></script>
<script src="/facturacion/includes/nnnick/chartjs/dist/Chart.min.js?layout=classic&amp;version=12.0.1"></script>
<script src="/facturacion/includes/jquery/plugins/select2/dist/js/select2.full.min.js?layout=classic&amp;version=12.0.1"></script>

<script>var CKEDITOR_BASEPATH = '/facturacion/includes/ckeditor/ckeditor/';
var ckeditorConfig = '/facturacion/theme/eldy/ckeditor/config.js?layout=classic&amp;version=12.0.1';
var ckeditorFilebrowserBrowseUrl = '/facturacion/core/filemanagerdol/browser/default/browser.php?Connector=/facturacion/core/filemanagerdol/connectors/php/connector.php';
var ckeditorFilebrowserImageBrowseUrl = '/facturacion/core/filemanagerdol/browser/default/browser.php?Type=Image&Connector=/facturacion/core/filemanagerdol/connectors/php/connector.php';
</script>
<script src="/facturacion/includes/ckeditor/ckeditor/ckeditor.js?layout=classic&amp;version=12.0.1"></script>
<script>CKEDITOR.disableAutoInline = true;
</script>

<script src="/facturacion/core/js/lib_head.js.php?lang=es_MX&layout=classic&amp;version=12.0.1"></script>

<script src="/facturacion/"></script>

<script src="/facturacion/h2g2/js/h2g2.js.php"></script>

<script src="/facturacion/h2g2/js/leaflet.js"></script>

<script src="/facturacion/custom/contab/js/functions.js"></script>
</head>

<body id="mainbody" class="sidebar-collapse">


<div class="side-nav-vert"><div id="id-top"><div id="tmenu_tooltip" class="tmenu">
<div class="tmenudiv"><ul role="navigation" class="tmenu">

<li class="tmenu tmenucompanylogo nohover" id="mainmenutd_companylogo"><div class="tmenucenter"><div class="center backgroundforcompanylogo menulogocontainer"><img class="mycompany" title="Vaya a Inicio-&gt;Configuraci&oacute;n-&gt;Empresa/Instituci&oacute;n para cambiar el logo o vaya a Inicio-&gt;Configuraci&oacute;n-&gt;Entorno para ocultarlo" alt="" src="/facturacion/viewimage.php?cache=1&amp;modulepart=mycompany&amp;file=logos%2Fthumbs%2FAJ-SINRECORTES_mini.jpg" style="max-width: 100px"></div>
</div></li>
<li class="tmenu menuhider" id="mainmenutd_menu"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="#" title=""><div class="mainmenu menu topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_menu"></span></div></a><a class="tmenu menuhider" id="mainmenua_menu" href="#" title=""><span class="mainmenuaspan"></span></a></div></li>
<li class="tmenusel" id="mainmenutd_home"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/index.php?mainmenu=home&amp;leftmenu=home" title="Inicio"><div class="mainmenu home topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_home"></span></div></a><a class="tmenusel" id="mainmenua_home" href="/facturacion/index.php?mainmenu=home&amp;leftmenu=home" title="Inicio"><span class="mainmenuaspan">Inicio</span></a></div></li>
<li class="tmenu" id="mainmenutd_companies"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/societe/index.php?mainmenu=companies&amp;leftmenu=" title="Terceros"><div class="mainmenu companies topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_companies"></span></div></a><a class="tmenu" id="mainmenua_companies" href="/facturacion/societe/index.php?mainmenu=companies&amp;leftmenu=" title="Terceros"><span class="mainmenuaspan">Terceros</span></a></div></li>
<li class="tmenu" id="mainmenutd_products"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/product/index.php?mainmenu=products&amp;leftmenu=" title="Productos | Servicios"><div class="mainmenu products topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_products"></span></div></a><a class="tmenu" id="mainmenua_products" href="/facturacion/product/index.php?mainmenu=products&amp;leftmenu=" title="Productos | Servicios"><span class="mainmenuaspan">Productos | Servicios</span></a></div></li>
<li class="tmenu" id="mainmenutd_mrp"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/mrp/index.php?mainmenu=mrp&amp;leftmenu=" title="MRP"><div class="mainmenu mrp topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_mrp"></span></div></a><a class="tmenu" id="mainmenua_mrp" href="/facturacion/mrp/index.php?mainmenu=mrp&amp;leftmenu=" title="MRP"><span class="mainmenuaspan">MRP</span></a></div></li>
<li class="tmenu" id="mainmenutd_project"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/projet/index.php?mainmenu=project&amp;leftmenu=" title="Proyectos"><div class="mainmenu project topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_project"></span></div></a><a class="tmenu" id="mainmenua_project" href="/facturacion/projet/index.php?mainmenu=project&amp;leftmenu=" title="Proyectos"><span class="mainmenuaspan">Proyectos</span></a></div></li>
<li class="tmenu" id="mainmenutd_commercial"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/comm/index.php?mainmenu=commercial&amp;leftmenu=" title="Comercial"><div class="mainmenu commercial topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_commercial"></span></div></a><a class="tmenu" id="mainmenua_commercial" href="/facturacion/comm/index.php?mainmenu=commercial&amp;leftmenu=" title="Comercial"><span class="mainmenuaspan">Comercial</span></a></div></li>
<li class="tmenu" id="mainmenutd_billing"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/compta/index.php?mainmenu=billing&amp;leftmenu=" title="Financiera"><div class="mainmenu billing topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_billing"></span></div></a><a class="tmenu" id="mainmenua_billing" href="/facturacion/compta/index.php?mainmenu=billing&amp;leftmenu=" title="Financiera"><span class="mainmenuaspan">Financiera</span></a></div></li>
<li class="tmenu" id="mainmenutd_bank"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/compta/bank/list.php?mainmenu=bank&amp;leftmenu=" title="Bancos | Cajas"><div class="mainmenu bank topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_bank"></span></div></a><a class="tmenu" id="mainmenua_bank" href="/facturacion/compta/bank/list.php?mainmenu=bank&amp;leftmenu=" title="Bancos | Cajas"><span class="mainmenuaspan">Bancos | Cajas</span></a></div></li>
<li class="tmenu" id="mainmenutd_accountancy"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/accountancy/index.php?mainmenu=accountancy&amp;leftmenu=" title="Contabilidad"><div class="mainmenu accountancy topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_accountancy"></span></div></a><a class="tmenu" id="mainmenua_accountancy" href="/facturacion/accountancy/index.php?mainmenu=accountancy&amp;leftmenu=" title="Contabilidad"><span class="mainmenuaspan">Contabilidad</span></a></div></li>
<li class="tmenu" id="mainmenutd_hrm"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/hrm/index.php?mainmenu=hrm&amp;leftmenu=" title="RRHH"><div class="mainmenu hrm topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_hrm"></span></div></a><a class="tmenu" id="mainmenua_hrm" href="/facturacion/hrm/index.php?mainmenu=hrm&amp;leftmenu=" title="RRHH"><span class="mainmenuaspan">RRHH</span></a></div></li>
<li class="tmenu" id="mainmenutd_ecm"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/ecm/index.php?idmenu=6359&mainmenu=ecm&amp;leftmenu=" title="Documentos"><div class="mainmenu ecm topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_ecm"></span></div></a><a class="tmenu" id="mainmenua_ecm" href="/facturacion/ecm/index.php?idmenu=6359&mainmenu=ecm&amp;leftmenu=" title="Documentos"><span class="mainmenuaspan">Documentos</span></a></div></li>
<li class="tmenu" id="mainmenutd_agenda"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/comm/action/index.php?idmenu=6341&mainmenu=agenda&amp;leftmenu=" title="Agenda"><div class="mainmenu agenda topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_agenda"></span></div></a><a class="tmenu" id="mainmenua_agenda" href="/facturacion/comm/action/index.php?idmenu=6341&mainmenu=agenda&amp;leftmenu=" title="Agenda"><span class="mainmenuaspan">Agenda</span></a></div></li>
<li class="tmenu" id="mainmenutd_ticket"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/ticket/index.php?idmenu=861&mainmenu=ticket&amp;leftmenu=" title="Ticket"><div class="mainmenu ticket topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_ticket"></span></div></a><a class="tmenu" id="mainmenua_ticket" href="/facturacion/ticket/index.php?idmenu=861&mainmenu=ticket&amp;leftmenu=" title="Ticket"><span class="mainmenuaspan">Ticket</span></a></div></li>
<li class="tmenu" id="mainmenutd_tools"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/core/tools.php?mainmenu=tools&amp;leftmenu=" title="Herramientas"><div class="mainmenu tools topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_tools"></span></div></a><a class="tmenu" id="mainmenua_tools" href="/facturacion/core/tools.php?mainmenu=tools&amp;leftmenu=" title="Herramientas"><span class="mainmenuaspan">Herramientas</span></a></div></li>
<li class="tmenu" id="mainmenutd_cashdesk"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/cashdesk/index.php?user=__LOGIN__&amp;idmenu=27&mainmenu=cashdesk&amp;leftmenu=" target="pointofsale" title="punto de venta"><div class="mainmenu cashdesk topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_cashdesk"></span></div></a><a class="tmenu" id="mainmenua_cashdesk" href="/facturacion/cashdesk/index.php?user=__LOGIN__&amp;idmenu=27&mainmenu=cashdesk&amp;leftmenu=" target="pointofsale" title="punto de venta"><span class="mainmenuaspan">punto de venta</span></a></div></li>
<li class="tmenu" id="mainmenutd_externalsite"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/externalsite/frames.php?idmenu=31&mainmenu=externalsite&amp;leftmenu=" title="$conf-&gt;global-&gt;EXTERNALSITE_LABEL"><div class="mainmenu externalsite topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_externalsite"></span></div></a><a class="tmenu" id="mainmenua_externalsite" href="/facturacion/externalsite/frames.php?idmenu=31&mainmenu=externalsite&amp;leftmenu=" title="$conf-&gt;global-&gt;EXTERNALSITE_LABEL"><span class="mainmenuaspan">$conf->global->EXTERNALSITE_LABEL</span></a></div></li>
<li class="tmenu" id="mainmenutd_ftp"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/ftp/index.php?idmenu=38&mainmenu=ftp&amp;leftmenu=" title="FTP"><div class="mainmenu ftp topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_ftp"></span></div></a><a class="tmenu" id="mainmenua_ftp" href="/facturacion/ftp/index.php?idmenu=38&mainmenu=ftp&amp;leftmenu=" title="FTP"><span class="mainmenuaspan">FTP</span></a></div></li>
<li class="tmenu" id="mainmenutd_lead"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/lead/index.php?idmenu=39&mainmenu=lead&amp;leftmenu=" title="Lead"><div class="mainmenu lead topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_lead"></span></div></a><a class="tmenu" id="mainmenua_lead" href="/facturacion/lead/index.php?idmenu=39&mainmenu=lead&amp;leftmenu=" title="Lead"><span class="mainmenuaspan">Lead</span></a></div></li>
<li class="tmenu" id="mainmenutd_timesheet"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/timesheet/timesheet.php?idmenu=65&mainmenu=timesheet&amp;leftmenu=" title="Parte de Horas"><div class="mainmenu timesheet topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_timesheet"></span></div></a><a class="tmenu" id="mainmenua_timesheet" href="/facturacion/timesheet/timesheet.php?idmenu=65&mainmenu=timesheet&amp;leftmenu=" title="Parte de Horas"><span class="mainmenuaspan">Parte de Horas</span></a></div></li>
<li class="tmenu" id="mainmenutd_contabilidad"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/custom/contab/periodos/fiche.php?idmenu=532&mainmenu=contabilidad&amp;leftmenu=" title="Contab"><div class="mainmenu contabilidad topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_contabilidad"></span></div></a><a class="tmenu" id="mainmenua_contabilidad" href="/facturacion/custom/contab/periodos/fiche.php?idmenu=532&mainmenu=contabilidad&amp;leftmenu=" title="Contab"><span class="mainmenuaspan">Contab</span></a></div></li>
<li class="tmenu" id="mainmenutd_cfdimx"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/cfdimx/index.php?idmenu=724&mainmenu=cfdimx&amp;leftmenu=" title="CFDI"><div class="mainmenu cfdimx topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_cfdimx"></span></div></a><a class="tmenu" id="mainmenua_cfdimx" href="/facturacion/cfdimx/index.php?idmenu=724&mainmenu=cfdimx&amp;leftmenu=" title="CFDI"><span class="mainmenuaspan">CFDI</span></a></div></li>
<li class="tmenu" id="mainmenutd_takepos"><div class="tmenucenter"><a class="tmenuimage" tabindex="-1" href="/facturacion/takepos/index.php?idmenu=6366&mainmenu=takepos&amp;leftmenu=" target="takepos" title="TPV"><div class="mainmenu takepos topmenuimage"><span class="mainmenu tmenuimage" id="mainmenuspan_takepos"></span></div></a><a class="tmenu" id="mainmenua_takepos" href="/facturacion/takepos/index.php?idmenu=6366&mainmenu=takepos&amp;leftmenu=" target="takepos" title="TPV"><span class="mainmenuaspan">TPV</span></a></div></li>
<li class="tmenuend" id="mainmenutd_"><div class="tmenucenter"></div></li>
</ul></div>
</div>
<div class="login_block usedropdown">
<div class="login_block_other"><div class="inline-block"><div class="classfortooltip inline-block login_block_elem inline-block" style="padding: 0px; padding: 0px; padding-right: 3px !important;" title="Click to open Chat."><a href="/facturacion/comm/propal/card.php?tawktotoggle=1"><span class="fa fa-comment-o atoplogin"></span></a></div></div>
<div class="inline-block"><div class="classfortooltip inline-block login_block_elem inline-block" style="padding: 0px; padding: 0px; padding-right: 3px !important;" title="Mostrar la p&aacute;gina para imprimir el &aacute;rea de contenido principal"><a href="/facturacion/comm/propal/card.php?id=116&optioncss=print" target="_blank"><span class="fa fa-print atoplogin valignmiddle"></span></a></div></div><div class="inline-block"><div class="classfortooltip inline-block login_block_elem inline-block" style="padding: 0px; padding: 0px; padding-right: 3px !important;" title="Leer la ayuda en l&iacute;nea (es necesario acceso a Internet ) - P&aacute;gina Wiki &quot;Presupuestos&quot;"><a class="help" target="_blank" rel="noopener" href="http://wiki.dolibarr.org/index.php/Presupuestos"><span class="fa fa-question-circle atoplogin valignmiddle"></span></a></div></div><div class="inline-block"><div class="classfortooltip inline-block login_block_elem inline-block" style="padding: 0px; padding: 0px; padding-right: 3px !important;" title="Dolibarr 12.0.1&lt;br&gt;Nivel de caracter&iacute;sticas: 2"><span href="#" class="aversion"><span class="hideonsmartphone small">12.0.1</span></span></div></div><div class="inline-block"><div class="classfortooltip inline-block login_block_elem logout-btn inline-block" style="padding: 0px; padding: 0px; padding-right: 3px !important;" title="Desconexi&oacute;n&lt;br&gt;"><a accesskey="l" href="/facturacion/user/logout.php"><span class="fas fa-sign-out-alt atoplogin" style="" title="Desconexi&oacute;n"></span></a></div></div></div><div class="login_block_user"><div class="inline-block nowrap"><div class="inline-block login_block_elem login_block_elem_name" style="padding: 0px;">
	        <div id="topmenu-bookmark-dropdown" class="dropdown inline-block">
	            <a class="dropdown-toggle login-dropdown-a" data-toggle="dropdown" href="#" title="Marcadores (Ctrl + shift + m)">
	                <i class="fa fa-star" ></i>
	            </a>
	            <div class="dropdown-menu">
	                
	        
	        <div class="dropdown-header bookmark-header">
	            
<form id="top-menu-action-bookmark" name="actionbookmark" method="POST" action="" onsubmit="return false"><input type="hidden" name="token" value="0598a9474cf850f9791aeefcfbb13d20"><input name="bookmark" id="top-bookmark-search-input" class="dropdown-search-input" placeholder="Marcadores" autocomplete="off" ></form>
	        </div>
	        
	        
	        <div class="bookmark-body dropdown-body">
	        <div id="dropdown-bookmarks-list" ></div>
	        </div>
	        
	        
	        <div class="bookmark-footer">
	                <a class="top-menu-dropdown-link" title="A&ntilde;adir esta p&aacute;gina a los marcadores" href="/facturacion/bookmarks/card.php?action=create&amp;url=%2Ffacturacion%2Fcomm%2Fpropal%2Fcard.php%3Fid%3D116" ><span class="far fa-star paddingright" style=""></span>A&ntilde;adir esta p&aacute;gina a los marcadores</a><a class="top-menu-dropdown-link" title="A&ntilde;adir esta p&aacute;gina a los marcadores" href="/facturacion/bookmarks/list.php" ><span class="fa fa-list paddingright"></span>Marcadores</a>
	            <div style="clear:both;"></div>
	        </div>
	    
				<script>
	            $( document ).on("keyup", "#top-bookmark-search-input", function () {

	                var filter = $(this).val(), count = 0;
	                $("#dropdown-bookmarks-list .bookmark-item").each(function () {

	                    if ($(this).text().search(new RegExp(filter, "i")) < 0) {
	                        $(this).addClass("hidden-search-result");
	                    } else {
	                        $(this).removeClass("hidden-search-result");
	                        count++;
	                    }
	                });
	                $("#top-bookmark-search-filter-count").text(count);
	            });
			    </script>
	            </div>
	        </div>
	        
	        <script>
	        $( document ).ready(function() {
	            $(document).on("click", function(event) {
	                if (!$(event.target).closest("#topmenu-bookmark-dropdown").length) {
						//console.log("close bookmark dropdown - we click outside");
	                    // Hide the menus.
	                    $("#topmenu-bookmark-dropdown").removeClass("open");
	                }
	            });

	            $("#topmenu-bookmark-dropdown .dropdown-toggle").on("click", function(event) {
					console.log("toggle bookmark dropdown");
					openBookMarkDropDown();
	            });

	            // Key map shortcut
	            $(document).keydown(function(e){
	                  if( e.which === 77 && e.ctrlKey && e.shiftKey ){
	                     console.log('control + shift + m : trigger open bookmark dropdown');
	                     openBookMarkDropDown();
	                  }
	            });


	            var openBookMarkDropDown = function() {
	                event.preventDefault();
	                $("#topmenu-bookmark-dropdown").toggleClass("open");
	                $("#top-bookmark-search-input").focus();
	            }

	        });
	        </script>
	        
	    <div id="topmenu-login-dropdown" class="userimg atoplogin dropdown user user-menu inline-block">
	        <a href="/facturacion/user/card.php?id=1" class="dropdown-toggle login-dropdown-a" data-toggle="dropdown">
	            <img alt="Photo" class="photouserphoto photouserphoto userphoto photologo__thumbs_IMG__________WA_____small_jpg"  src="/facturacion/viewimage.php?modulepart=userphoto&entity=1&file=1%2Fthumbs%2FIMG-20151218-WA0001_small.jpg&cache=1">
	            <span class="hidden-xs maxwidth200 atoploginusername hideonsmartphone paddingleft">Andre</span>
	        </a>
	        <div class="dropdown-menu">
	            
	            <div class="user-header">
	                <img alt="Photo" class="photouserphoto dropdown-user-image photologo__thumbs_IMG__________WA_____small_jpg"  src="/facturacion/viewimage.php?modulepart=userphoto&entity=1&file=1%2Fthumbs%2FIMG-20151218-WA0001_small.jpg&cache=1">
	                <p>
	                    <i class="far fa-star classfortooltip" title="Administrador" ></i> Andre Vivar Balderrama (andrevivar)<br><small class="classfortooltip" title="Conexi&oacute;n anterior" ><i class="fa fa-user-clock"></i> 10:48 PM 22/07/2020</small><br><small class="classfortooltip"><i class="fa fa-cog"></i> Version Dolibarr 12.0.1</small>
	                </p>
	            </div>

	            
	            <div class="user-body"><span id="topmenuloginmoreinfo-btn"><i class="fa fa-caret-right"></i> Mostrar m&aacute;s informaci&oacute;n</span><div id="topmenuloginmoreinfo" ><br><b>Administrador</b>: S&iacute;<br><b>Tipo:</b> Interno<br><b>Estado</b>: Habilitado<br><br><u>Session</u><br><b>Direcci&oacute;n IP</b>: 187.178.80.168<br><b>Modo de autentificaci&oacute;n:</b> dolibarr<br><b>Conectado desde:</b> 09:26 AM 23/07/2020<br><b>Conexi&oacute;n anterior:</b> 10:48 PM 22/07/2020<br><b>Tema actual:</b> eldy<br><b>Administrador de men&uacute; actual:</b> eldy<br><b>Idioma actual:</b> <img src="/facturacion/theme/common/flags/mx.png" alt="" title="es_MX" class="inline-block"> es_MX<br><b>Navegador:</b> chrome 84.0.4147.89 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36)<br><b>Presentaci&oacute;n:</b> classic<br><b>Pantalla:</b> 1778 x 841</div></div>

	            
	            <div class="user-footer">
	                <div class="pull-left">
	                    <a accesskey="l" href="/facturacion/user/card.php?id=1" class="button-top-menu-dropdown" ><i class="fa fa-user"></i>  Ficha</a>
	                </div>
	                <div class="pull-right">
	                    <a accesskey="l" href="/facturacion/user/logout.php" class="button-top-menu-dropdown" ><i class="fa fa-sign-out-alt"></i> Desconexi&oacute;n</a>
	                </div>
	                <div style="clear:both;"></div>
	            </div>

	        </div>
	    </div>
        
        <script>
        $( document ).ready(function() {
            $(document).on("click", function(event) {
                if (!$(event.target).closest("#topmenu-login-dropdown").length) {
					//console.log("close login dropdown");
					// Hide the menus.
                    $("#topmenu-login-dropdown").removeClass("open");
                }
            });
			
	            $("#topmenu-login-dropdown .dropdown-toggle").on("click", function(event) {
					console.log("toggle login dropdown");
					event.preventDefault();
	                $("#topmenu-login-dropdown").toggleClass("open");
	            });

	            $("#topmenuloginmoreinfo-btn").on("click", function() {
	                $("#topmenuloginmoreinfo").slideToggle();
	            });
        });
        </script>
        </div></div></div>
</div>
</div></div><div style="clear: both;"></div>

<div id="id-container" class="id-container">

<div class="side-nav"><div id="id-left">


<div class="vmenu">



<div id="blockvmenusearch" class="blockvmenusearch">
<select type="text" class="searchselectcombo vmenusearchselectcombo" name="searchselectcombo"><option></option></select></div>

<div class="blockvmenu blockvmenupair blockvmenufirst">

<div class="menu_titre"><a class="vmenu" title="Mi panel de control" href="/facturacion/index.php?mainmenu=home&amp;leftmenu=home"><i class="fa fa-bar-chart fa-fw paddingright"></i>Mi panel de control</a></div>
<div class="menu_top"></div>
<div class="menu_end"></div>
</div>
<div class="blockvmenu blockvmenuimpair">

<div class="menu_titre"><a class="vmenu" title="Configuraci&oacute;n" href="/facturacion/admin/index.php?mainmenu=home&amp;leftmenu=setup"><i class="fa fa-wrench fa-fw paddingright"></i>Configuraci&oacute;n</a></div>
<div class="menu_top"></div>
<div class="menu_end"></div>
</div>
<div class="blockvmenu blockvmenupair">

<div class="menu_titre"><a class="vmenu" title="Herramientas de administraci&oacute;n" href="/facturacion/admin/tools/index.php?mainmenu=home&amp;leftmenu=admintools"><i class="fa fa-server fa-fw paddingright"></i>Herramientas de administraci&oacute;n</a></div>
<div class="menu_top"></div>
<div class="menu_end"></div>
</div>
<div class="blockvmenu blockvmenuimpair blockvmenulast">

<div class="menu_titre"><a class="vmenu" title="Usuarios y grupos" href="/facturacion/user/home.php?leftmenu=users"><i class="fa fa-users fa-fw paddingright"></i>Usuarios y grupos</a></div>
<div class="menu_top"></div>
<div class="menu_end"></div>
</div>
<div class="blockvmenuend"></div>

<div id="blockvmenuhelp" class="blockvmenuhelp">
</div>


</div>



};
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5a91be4e4b401e45400d2ddc/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script></div></div> 

<div id="id-right">

<div class="fiche">

**Comment by eldy** [comment]
Trouble seems to come from external modules, not from v12 itself.
It seems you are using external module. External non official modules may not be compatible with v12
So you should disable them (before migrating to v12 or after if you can, or upgrade them to a version compatible with v12)
