### ISSUE TITLE
REST post to /products/{id}/purchase_prices gives 500 error in rest explorer and does not accept field "import_key" on endpoint

### ISSUE THREAD

**Issue by swedebugia** [Dolibarr/dolibarr#14282]
# Bug
fails silently on endpoint and enters all but the field mentioned.
in rest explorer fails with the error below no matter what I do.

## Environment
- **Version**: 12

## Expected and actual behavior
Does not insert "import_key" into the db.

## Steps to reproduce the behavior
data={'buyprice': 40.22, 'price_base_type': 'ttc', 'tva_tx': 0, 'fourn_id': '705', 'ref_fourn': '231461', 'delivery_time_days': 8, 'qty': 1, 'availability': 0, 'import_key': 'Import from script'}                                                                                                                     
    r=d.call_action_api("products",product_id,"purchase_prices",data)
using python-doli or 

{"buyprice": 40.22, "price_base_type": "ttc", "tva_tx": 0, "fourn_id": "705", "ref_fourn": "231461", "delivery_time_days": 8, "qty": 1, "availability": 0, "import_key": "Import from script"}
using rest explorer which renders this error:
{
  "error": {
    "code": 500,
    "message": "Internal Server Error: Error adding supplier to product : "
  },
  "debug": {
    "source": "api_products.class.php:683 at call stage",
    "stages": {
      "success": [
        "get",
        "route",
        "negotiate",
        "authenticate",
        "validate"
      ],
      "failure": [
        "call",
        "message"
      ]
    }
  }
}

**Comment by fappels** [comment]
Think same as https://github.com/Dolibarr/dolibarr/issues/14259 and fixed here https://github.com/Dolibarr/dolibarr/commit/ee74740384cdb0b63aaa31bdeea61a16c8908529
