### ISSUE TITLE
Elephant autoref does not autoincrement and suggest existing ref

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14293]
# Bug
Error message: "A product with reference already exists." <- I got when trying to save

## Environment
- **Version**: 12
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: 7.4
- **Database**: pgsql
- **URL(s)**: http://dolibarr.localhost/product/card.php

## Expected and actual behavior
I expected it to suggest a non existing ref based on the last ref added +1

## Steps to reproduce the behavior
enable autoref
create 1 product 
create another product ->error

**Comment by eldy** [comment]
Try to set field ref = 'auto'

**Comment by dpriskorn** [comment]
I think the field should be greyed out/Disabled and a ?-symbol with the text "Autoref is enabled." After it.
