### ISSUE TITLE
Products not for sale or purchase still show up in tags/categories drop-down box.

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14294]
# Bug
products show up and adds clutter. Its annoying when you have lots of "archived" products to scroll by.

## Environment
- **Version**: 12
- **URL(s)**: http://dolibarr.localhost/categories/index.php?leftmenu=cat&type=0

## Expected and actual behavior
I expected them to be "archived"/"hidden" when neither for sale or purchase

**Comment by dpriskorn** [comment]
can someone confirm this is still present?

**Comment by erikvanberkum** [comment]
In version 14 this is still present, but I am not sure if this is a bug. Products not for sale or purchase I give the Tag "End-of-Life". This can be useful for some users. It would be better to mark it as a feature request / discussion.

**Comment by atm-maxime** [comment]
I agree that having the possibility to add a product to a tag for all products, even those that are not for sale or for purchase anymore is standard behavior.
Tag association is not related to whether the product is for sale/purchase or not

**Comment by dpriskorn** [comment]
I understand, so a new field to archive/hide a product would solve both usecases. But of course it adds a little complexity so it might not be worth it.

**Comment by dpriskorn** [comment]
> 
> 
> In version 14 this is still present, but I am not sure if this is a bug. Products not for sale or purchase I give the Tag "End-of-Life". This can be useful for some users. It would be better to mark it as a feature request / discussion.

That is a good idea. I had not thought about that. :)

**Comment by erikvanberkum** [comment]
Third parties, contacts, have a disable button, it would perfectly make sense to implement the same button for products.
