### ISSUE TITLE
Support archiving of products/services

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14296]
# Feature Request
Archive feature.
I used Odoo before swiching to Dolibarr. In Odoo there were a button that enabled archiving of a product to hide it from the whole interface.

## Use case
hide no longer needed/wanted products that cannot be deleted

## Suggested implementation
a new boolean column in llx_products: archived
0=false
1=true

## Suggested steps
add column
add logic to products/*.php - especially list.php

**Comment by dpriskorn** [comment]
still relevant

**Comment by atm-maxime** [comment]
Archiving a product means setting setting the product not for sale and not for purchase. I think there's no need for a new field

**Comment by dpriskorn** [comment]
My issue with that is that it leaves a lot of clutter when searching. I want to hide the clutter easily.

**Comment by dpriskorn** [comment]
Still relevant in v15?

**Comment by atm-maxime** [comment]
Didn't saw your last answer. What do you mean by "clutter when searching" ? For me I simply defined default filters on product list to search for "on sale" ones. And disabled products don't show up in search for adding a line in a proposal for example

**Comment by dpriskorn** [comment]
Oh, that sounds like a workaround. I would like something more user friendly. 1-click solution.
