### ISSUE TITLE
Dolibarr assumes that purchase orders are invoiced for even unreceived products when creating invoice after partially receiving gods.

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14301]
# Feature Request
I would really like an option to turn on ONLY invoicing lines (and quantity) that are received instead.
 
## Use case
my bike parts suppliers do not invoice products that are missing from the first shipment.

## Suggested implementation
dunno, a setting on the settings page for invoice of the purchase module would be nice. Maybe a setting per supplier makes most sense as it can differ from supplier to supplier.

## Suggested steps
no idea. If someone wishes to help me pseudo code it I would be very happy.

**Comment by dpriskorn** [comment]
still relevant

**Comment by atm-maxime** [comment]
Try to use the new reception module. That way you can record an invoice reflecting the real reception

**Comment by dpriskorn** [comment]
I'll close this as it seems to be fixed :)
