### ISSUE TITLE
pmp column in llx_product cannot be updated in the interface and it leads to wrong stock valuation sometimes

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14302]
# Bug
pmp should be editable or be updated when a purchase price is edited.

## Environment
- **Version**: 12
- **URL(s)**: http://dolibarr.localhost/product/fournisseurs.php

## Expected and actual behavior
I changed minimum quantity on the only purchase price of a product but the pmp did not get updated. Thats a bug IMO.

## Steps to reproduce the behavior
create purchase price with min qty:10
edit the purchase price to min qty:1
pmp is now wrong.

**Comment by atm-maxime** [comment]
Pmp is a calculation based on stock entries. It changes when a new entry is made (manually or by making a supplier order reception). So it's normal it doesn't change when you change qty min of purchase price. The only thing that should change in this case is the unit price.

**Comment by dpriskorn** [comment]
Thanks for clarifying that. I manually updated the wrong pmp in llx_product and the latest wrong price on the last stock movement of the product in llx_stock_movement and now the stock value calculation is correct 😀
