### ISSUE TITLE
Unable to access Permissions using Dolibarr 12.0.1

### ISSUE THREAD

**Issue by p-abella** [Dolibarr/dolibarr#14303]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Using Dolibarr 12.0.1 I tried to see and modify the Permissions assigned to users, but every time I select Permissions for the current user or for another user when login as Admin, an empty page appears.
I would accept any help to find out where is the problem.
After having upgraded many times this dolibarr installation (initial installation 3.7.1), I found that on some upgrades not all the database tables have been complete updated. Maybe that could be part of the problem???

## Environment
- **Version**: 12.0.1
- **OS**: Linux s16.infinitysrv.com 3.10.0-962.3.2.lve1.5.26.4.el7.x86_64 #1 SMP Wed Sep 11 10:29:54 EDT 2019 x86_64
- **Web server**: Apache
- **PHP**: 5.6.40
- **Database**: 10.3.23-MariaDB - MariaDB Server 
- **URL(s)**:

## Expected and actual behavior
Expected: show available (active & inactive) Permission for the selected user.
Actual: a blank page is presented when Permissions page is selected for any user or Group

## Steps to reproduce the behavior
Every time the Permissions page is selected (for users or groups) a blamk page is loaded

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Screenshot_2020-07-27 About Dolibarr](https://user-images.githubusercontent.com/37841162/88606848-ba016680-d04b-11ea-8819-32bc8f4ebccd.png)
![Screenshot_2020-07-27 User card](https://user-images.githubusercontent.com/37841162/88606963-0056c580-d04c-11ea-99a2-7a787d30a5a7.png)
![Screenshot_2020-07-27 Permissions](https://user-images.githubusercontent.com/37841162/88606964-00ef5c00-d04c-11ea-8163-4a2313db9e37.png)

**Comment by dpriskorn** [comment]
Hi. Do you have the logging module enabled? What does the log say?

**Comment by p-abella** [comment]
Searching on the code, closed the issue to the combination of Mysql /php.
I copied all the site to a dev environment and all worked Ok.
Dev environment: PHP 7.4.8 , Database: MySQL or MariaDB 8.0.21-0ubuntu0.20.04.3, Database driver type: mysqli (mysqlnd 7.4.8)
Prod environment: PHP 5.6.40, Database: MySQL or MariaDB 10.3.23-MariaDB, Database driver type: mysqli (10.3.11-MariaDB)
On Dev environment forks fine,
On Prod environment I get the attached

 error:

**Comment by p-abella** [comment]
> Hi. Do you have the logging module enabled? What does the log say?

Tell me what logging module is needed and how to activate it and I will do it.
The Prod environment is running on a ISP site (X10premium.com) so not everything is accessible or customizable

**Comment by ksar-ksar** [comment]
Blank page usually mean PHP error.
Could you check the apache logs ?

**Comment by p-abella** [comment]
Solved.
Updating from PHP 5.6 to PHP 7-4 the error dissapeared.
it was on htdocs/core/lib/date.lib.php on the Datetime __construct call
Here the error_log:
[08-Aug-2020 15:18:51 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home/inninggr/public_html/dolibarr/core/lib/date.lib.php:134
Stack trace:
#0 /home/inninggr/public_html/dolibarr/core/lib/date.lib.php(134): DateTime->__construct('2020-07-27')
#1 /home/inninggr/public_html/dolibarr/core/modules/modAdherent.class.php(352): dol_time_plus_duree(1596899931, 1, 'y')
#2 /home/inninggr/public_html/dolibarr/user/perms.php(165): modAdherent->__construct(Object(TraceableDB))
#3 {main}
  thrown in /home/inninggr/public_html/dolibarr/core/lib/date.lib.php on line 134
[error_log.txt](https://github.com/Dolibarr/dolibarr/files/5045467/error_log.txt)

**Comment by dpriskorn** [comment]
Does this mean we should bump minimum supported php version?

**Comment by p-abella** [comment]
Maybe.
Iḿ not sure about the reason of the error or how to copmply with PHP 5.6 restrictions:
"PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home/inninggr/public_html/dolibarr/core/lib/date.lib.php:134"
I will try to get more information about this error and will post if it could be solved for PHP 5.6

**Comment by p-abella** [comment]
On the sentence that collapses Dolibarr (htdocs/core/modules/modAdherent.class.php, line 352 there is a comment about possible fails using old databases:
334:        if ($resql)    // This can fail when class is used on old database (during migration for example)

The file header says las modification was made by Alexandre Spangaro <aspangaro@open-dsi.fr>, but I can not know if that comment was put by him

My idea is that there is an incongruency between SQL and PHP date format that collapses dolibarr

**Comment by dpriskorn** [comment]
This commit introduced the comment.
https://github.com/Dolibarr/dolibarr/commit/1c07006015b94f202a8a95795cd80ae8a3462b9c
