### ISSUE TITLE
No proposal of existing lot number for a component when creating a MO

### ISSUE THREAD

**Issue by slotic** [Dolibarr/dolibarr#14318]
# Bug
No proposal of existing lot number when creating a MO

## Environment
- **Version**: 12.0.1
- **OS**: Ubuntu 16.0.4
- **Web server**: Apache
- **PHP**: PHP 7.2
- **Database**: Postgresql
- **URL(s)**: N/A

## Expected and actual behavior
Existing and mandatory lot number on a component -> creating a MO should display a list of available lots when component have some, whatever is the setting on the manufactured product.. Just because without this drop-down list it's just unusable as you have to keep a list on paper of the available lots in order to type the one(s) you want to consume

Plus the fact that you can have to consume several lots of the same component in your MO...

So no list, no MO -> designed as a bug because it makes the module just unusable in the most common conditions

(The 2d message for the mandatory lot number on the manufactured product is normal because i didn't write it)

## Steps to reproduce the behavior
Just create a MO, component has lot/serial mandatory, a lot is existing, no lot is proposed

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
[20200729_Mo.pdf](https://github.com/Dolibarr/dolibarr/files/4997580/20200729_Mo.pdf)

**Comment by BebZ** [comment]
Hello 

Is it a blocking bug for your production at the moment or is it a test ? 

Because I can maybe share a module for virtual products handling batch / lot numbers and expiry dates ;)

But anyway using M.O. will be recommended in the future when the module will be stable and with full options ;)

**Comment by cfoellmann** [comment]
This is a blocker for us too.
This is just mandatory.  in my case I need to use 100 serialized components of 1 product and it makes no sense to consume 1 at a time and also without suggestion of available lots.

**Comment by fbosman** [comment]
We also need the lotnummers for the used product in the MO, just like they are used in a shipment.
