### ISSUE TITLE
unable to set birth date before 2010

### ISSUE THREAD

**Issue by alculete** [Dolibarr/dolibarr#14312]
# Bug
Unable to set birthdate before 2010

## Environment
- **Version**: 12.0.1
- **OS**: Ubuntu Server 18.04 
- **Web server**: apache 2.4
- **PHP**: PHP 7.4.8
- **Database**:  Ver 15.1 Distrib 10.5.4-MariaDB

## Expected and actual behavior
set date before 2010

## Steps to reproduce the behavior
[create new user > try to set birthdate 

## [Attached files]
![image](https://user-images.githubusercontent.com/2129497/88690070-90077d00-d0fb-11ea-8b65-3701e7fcd884.png)

**Comment by atm-maxime** [comment]
Try selecting 2010 and opening the list again.
Or just type the date with keyboard.

**Comment by alculete** [comment]
Selecting 2010 worked. Thank you
