### ISSUE TITLE
Extrafield type 'date' on supplier price not saving correctly

### ISSUE THREAD

**Issue by tomVertuoz** [Dolibarr/dolibarr#14314]
# Bug
Extrafield type 'date' on supplier price not saving correctly while editing.

## Environment
- **Version**: 12.0.1
- **Web server**: APACHE2
- **PHP**: 7.3
- **Database**: MYSQL

## Expected and actual behavior
We have 2 dates extrafields on supplier price, when we save, dates are not saving properly in database.

## Steps to reproduce the behavior
Cf screenshot

[*Files*]
![Capture d’écran 2020-07-29 à 12 00 54](https://user-images.githubusercontent.com/15628945/88786842-4f5b4280-d193-11ea-8895-6326e16a7629.png)
![Capture d’écran 2020-07-29 à 12 01 07](https://user-images.githubusercontent.com/15628945/88786857-55512380-d193-11ea-98f3-98445f15cb01.png)

**Comment by dpriskorn** [comment]
I can confirm this on 12.0.2. I could not add a price and got this error from the logs:
2020-08-01 10:44:22 DEBUG   127.0.0.1        sql=INSERT INTO llx_product_fournisseur_price_extrafields (fk_object, date) VALUES (1628, '1596240000')
2020-08-01 10:44:22 ERR     127.0.0.1        DoliDBPgsql::query SQL Error message: ERROR:  22008: date/time field value out of range: "1596240000"
LINE 1: ...price_extrafields (fk_object, date) VALUES (1628, '159624000...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
LOCATION:  DateTimeParseError, datetime.c:3751 (DB_ERROR_22008)
2020-08-01 10:44:22 ERR     127.0.0.1        DoliDBPgsql::query SQL Error usesavepoint = 0

The table looks like this:
\d llx_product_fournisseur_price_extrafields
                                          Tabell "public.llx_product_fournisseur_price_extrafields"
   Kolumn   |             Typ             | Jämförelse | Nullbar  |                                 Standard                                 
------------+-----------------------------+------------+----------+--------------------------------------------------------------------------
 rowid      | integer                     |            | not null | nextval('llx_product_fournisseur_price_extrafields_rowid_seq'::regclass)
 tms        | timestamp without time zone |            | not null | now()
 fk_object  | integer                     |            | not null | 
 import_key | character varying(14)       |            |          | 
 date       | date                        |            |          | 
Index:
    "llx_product_fournisseur_price_extrafields_pkey" PRIMARY KEY, btree (rowid)
    "idx_product_fournisseur_price_extrafields" btree (fk_object)

The error is that dolibarr tries to store a timestamp in a date column which is not possible. It should output an iso date instead, see https://www.postgresqltutorial.com/postgresql-date/

**Comment by dpriskorn** [comment]
still present in v14?
