### ISSUE TITLE
Security Notice & Bug Bounty - Cross-site Scripting (XSS) - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [Dolibarr/dolibarr#14316]
# Overview

dolibarr is a modern and easy to use web software to manage your business.

This package is vulnerable to Cross-site Scripting (XSS). The module renders user-uploaded html files in the browser when the attachment parameter is removed from the direct download URL.

# Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by dpriskorn** [comment]
what is this? spam?

**Comment by JamieSlome** [comment]
@egils-consulting - not at all!

We have opened up a bounty for this vulnerability on https://www.huntr.dev/bounties/1-packagist-dolibarr/.

Let me know if you have any further questions! 🍰

**Comment by huntr-helper** [comment]
‎‍🛠️ A fix has been provided for this issue. Please reference: https://github.com/418sec/dolibarr/pull/10

🔥 This fix has been provided through the https://huntr.dev/ bug bounty platform.

**Comment by eldy** [comment]
FIX by 9bb513531714f61bd1600803f7df03b1a95b492d 5d5fb46af67b2714c7478d2617a7653cdbb3ccf8 and other commits
