### ISSUE TITLE
Feature Request: Support pictures in products list

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14321]
# Feature Request
This forum post describes how to modify products/list.php such that a picture is shown for every product in the list:
https://www.dolibarr.org/forum/t/solved-product-pictures-in-product-list/15930/7
I suggest that to be the default in Dolibarr and to add a config-option to turn it off in the products module.

I can write a pull request if others support it. WDYT?

## Use case
Very nice to be able to see a picture to easily distinguish between similar products.

## Suggested implementation
see link above

**Comment by dpriskorn** [comment]
I just noticed that the picture does show up on hover, so this might not be necessary after all and just add clutter. WDYT?

**Comment by futurehousestore** [comment]
Hover is a nice and helpful feature but I personally prefer images and whole product title to be displayed on the list as it speeds up my work a lot.
![dolibarr-pictures](https://user-images.githubusercontent.com/28427270/89101207-a2343480-d3f5-11ea-8a08-6a76b0e389d9.PNG)

**Comment by dpriskorn** [comment]
still missing in v14?
