### ISSUE TITLE
 Management of stocks/sales of products and raw materials by weight, volume or quantity

### ISSUE THREAD

**Issue by nathanboschi25** [Dolibarr/dolibarr#14320]
# Feature Request
To be able to **manage stocks, BOM, sales, quotes** with products / raw materials in **weight, volume**

**Comment by simon3p** [comment]
Would be great! 

Say I have raw materials that I use by weight but I order it by bags of 50 pounds.

Would be nice to be able to use bags count when I create order to my supplier and when I do the reception my inventory will be adjusted in weight.

Maybe it is possible right now and I don't know how.

Thanks!

**Comment by nathanboschi25** [comment]
This is not possible at the moment that's why I made a feature request and I hope that it will be developed soon
