### ISSUE TITLE
Question about logic for receiving orders

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14335]
Hi
I'm emulating receiving orders from python directly into dolibarr because there is no API for supplier shipments yet.
I have a few questions:

1. What is the logic flow?
I'm guessing its: 
Add line to llx_commande_fournisseur_dispatch
Add line to llx_stock_mouvement
Increment stock column in llx_product and update pmp column with average price?
Is that correct or did I miss something?

2. what does status=0/1 do in llx_commande_fournisseur_dispatch?

dolibarr=> \d llx_commande_fournisseur_dispatch
                                              Tabell "public.llx_commande_fournisseur_dispatch"
       Kolumn        |             Typ             | Jämförelse | Nullbar  |                             Standard                             
---------------------+-----------------------------+------------+----------+------------------------------------------------------------------
 rowid               | integer                     |            | not null | nextval('llx_commande_fournisseur_dispatch_rowid_seq'::regclass)
 fk_commande         | integer                     |            |          | 
 fk_product          | integer                     |            |          | 
 fk_commandefourndet | integer                     |            |          | 
 qty                 | numeric                     |            |          | 
 fk_entrepot         | integer                     |            |          | 
 fk_user             | integer                     |            |          | 
 comment             | character varying(255)      |            |          | 
 batch               | character varying(128)      |            |          | NULL::character varying
 eatby               | date                        |            |          | 
 sellby              | date                        |            |          | 
 status              | integer                     |            |          | 
 datec               | timestamp without time zone |            |          | 
 tms                 | timestamp without time zone |            | not null | now()
 fk_projet           | integer                     |            |          | 
 fk_reception        | integer                     |            |          |

**Comment by eldy** [comment]
For 1, it seems good. Note that if you use PHP method to record the movement, there is no need to update the field stocks

For field status in llx_commande_fournisseur_dispatch, i think it is to flag a reception for control quality. This is used only when a hidden option is enabled (feature not yet completely mature). You can set it to 1 or 0 (check what is value in common usage of dolibarr)

**Comment by BebZ** [comment]
Hello Dennis, 
Did you manage to record supplier receptions with Python in Dolibarr ? 
We could be interested for a multicompany environment :)

**Comment by dpriskorn** [comment]
> 
> 
> Hello Dennis,
> Did you manage to record supplier receptions with Python in Dolibarr ?
> We could be interested for a multicompany environment :)

No, I decided it was not worth the effort when an API is missing. 
See #18411
