### ISSUE TITLE
Stock Import is missing lot S/N field

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#14330]
# Instructions / Bug
There is an export assistant for stock of products with lot S/N fields.
But there is no import for this.

So it's impossible to migrate easily from another ERP.

## Environment -> irrelevant
Version: 12.0.1
OS: debian 10.4
Web server: apache 2.2
PHP: 7.3
Database: MariaDB

**Comment by atm-maxime** [comment]
Still relevant ?
