### ISSUE TITLE
FIX: REST API Contract line update

### ISSUE THREAD

**Issue by hectordufau** [Dolibarr/dolibarr#14336]
# Bug
REST API contract line update fail
## Environment
- **Version**: 13.0
- **OS**: Linux
- **Web server**: Apache2
- **PHP**: 7.*
- **Database**: MySQL

## Expected and actual behavior
After post contract line update data, Dolibarr REST API didn't it

## Steps to reproduce the behavior
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: [KEY]' -d '{
  "request_data": [
  {
  	"desc": "",
  	"subprice": "0.00000000",
  	"qty": "1",
	"remise_percent": "0",
	"date_start": 1595166416,
	"date_end": "1605166416",
	"tva_tx": "0.000",
	"localtax1_tx": "0.000",
    "localtax2_tx": "0.000",
	"date_start_real": 1595166416,
    "date_end_real": 1605166416,
	"info_bits": "0",
	"fk_fournprice": null,
	"pa_ht": "0.00000000",
	"array_options": [],
	"fk_unit": null
  }
]
}' 'http://[HOSTADDRESS]/api/index.php/contracts/1/lines/1'

**Comment by hectordufau** [comment]
Solution:

It is a problem to get stdClass values from $request_data variable, on contrat/class/api_contracts.class.php file.

Just change them to lines above:

$updateRes = $this->contract->updateline(
            $lineid,
            $request_data->request_data[0]['desc'],
			$request_data->request_data[0]['subprice'],
			$request_data->request_data[0]['qty'],
			$request_data->request_data[0]['remise_percent'],
			$request_data->request_data[0]['date_start'],
			$request_data->request_data[0]['date_end'],
			$request_data->request_data[0]['tva_tx'],
			$request_data->request_data[0]['localtax1_tx'],
			$request_data->request_data[0]['localtax2_tx'],
			$request_data->request_data[0]['date_start_real'],
			$request_data->request_data[0]['date_end_real'],
            'HT',
			$request_data->request_data[0]['info_bits'],
            $request_data->request_data[0]['fk_fournprice'],
			$request_data->request_data[0]['pa_ht'],
			$request_data->request_data[0]['array_options'],
			$request_data->request_data[0]['fk_unit']
        );

**Comment by dpriskorn** [comment]
Could you please submit a pull request and reference this issue?

**Comment by dpriskorn** [comment]
Thanks!

**Comment by eldy** [comment]
I think trouble is more how you send you payload.
Here API is to update 1 line, so you should pass the payload with the data of 1 line. But in your example, you pass an array of lines. Try to remove the [ ] in your payload

**Comment by eldy** [comment]
Note: Ignore last comment, it is not related to this issue
