### ISSUE TITLE
REST put to /supplierorders to "approve order" returns 500 and no output

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14338]
# Bug
It is impossible to approve an order via the REST API.

## Environment
- **Version**: 12

## Expected and actual behavior
I'm trying to approve an order via python. I cannot find a way to do it though the API.

## Steps to reproduce the behavior
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: text/html' --header 'DOLAPIKEY: ' -d '{"date_commande": "2020-08-01", "fk_input_method": 5}' 'http://dolibarr.localhost/api/index.php/supplierorders/96'

**Comment by dpriskorn** [comment]
can someone test with v14?

**Comment by dpriskorn** [comment]
Still relevant in v15?

**Comment by inoveaconseil** [comment]
I can't reproduce v16.0.2
