### ISSUE TITLE
Extrafields "Date" field in quotations module to be searchable using a range of dates (start date and end date). 

### ISSUE THREAD

**Issue by thegeettanna** [Dolibarr/dolibarr#14346]
# Feature Request
An extra field with type = 'Date' is added to quotations module. 
It is has Visibility set to '1'.
On the list page for quotations, we can search the field for a particular date. 
It needs to be searchable for a particular range of dates - using the start date and end date. 

![Screen Shot 2020-08-03 at 3 15 21 AM](https://user-images.githubusercontent.com/24646523/89133406-38bd3e80-d539-11ea-85e5-a8faed2833a7.jpg)

## Use case
We are using a date to followup on quotations. This date will be the time when our sales teams would call the client for an update on the quotation. Currently we can only search for a particular date. Being able to search for a particular range will help search for all pending followups before today. It will also help search for followups for the whole week or any range. 
*This if implemented with extra fields would be useable in other modules, I am sure there would be a lot more use cases. 

## Suggested implementation
With Dolibarr V12.0, Quotation Date & Quotation End Date are all searchable through a range of dates. 
The same could be implemented for this date field. 
Although since it is an extra field, I am not sure where to begin. 
![Screen Shot 2020-08-03 at 3 28 16 AM](https://user-images.githubusercontent.com/24646523/89133444-8afe5f80-d539-11ea-97ee-c62eaf12318a.jpg)

**Comment by dpriskorn** [comment]
I can help you solve this via my Dolibarr Python API until it is possible in the UI. It could run daily and send an email with links to the relevant quotations for example. Feel free to contact me on egils@riseup.net if you are interested.
