### ISSUE TITLE
REST POST /products: note_public and note_private do not work properly

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14342]
# Bug
Dolibarr simply discards the note_private and note_public in the json and create the product with all other fields.

## Environment
- **Version**: 12

## Expected and actual behavior
expected Dolibarr to insert the data in the database.

## Steps to reproduce the behavior
insert a product with rest explorer

 curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: ' -d '{"ref": "test3",
"label": "test",
"note": "test",
"note_private": "test",
"note_public": "test"}' 'http://dolibarr.localhost/api/index.php/products'
-> this inserts note and note_private

 curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: ' -d '{"ref": "test3",
"label": "test",
"note_private": "test",
"note_public": "test"}' 'http://dolibarr.localhost/api/index.php/products'
-> this inserts none of them

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: ' -d '{"ref": "test3",
"label": "test",
"note_public": "test"}' 'http://dolibarr.localhost/api/index.php/products'
-> this inserts "test" into note and note_private

So note_public and note_private never works. note works and duplicates into note_private. 

Suggestion: remove the confusing note-field and fix note_public and note_private.

Related issue:   https://github.com/Dolibarr/dolibarr/issues/11447

**Comment by ksar-ksar** [comment]
Hello,

Can you check with the FIX and V13 ?

**Comment by dpriskorn** [comment]
Closed as I assume it is fixed. I'm not using these fields because they don't show up on the card in the UI. 
I made my own extrafields to add public and private notea as needed 😀
