### ISSUE TITLE
Bug: Non-numeric and header information error

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14352]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Non-numeric and header information cannot be modify error when entering the customer payment in USD at the payment page.

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /compta/paiement.php?facid=50&action=create&accountid=2

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![payment](https://user-images.githubusercontent.com/52134143/89163615-6f7e6d80-d5a8-11ea-960e-a93ac4dd2b92.JPG)

**Comment by dpriskorn** [comment]
I also have this warning in my dolibarr log.
You can hide the warning from users by editing your php.ini until it is fixed.

**Comment by asolslk** [comment]
Thanks for the advise, just to create awareness here so this will be fix in future.

**Comment by asolslk** [comment]
btw, any idea whether this can be fix on coming version or had been fixed and waiting for release. Thanks

**Comment by dpriskorn** [comment]
If this was fixed it would be closed. Its probably not high priority as it is only a warning. Warnings from php should always be hidden in production deployments if you ask me.

**Comment by dpriskorn** [comment]
related to #14219
