### ISSUE TITLE
Multicurrency conversion is wrong, when creating invoice from PO

### ISSUE THREAD

**Issue by n15c** [Dolibarr/dolibarr#14353]
# Bug
Conversion from price in currency to net price when editing a position is wrong when creating supplier invoice from purchase order

## Environment
- **Version**: 12.0.0
- **OS**: Debian 10
- **Web server**: Apache/2.4.38 
- **PHP**: 7.3.11-1~deb10u1
- **Database**: MariaDB 5.5.5-10.3.18-MariaDB-0+deb10u1
- **URL(s)**: https://<dolibarr>/fourn/facture/card.php?facid={id}

## Expected and actual behavior
The expected result is, that the price in other currency is converted to the net price and the price including VAT is calculated correctly. Instead, the entered net price in currency is being "copied" to the price with VAT column.

## Steps to reproduce the behavior

1. Create purchase order
2. Generate invoice out of PO
3. Edit a line on this new invoice
4. Enter a net price in other currency
5. Clear the other price fields
6. Save the line

## Screenshots
**Entering the price (7000.-)**
![grafik](https://user-images.githubusercontent.com/11615401/89165085-565dc880-d578-11ea-8051-d1f034685773.png)
**The price 7000.- is now 6'034.48276, 7000 is now the price including VAT**
![grafik](https://user-images.githubusercontent.com/11615401/89165184-78efe180-d578-11ea-893b-8e4ba8daa0cc.png)

**Comment by dpriskorn** [comment]
Thank you for the very clear report 😀
