### ISSUE TITLE
recurring invoice missing field 

### ISSUE THREAD

**Issue by depoulpe** [Dolibarr/dolibarr#14357]
Hi,
error occur when modify the title
field last_gen present in class (htdocs/compta/facture/class/facture-rec.class.php) but not in DB
best regards
Gilles

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20200803084122
Dolibarr: 12.0.1 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.2.24
Serveur: Apache/2.4.37 (centos) Phusion_Passenger/6.0.4 OpenSSL/1.1.1c
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

Url sollicitée: /htdocs/compta/facture/card-rec.php
Referer: http://dolibarr.local/htdocs/compta/facture/card-rec.php?action=editref&id=1
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, export, agefodd, agenda, facture, fournisseur, societe, service, contrat, comptabilite, banque, propal
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT rowid,titre,entity,fk_soc,datec,remise,tva,localtax1,localtax2,total,total_ttc,fk_user_author,fk_projet,fk_cond_reglement,fk_mode_reglement,date_lim_reglement,note_private,note_public,modelpdf,last_gen,unit_frequency,date_when,date_last_gen,nb_gen_done,nb_gen_max,frequency,usenewprice,revenuestamp,auto_validate,generate_pdf,fk_account,fk_multicurrency,multicurrency_code,multicurrency_tx,multicurrency_total_ht,multicurrency_total_tva,multicurrency_total_ttc,fk_user_modif,tms,suspended FROM llx_facture_rec WHERE rowid = 1 LIMIT 1
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'last_gen' in 'field list'

**Comment by dpriskorn** [comment]
What were you trying to do?

**Comment by depoulpe** [comment]
I' m trying to modify the label of an invoice template.
select an invoice template ( htdocs/compta/facture/invoicetemplate_list.php?leftmenu=customers_bills_templates) and edit the title.
the field last_gen is missing from table facture_rec
File https://doxygen.dolibarr.org/develop/d7/d5a/facture-rec_8class_8php_source.html
line 158 :'last_gen' =>array('type'=>'varchar(7)', 'label'=>'Last gen', 'enabled'=>1, 'visible'=>-1, 'position'=>120),

**Comment by papoteur-mga** [comment]
This is fixed with #fcbc48fa287d80a51c041ed9e8298186e42d0bda
