### ISSUE TITLE
Store documents in database (and possibility to migrate to)

### ISSUE THREAD

**Issue by dseichter** [Dolibarr/dolibarr#14350]
# Feature Request
I would prefer to store all my documents (auto generated and manually attached) as objects in the underlying database.

## Use case
Working with docker in an AWS ECS environment, I have to use EFS to be able to store all my documents permanently. In other systems, like MantisBT, all my documents where stored inside the database itstelf, so backing up RDS (the database), also my documents will be stored within the snapshots. Also this will prevent an empty document store, if the mounting process of the Volume of the documents will fail.

## Suggested implementation
Option to store the documents. If there are files in the local storage (or mounted volume), they should be imported to the database (possible with a short migration script). All other features, like download the files, attach the files etc. should be untouched (working well).

**Comment by dpriskorn** [comment]
Have I understood correctly that you would like to store yhe pdf as binary data in a new  column/table?
How much data are we talking about?
How will it affect the database performance?

**Comment by dseichter** [comment]
Yes, each file should be stored inside the database as blob instead of writing it to the local filesystem. I am talking about 1GB of data (increasing over the time), currently stored on local filesystem (in an EFS volume mounted to the docker container as /var/www/documents).
Within the ECM module I found some columns, where each local file is stored as a link to the corresponding local file.

Each PDF, each attachment etc. should be stored in the database.

**Comment by dpriskorn** [comment]
This also affects images

**Comment by dpriskorn** [comment]
I'm not sure this is the best direction for Dolibarr core. It could be implemented as a module for sure. 
You could ask some of the Dolibarr partners to implement this for you.

**Comment by dseichter** [comment]
I will close this issue, because of this feature not relevant anymore. I installed Dolibarr on AWS with Aurora Serverless and EFS as document store. With this setup, I have automated backup with everything included on same timestamp.
