### ISSUE TITLE
Bug: Bank Journal does not convert the currency to the main currency

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14358]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Bank Journal / General Ledger does not convert the foreign currency to the local currency with the set conversion as per the order by considering only 1 currency shall appear in the GL for balance calculation.

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /accountancy/bookkeeping/listbyaccount.php?&search_date_startmonth=7&search_date_startday=1&search_date_startyear=2017&search_date_endmonth=6&search_date_endday=30&search_date_endyear=2018

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![bank J](https://user-images.githubusercontent.com/52134143/89169681-1ebf4280-d5b1-11ea-8f2b-8d2f219d8f61.JPG)

**Comment by dpriskorn** [comment]
Could you clarify a little more? What is your currency setup? How to reproduce this?
I just enabled multicurrency and would like to try to reproduce this.

**Comment by asolslk** [comment]
my setup have 2 bank account, 1 is USD, 1 is SGD and we created a quote to client using USD, the client profile was set to USD as well. once we receive the payment and enter into the system, the payment will go into my USD account correctly, no issue on that.

but when we come to GL, its show the payment received in the invoice had been converted to SGD like the supplier invoice above, but the bank GL still stick to USD which caused the number not able to tally.

had discussed with our accountant, and was suggested to create USD sub account to record the USD transaction, which mean if we have alot of different currency, we will need to have alot of sub account.

**Comment by dpriskorn** [comment]
I have 1 bank account in Dolibarr in SEK, but I make EUR payments from it (the bank converts to SEK before debiting the account) and Dolibarr seems to handle that just fine.
Do you have multiple bank accounts with different currencies? Seems like a nightmare if you ask me 😅

**Comment by asolslk** [comment]
Yes, i have 2 bank account with 2 different currency. And the solution we have now is to generate the sub account with different currency
