### ISSUE TITLE
Stock module setup

### ISSUE THREAD

**Issue by scxma** [Dolibarr/dolibarr#14368]
# Bug
I cant deactivate the function: Decrease real stocks on shipping validation AND Increase real stocks on manual dispatching into warehouse, after purchase order receipt of goods

## Environment
**Datum:** 20200804060931
**Dolibarr:** 12.0.1 - https://www.dolibarr.org
**Funktionslevel:** 0
**PHP:** 7.3.12
**Server:** Apache/2.4.41 (Win64) PHP/7.3.12
**OS:** Windows NT SERP 10.0 build 17763 (Windows Server 2016) AMD64
**UserAgent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
**Angefragte URL:** /dolibarr/admin/stock.php
**Menüverwaltung:** eldy_menu.php

## Expected and actual behavior
I cant deactivate the function: 
- Decrease real stocks on shipping validation 
- Increase real stocks on manual dispatching into warehouse, after purchase order receipt of goods
I click on the button. It turns off. I reload the site and its activated again.

## Steps to reproduce the behavior
Deactivate the options above and reload page or go to Start and go to module gain.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![grafik](https://user-images.githubusercontent.com/28040789/89269564-53c3a780-d63a-11ea-9e73-9cb2a4bd311f.png)

**Comment by BebZ** [comment]
Hello,
Maybe that's because you have an external module not allowing it that is activated
(MOBILID) 
Or module BATCH/LOT numbers activated ?

**Comment by scxma** [comment]
Hello,
these are my activated modules:

**Module / Anwendungen:** user, cron, societe, contrat, fournisseur, commande, expedition, propal, ficheinter, product, service, stock, productbatch, facture, categorie, barcode, workflow, import, agenda

So yes, i work with lot/serial numbers, but I dont want them automatically decrease my warehouse.
