### ISSUE TITLE
Renaming of existing warehouses doesnt work

### ISSUE THREAD

**Issue by scxma** [Dolibarr/dolibarr#14371]
# Bug
Renaming of existing warehouses doesnt work

## Environment
Datum: 20200804060931
Dolibarr: 12.0.1 - https://www.dolibarr.org
Funktionslevel: 0
PHP: 7.3.12
Server: Apache/2.4.41 (Win64) PHP/7.3.12
OS: Windows NT SERP 10.0 build 17763 (Windows Server 2016) AMD64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0

## Expected and actual behavior
expected: Modify the number of a specific warehouse work.
actual: Modify the number of a specific warehouse doesn't work.

## Steps to reproduce the behavior
List of Warehouses -> Open one warehouse -> Hit the button modify (next to delete button) -> Modify the number -> Safe -> Warehouse doesn't get the new name

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![grafik](https://user-images.githubusercontent.com/28040789/89280901-9345c000-d649-11ea-9b99-ad73cf997072.png)

**Comment by atm-maxime** [comment]
Isn't it because telefon and fax are mandatory and not filled ? What is the error message ?

**Comment by scxma** [comment]
> 
> 
> Isn't it because telefon and fax are mandatory and not filled ? What is the error message ?

No. I added telefon and fax for testing purpose to an existing warehouse. It is saving these values, but if I change the telefon/fax and the number, its also saving, but the number wont change and stay the same. There's also no error message, even if I only change the number.
I am also able to create a new warehouse without telefon/fax, so it seems that they are no mandatory fields.

**Comment by dpriskorn** [comment]
Confirmed (I changed ref to HOMEtest):
2020-08-06 21:42:09 DEBUG   127.0.0.1       BEGIN Transaction
2020-08-06 21:42:09 DEBUG   127.0.0.1        Entrepot::update
2020-08-06 21:42:09 DEBUG   127.0.0.1        sql=UPDATE llx_entrepot  SET ref = 'HOME', fk_parent = NULL, description = 'Hemmalager', statut = 1, lieu = 'Hometest', address = 'adress', zip = '', town = '', fk_pays = 20, phone = '', fax = '' WHERE rowid = 1
2020-08-06 21:42:09 DEBUG   127.0.0.1       COMMIT Transaction

**Comment by dpriskorn** [comment]
$object->ref         = GETPOST("ref");
This line is missing in the source under update. Perhaps intentionally, but in that case it should be greyed out in the form.
