### ISSUE TITLE
Limits/precision setup: cannot change unit price number of decimals

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#14372]
# Bug
With a fresh 12.0.1 install.
In the "Limits/precision" setup page.
Default setting is 5 decimals for unit prices.
I wanted to change it to 4, but I can't.
Other values 2, 3, 6 don't work any better.

## Environment
- **Version**: 12.0.1
- **OS**: debian 10.4
- **Web server**: apache 2.4.38
- **PHP**: 7.3.19
- **Database**: MariaDB 10.3

## Expected and actual behavior
In the "Limits/precision" setup page.
There is a "Number of decimals for unit prices" setting.
Expected : we MUST be able to modify it.
Actual behavior : value does not change.

## Steps to reproduce the behavior
Go to the "Limits/precision" setup page.
Click on "MODIFY".
Enter a new value in the "Number of decimals for unit prices" field.
Click on "SAVE".
=> value does not change

**Comment by atm-maxime** [comment]
Hi. Duplicate of #14272 ?

**Comment by StephaneLesage** [comment]
> Hi. Duplicate of #14272 ?

Oups, yes sorry.

**Comment by atm-maxime** [comment]
So if it's ok for you, you can close your issue 😉

**Comment by StephaneLesage** [comment]
Yes should be OK.

I couldn't find the commit by searching 14272, precision or decimal in the repository.
I finally found it by searching "limit"...
Shouldn't the commit title include the issue number ?
