### ISSUE TITLE
Dolibarr gives verbose error when no invoice found instead of just: "No record found."

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14388]
# Bug
If a payment is not found Dolibarr returns: No record found.

If a supplier invoice is not found I get this:
Dolibarr has detected a technical error.
You use an experimental or develop level of features, so please do NOT report any bugs, except if problem is confirmed moving option MAIN_FEATURES_LEVEL back to 0.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20200805082258
Dolibarr: 12.0.2 - https://www.dolibarr.org
Level of features: 2
PHP: 7.4.8
Server: nginx/1.18.0
OS: Linux parabola 5.7.8-gnu-1 #1 SMP PREEMPT Fri, 10 Jul 2020 23:36:43 +0000 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

Requested URL: /fourn/facture/card.php?id=122
Referer: http://dolibarr.localhost/fourn/facture/card.php?facid=122&save_lastsearch_values=1
Menu manager: eldy_menu.php

Modules/Applications: api, syslog, user, tax, salaries, multicurrency, product, banque, import, export, expedition, accounting, commande, facture, fournisseur, societe, service, margin, propal, blockedlog, doliosm, categorie, removeconf, workflow, stock
Database type manager: pgsql
Latest database access request error: No request in error
Return code for latest database access request error: No request in error
Information for latest database access request error: No request in error

Dolibarr has detected a technical error.
You use an experimental or develop level of features, so please do NOT report any bugs, except if problem is confirmed moving option MAIN_FEATURES_LEVEL back to 0.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20200805082258
Dolibarr: 12.0.2 - https://www.dolibarr.org
Level of features: 2
PHP: 7.4.8
Server: nginx/1.18.0
OS: Linux parabola 5.7.8-gnu-1 #1 SMP PREEMPT Fri, 10 Jul 2020 23:36:43 +0000 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

Requested URL: /fourn/facture/card.php?id=122
Referer: http://dolibarr.localhost/fourn/facture/card.php?facid=122&save_lastsearch_values=1
Menu manager: eldy_menu.php

Modules/Applications: api, syslog, user, tax, salaries, multicurrency, product, banque, import, export, expedition, accounting, commande, facture, fournisseur, societe, service, margin, propal, blockedlog, doliosm, categorie, removeconf, workflow, stock
Database type manager: pgsql
Latest database access request error: SELECT ec.rowid, ec.statut as statuslink, ec.fk_socpeople as id, ec.fk_c_type_contact, '-1' as socid, t.statut as statuscontact, t.login, t.photo, t.civility as civility, t.lastname as lastname, t.firstname, t.email, tc.source, tc.element, tc.code, tc.libelle FROM llx_c_type_contact tc, llx_element_contact ec LEFT JOIN llx_user t on ec.fk_socpeople = t.rowid WHERE ec.element_id = AND ec.fk_c_type_contact=tc.rowid AND tc.element='invoice_supplier' AND tc.source = 'internal' AND tc.active=1 ORDER BY t.lastname ASC
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: ERROR: 42601: syntax error at or near "AND"\nLINE 1: ...n ec.fk_socpeople = t.rowid WHERE ec.element_id = AND ec.fk_...\n ^\nLOCATION: scanner_yyerror, scan.l:1145

Dolibarr has detected a technical error.
You use an experimental or develop level of features, so please do NOT report any bugs, except if problem is confirmed moving option MAIN_FEATURES_LEVEL back to 0.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20200805082258
Dolibarr: 12.0.2 - https://www.dolibarr.org
Level of features: 2
PHP: 7.4.8
Server: nginx/1.18.0
OS: Linux parabola 5.7.8-gnu-1 #1 SMP PREEMPT Fri, 10 Jul 2020 23:36:43 +0000 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

Requested URL: /fourn/facture/card.php?id=122
Referer: http://dolibarr.localhost/fourn/facture/card.php?facid=122&save_lastsearch_values=1
Menu manager: eldy_menu.php

Modules/Applications: api, syslog, user, tax, salaries, multicurrency, product, banque, import, export, expedition, accounting, commande, facture, fournisseur, societe, service, margin, propal, blockedlog, doliosm, categorie, removeconf, workflow, stock
Database type manager: pgsql
Latest database access request error: SELECT ec.rowid, ec.statut as statuslink, ec.fk_socpeople as id, ec.fk_c_type_contact, t.fk_soc as socid, t.statut as statuscontact, t.civility as civility, t.lastname as lastname, t.firstname, t.email, tc.source, tc.element, tc.code, tc.libelle FROM llx_c_type_contact tc, llx_element_contact ec LEFT JOIN llx_socpeople t on ec.fk_socpeople = t.rowid WHERE ec.element_id = AND ec.fk_c_type_contact=tc.rowid AND tc.element='invoice_supplier' AND tc.source = 'external' AND tc.active=1 ORDER BY t.lastname ASC
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: ERROR: 42601: syntax error at or near "AND"\nLINE 1: ...n ec.fk_socpeople = t.rowid WHERE ec.element_id = AND ec.fk_...\n ^\nLOCATION: scanner_yyerror, scan.l:1145

## Environment
- **Version**: 12
- **URL(s)**: http://dolibarr.localhost/fourn/facture/card.php?id=

## Expected and actual behavior
Expected Dolibarr just to return: "No record found."

**Comment by atm-maxime** [comment]
Hi there, thanks for this feedback.
I think we must define the good behaviour and standardize it. I checked on many objects and there is a different way of handling a record not found for each...
In v11 :
- Thirdparties : blank page with "Record not found"
- Products : Dolibarr page with Access denied red banner
- Proposals : Dolibarr page, blank content, red error notification "Record not found"
- Orders : Dolibarr page, blank content, red error notification "Order with id 79 not found sql=SELECT ..."
- Supplier orders : Dolibarr page, blank content
- Contracts : Dolibarr page, blank content
- Invoice : Dolibarr technical error message
- Supplier Invoice : Dolibarr technical error message
- Customer payment : Dolibarr technical error message
- Supplier payment : Dolibarr page, card tabs, "Record not found"

So @eldy, what would be the right way to handle an inexistent card in database ?

**Comment by eldy** [comment]
It is clear that technical message means "error management is not complete yet here". So we must avoid it.
We should have at least top and left menu with a message Record not found.

**Comment by atm-maxime** [comment]
Still relevant

**Comment by dpriskorn** [comment]
Can someone verify?
