### ISSUE TITLE
12.0.1 : No new line in Third Party Address

### ISSUE THREAD

**Issue by kess78** [Dolibarr/dolibarr#14384]
## Bug
No new line in Third Party Address

## Environment
- **Version**: [*12.0.1*]
- **OS**: [*Debian 9*]
- **Web server**: [*Apache 2.4.25*]
- **PHP**: [*7.3*]
- **Database**: [*MariaDB 10.1.45*]
- **URL(s)**: [*/societe/card.php*]

## Expected and actual behavior
When modifying a Third Party address, with more lines CR and LF should not be replaced by a whitespace

## Steps to reproduce the behavior
Navigate to https://www.my-dolibarr-erp-instance.org/societe/card.php?socid=12345&action=edit
Type a multiline Address
Save
Navigate again to https://www.my-dolibarr-erp-instance.org/societe/card.php?socid=12345&action=edit 
Have a look at the Address

**Comment by atm-maxime** [comment]
Fix in progress #14331

**Comment by eldy** [comment]
Seems fixed in v12.0.2
