### ISSUE TITLE
Bug: Solved - Length of the General Ledger accounts not showing

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14392]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
The length of general ledger does not show 6 digit even the number was set. not sure is there any other setting that I had missed out or it is purely a bug.

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /accountancy/admin/index.php?action=setmanagezero&value=0

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![acc1](https://user-images.githubusercontent.com/52134143/89442927-2d108880-d782-11ea-9189-40dff837768c.JPG)
![2](https://user-images.githubusercontent.com/52134143/89442933-2e41b580-d782-11ea-850d-64268ec20586.JPG)

**Comment by dpriskorn** [comment]
Could you please clean up all your issues removing the things you did not fill in? It takes time to skip all the template garbage and focus away from understanding and perhaps addressing the issue. Thanks.

**Comment by asolslk** [comment]
> Could you please clean up all your issues removing the things you did not fill in? It takes time to skip all the template garbage and focus away from understanding and perhaps addressing the issue. Thanks.

I dont understand what you trying to mean. Are you referring to setup everything again by removing the template?

**Comment by dpriskorn** [comment]
I mean remove everything surrounded by [] in your post just as the template says. Just click edit and delete the unnecessary stuff.

**Comment by asolslk** [comment]
managed to solve by removing the ! in the function of the htdocs/core/lib/accounting.lib.php

function length_accountg($account)
{
	global $conf;

	if ($account < 0 || is_empty($account)) return '';
	//modified by asolslk
	if (is_empty($conf->global->ACCOUNTING_MANAGE_ZERO)) return $account;

	$g = $conf->global->ACCOUNTING_LENGTH_GACCOUNT;
	if (!is_empty($g)) {
		// Clean parameters
		$i = strlen($account);

		if ($i >= 1) {
			while ($i < $g) {
				$account .= '0';

				$i++;
			}

			return $account;
		} else {
			return $account;
		}
	} else {
		return $account;
	}
}

function length_accounta($accounta)
{
	global $conf;

	if ($accounta < 0 || is_empty($accounta)) return '';
	//modified by asolslk
	if (is_empty($conf->global->ACCOUNTING_MANAGE_ZERO)) return $accounta;

	$a = $conf->global->ACCOUNTING_LENGTH_AACCOUNT;
	if (!is_empty($a)) {
		// Clean parameters
		$i = strlen($accounta);

		if ($i >= 1) {
			while ($i < $a) {
				$accounta .= '0';

				$i++;
			}

			return $accounta;
		} else {
			return $accounta;
		}
	} else {
		return $accounta;
	}
}

![1](https://user-images.githubusercontent.com/52134143/89624856-75868e00-d8c9-11ea-9c0d-a74acd108a74.JPG)
![2](https://user-images.githubusercontent.com/52134143/89624858-77505180-d8c9-11ea-966f-cd07a36030dd.JPG)

**Comment by dpriskorn** [comment]
Could you send a pull request?

**Comment by asolslk** [comment]
I would but i dont know how as i am new to github, any guide?

**Comment by dpriskorn** [comment]
https://duckduckgo.com/?q=github+pull+request+tutorial&t=fpas&ia=web

**Comment by dpriskorn** [comment]
Essentially click edit on the file you want to edit, save and then click create pull request.
Add "fixes #14392" to the description and nothing else.
