### ISSUE TITLE
Purchase order wrong dummy VAT rates instead of dictionnary rates

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#14396]
# Bug
On a fresh 12.0.1 install, after importing customers, suppliers, products and warehouse.
I configured 2 VAT rates : 0 and 20%. They work fine for Customer Orders.
But in purchase order, the form shows 3 rates : 0, 6 and 19% coming from nowhere !!!

## Environment
- **Version**: 12.0.1
- **OS**: debian 10.4
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.22
- **Web Browser**: Chrome 84.0.4147.105

## Expected and actual behavior
Purchase order must show VAT rates configured in dictionnaries and not some random values 0, 6, 19%.

## Steps to reproduce the behavior
I actually cannot reproduce it when creating a new purchase order. I don't know what went wrong on this order.

Still, this probably can happen to anybody, and there is definitely something in the code that show these fixed VAT rates in particular circumstances.

![Capture TVA commande fournisseur](https://user-images.githubusercontent.com/69054301/89510822-61f7fc00-d7d1-11ea-89c6-f9ab1e53d9d1.png)

**Comment by atm-maxime** [comment]
I think it's not random but these vat rates are the rates available for the supplier country.

**Comment by StephaneLesage** [comment]
> I think it's not random but these vat rates are the rates available for the supplier country.

You're right. It's a supplier from the Netherlands.

But as we're a French company, this is intra EEC exchange and there should not be any VAT at all.
I hope the invoicing system uses the products' EEC accountancy code in this case.
=> can Dolibarr produce the Goods Exchange Declaration ? (DEB Déclaration d'Echange de Bien)

So I suppose as should flag all foreign suppliers as 'don't use VAT' manually right ?

**Comment by dpriskorn** [comment]
> So I suppose as should flag all foreign suppliers as 'don't use VAT' manually right ?

Yes, thats what I do. This should be documented in a ? in the UI IMO and  in the wiki at least because I also had a hard time figuring out how to set it up properly. I import from Germany (no VAT) and China (Aliexpress=no VAT, Wish 25% VAT). VAT is a headache to set up correctly, but Dolibarr works fine when you understand how to set it up properly.
Could you submit a pull request adding a [?] box to the supplier order card form?
