### ISSUE TITLE
Add new line to order: cannot choose product unit

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#14390]
# Bug
Using PRODUCT_USE_UNITS=1
When we add a line in customer/purchase order and select a predefined product/service,
some fields are automatically field, but we cannot choose the unit.

## Environment
- **Version**: 12.0.1
- **OS**: debian 10.4
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.22
- **Web Browser**: Chrome 84.0.4147.105

## Expected and actual behavior
We must be able to choose the unit before adding the new line.

## Steps to reproduce the behavior
In customer/purchase order, select a predefined product/service: there is a unit combo-box.

![Capture Ajouter ligne commande client sans unité](https://user-images.githubusercontent.com/69054301/89432091-fbc39880-d740-11ea-8bcc-a2b9c2caac0e.PNG)

**Comment by cfoellmann** [comment]
The current way it works it that you set the unit in the details for the specific product.
What is your use case for this?

**Comment by StephaneLesage** [comment]
> The current way it works it that you set the unit in the details for the specific product.

It's already set in the product general page.
I don't understand.
Do you mean in the product supplier price ? I see nothing here.

> What is your use case for this?

Use case is straightforward :
1. Stock is in meter, but I want to order a reel of 100 meters.
2. Stock is in pieces, but I want to order a box of 200 pieces
...

Before choosing the product, there is combo box to choose the unit, fine.
After selecting a product, the combo box disappears ???
Only way is to re-edit the line again... which is dumb and time-consuming...

**Comment by cfoellmann** [comment]
@StephaneLesage  the UNIT is not the "packaging". Example: you order cable. Cable is measured in UNIT = meter . But you can only order 100m coils. Then unit stays meter But the packaging is 100m

The experimental feature to use packaging (last option on the admin page for the products module) lets you define a packaging value for the supplier price

**Comment by BebZ** [comment]
@StephaneLesage I think you are missing the fact that there are no links between "purchasing prices" and "customer prices"
when you register 1 reel of 100m cable of 100€ in purchasing prices
if you want to sell it by meter you have to put qty 0.01 for 1 meter

my advice is to register (in the designation and in the sell price) 
**the smallest stock keeping unit or the smallest sell-able unit in the purchasing prices**
for example if you can sell the cable by centimeters, register your supplier price by cm : (minimum qty in purchasing price would be 100 000) and price 100€ so unit price would be 0.001€
and then make a module to constraint packaging (you don't want to sell less than 20cm) so minimum qty (in CUSTOMER side) is minimum 20 but this module need to be developped... 

are you interested ?

we can co -finance it !?

**Comment by StephaneLesage** [comment]
@bebz This is not related to sell prices. I will not sell these items.
@bebz I agree stock unit should be the smallest.

@cfoellmann I'm well aware that the unit is not the packaging. This is precisely why I defined reel/box units that I want to order with :
Some suppliers may sell by meters -> OK fine I can use packaging (already enabled and bug #14489)
But other suppliers will sell reels => so stock unit stays meters, and I need to choose the unit to order by reels.

For screws, stock units is pieces, because I will consume pieces in Manufacturing Orders, but I will always order boxes/bags of 100 or more.

This is very simple : just show the unit combo box so we can choose it...
