### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by DLC-SNT** [Dolibarr/dolibarr#14397]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
the MO module does not include the batch numbers of raw materials

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.2.31
- **Database**: MySQL or MariaDB 5.5.5-10.2.32-MariaDB
- **URL(s)**: /Doli12/index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Can you please give more details, screenshots ? And why calling this a bug if it's a missing feature ?

**Comment by DLC-SNT** [comment]
![Capture d'écran 2020-08-06 16 46 43](https://user-images.githubusercontent.com/69302305/89546846-51fa0f80-d805-11ea-8658-29aa7b7820c4.png)

on the screenshot above, circled in red, the lot numbers must be re-entered by hand when they have already been entered on delivery to the supplier.

**Comment by dpriskorn** [comment]
Thanks for the report and screenshot. Could you please clean up the template by removing all dead text and []? Also change the title to something that describes the problem.

**Comment by atm-maxime** [comment]
So what do you expect? Yes lot number must be entered on the mo, you wish to have a drop down list ? It's a feature request then.
