### ISSUE TITLE
Use PDO instead of manually generating SQL-statements

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14398]
# Feature Request
I just noticed this extension: https://www.php.net/manual/en/book.pdo.php
I suggest we convert all SQL statements in Dolibarr to use that.

WDYT?

related to: https://github.com/Dolibarr/dolibarr/issues/10054

**Comment by ERP-Academia** [comment]
1. PDO takes care of data sanitation.
2. PDO's Prepared statements are faster when inserting lot of similar information.
3. Returned datasets are traversable with foreach.

**Comment by DanielRuf** [comment]
See also https://github.com/Dolibarr/dolibarr/issues/2885
