### ISSUE TITLE
Description is not selectable/displayable in product/list.php

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14399]
# Bug
All columns from the llx_product should be selectable in product/list.php IMO

## Environment
- **Version**: 12
- **URL(s)**: product/list.php

**Comment by atm-maxime** [comment]
Text fields are usually not available in lists because they can contain many lines. So displaying a desc column in a list would break the list display.

**Comment by dpriskorn** [comment]
Oh, that sounds reasonable.
