### ISSUE TITLE
LibraOffice Template files in the (filename ).odt format no longer function

### ISSUE THREAD

**Issue by jccs1953** [Dolibarr/dolibarr#14394]
# Bug  

**MAJOR BUG - TESTED a fresh install DOES NOT support the Libreoffice ODT Template format**
[Libre office files will not open when used as a template (filename).odt]

## Environment
- **Version**: [12.0.1]
- **OS**: [Ubuntu Linux]
- **Web server**: [*Apache - 2.4.43*]
- **PHP**: [7.3]
- **Database**: [My SQL 5.6.48-cll-lve]
- **URL(s)**: [https://Bronsoroofing.net/accounts2*]

## Expected and actual behavior
Recently upgraded from 11.0.4 to 12.0.1 - Prior to the upgrade the LibreOffice.ODT file would function normally and  correctly after it, I would this error (see picture below when trying to open.)
![Screenshot from 2020-08-05 21-23-58](https://user-images.githubusercontent.com/17952470/89480470-6b4a7f80-d763-11ea-811e-23fa841000fc.png)
It does read the database  into the  pdf format (crabe) but I need to use the template and  not the pdf as it prints the information in a specific location on a letterhead

## Steps to reproduce the behavior
install 12.0.1 
create an invoice 
validate it using the template _( on fresh install it doesn't see that the **odt templates** are available only crabe PDF format is shown )_
when trying to print it produces the above error
Upon further study I have found that it won't even see the *.odt files in a separate installation of it on my testing website even the ones that come with it in the doctemplates folder */doctemplates/invoices on http:jccs.us my development website
I Restored the previous version from my backup 11.0.4 and the functionality returned to normal
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]Br-Invoice.odt
[Br_Invoice.odt.zip](https://github.com/Dolibarr/dolibarr/files/5035528/Br_Invoice.odt.zip)

**Comment by jccs1953** [comment]
Problem still not resolved in Version 12.0.2 
![image](https://user-images.githubusercontent.com/17952470/93808320-d23fcd00-fc19-11ea-9ebf-808c9233fa3c.png)

**Comment by RomainDeschamps** [comment]
> 
> 
> Problem still not resolved in Version 12.0.2
> ![image](https://user-images.githubusercontent.com/17952470/93808320-d23fcd00-fc19-11ea-9ebf-808c9233fa3c.png)

Works for me.

Try with the doc attached.

[Br_invoice.zip](https://github.com/Dolibarr/dolibarr/files/5257610/Br_invoice.zip)

**Comment by jccs1953** [comment]
Does not even see it in a fresh install still doesn't work beginning to think it may be server problem will try it on a different server
-------------------------------------------------------------------------------------------------------------------------
1. Tried on a different server hosted by a different company still the same result
2. I  downloaded the Bitnami stack and on a fresh install of 12.0.2-1 it does not work so it is not a server side problem 
3. Possibly a problem with the installation using Softaculous will try a manual install next to see if that might be the problem.
4. OK I did a manual install and the results are still the same. *A note on an upgrade*  it is possible to see the odt files and you can create ONE invoice, but then when you go to do the second one it fails with the read error
