### ISSUE TITLE
Dolibarr got slow after adding 7000 categories

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14409]
# Bug
I just added 7000 categories and afterwards Dolibarr got noticeably slower on the REST endpoints and in the WEB UI.

Does someone have any tips for debugging what slows it down? 

## Environment
- **Version**: 12
- **OS**: psql
- **Web server**: nginx
- **PHP**: 7.4
- **Database**: pgsql

**Comment by eldy** [comment]
Did you update your database statistics after the load ?
Do you identify by reading the log file dolibarr.log (module Log debug must be enabled) if there is one SQL request that takes more time than before.

**Comment by dpriskorn** [comment]
How do I update the db stats? I noticed it most on the endpoint when I query via rest multiple time in a row. Before the lag was a few hundred milliseconds and now it is up to 2 seconds. So a factor 100 slower approximately.

**Comment by dpriskorn** [comment]
For some reason it is no longer slow. Closing
