### ISSUE TITLE
Include best BOM cost price in buying prices card for products with BOM

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#14417]
# Feature Request
In the same way that you can see best buying price for purchased products, products with BOMs associated with them should have best BOM cost listed here. 

## Use case
Sales managers, when deciding on product prices, need to be able to see the costs for a product. If the product is purchased, the information is found in the buying prices card. However, BOMs are not tied to product cards, and are instead handled by their own cards under the MRP menu. BOMs themselves have their own unit cost in their cards. but given that a product can have more than one BOM, searching for the different prices for the BOMs is a time consuming and error prone task

## Suggested implementation
In the Buying Prices card of a product, include

- Best BOM cost (similar to current field "Best buying price")
- a list of the BOMs associated with the product, along with their unit cost, production quantity, etc (similar to current "Vendor prices")

**Comment by JLMARIN** [comment]
I support this request. For products that are manufactured, it would be useful to have the option for "Buying Price" to come directly from the associated BOM cost. Currently, I have to manually copy-paste it as a fixed cost but it is not linked in any way, os if the BOM changes cost I have to manually update it.

**Comment by ToniTen** [comment]
This is still an issue, and I don't see this being added in the V16 changelog.

**Comment by uhausmann** [comment]
This would be a very useful feature. Please reopen the issue.

**Comment by Kimbaras** [comment]
+1 for this request.

is there any plan to implement such functionality?

I really like the GUI of Dolibarr and wanted to make the switch from Odoo, but this is the most used function for me, and it's what is stopping me to actually making the switch.

Thanks!
