### ISSUE TITLE
All categories are shown on /categories/index.php no matter the number

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14410]
# Bug
This leads to a very long pageload time when you have over 1000 categories.

## Environment
- **Version**: 12

## Expected and actual behavior
It takes ~10s to load. Clicking the + lags 7s until the 7000 subcategories are shown
Dolibarr should split the category index page or simply limit the number of categories displayed and tell the user to search to find a specific category.
 
If I browse to /viewcat.php of the parent category having 7000 subcats I get this error:
2020/08/06 23:26:59 [error] 471#471: *2412 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/egil/src/php/dolibarr/htdocs/core/lib/treeview.lib.php on line 188" while reading upstream, client: 127.0.0.1, server: dolibarr.localhost, request: "GET /categories/viewcat.php?id=14&type=0&backtopage=%2Fcategories%2Findex.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "dolibarr.localhost", referrer: "http://dolibarr.localhost/categories/index.php?leftmenu=cat&type=0"

The computations are too expensive to apply to an unlimited number of categories.

## Steps to reproduce the behavior
Add 7000 categories to the database with 1 parent root category
go to /categories/index.php

**Comment by eldy** [comment]
Only 7000 categories should be very fast.
What may occurs is that there is an infinite loop if a category has one of its parent and grand parent that is a child or child of child...
In such a case, there is a protection but it needs a long time to system to discover we have reached the level 1000 of categories. Thanks to check this. You can have a look at the log dolibarr.log and search for "protection=" string to see what is the maximum value of the level of the protection.
You can also try this commit https://github.com/Dolibarr/dolibarr/commit/9876e37309f0c9c4d1ca4d067e02a6533258e1a7

**Comment by dpriskorn** [comment]
I have only two levels in total. The code is very expensive. If you have a php script I can measure it. It takes ~10s to do the calculations incl. sorting.

**Comment by dpriskorn** [comment]
Will try the commit and report back.
