### ISSUE TITLE
Dolibarr defaults to tosell=0 and tobuy=0 when cloning products

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14423]
# Bug
This results in more work for the user than if it would simply inherit the values form the subject to be cloned.

## Environment
- **Version**: 12

## Expected
Dolibarr inherits as much as possible to reduce user workload.

**Comment by atm-arnaud** [comment]
@egils-consulting  this is not a bug. This way has been choose for real reasons.

When you clone, you have to change ref / name. So if we change to sell 1, one user could add it in a proposal or invoice during your modification

@eldy i think this post could be closed
