### ISSUE TITLE
Minor bug: Add help tip everywhere where the input affects pmp/awp calculation

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14434]
# Bug
I think we should add a ? with a note stating that the input affects pmp to make the user aware of that.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.8
- **Database**: PostgreSQL 12.3
- **URL(s)**: /product/stock/product.php?id=1474&action=correction

**Comment by atm-maxime** [comment]
Yes it does, when you do a stock increase by correction or by supplier order reception, the pmp is calculated with the unit price provided in the correction form or the purchase price in the supplier order.
