### ISSUE TITLE
Fatal error when importing a file

### ISSUE THREAD

**Issue by Muleta2** [Dolibarr/dolibarr#14459]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Fatal error ocurred when importing a file*]

## Environment
- **Version**: [*12.0.1*]
- **OS**: [*Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux*]
- **Web server**: [*Apache*]
- **PHP**: [*7.4.9*]
- **Database**: [*MySQL or MariaDB 5.7.30-log*]
- **URL(s)**: [*http://clientes.miguelllorcabriganty.com/imports/import.php?step=4&datatoimport=societe_1&format=xlsx&excludefirstline=1&separator=%2C&enclosure=%22&filetoimport=20200811112834-Ejemplo_de_archivo_importaci%26oacute%3Bn_societe_1.xlsx*]

[import-fail.pptx](https://github.com/Dolibarr/dolibarr/files/5056417/import-fail.pptx)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by dpriskorn** [comment]
Please post sample data and how you set up dolibarr. Also enable logging module and post the output.

**Comment by Muleta2** [comment]
Hi.
Sorry, I'm just a user so I've limited technical knowledge.
Find attached file with data uploaded, and the log file.
The program is hosted in Ionos, so they set up the site.

[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/5063962/dolibarr.log)
[sample-data.xlsx](https://github.com/Dolibarr/dolibarr/files/5063974/sample-data.xlsx)
