### ISSUE TITLE
Bug: cannot change third party after creating order

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14452]
# Bug
I would like to be able to change the third party because I created a duplicate customer in error.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.8
- **Database**: PostgreSQL 12.3
- **URL(s)**: /commande/card.php?id=277

## Expected and actual behavior
able to edit the third party until the point where other documents are linked (after linking would be bad because then e.g. the order and invoice could have different socids). So when trying to edit the third party, Dolibarr should check if links exist and deny with an error "Cannot change third party because linked documents exist, delete those first".

## Steps to reproduce the behavior
create order with third party
try to change it in the UI

**Comment by atm-maxime** [comment]
2 ways of dealing with third-party errors on document :
Clone the document on the correct third-party and delete the wrong one
Merge the two third-party in case of duplicate

**Comment by dpriskorn** [comment]
I choose to edit the db directly and it worked fine. Then I deleted the duplicate and kept the old third party.
