### ISSUE TITLE
Import trash does not work

### ISSUE THREAD

**Issue by Muleta2** [Dolibarr/dolibarr#14458]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*In the import screen, step 3, when you click on trash of a line, file is deleted, but not the line*]

## Environment
- **Version**: [*12.0.1*]
- **OS**: [*Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux*]
- **Web server**: [*Apache*]
- **PHP**: [*7.4.9*]
- **Database**: [*MySQL or MariaDB 5.7.30-log*]

## Expected and actual behavior
[*After clicking on trash, the line should disappear, but it remains*]
[import-no-delete.pptx](https://github.com/Dolibarr/dolibarr/files/5056380/import-no-delete.pptx)

**Comment by atm-quentin** [comment]
Hello,
Thanks for reporting, i'll have a look

**Comment by atm-quentin** [comment]
This problem seems solved. 
Have you tried to upgrade your dolibarr to 12.0.4 ? I can't reproduce this error.
