### ISSUE TITLE
Table title overlaps the price when language set to portuguese

### ISSUE THREAD

**Issue by alculete** [Dolibarr/dolibarr#14466]
# Bug
Invoice table title unit price is overlapping the price when language is set to portuguese-PT on the generated PDF file.
Is possible please set it to **Preço Unit.** like in Brazilian Portuguese or one of the following: Preço, P. U.

## Environment
- **Version**: 12.02
**OS**: Ubuntu Server 18.04.5 LTS x86_64 
**Host**: HP Compaq 6200 Pro MT PC 
**Kernel**: 4.15.0-112-generic 
**PHP**: 7.4.9

[*Files*]
![unit price](https://user-images.githubusercontent.com/2129497/90002618-2e1a4c00-dc93-11ea-9439-8392d03cf1a1.png)

**Comment by atm-kevin** [comment]
I am working on it.

**Comment by alculete** [comment]
any update on this?

**Comment by atm-maxime** [comment]
Is this still an issue ? If yes, you can submit your translation change on transifex
