### ISSUE TITLE
Compte auxiliaire ne fonctionne pas

### ISSUE THREAD

**Issue by hanen91-ch** [Dolibarr/dolibarr#14468]
Bonsoir à tous, 
J'utilise la version 12.0.1, et j'ai une problème à propos le fonctionnement du paiement divers.
Lorsque je veux créer un nouveau paiement pour le tiers (client/fournisseur) le compte auxiliaire affiche rien. malgré le compte auxiliaire c'est le même le code comptable.
![image](https://user-images.githubusercontent.com/69306045/90012068-9882ba80-dc9a-11ea-9bc4-a000da5fbeee.png)

**Comment by atm-maxime** [comment]
Hi !
Thanks for contributing. Please use English on GitHub.
Did you seek help on official forums before declaring this issue on GitHub ?

**Comment by aspangaro** [comment]
@hanen91-ch Il suffit juste de donner un compte comptable dans l'onglet client ou fournisseur d'un tiers.

Ce n'est pas bug ni une feature request
