### ISSUE TITLE
Cannot add a field into 	llx_c_ticket_severity

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#14460]
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20200811123612
Dolibarr: 12.0.1 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.3.19-1~deb10u1
Serveur: Apache/2.4.38 (Debian)
OS: Linux seguin 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36

Url sollicitée: /admin/dict.php?id=40
Referer: https://erp.service-informatique.fr/admin/dict.php?id=40
Gestionnaire de menu: eldy_menu.php

Modules/Applications: api, user, barcode, fckeditor, workflow, import, externalrss, opensurvey, website, notification, mailing, emailcollector, cron, socialnetworks, oauth, externalsite, geoipmaxmind, clicktodial, dav, printing, blockedlog, debugbar, holiday, expensereport, societe, propal, commande, expedition, contrat, ficheinter, ticket, agenda, mrp, bom, fournisseur, supplier_proposal, facture, accounting, banque, tax, salaries, prelevement, loan, margin, product, service, stock, productbatch, variants, projet, resource, ecm, categorie, bookmark, export, modulebuilder
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: INSERT INTO llx_c_ticket_severity (rowid,pos,code,label,use_default,active) VALUES(5,'11','LOW30','Résolution sous 30 jours','1',1)
Code retour dernier accès en base en erreur: DB_ERROR_1364
Information sur le dernier accès en base en erreur: Field 'color' doesn't have a default value

**Comment by dpriskorn** [comment]
Thanks. Version? Db?

**Comment by matDOTviguier** [comment]
### Read the initial post :
Dolibarr: 12.0.1
llx_c_ticket_severity (rowid,pos,code,label,use_default,active)
There is **NO** _color_ attribute at all :)
Just a problem of back end code ...

**Comment by matDOTviguier** [comment]
Thank you Laurent.
