### ISSUE TITLE
Answer to: Is there a reason why you are using Apache [instead of Nginx]?

### ISSUE THREAD

**Issue by caos30** [Dolibarr/dolibarr#14477]
Hi. Thanks for writing about this obscure error. I never took the time to learn Apache which is IMO a legacy web server. I use nginx exclusively and its really nice and I have never had a situation like the one you describe. Is there a reason why you are using Apache?

_Originally posted by @egils-consulting in https://github.com/Dolibarr/dolibarr/issues/13270#issuecomment-673696561_

Hello. Maybe the answer to your question is that you're too much younger. The people who are making webapps during at least the 2 past decades had to work with Apache. So if you have not, then it seems you are a "recent" arrived to this industry.

Said this, sincerely, my **personal policy** regarding to use "new" technologies is to wait for to be in front of a CLEARLY better option. Sincerely, Nginx, although is more effective using server resources, the difference is really minimal for standard websites/webapps (in the best case a 10% faster). So, takin in account the wide presence of Apache around and its compatibility with almost the 100% of the mature LAMP webapps/CMS... sincerely, for me there is not enough reasons to change a known and stable and mature technology by another one a bit more fast (also RAM efficient, i know).

Obviously, the exception could be the case if you know that X CMS can work perfectly on Nginx and you specially need to attend a huge number of visitants... In this case is interesting to work to make more efficient the service, of course.

But, returning to Dolibarr (and other CMS/webapps) i think that our OBLIGATION is specially to make run them on Apache. 

Let me add this fact: the major of hosting providers only offer Apache on **shared hosting plans**. Usually you need an VPS to be able to choose Nginx. So, restrict the use of your CMS/webapp to a not standard technology in the low market of the hosting services... is a very bad decision for the success of your project. It's my opinion.

**Comment by dpriskorn** [comment]
Oh. I was not aware of the last fact. That seems really really bad.  Could you give some examples that only offer apache?
A less effective and older tech like apache often means more cost to maintenance and energy. 
The example of bug you reported leads me to believe that your time would have been better spent finding a proper nginx host and copy pasted the conf in the wiki (we have no example  apache conf what I know, but I did not search either.
That would have reduced your wasted time to about an hour.
Also if you are a professional, why not have a VPS? It only gives more headache to let others manage your software IMO (unless you pay them and they do a good job, which is not the case if they restrict you to a buggy apache server)

**Comment by dpriskorn** [comment]
Anyway, why did you create a new issue? Could you change the title at least? It seems like a bad idea to split the discussion.

**Comment by caos30** [comment]
Hello. I'm sorry to create a new issue... i really saw it once created!! The error was not to read well the menu of options to reply to. I'm sorry for that. If you want to delete this conversation please go ahead, o maybe we can CLOSE THE ISSUE hehehe.

Regarding to the question of Apache/Nginx:

1) you must choose the hosting depending ALSO on the money you have for that project, hehehe. No all the projects /customers can or need to pay for a VPS !!! The difference in prices in the cheapest cases is about 4-10 times the total money!!!

2) I will not change my hosting provider to use Nginx by Apache. Let me insist, maybe you're quite more younger like me, but i need to build a service (a hosted webapp) capable to be running smooth and stable along several years. I've projects with almost 20 years running, obviously updating Apache, PHP, backend, frontend, mobile friendly, etc... but if i must build TODAY a Dolibarr/Chamilo/Prestashop/etc... instance for a customer i need to have a trust and known provider for the hsoting... even the same technology. And i need to take that CMS, create the hosting account and make run the service if it is possible in a few hours! My main job (in hours) is to attend customers and to develop PHP modules (sometimes hackings) for those CMS to fully/better service those customers (each one usually need different things). 

So, briefly: my friend, it's not a recommendable solution to change your provider each time you have an inconvenient, hehehe. I say this to respond to your suggestion of search a Nginx provider. Furthermore, is not a "tiny" change to pass from Apache to Nginx... specially when you has not used NEVER nginx. I think that it could need more than one hour to find a good tutorial.

Last note: i've suffered a lot (a lot!) changing between hosting providers in the last 2 decades, and i think that i'm not the unique. I'm talking about specially of this fact: the final really important point to differentiate a good provider from a bad provider is the excellence on their response when the things FAIL... and always the things will fail one day or another, due to your fault or their fault or the net fault, hehehe. So i've to suffer when after to trust in some of the "greatest" companies of hosting (world wide level) they simply are ABSENT when you (or their server) has a problem!!! 

After having been customer of several (more than 10?) hosting providers, finally i'm quite stable and HAPPY with 4 of them (some of thenm in America and another ones on Europe, GDPR reason). I've no problem to share here their brands: 

- Dreamhost (super-mega-excellent the service of these guys... the best service to affordable prices), i know, these words seems advertising, but i'me trying to be sincere.
- CDmon (Barcelona, Europe)
- Dinahosting (Spain, Europe, probably the best customer service at the most affordable price, they are veterans on hosting)
- DigitalOcean (perfect for thins like BigBlueButton conferencing server and specific installations like this.
- Amazon AWS (i sued by now only the SES email SMTP service for send transactional emails for my own SaaS services... similar to SendGrid and other relays).

As i said... out of them i no need very much. I know their strengths and their weaknesses, but in balance i feel enough safe and happy with their service... in other words, i can sleep like a baby :smile: 

Cheers!

**Comment by caos30** [comment]
You had a good idea: change the title of the "issue" :+1:

**Comment by dpriskorn** [comment]
If you have multiple customers you could once setup 1 vps properly to serve multiple customers from a single nginx.
It supports multiple domains https etc and use few resources compared to apache. If you have 10 customers I'm sure you could make it work economically. 
You could have the database seperately and managed by AWS or someone else.
The VPS could perhaps easily be replicated over 2 datacenters if you want premium uptime for your customers. I'm unsure if thats easy to do with Dolibarr though, but a rsync running every minute to sync the files would probably be enough to keep the files in sync.
Relying on shared hosting from multiple providers sounds lke a pain in the ass to me.

**Comment by caos30** [comment]
Thanks for your suggestions. I'm using an VPS for my Dolibarr customers just as you explained ;-) In fact the minimal VPS of Dreamhost is ENOUGH to manage super-faster 6 Dolibarr instances and 3 Prestashops!! I don't know if you know Prestashop of have used it, but it eat a lot of resources... 

The magic with VPS Dreamhost is this: they give you unlimited space for unlimited MySQL database managed in certain machines of their datacenters specialized on MySQL, so the speed is simply amazing and this let you take an incredible performance of your VPS to run "only" Apache+PHP (you can choose Nginx+PHP). Furthermore (this could be advertising but i cannot not to share it) they offer also unlimited space for unlimited email accounts for whatever of the unlimited domain names you put in the VPS !! 

Man... the first time i knew about these conditions (a little more than 5 years ago) i couldn't believe that this could be real. But believe me... their service is simply awesome and their servers run faster and smoothly. I never get tired to recommending them, sincerely. If you don't know about them, i also recommend to read about the history of its founders... lovers of opensource, one of them is founder and main developer of opensource Ceph file system for distributed filesystems S3 compatible (look for DreamObjects) and so they have DreamCompute cloud service similar to AWS EC2... So, they are simply fascinating.

Returning to your suggestion, i take note about the rsync ... although i've very secure incremental backup system made by myself which use a combination of HTTP webservice and FTP for retrieve new/changed files... which i use it to backup daily all the webapps of my customers/projects. I know that rsync let you make also incremental backups... but i would like now to say something like in a previous comment of mine: some shared hostings don't give me SSH connection to the server, so i cannot use rsync ;-)

My FTP Backup system work perfect with whatever PHP hosting. I'm fine with that. Furthermore, recently i even added the option of include in the backup an instant full backup of the MySQL database made by the webservice part on the remote server. But this DB backup is not incremental. You probably know that an incremental backup of a database is really a complicated thing. The good new is i don't need manage yet heavy databases. Furthermore, the dump is gzipped, so is very tiny the file. A metric detail for you: the daily backup of 70 webapps take about 7 minutes, 5 seconds per site backed up !

As you see, my current architecture is quite similar to your proposition ;-) Hehehe, there is no many other ways to have all them running well.

Maybe the last detail is the creation of a new instance. But for this i've an "empty" instance of Dolibarr which i only must copy & paste, dump its database and restore in a new MySQL database and change the conf.php file... all them i've done in a few minutes ;-)

Sincerely, my pending work is to prepare a more efficient system to **propagate PHP code patches** when i develop new improvements on Dolibarr core or one of the modules (or Dark theme). By now i must make a very tedious copy paste using Filezilla (SFTP), site per site. **I want to prepare a tiny linux shell script to make this propagation in an automatic way** to all the Dolibarr instances i've installed. This will save me easily 20 minutes each time i need to do a change, and certainly without "human" errors, you know.

Anyway, **many thanks for your suggestions**. I sincerely appreciate it.
I promise to search more information about Nginx. It probably is a best option for my next VPS project than Apache. By now, sincerely... i'm unable to get that time for this. But certainly, the "need" is a powerful incentive! ;-)

Cheers.

**Comment by dpriskorn** [comment]
Closing as not related to core.
