### ISSUE TITLE
Invalid SQL for postgres into upgrade script

### ISSUE THREAD

**Issue by l00ptr** [Dolibarr/dolibarr#14472]
# Bug
Migration script from 10 to 11 is no longer working on posgtres - since this change : 
https://github.com/Dolibarr/dolibarr/commit/921e904acca2c8c0103c11165c196b69df95b9f7#diff-abcaddf6b9cc9a4ede8df5b0ab0014b7

mysql / mariadb and postgres doen't use the backtick the same way - So the generated SQL for postgres  doesn't work since this change. 

## Environment
- **Version**: 10 and 11
- **OS**: Debian 10.4
- **Web server**:  Apache 2.4
- **PHP**: 7.3
- **Database**: Postgres 12
- **URL(s)**:  -

## Expected and actual behavior
Upgrade from 10 to 11 upgrade smoothly

## Steps to reproduce the behavior
From a Dolibarr 10 try to upgrade to 11 with postgres as a backend

```
user=labo,db=validerp,app=[unknown],client=127.0.0.1 ERROR:  syntax 
error at or near "`" at character 41
user=labo,db=validerp,app=[unknown],client=127.0.0.1 STATEMENT:  ALTER TABLE llx_bom_bomline DROP COLUMN `rank`;
```

**Comment by dpriskorn** [comment]
Thabks for the clear bug report.
