### ISSUE TITLE
Error 500 in supplier order add line when product has no packaging defined

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#14489]
# Bug
Using PRODUCT_USE_SUPPLIER_PACKAGING.
When adding a new line on a supplier order.
If the product has no supplier/price or packaging defined, we get Internal Errror 500.
It's a division by zero at line 1728 of fournisseur.commande.class.php

## Environment
- **Version**: 12.0.2
- **OS**: debian 10.4
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.22
- **Web Browser**: Chrome 84.0.4147.105
- **Apache Log**: [Mon Aug 17 18:34:43.708413 2020] [php7:error] [pid 90963] [client 192.168.10.11:1591] PHP Fatal error:  Uncaught DivisionByZeroError: Modulo by zero in /usr/share/dolibarr/htdocs/fourn/class/fournisseur.commande.class.php:1728\nStack trace:\n#0 /usr/share/dolibarr/htdocs/fourn/commande/card.php(535): CommandeFournisseur->addline('Matrice num\\xC3\\xA9ri...', '2700', '1', '0', '0', '0', '56524', 0, NULL, '0', 'HT', '', '0', 0, '', '', '', Array, '28', '0', '', 0)\n#1 {main}\n  thrown in /usr/share/dolibarr/htdocs/fourn/class/fournisseur.commande.class.php on line 1728, referer: http://srv-dolibarr/dolibarr/fourn/commande/card.php?id=4

## Expected and actual behavior / Steps to reproduce the behavior

Using PRODUCT_USE_SUPPLIER_PACKAGING.
In a supplier order, select a predefined product which has no supplier/price/packaging defined, then click on "add".
You get an Internal error 500, where it should just work...

## Debugging the code

When not defined, product packaging is 0, thus the division error when trying to round-up the quantity.
The code should check $prod->packaging before using it.
Or product class should do it and/or packaging should default to 1 when fetching the object...

```
	if ($qty < $prod->packaging)
	{
		$qty = $prod->packaging;
	}
	else
	{
		if (($qty % $prod->packaging) > 0)		<--- There it is...
		{
			$coeff = intval($qty / $prod->packaging) + 1;
			$qty = $prod->packaging * $coeff;
			setEventMessage($langs->trans('QtyRecalculatedWithPackaging'), 'mesgs');
		}
	}
```

**Comment by dpriskorn** [comment]
Thank you for a very detailed bug report. Yay! Would you like to submit a pull request to fix this? How do you recommend we fix it?

**Comment by StephaneLesage** [comment]
> Thank you for a very detailed bug report. Yay!
>Would you like to submit a pull request to fix this?

Sorry I'm new to github and I don't know how to do this.

>How do you recommend we fix it?

I think that all object methods MUST set the member variables right so the object is usable.
I first thought that packaging should default to 1 but this is not right, because it could be set to 0.1 meter for example.
Now I think that packaging=0 is a legitimate value to say "there is no packaging".
So the all code related to packaging should enclosed within checkings:

```
if (!empty($conf->global->PRODUCT_USE_SUPPLIER_PACKAGING))
{
	$prod = new Product($this->db, $fk_product);
	$prod->get_buyprice($fk_prod_fourn_price, $qty, $fk_product, 'none', ($this->fk_soc ? $this->fk_soc : $this->socid));
	if ($prod->packaging > 0)	<== HERE
	{
		...
	}
}
```
