### ISSUE TITLE
Edit product supplier price page is missing packaging field (emballage)

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#14490]
# Bug
Using PRODUCT_USE_SUPPLIER_PACKAGING.
Edit product supplier price page is missing packaging field (emballage)

## Environment
- **Version**: 12.0.2
- **OS**: debian 10.4
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.22
- **Web Browser**: Chrome 84.0.4147.105
- **URL(s)**: http://srv-dolibarr/dolibarr/product/fournisseurs.php?id=56524&socid=70112&action=update_price&rowid=2

## Steps to reproduce the behavior / Expected and actual behavior 

List all product supplier prices : table has the packing column. OK.

Edit a product supplier price : there is no packaging field ???

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Capture Edit product supplier price NO PACKAGING](https://user-images.githubusercontent.com/69054301/90429462-12b1a580-e0c6-11ea-918f-89ccd6ced900.PNG)

![Capture List supplier prices column packaging OK](https://user-images.githubusercontent.com/69054301/90429471-16452c80-e0c6-11ea-919a-654cc6830daa.PNG)

**Comment by dpriskorn** [comment]
Would you mind finding the spot in the code where this is missing and linking to it here? Is this a regression, did it work on earlier versions?

**Comment by StephaneLesage** [comment]
Well. It's solved in current develop version 13 beta.
In addition, the list has been reduced so, there's no need to scroll anymore.

But the bug is still present in v12.0.3.
Someone to find the commit and fix v12 ?

**Comment by StephaneLesage** [comment]
> But the bug is still present in v12.0.3.

I found it, it's commit df4b208de1a43ce6685b333045ae95acc71fae27
@FHenry Thanks for the fix.
Maybe you should you fix v12 as well ?

**Comment by FHenry** [comment]
@StephaneLesage #15639 .
I've only back port the round issue.
