### ISSUE TITLE
Rights management for imports

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#14495]
# Instructions
All imports are broken

# Bug
Impossible to have rights to import something, refused after step 3.
tested on 2 new installed servers

## Environment
- **Version**: **11.0.5**
- **OS**: All
- **Web server**: All
- **PHP**: 7.3
- **Database**: Mysql
- **URL(s)**: /imports/import.php

## Expected and actual behavior
impossible to upload file after step 3

## Steps to reproduce the behavior
i haven't tried all, but no imports are working on 11.0.5

**Comment by homer8173** [comment]
Sorry, i'm on meeting, i haven't time to open the code

**Comment by dpriskorn** [comment]
Could you install the logging module in dolibarr and insert the relevant output here?

**Comment by MartinFulgueiras** [comment]
I have the same problem on a synology installation. 
Version: 11.0.5
OS: Synology / debian?
Web server: apache2
PHP: 7.3
Database: Mysql
URL(s): /imports/import.php
