### ISSUE TITLE
Suggest qty / lot into shipment of sub warehouse when we select a parent warehouse as source warehouse

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#14496]
# Bug
We have many sub-locations STK.A, STK.B, STK.C.1, STK.C.2 ... in a main warehouse CLAIX.
So I have imported them as children warehouses of the main parent warehouse.
The products are spread across all these sub-warehouses.
So when creating a shipping order, we select the main parent warehouse,
but the page doesn't show the stock of the children warehouses...

## Environment
- **Version**: 12.0.2
- **OS**: debian 10.4
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.22
- **Web Browser**: Chrome 84.0.4147.105

## Screenshots to reproduce

I have a product with serial numbers.
Stock is 2 pieces in warehouse "CLAIX.STK.C.2":
![Capture produit](https://user-images.githubusercontent.com/69054301/90528006-71345d80-e172-11ea-84f6-b9032a4b872e.PNG)

This warehouse is child of main parent warehouse "CLAIX":
![Capture Warehouse](https://user-images.githubusercontent.com/69054301/90528356-cec8aa00-e172-11ea-93f5-665407815437.PNG)

I create a new shipping from a customer order and select parent warehouse "CLAIX":
![Capture New shipping order](https://user-images.githubusercontent.com/69054301/90528638-2830d900-e173-11ea-8d1b-0073a69cd0d7.PNG)

Shipping order page says there is no stock in parent house CLAIX, which is strictly correct, but should display stock of children,
the same way as when we leave the warehouse field empty:
![Capture no stock in parent warehouse](https://user-images.githubusercontent.com/69054301/90528828-5adad180-e173-11ea-9de5-697c2f67fc70.PNG)

**Comment by BebZ** [comment]
Hello, 

can you push a screenshot please ? it is quite long to reproduce the bug...

**Comment by StephaneLesage** [comment]
> can you push a screenshot please ? it is quite long to reproduce the bug...

@BebZ Yes I edited the first comment.

**Comment by dpriskorn** [comment]
very nice screenshots, thank you. Is this expected to work? Does Dolibarr officially support child warehouses? 

Honestly it sounds to me like added complexity and I can't see the benefit. Could you explain what this is good for? Why not just have 1 warehouse per physical location/address?

**Comment by StephaneLesage** [comment]
>Does Dolibarr officially support child warehouses?
>Is this expected to work?

I should hope so, there is no hidden option, this plain standard out-of-the-box dolibarr.

There are already other threads here (#11659) and on the forum about people needing 'sub-places' inside warehouses like very other ERP on the planet. People using Dolibarr always say: "we don't need that, you can already use hierarchical warehouses for this".
So I just try to do it Dolibarr's way.

>Honestly it sounds to me like added complexity and I can't see the benefit. Could you explain what this is good for?

A small-size real-world warehouse of 200m²x10m high is something 5 columns x 5 rows x 4 places in height.
Do you expect the storekeeper to look everywhere for each product of an order ?

No,.. The basic process of companies needing serious storage is;
- every product has a default place in your warehouse.
- if there is no place when receiving a supplier order, then your store it at another place physically and in the database.
- when preparing the customer order, you tell the storekeeper where to look...

We are a small company with 15 people and only 1 storekeeper and we already need this...
I Imported 487 warehouses from our current ERP CEGID Manufacturing PMI.

Advanced users would also need:
- defaut place for reception  (before quality control, next move to default storage for shipping)
- defaut place for manufacturing
- default place for M.O components consumption
- receive in random empty place like Amazon...

>Why not just have 1 warehouse per physical location/address?

This is true for the main parent warehouses (2 sites here).
In our case, we have other "virtual warehouses" on the main site:
- products on engineers desks to run tests
- RMA products still belonging to the customer
- repaired products
- components in the manufacturing area.
...
These stocks are devaluated with various rates when exported to accountancy.

**Comment by dpriskorn** [comment]
Thank you for the thorough explanation 😀
I have a small company with only a few hundred products so I have not needed that.

Using multiple warehouses forces you to select the subwarehouse that holds the product. Is that a problem? I don't think so because Dolibarr helpfully shows you the stock per warehouse for each warehouse in the drop down select box.

You could further model this using tags/categories on products. One tag for row and one for shelf or using extrafields on the product or stock module.

Dolibarr is extremely flexible and has few limitations on how to use it, but I recommend you to ask in the forums or hire help before importing your existing data so it is modelled well in Dolibarr.

I'm not sure that the extrafields or tags would show up on the shipping card though, so if you need that I suggest creating a feature request.

**Comment by dpriskorn** [comment]
I have built a python library for dolibarr and it could easily help you check that all products have row/shelf and import/export the information as you like with a high degree of flexibility.
