### ISSUE TITLE
Problems with ODT file in Portuguese 

### ISSUE THREAD

**Issue by victorcasale** [Dolibarr/dolibarr#14491]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug

After upgrading do the last version 12.0.2, I could note the following behavior.  When trying to create an .odt file with some information about projects, it was perfectly working before, file was created with success and I could open it using my OpenOffice or msword. I’m in Brazil and official language is Portuguese, so we use some special caracthers like “é, à, á, ã, ç” 

If description field contains these type of carachters, Dolibarr creates .odt file but when trying to open it in my text editor, I receive an error message saying that file is corrupted or computer is out of memory. But when i make a description without these type of carachters, file is generated and I can open with my text processor. 

I also tried using the default doc template and the same thing happens: if accentuation is present, word processor can’t read the file, but when typing words without special characters, file opens normally 

Hope it could be repaired in the future versions 

Regards 
Victor 

## Environment
- **Version**: 12.0.2
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by AntonioFonseca1965** [comment]
Ja resolveu o problema ?
