### ISSUE TITLE
Legal Entity Type Not showing any options in company/organization   page

### ISSUE THREAD

**Issue by usama-tariq1** [Dolibarr/dolibarr#14504]
# Instructions
Legal Entity Type Not showing any options in company/organization page

# Bug
[*Short description*]
Legal Entity Type Not showing any options in company/organization page

## Environment
- **Version**: 12.0.0-alpha
- **OS**: Linux
- **Web server**: 
- **PHP**: 7.3.20
- **Database**: MySQL or MariaDB 5.6.48-cll-lve
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
Bugs Occurs when Setup company and organization on "legal entity type" and couldnt find any setup in dictionary 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Hi !
Did you try with the last stable 12 version instead of the alpha version ?
Is the country selected ? Can you add a screenshot ?

**Comment by aspangaro** [comment]
Surely a problem of country without any data in Dolibarr. Please propose legal entity list for your country.
