### ISSUE TITLE
Public notes not showing on invoices

### ISSUE THREAD

**Issue by andreash-esp** [Dolibarr/dolibarr#14500]
# Bug
Public Notes are not transferred to invoices

## Environment
- **Version**: 11.0.4
- **OS**: Ubuntu 18.0.4
- **Web server**: Apache/2.4.29
- **PHP**: 7.2.24
- **Database**: mariadb-server-10.1 .44
- **URL(s)**: dolibarr.localhost/compta/facture/card.php?action=create&origin=propal&originid=49&socid=53

## Expected and actual behavior
Public notes in proposals are not taken over for invoices. They show up find in delivery notes.
We use them to track customer order references that need to show up on all documents related to an order.

## Steps to reproduce the behavior
Create a new invoice from an order. The public notes need to be added manually.

**Comment by dpriskorn** [comment]
Did I understand correctly that you expect a public note to propagate from proposal->order->invoice and end up in the pdf-export of the invoice? If yes, where does the propagation fail? proposal->order or order->invoice?

**Comment by andreash-esp** [comment]
That's correct. It fails on the propagation to invoice, regardless of from where I create the invoice.
proposal -> order is fine
order -> expedition is fine
order -> invoice fails. It is not in the invoice and subsequently not in the pdf
expedition -> invoice fails. It is not in the invoice and subsequently not in the pdf

**Comment by dpriskorn** [comment]
Would you like to take a look at the code of the order card in  action section and see if you can spot where it is missing?

**Comment by andreash-esp** [comment]
I'm afraid I don't know where to look. I did have a quick look at the php code but my php knowledge is to limited to find the right spot.

**Comment by eldy** [comment]
Each object has its own public note that differs. The public note is not propagated by default.

**Comment by andreash-esp** [comment]
Hi Laurent,
the public not propagates fine from proposal to order or delivery. The only step it does not propagate through is to the invoice.
Can this be defined somewhere? I'm not aware I changed anything to have it propagate in the other step.
Regards
Andreas

**Comment by dpriskorn** [comment]
I think we should change that @eldy and always propagate it. Are there any downsides to doing to hat?
