### ISSUE TITLE
Tracking Number field printed in expedition "rouget" with public note

### ISSUE THREAD

**Issue by andreash-esp** [Dolibarr/dolibarr#14501]
# Bug
Tracking number field is printed on the expedition "rouget" even when no tracking number is given.
This happens when a public note is set.

## Environment
- **Version**: 11.0.4
- **OS**: Ubuntu 18.0.4

## Expected and actual behavior
An empty "Tracking-Number:" line is printed on expeditions when no tracking number is given but a public note is set.
This is a bug in pdf_rouget,modules.php:

     if (!empty($object->note_public) || !empty($object->tracking_number))
                   [...]
      $pdf->writeHTMLCell(60, 4, $this->posxdesc - 1, $tab_top - 1, $outputlangs->transnoentities("TrackingNumber")." : ".$object->tracking_number, 0, 1, false, true, 'L');

This prints the line regardless of an existing tracking number and makes the public note look like a tracking number.

## Steps to reproduce the behavior
Create an expedition "rouget" with a public note and no tracking number.
The PDF will print
   Tracking-Number: "nothing"
   "public note"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-quentin** [comment]
Hi, 
Thanks for reporting, i'll look this
