### ISSUE TITLE
llx_contrat.statut no further updates after contract validation

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#14513]
# Context
It is said in your documentation [Module_Contrat_(développeur)](https://wiki.dolibarr.org/index.php/Module_Contrat_(développeur)) that llx_contrat.statut should reflect the status of the services it is composed from. Actually looking at this page [https://wiki.dolibarr.org/index.php/Table_llx_contrat](https://wiki.dolibarr.org/index.php/Table_llx_contrat) possible values of llx_contrat.statut should be either 0 or 4 or 5.

# Bug
Actually llx_contrat.statut is equal to 0 as long as the contract remains a draft. Nevertheless, once validated/activated, whatever the changes I make on the services of different contracts (activate or deactivate them), llx_contrat.statut remains equal to 1 forever.

## Environment
- **Version**: 12.0.x
- **OS**: Linux
- **Web server**: apache
- **PHP**: 7.3.13
- **Database**: mySql

**Comment by eldy** [comment]
I updated the wiki  https://wiki.dolibarr.org/index.php/Table_llx_contrat
The status of contract is not more updated.
It is a value calculated dynamically from the services. A contract has no more a status. it is each of its services that has, and they may be different for each line.

**Comment by ghost** [comment]
Understood, nevertheless we feel it's a pity to have lost this information directly accessible.
