### ISSUE TITLE
Missing example on REST API post /orders/{id}/lines 

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14525]
# Bug
missing example.

## Environment
- **Version**: v12

## Expected and actual behavior
should have a minimum working example
I got sent this:
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: ' -d '{
    "fk_commande": "281", 
"qty": "1",
  "id": "384"
}' 'http://dolibarr.localhost/api/index.php/orders/281/lines'
got this:
{
  "error": {
    "code": 400,
    "message": "Bad Request: ERROR:  22P02: invalid input syntax for type integer: \"\"\nLINE 1: ...null, '', '1', '', '0', '0', '0', '0', '0', null, '', '0', 0...\n                                                             ^\nLOCATION:  pg_strtoint32, numutils.c:256"
  },

**Comment by eldy** [comment]
To get an example on how to fill a POST, just do a GET and reuse the result.

**Comment by dpriskorn** [comment]
I still think this is a bug. The error message is not very helpful.

**Comment by dpriskorn** [comment]
I will submit a pull request soon.
