### ISSUE TITLE
Captcha Dolibarr

### ISSUE THREAD

**Issue by victorcardim-zz** [Dolibarr/dolibarr#14522]
### Meio Ambiente

- Dolibarr 12.0.2
- Windows NT 10.0 compilação 19041 (Windows 10)
- Apache / 2.4.41 (Win64) PHP / 7.3.12
- 5.5-10.4.10-MariaDB 

Captcha is not differentiating upper and lower case characters. 

_This flaw was also identified by another user in the English Forum._
[https://www.dolibarr.org/forum/t/captcha-dolibarr/19436](url)

**Comment by erikvanberkum** [comment]
I can confirm that on my installation:

- Dolibarr 12.0.2
- Ubuntu 18.04
- Apache
- mysql 

have the same issue

**Comment by eldy** [comment]
The goal of a captcha is not like a password. A password must be case sensitive to increase the number of combination. There is not need to be case sensitive for a captchca.
Goal of a captcha is to force the system that submit the form to prove it is not a robot and that he was able to understand "humanly" the captcha. And proving that analysis of image was done by a human does not need to use case sensitive information when submitting the value, the value itself is enough (we don’t mind the number of possible combination for that, this is the goal of password). Think to the captcha of google that is the “Do you see a car on image ?”. We don’t mind if the answer if “Yes” or “yes”, all thing we need is to get yes or no.

**Comment by victorcardim-zz** [comment]
Hello!

Thank you for your answer and clarification.
