### ISSUE TITLE
Retained warranty

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#14524]
# Instructions
on situation invoices.

# Bug
the retained warranty computed on the 100% invoice should be computed ont the total amount and not only on the final situation invoice.
+ VAT should be displayed separately for warranty 

## Environment
- **Version**: 11.0.5

**Comment by atm-maxime** [comment]
@atm-john ?

**Comment by john-botella** [comment]
Hi,

This is the first version of retained invoice, in 12.0 of Dolibarr there is more options to manage how is computed warranty.
I invite you to test the options.

In your case it should computed on the 100% but for others people it should be computed by an other way and for still others it should be computed by still an other way.

So is't not a bug, it's just a missing feature in 11.0

For VAT is it a legal obligation ? 
The footer will be probably huge if there is a lot of different VAT, no ?
If it's separate, is it also separate for accounting ?

Have a nice week end.
