### ISSUE TITLE
Can't add project time spent 

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#14527]
# Instructions
create a project with contact limited view
add a contact from an external company to this project

# Bug
the external contact are not allowed to add time spent even if they are on the task
the system keep asking to add the contact to project first, even if he is inside

## Environment
- **Version**: 11.0.5

**Comment by atm-maxime** [comment]
I think that's because external contact are not supposed to have time spent recorded. Only users can. 😉

**Comment by homer8173** [comment]
It may be the correct answer but he can spent time if the project is public. The system keep asking to add as contact first if project is limited to contacts. It sounds like a bug but I haven't open the code (I was on meeting)

**Comment by eldy** [comment]
Still the trouble in v12.0 ?
