### ISSUE TITLE
Api Explorer returns error 

### ISSUE THREAD

**Issue by borisduin** [Dolibarr/dolibarr#14534]
# Bug
[*Api Explorer returns error*]

## Environment
- **Version**: *12.0.3*
- **OS**: *Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux*
- **Web server**: *Apache*
- **PHP**: *7.3.21*
- **Database**: *Mysql 5.7.30*
- **URL(s)**: */api/index.php*

*Verbose description*

## *When try to access dolibarr api via explorer option, this returns an invalid reponse from swagger. 
{"messages":["attribute paths is not of type `object`"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (array) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/paths"},"instance":{"pointer":"/paths"}}]}

*
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/15090218/91003940-5b6ed000-e598-11ea-8db6-3ef0a7cfa5be.png)
![image](https://user-images.githubusercontent.com/15090218/91004016-9cff7b00-e598-11ea-9dba-c97f8cd94ffe.png)

**Comment by dpriskorn** [comment]
I'm using the rest explorer on 12.0.2 version without problems. 
Did you install from git? Which commit?

**Comment by borisduin** [comment]
I installed via git. Commit 6e01ffd5

**Comment by borisduin** [comment]
I updated to commit 243f59b9e9, but unsolved. 
In production server showed same error. In my development enviroment showed explorer screen with headers without any API option.
 
I solved this problem changing in file api/index.php, line 59 
-- $url = $_SERVER['PHP_SELF'];
++ $url = $_SERVER['REQUEST_URI'];

Works fine in my dovelopment docker enviroment with NGINX and a production server with APACHE.

**Comment by dpriskorn** [comment]
Is this still present in v13?

**Comment by Computences** [comment]
Hello, problem still present in 14.0.2.
Replacing $_SERVER['PHP_SELF'] with $_SERVER['REQUEST_URI'] in file api/index.php solved the problem.

**Comment by Rascarquapac** [comment]
I got the problem with 14.0.4.

Replacing $_SERVER['PHP_SELF'] with $_SERVER['REQUEST_URI'] in file api/index.php solved the problem... for explorer but not for other API request (invoices,...). I changed in file api/index.php, line 86

-- $_SERVER['PHP_SELF'] ;
++ $url =  $_SERVER['SCRIPT_NAME'].$_SERVER['PATH_INFO'];

- On a docker instance $_SERVER['PHP_SELF'] is "/api/index.php/invoices" and both explorer and other request do work.
- On a production instance (OVH, no url rewriting in .htaccess) $_SERVER['PHP_SELF'] is "/invoices": nor explorer or other API request do work.

Using $url =  $_SERVER['SCRIPT_NAME'].$_SERVER['PATH_INFO']; is ok on both , but I am not able to understand why $_SERVER['PHP_SELF'] is different in the two cases.

**Comment by inoveaconseil** [comment]
I can't reproduce in 14.0.5
