### ISSUE TITLE
Sorting by physical stock desc does not work in product list

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14549]
# Bug
it is not sorted

## Environment
- **Version**: v12
- **URL(s)**: http://dolibarr.localhost/product/list.php?sortfield=p.stock&sortorder=desc&begin=&contextpage=productlist&search_tosell=-1&type=0&search_type=0&search_options_sello_tosell=0

## Expected and actual behavior
expected the most stock in the top and the least in the bottom
![Skärmbild_2020-08-25_13-13-31](https://user-images.githubusercontent.com/68460690/91167983-1dc39180-e6d5-11ea-9a98-e3bd1efedb72.png)

**Comment by eldy** [comment]
Can't reproduce currently on 12 branch. Someone else has the trouble ?

**Comment by dpriskorn** [comment]
I will test on my own develop instance once I get it installed.

**Comment by atm-kevin** [comment]
I can't either reproduce the bug on 12 branch.
