### ISSUE TITLE
Add focus when editing on product/stock/product.php

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14548]
# Bug
when I press the modify symbol on this page I get the input field but its not focused which leads to an extra click for the user which is annoying

## Environment
- **Version**: v12
- **URL(s)**: http://dolibarr.localhost/product/stock/product.php

## Expected and actual behavior
always focus field when editing

**Comment by eldy** [comment]
:+1:

**Comment by dpriskorn** [comment]
Thanks @eldy 😃
