### ISSUE TITLE
Unable to Sort Using the Pending Payments on Commercial Invoice List View

### ISSUE THREAD

**Issue by thegeettanna** [Dolibarr/dolibarr#14558]
#13973 Bug
Unable to sort page results on Commercial Invoice page based on the pending payments. 
![Screen Shot 2020-08-24 at 1 13 17 PM](https://user-images.githubusercontent.com/24646523/91232652-248deb00-e74d-11ea-9246-ea5a4ee77239.jpg)
## Expected and actual behavior
When we click Amount (excl tax) or Amount (incl tax), the page results are sorted ascending or descending. But when we have other fields "Received" & "Pending" Columns added to the list, they unfortunately are not clickable and thus un sortable. 

## Steps to reproduce the behavior
Show fields "Received" & "Pending" on the list page of commercial invoices to show them on the page. After which you would be able to test it out. 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
This feature is not yet implemented. This is why the title is not blue (not sortable). 
to be able to sort it we must implement another column that will be update with the dynamic calculation of pending payement each time a payment is create, or a credit not or down payment is added to invoice.

**Comment by thegeettanna** [comment]
@eldy, 

Okay. Thank you for the information. 
It is good to know how it should be implemented. 
But I think it would be implemented in near future updates as it is useful and easy to implement. 
So will wait for it for a few weeks, that way I don't mess the system up. 

Thank you for all your efforts 👍🏻
