### ISSUE TITLE
Warn on the product card when selling price(s) or buying prices or cost is missing

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14551]
# Feature Request
show the user whether the product is missing crucial information

## Use case
better overview on product card of product "readiness"

## Suggested implementation
a status in top right corner like on orders

**Comment by thegeettanna** [comment]
It seems useful. 
New to this community, so not sure how to upvote. 
So, going to say "Upvote" here instead 😅
