### ISSUE TITLE
Extrafields of lines is missing on orders, orders/{id}/lines and supplierorders REST endpoints

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14556]
# Bug
dolibarr should always output extrafields 

## Environment
- **Version**: v12

## Expected and actual behavior
expected array_options to be populated as it is on the /product

## Steps to reproduce the behavior
add an extrafield to the product module
create a product and fill in the extrafield
test getting the product using /product -> extrafield show up in array_options
now add the product to a new order
get the order using /orders -> lines show up but no extrafields (array_options is [])

**Comment by eldy** [comment]
Do you have the value into database of order lines or is it just in the reading API that you miss the extrafields fields ?

**Comment by dpriskorn** [comment]
Only reading. I dont know how to Post extrafield via the API, is it supported? I insert extrafields directly into the database which works but is obviously suboptimal.
