### ISSUE TITLE
Unable to create table `llx_product_attribute_combination_price_level` upon clean install

### ISSUE THREAD

**Issue by ERP-Academia** [Dolibarr/dolibarr#14562]
I am making a clean install from 23bb678

The creation query is in fact two queries devided by ";". Separately they work.

**Error message:**
```SQL Error DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ALTER TABLE llx_product_attribute_combination_price_level ADD UNIQUE( fk_product' at line 10```

**Offending query:**
```CREATE TABLE llx_product_attribute_combination_price_level ( rowid INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, fk_product_attribute_combination INTEGER DEFAULT 1 NOT NULL, fk_price_level INTEGER DEFAULT 1 NOT NULL, variation_price DOUBLE(24,8) NOT NULL, variation_price_percentage INTEGER NULL )ENGINE=innodb; ALTER TABLE llx_product_attribute_combination_price_level ADD UNIQUE( fk_product_attribute_combination, fk_price_level);```

**Comment by atm-maxime** [comment]
@atm-john

**Comment by ERP-Academia** [comment]
Perfect!
