### ISSUE TITLE
Invoice regeneration on payment ignores PDF preferences

### ISSUE THREAD

**Issue by hameau** [Dolibarr/dolibarr#14588]
## Environment
- **Version**: 12.0.2
- **URL(s)**: `htdocs/compta/paiement/class/paiement.class.php`

## Expected and actual behavior
Making a payment against an invoice (optionally) regenerates the invoice document. This feature fails to check the state of the PDF options in Setup-PDF system configuration (hide reference, details, description – MAIN_GENERATE_DOCUMENTS_HIDE_ ... preferences).

## Steps to reproduce the behavior
Setup-Other MAIN_DISABLE_PDF_AUTOUPDATE must be unset;
Setup-PDF must be set to hide any/all of 'product description', 'product reference' or 'product lines details'.

When a payment is made, the invoice is regenerated, but does not take account of the Setup-PDF preferences set above.

---
_**Local mitigation**_
The PDF preferences are only checked in `htdocs/compta/facture/card.php` (for invoices), but the payment automatic regeneration calls `generateDocument()` in `htdocs/compta/facture/class/facture.class.php`, which bypasses the PDF preferences.

For my use-case, I have `MAIN_GENERATE_DOCUMENTS_HIDE_REF = 1` and have added locally:
```patch
--- htdocs/compta/paiement/class/paiement.class.php - distributed
+++ paiement.class.php - locally modified
@@ -427,7 +427,7 @@
                             	$outputlangs->setDefaultLang($newlang);
                             }
                             $ret = $invoice->fetch($facid); // Reload to get new records
-                            $result = $invoice->generateDocument($invoice->modelpdf, $outputlangs);
+                            $result = $invoice->generateDocument($invoice->modelpdf, $outputlangs, '', '', $hideref = $conf->global->MAIN_GENERATE_DOCUMENTS_HIDE_REF);
                             if ($result < 0) {
                             	setEventMessages($invoice->error, $invoice->errors, 'errors');
                             	$error++;
```

**Comment by papoteur-mga** [comment]
I hit this bug in 11.0.4 too.
It seems fixed currently.
