### ISSUE TITLE
Measuring Units

### ISSUE THREAD

**Issue by Kadantte** [Dolibarr/dolibarr#14590]
After I add two measuring units Unite and Ensemble I get unitUnite or unitEnsemble into my pdf is there a way to show just my Unite or Ensemble?

![image](https://user-images.githubusercontent.com/11579313/91672855-ba2ad100-eae5-11ea-8898-eaa98351377f.png)

**Comment by Kadantte** [comment]
Fixed!

**Comment by atm-maxime** [comment]
Solution ?
