### ISSUE TITLE
Unexpected Behaviour when creating modules with numeric values

### ISSUE THREAD

**Issue by Arcr0s** [Dolibarr/dolibarr#14598]
# Bug
When using the module builder to create a new module and you use numeric values at the start of the identifier string dolibarr starts behaving unexpected, Module Builder site and Module Option site do not load properly/at all. Will only resume normal operation when deleting the module.

## Environment
- **Version**: 11
- **OS**: Linux (ubuntu 16.04)
- **Web server**: Apache 2.4.9
- **PHP**: 7
- **Database**: MySQL or MariaDB 5.7.29
- **URL(s)**: https://lifadolibarr.westeurope.cloudapp.azure.com/admin/modules.php
                    https://lifadolibarr.westeurope.cloudapp.azure.com/modulebuilder/index.php?module= [ModuleName]
## Expected and actual behavior
Expected to normaly show settings and info, but displays none of the core information besides side and top bar.

## Steps to reproduce the behavior
Use the module builder to create a module with numeric values at the start

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?
