### ISSUE TITLE
BUG: only 1 additionnal module for POS buttons

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#14594]
takepos/index.php line 960
`$hookmanager->initHooks(array('takeposfrontend'));
$reshook = $hookmanager->executeHooks('ActionButtons');
if (!empty($reshook)) {
	if (is_array($reshook) && !isset($reshook['title'])) {
		foreach ($reshook as $reshook) {
			$menus[$r++] = $reshook;
		}
	} else {
		$menus[$r++] = $reshook;
	}
}`

with my last PR we can add severals buttons but always from 1 module (only display buttons of last activated module)

We should add any buttons from severals external module (ie adherentsplus, rewards...) for 2,3,4... additionnals buttons.

cc @andreubisquerra @eldy

**Comment by atm-quentin** [comment]
Hello,
Can you please specify the dolibarr version in which you have encountered this problem ?

**Comment by ptibogxiv** [comment]
it 's occured in v12+
