### ISSUE TITLE
propal list accessible to users without rights

### ISSUE THREAD

**Issue by Crush33** [Dolibarr/dolibarr#14601]
# Bug

## Environment
- **Version**: v9 + v11
- **OS**: debian 9
- **Web server**: apache2
- **PHP**: 7.0
- **Database**: mariadb
- **URL(s)**: /comm/propal/list.php

## Expected and actual behavior
user should not access to propal list.

## Steps to reproduce the behavior
Create a group with full access to the third party only
Create a user and assign it to this group.

Connect with this user and go to a third-party client (or prospect) tab.
Click on the proposal button (with the amount of all the client's proposals)
there I have a table that opens with all the comments and their amounts (dolibarr/comm/propal/list.php), I cannot enter a proposal but normally I must have access denied page and never have access to this list.

If I do the same with invoice, I do have access denied, same for order.

**Comment by atm-lena** [comment]
Fixed in 11.0
