### ISSUE TITLE
When deleting a customer order Dolibarr ignores linked invoices

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14608]
# Bug
When deleting a customer order I get no warning about linked invoices. I think we should offer the user to delete linked invoice(s) which have still not been binded in the ledger.

## Environment
- **Version**: 12.0.2
- **URL(s)**: commande/card.php

## Expected and actual behavior
I expected Dolibarr to do the cleanup for me. Instead Dolibarr just deleted the order and gave me no information about the lingering invoice and or payments.

**Comment by atm-arnaud** [comment]
Hi,

You right but i think this is not a bug but a New Feature. Could you change your label ?

Regards,

**Comment by atm-arnaud** [comment]
@eldy to know it
