### ISSUE TITLE
Tickets - Edit ticket card button from Events/Agenda page directs to localhost 

### ISSUE THREAD

**Issue by rogerbulcock** [Dolibarr/dolibarr#14613]
# Bug
When modifying an existing ticket event the modify icon link directs to local host rather than the FQDN of the server

## Environment
- **Version**: 12.02
- **OS**: CentOS Linux release 7.8.2003 (Core) (3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64)
- **Web server**: Apache/2.4.6 (CentOS) PHP/7.3.21 
- **Web proxy**: nginx/1.16.1
- **PHP**: PHP/7.3.21
- **Database**: mysql  Ver 15.1 Distrib 5.5.65-MariaDB, for Linux (x86_64) using readline 5.1
- **URL(s)**: https://FQDN/dolibarr/htdocs/ticket/messaging.php?track_id=9g6cx6sal962iskb

## Expected and actual behavior
When modifying an event form the Ticket / Events/Agenda page the modify link is to localhost rather than the FQDN of the server.

Expected:
https://FQDN/dolibarr/htdocs/comm/action/card.php?action=edit&id=6

Actual:
https://127.0.0.1/dolibarr/htdocs/comm/action/card.php?action=edit&id=6

## Steps to reproduce the behavior
Assume we have an existing ticket with events

Ticket / List / "Select a Ticket" / Events/Agenda / Modify event

## Possible solution
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/lib/ticket.lib.php

Line 694

Change from:
```
    $out .= '<a class="timeline-btn" href="'.DOL_MAIN_URL_ROOT.'/comm/action/card.php?action=edit&id='.$actionstatic-id.'"><i class="fa fa-pencil" title="'.$langs-trans("Modify").'" ></i></a>';
```

To:
```
    $out .= '<a class="timeline-btn" href="'.DOL_URL_ROOT.'/comm/action/card.php?action=edit&id='.$actionstatic-id.'"><i class="fa fa-pencil" title="'.$langs-trans("Modify").'" ></i></a>';
```

This works for my environment and configuration.

**Comment by dpriskorn** [comment]
Could you send a pull request?

**Comment by atm-quentin** [comment]
Hello,

Thanks for reporting.
I'll have a look.

**Comment by atm-quentin** [comment]
This is already corrected in latest v11 can you upgrade your dolibarr and confirm that it's working now ?
