### ISSUE TITLE
Bug on adherents Extra filed adding form

### ISSUE THREAD

**Issue by yah00078** [Dolibarr/dolibarr#14616]
Hello, 
Please find below encountered bug. I can only add letters as "abc"
![Capture](https://user-images.githubusercontent.com/49900484/92086595-ac699a00-edca-11ea-86a4-301ee8beebea.PNG)

Dolibaar 11.0.3

Thank you !

**Comment by ksar-ksar** [comment]
HI,

It seems to be OK.
Attribut Code can't be only numbers.

**Comment by atm-quentin** [comment]
Hello,
Thanks for reporting, i'll have a look.
