### ISSUE TITLE
“Mark as credit available” handles credit note's positive amounts as negative

### ISSUE THREAD

**Issue by atm-florianm** [Dolibarr/dolibarr#14628]
# Instructions
* Create an invoice with one product (for 200€)
* Create a discount for that client with 100€
* Apply the discount to the invoice → an invoice line with -100 € is inserted
* Convert the invoice into a credit note with the same lines → a credit note with two lines (-200€ and 100€) is created
* Mark as credit available

Alternatively, you can also use the "old" method by enabling `FACTURE_ENABLE_NEGATIVE_LINES` and adding a line with -100€ on the invoice at the beginning (the effects are the same in the end).

# Bug
When you do this, Dolibarr creates two discount (one for each line): one amounting 200€ and one amounting 100€, so the sum of the discounts is 300€ instead of 100€.

Negative discounts don't make sense to me, so I do understand why it doesn't create one, but even though I don't know what the right solution would be, I think the current behavior entails miscalculations.

## Environment
- **Version**: at least from 3.8 to 12.0
- Other environment specifications not relevant to the issue

## Expected and actual behavior
I don't know exactly how Dolibarr should handle the situation, but I would expect a total discount of 100€ (200 - 100) instead of 300€ (200 + 100).

**Comment by atm-maxime** [comment]
Just to be more precise, the issue is when the discount line has a vat rate different than the other lines. But I am not sure this case should happen. Why would a discount have a vat rate different?

**Comment by TomNok** [comment]
I found the same bug but for the new supplier deposit invoices turning into discounts.
See screenshot, article of 53, discount of 5 => payment of 53-5=48, but available discount is  58 (53 + 5)..

![Schermafdruk van 2021-09-09 01-42-27](https://user-images.githubusercontent.com/90422744/132766666-7d189140-abd1-4dae-bcba-30acb8f340bb.png)
