### ISSUE TITLE
Changine letter sizes to inches crashes site (HTTP500 error)

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Dolibarr/dolibarr#14625]
# Instructions
# Bug
[Using inches in page layouts creates HTTP 500 error]

## Environment
- **Version**: [12.0.2]
- **OS**: [Windows 7]
- **Web server**: [Apache v2.4]
- **PHP**: [7.2.8]
- **Database**: [mySQL v8.0.21 (32bit)]
- **URL(s)**: [/admin/facture.php?action=specimen&module=crabe]

## Expected and actual behavior
[Expect it to create a PDF the correct site, actually crashes the site with HTTP 500 error, appears to not be able to create any PDF file]

## Steps to reproduce the behavior
[Changing the page layout sizes ot inches (Setup > Dictionaries > Paper formats > USLetter and USLegal to Inches with the correct sizes.  When testing these template results in a HTTP500 error (with the above URL), also creates an issue with every line added to a new invoice]

**Comment by dpriskorn** [comment]
Which version are you using?

**Comment by GRIFFCOMMca** [comment]
12.0.2

That said, not sure if its 12.0.2 or 12.0.0 Alpha, how can i tell?

**Comment by frederic34** [comment]
crabe is outdated, use sponge
