### ISSUE TITLE
Unit denominations not correctly generated on pdf

### ISSUE THREAD

**Issue by afreenet** [Dolibarr/dolibarr#14654]
# Bug
With "using units" activated at the proposals there is a denomination that is generated with unit's shortname preceded by "unit" for example when you chouse the unit Month with its shortname M it shows unitM
## Environment
- **Version**: [12.0.3]
- **OS**: [centos 7]
- **Web server**: [apache 2]
- **PHP**: [7.0]
- **Database**: [mysql]
- **URL(s)**: [comm/propal/card.php?id=3#builddoc]

## Expected and actual behavior
When you choose the unit the final document should show the shortname

## Steps to reproduce the behavior
Activate units and enerate a proposal or invoice

![gnome-shell-screenshot-GV7JQ0](https://user-images.githubusercontent.com/51289193/92380534-de476d00-f0f8-11ea-8907-203ae1ad75bc.png)
![Capture-20200907105604-567x70](https://user-images.githubusercontent.com/51289193/92380537-df789a00-f0f8-11ea-96e0-e6156538ddf5.png)

**Comment by atm-quentin** [comment]
Hello thanks for reporting.
I'll have a look

**Comment by atm-quentin** [comment]
Have you tried to upgrade to v12.0.4 ? Because i can't reproduce this error.
