### ISSUE TITLE
Decimal comma in field "Quantity" is not properly registered

### ISSUE THREAD

**Issue by jacmart** [Dolibarr/dolibarr#14666]
# Bug
*Decimal comma in field "Quantity" is not properly registered when user interface is localized to a "Latin spelling" (therefore not using the English "decimal point "spelling for fractions). On several input forms, it produces unexpected results.*

## Environment
- **Version**: *Ver 11.0.4 fr_FR*
- **OS**: *Linux*
- **Web server**: *Apache Shared host*
- **PHP**: *PHP 7.4*
- **Database**: *Mysql 5.7*
- **URL(s)**: *see below*

## Expected and actual behavior
*The quantity field describing a product can be written with a comma (e.g. 0,5) in the "latin" (e.g. French, German etc...) localized interfaces. However in some cases while it is only the English decimal point that can be used, the input of a comma yields unexpected results*

## Steps to reproduce the behavior

Input of a comma for fraction of product quantity in the following forms 
**1. Nouvelle propale**
behavior: no warning, page reloading, no reaction

**2. Expedition (> envoi partiel)**
behavior: the comma input triggers a warning : "le champ "Qté. a expedier/entrepot" est obligatoire". However that warning itself might be somewhat misleading

**3. Corriger stock (< stock < produit )**
Following a [conversation on the English Dolibarr forum with _fappels_ , a [fix ](https://github.com/Dolibarr/dolibarr/commit/2e7f588cacd3731b037db4f3ff2a4bf6154312d1) has been already implemented for version 13 

<hr>

**Workaround**
Until it is fixed, use the decimal point for describing fractions in quantities in all the described cases

**No fix needed**
All the following forms and quantity fields behave nicely with fraction commata as expected in French localized interface

- Nouvelle Commande
- Facture fournisseur, facture client
- Nouvelle commande fournisseur
- Contrat
- Demande de prix

### RELATED BUG

There is yet another specific inconsistency related both to the comma bug and stock movements :
the **stock movement list** ends up **displaying events that were not registered** because of the comma bug. They are therefore misleading as they had no impact on the stock.

This related bug might or might not be cured partially by curing the actual comma problem. 
As far as I could test it, the **decimal commata** but also **negative numbers** deceivingly appear in the list of movements (they are not truly registered in the stock though).

**Comment by atm-maxime** [comment]
Thanks for this detailed issue !

**Comment by atm-maxime** [comment]
Hi. I just made a few test in v11.
Seems to me that when adding a line in a proposal, using a qty like "1,5" is correctly working.

In shipments and in stock, you're right, it works with the ".", not with the ",".
