### ISSUE TITLE
email field does not constraint to a valid email address

### ISSUE THREAD

**Issue by erachen** [Dolibarr/dolibarr#14670]
# Bug
[email field does not constraint to a valid email]

Some user fill several mail address in the same field separated by space, semi-colon or comma.

As a result, emailing may or may not being sent correctly and it's not really clear for user what's wrong.

## Expected and actual behavior

exemple (contact for tiers):
name: `compta`
email: `mail1@provider.one; mail2@provider.two`

The (wrong) constructed email is
`"compta" <mail1@provider.one; mail2@provider.two>`

I think there is three way of dealing with this issue:
1. add a constraint for email field to allow only one email address
-> therefore there is only one email address: `"compta" <mail1@provider.one>`

2. parse the email field to find 0, 1 or several differents email address and deal with each
-> `"compta" <mail1@provider.one>, "compta" <mail2@provider.two>`

3. allow a "raw" (without `"Human readable name" <email@address>`) sent, therefore several comma separated email address will result as
`mail1@provider.one, mail2@provider.two`
and not
`"compta" <mail1@provider.one, mail2@provider.two>`

When method to sends email is set to `"PHP mail function"`, this function seems to be able to extract correctly
`mail1@provider.one` on one hand and `mail2@provider2.two` on the other hand.
So the emailing will *seems* to work.

However, the email header "To: " is set raw :
`mail1@provider.one,mail2@provider.two`

When method to sends email is set to `"SMTP/SMTPS socket library"`, the constructed email is sent directly to the MTA
and every MTA on earth will refuse
`"compta" <mail1@provider.one; mail2@provider.two>`

Emails nowdays is complex and a dolibarr installation is likely to upgrade it's mailing system from `"PHP mail function"` to a stronger MTA system `"SMTP/SMTPS socket library"`.

So for user experience: it works before the upgrade and not after

## Environment
- **Version**: [11.0.4]
- **OS**: [Debian 10 64 bits]
- **Web server**: [nginx 1.14.2]
- **PHP**: [7.3.19]
- **Database**: [Ver 10.1.44-MariaDB]
- **URL(s)**: [*Affected URL(s)*]

## Steps to reproduce the behavior

- configure dolibarr to use `"SMTP/SMTPS socket library"`
- create a customer tiers
- create an invoice for the customer tiers
- create a contact for a customer tiers
- Fill several email address in the email field, you can use space, comma or semi colon as separator it will lead to the same wrong behavior
- in the customer page, try to send the invoice to the contact you just fill in, you will get an error with this wrong email address of the form:
`"compta" <mail1@provider.one, mail2@provider.two>`

**Comment by atm-maxime** [comment]
Hi. I think this issue can be closed. Since version 12, there's a check on email fields to allow only one correctly formatted email address.

**Comment by erachen** [comment]
I confirm, thanks for follow up
