### ISSUE TITLE
Close mass action on propale list disappeared in V12

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#14678]
The closing mass action on proposals list has disappeared in V12 :

![image](https://user-images.githubusercontent.com/11922840/92568952-35c41500-f280-11ea-9fd7-fdd9ae4bee85.png)

It was here in V11 and is ok in develop version.

![image](https://user-images.githubusercontent.com/11922840/92569010-4c6a6c00-f280-11ea-81ca-917317d01903.png)

![image](https://user-images.githubusercontent.com/11922840/92569070-66a44a00-f280-11ea-8416-5e3b8b7d029f.png)

**Comment by atm-adrien** [comment]
Hello,
I'm working on this,

I'll tell you when it'll be corrected

**Comment by atm-adrien** [comment]
@RomainDeschamps 
Have you tried restarting the module?
I think the problem was with the permissions ("closed" in proposals module) that were not updated. Restarting the module could fix this bug.
