### ISSUE TITLE
Bug: editing an overwritten translation is impossible - page just reloads

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14685]
# Bug

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.8
- **Database**: PostgreSQL 12.3
- **URL(s)**: /admin/translation.php?rowid=24&entity=1&action=edit&page_y=510

## Expected and actual behavior
expected a form to edit the already overwritten translation

got page reload

## Steps to reproduce the behavior
overwrite a translation
go to the list of translations
click the pencil symbol

**Comment by dpriskorn** [comment]
Editing directly in the table llx_overwrite_trans works fine

**Comment by dolibit-ut** [comment]
Do you know what the problem was or have you already solved it?

nginx?

**Comment by dpriskorn** [comment]
I suppose its a bug in dolibarr

**Comment by dpriskorn** [comment]
I worked around it by editing in the database

**Comment by atm-adrien** [comment]
Hello, 
Can you give me more details on the path you followed in order to overwrite the translation?
I went through the configuration menu, then translating and overwriting worked great (I'm in version 12.0.4)
