### ISSUE TITLE
no error message when a Payment can not be erased with a Conciliated bank line 

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#14686]
HEllo, 

When you record a payment and conciliate the line, if you notice an error after having sorted the invoiced "payed" etc...

If you try to re-open it and delete the payment, it doesnt work because the bank line is protected by the conciliation
AND MOST IMPORTANT : NO ERROR MESSAGE IS THROWN

Steps: 
create an invoice
register the payement
conciliate on the bank line (set as "conciliated""
re open invoice 
try to delete payment
= not working, no error message.

I know the workoarround is to "unconciliate" the bank line, but a message should be displayed if not possible to delete the payment.

**Comment by atm-quentin** [comment]
Hello,
Can you please specify the dolibarr version in which you have encountered this problem ?
