### ISSUE TITLE
calculation VAT and TTC

### ISSUE THREAD

**Issue by hanen91-ch** [Dolibarr/dolibarr#14687]
Hi everybody,
would you like to help me, i have a problem about modifying the VAT calculation and the VAT amount.
I explain how I want to modify them.
for example :
HT = 10.000
TAX 2 (1%) = 0.100
VAT (19%) = (mnt HT + TAX2) * 19%
TTC = HT + TAX2 + VAT

**Comment by eldy** [comment]
It is really not common to have the VAT calculation that include the TAX 2. This opposite occurs in a lot of country but this cas is the first time. What is your country ? What is the name of the Tax2 in your country ? Are you sure it is not the opposite:
HT = 10.000
VAT (19%) = mnt HT * 19% = 1.9
TAX 2 (1% of HT +VAT) = 0.19
TTC = HT + TAX2 + VAT
Result for HT and TTC should be same but repartition between VAT and TAX2 will differ.

**Comment by hanen91-ch** [comment]
Thank you for your return, my country is tunisia, and my second tax is the fodec (1%). And for the calculation it is sure as I have already said.
HT = 10,000
TAX 2 (1% HT) = 0.100
VAT (19%) = (mnt HT + TAX2) * 19% = 1.919
TTC = HT + TAX2 + VAT

**Comment by eldy** [comment]
OK. The following page is speaking about this trouble (in french):
https://wiki.dolibarr.org/index.php/R%C3%A8gles_de_calcul_et_arrondi_de_TVA#Pour_la_Tunisie

**Comment by dolibit-ut** [comment]
if you add all the taxes to the net amount, the order doesn't matter:

net/ht = 100 
1%  100 * 0.01 = 1
19%   100 * 0.19 = 19 
Summe/total = 120

and if you have to add/mutliply one tax to the other it also shouldn't matter:

A)
net/ht = 100 
+ Tax1  (   1%)   100 * 1.01 =  101,00
+ Tax2  ( 19%)   101 * 1.19 =  120,19

B)
net/ht = 100 
+ Tax1  ( 19%)   100 * 1.19 =  119,00
+ Tax2  (   1%)   119 * 1.01 =  120,19

always the same result

**Comment by hanen91-ch** [comment]
Salut à tous, 
merci à vos idées, mais je veux juste savoir ou se fait exactement le calcul de tva si on utilise un 2éme taxe.
Merci à vous.
