### ISSUE TITLE
Doliconnect as Dolibarr B2B e-Commerce Module

### ISSUE THREAD

**Issue by Jenbalco** [Dolibarr/dolibarr#14693]
# Feature Request
Dolibarr is great but the missing, built-in e-commerce feature would be a great addition. So in a research to find existing solutions I came across this project  as an idea for B2B eCommerce https://github.com/ptibogxiv/doliconnect? (demo here: https://demo.ptibogxiv.net)

## Use case
This would allow B2B eCommerce capabilities to companies  for easier order management, improved customer relationship through self-service features and additionally it would add unique features to Dolibarr not offered by many other Open Source Communities
## Suggested implementation
I think https://github.com/ptibogxiv/doliconnect (demo here: https://demo.ptibogxiv.net)  can be used to extend the CMS module in Dolibarr. For example pages can be built using blocks and transactions can be processed using existing integrations such as stripe and PayPal or create quotes, contracts .

**Comment by atm-maxime** [comment]
@ptibogxiv

**Comment by ptibogxiv** [comment]
@Jenbalco thanks for quote my work. B2B or big B2B business need more automations or settings. I add this to dolibarr step by step month after month.

Next steps: auto send invoice or order PDF with template, auto pay with stripe or paypal (with cron task): this is really need when thousands orders or invoices by month

Doliconnect is for B2B or B2C e-commerce with ERP managed as big company (better for management et quick work)

Have you some examples of features that you need ?

**Comment by Jenbalco** [comment]
@ptibogxiv that integration is a great piece of work for sure, so it deserved to be highlighted. 

I think it is a great idea to add the subscription products/services with recurring billing capacities. that will work well for us. So I am very excited about the future of Doliconnect sir.

 I think on the wordpress side there are still some minor script errors that surface at times in regards to shipping and billing addresses. aside from that. I think it is a great tool. 

Can you tell me if adding Doliconnect as part of the core e-commere utilities in Dolibarr is something that you and @eldy have considered ?

Most importantly, thank you so much for your contribution to Dolibarr and Doliconnect is great.

**Comment by ptibogxiv** [comment]
You can when using adhérent plus and soon i add consumption as mobile/Phone  subscription

(long and difficulté to be Power full)

If you had specific request i can add it but keep in mind that free dev (often long), pay développement is more Quick because we can Block time for you.

For shipping/billing address, some changes occured in Dolibarr so i need to work on a fix.

**Comment by Jenbalco** [comment]
@ptibogxiv We are exploring some custom solutions after the release of version 13. We will be sure to reach out to define the scope of our project. 

Thanks!

**Comment by whp-jeffm** [comment]
I would still love to see this implemented.
