### ISSUE TITLE
Quick add window not displayed correctly

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#14709]
constant ``MAIN_USE_TOP_MENU_QUICKADD_DROPDOWN`` brings a nice feature but...

![image](https://user-images.githubusercontent.com/11922840/92889939-f5e36600-f416-11ea-8af0-104f11108b8a.png)

**Comment by aspangaro** [comment]
Hi @RomainDeschamps 

Please, you can give me your browser and your resolution ?

**Comment by aspangaro** [comment]
Result on Firefox 80 on Easya : 

![image](https://user-images.githubusercontent.com/2341395/93026383-dcecd780-f605-11ea-9057-73207cf1a14d.png)

**Comment by RomainDeschamps** [comment]
@aspangaro,

Firefox 80.0.1
1536 x 760

Better on Brave and Chrome nav.
![image](https://user-images.githubusercontent.com/11922840/93056755-2e7c7d00-f66d-11ea-9c6e-b48b6379ddd5.png)

**Comment by cfoellmann** [comment]
I just tested this feature.
For me its also not pretty.

![image](https://user-images.githubusercontent.com/1256090/118841553-b552bb00-b8c8-11eb-8c4c-240e1aa4576a.png)
Windows 10 + Chrome 90.x + 2560x1440

**Comment by cfoellmann** [comment]
for a simple listing like the bookmarks dropdown would be far better and easier to use
