### ISSUE TITLE
Supplier Orders Awaiting Reception

### ISSUE THREAD

**Issue by BlueGarm** [Dolibarr/dolibarr#14719]
# Feature Request
Modify widget and dashbord to show the number of supplier order Awaiting Rececption and Order Already Partially Received

## Suggested implementation
Modification of two files :
`/core/boxes/box_supplier_orders_awaiting_reception.php`
line : `$sql .= " AND c.fk_statut = ".CommandeFournisseur::STATUS_ORDERSENT;`
by : `$sql .= " AND fk_statut IN (".CommandeFournisseur::STATUS_ORDERSENT.",".CommandeFournisseur::STATUS_RECEIVED_PARTIALLY.")";`

And 

`/fourn/class/fournisseur.commande.class.php`
line :  `$sql .= " AND c.fk_statut = ".self::STATUS_ORDERSENT;`
by : `$sql .= " AND fk_statut IN (".self::STATUS_ORDERSENT.",".self::STATUS_RECEIVED_PARTIALLY.")";`

There are maybe another files to modify but actually in my version it's working like that,

Thanks

**Comment by BlueGarm** [comment]
Maybe also modify the line : (in `/fourn/class/fournisseur.commande.class.php`)
`$response->url = DOL_URL_ROOT.'/fourn/commande/list.php?statut=3&mainmenu=commercial&leftmenu=orders_suppliers';`

By : 
`$response->url = DOL_URL_ROOT.'/fourn/commande/list.php?statut=3,4&mainmenu=commercial&leftmenu=orders_suppliers';`

This modify the clickable link in the dashboard, and show both type of order.

**Comment by dpriskorn** [comment]
Could you send a pull request?

**Comment by BlueGarm** [comment]
> Could you send a pull request?

Done here : https://github.com/Dolibarr/dolibarr/pull/14800
