### ISSUE TITLE
Chart of Accounts Account number truncates last digit if its "0" [zero]

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Dolibarr/dolibarr#14722]
# Bug
[Chart of Accounts Account number truncates last digit if its "0" [zero]]

## Environment
- **Version**: [12.0.2]
- **OS**: [Windows 7, 64bit]
- **Web server**: [Apache 2.4]
- **PHP**: [7.2.8]
- **Database**: [MySQL or 8.0.12]
- **URL(s)**: [http://accounts/htdocs/accountancy/admin/account.php]

## Expected and actual behavior
[Adding an account number "4000" results in the system truncating the ending 3 zeros, so it adds the account as "4" and not "4000"]

## Steps to reproduce the behavior
[Add an new account with something like 5000, once saved it has truncated the ending zeros from the account number]

**Comment by aspangaro** [comment]
Hello @GRIFFCOMMca 

It's not a bug, you can manage account with zero in accountancy.
Some country like France don't use zero or maybe some virtual zero.

You can manage here :
![image](https://user-images.githubusercontent.com/2341395/93024010-41eb0200-f5f3-11ea-9929-86b0c79c58b6.png)

**Comment by GRIFFCOMMca** [comment]
Thanks, this fixed the issue
