### ISSUE TITLE
Error: Field 'Date' is required when modifying event

### ISSUE THREAD

**Issue by badboiaustria** [Dolibarr/dolibarr#14742]
# Bug
Error: Field 'Date' is required when adding event in event card. Actually the only way to be able to add an event is to click "Now". That date is fine and will be saved.but in case I select a date from popup calender, or enter my date via text field, it either throws the Error: Field 'Date' or simply does not change the date.

## Environment
Dolibarr current version (Programs) | 12.0.2
PHP 7.3.8
mysqli mysqlnd 5.0.12-dev
Apache

## Expected and actual behavior
it should simply take over the date I enter, or I select without error

## Steps to reproduce the behavior
Adding a new event and entering a start or enddate via textfield or calender.
independing of language settings of the user frontend (tried german and english)

[*Files*]
Video of the screen showing the bug:
https://drive.google.com/open?id=177WHcEJnzLXlL9sINBgIMEmQpy_O_WnT

**Comment by atm-quentin** [comment]
Hello,

Have you try to upgrade your dolibarr to the 12.0.4 version ? Because i can't reproduce it in this version.
