### ISSUE TITLE
Erreur d'arrondi du hors taxe dans facture->addline

### ISSUE THREAD

**Issue by uprisingweb** [Dolibarr/dolibarr#14765]
# Bug
Je constate que le problème vient lorsque, par exemple, j’ajoute de la main d’oeuvre directement avec une quantité de 0,33% et d’autre produit à l’unité.

J’ai par exemple un Montant HT de 17,80, une TVA de 3,56 et un Montant TTC de 21,35
Donc une différence de 0.01.
Ici le 2ème produit MOV en quantité 33% est calculé avec un HT de 15.13€
[Screenshot 1](https://www.dolibarr.fr/forum/uploads/default/original/2X/f/f9f56354c3b770c88637ccaf15486ff405b23413.png)

Si j’édite ma ligne main d’oeuvre et que je la revalide sans modification les totaux sont corrigés et corrects : 17,79 + 3,56 => 21,35
Apres édition le produit MOV en quantité 33% est calculé avec un HT de 15.12€ donc -0.01€
[Screenshot 2](https://www.dolibarr.fr/forum/uploads/default/original/2X/7/78d428f0903cac1d67e740737f344e5ef5543e60.png)

## Environment
- **Version**: 11.0.3
- **OS**: Unbuntu 18.04.5 LTS
- **Web server**: Apache 2.4.29
- **PHP**: PHP 7.2.24
- **Database**: MySQL 5.7.31

**Comment by eldy** [comment]
After calling the ->addline, the ->update_total() should update total.
When you say " j’ajoute de la main d’oeuvre directement...". Do you mean by your own code ? By API or by the user interface ?

**Comment by uprisingweb** [comment]
I mean by the user interface.

**Comment by atm-kevin** [comment]
I'm working on it.

**Comment by atm-kevin** [comment]
![Dolirush14765](https://user-images.githubusercontent.com/68547423/103750173-aef13000-5006-11eb-833b-c8d9b55f351f.png)

Bonjour,

Pouvez-vous tester la configuration en pièce jointe ? (Accueil => Configuration => Limites et précisions)

Si votre configuration "Limites et précisions" est différente de celle en pièce jointe, pouvez-vous l'ajouter en pièce jointe de cette issue ?

**Comment by redone147** [comment]
same probleme
