### ISSUE TITLE
Error While generating a Document for Stock Movements

### ISSUE THREAD

**Issue by LOTRg** [Dolibarr/dolibarr#14763]
Hello, 

When trying to Generate a Document for Stock Movements we are presented with this error 
"

> Error Failed to load doc generator with modelpaths=core/modules/stock/doc/ - modele=StdMouvement"

along with very Verbose output about the server, the DB Version and PHP  as if it's running in a debugging mode.

Can anyone help with this please ?

Thank you

**Comment by Tim-Otte** [comment]
There is a PR (#13709) that could fix this issue but it has not been merged. If somebody wants to fix this issue: that PR is correct and works just fine but needs to be atomic to be merged.
