### ISSUE TITLE
Change "Virtual Product" to "Kit"

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#14776]
I understand this would be a breaking change, but this choice of description/name is just plain wrong, and confusing/totally non-intuitive to new users. I don't find any other project using this nomenclature for a kit.

While it may have made some sense years ago, it certainly does not now, and I think it should be borne in mind to think about correcting it on a version change.

**Comment by dpriskorn** [comment]
I agree, we should follow industry standard as much as possible.  Where no standard exist we should create one with the other free software ERPs like Tryton.

**Comment by torvista** [comment]
A global change of text is no big deal PR-wise....but the underlying code should be planned to be reworked when appropriate, for consistency...or done on a version change to give a heads-up to add-on developers.
That needs to be on a roadmap....

**Comment by torvista** [comment]
:clap:
Wow, was it really that simple!!

**Comment by dpriskorn** [comment]
That was fast 😃
