### ISSUE TITLE
API Payments: bug with part payments

### ISSUE THREAD

**Issue by c3do** [Dolibarr/dolibarr#14783]
https://github.com/Dolibarr/dolibarr/blob/11bf662c381ccb4cffe444d6fe385dbdb8b15237/htdocs/compta/facture/class/api_invoices.class.php#L1488

it is not possible to record a partial payment via the API, when the multicurrency is active.The payment amount is replaced by the total invoice amount.

**Comment by dpriskorn** [comment]
Can someone confirm this?

**Comment by eldy** [comment]
Seems fixed with #14790
