### ISSUE TITLE
API Payment: Why shouldn't that be possible?

### ISSUE THREAD

**Issue by c3do** [Dolibarr/dolibarr#14781]
https://github.com/Dolibarr/dolibarr/blob/11bf662c381ccb4cffe444d6fe385dbdb8b15237/htdocs/compta/facture/class/api_invoices.class.php#L1469
It may happen that, inadvertently, a customer makes a transfer greater than the amount of the invoice. Why could not we add this payment to the invoice?

**Comment by dpriskorn** [comment]
Thanks for bringing this up. I agree that it should be possible, but perhaps a warning is warranted.

**Comment by eldy** [comment]
An option "accepthigherpayment" may be added to the API

**Comment by c3do** [comment]
> An option "accepthigherpayment" may be added to the API

There is not option "accepthigherpayment" and no limitation in dolibarr, so why not simply remove the limitation of the API, as i suggest in this PR #14790 ?

**Comment by c3do** [comment]
After checking, I hadn't noticed it, but there is indeed a small alert in dolibarr. I will try to improve the PR with an option to accept higher payment.

**Comment by c3do** [comment]
@eldy option integrated in PR #14790
