### ISSUE TITLE
Confusing naming. In the REST API its called supplierorders but the invoice is called vendor invoice in the main UI

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14795]
# Bug
inconsistent naming is bad and increases the learning curve unnecessarily IMO.

I suggest we get rid of "vendor" completely  and call it supplier everywhere.

## Environment
- **Version**: 12

**Comment by eldy** [comment]
You speak about "supplierorders". Are you speaking about the string into the URL endpoint of API ?

**Comment by dpriskorn** [comment]
The endpoint.
