### ISSUE TITLE
Select lines on invoice creation form doesn't work

### ISSUE THREAD

**Issue by atm-thibaultf** [Dolibarr/dolibarr#14807]
## Bug
When you create an invoice from an element (supplier order for example), the form page allows you to select the lines you want to have in your invoice from the order. All the lines are added to the invoice whatever the lines you have selected.

## Environment
- **Version**: Dolibarr v11+
- **OS**: Linux Ubuntu
- **Web server**: Apache
- **PHP**: 7.2
- **Database**: MariaDB

## Expected and actual behavior
When you create an invoice from an element (supplier order for example), the form page allows you to select the lines you want to have in your invoice from the order. All the lines are added to the invoice whatever the lines you have selected.

Only the lines selected should be added to the invoice created.

## Steps to reproduce the behavior
- Create an invoice from an element containing several lines
- In the form page, select only one line
- All the lines appear in the invoice created

**Comment by atm-thibaultf** [comment]
This bug is still present when an invoice is created from a supplier order. It works well for an invoice created from a proposal or a client order.

**Comment by atm-maxime** [comment]
Fixed by #18776 ?
