### ISSUE TITLE
Add product or service to BOM list 

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#14819]
When adding a new item to a BOM list the entry is not immediately visible in the list but on the next insert of a product or service the last product is visible. All items are in the database but the top item is not visible. A complete reload of the page result in visibility of all items. This behaviour is present in 12.0.1 and 12.0.2.

**Comment by erikvanberkum** [comment]
this issue was already reported in 31st of July.
[issues: 14326](https://github.com/Dolibarr/dolibarr/issues/14326)
