### ISSUE TITLE
Vacation days are consumed when reporting Sick Leave

### ISSUE THREAD

**Issue by Chudlight** [Dolibarr/dolibarr#14816]
# Feature Request
Option to set number of vacation days consumed per reported sick day to 0. In Germany, taking a sick day does not affect one's available vacation days. Currently, when filing a sick leave, we must then add the number of days back to the vacation total

## Suggested implementation
Allow the administrator to check a box in the module "Holiday" that sets the number of consumed vacation days per taken sick leave to zero.

**Comment by elsp1991** [comment]
Hello Chudlight Go to Setup->dictionaries->Type of leaves 
and under the SICK_LEAVE make the parameter "manage a counter" 1 this will allow to have different balance for the type SICK_LEAVE

**Comment by cfoellmann** [comment]
@Chudlight I am not sure that your dolibarr is working correctly.
Can you check again?
When you go to "Stammdaten - Urlaubsarten" and set "LEAVE_SICK" > "Zähler verwenden!" = 0 it should work like it should. We (in Germany) use this setting and when users send in their sick leaves it does NOT count against your vacation days.

**Comment by cfoellmann** [comment]
@Chudlight if it is working for you now please close this issue!
Also I would be interested how you handle the monthly addition of days. We deactivate and will add new days manually in January
