### ISSUE TITLE
PMP erroné - weighted average price error - Multicompany

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#14826]
# Instructions
Contrôle du calcul du PMP

# Bug
Le PMP est reporté sur la fiche du produit sans tenir compte de la provenance du mouvement de stock qui peut avoir au moins 2 origines différentes : 
-Multicompany avec les stocks appartenant à chaque company
-Multi-entrepot s'il y sont partagés dans le mode multicompany

## Environment
NA

## Expected and actual behavior
Avoir un calcul du pmp détaillé, 2 options seraient possibles
-PMP par Company
-PMP par Entrepot
Dans la fiche du produit il faudrait distinguer les PMP
Pouvoir relancer le calcul du PMP

## Steps to reproduce the behavior
Installation du module multicompany
Création de 2 sociétés
Création d'un produit partagé
Achat du produit à 2 prix différents (1 par société)
Réception sur 2 entrepôts (1 par société)
Les PMP devrait être différent alors qu'il sera calculé en global.

**Comment by ibuiv** [comment]
Je viens de découvrir ce souci qui est rédhibitoire dans mon projet en cours de construction. (Impossibilité d'avoir une valeur de stock à l'instant T pour une entité donnée)

J'ai envie de dire simple si chaque entrepôt n'est rempli QUE par une entité.

Par contre je ne crois pas qu'il soit possible de gérer simplement le cas où plusieurs entités nourrissent le même entrepôt ... 
Il faudrait séparer les lignes de stocks avec un champ **EntityOwner** et ça change grandement la logique de la table **llx_product_stock**

*Maintenant, comme c'est spécifique au multicompany, est-ce que cette issue a sa place ici ? ou ne devrait elle pas être donné au concepteur du multicompany*
*Et où placer le code qui adapte tout ça ... (dolibarr core, multicompany ou module à part) ?*
