### ISSUE TITLE
Multicompany & Dolibarr 12: "Dolibarr setup is not yet complete.  Click here to finish Dolibarr install process"

### ISSUE THREAD

**Issue by Trillo7** [Dolibarr/dolibarr#14830]
# Bug

Multicompany wont work with my Dolibarr installation. Tried even a clean installation and same issue. Dolibarr works fine but it doesnt even load multicompany CSS; Dolibarr setup is not yet complete, and when I go to the module's multicompany settings same error.

## Environment
- **Version**: 12.0.2, 12.0.3
- **OS**: CloudLinux 7
- **Web server**: Apache 2.4
- **PHP**: 7.4.10
- **Database**: MariaDB 10.2.33
- **URL(s)**: 

- https://*mydomain*.com/dolibarr_pr/custom/multicompany/css/multicompany.css.php?lang=es_ES&theme=eldy&userid=2&entity=1&layout=classic&version=12.0.3&revision=2

- https://*mydomain*.com/dolibarr_pr/custom/multicompany/admin/multicompany.php?save_lastsearch_values=1&backtopage=%2Fdolibarr_pr%2Fadmin%2Fmodules.php%3Fsearch_nature%3D%26search_version%3D%26search_status%3D

## Expected and actual behavior
Install multicompany and working fine

## Steps to reproduce the behavior
- Install multicompany
- Enable it
- You can already see messed up header because multicompany CSS cant load properly.
- Can't load multicompany settings

## [Attached files](https://help.github.com/articles/issue-attachments) 

[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/5281645/dolibarr.log)
![MCbug1](https://user-images.githubusercontent.com/42157810/94247921-0f5bd600-ff1e-11ea-961c-d3c7b0ccc91c.png)
![MCbug2](https://user-images.githubusercontent.com/42157810/94247926-0ff46c80-ff1e-11ea-9c45-8e1e52bc0659.png)
![MCbug3](https://user-images.githubusercontent.com/42157810/94249366-1ab00100-ff20-11ea-9571-b1e35714c65d.png)

Comments:
It works fine on another domain on SAME SERVER and on my localhost, but I get this issue with this domain, I tried lots of clean reinstallations, clones, security copies

**Comment by atm-quentin** [comment]
Hello, 

Which version of multicompany are you using ?

**Comment by hregis** [comment]
@Trillo7  
check if you use Multicompany 12 with Dolibarr 12
Multicompany is an external module, contact me directly please
