### ISSUE TITLE
BUG : No uptodate or outofdate filter in member list select search filter

### ISSUE THREAD

**Issue by daraelmin** [Dolibarr/dolibarr#14835]
# Bug No uptodate or outofdate filter in member list select search filter

## Environment
- **Version**: All (at least 12.0.3 ans develop)
- **URL(s)**: htdocs/adherents/list.php?leftmenu=members
- **URL(s)**: htdocs/adherents/list.php?leftmenu=members&statut=1&filter=outofdate

## Expected and actual behavior
When clicking on the outofdate membre list on left menu the status wich appears in the sélect form is validate. It should be out of date.
Same thing whith up to date 
## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files]((Screenshots)
[*Files*]
![outofdatememberlist](https://user-images.githubusercontent.com/8067223/94349283-54c5f380-0043-11eb-8dfa-a81f75e3826e.png)

**Comment by eldy** [comment]
I think trouble comes more from the label and the fact we try to manage 2 different things (the status of member: draft, validated, terminated) and the status of the subscription (not done, done and up-to-date, done but out-of-date). To make things cleaner I pushed a different fix so we can filter on both things differently.

**Comment by daraelmin** [comment]
I wonder if, in fact, the problem does not come from the confusion adherent (member) - adhesion (subscription).

The underlying problem is linked to the question of membership: can you be a member without subscribing, can you subscribe to several types of membership, etc.

if there were a dedicated subscription search form and a dedicated statistics page, the question would probably arise with less stake.

**Comment by daraelmin** [comment]
First of all : The solution provided solves my problem. Thank you !

But, I think we should really separate adherent search (and stats) from subscription search (and stats). Although your solution is much better than the actual way. It doesn't seems logical to the final user. 

I know that we are comparing apple and peer (don't know if we can say that in English) when checking the status of the member and the status of the subscription but for the final user the "status" should be the one that appear in the column. Which is not the case with your way of filtering. 

That said, moreover, the search criterion on the end date should be activated, cause it could be interesting for listing subscriber (ok, let say adherent). I mean, it could be useful to search for the one who will be out of date the next month or which member has not subscribe for the last 5 years. So maybe the search criteria for end date should be the ending date

Anyway, as I've said,the problem that I'm facing in my association is fixed. 

*For the final user, it will not be logical:*
![New_Search_Filter](https://user-images.githubusercontent.com/8067223/94375892-13067d00-0117-11eb-9206-ccc9be558366.png)
