### ISSUE TITLE
product label update after migration v4 to v11

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#14833]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When updating a product, the label is empty because Getpost function do nomore allow labels with this sign. But this is the sign for inches and for many products its an important data in label.

A user has products with the unit sign " example **Samsung Galaxy Tab A 2019 10.1"** 

In GETPOST function there is this commentary
// '"' is dangerous because param in url can close the href= or src= and add javascript functions.
// '../' is dangerous because it allows dir transversals

## Environment
- **Version**: 11
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: 7
- **Database**:mariadb
- **URL(s)**: product/card.php

## Expected and actual behavior
I think this is not a good evolution, because of limitation in the use of Dolibarr

## Steps to reproduce the behavior
create a product with " in label and try to update it

**Comment by eldy** [comment]
The symbol for inches should be double prime. But we often use the symbol double quotes instead (because double quotes is on keyboard). Currently allowing the double quotes allows also to hack Dolibarr.
A workaround for the moment is to use the simple quotes twice. 
An automatic conversion may be introduced.
