### ISSUE TITLE
12.02 problem of user rights

### ISSUE THREAD

**Issue by audace159** [Dolibarr/dolibarr#14834]
hello, 
I get this bug after updating from 11.03 to 12.02. An administrator does not encounter the problem.  Only on a user who has only some rights in read-only. The read-only user only gets pages with menus but without any results. On the invoice list, there is no invoice. We also get this bug: 

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20200925185317
Dolibarr: 12.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.1.33
Server: Apache
OS: Linux Audacieuse-Galerie 4.9.124-paas-2270098 #1 SMP PREEMPT Tue Aug 28 15:11:59 CEST 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

Url sollicitée: /fourn/facture/list.php?leftmenu=suppliers_bills
Referer: http://compta.audacieuse-galerie.ch/compta/facture/list.php?leftmenu=customers_bills
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, accounting, agenda, barcode, cron, commande, don, ecm, expensereport, facture, fournisseur, holiday, opensurvey, printing, resource, salaries, societe, hrm, service, takepos, variants, notification, banque, tax, documentgeneration, label, receiptprinter, expedition, cyberoffice, contrat, ficheinter, supplier_proposal, workflow, loan, prelevement, margin, adherent, propal, stock, projet, dynamicprices, reception, fckeditor, webservices, mailing, bookmark, import, export, cashdesk, categorie, product, skype, multicurrency, ticket
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT f.rowid as facid, f.ref, f.ref_supplier, f.type, f.datef, f.date_lim_reglement as datelimite, f.fk_mode_reglement, f.total_ht, f.total_ttc, f.total_tva as total_vat, f.paye as paye, f.fk_statut as fk_statut, f.libelle as label, f.datec as date_creation, f.tms as date_update, f.localtax1 as total_localtax1, f.localtax2 as total_localtax2, f.fk_multicurrency, f.multicurrency_code, f.multicurrency_tx, f.multicurrency_total_ht, f.multicurrency_total_tva as multicurrency_total_vat, f.multicurrency_total_ttc, f.note_public, f.note_private, f.fk_user_author, s.rowid as socid, s.nom as name, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta as code_compta_client, s.code_compta_fournisseur, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, country.code as country_code, p.rowid as project_id, p.ref as project_ref, p.title as project_label, u.login, SUM(pf.amount) as dynamount_payed FROM llx_societe as s LEFT JOIN llx_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN llx_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN llx_c_departements as state on (state.rowid = s.fk_departement), llx_facture_fourn as f LEFT JOIN llx_paiementfourn_facturefourn as pf ON pf.fk_facturefourn = f.rowid LEFT JOIN llx_projet as p ON p.rowid = f.fk_projet, llx_societe_commerciaux as sc LEFT JOIN llx_user AS u ON f.fk_user_author = u.rowid WHERE f.fk_soc = s.rowid AND f.entity IN (1) AND s.rowid = sc.fk_soc AND sc.fk_user = 8 GROUP BY f.rowid, f.ref, f.ref_supplier, f.type, f.datef, f.date_lim_reglement, f.fk_mode_reglement, f.total_ht, f.total_ttc, f.total_tva, f.paye, f.fk_statut, f.libelle, f.datec, f.tms, f.localtax1, f.localtax2, f.note_public, f.note_private, s.rowid, s.nom, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta, s.code_compta_fournisseur, typent.code, state.code_departement, state.nom, country.code, p.rowid, p.ref, p.title, u.login ORDER BY f.datef DESC, f.rowid LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.fk_user_author' in 'on clause'

Best regards

**Comment by audace159** [comment]
Hello 
And i mount in 12.03... idem. 

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20200926144841
Dolibarr: 12.0.3 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.1.33
Server: Apache
OS: Linux Audacieuse-Galerie 4.9.124-paas-2270098 #1 SMP PREEMPT Tue Aug 28 15:11:59 CEST 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

Url sollicitée: /fourn/facture/list.php?leftmenu=suppliers_bills
Referer: http://compta.audacieuse-galerie.ch/compta/facture/list.php?leftmenu=customers_bills_notpaid&search_status=1
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, hrm, notification, accounting, agenda, barcode, cron, commande, don, ecm, expensereport, facture, fournisseur, holiday, opensurvey, printing, banque, resource, tax, salaries, societe, documentgeneration, service, label, receiptprinter, takepos, variants, expedition, cyberoffice, contrat, ficheinter, supplier_proposal, workflow, loan, prelevement, margin, adherent, propal, stock, projet, dynamicprices, reception, fckeditor, webservices, mailing, bookmark, import, export, cashdesk, categorie, product, skype, multicurrency, ticket
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT f.rowid as facid, f.ref, f.ref_supplier, f.type, f.datef, f.date_lim_reglement as datelimite, f.fk_mode_reglement, f.total_ht, f.total_ttc, f.total_tva as total_vat, f.paye as paye, f.fk_statut as fk_statut, f.libelle as label, f.datec as date_creation, f.tms as date_update, f.localtax1 as total_localtax1, f.localtax2 as total_localtax2, f.fk_multicurrency, f.multicurrency_code, f.multicurrency_tx, f.multicurrency_total_ht, f.multicurrency_total_tva as multicurrency_total_vat, f.multicurrency_total_ttc, f.note_public, f.note_private, f.fk_user_author, s.rowid as socid, s.nom as name, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta as code_compta_client, s.code_compta_fournisseur, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, country.code as country_code, p.rowid as project_id, p.ref as project_ref, p.title as project_label, u.login, SUM(pf.amount) as dynamount_payed FROM llx_societe as s LEFT JOIN llx_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN llx_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN llx_c_departements as state on (state.rowid = s.fk_departement), llx_facture_fourn as f LEFT JOIN llx_paiementfourn_facturefourn as pf ON pf.fk_facturefourn = f.rowid LEFT JOIN llx_projet as p ON p.rowid = f.fk_projet, llx_societe_commerciaux as sc LEFT JOIN llx_user AS u ON f.fk_user_author = u.rowid WHERE f.fk_soc = s.rowid AND f.entity IN (1) AND s.rowid = sc.fk_soc AND sc.fk_user = 8 GROUP BY f.rowid, f.ref, f.ref_supplier, f.type, f.datef, f.date_lim_reglement, f.fk_mode_reglement, f.total_ht, f.total_ttc, f.total_tva, f.paye, f.fk_statut, f.libelle, f.datec, f.tms, f.localtax1, f.localtax2, f.note_public, f.note_private, s.rowid, s.nom, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta, s.code_compta_fournisseur, typent.code, state.code_departement, state.nom, country.code, p.rowid, p.ref, p.title, u.login ORDER BY f.datef DESC, f.rowid LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.fk_user_author' in 'on clause'

**Comment by daraelmin** [comment]
Hi,

Not sure if both problem have the same origin, but the SELECT SQL is wrong cause "llx_facture_fourn" and "llx_societe_commerciaux" should be JOIN formally (not with a comma) in a multiples left joint SQL query.

I could propose something, but as I have no example of these situations in my base, i can not reproduce the problem (and the fix)

Would you upload the file and test ?

**Comment by audace159** [comment]
Hello
thank you for your reply. which file do you want me to upload? 
best regards

**Comment by daraelmin** [comment]
Rename the actual file `/fourn/facture/list.php` like `/fourn/facture/list.php.bak`
Then up download unzip and upload this new version in /fourn/facture/
Hope it is better. If not remove the file and rename your old backup file.

**Comment by audace159** [comment]
Hello i test today after upload list.php in compta/facture .... it's idem

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20200929160355
Dolibarr: 12.0.3 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.1.33
Server: Apache
OS: Linux Audacieuse-Galerie 4.9.124-paas-2270098 #1 SMP PREEMPT Tue Aug 28 15:11:59 CEST 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

Url sollicitée: /fourn/facture/list.php?leftmenu=suppliers_bills
Referer: http://compta.audacieuse-galerie.ch/compta/index.php?mainmenu=billing&leftmenu=
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, hrm, notification, accounting, agenda, barcode, cron, commande, don, ecm, expensereport, facture, fournisseur, holiday, opensurvey, printing, banque, resource, tax, salaries, societe, documentgeneration, service, label, receiptprinter, takepos, variants, expedition, cyberoffice, contrat, ficheinter, supplier_proposal, workflow, loan, prelevement, margin, adherent, propal, stock, projet, dynamicprices, reception, fckeditor, webservices, mailing, bookmark, import, export, cashdesk, categorie, product, skype, multicurrency, ticket
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT f.rowid as facid, f.ref, f.ref_supplier, f.type, f.datef, f.date_lim_reglement as datelimite, f.fk_mode_reglement, f.total_ht, f.total_ttc, f.total_tva as total_vat, f.paye as paye, f.fk_statut as fk_statut, f.libelle as label, f.datec as date_creation, f.tms as date_update, f.localtax1 as total_localtax1, f.localtax2 as total_localtax2, f.fk_multicurrency, f.multicurrency_code, f.multicurrency_tx, f.multicurrency_total_ht, f.multicurrency_total_tva as multicurrency_total_vat, f.multicurrency_total_ttc, f.note_public, f.note_private, f.fk_user_author, s.rowid as socid, s.nom as name, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta as code_compta_client, s.code_compta_fournisseur, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, country.code as country_code, p.rowid as project_id, p.ref as project_ref, p.title as project_label, u.login, SUM(pf.amount) as dynamount_payed FROM llx_societe as s LEFT JOIN llx_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN llx_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN llx_c_departements as state on (state.rowid = s.fk_departement), llx_facture_fourn as f LEFT JOIN llx_paiementfourn_facturefourn as pf ON pf.fk_facturefourn = f.rowid LEFT JOIN llx_projet as p ON p.rowid = f.fk_projet, llx_societe_commerciaux as sc LEFT JOIN llx_user AS u ON f.fk_user_author = u.rowid WHERE f.fk_soc = s.rowid AND f.entity IN (1) AND s.rowid = sc.fk_soc AND sc.fk_user = 8 GROUP BY f.rowid, f.ref, f.ref_supplier, f.type, f.datef, f.date_lim_reglement, f.fk_mode_reglement, f.total_ht, f.total_ttc, f.total_tva, f.paye, f.fk_statut, f.libelle, f.datec, f.tms, f.localtax1, f.localtax2, f.note_public, f.note_private, s.rowid, s.nom, s.email, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.code_compta, s.code_compta_fournisseur, typent.code, state.code_departement, state.nom, country.code, p.rowid, p.ref, p.title, u.login ORDER BY f.datef DESC, f.rowid LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'f.fk_user_author' in 'on clause'

**Comment by audace159** [comment]
sorrzy in  /fourn/facture/ ... its ok,  but it doesn't list any bill, while the user is reading it.
Best regards

**Comment by daraelmin** [comment]
OK so you dont have the SQL error anymore, that's better.
maybe you should participate in the discussion #14855 around how to solve your problem

**Comment by optistea** [comment]
Hi evreryone,

I have the same problem. I created a group with permissions to consult customer invoices, supplier invoices, consultation of the general ledger, ... and I associated an internal user with this group. When this user logs in no list appears ...

I don't understand why...

**Comment by daraelmin** [comment]
Max this fix : fdc2a88 solve the issue ?
