### ISSUE TITLE
Dolibarr needs to migrate on modern framework

### ISSUE THREAD

**Issue by MUzayr** [Dolibarr/dolibarr#14840]
Dolibarr needs to upgrade to any new modern php framework like symfony or laravel etc which will make it to survive, prosper etc  in the current times...

**Comment by atm-maxime** [comment]
A little search and you would have found #10054.
Your contributions are welcome.

**Comment by MUzayr** [comment]
o this point was already raised... Yeah of course im preparing to contribute......
