### ISSUE TITLE
FR: PDF report for salary

### ISSUE THREAD

**Issue by n15c** [Dolibarr/dolibarr#14851]
# Feature Request
Adding the functionality to generate a PDF out of a salary payment.
## Use case
In some countries it is necessary to send a document with the salary declaration every payment period (usually monthly).

## Suggested implementation
To make the paperwork easier it would be great if you would have the possibility to create a pdf out of the payment. Additionally it would be necessary to implement the functionality creating deductions. A possible ((structural) template is the following [template from the swiss government](https://www.seco.admin.ch/seco/de/home/Arbeit/Personenfreizugigkeit_Arbeitsbeziehungen/schwarzarbeit/Arbeit_korrekt_melden/Private_Arbeitgebende/Lohnbudget_Lohnabrechnung/Berechnungsvorlagen_Rechenbeispiel.html).

## Suggested steps
- Implement the functionality to add deductions to the salary
- Make a PDF model
- Implement the functionality to generate a PDF out of the payment

**Comment by evatechserve** [comment]
I am waiting for this update 😊
Please notify on Dolibarr form also. 
thank you.

**Comment by loay-mustafa** [comment]
i write feature do this 
you can see it from this :
[https://github.com/loay-mustafa/pdfsalary](url)
