### ISSUE TITLE
Dolibarr Module   ticket/list .php

### ISSUE THREAD

**Issue by alexsilvausa** [Dolibarr/dolibarr#14854]
if ($search['fk_statut'] == 'openall' || in_array('openall', $search['fk_statut'])) $tmpstatus .= ($tmpstatus ? ',' : '')."'".Ticket::STATUS_NOT_READ."', '".Ticket::STATUS_READ."', '".Ticket::STATUS_ASSIGNED."', '".Ticket::STATUS_IN_PROGRESS."', '".Ticket::STATUS_NEED_MORE_INFO."', '".Ticket::STATUS_WAITING."'";
	    if ($search['fk_statut'] == 'closeall' || in_array('closeall', $search['fk_statut'])) $tmpstatus .= ($tmpstatus ? ',' : '')."'".Ticket::STATUS_CLOSED."', '".Ticket::STATUS_CANCELED."'";
	    if ($tmpstatus) $sql .= " AND fk_statut IN (".$tmpstatus.")";
	    elseif (is_array($search[$key]) && count($search[$key])) $sql .= natural_search($key, join(',', $search[$key]), 2);
	    continue;
	}
	if ($key == 'fk_user_assign')
	{
	    if ($search[$key] > 0) $sql .= natural_search($key, $search[$key], 2);
	    continue;
	}
	$mode_search = (($object->isInt($object->fields[$key]) || $object->isFloat($object->fields[$key])) ? 1 : 0);
    if ($search[$key] != '') $sql .= natural_search($key, $search[$key], $mode_search);
}
if ($search_all) $sql .= natural_search(array_keys($fieldstosearchall), $search_all);
if ($search_societe)     $sql .= natural_search('s.nom', $search_societe);
if ($search_fk_project) $sql .= natural_search('fk_project', $search_fk_project, 2);
if (!$user->socid && ($mode == "mine" || (!$user->admin && $conf->global->TICKET_LIMIT_VIEW_ASSIGNED_ONLY))) {
    $sql .= " AND (t.fk_user_assign = ".$user->id;
    if (empty($conf->global->TICKET_LIMIT_VIEW_ASSIGNED_ONLY)) $sql .= " OR t.fk_user_create = ".$user->id;
    $sql .= ")";
}

**Comment by alexsilvausa** [comment]
Feature Request Im new on Dolibarr and programming I need a simple change to be made and I can't figure out how to make default a page list.php to show only tickets assign to me. I submit many tickets open to all others to be assign, but i need to every user to see a list for the only tickets that he is assigned to work on without use the filter, all ticket are being mixed with the one I submitted with the one im assigned to work on, I need se setup a link to see the list.php to show with all tickets that  user assigned tickets only without using the filter.

**Comment by eldy** [comment]
Enable the module "Bookmark".
Go on list of ticket, add the column "Assigned to" and filter on your user.
Then click on the start of bookmark and "Add to boorkmark". You will get an url and a direct link to the list of tickets assigned to you.
Change the id in url in parameter search_fk_user_assign for a list for another user.
You can replace this id with the keyword "__USER_ID__" so link wil be same for everybody and will be replaced by the user id of user that is connected.
For example: 
https://mydomain/dolibarr/htdocs/ticket/list.php?search_fk_user_assign=__USER_ID__
is link to list of ticket assign to connected user.
