### ISSUE TITLE
Hook system issue

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#14859]
The hook system is pretty complex and not documented very well.

My issue is with this hook: https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/lib/functions.lib.php#L7450-L7460

As far as I understand the hook can only modify the `$object` and not the parameters.

My usecase is to remove a TAB if a project has a certain property.
Problem with the hook: $object is the project without access to the $head. That way I can not modify the tabs.

If no one can tell me I am wrong with this I will think about modifying the `completeTabsHead` hook to allow $head manipulation

**Comment by eldy** [comment]
Yes paramater $parameter is passed by value so you changing value in the hook will not change it into the calling function.
You can try to use inside your hook:
global $head; And then editing it.
check if it change in the calling function. Not sure it works.

To remove a tab on a condition you can use the 
->tabs array into the module descriptor
$this->tabs[] = array('data'=>'objecttype:-tabname:NU:conditiontoremove');
