### ISSUE TITLE
Extrafield  Propale  --> Invoice

### ISSUE THREAD

**Issue by idromel** [Dolibarr/dolibarr#14857]
Hello,
I created:
an extrafield (string 1 line) in the propal header and the same in the invoice header.
an extrafield (Selection list) in the propal header and the same in the invoice header. The lists are identical.
an extrafield (string n lines) in the propal header and the same in the invoice header.
When I create the propal I complete the extrafields and after validation I create the invoice.
The extrafield (string 1 line) has been transferred to the invoice.
The extrafield (Picklist) was not transferred to the invoice.
The extrafield (string n lines) has not been transferred to the invoice.

Tests carried out on several environments.
Thanks for your help.

Bonjour,
J’ai créé:
un extrafield (string 1 line) dans l’entête propale et le même dans l’entête facture.
un extrafield (Liste de sélection) dans l’entête propale et le même dans l’entête facture. Les listes sont identiques.
un extrafield (string n lines) dans l’entête propale et le même dans l’entête facture.
Quand je crée la propale je complète les extrafields et après validation je crée la facture. 
L’extrafield (string 1 line) a été transféré dans la facture.
L’extrafield ( Liste de sélection)n’a pas été transféré dans la facture.
L’extrafield (string n lines) n’a pas été transféré dans la facture.
 
Test réalisés sur plusieurs environnements.
Merci pour aide. 

## Environment
- **Version**: 12.0.1  à 12.0.3
- **OS**: Linux Ubuntu 18.04  et Windows 10
- **PHP**: 7.3.22
- **Database**: Mysql 5.7

**Comment by idromel** [comment]
Hello,
I confirm that there is a bug concerning the extrafields 'selection list' or 'string n lines'.
I took an 11.0.5 test environment for which I created an extrafield 'picklist and an extrafield' string n lines' in the propal and invoice header. Everything works well and the attributes are transferred to the invoice from the propal when creating an invoice (from the propal).
I switched the environment to 12.0.3 and there if I create an invoice from a propal, the attributes of type 'picklist' and 'string n lines' do not pass in the invoice. Only the type 'string 1 line' (which formerly corresponds to string) works.
Thanks for your help.

Bonjour,
Je confirme qu’il y a bien un bug concernant les extrafields ‹ liste de sélection › ou ‹ string n lines ›.
J’ai pris un environnement test 11.0.5 pour lequel j’ai créé un extrafield 'liste de sélection et un extrafield ‹ string n lines › dans l’entête propale et facture. Tout fonctionne bien et les attributs sont bien transférés dans la facture depuis la propale en cas de création de facture (depuis la propale).
J’ai passé l’environnement en 12.0.3 et là si je crée une facture à partir d’une propale, les attributs de type ‹ liste de sélection › et ‹ string n lines › ne passent pas dans la facture. Seul le type 'string 1 line ’ (qui correspond anciennement à chaîne) fonctionne.

**Comment by atm-lena** [comment]
Hello,

Thanks for reporting, i'll have a look.
