### ISSUE TITLE
Quotation Customer PDF viewer Blank

### ISSUE THREAD

**Issue by jordisorts** [Dolibarr/dolibarr#14869]
Hello,

After update to 12.0.3 when I try to see a preview of pdf quotation I see a blank page:

![image](https://user-images.githubusercontent.com/1792732/94674345-53811900-0318-11eb-822d-a47654620414.png)

![image](https://user-images.githubusercontent.com/1792732/94674383-5e3bae00-0318-11eb-93a4-7c1f422f5e1f.png)

Anybody have this issue ? I try with two themes Azur and Cyan and both has the same problem, and when I try to download the pdf I get an error 500.

If I send the pdf via email, there aren't a problem, the pdf is correct attached in email.

**Comment by jordisorts** [comment]
Searching in a console debug, I found this error:

![image](https://user-images.githubusercontent.com/1792732/94674980-4a447c00-0319-11eb-87b8-6d7dca12a10d.png)

**Comment by eldy** [comment]
If you have an error 500 when downloading file, you should get an error in the file error.log of your apache web server. Do you have access to this file ?

**Comment by jordisorts** [comment]
> If you have an error 500 when downloading file, you should get an error in the file error.log of your apache web server. Do you have access to this file ?

Yes,

Here you have:

[Thu Oct 08 16:05:05.061602 2020] [proxy_fcgi:error] [pid 26061:tid 139701633758976] [client 79.153.149.49:54334] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dolIsAllowedForPreview() in /var/www/vhosts/portal/document.php:166\nStack trace:\n#0 {main}\n  thrown in /var/www/vhosts/portal/document.php on line 166', referer: https://xxxx.com/commande/card.php?id=12&save_lastsearch_values=1
