### ISSUE TITLE
category filter not possible on projet/list.php

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#14861]
# Bug
On `projet/list.php` the multiselect box shows the project categories but selecting and applying the filter returns to the list without a filter for the categories.

## Environment
- **Version**: develop

**Comment by atm-maxime** [comment]
Hi. I just tried on the latest develop branch and it works fine for me. Can you check again ?

**Comment by cfoellmann** [comment]
thanks for the reply. I did update my develop install and it seems to work for me now, too.
