### ISSUE TITLE
ValidationDateNotDefinedEvenIfShipmentValidated is not in translation catalog

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#14884]
# Bug
From htdocs/expedition/stats/index.php

## Environment
- **Version**: 11.0

## Expected and actual behavior
see https://www.dolibarr.fr/forum/t/traduction-manquante-dans-les-statistiques-dexpedition/34348

## Steps to reproduce the behavior
[*Verbose description*]

**Comment by eldy** [comment]
It seems you have data into one column that is corrupted.
Try to run this on your database

update llx_expedition set date_valid = date_creation where fk_statut = 1 and date_valid IS NULL;
update llx_expedition set date_valid = NOW() where fk_statut = 1 and date_valid IS NULL;

Does it solve trouble ?
