### ISSUE TITLE
Extrafields missing in hook printObjectLine

### ISSUE THREAD

**Issue by zedzedtop** [Dolibarr/dolibarr#14883]
# Bug
Extrafields missing in hook printObjectLine  parameters. Since version 11 parameter 'extrafieldsline' missing.
- **File**: dolibarr/htdocs/core/class/commonobject.class.php
- ** Function**: printObjectLines

# Code version 10.5 Line 3990
`$parameters = array('line'=>$line,'var'=>$var,'num'=>$num,'i'=>$i,'dateSelector'=>$dateSelector,'seller'=>$seller,'buyer'=>$buyer,'selected'=>$selected, 'extrafieldsline'=>$extrafieldsline);`

# Code version 11.0 Line 4161
`$parameters = array('line'=>$line, 'num'=>$num, 'i'=>$i, 'dateSelector'=>$dateSelector, 'seller'=>$seller, 'buyer'=>$buyer, 'selected'=>$selected, 'table_element_line'=>$line->table_element);
					`
 
## Environment
- **Version**: 11 12
- **OS**: Debian Stretch
- **Web server**: Apache 2
- **PHP**: PHP 7
- **Database**: Postgresql

**Comment by eldy** [comment]
You should get a value of a key into table_element_line
Then into 
$extrafields[ table_lement_line ]    (with $extrafields is a global variable)
you should find the array with $extrafields of lines.

**Comment by zedzedtop** [comment]
It works if I use the global variable $ extrafields but I don't find it logical, it seemed to me that I should avoid global variables as much as possible.
The printObjectLine function has an Extrafields parameter, I should find it in the list of parameters received by my "hook" to be able to directly call the original function.

Cela fonctionne si j'utilise la variable globale $extrafields mais je ne trouve pas ça logique, il me semblait qu'il fallait éviter les variables globales au maximum.
La fonction printObjectLine a un paramètre Extrafields, je devrais le retrouver dans la liste des paramètres reçus par mon "hook" pour pouvoir appeler directement la fonction d'origine.

**Comment by eldy** [comment]
"I should avoid global variables as much as possible."
Yes for local need (so most needs).
For global need, global variables are very usefull. And there is 6 global needs in Dolibarr (variables we need to have them loaded everywhere) :
$conf, $langs, $db, $user, $extrafields, $hookmanager

**Comment by zedzedtop** [comment]
Thank you for your explanations
