### ISSUE TITLE
No Type3 tax (called "IRPF" in Spain) added to supplier invoice

### ISSUE THREAD

**Issue by joanahead** [Dolibarr/dolibarr#14896]
Dolibarr 12.0.2 used in spanish configuration.

We've got a VAT tax (21% in Spain) that also contains in its dictionary definition the Type3 tax (-19% in Spain).
Then, the supplier has got "Sujeto a IRPF - Yes" so it should apply not only the +21% VAT tax but also the -19% IRPF tax.

Although that, when we create a supplier invoice for this supplier VAT (+21%) is added calculated to the invoice but the IRPF tax (-19%) is not applied.

It used to work in Dolibarr 8 and 9. We updated recently to 12.0.2

Feel free to ask for any further information.

**Comment by eldy** [comment]
Can you make this test:
Go on home - setup - my company. Set the status "Enable third tax" to yes.
Then build a supplier invoice. Do yo see the type3 tax added ?

**Comment by joanahead** [comment]
Hi,
indeed it worked. The supplier invoice has type3 tax added, while the client invoice remains without type3 tax.
Has this changed lately? I'm sure this configuration has always been set to "Enable third tax - No" in my Dolibarr instance.
Thanks anyway.
