### ISSUE TITLE
DB_ERROR_NOSUCHFIELD

### ISSUE THREAD

**Issue by davidkiner** [Dolibarr/dolibarr#14899]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*rename model facture*]

## Environment
- **Version**: 12.0.3
- **OS**: Linux  4.14.154-ovh-vps-grsec-zfs-classid 
- **Web server**: Apache
- **PHP**: 7.3.20
- **Database**: MYSQL v.5.6
- **URL(s)**: /dolibarr/htdocs/compta/facture/card-rec.php

## Expected and actual behavior
i try to rename an invoice template

## Steps to reproduce the behavior
each time i try to rename an invoice template

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![bug dolibarr](https://user-images.githubusercontent.com/72263402/94930976-7867be80-04c7-11eb-8578-71054b768b20.JPG)

**Comment by eldy** [comment]
Seems to be fixed with fcbc48fa287d80a51c041ed9e8298186e42d0bda
