### ISSUE TITLE
Accountancy - Link between account and the expense reports

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#14948]
On this page:
[host]/accountancy/expensereport/list.php?search_year=2020

When you have an old accountancy module enabled (with duplicated accounts- apparently there was a migration script issue); the expense report is displayed twice.

Because you have two accounts related for the same fee ...

<img width="1635" alt="Screenshot 2020-10-06 at 20 57 49" src="https://user-images.githubusercontent.com/3658458/95247905-c9085000-0816-11eb-9e5e-c67d33bcb672.png">

**Comment by laudeco** [comment]
I didn't say it is in version 12.0.3 and earlier

**Comment by eldy** [comment]
Did you identify where you have the duplicate ?
Do you have an exemple of duplicated record ?

**Comment by laudeco** [comment]
Cf the discussion in the PR #14949 

Cheers
L.
