### ISSUE TITLE
Bug: Module translation not passed to mail form

### ISSUE THREAD

**Issue by Tim-Otte** [Dolibarr/dolibarr#14943]
# Bug
When using the "send email" method in a custom module the file `html.formmail.class.php` creates a translatable variabe called `PredefinedMailContentModulename` and inserts it into the mail body in the form. The developer of the module has no option to set this translation variable to a custom value because the module language file will not be loaded or passed to the mail form.

**Comment by atm-quentin** [comment]
Hello,
Which dolibarr version are you using ?
