### ISSUE TITLE
Cannot modify the date of a credit note

### ISSUE THREAD

**Issue by ndieschburg** [Dolibarr/dolibarr#14956]
When I create a credit note, there is no way to modify its date even if it is a draft. 

When I look into the code (compta/facture/card.php), I see : 

<pre>
if ($object->type != Facture::TYPE_CREDIT_NOTE && $action != 'editinvoicedate' && ! empty($object->brouillon) && $usercancreate && empty($conf->global->FAC_FORCE_DATE_VALIDATION))
		print '<td class="right"><a href="' . $_SERVER["PHP_SELF"] . '?action=editinvoicedate&amp;facid=' . $object->id . '">' . img_edit($langs->trans('SetDate'), 1) . '</a></td>';
</pre>

Is there a reason for such a thing? Is it dangerous to remove the check on CREDI_NOTE?

Thank you in advance for you response. 

Best regards. 

Noel Dieschburg.

**Comment by aspangaro** [comment]
I don't see any problem in allowing the issue date to be printed on a credit note invoice. I proposed the fix
