### ISSUE TITLE
Ampersand in Customer Name causes a broken ODT file

### ISSUE THREAD

**Issue by usigit** [Dolibarr/dolibarr#14957]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Ampersand in the customer name causes a broken odt file to be created when odt templates are used.
It leads to an error message : Read error in document part content.xml at 2,332199 (line,column) detected in the file

## Environment
- **Version**: 12.02
- **OS**: Debian 10.6
- **Web server**: 2.4.38-3+deb10u4
- **PHP**: 7.3.19-1~deb10u1
- **Database**: Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- **URL(s)**: /dolibarr/comm/propal/card.php?id=14#builddoc

## Expected and actual behavior
odt document without errors

## Steps to reproduce the behavior
Set up a customer with a & in the name.
Create an proposal or an invoice and generate the output with an odt template

**Comment by code-chicken** [comment]
Hi,

I can confirm this bug.

The following patch should help for release 12.0.3:

```
--- htdocs/includes/odtphp/odf.php	(date 1602230783416)
+++ htdocs/includes/odtphp/odf.php	(date 1602230783416)
@@ -141,6 +141,7 @@
 			//}
 		}
 
+        $value = $encode ? htmlspecialchars($value) : $value;
 		$value = ($charset == 'ISO-8859') ? utf8_encode($value) : $value;
 
 		// Check if the value includes html tags
```

**Comment by usigit** [comment]
Thank you very much,

It works!
