### ISSUE TITLE
Granular Permissions for Setups and Admin Section

### ISSUE THREAD

**Issue by LOTRg** [Dolibarr/dolibarr#14968]
## Feature Request
Can we implement a permissions system for the Admin section like Company Setup, Admin Tools and other sections available only for the superadmin?

## Use case
The granular permissions system for Admin section allows for delegation of roles to other employees, for example allow certain user to do DB backups without having access to all other company setups and information or auditing actions. Another Example would be, Allow a translator to translate the interface without having access to other sections of the Admin. Allowing An Account to access a certain module (invoices and Banks) but not access Products or Stocks or HRM Module .
This sort of granular permission specially in the admin area would help facilitate delegating responsibilities to teams and users based on their expertise without jeopardizing system setup mistakenly or by malicious actions.

## Suggested implementation
I suggest either extend the current permissions system to the Super Admin only where control of access can be maintained for Admin functionalities or perhaps a completely separate module dedicated for Admin section permissions.

Would this be possible ? or can we put it on our roadmap ?

**Comment by DATUC** [comment]
This wil be verry usefull i also have the sme needs to restrict wath admin A, B or C can do like configuration is realy important
