### ISSUE TITLE
ODT generation not working when validating invoice

### ISSUE THREAD

**Issue by michel-thomas** [Dolibarr/dolibarr#14979]
# Bug
I designed an ODT template for invoices. When an invoice is validated, it generates automatically the ODT file.
Since upgrade to 12.0.3 from 11.0.1, some of the fields (`{company_name}`, `{company_address}`, `{company_zip}` and `{company_town}`) are not completed inside generated ODT __when validating invoice__.
But if I click "Generate" after that, these fields are filled. I haven't modify anything in invoice, neither in ODT template.

## Environment
- **Version**: 12.0.3
- **OS**: Debian 10 Buster
- **Web server**: Apache 2.4
- **PHP**: 7.3
- **Database**: MariaDB 10.3
- **URL(s)**: https://my.site.fr/compta/facture/card.php?facid=1145#builddoc

## Expected and actual behavior
Following fields (`{company_name}`, `{company_address}`, `{company_zip}` and `{company_town}`) remains empty when invoice is validated. They should be filled with their value.
Workaround is to click on "Generate" after and new ODT file contains these values.
All other values are filled correctly.
These fields are inserted inside a square.

## Steps to reproduce the behavior
* Place odt template in doctemplates/invoice
* Create an invoice and validate it
* Open generated odt, some fields are empty
* Click on "Generate"
* Open new generated odt, fields are set

## Attached files
[Facture.odt.zip](https://github.com/Dolibarr/dolibarr/files/5356355/Facture.odt.zip)

**Comment by ksar-ksar** [comment]
A similar issue here : https://www.dolibarr.org/forum/t/error-when-creating-documents/19640

**Comment by code-chicken** [comment]
Hi all,

for the time being the attached patch might help. It is for release 12.0.3 but will probably also work for past releases since 12.0.0

[facture-14979.zip](https://github.com/Dolibarr/dolibarr/files/5404084/facture-14979.zip)

**Comment by michel-thomas** [comment]
@code-chicken It works well! Many thanks!
Will it be part of next release 12.0.4?
