### ISSUE TITLE
Create invoice screen does not pull default values used for that client (for Payment Terms, Type or Bank)

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Dolibarr/dolibarr#14985]
# Bug
Creating and invoice, after selecting the client (Thurd Party), the Payment Terms, Payment Type and Payment Bank entries are not updated with the details that client holds, they have to be filled manually

## Environment
- **Version**: 12.0.2, 12.0.3
- **OS**: Windows 7 Pro x64
- **Web server**: Apache 2.4
- **PHP**:  7.2.8
- **Database**: mySQL v8.0.12
- **URL(s)**: htdocs/compta/facture/card.php?action=create&leftmenu=

## Expected and actual behavior
When creating a new invoice, a client needs to be found, this client holds default values for Payment Terms, Payment Type and Payment Bank, these default values are not pulled in to the new created invoice screen and have to be manually entered, they should be pulled from the client once the client is selected when creating a new invoice.

## Steps to reproduce the behavior
Create a new invoice and select a client who has default values for Payment Terms, Payment Type and Payment Bank, the default values are not shown in the new created invoice

**Please see video link of the problem
https://www.griffcomm.dev/temp/dolibarr/2020-10-12_dolibarr_customer_payments.mp4**

**Comment by orebd** [comment]
Hello,
You need to add RELOAD_PAGE_ON_CUSTOMER_CHANGE = 1 into Setup => other Setup

Name | Value | Comment | Modif. date |  
-- | -- | -- | -- | --
RELOAD_PAGE_ON_CUSTOMER_CHANGE |  1 |   |   |

**Comment by orebd** [comment]
@eldy Maybe it make sense to set RELOAD_PAGE_ON_CUSTOMER_CHANGE = 1 by default into llx_const

**Comment by GRIFFCOMMca** [comment]
That has fixed this issue, thanks.  This should really be default as thats the whole reason for having this data in the client directly.
