### ISSUE TITLE
Adding a product or service to an invoice does not populate the description field

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Dolibarr/dolibarr#14998]
# Bug
Adding a product or service to an invoice, does not fill the description with the default value contained in that product or service item

## Environment
- **Version**: 12.0.2, 12.0.3
- **OS**: Windows 7 Pro x64
- **Web server**: Apache 2.4
- **PHP**:  7.2.8
- **Database**: mySQL v8.0.12
- **URL(s)**: https://erp.griffcomm.ca/htdocs/compta/facture/card.php?facid=38

## Expected and actual behavior
When adding product or service lines to an invoice, the product or service description does not populate on the invoice when adding the line, the price however does

## Steps to reproduce the behavior
Create a new draft invoice, then under "Add new line" select a "Predefined product/services to sell:, use one that has a description by default, the description of that product or service does not populate on the invoice field.

**Please see video link of the problem
https://www.griffcomm.dev/temp/dolibarr/2020-10-12_dolibarr_product_description.mp4**

**Comment by orebd** [comment]
Hello,

You can modify it into services or product module parameter
On the bottom of the page you can see:
"Display product descriptions in forms (otherwise shown in a tooltip popup)" you just have to set it to yes.
Then when you add a product or a service into an invoice, after clicking on ADD you'll see the description of your product/service.

**Comment by GRIFFCOMMca** [comment]
Hi, mine are set to YES in both of those modules, that setting didnt seem to effect anything

HOWEVEWR

We had YES = Add a feature to define the descriptions of products defined by the vendors in addition to descriptions for customers, we changed this to NO and i now see the descriptions.......

They only show up ONCE they are added, why would they not show up in the description once they are selected, is there a setting to change this so i see it BEFORE I add it so it can be edited (like the customer issue we saw, which was fixed with "RELOAD_PAGE_ON_CUSTOMER_CHANGE", this appears to be the same issue for the product description...

If we EDIT an added product we can then edit the description, however that adds 2 steps (Add it then edit it and re-save it)

**Comment by orebd** [comment]
Hello,
Sorry, i'm not able to do that

**Comment by GRIFFCOMMca** [comment]
> Hello,
> Sorry, i'm not able to do that

I'll submit it as a feature request later today...
