### ISSUE TITLE
The physical stock, shown, is not considering the Warehouse filter

### ISSUE THREAD

**Issue by cluza** [Dolibarr/dolibarr#15002]
# Bug
The physical stock, shown, is not considering the Warehouse filter

## Environment
- **Version**: 12
- **URL(s)**: product/stock/replenish.php

## Expected and actual behavior
The stock filter is selected and the following is displayed:
- the desired stock of the product per warehouse.
- and the total physical stock of the product.

The physical stock per warehouse must be shown, so that the correct quantity to order per warehouse can be calculated

## Steps to reproduce the behavior
1. Activate the desired Stock functionality of the couple (product-warehouse)
2 Create Product A
3. Create WareHouse 1 and WareHouse 2
4. Register Stock desired by warehouse
5. Register stock correction for Warehouse 1 and 2
6. check the physical stock in the replenishment form by warehouse

![stock_desired (product-warehouse)](https://user-images.githubusercontent.com/60309439/95809956-8a224080-0cd5-11eb-8b1e-9569ceb113ab.jpg)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
This has been fixed for v13
