### ISSUE TITLE
A security mecanism generates data loss

### ISSUE THREAD

**Issue by john-botella** [Dolibarr/dolibarr#15017]
replacing the param $check = 'none' by $check = 'alphanohtml'
https://github.com/Dolibarr/dolibarr/blob/02fcee5d94aaef9a63b2b7b3ae96d188142310dc/htdocs/core/lib/functions.lib.php#L306
Ok why not

but :

The quote is not html it's a real char...
https://github.com/Dolibarr/dolibarr/blob/02fcee5d94aaef9a63b2b7b3ae96d188142310dc/htdocs/core/lib/functions.lib.php#L662

if " is dangerous it's not because param in url can close the href= or src= and add javascript functions, it's because param in url like  href= or src= and javascript functions are not escaped.

if we use in a product label the char " for inch unit so we lose the information.
it's also true for all other kind of label or name...

see
https://github.com/Dolibarr/dolibarr/blob/02fcee5d94aaef9a63b2b7b3ae96d188142310dc/htdocs/product/card.php#L228
https://github.com/Dolibarr/dolibarr/blob/02fcee5d94aaef9a63b2b7b3ae96d188142310dc/htdocs/product/card.php#L401

**Comment by eldy** [comment]
It's true that problem of " is a problem of missing escapement. But for the moment, removing the sanitizing is more harmful than keeping it. A workaround for the moment to enter inch symbol " is to use 2 double quotes. We could add a replacement into GETPOST the same way to do it automatically (escapement everywhere to allow "  will take a long time).

**Comment by eldy** [comment]
See also #14833
