### ISSUE TITLE
Error for updating partner addresses with several lines

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#15029]
œ# Bug
If a partner address has several lines, the \n is lost in address field
ex : 
avenue des champs élysées
Bat 12
étage 3
is recorded as 
avenue des champs élysées Bat 12 étage 3

## Environment
- **Version**: 11 and 12
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
newlines are required for a correct printing on documents
they should not bee replaced with spaces
ocuured since getpost uses 'alphanohtml' instead of prevvious 'alpha'

**Comment by atm-maxime** [comment]
Has been fixed in v12 #14384
