### ISSUE TITLE
Extra fields intervention sheet, option Show in PDF does not work.

### ISSUE THREAD

**Issue by onlitec** [Dolibarr/dolibarr#15034]
When I create extra fields it doesn't matter which option I select the extra field is not displayed in the generated PDF.

Dolibarr version 10.0.3
![CAMPOS EXTRAS](https://user-images.githubusercontent.com/13083056/96156318-4dc62e80-0ee7-11eb-8c6f-16e4b63d4dd1.png)

**Comment by thegeettanna** [comment]
Dear @onlitec, 

Try using the "espadon" pdf template. 
It might work on that template. 

Let me know how it goes. Pretty sure this should help. 

![Screen Shot 2020-10-21 at 1 27 52 AM](https://user-images.githubusercontent.com/24646523/96637783-cccec300-133c-11eb-9ba7-191a75fb5b8f.jpg)
