### ISSUE TITLE
Closing a shipping on a customer order where there is already an invoice creates a new invoice duplicate invoice

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15039]
# Bug
we should not create duplicate invoices on orders if there is already an invoice on the order.

## Environment
- **Version**: 12.2

**Comment by thegeettanna** [comment]
Dear @egils-consulting, 

Maybe try this and it might help:
Go to workflows module.
Select the second option in Automatic Creation - "Automatically create a customer invoice.....",
And turn that option off. 

Screenshot attached for further expiation. 
Hope this helps. 

![Screen Shot 2020-10-21 at 1 22 44 AM](https://user-images.githubusercontent.com/24646523/96637533-6fd30d00-133c-11eb-941f-06b80fd81d40.jpg)

**Comment by dpriskorn** [comment]
Thanks! I did not know about that setting.

**Comment by atm-maxime** [comment]
Issue to close ?
