### ISSUE TITLE
Default order quantity

### ISSUE THREAD

**Issue by omogenot** [Dolibarr/dolibarr#15046]
Hi,

# Feature Request
[*Short description*]
When creating a supplier order, one can choose a product using a listbox that shows the various product prices depending on quantity for this supplier. When an option from this list box is chosen, it would be nice to set the ordered quantity to be at least the minimum value for this price (should the latter be less that the minimum).

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by futurehousestore** [comment]
/htdocs/product/fournisseurs.php?id=XXXX&action=add_price  (change XXXX to your product ID)
- Change Min. purchase quantity to your desire 
- Change Discount for this qty. to the specified value
- Fill in all the other necessary fields
- Check your PO for this product

**Comment by cfoellmann** [comment]
@futurehousestore
as @omogenot is suggesting the correct price should be used automatically when setting a quantity for the LINE.
If I understand you right what you are describing is only the way to set prices for certain quantities.

I am with @omogenot that the discount/price for amounts in the current state is not in any way usable in production.

**Comment by omogenot** [comment]
Problem/Feature has been solved as of current version I use: 14.0.4
