### ISSUE TITLE
Virtual product enhancement

### ISSUE THREAD

**Issue by Mx74** [Dolibarr/dolibarr#15044]
# Feature Request
Being able to dissociate the stock behavior for child product when buying or selling

## Use case
Virtual products are great for decreasing automatically the stock of products sold as a bundle. 
But nowadays, you only have an option for choosing if the the child product follow the parent stock change or not. 

Means: you buy  the 'final" product from a supplier, both the child and parent's stock increases. 

This behavior is irrelevant when you buy the parent and child product from different supplier with different minimum of quantity.
In that case we need to increase the stock of parent and child product separately, with separate supplier order, but decrease equally the parent and child stock when a bundle product (virtual product) is sold.   

## Suggested implementation

Change the single current option: "Augmenter/Réduire le stock sur changement du stock du père" by two independant options:
"Augmenter/Réduire le stock sur changement du stock du père à l'achat" & "Augmenter/Réduire le stock sur changement du stock du père à la vente"

**Comment by dolibit-ut** [comment]
translation into english:

### Suggested implementation

Change the single current option: "Increase/Decrease the stock on father's stock change" 
by two independant options:
"Increase/Decrease the stock on father's stock change on buy" & 
"Increase/Decrease the stock on father's stock change on sell".
