### ISSUE TITLE
Bug: lors de l'ajout de produits defini a acheter lancement d'une erreur 500

### ISSUE THREAD

**Issue by Grandjeanfrederic** [Dolibarr/dolibarr#15041]
# Bug
lors de l'ajout de produits defini a acheter lancement d'une erreur 500

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB
- **URL(s)**: /fourn/commande/card.php?id=17

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by aspangaro** [comment]
Blank page is a php error, can you send php server log ?
