### ISSUE TITLE
Bug on adding documents in email form (proposal and invoice)

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#15045]
# Bug
Similar to #11056. When I add document as attached in email form, mail is sent instead of realoading page with file attached.

## Environment
- **Version**: 12.0.2 and develop
- **OS**: Mint
- **Web server**: Apache
- **PHP**: 7.4
- **Database**: Mysql
- **URL(s)**: comm/propal/card.php?id=1589&action=presend&mode=init

## Expected and actual behavior
It is not possibile to attached files to email.

## Steps to reproduce the behavior
On the proposal or invoice mail form, add an additional document.

**Comment by laudeco** [comment]
Hi @aschio ;

I tried to reproduce your issue on version 12.0.3 with debug mode enabled and I cannot reproduce this issue.

Could you try and let me know if we can close this issue

Cheers
L.

**Comment by aschio** [comment]
yes, you can. I found the problem into an external module. Sorry...
