### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Grandjeanfrederic** [Dolibarr/dolibarr#15040]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB
- **URL(s)**: /fourn/commande/card.php?id=17

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
I think the issue description is missing ?

**Comment by aspangaro** [comment]
Same as #15041
