### ISSUE TITLE
Bug: cannot delete multiple draft customer invoices from the list 

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15056]
# Bug
I can delete multiple objects from other lists, it should be possible everywhere.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.11
- **Database**: PostgreSQL 12.4
- **URL(s)**: /compta/facture/list.php?leftmenu=customers_bills_draft&search_status=0

## Expected and actual behavior
option in drop-down list "delete"

**Comment by eldy** [comment]
Seems to work correctly with develop branch

**Comment by atm-maxime** [comment]
No it's not working in develop branch, but this is not a bug. This is a feature request because the mass delete action has not been implemented on the customer invoice list yet.

**Comment by eldy** [comment]
Yes, it works. It has been implemented in develop branch. I have tested again in develop successfully. Note: We are speaking about "draft" invoices. And for draft invoice, mass deletion is now implemented and seems to work on develop branch.

**Comment by atm-maxime** [comment]
@eldy , I found out that you must have INVOICE_CAN_REMOVE_DRAFT_ONLY setup activated to have the mass action available. And funny thing, I can delete draft and validated invoices... Fortunately the system checks if the invoice is the last validated one.

**Comment by dpriskorn** [comment]
@atm-maxime I could not find that setting in the settings of the invoices module. After setting it manually "delete" show up in the menu. 😃
I think it should be on by default.
