### ISSUE TITLE
Line newly created doesn't show up in the BOM listing

### ISSUE THREAD

**Issue by Mx74** [Dolibarr/dolibarr#15070]
# Bug

When adding a new line line in a BOM, after having clicked the "Add" button, this line doesn't show up in the listing above. 
It's registered and created, but it appears only after adding another line (and this new one won't appear) or validating the BOM.

## Environment
- **Version**: [*12.0.03*]
- **OS**: [ *Ubuntu Server 18.04*]
- **Web server**: [*Apache/2.4.29 *]
- **PHP**: [*PHP 7.0*]
- **Database**: [*MySQL 5.5*]
- **URL(s)**: [*/bom/bom_card.php?id=1#addline*]

## Expected and actual behavior
When a line is added in the BOM, it should appear right after the add button has been clicked. 

## Steps to reproduce the behavior
Add a line in the BOM.

**Comment by atm-maxime** [comment]
Sorru I can't reproduce with the latest 12.0 branch on github. Can you confirm ?

**Comment by Mx74** [comment]
Indeed, I tested the last dev version, and it seems to be solved. 
Great :+1:
