### ISSUE TITLE
Cannot add negative line to invoice if product comes from products database

### ISSUE THREAD

**Issue by joanahead** [Dolibarr/dolibarr#15087]
# Bug
When creating a regular invoice I need to include a negative quantity line. That is a line with positive product price (10€) and negative quantity (-1) because in this invoice we are subtracting a product that was mistakenly invoiced to the client before this.
If the product is $prod_entry_mode=="free" there's no problem, but if the product comes from the database Dolibarr shows an error (red box) with the text (translating from spanish...) "Quantity in clients' invoices cannot be negative".

## Environment
Dolibarr 12.0.2
It happened before this, even with Dolibarr 8. 

## Expected and actual behavior
We would expect Dolibarr to allow us that operation, mostly considering we have FACTURE_ENABLE_NEGATIVE_LINES set to 1 in Dolibarr's general configuration.
It works if the product comes from free entry mode, but not if it comes from the products database.
Also, we think it should be allowed in the same way in propals and commandes if FACTURE_ENABLE_NEGATIVE_LINES is set.

#Suggested solution
We used to change the code in /compta/facture/card.php like this in both "updateline" and "addline" actions:
```
//deleted line: if ($qty < 0) {
if ($qty < 0 && empty($conf->global->FACTURE_ENABLE_NEGATIVE_LINES)) {  //added line
			$langs->load("errors");
			setEventMessages($langs->trans('ErrorQtyForCustomerInvoiceCantBeNegative'), null, 'errors');
			$error++;
		}
```
Also changed this (only in "addline" action):
```
//deleted line: if (!$error && ($qty >= 0) && (!empty($product_desc) || !empty($idprod))) {
//added line:
if (!$error && ($qty >= 0 || !empty($conf->global->FACTURE_ENABLE_NEGATIVE_LINES)) && (!empty($product_desc) || !empty($idprod))) {
```

**Comment by FHenry** [comment]
If you invoice something you should cancel it with credit note, not delete it ?

**Comment by joanahead** [comment]
Not always as I see it.
Example: book distribution company. Sells and invoices each month to book shops...
This month's invoice sent to a client...
- Book A, 2 copies
- Book B, 3 copies
- Book C, -1 copy (the client sends this book back to distributor)
- Book D, 5 copies

This is usual and all companies seem to work/invoice this way.

**Comment by FHenry** [comment]
Yes exactly, so credit note with refund.

**Comment by eldy** [comment]
@aspangaro Did you see this case, 1 predefined product that is removed from a following invoice.
In most cases, we have to create a credit note for the refund of Book C, but why not having the negative amount here, as long as the vat of the same rate stay positive because of other products with same rate ?

**Comment by mmarquez** [comment]
I believe that this way of working is so common that an additional variable should be used to allow for negative amounts as long as the invoice total is not negative.

This is one of the first things I have to change in most installations.
