### ISSUE TITLE
BOM: error  when trying to delete a line

### ISSUE THREAD

**Issue by Mx74** [Dolibarr/dolibarr#15088]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug

In a BOM back to draft for modification, when trying to remove a line, I got this error: 
Warning: method_exists() expects parameter 2 to be string, object given in htdocs/testdolibarr/htdocs/core/actions_addupdatedelete.inc.php on line 265

Warning: Cannot modify header information - headers already sent by (output started at /htdocs/testdolibarr/htdocs/core/actions_addupdatedelete.inc.php:265) in/htdocs/testdolibarr/htdocs/core/actions_addupdatedelete.inc.php on line 295

Browsing back to the BOM page, the line is actually deleted. 

## Environment

    Version: [12.0.03]
    OS: [ Ubuntu Server 18.04]
    Web server: [*Apache/2.4.29 *]
    PHP: [PHP 7.0]
    Database: [MySQL 5.5]
    URL(s): [/bom/bom_card.php?id=3&lineid=12&action=confirm_deleteline&confirm=yes]

**Comment by atm-maxime** [comment]
I cannot reproduce with the latest 12.0 version from the github. I think it has been solved.

**Comment by Mx74** [comment]
Hello,

Indeed, I installed the last dev version and it's been resolved.
Great !
