### ISSUE TITLE
Creating Delivery Confirmation in non-English Language causes issues with special characters

### ISSUE THREAD

**Issue by MartinHold** [Dolibarr/dolibarr#15111]
# Pre Amble
This issue is there since my first installation of Dolibarr, which was Version **4.0.1** - **YES!!!**, it's been an issue for 8 major releases. **PLEASE** fix this issue, the solution is added below! I reported this very error in version 6.0.3 **three (YES 3 !!!!)** years ago - see issue #7530, which was closed due to **inactivity**.
Thank you - each time I run an upgrade at my customers I *must* do this goofy correction!

# Bug
Special characters not displayed properly in printouts / handouts. I.e. for Delivery Receipt in German, instead of proper character (i.e. 'ü') the related web sequence (i.e. '&uuml') is shown on the form, rendering it useless as it can't be used in real life.

## Environment
- **Version**: [*12.0.3*]
- **OS**: [*Linux nlss4.a2hosting.com 2.6.32-954.3.5.lve1.4.76.el6.x86_64 #1 SMP Mon Dec 23 07:33:14 EST 2019 x86_64*]
- **Web server**: [*Apache*]
- **PHP**: [*5.6.40*]
- **Database**: [*MySQL or MariaDB 10.1.40-MariaDB-cll-lve*]

## Expected and actual behavior
[*when using a non-English language to display printable documents and forms, special characters should be displayed correctly*]

## Steps to reproduce the behavior
[*Enable multiple languages, switch customer language to German and print delivery receipt, the signature section in the place for "For the Customer" should read "Für den Kunden" but reads "Für den Kunden" instead - in the PDF preview as well as in the printout*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*<img width="324" alt="31053868-a72d4988-a6a6-11e7-9a2f-683522b722d6" src="https://user-images.githubusercontent.com/17029736/96927418-4d193380-14b7-11eb-9143-003260b1a03e.png">*]

## Fix for this Bug
[*This issue can actually be fixed very easily with only very local impact (the correct behaviour) by doing the following in this release:*]

In File ..core/modules/livraison/doc/pdf_typhon.modules.php change the following two lines:

Line 664: $pdf->MultiCell($larg_sign, 2, **$outputlangs->transnoentities("For")**.''.$outputlangs->convToOutputCharset($mysoc->name).":", '', 'L');

Line 669: $pdf->MultiCell($larg_sign, 2, **$outputlangs->transnoentities("ForCustomer")**.':', '', 'L');

**Comment by Ahuahuachi** [comment]
@MartinHold, I created a PR with your suggestion. Hope it would be merged soon.

**Comment by 2BCAD** [comment]
Hi.
I am using Dolibarr 14.0.5 and I have still the same issue. I checked the indicated file. The 2 lines in my installation were not corrected. I then modified them, restarted even the server, but still the problem stays.
