### ISSUE TITLE
Bug: accented character

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#15121]
# Bug
Under "Customer invoice statistics" or "Statistics - Commercial proposals" the value that have a
Values that have accented characters are written with an html interpretation. Example (french):
"Valid&eacute;" ("Statistics - Commercial proposals")
"Sign&eacute;e" ("Statistics - Commercial proposals")
"Factur&eacute;e" ("Statistics - Commercial proposals")
...
Pay&eacute;e" ("Customer invoice statistics")
Commenc&eacute;e" ("Customer invoice statistics")
...
For information, the title of tables on the same web page which have accented characters are displayed normally

l don't know where the translation is.

## Environment
- **Version**: 13.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.0.33-0+deb9u10
- **Database**: MySQL or MariaDB 5.5.5-10.1.45-MariaDB-0+deb9u1
- **URL-1 **: /compta/facture/index.php?leftmenu=customers_bills
- **URL-2 **: /comm/propal/index.php?leftmenu=propals

## Expected and actual behavior
"Validé" ("Statistics - Commercial proposals")
"Signée" ("Statistics - Commercial proposals")
"Facturée" ("Statistics - Commercial proposals")
...
Payée" ("Customer invoice statistics")
Commencée" ("Customer invoice statistics")
...

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Screenshot_20201023_181713-1](https://user-images.githubusercontent.com/8665615/97028268-311b9d80-155c-11eb-8995-86cf923da1f2.png)
![Screenshot_20201023_181506-1](https://user-images.githubusercontent.com/8665615/97028281-34af2480-155c-11eb-9890-d61a52a1f3ba.png)

**Comment by eldy** [comment]
Should be fixed with bb147d2
