### ISSUE TITLE
"MO - Manufacturing Order" is not an Italian province

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#15161]
# Bug
"MO - Manufacturing Order" appears as an Italian province instead of "MO - Modena". This was tested both in a local install and in the shared demo instance.

## Environment
- **Version**: 12.0.3 from demo site
- **OS**: the one for https://demo.dolibarr.org/
- **Web server**: the one for https://demo.dolibarr.org/
- **PHP**: the one for https://demo.dolibarr.org/
- **Database**: the one for https://demo.dolibarr.org/
- **URL(s)**: All urls that let you set a province, or that use the value of a province, mainly:

- /societe/card.php 
- /societe/contact.php

## Expected and actual behavior
When you set country to Italy, and try to set Modena you see that it's translated as "MO - Manufacturing Order" (see the attached image). It seems that the translation key "MO" for Modena (llx_c_departements) is in conflict with "MO" for Manufacturing Order ( from /htdocs/langs/en_US/mrp.lang )

## Steps to reproduce the behavior
- Create a new third party
- Set country to Italy
- Scroll through the provinces list, you will see "MO - Manufacturing Order" as in the screenshot

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![screenshot_2020-10-26_09-03-48](https://user-images.githubusercontent.com/55888212/97148916-2f282900-176c-11eb-85b1-10f44491629c.png)

**Comment by orebd** [comment]
Hello,
there is the same issue with those code region into llx_c_departements :
  rowid | code_departement   1 | fk_region | cheflieu | tncc | ncc | nom | active
-- | -- | -- | -- | -- | -- | -- | --
182 | MO | 305 | NULL | NULL | NULL | MODENA | 1
 817 | MO | 1101 |   | 0 | MISSOURI | Missouri | 1
 861 | MO | 8602 |   | 0 |   | Morazan | 1

Maybe MO & MOs is not necessary and can be delete and replace by Mrp & Mrps
Seeing into mrp.lang
Mrp=Manufacturing Orders
MO=Manufacturing Order
MOs=Manufacturing orders

**Comment by orebd** [comment]
It needs to change MO to M_Order or indexing translation with the name of module like MRP_MO.

**Comment by ToniTen** [comment]
> Maybe MO & MOs is not necessary and can be delete and replace by Mrp & Mrps
> Seeing into mrp.lang
> Mrp=Manufacturing Orders
> MO=Manufacturing Order
> MOs=Manufacturing orders

I personally think that Dolibarr should stay away from 2 letter codes for translation keys, mainly because they gain it nothing (plenty of other translation keys are MUCH longer, so it's not saving space in the database) and they can lead to really weird bugs. It took me a while to find where the original source for the Modena name was, since it's not in any of the lang files, not was easily grep-able.

I wonder what other such strange issues are lurking in unnoticed due to this.
