### ISSUE TITLE
Nouvel Import Commande Client

### ISSUE THREAD

**Issue by hanen91-ch** [Dolibarr/dolibarr#15198]
Bonsoir, je veux ajouter un code PHP à la fenêtre import un autre champ "import commande " pour que je peux importer des commandes et leurs lignes.
![image](https://user-images.githubusercontent.com/69306045/97430002-85d26600-1918-11eb-85b9-6127b8f27d54.png)

**Comment by atm-maxime** [comment]
Hello,

Please keep github conversation in english so everyone can understand.
Thanks for this feature request. I don't think it's that easy to add an import of orders or any other document having lines. But if you have PHP skills, you're welcome to give it a try.

Cheers

**Comment by StephaneLesage** [comment]
Yes please use english.

Your feature request has been done by #14929.
It will be present in version 13.
Please close this issue.
