### ISSUE TITLE
Can not save changes in product account setup 

### ISSUE THREAD

**Issue by bluethumb** [Dolibarr/dolibarr#15208]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Can not save changes in product account setup 
Save knob get "grey" out !? 
accountancy/admin/productaccount.php 

## Environment
- **Version**:12.0.3
- **OS**: archlinux 
- **Web server**:ngnix
- **PHP**: 7.4.10
- **Database**: mariadb
Version                : 10.5.5-2
- **URL(s)**: localhost

## Expected and actual behavior
Save data/page

**Comment by futurehousestore** [comment]
I can confirm this bug in version 13 beta. You can actually save changes but only if you select products individually. If you use the mass select box to select all the products the "save" button is greyed out and not able to save changes.

**Comment by bluethumb** [comment]
Also pretty annoying interface if you have to edit a lot of accounts
