### ISSUE TITLE
Weighted Average Price calculation wrong due to deleted invoices/shipments. 

### ISSUE THREAD

**Issue by thegeettanna** [Dolibarr/dolibarr#15247]
# Bug
I have only tried with the stock setup where Shipment handles stock movement (decrease stock on Shipping validation and increase stock on shipping deleted). But I am sure that it is the same with Invoices.

The weighted average price calculated for each stock goes haywire as soon as there is a deleted invoice or shipment (based on the stock setup). It seems that the stock deleted in Invoice/Shipment is added at a cost price of "0" instead of the price it was sold on. Also, the field "Weighted Average Price" is not available for list view on stock movements as well. 

## Environment
- **Version**: 12.0.3

## Expected and actual behavior
When stock in increased due to deletion of Invoice or Shipment, the amount should be atleast the cost that it was sold on, if not the cost price when it was purchased. 

## Steps to reproduce the behavior
Add a product, buy the product at 'X' price. Sell the product (Stock to be decreased on Invoice/shipment) at 'Y' price. Weighted average price at this point should be 'X'. Now deleted the invoice/shipment. The new weighted average price should still be 'X', but instead it is X+0/(total quantity). 

![Screen Shot 2020-10-21 at 10 13 02 AM](https://user-images.githubusercontent.com/24646523/97799930-e3d3b600-1c56-11eb-86a8-73dba47a6aab.jpg)
![Screen Shot 2020-11-01 at 1 54 15 PM](https://user-images.githubusercontent.com/24646523/97799933-e8986a00-1c56-11eb-94c5-e23e9146b047.jpg)

**Comment by eldy** [comment]
When a shipment is deleted, we increase stock. But we should not modify the WAP price because this is not an entry in stock due to a product that is entered (new) into stock but because we made registered a stock exit by validating the shipment when we should not (the shipment was recorded and validated by error). Because the WAP did not change during the exit, we also do not change it during this correction.
So WAP should be same before the shipment is done, after the shipment has been validated (because a stock exit never change a WAP) and after it is deleted.

Did you enabled the hidden/develop option STOCK_UPDATE_AWP_EVEN_WHEN_ENTRY_PRICE_IS_NULL ? (Such option has no sense and should never be enabled).

**Comment by thegeettanna** [comment]
Dear @eldy, 

Agreed, WAP should not be modified because of shipment validations and deletions. But somehow our WAP is extremely low. We are not sure what has caused this and our first assumption was Shipment deletion was adding an entry with '0' unit purchase price. Every Product ref. with such an error had shipments or invoices that were deleted atleast once. 

I will have to go into more details by checking weighted average price after every entry. How can I add it to the list view in the stock movements? Is there an easy guide there out somewhere?

**Comment by thegeettanna** [comment]
The hidden option STOCK_UPDATE_AWP_EVEN_WHEN_ENTRY_PRICE_IS_NULL is not enabled.

**Comment by eldy** [comment]
When entry price is 0, then wap should be unchanged. There is a protection into the code that record a movement to not update wap if entry price is 0 . To help diagnose what make the wap become low, go on list of stock movement, add the column field unit purchase price. Do you see value that may hurt you (except 0 that should not have effect) ?
If you have trouble only for product with deletion of invoice or shipment, this may be a clue. What is your rule for automatic stock increase on stock setup ?

**Comment by thegeettanna** [comment]
Dear @eldy, 

Added protection in the code is very visionary of you. 
I have attached screen shots for unit purchase price in the list view. 
Except '0' I don't see anything that could have hurt the WAP. But I am going to do an intensive test later tonight. 
Screen Shots for stock movements:
![Screen Shot 2020-11-01 at 1 54 15 PM](https://user-images.githubusercontent.com/24646523/97951101-0f71b000-1dbf-11eb-9e7f-3b7f616ca55f.jpg)
![Screen Shot 2020-11-02 at 6 35 26 PM](https://user-images.githubusercontent.com/24646523/97951114-18fb1800-1dbf-11eb-8683-86f45505b382.jpg)

Stock Module Setup:
![Screen Shot 2020-11-03 at 10 03 20 AM](https://user-images.githubusercontent.com/24646523/97951124-244e4380-1dbf-11eb-8681-f4f4346ea4c3.jpg)

Although this might be irrelevant, we also decrease stock through POS module. Maybe if we need to check at a later stage, this information might come in handy.

**Comment by thegeettanna** [comment]
Let me also post the Cost Price & WAP of the relevant Products for which we have posted the stock movements. 
![Screen Shot 2020-11-03 at 10 37 54 AM](https://user-images.githubusercontent.com/24646523/97951601-b571ea00-1dc0-11eb-900c-738d52cf5bd0.jpg)
![Screen Shot 2020-11-03 at 10 40 03 AM](https://user-images.githubusercontent.com/24646523/97951665-fbc74900-1dc0-11eb-948c-12471ec723be.jpg)

**Comment by thegeettanna** [comment]
To give a more clear and accurate example, here I have attached a complete stock movement example and its WAP page as well. Although this example has a stock correction entry and not a deleted shipment. I still think this is something that needs to be addressed. 
![Screen Shot 2020-11-03 at 1 09 42 PM](https://user-images.githubusercontent.com/24646523/97959869-43a49b00-1dd6-11eb-8931-c56754114c15.jpg)
![Screen Shot 2020-11-03 at 1 06 22 PM](https://user-images.githubusercontent.com/24646523/97959876-47382200-1dd6-11eb-8683-7023d0c0c1a3.jpg)

Hope we can resolve this. @eldy let me know how can I help more. 
Will put in deleted shipment examples soon as well.

**Comment by thegeettanna** [comment]
@eldy 

Any updates on what is causing this error? 
How can I make the field Weighted Average Price visible on Stock Movements list page? Maybe that will help us find the corrupted entry?

**Comment by thegeettanna** [comment]
> @eldy
> 
> Any updates on what is causing this error?
> How can I make the field Weighted Average Price visible on Stock Movements list page? Maybe that will help us find the corrupted entry?

I just need to figure out how to add a field to the view page for stock movements. 
Can someone guide me on that?
