### ISSUE TITLE
Configure the public Holiday in DOLIBARR

### ISSUE THREAD

**Issue by ffit2020** [Dolibarr/dolibarr#15266]
# Bug
Public holidays: even if I have put all holidays in a specific country, then win timesheet (personal dolibarr use) is not shown...

Hi, I have set for a country, all public holidays.
But when I go to time spent, where a user has to fill his time spent, these fields are not in red or in yellow (in yellow are when the user is in vacation).
How can I do to make this go well ?
thanks

![image](https://user-images.githubusercontent.com/73834929/97875432-a7698e00-1d1a-11eb-8f58-10151017c108.png)

**Comment by eldy** [comment]
Can you confirm that the country of your company (setup - company) is same than the country you used to enter the holiday ?

**Comment by ffit2020** [comment]
hi, yes I have checked and yes we have set switzerland either in the company profile or in the holiday, see screen here:

![image](https://user-images.githubusercontent.com/73834929/98252354-1db7fb80-1f7a-11eb-9c46-1b3979ab4840.png)
