### ISSUE TITLE
Option to not add VAT for down payment when creating from a percentage of existing product

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#15279]
# Bug

TVA is added for "Facture d'acompte"

1. When making a "Facture d'acompte" based on a "Commande" and using any of the options with a percentage, VAT is added.  For "Factures d'acompte" VAT **shall not** be added.
2. If making the "Facture d'acompte" with a fixed amount, VAT is correctly not added.

So please correct #1 

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /azerty/htdocs/compta/facture/card.php?facid=298

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
If you create a down payment from a list of product, you know which product you include into your invoice, so you must include the VAT.
Not including VAT when making account means you ask the governement to give you a delay to pay the VAT included in your down payment (that will be payed later in final invoice instead of a small part with down payment and the rest for final invoice). Sometimes you can, sometimes you can't. In most cases, hen down payment is for a known list of products (so with VAT calculable) you can't, this is why this is default behaviour to have the VAT propagated into down payment.
If for your case, you are allowed to make down payment with no VAT, an option should be added. So i switch the status of the ticket to remind developers for this feature request.

**Comment by hasse-basse** [comment]
Hi

You are wrong and I'll explain why below

An invoice occurs in the same moment as a product changes hands. Not before, not after, but in that very moment and this has nothing to do with when the invoice is printed. It is the change of control of the product that matters.

Exception from the above are streaming services like telephony, electricity, gas and water, and some other well defind services. In  these cases VAT shall be added on the down payment. In all other cases, mening when goods (biens) are involved, the invoice does not occure untill the goods has changed hands, leading to that the VAT is not to be  declared until the controll of the goods have gone to the buyer. Of this I'm sure.

 **Down payment are to be seen as a security for future purchase and as no goods have changed hands,  tax shall not be declared. Of this I am also sure.**

But of course, the seller can  secure himself for the payment of the VAT, so for a purchase of 100 000 € HT, he can demand a downpament of 120 000 €, **BUT** VAT shall not be mentionned as the goods have still not changed hands.

Pls find the below text from this web page 

https://www.lecoindesentrepreneurs.fr/factures-dacomptes/#:~:text=L'entreprise%20doit%20facturer%20la,%C3%A0%20exigibilit%C3%A9%20de%20la%20TVA.&text=La%20TVA%20ne%20doit%20pas,d%C3%A8s%20l'encaissement%20du%20prix.

**La TVA sur les factures d’acomptes**
L’entreprise doit facturer la TVA sur les factures d’acomptes qu’elle émet dès lors qu’elles donnent lieu à exigibilité de la TVA. La nature des éléments facturés détermine les règles à suivre : 

1. - Pour les opérations de livraisons de biens, la TVA n’est pas encore exigible car le fait générateur intervient lors de la livraison des biens. La TVA ne doit pas figurer sur la facture d’acompte.
2. - Pour les opérations de prestations de services, la TVA est exigible dès l’encaissement du prix. La TVA doit figurer sur la facture d’acompte

.
La comptabilisation des factures d’acomptes
Au niveau de l’entreprise qui émet la facture d’acompte, seul le paiement reçu s’enregistre en comptabilité dans le compte suivant : 4191 « Clients – avances et acomptes reçus sur commandes ». Ensuite, le paiement doit être imputé dans le compte 411 « Clients » adéquat.

**Comment by hasse-basse** [comment]
Anyhow, the option you are proposing is a good solution. 

**I suggest that you make it compulsory to choose with our without VAT!**
