### ISSUE TITLE
Declared progress doesnt sort when more than 100% in Tasks/activities -> List

### ISSUE THREAD

**Issue by jsbrassard** [Dolibarr/dolibarr#15278]
Dolibarr
12.0.3

When trying to sort the task list by declared progress, the list sort from 100% and down.

If a task is more than 100%. The Task is listed with other task with declared progress starting with 1

As seen below

![image](https://user-images.githubusercontent.com/51123237/98014959-4600f800-1dca-11eb-893c-cfa85fad8ffa.png)

**Comment by jsbrassard** [comment]
This is the top of the list 
![image](https://user-images.githubusercontent.com/51123237/98015185-806a9500-1dca-11eb-95e9-df5d16ba4e2d.png)

**Comment by eldy** [comment]
How do you enter the declared progress of the task ?
Calculated progress can be higher than 100% but declared progress is a value from 0 to 100. What means a task is completed at 105% ?

**Comment by jsbrassard** [comment]
I updated the database. It's a way to bypass the fact that you cannot sort the calculated progress which I need. When a task is over 100% it means the project is in overtime and need attentions.
