### ISSUE TITLE
Uniformize salary and vat modules with tax module

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#15275]
# Feature Request
Currently, creating a salary payment or a vat payment only records the payments and the bank entry at the same time, preventing forecast creation. The tax module however allows to create a new tax record and later the payment with the bank entry.

## Use case
We would like to be able to have a forecast on salaries and vat as we can have it with future tax payments.

## Suggested implementation
Split the salary and vat creation and the bank entry creation, with a status unpaid / paid.

@eldy @aspangaro we talked about this, any remarks before we start developing ?
@ludovicandrieux Just so you know this task is visible by the Dolibarr community.

**Comment by eldy** [comment]
Go but keep ability to create both in one time as now for people that does enter payment only when done.

**Comment by aspangaro** [comment]
Ok, from my point of view, need to keep compatibility with old data. Maybe show old payment in list of salaries/tax list when fk_salaries or fk_vat in respective payment table are not set

**Comment by atm-gauthier** [comment]
Here's my PR of TVA uniformization : 
https://github.com/Dolibarr/dolibarr/pull/16020
