### ISSUE TITLE
Enable PostgreSQL backup with web interface

### ISSUE THREAD

**Issue by zedzedtop** [Dolibarr/dolibarr#15287]
# Feature Request
Allow the backup of the PostgreSQL database directly from the administration interface as for Mysql
Perform the TODO task on the mysql backup (Replace with executeCLI function in dumpDatabase function)

## Use case
PostgreSQL backup only works on command line currently because there is a problem to pass the password in parameter.
There is a way around this: either modify the pg_hba.conf file to allow passwordless connections for that specific connection, or create a .pgpass file for the user used to run the web server.

## Suggested implementation
I propose to add the management of the postgresql backup and to resume the mysql part to include the use of the "executeCLI" function.
The part on postgresql is currently functional on my installation, I was even able to add it in the "scheduled jobs"

## Suggested steps
I propose a pull request with the modifications

**Comment by eldy** [comment]
Your PRs are welcome.
