### ISSUE TITLE
ODT files corrupt when third party has the & symbol in the name. BUG

### ISSUE THREAD

**Issue by ojt1998** [Dolibarr/dolibarr#15295]
Hi all,

Dolibarr 12.0.3

As the title says, our ODT files don't generate if the third part has the symbol in their name. Is this a known issue that has a fix?

Kind regards,
Oliver

**Comment by ojt1998** [comment]
Environment

Version: 12.0.3
OS: UBUNTU 
Web server: Apache
PHP: 7.4.3
Database: MySQL 8.0.22

Expected and actual behavior

ODT file produced as per template and opening. Currently the files end up corrupted if the third party has an & symbol.

Steps to reproduce the behavior

Third party has & symbol in name. Then when generating a file for sales order, proposal, etc. they end up corrupt.

**Comment by code-chicken** [comment]
Should have been fixed here: #14957

**Comment by ojt1998** [comment]
Is it possible that when we upgraded to 12.0.3 the file wasn't replaced?

**Comment by eldy** [comment]
PR was merged 27 days ago. So i think it should be available in next 12.0.4 (12.0.3 was released just before).
Link to the fix: https://github.com/Dolibarr/dolibarr/pull/14974
