### ISSUE TITLE
supplier invoice - fiscal stamp

### ISSUE THREAD

**Issue by hanen91-ch** [Dolibarr/dolibarr#15293]
hello, I made some modification in the supplier invoice to display the fiscal stamp like the customer invoice. But the problem is that when I click on the button to modify the stamp amount, the lower part of the invoice (the part of the product table) is not displayed.

here is the code I modified
[code.txt](https://github.com/Dolibarr/dolibarr/files/5487766/code.txt)

![image](https://user-images.githubusercontent.com/69306045/98112637-c8f58180-1ea2-11eb-8f97-ceed59f45ac0.png)

**Comment by dolibit-ut** [comment]
I have not checked your code.
But why don't you use just the feature of an extrafield for that?

**Comment by hanen91-ch** [comment]
I cannot use an additional field because my "fiscal stamp" field must be calculable.
here is the code I modified
[code.txt](https://github.com/Dolibarr/dolibarr/files/5510719/code.txt)
