### ISSUE TITLE
Error while updating from 12.0.3 to  13 beta

### ISSUE THREAD

**Issue by Mx74** [Dolibarr/dolibarr#15309]
# Bug
At the first step of the migration script : 

Erreur DB_ERROR_1293: ALTER TABLE llx_ecm_directories CHANGE COLUMN date_m tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

Exécution du script | KO

## Environment
- **Version**: [12.0.3
- **OS**: Ubuntu server 18
- **Web server**: Apache 2.2
- **PHP**: PHP 7.0.33
- **Database**: mysql 5.5
- **URL(s)**: /install/check.php?testget=ok

**Comment by frederic34** [comment]
@Mx74 can you show structure of the table

**Comment by Mx74** [comment]
Hello,

The fix worked for updating to 13 beta. 
But today I tried to to update from 12.0.4 to 13.0.1, and same error message. 
it seems that the fix has not been integrated to the final version?

**Comment by Mx74** [comment]
Hello, 

While updating from 12.0.4 to 13.0.2, the same error appears, despite of the fix being merged. Any idea why?
