### ISSUE TITLE
separate category for services

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#15304]
# Feature Request
separate category for services 

In many customer cases with really a different range of products and services
it makes no sense to have one big category list.

suggestions:
A)
a separate table for service categories 

B)
a field in existing table to choose like 
0 - category for products + services
1 - category only for products
2 - category only for services

**Comment by eldy** [comment]
Note that you can create subcategory, so a category "Product" and another "Service" and then create subcategories into each of this parent category.

**Comment by dolibit-ut** [comment]
Thank you. Yes, I know and this is a nice workaround. 
But if you have a lot of categories with subcategories and subsubcategories  you get so wide tags
and you lose the overview.  IMHO
