### ISSUE TITLE
incorrect currency on third party's capital

### ISSUE THREAD

**Issue by henrynopo** [Dolibarr/dolibarr#15319]
## Environment
- **Version**: 12.0.3
- **OS**: Linux mankey.sgcloudhosting.com 3.10.0
- **Web server**: Apache
- **PHP**: 7.2.33
- **Database**: MySQL or MariaDB 5.7.32
- **URL(s)**: dolibarr/compta/facture/card.php

## Expected and actual behavior
- *Expecting the option to select different currency for the "Capital" of a third party.*

## Steps to reproduce the behavior
- *While creating a third party, the system set a default currency for under "Capital". This currency is the same as my company's main currency.*

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/3304600/98324412-274b6d00-2027-11eb-92dd-33a00e635fa8.png)

**Comment by dolibit-ut** [comment]
This is no bug. 
You have to activate the module **Multicurrency** - find at Multi-modules tools.

**Comment by henrynopo** [comment]
> This is no bug.
> You have to activate the module **Multicurrency** - find at Multi-modules tools.

The multicurrency module is activated in my Dolibarr. But I cannot select currency for third party's capital.
