### ISSUE TITLE
Salaries are seen by any users

### ISSUE THREAD

**Issue by ffit2020** [Dolibarr/dolibarr#15314]
Salaries are seen by any users, even if the option is unchecked "see salaries of everybody"
So all users now can see salaries of their collegues.
how can fix it?
thanks

**Comment by eldy** [comment]
Can you paste a copy of the permission for module "User" of the user that can see all salaries ?
Can you also check that the viewed employee is not a subordinate of user that see .

**Comment by atm-maxime** [comment]
There's no permission called "See salaries of everybody", only "Read payments of salaries". And if this is unchecked, user can't go on the salary menu.

**Comment by ffit2020** [comment]
hi, yes I wanted to tell that this "Read payments of salaries" is unchecked. 
he is unchecked there 

But if the user goes to his card, then click on "hr and bank" tab, can see on the right his last 3 salaries
clicking on "all salaries payments", rhe user will reach a page with only his salaries. 
But if a user cancel his name (email) on that form (see image 2, the text in the top, where I have put 2 arrows), he will be able to see ALL salaries of ALL users.
this is a bug

image 1
![image](https://user-images.githubusercontent.com/73834929/98563884-fdef4300-22ab-11eb-9ac7-1b495fe20c0b.png)

image 2:
![image](https://user-images.githubusercontent.com/73834929/98563676-bec0f200-22ab-11eb-99c4-c47057df08c9.png)

**Comment by atm-maxime** [comment]
Ok understood now. Which version of Dolibarr?

**Comment by ffit2020** [comment]
Hi, its’ not found this ticket


Massimo Lombardi
HelpDesk
Consultant | FORFIRM
P: +39 0332 1520511 | M:+39 3357769915
Via Sempione 14 - 21100 VARESE
m.lombardi@forfirm.com | www.forfirm.com<http://www.forfirm.com>


[cid:FORFIRMlogonuovogrande_65c71a90-db3e-4b62-9002-e475a4a336aa.PNG]
This e-mail including any files transmitted with it is of business nature and may contain confidential information. If you are not the intended recipient (or have received this e-mail in error), please notify the sender immediately and delete this message. Any form of unauthorized use, copying, disclosure or distribution of the contents in this message is strictly prohibited. Although due precautions have been taken to minimize the risk of transmission of viruses, it is suggested to check this e-mail and its attachment for the presence of viruses. We don’t accept responsibility for any damage or loss resulting from any virus transmitted by this e-mail.
Da: Maxime Kohlhaas <notifications@github.com>
Inviato: lunedì 9 novembre 2020 19:52
A: Dolibarr/dolibarr <dolibarr@noreply.github.com>
Cc: Support <support@forfirm.com>; Author <author@noreply.github.com>
Oggetto: Re: [Dolibarr/dolibarr] Salaries are seen by any users (#15314)


Ok understood now. Which version of Dolibarr?

**Comment by ffit2020** [comment]
hi, 12.0.2

**Comment by atm-maxime** [comment]
Hi. I just tested again on v12 and :
"But if the user goes to his card, then click on "hr and bank" tab, can see on the right his last 3 salaries" => no. If the user hasn't the permission to read salaries, he doesn't have the "last 3 salaries" on its user card, hr and bank tab.

I agree that we can have 2 different permissions : read all salaries / read my salaries. But that's a feature request, not a bug.

**Comment by ffit2020** [comment]
hi, I have the 12.0.2 version
which version do you have?
Because if you delete the employee name by the form and click the ENTER keyboard, he will see all salaries of all employees

see screenshot
![image](https://user-images.githubusercontent.com/73834929/99265774-5c736e80-2822-11eb-9515-ef40e053f7ce.png)

But I have the 12.0.2 version

**Comment by ffit2020** [comment]
hi, only this point is checked:
![Uploading image.png…]()

**Comment by ffit2020** [comment]
hi, only this check is flagged

![image](https://user-images.githubusercontent.com/73834929/99276249-c133c680-282c-11eb-888e-c643ef6176ae.png)

**Comment by atm-maxime** [comment]
Yes, so it's normal. Your user has the permission to read salaries, so he can see them all. As said before, there's only one permission today, so a nice feature request would be to add a permission "read my salaries".

**Comment by ffit2020** [comment]
ok thanks
