### ISSUE TITLE
Bug : Calcul TVA par Dolibarr avec factures de situation (v12.0.3)

### ISSUE THREAD

**Issue by AurelienBISOTTI** [Dolibarr/dolibarr#15324]
Bonjour,

J’ai un problème avec le récapitulatif de TVA que me calcule Dolibarr. J’utilise le module « Facture de situation » de Iouston (dolistore . com/fr/modules/1067-Facture-de-situation.html?search_query=situation&results=8) mais tous les chiffres remontés par ce module sont bons, le problème me semble venir de Dolibarr.

Je mets la capture d’écran en fichier joint.

    Création de la commande
    Création de 2 factures de situation. Les récapitulatifs sont bons.
    Pourtant, dans Dolibarr, quand je sors la TVA chaque mois, il me reprend la somme de TVA de toutes les factures de situation au lieu de juste prendre celle du mois.

La version de Dolibarr : à première vue, même bug sur toutes les versions. Les captures d’écran sont sur la v12.0.3

Votre version de PHP : 7.2.34

Votre dolibarr a t’il été mis a jour depuis une ancienne version ? Version installation initiale 6.0.3

Si vous êtes hébergé … Si oui, nom de l’hébergeur et type de serveur. Ionos, Plesk + (Debian?) serveur dédié qui est divisé entre plusieurs Dolibarr.

Vérifications de base
Problème reproduisible sur d’autres navigateurs ? Firefox/Chrome : OUI
Thème utilisé ? (Eldy/Md/Oblyon/etc) : ELDY

![](https://www.dolibarr.fr/forum/uploads/default/original/2X/5/5dd9383605ff7fe79c658cb8d33e170a3c25f63d.jpeg)

**Comment by dolibit-ut** [comment]
translation to english:

Hello,

I have a problem with the VAT summary that Dolibarr calculates me. I use the module "Situation invoice" from Iouston (dolistore . com/en/modules/1067-Situation-Invoice.html?search_query=situation&results=8) but all figures computed by this module are good, the problem seems to come from Dolibarr.

I put the screenshot as an attached file.


`Creation of the order
Creation of 2 situation invoices. Summaries are good.
However, in Dolibarr, when I take out the VAT each month, it takes me the VAT sum of all the situation invoices instead of just taking the one of the month.`

**Comment by dolibit-ut** [comment]
Hello,

please try to use next time english (try it with deepl).

**Comment by dolibit-ut** [comment]
You use an additional module. Please contact the developer (first) with the problem.

**Comment by AurelienBISOTTI** [comment]
Well, the dev said that's a problem with Dolibarr core and not his module.
Am I right @iouston ?

**Comment by iouston** [comment]
hi everybody.
Our module is just a php document template. In your example, the error is on monthly vat dolibarr report. Our module don't interact with this report. So i think this is a problem with vat calculation in dolibarr core

**Comment by eldy** [comment]
The feature invoice situation is currently an experimental feature that needs to be refactored to be working correctly for reports (a known conception trouble exists. This will need an important work so i'm afraid you can't expect a solution soon).

**Comment by AurelienBISOTTI** [comment]
Hello,

@eldy Is there any update about "invoice situation" ? How can we help with the fix ? Is there a specific fork / repo ?

ping @EchoLoGeek

**Comment by AurelienBISOTTI** [comment]
@eldy @iouston 

@echologeek solved the VAT issue

How can we push it into the core now ?

**Comment by atm-maxime** [comment]
@AurelienBISOTTI see https://github.com/Dolibarr/dolibarr/blob/develop/.github/CONTRIBUTING.md
