### ISSUE TITLE
Bug: v13 thirdparties API

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#15329]
when calling list or a thirdparty we get error with this message

Warning: substr() expects parameter 1 to be string, array given in /volume2/web/dolibarr/htdocs/includes/restler/framework/Luracast/Restler/Data/Text.php on line 63

**Comment by frederic34** [comment]
@ptibogxiv can you check with https://github.com/Luracast/Restler/pull/562/files
