### ISSUE TITLE
Bug: v13 error with token in module page

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#15326]
When editing module enable or disable module, an error occur with token security cf image

when unediting this line, error disappear 
13. if (!defined('CSRFCHECK_WITH_TOKEN')) define('CSRFCHECK_WITH_TOKEN', '1'); // Force use of CSRF protection with tokens even for GET

## Environment
- **Version**: 13.0.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.43 (Unix)
- **PHP**: fpm-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.5.5-10.3.21-MariaDB
- **URL(s)**: /admin/modules.php?id=431499&token=ed410aff495059bef82e71a00aa5b3a11be4f972&module_position=20&action=reset&value=modAdherentsPlus&mode=commonkanban&confirm=yes

![image](https://user-images.githubusercontent.com/3135833/98439481-6d213780-20f2-11eb-8a36-0a29b2776817.png)

cc @eldy

**Comment by atm-maxime** [comment]
I can reproduce this when MAIN_SECURITY_CSRF_WITH_TOKEN is set to 1 in Setup > Other, but only if I validate another form in another tab and the coming back on the tab having the module list. But I think this is expected behaviour. Having several forms opened in different tabs will always trigger this error after validating on of the form, because this will "consume" the token.

**Comment by ptibogxiv** [comment]
for me error is always ON (i'm just on this page)

**Comment by eldy** [comment]
@ptibogxiv I can't reproduce. Are you sure you didn't open another tab after opening the page with list of modules ?
Do you have external module that make ajax call on this page ?

**Comment by ptibogxiv** [comment]
> @ptibogxiv I can't reproduce. Are you sure you didn't open another tab after opening the page with list of modules ?
> Do you have external module that make ajax call on this page ?

indeed it was an external module. I try to find the mistake in modules

**Comment by ptibogxiv** [comment]
i find the module

**Comment by atm-maxime** [comment]
@ptibogxiv which one was it ?
