### ISSUE TITLE
expense report regulation 

### ISSUE THREAD

**Issue by isaya07** [Dolibarr/dolibarr#15325]
# Bug
When I create an expense report dolibarr assigns me an old payment, suddenly I cannot pay it

## Environment
- **Version**: 12.0.3

- **OS**: Linux debian 10.4
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MariaDB 5.5.5-10.3.23-MariaDB-0+deb10u1
- **URL(s)**: http://192.168.1.52/expensereport/card.php

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/25980421/98433716-db9dcf80-20c9-11eb-82bd-412ab8d0fda7.JPG)

**Comment by atm-maxime** [comment]
This looks like a wrong database manipulation and not a bug. As if you truncated your expense report table and not the payment table.

**Comment by isaya07** [comment]
Thank you that guided me in finding the solution because it is not a bug there were old records in the database in the llx_payment_expensereport table which dated from tests carried out on these dates, I deleted them and it works. Thank you
