### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Grandjeanfrederic** [Dolibarr/dolibarr#15345]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.26-MariaDB
- **URL(s)**: /admin/system/dolibarr.php?mainmenu=home&leftmenu=admintools_info

## Expected and actual behavior
probleme avec commande fournisseur erreur 500

## Steps to reproduce the behavior
lors de l'ajout d'un Produits prédéfinis à acheter lorsque je l'ajoute j'ai une page blanche erreur 500 qui apparait merci de  me dire ou peux se trouver l'erreur

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Can you paste content of the error.log of apache.

**Comment by Grandjeanfrederic** [comment]
Bonjour,

 

 

Ou ce trouve t il ?

 

 

 

Cordialement

 

 

Fred GRANDJEAN

 

De : Laurent Destailleur <notifications@github.com> 
Envoyé : jeudi 12 novembre 2020 13:33
À : Dolibarr/dolibarr <dolibarr@noreply.github.com>
Cc : Grandjeanfrederic <grandjean.frederic@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [Dolibarr/dolibarr] Bug: (#15345)

 

Can you paste content of the error.log of apache.
