### ISSUE TITLE
Support of multicurrency bank accounts

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#15340]
# Feature Request
Support of multicurrency bank accounts

## Use case
*In the current version of Dolibarr is necessary to register different bank account numbers in Dolibarr, one for each currency managed, even the real bank has only one account number that holds funds in several different currencies.

So at the moment is necessary to declare the same bank account number several times, one per each currency needed to manage.

It would be nice to be able to allow to a bank account to hold several currencies as occurs in the real life, declaring the bank account number only one time, and specify the currencies that can hold the bank account*

**Comment by dolibit-ut** [comment]
I think we would need a kind of sub bank account to handle this.
In real life i think you bank handle it also like that - you have one customer account but for every currency an bank sub account.

**Comment by edupulpillo** [comment]
The banks do not provide a different number of "sub-account", but  you can considerate that solution, since the identification for sub-accounts, can be any char string. Then Dolibarr will be more flexible.
We can configure the currency name as sub-account, or even a different number, as occurs sometimes in some countries.
The approach can be add  to each account "supported currencies". Then the account can be declared as a single currency account or multi-currency account easily, adding the support of more currencies on it. In fact a lot of banks provide you an account supporting one or 2 currencies at the beginning, and later provide you more currencies support, using the same bank account number, but different currency symbols to get the balance of the related coin.

Also this have another benefit, allowing Dolibarr to check that performing payments/receiving funds, are well registered in a bank account that is really supporting the same currency that is in the transaction.

**Comment by edupulpillo** [comment]
It will be nice to have this feature to improve the multicurrency support in Dolibarr
