### ISSUE TITLE
import bank entries with reconciliation

### ISSUE THREAD

**Issue by nathanboschi25** [Dolibarr/dolibarr#15357]
**## Feature Request**
Have the possibility of importing bank writings to reconcile them with the Dolibarr lines and that there is creation when they do not exist in Dolibarr with the possibility of giving a common name to it.
A module is for sale on the DoliStore but is very expensive for what it is and it would be a good implementation for dolibarr

**Comment by jhaand** [comment]
This feature is really necessary for any ERP program that I'm willing to use. I already got quite far with getting our data in Dolibarr, but I think I will now use a different package.

**Comment by JR-Polyline** [comment]
I support this. is there a Dev out there that i could pay to add this functionality?

**Comment by Markusi13** [comment]
There is a bank import module made by ATM-Consulting which could maybe help you guys. Would be cool if it could be added to the core modules in dolibarr, it's up to eldy/atm-consulting team though i guess.

https://github.com/ATM-Consulting/dolibarr_module_bankimport
