### ISSUE TITLE
Export of Resources module generating empty fields for Complimentary Attributes

### ISSUE THREAD

**Issue by sachinsyam** [Dolibarr/dolibarr#15365]
# Bug
[Export of Resources module generating empty fields for Complimentary Attributes. Only default fields are retrieved from database.]

## Environment
- **Version**: [*12.0.3*]
- **OS**: [*Windows 10 Build 18363*]
- **Web server**: [*Apache/2.4.46*]
- **PHP**: [*PHP/7.4.12*]
- **Database**: [*5.5.5-10.5.6-MariaDB*]
- **URL(s)**: [*/dolibarr/exports/export.php?step=5&datatoexport=resource_1*]

## Expected and actual behavior
[*Dolibarr should generate a CSV file with selected fields and their values from database.*]

## Steps to reproduce the behavior
[
1. Create a complimentary attribute for 'Resources'. 
2. Add a new resource with some value for newly created complimentary attribute. 
3. Export resources using export module.
]

**A related bug is also seen with 'Users' module.
If any complimentary attributes are created for users, they are not available for selection while exporting using the export module.**

**Comment by larsborn** [comment]
Hey @eldy, thanks a lot for the Bugfix! Before I'm investing a lot of time to back port it into the current Version (12.0.3 by the time of writing) I'd like to ask if there is already a release planed that includes this fix!

Thanks for all the hard work!
