### ISSUE TITLE
EORI customer code on invoices (URGENT)

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#15379]
**EORI customer code is mandatory on export invoices**, especially with UK customers since Brexit.
It should appear on pdf invoices.
Suggestions :
- add new eori code in llx_societe
- add eori code management in customer card
- print eori customer code in pdf invoice model

**Comment by orebd** [comment]
Hello,

You fcan ix it by using extrafield

**Comment by dolibit-ut** [comment]
Yes, an extrafield is a workaround.
But this field / this number is mandatory for all european trading companies.
And only with extrafield you can not print it everywhere (without additional tools or work).

**Comment by dolibit-ut** [comment]
added  field  'eori'  at  llx_societe
and added object 'eori' to societe/card.php

but now consider if it is easier to call **eori** as **profid7**  ??

**Comment by dolibit-ut** [comment]
other workaround: maybe you can use a 'free' profid field for that at first

**Comment by orebd** [comment]
You're right.
You can modify for example compagnies.lang :
ProfIdXFR=Id. prof. X (EORI) 
NOTE replace N with the first "ProfIdNFR=-" and '-' with Id. prof. X (EORI)
FR is for translation. use your country code instead
using profid7 need to modify pdf.lib and perhaps many file so now it's not an easy way.

**Comment by atm-maxime** [comment]
Done in v13

**Comment by altairis-tof** [comment]
@atm-maxime It's a pleasure to see it's done... what method did you choose ? have you any link on a commit ?

**Comment by atm-maxime** [comment]
I didn't do anything, just saw the field added and working. Check out the mention of @frederic34 on this issue, it links to a discussion about eori.
