### ISSUE TITLE
Bug:  Module Task - Setup - Tasks numbering module

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#15370]
# Instructions
Tasks numbering module is not working as described / as expected
at Module Setup Projects

# Bug
Mask input:   TK-{yy]{mm}-{000@99}
Error:     Error, can't use option @ if sequence {yy}{mm} or {yyyy}{mm} is not in mask

## Environment
- **Version**: 11.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.2.33-1+0~20200807.47+debian9~1.gbpcb3068
- **Database**: MySQL or MariaDB 5.5.5-10.1.47-MariaDB-0+deb9u1
- **URL(s)**: /dolibarr11/htdocs/projet/admin/project.php

[*Files*]

![Dolibarr 11 - Module Setup - Task - Universal Mask - Errror at99](https://user-images.githubusercontent.com/45215329/98949506-1ce21500-24f8-11eb-906f-4b2dfcb6a132.png)

**Comment by Feromsaf** [comment]
on Tasks numbering module, is it possible to make the New task Ref. number editable like New Project Ref.?
