### ISSUE TITLE
Costs on bom lines get set to 0 after editing a bom line

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#15388]
# Bug
When editing lines in a bom, cost per bom line gets set to 0 after each line is edited, Prices are updated when reloading the page.

## Environment
- **Version**: 12.0.3 from demo.dolibarr.org
- **OS**: from demo.dolibarr.org
- **Web server**: from demo.dolibarr.org
- **PHP**: from demo.dolibarr.org
- **Database**: from demo.dolibarr.org
- **URL(s)**: /bom/bom_card.php

### Actual behaviour
Editing a line in a bom will set all costs for all lines to 0. This is a display bug. Prices are updated when reloading the page by clicking on the bom tab, or by trying to delete a line, but not by adding new lines
### Expected behaviour
Cost per line should remain at the values it pulls from the database as you edit the lines

## Steps to reproduce the behavior

- Create a BOM
- Add at least one product
- Cost price for the line appears to be 0
- click on the BOM to reload
- BOM price gets updated with values pulled from the database
- Edit the line and chance quantity. Cost price for the line (and all other lines) gets reset to 0

**Comment by atm-quentin** [comment]
Hello,

Thanks for reporting i'll have a look
