### ISSUE TITLE
Keep the user login even if the login is not required

### ISSUE THREAD

**Issue by CyrilCARGOU** [Dolibarr/dolibarr#15399]
# Feature Request
If the ADHERENT_LOGIN_NOT_REQUIRED option is not set, both values, login and password, are not displayed in the edit user page. Because the values are no displayed, empty values are stored into the user object. 
If the it's logical  because the option is not set,  this way of work clean potential previous values. So in case of temporary switch or in my case when the login is set through RestAPI,  any user edition clean the login value.

## Use case
User account are create by RestAPI (by my IAM). However HR can still edit the user through Dolibarr web interface in order to add some other informations.
Because the Dolibarr login is handel  by OAuth authentication, the ADHERENT_LOGIN_NOT_REQUIRED is not required.
Beacause HR don't managed login, they must no be able to edit it.
With the current way of work, when HR edit some user, the login value is erased.

## Suggested implementation
In order to simple fix the issue I currently use the following fix : 
Source : /var/www/html/adherents/card.php
Line : 10171 (for version 12)

`

		/* Before
		 // Login

		if (empty($conf->global->ADHERENT_LOGIN_NOT_REQUIRED)) {
			print '<tr><td><span class="fieldrequired">'.$langs->trans("Login").' / '.$langs->trans("Id").'</span></td><td><input type="text" name="login" class="minwidth300" maxlength="50" value="'.(GETPOSTISSET("login") ? GETPOST("login", 'alphanohtml', 2) : $object->login).'"></td></tr>';
		}

		// Password
		if (empty($conf->global->ADHERENT_LOGIN_NOT_REQUIRED)) {
			print '<tr><td class="fieldrequired">'.$langs->trans("Password").'</td><td><input type="password" name="pass" class="minwidth300" maxlength="50" value="'.(isset($_POST["pass"]) ?GETPOST("pass", '', 2) : $object->pass).'"></td></tr>';
		}
                */

		//After
		// Login
		$styleNone = "";
		if (!empty($conf->global->ADHERENT_LOGIN_NOT_REQUIRED))
		{
			#In order to keep the data, even if the option ADHERENT_LOGIN_NOT_REQUIRED is not set
			#better way will be to perform it during the object update step.
			$styleNone = 'style="display:none"';
		}

		// Login
		print '<tr '.$styleNone.'><td><span class="fieldrequired">'.$langs->trans("Login").' / '.$langs->trans("Id").'</span></td><td><input type="text" name="login" class="minwidth300" maxlength="50" value="'.(GETPOSTISSET("login") ? GETPOST("login", 'alphanohtml', 2) : $object->login).'"></td></tr>';
		// Password
		print '<tr '.$styleNone.'><td class="fieldrequired">'.$langs->trans("Password").'</td><td><input type="password" name="pass" class="minwidth300" maxlength="50" value="'.(isset($_POST["pass"]) ?GETPOST("pass", '', 2) : $object->pass).'"></td></tr>';
		` 

## Suggested steps
Update the file /var/www/html/adherents/card.php

**Comment by Spitfireap** [comment]
This issue is not fixed. is it possible to reopen ? I may be able to work on this
