### ISSUE TITLE
Changelog is not using semver.

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15400]
When I read the changelog and when I see : 
_***** ChangeLog for 13.0.0 compared to 12.0.0 *****_

I suppose that 13.0.0 has been stabilized.

Is ChangeLog allways _"nightly"_ ?
[Use SEMVER](https://semver.org/lang/fr/spec/v2.0.0.html) ?

**Comment by ksar-ksar** [comment]
V13 is under freeze period : https://www.dolibarr.org/dolibarr-13-freeze.php

Yes Dolibarr version use SEMVER : https://wiki.dolibarr.org/index.php?title=Category:RoadMap

**Comment by matDOTviguier** [comment]
Thank you.
