### ISSUE TITLE
Faute de libellé dans configuration du module Stock / Entrepôt

### ISSUE THREAD

**Issue by PyroShape** [Dolibarr/dolibarr#15403]
# Bug
Dans la configuration du module Stock / Entrepôt il y a un paramètre "Décrémenterr les stocks physiques sur validation des commandes clients" avec une faute de frappe sur "Décrémenter" avec un "r" en fin de mot

## Environment
- **Version**: [*12.0.3*]

**Comment by atm-maxime** [comment]
Thanks for your contribution. Translations are managed by transifex, so the correction must be done on this site and will be updated in Dolibarr language files later.
