### ISSUE TITLE
Add joint files on category objects (not like photo)

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15427]
# Feature Request
Add possibility to join file for Categories in order to send the PDF with any product into this category.

## Use case
I'm selling services like online backups. I want to send automatically PDF of the (sub)category, _the first parent_, in order to mention others services in the same category. We cant adjust depth in order not to limit to the first parent.

## Suggested implementation
Add joint file to category object and then any plugin could refer to it.

## Suggested steps
Add joint file to category object. That's all, I think.

**Comment by matDOTviguier** [comment]
At this day, I have to manually join any file _foreach_ product into _foreach_ category. Time lost.

**Comment by dolibit-ut** [comment]
I think it is a very specific feature. Maybe there are solutions at Dolistore.com

**Comment by dolibit-ut** [comment]
But it was helpful, if we could choose a document/file to send from internal ECM/GED folders.
Not always to upload from local filesystem.

**Comment by matDOTviguier** [comment]
As specific as adding files through products.

**Comment by matDOTviguier** [comment]
What Upload from local filesystem ? DMS folder is localized on the server ...

**Comment by dolibit-ut** [comment]
If you now want to add files to an email, the local file manager opens. 
But you cannot directly select files that are stored with the product or generally in the ECM.

**Comment by matDOTviguier** [comment]
I see ... 

- [x] Understand. 

Good Idea !

**Comment by dolibit-ut** [comment]
I think with categories it is not as specific as with products. 

Categories can be used very differently. 
You can use multiple catgories. We have customers who use 30-50 categories per product.
You can use sub-sub-categories ...   Sometime we have there 7-8 levels.
Somebodies use only the last / lowest (sub-)category. Others use all (sub-)categories in the hierarchy.

But if it can be implemented well, why not.

**Comment by matDOTviguier** [comment]
I see. Closed. Using product with backed file association (on huge numbers).
