### ISSUE TITLE
Formatted text loosing its format.

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15437]
# Bug
Under some condition, we lost HTML formatting with integrated wysiwyg editor (in emails, in some product desctiptions).

## Environment
- **Version**: 12.0.3
- **OS**: Debian last stable updated, upgraded
- **Web server**: apache2 last stable on Debian stable
- **PHP**: php7 last stable on Debian stable
- **Database**: mariaDB last stable on Debian stable
- **URL(s)**: not url-based bug

## Expected and actual behavior
Expected behaviour is to observe formatted text, we get pure text with no format at all.

## Steps to reproduce the behavior
Edit a "Jalon" description, or send a mail via ticket (while beeing seen correct during edition, pure text is recorded thus sended).

## [Attached files]
![Capture1](https://user-images.githubusercontent.com/2384485/99645665-cb81da80-2a4f-11eb-8a53-18ae4c10dab6.PNG)
![Capture2](https://user-images.githubusercontent.com/2384485/99645671-cd4b9e00-2a4f-11eb-87f7-a78e1a67aa0c.PNG)
![Capture3](https://user-images.githubusercontent.com/2384485/99645677-cf156180-2a4f-11eb-9d44-a590279d8197.PNG)
![Capture4](https://user-images.githubusercontent.com/2384485/99645679-d0df2500-2a4f-11eb-8ff5-0245eb8655cd.PNG)

Same effect on TICKET MODULE while generating a mail.

**Comment by eldy** [comment]
It seems you are using an external module called "jalon".
There is a high chance it is related to it, at least for description of lines. Try without it.

For ticket, it may be another trouble. Can you paste a way to reproduce with ticket ?

**Comment by hregis** [comment]
@matDOTviguier this is an external module, contact me by mail

**Comment by matDOTviguier** [comment]
![Capture10](https://user-images.githubusercontent.com/2384485/99959315-1589f980-2d8b-11eb-8cba-37c5b2351c5e.PNG)
Message formatted, seen as formatted in Ticket module.
Sent in "plain text", but only new lines are OK. No color, no HTML attribute.
![Capture11](https://user-images.githubusercontent.com/2384485/99959347-263a6f80-2d8b-11eb-926f-850de228c205.PNG)

**Comment by matDOTviguier** [comment]
@hregis , pse reopen it. Problem occurs in an external module, OK. But seems to be on another place too.

**Comment by matDOTviguier** [comment]
A mail sent via the Ticket module, that is not kown to be external is affectedd too. But a mail sent via a proposal is not.

**Comment by eldy** [comment]
Can you paste a sceenshot ofbpage used to send forlated email from ticket, before sending ?

**Comment by matDOTviguier** [comment]
I bypassed ticket based mail model by forcing TICKET_MESSAGE_MAIL_INTRO & TICKET_MESSAGE_MAIL_SIGNATURE to "space".
Second plan is to NULLize in db, but space is ok.
I don't understand you @eldy 
I'm sending it via the "New message" and "email" check box.

BUT ... A new information.
Model is not shown correctly to.
Those CONST are not displyaing well.
Try to force it in DB and it is good. It is the way they are stored that left html behind the scene I think.

**Comment by matDOTviguier** [comment]
![Capture](https://user-images.githubusercontent.com/2384485/101019367-27c71d00-356d-11eb-97e6-9faa26a431dc.PNG)

**Comment by matDOTviguier** [comment]
![Capture](https://user-images.githubusercontent.com/2384485/101019426-3f9ea100-356d-11eb-8b8d-df63e1d3aef8.PNG)

**Comment by matDOTviguier** [comment]
Message sent, message received, "no html", and doesn't follow string replacement. "Code client".

**Comment by matDOTviguier** [comment]
![Capture](https://user-images.githubusercontent.com/2384485/101019736-ac19a000-356d-11eb-8b39-6ea8724ed07b.PNG)

**Comment by matDOTviguier** [comment]
Works Like a charm in 13.0.0
