### ISSUE TITLE
We can disable some contract contact type that are mandatory

### ISSUE THREAD

**Issue by atm-quentin** [Dolibarr/dolibarr#15431]
# Bug
We can disable some contract contact type that are mandatory : "Commercial (signature)" and "Commercial (monitoring)"

## Expected and actual behavior
Don't allow to disable this contact type

## Steps to reproduce the behavior
Disable this contact type, create a contract

**Comment by ATM-Nicolas** [comment]
Can you please specify the dolibarr version in which you have encountered this problem ? :) :)

**Comment by atm-florianm** [comment]
I can reproduce this issue in Dolibarr 12.0: 
![ksnip_20210122-150316](https://user-images.githubusercontent.com/50440633/105500514-491dcd00-5cc3-11eb-80af-021dc3de79fa.png)

The contract is not created unless I re-enable the disabled contact types. Either they should be made optional or they should be protected against disabling.
