### ISSUE TITLE
Add Notes fields to Document Objet

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15432]
# Why
Joint file cannot be annoted. Thus, only title can help.

# Feature Request
Add "Notes" field to this objetct

## Use case
In DMS Module, we can see Notes attached to a file.

## Suggested implementation
No idea at all.

## Suggested steps
I bid for a junction between notes and files.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/15500
