### ISSUE TITLE
All products appear "Out of sell" and "out of purchase" in the widget last products and services

### ISSUE THREAD

**Issue by BlueGarm** [Dolibarr/dolibarr#15439]
In the dashboard, and particulary in the widget last products and services, all of them are "Out of sell" and "out of purchase" (Hors vente et hors achat ) in the little popup.

![Bug](https://user-images.githubusercontent.com/52456749/99658169-68983f80-2a5f-11eb-8525-44e850b73588.jpg)

I'm using Dolibarr V12

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/15499

**Comment by BlueGarm** [comment]
Thanks
