### ISSUE TITLE
Supplier Reference disapear with a product/service without price with this supplier

### ISSUE THREAD

**Issue by BlueGarm** [Dolibarr/dolibarr#15440]
I don't know if it's a bug or the intended behaviour, but on my suppliers orders, if a want to add a product/service in an order on a specific supplier, when a select au predefined product/service, the field order supplier disapear and a can't specify the proper supplier reference. 
 
![Bug2](https://user-images.githubusercontent.com/52456749/99659131-b3668700-2a60-11eb-8dca-d69510cf8097.jpg)

For the moment my solution is : 
 1 -Add without supplier reference my product
 2 - Edit the line and add the reference

It's annoying, because a huge part of my products can be order in different supplier...

It's not possible to let the field visible, to allow modification (in case of incorrect reference) and/or just addition (if reference is missing in this supplier ?

Thanks,

**Comment by ATM-Nicolas** [comment]
Can you please specify the dolibarr version in which you have encountered this problem ?

**Comment by BlueGarm** [comment]
V12.0.1

**Comment by BlueGarm** [comment]
no solutions ? Thanks
