### ISSUE TITLE
download develop branch brings 12.0.0-alpha

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#15443]
Hey, if I download now the latest develop branch here i have an 12.0.0-alpha system, 
have not the new modules, not the new features like ecm extrafields and no kanban view for modules anymore.
??

**Comment by dolibit-ut** [comment]
just tried again download and installation via github   - https://github.com/Dolibarr/dolibarr/archive/develop.zip
- the same - all files are dated with feb. 10th

**Comment by ksar-ksar** [comment]
Hi,

The zip is from begining of October. 
You need to clone the Git to have the latest one.

**Comment by dolibit-ut** [comment]
If you unpack the zip you can see the files are from February.
And if you install the files you have a Dolibarr 12.0.0-alpha instead of a 13.0.0-beta - like you have with git.

**Comment by dolibit-ut** [comment]
solved now with #15504
