### ISSUE TITLE
Query SQL error BOM

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#15460]
# Bug
[*Query SQL error BOM*]

## Environment
- **Version**: [*12.0.3*]
- **OS**: [*Ubuntu*]
- **Web server**: [*Apache*]
- **PHP**: [*7.2*]
- **Database**: [*mysql 5.7.32*]

## Expected and actual behavior
[*checking the dolibarr.log file I see the following persistent errors coming up*]

DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 51
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 26
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 27
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 26
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 26
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 27
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 27
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 27
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 26
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 25
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 24
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 27
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'
DoliDBMysqli::query SQL Error query: SELECT max(rang) FROM llx_bom_bomline WHERE fk_bom = 41
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'rang' in 'field list'

**Comment by atm-maxime** [comment]
I think it has been fixed here #15141.
Next release of 12 will have this fix

**Comment by erikvanberkum** [comment]
atm-maxime, your are correct i have applied this fix and no longer receive error messages in the log file.
thanks for pointing me in the correct direction.
