### ISSUE TITLE
Modification du prix ttc d'un produit lors de l'accès à la fiche après un import

### ISSUE THREAD

**Issue by werewolf7160** [Dolibarr/dolibarr#15466]
# Bug
Lors de la visualisation d'un produit dans l'onglet "prix de vente", le prix ttc de la fiche principale n'est pas le même que celui de la partie historique

## Expected and actual behavior
![2020-11-20 12_36_34-Produit Telwin chargeur - Prix de vente](https://user-images.githubusercontent.com/31860486/99796061-1f162600-2b2d-11eb-818a-03ea427cea2e.png)
on peux voir que sur cette image le prix de la partie principale n'est pas égal au prix de l'historique, dans un premier temps.
une fois que la page est rechargée 👍 on peut constater que le prix de la fiche principale s'est mis à niveau avec le prix de l'historique.
![image](https://user-images.githubusercontent.com/31860486/99796203-5a185980-2b2d-11eb-8cd4-783abc67c922.png)

## Steps to reproduce the behavior
1. importer un produit en excel ou en csv
2. aller sur la fiche produit
3. cliquer qur l'onglet "prix de vente" pour avoir le même visuel que la même image
4. actualiser la page ou recliquer sur le titre de l'onglet pour avoir le même que la seconde image.

j'ai pu constater que le problème provenais d'un fix de compatibilité pour les anciennes versions : 

> // Il doit au moins y avoir la ligne de prix initial.
// On l'ajoute donc pour remettre a niveau (pb vieilles versions)
//$object->updatePrice($object->price, $object->price_base_type, $user, $object->tva_tx, $object->price_min);
if (!empty($conf->global->PRODUIT_MULTIPRICES)) {
    $object->updatePrice($object->multiprices[1], $object->multiprices_base_type[1], $user, (empty($object->multiprices_tva_tx[1]) ? 0 : $object->multiprices_tva_tx[1]), $object->multiprices_min[1], 1);
} else {
    $object->updatePrice($object->price, $object->price_base_type, $user, $object->tva_tx, $object->price_min);
}

fichier "Price.php" ligne 1452

le code marche pour les produit en "HT" mais pas pour ceux en "TTC".

le problème a été résolu pour moi en changeant le code vers ceci : 

> // Il doit au moins y avoir la ligne de prix initial.
// On l'ajoute donc pour remettre a niveau (pb vieilles versions)
//$object->updatePrice($object->price, $object->price_base_type, $user, $object->tva_tx, $object->price_min);
if (!empty($conf->global->PRODUIT_MULTIPRICES)) {
    $object->updatePrice($object->multiprices[1], $object->multiprices_base_type[1], $user, (empty($object->multiprices_tva_tx[1]) ? 0 : $object->multiprices_tva_tx[1]), $object->multiprices_min[1], 1);
} else {
    if($object->price_base_type == "TTC"){
        $object->updatePrice($object->price_ttc, $object->price_base_type, $user, $object->tva_tx, $object->price_min);
    }else{
        $object->updatePrice($object->price, $object->price_base_type, $user, $object->tva_tx, $object->price_min);
    }
}

**Comment by atm-quentin** [comment]
Hello,
Thanks for reporting, i'll have a look.

**Comment by atm-quentin** [comment]
Quelle version de dolibarr utilisez-vous ? Le problème semble être corrigé depuis le 17 décembre 2020.

**Comment by atm-quentin** [comment]
Je vous invite à mettre à jour votre dolibarr et nous indiquer si votre erreur est toujours d'actualité.

**Comment by werewolf7160** [comment]
je testerai lors de la mise à jour d'un de nos client. merci de votre temps
