### ISSUE TITLE
Dolibarr: 13.0.0-beta - error at Billing and payment area

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#15461]
Dolibarr has detected a technical error.
You use an experimental or develop level of features, so please do NOT report any bugs or vulnerability, except if problem is confirmed after moving option MAIN_FEATURES_LEVEL back to 0.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20201120100206

Dolibarr: 13.0.0-beta - https://www.dolibarr.org
Level of features: 2
PHP: 7.2.33-1+0~20200807.47+debian9~1.gbpcb3068
Server: Apache/2.4.25 (Debian)
 DB: MariaDB 5.5.5-10.1.47-MariaDB-0+deb9u1
OS: Linux v31927.1blu.de 3.16.0-1127.8.2.vz7.151.14 #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

Requested URL: /dolibit-13/htdocs/compta/index.php?mainmenu=billing&leftmenu=
Referer: /dolibit-13/htdocs/comm/index.php?mainmenu=commercial&leftmenu=
Menu manager: eldy_menu.php

Modules/Applications: user, contrat, categorie, takepos, ecm, resource, societe, propal, fournisseur, incoterm, comptabilite, facture, banque, commande, product, projet, agenda
Database type manager: mysqli
Latest database access request error: SELECT f.rowid, f.ref, f.datef as date, f.total as total_ht, f.tva as total_tva, f.total_ttc, f.ref_client, f.type, f.fk_statut as status, f.paye, s.nom as name, s.rowid as socid, s.email, s.code_client, s.code_compta, s.code_fournisseur, s.code_compta_fournisseur, cc.rowid as country_id, cc.code as country_code FROM llx_facture as f, llx_societe as s LEFT JOIN llx_c_country as cc ON cc.rowid = s.fk_pays WHERE s.rowid = f.fk_soc AND f.fk_statut = 0 AND f.entity IN (1) GROUP BY f.rowid, f.ref, f.datef, f.total, f.tva, f.total_ttc, f.ref_client, f.type, f.fk_statut, f.paye, s.email, s.nom, s.rowid, s.code_client, s.code_compta, s.code_fournisseur, s.code_compta_fournisseur, cc.rowid, cc.code
Return code for latest database access request error: DB_ERROR_1038
Information for latest database access request error: Out of sort memory, consider increasing server sort buffer size

![dolibarr-13 0 0-beta_error_at_bill-payment-area](https://user-images.githubusercontent.com/45215329/99781617-5e864780-2b18-11eb-8d56-69d24bd192fa.png)

**Comment by hregis** [comment]
@dolibit-ut this is a problem with your Mysql or Mariadb server configuration, try this solution : 
https://stackoverflow.com/questions/29575835/error-1038-out-of-sort-memory-consider-increasing-sort-buffer-size

**Comment by dolibit-ut** [comment]
Okay, but why is this only at this (bill and payment) area?
And only at a new (empty) Dolibarr 13.0.0-beta? But not at a Dolibarr 11 or 12 installation running on the same server?

**Comment by hregis** [comment]
@dolibit-ut i don't know... how many invoices in your llx_facture table ?

**Comment by dolibit-ut** [comment]
Zero - its a just now fresh installed new dolibarr instance with it own database.
But a Dolibarr 11 installation (on the same server with the same settings) with about 500 entries, 
(about 800 products and about 400 third parties with 2000 contacts) shows no error.

**Comment by hregis** [comment]
@dolibit-ut what is the value of "sort_buffer_size" in your my.cnf ?

**Comment by dolibit-ut** [comment]
- i had sort_buffer_size = 64K 
- and changed now to 256K  and no more error - okay - it works!
- but i wonder how can an empty setting have this error - which i never had before with much bigger databases

**Comment by hregis** [comment]
@dolibit-ut 
my "sort_buffer_size":    sort_buffer_size = 4M
