### ISSUE TITLE
Bug: purchase order can never be set completely received if quantity is more than ordered

### ISSUE THREAD

**Issue by tumeteus** [Dolibarr/dolibarr#15463]
# Bug
Made a purchase order of 15 000 pcs of product A. Actual amount received was 15 300. In the item reception, if amount to be dispatched is changed to actual pcs of received, order will be left in "Partially received" status. In the order page, using button "classify reception" changes nothing even if "Complete or nothing more expected" was selected.

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: apache2handler 7.2.24-0ubuntu0.18.04.7
- **Database**: MySQL or MariaDB 5.7.32-0ubuntu0.18.04.1
- **URL(s)**: /dolibarr/fourn/commande/card.php?id=71

## Steps to reproduce the behavior
Create purchase order of product that has been added in database and has a warehouse and it's quantity is tracked. Receive more items than in original order.

**Comment by dpriskorn** [comment]
Can someone reproduce?

**Comment by erikvanberkum** [comment]
I have issues in this area as well, didn't analyze details yet, now manually once in a while bump in mysql llx_commande_fournisseur  fk_statut from 4 to 5. 

Will check in more detail for a next purchase order but its not happening on all of them.

**Comment by erikvanberkum** [comment]
I have made a purchase order with 8 stock items and 1 service item. Created a reception of the 8 stock items, then the purchase order has the status "Partially received". 

In the next step hit the button "Classify Reception".

Then in the receive mini-form:

Delivery -> selected -> Complete or nothing more expected
Comment -> left blank

After submitting this form the purchase order status remains: "Partially received".

**Comment by FHenry** [comment]
Cant reproduce

**Comment by erikvanberkum** [comment]
I have made a purchase order of Product A en ordered 455 items, actual reception was 456 items. The purchase order got perfectly closed with all items received and stock level for the product was increased with 456 items. I cant reproduce that the actual status stays: "Partially received".

**Comment by tumeteus** [comment]
I tried some moments ago to close an order. Ordered amount 15 000, actual received amount 14 950. Classify reception to complete, but it stays partially received.

Link to a partial log file (with replaced IP address): https://www.dropbox.com/s/t6y8gg55bxffakz/dolibarr_partial.log?dl=1

From log file I got one warning:

2020-12-08 08:05:29 DEBUG   12.123.456.789  BEGIN Transaction
2020-12-08 08:05:29 INFO    12.123.456.789   CommandeFournisseur::Livraison
2020-12-08 08:05:29 DEBUG   12.123.456.789    CommandeFournisseur::Livraison
2020-12-08 08:05:29 DEBUG   12.123.456.789    sql=UPDATE llx_commande_fournisseur SET fk_statut = 5 WHERE rowid = 75 AND fk_statut IN (3,4)
2020-12-08 08:05:29 WARNING 12.123.456.789   Try to add a message in stack with empty message
2020-12-08 08:05:29 DEBUG   12.123.456.789  ROLLBACK Transaction
2020-12-08 08:05:29 DEBUG   12.123.456.789  CommandeFournisseur::fetch

Hope this helps to reproduce or even fix the problem.

**Comment by FHenry** [comment]
It seems that the only action that could cause that is the call of trigger ORDER_SUPPLIER_RECEIVE. Could you try in configuration event/agenda module, tab "auto fill" to uncheck this trigger ?
Do you have any custom module module activated ?

**Comment by erikvanberkum** [comment]
I turned off the ORDER_SUPPLIER_RECEIVE and tried to close an Purchase Order with a Service in the list. 
The PO stays with Status "Partially Received"

2020-12-09 10:23:57 WARN Try to add a message in stack with empty message

No custom modules in this installation

**Comment by FHenry** [comment]
It seems that this a bug actually fix on 12.0branch, will be offically packaged on 12.0.4. I've just discuss on french forum with some users with same bug, they fix it but upgrading their dolibarr from github branch 12.0 directly

**Comment by erikvanberkum** [comment]
Henry thanks for lettings us know. Can you post the commit here were the fix is. So i can patch myself.

**Comment by FHenry** [comment]
https://github.com/Dolibarr/dolibarr/pull/15075

**Comment by erikvanberkum** [comment]
I have copied the file with the 3 commits into my 12.0.3 installation and it looks like it works now. 
htdocs/fourn/class/fournisseur.commande.class.php

the issue can be closed
