### ISSUE TITLE
Ticket Module - no specific contact

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#15469]
# Today

In the **Ticket module**, when a ticket is created : once a customer company is picked, the list of contacts is populated. A contact is chosen by default.

# Feature Request

**User should be free to select "None".** A contact should not be mandatory.

**Comment by matDOTviguier** [comment]
I can create a ticket with a company that has no contact at all.

**Comment by vvnt** [comment]
You are talking about a company without contact. I am talking about company with contacts. Contact is not mandatory because it can be delete after ticket creation. It should be better to let user the choice to not pick a contact (no need or because not yet created in the database and you are answering the phone).

**Comment by matDOTviguier** [comment]
Same operation on a company with many contacts. No contact selected, ticket created well. I was wondering because we are using the same method (still not in db while in phone).

**Comment by matDOTviguier** [comment]
I mean, the contact is not chosen by default.

**Comment by vvnt** [comment]
Yes. It is true as long as you create your ticket from a customer page. However, it does not work when you create a new ticket from the ticket module.

**Comment by matDOTviguier** [comment]
you got it, thank you.
