### ISSUE TITLE
Dolibarr does not warn me when transferring to ledger when payments are not reconciled

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15477]
# Bug
I just found a payment that is entered incorrectly. It was not reconciled but has already been transferred to the ledger. Now I cannot alter it. Thats bad IMO.

## Environment
- **Version**: 12.2

## Expected and actual behavior
I expect a warning. Reconcile first, then register in ledger.

## Steps to reproduce the behavior
Add an invoice plus payment on an account with reconciliation enabled
Bind the invoice and transfer it to the ledger
No warning appears
Try deleting/altering the payment to fit during reconciliation = impossible

**Comment by thegeettanna** [comment]
@egils-consulting, 

Hi, I wanted to understand your accounting workflow. 
We are struggling with our accounting on the Dolibarr and we are using parallel accounting ERP for this reason. 
You can imagine the issues we are facing. Looking for accounting workflows from others. 
Have seen you answer a question of mine earlier so maybe you can help me on this one as well. 

Also, I am looking for a way to register a payment directly to third party without an invoice. 
We have clients that pay upfront before they are invoiced. Once we receive payment, we manufacture/assemble material. It is then packed and then invoiced before being dispatched. 
But as we cannot enter payment without invoice, our banks don't tally in Dolibarr ERP. 
So do you have a solution for that? 

Thank you for the help.

**Comment by dpriskorn** [comment]
> Also, I am looking for a way to register a payment directly to third party without an invoice. We have clients that pay upfront before they are invoiced. Once we receive payment, we manufacture/assemble material. It is then packed and then invoiced before being dispatched. But as we cannot enter payment without invoice, our banks don't tally in Dolibarr ERP. So do you have a solution for that?

That is called a down payment. Doli supports that on invoices. I would create an order, create a down-payment invoice with the amount. Then finish the work and invoice the rest of the amount according to the order-card. Did that make sense?

I recommend asking questions like these in the forum instead to avoid clutter in the issues.
