### ISSUE TITLE
External Site that points to Dolibarr itself generates N menus, if clicked N times.

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15470]
# Bug
When we link an external (via ad-hoc module) site with a link to Dolibarr itself, once clicked, said link open two "upper" Menu. A test is missing somewhere.

**Comment by dpriskorn** [comment]
I don't understand this report at all. Which version? You missed the whole bug template. Please provide more information.

**Comment by matDOTviguier** [comment]
![Capture1](https://user-images.githubusercontent.com/2384485/99958096-07d37480-2d89-11eb-8e63-651161ed4b85.PNG)
I add a link to an external site, witch points to it's source. When dolibarr just adds (include ?) the menu, it is included twice. In fact, N times, with N the number the loop is rolled.
![Capture2](https://user-images.githubusercontent.com/2384485/99958107-0bff9200-2d89-11eb-835b-dccc44c49a68.PNG)
