### ISSUE TITLE
llx_societe_commerciaux.fk_soc should have foreign key constraint on llx_societe.rowid

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#15483]

**Comment by eldy** [comment]
llx_societe_commerciaux.fk_soc "should" have foreign key constraint on llx_societe.rowid
Why "should" ?
We should if it has a dangerous effect to not have it. If we can avoid, we should (having a foreign key systematically on all fields that can have a child is not always the best choice). This solve a lot of side effect, like problem when deleting record, performance issue, mass loading. What can be here the dangerous effect here if we have an orphelin ? Current code seems to manage correctly if an orphelin exists.

Can you describe how you reproduce the bug and the error message you got and how you got it ?

**Comment by StephaneLesage** [comment]
> Why "should" ?

Because:
- it's a good design practice to insure database integrity
- you do it on other tables like llx_socpeople : 173 constraints for 319 table files.
- having broken reference to another table in a DB is like having a pointer to a deleted object in C/C++ and using it have the same catastrophic consequence
- orphan rows are like memory leaks in a language without garbage collector
- it's ugly to leave orphans in the DB, don't you think ?

> We should if it has a dangerous effect to not have it. If we can avoid, we should (having a foreign key systematically on all fields that can have a child is not always the best choice).
>This solve a lot of side effect, like problem when deleting record

Of course, but using foreign keys in this case of simple association like llx_societe_commercials can be even easier.
You probably already know that you can set the foreign key to null or auto-delete the row when the reference is deleted.
So nothing to check or do in the code.
I will modify the PR commit with CASCADE instead of RESTRICT.

>performance issue, mass loading.

Opinions diverge:
https://stackoverflow.com/questions/2618385/does-introducing-foreign-keys-to-mysql-reduce-performance
https://stackoverflow.com/questions/507179/does-foreign-key-improve-query-performance
https://www.experts-exchange.com/articles/4293/Can-Foreign-key-improve-performance.html

>What can be here the dangerous effect here if we have an orphelin ?
>Current code seems to manage correctly if an orphelin exists.

Seems right if it's not used anymore.
But there are also exports/imports beyond the code itself.
Orphans will be exported and imports which don't check the foreign key will create more.

> Can you describe how you reproduce the bug and the error message you got and how you got it ?

I was developping the third-party imports by customer/supplier code (in addition to name).

Actually, it was not working and I didn't understand why I had no errors.
I debugged and saw that the code was not fetching the row id as expected but inserting new rows using suppliercode as fk_soc...
Resulting in a complete useless mess of 12000 rows in the table.

Importing contacts on the contrary lead to errors because of the foreign key constraint.

**Comment by StephaneLesage** [comment]
PR #15484 updated for cascade
