### ISSUE TITLE
Limit size of drop down list

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15492]
# Feature Request
Use pages in order to navigate in drop down lists

## Use case
I have 30K+ items in societe

## Suggested implementation
[TypeAhead](https://twitter.github.io/typeahead.js/examples/)

**Comment by dolibit-ut** [comment]
I am not sure but maybe helps you this:
MAIN_DISABLE_AJAX_COMBOX ► If you have a large number of third parties or products, you can disable the autocomplete feature on the third parties list by setting this constant to 1
??

**Comment by matDOTviguier** [comment]
I read the whole [hidden options list](https://wiki.dolibarr.org/index.php/Setup_Other#List_of_known_hidden_options), no effect at all on this ... problem.

**Comment by matDOTviguier** [comment]
Sometimes list are shown by COMBOBOX, sometines in pure list. Generalize COMBOBOX if you want, but asking for a huge list kills the website.

**Comment by matDOTviguier** [comment]
It's a pain using Ticket on a list of users > 30K.
I need a quick hack !
Ho ! And it's not only ticket. On the proposal module, "Company" ? (Tiers in french) is a pure dropdown.
