### ISSUE TITLE
Old Session Does Not Expire After Password Change

### ISSUE THREAD

**Issue by muskan1706** [Dolibarr/dolibarr#15496]
Vulnerability Name: Old Session Does Not Expire After Password Change

Vulnerable URL: https://myaccount.novafirstcloud.com/index.php

Description :

On changing password only current session using which user changes password only that expires however old sessions in any other browser or device does not expire and remains active.
Reproduction Steps :

To verify the issue :

    Log in to Browser A and make sure to check 'stay logged in to this device' checkbox while logging in.
    Log in to Browser B and go https://myaccount.novafirstcloud.com/index.php
 and change password. Notice that Session on Browser A will remain active and does not expire.

Impact:

Due to this bug, there is no way for the victim to revoke access of attacker if account has been already compromised.

**Comment by eldy** [comment]
TODO: Dolibarr must suggest a mode to manage session in database (instead of a management by the system) so we will be able to clean session after a password change.

**Comment by joanlouis** [comment]
if we hash a timestamp of the last vaild moment (change password or disconnect all) in the session and the db it can do the job without db season handler.
what do you think about eldy?

**Comment by eldy** [comment]
@joanlouis What you suggest is:
- Save into session the moment when you create the sessions.
- Storing into database the date of last password change of user or disconnect all (field datelastpassvalidation into llx_user)
But then ? This will not destroy open session. May be you mean, we should also compare the value of date of session open and the date of last password change at each access ? On each url request, we compare the value on date used to create session with date of last password change if lower, we destroy session.
The is what you are thinking ? It seems it will work and is easier to implement.

**Comment by joanlouis** [comment]
Yes this is what i think and we can esealy invalidate all user sessions. We just need to update the timestamp

**Comment by joanlouis** [comment]
@eldy do you want I make a PR for it or you will make it ?

**Comment by muskan1706** [comment]
Hello team
any reward for this finding?
Regards 
Muskan

**Comment by daraelmin** [comment]
> eldy do you want I make a PR for it or you will make it ? 

Hi @joanlouis,

Could you please propose the PR for this one? I usually would have give a try but I don't know how it should be implemented.

Cheers

**Comment by Steiner-254** [comment]
An interesting P4.

**Comment by Rulebreker** [comment]
`k`

**Comment by eldy** [comment]
Fixed in v17
