### ISSUE TITLE
Computed extra fields using $object don't work in list.php (only in card.php)

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#15502]
# Bug
Product list : computed extra fields with sql don't work correctly

## Environment
- **Version**: 12.0.3 and 13.0.0-beta
- **OS**: Linux srv-dolibarr 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /product/list.php
Select 

## Steps to reproduce the behavior
Go to product list.

Add a computed extra-field column and apply.
**If it's not possible to compute values in the list, then please don't allow the user to select these columns...**

**Or maybe it's my expression which does not work in the product list:**
(($result = $db->query('SELECT sum(ps.reel) as stk FROM llx_product_stock as ps JOIN llx_entrepot as e ON ps.fk_entrepot=e.rowid WHERE ps.fk_product='.$object->id.' AND e.ref LIKE \'CLAIX%\';')) && ($row = $db->fetch_object($result))) ? intval($row->stk) : -999

**It shows -999 :**
![image](https://user-images.githubusercontent.com/69054301/100074490-1aa88080-2e3f-11eb-8b11-bf9c8de0278e.png)

**The values are correctly computed in the product card :**
![image](https://user-images.githubusercontent.com/69054301/100074807-7d9a1780-2e3f-11eb-951f-895f3f80703f.png)

**Comment by StephaneLesage** [comment]
~~@eldy today's head solves my problem for v12 and v13. What did you change ?~~
My bad, the columns were not shown. It's till not working.

**Comment by StephaneLesage** [comment]
I found why it's working in product card and not in the list.
It's because I use $object :
- in card.php, it is of course the object to view
- in list.php, it is not an item in the list, but a static object for hooks and extrafields attributes.

Is this supposed to be doable and work ?

I made it work with a hack:
```
$tmp = &$object;
$object = &$product_static;		// Set $object context for computed fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_print_fields.tpl.php';
$object = &$tmp;
```
@eldy What do you think of this ? Or shall we store the list rows in $object instead of $product_static ?

Can the developpers agree to a standard way to access the object from computed extrafields ?

**Comment by frederic34** [comment]
What do you think of that :
`(($reloadedobj = new Product($db)) && ($reloadedobj->fetch($object->id ? $object->id : $product_static->id)) ? $reloadedobj->stock : '-999'`

**Comment by coding1wolf** [comment]
@StephaneLesage 
Hello, did you finally solve it? I´m trying to compute a field by multiplying Stock Reel with another field but it doesn´t work

**Comment by sunshuvo** [comment]
> I found why it's working in product card and not in the list.
> It's because I use $object :
> 
> * in card.php, it is of course the object to view
> * in list.php, it is not an item in the list, but a static object for hooks and extrafields attributes.
> 
> Is this supposed to be doable and work ?
> 
> I made it work with a hack:
> 
> ```
> $tmp = &$object;
> $object = &$product_static;		// Set $object context for computed fields
> include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_print_fields.tpl.php';
> $object = &$tmp;
> ```
> 
> @eldy What do you think of this ? Or shall we store the list rows in $object instead of $product_static ?
> 
> Can the developpers agree to a standard way to access the object from computed extrafields ?

Did you solve it? I'm facing the same issues on the version 11.
