### ISSUE TITLE
zip version on githup not the last develop version

### ISSUE THREAD

**Issue by defrance** [Dolibarr/dolibarr#15504]
the last version is V12 ... if we need to download a last version of dolibarr develop we need to use only git hub.
something broken?

**Comment by eldy** [comment]
What do you mean ? Github provide a link to download zip for each branch. For develop, it is

https://github.com/Dolibarr/dolibarr/archive/develop.zip

**Comment by defrance** [comment]
![apE5MgFIJW](https://user-images.githubusercontent.com/1179011/100089873-ad9ee600-2e52-11eb-8ab5-b1b7388ae9a3.png)
![chrome_sczZPvWFnS](https://user-images.githubusercontent.com/1179011/100089888-b099d680-2e52-11eb-8ded-727445ee2dab.png)

**Comment by eldy** [comment]
A tag with the name "develop" was created making the download of branch taking another version.
I deleted the tag "develop" so you should get branch develop now.

**Comment by dolibit-ut** [comment]
same what i posted at #15443
