### ISSUE TITLE
Extrafields not transferred from order to expedition

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#15506]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Extra fields from order not transferred to expedition. Worked in Dolibarr 11

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**:  Apache/2.4.18 (Ubuntu)type and version*
- **PHP**: 7.0.33-37+ubuntu16
- **Database**: MySQL or MariaDB 5.7.32-0ubuntu0.16.04.1
- **URL(s)**: /htdocs/expedition/card.php?id=

## Expected and actual behavior
Extra fields made in orders should be transferred to Expeditions

## Steps to reproduce the behavior
Worked in version 11. Seems broken now.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![ScSh1](https://user-images.githubusercontent.com/43514101/100099358-a16d5580-2e5f-11eb-920e-6ec924160ee0.png)
![ScSh2](https://user-images.githubusercontent.com/43514101/100099370-a3cfaf80-2e5f-11eb-977e-118481a84df2.png)

**Comment by atm-quentin** [comment]
@eldy
