### ISSUE TITLE
It should not be possible to import computed extra-fields

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#15503]
# Bug
It should not be possible to import computed extra-fields.

## Environment
- **Version**: 12.0.3 and 13.0.0-beta
- **OS**: Linux srv-dolibarr 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /product/list.php
Select 

## Expected and actual behavior
Am missing something, or does it just makes no sense ?

## Steps to reproduce the behavior
Use import tool on a table with computed extra-fields.

In my case, it's the product table, it computes special stocks from specific warehouses:
![image](https://user-images.githubusercontent.com/69054301/100076105-1da47080-2e41-11eb-9316-c10a94541e71.png)

Import wizard step 2, download example file:
![image](https://user-images.githubusercontent.com/69054301/100075932-e6ce5a80-2e40-11eb-86c2-eef6024703ef.png)

Import wizard step 4:
![image](https://user-images.githubusercontent.com/69054301/100075727-a1aa2880-2e40-11eb-9ae7-8e3a7f103c9d.png)

**Comment by eldy** [comment]
This is to prepare a future feature "computed fields that will be stored" (after computation, value will be stored into database).
Do you experience trouble currently ? Does this block the import.

**Comment by StephaneLesage** [comment]
> This is to prepare a future feature "computed fields that will be stored" (after computation, value will be stored into database).

This "cache" feature was also on my mind, but how do you know when you need to recompute a value, as it can depend on anything in the database ?

Idea: add an explicit SQL type for computed extra-fields => use triggers !
That would be a killer feature.

If I understand correctly, value would not be imported, but an import would compute the field.
So exposing and selecting the column would mean "please recompute the value" ?
It should then be written explicitely on the import page to be clear to the user.
We still should hide the column in the example file.

> Do you experience trouble currently ? Does this block the import.

I didn't try to import them, so no trouble here.
It's just that it does not make sense to import something that is supposed to be computed.
For now, these fields should be hidden in the import pages.
