### ISSUE TITLE
print delivery address 

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#15513]
# Instructions
printing the delivery address 
is not behaving as expected

# Bug 
there is always the first line of the third party
but sometimes you dont want this

and if you want you can add by contact

**Comment by john-botella** [comment]
Hi

You can use this hidden conf MAIN_USE_COMPANY_NAME_OF_CONTACT to Use contact name and information rather than company

**Comment by dolibit-ut** [comment]
Hey, thank you, 
but I think this affects only the sender - not the recipient 
or am I mistaken there?

**Comment by john-botella** [comment]
Hi

It's for the recipient (normally)

Best regards.

**Comment by dolibit-ut** [comment]
Thank you!
