### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by tumeteus** [Dolibarr/dolibarr#15528]
# Bug
[*Short description*]

Free text item purchase order cannot be set to received. "Classify reception" button does not affect the state of the order.

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: apache2handler 7.2.24-0ubuntu0.18.04.7
- **Database**: MySQL or MariaDB 5.7.32-0ubuntu0.18.04.1
- **URL(s)**: /dolibarr/fourn/commande/card.php?id=65

## Expected and actual behavior
Classifying reception as complete should set status of the order as complete. Instead, status stays at "Standby reception".

## Steps to reproduce the behavior
1. Make a free-text item purchase order
2. Try classify reception.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Does the line in your purchase order has the type product or service ?
