### ISSUE TITLE
Thousand separator and decimals to Chile

### ISSUE THREAD

**Issue by danndaghost** [Dolibarr/dolibarr#15524]
Hello!

I use dolibarr v12.0.3 to Chile

Here use thousand separator . (dot) and non decimal separator and non decimal numbers.
Add this code in /core/lib/functions.lib.php line 4727

` if($thousand == '.' and $dec == '' and $conf->global->MAIN_MAX_DECIMALS_SHOWN == 0)
          $amount = str_replace($thousand, '', $amount); `

**Comment by erikvanberkum** [comment]
Not sure why you want to add some extra code for this. 
You can overwrite your translation key: SeparatorDecimal and use either , or .

In setup go to dictionaries and search for "SeparatorDecimal"
you also might want to adjust  the translation for: "SeparatorThousand"

A more permanent solution for other users would be to fix the translation for Chile Spanish on 
[https://www.transifex.com/dolibarr-association/dolibarr/language/es_CL/](https://www.transifex.com/dolibarr-association/dolibarr/language/es_CL/)

**Comment by danndaghost** [comment]
I do it, but SeparatorDecimal "," and SeparatorThousand "." generate a bug to edit a price or tax, for example CLP 14.000, saved CLP 14

https://www.transifex.com/dolibarr-association/dolibarr/language/es_CL/ 404 not found...

**Comment by eldy** [comment]
This has been fixed for version 12.0.4 and 13.0 (soon available).
For the moment, just remove the . in thousand separators to enter large numbers.
