### ISSUE TITLE
Hide selector "model" (PDF model) if only 1 model available

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#15536]
# Feature Request
We have only one PDF model for most data types  activated.
If only one (1) model is available the select field should be hidden automatically

Is there any negative to this? Please someone give a hint or a postive reply. So I can start doing this soon

**Comment by dolibit-ut** [comment]
Hello, or maybe as option (setup other):
main_document_type_activ = 1 disable/hide selection box

**Comment by cfoellmann** [comment]
I think this is so low a priority that this can be closed for now
