### ISSUE TITLE
Inventory function not yet operational on V12.0.3.

### ISSUE THREAD

**Issue by zuiko** [Dolibarr/dolibarr#15547]
# Current environment
Version: 12.0.3
OS: Linux Debian 3.16.64-2 (2019-04-01) x86_64
Web server: Apache/2
PHP: PHP 5.6.40
Database: MySQL or MariaDB 5.6.48-log
URL(s): /product/inventory/inventory.php?id=2

# Feature Request
*The Inventory function is not yet fully operational on V12.0.3.*

## Use case
*I made the inventory function appear in the inventory management by setting MAIN_FEATURES_LEVEL to 2.
The heading Inventory then appears in the right menu under the heading products.
You can create the inventory card without any problem and list the created inventories.
On the other hand, in the inventory tab itself of a given inventory, the header with titles of a table of products is well displayed but I could not see any product in this table.*
image
https://www.dolibarr.fr/forum/uploads/default/original/2X/a/a87f932e2259cbc064676da51bb59bf7b535a562.png
The inventory function is therefore in an unusable state.
## Suggested implementation
*It seems curious to me that it is not operational for an ERP version 12 knowing that it is essential for stock management.
An inventory with possible entry of product references with the hand shower and a barcode reader would be ergonomic.*

## Suggested steps
*The implementation is well under way, maybe there is not a lot of work left to do?*

**Comment by zuiko** [comment]
Sorry for the link, it's best to see directly :
![image](https://user-images.githubusercontent.com/1511011/100343584-d7394800-2fdf-11eb-9ed3-6c85ce4086d9.png)

**Comment by StephaneLesage** [comment]
> _It seems curious to me that it is not operational for an ERP version 12 knowing that it is essential for stock management. An inventory with possible entry of product references with the hand shower and a barcode reader would be ergonomic._

I couldn't agree more. Still experimental in v12 without batch numbers.
That's one main of the many blockers for us to adopt dolibarr rapidly. We just can't import our stock.
We start using it this week, but prospection only for now. CRM for customer quotes soon. Then we plan to transition next year with ATM...
Fortunately there are some good news, projects for example.
We were looking if it was possible to link them to additionnal companies.
We went to extra-fields and added 2 of them with type "link to object" -> class Societe.
It just works. It's magical to be able to do that in 1 minute :-)

**Comment by dpriskorn** [comment]
I also need this and would like to work on it. For now I'm planning to use my Python Dolibarr API to do the job.

**Comment by dpriskorn** [comment]
> Fortunately there are some good news, projects for example.
> We were looking if it was possible to link them to additionnal companies.
> We went to extra-fields and added 2 of them with type "link to object" -> class Societe.
> It just works. It's magical to be able to do that in 1 minute :-)

I totally agree. Coming from Odoo the extrafields are dead simple and effective to use. Documentation is pretty good too. I have 25 extrafields on my products module and populate them using Python when I import from sello.com. It works well. :)

**Comment by atm-maxime** [comment]
The inventory feature is going stable in next to come v 14. Some testing to finish debugging is welcome.
As always, an open-source projects relies on its contributors...
