### ISSUE TITLE
Errors/Restrictions/SQL breach with code of new extra-field

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#15558]
# Bug
Errors/Restrictions with code of new extra-field

## Environment
- **Version**: 12.0.3 and 13.0.0-beta
- **OS**: Linux srv-claix-debian 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /societe/admin/societe_extrafields.php?action=create#newattrib

## Steps to reproduce the behavior
Go to module config ->create a new extra-field.
Choose label, type, code, size and confirm.
We created 2 without any trouble.
Then a last one, and my colleague chose 'in' for the code, as short for 'Installer' 
He got a freaking cryptic error, that he really didn't understand because he just created 2 similar fields:
![image](https://user-images.githubusercontent.com/69054301/100403109-3fc70a00-305e-11eb-8206-9aeee133f68e.png)

I didn't get it at first, but then, as a developper, I could understand that the code chosen by the user was a SQL keyword !!!

0. this may be a SQL injection vulnerabilty ?
1. maybe quoting/escaping the code name is a solution
2. if not, then we must warn the user of the restriction in the comment AND look for SQL keywords to display a proper error.

**Comment by matDOTviguier** [comment]
I think that you can move your bug to a security breach.
