### ISSUE TITLE
Error message wrong

### ISSUE THREAD

**Issue by pascallannebere** [Dolibarr/dolibarr#15551]
In GPAO module when I create an FO  I have a message « Column ‹ tms › cannot be null »

**Comment by eldy** [comment]
Which version of Dolibarr do you use ? Can you provide a screenshot ?
Try to run this request:

ALTER TABLE llx_mrp_mo MODIFY COLUMN tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
