### ISSUE TITLE
NEW mass action in prospect list to change status of many prospects at once

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#15559]
# Feature Request
Feature request: new mass action in prospect list to change status of many prospects at once

## Use case
You want to select many prospects to contact to assign to assign the task to a sales representative.

## Suggested implementation
Add a status combo box above the list to choose the new status.

**Comment by matDOTviguier** [comment]
Status, why not. But why don't ask for a MAJOR improve, letting user apply a SQL statement equivalent to INSERT .... ON DUPLICATE KEY UPDATE on the selection ?

A user could modify anything at once. Commercial ? Anything else ...
