### ISSUE TITLE
Filter by gender in Users list don't work correctly

### ISSUE THREAD

**Issue by StephaneLesage** [Dolibarr/dolibarr#15557]
# Bug
Filter by gender in Users list don't work correctly

## Environment
- **Version**: 13.0.0-beta
- **OS**: Linux srv-claix-debian 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /projet/list.php?leftmenu=projets
Select 

## Steps to reproduce the behavior
Open config->users list.
Add gender column.
Filter only females : OK
Filter only male: BUG it shows both (not other and null)

**Comment by eldy** [comment]
Seems fixed in current branch 12.0

**Comment by StephaneLesage** [comment]
> Seems fixed in current branch 12.0

You're right. Only 13beta is affected by this bug.
Maybe with the introduction of "Other" gender.
