### ISSUE TITLE
CVS and Excel import problems

### ISSUE THREAD

**Issue by nekbv** [Dolibarr/dolibarr#15560]
1. # Bug Excel (LibreOffice)
[*Warning: tempnam(): open_basedir restriction in effect. File(C:\WINDOWS\TEMP) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\modules\import\import_xlsx.modules.php on line 219
Warning: ZipArchive::open(): Empty string as source in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\phpexcel\Classes\PHPExcel\Writer\Excel2007.php on line 239
Warning: ZipArchive::open(): Empty string as source in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\phpexcel\Classes\PHPExcel\Writer\Excel2007.php on line 240
Fatal error: Uncaught PHPExcel_Writer_Exception: Could not open for writing. in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\phpexcel\Classes\PHPExcel\Writer\Excel2007.php:241 Stack trace: #0 C:\dolibarr\www\dolibarr\htdocs\core\modules\import\import_xlsx.modules.php(221): PHPExcel_Writer_Excel2007->save(false) #1 C:\dolibarr\www\dolibarr\htdocs\imports\class\import.class.php(228): ImportXlsx->write_footer_example(Object(Translate)) #2 C:\dolibarr\www\dolibarr\htdocs\imports\emptyexample.php(108): Import->build_example_file('xlsx', Array, Array, 'produit_1') #3 {main} thrown in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\phpexcel\Classes\PHPExcel\Writer\Excel2007.php on line 241*]

 ## Environment
- **Version**: [*12.0.3*]
- **OS**: [*Windows 10*]
- **Web server**: [*Windows 10*]
- **PHP**: [*7.3.12*]
- **Database**: [*MySQL or MariaDB 5.5.5-10.4.10-MariaDB*]

## Expected and actual behavior
[*When I try to import products with LibreOffice, I receive these errors.*]

2. # Bug Excel (Open Office/Microsoft Excel)
[*Excel cannot open the file 'filename.xlsx' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.*]

## Environment
- **Version**: [*12.0.3*]
- **OS**: [*Windows 10*]
- **Web server**: [*Windows 10*]
- **PHP**: [*7.3.12*]
- **Database**: [*MySQL or MariaDB 5.5.5-10.4.10-MariaDB*]

## Expected and actual behavior
[*When I try to import products with OpenOffice, I receive these errors.*]

3. # Bug CSV (LibreOffice)
[*At step 5 when I try to import my products, I receive this error:
*** Linie 1    > Data truncated for column 'price' at row 1**
--*]

## Environment
- **Version**: [*12.0.3*]
- **OS**: [*Windows 10*]
- **Web server**: [*Windows 10*]
- **PHP**: [*7.3.12*]
- **Database**: [*MySQL or MariaDB 5.5.5-10.4.10-MariaDB*]

## Expected and actual behavior
[*I know this problem was solved some years ago. 
The error appears when I put prices with value 0.
For exaple: PENCIL , 0.15Eur.*]

**Comment by matDOTviguier** [comment]
It is not linked with your bug, but I definitely don't understand why it is possible to import/export in xl* format when we are ok with csv ... May your explain that to me ?

**Comment by nekbv** [comment]
> It is not linked with your bug, but I definitely don't understand why it is possible to import/export in xl* format when we are ok with csv ... May your explain that to me ?

Also CSV have problems.
Bug CSV (LibreOffice)
[At step 5 when I try to import my products, I receive this error:
*** Linie 1    > Data truncated for column 'price' at row 1*
--*]

Environment
Version: [12.0.3]
OS: [Windows 10]
Web server: [Windows 10]
PHP: [7.3.12]
Database: [MySQL or MariaDB 5.5.5-10.4.10-MariaDB]
Expected and actual behavior
[I know this problem was solved some years ago.
The error appears when I put prices with value 0.
For exaple: PENCIL , 0.15Eur.]

**Comment by eldy** [comment]
The column price must contains a numeric value. Try to make import with value
0.15
instead of 
0.15eur

**Comment by nekbv** [comment]
I've found the problem. 
I used commas not dots.

I our country we use commas on math or prices...
