### ISSUE TITLE
Bug: supplier order card.php is missing the order date

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15573]
# Bug
order date does not appear

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.13
- **Database**: PostgreSQL 12.5
- **URL(s)**: /fourn/commande/card.php

## Expected and actual behavior
the date is in the database and shown in the list of orders, so showing it should be easy

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by dpriskorn** [comment]
I'm unfortunately very busy. I will report back after my next upgrade, but it might take a long time.

**Comment by dolibit-ut** [comment]
Hello,

i can not see a field Date (date of creation) at Dolibarr 12.0.3 or Dolibarr 13.0.0-beta
![Screenshot_2020-12-01  Dolibarr 13 0 0-beta Purchase Order - Supplier Order - no field date](https://user-images.githubusercontent.com/45215329/100739546-822e7500-33d7-11eb-8b15-8d83a55615b4.png)
