### ISSUE TITLE
Feature: unidentify customers

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15591]
# Feature Request
Ability to remove identifying information after a period of time

## Use case
According to GDPR I have to scrub identifying information about customers when its no longer needed. In sweden im required by the accounting law to keep it in 7 years if I remember correctly.

After 7 years its illegal to retain the information

## Suggested implementation
Search based on latest invoice/payment of customer older than x years

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by john-botella** [comment]
Hi

Currently an experimental module  "datapolicy" for GDPR exist in Dolibarr, you need to set  hidden conf MAIN_FEATURES_LEVEL to 2.
But this is an experimental module so use this carefully (by testing on copy of you branch).
