### ISSUE TITLE
V12.0.3 problem at the validation level for receipt of the order supplier ! / problème au niveau de validation pour réception de la commande fournisseur

### ISSUE THREAD

**Issue by Sigmamatt** [Dolibarr/dolibarr#15608]
# Bug
**problem at the validation level for receipt of the order supplier ! / problème au niveau de validation pour réception de la commande fournisseur

if I click on the button classify reception there is a rollback and no change of status nor error message**
**Si je clique sur le bouton classer reception il y a un rollback et aucun changement de status ni message d'erreur**

## Environment
- **Version**: 12.0.3
- **OS**: Debian 4.19.152-1 (2020-10-18) x86_64
- **Web server**:  Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /dolibarr/fourn/commande/card.php?id=6&action=classifyreception#classifyreception

## Expected and actual behavior
...

## Steps to reproduce the behavior
...

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![Inkedpage1_LI](https://user-images.githubusercontent.com/75318324/100787644-3ea62c00-3414-11eb-9394-c3a03c74290d.jpg)
![page2](https://user-images.githubusercontent.com/75318324/100787656-449c0d00-3414-11eb-8209-af05fa5e77f1.png)

[dolibarr (3).log](https://github.com/Dolibarr/dolibarr/files/5627805/dolibarr.3.log)

**Comment by zuiko** [comment]
On my side (V12.0.3), I think there is a bug but the behaviour seems a little bit different:
After classifing the receipt, the products are going to stock which is well incremented (very important).
The status is then this:
![image](https://user-images.githubusercontent.com/1511011/100859475-8ddd7280-348f-11eb-8c44-b9f5c0c0ca57.png)
but it's the "create a reception" button which is in green (not "classified the reception") which seems also odd to me...

**Comment by erikvanberkum** [comment]
This topic is also partly described in the following issue #15463

**Comment by FHenry** [comment]
Can't reproduce

**Comment by Sigmamatt** [comment]
https://github.com/Dolibarr/dolibarr/pull/15075

you can close this issue its good in 12.0.4
