### ISSUE TITLE
disable/hide field weight - for products

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#15609]
# Feature request
need an option to disable/hide the field `weight` at product card

idea:
a new variable
PRODUCT_DISABLE_WEIGHT

**Comment by erikvanberkum** [comment]
I think dimensions and weight needs some rethinking. 
Weight is used in the shipping module, so their is a potential conflict when disabling.

Further, products have a weight and dimensions of their own, but their packaging has an other weight  and dimensions.
To complicate things further you can have a with multiple items which again results in another weight and dimensions

**Comment by dolibit-ut** [comment]
Hey,
it is an option for companies that do not maintain weights for products.
Many companies have products without weights.
And dimensions can already be hidden.
It is only an option - to hide these field.

For shipping / packaging you can use maybe Virtual Products/Kits.
