### ISSUE TITLE
TakePOS message d'erreur catégorie

### ISSUE THREAD

**Issue by Cyrix126** [Dolibarr/dolibarr#15604]
En allant sur TakePOS , un message d'erreur est affiché:
"TakePOS a besoin des catégories de produits pour fonctionner"

Le module catégorie/tag est activé, le tag produit est sélectionné dans la configuration de TakePOS et il existe des produits dans cette catégorie.

D'ailleurs l'utilisation de tags pour TakePOS était facultatif dans dolibarr 12.0.3 et d'après la description de Catégorie Racine des produits à vendre:
"Si défini, ..."
Indique que cette option n'est pas obligatoire.

L'erreur peut être ignoré et l'utilisation de la caisse ne s'en trouve pas impacté (il trouve bien les produits et l'erreur ne s'afiche pas lors d'une nouvelle vente mais seulement si la page est rafraîchie.

## Environment
- **Version**: 13.0.0-beta
- **Web server**:nginx/1.14.2
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1

**Comment by dolibit-ut** [comment]
`translation to english:`

When you go to TakePOS , an error message is displayed:
"TakePOS needs product categories to work".

The category/tag module is activated, the product tag is selected in the TakePOS configuration and there are products in this category.

By the way the use of tags for TakePOS was optional in dolibarr 12.0.3 and according to the Root Category description of products for sale:
"If defined, ..."
Indicates that this option is not mandatory.

The error can be ignored and the use of the checkout is not impacted (it finds the products well and the error is not displayed during a new sale but only if the page is refreshed.

Translated with www.DeepL.com/Translator (free version)

**Comment by dolibit-ut** [comment]
Hello,

i have just now tested it with TakePOS in Dolibarr 12.0.3 and in Dolibarr 13.0.0-beta
and have no errors.

**Comment by Cyrix126** [comment]
Reinstalled and configured takepos before going in it. Didn't have errors.

**Comment by dolibit-ut** [comment]
If it now works for you?
Then please set [Close Issue].

**Comment by info-techsolutions** [comment]
Please, I am having same issue with 12.0.4. I have tried installing a fresh instance configured all TakePOS required setting, then launch but it still pop up : "TakePOS needs product categories to work".

Kindly assist on the way forward

**Comment by dolibit-ut** [comment]
Do you tried to create one product category - e.g. 'pos' ?

**Comment by daraelmin** [comment]
Same issue
I have noticed that when I click on the catégory product button, the popup shows the third party, not the product

Édit : I was confused by the name of m'y category "subscription" and an other button "subscription". The subscription button shows the third party list, the service "subscription" is show only when searching it

**Comment by daraelmin** [comment]
@Cyrix126 The issue should be re-opened since I've experimented this on both 12.0.4 and 13.0.0

**Comment by daraelmin** [comment]
May this issue occur only for association ?

I mean the main service of my installation is the subscription witch is stored in services and in adherent module. Could be this the problem ?

**Comment by daraelmin** [comment]
I've found a workaround.

To avoid warning message
You **MUST** define at least one category product (empty is ok)
BUT 
You **MUST** let the "root category of sell product" empty in the configuration panel of the TakePOS module (htdocs/takepos/admin/setup.php)

**Comment by daraelmin** [comment]
If you limit to one category product it doesn't work. 

So I think the issue has something to do with this code (line 126 of takepos/index.php)

```
$categories = $categorie->get_full_arbo('product', (($conf->global->TAKEPOS_ROOT_CATEGORY_ID > 0) ? $conf->global->TAKEPOS_ROOT_CATEGORY_ID : 0), 1);

if ($conf->global->TAKEPOS_ROOT_CATEGORY_ID > 0)
{
	foreach ($categories as $key => $categorycursor)
	{
		if ($categorycursor['id'] == $conf->global->TAKEPOS_ROOT_CATEGORY_ID)
		{
			$levelofrootcategory = $categorycursor['level'];
			break;
	}
	}
}
```

[https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/takepos/index.php](url)

**Comment by daraelmin** [comment]
@Cyrix126 this issue can be closed cause eldy has commited a fix for this.
 (https://github.com/Dolibarr/dolibarr/commit/f4c23654f84d9997782d421ecffe57f6c1d6ea4c)

Apparently, there must be a sub category, even empty, to use takepos. I don't know why.

If we try to correct this (be able to use takepose without category product or to use it within the last subcategory level) it should be referenced as a enhancement (new feature) not an issue (bug).

Cheers
