### ISSUE TITLE
Changelog link points to actual release, not proposed upgrade

### ISSUE THREAD

**Issue by maxauvy** [Dolibarr/dolibarr#15618]
# Bug
When going in the admin section to check for updates, if an update is proposed, I usually click the changelog link to see if there's something critical/urgent... with this update.
This leads to the "old changelog", that is to say the diff between 12.0.1 and 12.0.2, and not to the diff between 12.0.2 (installed version) and the 12.0.3 (proposed version).

## Environment
- **Version**: 12.0.3 (but present for several releases)
- **OS**: Linux (Debian 10 "Buster" x64)
- **Web server**: nginx/1.14.2
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MariaDB 10.4.15
- **URL(s)**: mydomain.tld/admin/system/dolibarr.php?mainmenu=home&leftmenu=admintools_info

## Expected and actual behavior
The "See changelog" link shoul point to the diff between installed version and proposed update, not to the diff related to a previous upgrade.

On the image here, the link points to https://raw.githubusercontent.com/Dolibarr/dolibarr/12.0.2/ChangeLog while I was hoping to parse https://raw.githubusercontent.com/Dolibarr/dolibarr/12.0.3/ChangeLog 

![image](https://user-images.githubusercontent.com/2428307/100875627-8c6b7480-34a6-11eb-87ba-c104591ba0b0.png)

Thanks all for this great tool btw <3

**Comment by dolibit-ut** [comment]
I can see.

I thought  $newversion  should solve that - but then it refers to changelog 8.0.6  
?

**Comment by eldy** [comment]
The link "See ChangeLog" is the link to know what has changed in your current version. This is the expected behaviour but it is not clear so i pushed a fix.
