### ISSUE TITLE
Ticket is not sending to user, but to author

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15629]
# Bug
When you create a ticket from the inner page, when you ask in french "Notifier le tiers", it is the author that is notified, not the user.

## Environment
- **Version**: 12.0.3
- **OS**: debian 10 last stable
- **Web server**: apache2 last stable
- **PHP**: php7 last stable
- **Database**: mariaDB last stable
- **URL(s)**: url independant

## Expected and actual behavior
Expected : Mail sent to the email of the company whe no contact is selected
Actual : Mail sent to the dolibarr's user that created the ticket

## Steps to reproduce the behavior
Create a ticket to youself (perso) when you have a pro user. Seek for the mail sent, it is not sent to your personnal email.

![Capture](https://user-images.githubusercontent.com/2384485/101019133-cc952a80-356c-11eb-88df-147b2411391a.PNG)

**Comment by atm-lena** [comment]
Hello,

Thanks for reporting, i'll have a look.
