### ISSUE TITLE
Bug: deleting an erroneus internal transfer on bank account does not delete (or suggest to delete) the other linked part 

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15620]
# Bug
when making an internal transfer between accounts 2 records are created. if one is deleted the other should be automatically deleted as well IMO. 

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.13
- **Database**: PostgreSQL 12.5
- **URL(s)**: /compta/bank/bankentries_list.php?action=reconcile&sortfield=b.datev,b.dateo,b.rowid&sortorder=asc,asc,asc&search_conciliated=0&contextpage=banktransactionlist&id=2&search_account=2

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
create 2 accounts
create an internal transfer -> 1 entry in both accounts
delete 1 of them
the other one is left "dangling"

**Comment by dpriskorn** [comment]
Reopen

**Comment by OlivdeLab** [comment]
It's not a bug.
It helps to create two lines in banck.
2 actions to delete must be done
