### ISSUE TITLE
Mass E-Mail invoce failed after odt template generation

### ISSUE THREAD

**Issue by simaker** [Dolibarr/dolibarr#15642]
# Bug
I create my invoices with the help of odt templates. It works fine. If I want to send mass email invoces the problem is, that Dolibarr searches the generated invoice with filename = invoicenumber.pdf. This results in the error: *Failed to read file /'var/lib/dolibarr/documents/facture/20-000001/20-000001.pdf*
since the file is stored in */'var/lib/dolibarr/documents/facture/20-000001/20-000001_template.pdf* (see attached files)

The generated pdf. file although has the filename *invoicenumber+suffix.pdf* of the template name.

E.g. Invoicenumber = 20-000001; name of template: template --> generated file: 20-000001_template.pdf

A workaround i used was to rename the file after convertig to pdf in the skript odt2pdf.sh. Then it is working

## Environment
- **Version**: [*12.0.3*]
- **OS**: [*Ubuntu 20.04*]
- **Web server**: [Apache/2.4.41 (Ubuntu)]
- **PHP**: [7.4.3]
- **Database**: [MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0ubuntu0.20.04.1]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
generated pdf files after using odt templates must have the same naming when using pdf templates --> only the invoicenumber

## Steps to reproduce the behavior

1. Create an odt template for invoice
2. create an invoice 
3. use the script to convert to pdf
4. go to unpaid invoices
5. select all and send by mail

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Fehlermeldung_Massenemailversand_englisch](https://user-images.githubusercontent.com/56035663/101155372-50135200-3627-11eb-806e-9f209a6f51ec.PNG)
![ls](https://user-images.githubusercontent.com/56035663/101155374-50abe880-3627-11eb-81c5-a75a98ff271b.PNG)

**Comment by daxitsolutions** [comment]
Still a bug in version 14.0.4, same workaround needs to be applied (rename of all pdf after ODT generation)
