### ISSUE TITLE
Bug: Close order to status "All products received" automatically if all products are received <- does not work

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15656]
# Bug
when receiving all products the status on the order is changed to "partially received" erroneously

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.13
- **Database**: PostgreSQL 12.5
- **URL(s)**: /fourn/commande/dispatch.php?id=247

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Do you have something else than products in your order ? Can you add a screenshot of your order ?

**Comment by dpriskorn** [comment]
Yes, I did, but services are not affecting are they? Can you deliver a service?

**Comment by dpriskorn** [comment]
In case yes D should handle that better IMO. If I click the checkbox "mark as received if all products are received "it should do as it says.

**Comment by atm-maxime** [comment]
Yes but I think currently it checks all lines, products and services, so with services that are not receivable, it doesn't close the order. I agree this must be improved

**Comment by atm-maxime** [comment]
Is this the same as #13299 ?

**Comment by dpriskorn** [comment]
@atm-maxime yes it seems so. closed
