### ISSUE TITLE
saturday and sunday not detected correctly in function num_public_holiday()

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#15652]
# Bug
When using the `function num_public_holiday()` in the date.lib.php saturdays and sundays are not detected correctly.

For us (UTC+2) this is broken and the holidays on weekends are being set to sunday+monday.
Here: https://github.com/Dolibarr/dolibarr/blob/6c8a6aa81f7ca71d46fcae107e096527cfd06506/htdocs/core/lib/date.lib.php#L793-L806
the calculation is not dependable.

**Comment by ATM-Nicolas** [comment]
Can you please specify the dolibarr version in which you have encountered this problem ?

**Comment by cfoellmann** [comment]
current `develop` branch - 13.0-beta

I believe the calculation is working in some cases but for us it is just not working.
That is odd because we are in the same timezone as the big group of French users
