### ISSUE TITLE
Bug: classify reception defaults to empty "delivery" field.

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15655]
# Bug
I think thats a bug. It should default to "complete" to avoid extra clicks.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.13
- **Database**: PostgreSQL 12.5
- **URL(s)**: /fourn/commande/card.php?id=247&action=classifyreception

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by Zebedeu** [comment]
Can you provide Screenshots for a better understanding? just drag the image to the comment box and wait for it to load
