### ISSUE TITLE
V12.0.3: Supplier-Category visible on card.php, with Supplier-Module not active.

### ISSUE THREAD

**Issue by weltenspiegel** [Dolibarr/dolibarr#15659]
Version 12.0.3 on Debian
Module Categories is active (for Customer-Categories)
Module Supplier is NOT active, so jQuery("#fournisseur") is not on card.php

/htdocs/societe/card.php line 1751 - 1753

       			function init_supplier_categ() {
					console.log("is supplier = "+jQuery("#fournisseur").val());
					if (jQuery("#fournisseur").val() == 0)

Proposed fix:
       			function init_supplier_categ() {
					console.log("is supplier = "+jQuery("#fournisseur").val());
                                        var fournisseur_val=jQuery("#fournisseur").val();
					if ( fournisseur_val == 0 || typeof fournisseur_val == "undefined" )

**Comment by atm-quentin** [comment]
Hello,

Thanks for reporting, i'll have a look.
