### ISSUE TITLE
manage/display social networks for my company

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#15668]
discussion:  other arrangement of (social) networks of my company:

A) move the entries social networks at my company to a separate tab

    suggestion:    
    htdocs/admin/company.php  ->  htdocs/admin/company_networks.php 

B)  maybe there also using of function/dictionary social network

     (but then it is working for my company also only if module social network is active)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/15743 https://github.com/Dolibarr/dolibarr/pull/15744
