### ISSUE TITLE
BUG : problem of date in TakePOS 

### ISSUE THREAD

**Issue by maxime-robin-mis** [Dolibarr/dolibarr#15687]
# Bug
The date search of cashment is not right.
Dans le calcul du journal de caisse, les dates de recherches sont basées sur la date de la facture et non la date de l’encaissement.

## Environment
- **Version**: 12.0.3

## Expected and actual behavior
If you cash today an old invoice, the cashment doesn't add in cash report
WORK ONLY IF #15686 IS APPLY

## Steps to reproduce the behavior
- create an invoice to yesterday date
- cash the invoice with TakePOS
- the cashment is doesn't add in cash report

## my solution :
- In files : « compta/cashcontrol/cashcontrol_card.php » and « compta/cashcontrol/report.php »
Replace all « datef » by « p.datep »

**Comment by denis-poncereau** [comment]
Not corrected yet

**Comment by L33thium** [comment]
is there any activity about this feature request ? i'm very interested about that fonctionnality before adopting dolibarr

**Comment by peyo0** [comment]
Hello, I might be a little late but I solved the problem by changing (V17.0.3) on takepos/invoice.php, line 471 : 
		$invoice->date = dol_now('tzuserrel');		// We use the local date, only the day will be saved.
by 		$invoice->date = dol_now();		// We use the local date, only the day will be saved.
