### ISSUE TITLE
Error when validating a proposition with ODT model

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#15684]
# Bug
With a ODT model, validating the propale create an error:
Application Error
[Sat Dec 05 18:03:55.340750 2020] [php7:error] [pid 12908:tid 1036] [client 192.168.1.51:59950] PHP Fatal error:  Uncaught Error: Call to a member function getNomUrl() on null \comm\\propal\\card.php:1980\nStack trace:\n#0 {main}\n  thrown in htdocs\\doliv12\\comm\\propal\\card.php on line 1980, referer: /comm/propal/card.php?id=1&action=validate
See https://www.dolibarr.fr/forum/t/erreur-php-avec-modele-odt-lors-de-validation-de-propale/34349/5

## Environment
- **Version**: 12.0.3
- **OS**: Windows 10
MariaDB 10.5.8, PHP 7.4.13, Apache 2.4.46
- **URL(s)**: /comm/propal/card.php?id=1&action=validate

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/commit/85c5f423b119ee58a99e01480266461a8c4c0b63
