### ISSUE TITLE
Add invoice to TakePOS if cashment with him (for add into cash report)

### ISSUE THREAD

**Issue by maxime-robin-mis** [Dolibarr/dolibarr#15686]
# Feature Request
Add invoice to TakePOS if cashment with him (for add into cash report)

Dolivarr : v12.0.3

## Use case
- Create and valid an invoice without of TakePOS (by normally's path)
- Cash the invoice with TakePOS
- Currently, the cashment is not add to cash report

## Suggested implementation
- When an invoice is cashment with TakePOS, add the invoice in TakePOS for the cashment is add in cash report of day

## Suggested steps
- In file « compta/facture/class/facture.class.php », function update(), line 1860, add in sql variable « $sql »
``` php 
$sql .= " module_source=".(empty($this->module_source) ? "null" : "’".$this->module_source."’").",";
$sql .= " pos_source=".(empty($this->pos_source) ? "null" : "’".$this->pos_source."’".",");
```
(be careful to don't break the sql request)

- In file « takepos/invoice.php », in the
``` php 
if ($action == "valid" && $user->rights->facture->creer)
```
And add after
``` php 
// Add the payment
if ($res >= 0) {
```
that
``` php 
    $invoice->module_source = "takepos";
    $invoice->pos_source = $_SESSION["takeposterminal"];
    $invoice->update($user);
```

**Comment by denis-poncereau** [comment]
I have a more global question : what should cash report take in consideration ? Only paiement recorded in the takepos ?
What about :
- refunding a customer in cash
- making a deposit to put cash in the bank
- making an expense with cash ?
I think cash control should take every cash movement, going in or out the cash desk, to have a proper cash control (like said in #15664)
But it is getting more complicated  if you have several cash desks/terminals, should there be one account for each terminal ?

Maybe I'm not fully understanding the way cash control works in Dolibarr...

**Comment by maxime-robin-mis** [comment]
I think you right.
All of the movements would have to be present in cash report

And for me, one cash desk = one terminal because every terminal haves an entry/out of cash like bank's account.

**Comment by maxime-robin-mis** [comment]
In the code, the calcul of cash report is only based on invoice's paiements.
This modify require a refactoring of the sql's request.

**Comment by denis-poncereau** [comment]
> I think you right.
> All of the movements would have to be present in cash report

Yes, I think this module needs a deep rewriting to be accurate. I'd be happy to help on that !

> 
> And for me, one cash desk = one terminal because every terminal haves an entry/out of cash like bank's account.

Then, each cashdesk/terminal should have 1 cash account, to keep track of movements between cashdesk and central safe for example.
