### ISSUE TITLE
Bug: PHP error html_entity_decode() while creating invoice via customer card

### ISSUE THREAD

**Issue by anthonyvdberghe** [Dolibarr/dolibarr#15681]
# Bug
After updating from 10.0.4 to 12.0.4 it is not possible to create invoices directly from the customer card anymore. When clicking the "Create Invoice" button the following error appears right below "Deposit invoice":

`Warning: html_entity_decode() expects parameter 1 to be string, object given in /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/core/lib/functions.lib.php on line 1018 Fatal error: Uncaught Error: Object of class Facture could not be converted to string in /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/core/lib/functions.lib.php:4038 Stack trace: #0 /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/compta/facture/card.php(3207): dol_print_error(Object(TraceableDB), Object(Facture)) #1 {main} thrown in /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/core/lib/functions.lib.php on line 4038`

Creating an invoice directly works only when the date is inserted. When only inserting the client and not the date the same error as mentioned above happens. See attachment.

I think it has something to do with the Replacement invoice function?

On a fresh install the error does not happen.

## Environment
- **Version**: 12.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.4.13
- **Database**:  5.5.5-10.3.27-MariaDB-1:10.3.27+maria~focal
- **URL(s)**: /compta/facture/card.php?action=create&socid=2493

## Steps to reproduce the behavior

1. Open a customer card
2. Click on customer
3. Click on create invoice
4. All fields should appear, in my case the php error mentioned above appears and creation of an invoice is not possible.

## [Attached files]

![Schermafbeelding 2020-12-06 om 15 56 41](https://user-images.githubusercontent.com/16089768/101283724-96f67880-37dc-11eb-8988-b6eb9c771277.png)

**Comment by atm-quentin** [comment]
Hello,

Thanks for reporting, I'll have a look

**Comment by atm-quentin** [comment]
After some tests, this problem seems solved in 12.0.4, can you try to upgrade and tell us if the problem is still there?

**Comment by anthonyvdberghe** [comment]
Hi, unfortunately the problem still occurs. I have updated from 10.0.4 to version 12.0.4.
Just like before, this error only occurs when preselecting a client by invoicing from the client card or by inserting the client name and not inserting an invoice date.

`Warning: html_entity_decode() expects parameter 1 to be string, object given in /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/core/lib/functions.lib.php on line 1019 Fatal error: Uncaught Error: Object of class Facture could not be converted to string in /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/core/lib/functions.lib.php:4039 Stack trace: #0 /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/compta/facture/card.php(3222): dol_print_error(Object(DoliDBMysqli), Object(Facture)) #1 {main} thrown in /customers/0/7/d/tillssolutions.com/httpd.www/dolibarr/htdocs/core/lib/functions.lib.php on line 4039`

**Comment by anthonyvdberghe** [comment]
I have been looking into the error while browsing through the code in compta/facture/card.php and have noticed that the error occurs while querying the invoices from the selected company to make a credit note or replacement invoice. The output from list_replaceable_invoices() and list_qualified_avoir_invoices() is in both cases an array while the error above tries to convert to string.

When disabling replacement invoices and credit notes in "Setup Other" it is possible to create an invoice, however we would also like to create credit notes and replacement invoices :-)

My guess is that the queries and the old v10 database are probably not compatible but I'm not sure.
Thank you in advance for any help with this.
