### ISSUE TITLE
Not possible to edit Bank accounts - issue

### ISSUE THREAD

**Issue by ffit2020** [Dolibarr/dolibarr#15693]
hi, there is an issue: I cannot edit Bank account for a user. I can only the first create a new bank account (iban, bic), but after creating it, I cannot modify or update it.
How is possible to fix this ?
I need to change a Bank data (Iban, Bic) for a user buy I am not able to do this
users - click on a user - HR and Bank
thanks

**Comment by dolibit-ut** [comment]
Can you send more details.
Please read  https://github.com/Dolibarr/dolibarr/blob/develop/.github/CONTRIBUTING.md

**Comment by frederic34** [comment]
This issue has been fixed in develop : https://github.com/Dolibarr/dolibarr/commit/28cedd322946cb07652b2ad5164288110afafd11

**Comment by JonBendtsen** [comment]
@frederic34  Fix doesn't work in 18.0.3 :-(
