### ISSUE TITLE
Rest API tickets: Get tickets always empty

### ISSUE THREAD

**Issue by marcelK0** [Dolibarr/dolibarr#15702]
# Bug
Use the REST API to get a list of all tickets. However, the list is always empty.

## Environment
- **Version**: 12.0.3
- **OS**: Ubuntu 20.04
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: 7.4.3
- **Database**: MariaDB 5.5.5-10.3.25
- **URL(s)**: /api/index.php/explorer/#/

## Expected and actual behavior
In the API explorer, the get /tickets should return a list of all tickets. However, a call always returns "message": "Not Found: No ticket found". 

## Steps to reproduce the behavior
First, create a ticket.
Go to api explorer, tickets, GET /tickets. Enter API key for user with permissions to view (and modify) tickets. Try the request with default parameters (not filters, etc.). Returns that no tickets are found.

Using the POST /tickets call does work, the ticket can be seen in Dolibarr. However, calling GET /tickets afterwards again shows empty list.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by matDOTviguier** [comment]
Same thing here ! In a **complete reversed manner**. GET works, not POST.
![Capture](https://user-images.githubusercontent.com/2384485/101500611-013f2280-396f-11eb-947c-8a44e6f8833a.PNG)

**Comment by matDOTviguier** [comment]
@marcelK0 please, email to [doli_issue@service-informatique.fr](mailto:doli_issue@service-informatique.fr) in order to discuss it quicly. _Please notice that i'm not a member of DOLIBAR dev team at all._

**Comment by matDOTviguier** [comment]
I reopen on POST.
