### ISSUE TITLE
Error when  coping DB in PHPMYADMIN

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#15708]
# Bug

12.0.3 and MariaDB version 10.3.27

When making a copy of the DB in phpMyAdmin it throws an error as seen at the jpg attached. Is this anything on my side or what? Do you have any idea what to do about it? I have no problems in my daily use of Dolibarr.

![dolibarr](https://user-images.githubusercontent.com/24247236/101509530-26389300-3979-11eb-886c-5a3762725a98.jpg)

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by erikvanberkum** [comment]
I am not sure what you mean by making a copy of the database. I can imagine a backup or a restore. 
If phpMyAdmin fails you, have a look at these two applications for managing your database:

HeidiSQL is free software:
https://www.heidisql.com/

DBeaver has a free community edition: 
https://dbeaver.io/

Further more i think this is not a Dolibarr bug, you better look for help in the phpMyAdmin forum or in the Dolibarr forum:
https://www.dolibarr.org/forum/

**Comment by hregis** [comment]
@hasse-basse 
remember to disable the checking of foreign keys when you export / import the database

**Comment by hasse-basse** [comment]
Thanks for your suggestions. I will follow the advice to disable the foregin keys check and do a regular export.

To Eric I can say that phpMy Admin have a function namned Copy that creates a Copy of the DB on the server; you just give it another name. It works fine DB for other software, it is only on Dolibarr I have problem. I will use the standard export function and disable the foregin keys check
