### ISSUE TITLE
error opening ODT-File when "&" in {company_name_alias} 

### ISSUE THREAD

**Issue by RalfWillkommen** [Dolibarr/dolibarr#15717]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[error generating ODT-File when "&" in {company_name_alias} ]

## Environment
- **Version**: [*12*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [5.6]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[since update to dolibarr 12 an error occured when opening a odt-file (e.g. proposal), when {company_name_alias} contains the symbol "&" e.g. "Jessica & Marc"]

## Steps to reproduce the behavior
[I changed the {company_name_alias} into "Jessica and Marc", then it worked error-free
After re-inserting the "&" the bug happend again
![Bildschirmfoto vom 2020-12-09 16-32-21](https://user-images.githubusercontent.com/75743096/101650985-d9b68b80-3a3c-11eb-91ef-0acc2c3df643.png)
]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by Sigmamatt** [comment]
same problem for me

**Comment by frederic34** [comment]
related to https://github.com/Dolibarr/dolibarr/issues/15610

**Comment by frederic34** [comment]
Fixed here https://github.com/Dolibarr/dolibarr/commit/5510f1feef7417205f8bf2da2ab9dd053aefa1e9
