### ISSUE TITLE
Bug : product selling price not refreshed on product list when the pricing mode is set to be computed

### ISSUE THREAD

**Issue by zuiko** [Dolibarr/dolibarr#15739]
# Bug
Product selling price not refreshed, the first time, on product list when the pricing mode is set to be computed.

## Environment
-Version: 12.0.3
-OS: Linux Debian 3.16.64-2 (2019-04-01) x86_64
-Web server: Apache/2
-PHP: PHP 5.6.40
-Database: MySQL or MariaDB 5.6.48-log
-URL(s) /product/price.php?id=13371&action=edit_price
- **Dynamically calculated prices module activated**

## Expected and actual behavior
Modifying a product selling price by setting it to be computed, for example  price=#global_coeff3#*#supplier_min_price#, after the first registration of the product, returning to the list the selling price is not the same. If you return to the product and reopen the selling price and then saving without changing nothing, the selling price will be good this time.

**After a survey of users, the problem does not seem to be systematic but reproducible in about 10 to 20% of cases.**

## Steps to reproduce the behavior
Locating a product whose selling price differs from that of its peers:
![image](https://user-images.githubusercontent.com/1511011/101955946-061a0580-3bff-11eb-8931-9aed883c8a80.png)
Let's see what happened to his selling price:
![image](https://user-images.githubusercontent.com/1511011/101956043-32ce1d00-3bff-11eb-83a0-0ae498973f29.png)
Bizarre, everything seems correct, so let's change this selling price:
![image](https://user-images.githubusercontent.com/1511011/101956095-5002eb80-3bff-11eb-8b6d-8f151d81fea3.png)
Everything seems correct, the selling price is calculated using a simple formula (X_coeff3 corresponds to price=#global_coeff3#*#supplier_min_price#) involving the purchase price and also includes a minimum price.
I save, in this state, without modifying anything, the history is enriched by a line identical to the previous one:
![image](https://user-images.githubusercontent.com/1511011/101956278-96584a80-3bff-11eb-9554-461f7dec6643.png)
Then I go back to the list :
![image](https://user-images.githubusercontent.com/1511011/101956356-bdaf1780-3bff-11eb-83db-440786f88720.png)
And then, oh surprise, everything is back in order, the selling price is in line with what was calculated the first time.

Isn't there a variable badly initialized somewhere that would do its job badly?

Discussion on french forum[ here](https://www.dolibarr.fr/forum/t/calcul-de-prix-dynamique/24377).

**Comment by atm-florianm** [comment]
Thanks for the detailed issue description. I’ll have a look.

**Comment by ridfa1** [comment]
Hello,
The bug is still present on dolibarr v15.0.3 & v16 stable at this time.

**Comment by MarcVJ** [comment]
Hello,
The bug is still present on Dolibarr v19.0.2.
The formula we are using is : 
price = #supplier_min_price_with_discount# * #global_coeff1# 
We tried other formulas and it’s the same. 
We always have to go on the selling price page of the product, edit it and save it without touching anything, for the price to actually update in the product list.
And we have to do this on every product where the supplier price is changed.

We would greatly appreciate an update solving this problem !

Regards,
