### ISSUE TITLE
BOM: Items added are not shown until page refreshed.

### ISSUE THREAD

**Issue by martincoster** [Dolibarr/dolibarr#15748]
When I add a new item to BOM (and click Apply button), it does not display in BOM list. But when I refresh the browser page, it is shown, but sometimes appears twice. 

<img width="1122" alt="Screenshot 2020-12-13 at 10 06 06 PM" src="https://user-images.githubusercontent.com/20765268/102014158-95eeb980-3d8f-11eb-81e9-d9bd5d8effd0.png">

<img width="1130" alt="Screenshot 2020-12-13 at 10 07 06 PM" src="https://user-images.githubusercontent.com/20765268/102014175-a7d05c80-3d8f-11eb-92a0-eb830902beb6.png">

If I try to delete and item in the BOM (and click "yes" in pop-up dialog to confirm) I get errors: 

<img width="1166" alt="Screenshot 2020-12-13 at 9 53 07 PM" src="https://user-images.githubusercontent.com/20765268/102014096-398b9a00-3d8f-11eb-8180-483f69fb393b.png">

Then I click "back", and maybe ok... or maybe not. Sometimes I still see duplicate item. Try deleting again, get same error. 

Apple Macbook Pro 2013, Catalina 10.15.5. Tried in both Safari 13.1.1 and Brave 1.17.75, same issue.

**Comment by atm-adrien** [comment]
Hello ! 
What version of Dolibarr are you working on? 
I failed to reproduce the bug on version 12.0.4

**Comment by JESSTOFUNK** [comment]
It is happening in V12.0.0. I had the same issue until V12.0.4

When page is reloaded, the browser adds again the last item, that is why it appears duplicated.

Get 12.0.4 and this is solved there.

**Comment by erikvanberkum** [comment]
@martincoster please close issue
