### ISSUE TITLE
Workstation module

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#15758]
Following #5824

We will create a new workstation module to manage the company workstations and associated costs.
Then, we will work on combining workstations and BOM to have complete production process available and usable in manufacturing orders (MO)

**Comment by cfoellmann** [comment]
Is this different from the ATM workstation module?
Will this be a complete rebuild or will the existing module converted into a PR for core?

**Comment by atm-maxime** [comment]
We are going to rebuild the module for core compatibility. But we have in mind that we will have to deal with data migration from atm modules to core modules.

**Comment by atm-gauthier** [comment]
You can find here my PR : https://github.com/Dolibarr/dolibarr/pull/15794
