### ISSUE TITLE
Bug: Product: purchase price tab, supplier price table with list of products not "responsive"

### ISSUE THREAD

**Issue by zuiko** [Dolibarr/dolibarr#15755]
# Bug
Product: purchase price tab, the supplier price table with its list of products is not "responsive", as a result, the right-clickable areas, including the "Add purchase price" button, disappear to the right of the screens that are not full HD which forces the user to drag his window with the mouse.

## Environment
-Version: 12.0.3
-OS: Linux Debian 3.16.64-2 (2019-04-01) x86_64
-Web server: Apache/2
-PHP: PHP 5.6.40
-Database: MySQL or MariaDB 5.6.48-log
-URL(s) /product/fournisseurs.php

## Expected and actual behavior
When you use a not full HD screen or use Dolibarr inside a not full screen windows with the product managing function (purchase price tab), you want to have your right clckable button ("Add purchase price") directly on your screen without to have to scroll it. 
It's not the case, at least on V12.0.3.

## Steps to reproduce the behavior
product managing function / purchase price tab on a not full HD screen or inside a floating window.

## Suggested solution
The solution is to change the CSS class of the table to adopt the CSS class of the equivalent table of the selling price tab, which is "responsive", to it.
in htdocs/product/fournisseurs.php
We therefore replace :
`print '<table class="liste centpercent">';`
by :
`print '<table class="noborder centpercent">';`

Knowing that the class is used in 24 files, there might be other places where this class poses the same ergonomic problem. I don't know enough Dolibarr to generalize the correction ...
See also [discussion on the french forum](https://www.dolibarr.fr/forum/t/produit-prix-dachat-fenetre-non-responsive-et-ca-agace-mes-utilisateurs/35064).

**Comment by eldy** [comment]
I can't reproduct the trouble with 12.0.4.
Can you check with 12.0.4. If problem still occurs, can you provide ascreenshot ?

**Comment by zuiko** [comment]
Hi Eldy,
because for the moment [V12.0.3](https://github.com/Dolibarr/dolibarr/releases/tag/12.0.3) seems to be still the latest official release, I didn't installed the V12.0.4 but I will try it soon ;-)
If it has been fixed, it's perfect for me. It was verry easy to reproduce by using dolibarr in a not too wide window.
Sorry for the unnecessary trouble.

**Comment by dpriskorn** [comment]
I'm also affected by this on a small monitor. Pretty annoying.

**Comment by zuiko** [comment]
Hi @egils-consulting
you could temporarily patch your Dolibarr as I did if you still use V12.0.3...
Best regards.

**Comment by RomainDeschamps** [comment]
Still the same in 12.0.4 - official or github branch and develop :  

![image](https://user-images.githubusercontent.com/11922840/102354620-1d644480-3fab-11eb-9737-65f40461798d.png)

**Comment by RomainDeschamps** [comment]
OK with @zuiko's fix applied : 

![image](https://user-images.githubusercontent.com/11922840/102356505-94024180-3fad-11eb-8e45-be1b3fc37fb6.png)
