### ISSUE TITLE
Discussion: integrate commercial proposals and orders modules so approved orders are moved to orders module after approval

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15761]
# Discussion
Today it is possible to both create an order that affects the stock and invoicing from commercial proposals and from orders. This is confusing to me. When I want to search for an order I expect all orders that are "made/approved" to be in one place no matter if they started out as a proposal or not.

WDYT? 

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.13
- **Database**: PostgreSQL 12.5
- **URL(s)**: /comm/propal/card.php

**Comment by atm-maxime** [comment]
I don't understand your point. Can you add screenshots? All orders are available in the order list, created from a proposal or not.

**Comment by dpriskorn** [comment]
A ha, I seem to have misunderstood how the system works. I see now that the orders created from a proposal are linked from the order. It seems to work as expected then. 
What about creating an invoice directly from a proposal? Can I turn that possibility off?

**Comment by atm-maxime** [comment]
You can't turn off the possibility to create an invoice from a proposal.
