### ISSUE TITLE
prix moyen pondéré ne prend pas en compte les réduction fournisseurs

### ISSUE THREAD

**Issue by baou9** [Dolibarr/dolibarr#15776]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: [12.0.3]
- **OS**: [*linux*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Mysql*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Le prix moyen pondéré des produits sur dolibarr ne prend pas en compte les réductions que nous avons eu de la part de nos fournisseurs, même si nous précisons le taux de la remise sur le Bon de commande fournisseur.

Du coup, la valeur de notre inventaire n'est pas correcte.

Merci de fixer ce probléme.

  

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Hi. Can you please check on the latest 12.0.5 ? My test shows that the PMP is correctly calculated, including the supplier discount.
Hint for next time, try to use english ;)

**Comment by baou9** [comment]
Hi,
Thank you
