### ISSUE TITLE
How to update v12.0.4 to the latest v12.0Release ?

### ISSUE THREAD

**Issue by itstmyi** [Dolibarr/dolibarr#15773]
I have installed v12.0.4 and want to update it to the latest v12.0Release if any fix/update in v12.0Release branch here  have been changed .

Thanks for any information .

**Comment by ksar-ksar** [comment]
Hi,

What is exactly your question ?
If you want to upgrade to latest V12.0 branch, just download it from GitHub

**Comment by dolibit-ut** [comment]
Hello, 

your Dolibarr 12.0.4 is the latest Release. Really brand new!
If you want the developer version, you have to load here from GitHub.

What is your request?

**Comment by itstmyi** [comment]
> Hi,
> 
> What is exactly your question ?
> If you want to upgrade to latest V12.0 branch, just download it from GitHub

That's it . Thank you .

**Comment by itstmyi** [comment]
> Hello,
> 
> your Dolibarr 12.0.4 is the latest Release. Really brand new!
> If you want the developer version, you have to load here from GitHub.
> 
> What is your request?

Thank you . I need the latest v12.0 release , and the original v12.0.4 maybe still has some problems ,  and I want to update it afer installing official v12.0.4 , so that I can get a good and lastest  version with few problem .

**Comment by dolibit-ut** [comment]
If you want to update after installation, you have to download the files from github and copy these files into your dolibarr directory. Or download the complete package and extract into your dolibarr path and run again setup.

Please can you delete the feature request tag and close the this issue. Thank you.
