### ISSUE TITLE
timezone and mailing status

### ISSUE THREAD

**Issue by suged** [Dolibarr/dolibarr#15780]
# Instructions
"date sent" is ok
but "last update" in dolibarr/htdocs/comm/mailing/cibles.php ignores time zone

# Bug
642				print dol_print_date($obj->tms, 'dayhour');
I think should be replaced by
642				print dol_print_date($obj->tms, 'dayhour',true);

**Comment by ATM-Nicolas** [comment]
Can you please specify the dolibarr version in which you have encountered this problem ?
And also the step to follow in order to reproduce this bug

**Comment by suged** [comment]
still present in 13.0.1, in "Recepients" tab of Mailing tool you can see date read and date of last modification
it's easy to see that date of last modification is incorrect : it does not take timezone into account
I edited the file and applied the fix I suggested (add ",true" in dol_print_date) and it works
