### ISSUE TITLE
Feature Request : Batch handeling of documents

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#15785]
I would like to be able to process multiple documents in one click. On the attached image there are 6 price proposals to one client, and he choosed one of them. The other 5 are to be set to Not accepted. I would like to be able to do so by checking the box to the right and the from here, process all 5 documents in one click, without need to open up each document.

![batch](https://user-images.githubusercontent.com/24247236/102636020-6a374f00-4154-11eb-9dc1-7544daa677d7.JPG)

**Comment by hasse-basse** [comment]
It is a feature request and it is not included in 14.0.4, so pls keep it open and include it as soon as possible.

**Comment by atm-maxime** [comment]
Can you check please ? I just tried on a 14.0 and it seems it's possible to change status of proposal from the list. Sure there are some missing translations...
![image](https://user-images.githubusercontent.com/2097773/147553160-110f85c9-68ac-4e06-a929-0ec585160743.png)

**Comment by hasse-basse** [comment]
Hi

I'm so sorry, it is as I have asked for! I don't know how I could miss it!

So you can close the issue. Great work!

Bonne année! 

Hans

**Comment by hasse-basse** [comment]
New feature works as designed !

Great work.

**Comment by hasse-basse** [comment]
Issue closed as new feature works as designed !

Great work.

**Comment by atm-maxime** [comment]
Thanks for your feedback !
Bonne année !
