### ISSUE TITLE
About REST API

### ISSUE THREAD

**Issue by itstmyi** [Dolibarr/dolibarr#15795]
Where could I find the official details of requst_data format for REST API ? 
for example, POST a SupplierOrderLine by request_data
{
  "request_data": [
    "string"
  ]
}
I can get some data item by GET  REST API, but that's not enough and adequate .

Thanks for any information .

**Comment by dolibit-ut** [comment]
Hello,

you have a question - that is not really a feautre request.
Please read the guide  [https://github.com/Dolibarr/dolibarr/blob/develop/.github/CONTRIBUTING.md]

For these question look and use first the Dolibarr Forum.

Have you looked at Dolibarr Wiki?
https://wiki.dolibarr.org/index.php?title=Module_Web_Services_API_REST_(developer)

**Comment by itstmyi** [comment]
Thanks for your reply and sorry for labeling it "feautre request". I would close this issue soon .
I have read that and did some simple work for several weeks. Doest it  mean I have to write a complete Json sentence myself after reading those PHP source files? Some parameters of REST API is clear such as  New a Warehouse/Validate an order , but some with request_data only .
I make use of REST API by  Golang .

**Comment by Yamilestebangarcia** [comment]
Hello,
Could you tell me how to activate the rest api.
I have tried generating the api key but when I go to
 http://dolibarr/api/index.php/explorer

and I put the api key I get the error "failed to parse JSON/YAML response"

thank you
