### ISSUE TITLE
Feature request : Possibility to invoice Partially recived orders and to split orders to multiple invoices

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#15806]
12.0.4

I placed two orders to a supplier. I recived one of them only partially as one item was missing while the other order was complete. The supplier sent me one single invoice for both orders.

I then tried to merge the two orders into one invoice, but that was not possible as one of the orders was classed as only partially recived.

I would like to be able to make an invoice from an only partially recived order and also to split an order to multiple invoices.

All the best

**Comment by esteveboix** [comment]
Just as an idea, in SAP you do not actually make invoices out of purchase orders, but of material receptions  (though I'm sure you can create invoices out of POs as well).
Having such functionality in Dolibarr would solve your issue. If you have 3 lines, and you only partially receive materials from 1 (even not the complete line), you can actually create an invoice for that.

Regards,
Esteve
