### ISSUE TITLE
Validate Invoice + Stock Management : fail rename folder

### ISSUE THREAD

**Issue by Cuisineh** [Dolibarr/dolibarr#15800]
# Bug
When validating an invoice and inventory management is activated, a fetch is performed before renaming the file and documents. The "$this->ref" property is then modified with the new reference, which prevents the correct renaming.

## Environment
- **Version**: 12.0.3
- **OS**: Ubuntu
- **Web server**: Plesk 18.0.31
- **PHP**: 7.4.13
- **Database**: MariaDB

## Steps to reproduce the behavior
- Enable Invoice and stock management.
- Create a invoice and add un link document.
- Validate invoice.

## Possible correction
Save ref in local var before :
- line 2496 : $oldRef = $this->ref;
- line 2748 : $this->oldref = $oldRef;
- line 2749-2759 : replace $this->ref by $this->oldref

**Comment by ATM-Nicolas** [comment]
Can you provide me more information about your problem, i can't reproduce this
Are we talking about the PDF file or something else ?

**Comment by Cuisineh** [comment]
Hi,
Sorry for the late.
Yes, i talk about PDF in invoice.
If i push a PDF in draft invoice, when i validate the draft, PDF not follow in invoice (with module stock management enabled).
If i look Facture class, stock calculation save invoice in DB so erase informations (old_ref & new_ref).
The PDF move is make after this code.

**Comment by Cuisineh** [comment]
stock calculation erace informations this->ref with the new ref. 
in line 2739, we take $this->ref to provide $this->oldref so oldref is equal new ref
