### ISSUE TITLE
Problem with Warehouses and Listings.

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#15818]
# Bug
[In the section of warehouses
I have detected a functioning that I believe should not have this behaviour.
1º The field Ref. does not allow to be modified, once the warehouse is created.
2º In the case of having many warehouses, (for example 100) it is possible to filter by warehouse name and it works well, however when returning to the list, the focus is lost and it returns to the beginning of the list. (This does not happen in other lists such as products)].

**Comment by atm-jpb** [comment]
can you give me more information about the dolibarr version  you use ?

**Comment by JoAnMaFe** [comment]
Hello good afternoon. 
The version that I use is the 12.04 about XAMPP, but the problem I have been observing since version 10.
In case it has something to do with it, I started to use Dolibarr since version 8 (32bit) and I update it every time a new version appears, currently 12.04 (64 bit). 
I will try to explain better the problem. 
If you have a list of 100 stores from 001 to 100 and the display is 25 lines per page, (4 pages in total). 
Let's imagine that you want to search for store 060, it would be on the third page, you get there, you access it, you modify any value and when you return to the list, it doesn't return to the third page but to the beginning of the list on the first page.

Thanks for your interest and a greeting
