### ISSUE TITLE
Feature request : Be able to hide description per document

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#15812]
I would like to be able hide the description of products when creating a PDF

I have 2 requests in one. If the first otion is not possible, so maybe at least the second is possible?

**OPTION 1 :** The preferable solution would be if there was a checkbox that could be used for each document that is going to be printed as PDF. In may case, I never want to have the description on purchase orders and on delivery notes, and sometimes I would like to avoid it on client orders and also on some Price proposals, as my descriptions are quite long.

**OPTION 2 :** In Configuration --> PDF there is a setting for hiding the product description. I would like to be able to choose for what kind of document. In my case I would like to hide it for all purchase orders and delivery notes, but to keep it in most other cases.

![pdf](https://user-images.githubusercontent.com/24247236/103009329-ec4dbc00-4536-11eb-88ad-0aa0f943735c.JPG)

**Comment by dolibit-ut** [comment]
I have not a solution in Dolibarr standard but their are some third party modules at Dolistore 
- e.g. `InfraPack` / `InfrasPackPlus` or `UltimatePDF` with a lot of print-options for PDFs
   and for settings parameters and switch between you can try `integrated parameters` to switch betwenn you settings

**Comment by hasse-basse** [comment]
Thanks. I will look into them. paramétrage intégré looks very suitable.

**Comment by hasse-basse** [comment]
I've found a workaround. As I am alone on the system, I keep _Configuration --> PDF --> Autres_ open in a separate Window and can thereby easily change the setting for each document.

**I think that the full Autres section should be accessible for every document as Invoices, Price propsals etc. This should be a part of core.**

**Comment by hasse-basse** [comment]
In the Changelog for version 15.0.0 you write on line 93:

**NEW: print without details**

Is this the feature I ask for? If so, the issue can be closed.
