### ISSUE TITLE
Feature request : Be able to upload documents by Dragging and Dropping

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#15810]
Basically all documents from partners like clients, suppliers and others, are recived as emails. To upload let's say an supplisers invoice to the server, today I must first save it to a folder of my  PC  and then upload it according the the picutre attached to this message.

I would like to be able to drag and drop them directly from the email, in the way it is possible to do in this forum so I don't first have to save the document on my PC.

![upload](https://user-images.githubusercontent.com/24247236/103000860-26659080-452c-11eb-9da0-c72fc61ff9b3.JPG)

**Comment by fappels** [comment]
You should be able to drop the doc into the 'select. fichiers' button. Needs some aiming but should work.

**Comment by hasse-basse** [comment]
Cool, thank you, it works fine. Then I have another proposal

1. Add a text telling it is possible to do.
2. When hovering above the button, the change in color is hardly visible so it is difficult to see when you are on the right spot so pls add a stronger color when hovering.
3. Make the button bigger so it is easier to find it when hovering.

**Comment by fappels** [comment]
Good Idea, actual is default navigator fileupload button behaviour. Best change your FR title to 'Enhance file uploader for more easy drag and drop'

**Comment by hasse-basse** [comment]
Aha! I build my own sites in Drupal and html/php and I have not noticed this!

So I close this then

Thanks
