### ISSUE TITLE
Additional Technical Data tab for Products

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#15822]
# Feature Request
[It would be very interesting for the companies that manage fixed assets to have an additional tab in products, where they can register (through additional fields created by the user) the technical data related to the products. Currently, additional fields can be created on the same tab, but when the additional data is too much, the view becomes very chaotic. We have tried some external solution, but it works poorly and does not integrate well with dolibarr.]

## Use case
[Compare products from different manufacturers by analyzing technical data. ]

**Comment by dolibit-ut** [comment]
You can create your own tabs:  https://wiki.dolibarr.org/index.php/Tabs_system
Or with the ModuleBuilder.
Or you can look at the Module CustomTabs at Dolistore.com

**Comment by fbosman** [comment]
Hi,

I think it would be a very nice feature to extend the extrafields definition with a card-tab name. When the object-card is used the extrafields can be put on the selected tab.
Not only for technical data, but there may be more cases involved.
Currently the extrafields are on the main tab of the object-card and this can be confusing.

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 28 dec. 2020 om 21:00 heeft UT from dolibit <notifications@github.com> het volgende geschreven:

﻿
These technical data are very different depending on the company.
So for this you can use the ExtraFields at Products.

**Comment by JoAnMaFe** [comment]
Good night again.
I think many of us are in need of it too.
Continuing with the theme of adding a new tab on products, to be able to define extended characteristics of the same. If you think about it, it turns out to be more important than it seems at first glance. 
I know that there are external modules that generate new tabs or that the user can say "expert", but I think that this is not the most appropriate way. Dolibarr must have this feature as standard and even take it further, if possible.
Why, because many Dolibarr users use it in imaginable scenarios and others impossible to imagine. 
Who is not interested, (if you sell cars) to complete the form with more detailed information, or if they are books or phones or everything else .......?
That's why I think this feature must be if or if, in Dolibarr DNA. 
In fact, it is or should be part of its nature.

How? simply for those who want to use it or not. 
Do you remember this? PROJECT_ALLOW_COMMENT_ON_TASK because it could be also this other, PRODUCTS_ALLOW_EXTRAFIELD_ON_NEW_LAYER.
From there, the operation to create the additional fields is the same as the Category Label Configuration, for this particular tab.
In this way some questions are resolved, referring to the need or not for more specific data and that these can be determined by the activity carried out by the user. 

Greetings

**Comment by fbosman** [comment]
I did some testing on a demo-site and the module of Patat Monkey seems to function well:
https://www.dolistore.com/en/modules/354-CustomTabs--personalized-dynamic-tabs.html?search_query=customtab&results=1

**Comment by JoAnMaFe** [comment]
Hi Frans, good morning.
First of all, thank you for your interest.
Regarding the Custom Tabs module, I have already acquired it and tried it, it works well, however I personally believe that this is not the way.
I said in the previous comment that this feature must be in Dolibarr DNA.
I think that professionals (whatever they do) end up getting the tools they need. If we want Dolibarr to be an alternative to other ERP's we must provide better capabilities and that these are available to everyone.

Thank you and Happy and hopeful year 2021

Greetings
