### ISSUE TITLE
Feature Request : CDAV (carddav) for adherent and/or third-party

### ISSUE THREAD

**Issue by daraelmin** [Dolibarr/dolibarr#15831]
# Feature Request
The CDAV module should offer the possibility to sync adherent and third party.

## Use case
Association are more often in contact with their adherent than external companies. A possible workaround could be to offer the sync carddav with the third party.
It could be useful to use as a WhatsApp diffusion list for association
For large association it is very useful to have the contact sync on the phone to know who is calling.

## Suggested implementation
In CDAV

**Comment by dolibit-ut** [comment]
You mean CardDAV at the (sabre) DAV Module.
I think there is such a module from befox - if you look for befox/cdav.

**Comment by daraelmin** [comment]
Ok it seems the befox/cdav is doing the job. Why this module isn't include in the core ?

**Comment by BB2A-Anthony** [comment]
> Ok it seems the befox/cdav is doing the job. Why this module isn't include in the core ?

Yes it's very more for dolibarr if it is include in the core

**Comment by soerpoers** [comment]
same for me – i think carddav/caldav is useful to sync with most platforms and keep up to date…

**Comment by Bagu** [comment]
> > Ok it seems the befox/cdav is doing the job. Why this module isn't include in the core ?
> 
> Yes it's very more for dolibarr if it is include in the core

+1 here

**Comment by zunami** [comment]
I think it is a pity that this ticket was closed. 

I am of the same opinion. Why is this not included in the dolibarr core system? the times are becoming more modern how to communicate and you need this in everyday life where you check your contacts.

please add cdav to the dolibarr core system
