### ISSUE TITLE
Tickets statistics label bad encoding

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#15832]
When in the ticket app, the statistics section shows wrong labels in french:

- Assign&eacute ; instead of Assigné
- Annul&eacute ; instead of Annulé
- Cl&ocirc ;tur&eacute ; instead of Clôturé

(space before ; added in order to avoid the text to be interpreted)

Suspended is not translated (to Suspendu).

All these labels could be in their plural forms, i.e. Lus, Non Lus, etc.

![Capture d’écran de 2020-12-29 16-56-49](https://user-images.githubusercontent.com/14906222/103296721-f66c3080-49f6-11eb-973f-6a7bc1381371.png)

**Comment by eldy** [comment]
I think this is fixed for v13
