### ISSUE TITLE
Failed to insert event : Duplicate entry '0' for key 'PRIMARY' 

### ISSUE THREAD

**Issue by coop2540** [Dolibarr/dolibarr#15836]
# Bug
Duplicate entry '0' for key 'PRIMARY'  in all actions

## Environment
- **Version**: 12.0.4
- **OS**: linuxmint
- **Web server**: apache
- **PHP**: 7.2
- **Database**: mysql
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
Hi, I recieve Failed to insert event : Duplicate entry '0' for key 'PRIMARY'  in all actions (send email, create product, in all actions! 

![Captura de pantalla de 2020-12-30 10-26-34](https://user-images.githubusercontent.com/28749812/103343053-63310a80-4a8b-11eb-8b9b-8ea8c8e0dfc7.png)

Thanks!

**Comment by eldy** [comment]
Check your table llx_product and llx_product_extrafields.
Do you have a line with rowid = 0 ? If yes delete it.

If not, enable the module Log debug. And take a look at file documents/dolibarr.log and find line with code "ERR" to find the sql error and paste it in this ticket.
