### ISSUE TITLE
BUG : Configuration panel for Product Account display an SQL ERROR

### ISSUE THREAD

**Issue by daraelmin** [Dolibarr/dolibarr#15837]
# Bug
Configuration panel for Product Account display an SQL ERROR (and so these accounts can not be set)

## Environment
- **Version**: 12.0.4 and 13.0.0-beta (maybe older ones)
- **OS**: Linux h2web57 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64
- **Web server**: Apache
- **PHP**: 7.3.25
- **Database**: MariaDB - mysqli
- **URL(s)**: htdocs/accountancy/admin/productaccount.php?mainmenu=accountancy&leftmenu=accountancy_admin
- **Referer**: htdocs/accountancy/index.php?leftmenu=accountancy_admin
- **Menu**:  eldy_menu.php
- **Modules/Applications**: api, user, fckeditor, banque, tax, categorie, accounting, agenda, externalsite, facture, societe, service, website, gravatar, adherent, ticket, import, export

## Expected and actual behavior
Display setup for Product accounts in Module/setup/Product Account to configure these account.

## Steps to reproduce the behavior
Go to Account Module/ setup/ Product setup.

##  Debugging
Dolibarr has detected a technical error.

Requested URL: /htdocs/accountancy/admin/productaccount.php?mainmenu=accountancy&leftmenu=accountancy_admin
Referer: /htdocs/accountancy/index.php?leftmenu=accountancy_admin
Menu manager: eldy_menu.php

Modules/Applications: api, user, fckeditor, banque, tax, categorie, accounting, agenda, externalsite, facture, societe, service, website, gravatar, adherent, ticket, import, export
Database type manager: mysqli

Latest database access request error: SELECT p.rowid, p.ref, p.label, p.description, p.tosell, p.tobuy, p.tva_tx, p.accountancy_code_sell, p.accountancy_code_sell_intra, p.accountancy_code_sell_export, p.accountancy_code_buy, p.accountancy_code_buy_intra, p.accountancy_code_buy_export, p.tms, p.fk_product_type as product_type, aa.rowid as aaid FROM llx_product as p LEFT JOIN llx_accounting_account as aa ON p.accountancy_code_sell = aa.account_number AND aa.fk_pcg_version = 'PCG99-BASE' WHERE p.entity IN (1) AND aa.account_number IS NULL ORDER BY p.ref ASC LIMIT 26

Return code for latest database access request error: DB_ERROR_1267

Information for latest database access request error: Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='

**Comment by daraelmin** [comment]
I'm experimenting this bug on both 12.0.4 (production) and 13.0.0 beta (staging)

**Comment by daraelmin** [comment]
OK, I've found the workaround: 
htdocs/install/repair.php?force_utf8_on_tables=confirmed"

But why this command is not automatically launched during migration ?

**Comment by eldy** [comment]
No. 
This is not related to migration of Dolibarr. But to migration of mysql or to the fact the database was initially created with an old version. Problem is not into dolibarr code but into database maintenance.
