### ISSUE TITLE
Bug: Line item not show when creating invoice from reception

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#15846]
# Bug
Unable to create invoice in reception and error show in the picture below.

## Environment
- **Version**: 12.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.23
- **Database**:  5.6.40-84.0-log
- **URL(s)**: /fourn/facture/card.php?action=create&origin=reception&originid=17&socid=98

## Expected and actual behavior
Should be having a list of line item in PO for invoice creating and payment.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Capture](https://user-images.githubusercontent.com/52134143/103393501-d86d1000-4b5d-11eb-9feb-b55d135b47b5.PNG)

**Comment by atm-quentin** [comment]
Hello,
I'm working on this,

I'll tell you when it'll be corrected
