### ISSUE TITLE
Bug: V13.0.0-Beta SalesTax issue (999.9%) while editing an item on invoices, proposal . etc., or entering free-text item.

### ISSUE THREAD

**Issue by kkoech04** [Dolibarr/dolibarr#15848]
Tax rate becomes 999.9% instead of the actual taxrate from the settings.

![image](https://user-images.githubusercontent.com/24295847/103404657-7a442b00-4b65-11eb-96a9-1934ff2b447d.png)

![image](https://user-images.githubusercontent.com/24295847/103404681-98aa2680-4b65-11eb-8408-87b3a9e33a88.png)

**Comment by kkoech04** [comment]
Issue found. Should be looked into.

The problem was the [Dictionary setup - VAT Rates or Sales Tax Rates]

Any Tax rate with Numeric Code field behaves so. This is because the source code somehow combine the RATE & CODE, the source is the select dropdown while editing, see below

![image](https://user-images.githubusercontent.com/24295847/103412372-d74fd900-4b85-11eb-93c8-5450efe246d6.png)

Code Line:
![image](https://user-images.githubusercontent.com/24295847/103412609-12064100-4b87-11eb-8efc-55a83759541e.png)

Solution:
![image](https://user-images.githubusercontent.com/24295847/103412681-67dae900-4b87-11eb-8095-113add4dd7c0.png)

**Comment by loxK** [comment]
I think this is an attempt to fix this issue: https://github.com/Dolibarr/dolibarr/commit/fd4dab495f010fc170c94ab3e6d5a47be7e7f605

cc: @eldy

**Comment by kkoech04** [comment]
Great!

**Comment by eldy** [comment]
Will also be available with 12.0.5
