### ISSUE TITLE
Standardize code to follow rules of development suggested by Module Builder

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#15879]
Fix code to migrate more code to follow rules of development suggested by Module Builder
* so each DAO class mus have its $fields property (note the php array can be generated with module builder)
* pages use the same frame than templates provided by modulebuilder.

**Comment by davidNDU** [comment]
That would be great. I'm developing a module now for some time and it helps to see how things work elsewhere. 
Does that mean, that modules like Invoices or Products could be made by using the module builder? Looking at _product/card.php?action=edit_ (for example) it seems as if there is quite some legacy and customization applied that couldn't be achieved by the module builder.

**Comment by eldy** [comment]
@davidNDU It won't be possible to switch all legacy code into module builder standard, but goal is to do the much as possible.
