### ISSUE TITLE
BUG/Feature Request : Slow query on search all for supplier order list

### ISSUE THREAD

**Issue by john-botella** [Dolibarr/dolibarr#15871]
# Bug/Feature Request 

If your Dolibarr contain a lot of supplier orders (more than 4000 min), when you do a search all on supplier orders.
Sql query is not optimized, it doesn't use indexes because search is on notes fields.

Can we add fulltext search for desc and notes fields in Dolibarr. This kind of search will be more quick but can be less accurate, so I suggest to add Dolibarr option for global search using fulltext or not according to final user needs.

This is an open question, does Dolibarr community have any suggestions  or recommendations ?

# Environment
- **Version**: 6-13

**Comment by eldy** [comment]
I experienced the same trouble with 10 000 supplier orders.
In my case, the explain plan of mysql was wrong. I fixed it by adding a missing index with this commit 210ccc4b43ca4435aca9706f81c8e4eae4470113 (now i have instant result on a search)
Can you check you have it. And that you run the "optimize table" on table llx_commande_fournisseurdet after.

**Comment by john-botella** [comment]
Thank you @eldy for your answer, yes this index was missing and adding it does reduce the search delay but it will not resolve the core of the problem of searching in mysql text fields in huge base. I think about not only Documents like supplier orders but product desc  too if we have more than 200 000 products
