### ISSUE TITLE
NEW Improvements to Ticket module 'Ticket Area' Screen

### ISSUE THREAD

**Issue by git-putz** [Dolibarr/dolibarr#15917]
# Feature Request
Add more data/graphs to 'Ticket Area' screen.  Currently there are only 2 tables, - Statistics (year) and Last 10 newest tickets.
More options would be nice such as:
Chart for Ticket Type
Chart of Ticket Severity
Graph of daily tickets for last X days
New tickets vs Completed tickets for the day.

## Use case
Seeing these data points at a glance helps determine how your support department is doing for the day/week and what sort of ticket severity needs to be addressed.

## Suggested implementation
Add these data sets/charts as fixed option to the 'Ticket Area' screen or allow the end user to create widgets based on these data points and add them to the 'Ticket Area' screen.

**Comment by eldy** [comment]
Try to use "Close #xxx" instead of "Close abc #xxx"  (no text between close or fix and #number) so autclosing will not be broken

**Comment by eldy** [comment]
Try to use "Close #xxx" instead of "Close abc #xxx" (no text between close, new or fix and #number) so autclosing will not be broken
