### ISSUE TITLE
Sum Qty

### ISSUE THREAD

**Issue by DenysLP** [Dolibarr/dolibarr#15919]
do you have a model that adds the quantity field?
Or how do I do it?

**Comment by atm-maxime** [comment]
?? Can you provide informations please ?
What model ? what module ? what version ? what quantity field ?

**Comment by DenysLP** [comment]
Hi,

Excuse me, here's information:

Version: 11.0.3
Module: Invoice (Facture)
Generate template document "crabe"

![Capture](https://user-images.githubusercontent.com/15112491/103888183-12d92e80-50c3-11eb-9a9d-6c8334817973.PNG)

**Comment by dolibit-ut** [comment]
Hey, i think it is really very unusual to print the total quantity - across all products - on an invoice.
On an order confirmation maybe or on a delivery bill i can imagine, that it is usual / makes sense.

I think also in this case we would need another layout for the total area.
You can not print quantity & payment amount so in one line.

**Comment by DenysLP** [comment]
It really makes sense.

Grateful, ending the issue
