### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Psr\Log\AbstractLogger' not found

### ISSUE THREAD

**Issue by rajab12** [Dolibarr/dolibarr#15914]
Hi All,

I was trying to activate the modules. When trying to activate the debug module this issue happened to me.

Fatal error: Uncaught Error: Class 'Psr\Log\AbstractLogger' not found in C:\xampp\htdocs\dolibarr\htdocs\includes\maximebf\debugbar\src\DebugBar\DataCollector\MessagesCollector.php:20 Stack trace: #0 C:\xampp\htdocs\dolibarr\htdocs\debugbar\class\autoloader.php(12): require_once() #1 [internal function]: {closure}('DebugBar\\DataCo...') #2 C:\xampp\htdocs\dolibarr\htdocs\debugbar\class\DataCollector\DolMessagesCollector.php(9): spl_autoload_call('DebugBar\\DataCo...') #3 C:\xampp\htdocs\dolibarr\htdocs\core\lib\functions.lib.php(774): include_once('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\dolibarr\htdocs\debugbar\class\DebugBar.php(7): dol_include_once('/debugbar/class...') #5 C:\xampp\htdocs\dolibarr\htdocs\main.inc.php(291): include_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\dolibarr\htdocs\index.php(29): require('C:\\xampp\\htdocs...') #7 {main} thrown in C:\xampp\htdocs\dolibarr\htdocs\includes\maximebf\debugbar\src\DebugBar\DataCollector\MessagesCollector.php on line 20

Tried to rename the composer.lock and did a Composer Install again. Did not work. 

Am not able to see the Vendor folder to delete and do a fresh Composer Install.

Am using Composer 1.9. Did anybody face similar issues?!

**Comment by stephanebelazouz** [comment]
Hi,

Hope since last time you solve your problem !

I've encountered the same error and for disable manualy the module debugbar i had to change entity and value column of MAIN_MODULE_DEBUGBAR row in the datable from the const table.

Hope it help.

**Comment by mafzalzadeh** [comment]
It seems when you run 'composer update' the 'AbstractLogger' file moves to /Psr/Log/Psr/Log folder.
I changed the debugbar autoload folder and make the problem fixed.

Is there another way?

**Comment by Daviid-P** [comment]
This happens to me too, I just used jenkins to deploy to testing environment and I get this error. (All files exist and have same permissions and owners as other files)
Deleting the line from llx_const fixes the problem but you can't enable debugbar or it'll fail again.
