### ISSUE TITLE
Showing "List" of supplier proposals is very slow with more than 3000 supplier proposals

### ISSUE THREAD

**Issue by aurelienmi** [Dolibarr/dolibarr#15939]
Hi,
This is not a bug, just a possibility of improvement

If your Dolibarr contains a lot of supplier proposals (more than 3000), when you simply click on the "List" link to show the list of supplier proposals, it's very slow (whereas this will show only one page of results)

I am just wandering if the indexes are ok on MySQL for this table, or if there is some extra checks that make it slow on the PHP script to show the list ? maybe this comes from the "SELECT" MySQL request (which starts from line 257 of the list.php script ...

This is an open question, does Dolibarr community did you experience the same trouble and do you have an idea how to fix it  ? 

## Environment
- **Version**: [version 12]
- **OS**: [Windows Client with Chrome or Firefox]
- **Web server**: [*Mutualized server type OVH or o2Switch*]
- **PHP**: [*7.3*]
- **Database**: [*Database type and version*] : MySQL 5.6 mini
- **URL(s)**: [*Affected URL(s)*] : htdocs/supplier_proposal/list.php?leftmenu=supplier_proposals

## Expected and actual behavior
Actual behavior : it takes 1 min to show the first page when i click on the list on my Dolibarr - current content is 7807 lines of supplier proposals ... Compared to all other screens this one seems particularly low 

## Steps to reproduce the behavior
Click on the "Commercial module" -> Supplier proposals -> List

**Comment by dolibit-ut** [comment]
Hey,

we have a setting with about 12 thousand contacts
and another one with about 4000 third parties but with about 8000 customer orders -
both on small-medium webhostings  (shared webserver)
but there we have maximum waiting times of 5-10 seconds to show a list with 50 or 100 lines & all details,
usually 2-4 seconds.

On local servers it runs all in under 1-2 seconds.

So i think it depends on the webserver-settings.
What are the specs?

**Comment by aurelienmi** [comment]
Hello,
Thanks for your message
I confirm that there are no issues with thousands of contacts, third parties ..
But we experienced this issue only when we click on the "supplier proposal lists" ...
That's why we may believe there may be a possible improvement or optimization of this query ... 
maybe the script is making checks that makes the results appear slow
Thanks

**Comment by aurelienmi** [comment]
Hello,

i have tested the query itself in PhpMyAdmin on the same database and the query itself shows results in 32 seconds, which is already very long ... so we believe that the query has a problem or maybe optimized for a high number of lines ..
Here below the exact SQL of the query launched by this script list.php
i don't know how to optimize, need your help to fix it ...
Thanks for your help or just confirm if somebody else experienced the same issue with supplier proposals list

SELECT s.rowid as socid, s.nom as name, s.town, s.zip, s.fk_pays, s.client, s.code_client, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, sp.rowid, sp.note_private, sp.total_ht, sp.tva as total_vat, sp.total as total_ttc, sp.localtax1, sp.localtax2, sp.ref, sp.fk_statut as status, sp.fk_user_author, sp.date_valid, sp.date_livraison as dp, sp.fk_multicurrency, sp.multicurrency_code, sp.multicurrency_tx, sp.multicurrency_total_ht, sp.multicurrency_total_tva as multicurrency_total_vat, sp.multicurrency_total_ttc, sp.datec as date_creation, sp.tms as date_update, p.rowid as project_id, p.ref as project_ref, u.firstname, u.lastname, u.photo, u.login, ef.ref_propal as options_ref_propal, ef.ref_po as options_ref_po FROM llx_societe as s LEFT JOIN llx_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN llx_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN llx_c_departements as state on (state.rowid = s.fk_departement), llx_supplier_proposal as sp LEFT JOIN llx_supplier_proposal_extrafields as ef on (sp.rowid = ef.fk_object) LEFT JOIN llx_user as u ON sp.fk_user_author = u.rowid LEFT JOIN llx_projet as p ON p.rowid = sp.fk_projet WHERE sp.fk_soc = s.rowid AND sp.entity IN (1) ORDER BY sp.date_livraison DESC, sp.ref DESC LIMIT 51

**Comment by dolibit-ut** [comment]
Hey,

have you tried using dolibarr debug bar in the logs to look for more details.
Or with your browser dev tools (F12) at runtime analysis.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/16044

**Comment by frederic34** [comment]
@aurelienmi can you try adding these two index : 
`ALTER TABLE llx_supplier_proposal_extrafields ADD INDEX idx_supplier_proposal_extrafields (fk_object);`

`ALTER TABLE llx_supplier_proposaldet_extrafields ADD INDEX idx_supplier_proposaldet_extrafields (fk_object);`

**Comment by aurelienmi** [comment]
@frederic34  - modifications done & it's now perfect ! 1 s to show instead of 63 seconds !
I checked the index but not extrafields, thanks a lot
