### ISSUE TITLE
getting database 'Incorrect string value' error during installation

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [Dolibarr/dolibarr#15933]
SQL error : DB_ERROR_1366 - INSERT INTO drr1_c_regions ( code_region, fk_pays, cheflieu, tncc, nom, active) values ( 10201, 102, NULL, NULL, 'Αττική', 1); - Incorrect string value: '\xCE\x91\xCF\x84\xCF\x84...' for column `test`.`drr1_c_regions`.`nom` at row 1

**Comment by futurehousestore** [comment]
What's your charset? Set it to utf8_unicode_ci

**Comment by DanielMazurkiewicz** [comment]
> What's your charset? Set it to utf8_unicode_ci

Thank you, did set it like that (on MariaDB) and problem was solved.
```SQL
SET character_set_server = 'utf8';
```

But I think installation script should cover setting proper encoding, shouldn't it?
