### ISSUE TITLE
V13 : error message "Data truncated for column qty" when adding a line in supplier order

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#15938]
Select a product in a supplier order, add it : 

![image](https://user-images.githubusercontent.com/11922840/104120031-04457e00-5334-11eb-83fb-ba197ec2fc3d.png)

**Comment by dolibit-ut** [comment]
Hello,

i have a Dolibarr 13.0.0-beta and do not get this error.
 (version loaded from github 20. November 2020)

**Comment by RomainDeschamps** [comment]
13.0.0-beta downloaded yesterday 10/01/2021 from github

**Comment by atm-maxime** [comment]
Hi @RomainDeschamps !
I can't reproduce with a stable 13.0 version. Can you check ?
Cheers :wink:
