### ISSUE TITLE
Error while trying to filter vendor invoices by 'Linked to a particular user contact'.

### ISSUE THREAD

**Issue by sachinsyam** [Dolibarr/dolibarr#15940]
# Bug
Dolibarr is throwing an error while trying to filter 'Vendor Invoices' using 'Linked to a particular user contact:'.

## Environment
- **Version**: 12.0.3, 12.0.4
- **OS**: Windows 10 Pro 64X
- **Web server**: Apache 2.4.46
- **PHP**: 7.4.13
- **Database**: MariaDB 10.5.8
- **URL(s)**:  https://demo.dolibarr.org/fourn/facture/list.php
## Expected and actual behavior
It should return the search result.

## Steps to reproduce the behavior
Try to do a filter on vendor invoices by Linked to a particular user contact.

**The error message.
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'f.fk_user_author' in 'on clause'**

**Comment by dolibit-ut** [comment]
Hey,

i get the same error on our Dolibarr-Demo 12.0.3
in the vendor invoices list with both filters:
- Linked to a particular user contact 
- Third parties with sales representative

**Comment by sachinsyam** [comment]
Yes. I tried it with 12.0.4 and it's giving error for both Linked to a particular user contact and Third parties with sales representative.
