### ISSUE TITLE
mysqldump arguments for -p password are not quoted with single quotes so cause problem with dollar sign characters.

### ISSUE THREAD

**Issue by jcopehub** [Dolibarr/dolibarr#15955]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*mysql passwords with special characters cause mysqldump in Backup to fail*]

## Environment
- **Version**: [*Affected Dolibarr version(s) 12.0.4*]
- **OS**: [*Ubuntu 20.04 Linux jcope2020 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64*]
- **Web server**: [*Apache/2.4.41 (Ubuntu)*]
- **PHP**: [*PHP version 7.4.3*]
- **Database**: [*8.0.22-0ubuntu0.20.04.3*]

## Expected and actual behavior
[*mysqldump fails to run if password contains dollars signs or other special characters*]

## Steps to reproduce the behavior
[*Create database user with password including two dollar signs '$$"*]

## Quick Fix

[* replace double quotes with single quotes around password:  $paramclear .= ' -p' . "'" . str_replace(array('"', '`'), array('\"', '\`'), $dolibarr_main_db_pass) . "'"; *]

**Comment by eldy** [comment]
Another solution may be to escape the $ char.
`
$paramclear .= ' -p"'.str_replace(array('"', '`', '$'), array('\\"', '\\`', '\$'), $dolibarr_main_db_pass).'"';
`
