### ISSUE TITLE
Status 1054 - Unknown column 'p.facnumber' in 'field list' 

### ISSUE THREAD

**Issue by Hiperolius** [Dolibarr/dolibarr#15965]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Status 1054 - Unknown column 'p.facnumber' in 'field list' *]

## Environment
- **Version**: [*12.0.4*]
- **OS**: [*Centos 8*]
- **Web server**: [*Apache*]
- **PHP**: [*7.4.11*]
- **Database**: [*mysql server 8.0*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
I whould like to generate an invoice report but I have an error while doing it at a pdf format. I always have the folowing error:

"Main Report Query - Error: Query Failed

SELECT p.facnumber facnumber, t.nom AS customer, p.datef AS date, date_format( datef, '%d-%m-%Y' ) AS fecha, p.paye AS idstatus, CASE p.paye WHEN '0' THEN 'No' WHEN '1' THEN 'Yes' ELSE 'Unknown' END AS paid, p.total total, p.tva vat, p.total_ttc total_ttc, t.rowid rowid, date_format( p.datef, '%m' ) AS month, date_format( p.datef, '%Y' ) AS year, t.siren siren FROM llx_facture p INNER JOIN llx_societe t ON t.rowid = p.fk_soc LEFT JOIN llx_categorie_societe cats ON cats.fk_societe = t.rowid LEFT JOIN llx_categorie cat ON cat.rowid = cats.fk_categorie WHERE 1 = 1 AND p.entity=1 AND p.datef BETWEEN '2000-01-12' AND '2000-01-12' GROUP BY p.rowid ORDER BY date

Status 1054 - Unknown column 'p.facnumber' in 'field list' "

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Hi. This doesn't seem to be a dolibarr issue but your own issue ? Try asking on forums.

**Comment by Hiperolius** [comment]
Yes, I will but, it seems that the problem is in the code that generates
the query. The SQL query is looking for a field that not exists on the
table.... is that possible?

Thanks.

**Comment by catrielr** [comment]
It is not a dolibarr error, you are using an external module, facnumber changed to ref a long time ago

**Comment by Hiperolius** [comment]
oops, thank you so much. I don`t remember to have installed any module
manually. This installation of dolibarr was done several years ago and It
has been upgraded. I will look for help on the forums. Thank you so much
for your help.



*Carlos Sánchez*
[image: www.fotoscarlos.es] <http://www.fotoscarlos.es>
www.fotoscarlos.es
