### ISSUE TITLE
Manufacturing Order customization error in MRP module

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#15966]
# Bug
[*When we want to personalize the numbering we get an error message. Nothing specific in the logs*]

## Environment
- **Version**: [*12.0.3 et 12.0.4*]
![image](https://user-images.githubusercontent.com/3629675/104351299-86d16780-5505-11eb-8193-3cb7439acad8.png)

Line 51 de admin/mrp.php must be corrected : `$maskconstmrp = GETPOST(‹ maskconstBom ›, ‹ alpha ›);`

**Comment by atm-maxime** [comment]
Duplicate #15967
