### ISSUE TITLE
Dolibarr Schema "is not a Workbench document"

### ISSUE THREAD

**Issue by Valbou** [Dolibarr/dolibarr#16003]
# Bug
File dolibarr/dev/resources/dbmodel/dolibarr_schema.mwb is not a Worbench document
Opened with MySQL Workbench 8.0.21

## Environment
- **Version**: Dolibarr 9+
- **OS**: Windows 10
- **MySQL Workbench**: 8.0.21

## Expected and actual behavior
I can't open the file with MySQL Workbench 8.0.21 : "is not a Worbench document"
MySQL Workbench works well with others files

## Steps to reproduce the behavior
Download the file dolibarr/dev/resources/dbmodel/dolibarr_schema.mwb and open it with MySQL Workbench 8.0.21
![workbench-error](https://user-images.githubusercontent.com/34310553/104915270-b1517380-5990-11eb-96bf-458d6e38e05c.png)
.

Thanks

**Comment by dolibit-ut** [comment]
Hello,

just tried it out at WIN 10 with MySQL Workbench 8.0.22 and the file from Dolibarr 12.0.4 (from zip) and it works.

**Comment by hregis** [comment]
me too, no problem with Workbench 8.0.20 and 8.0.22 in Mac OS from Dolibarr 13

**Comment by hregis** [comment]
i try to save the file with the latest version of Workbench : https://github.com/Dolibarr/dolibarr/pull/16006
try to download the latest with this link : https://github.com/Dolibarr/dolibarr/raw/26e74d56b3ad84025b7e036c259f85ef8523faf1/dev/resources/dbmodel/dolibarr_schema.mwb

**Comment by Valbou** [comment]
Thanks, it works with the link.
