### ISSUE TITLE
Bug: if VAT code is written in non latin characters or begins by numerical characters, unable to edit the pricing in Sales Order

### ISSUE THREAD

**Issue by zuiko** [Dolibarr/dolibarr#16015]
# Bug
In V12.0.4 some people complained, at first, having problems modifying lines in customer orders if their VAT codes contained underscore as TX_NORMAL for example and this has been written in issue #15820 and fixed via PR #15983
But now, in the same version, some people complains to have similar difficulties if their VAT codes contains non latin characters as ДДВ (or cyrillic, greek and so on) or begins by numerical characters as 85NPR.
**And it's a regression in V12.0.4**

## Environment
-Version: 12.0.4
-OS: Linux Debian 3.16.64-2 (2019-04-01) x86_64
-Web server: Apache/2
-PHP: PHP 5.6.40
-Database: MySQL or MariaDB 5.6.48-log
-URL(s) /commande/card.php

## Expected and actual behavior
When you want to edit a product line in a customer order,
- If you want to use a VAT code containing non latin characters as ДДВ (macedonian)  or НОРМАЛНА_ЦЕНА (bulgarian) (or cyrillic, greek and so on) you will get an error message 
![image](https://user-images.githubusercontent.com/1511011/104972442-0ec9dc80-59f2-11eb-966c-ed03c764c1cc.png)
because Dolibarr is not able to found the TVA value in the database.
- If you want to use a preset VAT code which begins by numerical value as 85NPR, 
![image](https://user-images.githubusercontent.com/1511011/104972302-ae3a9f80-59f1-11eb-9cfe-fbfe42a8df37.png)
the value entered will be strange as 8,585% Instead of 8,5 %
![image](https://user-images.githubusercontent.com/1511011/104972361-df1ad480-59f1-11eb-9f7f-90fd8cc94c9d.png)

## Steps to reproduce the behavior
Create VAT rates  in dictionnary with codes containing non latin characters (cyrillic, greek...) or beginning by numbers.
Try to use it for products in a customer order or try to modify a line using it.

## Code to change
function price2num in htdocs/core/lib/functions.lib.php needs some enhancements...
that I will propose very soon.

## Forum post concerned
- you can see a [complaint on the english forum](https://www.dolibarr.org/forum/t/issue-with-vat-in-vendor-invoice/20093).

**Comment by eldy** [comment]
I tested on branch 12, and I can't reproduce. I tested with a vat code "ДДВ88" Can you reproduce on current branch 12 ? If yes, can you describe how ?

**Comment by zuiko** [comment]
The case of non latin characters VAT code has been covered by
[FIX Bad cleaning of VAT rate when numbers are into code](https://github.com/Dolibarr/dolibarr/commit/fd4dab495f010fc170c94ab3e6d5a47be7e7f605)
A large cleaning you performed some days ago around price2num calls with VAT code, I didn't see.
This answers also to the last complaint in PR #15983 about not complete fix for VAT code beginning with digits (as 85NPR)
My PR #16015 relayed about VAT code "ДДВ88" concerned pure V12.0.4 version (without your recent upstream cleaning)

**Comment by eldy** [comment]
The case of code beginning with number (like "85NPR") should also be already fixed.
If someone can reproduce the trouble on v12 branch, thanks to reopen ticket and describe test to reproduce.
