### ISSUE TITLE
compute extra fields 

### ISSUE THREAD

**Issue by coding1wolf** [Dolibarr/dolibarr#16023]
Hello, 
Im having some issues when using the computed fields function. I want to create a Field called A, another Field called B and a third field called C. And want this result C = A * B
I´ve used this code: ($object->array_options [‘options_A’])*($object->array_options [‘options_B’])
but it does not work.
![image](https://user-images.githubusercontent.com/77683226/105054768-a66f0f80-5a72-11eb-932a-29f612886164.png)

Thanks.

**Comment by Hystepik** [comment]
Hello i tryed and i did succeed by using this code   
$object->array_options['options_Code atribute for A']*$object->array_options['options_Code atribute for B']

**Comment by coding1wolf** [comment]
What about $object->array_options['options_Code atribute for A']*$product_static->stock_reel, does that work for you? Stock_reel is allready on the dolibarr, but that multiplication allways gives me back 0.

**Comment by Hystepik** [comment]
To make this work you need to make an SQL request in your code:  
$object->array_options['options_Code atribute for A']*$db->fetch_object($db->query('Here Your Request With The Good Product'))->reel

**Comment by coding1wolf** [comment]
I´m sorry for being kind of a noob on this things, but it still does not work, it gives me a lot of errors. What do you mean with('Here Your Request With The Good Product'). I mean, i want to have that extra field for all the products on my list, so i´m not sure what i have to write there. What i want in my new field is D=(C*stock_reel).
Thank you in advance.

**Comment by Hystepik** [comment]
Don't worry we all need to start somewhere.Just change CodeforC and it will work
$db->fetch_object($db->query('SELECT reel FROM llx_product_stock as ps WHERE ps.fk_product='.$object->id.';'))->reel*$object->array_options['CodeforC']

**Comment by coding1wolf** [comment]
Thanks for understading my noob issues. But still, I think I´m not explaining myself correctly, my problem is not with the 'CODEforC', that part does work, my issue is with the query part. I´m going to show you exactly where my issue is, so that you can help me easier.
`$db->fetch_object($db->query('ps.fk_product'))->reel*$object->array_options['C33']`  This is my code

`Fatal error: Uncaught Error: Call to a member function fetch_object() on bool in D:\dolibarr\www\dolibarr\htdocs\core\db\mysqli.class.php:310 Stack trace: #0 D:\dolibarr\www\dolibarr\htdocs\core\lib\functions.lib.php(7206) : eval()'d code(1): DoliDBMysqli->fetch_object(false) #1 D:\dolibarr\www\dolibarr\htdocs\core\lib\functions.lib.php(7206): eval() #2 D:\dolibarr\www\dolibarr\htdocs\core\class\commonobject.class.php(5392): dol_eval('$db->fetch_obje...', 1, 0) #3 D:\dolibarr\www\dolibarr\htdocs\core\tpl\extrafields_list_print_fields.tpl.php(55): CommonObject->fetch_optionals('1', Array) #4 D:\dolibarr\www\dolibarr\htdocs\product\list.php(1351): include('D:\\dolibarr\\www...') #5 {main} thrown in D:\dolibarr\www\dolibarr\htdocs\core\db\mysqli.class.php on line 310` 
This is the error I get.
So what I might be writing wrong is the query part. Thanks a lot for your time and patience in advance.

**Comment by Hystepik** [comment]
Sorry if I did not explain myself properly just copy paste all of the lines below this and it may work for you:
$db->fetch_object($db->query('SELECT reel FROM llx_product_stock as ps WHERE ps.fk_product='.$object->id.';'))->reel*$object->array_options['C33']

**Comment by coding1wolf** [comment]
Don´t worry, my fault. I did copy and paste that code and still get the same error. Do you have an idea why is that? Thank´s

**Comment by Hystepik** [comment]
Maybe if you copy paste this by replacing by "Codigo" attribute of the field needed?
($req =$db->query('SELECT reel FROM llx_product_stock as ps WHERE ps.fk_product='.$object->id.';')) && ($req = $db->fetch_object($req))? $req->reel*$object->array_options['options_\<Codigo\>'] : -1

**Comment by coding1wolf** [comment]
Well, this time it didn´t give me back an error, but still doesn´t work because it always gives me back -1. I´m sorry for the headackes. I think it ain´t getting the right value from the SQL request, but not sure how to do it. Thank you very much for your time!
Edit:
When I wrote only this code: `($req =$db->query('SELECT reel FROM llx_product_stock as ps WHERE ps.fk_product='.$object->id.';')) && ($req = $db->fetch_object($req))? $req->reel`, just to check if it worked I got this error: `Parse error: syntax error, unexpected ';' in D:\dolibarr\www\dolibarr\htdocs\core\lib\functions.lib.php(7205) : eval()'d code on line 1`
So Somewhy the issue I guess is while getting the info from the database

**Comment by coding1wolf** [comment]
@Hystepik Hello, sorry for coming againg with this issue, but do you a clue how to solve it?, maybe by writting the code on the right php document? Thanks for your time

**Comment by Hystepik** [comment]
Hello @coding1wolf, have you tried to remove .';' : 
 $db->query('SELECT reel FROM llx_product_stock as ps WHERE ps.fk_product='.$object->id)&& ($req = $db->fetch_object($req))? $req->reel : -1
 like this maybe

**Comment by coding1wolf** [comment]
Still gives me back -1, that query should work, but doesn´t. I was thinking maybe by writting it on the extrafields_add.tpl.php, but not sure how to do it.

**Comment by Hystepik** [comment]
oh I forgot to ask you . What is the version of your dolibarr ?

**Comment by coding1wolf** [comment]
12.0.2

**Comment by Hystepik** [comment]
I don't understand it works for me in 12.0.4
Sorry I have no idea of what is the problem

**Comment by coding1wolf** [comment]
It´s fine, don´t worry I´ll keep trying it. Thank you so much for your time

**Comment by coding1wolf** [comment]
@eldy, could you help me with this? Thanks!

**Comment by ksar-ksar** [comment]
Hello,

For this kind of help, please go to the forums : https://www.dolibarr.org/forum.php
