### ISSUE TITLE
MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND not work

### ISSUE THREAD

**Issue by dadyhood** [Dolibarr/dolibarr#16043]
Hi,

I have a probleme with the VAT calculation so i tried to use MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND but it look that don't work correctly. 

Here the report : 
" Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l’option $dolibarr_main_prod sur ‹ 1 › pour supprimer quelques notifications):
Date: 20210107182405
Dolibarr: 11.0.5
Niveau de fonctionnalités: 0
PHP: 5.5.12
Server: Apache/2.4.9 (Win32) PHP/5.5.12
OS: Windows NT LAPTOP-5A456MB2 6.2 build 9200 (Windows 8 Home Premium Edition) i586
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

Url sollicitée: /dolibarr/comm/propal/card.php?id=41
Referer: http://localhost/dolibarr/comm/propal/card.php?id=41
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, expensereport, propal, accounting, agenda, cron, ecm, facture, ficheinter, fournisseur, holiday, resource, salaries, societe, service, tax, loan, banque, margin, product, prelevement, stock, projet, fckeditor, import, export
Message: A rounding difference was detected into TOTAL but is too high to be corrected. Some data in your line may be corrupted. Try to edit each line manually."

Anyone who know how to do the VAT calculation on sum total and not line by line ?

Thanks for your answer.

**Comment by atm-maxime** [comment]
Duplicate #14705
