### ISSUE TITLE
Email collector

### ISSUE THREAD

**Issue by riker513** [Dolibarr/dolibarr#16047]
Hi there,

I was unable whether to file this as feature request or bug report, but I decided for the latter.

There is absolutely no documentation for the email collector module - what a pity in view of the work that has been put into it.
Without documentation, it's unclear to set up the system properly for non-standard use cases.

For instance, what if I want to forward all sales leads to Dolibarr's email adress. To help Dolibarr with sorting the mail to the right project contact, I manually paste the client's email address into the subject line of the mail I forward to Dolibarr (because otherwise it will be too ambiguous, and the sender of the mail is not the client but me).

Apparently, with commands such as
`$subject=EXTRACT:SUBJECT:([^\s]);$message=EXTRACT:BODY:([^\s]);$origin_email=EXTRACT:HEADER:X-From:.[^\s]+(.)`
I can do this.

Now a 3rd-party indeed is being created and attached to the project that is also created. This is a very valuable help because otherwise that always needs to be done manually. However, I know no way for how to tell Dolibarr to also use the email address from teh subject line for the new 3rd party entry. The way it is now, it will have the wrong name and wrong contact (mine in this case).

Are there are similar tags as the one described, but now for the automatic creation of 3rd parties? Can we create a documentation for this module?

**Comment by ksar-ksar** [comment]
Hi,

You can help for the documentation, create your account and participate to this page : https://wiki.dolibarr.org/index.php?title=Module_EMail_Collector
