### ISSUE TITLE
Unknown column 's.fk_warehouse' in 'field list'

### ISSUE THREAD

**Issue by theyough** [Dolibarr/dolibarr#16057]
# Bug

First, i got SQL error when i install the project about a foreign key `fk_warehouse` which is missing.
Now, when i try to create a supplier, i got this error `Unknown column 's.fk_warehouse' in 'field list'`

## Environment
Date: 20210124153452
Dolibarr: 14.0.0-alpha - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.3.26
Server: Apache/2.4.38 (Debian)
OS: Linux 05fb6d0918c6 5.8.0-38-generic #43-Ubuntu SMP Tue Jan 12 12:42:13 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

Url sollicitée: /fourn/card.php?socid=2
Referer: http://127.0.0.1/societe/card.php
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, receiptprinter, product, variants, takepos, banque, categorie, blockedlog, facture, societe, fournisseur, margin, propal, stock, expedition, commande
Type gestionnaire de base de données: mysqli

## Steps to reproduce the behavior
Modules/Applications: user, receiptprinter, product, variants, takepos, banque, categorie, blockedlog, facture, societe, fournisseur, margin, propal, stock, expedition, commande
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: 

```
SELECT s.rowid, s.nom as name, s.name_alias, s.entity, s.ref_ext, s.address, s.datec as date_creation, s.prefix_comm, s.status, s.fk_warehouse, s.price_level, s.tms as date_modification, s.fk_user_creat, s.fk_user_modif, s.phone, s.fax, s.email, s.socialnetworks, s.url, s.zip, s.town, s.note_private, s.note_public, s.model_pdf, s.client, s.fournisseur, s.siren as idprof1, s.siret as idprof2, s.ape as idprof3, s.idprof4, s.idprof5, s.idprof6, s.capital, s.tva_intra, s.fk_typent as typent_id, s.fk_effectif as effectif_id, s.fk_forme_juridique as forme_juridique_code, s.webservices_url, s.webservices_key, s.accountancy_code_buy, s.accountancy_code_sell, s.code_client, s.code_fournisseur, s.code_compta, s.code_compta_fournisseur, s.parent, s.barcode, s.fk_departement as state_id, s.fk_pays as country_id, s.fk_stcomm, s.remise_supplier, s.mode_reglement, s.cond_reglement, s.transport_mode, s.fk_account, s.tva_assuj, s.mode_reglement_supplier, s.cond_reglement_supplier, s.transport_mode_supplier, s.localtax1_assuj, s.localtax1_value, s.localtax2_assuj, s.localtax2_value, s.fk_prospectlevel, s.default_lang, s.logo, s.logo_squarred, s.fk_shipping_method, s.outstanding_limit, s.import_key, s.canvas, s.fk_incoterms, s.location_incoterms, s.order_min_amount, s.supplier_order_min_amount, s.fk_multicurrency, s.multicurrency_code, fj.libelle as forme_juridique, e.libelle as effectif, c.code as country_code, c.label as country, d.code_departement as state_code, d.nom as state, st.libelle as stcomm, st.picto as stcomm_picto, te.code as typent_code, i.libelle as label_incoterms, sr.remise_client, model_pdf FROM llx_societe as s LEFT JOIN llx_c_effectif as e ON s.fk_effectif = e.id LEFT JOIN llx_c_country as c ON s.fk_pays = c.rowid LEFT JOIN llx_c_stcomm as st ON s.fk_stcomm = st.id LEFT JOIN llx_c_forme_juridique as fj ON s.fk_forme_juridique = fj.code LEFT JOIN llx_c_departements as d ON s.fk_departement = d.rowid LEFT JOIN llx_c_typent as te ON s.fk_typent = te.id LEFT JOIN llx_c_incoterms as i ON s.fk_incoterms = i.rowid LEFT JOIN llx_societe_remise as sr ON sr.rowid = (SELECT MAX(rowid) FROM llx_societe_remise WHERE fk_soc = s.rowid AND entity IN (1)) WHERE s.entity IN (1) AND s.rowid = 2
```

Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 's.fk_warehouse' in 'field list'

Message: Unknown column 's.fk_warehouse' in 'field list'

**Comment by frederic34** [comment]
@theyough you are testing V14 you need sometimes to rerun instal/upgrade script, fk_entrepot has been renamed fk_warehouse

**Comment by theyough** [comment]
Thank you @frederic34 i will try to fix the issue by PR, do you know from where I can start to watch

**Comment by frederic34** [comment]
did you rerun upgrade ?

**Comment by frederic34** [comment]
go to install, and run last updgrade script (V14)

**Comment by theyough** [comment]
yes it works, thank you, btw i don't understand why when you order a product to a supplier you can create an invoice, it should be the supplier who emit an invoice to you ?

**Comment by frederic34** [comment]
it a "copy" of the supplier invoice, so you can register payments, pdf from the the supplier etc...
