### ISSUE TITLE
Captcha With Edge Or Chrome

### ISSUE THREAD

**Issue by TheRusty** [Dolibarr/dolibarr#16051]
# Bug
Captcha doesn't work with Edge Version 87.0.664.75 or Chrome Version 87.0.4280.141

But it works fine with FireFox 84.0.2

## Environment
- **Version**: v10, v12, v13, v14

**Comment by catrielr** [comment]
It works perfect for me on Dolibarr 12.0.4 in: 
Crome: 
Versión 87.0.4280.141 (Build oficial) (64 bits)
Versión 88.0.4324.104 (Build oficial) (64 bits)

Edge: 
Versión 87.0.664.75 (Compilación oficial) (64 bits)
Versión 88.0.705.50 (Compilación oficial) (64 bits)

**Comment by ksar-ksar** [comment]
Hello,

Also working for me.
