### ISSUE TITLE
The Unit of Product always show extra label "unit" on front of unit code

### ISSUE THREAD

**Issue by wesleychong21** [Dolibarr/dolibarr#16060]
# Bug
The Unit of Product always show extra label "unit" on front of unit code

## Environment
- **Version**: 13.0
- **OS**: Windows NT LAPTOP-ED714H77 10.0 build 19041 (Windows 10) AMD64
- **Web server**: Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/7.4.13
- **PHP**: 7.4.13
- **Database**: 5.5.5-10.4.17-MariaDB

- **URL(s)**: /product/card.php?id=1

## Expected and actual behavior
Product show show label or short_label in Unit 

## Steps to reproduce the behavior
go to /product/card.php?id=1

Actually I already fixed it. just go to line 5425 of \htdocs\product\class\product.class.php
replace function getLabelOfUnit($type = 'long') with below code. ( I wish to contribute back to community, please let me know to become official developer. )
```

public function getLabelOfUnit($type = 'long')
    {
        global $langs;

        if (!$this->fk_unit) {
            return '';
        }

        $langs->load('products');

        $label_type = 'label';

        if ($type == 'short') {
            $label_type = 'short_label';
        }
        else {
            $label_type = 'label';
        }
        

        $sql = 'select '.$label_type.', code from '.MAIN_DB_PREFIX.'c_units where rowid='.$this->fk_unit;
        $resql = $this->db->query($sql);
        if ($resql && $this->db->num_rows($resql) > 0) {
            $res = $this->db->fetch_array($resql);
            $label = $res[$label_type];
            $this->db->free($resql);
            return $label;
        } else {
            $this->error = $this->db->error().' sql='.$sql;
            dol_syslog(get_class($this)."::getLabelOfUnit Error ".$this->error, LOG_ERR);
            return -1;
        }
    }


```
## [Attached files]
![unit-label](https://user-images.githubusercontent.com/55903515/105661393-3cd68180-5f08-11eb-9de5-b087393e58f2.png)
![unit-label2](https://user-images.githubusercontent.com/55903515/105661401-44962600-5f08-11eb-80de-c742a87d3721.png)

**Comment by catrielr** [comment]
It is not a BUG, ​​the function is correct.
Check your lang file
