### ISSUE TITLE
 Unknown column 'datestartvalidity' in 'field list'

### ISSUE THREAD

**Issue by sebastienserre** [Dolibarr/dolibarr#16068]
# Bug
Hello,

I've just updated from Dolibarr 12.0.4 to Dolibarr 13.0 and got this error:  Unknown column 'datestartvalidity' in 'field list'
Impossible to log in.

Thank you

## Environment
- **Version**: 13.0
- **Web server**: Apache 2.4
- **PHP**: PHP 7.3
- **Database**: [*Database type and version*]
- **URL(s)**:  https://compta.thivinfo.com

**Comment by eldy** [comment]
Try to rerun the migration 12.0 to 13.0. This field should be added during this migration.

**Comment by sebastienserre** [comment]
Hello and thanks @eldy 
I have installed a new 12.0.4 and then migrate successfully to 13.0
I upgrade to 12.04 from years and maybe something was wrong in files...
