### ISSUE TITLE
Add signature date and user on propal

### ISSUE THREAD

**Issue by lvessiller-opendsi** [Dolibarr/dolibarr#16062]
Add signature date and user on propal
- add a new date (date_signature) with user identification (fk_user_signature) in "llx_propal" table
- add "signature()" method in propal class like "cloture()" to update propal status and signature date
- update "date_signature" and "fk_user_signature" with "date_cloture" and "fk_user_cloture" in Dolibarr upgrade process

At this moment we only have one field in database (date_cloture).
It's useful to  differentiate signature (date_signature) and close (date_cloture) dates for statistics.

**Comment by lvessiller-opendsi** [comment]
@eldy 
What do you think about this feature ?
Have you any comment ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
I would like your advice before begining to develop this feature ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
Have you any suggest ?

**Comment by eldy** [comment]
Yes, you can add a date and user to save who signed and when it was signed and not having this values erased when we close the proposal by setting it to the status "Billed". 
In migration, you can fill this new value with the date_close and user_close to have data not empty after a migration.
