### ISSUE TITLE
No pmp valuation of stock movements in gpao/mrp

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#16072]
# Bug
*When we produce a production order, the movements of stocks do not inform the value of the bpm of the products manufactured
See line 289 of mrp/mo_production.php
The inventory is wrong. The sale of products does not allow the calculation of margins
The pmp should be calculated and/or entered at the time of production*

## Environment
- **Version**: *12.0.4*

french forum's link : https://www.dolibarr.fr/forum/t/pmp-null-sur-produits-manufactures/35296

**Comment by eldy** [comment]
What do you mean with "inventory is wrong" ?
What do you mean with "The sale of products does not allow the calculation of margins" ?

Note that AWP (PMP in french) is currently affected only when we buy a product and product is entering the stock. By definition an AWP changes only when there is a stock entry. But a manufacturing is a stock entry of manufactured product, so we can imagine that the AWP can be affected in this case. Currently it is not.

When a production is done, a new input field should be available to enter the value of cost price (prefilled according to BOM cost price value or re-using the current AWP value of product), and we use it in line 289 de mrp/mo_production.php when calling

$idstockmove = $stockmove->reception($user, $line->fk_product, GETPOST('idwarehousetoproduce-'.$line->id.'-'.$i), $qtytoprocess, 0, $labelmovement, '', '', GETPOST('batchtoproduce-'.$line->id.'-'.$i), dol_now(), $id_product_batch, $codemovement);

to replace the 0 with the value.
