### ISSUE TITLE
CLOSE not working

### ISSUE THREAD

**Issue by pcworxstech** [Dolibarr/dolibarr#16082]
# Bug
[*CLOSE button not working in SHIPMENT card*]

## Environment
- **Version**: [*13.0*]
- **OS**: [*Linux*]
- **Web server**: [*Apache*]
- **URL(s)**: [*/dolibarr/expedition/card.php*]

## Expected and actual behavior
[*When clicking the CLOSE button on shipment card, it should change the status from VALIDATED to DELIVERED and remove inventory if setting is set to decrease on shipment close.   This does not work when CLOSE button is "clicked".*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*
![v13_close_bug](https://user-images.githubusercontent.com/54542571/106010271-7c22e080-6076-11eb-9cbf-3d146f1a3e6d.PNG)
  *]

**Comment by cfoellmann** [comment]
Is working as it should now.

CLOSE

**Comment by cfoellmann** [comment]
in 14.x

**Comment by pcworxstech** [comment]
Negative.

I did upgrade to 14.0.1 and the same issue exists as well.


Wayne Priem
928-607-7267
***@***.***

**Comment by cfoellmann** [comment]
Can you activate the debug bar and set the log level to debug?

**Comment by cfoellmann** [comment]
I just tested on 14.x and develop again. Works for me
