### ISSUE TITLE
Projects Module: DB_ERROR_42803

### ISSUE THREAD

**Issue by AMusketeer** [Dolibarr/dolibarr#16084]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Long story Short: I launched an EC2 instance on AWS to run Dolibarr v13, running PostgreSQL 12.4 on RDS, and Dolibarr itself on Ubuntu 20.04 LTS. All DIY, not Bitnami’s AMI. When I use the Projects Module none of the data is able to load.

## Environment
- **Version**: 13.0.0
- **OS**: Ubuntu 20.04 LTS
- **Web server**:  Apache/2.4.41 (Ubuntu)
- **PHP**: 7.4.3
- **Database**: PostgreSQL 12.4
- **URL(s)**: /dolibarr/projet/index.php?mainmenu=project&leftmenu=

## Expected and actual behavior
Should show me what projects are open and in draft.

## [Attached files]
![Capture](https://user-images.githubusercontent.com/10450017/106048056-64694d80-60b2-11eb-9421-a9c99e3885ec.PNG)

**Comment by eldy** [comment]
Fixed by b488bca02016766462fe9042f94c374dc6038f69
