### ISSUE TITLE
Bug: TCPDF ERROR: Could not include font definition file: roboto

### ISSUE THREAD

**Issue by bvlahovic77** [Dolibarr/dolibarr#16081]
after clean installation dolibarr 13.0.0. on debian 10.7, after validating vendor payment we receive following

TCPDF ERROR: Could not include font definition file: roboto

# Bug
[*Short description*]

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: apache2handler 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1
- **URL(s)**: /dolibarr/fourn/facture/list.php?leftmenu=suppliers_bills_notpaid&search_status=1

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Which package did you used to install dolibarr ?
The zip file, tgz or the .deb ?
