### ISSUE TITLE
Recalculate Method 1 / 2 not working

### ISSUE THREAD

**Issue by dimitrievski5** [Dolibarr/dolibarr#16108]
Hi,

I make upgrade on V13 of Dolibarr, but Recalculate Methods in vendor invoice still not working.
Now and final price is not rounding.
When i click on Method 1 or Method 2 nothing happen... 

If i set "Step of rounding range (for countries where rounding is done on something other than base 10. For example, put 0.05 if rounding is done by 0.05 steps) = 1" and click on Method 2 i get this error

**Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20210129224010
Dolibarr: 13.0.0 - https://www.dolibarr.org
Level of features: 0
PHP: 7.2.34
Web Server: Apache
OS: Linux wizard.zemi.mk 3.10.0-962.3.2.lve1.5.38.el7.x86_64 #1 SMP Thu Jun 18 05:28:41 EDT 2020 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36

Requested URL: /fourn/facture/card.php?id=424&action=calculate&calculationrule=roundoftotal
Referer: /fourn/facture/card.php?id=424&action=calculate&calculationrule=totalofround
Menu manager: eldy_menu.php

Modules/Applications: user, expedition, cron, commande, ecm, facture, fournisseur, salaries, societe, service, variants, export, propal, supplier_proposal, banque, margin, product, stock, categorie, tax, fckeditor, comptabilite, import
Message: A rounding difference was detected into TOTAL but is too high to be corrected. Some data in your line may be corrupted. Try to edit each line manually.**

I need to make round on final price (Final price with VAT).
I hope on solution about this problem.

Best Regards,
Martin

**Comment by zuiko** [comment]
@dimitrievski5 be careful, for the moment, the fixing reference is wrong for this issue...

**Comment by dimitrievski5** [comment]
> @dimitrievski5 be careful, for the moment, the fixing reference is wrong for this issue...

Hi @zuiko, yes i know that is wrong... I hope that someone will find the fix for this bug...
