### ISSUE TITLE
confirmation of the order / letter

### ISSUE THREAD

**Issue by klausking** [Dolibarr/dolibarr#16116]
# Feature Request
[*confirmation of the order / letter management *]

It would be great if in future versions it would be possible to send an order confirmation to customers. 
It would also be great if there was the possibility to write letters and be able to send them by e-mail straight away 
That would round off the program and you would not need additional software

**Comment by fbosman** [comment]
This confirmation is standard Dolibarr, or do you mean something else?

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 30 jan. 2021 om 19:05 heeft klausking <notifications@github.com> het volgende geschreven:

﻿
Feature Request

[*confirmation of the order / letter management *]

It would be great if in future versions it would be possible to send an order confirmation to customers.
It would also be great if there was the possibility to write letters and be able to send them by e-mail straight away
That would round off the program and you would not need additional software

**Comment by klausking** [comment]
For me that was always a module to answer incoming online orders as a control mail, therefore.
But yes, I understand what you mean, I just use it a little differently and therefore no longer have the "normal" order confirmation fpr other Customers. 
But writing letters would still be a good idea in my opinion.

**Comment by fbosman** [comment]
You can sent an email from the card...
