### ISSUE TITLE
Packing slip module 

### ISSUE THREAD

**Issue by klausking** [Dolibarr/dolibarr#16115]
# Feature Request
[*Packing slip module *]

It would be great if a module were added in the future, where a packing slip can also be created in the course of a delivery. 
This is actually common in online trading.

**Comment by fbosman** [comment]
Currently I implemented this as an extra template, which is processed at the approval of a shipment.

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 30 jan. 2021 om 19:02 heeft klausking <notifications@github.com> het volgende geschreven:

﻿
Feature Request

[*Packing slip module *]

It would be great if a module were added in the future, where a packing slip can also be created in the course of a delivery.
This is actually common in online trading.
