### ISSUE TITLE
Bug: Sales Order - Unit Price (currency) cannot be record while adding a Product Line

### ISSUE THREAD

**Issue by henrynopo** [Dolibarr/dolibarr#16119]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Sales Order - Unit Price (currency) cannot be recorded while adding a Product Line

## Environment
Version: 12.0.3 - 13.0.0
OS: Linux mankey.sgcloudhosting.com 3.10.0
Web server: Apache
PHP: 7.2.33
Database: MySQL or MariaDB 5.7.32
URL(s): dolibarr/compta/facture/card.php

## Expected and actual behavior
The multi-currency module is actived for my Dolibarr.
To add a new product line in Sales Order, the system does record the Unit Price (currency) I key in. 
However, once the product is added, I can update the U.P. (currency) correctly.
Such a bug exists only for Sales Order but not for Purchase Order.

Similar bug exists for Supplier Invoice.

**Comment by futurehousestore** [comment]
This happens in my Dolibarr version 13 in Purchase Orders. When I create a new PO and add products the products purchase prices are not displayed. The prices equal to 0 instead of the saved price in product buying prices tab. All the purchase prices need to be added manually. I also use the multicurrency module.

**Comment by haade-administrator** [comment]
same problem
