### ISSUE TITLE
Ticket assigned list view

### ISSUE THREAD

**Issue by Nicofol** [Dolibarr/dolibarr#16117]
An internal user can see all tickets, not just their own assigned. It is important that each user can **only see** their assigned tickets. The admin could decide who see what by permissions rules or other configurations. See attach image as an example made by an external ticketing 3part module...they add this feature in the module features.
![Immagine 2021-02-02 233854](https://user-images.githubusercontent.com/56766857/106672314-63975680-659f-11eb-8fce-1c17021a1f60.png)

**Comment by Nicofol** [comment]
Hello, are there chance to have this feature?

**Comment by artemChernitsov** [comment]
@Nicofol try to set global value TICKET_LIMIT_VIEW_ASSIGNED_ONLY to 1. 
<img width="1918" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/18346730/a0a5db79-88b7-4771-86f3-55ef7203d34d">

**Comment by Nicofol** [comment]
Hello, thank you, it seems to work correctly. Tks.

**Comment by artemChernitsov** [comment]
Yes, but it has "bug" - my list of tickets doesn't display tickets for which I'm a collaborator...
Also, anybody can paste any ticket ID and open it /ticket/card.php?id=ANY_ID. The ticket doesn't check access permissions by user at all.
