### ISSUE TITLE
BUG - V13.0.0 - Bank Balancing BUG

### ISSUE THREAD

**Issue by klausking** [Dolibarr/dolibarr#16114]
# Bug
Balancing the bank account returns a white website  you cannot continue.

## Environment
- **Version**: [*V13.0.0)*]
- **OS**: [*Apache/2.4.43 (Unix)*]
- **PHP**: [*7.4.13*]
- **Database**: [*mysqli (5.5.54)*]

If you want to balance an bank account, a white blank page appears after you click on balance and you cannot continue.
The balance itself is carried out

**Comment by ksar-ksar** [comment]
Hi,

White screen usually means PHP error => What does your logs say ?

**Comment by klausking** [comment]
Can be closed, that was a permission thing of the folder
