### ISSUE TITLE
V12.x V13.X decimal quantity in expense reports line on editline

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#16127]
# Bug
quantity can be decimal in expens reports line on addnewline action but not on editline action

## Environment
- **Version**: tested V12.x V13.X
- /expensereport/card.php

in action addnewline,  the field is:
`print '<input type="text" min="0" class="right maxwidth50" name="qty" value="'.dol_escape_htmltag($qty ? $qty : 1).'">'; // We must be able to enter decimal qty`

-> in action editline:
`print '<input type="number" min="0" class="right maxwidth50" name="qty" value="'.dol_escape_htmltag($line->qty).'" />';`
should be
`print '<input type="text" min="0" class="right maxwidth50" name="qty" value="'.dol_escape_htmltag($line->qty).'" />'; // We must be able to enter decimal qty`

**Comment by manu-p** [comment]
Hi, is it still a bug? Has it been fixed?

**Comment by manu-p** [comment]
Any news? See you next year! (or not) :-D

**Comment by priojk** [comment]
I think, this issue should be re-opened, IF it is still a bug. But is it indeed the case? Last year you just asked. It would be helpful to check in the current release and re-open only, if it is still relevant.

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue in develop.
Feel free to reopen if not.
