### ISSUE TITLE
Translation of opensurvey could not be used in Chinese (Taiwan)

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#16129]
# Instructions
Translation of opensurvey could not be used in Chinese (Taiwan)

# Bug
When  go to poll page , all words are still in english .
Even edit lang file and go to poll page  , that still don’t work .
But you could translate by go to translation function page .

## Environment
Version: [Version 13]
OS: [Windows 7 and MX linux 19.3]
Web server: [Apache 2.4.41]
PHP: [7.4.1]
Database: [MariaDB 5.5.5-10.4.11]

**Comment by eldy** [comment]
What do you mean with "could not be used" ? If text is still in english, in probably means text were not translated yet.
In such a case, fix must be done on 
https://www.transifex.com/dolibarr-association/dolibarr/dashboard/

**Comment by trekmorris** [comment]
Hi

I have translated , please refer the attachments .
Also i attach the translation file that download from transifex , you could
see all words are translate .

And as my testing , even i try to translate opensurvey.lang  , the poll
area still is in english .
Otherwise i have to use translation function in dolibarr .

![transifex translate 01](https://user-images.githubusercontent.com/78349579/106549030-1ab5b280-654b-11eb-81d5-3c7478443d91.png)
![image](https://user-images.githubusercontent.com/78349579/106549548-2eade400-654c-11eb-8231-558abbe78d50.png)

Update the screenshot in enginlish
![image](https://user-images.githubusercontent.com/78349579/107477762-4d972080-6bb3-11eb-906d-7398ef0efc51.png)

**Comment by eldy** [comment]
Can you also paste the page that is in english instead of chinese (screenshot of full page showing also the url of page)

**Comment by trekmorris** [comment]
Hi

I have updated the screenshot .

Laurent Destailleur <notifications@github.com> 於 2021年2月10日 週三 上午9:59寫道：
