### ISSUE TITLE
Couldn't export contact information to odt template in v13 and v14 beta

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#16128]
# Instructions
Couldn't export contact information to odt template in dolibarr v13  and v14 beta .

# Bug
Couldn't export contact information to odt template in v13 and v14 beta
## Environment
- **Version**: [Version 13][Version 14]
- **OS**: [*Windows 7*][*MX Linux 19.3*]
- **Web server**: [*Apache 2.4.41*]
- **PHP**: [*7.4.1*]
- **Database**: [*MariaDB 5.5.5-10.4.11*]
![odt error](https://user-images.githubusercontent.com/78349579/106441882-91a06c00-64b5-11eb-93e4-2a62ac1d0171.png)

**Comment by eldy** [comment]
For which document (an order, invoice, proposal, ... ?)

**Comment by trekmorris** [comment]
Hi 
I found this issue by using proposal .
And i try to test in vendor proposal , when i want to add a new contact it shows out a error "Wrong value for parameter 2" .
So i could not konw if the vendor proposal or others will get this issue or not .
![image](https://user-images.githubusercontent.com/78349579/106548842-b561c180-654a-11eb-863d-3444a547ad11.png)

**Comment by trekmorris** [comment]
Hi ALL

  I refer the solution from #16692 by danloic . So i try to replace all files in  " htdocs\core\modules\propale " from dolibarr 12.0.4 .
And after that , all fields are working .

**Comment by trekmorris** [comment]
I have tried 14.0.0 beta , and this version does not fix this issue .

**Comment by ksar-ksar** [comment]
Hello,

One workaround proposed by Libremaster is to put MAIN_USE_COMPANY_NAME_OF_CONTACT to 0 in Setup->Other

**Comment by trekmorris** [comment]
> Hello,
> 
> One workaround proposed by Libremaster is to put MAIN_USE_COMPANY_NAME_OF_CONTACT to 0 in Setup->Other

Hi 

It works on v 13 and v14 . Thanks
