### ISSUE TITLE
Allow to open in a new TAB of the browser the printed Barcodes

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#16123]
The print barcode tool produce a PDF after clicking in the button "GENERATE PAGE TO PRINT", but the pdf generated is displayed replacing the current TAB of the browser, losing the session in dolibarr, if a PDF viewer plugin is installed in the browser.

So using the tool to print several different barcodes,  is annoying to need to open the URL of  dolibarr again to return to the barcode printing tool again.

Kindly add the option in the configuration of the barcode module, to allow to select "open a new tab" or "Replace current tab", in similar way that is already working in the bookmarks module, that allows both cases
![barcode_pdf_in_a_new_tab](https://user-images.githubusercontent.com/7486607/106381093-87b53500-63f1-11eb-86b5-7aabdfdaea40.png)

**Comment by eldy** [comment]
Which browser did you use ? The file should be downloaded and not opened.
Can you try with chrome.

**Comment by edupulpillo** [comment]
The problem still is present in Firefox and Chrome in v13.0.0
