### ISSUE TITLE
Impossible to export payment

### ISSUE THREAD

**Issue by sebastienserre** [Dolibarr/dolibarr#16134]
# Instructions
I've created a report to know which payment has been made.
I'd like to have a csv or "excel" format to create an automated sheet.

# Bug
Payment are not exported

## Environment
- **Version**: 13.0 (maybe before, not tested
- **OS**: Debian9
- **Web server**: Apache 2.4
- **PHP**: 7.3

The query below return an empty report:
```
Requête SQL utilisée pour extraire les données:
SELECT DISTINCT s.nom as s_nom, f.ref as f_ref, f.fk_statut as f_fk_statut, p.rowid as p_rowid, p.amount as p_amount, p.datep as p_datep FROM llx_societe as s LEFT JOIN llx_c_country as c on s.fk_pays = c.rowid LEFT JOIN llx_c_departements as cd on s.fk_departement = cd.rowid, llx_facture as f LEFT JOIN llx_projet as pj ON f.fk_projet = pj.rowid LEFT JOIN llx_user as uc ON f.fk_user_author = uc.rowid LEFT JOIN llx_user as uv ON f.fk_user_valid = uv.rowid LEFT JOIN llx_facture_extrafields as extra ON f.rowid = extra.fk_object LEFT JOIN llx_paiement_facture as pf ON pf.fk_facture = f.rowid LEFT JOIN llx_paiement as p ON pf.fk_paiement = p.rowid LEFT JOIN llx_c_paiement as pt ON pt.id = p.fk_paiement LEFT JOIN llx_bank as b ON b.rowid = p.fk_bank LEFT JOIN llx_bank_account as ba ON ba.rowid = b.fk_account WHERE f.fk_soc = s.rowid AND f.entity IN (1) and date_format(p.datep,'%Y') > '2021'
```

**Comment by atm-maxime** [comment]
Maybe because your filter is where date of payment is > 2021 ? Did you start record 2022 payments ?

**Comment by sebastienserre** [comment]
arf your right. Thank you @atm-maxime .
It works with `>20210101`, I have some results but payment made before 12.0.4 => 13.0 lost their payment link
Invoice Payment info before migration:
![dolibarr12 0 4](https://user-images.githubusercontent.com/3902621/106561613-4e7fe080-6529-11eb-8da1-13525a028228.png)
Invoice Payment info after migration:
![dolibarr13 0](https://user-images.githubusercontent.com/3902621/106561653-5d669300-6529-11eb-89fc-75fb67bba995.png)

It results payment are not in this export.

Could you help me to correct this bug ?
