### ISSUE TITLE
Automatic email notification midification error for existing Agenda/Events

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#16130]
# Bug
[Error on automatic email notification reminder settings for any **agenda/event**. We have added new email template for Agenda Reminder. Now we have created a new agenda and checked the box, **Create an automatic reminder notification for this event** and selected the correct email template for the reminder. Now for some reason I wanted to modify the event. Now I click on the event and it opened. But at **Create an automatic reminder notification for this event** settings, **Default Mail Model** is selected by mistake. While tried to select my desired mail template and clicked on Save button, an error, **_Error creating the reminder notification for this event_** is shown. Detailed screenshots are attached. ]

## Environment
- **Version**: [*13.0.0*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4*]
- **PHP**: [*7.3*]
- **Database**: [*MySQL 5.7]
- **URL(s)**: [*comm/action/card.php?action=create&datep=20210201100000&backtopage=%2Fcomm%2Faction%2Flist.php%3F%26month%3D00%26year%3D2021*]

![Agenda email email remainder notification error](https://user-images.githubusercontent.com/1249577/106449911-7ed46a00-64aa-11eb-805c-f578b47ba933.png)
![Agneda default email templates error](https://user-images.githubusercontent.com/1249577/106449918-80059700-64aa-11eb-879d-297c1ab359c6.png)

[*Files*]

**Comment by eldy** [comment]
Thanks @alsoft10 
Did you try with 13.0.2 ? 
If big still occurs and you have a fix, you can push it by making a github PR

**Comment by alsoft10** [comment]
Hello @eldy 

Yes this bug is still present in 13.0.2. I will fix this problem and make a pull request.
