### ISSUE TITLE
Mail template attachement  = 0 or empty

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#16133]
# Bug
If in the input attachment there is 0 or empty on the model. The attachment is not deleted when selecting the model

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

**Comment by eldy** [comment]
For which type of email template for example,  invoice, proposal ?

**Comment by BB2A-Anthony** [comment]
I have a problèmes on propal and order

**Comment by BB2A-Anthony** [comment]
@eldy Close inssues becosed it's not a probleme in V13 or V14
