### ISSUE TITLE
TimeZone - Update Date Ticket

### ISSUE THREAD

**Issue by alyatis85** [Dolibarr/dolibarr#16141]
# Bug
Hello,
I restested on demo.dolibarr.org. Another bug on the updated ticket date displayed witch is also late from one hour as the realtime. 
I create the ticket : Creation Datetime OK
I update the ticket 15 minutes later : Update Datetime KO = 1 hour late

## Environment
demo.dolibarr.org

**Comment by ksar-ksar** [comment]
Hi,

See : https://github.com/Dolibarr/dolibarr/issues/16183#issuecomment-774342675

Can you try with V13.0.1 ?
