### ISSUE TITLE
Upgrade / install version 13 with PostgreSQL generates SQL Errors

### ISSUE THREAD

**Issue by jblion** [Dolibarr/dolibarr#16144]
# Bug
Install / Upgrade from 12 to 13 fails due to SQL errors

## Environment
- **Version**: 13.0.0
- **OS**: Debian GNU/Linux 10 (buster)
- **Web server**: Apache/2.4.38 (Debian) mpm-itk/2.4.7-04 OpenSSL/1.1.1g
- **PHP**: PHP 7.3.26-1
- **Database**: psql (PostgreSQL) 13.1 (Debian 13.1-1.pgdg100+1)

## Expected and actual behavior
When installing Dolibarr 13, we have following errors: 

```
Erreur SQL DB_ERROR_42830 ERREUR: 42830: il n'existe aucune contrainte unique correspondant aux clés données pour la table « llx_c_product_nature » référencée LOCATION: transformFkeyCheckAttrs, tablecmds.c:10351
```

When upgrading from 12 to 13, more errors are present: 

```
UPDATE llx_projet_task_time SET tms = null WHERE tms = 0;
ERREUR:  l'opérateur n'existe pas : timestamp without time zone = integer
LIGNE 1 : UPDATE llx_projet_task_time SET tms = null WHERE tms = 0;
```

This line is not "translated" correctly for PostgreSQL

```
ALTER TABLE llx_projet_task_time MODIFY COLUMN tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
```

(sorry, operating system in french)

## Steps to reproduce the behavior
Install or upgrade to 13 version with PostgreSQL database

**Comment by atm-maxime** [comment]
Same as in #16135 ?

**Comment by jblion** [comment]
I did not find the bug you reference. That's a duplicate.

In the related ticket it only mentions upgrade whereas the bug is also present when we perform a new install.
Will check linked bugs to see it that has been identified

**Comment by jblion** [comment]
Yes, duplicate.

**Comment by jblion** [comment]
Duplicate of #16135
