### ISSUE TITLE
The status of the checkboxes is not kept.

### ISSUE THREAD

**Issue by AurelienL7** [Dolibarr/dolibarr#16159]
# Bug
I created a module with an object. This object has a boolean property to display a checkbox.
When creating a new object, these checkboxes are not checked. Even if they are checked during the creation of the object, they are no longer checked on the next screen. The checkboxes remain checked when the object is modified.
In the database, if I checked the checkbox when creating the object, the database field records "0". If I don't check the checkbox, the field records "NULL". Instead of "0" or "1".

## Environment
- **Version**: 12.0.3
- **OS**: Mac
- **Web server**: localhost
- **PHP**: 7.4.6
- **Database**: MYSQL 5.7.23

## Expected and actual behavior
When I create my object, the checkboxes keep their status checked / unchecked. Expect the database field to be "0" or "1"

## Steps to reproduce the behavior
- Create an object with a boolean property.
- Add a new object, check the checkbox.
- After being redirected to the view list, the checkbox is not checked anymore.

**Comment by eldy** [comment]
Same with v13 ?

**Comment by AurelienL7** [comment]
It works on v13. But in the database the unchecked box has a "NULL" value and the checked box's value is "1".

**Comment by AurelienL7** [comment]
I don't know if its allowed but : bump. 
This is a blocking bug.
I didn't find a solution by myself.
