### ISSUE TITLE
Update purchase price with vendor order

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#16154]
Function request.

Add or update the "purchase prices" of a product in its file when an order is received or approved from a supplier when they have different prices, so that an updated price can always be used and stored for margin calculations.

**Comment by atm-maxime** [comment]
Specific hidden setup do this (https://wiki.dolibarr.org/index.php?title=Setup_Other)

SUPPLIER_ORDER_EDIT_BUYINGPRICE_DURING_RECEIPT ► Can modify the buying price used for PMP calculation when making a stock reception on a supplier order. ► (v6.0+) 

This option also updates the product supplier price so it's good for next orders.

**Comment by JuanBrillo** [comment]
I'm sorry, but I DO NOT agree, this function DOES NOT CHANGE OR UPDATE supplier prices in the ficha product file > purchase prices > supplier prices.

It is true that the PMP is updated (this was already done without said function activated).

What the module does not do is what I indicate, and it is in the list of supplier prices in the product file, update said prices, I just did the test in version 14, and nothing. It also does not update the best purchase price... which is only updated by inserting the supplier prices (for each supplier on each order card) manually.


If a supplier order inserts a product that is worth 10, but in the product file, it is worth 7, when you receive the product, and you insert the price of 10, it DOES NOT UPDATE said price in the supplier sheet, nor the best price, the old price continues to appear... so that in the following orders that are made, the indicated price will continue to be the same as that which appears in the product file > purchase prices > supplier prices.

And the same thing happens to me in 4 different installations that I have of dolibarr, in 8, 9, 14, and 15 beta.

**Comment by morafat81** [comment]
any solution for the buying prices to be updated on validating vendor invoices? and to be listed in the product page under the Vendor prices list?

**Comment by sergioponguta** [comment]
Any update on this?
