### ISSUE TITLE
Wrong max decimals shown in widgets and bank module.

### ISSUE THREAD

**Issue by vlehemonet** [Dolibarr/dolibarr#16150]
# Bug

Even if the "Max. decimals for prices shown on screen" is set to two, it show 8 decimals in the home screen and in the bank module.

## Environment
- **Version**: 13.0.0
- **OS**: Debian 10
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: PHP 7.3.19-1~deb10u1
- **Database**: 10.3.25-MariaDB-0+deb10u1 Debian 10

## Expected and actual behavior

Even if the "Max. decimals for prices shown on screen" is set to two, it show 8 decimals in the home screen and in the bank module. We expecte to see two decimals in the home screen and the bank module.

## Steps to reproduce the behavior

Set "Max. decimals for prices shown on screen" to two in the "Limits/Precision setup", navigate to home screen or to the bank module

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![Configuration_EN](https://user-images.githubusercontent.com/65860127/106671446-8a906100-657c-11eb-8e62-16a11db3c217.PNG)

![home](https://user-images.githubusercontent.com/65860127/106671443-8a906100-657c-11eb-8f91-f69fe2f6de24.PNG)

![bank_module](https://user-images.githubusercontent.com/65860127/106671444-8a906100-657c-11eb-9640-4ce6a6fed9d1.PNG)

**Comment by Hystepik** [comment]
hello @vlehemonet, you need to use the Parameter : "Max. decimals for total prices" to change these prices
