### ISSUE TITLE
Bug: Emails sortants (module Emailing) - Field missing

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#16162]
When making a test mail under Emails sortants (module Emailing) there is no field for Destinataires (Le champ 'Destinataire(s)' est obligatoire)

Se
![testmail](https://user-images.githubusercontent.com/24247236/106802818-bd615480-6663-11eb-9d61-c6753ed7037c.JPG)
e image

# Bug
[*Short description*]

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1
- **URL(s)**: /azerty/htdocs/admin/mails_emailing.php

**Comment by ksar-ksar** [comment]
Hello,

Work for me in V13.0.0 : 
![image](https://user-images.githubusercontent.com/35605507/107420874-add98400-6b19-11eb-949a-303101fb3b52.png)

**Comment by hasse-basse** [comment]
Are we on the same page?  I'm here : 

/htdocs/admin/mails_emailing.php?action=test&mode=init

Below you'll find a print screen. If you don't have the same issue, could it be a difference in language versions? As you can see I'm in French. As you can see, I'm missing both recivers lines and the e-mail template choise

![test_mail](https://user-images.githubusercontent.com/24247236/107422562-78ce3100-6b1b-11eb-9c04-14264eff29b0.JPG)

**Comment by hasse-basse** [comment]
It works here,
/dolibarr/admin/mails.php?action=test&mode=init#formmailbeforetitle

But not here
/htdocs/admin/mails_emailing.php?action=test&mode=init

**Pls reopen**

**Comment by hasse-basse** [comment]
Hmm... I made a clean installation and it does not look the same as the old one

In my old installation there are more options in the top? How come ?? 

Below you'll find first the old installation (the one I'm using) and then the vanilla installation. Why is this difference?

![old](https://user-images.githubusercontent.com/24247236/107427590-e0877a80-6b21-11eb-8ec0-227917575630.JPG)
![new](https://user-images.githubusercontent.com/24247236/107427610-e7ae8880-6b21-11eb-9678-cdad9f94a5df.JPG)

**Comment by hasse-basse** [comment]
**### SOLVED** (or at least a bit on the way)

It is the settings for the Emailing module (module Emailing). You don't have it active so therefor it does not appear in your installation

**SO the problem is in the settings for the Emailing module;**

**Comment by hasse-basse** [comment]
It is still not working. When trying to send an Test email from Outgoing email (module Emailing) there is no field where to add the destination email address.  If I still try to send, the system complains and says there must be an destination email address.

So the bug is still there, it is impossible to send a test email from module Emailing
