### ISSUE TITLE
Affichage du temps / module interventions

### ISSUE THREAD

**Issue by JPDelaunay** [Dolibarr/dolibarr#16168]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Incohérence entre le temps d'intervention sais et le temps affiché

## Environment
- **Version**: 13.0.0
- **OS**: Linux h2web41 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64
- **Web server**: Apache
- **PHP**: 7.4.14
- **Database**: MySQL or MariaDB 5.7.32-log
- **URL(s)**: https://intranet.spexi.fr/fichinter/card.php

## Expected and actual behavior
Lors de la saisie de lignes d'intervention, le temps affiché est augmenté d'1 heure par rapport au temps saisi. Au retour en mode saisie on retrouve le bon temps, mais l'affichage est faux et les PDF aussi. C'est très problématique en production.

## Steps to reproduce the behavior
Créer une intervention
saisir une ligne avec par exemple 0h30 de temps passé
Ajouter la ligne
Constater que Dolibarr affiche 1h30 au lieu de 0h30

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by Hystepik** [comment]
It works well for me in version 13.0.1

**Comment by JPDelaunay** [comment]
Nice, but 13.0.1 is not available yet…

**Comment by ksar-ksar** [comment]
> 
> 
> Nice, but 13.0.1 is not available yet…

Just download the V13 branch from GitHub to have the V13.0.1

See : https://github.com/Dolibarr/dolibarr/issues/16183#issuecomment-774342675

**Comment by ksar-ksar** [comment]
https://github.com/Dolibarr/dolibarr/issues/16183#issuecomment-774342675
