### ISSUE TITLE
TICKET: Add time elapsed to solve ticket.

### ISSUE THREAD

**Issue by JESSTOFUNK** [Dolibarr/dolibarr#16170]
# Feature Request
Add some print lines on TICKET INTERFACE to show the time elapsed to solve the problem on the close date of the ticket (From opening to close) this data helps with KPI's.

Add the elapsed time from close to actual date.

## Use case
If there is a need to verify how much time it took to solve a problem, it can be viewed directly from the ticket page.

## Suggested implementation
On  file "htdocs/ticket/card.php" in section //CLOSE DATE add code on the line 958.

I have this

	//ELAPSED TIME FROM CREATION TO TICKET CLOSE
        	print '<span class="opacitymedium"> - '.$langs->trans("Elapsed time to solve the problem").': <i>'.convertSecondToTime(roundUpToNextMultiple($object->date_close - $object->datec, 60)).'</i>';
             //ELAPSED TIME SINCE TICKET CLOSE UNTIL TODAY
	        print ' - '.$langs->trans("TimeElapsedSince").': '.'<i>'.convertSecondToTime(roundUpToNextMultiple($now - $object->date_close, 60)).'</i>'; 
	       

The text "Elapsed time to solve the problem" should be integrated to dictionary to be available in other languages.
	      
I add this lines on 4 installations I have every update is released, if this is added to the source code it will help others.

## Suggested steps
Make this change in coming dolibarr distributions, so user don't have to modify this lines on every update.
![Captura](https://user-images.githubusercontent.com/61986181/106972935-746ad800-6717-11eb-8c52-291ff69dee3f.PNG)

**Comment by ksar-ksar** [comment]
Same as https://github.com/Dolibarr/dolibarr/issues/16092
