### ISSUE TITLE
Invoice deposit in suppliers

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#16172]
Hello everyone, I, like many people who use Dolibarr (which by the way, congratulations, is a magnificent software) when we make a payment to a provider, for which we still do not have an invoice because it is a payment in advance, there is no way "correct" to manage it in Dolibarr, so I ask for the improvement of adding an invoice deposit to suppliers in the same way that there is an invoice deposit to customers.

A cordial greeting.

**Comment by aspangaro** [comment]
This functionality was integrated into 14
