### ISSUE TITLE
Bug: To update version 13 problem with time zone

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#16183]
# Bug
Problema with time zone, problem with duration. MAIN_SERVER_TZ en other configuration es America/Lima

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /fichinter/card.php?id=396&action=editline&line_id=761

## Steps to reproduce the behavior
To Add duration of intervention

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![Error Time Zone](https://user-images.githubusercontent.com/53640168/107061533-4c768580-67a6-11eb-902b-642a03395bb9.jpg)

![Error](https://user-images.githubusercontent.com/53640168/107061423-2fda4d80-67a6-11eb-9b68-c31b9fabb658.jpg)

**Comment by eldy** [comment]
Some fix were done into v13 branch. If you can test, feedbacks are welcome.

**Comment by leninrivas** [comment]
I will try. thank you

**Comment by leninrivas** [comment]
> 
> 
> Some fix were done into v13 branch. If you can test, feedbacks are welcome.

Test Ok. Thank you
