### ISSUE TITLE
Bug: DOLIBARR

### ISSUE THREAD

**Issue by ProveedorSygmas** [Dolibarr/dolibarr#16187]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[With the update to the 13.0.0 version, is not possible to make a exportation report]

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**:  5.7.26
- **URL(s)**: /exports/export.php?step=5&datatoexport=facture_2

## Expected and actual behavior
[I need to export data to make a invoicing report, but when you try to do that, in the step 5 , you don´t have the option to download the report, the option is not available]

## Steps to reproduce the behavior
[Step 1, chose the invoice report, step 2, you chose
![bug dolibarr data exportation](https://user-images.githubusercontent.com/78636180/107111335-f2f96f80-6814-11eb-877b-7f3c6dd687c2.JPG)
 the fields that you need, step 3, you chose the filters, step 4, you chose the order of the fields in the report, step 5, you can´t do anything to download the report!!!]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Same as #16091 already fixed

**Comment by ProveedorSygmas** [comment]
> Same as #16091 already fixed

But in 16091 I can´t see the solution, or the solution is to wait to new version update? 13.0.1?

**Comment by ksar-ksar** [comment]
Wait the 13.0.1 or download the V13 branch from GIT
