### ISSUE TITLE
Celebration video conference?

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#16199]
Hi I just saw that v13 recently was released and I absolutely love Dolibarr.
I would be happy to participate in some kind of celebration video conference. :D
Anyone interested?

**Comment by ksar-ksar** [comment]
Let's Celebrate !

![image](https://user-images.githubusercontent.com/35605507/107388203-dea7c200-6af5-11eb-8f38-764cd490565a.png)
