### ISSUE TITLE
 Warnings Cannot modify header information - headers already sent by... on Banques page

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#16200]
# Bug
I get 3 times the warning when opening the page Banques before the horizontal menu.
`Cannot modify header information - headers already sent by`
The message cited line 3 of /core/tpl/extrafields_list_array_fields.tpl.php called from main.inc.php
I deleted the line 3
https://github.com/Dolibarr/dolibarr/blob/5712d255b3d639bdb831f9326d94dc71e62b56f3/htdocs/core/tpl/extrafields_list_array_fields.tpl.php#L3
then the warnings go away.
This is a brand new installation.
I can't no more copy exactly the warning, because it is now away.
## Environment
- **Version**: 13.0.0
- **OS**: Serveur mutualisé Ionos.
- **PHP**: 7.2
- **Database**:Mysql
- **URL(s)**: compta/bank/list.php?mainmenu=bank&leftmenu=

**Comment by ksar-ksar** [comment]
Same issue than here : https://github.com/Dolibarr/dolibarr/issues/16083

**Comment by papoteur-mga** [comment]
Indeed. I didn't found it. this is the same error, but from another URL.
Note that I haven't any extra module.

**Comment by ksar-ksar** [comment]
Try to put 
`$dolibarr_main_prod=0; `
in 
`$dolibarr_main_prod=1; `
in conf.php

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/16286
