### ISSUE TITLE
Export Vendor Invoices Fails

### ISSUE THREAD

**Issue by wrightjs** [Dolibarr/dolibarr#16235]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Attempting to export vendor invoices and payments. At step 5 of the process there is no option to select a file type and complete the export

## Environment
- **Version**: 13.0.0
- **OS**: Linux hp198.hostpapa.com 3.10.0-962.3.2.lve1.5.24.8.el7.x86_64 #1 SMP Fri Jan 4 06:55:54 EST 2019 x86_64
- **Web server**: Apache 2.4.46
- **PHP**: 7.2.34
- **Database**: MySQL 5.7.32
- **URL(s)**: /exports/export.php?step=5&datatoexport=fournisseur_2

## Expected and actual behavior
After going through the steps, from memory of the previous version, you would select the file type and then generate the export file.

In this version there is no option to select a file type or generate the file

## Steps to reproduce the behavior
Go through steps 1 - 5.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![dolibarr export](https://user-images.githubusercontent.com/78321296/107366531-2b7ba080-6ad6-11eb-900c-6ddb2b2ce2a1.JPG)

**Comment by ksar-ksar** [comment]
Same as #16091  already fixed, just have to download the V13 branch from GitHub
