### ISSUE TITLE
Bug: the duration in the intervention sheets is not good, it adds 1 hour

### ISSUE THREAD

**Issue by Hallowman28** [Dolibarr/dolibarr#16233]
# Bug
 in the intervention sheets, the duration displays 1 hour more
the duration in the intervention sheets is not good, it adds 1 hour

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.3.23

**Comment by ksar-ksar** [comment]
Hi,

See : https://github.com/Dolibarr/dolibarr/issues/16183#issuecomment-774342675

**Comment by ksar-ksar** [comment]
Hello,

Could you confirm that it is corrected in V13.0.1 ?
