### ISSUE TITLE
Error merging societies

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16264]
While trying to merge two societies,
```
Unknown column 'fk_soc' in 'where clause'
Echec de la fusion de 2 enregistrements. Demande annulée.
```

v 13.0.0

**Comment by ksar-ksar** [comment]
Hi,

Could you explain a bit more ? What do you mean by merging companies ?

**Comment by matDOTviguier** [comment]
In french "Fusion des tiers".

**Comment by matDOTviguier** [comment]
![capture____](https://user-images.githubusercontent.com/2384485/107665931-3aa54e80-6c8e-11eb-95b2-9f14dedd7edc.PNG)

**Comment by ksar-ksar** [comment]
Hi,

Bug confirmed, when you try to merge two third party in V13 : 

Query :
UPDATE llx_mrp_production SET fk_soc = 17 WHERE fk_soc = 11 

Result : 
[DB_ERROR_NOSUCHFIELD] Unknown column 'fk_soc' in 'where clause'

**Comment by AMOSERVICES** [comment]
Same problem, impossible anymore to merge one society into an other one.
when we click on "Fusionner" we have this message: "Unknown column 'fk_soc' in 'where clause'
Echec de la fusion de 2 enregistrements. Demande annulée."

This causes big problem for invoices, any solution?

**Comment by matDOTviguier** [comment]
fk_soc has probably been renamed because it is not a foreign key as itself.

[EDIT] As in llx_mrp_production, it is. [/EDIT]

**Comment by ksar-ksar** [comment]
Hello,

Here is the FIX : https://github.com/Dolibarr/dolibarr/pull/15988

**Comment by matDOTviguier** [comment]
Thank you @ksar-ksar.
