### ISSUE TITLE
function to get the delivery shipping address

### ISSUE THREAD

**Issue by elsp1991** [Dolibarr/dolibarr#16261]
# Feature Request
function to get the delivery address of a shipment. As I am working on a UPS module these days I realized that there is no standardize way to define the delivery address of an order/shipment. What I mean by that is that for example the PDF generation of a delivery note has its own way to decide what is the delivery address (if there is a shipping contact will use this otherwise will use the third-party address. In the other hand the UPS module I am using it also has the same behavior implemented again. This problematic because the behavior of address selection depends on the developer and could lead to have a delivery not that goes to A and a shipping label that goes to B.

## Use case
Developing consistent shipping services plugins, where the delivery address is calculated based on a known recipe (function)

## Suggested implementation
create a function that will return you the address, state, country, etc 

## Suggested steps
Would be nice to have a standard Address class for all objects in Dolibarr that use address

**Comment by dolibarr95** [comment]
Hello
In my case I just use the "Contact client livraison commande"  (Customer contact delivery order) and use it for UPS, Fedex...
I just force the Dolibarr user to define this contact a the creation of the order.

**Comment by elsp1991** [comment]
I am not sure you understood correctly the problem. This problem affects module development not normal use. I mean a php function inside the [Expedition](https://doxygen.dolibarr.org/develop/de/d38/class_expedition.html) or [Delivery](https://doxygen.dolibarr.org/develop/d3/d07/class_delivery.html) class. So when you say in my case I assume you have a module that is implementing shipping  and thats what I mean that should not be the developer choosing where to ship
