### ISSUE TITLE
PHP Warning:  Undefined array key 3 in /path/to/dolibarr/scripts/cron/cron_run_jobs.php on line 128

### ISSUE THREAD

**Issue by sebastienserre** [Dolibarr/dolibarr#16285]
Hello,

From today, I receive a warning on cron jobs.
I haven't changed anything in my install these last day.

# Bug
Not really a bug, but a warning is not fair

## Environment
- **Version**:13.0
- **OS**: Debian 9
- **Web server**: Apache
- **PHP**: 7.3.27-2+0~20210213
- **Database**: MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u1

I laucnh this command in crontab:
`*/5 * * * * /path/to/dolibarr/scripts/cron/cron_run_jobs.php ##securekey## sebastienserre > /path/to/dolibarr/documents/cron_run_jobs.php.log` and got `PHP Warning: Undefined array key 3 in /path/to/dolibarr/scripts/cron/cron_run_jobs.php on line 128` by mail

**Comment by frederic34** [comment]
@sebastienserre remove url and secure key from your issue
