### ISSUE TITLE
Error when generating pdf file for : remisecheque

### ISSUE THREAD

**Issue by jusrel2000** [Dolibarr/dolibarr#16282]
After generating "bordereau de remise de chèque" : bordereau_cheque
at : http://localhost:80/dolibarr/compta/paiement/cheque/card.php?id=1
We try to open the pdf file, but we got the following error :
=> Erreur : ErrorFileDoesNotExists: CHK2102-0001/bordereau-CHK2102-0001.pdf

After investigating we found that the pdf file : bordereau-CHK2102-0001.pdf, was generated in :
D:\Dolibarr\dolibarr_documents\bank\checkdeposits\CHK2102-0001\CHK2102-00010
instead of :
D:\Dolibarr\dolibarr_documents\bank\checkdeposits\CHK2102-0001
The ref of the cheque is duplicated in the generated path. 

Moving the file to that folder result in the link to the file been removed from that page.
I think that it's a bug that occurs in the process of generating the file path.

Environment
Version: 13.0.0
OS: Windows
Install : DoliWamp-13.0.0.exe

**Comment by atm-maxime** [comment]
Already declared and fixed I think : #16190

**Comment by jusrel2000** [comment]
Thank you, the commit 8f4bd10a8d7c9e57fecf0add25e8661bfbc69449 fixed the problem for me.
