### ISSUE TITLE
Feature request : Develloped search function (filter) for listings

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#16281]
When listing all produts and making a search on reference number, I find the search function crude. If I want to filter on all products that starts with 160, all product references containg the string 160, turns up, like

- 106SSK160
- 150160
- 16010040

But it is just the last one I want. I therefore  suggest a filter with the options

- Begins with
- Contains
- Ends with

This should be applied on all listings in Drupal.

[*Short description*]

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1
- **URL(s)**: /azerty/htdocs/product/list.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by hasse-basse** [comment]
@atm-maxime 

Hi Maxime. You are very reactive when it comes to answer or classify Feature requests but this one you have not answered. Is there any chanse that this suggestion will become a Feautre request?

**Comment by atm-maxime** [comment]
@hasse-basse you're right but usually I don't have to classify issues because it's automatic when you choose bug or feature request.
Don't forget to delete useless sections in your issue.
