### ISSUE TITLE
Error 500 returned editing a "Free text item" line in vendor purchase order when click on SAVE to update the line

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#16283]
# Bug
An HTTP Error 500 is returned after clicking in the button "SAVE" trying to update an existing line of type "Free-text item line" in a purchase order for a Vendor, or an internal error in case of editing a"free text line" in a customer commercial proposal
Is possible to create new "Free-text item lines", but is not possible to update it after editing.
The lines with Predefined products/services to purchase, can be edited and updated properly, the problem only exist in the lines with "Free-text items"

Example:
- Editing a line we have the URL [https://www.example.com/fourn/commande/card.php?id=7#line_33](url)
- Clicking over SAVE in the line edited of the type  "Free-text item line" then points to https://www.example.com/fourn/commande/card.php?id=7#line_33 but returns a HTTP 500 ERROR

## Environment
- Dolibarr 13.0.0 
- Linux
- Apache/2.4.43 
- PHP7.3.19
- MySQL or MariaDB 5.6.29
- https://www.example.com/fourn/commande/card.php?id=7#line_33

**Comment by FHenry** [comment]
@edupulpillo What is a "Free-text item lines" ? Could you please send some print screen ? 
Do you have extarnal non core modules installed ?

**Comment by edupulpillo** [comment]
"Free text lines" are the lines that are specified in the order without any code of product or code of service.
As you know in Dolibarr you can add to a invoice/order  products and services lines 
This products and services can be coded before in products module to be reusable, or you can add "Free text lines" (As are denominated in Dolibarr) without any previous coding, allowing to add lines in the invoices with free text.

![error500_after_saving_changes_in_a_free_text_item](https://user-images.githubusercontent.com/7486607/108170136-b2fb8c00-7134-11eb-907e-95c778be22ad.png)

**Comment by FHenry** [comment]
Thank for screen shot. I realized that I never use doilbarr in english, and I didn't know that free-text line is the english translation for that, sorry... Tell me if I'm wrong but It's not really accurate, it's not a "only text" line as there is a price ?
If there is an error 500, you should find some error message (and hopefully the detail of "why ?") the  into your webserver log.
I try tro reproduce on last version of dolibarr 13, from github branch 13.0 and it's not reproductible. MAby have you a custom document model ? 
I can see also that you've activate the "hidden" option PRODUCT_USE_UNITS, do you have oher hidden options or custom developpements ?

**Comment by edupulpillo** [comment]
Hi, No worries, my pleasure to try to be more clear, and thank u for your kindness following this bug. 
The lines obviously have price and qty, and no "only text".
I do not have custom developments, and the option PRODUCT_USE_UNITS is activated, and i think is the root of the problem, now that you mention it. I guess that something wrong around the Units, because 3 versions ago a problem was present related on it, and that was fixed.
Please kindly try to reproduce the problem with this option activated. I found that sometimes the error 500 is not displayed, and instead an empty page is displayed in the browser.
The problem also exist in customer proposals, in this case the following error is displayed:
![customer_proposal_error_updating_a_manualtext_line](https://user-images.githubusercontent.com/7486607/108618245-77740100-7457-11eb-9556-f313663b5fed.jpeg)

**Comment by edupulpillo** [comment]
@FHenry  did you reproduce the problem ?
It seems similar to this problem https://www.dolibarr.org/forum/t/vendors-invoice-problem/18571/44
The problem do not exist in Dolibar 13.0.2 in invoices, but still is present in Vendor Proposals and Vendor purchase orders
please can you doube check it, and fix it as was fixed in vendor invoices ?

**Comment by edupulpillo** [comment]
Confirmed that the problem is related the option PRODUCT_USE_UNITS and exist only in the VENDOR PURCHASE ORDERS in this case:

Trying to update the content of a "Free text item" existing line in a vendor purchase order, with the option PRODUCT_USE_UNITS activated, redirects here after click in "SAVE" button: http://myserver.com/dolibarr/fourn/commande/card.php?id=6#line_214 
and display the HTTP ERROR 500

I think this is enough information to be able to reproduce the problem. Please @FHenry  let me know if you need any further information.

**Comment by FHenry** [comment]
Could you extract from your Web server log the error message ?

**Comment by edupulpillo** [comment]
I do not have access to this logfile, but as i explained is extremely easy to reproduce the problem.
Steps:
1. Activate the use of "units" in Setup/Other setup:  PRODUCT_USE_UNITS=1
2. Create a vendor purchase order with one  "Free text item" line and save it
3. Edit the "Free text item" line of the previous step, and change the price for example.
4. Click over "save" button in the line that is edited, and observe the error 500

You can reproduce easily the problem, and check the logs confortable in your own local installation.

**Comment by edupulpillo** [comment]
The problem do not exist in Dolibarr 14.0.3
