### ISSUE TITLE
Bug: FIX #16240 not working

### ISSUE THREAD

**Issue by salnaSrc** [Dolibarr/dolibarr#16298]
Hi everybody, 

I'm sorry to inform you that the FIX #16240 seem to don't solve the problem. I have updated my Dolibarr installation with this full package fix (13.0.1 - c875ad9) and i still continue to have the same problem (see picture). Is there somethning wrong i did ? 
thanks & best regards DP

![Dolibarr_Fix_13 0 1](https://user-images.githubusercontent.com/30660993/107941525-1d23fd80-6f8a-11eb-8e11-f4ebd975e38a.png)

_Originally posted by @salnaSrc in https://github.com/Dolibarr/dolibarr/issues/16240#issuecomment-779163459_

**Comment by daraelmin** [comment]
Same issue #16233 , #16141 , #16168 , #16183 ?

**Comment by salnaSrc** [comment]
Hi Guys, 

After more checks i think the FIX is working, i had a mystake on my file copy to the server :( 
So i did some tests, prices are now displayed correctly in all fields. 

Sorry to open a new issue, i close it with my comment 

Best regards DP 

![Dolibarr_Fix_13 0 1](https://user-images.githubusercontent.com/30660993/108035939-df7dae00-7037-11eb-9d45-e8e7f960e33b.png)
