### ISSUE TITLE
v13 PHP Warning - Undefined array key « label » - Can't create nor modify customer

### ISSUE THREAD

**Issue by tootai** [Dolibarr/dolibarr#16301]
# Bug
Undefined array key « label » when validating customer tab

## Environment
- **Version**: [*13.0.0*]
- **OS**: [*Linux Debian Buster*]
- **Web server**: [*Nginx 1.14.2*]
- **PHP**: [*8.0*]
- **Database**: [*MariaDB 10.3.27*]
- **URL(s)**: [*http://dolibarr/societe/card.php?socid=N*]

## Expected and actual behavior
When validating creation or modification of a customer card it should action should be done. At this time an error message is displayed "Supplier value is mandatory" !?!

## Steps to reproduce the behavior
Always when validating or creating a customer card

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
2021/02/15 15:59:31 [error] 23813#23813: *177 FastCGI sent in stderr: « PHP message: PHP Warning: Undefined property: stdClass::$MAIN_IHM_PARAMS_REV in /usr/share/dolibarr/htdocs/main.inc.php on line 1341PHP message: PHP Warning: Undefined property: stdClass::$PROJECT_USE_OPPORTUNITIES in /usr/share/dolibarr/htdocs/core/menus/standard/eldy.lib.php on line 210 » while reading response header from upstream, client: fd53:9b48:337:8b38::24, server: dolibarr, request: « POST /societe/card.php?socid=2 HTTP/1.1 », upstream: « fastcgi://unix:/var/run/php/php8.0-fpm.sock: », host: « dolibarr », referrer: « http://dolibarr/societe/card.php?socid=2 »
2021/02/15 15:59:31 [error] 23813#23813: *177 FastCGI sent in stderr: « PHP message: PHP Warning: Undefined array key 1 in /usr/share/dolibarr/htdocs/core/lib/company.lib.php on line 305 » while reading upstream, client: fd53:9b48:337:8b38::24, server: dolibarr, request: « POST /societe/card.php?socid=2 HTTP/1.1 », upstream: « fastcgi://unix:/var/run/php/php8.0-fpm.sock: », host: « dolibarr », referrer: « http://dolibarr/societe/card.php?socid=2 »
2021/02/15 15:59:31 [error] 23813#23813: *177 FastCGI sent in stderr: « PHP message: PHP Warning: Undefined array key « label » in /usr/share/dolibarr/htdocs/core/class/commonobject.class.php on line 6762 » while reading upstream, client: fd53:9b48:337:8b38::24, server: dolibarr, request: « POST /societe/card.php?socid=2 HTTP/1.1 », upstream: « fastcgi://unix:/var/run/php/php8.0-fpm.sock: », host: « dolibarr », referrer: « http://dolibarr/societe/card.php?socid=2 »

**Comment by ksar-ksar** [comment]
Hi,

Dolibarr V13 is not compatible with PHP V8.

Please downgrade to PHP V7.4
