### ISSUE TITLE
Bug: PROPOSALS_WITH_PICTURE posible error

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#16314]
# Bug
MAIN_GENERATE_PROPOSALS_WITH_PICTURE no function in templates

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /comm/propal/card.php?id=925

**Comment by ksar-ksar** [comment]
Hello,

What is the template used ?
What means "no function" ?

**Comment by leninrivas** [comment]
Good day. 
Cyan and Azur. The image does not appear in the pdf. In version 12 if it shows the image in the pdf

**Comment by simnandez** [comment]
Works for me in v13

![propale_with_image](https://user-images.githubusercontent.com/881833/108488809-199db880-72a1-11eb-860f-f25c03b6ab08.jpg)
