### ISSUE TITLE
Bug: Comptabilite

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#16321]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

Impossible to link the input in compta module

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.26
- **Database**: MySQL or MariaDB 5.7.30-log
- **URL(s)**: /accountancy/customer/list.php?mainmenu=accountancy&leftmenu=accountancy_dispatch_customer

## Expected and actual behavior
[*Verbose description*]

Links to the different lines to be done but error message happened

Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='

## Steps to reproduce the behavior
[*Verbose description*]

Click on the "line to link menu"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by fpav** [comment]
En Français....

Lorsqu'on se trouve dans la module compta avec le module compta (partie double) activé, on ne peut pas lier les écritures manuellement, lorsqu'on clique sur le bouton "lignes à lier" le message d'erreur apparait en haut de la page...


Merci de votre aide

**Comment by ksar-ksar** [comment]
Hello,

This is not a bug this a problem link to your installation.
You have the solution on the wiki : https://wiki.dolibarr.org/index.php?title=Troubleshooting#I_encounter_a_DB_ERROR_message

`when Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=' `
Run `/install/repair.php?force_utf8_on_tables=confirmed `

**Comment by fpav** [comment]
100 % effective! Thx to you Ksar!
