### ISSUE TITLE
Error Fichinter to propale in checkbox

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#16326]
# Bug
When creating a budget from intervention. Create all the rows in the quote even though some were disabled.

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /comm/propal/card.php?action=create&origin=fichinter&originid=408&socid=274

**Comment by eldy** [comment]
@atm-maxime Seems related to the PR to select the line to propagate.
Does the feature is supported for proposal creation (for example when creating proposal from intervention) ? (seems not)

**Comment by leninrivas** [comment]
> @atm-maxime Seems related to the PR to select the line to propagate. Does the feature is supported for proposal creation (for example when creating proposal from intervention) ? (seems not)

Yes. The problem persists in version 14 and version 15.
