### ISSUE TITLE
Number of Events for Third-Party not visible

### ISSUE THREAD

**Issue by simaker** [Dolibarr/dolibarr#16330]
Is it possible to display the number of events according to a third-party in the register card "events" like it is visible for "notes" or "linked files"?
![Screenshot 2021-02-17 150127](https://user-images.githubusercontent.com/56035663/108215817-07e9d300-7132-11eb-8f6f-a9c199bf6607.png)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/16335
