### ISSUE TITLE
SQL Error filtering by accountancy code

### ISSUE THREAD

**Issue by martinconverti** [Dolibarr/dolibarr#16334]
Hello! I get this error when I filter on the "Various Payments" list by accountancy code. The error is that my code is alphanumeric and when I build the query it takes it as a number and that is why the query fails ...

URL: /htdocs/compta/bank/various_payment/list.php?leftmenu=tax_various

the query does this: AND v.accountancy_code=1.1.4.02.05 ORDER BY v.datep DESC, v.rowid LIMIT 26
the query should do this: AND v.accountancy_code='1.1.4.02.05' ORDER BY v.datep DESC, v.rowid LIMIT 26

> Fecha: 20210217161602
> Dolibarr: 10.0.2
> Nivel de funciones: 0
> PHP: 7.2.25
> Server: Apache/2.2.15 (CentOS)
> OS: Linux srv-web03.primetec.com.ar 2.6.32-754.24.3.el6.x86_64 #1 SMP Thu Nov 14 15:35:16 UTC 2019 x86_64
> UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
> 
> URL solicitada: /htdocs/compta/bank/various_payment/list.php
> Referer: https://aseoargentina.primetec.com.ar/htdocs/compta/bank/various_payment/list.php?leftmenu=tax_various
> Gestor de menú: eldy_menu.php
> 
> Módulos: user, agenda, cron, commande, ecm, societe, service, report, expensereport, expedition, salaries, ticket, notification, stock, facture, banque, paymentreceipt, ficheinter, afipws, fournisseur, margin, propal, masscontracts, product, categorie, contrat, supplier_proposal, projet, import, export, tax, zenfusionmaps, accounting
> Tipo de gestor de base de datos: mysqli
> Último error en solicitud de acceso de base de datos: SELECT v.rowid, v.sens, v.amount, v.label, v.datep as datep, v.datev as datev, v.fk_typepayment as type, v.num_payment, v.fk_bank, v.accountancy_code, ba.rowid as bid, ba.ref as bref, ba.number as bnumber, ba.account_number as bank_account_number, ba.fk_accountancy_journal as accountancy_journal, ba.label as blabel, pst.code as payment_code FROM llx_payment_various as v LEFT JOIN llx_c_paiement as pst ON v.fk_typepayment = pst.id LEFT JOIN llx_bank as b ON v.fk_bank = b.rowid LEFT JOIN llx_bank_account as ba ON b.fk_account = ba.rowid WHERE v.entity IN (1) AND v.accountancy_code=1.1.4.02.05 ORDER BY v.datep DESC, v.rowid LIMIT 26
> Código de retorno de error para la última petición de acceso a la base de datos: DB_ERROR_SYNTAX
> Información del último error de petición de acceso de base de datos: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.4.02.05 ORDER BY v.datep DESC, v.rowid LIMIT 26' at line 1

**Comment by aspangaro** [comment]
Hello @martinconverti 

Your version is very old. Try to upgrade to 10.0.7 or more recent branch (v11 / v12 / not v13 too young)
No problem known with accounting account search in various payment in more recent version
