### ISSUE TITLE
Classer livrée - stock virtuel

### ISSUE THREAD

**Issue by Sigmamatt** [Dolibarr/dolibarr#16346]
# Bug
[*Short description*]

->>Mouvement de stock sur base de facture, dans le module stock.
Un bon de commande validé le stock virtuel est juste, il décrémente le stock virtuel.
Si le bon de commande est classé livrée sans passer par un bon de livraison le stock virtuel ne ce décrémente pas il revient en arrière. Ce qui est un peu absurde car pour que le workflow soit propre il faut que le document soit classé en livrée.

PS : Génération automatique travaux planifier, quand les factures modèles sont sur le statu à générer  "validé" & non "brouillon" le stock ne ce décrémente pas non plus pour un produit.  

_______

Stock movement based on invoice, in the stock module.
A purchase order validated the virtual stock is correct, it decrements the virtual stock.
If the order form is classified as delivered without going through a delivery note, the virtual stock does not decrease, it goes back. Which is a bit absurd because for the workflow to be clean, the document must be classified in livery.

PS: Automatic generation of planning work, when the model invoices are on the status to be generated "validated" & not "draft", the stock does not decrease either for a product.

## Environment
- **Version**: 12.0.4 & 13

**Comment by ksar-ksar** [comment]
Hello,

Could you write in English please ?

**Comment by Sigmamatt** [comment]
Sorry !

**Comment by toni-mx** [comment]
To complement this bug report I have seen this behavior when de recent module _modReception.class.php_ is active.

the virtual stock only decrements when the supplier order is in "all products received" status if it is partially received it does not take in consideration the ones already delivered so the virtual stock is always incorrect until the order is fully closed.

Environment
Version: 13.0.0
OS: Linux
Web server: Apache
PHP: 5.6.40
Database: MySQL or MariaDB 5.6.49-cll-lve

Screenshots:

Module deactive

![module deactive](https://user-images.githubusercontent.com/79340841/108572981-24743f80-72d9-11eb-8168-64a43544afdc.png)

Module active

![module active](https://user-images.githubusercontent.com/79340841/108572982-250cd600-72d9-11eb-8830-af006bd0c743.png)

**Comment by Sigmamatt** [comment]
up ?

**Comment by eldy** [comment]
You say 
"If the order form is classified as delivered without going through a delivery note, the virtual stock does not decrease"
If you setup "Stock increase on delivery note", then this is the expected behaviour. Only a delivery not will decrease the stock whatever actions are done on order.
Which option did you setup for stock decrease ?

**Comment by eldy** [comment]
@Sigmamatt do you have the module "Reception" enabled or not. What happen if you change (enable/disable the module) just to take a look at virtual stock ? Does virtual stock become ok ?

**Comment by Sigmamatt** [comment]
Hello, the reception module is not active with us. we validate the receipts on approval of the supplier order

![image](https://user-images.githubusercontent.com/75318324/110101535-f21c1500-7da3-11eb-820b-a150d6c3c742.png)

![image](https://user-images.githubusercontent.com/75318324/110101447-d57fdd00-7da3-11eb-8ae8-a484f80a7bec.png)

**Comment by futurehousestore** [comment]
I'm expecting the same problem so I'll post my data here.

## Bug
The virtual Stock quantity is incorrect if a product is in Sales Order

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache/2
- **PHP**: 7.3.27
- **Database**: 5.5.5-10.4.17-MariaDB
- **URL(s)**: /htdocs/product/stock/product.php?id=

## Expected and actual behavior
If Physical Stock is -8 units and there are 100 units ordered the virtual stock should show 92 units but actually is showing 84 units (2 x 8 =16)

## Steps to reproduce the behavior
Check virtual stock of the product which is included in Sales Order (if the product is not in the Sales Order then the Virtual Stock value is correct) and the value shown will be double the Sales Order

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![1](https://user-images.githubusercontent.com/28427270/114227519-02a84800-996d-11eb-9a60-4c9678c092a8.PNG)
![2](https://user-images.githubusercontent.com/28427270/114227516-020fb180-996d-11eb-8579-27f2bfdd72c9.PNG)

**Comment by fbueerkmen** [comment]
I think that the reception module is not completly finished. Something is wrong in
htdocs/product/class/product.class.php : we can see two identical code blocks in the load_virtual_stock function

`

		if ((!empty($conf->fournisseur->enabled) && empty($conf->global->MAIN_USE_NEW_SUPPLIERMOD) || !empty($conf->supplier_order->enabled) || !empty($conf->supplier_invoice->enabled)) && empty($conf->reception->enabled))
		{
			$filterStatus = '4';
			if (isset($includedraftpoforvirtual)) $filterStatus = '0,'.$filterStatus;
			$result = $this->load_stats_reception(0, $filterStatus, 1);
			if ($result < 0) dol_print_error($this->db, $this->error);
			$stock_reception_fournisseur = $this->stats_reception['qty'];
		}
		
		if ((!empty($conf->fournisseur->enabled) && empty($conf->global->MAIN_USE_NEW_SUPPLIERMOD) || !empty($conf->supplier_order->enabled) || !empty($conf->supplier_invoice->enabled)) && empty($conf->reception->enabled))
		{
			$filterStatus = '4';
			if (isset($includedraftpoforvirtual)) $filterStatus = '0,'.$filterStatus;
			$result = $this->load_stats_reception(0, $filterStatus, 1); // Use same tables than when module reception is not used.
			if ($result < 0) dol_print_error($this->db, $this->error);
			$stock_reception_fournisseur = $this->stats_reception['qty'];
		}
`

I propose to fix as : 
`

		if ((!empty($conf->fournisseur->enabled) && empty($conf->global->MAIN_USE_NEW_SUPPLIERMOD) || !empty($conf->supplier_order->enabled) || !empty($conf->supplier_invoice->enabled)) && empty($conf->reception->enabled))
		{
			$filterStatus = '4';
			if (isset($includedraftpoforvirtual)) $filterStatus = '0,'.$filterStatus;
			$result = $this->load_stats_reception(0, $filterStatus, 1);
			if ($result < 0) dol_print_error($this->db, $this->error);
			$stock_reception_fournisseur = $this->stats_reception['qty'];
		}
		
		if ((!empty($conf->fournisseur->enabled) && empty($conf->global->MAIN_USE_NEW_SUPPLIERMOD) || !empty($conf->supplier_order->enabled) || !empty($conf->supplier_invoice->enabled)) && !empty($conf->reception->enabled))
		{
			$filterStatus = '4';
			if (isset($includedraftpoforvirtual)) $filterStatus = '0,'.$filterStatus;
			$result = $this->load_stats_reception(0, $filterStatus, 1); // Use same tables than when module reception is not used.
			if ($result < 0) dol_print_error($this->db, $this->error);
			$stock_reception_fournisseur = $this->stats_reception['qty'];
		}
`

the second problem is in the load_stats_reception function (same module) which not take into account the reception module
I propose to fix as : 
`

		$sql = "SELECT COUNT(DISTINCT cf.fk_soc) as nb_suppliers, COUNT(DISTINCT cf.rowid) as nb,";
		$sql .= " COUNT(fd.rowid) as nb_rows, SUM(fd.qty) as qty";
		$sql .= " FROM ".MAIN_DB_PREFIX."commande_fournisseur_dispatch as fd";
		$sql .= ", ".MAIN_DB_PREFIX."commande_fournisseur as cf";
		$sql .= ", ".MAIN_DB_PREFIX."societe as s";
		if(!empty($conf->reception->enabled)) {
		    $sql .= ", ".MAIN_DB_PREFIX."reception as r";
		    $sql .= ", ".MAIN_DB_PREFIX."element_element as er";
		}
		if (empty($user->rights->societe->client->voir) && !$socid && !$forVirtualStock) {
			$sql .= ", ".MAIN_DB_PREFIX."societe_commerciaux as sc";
		}
		$sql .= " WHERE cf.rowid = fd.fk_commande";
		$sql .= " AND cf.fk_soc = s.rowid";
		$sql .= " AND cf.entity IN (".getEntity($forVirtualStock && !empty($conf->global->STOCK_CALCULATE_VIRTUAL_STOCK_TRANSVERSE_MODE) ? 'stock' : 'supplier_order').")";
		$sql .= " AND fd.fk_product = ".$this->id;
		if (empty($user->rights->societe->client->voir) && !$socid && !$forVirtualStock) {
			$sql .= " AND cf.fk_soc = sc.fk_soc AND sc.fk_user = ".$user->id;
		}
		if ($socid > 0) {
			$sql .= " AND cf.fk_soc = ".$socid;
		}
		if ($filtrestatut <> '') {
			$sql .= " AND cf.fk_statut IN (".$this->db->sanitize($filtrestatut).")";
		}
		if(!empty($conf->reception->enabled)) {
		    $sql .= " AND er.fk_source=cf.rowid AND er.fk_target=r.rowid AND er.sourcetype='order_supplier' AND er.targettype='reception'";
		    $sql .= " AND r.fk_statut > 1";
		}

`

**Comment by toni-mx** [comment]
wow @fbueerkmen thank you very much, I hope this gets approved as, at least for us, is a critical bug.
