### ISSUE TITLE
Cronjob - Create ODT document with MAIN_ODT_AS_PDF set fails from command line with "headers already sent"

### ISSUE THREAD

**Issue by DrMcMarco** [Dolibarr/dolibarr#16343]
# Bug
Cronjob "Create Recurring Invoices" fails on CLI when ODT to PDF conversion is enabled.
(Job works when executing via the web interface)

## Environment
- **Version**: 12.0.4
- **OS**: Ubuntu 20.03
- **Web server**: Apache/2.4.41
- **PHP**: 7.1.33-24 (CLI)
- **Database**: MariaDB 10.3.25

## Expected and actual behavior
Expected:
- Cronjob creates a new invoice object and attaches the generated ODT and PDF files

Actual:
- Cronjob fails with error "Headers already sent"
- ODT and PDF files are not generated
- Changes to the database (i.e. new invoice object) are rolled back

## Steps to reproduce the behavior
- Activate cronjob module
- Add a new rule to the crontab that executes "scripts/cron/cron_run_jobs.php" every couple of minutes
- Create a recurring invoice
- Wait for cronjob to execute (do not execute it via the web interface, issue only occurs on PHP CLI)

### Cutout from dolibarr.log
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/6001893/dolibarr.log)
### Code that causes the issue (includes/odtphp/odf.php)
![Code](https://user-images.githubusercontent.com/9693248/108340141-8ac56900-71d8-11eb-8480-9d338f9bc850.PNG)

## Solution Approach
- The function headers_sent() returns true on CLI which causes an exception. I assume that happens because CLI does not use output buffering?
- Maybe only check if headers were already sent before the new ones are added (i.e. put the check inside the following if-statement)?
- Check if command line interface is being used and don't respond with a download at all?

**Comment by eldy** [comment]
Can you try this.
In the file odf.php
replace the block

```
	if (headers_sent($filename, $linenum)) {
		throw new OdfException("headers already sent ($filename at $linenum)");
	}
	if (!empty($conf->global->MAIN_DISABLE_PDF_AUTOUPDATE)) {
		$name=preg_replace('/\.od(x|t)/i', '', $name);
		header('Content-type: application/pdf');
		header('Content-Disposition: attachment; filename="'.$name.'.pdf"');
		readfile($name.".pdf");
	}
```

with

```
if ( php_sapi_name() != 'cli') {
	if (headers_sent($filename, $linenum)) {
		throw new OdfException("headers already sent ($filename at $linenum)");
	}
	if (!empty($conf->global->MAIN_DISABLE_PDF_AUTOUPDATE)) {
		$name=preg_replace('/\.od(x|t)/i', '', $name);
		header('Content-type: application/pdf');
		header('Content-Disposition: attachment; filename="'.$name.'.pdf"');
		readfile($name.".pdf");
	}
}
```

So we sent the doc to output only when in a browser context.

**Comment by DrMcMarco** [comment]
Works like a charm, thank you 👍
