### ISSUE TITLE
Issue on project module version 7 to 13

### ISSUE THREAD

**Issue by Likeandfeel** [Dolibarr/dolibarr#16355]
# Bug
On module project, when you make migration since version 5, one by one until 12.0.5 or 13.0.
When you enter on Project module you get this error message 

Modules/Applications: user, tax, import, categorie, productbatch, stock, document, pibarcode, bookmark, propal, skype, paypal, contrat, expedition, export, agenda, barcode, commande, ecm, expensereport, banque, facture, fournisseur, resource, product, societe, service, ticket, projet
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT cls.rowid, cls.code, cls.percent, cls.label FROM llx_c_lead_status as cls WHERE active=1
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'cls.percent' in 'field list'

## Environment
- **Version**: 7 to 13.0
- **OS**: Linux 
- **Web server**: Apache
- **PHP**: 7.3.23
- **Database**: mysqli
- **URL(s)**: 
- Url sollicitée: /projet/index.php?mainmenu=project&leftmenu=
Referer: http://www.xxx.xx/admin/modules.php?mode=commonkanban&page_y=1728
Gestionnaire de menu: eldy_menu.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
Activate Project module and configure it
Go to Project menu

Full details : 
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20210219083835
Dolibarr: 12.0.5 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.3.23
Server: Apache
OS: Linux x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0

Url sollicitée: /projet/index.php?mainmenu=project&leftmenu=
Referer: http://www.xxx.yy/admin/modules.php?mode=commonkanban&page_y=1728
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, tax, import, categorie, productbatch, stock, document, pibarcode, bookmark, propal, skype, paypal, contrat, expedition, export, agenda, barcode, commande, ecm, expensereport, banque, facture, fournisseur, resource, product, societe, service, ticket, projet
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: **SELECT cls.rowid, cls.code, cls.percent, cls.label FROM llx_c_lead_status as cls WHERE active=1**
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: **Unknown column 'cls.percent' in 'field list'**

**Comment by ksar-ksar** [comment]
Hi,

the table llx_c_lead_status is with percent field since it's creation in V3.8

Seems to be linked to your installation.

**Comment by Likeandfeel** [comment]
Hi Ksar

Thanks for your answer but my testing came from fresh install and migration since v3 until 13...
So missing table on SQL script.

I check on 5 other instance i have and same issue.
Not sure create manually on MySQL server is correct solution...

Have a nice day

**Comment by ksar-ksar** [comment]
Hi,

The field exist on the table creation : https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/tables/llx_c_lead_status.sql#L23

**Comment by Likeandfeel** [comment]
Hi Ksar

Please take time to read my concern.
I know on creation script exist i have sql code.

-- Manage Lead
-- Copyright (C) 2014  Florian HENRY <florian.henry@open-concept.pro>
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

create table llx_c_lead_status
(
  rowid       integer AUTO_INCREMENT PRIMARY KEY,
  code 		  varchar(10),
  label       varchar(50),
  position    integer,
  percent     double(5,2),
  active      tinyint DEFAULT 1 NOT NULL
)ENGINE=innodb;


My concern is on migration process...
This step regarding alter table is missing.

So the issue is not on installation is on updating exiting installation...

Have a nice day.

**Comment by Likeandfeel** [comment]
This part is missing

**ALTER TABLE llx_c_lead_status ADD COLUMN percent double(5,2)** 

and of course if i do manullay its works...
My concern is >> this line should be on migration script no done manually by end user...
And less on fresh install

so issue exist since migration script 3.70 to 3.8.0 because before this tab didn't exist.

hope explainations are ok now.
Have a nice day.
best regards

**Comment by ksar-ksar** [comment]
Hello,

> Please take time to read my concern.

I do, but you write : 

> Thanks for your answer but my testing came from fresh install

So it is on fresh or not ?

For migration, there is no issue because, this was added during the migration of V3.7 to V3.8 : https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/migration/3.7.0-3.8.0.sql#L725

So the only possible issue is that the migration was not OK


> ALTER TABLE llx_c_lead_status ADD COLUMN percent double(5,2)

Not needed because there is a CREATE in migration script.

**Comment by Likeandfeel** [comment]
So the only possible issue is that the migration was not OK
>> its exactly that i said since begining....

**Comment by ksar-ksar** [comment]
So it is related to your migration what was not properly done, because the create table exist in migration script : https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/migration/3.7.0-3.8.0.sql#L719

I close.

**Comment by Likeandfeel** [comment]
Closed without read and understand issue and purpose solution...
really constructive actitude...

**Comment by ksar-ksar** [comment]
Sorry but for me it is closed : 

1. New instance are OK
2. Migration from 3.7 to 3.8 is OK

So what do you need more ?

Also you are referring to a V3.8 that is 6 years old...

Anyway you can always re-open the issue if you think it is still a BUG
