### ISSUE TITLE
Import option not available in 13.0.1

### ISSUE THREAD

**Issue by NHC390** [Dolibarr/dolibarr#16367]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
Version: [13.0.0]
OS: [Windows 10 64bit]
Web server: [Apache2.4.46]
PHP: [7.4.15-Win32-vc15-x64]
Database: [mariadb-10.4.17-winx64]
URL(s): [http://192.20.20.6/dolibarr/imports/import.php?step=2&datatoimport=produit_1&excludefirstline=1&separator=%2C&enclosure=%22]

## Expected and actual behavior
[*'File to import must have one of following formats' is displayed but there is no option to select any format, there is no links available to select. The steps outlined in the online procedure shows many options but in actual nothing is visible in this page*]

## Steps to reproduce the behavior
[*Options available in 12.0.5 should be available in 13.0.1 *]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
Attached screen shot of 12.0.5 and 13.0.1 
The same web page displays option in 12.0.5 but in 13.0.1 its missing.
![12 0 5](https://user-images.githubusercontent.com/79080211/108623458-ab035b00-7458-11eb-97a6-7fb44df677ec.JPG)
![13 0 1](https://user-images.githubusercontent.com/79080211/108623459-ac348800-7458-11eb-83d9-5ab6ab0b24ce.JPG)

**Comment by daraelmin** [comment]
Try desactivate the module import. I had a similar issue on upgrading and that's how I solved it.

Hope it helps

**Comment by daraelmin** [comment]
Duplicate of #16295

**Comment by frederic34** [comment]
@ksar-ksar

**Comment by NHC390** [comment]
> Duplicate of #16295

But #16295 was marked closed, but actual problem was not rectified.

**Comment by NHC390** [comment]
> Try desactivate the module import. I had a similar issue on upgrading and that's how I solved it.
> 
> Hope it helps

I tried, but it dint solve the issue.

**Comment by ksar-ksar** [comment]
> 
> 
> > Duplicate of #16295
> 
> But #16295 was marked closed, but actual problem was not rectified.

Yes sorry I was a bit quick that day, it is not the same issue than the others.
Most of the users had issues in Step-5 of the Export in V13.0.0

But you it is in Step-3

**Comment by NHC390** [comment]
> > > Duplicate of #16295
> > 
> > 
> > But #16295 was marked closed, but actual problem was not rectified.
> 
> Yes sorry I was a bit quick that day, it is not the same issue than the others.
> Most of the users had issues in Step-5 of the Export in V13.0.0
> 
> But you it is in Step-3

Even I wonder how no one else has the similar issues, may be some sort of installation issues or missing php? Since the option is visible in older 12.0.5 i dnt understand what may be the missing element.

**Comment by NHC390** [comment]
I just found myself that MBString extension was not enabled in the php, now its working and thanks a lot for all the support.
