### ISSUE TITLE
More E-Mail Contact substitution Values for better salutation

### ISSUE THREAD

**Issue by danielprowald** [Dolibarr/dolibarr#16378]
# Feature Request
For more flexible salutation in some languages the folloing Variables are availible

__CONTACT_LASTNAME_XXX__
__CONTACT_FIRSTNAME_XXX__
__CONTACT_SALUTATION_XXX__

**Comment by toni-mx** [comment]
Would be great to extend this to other variables like

__CONTACT_EMAIL_XXX__
__CONTACT_PHONE_XXX__
