### ISSUE TITLE
Bug On installation Page

### ISSUE THREAD

**Issue by pravin0310** [Dolibarr/dolibarr#16377]
( ! ) Notice: Undefined property: stdClass::$tzuserinputkey in C:\wamp64\www\dolitest\htdocs\core\lib\functions.lib.php on line 1988
![Capture](https://user-images.githubusercontent.com/62247298/108666348-e7889280-74fc-11eb-8916-8e49543e9ae5.PNG)

**Comment by ksar-ksar** [comment]
Hi,

This is just a Notice, so not really an error.

What is your PHP version ?
What is the error_reporting in php.ini ?

**Comment by ksar-ksar** [comment]
Fix : #16382
