### ISSUE TITLE
last modified invoice in "last modified invoices" widget has a wrong status displayed when unpaid

### ISSUE THREAD

**Issue by suged** [Dolibarr/dolibarr#16386]
# Bug
Status of unpaid invoices displayed in "last modified invoices" is wront (displays "payment started")
whereas it is correct in "last unpaid invoices" widget

## Environment
- **Version**: 13.0.0, 13.0.1
- **PHP**: 7.2
- **Database**: MariaDB 10
- **URL(s)**: /index.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
create an invoice, leave it unpaid invoice and look at the widgets in the main dashboard

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 13.0.3
