### ISSUE TITLE
MRP / Manufacturing Orders: the lot number of the raw material used is not coming in automatic

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#16383]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When we consume the raw materials during a Manufacturing Order, the lot number of the raw material is not visible. We can't select a lot number of a (purchased) raw material in stocks. We have to fill the lot number by hand for each ingredient.

## Environment
- **Version**: Dolibarr 13.0.0
- **OS**: Linux dolionline 5.4.78-1-pve #1 SMP PVE 5.4.78-1
- **Web server**: Apache
- **PHP**: 7.0.33-0+deb9u10
- **Database**: MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u1

## Expected and actual behavior
The lot / batch number of any raw materials in stock should be proposed when we fill the ref of this raw materiel.

## Steps to reproduce the behavior
Make a Manufacturing Orders. Go in Production sheet. Fill the quantity consumed of each product.

**Comment by erikvanberkum** [comment]
I can confirm that the above desired functionality is not available. Would be great to have this in a next version.

**Comment by syrinx75** [comment]
As the automatic selection of the lot number is available for a delivery/sale, I thought it's possible also for a Manufacturing Order.

Thanks for your reply.

**Comment by erikvanberkum** [comment]
![image](https://user-images.githubusercontent.com/7335299/108795812-8202d780-75ca-11eb-8387-7d15f92f9c08.png)

To further clarify, the red square would be the place for a pop down button to select. 
I notice that in version 13.01 there is no longer the option to add a new Lot/Serial number for the new product to produce. In version 12 we had this ability.

**Comment by syrinx75** [comment]
So, I should stay far away of the version 13.0.1 if it doesn't allow the lot number in MRP! Thanks.

**Comment by elsp1991** [comment]
+1 That would be a great help

**Comment by elsp1991** [comment]
> ![image](https://user-images.githubusercontent.com/7335299/108795812-8202d780-75ca-11eb-8387-7d15f92f9c08.png)
> 
> To further clarify, the red square would be the place for a pop down button to select.
> I notice that in version 13.01 there is no longer the option to add a new Lot/Serial number for the new product to produce. In version 12 we had this ability.

I have V13 and you are able to set Lot/Serial number for the new product. Just make sure that you have activated Lot/Serial in the product's paramters

**Comment by syrinx75** [comment]
These parameters are active: look in the red square, there is a space to fill in the lot number.

The problem is: when we select a raw material in stock, the lot number should be in a list (like it's possible in the sales module).

**Comment by erikvanberkum** [comment]
@elsp1991 the **to produce** serial number has been fixed, I advise you to upgrade to version 14. Version 14 has the ability to delete line  items from your MO, which is also a big plus.

**Comment by syrinx75** [comment]
Good, thanks. I didn't see this in the changelog. Is it possible to add a line or to add a new input product in a MO already started?

**Comment by erikvanberkum** [comment]
not in de change log  but check here  #16536 

If a consumption has started on a line, deletion should not be possible.
