### ISSUE TITLE
Config DB

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#16388]
Hello
i put here a doc on good setups for DB
https://docs.moodle.org/3x/fr/Support_unicode_complet_pour_MySQL
we should require it for dolibarr

BR

**Comment by frederic34** [comment]
@homer8173 if you want to experiment https://github.com/Dolibarr/dolibarr/pull/16483

**Comment by homer8173** [comment]
Thanks but I was more interested by the recommandations around barracuda file format for inodb

**Comment by homer8173** [comment]
Nice job anyway

**Comment by eldy** [comment]
What the doc does not say is that with utf8mb4_unicode_ci the size of each octet is 4 bytes and the table with format innodb compact is limited to 753 bytes for index. It means we can only have 188 bytes of chars for index in a table. No enough for most tables. So you must choose between utf8mb4_unicode_ci and table with just few index or utf8 and you can have enough index for all the needs. Or not use innodb compact format (that is the default in a lot of database).

**Comment by homer8173** [comment]
Very interesting subject @eldy, my goal is to have the longest index , can we make recommandation to fit that ?

**Comment by homer8173** [comment]
NExtcloud provides requirements here https://docs.nextcloud.com/server/20/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by frederic34** [comment]
https://dev.mysql.com/doc/refman/5.6/en/innodb-row-format.html

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/109615609-68b2db80-7b34-11eb-8106-dbe79299e58e.png)
also need to modify backup in utils.class.php, if not backup will restore ????
