### ISSUE TITLE
Take POS product list not refresh when search

### ISSUE THREAD

**Issue by mtbochaca** [Dolibarr/dolibarr#16397]
# Bug
The TakePOS product list is not refreshed when searching for something other than barcode.
The "Hide Product Images" option must be enabled, it works properly.
The most curious thing is that clicking on a product brings the search product to the market, not the product that we view in the list. 

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.3
- **Database**: MariaDB
- **URL(s)**: /takepos/index.php?idmenu=99&mainmenu=takepos&leftmenu=

## Expected and actual behavior
The operation should be the same as with the "Hide product images" feature disabled.

## Steps to reproduce the behavior
Search product by name or reference to the search bar inside TakePOS.

**Comment by eldy** [comment]
Can't reproduce. Do you have same trouble with 13.0.1 ?

**Comment by mtbochaca** [comment]
The same problem with version 13.0.1 and with 2 different databases.
To fail, in the configuration of the TakePOS module, in the skin tab, the "Hide Product Images" option must be enabled
![Captura de 2021-02-23 16-04-42](https://user-images.githubusercontent.com/25686532/108863533-973f2c80-75f1-11eb-91e5-b47773702bfa.png)
![Captura de 2021-02-23 16-10-24](https://user-images.githubusercontent.com/25686532/108863739-ce154280-75f1-11eb-89a9-fcfea578cb55.png)

**Comment by eldy** [comment]
Does your product Pinzell is inside a category and does this category is inside the parent category that is used to defined which product to show in takepos (in setup of takepos) ?

**Comment by mtbochaca** [comment]
> Does your product Pinzell is inside a category ?

Yes. The product is inside a category.

> this category is inside the parent category that is used to defined which product to show in takepos (in setup of takepos) ?

No. There is no defined main category of products to be sold.

I'm attaching another image to make the problem more understandable.
![pinzell](https://user-images.githubusercontent.com/25686532/109694048-a3476300-7b8a-11eb-92c0-374f8b1b8d58.png)
