### ISSUE TITLE
No more widgets visible at all for me and then everyone (after trying to fix it)

### ISSUE THREAD

**Issue by ZARazor91** [Dolibarr/dolibarr#16396]
I hope that the bug report is fine that way.

# Bug
No more widgets visible at all for everyone after trying to add a widget and then try to fix it by disabling and re-enabling.

## Environment
- **Version**: 13.0.0
- **OS**: Ubuntu 20.04.1 LTS
- **Web server**: Apache 2.4.41
- **PHP**: 7.4.3
- **Database**: 10.3.25-MariaDB-0ubuntu0.20.04.1
- **URL(s)**: http://<ip here>/index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
The expected behavior would be to see all the enabled widgets on the page but it shows no widgets at all for every user. Our fastest solution (as we really needed it fixed) was to use a backup.

## Steps to reproduce the behavior
I wanted to enable the widget "Latest tickets" or "Latest changed tickets" (not sure anymore). As soon as i did it, no widgets at all were visible to me. I logged into the admin account, tried to disable the widget and checked if it's working again. Nothing changed so i re-enabled the widget. As soon as i did that, no widgets at all were visible to every user.

## Attached files
![bug_dolibarr](https://user-images.githubusercontent.com/3112532/108824100-9d1d1980-75c1-11eb-9615-089eab0fed11.png)
I sadly don't have any log-files as i wasn't able to get them.

**Comment by eldy** [comment]
Try to upgrade to 13.0.1
If you still have the trouble, take a look into the file error.log of the apache web server.

**Comment by ZARazor91** [comment]
I sadly can't upgrade at the moment as the system is currently in use by other collegues, i'll do it as soon as possible and then report if it fixed it and if not, i'll provide the error.log.

**Comment by frederic34** [comment]
perhaps it's box_client https://github.com/Dolibarr/dolibarr/pull/16066 which is resolved in 13.0.1

**Comment by dallenrpccs** [comment]
I'm having this same issue I even tried to fix it by disabling all apps. nothing seems to help I'm running version 17.0.1
