### ISSUE TITLE
Wrong PHP Server Time

### ISSUE THREAD

**Issue by thegeettanna** [Dolibarr/dolibarr#16401]
I know seems to be less of a Dolibarr issue, it is rather a Xampp issue that i haven't been able to figure out yet. 
In 'About Dolibarr' section, I saw the date on the "=> PHP Time (server)" & " => Client time (user)" is wrong. Although the TimeZone is correct. 
Was not able to find answers online. Since I am using Dolibarr on Xampp, this is the community I reach out to. 
Screen shots attached. 

I came across the below and tried these three steps amongst others, but still getting wrong date & time. 
"Europe/Moscow" was replaced by "Asia/Kolkata" in all the instances. 
|||||||||||||||||

Try this
1) In httpd.conf (\xampp\apache\conf\httpd.conf) , add the following line:
SetEnv TZ Europe/Moscow
2) Edit php.ini (\xampp\php\php.ini) date.timezone value in [Date] section:
date.timezone = "Europe/Moscow"
3) In my.ini (\xampp\mysql\bin\my.ini) add or replace
default-time-zone = "Europe/Moscow"
Restart Apache and MySQL
||||||||||||||||

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![108851676-b5fded00-760a-11eb-928f-15a37b9292c5](https://user-images.githubusercontent.com/24646523/108852178-4805f580-760b-11eb-995f-a5f701ada091.jpg)
![108851705-bd24fb00-760a-11eb-83bc-329a2409711e](https://user-images.githubusercontent.com/24646523/108852184-4a684f80-760b-11eb-85a7-8e743f83b5e6.jpg)

**Comment by ksar-ksar** [comment]
Hello,

What version of Dolibarr ? There were some fix regarding this in V13.0.1

**Comment by toni-mx** [comment]
@ksar-ksar still present in V13.0.1

Environment
Version: 13.0.1
OS: Linux
Web server: Apache
PHP: 5.6.40
Database: MySQL or MariaDB 5.6.49-cll-lve

Time of posting: 11:17 am UTC -6    (PHP server time is correct)

![Captura de pantalla 2021-02-23 111803](https://user-images.githubusercontent.com/79340841/108881350-d3aa6280-75c8-11eb-91ba-388d25180d63.png)

**Comment by thegeettanna** [comment]
> Hello,
> 
> What version of Dolibarr ? There were some fix regarding this in V13.0.1

I am currently on V13.0.0
Will upgrade during weekend. Will be able to ascertain if this was fixed or not then.

**Comment by ksar-ksar** [comment]
> 
> 
> @ksar-ksar still present in V13.0.1
> 
> Environment
> Version: 13.0.1
> OS: Linux
> Web server: Apache
> PHP: 5.6.40
> Database: MySQL or MariaDB 5.6.49-cll-lve
> 
> Time of posting: 11:17 am UTC -6 (PHP server time is correct)
> 
> ![Captura de pantalla 2021-02-23 111803](https://user-images.githubusercontent.com/79340841/108881350-d3aa6280-75c8-11eb-91ba-388d25180d63.png)

Hello,

Your PHP server configuration seems wrong.
"Hora de Verano :" is No for server and Yes for client....

**Comment by toni-mx** [comment]
> > @ksar-ksar still present in V13.0.1
> > Environment
> > Version: 13.0.1
> > OS: Linux
> > Web server: Apache
> > PHP: 5.6.40
> > Database: MySQL or MariaDB 5.6.49-cll-lve
> > Time of posting: 11:17 am UTC -6 (PHP server time is correct)
> > ![Captura de pantalla 2021-02-23 111803](https://user-images.githubusercontent.com/79340841/108881350-d3aa6280-75c8-11eb-91ba-388d25180d63.png)
> 
> Hello,
> 
> Your PHP server configuration seems wrong.
> "Hora de Verano :" is No for server and Yes for client....

Hi @ksar-ksar 

Thank you for your reply, I know it seems wrong configuration. The thing is PHP server Time is correct. and the client doesn't even windows seems to be fine.

Any hint as of what can be wrong?

**Comment by thegeettanna** [comment]
@ksar-ksar, 
It is resolved in Version 13.0.1.
Thank you. 

Closing this case. 

@Toni-RS, 
Try this & it might resolve your issue. Good luck. 

In httpd.conf (\xampp\apache\conf\httpd.conf) , add the following line:
SetEnv TZ Europe/Moscow
Edit php.ini (\xampp\php\php.ini) date.timezone value in [Date] section:
date.timezone = "Europe/Moscow"
In my.ini (\xampp\mysql\bin\my.ini) add or replace
default-time-zone = "Europe/Moscow"
Restart Apache and MySQL
