### ISSUE TITLE
Set optional the Fix #15565

### ISSUE THREAD

**Issue by catrielr** [Dolibarr/dolibarr#16416]
Dolibarr V.13

We could make optional the use of e.keyCode == 13) {return false; } ???
Because I use a barcode that comes from a scale where I process them with "doAcctions" and rewrite the $ _POST array with the quantity data and the product code. That is, the barcode contains the product code and the amount it weighs.

EJ: 2000026064657

20 = Indicates that it is a scale.
00026 = Product code.
06465 = Amount in Grams.
7 = CRC

Saludos, Catriel

**Comment by eldy** [comment]
to which e.keyCode == 13 are speaking about ?  (can you mention file / line ?)
Can you describe more why you need to disable this by describing step by step what you do, on which screen ?

**Comment by catrielr** [comment]
Hello Eldy, I made reference to Fix # 15565, because it is described there.
https://github.com/Dolibarr/dolibarr/issues/15565

I have an EAN that comes from a scale.
Within this code, is the product ref and the quantity.
As I describe it above.
What I need is, if possible, that "enter" is allowed, or that restriction is optional.

**Comment by zuiko** [comment]
HI @eldy and @catrielr 
for #15565 the fix has been done  in /core/lib/ajax.lib.php in function ajax_autocompleter currently line 77
but I don't clearly understand the need to disable this. Is it for a specific/private module (using javascript doAction)?

**Comment by catrielr** [comment]
Friends, I already solved the problem with the enter.
I made a module with js code:

```
$(function() {
$("#search_idprod").keydown(function(e) {

        if (e.keyCode == 13) {  $("#addproduct").submit(); } /* to enable "ENTER"  */
        console.log("Clear id previously selected for field search_idprod");

});
});
```

 that when doing an "enter" sends the form, then with the hook "doActions" I modify the $ _POST.
Thanks for everything.
