### ISSUE TITLE
Bug: accounting doc. reference to invoice is not a link

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#16419]
# Bug
Dolibarr should make it easy to navigate from transactions in the ledger to the source invoice

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.14
- **Database**: PostgreSQL 13.1
- **URL(s)**: /accountancy/bookkeeping/card.php?piece_num=160&save_lastsearch_values=1

## Expected and actual behavior
Visiting a transaction in the ledger as in the url above I get this text string:
Accounting Doc. FA2009-0112

## Steps to reproduce the behavior
make an invoice
add it to the ledger
visit the ledger transaction
try finding a link to the invoice -> impossible

# expected
link to invoice, in this case: http://dolibarr.localhost/compta/facture/card.php?facid=164 (found via searching for FA2009-0112
 in the list of customer invoices)

Can someone reproduce on v13?

**Comment by ksar-ksar** [comment]
Hello,

This is unclear to me, in the ledger transaction the URL to the invoice is wrong or missing ?
