### ISSUE TITLE
Bug: header title is missing on "internal transfer" page

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#16418]
# Bug
missing title

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.14
- **Database**: PostgreSQL 13.1
- **URL(s)**: /compta/bank/transfer.php?leftmenu=

## Expected and actual behavior
title on all pages

**Comment by dpriskorn** [comment]
can anyone confirm on v13?

**Comment by matDOTviguier** [comment]
Bug confirmed. title is "Dolibarr" in v13.0.0
![capture____](https://user-images.githubusercontent.com/2384485/108985558-79290900-7691-11eb-92e9-179b299c0f70.PNG)
