### ISSUE TITLE
Cannot rename -Facture Modele- V13.0.0

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16417]
See #15595

**Comment by daraelmin** [comment]
It's not the same issue.
The problèmes ils that the field name in database seem not have been translated in V13 and ils still in french (titre vs title). 

@matDOTviguier could you copy-paste the new error hère please

**Comment by matDOTviguier** [comment]
Not the same fix, but the same bug (cannot rename). Hence my suggestion.
It now says " Unknown column 'title' in 'field list' "

**Comment by daraelmin** [comment]
No it's not the same bug. It blocks you on the same function, but it's not the same bug.
As you can read yourself here: https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/facture/card-rec.php, the card-rec.php file contains 1710 lines of code. The more information we get, the faster we can solve it.

Please copy and paste the error.

**Comment by matDOTviguier** [comment]
Yes, I understand you well @daraelmin.
It is not the same "bug", nor the same "error", nor the same "problem".
It is only the same "report". We can't rename it afterall in 13.0.0.

The error is **"Unknown column 'title' in 'field list'"** when you try to rename a "Facture Modèle".

_Just a line above_. What do you want me to copy/paste but the error ?
![Capture](https://user-images.githubusercontent.com/2384485/108993507-f9a03780-769a-11eb-829b-811f33ae36de.PNG)

**Comment by daraelmin** [comment]
Do you have access to log file ?

**Comment by matDOTviguier** [comment]
Yes, I upgrade to 13.0.1 and I send the log.

**Comment by matDOTviguier** [comment]
Works well in 13.0.1... so ...
