### ISSUE TITLE
Bug: Can't create new order

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#16425]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

When creating a new Order, it is not possible to validate it. I have the error message :

Error, the balance begin/close of db transactions has been broken into trigger InterfaceSplash with action=ORDER_CREATE before=2 after=1

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.27
- **Database**: MySQL or MariaDB 5.7.30-log
- **URL(s)**: /commande/card.php

## Expected and actual behavior
[*Verbose description*]

Expected to have a normal behavior, since upgrade to 13.0.0 the system is not working properly

## Steps to reproduce the behavior
[*Verbose description*]

Just create a new Order from an existing customer

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Hi. It seems the error comes from the external splash module. Please advise the module editor about this error.
In v13 there's a strict check on database begin/close functions.
