### ISSUE TITLE
Error 500 update supplier order with API

### ISSUE THREAD

**Issue by bartbc** [Dolibarr/dolibarr#16437]
# Bug
It is impossible to update an supplier order via the REST API.

## Environment
- **Version**: 13
- **OS**: debian 10
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.19

## Expected and actual behavior
I'm trying to update a draft supplier order with the API. I test directly with the Dolibarr API eplorer and returns a 500 error.
Apache log : " [php7:error] [pid 118031] [client 5.48.16.244:58733] PHP Fatal error:  Uncaught Error: Call to undefined method CommandeFournisseur::update() in /var/www/html/dolibarr/htdocs/fourn/class/api_supplier_orders.class.php:251"

## Steps to reproduce the behavior
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: text/html' --header 'DOLAPIKEY: mydolapikey -d '{"request_data": [{"ref": "my new ref"}]}' 'https://myserver/htdocs/api/index.php/supplierorders/200'

**Comment by frederic34** [comment]
update() doesn't exist in CommandeFournisseur, this give err 500

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/16479

**Comment by bartbc** [comment]
I tested the modifications and there is an error : 
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'total_tva' in 'field list'
CommandeFournisseur::update Error Unknown column 'total_tva' in 'field list'

**Comment by frederic34** [comment]
field name has changed from 13 to 14

**Comment by bartbc** [comment]
Can I use the initial name (which one) ? if it's possible ?

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/issues/14697

**Comment by bartbc** [comment]
Thank you, there are no more errors but the update does not work ... I'm searching ...

**Comment by frederic34** [comment]
you can see sql request in dolibarr.log

**Comment by bartbc** [comment]
precisely the sql request takes the original values ​​and not the modified , I'm trying to understand

**Comment by bartbc** [comment]
error when building my json ... everything seems ok

**Comment by eldy** [comment]
With last comment i understand bug is fixed, so i close ticket.
