### ISSUE TITLE
Bug: Supplier Order / Email sending: Unable to attach file

### ISSUE THREAD

**Issue by anton10ruiz** [Dolibarr/dolibarr#16430]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 13.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.4.15
- **Database**:  5.5.60-0+deb7u1-log
- **URL(s)**: /agente/htdocs/admin/company.php?mainmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Duplicated of  #16423, #16420

**Comment by anton10ruiz** [comment]
Sorry
Close isue
