### ISSUE TITLE
Mail system in Ticket is broken

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16436]
# Bug
It is not possible to join any PDF in the message "Reply" sent via the Ticketting Interface.

## Environment
- **Version**: 13.0.1
- **OS**: debian 10 
- **Web server**: apache2 last stable on debian 10
- **PHP**: php7 last stable on debian 10
- **Database**: Mysql last stable on debian 10
- **URL(s)**: 

## Expected and actual behavior
Expected behavior, like in the mail interface on Customer.
Actual behavior. File is said to be joint, each time. But still no file joint at all.

## Steps to reproduce the behavior
Open a ticket. On it, send a message via mail. Try to join a file with the message. Look at the green pop-up in the upper right corner saying your file is attached. Look at the list of joint files. Empty. Control with your mail server. No file.

**Comment by matDOTviguier** [comment]
Probably duplicate with #16420

**Comment by ksar-ksar** [comment]
Link to #16420

**Comment by matDOTviguier** [comment]
thank you ksar-ksar. Closed.
