### ISSUE TITLE
Reunion Island is not considered as part of EEC

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#16432]
# Bug
Trying to make a automatic debiting result on a error : Impossible de générer le fichier de reçu des prélèvement pour votre pays RE (Votre pays n’est pas supporté)

## Environment
- **Version**: V13

## Expected and actual behavior
Réunion Island should be considered to be part of EEC.

The function `getCountriesInEEC `of `core/lib/company.lib.php`
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/lib/company.lib.php#L701
Should be modified, to add RE

A workaround is to set the hidden variable MAIN_COUNTRIES_IN_EEC = ‹ AT,BE,BG,CY,CZ,DE,DK,EE,ES,FI,FR,GB,GR,HR,NL,HU,IE,IM,IT,LT,LU,LV,MC,MT,PL,PT,RO,SE,SK,SI,UK,RE ›

See : https://www.dolibarr.fr/forum/t/module-prelevement-a-la-reunion/35822

**Comment by eldy** [comment]
Yes Reunion is not a country but a region of FR. For this reason, it is not into list by default. But we could add it for the case of users that use Reunion as a separate country.
Correct fix is to add a column in table of countries to say if country is in europe or not and update the method getCountriesInEEC to use this table. So we can edit which country is in Europe or not using this table (the hidden constant MAIN_COUNTRIES_IN_EEC was a quick workaround)
