### ISSUE TITLE
Bug: No TVA calculated with free line products

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#16451]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

When creating an Purchase Order for a customer with free lines, no VAT is calculated in the total unless the CVAT is well calculated. A star is appearing on the side of the VAT but nothing to force VAT calculation in the Total

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.27
- **Database**: MySQL or MariaDB 5.7.30-log
- **URL(s)**: /commande/card.php?id=142

## Expected and actual behavior
[*Verbose description*]

Brand new behavior from the 13.0.0 as this is happening only on the non registered products, VAT for registered products is well considered in the total. For free lines, no VAT is added to the Total??

## Steps to reproduce the behavior
[*Verbose description*]

Create a PO from a Customer and add several free lines with VAT.
VAT is well calculated but total is wo VAT.
![2021-02-26_10-36-33](https://user-images.githubusercontent.com/58973675/109282970-84f60600-781e-11eb-941c-0c8b7d4fec8c.jpeg)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

I can not reproduce this in my setup.
![image](https://user-images.githubusercontent.com/35605507/109300478-db6f3e80-7836-11eb-91eb-a324a7dee4f2.png)

Can you check that your third party is well configured ?
![image](https://user-images.githubusercontent.com/35605507/109300594-fc379400-7836-11eb-83a5-eea2a9f05b86.png)

**Comment by fpav** [comment]
You are right I couldn't reproduce it in my demo site. I finally found the problem in Dictionnary. My accounting department changed the TVA allocation in the dictionnary to Yes instead of No!

Here is a snapshot of what caused the issue.
![2021-02-26_15-03-13](https://user-images.githubusercontent.com/58973675/109309757-ff854c80-7843-11eb-9338-67459f940a93.jpeg)
