### ISSUE TITLE
Bug: Product code gone after update currency (PO)

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#16465]
# Bug
When updating the currency for the Purchase Order, the product code, vendor SKU went missing, and keep only the text. Please see the pictures attached for the before and after.

## Environment
- **Version**: 12.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.23
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /fourn/commande/card.php?id=110&save_lastsearch_values=1

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![1](https://user-images.githubusercontent.com/52134143/109333891-f5426d00-789a-11eb-98fd-269396604f79.PNG)
![2](https://user-images.githubusercontent.com/52134143/109333898-f70c3080-789a-11eb-830d-ff188adc7129.PNG)

**Comment by frederic34** [comment]
I can reproduce the bug in V14

**Comment by frederic34** [comment]
idem with invoice
