### ISSUE TITLE
Bug: Files number not show (SI)

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#16466]
# Bug
Found that the number of files does not show in the header on the supplier invoice.

## Environment
- **Version**: 12.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.23
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /fourn/facture/document.php?facid=108

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![1](https://user-images.githubusercontent.com/52134143/109335422-fa082080-789c-11eb-8306-136e68272089.PNG)

**Comment by ksar-ksar** [comment]
Hi,

For me this is not a bug but a feature request

**Comment by frederic34** [comment]
Do you have some files atached ? For me it works

**Comment by asolslk** [comment]
Yes, there are files attached.
It works when in the draft, after validation, it's gone. So I think it's a bug.. can be ignored if it is not a bug.

![Capture](https://user-images.githubusercontent.com/52134143/109378456-ad106280-790d-11eb-93a2-999aeac721f4.PNG)
![Capture1](https://user-images.githubusercontent.com/52134143/109378467-c31e2300-790d-11eb-8b79-aec3572a9108.PNG)

**Comment by eldy** [comment]
Try also to upgrade to 12.0.5
