### ISSUE TITLE
Regenerate PDF produces wrong language

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#16476]
Dolibarr 12.0.4, multilanguage support, en_GB as main language but all customers have sv_SE as default language (to get swedish on invoices etc). When manually clicking "generate" under invoice, "Swedish" is selected and PDF goes in Swedish.

However, when selecting multiple invoices (all which are set to "swedish") and clicking Regenerate PDF, all those PDF are in en_GB language. That is, the regenerate function ignores the third party language settings and uses the system wide language setting instead.

This is incorrect, I believe it should respect the third party language setting.

![2021-02-27_083629](https://user-images.githubusercontent.com/11036018/109380937-b383e780-78d7-11eb-804d-6abd98038006.png)

**Comment by eldy** [comment]
Can you try with 12.0.5 ?

**Comment by bos4711** [comment]
Sorry for the delay.

I just tried it in Dolibarr v12.0.5 and it is the same issue. All PDF:s get regenerated in en_GB despite they are set to "swedish" in the invoice settings.

**Comment by bos4711** [comment]
Bug is confirmed in 14.0.3 as well. Third parties has default language Swedish (sv_SE), all invoice PDF have language sv_SE, yet mass-action "Re-generate PDF" produces en_US output.

I have been digging in `actions_massactions.inc.php` (in the `if (!$error && $massaction == 'generate_doc' && $permissiontoread)` tree) for an hour now but I cannot track down the error. Will try again tomorrow.

**Comment by bos4711** [comment]
Now I've had more time to investigate (in the stable 14.0 branch). In `actions_massactions.inc.php`, on the if-case on line 1346, is where I found the regeneration occurs. In this if-branch, there are four new ifs:

    if ($conf->global->MAIN_MULTILANGS && empty($newlang) && GETPOST('lang_id', 'aZ09')) {
      $newlang = GETPOST('lang_id', 'aZ09');
    }
    if ($conf->global->MAIN_MULTILANGS && empty($newlang) && isset($objecttmp->thirdparty->default_lang)) {
      $newlang = $objecttmp->thirdparty->default_lang; // for proposal, order, invoice, ...
    }
    if ($conf->global->MAIN_MULTILANGS && empty($newlang) && isset($objecttmp->default_lang)) {
      $newlang = $objecttmp->default_lang; // for thirdparty
    }
    if (!empty($newlang)) {
      $outputlangs = new Translate("", $conf);
      $outputlangs->setDefaultLang($newlang);
    }

Every one of these are resulting in "false" in our system, while MAIN_MULTILANGS is "1". The culprits therefore seems to be the variable "default_lang", and this is where I have trouble debugging them. When I do a `print_r($objecttmp)` I see no traces of "default_lang" anywhere in the SQL-results, but I do find this: `[lastquery] => SELECT rowid, name, label, type, size, elementtype, fieldunique, fieldrequired, param, pos, alwayseditable, perms, langs, list, printable, totalizable, fielddefault, fieldcomputed, entity, enabled, help FROM llx_extrafields WHERE ...`. The queries only fetches from llx_extrafields, and this table is completely empty on our system. I do not know if this is the culprit, but there are no signs of any language anywhere in this if-branch (en_US, se_SV, etc).  **(EDIT)** If I, right before `if (!empty($newlang)) ...` add `$newlang = "sv_SE"` then the regeneration outputs the new PDF in correct language, which proves that the if-cases are not working as they should.

Also, I think the order of if-case 2 and 3 are wrong. When re-generating PDF, Dolibarr should first respect the language setting for the invoice (or customer order, or whatever) first. Then, if that's empty (non-existing PDF), get the value from the third party. My reasoning here is because one third party can have "default language: sv_SE" but one particular invoice could have been generated in en_US because of a foreign customer. This is why the regeneration should respect this settings before the third party settings.


I am sorry I couldn't figure out how the SQL-transactions are run, but these are a bit complex for me (who is not a dolibarr developer), but I hope my findings can help tracking down this bug.

**Comment by bos4711** [comment]
I have now found the root cause of this bug. It is because `$objecttmp` does not have a thirdparty in it, and this is because of this (excerpt from "git show" after I applied my local fixes):

```
diff --git a/htdocs/commande/class/commande.class.php b/htdocs/commande/class/commande.class.php
index f02e74687a..358db5a397 100644
--- a/htdocs/commande/class/commande.class.php
+++ b/htdocs/commande/class/commande.class.php
@@ -1837,7 +1837,7 @@ class Commande extends CommonOrder
                                $this->ref_int                          = $obj->ref_int;
 
                                $this->socid = $obj->fk_soc;
-                               $this->thirdparty = null; // Clear if another value was already set by fetch_thirdparty
+                               $this->fetch_thirdparty();
 
                                $this->fk_project = $obj->fk_project;
                                $this->project = null; // Clear if another value was already set by fetch_projet
diff --git a/htdocs/compta/facture/class/facture.class.php b/htdocs/compta/facture/class/facture.class.php
index a28838756d..70d6e7e07f 100644
--- a/htdocs/compta/facture/class/facture.class.php
+++ b/htdocs/compta/facture/class/facture.class.php
@@ -1656,7 +1656,7 @@ class Facture extends CommonInvoice
                                $this->close_note                       = $obj->close_note;
 
                                $this->socid = $obj->fk_soc;
-                               $this->thirdparty = null; // Clear if another value was already set by fetch_thirdparty
+                               $this->fetch_thirdparty();
 
                                $this->fk_project = $obj->fk_project;
                                $this->project = null; // Clear if another value was already set by fetch_projet
```

However, I cannot find the reason why you are setting it to null. If you look in `expedition.class.php` to find the similiar case, you find this:

```
                                // Thirdparty
                                $result = $this->fetch_thirdparty(); // TODO Remove this
```

So there must be a reason why you set thirdparty to null, but this has the side effect that "Re-generate PDF" fails. Git blame says "Scrutinizer Auto-Fixer" which I don't know what that is.
