### ISSUE TITLE
accounting entries : import 

### ISSUE THREAD

**Issue by optistea** [Dolibarr/dolibarr#16484]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

Hello !

ISSUE :
When I import accounting entries with the tool it is possible to import unbalanced entries  and even if a account not existe 👎 

SOLVING : 
 **before** processing the import 

- control that the entries is balanced (D=C)
- control that all acounts was created in the accounting plan

Have fun !

**Comment by ksar-ksar** [comment]
Hello,

Sound to me normal.

You can't import something that is not OK.

Could you elaborate a bit more why Dolibarr should accept the data's and how to deal with wrong account for examples ?

By the way you do not indicate on what dolibarr version your are working.
