### ISSUE TITLE
No product description on client invoice, delivery note, and order

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#16496]
# Bug
With the version v13, we don't succeed to print the description text of the product on any invoice, delivery note, order. We have tested in 2 languages with the 'crabe' invoice template.

## Environment
- **Version**: 13.0.0
- **OS**: Linux dolionline 5.4.98-1-pve #1 SMP PVE 5.4.98-1 (Mon, 15 Feb 2021 16:33:27 +0100) x86_64
- **Web server**: Apache
- **PHP**: 7.0.33-0+deb9u10
- **Database**: MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u1

## Expected and actual behaviour
On each line of the invoice, for each invoice, we expect to have the description of the product sold. 

## Steps to reproduce the behaviour
We make an order from a 'Third party', 'Customer' page of the third party, 'Create order'. We add the products. Validate the order. Make a delivery. Make the invoice.

## [Attached files]
(https://user-images.githubusercontent.com/3815422/109492843-3fdb0980-7a94-11eb-82cd-75c80b932a83.PNG)

**Comment by ksar-ksar** [comment]
Hello,

I don't understand your issue.
On the screenshot you provide, there are products descriptions
![image](https://user-images.githubusercontent.com/35605507/109511167-12498c80-7aa3-11eb-84d6-da0991a227ef.png)

**Comment by syrinx75** [comment]
Hello.

Only the 'ref' and the product 'label' are visible on this invoice. Not the description.

If I'm not wrong, if there is a description in the product form, it should appear on each invoice. Shouldn't it?

![image](https://user-images.githubusercontent.com/3815422/109512887-3611d000-7aad-11eb-99e5-e56fe9e86a89.png)

**Comment by matDOTviguier** [comment]
depending on you model, but in the default one, yes. Can you verify the model used in Invoicing Module ?

**Comment by syrinx75** [comment]
I did it again on 'crabe' template for the invoice: still no description on the invoice. Is it 'crabe' the original template from the Dolibarr's developers?
