### ISSUE TITLE
Link Tasks and Customers (Third Parties ?)

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16494]
# Feature Request
Add a solution to link a TASK (in project module) to a Third Party (societe.nom in db).

## Use case
Link a task with a customer, not a the Project level.
I have tasks into a project "Customer incident". I want to manage tasks attached to customers. Not projects.

## Suggested implementation
Let the user select a "Tiers" on a task and create an automatic event on them (on the task, on the "Tiers" with a 1<>1 link).
In french, here is my bypass : "Afin de relier un tiers à une tâche **il faut** et _il suffit_ de créer un évènement “vierge” car un événement peut être relié à un tiers et à une tâche."

**Comment by eldy** [comment]
Note: On the tab "Contact" of a task, you can link a task with the contact of a thirdparty.

**Comment by matDOTviguier** [comment]
Probably only if thirdparty is linked to the project. And this not my usecase ...
I cannot add all thirdparties to the project "Customer Service" :)

![Capture](https://user-images.githubusercontent.com/2384485/109778414-142b6100-7c05-11eb-8378-8651672053f7.PNG)

I mean, I can add a contact of a thirdparty, but at the project level. So my FR.
