### ISSUE TITLE
Support extrafields for BOM lines

### ISSUE THREAD

**Issue by NHC390** [Dolibarr/dolibarr#16499]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
In the setup of the BOM and MO module Complementary attributes (bom_bom_extrafields) cannot be added to the BOM or MO list, currently option is visible only for the BOM and MO not for its list (bom_bomlist_extrafields). 

## Environment
Version: [13.0.0]
OS: [Windows 10 64bit]
Web server: [Apache2.4.46]
PHP: [7.4.15-Win32-vc15-x64]
Database: [mariadb-10.4.17-winx64]
URL(s): http://192.20.20.6/admin/bom_extrafields.php

## Expected and actual behavior
bom_bomlist_extrafields is available in database tables but not sure how to set-up. In set up of module, only bom_bom_extrafields option is visble.

## Steps to reproduce the behavior
bom_bomlist_extrafields is available in database tables but not sure how to set-up. In set up of module, only bom_bom_extrafields option is visble.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Seems fixed into v13.0.1

**Comment by NHC390** [comment]
Thanks for the response. 
In the setup of BOM module: bom_extrafields was available to add fields, but bomline_extrafields is not possible to add. This option does not exist in the module set up.  
![image](https://user-images.githubusercontent.com/79080211/109604273-ae73a200-7b3c-11eb-93f7-eb2c952f8302.png)

**Comment by eldy** [comment]
Yes, extrafields for BOM lines is not a feature available for the moment.
Only extrafields for BOM object.

**Comment by ToniTen** [comment]
I assume, given that the database seems to have the required table (llx_bom_bomline_extrafields) there is a plan to eventually add the extrafield functionality to the BOM lines (and MO lines, and allow automatically copying the values of the extrafields from BOM to MO). I would find it very very useful, as I would add notes to certain lines so the person assembling the product has extra information.

**Comment by wysman** [comment]
Hey,

Does they have anyone working on adding extrafields on BomLines ?
We need to add some technical annotation in our BOM.
