### ISSUE TITLE
Missing file after installation 

### ISSUE THREAD

**Issue by rzaprianov** [Dolibarr/dolibarr#16498]
I have installed module AWSTATS but after installation when I try to configure the module I can't find the file "awstats.pl" it simply doesn't exists.

**Comment by ksar-ksar** [comment]
Hello,

I don't think this is a "core" module.

For external modules, you need to ask the developer of that module.

**Comment by frederic34** [comment]
https://wiki.dolibarr.org/index.php?title=Module_AWStats

**Comment by rzaprianov** [comment]
> https://wiki.dolibarr.org/index.php?title=Module_AWStats

Doesn't work. Missing file "awstats.pl"   https://i.imgur.com/sBc3KNG.png

**Comment by rzaprianov** [comment]
I can't see any other report modules included in Dolibarr. Are the reports additional modules and all paid? I don't have issue with the payment, but if they work as these 2 I already try to install and they both failed .... I mean AWstats and MyList - both failed. The first miss a core file, the second have problem https://i.imgur.com/Irgfodc.png

**Comment by frederic34** [comment]
you need to install awstats from your server software distribution

**Comment by rzaprianov** [comment]
> you need to install awstats from your server software distribution

We took the module from here https://www.dolistore.com/en/modules/5-AWStats.html  and installed on the server as per the instructions. What we miss?  https://i.imgur.com/YPFWnEr.png

**Comment by frederic34** [comment]
By example, if your server run ubuntu, look for "install awstats for ubuntu"  and then you can use the module

**Comment by ksar-ksar** [comment]
Anyway this is an external module.
So you should ask the developer of that module.

I will close
