### ISSUE TITLE
Error with thousands separator dot, when editing product line.

### ISSUE THREAD

**Issue by gavrielzs** [Dolibarr/dolibarr#16503]
[Error with thousands separator dot, when editing product line.]

**Environment**
Version: [13.0.1]
OS: [Linux]
Web server: [Apache]
PHP: [7.4.4]
Database: [MySQL or MariaDB 5.5.5-10.1.44-MariaDB-cll-lve]
URL(s): [/dolibarr/htdocs/compta/facture/card.php?] and others...

**Expected and actual behavior**
[*When you need to edit a product or service line, you must delete the thousands separator point. Otherwise, the values are changed.The system confuses the dot char with the comma char.

Affected ID lines "price_ht" and "buying_price*]

**Screen Captures**
Previous to edit product price

![01](https://user-images.githubusercontent.com/67830715/109537052-3609d400-7a9d-11eb-9193-a12524ca252e.png)

After edit product price, without delete dot char

![02](https://user-images.githubusercontent.com/67830715/109537170-5d60a100-7a9d-11eb-83f0-ba320868953d.png)

Manual edit dot char

![03](https://user-images.githubusercontent.com/67830715/109537221-6b162680-7a9d-11eb-8ec5-ec90d97d7547.png)

Result editing dot char

![04](https://user-images.githubusercontent.com/67830715/109537265-749f8e80-7a9d-11eb-8c0b-875a724502c1.png)

**Comment by ksar-ksar** [comment]
Hello,

First thing is to upgrade to at least V11.0.5

**Comment by gavrielzs** [comment]
> Hello,
> 
> First thing is to upgrade to at least V11.0.5 
> 

Sorry, i fix that, its V13.0.1

**Comment by eldy** [comment]
Can you tell me what is your language code (for example es_MX) ?
Can you tell me also what you set for accuracy of unit price into home - setup - accuracy and limits ?

**Comment by gavrielzs** [comment]
> Can you tell me what is your language code (for example es_MX) ?
> Can you tell me also what you set for accuracy of unit price into home - setup - accuracy and limits ?

Language: es_ES

Accuracy and limits:
![Captura 01](https://user-images.githubusercontent.com/67830715/109568865-4c785580-7ac6-11eb-8d3f-fc8c8e55e095.PNG)

Thanks!

**Comment by eldy** [comment]
And what is your country ?

**Comment by ksar-ksar** [comment]
Hello,

Can you try the FIX ?
