### ISSUE TITLE
"The security token has expired, so the action has been cancelled. Please try again".

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#16519]
# Bug
[After upgrading from version 12.03 to version 13 or 13.01
When I try to activate any module, official or not, I get this message and the module is not activated.]

## Environment
- **Version**: [v3 - v3.1]
- **OS**: [W10 x64]
- **Web server**: [Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/7.4.15]
- **PHP**: [7.4.15]
- **Database**: [10.4.17-MariaDB]

**Comment by eldy** [comment]
Did you install external module, for example the module multicompany ?
If yes, try to remove it by deleting the directory.

**Comment by JoAnMaFe** [comment]
Good afternoon.
I deleted the files and folders of all modules in the folder dolibarr/htdocs/custom and restarted the server, but the problem still occurs, I reinstalled the version of dolibarr that I had previously 12.0.5 and the problem does not appear.
Note: In both configurations I kept the same versions of PhP and Apache.

**Comment by daraelmin** [comment]
Duplicate #16096 ?

@JoAnMaFe : To give more info to the debugger could you copy-paste the related line of log ?

https://github.com/Dolibarr/dolibarr/issues/16096#issuecomment-786709480 please ?

**Comment by ksar-ksar** [comment]
Hi,

Could you try with V13.0.2 ?

If you still have the error, with v13.0.2, when the module syslog is enabled, you will also find into the dolibarr.log a line
NEW TOKEN reclaimed by : name of page

**Comment by JoAnMaFe** [comment]
Gracias ksar-ksar
For me, it doesn't quite work.
When upgrading from 12.05 to 13, 13.01 and then 13.02 
With both versions I got the same problem with the security token.
I went back to 12.05 which worked fine and when I read Eldy and said that the problem was in the external modules, before upgrading, I deactivated all the external modules (3) and deleted them from the htdosc/custom folder. The installation worked fine and I proceeded to install and activate the external modules without any problem.
I have also observed on occasion that when activating or deactivating a module (and not necessarily the same one), the TOKEN message has reappeared, although on repeating the action, the message has disappeared.

Tip: Perform the updates or backups to perform the updates with the external modules deactivated and after performing the update, activate them again. 
In my case it worked.

**Comment by BebZ** [comment]
HOw can we upgrade to v13 without tokens ? 
it is not the right time to make it mandatory, some people need time to adapt to this evolution. 
Of course it's great, and we recognize the hard work, but there were no informations about it to let time to adapt...

**Comment by eldy** [comment]
There is no particular thing to do to migrate to v13 (i mean related to token). The security around token is similar in v13 than in v12.
Check however you are in stable mode (MAIN_FEATURES_LEVEL must not be set).

**Comment by BebZ** [comment]
thanks for this simple answer, we were on feat levels higher than 0...
