### ISSUE TITLE
ClickToDial script to launch Linphone does not work

### ISSUE THREAD

**Issue by mkrtchian** [Dolibarr/dolibarr#16518]
# Bug
I have activated ClickToDial, following [the documentation](https://wiki.dolibarr.org/index.php/Module_ClickToDial_En). I have installed and configured Linphone, which works without Dolibarr. But When clicking on a phone number on Dolibarr, and choosing `linphone.sh` in firefox, it does not work. On chrome the choice is even not there at all.

## Environment
- **Version**: 13.0.1
- **OS**: Ubuntu
- **Web server**: Nginx 1.18.0 on my local machine (with Valet)
- **PHP**: 7.4.3
- **Database**:  MySQL version 8.0.23

## Expected and actual behavior
Actual:
* On firefox I click on a phone number on Dolibarr, the browser asks me to choose a software, I choose the script `linphone.sh`, and nothing happens.
* On Chrome I click on a phone number on Dolibarr, the browser launches Zoom which tells me that it cannot do anything with SIP.

Expected:
On Firefox and Chrome, I click on a phone number on Dolibarr, the browser asks me to choose a software, I choose the script `linphone.sh`, it opens Linphone and the call is made.

## Steps to reproduce the behavior
The [linphone.sh script available](https://github.com/Dolibarr/dolibarr/blob/develop/scripts/clicktodial/linphone.sh) is probably a bit old now. The [latest version of Linphone](https://www.linphone.org/technical-corner/linphone) is an Appimage that will be stored in the user space (we can put it next to `linphone.sh`).

The command line API has also changed. Here is a command that works to make a call:
```bash
./Linphone-4.2.5.AppImage "call sip-address=sip:NUMBER@DOMAIN" &
```

So I have changed a bit the script to:
```bash
#!/bin/bash
./Linphone-4.2.5.AppImage "call sip-address=$1" &
```
And in the configuration of ClickToDial I have put `sip:__PHONETO__@sip5.ovh.fr` (OVH is my SIP provider).

And I am sure that the script is not executed at all by firefox, just before the line that launches Linphone, I have put this line:
```bash
echo Launch Linphone $1 $2 > test
```
When I execute it by hand Linphone is launched and the call works, and the `test` file is created. But when I try through Firefox by choosing `linphone.sh`, nothing happens, and there is no `test` file created. Maybe Firefox doesn't want to execute the shell script for security reasons or something like that.

And as for Chrome as I said it doesn't give me the choice for the software I want, it just picks Zoom, enven after I followed the tutorial in the ClickToDial documentation.

**Comment by eldy** [comment]
This solution is based on the fact that you have a sip: link on the phone numbers and that your browser is configured to launch a script when such a link is clicked. Unfortunately, it is no longer supported by most recent versions of web browsers.
To use clicktodial with OVH, you must have an url to call to launch the dial. 
You can use this module https://wiki.dolibarr.org/index.php?title=Module_OVH_(SMS,_ClickToDial,_...)_FR for sip with OVH

**Comment by mkrtchian** [comment]
Thank you for your answer. I had already installed the OVH module, it was just more direct to launch Linphone and call directly than to recieve a call from OVH and then call the recipient. But if recent browsers do not allow it, I will use the OVH module.

I think it could be useful to add in the documentation wiki that the indicated Linphone / Ekiga solutions for click to dial are no more compatible with recent browsers (I have created an account on the wiki but I can't make modifications on the page).

**Comment by matDOTviguier** [comment]
I have done a workaround, sending the complete url elsewhere (at the ipbx level).
My ipbx calls me, I answer, the ipbx composes the number asked for.
And in fact the click to dial is automatic on Android seeing a link with a correct number.
So the link on the phone number displayed by Dolibarr is not intercepted well by mobile devices.

**Comment by eldy** [comment]
Yes, on a smartphone android, the link is tel: and is automatically handled by your android. The clicktodial module is usefull only for  desktop use.
