### ISSUE TITLE
different delivery/invoice address in ODT template does not work

### ISSUE THREAD

**Issue by usigit** [Dolibarr/dolibarr#16517]
# Bug
if you specify a different delivery/invoice address, everything is entered correctly with the PDF templates rouget and espadon. With an ODT template, the different addresses are not entered in the tags. Only the tags appear on the delivery note/invoice.

## Environment
- **Version**: [*12.03 ->*]
- **OS**: [*Debian 10*]
- **Web server**: [*Apache 2.4.38*]
- **PHP**: [*7.3.27*]
- **Database**: [*MariaDB 10.3.27*]
- **URL(s)**:

**Comment by ksar-ksar** [comment]
Hello,

What TAGs are you using ?
Also could you make the update to 12.0.5 ?

**Comment by usigit** [comment]
Hello,

I use the following tags: 
{company_name}
{company_address}
{company_zip} {company_town}
{company_state}

for testing purposes, I found the same behavior on an identical environment up to version 13.0.

Am Mittwoch, den 03.03.2021, 00:29 -0800 schrieb ksar:

**Comment by ksar-ksar** [comment]
Same as  #16323 and #16128

**Comment by ksar-ksar** [comment]
Hello,

One workaround proposed by Libremaster is to put MAIN_USE_COMPANY_NAME_OF_CONTACT to 0 in Setup->Other
