### ISSUE TITLE
MRP ability to delete a line

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#16525]
# Feature Request
In the manufacturing order in the tab production have a possibility to delete a line, currently there is only the possibility to add a line.  

## Use case
![image](https://user-images.githubusercontent.com/7335299/109740389-8bb1be00-7c0e-11eb-87be-69f2ec402d4a.png)

## Suggested implementation
Use a row delete button conform we use in orders or invoices, see picture above

**Comment by eldy** [comment]
For @Hystepik, Can you implement this. The most important is the delete button on line. 
Note: Put the delete dustbin picto at end of line to match look and feel.
Note 2: If a consumption has started on a line, deletion should not be possible.
