### ISSUE TITLE
How large could be the set of objects in mass action ?

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16527]
# Bug
Only 970 first elements could be deleted in mass action.

## Environment
- **Version**: 13.0.1
- **OS**: Debian 10 last stable
- **Web server**: Apache2 last stable on Debian 10 last stable
- **PHP**: php7 last stable on Debian 10 last stable
- **Database**: mariaDB last stable Debian 10 last stable

## Expected and actual behavior
Set the number at the selection

## Steps to reproduce the behavior
Create 10k thirdparties, try to delete 9K. See that only 970 will be.

**Comment by matDOTviguier** [comment]
Now at 980 ... Seems to be the size of the request ...

**Comment by eldy** [comment]
Dolibarr try only for 1000 records in mass action.

**Comment by atm-maxime** [comment]
And you might have a max_post_size set to 1000 in the php setup

**Comment by matDOTviguier** [comment]
Dolibarr should tell it near the mass action button, via an hint ? (try only for 1000 records).

**Comment by matDOTviguier** [comment]
It is not a bug, it is a comportemental behavior that needs to be documented.

**Comment by altatof** [comment]
one trick to extend possibilities is to base64_encode the parameters
