### ISSUE TITLE
no results in tickets, with project column and filter "open all" "closed all"

### ISSUE THREAD

**Issue by rem5411** [Dolibarr/dolibarr#16539]
# Bug
in the "tickets" part, once the "projects" are activated and attached to a ticket, the complete list of tickets no longer works normally. all tickets disappear from the screen, when you change a filter like "all open" or "all closed" 

## Environment
- **Version**: 13,0,1
- **OS**: Windows, and mac 
- **Web server**: safari, chrome, and opera
- **PHP**: 7.3.23
- **Database**: 5.5.5-10.3.28-MariaDB

## Expected and actual behavior
all tickets appear (all open and all closed)

no one tickets appear

## Steps to reproduce the behavior
Activate tickets, agendas, projects
Create a ticket, link it with a project, and valide it
go to "tickets complete list"
clic on "select fields" and add "projects" column, wait for new screen
change a filter like "all open" to "all closed" or another

**Comment by JoAnMaFe** [comment]
The same applies to this configuration.

Versión : [v13 - v13.0.1]
SO : [W10 x64]
Servidor web : [Apache / 2.4.46 (Win64)
PHP : [7.4.15]
Base de datos : [10.4.17-MariaDB]

**Comment by matDOTviguier** [comment]
idem here.

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 13.0.3
