### ISSUE TITLE
Event ticket Error dolibarr 13.0.1

### ISSUE THREAD

**Issue by xerozere** [Dolibarr/dolibarr#16533]
Here massage from X debug

( ! ) Xdebug: user triggered in /var/www/html/dolibarr/htdocs/core/lib/functions.lib.php on line 4182
--

1 | 0.0030 | 363720 | {main}( ) | .../messaging.php:0
2 | 0.0395 | 2409080 | show_ticket_messaging( ) | .../messaging.php:257
3 | 0.0414 | 2443664 | dol_print_error( ) | .../ticket.lib.php:524
4 | 0.0422 | 2490544 | xdebug_print_function_stack ( ) | .../functions.lib.php:4182

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20210304103716
Dolibarr: 13.0.1 - https://www.dolibarr.org
Level of features: 0
PHP: 7.4.9
Server: Apache
OS: Linux erp-clinic 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36

Requested URL: /dolibarr/htdocs/ticket/messaging.php?id=179
Referer: http://192.168.24.52/dolibarr/htdocs/ticket/card.php?action=view&track_id=evy5xekejm489nf3
Menu manager: themeadmin_menu.php

Modules/Applications: api, syslog, user, margin, stock, projet, workflow, import, export, categorie, banque, product, adherent, lemodule, importorderlines, dmadvancedconfig, stocktransfers, easyparam, abricot, scrollto, webservices, oauth, propal, expedition, supplier_proposal, tax, comptabilite, notification, maintenance, ficheinter, pivotreports, productbatch, contrat, barcode, cron, commande, ecm, expensereport, facture, fournisseur, holiday, salaries, societe, service, ticket, website, takepos, socialnetworks, variants, themeadmin, productmixer
Database type manager: mysqli
Latest database access request error: ORDER BY dp DESC, id DESC
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY dp DESC, id DESC' at line 1

XDebug informations:
File: /var/www/html/dolibarr/htdocs/ticket/messaging.php
Line: 257
Function: show_ticket_messaging

**Comment by eldy** [comment]
Try to enable the module Event/Agenda.

**Comment by xerozere** [comment]
Thank you

**Comment by ksar-ksar** [comment]
Hello,

It is working now ?

**Comment by xerozere** [comment]
Yes. very smooth.
