### ISSUE TITLE
Bug: cost price on recurring invoice line is not reported from invoice template

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#16530]
# Bug
I inserted cost price on single invoice line into invoice template. When I go to generate single invoice, cost price is 0.

## Environment
- **Version**:  Dolibarr 12.0.2
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 7.4
- **Database**: mysql
- **URL(s)**: compta/facture/facture.class.php

## Steps to reproduce the behavior
- create template invoice and set cost price for at least one line
- create single invoice
- cost price is 0

Template invoice:
![image](https://user-images.githubusercontent.com/1215488/109823079-e3185400-7c37-11eb-8ecd-65aad39a18f8.png)

Invoice generated from template:
![image](https://user-images.githubusercontent.com/1215488/109823150-f62b2400-7c37-11eb-8b18-fc50d5a96538.png)

Solution:
in compta/facture/facture.class.php:
```
// fix core: 19.coop 
//$fk_product_fournisseur_price = empty($_facrec->lines[$i]->fk_product_fournisseur_price) ?null:$_facrec->lines[$i]->fk_product_fournisseur_price;
//$buyprice = empty($_facrec->lines[$i]->buyprice) ? 0 : $_facrec->lines[$i]->buyprice;
$fk_product_fournisseur_price = empty($_facrec->lines[$i]->fk_fournprice) ?null:$_facrec->lines[$i]->fk_fournprice;
$buyprice = empty($_facrec->lines[$i]->pa_ht) ? 0 : $_facrec->lines[$i]->pa_ht;
// end fix core: 19.coop 
```
buyprice --> pa_ht
fk_product_fournisseur_price --> fk_fournprice

**Comment by eldy** [comment]
Thanks @aschio I fixed a lot of other problem too. My fix is more complete.
