### ISSUE TITLE
CONTRACTLINE_REF DONT WORKING

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#16543]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
THE LINK THAT THE PAYPAL MODULE GENERATES TO BE ABLE TO MAKE A PAYMENT FOR THE CONTRACT LINES DOES NOT WORK, WHEN WANTING TO USE IT IT GENERATES A TECHNICAL ERROR

## Environment
- **Version**: 13.1
- **OS**: LINUX
- **Web server**: NGINX
- **PHP**: 7.4.11
- **Database**: MySQL or MariaDB 5.5.5-10.4.15-MariaDB
- **URL(s)**: htdocs / public / payment / newpayment.php? Source = contractline & ref

## Expected and actual behavior
THE LINK THAT THE MODULE GENERATES IS htdocs / public / payment / newpayment.php? Source = contractline & ref = contractline_ref AND IT IS EXPECTED THAT IF WE INSERT THE CONTRACT SUBSTITUTION CODE AND MAYBE THE CONTRACT LINE THIS WILL GENERATE A VALID LINK TO BE ABLE TO MAKE THE PAYMENT VIA PAYPAL, BUT AS I DESCRIBE IT IS NOT PERFORMING IT.
## Steps to reproduce the behavior
I HAVE ACTIVATED THE PAYPAL MODULE TO GENERATE PAYMENT LINKS FOR VARIOUS ITEMS SUCH AS INVOICES, CONTRACT LINES, ETC. BUT IF I INSERT THE LINK OF THE CONTRACT LINES IN AN EMAIL, FOR EXAMPLE: htdocs / public / payment / newpayment.php? Source = contractline & ref = CT1811-0024 IT DOES NOT WORK, BUT IF I USE A SIMILAR LINK FOR INVOICES IF IT WORKS, FOR EXAMPLE: htdocs / public / payment / newpayment.php? Source = invoice & ref = FA2103-0251.
I HAVE NOTED THAT THE LINK OF THE CONTRACT LINES WORK WITH A COSECUTIVE THAT THE SYSTEM GIVES TO THE CONTRACT LINES BUT I UNDERSTAND THAT THE IDEAL IS FOR IT TO WORK AS SPECIFIED: "contractline & ref" WHICH FROM WHAT I UNDERSTAND IT MUST BE THE LINE OF THE CONTRACT AND THE REFERENCE TO THE CONTRACT, BECAUSE OTHERWISE IT WOULD HAVE TO MAKE A SEARCH IN THE DATABASE UNTIL THE DESIRED REFERENCE IS FOUND.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/28205134/110074303-9a02f580-7d46-11eb-9780-529a0b59eba3.png)

**Comment by atm-maxime** [comment]
Thanks for this detailed report. You can remove the "Instructions" part. And try to shout less louder next time 😉
