### ISSUE TITLE
On a ticket, one should send to a Thirparty without any contact

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16545]
# Feature Request
From #15629 the contact of the Thirdparty can now receive an email related to a ticket. What about a Thirdparty with no contact ?

## Use case
The ticket is linked to a Thirdparty and can be linked to a contact. The email could be only attached to a contact. It is a non sense. If the Thirdparty has an email, one should send any mail related object to it, without using the contact sub object.

## Suggested implementation
No idea at all.

## Suggested steps
List email at thirdpaty level AND thirdparty's contacts level.

**Comment by freechelmi** [comment]
Here on 14.0.4 : 

- Create a Thirrd party with email and no contact
- Create a ticket and select notify the third party 
- Third party is notified for creation
- Then add a message to this ticket and select " send by email" 
- the email of the third party does not appear in the list of the email recipient 
- BUT when sending the notification confirms you that he will be receiving the email
- the third party received the email

We need to show the user that the third party will receive the email by showing it in the recipient

**Comment by freechelmi** [comment]
Confirmed also on 14.0.5 

The 3rd party without contact received the mail but it does appear in the recipient list ( the ticket owner is the only recipient shown here ) 

![image](https://user-images.githubusercontent.com/446021/150508525-ff29fc51-184b-4939-9fb1-87b679d34ad8.png)

**Comment by freechelmi** [comment]
Sorry we can't let the Bot close issues that are valid , well described and not verified by a human , let us help you triage the issues.
