### ISSUE TITLE
variable substitution not working in emails

### ISSUE THREAD

**Issue by Martin-bl** [Dolibarr/dolibarr#16558]
# Bug
*variable substitution codes __EXEMPLE__ not working in email*

## Environment
- **Version**: *12.03*
- **OS**: [*Debian 10 / Debian 4.19.171-2*]
- **Web server**: [*nginx/1.14.2*]
- **PHP**: [* 7.3.27-1~deb10u1*]
- **Database**: [*MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
when writing and email I expected that substitutions __CODE__ that I wrote in the email are substituted by the correct values. 

## Steps to reproduce the behavior
In a invoice, 
(html text enabled)
* clic "send email" 
* wrote some __codes__ available in the trick menu, 
* send 
-> recieved email with __CODES__ instead of values of substitution

Thanks for your job.

**Comment by ksar-ksar** [comment]
Hi,

I can't reproduce. Could you at least upgrade to 12.0.5 ?
All the codes are not working ?
