### ISSUE TITLE
Duplicated lines on fourn product list when several entities

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#16551]
# Bug 
When you use several entities, when products and fourn prod prices are shared between entities, and several prices are created for one product, in this screen htdocs/fourn/product/list.php?fourn_id=xxx, if you use 5 different entities, same product/price is repeated 5 times

## Environment
All versions including trunk

# Fix 
In trunk, file /develop/htdocs/fourn/product/list.php, arround line 161, replace 
`$sql .= " LEFT JOIN ".MAIN_DB_PREFIX."product_fournisseur_price as ppf ON p.rowid = ppf.fk_product";`
by
`$sql.= " LEFT JOIN ".MAIN_DB_PREFIX."product_fournisseur_price as ppf ON (p.rowid = ppf.fk_product and p.entity=ppf.entity)";`

**Comment by atm-maxime** [comment]
@hregis can you have a look ? When the "supplier price sharing" option has been added in multi-company module, the SQL request should have been changed ?
