### ISSUE TITLE
Unable to attach files

### ISSUE THREAD

**Issue by sanjiiiv** [Dolibarr/dolibarr#16553]
After upgrading to 13.0.1, unable to attach files in mails.
After choosing file and uploading it shows File(s) uploaded successfully, but attachment is nil.\

Kindly solve the same at the earliest as unable to send Proposals/ Invoices with attachment using send mail function.

**Comment by Hystepik** [comment]
It works for me in 13.0.1

**Comment by ksar-ksar** [comment]
#16420 #16423 #16488 #16477

FIX is on V13.0.2
