### ISSUE TITLE
LINECONTRACT_INSERT trigger could not handle new line data

### ISSUE THREAD

**Issue by kaizirlewagen** [Dolibarr/dolibarr#16552]
# Feature Request
When the LINECONTRACT_INSERT trigger is called, in difference to the trigger LINECONTRACT_UPDATE, the $object is not updated before the trigger is called. As a result, the newly added object ContratLigne within the trigger code is not available in the property "lines" of $object. 

## Use case
To handle the new line data within the LINECONTRACT_INSERT trigger the $object should be updated.

## Suggested implementation
We have to modify the public function addline() in "contrat.class.php".

## Suggested steps
Add patch1.diff to "contrat.class.php".

[patch1.diff.txt](https://github.com/Dolibarr/dolibarr/files/6089505/patch1.diff.txt)

**Comment by atm-maxime** [comment]
Hi. Thanks for sharing this. I think the proper fix would be to use the insert method of the ContratLigne class instead of doing the SQL insert in the addline of Contrat class. In doing so, the trigger $object should be the ContratLigne object.
