### ISSUE TITLE
MRP/MO: Error message "A kit can't be used into a BOM or a MO"

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#16566]
# Feature Request
The item (box of beer) produced by my BOM is a kit which has 1 son product (beer bottle).

I've validated a 'Bill of Materials' then I've started a new 'Manufacturing order'. This one is refused by Dolibarr with the error message 'A kit can't be used into a BOM or a MO'. The picture is attached.

This type of BOM was running well in October-November with the beta version of the v13. I use now the v13.0.0

When this feature will be reactivated?

![unnamed](https://user-images.githubusercontent.com/3815422/110199349-b004d900-7e60-11eb-96d4-50b8c3cb306a.png)

Thanks.

**Comment by tuxgasy** [comment]
Fixed by #16606
