### ISSUE TITLE
TakePOS: add a lot/batch compatibility

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#16569]
# Feature Request
We would like to use TakePOS but we can't because it's not compatible with the batch number. We are a beer producer, we need to use lot/batch number for food traceability.

## Use case
When I activate the module TakePOS for a sale in our shop, I can't choose the batch number. I guess if I would finalise this sale, the default batch number would be '00000'. My stock would be wrong for the batch sold and the inexistent lot '00000' would be become negative.

## Suggested steps
To be able to select the batch number after selection o the items sold.

**Comment by javierybar** [comment]
Solved with external module
[https://www.dolistore.com/en/products-services-or-stock/1486-TakePOS-Lots---Serials.html?search_query=lots&results=3](https://www.dolistore.com/en/products-services-or-stock/1486-TakePOS-Lots---Serials.html?search_query=lots&results=3)

**Comment by altairis-tof** [comment]
Since lots and serials are now part of Dolibarr, TakePos should be able to manage it

**Comment by syrinx75** [comment]
The lot numbers are still not used in TakePOS.
