### ISSUE TITLE
MAIN_USE_COMPANY_NAME_OF_CONTACT does not work

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#16562]
# Instructions
This hidden option seems not working

*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Use contact name and information rather than company seems not working

## Environment
- **Version**: 12.0.4
- **OS**: Linux
- **Web server**: [*Webserver type and version*]
- **PHP**: 7.4
- **Database**: [*Database type and version*]
- **URL(s)**: https://www.website.xxx/compta/facture/card.php?facid=XXXX

## Expected and actual behavior
Use contact name and information rather than company

## Steps to reproduce the behavior
MAIN_USE_COMPANY_NAME_OF_CONTACT ADD in admin/const.php?mainmenu=home
Generate a bill
Put a contact billing
We should have contact name and information rather than company

**Comment by FHenry** [comment]
Work For Me.
You have to select the other thridparty first and the contact of this other thirdparty

**Comment by lmag** [comment]
Sorry it is ok. 
Just IHM problème !
