### ISSUE TITLE
Bug: export

### ISSUE THREAD

**Issue by higoune** [Dolibarr/dolibarr#16577]
Warning: constant(): Couldn't find constant PHPEXCEL_PATH in /home/clients/215d323ef0ef78b7d0e36d648abd64ce/gestion/dolibarr/core/modules/export/export_excel.modules.php on line 84

Warning: Use of undefined constant PHPEXCEL_PATH - assumed 'PHPEXCEL_PATH' (this will throw an Error in a future version of PHP) in /home/clients/215d323ef0ef78b7d0e36d648abd64ce/gestion/dolibarr/core/modules/export/export_excel.modules.php on line 99

Warning: require_once(PHPEXCEL_PATHPHPExcel.php): failed to open stream: No such file or directory in /home/clients/215d323ef0ef78b7d0e36d648abd64ce/gestion/dolibarr/core/modules/export/export_excel.modules.php on line 99

Fatal error: require_once(): Failed opening required 'PHPEXCEL_PATHPHPExcel.php' (include_path='/home/clients/215d323ef0ef78b7d0e36d648abd64ce/gestion/htdocs') in /home/clients/215d323ef0ef78b7d0e36d648abd64ce/gestion/dolibarr/core/modules/export/export_excel.modules.php on line 99
[*Short description*]

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.27
- **Database**: MySQL or MariaDB 5.6.49-log
- **URL(s)**: /dolibarr/exports/export.php?step=5&datatoexport=adherent_1

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hi,

FIX in V13.0.1
