### ISSUE TITLE
Customer name not showing on TakePOS receipt when using "Dolibarr Receipt Printer" print method

### ISSUE THREAD

**Issue by d3m0nx** [Dolibarr/dolibarr#16575]
the tags {dol_value_customer_firstname} and {dol_value_customer_lastname} yield no value when used on receipt templates that are printed using Dolibarr receipt printer method to print TakePOS receipts

**ENVIRONMENT**
Dolibarr version 13.0.1
Webserver - Apache (running in docker on Ubuntu host with IP address in physical subnet)
Database - Mariadb (also running in docker)

**EXPECTED BEHAVIOUR**
Customer name expected to appear on receipt printout, when using Dolibarr receipt printer print method

**STEPS TO REPRODUCE BEHAVIOUR**
- Activate TakePOS and Receipt printer Modules
- select 'Dolibarr Receipt Printer' option under 'Receipts' tab in the TakePOS Module setup page
- Go to 'Receipt Printers' Module setup page, then add tags {dol_value_customer_firstname} and {dol_value_customer_lastname} to receipt template
- Go to POS module, generate a sale and print receipt. Customer names do not appear on receipt.

**Comment by izrunas** [comment]
Same problem with these customer fields (same steps to reproduce):

{dol_value_customer_mail}
{dol_value_customer_phone}
{dol_value_customer_mobile}
{dol_value_customer_skype}
{dol_value_customer_tax_number}
{dol_value_customer_account_balance}
