### ISSUE TITLE
Custom Status for tickets

### ISSUE THREAD

**Issue by Slydder** [Dolibarr/dolibarr#16571]
Hello,

We are using dolibarr in our company and part of what we do is repairs for phones, laptops, apple devices and such down to the board level. As such we would like to be able to add a few extra ticket statuses to help in sorting through the tickets.  There are currently only "to do", "in progress" and "finished". We would like to be able to add the following.

In Transit inbound
In Transit outbound
Awaiting pickup
Awaiting delivery
Awaiting parts
Awaiting Customer contact

**Comment by atm-maxime** [comment]
Custom statuses is not currently possible in Dolibarr. However, you can create your own attributes in the module setup to manage your specific statuses.

**Comment by Slydder** [comment]
The lack of a custom status option is the reason I started the issue. ;)

It would be nice to have this option. I am currently going through the code to see how difficult it would be to allow for this. Currently having problems finding where the dictionary entries are at.

**Comment by atm-maxime** [comment]
Yes but the status notion is used in every object within Dolibarr and many many things rely on status. That's why it's hard to have them customizable. But you're right this would be nice.

**Comment by Slydder** [comment]
I went ahead and hardcoded 4 new buttons at the bottom and pushed closed and canceled to values of 12 and 13 accordingly. it works great so far. am thinking of offering an option in settings to allow to dis/en-able these buttons for repair shop functionality.

**Comment by atm-maxime** [comment]
Not sure this is generic enough to be part of the standard code but we'll done if you achieved what you wanted

**Comment by Slydder** [comment]
that's why it would ship in an off state and a shop could just activate it if needed.

**Comment by Slydder** [comment]
so. made a non-destructive settings option to enable and disable the extra buttons.
