### ISSUE TITLE
Bug: Event settings changed without interference

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#16592]
# Bug
Event registration for sent emails stopped registering

## Environment
- **Version**: 13.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.27-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1
- **URL(s)**: /azerty/htdocs/admin/agenda.php

## Expected and actual behavior
When sending an email like an invoice or any other email from within Dolibarr, the event should be registred and so has it worked for me. Anyhow, today I noted that this was no more the case, emails that I have sent the last days was not registerd. After looking around on the net I found that the solution could be to have a look in /htdocs/admin/agenda.php  and yes, there was the answer. The settings for all logging of emails had me unknowlingly changed to Not register. After chanching back the settings, all works fine. 

To clairfy; I'm the only one using Dolibarr and no one else has access to the installation. I understand that my Bug report seem odd, but I have not changed any settings by myslef so my suspicion  is that something happend when upgrading to 13.0.1

## Attached files
![klipp1](https://user-images.githubusercontent.com/24247236/110371582-76dd8c00-804d-11eb-8ab7-0369f386bf0a.JPG)
![klipp3](https://user-images.githubusercontent.com/24247236/110384830-7699bc80-805e-11eb-917c-862419d63a67.JPG)

**Comment by eldy** [comment]
After setting back the correct setup, does the feature works correctly ? Or do you loose again the setup few days fater ?

**Comment by hasse-basse** [comment]
I reinstalled from backup and could not reproduce, so I must have done something I shouldn't have done. I close this one
