### ISSUE TITLE
Accent in invoices line

### ISSUE THREAD

**Issue by Ninjabil** [Dolibarr/dolibarr#16595]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
My product description (or invoice line description) don't support special character in the database like accent for exemple.

## Environment
- Version Dolibarr 13.1
- Debian
- Nginx
- Php 7.4
- MariaDB

## Expected and actual behavior
Generate PDF with special character

## [Attached [files]
Here is some screenshot
My invoice line:
![image](https://user-images.githubusercontent.com/78621823/110395264-21fe3d80-806e-11eb-8759-180a5d97794d.png)

My PDF genrated
![image](https://user-images.githubusercontent.com/78621823/110395342-41956600-806e-11eb-8a58-8c653db66631.png)

My database on php my admin:
![image](https://user-images.githubusercontent.com/78621823/110395632-c2546200-806e-11eb-812f-bd1360951fff.png)

Thank you guys !

**Comment by Ninjabil** [comment]
When I edit my database the pdf is well generated

Thanks for your help

**Comment by Hystepik** [comment]
Fix in v.13.0.1

**Comment by Ninjabil** [comment]
I'm actually in 13.1 but the bug is the same only for accent it is writen in html
