### ISSUE TITLE
Incorrect behaviour in Virtual products (Kits)

### ISSUE THREAD

**Issue by MartinFulgueiras** [Dolibarr/dolibarr#16604]
# Bug
[*Short description*]

## Environment
- **Version**: [13.0.1]
- **OS**: [Linux 3.10.0-962.3.2.lve1.5.24.8.el7.x86_64]
- **Web server**: [Apache]
- **PHP**: [7.2.34]
- **Database**: [MySQL or MariaDB 5.7.33]
- **URL(s)**: [.../product/composition/card.php?id=727]

## Expected and actual behavior
Expected: 
When creating a Virtual product (Kit, let's call it AA) and you make up the list of child products that make up Product/Kit AA the warehouse management of the parent and child products should be independent. 
So I have child BB1 in warehouse materials and child BB2 in warehouse packaging and Parent AA in warehouse Delivery. When I create an order for Parent AA the quantities fo BB1 and BB2 in their respective warehouses should diminsh and Parent/kit AA should diminish in Delivery.

Actual:
When creating the order for Parent/kit AA Dolibarr is creating negative entries in the warehouse where Parent/kit AA is stored for child products BB1 and BB2. The quantities in their original warehouses (material and packaging) stays unmodified.

Am I missing something here? Is there a way of stating that product/kit AA is a virtual product? Now the only options are raw material or manufactured item.

**Comment by eldy** [comment]
Option raw material or manufactured item is just a characteristic. It has no effect on stock.
To manage kits, you mut go on tab "Virtual/Kit product".
When you set the child product of a kit on this tab, you can set if stock must be increased of not when the stock of kit is modified.

However, the feature to manage different warehouses for each child product of kit is not an available feature for the moment.

**Comment by MartinFulgueiras** [comment]
Thanks for the reply Eldy. 

As it is, it's incorrect behaviour that wrong warehouses are increased or decreased. Everything is being accounted (negatively) on the warehouse of the parent product although child products are not stored there (and there's no stock).  

Kits for virtual products (eg a bundle promo of 2 existing products) don't need stock as they come from each child's warehouse and are bundled on delivery. 

I just revised and the behaviour doesn't happen when stocks are not allowed to be negative (ie. a negative creation of child's product on parent's warehouse), but it doesn't decrease the child's consumption. 

Thanks!
