### ISSUE TITLE
Date minored by 1 hour after after time zone swap to summer time

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#16600]
# Bug
while setting a appointment after 28/03 (switch to local time zone : summer) the appointment is minored by h-1

## Environment
- **Version**: 13.0.1

current discussion on French forum : 
https://www.dolibarr.fr/forum/t/probleme-horaire-dans-le-module-agenda-v13
https://www.dolibarr.fr/forum/t/bug-critique-agenda-evenement-sur-une-journee-v13-0-1

**Comment by henosis76** [comment]
We hit this bug and the agenda will not be longer usable by customers after the 28/03. 
**Really critical for us.**

each time a dairy event is edited, the event date switch to the day before due to this bug.

**Comment by henosis76** [comment]
Hello,

We again hitting the bug in the Dolibarr 14.0.5 for all event after March 26 2022 ( Summer Time in France)
The bug is always here...

We have apply the fix below:
replace all "tzuser" and "tzuserrel" variables in /htdocs/comm/action/*.php  by the variable "tzserver"
