### ISSUE TITLE
Can't create holiday if advanced permissions activated

### ISSUE THREAD

**Issue by tomours** [Dolibarr/dolibarr#16608]
# Bug
Create holiday doesn't work. See MR

## Environment
- **Version**: 13.0.1
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Create holiday doesn't work

## Steps to reproduce the behavior
Create new holiday (with advanced permissions activated)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
Fixed also by 67f5837072bdcd63b769ece06d6daeaec4dbee73
