### ISSUE TITLE
"Force invoice date" does not alter invoice date

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#16613]
Setup -> Modules -> Invoices -> setting "Force invoice date to validation date" to "Yes" does not change the invoice date at all in Dolibarr 12.0.4. Invoice date (draft) is set to 2021-02-18 and validated today (2021-03-10), but the invoice date is still set to 2021-02-18 after validation.

**Comment by eldy** [comment]
Note: This feature works only the first time (first validation of draft invoice).
i have complete label of option into
"Force invoice date to validation date (forcing is possible only the first time an invoice is validated)"

**Comment by bos4711** [comment]
If that's the case (I haven't tested) then I still have some opinions about it. When setting this setting to "Yes", the ability to modify the invoice date is removed. This in combination with the fact that the "force date" only works for the first time is not good in case the invoice needs to be changed.

Example ("force date" = yes):

2020-01-01 Draft, Invoice date = 2020-01-01
2020-01-09 Validated, Invoice date = 2020-01-09
2020-01-09 Draft, because I forgot something, Invoice date = 2020-01-09
2020-01-20 Validated, because I fixed it, Invoice date = 2020-01-09

And here I'm not able to change the date because "force date" setting removes the ability to change the setting.

My opinion, allow either these scenarios:
1. force date = yes, still allow the user to change the date (because of above reason)
OR
2. force date = yes, alter the invoice date everytime it goes from draft -> validated.
