### ISSUE TITLE
Not able to display product text extrafield on odt shipment template

### ISSUE THREAD

**Issue by mpractic** [Dolibarr/dolibarr#16624]
# Bug

It's not possible to display a product extrafield within an odt shipment template. All other shortcodes are working properly but not this one ({line_product_options_xxx}).
My goal is adding an extrafield to the products and include it into the shipment orders so the warehouse guys can check those notes when packing the items.

I think other users are affected:
https://github.com/Dolibarr/dolibarr/issues/9183
https://github.com/Dolibarr/dolibarr/issues/12873

## Environment
- **Version**: 13.0.1
- **OS**: Debian 10
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.4.15
- **Database**: Mariadb

## Expected and actual behavior

The line "{line_product_options_xxx}" is expected do get repaced by the actual content, but unlike the other shortcodes, it's displayed as it.

## Steps to reproduce the behavior

- Create a product extrafield (text).
- Create a test product and write anything inside the text extrafield.
- Create and upload an odt shipment template that contains the extrafield product line "{line_product_options_xxx}".
- Create a shipment containing the test product and generate an odt document.
- Check result. You will see "{line_product_options_xxx"} instead of the expected test text.

## Attached files

Attaching template and result.
[template.zip](https://github.com/Dolibarr/dolibarr/files/6124718/template.zip)

**Comment by ksar-ksar** [comment]
Hello,

Link to #16341

Corrected in this PR : #16583

**Comment by mpractic** [comment]
Thanks!
