### ISSUE TITLE
Bug: Absence of indicator of the number of tickets in use in a project inside a costumer

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#16623]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 13.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.2.37-MariaDB
- **URL(s)**: /basedados/projet/card.php?id=504

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by alimentarius** [comment]
![Screenshot_2021-03-11 Lista de tickets](https://user-images.githubusercontent.com/19837231/110820526-16d22a00-8287-11eb-85d8-f7a3dd8c940a.png)

**Comment by ksar-ksar** [comment]
Hi,

Could you explain a bit more ?

**Comment by dolibit-ut** [comment]
I don't really know, but I think it means that the Tickets card/tab doesn't show the number of tickets assigned to the project.
(like you can see at contacts or documents)

**Comment by ksar-ksar** [comment]
Ok thanks for the translation 👍 

Then it is a Feature Request not a BUG

**Comment by dolibit-ut** [comment]
I see now that it is also a bug - not only that it not shows the number of tickets assigned to a project.

If you want create a ticket from project you have to select the project again on creation template.
So we have two fields **project**:
One at top of the form you can not change.
And another at bottom of the form you have to choose.

That's maybe a bug.

If you do not choose the project at the second field, the ticket is not assigned.

And you can not change this field to link to a project afterwards.
That's a second bug.
