### ISSUE TITLE
Compatibility phpv8

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#16628]
Install php v8, check that dolibarr gui is working correctly without warning. Fixing any reported error and warning by navigating in each screen.

**Comment by ksar-ksar** [comment]
Hi,

Need to check on develop or V13 or both ?

**Comment by eldy** [comment]
On develop only.

**Comment by frederic34** [comment]
PHP Warning:  Undefined array key "dol_entity" in /home/fred/netlogic/dolibarr/htdocs/main.inc.php on line 788

**Comment by frederic34** [comment]
PHP Warning: Undefined array key "dol_entity" in dolibarr/htdocs/main.inc.php on line 788
PHP Warning:  Undefined array key "dol_screenwidth" in dolibarr/htdocs/main.inc.php on line 1996
PHP Warning:  Undefined array key "dol_screenheight" in dolibarr/htdocs/main.inc.php on line 1996
PHP Warning:  Undefined array key "dol_dst" in dolibarr/htdocs/main.inc.php on line 1987
PHP Warning:  Undefined array key "dol_tz_string" in dolibarr/htdocs/main.inc.php on line 1989

**Comment by frederic34** [comment]
PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, string given in dolibarr/htdocs/core/lib/memory.lib.php:96\
https://github.com/Dolibarr/dolibarr/pull/16648

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/111078933-17252c00-84f8-11eb-9804-ef257fee081d.png)
