### ISSUE TITLE
Bug: supplier invoice 

### ISSUE THREAD

**Issue by RalfWillkommen** [Dolibarr/dolibarr#16621]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*supplier invoice - unmarked positions*]

## Environment
- **Version**: 12.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: apache2handler 7.2.24-0ubuntu0.18.04.7
- **Database**: MySQL or MariaDB 5.7.33-0ubuntu0.18.04.1
- **URL(s)**: /fourn/facture/card.php?id=131&action=ask_deleteline&lineid=517&page_y=285

## Expected and actual behavior
[*In the draft for supplier invoices there is a possibility to mark or unmark positions which are delivered and settled by the supplier. 
When I unmark several positions and press confirm, then all positions equal if marked or unmarked are taken to the supplier invoice*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by dolibit-ut** [comment]
Yes, i checked this and can confirm the bug.

**Comment by eldy** [comment]
I can't reproduce with v13.
If you can, can you paste a screenshot ?

**Comment by dolibit-ut** [comment]
create purchase order

![grafik](https://user-images.githubusercontent.com/45215329/110938405-1d6aab00-8334-11eb-8ab6-21dc7ec0d5be.png)


create supplier invoice from purchase order
and select only one line to take over in draft

![grafik](https://user-images.githubusercontent.com/45215329/110938820-bb5e7580-8334-11eb-8bea-b8c37510156f.png)

but draft took all lines
![grafik](https://user-images.githubusercontent.com/45215329/110938915-e3e66f80-8334-11eb-9f34-c5f8bee8bafa.png)
