### ISSUE TITLE
Bug: attribute_combination2val cannot have more than one of the same attribute

### ISSUE THREAD

**Issue by Dev-rdg** [Dolibarr/dolibarr#16622]
# Bug
When on the variant creation page: variants/combinations.php?action=add
It is possible to add the same attribute more than once 
eg: attribute id 1 is color -> i can add two attributes color to the combination form
But in the code, in the same file line 128 ; the attribute id is used as key to populate the array sanit_feature which is then used 
to create to product combination if it doesn't exists.
This operation silently erase one of the two attribute; the first one in fact since it happens in a foreach loop.
I see several problem with the approch taken here
1 - There is no validation in the form that prevents adding two attributes of the same type
2 - There is no error whatsoever regarding the fact that adding two of the same attribute type is not allowed; it just fails to create the product without warning
3 - Nothing in the db schema prevents the use case of adding more than once an attribute there is even a variable in variants/combinations.php named $productCombination2ValuePairs1 that records all of the product combinations but it is never used anywhere in the $action 'add' ||'create'  block

## Environment
- **Version**: 10.0.3
- **OS**: Ubuntu 20.04
- **Web server**: apache 2.4.41-4ubuntu3.1
- **PHP**: 7.4.16-1+ubuntu20.04.1+deb.sury.org+1
- **Database**: 8.0.23-0ubuntu0.20.04.1
- **URL(s)**: variants/combinations.php?action=add and action=create

## Expected and actual behavior
It should be possible to add the same attribute type more than once or have an form validation/error message to prevent user from doing so
![Screenshot_20210311_165420](https://user-images.githubusercontent.com/80473041/110815186-84cc2080-828a-11eb-8976-072864c118d9.png)

I am willing to submit a pull request altering that behavior to allow that since it's the use case i want, but i would have to touch at several files

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?
