### ISSUE TITLE
replace BACK button "javascript:history.go(-1)" with different fallback

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#16635]
# Feature Request
We have had problems with users "going back" after form submissions. Generating duplicate items.
At first I tried to block all going back actions with javascript.
This resulted in breaking all BACK buttons that have "javascript:history.go(-1)" as the fallback/action. I reverted that hotfix.

It would be great to integrate proper saveguards to block duplicate content creations.

removing `javascript:history.go(-1)` would be a start!?

**Comment by ksar-ksar** [comment]
Hi,

With the Security Token implemented now in V13, it should be impossible to have duplicate items no ?

**Comment by cfoellmann** [comment]
Right, that should block duplicate content creation.
But the user is still confronted with the dialog to send the form again.

I will look into this further when we "launch" dolibarr internally as a installed pwa

**Comment by cfoellmann** [comment]
This is more or less done
