### ISSUE TITLE
body vs leftmenu on product/fournisseurs.php?id=

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#16631]
# Bug
On `product/fournisseurs.php?id=` I get the issue you can see in the picture.
The "content" is too wide for the leftmenu.
As far as I can see this is just on this page. Anyone else seeing this? Or is it something on my end!?

![image](https://user-images.githubusercontent.com/1256090/110931645-cc09ee00-832a-11eb-9719-2a1d983e0cbf.png)

## Environment
- **Version**: 13.0 branch

**Comment by eldy** [comment]
According to the screenshot of the bug you mention, it seems you have a non official menu entry compared to standard version in the left area. Probably coming from an external module or experimental option. Fix should be done into this external module or option.

**Comment by cfoellmann** [comment]
yes, deactivated these elements and it is fixed. sorry
