### ISSUE TITLE
Support Customer Invoices made by third parties under a Billing Mandate (Mandat de Facturation).

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#16640]
# Feature Request
Support Customer Invoices made by third parties under a Billing Mandate (French: Mandat de Facturation).

## Use case
- The third party has a contract with the Company (dolibarr user) allowing them to emit invoices for the account of the Company.
- The concrete example is that the Third Party bills Consulting Services and generates two invoices at once: one to bill the end Customor with his middleman fee, and a second one which bills the Services provided by the Company to the end Customer.  The end Customer pays the Company directly for this part.
- Another use case is where the Company sells products for the Third Party.  The Third Party does not invoice the products to the Company, but emits invoices on behalfs of the Company to bill the Third Party for the Sales Fee they pay to the Company for each product sold. or each microservice rendered)  (This avoids that the Sales Volume of the product enters in the Sales Volume of the Company which given the low sales fee would be quite unfair).

## Suggested implementation

- Add a new type of Customer invoice;
- The simpliest implementation would be to let the user enter the invoice number for a Company Bill generated under a Billing Mandate;
- The above two items would be the "minimum feature set";
- It would be required that these invoice numbers are unique in the system (independent of the third party);
- A more advanced implementation would be to let the user enter the invoice number, but also check the invoice numbering sequence as the separates numbering sequence needs to be complete..  The system could warn about missing sequence numbers when creating the new invoice and/or on the main page.
- An even more advanced implementation would allow the user to choose the next invoice number from a dropdown;
- An even more advanced implementation would allow defining separate numbering systems for Billing Mandates and also link Billing Mandates to the Third Party that is creating the invoices (and allow to get the list of these invoices).

## Suggested steps

- [ ] Create a new invoice type;
- [ ] Adapt the Supplier Invoice methods to support Invoices made under Billing Mandate.  The behavior is very similar (the user can enter a "free" text for the invoice, and the invoice numbers are already checked for uniqueness within the Customer's list).
- [ ] Adjust the verification of uniqueness of the invoice number of a Billing Mandate.
- [ ] Add a check for missing invoice numbers under the Billing Mandate, perform this check when a new bill is added and  and set a flag accordingly - the flag could be "empty" when everything is ok and containe the id of the first missing bill found when not ok (to help the user identify the missing bills).
- [ ] Generate a temporary notification when a missing bill is identified, showing the first missing bill label.
- [ ] Generate a "permanent" notification on the main page showing that bills are missing.
- [ ] Define further steps for the further advanced functionnalities.

**Comment by atm-maxime** [comment]
@aspangaro any advice on the matter? How does it work in accounting?

**Comment by mdeweerd** [comment]
## Workaround
I had to add such an invoice to Dolibarr today.  I temporarily changed the invoice numbering rule, added the invoice and reverted to the original numbering rule.
