### ISSUE TITLE
Date in article not updated when document is cloned

### ISSUE THREAD

**Issue by tootai** [Dolibarr/dolibarr#16649]
# Bug
[Article date not updated when cloning document]

## Environment
- **Version**: [13.0.1]
- **OS**: [Debian 10]
- **Web server**: [Nginx 1.14.2]
- **PHP**: [7.4]
- **Database**: [mariadb 10.3]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]
If an article has a date in description eg valid from dd/mm/yyyy to dd/mm/yyyy in a document, the date is not updated when document is cloned in another month. This  is a regression since 13.0.0

## Steps to reproduce the behavior
[*Verbose description*]
Create a document with date eg in january, add an article having a valid date like from 01/01/2021 to 31/01/2021, validate the document and than clone it in february: the date does not evoluate in 01/02/2021 to 28/02/2021

**Comment by eldy** [comment]
For which document for example (invoice, order, proposal ?)

**Comment by tootai** [comment]
I use this feature only with invoices

**Comment by eldy** [comment]
This feature is not on by default.
Try to add this constant into home - setup - other
INVOICE_AUTO_NEXT_MONTH_ON_LINES to value 1

**Comment by tootai** [comment]
I did it and:
. option doesn't exist in the list of known_hidden_options from wiki
. I creatre it but it never appears in option list after validation
. gave it a try => still no date update
BTW, I never activate such option in 12.x

**Comment by tootai** [comment]
Tried with FF and chrome, no changes. Home - Setup - Other is in french Accueil - Configuration - Divers, right ?

**Comment by tootai** [comment]
Installed 13.0.2, problem is still there.

**Comment by tootai** [comment]
Le 15/03/2021 à 14:15, Laurent Destailleur a écrit :
>
> This feature is not on by default.
> Try to add this constant into home - setup - other
> INVOICE_AUTO_NEXT_MONTH_ON_LINES to value 1
>
Any news about this ?

For the record, this parameter was added but doesn't change anything. 
Remember that in 12.x it was working without this parameter.

Regards

-- 
Daniel

**Comment by tootai** [comment]
Update to 15.0.1 still not working :(
