### ISSUE TITLE
Cannot (re)edit extrafields in shipment modul

### ISSUE THREAD

**Issue by danloic** [Dolibarr/dolibarr#16647]
# Bug
When you creat a shipment after created an order, it's possible to fill extrafields only when you can select how many product or service you want to ship, after this step it's impossible to (re)edit the extrafields (to add a remark or something other). So it's just before the validation of the shipment receipe.  

## Environment
- **Version**: V13, V13.0.1
- **OS**: Windows Server, Windows 10

**Comment by Hystepik** [comment]
Hello,
It seems to be fixed so I close the issue.
Feel free to reopen if not.
