### ISSUE TITLE
Bug: back arrow in browser can validate 2 times an order without reopening it, creating wrong stock movement

### ISSUE THREAD

**Issue by zuiko** [Dolibarr/dolibarr#16719]
# Bug
If the stock module is set to "Decrement physical inventory upon validation of customer orders", usibg back arrow in browser can make the stock management of some products wrong.

## Environment
-Version: 12.0.4
-OS: Linux Debian 3.16.64-2 (2019-04-01) x86_64
-Web server: Apache/2
-PHP: PHP 5.6.40
-Database: MySQL or MariaDB 5.6.48-log
-URL(s) /product/stock/product.php

## Expected and actual behavior
If the stock module is set with _"Decrement physical inventory upon validation of customer orders"_
A validated order decrement correctly the stock.
But using back arrow in browser to verify the order after shipment change the previous stock movement.
This is not the expected result.

## Steps to reproduce the behavior
**Stock module settings:**
![image](https://user-images.githubusercontent.com/1511011/111210403-7ef97680-85cd-11eb-8fc6-f4f603eea1d9.png)

**Verify the stock of a product = 3**

**Sell it by a validated order: 1**
![image](https://user-images.githubusercontent.com/1511011/111211780-1d3a0c00-85cf-11eb-9a92-abda4b40bb0a.png)
**Control the stock of this product: 2**
![image](https://user-images.githubusercontent.com/1511011/111212152-8b7ece80-85cf-11eb-8804-f9b13ab72980.png)
**Control the stock movement: OK the stock movement is involved by the order**
![image](https://user-images.githubusercontent.com/1511011/111212567-07791680-85d0-11eb-87d8-4efe0e0a1e32.png)
**Create and validate the shipment of this product: 1 product**
![image](https://user-images.githubusercontent.com/1511011/111213391-009ed380-85d1-11eb-9bd1-ecf052ff232f.png)
**If I return to the same order using back arrow of the Firefox browser, some time after: The order appears validated 2 times**
![image](https://user-images.githubusercontent.com/1511011/111220456-8030a080-85d9-11eb-8502-14fabdb1418b.png)
![image](https://user-images.githubusercontent.com/1511011/111220609-af471200-85d9-11eb-886b-ea6f5112a681.png)
**And there is 2 stock movements**
![image](https://user-images.githubusercontent.com/1511011/111221001-398f7600-85da-11eb-8aa2-a91dc014b046.png)
**and the stock for this product is now wrong: 1 instead of 2**
![image](https://user-images.githubusercontent.com/1511011/111221382-b6baeb00-85da-11eb-9113-03892772270d.png)

**After analysis, this sort of behaviour seems to be due to coming back with back arrow browser.**

## Expected behavior
**If the stock module is set with _"Decrement physical inventory upon validation of customer orders"_
a later coming back to the order using back arrow of the browser should not change the stock which has already been done by the order validated.**

**Comment by zuiko** [comment]
**But sometimes we can have a correct behaviour
Same product stock = 1**
![image](https://user-images.githubusercontent.com/1511011/111223369-5aa59600-85dd-11eb-9cc6-e8c3d529b524.png)
**Order validated with 3 items**
![image](https://user-images.githubusercontent.com/1511011/111224023-34342a80-85de-11eb-89f3-09895d8f8807.png)
**To be able to ship the order I must increase the negative stock at least +2:**
![image](https://user-images.githubusercontent.com/1511011/111224262-7a898980-85de-11eb-9196-ccf345227b41.png)
**You can see it done in the stock movement:**
![image](https://user-images.githubusercontent.com/1511011/111224715-1fa46200-85df-11eb-8652-0bc353a6ea32.png)
**If I try to make a shipment, Dolibarr says me that the stock is not sufficient:**
![image](https://user-images.githubusercontent.com/1511011/111225595-4747fa00-85e0-11eb-8d69-2556643f71d4.png)
**But it agrees to do it and validate it:**
![image](https://user-images.githubusercontent.com/1511011/111225853-9726c100-85e0-11eb-8f2b-9775f5b14728.png)
**And you can see that this time there is no stock movement for this shipping, which is perfect.**
![image](https://user-images.githubusercontent.com/1511011/111227729-4b294b80-85e3-11eb-813c-ab8db12b7aa8.png)

**Comment by zuiko** [comment]
Sorry, but after a more accurate analysis, I have completely changed the supposed origin of the cause of the problem.

**Comment by kuipumu** [comment]
@zuiko have you found a temporal fix to this problem?

**Comment by zuiko** [comment]
@kuipumu infortunately I have not, I just advised my users to avoid to do that...

**Comment by ksar-ksar** [comment]
Normally on V13 with the new security check it should not be possible.

Could you try ?
