### ISSUE TITLE
Current outstanding bill is not correct

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16725]
# Bug
The outstanding bill is shown on a customer, calculting the sum of the bills, not calulating the sum of the Remaining unpaid only. If a customer has paid a part of a bill, the oustanding bill is not showing the outstanting remainning to pay only.

## Environment
- **Version**: 13.0.1

## Expected and actual behavior
Actual : Sum of the total to pay for the total of invoices.
Expected : Sum of the total ramaining to pay.

**Comment by Hystepik** [comment]
Hello,
It works for me in 13.0.2, try to update to 13.0.2

**Comment by atm-maxime** [comment]
Also works for me with partially paid invoice and invoice with a credit note applied on

**Comment by Hystepik** [comment]
It seems to be fix so I close the issue.
Feel free to reopen if not.
