### ISSUE TITLE
Add a button in Orderline to create a MO

### ISSUE THREAD

**Issue by whynotwi** [Dolibarr/dolibarr#16735]
# Feature Request
[*To create a MO needs to go to the BOM and create a MO from the called BOM. I miss a function where i can create a MO directly from the order line.*]

## Use case
[*In our case we have products which we just sell (trade ware) and products we have to assemble first (production ware). For products to be assembled we create a MO. But this is very cumbersome, as we have to leave the order (or open a new tab in the browser), open the BOM, filter for the product and open the BOM. Afterwards we have to press "Create Manufacturing Order" and then the MO is created.
We would like to create a MO from the order line, as already there is known which product has to be assembled.*]

## Suggested implementation
[*Just a button in every order line of products which don't have the option "to buy". Don't filter for "to sell" also, as there are products which are produced and are raw material for other products (and hence are not sold)*]

**Comment by elsp1991** [comment]
I totally agree with you whynowi, also would be nice of the MO will appear under the Related objects in the order
