### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#16767]
# Bug
I can't delete file to send email

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /comm/propal/card.php?id=1113

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Erro correo](https://user-images.githubusercontent.com/53640168/111509489-c6414d80-871a-11eb-9bc7-ff718f2dab60.jpg)

**Comment by daraelmin** [comment]
Bug probably linked to fix for #16420 and #16423.

**Comment by leninrivas** [comment]
> Bug probably linked to fix for #16420 and #16423.

Attach files is ok. The problem is to delete.

**Comment by daraelmin** [comment]
I've understand the problem, but if you read thé thread un #16420 you'll see that xbloq and I have faces a similar issue while trying to solve the issue. 

It seems to us, that it happens when using multilanguage... So do you use it ?

Thats why I think it ils linked to the fix.

**Comment by xbloq** [comment]
V13.0.2
@daraelmin I have the same problem than @leninrivas with the new version

VERY IMPORTANT: I haven't idea that I'm doing, only information

In line 385 I changed

if (GETPOST('mode', 'alpha') == 'init' || (GETPOST('modelmailselected', 'alpha') && GETPOST('modelmailselected', 'alpha') != '-1'))

by

if (GETPOST('mode', 'alpha') == 'init' || (GETPOST('modelselected') && GETPOST('modelmailselected', 'alpha') && GETPOST('modelmailselected', 'alpha') != '-1'))

all it's working again

**Comment by daraelmin** [comment]
> V13.0.2
> @daraelmin I have the same problem than @leninrivas with the new version
> 
> VERY IMPORTANT: I haven't idea that I'm doing, only information
> 
> In line 385 I changed
> 
> if (GETPOST('mode', 'alpha') == 'init' || (GETPOST('modelmailselected', 'alpha') && GETPOST('modelmailselected', 'alpha') != '-1'))
> 
> by
> 
> if (GETPOST('mode', 'alpha') == 'init' || (GETPOST('modelselected') && GETPOST('modelmailselected', 'alpha') && GETPOST('modelmailselected', 'alpha') != '-1'))
> 
> all it's working again

it was an underlying suggestion of my comment https://github.com/Dolibarr/dolibarr/issues/16423#issuecomment-788077594 to replicate the condition of lign 333 at line 385.

I'll propose this solution as a fix un a few moment

**Comment by xbloq** [comment]
thanks @daraelmin
