### ISSUE TITLE
Feature request: allow editing supplier invoice even after draft status

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#16772]
I sometimes work fast and finish an invoice before the descriptions of lines are perfect.
Dolibear wants me to first change to unpaid, then remove the payment and then modify before I can edit any of the descriptions. Thats annoying. 

I then go to the database find the lines in facture_fourn and set the status to 0 which means draft. 

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.14
- **Database**: PostgreSQL 13.1
- **URL(s)**: /fourn/facture/card.php?id=230&action=confirm_paid&confirm=yes&token=%242y%2410%244tfSqwLBufZsA3w13kXDfuQaAXrguogOuQ3jroQkd28m1CxtWU5fu

## Expected and actual behavior
mark an invoice as paid and try editing the description on any line

**Comment by atm-maxime** [comment]
How is that a bug ? Everywhere in Dolibarr you can edit documents only when it's in draft status, that's the standard expected behavior. That being said I can understand that you want to record supplier payments before finishing the invoice details recording. So a good feature request to ask for would be "allow editing supplier invoice even after draft status"

**Comment by dpriskorn** [comment]
It seems this feature already exists!
![image](https://user-images.githubusercontent.com/68460690/155358155-50c0c62a-09c0-465b-89df-5574a22ff088.png)
https://wiki.dolibarr.org/index.php/Setup_Other

**Comment by atm-maxime** [comment]
I guess it's for customer invoices

**Comment by dpriskorn** [comment]
> I guess it's for customer invoices

Yes, exactly

**Comment by edupulpillo** [comment]
Is also very useful for Supplier invoices, and is not working with suppliers in dolibarr v22.0.4
