### ISSUE TITLE
After some more testing on version 13.0.2 by Fred and me we still encounter the same error:

### ISSUE THREAD

**Issue by jongerli** [Dolibarr/dolibarr#16793]
After some more testing on version 13.0.2 by Fred and me we still encounter the same error:
Remote host said: 550 Maximum line length exceeded (see RFC 5322 2.1.1).
Problem not solved yet.

_Originally posted by @jongerli in https://github.com/Dolibarr/dolibarr/issues/13510#issuecomment-801818981_

**Comment by ksar-ksar** [comment]
Duplicated of #13510

Close
