### ISSUE TITLE
Bug: the UI truncates zeros in the end of account numbers

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#16821]
# Bug
in Sweden we have account numbers like 3900, 5400, etc.
When add accounts manually the UI truncates the zeros in the end so 3900 -> 39 in the database table llx_accounting_account column account_number.

That's pretty annoying.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.14
- **Database**: PostgreSQL 13.1
- **URL(s)**: /accountancy/admin/account.php

can someone confirm on v13?

**Comment by daraelmin** [comment]
Theres already an option for thid

Update your version to 12.0.5

Then in General setting of accounting, activate the third option.

![IMG_20210320_211605.jpg](https://user-images.githubusercontent.com/8067223/111884371-99fb2a80-89c1-11eb-8d21-b92aac74b8a0.jpg)

**Comment by daraelmin** [comment]
@eldy when acrivating the swiss chart of account the option is automatically set, it may be interesting to do so whith the sweedish chart of account.

**Comment by dpriskorn** [comment]
Thanks for the explanations 😃
