### ISSUE TITLE
Clarify the vocabulary of Adherent's module

### ISSUE THREAD

**Issue by daraelmin** [Dolibarr/dolibarr#16887]
#  Clarify vocabulary of the module adherent in english and in french

In particular :
Adherent (adhérent) 
Member (membre)
Membership (adhésion)
Subscription (cotisation)

I request a clarification is it a new feature ?

## Use case
In my acceptance:

A member has the right to vote.

An adherent is not necessarly member. He can support the association, participate to some events.

An adherent or a member can contribute several times, over time and at the same time (as an activist and as a beneficiary for example), but his membership only exists once.

A membership does not necessarily imply a subscription (honorary member, association without subscription, etc.) or it maybe a one shot subscription for all time.

a subscription does not necessarily imply membership, typically when the association provides for a "supporter" status without voting rights

Since I am interested and that jutilse Dolibarr to manage the members of my association, I come up against a problem of terminology. In French, the concepts are mixed because these words have several meanings. It seems to me that this is less the case in English.

Let's take this opportunity to discuss and clarify the underlying terminology. 

## Suggested implementation
Adherent module
Class adherent  / member
Class subscription 

## Suggested steps
1) Clarify termes and fix concept related into a glossary
2) Change french translation
3) Translate into code and use right word for right thing

**Comment by dolibit-ut** [comment]
I agree!  I saw the same issue by check the translations.

We need to clarify the termes: 
member vs. membership / subscription

**Comment by daraelmin** [comment]
This commit bcd835d is a very good start.
Let's work on translation (transifex)
