### ISSUE TITLE
TakePOS : use absolute discount as a paiment method

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#16937]
In TakePOS, when we set the customer to an existing thirdparty that have an absolute discount, it would be nice to be able to pay using this discount with one click.

**Comment by Guiguimps** [comment]
Hello, I just found this opened issue ! And that's exactly what I need.
@dbeniamine do you found a solution to use the absolute discount in TakePOS ?

**Comment by dbeniamine** [comment]
> Hello, I just found this opened issue ! And that's exactly what I need. [@dbeniamine](https://github.com/dbeniamine) do you found a solution to use the absolute discount in TakePOS ?

Nope, this was a "Nice to have" but we did not worked in this specific issue ...
