### ISSUE TITLE
Images in Product Datasheet Generation Through Products Standard_PDF

### ISSUE THREAD

**Issue by thegeettanna** [Dolibarr/dolibarr#16939]
Dear Dolibarr Community, 
Hope you guys are all doing well. 

This feature request is for creating product technical data-sheets using the pdf generation option in products module. 
There is a standard pdf template in ERP. Although it does not include any pictures from the product. 
Only the description is available which does not help when sending it to client. 

We would like to be able to generate product data sheets for all the products. 
If a product has images, they should appear as shown in the marked up example of the generated standard pdf. 
[KTI16016001CASS_YELLOW.pdf](https://github.com/Dolibarr/dolibarr/files/6187043/KTI16016001CASS_YELLOW.pdf)

## Use case
Every brand has product sheets that are shared. I have added an example from the brand 3m. 
They have a product sheet for something that sells at less than half a dollar. 
Being able to generate product sheets help create a brand, but also give product the look and feel of being something important. 
[FINAL lo-res Classic.pdf](https://github.com/Dolibarr/dolibarr/files/6187044/FINAL.lo-res.Classic.pdf)

Also, if someone has any other pdf templates that they would like to share, please do that to help the community. Would appreciate it.

**Comment by thegeettanna** [comment]
@eldy, 

Any help here? 
Just a little guidance would work as well. 

Thanking you, 
Geet.

**Comment by Be0rn01** [comment]
Hi, 
Search also a solution, there Leboubou111 as make something great, and it can be a good base to work around

- https://github.com/Dolibarr/dolibarr/issues/11039 

Cheers,

**Comment by thegeettanna** [comment]
@Be0rn01, 

Appreciate the mention of the other thread. It definetely help us to begin with a strong base. 
Thank you 🙂.
