### ISSUE TITLE
Dolibarr doesn't wanna install on a remote database

### ISSUE THREAD

**Issue by M1ndo** [Dolibarr/dolibarr#16936]
# Bug
Recently i wanted to install dolibarr on my local server however mysql is server is not hosted in the same server as dolibarr, and that results into issues when installing .

## Environment
- **Version**: [*13.0.1, 13.0.3*]
- **OS**: [*Ubuntu 16.04 LTS*]
- **Web server**: [*Nginx*]
- **PHP**: [*PHP 7.0*]
- **Database**: [*10.5.9-MariaDB *]
- **URL(s)**: [*http://ip/dolibarr/htdocs/install/step1.php*]

## Expected and actual behavior
when using remote mysql database server of another host it doesn't wanna continue with the installation and it stops at the following error: ```Error: DB_ERROR_ACCESSDENIED Access denied for user 'root'@'172.16.79.134' to database 'dolibarr2'. Connected user not allowed to GRANT ALL PRIVILEGES ON dolibarr2.* TO 'dolibarr22'@'%' IDENTIFIED BY '*****'```
```Server "172.16.79.130", database name "dolibarr2", login "dolibarr22", or database password may be wrong or the PHP client version may be too old compared to the database version.If the user does not exist yet, you must check option "Create user"```
- 172.16.79.134 is where dolibarr is hosted (ubuntu 16.04)
- 172.16.79.130 is where mysql is hosted (Arch Linux)

## Steps to reproduce the behavior
- Use Another Mysql Server Other Than Local Mysql server to install dolibarr

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![2021-03-22-135632_1801x339_scrot](https://user-images.githubusercontent.com/44820142/111993529-a0e38380-8b0e-11eb-952f-c9a3148c8f9a.png)
![2021-03-22-135559_1751x633_scrot](https://user-images.githubusercontent.com/44820142/111993563-ad67dc00-8b0e-11eb-8909-ec27f8aaddc1.png)

**Comment by ksar-ksar** [comment]
Hello,

It doesn't seems to be a dolibarr bug, this is link to your setup.
Either the 172.16.79.130 doesn't accept external connexion or the Dolibarr user is not allowed from remote
Or the 172.16.79.134 block the connection.

You need to analyze the logs of MYSQL server first.

**Comment by M1ndo** [comment]
@ksar-ksar Thanks for replying , i have mysql setup to accept external connection in fact i can connect to mysql from the ubuntu server and it's all works fine ,however when installing dolibarr it's doesn't want to connect like u see in the screenshot.
i have set it mysql server to be 172.16.79.130 and it does create a database on mysql but when creating user it stops and tries to connect to 172.16.79.134 instead of 72.16.79.130
