### ISSUE TITLE
HRM leave request - is not shown the correct approver

### ISSUE THREAD

**Issue by ffit2020** [Dolibarr/dolibarr#16934]
# Bug
[*Short description*]

## Environment
- **Version**: [13.0.1]
- **OS**: [ubuntu]
- **Web server**: [apache]

## Expected and actual behavior
if I add a supervisor to a user, the user will not find this supervisor in the approver dropdown menu
I tried to edit and choose anothe supervisot, but are always shown others
I have also added a supervisor ad admin, nothing, he is not shown in the user approver dropdown

## [Attached files](
![approver issue](https://user-images.githubusercontent.com/73834929/111974818-2a3f8980-8b00-11eb-8e8b-733761a737bb.JPG)
https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hi,

https://www.dolibarr.org/forum/t/leave-request-approver-not-shown-in-dropdown/20426/2
