### ISSUE TITLE
members - nature of members  is not considered

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#16944]
# Instructions

   I have one members type with set nature of members only for physical.

# Bug

   If i create / edit a member for this member type i can always select moral type.

## Environment

Dolibarr 12 & Dolibarr 13

**Comment by daraelmin** [comment]
Not sure how to implemant this.
If we force nature by adherent type, what's the expected workflow?

Does the adherent change his nature when we change his type ? It seems strange, so adherent type should not be selectable for adherent if there nature is not the right one... But when creating adherent the adh type and the nature are mandatory. 

So whats the prority ? Is the nature forced by the type or the type forced by nature ?

I was thinking of something like that:
1) for creation : nature must be selected before adh type
2) for update : nature can not be changed inside an adh type witch nature is forced. But can change to an other type, witch accept both nature to change his nature...

But then I ask my self "but when and why should someone change the nature of an adherent ?"
... 

May be the solution is just to remove nature from update. 

What do you think ?
