### ISSUE TITLE
Error Upgrade Dolibarr 11.0.4 to Dolibarr 12.0.4

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#16957]
#Instruction 

Upgrade Dolibarr 11.0.4 to Dolibarr 12.0.4

LAMP-System

Update Start Page:
Ok PHP-Version 7.4.16 (Weitere Informationen)
Ok Ihre PHP-Konfiguration unterstützt GET- und POST-Variablen.
Ok Ihre PHP-Konfiguration unterstützt Sessions.
Ok Ihre PHP-Konfiguration unterstützt GD-gestütze Funktionen zur dynamischen Erzeugung und Manipulation von Grafiken.
Ok Ihre PHP-Konfiguration unterstützt cURL.
Ok Ihre PHP-Konfiguration unterstützt die Kalender-Erweiterungen.
Ok Ihre PHP-Konfiguration unterstützt die UTF8-Funktionen.
Ok Ihre PHP-Konfiguration unterstützt die Internationalisierungs-Funktionen.
Ok Dieses PHP unterstützt ZIP-Funktionen.
Ok Die Sitzungsspeicherbegrenzung ihrer PHP-Konfiguration steht auf 512M. Dies sollte ausreichend sein.
Ok Die Konfigurationsdatei htdocs/conf/conf.php ist vorhanden.
Ok Die Konfigurationsdatei htdocs/conf/conf.php ist beschreibbar.

Letzte Versionsaktualisierung: 11.0.4 - Programmversion: 12.0.4

=> translated EN:

Ok PHP version 7.4.16 ( More information )
Ok Your PHP configuration supports GET and POST variables.
Ok Your PHP configuration supports sessions.
Ok Your PHP configuration supports GD-supported functions for the dynamic generation and manipulation of graphics.
Ok Your PHP configuration supports cURL.
Ok Your PHP configuration supports the calendar extensions.
Ok Your PHP configuration supports the UTF8 functions.
Ok Your PHP configuration supports the internationalization functions.
Ok This PHP supports ZIP functions.
OkThe session PHP configuration is memory limit of your 512M . This should be sufficient.
OkThe configuration file htdocs / conf / conf.php is available.
OkThe configuration file htdocs / conf / conf.php is writable.

Last version : version update 11.0.4 - Program : 12.0.4

#Bug  / #Error 

on second page -> Database migration Script:

...
  DB_ERROR_1296: ALTER TABLE llx_product ADD COLUMN accountancy_code_buy_export varchar(32) AFTER accountancy_code_buy_intra;
Got error 64 'Temp file write failure' from InnoDB

...

**Comment by ksar-ksar** [comment]
Hi,

This error is usually due to the tmpdir set for MySQL/MariaDB is running out of space. 

Not a dolibarr bug

**Comment by dolibit-ut** [comment]
Okay. Good to know. Thank you.
