### ISSUE TITLE
Attached file on mail, again ...

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#16952]
# Bug
Joint files with mails doesn't work.

## Environment
- **Version**: 13.0.2
- **OS**: debian
- **Web server**: apache2
- **PHP**: 7.3
- **Database**: mariadb 

## Expected and actual behavior
HTTP 500 when a file is joint.

## Steps to reproduce the behavior
On a thirdparty. Send a mail with a file attached. HTTP500

`[Wed Mar 24 11:26:32.813384 2021] [php7:error] [pid 15877] [client 86.253.107.4:61872] PHP Fatal error:  Uncaught Swift_IoException: The path cannot be empty in /var/www/html/erp.service-informatique.fr/htdocs/includes/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:45\nStack trace:\n#0 /var/www/html/erp.service-informatique.fr/htdocs/includes/swiftmailer/lib/classes/Swift/Attachment.php(53): Swift_ByteStream_FileByteStream->__construct('')\n#1 /var/www/html/erp.service-informatique.fr/htdocs/core/class/CMailFile.class.php(542): Swift_Attachment::fromPath('', 'application/pdf')\n#2 /var/www/html/erp.service-informatique.fr/htdocs/core/actions_sendmails.inc.php(409): CMailFile->__construct('Message pour la...', 'MATTHIEU VIGUIE...', 'Service Informa...', '<html><head><ti...', Array, Array, Array, '', 'fmerpsi@service...', '0', -1, '', '', 'thi10376', '', 'standard')\n#3 /var/www/html/erp.service-informatique.fr/htdocs/societe/card.php(890): include('/var/www/html/e...')\n#4 {main}\n  thrown in /var/www/html/erp.service-informatique.fr/htdocs/includes/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php on line 45, referer: https://erp.service-informatique.fr/societe/card.php?id=10376`

The image show a strange line with a null filename.
![Capture](https://user-images.githubusercontent.com/2384485/112299876-8b9a6080-8c98-11eb-987f-a59f65490820.PNG)

**Comment by matDOTviguier** [comment]
This problem doesn't occurds in propal/card.php
But seems to be only related with societe/card.php

**Comment by matDOTviguier** [comment]
ticket/card.php cannot send any attached file.

**Comment by xbloq** [comment]
I had that problem, not now https://github.com/Dolibarr/dolibarr/commit/8f6f8248a3e1c72a5cecc55d48830b777f4a7b2b
https://github.com/Dolibarr/dolibarr/issues/16767

**Comment by matDOTviguier** [comment]
only from societe/card.php ?

**Comment by daraelmin** [comment]
@matDOTviguier 
Try the patch. The bug was located on the mailing function called by formmai.class.php.
If you still face problem, please tell me if you have a mailmodel for société/card.php . I'm not sure that temp file can be remove without.

**Comment by matDOTviguier** [comment]
@daraelmin , I'm at 13.0.2. The patch doesn't affect formmail.class.php
Line patched **is already the same** as in the patch.
Changelog thus explicitly says _FIX: #16420 #16423 #16488 #16477_
I have a mailmodel for societe/card.php, yes.

**Comment by daraelmin** [comment]
@matDOTviguier 

As xbloq mentionned it I have submitted a new fixed here #16767 

It will be published in 13.0.3 but you can update the line 385 formmail.class.php 

If you use mailmodel on societe/card.php this one will hopefully solve your issue.

Cheers

**Comment by matDOTviguier** [comment]
OK, now I have my eyes open, it' works.
Guilty !
