### ISSUE TITLE
Request ODT Tags for HS Codes and a separate field in Invoice and Quotes

### ISSUE THREAD

**Issue by hussain-attari** [Dolibarr/dolibarr#16961]
Hi,

Can you create a dedicated field for Customs Code [HSN].

It is now going to become mandatory in India for the HSN to be mentioned on all invoices.

I use the free entry product option while creating my quotes and invoices as I deal in a lot of custom made products I am unable create a product for each of them.

Another benefit of creating this column is that it will ensure that the HSN Code for product is mentioned in all the necessary documents and will avoid unnecessary omissions while creating the documents.

A line tag for ODT will also be required column creation and insertion at individual product level in custom ODT Formats

Regards
Hussain

**Comment by hussain-attari** [comment]
#7479

**Comment by hussain-attari** [comment]
Currently add this as a complimentary attribute [lines] however would appreciate if this is built in Dolibarr framework.

**Comment by hussain-attari** [comment]
Can we control the location of the Complimentary attribute? How do I make it show between Tax and Unit Price in the Dolibarr backend?

**Comment by avinashlondhe** [comment]
I agree we can HSN code, but could not generate the HSN/SAC invoice summary
Details as follows:
https://cleartax.in/s/guide-to-gstr1-filing#hsn
