### ISSUE TITLE
code check \admin\agenda.php

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#16963]
htdocs\admin\agenda.php

code lines 180-181:

if ($trigger['code'] == 'FICHINTER_CLASSIFY_BILLED' && empty($conf->global->FICHINTER_CLASSIFY_BILLED)) continue;
if ($trigger['code'] == 'FICHINTER_CLASSIFY_**UNBILLED**' && empty($conf->global->FICHINTER_CLASSIFY_**BILLED**)) continue;

question:
I am just unsure if this is really correct at second line.

**Comment by eldy** [comment]
This looks good to me. There is 2 different triggers but only 1 setup optionFICHINTER_CLASSIFY_BILLED
