### ISSUE TITLE
option to preset members nature

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#16972]
# Feature Request

A new option (variable) to preset the nature of member.

**Comment by daraelmin** [comment]
Duplicate of #16944 ?
Or are you requiring two different things ?

**Comment by dolibit-ut** [comment]
Thank you for asking!
This is really almost the same.

(But also a little bit different:  #16944  is a bug - this is a feature request - but in the end   :-) )

**Comment by daraelmin** [comment]
It is be possible on new public form to force nature of all new member. With this PR #17527 the option will be visible in public form setup.

Is that what your expecting ?

Or do you want a preset for all new member ?
