### ISSUE TITLE
Bug: Wrong value for parameter 

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#16985]
# Bug
Wrong value for parameter 2 when adding third-party contact into the vendor quote.

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache/2.4.46 (Unix) OpenSSL/1.1.1d
- **PHP**: fpm-fcgi 7.4.15
- **Database**:  8.0.23
- **URL(s)**: /supplier_proposal/contact.php?id=145

[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/112714539-bf35ee80-8f15-11eb-8498-b48958df8c5f.PNG)

**Comment by daraelmin** [comment]
i have a similar issue when creating new member.

**Comment by daraelmin** [comment]
> i have a similar issue when creating new member.

My issue was linked to an external module

**Comment by asolslk** [comment]
This was left out in 13.0.3 version
