### ISSUE TITLE
Migrate Phones and emails into separate db tables for members, thirdparties, socpeople and users

### ISSUE THREAD

**Issue by frederic34** [Dolibarr/dolibarr#16989]
I propose to use separate fb tables to store multiple emails and phones numbers

**Comment by frederic34** [comment]
tables https://github.com/Dolibarr/dolibarr/pull/16987

**Comment by daraelmin** [comment]
Wouldn't it be more coherent to remove the redundant columns across the member / company / employee / user / contact / etc tables to group them into one (legal_entitey) which all the modules would refer to?

A single table with a single extrafield per legal entity
the management of name, email and telephone changes would thus be facilitated by centralization as well as searches.

When someone gets married, their name must be changed and checked in 3 to 6 tables ... same for a move, a change of operator or email address

recent example:
One member changed her name after her marriage. we changed the name in adherent first ... But the thirdparty (client) hasn't be affected. we have therefore been modifying the name in the thirdparty... the operation causes a synchro and has modify ... the name of the company which employs our member ... Etc.
