### ISSUE TITLE
Thirdparties no search result

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#16994]
# Bug
In Thirdparties, searching for any Thirdparty does not show any result. In List view, it shows the customer.
Tried search for Name, Town or Postcode does not work.

If you create an Invoice, you can find the same Customer without problem.

Dolibarr 14 (development) checked out today (29. March 2021) but the problem persists since a few weeks.

**Comment by mwelters** [comment]
Investigating deeper:
Some recently touched Customers are findable - some old Customers are not findable. 
Comparing records in societe does not show visible difference.

**Comment by dolibit-ut** [comment]
Have you checked the database records?
Have you tried run repair.php?

**Comment by mwelters** [comment]
> Have you checked the database records?
> Have you tried run repair.php?

Yes, checked Database records, did not find difference in societe between shown and not-shown records. Must be in another table.
re-run repair (but did not find matching task)
No clue what might cause it in the records

**Comment by daraelmin** [comment]
I have same issue.

**Comment by mwelters** [comment]
What should I search for ?
I am sure there is a regression with my old data, which travels for years with Dolibarr.

Shall I install new dolibarr database and compare table definitions to find the difference ?

**Comment by daraelmin** [comment]
I dont know.
I have migrate twice my 13.0.2 on wich everything is okay but it doesnt work on develop.

I don't know what had happen. My first suspect was these commit:

https://github.com/Dolibarr/dolibarr/commit/bee08492909488a71a07a9b268fe708f6e2cdad7#diff-3200abafd809689603416752f05135b36ca1d3a23237ffa62d4035d3da54dd12

https://github.com/Dolibarr/dolibarr/commit/b1a78c6c18829e63eeb3c1c0e9b62481c3b7c03a#diff-3200abafd809689603416752f05135b36ca1d3a23237ffa62d4035d3da54dd12

https://github.com/Dolibarr/dolibarr/commit/20aa1e29f60c166050d1d95f73a4369137ae14aa#diff-3200abafd809689603416752f05135b36ca1d3a23237ffa62d4035d3da54dd12

But I dont have time to test.

**Comment by daraelmin** [comment]
This one :

20aa1e2

is my favorite as it modify the sql query to show a new field

**Comment by mwelters** [comment]
I edited one Customer who was not findable. Only added a salesrepresentative (was empty), saved and the Customer can be found again.

Comparing the data in the record I noticed changes:
code_client  NULL   -->   CU2103-00199
code_compta NULL --> 411CU210300199
socialnetworks NULL   -->  []     (some strange utf8 character)
fk_effectiv  3  --> 0
siren, siret, ape, idprof4, idprof5, idprof6   " " --> NULL            (from empty to NULL)
fk_prospectlevel " " --> NULL
fk_incoterms 0 --> NULL
fk_user_modif   1  --> NULL
localtax1_assuj  NULL --> 0
localtax1_value  0.000  --> NULL
localtax2_assuj  NULL --> 0
localtax2_value  0.000  --> NULL
Accountancy_code_sell " " --> NULL
Accountancy_code_buy " " --> NULL
model_pdf " " --> NULL
multicurrency_code " " --> NULL
Setting some fields to the new "defaults" did not help. 

So - setting one or more salesrepresentatives makes the thirdparty findable.
I think it is a problem in the Rights-System. The logged in User I used is Admin. Will investigate further tomorrow...

**Comment by daraelmin** [comment]
I've tried something : 

I have copy paste the query from the search on 13.0.2 in the bdd of 14.0.0 alpha...

It works. 

I havent already identify all differences between the two queries, but the new one has more "left join" and there's something new about the commercial and their picto.

**Comment by daraelmin** [comment]
Here are the both part of the queries witch are different.

V13
LEFT JOIN llx_c_stcomm as st ON s.fk_stcomm = st.id 
WHERE s.entity IN (1) 
AND (s.fournisseur <> 1 OR s.client <> 0)
AND (s.nom LIKE '%soc%') 
AND (s.status IN (1)
) 
ORDER BY s.nom ASC LIMIT 26 

V14
LEFT JOIN llx_categorie_societe as cc ON s.rowid = cc.fk_soc 
LEFT JOIN llx_categorie_fournisseur as cs ON s.rowid = cs.fk_soc 
LEFT JOIN llx_c_stcomm as st ON s.fk_stcomm = st.id
, llx_societe_commerciaux as sc 
WHERE s.entity IN (1) 
AND s.rowid = sc.fk_soc 
AND (s.nom LIKE '%soc%') 
AND (s.status IN (1)
) 
ORDER BY s.nom ASC

**Comment by daraelmin** [comment]
Ok I've found the problem:

llx_societe_commerciaux should be "left joined" and not directly added in from.

LEFT JOIN llx_societe_commerciaux as sc ON s.rowid = sc.fk_soc

**Comment by daraelmin** [comment]
,@mwelters I think the last commit have solved the problem so you may close this thread

**Comment by mwelters** [comment]
@daraelmin 
Yes, thank you. The Problem is solved !
