### ISSUE TITLE
EMailing module setup How to add multiple email accounts

### ISSUE THREAD

**Issue by shi2yue1hao** [Dolibarr/dolibarr#17016]
![Snipaste_2021-03-30_11-41-29](https://user-images.githubusercontent.com/80890679/112944972-3661c180-9166-11eb-9a45-29d9db2ff5ce.jpg)

EMailing module setup How to add multiple email accounts? At present, the value here can only fill in one mailbox.

![Snipaste_2021-03-30_11-43-35](https://user-images.githubusercontent.com/80890679/112944984-38c41b80-9166-11eb-8b9f-7dda6c4acbe5.jpg)

The function I want is to use the purchase mailbox when sending the purchase order and the sales mailbox when sending the sales order.

How should it be configured, or is it impossible to realize this function at present?

**Comment by atm-maxime** [comment]
I suggest you to ask about it on forums first. Here on github we are dealing with feature request and bug issues. What you ask is if the function exists. Ask it on forums and if you find out that the function does not exists, then you can create a feature request for adding the function.
