### ISSUE TITLE
Unable to attach a contract to an invoice.

### ISSUE THREAD

**Issue by theyro** [Dolibarr/dolibarr#17026]
# Bug
The "attach" link in invoice page dont show the list of contract

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apapche
- **PHP**: 7.3.27
- **Database**: MySQL
- **URL(s)**: [*Affected URL(s)*]

## Steps to reproduce the behavior
I have 3 contracts for a customer (1 active and 2 inactives). 
When I create a new invoice for this customer, I click on th link to attach a contract. I see only one contract and this is the first (who is inactive!)
Before the upgrade of Dolibarr, the click on the attach link see a list of contract. 

![image](https://user-images.githubusercontent.com/62514322/113009948-b98c1300-9178-11eb-961b-46414ce77afb.png)

**Comment by daraelmin** [comment]
Duplicate #16767 and #16952

try this patch #16885

**Comment by eldy** [comment]
Are you sure your 3 contracts are on the same third party ?

**Comment by theyro** [comment]
Yes. Sure. 

Le 2 avril 2021 22:26:46 GMT+02:00, Laurent Destailleur ***@***.***> a écrit :
>Are you sure your 3 contracts are on the same third party ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Dolibarr/dolibarr/issues/17026#issuecomment-812697694

-

**Comment by xbloq** [comment]
I have this warning  I don't know if  it's related

Warning: Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/html/dolibarr/htdocs/core/class/html.form.class.php on line 7210

**Comment by daraelmin** [comment]
> I have this warning  I don't know if  it's related
> 
> Warning: Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in /var/www/html/dolibarr/htdocs/core/class/html.form.class.php on line 7210
> 

@xbloq this is related to #17066 and should be fixed with #17068

**Comment by xbloq** [comment]
Thanks it's ok now

**Comment by theyro** [comment]
Same problem with the patch. 
![image](https://user-images.githubusercontent.com/62514322/115680079-8857ca80-a353-11eb-9751-098a60b832d8.png)

I have only one contract in the list (The first one, which is closed)
I normally have 3 contracts for this customer (2 closed and 1 active) 

The problem is not linked to the customer; Same problem on each one
