### ISSUE TITLE
Table `actioncomm` : action type mismatch `fk_action` and `code`

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#17033]
# Bug
In `actioncomm` table, the field `fk_action` give the real action type. The field `code` (table : `actioncomm`) can be different (value at event initialization, does not change after update).

## Environment
- **Version**: Dolibarr v. 10.0.7
- **Database**: MySQL

**Comment by ksar-ksar** [comment]
Hi,

Not clear for me, can you explain what is the issue ?

**Comment by vvnt** [comment]
It does not afect user. Is it visible only in the database.

Let's create an action - a phone call 

![dolibarr_action_before_type_update](https://user-images.githubusercontent.com/5360027/113413832-d7958580-93bb-11eb-94c0-1f37868bce0f.png)

Below the record in the database : 

![action_before_type_update](https://user-images.githubusercontent.com/5360027/113413866-eaa85580-93bb-11eb-9bbf-adbac8433ff7.png)

For a phone call : `fk_action` = 1 and `code` = AC_TEL 👍 

However, if you change your mind and want to change the action type from **phone call** to **meeting** : 

![dolibarr_action_after_type_update](https://user-images.githubusercontent.com/5360027/113414065-5e4a6280-93bc-11eb-8226-8e7fce536097.png)

It is working well in the user interface, however in the database the field `code` seems useless.

![action_after_type_update](https://user-images.githubusercontent.com/5360027/113414116-833ed580-93bc-11eb-9f0a-ad87df8b186f.png)

**After update : `fk_action` = 5 👍  and `code` keeps the value AC_TEL 👎  **
