### ISSUE TITLE
Agenda Month Calendar view showing up day before actual event

### ISSUE THREAD

**Issue by GreenEyeCoder** [Dolibarr/dolibarr#17040]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Agenda Month Calendar view showing up day before actual event

## Environment
- **Version**: 13.0.1

cPanel Version | 86.0 (build 38)
Apache Version | 2.4.46
PHP Version | 7.3.27
MySQL Version | 5.6.41-84.1
Architecture | x86_64
Operating System | linux
Path to Perl | /usr/bin/perl
Perl Version | 5.10.1
Kernel Version | 4.14.146-225.ELK.el6.x86_64
- **URL(s)**:https://greeneyecoder.com

## Expected and actual behavior
The events showing up on the correct date.

## Steps to reproduce the behavior
Just add an event

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![bug](https://user-images.githubusercontent.com/55360086/113032570-d870b200-9144-11eb-88a5-2679534b6171.png)

[*Files*]

**Comment by ksar-ksar** [comment]
There where some issues on that that has been corrected in V13.0.2.
Could you try the upgrade ?

Also check the timezone definition on PHP configuration.

**Comment by leninrivas** [comment]
Seems fixed with PR #17190 and  #17192
