### ISSUE TITLE
Bug: Error facture List external user's

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#17055]
# Bug
Módulos: user, workflow, multicurrency, bookmark, import, projet, propal, servcomfac, expedition, servcomguiar, contrat, ficheinter, numberseries, tax, stock, productbatch, loan, banque, margin, tawkto, product, bom, mrp, notification, fckeditor, export, accounting, agenda, cron, commande, expensereport, facture, fournisseur, opensurvey, resource, salaries, societe, service, ticket, categorie, variants
Tipo de gestor de base de datos: mysqli
Último error en solicitud de acceso de base de datos: SELECT u.rowid, u.lastname, u.firstname, u.statut as status, u.login, u.photo, u.gender, u.entity, u.admin FROM llxod_user as u WHERE u.entity IN (0,1) AND u.rowid = 16 AND u.fk_soc = 274 UNION SELECT u2.rowid, u2.lastname, u2.firstname, u2.statut as status, u2.login, u2.photo, u2.gender, u2.entity, u2.admin FROM llxod_user as u2, llxod_societe_commerciaux as sc WHERE u2.entity IN (0,1) AND u2.rowid = sc.fk_user AND sc.fk_soc=274 ORDER BY statut DESC, lastname ASC
Código de retorno de error para la última petición de acceso a la base de datos: DB_ERROR_NOSUCHFIELD
Información del último error de petición de acceso de base de datos: Unknown column 'statut' in 'order clause'

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /compta/facture/list.php?leftmenu=customers_bills

![Facturas a clientes](https://user-images.githubusercontent.com/53640168/113088500-5071c300-91ab-11eb-8b0f-d1b16a223b24.jpg)

**Comment by ksar-ksar** [comment]
Hello,

Work for me.

Strange that you do not have a 'statut' field on your llx_user table.
Could you check the structure of the llx_user table ?

**Comment by leninrivas** [comment]
> Hello,
> 
> Work for me.
> 
> Strange that you do not have a 'statut' field on your llx_user table.
> Could you check the structure of the llx_user table ?

Hi.
with permises only facture and pay?.
Thas problem only is external user with only permises facture and pay.

**Comment by dom-breizh** [comment]
Hi,

I just encountered the same issue.

##Bug

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20210927114111
Dolibarr: 13.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.4.3
Server: Apache/2.4.41 (Ubuntu)
OS: Linux greenbee 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 OPR/79.0.4143.50

Url sollicitée: /compta/facture/list.php?leftmenu=customers_bills
Referer: https://dolitest.greenbee.eu/compta/index.php?mainmenu=billing&leftmenu=
Gestionnaire de menu: eldy_menu.php

Modules/Applications: twofactorauth, user, api, expedition, supplier_proposal, tax, loan, margin, product, banque, stock, projet, fckeditor, socialnetworks, categorie, webservices, mailing, productbatch, bom, mrp, multicurrency, import, dav, notification, incoterm, cdav, export, propal, accounting, agenda, barcode, commande, ecm, externalsite, expensereport, facture, fournisseur, printing, salaries, societe, service, ticket, variants, abricot, subtotal, deliveryaddress, autoattachfile, sendinblue, splash, cyberoffice
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT u.rowid, u.lastname, u.firstname, u.statut as status, u.login, u.photo, u.gender, u.entity, u.admin FROM llx_user as u WHERE u.entity IN (0,1) AND u.rowid = 11 AND u.fk_soc = 1082 UNION SELECT u2.rowid, u2.lastname, u2.firstname, u2.statut as status, u2.login, u2.photo, u2.gender, u2.entity, u2.admin FROM llx_user as u2, llx_societe_commerciaux as sc WHERE u2.entity IN (0,1) AND u2.rowid = sc.fk_user AND sc.fk_soc=1082 ORDER BY statut DESC, lastname ASC
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'statut' in 'order clause'

## Environment
- **Version**: 13.02
- **OS**: Ubuntu Server LTS 20.04.3
- **Web server**: Apache 2.4
- **PHP**: PHP 7.4.3
- **Database**: MySQL 8.0.26
- **URL(s)**: /compta/facture/list.php?leftmenu=customers_bills

## Expected and actual behavior
Connect as external user, navigate to the Invoices tab, then choose list.
Expected: get a normal list page
Results: Error as described above.

## Steps to reproduce the behavior
Add external access to existing customer. Define access rights. Conect and get the error.

## Additional info:
I tried the SQL code directly against the MySQL server with the same results:

SELECT u.rowid, u.lastname, u.firstname, u.statut as status, u.login, u.photo, u.gender, u.entity, u.admin 
FROM llx_user as u 
WHERE u.entity IN (0,1) AND u.rowid = 11 AND u.fk_soc = 1082 
UNION 
SELECT u2.rowid, u2.lastname, u2.firstname, u2.statut as status, u2.login, u2.photo, u2.gender, u2.entity, u2.admin 
FROM llx_user as u2, llx_societe_commerciaux as sc 
WHERE u2.entity IN (0,1) AND u2.rowid = sc.fk_user AND sc.fk_soc=1082 
ORDER BY statut DESC, lastname ASC

SQL Error [1054] [42S22]: Unknown column 'statut' in 'order clause'

I changed the 'statut' reference in the ORDER clause by 'status' and it works (at least in SQL). Just have to locate the PHP page to make the change and test it with Dolibarr.

**Comment by dom-breizh** [comment]
I just check v14.0.2 and it works properly. Can someone confirm in what version of Dolibarr it was fixed ?
Thanks.

**Comment by ksar-ksar** [comment]
Hello,

The error is here : https://github.com/Dolibarr/dolibarr/blob/13.0.2/htdocs/core/class/html.formother.class.php#L477

It has been fixed by https://github.com/Dolibarr/dolibarr/commit/6ba878725e4a25d27e4a94da3d5e7865627d601b  On V13.0.3

So just update.

**Comment by dom-breizh** [comment]
Thanks, just found it in my install. I'll update to the last of 13.x versions
