### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by r9guy** [Dolibarr/dolibarr#17064]
# Bug
Right after installation v12 I receive an error, upon first login.

> Dolibarr has detected a technical error.
> This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
> Date: 20210401100517
> Dolibarr: 12.0.5 - https://www.dolibarr.org
> Level of features: 0
> PHP: 8.0.0
> Server: Microsoft-IIS/10.0
> OS: Windows NT ARSHAMA-NB02 10.0 build 19042 (Windows 10) AMD64
> UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
> 
> Requested URL: /index.php?mainmenu=home
> Referer: http://localhost/index.php
> Menu manager:
> 
> Modules/Applications: user
> Database type manager: mysqli
> Latest database access request error: No request in error
> Return code for latest database access request error: No request in error
> Information for latest database access request error: No request in error
> 
> Message: Error in some triggers USER_LOGIN or in some hooks afterLogin

## Environment
- **Version**: 12
- **OS**: Windows 10
- **Web server**: IIS
- **PHP**: 8
- **Database**: MySQL 8
- **URL(s)**: localhost

**Comment by ksar-ksar** [comment]
Hello,

PHP V8 is not supported by Dolibarr V12 or V13.
Need to downgrade PHP to V7.4 MAX

https://wiki.dolibarr.org/index.php/Releases
