### ISSUE TITLE
PB/BUG order status

### ISSUE THREAD

**Issue by pyr74** [Dolibarr/dolibarr#17067]
# Bug
We recently migrated from version 11.0.3 to version 13.0.2.
With version 11, when we created a Delivery (Shipping) from an Order, the order changed from the “Validated” state to “In progress” and the Shipping was in the “Validated” state (products to be sent or sent ) "
With version 13, during the same operation, the order goes directly to the "Delivered" state, the Shipping is indeed in the "Validated (products to be sent or sent)" state

## Environment
- 13.0.2
- UBUNTU Server 18.04.5
- Apache 2.4.29
- PHP 7.2.24
- MySQL 5.7.33

**Comment by pyr74** [comment]
I revive the subject ...
Will my request be taken into account?

**Comment by jocker132** [comment]
I have the same behavior you described above on version 12.0.5.
In this case on which even you want the order to turn to delivered instead of In process since there is not Mark as delivered button in shipment screen.

**Comment by atm-maxime** [comment]
This is standard behavior. The order stays "in progress" if you haven't shipped all of its lines. Otherwise it goes directly to the shipped status

**Comment by atm-maxime** [comment]
And for further help on how to use Dolibarr, you can seek informations on the wiki and on forums

**Comment by ibuiv** [comment]
Ok it seems ...
