### ISSUE TITLE
PHP Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in \core\class\html.form.class.php on line 7210

### ISSUE THREAD

**Issue by Bagu** [Dolibarr/dolibarr#17066]
# Bug
In error log, i see this error PHP Warning:  Use of undefined constant label - assumed 'label' (this will throw an Error in a future version of PHP) in \core\class\html.form.class.php on line 7210
I don't know what is the origin of this error so i can't tell how to reproduce.

## Environment
- **Version**: Dolibarr 13.0.2
- **OS**: Windows 10 64 bits
- **Web server**: Apache 2.4.46 64 bits
- **PHP**: php 7.4.16 64 bits
- **Database**: mariadb 10.5.9 64 bits
- **URL(s)**: Unknwown

**Comment by daraelmin** [comment]
Maybe this PR #17068 should solve this

**Comment by Bagu** [comment]
Thanks, i will try it.

**Comment by eldy** [comment]
Yes, should be fixed with #17068
