### ISSUE TITLE
REST API : supplierorders put method fails in security checks

### ISSUE THREAD

**Issue by guiguichupote** [Dolibarr/dolibarr#17060]
# Bug
When sending put request on supplierorder, the methode calls 
DolibarrApi::_checkAccessToResource('fournisseur', $this->order->id, '', 'commande')
The problem is that 'fournisseur' table does not exists in database ( the real table to check seems to be commande_fournisseur)
The security checks fails and it is not possible to put supplierorder.

**Comment by ksar-ksar** [comment]
Hi,

Can you check if the above FIX solve the issue ?

Thanks.

**Comment by guiguichupote** [comment]
Yes it is.
I did same fix locally but had no time to share.
Thanks
