### ISSUE TITLE
Bug: Error of price on defined product selection in supliers orders

### ISSUE THREAD

**Issue by mperaya** [Dolibarr/dolibarr#17115]
I am a Spanish guy. We use ',' for decimals and '.' for thousands.
If I select a product from popup for add a new line to a vendor proposal or purchase order, the stored price is shown as 99,99 in popup, but is added as 99.99 to the new line and then all calcs are wrong.

If I do the same for a sales order, commercial proposal, customer invoice or vendor invoice, all works right and the prices are added in spanish numeric style.

My dolibarr version is 13.0.2

**Comment by cfoellmann** [comment]
we also have big issues with prices. 
Dolibarr 14.x & develop 15-beta

I identified the following:

Defined product with a supplier price where the price has __3__ decimal digits!! Resulting in a price 1000x as high as it should be.
Example:

Product: 1 piece = 1.323 (€) [1 Euro and 32,3 cents]
Line added: 100 pieces => Result: 132.300 € [132 thousand and 300 Euros]

this only occurs with exactly 3 decimal digits. not with 2, 4 or more!
