### ISSUE TITLE
Bug white background in dark mode

### ISSUE THREAD

**Issue by daraelmin** [Dolibarr/dolibarr#17116]
# Bug white background in dark mode
When the display doesn not require the entire height of the screen, the empty zone is filled with white.

![IMG_20210405_101413.jpg](https://user-images.githubusercontent.com/8067223/113553380-fda76980-95f7-11eb-8f82-83858d0e3a54.jpg)

**Comment by eldy** [comment]
Some enhancement on dark mode will be available into  v14 (still experimental)

**Comment by daraelmin** [comment]
Cool !

**Comment by daraelmin** [comment]
> Some enhancement on dark mode will be available into  v14 (still experimental)

Fixed
