### ISSUE TITLE
Bug: Captcha on v13.0.2 : impossible to log on

### ISSUE THREAD

**Issue by DoliFRAP67** [Dolibarr/dolibarr#17120]
# Bug
Impossible to log on with active captcha on v13.0.2

## Environment
- **Version**: 13.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) PHP/7.3.12
- **PHP**: apache2handler 7.3.12
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB
- **URL(s)**: /dolibarr/admin/security_other.php

## Expected and actual behavior
With googd information : system had to logon, with captcha ; refuse logon and cancel login values and tell "wrong information entered"

## Steps to reproduce the behavior
This has produced after enabling Captcha in Setup/security/others

## Report
Impossible to log on with a computer.
I have try to log with : Edge, Chrome, Firefox = Error
I managed to pass the captcha by connecting with the server url on my smartphone. 
(P20lite, Android 9, Google Chrome)

Is ther any update for captcha module?

**Comment by ksar-ksar** [comment]
Hello,

Work for me on Edge, Chrome and Firefox.
Could you have a look on log files ?

**Comment by hasse-basse** [comment]
For information, I use CAPTCHA on 13.0.2 and  I have no problems on Edge and Chrome. Havn't tried on the others.
