### ISSUE TITLE
Form Styler

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#17134]
Hi
I have download de zip file of formstyler to dolibarr directory and unzip, but doesn't apear in my dolibarr
What can i do?
Thanks

**Comment by atm-maxime** [comment]
Hi. Did you read the comments on your previous issue #16540 ? You have online forums available to ask your questions. The subject of this new issue is not a bug nor a feature request, so it doesn't belong here on GitHub.
Thanks.
