### ISSUE TITLE
ProductsEasyAccess  Model c408d20151116180114 

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#17132]
Hi
How can i instal "ProductsEasyAccess

Model c408d20151116180114 " in my dolibarr?
Thank's

**Comment by atm-maxime** [comment]
Hi. Did you read the comments on your previous issue #16540 ? You have online forums available to ask your questions. The subject of this new issue is not a bug nor a feature request, so it doesn't belong here on GitHub.
Thanks.
