### ISSUE TITLE
Product Variant Value drop down not populated

### ISSUE THREAD

**Issue by ed1023** [Dolibarr/dolibarr#17181]
# Bug
*Product Variant Value drop down not populated*

## Environment
- **Version**: 13.0.2
- **OS**: Debian 10
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.27-1~deb10u1
- **Database**: PostgreSQL 11.11
- **URL(s)**: dolibarr/variants/combinations.php

## Expected and actual behavior
After clicking on a product in the product list and selecting variants and selecting the variant Size in the "Variant attribute" drop down I expect that the value drop down would be populated with values entered in the Variant attributes menu.

## Steps to reproduce the behavior
- I started off by going to dolibarr/variants/list.php and adding a SIZE variant with 6 options XL. L, M, S, XS, XXS
- Then I add a simple test product only filling out Ref and Label fields
- Then I select the product in the product list 
- I click on the Variants tab
- Then click on "New Variant"
- After selecting "Size" the value menu does not populate

**Comment by eldy** [comment]
Did you create first your variant into menu "Product - Attribute variants". Can you make a screenshot of this page

**Comment by eldy** [comment]
When you make "right -click" then "inspect" on chromr or firefox, do you see "javascript error" ?
Can you also paste the screenshot of page /variants/list.php

**Comment by ed1023** [comment]
There is an error in the console window It happens when i am in the product card and click on the new variant
url: dolibarr/variants/combinations.php?id=1&action=add
error: Uncaught SyntaxError: expected expression, got ';'  combinations.php:215:24
![product-add-variant](https://user-images.githubusercontent.com/4974624/114315379-5e391980-9ac4-11eb-9d17-bec3c59319d9.jpeg)

Other requested screenshots
variants-card
![variants-card](https://user-images.githubusercontent.com/4974624/114315358-406bb480-9ac4-11eb-8061-7ba50b4edfaf.jpeg)

variants-list
![variants-list](https://user-images.githubusercontent.com/4974624/114315359-41044b00-9ac4-11eb-99f8-b5a6c1b88bae.jpeg)

**Comment by xoddark** [comment]
Hello, I have the same problem.
I have the following error at page loading :
error: Uncaught SyntaxError: expected expression, got ';' combinations.php:215:24

And the corresponding javascript is : 
`			variants_available = ;
			variants_selected = {
				index: [],
				info: []
			};`

PS: I have to variant attributes, with several value for each.

**Comment by xoddark** [comment]
@eldy I have investigate (with limited php knowledge).
It's seems than the line : 
```php
variants_available = <?php echo json_encode($prodattr_alljson); ?>;
```
does not work as expected.
I have modified the foreach loop than fill $prodattr_alljson from this :
```php
                                $prodattr_alljson[$each->id] = $each;
``` 
to this :
```php
                                $prodattr_current = array();  
                                $prodattr_current['id'] = $each->id;
                                $prodattr_current['ref'] = $each->ref;
                                $prodattr_current['label'] = $each->label;
                                $prodattr_alljson[$each->id] = $prodattr_current;
```
With this change, the list box "Valeur" in page combinations.php change to "Loading..." when I select a "Attribut de variante". But nothing happen after.
I have no more ideas for investigation.

**Comment by ed1023** [comment]
I still see the same issue in v14

**Comment by ed1023** [comment]
Still seeing this same issue in v14.0.2

**Comment by N3miroff** [comment]
Hello,
I have exactly the same problem with 14.0.3 and 14.0.4 versions.
Regards

**Comment by poterieMadeleine** [comment]
Hello same problem in 14.0.5

**Comment by graillet** [comment]
Same here 14.0.5, PHP Version 7.4.27 the json_last_error() function throws 8 when json_encode($prodattr_alljson) is called, so it cannot serilize becouse of nulls, I changed to json_encode($prodattr_alljson, JSON_PARTIAL_OUTPUT_ON_ERROR); but now the problem, as others, is the endless "Loading...".

I will downgrade my PHP version becouse json_encode is used 262 times.

**Comment by graillet** [comment]
FIXED. So, I tested with other PHP versions but was still the same problem, I don't know why same 14.0.5 in the novafirstcloud instance is working fine with variants, the only diference that I have vs their instance is that I'm using postgresql and they are using mysql, but I decided not to change the DBMS, so what we need to do is to add the JSON_PARTIAL_OUTPUT_ON_ERROR in json_encode function calls (in combinations.php and get_attribute_values.php), this is becouse the objects to encode in json have null values and that's why the json_last_error() throws 8, sadly this function, as I said before, is used 262 in dolibarr, so maybe we need to change all that calls.

![image](https://user-images.githubusercontent.com/30445549/152089308-8b550403-a868-4b39-9369-7cb027636576.png)

![image](https://user-images.githubusercontent.com/30445549/152089363-d3c4b4c2-e3cb-4502-bb57-4529bc295aec.png)

**Comment by ed1023** [comment]
Hey @graillet thanks for the update will test on my setup, I spent a couple days trying to figure this out and was truly stumped.
Joel

**Comment by ed1023** [comment]
@graillet solution is tested working for me @eldy on my setup.

**Comment by N3miroff** [comment]
Dear All,
I've just install Dolibarr V15.0, unfortunately drop down non populated for variant remain in force...
Hope to have this solved soon on official release.
Best regards

**Comment by VoidScute** [comment]
Same issue for me on V15.0

**Comment by coding1wolf** [comment]
By adding JSON_PARTIAL_OUTPUT_ON_ERROR just as said a couple messages before, it starts working

**Comment by redcumbre-dsb** [comment]
> FIXED. So, I tested with other PHP versions but was still the same problem, I don't know why same 14.0.5 in the novafirstcloud instance is working fine with variants, the only diference that I have vs their instance is that I'm using postgresql and they are using mysql, but I decided not to change the DBMS, so what we need to do is to add the JSON_PARTIAL_OUTPUT_ON_ERROR in json_encode function calls (in combinations.php and get_attribute_values.php), this is becouse the objects to encode in json have null values and that's why the json_last_error() throws 8, sadly this function, as I said before, is used 262 in dolibarr, so maybe we need to change all that calls.
> 
> ![image](https://user-images.githubusercontent.com/30445549/152089308-8b550403-a868-4b39-9369-7cb027636576.png)
> 
> ![image](https://user-images.githubusercontent.com/30445549/152089363-d3c4b4c2-e3cb-4502-bb57-4529bc295aec.png)

Confirmed. its Work on 16.0.1

**Comment by seigakaku** [comment]
Found the same error on version 16.0.3
Adding JSON_PARTIAL_OUTPUT_ON_ERROR fixed it.
Thank you very much.
