### ISSUE TITLE
Bug: Agenda module, date offset in monthly view

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#17190]
# Bug
Agenda module, date offset in monthly view

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /comm/action/index.php?action=show_month&year=&month=&day=

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Falla de agenda](https://user-images.githubusercontent.com/53640168/114092655-c21ed080-987f-11eb-9f75-254bba251de6.jpg)

**Comment by eldy** [comment]
Seems fixed with PR #17192

**Comment by leninrivas** [comment]
> 
> 
> Seems fixed with PR #17192

Thanks, Tested Ok with 13.0.2
