### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ffit2020** [Dolibarr/dolibarr#17191]
# Bug
Language is not changed

## Environment
- **Version**: 13.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: apache2handler 7.0.33-0ubuntu0.16.04.16
- **Database**: MySQL or MariaDB 5.6.39-log
- **URL(s)**: /admin/index.php?mainmenu=home&leftmenu=setup

## Expected and actual behavior
I try changing language into English UK, or English USA, language instead stay Italian

## Steps to reproduce the behavior
Settings - location

**Comment by DH88UK** [comment]
I guess by 'Settings - location' you mean to say Setup -> Company Organisation -> Country ?

The user language is set elsewhere, Setup -> Display -> Default Language

![2021-04-11 08_22_01-Greenshot](https://user-images.githubusercontent.com/58177104/114295741-21a6f700-9a9f-11eb-9c94-3d9e3d607393.jpg)

**Comment by eldy** [comment]
This is to change the "default" language. But language may be forced on the user profile. Check also the tab "Display" on your user record.

**Comment by ffit2020** [comment]
> This is to change the "default" language. But language may be forced on the user profile. Check also the tab "Display" on your user record.

hi Eldy, yes now I have tried, but it stays English for a user, even if I change into italian her preferred language

And also if I put English into setup, etc, doesnt change language for all perople

could it be a browser setting? how to avoid this, or test if is a browser setting? is there a site where to test browser pages in different languages?
thanks

**Comment by ksar-ksar** [comment]
Hi,

Check in Admin Tools -> About Dolibarr 

![image](https://user-images.githubusercontent.com/35605507/114852636-3e1a9a80-9de3-11eb-8f2d-99be292c254c.png)

**Comment by ffit2020** [comment]
ok thanks, I will try editing it
