### ISSUE TITLE
Virtual Stock quantity is incorrect if a product is in Sales Order

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#17208]
# Bug
The virtual Stock quantity is incorrect if a product is in Sales Order

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache/2
- **PHP**: 7.3.27
- **Database**: 5.5.5-10.4.17-MariaDB
- **URL(s)**: /htdocs/product/stock/product.php?id=

## Expected and actual behavior
If Physical Stock is -8 units and there are 100 units ordered the virtual stock should show 92 units but actually is showing 84 units (2 x 8 =16)

## Steps to reproduce the behavior
Check virtual stock of the product which is included in Sales Order (if the product is not in the Sales Order then the Virtual Stock value is correct) and the value shown will be double the Sales Order

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![1](https://user-images.githubusercontent.com/28427270/114227519-02a84800-996d-11eb-9a60-4c9678c092a8.PNG)
![2](https://user-images.githubusercontent.com/28427270/114227516-020fb180-996d-11eb-8579-27f2bfdd72c9.PNG)

**Comment by toni-mx** [comment]
Something similar reported here https://github.com/Dolibarr/dolibarr/issues/16346
Maybe this can help identifying what's happening.

What i was able to understand it has to do with status of the sales order and/or the reception module. 
Somehow it counts what's received but if the sales order status is open or partially received it counts again and when you close or finish receiving all products it stop counting double.

I'll keep you posted

Thanks and Regards

**Comment by futurehousestore** [comment]
Thanks @Toni-RS I will close my issue now and add my data to issue #16346
