### ISSUE TITLE
Enabling Lot/batch number for a preexisting products leads to the creation of an unusable Lot/batch

### ISSUE THREAD

**Issue by elsp1991** [Dolibarr/dolibarr#17201]
# Bug
Enabling Lot/batch number for a preexisting products leads to the creation of an unusable Lot/batch number 00000. That when you click on it is not showing anything. I assume because its a conflicted Lot/batch number between many products.

## Environment
- **Version**: v 13.0.1
- **OS**: Linux apollon2 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64
- **Web server**:  Apache/2.4.29 (Ubuntu)
- **PHP**: 7.2.24-0ubuntu0
- **Database**: MySQL or MariaDB 5.5.5-10.1.47-MariaDB-0ubuntu0.18.04.1

## Expected and actual behavior
The Expected behavior is to create automatically a unique Lot/batch number (maybe using the ref of the product) to avoid conflicts.

## Steps to reproduce the behavior
- *Create 2 products with lot/batch disabled.*
- *Increase stock for both of them*
- *Go back to products and enable Lot/batch*
- *Go to stock of this products and observe that the previous stock has a lot/batch 00000 that is not usable*

**Comment by eldy** [comment]
This is the expected behaviour to have the lot/batch number to "00000" when you enable the module lot/batch after having entered a product in mode "not lot batch requested". All product with unknown lot/batch number are set to batch number "00000".
However, this lot/number should be usable like any other lot number.
What do you mean with "that is not usable".

**Comment by elsp1991** [comment]
Hello Laurent,

sorry for the incomplete description. The stock it is usable in terms of consuming it, but going through the product page to the lot/batch list and clicking the 00000 lot will return just a white blank page. Also since lot numbers they only suppose to correspond to one type of product i dont see how having the same 000000 for several products can work.
