### ISSUE TITLE
DOLIBARR : I would like to be able to permit new user to access his own warehouse only, not all the warehouses. 

### ISSUE THREAD

**Issue by RomainMenage** [Dolibarr/dolibarr#17200]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request
When creating a new user in Dolibarr, I would like to permit him to access his own warehouse only, while he can access all warehouses at the moment. I created for each of my customer a new warehouse but my customers can access all other customers' warehouses at the moment. I would like to be able for all my customers to access only his own warehouse, for security reasons.

## Suggested implementation
When creating a new customer in Dolibarr, a new implementation would be to be able to choose to :
- allow him access to all warehouses,
- allow him to access to his own warehouse. 

## Suggested steps
- No idea of suggested steps as I am not a developper...

**Comment by dom-breizh** [comment]
While on the subject of warehouse management, it would be usefull to me to allow/block user access/view/modifications/etc... to specific warehouse(s), not only all or nothing options:

- allow all warehouses
- allow common (systemwide) warehouses 1, 5, 7
- allow own warehouse

also regarding his own warehouse, it should be possible to extend access to other users.
