### ISSUE TITLE
When shipping product show only available warehouses

### ISSUE THREAD

**Issue by DH88UK** [Dolibarr/dolibarr#17216]
When the user is creating a stock shipment, there is the option to take the product from any warehouse.
In my case at least, each item of stock is only applicable to 1 or 2 warehouses.
It would be very helpful if the dropdown menu only showed the warehouses where the product was actually available, and better still if the quantity available at each warehouse was given to the user in the dropdown.

**Comment by jocker132** [comment]
Dear @DH88UK ,
What if the order contains multiple products and that the not all the products ordered are available on same warehouse.
In this case which warehouse should be available on the list ? And which quantity to show on the dropdownlist ? Of each product ?
