### ISSUE TITLE
Bug: cannot change customer of a proposal

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#17221]
# Bug
there is no edit pen next to the customer

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.14
- **Database**: PostgreSQL 13.1
- **URL(s)**: /comm/propal/card.php?id=20

## Expected and actual behavior
I expected to be able to change customer. The customer I created was a duplicate and now I found the original card and want to change to that.

## Steps to reproduce the behavior
create a proposal
try to change the customer after creation -> impossible

**Comment by atm-maxime** [comment]
Hello. This is expected behavior. If you have a duplicate third-party, try to merge the 2 third-party cards. And don't hesitate to ask on forums before opening an issue on GitHub.

**Comment by dpriskorn** [comment]
I merged the contacts. Worked fine :D
