### ISSUE TITLE
Bug: cannot change amount on salary payment

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#17236]
# Bug
changing the linked bank entry worked fine, but the salary card does not allow me to change the amount.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.14
- **Database**: PostgreSQL 13.1
- **URL(s)**: /salaries/card.php?id=2&save_lastsearch_values=1

## Expected and actual behavior
I expect to be able to change the amount

## Steps to reproduce the behavior
create a salary payment
try changing the amount

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/68460690/114436075-37aed780-9bc5-11eb-94d9-b89a454d864e.png)

Can someone confirm this is present on v13?
Is this intended?
I changed the amount in the database (llx_payment_salary) and it worked fine.

**Comment by ksar-ksar** [comment]
Hi,

First thing is to try to upgrade to V12.0.5
