### ISSUE TITLE
TakePos display problem: special characters

### ISSUE THREAD

**Issue by fred1201** [Dolibarr/dolibarr#17242]
# Bug
TakePos Doesn't display special caracter in TPV screen dispite the fact other screen is working in dolibarr.
ex : rather than display éèà in the screen we obtain `&eacute;&egrave;&agrave;`

![213c374549f6d4784cd398f42cb36041da6e5263](https://user-images.githubusercontent.com/25524020/114503963-644b0980-9c2e-11eb-9a77-63cfdaa1c5df.jpeg)

## Environment
- **Version**: 12.xx and 13.xx
- **OS**: centos
- **Web server**: apache
- **PHP**: 7.4
- **Database**: mysql 1.3
- **URL(s)**: /takepos/index.php?idmenu=1

## Expected and actual behavior
Description which comes from a MySQL table, isn't displayed correctly - any HTML output that should be in description is broken.
I expect to display properly.

## Steps to reproduce the behavior
encode description categorie or product in Dolibarr database with `&eacute;&egrave;&agrave;` you should obtain `&eacute;&egrave;&agrave;` in the screen rather than éàè

To fix change call fonction in the folowing file  \htdocs\takepos\index.php

line 207 in dolibarr 12.05 ex :
//* this $("#catdesc"+i).text(categories[parseInt(i)+parseInt(first)][‹ label ›]);
should be $("#catdesc"+i).html(categories[parseInt(i)+parseInt(first)][‹ label ›]);

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
before the fix

![213c374549f6d4784cd398f42cb36041da6e5263](https://user-images.githubusercontent.com/25524020/114503824-29e16c80-9c2e-11eb-8209-515cdbb9df46.jpeg)

and after

![7a4a355a19e410177b7339473788afef3b7f8192_2_690x313](https://user-images.githubusercontent.com/25524020/114503848-32d23e00-9c2e-11eb-8278-9f45f40734be.jpeg)

Can someone confirm this is present on v12 and v13 ?
Is this confirmed i would be very please to fix it.

Thank in advance.

**Comment by dolibit-ut** [comment]
Hey, i have tested this with  éèà  and  äöü  in Dolibarr 13 and have no display errors.



![grafik](https://user-images.githubusercontent.com/45215329/115441819-956ca080-a211-11eb-9c45-9eb6808040cd.png)

**Comment by fred1201** [comment]
Hi 

Tested on 13.0.3 bug still there.
Please insert data directly in database to reproduce the problem.

Thank in advance

![Display](https://user-images.githubusercontent.com/25524020/123932935-36a27080-d992-11eb-9477-567fc5e872b6.PNG)
