### ISSUE TITLE
can't create new user

### ISSUE THREAD

**Issue by nezzept** [Dolibarr/dolibarr#17241]
# Bug
after a fresh installation which works without any errors, i wasn't able to create new user(s).
i was looking into the source of /user/card.php

the problem was that the var "$action" was always set to the $_GET action which was always "create" and does not take the value from the hidden input in $_POST action...

The solution which worked for me was to change the line:
$action         = GETPOST('action', 'aZ09');
to:
$action         = GETPOST('action', 'aZ09', 3);

because now the action comes from $_GET only when in $_POST action isn't set.

Was it a bad idea from me? Did i made something wrong?

## Environment
- **Version**: 13.0.2
- **OS**: Ubuntu Bionic
- **Web server**: nginx/1.14.0 (Ubuntu)
- **PHP**: 7.2
- **Database**: MariaDB 10.5.9
- **URL(s)**: /user/card.php?leftmenu=users&action=create

BTW: This seems to be the same problem when create a new group. same issue.

maybe the problem is the "function GETPOST" on htdocs/core/lib/functions.lib.php

"function GETPOST($paramname, $check = 'alphanohtml', $method = 0, $filter = null, $options = null, $noreplace = 0)"

So when "$method" is not defined on the function call, it gives as the result the var from $_GET back, even when it is existing in $_POST.
Maybe it would be better to set it to $method = 3 ? Then it will give the result from the $_GET in the url back, if there no var with the same name exist in $_POST, which makes much more sense when i think about the create user and create group functions.

**Comment by ksar-ksar** [comment]
Hi,

This is working for me, I can't reproduce.

**Comment by nezzept** [comment]
I wasn't looking deeper in the code.
I was writing a var_dump int the file card.php before and after the hook for other functions in this file.
And i saw everytime that the var $action has the value "create".
So the part where the new user will be written to the database was never reached.

As a guy who isn't so deep into php, where i can search for a configuration mistake on my machine?
Where is the point to jump in and have a look?

**Comment by nezzept** [comment]
OK. I have installed the same version on another server which was freshly installed and there was no problem to create users.
So i looked what phpinfo() can tell me what is different on both installations.

THE SOLUTION:
change this in php.ini to standard:

cgi.fix_pathinfo = 1

and all will be fine. Seems too many cooks spoil the broth.

When this is set to 0, the $_SERVER['PHP_SELF'] will be empty and so dolibarr doesn't work right.
there are many old tutorials who write that this must be changed to 0 for security reasons. But seems this is only for the older PHP versions a security problem.
