### ISSUE TITLE
fk_warehouse missing

### ISSUE THREAD

**Issue by bungee-** [Dolibarr/dolibarr#17258]
Installed 14.0.0-alpha today and when I tried to open newly created third-party (customer) I got back blank page with record missing text.

Error in log was: DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 's.fk_warehouse' in 'field list'

I added fk_warehouse(INT) field to llx_societe table and it works now. 

I hope this helps, I'm glad to provide feedback to good project.

**Comment by bungee-** [comment]
This topic may be duplicate of: "can't create new user #17241"

**Comment by BB2A-Anthony** [comment]
Thank It's new install? Not migrate?

**Comment by BB2A-Anthony** [comment]
I have résolve bug in PR #17267

if you whant to retry when @eldy merge PR #17267
