### ISSUE TITLE
login form action path with $dolibarr_main_url_root is define

### ISSUE THREAD

**Issue by dbelpois** [Dolibarr/dolibarr#17254]
Hello.
$when dolibarr_main_url_root is define, on the login page this path is not include in action ref
here is the html content when I try to connect
<form id="login" name="login" method="post" action="/index.php?mainmenu=home">

in source code core/tpl/login.tpl.php 
<form id="login" name="login" method="post" action="<?php echo $php_self; ?>">

Is it possible to modified like this or sothing like this ? 
<form id="login" name="login" method="post" action="<?php echo **DOL_URL_ROOT.**$php_self; ?>">

**Comment by ksar-ksar** [comment]
Hello,

Sorry but difficult to understand your question, and I'm not sure GitHub is the right tool to do so.
Please post your message on the English forum : https://www.dolibarr.org/forum/

**Comment by dbelpois** [comment]
sorry my message was not complete.
can you add $dolibarr_main_url_root in login.tpl.php line 102 when is define ?
like this (exemple)
form id="login" name="login" method="post" action="<?php echo DOL_URL_ROOT ?><?php echo $php_self; ?>"

or in $php_self  variable
