### ISSUE TITLE
Mysql in error on supplier invoice creation with PHP 8

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#17277]
# Bug
Mysql in error on supplier invoice creation with PHP 8.
I know that PHP 8 is not yet supported, but Dolibarr should be prepared for it.
The error doesn't occur when I use PHP 7.4 (the remaining being the same.)

## Environment
- **Version**: 13.0.2
- **OS**: Mageia Linux 8
- **Web server**: apache
- **PHP**: 8.0.2
- **Database**: MariaDB 10.5.8
- **URL(s)**: /dolibarr/htdocs/fourn/facture/card.php

## Expected and actual behavior
'''
Dolibarr a détecté une erreur technique.
You use an experimental or develop level of features, so please do NOT report any bugs or vulnerability, except if problem is confirmed after moving option MAIN_FEATURES_LEVEL back to 0.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20210414172841
Dolibarr: 13.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 2
PHP: 8.0.2
Serveur: Apache/2.4.46 (Mageia) PHP/8.0.2
OS: Linux VMm8 5.10.27-desktop-1.mga8 #1 SMP Tue Mar 30 23:14:59 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.1.0 Chrome/83.0.4103.122 Safari/537.36

Url sollicitée: /dolibarr/htdocs/fourn/facture/card.php
Referer: http://localhost/dolibarr/htdocs/fourn/facture/card.php?leftmenu=suppliers_bills&action=create
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, api, notification, multicurrency, workflow, accounting, agenda, commande, ecm, expensereport, facture, fournisseur, printing, resource, salaries, societe, service, propal, blockedlog, mailing, ficheinter, document, banque, tax, imprap, importfrombankcsv, mylist, product, receiptprinter, phpip
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT p.ref, pf.amount, pf.multicurrency_amount, p.fk_paiement, p.datep, p.num_paiement as num, t.code FROM llx_paiementfourn_facturefourn as pf, llx_paiementfourn as p, llx_c_paiement as t WHERE pf.fk_facturefourn = AND pf.fk_paiementfourn = p.rowid AND p.fk_paiement = t.id AND p.entity IN (1)
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND pf.fk_paiementfourn = p.rowid AND p.fk_paiement = t.id AND p.entity IN (1)' at line 1

Dolibarr a détecté une erreur technique.
You use an experimental or develop level of features, so please do NOT report any bugs or vulnerability, except if problem is confirmed after moving option MAIN_FEATURES_LEVEL back to 0.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20210414172842
Dolibarr: 13.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 2
PHP: 8.0.2
Serveur: Apache/2.4.46 (Mageia) PHP/8.0.2
OS: Linux VMm8 5.10.27-desktop-1.mga8 #1 SMP Tue Mar 30 23:14:59 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.1.0 Chrome/83.0.4103.122 Safari/537.36

Url sollicitée: /dolibarr/htdocs/fourn/facture/card.php
Referer: http://localhost/dolibarr/htdocs/fourn/facture/card.php?leftmenu=suppliers_bills&action=create
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, api, notification, multicurrency, workflow, accounting, agenda, commande, ecm, expensereport, facture, fournisseur, printing, resource, salaries, societe, service, propal, blockedlog, mailing, ficheinter, document, banque, tax, imprap, importfrombankcsv, mylist, product, receiptprinter, phpip
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT rowid, fk_source, sourcetype, fk_target, targettype FROM llx_element_element WHERE (fk_source = AND sourcetype = 'invoice_supplier') OR (fk_target = AND targettype = 'invoice_supplier') ORDER BY sourcetype
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND sourcetype = 'invoice_supplier') OR (fk_target = AND targettype = 'invoi...' at line 1
'''

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by papoteur-mga** [comment]
This seems linked to the fact in the first screen of the invoice creation (create) the "Standard invoice" is not selected, nor any other radio button of the list. Thus the variable 'type' is not set as Post data.

**Comment by ksar-ksar** [comment]
Hello,

Dolibarr V13 is not compatible PHP V8 : https://wiki.dolibarr.org/index.php/Releases

If you want to help to PHP V8 integration go there : https://github.com/Dolibarr/dolibarr/issues/16628
