### ISSUE TITLE
Feature Request: Supplier Automatic share key generation

### ISSUE THREAD

**Issue by toni-mx** [Dolibarr/dolibarr#17286]
# Feature Request
Just as the customer proposals, orders and invoice have an option to automatically set a share key when PDF is generated
INVOICE_ALLOW_EXTERNAL_DOWNLOAD 
PROPOSAL_ALLOW_EXTERNAL_DOWNLOAD
ORDER_ALLOW_EXTERNAL_DOWNLOAD

It would be great to have this same option under Supplier module as some of us still using traditional buying processes  (Generate Supplier order, sign it, send it, etc.)

This can help us program bot notifications for messaging software like Whastapp, Sign, Telegram, etc.

Thanks in Advance

 - Toni S

**Comment by ksar-ksar** [comment]
Hello,

Could you explain a bit more what is "not working" ?

**Comment by toni-mx** [comment]
Hi @ksar-ksar 
OMG I'm so, so sorry I misread entirely the setup (In my country we use the word order almost all the time to refer a **supplier** side transaction.

Until now I see I was reading an option for **customer order**

So setup is working as it should.

There is no bug here rather is a _Feature Request_

**Request Updated**

My apologies 
  -Toni
