### ISSUE TITLE
Error "Duplicate_entry for uk_ecm_files" should not occur for files with the same basename.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#17289]
# Bug
When uploading a png and a pdf with the same basename (example: BASENAME.png and BASENAME.pdf), an error notification appears ("Duplicate_entry ... for uk_ecm_files")

## Environment
- **Version**: 12.0.5
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**:  7.4.13
- **URL(s)**: /fourn/facture/document.php

This images demonstrates the message:
![image](https://user-images.githubusercontent.com/1504752/115004047-b007e800-9ea6-11eb-8474-1c0025523983.png)

Complément: le message "Error Duplicate entry 'fournisseur/facture/1/0/SI2103-1294-SI2103-1294-8127591763170753' for key 'uk_ecm_files'" s'affiche également en visitant la page des fichiers ajoutés, il n'apparaît pas seulement après le téléversement de fichiers.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by mdeweerd** [comment]
The bug report shows the version this was tested with "12.0.5" which is one of the latest stable versions (at least the latest one in the level 12.

I do not like upgrading to the highest version (13.0.2) that much.

In the online 13.0.2 demo version the issue does not appear.

I close the ticket because you seem to believe this is fixed in the last stable, which must be 13.0.2 and because it does not occur on the demo platform.
If I run into this again, I can reopen the ticket.

**Comment by catmaps** [comment]
We got a similar problem in version 14.03. It gives this message:
>>Error Duplicate entry 'bank/checkdeposits/CHK2101-001-bordereau-CHK2101-0001.pdf-1 for key 'uk_ecm_files'

**Comment by centoasa** [comment]
same issue still remain on latest release 19.02
