### ISSUE TITLE
Bug?: Third-party relative discount not applied when using Replenishment order

### ISSUE THREAD

**Issue by mimifred** [Dolibarr/dolibarr#17296]
# Bug
Relative discount is configured in third-party.
Discount is applied when creating a new order from commerce module
Discount is **not applied** when using //Product | Service - Warehouses - Replenishment//

## Environment
- **Version**: 13.0.2
- **Web server**: apache
- **PHP**: 7.2

**Comment by eldy** [comment]
Can you check that the relative discount is a "vendor" relative discount and not a customer discount ?
If yes, this is a bug.

**Comment by mimifred** [comment]
Hello,

Third-party is "Not prospect, nor customer"
Discount is added under "Vendor/Relative discount"

When creating a replenishment order, I can see "You have a default discount of 10% from this vendor.You have discounts available (credits notes or down payments) for 7.00 Swiss Francs from this vendor."

But nor Relative discount, nor credit notes are applied

**Comment by Hystepik** [comment]
It seems to be fix so I close the issue.
Feel free to reopen if not.
