### ISSUE TITLE
Error when creating new customer

### ISSUE THREAD

**Issue by eleobfr** [Dolibarr/dolibarr#17308]
# Bug
When creating a new CUSTOMER, I had an error message : Field 'Vendor' is required
But I don't use Vendor module, I only want to create a new customer

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 8.0.3
- **Database**: MariaDB-1:10.5.9+maria~stretch
- **URL(s)**: [.../societe/card.php?leftmenu=customers&action=create&type=c]

## Steps to reproduce the behavior
Create a new customer with Vendor disabled

## [Attached files]
![image](https://user-images.githubusercontent.com/62488125/115151328-afb94980-a06c-11eb-94f9-42d57f99b400.png)

**Comment by ksar-ksar** [comment]
Hello,

> Version: 13.0.2
> PHP: 8.0.3

Version 13.0.2 is not compatible with PHP V8

**Comment by eleobfr** [comment]
OK, back to php7.4 resolve the issue
