### ISSUE TITLE
Double clic protection on POST requests

### ISSUE THREAD

**Issue by Magissia** [Dolibarr/dolibarr#17319]
# Feature Request
[*Short description*]
When two successive POST request from the same session contain exactly the same data and are submitted in less than a specified time with a default of 1000ms, acknowledge only the first POST within that time frame and ignore the others.
## Use case
[*Verbose description*]
When someone accidentally double clic (user error or mouse, touchscreen, driver, browser malfunction) on a button that leads to a POST request that would create data (like adding stock, additional products to an invoice), it can in some case create situations it is difficult to recover from, or are uselessly time consuming to recover from.

This suggestion is linked to this [thread ](https://www.dolibarr.fr/forum/t/probleme-de-commande-fournisseur-suite-a-double-clic-bug-probable/36377), as it would be a good measure to prevent issues expressed there.
## Suggested implementation
[*Verbose description*]
Lot of open source bulletin boards software have such feature to prevent accidental double post.
Github prevents you from double opening an issue.

From a sysadmin point of view, each button that leads to a POST request could have a hidden timestamp field generated and pre populated when a page is loaded, allowing backend PHP to compare the requests received, checking the session ID too to prevent situations where two different persons work the same time on Dolibarr.
## Suggested steps
[*List of tasks to achieve goal*]
I am not a dev, I am not qualified to evaluate this part.

**Comment by ksar-ksar** [comment]
Hello,

On which Dolibarr version ?
Normally in V13 it should not be possible

**Comment by daraelmin** [comment]
Wich version of dolibarr do you use ?
Normally with 13.0 and CSRF token activated (default) the issue shouldn't appear cause the token is no more valid when used once.

**Comment by daraelmin** [comment]
@ksar-ksar you was faster than I. ;-)

CSRF tokens may have been deactivated with the setup other option. So the question : 
Should we implement something for CSRF deactivated ?
