### ISSUE TITLE
Star Ratings Option on Invoices, Tickets & Products for Better Feedback Management. 

### ISSUE THREAD

**Issue by thegeettanna** [Dolibarr/dolibarr#17313]
# Feature Request
We would like to add ratings to our each of our invoices, to enable a more sincere feedback process for each transaction we encounter with the outside world. 

This is what we were able to reach: 
![Screen Shot 2021-04-19 at 11 41 49 PM](https://user-images.githubusercontent.com/24646523/115283413-f0968880-a168-11eb-9a1c-0389950f1f12.jpg)

## Use case
There is currently no module that enables such option with ease. But the extra fields help in a way. So we added an extra field to customer invoices that was a radio button option with options from 1-5. 
This was then masked using jquery as per the resources from this website:
https://www.codexworld.com/star-rating-system-with-jquery-ajax-php/

## Suggested implementation
We are now able to insert data in extra fields table for the customer invoice, we are yet to show the feedback on invoices page. There were troubles reaching here, so made this post, but then before we could add data, it was posted. 

I believe such an approach can help a lot of modules, like Customer & Vendor Invoices. Another module that can benefit is Tickets. Once we successfully test it out, we will be send emails with option to give us feedback using these stars. 

If people would be interested, we would be glad to furnish the code if we successfully implement. Although, we are non technical enthusiast, which is why our code might take some time and might be inadequate in a way. But hey, the ideas is worth pursuing.

It looks something like this:
![image](https://user-images.githubusercontent.com/24646523/115284219-06f11400-a16a-11eb-8dc1-a959f8de329e.png)

**Comment by atm-maxime** [comment]
Hey !
And your issue is ?

**Comment by daraelmin** [comment]
Is this a real erp function ? 
I meen : it introduce marketing info into work process but dolibarr purpose is management not communication (publicité).

**Comment by thegeettanna** [comment]
> Is this a real erp function ?
> I meen : it introduce marketing info into work process but dolibarr purpose is management not communication (publicité).

In my opinion it is still a management process. It is sort of marketing when you send it to clients for feedback, agree on the same. But at the same time, if anyone is trying to lead a company into something better for their customers, then they need feedback. 
What process is management monitoring? Without feedback, what steps are to be taken to improve management and operations in a company is difficult to judge. This gives a data centric approach to managers trying to lead changes in their organizations. 
Feedback in all its entity is a managers best friend. 

This is what inspired us to attempt the star ratings option. 
![Screen Shot 2021-04-16 at 2 01 35 PM](https://user-images.githubusercontent.com/24646523/115340897-31bc8600-a1c5-11eb-9624-2002b06e60b8.jpg)

**Comment by daraelmin** [comment]
Hi @geetthegreat ,

Cozld you propose this code as a default module (in htdocs not in custom) for testing please ?

Cheers

**Comment by BebZ** [comment]
Hello, 
Good idea, of course ratings are a manager's driver for change :)
But if you keep it inside Dolibarr only it doesn't make any sense, because only employees can add feedback
How did you "open it to the outside word" ? How you customers / third parties give a feeback on it ?
With an external portal it would be possible, but do you plan something like this ? 
If yes, we could help you because we will be working on "external users" for them to have an access to their documents inside Dolibarr.
Thanks for your feedback and keep your efforts going  !

**Comment by daraelmin** [comment]
> Hello, 
> Good idea, of course ratings are a manager's driver for change :)
> But if you keep it inside Dolibarr only it doesn't make any sense, because only employees can add feedback
> How did you "open it to the outside word" ? How you customers / third parties give a feeback on it ?
> With an external portal it would be possible, but do you plan something like this ? 
> If yes, we could help you because we will be working on "external users" for them to have an access to their documents inside Dolibarr.
> Thanks for your feedback and keep your efforts going  !

External user may be able to rates, so if your customer have an access, they can rate directly.

And, I think it may not be so complicated to offer a public page that may accept rating with a token refer to an order or so.

**Comment by thegeettanna** [comment]
> Hi @geetthegreat ,
> 
> Cozld you propose this code as a default module (in htdocs not in custom) for testing please ?
> 
> Cheers

Hi @daraelmin, 

I am not sure how to propose the code in default mode. Let me know and I will do that as well. 
But I will share my code by this weekend, I actually ran into a problem and this customization was side tracked due to other priorities. But will complete this during weekend and share the code here 👍🏻

**Comment by thegeettanna** [comment]
> Hello,
> Good idea, of course ratings are a manager's driver for change :)
> But if you keep it inside Dolibarr only it doesn't make any sense, because only employees can add feedback
> How did you "open it to the outside word" ? How you customers / third parties give a feeback on it ?
> With an external portal it would be possible, but do you plan something like this ?
> If yes, we could help you because we will be working on "external users" for them to have an access to their documents inside Dolibarr.
> Thanks for your feedback and keep your efforts going !

Hi @BebZ, 

We can easily send it to the outside world for feedback, but ours was designed for internal users so they could get in touch with clients and update their feedbacks to begin experimentation with feedback. But yes, the code already is able to accommodate the feature of sending html emails to the outside world and collecting the feedback and updating the database with feedback received. Which is what we have planned 3 months from now for our case as well. 

When a user clicks on any of the stars on dolibarr page, it is actually going to call a link which then inputs the data inside our db, this same concept can be used in emails for feedback. When we send them an email using html, we can add those links to those stars and when the user (irrespective of who it is) clicks on either of the stars, it will be registered in our database. 
Although, you will want to change the landing page in case of external users, so the links for emails will need a different landing page. 

I think me sharing the code will help clear things a little more. 
Will try to complete it soon and send it over for review to the community.
