### ISSUE TITLE
Change ref= keyword in URI because of plugins/url cleaner

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#17311]
Hello,
some of our users / customers / org members can't pay their invoices when clicking on URL in mails due to "ref=" keyword remove feature from some plugins or "privacy" tools.

So i think it could be a good idea to replace ref= by an other keyword such as invoice= or something else ... or by base64encode arguments maybe ?

For example: https://example.com/dolibarr/public/payment/newpayment.php?source=invoice&ref=FA2104-0001&securekey=xxxx is converted to https://example.com/dolibarr/public/payment/newpayment.php?source=invoice&securekey=xxxx (ref= was removed by some privacy ruyles / plugins) then error on dolibarr was : "Paramètres incorrects - ref"

Exemple with this firefox plugin : https://addons.mozilla.org/fr/firefox/addon/clearurls/

Thanks

**Comment by ksar-ksar** [comment]
Hello,

This is not directly linked to dolibarr, this is more a feature request

**Comment by rycks** [comment]
Ok @ksar-ksar that's your point of view ... but when your customers can't follow payment links due to that you could change and think that's a serious problem ! And when customers of your customers (for example if you are a dolibarr hosting provider) it could became a very big problem because you loose business and $$$.

So feature request if you wan't but for me it's a serious problem like a big bug (a business one, not a technical one of course).
