### ISSUE TITLE
Bug : length of llx_expedition.refclient too short

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#17339]
Hello,  

llx commandedet . refclient can accept field of 255 characters 
but llx expeditiondet . refclient accepts only 30 characters

so when you generate a shipment, it trims the end of a long refclient, or generates a bug 

Bug also seen in Mobilid Ext.Direct picking 

seen in dolibarr 12.0.4

**Comment by eldy** [comment]
There is no column refclient into llx_expeditiondet.  Do you speak about table llx_expedition ? (if yes, it is 255 for v14)

**Comment by BebZ** [comment]
@fappels following our discussion, Francis. 
Can you confirm where the bug originates from ?
Thanks

**Comment by fappels** [comment]
I confirm to have error on 13

![ea017cdc-009f-41b2-ab3a-425f88774d36](https://user-images.githubusercontent.com/4573808/116522608-aaae9280-a8d5-11eb-8cd0-3fb39b51963a.png)

But origin of problem is 30 to 255 (updated in 7.0) for ref_customer in llx_expedition is missing in [7.0 migration script](https://github.com/Dolibarr/dolibarr/blob/7.0/htdocs/install/mysql/migration/6.0.0-7.0.0.sql)

So for new installations no issue, only for migrated installations.

@eldy Not sure what is best way to fix, add to 13 to 14 migration?

**Comment by Hystepik** [comment]
It seems to be fix so I close the issue.
Feel free to reopen if not.
