### ISSUE TITLE
BUG No label name on filter select

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#17357]
# Bug
[*No label name on filter select*]

For user frendly it's good to read the label name

![image](https://user-images.githubusercontent.com/34568357/115407304-3480a080-a1f0-11eb-8b05-d99f177ba2a3.png)

On black mode

![image](https://user-images.githubusercontent.com/34568357/115407526-61cd4e80-a1f0-11eb-82a3-74d64d15cffe.png)

Dolibarr version : 14

**Comment by eldy** [comment]
Seems already fixed by another PR
