### ISSUE TITLE
export comptat quadratus

### ISSUE THREAD

**Issue by Thipas** [Dolibarr/dolibarr#17351]
# Bug
[*Short description*]

L'export vers quadratus affiche "0" sur les lignes en CREDIT (TVA autre)

[*Files*]
/htdocs/accountancy/class/accountancyexport.class.php ligne 560

"$Tab['montant'] = str_pad(abs(($data->debit - $abs->credit) * 100), 12, '0', STR_PAD_LEFT);"

correctif possible 
$Tab['montant'] = str_pad(abs(($data->debit - $data->credit) * 100), 12, '0', STR_PAD_LEFT);

**Comment by aspangaro** [comment]
#17354
