### ISSUE TITLE
Right timezone wrong time

### ISSUE THREAD

**Issue by plp05045** [Dolibarr/dolibarr#17378]
I currently have my timezone set to America/Halifax and the current time is 9:31 however in Dolibar it is showing the time as 8:31. Is there something I have wrong in my configuration or is it a bug?

**Comment by daraelmin** [comment]
Wich version of dolibarr do you use ?

**Comment by plp05045** [comment]
13.0.2

**Comment by daraelmin** [comment]
Related #10885
And may be related to #16183
