### ISSUE TITLE
BUG: extrafield of type datetime in invoice row gets converted to unixtimestamp

### ISSUE THREAD

**Issue by betz0r** [Dolibarr/dolibarr#17380]
# Bug
Date and Time is stored in human readable format in database but gets converted to unixtimestamp on ODT invoices.

## Environment
- **Version**: 13.0.2
- **OS**: Ubuntu 20.04 Fokal
- **Web server**: Apache 2.4.41
- **PHP**: PHP 7.4.3
- **Database**: MariaDB 10.3.25

## Expected and actual behavior
User input by Date/Time datepicker in invoice module should be shown in invoice as human readable date/time (is stored in database as human readable date)

## Steps to reproduce the behavior
add additional row field in invoice, select type Date and Time, add row to any invoice and select from datepicker a date and time, check result on odt/pdf invoice, you will see a unixtimestamp instead of human readable datetime. 

![image](https://user-images.githubusercontent.com/1616482/115866542-15754f00-a43a-11eb-836d-b2820d3d3237.png)

**Comment by Hystepik** [comment]
Works for me in 13.0.2

**Comment by betz0r** [comment]
Thanks for your response. 
Deleting and recreating the extrafield and repopulating all data fixed it also for me.
Still curious what triggered this error, maybe upgrade from 10 to 13.0.2.
Thx and closed.

**Comment by mpractic** [comment]
I have this very same issue, both in v15 and v16, and I'm on Ubuntu 20.04 and MariaDB too. 
I've tried recreating the extrafield with no luck. Any ideas on how to solve it?
