### ISSUE TITLE
Adding organisational profile IDs in deafult invoice PDF template, crabe

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#17389]
# Feature Request
*In India it is mandatory to have GSTIN & PAN details in the invoice that businesses generate for customers. First there will be company details and address for From Company. Below the address GSTIN and PAN numbers should be present. We are providing these details in Setup->Company/Organization->Prof Id 1 (GSTIN),Prof Id 2 (PAN). But these information is not populated in the actual invoice.*

*On the current invoice the invoice number is given as Ref. It should be Invoice No.*

## Use case
*Install Dolibarr 13.0.2 and select en_IN as the display language. Now create a third party and generate an invoice for them. You will see no profile IDs is fetched in form company section.*

![Proposed invoice changes](https://user-images.githubusercontent.com/1249577/115955670-948b8580-a515-11eb-92b4-845d389e9b62.png)

**Comment by gmilad** [comment]
(French below)
Hello,

To add Prof Id 1 and Prof Id 2 you have to add MAIN_PROFID1_IN_SOURCE_ADDRESS in the configuration:

https://wiki.dolibarr.org/index.php?title=Setup_Other#PDF_Options

For Ref to transform into Invoice No you have to check the translations in the configuration.

Sincerely,
Gaëtan.

(Français en dessous)
Bonjour,

Pour rajouter Prof Id 1 et Prof Id 2 il faut rajouter MAIN_PROFID1_IN_SOURCE_ADDRESS dans la configuration :

https://wiki.dolibarr.org/index.php?title=Setup_Other#PDF_Options

Pour Ref a transformer en Invoice No il faut voir du côté des traductions dans la configuration.

Cordialement,
Gaëtan.

**Comment by alsoft10** [comment]
Thank you so much @gmilad . You saved my day. I appreciate your help.
