### ISSUE TITLE
LDAP membertypes test

### ISSUE THREAD

**Issue by francoisPE** [Dolibarr/dolibarr#17386]
# Bug
Test for LDAP group memberstypes set up with bug

## Environment
- **Version**: [*13.0.2*]
- **OS**: [*ubuntu20.04*]
- **Web server**: [*Apache2*]
- **PHP**: [*PHP 7.4*]
- **Database**: [*Maria*]
- **URL(s)**: [*https://.../ldap_members_types.php?action=testmembertype*]

## Expected and actual behavior
Test failed because ldap input file is wrong
"
dn: cn=MEMBERS TYPE SPECIMEN,ou=memberstypes,dc=domain,dc=fr
objectclass: top
objectclass: groupOfUniqueNames
cn: MEMBERS TYPE SPECIMEN
description: This is a note
uniqueMember: **uid=**,ou=members,dc=domain,dc=fr
"
I modify it and test in console. it works.
"
dn: cn=MEMBERS TYPE SPECIMEN,ou=memberstypes,dc=domain,dc=fr
objectclass: top
objectclass: groupOfUniqueNames
cn: MEMBERS TYPE SPECIMEN
description: This is a note
uniqueMember: **uid=mysuperadmin**,ou=members,dc=domain,dc=fr
"
(obviously, mysuperadmin is an alias for that forum...)

Rem : No impact on normal operations.

I would have modify the code and propose a PR. But I didn't find where LDAP is.
Many thanks

**Comment by daraelmin** [comment]
I'm not sure of what you want to change, but 

the ldap class is here: htdocs/core/class/ldap.class.php

the ldap array is called here : htdocs/core/lib/ldap.lib.php

and

the member ldap info are loaded from here : htdocs/adherents/ldap.php

**Comment by francoisPE** [comment]
It seems not to be there.
It is more likely in interface web module.
See picture
![image](https://user-images.githubusercontent.com/60675606/116109416-08b05f80-a6b5-11eb-8703-e04542a5c254.png)

**Comment by daraelmin** [comment]
Do this fix #17617 solve pour issue ?

**Comment by francoisPE** [comment]
Sorry, but I have dolibarr site right now.
I need few time to set up a new one.
I'll let you know.

**Comment by francoisPE** [comment]
Hello,
I test with 13.0.3, it still remains. This #17617 doesn't solve this issue.
Not sure that bug is same issue that #17782 
I thing it is simply a missing variable in file. But I didn't find out the file.
If you can tell me where LDAP synchro test is done, I can look at.
