### ISSUE TITLE
Bug: Messages in ticke crossed

### ISSUE THREAD

**Issue by pymeralia** [Dolibarr/dolibarr#17397]
# Bug
Messages on Dolibarr ticketing

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.16
- **Database**:  5.5.5-10.1.45-MariaDB-0+deb9u1
- **URL(s)**: /htdocs/ticket/card.php?action=view&track_id=3r12z7rwor94ozwj

## Expected and actual behavior
The messages in tickets, don't run ok, the items cross between different tickets. For example, in ticket 1, i write 1 message, after that, message appears in ticket 2. I have a real example to show yours, if you 

## Steps to reproduce the behavior
Nos encontramos en los tickets mensajes asociados que no corresponden al hilo del ticket. Pienso que existe algun problema en las claveds de las tablas tickets y eventos.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![imatge](https://user-images.githubusercontent.com/83216282/116070215-a17eb500-a68c-11eb-95f5-c4591ab4aa10.png)

**Comment by ksar-ksar** [comment]
Hello,

First thing is to upgrade to 12.0.5 at least
