### ISSUE TITLE
Bug: No podemos eliminar tareas

### ISSUE THREAD

**Issue by pymeralia** [Dolibarr/dolibarr#17398]
# Bug
Da un error al eliminar tareas.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.16
- **Database**:  5.5.5-10.1.45-MariaDB-0+deb9u1
- **URL(s)**: /htdocs/ticket/card.php?action=view&track_id=3r12z7rwor94ozwj

## Expected and actual behavior
No podemos suprimir tareas.

## Steps to reproduce the behavior
Creamos una tarea, y al intentar eliminarla, salta el error adjunto. subquery returns more than 1 row,

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![error_dolibarr_eliminar_tareas](https://user-images.githubusercontent.com/83216282/116070580-16ea8580-a68d-11eb-9ea1-f94f4bee6833.JPG)

**Comment by ksar-ksar** [comment]
Hello,

First thing is to upgrade to 12.0.5 at least
