### ISSUE TITLE
Add Badge on tabs

### ISSUE THREAD

**Issue by Mika-6-9** [Dolibarr/dolibarr#17391]
# Feature Request
Add Badge on tabs

## Use case
With the new function this-> tabs we cannot put a badge on a tab

## Suggested implementation
modify "function complete_head_from_modules" in fonctions.lib.php to implement this function

## Suggested steps
Add a seventh field with the value you want to display in the badge.
If the value is null, nothing is displayed.
Exemple :
if ($num > 0) $head[$h][1] .= '<span class="badge marginleftonlyshort">'.$num.'</span>';

**Comment by frederic34** [comment]
using hook completeTabsHead, you can add a tab where you want with badge showing any value
ex :
![image](https://user-images.githubusercontent.com/3624836/117549100-d863ac00-b038-11eb-8041-d4f91ae98583.png)

**Comment by Mika-6-9** [comment]
Hello.
Thanks for your comment, but after researching the wiki, forum, and Dolibarr core, I can't find anything.
Can you give me an example for a new module?
Thank you in advance.

**Comment by frederic34** [comment]
/**
	 * Execute action completeTabsHead
	 *
	 * @param   array           $parameters     Array of parameters
	 * @param   CommonObject    $object         The object to process (an invoice if you are in invoice module, a propale in propale's module, etc...)
	 * @param   string          $action         'add', 'update', 'view'
	 * @param   Hookmanager     $hookmanager    hookmanager
	 * @return  int                             <0 if KO,
	 *                                          =0 if OK but we want to process standard actions too,
	 *                                          >0 if OK and we want to replace standard actions.
	 */
	public function completeTabsHead(&$parameters, &$object, &$action, $hookmanager)
	{
		global $langs, $conf, $user;
		if (!isset($parameters['object']->element)) {
			return 0;
		}
		if ($parameters['mode'] == 'remove') {
			// utilisé si on veut faire disparaitre des onglets.
			return 0;
		} elseif ($parameters['mode'] == 'add') {
			$langs->load('monmodule@monmodule');
			// utilisé si on veut ajouter des onglets.
			$counter = count($parameters['head']);
			$element = $parameters['object']->element;
			$id = $parameters['object']->id;
			// verifier le type d'onglet comme member_stats où ça ne doit pas apparaitre
			if (in_array($element, ['societe', 'member', 'contrat', 'fichinter', 'project', 'propal', 'commande', 'facture', 'order_supplier', 'invoice_supplier'])) {
				$emailcount = 0;
				$sql = 'SELECT count(rowid) as nb FROM '.MAIN_DB_PREFIX.'monmodule_emails_sent';
				$sql .= ' WHERE userid='.(int) $user->id . ' AND module="'.$element.'"';
				$sql .= ' AND fk_object='.(int) $id;
				$resql = $this->db->query($sql);
				if ($resql && $obj = $this->db->fetch_object($resql)) {
					$emailcount = $obj->nb;
				}
				$parameters['head'][$counter][0] = dol_buildpath('/monmodule/tabs/msgraph_emails.php', 1) . '?id=' . $id . '&amp;module='.$element;
				$parameters['head'][$counter][1] = $langs->trans('monmoduleMailsTab');
				if ($emailcount > 0) {
					$parameters['head'][$counter][1] .= '<span class="badge marginleftonlyshort">' . $emailcount . '</span>';
				}
				$parameters['head'][$counter][2] = 'monmoduleemails';
				$counter++;
			}
			if ($counter > 0 && (int) DOL_VERSION < 14) {
				$this->results = $parameters['head'];
				// return 1 to replace standard code
				return 1;
			} else {
				// en V14 et + $parameters['head'] est modifiable par référence
				return 0;
			}
		}
	}

**Comment by frederic34** [comment]
put in actions_monmodule.class.php

**Comment by Mika-6-9** [comment]
I'm in V12, that certainly explains why I couldn't find it.
This function does not exist, it must have appeared in V13 or V14.
Thank you for everything.

**Comment by frederic34** [comment]
the hook completeTabsHead is called in complete_head_from_module : 
$reshook = $hookmanager->executeHooks('completeTabsHead', $parameters);

I added an example here in modulebuilder : https://github.com/Dolibarr/dolibarr/pull/17588
