### ISSUE TITLE
key shortcuts on Web-UI

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#17433]
Is it possible to create shortcuts for web use?

# Feature Request

Shortcuts for general navigation usage like
- page forward
- page backward
- go back to list
- switch the top-menu tabs
...

**Comment by ksar-ksar** [comment]
Hi,

I think same as #2787 https://github.com/Dolibarr/dolibarr/issues/2787

**Comment by dolibit-ut** [comment]
Oh, soooo old request.  Yes that's the same.

_But maybe also useful to stay renew for new discussion and motivation  ;-)_

**Comment by dolibit-ut** [comment]
But in difference to #2787 

i think initially it is good to create only generally valid (system-wide) shortcuts
like
- page forward / next page
- page backward / previous page
- go back
- creation (new entry/new document)
- new line
- go to next input field (?)
- save 
- view print form

and as second step a solution for individual/customized settings for different modules and users

**Comment by priojk** [comment]
I think this could still be interesting. It's one of the few strengths of the dedicated (fat) clients of some other ERP systems that users who are making many entries can speed up their workflow with such shortcuts.
