### ISSUE TITLE
TakePOS Search box wont work

### ISSUE THREAD

**Issue by loejo** [Dolibarr/dolibarr#17438]
# Bug

Short description*]
## Environment
- dolibarr 13.0.2
- windows 10
- google chrom

Search box wont work  for product name or code barr or anything alse 
![dol pr](https://user-images.githubusercontent.com/82964531/116647175-6e2c7680-a969-11eb-8621-9008849c6214.png)

**Comment by Hystepik** [comment]
Works for me in 13.0.2

**Comment by loejo** [comment]
@Hystepik  
the problem is solved by reinstalling dolibarr .
