### ISSUE TITLE
501 error in Supplier Payment

### ISSUE THREAD

**Issue by Dreller** [Dolibarr/dolibarr#17460]
# Bug
501 error when setting "brodator" as numbering sequence in Supplier Payment.

## Environment
- **Version**: *13.0.0*
- **OS**: *Linux*
- **Web server**: *Linux world-218.ca.planethoster.net 3.10.0-962.3.2.lve1.5.36.el7.x86_64 #1 SMP Mon May 18 02:16:06 EDT 2020 x86_64*
- **PHP**: *7.3.27*
- **Database**: *MySQL or MariaDB 5.5.5-10.2.37-MariaDB*
- **URL(s)**: */admin/supplier_payment.php*

## Expected and actual behavior
We can expect the system to activate the desired numbering sequence.  Instead, we get this 501 error:

> Not Implemented
> GET not supported for current URL.
> Additionally, a 501 Not Implemented error was encountered while trying to use an ErrorDocument to handle the request.

## Steps to reproduce the behavior
In "Configuration des règlements fournisseurs", go to tab "Règlements fournisseurs".
Set a custom mask for the numbering "brodator".
Activate the numbering "brodator".
See screenshot: https://prnt.sc/12e2ebl

You get the 501 error.
See screenshot: https://prnt.sc/12e2htz

PS: THANK YOU for Dolibarr, it's THE best software !! ❤

**Comment by Hystepik** [comment]
Hello works for me in 13.0.2
