### ISSUE TITLE
defaultvalue 'fk_account' on compta/facture not working

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#17502]
I am trying to set defaultvalues for the create customer invoice card.
I set these values:

<html>
<body>

compta/facture/card.php?action=create | fk_account | 1 |   |  
-- | -- | -- | -- | --
compta/facture/card.php?action=create | mode_reglement_id | 2 |   |  

<br class="Apple-interchange-newline">
</body>
</html>

`mode_reglement_id` is working.
`fk_account` is not being set as the default value on the select item.

-- 

I checked the source and it seems that `GETPOSTISSET('fk_account')` returns false although I set the options like in the table above

**Comment by dolibit-ut** [comment]
I have also checked now and can confirm this.

**Comment by dolibit-ut** [comment]
Btw: It would be also nice to have a general setting for a default bank account.
