### ISSUE TITLE
Problem recovering a third party containing an apostrophe from the database

### ISSUE THREAD

**Issue by AbdoulAzizi** [Dolibarr/dolibarr#17547]
# Instructions
Third party (Tiers) containing an apostrophe 
#17546

# Bug
There is a bug when you want to retrieve the name of a third party from the database to display it in a <*select> <*/select> form by a hook system.
url : /product/stock/product.php?id=8&action=transfert

## Environment
- **Version**:  Dolibarr version 12
- **OS**: Linux Ubuntu Version 20.04
- **Web server**: Postgresql
- **PHP**: 7
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]
## Expected and actual behavior

This is when fields are added during the stock transfer (the "Transporteur" and "Demandeur" field by the Hook system) which will require a database query in order to display the shots available in the corresponding fields.
When there is a third party created with an apostrophe (for example Afra'ou) the "Transporteur"  and "Demandeur" fields will not appear as in the first screenshot.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

![transfertdestock1](https://user-images.githubusercontent.com/46421012/117552397-90458900-b03a-11eb-97c5-c66ebab893f7.png)
![transfertdestock2](https://user-images.githubusercontent.com/46421012/117552404-9b001e00-b03a-11eb-95e6-4bcd48481456.png)

**Comment by daraelmin** [comment]
Hi,

Could you copy/paste the url (without the dns) please ?

Cheers

**Comment by AbdoulAzizi** [comment]
> Hi,
> 
> Could you copy/paste the url (without the dns) please ?
> 
> Cheers

Hi, here is the url without the dns : 

/product/stock/product.php?id=8&action=transfert

**Important!** Note that these two fields "Transporteur" and "Demandeur" do not exist in the standard version of dolibarr, they are added by us by the hook system that dolibarr offers for developers.

Cheers

**Comment by daraelmin** [comment]
Is it possible that your hook use simple quote instead of double quote to display the database info ?

**Comment by AbdoulAzizi** [comment]
> Is it possible that your hook use simple quote instead of double quote to display the database info ?

Yes exactly.
In fact, we called the method `append('$myvariable')` to display Third party (Tiers) from the database.
While checking now, I found a solution by using the another php "addslashes ()" method to escape single quotes.
here is the solution:

```
$myvariable = addslashes($myvariable);
print "<script> $('div.tabBarWithBottom table.border').append('$myvariable') </script>";
```

Thank you very much for the attention you have given to this subject, and your concern for support.

**Comment by daraelmin** [comment]
@AbdoulAzizi you're welcome

@eldy should we add something un hookmanager doc about this issue or modify hook management to prevent it from happening (I'm mot really sure if it ils possible) ?

**Comment by AbdoulAzizi** [comment]
> @AbdoulAzizi you're welcome
> 
> @eldy should we add something un hookmanager doc about this issue or modify hook management to prevent it from happening (I'm mot really sure if it ils possible) ?

@daraelmin I am really grateful for your help.
@daraelmin @eldy If that is possible, really that would be interesting to modify hook management to prevent it from happening,
