### ISSUE TITLE
Other Setup - shows no more the modified date - Dolibarr 14 alpha

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#17543]
htdocs/admin/const.php

# Bug
on 'Other Setup' View   (/admin/const.php) 
the column 'modified date' is now empty  

## Environment
- **Version**: Dolibarr 14.0.0-alpha
- **OS**: Windows 10
- **Web server**: Apache
- **PHP**: 7.4
- **Database**: MariaDB

**Comment by dolibit-ut** [comment]
In   /admin/const.php   i found now this difference between 13.0.2 and 14.0.0-alpha

```
// Date last change
print '<td class="nowraponall">';
```

class="nowraponall"  is new insert

What is that for?

**Comment by Hystepik** [comment]
Hello try to update your Dolibarr version, because it works for me

**Comment by dolibit-ut** [comment]
Hello, 
i made the update to now 14.0.0-beta  and have still no modification date.

![Screenshot_2021-05-20  Dolibarr 14 0 0-beta - Other Setup - shows no modif date](https://user-images.githubusercontent.com/45215329/118986573-c6123800-b97f-11eb-9b28-a9df96d2d100.png)

**Comment by daraelmin** [comment]
Work for me.
Do you use eldy thème ?

**Comment by dolibit-ut** [comment]
Yes, eldy theme & all like standard - no special settings.

First installation was Dolibarr 11.0.4 and then updates to 12 / 13 / 14
and until Dolibarr 13 it shows the modif. date.

**Comment by Hystepik** [comment]
> In /admin/const.php i found now this difference between 13.0.2 and 14.0.0-alpha
> 
> ```
> // Date last change
> print '<td class="nowraponall">';
> ```
> 
> class="nowraponall" is new insert
> 
> What is that for?

This is only used to classify code, but maybe you could copy paste the two next lines to see what you have next.
