### ISSUE TITLE
the automatic copy of the public note of the order or shipment to the invoice no longer works

### ISSUE THREAD

**Issue by chabgui** [Dolibarr/dolibarr#17544]
# Bug
the automatic copy of the public note of the order or shipment to the invoice no longer works in 13.0.2

**Comment by ksar-ksar** [comment]
Hello,

You need to activate FACTURE_REUSE_NOTES_ON_CREATE_FROM

https://wiki.dolibarr.org/index.php?title=Setup_Other#Invoice_Module
