### ISSUE TITLE
Same EAN can not be used from 2 diffrent provider

### ISSUE THREAD

**Issue by ArnaudFR67** [Dolibarr/dolibarr#17550]
![Capture d’écran 2021-05-09 141156](https://user-images.githubusercontent.com/81926163/117571847-8b331900-b0d0-11eb-940d-405bfcc83dbb.png)
# Instructions
[When I enter a second purchase price for a second supplier, I get an error.]
# Bug
[see attached]

## Environment
- **Version**: 13.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) PHP/7.3.12
- **PHP**: apache2handler 7.3.12
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB
- **URL(s)**: /dolibarr/product/fournisseurs.php?id=679

## Expected and actual behavior
[I should be able to enter for the same product (EAN13) enter several prices and suppliers]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
You make a confusion between the barcode of the product and a barcode of a supplier reference.
If it is the same between 2 different provider, it means it is the same product (so barcode must be entered into product and not into the supplier ref). If this is an EAN specific to a supplier (so a real supplier ref), it can't be similar (the EAN code of a supplier should contains the code of supplier inside).
Also note that a reference price can/must include the supplier inside even if price is same when you enter the 2 price references.

**Comment by ArnaudFR67** [comment]
Thank you for your answer.
