### ISSUE TITLE
BUG : Configuration of the module accounting (double entry) does not work

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#17560]
# Bug
Most of the settings of the module accounting (double entry) does not work

## Environment
- **Version**: 13.0.2
- **URL(s)**: htdocs/accountancy/admin/index.php

## Expected and actual behavior
When you click on the button, the settings are not saved.

![image](https://user-images.githubusercontent.com/35605507/117630107-2385d800-b17b-11eb-9b8b-94a174ded318.png)

**Comment by eldy** [comment]
👍🏻 
I made a more complete fix to aslo show a message when changing setting...
