### ISSUE TITLE
Installer first page, data-html links to language images are incorrect/broken

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#17593]
Branch develop
php8, local server (Laragon) Windows

Can't say I quite understand what the data-html tags are doing, but I don't think the src link structure should be in there!

![Clipboard01](https://user-images.githubusercontent.com/4391026/118040166-880a8800-b371-11eb-8f1b-d56838dee4d0.gif)

**Comment by torvista** [comment]
This is being generated here:
https://github.com/Dolibarr/dolibarr/blob/a9ddf2a5ad51be91b2769fdbcf6595fa8db5457b/htdocs/core/class/html.formadmin.class.php#L132-L135

Can someone explain the use of data-html here?

Added here:
https://github.com/Dolibarr/dolibarr/commit/6c65ebef0d2ea9870711572ce30dd25723a2bbd6#diff-c2baa872e188f1c692d365f187f0cebe39b938dd556a1ba67a7f0f0f73bc6421

**Comment by torvista** [comment]
So, no-one else understands what is the intention here?

**Comment by torvista** [comment]
Dolibarr 22/05/2021: 789 issues...361 open bugs. Looks like more contributors are needed.
I would normally contribute to any project I use, but not if it means guessing solutions.
Some community response is required here please.....

**Comment by daraelmin** [comment]
Hi,

I think the problem is not related to data-html  but to a wrong path for the flags images.

The images path should be something like "dol_htdocs_URL/theme/common/flags/..." not "/theme/common/flags/..."

But when installing, the dol_htdocs_URL may not be already define... So the only way I guess is to use "**../**/theme/common/flags/..." or just remove the flags. 

If I could choose,  I'll say it would be better to remove the flags as the relative path may cause more bug and the gain in design is really low as this page should be used only once.

**Comment by daraelmin** [comment]
As far as I know data-html is a custom attribute to be able to use html tag inside the option value.

A little Explaination for data-html could be fond here  : 
https://www.w3schools.com/tags/att_data-.asp#:~:text=The%20data-*%20attribute%20gives,server-side%20database%20queries).

But most important point is "Custom attributes prefixed with "data-" will be completely ignored by the user agent".

**Comment by torvista** [comment]
Firstly, thanks for taking the time to respond.

> But most important point is "Custom attributes prefixed with "data-" will be completely ignored by the user agent".

That is exactly my question....just what is the point of the data-html in the first place? I don't see anything that may use it.

Someone had the idea to display the flags next to the language name but didn't finish it?

I picked this error as an example for a potential employee to try out their programming skills and fix it....not because it is important. But, it seems to be a bad example if it has crept into the project unfinished/has no use at all....???

**Comment by daraelmin** [comment]
> Someone had the idea to display the flags next to the language name but didn't finish it?
> 
> I picked this error as an example for a potential employee to try out their programming skills and fix it....not because it is important. But, it seems to be a bad example if it has crept into the project unfinished/has no use at all....???
> 

I don't think someone didn't finish the job. I think the path is not define cause the constant path for URL is not define when installing. 

In all other configuration page of the soft it works cause the constant is define during the installation.

**Comment by daraelmin** [comment]
EDIT : should work on all part. (I haven't tested this)

**Comment by daraelmin** [comment]
If you're looking for issue to solve as test try labels

"good first issue" : https://github.com/Dolibarr/dolibarr/issues?q=is%3Aopen+is%3Aissue+label%3A"good+first+issue"

Or

"hacktoberfest-accepted"
https://github.com/Dolibarr/dolibarr/labels/hacktoberfest-accepted

Cheers

**Comment by daraelmin** [comment]
> That is exactly my question....just what is the point of the data-html in the first place? I don't see anything that may use it.

For security reason, dolibarr doesn't store html code in database and reject html tag as data. So html codeis encoded as string. 

A JQuery script decode all value of element with data-html attribute on client machine just to display it correctly but the "real" value remain encoded to be sure it womt be rejected when sending the form.

**Comment by daraelmin** [comment]
JQuery script printed on page with data-html

`<!-- JS CODE TO ENABLE select2 for id = main_lang_default --> <script> 	$(document).ready(function () { 		$('#main_lang_default').select2({ 		 dir: 'ltr', 			width: 'resolve',		/* off or resolve */					minimumInputLength: 0,					language: select2arrayoflanguage, 				containerCssClass: ':all:',					/* Line to add class of origin SELECT propagated to the new <span class="select2-selection...> tag */					selectionCssClass: ':all:',					/* Line to add class of origin SELECT propagated to the new <span class="select2-selection...> tag */					templateResult: function (data, container) {	/* Format visible output into combo list */	 					/* Code to add class of origin OPTION propagated to the new select2 <li> tag */						if (data.element) { $(container).addClass($(data.element).attr("class")); }					 //console.log($(data.element).attr("data-html"));					 if (data.id == -1 && $(data.element).attr("data-html") == undefined) {							return '&nbsp;';						}						if ($(data.element).attr("data-html") != undefined) return htmlEntityDecodeJs($(data.element).attr("data-html"));		// If property html set, we decode html entities and use this						return data.text;					},					templateSelection: function (selection) {		/* Format visible output of selected value */						if (selection.id == -1) return '<span class="placeholder">'+selection.text+'</span>';						return selection.text;					},					escapeMarkup: function(markup) {						return markup;					},					dropdownCssClass: 'ui-dialog'				});});</script>`

**Comment by torvista** [comment]
Thanks for the very useful info, I'll look into it further when I have time.

**Comment by cfoellmann** [comment]
I would vote to remove flags at that point to remove the bug.

+ Close the issue with the PR
