### ISSUE TITLE
Amélioration de l affichage /edition du plan de table

### ISSUE THREAD

**Issue by webmasterproxy-media** [Dolibarr/dolibarr#17605]
https://www.dolibarr.fr/forum/t/plan-de-salle-takepos/35165

**Comment by ksar-ksar** [comment]
Hello,

Could you please write in English ?

**Comment by ingprod** [comment]
> Hello,
> 
> Could you please write in English ?

Hello everyone,

I'm using the Takepos module with the restaurant option in Dolibarr 18.0.4.
Thank you for your greate contribution on this module, the POS part is working perfectly.
However, the feature of "Defining the table layout" in Bar & restaurant seems to be broken.
When creating the seating plan: 
1- Only adding new tables is available (through each floor)
2- Impossible to edit/see all the tables to position them as before the bug
![image](https://github.com/Dolibarr/dolibarr/assets/16608548/4fb630f4-35d0-4fde-99fd-657bd87aaa09)

3- When clicking on the "Emplacement" button on the POS is does display only the last created table for each floor. Editing allow only to add new tables
![image](https://github.com/Dolibarr/dolibarr/assets/16608548/bc4238b1-2748-4758-804b-514539dda74b)
![image](https://github.com/Dolibarr/dolibarr/assets/16608548/248f907f-8d34-4a56-95a5-ef7eda29a7a5)

So it's impossible to manage.
It's also impossible to display order comments on the order ticket.
I'd appreciate it if you could mark the assigned tables on the seating plan.
If anyone has a solution, I'd love to hear from you.


Thank you for you effort
Cheers
