### ISSUE TITLE
Bug: WARNING err = is_dir()

### ISSUE THREAD

**Issue by ArnaudFR67** [Dolibarr/dolibarr#17625]
# Instructions
*Warning: is_dir(): open_basedir restriction in effect. File(/9) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 102*

# Bug
[Warning Error : How can I solve it]

## Environment
- **Version**: 13.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) PHP/7.3.12
- **PHP**: apache2handler 7.3.12
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB
- **URL(s)**: /dolibarr/projet/element.php?id=7

## Expected and actual behavior
[I have this message in Project]
![Capture d’écran 2021-05-16 184348](https://user-images.githubusercontent.com/81926163/118405181-d6bc6880-b676-11eb-81f3-a003734fadc7.png)
]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

This is related to how you have installed Dolibarr and your PHP configuration : Please give details
Not a bug, but a configuration issue.
Please create a topic on forums : https://www.dolibarr.org/forum.php

**Comment by ArnaudFR67** [comment]
Hello : 
Installation with DoliWAMP
PHP:
Version | 7.3.12
GET and POST support | Ce PHP prend bien en charge les variables POST et GET.
Sessions support | Ce PHP prend en charge les sessions.
UTF-8 support | Ce PHP prend en charge les fonctions UTF8.

Is this helpfull?

**Comment by DoliFRAP67** [comment]
> Hello,
> 
> This is related to how you have installed Dolibarr and your PHP configuration : Please give details
> Not a bug, but a configuration issue.
> Please create a topic on forums : https://www.dolibarr.org/forum.php

Topic created on the forum 👍 
URL :
https://www.dolibarr.fr/forum/t/warning-is-dir-open-basedir-restriction-in-effect/37709
Migration from v13 to v14 did not solve the problem
