### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ArnaudFR67** [Dolibarr/dolibarr#17627]
# Instructions
- *No picture appears in "photo" space of the supplier*
- *That is the same if I put my picture by loined pieces*

# Bug
[*No picture*]

## Environment
- **Version**: 13.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) PHP/7.3.12
- **PHP**: apache2handler 7.3.12
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB
- **URL(s)**: /dolibarr/societe/card.php?socid=66&save_lastsearch_values=1

## Expected and actual behavior
[*I try to re enter the picture using supplier form  : no change*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[![Capture d’écran 2021-05-16 185550](https://user-images.githubusercontent.com/81926163/118405555-d3c27780-b678-11eb-9ec5-6dd56b8649e4.png)]

**Comment by atm-maxime** [comment]
Hi !
Thanks for your report. I can't reproduce on my side with the latest 13.0. Can you check the permissions on your "documents" folder ? When you add a file in the attachments tab it works ?
