### ISSUE TITLE
API  : get donation 503

### ISSUE THREAD

**Issue by r3dge** [Dolibarr/dolibarr#17637]
hi,

I am trying to get donations using API. Unfortunately i encountered an HTTP 503 error code.

CURL request : 

curl -X GET --header 'Accept: application/json' --header 'DOLAPIKEY: XXXXXXXXXXXXXXXXXX' 'https://MYDOMAIN.FR/api/index.php/donations?sortfield=t.rowid&sortorder=ASC&limit=100'

Result : 

{
    "error": {
        "code": 503,
        "message": "Service Unavailable: Error when retrieve donation list : **Unknown column 'sc.fk_soc' in 'field list'**"
    },
    "debug": {
        "source": "api_donations.class.php:161 at call stage",
        "stages": {
            "success": [
                "get",
                "route",
                "negotiate",
                "authenticate",
                "validate"
            ],
            "failure": [
                "call",
                "message"
            ]
        }
    }
}

**Comment by ksar-ksar** [comment]
Hello,

What is your dolibarr version ?

**Comment by r3dge** [comment]
The version version is v.13.0.2

**Comment by r3dge** [comment]
This issue seems to be due to the permissions granted to the related user.

Workaround found : enabling the following permissions : third-parties/Read third parties linked to user & third-parties/Read contacts

After enabling this permissions the query works.

**Comment by mathieufrh** [comment]
I have faced the same issue on Dolibarr 15.0.3-4 on Debian 12.5. With enough permissions, the API query is working. A lack of permissions should **NEVER** raise an exception and return a 5xx HTTP code. This issue should be addressed, not silenced.
