### ISSUE TITLE
Missing translations in the user info dropdown

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#17634]
In the user dropdown, some translations are missing. These are in the "companies" lang file. Where should we include this langs ?
![image](https://user-images.githubusercontent.com/2097773/118492785-a9c49000-b720-11eb-8f3f-73161f739de7.png)

**Comment by frederic34** [comment]
@atm-maxime is your dolibarr dev uptodate ? https://github.com/Dolibarr/dolibarr/pull/17567/files

there were a missing $mysoc

![image](https://user-images.githubusercontent.com/3624836/118496539-813e9500-b724-11eb-8619-aefbcc3112ba.png)

**Comment by atm-maxime** [comment]
Hi @frederic34 ! Sorry I didn't saw your answer.
The issue is not linked to $mysoc. I am on a Dolibarr with the thirdparty module not activated. In this case, the lang file "companies" is not loaded", so mysoc informations are not translated.

**Comment by cfoellmann** [comment]
I can not reproduce this.
Maybe you can overwrite the `langs/` folder with the current data.

**Comment by atm-maxime** [comment]
Install a fresh 14.0.2, don't activate the Thirdparty module and you'll see it's not translated

**Comment by cfoellmann** [comment]
CLOSE
