### ISSUE TITLE
rights issue on leave vacation request

### ISSUE THREAD

**Issue by Crush33** [Dolibarr/dolibarr#17633]
# Bug (regression?)

## Environment
- **Version**: since v13 ?
- **OS**: debian 9
- **Web server**: apache2
- **PHP**: 7.0
- **Database**: mariadb
- **URL(s)**: /dolibarr/holiday/list.php

## Expected and actual behavior
user with all the "Leave requests" rights should be able to see all the requests.

## Steps to reproduce the behavior
give all the rights to a user (line manager)
the line manager can no longer see the leave requests even if he has the right to see all the leaves.

---

un utilisateur avec tous les droits "demande de congés" pouvait (avant v13) voir toutes les demandes de congés et y répondre.
Depuis v13 il doit être responsable hiérarchique des personnes pour accéder à ce droit.

**Comment by gmilad** [comment]
(English below)
Bonsoir,

Il faut aller configurer les droits pour l'utilisateur/le groupe : 

![image](https://user-images.githubusercontent.com/61253440/119385027-da2ea000-bcc5-11eb-90cf-ba256dbcd47d.png)

Cordialement,
Gaëtan.

Good evening,

You have to configure the rights for the user/group: 

![image](https://user-images.githubusercontent.com/61253440/119385027-da2ea000-bcc5-11eb-90cf-ba256dbcd47d.png)

Sincerely,
Gaëtan.
