### ISSUE TITLE
Advanced filtering for number types extrafield KO

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#17649]
# Bug
It's no more possible to set and advanced filter (like ">100", ">100 <1000") on number (int double real price) extrafield in a list page
If you enter ">100", system keeps only "100" and filter only values equal to 100

## Environment
- **Version**:All versions

**Comment by vmaury** [comment]
FIX : I'll soon propose a pull request on /htdocs/core/class/extrafields.class.php
Replace lines 2217-2218:

`$value_arr = GETPOST($keysuffix."options_".$key.$keyprefix);`
`$value_key = price2num($value_arr);`
By 
`$value_key = GETPOST($keysuffix."options_".$key.$keyprefix);`

The `price2num` function is ok for security but deletes all _special_ chars like >, < spaces, VERY usefull in filters

**Comment by TheGivrix** [comment]
Can you tell me on which page you got the bug. All listing pages ? Cause I don't have this bug personally. (I tried on /fourn/facture/list.php page)

**Comment by SVGAnimate** [comment]
Hello,

vmaury, what about : `">1,99"` or `"<1'000"`

**Comment by vmaury** [comment]
The bug occurs on all listing pages... but only for extrafields, for normal fields advance filtering is ok
I solved the bug on my instance by removing the price2num call, cf my fix above

**Comment by SVGAnimate** [comment]
The filter value is no longer displayed.
see https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/class/extrafields.class.php#L1166

**Comment by eldy** [comment]
I can't reproduce the trouble. I test with ">100" filter on last version into branch v13 and develop and the filter is correctly applied.
