### ISSUE TITLE
for extrafield list type, required option is ignored

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#17647]
# Bug
For an "list type" extrafield, an empty value should not be proposed when editing

## Environment
- **Version**: All versions

**Comment by Hystepik** [comment]
Sorry, but I don't understand why it should not be proposed empty. If you want the user to fill it you need to make it required.

**Comment by Hystepik** [comment]
I think the field need to be blank to make sure the user has filled it on by himself with his answer.

**Comment by eldy** [comment]
As said by @Hystepik , there is a difference between "mandatory" and "first value must be automatically selected in combo list".
We must keep the empty value so the combo is not automatically selected on first value (except if a default value exists, in such a case we can auto select on it). The user must choose by himself.
The mandatory status will be checked by backoffice too.
