### ISSUE TITLE
Issue encoding in ODT template since v13

### ISSUE THREAD

**Issue by Crush33** [Dolibarr/dolibarr#17653]
since v13, encoding seems wrong in ODT template files.
exemples :
`< br />` are displayed in end of each line
`à` accent are displayed as `&#39;&agrave;`

it doesn't seem to me that we had any problem in v12...

**Comment by gmilad** [comment]
(English below)
Bonsoir,

J’arrive à reproduire le des '< br / >' c'est l'éditeur WYSIWYG qui les rajoutes (testé sur une version 12.0.4 et sur la version en cours de développement) par contre je n'arrive pas à reproduire le problème pour les accents j'ai mis en note çàéè et ça s'est bien affiché dans le fichier ODT d'exemple, voir peut-être un problème de charset.

Pouvez-vous nous donner plus d'informations sur votre installation de Dolibarr.

Cordialement,
Gaëtan.


Good evening,

I can reproduce the '< br / >', it's the WYSIWYG editor that adds them (tested on a 12.0.4 version and on the version under development) but I can't reproduce the problem for the accents, I put çàéè in the note and it's well displayed in the ODT example file, maybe it's a charset problem.

Can you give us more information about your Dolibarr installation.

Sincerely,
Gaëtan.

**Comment by atm-maxime** [comment]
Maybe you just activated the wysiwyg module in v13 and it's not compatible with odt models to my knowledge
