### ISSUE TITLE
Bug: Incorrect date value for column extrafield date required

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#17652]
# Bug
Il try create extrafield date required en societe with name fecha_cierre and shows error: Incorrect date value: '0000-00-00' for column 'fecha_cierre' at row 1.
Then i created without required and Ok, later I modified with option required and show error: Invalid use of NULL value.

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.28
- **Database**: MySQL or MariaDB 5.7.34
- **URL(s)**: /societe/admin/societe_extrafields.php

**Comment by SVGAnimate** [comment]
Hello leninrivas, you-all

"Incorrect date value" is a SQL error message.
For more technical information, and quick fix, you can read this link : https://stackoverflow.com/questions/36374335/error-in-mysql-when-setting-default-value-for-date-or-datetime/36374690#36374690

Could you indicate which version of Dolibarr you are using ?
I'm using Dolibarr 14.0 and i see a field named "Default value"

There is a good chance that if you specify a default value, the error no longer occurs. In your case: 2200-00-00 can be a good choice.

I think that the default value field should be made mandatory if the "required" field is checked.

What do you think, you other? 


Kind regards,
Serge

**Comment by leninrivas** [comment]
Updated 14.0.0 Ok
