### ISSUE TITLE
Cannot delete inventory after upgrade 12->13

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#17666]
# Bug
get error when trying to delete inventory

## Environment
- **Version**: 13.0.2 (upgraded from 12.0.5)
- **URL(s)**: http://dolibarr.localhost/product/inventory/card.php?id=2&action=confirm_delete&confirm=yes&token=%242y%2410%24.AVHkaCBe.Q1kHIPHuXHre4CQLBtQ%2FjZFfT8ysdtDEHJUqUQC0iTC

## Expected and actual behavior
deletion expected, got error
![image](https://user-images.githubusercontent.com/68460690/118723480-c69ab980-b82d-11eb-9b81-afb33f2678bf.png)

## Steps to reproduce the behavior
install 12.0.5
create inventory
upgrade
try deleting the inventory

The error is correct, there is no table with that name:
![image](https://user-images.githubusercontent.com/68460690/118723666-fd70cf80-b82d-11eb-841a-f05c4a046d71.png)

**Comment by atm-maxime** [comment]
Inventory is not a stable feature on v12 or v13.

**Comment by dpriskorn** [comment]
I know. I hope to be able to contribute to make it so 😃

**Comment by atm-maxime** [comment]
Thanks, but check the 14 beta version, inventory is now a stabilized feature 😉

**Comment by dpriskorn** [comment]
Fantastic! I'll close this as I assume it's a won't fix 😃
