### ISSUE TITLE
Missing support of chkbxlst in commonobject.class & modulebuilder.class

### ISSUE THREAD

**Issue by kubajznik** [Dolibarr/dolibarr#17679]
I developed an own module. I added a field (no extrafield, directly in module) of type "chkbxlst". It didn't work.

I found in commonobject.class, that it is being checked for "sellist" but not for "chkbxlst". (functions showInputField & showOutputField)
The fix was pretty easy - I added the respective code, basically copy & paste of "sellist".
The same applies for modulebuilder.class, there the functions rebuildObjectClass and rebuildObjectSql need the update.

Is there a reason, why this was missing or was it by mistake?
Otherwise, happy to share my solution ...

Cheers Kuba
![image](https://user-images.githubusercontent.com/35335130/118842875-d8319f00-b8c9-11eb-8bdf-b4c6f064b78f.png)
![image](https://user-images.githubusercontent.com/35335130/118842931-e1bb0700-b8c9-11eb-8a7a-74d42fd28085.png)

**Comment by mohameduk** [comment]
hi can you please share the modification in the functions rebuildObjectClass and rebuildObjectSql because I did the same as selllist the input work but no date saved in the data base

**Comment by mstoluca** [comment]
EN LAS VERSIONES 16 SIGUE ESTANDO ESE ERROR O FALTA DE PROGRAMACION

**Comment by aluquerivas-dev** [comment]
> EN LAS VERSIONES 16 SIGUE ESTANDO ESE ERROR O FALTA DE PROGRAMACION

Efectivamente aun falla.
