### ISSUE TITLE
API Calls Do Not Trigger Business Events

### ISSUE THREAD

**Issue by carmelchas** [Dolibarr/dolibarr#17681]
# Trigger execution in API functions.

# Feature Request
 Is it a standard for all API functions to skip trigger execution?

Is there a document that explains the standards for what is allowed related to triggers and API functions?

## Use case
For example, I create a product using the API, but my trigger for PRODUCT_CREATE does not execute. Upon inspection I see that the out-of-the-box API function calls “$this->product->create(DolibarrApiAccess::$user)” without the second argument “$no_trigger” or any way to affect whether or not to execute the trigger(s).

**Comment by atm-maxime** [comment]
There's no reason triggers are not executed after API calls. How can you tell ? Did you activate and check the Dolibarr log to see if the trigger is called ?

**Comment by carmelchas** [comment]
Actually.. I need to check to confirm, but it may just be the contacts update ( contacts PUT) method that does not call triggers.  See the call to update below passes the third argument hard-coded as "1" which instructs the contact class's update function to NOT execute triggers.  Perhaps this is a bug.

# htdocs/societe/class/api_contacts.class.php
...
public function put($id, $request_data = null)
{               
              ... code before ...            
                                        
                if ($this->contact->update($id, DolibarrApiAccess::$user, 1, '', '', 'update'))
                        return $this->get($id);         
                                                             
                return false;                           
 }
        
 ...     
 
 # htdocs/contact/class/contact.class.php
        public function update($id, $user = null, $notrigger = 0, $action = 'update', $nosyncuser = 0)
        {
                       ...
                        if (!$error && !$notrigger)
                        {
                                // Call trigger
                                $result = $this->call_trigger('CONTACT_MODIFY', $user);
                                if ($result < 0) { $error++; }
                                // End call triggers
                        }
                        
                         ...
        }

**Comment by carmelchas** [comment]
It does appear to only be the contact API class that does not execute triggers for updates via API.

**Comment by rycks** [comment]
Same problem for me with invoices: make a pdf via API call (builddoc) -> there is no trigger !
