### ISSUE TITLE
Invoice from order can be duplicated when shipment is created

### ISSUE THREAD

**Issue by bebenbouv** [Dolibarr/dolibarr#17696]
Hi,

An invoice linked to an order can be duplicated when order is shipped. The button "create invoice" from shipment page is visible even if an invoice of same amount already exists.

Example : 
An order (50€ HT) is created with the "validated" status. No shipment exists.
On the order page we click on the button "create invoice" and go through the invoice process. The invoice is now created (50€ HT) and the order status is "validated - invoiced" 
Few days latter we create the shipment for this order. we go through the shipment process. The shipment is now created (50€ HT). We can see in the "linked objects" that the order is displayed, not the invoice.
On the shipment page we see a button "create invoice" even if there is an invoice already. If we click on that button, we are able to create a second invoice for the same order which leads to a duplicate. No warning message is displayed to inform the user that this new invoice might be a duplicate.

## Environment
- **Version**: 13.0.2
- **OS**: Linux - apache - mariadb

## Expected and actual behavior

Hide the "create invoice" button from shipment page if an invoice (at least of full order amount) already exists for the related order.
Show invoices created before shipment in the "linked objects" section of the shipment.

Thank you for your help and hurray for dolibarr :)

**Comment by toni-mx** [comment]
In addition to this it would be helpful if you can link invoices to shipments and vice versa  same case in supplier module.
