### ISSUE TITLE
Official build on Docker Hub

### ISSUE THREAD

**Issue by SecT0uch** [Dolibarr/dolibarr#17694]
# Feature Request
Would you consider to provide official image on Docker Hub?

**Comment by SecT0uch** [comment]
Keep that open bot!

**Comment by SecT0uch** [comment]
Nope. No answer yet.

**Comment by yledoare** [comment]
We need to pay a plan on docker hub to build images
It can be discussed at next devcamp

**Comment by SecT0uch** [comment]
Actually any docker repo would be great

**Comment by yledoare** [comment]
to be validated with @eldy

**Comment by yledoare** [comment]
Hello, the request to use a docker hub account was not validated by the core team. Maybe in the future 

I wrote some code to generate docker images : https://github.com/yledoare/docker-images
Images are put [here ](https://jukebox.linuxconsole.org/docker/)
You can test it (for dolibar17) with this code : https://github.com/yledoare/docker-images/blob/master/dolibarr-17/test.sh

Regards

**Comment by marclaporte** [comment]
> We need to pay a plan on docker hub to build images

Criteria should be reviewed for "Docker-Sponsored Open Source Program"
https://www.docker.com/community/open-source/application/

**Comment by yledoare** [comment]
Thanks @marclaporte for this link
@FHenry , we maybe also request for https://hub.docker.com/u/dolibarr user

**Comment by SecT0uch** [comment]
Seems like we've got it: https://hub.docker.com/r/dolibarr/dolibarr

**Comment by yledoare** [comment]
https://hub.docker.com/r/dolibarr/dolibarr/ seems to be managed with [tuxgasy](https://github.com/tuxgasy) not the official Dolibarr team
In last build we can see tag was set with https://hub.docker.com/u/dolibarrasso .. What is this account ?

**Comment by SecT0uch** [comment]
After double-checking https://hub.docker.com/r/dolibarr/dolibarr/ is managed by the official Dolibarr team since it is [linked in the README](https://github.com/dolibarr/dolibarr#using-docker-images)
