### ISSUE TITLE
Error on phpMyAdmin import of US-BASE llx_accounting_account_us.sql 

### ISSUE THREAD

**Issue by rotor-head** [Dolibarr/dolibarr#17708]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Unknown column '__ENTITY__' in 'field list' 

## Environment
- 13.0.2 
- Debian 10.7
- Apache 2.4.46
- PHP 7.3.25
- phpMyAdmin 5.0.4 
- Maria DB 5.7.32
- n/a
- 
## Expected and actual behavior
Import US based chart of accounts

## Steps to reproduce the behavior
1. scp llx_accounting_accounts_us.sql to Desktop of workstation.
2. ssh -N -L 8888:127.0.0.1:80 -i 'userkeyfile' user@SERVER-IP
3. open http://localhost:8888/phpMyAdmin from local browser 
4. log in to phpMyadmin with root pass
5. navigate to Import tab, select .sql file from Desktop, run import

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by rotor-head** [comment]
Just to clarify, you mean a more recent version of phpMyAdmin? Happy to test and report back my findings.

**Comment by dolibit-ut** [comment]
Hello

Why are you re-importing the file?
Was something wrong / missing before?

**Comment by dolibit-ut** [comment]
By the way - your PHP version (5.0.4 ?) is very outdated!
Maybe a problem - because Dolibarr 13 only likes PHP 5.6+

**Comment by rotor-head** [comment]
My mistake. Actually, it's phpMyAdmin that is at 5.0.4. Thanks for bringing that to my attention. I've edited the original post and corrected + updated it, corrected the Mariadb version, and added the PHP information.

Originally, I had a CoA specific to our business. I followed the Excel template to build out the file for import, but that failed to import. That sent me digging through the documentation and forums for some guidance and found a thread about creating an English based CoA here: https://www.dolibarr.org/forum/t/how-to-get-an-english-chart-of-accounts/15879. The post gave some insight into the SQL work on the database side. 

The US-BASE was not an option in the web interface Chart of Accounts selection, but with the information gleaned from the various forum posts and navigating Github repo, I uncovered the .sql file noted above.

**Comment by rotor-head** [comment]
I stood up a new installation on a Debian 10.x VM. After working through getting mariadb root password set properly, the install completed without issue.

After the initial configuration of Company details and Module selections, I see both the US-BASE and CA-ENG-BASE charts are visible.

Given this is a new installation and the low possiblity of an older installation needing this to work, this issue is moot.

.
