### ISSUE TITLE
Donations : bug with rest api POST

### ISSUE THREAD

**Issue by r3dge** [Dolibarr/dolibarr#17700]
# Bug
Any donations creation using REST API (POST) send 500 error code without any error message. Viewing Apache error.log i saw an error : 
"[Fri May 21 14:00:39.753768 2021] [php7:error] [pid 864] [client 127.0.0.1:45064] PHP Fatal error:  Uncaught Error: Class 'Orders' not found in /var/www/html/dolibarr/htdocs/don/class/api_donations.class.php:358\nStack trace:\n#0 /var/www/html/dolibarr/htdocs/don/class/api_donations.class.php(182): Donations->_validate()\n#1 [internal function]: Donations->post()\n#2 /var/www/html/dolibarr/htdocs/includes/restler/framework/Luracast/Restler/Restler.php(1071): call_user_func_array()\n#3 /var/www/html/dolibarr/htdocs/includes/restler/framework/Luracast/Restler/Restler.php(308): Luracast\\Restler\\Restler->call()\n#4 /var/www/html/dolibarr/htdocs/api/index.php(298): Luracast\\Restler\\Restler->handle()\n#5 {main}\n  thrown in /var/www/html/dolibarr/htdocs/don/class/api_donations.class.php on line 358, referer: http://localhost/dolibarr/htdocs/api/index.php/explorer/"

A wrong reference to "Orders" class is done instead of "Donations" class. As Orders class is not specified that throws an exception. 

# Proposed fix 

in htdocs/don/class/api_donations.class.php : 

- line 358 : replace Orders::$FIELDS by Donations::$FIELDS
- line 35 : add required static fields. Example : 	static $FIELDS = array('amount');

## Environment
- **Version**: 13.0.2
- **OS**: Lubuntu 20.04
- **Web server**:  Apache
- **PHP**: 7.4.3
- **Database**: Mysql 8.0.25
- **URL(s)**: donations

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
