### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by madhupsrivastava** [Dolibarr/dolibarr#17709]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Categories are not available while creating Vendors. Secondly, the Vendor list is not showing up.

## Environment
- **Version**: 12.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.3.27
- **Database**: MySQL or MariaDB 5.7.34
- **URL(s)**: /societe/list.php?type=f&leftmenu=suppliers

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Did you create the categories before trying to create the vendor ?
What means the "vendor list is not showing up" ?
Some screenshots might help understand your issue

**Comment by daraelmin** [comment]
Try also to upgrade to 12.0.5

**Comment by cfoellmann** [comment]
@madhupsrivastava Can you please follow up on the suggestions by @atm-maxime and @daraelmin ?
Close if fixed in the latest minor release or post some more data. Like screenshots.

Time for bugfixes in 12.x is running out!! Or plan for an update to 13.x or later

**Comment by madhupsrivastava** [comment]
Hi,

Close this. This is all good.
Peter S.
M+61 0479 160 265

**Comment by cfoellmann** [comment]
You can close this
