### ISSUE TITLE
Module Manufacturing Process (MP)

### ISSUE THREAD

**Issue by atm-thibaultf** [Dolibarr/dolibarr#17715]
# Feature Request
Creation of a module to define the chronological order of the required steps to manufacture a product.

## Use case
Dolibarr v14 proposes several modules to manage production process :
- Bills Of Materials (BOM) - Stable - Allows to define the composition of a product. Components can be products or services.
- Manufacturing Order (MO) - Stable - Allows to produce a product from a BOM to decrease the stock of the components and to increase the stock of the final product.
- Workstation - Development - Allows to define a workstation and to link it to an user group and/or ressources.

None of the modules above allow to define the chronological order of the different steps required to manufacture a product. A  Manufacturing Process (MP) module could be added to define such a process.

## Suggested implementation
The Manufacturing Process module should do the link between the BOM/workstation modules and the MO module. Indeed, the MP module should offer an interface to define several steps and to link a workstation and several products (from a BOM) to each step. A unique MP could be linked to several BOM.
Finally, the MP module should allow to create a MO directly from a MP.

## Suggested steps
The form to create a MP should propose the fields below :
- Label (required)
- Description
- Version

Once the MP is created, the MP card should offer :
- an interface to add several steps (like we add product on a propal for example). The line to add a step should propose the fields below :
-> Number (number to order the step) - Autofilled by the next number available (still editable)
-> Label (required)
-> Workstation : select list (unique) from the existing workstations
-> Description
-> A "Add button"
- an interface to add one or several BOM(s). A select field should propose the list of the existing BOMs and a "Add button". Once the BOM is added, the interface should propose a table with the list of products/services existing in the BOM. It should be possible to define the number of the step (above) associated to each product / service.

Finally, the MP card should propose a tab (called "Production available" for example) which display the list of the production available. This view could be readable only and propose for each BOM the list of the steps with the workstation and the products/services associated. For each BOM, a button "Create MO" should propose to create a MO from the MP card tab.

**Comment by edupulpillo** [comment]
Very useful, please take care about the serial numbers/lots feature on it.

**Comment by atm-thibaultf** [comment]
I think the serial numbers/lots feature should not be involved in the manufacturing process module because we define here the steps of the process. At this stage, we don't know yet what serial numbers/lots will be used to finally manufacture the product. The serial numbers/lots feature should be used in the manufacturing order like it's already existing when we define what serial numbers/lots will be used to manufacture the product.

**Comment by edupulpillo** [comment]
Hi. I mean the serial numbers of the manufactured products. 
When you manufacture something, the last step oftenly is the packing and the serial number assignation to each item.
Sometimes laser engraving in the cases, software recording numbers, and labels detailing the serial number of each item.
Sometimes the products produced no need serial numbers, and sometimes  each product produced need to have a serial number as a requirement.
Also if the components of the BOM used to manufacture something have serial numbers, would be nice to track the serial numbers of the components of a produced item.
For example is very useful for aftersales services.
Example: We manufacture a TV that use a power supply. then if the power supply fails, we can track the serial number / lot of the powersupplies that can fail.

So then as you said: In the manufacturing order, it should be detailed the serial numbers required, that aftermanufacturing can be updated (sometimes the serial numbers produced are not exactly as was planned at the beginning)
And the components used for production, also can specify the serial numbers in their BOM list (but not one by one of course, in ranges "from/to", should be very nice.

**Comment by atm-thibaultf** [comment]
Hello,

I understand what you said. For now the link between the true final manufactured product (with its serial numbers if required) and the true components used to manufacture (also with serial numbers if required) is done in the Manufacturing Order and it's already available in Dolibarr v14 (from v12 I think). I think it's the good place to do this job and to track the serial numbers correctly because it's where we surely define the serial numbers of each one (the final products and the components).

The manufacturing process module should not involved serial numbers as we just define in it the steps of the production and not the true products (or components) which will be used for the real production.

I understand the need to allow to define a range of serial numbers (from/to) that can be used to manufacture a specific product and I agree it could be very usefull but I think it's something to add in the BOM module (as you said) or maybe in the manufacturing order module. That's why I said the serial numbers featured should not be involved in the new MP module.

**Comment by eldy** [comment]
If a MP contains several BOM, it means that when you convert a BOM into a MO, you will get several MO ? So we must also have a relation Mo has this MO as parent.
And a new status "pending" for MO to say we wait parent mo before starting chield MO. 
Also it is planned to manage "cascading Bom", with a Mo that has a parent Mo (and a BOM that can consume another BOM). So the MP could be genrated by selecting several independent BOM or by selecting one final BOM that includes other BOM to consume.

**Comment by edupulpillo** [comment]
Hi both, and thank you so much for following this topic.
@atm-thibaultf When you said.... "The manufacturing process module should not involved serial numbers as we just define in it the steps of the production and not the true products (or components) which will be used for the real production." this thoughts:
Got it and I agree that maybe in the MO where the serial numbers should be specified, but since the serial number assignation of the produced items is in fact one of the latest steps of the manufacturing, it will be nice to know and track wich MO produce an item with a specific serial number. Also kindly keep in mind that the live is not perfect during manufacturing, and the serial numbers planned and the really produced maybe differs.

@eldy Really "cascading Bom" is exactly what we need, and the new status "pending" is nice. We hope will be implemented soon, it will be great!!! and will make really useful the current MO/MP/BOM modules. 
Maybe MP can be considered just a BOM list with service steps inside in chronological order?

Besides that, should be very nice to:
- Manage the serial numbers/lots of the items produced (as one step of manufacturing process) what is the MO that belongs, for better traceability.
- Manage serial numbers/lots of the components used to produce a new item manufactured  (serial numbers of the components used to produce a new product) for better traceability.

**Comment by atm-thibaultf** [comment]
Hi,

Thank you both for your feedback. 

@eldy when you say that "it is planned to manage "cascading Bom"", could you tell us what is planned exactly ? Indeed, we are also thinking of developing something around this feature because we need to anticipate this feature for the MP module. That's why if something is already planned, it should be interesting to know what is planned. Is there a specification about this "cascading BOM" feature or is it just in concept state for now ?

Finally, for the MP module, I would like to be sure we are align of what we are talking about. The MP module will come between the BOM & Workstation module in one side and the MO module on the other side. MP will provide an additonnal feature to define the chronological steps of the manufacturing process (including products from BOM but also workstation from the workstation module). We will have the following process : **BOM / Workstation => MP => MO**. The final long term objectif is to be able to provide a planning module based on the ressources (machine and human) including in the workstation module. We would have to include some workstation informations into the MO module for that.

It will be still possible to create a MO from a BOM as it is alreday possible for user who don't want to use MP module : **BOM => MO**

**Comment by atm-thibaultf** [comment]
Replace by this issue #19661
