### ISSUE TITLE
Accounting - Setup - General (double entry)

### ISSUE THREAD

**Issue by biodland** [Dolibarr/dolibarr#17711]
Dolibarr 13.0.2

The toggle buttons have wrong link attached to them.

for instance;
/accountancy/admin/index.php?token=...&managezero&value=0
should be
/accountancy/admin/index.php?token=...&setmanagezero&value=0

This also is some of the other radio buttons.

**Comment by daraelmin** [comment]
Witch setup?
Could you copy/paste theconcerned URL and maybe dôme screenshot please?

**Comment by biodland** [comment]
Hi

Under Accounting -> Setup -> General
All the toggle switches does not seem to work properly.
Don't have enough experience with PHP to understand what is wrong in the source it self, but if I just change the link query field managezero to setmanagezero it works. (as per the index.php's IF $action testing suggests).

![image](https://user-images.githubusercontent.com/28107493/119895703-60edb200-bf3e-11eb-958f-3f70d6dba63f.png)
![image](https://user-images.githubusercontent.com/28107493/119895833-81b60780-bf3e-11eb-9aeb-8b7cf303a73b.png)

**Comment by aspangaro** [comment]
It's seems to work now
