### ISSUE TITLE
supplier order -> refuse + (Add) field for refusal cause

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#17727]
# Feature Request
We would like to add a text field to the dialog box for confirming the refusal of a supplier order.

`Cause: <textfield>`

any argument against this?
I just need a 👍 and I will implement and send the PR

## Use case
We want to send the cause to the trigger `ORDER_SUPPLIER_REFUSE` and add it to our mail notifications.

**Comment by BebZ** [comment]
👍 for me

**Comment by riseval** [comment]
Not only for Suppliers, every validation / approval / rejection need to have this text field to use either : 

1. Reason for rejection 
2. Justification for approvals.

👍

**Comment by cfoellmann** [comment]
PR #17781
