### ISSUE TITLE
Products and Services Require Make, Category, Model

### ISSUE THREAD

**Issue by carmelchas** [Dolibarr/dolibarr#17751]
# Instructions
Is it an intended feature to require services to have make, category, and model?

I perhaps can understand requiring a category, but make and model do not make sense for services.

# Bug
When editing a Product / Service in the web interface an error is encountered if you do not provide values for the following fields:

- Make
- Category
- Model

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
I expect to be able to update Products/Services without specifying these fields.  At a minimum I expect to be able to edit Services without specifying these fields.

## Steps to reproduce the behavior
1. Add a product/service via the API without providing make, category, and model. SUCCESS
2. Attempt to update a product/service without filling-out the fields make, category, and model.  ERROR

**Comment by atm-maxime** [comment]
To my knowledge, there are no such fields as make and model. And by category do you mean tags ? Do you use specific complementary attributes?

**Comment by carmelchas** [comment]
Good call.  Someone added these extra fields without me knowing.  Please disregard this message.
