### ISSUE TITLE
Top menu missing icon at first external module activation main.inc.php

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#17761]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*

# Bug
When activating an extension for the first time, the icon is not loaded.
You will have to do Ctrl + F5 so that the top menu is ok

## Environment
- **Version**: All
- **OS**: All
- **Web server**: All
- **PHP**: All
- **Database**: All
- **URL(s)**: All

## Expected and actual behavior
Reload the CSS in order to have the icons of the new module that has just been activated
## Steps to reproduce the behavior
- First installation of an extension with an icon in the top menu
- Activation of the extension
- The icon is not present in the top menu
- If CTRL + F5 the extension icon appears in the top menu

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
Before : 
![image](https://user-images.githubusercontent.com/3288514/119951013-ca4fde00-bf9b-11eb-9fe5-87df5577a896.png)

![image](https://user-images.githubusercontent.com/3288514/119951367-287cc100-bf9c-11eb-9b89-998c48dc58d3.png)

![image](https://user-images.githubusercontent.com/3288514/119951568-61b53100-bf9c-11eb-8f1e-334d8a315c89.png)

After CTRL +F5

![image](https://user-images.githubusercontent.com/3288514/119951682-83aeb380-bf9c-11eb-99f7-be5bcc7dbbc6.png)

After : 
![image](https://user-images.githubusercontent.com/3288514/119950493-2d8d4080-bf9b-11eb-889f-41db22f55316.png)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/17769

**Comment by lmag** [comment]
👍  thank !
