### ISSUE TITLE
D14.0.0 / B210530001 / Financial Year removed in Double Accounting Setup

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#17771]
# Bug
Financial Year setup that was available in D 13.0.2 seem to be not available in D 14.0.0 Beta

## Environment
- **Version**: 14.0.0
- **OS**: Linux Ubuntu 18.0.4
- **Web server**: Apache2
- **PHP**: 7.2.4
- **Database**: MySQL 5.5
- **URL(s)**: <http://dolibarrurl> /accountancy/admin/fiscalyear.php?mainmenu=accountancy&leftmenu=accountancy_admin

## Expected and actual behavior
Financial year in countries like India start from 1st of April and ends in 31st March of next year.  If a company has branches in another country, that may start from 1st of Jan and end by 31st of Dec. So it is required to setup the fiscal year / financial year in dolibarr in order to account all of the transactions falling during that period in the same financial year.

However, this step of creating financial year / fiscal year is not seen in dolibarr 14.0.0 beta

## Steps to reproduce the behavior
1. Login as admin
2. Click Accounting > Setup > Accounting Period 

Step 2 is available in Dolibarr 13.0.2 but not in Dolibarr 14.0.0 beta

Request  to kindly restore the functionality.

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 14.0.0 beta

**Comment by eldy** [comment]
May be you must set constant MAIN_FEATURES_LEVEL to 1 or 2 (into home - setup - other) to get the feature.
But this is useless. Dolibarr already allows to get reports from any date to any other date in real time.
