### ISSUE TITLE
Support of Office documents (Excel/word) with phpspreadsheet lib present already in Dolibarr or adding WOPI server feature

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#17788]
Support of **phpspreadsheet** to open office documents attached to any object in edit mode.
AT the moment only the pdf files and image files attached to an object are opened direclty in Dolibarr "on the fly". Using **https://phpspreadsheet.readthedocs.io/en/latest/#file-formats-supported** with DOlibar, will open the door to read/write office documents that are stored in Dolibarr.
Another option maybe implementing a WOPI host = WOPI server = a web API that serves files to a WOPI client (WOPI client = an application that is able to edit files served by WOPI host)  
Some PHP base code: https://github.com/nagi1/laravel-wopi

**Comment by toni-mx** [comment]
I join this request. Would be awesome

**Comment by edupulpillo** [comment]
Here is mentioned in the forum a small "howto" but limited to import/export: 
https://www.dolibarr.org/forum/t/how-to-use-phpspreadsheet-in-dolibarr/21253

Maybe is a good idea to have a standard module in Dolibarr declaring the file types that have installed at the server side a PHP script able to handle it, opening/editing it.
The feature then will make possible to open/edit the files at the server side, without need to download it first locally, and upload it again.

At the moment Dolibarr can manage PDF and images in "preview" mode of any file attached to any object of Dolibarr . It would be very nice to have a centralized module declaring file types and the php libraries/scripts able to handle it with both preview and edit modes. Then the user will be able to edit spreadsheets for example without need to install in his computer excel locally. The options for each recognized type of file then should be "preview", "edit&update", and "download.
