### ISSUE TITLE
LDAP user login broken

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#17782]
# Bug
in the current develop branch https://github.com/Dolibarr/dolibarr/commit/0071d63fbba31aefc51c136eacc6afb455d8fd67 of v14 the ldap login is broken.

## Environment
- **Version**: https://github.com/Dolibarr/dolibarr/commit/0071d63fbba31aefc51c136eacc6afb455d8fd67

## Expected and actual behavior
ldap user lookup and successful login of user.

## Steps to reproduce the behavior
I just updated all files to the most current commit in develop. After that the user login of a ldap user fails. The data is still the same and the connection on the ldap module settings page is successful.
ldap login on different (older) codebase on same server is working correctly.

For me debugging ldap is not really easy. We run the synology active directory package an logging is non-existent here. 👿

**Comment by daraelmin** [comment]
Maybe related to this one #17386

**Comment by cfoellmann** [comment]
release version of 14.0 is working again. can not reproduce anymore and it current develop is also working
