### ISSUE TITLE
Bank Statement Import 

### ISSUE THREAD

**Issue by rotor-head** [Dolibarr/dolibarr#17783]
@FHenry  - I see a few feature requests for CSV importing of bank statements for a module that you've already written and is available on DoliStore for a reasonable fee. However, It doesn't appear to have been updated in over a year.

Are you still supporting this module?

**Comment by FHenry** [comment]
Could you provide the link this product on dolistore? 
I don't remember this. May be my previous company have done it, but I wasn't the only developper there.

**Comment by rotor-head** [comment]
> Could you provide the link this product on dolistore?
> I don't remember this. May be my previous company have done it, but I wasn't the only developper there.

Maybe this isn't you?
https://www.dolistore.com/en/modules/1266-Dolimport-API.html?search_query=Florian+DUFOURG&results=4

**Comment by FHenry** [comment]
I can confirm that it is not me ;-)

**Comment by rotor-head** [comment]
Okay!

I'll close this and create a new feature request to avoid any confusion.
