### ISSUE TITLE
Error when loading chart of accounts

### ISSUE THREAD

**Issue by esaumell** [Dolibarr/dolibarr#17791]
## Bug
*Try to load "PCG08-PYME - The PYME accountancy spanish plan - (ES)" accounting plan*

## Environment
- **Version**: *13.0.2 and 12.0.5 (on Dollicloud)*
- **OS**: *Debian GNU/Linux 10*
- **Web server**: *Apache/2.4.38 (Debian)*
- **PHP**: *7.3.27-1~deb10u1*
- **Database**: *MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1*
- **URL(s)**: */accountancy/admin/account.php?valid_change_chart=1&chartofaccounts=7 on 13.0.2*
- **URL(s)**: */accountancy/admin/account.php?valid_change_chart=1&chartofaccounts=4 on 12.0.5 (Dollicloud)*

## Expected behavior
*Should be no errors*
*In case of errors would be nice to know what they are.*

## Actual behavior
*Some accounts load but some not. Apparently there is no information about which ones did not load.*
***Message displayed (yellow):*** *Error when loading chart of accounts. If few accounts were not loaded, you can still enter them manually.*

## Steps to reproduce the behavior
*Go to /accountancy/admin/account.php and try to load the "PCG08-PYME - The PYME accountancy spanish plan - (ES)" accounting plan.*

*It seems that something similar happened before with SKR03 [#11456](https://github.com/Dolibarr/dolibarr/issues/11456)*

## [dolibarr.log](https://github.com/Dolibarr/dolibarr/files/6582260/dolibarr.log)
*File truncated before loading the plan. There is only the result of importing the accountancy plan.*

**Comment by esaumell** [comment]
Great! Fix solves the Spanish one. Fix missing on SKR03 as of [#11456](https://github.com/Dolibarr/dolibarr/issues/11456).
I checked them all on 12.0.5 on Dolicloud. Same error on screen with SKR04 and AT ones.

**Comment by Hystepik** [comment]
SKR03 fix works too for SKR04
