### ISSUE TITLE
Bank Statement CSV Import - Part II

### ISSUE THREAD

**Issue by rotor-head** [Dolibarr/dolibarr#17798]
# Feature Request
*Add native ability to import monthly bank statements from CSV and Excel into Dolibarr*

## Use case
Currently, end users have a facility to manually enter bank statement items into the system. This process is prone to data entry error and can exacerbate the challenge of the routine reconciliation of accounts.

Utilizing an import of monthly statements from bank accounts can assist in eliminating those variances as well as reduce the time end users waste on uncovering/correcting the errors.

## Suggested implementation
* Add CSV/Excel import section under the Bank/Cash with role based access control.
* No two banks are alike. Therefore, mapping of column imports should include date, credit/debit options, payment type, expense category.
* Provide simple documentation with explanations of mappings 
* Preview and flag any potential errors, such as entries already existing in the database, and allow for end user to override or uncheck the offending entry.

## Suggested steps
Not a super sexy project. Maybe the first step here is to agree it is needed, then draw straws to see who gets stuck implementing the feature?

**Comment by aspangaro** [comment]
An external module is present on Dolistore (there are no plans to integrate it into the core at this time) : https://www.dolistore.com/fr/modules/1385-Suivi-Bancaire-Automatique-sans-abonnement.html?search_query=suivi&results=50
