### ISSUE TITLE
Dolibarr needs to migrate to a framework like laravel

### ISSUE THREAD

**Issue by MUzayr** [Dolibarr/dolibarr#17803]
Things are changed now and now the difficulty of dolibarr code maintenance is increasing day by day... dolibarr needs to be migrated to Laravel etc to survive... Please start a new repo where contributors start work to migrate code to Laravel or any other framework

**Comment by daraelmin** [comment]
Duplicate of #14840 (that you had have opened) and #10054 (witch @aspangaro has already pointed to you)

Your help is still welcome

**Comment by cfoellmann** [comment]
This is a complete rewrite and totally out of scope of the manpower this project has.
We need to streamline and standardize more stuff like lists (tables), cards, whole forms into classes that can be extended but "migrating" all logic to a framework is just stating a new project.

**Comment by cfoellmann** [comment]
#9429
