### ISSUE TITLE
SMTP Error Codes

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#17800]
Hello, 
i have now the first time ever (in about 8 years) problems with sending emails from Dolibarr via SMTP (TLS, 465)

The Customer wants/needs to use a remote mail server (something like exchange).
Settings are so right okay - tested with local desktop mail clients (outlook / thunderbird).

But with Dolibarr - testing the server availability in Dolibarr - the customer gets an error 110.
If i test it on my test-system - with the same parameters - get the error code 0.

My tests with a non Dolibarr System and the customer mail server are okay 
and with Dolibarr and another email-Server like Gmail is also working.

Where can i check the mail error codes? 
Can i log them? (found nothing in general dolibarr logs).

**Comment by Toni-RS** [comment]
I join this request. Would be awesome
