### ISSUE TITLE
cron script

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#17808]
# Feature Request
Extand compatibility of cron script for installation with "htdocs" renamed

## Use case
\scripts\cron\cron_run_jobs.php
near line 45 : require_once $path."../../htdocs/master.inc.php";
"htdocs" is hardcoded

## Suggested implementation
move the script in htdocs, so relative path can be used (without specified "htdocs" or else)
change the line 45 for a relative path included into the modified path
ex : require_once $path."../master.inc.php"; if cron_run_jobs.php is in "\mypath\cron"

**Comment by FHenry** [comment]
Install Dolibarr in another directory structure ad "root"/htdocs" is not a good idea. The Github repository include this structure itself. install with another way (directory structure) seems to not be a good practice at all.

**Comment by Arre8** [comment]
ok, why impose "htdocs"? only for historical reasons?

**Comment by gmilad** [comment]
(English below)
Bonsoir @FHenry ,

Même en faisant référence à "$dolibarr_main_url_root" qui est renseigné lors de l'installation/configuration/migration c'est ce que j'allais proposé comme Pull Request.

Amicalement,
Gaëtan.

Good evening @FHenry,

Even with the reference to "$dolibarr_main_url_root" which is filled in during installation/configuration/migration this is what I was going to propose as Pull Request.

Kind regards,
Gaëtan.

**Comment by eldy** [comment]
htdocs is not the parent directory but a subdirectory of dolibarr. 
The name of parent directory is not imposed. But any subdire like htdocs, htdocs/core, etc... must remains.
The sub-directory htdocs just means that once dolibarr has been installed (unziped or cloned), this is on this directory that you must point your web server virtual host.

**Comment by Arre8** [comment]
ok, stange choice
i'll respet /htdocs for future installation

i close this issue.
