### ISSUE TITLE
D14.0.0/ B2106030001 / Ability to do payments of multiple invoices in a single stroke

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#17811]
# Bug
As an accountant, I should be able to do payments for multiple invoices (Customer & Vendor)  in a single stroke

## Environment
- **Version**: All
- **OS**: All
- **Web server**: All
- **PHP**: All
- **Database**: All
- **URL(s)**: https://<dolibarr-path>/compta/facture/list.php?leftmenu=customers_bills
-                   https://<dolibarr-path>/fourn/facture/list.php?leftmenu=suppliers_bills 

## Expected and actual behavior
Expected Behavior :
1. Please refer to the below graphic.
2. There is a mass action drop down already available that will effect the selected action on all of the invoices.
3. In real life, we may receive one check or one bank transfer from customer for multiple invoices and similarly, we make one payment for multiple invoices.
4. So the mass action drop down should consists of option to mark payments for all of the selected invoices within one stroke rather than opening each invoice one by one and click on "payment" button.
Current Scenario:
1. There is no way to make one payment for multiple invoices.
2. We need to list and open each invoice and click the "payment" button and update the payment details which is very tedious in case of multiple small item invoices.

## Steps to reproduce the behavior
Home>Billing | Payments > Customer Invoices > List
Home>Billing | Payments > Vendor Invoices > List

## [Attached files]
![image](https://user-images.githubusercontent.com/85006729/120650353-55990a00-c49b-11eb-8f74-3945a160b5e9.png)

**Comment by atm-maxime** [comment]
Not sure I understand. You already can record a payment for multiple invoices. If you click on "create payment" on any invoice, the screen to record the payment shows you all unpaid invoice for the same third-party. Then you can choose which invoices are concerned by the payment.

**Comment by riseval** [comment]
Rechecked and Agree. Thanks a ton for the info.
