### ISSUE TITLE
Problème “re-générer le PDF”

### ISSUE THREAD

**Issue by Axel-v404** [Dolibarr/dolibarr#17828]
Bonjour

Je rencontre un problème sur mon dolibarr, lorsque que je coche tout les facture fournisseurs, et que je demande a re-générer le PDF tout les « TIERS » s’inverse.

Exemple : la première facture le fournisseur s’appel AMAZON et la deuxième facture le fournisseur s’appel CDISCOUNT et bien lorsque que je l’ai coche pour re-générer leurs PDF, CDISCOUNT se met sur la première facture.

J'ai tester sur la démo de dolibarr et ça fais exactement le même soucis alors que sur les factures clients il n'y a aucun soucis sur ce niveau la juste sur les factures fournisseurs.

**Comment by gmilad** [comment]
Hello, in English : 

> Hello
> 
> I have a problem on my dolibarr, when I check all the supplier invoices, and I ask to re-generate the PDF all the "THIRD PARTY" is reversed.
> 
> Example: the first invoice the supplier is called AMAZON and the second invoice the supplier is called CDISCOUNT and well when I checked to re-generate their PDF, CDISCOUNT is put on the first invoice.
> 
> I tested on the demo of dolibarr and it does exactly the same problem while on the customer invoices there is no problem on this level just on the supplier invoices.
> 

Discussions on the French forum : 
https://www.dolibarr.fr/forum/t/probleme-re-generer-le-pdf/36962

**Comment by ksar-ksar** [comment]
Could you try https://github.com/Dolibarr/dolibarr/commit/eaa6987e8b6769af55c08868d3f4cc6731c7e167 ?

**Comment by Axel-v404** [comment]
Bonjour

J’ai effectué la mise à jour et j’ai réessayer en effet le problème est résolu.

Je vous remercie !

Cordialement.
