### ISSUE TITLE
Apply discount

### ISSUE THREAD

**Issue by Likeandfeel** [Dolibarr/dolibarr#17837]
HI Team

Just trying version 14 (beta) and found an issue when you want apply a discount on a bill.

Error Unknown column 't.note_private' in 'field list'
Error Duplicate entry 'facture/(PROV212)-(PROV212).pdf-1' for key 'uk_ecm_files'

# Bug
[*Short description*]

## Environment
- **Version**: 14 beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.3.27
- **Database**: MariaDB 10.3.27-MariaDB

## Expected and actual behavior
Apy discount without notice or error message

## Steps to reproduce the behavior
1. Create a bill
2. Create a discount
3. Assign a product on the bill
4. Apply the discount

Best regards

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 14 beta

**Comment by dpriskorn** [comment]
I think we should close this and ask the reporter to reopen if they still have the issue after upgrading.
