### ISSUE TITLE
Order alert for late date is incorrect

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#17836]
Order was placed 2021-06-03. "Alert" is set to +14 days, which means this order should alert on 2021-06-18. Yet this order shows an alert today, 2021-06-07, which is incorrect.

Dolibarr v12.0.4

![2021-06-07_071636](https://user-images.githubusercontent.com/11036018/120962836-cb81c780-c760-11eb-9cc3-f073fc00e9a0.png)

**Comment by daraelmin** [comment]
Hi,
Could you re-try after upgrade to 12.0.5 ?
Thx

**Comment by bos4711** [comment]
I downloaded dolibarr-12.0.5.tgz and followed the upgrade instructions. Upgrade goes fine, no errors, but it's still 12.0.4 when I re-launch the application.

I will try 13.0.

**Comment by bos4711** [comment]
Ok, I think I found the error. My installation is in /www/doli/ but somehow Dolibarr expects to be installed in /path/htdocs, which means the upgrade script is in /www/doli/htdocs/install, but running that one thinks dolibarr should be fresh install. What a mess.

I will see if moving everything out from htdocs/ to .. will help.

**Comment by bos4711** [comment]
@daraelmin  Now I managed to upgrade to 12.0.5 but the alert is still here. That is, the bug is not fixed in 12.0.5.

**Comment by daraelmin** [comment]
> Ok, I think I found the error. My installation is in /www/doli/ but somehow Dolibarr expects to be installed in /path/htdocs, which means the upgrade script is in /www/doli/htdocs/install, but running that one thinks dolibarr should be fresh install. What a mess.
> 
> I will see if moving everything out from htdocs/ to .. will help.

Why did you change the structure of the soft ? The issue may occure cause the files are probably not saved where expected.

**Comment by bos4711** [comment]
We changed the structure because "http://www.ourdolidomain.com/htdocs/" looks ugly and unprofessional. Been running for over a year without htdocs without any hassle or problems regarding that.

**Comment by daraelmin** [comment]
You better change the root reprository of your dns to htdocs.

For security reason, tge structure is define in dolibarr directory to avoid direct access from dns to folder like "document" or "script".

So you should define http://www.ourdolidomain.com/ pointing to htdocs. First, for security, secondly to guaranty the usability of your installation

**Comment by bos4711** [comment]
Fair point. I will look into that.

However, the order date alert (this ticket's root cause) is still not working in 12.0.5.

**Comment by bos4711** [comment]
This fix corrects the bug in the order list, but the widget still shows an alert (when there should be none). ![Screenshot_20210709_142258.jpg](https://user-images.githubusercontent.com/11036018/125077411-5c7df280-e0c1-11eb-9ba1-571481e65db6.jpg)
