### ISSUE TITLE
The filter of Related Objects of the function "Link To" in a customer invoice, do not allows to select and link vendor objects

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#17842]
In the customer invoice form, at the bottom is located the very useful functionality Related Objects "Link To", to make relations between documents and Objects in Dolibarr (then the link appears in both related objects with a single link)

For example for Accountants and Auditors is very interesting to be able to make a link between a customer invoice and a supplier invoice, to easily identify the document of goods purchased that are invoiced to the customer.

Please unblock the filter (or at least add a special setup in Home/Setup/Other Setup ) to allow to select any object in the list,  to be linked.

**Comment by edupulpillo** [comment]
Nobody thinks is a convenient feature?

**Comment by cfoellmann** [comment]
@edupulpillo I think this is very convenient. It is not that easy to implement and I dont have the time at the moment

**Comment by edupulpillo** [comment]
This freature ecxist already in Purchase orders.

**Comment by edupulpillo** [comment]
it works with the condition the invoices have selected the same project number
