### ISSUE TITLE
Besoin d'ajout bilan comptable dans le module comptabilité

### ISSUE THREAD

**Issue by osmy310** [Dolibarr/dolibarr#17871]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by daraelmin** [comment]
Un with acoounting module do you need this ? (There's two modules for accounting, zone simple and a second advanced)

**Comment by aspangaro** [comment]
No reponse & please use english.

And in fact, you can use personalized groups ti build your own balance sheet.

Close this issue
