### ISSUE TITLE
API: support multiprices

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#17891]
# Feature Request
I currently use SQL to PUT multiprices on my products in Dolibarr which is suboptimal 

## Use case
multiprices are an essential thing for my business as I am selling goods both locally and on the internet and the price differs quite a bit.

## Suggested implementation
should be pretty simple to add, here is my python code to do the job:
```
def insert_multiprice(
        product_id, brutto_price1, brutto_price2, vat,
):
    conn = db_connect()
    # Create a cursor object
    cur = conn.cursor()
    query = sql.SQL("INSERT INTO public.llx_product_price " +
                    "(fk_product, price, price_ttc, tva_tx, " +
                    "date_price, price_base_type, price_level," +
                    "fk_user_author) " +
                    "VALUES (%s,%s,%s,%s,now(),'TTC',%s,1)")
    # exec for each pricelevel:
    cur.execute(query, (
        product_id, int(brutto_price1) / 1.25, brutto_price1, vat, 1
    ))
    cur.execute(query, (
        product_id, int(brutto_price2) / 1.25, brutto_price2, vat, 2
    ))
    cur.close()
    try:
        conn.commit()
    except ConnectionError:
        print("Could not commit to db")
    print("Multiprice added.")
    db_disconnect(conn)
```

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by dpriskorn** [comment]
duplicate of #12812

**Comment by MarchesiQuant** [comment]
Hey, I am trying to implement this in my business (with python via REST API), but I don't know much about SQL. I have a few questions about your code, please send me an email to pablomarchesiselma@gmail.com if you are willing to help me with this. Thanks!
