### ISSUE TITLE
Products/services duplicates on supplier card

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#17892]
# Bug
If a supplier sells a product with different prices, this product can be duplicated on product/service's summary in right column on the supplier card

## Solution
sql query on line #517 of /htdocs/fourn/card.php
replace 
`$sql = 'SELECT p.rowid, p.ref [...]`
by
`$sql = 'SELECT distinct(p.rowid), p.ref [...]`

**Comment by eldy** [comment]
Can you paste a screen shot of page where data are duplicated ?
