### ISSUE TITLE
Tasks extrafields not displayed in tasks list (but project extrafields)

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#17896]
# Bug
Extrafields added in Project module setup > Complementary attributes (tasks) with Visibility set to 1 are not displayed in Tasks lists, not even listed in `projet/tasks.php?id=1#selectedfields` (here for project id 1). 

But this list of displayable columns shows **projects** extrafields...

## Environment
- **Version**: 13.0.1

## Expected and actual behavior
Ability to select tasks extrafields to be displayed in tasks lists, even Computed extrafields. :)

**Comment by manu-p** [comment]
Still the same as of 15.0.2

**Comment by inoveaconseil** [comment]
It's work in 14.0.5
