### ISSUE TITLE
Bug: Fatal error: Uncaught Error: Call to undefined function htmlPrintOnlinePaymentFooter()

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#17907]
in /home/.../httpdocs/public/recruitment/view.php on line 330
# Bug
[*The bug appears on the public link*]

## Environment
- **Version**: 14.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.4.20
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1-log
- **URL(s)**: /recruitment/recruitmentjobposition_card.php?id=1

**Comment by ksar-ksar** [comment]
Hello, you have the website URL in the issue
