### ISSUE TITLE
Bug:  Warning: array_replace(): Expected parameter 1 to be an array, 

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#17908]
null given in /home/.../httpdocs/recruitment/core/modules/recruitment/doc/pdf_standard_recruitmentjobposition.modules.php on line 1285

# Bug
[*appears when generated document*]

## Environment
- **Version**: 14.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.4.20
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1-log
- **URL(s)**: /recruitment/recruitmentjobposition_card.php?id=1

**Comment by ksar-ksar** [comment]
Hello, you have the website URL in the issue

**Comment by grandoc** [comment]
thanks @ksar-ksar
