### ISSUE TITLE
Bug: Warning: uasort() expects parameter 1 to be array, null given in /home/.../httpdocs/core/class/commondocgenerator.class.php on line 975

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#17909]
# Bug
[*When generate document*]

## Environment
- **Version**: 14.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.4.20
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1-log
- **URL(s)**: /recruitment/recruitmentjobposition_card.php?id=1

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/17911

**Comment by ksar-ksar** [comment]
Hello, you have the website URL in the issue title
