### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [Dolibarr/dolibarr#17912]
Hi @eldy 
Potential security vulnerability has been submitted through huntr .
Plz validate there 
https://huntr.dev/bounties/18-other-Dolibarr/dolibarr/
https://huntr.dev/bounties/23-other-Dolibarr/dolibarr/
https://huntr.dev/bounties/22-other-Dolibarr/dolibarr/
https://huntr.dev/bounties/21-other-Dolibarr/dolibarr/
https://huntr.dev/bounties/20-other-Dolibarr/dolibarr/
https://huntr.dev/bounties/19-other-Dolibarr/dolibarr/

**Comment by ranjit-git** [comment]
Hello @eldy 
any update about this bug?

**Comment by IC-Florian** [comment]
All these vulnerabilities are fixed since v15.0.0 of Dolibarr. Issues to close
