### ISSUE TITLE
Improve "Quickadd dropdown" style

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#17922]
# Feature Request
I would like to change the current "style" of the quickadd dropdown
![image](https://user-images.githubusercontent.com/1256090/121863748-757ec800-ccfc-11eb-9bd5-f5fc4e8beabe.png)

to show up like the bookmarks dropdown
Like so:
![image](https://user-images.githubusercontent.com/1256090/121864519-46b52180-ccfd-11eb-9b59-651021cec79b.png)

I would love to get some input on this. I would get on this very soon.

**Comment by cfoellmann** [comment]
@eldy @daraelmin what do you guys think?

**Comment by daraelmin** [comment]
I like your idea.
