### ISSUE TITLE
Need a Job and Skills management in Dolibarr

### ISSUE THREAD

**Issue by atm-arnaud** [Dolibarr/dolibarr#17947]
# Feature Request
A job management will be usefull to see available job in the company and possible employees.
The final aim will be comparing usergroups without one person to prevent lost skills.

## Suggested implementation
We need a skill list evaluable (compétence)
We need a Job list. (emploi)
We need a Position list. (poste)
A job will be defined by his skills list needed. A job will deserve a list of real jobs (position) in the company.

We need a comparative system for usergroups

With Dolibarr 14, we could add a feature to this addon : 
When a position is free (an employee leave our company), we could add a button to create a new recruitement job position.

Regards,

**Comment by atm-arnaud** [comment]
@eldy ATM Consulting will work on this Feature between July and September 2021

**Comment by eldy** [comment]
Thanks to implement it (menu, permission, objects, etc into the existing empty module modHRM  (Human Relationship Management).

**Comment by atm-gauthier** [comment]
Hi !

SQL integration PR : https://github.com/Dolibarr/dolibarr/pull/18832
Source code PR : https://github.com/Dolibarr/dolibarr/pull/18850

**Comment by cfoellmann** [comment]
Some code made it into the codebase but where can I test the features? I am already in feature level = 2

**Comment by atm-gauthier** [comment]
@cfoellmann for the moment, only sql tables are present in develop.
My second PR should be merged soon, but if you want to test it now, you have to install a dolibarr in branch develop, and after switch to my branch https://github.com/atm-gauthier/dolibarr/tree/NEW/integration_GPEC_code, and activate hrm module

**Comment by atm-gauthier** [comment]
@cfoellmann now everything's on develop if you want to test it

**Comment by atm-arnaud** [comment]
This issue has been merged.
Thanks @eldy
