### ISSUE TITLE
Bug: does not save edits on invoice lines after update to PHP8 on arch

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#17969]
# Bug
Dolibarr does not save edits to lines regarding description or price. No error is shown in the interface.

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: nginx/1.20.0
- **PHP**: fpm-fcgi 8.0.7
- **Database**: PostgreSQL 13.3
- **URL(s)**: /compta/facture/card.php?id=304

## Expected and actual behavior
expected dolibarr to update the database
it does not

## Steps to reproduce the behavior
create an invoice
add a line
edit the line
save
-> no change after reload
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by dpriskorn** [comment]
can anyone reproduce?

**Comment by dpriskorn** [comment]
deleting lines work fine

**Comment by ksar-ksar** [comment]
Dolibarr V13 is not compatible with PHP V8.
It is PHP V7.4 only : https://wiki.dolibarr.org/index.php/Releases

I close.
