### ISSUE TITLE
Add a "billable" link to the Order widget

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#17963]
The "Purchase order" widget has a link to "Open" orders and "Awaiting reception" orders. It would be nice if the Order widget could have a link to Billing/Payment->Billable orders.

![Untitled](https://user-images.githubusercontent.com/11036018/122397735-89832d80-cf79-11eb-8a36-e0d9d871306e.png)

**Comment by atm-maxime** [comment]
So it will be the count of all customer orders (a least with validated status) where the "billed" flag is "no". And it would be called "billable orders".

**Comment by bos4711** [comment]
Yes, where the link goes to "/commande/list.php?leftmenu=orders&search_status=-3&billed=0&contextpage=billableorders".

**Comment by atm-maxime** [comment]
Are you sure you want to have orders that are not yet delivered ? My guess is that a billable order is a delivered order not yet billed.

**Comment by bos4711** [comment]
Your guess is correct.
