### ISSUE TITLE
Bug: Fatal PHP8 Error causes linked objects to disappear from commande/card.php and fourn/commande/card.php

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#17973]
# Bug
The linked invoice does not show up.

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: nginx/1.20.0
- **PHP**: fpm-fcgi 8.0.7
- **Database**: PostgreSQL 13.3
- **URL(s)**: /commande/card.php?id=493&action=classifyunbilled

## Expected and actual behavior
linked files accessible 
they are gone

## Steps to reproduce the behavior
install dolibarr on php8
create an order
create an invoice
goto commande/card.php 
cannot scroll down further - linked objects is gone

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/68460690/122521287-ef70c300-d014-11eb-93cb-49f93677ac3d.png)

**Comment by dpriskorn** [comment]
Got this from the log:
```
Jun 18 09:23:15 parabola nginx[435]: 2021/06/18 09:23:15 [error] 435#435: *983 FastCGI sent in stderr: "
d property: Conf::$supplier_proposal in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php on line 7138
PHP message: PHP Warning:  Attempt to read property "enabled" on null in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php on line 7138
PHP message: PHP Warning:  Undefined property: Conf::$ticket in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php on line 7141
PHP message: PHP Warning:  Attempt to read property "enabled" on null in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php on line 7141
PHP message: PHP Warning:  Undefined property: stdClass::$ref_client in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php on line 7208
PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "label" in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php:7210
Jun 18 09:23:15 parabola nginx[435]: Stack trace:
Jun 18 09:23:15 parabola nginx[435]: #0 /home/egil/src/php/dolibarr-production/htdocs/fourn/commande/card.php(2626): Form->showLinkToObjectBlock(Object(CommandeFournisseur), NULL, Array)
Jun 18 09:23:15 parabola nginx[435]: #1 {main}
Jun 18 09:23:15 parabola nginx[435]:   thrown in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php on line 7210" while reading upstream, client: 127.0.0.1, server: dolibarr.localhost, request: "GET /fourn/commande/card.php?id=319&save_lastsearch_values=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "dolibarr.localhost", referrer: "http://dolibarr.localhost/fourn/commande/list.php?leftmenu=orders_suppliers&statut=5"
```

**Comment by dpriskorn** [comment]
Why has this not been caught by the test suite?

**Comment by frederic34** [comment]
PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "label" in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php:7210 is already fixed here https://github.com/Dolibarr/dolibarr/pull/16526/files
also I think 13 is not usable with php8

**Comment by dpriskorn** [comment]
> PHP message: PHP Fatal error: Uncaught Error: Undefined constant "label" in /home/egil/src/php/dolibarr-production/htdocs/core/class/html.form.class.php:7210 is already fixed here https://github.com/Dolibarr/dolibarr/pull/16526/files
> also I think 13 is not usable with php8

In V13 readme it says "PHP5.4+". That should be changed to "PHP 5.4-7.4"

**Comment by dpriskorn** [comment]
I downgraded to 7.4 and it seems to work fine, and that version complains/warns about the label-issue.

**Comment by ksar-ksar** [comment]
Hello,

Dolibarr V13 is PHP V7.4 maximum : https://wiki.dolibarr.org/index.php/Releases

I close the issue.
