### ISSUE TITLE
When Sales Tax is "No" for third party, It still calculates sales tax on invoices. 

### ISSUE THREAD

**Issue by thegeettanna** [Dolibarr/dolibarr#17972]
# Bug
I am using dolibarr setup for India taxation system on 13.0.1 version. I am trying to setup three tax rates (IGST + CGST + SGST) and based on the location of the third party, will configure which ones to be used for that particular third party. 
But to focus only on the problem, I am going to skip the taxation related stuff for now and directly explain the issue here. 

I have enable Sales Tax, Second Tax & Third Tax in my company module:
![Screen Shot 2021-06-17 at 11 57 36 PM](https://user-images.githubusercontent.com/24646523/122470560-d1d33780-cfdb-11eb-9761-624c095279a2.jpg)

Now, All defualt tax rates have been enabled for India:
![Screen Shot 2021-06-17 at 11 57 47 PM](https://user-images.githubusercontent.com/24646523/122470619-e7486180-cfdb-11eb-9d39-31a1b40f9414.jpg)

Tax rate for product has been configured:
![image](https://user-images.githubusercontent.com/24646523/122470689-fa5b3180-cfdb-11eb-96d0-271d1b7eab25.png)
As seen in the previous image the tax rate (I-18) selected has 'sales tax = 18', 'second tax = 0' & 'third tax = 0'. 

Now, for a third party, I have disabled 'sales tax'. Which means the expected behavior is to not calculate the sales tax as per setup for the specific third party. 
![image](https://user-images.githubusercontent.com/24646523/122470949-4ad28f00-cfdc-11eb-9962-166212c1ce34.png)

But as seen in the invoice made, it still calculates the sales tax for the third party, even when "Sales Tax is configured as No". 
![image](https://user-images.githubusercontent.com/24646523/122471064-6c337b00-cfdc-11eb-9843-89ada5b25209.png)

I have already tried configuring all sales tax, second tax & third tax as "No" for the third party, but it has not worked. 
What am I missing? What overrides the setup for individual third parties in terms of sales tax? 

##Use Case
When using more Sales Tax + Sales Tax 2 + Sales Tax 3 (For Indian GST Taxation System), there is a problem as in every invoice we are expected to change the tax rates. But I found a better option to add a sales tax rate with Tax 1, Tax 2 & Tax 3. Now, all I need to do is trigger the tax rate as per setup for each individual company. Which as explained above is not working as expected. If we are able to achieve this, which I believe we should be with ease. Then the setup for taxation in India can be implemented as per rules in a very user friendly way.

**Comment by atm-maxime** [comment]
I think the "sales tax = no" on the third-party card means that the third party does not apply taxes on its own sales. Not that you don't apply taxes on your sales to it.

**Comment by thegeettanna** [comment]
@atm-maxime, 

Thank you for your response. 
Any ideas on how to achieve this based on the existing infrastructure? 

I will try to explain the problem in a little more detail:

So in India, there are three types of taxes:
1. IGST for interstate sales & purchase. 
2. CGST for same state sales & purchase. 
3. SGST for same state sales & purchase. 

For example - a product XYZ has to be sold at 18% tax rate. 
If we sell it to a third party in the same state, we pay CGST (9%) + SGST (9%). 
And if we sell it to a third party in other state, we pay IGST (18%). 

Currently the way dolibarr handles this is that the tax rates for using 'IGST' or 'CGST + SGST' are different. So when making an invoice, we are actually forced to change tax rates. 
Instead, if we are able to configure whether we use sales tax (IGST), or sales tax 2 & 3 (CGST & SGST) for third parties, then whenever we make an invoice, this can be handled directly. And then make up tax rates as per attached screenshots. 
![Screen Shot 2021-06-20 at 4 01 15 PM](https://user-images.githubusercontent.com/24646523/122670762-3e6b5380-d1e1-11eb-9ab0-a15f8b17db74.jpg)

This is important for us, as for each product, we have configured one tax rate. We have selected all rates for 'IGST' now unfortunately we have to give rights to others to change it and if they make a mistake, the whole process hits a legal roadblock, but this is not a practical method and we have had to rename 'IGST' as 'GST' and we use another software for invoicing. 

If you show me how this can be achieved, I will try to implement and share the code here. 
Pinging @eldy @ksar-ksar - in case you can help me out here.

**Comment by eldy** [comment]
My understanding is that for some thirdparties, you need to use GST18 and for some other C+S-18 depending on state of customer. Right ?

But Dolibarr is not able to guess in which case you must use one or the other (so the higher value is suggested by default, so GST18), so currently you will always have to set it manually.
In a future version, we hope to have the combo list with different vat code available during the insert to avoid to have to edit it manually after the insert of line. But there is no date planned for this feature.

**Comment by thegeettanna** [comment]
Dear @eldy, 

I understand what you are trying to say. And that is correct, we either use 'I-18' tax rate or 'C+S-18' depending upon the state of the customer. Which actually can be decided upon the first 2 numbers of a GST code, as each GST code begins with 2 digit state code. But I understand that it is not on the priority changes as of now. Appreciate the already built in system. 

I think there is another way to achieve this as well. If we can configure the sales tax usage for third parties from the third parties page. We could trigger which tax to use for them from the third party setup page. And setup Tax rates as per 'GST-18'
![122670762-3e6b5380-d1e1-11eb-9ab0-a15f8b17db74](https://user-images.githubusercontent.com/24646523/123113360-205d5780-d45c-11eb-871e-645892b927f0.jpg)

I would have made extra fields and attempted the same thing, the only problem is I am not sure if it would break the tax counting at some other place or not. 
Or else, I could add two fields and add a trigger before tax calculation on Proposals, Commande (orders), Invoices for both Customers & Vendors. 
Should I attempt something like that? Just add a trigger based on the 2 extra fields in these modules?

**Comment by thegeettanna** [comment]
@eldy @ksar-ksar @hregis 
Sorry to ping you guys again. I know you all must be busy with V14.0 code checks. 
This problem is stopping me from launching invoices from the Dolibarr ERP. Our offices still uses another software, which I aim to discontinue, but it won't happen as long as we are unable to make invoices from ERP directly without manually altering the Tax rates. 

So, after a lot of checks and thoughts, I have been able to pinpoint a solution, but need your help is telling me which file to edit. I am explaining the solution below, but first I will tell you what I am trying to change and please help me with the files to edit to achieve this:
![Screen Shot 2021-07-01 at 8 18 23 PM](https://user-images.githubusercontent.com/24646523/124146357-5083a680-daab-11eb-9c0a-7196e5372388.jpg)
In llx_societe sql table, the field tva_assuj decides if Supplier: issues invoices with VAT? / Customer: is subject to VAT?
But instead I want every supplier & customer to always use VAT. 
I want tva_assuj to reflect if the supplier or customer uses 'IGST' which it already does. But if tva_assuj is "0" ('NO'), then the system does not even consider it for localtax1 or localtax2, which is my only point of pain. 

Even if tva_assuj is 0, I want the system to check if localtax1_assuj is 1 or 0 & check if localtax2_assuj is 1 or 0. And then calculate localtax1 and/or localtax2  if they are 1 ('active'). 
**_So all we need is a way to override the check on localtax1 and localtax2, irrespective of the tva_assuj value._** 

Screenshots of only two types of setup required:
#1 Type - Which works okay as per current settings. 
![image](https://user-images.githubusercontent.com/24646523/124145904-d94e1280-daaa-11eb-91dd-c2cb6504c8e5.jpeg)
#2 Type - Which does not calculate any tax because tva_assuj = 0. 
![image](https://user-images.githubusercontent.com/24646523/124145996-f08d0000-daaa-11eb-9376-b1a6ca0f9c3e.jpeg)

I don't know many other people that might be able to help, but if you can point me to someone else, I will reach out to them as well.

**Comment by thegeettanna** [comment]
> My understanding is that for some thirdparties, you need to use GST18 and for some other C+S-18 depending on state of customer. Right ?
> 
> But Dolibarr is not able to guess in which case you must use one or the other (so the higher value is suggested by default, so GST18), so currently you will always have to set it manually.
> In a future version, we hope to have the combo list with different vat code available during the insert to avoid to have to edit it manually after the insert of line. But there is no date planned for this feature.

@eldy - If we are able to override the system and we allow it for calculation of localtax1 & localtax2 even if tva_assuj is 0 ('No'), then all that would be left is to add combined tax rates, and that would take less than 60 seconds. You won't need to plan a date for this feature, it would have been achieved. 

This is the easiest way of resolving this problem in my opinion. The only problem is that I am not sure what files and lines to edit. Point me to the files and I will do my best to resolve this using trial and error checks.
