### ISSUE TITLE
Tax rate of a product/service cannot be changed if the p/s is set to "Not for sale"

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#17971]
The "default tax rate" setting for a product or a service is very useful, but as of version 12.0.5 there's a problem with it. If you add a new product/service you can change the tax rate immediately and then set to "Not for sale" and everything is fine. However, if you forget to change the default tax rate and set to "Not for sale", the default tax rate is not possible to change. The only solution to it is to temporarily change the product/service to "For sale" so you can access the "Selling prices" tab, and there change the tax rate. And then change back to "Not for sale". However, this is tedious work.

Suggestion: move the field "Default tax rate" so it can be seen/changed in the first tab (Product/Service), without bothering if the product/service is set to "For sale" or "Not for sale".

![2021-06-17_212512](https://user-images.githubusercontent.com/11036018/122461261-683f3300-cfb3-11eb-9d80-3a9deca80ec9.png)
![2021-06-17_212520](https://user-images.githubusercontent.com/11036018/122461263-68d7c980-cfb3-11eb-8194-db356edfd2a6.png)

**Comment by atm-maxime** [comment]
I'd say it's normal. Why would you need to deal with the default tax rate if your p/s is not for sale ?

**Comment by bos4711** [comment]
Because when you put a purchase order with the wrong tax rate, you cannot change it there. So you have to go to the product, make it sellable, change the tax-rate, remove it from sellable, and then add it in the purchase order.


![2021-06-19_091022](https://user-images.githubusercontent.com/11036018/122634402-5d34f180-d0de-11eb-8510-98870515c964.png)
