### ISSUE TITLE
Expense Reports: Create for third party

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#17977]
# Feature Request
Allow creation of expense reports for other employees (unless I missed it, expense reports, can only be created by looged user).

## Use case
Allow creation of expense reports by an employee for another one.

## Suggested implementation
Add option to module's permissions : Create/Modify Expense Reports for other user. 

## Suggested steps
When creating expense reports, choose own or alternate user.

**Comment by atm-maxime** [comment]
Confirmed, whatever the permissions are, you can only create an expense report for yourself or one of your subordinates. Perhaps rather than create a new permission, we should also be able to create an expense report for one of the subordinates defined by the "expense report validator" field ?

**Comment by dom-breizh** [comment]
Unless I misundertood you, creating expense reports for subordinates seems unlogical... In a basic structure, the PA creates the expense reports for the supervisor or other employees not the way around. Approval then goes back to the defined supervisor of the corresponding employee. 
Permissions should probably be more refined (Create/edit,...) by user groups (departments), rather then just create/edit  for everyone.

**Comment by tsaquet** [comment]
Hello ! We just hired someone to help us about different things, we wanted him to create expense reports for us and we found out here this is not possible. Is it possible to re-open this issue ?

**Comment by FlorentPoinsaut** [comment]
@eldy could you please confirm that this Feature Request is never implemented on Dolibarr? If so, could we reopen this issue and I will try to take the time to implement it.

**Comment by eldy** [comment]
The use case described is:
Allow creation of expense reports by an employee for another one.

It seems this is already possible with current version, depending on permission.

Do you think to something else ?

**Comment by FlorentPoinsaut** [comment]
You have the right use case.
It's possible only if the creator is higher in the hierarchy that is not the case for a management assistant.

**Comment by eldy** [comment]
> You have the right use case.
> It's possible only if the creator is higher in the hierarchy that is not the case for a management assistant.

So for a manager that need to generate expense report for users not under its hierarchy, tou can give hime the permission "Create expense reports for everybody"

**Comment by FlorentPoinsaut** [comment]
> So for a manager that need to generate expense report for users not under its hierarchy, tou can give hime the permission "Create expense reports for everybody"

Oh! It's an advanced right. So I set the `MAIN_USE_ADVANCED_PERMS` const to 1 and I found this permission.
Thank you Eldy!
