### ISSUE TITLE
[Adherents]  llx_adherent_type.subscription is a VARCHAR

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#17996]
Another type mismatch in the "Adherents" module, similar to #17986 

in adherents/list.php , there are 3 `varchar = integer` comparisons like this

```php
$sql .= " AND (datefin IS NULL OR t.subscription = 0)";
```

See https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/adherents/list.php#L366

Again MySQL allows this kind of comparisons but PostgreSQL does not. By the way, the default value of the subscription column is "yes" which would lead to some unexpected behaviours because for MySQL the comparision `'yes' = 1` is false.

Anayway the numeric value should be quoted like this

```php
$sql .= " AND (datefin IS NULL OR t.subscription = '0')";
```

**Comment by daraelmin** [comment]
> Again MySQL allows this kind of comparisons but PostgreSQL does not. By the way, the default value of the subscription column is "yes" which would lead to some unexpected behaviours because for MySQL the comparision `'yes' = 1` is false.

Where did you find this default value ? As I can read in /htdocs/install/mysql/tables/llx_adherent_type.sql default value for suscription is '1'

```mysql
create table llx_adherent_type(
   rowid            integer AUTO_INCREMENT PRIMARY KEY,  entity           integer DEFAULT 1 NOT NULL,
   tms              timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CRURENT_TIMESTAMP,
   statut           smallint NOT NULL DEFAULT 0,
   libelle          varchar(50) NOT NULL,
   morphy           varchar(3) NOT NULL,
   duration         varchar(6) DEFAULT NULL,
   subscription     varchar(3) NOT NULL DEFAULT '1',
   amount           double(24,8) DEFAULT NULL,
   vote             varchar(3) NOT NULL DEFAULT '1',
   note             text,
   mail_valid       text
)ENGINE=innodb;
````

But, it may be interresting to convert the varchar to integer.

**Comment by daraelmin** [comment]
If we do so, we should also convert `vote` to integer.
And maybe, `morphy` should be also converted to integer in order to save space and optimize perf.

**Comment by daraelmin** [comment]
> > Again MySQL allows this kind of comparisons but PostgreSQL does not. By the way, the default value of the subscription column is "yes" which would lead to some unexpected behaviours because for MySQL the comparision `'yes' = 1` is false.
> 
> Where did you find this default value ? As I can read in /htdocs/install/mysql/tables/llx_adherent_type.sql default value for suscription is '1'
> 
> ```sql
> create table llx_adherent_type(
>    rowid            integer AUTO_INCREMENT PRIMARY KEY,  entity           integer DEFAULT 1 NOT NULL,
>    tms              timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CRURENT_TIMESTAMP,
>    statut           smallint NOT NULL DEFAULT 0,
>    libelle          varchar(50) NOT NULL,
>    morphy           varchar(3) NOT NULL,
>    duration         varchar(6) DEFAULT NULL,
>    subscription     varchar(3) NOT NULL DEFAULT '1',
>    amount           double(24,8) DEFAULT NULL,
>    vote             varchar(3) NOT NULL DEFAULT '1',
>    note             text,
>    mail_valid       text
> )ENGINE=innodb;
> ```
> 
> But, it may be interresting to convert the varchar to integer.
> 
> If we do so, we should also convert vote to integer.
> And maybe, morphy should be also converted to integer in order to save space and optimize perf

@eldy Can we change the type from varchar to integer in freeze version or should we wait until 14.0 is published as stable to propose the PR for 15.0 ?

**Comment by daamien** [comment]
`'yes'` was the default value until version 12. I can see it's fixed now, thanks....

https://github.com/Dolibarr/dolibarr/blob/11.0/htdocs/install/mysql/tables/llx_adherent_type.sql#L34

To clarify : I am not asking for the type change on these columns. There may be practical reasons to store this as a VARCHAR. I'm just saying that these columns should be compared with VARCHAR values, not integers...

**Comment by daraelmin** [comment]
> `'yes'` was the default value until version 12. I can see it's fixed now, thanks....
> 
> https://github.com/Dolibarr/dolibarr/blob/11.0/htdocs/install/mysql/tables/llx_adherent_type.sql#L34
> 
> To clarify : I am not asking for the type change on these columns. There may be practical reasons to store this as a VARCHAR. I'm just saying that these columns should be compared with VARCHAR values, not integers...

I've understand you're demand. But since 'yes' is deprecated. I think, but I may be wrong, that we should add a migration script to convert 'yes' to '1' and 'no' to '0'. Ans to alter thé columns to integer

**Comment by daamien** [comment]
Sorry if I am unclear but this issue is not about the "yes" default value. I talked about it to demonstrate why the varchar-to-int conversion is a problem. But this is not the main issue.

The main issue is `t.subscription = 0` and the quick fix would be  `t.subscription = '0'`

You can still improve the module afterward by converting the columns from VARCHAR to INT but right now simply adding 2 quotes seems way simpler and does not introduce any regression.

See https://github.com/Dolibarr/dolibarr/pull/17999
