### ISSUE TITLE
La configuration du module Withdraw semble incomplète. Aller sur la page Accueil - Configuration - Modules pour corriger.

### ISSUE THREAD

**Issue by HelouardiDev** [Dolibarr/dolibarr#18006]
# Bug
*La configuration du module Withdraw semble incomplète. Aller sur la page Accueil - Configuration - Modules pour corriger. :*
- *Banques | Caisses*
- *Paiement par prélèvement*

## Environment
- **Version**: [*13.0.2*]
- **URL(s)**: [*/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/86305228/122935358-2e31b080-d368-11eb-86f0-5a43806cb3c2.png)

**Comment by eldy** [comment]
This is a translation problem. The message should be 
"La configuration du module 'Paiement par prélèvement' est incomplète...."
Il faut aller sur la configuration de ce module pour la terminer. Si elle semble complète, fournir une copie écran da la page entière de configuration.
