### ISSUE TITLE
Mass action invoice emails recipient

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#18009]
# Bug
Mass action invoice doesn't use "Contact client facturation" to select the recipient but the generic email from third party card.

* if no email in third party card : no email sent
* if a generic email is defined in third party card : email is sent to generic email and not to the "Contact client facturation" 

## Environment
- **Version**: [v130.3]

## Expected and actual behavior
The mass action should use the contact defined in the object card "Contact client facturation" for example

Thank you

**Comment by dolibarr95** [comment]
Related post on the french forum : 
https://www.dolibarr.fr/forum/t/envoi-masse-facture-clients/37167/5

**Comment by dolibarr95** [comment]
Tested with "Regroupement emails" selected and not selected.

**Comment by dolibarr95** [comment]
Tested also on v10 same behavior :(

**Comment by atm-maxime** [comment]
Yes that's because it's a feature request. The mass mailing has been developed in a generic way so the email used is currently the third-party email. But should we say we always use billing contact for invoices, customer contact for proposals, ?...
I think adding a choice to select the contact role we want to use in the mass mail form would be good.

**Comment by dolibarr95** [comment]
Hello
I think we should use the contact defined in the contact card. 
Eg for the shipping if we want to send mass action email, the recipicent will be the shipping contact as for the delivery contact.

Of course the select choice will be a great option.

**Comment by dolibarr95** [comment]
Hello
Yesterday I cloned Dolibarr v10 and upgraded to v13 and encountered the issues I described above.
Today I install a fresh v13 and the behavior is as expected ... strange but perfect!

**Comment by dolibarr95** [comment]
Hello
@eldy is this function available (maybe it's a misconfiguration on my part)? Or can you please help?
If I wish, send an email from Dolibarr

From a subject card: the email template loads and selects the contact email of the contact defined in the subject's contact page
From Bulk Action: The email template loads and the contact email is empty.

Is there a way to pre-select the mass action of the email form?

Tks for reading

**Comment by dolibarr95** [comment]
Hello
I think the solution is here (actions_massactions.inc.php)
```php
if ($objectclass == 'Facture') {
					$tmparraycontact = array();
					$tmparraycontact = $objecttmp->liste_contact(-1, 'external', 0, 'BILLING');
					if (is_array($tmparraycontact) && count($tmparraycontact) > 0) {
						foreach ($tmparraycontact as $data_email) {
							$listofobjectcontacts[$toselectid][$data_email['id']] = $data_email['email'];
						}
					}
				} 
/////
if ($objectobj->element == 'facture' && !empty($listofobjectcontacts[$objectid])) {
						$emails_to_sends = array();
						$objectobj->fetch_thirdparty();
						$contactidtosend = array();
						foreach ($listofobjectcontacts[$objectid] as $contactemailid => $contactemailemail) {
							$emails_to_sends[] = $objectobj->thirdparty->contact_get_property($contactemailid, 'email');
							if (!in_array($contactemailid, $contactidtosend)) {
								$contactidtosend[] = $contactemailid;
							}
						}
						if (count($emails_to_sends) > 0) {
							$sendto = implode(',', $emails_to_sends);
						}
					}
```
Just have to create propal (or other) condition
