### ISSUE TITLE
field product is not completed in proposal line

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#18012]
# Bug
When trying to add a service in proposal, I type some letter. In previous version, a list is populated with all matching services/products. Now I get only a running wheel.

## Environment
- **Version**: 14.0.0beta
- **OS**: Mageia 8
- **Web server**: apache
- **PHP**: 8.0.5
- **Database**: mariaDB
- **URL(s)**: /htdocs/comm/propal/card.php?id=498&mainmenu=home

From javascript console:
Clear id previously selected for field idprod card.php:301:16
Call method change() after change on #idprod or #idprodfournprice (senderissupplier=0). this.val = 33 card.php:560:11
Call setforpredef. We hide some fields and show dates card.php:641:11
Load unit price without tax and set it into #price_ht for product id=33 socid=16 card.php:574:13
Load unit price end, we got value 12 000,00

From error_log:
[Wed Jun 23 14:24:35.866553 2021] [php:warn] [pid 3844] [client 127.0.0.1:53978] PHP Warning:  Undefined variable $form in /var/www/html/dolibarr-develop/htdocs/product/ajax/products.php on line 238, referer: http://localhost/dolibarr-develop/htdocs/comm/propal/card.php?id=498&mainmenu=home

**Comment by papoteur-mga** [comment]
I have checked with PHP 7.4, the problem is the same

**Comment by atm-maxime** [comment]
Hi !
Can you check now with a stable version 14.0 ? It seems this issue has been fixed. If it's ok for you, you can close it.
