### ISSUE TITLE
NEW sorting fields on leave balances

### ISSUE THREAD

**Issue by lvessiller-opendsi** [Dolibarr/dolibarr#18011]
The page to define "leave balances" for each employe (define_holiday.php) in "GRH" menu don't have sorting field.

![image](https://user-images.githubusercontent.com/45359511/123094647-6a7b1480-d42d-11eb-8aa2-71884c803f6f.png)

It would be interesting to add field like "employees" (on firstname and lastname) to sort this list.

At the same time, we can't select fields to show or hide a column and this page doesn't have any pagination system like in others lists (thirdpaty, product, proposal, order, etc).

Do you think it could be usefull and integrated in next version of Dolibarr ?

**Comment by warnerbryce** [comment]
I upvote this idea. 

It would be great to sort by employees, i lost quite some time by not having this feature.

**Comment by aspangaro** [comment]
With a lot employees, this functionality is very important

**Comment by lvessiller-opendsi** [comment]
It's a feature request and not yet covered by version 17.0.0.

**Comment by warnerbryce** [comment]
Hi 👋 
@eldy could you take a look on this one please ? 
i’m interested

**Comment by lvessiller-opendsi** [comment]
Alrready done
