### ISSUE TITLE
After v13->v14 upgrade, invoices are disabled

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#18013]
# Bug
I migrated from v13 to v14.0.0beta
After that customer invoices and supplier invoices modules are disabled.
## Environment
- **Version**: v14.0.0beta
- **OS**: Mageia 8
- **Web server**: Apache
- **PHP**: 8.0.5
- **Database**: MariaDB

## Expected and actual behavior
Invoices modules were enabled before the upgrade, but they should not be disbled after the upgrade.

**Comment by atm-maxime** [comment]
I noticed this some times and it was related to the permissions of the doctemplates folder in documents. When the upgrade process tried to reload all active modules, if the module fails in copying files in the doctemplates folder, it throws an error and the module is not reactivated...

**Comment by papoteur-mga** [comment]
Hi Maxime,
Yes, this explanation is probably correct. I didn't set the permission before starting the process. I had to do that after a fail in the migration, I didn't remember exactly at which step.
Could the checking be improved to avoid this behaviour?
