### ISSUE TITLE
Getting email with "This is a message with multiple parts in MIME format."

### ISSUE THREAD

**Issue by fvelasquez-scantech** [Dolibarr/dolibarr#18029]
# Bug
When i send a quote i receive this message "This is a message with multiple parts in MIME format." and no attachment in the email.

## Environment
- **Version**: 13.0.3

## [Attached files]
![error](https://user-images.githubusercontent.com/61747153/123338991-c752f980-d517-11eb-855a-a2711e080c6e.PNG)

**Comment by edupulpillo** [comment]
i observe also this problem but only using a PHP version > 7.4, and i fixed it adding mailparse php extension in the PHP configuration of PHP v8.1.
