### ISSUE TITLE
Allow for negative quantities for both produced items and components in Manufacturing Orders

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#18022]
# Feature Request
Right now, you can't select negative  as the quantity to produce in a Manufacturing Order (MO), and any Bill of Materials (BoM) with negative quantities in the lines won't generate a valid MO

## Use case
Right now, a manufacturing order can only produce a single product, even if it can produce multiple units of that product at once. You can only produce a positive number of items in a MO. This is enough for a basic manufacturing module, but there are two use cases that are hard to address with this setup:

1. When making a product, there is a secondary product that is also produced: take 1m bars, cut them into 30 cm rods, and end up with a leftover 10 cm rod. This 10 cm rod is technically a waste product, but it might be worth keeping track because it might also be a valid for sale product. 
2. Sometimes, it's worthwhile to buy an assembled product, and then disassemble it and sell the parts and/or use the parts for some other manufacturing,

(1) could be solved by adding a line with a negative quantity to the BOM (to produce: 3 30 cm rods, to consume: 1 1m bar and -1 10 cm rod) and making a manufacturing order from it. BOMs allow for negative values for components, but generating a manufacturing order from such a BOM fails
(2) could be solved by allowing negative quantities in the amount to produce when making a BOM. Thus, you produce -1 of product A to obtain the parts.

## Suggested implementation
It seems to me that Dolibarr checks that the quantities to consume are positive numbers (since it throws this error BadValueForquantityToConsume if you try to make a manufacturing order with negative quantities). This might be a good way to avoid human errors, but this condition should either be loosened up so negative values in quantities to consume are allowed, or be made toggle-able by the user either from the module configuration page or through Setup Other

**Comment by AntoineArt** [comment]
I am facing the exact same problem where I have secondary products from my production. 
Basically I have Material M -> Product A + Product B + Product C 
Any news or solution about this ?
