### ISSUE TITLE
Bug: Vendor Invoice can't open invoices from list or after creating new

### ISSUE THREAD

**Issue by biodland** [Dolibarr/dolibarr#18039]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When trying to open a Vendor/Supplier invoice I get an error message from dolibarr with a unknown column in the sql.

## Environment
- **Version**: 14.0.0-beta
- **OS**: Debian 4.19
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.27
- **Database**: MySQL or MariaDB 5.5.5-10.3.29-MariaDB-0+deb10u1
- **URL(s)**: /fourn/facture/card.php?facid=1

## Expected and actual behavior
[*Verbose description*]
To open the vendor invoice.

## Steps to reproduce the behavior
[*Verbose description*]
On 2 instances from the latest github (Beta 14.0) I have been meeting the same issue. Problem with unknown field in the database.
Create a vendor invoice, fail occures after creation or when navigating to a given vendor invoice from the list.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
Modules/Applications: user, banque, paymentbybanktransfer, comptabilite, product, service, stock, projet, ecm, barcode, takepos, categorie, adherent, expensereport, societe, commande, contrat, ficheinter, workflow, agenda, fournisseur, supplier_proposal, reception, facture, don
Database type manager: mysqli
Latest database access request error: SELECT t.rowid, t.ref, t.ref_supplier, t.entity, t.type, t.fk_soc, t.datec, t.datef, t.tms, t.libelle as label, t.paye, t.amount, t.remise, t.close_code, t.close_note, t.tva, t.localtax1, t.localtax2, t.total_ht, t.total_tva, t.total_ttc, t.fk_statut, t.fk_user_author, t.fk_user_valid, t.fk_facture_source, t.fk_projet as fk_project, t.fk_cond_reglement, t.fk_account, t.fk_mode_reglement, t.date_lim_reglement, t.note_private, t.note_public, t.model_pdf, t.import_key, t.extraparams, cr.code as cond_reglement_code, cr.libelle as cond_reglement_label, cr.libelle_facture as cond_reglement_doc, p.code as mode_reglement_code, p.libelle as mode_reglement_label, s.nom as socnom, s.rowid as socid, t.fk_incoterms, t.location_incoterms, i.libelle as label_incoterms, t.fk_transport_mode, t.fk_multicurrency, t.multicurrency_code, t.multicurrency_tx, t.multicurrency_total_ht, t.multicurrency_total_tva, t.multicurrency_total_ttc FROM llx_facture_fourn as t LEFT JOIN llx_societe as s ON (t.fk_soc = s.rowid) LEFT JOIN llx_c_payment_term as cr ON t.fk_cond_reglement = cr.rowid LEFT JOIN llx_c_paiement as p ON t.fk_mode_reglement = p.id LEFT JOIN llx_c_incoterms as i ON t.fk_incoterms = i.rowid WHERE t.rowid=1
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 't.fk_transport_mode' in 'field list'

![image](https://user-images.githubusercontent.com/28107493/123591921-dfaf6680-d7ec-11eb-91f5-b4fd2a57fd39.png)
![image](https://user-images.githubusercontent.com/28107493/123591901-d9b98580-d7ec-11eb-8c2f-1c96cd0db35c.png)

## Resolution
htdocs/fourn/class/fournisseur.facture.class.php
Line 678 $sql .= ' t.fk_transport_mode,';
Line 751 $this->transport_mode_id = $obj->fk_transport_mode;

Changed both these lines to 'fk_mode_transport' and got it working on my end.

**Comment by Hystepik** [comment]
Hello,
it works for me in 14.0-beta, have you done your migration ?

**Comment by biodland** [comment]
One of the instance was a migration, the other was not.
Same error occured on both of them.

**Comment by biodland** [comment]
Will try to deploy a new instance then on the same server with new database and see if the error occurs again.

**Comment by Dreller** [comment]
Hi @biodland !  I had the same issue, and THANK YOU for adding the resolution to fix the issue.  I was able to correct my live and test installs.  THANKS!

**Comment by biodland** [comment]
Glad to hear someone else faced the same issue, even tho it would be better if it was only me.

Was it fresh installs, or was it migrations?

**Comment by biodland** [comment]
> it works for me in 14.0-beta, have you done your migration ?

I just did a fresh install, and again. Same error and works again with same fix applied as mentioned in my original post.

**Comment by bontiv** [comment]
Same for me. I fixed in my setup and the upgrade to 14.0.1 broke it again. So I created a PR. It will be great if it can be approved as soon as possible, for next version.

**Comment by eldy** [comment]
According to the sql files into branch 14.0 and develop that create the table the column name is

fk_transport_mode

so code seems correct. 
The fields were created into v13 with migration to v12 to v13:
ALTER TABLE llx_facture ADD COLUMN fk_transport_mode integer after location_incoterms;
ALTER TABLE llx_facture_fourn ADD COLUMN fk_transport_mode integer after location_incoterms;

**Comment by bontiv** [comment]
Ok. So it's a migration issue maybe. In version tagged 13.0.4, the field have the wrong name in installation script. It's fixed in the 13.0 branch but they are no release after the fix.

https://github.com/Dolibarr/dolibarr/blob/a2de6c00a00940a0edc76c32f4400f689141f54f/htdocs/install/mysql/tables/llx_facture_fourn.sql#L74

Everyone who install Dolibarr version 13.0.0 - 13.0.4 is impacted. The fix in branch 13.0 will avoid the bug in future installations with maybe the 13.0.5 version. Fresh install with version 14.0 and above will not be impacted.

Migration of version 13.x to 14.x do not fix the field name. The good practice will be altering table in the next migration script if the field is nammed fk_mode_transport.

**Comment by bontiv** [comment]
I wrote a new draft PR, not tested, to fix column name during migration.

**Comment by eldy** [comment]
See f3babd28194eb3563f43f685ad5caeeef7045cb2
