### ISSUE TITLE
Extrafield and regular expression

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#18048]
# Feature Request
Add a new type of extrafield named "regular expression".

## Use case
User wants to create a new extrafield that must respect a regex to be registered.

Example:

| Title  | Field  |
|---|---|
| Type   | Regular expression  |
| Name   | ISBN  |
| Regular expression  | ^(?=(?:\D*\d){10}(?:(?:\D*\d){3})?$)[\d-]+$  |

## Suggested implementation
Checking could be done with GETPOST()
```php
$isbn = GETPOST('isbn',
                $check='custom',
                $method=0,
                $filter=FILTER_VALIDATE_REGEXP,
                $options=array("options" => array("regexp"=>"/^(?=(?:\D*\d){10}(?:(?:\D*\d){3})?$)[\d-]+$/","default"=>"false"))
                );
```
## Suggested implementation
* Add an extrafield regular expression
* Add a field to define the corresponding regular expression
* Check if the regular expression is respected when submit a form

Tks for reading

**Comment by john-botella** [comment]
Hi @dolibarr95 :-) 

We can use validate class  in htdocs/core/class/validate.class.php

see usage in validateField method of common object

We just have to extends usage of validate class to extra-fields instead of test the $_REQUEST with GETPOST

what do you think about it ?

**Comment by dolibarr95** [comment]
Hello here :)
@atm-john tks for the advice, I will check this class and give a feed back here

**Comment by dolibarr95** [comment]
Hello bot kan you please keep this issue open?
