### ISSUE TITLE
Missing tags and categories in tickets

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#18046]
# Feature Request
Missing tags and categories in tickets

**Comment by lmag** [comment]
We will propose the implementation. @nicolas-eoxia @FHenry

**Comment by evarisk-theo** [comment]
I'll work on this too!

**Comment by lmag** [comment]
Cool @evarisk-theo

**Comment by evarisk-theo** [comment]
Data model has been updated on https://wiki.dolibarr.org/index.php?title=Table_llx_categorie_ticket

**Comment by evarisk-theo** [comment]
PR done : #18127 #18128  #18129

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/18190/files
