### ISSUE TITLE
Invoice created incomplete in shipping management - services not included

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#18050]
# Bug
Invoice created incomplete in shipping management. Services are not included when creating invoice from the shipping 

## Environment
- **Version**: 13.02
- **OS**: Ubuntu Server 20.04
- **Web server**: Apache 2.4
- **PHP**: PHP 7.3
- **Database**: MySQL 8.0.25
- **URL(s)**: NA

## Expected and actual behavior
Expected: When creating the invoice from any steps : proposals, sales orders, shipping, all items (products and services) are passed onto the invoice.
Actual: Expected: When creating the invoice from any steps : proposals, sales orders, all items (products and services) are passed onto the invoice. When created from the shipping steps, services (such as shipping cost, insurances) are not passed to the invoice.

## Steps to reproduce the behavior
Create sales order with a mixture of products and services, approve it, create the shipping, validate it, create the invoice from the shipping tab. Services will not be present anymore on the invoice.

**Comment by dolibarr95** [comment]
Hello
i think this is normal behavior
If you want to ship services, you have to manage service stocks I think

**Comment by dom-breizh** [comment]
Hi,
I do not want to 'ship' services. I just want the button to create an invoice on the shipping page to collect all invoice items (products and services) and create the correct invoice.

**Comment by ToniTen** [comment]
Why do you then want to create the invoice from the shipment? Imagine you've got an order that you deliver in two shipments, and you've got a single line in the order for a service (say shipping costs). If you do the invoice from one of the shipments, you will only get the items in that shipment, but you now want to add the services from the order?
