### ISSUE TITLE
Product codes not duplicated when duplicating supplier codes.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#18055]
# Instructions
* Create Invoice
* Add product lines with product codes ("Réf. Produit Fournisseur" in French).
* Validate the invoice
* Clone/Duplicate the invoice.
* Observe that the product codes were not copied.

Example of product code (2nd column):
![image](https://user-images.githubusercontent.com/1504752/123849103-b855b800-d918-11eb-88bc-13cd73bab3a6.png)

Expected behavior: product codes are duplicated when cloning/duplicating the invoice.

Dolibarr version used: 13.0.2

**Comment by cfoellmann** [comment]
@mdeweerd can you recheck?
And close if it is resolved?

**Comment by mdeweerd** [comment]
Given the [dates of the releases](https://wiki.dolibarr.org/index.php?title=Versions), I suppose that this is not released yet.  Is it testable somewhere?

**Comment by erikvanberkum** [comment]
Give this a try:

https://sourceforge.net/projects/dolibarr/files/latest/download

**Comment by mdeweerd** [comment]
I upgraded to 14.0.2 and cloned an invoice with references, the values are now copied.
Perfect!
