### ISSUE TITLE
FEC Import issue

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#18061]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Error when trying to import a Accounting FEC file with the following error message. The test has been done with the file attached with 3 lines on it. The txt file (FEC file generated by Quadrattus) with space separator has been converted by a semicolon ';' and extension change form txt to CSV (using LibreOffice : see file attached).
Amounts have been tested either with coma or semicolon  : 
Ligne 2     > Bad value of profile setup rule-computeMontant for array_import_fieldshidden     > Bad value of profile setup rule-computeSens for array_import_fieldshidden* 
Ligne 3     > Bad value of profile setup rule-computeMontant for array_import_fieldshidden     > Bad value of profile setup rule-computeSens for array_import_fieldshidden* 
Ligne 4     > Bad value of profile setup rule-computeMontant for array_import_fieldshidden     > Bad value of profile setup rule-computeSens for array_import_fieldshidden
--

## Environment
- **Version**: [14.0.0-beta]
- **OS**: [Linux webd077.cluster028.gra.hosting.ovh.net 4.14.232-ovh-vps-grsec-zfs-classid #1 SMP Mon May 10 09:26:52 CEST 2021 x86_64 ]
- **Web server**: [Apache]
- **PHP**: [7.4.15]
- **Database**: [5.5.5-10.2.36-MariaDB-10.2.36+maria~stretch-log]
- **URL(s)**: [/imports/import.php?step=2&datatoimport=accounting_2&excludefirstline=1&separator=%3B&enclosure=%22]

## Expected and actual behavior
Importation FEC failed 

## Steps to reproduce the behavior
Go to tools then import menu and select FEC import

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="613" alt="Screenshot FEC IMPORT 3 at Jun 30 15-55-07" src="https://user-images.githubusercontent.com/57623859/123974002-8eee6800-d9bc-11eb-9f9a-b0f21b9a6d4d.png">
<img width="615" alt="Screenshot FEC IMPORT 2 at Jun 30 15-55-07" src="https://user-images.githubusercontent.com/57623859/123974016-91e95880-d9bc-11eb-8983-de14cacbdc45.png">
<img width="611" alt="Screenshot FEC IMPORT 1 at Jun 30 15-55-07" src="https://user-images.githubusercontent.com/57623859/123974025-93b31c00-d9bc-11eb-9de1-82442dcf76e5.png">
[SERIOUS751835331FEC20190930TEST3.csv](https://github.com/Dolibarr/dolibarr/files/6741484/SERIOUS751835331FEC20190930TEST3.csv)

**Comment by josett225** [comment]
After looking into the code, I decided to comment on modAccounting.class.php on line : 349 and 350
		//	'b.montant'=>'rule-computeMontant',
		//	'b.sens'=>'rule-computeSens'

Not sure, I am correct but the importation seems to work. Could you confirm this is right?
Thanks

**Comment by aspangaro** [comment]
It works for me but there are several constraints:

The separator in the FEC format is not a ";" but a tab (	) and since we are working on txt, csv format, we have a problem on the amounts format whose separator is the "," when it should be a "."

Need some evolution

**Comment by josett225** [comment]
Hi @aspangaro,

I already cleaned the file with "." instead of ";" and I make it work with ";" as separator and keeping the lines 349 and 350 in comment. I will tried to go back to tab as separator and uncomment the lines to see if it works.

**Comment by josett225** [comment]
Hi @aspangaro 
After testing again the issue is still there. I had to comment line 353 and 354 in v14.0.3 in file 
/dolibarr/htdocs/core/modules/modAccounting.class.php
// 'b.montant'=>'rule-computeMontant',
// 'b.sens'=>'rule-computeSens'

**Comment by josett225** [comment]
Hi @aspangaro 

is this fix with the following PR as I still have the issue when importing with 14.0.5?
			- 'b.montant'=>'rule-computeMontant',
			- 'b.sens'=>'rule-computeSens'
			+ 'b.montant'=>'rule-computeAmount',
			+ 'b.sens'=>'rule-computeDirection'

The PR is the following :
https://github.com/Dolibarr/dolibarr/pull/19981/commits/6d350f9a75677ffcf78d992813493464c5355dad

Best Regards
Jose
