### ISSUE TITLE
Wikidata integration for products

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#18077]
# Feature Request
Import a product that is already described in Wikidata by searching for it. E.g. https://www.wikidata.org/wiki/Q107335417

## Use case
Get image and label etc. from Wikidata

# User stories
* As a user, I want to search for a product among Wikidata items and choose it.
* As a user, I want to import selected fields from the selected Wikidata item into Dolibarr so I don't have to type in more than strictly necessary.
* As a user, I want to be able to go directly to Wikidata and improve the item before or after importing the data.

## Suggested implementation
Add search box on create form
Add link to Wikidata item after import
Make it easy to choose what to import

**Comment by dpriskorn** [comment]
@ksar-ksar I'm willing to make a bounty for this. Interested?

**Comment by ksar-ksar** [comment]
Hello,

I think a lot of developper could be.
I'm only a volunteer not a real Dolibarr developper.

**Comment by dpriskorn** [comment]
> I think a lot of developper could be.

Great see https://github.com/Dolibarr/dolibarr/issues/18082

**Comment by dolibarr95** [comment]
Hello  
Why don't you create a module that records the json result?
Eg for your product https://www.wikidata.org/wiki/Q107335417
use : https://www.wikidata.org/wiki/Special:EntityData/Q107335417.json

**Comment by dpriskorn** [comment]
@dolibarr95 I'm not well versed in PHP unfortunately. The json endpoint of course is a good idea to use once the user found what they are looking for.

Would you like to help write such a module?

It would make sense to first search for the item and then import the data from the json.
