### ISSUE TITLE
API: create and update product multiprices

### ISSUE THREAD

**Issue by ruemmlernet** [Dolibarr/dolibarr#18080]
Currently there is no way to update product multiprices via API

# Feature Request
Make it possible to update multiprices via API and also by creating products

## Use case
By creating products via API write multiprices if availabe (POST).
By product update change multiprices if necessary (PUT).

## Suggested implementation
    public function post($request_data = null)
    {
	global $conf;
	
        if (!DolibarrApiAccess::$user->rights->produit->creer) {
            throw new RestException(401);
        }
        // Check mandatory fields
        $result = $this->_validate($request_data);

        foreach ($request_data as $field => $value) {
    	    $this->product->$field = $value;
        }
        if ($this->product->create(DolibarrApiAccess::$user) < 0) {
            throw new RestException(500, "Error creating product", array_merge(array($this->product->error), $this->product->errors));
        }

        if ($conf->global->PRODUIT_MULTIPRICES) {
	    for ($key = 1; $key <= $conf->global->PRODUIT_MULTIPRICES_LIMIT; $key++) {
        	$newvat = $this->product->multiprices_tva_tx[$key];
        	$newnpr = 0;
        	$newvatsrccode = $this->product->default_vat_code;
        	$newprice = $this->product->multiprices[$key];
        	$newpricemin = $this->product->multiprices_min[$key];
        	$newbasetype = $this->product->multiprices_base_type[$key];
        	if (empty($newbasetype) || $newbasetype == '') {
        	    $newbasetype = $this->product->price_base_type;
        	}
        	if ($newbasetype == 'TTC') {
        	    $newprice = $this->product->multiprices_ttc[$key];
        	    $newpricemin = $this->product->multiprices_min_ttc[$key];
        	}
		if ($newprice > 0) {
        	    $result = $this->product->updatePrice($newprice, $newbasetype, DolibarrApiAccess::$user, $newvat, $newpricemin, $key, $newnpr, 0, 0, array(), $newvatsrccode);
        	}
            }
        }

        return $this->product->id;
    }

    public function put($id, $request_data = null)
    {
        global $conf;

        if (!DolibarrApiAccess::$user->rights->produit->creer) {
            throw new RestException(401);
        }

        $result = $this->product->fetch($id);
        if (!$result) {
            throw new RestException(404, 'Product not found');
        }

        if (!DolibarrApi::_checkAccessToResource('product', $this->product->id)) {
            throw new RestException(401, 'Access not allowed for login '.DolibarrApiAccess::$user->login);
        }

        $oldproduct = dol_clone($this->product, 0);

        foreach ($request_data as $field => $value) {
            if ($field == 'id') { continue;
            }
            $this->product->$field = $value;
        }

        $updatetype = false;
        if ($this->product->type != $oldproduct->type && ($this->product->isProduct() || $this->product->isService())) {
            $updatetype = true;
        }

        $result = $this->product->update($id, DolibarrApiAccess::$user, 1, 'update', $updatetype);

        // If price mode is 1 price per product
        if ($result > 0 && !empty($conf->global->PRODUCT_PRICE_UNIQ)) {
            // We update price only if it was changed
            $pricemodified = false;
            if ($this->product->price_base_type != $oldproduct->price_base_type) { $pricemodified = true;
            } else
            {
                if ($this->product->tva_tx != $oldproduct->tva_tx) { $pricemodified = true;
                }
                if ($this->product->tva_npr != $oldproduct->tva_npr) { $pricemodified = true;
                }
                if ($this->product->default_vat_code != $oldproduct->default_vat_code) { $pricemodified = true;
                }

                if ($this->product->price_base_type == 'TTC') {
                    if ($this->product->price_ttc != $oldproduct->price_ttc) { $pricemodified = true;
                    }
                    if ($this->product->price_min_ttc != $oldproduct->price_min_ttc) { $pricemodified = true;
                    }
                }
                else
                {
                    if ($this->product->price != $oldproduct->price) { $pricemodified = true;
                    }
                    if ($this->product->price_min != $oldproduct->price_min) { $pricemodified = true;
                    }
                }
            }

            if ($pricemodified) {
                $newvat = $this->product->tva_tx;
                $newnpr = $this->product->tva_npr;
                $newvatsrccode = $this->product->default_vat_code;

                $newprice = $this->product->price;
                $newpricemin = $this->product->price_min;
                if ($this->product->price_base_type == 'TTC') {
                    $newprice = $this->product->price_ttc;
                    $newpricemin = $this->product->price_min_ttc;
                }

                $result = $this->product->updatePrice($newprice, $this->product->price_base_type, DolibarrApiAccess::$user, $newvat, $newpricemin, 0, $newnpr, 0, 0, array(), $newvatsrccode);
            }
        }

        if ($result > 0 && $conf->global->PRODUIT_MULTIPRICES) {
	    for ($key = 1; $key <= $conf->global->PRODUIT_MULTIPRICES_LIMIT; $key++) {
        	$pricemodified = false;
        	if ($this->product->multiprices_base_type[$key] != $oldproduct->multiprices_base_type[$key]) {
        	    $pricemodified = true;
        	} else {
        	    if ($this->product->multiprices_tva_tx[$key] != $oldproduct->multiprices_tva_tx[$key]) $pricemodified = true;
        	    if ($this->product->multiprices_base_type[$key] == 'TTC') {
        		if ($this->product->multiprices_ttc[$key] != $oldproduct->multiprices_ttc[$key]) $pricemodified = true;
        		if ($this->product->multiprices_min_ttc[$key] != $oldproduct->multiprices_min_ttc[$key]) $pricemodified = true;
        	    } else {
        		if ($this->product->multiprices[$key] != $oldproduct->multiprices[$key]) $pricemodified = true;
        		if ($this->product->multiprices_min[$key] != $oldproduct->multiprices[$key]) $pricemodified = true;
        	    }
        	}
        	if ($pricemodified && $result > 0) {
        	    $newvat = $this->product->multiprices_tva_tx[$key];
        	    $newnpr = 0;
        	    $newvatsrccode = $this->product->default_vat_code;
        	    $newprice = $this->product->multiprices[$key];
        	    $newpricemin = $this->product->multiprices_min[$key];
        	    $newbasetype = $this->product->multiprices_base_type[$key];
        	    if (empty($newbasetype) || $newbasetype == '') {
        		$newbasetype = $this->product->price_base_type;
        	    }
        	    if ($newbasetype == 'TTC') {
        		$newprice = $this->product->multiprices_ttc[$key];
        		$newpricemin = $this->product->multiprices_min_ttc[$key];
        	    }

        	    $result = $this->product->updatePrice($newprice, $newbasetype, DolibarrApiAccess::$user, $newvat, $newpricemin, $key, $newnpr, 0, 0, array(), $newvatsrccode);
        	}
            }
        }

        if ($result <= 0) {
            throw new RestException(500, "Error updating product", array_merge(array($this->product->error), $this->product->errors));
        }

        return $this->get($id);
    }

`

**Comment by dpriskorn** [comment]
Looks great. Could you send a pull request?

**Comment by MarchesiQuant** [comment]
The issue is still there, any idea how to solve it using python?

**Comment by matthieu-michou-wattandsea** [comment]
Thanks for the code aboce @ruemmlernet
For the newbies like me : you need to replace the 2 existing functions `put` and `post` in the file htdocs/product/class/api_products.class.php by the ones above. Here my file : [api_products.class.php.zip](https://github.com/Dolibarr/dolibarr/files/13327572/api_products.class.php.zip)

Then when you create a product, following fields can now be imported, for example  if you have set 7 levels of prices : 
```
    "price_base_type": "HT",
    "default_vat_code": "20",
    "tva_tx": "20.0000",
    "price": 199.98,
    "multiprices": {"1": "199.98", "2": "180", "3": "170", "4": "160", "5": "150", "6": "140", "7": "139.99"},
    "multiprices_base_type": {"1": "HT", "2": "HT", "3": "HT", "4": "HT", "5": "HT", "6": "HT", "7": "HT"},
    "multiprices_tva_tx": {"1": "20", "2": "20", "3": "20", "4": "20", "5": "20", "6": "20", "7": "20"},
```
I tested it with Python `call_create_api` ; not tested with `call_update_api`
