### ISSUE TITLE
 What bounty platform is preferred by you/the community?

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#18082]
I'm using Dolibarr every day in my business and would like to create a few bounties for fixing of issues I have posted here. 

I wonder what https://en.wikipedia.org/wiki/Open-source_bounty system is preferred by the community?

**Comment by dpriskorn** [comment]
Any reactions?

**Comment by atm-maxime** [comment]
If I understand correctly you want to have a way to pay someone for fixing issues ? Wouldn't it bring down the efforts made by volunteers ?

Anyway, I'll bring the subject to the board next meeting.

**Comment by dpriskorn** [comment]
The idea is to incentivize for issues to get closed faster via a bounty. I have no idea if it works in practice.
