### ISSUE TITLE
Update barcode module documentation

### ISSUE THREAD

**Issue by noedelcroix** [Dolibarr/dolibarr#18098]
Hello,
I'm trying to use the barcode module following this documentation : [Module Code Barre](https://wiki.dolibarr.org/index.php?title=Module_Codes_Barre). It's writed to use "genbarcode" bin but link looks dead... Is it possible to update the link to genbarcode in the documentation please ?
Thanks

**Comment by noedelcroix** [comment]
This is the dead link and I didn't found any alternative : [https://ashberg.de/php-barcode/download/#genbarcode](https://ashberg.de/php-barcode/download/#genbarcode)

**Comment by fappels** [comment]
There is a link in the English version. You can also use the TCPDF-barcode engine. This was not yet documented, I added this in the documentation. Feel free to also update the French version.

**Comment by noedelcroix** [comment]
OK! Thanks! I'll first try to understand Dolibarr, and then, no problem to correct the french docs.
