### ISSUE TITLE
Amounts are not being properly computed in invoices.

### ISSUE THREAD

**Issue by gillerby** [Dolibarr/dolibarr#18091]
# Bug
Amounts are not being properly computed in invoices.

## Environment
- **Version**: Latest 13.0.3
- **OS**: Linux 
- **Web server**:  Apache
- **PHP**: 7.4.20
- **Database**:  Mysql

## Expected and actual behavior
U.P (Unitary price) should be shown as 100, which is the hourly rate I set. 
Total should be 300, which is hourly price (UP = 100) times the amount/quantity, which in this case is 3. 
Instead, UP appears to already be hourly rate times quantity, and total appears to be UP times quantity, so 900.

## Steps to reproduce the behavior
Set hourly rate to 100 
![image](https://user-images.githubusercontent.com/36923120/124473447-ba36d580-dd75-11eb-90aa-2f4172fb5789.png)

Create task with duration of 3 hours by user who has the hourly rate of 100 (superadmin=me in this case)
![image](https://user-images.githubusercontent.com/36923120/124473461-be62f300-dd75-11eb-93ef-8925e4445236.png)

Here's how it looks when invoiced:
![image](https://user-images.githubusercontent.com/36923120/124473474-c327a700-dd75-11eb-9fa3-e8a2671ded9d.png)

And in pdf:
![image](https://user-images.githubusercontent.com/36923120/124473723-08e46f80-dd76-11eb-916c-d67519d074d2.png)

If I'm doing this wrong and this is expected behavior, please clarify:
- what U.P is exactly and how to get the behavior i expected
- How I can show hourly rate in invoices

Thank you.

**Comment by eldy** [comment]
This has been fixed for v14:
The value is the cost of the time (duration * hourly rate). For invoice, we want the selling price. 
When you create your invoice, if you select a product it will use the price of product.
If PROJECT_TIME_SPENT_INTO_INVOICE_USE_VALUE is set, it will reuse the value.
