### ISSUE TITLE
Dolibarr menu no more displayed with "ExternalSite" module (13.0.3)

### ISSUE THREAD

**Issue by GitHubLesCarnets** [Dolibarr/dolibarr#18103]
Hello,
We are facing a bug after upgrade from Dolibarr 9 to Dolibarr 13
Thanks and best regards.

# Bug
Dolibarr menu no more displayed with "ExternalWebSite" module (13.0.3)

## Environment
- **Version**: 13.0.3
- **OS**: Linux - Shared linux hosting (by LWS) : Linux 5.9.0-0.bpo.5-amd64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) x86_64
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: 7.2.34
- **Database**: MySQL
- **URL(s)**: ./externalsite/frames.php?idmenu=30&mainmenu=externalsite&leftmenu=

## Expected and actual behavior
The main Menu is supposed to stay (as before the upgrade)
![image](https://user-images.githubusercontent.com/87070031/124784128-ebfe9680-df45-11eb-9f10-df4a97b3c70d.png)

## Steps to reproduce the behavior
Dolibarr menu no more displayed with "ExternalWebSite" module
![image](https://user-images.githubusercontent.com/87070031/124761959-a389ad80-df32-11eb-89d6-1df87ecc4ac9.png)

## Workarround
We did a restore and upgraded to Dolibarr 12.0.5 where the issue does not appear.

**Comment by eldy** [comment]
Try to disable module and enable moduel again.

**Comment by GitHubLesCarnets** [comment]
@eldy: this is first thing I tried, but it did not solve the issue
