### ISSUE TITLE
Mass emailing: Wrong field separator character used exporting the selected recipients csv file.

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#18101]
# Bug
Mass emailing: Wrong field separator character used exporting the selected recipients csv file.
The file genrated have as field separator the "," instead ";" as should be.

Environment
Version: 13.0.3
OS: Linux
Web server: Apache/2.4.46 (cPanel) OpenSSL/1.1.1g mod_jk/1.2.41 mod_bwlimited/1.4 mod_fcgid/2.3.9 Phusion_Passenger/5.3.7
PHP: 7.4.7
Database: MySQL or MariaDB 5.6.29
URL(s): https://www.domainname.com/dolibarr//comm/mailing/cibles.php?exportcsv=1&id=3

## Expected and actual behavior
The expected behavior is generate the csv file with ";" separator, instead "," as is now.

## Steps to reproduce the behavior
[*Verbose description*]
After importing correctly a recipients list using a csv file using ";" as column separator, using the button "download" generates a csv file that use a "," as field separator instead ";" as should be. 

## [Attached files]
![image](https://user-images.githubusercontent.com/7486607/124681429-18d98c00-defb-11eb-9ec1-760e73d88b24.png)

**Comment by daraelmin** [comment]
In fact the standard separator for csv file is the coma (","). The use of ";" is a MS Excel exception.

However you can change the default separator by adding a constant in "Setup -> other" .

EXPORT_CSV_SEPARATOR_TO_USE ► String value to use as default separator to delimit fields of exported files (by default Dolibarr uses ","). Example: EXPORT_CSV_SEPARATOR_TO_USE=;

More info here : https://wiki.dolibarr.org/index.php?title=Setup_Other

**Comment by edupulpillo** [comment]
Thanks for your help

**Comment by edupulpillo** [comment]
The problem of use a "," as the standard separator, is that the fields of addresses and another columns have inside "," in their values. The problem is during import, and not during export.
