### ISSUE TITLE
Native dark mode theme

### ISSUE THREAD

**Issue by gillerby** [Dolibarr/dolibarr#18111]
# Feature Request
A native dark mode theme, already bundled with Dolibarr.

Currently all dark mode themes are addons which need extra installation, and all are paid.

**Comment by atm-maxime** [comment]
Development is in progress, try it with the hidden setup THEME_DARKMODEENABLED

**Comment by daraelmin** [comment]
Duplicate of #13132

**Comment by alsoft10** [comment]
Is dark mode theme is still in development progress status? When the development will be finished @atm-maxime ?
