### ISSUE TITLE
Partial delivery from purchase order to invoice

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#18120]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Technical error on purchase invoice after un-selecting lines. Also, when all lines are selected it goes wrong

## Environment
- **Version**: 14.0.0-beta
- **OS**:  Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: 7.0.33-50+ubuntu16
- **Database**: MySQL or MariaDB 5.7.33-0ubuntu0.16.04.1
- **URL(s)**: ./htdocs/fourn/facture/card.php?action=create&origin=order_supplier&originid=2&socid=4

## Expected and actual behavior
Creates an invoice from the only selected lines

## Steps to reproduce the behavior
When having a partial delivery from a purchase order I want to invoice this delivery.
From the "Order - Standby reception" status I want to create an invoice from the lines which I have received.
After I select "Create invoice", I have the possibility to select and nu-select the lines to invoice.
When I do so, and un-select a line and hit the "Create Draft" button, I get a technical error creating the invoice.
Invoice is created but with errors. Also, it is impossible to delete this draft invoice.

![Screenshot at 09-04-04](https://user-images.githubusercontent.com/43514101/125039196-84a42c00-e096-11eb-98b8-93c202597a3e.png)

![Screenshot at 09-13-35](https://user-images.githubusercontent.com/43514101/125039223-8b32a380-e096-11eb-9d8d-3b2e7589653a.png)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

Can you test with V14 stable ?
