### ISSUE TITLE
StockATdate and between dates ?

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#18137]
Hello @eldy and @frederic34 

thanks for the development of the **Stock At date** function that will be very useful :)

"Brain-fucking" question :

How would you calculate stock comprised between future and past (or actual) date ?

with a date comprised... NOT IN ? 

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/product/stock/stockatdate.php

![image](https://user-images.githubusercontent.com/3694135/125326136-fd7ae080-e341-11eb-8dca-855dc41392de.png)

**Comment by atm-maxime** [comment]
Stock changes with time, so a stock at a certain date (past or future) makes sense to me. Stock "between" 2 dates seems to me a nonsense. Between 2 dates a product stock can have several values...

**Comment by BebZ** [comment]
True, 
Sometimes it's better to think twice before asking a question :) 
So yes the result can reflect different and almost infinite values.

Thanks @atm-maxime 

#18137 closed.
