### ISSUE TITLE
V14-Beta Production array is empty : mrp/mo_production.php?id=2&action=consumeorproduce

### ISSUE THREAD

**Issue by WebAuxilium** [Dolibarr/dolibarr#18134]
# Bug
In tab Production, fieds for production are empty (no product, no qty)

## Environment
- **Version**: V14-beta

- **URL(s)**: mrp/mo_production.php?id=2&action=consumeorproduce

## Expected and actual behavior
[*Verbose description*]

**Comment by eldy** [comment]
Can you still reproduce ? Can you provide a screenshot to help us understand the trouble ?

**Comment by WebAuxilium** [comment]
![Capt MO](https://user-images.githubusercontent.com/61405530/125758379-cc2c253c-5d58-4259-a1b9-6707fe0972a2.jpg)

**Comment by erikvanberkum** [comment]
I have tried to reproduce this in 14.0.0, but producing a manufacturing order works fine for me.
In the above, picture Product HE91_1kg is produced from the same product HE91_1KG, I think this is impossible.

**Comment by WebAuxilium** [comment]
First thank for your answer and sorry for the wrong example with the screenhot.
However i'll confirm the problem is still here with a right article
I've done some additionnal test and i  notice : 
If the procduct have a Bom, it's ok
If the product have no Bom, it's not ok
In V13 we can create an OF without BOM and it's ok.
@erikvanberkum, @eldy 
Do you try to create an OF without BOM ?

**Comment by cfoellmann** [comment]
@WebAuxilium can you confirm the issue is still present in 14.0.1
Or close the issue if it is resolved

**Comment by erikvanberkum** [comment]
I think this issue can be closed as its moved here #18584

**Comment by WebAuxilium** [comment]
Sorry for the late answer but i'll confirm it's the same in 14.0.1
