### ISSUE TITLE
Create an invoice from provider: import products from UK to Spain

### ISSUE THREAD

**Issue by dgfmdrv** [Dolibarr/dolibarr#18138]
# Feature Request
I would like to create invoices when we bought products in the UK from Spain.

## Use case
This use case generates two invoices:
- UK store with 0% VAT. For example: product 440€ + shipping cost 30€ + 0% VAT=470€
- Shipping company (for example, TNT) creates an invoice (10.50+98.70+50=159.20€) with two rows:
1. “Tramites y gestiones aduaneras” (customs procedures and fees) in this example 50€ + 21% VAT 10.50€=60.50€
2. “IVA ADUANA” (CUSTOMS VAT) 98.70€ (21% of 470€).

Example:
![image](https://user-images.githubusercontent.com/1451834/125358622-6cb7fb00-e369-11eb-9e3a-1ad833fe5d60.png)

I'm able to create the first invoice with 0%VAT but the second TNT invoice with a line of 98.70€ (100% VAT) is impossible.

I'm doing this way but is a weird thing:
![image](https://user-images.githubusercontent.com/1451834/125359588-ca991280-e36a-11eb-9a3c-2475af41acc6.png)
For each invoice I need to calc and create an custom vat %.

**Comment by torvista** [comment]
Although I am not usung Dolibarr at the moment this use case is relevant to me, and indeed to everyone in the EU importing from the UK.
Maybe I am not understanding what is the part that is impossible, but can not the 98.70 VAT paid to customs be treated as a item/product/service of cost 98.70 but with 0% VAT added?

**Comment by dgfmdrv** [comment]
This use case should be relevant to anyone buying outside the EU. The UK may be common because of recent changes (Brexit). 

Shipping companies apply VAT and/or parcels without exception in orders from the UK but in theory, every order outside the EU should apply (**according to my knowledge**)


> Although I am not using Dolibarr at the moment this use case is relevant to me, and indeed to everyone in the EU importing from the UK.
> Maybe I am not understanding what is the part that is impossible, but can not the 98.70 VAT paid to customs be treated as an item/product/service of cost 98.70 but with 0% VAT added?

Under my understanding, Dolibarr needs to know that 98.70 is a VAT quantity to include in reports, for example here:
![image](https://user-images.githubusercontent.com/1451834/125459412-20c31411-13e9-4992-8b03-3989dab9ad4a.png)

The 98.70 needs to be a VAT quantity because the system calculates VAT in - VAT out. 98.70 is 100%VAT

**Comment by torvista** [comment]
So the issue is an accounting issue.
In truth TNT are not charging the VAT, they are collecting it on the behalf of Aduanas. You could file their invoice without the import VAT as I see in another software that they record this import VAT payment as a single expense, separately.
Is that not possible?

You are right that any user that pays import duties and wishes to account for their VAT balance will have the same issue anywhere in the world....so others must have already dealt with this issue in some way.

**Comment by dgfmdrv** [comment]
> So the issue is an accounting issue.
You could file their invoice without the import VAT as I see in another software that they record this import VAT payment as a single expense, separately.
> Is that not possible?

Hi. I don't care if this amount is registered in the invoice of the transport company or in another place.  I don't know if exists an external module for this purpose. it would be interesting to know.
Thanks 👍

**Comment by SHSV2006** [comment]
I join this thread. I want to know if there is a solution to this important feature. I am sure that most of the companies are currently importing.

**Comment by juri-ko** [comment]
Does solution exist?
