### ISSUE TITLE
How to connect database with socket access

### ISSUE THREAD

**Issue by ludogre** [Dolibarr/dolibarr#18139]
# Feature Request
There is no example in htdocs/conf/conf.php.example and htdocs/conf/conf.php.pgsql for connect a database with a socket access. :-(

## Use case
With dolibarr 13.0.3 version, with mysql database server, I've tried those values for `$dolibarr_main_db_host`:
- `localhost:/run/mysqld/mysqld.sock`
- `/run/mysqld/mysqld.sock`
- `localhost`

For the first case, I've got this error message: 

> Message: host=localhost:/run/mysqld/mysqld.sock, port=3306, user=gnagnagna, databasename=gnagnagna, Connection refused.

For the second one, I've got this error message:

> Message: host=/run/mysqld/mysqld.sock, port=3306, user=gnagnagna, databasename=gnagnagna, php_network_getaddresses: getaddrinfo failed: Name or service not known

For the third one, it's OK.

I've although successfully tried to connect to my database `gnagnagna` with user `gnagnagna` in command line.

## Suggested implementation
It would be nice to include an example of database socket connection access in htdocs/conf/conf.php.example and htdocs/conf/conf.php.pgsql , because for most popular other website, like CMS, this is the two first options that are the good one.

Thanks.

**Comment by cfoellmann** [comment]
I am pretty sure that using `localhost` will NOT give you a socket connection.
It will be the same as 127.0.0.1 and give you a tcp connection to the loopback on your host

**Comment by williamdes** [comment]
> host=localhost:/run/mysqld/mysqld.sock

It will never work, the code is not prepared to support socket mode

Here the last param is missing:
https://github.com/Dolibarr/dolibarr/blob/02ec4cf4211b462b04b52570613ceabcd2b0702a/htdocs/core/db/mysqli.class.php#L269-L272
