### ISSUE TITLE
REST api thirdparties update does ignore code_compta field

### ISSUE THREAD

**Issue by a-schild** [Dolibarr/dolibarr#18146]
When sending a put request to update a thirdparty code_compta field, then the operation returns status 200, but the field is not updated.

System: Dolibarr 13.0.2, Ubuntu 20.04, Maria DB 10.x

```
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: xxxxxxxxxxx' -d '{
"code_compta":"1234"
}' 'http://localhost/lbs/api/index.php/thirdparties/48109'
```
Response body

```
{
  "entity": "1",
  "name": "aarboard ag",
  "name_alias": "",
  "address": "Egliweg 10",
  "zip": "2560",
  "town": "Nidau",
  "status": "1",
  "state_id": "0",
  "state_code": null,
  "state": null,
  "phone": null,
  "fax": null,
  "email": null,
  "socialnetworks": [],
  "url": null,
   ...........
  "typent_code": "TE_UNKNOWN",
  "fk_prospectlevel": "0",
  "date_modification": 1626189204,
  "user_modification": "1",
  "date_creation": 1624460471,
  "user_creation": "1",
  "client": "1",
  "prospect": 0,
  "fournisseur": "0",
  "code_client": "CU2107-00004",
  "code_fournisseur": null,
  "code_compta": null,
  "code_compta_client": null,
  "code_compta_fournisseur": null,
  "note_private": null,
  "note_public": null,
  ...........
}
```

**Comment by a-schild** [comment]
The cause for this, is the call to the update method in societe.class.php

In line 271 of api_thirdparties.class.php we have this call:

`if ($this->company->update($id, DolibarrApiAccess::$user, 1, '', '', 'update')) {`

If we specify 1 instead of '' in arguments 4+5 we are able to update code_compta and code_compta_fournisseur on thirdparties.
Would a pull request for this be accepted, or what's the reason for useing '' instead of 1 as default in the REST api?

**Comment by eldy** [comment]
The parameter means  "autogenerate a value if not set". But if you provide the value into this->compta, it is included into the update.
I checked with v14.

**Comment by a-schild** [comment]
I will check this in v14, but after reviewing the v14 code I see no reason why it should work there.
The relevant code parts have not changed.

You did a PUT request and did set the code_compta field, as in my example, correct?

In line 1293 of https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/societe/class/societe.class.php $client is only set to true if $allowmodcodeclient isn't empty.
```
$customer = false;
		if (!empty($allowmodcodeclient) && !empty($this->client)) {
			// Attention get_codecompta peut modifier le code suivant le module utilise
			if (empty($this->code_compta)) {
				$ret = $this->get_codecompta('customer');
				if ($ret < 0) {
					return -1;
				}
			}

			$customer = true;
		}

```

And then later in the SQL update statement build on line 1461 we include the field only if $customer is true, but it isn't

```
if ($customer) {
				$sql .= ", code_client = ".(!empty($this->code_client) ? "'".$this->db->escape($this->code_client)."'" : "null");
				$sql .= ", code_compta = ".(!empty($this->code_compta) ? "'".$this->db->escape($this->code_compta)."'" : "null");
			}

```

**Comment by a-schild** [comment]
I did a clean v14.0.0 install and did test it again.
It's behaving differently, but still not ok.

Rest answer for teh GET of thirdparty 1

```
  "code_client": "CU2107-00001",
  "code_fournisseur": null,
  "code_compta": null,
  "code_compta_client": null,
  "code_compta_fournisseur": null,
  "note_private": null,
  "note_public": null,
```

Then I do the update
`curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: xxxxxxxxxx' -d '{ "code_compta": "1234"}' 'http://localhost/dolibarr14/api/index.php/thirdparties/1'`

Answer:
```
  "code_client": "CU2107-00001",
  "code_fournisseur": null,
  "code_compta": null,
  "code_compta_client": "1234",
  "code_compta_fournisseur": null,
  "note_private": null,
  "note_public": null,
```

But when I do a GET again, the value is not set
```
  "code_client": "CU2107-00001",
  "code_fournisseur": null,
  "code_compta": null,
  "code_compta_client": null,
  "code_compta_fournisseur": null,
  "note_private": null,
  "note_public": null,
  "stcomm_id": "0",
```

I think the correct patch would be to change the two '' parameters in api_thirdparties.php on line 298 to 1
`		if ($this->company->update($id, DolibarrApiAccess::$user, 1, '', '', 'update')) {`

Should I submit a pull request?

**Comment by a-schild** [comment]
@eldy Did you have time to look into this one once more?
