### ISSUE TITLE
Setting "default values" for input fields wont work for a lot of forms

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#18150]
# Bug
Setting "defaults" for input fields is only working for some fields in some forms.
This needs to be revisited throughout the whole UI code base.

a lot of fields are not "picking up" the defaults on load.

The quick solution should be adding the necessary code to these fields.
The proper way would be to generalize the "creation" of fields with helper methods so all fields are automatically able to fetch defaults.

## Environment
- **Version**: 13.x/develop

**Comment by eldy** [comment]
Can you provide an example of case that is not supported so we can analyze why it's wrong (the solution for default field is a generic feature so should works everywhere) ?

**Comment by cfoellmann** [comment]
comm/propal/card.php?action=create | cond_reglement_id | 2 |   |  
-- | -- | -- | -- | --
comm/propal/card.php?action=create | mode_reglement_id | 2 |   |  
comm/propal/card.php?action=create | shipping_method_id | 11

these dont work for me. for example

**Comment by ksar-ksar** [comment]
Hello,

This are selection box no ?
"default values" doesn't work for Selection boxes

**Comment by cfoellmann** [comment]
> Hello,
> 
> This are selection box no ?
> "default values" doesn't work for Selection boxes

It does work for many others. For example:

<html>
<body>


product/card.php?action=create&type=0 | fk_default_warehouse | 5 |   |  
-- | -- | -- | -- | --
product/card.php?action=create&type=1 | statut_buy | 0 |   |  

<br class="Apple-interchange-newline">
</body>
</html>
a fraction of the ones we use.

**Comment by fparrar** [comment]
Still relevant. Totally agree with cfoellman. Setting "defaults" for input fields is only working for some fields. Actually some fields doesn't have ID (example: % progress field on tasks)

**Comment by esaenz7** [comment]
This issue is still present on current version 17.0.1 as described and as was said before, it is relevant!
