### ISSUE TITLE
User Cannot be deleted, Forbidden Error

### ISSUE THREAD

**Issue by chroniclesoft** [Dolibarr/dolibarr#18153]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*I use dolibarr very 13.2, and I experience this same issue. Its frustrating.

Another one is "Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.". This shows when you intend to update an account. The error is linked with vcard*]

## Environment
- **Version**: [*13.2*]
- **OS**: [*Linux*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*ops.chroniclesoft.com, mercury.chroniclesoft.com*]

## Expected and actual behavior
[*To delete the user when the administrator did such an action, Also updating a contact information should save without the forbidden information. the Actual Behaviour is it refused deletion and upon updating user info, it shows forbidden once it is saved*]

## Steps to reproduce the behavior
[*Log in as Admin, create a user, use the user to do a transaction. Afterwards, remove the transactions tied to it, then try to delete. Also try to edit some aspect of the user and try to save, it would pop up forbidden...*]

**Comment by ksar-ksar** [comment]
Hello,

Can you try with V13.0.4 ?

Thanks

**Comment by chroniclesoft** [comment]
Hello Ksar,

We would, but does that mean we have to upgrade from our current Version or
we do a new Install instance

**Comment by cfoellmann** [comment]
@chroniclesoft have you tested this again with the updates version?
Minor releases are only bugfixes so we can only help you if you update to the latest available minor release for the version you are running.
