### ISSUE TITLE
BUG : Error configuring an external user. barcode printing is visible.

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#18160]
# Bug
Error configuring an external user. barcode printing is visible.

## Environment
- **Version**: 13.0.4

## [Attached files]

![image](https://user-images.githubusercontent.com/3288514/125919294-3b848030-6459-4898-8366-4440c2a3d87a.png)

**Comment by ksar-ksar** [comment]
Hello,

A fix has been released, can you check that it is solving the issue ?

Thanks!
