### ISSUE TITLE
Wrong base currency conversion rate in Proposal and Order

### ISSUE THREAD

**Issue by iwantan** [Dolibarr/dolibarr#18169]
# Bug
Wrong base currency conversion rate in Proposal and Order

## Environment
- **Version**: [13.0.3]
- **OS**: [Linux]
- **Web server**: [Apache]
- **PHP**: [7.2.26]
- **Database**: [MySQL]
- **URL(s)**: [htdocs/comm/propal/card.php?id=22#addline]

## Expected and actual behavior
My company base currency is IDR, so when creating Proposal and Order in IDR, the conversion rate should be 1:1

## Steps to reproduce the behavior
Step 1 Activate Multi Currency Module, Add USD as second currency with rate of 1 IDR = 0.000069 USD
<img width="1183" alt="Screen Shot 2021-07-17 at 17 40 48" src="https://user-images.githubusercontent.com/39124890/126034370-a54f8a7f-eaeb-4dca-88a1-af03883b703e.png">

Step 2 Create Proposal / Order, Currency Set to IDR, Click Create.
<img width="1164" alt="Screen Shot 2021-07-17 at 18 09 05" src="https://user-images.githubusercontent.com/39124890/126035021-c00f0881-8739-4bc7-85a9-49348b0f7d80.png">

Step 3 Currency Conversion Rate shows 14,508 IDR = 1 IDR, which should've been 1 IDR = 1 IDR Add product/service line detail, enter U.P in IDR
<img width="1166" alt="Screen Shot 2021-07-17 at 18 03 51" src="https://user-images.githubusercontent.com/39124890/126034926-a6e6f835-2432-447e-b42a-1bb2f917f74a.png">

Step 4 Preview PDF, All price are shown multiplied with 14,508 conversion rate.
<img width="1081" alt="Screen Shot 2021-07-17 at 18 04 23" src="https://user-images.githubusercontent.com/39124890/126034942-5e49c280-cd51-4a2b-8845-0ca8af82a2eb.png">

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by nanoworkssa** [comment]
This is still a bug in the latest stable version. From googling this issue, it is a major issue with many users. Can the developers address it please.
