### ISSUE TITLE
FEAT : Separate read-only and adding time on projects

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#18162]
# Instructions
Separate read-only and adding time on projects

# Feature Request
In https://yourdolibarr/user/group/perms.php?id=2
"Lire les projets et tâches (partagés ou dont vous n'êtes pas contact). Permet la saisie de temps passé, pour vous-même et votre hiérarchie (vos subordonnés), sur les tâches assignées (Feuilles de temps)."
Permission 41 : Should be Read Only
Permission 145 : Add : Writing permissions for time tracking

## Sample

![image](https://user-images.githubusercontent.com/3288514/125921099-e1fe304d-5b8a-49ff-94be-2c6d5082eda9.png)

We must not be able to add time to a project in reading

![image](https://user-images.githubusercontent.com/3288514/125921374-d715af29-2763-4f9d-ac35-8b9b64bc934a.png)

**Comment by lmag** [comment]
@FHenry

**Comment by cfoellmann** [comment]
please close

**Comment by cfoellmann** [comment]
@eldy
