### ISSUE TITLE
Impossible to make booking in ledger

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#18177]
# Bug
Impossible to make bookings in ledger. Getting error "Error Unknown column 'date_export' in 'field list'"

## Environment
- **Version**: 14.0.0
- **OS**: LINUX
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: 7.0.33
- **Database**:MySQL or MariaDB 5.7.33
- **URL(s)**: /htdocs/accountancy/bookkeeping/card.php

## Expected and actual behavior
Can choose journal en make booking

## Steps to reproduce the behavior
Try to make a booking by choosing a journal and add a subscription. It reproduces the error: Error "Unknown column 'date_export' in 'field list'
Also, the date format is changed. Using the Dutch way for date format 19-07-2021 , Dolibarr now always uses the US standard 07/19/2021.

**Comment by aspangaro** [comment]
Hi @KlaasOl 

Field "date_export" in accountancy was introduced in Dolibarr v10.

Can you verify if you have this field in table llx_accounting_bookkeeping ?

If not, try to launch with request : 
ALTER TABLE llx_account_bookkeeping ADD COLUMN date_export datetime DEFAULT NULL;

Give me returns
Good evening

**Comment by aspangaro** [comment]
Correct 14.0.1
