### ISSUE TITLE
V14.0.0 Projets and Task attachments cannot be viewed or opened

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#18171]
# Bug
[Since the update to V14.0.0 (2 days ago)
tasks show the list of attachments, but do not allow to open or download them, displaying the following message
Access denied.
You are trying to access a page, area or functionality of a disabled module or without an authenticated or unauthorised session to your user.
Current login: admin
Permissions for this user can be assigned by Dolibarr administrator via menu Home-> Users.
With previous versions (13.03) this problem did not exist. ]

## Environment
- **Version**: [14.0.0]
- **OS**: [W10]
- **Web server**: [Apache 2.4.48]
- **PHP**: [7.4.20]
- **Database**: [MariadB 10.5.10]
- **URL(s)**: [Localhost]

## Expected and actual behavior
[Being able to access attachments, as it worked in previous versions]]

**Comment by matDOTviguier** [comment]
+1 same bug here on task attachement. On projet attachement, it works well.
We name the file attached to the project by the name "task_name+file_name" as a workaround :(

**Comment by FHenry** [comment]
Fix in 14.0.1
