### ISSUE TITLE
Wrong ODT creation when contact defined in customer

### ISSUE THREAD

**Issue by strinidad** [Dolibarr/dolibarr#18170]
# Bug
When we create a proposal using an ODT template, some cases works fine but other cases the Customer information not shown.
As the PDF converts from ODT via libreoffice, the problem appears also in PDF generated because the problem is in ODT generation.

## Environment
- **Version**: 13.0.1
- **OS**: Debian 10
- **Web server**: Apache
- **PHP**: 7.3.27
- **Database**: postgresql 11
- **URL(s)**: 

## Expected and actual behavior
The expected result when you create a proposal is to get all variable fields filled, but some cases the customer info not shown.
But I tested and found that when a contact is applied to a customer, the info shown in the "$this->vars" and then in the ODT template, is the info of the contact and not the customer.

## Steps to reproduce the behavior
1. Create a customer (Third Party Client)
2. Create a contact linked to step 1 customer
3. Create a proposal using ODT template
4. Generate the document - FAIL !!!
5. Remove the contact from the customer (Disabling doesn't works) you must remove the contact.
6. Come back to proposal and generate the document - CORRECT !!!

**Comment by trekmorris** [comment]
Could you try to put MAIN_USE_COMPANY_NAME_OF_CONTACT = 0 in setup other ?

**Comment by strinidad** [comment]
@trekmorris,

Yes, that solves the issue.

Thank you for the reply
