### ISSUE TITLE
Prospect - Filter "Do not contact" not working - Showing "To contact" instead

### ISSUE THREAD

**Issue by AurelienBISOTTI** [Dolibarr/dolibarr#18185]
# Bug
Prospect - Filter "Do not contact" not working - Showing "To contact" instead

## Environment
- **Version**: 13 and 14
- **OS**: Debian 10
- **Web server**: nginx
- **PHP**: 7.4
- **Database**: MariaDB 10.5
- **URL(s)**: /societe/list.php

## Expected and actual behavior
[*Expected to see the good "prospect status" filtered when selecting "Do not contact"*]

## Steps to reproduce the behavior
[*Select "Do not contact"*]

## [Attached files]
[*Files*]
![Capture](https://user-images.githubusercontent.com/12530585/126353487-3fd45712-8f97-438c-b207-a421435ffe6e.PNG)

**Comment by ksar-ksar** [comment]
Hello,

A fix has been posted, can you try it ?

**Comment by AurelienBISOTTI** [comment]
Tried it on v13, it works now

**Comment by AurelienBISOTTI** [comment]
You merge it and you close the ticket or I close the ticket myself ?

**Comment by ksar-ksar** [comment]
Thanks for the confirmation

When it will merge, we will close it.
