### ISSUE TITLE
After 13.0.2 to 13.0.4 update multiprices cannot be changed

### ISSUE THREAD

**Issue by pintybor** [Dolibarr/dolibarr#18199]
After updating from version 13.0.2 to 13.0.4 when I try to edit customer prices for level 1 and level 2 prices are not changed. There is no error and record saved is returned but prices are not updated or changed.

**Comment by toni-mx** [comment]
Some temporary fix here...
https://github.com/Dolibarr/dolibarr/issues/18473

I don't know what else is changed by doing that. Also applies to V.13.0.2 just need to find the right lines.

Hope it helps

**Comment by pintybor** [comment]
Hi!

The solution given in #18473 does fix this issue.
Thank you for helping me out with this.

Regards!

**Comment by pintybor** [comment]
This issue has been fixed since version 15.0.2 and later.
