### ISSUE TITLE
Discussion about improving the email collector

### ISSUE THREAD

**Issue by BAKFR** [Dolibarr/dolibarr#18195]
Hi,

New user to Dolibarr, I plan to use intensively the email collector. After looking the source code, I've realized that there is some missing features I need, and that the module itself is poorly written (no documentation, filter not working, lot of commented code, etc.).

I plan to fix bugs and add features to suit my needs.
I've opened this issue to list theses things, discuss how to do it, and more generally share knowledge.

**What i need that isn't implemented:**

- The ability to detect *users*, *third-parties* and *contacts* from all members of an email thread (from, to, cc and bcc).
- The ability to create an Event with several *users* and several *contacts* when an email is received.

**Bugs I found so far:**

- `CC` and `BCC` filters are not working.
- filter `withouttrackingidinmsgid` probably make the inverse of what we want.
- `withtrackingid` and `withtrackingidinmsgid` filters do the same thing (is it expected ?)

**Questions:**
- The `to` filter accept wilcards `*` , but other address filters doesn't (from, cc, bcc). What was the intent in adding this feature ?

NOTE: I use the develop branch, but all these bugs are present in v13 and v14.

**Comment by BAKFR** [comment]
`smaller` and `larger` filters are not working in my config, probably due to php using IMAPv2 instead of IMAPv4. I guess they've never worked.
I'm not planning to fix them, but it would be a good thing to either fix them or remove them (unless it works for other config).

**Comment by elsp1991** [comment]
Hello Bakfr,

Happy to hear that someone else is also planning to intensively work with email collector. I think so far dolibarr have become a great ERP system but its CRM are bottlenecked cause of the lack of a properly working Email-collector module. For me the most important aspect of the CRM is keep all the communication with customers and supplier in an accessible system and not in the personal emails of each employee. The past months I have tried several things with the email collector and I wanted to share here also the problems and missing features of it that are required to have a minimal version that can be helpful. 

- Email collector records the receiving email as event but is not assigning it to the related object always.
- Email collector is not receiving attachments. Ideally should record the email as event and link the attachment in the related object if any. (This feature would be very useful for the hiring process when you receive an application with the CV and cover letter attached)
- Ability to tag an email from your email client with a certain word (by replying to it for example) to tell the email collector to record it and link it to the a certain object (order, invoice, job application, shipment, etc) of dolibarr
- Email collector is not able to create contacts and assign them to Third party (you mentioned already)
- Email collector filter parameters has limited amount of chars in the field limiting the available parsing
- Email collector can not assign custom fields properly if used with SET:EXTRACT
- Email collector for parsing responses is not running consistently

Are you planning to work on it by yourself ?

**Comment by BAKFR** [comment]
I'm not sure yet if I will works on it. I've looked into the code these past days, and the whole module filled with dead code and bugs. The best approach would be to completely rewrite the module, but it's not my priority and I think it would take some time for me to understand how Dolibarr code works. I haven't found any developer doc on existing objects and theirs attributes.

That being said, it's always a good thing to gather info on what's works and what's doesn't works.
