### ISSUE TITLE
Installation - Switch from other billing system to Dolibarr

### ISSUE THREAD

**Issue by carmelchas** [Dolibarr/dolibarr#18197]
# Feature Request
In preparation for switching to Dolibarr as a billing platform I am importing customers and their balances. I am creating an Invoice to reflect monies owed, but cannot identify a way to reflect credit balances. (e.g. An account has a $10 credit balance and all their invoices are paid.

How do I initialize a customer in Dolibarr with a credit balance that will automatically be applied to their next invoice.

## Use case
We are migrating customers into the  system and establishing a baseline for their billing.  For customers that have outstanding invoices in the legacy billing system we are creating an invoice to reflect the amount due.

We have a small number of customers that have a credit balance that is to be applied to their next invoice.

Is the an existing way to reflect a credit balance in such a way that it gets consumed when the next invoice is generated?

**Comment by priojk** [comment]
I assume that opening bookings for the various balances should be possible via journal entries - without generating invoices to create these balances. However, I have not yet looked into this functionality in detail.

As a workaround, you can create an invoice about say $1 and then register a payment of $101 and your customer ends up with a balance of $100 which can be applied to the next invoice. But accountants will definitely not like this way of creating opening balances.

Overall, I guess this kind of discussion would be better placed in the forum to get some more answers from users of the system.

**Comment by carmelchas** [comment]
The question was posted on the forum over a week ago with no responses.

Thank you for your response.
