### ISSUE TITLE
link contacts/addresses

### ISSUE THREAD

**Issue by RANDOMLY-OBFUSCATED** [Dolibarr/dolibarr#18205]
Hi!

# Feature Request
have the possibility to link contact from another thrid-party

## Use case
1. I add a pro customer and I need to add multiple contacts
2. the contacts are already my customers and have some contacts/addresses
3. I simply add a link to a contact card
4. I delete customer and I have to chose to import the contact to replace the future dead link

Real false good idea or useful?
Thanks.

**Comment by cfoellmann** [comment]
I still like the idea.
I hope I understand the usage right.

It is "just" the ability to add a contact to multiple thirdparties, right?

**Comment by cfoellmann** [comment]
@18info still using dolibarr and bugged about not being able to link contacts?

**Comment by 18info** [comment]
Yes, absolutely. (apologies, I never seen your first answers)

**Comment by RANDOMLY-OBFUSCATED** [comment]
@cfoellmann Yes, absolutely. (apologies, I never seen your first answers)

**Comment by RANDOMLY-OBFUSCATED** [comment]
auto-closed as "completed" but can't see the feature… (just to keep it open)

**Comment by cfoellmann** [comment]
we should reopen this. I promise to get this done in 2023 😞

**Comment by RANDOMLY-OBFUSCATED** [comment]
waoooo… The life's lag is still working :-/. Sorry, really.
> It is "just" the ability to add a contact to multiple thirdparties, right?

No. It's the ability to re-use contact information to create/link a new thirdparty
Possible to discuss it by chat ; if you want. I send you a message with my personal contact informations.
Best regards,
