### ISSUE TITLE
Sales Tax Report

### ISSUE THREAD

**Issue by riker513** [Dolibarr/dolibarr#18204]
# Feature Request
It would be very helpful to show the sum of VAT collected or paid for during a given month.

## Use case
For example, with 19% VAT, suppose I bought for 119 and 238, and sold goods for 1190, all within one month. Then the VAT report should show 19+38-190=-133 for that month. Such that I know how much I owe the tax office (133 in this case), without having to open each invoice by hand and summing up the VAT amounts manually.

## Suggested implementation
For instance within the accounting module.

## Suggested steps
I'd think this amounts to locating the right fields in the database, writing a suitable SQL query, inserting it into the PHP file to generate an extra line with the information on the accounting sheet.

Kind regards

**Comment by riker513** [comment]
The taxes module is able to do this in principle, but it sorts the transaction according to invoice date. The tax office however requires sorting for the actual dates of payment.

**Comment by dpriskorn** [comment]
This is possible with a SQL query. You are welcome to contact me if you want help creating such a query.
