### ISSUE TITLE
Removing a tax or social charge does not remove the related entry in the bank

### ISSUE THREAD

**Issue by iouston** [Dolibarr/dolibarr#18201]
# Bug
- add a tax or social charge
- paid there
- classify it as paid
- remove the social or tax burden
- the bank payment is always present

If i reopened my tax or social burden and remove my payement, the bank payment is removed
In my opinion there is a problem, the button that deletes the whole should logically delete the bank entry

## Environment
- **Version**: 13.03

**Comment by riker513** [comment]
Confirmed this. It's really quite a big problem.

**Comment by iouston** [comment]
still relevant ?
