### ISSUE TITLE
Wrong behavior in leave request

### ISSUE THREAD

**Issue by HythamSoliman** [Dolibarr/dolibarr#18219]
# Bug
[*The number of leave days is wrongly calculated, plus the system didnt consider the Sunday as working day*]

## Environment
- **Version**: [*14.0.0beta*]
- **OS**: [*saas*]
- **Web server**: [*Apache 2.4.48*]
- **PHP**: [*7.3*]
- **Database**: [*MySQL*]
- **URL(s)**: [*holiday/card.php*]

## Expected and actual behavior

1- When entering dates in Sundays it give an error that is not a woking day, although it is defined as a working day. even this message sometimes appear on Mondays as well, it is at the attachement.

2- also when enter a date from and next day in the date to and both are morning, so it calculate only half day 0.5 days
Please see the attachement. 

Thank you

<img width="1675" alt="wrongLeaveDays" src="https://user-images.githubusercontent.com/13718660/126900215-0d1f4598-a2e0-4944-a407-7c7cc1da34ed.png">
<img width="1675" alt="WrongWorkingDays" src="https://user-images.githubusercontent.com/13718660/126900219-cea1daa8-abdc-43ab-a8a7-6372ea94ce3b.png">

**Comment by ksar-ksar** [comment]
Hello,

Can you try to update to V14.0.0 stable version and not the beta ?

**Comment by HythamSoliman** [comment]
Tried with the V14.0.0 stable version and the calculation is still same 0.5 day! which is wrong

Moreover, when friday & Saturday are off means, any leave from Thursday morning till Sunday Afternoon should be calculated as 2 days only not 3 days, please have a look at attachment.

<img width="1675" alt="Screen Shot 2021-07-31 at 12 45 29 AM" src="https://user-images.githubusercontent.com/13718660/127718920-87f45300-1b04-4dc5-b9ad-7323b94fadbb.png">

**Comment by HythamSoliman** [comment]
Moreover, when select a user at Agenda and trying to show the leaves also, it show all leaves for all employees not only the selected user.

<img width="1459" alt="Screen Shot 2021-07-31 at 1 02 07 AM" src="https://user-images.githubusercontent.com/13718660/127719516-b585cd22-7bac-4658-a352-d8df307e5ff6.png">

**Comment by HythamSoliman** [comment]
Our working days from Sunday till Thursday, we have friday and saturday off! we still having this message!

![sundayoff](https://user-images.githubusercontent.com/13718660/128323017-21fba02b-54df-4f54-bb91-eb46313864a1.jpeg)

**Comment by BebZ** [comment]
Hello Hytham, 
When you say : when friday & Saturday are off means, any leave from Thursday morning till Sunday Afternoon should be calculated as 2 days only not 3 days, please have a look at attachment.

There is a special calculation system in France for leaves I know... Sometimes complicated to understand.
When a person has 5 weeks paid vacation, it means 5 full weeks (30days i guess), so when they take, for example 5 times 5 days
the accountant has to remove + 1 day each time... 
I don't have the specific details, but maybe that's the source of the problem. An option should ask : How many days off you contribute to in the year... So for France when you contribute to 25 days, if you take 5 days off it is 5, when you contribute to 30 days and you take 5 days, it is 5+1... Maybe an HR expert could explain better what i mean ?
PS : I don't use HR modules (yet)

**Comment by HythamSoliman** [comment]
@BebZ Thanks for the clarification
I believe there should be an option where we can control the begaviour without the manual HR employee interaction. Hope so.

**Comment by HythamSoliman** [comment]
@ksar-ksar 
any more info needed ?

**Comment by raulnvrz** [comment]
@HythamSoliman This issue has been around for a long time since several versions ago.

I prefer to made my own function to calculate the days, and modify with a hook using JQuery, to edit the columns with the correct input.

Regards
