### ISSUE TITLE
Bug: UI: when a confirmation dialog appears and "yes" is highlighted Enter selects "no" 

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#18211]
# Bug
I want the system to make it easy for me to handle all the confirmation that appear everywhere

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: nginx/1.20.1
- **PHP**: fpm-fcgi 7.4.20
- **Database**: PostgreSQL 13.3
- **URL(s)**: /ticket/card.php?action=view&track_id=53wl8phbymtsyvkd

## Expected and actual behavior
Enter selects the highligted button

## Steps to reproduce the behavior
Create a ticket. 
Click on hold
press enter

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by Hystepik** [comment]
Hello,
It works for me in last version of 13.0.4

**Comment by dpriskorn** [comment]
Great! I'll close this then.
