### ISSUE TITLE
Support ORDER_ENABLE_NEGATIVE_LINES

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#18210]
# Feature Request
We currently have FACTURE_ENABLE_NEGATIVE_LINES but no equivalent for order lines it seems. See https://wiki.dolibarr.org/index.php?title=Setup_Other

## Use case
Add a discount on an order and let it propagate to the invoice.

**Comment by BebZ** [comment]
And also, negative quantities could handle "returns" from customers :) if we "ship" a negative qty it makes a positive movement. it is a quick workaround to handle customer returns in orders.

**Comment by dpriskorn** [comment]
Interesting idea. Could you create a new issue for that and link it in your post above? 😃
