### ISSUE TITLE
Dolibarr 14 - Error - create a member

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#18212]
# Bug
Error if you create a member in Dolibarr 14.0.0 without enter a URL.

Inputs are:
- member id
- password
- member type
- type: individual
- last name
- first name

want save with [create member]
get error  **Unknown column 'url' in 'field list'**

## Environment
- **Version**: Dolibarr 14.0.0 (Sourceforge zip)
- **OS**: Windows 10 V21H1
- **Web server**: Apache httpd-2.4.35-win64-VC15
- **PHP**: PHP 7.2.19-win64-VC15
- **Database**: MySQL 5.7.24
- **URL(s)**: htdocs/adherents/card.php

![grafik](https://user-images.githubusercontent.com/45215329/126807806-aec7e23e-6380-42b6-9af0-71dc87d2c69e.png)

**Comment by ksar-ksar** [comment]
In fact the issue is that in V14, a new field has been introduced : 
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/migration/13.0.0-14.0.0.sql#L501

But not on the install script : https://github.com/Dolibarr/dolibarr/edit/14.0/htdocs/install/mysql/tables/llx_adherent.sql
