### ISSUE TITLE
[DB_ERROR_NOSUCHFIELD] Unknown column 'd.url' in 'field list'

### ISSUE THREAD

**Issue by AhmedFatehy** [Dolibarr/dolibarr#18222]
# Bug
`[DB_ERROR_NOSUCHFIELD] Unknown column 'd.url' in 'field list'`
When I update a third-party prospected account ( only main account without related users it gives me this Error, while the debug bar appears the SQL code like below

`SELECT
    d.rowid,
    d.ref,
    d.ref_ext,
    d.civility AS civility_code,
    d.gender,
    d.firstname,
    d.lastname,
    d.societe AS company,
    d.fk_soc,
    d.statut,
    d.public,
    d.address,
    d.zip,
    d.town,
    d.note_private,
    d.note_public,
    d.email,
    d.url,
    d.socialnetworks,
    d.phone,
    d.phone_perso,
    d.phone_mobile,
    d.login,
    d.pass,
    d.pass_crypted,
    d.photo,
    d.fk_adherent_type,
    d.morphy,
    d.entity,
    d.datec AS datec,
    d.tms AS datem,
    d.datefin AS datefin,
    d.birth AS birthday,
    d.datevalid AS datev,
    d.country,
    d.state_id,
    d.model_pdf,
    c.rowid AS country_id,
    c.code AS country_code,
    c.label AS country,
    dep.nom AS state,
    dep.code_departement AS state_code,
    t.libelle AS TYPE,
    t.subscription AS subscription,
    u.rowid AS user_id,
    u.login AS user_login
FROM
    llx_adherent_type AS t,
    llx_adherent AS d
LEFT JOIN llx_c_country AS c
ON
    d.country = c.rowid
LEFT JOIN llx_c_departements AS dep
ON
    d.state_id = dep.rowid
LEFT JOIN llx_user AS u
ON
    d.rowid = u.fk_member
WHERE
    d.fk_adherent_type = t.rowid AND d.entity IN(1) AND d.fk_soc = 1`

I found llx_adherent Table doesn't contain any column called URL

## Environment
- **Version**: [*15.0.0-alpha*]
- **OS**: [*Windows 10*]
- **Web server**: [*Wampserver 3.1.4 64 bit*]
- **PHP**: [*PHP version 7.2.10*]
- **Database**: [*MySql 5.7.23*]
- **URL(s)**: [*http://dolibarr.acc/societe/card.php?socid=1*]

**Comment by ksar-ksar** [comment]
Seems to be the same for V14.0.0
![image](https://user-images.githubusercontent.com/35605507/127219840-b7e9d851-3f83-4a18-a169-0f49804db299.png)

**Comment by ksar-ksar** [comment]
Linked to #18212

**Comment by ksar-ksar** [comment]
FIX : #18255
