### ISSUE TITLE
' bug when generating quote pdf

### ISSUE THREAD

**Issue by tonyvsz** [Dolibarr/dolibarr#18250]
# Bug
the `'` character is not encoded when generating a pdf for a quote, `&apos;` appears since dolibarr update.

## Environment
- **Version**: 14.0.0
- **OS**: Linux (mutualisé OVH)
- **Web server**: Apache
- **PHP**: 7.3.27
- **Database**: MySQL 5.5.30
- **URL(s)**: -

## Steps to reproduce the behavior
generate a quote with `'`, preview pdf

Also, after this bug, I updated the version of TCPDF but it doesn't change anything

## [Attached files]
![bug](https://user-images.githubusercontent.com/87755952/127168463-cb501927-1245-4494-8116-bf9043b1dcef.png)
![php](https://user-images.githubusercontent.com/87755952/127168773-4fcfa1b9-4f2a-4f6b-b2fa-85c65a3b0eb9.png)

Thanks

**Comment by flemarie** [comment]
I confirm the bug. Test with different php version. This is a problem that concerns all pdfs (proposal, invoicing, etc.). It is an important problem. The proposals are not clean. We have to go back and put version 13 back

**Comment by Crashone** [comment]
I also confirm this bug.

**Comment by Cyril35** [comment]
Bonjour,
Bug toujours présent en version 14.0.1 quelque soit la base de donnée (Latin, UTF8...)
De plus il'n'est pas que sur la génération des PDF, il en est de même dans l'envoi d'un mail (propal, commande....)

Hello,
Bug still present in version 14.0.1 whatever the database (Latin, UTF8 ...)
In addition, it is not only about the generation of PDFs, it is the same when sending an email (propal, order ....)

**Comment by BenoitPel** [comment]
same for me on 14.0.1

**Comment by matDOTviguier** [comment]
Sorry, duplicate issue now deleted, I confirm this critical bug too from 14.0 to 14.0.1

**Comment by tomtoom1978** [comment]
same problem on 14.0.1

**Comment by ibuiv** [comment]
Bug non reproduit chez moi
Après tests
Le Bug n'apparait seulement que si le module  Editeur WYSIWYG est activé
(Mauvaise solution temporaire : désactiver le module WYSIWYG, retaper les portions des champs à probleme and generer le PDF)
Pas le temps en urgence de mon côté, mais si cette piste peut débloquer le probleme ;)

Bug not applying on my instance
With many tests : 
Bug only appears if WYSIWYG module is activated 
(bad temporary solution : disactivate WYSIWYG, retype the fields with problems and Generate PDF)
not enough time now to repair but if someone can ^^

**Comment by matDOTviguier** [comment]
The WYSIWYG module generates the `'` via `&#39;` and **dolibarr 14.0+** generates PDF with `&apos;` @eldy , it seems to be critical ...

**Comment by matDOTviguier** [comment]
`'` is encoded `&#39;` in WYSIWYG

**Comment by Cyril35** [comment]
Hello,
on my installation even by deactivating the WYSIWYG module, all the products already filled with a description containing an ' are incorrectly generated in PDF.

**Comment by matDOTviguier** [comment]
Yes @Cyril35 you have to replace `&apos;` everywhere. Mailing module is impacted too.

**Comment by tonyvsz** [comment]
Hello, version 14.0.2 seems to have solved the problem, the generation of pdf shows `"`.

**Comment by Crashone** [comment]
In my case, the bug is not solved at all in version 14.0.2
