### ISSUE TITLE
Field 'ref' doesn't have a default value on Dolibarr 14.0.0 fresh install on adherents import.

### ISSUE THREAD

**Issue by oandradesanchez** [Dolibarr/dolibarr#18266]
# Bug
[*When importing from the exemple excel or csv file a list of members the new field 'ref' can't be assigned*]

## Environment
- **Version**: [*14.0.0*]
- **OS**: [*Debian Linux last stable*]
- **Web server**: [*Apache last stable*]
- **PHP**: [*PHP 7.4*]
- **Database**: [*MariaDb last stable*]
- **URL(s)**: [*N/A*]

## Expected and actual behavior
[*Expected : i can import my members by importing an csv file. Actual : i can't.*]

## Steps to reproduce the behavior
[*Just try to import one member with the exemple csv file*]

## [Attached files]![Capture d’écran du 2021-07-28 12-19-39](https://user-images.githubusercontent.com/1705445/127307419-3e173e37-4409-44bb-8cf3-667f24f79017.png)
[*Files*]

**Comment by daraelmin** [comment]
Works for me

**Comment by scenaristeur** [comment]
bug for me too v14.0.1

![image](https://user-images.githubusercontent.com/4020744/134945125-f980c1cf-0c19-4202-bda4-e3a819df338c.png)

**Comment by daraelmin** [comment]
Seems to be fixed on 14.0.2
I cannot reproduce any more

**Comment by scenaristeur** [comment]
migrated to 14.0.2 but always same issue,

![image](https://user-images.githubusercontent.com/4020744/135050429-4acc021b-d38b-4bbe-a0a1-0ab17ebb8f1e.png)

 + i've seen another probleme, I don't think but perharps is it linked : explaination of the "Nature" field should be "Personne physique/Personne morale" not "Matière Première/Produit Fabriqué"

![image](https://user-images.githubusercontent.com/4020744/135050219-4b8cb712-fc11-48c6-aad8-1a7ac274f7c5.png)

@daraelmin you can test it in place at https://bricodeurs.doli.bar/imports/import.php?leftmenu=import with
 "issue18266" as login and pass

**Comment by daraelmin** [comment]
Try to launch install script please.

**Comment by daraelmin** [comment]
I have lauch the install script on the installation above.
I'm on my mobile phone, so I can not test import now, bit I'll try soon.

**Comment by scenaristeur** [comment]
thxs @daraelmin, i've just tested the import but still got the same message.

**Comment by franckhomer** [comment]
Any idea?

**Comment by elesouef** [comment]
I'm facing the same issue. Are there any progress on this issue ?
Thanks :)

**Comment by scenaristeur** [comment]
Sadly, not for me

**Comment by SiM** [comment]
Same problem here on 14.0.3.
The import was working well on 13.x

**Comment by elesouef** [comment]
UP on this topic. This issue prevents some users to populate Dolibarr. Athough not critical, I consider it a major issue.

**Comment by elesouef** [comment]
Problem solved in 14.0.4 !

**Comment by daraelmin** [comment]
Hi @aplose,
Could you close this bug ?
Thx
