### ISSUE TITLE
Recruitment mask (customized number) did not work

### ISSUE THREAD

**Issue by soebadri** [Dolibarr/dolibarr#18279]
# Bug
The customized numbers in the Recruitment module did not work

## Environment
- **Version**: Dolibarr 14.0.0

**Comment by ksar-ksar** [comment]
Hi,

What does that mean "do not work" ?

**Comment by soebadri** [comment]
Hi, 

I change the advance numbering models with mask: {dd}{yy}, it did not change when i create  a new job position. 

so at the moment i only used standard numbering (JOB0501-0001)

**Comment by panchtatvam** [comment]
I confirm the bug. I'm also not able to update the mask. Only the predefined masks work

**Comment by Zulgrib** [comment]
Hello, the code was merged in develop but we didn't see it appear in V16, do we have a chance to see it merged with V17 or are there pending issues with the code merged that would prevent the advanced numbering to register the constant when clicking modify?
