### ISSUE TITLE
Export order template showed <b>Warning</b>:  Illegal string offset 'c.ref' in htdocs/imports/emptyexample.php</b> on line <b>111</b><br />

### ISSUE THREAD

**Issue by Yuwei9291** [Dolibarr/dolibarr#18289]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
File export error. 
## Environment
- **Version**: [*Affected Dolibarr version(s)*]Dolibarr 14.0.0
- **OS**: [*Server OS type and version*]CentOS 8
- **Web server**: [*Webserver type and version*]NGINX 18
- **PHP**: [*PHP version*]PHP 7.4.19
- **Database**: [*Database type and version*]Mysql 8
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]
Activate module import and export
Tools > New import > Sales Orders  click right arrow > download csv or xlsx file
Download correct file  the file should be a template of order .

But the xlsx file could not be opened and csv showed as follow :
<br />
<b>Warning</b>:  Illegal string offset 'c.ref' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.ref_client' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.fk_soc' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.fk_projet' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.date_creation' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.date_valid' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.date_commande' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.fk_user_modif' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.fk_user_valid' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.fk_statut' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.remise_percent' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.total_tva' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.total_ht' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.total_ttc' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.note_private' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'c.note_public' in <b>/www/wwwroot/xxxxxxx/htdocs/imports/emptyexample.php</b> on line <b>111</b><br />
<br />

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by Hystepik** [comment]
There is a fix #18294
