### ISSUE TITLE
Dolibarr cannot handle nested groups from ActiveDirectory

### ISSUE THREAD

**Issue by spirritus** [Dolibarr/dolibarr#18295]
# Bug
With active directory  it is possible, and widely used, to nest groups, e.g. there are three groups, A, B and C.
A contains B and B contains C. Users are listed in C. When groups are imported with sync_groups_ldap2dolibarr.php and memberships are resolved  this recursion has to be traversed. Currently the group A is just empty. This is wrong behaviour.

## Environment
- **Version**:  tested with 14
- **OS**: debian 10
- **Web server**: nginx
- **PHP**: 7.3.29
- **Database**: postgres

## Expected and actual behavior
Als transitive groups are resolved for user group membership of nested groups.

## Steps to reproduce the behavior
See above.

**Comment by atm-maxime** [comment]
Agreed
