### ISSUE TITLE
Member subscription confirmation email sent even if mandatory fields are missing

### ISSUE THREAD

**Issue by Jacques83300** [Dolibarr/dolibarr#18304]
**Bug**
By using the auto-subscription formular, when the user sent it, a confirmation email is sent back to him. In V14.0.0, it seems the email is sent twice.

**Environment**
Version: 14.0.0
Web server: Apache

**Expected and actual behavior**
The email shoud be sent (and received) only once.

**Steps to reproduce the behavior**
Fill the subscription formular and send it. You should receive two confirmation emails.

**Comment by daraelmin** [comment]
Hi @Jacques83300,

May this issue related to this one : #17316 ?

Cheers

**Comment by Jacques83300** [comment]
Hi [daraelmin](https://github.com/daraelmin),

I don't think. The problem is not linked to a payment but well to a new member subscription. No payment is active on our site.

Best regards

**Comment by Jacques83300** [comment]
After a deeper investigation, it appears the message is not sent twice but the problem is the confirmation message is sent even if a mandatory field is missing. This should not as it may let think to the user his subscription is well done which is not the case as the data are not copied into the database.
I update the title of this issue

**Comment by daraelmin** [comment]
> After a deeper investigation, it appears the message is not sent twice but the problem is the confirmation message is sent even if a mandatory field is missing. This should not as it may let think to the user his subscription is well done which is not the case as the data are not copied into the database. I update the title of this issue

What mandatory field is relatés to yozr issue?
 Do you use exterbal module ?

**Comment by Jacques83300** [comment]
The problem seems to be related to the **required extra-fields**.
I think the issue is linked to a bug in public/members/new.php:
```
		// Fill array 'array_options' with data from add form
		$extrafields->fetch_name_optionals_label($adh->table_element);
		$ret = $extrafields->setOptionalsFromPost(null, $adh);
		if ($ret < 0) {
			$error++;
		}

				
		$result = $adh->create($user);
		if ($result > 0) {
			...
```
In this code, the extrafields are checked then the member is created without regarding the result of the check.
To fix it, I just added a test before the member creation:
```
		// Fill array 'array_options' with data from add form
		$extrafields->fetch_name_optionals_label($adh->table_element);
		$ret = $extrafields->setOptionalsFromPost(null, $adh);
		if ($ret < 0) {
			$error++;
		}

		if (!$error) {
			$result = $adh->create($user);
			...
```
