### ISSUE TITLE
Wrong User Permissions

### ISSUE THREAD

**Issue by HythamSoliman** [Dolibarr/dolibarr#18303]
# Bug
Wrong User Permissions by missing the group persmission

## Environment
Version: [14.0.0]
OS: [saas]
Web server: [Apache 2.4.48]
PHP: [7.3]
Database: [MySQL]
URL(s): [user/perms.php]

## Expected and actual behavior
Creating new user and assigning him to a group does not inhiret the group permissions!
please have alook at the below attachement
User "Aya" has only 9 permissions and she is part of the Sales group, while the sales group has 32 permissions!

<img width="1909" alt="Screen Shot 2021-08-01 at 10 04 29 AM" src="https://user-images.githubusercontent.com/13718660/127764069-0a7911d7-a35f-46d4-b444-6d9c1ebfca85.png">
<img width="1682" alt="Screen Shot 2021-08-01 at 10 06 24 AM" src="https://user-images.githubusercontent.com/13718660/127764073-b2acfe75-8a84-4184-a52e-c7a92e5a31e9.png">

**Comment by Hystepik** [comment]
Hello,
It works for me in last version of 14.0

**Comment by TheTrueTom** [comment]
I do have the same problem on 14.0.2
I haven't been able to find any way to solve this yet.

**Comment by inoveaconseil** [comment]
I can't reproduce the in 14.0.3.
