### ISSUE TITLE
14.0.0 gone from Sourceforge

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#18323]
A short while ago I installed 14.0.0 from Sourceforge as it was presented as Stable, but now it is gone from the download area at Sourceforge!

What happend?

**Comment by futurehousestore** [comment]
it's here https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/14.0.0/

**Comment by hasse-basse** [comment]
Thanks! I was afraid it was withdrawn because too buggy. 

But it can not be found here; https://sourceforge.net/projects/dolibarr/files/
