### ISSUE TITLE
Bug:  Warning: Undefined property: stdClass::$ficheinter in C:\wamp64\www\dolibarr-140\htdocs\comm\propal\card.php on line 124

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#18338]
## Environment
- **Version**: 14.0.1
- **OS**: Windows NT
- **Web server**: Apache/2.4.48 (Win64) PHP/8.0.9
- **PHP**: apache2handler 8.0.9
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB
- **URL(s)**: /comm/propal/card.php?id=1

**Comment by cerguey** [comment]
Environnement de travail :  
→ Version 14.0.5
→ OS Windows (WampServer)
→ Serveur Apache 2.4.52
→ Php : 8.0.14
→ Base de données MariaDB 10.6.5
→ MySql 8.0.27
