### ISSUE TITLE
MRP: Manufacturing order set up cost of manufactured product 

### ISSUE THREAD

**Issue by elsp1991** [Dolibarr/dolibarr#18336]
# Feature Request
Apply the total cost of BOM in the cost the newly manufactured product. So the user can have "weighted average cost" for manufactured products. Since a manufactured product is "not for purchase" its not possible to set a cost and it's cost is anyways variable depending on the raw material

## Use case
A typical use case of the MRP module includes a "Raw Material" that the user typically buys from a "Vendor" and "manufactured product" that is being produced by a Manufacturing order. For the "raw material" when is bought from a vendor and have been received the reception will create a stock movement and will calculated and update the "Weighted average price". This is a very nice feature because the user can see how much the stock of this product worth. This feature is not available for "manufactured products" and since the manufactured products are "not for purchase" the user is not even able to input the cost of them.
Since a MO (manufacturing order) is creating a stock movement for the "manufactured product" I think it would make sense to sum up the cost of all product of the BOM and provided this number as the cost of the "manufactured product". This way the user know the worth of the stock of the "manufactured product" and also can use this product in other BOMs

## Suggested implementation
From my understanding each stock movent has a cost. Since the MO is creating a stock movement for the produced product should be relatively straight forward to implement, given my assumption is correct

**Comment by atm-maxime** [comment]
Yeah your right, but for now the manufactured product has no value when it's incrementing the stock. It's because the MO does not contains the value of the human power needed but only the raw materials value. So setting a value would be wrong because not including production costs

**Comment by atm-maxime** [comment]
Wait for #17715 which will give datas to have better value for manufactured product

**Comment by elsp1991** [comment]
Right now the way we deal with the lack of man power is to always add a "service" in the BOM that is the cost of labor this works nicely for us. Cause the service basically is not in the stock management so its purely contributes only in the cost of the BOM

**Comment by elsp1991** [comment]
This issue have been fixed already in this issue #16072 and merged in version 14.0
