### ISSUE TITLE
New Customer / Prospect always gives "New prospect"

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#18346]
Dolibarr 12.0.5

After clicking Third-party, no matter if I click "New customer" or "New prospect", the "Prospect / Customer" field is always set to "Prospect". (If I click "New vendor", the result is ok).

![cust](https://user-images.githubusercontent.com/11036018/128411919-af8ceb42-4af0-4433-9e1a-9acc9d616e95.png)
![prosp](https://user-images.githubusercontent.com/11036018/128411924-12f48699-5040-4e62-809f-bf1cfe286d2e.png)

**Comment by trekmorris** [comment]
Hi 

Have you tried to set the default type of new customer in third-party module ?
There is a " Default thirdparty type for "New customer" creation form " option you could set it to " customer " .

**Comment by bos4711** [comment]
It's set to "Customer" already. We set it up like that last year and have never changed it.
![2021-08-07_081255](https://user-images.githubusercontent.com/11036018/128590276-eaa0ae89-6aa4-4263-99d2-75e0aa0eab44.png)

**Comment by aspangaro** [comment]
Sorry but works for me in v12.0.4

**Comment by bos4711** [comment]
We upgraded to 14.0.3 this week and we still have this issue.
