### ISSUE TITLE
Eat By vs Sell By Date mixup in French

### ISSUE THREAD

**Issue by atm-florianm** [Dolibarr/dolibarr#18361]
# Bug
The French translations for `SellByDate` and `EatByDate` should be swapped. At first I thought the issue lay with the code (cf. [this closed PR](https://github.com/Dolibarr/dolibarr/pull/18311/files)) but I now think it is purely a translation problem.

Current translations:

| Key | en_US | fr_FR |
|----|-------|-------|
| SellByDate | Sell-by date | DLC |
| EatByDate | Eat-by date | DMD/DLUO |

Correct translations:

| Key | en_US | fr_FR |
|----|-------|-------|
| SellByDate | Sell-by date | DDM/DLUO |
| EatByDate | Eat-by date | DLC |

Note that, as far as I can tell, other languages (I checked de_DE and es_ES) use correct translations.

The legal meaning of DMD/DLUO matches the meaning of "Sell-by date" more closely than DLC does. Actually, I found [DDM](https://agriculture.gouv.fr/comment-conserver-les-aliments-dlc-ddm-quelle-difference), not "DMD".

While "Eat-by date" doesn't seem to have a precise legal meaning in US-American English, the idea it conveys matches that of "DLC" in French (the legal phrase used in US-American English is "[Use-by date](https://www.fda.gov/consumers/consumer-updates/confused-date-labels-packaged-foods)", but "Eat-by" is close enough).

For companies that use Dolibarr in a multilingual environment, this mistranslation could have serious consequences, but for companies that use only French, fixing this problem could also cause problems (after upgrading DLC would become DMD/DLUO and vice versa).

**Comment by BebZ** [comment]
I agree, my 2 cents

**Comment by eldy** [comment]
DLC means Date limit of Consommation in French. It is the date we can't bypass when we sell something and also the date it is dangerous to eat something. When this date has been reached, **we must remove the product from sell**. So it is the SellByDate in English. 

DLUO is date when **taste of product changes** but it can be eat after with no danger. It is the EatByDate.

So according to definition, the current translation seems good. It is confirmed by the link you gave https://agriculture.gouv.fr/comment-conserver-les-aliments-dlc-ddm-quelle-difference but also here
English version: https://www.anses.fr/en/content/use-date-ubd-and-date-minimum-durability-dmd
French version: https://www.anses.fr/fr/content/use-date-ubd-and-date-minimum-durability-dmd
and by the site http://www.eatbydate.com/

English:
Sell-by date = Shelf life expiration date = Use by (foods must be removed from store after this date)
Eat-by date = Best Before date = Best if Used By = Best by
WARNING:  "Use by" is different than "Best If Used By"

French:
DLC = Date limite Consommation = Date à consommer avant (les denrées doivent être supprimés des magasins une fois cette date passée) = Sell-by in English
DLUO = Date limite Utilisation Optimale = Date à consommer DE PREFERENCE avant = Date Durabilité Minimale (DDM) = Eat-by in English = Date of Minimum Durability (DMD) in English


Key | en_US | fr_FR
-- | -- | --
SellByDate | Sell-by date | DLC
EatByDate | Eat-by date | DMD/DLUO
