### ISSUE TITLE
Errors on Tasks stats page - wrong php for INNER JOIN

### ISSUE THREAD

**Issue by janis-j2b** [Dolibarr/dolibarr#18375]
# Bug
Missing `t.fk_so`c column in 'ON clause' error

## Environment
- **Version**: 14.0.1
- **OS**: Ubuntu server 20.04
- **Web server**: Apache2.4.x
- **PHP**: v7.4.3
- **Database**: MariaDB v10.4
- **URL(s)**: https://example.com/projet/tasks/stats/index.php?leftmenu=projects

## Expected and actual behavior
Visiting Projects > Tasks/activites > Statistics menu, there should be no errors but stistics page. Yet, stats were not displayed, claiming "...missing column t.fk_soc column in 'ON clause'".

## Steps to reproduce the behavior
Fresh install directly from GIT branch 14.0. (Cloned git repo, checkout to branch 14.0, do fresh install).

## Affected files
Found affected file: `./htdocs/projet/class/taskstats.class.php` where wrong INNER JOIN was coded. Probably due to schema change along the way.

Table `llx_projet_task` does not reference Third party via `fk_soc` field, rather via `entity` field. PHP file had wrong coding.

To correct issue, the following (multiple) lines in `taskstats.class.php` must be changed.

From:
`$sql .= " INNER JOIN ".MAIN_DB_PREFIX."societe_commerciaux as sc ON sc.fk_soc=t.fk_soc AND sc.fk_user=".$user->id;`

to:
`$sql .= " INNER JOIN ".MAIN_DB_PREFIX."societe_commerciaux as sc ON sc.fk_soc=t.entity AND sc.fk_user=".$user->id;`

Pardon for not pasting diff, just do not know how to.

**Comment by aspangaro** [comment]
Wrong fix, fk_soc is on llx_projet, t.fk_soc become p.fk_soc in class taskstats.class.php

**Comment by denisb79** [comment]
Hi everybody.
I found the same issue in the version 15.
I opened taskstats.class.php and I viewed that code wrote above has been commented //, but the issue didn't fix.
Is there some one can help me please?

CODE in version 15.0.3:
// No check is done on company permission because readability is managed by public status of project and assignement.
		//if (! $user->rights->societe->client->voir && ! $user->socid)
		//	$sql .= " INNER JOIN " . MAIN_DB_PREFIX . "societe_commerciaux as sc ON sc.fk_soc=t.fk_soc AND sc.fk_user = ".((int) $user->id);
		$sql .= ", ".MAIN_DB_PREFIX."c_lead_status as cls";
		$sql .= $this->buildWhere();
