### ISSUE TITLE
Email Campaign - No Receiver Listing anymore?

### ISSUE THREAD

**Issue by bugfishtm** [Dolibarr/dolibarr#18386]
# Feature Request
There was a list of receivers on Dolibarr 13.0.1-13.0.4 where you can see, which "items" have been added to the mail campaign.
Unfortunately it seems that this list has been removed in 14.0.0? Will it come back? 

## Use case
To see and remove single receipients.

## Suggested implementation
Please reimplement again

On Dolibarr 13:
![13](https://user-images.githubusercontent.com/27702527/128859483-58d5d16a-9aa4-458d-9320-ab25552f4f07.PNG)

On Dolibarr 14:
In "Advanced Selection" is no listing available, too.
![14](https://user-images.githubusercontent.com/27702527/128859484-edd5fff0-086e-40fd-9972-142743616c84.PNG)

**Comment by priojk** [comment]
In my installation (14.0.0), when I select recipients (within the tab "Recipients"=Empfänger), they do show up in a list at the bottom of the page as in your screenshot from version 13. So the issue seems to be about something specific with your installation/upgrade.

**Comment by bugfishtm** [comment]
Thanks for looking this up. I found out in 14.0.0 the list is only showing 
if the mail campaign is "released" (maybe i misspelled the word)
So in an mail campaigns draft, the list is not displaying.

Thats ok for me so far, so i will close this issue :)

**Comment by priojk** [comment]
I just had another look. The campaign, which I created for the test, hast not been validated/released so far ("E-Mail-Kampagne freigeben" has still to be activated) - and the list is showing as described. So there still seems to be an issue with your specific installation, the feature as such is there.

**Comment by bugfishtm** [comment]
Thanks again, i checked this again on my installation, and it was a conflict with an outdated module. :D

**Comment by bugfishtm** [comment]
Just for information, the module has been customersowed
