### ISSUE TITLE
LDCompta10 export issue - accountancyexport.class.php

### ISSUE THREAD

**Issue by GuillaumeMARQUES** [Dolibarr/dolibarr#18389]
# Bug
The LDCompta 10 export is bad.

Code Nature Pièce (CNPI) must be AC for customer asset (avoir) and FC for supplier_invoice. The old calculation was if montant <0 then AC, else FC. It was GOOD. Now, with a debit / credit substraction, it doesn't work.

## Environment
- **Version**: 13.0.0.4
- **OS**: Windows 2019
- **Web server**: DoliWamp
- **PHP**: N/A
- **Database**: N/A
- **URL(s)**: /accountancy/bookkeeping/list.php?action=export_file&&search_date_startmonth=1&search_date_startday=1&search_date_startyear=2021&search_date_endmonth=12&search_date_endday=31&search_date_endyear=2021

## Expected and actual behavior
The LDCompta10 technical description explain she need FC line for supplier invoice  and AC for customer asset (avoir) but with the "new" algorithm, we have FC for "positive" line and AC for negative with the calculation debit-credit <0 then AC, else FC

## Steps to reproduce the behavior
export bookeeping for LDCOMPTA10

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

Must reuse the montant < 0 use before in the accountancyexport.class.php

**Comment by BebZ** [comment]
LDcompta changed its import method and process in a working version ?
what is the lastest version of LDcompta working ? 
So they can create an export for LDcompta10"v2" and keep the old one.

**Comment by GuillaumeMARQUES** [comment]
LDCompta doesn't change anything, the dolibarr method between 13.0.0 and 13.0.4 have been changed.

**Comment by aspangaro** [comment]
Hello,

Field "montant" is deprecated since 13.0.x. A modification integrated in v13.0.2 has created a problem with sens of the operation on suppllier invoice. Look the PR.

**Comment by GuillaumeMARQUES** [comment]
The same CNPI (Nature Piece) must be used for all the lines linked to a piece.
We will have 1 line with more credit than debit and for a customer invoice, this line will be marked as AC with the code linked to the fix.

I think we must have an information linked to all lines records, with the total amount or the global information (Customer asset or Customer invoice).

Best Regards.

**Comment by aspangaro** [comment]
#18417 Better fix to have the same CNPI
