### ISSUE TITLE
Extra date field goes 1 day backwards after filling it

### ISSUE THREAD

**Issue by esaumell** [Dolibarr/dolibarr#18396]
# Bug
After filling the field with 09/01/1949 and save changes, it is set as 08/31/1949

## Environment
- **Version**: 13.0.3
- **OS**: Linux dolibarr 4.19.0-17-amd64 SMP Debian 4.19.194-2 (2021-06-21) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.29-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.29-MariaDB-0+deb10u1
- **URL(s)**: /dolibarr/societe/card.php?socid=3&action=edit

## Expected and actual behavior
After filling the field with 09/01/1949 and save changes, it should stay as 09/01/1949. Instead, it goes 1-day backwards.

## Steps to reproduce the behavior
Create a date field (Complementary attributes (third party)) on third party module like this:
Position: 100
Label or translation key: Date of birth 
Translation string: Date of birth 
Attribute code: dob 
Type: Date 
Size: 
Computed field: 
Unique: No 
Required: No 
Can always be edited: Yes 
Visible: 1
Display on PDF: 0
Totalizable: No

Go to an existing customer and fill the field with 09/01/1949 and save changes. It is set as 08/31/1949
Relevant dolibarr.log attached. 

[Date extra field bug.txt](https://github.com/Dolibarr/dolibarr/files/6969304/Date.extra.field.bug.txt)

**Comment by esaumell** [comment]
I've just took a look on to de DB. It seems the value is correctly stored there. But Dolibarr shows me 08/31/1949 :man_shrugging:

![image](https://user-images.githubusercontent.com/6902252/129076251-cc565ac6-b3eb-4cb8-965e-1a82ddbc1ecb.png)

**Comment by esaumell** [comment]
I did some testing editing the value directly on the DB and refreshing the browser:

If I set it to 1949-12-01 Dolibarr shows me 12/01/1949 <-- correct value
If I set it to 1949-10-03 Dolibarr shows me 10/03/1949 <-- correct value
If I set it to 1949-10-02 Dolibarr shows me 10/01/1949 <-- wrong value
If I set it to 1949-08-02 Dolibarr shows me 08/01/1949 <-- wrong value

**Comment by atm-maxime** [comment]
I can confirm, for some years, the dol_print_date function prints 1 day earlier. Here are the years concerned (checked only between 1000 and 2100) :
all before 1583 (more than a whole week back)
1916, 1917, 1918
1940 to 1949

This seems to come from the _adodb_getdate function (adodb-time.inc.php)

**Comment by esaumell** [comment]
> If I set it to 1949-10-02 Dolibarr shows me 10/01/1949 <-- wrong value
> If I set it to 1949-08-02 Dolibarr shows me 08/01/1949 <-- wrong value

I've just tried these two dates with v12.0.5 on Dolicloud, and it seems it's working properly.

I've compared adodb-time.inc.php v12.0.5 with the one on v13.0.3 and there is no difference, so not sure if this is coming from there.

**Comment by esaumell** [comment]
After having migrated to Dollicloud, I've no longer this problem. What I can see different from http://dolibarr.local/dolibarr/admin/system/phpinfo.php?mainmenu=home&leftmenu=admintools, is that on Dolicloud I'm using PHP 7.4.3 and timelib version 2018.03 while on my dev environment I use PHP 7.3.29-1~deb10u1 and timelib version 2018.04.
