### ISSUE TITLE
Bug: Result search to press key behind th confirmation Window

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#18414]
# Bug
Option to press a key to show the list of companies in the confirmation form, for example clone shows the result behind the confirmation window.

## Environment
- **Version**: 14.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /compta/facture/card.php?facid=1353&action=clone&object=invoice&page_y=500

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Ero duplicar](https://user-images.githubusercontent.com/53640168/129447879-d4466c1f-93a9-48f6-a40c-6e0e01c11c89.jpg)

**Comment by atm-maxime** [comment]
This has been fixed recently and will be soon available in 14.0.1
#18214
