### ISSUE TITLE
Salary Payment - extrafields are no more available (14.0.0)

### ISSUE THREAD

**Issue by henrynopo** [Dolibarr/dolibarr#18412]
# Bug
After updated to 14.0.0, I noticed that the salary payments are split into two different tables, i.e. payment_salary and salary (most data are duplicated with Payment_salary). However, the extrafields (Complementary attributes (salaries)) are no more available for edit / view.

There must be some coding logic issues. I doubt it is related to 
- $object = new Salary($db);
- $extrafields = new ExtraFields($db);

Therefore, I tweaked the database extrafields list, and replaced elementtype "payment_salary" by "salary". Then all the extrafields are now available for edit / view but cannot be really edited in the salary payment list.

**Comment by atm-maxime** [comment]
@atm-gauthier

**Comment by atm-gauthier** [comment]
@henrynopo, i'm working to debug this, i will link the PR when it's ready

**Comment by henrynopo** [comment]
> @henrynopo, i'm working to debug this, i will link the PR when it's ready

Thanks a lot for your reaction. Looking forward to your PR soon.

**Comment by atm-gauthier** [comment]
Hi @henrynopo, here's my PR : https://github.com/Dolibarr/dolibarr/pull/18623

**Comment by henrynopo** [comment]
@atm-gauthier I have tried it with success. Thank you very much.

**Comment by atm-gauthier** [comment]
@henrynopo thank you for this feedback, i hope @eldy will merge it asap

**Comment by atm-gauthier** [comment]
Hi @henrynopo can you close this issue please ? everything has been merged ;)
