### ISSUE TITLE
Security token has expired - again-  a never ending bug story?

### ISSUE THREAD

**Issue by choybe** [Dolibarr/dolibarr#18421]
It was now discussed on several issues and I hoped it will end with the v14 release
But it still continues: I just set up a brand new Dolibarr installation with v14. 
At first sight everything seemed to be in order, but as soon as I tried to set up company and activate internal modules I was redirected to log in again and when trying then to login came again the message I hate in between:
"Security token has expired, so action has been cancelled. Please try again." 

I have to say, that I run on the same server with same server-configuration another DB v14 version updated from v13. And here everything works. But even there I get from time to time this awful message, "Security token has expired, so action has been cancelled. Please try again." But here it works. I can try again and then continue as usual with DB.

How to stop this ? How can be avoided that this security token, can be avoided from the scratch with the install config?

**Comment by tboinay** [comment]
I also did a V14 upgrade hoping to fix the problem.
This time if it's worse I can't connect.

**Comment by choybe** [comment]
can anyone friom the dolibarr tema respind this bug?
I tried it out again with a fresh !4.01 install. Same story
first you get everthing installed, except you cannot create a superadmin during install. (error message saying access to the databese is denied - reason - when you go back yu see that by adding a superadmin type a password the password for the database was deleted,  
so I setup without creating a user. everything wiorks fine . At the end of the process I can create my user access.
once then in the new dolibarr install you want to configure company and modules -
but as soon as i add a country in company I get forwared to the login again
same when i try to activate any moduie -after 273 attempts yu get on the logon this AWFUL
"Security token has expired" (how I hate in between this message) and no way to access any more to without any further explanation in the error message that may indicate what have happenend

i have to add: I have a running dolibarr 14 installation on the same server, same server config. It is a dolibarr version regularaly updated from former versions. There as well I get from time this nasty "Security token has expired" message. But it can easily by passed just by refresh the page.
 
so please any one has an idea how to stop this awful everything blocking "Security token has expired"?

**Comment by hregis** [comment]
@choybe I have just performed an installation of V14 and I don't have this problem, can you contact me by email to look at remote maintenance? 

regis dot houssin at gmail dot com

**Comment by tboinay** [comment]
Many of us have encountered the problem of security tokens.
I downgraded to V13 in order to find a working Dolibarr.

**Comment by choybe** [comment]
I discovered a funny thing with this nasty security token expired message
when I name my dolibarr root file dolibarr (url redirect dolibarr/htdocs)
when i install dolibarr and rename the file eg dolibarr2 (url redirect dolibarr2/htdocs)
i can install dolibarr but under this renamed dolibarr version but all changes on the configuration via ui end up with abve decribed bug
Question is there y way to work on dolibarr via terminal (eg with drush) . It may help to find the error, for there is no way to fiund out via Ui why the security token expired message blocks everything. Also in the database neither in the server log is something to find about.

**Comment by choybe** [comment]
How to find out what make the security token expired. I cannot find anything in my error files. It would help.
I suspect it may has to do something with my php.ini and/or mysql.conf 
I use  php 7.4.24 with 5.5.5-10.3.29-MariaDB an an Linux Apache Server 
As not everyone has this security-token-expired problem,. the only explanation can be that certain server prerequisites may not be compatible with Dolibarr security token config.
