### ISSUE TITLE
Setup/PDF didn't save option

### ISSUE THREAD

**Issue by TheZnuf** [Dolibarr/dolibarr#18430]
# Bug
When I change an option in Setup/PDF, the save button say it's saved, but the buttons are reset. Except for logo height. The option *Randomly selected if several pictures are available* under Other is working

## Environment
- **Version**: [*14*]
- **OS**: [*Debian*]
- **Web server**: [*Apache/2.4.38*]
- **PHP**: [*7.3.27-1*]
- **Database**: [*MariaDB 5.5.5-10.3.27*]
- **URL(s)**: [*/admin/pdf.php?mainmenu=home*]

## Expected and actual behavior
*Save selected option*

## Steps to reproduce the behavior
*Select option activate and click on save*

**Comment by TheZnuf** [comment]
Works in v15-alpha

**Comment by ksar-ksar** [comment]
I think it has been corrected on V14.0.1, can you check ?

**Comment by TheZnuf** [comment]
Yes, working in 14.0.1 !

**Comment by cfoellmann** [comment]
CLOSE
