### ISSUE TITLE
Employee management improvements

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#18434]
# Feature Request
Change the way data of an employee are managed, add new data and permissions about these datas

## Use case
When we want to manage informations about our employees (personal informations), these informations are shared to everyone who can read a user card. We'd like to add new permissions to deal with personal datas and move all datas in the employee tab

## Suggested implementation
- [x] Add 2 new permissions in the user module : read employee and write employee
- [ ] Only display the employee tab if the user is flagged as an employee
- [ ] Move these datas in the employee tab : Supervisor, Force expense report validator, Force leave request validator, Job position, Average hourly rate, Average daily rate, Salary, Hours worked (per week), Employment date, Date of birth, Accounting account
- [x] Add new fields in employee tab : ref (i.e. employee number, used on the payslips), national registration number (i.e. social security number)

**Comment by cfoellmann** [comment]
I am completely with you on this.
Do you need help with anything or do you have the time to get this ready for 15.x?

**Comment by cfoellmann** [comment]
We already have the HR+bank tab.
This should be the employee data tab!?

**Comment by atm-adrien** [comment]
https://github.com/Dolibarr/dolibarr/pull/20249
