### ISSUE TITLE
Create deposit invoice with % of proposal/order defined on customer/payment term dict

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#18439]
**=Dictionnary Update=**

![image](https://user-images.githubusercontent.com/1050053/131676310-62cbf785-a12a-49b6-b0d7-d0e616883192.png)

 -Add a column into dictionnary Payment Terms : CheckBox : % manage Deposit invoice 
 -In this case the description can contain %s : "%s % at order, %s at delivery"

**=Fields To add=**
On customer, proposal, order,
  If a payment term with "checkbox % manage Deposit invoice" is selected, it display a field to input a number
  The "% deposit" can be change on Propal and Order but it will be filled with the customer default values

![image](https://user-images.githubusercontent.com/1050053/131676341-4b7a21e0-c0e2-4768-bbba-4d80e9262267.png)

**=Feature=**
On proposal or order validation, if % deposit invoice is set on document and deposit invoice do not exists yet :
    The confirmation pop-up will ask  on in form confirm
           => Create deposit invoice "yes/no"
              => If Yes : Validate Deposit invoice "Yes/no"
              => If Yes (create deposit invoice) the deposit mode use will be by default "Variable amount (% tot.) - 1 line with label 'Down payment'"
    And in the only line description there will be a summary of each lines of the proposal or order
        - Ref product (according global setting) - label product - Qty : X - Total Price XX € HT 
        Line description

The feature to summaryse the description of all lines into the only line of deposit invoice will be an hidden option (it means it will be done also for standard use of "Variable amount (% tot.) - 1 line with label 'Down payment'"

**=PDF Changes=**
On PDF cyan, eratosthene and proforma, the Payment Terms description will be replace with correct figures
 For exemple is % deposit is 30 % on the card " 30% at order, 70% at delivery"

**Comment by marc-dll** [comment]
@FHenry I think you can close this issue as PR has been merged ;)
