### ISSUE TITLE
 Security token has expired, so action has been canceled  

### ISSUE THREAD

**Issue by ibiza075** [Dolibarr/dolibarr#18437]
Hello 

Thank you for your help :)

after the update over the 14.0.0 version, I am unbale even to log into it.

The bug "Security token has expired, so action has been canceled ": was already all over prior the update, however, I was able to log and do some actions like create invoices, etc. 

[*  Security token has expired, so action has been canceled  *]

Server Environment

PHP Version | 7.4.22
-- | --
MySQL Version | 10.3.31-MariaDB
Architecture | x86_64
Operating System | linux
Shared IP Address | 107.6.183.178
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.16.3
Kernel Version | 3.10.0-962.3.2.lve1.5.44.2.el7.x86_64

**Comment by atm-maxime** [comment]
You certainly have an external module that is not compatible with version 14 and token management

**Comment by ibiza075** [comment]
Thank you, what you suggest to locate the not compatible module?

Kindly note that I do not have access to the admin in order to disable them, however, I deleted some via file manager.

**Comment by atm-maxime** [comment]
Remove all external modules (keep them in another directory) and try again. Then put back the modules one by one and see which one is blocking

**Comment by ibiza075** [comment]
I have deleted all the external modules and the error persist. I have not put back yet them modules back as the bug still popping up from the log page. I am unbale to log into the app.

Note: The external modules I had installed were only 2 from Google brought into dolistore at a premium.

Thanks

**Comment by atm-maxime** [comment]
Seek help on forum. This is related to your installation, note Dolibarr core code.

**Comment by ibiza075** [comment]
Thanks Maxime

Please can you share the link to the forum.

**Comment by atm-maxime** [comment]
https://www.dolibarr.org/forum.php

**Comment by ibiza075** [comment]
I am not getting any answer on the forum!
 Would you please give more details regarding the php version or what are the other points I can check to correct the issue?
 
 I am using 7.4.22 PHP version and I have updated the dolibarr to the last 14.0.1 version.
 
 Thanks

**Comment by futurehousestore** [comment]
Hi guys. Just an idea. Have a look at your hidden options setting. Maybe one of them causing the problem. I had a different problem which was caused by the hidden option not compatible with my server. I’m on 14.01 and don’t have the problem with security token.

**Comment by ibiza075** [comment]
Thanks guys, the issue I that I am getting the error from the logging, I am unable to log into the app.
besides "custom" into the public folder, is any other folder where to external modules could be installed?

**Comment by ibiza075** [comment]
Hi Maxime,

Thank you for your assistance.

Is it now a few days without any feedback on the forum?

Please confirm what you are referring to by  core code?

Any other recommendation to solve the issue as we are completely blockt due
to the issue?


Thank you


Kind regards
jose

**Comment by choybe** [comment]
I confirm this error persist. See as well:https://github.com/Dolibarr/dolibarr/issues/18421#issuecomment-902426346
