### ISSUE TITLE
Tickets module: easy overview messages

### ISSUE THREAD

**Issue by rubenkon** [Dolibarr/dolibarr#18456]
# Feature Request
Easy overview of all messages for a ticket

## Use case
Sometimes more people need to work on a singel ticket. Then it would be very helpfull to have an clear overview of all messages that have been submitted to this ticket. Also once the ticket is closed when reading back the ticket it is easy to read the problem, and all the messages and then the solution.

**Comment by atm-maxime** [comment]
My guess is that the event tab with the conversation view should be available on the main card tab. Wdyt ?
