### ISSUE TITLE
 downgrade from the 14.0.1 version to the 13.0.1 on linux server installation 

### ISSUE THREAD

**Issue by ibiza075** [Dolibarr/dolibarr#18469]
Hi Guy's,

Thanks for your help.

please can you orientate me on how to downgrade from the 14.0.1 version to the 13.0.1 as it's the quickest way I see to sort the "Security token has expired, so action has been canceled" bug ?

PHP Version | 7.4.22
-- | --
MySQL Version | 10.3.31-MariaDB
Architecture | x86_64
Operating System | linux
Shared IP Address | 107.6.183.178
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.16.3
Kernel Version | 3.10.0-962.3.2.lve1.5.44.2.el7.x86_64

Regards

**Comment by cfoellmann** [comment]
downgrading will be a big pain!

make the following changes in htdocs/main.inc.php:

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/main.inc.php#L445
```php
if (!defined('NOTOKENRENEWAL') && false) {
```

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/main.inc.php#L463
```php
if (((!defined('NOCSRFCHECK') && empty($dolibarr_nocsrfcheck) && !empty($conf->global->MAIN_SECURITY_CSRF_WITH_TOKEN)) || defined('CSRFCHECK_WITH_TOKEN')) && false) {
```

**Comment by cfoellmann** [comment]
After that you can sort out what is causing your issue. It is probably a custom module you have activated

**Comment by ibiza075** [comment]
Thanks cfoelmann

My linux installation htdocs folder is empty.

Should I copy create the file and upload it per the links you have sent?

**Comment by cfoellmann** [comment]
😟  empty?
there should be all the files that make up dolibarr. Something is really fishy there.
Are you sure you do not have deeper issues there?

**Comment by ksar-ksar** [comment]
How it has been installed ? with a .deb ?
If yes, the path should be \usr\share\dolibarr\htdocs\

**Comment by ibiza075** [comment]
It was installed via cpanel using softacoulus.

I checked the html htdocs\ folder that is empty :)

**Comment by ibiza075** [comment]
> 😟 empty?
> there should be all the files that make up dolibarr. Something is really fishy there.
> Are you sure you do not have deeper issues there?



> 😟 empty?
> there should be all the files that make up dolibarr. Something is really fishy there.
> Are you sure you do not have deeper issues there?

I have a linux softacoulus installation.
Please indicate where the folder is located ?

**Comment by cfoellmann** [comment]
Quick search indicates 

/var/softaculous

**Comment by ibiza075** [comment]
I have located the file and have some difficulties to complete the edit.

If I send you the file, would you help me to edit it?

Thanks :)

**Comment by ibiza075** [comment]
Thank you, it worked very nice :)

**Comment by cfoellmann** [comment]
this is just a band-aid. Please check your third party modules and maybe you can follow up with the developers there.

Please close this issue for now

**Comment by choybe** [comment]
Sorry to day, this is also no solution. 
This "security token expired" makes me somehow crazy. See: https://github.com/Dolibarr/dolibarr/issues/18421#issuecomment-902426346
I have fortunately still an old regulary upgraded dolibarr version up to 14.03 on my server working well. 
But any new install on the same server same, same configuration fails with security token expired. 
This bug is really very persistent! And nowhere any explanation to find why the security token has expired.
