### ISSUE TITLE
phpstorm config for codestyle

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#18470]
is anyone using phpstorm and can share the config for codestyle autoformat?

**Comment by erikvanberkum** [comment]
Yes, I am using phpStorm but have noting modified just use basic settings. Not sure what you are actually looking for:

![phpstorm_code-style](https://user-images.githubusercontent.com/7335299/130634029-ee7d6c93-520c-4801-a200-3bd9e3872b4b.png)

![phpstorm_code-style_editor-config](https://user-images.githubusercontent.com/7335299/130634067-66f3278d-8dad-421c-82b1-beac573b8f5f.png)

**Comment by cfoellmann** [comment]
when I autoformat the code it changes away from dolibarr standards. I am coming from WordPress and the codestyle is a little different.
I will take the time and try to change the settings to align with dolibarr standards. Will post what I come up with

**Comment by cfoellmann** [comment]
I found the issue!
You also need to set the proper tab config for HTML otherwise the codestyle for the php files is also wrong most of the time. I think it is because of the high ratio of HTML code on the files

**Comment by cfoellmann** [comment]
@erikvanberkum do you have a config solution to "active" in phpstorm these includes?
Example: `include DOL_DOCUMENT_ROOT.'/core/tpl/document_actions_post_headers.tpl.php';` 

phpstorm is not resolving the DOL_DOCUMENT_ROOT so I can not jump directly into the file by clicking

**Comment by erikvanberkum** [comment]
I am not of any help with this, I have the same issue.

Checking the manual: https://www.jetbrains.com/help/phpstorm/configuring-include-paths.html

![image](https://user-images.githubusercontent.com/7335299/140651975-e3871db4-a488-4a77-944a-979c3687034a.png)
