### ISSUE TITLE
PROJECT: Create new object button

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#18479]
If you activate the global `PROJECT_SHOW_CREATE_OBJECT_BUTTON` you get a huge amount of buttons on the project card:

![image](https://user-images.githubusercontent.com/1256090/130589635-eba5ec26-00f5-4904-aa9c-3a49e314cc3d.png)

Maybe nicer would be something looking like this:
![image](https://user-images.githubusercontent.com/1256090/130592038-df7e1293-29d7-4e52-b994-419230282951.png)

Example code: https://www.w3schools.com/howto/howto_js_dropdown.asp

But it should work like the quickadd or bookmark dropdowns

**Comment by Alepes-8** [comment]
As I am starting to work on it I am wondering where one can find the customization for a button class like butAction? The picture below shows an exemple where a butAction is in use to customize the aesthetics of the button.
![Screenshot 2021-10-05 144942](https://user-images.githubusercontent.com/47854778/136025761-b71290b0-bde8-4faa-af2c-0bf398f91451.png)
directory dolibarr/htdocs/projet/card.php

**Comment by priojk** [comment]
The respective pull request still has the Discussion label. Would like to keep this open until it gets merged or declined.
