### ISSUE TITLE
Bug Recruitment Modul ... referrer false

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#18488]
# Instructions

If an event is to be created for an applicant, you can create the appointment for the interview, for example ... so it will be saved. However, the referer is set incorrectly!
![grafik](https://user-images.githubusercontent.com/3923753/130634137-668af5c4-7b09-4b4e-bd62-2f6e5fd2fc1d.png)

# Bug
/htdocs/comm/action/card.php?action=create&origin=recruitmentcandidature@recruitment&originid=13&backtopage=1&percentage=-1
This form is redirected by add to the following useless url
/htdocs/comm/action/backbone.companyweb.at/htdocs/recruitment/recruitmentcandidature_agenda.php?id=13
and clear it get a Error404

## Environment
- **Version**: 14.0.1
- **OS**: Linux www3 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
- **Web server**: Apache
- **PHP**: 7.2
- **Database**: MySQL or MariaDB 5.5.5-10.3.27-MariaDB-0+deb10u1
- **URL(s)**: /htdocs/comm/action/card.php?action=create&origin=recruitmentcandidature@recruitment&originid=13&backtopage=1&percentage=-1

## Expected and actual behavior
refer to /htdocs/recruitment/recruitmentcandidature_agenda.php?id=13

**Comment by erikvanberkum** [comment]
A similar bug was found in this issue  #18296
