### ISSUE TITLE
new core modules filenames?

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#18490]
the core modules added recently do not use filenames like `card.php` or `list.php` BUT INSTEAD use filenames like `partnership_card.php` or `bom_list.php`.
Why the h***?

**Comment by eldy** [comment]
You can still use card and list, but when a module need 2 different object. How to make a difference ?
So you can have object_card and object_list
Module builder generates files like this. Only a prefix is added.

**Comment by cfoellmann** [comment]
Ok.
