### ISSUE TITLE
Testing results and ideas Module Knowledgemanagement 

### ISSUE THREAD

**Issue by Dolisupport** [Dolibarr/dolibarr#18545]
Input from tester for project future release Module Knowledgemanagement 
1.	Knowledgemanagement Module, Advanced search
A search option for the total article (with regular expression) is needed (not only title/question) to be really useful.
2.	Knowledgemanagement Module, Link to Tickets
It should be possible to link articles to tickets.
3.	Tickets Module, Link to knowledgemanagement articles
It should be possible to link tickets to articles.
4.	Knowledgemanagement Module, Public usage
Articles should be readable for external use if marked as public/externally (maybe special page for public articles as a FAQ/WIKI page).
5.	Knowledgemanagement Module, Width of Solution column
Solution column, please use total width of the card so more space can be used for example for tables.
6.	Knowledgemanagement Module, field ‘group of tickets’
‘Group of tickets’ is also ok to have on the left.
7.	Knowledgemanagement Module, Widget
A widget for the last five articles would be nice.

**Comment by cfoellmann** [comment]
Renaming it to `knowledgebase` would have been nice.
