### ISSUE TITLE
Not displaying correctly 0.5 day leaves in Agenda 

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#18557]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[Missing half of day of leaves in Agenda]

## Environment
- **Version**: [*14.0.1 and 15 alapha]
- **OS**: MacOS with MAMP]
- **Web server**: [Apache]
- **PHP**: [7.4]
- **Database**: [*Database type and version*]
- **URL(s)**: [http://dolibarr.serious.com:8888/holiday/card.php?id=2, dolibarr.serious.com:8888/comm/action/inphp?year=2021&month=9&search_actioncode=0&search_filtert=1&search_showbirthday=1&action=show_month&maxprint=3]

## Expected and actual behavior
[When selecting 4,5 of leave days, agenda page shows only 4 full days instead of 4 days and a half. See screenshot]

<img width="714" alt="Screenshot Dolibarr Agenda Leaves Issue at Aug 30 23-52-44" src="https://user-images.githubusercontent.com/57623859/131429660-192b62bb-2ec6-4db0-9b2a-550972826ee9.png">
<img width="630" alt="Screenshot Dolibarr Agenda Leaves Issue 1 at Aug 30 23-52-44" src="https://user-images.githubusercontent.com/57623859/131429667-a266245b-0b98-4062-ad8c-9f4158385643.png">

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by josett225** [comment]
Hi there
Do I need to add more information or communicate on the forum instead?

Best regards

Jose

**Comment by josett225** [comment]
Hi There

The issue is here on the code /dolibarr/htdocs/comm/action/index.php between line 1003-1013 in version 14.0.2
The comparison between $daycursor and $daykey and $event->date_end_in_calendar does not work in my configuration as $daykey value in the first iteration is higher than $daycursor instead of being equal and at the end of the loop the last value of $daykey is of course higher than $event->date_end_in_calendar. I believe dol_mktime function is creating the gap between $daycursor and $daykey in my case. (see screenshot). The result is that the last day event is not displayed in the agenda.
<img width="339" alt="Screenshot Agenda issue at Sep 14 05-35-31" src="https://user-images.githubusercontent.com/57623859/133192628-7357fa78-6c05-4e7e-afb9-28d59e68cfa4.png">

I tested several options to make it work and as I not a Dolibarr developer expert, here is a code suggestion that worked in my side with a new variable $dayendholiday :

Here is the actual code :
`		$daycursor = $event->date_start_in_calendar;
		$annee = dol_print_date($daycursor, '%Y', 'tzuserrel');
		$mois = dol_print_date($daycursor, '%m', 'tzuserrel');
		$jour = dol_print_date($daycursor, '%d', 'tzuserrel');

		$daykey = dol_mktime(0, 0, 0, $mois, $jour, $annee, 'gmt');
		do {
			$eventarray[$daykey][] = $event;

			$daykey += 60 * 60 * 24;
		} while ($daykey <= $event->date_end_in_calendar);`

Here is the new code

`              $daycursor = $event->date_start_in_calendar;
		$annee = dol_print_date($daycursor, '%Y', 'tzuserrel');
		$mois = dol_print_date($daycursor, '%m', 'tzuserrel');
		$jour = dol_print_date($daycursor, '%d', 'tzuserrel');

		$daykey = dol_mktime(0, 0, 0, $mois, $jour, $annee, 'gmt');

                $daycursor = $event->date_end_in_calendar;
	        $annee_holidays_fin = dol_print_date($daycursor, '%Y', 'tzuserrel');
		$mois_holidays_fin = dol_print_date($daycursor, '%m', 'tzuserrel');
		$jour_holidays_fin = dol_print_date($daycursor, '%d', 'tzuserrel');

		$dayendholiday = dol_mktime(0, 0, 0, $mois_holidays_fin, $jour_holidays_fin, $annee_holidays_fin, 'gmt');

		do {
			$eventarray[$daykey][] = $event;

			$daykey += 60 * 60 * 24;
		} while ($daykey <= $dayendholiday);`

**Comment by Belface** [comment]
Hi there,
I confirm the same issue, but not only with half day, but with full day too.

To reproduce :
- Create a holiday from monday AM to Wednesday PM (for example)
- When you look in the calendar, holiday appears only in monday and tuesday box (wednesday box is empty)

Didn't had time to test **josett225** workaround.
Will give you a feed back

**Comment by Belface** [comment]
I confirm that josett225 workaround is working
Thanks !

**Comment by josett225** [comment]
Hi There
Seems to be fixed :
https://github.com/Dolibarr/dolibarr/pull/20584

Closing this ticket
