### ISSUE TITLE
Difference between ClientTZ v/s TimeZone PHP America/Santiago

### ISSUE THREAD

**Issue by cristcampos** [Dolibarr/dolibarr#18569]
# Bug
Server time zone does not match client time zone with America/Santiago

## Environment
- **Version**: 14.0.0
- **OS**: Debian 10
- **Web server**: Apache
- **PHP**:  7.3.19
- **Database**: MariaDB 5.7.30
- Server in Google Cloud Platform

## Expected and actual behavior
There is a difference between America/Santiago between the server that is -4 and the ClientTZ -3.

![1](https://user-images.githubusercontent.com/89870449/131560945-3230c3aa-76d4-4193-82e5-0671574e0802.jpg)

![image](https://user-images.githubusercontent.com/89870449/131563252-74108124-32ab-4f6a-8e8a-f1115828e535.png)

In Server Debian
![image](https://user-images.githubusercontent.com/89870449/131561853-7197315c-3cbf-4bf9-acaf-4275d5744f89.png)

This causes inconsistency in the generation of user movements within the application

 In my PC with Google Chrome (SO Windows 10):

![image](https://user-images.githubusercontent.com/89870449/131564020-e1997814-a7d3-416f-a353-3b2f17c460a0.png)

I suspect it may be the daylight saving time issue, but I don't know how to set it.

this also happens with demo.dolibarr.org:

![image](https://user-images.githubusercontent.com/89870449/131563588-d089f31d-def0-43d3-90ca-d3f17d588c99.png)

Please, I need your help!
Thanks!!

**Comment by progiseize** [comment]
Same here
PHP and SQL Serveur are on the right timezone
Windows on the right timezone,
I didn't figure out where was Dolibarr finding "client timezone"

**Comment by progiseize** [comment]
@cristcampos I found the problem but it was specific to my instance, because of a custom module.

You might want to check the PHP session variable to find if everything is OK : 
$_SESSION['dol_tz']
$_SESSION['dol_dst']

**Comment by cristcampos** [comment]
Hi!
thanks for all

this is varibales:

dol_tz => -3, dol_tz_string => America/Santiago, dol_dst => 0, dol_dst_observed => 1, dol_dst_first => , dol_dst_second => 

it's OK now.
It is solved only when it is daylight .

![image](https://user-images.githubusercontent.com/89870449/139448593-eccbb785-c24c-4054-9b2b-5b8480354bed.png)
