### ISSUE TITLE
Feature request : create shipping without customer order

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#18578]
It would be useful to be able to create shipping without customer order.
I know it implies lot of changes in the database shipping tables that are currently linked to orders.

**Comment by ToniTen** [comment]
Yeah, this would work great for more than a few use cases. If in addition it would let you add lines to the shipment that are not linked to order lines, it would solve even more issues:
- You would be able to add free items to orders (like including a line for say a warranty card, an instruction manual, replacement labels, etc)
- You would be able to send extra/replacement small accessories for items (like extra fixing crews/plugs/etc)
