### ISSUE TITLE
Multicompany transverse mode : users module permissions

### ISSUE THREAD

**Issue by atm-lena** [Dolibarr/dolibarr#18573]
# Bug

When we create a user, this user has the entity "1".
An admin user can only see users linked to a group and an entity.
An admin user can create a user without being able to link an group to new user. 
A error display : Access Denied. 

## Environment
- **Version**: 12.0/13.0/14.0
- **OS**: Debian linux
- **Web server**: apache2
- **PHP**: 7.4
## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
- Create a user admin (no superadmin) with all users module permissions
- Activate transversemode multi-entity's module
- Connect to user admin
- Create a user
=> a error message displays

**Comment by hregis** [comment]
@atm-lena Hello, if you use the "centralized management of users and groups on the main entity " option, users and groups can only created in master entity (for the moment)
