### ISSUE TITLE
SEPA XML File Error - SEPA Transfer

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#18586]
Hello,

Unfortunately, the SEPA payment by bank transfer is incorrect.
If the field supplier ("Ustrd") character exceeds a certain number, the XML file can no longer be submitted to the bank and an error occurs. The problem is that a special character was inserted in the area "<EndToEndId> </EndToEndId>", which leads to the error. 
Here the truncation is not done properly.

Here the reduction to the maximum number of digits is incorrect.

If too long:
Ustrd>XX-XXXXXXX-XX-XXXXXXX</Ustrd

Shortening incorrect:
EndToEndId>XX-XXX-XX-XXXXXXX-XX-XX…-XXXXXXXXXX</EndToEndId

It can be checked in the file. (SEPA_XML_FILE_ERROR.txt)

If the field supplier character ("Ustrd") does not exceed the maximum number of "EndToEndId" and no shortening is made, the XML file can be submitted without problems.

Please let me know how I can solve the problem as many transfer texts (Ustrd) are significantly longer and have been shortened.

THX

Eg.
[SEPA_XML_FILE_ERROR.txt](https://github.com/Dolibarr/dolibarr/files/7100587/SEPA_XML_FILE_ERROR.txt)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/7759288/131887272-932365ba-1afc-46c1-b132-a95812744d62.png)

The special character that caused the problem is marked in the picture.

**Comment by atm-maxime** [comment]
You're right, the "..." has been replaced by a single character (which is not accepted by banks) in this february 2021 commit d3a98c7680178da9811a579773c47aeb580254f8
@eldy, what is best ? Go back to have classic "..." in the dol_trunc() function, or specify $nodot=true in every dol_trunc calls within the XML creation ?

**Comment by ghost** [comment]
Can someone tell me what I need to change to restore the function of the module.
 Unfortunately, it is currently not possible to use it.

**Comment by atm-maxime** [comment]
@eldy ?
In the meantime, you can undo what has been done in the commit I mentioned.

**Comment by ghost** [comment]
Points are also not allowed at German banks. 
The shortening must be done without additional characters without inserting anything.

**Comment by ghost** [comment]
I have now replaced it with an "x", now the transfer work.
Can someone change that. So that I don't have to do that with every update.



/**
 *	Truncate a string to a particular length adding 'x' if string larger than length.
 * 	If length = max length+1, we do no truncate to avoid having just 1 char replaced with 'x'.
 *  MAIN_DISABLE_TRUNC=1 can disable all truncings
 *
 *	@param	string	$string				String to truncate
 *	@param  int		$size				Max string size visible (excluding x). 0 for no limit. WARNING: Final string size can have 3 more chars (if we added x, or if size was max+1 so it does not worse to replace with ...)
 *	@param	string	$trunc				Where to trunc: 'right', 'left', 'middle' (size must be a 2 power), 'wrap'
 * 	@param	string	$stringencoding		Tell what is source string encoding
 *  @param	int		$nodot				Truncation do not add x after truncation. So it's an exact truncation.
 *  @param  int     $display            Trunc is used to display data and can be changed for small screen. TODO Remove this param (must be dealt with CSS)
 *	@return string						Truncated string. WARNING: length is never higher than $size if $nodot is set, but can be 3 chars higher otherwise.
 */
function dol_trunc($string, $size = 40, $trunc = 'right', $stringencoding = 'UTF-8', $nodot = 0, $display = 0)
{
	global $conf;

	if (empty($size) || !empty($conf->global->MAIN_DISABLE_TRUNC)) {
		return $string;
	}

	if (empty($stringencoding)) {
		$stringencoding = 'UTF-8';
	}
	// reduce for small screen
	if ($conf->dol_optimize_smallscreen == 1 && $display == 1) {
		$size = round($size / 3);
	}

	// We go always here
	if ($trunc == 'right') {
		$newstring = dol_textishtml($string) ? dol_string_nohtmltag($string, 1) : $string;
		if (dol_strlen($newstring, $stringencoding) > ($size + ($nodot ? 0 : 1))) {
			// If nodot is 0 and size is 1 chars more, we don't trunc and don't add x
			return dol_substr($newstring, 0, $size, $stringencoding).($nodot ? '' : 'x');
		} else {
			//return 'u'.$size.'-'.$newstring.'-'.dol_strlen($newstring,$stringencoding).'-'.$string;
			return $string;
		}
	} elseif ($trunc == 'middle') {
		$newstring = dol_textishtml($string) ? dol_string_nohtmltag($string, 1) : $string;
		if (dol_strlen($newstring, $stringencoding) > 2 && dol_strlen($newstring, $stringencoding) > ($size + 1)) {
			$size1 = round($size / 2);
			$size2 = round($size / 2);
			return dol_substr($newstring, 0, $size1, $stringencoding).'x'.dol_substr($newstring, dol_strlen($newstring, $stringencoding) - $size2, $size2, $stringencoding);
		} else {
			return $string;
		}
	} elseif ($trunc == 'left') {
		$newstring = dol_textishtml($string) ? dol_string_nohtmltag($string, 1) : $string;
		if (dol_strlen($newstring, $stringencoding) > ($size + ($nodot ? 0 : 1))) {
			// If nodot is 0 and size is 1 chars more, we don't trunc and don't add x
			return 'x'.dol_substr($newstring, dol_strlen($newstring, $stringencoding) - $size, $size, $stringencoding);
		} else {
			return $string;
		}
	} elseif ($trunc == 'wrap') {
		$newstring = dol_textishtml($string) ? dol_string_nohtmltag($string, 1) : $string;
		if (dol_strlen($newstring, $stringencoding) > ($size + 1)) {
			return dol_substr($newstring, 0, $size, $stringencoding)."\n".dol_trunc(dol_substr($newstring, $size, dol_strlen($newstring, $stringencoding) - $size, $stringencoding), $size, $trunc);
		} else {
			return $string;
		}
	} else {
		return 'BadParam3CallingDolTrunc';
	}
}

**Comment by ghost** [comment]
[SEPA_Truncate_a_string_OK.txt](https://github.com/Dolibarr/dolibarr/files/7178929/SEPA_Truncate_a_string_OK.txt)

**Comment by ghost** [comment]
Hello,

A separate function for the SEPA module is urgently needed here. Since the adjustment unfortunately also affects other functions and SEPA does not work with points etc.

Can someone fix it?

**Comment by ghost** [comment]
Hi there,

can someone build in a function that is only for the abbreviation of SEPA. 
If I adapt the existing function, this also affects other modules.
Here a function would only be perfect for the SEPA reduction, 
which can then also be adjusted if necessary.

 Thanks very much!

@eldy 
@ksar-ksar 
@frederic34
