### ISSUE TITLE
Feature Request: Invoice notification after PDF generation

### ISSUE THREAD

**Issue by bontiv** [Dolibarr/dolibarr#18588]
# Feature Request
Send notification *after* the PDF generation on Invoice.

## Use case
When using template invoice to auto generate invoice, the notification is send to billing contact before the PDF is generated.

They are two issues:

1. The mail template use the "(PROVxx)" as invoice reference for recurring invoice. 
2. They are no attached PDF in the notification mail or the attached file is the draft invoice.

The notification send to billing contact may be send after the invoice reference generation and PDF generation.

This feature is very useful for invoice template generation to immediately send generated invoice by mail.

## Work to be implemented
Email is send by trigger system. The same trigger which verify invoice can be created. The next step after triggers is generating the invoice reference and sending the mail.

Two proposals :
1. Use the same trigger system for invoice ref generation and PDF generation.
2. Use another trigger after the ref is assigned on invoice and PDF generated.

The first proposition will let invoicing system to be more modulable. Developers will be able to create trigger between ref and PDF generation to change invoice reference or a trigger after PDF generation to send it on external storage.

The second proposition use less structure modification. It's more easy to implement.

**Comment by bontiv** [comment]
I finally use a new setup option to postpone triggers and enable PDF generation after the invoice validation.
It work for manually validated invoice and recurring invoice. The final PDF is send with notification instead of draft PDF.

**Comment by BebZ** [comment]
👍  well done, I hope your next commit will be merged as soon as possible !
