### ISSUE TITLE
Error 500 when adding item in exense report

### ISSUE THREAD

**Issue by chaitanya-mandala** [Dolibarr/dolibarr#18599]
I am getting an error 500 this page isn't working and the page doesn't redirect back to the expenses report page needs to go back manually when adding items to the expenses report or click on validate or approve expense report. if click on refresh its again posting data and gets duplicated data in the database.

**Comment by atm-maxime** [comment]
Hi ! Can you provide your Dolibarr version, if you have extra module installed and the error message in the apache log related to the 500 error ? (php fatal)

**Comment by chaitanya-mandala** [comment]
hi, i am using dolibarr 14.0.2 hosted in infinity free free hosting service. I have installed only available modules in setup no third-party modules were installed. The hosting site doesn't provide any apache log due to its free hostig. if log definitely need I can install on local server and test it.

**Comment by atm-maxime** [comment]
Please do, I can't reproduce on a 14.0.2, adding lines, validating and approving are working just fine...

**Comment by chaitanya-mandala** [comment]
hi, I installed and running xampp local server its running fine without 500 error, but for adding a line, validating, re-editing takes 15-20sec to submit and redirect to the same page. any idea on this? i added error log and access log files.
[error.log](https://github.com/Dolibarr/dolibarr/files/7109530/error.log)
[access.log](https://github.com/Dolibarr/dolibarr/files/7109531/access.log)

**Comment by atm-maxime** [comment]
Can you check how long it takes to generate the expensereport PDF ? Maybe your logo is too big and the PDF generation is taking too long. And everytime you add a line or validate the expensereport, the PDF is auto generated.
