### ISSUE TITLE
Bug ajout imprimante postgresql

### ISSUE THREAD

**Issue by noedelcroix** [Dolibarr/dolibarr#18591]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Bug lors de l'ajout d'imprimante sur une base de données postgresql

## Environment
- **Version**: 13.0.4 et 14.0
- **OS**: debian (docker)
- **Web server**: apache2
- **PHP**: php 7.4
- **Database**: postgresql (docker)
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Bonjour,
J'ai remarqué lors de mes tests que lorsque nous utilisons une base de données postgresql avec Dolibarr, un bug survient lors de l'ajout d'une imprimante locale via le module imprimante ticket. J'ai remarqué ce bug sur la version 13.0.4 et 14.0.
Pour mon cas, ce n'est pas grave car je vais finalement utiliser une base de données mysql mais c'est un bug assez embêtant pour ceux qui doivent passer par du postgresql.

## Steps to reproduce the behavior
1. Installer un serveur postgresql. Dans mon cas, j'ai créé un container docker mais cela n'a pas d'importance.
2. Installer dolibarr.
3. Activer le module imprimante ticket.
4. configurer le module en ajoutant une imprimante locale ou windows locale (je n'ai pas testé les autres).

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

You need to write in English.

What is the exact error message ?

**Comment by noedelcroix** [comment]
Hello,
It's an error when you add a ticket printer in Dolibarr with a postgresql database. This is the error :
```
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20210907125518
Dolibarr: 13.0.4 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.4.23
Serveur: Apache/2.4.38 (Debian)
OS: Linux 3b7990ce5d72 5.11.0-7633-generic #35~1630100930~21.04~ae2753e-Ubuntu SMP Mon Aug 30 18:26:54 UTC x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36

Url sollicitée: /admin/receiptprinter.php?mode=config
Referer: http://127.0.0.1/admin/receiptprinter.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php%3Fsearch_keyword%3Dticket%26search_nature%3D%26search_version%3D%26search_status%3D
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, receiptprinter
Type gestionnaire de base de données: pgsql
Requête dernier accès en base en erreur: INSERT INTO llx_printer_receipt (name, fk_type, fk_profile, parameter, entity) VALUES ("Tickets", 2, 0, "/dev/usb/lp0", 1)
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: ERROR: 42703: column "Tickets" does not exist\nLINE 1: ..., fk_type, fk_profile, parameter, entity) VALUES ("Tickets",...\n ^\nLOCATION: errorMissingColumn, parse_relation.c:3514


Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/dolibarr/htdocs/core/lib/functions.lib.php:4212) in /var/www/html/dolibarr/htdocs/main.inc.php on line 1220

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/dolibarr/htdocs/core/lib/functions.lib.php:4212) in /var/www/html/dolibarr/htdocs/main.inc.php on line 1224

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/dolibarr/htdocs/core/lib/functions.lib.php:4212) in /var/www/html/dolibarr/htdocs/main.inc.php on line 1225
```

**Comment by noedelcroix** [comment]
The problem is that Dolibarr take the printer name as a database column name.

**Comment by ksar-ksar** [comment]
The problem is the double quote of the request : 
INSERT INTO llx_printer_receipt (name, fk_type, fk_profile, parameter, entity) VALUES ("Tickets", 2, 0, "/dev/usb/lp0", 1)

Mysql alows but not postgresql
