### ISSUE TITLE
Region not translated in user card

### ISSUE THREAD

**Issue by mschamp** [Dolibarr/dolibarr#18612]
In the user card, the address is shown on top, but the region is not translated.
By default the French name of the regions is available, so I added a dutch version:
![image](https://user-images.githubusercontent.com/34092708/132130218-398929af-4f98-4abc-b1ec-b023f4b6332c.png)

The translation works in the selection box when you edit a user, but when you view a user, the original name is shown

![KnipselBug](https://user-images.githubusercontent.com/34092708/132130134-f9ae865c-8274-4f88-8d13-e5aa0cdc2dc6.PNG)
![image](https://user-images.githubusercontent.com/34092708/132130154-f4ae5caa-7a5c-4bac-922d-e0fd48a401db.png)

**Comment by mschamp** [comment]
## Environment
- **Version**: 14.0.1
- **URL(s)**: [server]/dolibarr/user/card.php?id=[number]

## Expected and actual behavior
Expected behavior is the translation to show

## Steps to reproduce the behavior
- Add translation for a region
- Set the region of a user to a region with translation (in the edit checkbox, the translation will be used)
- Open a user card, the non translated region will be shown at the top of the card

**Comment by atm-florianm** [comment]
I think the "State/Province" feature was not designed to be translated in the first place. While this is not usually a problem for countries with only one official language, it can become one when a country has more than one.

I don't believe there is an easy solution to your issue at the present (but I think this is a good issue, as it could be a useful feature).
