### ISSUE TITLE
INVOICE_MAX_FUTURE_DELAY is not respected

### ISSUE THREAD

**Issue by lainwir3d** [Dolibarr/dolibarr#18621]
# Bug
INVOICE_MAX_FUTURE_DELAY is not respected

## Environment
- **Version**: 14.0.x
- **PHP**: 7.3.20
- **Database**: MariaDB-10.3.28

## Expected and actual behavior
INVOICE_MAX_FUTURE_DELAY, introduced in 14.0.0, allows invoice to be invoiced in the future. The [wiki](https://wiki.dolibarr.org/index.php?title=Setup_Other) states that it is the "Numbers of days allowed for billing in the future", but it's not working and the code is not coherent with that information.

## Steps to reproduce the behavior
Set INVOICE_MAX_FUTURE_DELAY to 2, and try to create an invoice with a date two days in the future => not working.

**Comment by ksar-ksar** [comment]
Hello,

In fact the INVOICE_MAX_FUTURE_DELAY must be in seconds not in days

**Comment by lainwir3d** [comment]
All right! Is it possible to edit the [wiki](https://wiki.dolibarr.org/index.php?title=Setup_Other) to reflect that information please?

I don't think I have the access right to do that. 

Cheers.

**Comment by ksar-ksar** [comment]
Done

> 
> 
> All right! Is it possible to edit the [wiki](https://wiki.dolibarr.org/index.php?title=Setup_Other) to reflect that information please?
> 
> I don't think I have the access right to do that.
> 
> Cheers.

Done

**Comment by lainwir3d** [comment]
Thanks! Closing this.
