### ISSUE TITLE
Bug: Impossible de modifier l’état dans proposition commercial (ACCEPTÉ/REFUSÉ)

### ISSUE THREAD

**Issue by hechmiS** [Dolibarr/dolibarr#18638]
Bonjour,
 je n’arrive pas à modifier le statut d'une proposition commercial car la bouton « Définir accepté/refusé » est désactivé ,
et le message "vous n'avez pas les permissions pour cette action" s'affiche sur la bouton
![image](https://user-images.githubusercontent.com/90255036/132340051-368df154-f760-42af-abcd-cb95f116425e.png)

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.4.21
- **Database**:  5.7.35
- **URL(s)**: /dolibarr/user/home.php?leftmenu=users

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

In English please.

For first help like that, forum is the right tool : https://www.dolibarr.fr/forum/

**Comment by hechmiS** [comment]
Hello,
I can't change the status of a business proposal because
the "Set accepted / refused" button is disabled, and the message "you do not have permissions for this action" is displayed on the button
