### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by tumeteus** [Dolibarr/dolibarr#18651]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Impossible to add products to shipment if stock is negative. It seems the setting in stock-module options does not affect this.

## Environment
- **Version**: 14.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: apache2handler 7.2.24-0ubuntu0.18.04.8
- **Database**:  5.7.35-0ubuntu0.18.04.1

## Expected and actual behavior
If setting in Stock module (Stock level must be enough to add product/service to shipment (check is done on current real stock when adding a line into shipment whatever the rule for automatic stock change) is set to disabled, products can still not be added to shipment. In the shipment form, "No product to ship found in warehouse <warehouse>. Correct stock or go back to choose another warehouse." message is shown and no qty can be set.

## Steps to reproduce the behavior
Create sales order, add product to order which stock is less than you intend to ship, validate order, create shipment.

**Comment by Hystepik** [comment]
Hello,
It works for me in last version of 14.0.2

**Comment by cfoellmann** [comment]
@tumeteus please rename the issue to show some info in the headline
