### ISSUE TITLE
Wrong placement of trigger call "BILL_VALIDATE"

### ISSUE THREAD

**Issue by libremaster** [Dolibarr/dolibarr#18669]
# Instructions

It is about the new system to send e-mail with PDF attached when invoice is validated.
But the trigger is called before the invoice is really validated and committed so the e-mail contains temporary invoice number (PROVXX) and no PDF.

## Environment
- **Version**: 14.0.1

## Expected and actual behavior

The trigger should be called after the invoice is really committed with status "validate" : 

**htdocs/compta/facture/class/facture.class.php :**

I think it should be something like this (and the end of the function "validate" ) : 

```
if (!$error) {
			$this->db->commit();

			// Trigger calls
			if (!$notrigger) {
				// Call trigger
				$result = $this->call_trigger('BILL_VALIDATE', $user);
				if ($result < 0) {
					// do something
				}
				// End call triggers
			}

			return 1;
		} else {
			$this->db->rollback();
			return -1;
		}
	}
```

**Comment by simnandez** [comment]
The placement is correct: If any module collects the trigger and due to the module's rules, the invoice cannot be validated, it should not be validated

**Comment by priojk** [comment]
I just came across the same issue:

Recurring invoices need to be sent via mail to the customer, once they get validated. I.e.the mail needs to contain the final invoice number and the pdf attached.

Probably we need two triggers: The existing BILL_VALIDATE to allow modules to stop the validation, if certain conditions are not met (i.e. the current position as above) and BILL_VALIDATION_COMPLETED to allow the handling of validated invoices, e.g. for notification purposes.

What do you think?
