### ISSUE TITLE
VAT is not listed

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#18662]
# Bug
VAT is simply not shown in invoice list

## Environment
Probably independant, V 14.0.1

## Expected and actual behavior
Expect, show the amount calculated, actual, shows '0' everywhere

## Steps to reproduce the behavior
In invoice list, select a date from & to, select VAT exl., VAT inc., and VAT

## [Attached files]
![image](https://user-images.githubusercontent.com/2384485/132695536-477c8eb1-b81c-4106-be08-01c5763f5c6f.png)

**Comment by Hystepik** [comment]
Hello,
It works for me in last version of 14.0.2

**Comment by matDOTviguier** [comment]
@Hystepik it's not stable yet ...

**Comment by aspangaro** [comment]
Hello, It's stable now
