### ISSUE TITLE
Propal always insert a (PROV) ref

### ISSUE THREAD

**Issue by danndaghost** [Dolibarr/dolibarr#18671]
# Bug
When insert a new propal and have a set ref by code, this always insert (PROV)

## Environment
- **Version**: 13.0.4
- **OS**: Debian Buster
- **Web server**: Apache 2.4
- **PHP**: 7.2
- **Database**: Mysql 15.1
- **URL(s)**: htdocs/comm/propal/card.php

## Expected and actual behavior
Change line 1139 on propal.class.php to $this->ref = (!empty($this->ref)) ? $this->ref : '(PROV'.$this->id.')';

## Steps to reproduce the behavior
Change the form of create a propal to you set by form a REF code, this custom REF can't insert, always insert (PROV)

**Comment by simnandez** [comment]
It is the correct and expected operation, when the propal is created, the status is set as draft, and when the user validates the propal, that is when the REF is assigned

**Comment by eldy** [comment]
If you need to set a custom ref by code, i recommand you to update the propal just after its validation (by a trigger or by your own code if you call yourself the "validate")

**Comment by danndaghost** [comment]
Hello, i don't think so... see the line 1045:

```
// Check parameters
if (!empty($this->ref)) {	// We check that ref is not already used
	$result = self::isExistingObject($this->element, 0, $this->ref); // Check ref is not yet used
	if ($result > 0) {
		$this->error = 'ErrorRefAlreadyExists';
		dol_syslog(get_class($this)."::create ".$this->error, LOG_WARNING);
		$this->db->rollback();
		return -1;
	}
}
```
In those lines validate the REF when you use a custom value, so it's a inconsistent validation to REF parameter if you can't persist the custom value because always insert a (PROV) value.
