### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by mmpattnaik** [Dolibarr/dolibarr#18670]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.1
- **OS**: SunOS
- **Web server**: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/5.6.15
- **PHP**: apache2handler 5.6.15
- **Database**:  5.6.42
- **URL(s)**: /dolibarr-develop/htdocs/admin/tools/update.php?action=getlastversion&token=6172048c18042d1cc7e310e4a373df3c

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

What is the BUG ?
