### ISSUE TITLE
Dolibarr 14.0.1 - WYSIWYG on elements (orders - quotations - invoices) - Error with caracters 

### ISSUE THREAD

**Issue by FlorianMA13** [Dolibarr/dolibarr#18687]
[*WYSIWYG replace automaticly specials caracters in hexadecimal*]

## Environment
- **Version**: 14.0.1
- **OS**: [*Server OS type and version*]
- **Web server**: Litespeed
- **PHP**: 7.4

Hello guys, 

Since 1 week (update to 14.0.1), i have a big problem with WYSIWYG. All product i haved created with this editor, when i'm try to use it for a quotation / orders or invoices does not appear correctly.

I think it's a general problem from last version of Dolibarr.

Do you have a same problem? Did you have an solution to correct that?

Have a nice day, thank you
<img width="790" alt="Capture d’écran 2021-09-12 à 10 02 30" src="https://user-images.githubusercontent.com/90548415/132978905-04aa61ef-8c2e-4869-9db0-ee1ed5b6183a.png">
<img width="785" alt="Capture d’écran 2021-09-12 à 10 02 35" src="https://user-images.githubusercontent.com/90548415/132978906-2ea8c42a-aff3-48d3-a874-5a1a7a847693.png">
<img width="732" alt="Capture d’écran 2021-09-12 à 10 03 15" src="https://user-images.githubusercontent.com/90548415/132978907-0a98611f-2929-4dce-9ffb-5e5e7891d44f.png">

**Comment by ibuiv** [comment]
see [Issue 18250](https://github.com/Dolibarr/dolibarr/issues/18250)

**Comment by tonyvsz** [comment]
hi, resolved in 14.0.2.
