### ISSUE TITLE
Impossible to select a thirdparty from the popup on cloning documents or merging thirdparties.

### ISSUE THREAD

**Issue by Delthair** [Dolibarr/dolibarr#18684]
## Bug
When trying to clone a proposal, an order, or merge thirdparties, it is impossible to select the thirdparty from the popup list if the option  **_"Wait until a key is pressed before loading content of Third Parties combo list. This may increase performance if you have a large number of third parties, but it is less convenient."_** is set to **_"When you enter 3 characters, you can see the list but it is "behind" the pop up preventing the selection."_** 

## Environment
- **Version**: [*13.0.4*]

## Expected and actual behavior
When you enter 3 characters, you can see the list based on the 3 characters typed and then you can select the thirdparty you want.

## Steps to reproduce the behavior
In the thirdparty / Company module setup, activate the  option _Wait until a key is pressed before loading content of Third Parties combo list. This may increase performance if you have a large number of third parties, but it is less convenient_. and set it to _YES (number of characters to trigger search: 3)_ Then go to a commercial proposal for exemaple and try to clone it. When you enter 3 characters, you can see the list but it is **_"behind"_** the pop up preventing the selection.

**Comment by aspangaro** [comment]
See my answer : 
https://www.dolibarr.fr/forum/t/fusion-des-tiers-probleme-fenetre/37814/6
