### ISSUE TITLE
Adherent subscription deletion non-asked confirmation causing refused access

### ISSUE THREAD

**Issue by ninichat** [Dolibarr/dolibarr#18706]
# Bug
Upon trying to delete a subscription, an error message is displayed saying that I basically don't have the right to do so; using the superadmin account. Also, a prompt asking me to confirm the deletion isn't displayed.

## Environment
- **Version**: [*14.0.1*]
- **OS**: [*Linux dolibarr 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64*]
- **Web server**: [*Apache/2.4.38 (Debian)*]
- **PHP**: [* 7.3.19-1~deb10u1*]
- **Database**: [*MySQL or MariaDB 5.5.5-10.3.29-MariaDB-1:10.3.29+maria~focal*]
- **URL(s)**: [*/adherents/subscription/card.php*]

## Expected and actual behavior
Expected:
- Click delete on a subscription
- See a confirmation prompt
- Click yes on the prompt
- Delete the subscription
- Redirect to adherents/card.php

(basically running the if at line 142 in htdocs/adherents/subscription/card.php)

Actual:
- Click delete on a subscription
- Instant access refused regardless of permissions

## Steps to reproduce the behavior
- Creating a new adherent subscription if none is existing
- Go to that subscription.
- Click delete.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

The code here (htdocs/adherents/subscription/card.php:269)
```
	if ($action == 'delete') {
		//$formquestion=array();
		//$formquestion['text']='<b>'.$langs->trans("ThisWillAlsoDeleteBankRecord").'</b>';
		$text = $langs->trans("ConfirmDeleteSubscription");
		if (!empty($conf->banque->enabled) && !empty($conf->global->ADHERENT_BANK_USE)) {
			$text .= '<br>'.img_warning().' '.$langs->trans("ThisWillAlsoDeleteBankRecord");
		}
		print $form->formconfirm($_SERVER["PHP_SELF"]."?rowid=".$object->id, $langs->trans("DeleteSubscription"), $text, "confirm_delete", $formquestion, 0, 1);
	}
```
Doesn't seem to trigger a confirmation prompt.
Which ends up as a redirection to action=delete, instead of action=confirm_delete with confirm=yes.
I couldn't find a way to fix the prompt thing, but by setting confirm to 'yes' at the beginning of the file, and forcing a action=confirm_delete, a subscription was deleted (this isn't a solution though obviously).

[*Files*]
Access refused: https://imgur.com/a/sQHn0e1

**Comment by SiM** [comment]
Hi,

Same problem here in 14.0.2.

Thank you @ninichat for the workaround.

**Comment by daraelmin** [comment]
Hi,
I'm not sure, but I think this issue is related with use of Ajax.

Could you try with modify this line
`print $form->formconfirm($_SERVER["PHP_SELF"]."?rowid=".$object->id, $langs->trans("DeleteSubscription"), $text, "confirm_delete", $formquestion, 0, 1);`
To 
`print $form->formconfirm($_SERVER["PHP_SELF"]."?rowid=".$object->id, $langs->trans("DeleteSubscription"), $text, "confirm_delete", $formquestion, 0, 0);`

(Just change the last parameter to zero).

Tell me if this workaround may help.

Cheers

**Comment by daraelmin** [comment]
PS : this is not a propre fix. 

It only meens that we must add jquery code to trigger opening of box (with correct parameters) just after calling this method. : 
`print <script type="text/javascript">'."\n"; print 'jQuery(document).ready(function() {'."\n"; print 'jQuery(".xxxlink").click(function(e) { jQuery("#aparamid").val(jQuery(this).attr("rel")); jQuery("#dialog-confirm-xxx").dialog("open"); return false; });'."\n"; print '});'."\n"; print '</script>'."\n";`

As specified here : https://doxygen.dolibarr.org/13.0/df/d08/class_form.html#a50f4697bdb353b8ad6cc01d0695910c8

**Comment by hregis** [comment]
this is a problem with "restrictedArea" function

`$result = restrictedArea($user, 'subscription', 0); // TODO Check on object id`

try to comment this line 

`// $result = restrictedArea($user, 'subscription', 0);	// TODO Check on object id`

**Comment by daraelmin** [comment]
Are you sure @hregis ?

ninichat said that there is no confirmation prompt. If so, user can not send the confirm=yes to the server.

How restrictedArea may block the confirmation prompt ?

**Comment by hregis** [comment]
restrictArea blocks access to the page, there is a bug in checking the subscription id. 
Moreover there is a todo in comment 
`
// TODO Check on object id`

**Comment by ninichat** [comment]
Indeed, a confirmation prompt is displayed and a subscription can be deleted when I comment that line:
`$result = restrictedArea($user, 'subscription', 0); // TODO Check on object id`

Modifying this line:
`print $form->formconfirm($_SERVER["PHP_SELF"]."?rowid=".$object->id, $langs->trans("DeleteSubscription"), $text, "confirm_delete", $formquestion, 0, 0);`
Doesn't work, no confirmation prompt either.

**Comment by daraelmin** [comment]
This part added by this commit : https://github.com/Dolibarr/dolibarr/commit/d92e17aabd04805c2d38d6aef05582427b6a6598 for hook purpose, I assume. However, I'm mot familiar with the hook system.

But this :
`$result = restrictedArea($user, 'subscription', $id, '', '', 'socid', 'rowid');`
was wrong. I think, cause $id isn't defined at this point. But there is a $rowid defined.

So I can propose this one :
`$result = restrictedArea($user, 'subscription', $rowid);`

I dont know how to specified other fields as fk_soc (and mot socid) is stored un llx_adherent and not in subscription...
