### ISSUE TITLE
Liste des interventions et extrafields

### ISSUE THREAD

**Issue by JPDelaunay** [Dolibarr/dolibarr#18719]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
The list of interventions actually lists the lines of interventions, but allows to display in the columns the extrafields configured on the interventions, but not those configured on the lines of interventions.

## Environment
- **Version**: 13.0.4
- **OS**: Linux h2web41 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64
- **Web server**: Apache
- **PHP**: 7.4.22
- **Database**: MySQL
- **URL(s)**:  https://monserveur/fichinter/list.php

## Expected and actual behavior
The list of interventions does not display the extrafields defined on the intervention lines.
Ideally, it would be necessary to keep the list of interventions which would only list the interventions (with their extrafields) and create a list of intervention lines to list the lines explicitly, with their extrafields.

## Steps to reproduce the behavior
Create an extrafield at the level of interventions (configured to be visible in the lists), create another at the level of the intervention lines (with the same configuration), go to the list of interventions, click on the button to select the fields to display, note that only the extrafield created at intervention level appears in the list

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

Can you write in ENglish please ?

It is the same as for the customer invoice, the list, list all the invoices, but not the invoice lines....

**Comment by JPDelaunay** [comment]
Hi @ksar-ksar
I don't agree.
Customer invoices list lists all the invoices, that's OK, but in the intervention lists, the list is an intervention LINES list.
It is not coherent
