### ISSUE TITLE
v14.0.0. - 14.0.1 y 14.0.2 Las archivos adjuntos asociados a las tareas, no permiten abrirlos ni descargarlos. Solucionado para mi

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#18716]
The files attached to the task appear in the attachment list, but you cannot open or download them. # 18617
alsoft10 I propose a solution # 18589 but in my case it did not work, with all the files attached, some of them did but others remained the same.
There was another problem with the mini images of the attached files in the events, they could be opened, but it did not allow the preview of the thumbnail.
In any case, I thank you for cluing me in on the location of the problem. (which worked for me).
I replaced the file files.lib.php located in Apache24/htdocs/dolibarr/htdocs/core/lib with the same file, but from a version 13.0.3 that I have in a production system.
For the moment it works correctly, although not being a programmer, I don't know if it will eventually generate another problem.

## Environment
- **Version**:14.0.0  14.0.1 - 14.0.2
- **OS**: W10
- **Database**: MarisDB

See if it can be officially fixed in 14.0.3

**Comment by edupulpillo** [comment]
The problem persist in 14.0.3
Trying to access to any attached file to the task using the link is returning a problem of permissions, even using the admin user with all the rights enabled. The only way to be able to access to the file attached is generate a public access link, and use it.

This is the error message returned:

    Access denied.
    You try to access to a page, area or feature of a disabled module or without being in an authenticated session or that is not allowed to your user.
    Current login: admin
    Permission for this login can be defined by your Dolibarr administrator from menu Home->Users.

**Comment by devjointoit** [comment]
Also have the same issue.

**Comment by edupulpillo** [comment]
The problem persist in 14.0.5

**Comment by JoAnMaFe** [comment]
The problem is still active in 14.05
And the "temporary" solution remains the same.
I replaced the file files.lib.php located in Apache24 / htdocs / dolibarr / htdocs / core / lib with the same file, but from a version 13.0.3 that I have on a production system.
The problem also affects the preview of jpg files that are attached in the agenda.

I think the problem may be related to the installation path of dolibarr.

**Comment by edupulpillo** [comment]
Hi @JoAnMaFe 
There is a  simple solution:
Replace projet&project by projet_task&project_task in the line number 2665 of the file /htdocs/dolibarr/htdocs/core/lib/files.lib.php in version 14.0.5
This small update fix the problem.
I just did a PR hoping be accepted for next version.

**Comment by edupulpillo** [comment]
Problem solved with commit  5d5a219 explained in #19770 
Please close this issue
