### ISSUE TITLE
Access denied when subscribe to a new automatic email notification in 14.0.2

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#18728]
# Bug
The user has permision to create/modify his own user information , but when user want to subscribe to a new automatic email notification will show  " Access denied " error in 14.0.2 but not in 13.0.4 .
And i have to enable " Create/modify other users, groups and permissions " , then user will not has this error show out .
Second issue is when user subscribe to a new automatic email notification , the " List all active subscriptions (targets/events) for automatic email notification " zone will disapear in 14.0.2 , but it show in 13.0.4 .

## Environment
- **Version**: [14.0.2]
- **OS**: [windows 7]
- **Web server**: [Apache/2.4.41 (Win64) ]
- **PHP**: [7.4.1]
- **Database**: [MariaDB 5.5.5-10.4.11]
- **URL(s)**: [/user/notify/card.php?id=4]

## Expected and actual behavior
[*Verbose description*]
   Should not show the permission error .

![001](https://user-images.githubusercontent.com/78349579/133615428-df193e5a-fc42-49f0-8c24-65d7eb2c6c6b.png)
![13 0 4](https://user-images.githubusercontent.com/78349579/133615482-98a1c360-2024-475e-b0d0-5b91c514c0e7.png)
![14 0 2](https://user-images.githubusercontent.com/78349579/133615505-bca934d5-104e-42c5-872d-17a4979976d3.png)

**Comment by homer8173** [comment]
seems to be fixed in Dol 15 
Do you have details ?
![image](https://user-images.githubusercontent.com/8720867/138561819-c46e4240-b589-45d8-9e2b-d802b726631b.png)

**Comment by trekmorris** [comment]
Hi 

What detail do you need ?
I have not tried v15 , so i can't confirm that be fixed or not .
