### ISSUE TITLE
Can't see user module settings icon 

### ISSUE THREAD

**Issue by vincentjdc** [Dolibarr/dolibarr#18731]
# Bug
The list of modules/applications does not display the settings icons to add extra fields on the user table
But if I go the url `/admin/user.php` I can access the configuration and add fields.

## Environment
- **Version**: 14

## Expected and actual behavior
the settings icon should be displayed but it's not the case

## Steps to reproduce the behavior
- Install fresh version of dolibarr v14
- go to the modules/application configuration
- try to go to the settings of the user module.

![dolibarr01](https://user-images.githubusercontent.com/50613035/133623273-102934fb-dfc7-4e03-b94d-2d13af34a295.png)

**Comment by ksar-ksar** [comment]
Hello,

Strange, it is working for me on V14.0.2
![image](https://user-images.githubusercontent.com/35605507/133984548-df9692d9-3e2d-40bd-b99f-eff34c7bcd01.png)
