### ISSUE TITLE
HTTP_X_FORWARDED_FOR

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#18738]
Can't the option "HTTP_X_FORWARDED_FOR" also be set via parameters or at least be permanently included in "main.inc.php". 
This has become a common function. 
The best would be a selection about the extended setting in the Dolibarr.

---

if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
	$http_x_headers = explode( ',', $_SERVER['HTTP_X_FORWARDED_FOR'] );

	$_SERVER['REMOTE_ADDR'] = $http_x_headers[0];
}

**Comment by ghost** [comment]
The function must be entered again with each update ...

**Comment by ksar-ksar** [comment]
Hello,

Could you explain the usecase ?

**Comment by ghost** [comment]
Hello,

the X-Forwarded-For (XFF) HTTP header field is a common method for identifying the originating IP address of a client connecting to a web server through an HTTP proxy or load balancer.

This function is necessary as soon as I use a proxy (e.g. HA proxy). A different SRC address is then used from that of the local proxy. So dolibarr can no longer recognize which is the "correct" SRC address of the client. The IP of the proxy is then always displayed in the Dolibarr.


![image](https://user-images.githubusercontent.com/7759288/134020137-4865882f-a76c-44c4-af1f-4427d131a65a.png)

**Comment by ghost** [comment]
Is it possible to implement the function?

**Comment by ghost** [comment]
There must only be a checkbox where you can switch the function on and off

**Comment by soft4net** [comment]
I was not even able to login behind HAProxy because of ERR_TOO_MANY_REDIRECTS after adding those lines to "main.inc.php" problem seems to be solved:

`
if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
	$_SERVER['HTTPS'] = 'on';
}
`

**Comment by ghost** [comment]
@soft4net Here is the configuration that works

<img width="685" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/7759288/0a9d79d8-d5eb-4f36-bf0b-4cd29bc27ee5">

**Comment by ghost** [comment]
I've been using the configuration for several years and it works without any problems.

**Comment by ghost** [comment]
Can you please add the function. Thanks
