### ISSUE TITLE
List of inventories - Deleting - Access denied.

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#18739]
Deleting a "List of inventories" not possible. 
The user has all authorizations but it is not possible to delete the list.

The user already has all rights that I can assign (all)

ERROR:
Access denied.
You try to access to a page, area or feature of a disabled module or without being in an authenticated session or that is not allowed to your user.

![image](https://user-images.githubusercontent.com/7759288/133648808-2e5226fc-4b86-466b-bd14-7aa65aeadda7.png)

![image](https://user-images.githubusercontent.com/7759288/133648602-d2b81833-e8a2-4203-a069-029daa0ed6df.png)

**Comment by ksar-ksar** [comment]
Hello,

What is your Dolibarr version?

**Comment by ghost** [comment]
Hi,

dolibarr-Version - 14.0.2
