### ISSUE TITLE
(French) labels inconsistent between montly detail and summary for monthly VAT report.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#18747]
![image](https://user-images.githubusercontent.com/1504752/133778731-552f06d4-5e79-49c5-a601-aa6d82ea9dd0.png)

# Bug
The VAT Summary shows a different amount for "VAT Claimed" thant he total ov "Claimed VAT".
Currently the total seems to correspond to "Paid VAT".

## Environment
- **Version**: 13.0.2
- **OS**: Debian stretch
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**:  7.4.16
- **Database**: MariaDB 5.6.40-84.0
- **URL(s)**: /compta/tva/index.php

## Steps to reproduce the behavior
- Create service invoice of 4000 € in month A;
- Pay 1000€ in month A;
- Pay 1000€ in month A+1;
- Optionnaly pay 200€ VAT in month A and 150€VAT in month B
- Check report on /compta/tva/index.php - do the analysis for the period 1st day of month A up to last day of month A+1 (=two months).  Verify VAT Received, VAT Claimed and VAT Paid amounts for consistency.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by mdeweerd** [comment]
I will upgrade my installation in the coming weeks and I will follow up on this ticket.

**Comment by mdeweerd** [comment]
I've upgraded my installation earlier than expected to 14.0.2 .

The original issue disappeared because the summary disappeared, but a new one appears as the VAT received in August disappeared from the detail:
![image](https://user-images.githubusercontent.com/1504752/134919653-7dce0508-6334-4f60-9a42-985b16d54e41.png)

The data is the same as in the initial message, so there should be a non 0 amount for August.
