### ISSUE TITLE
Get properties of third party object by email not working - REST API

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#18749]
# Bug
## Get properties of third party object by email is not working in Dolibarr REST API interface.
*While we are searching a third party at REST API interface using by email,it is not working. It is returning only dummy data having email address, specimen[at]specimen.com.  I have attached the screenshots. This is because there is no code written for that. I am mentioning the code here below.*

`private function _fetch($rowid, $ref = '', $ref_ext = '', $barcode = '', $idprof1 = '', $idprof2 = '', $idprof3 = '', $idprof4 = '', $idprof5 = '', $idprof6 = '', $email = '', $ref_alias = '')
	{
		global $conf;
		if (!DolibarrApiAccess::$user->rights->societe->lire) {
			throw new RestException(401);
		}
		if ($rowid == 0) {
			$result = $this->company->initAsSpecimen();
		} else {
			$result = $this->company->fetch($rowid, $ref, $ref_ext, $barcode, $idprof1, $idprof2, $idprof3, $idprof4, $idprof5, $idprof6, $email, $ref_alias);
		}
		if (!$result) {
			throw new RestException(404, 'Thirdparty not found');
		}

		if (!DolibarrApi::_checkAccessToResource('societe', $this->company->id)) {
			throw new RestException(401, 'Access not allowed for login '.DolibarrApiAccess::$user->login);
		}

		if (!empty($conf->global->FACTURE_DEPOSITS_ARE_JUST_PAYMENTS)) {
			$filterabsolutediscount = "fk_facture_source IS NULL"; // If we want deposit to be substracted to payments only and not to total of final invoice
			$filtercreditnote = "fk_facture_source IS NOT NULL"; // If we want deposit to be substracted to payments only and not to total of final invoice
		} else {
			$filterabsolutediscount = "fk_facture_source IS NULL OR (description LIKE '(DEPOSIT)%' AND description NOT LIKE '(EXCESS RECEIVED)%')";
			$filtercreditnote = "fk_facture_source IS NOT NULL AND (description NOT LIKE '(DEPOSIT)%' OR description LIKE '(EXCESS RECEIVED)%')";
		}

		$absolute_discount = $this->company->getAvailableDiscounts('', $filterabsolutediscount);
		$absolute_creditnote = $this->company->getAvailableDiscounts('', $filtercreditnote);
		$this->company->absolute_discount = price2num($absolute_discount, 'MT');
		$this->company->absolute_creditnote = price2num($absolute_creditnote, 'MT');

		return $this->_cleanObjectDatas($this->company);
	}`

As you can see in the above code, there is no code written for searching third party by email.

## Environment
- **Version**: [*14.0.1*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4*]
- **PHP**: [*7.3*]
- **URL(s)**: [*http://localhost/dolibarr/htdocs/api/index.php/explorer/#!/thirdparties/thirdpartiesRetrieveByEmail*]
![wrog return](https://user-images.githubusercontent.com/1249577/133790104-50f8d4a3-ed60-4a86-9968-5e2395852988.png)

**Comment by priojk** [comment]
Sorry to disagree with your analysis about the missing code to fetch the company data. It's ​right in the section you quoted:
`$result = $this->company->fetch($rowid, $ref, $ref_ext, $barcode, $idprof1, $idprof2, $idprof3, $idprof4, $idprof5, $idprof6, $email, $ref_alias);`

What value did you use for rowid in your request? If it's 0, you receive the sample data as specified here:
`if ($rowid == 0) {
$result = $this->company->initAsSpecimen();
} else {`

**Comment by eldy** [comment]
I checked into code of v14.0.1 and the test is
if ($rowid === 0)
And not
if ($rowid == 0)
So you should not have the bug with 14.0.1

**Comment by alsoft10** [comment]
I completely understand. But there is nothing to do with the row I'd here. We searching the third-party using their email. So email is more important here.This _fetch function is actually called by main function that is written at the beginning  side of class. I am not by my computer now. If I would I would show that function is calling the _fetch function without any row id. There no code written there. Just review the class again. You can understand what I want to say.On Sep 17, 2021 21:41, Laurent Destailleur ***@***.***> wrote:
I checked into code of v14.0.1 and the test is
if ($rowid === 0)
And not
if ($rowid == 0)
So you should not have the bug with 14.0.1

**Comment by eldy** [comment]
This is the expected behavior.
When you call the api to fetch a user from email, the call to _fetch is done without rowid set. So the rowid === 0 is false and it does not return the specimen data, instead it return the third party with the email.
I tested with 14.0.1 and api seems to work correctly.

**Comment by alsoft10** [comment]
@eldy You are right. But the problem comes when we have more than two Third-parties with same email address. API returns specimen data or not data at all. I think in the case of duplicate third-parties, the API should return the latest third party. 

As the Dolibarr allows creating multiple thirdparties with the same email address, it is solely responsible of the admin to merge the thirdparties if they don't want the duplicate. But API must return latest third parties.
