### ISSUE TITLE
Can't enable advanced permission when use traditional chinese ( zh_TW ) interface 

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#18758]
# Bug
When administrator of dolibarr useing traditional chinese ( zh_TW ) , then administrator can't enable the function " Use the advanced permissions of some modules " .
But if use english interface , then administrator can enable this function .

## Environment
Version: [14.0.2]
OS: [windows 7]
Web server: [Apache/2.4.41 (Win64) ]
PHP: [7.4.1]
Database: [MariaDB 5.5.5-10.4.11]
URL(s):/admin/security_other.php?mainmenu=home

## Expected and actual behavior
Should can enable this function in any language .

**Comment by ksar-ksar** [comment]
Hello,

What does that mean "can't enable the function" ? Error message ?

**Comment by trekmorris** [comment]
Hi

That is mean can't enable advanced permission .

**Comment by ksar-ksar** [comment]
Works for me !
![image](https://user-images.githubusercontent.com/35605507/134147492-5fe3e484-56d4-4426-97f1-d0f4bd20829b.png)

**Comment by trekmorris** [comment]
Hi

What is your host OS ? Linux or windows ?
My linux host also works , but fail in windows .

**Comment by ksar-ksar** [comment]
Linux
