### ISSUE TITLE
Unable to delete membership record

### ISSUE THREAD

**Issue by gzanelli** [Dolibarr/dolibarr#18767]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When trying to delete a membership record, a error message appears : Accès refusé.
"Vous essayez d'accéder à une page, région ou fonctionnalité d'un module désactivé, ou sans être dans une session authentifiée, ou avec un utilisateur non autorisé."
Being in superadmin role, all rights granted.

## Environment
- **Version**: 14.0.2
- **OS**: Ubuntu 16.04
- **Web server**: apache 2.2
- **PHP**: 7.4.11
- **Database**:MySQL or MariaDB 5.5.5-10.0.38-MariaDB-0ubuntu0.16.04.1
- **URL(s)**: /htdocs/adherents/subscription/card.php?rowid=450&action=delete&token=3b960b67b4cea92b16485434eed4152b

## Expected and actual behavior
Expected : confirmation for record deletion
Actual : error message mentionning rights or inexistant page

## Steps to reproduce the behavior
Create membership
Delete membership

## [Attached files]
screenshot
![2021-09-20 17_34_47-Agatsukan Eghezée](https://user-images.githubusercontent.com/37375693/134030525-c62afdc5-f1ce-433a-adab-7ac5dc140eb1.png)

**Comment by gzanelli** [comment]
I just checked on version 14.0.1, same issue.

**Comment by ksar-ksar** [comment]
Hi,

I confirm it with the V14.0.3....

**Comment by gzanelli** [comment]
Fix confirmed.
