### ISSUE TITLE
Add turnover widget

### ISSUE THREAD

**Issue by ywarnier** [Dolibarr/dolibarr#18768]
# Feature Request
Add a widget to show the turnover for the last x years

## Use case
Show the total amount for customer invoices (aka turnover) for the last x years, where x can be defined through MAIN_NB_OF_YEAR_IN_WIDGET_GRAPH.

## Suggested implementation
I will send a PR for that.

**Comment by ywarnier** [comment]
Sent in #18769

**Comment by aspangaro** [comment]
Thanks for integration
