### ISSUE TITLE
Reception Module : Uncaught Error: Class 'CommandeFournisseur' 

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#18765]
# Bug
When we try to access to a reception, url : https://doli.xxxxxxxx/14/reception/card.php?id=1

PHP Fatal error:  Uncaught Error: Class 'CommandeFournisseur' not found in /var/www/doli/14/core/class/commonobject.class.php:1813
Stack trace:
#0 /var/www/doli/14/reception/card.php(127): CommonObject->fetch_origin()
#1 {main}
  thrown in /var/www/doli/14/core/class/commonobject.class.php on line 1813

Referer: https://doli.xxxxxx.xxx/14/reception/list.php?leftmenu=receptions

## Environment
- **Version**: V14.0.3
- **OS**: Debian
- **Web server**: Apache2
- **PHP**: 7.3.29
- **Database**: Mysql
- **URL(s)**: https://doli.xxxxxxxx/14/reception/card.php?id=1

**Comment by Hystepik** [comment]
Hello,
It works for me in last version of branch 14

**Comment by ksar-ksar** [comment]
Hi,

I downloaded the last version of branch 14 and still the same.
Anyway it is not blocking for me, so if you can't reproduce, we can close.
