### ISSUE TITLE
No Social network entries visible with multicompanies

### ISSUE THREAD

**Issue by choybe** [Dolibarr/dolibarr#18774]
# Bug
When enabling the social network with other companies than the master entity the are not visible on Third party & Contact forms, neither can be the different social media can be configured individually, per entity.
A reason can be: when activating social networks on an entity not master entity no data with ref entity are set in the database the table llx_c_socialnetworks. All entries there refer to entity 1.     

But the code calls for the entity of the entity of the entry eg:
SELECT rowid, code, label, url, icon, active FROM llx_c_socialnetworks WHERE entity=3  

A reason may be that the table llx_c_socialnetworks column entity is set to default 1? 

When using the multicompany option to share Third Parties / Contacts between the entries
It is possible to edit the social networks entries on the master entity, and they are then visible on the other entity.
But as told above when editing the contact on the given entity the form fields are not visible

**Comment by ksar-ksar** [comment]
Hi,

This BUG is in relation to the External Module " Multicompany". 
So not related to the Dolibarr core.

You need to contact the developer : https://support.inodbox.com/?lang=en_US

**Comment by hregis** [comment]
@choybe
HI, I see this quickly... Thanks
