### ISSUE TITLE
upgrade 13 to 14

### ISSUE THREAD

**Issue by TimothyTH** [Dolibarr/dolibarr#18789]
Hi,

When updating the database 13 to 14, I got this as an error.

Request 170 sql='create table jfjejhk42k_eventorganization_conferenceorboothattendee_extrafields(rowid integer AUTO_INCREMENT PRIMARY KEY,tms timestamp,fk_object integer NOT NULL,import_key varchar(14)) ENGINE=innodb;'
Erreur DB_ERROR_1103: create table jfjejhk42k_eventorganization_conferenceorboothattendee_extrafields(rowid integer AUTO_INCREMENT PRIMARY KEY,tms timestamp,fk_object integer NOT NULL,import_key varchar(14)) ENGINE=innodb;Incorrect table name 'jfjejhk42k_eventorganization_conferenceorboothattendee_extrafields'
Request 171 sql='ALTER TABLE jfjejhk42k_eventorganization_conferenceorboothattendee_extrafields ADD INDEX idx_conferenceorboothattendee_fk_object(fk_object);'
Erreur DB_ERROR_1103: ALTER TABLE jfjejhk42k_eventorganization_conferenceorboothattendee_extrafields ADD INDEX idx_conferenceorboothattendee_fk_object(fk_object);Incorrect table name 'jfjejhk42k_eventorganization_conferenceorboothattendee_extrafields'

Do you have any idea what can be wrong ?

Thx
Timo

**Comment by ksar-ksar** [comment]
Hello,

The problem is the table name : jfjejhk42k_eventorganization_conferenceorboothattendee_extrafields
MYSQL allows only 64 characters and you have 66.
Your table prefix is too loung : jfjejhk42k_

**Comment by TimothyTH** [comment]
Hello,

Exactly I had not spent there.

Thx
Bye
