### ISSUE TITLE
Can't make Dav Module working...

### ISSUE THREAD

**Issue by Thatoo** [Dolibarr/dolibarr#18787]
# Bug
When I go on /dav/fileserver.php, I'm asked to identify but then I get a very weird page without css and then, if  I go to /dav/fileserver.php/private, I get a 404 error page.

## Environment
- **Version**: 14
- **OS**: Debian Bullseyes
- **Web server**: Nginx 1.18
- **PHP**: PHP 7.4
- **Database**: Mariadb
- **URL(s)**: /dav/fileserver.php

## Expected and actual behavior
/dav/fileserver.php doesn't display well
![image](https://user-images.githubusercontent.com/464782/134213483-6c2a0391-648b-47e7-bfcf-79a32a43e221.png)

/dav/fileserver.php/private gives a 404 error page

I guess the reason is that the Dav Module is based on SabreDAV : 3.2.2
and SabreDAV support PHP 7.4 from v 4.1.0 : https://github.com/sabre-io/dav/releases/tag/4.1.0

**Comment by Thatoo** [comment]
I've tried to install PHP 7.3 and I got the same mistake so might probably not be a php version issue. What could it be?

**Comment by Thatoo** [comment]
If I look at the console (F12) in firefox when I go to /dav/fileserver.php, then I cn see these error : 

> GEThttps://dolibarr.atossa.fr/dav/fileserver.php/?sabreAction=asset&assetName=sabredav.css
> [HTTP/2 404 Not Found 0ms]
> 
> GEThttps://dolibarr.atossa.fr/dav/fileserver.php/?sabreAction=asset&assetName=openiconic/open-iconic.css
> [HTTP/2 404 Not Found 0ms]
> 
> GEThttps://dolibarr.atossa.fr/dav/fileserver.php/?sabreAction=asset&assetName=sabredav.png
> [HTTP/2 404 Not Found 0ms]
> 
> GEThttps://dolibarr.atossa.fr/dav/fileserver.php/?sabreAction=asset&assetName=favicon.ico
> [HTTP/2 404 Not Found 0ms]

Nothing appear on error.log file that I set in my nginx config : 

```
server {

        root /var/www/dolibarr/htdocs;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html index.php;

        server_name dolibarr.example.fr;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
                fastcgi_intercept_errors on;
                include         fastcgi_params;
                fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param   SCRIPT_NAME $fastcgi_script_name;
        #       # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dolibarr.example.fr/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dolibarr.example.fr/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    error_log /var/log/nginx/dolibarr.example.fr/error.log warn;
    access_log /var/log/nginx/dolibarr.example.fr/access.log;

}
server {
    if ($host = dolibarr.example.fr) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        listen [::]:80;

        server_name dolibarr.example.fr;
        return 404; # managed by Certbot
}
```

**Comment by Thatoo** [comment]
OK, I just needed to change the line

`        location ~ \.php$ {`

to

`        location ~ [^/]\.php(/|$) {`

and it works.

Why is it so difficult to find an nginx config file for Dolibarr? Why is it not in the wiki?

**Comment by priojk** [comment]
Great that you figured it out! The Wiki is actually maintained jointly by all of us (i.e. the community) and it's very easy to contribute. So I guess it would be nice if you could include your now working config file as an example in the Wiki.

**Comment by Thatoo** [comment]
Done : https://wiki.dolibarr.org/index.php?title=Pr%C3%A9requis#Configuration_Nginx

**Comment by Thatoo** [comment]
@priojk @ksar-ksar I have tried to add to the wiki https://wiki.dolibarr.org/index.php?title=Pr%C3%A9requis&oldid=52079 but it has been removed...
I might not have the right to do it... never mind, others can find it in here.
Maybe I should open an issue called nginx config just to keep track of it somewhere being easy to find...

**Comment by ksar-ksar** [comment]
@Thatoo it is not removed, but moved to a new page : https://wiki.dolibarr.org/index.php?title=Webserver
@eldy re-arrange it.

**Comment by Thatoo** [comment]
Great. That is what I wanted to do but I couldn't find how to create a new page, only how to edit an existing page. All for the best then. Thank you @eldy
