### ISSUE TITLE
Extrafields Date break filtered search on ressources list

### ISSUE THREAD

**Issue by BlueGarm** [Dolibarr/dolibarr#18806]
Hi, 
On Dolibarr 14.0.2, on the module "Ressources" if we perform a filtered search, and we have date type extrafields, this is break completly the request (you can find the error message displayed on the screen).
Extrafields can be empty or not we obtain the same result, but if we choose to hide this type of extrafields in list view, we fix the issue.

**Other clue to fix this issues:** 
The error message indicate: "**_You have an error in your SQL syntax_**" and if we check the SQL request we can find an empty conditionnal request "**_AND ()_**" at the end BUT if we perform the same request without that (with phpmyadmin or in terminal) we obtain a correct response.

Thanks,

_
**Warning**: urlencode() expects parameter 1 to be string, array given in **C:\dolibarr\www\dolibarr\htdocs\resource\list.php** on **line 90**
**Warning**: trim() expects parameter 1 to be string, array given in **C:\dolibarr\www\dolibarr\htdocs\core\lib\functions.lib.php** on line **8813**

Date: 20210923111612
Dolibarr: 14.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.3.12
Server: Apache/2.4.41 (Win64) PHP/7.3.12
OS: Windows NT TIMC-GEM-61P 10.0 build 19043 (Windows 10) AMD64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

Url sollicitée: /dolibarr/resource/list.php
Referer: http://localhost/dolibarr/resource/list.php?idmenu=186&mainmenu=tools&leftmenu=
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, facture, fckeditor, contrat, product, stock, projet, notification, agenda, ecm, fournisseur, resource, service, societe, ticket, blockedlog, productbatch, categorie, multicurrency, bookmark, import, export, knowledgemanagement
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT t.rowid, t.entity, t.ref, t.description, t.fk_country, t.fk_code_type_resource, t.tms, ty.label as type_label FROM llx_resource as t LEFT JOIN llx_c_type_resource as ty ON ty.code=t.fk_code_type_resource LEFT JOIN llx_resource_extrafields as ef ON ef.fk_object=t.rowid WHERE t.entity IN (1) AND t.ref LIKE '%autoclave%' AND ()
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

Message: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
_

**Comment by ksar-ksar** [comment]
Hi,

I can confirm the bug on the latest V14.0.3 from Git.

Log : 
> 2021-09-23 15:11:48 NOTICE  127.0.0.1       --- Access to POST /14/resource/list.php - action=list, massaction=
> 2021-09-23 15:11:48 DEBUG   127.0.0.1       sql=SELECT transkey, transvalue FROM llx_overwrite_trans where lang='en_US' OR lang IS NULL AND entity IN (0, 1) ORDER BY lang DESC
> 2021-09-23 15:11:48 DEBUG   127.0.0.1       sql=SELECT m.rowid, m.type, m.module, m.fk_menu, m.fk_mainmenu, m.fk_leftmenu, m.url, m.titre, m.prefix, m.langs, m.perms, m.enabled, m.target, m.mainmenu, m.leftmenu, m.position FROM llx_menu as m WHERE m.entity IN (0,1) AND m.menu_handler IN ('eldy','all') AND m.usertype IN (0,2) ORDER BY m.position, m.rowid
> 2021-09-23 15:11:48 DEBUG   127.0.0.1       sql=SELECT rowid, name, label, type, size, elementtype, fieldunique, fieldrequired, param, pos, alwayseditable, perms, langs, list, printable, totalizable, fielddefault, fieldcomputed, entity, enabled, help FROM llx_extrafields WHERE elementtype = 'resource' ORDER BY pos
> 2021-09-23 15:11:48 DEBUG   127.0.0.1       sql=SELECT rowid, title, url, target FROM llx_bookmark WHERE (fk_user = 12 OR fk_user is NULL OR fk_user = 0) AND entity IN (1) ORDER BY position
> 2021-09-23 15:11:48 DEBUG   127.0.0.1       sql=SELECT  t.rowid, t.entity, t.ref, t.description, t.fk_country, t.fk_code_type_resource, t.tms, ty.label as type_label FROM llx_resource as t LEFT JOIN llx_c_type_resource as ty ON ty.code=t.fk_code_type_resource LEFT JOIN llx_resource_extrafields as ef ON ef.fk_object=t.rowid WHERE t.entity IN (1) AND ()
> 2021-09-23 15:11:48 ERR     127.0.0.1       DoliDBMysqli::query SQL Error message: DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
> 2021-09-23 15:11:48 DEBUG   127.0.0.1       Dolresource::fetch_all
> 2021-09-23 15:11:48 DEBUG   127.0.0.1       sql=SELECT  t.rowid, t.entity, t.ref, t.description, t.fk_country, t.fk_code_type_resource, t.tms, ty.label as type_label FROM llx_resource as t LEFT JOIN llx_c_type_resource as ty ON ty.code=t.fk_code_type_resource LEFT JOIN llx_resource_extrafields as ef ON ef.fk_object=t.rowid WHERE t.entity IN (1) AND ()
> 2021-09-23 15:11:48 ERR     127.0.0.1       DoliDBMysqli::query SQL Error message: DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
> 2021-09-23 15:11:48 ERR     127.0.0.1       Error url=/14/resource/list.php, query_string=, sql=SELECT  t.rowid, t.entity, t.ref, t.description, t.fk_country, t.fk_code_type_resource, t.tms, ty.label as type_label FROM llx_resource as t LEFT JOIN llx_c_type_resource as ty ON ty.code=t.fk_code_type_resource LEFT JOIN llx_resource_extrafields as ef ON ef.fk_object=t.rowid WHERE t.entity IN (1) AND (), db_error=You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1, msg=You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
> 2021-09-23 15:11:48 INFO    127.0.0.1       --- End access to /14/resource/list.php
