### ISSUE TITLE
Increase tax data base columns precision

### ISSUE THREAD

**Issue by Ahuahuachi** [Dolibarr/dolibarr#18805]
# Feature Request
Increase database precision on tax fields to at least 4 digits after decimal (ex. 99.9999)

## Use case
I recently found that the database precision for taxes (localtax1 and localtax2) for invoices needed to be increased to 4 digits after decimal for my country. I think that it should be the rule as it is more common to have 4 digits of precision on taxation documents.

## Suggested implementation
Declare al tax columns as `double(6,4)`

**Comment by eldy** [comment]
Are you speaking about the rate or the amount ?
