### ISSUE TITLE
Error importing inventories: Duplicate entry ‘17-1’ for key ‘uk_product_stock’ inventory import

### ISSUE THREAD

**Issue by chbacher** [Dolibarr/dolibarr#18804]
# Instructions
- Import function of inventory / product stock based on xls / cvs template generates "Duplicate entry ‘17-1’ for key ‘uk_product_stock’" error
- All products / article reference numbers are "numbers" only e.g. Product A has id=17 and article number: 1158490

# Bug
Use template as provided

<html>
<body>
<div class="md-table" style="overflow-y: auto; margin: 1em 0px; color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Product* (ps.fk_product) | Warenlager* (ps.fk_entrepot) | Warenbestand* (ps.reel)
-- | -- | --
ref:1031270 | id:1 | 8

</div>
</body>
</html>

or

<html>
<body>

Product* (ps.fk_product) | Warenlager* (ps.fk_entrepot) | Warenbestand* (ps.reel)
-- | -- | --
17 | 1 | 8

</body>
</html>

leads to the above mentioned error

## Environment
- 14.0.0
- Windows

## Expected and actual behavior
Generates error where none should be

## [Attached files]
![temp](https://user-images.githubusercontent.com/14800362/134459443-275cd1de-1720-425e-8c7e-b5edb0c2ba56.png)

**Comment by priojk** [comment]
Just a question: In the screenshot, there is no setting for updating existing products selected (no key for updating selected: "Schlüssel (Spalte), der zum Aktualisieren der vorhandenen Daten verwendet wird"). The text on the right side says, that only new data sets are expected. So, if a product with the article number 17 does already exist in the database, Dolibarr is right to report a conflict during the import. Could you please check, if this is the case?

**Comment by chbacher** [comment]
A damn, the devil is a squirrel.

You are absolutely right. Now it went through flawlessly. Thanks for your help
