### ISSUE TITLE
Add legal entity types for Sweden (SE)

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#18814]
Legal entity types for Sweden (SE) is missing in Dolibarr as of version 12.0.5 so I have assembled a list of all the entities that are available in Sweden. Unfortunately I do not know how to create a patch-file for this so I created SQL-statements in the attached file if that's of any help.

    # Entity code    Entity name
      5001           Aktiebolag
      5002           Publikt aktiebolag (AB publ)
      5003           Ekonomisk förening (ek. för.)
      5004           Bostadsrättsförening (BRF)
      5005           Hyresrättsförening (HRF)
      5006           Kooperativ
      5007           Enskild firma (EF)
      5008           Handelsbolag (HB)
      5009           Kommanditbolag (KB)
      5010           Enkelt bolag
      5011           Ideell förening
      5012           Stiftelse

[llx_c_forme_juridique.sql.txt](https://github.com/Dolibarr/dolibarr/files/7225020/llx_c_forme_juridique.sql.txt)

**Comment by eldy** [comment]
This can be done by completing the file 
llx_c_forme_juridique.sql
