### ISSUE TITLE
Can't click " SET ACCEPTED/REFUSED " in propalsal ( You don't have permission for this action . ) v14.0.2

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#18826]
# Instructions
After enable  "  Use the advanced permissions of some modules " , user can't click  " SET ACCEPTED/REFUSED " in propalsal even user is administrator .
And as my testing , enable / disable " Send commercial proposals (Permision available in Advanced permission mode only) " in user permission page will will enable / disable " SEND EMAIL " in propalsal . But enable / disable " Validate commercial proposals (Permision available in Advanced permission mode only) " will not enable / disable " SET ACCEPTED/REFUSED " in propalsal ( Alway show " SET ACCEPTED/REFUSED " in anti-white , can't click . ) .

Also i confirm this issue is not happen in windows .

# Bug
Can't click  " SET ACCEPTED/REFUSED " in propalsal even user is administrator .

## Environment
- **Version**:14.0.2
- **OS**: MX Linux 19.3
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.4.3
- **Database**: MariaDB 5.5.5-10.3.29-MariaDB-0+deb10u1
- **URL(s)**: 
/user/perms.php?id=1&action=addrights&entity=1&rights=22&confirm=yes&token=1460cc10653f37a4f802f098d7859fca&page_y=1102.4000244140625
comm/propal/card.php?id=987&action=confirm_validate&confirm=yes&token=c4f20e1256aab2d3bb8da2561e872e51#
## Expected and actual behavior
[*Verbose description*]

Should fix the permission issue , so user can click " SET ACCEPTED/REFUSED " when user has the permission .

## Steps to reproduce the behavior
[*Verbose description*]

[*Files*]
![image](https://user-images.githubusercontent.com/78349579/134777127-a8b14134-b56b-42a6-80eb-9ed5b396f80c.png)
![image](https://user-images.githubusercontent.com/78349579/134777138-f9c92515-b1c6-44ee-8377-20affb94bbfd.png)

**Comment by homer8173** [comment]
can you try to disable + reactivate the all Proposals rights ?
it have fixed rights for me in past

**Comment by trekmorris** [comment]
hi

i have tried it , and it works .
Thanks .
