### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ditsa17** [Dolibarr/dolibarr#18829]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.2
- **OS**: Linux
- **Web server**: nginx/1.19.8
- **PHP**: fpm-fcgi 7.3.30
- **Database**:  5.6.50-log
- **URL(s)**: /index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
And I think this one should be closed...
