### ISSUE TITLE
PHP warning: Non-numeric value / Cannot modify header

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#18835]
# Bug

## Environment
- **OS**: Linux
- **Web server**: Apache
- **URL(s)**: paiement.php apparently

## Steps to reproduce the behavior

Go to customer invoice.
Click enter payment.
Payment is validated.
User is redirected to error.
The process is saved correctly most of the time regardless of the error, but it's still worrying.

**Comment by homer8173** [comment]
Thanks for report, it was just a warning that should not be displayed by your server. 
With the following redirection, it locks you there.
See doc for server setup there : 
https://stackify.com/display-php-errors/#post-21585-_qk7srln7jw59
display_errors = off
