### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ditsa17** [Dolibarr/dolibarr#18830]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.2
- **OS**: Linux
- **Web server**: nginx/1.19.8
- **PHP**: fpm-fcgi 7.3.30
- **Database**:  5.6.50-log
- **URL(s)**: /index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Report
A/ Customer invoice: payment problem when you enter payment to  pay
Warning: A non-numeric value encountered in /www/wwwroot/erp.ditsa.cn/htdocs/compta/paiement.php on line 134

B/ MRP problem: The import function of Bill of material and bill of materials line are not complete, the data can't be imported
And hope it can be possible to generate excel instead of odt file about the bill of materials list and maunfacturing orders list.

C/ Purchase order: erros happens when there's more vendors price and when you want to change to another product
a) When we add the product in purchase order list, if this product have 3 different prices, it will add all prices in the list even I only choose one of them
b) When we choose one product, it shows detail, but we haven't click "add". then we change another product, but the quantity and price didn't change by product changing, it still show last product's.

D/ Customer account: What customer account saw are different from what internal account saw.
a) When we make a commercial proposal, what we saw is normal, but from customer's account, always show the same proposal, no matter how many proposal we made, but PDF is correct
b) The permission changed. The same permission as before, but this version , customer can't read the orders and some informations

There's more bugs, hope it can be solved soon. Thanks！

**Comment by atm-maxime** [comment]
Thanks for reporting.
Can you open 1 issue per bug ? And have a meaning title related ?
