### ISSUE TITLE
BUG[?]: ACCOUNTING (DOUBLE ENTRY) wrong account match for payment

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#18844]
# Bug
Payment linked to wrong account code

## Environment
- **Version**: 13.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.3.30
- **Database**: MariaDB 5.5.5-10.3.31

## Expected and actual behavior
We have setup tax account code and expense reports account code. For salaries everything is OK. However, for social insurance not.

Workflow: Create expense report for salaries then payment from "Billing > Salaries > New payment". Rezult is 604000 transfered to 421000 (set for Accounting account used for user third parties).

Create expense report for social insurance and then payment from "Billing > Paymnt > New social/fiscal tax". Expected behavior is 605000 to be linked to 424000. Instead, it is linked to 421000.

More info about setup and result in the attachments.

## **Default accounts**
![Screenshot_1](https://user-images.githubusercontent.com/4587305/135107547-2dd4cdb9-b132-413d-883c-250e54554bd9.png)

## **Expense report - Types of expense report lines**
![Screenshot_2](https://user-images.githubusercontent.com/4587305/135107595-e29c5719-107c-4049-9478-f4225188599f.png)

## **Tax accounts**
![Screenshot_3](https://user-images.githubusercontent.com/4587305/135107620-f91a9238-5e92-4ab7-ae9b-410818c94aaf.png)

## **Result for salaries**
![Screenshot_4](https://user-images.githubusercontent.com/4587305/135107636-a2297c05-e1e1-46ca-a734-9cae866595c3.png)

## **Result for social insurance**
![Screenshot_5](https://user-images.githubusercontent.com/4587305/135107644-88f5052c-a13e-48aa-8137-bcbc3610b19f.png)

**Comment by aspangaro** [comment]
Hello,

Sorry, I don't understand your problem.

Why the accounting account should be 424000 than 421000 in expensereport transaction ?

**Comment by milenmk** [comment]
> Hello,
> 
> Sorry, I don't understand your problem.
> 
> Why the accounting account should be 424000 than 421000 in expensereport transaction ?

421000 is for salaries paid to the employees, while 424000 is for social incurance of those employees and is paid to the state.

**Comment by milenmk** [comment]
So can anyone explain how exactly the account matching works? I.e. How can I say, that one account, let's say 605000, should be debited to 454000 and then have a credit from 454000 to 503000?

After some investigation, I've found that for this particular example, in `llx_accounting_bookkeeping` no record is inserted for subledger_account. Before inserting into the main ledger, on `/accountancy/journal/expensereportsjournal.php` it says it will be linked to 421000 (when we need 454000), and then, after registering into the ledger it is not linked to anything. If I manually edit the database as per screenshot one, the result is as it should be on screenshot 2.

![Screenshot_1](https://user-images.githubusercontent.com/4587305/140163380-eef8a7d4-7a78-4415-822e-fec06c3a4257.png)

![Screenshot_2](https://user-images.githubusercontent.com/4587305/140163400-1eccf902-4ec3-474b-bd6c-368f42ebfa04.png)

I think this is a major issue when adding new account options besides the default settings in Dolibarr (Dictionary setup - Expense report - Types of expense report lines for example).

@eldy ?
