### ISSUE TITLE
Manage user rights automatically

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#18841]
# Feature Request
[*Short description*]
Manage user rights automatically.
## Use case
[*Verbose description*]
I am trying to identify modules and their options in order to change user rights (mostly external users) with a schedule, to force certain operations only in certain periods (i.e allow orders to be made only on specific days or hours ranges).
## Suggested implementation
[*Verbose description*]
I already identified the llx_users and llx_users_rights tables and the group tables, but the llx_dolibarr_modules is currently missing although documented in the wiki. What I am missing is a table that identifies the modules options (read, modify, delete,....)

## Suggested steps
[*List of tasks to achieve goal*]
Base needs:
Get the llx_dolibarr_modules added to the databse schema
Populate it automatically at install/upgrade
Create a llx_dolibarr_modules_options table with their corresponding numbers (from the ones used in llx_user_rights)
Advance Needs:
Create a module to manage the schedule by user/rights.

**Comment by eldy** [comment]
The table llx_dolibarr_modules is no more used.
What means "schedule" user/rights ?
