### ISSUE TITLE
Virtual stock cache improvement

### ISSUE THREAD

**Issue by john-botella** [Dolibarr/dolibarr#18842]
# Feature Request

Add cache for Virtual stock. 
The cache could be updated by triggers on each element susceptible to impact the stock so as to force virtual stock update for products impacted.

A cron job could also do an update to force calc

## Suggested implementation

Add new table product_virtual_stock with : 
```rowid, fk_product, element, qty, tms```

Element col is important to be able to separate calc, a simple SUM() will do the job to get current virtual stock

**Comment by atm-maxime** [comment]
To keep

**Comment by atm-maxime** [comment]
To keep
