### ISSUE TITLE
MouvementStock::setOrigin working only for project ???

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#18852]
https://github.com/Dolibarr/dolibarr/blob/01c8bbedbfa76cad1ada75242bda4658dfa89b31/htdocs/product/stock/class/mouvementstock.class.php#L1009

i tryed to pass an object to this function and it avoid my origin, it only support project

does it sound normal to you ?

**Comment by eldy** [comment]
No.
I made a re-engeneering of this in v15.

**Comment by JohnXLivingston** [comment]
> No. I made a re-engeneering of this in v15.

Hello @eldy. Is there any workaround with Dolibarr 12 (or 14?) to make product->correct_stock take into account $origin_element and $origin_id? 
Because of this bug, these values are not saved on the movement.
