### ISSUE TITLE
fckeditor wrong encoding in pdf and odt

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#18856]
# Bug
the output of many accented and special characters and breaks in odt and pdf documents is alike this:
l'!"£$%&èé*+çòàù§°.;l'ì^=)(/&%$£"

## Environment
- **Version**: 14.0.2

## Expected and actual behavior
Good encodage
Use https://github.com/ckeditor/ckeditor5 ? Stop dreaming ok !

## Steps to reproduce the behavior
Active Fckeditor and try special characters like
é l'apostrophe etc...

![image](https://user-images.githubusercontent.com/3288514/135346953-92cdac86-0e3b-4a3b-b767-be51691f3fbe.png)

Links
https://www.dolibarr.org/forum/t/fckeditor-wrong-encoding/15945/4

**Comment by ksar-ksar** [comment]
Hello,

I can reproduce it. on my 14.0.3.

I have put your strings : l'!"£$%&èé*+çòàù§°.;l'ì^=)(/&%$£"
On description of existing product
On free lines
On description of product

All is good...
![image](https://user-images.githubusercontent.com/35605507/135524792-e80cc27b-deb4-4b1f-a54d-6cb85219e58d.png)

**Comment by FHenry** [comment]
Fixed by this commit https://github.com/Dolibarr/dolibarr/commit/68d24661dbd27bdcfd87bdfa859e94b720c1ebad
in Release on 14.0.2
