### ISSUE TITLE
Overwriting files if exists in DMS/ECM does not work

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#18854]
We uploaded some process files to the "Document" area. Immediately we found an error in the files so we re-uploaded them and checked "Overwrite file if exists", then Dolibarr complains that the files exists.

Expected outcome is that Dolibarr actually overwrites the files when the checkbox is active, and not warn about it.

![2021-09-29_182828](https://user-images.githubusercontent.com/11036018/135310705-6486fbc1-dae3-4458-900e-fb1d76357e26.png)

**Comment by ksar-ksar** [comment]
Confirmed on V14.0.3
