### ISSUE TITLE
Custom field included in list of tasks

### ISSUE THREAD

**Issue by conformist66** [Dolibarr/dolibarr#18876]
# Feature Request
When displaying lists of tasks under Projects section, there seems to be no ability include custom fields that I've created in the list.

## Use case
I am an electrician. I have a custom field called 'room' which is the location where the task is to be undertaken.  e.g. I'm installing a light in the master bedroom.  I would like to be able to include in the list, the master bedroom so I can sort/filter by it and other rooms.  Currently, I'm using a work-around where I click on 'list' (under tasks/activities) and have to filter out all of the other projects.  The custom field does appear in that list.  I can see this becoming an issue as the task list grows over time.

**Comment by matDOTviguier** [comment]
+1
