### ISSUE TITLE
 Bug : Invalid argument supplied for foreach() in reception\list.php

### ISSUE THREAD

**Issue by PyroShape** [Dolibarr/dolibarr#18875]
# Bug
I have got this message on the top of the screen :
Invalid argument supplied for foreach() in reception\list.php on line 615

## Environment
New installation test of 14.0.3
Php version = 7.1.9

**Comment by ksar-ksar** [comment]
Hi,

What is your php version?

**Comment by PyroShape** [comment]
Hi,

php version = 7.1.9
