### ISSUE TITLE
Proposal Extrafields compute not working as expected

### ISSUE THREAD

**Issue by alexakis13** [Dolibarr/dolibarr#18870]
![Screenshot_1](https://user-images.githubusercontent.com/19177394/135618612-e9dd0885-7079-409b-920d-3886c3386103.png)
Hello I m trying to compute some extrafields to calulate the square meters of a product in Proposal form. I did make the 3 extrafields ex. length, width, result and I m giving the numbers to the length and width. If I m gonna use 
`$object->array_options['options_length'] * $object->array_options['options_width']` to calculate the result,
the result field return 0.
After this attempt I tried to retrieve the values from the DB so I use this code:

`($req = $db->query('SELECT rowid FROM llxxh_propaldet as ps WHERE ps.fk_propal='.$object->id.';')) && ($req = $db->fetch_object($req)) && ($req1 =$db->query('SELECT * FROM llxxh_propaldet_extrafields as ef WHERE ef.fk_object='.$req->rowid.';')) && ($req1 = $db->fetch_object($req1)) ? $req1->length*$req1->width : -1;`

That runs correct but only for the first entry of products the other entries keeps the first result.
Im stuck..

**Comment by ksar-ksar** [comment]
Hi,

The extrafield that you are using are LINE extrafiled not OBJECT
So you need to use `$object->lines[$i]->array_options['options_my_line_extra']`

**Comment by alexakis13** [comment]
Hello,

I tried it but keeps returning 0

Thank you for the quick response!

ksar-ksar I think i used a module you made to compute the result (with some changes) but didnt seem running.

the code i used before is inside the compute extrafield. Should I edit it in a module someway?
