### ISSUE TITLE
[Feature request] Tickets improvement

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#18889]
# Feature Request
Extend tickets module and emails for tickets

## Suggested steps
1. Auto add ticket creator as "contributor". Thus, he will be present in email list when message is created and "Send message by email" is checked i.e. will receive notification for the submitted message.

2. Send email to all users defined in "Contacts" when ticket is closed.

**Comment by freechelmi** [comment]
Please update your issue title . 

I can confirm the feature request.

**Comment by freechelmi** [comment]
I propose to mark this issue as duplcated of #16545 and sum up the default behaviour we want for tickets there
