### ISSUE TITLE
Inventory counting does not honour "value date" field

### ISSUE THREAD

**Issue by AshleyButcher** [Dolibarr/dolibarr#18894]
# Bug
When creating an inventory counting ("inventories"), Dolibarr does not honour the value date specified. This means:
1. The "expected quantity" is current on-hand, and not as of the value date
2. The posted movements as a result of generating movements and closing the inventory counting is booked on the current date

## Environment
- **Version**: 14.0.2
- **OS**: Debian 4.19
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.29-1
- **Database**: MySQL 8.0.23
- **URL(s)**: /product/inventory/list.php?leftmenu=stock_inventories

## Expected and actual behaviour
On the assumption that the "value date" represents the date inventory was closed and counted in a particular warehouse:

Expected:
 1. The "expected quantity" in the inventory counting screen ("inventories") is the quantity on hand as of the value date - if this causes confusion, a second column should be possible that shows current on-hand too, but the expected quantity should match that of the value date
 2. The posted movements are posted on the value date, even if this is in the past

Actual:
 1. The "expected quantity" column shows the current on-hand stock
 2. The posted movements are always posted at the time the "generate movements and close" button is clicked

## Steps to reproduce the behavior
 1. Generate stock movements for items on the current date
 2. Observe current and past stock levels using the "stocks at date" warehouse enquiry (/product/stock/stockatdate.php) using a date in the past (i.e. 30/9/2021)
 2. Create an inventory counting ("inventories"), specifying a value date in the past (same as previous step, i.e. 30/9/2021)
 3. Validate/open
 4. Observe that the "expected quantities" matches current quantities, not the stock levels of the value date 
 5. Adjust quantities in the "real quantities" column and save
 6. Click the "generate movements and close" button
 7. Observe current and past stock levels using the "stocks at date" warehouse enquiry (/product/stock/stockatdate.php) using a date in the past (same as before i.e. 30/9/2021) - note that stock levels in the past have not changed, but current stock levels have
 8. Observe warehouse stock movements (/product/stock/movement_list.php) to see the movements related to the inventory counting just generated are not on the value date, rather the date and time the movements were generated

**Comment by AshleyButcher** [comment]
Seems this got fixed at once point by something else, so no need to reopen this.

**Comment by biaucean** [comment]
I think I have the same problem :
I post that on the forum : 
Bonjour,
J’ai un souci avec le stock à date :
L’état des stocks à date incrémente à la "date de saisie" et non à la « date facturation » de la facture fournisseur indiquée au moment de la saisie.
Alors que dans le module statistique, les produits sont biens répartis à la « date facturation »

J’utilise cette fonction sur ma TPE de manière particulière. J’ai un cahier de fabrication manuel au jour le jour. Je regroupe la saisie des fabrications sous forme de facture fournisseur (le fournisseur étant la TPE elle même). Dans la facture fournisseur, la date facturation indiquée est celle de la fabrication
Sauf que lorsque je veux vérifier la validité de mon stock à une date donnée, le stock indiqué ne tient pas compte des saisies ultérieures à la date d’état des stocks.
Exemple :
J’ai saisi les fabrications du 4ième trimestre 2023 que j’ai daté en facturation, à la date de fabrication , saisie faite courant janvier 2024.
Si je fais un état des stocks à date au 31/12/2023, le chiffre indiqué ne tient pas compte de la saisie faite en 2024 concernant ces fabrications de 2023

J'ai migré sous la version 19 avec le même problème. Je suis en local sous macos 10.13. php 7.4.33  Mamp 6.8 mysql 5.7.39
