### ISSUE TITLE
Problème de taxe - commande fournisseur / tax problem - purchase order

### ISSUE THREAD

**Issue by GOLIPU** [Dolibarr/dolibarr#18898]
# Bug
[Lorsque nous faisons une modification sur une ligne d'une commande fournisseur, les taxes changes pour des % aléatoire. exemple : ajout d'un item à 1$ taxe 5% et 10% (2 taxes). Modification de quantité d'item à 2 items. Effet : taxe de 23% et 194%. ]

## Environment
- **Version**: [13.0.2]
- **OS**: [DEBIAN-UNBUNTU]
- **Web server**: [unknown]
- **PHP**: [*unknown*]
- **Database**: [*unkknown*]
- **URL(s)**: [unknown]

## Expected and actual behavior
[Il serait attendu que les taxes restent les mêmes malgré les changement de quantité, prix, description]

## Steps to reproduce the behavior
[Modification d'un paramètre d'un item dans une commande fournisseur]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[
![taxe_1](https://user-images.githubusercontent.com/91914669/135914137-95b91984-e3f4-45f0-aab6-10aec2b091bb.PNG)
![taxe_2](https://user-images.githubusercontent.com/91914669/135914134-bd02c66a-53d8-4919-a956-a21f48620848.PNG)
]

**Comment by ksar-ksar** [comment]
Hello,

Can you try at least to update to the latest v13?

**Comment by GOLIPU** [comment]
I tried all versions and the problem is the same.

Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
________________________________

**Comment by ksar-ksar** [comment]
Hi,

I can't reproduce.
Try to deactivate all your external modules.

**Comment by GOLIPU** [comment]
Can you try with two taxes setup? Here my configuration for information.

The problem does not appeared when only 1 tax is selected.

Also, it only happend with "commande fournisseur"

![multi taxe](https://user-images.githubusercontent.com/91914669/136011872-85885b2d-f4d3-4d90-92c1-8738a17235c4.PNG)
