### ISSUE TITLE
Extrafield transfert from fichinter to propal not working

### ISSUE THREAD

**Issue by Timoune974** [Dolibarr/dolibarr#18893]
# Bug
[*Extrafield transfert from fichinter to propal not working*]

## Environment
- **Version**: [*13.0.4*]
- **OS**: [*linux*]
- **Web server**: [*Apache 2.4*]
- **PHP**: [*7.4*]
- **Database**: [*mariadb*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
when you create a propal from a fichinter where you have extrafields, extrafields not transfered from fichinter to propal
I removed in htdocs/comm/propal/card.php the following line and it's working fine. I did some regression test and I didn't have any issue then I don't know why in the propral creation process the propal object is reset 
 line 1505 ==> $object = new Propal($db);

## Steps to reproduce the behavior
In fichinter module create an extrafield TOTO 
In propal create the same extrafield TOTO
create an inter and then create a propal from this intervention 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by homer8173** [comment]
Thanks for report
