### ISSUE TITLE
REST API : it's possible to create a product with an extrafield, without this extrafield in dolibarr

### ISSUE THREAD

**Issue by PyroShape** [Dolibarr/dolibarr#18896]
# Bug
There is no error message when you use the API to create a product with an extrafield, even if you have not created the extrafield before in the configuration of the module Product.
For example you can try this json, the product will be created even if the extrafield is not correct : 
{ "ref": "ref_test",  "label": "a product to test", "array_options": {"options_an_extra_field": "Hello"} }

## Environment
- **Version**: [14.0.3]
- **PHP**: [*7.1.9*]

**Comment by homer8173** [comment]
On all REST API, all the fields provided that not match a landing field are just avoided, so for the extrafields. That's not a bug
@eldy Close ?

**Comment by PyroShape** [comment]
That's not normal to have a success response if the request is not a success.

**Comment by homer8173** [comment]
I invite you to double test, your json created a product during my test
![image](https://user-images.githubusercontent.com/8720867/138563308-fc9dc6a8-7582-46d9-9ff0-45fbd76fd6f1.png)

**Comment by PyroShape** [comment]
Yes that's the problem : your POST request contain a field that doesn't exist and yet you have a success response on your request and your product is creates without all the field in the POST.

**Comment by atm-maxime** [comment]
Hi. I agree with @homer8173, your request is a success, the product is created. If you use fields that does not exists, it's simply ignored, and that's the wanted behaviour. Note that this is not linked to extrafields, if you add a "xxx" : "yyy" at the same level of ref or label, it's simply ignored too.
