### ISSUE TITLE
Refresh OpenSurvey / add new survey features

### ISSUE THREAD

**Issue by atm-florianm** [Dolibarr/dolibarr#18907]
The latest version of OpenSurvey is more recent than Dolibarr's. However, OpenSurvey seems to have been stagnant for a few years, so it would be a good idea to review Dolibarr's survey system.

**Comment by c-orazio** [comment]
under dolibarr 14.0.5 on ubuntu server the plus button to add a column when designing a  survey is not working..!
https://xxx.com/opensurvey/wizard/choix_date.php

**Comment by atm-maxime** [comment]
Still relevant
