### ISSUE TITLE
Submitting a line with missing values in bulk stock transfer causes existing values to disappear

### ISSUE THREAD

**Issue by AshleyButcher** [Dolibarr/dolibarr#18916]
# Bug
When creating a bulk stock transfer, if a field is missing (i.e. source warehouse) when submitting a line, then an error is returned and the existing lines on the bulk stock transfer are no longer shown.

## Environment
- **Version**: 14.0.2
- **OS**: Debian 4.19
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.29-1
- **Database**: MySQL 8.0.23
- **URL(s)**: /product/stock/massstockmove.php

## Expected and actual behavior
Expected: When submitting a bulk stock transfer line that has an error (i.e. missing required value), the previously selected lines should remain in place in spite of the error.

Actual: The lines disappear when an error is displayed.

## Steps to reproduce the behavior
1. Create a bulk stock transfer with one or more lines
2. Intentionally enter a stock transfer line with a missing value (i.e. missing source warehouse), click submit
3. Observe: Error is correctly shown, however lines previously entered have disappeared

**Comment by tiaris** [comment]
works for me in dolibarr 14.0.3

![image](https://user-images.githubusercontent.com/919513/138551095-a534a445-0ef8-476e-b47a-a1ca0144ebec.png)

**Comment by AshleyButcher** [comment]
Hi @tiaris, I don't see any lines in your screenshot, only the line that is being added, so it doesn't look like it's working following the reproduction steps, or you didn't follow first step of the reproduction steps.

To be clear - add one or more lines to the bulk transfer first beforehand (step 1 of the reproduction steps), then create an erroneous line. The lines you previously created will no longer be visible. If you reload the page, the already created lines reappear.

**Comment by atm-maxime** [comment]
@Ashley-Butcher I have reproduced. You're right, previous lines are not shown, but if you refresh the page, it's displayed again. I'll see for a fix.
