### ISSUE TITLE
Unable to delete recent Accounting lines (Ecriture comptable)

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#18913]
# Bug
After importing a FEC file, I am discovering that I cannot delete any accounting lines after clicking on delete even if I get a positive acknowledgement message in the "Grand Livre" list page. See screenshots.

## Environment
- **Version**: 14.0.3
- **OS**: Darwin MacBook-Pro-Pichi.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64 x86_64
- **Web server**: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.4.2 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2
- **PHP**: 7.4.2
- **Database**: MySQL
- **URL(s)**: http://dolibarr.pichinov.fr:8888/accountancy/bookkeeping/listbyaccount.php?&search_date_startmonth=10&search_date_startday=1&search_date_startyear=2015&search_date_endmonth=09&search_date_endday=30&search_date_endyear=2022

## Expected and actual behavior
Delete any line when selected in menu.

## Steps to reproduce the behavior
Display list of accounting lines and then select on delete in left botton of the screen

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="524" alt="Supprimer Ligne Compta sans effet 1 06 12-02-07" src="https://user-images.githubusercontent.com/57623859/136184104-e12505e1-1fae-49f5-88b4-3e697db89341.png">
<img width="613" alt="Supprimer Ligne Compta sans effet 2 06 12-02-07" src="https://user-images.githubusercontent.com/57623859/136184110-fe4a7e17-a6ad-4285-9497-e28e19fa3b90.png">

**Comment by aspangaro** [comment]
Hello @josett225 ,

It's not a bug, a validated line in ledger (grand livre) cannot be deleted. If you have imported a FEC, some lines may be already validated. This imported lines cannot be removed.

**Comment by josett225** [comment]
Hi @aspangaro 
Ok understood. However is there possible either to grey the suppress button and/or avoid the message that lines have been deleted or a clear message explaining that these lines cannot be deleted for the reason explained in your answer?

Many thanks for the previous answer.

**Comment by josett225** [comment]
It is still valid to display the right error message
