### ISSUE TITLE
Inventory stock at date (in the past) produces unexpected results - stock on date not included

### ISSUE THREAD

**Issue by AshleyButcher** [Dolibarr/dolibarr#18914]
# Bug
When reporting stock count at date, the "date in past" functionality does not include the stock movements performed on that date. For example, reporting for the end of a month/quarter (i.e. 30/9/2021) it is expected to see all movements up until the end of the date included, so you see the result as of the end of the month. Instead, stock levels exclude the date you select.

The issue is in htdocs/product/stock/stockatdate.php :
```
        if ($mode == 'future') {
                $sql .= " AND sm.datem <= '".$db->idate($dateendofday)."'";
        } else {
                $sql .= " AND sm.datem >= '".$db->idate($date)."'";
        }
```
should be:
```
        if ($mode == 'future') {
                $sql .= " AND sm.datem <= '".$db->idate($dateendofday)."'";
        } else {
                $sql .= " AND sm.datem >= '".$db->idate($dateendofdate)."'";
        }
```
## Environment
- **Version**: 14.0.2
- **OS**: Debian 4.19
- **Web server**: Apache/2.4.38
- **PHP**: 7.3.29-1
- **Database**: MySQL 8.0.23
- **URL(s)**: /product/stock/stockatdate.php

## Expected and actual behavior
Expected: Standard accounting practise, and common practise in other ERP systems (Dynamics AX, Sage, SAP, ...) would be that if you enter a reporting date, it includes the transactions/movements on that date. Requesting a stock level report as of a particular date should include all transactions up until the end of that date. Currently this only works in "future" mode, not in "past" mode.

Actual: The stock is only shown up until 00:00:00 (midnight), i.e. the morning of the date specified) so reporting on a particular period yields unexpected results as the movements on the reporting date are missing.

Note: In standard practise, if running such an enquiry to validate stock levels for reconciliation purposes, you do not want to specify a date that is in another period (i.e. the next accounting period) for clarity, especially in an audit scenario. Furthermore, since the wording is "stocks _on_ date" you expect all transactions on that date to be included.

## Steps to reproduce the behavior
1. Generate movements, i.e. end of period (for example, stock counting in "inventories" in preparation for end of month/quarter reporting)
2. Run stocks at date enquiry for that date, note that transactions from that date are missing
3. Run stocks at date enquiry for the following date, note that transactions for that date are included

**Comment by homer8173** [comment]
Thanks for report , your bugfix is submited
