### ISSUE TITLE
DB_ERROR_SYNTAX back to the ticket list

### ISSUE THREAD

**Issue by Felix40400** [Dolibarr/dolibarr#18921]
# Bug
error message when returning to the ticket list.

## Environment
- **Version**: 14.0.2
- **OS**:  Linux server 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: 7.3.30-1+ubuntu18
- **Database**: MySQL or MariaDB 5.7.35-0ubuntu0.18.04.2
- **URL(s)**: htdocs/ticket/list.php?restore_lastsearch_values=1

## Expected and actual behavior
By consulting a ticket, by clicking on "return to the list" Dolibarr displays the list of tickets

## Steps to reproduce the behavior
By consulting a ticket, by clicking on "return to the list" Dolibarr displays a syntax error

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
`Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20211007144603
Dolibarr: 14.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.3.30-1+ubuntu18.04.1+deb.sury.org+1
Server: Apache/2.4.29 (Ubuntu)
OS: Linux server 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

Url sollicitée: /htdocs/ticket/list.php?restore_lastsearch_values=1
Referer: http://******/htdocs/ticket/card.php?id=997&save_lastsearch_values=1
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, categorie, import, export, blockedlog, mailing, socialnetworks, statistiques, ecotaxdeee, accounting, agenda, banque, cron, commande, ecm, externalsite, facture, fournisseur, holiday, margin, printing, resource, salaries, service, societe, ticket, workflow, projet, takepos, contrat, externalrss, emailcollector, expedition, variants, ficheinter, paypal, incoterm, loan, notification, fckeditor, webservices, mycyberoffice, cyberoffice, supplier_proposal, tax, product, reception, paymentbybanktransfer, stock, prelevement, propal
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT t.rowid, t.entity, t.ref, t.track_id, t.fk_user_create, t.origin_email, t.subject, t.type_code, t.category_code, t.severity_code, t.timing, t.fk_soc, t.notify_tiers_at_create, t.fk_project, t.datec, t.date_read, t.fk_user_assign, t.date_close, t.tms, t.message, t.email_msgid, t.progress, t.resolution, t.fk_statut, t.import_key FROM llx_ticket as t LEFT JOIN llx_societe as s ON (t.fk_soc = s.rowid) WHERE t.entity IN (1) AND (subject LIKE '%yamaha%') AND (type_code LIKE '%SAV%' AND type_code LIKE '%ELEC%') AND () ORDER BY t.datec DESC LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY t.datec DESC LIMIT 26' at line 1`

**Comment by ksar-ksar** [comment]
Hello,

I do not experience the error on the latest V14 from GitHub

**Comment by Felix40400** [comment]
I @ksar-ksar  It seems to happen randomly. Maybe by adding filters.

**Comment by JoAnMaFe** [comment]
the problem appears when making a listing with the filter deactivated. (All of them are shown), you access one of them and from there you click Back to the list. From that moment on, the error is displayed.

This website or feature is currently temporarly not available or failed after a technical error.
This may be due to a maintenance operation. Current status of operation (2022-01-04T19:36:20Z) are on next line...
Dolibarr ha detectado un error técnico. Puede leer el archivo log o establecer la opción $dolibarr_main_prod a '0' en su archivo de configuración para obtener más información.
