### ISSUE TITLE
BUG When load a draft invoice from history I can't add products

### ISSUE THREAD

**Issue by javierybar** [Dolibarr/dolibarr#18935]
# Instructions
Only load history invoice unclosed and add products

# Bug
When load a draft invoice from history I can't add products

## Environment
All versions

**Comment by ksar-ksar** [comment]
Hello,

Work for me !
![image](https://user-images.githubusercontent.com/35605507/136911786-87cfd2aa-a13e-431d-a6d7-7feb091ab4b4.png)
![image](https://user-images.githubusercontent.com/35605507/136911872-bdc2adb1-c7a3-4495-9b5d-aea0a27c9623.png)
![image](https://user-images.githubusercontent.com/35605507/136911946-9e25dd5c-a5a0-4c44-b965-16589a14cd87.png)
