### ISSUE TITLE
LOT / SERIE filter module anomaly

### ISSUE THREAD

**Issue by RaVaHgNu** [Dolibarr/dolibarr#18932]
# Bug
Hello
I have a problem with the use,
when you click on the product page then stock / lot / series, the filters at the top of the page do not work
ditto for the stock page!
in summary the pages:
List, and batch / series -> the filter works
Stock and Stock / batch serie -> the filter does not work

version 14.0.2 hosted in shared, I tested the same locally too!
I have nothing on github (unless I'm mistaken of course).
thank you in advance for any leads or help
have a good day 

![pic2](https://user-images.githubusercontent.com/92171284/136585498-8b1ef6b8-56a8-482d-9901-187a93073d51.jpg)
![pic 1](https://user-images.githubusercontent.com/92171284/136585503-8e75cdc3-47a4-4a3a-b7b2-c656519032b8.jpg)

**Comment by homer8173** [comment]
even a search without param was not working, solved by handling the categorie correctly

**Comment by RaVaHgNu** [comment]
@eldy @homer8173 thank you so much
