### ISSUE TITLE
Google OAuth

### ISSUE THREAD

**Issue by j2bd** [Dolibarr/dolibarr#18948]
# Feature Request
*Configure Google OAuth to enable login via Google for Dolibarr via a quick configuration on GCP*

## Suggested implementation
A link below if it helps... 
https://docs.appsmith.com/v/v1.2/getting-started/setting-up/docker/google-login

**Comment by rootkit7628** [comment]
Hello, is there any news about this features ?  I want to implement a google authentification on dolibarr and I'm wondering if there is already a solution for that.
