### ISSUE TITLE
Dolibarr refuses to create a credit note for/from a vendor invoice

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#18952]
One of our vendors charged us too much on their invoice (which is not yet paid, and not overdue) and sent us a credit note. When trying to add this credit note, Dolibarr complains about "Module/Application not configured". It does not say which module, and we cannot find any setting anywhere that deals with this situation.

The error is reproducable everytime:

1. Open the original invoice.
2. Click "Create credit note"
3. Enter the values from the vendor
4. Click Validate
5. Dolibarr says "Module/Application not configured" and the invoice is not validated.

v12.0.5
![Untitled](https://user-images.githubusercontent.com/11036018/136912104-86f3211b-6010-41b5-aa24-e07032dbe807.png)

**Comment by atm-maxime** [comment]
You just haven't set the numbering mask for vendor credit note. Go to the vendor module setup, invoice tab, you'll see there's a setup missing.

**Comment by bos4711** [comment]
That worked. Thanks.

Then I would suggest a more informative error message, at the very least in which module the error is for, and perhaps a note of what setting is missing.
