### ISSUE TITLE
Supplier Invoice : field `paye`(paid) is not set when early payment discount

### ISSUE THREAD

**Issue by vincentjdc** [Dolibarr/dolibarr#18954]
# Bug
Sometimes, the supplier makes a discount if we pay within a certain amount of time. This is an early payment discount.
Dolibarr let the possibility to indicate that :

![Capture du 2021-10-12 12-37-20](https://user-images.githubusercontent.com/50613035/136941446-61eda7d6-5cb9-4f55-9ce6-5f524f8e612d.png)

The status of the invoice then is "Paid (partially)" but the field `paye` of the `llx_facture_fourn` table is not set to 1.

## Expected and actual behavior
I expect that the value of `paye` is 1 because no more payment is attended.

## Steps to reproduce the behavior
- Go to a supplier invoice
- Make a payment of the invoice with an amount less than the invoice total so that there is a remaining balance
- Set the invoice as "partially paid" and indicate that is an early payment discount
- Check the value of the field `paye` in the `llx_facture_fourn` table.

**Comment by atm-maxime** [comment]
Hi. Thanks for reporting.
My guess is that this is the wanted behaviour. If you want to know if an invoice is not awaiting anymore payment, you should use the fk_statut column (=2). Paye = 1 means that the invoice has actually been paid. If paye = 0, then it means that it has been paid partially, or not at all. This is the same behaviour on the customer side.

**Comment by vincentjdc** [comment]
Hi.

Okay, I know use the `fk_statut`
Thanks for your reply.
