### ISSUE TITLE
REST API Explorer not working with Dolibarr 13.0.4 (error: `failed to parse JSON/YAML response`)

### ISSUE THREAD

**Issue by LesCarnets** [Dolibarr/dolibarr#18969]
Hello,

I am facing issue with the REST API Explorer

# Bug
When I go to API Explorer I cannot do anything, there is following error message (even before I put my DOLAPIKEY):
`failed to parse JSON/YAML response`

## Environment
- **Version**: 13.0.4
- **OS**: Linux webdb46.lwspanel.com 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64
- **Web server**: Lunix shared hosting
- **PHP**: 7.0.33. I am still able to reproduce after upgrade to PHP 7.4
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /api/index.php/explorer/

# Workarround
Downgrade to Dolibarr 13.0.3

**Comment by ksar-ksar** [comment]
Hello,

Can you try to upgrade to v13.0.5?

**Comment by LesCarnets** [comment]
Hi @ksar-ksar,

Actually, I am not able to reproduce with version 13.0.3 and version 13.0.5 (only version 13.0.4 have this behaviour).

Thanks and best regards,

**Comment by ksar-ksar** [comment]
Ok, then it's OK if it is working in V13.0.5
