### ISSUE TITLE
Bug about delivery document (receipt) from expedition Dolibarr 14.0.2

### ISSUE THREAD

**Issue by fdabere** [Dolibarr/dolibarr#18962]
# Bug
When you click on generate delivery document button (bon de livraison) from expedition module doesn't work, abnormal behavior.

## Environment
- **Version**: Dolibarr 14.0.2
- **OS**: All OS
- **Web server**: Doliwamp 14.0.2 package
- **PHP**: PHP 7.3.12
- **Database**: MySQL 5.0.45
- **URL(s)**: http://localhost:8888/dolibarr/expedition/card.php?id=15&action=create_delivery

## Expected and actual behavior
should create a record in llx_livraison table but no record inserted, i have seen migrating llx_livraison to llx_delivery table but not finished development apparently...

## Steps to reproduce the behavior
Click on button generate receipt from shipping invoice page.

**Comment by tiaris** [comment]
works for me (dolibarr v 14.0.3) see  #18934

**Comment by atm-maxime** [comment]
Take a look in llx_delivery, it has replaced the livraison table since v13.
the "livraison" tables should be removed in a near future.
