### ISSUE TITLE
Fehler bei Übernahme Positionen Lieferantenrechnung

### ISSUE THREAD

**Issue by RalfWillkommen** [Dolibarr/dolibarr#18979]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Fehler bei Übernahme Positionen in Lieferantenrechnung

## Environment
- **Version**: 12.0.5

## Expected and actual behavior
Es werden auch nicht markierte Positionen übernommen.

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[Screenshots Bug Lieferantenrechnung.pdf](https://github.com/Dolibarr/dolibarr/files/7346394/Screenshots.Bug.Lieferantenrechnung.pdf)

**Comment by ksar-ksar** [comment]
Hello,

In English please?

**Comment by BlackyPurpHair** [comment]
it says error in takeover from position to Supplier invoice

in the screenshots he marked 2 Products and all products, so also products that aren't marked are being taken over to the supplier invoice
