### ISSUE TITLE
ZipStream Archive class not found

### ISSUE THREAD

**Issue by Stormrice** [Dolibarr/dolibarr#18981]
# Bug
Cannot export document to Excel 2007.

phpoffice/phpspreadsheet try to "include" maennchen/zipstream-php but an "not found error" appears.

The file "htdocs/includes/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/**Xlsx.php**" try to *use* the class "htdocs/includes/maennchen/zipstream-php/src/Option/**Archive.php**" as follows:

```
use ZipStream\Exception\OverflowException;
use ZipStream\Option\Archive;
use ZipStream\ZipStream;
```

But this error is thrown:
```
2021/10/14 16:43:35 [error] 10683#10683: *285042 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'ZipStream\Option\Archive' not found in /.../dolibarr/htdocs/includes/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php:506
Stack trace:
#0 /.../dolibarr/htdocs/core/modules/export/export_excel2007.modules.php(384): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save('/...')
#1 /.../dolibarr/htdocs/exports/class/export.class.php(696): ExportExcel2007->close_file()
#2 /.../dolibarr/htdocs/exports/export.php(279): Export->build_file(Object(User), 'excel2007', 'fournisseur_1', Array, '')
#3 {main}
  thrown in /.../dolibarr/htdocs/includes/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php on line 506" while reading response header from upstream, client: ..., server: ....com, request: "POST /dolibarr/htdocs/exports/export.php?step=5&datatoexport=fournisseur_1 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "....com", referrer: "https://.../htdocs/exports/export.php?step=5&datatoexport=fournisseur_1"
```
ZipStream is installed via composer and all files have u=rw,g=r,o=r permissions.

## Environment
- **Version**: 14.0.0
- **OS**: Ubuntu 16.04.7 LTS
- **Web server**: nginx/1.10.3
- **PHP**: php7.2-fpm
- **Database**: mysql Ver 14.14 Distrib 5.7.33, for Linux (x86_64) using  EditLine wrapper
- **URL(s)**: /dolibarr/htdocs/exports/export.php?step=5&datatoexport=fournisseur_1 HTTP/2.0

## Expected and actual behavior
Expected: The document is exported to Excel 2007.
Actual: Error 500.

**Comment by ksar-ksar** [comment]
Hello,

It is working for me in V14.0.2, can you try to update ?

**Comment by Stormrice** [comment]
Hi ksar-ksar,

Sadly, we can't upgrade to 14.0.2 for now, is there any workaround ?

Thanks :)
