### ISSUE TITLE
[NEW] add hiden option "pdf-A-1b" in setting pdf

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#18990]
# Instructions
Hiden PDF_USE_1A

# Feature Request
Add in page setting

Thank to @frederic34

**Comment by lmag** [comment]
Information about PDF A
https://tcpdf.org/examples/example_065/

**Comment by eldy** [comment]
I renamed var into PDF_USE_A so you can set value 1 or 3 for PDF/A-1 or PDF/A-3
