### ISSUE TITLE
[NEW] Add Tag on task

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#18992]
# Instructions
Add Tag on task

# Feature Request
Add tag on task as project and ticket
@FHenry next time

**Comment by lmag** [comment]
@evarisk-theo @nicolas-eoxia

**Comment by atm-maxime** [comment]
Imho, the tag system should be rewritten to have only one table to store all relations between an element and a tag. This way adding a tag on any element or custom objects would become very easy ! Let's talk about it next week 😉

**Comment by atm-maxime** [comment]
#18996

**Comment by lmag** [comment]
Yes good idea !

**Comment by edupulpillo** [comment]
Great approach

**Comment by JoAnMaFe** [comment]
In any case, adding a label to the tasks would be very useful, especially for their independent classification of the projects.
