### ISSUE TITLE
Rewrite category/tag module

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#18996]
# Feature Request
Rewrite the category/tag module to make it easier to use and allow any element to be tagged

## Use case
Currently each element/tag association is stored in a dedicated table. Which means that when we want to use rag on a new element (see recent KM module), we must create and use a new table. Having a single table to store this will make it easier to expand the tag system on any element (ECM, tasks, proposals, ...)

## Suggested steps
- [x] Create a table "element_tag" (rowid, fk_category, fk_element)
- [ ] Migrate data from the old tables (societe_category, contact_category, ...) to the new table
- [ ] Rewrite the category class to use the new table
- [ ] Move the tag management menu to the "Tools" main menu to manage all tags from there instead of in all menu
- [ ] Add a module_part "tags" to define if a module uses the tag system

## To go further
Ideas to discuss to improve the tag module :
- Allow to create a tag while creating/editing an object
- ...

**Comment by lmag** [comment]
@evarisk-theo @nicolas-eoxia

**Comment by evarisk-theo** [comment]
I think we should add a element_type column to this table to make this table generic and usable for all objects

**Comment by edupulpillo** [comment]
Great approach

**Comment by JoAnMaFe** [comment]
Certainly, this new approach could simplify the use of categories, but it could result in a very large "single table".

**Comment by atm-maxime** [comment]
> I think we should add a element_type column to this table to make this table generic and usable for all objects

I think this is not necessary because this information is already in llx_categorie with the column type which correspond to the element. But maybe improve this to store element (ie : "societe") instead of a numeric type.

**Comment by FHenry** [comment]
@atm-maxime Did you notice that llx_element_tag was created in install/mysql/migration/3.2.0-3.3.0.sql ? It's only in this migration file.... Should it be remove/rename it in install/mysql/migration/15.0.0-16.0.0.sql before CREATE TABLE llx_element_tag for people that come from 3.2 (few cases sure, but can exists). Did you target to finish Task on this issue for 16.0 ? or later ?

**Comment by lmag** [comment]
@atm-maxime are you interested in working on it : Rewrite the category class to use the new table ?

**Comment by atm-maxime** [comment]
> @atm-maxime are you interested in working on it : Rewrite the category class to use the new table ?

@lmag Interested? Always, that's why I started it 😉. But for now I don't have time to continue the task. Maybe in Nantes :)

> @atm-maxime Did you notice that llx_element_tag was created in install/mysql/migration/3.2.0-3.3.0.sql ? It's only in this migration file.... Should it be remove/rename it in install/mysql/migration/15.0.0-16.0.0.sql before CREATE TABLE llx_element_tag for people that come from 3.2 (few cases sure, but can exists). Did you target to finish Task on this issue for 16.0 ? or later ?

@FHenry I'll check this out. Strange that the table existed before...

**Comment by FHenry** [comment]
> @FHenry I'll check this out. Strange that the table existed before...

Probably time when Regis try to do rolling release.

**Comment by lmag** [comment]
Add drop table llx_element_tag and recreate in 15.0.2 @atm-maxime #20649

**Comment by lmag** [comment]
We need TAG for invoice we propose todo :

- [ ] Add table : llx_categorie_invoice
- [ ] Add link for invoice
- [ ] Add link for Reccuring Invoice
- [ ] Add script for invoice from reccurring invoice to invoice

Before the migration of TAG
Is it ok for you @eldy @atm-maxime

**Comment by JoAnMaFe** [comment]
V17.0.0 "Nested" Tags / Categories do not work correctly in Products and Projects. #24188

**Comment by frederic34** [comment]
I found llx_element_tag used in an external module...

**Comment by FHenry** [comment]
@frederic34 it was an attemp during a devcamp to create the base table, but it never follow the developpement.
But it's only use by external module, it should be remove or use in the core.
After say that, it's gentle, but I didn't take time myself to work on it...

**Comment by JoAnMaFe** [comment]
V17.00 and V17.01 "Nested" tags/categories do not work correctly in products and projects. #24707

**Comment by EchoLoGeek** [comment]
I just started using categories for a custom object via the "constructCategory" hook.
What about a hook in viewcat.php in order to show a custom code (ex: list) for custom object ?

**Comment by atm-maxime** [comment]
Seems that the work is pending #25269

**Comment by lmag** [comment]
- [ ] Add an order to TAG for each branch

**Comment by inesaudinot** [comment]
Exemple de tri à faire dans les tags

![image](https://github.com/Dolibarr/dolibarr/assets/152158632/ac9d6f54-2830-4234-bf08-fde87917bfcc)

**Comment by edupulpillo** [comment]
is  really finished this work ?
Is really a great thing to unify the tags for all the objects.
