### ISSUE TITLE
Invoice mask

### ISSUE THREAD

**Issue by xbloq** [Dolibarr/dolibarr#18994]
I don’t know if it’s a mistake in dolibar or my mistake

I have diferent mask for standard, replacement ... invoices

{yy}{00000+41202}
{yy}{00000+11200}
{yy}{00000+21201}
{yy}{00000+31201}

But all invoices models get the same standard invoice mask

Dolibarr Version 13.0.4 / Version 14.0.2
Fedora 34
Apache

**Comment by atm-maxime** [comment]
Hi. Your masks are all identical, the only change is the added number at the end. So all your invoice type will have the same numbering, it's normal. Try adding a letter at the beginning of your masks, you'll see the difference

**Comment by xbloq** [comment]
It's OK. Sorry.
