### ISSUE TITLE
Contract / Style for the new line part seems messed up

### ISSUE THREAD

**Issue by DrMcMarco** [Dolibarr/dolibarr#19009]
# Bug
When adding a new line to a contract, the style for the new line part seems messed up

## Environment
- **Version**: 14.0.2
- **OS**: Ubuntu 20.04.1
- **Web server**: Apache 2.4.41
- **PHP**: 7.1.33
- **Database**: MariaDB 5.5.5-10.3.31
- **URL(s)**: /contrat/card.php

## Expected and actual behavior
Expected: Labels floating left, inputs floating right
Actual: Labels floating left, inputs directly next to them

## Steps to reproduce the behavior
1. Add new line to any contract

Tried clearing cache, Ctrl+F5, using other browsers, etc... No difference.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*
### Before (v12.0.4)
![Before (v12.0.4)](https://user-images.githubusercontent.com/9693248/137736903-0dd6c93f-7ba9-4429-a8db-9e0c4a75ff70.PNG)
### After (v14.0.2)
![After 14.0.2](https://user-images.githubusercontent.com/9693248/137736925-574e6a52-7ec2-453a-a22b-fde36ebebd18.PNG)
]

**Comment by atm-maxime** [comment]
Comes from #15805
@eldy, should we revert the code ?

**Comment by atm-maxime** [comment]
@FHenry can you check the display of line extrafields ?

**Comment by eldy** [comment]
@FHenry Can you add tags
```
<dl>
<dt>Title of extrafiels</dt>
<dd>Value</dd>
<dt>Title of extrafiels 2</dt>
<dd>Value 2</dd>
</dl>
```

So we will be able to restore alignement using CSS.

**Comment by FHenry** [comment]
I'll check

**Comment by FHenry** [comment]
@eldy  What do you mean by tags ? you mean a class in HTML ?
