### ISSUE TITLE
Warehouse list for shipments

### ISSUE THREAD

**Issue by fgarciapatino** [Dolibarr/dolibarr#19018]
# Bug
All warehouses listed when creating new expeditions from shipping tab at order

## Environment
- **Version**: 14.0.2
- **OS**:  Linux 3.10.0-1160.31.1.el7.x86_64 Develop #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64
- **Web server**: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
- **PHP**:  7.4.21
- **Database**: 5.5.5-10.2.39-MariaDB
- **URL(s)**: /expedition/card.php?action=create&shipping_method_id=&origin=commande&origin_id=XXXX
## Expected and actual behavior
Expected: list only products at selected warehose
Actual: All warehouses are listed

## Steps to reproduce the behavior
Go to /expedition/shipment.php?id=XXX
Select a warehouse
Press "Create"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Select_WH](https://user-images.githubusercontent.com/4846366/138403806-907e8ada-3d51-4cac-a81f-765af32cd612.png)
![Choose_WH](https://user-images.githubusercontent.com/4846366/138403840-4eef34e4-1d40-4b80-b0f8-53b421b95d65.png)

**Comment by tiaris** [comment]
works for me in v 14.0.3, only warehousses with product stock are shown, to choose, one or more warehouses

![image](https://user-images.githubusercontent.com/919513/138550717-a05201d9-82de-4c9d-abde-55149645e324.png)

product is not in Entrepot 1
![image](https://user-images.githubusercontent.com/919513/138550759-a98dc140-35f8-4f36-8c60-5a8fb622626d.png)

**Comment by atm-maxime** [comment]
I just checked with a 14.0.3 and I can't reproduce. The only serial numbers shown after selecting a warehouse are the ones in this warehouse. And all appears when no warehouse is selected

**Comment by fgarciapatino** [comment]
I believe you. I promise.  Same as on the screens I've sent.

That's exactly what I get: sometimes works, sometimes not... My problem is
to be able to explain why.

Did you test with 14.0.2?. Do you think "my" issue will be solved with the
upgrade because it is a known issue I have'nt found documented for previous
versions?. If so, I would not mind to upgrade, but I'm expeciencing some
troubles since my last upgrade from 13.0.2 that I would wish to explain
before.

¿Which factors from your knowledge of the source code you think could be
involved with this behaviour?

I've test it in four different environments: the three of my project
development infrastructure, and an clean extra one to be aware of malefical
influences.

**Comment by AshleyButcher** [comment]
We have the same issue, but also cannot determine when/why this happens. We see this behaviour in 14.0.2, but haven't yet reported it as I only want to report things with reliable reproduction steps. We are planning to move to 14.0.3 before the end of this month.

In our scenario, often making a shipment with a specific warehouse selected, the following screen for the quantities has the quantities spread over all warehouses instead of the warehouse selected.

If this continues in 14.0.3, and my colleague or I can find reliable reproduction steps, I will return with more information. I just wanted to say we've seen it too :)

**Comment by fgarciapatino** [comment]
Hello.

I found something wrong in file /expedition/shipment.php at line 901, with
the action button but I don't think it's the source of the problem.

print '<input type="submit" class="butAction" named="save"
value="'.$langs->trans("CreateShipment").'">';

"named" is not a standard html attribute for input element. Meant name?

As my colleague said, I will investigate the code, and I've tell the users
to pey attention to find a relationship with the behaviour and whichever
product, warehouse, and order attribute combinatios they use that can
identify the source of the issue.
