### ISSUE TITLE
Serial number stock management on invoice

### ISSUE THREAD

**Issue by BlackyPurpHair** [Dolibarr/dolibarr#19010]
Both Modules are activated. Stock/Warehouse module is actived and charge from serials. 
i create a product in the Product module,in said module, i choose that serial numbers are actived.I then order said prodcut from my distributor. The incoming goods are booked with serial numbers, stock increases as it should. Now if i write an invoice to my costumer and take said Product from my stock and put it in the invoice, it is in the invoice but it won't ask for a serial number and the stock will not be counted down.

## Environment
- **Version**: [14.0.2]
- **OS**: [Debian 10 Server]
- **Web server**: [*Apache 2.4*]
- **PHP**: [*7.3*]
- **Database**: [*MariaDB*]
- 
## Expected and actual behavior
[it should count the stock up with my Serial number, then i create a invoice, i add the product, it will ask me for which serial number to choose and i will enter it and the stock will count down.
it counts the stock up, then i create a invoice, i add the Product and it just adds the product to the Invoice, without serial number.]

## Steps to reproduce the behavior
[Create new Product, activate Serial number for said product, Create invoice, add Product to invoice]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/7365158/dolibarr.log)
]

**Comment by BlackyPurpHair** [comment]
We have found the error. It was on understanding, that the system will only count the Stock down, if there is a delivery Note creation with the Invoice. We usually only do invoices. Is there any way to set some settings, so that the system will also count down without creating a Delivery Note?

**Comment by atm-maxime** [comment]
Currently serial numbers can only be selected and counted down with a shipment. What you need is this feature to be added on the invoice or order. This is not a bug and it's not just a simple task... You might want to contact a developer to ask about the cost of having this feature developed.

**Comment by atm-maxime** [comment]
Please rename your issue as "Serial number stock management on invoice"

**Comment by BlackyPurpHair** [comment]
Thank you very much for your very detailed answer abt this „problem“ instead of leaving this open as a feature request, I’d like to close this.
