### ISSUE TITLE
Order filters not working properly

### ISSUE THREAD

**Issue by fgarciapatino** [Dolibarr/dolibarr#19017]
# Bug
Order filters not working properly 

## Environment
- **Version**:14.0.2
- **OS**: Linux 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64
- **Web server**: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
- **PHP**: 7.4.21
- **Database**: 5.5.5-10.2.39-MariaDB
- **URL(s)**: /commande/list.php

## Expected and actual behavior
Expected: list filtered
Actual behaviour: Empty result

## Steps to reproduce the behavior
Type an existing order reference and press "enter". The result is always empty altough the order reference exists

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by IC-Ilies** [comment]
Hello,

After many tests, i can't reproduce this issue

**Comment by atm-florianm** [comment]
@fgarciapatino Can you reproduce your issue regardless of external modules (i.e. reproduce with all external modules disabled)?

I couldn't reproduce it on my default v14 install.

If you can reproduce it consistently, I am wondering if it could be caused by a third party module.

**Comment by tiaris** [comment]
works for me with dolibarr 14.0.3

**Comment by fgarciapatino** [comment]
Thank you.

Did you check the issue with 14.0.2? I have 5 issues opened for two weeks
since last update from 13.0.2 to 14.0.2, and I am a bit aware of 14.0.3
because the change log says nothing about muy troubles.

As I understand I have no external modules triggering or hooking neither
order nor  expedition state changes.

**Comment by atm-florianm** [comment]
I have just tried the same with Dolibarr 14.0.2 and 14.0.1, with no problems filtering the customer order list with a specific ref.

Do your order refs follow any unusual pattern (like a custom mask)?

And just to be sure: are we talking about customer orders, not supplier orders? [edit] I just checked them too in 14.0.1 and didn't have any issue filtering the list.

**Comment by fgarciapatino** [comment]
Ok.

I've deployed a clean installation with 14.0.2 in my development
environment, and I think I've identified the problem. It happens when I
select fk_typent in the list of columns to display in the orders list

Thank you in advance.

**Comment by fgarciapatino** [comment]
Just for including the field, without needing to set a value

**Comment by atm-maxime** [comment]
Can you give us a screenshot ? I tried adding the typent column in my order list and all filters are working fine...

**Comment by fgarciapatino** [comment]
Here are the requested screenshots:

![default](https://user-images.githubusercontent.com/4846366/138585102-759d3c06-e1f2-4620-bd25-95c6dbc4dfbc.png)
![Filter1](https://user-images.githubusercontent.com/4846366/138585104-f01a1698-96db-407d-95e3-8178d3761f61.png)
![Filter2](https://user-images.githubusercontent.com/4846366/138585105-a64405f6-472c-4bf3-b5ea-0b7aa7bab980.png)
![Filter4](https://user-images.githubusercontent.com/4846366/138585106-dbddbd66-99a5-4831-ae34-bc876dd949e2.png)
![Filter5](https://user-images.githubusercontent.com/4846366/138585107-21e45594-3925-4bd1-9c1a-8007882cafb5.png)
s:

**Comment by atm-maxime** [comment]
HI. I just did the same on a 14.0.3 from the 14 branch of github :

1. Filter withoud typent column works
![image](https://user-images.githubusercontent.com/2097773/138598711-8decdaa1-bce6-4e7e-9774-9dd32a0504a7.png)

2. Add the column typent
![image](https://user-images.githubusercontent.com/2097773/138598731-84b3c8a4-a6e6-4bd8-8122-0271b966afeb.png)

3. Filter again
![image](https://user-images.githubusercontent.com/2097773/138598743-eb229ee4-08b8-4b40-8f6b-c14a03fd2b54.png)

So my guess is that this comes from your instance / environment. Try checking the SQL request generated on the order list to see why there are no results.

**Comment by fgarciapatino** [comment]
Hello.

I check the sql before and after the hooks and both are identical (there are no hooks, but...). You can see the "s.fk_typent IN (-1)" causing the problem:

SELECT s.rowid as socid, s.nom as name, s.name_alias as alias, s.email, s.phone, s.fax, s.address, s.town, s.zip, s.fk_pays, s.client, s.code_client, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, country.code as country_code, c.rowid, c.ref, c.total_ht, c.total_tva, c.total_ttc, c.ref_client, c.fk_user_author, c.fk_multicurrency, c.multicurrency_code, c.multicurrency_tx, c.multicurrency_total_ht, c.multicurrency_total_tva as multicurrency_total_vat, c.multicurrency_total_ttc, c.date_valid, c.date_commande, c.note_public, c.note_private, c.date_livraison as date_delivery, c.fk_statut, c.facture as billed, c.date_creation as date_creation, c.tms as date_update, c.date_cloture as date_cloture, p.rowid as project_id, p.ref as project_ref, p.title as project_label, u.login, u.lastname, u.firstname, u.email, u.statut, u.entity, u.photo, u.office_phone, u.office_fax, u.user_mobile, u.job, u.gender, c.fk_cond_reglement,c.fk_mode_reglement,c.fk_shipping_method, c.fk_input_reason, ef.serie as options_serie, ef.phone as options_phone, ef.expdate as options_expdate FROM llx_societe as s LEFT JOIN llx_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN llx_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN llx_c_departements as state on (state.rowid = s.fk_departement), llx_commande as c LEFT JOIN llx_commande_extrafields as ef on (c.rowid = ef.fk_object) LEFT JOIN llx_projet as p ON p.rowid = c.fk_projet LEFT JOIN llx_user as u ON c.fk_user_author = u.rowid WHERE c.fk_soc = s.rowid AND c.entity IN (1) AND (c.ref LIKE '%PE/U21%') AND s.fk_typent IN (-1) ORDER BY c.ref DESC

**Comment by fgarciapatino** [comment]
in /commande/list.php I found:

at line 80 
$search_country = GETPOST("search_country", 'int');

That returns -1 when the filter is empty as the default value set for thirdparty select2 "<option class="optiongrey" value="-1" data-select2-id="43">&nbsp;</option>".

at line 548, you can see:
if ($search_type_thirdparty) {

and if I write "print $search_type_thirdparty" at 549 inside the if statement it prints -1, so it is being executed considering -1=true

if I change the line 548 to:
if ($search_type_thirdparty != '' && $search_type_thirdparty > 0) {

It works properly. 
Why "-1" could be considered as "true"?

**Comment by atm-florianm** [comment]
@fgarciapatino `(bool) -1` evals to true, this is normal PHP behavior.

As to the lines you describe, they have already been fixed in September, cf. commit fc56b88a1f7c5cbd6d3f0fcdcd9f8508c3b8c05d. Updating to the current stable version (14.0.3) will solve this and other problems.

**Comment by fgarciapatino** [comment]
That's true.

Thank you very much.
