### ISSUE TITLE
Modulebuilder object update

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#19014]
# Bug
Some fields are not submitted when editing object properties inside modulebuilder

## Environment
- **Version**: 14.0.1
- **OS**: Windows
- **Web server**: Apache/2.4.41 (Win64)
- **PHP**: 7.3.12
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB

## Expected and actual behavior
When updating object properties row, unchanged fields should keep their value. In fact, if you for example edit row "ref" and set "Kew for tooltip", the value for "Default value (PROV)" disappears and cannot be set again.

The same happens for "Foreign key" if you edit "fk_user_creat", and you are not able to set "fk_user_creat" neither for "fk_user_creat" or "fk_soc" for example.

I guess some of the fields have missing GETPOST and their values are not submitted on change/update.

## Steps to reproduce the behavior
- create new module via module builder
- create object for module
- edit "ref" row OR try to set "societe:rowid" as "foreign key" of "fk_soc"

**Comment by atm-florianm** [comment]
I do reproduce the issue in my v14 (14.0.3) install. It does seem that the HTTP parameter `propdefault` is never used in the `if` handling action `addproperty`. I’ll try to fix it.
