### ISSUE TITLE
Bug adding local tax payments

### ISSUE THREAD

**Issue by xabitrigo** [Dolibarr/dolibarr#19021]
# Bug

Latest change on compta/localtax/card.php prevented me from adding tax payments. 

**WORKAROUND**: Reverting that file to v13.0.1 seems to fix the problem.

## Environment
- **Version**: 14.0.2
- **OS**: Ubuntu 16.04
- **Web server**: Apache/2.4.46 (Ubuntu)
- **PHP**: 8.0.2
- **Database**: mysql  Ver 5.7.33-0ubuntu0.16.04.1
- **URL(s)**: 
  - /compta/localtax/card.php?action=create&localTaxType=2
  - /compta/localtax/card.php

## Expected and actual behavior
Trying to create a payment for a custom local tax (Spanish IRPF) didn't work. The page appeared blank. The devtools network tab showed what seemed a correct POST request to the card.php file so I figured some change there could cause the problem.

I just tested an old copy of that file from dolibarr 13.0.1 and it worked again.

## Steps to reproduce the behavior
Just try to add a payment for a custom local tax. After that I just see the menu with a blank content.

**Comment by vabeltran** [comment]
Confirmed same issue reproduced under identical conditions.
