### ISSUE TITLE
Salaries forecast in the bank account

### ISSUE THREAD

**Issue by wforte88** [Dolibarr/dolibarr#19026]
# Feature Request
Salaries forecast in planned entries

## Use case
When i create a salary entry in Billing > Salaries, i link it to a bank account. If the salary is paid, the entry is displayed in transactions of the bank’s module. But, if the salary has not been paid (only planned), it does not appear in the planned entries of the bank account.

## Suggested implementation
Like vendor/customer invoices, unpaid salaries could be displayed in Bank Account > Planned Entries. The payment of salaries is a debit to the account, so it must be planned and foreseen, alike vendor/customer invoices.

## Suggested steps (end user view)
1. Access Billing/Payment > Salaries > New;
2. Set a salary payment forecast date;
3. Save the entry without "Automatically record the payment";
4. Access Bank/Cash and open the same account informed in the salary payment entry;
5. Click on "Planned entry" tab. The entry planned will be displayed in table with the date informed to payment, with impact on the projected balance;
6. When the salary is paid, it will be displayed in the "Bank entries" tab (current behavior).

**Comment by ksar-ksar** [comment]
Hello,

May be fixed by #19037 ?

**Comment by wforte88** [comment]
> Hello,
> 
> May be fixed by #19037 ?

Hi, @ksar-ksar 

Your PR resolves the problem of the salaries in Accountancy (resultat/clientfourn.php ). I'll merge your code with my local Dolibarr. I hadn't seen that the accounts don't show salaries. Thanks for you comment.

But, my issue is about the planned entries (compta/bank/treso.php), for analysis of the future balance per account. Would you help me with this?

**Comment by xbloq** [comment]
I made the changes in clientfourn. I work with module accountacy (not simplified)
My problen is that salary not appear in  Project-Overview like before V14. Now show "List of payment of salaries related to the project" and only appear if it's paid. It's possible view a list of salaries (paid and not paid) in project-overview

**Comment by wforte88** [comment]
> I made the changes in clientfourn. I work with module accountacy (not simplified) My problen is that salary not appear in Project-Overview like before V14. Now show "List of payment of salaries related to the project" and only appear if it's paid. It's possible view a list of salaries (paid and not paid) in project-overview

Yes, @xbloq. I think that the integration of salaries forecast with other modules are an epic, with some tasks, one for each integration/functionality. Only here, we listed three:
- Accountancy
- Bank Account
- Project Overview

I don't know how admins manage this cases. Should we open one issue to each suggestion? Are there some taxonomy to group them?
