### ISSUE TITLE
Automatic round when adding a product (Ajax)

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#19022]
# Bug
When adding products to an order, sometimes prices are truncate randomlly to 2 number after the dot wich cause an issue when calculating price with hi quantities

## Environment
- **Version**: 13.0.3
- **OS**: Debian
- **Web server**: Apache2
- **PHP**: PHP 7.3.29-1~deb10u1
- **Database**: Postgres 11
- **URL(s)**: https://XXXXX/commande/card.php?id=203#addline

## Expected and actual behavior
When the products have prices with 5 digits after the dot it happen that Dolibarr automatically convert the HT prices to the rounded 2. 
It's not always the case, it happen one time on ten cases.. really wierd.

## Steps to reproduce the behavior
Add a product with a price for example "46,22642" 
Add this product to an order

## [Attached files]
![Commande](https://user-images.githubusercontent.com/26635105/137984826-9dcc09a1-ae45-4e65-8757-13d525ddc04a.png)

![Cursor_et_Produit_SPECULOOS_SAINT_____-_Prix_de_vente](https://user-images.githubusercontent.com/26635105/137985114-9e93d1e2-7170-4e13-832e-7fd1ad1c52bf.png)

**Comment by atm-maxime** [comment]
Hi, I can't reproduce on a 13.0.5
Are you sure an admin didn't change the setup of "Limits and accuracy" between two added lines ? Can you reproduce ?

**Comment by daxitsolutions** [comment]
Case closed, it looks like the price changed on the table behind the scene - now everything is good.
