### ISSUE TITLE
Bug: Warning: php_uname() has been disabled for security reasons in /home/soinesvi/public_html/spr/main.inc.php on line 2270

### ISSUE THREAD

**Issue by abravo23** [Dolibarr/dolibarr#19020]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 12.0.1
- **OS**: 
- **Web server**: Apache
- **PHP**: litespeed 7.4.20
- **Database**: MySQL or MariaDB 5.7.33-log-cll-lve
- **URL(s)**: /spr/index.php?mainmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

This is not a Dolibarr bug, you need to contact your hosting company to allow this functionality

https://yoast.com/help/loadclass-disabled-for-security-reasons/
