### ISSUE TITLE
security setting: file permission

### ISSUE THREAD

**Issue by Alexis-M51** [Dolibarr/dolibarr#19032]
Hello
I have a question, for the security setting it asks to change restriction permissions for source files.
But when I make restrictions it makes the site bug.

Can we have a list of files to modify?

**Comment by ksar-ksar** [comment]
Hello,

What are you doing exactly ?

the chmod should be 755

**Comment by Alexis-M51** [comment]
Bon vu que tu es français, je voulais savoir pourquoi les développeurs nous demandent de modifier les fichiers en lecture seule, alors que si on fait cela le système ne fonctionne plus. Et aussi s'il existe une liste de fichiers à modifier qui n'endommagerait pas le système.

**Comment by ksar-ksar** [comment]
Je ne comprends pas où l'on dit qu'il faut mettre les fichiers en lecture seul ?
Il ne faut pas être en lecture seul, sinon Dolibarr ne peut pas fonctionner.

**Comment by Alexis-M51** [comment]
Dans outils d'administration, puis infos sécurité et dans la section "Permissions sur les fichiers du répertoire racine" et là il donne une liste de fichiers à mettre en lecture seule, ce qui est impossible comme ça endommage le système, je voulais savoir si ça pose un problème de sécurité où je m'en occupe pas?

**Comment by atm-florianm** [comment]
@Alexis-M51 Comment avez-vous mis ces fichiers en lecture seule ?

J’ai fait un essai chez moi (en local, où d’ordinaire mes fichiers sont en lecture-écriture pour faciliter le débogage et le développement).

Après une fausse manip (où `htdocs` était en lecture seule pour tout le monde), j’ai rectifié le tir : les sous-arborescences de `htdocs` sont en lecture seule pour tout le monde, mais pas `htdocs` lui-même, ni `htdocs/custom`.

Avec ce paramétrage, je n'ai pas de soucis.

**Comment by Alexis-M51** [comment]
j'ai fait un script ou je change un par un la liste de fichiers qu'il donne en lecture seule, je vais essayer ce que vous m'avez dit et je reviens vers vous.

**Comment by Alexis-M51** [comment]
@atm-florianm alors j'ai essayé ce que vous m'avez conseillé et ça fait toujours le même problème.

**Comment by atm-florianm** [comment]
@Alexis-M51 Pouvez-vous préciser en quoi consiste le problème (message d’erreur sur une page, sur toutes les pages, warnings, erreur 500, accès interdit ou autre), au cas où ça puisse aider à diagnostiquer ?

À part ça, au delà de l'accès en écriture, il faut évidemment s'assurer que www-data a accès en lecture à tous ces fichiers et en exécution aux répertoires (pour rappel : sans droit d’exécution sur un répertoire, ce répertoire ne peut pas être ouvert, c’est un peu contre-intuitif au début).

**Comment by Alexis-M51** [comment]
@atm-florianm Ça me mais comme erreur que les fichiers n'ont pas les droits pour être accessible, et oui je vais voir ce que vous m'avez dit et je reviens vers vous si j'ai un autre problème.

**Comment by Alexis-M51** [comment]
Alors ça allaire de fonctionne en mettant lecture et exécution. Je reviens vers vous si j'ai un problème sur ce sujet.

**Comment by Alexis-M51** [comment]
Aussi si je veut faire un autre sujet sur le Github mais c'est pour demander de l'aide, je suis obligé de sélectionner la section bug?

**Comment by atm-florianm** [comment]
@Alexis-M51 Dans ce cas-là, il vaut mieux poser la question sur [le forum](https://www.dolibarr.fr/forum/).

On peut utiliser son compte GitHub pour s'y connecter.

Du coup, je ferme l’issue (vous pourrez la rouvrir si besoin).
