### ISSUE TITLE
Bug: Warning: Creating default object from empty value in /erp/main.inc.php on line 1045

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#19057]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.31
- **Database**: MySQL or MariaDB 5.7.30-log
- **URL(s)**: /index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
no error

## Steps to reproduce the behavior
Immediatly after connection

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by fpav** [comment]
It seems that it is linked to documents archive, I lost links to all the documents? How can I recover them or repair the database? It seems that it occured during upgrade from 14.0.2 to 14.0.3

**Comment by fpav** [comment]
Perfectly solved by your addition!... I thank you so much.

**Comment by dlau74** [comment]
Hi all, could it be possible to explain how you fixed this issue ?  I have exactly the same but do not see clearly what you did in order to fix it. Sorry but I am pretty newbe in github usage...

**Comment by fpav** [comment]
Just click on the link : 
0692d52

and modify the main file accordingly.

This is solving the issue.

**Comment by dlau74** [comment]
Thanks a lot !
