### ISSUE TITLE
Dolibarr include in an iFrame

### ISSUE THREAD

**Issue by lemnet** [Dolibarr/dolibarr#19055]
I'm trying to include dolibarr as an external site in Nextcloud.
With some `define` in the conf.php file, I was able to make this work but when in an iFrame dolibarr hides the top and left menus with this code at the end of [htdocs/core/js/lib_head.js.php](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/js/lib_head.js.php) : 
```
// Force to hide menus when page is inside an iFrame
$(document).ready(function() {
	if (window.location !== window.parent.location ) {
		console.log("Page is detected to be into an iframe, we hide by CSS the menus");
		// The page is in an iframe
		jQuery(".side-nav-vert, .side-nav, .websitebar").hide();
		jQuery(".id-container").css('width', '100%');

	}
});
```
So, would it be possible to have an option to not hide the menus when in an iframe ?

**Comment by gortium** [comment]
I would like to reopen this feature request. I'm having the same issue.
These guys too seem to have the same issue without any real fix:
https://www.dolibarr.fr/forum/t/iframe-nextcloud/29812
