### ISSUE TITLE
Access forbidden when the password of other users is changed

### ISSUE THREAD

**Issue by javieralapps4up** [Dolibarr/dolibarr#19064]
# Bug
Access forbidden when the password of other users is changed

## Environment
- **Version**: 14.0.2
- **OS**: All
- **Web server**: All
- **PHP**: 7.4.13
- **Database**: MariaDB 10.6.4
- **URL(s)**: /htdocs/user/card.php?id=xx

## Steps to reproduce the behavior
User with lire and password (user) perms, but no creer.

When this user saves or cancels the edition of the password of another user, he is sent to the prohibited page

**Comment by atm-florianm** [comment]
I can reproduce this bug with Dolibarr 14.0.3. I will look into it.
