### ISSUE TITLE
wrong redirection after contact creation

### ISSUE THREAD

**Issue by evarisk-theo** [Dolibarr/dolibarr#19111]
![image](https://user-images.githubusercontent.com/68421590/138470411-e3e85a8c-0af0-4673-b755-4c47e7bea742.png)

**Comment by tiaris** [comment]
I can not reproduce it with 14.0.3. Can you give more details ? Configuration?

**Comment by evarisk-theo** [comment]
This bug happens only on 15.0.0 alpha
