### ISSUE TITLE
Modulebuilder not working with multiple objects for same custom module

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#19123]
# Bug
When creating multiple objects for a custom module cannot create records for all objects except the first one.

## Environment
- **Version**: 14.0.1
- **OS**: Windows
- **Web server**: Apache/2.4.41 (Win64)
- **PHP**: 7.3.12
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB

## Expected and actual behavior
Should be able to create/edit/insert for any object оф the module

## Steps to reproduce the behavior
1. Create custom module via module builder
2. Create the first object. Edit some fields and test create. (All is OK)
3. Create a second object for the same module.
4. Try to create a record - page reloads, but nothing happens and there is no record in the database.

**Comment by atm-maxime** [comment]
Hi ! Thanks for reporting.
Did you activate the module before creating the 2nd object ? Can you try reactivating the module ?

**Comment by milenmk** [comment]
After creating the first object - no.

I've created all objects before first activation, modified the fields and then activated it.

After that, tried to turne it off and on again and still nothing.

When clicking create for any oh the other objects, redirect is to "objectname_card.php" without the "?id=" at the end. 

Did a var_dump and I can see the data is posted.

Nothing in the debug bar, or any errors in dolibarr.log.

Tried to return the sql query as a string from "$this->createCommon($user, $notrigger);" but nothing. Just a blank screen after clicking create.

**Comment by milenmk** [comment]
Just found the reason - permissions for the objects. When creating a fresh module, in /core/modNAMEclass.php we have this:

```
// Add here entries to declare new permissions
/* BEGIN MODULEBUILDER PERMISSIONS */
$this->rights[$r][0] = $this->numero . sprintf("%02d", $r + 1); // Permission id (must not be already used)
$this->rights[$r][1] = 'Read objects of DistributorSales'; // Permission label
$this->rights[$r][4] = 'myobject';
$this->rights[$r][5] = 'read'; // In php code, permission will be checked by test if ($user->rights->distributorsales->myobject->read)
$r++;
$this->rights[$r][0] = $this->numero . sprintf("%02d", $r + 1); // Permission id (must not be already used)
$this->rights[$r][1] = 'Create/Update objects of DistributorSales'; // Permission label
$this->rights[$r][4] = 'myobject';
$this->rights[$r][5] = 'write'; // In php code, permission will be checked by test if ($user->rights->distributorsales->myobject->write)
$r++;
$this->rights[$r][0] = $this->numero . sprintf("%02d", $r + 1); // Permission id (must not be already used)
$this->rights[$r][1] = 'Delete objects of DistributorSales'; // Permission label
$this->rights[$r][4] = 'myobject';
$this->rights[$r][5] = 'delete'; // In php code, permission will be checked by test if ($user->rights->distributorsales->myobject->delete)
$r++;
/* END MODULEBUILDER PERMISSIONS */
```

Once an object is created, on the line `$this->rights[$r][4] = 'myobject';`, `myobject` is changed with the newly created object name.

However, if we add more objects, the above permissions are not generated for them. If I add them by hand everything is working.

**Possible solution:**

Add objects to an array, and change code like this (tested and working):

```
		// Permissions provided by this module
		$moduleObjects = array('object1', 'object2');
		$this->rights = [];
		$r = 0;
		foreach ($moduleObjects as $value) {
			// Add here entries to declare new permissions
			/* BEGIN MODULEBUILDER PERMISSIONS */
			$this->rights[$r][0] = $this->numero . sprintf('%02d', $r + 1); // Permission id (must not be already used)
			$this->rights[$r][1] = 'Read objects of DistributorSales'; // Permission label
			$this->rights[$r][4] = $value;
			$this->rights[$r][5] = 'read'; // In php code, permission will be checked by test if ($user->rights->distributorsales->distributors->read)
			$r++;
			$this->rights[$r][0] = $this->numero . sprintf('%02d', $r + 1); // Permission id (must not be already used)
			$this->rights[$r][1] = 'Create/Update objects of DistributorSales'; // Permission label
			$this->rights[$r][4] = $value;
			$this->rights[$r][5] = 'write'; // In php code, permission will be checked by test if ($user->rights->distributorsales->distributors->write)
			$r++;
			$this->rights[$r][0] = $this->numero . sprintf('%02d', $r + 1); // Permission id (must not be already used)
			$this->rights[$r][1] = 'Delete objects of DistributorSales'; // Permission label
			$this->rights[$r][4] = $value;
			$this->rights[$r][5] = 'delete'; // In php code, permission will be checked by test if ($user->rights->distributorsales->distributors->delete)
			$r++;
		}
```
