### ISSUE TITLE
S/N by warehouse on production

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#19134]
https://github.com/Dolibarr/dolibarr/blob/ad2d41179376d3a100d9c2543a7f3a85fe1fffc5/htdocs/mrp/mo_production.php#L978

i was about to push a commit with this usage with stocks, serial numbers by warehouse :
![image](https://user-images.githubusercontent.com/8720867/138548404-968367a2-50a7-4a9a-946f-8f862c5d4c08.png)

would you like this instead of dalatlist ?

**Comment by BebZ** [comment]
oh yes!

**Comment by homer8173** [comment]
It is still a wanted feature
