### ISSUE TITLE
Is not possible to select a different parent project in a task to allow to move tasks between different projects

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#19177]
Now in Dolibarr 14.0.3 is not possible to move tasks from one project to another one when is necessary.

To be able to do it, please add the possibility to allow to select a different parent project in a task to allow to move tasks between projects, Also obviously all the attached files to the task should be also moved to the files folder related the new project that the task belongs.

**Comment by atm-maxime** [comment]
Hi. Thanks for contributing. However, I think that your issue must be qualified as a feature request and not a bug.

**Comment by moreauftheobald** [comment]
it not seems to be very difficult to release. I'll do it.

**Comment by PaMaintenance** [comment]
Hi, I am interesting for this feature. Can you share your solution ?
I’m not a developer !
Thanks

**Comment by edupulpillo** [comment]
@moreauftheobald do you have any commit request ready that we can test ?

**Comment by zunami** [comment]
i think that's a great idea.
But it would be great to link projects or to create sub-projects.

**Comment by lmag** [comment]
- [ ] Option in the project configuration "Moving tasks to another project"
- [ ] Added listing of all valid projects on this entity
- [ ] Addition of the option to modify invoices made over the time of this task and assignment to the new project
- [ ] Affect Task users to the project where we transfert the task
- [ ] Add an event indicating the transfer of the old project task to the new project

**Comment by altairis-arre** [comment]
what about content linked to the task after the transfert ? (time, users, ...)

**Comment by lmag** [comment]
@evarisk-theo @nicolas-eoxia Suivre le forum : 
https://www.dolibarr.fr/forum/t/taches-et-projets/38225

**Comment by edupulpillo** [comment]
And what about if a task and a project be the same kind of object, but that can have a parent-child relation with another tasks. Then the task that is the root in a tree will be the current "project"

**Comment by Francewhoa** [comment]
For those interested in this feature, find this related and open ticket at https://github.com/Dolibarr/dolibarr/issues/23230
