### ISSUE TITLE
Add description for the shipping option under Workflow module

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#19188]
14.0/Changelog says this:

    NEW: add option in Workflow module to set a shipment as closed

However, the description for that needs to be rewritten in the Workflow module because it looks like it's some kind of placeholder for developers?

![Untitled](https://user-images.githubusercontent.com/11036018/138610620-66795187-1c62-4b39-a231-9283a2767673.png)

**Comment by atm-maxime** [comment]
That's a missing translation on transifex. Which language are you with ?

**Comment by bos4711** [comment]
en_US

**Comment by bos4711** [comment]
It seems en_US/main.lang was not properly installed during the upgrade. When replacing manually, the description is fine so this does not need any fix.

Closing issue.
