### ISSUE TITLE
Difference table structure between MySql & Postgres for llx_facture & llx_facture_fourn

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#19198]
# Bug
For the same column in tables **llx_facture** & **llx_facture_fourn** there is a difference between the Postgres Structure and the MySql structure. 
It cause an issue when hi-availability or replication are setup between systems, especially if the artcitecture are different between datacenters 

- Postgres : Table llx_facture - Column name = **fk_mode_transport**
- Mysql : Table llx_facture - Column name = **fk_transport_mode**

- Postgres : Table llx_facture_fourn - Column name = **fk_mode_transport**
- Mysql : Table llx_facture_fourn - Column name = **fk_transport_mode**

## Severity
Minor

## Environment
- **Version**: 13.0.2
- **OS**: Debian 
- **Web server**: Apache2
- **PHP**: 7.4
- **Database**: Mysql & Postgres
- **URL(s)**: N/A

## Expected and actual behavior
The column should be renamed the same way on both install

## Steps to reproduce the behavior
Compare two shemas

**Comment by ksar-ksar** [comment]
Hello,

Normally this is not possible, the fk_mode_transport has been rename in fk_transport_mode in V14
So for V13, it should be fk_mode_transport 

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/migration/13.0.0-14.0.0.sql#L628

It seems that your MYSQL instance is on V14 not V13

**Comment by daxitsolutions** [comment]
The database has been patched in order to allign the migration 
Case closed if this has been included in v14

**Comment by daxitsolutions** [comment]
Thanks
