### ISSUE TITLE
set defaults for form fields - not working consistently 

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#19193]
# Bug
example:
the `target` select for a bookmark is broken by this change https://github.com/Dolibarr/dolibarr/commit/687eb536aee1eb8a71d0077abc0ab1de20118a55 again. 
After my PR https://github.com/Dolibarr/dolibarr/pull/18349 it worked although I do not see why the change above does not work properly.

we need to think about moving the creation of forms to a class that needs to be extended like the `class CommonObject`

## Environment
- **Version**: develop 15.x

**Comment by eldy** [comment]
I can't reproduce the trouble (on develop). Can you describe how you reproduce it ?
