### ISSUE TITLE
V14.0.3 : Warning with MAIN_USE_ADVANCED_PERMS = 1

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#19199]
# Bug
We you use MAIN_USE_ADVANCED_PERMS =1
You get 3 warnings on the main.inc.php when you are ADMIN : 

```
Warning: Creating default object from empty value in /htdocs/main.inc.php on line 1045
Warning: Creating default object from empty value in /htdocs/main.inc.php on line 1047
Warning: Creating default object from empty value in /htdocs/main.inc.php on line 1049
Warning: Cannot modify header information - headers already sent by (output started at /htdocs/main.inc.php:1045) in /user/logout.php on line 110
```

This is due to that code : 
```
//Required if advanced permissions are used with MAIN_USE_ADVANCED_PERMS
		if (!empty($conf->global->MAIN_USE_ADVANCED_PERMS)) {
			$user->rights->user->user_advance->readperms = 1;
			$user->rights->user->user_advance->write = 1;
			$user->rights->user->self_advance->readperms = 1;
			$user->rights->user->self_advance->writeperms = 1;
			$user->rights->user->group_advance->read = 1;
			$user->rights->user->group_advance->readperms = 1;
			$user->rights->user->group_advance->write = 1;
			$user->rights->user->group_advance->delete = 1;
		}
```
## Environment
- **Version**: V14.0.3
- **OS**: Any
- **Web server**: Any
- **PHP**: V7.4
- **Database**: Any
- **URL(s)**: Any

https://www.dolibarr.org/forum/t/warning-about-advance-permission-after-upgrade-to-v14-0-3/21337
https://www.dolibarr.fr/forum/t/v14-0-3-warning-au-lancement-en-admin-seulement/38177

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/issues/18760

**Comment by ksar-ksar** [comment]
> #18760

Yes it has been introduced by this PR

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/18772

**Comment by ksar-ksar** [comment]
Ok sorry it has been closed by #18772

**Comment by frederic34** [comment]
in develop or in 14 ?

**Comment by ksar-ksar** [comment]
Rhaa.... FIX is only for develop.....

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/19202

**Comment by ksar-ksar** [comment]
Thank you @frederic34
