### ISSUE TITLE
Salaries: Batch add salaries for a period

### ISSUE THREAD

**Issue by TheTrueTom** [Dolibarr/dolibarr#19218]
# Feature Request
When adding salaries, it can become cumbersome to add salaries one by one for all employees. Especially if that number of employees tends to rise although the "Save and new" button is a huge time saver.
It would be nice to be able to batch record salary for all employees.

## Use case
This feature would be use to add salaries for all employees at the same time rather than one at a time.

## Suggested implementation
In the "New salary" page, the top section could be replaced with a table generated with all the employees registered in the company. Other fields of the table could include Label, start date, end date, amount, project, comment.

**Comment by colabware-app** [comment]
Hey @TheTrueTom, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!
