### ISSUE TITLE
Salaries: Save and new should remember the date period

### ISSUE THREAD

**Issue by TheTrueTom** [Dolibarr/dolibarr#19217]
# Bug
When entering salaries, the user has an option to either "Save" or "Save and new" which keeps fiels such as payment date, bank account and payment method but not start date and end date.
It seems logical that the start date and end date should be the same as the previous salary entered as pay is often paid once a month for all employees.

## Environment
- **Version**: 14.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.3.31
- **Database**: MySQL or MariaDB 5.6.50-log
- **URL(s)**: https://gestion.mexbrain.fr/salaries/card.php?action=create

## Expected and actual behavior
Expected behaviour:
When pressing button "Save and new", start date and end date should be filled with values corresponding to the previous values entered
Actual behaviour:
When pressing button "Save and new", start date and end date are filled with start and end of month

## Steps to reproduce the behavior
Enter a salary for a month that isn't the current month, "Save and new"

**Comment by manu-p** [comment]
Same question, and even the initial the start date and end date should be of current month, not last month, or at least configurable somewhere since many are passing salaries in the last days of the current month, not during the beginning of the next month.
