### ISSUE TITLE
Issue with SQL SELECT

### ISSUE THREAD

**Issue by linuxprocess** [Dolibarr/dolibarr#19214]
# Bug
On a fresh Dolibarr installed via git clone, on the screen "Configuration des limites et précisions", I encountered this error : 

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20211026175501
Dolibarr: 14.0.3 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.4.21
Serveur: Apache/2.4.49 (Debian)
OS: Linux NewDebian 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

Url sollicitée: /dolibarr/admin/limits.php?mainmenu=home
Referer: http://127.0.0.1/dolibarr/admin/pdf.php?mainmenu=home
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, don
Type gestionnaire de base de données: pgsql
Requête dernier accès en base en erreur: SELECT taux as vat_rate, t.code as vat_code, t.localtax1 as localtax_rate1, t.localtax2 as localtax_rate2 FROM llx_c_tva as t, llx_c_country as c WHERE t.active=1 AND t.fk_pays = c.rowid AND c.code='FR' AND (t.taux <> 0 OR t.localtax1 <>0 OR t.localtax2 <>0) ORDER BY t.taux ASC
Code retour dernier accès en base en erreur: DB_ERROR_42883
Information sur le dernier accès en base en erreur: ERREUR: 42883: l'opérateur n'existe pas : character varying <> integer\nLINE 1: ...d AND c.code='FR' AND (t.taux <> 0 OR t.localtax1 <>0 OR t.l...\n ^\nHINT: Aucun opérateur ne correspond au nom donné et aux types d'arguments.\nVous devez ajouter des conversions explicites de type.\nLOCATION: op_error, parse_oper.c:722

## Expected and actual behavior
I expect the correct SQL to be : 
*SELECT taux as vat_rate, t.code as vat_code, t.localtax1 as localtax_rate1, t.localtax2 as localtax_rate2 
FROM llx_c_tva as t, llx_c_country as c WHERE t.active=1 AND t.fk_pays = c.rowid AND c.code='FR' 
AND (t.taux <> 0 OR t.localtax1 <> '0' OR t.localtax2 <> '0') 
ORDER BY t.taux ASC*

**Comment by ksar-ksar** [comment]
Hello,

You are using PostgreSQL, that is a bit more sensitive to that.

**Comment by linuxprocess** [comment]
Thanks
