### ISSUE TITLE
DOLIBAR REST API ISSUE ON IONOS 1&1 - ANY SOLUTIONS? <source>Routes.php:457 at route stage</source>

### ISSUE THREAD

**Issue by SakoKazanjian** [Dolibarr/dolibarr#19216]
Hello world, I am trying to fix an issue related to REST API module:
The issue is that on my local machine and on other hosting providers with no specific configurations of apache dolibarr and REST API is working like a charm. But when it comes to IONOS hosting everything works fine except REST API does not work, it does not generate API keys. Below you can find attached the error I get when I try to get API token using the link (http://www.example.com/api/index.php/login?login=rest&password=rest) which is expected to return the token. I tried to solve the issue with so many different approaches like using .htaccess, trying to modify configurations but nothing works also i found some people having similar issues but there is no solution for it like.. https://www.dolibarr.org/forum/t/the-login-api-to-get-the-api-key-error/19821

Any one had the same issue before? any solutions ?

<img width="426" alt="Screen Shot 2021-10-26 at 8 34 43 PM" src="https://user-images.githubusercontent.com/35534396/138931628-65e42a3c-4c4b-4008-b33e-fcb6d3630b82.png">

**Comment by ksar-ksar** [comment]
Hello,

Basically you need to ask them !
It seems to be a NGINX configuration issue,  I don't know what you can modify or not, but here you have an example that worked : https://wiki.dolibarr.org/index.php?title=Webserver

**Comment by SakoKazanjian** [comment]
Thank you @ksar-ksar for your comment, I am running Dolibarr on Apache and I have the same configuration locally and on IONOS but on IONOS it is not working, I tried to explain and ask IONOS about it but we did not come to a solution. I am looking for someone that may have encountered such an issue and managed to solve it somehow.

**Comment by SakoKazanjian** [comment]
Issue still not resolved

**Comment by ksar-ksar** [comment]
Hello,

This issue is realted to IONOS not Dolibarr.
For this kind of things you can use the Dolibarr forums.
