### ISSUE TITLE
Error in Stock module

### ISSUE THREAD

**Issue by charleslcso** [Dolibarr/dolibarr#19229]
# Bug
Crash after clicking "Replenishment" in Stock module

## Environment
- *14.0.3 cloud
- Linux apollon3 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
- Apache/2.4.41 (Ubuntu)
- 7.4.3
- MariaDB
- /product/stock/replenish.php?leftmenu=

## Expected and actual behavior
Display proper page content

## Steps to reproduce the behavior
Just click "Replenishment"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Screenshot 2021-10-28 at 3 32 08 PM](https://user-images.githubusercontent.com/520537/139208203-2c356bc4-14cf-4fb4-b17e-4e36cfba0369.JPG)

**Comment by noec764** [comment]
I'm working on it

**Comment by ksar-ksar** [comment]
You need to have at least one warehouse to use this module
