### ISSUE TITLE
Centralize all checks in `restricedArea` ?

### ISSUE THREAD

**Issue by vincentjdc** [Dolibarr/dolibarr#19233]
# Feature Request / Question

This is more an opened question than a feature request.
Dolibarr has a `restrictedArea` function that can be hooked, which is great for modules to alter the default behavior.
I see that in some files, like in `expensereport/card.php`, some checks are done before/outside the `restrictedArea` function : 

https://github.com/Dolibarr/dolibarr/blob/d1794d7948300f23a9e9fbe1ebd34aaf00d3d035/htdocs/expensereport/card.php#L122-L140

In that situation the hook in `restrictedArea` is almost useless.

Shouldn't all the checks exclusively done in `restrictedArea` ? So that any security check behaviors can be changed using a module ?

## Use case

My personal use case is that we need more complex access that the one offered by Dolibarr.
We thinking of making a module that manage multiples business units (BU)  where :
- some people can only see his own data (own orders, own expense reports, ...)
- some people can only see own business unit data (all orders of the BU, all expenses reports of BU)
- some people can see all the data of all business units.

If all the checks are done in `restrictedArea`, I can make a module to manage the business units and his users/groups and control the access using a hook.

PS : we already purchased the multi-company module but :
- it does not fit all our needs
- company changing is very annoying
- our purpose is to only filter the access, not to change invoicing informations, VAT, ...
- support is inexistant

**Comment by hregis** [comment]
@vincentjdc 
hello, to have support on multicompany you should already contact me !
have a good day...

**Comment by vincentjdc** [comment]
@hregis I did on support.inodbox.com (ticket #441074) + by email, but this is not the place to discuss this ;-)
