### ISSUE TITLE
Bug: PayPal module error message

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#19239]
After letting a client pay by PayPal, the payment worked fine but I recived an email with the massage below, and the payment is not registed in Dolibarr. What is this about?

La page de confirmation des paiements ayant été apellée par le système de paiement a retourné un erreur 

Informations techniques:
Système de paiement en ligne: paypal
URL de retour de paiement: /my_path/public/payment/paymentok.php?s=order&ref=BC300329&fulltag=ORD%3D244.CUS%3D17827.PM%3Dpaypal&securekey=7lZp7A760QX0b7cSyOB62FyoSaZe1srZ&e=1&token=EC-9XV27610WH089633T&PayerID=7WACDBHT8BHN2

tag=ORD=244.CUS=17827.PM=paypal
token=EC-9XV27610WH089633T
paymentType=
currencycodeType=
payerId=7WACDBHT8BHN2
ipaddress=
FinalPaymentAmt=

## Environment
- **Version**: 14.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.31-1+0~20210923.88+debian10~1.gbpac4058
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0+deb10u1
- **URL(s)**: /azert/compta/facture/card.php?facid=355

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Please go to forum for this kind of "how to use" issue.
