### ISSUE TITLE
Salary 

### ISSUE THREAD

**Issue by xbloq** [Dolibarr/dolibarr#19241]
If I enter a salary but it isn't paid, then the salary does not appear in the Overview Project.

If I pay this salary linked to a project, then in "List of payments of salaries related to the project" of Overview Project I have a new "Select element Link To", but it's not OK. The number that I can select it's not the new salary payment it's the same number but of another salary (not payment salary) not linked to the project

 I think it is an error between fields of salary number and salary payment number 

V.14.0.3
Fedora 35
Apache/2.4.46
PHP: 7.4.24 
Mariadb  10.5.12

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by xbloq** [comment]
In table payment_salary after make a payment of salary

rowid is salary number not salary_payment number
ref is null
fk_user is null
datev is null
fkproject is null
label is null
datesp is null
dateep is null 
fk_salary is different a rowid and different to salary and salary_payment. It's possible  in this case because there were salary payments that were eliminated? 

when I correct those fields in mysql as in the entries before to V14 everything is OK

**Comment by aspangaro** [comment]
Thanks for your return, it's a bug. I try to correct this.

**Comment by xbloq** [comment]
Now, with fix In Overview project in List of time consumed on tasks of project I have a message:

_This website or feature is currently temporarly not available or failed after a technical error.
This may be due to a maintenance operation. Current status of operation (2021-10-31T12:14:28Z) are on next line...
Dolibarr has detected a technical error. You can read log file or set option $dolibarr_main_prod to '0' in your config file to get more information._ 

and a popup _Unknown column 't.fk_soc' in 'where clause'_

In my dolibarr log:

ERR     10.8.0.6       DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 't.fk_soc' in 'where clause'
ERR     10.8.0.6        Error url=/dolibarr/projet/element.php?id=333, query_string=id=333, sql=SELECT t.rowid, t.ref, s.nom as name FROM nal_salary as t, nal_societe as s WHERE fk_projet is null AND t.fk_soc = 2 AND t.entity IN (1) AND s.rowid = t.fk_soc ORDER BY ref DESC, db_error=Unknown column 't.fk_soc' in 'where clause'
ERR     10.8.0.6        FormProjets::select_element Unknown column 't.fk_soc' in 'where clause'

**Comment by xbloq** [comment]
Thanks aspangaro & eldy. Work without error now
