### ISSUE TITLE
Cannot list HRM / Employees 

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#19255]
If am in HRM / Employees 
/dolibarr/hrm/index.php?mainmenu=hrm&leftmenu=

and I click on _Employees->List_ I get an "Permission denied" Error
Link copied from menu:
/dolibarr/user/list.php?mainmenu=hrm&leftmenu=hrm&mode=employee&contextpage=employeelist

Dolibarr Development (last pull today)
PHP 7.3 & 7.4 tested

**Comment by aspangaro** [comment]
Hello @mwelters 

Can't reproduce, works for me. Try to disable/enable the HRM module

**Comment by mwelters** [comment]
Hi,

after disabling a lot of modules and re-enabling these modules the List appeared again.
I think there was some kind of mess in permissions table.
Thanks for the hint !
