### ISSUE TITLE
Extrafields not working when creating a customer invoice from a template

### ISSUE THREAD

**Issue by geb-solutions** [Dolibarr/dolibarr#19289]
# Bug
I added an extrafield on customer invoices. When I create a new invoice from a template, I can enter the value of the extrafield on the creation page (/dolibarr/compta/facture/card.php?action=create&socid=163&fac_rec=8), but it isn't saved. 
The value is empty in the new customer invoice.

## Environment
- **Version**: Dolibarr 14.0.3
- **OS**: Ubuntu 20.04.3 LTS
- **PHP**: PHP 7.4.3
- **Database**: MariaDb 15.1
- **URL(s)**:  /dolibarr/compta/facture/card.php?action=create&socid=163&fac_rec=8

**Comment by milenmk** [comment]
When creating the custom field did you set that it should be visible on the pdf?
