### ISSUE TITLE
API: more options to get details of time spent lines 

### ISSUE THREAD

**Issue by mschamp** [Dolibarr/dolibarr#19294]
# Feature Request
Add options to get time spent on tasks by the REST API.

## Use case
I could be handy to be able to get a detailed overview of the time spent on a task. 
In the GET /tasks/{id} option 2 of includetimespent is not yet implemented.

It could also be handy to have an option to get an overview based on the user ID.
For example: Al tasks and times spent of user [id] between [startdate] and [enddate]

**Comment by colabware-app** [comment]
Hey @mschamp, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!

**Comment by mproove-gh** [comment]
I have the same need.
I am looking for a way to retrieve the detailed list of time records spent on a task.

When will the option 2 of "includetimespent" parameter be implemented?

**Comment by mschamp** [comment]
No idea, I never added things to the API, but I will give it a try this weekend.
