### ISSUE TITLE
Get all products as objects

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#19297]
# Feature Request
Add availability to fetch all products

## Use case
Currently, to fetch a product you need to specify at least its ID, due to the restrictions on line 2237 in '/product/class/product.class.php'

## Suggested implementation

Adopt the 'fetch()' method to be able to return all products in an array of objects

Further below, in the SQL query, there is a condition to add a "Where" clause to the SQL query if the product id is specified, so I think this will be a safe change

**Comment by altairis-tof** [comment]
hello, why do you need this feature ? it can be very dangerous in terms of performance with big databases (imagine 66000 products for instance...)

**Comment by milenmk** [comment]
> hello, why do you need this feature ? it can be very dangerous in terms of performance with big databases (imagine 66000 products for instance...)

That's why I've mentioned the where clause.

Send the ability to fetch all products is very useful for custom queries or filla drop-down menu. Using the where clause, you can get all products for particular category for example.

Otherwise, we need to get ALL id's with one query and the fetch the info in loop with another query. I.e. 2 queries instead of one.

**Comment by fappels** [comment]
You mean probably 'Add a fetchAll() method to product class' like in 
/htdocs/modulebuilder/template/class/myobject.class.php

**Comment by milenmk** [comment]
> You mean probably 'Add a fetchAll() method to product class' like in 
> /htdocs/modulebuilder/template/class/myobject.class.php

Yes, something like that.

**Comment by milenmk** [comment]
I am closing this, because as we have in `html.form.class.php` methods `select_produits` and `select_produits_list` this is probably not needed.
