### ISSUE TITLE
TakePOS : show only items in stock

### ISSUE THREAD

**Issue by eljub** [Dolibarr/dolibarr#19309]
# Feature Request
TakePOS : show only items in stock

## Use case
Because normally you can't sell an item that is not on stock, I would suggest to add the ability to only display items that are in stok in the TakePOS terminal

## Suggested implementation
Add an option on each TakePOS terminal to only display item that are in stock

A remaining question could be : should this be enable only if the option "Force and restrict warehouse to use for stock decrease" has been selected ?
For me this option could be useful in both case, if the "restrict" option has been selected or not

**Comment by altairis-tof** [comment]
hello, we are working on it; PR will be ready in two weeks. @altairis-melina

**Comment by altairis-tof** [comment]
PR done : https://github.com/Dolibarr/dolibarr/pull/19603

**Comment by Zulgrib** [comment]
Hello,
Enabling the constant prevent selling services from the POS page because they cannot have any stock, the constant should only affect physical products.

**Comment by Zulgrib** [comment]
@altairis-tof 
Hello,
Enabling the constant prevent selling services from the POS page because they cannot have any stock, the constant should only affect physical products.

**Comment by altairis-tof** [comment]
Hello, you are right. I will sibmit a PR to fix it but il will not be integrated in dolibarr core since v18 because v17 is already frozen.

**Comment by altairis-tof** [comment]
since i cannot assign myself, i ping myself @altairis-tof so i will not forget
