### ISSUE TITLE
TakePOS : Customize Terminal's name

### ISSUE THREAD

**Issue by eljub** [Dolibarr/dolibarr#19308]
# Feature Request
TakePOS : Customize Terminal's name

## Use case
I think this could be great to be able to customize the name of the terminal in TakePOS instead of having Terminal 1, terminal 2, etc

## Suggested implementation
Add the possibility to customize TakePOS terminal's name

## Suggested steps
- add a field for terminal's name ?

**Comment by colabware-app** [comment]
Hey @eljub, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!
