### ISSUE TITLE
Improvement of production functiontionality (relation between MO's and MO priorities)

### ISSUE THREAD

**Issue by CodeNinja1337** [Dolibarr/dolibarr#19315]
# Feature Request
We start using Dolibarr to improve the warehouse and production management. One of the features we need is a dependency between MO's to make sure pre-productions are produced before the related end-product production. Also giving a "manufacturing-order" is something we would like to see.

## Use case
The products we manufacture and sell are off course existing out of a BOM. As we are active in a business where we have a lot of peak and trough in the production, we want to do some pre-production in quet times to decrease prodution presure at peak times. To represent it in Dolibarr we like the idea to create BOM's which result in a product which are a "component" of another BOM (which is represents the end-product). 

As we are a small company we don't want to have a lot of stock so there are situations that we don't have enough pre-manufactured parts (i will call them sub-components) when a big order comes in. In this case we create 2 manufacturing orders, 1 for the (missing) sub-components and 1 for building (all) the end-products (which includes 1 or more sub-components). 

As we mostly have multiple open production orders, the sub-component MO's are getting "lost" between all the other MO's. Its also not obvious which MO is depending on which sub-component MO so its working really confusing for the people in the production. They first need to figure out if all the sub-components are available (on stock). They can't see in the MO view so they need to go to the sub-component product or product overview for this information! If there is to less stock, they need to "search" for the corresponding MO's between all the other MO.  

We also have issues with the order of production. The order of production of a product is not always similar to the order where the MO's are created in. The order of production depends on the agreed delivery date with the customer (sometimes we receive order with a delivery date of 1 year ahead). It would be nice if there is a way to define a "order of production", "priority" or "due date" which is shown in the overview.

## Suggested implementation
To solve the "sub-comonent" and "main-MO" issue we would like to see some functionality to add a dependency between a "main-MO" and a sub-component MO. The idea is that the main-MO can only go to "in Progress" when the dependent sub-component MO is finished.

Additionally it would be great if there is a kind of check when creating an main-MO (so one which contains "sub-components" MO) which determines if there are to less sub-components on stock. It could give a warning ("You don't have enough sub-components on stock") with the option "Create a new related MO for the missing sub-components". Checking the box will creating a MO for the missing amount of sub-components automatically and add the depency to the main MO. This makes life easier! Its kind of a parent-child relation :-)

Last but not least, the "order of production" issue. According to our vision there are multiple nice ways to solve this. We like any of them:
- Add a Due date to each (main-)MO would be the easiest way. Depending MO should inherit this date or have an earlier date as it does not make sense when the sub-MO has a later due date then the main-MO.
- Make them drag-and-drop able to change the order. This is probably easy to implement but also probably the most dirty solution to work with as it can work chaotically or confusing. Especially if there are a lot of MO listed.
- A "smart priority" system with "priority id's". A ID is a unique number which represents the order (adding a priority should not be required!). Each time an oder is added and gets a priority id, the MO with the same and higher piority id's are increased with 1. When a MO is finished, all folowing MO priority id's are decreased with 1. related/linked MO should get the same number as the parent MO. This is probably the most complex implementation but would work nicly. 

## Suggested steps
1. Implement depencies/relations between MO
2. Add priorities for MO 
3. Improve the depency/relation between MO with the check/auto creation of MO's 

I would like to hear what other think about this. I also be available to discuss this in more detail with the developers if this helps. We like to support the development with our expertise and testing as well.

**Comment by CodeNinja1337** [comment]
We noticed that we can allocate MO's to a project. As its possible to add the column "project" to the MO overview we can sort the MO's on this column. It makes it easier to determine which "sub-component" MO belongs to which "main-MO" which works fine for us. Maybe this is more the "Dolibarr way" to go instead of the requested dependencies. 

The "MO priorities" are still something we like to see.

**Comment by atm-maxime** [comment]
Hi! We are about to launch a crowdfunding on production modules. Maybe you'll be interested, we plan on developing relation between MOs. @atm-thibaultf is leading the subject.

**Comment by colabware-app** [comment]
Hey @atm-maxime, I’m sure you are struggling to keep up with the number of feature requests here. With [Colabware](https://colabware.co/project/1637415975874x610736382815988200), you can easily harness the power of crowdfunding to drive innovation and sustain developer livelihood. Please do let us know if you have any questions, and I hope we can assist with your project!
