### ISSUE TITLE
barcode scaner in card (search product on input text)

### ISSUE THREAD

**Issue by ander-chan** [Dolibarr/dolibarr#19325]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request
[when PRODUIT_USE_SEARCH_TO_SELECT is defined,select/focus first item list on search]

## Use case
[when PRODUIT_USE_SEARCH_TO_SELECT is defined, the barcodescaner on the input search emit end CLF and submit empty price]

## Suggested implementation
[Add property  **autoFocus:true** in the instance of autoselect, in function  ajax_autocompleter in core/lib/ajax.lib.php (or define global conf for this)]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by colabware-app** [comment]
Hey @ander-chan, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!
