### ISSUE TITLE
Add products or services in interventions

### ISSUE THREAD

**Issue by geb-solutions** [Dolibarr/dolibarr#19326]
# Feature Request
Add products or services in interventions (instead of free description lines ?)
Reuse these products on proposal or invoice creation.
Decrease the stock

## Use case
Our company sells machines and spare parts, and we perform maintenance.
When we sell a machine or parts, we do a sales order and then a shipment. The stock is well decremented.
NB: the stock is decremented during shipment to manage the serial numbers of the machines.
When a technician performs maintenance, he does not order or ship. He just takes the parts he needs from his truck (which is a warehouse).
Currently, the technician must manually write the products he uses and the services he performs during the intervention. He must also perform an inventory correction for each product.
Next, the billing department must find and add the products / services to the proposals or invoices.
These steps are sources of errors.

## Suggested implementation
The technician should be able to choose the products / services with a drop-down list when he create / modify an intervention. 
He should be able to decrement the warehouse stock with a button on a validated intervention (before classify “done”).
The products / services should be transmitted when generating an invoice.
In my opinion, this should be in place of the current description lines because we could still add generic services and change the description.

**Comment by JoAnMaFe** [comment]
I too think it would be a very interesting benefit.

**Comment by colabware-app** [comment]
Hey @geb-solutions, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!

**Comment by warnerbryce** [comment]
Too bad this issue get Closed. 
It's really a good idea that i can made use of.

**Comment by BurksEngineering** [comment]
see #26057
