### ISSUE TITLE
Credit notes should not show up when filtering for "unpaid" invoices

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#19327]
14.0.3, when clicking "Unpaid invoices" in the "Invoices" box on homescreen, credit notes also show up as "Unpaid". These should not show up here. Rather, I think these should be represented in another place and not grouped together with normal invoices.

![2021-11-06_155632](https://user-images.githubusercontent.com/11036018/140614106-b3628a10-22fd-40b4-b4ca-58857fe60261.png)

**Comment by atm-maxime** [comment]
For me it's the right place. If your credit note is unpaid this means you have not refunded your customer yet.
And that's often a transitory status, after validating the credit note you either refund your customer or mark the credit note as a future discount, so it shouldn't stay on the unpaid status...

**Comment by bos4711** [comment]
Here, in Sweden, a credit note is used together with a future invoice to get the credit. We don't issue a refund per se, just a rebate on a future invoice. It could be in a week or in 5 years, so having it listed as "unpaid" is a bit of a nuisance.

How do we solve this? The customer has now got the credit note and we don't want it to be showing. We cannot "enter payment" because that will affect the bank balance in Dolibarr.

**Comment by bos4711** [comment]
Even if I disagree with the credit note functionality, this is obviously not a bug. That's why I'm closing this ticket.

**Comment by atm-maxime** [comment]
I don't know how accountancy work in Sweden, but a credit note is for me something to reduce or cancel an invoice (fix an invoice error for example). And the global turnover is the sum of all invoices, credit note included. So what you say about creating a credit note to get the credit before invoicing is a bit confusing for me.

In Dolibarr, you can't create a credit note without having the origin invoice. What you say seems to me to be more like a deposit invoice when a customer pays a deposit (ie 30% of the order) and this deposit will be deduced from the final invoice later.
