### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by optistea** [Dolibarr/dolibarr#19331]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Importing entries

## Environment
- **Version**: 14.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 8.0.12
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB
- **URL(s)**: /finance/accountancy/index.php?leftmenu=accountancy_transfer

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Report

I tried importing entries with a csv file. Everything went well. But I can't find these entries in the ledger. Impossible to find !

**Comment by atm-maxime** [comment]
With this much information, we can't target any issue. Please seek help on forums as this is probably related to your use of Dolibarr and not a real bug.
