### ISSUE TITLE
QR code for invoice

### ISSUE THREAD

**Issue by husainthangal** [Dolibarr/dolibarr#19340]
# Instructions
It is mandatory to have QR code in invoices for Saudi Arabia (effective from Dec 04, 2021) which will show basic information (Seller name, vat, buyer name, vat, invoice number, amount, vat, total amount including vat etc) once scanned.

# Feature Request
Please include QR code for invoices as new feature since it is mandatory in Saudi Arabia
## Use case
Mandatory in Saudi Arabia
## Suggested implementation
As quick as possible

**Comment by ksar-ksar** [comment]
You have external modules that can do that : https://www.dolistore.com/en/modules/1368-UltimateQRcode-13-0.html

**Comment by colabware-app** [comment]
Hey @husainthangal, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!

**Comment by ksar-ksar** [comment]
> Hey @husainthangal, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!

@eldy, is that kind of post allowed ?

**Comment by dolibarr95** [comment]
@colabware-app ????
