### ISSUE TITLE
{TOBE CLOSED} Extrafields on BOM Lines should be displayed if comulns are arvailable on DB

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#19361]
# Feature Request
There is an existing table "llx_bom_bomline_extrafields" but it's not used. Extrafields on BOM Lines should be displayed if comulns are available on DB.

## Use case
When we add a column on the table llx_bom_bomline_extrafields, the filelds should be displayed on form when create / edit / display the Bom lines. 

## Suggested implementation
- Add a menu on the module BOM to manage extrafields on BOM lines (same as for "facture" and "commande") 
- Change the template form to diplay extrafields

## Suggested steps
1. Create an extra comuln on llx_bom_bomline_extrafields 
`ALTER TABLE llx_bom_bomline_extrafields ADD champextra1 varchar(255) DEFAULT NULL`
`INSERT INTO llx_extrafields (rowid, name, entity, elementtype, label, type, size, fieldcomputed, fielddefault, fieldunique, fieldrequired, perms, enabled, pos, alwayseditable, param, list, printable, totalizable, langs, help, fk_user_author, fk_user_modif, datec, tms) VALUES
(66, 'champextra2', 1, 'bom_bomline', 'champextra2', 'varchar', '255', NULL, NULL, 0, 0, NULL, '1', 100, 1, 'a:1:{s:7:\"options\";a:1:{s:0:\"\";N;}}', '1', 0, 0, NULL, NULL, 1, 1, '2021-11-12 10:15:33', '2021-11-12 13:47:18');`
2. Create a new BOM from .../htdocs/bom/bom_card.php?leftmenu=bom&action=create
3. Add a line to the BOM from .../htdocs/bom/bom_card.php?id=1&save_lastsearch_values=1

**Comment by daxitsolutions** [comment]
![BOM](https://user-images.githubusercontent.com/26635105/141487315-e377dcb8-a716-4b45-91c5-62ce16421d40.png)
Today (v14.0.3) the extrafields are out of the table

**Comment by FHenry** [comment]
The extraffields have to be create with llx_extrafileds entry too. That what extrafield setup page are design for

**Comment by daxitsolutions** [comment]
This feature has been implemented - tread can be closed
https://github.com/Dolibarr/dolibarr/pull/22254
https://github.com/Dolibarr/dolibarr/pull/23104

Thanks a lot @atm-lena
