### ISSUE TITLE
NEW Stripe Payment Element

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#19360]
Replace actual dolibarr"s stripe payment integration by this

https://stripe.com/docs/payments/payment-element

in order to support more gateways

**Comment by colabware-app** [comment]
Hey @ptibogxiv, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!
