### ISSUE TITLE
Ticket message not send to assigned user

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#19371]
# Bug
When the ticket creator writes a message, an email is sent twice to him and NOT sent to the assigned user

## Environment
- **Version**: 13.0.1
- **OS**: Linux 3.10.0-1160.36.2.el7.x86_64
- **Web server**: Apache
- **PHP**: 7.3.32
- **Database**: MySQL or MariaDB 5.5.5-10.3.32-MariaDB

## Expected and actual behavior
A ticket is created and is assigned to a user. When the ticket creator is composing a message and "Send message by email" is checked, one email should be sent to him, and another to the assigned user.

## Steps to reproduce the behavior
Create a ticket, assign a user, compose a message with "Send message by email" check and click "Add message"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[dolibarr2.log](https://github.com/Dolibarr/dolibarr/files/7529673/dolibarr2.log)

**Comment by ksar-ksar** [comment]
Hello,

At least upgrade to v13.0.5 before reporting any bug

**Comment by milenmk** [comment]
> Hello,
> 
> At least upgrade to v13.0.5 before reporting any bug

Same for 14.0.4. I have created a ticket, assign it to one user then add another user as a contributor.

I write a message and check "Send by email".

I receive email that message is added - the other two users don't.
