### ISSUE TITLE
Edit Product Extra Fields from API

### ISSUE THREAD

**Issue by kastoras** [Dolibarr/dolibarr#19378]
# Feature Request
I need to update product extra field values form API (db table:product_extrafields).

## Question
Is there any class I can re-use to help me build this functionlaity? or do I need to build it from scratch?

## Suggested implementation
My first thought is to implement this functionality in Product module, building a new class for this.

**Comment by colabware-app** [comment]
Hey @kastoras, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!

**Comment by kastoras** [comment]
> Hey @kastoras, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!

Hi @colabware-app, thanks for the info. I am building this feature and I will push the code when it s finished.

**Comment by dpriskorn** [comment]
I also would like support for this. I update the database directly currently and that us not ideal
