### ISSUE TITLE
CRON KEY const with multicompany saved with entity = 0

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#19381]
# Bug
Constant CRON_KEY is always stored with entity = 0, so every entity has same cron key.

## Environment
- **Version**: Dolibarr 14.0.x (but also develop branch)
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.4.x
- **Database**: MySql
- **URL(s)**: /cron/admin/cron.php

Solution:
replace this code:
`$i += dolibarr_set_const($db, 'CRON_KEY', GETPOST("CRON_KEY"), 'chaine', 0, '', 0);`
  
with this code
  
`$i += dolibarr_set_const($db, 'CRON_KEY', GETPOST("CRON_KEY"), 'chaine', 0, '', $conf->entity);`

**Comment by aschio** [comment]
Problem is still present in Dolibarr 16.0.1

**Comment by aschio** [comment]
Problem is still present in Dolibarr 17.0.1

**Comment by hregis** [comment]
@aschio fixed here https://github.com/Dolibarr/dolibarr/pull/24592
