### ISSUE TITLE
how to add the Serial Number in a pdf document in php or doc template

### ISSUE THREAD

**Issue by BlackyPurpHair** [Dolibarr/dolibarr#19385]
# Feature Request
Basically, i'm trying to add an extra field in the basic Crabe pdf creation, in which the Serial Number of a product will be shown. So it's supposed to take the Serial number when converting a shipment to an invoice and wirte it in the Desciption. I have been trying to add it into the pdf generation but am Failing drasticly, is there any obvious way i'm missing here?

## Use case
The use case would be generating an invoice from an shipment so the products will already have been fitted with a serial number.

## Suggested implementation
i would suggest, that i can basically just add a function or maybe a variable to the pdf creation crabe which will expect the value of the serial number. I don't expect anyone to just go and fix my Problem but i would appreciate some thoughts and maybe an idea i can try to implement

**Comment by dolibarr95** [comment]
Hello @BlackyPurpHair 
https://www.dolibarr.fr/forum.php
https://wiki.dolibarr.org/index.php/Create_a_PDF_document_template
https://wiki.dolibarr.org/index.php?title=Add_Extrafields_on_PDF_Models
