### ISSUE TITLE
Unable to delete a customer invoice 

### ISSUE THREAD

**Issue by Crashone** [Dolibarr/dolibarr#19394]
# Bug
When I try to delete a customer invoice, I get the following error message :
Unknown column 'fk_invoice' in 'where clause' sql=UPDATE dolibarr_eventorganization_conferenceorboothattendee SET fk_invoice = NULL WHERE fk_invoice = 234
The last number (here 234) may change according to the invoice concerned.

## Environment
- **Version**: Dolibarr 14.0.3
- **OS**: OVH Mutualisé
- **Web server**: Apache 2.4
- **PHP**: 7.4.24
- **Database**: MySQL or MariaDB 5.6.50

**Comment by ksar-ksar** [comment]
Hello,

Strange because the 'fk_invoice' field exist on `eventorganization_conferenceorboothattendee`
![image](https://user-images.githubusercontent.com/35605507/142638015-3ab6ea5b-498a-42d1-b175-6bfb5b52b074.png)

Could you check on your installation if this filed exist in the table ?

**Comment by Crashone** [comment]
Indeed, the field does not exist in my table..
![Screenshot 2021-11-19 at 16-40-46 phpmyadmin-gra2 hosting ovh net ebullisc mysql db phpMyAdmin OVH](https://user-images.githubusercontent.com/20670076/142650499-7c852c77-d296-4613-a11e-f1da956e51c7.png)

Is there a way to check the database and create missing entries ?

**Comment by Crashone** [comment]
I upgraded to Dolibarr 14.0.4 and this fixed the issue.
