### ISSUE TITLE
TakePOS Direct Payment (Cash) Button doesn't work - regression of 18641

### ISSUE THREAD

**Issue by nyfon** [Dolibarr/dolibarr#19397]
# Bug
TakePOS Direct Payment (Cash) Button doesn't work - looks like regression of 18641.
Getting message "Bank account required"

## Environment
- 14.0.3

## Expected and actual behavior
Sale should be completed

## Steps to reproduce the behavior
When "Direct cash payment" button is enabled and used, sale doesn't go through.

EZ Fix, 
Replace 
$("#poslines").load("invoice.php?place="+place+"&action=valid&pay=<?php echo $langs->trans("cash"); ?>", function() {
By	
$("#poslines").load("invoice.php?place="+place+"&action=valid&pay=LIQ", function() {

in index.php

**Comment by nyfon** [comment]
In function DirectPayment()

**Comment by ksar-ksar** [comment]
Hello,

The line in branch 14 is : https://github.com/Dolibarr/dolibarr/blob/14.0/htdocs/takepos/index.php#L771
And due to the translation of https://github.com/Dolibarr/dolibarr/blob/14.0/htdocs/langs/fr_FR/bills.lang#L509
You have `Liquide` instead of `LIQ`

@andreubisquerra could you check ?

**Comment by andreubisquerra** [comment]
Yes, you are in tight!
PR sended!
Thank you @nyfon and @ksar-ksar
