### ISSUE TITLE
The bank account specified into the third-parties for paiements is not usable into Commercial proposal pdf module

### ISSUE THREAD

**Issue by Fra35** [Dolibarr/dolibarr#19400]
For Dolibarr 14.0.3 and olders releases:

When generating a pdf with the module pdf_azur_aster.modules.php (for example) the default bank account specified for the paiement into the third-party is never printed.

Expected:
The default bank account for the third party shoud be printed at the bottom of the PDF into "Commercial proposal" even if the default bank account is specified

The var "$object->fk_account" is null even if the bank is specified:

So i added this piece of code (after the line "if (empty($object->mode_reglement_code) || $object->mode_reglement_code == 'VIR') {"

        $sql ="select fk_account from llx_societe where rowid=".$object->socid;
        $resql=$object->db->query($sql);

        if ($resql)
        {
          $obj=$object->db->fetch_object($resql);
          if (!empty($obj->fk_account))
            $object->fk_account=$obj->fk_account;
        }

**Comment by atm-maxime** [comment]
The account defined on the third-party card is the default bank account to use when creating a document for the customer. So if you create a new invoice, the account should be filled on the invoice with the one of the third-party. Then the fk_account should be filled when generating the PDF. If not, this is the global default bank account that is used.
You shouldn't need to do a SQL query in the PDF generation.

**Comment by Fra35** [comment]
Yes I agree for the invoice but for the proposal, the PDF show at the bottom of the PDF:
"Payment by transfer to the following bank account:"
And then at this place the default account defined on the third-party card should be printed. I supposed? (Or perhaps I missed something)
