### ISSUE TITLE
multi-price in php5.6

### ISSUE THREAD

**Issue by Goldron** [Dolibarr/dolibarr#19409]
# Bug
price recording in several customer price levels.

## Environment
- **Version**: [*14.0.3*]
- **OS**: [*Debian*]
- **Web server**: [*Apache*]
- **PHP**: [*5.6*]
- **Database**: [*mysql*]
- **URL(s)**: [*/product/price.php*]

## Expected and actual behavior
Problem when registering customer price with multiple price levels.

## Steps to reproduce the behavior
only under php5.6
(bug fixed with PHP version greater than 5.6)

**Comment by ksar-ksar** [comment]
Hello,

Could you describes the "problem" ?

**Comment by Goldron** [comment]
Hi,
The recording of values is not done. Impossible to change the prices.

**Comment by Goldron** [comment]
And no error message in the logs.
