### ISSUE TITLE
SQL syntax error in accountancy_report module

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#19416]
# Bug
I get a syntax error when trying to click numbers in the report in the accounting module

## Environment
see below

## Expected and actual behavior
When clicking a number I expect some kind of details to show up

## Steps to reproduce the behavior
Go to reports http://dolibarr.localhost/compta/resultat/index.php?leftmenu=accountancy_report
click a number in the table

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]```

Dolibarr har upptäckt ett tekniskt fel.
Denna information kan vara användbar för diagnostiska ändamål (du kan ange alternativ $ dolibarr_main_prod till '1' för att ta bort sådana meddelanden):
Datum: 20211118132955
Dolibarr: 14.0.2 - https://www.dolibarr.org
Nivå av funktioner: 0
PHP: 7.4.20
Server: nginx/1.20.1
OS: Linux parabola 5.10.39-gnu-1-lts #1 SMP Wed, 26 May 2021 21:20:56 +0000 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0

Begärd webbadress: /compta/resultat/clientfourn.php?year=2021&month=7&modecompta=BOOKKEEPING
Referer: http://dolibarr.localhost/compta/resultat/index.php
Menyhanteraren: eldy_menu.php

Moduler / Applications: api, syslog, user, tax, multicurrency, product, import, export, expedition, margin, propal, blockedlog, salaries, societe, service, variants, projet, ticket, categorie, doliosm, removeconf, workflow, stock, accounting, agenda, banque, commande, facture, fournisseur
Database Type Manager: pgsql
Senaste databasåtkomstförfrågan fel: SELECT f.thirdparty_code as name, -1 as socid, aa.pcg_type, SUM(f.credit - f.debit) as amount FROM llx_accounting_bookkeeping as f, llx_accounting_account as aa WHERE f.numero_compte = aa.account_number AND ( (pcg_type = 'EXPENSE') OR (pcg_type = 'INCOME')) AND fk_pcg_version = 'BAS-SMALL' AND f.entity = 1 AND f.doc_date >= '2021-07-01 00:00:00' AND f.doc_date <= '2021-07-31 23:59:59' GROUP BY pcg_type DESC, name, socid
Returkod för senaste databasåtkomstbegäran: DB_ERROR_SYNTAX
Information för senaste databasåtkomstbegäran: ERROR: 42601: syntax error at or near "DESC"\nLINE 1: ...c_date <= '2021-07-31 23:59:59' GROUP BY pcg_type DESC, name...\n ^\nLOCATION: scanner_yyerror, scan.l:1176
```

**Comment by ksar-ksar** [comment]
Try to update to V14.0.4

**Comment by elcf** [comment]
I'm getting the same error with 15.0.1, the page with the error is on the Double Entry Accounting Module > Accounting > Reporting > Income / Expense > "By predefined groups"

The error:
```
Dolibarr: 15.0.2 - https://www.dolibarr.org
Level of features: 0
PHP: 7.4.25
Server: Apache
OS: Linux
UserAgent: Mozilla/5.0

Requested URL: /compta/resultat/clientfourn.php?leftmenu=accountancy_report
Referer: https://doliwebsite/accountancy/index.php?leftmenu=accountancy_report
Menu manager: eldy_menu.php

Modules/Applications: user, propal, contrat, tax, projet, product, expedition, accounting, banque, commande, expensereport, facture, fournisseur, service, societe, variants, import, ficheinter
Database type manager: mysqli
Latest database access request error: SELECT -1 as socid, aa.pcg_type, SUM(f.credit - f.debit) as amount FROM llx_accounting_bookkeeping as f, llx_accounting_account as aa WHERE f.numero_compte = aa.account_number AND ( (pcg_type = 'EXPENSE') OR (pcg_type = 'INCOME')) AND fk_pcg_version = 'US-BASE' AND f.entity = 1 AND f.doc_date >= '2022-01-01 00:00:00' AND f.doc_date <= '2022-12-31 23:59:59' GROUP BY pcg_type DESC
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC' at line 1
```

**Comment by ghost** [comment]
This error is a typo in the code:
* File: [/htdocs/compta/resultat/clientfourn.php](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/resultat/clientfourn.php)
* Line: 299 `	$sql .= " GROUP BY pcg_type DESC";`

DESC should be removed

**Comment by ksar-ksar** [comment]
@aspangaro can you check ?
