### ISSUE TITLE
Import Adhérent impossible en 14.0.3

### ISSUE THREAD

**Issue by franckhomer** [Dolibarr/dolibarr#19410]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
lors de l'import des adhérents au format fourni, il y a l'erreur
`

    Duplicate entry ‹ 1 › for key ‹ uk_adherent_ref ›
Après avoir demandé sur le forum, il s'avère qu'une nouvelle zone est obligatoire 

"Attention, il y a maintenant un nouveau champ obligatoire dans l’opération d’import qui est la Ref de l’adhérent. Il s’agit de la première colonne, aussi, il vous faudra ajouter cette colonne à votre fichier (1ere colonne) et vérifier l’association des champs. Si vous n’avez pas de ref particulière pour identifier les adhérents, vous pouvez y remettre le login sinon, i lest possible aussi de mettre la valeur « auto » pour tout le monde, dans ce cas, la ref sera un numéro attribué automatiquement lors de l’import."
Cependant impossible d'ajouter la zone.

En revanche quand je fais un export, j'ai bien la zone dans le fichier d'export.
## Environment
- **Version**: [*Affected Dolibarr version(s)*]14.0.3
- **OS**: [*Server OS type and version*]Linux baguette.o2switch.net 4.18.0-147.8.1
- **Web server**: [*Webserver type and version*]APACHE 
- **PHP**: [*PHP version*] 7.4.25
- **Database**: [*Database type and version*]MySQL or MariaDB 5.5.5-10.5.13-MariaDB 
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]
Je souhaiterai importer ma liste d'adhérent au format excel ou CSV sans devoir passer par des requetes
## Steps to reproduce the behavior
[*Verbose description*]
Demande d'un fichier type dans l'import, renseigner les champs essayer de l'intégrer
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/38362462/142382855-613066c8-40dc-40be-8bd6-088e7f3c2faa.png)
Impossible d'ajouter le champ "uk_adherent_ref"

**Comment by daraelmin** [comment]
Duplicate #18266
