### ISSUE TITLE
If third party language is English (United Kingdom), documents are generated in the wrong language

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#19418]
# Bug
When third party language is English (United Kingdom), documents will be generated by default in the first language in the dropdown

## Environment
- **Version**: 14.0.3
- **OS**: Linux  4.14.253-ovh-vps-grsec-zfs-classid from OVH shared hosting
- **Web server**: Apache from OVH shared hosting
- **PHP**: 7.4.24
- **Database**: MySQL or MariaDB 5.6.50-log from OVH shared hosting
- **URL(s)**:  Any URL that generates documents in the customer language, such as:
  /comm/propal/card.php 
  /commande/card.php 
  /fourn/commande/list.php
  /compta/facture/card.php

## Expected and actual behavior
When a language is set for a third party, the user expects the documents to be generated in that language. However, when Third Party language is set to English (United Kingdom), the language gets reset in the dropdowns to the first language in the list (which might change if MAIN_LANGUAGES_ALLOWED is set and/or based on interface language). This does not happen with English (United Estates)

## Steps to reproduce the behavior

1. In /admin/ihm.php set "Enable multilanguage support for customer or vendor relationships"
2. Create a new third party with language English (United Kingdom)
3. Create a proposal/order/etc. document from the third party

The language that will be set on the proposal/order/etc will not be English (United Kingdom), but the first language in the language selector.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![third party](https://user-images.githubusercontent.com/55888212/142627591-da395b69-0b22-4c4a-b689-816c6581e642.png)
![order](https://user-images.githubusercontent.com/55888212/142627604-0c714ee9-5d96-41d5-af17-5557e9d11741.png)

**Comment by ToniTen** [comment]
This was reproduced in a bitnami virtual machine and on https://demo.dolibarr.org/

**Comment by ksar-ksar** [comment]
We have another case in the French Forum : https://www.dolibarr.fr/forum/t/comment-fixer-la-langue-par-defaut-des-propositions/38407

**Comment by eric-lamy-agerix** [comment]
> We have another case in the French Forum : https://www.dolibarr.fr/forum/t/comment-fixer-la-langue-par-defaut-des-propositions/38407

Thank you ksar-ksar for sharing my thread. Even if it is an important problem for those who work like us with multilingual on Dolibarr, you can get around the problem by being careful to put the right language before generating the document. 

Because it doesn't work only when you click on the "Generate" button before validation. If you follow the process and click on the "validate" button, the document is in English. On the other hand, if you generate the document before validating, the language choice is wrong. Tested also on orders and invoices.
Hope it helps

**Comment by Je2fb** [comment]
It seems the issue coming from the class html.formadmin.class.php on line 78, 
The function in_array will didn't find the country code "en_GB" because the country code is a key and not a value.

I replace the line by this one below:
		if ($selected && !isset($langs_available[$selected]) && empty($showempty)) {
