### ISSUE TITLE
Products Module

### ISSUE THREAD

**Issue by isoscent** [Dolibarr/dolibarr#19411]
I am hoping that this will be done in dolibarr

https://www.dolibarr.org/forum/uploads/dolibarrorg/original/2X/8/8aa93aecf027b43987f71041acc1539fc4cb4f76.png

**Comment by colabware-app** [comment]
Hey @isoscent, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!

**Comment by dolibarr95** [comment]
@colabware-app  ?????

**Comment by isoscent** [comment]
The Core module of Dolibarr, that needs to be develop, the missing piece on Products Module, as well as missing Journa entries in Accounting.

**Comment by isoscent** [comment]
Therefore, If this will not be there in Dolibarr, then something is missing, e.g. specially the Future of e-Commerce Depends on this.
