### ISSUE TITLE
Problem with dol_eval()

### ISSUE THREAD

**Issue by atm-florianm** [Dolibarr/dolibarr#19429]
# Issue
In some external modules (in this example, Agefodd), the eval code for determining whether to show a menu uses a conf whose name contains one of the forbidden strings for dol_eval, which breaks the module (here `$conf->global->AGF_CONTACT_DOL_SESSION` because the name contains the forbidden string `_SESSION`).

```php
$this->menu[$r] = array(
	'fk_menu' => 'fk_mainmenu=agefodd',
	'type' => 'left',
	'titre' => 'AgfMenuContact',
	'leftmenu' => 'AgfMenuContact',
	'url' => '/agefodd/contact/list.php',
	'langs' => 'agefodd@agefodd',
	'position' => 600 + $r,
	'enabled' => '$conf->agefodd->enabled && $user->rights->agefodd->lire && empty($conf->global->AGF_CONTACT_DOL_SESSION)',
	'perms' => '$user->rights->agefodd->lire',
	'target' => '',
	'user' => 0
);
```

So far the only workaround we found (beside renaming the conf, which would take a lot of time) is a bit ugly, it looks like this:
```php
$this->menu[$r] = array(
    […]
    'enabled' => '$conf->agefodd->enabled && $user->rights->agefodd->lire && empty($conf->global->{\'AGF_CONTACT_DOL_SES\'.\'SION\'})',
    […]
);
```

Maybe there is a way to use word boundary detection like in https://github.com/Dolibarr/dolibarr/pull/19227 without weakening security for `_ENV` (which was the reason the fix proposed in that PR was rejected and the problem was fixed differently).

**Comment by john-botella** [comment]
Effectivement, le système est très facilement contournable en l'état et génère des difficultés sur des modules existant, ce qui au final rend malheureusement le patch presque inutile.

**Comment by edupulpillo** [comment]
Same problem here.
PHP Parse error:  syntax error, unexpected ')' in /public_html/erp0/core/lib/functions.lib.php(8145) : eval()'d code on line 1
how can be fixed? All the modules of my instance of my Dolibarr in production are suffering this problem. Any recommendation to fix it quickly?
