### ISSUE TITLE
NEW: Apply the default exifs especially for rotating images

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#19421]
Feature Request
Use by default
MAIN_USE_EXIF_ROTATION = 1
The pictures will be in the right way

**Comment by colabware-app** [comment]
Hey @lmag, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!
