### ISSUE TITLE
Tickets - default sending emails when adding a message

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19437]
There is no option two make email sending when adding a message to a ticket. You have to click it manually and a lot of times people forget to click it

**Comment by atm-maxime** [comment]
And if there was there will be lots of times when people forget to unclick it when recording an internal message. Which is best ?

**Comment by ecroow** [comment]
> And if there was there will be lots of times when people forget to unclick it when recording an internal message. Which is best ?

Yes, that's why I wrote it to be an option to make it be the default state. If somebody isn't completely sure, turns it on and gets the message every time.

**Comment by atm-maxime** [comment]
You didn't wrote it to be an option, you said "there's no option"... "It would be good to have an option to make a ticket message being sent by mail as default"

**Comment by alsoft10** [comment]
The best option would be, there should be a configuration entry at Ticket Module. It it is enabled, all message replies will be send via email notification to client email address automatically. Please see the attachment for the details.
![Ticket configuration](https://user-images.githubusercontent.com/1249577/145803145-667dc529-fd46-4946-b4fb-5d0acaccc86a.png)

Now here is an problem that dolibarr user sometimes don't want to send or append message to email reply. In that case, at the ticket reply form, they will uncheck the email notification if they don't want to send reply. If they most of the times don't send the reply, then they will first Disable ticket email reply settings. Now as automatic email reply settings is off, while user will type a reply, by default notify via email checkbox will be unchecked; if they want to send the reply they will just check. This way most of the requirements will be fulfilled.

@atm-maxime if you want, I can start development on this immediately.

**Comment by atm-maxime** [comment]
@alsoft10 you don't need my approval to start any development. If you feel like it's a good feature to have, go !

**Comment by VaderD** [comment]
In the latest version still this feature is missing...
