### ISSUE TITLE
Defective stock

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19439]
There is no option in Dolibarr to decline stock from the warehouse if a product is this defective. It should record this somewhere and you should be able to write down what the reason is for that product to be defective

**Comment by atm-maxime** [comment]
A simple "defective" warehouse and the reason explained on the stock movement you make between the 2 warehouses?

**Comment by josett225** [comment]
Hi All
I believe This is still a valid feature.
Closed, Open and Internal is not enough today to manage situations as defective or buffer or repaired or e-commerce or multiple physical shops situations. 
This is an issue for real and virtual stock management.

**Comment by josett225** [comment]
Still valid
