### ISSUE TITLE
Duplicate 3rd partires

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19432]
# Feature Request
[*Hello! I've got a team of 40 people using Dolibarr and one of the annoying things is that when you create a duplicate 3rd party, it doesn't tell you and it creates it. Can there be an option to choose from what field to look for and check whether it's duplicate or not.*]

**Comment by atm-maxime** [comment]
This would be an interesting option.
Do you know there's a global search usable before creating something?

**Comment by ecroow** [comment]
> 

Yes, I know there's such option, but my 40 employees don't use it, and sometimes forget it's there.

Hubspot for example has it automatically, and looks for duplicate numbers, websites, company names etc.

**Comment by atm-maxime** [comment]
If users don't use what already exists and if hubspot has it... Thanks for the beginning of a solution. So after submitting the third-party creation form, we should check for some similar data and ask the user if he's sure he wants to create a new third ?
Otherwise, there's the merge function what is useful when detecting there are a third duplicate

**Comment by rycks** [comment]
Here is a idea on french forum for that feature request : https://www.dolibarr.fr/forum/t/recherche-automatique-lors-de-creation-dun-nouveau-tiers/39726

**Comment by hregis** [comment]
@rycks @ecroow 
What if the person has to create a company that has the same name but in a different city? How will it know that this customer is the right customer that has already been created?

**Comment by BebZ** [comment]
rint $form->select_company(0, ‹ name ›, ‹ (s.client = 1 OR s.client = 3) AND status=1 ›, ’ ');

they answered on the french forum it seems ?
