### ISSUE TITLE
Project templates

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19435]
There are no project templates which I can choose from.

I have a website development company, and we create a project for each website we're building. And we have to do the same things for every site. We have to manually create every single task and that takes quite a lot of time

**Comment by atm-maxime** [comment]
I imagine that with a website development company, you have some web developers ? Try and help the Dolibarr community by making them contribute 😉 
And for the record, you can perfectly clone a project and its task...

**Comment by zunami** [comment]
I think this is a good idea because I have the same problem every time.
I would like it if it is integrated into the dolibarr core system.

**Comment by atm-maxime** [comment]
As I said, you can clone a project and it's tasks, so create a project named "Project template" and start cloning it every new project you have.
