### ISSUE TITLE
Ticket messages

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19436]
When somebody deletes a ticket, the creator of the ticket doesn't know that.

When somebody completes a ticket, the creator of the ticket doesn't know that

**Comment by atm-maxime** [comment]
Can you try to explain it like this ?
"It would be good if the ticket creator (and related contacts) received an email when the ticket is deleted"

**Comment by ecroow** [comment]
> Can you try to explain it like this ? "It would be good if the ticket creator (and related contacts) received an email when the ticket is deleted"

Yes, exactly!

**Comment by freechelmi** [comment]
Please update your issue title for a precise bug or feature description.
