### ISSUE TITLE
Contacts of 3rd parties can't have dedicated salesperson

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19433]
Contacts of 3rd parties can't have a dedicated salesperson. This would be perfect for sales organisations that deal with multiple salespeople and a 3rd party has multiple contacts.

For example, we've got a client who has 30 different retail stores and we need to have different person assigned to each retail store.

**Comment by atm-maxime** [comment]
Oh good an example ! Why don't you create 30 third parties ? Like this you can have a salespeople affected to each one of them. And I imagine that in each store you know different real contacts.

**Comment by ecroow** [comment]
> Oh good an example ! Why don't you create 30 third parties ? Like this you can have a salespeople affected to each one of them. And I imagine that in each store you know different real contacts.

Why would I do that, if it's 1 company? 1 company has 30 retail stores under the same brand. Why should I create 30 different 3rd parties?

**Comment by atm-maxime** [comment]
Maybe you want to deliver goods to each store, or invoice them separately, maybe you need to have a contact card for each store manager, maybe you need separated statistics about your business with each store. And if there are all thirdparties, you can link them all together with the same parent third-party.
