### ISSUE TITLE
support Iraqi Dinar (IQD) Currency  

### ISSUE THREAD

**Issue by ZamanOof** [Dolibarr/dolibarr#19431]
# Feature Request
Adding Support to Iraqi Dinar (IQD)

## Use case
so what i need to provide for adding it in dolibarr system

**Comment by colabware-app** [comment]
Hey @ZamanOof, it’s hard finding open-source contributors to build your features for free. By [submitting your request through Colabware](https://colabware.co/project/1637415975874x610736382815988200), harness the power of crowdfunding to encourage developers, whilst enabling others to support your vision. Please do let us know if you have any questions, and I hope we can assist with your project!
