### ISSUE TITLE
wrong output dir in odt file generation for recruitment

### ISSUE THREAD

**Issue by cartsofware** [Dolibarr/dolibarr#19449]
Hi,
the [output folder](https://github.com/Dolibarr/dolibarr/blob/e8f7b755f14ddfe84b2bee70f2021324152d95a5/htdocs/recruitment/core/modules/recruitment/doc/doc_generic_recruitmentjobposition_odt.modules.php#L244) is wrong when you try to generate an odt  custom document for recruitment 
It should be not **command** but **recruitment**

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/21695
