### ISSUE TITLE
Sales statistics

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19440]
There are almost no sales of statistics in Dolibarr. I can't see what quantity I have salt from a particular product today, yesterday or one week ago. I can't see how much my sales people are selling each day

**Comment by atm-maxime** [comment]
Thanks for your feedback. What solution do you propose ?
On a product card, you have a specific tab showing statistics and another listing all sales documents containing the product. And based on what you consider your salespeople sells ? Signed proposals ? Invoices? Orders ?

**Comment by dpriskorn** [comment]
You could use the API and Python to generate this statistic. If you want my help with that feel free to contact me.
