### ISSUE TITLE
Cannot cancel "make order" in purchase order

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#19454]
14.0.3

We made a purchase order and I clicked "Make order". In there I forgot something so I clicked "Cancel", but Dolibarr tells me "Order method required" despite wanting to cancel.
![Screenshot_20211122_190641_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/11036018/142913205-06928761-3eb4-4704-b07f-dec3964cebc4.jpg)![Screenshot_20211122_190723.jpg](https://user-images.githubusercontent.com/11036018/142913219-60150035-2b6a-45c8-b1ec-418a6e340a3c.jpg)

**Comment by bos4711** [comment]
Update: If you do select the "Order method" and then click cancel, Dolibarr says this. And if you in **this** dialog select "no", then it is finally cancelled.



![2021-11-23_070715](https://user-images.githubusercontent.com/11036018/142978026-0bc93cf7-0c65-48bb-9fa4-7d25787324ee.png)

**Comment by atm-maxime** [comment]
I can confirm this behaviour. Due to 8b0c2d997cec857f02651b70f3b78fbb8edc66f7.
@eldy any clue on how to solve this ?

**Comment by inoveaconseil** [comment]
Already fixed
