### ISSUE TITLE
Direct Print for Contracts

### ISSUE THREAD

**Issue by st31ny** [Dolibarr/dolibarr#19467]
# Feature Request
Support Direct Print feature for contracts.

## Use case
The direct print function is very convenient, e.g. for offers and invoices. However, contracts cannot be printed directly yet.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/19510

**Comment by st31ny** [comment]
Thanks for the implementation, @frederic34 — this works great for me!
