### ISSUE TITLE
Ticket Email Collector does not send emails on replies ticket messages

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19477]
# Bug
If a reporter replies the message from his email client and sends it back to dolibarr  and the email collector insertes it no email messages is sent informing about it

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

**Comment by alsoft10** [comment]
Confirmation email is important to send back to the client again. But it is always not necessary. Better way is, when clients are sending the mail for first time and the ticket is created for the first time, a confirmation email back to the client is necessary like, "We have got your request. Our support team will get back to you soon." We are working on this bug. You should close it here.

**Comment by VaderD** [comment]
Hello there alsoft10 ,
The confirmation message is sent correctly to the client ! This is not the issue ! And yes maybe sometimes is not necessary...

But at all times email collector should sent to us in order to know that the client sent a new message. Otherwise we do not know about it because the collector does not inform us.  Actually the collector does informs us only when a ticket is created not when a reply is inserted... If the client is not informed the collector should sent to the email we have configured from the settings at least

**Comment by VaderD** [comment]
Well in mind also that the Ticket Fetcher i was using from Librethetic had that functionality.. Is you test it in that module you will understand my thinking...
