### ISSUE TITLE
VAT Calculation mode ignoring Limits and accuracy

### ISSUE THREAD

**Issue by mimifred** [Dolibarr/dolibarr#19472]
# Bug
VAT Calculation mode can be 1 or 2 (based on every line - default ; base on total)
When mode 2 is selected (based on total), parameter "Step of rounding range" in Limits and accuracy is ignored

## Environment
- 14.0.4 and lower

## Steps to reproduce the behavior
Choose Step of rounding range of 0.05 (Switzerland)
Set MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND to 1
Create order or invoice
Total is not rounded to 0.05

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
