### ISSUE TITLE
Wrong initial message on Tickets

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19478]
# Bug
In the ticket initial message on the subject it appears the "New ticket created - Ref  (public ticket ID )" instead of "New ticket created - Ref  (Ticket Number:). Where Ticket Number is TS2111-0018

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

**Comment by VaderD** [comment]
Any news regarding this issue ..?

**Comment by dpriskorn** [comment]
Screenshot?

**Comment by ibuiv** [comment]
![image](https://user-images.githubusercontent.com/50403308/204054394-9d462209-ff66-4359-b568-754876182fd7.png)

already done it seems
