### ISSUE TITLE
In Ticket List the scroll bar is not apearing if you do not go down at the end of the page

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19475]
# Bug
In Ticket List the scroll bar is not apearing if you do not go down at the end of the page

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![2](https://user-images.githubusercontent.com/34111030/143438117-83d67aaa-7389-452c-b74d-314d628fba44.png)
![1](https://user-images.githubusercontent.com/34111030/143438122-44deecda-c106-440d-985e-551e324c380a.png)

**Comment by VaderD** [comment]
Any news regarding this issue ..?

**Comment by atm-maxime** [comment]
Fixed in v15
