### ISSUE TITLE
Max. decimals for prices shown on screen is applied not only on screen

### ISSUE THREAD

**Issue by mimifred** [Dolibarr/dolibarr#19473]
# Bug
"Max. decimals for prices shown on screen" is supposed to affect only screen showing numbers.
Implied, calculations are made on numbers with decimals entered in "Max. decimals for unit prices" and "Max. decimals for total prices".
But if you set "on screen" at 2, every price calculations are made with 2 decimals and not more even if more set on Max decimals for unit.
Resulting in rounding errors.

## Environment
- 14.0.4

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
