### ISSUE TITLE
Error in extra fields of lines in receptions

### ISSUE THREAD

**Issue by JOAAB** [Dolibarr/dolibarr#19479]
# Bug
With the extra fields of lines configured, in the capture of receptions the extra fields for their capture do not appear

## Environment
- **Version**: 14.0.3 - 14.0.4
- **OS**: Windows
- **Web server**: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
- **PHP**: 7.4.19
- **Database**: MySQL or MariaDB 5.5.5-10.4.19-MariaDB
- **URL(s)**: htdocs/reception/card.php

this is because the variable ($extralabelslines) is not defined in the file (htdocs/reception/card.php), adding in line 108 of the mentioned file the following line is solved:

$extralabelslines = $extrafields->fetch_name_optionals_label($object->table_element_line);

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
