### ISSUE TITLE
Ticket Edit initial message it appears blank page

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19476]
# Bug
When you edit an already inserted ticket the initial message it appears blank page after you press the Modify button it  shows a blank page... 

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

**Comment by ksar-ksar** [comment]
Hello,

I can reproduce on my setup 

PHP error is : 
PHP Fatal error:  Uncaught Error: Class 'Diff' not found in /var/www/doli/14/ticket/card.php:573
Stack trace:
#0 {main}
  thrown in /var/www/doli/14/ticket/card.php on line 573, referer: https://xxxxx/14/ticket/card.php?action=edit_message_init&track_id=fdv9wrzcte7b3c8b

The code is : 
// include the Diff class
				dol_include_once('/ticket/class/utils_diff.class.php');
				// output the result of comparing two files as plain text
				$log_action .= Diff::toString(Diff::compare(strip_tags($oldvalue_message), strip_tags($object->message)));

But /ticket/class/utils_diff.class.php doesn't exist from card.php....

Should be dol_include_once('/core/class/utils_diff.class.php');
