### ISSUE TITLE
Tickets not be translated to traditional chinese in v14 and v15 alpha

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#19485]
# Bug
[*Short description*]
" Tickets " is not be translated to traditional chinese  .
## Environment
- **Version**: V14 and v 15 alpha
- **OS**: Mx linux 19.4 and Mx linux 21.1
- **Web server**: Apache 2.4.38
- **PHP**: 7.4.3
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0+deb10u1

- **URL(s)**: [*Affected URL(s)*]/index.php

## Expected and actual behavior
[*Verbose description*]
Should be translated .

## [Attached files]
[*Files*]
![image](https://user-images.githubusercontent.com/78349579/143464176-bdc52599-11ae-4b92-bec1-172e9a55c776.png)

**Comment by blftpe** [comment]
To add to Trekmorris comment: he added the translation in Transifex already, but the chinese doesn't show up in the module bar as shown in the picture.
