### ISSUE TITLE
Intervention list total time erratic

### ISSUE THREAD

**Issue by FlorentinGarnier** [Dolibarr/dolibarr#19483]
# Bug
Intervention list time total is erratic. 

## Environment
- **Version**: 14.0.3
- **Web server**: apache 2.4
- **PHP**: 7.4
- **Database**: Mariadb 10
- **URL(s)**: fichinter/list.php

## Expected and actual behavior
As a Dolibarr User
Given I Have some intervention done
When I list intervention
Then I see the total time on total line

## Steps to reproduce the behavior
Get some inter and list them

## [Attached files]

![Screenshot 2021-11-25 at 14-55-50 Liste des interventions](https://user-images.githubusercontent.com/591596/143454666-36cbf762-7475-49a2-b3c3-467cfc3b525d.png)

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
