### ISSUE TITLE
Error in the creation of receipts reverses the expiration date and sale date

### ISSUE THREAD

**Issue by JOAAB** [Dolibarr/dolibarr#19480]
# Bug
Products configured with batch/series handling expiration dates, when creating a receipt from the purchase order by inserting the batch data, purchase date and expiration date in the product receipt section (htdocs/fourn/commande/dispatch.php), the expiration date and sale date data are reversed when moving to the receipt capture (htdocs/reception/card.php), if the information is corrected in this capture, when validating the receipt it reverses the dates again leaving the incorrect batch information

## Environment
- **Version**: 14.0.3 - 14.0.4
- **OS**: Windows
- **Web server**: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
- **PHP**: 7.4.19
- **Database**: MySQL or MariaDB 5.5.5-10.4.19-MariaDB
- **URL(s)**: (htdocs/fourn/commande/dispatch.php) (htdocs/reception/card.php)

The error is in the two files indicated, where the SELLBY variable corresponds to the values related to dluo, while EATBY corresponds to the dlc values, these are inverted in some parts, modifying in both files with the correct relationships the error was corrected.

**Comment by lemathou** [comment]
In 14.0.5 you have to change in htdocs/reception/card.php

lines 615  : $eatby = GETPOST($dlc, 'alpha');
by : $eatby = GETPOST($dluo, 'alpha');

line 617 : $sellby = GETPOST($dluo, 'alpha');
by : $sellby = GETPOST($dlc, 'alpha');

**Comment by pyr74** [comment]
You also need to change

line 340 :$eatby = "dlc".$i; //Correction BUG DLUO/DLC
by : $eatby = "dluo".$i;

line 341 : $sellby = "dluo".$i; //Correction BUG DLUO/DLC
by : $sellby = "dlc".$i;
