### ISSUE TITLE
EMail Collector does not insert tickets attachments.

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19498]
# Bug
Email messages with attachments sent to the email that email collector checks it inserts only the message boy and subject but not the attachments.  When a message is correctly inserted then attachments should appear in the attachments area.

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]
-

**Comment by alsoft10** [comment]
@VaderD we already created a feature request at [https://github.com/Dolibarr/dolibarr/issues/19569](https://github.com/Dolibarr/dolibarr/issues/19569) and we are working on this. This is not a bug. It's a new features that need to be implemented in Dolibarr. So please close your bug report.
