### ISSUE TITLE
Search capability is disabled on Ticket View

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19496]
# Bug
On the ticket view you cannot search you do on other modules ... Because is disabled

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

![1](https://user-images.githubusercontent.com/34111030/143602230-8d9e7ac0-ed81-4346-bc2d-85c6f45b1dc0.png)

**Comment by VaderD** [comment]
Any news regarding this issue ..?

**Comment by VaderD** [comment]
Bug still exists !

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on a V18 ?

**Comment by VaderD** [comment]
It is fixed....
