### ISSUE TITLE
after canceling a supplier order, the stock will not be updated. for customer orders it is ok. Note that the configuration of stock management is of course configured on the validation of orders

### ISSUE THREAD

**Issue by ayman-zwawi** [Dolibarr/dolibarr#19505]
## Environment
- **Version**: [*v13 14]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Confirmed on v13 : if stock option is set on "Increase real stocks on purchase order approval", the stock is correctly increased after approval, user being asked for the warehouse to use.
But afterwards if user disapprove or cancel the order, warehouse is not asked and stock is not decreased.

**Comment by ayman-zwawi** [comment]
and on v14

**Comment by atm-maxime** [comment]
In my opinion, this stock option allowing to increase stock on order approval is not logical. You haven't send the order to your supplier and yet you consider the stock being available? I think we should deprecate this option instead of fixing this issue.

**Comment by edupulpillo** [comment]
Or at least manage a stock "pending to receive"
