### ISSUE TITLE
The Scheduled Jobs present in our 14.0.3 instance dissapear after updating to 14.0.4

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#19506]
The Scheduled Jobs present in our 14.0.3 instance dissapear after updating to 14.0.4

## Environment
- **Version**:  14.0.4
- **OS**:Linux
- **Web server**:  Apache/2.4.51 (cPanel) OpenSSL/1.1.1l mod_jk/1.2.41 mod_bwlimited/1.4 mod_fcgid/2.3.9 Phusion_Passenger/6.0.7
- **PHP**:  7.4.25
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB
- **URL(s)**: /cron/list.php?mode=modulesetup)
Inour instance 14.0.3 we had 12 scheduled jobs, after the update to 14.0.4, only one scheduled job is displayed in the list, but the window tab header still display the number 12. So for any reason the list do not display the stored scheduled jobs in the database.

This is the screenshot of the list after the update:
![image](https://user-images.githubusercontent.com/7486607/143722900-0052b30c-5602-4631-948e-172dc41cb84e.png)

**Comment by fappels** [comment]
Made PR #19504 to fix this.

**Comment by edupulpillo** [comment]
The fix works fine!
