### ISSUE TITLE
EMail Collector wont work 

### ISSUE THREAD

**Issue by DonFischy** [Dolibarr/dolibarr#19516]
# Problem
I want to change from Zammad Ticket-system to Dolibarr Ticket-system. (Zammad works - Dolibarr not)  
And i dont know what to do. 

The EMail Collector wont work. Everytime is try to fetch mails i get the error 
Failed to open IMAP connection {servername:993/service=imap/ssl/novalidate-cert}INBOX

Failed to open IMAP connection {servername:993/service=imap/ssl/novalidate-cert}INBOX
TLS/SSL failure for servername: SSL negotiation failed

Username, Password and Server IP are correct. 
PHP IMAP function is active. 
Connection via Open SSL works too.

Do i miss something? 

# Environment
- **Version**: 14.0.3
- **OS**: Ubuntu
- **Web server**: Apache 2
- **PHP**: 7.4

**Comment by ksar-ksar** [comment]
Hello,

You have the forum for support : https://www.dolibarr.org/forum/

A lot of things could block, difficult to say : 
 - Does Ubuntu get a firewall ?
 - How the server is connected to internet ?
 - What are the PHP settings ?
etc..

**Comment by DonFischy** [comment]
First: Thanks for you answer!

i know its difficult ... i tried so many things and nothing worked ... 

no firewall (for internal use only) 
Mailserver is in my internal network no route over internet
PHP Settings should be default   

ill try to open this post in dolibarr forum too

**Comment by VaderD** [comment]
Hello there,

It works fine this step to me .... But i do not use SSL. I use servername
