### ISSUE TITLE
Can't edit contacts related to an invoice

### ISSUE THREAD

**Issue by l00ptr** [Dolibarr/dolibarr#19519]
# Bug
We can't edit contact related to an invoice; the invoice is never fetched from the database within this script and we directly fall under "ErrorRecordNotFound". It's probably because without action into the URL we directly go to the view part, and it starts with this piece of code :
```
if (empty($object->id)) {
        llxHeader();
        $langs->load('errors');
        echo '<div class="error">'.$langs->trans("ErrorRecordNotFound").'</div>';
        llxFooter();
        exit;
}
```

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/facture/contact.php#L103
and 
https://github.com/Dolibarr/dolibarr/blob/13.0/htdocs/compta/facture/contact.php#L111

## Environment
-  13.0
-  Debian 10
- Apache
- PHP 7.3.31-1~deb10u1
-  PostgreSQL 12
- /compta/facture/contact.php?facid=4395

## Expected and actual behavior
be able to edit contact related to a invoice

We fall directly under the "Enregistrement non trouvé." / ErrorRecordNotFound invoice is never fetched

## Steps to reproduce the behavior
Just visit the contact tab of an invoice with Dolibarr 13 and probably 14

**Comment by l00ptr** [comment]
We have the same problem with this https://github.com/Dolibarr/dolibarr/blob/ca8dab3/htdocs/compta/facture/info.php#L46

The object->id is always null because we fetch the data after this line, so we never reach the fetch :
```

if (empty($object->id)) {
	llxHeader();
	$langs->load('errors');
	echo '<div class="error">'.$langs->trans("ErrorRecordNotFound").'</div>';
	llxFooter();
	exit;
}

$form = new Form($db);

$title = $langs->trans('InvoiceCustomer')." - ".$langs->trans('Info');
$helpurl = "EN:Customers_Invoices|FR:Factures_Clients|ES:Facturas_a_clientes";
llxHeader('', $title, $helpurl);

$object = new Facture($db);
$object->fetch($id, $ref);
$object->fetch_thirdparty();
```

**Comment by atm-maxime** [comment]
Hi ! Thanks for reporting. I just checked on the v13.0.5 (last commit from github) and it seems to be fixed. I think such a big issue has been quickly solved. If it's ok for you, you can close the issue.

**Comment by l00ptr** [comment]
Hi @atm-maxime,

we can close this issue.

Best regards,
J
