### ISSUE TITLE
modPaymentByBankTransfer - Permission Error

### ISSUE THREAD

**Issue by dreamtim** [Dolibarr/dolibarr#19513]
# Bug

Attempt to use the core banktransfer module to generate SEPA transfer from supplier invoices raise a permission error which prevent
to create or view any bank transfer. I did not find prevous issue mentionning this problem.

I made some test to fix the problem : 
1. Attempt to disable reenable faulty module did not fix the problem
2. Attempt to remove / reallow permission to the user did not fix the problem
3. Switching to superadmin and other allowed users did not fix the  problem is encountered 

## Environment
- **Version**: 14.0.2 
- **OS**: Linux h2web62 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64
- **Web server**: Apache
- **PHP**: 7.4.25
- **Database**: mysqli 5.6.50-log (mysqlnd 7.4.25)
- **URL(s)**: /compta/prelevement/rejets.php?type=bank-transfer&mainmenu=bank

## Expected and actual behavior
* **Expected** : when an allowed user for bankTransfert module attempt to create a new bank transfer the creation form displays
* **Actual** : when an allowed user for bankTransfert module attempt to create a new bank transfer a **Access Denied Message** raises

## Steps to reproduce the behavior
1. Enable module modPaymentByBankTransfer
2. Give Explicit permission to user
2. Open page Bank
3. Click on Bank Transfert
4. Attempt to create new bank transfer

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![image](https://user-images.githubusercontent.com/5686233/143866204-a3c25be6-6e1b-4f97-9433-3a470e9c6a8d.png)

**Comment by aspangaro** [comment]
Problem solved in a more recent version. Move to Dolibarr v14.0.5

**Comment by dreamtim** [comment]
@aspangaro great thx ! I'll try the update then.
