### ISSUE TITLE
List sorted by ref in adherents module

### ISSUE THREAD

**Issue by pcbleu** [Dolibarr/dolibarr#19537]
see this post "Tri par réf dans liste adhérent"

https://www.dolibarr.fr/forum/t/tri-par-ref-dans-liste-adherent/38454
![image](https://user-images.githubusercontent.com/29097943/144382602-e918ef5f-8f53-4355-a08f-3b5d1d46e822.png)

**Comment by jocker132** [comment]
Not reproducible on V 12.0.5 since same as 13.0.

**Comment by daraelmin** [comment]
hi @pcbleu ,
I'm working on a workaround this problem. Could you test the proposition (not in prod cause it may change some datas).
Ths

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by pcbleu** [comment]
Hello

in v18.0.1 this part of code is identical with v14

**Comment by daraelmin** [comment]
The issue is not corrected in v18.0.2. 
The sort order is string based but ref are integer.
A very simple work around is to add the rowid as a column in the list.

cheers


![Screenshot_20231018-214806230 (1)](https://github.com/Dolibarr/dolibarr/assets/8067223/1059e619-c9a2-4374-bfe6-244308714f3b)
