### ISSUE TITLE
Spelling mistake (French version)

### ISSUE THREAD

**Issue by 24Lucas** [Dolibarr/dolibarr#19551]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
In the French version, on the public interface for signing quotes, there is written: "Proposition déjà accetpée" while there should be written: "Proposition déjà acceptée"

## Environment
- **Version**: 15.0.0-alpha
- **OS**: Linux VPS
- **Web server**: 
- **PHP**: 8.0
- **Database**:DATABASE
- **URL(s)**: /public/onlinesign/

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Thanks for reporting. Translations are managed on transifex, you can contribute there 😉

**Comment by atm-maxime** [comment]
I just changed the translation on transifex, I close this issue
https://www.transifex.com/dolibarr-association/dolibarr/translate/#fr_FR/propal/337825890?q=translation_text%3Ad%C3%A9j%C3%A0
