### ISSUE TITLE
Transifex links for Translation assistance not properly working

### ISSUE THREAD

**Issue by Basti-Fantasti** [Dolibarr/dolibarr#19565]
# Bug
Link to transifex in Translations is not working. The dolibarr project is not found

## Environment
- **Version**: 14.0.3

## Expected and actual behavior

When clicking on the box next to a not translated item to open it externally to help the project, the link itself is working, but the dolibarr project is not found

## Steps to reproduce the behavior
Click on Icon next to untranslated text item in Settings > Translations

**Comment by atm-maxime** [comment]
Hi ! Thanks for reporting. Can you provide a screenshot please ? I don't see where the "box next to a not translated item" is.

**Comment by Basti-Fantasti** [comment]
Hi,

yes sure.

Here's the screenshot with the buttons marked beautifully red on the right side :smile: :

![Bildschirmfoto vom 2021-12-29 13-54-38](https://user-images.githubusercontent.com/1663072/147672502-b37f9849-4891-493c-96b7-4b266d579bfc.png)

**Comment by atm-maxime** [comment]
Ok you must have an option to show this, I'll look into it. Thanks for the beautiful screenshot ☺️

**Comment by Basti-Fantasti** [comment]
you're welcome 😁 
just let me know if you need any further details.

Thanks for your support!
