### ISSUE TITLE
Bug : Erreur dans les substitutions lors de l'envoi de mail en masse 

### ISSUE THREAD

**Issue by atm-adrien** [Dolibarr/dolibarr#19562]
## Bug : Erreur dans les substitutions lors de l'envoi de mail en masse 

Lors de l’envoi d'email en masse (depuis la liste des factures par exemple), il semble que certaines clés de substitutions définies dans les modèles de courriels n'apparaissent pas comme elles le devraient ("__TOTAL_HT__" par exemple).

En effet, lors de l'action "presend", nous passons dans le fichier "massactions_pre.tpl.php" et exécutons la fonction getCommonSubstitutionArray qui est censée définir la valeur des clés de substitutions présentes dans le modèle de courriel (durant l'action "confirm_presend" pour la massaction). 
A ce moment là (toujours dans la massaction "presend"), nous ne parcourons pas les factures sélectionnées et leurs valeurs. 
Par conséquent la fonction getCommonSubstitutionArray défini la valeur des clés de substitutions à partir d'un objet "facture" vide. Or, les valeurs vides (null) ne sont pas prise en compte, ainsi la plupart des clefs de substitutions restent telles quelles. 
Les clefs de substitution non "traitées" le sont ensuite lorsque nous parcourons la liste des factures sélectionnées dans le fichier  massactions_pre.inc.php (massaction "confirm_presend").

Néanmoins, dans le fichier "facture.class.php", certaines des valeurs de facture ont une valeur par défaut (par exemple "$total_ht" correspondant à la clé de substitution "__TOTAL_HT__"). 
Par conséquent, lors de la massaction "presend" (n'étant pas censée définir véritablement les valeurs de ces clés de substitution puisque se servant d'une facture vide), des clés de substitutions sont, dans les mails envoyés, remplacées par les valeurs par défaut définies dans la classe de facture. 
Or ces clés de substitutions devraient être remplacé par les valeurs des factures sélectionnées.

Cas de test : 
- Créer un modèle de mail pour facture avec des clés de substitution (la clé "__TOTAL_HT__" est un bon exemple)
- Sélectionner plusieurs factures depuis la liste en se servant des cases à coche sur la droite de la liste
- S'envoyer le mail 

Je vois deux solution pour résoudre cela : 
- Retirer les valeurs par défaut des objets concernés (facture, proposition commerciales...)
- Adapter la fonction getCommonSubstitutionArray, afin qu'elle vérifie l'existence des données avant de définir la valeur de remplacement des clés de substitution. Ainsi, elle ne définira pas des données vides pour valeur.

@eldy savez-vous comment je peux/dois gérer ce problème ?

Je reste à disposition pour tout complément d'information.

**Comment by eldy** [comment]
Thanks for this great analysis of this problem.
I took the direction to remove default value. However this may have some side effect somewhere else. So i started this work into develop for v15.
