### ISSUE TITLE
Cors Error when using Javascipt Axios to call the REST API

### ISSUE THREAD

**Issue by ThcDelux3** [Dolibarr/dolibarr#19572]
# Bug
Cors Error when using Javscrtipt axios calls to get data from the API

## Environment
- **Version**: 14.0
- **OS**:  Ubuntu 20.04
- **Web server**: Apache
- **PHP**:  7.4
- **Database**:  MariaDB
- **URL(s)**:  /api/index.php/login

## Expected and actual behaviour
Expected:
Call the API and get the response.

actual behaviour
cors error

## Steps to reproduce the behaviour
[*Verbose description*]
Activate the REST API in the module Section
Create a Javascript Axios request to the API

**Comment by eldy** [comment]
Do you still have trouble if you set 
API_DISABLE_COMPRESSION to 1 into home - setup - other ?

**Comment by ThcDelux3** [comment]
I reinstalled dolibarr completly fresh. Only activated the API module.

Sadly yes the cors error still occurs.

even when using fetch instead of axios:

    await fetch('https://dolibarr.rr.business/api/index.php/login?login=*username*&password=*pass*, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'DOLAPIKEY': '*apikey*'
      }
    });

demo axios code:

    this.$axios({
      method: "get",
      url: "https://dolibarr.rr.business/api/index.php/login/",
      data:{
        login: "*username*",
        password: "*pass*",
      }
    });


I added API_DISABLE_COMPRESSION but did not change anything.
![image](https://user-images.githubusercontent.com/25651512/146690269-24f8a208-a2af-44cd-b051-3e6202aec326.png)

In the browser or postman everything works as expected.
![image](https://user-images.githubusercontent.com/25651512/146689814-93edf295-5a1f-4416-95f3-c0cde28b8684.png)

postman
![image](https://user-images.githubusercontent.com/25651512/146690171-ad978744-b665-4aac-95a4-5fdf7f23c8b6.png)

The error I get:
![image](https://user-images.githubusercontent.com/25651512/146690208-52e3f770-cd27-40a5-b322-be3556257bcb.png)

Any Idea?

**Comment by fappels** [comment]
What is your php setting value for 'session.cookie_samesite'?

**Comment by ThcDelux3** [comment]
it says no value. You can check out my phpinfo here:

https://dolibarr.rr.business/phpinfo.php

**Comment by fappels** [comment]
Yes indeed session.cookie_samesite (php 7.3+ build in CSRF protection) not set, so should not be the reason for your trouble.

**Comment by ThcDelux3** [comment]
Any Idea I can create you a test account and send you my js code to test if you want.
