### ISSUE TITLE
Ticket Back to List From Third Party Ticket List Crash

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19589]
# Bug
When you go from a tird party to it's ticket list and after that you go of one of its ticket when you click on the "Back to list for the third-party" or "Back to list" you get the following crash

Το Dolibarr ανίχνευσε τεχνικό σφάλμα.
Αυτές οι πληροφορίες μπορούν να είναι χρήσιμες για διαγνωστικούς σκοπούς (μπορείτε να ορίσετε την επιλογή $ dolibarr_main_prod σε &#39;1&#39; για να καταργήσετε αυτές τις ειδοποιήσεις):
Ημερομηνία: 20211209161946
Dolibarr: 14.0.4 - https://www.dolibarr.org
Επίπεδο δυνατοτήτων: 0
PHP: 7.4.26
Server: Apache
OS: Linux dolibarr.localdomain.gr 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

Αιτηθέν URL: /ticket/list.php?restore_lastsearch_values=1
Referer: https://dolibarr.localdomain.gr/ticket/card.php?id=1159&save_lastsearch_values=1
Menu manager: eldy_menu.php

Ενότητες / Εφαρμογές: user, emailcollector, categorie, propal, contrat, ficheinter, agenda, cron, commande, expensereport, facture, fournisseur, holiday, margin, printing, resource, salaries, service, societe, ticket, ticketfetcher, export, import, mydata, expedition, ticketsup, projet, tax, product, banque, fckeditor
Τύπος διαχειριστή βάσης δεδομένων: mysqli
Σφάλμα στην αίτηση πρόσβασης της τελευταία βάσης δεδομένων: SELECT t.rowid, t.entity, t.ref, t.track_id, t.fk_user_create, t.origin_email, t.subject, t.type_code, t.category_code, t.severity_code, t.timing, t.fk_soc, t.notify_tiers_at_create, t.fk_project, t.datec, t.date_read, t.fk_user_assign, t.date_close, t.tms, t.message, t.email_msgid, t.progress, t.resolution, t.fk_statut, t.import_key FROM llx_ticket as t LEFT JOIN llx_societe as s ON (t.fk_soc = s.rowid) WHERE t.entity IN (1) AND () ORDER BY t.datec DESC LIMIT 26
Επιστρεφόμενος κωδικός για το σφάλμα στην αίτηση πρόσβασης της τελευταίας βάση δεδομένων: DB_ERROR_SYNTAX
Πληροφορίες για το σφάλμα στην αίτηση πρόσβασης της τελευταίας βάση δεδομένων: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') ORDER BY t.datec DESC LIMIT 26' at line 1

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

**Comment by ksar-ksar** [comment]
It's quite strange...

The 'AND ()' is coming from 
`$sql .= natural_search($key, $search[$key], $mode_search);`
Where 
- $key = fk_statut
- $search[$key] = [fk_statut] => Array
        (
        )
- $mode_search = 1

The empty array is coming from `$search[$key] = GETPOST('search_'.$key, 'alpha');
`
And it is crazy because $GET has 
```
Array
(
    [restore_lastsearch_values] => 1
)
```
And $POST has : 
```
Array
(
)
```

So basically we need to update either the `GETPOST `or the `natural_search`

**Comment by VaderD** [comment]
I also forgot to mention that this issue occurs only you are using dolibarr from mobile....(smartphone/tablet) Mine is android
From desktop PC it is ok ! It does not occur ! 

So try it from your mobile phone !

**Comment by ksar-ksar** [comment]
Hello,

For me the BUG is there also on Desktop

**Comment by VaderD** [comment]
Hello,

OK ! You know better ! It is ok !

**Comment by Felix40400** [comment]
I report the same problem on Desktop : #18921

**Comment by VaderD** [comment]
Any news regarding this issue ..?

**Comment by ksar-ksar** [comment]
There is a FIX : #19076
But not integrated on the core yet.
