### ISSUE TITLE
annual periodic event in calendar

### ISSUE THREAD

**Issue by gigarun** [Dolibarr/dolibarr#19591]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request
Hello, the management of periodic calendar events lacks two things:
1- The annual recurrence
2- The possibility of changing the recurrence step (every x years for example for this specific case)
Certainly there is a third-party module to achieve this; but it is absolutely necessary for other external modules that this be integrated natively. asked for v13 and above

## Use case
need to create bi-annual events for periodicals technical intervention on items

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by JoAnMaFe** [comment]
It would be very useful, and much better if it could incorporate a field to specify the pre-warning time and generate some kind of alarm after that time.
