### ISSUE TITLE
Bank Log Issue

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19597]
I get the following error when i try to see the log of a bank enty…I have the neccessary permissions in order to see them…Actually i am the admin…
The same issue is happeing when i login with the admin account

Access denied.
You try to access to a page, area or feature of a disabled module or without being in an authenticated session or that is not allowed to your user.

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]
## Expected and actual behavior
[*Verbose description*]

![1](https://user-images.githubusercontent.com/34111030/145689888-e8beea02-644b-4095-afcc-97e7619512bd.png)

**Comment by ksar-ksar** [comment]
What is the exact URL of the error ?

**Comment by VaderD** [comment]
Hello there,

Here is the url: /compta/bank/info.php?rowid=xxxx

**Comment by ksar-ksar** [comment]
Hello,

I can't reproduce on my setup.
![image](https://user-images.githubusercontent.com/35605507/145815597-d4eb415d-b7b6-4905-bd41-dbf035210d0d.png)

**Comment by VaderD** [comment]
Hello there, 

As i said it works fine from Windows/Desktop/PC ...It occures from mobile...using the interface
Please try it from there !

**Comment by VaderD** [comment]
What is your dolibarr version  you are testing..?

**Comment by ksar-ksar** [comment]
V14.0.4

**Comment by VaderD** [comment]
Is your installation a clean or upgraded installation ..?

**Comment by VaderD** [comment]
Hello there,

Mine is an upgraded version from 7.0.4 to 14.0.4 and then to 14.0.4 ...

Maybe this is the way to find the issue ...

**Comment by ksar-ksar** [comment]
> Is your installation a clean or upgraded installation ..?

It's an upgrade since V3.4

**Comment by VaderD** [comment]
It is an upgrade since 3.6

Well Also in the test installation i have upgraded from the 3.6.0->7.04->14.04 also the issue exist

**Comment by eapcorreo** [comment]
Hi. I have some migrations from 4.x to 14.x with success.
You need migrate one version after the other, delete some files installer points you. (4 to 14 are 10 migrations in the process)
You need PHP 5.6 to get all working form 4.x to 14.x
Later if all ok, you con use PHP 7.x to get all running in production environment.

Hope this helps.
Greetings.

**Comment by VaderD** [comment]
Hello there, 

The upgrade procedure i have followed is the one you mentioned...

**Comment by VaderD** [comment]
It seems that in the 14.0.5 it is fixed !
