### ISSUE TITLE
Multicurrency price on suply orders is false

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#19604]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Order does nit show the correct price defined in currency, but calculate it 

## Environment
- **Version**: 13.0.4
- **OS**: debian
- **Web server**: apache2
- **PHP**: 7.3
- **Database**:mariadb
- **URL(s)**: /fourn/commande/card.php?id=

## Expected and actual behavior
We should get the defined price in currency on the order without calculating it

## Steps to reproduce the behavior
- define a supplier price in a currency : ex 10 USD with a rate 1EUR = 1.1 USD
- Change currency rate to 1.2 (in config or on order) : the rate has changed between the supplyprice definition and the order
- Create an order in currency USD 
- Add this product  to order  unitprice is no more 10 USD but 10.9 (eg  (10 /1.1) * 1.2) 

it should always be 10 USD, only the price in EUR must be calculated 10 / 1.2

With multicurrency, we should provide also the multicurrency_unitprice_ht info and set it in the order addline form
if the form_field multicurrency_unitprice_ht has the right info, it seems to work correctly

**Comment by tiaris** [comment]
the feature is broken in v 14.0 too.

**Comment by torvista** [comment]
related
https://github.com/Dolibarr/dolibarr/issues/9604

**Comment by eldy** [comment]
Can you provide a screenshot of the setup of the supplier price of the product ?
