### ISSUE TITLE
Error when trying to change visibility of an extrafield

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#19602]
# Bug
Dolibarr raise an error when we want to change the value of the 'visibility' of an extrafield

## Environment
- **Version**: 14.0.3
- **OS**: Debian
- **Web server**: Apache2
- **PHP**: 7.3
- **Database**: Postgres 11
- **URL(s)**: https://XXXXXX/compta/facture/admin/facture_cust_extrafields.php?attrname=need_eol_update

## Expected result
We should be able to change the visibility of an attribute from the admin pannel

## Steps to reproduce the behavior
- Create an extrafield with visibility = 1 
- Update the extrafield and set it up to 0 (not visible value)

## Error
ERROR: 42601: syntax error at or near '(' LINE 2: ...facture_extrafields ALTER COLUMN need_eol_update TYPE int(1) ^ LOCATION: scanner_yyerror, scan.l:1133

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![Configuration_du_module_Factures](https://user-images.githubusercontent.com/26635105/145815961-66d00dbf-35bd-4d8b-ac14-50745e2db2d2.png)

![Cursor_et_Configuration_du_module_Factures](https://user-images.githubusercontent.com/26635105/145815803-ed6ac14a-ec8c-44ca-9f0c-01543f49165d.png)

## Impact
Medium

## Workarround 
Set the right visibility on create

**Comment by ksar-ksar** [comment]
Hello,

Please remove your Dolibarr URL, and put something like https://xxxxxxxxxxxxx.com/compta/facture/admin/facture_cust_extrafields.php?attrname=need_eol_update

I can't reproduce that with MYSQL, so it is most probably something related to postgresql.
Can you activate the logs, reproduce the fault and post them here ?

Thanks.

**Comment by daxitsolutions** [comment]
Dear @ksar-ksar 

1) URL has been updated
2) please find the Dolibar log related to this isussue 👍 

```
2021-12-14 21:21:21 ERR     91.181.168.15   DoliDBPgsql::query SQL Error query: -- ALTER TABLE llx_societe_extrafields MODIFY COLUMN need_eol_update int(1) DEFAULT 1 replaced by --
ALTER TABLE llx_societe_extrafields ALTER COLUMN need_eol_update TYPE int(1)
2021-12-14 21:21:21 ERR     91.181.168.15   DoliDBPgsql::query SQL Error message: ERROR:  42601: syntax error at or near "("
LINE 2: ...societe_extrafields ALTER COLUMN need_eol_update TYPE int(1)
                                                                    ^
LOCATION:  scanner_yyerror, scan.l:1133 (DB_ERROR_SYNTAX)
2021-12-14 21:21:21 ERR     91.181.168.15   DoliDBPgsql::query SQL Error usesavepoint = 0
```

Same error applied to any extrafield on any master objects (tiers, facture, ..)
