### ISSUE TITLE
Public and private notes on SERVICES modulo

### ISSUE THREAD

**Issue by rpgiraldez** [Dolibarr/dolibarr#19606]
There's no way to delete or edit private ou public notes on services already created.

Version: 14.0.4 (Linux)

STEPS:
1 - Goto Services menu
2 - Create a new service and ADD notes.
3 - Try to edit this service, click on NOTES and there's no ICON (as 14.0.3) to edit notes (see attached files).

Thank You !!

![Captura de Tela 2021-12-13 às 14 44 30](https://user-images.githubusercontent.com/22435717/145862177-84d50457-81c9-47cb-a4cf-f01d4da21eb3.png)

**Comment by ksar-ksar** [comment]
Hello,

Strange, work for me : 
![image](https://user-images.githubusercontent.com/35605507/145972595-7a488361-1441-4342-9c12-0cc17b720410.png)

**Comment by rpgiraldez** [comment]
Hello.
Can you try enabling only SERVICES modules, please?

**Comment by rpgiraldez** [comment]
Hello.
**This error is in version 14.0.4**
Version 14.0.3 is OK.

**Comment by ksar-ksar** [comment]
I'm in V14.0.4 and it is working

**Comment by rpgiraldez** [comment]
Try to disable PRODUCTS module, please.
I think that's the bug.
The note edit button only appears on services IF products module is activated.

**Comment by ksar-ksar** [comment]
> Try to disable PRODUCTS module, please. I think that's the bug. The note edit button only appears on services IF products module is activated.

Still working with product module disabled : 
![image](https://user-images.githubusercontent.com/35605507/146375283-dbb1bb06-7e72-4805-8d50-7d3cd4317c18.png)
