### ISSUE TITLE
Update status change in contact form

### ISSUE THREAD

**Issue by jurijacalinovic** [Dolibarr/dolibarr#19617]
* Sorry for my poor english...
# Feature Request
When a company state is updated (Open/Closed), the state of the contacts of this company do not change.
I think, in my usual use, state of contacts has to change in the same time, by default.

I think, if the company is "desactived", his contacts has to been so....

Same issue in all versions in use for me :
8.xx -> 14.xx

**Comment by 1ocate** [comment]
Hi need version information

**Comment by jurijacalinovic** [comment]
I extend the request :
It is not possible to change the state of a contact card...
There is the tag in the card, but it I did not see how to change it...

I don't want to delete "unactive" contacts, I'd like it be possible to use and change his state "Open" to "Close".
