### ISSUE TITLE
Developper wanted page on dolibarr.org and/or dolistor and/or doli-forum

### ISSUE THREAD

**Issue by daraelmin** [Dolibarr/dolibarr#19625]
# Feature Request

it would be interesting to centralize on the dolibarr.org platform a developer research announcement page for a specific module

## Use case

When a user or company is looking for a developer, he can only post his ad on forums where there are no specific categories to do so.

Likewise, when a freelance developer is looking for work, he cannot verify if someone needs him.

## Suggested implementation
Add a new forum *Developpeur Wanted* or *Looking for a developer* on **dolibarr.org**.

**Comment by daraelmin** [comment]
Similar to https://github.com/Dolibarr/dolibarr/issues/18082#issuecomment-1048918130

**Comment by atm-maxime** [comment]
A good idea but as always, who will manage these ads ? I'll bring the subject to the board
