### ISSUE TITLE
Do not have all authorizations for inventory

### ISSUE THREAD

**Issue by Felix40400** [Dolibarr/dolibarr#19627]
# Bug
[*Do not have all authorizations for inventory*]

## Environment
- **Initial Version**: [*10.0.3*]
- **Current Version**: [*14.0.4*]
- **OS**: [*Linux server 4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 x86_64*]
- **Web server**: [*Apache/2.4.29 (Ubuntu)*]
- **PHP**: [*7.3.33-1+ubuntu18*]
- **Database**: [*MySQL or MariaDB 5.7.36-0ubuntu0.18.04.1*]
- **URL(s)**: [*http://****/htdocs/product/inventory/card.php?id=1&action=delete&token=61bf49c1397938d6c8718c63a990a594*]

## Expected and actual behavior
[*When creating inventory, it is impossible to delete them and validate the stock movements. There is no pagination, the page loads 6000 references. And Dolibarr does not offer me all the permissions related to the module.*]

## Steps to reproduce the behavior
[*Delete or validation*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*
![error inventory](https://user-images.githubusercontent.com/80969508/146176814-4c6dd68f-bc7a-4a18-a213-e8aec3d3a38b.png)
*]

**Comment by eldy** [comment]
Can't reproduce on develop. Thanks to test again once v15 has been released.

**Comment by Felix40400** [comment]
Hi @eldy, I can't reproduce the bug on a new installation. I think it comes from having made the updates since version 10. All of my updates have installed well.
