### ISSUE TITLE
Vendor invoice : Invalid Remaining unpaid

### ISSUE THREAD

**Issue by seblu** [Dolibarr/dolibarr#19631]
# Bug
In the **Vendor invoice** module (`/fourn/facture/card.php`), the computed value of **Remaining unpaid** is incorrect. The value is not the difference between the **billed** value and the **amount** value. This difference is the value of the *credit note*. 

![Screenshot_20211215_165331](https://user-images.githubusercontent.com/615816/146269580-f43de1c4-a645-4a25-a242-4ee21a803319.jpg)

## Environment
- **Version**: 14.0.4
- **OS**: Ubuntu 20.04
- **Web server**: apache 2.4
- **PHP**: 7.4
- **Database**: mariadb 10.3

## Expected and actual behavior
- **Remaining unpaid** should be the difference between **billed** and **amount**. 0 is our case.

**Comment by seblu** [comment]
**Remaining unpaid** is also incorrect without **credit note** but when the **Recalculate** feature is used to compute another tax rounding.

![Screenshot_20211215_235626](https://user-images.githubusercontent.com/615816/146278812-c384cce9-ce85-4f4b-95ec-d047803c19c8.jpg)

![Screenshot_20211216_001107](https://user-images.githubusercontent.com/615816/146279493-3b16da25-6934-4bd7-9d7c-a5ea58ab20d6.jpg)

**Comment by seblu** [comment]
Please note, when `Classify automatically all standard, down payment or replacement invoices as "Paid" when payment is done entirely` is checked in the payment form (`/fourn/facture/paiement.php`), the **Remaining Unpaid** is correctly set to 0 and the invoice is closed as paid.

**Comment by seblu** [comment]
I confirm it is still present on latest stable version

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by michalhana99** [comment]
unfortunately even in version 18.0.3 this problem persists, when will this error be fixed?

**Comment by kkhelifa-opendsi** [comment]
Fixed in develop (version 21)

Mode 1:
![image](https://github.com/user-attachments/assets/3f353caa-61ac-47ab-955b-6fa48cb3c552)
Mode 2:
![image](https://github.com/user-attachments/assets/4deceb51-834d-4290-a960-0ec4f18d4aaf)

Mode 1:
![image](https://github.com/user-attachments/assets/d2fddd5a-cacf-49d8-ad22-7bb81866b9f6)
Mode 2:
![image](https://github.com/user-attachments/assets/be15d7fe-d79a-407b-a0bc-9e50c6f80bea)
