### ISSUE TITLE
Yearly statistics shown in /compta/facture/stats/index.php should not include invoices in draft state

### ISSUE THREAD

**Issue by joanahead** [Dolibarr/dolibarr#19632]
# Bug
When navigating to /compta/facture/stats/index.php you can see a table (and graphics) with per-year statistics (number of invoices, total amount invoiced, etc.). Those table/graphs include invoices in draft status without stating it in any visible way, which is a bit dangerous.
It should probably only include invoices in a valid state.

## Environment
- **Version**: 14.0.3
- **OS**: Linux Centos (although it is irrelevant)
- **Web server**: Apache (although it is irrelevant)
- **PHP**: 7.4 (although it is irrelevant)
- **Database**: MySQL 8 (although it is irrelevant)
- **URL(s)**: /compta/facture/stats/index.php

## Expected and actual behavior
Calculations should not include invoices in draft state. Maybe it should avoid some other special state... don't know for sure, but it should be consequent with the accounting, and draft invoices are not included for tax calculations for example.

## Steps to reproduce the behavior
Just navigate to /compta/facture/stats/index.php

**Comment by jocker132** [comment]
I think that those tables and graph are use to retrieve all type of onvoices in begining not only the paid/unpaid ones. 

But as you can check below, you can use the paid/unpaid value on Status filter to check only the paid / unpaid invoices
![image](https://user-images.githubusercontent.com/28537382/146693330-82d8cab5-8dd5-418e-a12c-c2c3076dcfd0.png)

**Comment by joanahead** [comment]
Did not think about that selector.
Don't you think that "Not paid / Paid" should be selected by default? otherwise someone could misinterpret (it was our case) the information thinking that those are the real taxable invoiced amounts.

**Comment by OlivdeLab** [comment]
> I think that those tables and graph are use to retrieve all type of onvoices in begining not only the paid/unpaid ones.
> 
> But as you can check below, you can use the paid/unpaid value on Status filter to check only the paid / unpaid invoices ![image](https://user-images.githubusercontent.com/28537382/146693330-82d8cab5-8dd5-418e-a12c-c2c3076dcfd0.png)

Thank, you issue closed
