### ISSUE TITLE
Update from 13.0.* to 14.0.* prevent Swagger API explorer to load (Compression Issue)

### ISSUE THREAD

**Issue by dreamtim** [Dolibarr/dolibarr#19639]
# Bug

Update from 13.0.4 to 14.0.1+ prevent the Swagger API explorer to load on my installation of dolibarr

## Environment
- **Host** : Infomaniak 
- **Version**: 14.0.1, 14.0.2, 14.0.3
- **OS**: Linux h2web62 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64
- **Web server**: Apache2
- **PHP**: 7.4
- **Database**: mysqli (mysqlnd 7.4.26)
- **URL(s)**: 
      - /api/index.php/explorer/
      - - /api/index.php/login

## Expected and actual behavior

**Expected** :  Opening API uri /api/index.php/explorer/ return valid and compressed json returned and Swagger UI loaded

**Actual** :  Opening API uri /api/index.php/explorer/ return valid and **_uncompressed_** json raising an error `" Can't read from server. It may not have the appropriate access-control-origin settings."`

**Comments** :

- It seems to be due to a compression issue : the header of the json file indicates the json is compressed and it is not the case. 
- Adding `API_DISABLE_COMPRESSION=1` parameter (introduced in 69d57f48fd20c0bb6d6ec59581523d9731cf2c83 )  global config solve the problem.

## Steps to reproduce the behavior
- Update from 13.0.* to 14.0.* 
- Open API uri /api/index.php/explorer/

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![image](https://user-images.githubusercontent.com/5686233/146361157-f5f8ce7e-6c2c-411e-9efb-fbef9cc1c9a6.png)

**Comment by eldy** [comment]
Do you know if at least one of the 3 method is available on your PHP ?
brotli_compress
bzcompress
gzencode

**Comment by dreamtim** [comment]
2 methods are available according to my check using php `function_exists` : 
* brotli_compress --> unavailable
* bzcompress  --> available
* gzencode --> available
