### ISSUE TITLE
Cannot change self password in /user/card.php if only "Change self password" permission is set

### ISSUE THREAD

**Issue by joanahead** [Dolibarr/dolibarr#19638]
# Bug
If users are configured with "change self password" permission and not "change other users' passwords" then no one can change its own password.

## Environment
- **Version**: 14.0.3
- **OS**: Ubuntu Centos (although it's irrelevant)
- **Web server**: Apache (irrelevant)
- **PHP**: 7.4 (irrelevant)
- **Database**: MySQL 8 (irrelevant)
- **URL(s)**: /user/card.php

## Expected and actual behavior
User should go to /user/card.php and be able to change own password.

## Steps to reproduce the behavior
Just go to /user/card.php and no button for password change.
User must be configured with "change self password" permission and not the "change other users' passwords" permission though.

## Solution proposal
in /user/card.php I changed line 1858 from this
`					} elseif (($user->id != $id && $caneditpassword) && $object->login && !$object->ldap_sid &&`
to this
`					} elseif (($user->id == $id && $caneditpassword) && $object->login && !$object->ldap_sid &&`
because it made no sense trying to allow the change of the own password but checking that $user->id is different from $id, because in that case you would be opening another users' card.

**Comment by eldy** [comment]
i think the replacement should be into 
`} elseif ($caneditpassword && $object->login && !$object->ldap_sid &&`
so no test on user because it is alreaydy included into the set of $caneditpassword
If you change the test as suggested, it won't be possible for people with permission to edit all pass to do it for other users. Thanks to confirm
