### ISSUE TITLE
Changing the name order for a thirdparty from a member.

### ISSUE THREAD

**Issue by Guerno** [Dolibarr/dolibarr#19648]
# Instructions
When creating a third party from a member, I think it would be better to use the last name first and then the first name after.

In fact, when the third party's accounting account number is subsequently created with the DIGITARIA tool, we will find ourselves less often with duplicates.

## Suggested implementation
I think the changes are very simple in the file:
htdocs/adherents/card.php
* line 596: replace: $fullname = $object->getFullName($langs);
  * by: $fullname = $object->lastname.' '.$object->firstname;
* line 1476: replace: $fullname = $object->getFullName($langs);
  * by: $fullname = $object->lastname.' '.$object->firstname;

---
I'm not comfortable with GitHib, hope to do things the right way.
cordially.

**Comment by daraelmin** [comment]
There is already an option to decide the common order of firstname/lastname (into home - setup - display).
