### ISSUE TITLE
Statistique correspondant aux dates d'exercices (Statistics corresponding to the exercise dates)

### ISSUE THREAD

**Issue by Cyril35** [Dolibarr/dolibarr#19646]
Bonjour,
Comme vous le savez, toutes les entreprises ne commencent pas leur exercice au 1er janvier.
il serait intéressant que les statistiques puissent soit être calculées annuellement (comme c'est le cas actuellement) soit sur les dates d'exercices.

Vous adorez l'anglais (pas moi, mais je vais faire un effort (enfin Google le fait pour moi))

Hello
As you know, not all businesses start their fiscal year on January 1.
it would be interesting for the statistics to be calculated annually (as is currently the case) or on the exercise dates.

**Comment by jocker132** [comment]
Bonjour,

Donc vous souhaitez que les statistiques puissent être calculées sur une année glissante ?

Dear,

Do you want to compute the statistics on a rolling year ?

**Comment by Cyril35** [comment]
Bonjour, 
effectivement sur une année glissante ça répond à tous les cas de figure.

Hello,
indeed over a sliding year, it meets all the scenarios.

**Comment by jocker132** [comment]
Est ce qu'on peut fonctionnellement utiliser le premier du Mois de début d'exercice paramétrable au niveau de la fiche signalétique configuration >> Société/Organisation afin de calculer le début de l’année glissante pour les statistiques ?

![image](https://user-images.githubusercontent.com/28537382/146831129-2f2bfd20-0fc2-48bc-b5b0-92e5445aad3d.png)


Can we use Starting month of the fiscal year under Setup>> Company/Organization to calculate the starting of the rolling year for statistics screen.

**Comment by Cyril35** [comment]
Yess you can

**Comment by josett225** [comment]
In my opinion, there is still a need to at least add this feature of taking care of the fiscal year and also to add a start date and end date with a custom filter that could be used on any statistics. 
Thoughts?
