### ISSUE TITLE
Re-calculation method 2 goes wrong

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#19643]
# Bug
Recalculation supplier-invoices goes wrong

## Environment
- **Version**: 14.0.4

## Expected and actual behavior
When you choose te do an re-calculation on in suppliers invoice the "still to Pay" does not change.

Make an suppliers invoice, choose: Recalculation methode 2

![recalculation](https://user-images.githubusercontent.com/43514101/146516413-10d4f131-282d-46cb-b00b-1dbd91b3b3d9.png)

**Comment by eldy** [comment]
Can you also paste screenshot after clicking on method 1 ?
Also after having clicking on method 2, what if you recall the page of invoice ?

**Comment by KlaasOl** [comment]
![afbeelding](https://user-images.githubusercontent.com/43514101/146734363-8a3d25b5-31af-4143-a642-1e574eb89aed.png)

After clicking on Method 1, nothing changed. 
It is an complex invoice of 14 lines with each item up to three decimals.
I did not have this problem on previous versions.

**Comment by KlaasOl** [comment]
It seems that it has to do with items of more than two decimals. I also have it on a invoice with only one item.

**Comment by KlaasOl** [comment]
Solved in update 14.0.5
