### ISSUE TITLE
Régression aperçus dans les listes

### ISSUE THREAD

**Issue by webolabo** [Dolibarr/dolibarr#19659]
Bonjour,
Je viens de migrer de la 11 à la 14 et là je trouve une régression dans les listes des factures par exemple
Avant on pouvait voir et télécharger tous les pdf générés d'une facture sans cliquer sur le lien de la facture or maintenant le bouton de l'aperçu n’apparaît sur la liste que lorsqu'il y a un PDF avec un nom qui contient juste le numéro de la facture mais pas des autres pdf nommés différemment 
 (Voir capture)
https://ibb.co/bXLZHJY

**Comment by ksar-ksar** [comment]
Hello,

In English, please ?

**Comment by atm-maxime** [comment]
I tried on a v11 and the only way to have several PDF available from the list is when the other files are named with the invoice ref immediately followed by "_". Seems to me that this was a bug and it has been fixed in v14
