### ISSUE TITLE
Cannot grant user privileges on dolibarr database when using MySQL 8

### ISSUE THREAD

**Issue by antoineguichard** [Dolibarr/dolibarr#19662]
# Bug
When using MySQL 8.0, Dolibarr install scripts cannot grant the dolibarr user the privileges it needs on the dolibarr database 

## Environment
- **Version**: 14.0.4
- **OS**: Ubuntu 20.04
- **Web server**: Apache 2.4.41
- **PHP**: 7.4.3
- **Database**: MySQL 8.0.19
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
After filling in database name and database user credentials in the web-based installer and selecting "Create database" and "Create user account or grant user account permission on the Dolibarr database", the installer should do that -  "Create database" and "Create user account or grant user account permission on the Dolibarr database".

Instead, it returns the error:

> Creation user : dolibarr	Error: DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'dolibarr007'' at line 1. Connected user not allowed to GRANT ALL PRIVILEGES ON dolibarr.* TO 'dolibarr'@'localhost' IDENTIFIED BY '*****'

## Reasons

In MySQL 8.0, you can no longer create a user and grant privileges all within the same command. The user needs to be created first, then privileges can be granted to that user.

In MySQL 5.7, you could do both in one step, which is what Dolibarr is trying to do here (in dolibarr/htdocs/core/db/mysqli.class.php):
```
mysql> GRANT ALL PRIVILEGES ON dolibarr.* TO 'dolibarr-user'@'localhost' IDENTIFIED BY 'dolibar-user-password';
```

In MySQL 8.0, you have to do it in two steps:
```
mysql> CREATE USER 'dolibarr-user'@'localhost' IDENTIFIED BY 'dolibar-user-password';
mysql> GRANT ALL ON dolibarr.* TO 'dolibarr-user'@'localhost';
```
See:
[Grant command in MySQL 8.0](https://dev.mysql.com/doc/refman/8.0/en/grant.html)
[Grant command in MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/grant.html)

## Fix

The current code (in dolibarr/htdocs/core/db/mysqli.class.php) first creates the user, but without allocating it a password (lines 942 and 955) then uses the now deprecated grant syntax to grant privileges and allocate password at the same time (line 958). Line 962 then provides an error code corresponding to the command in line 958, in case that command fails.

What we need is to first create the user, allocating it a password straight away, then grant the user privileges on the database. 

I tried the the following changes to lines 942, 955, 958 and 962:

### Line 942
Replace
`$sql = "CREATE USER '".$this->escape($dolibarr_main_db_user)."'";`
by
`$sql = "CREATE USER '".$this->escape($dolibarr_main_db_user)."'@'".$this->escape($dolibarr_main_db_host)."' IDENTIFIED BY '".$this->escape($dolibarr_main_db_pass)."'";`

### Line 955
Replace
`$sql = "CREATE USER '".$this->escape($dolibarr_main_db_user)."'@'localhost'";`
by
`$sql = "CREATE USER '".$this->escape($dolibarr_main_db_user)."'@'".$this->escape($dolibarr_main_db_host)."' IDENTIFIED BY '".$this->escape($dolibarr_main_db_pass)."'";`

### Line 958
Replace
`$sql = "GRANT ALL PRIVILEGES ON ".$this->escape($dolibarr_main_db_name).".* TO '".$this->escape($dolibarr_main_db_user)."'@'".$this->escape($dolibarr_main_db_host)."' IDENTIFIED BY '".$this->escape($dolibarr_main_db_pass)."'";`
by
`$sql = "GRANT ALL PRIVILEGES ON ".$this->escape($dolibarr_main_db_name).".* TO '".$this->escape($dolibarr_main_db_user)."'@'".$this->escape($dolibarr_main_db_host)."'";`

### Line 962
Replace
`$this->error = "Connected user not allowed to GRANT ALL PRIVILEGES ON ".$this->escape($dolibarr_main_db_name).".* TO '".$this->escape($dolibarr_main_db_user)."'@'".$this->escape($dolibarr_main_db_host)."'  IDENTIFIED BY '*****'";`
by
`$this->error = "Connected user not allowed to GRANT ALL PRIVILEGES ON ".$this->escape($dolibarr_main_db_name).".* TO '".$this->escape($dolibarr_main_db_user)."'@'".$this->escape($dolibarr_main_db_host)."'";`

I tried that change twice on two different virtual machines running MySQL 8.0, and it worked fine.
I have not tried it with MySQL 5.7 though.

**Comment by atm-maxime** [comment]
Hi ! Thanks for reporting this. I made the pull request with your changes, but first I need you to check what I did and check that this changes are still working with mysql 5.1 as this is the lower supported mysql version for Dolibarr 14.0 (see https://wiki.dolibarr.org/index.php/Releases)

**Comment by antoineguichard** [comment]
Hi. I confirm that the pull request (the file shown at https://github.com/atm-maxime/dolibarr/blob/706ee8ce6236e3de47a3b148a0bed57706ae170b/htdocs/core/db/mysqli.class.php) corresponds to the modified code I have tested and works in MySQL 8.0.
```
diff -us mysqli.class.php__ag-modified-2021-12-20 mysqli.class.php__atm-maxime-pull-request-2021-12-28 
Files mysqli.class.php__ag-modified-2021-12-20 and mysqli.class.php__atm-maxime-pull-request-2021-12-28 are identical
```
I'll have a look at MySQL 5.1.

**Comment by antoineguichard** [comment]
# Checking if it works in MySQL 5.1

I have not (yet?) been able to do a full functional test, as I have not managed to set up a Virtual Machine (VM) with MySQL 5.1 and a PHP version supported by Dolibarr 14

## setting up a VM with MySQL 5.1 ... but with PHP 5.2

I have set up a VM with Ubuntu Server 9.10 (Karmic), which has MySQL 5.1.

But it has PHP 5.2, and Dolibarr 14 only supports PHP 5.6 to 7.4.

I tried to upgrade PHP on the VM but have failed to find a suitable repository or private ppa for Karmic. Not sure if and how I can solve that.

I tried anyway to run a Dolibarr 14.0.4 install on the VM as it was, but as soon as I direct my browser to dolibarr/htdocs/, I get a PHP error:
```
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /var/www/dolibarr/htdocs/main.inc.php on line 2856
```
So I cannot get to the step where I can check that the new code works.

## checking MySQL 5.1 documentation for syntax

The documentation for CREATE USER and GRANT indicates that the syntax we are using is valid in MySQL 5.1, eg:

> CREATE USER 'jeffrey'@'localhost' IDENTIFIED BY 'mypass';

> GRANT ALL PRIVILEGES ON mydb.* TO 'someuser'@'somehost';

("GRANT ALL" and "GRANT ALL PRIVILEGES" are equivalent, noted "GRANT ALL [PRIVILEGES]" in the documentation)

Documentation links:

- for CREATE USER: https://docs.oracle.com/cd/E19078-01/mysql/mysql-refman-5.1/sql-syntax.html#create-user

- for GRANT: https://docs.oracle.com/cd/E19078-01/mysql/mysql-refman-5.1/sql-syntax.html#grant

## checking dolibarr db and user creation on the command line in MySQL 5.1

In my VM, I checked manually on the command line the syntax used in the modified code, and it worked:

```
$ mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 35
Server version: 5.1.37-1ubuntu5 (Ubuntu)

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select version(); show databases; select user, host from mysql.user;
+-----------------+
| version()       |
+-----------------+
| 5.1.37-1ubuntu5 | 
+-----------------+
1 row in set (0.00 sec)

+--------------------+
| Database           |
+--------------------+
| information_schema | 
| mysql              | 
+--------------------+
2 rows in set (0.00 sec)

+------------------+------------+
| user             | host       |
+------------------+------------+
| root             | 127.0.0.1  | 
| debian-sys-maint | localhost  | 
| root             | localhost  | 
| root             | ubuntu0910 | 
+------------------+------------+
4 rows in set (0.00 sec)

mysql> create database dolibarr_db;
Query OK, 1 row affected (0.00 sec)

mysql> create user 'dolibarr_user'@'localhost' identified by 'dolibarr_pwd';
Query OK, 0 rows affected (0.00 sec)

mysql> grant all privileges on dolibarr_db.* to 'dolibarr_user'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql> show databases; select user, host from mysql.user;
+--------------------+
| Database           |
+--------------------+
| information_schema | 
| dolibarr_db        | 
| mysql              | 
+--------------------+
3 rows in set (0.00 sec)

+------------------+------------+
| user             | host       |
+------------------+------------+
| root             | 127.0.0.1  | 
| debian-sys-maint | localhost  | 
| dolibarr_user    | localhost  | 
| root             | localhost  | 
| root             | ubuntu0910 | 
+------------------+------------+
5 rows in set (0.00 sec)

mysql> show grants for 'dolibarr_user'@'localhost';
+----------------------------------------------------------------------------------------------------------------------+
| Grants for dolibarr_user@localhost                                                                                   |
+----------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'dolibarr_user'@'localhost' IDENTIFIED BY PASSWORD '*C46B3A906C36942803D74D862A4408772DE3B253' | 
| GRANT ALL PRIVILEGES ON `dolibarr_db`.* TO 'dolibarr_user'@'localhost'                                               | 
+----------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> 
```

**Comment by papoteur-mga** [comment]
Similar problem with MariaDB : #19842
This present commit would probably fix also the bug.
