### ISSUE TITLE
bank entries search result

### ISSUE THREAD

**Issue by hatted** [Dolibarr/dolibarr#19667]
If I search a Third-party/User in the bank entries, all the results are duplicate 3 times.
/compta/bank/bankentries_list.php

![Screenshot 2021-12-21 at 17 31 53](https://user-images.githubusercontent.com/5671197/146906349-2d04115e-c7d7-45cc-adc8-1f94ac53ae14.png)

**Comment by ksar-ksar** [comment]
Hello,

Confirmed on a V14.0.4
compta/bank/bankentries_list.php

Everything is multiplied by the bank accounts number (4 in my case)
![image](https://user-images.githubusercontent.com/35605507/146923148-4644e879-fde9-43b0-b45c-8058e9d0583f.png)

**Comment by jocker132** [comment]
Not reproducible on version 12.0.5.

![image](https://user-images.githubusercontent.com/28537382/147387347-d7742deb-3656-41bc-bac2-742cfaac9c78.png)

@hatted 
Please which version are you using of Dolibarr ?

**Comment by atm-maxime** [comment]
as @ksar-ksar says, I can reproduce from v14. I'll look into it
