### ISSUE TITLE
Nom alternatif dans liste factures V14.0.4

### ISSUE THREAD

**Issue by webolabo** [Dolibarr/dolibarr#19660]
# Bug
Nom alternatif liste factures V14.0.4

## Environment
- **Version**: V14.0.4

## Expected and actual behavior
Affichage du nom alternatif dans la colonne de la liste des factures (Dans la liste de Propals ça marche très bien)

## Steps to reproduce the behavior
Ajouter colonne nom alternatif dans la liste des factures

**Comment by ksar-ksar** [comment]
Hello,

This seems to be a feature request.
Can you put screenshots and write in English ?

**Comment by Felix40400** [comment]
Have you tried checking the alternate name column in the display selection?

**Comment by webolabo** [comment]
Hello Felix
Thank you very much for your answer 
Yes of course I added Alternate Name and Payment method but both of them are empty (see screenshot) all the rest of columns are OK.
https://ibb.co/RcKfP2B 
![image](https://user-images.githubusercontent.com/13449237/146814189-5aec72c2-2a5b-48d0-a0ec-6e42b8589186.png)

**Comment by webolabo** [comment]
> Hello,
> 
> This seems to be a feature request. Can you put screenshots and write in English ?

Hello Ksar 
I think that it's a bug unfortunately 
Sorry for having used French in my 1st post. I thought Dolibarr was maintained by a french team

**Comment by ksar-ksar** [comment]
Hello,

For payment method, it's working for me in V14.0.4 : 
![image](https://user-images.githubusercontent.com/35605507/146917613-1991c6d6-ffb8-4386-a8c8-337b1ed5ccb9.png)

For alternative name, I don't use it.

> Sorry for having used French in my 1st post. I thought Dolibarr was maintained by a french team

Not only.

**Comment by webolabo** [comment]
Hello @ksar-ksar 
Now it's OK I thought it takes the method directly from payments but not. I should add the method manually in the invoice.
Now I have the problem of the Alias name that shows in Propals list but not in invoice list 
Is it a bug do you think ?

**Comment by aspangaro** [comment]
It's a bug, fix in link, probably for the next version 14.0.6
