### ISSUE TITLE
Manage lot numbers in kit products

### ISSUE THREAD

**Issue by nathanboschi25** [Dolibarr/dolibarr#19669]
# Feature Request
Would it be possible to allow kit products to consist of products with lot numbers

## Use case
Exemple : 
_A kit (box of 4 products) composed of 4 products with a batch number for each of them._

**Comment by nathanboschi25** [comment]
I am actively waiting for your feedback on this. Because this feature will make Dolibarr more perfect. This would allow many companies to fully use Dolibarr and not struggle with existing features.

**Comment by edupulpillo** [comment]
Same here. The control of serial numbers-lots in kits will be very welcome to control better the traceability of the components and the control of the guarantees.
