### ISSUE TITLE
Extra field when category

### ISSUE THREAD

**Issue by mschamp** [Dolibarr/dolibarr#19671]
# Feature Request
Extra field when products belongs to category

## Use case
Some product properties are related to the kind of product and are not useful for other products.
Those products are grouped in a category, so it would be usefull to be able to link extra fields for products to a category.
In the card the field should only be visible when that category is assigned to that product.
That way, the extrafields could be organised and managable.

**Comment by ksar-ksar** [comment]
Hello,

Could be possible with the visibility field of the extra field?

**Comment by mschamp** [comment]
> Hello,
> 
> Could be possible with the visibility field of the extra field?

Thank you for your respons.
I also thought it would be possible, but i'm not really and expert in PHP.
I did some research on the (English) forum and could not find a similar issue.

Also in the documentation on https://doxygen.dolibarr.org/14.0/dc/d42/class_product.html
I could not find how to get the categories of the product.
I think the Visibility field needs to be something like:

(inArray("IDOfCategoryIWant",$object->Categories))?1:0

Can you give some more information how to achieve the goal?

**Comment by ksar-ksar** [comment]
Hello,

To retrive categories of an object you need to load : 
```
$c = new Categorie($db);
$cats = $c->containing($object->id, Categorie::TYPE_PRODUCT);
```

So may be a 
`(($c = new Categorie($db)) && ($cats = $c->containing($object->id, Categorie::TYPE_PRODUCT))&& (in_array('mycategory',$cats ))) ? 1 : 0`
Could work ?

**Comment by mschamp** [comment]
Thanks, that did the tric!
I noticed that the id in the API response of 
    http:/[ip]/dolibarr/api/index.php/categories?sortfield=t.rowid&sortorder=ASC&limit=100
is not the correct id, it is more like an index (I removed id 1 and 2 earlier) so with is id=1 in that API result, I have to insert 3 in your syntax.
