### ISSUE TITLE
French "département" codes not recognised when importing members 

### ISSUE THREAD

**Issue by antoineguichard** [Dolibarr/dolibarr#19687]
# Bug
When importing a list of members from a CSV file into the Members module, the French "département" codes are not recognised in the stateid field, but codes for other countries are. 

## Environment
- **Version**: 14.0.4
- **OS**: Ubuntu 20.04
- **Web server**: Apache 2.4.41
- **PHP**: 7.4.3
- **Database**: MySQL 8.0.19
- **URL(s)**: [*Affected URL(s)*]

## Expected behavior
When importing a list of members from a CSV or xlsx file, the column for "States/Provinces" should include the corresponding code found in the "States/Provinces" dictionary, eg [TAS] for the Australian state of Tasmania, [HH] for the Hamburg lander of Germany or [32] for the Gers departement of France.

## Actual behavior
Using [TAS] or [HH] correctly decodes the State/Province as Tasmania or Hamburg.
Using [32] (or any other French département number) fails to decode the correct département and instead falls back on the corresponding row number of the MySQL table - eg 
- [32], instead of the Gers département, falls back to row 32 of the table, the Willaya d'Oran region of Algeria
- [92], instead of the Hauts-de-Seine département, falls back to row 92 of the table, the La Pampa province of Argentina

## Possible cause
If the code is detected as being an integer, it does not even bother looking into the code column and goes straight into falling back to the row ID? 

## Workaround
| For Département: | Use RowId: |
| ---------------- | ---------- |
| 1 | 269 |
| 2 | 270 |
| 3 | 271 |
| 4 | 272 |
| 5 | 273 |
| 6 | 274 |
| 7 | 275 |
| 8 | 276 |
| 9 | 277 |
| 10 | 278 |
| 11 | 279 |
| 12 | 280 |
| 13 | 281 |
| 14 | 282 |
| 15 | 283 |
| 16 | 284 |
| 17 | 285 |
| 18 | 286 |
| 19 | 287 |
| 2A | 288 |
| 2B | 289 |
| 21 | 290 |
| 22 | 291 |
| 23 | 292 |
| 24 | 293 |
| 25 | 294 |
| 26 | 295 |
| 27 | 296 |
| 28 | 297 |
| 29 | 298 |
| 30 | 299 |
| 31 | 300 |
| 32 | 301 |
| 33 | 302 |
| 34 | 303 |
| 35 | 304 |
| 36 | 305 |
| 37 | 306 |
| 38 | 307 |
| 39 | 308 |
| 40 | 309 |
| 41 | 310 |
| 42 | 311 |
| 43 | 312 |
| 44 | 313 |
| 45 | 314 |
| 46 | 315 |
| 47 | 316 |
| 48 | 317 |
| 49 | 318 |
| 50 | 319 |
| 51 | 320 |
| 52 | 321 |
| 53 | 322 |
| 54 | 323 |
| 55 | 324 |
| 56 | 325 |
| 57 | 326 |
| 58 | 327 |
| 59 | 328 |
| 60 | 329 |
| 61 | 330 |
| 62 | 331 |
| 63 | 332 |
| 64 | 333 |
| 65 | 334 |
| 66 | 335 |
| 67 | 336 |
| 68 | 337 |
| 69 | 338 |
| 70 | 339 |
| 71 | 340 |
| 72 | 341 |
| 73 | 342 |
| 74 | 343 |
| 75 | 344 |
| 76 | 345 |
| 77 | 346 |
| 78 | 347 |
| 79 | 348 |
| 80 | 349 |
| 81 | 350 |
| 82 | 351 |
| 83 | 352 |
| 84 | 353 |
| 85 | 354 |
| 86 | 355 |
| 87 | 356 |
| 88 | 357 |
| 89 | 358 |
| 90 | 359 |
| 91 | 360 |
| 92 | 361 |
| 93 | 362 |
| 94 | 363 |
| 95 | 364 |
|  |  |
| 971 | 264 |
| 972 | 265 |
| 973 | 266 |
| 974 | 267 |
| 976 | 268 |

**Comment by atm-maxime** [comment]
Thanks for reporting this issue.
You're right, if the value is a numeric, the import system consider that this is the rowid of the corresponding table. Can you try by adding "ref:" before the department number (i.e. ref:26). This will force the import system to look for the department where the code is 26.

**Comment by antoineguichard** [comment]
Yes, thanks, I can confirm that adding either "ref:" or "Ref:" in front of the "States/Provinces" code does work, whether the code is an integer or a non-integer alphanumeric string.
- Using "Ref:32" correctly decodes the Gers département of France.
- Using "Ref:TAS" correctly decodes the Australian state of Tasmania
- Using "Ref:HH" correctly decodes the Hamburg lander of Germany

**Comment by antoineguichard** [comment]
I have identified a further problem.

The StateID reference codes are not unique. 

Several countries have numeric values for "Ref" in their "States/Provinces" dictionary.
For example: 
- France: for "départements", using Ref 01 through to 95 plus 971 through to 976
- Belgium: for "provinces", using Ref 01 through to 11
- Chile: for "provinces", using various values of Ref between 011 and 152 

If I import a member address in Belgium's Hainaut province (Ref is 07), it is always decoded as the french département 07 (Ardèche) even if
- I have BE set explicitly as the country code in that row of the import table
- I change the UI default language to fr_BE (in Setup > Display)
- I change the address of the organisation to an address in Belgium (in Setup > Company/Organisation) 

Would that make sense to provide a way to import the State_id using a syntax such as FR-07 for French Ardèche département and BE-07 for Belgian Hainaut province?

Though I am not sure if those numerical references are stored as numbers or as strings, and in the case of strings if that includes the leading 0.

**Comment by antoineguichard** [comment]
Would that make sense to use ISO 3166-2 codes as StateID references?
> ISO 3166-2:2020
> Codes for the representation of names of countries and their subdivisions — Part 2: Country subdivision code
https://www.iso.org/standard/72483.html
https://en.wikipedia.org/wiki/ISO_3166-2

ISO 3166-2 Country and State/Region Tables for MySQL are available there:
https://gist.github.com/mindplay-dk/4755200
