### ISSUE TITLE
Edit button is missing in validated client invoices

### ISSUE THREAD

**Issue by alonsosdp** [Dolibarr/dolibarr#19707]
# Bug
In previous versions of dolibarr, it was possible to edit a client's invoice even after it was validated.

## Environment
- **Version**: 14.0.4
- **OS**: Linux
- **Web server**: Apache 
- **PHP**: 7.4.27
- **Database**: MySQL or MariaDB 5.7.36

## Expected and actual behavior
After an invoice is validated there should be a button which permits the modification of the invoice.

## Steps to reproduce the behavior
Validate an invoice

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/49050836/147603118-d3f64a28-1887-4f6f-8910-3e230a1d8ffe.png)

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 14.0.5
