### ISSUE TITLE
Changing date on one Contract line, changes dates on all lines.

### ISSUE THREAD

**Issue by karozans** [Dolibarr/dolibarr#19708]
# Bug
All lines in a Contract are automatically changed if you change the dates on one single Contract line.

## Environment
- **Version**: 14.0.4
- **OS**: Ubuntu 20.04
- **Web server**: Apache/2.4.41
- **PHP**: PHP 7.4.3
- **Database**: mysql  Ver 8.0.27-0ubuntu0.20.04.1 
- **URL(s)**:  https://localhost/contrat/card.php

## Expected and actual behavior
It should be expected for only the line that you have modified should be changed.

The actual behavior is that all of the line items in the Contract are updated, instead of just the one you are modifying.

## Steps to reproduce the behavior
1.  Create at least 2 different services.
2. Create a Contract and add both services to the Contract with "Planned Start Date" and "Planned End Date".
3. Validate, and activate all contract lines.
4. Open back up the same Contract and edit one of the Service lines and modify the "Planned Start/End Date".
5. Click "Modify" to save the changes.
6. You will notice that all the lines in the same Contract have been changed.

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 14.0.5
