### ISSUE TITLE
Time tracking for flexible employee work time

### ISSUE THREAD

**Issue by st31ny** [Dolibarr/dolibarr#19714]
# Feature Request
Time tracking for employees with flexible work time.

## Use case
Most of our employees have a flexible work time, i.e., they are required to work a certain amount of time on average per day, but it is perfectly ok if they work some hours extra on one day and some hours less the other day. Currently we are using Dolibarr's project/task feature to track the time. So, each employee gets a personal task per month to track his or hers work time within that month. This approach has a couple of drawbacks however: First, we do not directly know an employees time balance (so how much should he or she have worked within the month aka task?). This leads to the second problem: At the end of the month we would need to transfer the balance to the next month, no matter if it's positive or negative. Since negative work times are not allowed right now, this approach is also very limited.

## Suggested implementation
A simple idea that we came up with, is to allow negative times in tasks as we would then get an easy balance in the "Time spent" report at the end of the month. But there are probably smarter ways to implemented this.

**Comment by erikvanberkum** [comment]
How about a module Dolibarr timesheet. I don't have experience with it myself but it looks like its maintained well. 

https://sourceforge.net/projects/dolibarr-timesheet/

**Comment by st31ny** [comment]
> How about a module Dolibarr timesheet. I don't have experience with it myself but it looks like its maintained well.

Thanks for your suggestion. We actually already tried the timesheet module. However, it unfortunately does not allow customized work times per employee. We are now looking into the [GRH module](https://www.dolistore.com/fr/modules/1234-Gestion-avanc--e-des-ressources-humaines---GRH---All-In-One.html?search_query=contrat&results=68), however.

**Comment by gillerby** [comment]
This would be very useful.

**Comment by st31ny** [comment]
I think we found a solution that nearly works neatly.

In summary, we are using a Task for each employee. Our employees then use the [timesheet plugin](https://github.com/delcroip/dolibarr_project_timesheet) to enter their work times. At the end of the month I add a negative timespent which amounts to the number of workdays times the daily hours for that employee using the API (a little python script queries the user's weekly hours and then does the math).

This works quite neatly except that negative time bookings (which can only be entered in the API, not in the UI) are not formatted correctly (e.g. "-10:-12" instead of "-9:12"). I'll try to find that issue and will open a PR for it.
