### ISSUE TITLE
Create invoice ("facture") from "contrat" does not set the bank account previously set in the "societe"

### ISSUE THREAD

**Issue by joanahead** [Dolibarr/dolibarr#19715]
# Bug
When generating an invoice ("facture") from a "contrat" the system does not automatically fill in the bank account where the invoice should be payed.
In our case we have two bank accounts and each third party ("societe") has a bank account selected in their client/customer form at <baseurl>/comm/card.php?socid=45

## Environment
- **Version**: 14.0.3
- **OS**: Centos 7, although irrelevant
- **Web server**: Apache, although irrelevant
- **PHP**: 7.4, although irrelevant
- **Database**: MySQL, irrelevant
- **URL(s)**: <baseurl>/compta/facture/card.php?action=create&origin=contrat&originid=87&socid=45

## Expected and actual behavior
The form shown at <baseurl>/compta/facture/card.php?action=create&origin=contrat&originid=87&socid=45 should automatically have the bank account selected if the third-party has it set in their client/customer tab at <baseurl>/comm/card.php?socid=45
The actual behavior is that the bank account drop down select is not set when creating the invoice from the contrat.

## Steps to reproduce the behavior
The Dolibarr's installation company should have two bank accounts.
Then go to the third-party (in this example it's the one with database ID 45).
Edit that third-party and, in the client/customer tab select the bank account they should do payments to.
Create a contrat for that third-party (in this example the contrat has database ID of 87).
Then just visit <baseurl>/compta/facture/card.php?action=create&origin=contrat&originid=87&socid=45 (with a valid contrat id as originid and a valid third-part as socid) and see how the bank account dropdown select is empty.

**Comment by OlivdeLab** [comment]
Solved with V15
