### ISSUE TITLE
# Bug Add or old task cron

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#19719]
# Bug
If add task cron it's not view in list if i clone the task it's view in list

If i active debug mode erreur is

![image](https://user-images.githubusercontent.com/34568357/147829733-b91f98d8-14dd-4d5d-9034-b90f97bf2c44.png)

## Environment
- **Version**: 14.0.4
- **OS**: DEBAIAN 10 or WINDOWS
- **Web server**: [*Webserver type and version*]
- **PHP**: 7.4 or 7.3
- **Database**: mysql or mariadb
- **URL(s)**: /cron/list.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
Create a new task cron

Subject in french forum
[https://www.dolibarr.fr/forum/t/taches-planifiees-ne-saffichent-pas-et-ne-sexecute-pas/38718/2](https://www.dolibarr.fr/forum/t/taches-planifiees-ne-saffichent-pas-et-ne-sexecute-pas/38718/2)

**Comment by jocker132** [comment]
Not reproducible on version 12.0.5

**Comment by fappels** [comment]
Fixed here: https://github.com/Dolibarr/dolibarr/pull/19504

**Comment by BB2A-Anthony** [comment]
Ok look tomorow and close issue

**Comment by BB2A-Anthony** [comment]
OK i did a test
