### ISSUE TITLE
L'authentification LDAP meurt sans faire de bruit

### ISSUE THREAD

**Issue by vdegrandpre** [Dolibarr/dolibarr#19725]
**Environnement: ** PHP 8.0, Dolibarr 14.0.4

Une condition fait que la ressource passée à la fonction ldap_clone n'est pas de type « ldap link » mais « Unknown », ce qui fait planter le processus.

Trace d'erreur :+1: 
`PHP Fatal error:  Uncaught TypeError: 
ldap_close(): supplied resource is not a valid ldap link resource in htdocs/core/class/ldap.class.php:305\nStack trace:\n
#0 htdocs/core/class/ldap.class.php(305): ldap_close()\n
#1 htdocs/core/login/functions_ldap.php(274): Ldap->close()\n
#2 htdocs/core/lib/security2.lib.php(99): check_user_password_ldap()\n
#3 htdocs/main.inc.php(718): checkLoginPassEntity()\n
#4 htdocs/admin/index.php(25): require('...')\n
#5 {main}\n  
thrown in htdocs/core/class/ldap.class.php on line 305, referer: https:///admin/index.php?mainmenu=home&leftmenu=setup`

**Comment by ksar-ksar** [comment]
Hello,

Thanks,
To be noted that dolibarr V14 is not compatible PHP V8.
