### ISSUE TITLE
MySQL syntax error when click in "Ticket / back to list"

### ISSUE THREAD

**Issue by cesar-bsd-com-br** [Dolibarr/dolibarr#19728]
# Bug - MySQL Syntax error when selected "Tickets / Back to list"
[
  When I click in "TICKET", I see the tickets listed and change some information in a ticket (% progression, for example).
  So I click in the "Back to list" link, that points to http://my_site_example/ticket/list.php?restore_lastsearch_values=1 and gives me an error:

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20220103075506
Dolibarr: 14.0.4 - https://www.dolibarr.org
Level of features: 0
PHP: 7.3.33
Server: Apache
OS: Linux MY_PROVIDER_EXAMPLE 4.19.150-76.ELK.el6.x86_64 #1 SMP Wed Oct 7 01:34:10 CDT 2020 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

Requested URL: /ticket/list.php?restore_lastsearch_values=1
Referer: http://MY_PROVIDER_EXAMPLE/ticket/card.php?track_id=zpgioy841hqhp385
Menu manager: eldy_menu.php

Modules/Applications: user, resource, ecm, categorie, fckeditor, bookmark, barcode, workflow, socialnetworks, externalsite, cron, expensereport, societe, propal, commande, contrat, ficheinter, supplier_proposal, ticket, fournisseur, agenda, reception, takepos, facture, salaries, banque, product, service, stock, projet
Database type manager: mysqli
Latest database access request error: SELECT t.rowid, t.entity, t.ref, t.track_id, t.fk_user_create, t.origin_email, t.subject, t.type_code, t.category_code, t.severity_code, t.timing, t.fk_soc, t.notify_tiers_at_create, t.fk_project, t.datec, t.date_read, t.fk_user_assign, t.date_close, t.tms, t.message, t.email_msgid, t.progress, t.resolution, t.fk_statut, t.import_key FROM llx_ticket as t LEFT JOIN llx_societe as s ON (t.fk_soc = s.rowid) WHERE t.entity IN (1) AND () ORDER BY t.datec DESC LIMIT 21
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY t.datec DESC LIMIT 21' at line 1

]

## Environment
- **Version**: [14.0.4]
- **OS**: [Linux 4.19.150-76.ELK.el6.x86_64 #1 SMP Wed Oct 7 01:34:10 CDT 2020 x86_64]
- **Web server**: [Apache 2.4]
- **PHP**: [7.3.33]
- **Database**: [MySQL 5.6.41]
- **URL(s)**: [/ticket/list.php?restore_lastsearch_values=1]

## Expected and actual behavior
[Dolibarr produces an error when click in link that should show the project's ticket list]

## Steps to reproduce the behavior
[
  Select a project
  Click on "Tickets"
  Change some information on a ticket
  Click on "Back to list" (you'll see the error)
]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

![image](https://user-images.githubusercontent.com/59903458/147923668-607a492a-b6ce-4280-b88d-a0f7d47198c7.png)

**Comment by ksar-ksar** [comment]
Duplicate of #18921 and #19589

**Comment by JoAnMaFe** [comment]
the problem appears when making a listing with the filter deactivated. (All of them are shown), you access one of them and from there you click Back to the list. From that moment on, the error is displayed.

This website or feature is currently temporarly not available or failed after a technical error.
This may be due to a maintenance operation. Current status of operation (2022-01-04T19:36:20Z) are on next line...
Dolibarr ha detectado un error técnico. Puede leer el archivo log o establecer la opción $dolibarr_main_prod a '0' en su archivo de configuración para obtener más información.

**Comment by cesar-bsd-com-br** [comment]
The problem is solved on version 16.0.3
