### ISSUE TITLE
 Accès refusé. Vous essayez d'accéder à une page, .... Etc etc...

### ISSUE THREAD

**Issue by grosbout2003** [Dolibarr/dolibarr#19720]
Version 15.0.0.0 Beta
Module : Banque 
Table   : Liste écritures
Action : Modifier une écriture

Retour d'un "Accès refusé. ......."

**Comment by atm-maxime** [comment]
Confirmed, due to #19605

**Comment by hregis** [comment]
@grosbout2003 is this error still present with the stable version? (15.0.1)
