### ISSUE TITLE
delivery note sent by email

### ISSUE THREAD

**Issue by orducom1** [Dolibarr/dolibarr#19735]
# Feature Request
allow sent delivery note by email

## Use case
I need sometimes to can send by email my delivery note

## Suggested implementation
I suggest to add a button to allow sending a delivery note by mail like Expedition note

**Comment by ksar-ksar** [comment]
Hello,

What do you call "delivery notes" ? 
Can you put the URL of that function ?

**Comment by orducom1** [comment]
Hello !

In French, we call that « Bon de Livraison » --> Fiche réception in Dolibarr
When you created a « Commande », it’s allow to create a « Fiche expédition » and after that a « Fiche réception »
I wish can to send this « Fiche reception » by email exactly like with the « Fiche expédition ».

doli_test/delivery/card.php?id=3

Regards,
Emeric

I Wish You a Happy New Year !
