### ISSUE TITLE
15.0.0-Beta - Creation of tier with incorrect creator

### ISSUE THREAD

**Issue by BeMins** [Dolibarr/dolibarr#19731]
# Bug
When creating a new tier, the creator is someone from the CRM, but not the one who created the tier.

## Environment
- **Version**: 15.0.0-Beta
- **OS**: Ubuntu
- **Web server**: Apache 2
- **PHP**: 7.4
- **Database**: MySQL

## Expected and actual behaviour
When a user creates a new prospect or client, we should see that he created it. We can see it in the logs, but the "created by" field is populated with someone else. As shown is the screenshots, they are all created by Olivier and Dolibarr says it has been created by other users (not always the same one).
It doesn't affect who the tier is affected to. Only the one who "created" it. 

## Steps to reproduce the behaviour
Use many users. Create a tier. Every time the user creates a tier.

## [Attached files]
![image](https://user-images.githubusercontent.com/96686174/147964059-41a38f09-a975-41db-9dcc-d45a45de55a3.png)
![image](https://user-images.githubusercontent.com/96686174/147964103-194ad5bc-4446-4b7a-ad1f-864c149d5d70.png)
![image](https://user-images.githubusercontent.com/96686174/147964137-acfa0a1f-99c7-437e-b0f2-743faa170c1d.png)

**Comment by aspangaro** [comment]
Not reproduce on 15.0.0 RC

**Comment by Stef83136** [comment]
Reproduce on 14.0.5 !
