### ISSUE TITLE
Cannot relate Order/Invoice/etc with tickets

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19747]
# Bug
Cannot relate from the order/invoice/etc view tickets... When i try to use the relate link with a ticket after the relation process the whole related area view is lost. To Reproduce create an order and a ticket the same customer..Then try to relate between them and see after the relation process the whole relation area is lost... 

No screenshot required 

## Environment
- **Version**: [*14.0.4*] - [*14.0.5*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

**Comment by VaderD** [comment]
Any news regarding this issue ..?

This is issue is rather important .... i think

**Comment by dpriskorn** [comment]
Could you add screenshots?
