### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#19742]
When creating an invoice from an order I would like to have one more option (pls see the attached picture). I would like to have the additonal option "Créer facture et Classer facturé" or maybe better, when clicking on "Créer facture" a question will pop up if I want to class it as "Facturé" as well.

As it is now, I must go back to theorder and class it as "Invoiced" and it is anoying!

![Skarmklipp](https://user-images.githubusercontent.com/24247236/148105543-451d77e8-cdcd-4339-a5ac-a489506aabce.jpg)

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.33-1+0~20211119.91+debian10~1.gbp618351
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0+deb10u1
- **URL(s)**: /azert/commande/card.php?id=251&action=confirm_shipped&confirm=yes&token=f818135dc954c87ed01a7cdcfd0ab686

**Comment by atm-maxime** [comment]
Thanks for your issue. Please try to have a more precise title next time.
I suggest you to have a look on the workflow module

**Comment by hasse-basse** [comment]
Hi

Sorry for the title, I just forgot about it. Concerning my request, thanks for the input: the Workflow module made the trick as it seem to.

I close this
