### ISSUE TITLE
API for Double Entry Accounts

### ISSUE THREAD

**Issue by rfranks-securenet** [Dolibarr/dolibarr#19741]
# Feature Request
At present there is no API for the double entry accounting system. This feature request is to ask for one.

## Use case
We manage our accounting through Sage One (required as it has automatic links to HMRC for VAT returns). I can pull in automatically all invoices, proposals, products, etc., but am not able to pull in the double entry account entries as there is no API available on the Dolibarr end.

## Suggested implementation
Implementation of an API for the Double Entry accounts module

**Comment by aspangaro** [comment]
1st version of accounting double entries API is planned for Dolibarr v16 (July 2022)

**Comment by rfranks-securenet** [comment]
Did this get put in to v16.

I'm now running 16.0.1, and I can't see any entries in the Swagger file?

**Comment by rfranks-securenet** [comment]
Did this ever get included? We're on v19 now, and I still can't see it in the swagger docs?
