### ISSUE TITLE
Account number loose 0-suffix in account menu

### ISSUE THREAD

**Issue by Seriousness** [Dolibarr/dolibarr#19750]
# Bug
An existing account number eg. 1830 is saved as 183 after changing description.

## Environment
- **Version**: 15.0.0-beta but should also fail before
- **OS**: Ubuntu 20.04.3 LTS
- **Web server**: Apache
- **PHP**: 7.4.26
- **Database**: MySQL or MariaDB 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

## Expected and actual behavior
Account numbers somethings have leading zeros and suffix zeros. Whilst the leading zero is not that great matter, it should at least keep the suffix.

## Steps to reproduce the behavior
Set a new account in the chart of accounts page / edit an existing account with an account number that has a suffix zero. It will be removed upon save. Also imported accounts from a chart of account model will be changed!

**Comment by aspangaro** [comment]
Hello,

It's not a bug, dolibarr using virtual zero to operate with a lot of accountancy software.

We have the possibility to define length of virtual zero or use zero in option of accountancy : (Accounting > Setup > General)

![image](https://user-images.githubusercontent.com/2341395/148284880-e5118acf-edfa-4613-8edf-70f95e4f1f41.png)
