### ISSUE TITLE
Error to create credit transfer file (PHP 8)

### ISSUE THREAD

**Issue by xbloq** [Dolibarr/dolibarr#19754]
# Bug
[*The xml file it's created OK in documents/paymentbybanktransfer/receipts/ but I received a blank page in dolibarr and the credit transfer order not appear in dolibarr after*]

## Environment
- **Version**: [*14.0.5*]
- **OS**: [*Fedora 35*]
- **Web server**: [*Apache/2.4.52*]
- **PHP**: [*8.0.14*]
- **Database**: [*Mariadb 10.5.13*]
- **URL(s)**: [*compta/prelevement/create.php?action=create*]

 DEBUG          sql=SELECT rowid, ref FROM llx_prelevement_bons as pb WHERE pb.rowid = 210
 WARNING        Functions.lib::dol_print_date function called with a bad value from page /dolibarr/compta/prelevement/create.php
 ERR            DoliDBMysqli::close Closing a connection with an opened transaction depth=1
 WARNING        --- End access to /dolibarr/compta/prelevement/create.php (Warn: db disconnection forced, transaction depth was 1)

**Comment by ksar-ksar** [comment]
Hello,

Dolibarr V14 is not compatible PHP V8

**Comment by xbloq** [comment]
Sorry. Yes I Know https://wiki.dolibarr.org/index.php/Releases V14.0.0 it's in testing mode with PHP 8. The rest of operations it's working to me in this configuration (the ones I use, a great number). I was think that this information could help. Should I close this?

**Comment by xbloq** [comment]
PHP Warning:  Undefined property: stdClass::$PAYMENTBYBANKTRANSFER_ADDDAYS in /var/www/html/dolibarr/htdocs/compta/prelevement/create.php on line 112
 PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_BANQUE in /var/www/html/dolibarr/htdocs/compta/prelevement/create.php on line 118
 PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_GUICHET in /var/www/html/dolibarr/htdocs/compta/prelevement/create.php on line 118
 PHP Warning:  Trying to access array offset on value of type null in /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php on line 1000
 PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php on line 1946
 PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php on line 1987
 PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php on line 1946
 PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php on line 1987
 PHP Fatal error:  Uncaught TypeError: chmod(): Argument 1 ($filename) must be of type string, resource given in /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php:1755
Stack trace:
0 /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php(1755): chmod(Resource id 119, 436)
1 /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php(1126): BonPrelevement->generate('', 1641596400, 'bank-transfer')
2 /var/www/html/dolibarr/htdocs/compta/prelevement/create.php(118): BonPrelevement->create(NULL, NULL, 'real', '', 1641596400, 0, 'bank-transfer')
3 {main}
  thrown in /var/www/html/dolibarr/htdocs/compta/prelevement/class/bonprelevement.class.php on line 1755

**Comment by lmag** [comment]
For PHP 8 you must have Dolibarr 16.x at minimum
