### ISSUE TITLE
ADD default Service on Task Time

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#19763]
# Instructions
ADD FK_product Default Service in projet_task_time

# Feature Request
Adding this key allows you to retrieve it and automatically manage invoicing

## Use case
Billing of time spent by service automatically

## Suggested implementation
Step 1 : ADD FK_product in BDD
![image](https://user-images.githubusercontent.com/3288514/148534475-868c2ac7-5d94-48e6-8702-4ca49681f914.png)

Step 2 : Add the option to recover the service linked to the time spent line in the invoice creation screen
![image](https://user-images.githubusercontent.com/3288514/148535092-54190567-ae9b-4949-9d75-8e3810dfd4b8.png)

**Comment by lmag** [comment]
@nicolas-eoxia @evarisk-theo @FHenry

**Comment by lmag** [comment]
STEAP 1 : https://github.com/Dolibarr/dolibarr/pull/19764

**Comment by lmag** [comment]
STEAP 2 : In progress : https://github.com/Dolibarr/dolibarr/pull/19765

**Comment by FHenry** [comment]
Add mass action to apply product on time spend
Change label on Service to Invoice with Service to Invoice (when empty)

When Invoice use product of line
