### ISSUE TITLE
Unable to activate modules, modules absent, not shown, tested V15beta and 14.0.5

### ISSUE THREAD

**Issue by Thomas-Liot** [Dolibarr/dolibarr#19767]
# Bug
Unable to go further than mandatory step 1 (company settings) after new install. Mandatory step 2 (activating modules) gives a blank page with sidebar and header only. No modules are shown. 

## Environment
    Version: 15 beta, also 14.0.5, not 14.0.3, 14.0.4 not tested.
    OS: Linux 5.14.21-2-MANJARO x86_64
    Web server: Apache/2.4.52 (Unix) OpenSSL/1.1.1m PHP/8.0.14
    PHP: PHP/8.0.14
    Database: 10.6.5-MariaDB

see: https://www.dolibarr.fr/forum/t/etoile-globalgroup-dans-les-groupes-dutilisateurs-quelle-signification-quel-usage/38772/15?u=kpbls

**Comment by ksar-ksar** [comment]
Hello,

Welcome to Dolibarr GitHub !
I forgot to ask you on the forum : Do you have something on Apache logs ? Usually blank page means PHP errors

**Comment by Thomas-Liot** [comment]
Hi, @ksar-ksar , you're right. 

Here's the line thrown in my error.log file as soon as I try to access the modules page : 

`[Fri Jan 07 19:31:13.495884 2022] [php:error] [pid 9905] [client 127.0.0.1:49584] PHP Fatal error:  Uncaught Error: Undefined constant "warning" in /home/capables/sites/org.capables.test/htdocs/core/lib/admin.lib.php:642\nStack trace:\n#0 /home/capables/sites/org.capables.test/htdocs/admin/modules.php(501): modules_prepare_head()\n#1 {main}\n  thrown in /home/capables/sites/org.capables.test/htdocs/core/lib/admin.lib.php on line 642, referer: https://www.org.capables.test/htdocs/admin/index.php?mainmenu=home&leftmenu=setup&mesg=setupnotcomplete`

**Comment by atm-maxime** [comment]
Yes there's an error in code in admin.lib.php line 642. It seems to only throw a fatal with php8. I'll fix it soon

**Comment by ksar-ksar** [comment]
Hello @atm-maxime, did you found the issue ?

**Comment by FHenry** [comment]
@ksar-ksar fix by https://github.com/Dolibarr/dolibarr/commit/297d2ecfbda7f4397ec5e2453427420e8b2c379e

**Comment by FHenry** [comment]
fix by https://github.com/Dolibarr/dolibarr/pull/19820
