### ISSUE TITLE
Warehouses not for sale

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#19775]
Hi,

Lot of users ask to have one more warehouse option : 
with ENTREPOT_EXTRA_STATUS=1
we have :
- Closed
- Open (all movement)
- Open (only internal movement) -> some users don't understand exactly this option because they think that sales are not allowed on this warehouse but the stock show the concerned quantity

Can you had (**or modify "Open (only internal movement)"**)
- Open (excluded for sales and replenishment)
-> same as "Open (only internal movement)" but **not impacting the stock in all sales screen** and **during replenishment**

impacted screen :
/comm/propal/card.php (stock appear while adding a new line)
/commande/card.php (stock appear while adding a new line)
/compta/facture/card.php (stock appear while adding a new line)
/product/stock/replenish.php (warehouse)
perhaps some other screens...

case reported:
- "garbage"
- product tested 
- product lended to a department of the compagny (R&D, sales, marketing...)

French forum : https://www.dolibarr.fr/forum/t/entrepot-stock-non-vendable/38769

**Comment by Arre8** [comment]
other cases discussed:
- jailed : reserved to particular customer... -> shipment should be authorized from the datawarehouse, so only proposal, order and invoice are impacted by the new state "Open (excluded for sales and replenishment)" or by "Open (only internal movement)" if this one is modified 
- quality stop : waiting to be approved/refused by quality department -> waiting for commercial decision or waiting to be return to supplier (could be integrated to a quality workflow)

**Comment by DATUC** [comment]
Hi @Arre8 i was wondring if we can also have int the warehaouses replenishment workflow a validation option

**Comment by JoAnMaFe** [comment]
Could there be an option to associate a warehouse to a project? For example, all the products that we are going to use in this project have to be physically moved to that warehouse.

**Comment by josett225** [comment]
Hi There,
This issue is a real one I am facing. We are a french bikes manufacturer. We need to get different stocks to separate products to sell from same products to build bikes.

**Comment by fappels** [comment]
https://github.com/Dolibarr/dolibarr/pull/22704

**Comment by josett225** [comment]
Still required
