### ISSUE TITLE
variants list missing in MRP

### ISSUE THREAD

**Issue by WebAuxilium** [Dolibarr/dolibarr#19773]
# Bug
in /mrp/mo_production.php,  for consumption (order type manufacturing) or production (order type Disassemble), the select list of product show "father" product  but not child product (see picture)

## Environment
- **Version**: 15.0 Beta
- **OS**: Linux
- **Web server**: [*APACHE2*]
- **PHP**: 7.4
- **Database**: Mysql

![mrp-doli-no-var](https://user-images.githubusercontent.com/61405530/148648275-a6d4fb37-8cbf-49a9-8031-7478cfa5bea9.jpg)

**Comment by freechelmi** [comment]
Could you edit your title to describe the issue ? thanks

**Comment by edupulpillo** [comment]
You can title it as "variants list missing in MRP"

**Comment by atm-maxime** [comment]
@WebAuxilium thanks for contributing. Can you edit the title of your issue as advised ?

**Comment by WebAuxilium** [comment]
Hello,
First sorry for the late answer
I found the solution 
In modul Variant, you have an option to hide variant in section list and by default this option is activate. If you disable it, it's run perfectky. I've never notice this option before V15.
