### ISSUE TITLE
 Error Duplicate entry

### ISSUE THREAD

**Issue by catmaps** [Dolibarr/dolibarr#19777]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When making deposits, we started getting this error message:

Error Duplicate entry 'bank/checkdeposits/CHK112-0016-bordereau-CHK2112-0016.pdf-1' for key 'uk_ecm_files'

As far as we can see, there is no duplicate deposit entry. We cannot make this nuisance error notice go away. Do we need to somehow edit the database? Or is this a software bug? See similar issue #17289

## Environment
- **Version**: 14.0.4
- **OS**: Debian
- **Web server**: Apache/2.4.48 (Debian) 
- **PHP**: 7.4.21
- **Database**: [*Database type and version*]
- **URL(s)**: /compta/paiement/cheque/card.php?id=20

**Comment by maxoghana** [comment]
Hello, 
I also got this issue since dolibarr 13.x (I don't remember exactly when this issue occurs for the first time).
I thought it will disappear  with the next upgrade of dolibarr.
But 2 or 3 upgrades later, it's still there.

I have upgraded to 14.0.5 this morning but the issue is not solved

**Comment by didierlucquy** [comment]
I also got this issue today on dolibarr 14.05 when generate a pdf from check deposit.
