### ISSUE TITLE
Duplicate entry for product_extrafields

### ISSUE THREAD

**Issue by Iledher** [Dolibarr/dolibarr#19784]
Cloning Product with unique extrafield is not possible

## Environment
- **Version**:  [14.0.4 ]
- **OS**: [ 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64]
- **Web server**: [Apache]
- **PHP**: [ 7.4.25]
- **Database**: [mysqli]
- **URL(s)**: [/dolibarr/product/card.php?id=72&action=confirm_clone&confirm=yes&token=f33d9b2aa7fb38aa109ed1ec6504e9bb&clone_ref=Copie%20de%20Tsldec_350g&clone_content=on&clone_categories=on&clone_prices=&clone_composition=]

## Expected and actual behavior

I add an extrafield (integer) for the Product, with the Unique checkbox active (this is the ID of this article into a another software)
When i try to clone a product with something in this extrafield, i got the error message and the product is not clone.

**Comment by ksar-ksar** [comment]
Hello,

Seems safe too me.
You can clone if you have a unique extrafield.

What do you want exactly ? to reset the unique extrafiled to empty ? but then it is not a "clone" anymore....

**Comment by Iledher** [comment]
hello,
i just want to clone a product. This function works well before I add this extrafield

**Comment by ksar-ksar** [comment]
Ok then remove the unique extrafield

**Comment by Iledher** [comment]
It works if i leave blank the unique extrafield or if i modify the extrafield to 'not unique'... For me it's a bug...

**Comment by ksar-ksar** [comment]
As explain above, clone is not possible due to the unique extrafiled.
Then what do you want that Dolibarr does in this case ?
In my opinion, there are two choices ; 
1. Throw an error (Actual behavior)
2. Put the unique extrafield to empty : But then it is not a "clone" any more.

**Comment by Iledher** [comment]
For me the second behavior is the best. Or better : when you clone a Supplier Invoice the interface open a modal window with the new date and ref for the clone invoice.
![Capture d’écran de 2022-01-12 09-14-20](https://user-images.githubusercontent.com/24903496/149089617-5cbddf71-ada4-434c-90a3-d57153978720.png)
