### ISSUE TITLE
Bug: tva

### ISSUE THREAD

**Issue by DjNimesEvents** [Dolibarr/dolibarr#19782]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
la TVA ne veut pas s'apparaitre sur les devis et facture .....

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.4.25
- **Database**: MySQL or MariaDB 5.5.60-0+deb7u1-log
- **URL(s)**: /htdocs/index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

First thing to do, is to upgrade to V12.0.5

**Comment by aspangaro** [comment]
No information. Close issue
