### ISSUE TITLE
SEPA not possible for non-EU SEPA countries (ex. Switzerland)

### ISSUE THREAD

**Issue by anglepoise86** [Dolibarr/dolibarr#19793]
Hello,

I tried to generate a bank transfer (SEPA) for our Swiss company but I got the following error message:
`Impossible de générer le fichier de reçu des prélèvement pour votre pays CH (Votre pays n'est pas supporté)`

As far as I understood, Dolibarr supports SEPA only for countries located in the European Economic Community (EEC).
However the SEPA area includes also non european countries such as Switzerland, UK, Norway etc., according to the link below:
https://www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html

Is there any reason that those countries are not in Dolibarr ? If not, is it possible to add them in a future release ?

Thank you in advance.

**Comment by emo53** [comment]
Still issue in version 20.0.4.
Workaround in core\lib\company.lib.php.
Add $country_code_in_EEC[] = "CH"; 
in function getCountriesInEEC()
