### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by David-Maran** [Dolibarr/dolibarr#19822]
I don't know if it's wanted.
The symfony/var-dumper package and maximebf/debugbar are in the require.
Shouldn't they be in require_dev?

**Comment by cfoellmann** [comment]
First the composer integration in the dolibarr core is not used as it should be. Packages are commited to Git.

For the debugbar: The package is required for the module. the module is in the release package therefor the composer package should not be limited to require_dev

**Comment by David-Maran** [comment]
@cfoellmann  var-dumper is a package that should ONLY be used for dev and should ONLY be in require_dev. If you forget a dd() in the code that is put in production then you will have surprises.
