### ISSUE TITLE
Bug: In the members module, when creating a new member, the save button does not appear.

### ISSUE THREAD

**Issue by arvinhas** [Dolibarr/dolibarr#19831]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 8.0.14
- **Database**: MySQL or MariaDB 5.7.36-cll-lve
- **URL(s)**: /adherents/card.php?leftmenu=members&action=create

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
![Sem Título](https://user-images.githubusercontent.com/97702175/149404652-b219b5c7-1c8a-473b-a1d6-10f7c5395dcd.png)

[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

Dolibarr V14 is not compatible PHP V8

**Comment by xbloq** [comment]
Hi @arvinhas
You shouldn't listen to me, I don't know what I'm doing but it's works with a new member 

V14.0.5 with PHP 8.0.15
/htdocs/adherents/card.php

Comment lines 1055 to 1059
//if (empty($soc->country_id)) {
//$soc->country_id = $mysoc->country_id;
//$soc->country_code = $mysoc->country_code;
//$soc->state_id = $mysoc->state_id;
//}

**Comment by lmag** [comment]
For PHP 8 you must have Dolibarr 16.x at minimum
