### ISSUE TITLE
Inconsistency between display "Delete File" icon in all Document tab and permission cheked

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#19837]
Dolibarr version 14.0.5

Exemple with product/document.php

User 1 :
Perms Add Product =1
Perms Delete Product = 0

Go on Product, Document Tab, Upload file => OK
Delete The File : Error : you try to do something you cannot

Line 99 In product/document.php the test to display trash icon and use by core/actions_linkedfiles.inc.php is
`$permissiontoadd = (($object->type == Product::TYPE_PRODUCT && $user->rights->produit->creer) || ($object->type == Product::TYPE_SERVICE && $user->rights->service->creer));
`

But just after the is the restrictedArea call where GETPOST('action') is tested and in this case action='delete', and as user do have right to Delete a product : Error message from restrictedArea.

**Comment by FHenry** [comment]
@eldy What is the best way to fix it ?
1 - Change test on $permissiontoadd in all document.php (and in module builder) pages to match "delete perms" instead of "add perm" (more accurate but no ok in most of use case)
2 - Change action='delete' on click on trash icon by delete_file : in this case restrictedArea won't test this it's ok
3 - Add another argument to restrictedArea to send $permissiontoadd that override his test ?
4 - Create a new set of perms for each object : Can add file, Can delete file
5 - Another Idea ?

**Comment by eldy** [comment]
It is clear that if you have permission to upload an attached file (should need permission to edit/create object), we should use the same permission to delete the file (deleting a file is modifying the properties of an object). So Permission should be the same.
Permission to delete is to remove the object, it is not related to files that are properties of object so managed by the edit/create perm. So i discard choice 4.
Solution is choice 5: when we delete a file, we must use param action=deletefile and not delete
I think this has already been fixed into v15 but may be not everywhere.
