### ISSUE TITLE
Price request page: Add new free text item not working

### ISSUE THREAD

**Issue by jrucker2004** [Dolibarr/dolibarr#19843]
# Bug
On the Price Request creation page, I can add a pre-defined product, but cannot add a free text item.

Filling out the necessary fields, and hitting the "add" button refreshes the page, but the new item is not added.

EDIT:  See comment below:  The bug is that the price request form doesn't allow a null dollar amount when adding a new item.  A price request should not require entering a dollar amount, as the dollar amount is unknown, which is the entire reason for creating a price request.

## Environment
- **Version**: 14.0.2 & 14.0.5
- **OS**: Ubuntu server 20.0.4
- **Web server**: Apache 2.4.41
- **PHP**: 7.4.3
- **Database**: mariadb 10.3.32
- **URL(s)**: /dolibarr/supplier_proposal/card.php?id=8#add

## Expected and actual behavior
After the fields for a new free line item are filed out, and the "add" button is pressed, the item should be added to the price request, and display along with other items already on the price request.

## Steps to reproduce the behavior
1.  Create a new price request draft (Commerce tab -> new price request -> create draft)
2. under the "add new line" section, select "free text item"
3. select "service" or "product" from the dropdown
4. Enter some descriptive text for the service or product
5. Enter a quantity of at least 1
6. Click the "add" button

**Comment by ksar-ksar** [comment]
Hello,

First thing is to update to V14.0.5

**Comment by jrucker2004** [comment]
> 

Upgrade to 14.0.5 complete, no change in behavior described in initial but report.

**Comment by jrucker2004** [comment]
Upgrade to 15.0.1 complete, bug still present.

**Comment by hregis** [comment]
@jrucker2004 
I can't reproduce the problem! neither in 14.0.5 nor in 15.0.x
Do you have an external module that could create conflicts?

**Comment by jrucker2004** [comment]
I don't have any external modules installed.

Modules currently enabled:

Under the CRM section:

- Third Parties
- Proposals

Under the VRM section:

- Vendors
- Vendor Commercial Proposals

under the Financial Modules section:

- Invoices

under the Product Management section:

- Products
- Product Variants
- Bills of Material
- Manufacturing orders

**Comment by jrucker2004** [comment]
I enabled the debug logs module, and this is the only thing logged when following the steps above:

`2022-02-22 22:49:46 ERR     192.168.1.80      Price.lib::calcul_price_total function called with bad parameters combination (pu or multicurrency_tx are not numeric)`

AH!
That clearly means the price per item can't be null.
If I'm creating a price request, I have no idea how much the vendor is going to charge me, it doesn't make any sense from a workflow perspective to enter a price at this point.

The bug is that this form should allow a zero or null dollar amount when creating a price request, and it isn't.
