### ISSUE TITLE
[Ticket] Pre recorded reply 

### ISSUE THREAD

**Issue by freechelmi** [Dolibarr/dolibarr#19858]
Hope it's not a DUP but I could not find it.

# Feature Request
It would be usefull to be able to prerecord some standard reply in the ticket system to send them in one click to replay to tickets

## Use case
One would record standard replies like " Can you confirm the problem is now solved ? " 

## Suggested implementation
Show a dropdown list on top of the "message" list when adding a reply on a ticket

## Suggested steps

- Add a Database table for " ticket standard replies" 
- Be able to filter them on commercial/support type
- Add a dropdown seletor on ticket reply page 
- on select the content of "message" will be replaced by the content of teh standard reply

**Comment by atm-maxime** [comment]
Did you try with email models ? It's what we use to have predefined message we need to send to contacts linked to the ticket

**Comment by freechelmi** [comment]
Thanks , I do think this is sufficient for this need , I close the feature request then
