### ISSUE TITLE
One contact to be used on several third parties

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#19859]
# Feature Request
Being able to use a contact on multiple third parties

## Use case
Currently, one contact can be use only in one third party.
But we could have the same contact for several third parties.

## Suggested implementation
There is a workaround described here :

1. Create a particular user group that will not have any rights (example: "multiple contacts")
2. Open the contact's card.
3. Click on "Create a user account" button and validate.

And that's it! You can now assign this contact to several third parties by going through the "Salespersons" field of the third party.

To prevent this contact from doing anything as a user, you assign it to the "multiple contacts" group.

This solution is quick, it does the job.

Source : https://www.dolibarr.fr/forum/t/plusieurs-tiers-pour-le-meme-contact/28933/66

**Comment by conformist66** [comment]
Thanks but I've tried this and an important feature is missing using this workaround.  I have a wholesaler customer that has multiple branches and a centralized accounts department.  I need to have this accounts department assigned to each branch.  I've setup the proposed method outlined but the email address for the 'salesperson' does not appear when emailing the branch (I need to copy each branch invoice to accounts).  Have I missed a step somewhere?

**Comment by philippe-opendsi** [comment]
Hi
We've made this extension https://git.open-dsi.fr/dolibarr-extension/dolibarr_module_relationstierscontacts
At this day, the main limit is the ability to use contact not related to a thirdparty as a contact on proposition, order, invoice, etc... In order to do that, we need to make significativ change in Dolibarr core.
This extention can be a start for this feature...
Regards

**Comment by yaslama** [comment]
It seems that the feature is there but hidden and not very well tested:
See https://github.com/Dolibarr/dolibarr/pull/29010
