### ISSUE TITLE
Email template variable: __SHIPPING_METHOD__ needed

### ISSUE THREAD

**Issue by ultrasites** [Dolibarr/dolibarr#19876]
# Feature Request
Email template variable __SHIPPING_METHOD__ that returns the shipping method e.g. UPS ..

## Use case
Sending shipping notification to a customer

**Comment by jameszhang023** [comment]
good idea

**Comment by ultrasites** [comment]
still relevant

**Comment by ultrasites** [comment]
Hi, any news?

**Comment by ultrasites** [comment]
Ok, here is the PR: https://github.com/Dolibarr/dolibarr/pull/25667

Please review @eldy @jameszhang023

**Comment by eldy** [comment]
PR merged
