### ISSUE TITLE
Email template variabe __DATE_DELIVERY__ is empty

### ISSUE THREAD

**Issue by ultrasites** [Dolibarr/dolibarr#19877]
If I create a new delivery, i want to send a notification to my customer with the delivery date.  But the email template variable `__DATE_DELIVERY__` is always empty in the template, but the planed delivery date is set in dolibarr. 

What can i do?

Thx.

**Comment by ksar-ksar** [comment]
Hello,

What is your dolibarr version ?

**Comment by ultrasites** [comment]
@ksar-ksar 14.0.5
