### ISSUE TITLE
Error on API method GET /projects

### ISSUE THREAD

**Issue by JJaviMS** [Dolibarr/dolibarr#19872]
Hi, I am trying to get a list of my projects using the API method GET /projects. The problem is that the response I got from the server is a 404 error instead of the list of projects.

The curl request if the next one: ` curl -X GET --header 'Accept: application/json' --header 'DOLAPIKEY: MyApiKey' 'https://example/api/index.php/projects/'`

And the response:

```
{
    "error": {
        "code": 404,
        "message": "Not Found: No project found"
    },
    "debug": {
        "source": "api_projects.class.php:189 at call stage",
        "stages": {
            "success": [
                "get",
                "route",
                "negotiate",
                "authenticate",
                "validate"
            ],
            "failure": [
                "call",
                "message"
            ]
        }
```
Also if I try a request on an unique project the GET is working, for example GET /projects/1

Anyone knows why am I getting this 404 error?

Thanks in advance

**Comment by mproove-gh** [comment]
did you try to remove the ending '/' from your URL?

`curl -X GET --header 'Accept: application/json' --header 'DOLAPIKEY: MyApiKey' 'https://example/api/index.php/projects'`

**Comment by vincentjdc** [comment]
I just add this error.

I needed to read the code to know why I get that404 error.
I had just to set permission to read thirdparties to the user used by the API (`$user->rights->societe->client->voir`)

Hope this helps

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by John-H-Smith** [comment]
Same for /invoice.
Regarding to HTTP standard, 4xx errors only should be returned if the user agent has done something wrong (for example a wrong url or wrong resource). But in that case, the url is correct, but there's simply no resource. The HTTP response code should be changed for 200 or 204 for those cases.

EDIT:
As I can see [here](https://github.com/Dolibarr/dolibarr/blob/5d159e82314bf9312a947d6d1c8328a2228dffa2/htdocs/compta/facture/class/api_invoices.class.php#L285), the api is developed in mind that this would be a full exception, which it isn't.
