### ISSUE TITLE
Multiple fields in the ReceiptPrinter module do not print on TakePOS receipts, despite being included in the template.

### ISSUE THREAD

**Issue by izrunas** [Dolibarr/dolibarr#19875]
# Bug
Multiple fields in the ReceiptPrinter module do not print on receipts generated when using TakePOS, despite being included in the selected receipt template.

## Environment
- **Version**: Dolibarr ver. 14.0.4
- **OS**: Debian 10  (Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux)
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.33-1+0~20211119
- **Database**: MariaDB 5.5.5-10.3.31-MariaDB-0+deb10u1
- **URL(s)**: ~/admin/receiptprinter.php?mode=template

## Expected and actual behavior
When configuring a template for receipt printing via the ReceiptPrinter module of Dolibarr, there is a list of fields which are given as options to be included in the receipt templates--and thus are expected to print when a receipt is printed on a configured receipt printer from the TakePOS cash desk.  However, the fields that should print customer information on the receipt do not work.  When included in a template, the fields print nothing, regardless of data in the related customer record.

The fields which do not print include:
{dol_value_customer_firstname} | Customer first name
{dol_value_customer_lastname} | Customer last name
{dol_value_customer_mail} | Customer mail
{dol_value_customer_phone} | Customer phone
{dol_value_customer_skype} | Customer Skype
{dol_value_customer_tax_number} | Customer tax number

## Steps to reproduce the behavior
With TakePOS set to use the ReceiptPrinter module to print receipts: Include any of the listed fields in a receipt template, then when printing a receipt from the TakePOS cash desk screen after selecting a non-default customer, the line(s) where the information should appear is blank regardless of actual customer information values that exist in the system.  To my experience, all other fields print as expected.

**Comment by catrielr** [comment]
Could you add the template you are using?

**Comment by izrunas** [comment]
`{dol_print_text}{dol_value_customer_entity}
{dol_print_text}{dol_value_customer_firstname}
{dol_print_text}{dol_value_customer_lastname}
{dol_align_center}
{dol_line_feed}
{dol_print_logo}
{dol_line_feed}
{dol_print_text}307 S 1st St, Dubois WY 82513
{dol_print_text}+1 (307) 455-2991
{dol_print_text}www.PVMercantile.com
{dol_line_feed}
{dol_print_text}{dol_value_day_letters}, {dol_value_month_letters} {dol_value_day}, {dol_value_year}
{dol_print_text}Invoice #: {dol_value_object_ref}
{dol_print_text}---------------------------------------
{dol_align_left}
{dol_print_object_lines}
{dol_line_feed}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_object_total}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_payment}
{dol_align_center}
{dol_print_text}{dol_value_customer_entity}
{dol_print_text}{dol_value_customer_firstname}
{dol_print_text}{dol_value_customer_lastname}
{dol_print_text}{dol_value_customer_mail}
{dol_print_text}---------------------------------------
{dol_line_feed}
{dol_print_text}Thank you for your business!
{dol_line_feed}
{dol_print_text}Please come back soon!
{dol_line_feed}
{dol_cut_paper_full}
{dol_align_center}
{dol_print_text}STORE COPY
{dol_line_feed}
{dol_print_text}{dol_value_day_letters}, {dol_value_month_letters} {dol_value_day}, {dol_value_year}
{dol_print_text}Invoice #: {dol_value_object_ref}
{dol_print_text}{dol_value_customer_entity}
{dol_print_text}{dol_value_customer_firstname}
{dol_print_text}{dol_value_customer_lastname}
{dol_print_text}{dol_value_customer_mail}
{dol_print_text}---------------------------------------
{dol_align_left}
{dol_print_object_lines}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_object_total}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_payment}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_cut_paper_full}`

**Comment by izrunas** [comment]
This is the template I was trying to use.  Absolutely none of the {dol_value_customer_* fields will print anything, regardless of what is actually listed in their third-party record.  

{dol_align_center}
{dol_line_feed}
{dol_print_logo}
{dol_line_feed}
{dol_print_text}307 S 1st St, Dubois WY 82513
{dol_print_text}+1 (307) 455-2991
{dol_print_text}www.PVMercantile.com
{dol_line_feed}
{dol_print_text}{dol_value_day_letters}, {dol_value_month_letters} {dol_value_day}, {dol_value_year}
{dol_print_text}Invoice #: {dol_value_object_ref}
{dol_print_text}---------------------------------------
{dol_align_left}
{dol_print_object_lines}
{dol_line_feed}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_object_total}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_payment}
{dol_align_center}
{dol_print_text}{dol_value_customer_entity}
{dol_print_text}{dol_value_customer_firstname}
{dol_print_text}{dol_value_customer_lastname}
{dol_print_text}{dol_value_customer_mail}
{dol_print_text}---------------------------------------
{dol_line_feed}
{dol_print_text}Thank you for your business!
{dol_line_feed}
{dol_print_text}Please come back soon!
{dol_line_feed}
{dol_cut_paper_full}
{dol_align_center}
{dol_print_text}STORE COPY
{dol_line_feed}
{dol_print_text}{dol_value_day_letters}, {dol_value_month_letters} {dol_value_day}, {dol_value_year}
{dol_print_text}Invoice #: {dol_value_object_ref}
{dol_print_text}{dol_value_customer_entity}
{dol_print_text}{dol_value_customer_firstname}
{dol_print_text}{dol_value_customer_lastname}
{dol_print_text}{dol_value_customer_mail}
{dol_print_text}---------------------------------------
{dol_align_left}
{dol_print_object_lines}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_object_total}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_align_right}
{dol_print_payment}
{dol_align_center}
{dol_print_text}---------------------------------------
{dol_cut_paper_full}

**Comment by izrunas** [comment]
I anyone going to address this issue?  It is ongoing and would appear to affect ALL normal installations of Dolibarr.
