### ISSUE TITLE
v14.0.4 - Hidden option "THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT" doesn't work

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#19874]
# Bug
After set THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT = 3 on the constant, the form doesn't display the defaut value "customer" 

## Environment
- **Version**: 14.0.4
- **Web server**: Apache
- **PHP**: 7.3
- **Database**: Any
- **URL(s)**: https://XXXcom/admin/const.php & https://XXXXcom/societe/card.php?action=create&leftmenu=

## Steps to reproduce the behavior

1. Open https://XXXcom/admin/const.php
2. Create a new const THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT = 3 
3. check https://XXXXcom/societe/card.php?action=create&leftmenu=

Related doc : https://wiki.dolibarr.org/index.php/Setup_Other#List_of_known_hidden_options 
THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT ► Set the third party type by default (3 = customer / 2 = prospect)

## [Attached files]
![Tiers](https://user-images.githubusercontent.com/26635105/150013561-fcf23a37-0f0b-4dee-92a4-35b271a68d81.png)

**Comment by daxitsolutions** [comment]
By the way, the documentation is also wrong 
THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT ► Set the third party type by default (3 = customer / 2 = prospect)

The right definition is : 
THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT ► Set the third party type by default (3 = customer & prospect / 2 = prospect / 1 = customer )

**Comment by ksar-ksar** [comment]
Hello,

This is exactly the way it is supposed to work no ?
If you want to keep the field, you need to use "Default values/filters/sorting"

**Comment by daxitsolutions** [comment]
@ksar-ksar 

1) setup the "THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT" 
![Configuration](https://user-images.githubusercontent.com/26635105/152644448-bc49c537-1928-4927-8a54-7844e4d17c60.png)

2) check on the form when creating the new customer 
![Tiers](https://user-images.githubusercontent.com/26635105/152644474-e2c67603-771b-48ed-bb62-8f05418b935f.png)


I'm expecting something like this (automatic set of the drop-down field):

![Tiers](https://user-images.githubusercontent.com/26635105/152644494-40e6848f-f6ce-4f34-ac03-9b2240dfc0b6.png)
