### ISSUE TITLE
Interventions Module: possibility to add/select predefined services

### ISSUE THREAD

**Issue by dominiksaul** [Dolibarr/dolibarr#19882]
# Feature Request
Request to add in the interventions module the possibility to select predefined Services or Products and add supplementary text. + the possibility that those positions in are correctly taken over in bills. (Like it is already in the modules offer, orders, etc.)
If you create at the moment positions in an intervention you cannot chose predefined products or services from the products module. And if you create out of this intervention an offer or bill, the positions from the intervention don't have a price and it always has to be modified manually.

**Comment by BurksEngineering** [comment]
see #26057
