### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by achillesh** [Dolibarr/dolibarr#19886]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[I can't enter any Bank account data, IBAN, BANK CODE, BIC/SWIFT etc.]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 8.0.14
- **Database**: MySQL or MariaDB 10.3.32-MariaDB-cll-lve
- **URL(s)**: /compta/bank/card.php?action=edit&token=2b57ccdea76ef53a670f94d5833dd4f6&id=1

## Expected and actual behavior
[]

## Steps to reproduce the behavior
[Nothing of the above bank item to edit only view.]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[]

**Comment by ksar-ksar** [comment]
Hello,

What does that mean "I can't enter any Bank account data," ?
Any error messages ?

**Comment by ksar-ksar** [comment]
And Dolibarr V14 is not compatible php V8

**Comment by achillesh** [comment]
My php version is 7.3. I 'll test it with php 7.2 but at the moment nothing of the above item is able to edit.
I edit them form mysql table.

**Comment by achillesh** [comment]
All is ok with 7.2 php Version !!
