### ISSUE TITLE
Can't not use 0 in the end of Account number in List of the accounting accounts

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#19881]
# Bug
[*Short description*]
In taiwan , the account number in List of the accounting accounts will use 0 in the end , like 1100 , 1310 ... etc .
But when i want to use 0 ( number zero ) in the end , like 1100 , it will become 11 .
## Environment
- **Version**:14.0.5 and 14.0.3
- **OS**: Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.4.3
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0+deb10u1
- **URL(s)**: /accountancy/admin/account.php?mainmenu=accountancy&leftmenu=accountancy_admin

## Expected and actual behavior
[*Verbose description*]

Should also can use 0 in the end of account number .

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/78349579/150168727-0c528748-b649-45ee-b057-dcaa199d53a9.png)
![image](https://user-images.githubusercontent.com/78349579/150168968-5059bc07-4513-4c35-b133-1ca3e81332c2.png)

**Comment by priojk** [comment]
This is probably not a bug but can be solved with a configuration setting in Setup -> Modules -> Accounting Double Entry:

In setup/general of the module there is this point:
"Allow to manage different number of zeros at the end of an accounting account. " which you need to activate to preserve the zeros at the end.

**Comment by trekmorris** [comment]
> 
Hi priojk

Yes , you are correct . i will closed this issue , thanks .
