### ISSUE TITLE
VAT issue in generated PDF

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#19887]
I updated to the current 15.0 branch.
VAT calculation (or display) in PDFs is broken.

Reverting this commit https://github.com/Dolibarr/dolibarr/commit/c3a42162d98805ac3f2fa57419c1c706fac35dc6 just solves the issue for us for now.

**Comment by bargoud** [comment]
Hello,
Same here. The VAT displayed in the PDF is not the sum, it's only the last line's vat value.

**Comment by ozit** [comment]
It seems to be solved

**Comment by cfoellmann** [comment]
fixed!
