### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by spyros243** [Dolibarr/dolibarr#19907]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: apache2handler 7.3.31-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0+deb10u1
- **URL(s)**: /dolibarr/htdocs/custom/mydata/mydataindex.php?idmenu=45&mainmenu=mydata&leftmenu=

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Thanks for this empty issue 🙂
