### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Pantapath** [Dolibarr/dolibarr#19903]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1
- **URL(s)**: /admin/system/perf.php?mainmenu=home&leftmenu=admintools

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

What is the question ?

**Comment by atm-maxime** [comment]
Thanks for this empty issue 🙂
