### ISSUE TITLE
Feature request - POS - German or other EU countries legal situation TSE (Technical Safety Device) 

### ISSUE THREAD

**Issue by klausking** [Dolibarr/dolibarr#19902]
In Germany (and other EU countries) it is required by law to equip new POS systems with a TSE, which should be considered when developing the POS.
At least it would be great to facilitate usb or cloud TSE integration with the appropriate settings in the options.

In connection with this, these values would of course also have to be output on the receipt. ( receipt responsibility in Germany...)
For more informations -->   [https://kassensichv.com/]

**Comment by ksar-ksar** [comment]
Hello,

What is a TSE ?
https://wiki.dolibarr.org/index.php/Module_Unalterable_Archives_-_Logs ?

**Comment by hregis** [comment]
@ksar-ksar @klausking 
you speak of the Dolibarr module "Unalterable Archives" ?

**Comment by klausking** [comment]
The "Kassensicherungsverordnung" (KassenSichV) in Germany, 
which requires the complete, unchanged and tamper-proof storage of business transactions and some other processes.
The "TSE" obligation is gradually being introduced for this. Roughly speaking, the general obligation to 
issue receipts should curb tax evasion in cash transactions.
The "TSE" itself is a hardware or cloud solution. This has nothing to do with the dolibarr log.That is not enough.

Technical functioning 

In the future, every checkout process will be stored on the TSE and electronically signed by it. 
A chaining principle is used here. Every transaction gets an electronic signature, a signature counter and a time stamp. 
This means that each signature can only be produced exactly once. 
This ensures that it is impossible to make changes to the chain of transactions afterwards without this being verifiable. 
The technical security device can therefore be checked by the tax office for manipulation, gaps and changes using test software. 
A journal is saved of all transactions, which the tax office must be able to export at any time. 
The file with the exported data is in tar format.

https://de.wikipedia.org/wiki/Technische_Sicherheitseinrichtung#:~:text=Als%20Technische%20Sicherheitseinrichtung%20(TSE)%20wird,unver%C3%A4nderbaren%20Aufzeichnung%20aller%20Kassenvorg%C3%A4nge%20dient.


![image](https://user-images.githubusercontent.com/55943092/150589465-a1c5688c-1dc8-48ab-a375-bda478ed373c.png)


The problem now is that the POS module can unfortunately no longer be used legally. (In Germany and other EU states )

**Comment by priojk** [comment]
Hello @klausking,

your concerns for the use in Germany are absolutely valid. But I think a solution is already on its way: At the last German Doliday in December, a module was presented, which will allow a connection to the cloud based TSE servcie from Fiskaly.

It was announced that it would be available in January. Here are some notes about this from Twitter: https://twitter.com/bloxera/status/1469240148911079426
. I took these notes, but unfortunately I don't quite remember, who actually presented this during the Doliday.

**Comment by klausking** [comment]
Hi there,

that doesn't sound so bad.

But basically I think it's a pity that more and more expensive third-party software / solutions have to be used to meet legal requirements. The same example with the accounting in Dolibarr, which is also not 100% GobD compliant.

Nevertheless, Dolibarr is of course great and one must not forget open source! 
One can only hope for the future :)

Thank you for the information.

**Comment by catrielr** [comment]
this can help you

#19501

**Comment by klausking** [comment]
Great ! Thanks a lot

**Comment by hanneshier** [comment]
@klausking do you have any news on this topic? I need a TSE Module as well, but I cannot find any information except for @priojk s Tweets

**Comment by klausking** [comment]
@hanneshier - Hello, I solved the whole thing differently now. I have integrated the "order sprinter" software into Dollibar. Since there is currently simply no sensible solution for the inter POS solution.

https://www.ordersprinter.de/

**Comment by hanneshier** [comment]
@klausking how did you integrate the two systems? Do they work together automatically?

**Comment by Adventurousdonut** [comment]
Any news from this? I'd also need something *similar*, i need it to compliant with the Austrian RKSV (Registrierkassensicherheitsverordnung). The RKSV is very similar to the TSS.

Btw here's a good explanation what the TSS/TSE is exactly: https://developer.fiskaly.com/en/docs
And here is a *kind of a list* of what the RKSV needs: https://developer.fiskaly.com/api/rksv/v1#section/Introduction plus the official governmental english explanation of the RKSV: https://www.wko.at/branchen/information-consulting/unternehmensberatung-buchhaltung-informationstechnologie/it-dienstleistung/BGBLA-2015-II-410-EN.PDF

**Comment by andreubisquerra** [comment]
Important update:
Abbes from AB1 Consulting is developing a module to integrate the TSS/TSE via API into a TakePOS and cover all legal requirements for Germany and Austria. This module will be available very soon on Dolistore and on ab1 Consulting page http://www.ab1consult.com/

**Comment by andreubisquerra** [comment]
BUG solved by external module. The module is already for sale in https://ab1consult.com/en/38-fiskaly-signde-tse.html and Dolistore. It is also free available in all AB1 Consulting SAAS https://ab1consult.com/en/17-cloud-services. There is a video explaining how it works on youtube https://youtu.be/1nqY9BcciXM

**Comment by hanneshier** [comment]
The external module seems not to be available anymore and the website of the developer is down. Does anyone has information on this matter or about any other development?

**Comment by priojk** [comment]
I think in the past years German requirements have tightened. From what I have seen, a pure Software-TSE is not possible but would require the entire software system to get certified. The cost of this is prohibitive.

**Comment by hanneshier** [comment]
> I think in the past years German requirements have tightened. From what I have seen, a pure Software-TSE is not possible but would require the entire software system to get certified. The cost of this is prohibitive.

@priojk do you have a link for any resources/article about the tightened requirements?

**Comment by priojk** [comment]
The detailed requirements should be available at www.bsi.bund.de which is the responsible certification body in Germany. 

The technical requirements (Technische Richtlinie) is here available: https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03153/TR-03153-1_Version1-1-1.pdf?__blob=publicationFile&v=3

There is also a FAQ:
Sind auch „Cloud“-Lösungen möglich?
Ja. Im Zuge der Technologieoffenheit sind auch fernverbundene Technische Sicherheitseinrichtungen und Komponenten von Technischen Sicherheitseinrichtungen möglich. Bei dieser Art einer Technischen Sicherheitseinrichtung muss jedoch auch in der Kasse oder dem Kassenverbund eine zertifizierte Sicherheitsmodulanwendung eingesetzt werden, über welche die sichere Anbindung des fernverbundenen Hardware-Sicherheitsmoduls erfolgt.

So, you need a certified "Sicherheitsmodulanwendung" locally that connects with the certified cloud solution.

Unfortunately, this makes a software based POS solution challenging in terms of certification requirements.
