### ISSUE TITLE
Feature request: populate the invoice generated from the project/timespent view with period of services invoiced

### ISSUE THREAD

**Issue by isamuse2** [Dolibarr/dolibarr#19913]
When creating an invoice from the time spent view of projects, the invoice has to be edited to add the period of time being invoiced.

It would accelerate the generation of invoices to directly integrate in the invoice the period of time which is concerned. This would allow to fill in automatically, at the level of the description line of the invoice the mention:"If product is a service with limited duration: From DD/MM/YYYY to DD/MM/YYYY"

As a consequence, if the invoice concerns time spent from Nov. 3, 2021 to Jan. 15, 2022, il would appear in the invoice “(From 03/11/2022 to 15/01/2022)”.

When time spent are filtered with a period of time (for instance the last month), it would even be better, to “populate” the invoice with the filtered period. Thus, if time if filtered for January 2022, the invoice would indicate “(From 01/01/2022 to 31/01/2022)”.

**Comment by joanahead** [comment]
Hy @isamuse2 
in my opinion some of the requests you recently made should be covered by Dolibarr.
In the meanwhile, we can help you with a custom-made solution.
Let me know if that's the case please.

**Comment by isamuse2** [comment]
Hi @joanahead 
Not sure to understand exactly your message! But I'm not looking for a "meantime" solution.

**Comment by joanahead** [comment]
@isamuse2 we can develop custom-made solutions, feel free to contact me (go to https://github.com/joanahead) if you want to talk about that.
