### ISSUE TITLE
Apply a discount on all the lines of an invoice or an estimate

### ISSUE THREAD

**Issue by Nexyll** [Dolibarr/dolibarr#19915]
# Feature Request

As it is already possible for taxes, it would be very useful to be able to apply a reduction on all the lines of an invoice or an estimate.

## Use case

I know that it's already possible to associate a discount by default on a customer but this functionality does not necessarily correspond to the following scenario: 

The customer has no default discounts but for a particular project he requests a quote with a constrained budget, so we apply a discount on the whole of this quote without this discount being valid on the next projects of the customer. 

## Suggested implementation

I don't know the dolibarr code base very well, I tried to look a little on my side but nothing probing. 

For now, I see 2 possible implementations :
- The first one, which would be the simplest, would be to reuse the existing operation on taxes, i.e. in the header of the table, add a button that allows you to "edit the value for all the rows" and that would therefore apply the discount to all the rows of the invoice, which would be the same as creating a global discount, I think this is the simplest implementation.
- The second solution would be to add a notion of global reduction on the amount of the invoice.

**Comment by dpriskorn** [comment]
I also need this in my business.

**Comment by Nexyll** [comment]
Implemented with #20658
