### ISSUE TITLE
Feature request : populate the invoice generated from the project/timespent view with additional data

### ISSUE THREAD

**Issue by isamuse2** [Dolibarr/dolibarr#19912]
When creating an invoice from the time spent view of projects, the invoice has to be edited to add Payment Terms and Payment type, even when this information is already integrated in the customer tab for this third party.

Therefore this generation of invoice does not fully integrate the information of the client.

Allowing to populate the invoice with this data of payment terms and type would improve Dolibarr's behaviour

**Comment by rycks** [comment]
Fix is in PR #22591
