### ISSUE TITLE
Don't have permission to delete / validate inventory when enable advanced permission

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#19911]
# Bug
[*Short description*]
When enable advanceed permission , you will be not able to delete an inventory even you are admin . 
But if you disable advanced permission , then you could delete an inventory .
And there is no validate permission for usr or group permission .
## Environment
- **Version**: 14.0.3
- **OS**: windows 7 sp1 , debian 10
- **Web server**: Apache/2.4.41
- **PHP**: 7.4.1
- **Database**: MariaDB 5.5.5-10.4.11
- **URL(s)**: /product/inventory/list.php?leftmenu=stock_inventories
-                   /user/perms.php?id=8

## Expected and actual behavior
[*Verbose description*]
Should have  options to enable or disable " Delete inventories (Permision available in Advanced permission mode only) "  and " Validate inventories (Permision available in Advanced permission mode only) " permissions in user and group permission tab .
## Steps to reproduce the behavior
[*Verbose description*]

Enable advanced permission and create a new inventory . Then try to delete it in inventories list page .

**Comment by ksar-ksar** [comment]
Hello,

I think it has been corrected on V14.0.5, please update.

**Comment by trekmorris** [comment]
Hi

I have the other dolibarr with v14.0.5 , but still has same issue .
And i have tried v 15 beta , also has this issue .
![image](https://user-images.githubusercontent.com/78349579/150882037-2c0b43dc-10ca-4cc2-afd8-d3b36ea83c2f.png)
![image](https://user-images.githubusercontent.com/78349579/150882124-e3edffe5-dae8-42a6-900e-a785c3a2f1b5.png)
