### ISSUE TITLE
selling price of kit products

### ISSUE THREAD

**Issue by chente38** [Dolibarr/dolibarr#19945]
### Bug

HI,

I have an issue using kit product (or maybe it's not possible. with dolibarr out of the box)

I have a virtual/kit product composed of several subproducts inside.
Each  subproducts has a sell price wich is dynamic(it's a calculated price which is modifided when the value of a field change)

My issue is :

I would like that the Selling price  of a kit product be the Total of subproducts selling prices
If the price of a subproduct change, the price of the kit price change by itself.

Does anybody know how to do it please?

Thank a lot,

### Environment Version

14.05

### Environment OS

ubuntu

### Attached files

[](url
![Capture d’écran 2022-01-26 164111](https://user-images.githubusercontent.com/64938774/151259497-d3bff78a-86b2-4fc1-92af-4b117253ef11.png)
)

**Comment by edupulpillo** [comment]
this feature is very useful

**Comment by edupulpillo** [comment]
this feature is very useful, any news?

**Comment by edupulpillo** [comment]
this feature is very useful
