### ISSUE TITLE
[ical export] date export bug when events are "all day events"

### ISSUE THREAD

**Issue by jbfrys** [Dolibarr/dolibarr#19942]
### Bug

When I create an "all day event", the date is wrongly exported on ical.

### Environment Version

14.05

### Environment OS

Dolicloud

### Environment Web server

Dolicloud

### Environment PHP

Dolicloud

### Environment Database

Dolicloud

## **example:**

I created an event on _27/01/2022_ :
![image](https://user-images.githubusercontent.com/59099394/151217914-2a2f687d-86d2-438c-8998-41e996e111a1.png)

But when I do export it with ical link, the date is _26/01/2022_
![image](https://user-images.githubusercontent.com/59099394/151217939-9cf8e1a8-e219-4971-804e-8854e1820a94.png)

### Steps to reproduce the behavior

- create an event.
- select "all day event"
- use ical link given in _/admin/agenda_xcal.php_
- export with ```wget "https://link/ical/" -o output-file``` for example
- compare date in Dolibarr and in **output-file**

**Comment by ksar-ksar** [comment]
Hello,

Did you ask the question to Dolicloud ?

**Comment by jbfrys** [comment]
Hello,

No I didn't.
I'll do that today.
