### ISSUE TITLE
Variable Substitution - Project Variables Not Working

### ISSUE THREAD

**Issue by playcock** [Dolibarr/dolibarr#19953]
### Bug

The following variables do not work in email templates.
```
__PROJECT_ID__
__PROJECT_REF__
__PROJECT_NAME__
```

### Environment Version

13.0.1

### Environment OS

Ubuntu 18.04.5 LTS

### Environment Web server

Apache/2.4.29 (Ubuntu)

### Environment PHP

PHP 7.2.24

### Environment Database

MariaDB

### Environment URL(s)

/admin/mails_templates.php

### Expected and actual behavior

The following Variable Substitutions are not populating the Project Emails as expected:
```
__PROJECT_ID__
__PROJECT_REF__
__PROJECT_NAME__
```
When using any of the above variables, the email message body just prints their key.
Example of variable in an email message:
![image](https://user-images.githubusercontent.com/9416592/151410574-6fe3de5a-327b-4b13-a2b6-7c646fd582bc.png)

The expected behavior would be:
Print out the Project id for `__PROJECT_ID__`
Print out the Project ref for `__PROJECT_REF__`
Print out the Project title for `__PROJECT_NAME__`

I am pretty confident that the following lines in  `htdocs/core/lib/functions.lib.php` never get hit:
```
if (is_object($object->project))
{
	$substitutionarray['__PROJECT_ID__'] = (is_object($object->project) ? $object->project->id : '');
	$substitutionarray['__PROJECT_REF__'] = (is_object($object->project) ? $object->project->ref : '');
	$substitutionarray['__PROJECT_NAME__'] = (is_object($object->project) ? $object->project->title : '');
}
if (is_object($object->projet))	// Deprecated, for backward compatibility
{
	$substitutionarray['__PROJECT_ID__'] = (is_object($object->projet) ? $object->projet->id : '');
	$substitutionarray['__PROJECT_REF__'] = (is_object($object->projet) ? $object->projet->ref : '');
	$substitutionarray['__PROJECT_NAME__'] = (is_object($object->projet) ? $object->projet->title : '');
}
```
I will note that even though the following code does not exist in  `htdocs/core/lib/functions.lib.php`, it will print out the expected values in Project emails when they are added outside of the conditional blocks for `if (is_object($object->project))` and `if (is_object($object->projet))`:
```
$substitutionarray['__PROJECT_ID__'] = $object->id;
$substitutionarray['__PROJECT_REF__'] = $object->ref;
$substitutionarray['__PROJECT_NAME__'] = $object->title;
```

### Steps to reproduce the behavior

Create a project email template with any of these variables:
```
__PROJECT_ID__
__PROJECT_REF__
__PROJECT_NAME__
```
Send a Project email using the email template.

**Comment by playcock** [comment]
Bug description updated.

**Comment by carmelchas** [comment]
From what I can see in the report the problem is that the PROJECT substitutions are only provided when $object "Has-A Project".   There is not logical code-block to provide substitutions when $object "Is-A Project".

For example:

if (is_object($object) && get_class($object) === 'Project')
{
	$substitutionarray['__PROJECT_ID__'] = $object->id ;
	$substitutionarray['__PROJECT_REF__'] = $object->ref ;
	$substitutionarray['__PROJECT_NAME__'] = $object->title;
}

**Comment by mikeemike7** [comment]
this is still a bug on dolibarr 18.0.1
:-(
