### ISSUE TITLE
getFieldList() in commonobject.class is protected, but should be public?

### ISSUE THREAD

**Issue by kubajznik** [Dolibarr/dolibarr#19959]
### Bug

getFieldList() is defined in commonabject.class.php as a protected function.
When I create a new object and I use 
    // Build and execute select
    $sql = 'SELECT ';
    $sql .= $object->getFieldList('t');
I get the error, that it is protected. Is that by design?
Changing the function to public solves the issue ...

Thanks,
Kuba

### Environment Version

14.0.5

### Environment OS

Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64

### Environment Web server

Apache

### Environment PHP

7.3.33

### Environment Database

MySQL 	5.7.36-1

### Expected and actual behavior

Expected:
 // Build and execute select
    $sql = 'SELECT ';
    $sql .= $object->getFieldList('t');
works.

Actual:
throws error because function is protected.

### Steps to reproduce the behavior

Create new object in module and open object_list.php

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/16625
