### ISSUE TITLE
No include of Lots / Serials on invoice when generated from shipment

### ISSUE THREAD

**Issue by fbagnol** [Dolibarr/dolibarr#19968]
### Bug

I active the global INVOICE_INCUDE_DETAILS_OF_LOTS_SERIALS

My shipment order have serial number but when I create the invoice from the shipment order screen serial number is not reported.

### Environment Version

14.0.5

### Environment OS

Debian 10

### Environment Web server

Nginx 1.20.1

### Environment PHP

7.3.19

### Environment Database

MariaDB 10.3.22

### Expected and actual behavior

If the global INVOICE_INCUDE_DETAILS_OF_LOTS_SERIALS is activated when an invoice is created from the shipment order, Lots and Serials presents on shipment line description have to be reported on invoice line description.

The actual behavior is there is no report.  

### Steps to reproduce the behavior

- Have product with serial managment
- Have stock of product with serials
- Create a shipment of this product and select the serial number involved
- Create an invoice from the shipment screen

**Comment by FHenry** [comment]
This "hidden" option is not documented in https://wiki.dolibarr.org/index.php/Setup_Other and as I according what I see in the code it cannot work.

**Comment by BebZ** [comment]
INVOICE_INCUDE_DETAILS_OF_LOTS_SERIALS
check without misspelling maybe ?
INVOICE_INCLUDE_DETAILS_OF_LOTS_SERIALS
but i never saw this magic formula anywhere yet

**Comment by fbagnol** [comment]
> This "hidden" option is not documented in https://wiki.dolibarr.org/index.php/Setup_Other and as I according what I see in the code it cannot work.

Why it cannot work ?

**Comment by FHenry** [comment]
@BebZ  it's INVOICE_INCUDE_DETAILS_OF_LOTS_SERIALS in the code. but it's a not documented feature and a not working peace of code
@fbagnol it cannot work because the feature is not correctly coded. $object->lines[$i] do not exits here in the code.... I will probably make a PR to remove it completly

**Comment by Basti-Fantasti** [comment]
@FHenry imho it would be better to have this functionality working in Dolibarr instead of removing this option totally.
I'm currently trying to find a solution to have the serial number printed on our invoices, that's how I stumbled upon this issue.

**Comment by FHenry** [comment]
Yes, I understand, but actually this is a not working code that call undefined variables... To make it work there a half/one day work

**Comment by FHenry** [comment]
A work around is to add thedelivery note PDF, where part num are printed, in the invoice mail.

**Comment by Basti-Fantasti** [comment]
Yes that's a feasible workaround, to attach the delivery note together with the invoice.
Maybe there will be an implementation of this feature in any way in a future version.

**Comment by FHenry** [comment]
Same between 0.5 or 1 day of work, may be someone will pay for it...

**Comment by Basti-Fantasti** [comment]
is there some defined way on how to pay for official changes?
I'm not so much into PHP, that's why I can't do it on my own and create a PR

In parallel I'm currently checking if it's mandatory to have serial numbers on the invoice when exporting products from the EU to 3rd countries. If this is not mandatory, I think we can go with adding the delivery note to the parcel.
