### ISSUE TITLE
Sales/buy/stock/standard units

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#19969]
### Feature Request

Hi,

some users experiment a problem on the forum (and other users are used to work with actual feature ;) ), and it seems that dolibarr do not answer with any feature:
**Sales/buy/stock/standard units** (and others ?)

As an idea, here is a first proposal:

I experiment this feature on several ERP and i think a simple answer could be:
- add a column in the units dictionary (llx_c_units) "ref" : id of a product/service (can be null)
- add a column in the units dictionary (llx_c_units) "coef" : like the existing one, but "double" format
- add a column in the units dictionary (llx_c_units) "standard_unit" (can be null...for a standard unit)
- the primary key is "ref" + "unit id" +"standard_unit"
This could be set up on an other table : the existing one could be for "standard units", the new one for "specific units for a product".

- add column in products table "sales_unit" / "buy_unit" / "stock_unit" / "standard_unit"
- add column in each object table (commande lines, invoice line, stock, etc..") : id from llx_c_units
(coef could be stocked in these tables for performance purpose, i don't know)

Rule:
- set each product with a standard unit : from dictionary with "ref" null -> every other units are set by default to this unit)
- if necessary, set others units (sales/buy/stock) to a unit with ref=null or a coef relative to the standard unit (ref = his own id)
- automatically have the good unit in the different workflows (can be modified during lines creation/modify)

Advantage:
- units from imperial system are no longer a particular case
- a same unit can have different coef for each product (ex: 1 "piece" of wood A is 3.5 "m2", 1 "piece" of wood B is 2.3 "m2", etc..)
- it improves user experience for sales and purchase workflow (i stock "piece", but i buy "box" ans i sell "m2")
- inventory are easer : you count what you see, not what dolibarr know as a standard unit
- as a next step : prices could be impacted : i have "piece" of XXX, i can sell "box of 6" or "box of 12" or "piece" with different price
- etc..

I know that it's a hard work, cause it modify lot of screens, tables and php code.... but :
Do you think that is a good project to work on ?
Do you think it can be improved by a crowdfunding ?

**Comment by ladromelaboratoire** [comment]
As a way to add use cases. We are currently implementing Dolibarr as sell/purchasing ERP in addition of our LIMS (analytic ERP). A strong communication is needed between the 2 of them and @scopen-coop is taking care of that.

However, we are facing an issue regarding stock management. Developping the feature out of the core system seems to be a short term idea.

Here an example of our use cases to illustrate our need.

We are purchasing reagents, small analysis materials, liquid nitrogen and gas such as argon. Let's say the purchasing units are :
- reagents : 5L bottles
- Small materials : big box of 100 boxes of 50 elements
- liquid nitrogen : raw delivery of 5 tons
- argon : raw delivery of 5m3

Liquid Nitrogen and Argon are consumed by analysis machines on a basis of mm3 per sample. The LIMS need to consume stock on its unit per analysis.

Team members are grabbing in stock a box of small material and using each item for one analysis. This means LIMS can decrease stock based on number of analysis done in an automatic way. This will trigger the low stock alert when needed and improve cost accounting.

Reagents are quite a good example too. We are buying a box of 6 bottles of 5L. The team member is using one ottle at a time. But regarding each analysis machine we can use between 2 and 20ml per sample. This means some machines are using a bottle per week, some others 1 per day. To avoid out of stock condition, we need to consume the bottles on the "per sample" basis : ml per each analysis.

An improved way to manage stock which takes care of suppliers specifities and allows us to consume stock anther way would help us, and I think, other users.
@Arre8 gave a really good idea of improvement

**Comment by lmag** [comment]
@FHenry
