### ISSUE TITLE
Cannot install Dolibarr on Fedora 34

### ISSUE THREAD

**Issue by vmario89** [Dolibarr/dolibarr#19967]
### Bug

Doilbarr can't be installed because php-imap is missing.

### Environment Version

14.0.5-0.4

### Environment OS

Fedora 34

### Environment Web server

nginx

### Environment PHP

7.4

### Environment Database

PostgreSQL

### Environment URL(s)

n.a.

### Expected and actual behavior

Doilbarr should install without error, but it does not. Instead:
```
yum install dolibarr-14.0.5-0.4.noarch.rpm
Letzte Prüfung auf abgelaufene Metadaten: vor 0:52:41 am So 30 Jan 2022 23:12:16 CET.
Fehler: 
 Problem: conflicting requests
  - nothing provides php-imap needed by dolibarr-14.0.5-0.4.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```

I cannot install php-imap module:
```

dnf install php-imap
Letzte Prüfung auf abgelaufene Metadaten: vor 0:52:57 am So 30 Jan 2022 23:12:16 CET.
Keine Übereinstimmung für Argumente: php-imap
Fehler: Es konnte kein Treffer gefunden werden.: php-imap

```

### Steps to reproduce the behavior

```
wget https://deac-fra.dl.sourceforge.net/project/dolibarr/Dolibarr%20installer%20for%20Fedora-Redhat-Mandriva-Opensuse%20%28DoliRpm%29/14.0.5/dolibarr-14.0.5-0.4.noarch.rpm

yum install dolibarr-14.0.5-0.4.noarch.rpm
```

**Comment by ksar-ksar** [comment]
Hello,

php-imap has been removed from FEDORA project : https://bugzilla.redhat.com/show_bug.cgi?id=1956278

But you can still install it manually : https://rpmfind.net/linux/RPM/remi/fedora/34/x86_64/php-imap-7.4.27-1.fc34.remi.x86_64.html

**Comment by lastmikoi** [comment]
Hello,

Been hitting on this issue on RHEL8, a Fedora derivative, while trying to set up the mail fetch module.

> Hello,
> 
> php-imap has been removed from FEDORA project : https://bugzilla.redhat.com/show_bug.cgi?id=1956278
> 
> But you can still install it manually : https://rpmfind.net/linux/RPM/remi/fedora/34/x86_64/php-imap-7.4.27-1.fc34.remi.x86_64.html

Excerpt from this bug report, directly from the (very kind) maintainer of the php-imap package you linked right after that

> The main issue is that uw-imap (used by imap) extension is a dead project, not maintained for >10 years
> 
> Nobody serious should rely on it
> 
> As uw-imap have been removed from the distribution, php-imap also

I've noticed that another imap library, that doesn't rely on the php-imap extension, has been added as a dependency of dolibarr to handle OAuth2 IMAP providers: https://github.com/Dolibarr/dolibarr/pull/21766

While I lack the time and expertise to migrate the current emailcollector to not require the php-imap extension (by re-using the webklex/php-imap library), I do believe marking this issue as `Won't Fix` to be detrimental when it comes to allowing someone to implement this needed change.

**Comment by HLFH** [comment]
@lastmikoi Hello. I created the issue: https://github.com/Dolibarr/dolibarr/issues/24765
