### ISSUE TITLE
Enable Rich edit on initial message when creating a Ticket 

### ISSUE THREAD

**Issue by freechelmi** [Dolibarr/dolibarr#19973]
### Feature Request

So far I cannot create a ticket with a http link as the initial message does not permit rich text

**Comment by dolibit-ut** [comment]
Hello, this feature exists.
But you must go to module FCKeditor and have to activate it for Tickets.

But you point to a small 'bug':  
FCKeditior is disabled for Tickets at default - we should check if it is better so or enabled.
And so if you create a Tocket you have no FCKeditor. 
But if you answer or work with the Message you have access to FCKeditor - although it is set as disabled.

I create a Bug entry.
