### ISSUE TITLE
Cannot generate PDF for custom module object

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#19970]
### Bug

When creating a custom module and object for it, after a card is created, on validation PDF is autogenerated. However, when manually trying to generate PDF nothing happens and no errors in the LOG file. Tested on 2 different installations.

Also, the autogenerated PDF is not shown on the "Linked files" block on the card page but is present on the "Linked files" tab.

### Environment Version

13-14

### Environment OS

Windows NT DESKTOP-VVIBA8V 10.0 build 22000; Linux web.shhservice.com 5.4.0-91-lowlatency #102-Ubuntu SMP PREEMPT

### Environment Web server

Apache/2.4.41

### Environment PHP

7.3.12; 7.4.26

### Environment Database

5.5.5-10.4.10-MariaDB; 5.5.5-10.5.13-MariaDB

### Expected and actual behavior

When clicking on generated a PDF file have to be generated

### Attached files

[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/7976582/dolibarr.log)

**Comment by AleaddineElAji** [comment]
Le bug est toujours actif, le 05/09/2024... 
Problème viens du fait que module-xxx.php est pas généré.
Apres génération et paramétrages, le problème persiste.

**Comment by AleaddineElAji** [comment]
de ce que j'ai compris, cest un probleme de 'diroutput', il y a conflit entre le lieu que je définit comme dossier de stockage, et le lieu natif dolibarr..
