### ISSUE TITLE
ODT Tags broken in odt template bom

### ISSUE THREAD

**Issue by csteh** [Dolibarr/dolibarr#19999]
Can not use product description in odt template bom. The only working substitution in line is ref with tag `{line_fulldesc}`

### Environment Version

14.0.5

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.1.33

### Environment Database

MySQL or MariaDB 5.6.32-78.1

### Environment URL(s)

/bom/bom_card.php

### Steps to reproduce the behavior

1 - Create ODT doc template following tutorial [Create ODT Document](https://wiki.dolibarr.org/index.php?title=Create_an_ODT_document_template)
2 - Use this code to write line of object 
```
[!-- BEGIN row.lines --] 
[!-- END row.lines --]
```
3 - Inside line of object insert any of these tags 
```
{line_fulldesc}
{line_product_ref}
{line_product_label}
{line_desc}
```
4 - Upload the new ODT template into folder ../documents/doctemplates/boms/
5 - Go to MRP
6 - New bill of material
7 - Create
8 - Generate odt document
9 - View and print document with Apache-Openoffice Writer

### Attached files

![bom-card](https://user-images.githubusercontent.com/34811131/152675175-6f5398bf-598d-4c1d-9660-a985e1f349a2.png)
![bom-odt-setup](https://user-images.githubusercontent.com/34811131/152675188-7c2c7325-5c10-4ed6-b9c5-0cd2760213a8.png)
![bom-odt-return](https://user-images.githubusercontent.com/34811131/152675211-d35773e3-a0ad-46a0-bdb0-e5dbfe319d06.png)

**Comment by vmaury** [comment]
Hi,
I made a try on developp version today,it seems to be ok.
You've to be very carefull with the tags in ODT doc : use Shift+Ctrl+V to paste, and /or use the Ctrl+M to remove direct formatting from Tags, may be this cause the problem.
Could you please re-check ?
