### ISSUE TITLE
Clone product doesnt copy status and status_buy

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#19991]
### Bug

When cloning a product, its statuses  ("status" ie (not)in sale), and "status_buy") are reseted.
May be is there a reason, but it's not very logical ...

To correct it, delete or comment folowing lines in /htdocs/product/car.php: (line #688 in trunk)
```
// Action clone object
[...~ 10 lines ..]
**$object->status = 0;
$object->status_buy = 0;**
```

### Environment Version

all

**Comment by aljawaid** [comment]
I think that is intentional.... for me in my use it makes perfect business sense.  One the product is cloned, the cloned version should be checked and modified.
