### ISSUE TITLE
Replenishment proposal with running "Manufacturing Orders" not correct

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#20004]
### Bug

I think this Replenishment proposal ist not correct in this view (it is no action for this product required):
![image](https://user-images.githubusercontent.com/78662388/152704630-d06abfae-7060-4f04-9056-ecd364f0d6e9.png)

For the product is a Manufacturing Order running (i think this must filtered on the Replenishment):
![image](https://user-images.githubusercontent.com/78662388/152704716-0c26594f-f690-4379-a836-eec0699d493e.png)

In our case with many many Manufacturing Orders will the replenishment view really confusing.

I think the MO-Module is not observed in the SQL-Query:
![image](https://user-images.githubusercontent.com/78662388/152704971-6d5b1940-7857-4646-ae50-058417e4d005.png)

I hope you understand my issue.
P.S.: Is my first time on an opensource project. If you need more informations please contact me.

Best regards
Christian

### Environment Version

14.0.5

**Comment by Humml87** [comment]
Is this a bug? If it is a bug, than i can try to fix this. Please give me a feedback if you know something about this.

**Comment by eldy** [comment]
Just by reading the old code i think your fix is good.
Old code was doing 
if a is null then 0 else b
Looks strange. Your fix do
If a is null then 0 else a
It has a sense and confirm the comment saying we need the if to always get a numeric value even if null. Can't tell if this business result is the one expected but can confirm that the old code was strange.
