### ISSUE TITLE
Ckeditor 4 : WebSpellChecker is END-OF-LIFE

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#20011]
### Bug

htdocs/includes/ckeditor/ckeditor/plugins/wsc/ is END-OF-LIFE
https://webspellchecker.com/blog/2020/12/02/end-of-life-for-spell-checker-dialog-plugin-for-ckeditor-4/

When you click on "Check Spelling"
![image](https://user-images.githubusercontent.com/35605507/152798713-7e43b51a-0de1-4b81-a7f1-119f62ddadde.png)

Then you have any empty pop-up : 
![image](https://user-images.githubusercontent.com/35605507/152798120-900e6073-1299-40dc-b24e-bf0769c7397b.png)

And that in the console : 
![image](https://user-images.githubusercontent.com/35605507/152798255-7ddf904b-edec-4560-9458-2d922c65ef0b.png)

https://www.webspellchecker.net/spellcheck31/lf/22/js/wsc_fck2plugin.js

### Environment Version
V14.0.5

### Environment OS
Debian 10

### Environment Web server
Apache

### Environment PHP
V7.3

**Comment by rycks** [comment]
CKEditor was upgraded to version 4.18.0 into dolibarr 17
