### ISSUE TITLE
PMP and PO discount

### ISSUE THREAD

**Issue by mverove** [Dolibarr/dolibarr#20029]
### Bug

New PMP product doesn't include discount in a PO Line.

### Environment Version

14.0.5

### Expected and actual behavior

After confirming reception based on purchase order including discounts, PMP should be updated based U.P. and discount.

### Steps to reproduce the behavior

1. create product in catalog
2. assign a vendor price (=10€) to this product
3. create a PO to buy 1 product unit with a 50% discount on the PO line related to this product
4. Proceed to Reception
5. New PMP product should be 10/2=5€ but PMP is 10€

**Comment by Jean-BaptisteDes** [comment]
Same issue on V13.0.5
