### ISSUE TITLE
Bug: Accuracy fails in budget and invoice detail

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#20023]
# Bug
Unit prices are set to 8 decimal places.
When entering the products that in the database the 8 decimals of the products are seen.
When adding a detail to the budget it only takes 2 decimal places.

## Environment
- **Version**: 14.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /comm/propal/card.php?id=1477

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
Attached budget detail and how it looks in the database propaldet
![Presupuesto - Ficha - Google Chrome](https://user-images.githubusercontent.com/53640168/153082962-7e2727f2-f559-4743-b65b-7836082d9fb8.jpg)
![propaldet  phpMyAdmin 4 9 7](https://user-images.githubusercontent.com/53640168/153083469-6ca04ad5-a820-4aa5-9969-61fc377f0ad1.jpg)

**Comment by joanahead** [comment]
Dolibarr 14.0.3 here. 
Set a service at 10,0001€ and tried to add it to a client propal...
![image](https://user-images.githubusercontent.com/36500882/154449634-bc2b7a90-abfc-4d62-9b71-af441196fcc2.png)

As you can see, the unit price and the line's base price (base imp.) are correctly calculated.
Seems like you could have some other config problem in your system.

Can you share the configuration you have in "limits and precision" so we can check?

**Comment by leninrivas** [comment]
Good day. I Attach precision.
![Configuración de límites y precisiones](https://user-images.githubusercontent.com/53640168/155352840-948a882f-e7af-440d-9f22-863eba3d8d37.jpg)

**Comment by leninrivas** [comment]
> 
The price of the product is 100 including tax, when adding the product the total shows 100.01 and that is because it does not take the other 6 remaining decimals.

**Comment by joanahead** [comment]
@leninrivas can you try increasing the "decimals shown in screen" (mostrados en pantalla) field? In my case it was 4 or 5 (don't exactly remember) and maybe that's the reason.
