### ISSUE TITLE
New Customer (Nouveau Tiers) - Societe \ Card

### ISSUE THREAD

**Issue by Sylvain089** [Dolibarr/dolibarr#20022]
### Bug

When you click on "New Customer", the drop list "Lead (Prospect) / Customer (Client)" is filled by "Lead (Prospect)" instead of "Customer (Client)"

### Environment Version

15.0.0

### Environment OS

Linux (NAS Synology)

### Environment Web server

Apache/2.4.46 (Unix)

### Environment PHP

7.4.18

### Environment Database

MySQL or MariaDB 5.5.5-10.3.29-MariaDB

### Environment URL(s)

htdocs/societe/card.php?leftmenu=customers&action=create&type=c

### Expected and actual behavior

Expected behavior : Customer (Client) instead of Prospect (Propsect)

To fix this issue, we need to modify the file : htdocs\societe\card.php
Line 1017
if (GETPOST("type") == 'c') {
			if (!empty($conf->global->THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT)) {
				$object->client = $conf->global->THIRDPARTY_CUSTOMERTYPE_BY_DEFAULT;
			} else {
				$object->client = 3;
			}
		}
becomes 	$object->client = 1;

### Attached files

Before modification : 

![image](https://user-images.githubusercontent.com/55165532/153048385-73ca6153-bd47-4e32-827b-c2af1b5ab97b.png)

After modification : 

![image](https://user-images.githubusercontent.com/55165532/153048591-f6ee88af-86a2-440c-9862-8df4207b7bb2.png)

**Comment by edupulpillo** [comment]
Hi.
Bug confirmed in our instance of Dolibarr.
Can you perform a PR or do you prefer i do it ?

**Comment by lmag** [comment]
It is ok for me in 15.0.2
