### ISSUE TITLE
PDF Configuration - French Translation

### ISSUE THREAD

**Issue by Sylvain089** [Dolibarr/dolibarr#20021]
### Bug

In Configuration \ PDF, "Print label of product item in Bold in PDF" is not translated in French (Translation/fr_FR/BoldLabelOnPDF) and "Print reference and period of product item in PDF" is not translated in French (Translation/_fr_FR/BoldRefAndPeriodOnPDF), with a new install (Files donwloaded on 20220208). 

### Environment Version

15.0.0

### Environment OS

Linux (NAS Synology)

### Environment Web server

Apache/2.4.46 (Unix)

### Environment PHP

7.4.18

### Environment Database

	MySQL or MariaDB 5.5.5-10.3.29-MariaDB

### Environment URL(s)

htdocs/admin/pdf.php?mainmenu=home

### Expected and actual behavior

A French translation.

### Attached files

![image](https://user-images.githubusercontent.com/55165532/153045168-c2cd3992-43c2-4904-8764-91485c4d6c91.png)

![image](https://user-images.githubusercontent.com/55165532/153045364-3ac087c2-cddc-4429-9c5d-94d3ddcfb1e2.png)

**Comment by priojk** [comment]
I noticed these two lines as new in Transifex on last Sunday. So, it might be fixed already, just not yet synchronized back into github.

Edit: I am just registered for the German translations. It seems as if there are a few recent translations still open in French, so probaby this still has to be translated in Transifex by someone.

**Comment by lmag** [comment]
Thank done
![image](https://user-images.githubusercontent.com/3288514/204061042-89e62bec-840c-4191-8f53-4b4a428c5631.png)
