### ISSUE TITLE
Bug: Dashboard is blank

### ISSUE THREAD

**Issue by madhupsrivastava** [Dolibarr/dolibarr#20050]
![image](https://user-images.githubusercontent.com/72741742/153686737-467ff4c2-1508-4614-8301-9c23f8ed36fe.png)

**Comment by atm-maxime** [comment]
Please seek help on the forum, this is not a Dolibarr issue but it's related to your environment. Maybe an external module not compatible with v14 ? (You have a menu starting with $conf-> for example...)

**Comment by fejzullan** [comment]
hi, i have same problem after manually translated, i don't know which file to search resolving this.
so only in one language translated dashboard is empy.
