### ISSUE TITLE
Improvements to multi-currency module

### ISSUE THREAD

**Issue by blftpe** [Dolibarr/dolibarr#20054]
### Feature Request

Automatically close the "remaining unpaid amount" for a supplier invoice where payment is made in local currency while invoicing is in a foreign currency (typically USD or EUR).
This can be done by recalculating the exchange rate based on the total amount paid in local currency.

### Use case

- When I purchase something in foreign currency, I (and many people?) will actually debit my account in local currency. Besides, it is usual to pay invoices in different slices (at order, at delivery, XX days after delivery). so there is not one exchange rate for one order, but several.
- Currently, if you enter a payment in local currency, Dolibarr will use the currency rate that has been set before and leave a surplus/minus vs the rate that you have entered earlier, and this is very time-consuming to handle, because even a mistake of 1 currency can't be accepted by accountants. Because there is usually not just one payment, the rate keeps changing.

- We can summarize as below:
**Dolibarr: 
FOREIGN AMOUNT INVOICE x EXCHANGE RATE  = GLOBAL AMOUNT TO PAY IN LOCAL CURRENCY
Reality: 
FOREIGN AMOUNT INVOICE / PAYMENT LOCAL CURRENCY [(1, rate 1)+(2, rate 2)+(3, rate 3)+...] = ACTUAL GLOBAL EXCHANGE RATE**

<img width="577" alt="Screen Shot 2022-02-13 at 11 01 34 AM" src="https://user-images.githubusercontent.com/4622001/153736572-c9d04a3e-2425-42f6-88f3-1d9875512e2f.png">

- BTW, handling this "remaining to pay" amount is made more difficult by the fact that exchange rate input is not bi-directional.
<img width="592" alt="Screen Shot 2022-02-13 at 10 55 51 AM" src="https://user-images.githubusercontent.com/4622001/153736706-113b8c1a-e256-4efc-b3c6-c9e6151e540e.png">

### Suggested implementation

1. My suggestion is, _when the currency of payment of a supplier invoice (or customer invoice) is different from the currency of order_, to just add a button to recalculate the transfer rate at the end of the transaction. See above screen shot the green "recalculate rate".
2. Ideally the amount in local currency of the purchasing order should be recalculated as well.
3. I also suggest to be able to enter a bi-directional exchange rate, because 1USD = 27.6 TWD is better than 1TWD=0.03623188406.

**Comment by josett225** [comment]
Still feature required.
