### ISSUE TITLE
Greek letters are sometimes HTML encoded in database

### ISSUE THREAD

**Issue by palexandridis** [Dolibarr/dolibarr#20068]
### Bug

Greek characters are HTML encoded in the database. This has been tested with the Tickets module when the Dolibarr language is set to Greek. 
Example: 
"&Tau;&omicron; ticket TS2202-0001 &delta;&iota;&alpha;&beta;ά&zeta;&epsilon;&tau;&alpha;&iota; &alpha;&pi;ό &tau;&omicron;&nu; &Alpha;&lambda;&epsilon;&xi;&alpha;&nu;&delta;&rho;ί&delta;&eta;&sigmaf; &Pi;έ&tau;&rho;&omicron;&sigmaf;"

This was observed in the tickets module since initially Dolibarr complained about not being able to store the note column of the  actioncomm table. After increasing the varchar length of column from 255 to 512, it successfully stored text in the note and label columns but in HTML encoding.

This could affect other modules, since the Statistics in the Thrid Parties module also display something similar (screenshot attached). 
 
Current config:
`$dolibarr_main_db_character_set='utf8';`
`$dolibarr_main_db_collation='utf8_unicode_ci';`

### Environment Version

Dolibarr 14.0.x

### Environment OS

Synology

### Environment Web server

nginx/1.16.1

### Environment PHP

7.4.9

### Environment Database

 10.3.29-MariaDB

### Expected and actual behavior

The characters should be stored in Greek UTF8 encoding and not HTML encoded.

### Steps to reproduce the behavior

0. Increase the length of note column in actioncomm table to 512
1. Set the language to Greek
2. Enable the Ticket module
3. Create a ticket
4. Mark the ticket as "read"
5. Observe the characters stored in the note and label columns in actioncomm table.

### Attached files

![εικόνα](https://user-images.githubusercontent.com/98951121/154016877-a752d92f-1d55-471a-890b-db4b29a14d5e.png)

**Comment by eldy** [comment]
With v15, the "note" field in actioncomm has type "text" so problem of size too small should be ok now in v15.

For the charset problem, did you create the ticket (step 3) from the backoffice or the public interface ?

**Comment by palexandridis** [comment]
Good news! We are planning on upgrading to v15 in the following weeks.
The issue appears when marking the ticket as read, not on the creation of the ticket. The letters when creating the ticket either from the public interface or the backoffice are correctly stored in the database. Only when marking the ticket as read from the backoffice the characters are stored in HTML encoding in the DB.
Please have a look at the attached screenshots. TS2202-001 was created (and deleted) from the backoffice and public interface.
![εικόνα](https://user-images.githubusercontent.com/98951121/155194138-ac57791b-5d8f-4911-9c7c-d4f5f3a234f0.png)

**Comment by palexandridis** [comment]
One additional comment, is that the llx_actioncomm table is updated only when creating/deleting/marking as read the ticker and not when assigning or changing any other status of the ticket.

**Comment by eldy** [comment]
Do you still have trouble of data stored in htmlentities instead of utf when setting a ticket in v16 to status Read ?

**Comment by palexandri** [comment]
Unfortunately yes. We are in 16.0.1 now. When marking the ticker as read, the label and note columns in the llx_actioncomm table are html encoded. I just made a test to verify. The first line is the creation of the ticket and the second line is marking the ticker as read.

![εικόνα](https://user-images.githubusercontent.com/2471109/196479686-ed4232fb-c04d-4f4e-a548-7fc0cb53e13f.png)

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by palexandri** [comment]
Hi,

We have switched to odoo since last year so I cannot test or verify the issue with v18.
