### ISSUE TITLE
Dolibarr installer does not mark php8 as unsupported

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#20091]
### Bug

php8 is unsupported according to the docs.
![image](https://user-images.githubusercontent.com/68460690/154351972-3dc980ac-db34-46c4-8311-1f5fb1bcbbec.png)
on the installer of 14.0.2 it has a green tick

**Comment by dolibit-ut** [comment]
It is not really a Bug. PHP 8 is not 'unsupported' - but not complete tested,
but most of the modules are already adapted and working.

**Comment by rycks** [comment]
Thanks, but now dolibarr 16 add php8 support :-)
