### ISSUE TITLE
User can edit or delete event that created by dolibarr system

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#20092]
### Bug

If user want to use agenda module and enable the permissions that are " Read actions (events or tasks) linked to his user account (if owner of event or just assigned to) " and "  Create/modify actions (events or tasks) linked to his user account (if owner of event) " , then user can edit the event created by dolibarr .
And if you enable the permission " Delete actions (events or tasks) linked to his user account (if owner of event) " , then user can delete the event created by dolibarr .

### Environment Version

v 14.0.3

### Environment OS

Deian 10 windows 7

### Environment Web server

 Apache/2.4.38 Apache/2.4.41 

### Environment PHP

7.4.1

### Environment Database

MariaDB 5.5.5-10.3.31

### Environment URL(s)

comm/action/card.php

### Expected and actual behavior

The user permission should not effect the dolibarr system auto actions .
Users should be not can create / edit / delete  events that created by dolibarr system .  

### Steps to reproduce the behavior

Create any proposal / order / ticket and valid it to create a event , then try to edit it .

**Comment by trekmorris** [comment]
the request is still relevant and not yet covered by latest stable version.

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
