### ISSUE TITLE
Block date bill

### ISSUE THREAD

**Issue by philou15** [Dolibarr/dolibarr#20090]
### Feature Request

Désolé, je ne pourrais pas ecrire en anglais.

Il serait bien de ne pas pouvoir daté une facture de la derniere validé dans le logiciel

Car cela peut provoquer des erreurs, surtout avec la lois anti fraude en france.

**Comment by WimpyMan** [comment]
Tu as une option dans le module facturation.

**Comment by philou15** [comment]
Je ne l'ai pas trouvé. J'ai poser la question sur le forum. Peut tu m'en
dire plus ?

Merci

**Comment by isamuse2** [comment]
Autre suggestion proche : pouvoir établir une facture récurrente pour une période de service passée. A ma connaissance, l'option de Dolibarr pour la génération automatique de facture porte exclusivement sur les périodes futures.

Other suggestion linked: being able to produce recurring invoices for a passed period of time. To my knowledge, Dolibarr's option to generate automatically an invoice only  concerns invoices for a future period of time.

**Comment by dnutan** [comment]
In the invoices module configuration parameters, there's this option that does what the OP asked:
![image](https://user-images.githubusercontent.com/15559754/211013443-4ff98674-7d61-4ef2-850f-c62e94c2d37c.png)

Another related option is to force invoice/bill date to validation date:
![image](https://user-images.githubusercontent.com/15559754/211014070-164950dd-f4e7-4a10-8ce6-4ee3f2db04bc.png)

As this feature request is already implemented the issue can be closed.
