### ISSUE TITLE
Flexible permissions for tags / categories module

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#20093]
### Feature Request

Can let specific user or group to create / read / edit or delete specific proposal / order / projects / product / service / event / ticket of specific tag or categorie .

### Use case

If i have proposal's tags as below and also has same tags in user :
proposal tags :
   a.service   a.1 service group 1  a.2 service group 2
   b.sales      b.1 sales group 1     b.2 slaes group 2
user tags :
   a.service   a.1 service group 1  a.2 service group 2
   b.sales      b.1 sales group 1     b.2 slaes group 2   

Then if user or group has same a.1  tag , then they can read all proposal with a.1 tag .
And they just can edit / delete the propal if that propal assigned to them .
Also they can't read propal with a.2 tag .
If this user or group has tag " service " , then they will can read proposals with a.1 and a.2 .

### Suggested implementation

Add this function in tags module , so people can choose enable this function or not .
Has a option " Tags permission control "
Has a option  " Auto add same tags of user when they create a new proposal / order / projects / event / ticket . "

**Comment by BebZ** [comment]
interesting feature, but has to absolutely deal with existing permissions, having a dynamic permission's list for tags ?
it can create a big mess for users having hundreds of tags, so has to be activated separately ?
I think Devs team wil not agree to add another layer of other types of permissions, or it will become very complicated for all objects to maintain.

**Comment by trekmorris** [comment]
Hi @BebZ 

Yes , it is a interesting feature , and i think it also a very important feature if dolibarr could be really used on a company .
As you know the dolibarr permission control is not so completely . 
In real world , the company will has several different departments , and it will be some people know some information , not information for all people .
For example , propopsal module , if you got service and sales departments , for some reason you will want service people can read the proposals about service only , or maybe you just want service can read the proposals about their own parts .

So i think if dolibarr can add this feature , then it will fix many usage problem in real life .

And it will be easier if you use tags module to get more permission control .

I think it should be need add a program judgment function to check if the user has same tags then return one code .
If user has the default permisson and get same tags , then the user can read / edit / delete the proposal / oder / ticket .....etc .   

Also , it will be more easier for future functions development , just need to add tags function then you will has flexible permission control .
