### ISSUE TITLE
llx_c_ziptown table seems empty

### ISSUE THREAD

**Issue by battosai30** [Dolibarr/dolibarr#20097]
### Bug

Hi,

Digging to find why I got no suggestion when I'm writing a zip code (creating a client for example) I found that llx_c_ziptown table seems empty. 

Any suggestion on how to solve that ?

### Environment Version

14.0.x

### Environment OS

Alpine 3.14 & Debian 10

### Environment PHP

7.4

**Comment by dolibit-ut** [comment]
It is not a Bug (more a missing Feature) - it is always empty. 
You can fill it own your own and then use - or look in Dolistore.com for Modules with filled Zip-Files for Countries.

**Comment by battosai30** [comment]
Ok but it was not like that before ? I have older instances, I never filled them and I have a complete zip code list

**Comment by atm-maxime** [comment]
Basically, when you entre a zip code or a town value on a form, Dolibarr searches through existing values in societe table.

**Comment by battosai30** [comment]
Yes yes I know but for one instance I get suggestions that I'm sure I never used ... Maybe Idon't remember but I added the plugin you suggest.

Thanks for your time :)
