### ISSUE TITLE
Bug: Forbidden You don't have permission to access this resource.  Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request

### ISSUE THREAD

**Issue by shabanialexandre** [Dolibarr/dolibarr#20106]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.27
- **Database**: MySQL or MariaDB 5.7.36-cll-lve
- **URL(s)**: /index.php?mainmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

Can you describe the problems ?

**Comment by dpriskorn** [comment]
Screenshot?

**Comment by shabanialexandre** [comment]
I generate an invoice is that I wish to see it that I receive this message

![image](https://user-images.githubusercontent.com/69487012/155278603-653f7830-5b4f-4cc4-a725-4e77c09e9d17.png)

after i get this message

![image](https://user-images.githubusercontent.com/69487012/155278969-91988169-b45a-4628-99ed-af1bdcdd290f.png)

**Comment by hregis** [comment]
@shabanialexandre can you check if you have an activated invoice model in invoice module setup

**Comment by shabanialexandre** [comment]
yes, 
as you can see below

![image](https://user-images.githubusercontent.com/69487012/155280835-c1eb28d5-6193-46f8-9f41-d1822564ad2a.png)

**Comment by hregis** [comment]
@shabanialexandre and the write permission in "documents" directories and sub-directories ?

**Comment by shabanialexandre** [comment]
yes i have all permissioms

![image](https://user-images.githubusercontent.com/69487012/155282097-ab6662e8-f88d-40cc-9cd7-884ceb9ffeda.png)

and precisely on the invoice sub-directory

![image](https://user-images.githubusercontent.com/69487012/155282723-425b2b6a-a153-4321-bdcd-24a50ad5a444.png)

**Comment by shabanialexandre** [comment]
the application is on an apach server

![appach_server](https://user-images.githubusercontent.com/69487012/155282990-398be94a-9752-459e-9411-0d8cb1b27e9d.jpg)

**Comment by hregis** [comment]
@shabanialexandre and show you the (PROV3) directory inside "facture" directory and show you the pdf and what is the rights for this file ?

**Comment by shabanialexandre** [comment]
YES,
![image](https://user-images.githubusercontent.com/69487012/155284525-a49f6054-30da-4082-a2c2-e1d8cc613132.png)

**Comment by shabanialexandre** [comment]
indeed, I use filezila for my various applications on the servers...

**Comment by hregis** [comment]
@shabanialexandre and inside (PROV3) directory ? pdf is here ?

**Comment by shabanialexandre** [comment]
yes it's

![image](https://user-images.githubusercontent.com/69487012/155285164-e3aeb225-b89c-4c4d-a2cb-44ee50f1d33a.png)

**Comment by shabanialexandre** [comment]
with all permissions

![image](https://user-images.githubusercontent.com/69487012/155285625-89f2ded7-4f96-425c-abd5-a1b2d2fd29c0.png)

**Comment by hregis** [comment]
@shabanialexandre it's a right problem with your server, not a Dolibarr problem !
check the .htaccess in your "documents" directory...
you should check the php errors in the apache logs...

**Comment by shabanialexandre** [comment]
yesterday while looking for how to solve the problem, I went to the administration tool of dolibarr / security info in order to read the recommendations available, may this can enlighten you to help me...

![image](https://user-images.githubusercontent.com/69487012/155287938-817d834a-3934-4767-a509-1d87394acd88.png)

**Comment by shabanialexandre** [comment]
![image](https://user-images.githubusercontent.com/69487012/155288206-eaa99e12-89b8-41a0-99ce-3d29e26319ee.png)
these are the two that require recommendations, can you help me exactly so that this problem can be solved properly?

**Comment by shabanialexandre** [comment]
these are the two that require recommendations, can you help me exactly so that this problem can be solved properly?

**Comment by hregis** [comment]
@shabanialexandre it is recommended to place the "documents" directory outside the web root (public_html) and modify the "conf.php" file accordingly

**Comment by shabanialexandre** [comment]
when I have already moved the documents directory outside the folder: '' public_html ''

I want to modify the file: conf.php

on the following lines:

![image](https://user-images.githubusercontent.com/69487012/155294557-c557d43e-7d26-41c7-8ed1-dcfbb862198a.png)

try to tell me if that's exactly it so i know what to do right now

**Comment by shabanialexandre** [comment]
I just moved the document folders outside of public_html

![image](https://user-images.githubusercontent.com/69487012/155297719-67f4ae93-0536-451f-90e7-b77d7b088883.png)


And here I modified the tree structure in the conf.php file

![image](https://user-images.githubusercontent.com/69487012/155298180-0cadaf45-aa30-4ac4-b09f-4b8962fbf89b.png)

I'm waiting for your answer because already I don't see any improvement

**Comment by hregis** [comment]
@shabanialexandre just change "$dolibarr_main_data_root", this the path of "documents" directory

**Comment by shabanialexandre** [comment]
already had no effect

![image](https://user-images.githubusercontent.com/69487012/155303679-1bf8bbff-fcf1-4167-82ae-c825d68940dd.png)
![image](https://user-images.githubusercontent.com/69487012/155303794-23aeeedc-ea42-4a4b-be21-4189a8686012.png)

**Comment by hregis** [comment]
@shabanialexandre see the php error log !

**Comment by dpriskorn** [comment]
We need the log from apache/php to help you further.

**Comment by dpriskorn** [comment]
@hregis I think we shoud close this and refer to ask for help in the forums. This is most probably not an error in Dolibarr

**Comment by shabanialexandre** [comment]
sorry I had an impediment to continue, I continue as soon as possible
