### ISSUE TITLE
Spelling Mistakes

### ISSUE THREAD

**Issue by ubaid1987** [Dolibarr/dolibarr#20102]
![image](https://user-images.githubusercontent.com/31791335/154497494-918198f6-6b47-47e9-9757-1b18296ed975.png)

Please check the highlighted spelling.

**Comment by priojk** [comment]
Spelling mistakes can easily be fixed on transifex.com, just set up an account.

**Comment by ubaid1987** [comment]
> Spelling mistakes can easily be fixed on transifex.com, just set up an account.

Yeah, I just highlighted to improve the quality of work. Anyhow, I am really impressed with this project. Really amazing.

**Comment by dpriskorn** [comment]
Actually this cannot be fixed in trnsifex because it is the original English string
