### ISSUE TITLE
Tracking of emailings on the contact tab

### ISSUE THREAD

**Issue by isamuse2** [Dolibarr/dolibarr#20101]
### Bug

When sending an emailing, in some case there is a tracking of the emailing on the contact tab and in some cases there is no tracking.

Watch the difference, for an emailing with **two contacts from the same third party** in the pictures attached.

![view](https://user-images.githubusercontent.com/51233081/154487466-3a51ef53-9927-4191-a6ce-bce6e885852a.png)

As a consequence, for the fist contact there is a possibility to know which emailing exactly he received whereas for the second contact, we only have the information that he received an emailing but NO reference to the specific emailing.

After investigating the issue, I have no idea where it comes from. It does not seem to be linked to the domain of the email address. For two contacts of the same third party (and same domain name), I have different behaviours: for one contact I have the tracking and not for the other one.
It does not seem either linked to the contact: for the same contact, I may have the tracking for one emailing but no tracking for another emailing. 

### Environment Version

Dolibarr 12.0.4

### Environment OS

Linux pasta.o2switch.net 3.10.0-962.3.2.lve1.5.26.3.el7.x86_64 #1 SMP Wed Aug 14 08:29:59 EDT 2019 x86_64

### Environment Web server

Apache 

### Environment PHP

 7.2.34

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB

### Expected and actual behavior

Expected behaviour: same behaviour for all contacts i.e. possibility to track the details of the email sent via emailing to a contact on the contact tab and in the agenda
actual behavior: no tracking of the email for some contacts

### Steps to reproduce the behavior

Send an emailing

**Comment by ksar-ksar** [comment]
Hi,

First thing to do is to update to at least V12.0.5

**Comment by isamuse2** [comment]
Sure!
Tested with v12.0.5 AND v14.0.5 (with all external modules of Dolibarr desactivated). Same behaviour.
