### ISSUE TITLE
Dolibarr 12+ regression fetch supplier order lines caused by PR #20028

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#20118]
### Bug

When PRODUCT_USE_SUPPLIER_PACKAGING enabled we get group by sql error.
Also after fixing groupby sql error, no lines are fetched anymore.

Caused by #20028 

### Environment Version

Dolibarr 12+

**Comment by noec764** [comment]
Thank you for your answer, 
Can you precise me where this bug appears? There are other problems with this conf, so I would like to know exactly what caused the bug

**Comment by fappels** [comment]
The bug appears when the conf is enabled and mysql is in strict mode. Not familiar with this feature, only noticed the sql error when loading someone's database with this feature enabled in my dolibarr dev. I always have mysql strict mode on for development because all should work fine in strict mode.

**Comment by noec764** [comment]
I can't reproduce this bug even if I am in strict mysql mode.

What version of dolibarr are you working on?
What page are you on when the error occurs?
Can you give me the sql error message you found and the sql query that triggers this error? 

I would also like to know your sql configuration, can you give me the result of the mysql query ``select @@sql_mode;``

**Comment by fappels** [comment]
my @@sql_mode: 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
![Purchase order - Card 3-2-2022 2-17-06 PM](https://user-images.githubusercontent.com/4573808/156368998-b87a2e21-8044-40b5-b8e6-d13afdcae6d5.png)

This is from dolibarr 15, but also had in on 14

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/156889862-ae3bdd50-c9e0-43cf-acea-01aa1516fedb.png)

**Comment by noec764** [comment]
@frederic34 Does your commit fix the bug?

**Comment by fappels** [comment]
For me the fix from @frederic34 fixes the sql bug, think other issues with this conf should be fixed in develop branch.
