### ISSUE TITLE
Feature request : Show product image in product listning

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#20123]
I would like to be able to chose to show the product image in the product listning - **URL(s)**: /myUrl/product/list.php

## Environment
- **Version**: 15.0.0
- **URL(s)**: /myUrl/product/list.php

**Comment by RomainDeschamps** [comment]
https://github.com/Dolibarr/dolibarr/pull/20017/

**Comment by hasse-basse** [comment]
Aha great, thank you. When can we expect it?

**Comment by hasse-basse** [comment]
Sorry, stupid question. It is already there! Thanks! I close the issue!
