### ISSUE TITLE
Change VAT Price error on Dolibar 15

### ISSUE THREAD

**Issue by Mendiaco** [Dolibarr/dolibarr#20129]
### Bug

When it tries to change price on a product, VAT is incorrect,  aplication modifies and his own.
21/5-2 are not correct values...

![Captura de pantalla 2022-02-21 a las 12 01 19](https://user-images.githubusercontent.com/59293221/154945942-8f6474a1-59b8-44c9-bdb7-f1ed6a7cd6bd.png)

### Environment Version

15.0

### Environment OS

OSX

### Environment Web server

MAMP

### Environment PHP

7.4.21

### Environment Database

Mysql

**Comment by dpriskorn** [comment]
Hi. I fid not understand. What did you expect and what happened instead? Could you add a better screenshot so we can clearly see the issue?

**Comment by Mendiaco** [comment]
Hi,
First sorry for my English I'm not a very english writer.
On dolibarr/product/price.php.
I Change Vat in my case at 21%.
But dolibar show me:  21/5.2/-19%
My instalatios was updated from dolibarr 14.

I have 2 instalations, and I obtain the same error.

**Comment by dpriskorn** [comment]
Have you customized the translation strings? Is this a UI issue (wrong column header as shown in the photo)?

**Comment by Mendiaco** [comment]
Yes:
When I change vat price in products: I obtain this SQL error:

`_> "Error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':-15:-9, localtax1_type='3', localtax2_type='5', fk_user=1, import_key=null WHER' at line 1"_`

It was all working Ok at version 14.04
