### ISSUE TITLE
HRM (Module)

### ISSUE THREAD

**Issue by pascal14633** [Dolibarr/dolibarr#20125]
### Bug

Hi, In the HRM section the Ref. # for application stock to (PROVx) never get an reference number and in this section the Doc template is not working.No error nothing append when you try to generate the form.  Fresh install v14 and v15. There also a problem with the ODT Templates in Recruitment setup also.

### Environment Version

v14 and v15

### Environment OS

Linux CRM 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64

### Environment Web server

Apache/2.4.52 (Debian)

### Environment PHP

7.4.25

### Environment Database

MySQL or MariaDB 5.5.5-10.5.12-MariaDB-0+deb11u1

### Environment URL(s)

recruitment/recruitmentcandidature_card.php?id=1&save_lastsearch_values=1

### Expected and actual behavior

The reference number never sitch from PROV to JOAyymm-nnnn  "Returns the reference number in the format JOAyymm-nnnn where yy is the year, mm is the month and nnnn is a sequential auto-incrementing number with no reset"

Document models Recruitment module
Standard PDF template or ODT Not Working

### Steps to reproduce the behavior

Nothing special it's not working

**Comment by atm-maxime** [comment]
Hi ! I can't reproduce your issue with the job candidature reference, if it's correctly setup, it's correctly generated.
I fixed the issue with documents models. There are no model available for now and the card was showing the models from the job position
