### ISSUE TITLE
Email collector fail on incorrect string value in email

### ISSUE THREAD

**Issue by freechelmi** [Dolibarr/dolibarr#20127]
### Bug

When receiving an HTML email from customer the mail collector failed to treat it : 

Incorrect string value: '\xF0\x9F\x98\x8A)<...' for column `dolibarr`.`llx_actioncomm`.`note` at row 1

I guess it is related to the presence of an emoticon ? 

After removing the emoticon and importing manually the message , it worked

### Environment Version

14.0.5

### Environment OS

Linux

### Environment Web server

Apache/2.4.38 (Debian)

### Environment PHP

7.4.25

### Environment Database

MySQL or MariaDB 5.5.5-10.6.5-MariaDB-1:10.6.5+maria~focal

### Expected and actual behavior

The email should be imported in the ticket 

### Steps to reproduce the behavior

insert an emoticon in a message

**Comment by atm-maxime** [comment]
The same kind of error happens if you try to copy/paste a text with an emoji in a note field on any object. This surely comes from the emoji, so we have to find a way to deal with them or discard them in the meantime

**Comment by freechelmi** [comment]
Thanks , I have to say that it is really rare that a client put an emoji on its message so low priority I would say
