### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ntbossmaster** [Dolibarr/dolibarr#20132]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[There is no update when i am using HRM Next Gestion External Module. I enter salaries , etc, but no updates even when i refresh.]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.27
- **Database**: MySQL or MariaDB 5.5.5-10.2.25-MariaDB-log
- **URL(s)**: /custom/grh/pointage/racapsp.php?idmenu=72&mainmenu=grh&leftmenu=

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by dpriskorn** [comment]
Could you add a title and a screenshot of the issue?

**Comment by daraelmin** [comment]
HRM Next Gestion is an external module as you mentioned. You should post your issue to the author of the module. We can't debug it as it is not part of the official dolibarr.
