### ISSUE TITLE
Ticket reply by email not linked to ticket ( but email collector does create the events )

### ISSUE THREAD

**Issue by freechelmi** [Dolibarr/dolibarr#20139]
### Bug

We received from the customer 2 replies by email to a ticket 

- the emails are treated by the email collector as they are moved and events are created
- However the events are not linked to the ticket 
- the customer use "laposte.net" , maybe the headers are modified and it could not link to the original email ? 

### Environment Version

14.0.5

### Environment OS

Linux

### Environment Web server

Apache/2.4.38 (Debian)

### Environment PHP

7.4.25

### Environment Database

MySQL or MariaDB 5.5.5-10.6.5-MariaDB-1:10.6.5+maria~focal

**Comment by atm-maxime** [comment]
If you look in the email headers, do you have something like "ticXXX" where XXX is the ticket ID ?
Can you give the email collector rule you're using ?

**Comment by freechelmi** [comment]
You mean X-Dolibarr-TRACKID: tic114@40d1b2d83998fabacb726e5bc3d22129

It was in the "new message" sent to the customer and was not in its reply on this message through laposte.net

**Comment by atm-maxime** [comment]
So I guess it's normal because the link with the ticket is made by the collector thanks to the tic114, this means the ticket ID 114 is to be linked. If laposte.net rewrites the email headers on a reply there's not much we can do...

**Comment by dpriskorn** [comment]
I agree, we can close this as invalid. The bug is not in D
