### ISSUE TITLE
NEW - Head contact

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#20137]
### Feature Request

I suggeste to create a link to a contact (head contact) like head quarter.

And a option to update automaticly a contact childs.

And other option delete head contact -> delete all childs contact

### Use case

I think this alleviates the problem visibly often encountered 1 contact belongs to one and only one third party.

### Suggested steps

Create link in database -> fk_head_contact
In card contact list of childs contact

**Comment by eldy** [comment]
Do you mean having a contact that is parent of other ?

**Comment by BB2A-Anthony** [comment]
Yes this it

**Comment by eldy** [comment]
Why not. 

It may be used to manage a hierarchy of contact into a given thirdparty.
But trying to use 1 contact for different companies is a very very bad idea. When the same physical contact is in 2 different company it is not the same role, also often not the same contact phone, address, etc;;, so it must be also remain 2 different address record.
Also this will bring a lot of problem (permission problem, pb with external contact, pb for import, ...) . This feature was already implemented in past and we have to remove it. It is not a so requested feature and when it is, it appears that it is to represent the same firstname and lastname only and role is different so keeping 2 different record was better and we revert to feature 1 contact for 2 thirdparties. A "link" without constraint may be a better implementation but it must be a hidden feature for the moment for 2 reasons:
- Some similar problem we got in past will reappears. 
- This feature is clearly not a feature that is requested by a lot of user (and when it is, 99.99% of time, it appears at the first need to change the phone, desk, email, in company one and not in company 2 that it was a bad idea).

You must first send a PR with database structure changes before submitting php code.

**Comment by BB2A-Anthony** [comment]
@eldy i understand i have create a PR for database structure

**Comment by BB2A-Anthony** [comment]
up

**Comment by eldy** [comment]
PR merged manually.
