### ISSUE TITLE
Invoices : Reactivate the action button 'classify to Paid'

### ISSUE THREAD

**Issue by FredBl79** [Dolibarr/dolibarr#20143]
### Bug

After migration to V14, we have lost the feature to classify an invoice to Paid directly on the invoice page. This remain a very useful feature when we do not manage accountancy into Dolibarr.
Now, we have to pay in order to have the classification 'Paid' on each invoice.

Can you reactivate the action button directly on the invoices as the previous Dolibarr version

Thanks

### Environment Version

V14

**Comment by atm-maxime** [comment]
What was your Dolibarr previous version? Because I think this has changed a long time ago.
Can you try the option INVOICE_CAN_SET_PAID_EVEN_IF_PARTIALLY_PAID

**Comment by FredBl79** [comment]
Hi,

V13, we still had the button on supplier invoice to classify to paid even
if you didn't do the payment.

Frédéric

Le mar. 22 févr. 2022, 20:54, Maxime Kohlhaas ***@***.***> a
écrit :

**Comment by atm-maxime** [comment]
Oh supplier invoices... You didn't mention that in your issue, I assumed customer invoice...
I'll check that

**Comment by FredBl79** [comment]
> Oh supplier invoices... You didn't mention that in your issue, I assumed customer invoice... I'll check that

apologizes.....let me know if I can support you.

Fred

**Comment by josett225** [comment]
Hi @atm-maxime ,
is there any chance to get this feature back? 
Best Regards

**Comment by ismailelahmadi** [comment]
> INVOICE_CAN_SET_PAID_EVEN_IF_PARTIALLY_PAID
I t works for me  v 15

**Comment by daGrumpf-bxp** [comment]
INVOICE_CAN_SET_PAID_EVEN_IF_PARTIALLY_PAID
doesn't work in v16
could some one reactive this feature ? set provider invoice without paiement action

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
