### ISSUE TITLE
Warning on Event Organization Module

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#20146]
### Bug

`Warning: Declaration of ConferenceOrBooth::fetch($id, $ref = NULL, $ref_ext = ‹  ›, $email_msgid = ‹  ›) should be compatible with ActionComm::fetch($id, $ref = ‹  ›, $ref_ext = ‹  ›, $email_msgid = ‹  ›, $loadresources = 1) in /htdocs/eventorganization/class/conferenceorbooth.class.php on line 243`

### Environment Version

V14.0.5

**Comment by eldy** [comment]
Seems fixed with v15
