### ISSUE TITLE
After upgrade (14 -> 15) shipping module breaks the weight unit

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#20142]
### Bug

v15.0.0

In here, we select "kg" and then modify:

![weight1](https://user-images.githubusercontent.com/11036018/155028836-ddaaaf08-fc56-4cf2-892a-dc5e84e7fd7b.png)
![weight2](https://user-images.githubusercontent.com/11036018/155028838-23a513c8-a46d-47bb-8981-83f35cbbe14a.png)

All is well. Then we click "Generate" to get a new PDF, and all of a sudden the weight unit is completely bonkers:

![weight3](https://user-images.githubusercontent.com/11036018/155028884-3185dade-d890-4167-94ce-6db3cd001b2a.png)
![weight4](https://user-images.githubusercontent.com/11036018/155028887-b5cf53ec-a56a-4691-b4d7-0f3f413d55d8.png)

The shipping module in use is "rouget" and we get the same error if we use module "espadon". We did not have this error earlier this morning when we used Dolibarr 14.0.3.

### Environment Version

15.0.0

**Comment by dpriskorn** [comment]
Thanks for the very clear issue with screenshots 😀
