### ISSUE TITLE
Create PlanUML diagrams of classes

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#20154]
### Feature Request

To better onboard new developers I suggest we create diagrams of classes and components. 
A diagram for the database structure would also be nice.

**Comment by hregis** [comment]
@dpriskorn for db you have a Mysql Workbench file in /dev/resources/dbmodel/dolibarr_schema.mwb

**Comment by hregis** [comment]
@dpriskorn and you can generate the doc with doxygen  : https://doxygen.dolibarr.org/develop/annotated.html

**Comment by dpriskorn** [comment]
I found https://doxygen.dolibarr.org/develop/inherits.html and that looks pretty good!
