### ISSUE TITLE
Import assistant step 2 and step 3 download "Example_of_import_file_xxx", downloaded file have error 

### ISSUE THREAD

**Issue by adstvstore** [Dolibarr/dolibarr#20158]
### Bug

Import assistant step 2 and step 3 download "Example_of_import_file_xxx", downloaded file have error. The files can be downloaded, but the downloaded files (in Excel format) have error statement inside, this are the error message:

Warning: tempnam(): open_basedir restriction in effect. File(C:\WINDOWS\TEMP) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\modules\import\import_xlsx.modules.php on line 220
Warning: ZipArchive::open(): Empty string as source in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\PhpSpreadsheet\src\PhpSpreadsheet\Writer\Xlsx.php on line 216
Warning: ZipArchive::open(): Empty string as source in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\PhpSpreadsheet\src\PhpSpreadsheet\Writer\Xlsx.php on line 217
Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Writer\Exception: Could not open for writing. in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\PhpSpreadsheet\src\PhpSpreadsheet\Writer\Xlsx.php:218 Stack trace: #0 C:\dolibarr\www\dolibarr\htdocs\core\modules\import\import_xlsx.modules.php(222): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save(false) #1 C:\dolibarr\www\dolibarr\htdocs\imports\class\import.class.php(244): ImportXlsx->write_footer_example(Object(Translate)) #2 C:\dolibarr\www\dolibarr\htdocs\imports\emptyexample.php(113): Import->build_example_file('xlsx', Array, Array, 'produit_1') #3 {main} thrown in C:\dolibarr\www\dolibarr\htdocs\includes\phpoffice\PhpSpreadsheet\src\PhpSpreadsheet\Writer\Xlsx.php on line 218

[Example_of_import_file_produit_1.xlsx](https://github.com/Dolibarr/dolibarr/files/8123208/Example_of_import_file_produit_1.xlsx)

### Environment Version

v15.0.0

### Environment OS

Window

### Environment Web server

Doliwamp15.0

### Environment PHP

PHP7

### Expected and actual behavior

In previous version, v14, v13, v12.... we are able to download example files with Field name that are expected to be fill in with import data. But this v15, thie files still able to be download, but inside the file only have error message.

### Steps to reproduce the behavior

Just go to Tool --> New import --> Step 2 to download the example file.

### Attached files

![DolibarrFileError](https://user-images.githubusercontent.com/100277106/155295620-62deb52a-9537-4d43-a1bd-f074861a50d2.jpg)

**Comment by atm-maxime** [comment]
This issue is related to your environment and installation setup, not a Dolibarr bug. Please seek help on the forums or with a partner.
