### ISSUE TITLE
[BUG] two $$ at the variable user

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#20171]
https://github.com/Dolibarr/dolibarr/blob/2f0040e9c1121a92ec151bedf47b71cb4e36ee4d/htdocs/projet/tasks/document.php#L77

![grafik](https://user-images.githubusercontent.com/78662388/155424204-88830c53-03d1-4a4f-ba17-3f6a84905278.png)

**Comment by edupulpillo** [comment]
This commit is not present in v15.0.0

**Comment by atm-maxime** [comment]
Yes it is, 
https://github.com/Dolibarr/dolibarr/commits/15.0/htdocs/projet/tasks/document.php
but if you use source forge zip, wait for 15.0.1
