### ISSUE TITLE
V15 -  proposal online signature

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#20182]
### Bug

Hi,

One question (could become an issue for some users) and a "bug" reporte. (seems to be a function not called)

On the bottom of validated proposal (/comm/propal/card.php?id=xxx) there is a link that you can send to the customer to sign online:

1- The document (PDF) shown for signature (/public/onlinesign/newonlinesign.php?source=proposal&ref=xxx) is the latest generated : if the user has generated other PDF with other models (with the same or a different name file), this one is presented for signature.
-> Is there a way to select the latest but only for a specific model (the default model for proposal ?)

2 - There's no email sent when the proposal has been signed online (/public/onlinesign/newonlinesign.php?source=proposal&ref=), even if the template of "Customer proposal closed signed" is setup in the notification module. 
It works well when you click on "set accepted/refused -> signed" in the proposal screen (/comm/propal/card.php?id=xxx)

**Comment by rebootit** [comment]
No notification on signed propal confirmed

**Comment by atm-maxime** [comment]
Could you split this into 2 issues ? 1) is a feature request to be able to define which PDF is presented on the online sign portal, 2) seems to be a bug, even if I think it's normal because on this public page, there's no logged user session so maybe it can't send notifications

**Comment by Arre8** [comment]
sure,
i do not know how to split, so i created two new issues :)
https://github.com/Dolibarr/dolibarr/issues/20204
https://github.com/Dolibarr/dolibarr/issues/20205

@atm-maxime can you close this one ?
(and explain to me how to split if it isn't the correct way)

**Comment by atm-maxime** [comment]
That's ok like this 😉
