### ISSUE TITLE
thirdparty in ticket mail notification 

### ISSUE THREAD

**Issue by rem5411** [Dolibarr/dolibarr#20192]
### Bug

hi, 
there are not thirdparty information in the ticket mail notification 
can you add it ? 
thank 

### Environment Version

14.0.5

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.4.27

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB

### Environment URL(s)

https://sav.verticalip.org/ticket/card.php?track_id=jz4mtwb3uvekzzd6&action=view&set=assign_ticket

### Steps to reproduce the behavior

assign a ticket

### Attached files

Vous avez été assigné au ticket #jz4mtwb3uvekzzd6 par Caroline FORN

    Titre : TELEPHONIE
    Type : Question commerciale
    Tag/catégorie : Maintenance
    Sévérité : Normal
    options_asr :
    options_dap :
    options_hco :
    options_fact : 1
    options_fac :

**Comment by atm-maxime** [comment]
Can you please change the issue label to feature request?

**Comment by rem5411** [comment]
this is a new feature ? really ? it s so logical
