### ISSUE TITLE
Let tags of knowledge can see related articles

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#20203]
### Feature Request

In knowledge page , when you go to tags of knowledge module , you can't see the articles area like tags of ticket module or others .
![image](https://user-images.githubusercontent.com/78349579/155758115-c758d592-9828-4dfd-ac52-1dcc8bcb0605.png)

### Environment Version

v15.0.0

### Environment OS

Deian 10

### Environment Web server

 Apache/2.4.38 Apache/2.4.41 

### Environment PHP

7.4.1

### Environment Database

MariaDB 5.5.5-10.4.1

### Environment URL(s)

categories/viewcat.php?id=320&type=knowledgemanagement&backtolist=%2Fdolibarr2%2Fcategories%2Findex.php%3Ftype%3Dknowledgemanagement&backtopage=%2Fdolibarr2%2Fcategories%2Findex.php%3F%26backtolist%3D%252Fdolibarr2%252Fcategories%252Findex.php%253Ftype%253Dknowledgemanagement

### Expected and actual behavior

Should like other tags page as below ( You can see the ticket in the end of page . ):
![image](https://user-images.githubusercontent.com/78349579/155758336-82cd23bf-8217-4056-b557-26d58a73ceb7.png)

### Steps to reproduce the behavior

Go the tags of knowledge  then create a tag .
And get in it to see .

**Comment by atm-maxime** [comment]
Could you add the feature request label instead of bug ? It's a missing feature

**Comment by trekmorris** [comment]
Hi 

I don't know how to change the label , how to do that ?
