### ISSUE TITLE
Bug: GET parameter search_date_start is not working in /accountancy/bookkeeping/listbyaccount.php

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#20219]
# Bug
[*Short description*]

## Environment
- **Version**: 14.0.2
- **OS**: Linux
- **Web server**: nginx/1.20.2
- **PHP**: fpm-fcgi 7.4.28
- **Database**: PostgreSQL 13.5
- **URL(s)**: /accountancy/bookkeeping/listbyaccount.php?search_accountancy_code_start=1460&search_accountancy_code_end=1460&search_date_start=2020-01-01

## Expected and actual behavior
that the date should have effect. Instead the default date (start of current year) is used

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by aspangaro** [comment]
I can't reproduce on v14. 0.5, I think is an old bug. Please upgrade to the last minor version of v14 branch

**Comment by dpriskorn** [comment]
We really need more unittests. Dolibarr is full of odd bugs it seems.

**Comment by aspangaro** [comment]
We have some tests but not to verify this point. Sorry
