### ISSUE TITLE
V15 can't add more than one extrafield in Knowledge Management module

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#20210]
### Bug

When create more than one extrafield will show the error as below :
![image](https://user-images.githubusercontent.com/78349579/155884072-2016709b-abff-4ab2-ab44-15ccccbe7e8f.png)

![image](https://user-images.githubusercontent.com/78349579/155884080-8a52da0f-0d79-41d8-99ab-47b843a5b0d3.png)

![image](https://user-images.githubusercontent.com/78349579/155884209-73e1e047-ab2b-46ab-847b-b826b9a47dc3.png)

### Environment Version

v15.0.0

### Environment OS

Deian 10

### Environment Web server

 Apache/2.4.38 Apache/2.4.41 

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.4.1

### Environment URL(s)

/knowledgemanagement/knowledgerecord_list.php?idmenu=403&mainmenu=ticket&leftmenu=

### Expected and actual behavior

Should not show the error .

### Steps to reproduce the behavior

Create two " Select list " extrafileds or other type extrafield .
And go to list of Knowledge Management .

**Comment by inoveaconseil** [comment]
In 15.0.3, it's work fine.

**Comment by trekmorris** [comment]
Now is only release v15.0.2 , where to find v15.0.3 ?
