### ISSUE TITLE
>> Imp ! D 15.0.0. Link osTicket as Helpdesk software within Dolibarr

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#20211]
### Feature Request

Hi,

Since osTicket ( https://osticket.com/ )  is opensource software, I want to link it within Dolibarr so that non technical users can raise tickets whenever they face issues in using dolibarr that can eventually come to me to attend.

Can you kindly guide to any link / document on how we can achieve this so that any future updates of dolibarr shall not remove this integration.

Thank you in advance,

yesbee

### Use case

Dolibarr customers need a helpdesk for a smooth function of the ERP in terms of using dolibarr, customization requests or any clarifications.

At present, this ticketing is not adequate and osTicket seem to be versatile in that area and more importantly claims to be an opensource.

Due to this reason, would like to integrate it within dolibarr for internal support and use ticketing for external support.

Need help to navigate to the correct documentation / link to setup osTicket within Dolibarr 15.0.0

### Suggested implementation

nil

### Suggested steps

nil

**Comment by atm-maxime** [comment]
Hi! Thanks for contributing.
Dolibarr has its own ticket management system, the "ticket" module. However if you prefer osTicket, you can develop a connector. All you need to know about how to develop within Dolibarr is here : [wiki.dolibarr.org](https://wiki.dolibarr.org)
And the modulebuilder module will help you build your own "osTicket" module to connect the 2 softwares.

But whatever you develop, you will need to review your code every new version of Dolibarr or osTicket to keep the compatibility.

If you need help from Dolibarr expert, check out [partners.dolibarr.org](http://partners.dolibarr.org)

**Comment by riseval** [comment]
Hi

Thanks for the reply.

I need to develop extra tab and add some fields into it. If you undertake such customizations, Can you kindly help and let me know the charges please
