### ISSUE TITLE
Biometrics devices

### ISSUE THREAD

**Issue by Mohaamaad7** [Dolibarr/dolibarr#20218]
### Feature Request

Hello,
I’m looking for a way to link my Dolibarr to Biometrics devices, specifically ZKTeco devices, is there any ready module to do that or a way to develop it ??

**Comment by cfoellmann** [comment]
are these terminals able to communitcate with custom endpoints via REST?

**Comment by hregis** [comment]
@Mohaamaad7 you can try my TwoFactor Authentication here : 
https://myaccount.dolibox.cloud/register.php?plan=PACK-PREMIUM-1M

**Comment by DATUC** [comment]
Hi @ll @hrigs i tink @Mohaamaad7 want to do more withe the biometric device than just openning sessionn he may want allso to he abel to use it on HR module

**Comment by Mohaamaad7** [comment]
@hregis cannot find that !

**Comment by Mohaamaad7** [comment]
@cfoellmann yes

**Comment by Mohaamaad7** [comment]
@DATUC exactly

**Comment by cfoellmann** [comment]
@Mohaamaad7 can you send some links to the documentation describing how to communicate with custom endpoints?
I would be very interested in that and might be able to get work time for this project (connect to dolibarr)

**Comment by cfoellmann** [comment]
We might go now for a zkteco device connected to the biotime 8 software and push and pull data back and forth to dolibarr
