### ISSUE TITLE
Proposal Signature > Send email notification to admin / sales

### ISSUE THREAD

**Issue by BenSavi** [Dolibarr/dolibarr#20221]
### Feature Request

Notification email pour toute signature de proposition commerciale.
Lorsqu'une proposition commerciale est signée en ligne ( avec Dolibarr version 15)
Envoyer un notification par email , comme la notification qu'on reçoit lorsqu'une facture à été réglée en ligne.

### Use case

1. Le client signe et accepte une proposition commerciale en ligne avec la V15
2. Le commercial qui est en charge de la proposition commerciale reçoit une notification par email

### Suggested implementation

sur la fiche de la propostion 
mydolibarr.com/comm/propal/card.php?id=XXX

Ajouter un évènement dans " Événements sur la proposition	"
signature en ligne de proposition

**Comment by atm-maxime** [comment]
Hi ! Thanks for contributing but please use English here 😉 
I guess your issue is the same as #20204

**Comment by BenSavi** [comment]
Hi Maxime, Yes it's the same
