### ISSUE TITLE
v15.0.0/v18.0.2 The "send email" button in a customer payment card is missing.

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#20229]
### Bug

v15.0.0 The "Send email" button in a payment card always appears disabled or is missing.

### Environment Version

15.0.0

### Environment OS

Linux

### Environment Web server

  Apache/2.4.52 (cPanel) OpenSSL/1.1.1m mod_jk/1.2.41 mod_bwlimited/1.4 mod_fcgid/2.3.9 Phusion_Passenger/6.0.7

### Environment PHP

PHP 7.3.33

### Environment Database

MySQL or MariaDB 5.5.5-10.3.31-MariaDB

### Environment URL(s)
www.myserver.com/fourn/paiement/card.php?id=2
www.myserver.com/compta/paiement/card.php?id=33

### Expected and actual behaviour

In supplier payments, the button to send an email always is displayed disabled, and is not possible to be used.
In customer payments, the button to send an email is missing.

### Steps to reproduce the behaviour

1. Open a payment of a vendor invoice.
2. Observe that the button is disabled.

### Attached files
PAYMENT OF A VENDOR INVOICE:
![image](https://user-images.githubusercontent.com/7486607/156083155-2ddd691e-a89d-4b85-a2af-fc648b7e337e.png)
PAYMENT OF A CUSTOMER INVOICE
![image](https://user-images.githubusercontent.com/7486607/156084176-94b843ed-79f9-432a-9aa1-8d2b830696ef.png)

**Comment by hregis** [comment]
@edupulpillo fix with this PR https://github.com/Dolibarr/dolibarr/pull/20232

**Comment by edupulpillo** [comment]
The problem is fixed in v15.0.2 in payment cards of vendor invoices, but is still present in the customers invoice, since is not possible to attach files or send by email the payment of customer invoices.
Kindly enable the same functionality to the customer invoices.

**Comment by gschratzer** [comment]
for me it works the customer invoice with attachments, please can you close this issue for the payment card and then you can open an issue for the customer invoice but with more description and maybe errormessage, syslog etc

**Comment by edupulpillo** [comment]
[gschratzer](https://github.com/gschratzer) as you said in the customer invoice works fine and i am not talking about invoice object. I am talking about payment card object. When a vendor invoice is payed, you have a payment card, selecting that payment card, you can see the details, and then the send email button is missing, as is explained in the previous screenshot in this issue description.
 
The payment card exist in both, vendor and customer invoices, so to fix this issue, is necessary to fix two cases. The title of the issue is well describer "payment card", and the payment card can be for both vendors and customer. So to be able to close this issue both cases should be fixed, and the PR https://github.com/Dolibarr/dolibarr/pull/20232 only fix the half of the problem. 
Anyway i have updated the title following your suggestion trying to make it more clear.

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by edupulpillo** [comment]
Yes, the send email button still is missing in 18.0.2

**Comment by inoveaconseil** [comment]
It's working for me in 18.0.3

**Comment by edupulpillo** [comment]
It's also working for me in 18.0.3
