### ISSUE TITLE
Bug: Adding pre-payment invoice to supplier's invoice does not reduce the amount

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#20226]
I've made a number of pre-payments to a supplier and created accordingly "factures d'accompte". I've now recived one invoice and then I chosed one of the availble prepayments, of 339.20€ to pay pay it.

![1](https://user-images.githubusercontent.com/24247236/156037759-03e8ada6-17a3-43e1-b036-584d86cb6a71.jpg)

As a result is it is written on the right side of the page as per below

![2](https://user-images.githubusercontent.com/24247236/156038174-aecbda46-c963-4bd6-ade9-500d62587d00.jpg)

Acompte FDA200100     **339.20**
Facturé                           **339.20**
Reste à payer                  **339.20**

In other words, the debt is not reduced, but available prepayment amount has been reduced width 339.20 and the invoice remain unpaid. In other words, the money has gone up in thin air.

The correct behaviour would have been that Rest à payer should have been at 0 and the invoice should have had the status Payé (Paid).

Acompte FDA200100     **339.20**
Facturé                           **339.20**
Reste à payer                  **0**

## Environment
- **Version**: 15.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.33-1+0~20211119.91+debian10~1.gbp618351
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0+deb10u1
- **URL(s)**: /azert/fourn/facture/card.php?facid=519

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by hregis** [comment]
@hasse-basse do you have externals modules?

**Comment by hasse-basse** [comment]
CONCAT PDF 6.0.2
JALONS 9.0+2.3.0 (seem to be your module!) I can see it is too old! Does version 14 work with Dolibarr 15?
Ultimat PDF an old version. I don't use it so I will take it away

I've tried to turn all of them off, but it didn' help!

**Comment by hasse-basse** [comment]
I just tried it on another invoice and it worked as designed  si I don't know what is going on. Maybe it still was about one of the modules as suggested.

I close the issue.

**Comment by hasse-basse** [comment]
The problem is back and I can't figure out why it work sometimes and other times not. This is highly annoying and I hope someone can figure out a solution. I will keep playing around and see if I will find a pattern, but I hope for your help.

**Comment by josett225** [comment]
Hi there 
This is maybe the same issue

https://github.com/Dolibarr/dolibarr/issues/19724
