### ISSUE TITLE
Dolibarr 15.0.0. Additional CSS like WordPress

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#20239]
### Feature Request

Hi,

Kindly refer to the attachment.

Many times, we need to modify the style css file if we need to get minor change of UI.  It would be great if we have an area like "Additional CSS" wherein we can add all of our CSS, Javascript and jQuery code so that they wont get affected during upgradations.

Such features are available in most of the PHP systems including WordPress.  Can you please help to create similar one for dolibarr as well.
![additional-css](https://user-images.githubusercontent.com/85006729/156181623-8a22bbd3-1409-4458-8740-52e92b6cc485.jpg)

### Use case

Minor customizations of UI of Dolibarr using additional CSS  / Javascript / jQuery.

Kindly refer to the attachment.

Many times, we need to modify the style css file if we need to get minor change of UI.  It would be great if we have an area like "Additional CSS" wherein we can add all of our CSS, Javascript and jQuery code so that they wont get affected during upgradations.

Such features are available in most of the PHP systems including WordPress.  Can you please help to create similar one for dolibarr as well.

### Suggested implementation

Please add an extra link in Setup

**Comment by rycks** [comment]
hello @riseval ,
something like that ?

![image](https://user-images.githubusercontent.com/1468823/219511749-62f954af-ce12-47ae-b887-ee672f4013aa.png)
