### ISSUE TITLE
E-Mails setup parameters for Google workspace (Gsuite) not working

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#20236]
### Bug

Hi @ll i have tried so many time the this [stetup](https://wiki.dolibarr.org/index.php/Setup_EMails#Gmail_.28with_mode_relay_of_Gmail_with_GSuite.29] to have this working) but not, have event teste **GMass** to confirm i my configuration was ok and it is but **Dolibarr** is not working any help please

### Environment Version

Dolibar 14.0.5 and 15

### Environment OS

Linux shared hosting

### Environment Web server

LAMP

### Environment PHP

7.4

### Environment Database

5.6

### Expected and actual behavior

Serveur non disponible à l'adresse smtp-relay.gmail.com sur le port 465 - Error 111 - Connection refused

**Comment by atm-maxime** [comment]
Hi. Thanks for your feedback. Please use forums to seek tech support. Your specific setup is not a bug within Dolibarr core code.

**Comment by DATUC** [comment]
> Hi. Thanks for your feedback. Please use forums to seek tech support. Your specific setup is not a bug within Dolibarr core code.

Hi @atm-maxime have done that in the french forum [[Problème configuration email avec Google Gsuite](https://www.dolibarr.fr/forum/t/probleme-configuration-email-avec-google-gsuite/39306?u=tadit)
but the provided solution did not work also
