### ISSUE TITLE
v15.0.0 The link to pay is missing in customer invoices in PDF

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#20230]
### Bug

v15.0.0 The link to pay is missing in customer invoices in PDF

### Environment Version

15.0.0

### Environment OS

Linux

### Environment Web server

Apache/2.4.52 (cPanel) OpenSSL/1.1.1m mod_jk/1.2.41 mod_bwlimited/1.4 mod_fcgid/2.3.9 Phusion_Passenger/6.0.7

### Environment PHP

PHP 7.3.33

### Environment Database

MySQL or MariaDB 5.5.5-10.3.31-MariaDB

### Environment URL(s)

https://www.myserver.com/document.php?modulepart=facture&file=FA1909-0050%2FFA1909-0050.pdf&entity=1

### Expected and actual behavior

The customer invoice generated in PDF do not include the link to proceed with the payment. 

### Steps to reproduce the behavior

1. Open an invoice and be sure you select a payment terms with Bank data filled.
2. Validate the invoice
3. Generate the pdf file
4. Open the PDF and observe is not included the link for the payment

### Attached files

![image](https://user-images.githubusercontent.com/7486607/156087090-f3665b2f-b0a0-4426-9acd-8631f1ee717b.png)

**Comment by atm-maxime** [comment]
So this means the link was available and working in the PDF in v14 ? If not and it's simply that the link has never been in the PDF, it's a feature request.

**Comment by edupulpillo** [comment]
Hi.
In the changelog of v15.0.0 is included as a new feature, but the feature do not appears. For this reason i talk about bug in this issue, instead feature request.
Maybe is a commit that was forget to merge?

**Comment by priojk** [comment]
@edupulpillo 

Some questions regarding your setup:

- Did you activate and configure an online payment service (Paypal, Stripe, ...)?
- Did you enable the creation of the link in home/settings/PDF?
.


![image](https://user-images.githubusercontent.com/10772984/192107862-7102c516-0f0b-4480-bf43-78eda83c98fb.png)

For me this works in 15.0.3 and looks as follows with Stripe configured as the service:

![image](https://user-images.githubusercontent.com/10772984/192107936-0b2c1bf6-e1bd-4be2-b81f-063abb66d1a4.png)


If the settings are all ok, you could test to update 15.0.0 to the latest minor release of v15.

**Comment by rycks** [comment]
ok, that's not a bug but a configuration problem. Thanks @priojk you provide the solution.

**Comment by edupulpillo** [comment]
Thank you everybody for your help double checking it
