### ISSUE TITLE
Introduce CheckInvoiceDate feature as a core functionnality

### ISSUE THREAD

**Issue by thomas-Ngr** [Dolibarr/dolibarr#20234]
### Feature Request

[CheckInvoiceDate](https://www.dolistore.com/en/modules/1334-Invoice-dates-check.html) module allows to check an invoice date when validating a draft invoice. This is useful for some companies. However, this module seems not to be maintained.

I suggest to add this functionality in the core, available as an option of Facture module.

### Use case

The user wants to be sure that validated invoices of same type follow one another, by ref number and by date.

### Suggested implementation

Considering new option  INVOICE_CHECK_POSTERIOR_DATE  is activated :

- when validating a draft invoice, we verify that the current invoice date is posterior to the last invoice **with the same invoice type**. If not, an error should be displayed and block the invoice validation.

- when validating an invoice **that is being modified** (name is not PROV* but FA*), the validation should pass even if the current invoice date is anterior to the last invoice found for same invoice type.

- by "posterior date", we mean "the **day** is posterior or equal". We won't check for **hour** posteriority.

- this check is made on single invoice validation (compta/facture/card.php) and mass validation (compta/facture/list.php)

- ~~when mass validating invoices, an error on this check on a single invoice should not prevent other invoices to be validated (should not block the whole validation lot). A warning should be displayed with the appropriate invoice reference (PROV*)~~ (this would need to change the whole mass validation process)

- when mass validating invoices, a sorting should be made by invoice date before validating invoices. This prevents conflicts due to wrong invoice order.

### Suggested steps

- introduce option INVOICE_CHECK_POSTERIOR_DATE in Facture module and Facture admin panel (part "Invoices and credit notes numbering model")

- create a method willBeLastOfSameType() for Facture object

- add the check on facture/card.php
- add the check on facture/list.php

**Comment by atm-maxime** [comment]
Hi. Thanks for contributing.
Did you try to contact the module editor to ask him about his module ?

**Comment by thomas-Ngr** [comment]
Hi !

No. I just sent them an email.

However, the PR https://github.com/Dolibarr/dolibarr/pull/20247 I made inbetween (draft for now) adds this check on mass validation, which seems not to be part of the original module functionnality. So  I would rather merge this PR.

Moreover, I did not use the original module code.

**Comment by thomas-Ngr** [comment]
Since I did not have any answer after one week, and considering:
- the PR does not use any code from checkInvoicedate external module
- the PR adds functionnality (invoice date check on mass validation)

I think this proposition can be merged.
