### ISSUE TITLE
v15.0.0 Budget field in a task should be multicurrency

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#20231]
### Bug
v15.0.0 Budget field in a task should be multicurrency

![image](https://user-images.githubusercontent.com/7486607/156088138-b1331fa1-ad3d-46fb-8bfe-38cd83161b95.png)

**Comment by atm-maxime** [comment]
Hi. Can you explain why ? Give an example?
Fir me this budget field must be in my company currency because I compare it with the cost of time spent on the task. Also if you need it multicurrency, don't you think it's a feature request?

**Comment by edupulpillo** [comment]
Well the multicurrency modul is activaed, and should propagate the use of multiple currencies everywhere under my point of view. At the moment the expenses report and this new "budget field" do not have it. Every new module, should be compatible with multicurrency , i think.

**Comment by atm-maxime** [comment]
Under my point of view, developing a new feature that is useless or not needed by a great number of users is not a good thing.
Multicurrency is needed by many companies for selling or purchasing. However, a few companies need to deal with expense reports in multiple currencies.

Furthermore if you have a task budget defined and you want also a field to have the budget in another currency, when do you convert the value ? With what rate, based on what date ?

**Comment by edupulpillo** [comment]
In the same way that now is in the invoice: storing the currency exchange rate with the base currency. Then the user can choice the date and the exchange rate as be desired.
In my opinion if Dolibarr is multicurrency, all the ammounts of any payment, salary, invoicing, proposal, accountancy or whatever should maintain the multicurrency. feature. If we do not do it we can not say that Dolibarr really is multicurrency, and will be a "partially" multicurrency solution.
As you mentioned multiple companies for selling or purchasing have business trips, that have multicurrency rececips. Also the projects can succeed in multiple countries, and the receipts, budgets and prices are expressed in the currency where the tasks occurs.

**Comment by edupulpillo** [comment]
Can be schedulled this feature for any Dolibar v17.x version?

**Comment by edupulpillo** [comment]
still is a needed feature. The international expenses are expressed in different currencies
