### ISSUE TITLE
Ticket: linked files should be linked to messages, not ticket

### ISSUE THREAD

**Issue by thomas-Ngr** [Dolibarr/dolibarr#20259]
### Feature Request

On Ticket module, files are directly linked to the ticket and accessible in the "linked files" tab.
Having all linked files on a single tab is a great feature, and this should be kept.

However, I think that the files should be linked to the ticket messages. On the message view, we may want to **see a linked file directly from the message** (typically a screenshot) , to have more understanding context.

This would also **ease the display of linked files** in the public interface. This last feature is often required by users of ticket public interface.

----

There may be good reasons to have done things that way at the beginning, but I don't see them for now.

### Suggested implementation

- when adding a message with a linked file (public interface or backend), the file should be linked to the `actioncomm` element, not to the ticket.

- A side benefit of this is that files will also be displayed in the message view (this is a screenshot from an actual message with a linked file):

![PJ_ticket](https://user-images.githubusercontent.com/89838020/156590766-0cf82aa4-e06e-402e-922c-56c87658493e.png)

- on ticket/document.php card, the files from linked messages should be displayed aside files directly linked to ticket.

- On the public interface, ticket linked files should be made available aside messages.

**Comment by edupulpillo** [comment]
what is the commit that solve this?
