### ISSUE TITLE
Change color for List of order status

### ISSUE THREAD

**Issue by AnggaRifandi** [Dolibarr/dolibarr#20260]
### Feature Request

Currently I am using Dolibarr 15.0.0.

In list of order there are color status for:
- In process
- Delivered
- Validated
- Canceled

I am aware that color status related with class 'badge' and 'badge-status'.

Is it possible to add feature to make easily to change the color status?

### Use case

Currently In process and Delivered use the same color. It will be better if those two process using different color.

### Suggested implementation

Add color change feature in Settings.

**Comment by thegeettanna** [comment]
Dear @AnggaRifandi, 

We achieved this using a simple if loop in the \commande\list.php file. 
Right below the // show shippable & not shippable loop, we added the below code. It is based on a combination of conditions which include checking a "fk_statut" & "internalorderstatus" (this is a field we use to further divide live orders). 

Adding screenshots, Although this only adds color to one column, it is very easily doable for the whole row. This I believe keeps things tidy and neat. Sorry about the cropped screenshots as the data is from our production site. 
![Screen Shot 2022-03-04 at 1 06 44 PM](https://user-images.githubusercontent.com/24646523/156722173-f7bbba65-7bb7-4f65-8261-cf975193f01f.jpg)

![Screen Shot 2022-03-04 at 12 47 14 PM](https://user-images.githubusercontent.com/24646523/156722159-67c7084a-fb4b-434c-92d2-424f23f8e1d7.jpg)


I have also attached a screenshot of the card page (\commande\card.php) where we see these stages on the inside as well. 
![image](https://user-images.githubusercontent.com/24646523/156721994-b3bbf834-4e94-4fc2-8b76-fe6b52b8cea0.jpeg)



Code for Copy Paste: (But you will have to most of it anyway based on your requirements). 

            if (!empty($arrayfields['c.ref']['checked'])) {
                //KTI internal Order Status---Background Color-Start

                //Order Cancel
                if($obj->fk_statut == -1){
                    print '<td class="nowraponall" style = "background-color: #FFFFFF">';
                }
                elseif($obj->options_internalorderstatus == 1) // New Order
                {
                    //New Order -- Light Orange Color
                    print '<td class="nowraponall" style = "background-color: #ffb738">';
                }
                elseif ($obj->options_internalorderstatus == 10) //Waiting for advanced
                {
                    //Waiting for Advance -- Light Yellow Color
                    print '<td class="nowraponall" style = "background-color: #fffa15">';
                }
                elseif ($obj->options_internalorderstatus == 20 && $notshippable != 0)//accounts approval
                {
                    //Accounts Approval and to purchase -- Light Blue Color
                    print '<td class="nowraponall" style = "background-color: #2dd2e6">';
                }
                elseif ($obj->options_internalorderstatus == 20 && $notshippable == 0 || $obj->options_internalorderstatus == 30)
                {
                    //Accounts Approval and to store or purchase approval -- Light Blue Color
                    print '<td class="nowraponall" style = "background-color: #bee6c8">';
                }
                elseif ($obj->options_internalorderstatus == 40)
                {
                    if ($obj->fk_statut == 3 && $obj->billed == 1)
                    {
                        print '<td class="nowraponall" style = "background-color: #FFFFFF">';
                    }
                    else {
                        //To Store Approval -- Royal Blue Color
                        print '<td class="nowraponall" style = "background-color: #23e103">';
                    }
                }
                else {
                    print '<td class="nowraponall">';
                }
                //KTI internal Order Status---Background Color-End

**Comment by AnggaRifandi** [comment]
Thank you @geetthegreat, I will try it.

**Comment by AnggaRifandi** [comment]
Hi @geetthegreat,

I have tried to implement your code in line 1467 but still not get any color in Ref. column.

![image](https://user-images.githubusercontent.com/7530088/156984690-ed89273a-d848-421b-bdc9-44aa584b00d6.png)

Could you explain more about *options_internalorderstatus*? Should I make it first? Because I can not found that name in Dolibarr 15.0.0 files.

**Comment by AnggaRifandi** [comment]
Finally I try to change the color manually in `theme/eldy/theme_vars.inc.php` and modify `commande/class/commande.class.php` to make different color status for In process and Delivered.

**Comment by thegeettanna** [comment]
Dear @AnggaRifandi, 

My code was based on an extra field created for our instance called 'Internal Order Status'. 

If you use the 'fk_statut' instead of the 'options_internalorderstatus', then it will work as expected. 
You can try something like this:

if (!empty($arrayfields['c.ref']['checked'])) {
          
            //Order Cancel
            if($obj->fk_statut == -1){
                print '<td class="nowraponall" style = "background-color: #FFFFFF">';
            }
            elseif($obj->fk_statut == 0) // Draft Order
            {
            print '<td class="nowraponall" style = "background-color: #ffb738">';
            }

elseif($obj->fk_statut == 1) // Validated Order
            {
            print '<td class="nowraponall" style = "background-color: #bee6c8">';
            }

elseif($obj->fk_statut == 2) // In Progress Order
            {
            print '<td class="nowraponall" style = "background-color: #23e103">';
            }
elseif($obj->fk_statut == 3) // Delivered Order
            {
            print '<td class="nowraponall" style = "background-color: #fffa15">';
            }

//Change colors as per requirement.

**Comment by AnggaRifandi** [comment]
Thank you for your explanation @geetthegreat.

Will try it.
