### ISSUE TITLE
Bulk change for accounting code don't work with PostgreySQL database

### ISSUE THREAD

**Issue by soundheritage** [Dolibarr/dolibarr#20279]
### Bug

You can't change by "bulk methode" (multiple lines, in same times), the accounting code, on a environnement  dolibarr V12 V13 V14 V15 installed on PostgreySQL Database. There is this error message for eatch lines : 
"ERROR: 42703: column 'l' of relation 'llx_facture_fourn_det' does not exist LINE 1: UPDATE llx_facture_fourn_det as l SET l.fk_code_ventilation=... ^ LOCATION: transformUpdateTargetList, analyze.c:2333
ERROR: 42703: column 'l' of relation 'llx_facture_fourn_det' does not exist LINE 1: UPDATE llx_facture_fourn_det as l SET l.fk_code_ventilation=... ^ LOCATION: transformUpdateTargetList, analyze.c:2333"

### Environment Version

Tested on Dolibarr V12 V13 V14 V15

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

PHP 7.4

### Environment Database

PostgreSQL 12

### Environment URL(s)

accountancy/supplier/lines.php
accountancy/customer/lines.php

### Expected and actual behavior

We expect can be use the bulk changes with PostgreySQL database that working fine on a MySql database

### Steps to reproduce the behavior

Check multiples lines, to change in bulk mode the accountancy code. Then, you try to apply the changes, by click to the button "changing link". and you have an error code, like the screenshot. The changing wasn't apply.

But if you change line by line,  using the "modifying pen" on the right of the line, you can change the accountancy code.

### Attached files

![masse_changing_code](https://user-images.githubusercontent.com/83544637/156843333-644e453b-3570-4567-8b20-7b552662b9a9.JPG)
![Code_comptable_change_error](https://user-images.githubusercontent.com/83544637/156843341-923519eb-feac-4d21-8f80-f87611464dba.JPG)

**Comment by soundheritage** [comment]
The database structure, for the llx_facture_fourn_det table :

![database structure](https://user-images.githubusercontent.com/83544637/156880723-676340f4-0446-4b7b-9db8-7ad33e9b6791.JPG)

Do you think there will be a fast workaround for this issue ?

**Comment by aspangaro** [comment]
I proposed an easy fix #20297, possibility to apply to verify if it's work ?
