### ISSUE TITLE
editing Bankentries borken since 14.0.5

### ISSUE THREAD

**Issue by funsurfer2008** [Dolibarr/dolibarr#20273]
### Bug

If i want to edit details of a bankentry and click update (if i changed a thing or not) the account is deleted.
This Bug is there since 14.0.5 and persists in 15.0.0.

in version 14.0.4 everything is working fine.

brgds

### Environment Version

14.0.5 15.0.0

### Environment OS

Linux web01.a-square.at 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64

### Environment Web server

Apache/2.4.52

### Environment PHP

7.4.28

### Environment Database

MariaDB 5.5.5-10.5.15-MariaDB-1:10.5.15+maria~buster

**Comment by aspangaro** [comment]
Sorry, I can't reproduce. I realize an update of a bank entry on dolibarr 14.0.5, any problem founds. 

Please, can you explain with picture your problem ?

**Comment by funsurfer2008** [comment]
![image](https://user-images.githubusercontent.com/59434775/157880072-3c30e615-5bdf-499b-b87d-0d5f281c342d.png)
![image](https://user-images.githubusercontent.com/59434775/157880228-1064f169-e13f-4a8e-9d67-dfa8af3de4f5.png)
![image](https://user-images.githubusercontent.com/59434775/157880422-2d97f842-f015-4bc5-871f-8fea8b6e01eb.png)
![image](https://user-images.githubusercontent.com/59434775/157880557-0bc2c2b6-e05c-414a-aba1-b7eaeea11ef3.png)

**Comment by funsurfer2008** [comment]
you can test it here: https://demo.dolibarr.biz/index.php
