### ISSUE TITLE
Have a warehouse per project.

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#20277]
### Feature Request

In this way we could send to this warehouse all the products that we will use in the execution of this project.
Something similar to what has been done for third parties or contacts.

### Use case

For example, if we carry out electrical installations in a location outside our facilities, we could define a warehouse on site and control the products that enter and leave it, in the same installation. 

### Suggested implementation

A new field in the projects tab that allows you to select one of the warehouses that have already been created and to be able to access it after having selected it.

**Comment by atm-maxime** [comment]
Structurally, I would do the other way around : on the warehouse card, define the associated project (just as it already exists on several objects). I guess you won't have several projects for the same warehouse but several warehouse for the same project perhaps.

And on the overview tab of a project, show the related warehouses and their value. And when doing a stock movement on a warehouse, auto select the project on the movement.

**Comment by JoAnMaFe** [comment]
Hello again.
I have been doing some tests with Warehouses and Projects.
It is true that if we do it as atm-maxime says in the warehouse tab we define the associated project, it is a relationship of several to one (so we can have multiple warehouses for the same project, but without visibility from the project), if we do the opposite One warehouse per project, the relationship is one to one, but from the project you can access the associated warehouse, in the case of needing several warehouses for a project, you can define a parent warehouse to which you can add child warehouses.
With this arrangement you can add a single field in projects that allows you to access that warehouse and then return to the project.

**Comment by atm-maxime** [comment]
Mmh... If you do as you say, it's not a one to one relationship as you can use the same warehouse on several projects. And how do you go back on the project once you're on the warehouse?
Of course with what I said, I would add the display of related warehouses in the "related objects" tab of the project, so you can navigate between the 2. And it seems to me interesting to use the financial value of the warehouse as a project indicator. If you define x products in stock in the warehouse, the linked project could consider the products value to be a "budget" to consume during the project.

**Comment by hregis** [comment]
@atm-maxime @JoAnMaFe 
at the moment I only see the option to associate a warehouse with a project... but the warehouse will be linked to this single project! but it's possible to linked project with multiple warehouse !
It lacks the flexibility to make... a warehouse with several projects and a project with several warehouses! 
this is the question ?
