### ISSUE TITLE
Urgent > How to add Sub Heading when we add extra fields in Members

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#20288]
### Bug

How to add Sub heading when we add extra fields in Members

Like :

Know your members
Field 1:
Field 2:

Special Members
Field1:
Field2:

extra.

Request to kindly help

### Environment Version

14.0.5 & 15.0.0

### Environment OS

Ubuntu 20

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

/adherents/card.php?leftmenu=members&action=create

### Expected and actual behavior

I am trying to add extra fields in New member list.  In view of many fields, I need to group them logically for easy readability and data entry.  However, I am not aware of how to create a grouping or Sub heading so that it will become easily readable.

### Steps to reproduce the behavior

Home>Members>New Member

### Attached files

Self explanatory in above

**Comment by atm-maxime** [comment]
If I understand correctly, you seek help on Dolibarr. This is what forums are made for, or maybe Dolibarr partners. Here on GitHub we deal with issues to fix bugs or add new features.
However, did you try to create an extrafield with the "separator" type ?

**Comment by riseval** [comment]
Hi Thanks a lot.  I have already completed with extrafield and separator.  While I am exploring on CSS modification of separator to look like dolibarr section heading, my main issue is:

- How to create fields to upload files using extra fields.

grateful for any help.

**Comment by atm-maxime** [comment]
As I stated before, please use forums to seek for help. Your specific needs is not an issue for Dolibarr core code, and certainly not a bug.

**Comment by riseval** [comment]
CSS is modified in global.inc.php in theme folder such that the sub headings span 2 columns (Default is 1 column ! ) and background color similar to that of sub heading color variable added reflects in file : /public/members/new.php

The bug is sub headings are not spanning in two columns and doesnot contain any extra spaces or colors in order to differentiate them from other fields.
