### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by mmpattnaik** [Dolibarr/dolibarr#20283]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 15.0.0
- **OS**: SunOS
- **Web server**: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/5.6.15
- **PHP**: apache2handler 5.6.15
- **Database**:  5.6.42
- **URL(s)**: /dolibarr-develop/htdocs/ftp/index.php?action=refreshmanual&numero_ftp=1&section=%2F

## Expected and actual behavior
In Root all files and directories under root not showing. Only part  is showing. 

## Steps to reproduce the behavior
When clicking FTP configured Clicked

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by freechelmi** [comment]
Please update the title of your issue
