### ISSUE TITLE
Looking for dolibarr customization developer

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#20285]
### Feature Request

Dolibarr customization developer to add two tabs and few fields per each tab in card.

Kindly send your price or reply with your contact details for more info.

thanks
yesbee

### Use case

need to add more tabs and fields for dolibarr card

**Comment by ayoub-el97** [comment]
can we chat on WhatsApp ! i think i can help you for

**Comment by hregis** [comment]
Sorry this is not an issue !
you can see the official partner list here : https://wiki.dolibarr.org/index.php?title=List_of_Dolibarr_partners_and_providers

**Comment by riseval** [comment]
> can we chat on WhatsApp ! i think i can help you for

**Comment by riseval** [comment]
Sure. Please let me know your whatsapp number or your mail id so that I can reach out to you.  Alternatively, you can connect to me online at https://www.riseval.com

thanks a ton.
