### ISSUE TITLE
Tiny Text Editor Broken in Upgrade from 14.0.5 to 15.0.0

### ISSUE THREAD

**Issue by jccs1953** [Dolibarr/dolibarr#20289]
### Bug

Tiny Text editor ceased to function in new version when adding customer notes 

### Environment Version

15.0.0

### Environment OS

Linux - kernal 2.6.32-673.26.1.lve1.4.20.el6.x86_64

### Environment Web server

Apache Version	2.4.52

### Environment PHP

PHP Version	7.4

### Environment Database

MySQL Version	5.7.37-cll-lve

### Environment URL(s)

https://jccs.us/crm

### Expected and actual behavior

The expected behavior was that the Tiny Text Editor would continue to function as it did in 14.0.5
![image](https://user-images.githubusercontent.com/17952470/156934914-f3838006-ea8b-4f05-8eac-311fdbccaa37.png)
The actual behavior was that it no longer does the tiny text editor no longer exists when editing notes in a customer file  
![image](https://user-images.githubusercontent.com/17952470/156934936-064d8e02-620f-4f00-aa1f-124ef9d1d546.png)

### Steps to reproduce the behavior

1. go into a customer file 
2. select notes / private notes
3. the field no longer allows Tiny text editor as being active - no editor present

### Attached files

![image](https://user-images.githubusercontent.com/17952470/156934950-0244a369-dbda-4ba0-b696-6eb7ae1255e7.png)
![image](https://user-images.githubusercontent.com/17952470/156934959-3edd3aab-bb69-4080-8c6b-f6c2d844e130.png)

**Comment by atm-maxime** [comment]
Did you check that the wysiwyg module is still active in your 15 version ?

**Comment by jccs1953** [comment]
> Did you check that the wysiwyg module is still active in your 15 version ?

OK strange that it deactivated the notes wysiwyg when it worked previously I went back in and found that was the case thanks for the fix
