### ISSUE TITLE
BUG - product tax rate ignored in new supplier invoice

### ISSUE THREAD

**Issue by TomNok** [Dolibarr/dolibarr#20287]
### Bug

When adding products to a supplier invoice, the tax rate is set to whatever default tax rate was filled in the grid. 
Instead I would expect that the tax rate from the product's buying price would be applied. 

### Environment Version

15.0.0

### Environment OS

Linux

### Environment Web server

Apache/2

### Environment PHP

7.4.27

### Environment Database

10.3.29-MariaDB-cll-lve

### Steps to reproduce the behavior

Add a product with a tax rate different from the pre-selected tax rate on the screen.

### Attached files

Product tax rate is 6%
![image](https://user-images.githubusercontent.com/90422744/156923299-297ce3f8-cac8-4d2d-bf0a-8af46f403336.png)

But when added to supplier invoice it's 21% :
![image](https://user-images.githubusercontent.com/90422744/156923343-7770fea1-3b6f-4fd0-9995-e0ca888aaeb4.png)

**Comment by TomNok** [comment]
Seems this is not assigned yet.. Am I the only one having this issue ? It is really disturbing for me,  as it is a very basic function..

**Comment by Yakouaho** [comment]
No i'm having the same issue here on 15.01 version
In the early version it do not happened
