### ISSUE TITLE
Inconsistency with propal date and validity date when STATUS_VALIDATED

### ISSUE THREAD

**Issue by bomuux** [Dolibarr/dolibarr#20304]
### Bug

Problem concerns this two propal dates :

- date (function Propal::set_date)
- validity date (function Propal::set_echeance)

When propal status is STATUS_VALIDATED, this two dates seems to be editable (on propal card) but can't be changed because of queries in corresponding functions : queries require status to be STATUS_DRAFT.

**Suggestion** : Update should be possible OR edition (pencil) should be removed.

### Environment Version

15

**Comment by tiaris** [comment]
PR added https://github.com/Dolibarr/dolibarr/pull/22618
