### ISSUE TITLE
Super Administrator profile picture BUG

### ISSUE THREAD

**Issue by KanzuTachiba** [Dolibarr/dolibarr#20317]
### Bug

Changing the profile picture from Super Administrator removes the Super Administrator from the user list and card.php from Super Administrator is locked.

### Environment Version

14.0.2

### Environment OS

Debian 10

### Environment Web server

Apache/2.4.38 (Debian)

### Environment PHP

 7.3.29-1~deb10u1

### Environment Database

mysql 8.0.26

### Environment URL(s)

/user/list.php?leftmenu=users , /user/card.php?id=1

### Expected and actual behavior

Expected: Super Administrator gets a profile picture
Actual: Super Administrator went missing from the user list

### Steps to reproduce the behavior

I changed the profile picture from the super administrator in Home ->Users & Groups -> List of Users -> Super Administrator profile (card.php) -> Change -> Picture to a 512x512 png file. The picture finished to upload to the card.php as the new Super Administrator profile picture.
Then I clicked on Save, but the Super Administrator went missing from the User-List.
And when I click on the Super Administrator's name on the left side in the upper corner, it opens the card.php but with a massage "Access denied.
You try to access to a page, area or feature of a disabled module or without being in an authenticated session or that is not allowed to your user."

### Attached files

![image](https://user-images.githubusercontent.com/100464313/157556319-ff7409a2-1a79-4765-9e9e-4e43192f7ea0.png)

![image](https://user-images.githubusercontent.com/100464313/157556376-6724530a-e0b7-4a07-a130-cfe8dffb22a9.png)

**Comment by ksar-ksar** [comment]
Hello,

First thing to do is to upgrade to V14.0.5

**Comment by KanzuTachiba** [comment]
> 

Thank you! Upgrade to V14.0.5 solved the problem!
