### ISSUE TITLE
ErrorBadCharIntoLoginName with login containing @

### ISSUE THREAD

**Issue by pyr74** [Dolibarr/dolibarr#20322]
### Bug

Since version 14 it is impossible to create or update users whose login contains **"@"**. We we try to create or update users we have the error : ErrorBadCharIntoLoginName.
For years our logins have been the email addresses of users. So it's quite problematic.

We have temporary solve this problem by modifying le file **/htdocs/user/class/user.class.php :**

**Line 1292 :**
Change : _**} elseif (preg_match(’/[,@<>"’]/’, $this->login)) {**_
By : **_} elseif (preg_match(’/[,<>"’]/’, $this->login)) {_**

**Same change line 1689**

I don't know if it is a BUG or a voluntary change.
Can you tell us more about this subject ?

### Environment Version

14.0.3

### Environment OS

Linux UBUNTU

### Environment Web server

Apache 2.4.29

### Environment PHP

7.2.24

### Environment Database

MySQL 5.7.37

**Comment by aspangaro** [comment]
Hello, it's not a bug, it's a secure choice. But I made a patch to define with a constant a list of unautorized caracters

See #19737

Code is for v16 and works in v14
