### ISSUE TITLE
bank/sepa transfer. Classified as send doesn't do anything

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#20327]
### Bug

When you create a sepa xml payment and mark it as send doesn't do anything (reload the page)

### Environment Version

15.0.0

**Comment by Iledher** [comment]
I have the same problem with V15.0.3.
I have a other Dolibarr installation ( V14.0.4), and I could validate the transmission method and date when I click on "Set on status 'File Sent'"
![set to status file sent](https://user-images.githubusercontent.com/24903496/182657464-2598b198-6179-471a-8cc4-23443bd24cca.png)

**Comment by Iledher** [comment]
I just tried something : I activate the "Payments by Direct Debit" module, and this fix the problem with  "Payment by credit transfer" module. I think it's a permission problem...
