### ISSUE TITLE
Display error in VAT and without VAT column ( tva et ht )

### ISSUE THREAD

**Issue by laurent-pixel** [Dolibarr/dolibarr#20329]
### Bug

In the list of invoiced quotes
if the columns "invoiced amount" including tax and/or excluding tax are displayed
the values displayed in the "invoiced" columns are reversed
The amount including tax is the tax-free amount and vice versa. 

Dans la liste des devis facturés
si on affiche les colonnes "montant facturé" TTC et/ou HT
les valeurs affichées dans les colonnes "facturé" sont inversées 
Le montant TTC est le Hors-Taxe et Vice-versa.
 

### Environment Version

Dolibarr 11.0.4

### Environment OS

Linux

### Environment Web server

apache 

### Environment PHP

PHP 5.6.38 

### Environment Database

 5.5.57-MariaDB

### Environment URL(s)

All

### Expected and actual behavior

The HT column must display the amount invoiced excluding tax
The VAT column must display the amount including tax

La colonnes HT doit afficher le montant facturé HT
La colonne TTC doit afficher le montant TTC

### Steps to reproduce the behavior

go to quote
go to the invoiced quote subcategory
in the menus to customize the display of the columns (3 small dots on the right):
display the HT column
display the tax-inclusive column
The amounts displayed are reversed 

allez dans devis
allez dans la sous catégorie devis facturé
dans le menus pour customiser l'affichage des colonnes ( 3 petits points à droite ) :
affichez la colonne HT 
affichez la colonne TTC
Les montants affichés sont inversés 

### Attached files

![Capture d’écran_2022-03-11_16-42-38](https://user-images.githubusercontent.com/101413627/157907872-45b1bb5e-ec12-46e3-9003-cfe79007e343.jpg)

**Comment by emheyarssi** [comment]
Hi, this bug doesn't exist anymore since version 12. Upgrade your version of Dolibarr.
