### ISSUE TITLE
EXPORT/IMPORT TOOL FAILURE

### ISSUE THREAD

**Issue by aapostolos** [Dolibarr/dolibarr#20328]
### Bug

When I want to export a file from the export tool, as soon as I get to step 5 I do not see the export tool at all, the box with the file I want to export, as well as the export button. the same goes for the input tool. there is no file selection box and the import button.
PS. By migrations from 11 to 12, I had a fault error in phpMyAdmin in database from Dolibarr. I do not know if it has anything to do with this issue.

### Environment Version

14, 15

### Environment OS

Linux 4.4.180 (SYNOLOGY NAS 918+)

### Environment Web server

Apache/2.4.51 (Unix)

### Environment PHP

7.4.24

### Environment Database

Mariadb10

### Steps to reproduce the behavior
After I deleted in dolibarr / htdocs / core / modules / export / export_excel2007.modules.php on line 93 the problematic code worked
![export ds](https://user-images.githubusercontent.com/101409275/157892929-403c3a14-094d-4a19-a1dd-f1b630795633.png)
**### but it comes to this error after I request Excel 2007 file** (CSV works fine):
" Warning: require_once(/var/services/web/dolibarr/htdocs/includes/phpoffice/phpspreadsheet/src/autoloader.php): failed to open stream: No such file or directory in /volume3/web/dolibarr/htdocs/core/modules/export/export_excel2007.modules.php on line 198 Fatal error: require_once(): Failed opening required '/var/services/web/dolibarr/htdocs/includes/phpoffice/phpspreadsheet/src/autoloader.php' (include_path='/volume3/web/dolibarr/htdocs') in /volume3/web/dolibarr/htdocs/core/modules/export/export_excel2007.modules.php on line 198 "
### Attached files

![export](https://user-images.githubusercontent.com/101409275/157883399-146973c8-8807-4538-aa0b-47b85b20526f.png)
![import](https://user-images.githubusercontent.com/101409275/157883473-90c11522-316e-4a8e-9148-21d949f4ee77.png)
AFTER I enable the display for PHP-error messages:
![export 15](https://user-images.githubusercontent.com/101409275/157890764-b543efa0-cc3a-46f4-8176-a9b023e63022.png)

**Comment by DATUC** [comment]
I had an issue wen tring to import costumers in V15 allways hav this error
![image](https://user-images.githubusercontent.com/26550824/159231793-454ecec7-5a6d-4f06-9f49-78f0b1769b71.png)

and also have this field Field 18->s.skype 
how to solve this please

**Comment by Arre8** [comment]
see https://github.com/Dolibarr/dolibarr/issues/20417
