### ISSUE TITLE
External users cannot see projects

### ISSUE THREAD

**Issue by libremaster** [Dolibarr/dolibarr#20331]
### Bug

External users can't access to their projects because of access check mistake.

### Environment Version

14

**Comment by libremaster** [comment]
[project.class.php.txt](https://github.com/Dolibarr/dolibarr/files/8236574/project.class.php.txt)

**Comment by julbroa** [comment]
hi for me don´t works in 14.0.5 version @Hystepik could you explain me how make it work?

**Comment by Hystepik** [comment]
hi @julbroa , I added the permissions of the external user
