### ISSUE TITLE
Implementation of API with Frensh CESU (URSSAF)

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#20332]
### Feature Request

Hi,
more and more users report that there is a new way in payment processing regarding the CESU.

Is it a subject for a next version of dolibarr ?
did some developer plan to develop a such external module ?

### Use case

https://www.dolibarr.fr/forum/t/support-des-api-cesu-avance-immediate/39421
https://www.dolibarr.fr/forum/t/api-avance-immediate-dans-dolibaar/39488
https://www.dolibarr.fr/forum/t/reglement-en-cesu-prefinance/6331

### Suggested implementation

https://www.urssaf.fr/portail/files/live/sites/urssaf/files/pdf/Avance%20immediate_OSP_webconf_2112_VF.pdf

**Comment by hansemschnokeloch** [comment]
Hi,

On the forum, people are talking about two different APIs provided by URSSAF. Theses two APIs have nothing in common.
You have to do a "request for authorization" for each of them if you want acces to the test environment.

API tiers de prestation : https://api.gouv.fr/les-api/api-tiers-de-prestation

API tierce déclaration CESU : https://api.gouv.fr/les-api/api-declaration-cesu

**Comment by LeBelou66** [comment]
Des nouvelles ?

**Comment by hansemschnokeloch** [comment]
URSSAF services for "tiers de prestation" and "declaration cesu" are very specific to France and can only be used by a very specific target group.
Besides of that, the URSSAF API specification can change rapidly as regulation evolves.

This is typicaly a feature for an external module, not something to add to the core of Dolibarr.

**Comment by RemiPoignon** [comment]
Hi,
I'm a freelance developer, I developed this module that allows you to use the URSSAF Tiers de Prestation API.
I asked the API for sandbox codes to test my module before putting it on the dolistore. I think it should arrive in the next few weeks.
