### ISSUE TITLE
it units-rains cats and dogs

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#20349]
### Feature Request

Hi

On all forums, there is lots of topics about conversion, packaging and units for products and service.
There is a begining of unit implementation with PRODUCT_USE_UNITS and in purchase prices.

I think this would be great to implement :
* a real decimal conversion between units in the unit dictionary (not scale) (including time conversion for services?)
* allow do define specific conversion for each product/service (replacing dictionary and/or adding new)
* allow to visualise any data in dolibarr in any conversion relative to a product/service
* use any existing conversion to enter an order/invoice/inventory/BOM... line (with a well designed conversion tool like a "pocket-calculator/translator" for example)
* use any existing conversion to setup customer/provider prices

note : this idea could seem to be too large and could be divided into a simple unit system AND a real implementation of packaging.
But i don't think so:
A vendor has to be able to sell a crate of 10 salad or 1 salad, buy 1kg of metaland sell one metter of tube, with different prizes and only one product, without OF or packaging workflow. (there is physically only one stock and no additionnal value converting one to each other)
There are way more examples all over the forum and each day in industry, services and stores.
In a next step (not in this project) : a WMS-compatibility (API?) and/or a packaging notion could be added to shipment and receipt.

Of course, the existing system with only a quantity and no "units" feature have to continue to work.

I have already ask to the frensch community if this kind of idea would be intersintg:
https://www.dolibarr.fr/forum/t/sondage-unites-de-stock-vente-achat/39044

and started functional specifications (it's only the V1 !!)
https://dzen.art/CDCF_uniteplus_V1.pdf

and consider to promot/explain the project with video, here is a trial : (please do not share, this video will be soon deleted) subtitle available in english.
https://youtu.be/t8QgxFC_jP8  

I know that a really big dev-job, so i will work with a dev compagny which is able to make a such project.
Actually, i only work for taking advices, communicate about the idea and building spec.
The project may represent 15-20 days of dev (?) so i want to help a quick implementation with a crowdfunding.

This post IS NOT to discuss about "how" but only about intereset.

What main developper of dolibarr (and others :) ) think about that ?
Should i continue ? stop ? change something ?

**Comment by eldy** [comment]
Hi currently we already have a table that store all the existing units. This table also contains the rule to make conversion from one unit to another one (it is used to be able to calculate total weight of a shipment for example when several product references are using different units. Only some uncommon units are hard coded, but we can enhance the existing table to remove this hardcoding by recording the rule for conversion for this special units too.

A good practice to address management of different packaging ("conditionnement" in french) that is the feature described into the examples of this feature request, is to use different sub-reference for each king of package and we make a manufacturing order to convert one product into another one (for example 100 P1 are converted into 1 product P100 once packaged).
For some user, using this recommended practice to manage packaging may be a gaz engine (when the need is very light). In such a case, we can imagine an easier way, the same way it is to manage packaging for the purchased product (with the several possible packagings that are defined into the sale price tab, like we defined the several packagings in the purchase price). Note: A packaging (conditionnement in french) is a (quantity + a label including name of package). But currently on purchase prices, we only record the quantity of a package without the label.

**Comment by Arre8** [comment]
**Hi currently we already have a table that store all the existing units. 
This table also contains the rule to make conversion from one unit to another one** 

Yes, but only if a scale exists between the units.
And why should i have to convert only unit into one dimension ? (ex : m->km)
Why not m->kg ? UN->L ?
H -> day ? H -> Half-day ? (Potentially with a round function : a half hour debuted is counted as a half full hour for example)

**(it is used to be able to calculate total weight of a shipment for example when several product references are using different units.** 

But the sum of weights is not obligatory the weight of the products reunited.
1 feather crate = 10 kg
1 pallet of 10 feather crate = 110kg (10 feather crate + the pallet + packaging load)
A way to solve that :
Discard weight form product and :
* add a weight on each unit conversion (but this have to be set on each unit/product, not in a global dictionnary)
* or set as specific conversion in the product (pal<->kg, crate<->g, etc...)
But not a good idea too... a secretary does not know often how the product will be prepared : 1 big palett ? 1 palett + an half ? ...

-> In that case, "net weight" could stay as an "information" in the product, but the list/weight of the product packaged/prepared should be on the delivery. (That is another question, not included in the development that i plan)
(this question is the same for surfaces, dimensions and volume)

**Only some uncommon units are hard coded, but we can enhance the existing table to remove this hardcoding by recording the rule for conversion for this special units too.**

Totaly agree: that's a part of the dev.

**A good practice to address management of different packaging ("conditionnement" in french) that is the feature described into the examples of this feature request, 
is to use different sub-reference for each king of package and we make a manufacturing order to convert one product into another one 
(for example 100 P1 are converted into 1 product P100 once packaged).**

Sub-reference are not real sub-reference in dolibarr : they are other reference linked to the parent one.
Not really user-friendly to manage conversion and stock.
(sub-ref are really great to manage variant of a product, such as color or size, but not for packaging)

In my opinion : If no modification of the value and no modification of the real, physical stock; you don't have to do a manufacturing order.
In big society, financial department and head quarter use generally this rule to determine the necessity of a management level or not.
In little society : no time to do a manufacturing order (in this specific case!) and not necessarily cause no financial movement.

**For some user, using this recommended practice to manage packaging may be a gaz engine (when the need is very light). 
In such a case, we can imagine an easier way, the same way it is to manage packaging for the purchased product 
(with the several possible packagings that are defined into the sale price tab, like we defined the several packagings in the purchase price). 
Note: A packaging (conditionnement in french) is a (quantity + a label including name of package). But currently on purchase prices, we only record the quantity of a package without the label.**

I agree : this is why i propose this evolution : "hard" to code/modify in dolibarr, but really easy to use and not "closed" to a short list of users' cases.
I join your opinion with a next step for packaging functionnality (like described above)

**Comment by Arre8** [comment]
Oops: i did not read the last sentence correctly.

**In such a case, we can imagine an easier way, the same way it is to manage packaging for the purchased product
(with the several possible packagings that are defined into the sale price tab, like we defined the several packagings in the purchase price).
Note: A packaging (conditionnement in french) is a (quantity + a label including name of package). But currently on purchase prices, we only record the quantity of a package without the label.**

You're right and the implementation of multiple units is an effective way to implement this "label" everywhere in dolibarr
Without risk of "exotic" label and allow to stock more information.
It could make the workflow easier to understand too: you do not have to remember that "56430 units" are in fact 1 conteiner for this product.
or every time, while a secretary is selling : "How many crates are in 1 pallet ?" "How many meter are in 1 roll?"...

**Comment by edupulpillo** [comment]
Hi, maybe also is useful to keep in mind that the packaging materials need to be considerate as components of the product (Kits, manufacturing, Bom...) what do you think?

**Comment by Arre8** [comment]
Hi @edupulpillo 
yes and today it's already what's you can do:
* for manufactured product : you can add packaging in BOM
* for resseler : the packaging is allready in the product price
* for kit : the packaging can be a part of the kit, same as other products included in the kit

You could want to add pallet, plastic film, box while re-packaging/protecting product or grouping product for shipment.
As discribe above, this last thing should  
* or incorpored in the shipment process, (adding lines in th shipment, decrease the stock of packaging, etc..)
* or managed as a manufactiring order

It's not a part of this project, but you're right :)

**Comment by Arre8** [comment]
V2 of  functional specifications :)
ligher, decrease of impact on actual functionnality, precision for supplier/customer prices.

Sorry, only in Frensh, V3 will be easer to read for final users and in Frensh and English

https://dzen.art/CDCF_uniteplus_V2.pdf

**Comment by Arre8** [comment]
Here are the V3 functional specifications in English (screenshot are still in frensh -> will be corected in V4)

https://dzen.art/CDCF_uniteplus_V3EN.pdf

Feel free to comment/approve/desapprove … :)

**Comment by edupulpillo** [comment]
Also is a good idea to determine the number of layers of the packaging.
For example: Pallet+Cartonbox+Innerbox+Productbox have 4 layers.

**Comment by edupulpillo** [comment]
Any progress in this matter?

**Comment by zunami** [comment]
That's a shame – that's exactly what I was looking for. Once again, it hasn't made it onto the Dolibarr wish list. :-(
