### ISSUE TITLE
Need HR module support biometric devices

### ISSUE THREAD

**Issue by Mohaamaad7** [Dolibarr/dolibarr#20352]
### Feature Request

Hello

I need module support getting data from fingerprint devices and saving it to excel or pdf 

and also need to know the best fingerprint devices brand to use with this system 

any help ?

**Comment by riseval** [comment]
Hi

Normally, finger print devices store text data in the terminal and FTP them at selected intervals to the central server - which ever you configure.

Did you try this feature giving your Dolibarr server folder shareable with the terminal device user and then try to pump the text file into dolibarr db..?

thanks
yesbee
