### ISSUE TITLE
Module externalsite no more working in version 13 and 14

### ISSUE THREAD

**Issue by LesCarnets** [Dolibarr/dolibarr#20351]
### Bug

Hello,

The "externalsite" was well working in Dolibarr v12 (and before) but it is no more working since v13 (and v14).

The iframe is well displayed but the top menu bar disappears :(

I tried to enable/disable the module, same problem.
I tried on a new deployment (instead of upgrade), same problem.

Thank you by advance for your help,

Best regards,

### Environment Version

All versions from 13.0.0 to 14.0.5

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

MySQL

### Expected and actual behavior

What was displayed in 12.0.5:
![image](https://user-images.githubusercontent.com/36789892/158158658-5e01354d-acc7-4373-852e-088acba084a8.png)

What is displayed in 14.0.5:
![image](https://user-images.githubusercontent.com/36789892/158158755-d0478404-b07e-4f42-b8bc-e742596dc671.png)

### Steps to reproduce the behavior

Here are the settings of the module:
![image](https://user-images.githubusercontent.com/36789892/158160440-5bfbf958-e206-4e6e-9e2e-4bf3a20cb73d.png)

**Comment by ksar-ksar** [comment]
Hello,

I don't understand, why, but it is because of a "display:none;"
![image](https://user-images.githubusercontent.com/35605507/158163136-4b758d77-d4b7-4a1d-a65b-b23e5d92b712.png)

**Comment by LesCarnets** [comment]
Hello @ksar-ksar,

Thank you for this. How can I change that? Because I cannot see this parameter in the module settings:
![image](https://user-images.githubusercontent.com/36789892/158163501-d93a7468-9167-4bb3-b9d3-96f3395ac886.png)

Thanks and best regards,
