### ISSUE TITLE
__unsubscribe__  not generating link

### ISSUE THREAD

**Issue by rportojr** [Dolibarr/dolibarr#20367]
### Bug

The __unsubscribe__ link for the email templates does not render a link when the email is sent.

### Environment Version

15.0.0

### Environment OS

Linux business94.web-hosting.com 2.6.32-954.3.5.lve1.4.80.el6.x86_64 #1 SMP Thu Sep 24 01:42:00 EDT 2020 x86_64

### Environment Web server

LiteSpeed

### Environment PHP

 7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-cll-lve

### Expected and actual behavior

no unsubscribe link was generated in the email when using the available substitution variables.

Thank you for your time.

Roger

### Steps to reproduce the behavior

Add __UNSUBSCRIBE__ to my email template

send email to test email address

email just has __UNSUBSCRIBE__

### Attached files

![emailtemplate_1-unsubscribe](https://user-images.githubusercontent.com/101669684/158459549-a887d316-457f-48a5-88c1-ed76a62b20e7.png)
![emailtemplate_2-unsubscribe](https://user-images.githubusercontent.com/101669684/158459560-3b4351b7-69c4-4063-b95e-3f503a2aea1a.png)
![emailtemplate_4-unsubscribe](https://user-images.githubusercontent.com/101669684/158459583-b1cf34c3-f15a-4881-8de0-78ce042a03f3.png)

**Comment by trekmorris** [comment]
Hi 

This also happen in v 14.0.3 and v15.0.1 .

**Comment by BoyLado** [comment]
**Try this simple modification:**

**Step 1:**
Open Dolibarr/htdocs/core/actions_sendmails.inc.php directory and search for `__CHECK_READ__` substitution array index.
Below that code, paste the `__UNSUBSCRIBE__` substitution code below.

`$substitutionarray['__UNSUBSCRIBE__'] = '<a href="'.DOL_MAIN_URL_ROOT.'/public/emailing/unsubscribe.php?unsuscrib=1&securitykey='.urlencode($conf->global->MAILING_EMAIL_UNSUBSCRIBE_KEY).'&email='.urlencode(sendTo($sendto)).'&id='.$sendtoid[0].'" target="_blank" rel="noopener noreferrer">Unsubscribe</a>';`

After that, paste the `sendTo()` function at the bottom part of the file.
 
```
function sendTo($val)
{
	$regs = array();
	if (preg_match('/^(.*)<(.*)>$/i', trim($val), $regs)) {
		$name  = trim($regs[1]);
		$email = trim($regs[2]);
	} else {
		$name  = '';
		$email = trim($val);
	}

	return $email;
}
```

**Step 2:** 
Open Dolibarr/htdocs/public/emailing/ directory, create `unsubscribe.php` file and paste the code below.

```
<?php

if (!defined('NOLOGIN')) {
	define('NOLOGIN', '1');
}
if (!defined('NOCSRFCHECK')) {
	define('NOCSRFCHECK', '1');
}
if (!defined('NOBROWSERNOTIF')) {
	define('NOBROWSERNOTIF', '1');
}
if (!defined('NOREQUIREMENU')) {
	define('NOREQUIREMENU', '1'); // If there is no need to load and show top and left menu
}
if (!defined('NOIPCHECK')) {
	define('NOIPCHECK', '1'); // Do not check IP defined into conf $dolibarr_main_restrict_ip
}
if (!defined("NOSESSION")) {
	define("NOSESSION", '1');
}

/**
 * Header empty
 *
 * @return	void
 */
function llxHeader()
{
}
/**
 * Footer empty
 *
 * @return	void
 */
function llxFooter()
{
}

require '../../main.inc.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';

global $user, $conf, $langs;

$langs->loadLangs(array("main", "mails"));

$id = GETPOST('id');
$email = GETPOST('email');
$unsuscrib = GETPOST('unsuscrib');

$securitykey = GETPOST('securitykey');


/*
 * Actions
 */

dol_syslog("public/emailing/mailing-read.php : tag=".$tag." securitykey=".$securitykey, LOG_DEBUG);

if ($securitykey != $conf->global->MAILING_EMAIL_UNSUBSCRIBE_KEY) {
	print 'Bad security key value.';
	exit;
}

if ($unsuscrib == '1') {

	$sql = "SELECT rowid, email, no_email";
	$sql .= " FROM ".MAIN_DB_PREFIX."socpeople ";
	$sql .= " WHERE rowid = '".$id."'";

	$resql = $db->query($sql);
	if (!$resql) {
		dol_print_error($db);
	}

	$obj = $db->fetch_object($resql);

	if (empty($obj)) {
		print 'Email target not valid. Operation canceled.';
		exit;
	}
	if (empty($obj->email)) {
		print 'Email target not valid. Operation canceled.';
		exit;
	}
	if ($obj->no_email == 1) {
		print 'Email target already set to unsubscribe. Operation canceled.';
		exit;
	}
	
	$statut = '1';
	$sql = "UPDATE ".MAIN_DB_PREFIX."socpeople SET no_email=".((int) $statut)." WHERE rowid = '".$id."'";

	$resql = $db->query($sql);
	if (!$resql) {
		dol_print_error($db);
	}


	$sql = "INSERT INTO ".MAIN_DB_PREFIX."mailing_unsubscribe (date_creat, entity, email, unsubscribegroup, ip) VALUES ('".$db->idate(dol_now())."', 1, '".$db->escape($obj->email)."', '', '".$db->escape(getUserRemoteIP())."')";

	$resql = $db->query($sql);

	header("Content-type: text/html; charset=".$conf->file->character_set_client);

	print '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">';
	print "\n";
	print "<html>\n";
	print "<head>\n";
	print '<meta name="robots" content="noindex,nofollow">'."\n";
	print '<meta name="keywords" content="dolibarr,emailing">'."\n";
	print '<meta name="description" content="Dolibarr EMailing unsubcribe page">'."\n";
	print "<title>".$langs->trans("MailUnsubcribe")."</title>\n";
	print '<link rel="stylesheet" type="text/css" href="'.DOL_URL_ROOT.$conf->css.'?lang='.$langs->defaultlang.'">'."\n";
	print '<style type="text/css">';
	print '.CTableRow1      { margin: 1px; padding: 3px; font: 12px verdana,arial; background: #e6E6eE; color: #000000; -moz-border-radius-topleft:6px; -moz-border-radius-topright:6px; -moz-border-radius-bottomleft:6px; -moz-border-radius-bottomright:6px;}';
	print '.CTableRow2      { margin: 1px; padding: 3px; font: 12px verdana,arial; background: #FFFFFF; color: #000000; -moz-border-radius-topleft:6px; -moz-border-radius-topright:6px; -moz-border-radius-bottomleft:6px; -moz-border-radius-bottomright:6px;}';
	print '</style>';

	print "</head>\n";
	print '<body style="margin: 20px;">'."\n";
	print '<table><tr><td style="text_align:center;">';
	print $langs->trans("YourMailUnsubcribeOK", $obj->email)."<br>\n";
	print '</td></tr></table>';
	print "</body>\n";
	print "</html>\n";
}

$db->close();
```

**Comment by daraelmin** [comment]
> **Try this simple modification:**
> 
> **Step 1:**
> Open Dolibarr/htdocs/core/actions_sendmails.inc.php directory and search for `__CHECK_READ__` substitution array index.
> Below that code, paste the `__UNSUBSCRIBE__` substitution code below.
> 
> `$substitutionarray['__UNSUBSCRIBE__'] = '<a href="'.DOL_MAIN_URL_ROOT.'/public/emailing/unsubscribe.php?unsuscrib=1&securitykey='.urlencode($conf->global->MAILING_EMAIL_UNSUBSCRIBE_KEY).'&email='.urlencode(sendTo($sendto)).'&id='.$sendtoid[0].'" target="_blank" rel="noopener noreferrer">Unsubscribe</a>';`
> 
> After that, paste the `sendTo()` function at the bottom part of the file.
>  
> ```
> function sendTo($val)
> {
> 	$regs = array();
> 	if (preg_match('/^(.*)<(.*)>$/i', trim($val), $regs)) {
> 		$name  = trim($regs[1]);
> 		$email = trim($regs[2]);
> 	} else {
> 		$name  = '';
> 		$email = trim($val);
> 	}
> 
> 	return $email;
> }
> ```
> 
> **Step 2:** 
> Open Dolibarr/htdocs/public/emailing/ directory, create `unsubscribe.php` file and paste the code below.
> 
> ```
> <?php
> 
> if (!defined('NOLOGIN')) {
> 	define('NOLOGIN', '1');
> }
> if (!defined('NOCSRFCHECK')) {
> 	define('NOCSRFCHECK', '1');
> }
> if (!defined('NOBROWSERNOTIF')) {
> 	define('NOBROWSERNOTIF', '1');
> }
> if (!defined('NOREQUIREMENU')) {
> 	define('NOREQUIREMENU', '1'); // If there is no need to load and show top and left menu
> }
> if (!defined('NOIPCHECK')) {
> 	define('NOIPCHECK', '1'); // Do not check IP defined into conf $dolibarr_main_restrict_ip
> }
> if (!defined("NOSESSION")) {
> 	define("NOSESSION", '1');
> }
> 
> /**
>  * Header empty
>  *
>  * @return	void
>  */
> function llxHeader()
> {
> }
> /**
>  * Footer empty
>  *
>  * @return	void
>  */
> function llxFooter()
> {
> }
> 
> require '../../main.inc.php';
> require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';
> 
> global $user, $conf, $langs;
> 
> $langs->loadLangs(array("main", "mails"));
> 
> $id = GETPOST('id');
> $email = GETPOST('email');
> $unsuscrib = GETPOST('unsuscrib');
> 
> $securitykey = GETPOST('securitykey');
> 
> 
> /*
>  * Actions
>  */
> 
> dol_syslog("public/emailing/mailing-read.php : tag=".$tag." securitykey=".$securitykey, LOG_DEBUG);
> 
> if ($securitykey != $conf->global->MAILING_EMAIL_UNSUBSCRIBE_KEY) {
> 	print 'Bad security key value.';
> 	exit;
> }
> 
> if ($unsuscrib == '1') {
> 
> 	$sql = "SELECT rowid, email, no_email";
> 	$sql .= " FROM ".MAIN_DB_PREFIX."socpeople ";
> 	$sql .= " WHERE rowid = '".$id."'";
> 
> 	$resql = $db->query($sql);
> 	if (!$resql) {
> 		dol_print_error($db);
> 	}
> 
> 	$obj = $db->fetch_object($resql);
> 
> 	if (empty($obj)) {
> 		print 'Email target not valid. Operation canceled.';
> 		exit;
> 	}
> 	if (empty($obj->email)) {
> 		print 'Email target not valid. Operation canceled.';
> 		exit;
> 	}
> 	if ($obj->no_email == 1) {
> 		print 'Email target already set to unsubscribe. Operation canceled.';
> 		exit;
> 	}
> 	
> 	$statut = '1';
> 	$sql = "UPDATE ".MAIN_DB_PREFIX."socpeople SET no_email=".((int) $statut)." WHERE rowid = '".$id."'";
> 
> 	$resql = $db->query($sql);
> 	if (!$resql) {
> 		dol_print_error($db);
> 	}
> 
> 
> 	$sql = "INSERT INTO ".MAIN_DB_PREFIX."mailing_unsubscribe (date_creat, entity, email, unsubscribegroup, ip) VALUES ('".$db->idate(dol_now())."', 1, '".$db->escape($obj->email)."', '', '".$db->escape(getUserRemoteIP())."')";
> 
> 	$resql = $db->query($sql);
> 
> 	header("Content-type: text/html; charset=".$conf->file->character_set_client);
> 
> 	print '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">';
> 	print "\n";
> 	print "<html>\n";
> 	print "<head>\n";
> 	print '<meta name="robots" content="noindex,nofollow">'."\n";
> 	print '<meta name="keywords" content="dolibarr,emailing">'."\n";
> 	print '<meta name="description" content="Dolibarr EMailing unsubcribe page">'."\n";
> 	print "<title>".$langs->trans("MailUnsubcribe")."</title>\n";
> 	print '<link rel="stylesheet" type="text/css" href="'.DOL_URL_ROOT.$conf->css.'?lang='.$langs->defaultlang.'">'."\n";
> 	print '<style type="text/css">';
> 	print '.CTableRow1      { margin: 1px; padding: 3px; font: 12px verdana,arial; background: #e6E6eE; color: #000000; -moz-border-radius-topleft:6px; -moz-border-radius-topright:6px; -moz-border-radius-bottomleft:6px; -moz-border-radius-bottomright:6px;}';
> 	print '.CTableRow2      { margin: 1px; padding: 3px; font: 12px verdana,arial; background: #FFFFFF; color: #000000; -moz-border-radius-topleft:6px; -moz-border-radius-topright:6px; -moz-border-radius-bottomleft:6px; -moz-border-radius-bottomright:6px;}';
> 	print '</style>';
> 
> 	print "</head>\n";
> 	print '<body style="margin: 20px;">'."\n";
> 	print '<table><tr><td style="text_align:center;">';
> 	print $langs->trans("YourMailUnsubcribeOK", $obj->email)."<br>\n";
> 	print '</td></tr></table>';
> 	print "</body>\n";
> 	print "</html>\n";
> }
> 
> $db->close();
> ```
> 
> 

Could you send a pull request with your proposition to fix this issue please ?

**Comment by inoveaconseil** [comment]
It's work fine. The link is replaced after sending the emailing not in test
