### ISSUE TITLE
viewimage.php and custom module ?

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#20364]
### Bug

I'm not really sure about a bug or not ... so could you please help me ?

On a custom module (for example my module name is "foo"). In "foo" i have a document upload form with

```
    $formfile->form_attach_new_file($_SERVER['PHP_SELF'].'?id='.$object->id.'&amp;type='.$type, $langs->trans("AddPicture"), 1, '', 1, 50, $object, '', false, '', 0, 'formuserfile', '', '', 2);
```

and my picture is stored in a subdir of my module, for example 

```
./(PROV16)/16/photos
./(PROV16)/16/photos/thumbs
./(PROV16)/16/photos/thumbs/main_mini.jpg
./(PROV16)/16/photos/thumbs/main_small.jpg
./(PROV16)/16/photos/main.jpg
```

then admin could view pictures with `https://my.server/viewimage.php?modulepart=foo&file=photo/(PROV16)/16/photos/main.jpg` but users always get the security wall ...

i've spent time to search and i found that in core/lib/files.lib.php, function dol_check_secure_access_document wich seems to be the good part of what i need:

```
            if (!empty($fuser->rights->$modulepart->{$lire}) || !empty($fuser->rights->$modulepart->{$read})) {
                $accessallowed = 1;
            }
```

but my object does not have user->rights->foo->read, i just have user->rights->foo->document->read ... so i think there is a problem somewhere in my brain ... then could you please help me ? or could it be a bug ? and core/lib/files.lib.php miss submodule part in rights access tests ?

juste note that if i change dolibarr code to that, it works:

```
            if (!empty($fuser->rights->$modulepart->$modulepart->{$read}) || !empty($fuser->rights->$modulepart->{$read})) {
                $accessallowed = 1;
            }
```

Thanks

### Environment Version

Dolibarr 14.0.5 on apache2 / PHP 7.4 MariaDB 10

**Comment by eldy** [comment]
If you want to manage a permission
user->rights->mymoduleabc->myobjectdef->read
files for object myobjectdef must be stored into a path like this
/mymoduleabc/myobjectref/(PROV...)/xxxxxxx

link will be download.php?modulepart=mymoduleabc&file=myobjectdef/...

**Comment by rycks** [comment]
ok, thanks, subdir is subright
