### ISSUE TITLE
Crash occurs validating a BOM list if the ODT template is not activated in settings

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#20368]
### Bug

Creating a new BOM list and clicking over "validate" originates a crash error.

### Environment Version

15.0.0

### Environment OS

Linux

### Environment Web server

Apache/2.4.52 (cPanel) OpenSSL/1.1.1m mod_jk/1.2.41 mod_bwlimited/1.4 mod_fcgid/2.3.9 Phusion_Passenger/6.0.7

### Environment PHP

PHP 7.3.33

### Environment Database

MySQL or MariaDB 5.5.5-10.3.31-MariaDB

### Environment URL(s)

/bom/bom_card.php?id=2&action=confirm_validate&confirm=yes&token=this_is_the_token

### Expected and actual behavior

Find below the the path and error messages displayed:

![image](https://user-images.githubusercontent.com/7486607/158496005-8fa4998e-b13d-45f8-89e1-571d14e98d4d.png)

This problem occurs when is clicked this button:
![image](https://user-images.githubusercontent.com/7486607/158496237-630065f4-05d5-45e8-93aa-5a9d6553af9a.png)

### Steps to reproduce the behavior

Just validate one BOM list and observe the problem.

**Comment by atm-kevin** [comment]
I will check on my side and get back to you as soon as I have more information

**Comment by atm-kevin** [comment]
I can't reproduce

**Comment by edupulpillo** [comment]
wich version?

**Comment by erikvanberkum** [comment]
I can reproduce this when i rename the file: /htdocs/core/modules/bom/doc/dox_generic_bom_odt.modules.php to something different

![image](https://user-images.githubusercontent.com/7335299/160262846-7a58f06f-edae-4daa-86b6-f7009be5fff7.png)

but mine looks like modele=generic_bom...

yours looks like modele=avalue

can you share a screenshot of your BOM setup? Below is the one i have

![image](https://user-images.githubusercontent.com/7335299/160262927-9ba56dfe-0cfc-4a97-805b-e398bf5fb838.png)

**Comment by edupulpillo** [comment]
Thank you for the feedback.
I did not have activated any ODT template in the configuration of the module.
I just activate it in the default ODT template same as you have with the default path DOL_DATA_ROOT/doctemplates/boms , and the problem persist if is not selected "default". After selecting the checkbox "default" the crash problem disappear.
So still is needed to fix something in the code checking that if is not selected any document template by default, to make the system display a warning message instead get a crash.
The version i tested this time is the 15.0.2

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by edupulpillo** [comment]
It seems fixed in v18.0.2 using both PHP 7.4 or PHPv8.0
Problem seems fixed.
