### ISSUE TITLE
v15 : Accounting - Reporting - Personalized groups : Custom groups formulas not computing

### ISSUE THREAD

**Issue by AurelienBISOTTI** [Dolibarr/dolibarr#20373]
### Bug

Formula in a reporting custom group are not computing. 
See screenshots
Bug only in v15. v13 and v14 were OK.

### Environment Version

15.0.1

### Environment OS

Linux ubuntu

### Environment Web server

Apache

### Environment PHP

7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0ubuntu0.20.04.1

### Expected and actual behavior

Sum should work

### Steps to reproduce the behavior

Create custom groups (with data in bookkeeping corresponding to these accounts) and sum them.

### Attached files

![1](https://user-images.githubusercontent.com/12530585/158555717-6f059aac-eba2-45bb-9eee-5ff63f422256.PNG)
![2](https://user-images.githubusercontent.com/12530585/158555738-81b020dc-b1b9-4b52-8939-d0c1263b5446.PNG)

**Comment by atm-gauthier** [comment]
Hi @AurelienBISOTTI, @eldy and I add some corrections in this screen yesterday, but like you i just saw that there are other problems with prices containing decimals.

@eldy how can we use dol_eval() function in custom accountancy groups report if dot char is forbidden ? dot is necessary with prices.
This block can't work with accoutancy report :

	if (strpos($s, '.') !== false) {
		if ($returnvalue) {
			return 'Bad string syntax to evaluate (dot char is forbidden): '.$s;
		} else {
			dol_syslog('Bad string syntax to evaluate (dot char is forbidden): '.$s);
			return '';
		}
	}

There is a problem here, should we add a new parameter to dol_eval() to allow dot char when we come from custom accountancy groups report or simply remove this block ?

**Comment by Veance** [comment]
Hi,

Same problem for me since 15.0 (15.0.0 --> 15.0.1--> 15.0.2). 
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/16508670/161809614-81a2d033-dafd-4eb4-b5d3-0a54ed984796.png">

Any advice for make it work until update ?

Thanks ! 
Regards,

**Comment by AurelienBISOTTI** [comment]
I think you can delete the block in dol_eval() :
if (strpos($s, '.') !== false) ...

But I'm not sure why it is here and what other functions need to check if there is a dot.

**Comment by Rincewind76** [comment]
Any update on this topic? Which file needs a change to make it work again?

**Comment by atm-gauthier** [comment]
@Rincewind76 dol_eval() function in core/lib/functions.lib.php needs to be corrected, but we need @eldy to know what correction we are allowed to add. in this specific case it's difficult to be sure of what we have to do.

**Comment by AurelienBISOTTI** [comment]
I have commented all the suspected code in core/lib/functions.lib.php, but the sum is still not working

**Comment by Beta555** [comment]
We just implemented a nice system in DB 14.05 with Extrafields to do some neat stuff, but after upgrading to 15.0.1 we have a dot problem with this kind of code:

($ContactID = $object->array_options['options_order_contact_id']) 
	?
	(
		(($result = $db->query('SELECT sp.firstname AS Firstname, 
									sp.lastname AS Lastname, 
									soc.nom AS Companyname 
							FROM llx_socpeople AS sp INNER JOIN llx_societe AS soc ON sp.fk_soc=soc.rowid 
							WHERE sp.rowid='.$ContactID.';')) && 
		 ($row = $db->fetch_object($result))
		) 
			? 
			($row->Companyname.' - '.$row->Firstname.' '.$row->Lastname)
			:
			('not found')
	) 
	: 
	(
		(($result = $db->query('SELECT soc.nom AS Companyname 
							FROM llx_societe AS soc WHERE soc.rowid='.$object->socid.';')) && 
		 ($row = $db->fetch_object($result))
		) 
			? 
			($row->Companyname.' - '.'Dept. purchasing')
			:
			('not found')
	)

Without a dot you can't even concatenate strings I suppose.

**Comment by Beta555** [comment]
The above query and all other code works normally again when I take out the dot-filter from functions.lib.php (lines 8243 - 8252).

**Comment by atm-gauthier** [comment]
Hi eveybody, it seems that @eldy did a correction commit https://github.com/Dolibarr/dolibarr/commit/ef184567248af5dbeea8cbd63be5cd2d965ad756
Can someone pull Dolibarr 15.0 and check if it's ok now ?

**Comment by Rincewind76** [comment]
With the 15.0.2 it works on my side now

**Comment by Beta555** [comment]
My report from yesterday about queries not working was actually about 1.50.2, not 15.0.1 (my mistake). 

It has this piece of code that blocks the queries:

```
	if (preg_match('/[^0-9]+\.[^0-9]+/', $s)) {	// We refuse . if not between 2 numbers
		if ($returnvalue) {
			return 'Bad string syntax to evaluate (dot char is forbidden): '.$s;
		} else {
			dol_syslog('Bad string syntax to evaluate (dot char is forbidden): '.$s);
			return '';
		}
	}
```
I think that theoretically it would still block a number like '-.4'. And also something like 'Name: '.$name

So our query problems are not solved with this fix.

What is acutally the rationale behind blocking the dot? What dot construct would pose a security risk? Or are queries themselves considered a risk?

**Comment by Veance** [comment]
It works on my side too since 15.0.3. 
Thanks !

**Comment by AurelienBISOTTI** [comment]
I can confirm, solved with 15.0.3

**Comment by Beta555** [comment]
I'm not getting any response to my questions about running queries from a computed field, and this issue has been closed without addressing our problems.

Is the official standpoint that queries are not allowed in computed fields?

**Comment by AurelienBISOTTI** [comment]
Hello, I closed the issue because the initial problem is solved, I think you might open another one.

**Comment by Beta555** [comment]
Thanks Aurelien. I will open a new issue.
I jumped in on this one because it is the same lines of code that create our problem.
