### ISSUE TITLE
Project activity filtering failed

### ISSUE THREAD

**Issue by jsoto61** [Dolibarr/dolibarr#20401]
### Bug

In the project module, when I apply the filters for the search of activities with certain values in the different fields, many more results are displayed than expected. Many repeated items appear. However, when I sort them (by clicking on any of the fields) the correct records appear. The error is always reproduced when we click on the magnifying glass icon

### Environment Version

14.0.5

### Environment OS

Linux com404.raiolanetworks.es 3.10.0-962.3.2.lve1.5.38.el7.x86_64 #1 SMP Thu Jun 18 05:28:41 EDT 2020 x86_64

### Environment Web server

LiteSpeed

### Environment PHP

7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB

**Comment by inoveaconseil** [comment]
I can't reproduce. It's work for me
