### ISSUE TITLE
Scheduling sending emails

### ISSUE THREAD

**Issue by jsoto61** [Dolibarr/dolibarr#20404]
### Feature Request

Possibility to schedule the date/time of sending the email.

**Comment by edupulpillo** [comment]
Sounds great. Then also will be necessary to manage a queue of emails, just in case need to cancel/update the emails pending to send.

**Comment by atm-maxime** [comment]
Are you talking about any email you can send (from an invoice i.e.) or about the emailing module ?

**Comment by jsoto61** [comment]
I´m talking about any email I can send (from an invoice i.e.)

**Comment by edupulpillo** [comment]
In any case, if a queue of emails is going to be setup, it will be shared between the both scenarios.
