### ISSUE TITLE
When attached file is uploaded on a supplier invoice not validated. When validated the uploaded attachment disappear

### ISSUE THREAD

**Issue by iaoranamoa** [Dolibarr/dolibarr#20408]
### Bug

Hi, 
When you have a supplier invoice and you want to attach the original supplier invoice to be linked to the dolibarr invoice, you upload the file. When uploaded you should have 2 files attached. The dolibarr supplier invoice and the attachment.

Doing this on the draft works fine.
The trouble is when you validate the invoice the uploaded file disappear and you keep the only new generated dolibarr supplier invoice.
Looking on the web server and the llx_ecm_files tables :
The file is still on the web server but in a PROV directory and the path in ecm_files is also related to the PROV document which is no longer valid.

![2022-03-19 16_09_33-127 0 0 1 ](https://user-images.githubusercontent.com/35940936/159108446-897cf419-3c26-4ae6-9f46-3786002401be.png)

### Environment Version

tested on 14.0.0 and 14.0.5

### Environment OS

windows 10

### Environment Web server

nginx/1.20.2

### Environment PHP

 7.4.28

### Environment Database

5.5.5-10.1.48-MariaDB

### Expected and actual behavior

Should keep the attached file to the invoice validated

### Steps to reproduce the behavior

Easy to reproduce look at the bug description.

**Comment by edupulpillo** [comment]
I can not reproduce it, It works fine for me in 15.0.2 in Linux
