### ISSUE TITLE
V15.0 Insert barcode along with Product in Invoice using ODT

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#20411]
### Bug

Hi,

Using ODT, I am trying to:

(a) insert barcode next to product SKU / code
(b) insert barcode / QR Code for Invoice so as to verify the authenticity of the Invoice.
(c) insert a paypal link in the Invoice PDF so that customers can pay for the invoice by clicking the link

I am trying all possible methods without luck including experimenting with all of the tags from https://wiki.dolibarr.org/index.php/Create_an_ODT_document_template

Can any one help whether you have solved similar issues ? If yes, grateful for sharing the know-how.

thank you,
yesbee.

### Environment Version

15.0.0

### Environment OS

Ubuntu 18.04

### Environment Web server

Apache2.4

### Environment PHP

7.4

### Environment Database

MySQL

### Expected and actual behavior

To generate Invoice using ODT file :

Sno | Barcode | Product SKU| Product Desc | Rate | Qty | Tax | Amount

### Steps to reproduce the behavior

1) enable barcode and create default code patterns
2) enable barcode in product and services
3) Create and ODT and use the tag {company_barcode} and create custom field for {line_product_barcode}
4) Use Miscellaneous tab and Upload the ODT to Invoices 
5) Generate Invoice.

Unfortunately, the barcode doesnot appear.

**Comment by lmag** [comment]
Thoses functions are not availables in the .odt files at the moment I change  tag to feature request
