### ISSUE TITLE
Import bug on Field 18->s.skype Unknown column 'skype' in 'field list'

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#20417]
### Bug

I had an issue wen tring to import costumers in V15 allways hav this error
* Line 3
    > Unknown column 'skype' in 'field list'

As long as the social network fields are no longer on the user, company, members, tables.
how to solve this please

### Environment Version

Dolibar 14.0.5 and 15

### Environment OS

Linux shared hosting

### Environment Web server

LAMP

### Environment PHP

7.4

### Environment Database

5.6

### Attached files

![image](https://user-images.githubusercontent.com/26550824/159263603-a86e3e6c-4e96-4b19-b8f9-be1844270a67.png)

**Comment by Arre8** [comment]
This is not a bug, 
Activate the module "socialNetwork" and manage the networks in dictionary.
This will automacly create the field in database.

**Comment by DATUC** [comment]
Bug solved on v15.0.1
