### ISSUE TITLE
V15 Miscellaneous payments / Social/fiscal taxes - wrong update of Bank entry 

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#20414]
### Bug
ACCOUNTING (SIMPLIFIED) = ON

When you click on first MODIFY button on the bank entry, coming from a Miscellaneous payments (/compta/bank/line.php?rowid=xxx&save_lastsearch_values=1) AND the entry is flaged "Entry reconciled with bank receipt"
fk_acount is set to 0 in llx_bank.
The entry becomes orphelin.

### Environment Version

V15

### Expected and actual behavior

keep the fk_acount unmodified in llx_bank.

**Comment by Arre8** [comment]
or disable the first MODIFY button when  the entry is flaged "Entry reconciled with bank receipt" ?

**Comment by Arre8** [comment]
one more example on Social/fiscal taxes: (V14.0.1)
https://www.dolibarr.fr/forum/t/charge-sociale-sans-banque/39730

**Comment by funsurfer2008** [comment]
Maybe Same error as Said Herr:
editing Bankentries borken since 14.0.5 #20273
