### ISSUE TITLE
Strings not being replaced with translation

### ISSUE THREAD

**Issue by gillerby** [Dolibarr/dolibarr#20418]
### Bug

e.g. in attachment you can see it says "setupdescription1" where the proper string in english should go.

My user's language is english.

### Environment Version

14.0.5 (continues in 15.0.1)

### Environment PHP

7.4

### Environment Database

mysql

### Attached files

![image](https://user-images.githubusercontent.com/36923120/159267939-962bf0e6-52cb-4163-9d3e-622b9c0b385b.png)
![image](https://user-images.githubusercontent.com/36923120/159267972-2f9a2aa9-4b76-45ff-9931-fd5de5732160.png)

**Comment by atm-lena** [comment]
I can’t reproduce the problem
