### ISSUE TITLE
Password(s) for Document share links and online signatures

### ISSUE THREAD

**Issue by DrSloth** [Dolibarr/dolibarr#20427]
### Feature Request

Add Passwords to file shares and online proposals.

### Use case

Currently files can be shared with a public share link, also there is a feature for online proposal signature.
Adding the possibility to protect both with passwords would boost the security and would prohibit people with the link but without the password to access the file/proposal.

This means that for such links a double security would be enabled by distributing the password and link in different ways.

This would be espacially useful if you can allow members of the organization to access the files with their own passwords and distribute multiple passwords for the customer on a per file basis.

I am always a bit paranoid with such things, i think it would be nice to protect everything further to prevent missuse or data leaks.

### Suggested implementation

I think storing passwords and storing "permits" in an n:m table would be possible. On the frontend the file download would need to be extended with a password field. Also an option on any file and general configuration for permits would be necessary. 

### Suggested steps

I don't know if the interest for this exists, or if the hashs, inside the links, are considered enough security. I am a Programmer myself and i know the stack Dolibarr uses but i haven't implemented anythin for dolibarr yet. However i already took a look at the implementation guides and started to work myself into Dolibarrs implementation. With some guidance i might be able to help implement this.

To implement this all the parts would need to be put in place. First extending the database with permits then implementing configuration and last implementing file download password dialog.

**Comment by LaplancheMaxime** [comment]
Hi,

I have created this issue: #20486 
I think that our issues are complementary

Have a nice day
