### ISSUE TITLE
V15.x : Upgrade to 15.0.1 crash from 14.0.5

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#20437]
### Bug

During upgrade process, i get some errors

### Environment Version

15.0.1

### Environment OS

Debian 10.11

### Environment Web server

nginx/1.21.6

### Environment PHP

7.3.31

### Environment Database

PostgreSQL 13.6 

### Expected and actual behavior

Expected : Upgrade without problems
Actual behavior : Some crashs appear

### Steps to reproduce the behavior

Run the upgrade process from 15.0.1 to 14.0.5

### Attached files

![2022-03-22_191922](https://user-images.githubusercontent.com/11213740/159551904-3418d70d-680b-45b4-91fe-102ebf5040a6.png)

**Comment by ptitgnu** [comment]
Yep, same bug here with pgsql 9.6...
I'll go back to 14.0.5 while waiting for a fix.

**Comment by ludovicandrieux** [comment]
Fix in 15.0.2 with this issue #20476
