### ISSUE TITLE
V15.0.1 Nothing happens after clicking quotation sign button

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#20445]
### Bug

Nothing happens after clicking on quotation signing button

Please refer to the attachment picture for details

### Environment Version

15.0.1

### Environment OS

Ubuntu 18.04

### Environment Web server

Apache2.4

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

https://www.dolibarr-URL/public/onlinesign/newonlinesign.php

### Expected and actual behavior

Expected : After clicking on Sign button, the response page to be loaded informing customer about the action taken
Actual : System doesnot move forward

### Steps to reproduce the behavior

1. Create a Test thirdparty with Customer profile.
2. Goto Customer Tab and click Create quotation button
3. Create a quotation using ODT and click on "Generate button"
4. Copy the Link for online signature and paste it in the new browser window
5. sign using mouse and click on "Sign" button.
6. The system doesnot move forwards.

### Attached files

![image](https://user-images.githubusercontent.com/85006729/159756201-6c96a89d-097f-4a8f-b027-0aff03d98140.png)

**Comment by trekmorris** [comment]
same as #20131
