### ISSUE TITLE
Unable to upgrade from 14.05 to 15.01 via Softaculous

### ISSUE THREAD

**Issue by akhalz** [Dolibarr/dolibarr#20462]
### Bug

I am unable to upgrade from 14.05 to 15.01 via Softaculous.
After selecting upgrade in the initial checking submitted data phase it throws the following error:
 The following errors were found :

    This script is not compatible with PHP version : 8.0.0+
    Do you wish to enable PHP 7.4.28 ? (Might cause issues with your existing installations).
    Required PHP version less than : 8.0.0 AND found version is : 8.0.16
    Do you wish to enable PHP 7.4.28 ? (Might cause issues with your existing installations).

It looks like an incorrect minimum requirements listing with Softaculous. 

### Environment Version

14.05

### Environment OS

Linux galex.aserv.co.za 3.10.0-1160.45.1.el7.x86_64

### Environment Web server

Apache

### Environment PHP

8.0.16

### Environment Database

MySQL or MariaDB 10.2.43-MariaDB

### Expected and actual behavior

Expected : Move forward with Upgrade
Actual : Doesnt start upgrading as it is blocked due to compatibility issues

### Steps to reproduce the behavior

Click upgrade when upgrading via a Softaculous package installer

### Attached files

![Screenshot 2022-03-25 113321](https://user-images.githubusercontent.com/4792542/160094614-0a745c66-e08e-4490-a877-17ed544fa5ad.jpg)

**Comment by priojk** [comment]
I think Dolibarr v15 is still not fully ready for php 8 yet.

**Comment by akhalz** [comment]
I still cannot upgrade to version 15.01 and i tried to upgrade to 15.02.
It looks like a simple incorrect minimum requirements restriction on Softaculous.
Where are those set? via dolibarr or softaculous?

**Comment by priojk** [comment]
Regardless of 15.0.1 or 15.0.2: php8.0+ is no supported. First version to support php8.0 is v16 (not published yet).

Furthermore, Softaculous is known to be problematic for installations. The recommended ways for installing Dolibarr are described in wiki.dolibarr.org.

**Comment by ksar-ksar** [comment]
You need to contact Softaculous for that.

I have tried to correct the installer without success for the moment : https://www.softaculous.com/board/index.php?tid=18694&tpg=1#p55570
