### ISSUE TITLE
v15.0.1 - EXPERIMENTAL Recruitment - Missing a Column in Database

### ISSUE THREAD

**Issue by warnerbryce** [Dolibarr/dolibarr#20464]
### Bug

With a fresh install of Dolibarr 15.0.1 with an empty database, 
Activating the Experimental Module Recruitment
Going to HRM then New Job Position 
You will get an error on Establishment : 
Latest database access request error: SELECT t.rowid, t.ref,t.label FROM llx_establishment as t WHERE 1=1 AND t.entity IN (1) ORDER BY t.ref ASC, t.label ASC
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 't.label' in 'field list'

Creating a Column like this in Database will correct this error : 
ALTER TABLE llx_establishment ADD label VARCHAR(150);

### Environment Version

15.0.1

### Environment Database

MariaDB 10.3

### Expected and actual behavior

When activating the Module, all tables must be created completely

**Comment by cfoellmann** [comment]
@warnerbryce I am in the progress of fixing the module.
Is your select field properly filled with the existing establishments on the form after your "hotfix"?
For me it does not produce the error but the field is still without data.

**Comment by warnerbryce** [comment]
Wierd
Something might changed since the 15.0.1, i dig into i m with my mobile. 

For me in 15.0.1 i took the same parameters than the label establishment i think. 
creating the field gave me access to a working module, without blank establishment
