### ISSUE TITLE
Recruitment Module : warning

### ISSUE THREAD

**Issue by cabinetdsi** [Dolibarr/dolibarr#20470]
### Bug

When we click on an item of recruitment, we have 2 warnings :
- Warning: file_exists(): open_basedir restriction in effect..../recruitmentcandidature_card.php on line 55
- Warning: file_exists(): open_basedir restriction in effect..../recruitmentcandidature_card.php on line 58

### Environment Version

15.0.1

### Environment OS

Linux Debian 5.10.92-1

### Environment Web server

Apache 2.4.25 (LWS environnement mutualisé)

### Environment PHP

7.4.27

### Environment Database

MariaDB 5.5.5-10.3.31

### Expected and actual behavior

no warning

I think there is a problem with the path

**Comment by cfoellmann** [comment]
please try to confirm that all dolibarr files in `htdocs` are where they are supposed to be!

**Comment by cfoellmann** [comment]
@cabinetdsi can you test again? It seems to be an issue with the files on your system.
If so we should close this.
