### ISSUE TITLE
Upgrading from 14.0.4 to 15.0.1 fails with postgresql

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#20476]
I'm trying to migrate to 15.0.1 and get the following database migration error: 

**DB_ERROR_42804: ALTER TABLE llx_product_fournisseur_price MODIFY COLUMN packaging real DEFAULT NULL;ERROR:  42804: column "packaging" cannot be cast automatically to type real HINT:  You might need to specify "USING packaging::real". LOCATION:  ATPrepAlterColumnType, tablecmds.c:9840**

 **DB_ERROR_42804: ALTER TABLE llx_ticket MODIFY COLUMN progress integer;ERROR:  42804: column "progress" cannot be cast automatically to type integer HINT:  You might need to specify "USING progress::integer". LOCATION:  ATPrepAlterColumnType, tablecmds.c:9840**

**Comment by smyds** [comment]
I'm having the same issue.

**Comment by matll42** [comment]
In your `htdocs/install/mysql/migration/14.0.0-15.0.0.sql`, you must change this line :
```
ALTER TABLE llx_product_fournisseur_price MODIFY COLUMN packaging real DEFAULT NULL;
```
to this line
```
ALTER TABLE llx_product_fournisseur_price MODIFY COLUMN packaging real DEFAULT NULL USING packaging::real;
```
