### ISSUE TITLE
V15.0 Error when upload file with tradintional chinese name file

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#20471]
### Bug

When upload the photo or other related file to product , proposal ,order .... etc , will show error message like " Error Duplicate entry 'propale/(PROV2854)-.png-1' for key 'uk_ecm_files' " .

And if you upload with enginlish name is ok .
If update with enginlish name then change it to chinese name , it will the error and you can't change the name back to enginlish  or delete it .

### Environment Version

15.0.0

### Environment OS

Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64

### Environment Web server

Apache/2.4.38 (Debian)

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.3.31

### Environment URL(s)

/comm/propal/document.php

### Expected and actual behavior

No error show up as v 14.0.3 .

### Steps to reproduce the behavior

In any module then try to upload the chinese name file .

### Attached files

![image](https://user-images.githubusercontent.com/78349579/160225705-4df1133e-362a-43e7-bd91-7fb4cc935768.png)

**Comment by erikvanberkum** [comment]
This is also true for Japanese language. This is not only related to version 15 other versions have this as well. Wondering if this is a bug or a feature request.

**Comment by trekmorris** [comment]
Hi

I think this is a bug , because when i am not to upgrade to v15 , it is ok for upload traditional chinease name file .
And i have two different host system , in winodws host has this issue before until now ( i have installed v 14.0.3 in windows host , same as in linux host . ) .
But never happened this in linux host .

**Comment by trekmorris** [comment]
Hi 

I have confirmed this issue be fixed in v 15.0.1 .
