### ISSUE TITLE
Translation problem on bank details "kontrollsumma" for Swedish

### ISSUE THREAD

**Issue by wutanggg** [Dolibarr/dolibarr#20479]
### Bug

When generating order or billing PDFs using Swedish translation, the "checksum" field at the bottom of the PDF is translating as "kontrollsum ma" with a line break, the "ma" part covers the actual checksum.
Swedish translation string appears too long for the space.

Possible other solution is to remove French RIB style details altogether on foreign language translations and leave only IBAN+BIC details ?

### Environment Version

15.x

### Environment OS

Linux

### Expected and actual behavior

Field "kontrollsumma" should not be wrapping as "kontrollsum ma"

### Steps to reproduce the behavior

Generate any PDF in Swedish language with French bank details.

**Comment by dolibit-ut** [comment]
Can you maybe add a screenshot?

**Comment by wutanggg** [comment]
Below is a screenshot of the problem.
This happened before back in v9 or v10, also with Swedish language PDFs.

<img width="1734" alt="Screenshot 2022-04-01 at 11 37 37" src="https://user-images.githubusercontent.com/46397696/161238655-49a5c66a-1941-4ff9-955a-c7bd3aba9914.png">
