### ISSUE TITLE
V15.0.1 - No display of Compute Field in Complementary attributes (lines) Invoice ODT

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#20474]
### Bug

Greetings,

I am facing a strange issue of only particular fields doesnot appear if we use computational field in complementary attributes(lines) of Invoices:

Please refer to below picture:

![image](https://user-images.githubusercontent.com/85006729/160282862-75973cfb-678b-47c0-ac4c-bc8dac829bc5.png)

The same formula WORKS FINE with other parameters. Like few examples given below:

(($reloadedobj = new Facture($db)) && ($reloadedobj->fetchNoCompute($obj->id:(($obj->rowid ? $obj->rowid: $object->id)) > 0)) ? $reloadedobj → ref: ‘-1’
(($reloadedobj = new Facture($db)) && ($reloadedobj->fetchNoCompute($obj->id:(($obj->rowid ? $obj->rowid: $object->id)) > 0)) ? $reloadedobj → total_ht: ‘-1’
(($reloadedobj = new Facture($db)) && ($reloadedobj->fetchNoCompute($obj->id:(($obj->rowid ? $obj->rowid: $object->id)) > 0)) ? $reloadedobj → total_ttc: ‘-1’

Surprisingly, nothing appear if we use localtax1 and/or localtax2 on the PDF when called thru custom field. I have already enabled local tax in setup as well. Thats is:

(($reloadedobj = new Facture($db)) && ($reloadedobj->fetchNoCompute($obj->id:(($obj->rowid ? $obj->rowid: $object->id)) > 0)) ? $reloadedobj → localtax1: ‘-1’
or

(($reloadedobj = new Facture($db)) && ($reloadedobj->fetchNoCompute($obj->id:(($obj->rowid ? $obj->rowid: $object->id)) > 0)) ? $reloadedobj → localtax2: ‘-1’
GIVES ONLY BLANK OUTPUT

Can anyone help how to display localtax1 and localtax2 on PDF generated through ODT

thanks
yesbee

### Environment Version

15.0.1

### Environment OS

Linux Ubuntu 18.0.4

### Environment Web server

Apache 2.4

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

/compta/facture/admin/facturedet_cust_extrafields.php

### Expected and actual behavior

Expected behavior : Just like other fields, localtax1 and localtax2 should be displayed in the invoice line item
Actual behavior : Except localtax1 and localtax2, other db fields are displayed with the same code.

### Steps to reproduce the behavior

1. Enable local taxes in the company setup
2. create a computational field as specified in the below picture:
![image](https://user-images.githubusercontent.com/85006729/160282990-062cfd33-f950-4939-8ae6-27017c1764ba.png)
3. check in the invoice link whether the field is displayed 
4. check in the Generate button to generate invoice from the ODT after incorporating it into a test ODT file calling the line_options parameter.

**Comment by ksar-ksar** [comment]
Hello,

Are you sure that localtax1 and 2 exist on Facture object?

**Comment by riseval** [comment]
Dear Ksar,

Many thanks for the reply.

Basically, the facture object consists of all fields of llx_facture table and below are the fields of it.  Except localtax1 and localtax2 others are fetched and displayed correctly.

+-------------------------------------+--------------+------+-----+-------------------+-----------------------------+
| Field                                                | Type              | Null   | Key |        Default           |            Extra                       |
+-------------------------------------+--------------+------+-----+-------------------+-----------------------------+
| rowid                                               | int(11)      | NO   | PRI | NULL              | auto_increment              |
| ref                                                    | varchar(30)  | NO   | MUL | NULL              |                             |
| entity                                               | int(11)      | NO   |     | 1                 |                             |
| ref_ext                                              | varchar(255) | YES  |     | NULL              |                             |
| ref_int                                              | varchar(255) | YES  |     | NULL              |                             |
| ref_client                          | varchar(255) | YES  |     | NULL              |                             |
| type                                | smallint(6)  | NO   |     | 0                 |                             |
| fk_soc                              | int(11)      | NO   | MUL | NULL              |                             |
| datec                               | datetime     | YES  |     | NULL              |                             |
| datef                               | date         | YES  |     | NULL              |                             |
| date_pointoftax                     | date         | YES  |     | NULL              |                             |
| date_valid                          | datetime     | YES  |     | NULL              |                             |
| tms                                 | timestamp    | NO   |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
| date_closing                        | datetime     | YES  |     | NULL              |                             |
| paye                                | smallint(6)  | NO   |     | 0                 |                             |
| remise_percent                      | double       | YES  |     | 0                 |                             |
| remise_absolue                      | double       | YES  |     | 0                 |                             |
| remise                              | double       | YES  |     | 0                 |                             |
| close_code                          | varchar(16)  | YES  |     | NULL              |                             |
| close_note                          | varchar(128) | YES  |     | NULL              |                             |
| total_tva                           | double(24,8) | YES  |     | 0.00000000        |                             |
| localtax1                           | double(24,8) | YES  |     | 0.00000000        |                             |
| localtax2                           | double(24,8) | YES  |     | 0.00000000        |                             |
| revenuestamp                        | double(24,8) | YES  |     | 0.00000000        |                             |
| total_ht                            | double(24,8) | YES  |     | 0.00000000        |                             |
| total_ttc                           | double(24,8) | YES  |     | 0.00000000        |                             |
| fk_statut                           | smallint(6)  | NO   | MUL | 0                 |                             |
| fk_user_author                      | int(11)      | YES  | MUL | NULL              |                             |
| fk_user_modif                       | int(11)      | YES  |     | NULL              |                             |
| fk_user_valid                       | int(11)      | YES  | MUL | NULL              |                             |
| fk_user_closing                     | int(11)      | YES  |     | NULL              |                             |
| module_source                       | varchar(32)  | YES  |     | NULL              |                             |
| pos_source                          | varchar(32)  | YES  |     | NULL              |                             |
| fk_fac_rec_source                   | int(11)      | YES  |     | NULL              |                             |
| fk_facture_source                   | int(11)      | YES  | MUL | NULL              |                             |
| fk_projet                           | int(11)      | YES  | MUL | NULL              |                             |
| increment                           | varchar(10)  | YES  |     | NULL              |                             |
| fk_account                          | int(11)      | YES  | MUL | NULL              |                             |
| fk_currency                         | varchar(3)   | YES  | MUL | NULL              |                             |
| fk_cond_reglement                   | int(11)      | NO   |     | 1                 |                             |
| fk_mode_reglement                   | int(11)      | YES  |     | NULL              |                             |
| date_lim_reglement                  | date         | YES  |     | NULL              |                             |
| note_private                        | text         | YES  |     | NULL              |                             |
| note_public                         | text         | YES  |     | NULL              |                             |
| model_pdf                           | varchar(255) | YES  |     | NULL              |                             |
| last_main_doc                       | varchar(255) | YES  |     | NULL              |                             |
| fk_incoterms                        | int(11)      | YES  |     | NULL              |                             |
| location_incoterms                  | varchar(255) | YES  |     | NULL              |                             |
| fk_transport_mode                   | int(11)      | YES  |     | NULL              |                             |
| situation_cycle_ref                 | smallint(6)  | YES  |     | NULL              |                             |
| situation_counter                   | smallint(6)  | YES  |     | NULL              |                             |
| situation_final                     | smallint(6)  | YES  |     | NULL              |                             |
| retained_warranty                   | double       | YES  |     | NULL              |                             |
| retained_warranty_date_limit        | date         | YES  |     | NULL              |                             |
| retained_warranty_fk_cond_reglement | int(11)      | YES  |     | NULL              |                             |
| import_key                          | varchar(14)  | YES  |     | NULL              |                             |
| extraparams                         | varchar(255) | YES  |     | NULL              |                             |
| fk_multicurrency                    | int(11)      | YES  |     | NULL              |                             |
| multicurrency_code                  | varchar(3)   | YES  |     | NULL              |                             |
| multicurrency_tx                    | double(24,8) | YES  |     | 1.00000000        |                             |
| multicurrency_total_ht              | double(24,8) | YES  |     | 0.00000000        |                             |
| multicurrency_total_tva             | double(24,8) | YES  |     | 0.00000000        |                             |
| multicurrency_total_ttc             | double(24,8) | YES  |     | 0.00000000        |                             |
+-------------------------------------+--------------+------+-----+-------------------+-----------------------------+

regards,
yesbee

**Comment by ksar-ksar** [comment]
Hello,

What you have posted is Database, not PHP object fields.
