### ISSUE TITLE
Multi-level Prices not updating in V15.0.0 and V15.0.1

### ISSUE THREAD

**Issue by biosk4hvd** [Dolibarr/dolibarr#20480]
### Bug

When I enable Multi-Level prices, I cannot update the prices on any product.

The page for updating the prices opens, I type in the new prices, click on Save, I even get a Message saying that the new prices have been saved. But the prices stay the same.  I tried for different products, different services, it is all the same.

If i turn off the multi-price level, i can then update the price normally.

This issue started when i updated from 14.0.6 to 15.0.0 and continued with the update to 15.0.1.

![Screenshot 2022-03-29 111400](https://user-images.githubusercontent.com/102580952/160565554-5f36e9e3-b636-4e91-8257-7200eb769d5d.jpg)

![Screenshot 2022-03-29 111335](https://user-images.githubusercontent.com/102580952/160565545-5a7aa95b-4f15-4b86-8fc4-029c84b4b3e4.jpg)

### Environment Version

15.0.0 AND 15.0.1

### Environment Web server

Apache 2.4.53

### Environment PHP

7.4.28

### Environment Database

MySQL 5.6.41-84.1

### Environment URL(s)

www.group-four.com/dolitest

**Comment by toni-mx** [comment]
Hi, 
First of all don't take my answer as final as I'm not an expert. We had the same problem, the issue we locate is related to PHP version. We used 5.x.xx and after updating to 7.4.29 it solved automatically, no other change was made. Maybe you can try.

Our dolibarr version is 14.0.5

Regards
