### ISSUE TITLE
error from email file from list

### ISSUE THREAD

**Issue by xheronimo** [Dolibarr/dolibarr#20499]
### Bug

Gives an undefined function error when sending file by mail from the list at least propal
to url
/dolibarr/comm/propal/list.php

This error report is:
fatal error: Uncaught Error: Call to undefined function getOnlineSignatureUrl() in C:\dolibarr\www\dolibarr\htdocs\core\lib\functions.lib.php:7273 Stack trace: #0 C:\dolibarr\www\dolibarr\htdocs\core\actions_massactions.inc.php(418): getCommonSubstitutionArray(Object(Translate), 0, NULL, Object(Propal)) #1 C:\dolibarr\www\dolibarr\htdocs\comm\propal\list.php(343): include('C:\\dolibarr\\www...') #2 {main} thrown in C:\dolibarr\www\dolibarr\htdocs\core\lib\functions.lib.php on line 7273

To correct this bug you have to include this line at the beginning of the file

core\lib\functions.lib.php on line in fi
include_once DOL_DOCUMENT_ROOT.'/core/lib/signature.lib.php';

### Environment Version

15.0.1

### Environment OS

windows and linux

**Comment by ksar-ksar** [comment]
FIX is here #20610
