### ISSUE TITLE
Add sale representative in invoice list error

### ISSUE THREAD

**Issue by xusdeejay** [Dolibarr/dolibarr#20496]
### Bug

In the list of invoices, when choosing to display the commercial field of the third party (sale_representative), it crashes the list.

### Environment Version

15.0.0,15.0.1

### Environment OS

Linux Ubuntu

### Environment Web server

Apache

### Environment PHP

7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0ubuntu0.20.04.1

### Environment URL(s)

dolibarr/compta/facture/list.php?leftmenu=customers_bills

### Expected and actual behavior

It crashes the list.

### Steps to reproduce the behavior

choose to display the commercial field of the third party (SaleRepresentativesOfThirdParty)

**Comment by xusdeejay** [comment]
Solution for us:
Change line 
$listsalesrepresentatives = $thirdpartystatic->getSalesRepresentatives($user);
for:
$listsalesrepresentatives = $companystatic->getSalesRepresentatives($user);

Thanks

**Comment by hregis** [comment]
Hello @xusdeejay 
it's fixed for the next release https://github.com/Dolibarr/dolibarr/pull/20490
