### ISSUE TITLE
Intervention validate button greyed

### ISSUE THREAD

**Issue by l0d0v1c** [Dolibarr/dolibarr#20502]
### Bug

After updating to 15.0.1, the **validate** button of card.php remains disabled. It is possible to force the normal behaviour by appending the url by 

`...fichinter/card.php?id=...&action=validate `

### Environment Version

15.0.1

### Environment OS

centos

### Environment Web server

nginx

### Environment PHP

7.1

### Environment Database

sql

**Comment by ksar-ksar** [comment]
Hello,

I can't reproduce.

Do you have check the user rights ?
Do you use the advanced permissions ?

Can you try to disable/enable the module ?

**Comment by atm-arnaud** [comment]
@l0d0v1c we need more informations to help you

**Comment by l0d0v1c** [comment]
Hello !
Yes I checked user rights (that didn't changed after update)
No advanced permissions
**Disable/enable the module fixed the issue**

Thank you and sorry for not having thought about that
