### ISSUE TITLE
Fatal error: Uncaught Error: Class 'DolibarrApi' not found in

### ISSUE THREAD

**Issue by kwk9892** [Dolibarr/dolibarr#20503]
### Bug

Hi, i am trying to import `Contacts` class in `/societe/class/api_contacts.class.php`

This is my code `require_once DOL_DOCUMENT_ROOT."/societe/class/api_contacts.class.php";`

Code that triggers error:

`
$obj = new Contacts();
$contacts = $obj->index();
foreach($contacts as $contact) {
	var_dump($contact->mobile_number);
}
`

### Environment Version

15.0.0

### Environment OS

Windows 10

### Environment Web server

Apache 

### Environment PHP

7.4

### Environment Database

mysql

### Expected and actual behavior

Able to import `Contacts` class and use `Contacts.index()`

### Steps to reproduce the behavior

`
$obj = new Contacts();
$contacts = $obj->index();
foreach($contacts as $contact) {
	var_dump($contact->mobile_number);
}
`

### Attached files

```
Fatal error: Uncaught Error: Class 'DolibarrApi' not found in C:\xampp\htdocs\15.0.0\societe\class\api_contacts.class.php:31 Stack trace: #0 C:\xampp\htdocs\15.0.0\custom\moceanapi\core\controllers\settings\bulk_sms.setting.php(4): require_once() #1 C:\xampp\htdocs\15.0.0\core\lib\functions.lib.php(937): include_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\15.0.0\custom\moceanapi\admin\bulk_sms.php(76): dol_include_once('/moceanapi/core...') #3 {main} thrown in C:\xampp\htdocs\15.0.0\societe\class\api_contacts.class.php on line 31
```

**Comment by ksar-ksar** [comment]
Hello,

You can't call `require_once DOL_DOCUMENT_ROOT."/societe/class/api_contacts.class.php";` like that.
You need before to call `/api/class/api.class.php`

Anyway, I don't understand what you are trying to achieve.
