### ISSUE TITLE
ADD - Type of contract

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#20515]
### Feature Request

Be able to manage types of contract like :
- [ ] Rental agreement
- [ ] Employment contract
- [ ] "Training agreement" contract
- [ ] etc.

### Use case

Be able to manage all types of contract and filter them by type of contract

### Suggested implementation

Add dictionnaire : 
Type de contract (Code, type de contract, label, title pdf)

- [ ] CONTRACT_HIDE_PLANNED_DATE_ON_PDF
- [ ] CONTRACT_HIDE_REAL_DATE_ON_PDF
- [ ] CONTRACT_HIDE_QTY_ON_PDF
- [ ] CONTRACT_HIDE_PRICE_ON_PDF

**Comment by dolibit-ut** [comment]
Nice idea.

A)  an additional Dictionary of Contract_Type  
or / and 
B)  Categories for Contracts


But some of your mentioned contract types are special and not really used with the contract (sales) module.
For employment contracts you should use HR module or special modules and for rental maybe to
(look at DoliStore) and for Training and Rental you can maybe also use combination with projects.

**Comment by isamuse2** [comment]
Very helpful feature as suggested by lmag in order to link any contract with clients, suppliers, employees.

Indeed, contacts as defined in Dolibarr, are limited to subscriptions of services to be renewed which is limiting and not conform to the management of an enterprise.
