### ISSUE TITLE
PDF Download link in Purchase Order does not work

### ISSUE THREAD

**Issue by uvigii** [Dolibarr/dolibarr#20524]
### Bug

Trying to download the attached pdf in Purchase Order produces error on client side:
```
This site can’t be reached. The webpage at https://*****/document.php?modulepart=commande_fournisseur&file=PO2204-0002%2FPO2204-0002.pdf&entity=1 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```
Traced down the problem to 
[/douments.php
](https://github.com/Dolibarr/dolibarr/blob/15.0/htdocs/document.php#L322)

Changing that line with:
`$fp = fopen($fullpath_original_file_osencoded, 'rb');
        fpassthru($fp);`
seems to fix the problem.

### Environment Version

15.0.1

### Environment OS

ubuntu 20.04

### Environment Web server

Apache 2.4

### Environment PHP

7.4

### Environment Database

mariadb 10.4

### Environment URL(s)

https://*****/document.php

### Expected and actual behavior

Clicking the download link should trigger the file download.

### Steps to reproduce the behavior

Click on the linked files below Order.

**Comment by priojk** [comment]
I tried with 15.0.1 and could download the pdf without problems. - So there seems to be an additional yet unknown error condition.

**Comment by uvigii** [comment]
Tracing it down:
It seems that there are at least 3 different DW modes.

```
Nothihg
MAIN_FORCE_READFILE_WITH_FREAD
MAIN_FORCE_READFILE_WITH_STREAM_COPY
```


Setting MAIN_FORCE_READFILE_WITH_FREAD to 1 seems to fix the problem for me.
Thanks.
