### ISSUE TITLE
PUBLIC API

### ISSUE THREAD

**Issue by pratushraj** [Dolibarr/dolibarr#20546]
### Feature Request

No public API is available. Please implement the public API for a Ticket reply.

### Use case

I am facing the problem while I'm sending the reply/message with the help of ticket API, (Sending the request from my front end) with Public tracking no. and message. We can't define who is users, are because here we are accessing this API via DOLAPIKEY that s why it is not defining the users. So, it'll be better if one public API is added for creating, updating, deleting, and view for tickets.

**Comment by dolibit-ut** [comment]
I do not understand - but do you wish that anybody can read or delete all your tickets ???

**Comment by pratushraj** [comment]
No. When I submit the new message via REST API with tracking_id and message. I'm unable to define whether this message is from the customer side or the staff side. So my question is how I know which message is related to which side whether the message is sent from the customer side or staff side.

**Comment by dolibit-ut** [comment]
For staff side you have to add  "fk_user_create" 
and for customer side you add  "origin_email"

**Comment by pratushraj** [comment]
Not working. I'm sending a new message in the ticket with the tracking_id via REST API.

![image](https://user-images.githubusercontent.com/82569386/162118894-7b2072e5-b958-4322-aac8-70067bf2978c.png)
You can see the parameters in the above image. The problem is that this API is that this message is from the staff side, not the customer side.

![image](https://user-images.githubusercontent.com/82569386/162119429-1ec6707b-5d84-47ce-ad8f-36349c4c617e.png)

you can see the message threads in the image.
I want to add the message from the customer side via REST API, How can I do that?

**Comment by AlbanDurrheimer** [comment]
Hello,
I have the same problematic. I would like to be able to create a ticket from the API without it being assigned to a user, but only to `origin_email`.
