### ISSUE TITLE
New EU VAT rules (07/2021) for e-commerce

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#20554]
### Feature Request

There is new VAT rules in europe since 07/2021, here is a link in french :

https://www.douane.gouv.fr/actualites/professionnels-1er-juillet-2021-entree-en-vigueur-du-paquet-tva-e-commerce

### Use case

Invoice from ETSY (irland supplier with VAT number IE9777587C) AND product with VAT rate 20% because buyer is french :-)

With dolibarr i can't create that supplier invoice : dolibarr VAT rates dropdown allow only '0', '4.8', '9', '13.5' and '23'% values ...

![image](https://user-images.githubusercontent.com/1468823/161841681-e8dbdfdc-5748-4124-88ad-2f8678a52d1e.png)

**Comment by dolibit-ut** [comment]
Maybe i don't understand complete your problem - 
but i think you only have to add the VAT/TVA Rate to Ireland in Dictionaries.

**Comment by rycks** [comment]
Hello @dolibit-ut , thanks for that idea, it could be a "solution for one or two users / suppliers" but we can't explain to each dolibarr users that they can't make supplier invoices if they don't manually add their own vat rate each time a new european supplier apply that new rules !
That new european rules is global.
Here is some more informations in all european languages (just change _en at the end of the URI or click on english flag on the top of the page) https://ec.europa.eu/taxation_customs/ioss_en

**Comment by dolibit-ut** [comment]
Maybe we add for every EEC Country this VAT rate as fast solution?

Another way seems a bit more complicated (to me) - we have VAT rates based on countries.
