### ISSUE TITLE
Stock movements for manufacturing orders, receptions and shipments do not create links to the appropriate document in 15.0.1

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#20563]
### Bug

Origin column for stock movements relating to receptions and shipments is blank

### Environment Version

15.0.1

### Environment OS

Linux debian 4.19.0-19-amd64 #1 SMP Debian 4.19.232-1 (2022-03-07) x86_64

### Environment Web server

Apache 2.4.53 (Unix)

### Environment PHP

7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB

### Environment URL(s)

/product/stock/movement_list.php

### Expected and actual behavior

 Now, this does not happen any more.

#### Expected
It used to be that when you receive an item from the supplier and enter it into stock, or when you you shipped an item to a customer, the corresponding document would be linked to the stock movement, in the "Origin" column in /product/stock/movement_list.php 
#### Actual behaviour
For at least Manufacturing orders, Receptions (/reception/card.php) and Shipments (/expedition/card.php) the field "Origin" is blank. Actual document name is still present in "Label of movement".

### Steps to reproduce the behavior

Create a stock movement via Manufacturing Order, Shipment or Reception

### Attached files

![Stock Movements](https://user-images.githubusercontent.com/55888212/161957766-1c8df20c-98c1-4a0f-83a1-aca795cb4d50.png)

**Comment by ToniTen** [comment]
This used to work as expected in version up to 14.0.5

**Comment by fappels** [comment]
Fixed here: https://github.com/Dolibarr/dolibarr/pull/20431

**Comment by ToniTen** [comment]
Thanks @fappels . I see that 15.0.1 shipped just before that commit landed. I guess I will have to either patch it myself, or wait until 15.0.2 I don't like patching live installs though (and well, this was only noticed after I upgraded my production install to 15.0.1 (from 14.0.5).

Still, given that the fix is already in, I'm closing this bug report. Thanks for the hard work.
