### ISSUE TITLE
Product price per customer

### ISSUE THREAD

**Issue by gmeles** [Dolibarr/dolibarr#20567]
### Bug

On products module you can enable to set different product prices per customer, but when you try to add a new product price per customer you get "Security token has expired, so action has been canceled". 

### Environment Version

15.0.2

### Environment OS

Ubuntu 20.04 LTS

### Environment Web server

Apache

### Environment PHP

7.4.3

### Environment Database

MariaDB 8.0.28-0ubuntu0.20.04.3

### Steps to reproduce the behavior

Just try to add a product price per customer

**Comment by ksar-ksar** [comment]
Did you get any external modules?

**Comment by gmeles** [comment]
No external modules. The weird is that if you go from customer to assign a price it works fine. The problem comes when you are at products page and you need to assign a price per customer there. For the time being I use the above workaround. But it is definitely a bug [[img](https://ibb.co/Hr8yfD4)]

**Comment by ksar-ksar** [comment]
Hello,

The FIX is here : https://github.com/Dolibarr/dolibarr/commit/afdefad55b998f1b040b108715d2f445c6e02833

Will be in the next V15.0.2 release.
