### ISSUE TITLE
List, massaction to update extrafields

### ISSUE THREAD

**Issue by atm-arnaud** [Dolibarr/dolibarr#20560]
### Feature Request

On dolibarr list, i need to update every choosen lines extrafields. I need a screen with all extrafields loaded to update 1 or more extrafields.

### Use case

I added comment and color (selllist) in task extrafields
I'm on task list, i check TK001, TK002, TK003. i click on massaction "change extrafields"
in this screen i empty comment area and pick red in color list.
I click in save/update

TK001, TK002 and TK003 have been updated with a blank data in comment and red in color

### Suggested implementation

Add this code into modulebuilder and tasklist

### Suggested steps

Try on a simple list
Add into modulebuilder
Add into others lists

**Comment by atm-maxime** [comment]
I think that adding a massaction to update all extrafields at once will result in an uggly UI for a little use cases. Allowing to update extrafields one by one seems better to me.

- Select elements in an element list (i.e. tasks)
- Choose massaction "Update extrafield"
- Select the concerned extrafield
- Input the value
- Press update
