### ISSUE TITLE
Display of physical and virtual stocks with decimals

### ISSUE THREAD

**Issue by EpixFr** [Dolibarr/dolibarr#20588]
### Bug

In the product list page, the table views physical and virtual stocks with decimals.

The bug is on /product/list.php 

Line 1705 :
 print price(price2num($product_static->stock_reel, 'MS'));  -> print $product_static->stock_reel;

Line 1719 : 
print price(price2num($product_static->stock_theorique, 'MS')); -> print $product_static->stock_theorique;

### Environment Version

Dolibarr 15.0.2

### Environment OS

Ubuntu 20.04

### Environment Web server

Apache 2.4

### Environment PHP

7.4.20

### Environment Database

MariaDB 10.3

### Environment URL(s)

/product/list.php 

### Attached files

The bug is on /product/list.php 

Line 1705 :
 print price(price2num($product_static->stock_reel, 'MS'));  -> print $product_static->stock_reel;

Line 1719 : 
print price(price2num($product_static->stock_theorique, 'MS')); -> print $product_static->stock_theorique;

**Comment by atm-maxime** [comment]
Thanks for reporting.
I don't quite understand what your issue is. A stock value can be with decimals. Can you add a screenshot showing the issue ?

**Comment by EpixFr** [comment]
Thank you for your reply,
Can you explain to me how can we have a stock with decimals ?
