### ISSUE TITLE
V15.01 Invoices edition bug

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#20589]
### Bug

This site can’t be reachedcrm.tadit-services.com took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT

### Environment Version

Dolibar 15.0.1

### Environment OS

Linux shared hosting

### Environment Web server

LAMP

### Environment PHP

7.4

### Environment Database

5.6

### Expected and actual behavior

Wen editing any invoice in costumer account at a certain time the software bug with
This site can’t be reachedcrm.tadit-services.com took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT

**Comment by ksar-ksar** [comment]
Hello,

This is not a Dolibarr bug, the problem is most probably on the infrastructure.
Have a look at the infrastructure logs.

**Comment by DATUC** [comment]
Hi @ksar-ksar 
I also tink the same but after looking all around i did not foun any problem i have even revert back on 14.5 everytng is ok but wen upgrade back the problem is ther
