### ISSUE TITLE
Bug: Text formatting in Notes not possible

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#20580]
In the Note fields (Note publique and Note privée) when making a price proposal, it was earlier possible to format the text. With 15.0.0 and 15.0.1 the text formatter is gone. It is possible to write code like this `<h1>Test</h1>`  but I would like to have back the text formatter as earlier.

# Bug
[*Short description*]

## Environment
- **Version**: 15.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.33-1+0~20211119.91+debian10~1.gbp618351
- **Database**: MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0+deb10u1
- **URL(s)**: /azert/comm/propal/note.php?action=editnote_public&token=cc05b770c6a3b7d4ecf6c4d5f016b9d8&id=838

**Comment by ksar-ksar** [comment]
Have a look on #20289 

Need the editor module activation

**Comment by hasse-basse** [comment]
Thanks, it's fine now, but why does it change settings?
