### ISSUE TITLE
Impossible to upload a document for an order from REST API

### ISSUE THREAD

**Issue by guiguez38** [Dolibarr/dolibarr#20597]
### Bug

It's impossible to upload a document for an order from API REST because it's not implemented in /htdocs/api/class/api_documents.class.php.

You just need to add line in post method:

`elseif ($modulepart == 'order' || $modulepart == 'commande') 
{
     $modulepart = 'commande';
     require_once DOL_DOCUMENT_ROOT.'/commande/class/commande.class.php';
     $object = new Commande($this->db);
}
`

### Environment Version

15.1

**Comment by emheyarssi** [comment]
Related with #20558?

**Comment by homer8173** [comment]
Fixed in dol 15.0.2

**Comment by homer8173** [comment]
update your dolibarr
