### ISSUE TITLE
Keep product label on detail of element

### ISSUE THREAD

**Issue by defrance** [Dolibarr/dolibarr#20596]
### Feature Request

follow the close of an precedent pull

https://github.com/Dolibarr/dolibarr/pull/14997

on some element the product label is not keep on detail line of order, we use continually the label of the product table.
Logicaly we must keep the label of the product when we produce by example a bill else the original pdf must be altered after hos who is not permit 

### Use case

create a bill 
pay it, normaly we don't have the right then to change anything on it after
change the label of a product present on the bill and return on
generate a pdf and the label is changed...

### Suggested implementation

I precise the rule are not the same on all element and generate some error for thansfert between element (order to bill)

### Suggested steps

need to define precise rules on usage of label on element

**Comment by dolibit-ut** [comment]
Hello @defrance

yes thank you, i think this is almost a general problem in dolibarr.

We need to distinguish between changes to master data (products / tiers) 
that take effect everywhere afterwards and those that may not be changed afterwards.

Actually we should record the changes on master data (a history table)
and once a document has been set to a defined state, subsequent changes may no longer change these documents.

(And (printed) documents can not longer be changed (or only with historical records).)
