### ISSUE TITLE
Create Draft Invoice when Classify Delivered 

### ISSUE THREAD

**Issue by Mohamedali1880** [Dolibarr/dolibarr#20599]
### Bug

After Updating to 15.0.1 when made order "Delivered" by Pressing Classify Delivered its create draft invoice even if order had invoice 
please check 

### Environment Version

15.0.1

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

 7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.6.7-MariaDB

**Comment by BebZ** [comment]
Hello 

You can share your solution ? was it hidden option ? 
I noticed you have no shipment on your order, it creates invoice from order, not from shipment.
