### ISSUE TITLE
__USER_FULLNAME__ not Working with Default values (to use on forms)

### ISSUE THREAD

**Issue by ThcDelux3** [Dolibarr/dolibarr#20601]
### Bug

When adding an "Default values (to use on forms)" The constant __USER_FULLNAME__ is not working. The constant __USER_ID__ works fine.

### Environment Version

15.0.1

### Environment OS

Windows

### Environment Web server

Apache

### Environment PHP

7.4.26

### Environment Database

MySQL

### Expected and actual behavior

When adding an "Default values (to use on forms)" The constant __USER_FULLNAME__ is not working. The constant __USER_ID__ works fine.

__USER_FULLNAME__ shows Nothing
__USER_ID__  shows the expected ID of the user

### Steps to reproduce the behavior

1.) New Dolibarr Installation 
2.) Go to "Default values/filters/sorting" / "Default values (to use on forms)"
- url: comm/propal/card.php
- field: options_refuser
- value: __USER_ID__ 

4.) Go to the Module  / Complementary attributes
3.) Add a new Field
- Label or translation key: Unser Zeichen
- Attribute code: refuser
- Type: String
- Size: 255
- Required: true

### Attached files
![image](https://user-images.githubusercontent.com/25651512/162638069-8e1133a8-d6c3-4f57-b2c4-6971e42868da.png)
As you can see the Customfield is added but is has not the expected value.
_No response_

**Comment by ThcDelux3** [comment]
These is a list of working constants for me:

__USER_ID__
__DAY__ 
__YEAR__ 
__PREVIOUS_DAY__ 
__PREVIOUS_YEAR__ 
__PREVIOUS_MONTH__
__NEXT_DAY__ 
__NEXT_MONTH__ 
__NEXT_YEAR__

**Comment by IC-Mathieu** [comment]
replace comm/propal/card.php by societe/card.php its works for me
