### ISSUE TITLE
v14.0.3 and v15.0.1 User can change his own permission when disable  modify its own permission

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#20616]
### Bug

When enable permission " Create/modify internal/external users and permissions " , then user can change his own permission even disable " Modify its own permissions (Permision available in Advanced permission mode only) " .

![image](https://user-images.githubusercontent.com/78349579/162996089-c4d5edfd-bfe3-45a4-8c96-e9cbcbbf54e1.png)

### Environment Version

v 14.0.3 and v15.0.1

### Environment OS

Deian 10 windows 7

### Environment Web server

 Apache/2.4.38 Apache/2.4.41 

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.4.1

### Environment URL(s)

/user/group/perms.php?id=8&action=addrights&entity=1&rights=253&confirm=yes

### Expected and actual behavior

When disable " Modify its own permissions (Permision available in Advanced permission mode only) " , then user should can't modify his own permission even he has enable permission " Create/modify internal/external users and permissions " .

### Steps to reproduce the behavior

Create a user and enable advanced permission mode .
Then give user permission " Create/modify internal/external users and permissions  " and login with that user to test .

**Comment by hregis** [comment]
hello @trekmorris 
I can't reproduce your problem.
I can modify the rights of other users, and the permission tab of the current user is hidden. 
On the other hand I can change the permissions of superadmin/admin, and that's a bug!

**Comment by hregis** [comment]
@trekmorris 
a user can not modify permissions of admins : https://github.com/Dolibarr/dolibarr/pull/20622

**Comment by trekmorris** [comment]
@hregis 

Hi 

If like what your situation , i will need to disable " Read its own permission " .
Or the user will see his own permission .
