### ISSUE TITLE
#bug warehouse pdf generation issue

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#20628]
Hi @ll actualy having an issue wen generating the warehouse contain PDF if the contain equand fill just in one page v=everyting is ok but wen it com to 2 pages the contain on the secong page is ot well positioned.
![image](https://user-images.githubusercontent.com/26550824/159672828-94ed1415-6e40-4de0-8f86-befe48254d1a.png)

_Originally posted by @DATUC in https://github.com/Dolibarr/dolibarr/issues/8604#issuecomment-1076171756_

**Comment by priojk** [comment]
In order to report bugs, it's helpful to use the template, which is provided by github. Without any information about your Dolibarr version and the used environment, it will probably be difficult to move forward with this issue.

**Comment by DATUC** [comment]
> In order to report bugs, it's helpful to use the template, which is provided by github. Without any information about your Dolibarr version and the used environment, it will probably be difficult to move forward with this issue.

Hi @priojk tks is just that i directly extract this from an other discution
