### ISSUE TITLE
field ref_customer in llx_expedition is not varchar(255)

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#20629]
### Bug

hi

the filed ref_client is varchar(255) in llx_commande
but ref_customer is varchar(30) in llx_expedition 
causing a sql error during expedition creation when ref_client is longer than 30.

example : https://www.dolibarr.fr/forum/t/impossible-de-creer-une-expedition/39846

### Environment Version

15.0.1 and before ?

**Comment by fappels** [comment]
It is for fresh install but not for migrated dolibarr because missing in migration sql.
