### ISSUE TITLE
startTime errors in the installation process

### ISSUE THREAD

**Issue by Zebedeu** [Dolibarr/dolibarr#20620]
### Bug

I found many errors related to the strftime function. I believe it's not a very high priority level and I'm willing to work on it.
What do you think about it?

### Environment Version

16.0.0

### Environment OS

MacOs Monterey 

### Environment Web server

Server version: Apache/2.4.51 (Unix) Server built:   Dec 17 2021 17:10:27

### Environment PHP

8.1.4

### Environment Database

MySql 8.0.28

### Environment URL(s)

occurs throughout the installation process

### Expected and actual behavior

In the installation process, it is expected that a clean and error-free installation will be done.

**Comment by hregis** [comment]
@Zebedeu 
and what is this errors ?

**Comment by Zebedeu** [comment]
@hregis 
<img width="1440" alt="Captura de ecrã 2022-04-12, às 21 09 07" src="https://user-images.githubusercontent.com/12781593/163045644-45d12e83-afee-4876-b87c-e3c611dfaf8f.png">

**Comment by hregis** [comment]
@Zebedeu 
you use php >= 8.1 ?
it's not recommanded ! for the moment !

**Comment by Zebedeu** [comment]
OK. Yes I use php 8.1
