### ISSUE TITLE
Third-Party cannot modify Customers tags/categories

### ISSUE THREAD

**Issue by zunami** [Dolibarr/dolibarr#20638]
### Bug

you can't change already recorded third-party "customers tags/categories" afterwards.

### Environment Version

14.0.5

### Environment OS

Proxmox / Debian 11 / Yunohost 5.13.19-6

### Environment Web server

nginx/1.18.0

### Environment PHP

7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.5.15-MariaDB-0+deb11u1

### Steps to reproduce the behavior

I have full rights

**test this is how it works:**
i create a new Third-Party. where i have already entered the "Customers tags/categories". i can see them and also the field to edit is present.

**test how it does NOT work: BUG**
i create a Third-Party without a "Customers tags/categories". i want to add a "Customers tags/categories" afterwards. i click on modify. there is no field to edit "Customers tags/categories" visible. **BUG**

### Attached files

**VIEW**
![Screenshot 2022-04-14 122411](https://user-images.githubusercontent.com/4697822/163367973-9c31f8af-ad2a-4e88-bf4b-9884dc5a0639.png)

**Editing where the category was already entered**
![Screenshot 2022-04-14 122437](https://user-images.githubusercontent.com/4697822/163368011-ca064377-2681-48f0-9b23-2ecb5ae00234.png)

**Editing where was recorded where from the beginning no category was deposited.**
![Screenshot 2022-04-14 122541](https://user-images.githubusercontent.com/4697822/163368052-360a7a13-e105-4c52-a2ad-7c347d053498.png)

**Comment by atm-maxime** [comment]
I can't reproduce on a 14.0.5. The only way the "tags" section does not appear is when your thirdparty is not a customer, nor a prospect. Can you check ?
