### ISSUE TITLE
V15.0.1 Add Propal signed in the List of email notifications

### ISSUE THREAD

**Issue by Bertrand-22** [Dolibarr/dolibarr#20644]
### Feature Request

For the online signing of proposals action by client, the notification by email will be useful.

Can you add the PROPAL_SIGNED in the list of email notifications?

### Suggested implementation

add the case PROPAL_SIGNED in the code in file
notify.class.php

....

**Comment by adpal06** [comment]
Yes i'm waiting for this too :)
