### ISSUE TITLE
one project and more than 1 third party 

### ISSUE THREAD

**Issue by zunami** [Dolibarr/dolibarr#20640]
### Feature Request

I always have the problem that I have a project but more than 1 Third-Party is involved.

create projects with multi "Third-Party".

### Use case

**A house remodeling**

So a project but there work only third-party.
One makes the windows
One does the screed
One does the plumber
One does the painting
...

Therefore input of more than one third-party.

Furthermore, the selection of the third party would be important for the tasks / gantt.
e.g. gantt
the screed layer works from to
the painter from to

one construction project and that with some subcontractors.
one overview of everything
one gantt control with when what starts.

**Comment by iouston** [comment]
Hi,
It's already possible if you didn't assign a thirdparty on a project.
Just create your project, validate it and enjoy with your several partners

**Comment by zunami** [comment]
yes that's not how i think of it. but i am the administrator over the project and there are subpartners. of course then i have to make subparters over each individual area a project with a partner
