### ISSUE TITLE
CRM / contact and default_lang ...

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#20651]
### Bug

I can't give language speaking of a contact

### Environment Version

14

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

php7.4

### Environment Database

mariadb 10

### Expected and actual behavior

There is default_lang field in database (socpeople) and contact.class.php seems to be good (hmmm varchar ... it could be better with a link to a language table):

`
                'default_lang' =>array('type'=>'varchar(6)', 'label'=>'Default lang', 'enabled'=>1, 'visible'=>3, 'position'=>205),
`

but i can't see a "Default lang" field when i create / update a user

**Comment by atm-maxime** [comment]
The default lang field appears when you activate the multi-lang interface in Home > Setup > Display

**Comment by rycks** [comment]
@atm-maxime so sorry i just remember the problem now !

yes of course i'm on multi lang setup but you can't configure language speaking of a contact even if your setup is multi lang.

For example, take a company in england, how could you configure a french-only-speaking people in that company ?

Other example: you can hire a spannish remote people to handle spannish customers in your own french company ... then how to put that information (contact juan.carlos is spanish-only-speaking) into default_lang database socpeople field ? everything seems to be ready in database but there is no solution ... i will do an other MR for that.

**Comment by rycks** [comment]
Result on a contact card : 

![image](https://user-images.githubusercontent.com/1468823/169769873-659b2330-21f8-4d45-8d6c-ad039c1def89.png)

**Comment by rycks** [comment]
as @eldy said during devcamp "that's not a bug" ... ok, ok, ok, so i add feature request tag :)
