### ISSUE TITLE
Doli 15.01: the origin of the movements is missing

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#20662]
### Bug

When we deliver an item to a customer, the origin is not reported in the 'List of movements of the item".

### Environment Version

15.0.1

### Environment OS

Linux dolionline 5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200) x86_64

### Environment Web server

Apache

### Environment PHP

7.0.33-0+deb9u12

### Environment Database

MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2

### Environment URL(s)

/custom/sme/list.php?idmenu=6&mainmenu=products&leftmenu=

### Attached files

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/3815422/163600159-2e531e80-60ed-4906-a9f2-82647834cdf0.png">

**Comment by atm-maxime** [comment]
I can't reproduce with a 15.0.2. The ony way to have this value empty is to delete the shipment, but then you have a movement corresponding to the deletion....

**Comment by syrinx75** [comment]
I'm sill with Doli 15.0.1. We do the delivery like this: we select the form of the customer, then page 'Customer', then 'Create an order', validation, delivery, invoice.

**Comment by syrinx75** [comment]
I've uploaded on 15.0.02, still a problem with the origins in the MRP: /mrp/mo_movements.php?id=116 
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/3815422/170884162-9c4ccd5a-872c-4e50-b743-ca7d27701a0c.png">

**Comment by syrinx75** [comment]
Still true in 15.0.3

![image](https://user-images.githubusercontent.com/3815422/185632832-47f2f3dd-75e4-49fa-a432-8c50a5056941.png)
