### ISSUE TITLE
Resource type list not appearing on new resource form in Dolibarr 15.0.1

### ISSUE THREAD

**Issue by paulorcdo** [Dolibarr/dolibarr#20672]
### Bug

Resource type list not appearing on new resource form in Dolibarr 15.0.1
The list is created with the values of <option> but the Text does not appear in the select

 
\<select id="selectfk_code_type_resource" class="flat maxwidthonsmartphone select_fk_code_type_resource" name="fk_code_type_resource">
\<option value="RES_ROOMS">\</option>
\<option value="RES_CARS">\</option>
\<option value="novo">\</option>
\<option value="sdfasdf">\</option>
\</select>
 
### Environment Version

15.0.1

**Comment by jocker132** [comment]
We have the same issue on the version 15.0.1
