### ISSUE TITLE
Bug: Vous essayez d'accéder à une page, région ou fonctionnalité d'un module désactivé, ou sans être dans une session authentifiée, ou avec un utilisateur non autorisé.

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#20699]
# Bug
On my test database (16.0.0.Alpha), I see the following:
I have the following error message when I try to add a product or a service, including **only** numbers at the level of its reference OR begining with number:
"You are trying to access a page, region or feature of a disabled module, or without being in an authenticated session, or with an unauthorized user."
For now, I work around the problem by entering at least one letter in the reference (example: "a11111", then I modify the product or service by removing the added letter "11111")
I cleared my browser cache, this happens on different OS, different browsers.
I deactivated the rights then reassigned the rights.
Same problem.

I haven't been able to figure out if issue #[19720](https://github.com/Dolibarr/dolibarr/issues/19720) is the same as mine, but I'm posting it here just in case.

If necessary, I have screenshots

## Environment
- **Version**: 16.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.0.33-0+deb9u12
- **Database**: MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2
- **URL(s)**: /product/card.php

## Expected and actual behavior
I expect to have a product created, I have the following error message:
"You are trying to access a page, region or feature of a disabled module, or without being in an authenticated session, or with an unauthorized user."

## Steps to reproduce the behavior
Product / Add a new product
On reference : 111111
On descrition : test1

**Comment by hregis** [comment]
hello @ozit 
it's fixed here https://github.com/Dolibarr/dolibarr/pull/20702
