### ISSUE TITLE
What do you think about remember filter and sorted field on table list views?

### ISSUE THREAD

**Issue by caos30** [Dolibarr/dolibarr#20701]
### Feature Request

To implement on Dolibarr an automatic system (maybe optionally to enable on settings) to let the table list views (list of invoices, thirds, products, etc.) to REMEMBER the LAST FILTER/SEARCH applied and the COLUMN choosed by the current user to SORT the results. 

### Use case

You usually like to see RECURRENT INVOICE LIST sorted by "next generation date" in ASCENDANT direction (closer next invoices at top). Nowadays i must TO CLICK TWICE the title of that column EACH TIME i go to that list (usually once per day)... so it's a really annoying and stupid waste of time and bandwidth and server CPU... (so i need to contaminate planet 3 times the really needed to check that table each day).

But i think that with whatever table list (products, invoices, tickets, etc...) we usually also prefer always to sort by "our preferred column and direction". So, i would love that Dolibarr REMEMBER the last sorting i used on X table list view.

The same can be applied to the filter or search options above those kind of tables/lists: you're checking the invoices of ONE CUSTOMER and each time you go to the INVOICE LIST you has to apply again the same filter !!??

So, it would be great that natively Dolibarr remember these 2 UI things during my navigation experience.

### Suggested implementation

I've implemented it for my CMS, and it's quite simple to do it on Dolibarr as well: 

- save on the user SESSION variable an array of "views" where to save those "settings per view useful to remember"
- and then when you're rendering again that view, consulting that information to apply the same settings

My apologies if such a system already exists... i've done some personal tests on my Dolibarr instance and i've not found how to get this behavior. And i've searched too in this "forum" for any other "issue/feature request" and i've not found nothing.

I could help with this, but only if someone of the core team accept to add it to the next version of Dolibarr. Thanks in advance!

**Comment by atm-maxime** [comment]
Thanks for sharing your experience.
Currently there are 2 existing things :
- default filter and sort on lists (home, setup, default values) which can help you have the recurring invoice list sorted like you want.
- using the link "back to list" on a card takes you back on your list just as it was (filters and sort are kept)

We could use the second system to always remember the list filters and sort but in my experience, if I click on "back to list", I want my list as it was, but if I click in the menu on a list link, I want the basic list.

**Comment by caos30** [comment]
@atm-maxime thanks... works great this "back to list" link... i usually use to return to the list. I didn't know about that "default settings" ... what is super great new!!!

Said this, i've realised now that at invoice list (for example): i can set a filter by the name of the THIRD, but if i click on a column title (ref, currency, multi_currency amount ...) to SORT the results, then the FILTER DISAPPEAR (!?). In other words: **i don't find how to apply a filter and a sorting at the same time (!)**.

Maybe this is not a feature request, but a "new" issue (i've not searched on opened issues, only have discovered the issue just now trying your second suggestion). But anyway, let me insist in my initial comment on this "feature request": i think that to SAVE ON USER SESSION the LAST filter and sorting is NEEDED. 

If you save on session that information you can forget about "carry on" always that information on physical LINKS... I've implemented it about more than 10 years ago in my own CMS and i really love it: 

1. visit invoice list, filter it, sort it
2. edit one of those invoices, saving or no saving
3. even from the invoice card you visit the third card, notes, documents, etc...
4. when you finally open (maybe in another browser tab) again the invoice list, you get THE EXACT list from you began (filter and sorting)

This is only possible using SESSION storage.
The unique minor "CONTRA" (handicap) is that you need to click the "clean filters" button on the table header (right corner). But it's not so handicap, because anyway you must now to do a click to the "invoice list" link in the left-vertical-menu.

Indeed, this left-vertical-menu has a behavior QUITE ANNOYING (i suppose that i'm not the unique user expressing this): if you visit a new module, then sometimes appear on the left the menu of the PREVIOUS module... in ways that i'm unable to understand without study the dolibarr PHP code... after almost 7 years using Dolibarr it continue being really annoying. But this is subject of interest for another issue itself (feature request, probably).

Please, i want you understand that i'm not requesting that Dolibarr runs as i would like. This "feature request" was to find more people that probably think like me that it would be improved in the way i'm suggesting. But if core-team (people like you) think that it's not necessary... i'm 100% agree with your criteria, of course.

Have a nice day.

**Comment by dolibit-ut** [comment]
I like your suggestion

**Comment by aspangaro** [comment]
Module Quick list is available on dolistore

**Comment by UBuschler** [comment]
Hi.

I use the Standard Module "Bookmarks". With this you are able to save a list or something else with set filter as a Bookmark (Bookmark in Dollar a shown on the Star Symbol left to the Username).

Perhaps this is also useful?
