### ISSUE TITLE
Numeric only ref. for products

### ISSUE THREAD

**Issue by lgeologic** [Dolibarr/dolibarr#20700]
### Bug

When we try to create a new product or service with numeric only ref (by hand or by mask) , dolibarr send an authentification error 

### Environment Version

16-alpha

### Environment OS

Debian 9

### Environment Web server

Apache 2

### Environment PHP

7.3

### Environment Database

Mariadb 5.5

### Environment URL(s)

/product/card.php

### Expected and actual behavior

I expected the product or service to be created.
Not to have a user right error (even if I use the super admin)

### Steps to reproduce the behavior

Create a new product or service

- Set a numeric only ref. or setup the mask to do so (eg : {0000} )
- Set a description
- Create product ; You'll see the error

**Comment by hregis** [comment]
@ldennery it's fixed here https://github.com/Dolibarr/dolibarr/pull/20702
