### ISSUE TITLE
Organisational departments setup through Dolibarr dictionary setup

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#20708]
### Feature Request

# Feature Request
Organizational structure is the backbone of any company or organization. And **Departments** is the one of the key aspects to make an effective organization structure. So a modern ERP should have a facility to Add/Edit/Modify departments inside it. Dolibarr ERP/CRM is getting better and better every day. But still don't have any feature to maintain an organization's depart in correct way. 

### Use case

# Use Case
A department is need in following cases but not limited to it.

1. Department is needed while we add an internal user. Let's say a organization can have 100s of employees belongs to several department.
2. Department is needed in Third Party Contacts and Addresses. Because third party's contacts or addresses are most of the time employees, so they belong to certain department.
3. Departments are needed in the organizational recruitment process. That is in which department a company is hiring.

### Suggested implementation

# Suggested implementation
The best place to give functionality of Departments Add/Edit/Delete, the Home->Setup->Dictionaries. After getting in on the page dictionaries setup, there will be link called, **_Departments_**.  After clicking on **_Departments_** the general setup page for departments should be displayed.  Now in the required modules or pages the Departments will be populated as a dropdown.

**Comment by alsoft10** [comment]
@eldy this is a very important feature for any modern ERP/CRM. I started development on this.

**Comment by hregis** [comment]
@alsoft10 you can use extra fields instead?

**Comment by alsoft10** [comment]
@hregis yes, your suggestion is good. But you know, I think it is better to have certain configuration for **_Departments_**. Because it's one of the primary need of any organizational structure. On the other hand **_Departments_** are needed by multiple pages and modules. So for every place we have to create extra field which obviously not professional.

**Comment by eldy** [comment]
If you enable the module Human Resource (still in dev), you should find features to manage company departments.
