### ISSUE TITLE
DB : qty type problem : Supplier order

### ISSUE THREAD

**Issue by Projets-ACTI** [Dolibarr/dolibarr#20704]
### Bug

Quantity calculation problem received on supplier order, on quantities with two decimal places

### Environment Version

13.0.5 -> 15.0.1

### Environment OS

NT INDUS 6.1 build 7601

### Environment Web server

Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.2.20

### Environment PHP

7.2.20

### Environment Database

MySQL or MariaDB 5.5.5-10.4.21-MariaDB

### Expected and actual behavior

On a supplier order, dispatched quantity equal to the quantity ordered, but the order remains in status: partially received! Problem seen noticed on orders with quantities to two decimal places (exemple : 12.99)
llx_commande_fournisseur_dispatch -> the type of "qty" is float
llx_commande_fournisseurdet -> the type of "qty" is double

This creates a calculation problem for quantities with two decimal places

**Comment by homer8173** [comment]
can't reproduce on dol16
