### ISSUE TITLE
Add a webhook module

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#20703]
### Feature Request

Add a module working like the module Agenda with a trigger that send, at each t

### Use case

Thus should allow to have integration possible with external tools with no need to develop a module on Dolibarr side.

### Suggested implementation

rigger event, a json post to an external url.
In setup, you can add urls to save into 
llx_webhook_targets
For each url, you can define list of trigger code supported (stored into a column of the table, all codes separated with a coma).
When an event is triggered, if the event is inside one line if llx_webhooks_targets, we 
This should make integration with generate a json that contains trigger code, the object and post it to the url

**Comment by BebZ** [comment]
That sounds nice :) 
Can you give working examples ? 
Each time a trigger is called, it opens an url ? 
Thanks

**Comment by grossfr** [comment]
Hi, please can you give an example of how the parameter added to the url looks like?
Thanks, Franz
