### ISSUE TITLE
Product entries not translating from French when generating foreign language PDFs

### ISSUE THREAD

**Issue by wutanggg** [Dolibarr/dolibarr#20719]
### Bug

When generating PDFs into foreign languages from a French installation of Dolibarr 15, fields "Nomenclature douanière ou Code SH" and "Pays d'origine" are appearing in French in all tested language translations of documents types.
The rest of the document translated OK.

I'll add that in the French versions "Nomenclature douanière ou Code SH" is displaying redundant info and is making the string too long to be easily readable and introducing clutter to the generated documents.

### Environment Version

15

### Environment OS

LINUX 20.04

### Environment PHP

7.4

### Environment Database

MYSQL 8.0

### Expected and actual behavior

optional product information strings should be translated

**Comment by wutanggg** [comment]
I forgot to add that using custom translations in the configurations page for "CustomCode" or "CountryOrigin" does not work for these values

**Comment by ns-info90** [comment]
Hello,

In which PDF edition do you have this problem?
