### ISSUE TITLE
Product lot document management should not use batch but ref (is lot id)

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#20711]
### Bug

Issue is on line 93 of htdocs/product/stock/productlot_card.php amd line 86 on htdocs/product/stock/productlot_document.php.
($object->ref = $object->batch;) 
Batch is not unique and can be same on different product.
Not sure how to solve, because already there from Dolibarr 8.
If we simply remove line, current document links are lost. Add constant USE_OLD_LOT_DOCUMENT_PATH ??

**Comment by BebZ** [comment]
True... if i understand, please correct me if I'm wrong :
 
"batch" is considered like a "foreign key" ? 
but it has to be "rowid" of the table product_batch instead ?
wrong conception of the table at its implementation ?

**Comment by fappels** [comment]
@BebZ, Table and classes are ok, There is no ref field in table but product_lot class sets id value into the ref property. But it's the pages who replace ref by batch. So if you have two lot from a different product with same value for batch and you upload a doc to one of them you will have same doc on the other lot, If you upload other doc to other lot you have you will also have this one on the first one.
Example:
Uploaded pdf to product PP10015:
![ProductLot 4-25-2022 7-45-16 PM](https://user-images.githubusercontent.com/4573808/165144790-e20465b3-b1c5-48d0-a9c7-2d6e90e94448.png)
Uploaded image to product 367855:
![ProductLot 4-25-2022 7-44-20 PM](https://user-images.githubusercontent.com/4573808/165145038-6e4058aa-7696-4421-afd9-dc50051071f4.png)
I have both doc on both lot.
