### ISSUE TITLE
Feature request : Field on price proposal showing Surface 

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#20725]
In connection to the calculated Wheigt and Volume I would like to have the calculated Surface as well. Pls see image below

![image](https://user-images.githubusercontent.com/24247236/165548912-fb3e724e-e733-45dc-b3ca-897fa5c449c5.png)

**Comment by dolibit-ut** [comment]
Hello,

this is mathematically impossible because bodies with the same volume or weight
but with different shapes have different surfaces.

**Comment by hasse-basse** [comment]
Hi

 It is done under product/card.php so it is just to move the code to wherever it is needed! (pls see the picture) I guess you are working with smaller items, I work with pallets and I promise that there is an up and a down and sides clearly defind.

This information is valubale when estimating transport costs as it is based partly on how much space the palette takes on the truck and partly on weight.

![surface](https://user-images.githubusercontent.com/24247236/166007563-80b066d6-a42b-412b-8d6f-910a6243ab4f.jpg)
