### ISSUE TITLE
Bug: No option to delete a component from a kit

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#20727]
There is no option to delete a component from a kit so a created kit can not be deleted! Pls see picture.

## Environment
- **Version**: 15.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.33-1+0~20211119.91+debian10~1.gbp618351
- **Database**: MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0+deb10u1
- **URL(s)**: /azert/product/composition/card.php?id=1718
- 
![delete](https://user-images.githubusercontent.com/24247236/165613505-63ab1d40-6289-482e-bc56-bb74ae935819.jpg)

**Comment by priojk** [comment]
It's possible to delete but maybe not the most intuitive process: To remove a component from the kit, just set the quantity to 0 and press the save button. It will then disappear from the list of components.

**Comment by hasse-basse** [comment]
Et voilà! Thanks. So then we maybe change this bug to a feature request; an instruction about how to do!
