### ISSUE TITLE
Adding new Fields

### ISSUE THREAD

**Issue by rudirossouw89** [Dolibarr/dolibarr#20749]
Hi

I'm new to Dolibarr. I would like to learn how to add custom fields in some of the Modules.  The problem I'm having is that once someone adds a new Purchase order and they select the third party, there is no way I can find of changing the third party at a later stage. For example, if they decide to use a different supplier halfway through the order, I would like to either be able to change the third party, or have a custom field to stipulate  the change in third party. Any assistance would be appreciated.

Kind regards
Rudi

**Comment by dolibit-ut** [comment]
Hi,

'custom fields' are now called 'extrafields' in Dolibarr.

You can always find them in the module setup.

Maybe this is helpful for you:

https://wiki.dolibarr.org/index.php?title=Extrafields

And take a look at the forum.

**Comment by ksar-ksar** [comment]
Hello,

Forum is there for user help : https://www.dolibarr.org/forum/
GitHub is for Bugs and developers
