### ISSUE TITLE
Order receptions: ErrorWarehouseRequiredIntoReceptionLine in Dolibar 14.01

### ISSUE THREAD

**Issue by slimdiallo** [Dolibarr/dolibarr#20748]
Hi 
someone can help me im facing this issue in dolibar 14.01. i have this only when i create multiple line reception.
thank you

**Comment by dolibit-ut** [comment]
Please make first an update to Dolibarr 14.0.5
and then try it again.

**Comment by slimdiallo** [comment]
its possible to do it for me and ill pay for the service

**Comment by slimdiallo** [comment]
hi, i update to dolibar 15.01 now the error change . the new error is  **Le champ 'Qté à recevoir/Entrepôt' est obligatoire**
mean the input Qty receive/warehouse is mandatory.
