### ISSUE TITLE
Inventory of large warehouses

### ISSUE THREAD

**Issue by valtbern** [Dolibarr/dolibarr#20741]
### Bug

Upon inventory of the warehouses with a large amount of items page becomes unresponsive.

### Environment Version

15.0.1

### Environment OS

Linux

### Environment Web server

LiteSpeed

### Environment PHP

7.4.28

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-cll-lve

### Environment URL(s)

/product/inventory/inventory.php?id=xyz&action=updatebyscaning

### Expected and actual behavior

We're using the scanner and scanning tool for the inventories.
The warehouses on average consist of 1000 - 3000 items. When we complete the process and hit ADD on the scanning tool window it takes a considerably long time to process the barcodes scanned and constantly keeps becoming unresponsive which makes the work inefficient and unable to conclude the inventory process.

Therefore it would need some technical optimization.

### Steps to reproduce the behavior

Try to perform inventory with a large number of products in Warehouse 

### Attached files

![image](https://user-images.githubusercontent.com/21037425/165812545-b4f9e3be-d4d8-4e68-9c79-97ac9f635b9b.png)

**Comment by dolibit-ut** [comment]
Hi,  

i don't know LiteSpeed  (most using Apache2 or nginx)

but maybe take a look into your php.ini  at 

- memory_limit 
- max_execution_time

What are your values?

**Comment by ksar-ksar** [comment]
Hello,

This issue is related to the Hosting not to Dolibarr directly

**Comment by atm-maxime** [comment]
We are also working on an improvement here #20298
