### ISSUE TITLE
Custom pdf Proposal

### ISSUE THREAD

**Issue by aaramirez91** [Dolibarr/dolibarr#20743]
### Feature Request

I'm trying to modify the default azur/cyan pdf model for my proposal but i want to display the label and ref on columns, does anyone could help me?

**Comment by dolibit-ut** [comment]
Hello,

this is not a bug or a feature request,

it is a question for the Forum    https://www.dolibarr.org/forum  

or take a look at the Wiki          https://wiki.dolibarr.org/index.php?title=Create_a_PDF_document_template

Please consider for the future - and successful work
