### ISSUE TITLE
Fields missing in invoice lines

### ISSUE THREAD

**Issue by Natureshadow** [Dolibarr/dolibarr#20750]
### Bug

I am generating an invoice using the sponge theme.

Here is how the entries look in the invoice editor:

![image](https://user-images.githubusercontent.com/212972/165956751-9036dc90-4056-48fa-91ee-79d59b2a4813.png)

And here is how it looks in the PDF:

![image](https://user-images.githubusercontent.com/212972/165956839-0aaca5f5-dae7-4d4b-8137-c93722fd6b2e.png)

As you cansee, all data except for the item description is missing in the PDF.

### Environment Version

15.0.1

### Environment OS

Debian 11 (bullseye)

### Environment Web server

nginx 1.18.0

### Environment PHP

PHP 7.4 (fpm)

### Environment Database

PostgreSQL 14

**Comment by ksar-ksar** [comment]
Hello,

Check on Setup->PDF->Hide product lines details 
It should be desactivated
![image](https://user-images.githubusercontent.com/35605507/166068429-95fddbf9-69a2-44b1-90cf-be76099aff00.png)

**Comment by Natureshadow** [comment]
Ah, yes, that fixes it.

I am somewhat puzzled as to what the point of defaulting to an empty invoice it, but nonetheless, thanks for pointing to that option!
