### ISSUE TITLE
delete_module_parts doesn't remove CSS path of disabled modules, sometimes

### ISSUE THREAD

**Issue by caos30** [Dolibarr/dolibarr#20760]
### Bug

`main.inc.php` insert a `<link rel="stylesheet" type="text/css" href="..." />` in the HTML HEAD for DISABLED modules, sometimes. This cause USELESS extra resources consume ON EACH CLICK using Dolibarr: extra work for web browser, for the network bandwidth, and extra CPU/disk IO work for the server trying to recover non-existing files. 

Why i say "sometimes"? because it doesn't happen for any module or always for the same module. Let me explain. After a couple of hours of follow the ant's row i found the problem: `delete_module_parts()` method on this file:

`/core/modules/DolibarrModules.class.php `

The problem (it's my opinion) is that it tries now to find and delete keys on `llx_const` table using the CURRENT `module_aparts[]` array currently defined in the file modMyModule.class.php

The problem arise when -for example- an admin user REPLACE the directory of a third module with a new version (unzipping it, you know) BEFORE TO DEACTIVATE the module in the Dolibarr-Settings-Modules area, and the new version DOESN'T HAS DEFINED a CSS element (in module_parts array) !!! in this case, the constant `MAIN_MODULE_MYMODULE_CSS` IS NOT DELETED !!!

I suppose that this could cause other (worst?) problems if there are missing elements on module_aparts different than CSS, like JS, TRIGGERS, MENUS, MODELS, ETC...

**So my question for you (someone of core team... @eldy ?) is if the function `delete_module_parts()` would be better to DELETE ALL CONSTANTS from llx_const related to a module when it's disabled ?**

Instead of current query:

```
$sql = "DELETE FROM ".MAIN_DB_PREFIX."const";
$sql .= " WHERE ".$this->db->decrypt('name')." LIKE '".$this->db->escape($this->const_name)."_".strtoupper($key)."'";
$sql .= " AND entity = ".((int) $entity);

```
something like this (without the $key and without the `foreach` of course):

```
$sql = "DELETE FROM ".MAIN_DB_PREFIX."const";
$sql .= " WHERE ".$this->db->decrypt('name')." LIKE '".$this->db->escape($this->const_name)."_;
$sql .= " AND entity = ".((int) $entity);

```

I found this issue just because in one of my modules i decided (some versions ago) to not include a 'css' PHP file in the module, but embed the few CSS styles in the same PHP module's files. But the browser continue asking for that OLD CSS file (!?). Let me insist: i suspect that this is causing other troubles with other elements missing on `module_parts` of some modules, not only CSS.

Last comment: i know that is more frequent to ADD elements to an existing module instead of REMOVE elements... but certainly it happens. So... i would say that we need to take a more solid solution.

### Environment Version

Dolibarr 15.0.0

### Environment URL(s)

/htdocs/admin/modules.php

### Expected and actual behavior

**Expected behavior:** after disable a module, ALL the constants on llx_const of tyoe MAIN_MODULE_MYMODULE_CSS should be removed. 

**Actual behavior:** the `llx_const` for that module are only removed when they exist in the `modMyModule.class.php` file, so if i disable&enable the module AFTER replace the physical files of the module, and there are differences in the NON-EMPTY elements of the array `module_aparts`, it can remain some OLD elements defined on llx_const! 

### Steps to reproduce the behavior

1. take a ENABLED third module (/custom/)
2. comment the 'css' element in the `module_parts` array of its `modMyModule.class.php `
3. DISABLE the module
4. load ANY page of Dolibarr and you will see that the web browser is returning a RED ERROR trying to load the OLD css filepath of thata module (you can see it on the SOURCE CODE of that page)
5. also, you can search at `llx_const` db table and you will STILL found the constant: `MAIN_MODULE_MYMODULE_CSS`

**Comment by hregis** [comment]
@caos30 
It is up to the module developer to ensure that the constants are properly cleaned, moreover if you delete "MAIN_MODULE_MYMODULE_*" you also delete constants that are used for configuration, and deactivating/reactivating the module would cause it to lose its setup!

**Comment by caos30** [comment]
> @caos30 It is up to the module developer to ensure that the constants are properly cleaned, moreover if you delete "MAIN_MODULE_MYMODULE_*" you also delete constants that are used for configuration, and deactivating/reactivating the module would cause it to lose its setup!

Ok, i understand your point. And i understand that a delete of `MAIN_MODULE_MYMODULE_*` would delete previous settings. But then it has no sense to include a `module_aparts[]` array in the `modMyModule.class.php` file if the module ALWAYS HAS TO CHECK IF THAT INFO HAS BEEN CORRECTLY inserted to the corresponding constans on `llx_const`.

So, briefly:
- ok, we cannot remove `MAIN_MODULE_MYMODULE_*` when disabling a module
- but at least, in the RE-ENABLING of the module, we must check one by one the existing elements on `llx_const` for that module to REMOVE the ones that are not being used. In other words, following the issue with my module: if in the new version of the module there is not declared a 'css' value but there exists `MAIN_MODULE_MYMODULE_CSS`, then Dolibarr `_init()` method SHOULD REMOVE it from `llx_const` !

Am i wrong? Do you agree with this "improvement" for the `_init()` method?

**Comment by hregis** [comment]
@caos30 
Sorry I confused with the constants!
Yes, we can absolutely delete all `MAIN_MODULE_MYMODULE_*`

**Comment by hregis** [comment]
@caos30
On the other hand, if you delete the foreach, you will no longer be able to process the "entity" field which may be present in the "array" of "module_parts"!

**Comment by hregis** [comment]
@caos30 
i send a fix : https://github.com/Dolibarr/dolibarr/pull/20767
