### ISSUE TITLE
Checkbox is not checked by default with a default value to 1

### ISSUE THREAD

**Issue by AurelienL7** [Dolibarr/dolibarr#20769]
### Bug

I added a checkbox extrafield on products with a default value to 1 but when I go to the product creation page the checkbox is not checked.

I think I've figured out what the problem is :

In commonobject.class.php, function showOptionals(), line 7514 : 

`if (in_array($extrafields->attributes[$this->table_element]['type'][$key], array('html', 'text', 'varchar', 'select', 'int')))`

Replace by : 

`if (in_array($extrafields->attributes[$this->table_element]['type'][$key], array('html', 'text', 'varchar', 'select', 'int', 'boolean')))`

### Environment Version

14.0.5

### Environment PHP

7.4.12

**Comment by atm-maxime** [comment]
Thanks @AurelienL7
