### ISSUE TITLE
International invoice VAT for EU seller with EU customers

### ISSUE THREAD

**Issue by xabitrigo** [Dolibarr/dolibarr#20788]
### Bug

International buys should allow VAT types for both the origin and destination countries. According to this: https://ec.europa.eu/taxation_customs/business/vat/vat-e-commerce_en both cases are possible.

This can be activated via the option SERVICE_ARE_ECOMMERCE_200238EC (https://wiki.dolibarr.org/index.php/Setup_Other#Services_Module) , but it only seems to be working for predefined items, and not for free text products or services.

I think the problem may be in the line 5903 of tile htdocs/core/class/html.form.class.php 
```
if (!isInEEC($societe_vendeuse) && (!is_object($societe_acheteuse) || (isInEEC($societe_acheteuse) && !$societe_acheteuse->isACompany()))) {
```

if I remove the "not" from the first `isInEEC` I can see the VAT for both countries

This is related to issue #12557

### Environment Version

15.0.1

### Environment OS

Ubuntu 20.04

### Environment Web server

Apache

### Environment PHP

 7.4.29 FPM/FastCGI 

### Environment Database

PostgreSQL 12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)

### Expected and actual behavior

To see the VAT for both countries

### Steps to reproduce the behavior

- Install dolibarr
- Set up the company as a Spanish company
- Add a client from Italy
- Create an Invoice
- You should be able to use Italy 22% VAT, but it's not visible

**Comment by lemathou** [comment]
I'm working on it at the moment... The conditions seems to be bugged.
First, it should also work for products and it is not, and second this prevents the main enterprise configured in Dolibarr (sender/seller) to be in EEC, which is nonsense... !isInEEC($societe_vendeuse).

I think we should replace :
`if (!isInEEC($societe_vendeuse) && (!is_object($societe_acheteuse) || (isInEEC($societe_acheteuse) && !$societe_acheteuse->isACompany()))) {`
with
`if (isInEEC($societe_vendeuse) && (is_object($societe_acheteuse) && (isInEEC($societe_acheteuse) && !$societe_acheteuse->isACompany()))) {`

and after :
`if ($type == 1)`
with
`if ($type == 1 || $type == 0)`

Or, better make it work with every product line, and some services (except shipping, and any others if I understood well the rules)

**Comment by Ludovicode42** [comment]
**Informations:**

Dolibarr 15.0.3
SERVICE_ARE_ECOMMERCE_200238EC = 1

On Sales Order, Sales Proposal and Invoice, when modifying a line with VAT outside of France (e.g. Germany), the VAT goes from 19% to 0% .

**Example with a German third party,**

Product added with good VAT : 

![image](https://user-images.githubusercontent.com/124346383/216557957-0ea98523-fce8-4802-887d-76133ecb6238.png)

If you click on the pencil, the VAT is set to 0 and the German VAT is not proposed : 

![image](https://user-images.githubusercontent.com/124346383/216558262-2378df1f-e5ef-470c-8f7e-bd5ef8595f9f.png)

If you don't make any changes and validate the order, everything is fine (VAT at 19%). If you want to create an invoice for a fixed amount on account, the VAT will also appear at 0% : 

![image](https://user-images.githubusercontent.com/124346383/216559451-26a716a9-b363-401a-ad37-688579308f97.png)

![image](https://user-images.githubusercontent.com/124346383/216559650-db8e6ac4-75d8-4c7f-855d-ce2f101f1501.png)

**Comment by ErikRakhorst** [comment]
any progress on this? 
I still see the same behavior as described above with 17.0.0

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
