### ISSUE TITLE
Improve project main view

### ISSUE THREAD

**Issue by zunami** [Dolibarr/dolibarr#20795]
### Feature Request

I think the project is a little hidden treasure that still has a lot of potential.

I just have my problems with the main view of the leads / projects and the projects themselves main view

this page should be designed like the main view variable and with much more different queries. i never get there the most important information i need daily.
new queries should be added . you should be able to activate and deactivate them like in the main view of dolibarr.

**main view of the leads / projects
dolibarr/projet/index.php?mainmenu=project**

what views would i need?
- projects by categories that you can select yourself with the checkbox.
- view with open tasks including gantt
- open tickets linked to projects
- contacts suggestions in random mode for networking

**the projects themselves main view
/dolibarr/projet/card.php?id=NUMBER**

what views would i need?
- i would rather need contacts instead of linked documents
- a slim view of the open or better yet the soon due tasks
- notes on view

**Comment by zunami** [comment]
this is still needed

**Comment by zunami** [comment]
this is still needed

**Comment by eldy** [comment]
Because the ticket contains several different requests, it is not possible to process it. Feature requests mut contains one and only 1 topic or suggestion so it become possible to exchange on the topic or assign it (assignation is too difficult to manage when a ticket contains 2 or more suggestions).
