### ISSUE TITLE
CMailFile:buildCSS incorrect work

### ISSUE THREAD

**Issue by Libaud** [Dolibarr/dolibarr#20791]
### Bug

The buildCSS method on CMailFile class doesn't correctly get css argument on class constructor. Because the css argument as been crushed on the code. Reading the code to see it :

        public function buildCSS()
	{
		if (!empty($this->css)) {
			// Style CSS
			$this->styleCSS = '<style type="text/css">';
			$this->styleCSS .= 'body {';

			if ($this->css['bgcolor']) {
				$this->styleCSS .= '  background-color: '.$this->css['bgcolor'].';';
				$this->bodyCSS .= ' bgcolor="'.$this->css['bgcolor'].'"';
			}
			if ($this->css['bgimage']) {
				// TODO recuperer cid
				$this->styleCSS .= ' background-image: url("cid:'.$this->css['bgimage_cid'].'");';
			}
			$this->styleCSS .= '}';
			$this->styleCSS .= '</style>';
		}
	}

### Environment Version

15.1

### Environment OS

Linux

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MariaDB

**Comment by homer8173** [comment]
Could you detail ? the argument here is $this->css and it's never crushed within this function
