### ISSUE TITLE
Bug: problème prix d'achat/TVA

### ISSUE THREAD

**Issue by DoliFRAP67** [Dolibarr/dolibarr#20803]
# Instructions
Version 15.0.1 / facturation / commerce
Erreur TVA même sur PU HT/TVA connu

# Bug
facture ou commande : les lignes sont toujours à TVA20% y compris pour les produits avec prix d'achat/TVA enregistré

## Environment
- **Version**: 15.0.1
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) PHP/7.3.12
- **PHP**: apache2handler 7.3.12
- **Database**: MySQL or MariaDB 5.5.5-10.4.10-MariaDB
- **URL(s)**: /dolibarr/fourn/facture/card.php?facid=848

## Expected and actual behavior
Les taux de TVA devraient s'appliquer si le PU HT est enregistré.

## Steps to reproduce the behavior
Version 15.0.1 / facturation / commerce
Lors de l'établissement d'une facture ou d'une commande, les lignes sont toujours à TVA 20%
Chaque ligne se complète systématiquement au taux de 20%. 
Même si le prix d'achat et son taux de TVA est enregistré.
Il faut donc reprendre chaque taux et corriger chaque ligne.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/81977311/167252835-9541e80f-51bf-449b-bf2b-862eb11dfa46.png)
![image](https://user-images.githubusercontent.com/81977311/167252898-26fe0e1e-91ec-49e8-86d5-92fe12abb84c.png)

## Report

Merci pour vos aides

**Comment by homer8173** [comment]
bug reproduit sur V16

**Comment by homer8173** [comment]
https://github.com/Dolibarr/dolibarr/pull/20920
