### ISSUE TITLE
Ticketing Widgets Labels Are Wrong

### ISSUE THREAD

**Issue by git-putz** [Dolibarr/dolibarr#20804]
### Bug

"Number of open tickets by severity" and "Distribution of open tickets by type" widget graphs have incorrect labels.
For example the severity list I have configured is Priority 1, 2 ,3, and 4.  The "Number of open tickets by severity" graph displays them as follows:

TicketSeverityShortPRIORITY1
TicketSeverityShortPRIORITY2
TicketSeverityShortPRIORITY3
TicketSeverityShortPRIORITY4

For "Distribution of open tickets by type" graph, I have types configured as Request, Incident, Problem, NOC, Sales, Client Account and the chart shows the labels as:

TicketTypeShortREQ
TicketTypeShortINCIDENT
TicketTypeShortNOC
TicketTypeShortSALES
TicketTypeShortACCOUNT

"Problem" is the only labeled correctly

Is it possible to get these Widgets to display the "Label" of each from the Dictionary Setup?

### Environment Version

15.01

### Environment OS

Ubuntu 20.04

### Environment Web server

nginx/1.18.0

### Environment PHP

7.4.3

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0ubuntu0.20.04.1

### Steps to reproduce the behavior

Add items in dictionary setup for Ticket - Types and Ticket - Severities.  
Create tickets.
Add Widget to Tickets screen.

### Attached files

![D_Widget02](https://user-images.githubusercontent.com/52859696/167267642-cd96ed44-898d-4609-834a-e225facc7246.PNG)
![D_Widget01](https://user-images.githubusercontent.com/52859696/167267643-0b657b80-44ee-49e1-9888-1ea816f58c65.PNG)
![D_Types](https://user-images.githubusercontent.com/52859696/167267644-2ddb0c35-43a7-4688-bf40-61530d6509f5.PNG)
![D_Severities](https://user-images.githubusercontent.com/52859696/167267645-8cea104f-6aa6-4b58-aa94-72c413efecb9.PNG)

**Comment by lmag** [comment]
I closed it for you @atm-maxime
