### ISSUE TITLE
Fields  fk_origin and origintype of llx_stock_mouvement not updated when Shipment validated

### ISSUE THREAD

**Issue by Rascarquapac** [Dolibarr/dolibarr#20806]
### Bug

Using version 14.0.4, the "shipment validated" action generated movements in the llx_stock_mouvement table with 
- label field : "Shipment SHxxxxx validated" 
- fk_origin field: <a number>
- origintype: "shipping" 
Using version 15.0.1, the "shipment validated" action generated movements in the llx_stock_mouvement table with 
- label field : "Shipment SHxxxxx validated" 
- fk_origin field: 0
- origintype: void 
Dolibarr 15.0.1 was installed on the 25/04/2022 (14.0.4 before)

This behavior is different from 14.0.4 to 15.0.1 . It seems do not match the wiki description of "https://wiki.dolibarr.org/index.php?title=Table_llx_stock_mouvement" for fields fk_origin  and origintype. Requests (API or SQL) based on these fields are no more correct. 

### Environment Version

15.0.1

### Environment OS

Linux (OVH mutu:Linux webm084.cluster015.gra.hosting.ovh.net)

### Environment Web server

Apache

### Environment PHP

7.3.32

### Environment Database

Mysql /Version:5.6.50/Driver:mysqli (mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $)

### Expected and actual behavior

See bug description.

### Steps to reproduce the behavior

- Create an Sales Order with predefined products (have to be in stocks), validate
- Create a Shipment from the Sales Order and validate it
- Check the movements associated in llx_stock_mouvement.

### Attached files

<img width="1039" alt="llx_stock_mouvement table screenshot" src="https://user-images.githubusercontent.com/25272167/167353205-b6837f4a-aa1f-4ff8-bcb8-69c84fa769f4.png">

**Comment by tetus** [comment]
I have same issue behaviour on Customer orders, no origintype nor fk_origin set when creating new entrie. Please Help

**Comment by edupulpillo** [comment]
the problem still is present in v17
