### ISSUE TITLE
Customize Self Registration Module

### ISSUE THREAD

**Issue by hanneshier** [Dolibarr/dolibarr#20826]
### Feature Request

Add options to customize the self registration page of the member module.

### Use case

The self registration page is one of the first impressions a new member gets of our foundation. It would be nice to get some options to customize this experience.

### Suggested implementation

Add the option to hide default form fields that are note necessary for some use cases.
Add the option to add custom css.
Add option add some extra information/text.
Add option to make additional fields mandatory.

**Comment by dolibit-ut** [comment]
Hello, the most of these requested features are yet available.
Please check first your Dolibarr Version and look into Wiki and Forum.

**Comment by hanneshier** [comment]
I've already checked the wiki and forum, but especially for editing form fields I did not find a solution. So I want to disable the "Information is public" checkbox and need to make the birthdate field mandatory.
