### ISSUE TITLE
Error creating Intervention from a model

### ISSUE THREAD

**Issue by VH35** [Dolibarr/dolibarr#20828]
### Bug

The function creation of an intervention from a model already registered does not work. The actions defined in the models are not present in the intervention created from.

### Environment Version

V14.0.4

### Environment OS

Linux dolifarm1 5.4.174-2-pve #1 SMP PVE 5.4.174-2 (Thu, 10 Mar 2022 15:58:44 +0100) x86_64

### Environment Web server

Apache

### Environment PHP

7.4.29

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0+deb10u1-log

### Expected and actual behavior

Creation of an intervention model and then, using this model as much as necessary to produce new interventions with the same frame. By clicking on the button "create intervention" from the model, the intervention sheet is empty, without lines integrated in the model.

**Comment by priojk** [comment]
Can confirm that this behaviour exists also in 15.0.1. Tasks which are present in the template are not present in interventions created form this template.

Two additional observations: 

- Button to create an intervention from template is labeled "CREATEFICHINTER" (i.e. no translation used).
- There seems to be no way to edit an existing template of an intervention.
