### ISSUE TITLE
Third gender not available on the self-registration page of the the members module

### ISSUE THREAD

**Issue by hanneshier** [Dolibarr/dolibarr#20824]
### Feature Request

~~Add the option to add several gender types, like non-binary or agender~~
Make the third gender type available in the self registration-page of the members module.

### Use case

~~We are using Dolibarr within our foundation to manage our members. But currently, we only have the option to use male and female as their gender. Especially on the member module self registration page, this two options seem to exclude some members of our community.~~

New members should have the option to chose their gender upon registration by themself.

### Suggested implementation

~~Add either at least one additional gender option or let the gender types be editable via the Dictionary Setup.~~

**Comment by dolibit-ut** [comment]
Hello,
i guess your Dolibarr is not up-to-date.

At least since Version 14  there is a third gender for members and users.

And you can maybe use the field salutations which you can set via the dictionary.

**Comment by hanneshier** [comment]
Oh, youre right! Sorry. The option is not available on the self-registration page though. I´ve updated this issue accordingly.

![Screenshot 2022-05-13 at 12 51 19](https://user-images.githubusercontent.com/11063798/168268719-ea5d5d20-2638-43a3-ac97-187aee71589d.png)

**Comment by dolibit-ut** [comment]
Hey i think it is fixed with  #22044
