### ISSUE TITLE
Import/Export Template in ModuleBuilder

### ISSUE THREAD

**Issue by karozans** [Dolibarr/dolibarr#20875]
### Bug

When creating a new module using the moduleBuilder, the import template is not correct and is missing lots of information to get the import working.

### Environment Version

14.05 and 15.0.1

### Environment OS

Debian 10

### Environment Web server

Apache 2.4.48

### Environment PHP

7.3.29

### Environment Database

Mysql 8

### Environment URL(s)

modulebuilder/template/core/modMyModule.class.php

### Expected and actual behavior

It is expect to have the proper template generated for the imports and exports when you create a new module using the modulebuilder.  Instead the import and export templates are not correct and doesn't print out the correct template to use for the import and export functionality.

### Steps to reproduce the behavior

Create a new module using the modulebuilder.  Then edit the descriptor file section for the imports/exports.

**Comment by atm-maxime** [comment]
Thanks for your feedback. For now the "/* BEGIN MODULEBUILDER IMPORT MYOBJECT */" section in the module descriptor is not generated automatically. This is a feature request to improve modulebuilder.
