### ISSUE TITLE
OpenId implementation and documentation

### ISSUE THREAD

**Issue by alograg** [Dolibarr/dolibarr#20888]
### Bug

There is no documentation to configure ***OpenId***, nor to add another OpenId service in the ***OAuth configuration section***.

### Environment Version

All

### Environment OS

All

### Environment Web server

All

### Environment PHP

All

### Environment Database

All

### Environment URL(s)

All

### Expected and actual behavior

A documentation with the al steps to configure access with OpenID

### Steps to reproduce the behavior

Set the variable in the configuration : 

```php

$dolibarr_main_authentication='openid,dolibarr';

```

**Comment by atm-maxime** [comment]
Did you activate the Oauth module ?
Adding a new oauth service is a feature request

**Comment by alograg** [comment]
Yes, i did.
Ok, i need create a nwe ticket ?
Still there is no documentation for the module.
