### ISSUE TITLE
Latest (`15.0.2`) deb package cannot be installed on Debian (unknown compression)

### ISSUE THREAD

**Issue by GaetanLepage** [Dolibarr/dolibarr#20894]
### Bug

The latest DoliDeb package seems to be incompatible with Debian:

### Environment OS

Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

### Environment Web server

lighttpd 1.4.59

### Environment PHP

PHP 7.4.28

### Expected and actual behavior

- Expected: the package gets installed succesfully
- Actual:
```
[I] ➜ sudo dpkg -i dolibarr_15.0.2-4_all.deb
dpkg-deb: error: archive 'dolibarr_15.0.2-4_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive dolibarr_15.0.2-4_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 dolibarr_15.0.2-4_all.deb
```

### Steps to reproduce the behavior

- Download the latest dolideb package (`15.0.2`)
- `sudo dpkg -i dolibarr_15.0.2-4_all.deb`

**Comment by stephanehofman** [comment]
Same thing for me ...
Installation of zstd package  does not change the situation 

file dolibarr_15.0.2-4_all.deb
dolibarr_15.0.2-4_all.deb: Debian binary package (format 2.0), with control.tar.zs, data compression zst

**Comment by troublestarter** [comment]
same here

**Comment by pascal14633** [comment]
same here!

**Comment by stephanehofman** [comment]
Workaround : repack the .deb file 
ar x dolibarr_15.0.2-4_all.deb
zstd -d < control.tar.zst | xz > control.tar.xz
zstd -d < data.tar.zst | xz > data.tar.xz
ar -m -c -a sdsd dolibarr_15.0.2-4_all_repacked.deb debian-binary control.tar.xz data.tar.xz
rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst

**Comment by GaetanLepage** [comment]
Thank you for the fix.
Is there a chance that Dolibarr developers will repair the package for Debian ?

**Comment by LudovicRousseau** [comment]
The problem could be fixed using something like:
```patch
--- build/debian/rules.old	2022-08-25 21:36:43.000000000 +0200
+++ build/debian/rules	2022-08-25 21:37:03.000000000 +0200
@@ -126,3 +126,5 @@
 	chown www-data:www-data debian/dolibarr/var/lib/dolibarr/documents
 	chmod 2775 debian/dolibarr/var/lib/dolibarr/documents
 	
+override_dh_builddeb:
+	dh_builddeb -- -Zgzip
```
to force the use of gzip instead of zstd.

**Comment by Mobiak** [comment]
> Workaround : repack the .deb file ar x dolibarr_15.0.2-4_all.deb zstd -d < control.tar.zst | xz > control.tar.xz zstd -d < data.tar.zst | xz > data.tar.xz ar -m -c -a sdsd dolibarr_15.0.2-4_all_repacked.deb debian-binary control.tar.xz data.tar.xz rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst

I got the same issue packaging my stuff for our Yocto.
This fixed it ;)

**Comment by LudovicRousseau** [comment]
I improved the script given by @stephanehofman to make it more verbose and more efficient (use all the CPUs to recompress):
```bash
#!/bin/bash

set -e

# dolibarr_16.0.2-4_all.deb
filename=$1

# => 16.0.2-4_all.deb
filename=${filename/dolibarr_/}

# => 16.0.2
VERSION=${filename/-4_all.deb/}

echo "Using dolibarr_${VERSION}-4_all.deb"

if [ ! -f dolibarr_${VERSION}-4_all.deb ]
then
	echo "File not found"
	exit
fi

set -x

ar x dolibarr_${VERSION}-4_all.deb
unzstd control.tar.zst
unzstd data.tar.zst
xz --threads=0 --verbose control.tar
xz --threads=0 --verbose data.tar
rm dolibarr_${VERSION}-4_all.deb
ar cr dolibarr_${VERSION}-4_all.deb debian-binary control.tar.xz data.tar.xz

rm -f debian-binary \
	control.tar control.tar.xz control.tar.zst \
	data.tar data.tar.xz data.tar.zst
```

Save it as `dolibarr_repack.sh` and use it like this:
```
$ dolibarr_repack.sh dolibarr_16.0.2-4_all.deb
```

**Comment by bugfishtm** [comment]
> ar x dolibarr_15.0.2-4_all.deb
> zstd -d < control.tar.zst | xz > control.tar.xz
> zstd -d < data.tar.zst | xz > data.tar.xz
> ar -m -c -a sdsd dolibarr_15.0.2-4_all_repacked.deb debian-binary control.tar.xz data.tar.xz

this is still working for actual versions, i encountered this error on debian 11.
ar is not installed by default, you have to install it using apt install binutils.
Thanks for that @stephanehofman

**Comment by rycks** [comment]
@LudovicRousseau thanks, let me try on my debian, then make the PR to push your solution upstream !
