### ISSUE TITLE
buying prices is not automatically updated upon vendor invoice validating

### ISSUE THREAD

**Issue by morafat81** [Dolibarr/dolibarr#20893]
### Bug

in the product page the buying prices and the vendor prices is not getting any update after validating vendor invoice
![image](https://user-images.githubusercontent.com/105800960/169075280-b58853e8-42eb-4d08-9b9d-3d8096e7c611.png)
 and this reflects on the margins to be wrong and the kits cost to be wrong too
 
![Untitled-1](https://user-images.githubusercontent.com/105800960/169078955-1efb7f7b-3495-4184-9702-02bbd23448fc.jpg)

**Comment by atm-maxime** [comment]
Hi. This is normal behaviour. Not everyone wants an automatic update like this. Mainly people have the buying price defined regarding the vendor.
2 hidden options exists to update automatically existing prices on supplier orders SUPPLIER_ORDER_EDIT_BUYINGPRICE_DURING_RECEIPT and SUPPLIER_ORDER_CAN_UPDATE_BUYINGPRICE_DURING_RECEIPT

**Comment by morafat81** [comment]
SUPPLIER_ORDER_EDIT_BUYINGPRICE_DURING_RECEIPT and SUPPLIER_ORDER_CAN_UPDATE_BUYINGPRICE_DURING_RECEIPT

these works on version 13?

**Comment by atm-maxime** [comment]
Seems to be since V6 according to https://wiki.dolibarr.org/index.php?title=Setup_Other

**Comment by rsodarith** [comment]
After set 
SUPPLIER_ORDER_EDIT_BUYINGPRICE_DURING_RECEIPT SUPPLIER_ORDER_CAN_UPDATE_BUYINGPRICE_DURING_RECEIPT
![2024-05-10 15 21 35](https://github.com/Dolibarr/dolibarr/assets/3657351/d2444021-e7ce-4565-a152-06ed4b7e883c)

It is still 0 
![2024-05-10 15 22 51](https://github.com/Dolibarr/dolibarr/assets/3657351/470841dd-1758-42a2-a433-c25d4e7e1cca)

**Comment by sergioponguta** [comment]
Did you find any solution for this?
