### ISSUE TITLE
Warning: md5_file

### ISSUE THREAD

**Issue by bardieldj** [Dolibarr/dolibarr#20904]
### Bug

Warning: md5_file(D:/xampp/htdocs/gestion/documents/facture/FA2205-0038/FA2205-0038_Factura.odt): failed to open stream: No such file or directory in D:\xampp\htdocs\gestion\core\class\commonobject.class.php on line 5405

### Environment Version

15.02

### Environment OS

windows 10

### Environment Web server

apache

### Environment PHP

7.4

### Environment Database

marianadb

**Comment by lmag** [comment]
Work on 16.01, 16.0.2, 17 beta
