### ISSUE TITLE
Scayt Spell Checker button missing in WYSIWIG module

### ISSUE THREAD

**Issue by alexolait** [Dolibarr/dolibarr#20903]
### Bug

The button Scayt (Spell checker) is missing in the textarea with WYSIWIG module activated since Dolibarr v15

### Environment Version

15.0.1

### Environment OS

Debian

### Environment Web server

Apache

### Environment PHP

PHP7

### Environment Database

Mysql

### Steps to reproduce the behavior

Create, intervention, invoice, propal... Everywhere you can write text in a text area with WYSIWIG module activated

### Attached files

![image](https://user-images.githubusercontent.com/22803868/169355124-63471cf9-671e-4a92-8687-9f95e0a2bcfa.png)

**Comment by atm-maxime** [comment]
I can't reproduce on 15.0.3 (github), so seems to be fixed

**Comment by alexolait** [comment]
Same in 15.0.2 I hope has you said the bug is corrected in 15.0.3

**Comment by PlanPc** [comment]
Same problem at 15.0.3


Params, doesnt work either, trying to force at file **\theme\eldy\ckeditor\config.js**


config.scayt_autoStartup = true;
config.scayt_sLang = 'es_ES';

Scayt completely gone

## Environment
- **Version**: 15.0.3
- **OS**: Linux
- **Web server**: nginx/1.16.1
- **PHP**: fpm-fcgi 7.4.9
- **Database**: MySQL or MariaDB 5.5.5-10.3.29-MariaDB
- **URL(s)**: /admin/fckeditor.php

**Comment by PlanPc** [comment]
Since, dont know what Dolibarr version, its only neccesary to activate in https://wiki.dolibarr.org/index.php/Setup_Other this variable to work SCYAT again.


**FCKEDITOR_ENABLE_SCAYT_AUTOSTARTUP**
