### ISSUE TITLE
Random lis of project displayed in many lists : agenda, invoices, ...

### ISSUE THREAD

**Issue by c-orazio** [Dolibarr/dolibarr#20913]
### Bug

I moved from dolibarr 11 to 14.0.5 on ubutu 20.04
When we want to make a new invoice or a new entry in the agenda, we do not have the complete list of projects available in the select list of the field 'project'
This is a major issue, because then we control all the topic related to a project... 
It sound like the field list is randomely filled

### Environment Version

14.0.5

### Environment OS

server ubuntu 20.4 

### Environment Web server

server ubuntu 20.4 

### Environment PHP

php 7

### Environment Database

mysql

### Expected and actual behavior

we expect to have the list with all open project listed in the field project of agenda, or invoice, or...

### Steps to reproduce the behavior

try to create a new invoice or agenda entry and try to associate a project

**Comment by atm-maxime** [comment]
I checked on a v15, when I try to create a new invoice, the project list shows all non closed projects (and draft are visible but not selectable). It's the same on all other forms.
But on a new event, the list only shows open projects with no thirdparty. So it seems that the project list on a new event must be fixed.

**Comment by atm-maxime** [comment]
I can't reproduce on a 14.0.5
