### ISSUE TITLE
Expedition not set as billed in database

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#20987]
### Bug

When an invoice is created from a shipment (expedition), the column "billed" in llx_expediton remains with a value 0 instead of 1

### Environment Version

14.0.4, 15.0.2

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.4

### Expected and actual behavior

When an invoice is created from the expedition card, the column value of llx_expedition.billed should be changed to 1

### Steps to reproduce the behavior

Create order, create a shipment from order, create invoice from shipment.

**Comment by eldy** [comment]
Invoice is in module Invoice
Shipment is in module shipment.
So to have shipment status modified on invoice creation, you may use the workflow module. Did you enable the module ? If yes, did you try to enabled the option "Classify linked source shipment as closed when customer invoice is validated (and if the amount of the invoice is the same as the total amount of the linked shipments)"

**Comment by milenmk** [comment]
Sometimes, there is a workflow, where you create a shipment, then create an invoice and validate this invoice. But the items are NOT shipped yet. So, at a later stage, when the warehouse ship the items they classify the shipment as "Closed (sent)". I.e. you can have an invoice when the shipment is not yet processed. Thus, when you create an invoice, the shipment should be set as billed but NOT closed. I see it is fixed already as suggested and I hope you get my point of view.

**Comment by atm-maxime** [comment]
Maybe there are missing status on the shipment object : shipped and delivered.
And you're right, the billed status (0/1) should be separated from the shipment status, just as it's done on the order object.
Maybe open a new feature request issue ?
