### ISSUE TITLE
Multiple payment lines on one expense report

### ISSUE THREAD

**Issue by atm-benoit** [Dolibarr/dolibarr#20995]
### Feature Request
In order to facilitate the entry of payments on the expense reports, ATM proposes to set up the following elements and to propose them to the community. This work has been done in consultation with  @ludovicandrieux from Nysis. Your comments are welcome.

Link to the Dolibarr French forum thread for the feature : https://www.dolibarr.fr/forum/t/evolution-note-de-frais-plusieurs-lignes-de-paiement-sur-une-note-de-frais/40139

### Use case

When entering a payment for an expense report, all payments for this user will be listed so that it is possible to enter a payment for several expense reports (as is the case for invoices for example). Only the approved expense reports of the same user and being in the "Approved" status or having a remaining amount to pay will be grouped together.

### Suggested steps

**MODIFICATION OF THE "EXPENSE REPORT" MODULE**
The expense report module will be modified as follows:

* On the "Enter a payment" page, one line per expense report for the same user will be added.

* When entering multiple expense reports, the status of each report will change.

![image](https://user-images.githubusercontent.com/74977238/169800209-2ea58890-fba8-4ffe-b77c-a2938bf1f322.png)

**Comment by atm-gauthier** [comment]
PR : https://github.com/Dolibarr/dolibarr/pull/23154
