### ISSUE TITLE
Third party standardization in lists

### ISSUE THREAD

**Issue by atm-benoit** [Dolibarr/dolibarr#21000]
### Feature Request

In order to standardize how the columns "Third party" and "Alternative name" are displayed on lists, ATM proposes to set up the following elements and to propose them to the community. This work has been done in consultation with @ludovicandrieux from Nysis. Your comments are welcome.

### Use case

Dolibarr lists must display the column "Alternative name" as soon as the name of the third party is present. If the column is not displayed, the alternative name will be added after the third party in parentheses.

### Suggested steps

**CHANGES MADE**

- Addition of the column "Alternative name" in the following lists:
  - Supplier invoices
  - Supplier sales proposals
  - Supplier orders
  - Projects
  - Tasks
  - Time reported 

If the column is not displayed, the alternative name must appear between parentheses (see example on invoices below).
![image](https://user-images.githubusercontent.com/74977238/169846635-c6927d13-ee28-43b3-b881-490140df482d.png)

**Comment by eldy** [comment]
@atm-benoit It's ok for me.
Note that the PR has been already implemented and suggested by @fboitel
