### ISSUE TITLE
Extrafields Computed Fields not working in V15.x

### ISSUE THREAD

**Issue by Beta555** [Dolibarr/dolibarr#21025]
### Bug

After upgrading from 14.0.5 to 15.0.1 and 15.0.2, certain computed fields are blocked by the DOL_EVAL function.

This means that these constructs in the computed field don't work anymore:

 `'TechID = '.$object->id`
```
$result = $db->query('SELECT sp.firstname AS Firstname, sp.lastname AS Lastname, soc.nom AS Companyname
FROM llx_socpeople AS sp INNER JOIN llx_societe AS soc ON sp.fk_soc=soc.rowid
WHERE sp.rowid='.$ContactID.';')
```

The function DOL_EVAL now contains this line (linenr 8249 in V15.0.2), blocking the dot character in these cases:
`  if (preg_match('/[^0-9]+\.[^0-9]+/', $s)) {	// We refuse . if not between 2 numbers`

This bug is directly related to [#20373](https://github.com/Dolibarr/dolibarr/issues/20373)

### Environment Version

V15.0.0, V15.0.1,  V15.0.2, V15.0.3

### Environment OS

Windows Server

### Expected and actual behavior

Computed Field in Proposal | Complementary Attributes: `'TechID = '.$object->id`
Expected (in V14.0.5): TestField: `TechID = 137`
Result (in V15.0.2): TestField: `Bad string syntax to evaluate (dot char is forbidden): 'TechID = '.$object->id`

### Steps to reproduce the behavior

Create a complementary attribute in Proposal:
Name: Testfield
Attribute: testfield
Type: String
Computed Field: `'TechID = '.$object->id`
Visibility: 1

Now open or create a proposal. Testfield will now show: `Bad string syntax to evaluate (dot char is forbidden): 'TechID = '.$object->id`

**Comment by atiyab** [comment]
Possible workaround is using php join and array functions, eg:
`join(' ',array('TechID =',$object->id))`
or
`join(" ",array("TechID =",$object->id))`

**Comment by StephaneLesage** [comment]
Same problem here.
Computed fields are unusable.

**Comment by lucky4ever2** [comment]
We also have problem with dots in Extrafields.
We want the german number format with the following php code: `number_format( $object->total_ttc/4, 2, ',', '.')`
In V14.x.x= 6.304,56
In V15/V16= Bad string syntax to evaluate (dot char is forbidden): number_format( $object->total_ttc/4, 2, ',', '.')
Without a fix we cannot update our version >14

**Comment by sonikf** [comment]
Same problem here.

In Greece we are using a custom contributed module to upload invoice data to the Greek IRS and this bug is affecting greatly those of us using computed fields.

**Comment by daxitsolutions** [comment]
Problem still present in v16

Try add a calculated value in an extra ayttribute in object commande (Order) with : 

`mysqli_fetch_array($resql = $db->query('SELECT fk_warehouse from llx_commande commande WHERE rowid='.$object->id))["fk_warehouse"];`

-> error will occurs
Bad string syntax to evaluate (dot char is forbidden)

**Comment by hregis** [comment]
@eldy this is the line 8266 of "/core/lib:functions.lib.php" of branch 15 wich is problematic

```
if (preg_match('/[^0-9]+\.[^0-9]+/', $s)) {	// We refuse . if not between 2 numbers
		if ($returnvalue) {
			return 'Bad string syntax to evaluate (dot char is forbidden): '.$s;
		} else {
			dol_syslog('Bad string syntax to evaluate (dot char is forbidden): '.$s);
			return '';
		}
	}
```

**Comment by lucky4ever2** [comment]
In germany we need the dot to display that is a 1.000

**Comment by DavidHamelin** [comment]
Same issue in version 17.0.1...

**Comment by ghwaldo** [comment]
Still the same in 20.

Dolibarr is awesome work, thank you, but why is this behaviour so hard coded ?
I only want to format date with "d.m.Y" ?!

**Comment by Gouttfi** [comment]
Hi,

It is very very hard to have working calculated field, because the slightest character is restricted.
It is no longer possible to do any var_dump(), any debug. All of my calculated fields are broken and the documentation has not been updated at all.

What solutions do we have available?
