### ISSUE TITLE
Bug Creating proposal with language de_ch

### ISSUE THREAD

**Issue by HB9GSL** [Dolibarr/dolibarr#21046]
### Bug

When de_ch ist set as language. The Radiobuttons to add products to proposals wont show. If you change the language to de_de they are present. 

### Environment Version

15.0.2

### Environment OS

Ubuntu22

### Environment Web server

apache

### Environment PHP

8.1

### Environment Database

mysql

### Expected and actual behavior

Radiobuttons to chose an predefined product or a freetext product should be present.

### Steps to reproduce the behavior

Change language to de_ch and make a new proposal.

**Comment by daraelmin** [comment]
Hi,
Could you add screenshot of both situation please
Cheers
