### ISSUE TITLE
Error creating client specific prices

### ISSUE THREAD

**Issue by mpractic** [Dolibarr/dolibarr#21040]
### Bug

I can't create client specific prices for products and services since v15.

### Environment Version

15.0.2

### Environment OS

Ubuntu 20.04.4 LTS

### Environment Web server

Apache/2.4.41 (Ubuntu)

### Environment PHP

7.4.3

### Environment Database

 5.5.5-10.3.34-MariaDB-0ubuntu0.20.04.1

### Environment URL(s)

/product/price.php

### Expected and actual behavior

Should be able to create client specific prices for products and services but I can't. 

Appearing error:

`Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':-15:-9, 1, NULL)' at line 1`

On Database debug:
`INSERT INTO llx_product_customer_price(entity,datec,fk_product,fk_soc,ref_customer,price,price_ttc,price_min,price_min_ttc,price_base_type,default_vat_code,tva_tx,recuperableonly,localtax1_type,localtax1_tx,localtax2_type,localtax2_tx,fk_user,import_key) VALUES ( 1, '2022-05-26 13:39:13', '128', '1', '', '200', '242', 0, 0, 'HT', null, 21, '0', '3', 5.2, '5', -19:-15:-9, 1, NULL)
[DB_ERROR_SYNTAX] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':-15:-9, 1, NULL)' at line 1`

**Comment by ibuiv** [comment]
![image](https://user-images.githubusercontent.com/50403308/204059555-a26ceb13-1fb5-4c35-a0a0-34a4d4c9fe9a.png)

Can't reproduce it in 15.0.3
