### ISSUE TITLE
Bug: Product - cannot add or change the note, neither public note nor private note

### ISSUE THREAD

**Issue by webgras** [Dolibarr/dolibarr#21057]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
I am editing a product but I cannot add/change the field "note". 

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.28
- **Database**: MySQL or MariaDB 5.5.5-10.5.15-MariaDB-1:10.5.15+maria~focal-log
- **URL(s)**: /product/note.php?id=92

## Expected and actual behavior
I want to see the small edit icon or the field in the edit form.

## Steps to reproduce the behavior
open a product/service and click "edit/change". there is no field for the "note".
Or click on the tab "Note", the field is not editable.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![grafik](https://user-images.githubusercontent.com/10774704/171044657-5be240f7-407b-424b-afd3-233e01ccfce2.png)

**Comment by priojk** [comment]
In 15.0.1 (don't have a v14 here for testing), there is a pencil icon displayed next to the public and private note fields:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/10772984/171056519-4faf7771-13f6-4dd2-9dde-90ebcc462c5c.png">

So, it seems to be fixed in v15.

**Comment by webgras** [comment]
I upgraded to 15.0.2 but the icon is still missing.
I did some further tests.

I have only "Services" active, but the module "Products" is not active. (I am not selling products, only services).
When I activate "Products", then I see the pencil icon.
If I deactivate "Produts", then the pencil is missing.

**Comment by tmulzer** [comment]
Still the case in 16.0.3 .. even if product module is active.
I'm not sure if 16.0.0 had that error .. I think, I have been able to attach some notes to products.

**Comment by fradir** [comment]
We have the same issue. I had the feeling that this bug was reimplemented with the upgrade from 16.0.2 to 16.0.3. The pencils are missing.

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
