### ISSUE TITLE
Product ID set to NULL when changing currency or updating rate for Supplier invoice

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#21063]
### Bug

When creating a Supplier invoice, if you add some products and then change the currency or update the currency rate, the product ID is set to 0.

Browsing the logs, I see that when updating lines the "fk_product" is set to NULL. In `fournisseur.facture.class.php`, method `public function updateline( ...` has `$idproduct = 0`. This causes all the code that follows to have no product ID. Possible solution (tested and working):

Change this:

```
		if ($idproduct) {
			$product = new Product($this->db);
			$result = $product->fetch($idproduct);
			$product_type = $product->type;
		} else {
			$product_type = $type;
		}

		//Fetch current line from the database and then clone the object and set it in $oldline property
		$line = new SupplierInvoiceLine($this->db);
		$line->fetch($id);
		$line->fetch_optionals();

		$staticline = clone $line;
``` 

to this:

```
		 /*
		if ($idproduct) {
			$product = new Product($this->db);
			$result = $product->fetch($idproduct);
			$product_type = $product->type;
		} else {
			$product_type = $type;
		}
		*/

		//Fetch current line from the database and then clone the object and set it in $oldline property
		$line = new SupplierInvoiceLine($this->db);
		$line->fetch($id);
		$line->fetch_optionals();

		$staticline = clone $line;

        if ($idproduct) {
            $product = new Product($this->db);
            $result = $product->fetch($idproduct);
            $line->fk_product = $idproduct;
            $product_type = $product->type;
        } else {
            $line->fk_product = $staticline->fk_product;
            $product_type = $type;
        }
```

add remove line `$line->fk_product = $idproduct;` further below.

### Environment Version

14.0.4 - 15.0.3

### Environment OS

Windows/Ubuntu

### Environment Web server

11/20.0.4

### Environment PHP

7.4

### Expected and actual behavior

When changing currency or updating the rate product ID should be kept

### Steps to reproduce the behavior

Create supplier invoice, add product and change currency OR update rate

**Comment by josett225** [comment]
Hi All

is there a way to get this fix in version 14 ?

Best Regards

**Comment by milenmk** [comment]
> Hi All
> 
> is there a way to get this fix in version 14 ?
> 
> Best Regards

Have you tried manually making the changes described above?

**Comment by milenmk** [comment]
Fixed

**Comment by josett225** [comment]
Hi @milenmk 

Yes I did it and it works with the modified code.
