### ISSUE TITLE
Add automatic supplier ordering to MRP

### ISSUE THREAD

**Issue by fbosman** [Dolibarr/dolibarr#21060]
### Feature Request

Add a function that calculates the needed stock per BOM-line for the requested number of products to be build and create concept supplier orders based on the shortages.

### Use case

Enable the user to minimize the stock for the BOM-lines and to reduce the work needed for gathering the needed elements for the build.

### Suggested implementation

Ad a new card with the calculated needs and enable to order these line by line.

### Suggested steps

Create card with needed stocks
Create concept supplier orders

**Comment by josett225** [comment]
Still required
