### ISSUE TITLE
Can't auto-caculate " Price quantity min. " when enable multi-currency module

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#21071]
### Bug

Can't auto caculate " Price quantity min. " when enable multi-currency module .
If conversion rate is bigger than 0.5 (as testing , it become 1 when it auto-caculate the price . Below 0.5 , then it will become 0 . ) , then  it can auto-caculate " Price quantity min. " .
![image](https://user-images.githubusercontent.com/78349579/171197159-cdf0e29f-e871-4de3-942e-4a95395deb5d.png)
![image](https://user-images.githubusercontent.com/78349579/171197287-23cfb99b-fe51-41c7-8e84-33f29e59151e.png)

### Environment Version

v 14.0.3 and v15.0.2

### Environment OS

Deian 11 windows 7

### Environment Web server

Apache/2.4.38 Apache/2.4.41

### Environment PHP

7.4.28

### Environment Database

5.5.5-10.5.15-MariaDB-0+deb11u1

### Environment URL(s)

/product/fournisseurs.php?id=276&action=add_price&token=f3e8e9b221d1cb68a7f9875572737f39

### Expected and actual behavior

Should could auto-caculate " Price quantity min. " .

### Steps to reproduce the behavior

Enable multi-currency module and add different currency to test .

**Comment by inoveaconseil** [comment]
I can't reproduce
