### ISSUE TITLE
Function "getChildsArbo" from Product did not give all sub products from a kit

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#21094]
### Bug

Example in the screenshot bellow 

Function "getChildsArbo" doesn't give the right result when the following case occurs 
- Product_1 : Has Product_3 and Product_2  as child 
- Product_2 : Has Product_3 and Product_4 as child 

Current result of the function is : 
Product_1
-> product_3
-> product_2
--> product_4

instead of 
Product_1
-> product_3
-> product_2
--> product_3
--> product_4

In the tree, we do not see the right amount of quantity because product_3 can be part of product_1 ans part of product 2

How to patch : 
**/product/class/product.class.php - Line 4688**
Remove "continue statement" 
`if (!empty($alreadyfound[$rec['rowid']])) {
					dol_syslog(get_class($this).'::getChildsArbo the product id='.$rec['rowid'].' was already found at a higher level in tree. We discard to avoid infinite loop', LOG_WARNING);
					continue;}`

### Environment Version

14.0.4

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

Mysql

### Environment URL(s)

https://XXXX.com/expedition/shipment.php?id=XXX

### Attached files

![Image_1_06_22_21_05_collée](https://user-images.githubusercontent.com/26635105/171490837-5b58fe19-d450-4863-b5a0-7ea290e3c387.png)

**Comment by eldy** [comment]
@daxitsolutions Can you confirm that the bug is fixed with the PR #21184 ?
