### ISSUE TITLE
Payment is not exchange in different currencies

### ISSUE THREAD

**Issue by artemChernitsov** [Dolibarr/dolibarr#21111]
### Bug

In our company, we have 2 currencies, USD and UAH. 
When I have a Vendor invoice in USD $74.39 and in Bank entries in the bank account in UAH I see value in USD, not in UAH $74.39 * 29.5 = 2194,51UAH.
Module Multi-currency is enabled https://tppr.me/kPPN5.
This bug reproduced in all modules - Accounting, Bank|Cash, Billing|Payment, etc.

### Environment Version

15.0.3

### Environment OS

Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64

### Environment Web server

nginx/1.17.6

### Environment PHP

7.2.24-0ubuntu0

### Environment Database

PostgreSQL 10.21 (Ubuntu 10.21-0ubuntu0.18.04.1)

**Comment by artemChernitsov** [comment]
Also, have a bug with bank entries, it doesn't calculate in bank account currency.

**Comment by josett225** [comment]
Still valid

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by michalhana99** [comment]
unfortunately even in version 18.0.3 this problem persists, when will this error be fixed?
