### ISSUE TITLE
Lenteur = montant 0 (Bug ?)

### ISSUE THREAD

**Issue by webolabo** [Dolibarr/dolibarr#21130]
### Bug

Bonjour,
On utilise Dolibarr sur un serveur web qui pourrait parfois rencontrer un peu de lenteur

Quand il y a des lenteurs et que l’agent effectue les actions rapidement ça crée un très grand problème que nous avons constaté à partir de la V15 (Il n’existait pas dans la V11)

Au fait dans les Propales et les Factures nous avons beaucoup de lignes avec montant 0 ce qui nous a créé beaucoup de problèmes avec nos clients qui ont pensé que c’était une remise :smiley:
Reproduire l’erreur : Sélectionner un produit et appuyer rapidement sur le bouton ajouter

Bien cordialement

### Environment Version

15

### Steps to reproduce the behavior

Sélectionner un produit et appuyer rapidement sur le bouton ajouter

**Comment by emheyarssi** [comment]
Please write in english. Thanx

**Comment by ksar-ksar** [comment]
Hi,

Some answers have been provided to you on the forum : https://www.dolibarr.fr/forum/t/lenteur-montant-0-bug/40254
