### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by fakumpule** [Dolibarr/dolibarr#21132]
[Payroll.docx](https://github.com/Dolibarr/dolibarr/files/8838245/Payroll.docx)
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[Employee List Does not Displaying]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1
- **URL(s)[**: /custom/paiedolibarr/card.php?action=add](https://assisifoodsltd.with4.dolicloud.com/custom/paiedolibarr/card.php?action=add)

## Expected and actual behavior
[In not able to select Emplyee created within the userlist to make up the payroll]

## Steps to reproduce the behavior
[1. Employee Payroll 
2. New Payroll]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
[Payroll.docx](https://github.com/Dolibarr/dolibarr/files/8838251/Payroll.docx)

**Comment by hregis** [comment]
@fakumpule this is an external module, contact the developer of this module

**Comment by fakumpule** [comment]
Thanks
