### ISSUE TITLE
Trouble seems partially fixed after the merge.

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#21139]
Trouble seems partially fixed after the merge.
If i remove an assignement from the tab "Contact", it is not removed on the ticket card.
Also if i assign 2 guys form contact tab (one contributor, one use rassigned), if i modified use rassigned from the ticket, all are removed, even if the other assignement has the type "Contributor" and not "User assigned". We should removed only link for "User assigned".
Can you check @FHenry the PR merge ?

_Originally posted by @eldy in https://github.com/Dolibarr/dolibarr/pull/19426#issuecomment-1148420893_

**Comment by FHenry** [comment]
@eldy ok new PR fix it
