### ISSUE TITLE
error when try import task 

### ISSUE THREAD

**Issue by julbroa** [Dolibarr/dolibarr#21138]
### Bug

when try import task to project, always get the same error
![image](https://user-images.githubusercontent.com/105558823/172285801-9f85b8fe-6cac-45ca-b734-6a02dc76e7e0.png)
i try change ref of project to numbre of id in url and name's project give to the system of dolibarr but get the same error.
as for creation date, start date and end date I have directly written the values in xls as text with the requested format and in csv in the same way but the problem is not solved.

### Environment Version

15.0.2

### Environment OS

Linux us-imm-web398.main-hosting.eu 4.18.0-305.12.1.lve.el7h.x86_64 #1 SMP Tue Aug 17 03:13:08 EDT 2021 x86_64

### Environment Web server

LiteSpeed

### Environment PHP

8.0.7

### Environment Database

MySQL or MariaDB 5.5.5-10.5.12-MariaDB-cll-lve

### Environment URL(s)

https://gestion.compusya.com/htdocs/imports/import.php?&leftmenu=import&format=xlsx&datatoimport=tasksofprojects&filetoimport=20220606211132-importacion+tareas+prueba.xlsx&nboflines=2&separator=%2C&enclosure=%22

### Attached files

![image](https://user-images.githubusercontent.com/105558823/172286898-f23b5fa7-86a1-45f9-8889-509ccf8ad0d0.png)

**Comment by priojk** [comment]
I think v15.0.2 is not fully compatible with php8, maybe you could test the behaviour with php7.4?

**Comment by julbroa** [comment]
i changed php version to 7.4 but get same error

**Comment by eldy** [comment]
> i changed php version to 7.4 but get same error

You try to import the line 1 of your file that are comments, you must set your import to start to line 2.
