### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by fakumpule** [Dolibarr/dolibarr#21133]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Pointing of Staff Page Not Displaying
[Doc1.docx](https://github.com/Dolibarr/dolibarr/files/8838265/Doc1.docx)
 *]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1
- **URL(s)[**: /custom/grh/pointage/listtime.php?idmenu=133&mainmenu=grh&leftmenu=
](https://github.com/Dolibarr/dolibarr/issues/new?labels=Bug&title=Bug%3A+&body=%23+Instructions%0A%2AThis+is+a+template+to+help+you+report+good+issues.+You+may+use+%5BGithub+Markdown%5D%28https%3A%2F%2Fhelp.github.com%2Farticles%2Fgetting-started-with-writing-and-formatting-on-github%2F%29+syntax+to+format+your+issue+report.%2A%0A%2APlease%3A%2A%0A-+%2Areplace+the+bracket+enclosed+texts+with+meaningful+information%2A%0A-+%2Aremove+any+unused+sub-section%2A%0A%0A%0A%23+Bug%0A%5B%2AShort+description%2A%5D%0A%0A%23%23+Environment%0A-+%2A%2AVersion%2A%2A%3A+14.0.5%0A-+%2A%2AOS%2A%2A%3A+Linux%0A-+%2A%2AWeb+server%2A%2A%3A+Apache%2F2.4.41+%28Ubuntu%29%0A-+%2A%2APHP%2A%2A%3A+apache2handler+7.4.3%0A-+%2A%2ADatabase%2A%2A%3A++5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1%0A-+%2A%2AURL%28s%29%2A%2A%3A+%2Fcustom%2Fgrh%2Fpointage%2Flisttime.php%3Fidmenu%3D133%26mainmenu%3Dgrh%26leftmenu%3D%0A%0A%23%23+Expected+and+actual+behavior%0A%5B%2AVerbose+description%2A%5D%0A%0A%23%23+Steps+to+reproduce+the+behavior%0A%5B%2AVerbose+description%2A%5D%0A%0A%23%23+%5BAttached+files%5D%28https%3A%2F%2Fhelp.github.com%2Farticles%2Fissue-attachments%29+%28Screenshots%2C+screencasts%2C+dolibarr.log%2C+debugging+informations%E2%80%A6%29%0A%5B%2AFiles%2A%5D%0A%0A%0A%23%23+Report%0A)

## Expected and actual behavior
[*THE HRM MANEGEMENT pointing of staff link does not display*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by hregis** [comment]
@fakumpule this is an external module, contact the developer of this module.

**Comment by fakumpule** [comment]
Thanks
