### ISSUE TITLE
In accounting, you can no longer insert manual lines

### ISSUE THREAD

**Issue by klausking** [Dolibarr/dolibarr#21150]
### Bug

In accounting, you can no longer insert manual lines if you transfer automatically created transactions to the general ledger, this was possible before.
However, this function is important for bookkeeping, especially in order to be able to post taxes correctly afterwards.
Without a feature to add manual lines for automatically generated transactions, accounting is unfortunately useless.

### Environment Version

15.0.2 

### Environment Web server

Apache/2.4.38 

### Environment PHP

7.3.31-1~deb10u1

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0+deb10u1

### Expected and actual behavior

Previously, there was a button to manually insert new lines in accounting.

(In the case of automatically transferred transactions to the general ledger) 

### Attached files

[example.pdf](https://github.com/Dolibarr/dolibarr/files/8855815/example.pdf)

**Comment by priojk** [comment]
The button with label "Add" on accountancy/bookkeeping/card.php ist present in v15.0.1 and indeed missing in develop (could not check 15.0.2). This would be a major change in behaviour between 15.0.1 and 15.0.2. 

Looking quickly at the source, it is still there, but not shown on the page. Probably this is related to some work trying to avoid empty lines under certain circumstances.

@daraelmin worked on this, so maybe he can confirm, if this is the desired behaviour or rather a regression.

I fully support the point that prior to validating a transaction, it can make sense to manually add additional accounting lines, e.g. moving VAT form a VAT due account to a VAT undue account is such a topic in Germany, depending on whether a company is VAT-taxed by invoice date or by payment date.

**Comment by daraelmin** [comment]
It was certainly not a feature so it is a regression. I'm working on it now.

**Comment by daraelmin** [comment]
Hope it's better

**Comment by priojk** [comment]
For me the patch is working great. Thanks for your quick reaction!

**Comment by klausking** [comment]
Perfect, not even million dollar companies can offer better support, absolutely great!
