### ISSUE TITLE
warning "undefined...."   php 8

### ISSUE THREAD

**Issue by webmasterproxy-media** [Dolibarr/dolibarr#21153]
### Bug

Some warnings on test

### Environment Web server

Apache/2.4.51 (Win64) PHP/8.1.0

### Environment PHP

 8.1.0

### Attached files

![Screenshot 2022-06-08 at 08-15-01 Tags_catégories](https://user-images.githubusercontent.com/30132548/172547459-4a0efc35-8822-4427-a083-c236f3729323.png)
![Screenshot 2022-06-08 at 08-16-09 Tiers](https://user-images.githubusercontent.com/30132548/172547462-1fa92840-be32-4299-ac1e-80233de7e8f4.png)
![Screenshot 2022-06-08 at 08-16-53 Statistiques sur les produits _ services](https://user-images.githubusercontent.com/30132548/172547464-f551320f-59ce-4170-aaf7-1ded5e0fedd6.png)
![Screenshot 2022-06-08 at 08-17-58 Proposition commerciale - Fiche](https://user-images.githubusercontent.com/30132548/172547466-4348d084-92c9-4956-a1d2-bcb479e626e4.png)
![Screenshot 2022-06-08 at 08-18-57 Intervention](https://user-images.githubusercontent.com/30132548/172547467-d5b70f0e-366e-4c3b-9e78-69358790c7df.png)
![Screenshot 2022-06-08 at 08-19-30 Modèle d'intervention](https://user-images.githubusercontent.com/30132548/172547468-c6c32370-6a37-46c9-adbb-1367802c4af4.png)
![Screenshot 2022-06-08 at 08-20-07 Facture client - Fiche](https://user-images.githubusercontent.com/30132548/172547470-8ec80aa7-e064-4394-922f-ce65a2c92ffd.png)
![Screenshot 2022-06-08 at 08-21-26 Agenda](https://user-images.githubusercontent.com/30132548/172547476-6a8491ac-e2af-4cf7-8b2b-ce0276b3f718.png)
![Screenshot 2022-06-08 at 08-21-42 Créer ticket](https://user-images.githubusercontent.com/30132548/172547479-53cf6d98-43b8-432e-ab1d-783b14a61ab3.png)

**Comment by trekmorris** [comment]
What is your dolibarr version ?
