### ISSUE TITLE
MySQL Error in facture/stats

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#21162]
### Bug

When pulling stats in invoices with tag filters (otherwise it works), a MySQL error is thrown back.

### Environment Version

15.0.1

### Environment OS

Ubuntu Server 20.04.4 LTS

### Environment Web server

Apache 2.4.1

### Environment PHP

php 7.4.3

### Environment Database

mysql 8.0.29

### Environment URL(s)

https://mydomain.com/compta/facture/stats/index.php

### Expected and actual behavior

Expected: Show filtered results
Actual: MysqL Error

### Steps to reproduce the behavior

Add a criteria to the filters:
Select Tag
Execute report

Bug shows as follow:
Modules/Applications: twofactorauth, api, memcached, user, syslog, subtotal, cdav, propal, ficheinter, contrat, expedition, supplier_proposal, reception, incoterm, tax, loan, product, productbatch, stock, projet, categorie, fckeditor, multicurrency, import, export, socialnetworks, autoattachfile, extdirect, ecotaxdeee, abricot, extraprice, advanceddiscount, intracommreport, accounting, agenda, bom, banque, barcode, cron, commande, expensereport, facture, fournisseur, holiday, margin, mrp, printing, resource, salaries, service, societe, stripe, ticket, variants
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT date_format(f.datef,'%m') as dm, COUNT(*) as nb FROM llx_facture as f LEFT JOIN llx_categorie_societe as cat OmdN (f.fk_soc = cat.fk_soc) WHERE f.datef BETWEEN '2020-01-01 00:00:00' AND '2020-12-31 23:59:59' AND f.fk_statut >= 0 AND f.entity IN (1) AND (f.fk_statut <> 3 OR f.close_code <> 'replaced') AND f.type IN (0,1,2,3,5) AND cat.fk_categorie IN (11) GROUP BY dm ORDER BY dm DESC
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OmdN (f.fk_soc = cat.fk_soc) WHERE f.datef BETWEEN '2020-01-01 00:00:00' AND '20' at line 1

When looking at the SQL, it looks like the join syntax is corrupted:

LEFT JOIN llx_categorie_societe as cat **OmdN** (f.fk_soc = cat.fk_soc)

I believe it shoud read **ON** instead.

A quick and dirty test with the corrected syntax in the SQL console actually works properly.

**Comment by ksar-ksar** [comment]
Hello,

First thing to do is to upgrade to V15.0.2 ?

**Comment by dom-breizh** [comment]
Upgrading to 15.0.2 fixed the problem.
Thanks
