### ISSUE TITLE
Duplicate product in invoice

### ISSUE THREAD

**Issue by bardieldj** [Dolibarr/dolibarr#21173]
### Bug

Duplicate product in invoice

### Environment Version

15.2

### Environment OS

windows 10

### Environment Web server

Apache24

### Environment PHP

7.4

### Environment Database

MarianaDB

**Comment by atm-maxime** [comment]
Hi @bardieldj 
A little more explanation (url, step to reproduce, screenshot, ...) might help understand your issue.
Also, the 15.2 version of Dolibarr doesn't exist, maybe you mean 15.0.2 ? And can you tell us more about MarianaDB ? 😉
