### ISSUE TITLE
La note public n'est pas sauvegardée dans les factures client

### ISSUE THREAD

**Issue by xmillies** [Dolibarr/dolibarr#21199]
### Bug

Le formulaire envoi l'action "editnote_public" mais visiblement, il n'y a pas de traitement / action associée ....

grep -R editnote_public *
comm/propal/note.php:           //if ($action == 'editnote_public') $cssclass='titlefieldcreate';
contact/note.php:       //if ($action == 'editnote_public') $cssclass='titlefieldcreate';
product/note.php:       //if ($action == 'editnote_public') $cssclass='titlefieldcreate';
societe/note.php:       //if ($action == 'editnote_public') $cssclass='titlefieldcreate';

### Environment Version

15.0.2

### Environment OS

Linux / Centos 

### Environment Web server

nginx

### Environment PHP

8.1

### Environment Database

mysql

### Environment URL(s)

compta/facture/note.php?action=editnote_public&token=xxxxxxx&id=204

### Steps to reproduce the behavior

Editer une note publique sur une facture

**Comment by emheyarssi** [comment]
Unable to reproduce.

**Comment by ksar-ksar** [comment]
Hi,

Same issue here : https://www.dolibarr.org/forum/t/public-notes-update-error/22411

**Comment by xmillies** [comment]
Could I add a trace ?

**Comment by xmillies** [comment]
For instance

** Request headers**
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,et;q=0.6,de;q=0.5,gl;q=0.4
Cache-Control: no-cache
Content-Length: 113
Content-Type: application/x-www-form-urlencoded
Cookie: DOLSESSID_c6af89d08176aa3cb547b3ba70300faa=b49d2fa6bdf7a5afd37a25b7c56439cf; DOLSESSID_790a29d25fcec832542dad5fa9dc3d2a=0a48460cce576fc95a21da2f33d5f077
Host: www.xaneo.fr
Origin: http://xxxxxxxxxxxxxxxxxx
Pragma: no-cache
Proxy-Connection: keep-alive
Referer: http://xxxxxxx/compta/facture/note.php?action=editnote_public&token=xxxxxxxxxxxxxxxxxxxxx&id=204
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36

**Payload*** 

action: setnote_public
token: xxxxxxxxxxxxxxxxxxxxxxxx
id: 204
note_public: My new public note
modify: Modifier

Is it normal to have two sessions cookies for Dolibarr : DOLSESSID cookies ?

**Comment by xmillies** [comment]
I remove the cookies and tried again.
Fresh session : same issue.

**Comment by xmillies** [comment]
The payload and the GET parameters differ : setnote_public and editnote_public ......

**Comment by xmillies** [comment]
$_GET
array:3 [
  "action" => "editnote_public"
  "token" => "d9b96536599b77850626f34599f84316"
  "id" => "204"
]
$_POST
array:5 [
  "action" => "setnote_public"
  "token" => "d9b96536599b77850626f34599f84316"
  "id" => "204"
  "note_public" => "qsdf"
  "modify" => "Modifier"
]

**Comment by edupulpillo** [comment]
I can not reproduce it in 15.0.2, i can save properly the public notes in he customer invoices.

**Comment by xmillies** [comment]
> I can not reproduce it in 15.0.2, i can save properly the public notes in he customer invoices.

Same GET and POST ?

**Comment by edupulpillo** [comment]
Just using the web interface

**Comment by xmillies** [comment]
> Just using the web interface

Could you use debug toolbar and see GET and POST values ?
