### ISSUE TITLE
wage settlement 

### ISSUE THREAD

**Issue by fakumpule** [Dolibarr/dolibarr#21207]
### Bug

This page isn’t working right nowassisifoodsltd.with4.dolicloud.com can't currently handle this request.
HTTP ERROR 500

### Attached files

[wage settlement.docx](https://github.com/Dolibarr/dolibarr/files/8884448/wage.settlement.docx)

**Comment by atm-maxime** [comment]
So please contact dolicloud, it's your Dolibarr provider, through your customer portal.
