### ISSUE TITLE
Make payments on Proposals and Orders without creating a Down payment invoice

### ISSUE THREAD

**Issue by lemathou** [Dolibarr/dolibarr#21205]
### Feature Request

Make payments on Propal and Orders without creating a Down payment invoice, but simply recording the payment, and create associate it properly when an invoice is created

### Use case

My client receives a lot of down payments on proposals. He doesn't want to multiply invoices, don't want to use Down payment invoices, and has sometimes to create invoices only when the goods are shipped... and he wants his proposals to be paid and payments to be correctly recorded.

### Suggested implementation

In fact, I already did it. Added Hooks, Database tables (paiment_object to link paiement with proposals and orders, paiement_extrafields to add extrafields relatives to payment mean, transaction number, etc.) and used MBIEtransactions module for payments (my clients had already this payment mean activated on his Prestashop). Also added informations for payment by cheque and bank transfer, and sends email with informations.

### Suggested steps

I can publish a PR with juste a few hooks, and two modules (one to adapt payments to proposals and orders with new hooks), and one to use it with my adapted version of mbietransations.

**Comment by hasse-basse** [comment]
Hmm... I'm sure I've done exactly that earlier, but I can't do it now. Something have happend and I can't figure out what.
