### ISSUE TITLE
Add button to create new agenda in Third Parties List View

### ISSUE THREAD

**Issue by aceitldh** [Dolibarr/dolibarr#21211]
### Feature Request

While scrolling down the third parties list we wish to create new agenda on the same screen. 

### Use case

when we scroll through all our prospects we get reminded immediately that we should create new agenda for this prospect and again for another prospect. There should be a "create agenda" button in front of Party name and when we press it a new small pop window should open where we can create agenda and when completed we are again on the same list view on parties. This can make dolibarr more useful in terms of CRM.

Thanks

**Comment by atm-maxime** [comment]
Why not as an option, but if your need is to have a shortcut to create an event from the list, others would want to create a proposal, or an invoice, or a ticket, or something else related to their own use of Dolibarr.

In v16 there's a new icon on the top right menu. A "+" sign to quickly create any element in Dolibarr. Why not adding this feature in the third party list.

**Comment by aceitldh** [comment]
when we have opened list of prospects and then we press "+" sign on the top right it opens windows to add new prospect. Same is the case with agenda list view, if we press "+" it opens window to add new agenda. 
Our requirement is that we have suppose 500 prospects and we are on the 10 page, we are scrolling through all our prospects and then reminded of that we should create event for this very party instantly and at that time "+" sign in front of party line is very useful, it can be customizable button, one can create agenda, invoice, ticket or something else from there.

**Comment by atm-maxime** [comment]
Agreed, a + sign on the third party line would be useful
