### ISSUE TITLE
Missing French translation for "Payment method"

### ISSUE THREAD

**Issue by omogenot** [Dolibarr/dolibarr#21254]
### Bug

There seem to miss a French translation for the term `Payment method` shown in many screens.

### Environment Version

15.0.2

**Comment by daraelmin** [comment]
Hi,

Can you provode at les one URL relatés to this issue ?

Thx

**Comment by atm-maxime** [comment]
Translation are done on transifex and a sync is made before a release

**Comment by omogenot** [comment]
Hi,

@daraelmin : As mentionned, this statement is shown on various screens: company card, supplier order, customer order, invoices, etc.
As an example `fourn/card.php?socid=xx`

Rgds.

**Comment by code42fr** [comment]
We cant't reproduce this !
