### ISSUE TITLE
Unable to upload file whose first character is traditional Chinese

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#21262]
### Bug

Unable to upload file whose first character is traditional Chinese in every upload page .
And it will show a erro " Filename can't start with a '.' " as below .
![image](https://user-images.githubusercontent.com/78349579/173547744-549b5a9a-a4ad-4bb0-ad56-b4f2b305b6d1.png)

But if you put a number or english in the front , then no error show up .

### Environment Version

v 14.0.3 and v15.0.2

### Environment OS

Deian 10

### Environment Web server

Apache/2.4.38 Apache/2.4.41

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.3.31

### Environment URL(s)

ecm/index.php?uploadform=1    projet/document.php?id=31

### Expected and actual behavior

Should not show any errors .

### Steps to reproduce the behavior

Go to any proposal or order and try to upload a chinese name file like "測試" .

**Comment by trekmorris** [comment]
the request is still relevant and not yet covered by latest stable version.

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by trekmorris** [comment]
Hi 

NO , it still not working on v 18.0.3 .

**Comment by Hystepik** [comment]
Hi
It works for me in last version of 18.0.6

**Comment by trekmorris** [comment]
Hi 

Yes , it has fixed in v18.0.5 , thanks for your message .
