### ISSUE TITLE
Missing extrafields on expense report lines

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#21309]
### Feature Request

![image](https://user-images.githubusercontent.com/3288514/174259227-2e83449d-8486-49b4-a6dd-803562986247.png)

### Use case

Re-invoice the cost lines to the customer

### Suggested implementation

1) ADD Table in BDD

**Comment by FHenry** [comment]
WIP : https://github.com/FHenry/dolibarr/tree/dev_extrafield_on_expensereport_lines
