### ISSUE TITLE
Problem with "Approver" filter on holiday list

### ISSUE THREAD

**Issue by leny0769** [Dolibarr/dolibarr#21311]
### Bug

For users who are not administrators, the drop-down list is filtered. But, it is reversed. A non-administrator user can filter on all users except himself, while it should be possible to filter only on himself. I think we have to change the variable $excludefilter in holiday/list.php, like this :

- Before : 
![2fa673f9498516045be38ab2886bcc9018d0de51](https://user-images.githubusercontent.com/75144133/174286417-f501ea03-a73a-40c3-91c2-d2a57dff780a.png)

- After : 
![881dfd42a0c5cfea12e0a5d3fd1d64bac7acb10e](https://user-images.githubusercontent.com/75144133/174286495-2dc37697-c013-4f82-ba5e-bed23435a8d7.png)

### Environment Version

v15

**Comment by alkaan** [comment]
For all users we can present all approvers, this list won't depend on connected user, except for admin perhaps who can have all user in the list :
![image](https://user-images.githubusercontent.com/23650748/210063307-3aae9931-e0bb-41bd-829e-7cc3ac13db76.png)

or
![image](https://user-images.githubusercontent.com/23650748/210063290-be75faff-1738-4220-b052-8c03e264fe0c.png)

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
