### ISSUE TITLE
Unknown column 'amount_main_currency' in 'field list'

### ISSUE THREAD

**Issue by FranckInfans** [Dolibarr/dolibarr#21322]
### Bug

When i try to create a bank account : 
Unknown column 'amount_main_currency' in 'field list'

### Environment Version

15.0.2

### Environment OS

Debian

### Environment Web server

Apache/2.4.38 (Debian)

### Environment PHP

PHP 7.3

### Environment Database

8.0.29

### Environment URL(s)

compta/bank/card.php

**Comment by atm-maxime** [comment]
You have to run the v15 migration script by going on /install
