### ISSUE TITLE
inquiry / discussion to asset-table-names with hyphen

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#21339]
Hello,

the new asset-tables are created with hyphen.

I remember that in the past this could always cause problems (with queries ...).

Is this no longer an issue  (also for older/exotic configurations) ?

Otherwise I would suggest to stay with the underscore in general 
and change it before release of Dolibarr 16.

@aspangaro @eldy

**Comment by edupulpillo** [comment]
agree

**Comment by hregis** [comment]
@dolibit-ut @edupulpillo

The hyphen is not for the table name, if you have "tablename-module" this is for create "tablename" only when "module" is enabled the first time.
