### ISSUE TITLE
Accounting Period Menu is missing

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#21369]
### Bug

Hello,

the accounting period entry is missing in upgraded versions of Dolibarr 14.0.5 & 15.0.1 (only these we have tested).

In all fresh/newly installed environments the menu is displayed,
but in all our updated systems not.

We can access the page manually via the url.

All systems have FeatureLevel 1 or 2.

### Environment Version

Dolibarr 14-15 upgraded from previous versions

### Environment OS

Linux (Debian 10)

### Environment Web server

Apache 2

### Environment PHP

PHP 7.4

### Environment Database

MariaDB

**Comment by eldy** [comment]
What about 15.0.2 ?
Also can you say what is the url you expect to see in menu and that you miss ?

**Comment by dolibit-ut** [comment]
Now after upgrade from 14.0.5 to 15.0.2 it shows the menue 'Accounting Period'.

URL we missed and now see is 
/**htdocs/accountancy/admin/fiscalyear.php**?mainmenu=accountancy&leftmenu=accountancy_admin
