### ISSUE TITLE
Product pagination not work

### ISSUE THREAD

**Issue by bardieldj** [Dolibarr/dolibarr#21372]
### Bug

Product pagination not work

### Environment Version

15.0.2

### Environment OS

Windows 10

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

MarianaDB

### Attached files

![asdfasfasfda1234124asdfasdf](https://user-images.githubusercontent.com/19998963/175575764-80fbcb51-80ad-4aec-8630-c5e117bbcfcf.JPG)
![asdfasdfa123123](https://user-images.githubusercontent.com/19998963/175575777-966e67c3-81b5-43bf-9012-05571f4ac685.JPG)

**Comment by eldy** [comment]
I can't reproduce.
Can you tell me how many product you have ? Do you have module "Service" enabled ? If yes, how many services do you have ?
