### ISSUE TITLE
RFE: Tick box to let the user ignore the first line when importing a file

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#21376]
### Feature Request

Tested on: 15.0.1

Hello,
When I have exported data, for example warehouses, the first line contains titles.
But if I want to modify that file and then reimport I need right now to delete the first line otherwise it doesn't work.
However that first line with titles really helps to match fields in the import process.

So the feature that I would like is, at step 4 when making an import, that a tick box exist and say ignore first line when importing.

Thank  you

![Ignorer_1ere_ligne](https://user-images.githubusercontent.com/2222550/175770641-d6c5ee33-9344-4b0a-a611-fc35f4f782c6.JPG)

**Comment by mikygee** [comment]
The work around at Step 5 is to start at line 2
![image](https://user-images.githubusercontent.com/2222550/175785374-308b19fa-531f-4572-b796-c29054b12d2d.png)

But the choice should be asked at Step 4, much more ergonomic.

**Comment by atm-maxime** [comment]
Thanks for your feedback. On my side I find the feature of choosing on which line number the import must begin much more effective and useful than a checkbox.

**Comment by mikygee** [comment]
Hello Maxime,

Yes actually the goal is different.
Choosing the line number to import is more granular.
But what we do as a user is usually export data, tweak the file with new values and reimport (all the lines). We want to keep the columns titles in the csv file.
And it's confusing because we expect to be asked to ignore the first line at step 4.

So actually I should change my feature request so that this choice (Imorter les lignes à la position) is asked at step 4 and not step 5
step 5 is supposed to be a summary of what will be done.
at step 4 I should choose what to match and if I need to ignore the first line.

**Comment by eldy** [comment]
With v16, the "First line to start import" is by default on value 2 (import has been rewritten).
It was a hard coded value that was 1 and it become 2 by default.

**Comment by mikygee** [comment]
I'll check this ticket during the month of july.
