### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by PatPat84** [Dolibarr/dolibarr#21371]
# Bug
Default payment method

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k
- **PHP**: fpm-fcgi 7.4.30
- **Database**: MySQL or MariaDB 5.7.37

## Expected and actual behavior
On Dolibarr, a default payment method is indicated if it is not defined on the invoice
 
![image](https://user-images.githubusercontent.com/101411991/175551087-0136ba0f-ec91-4f19-8a4c-1124c4c1535b.png)

It should be if it is not defined in the tier:

![image](https://user-images.githubusercontent.com/101411991/175551116-a5d44a76-1bf3-4e13-88cc-bccc46e86586.png)

## Report
- **Multicompany**: 14.0.0

**Comment by eldy** [comment]
Sorry, i don't understand the bug.
The value define on thirdparty is the value used by default that will be defined on invoice.
But this is the value of payment mode on invoice (each invoice can have a payment mode that is different) that we must use to decide which information we show on PDF.

**Comment by PatPat84** [comment]
You need to change how the default payment account works.
Payment account information is on the tier.
If this is empty then we take the default account and not on the invoice.

**Comment by PatPat84** [comment]
We found the variable
RELOAD_PAGE_ON_SUPPLIER_CHANGE
