### ISSUE TITLE
Issue with SQL and Payment Date. 

### ISSUE THREAD

**Issue by azertym** [Dolibarr/dolibarr#21385]
### Bug

Hi all, I'm new here.

I use dolibarr V16 and i've a mistake with the SQL database. When i make a payement on bills, i've this mistake. 
![Capture d’écran 2022-06-26 115759](https://user-images.githubusercontent.com/3206982/175808989-f82afc30-15f5-4c46-9a81-3ef59876425c.png)

I tried to repair the sql database but i've the same mistake... 

I d'ont know how to make now. 

### Environment Version

16.0.0

### Environment Web server

AP

### Environment PHP

7.4.25

### Environment Database

MySQL

**Comment by emheyarssi** [comment]
Hi. Have you try first to find help on the dolibarr forum? https://www.dolibarr.fr/forum/

**Comment by azertym** [comment]
> Hi. Have you try first to find help on the dolibarr forum? https://www.dolibarr.fr/forum/

Hi emheyarssi,

Yes but the People of the forum said me to come here because i use dolibarr v16...

So, coool....

**Comment by emheyarssi** [comment]
> because i use dolibarr v16

Sorry, I've missed that.
