### ISSUE TITLE
FEC import "Data truncated for column" for data with a "," as decimal separator

### ISSUE THREAD

**Issue by williamdes** [Dolibarr/dolibarr#21403]
### Bug

Data truncated for column

Same as #14389

### Environment Version

15.0.x

### Environment PHP

7.4

### Environment Database

MariaDB

### Expected and actual behavior

I expect it to import

And it does not

```
 Erreurs sur 12 enregistrement(s) source
* Ligne 2
    > Data truncated for column 'debit' at row 1
* Ligne 3
    > Data truncated for column 'debit' at row 1
* Ligne 4
    > Data truncated for column 'debit' at row 1
* Ligne 5
    > Data truncated for column 'debit' at row 1
* Ligne 6
    > Data truncated for column 'debit' at row 1
* Ligne 7
    > Data truncated for column 'debit' at row 1
* Ligne 8
    > Data truncated for column 'debit' at row 1
* Ligne 9
    > Data truncated for column 'debit' at row 1
* Ligne 10
    > Data truncated for column 'debit' at row 1
* Ligne 11
    > Data truncated for column 'debit' at row 1
* Ligne 12
    > Data truncated for column 'debit' at row 1
* Ligne 13
    > Data truncated for column 'debit' at row 1
```

### Steps to reproduce the behavior

Import an OpenConcerto FEC txt file

[ExportOC_20220620-20220628_FEC.20220628_153124.csv](https://github.com/Dolibarr/dolibarr/files/9001475/ExportOC_20220620-20220628_FEC.20220628_153124.csv)

### Attached files

![image](https://user-images.githubusercontent.com/7784660/176191914-e56fdc79-bb94-4718-93e4-3a0ac6c1b3de.png)

See: https://github.com/upshift-docker/dolibarr

**Comment by aspangaro** [comment]
Hi,

Try with separator tabulation : \t

**Comment by williamdes** [comment]
> Hi,
> 
> Try with separator tabulation : \t

Hi,
This is what I used, you can see that in the capture

**Comment by emheyarssi** [comment]
Replace char , with the char . in your decimal values.

**Comment by williamdes** [comment]
> Replace char , with the char . in your decimal values.

Thanks for the workaround, but can anyone make a patch for this bug?

**Comment by emheyarssi** [comment]
The problem reside in the "fgetcsv" nativ php function which doesn't give the possibility to specify the decimal separator. So AFAIK the only solution I see is to developp a new csv parser.
Another tipp could be to enclosing each data with the " char (not testet yet)

**Comment by williamdes** [comment]
> The problem reside in the "fgetcsv" nativ php function which doesn't give the possibility to specify the decimal separator. So AFAIK the only solution I see is to developp a new csv parser. Another tipp could be to enclosing each data with the " char (not testet yet)

For me this isn't the issue
```php
fgetcsv(
    resource $stream,
    ?int $length = null,
    string $separator = ",",
    string $enclosure = "\"",
    string $escape = "\\"
): array|false
```
Since the separator is `\t`
For me the issue resides on how the data is sent to MySQL
Or casted as the right type before
It has something to do with the number parsing I think
Can you point me some points on the codebase so I can maybe try to have a look
Will a PR be reviewed and merged?

**Comment by emheyarssi** [comment]
Yes, you've right. MySQL Decimal type doesn't accept comma as decimal separator.

MySQL import is made here: `/htdocs/core/modules/import/import_csv.modules.php` on line 312 and `fgetcsv` on line 248 in the same file.

**Comment by williamdes** [comment]
Given how much this got care since then, I am closing this. I know pretty well open source, and clearly Dolibarr is not production ready.

**Comment by emheyarssi** [comment]
> Given how much this got care since then, I am closing this. I know pretty well open source, and clearly Dolibarr is not production ready. 

You're feel free to participate to make dolibarr better. According your profile, resolving this issue should not be a problem for you.
