### ISSUE TITLE
Filter tag categorie in members area

### ISSUE THREAD

**Issue by inkoozing** [Dolibarr/dolibarr#21416]
### Bug

Hello,
I have the module tag-categories activated.
In members menu, i try to filter by tag, (tag : "without tag-sans catégories") there is a bug.
The same filter in society menu is working.

Thanks for helping our association.

### Environment Version

15.02

### Environment Web server

Apache

### Environment PHP

7.4.25

### Environment URL(s)

http://dolibarr.inkoozing.fr

### Attached files

Dolibarr a détecté une erreur technique.
Ces informations peuvent être utiles à des fins de diagnostic (vous pouvez définir l'option $dolibarr_main_prod sur '1' pour masquer les informations sensibles):
Date: 20220630073711
Dolibarr: 15.0.2 - https://www.dolibarr.org
PHP: 7.4.25
Server: Apache
OS: Linux paas_15464 5.16.12-paas #307 SMP PREEMPT Tue Mar 8 10:08:07 CET 2022 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

Url sollicitée: /htdocs/adherents/list.php
Referer: http://dolibarr.inkoozing.fr/htdocs/adherents/list.php?leftmenu=members
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, dbadmin, categorie, export, workflow, accounting, banque, don, facture, fournisseur, margin, service, modulebuilder, societe, debugbar, fckeditor, propal, prelevement, adherent, stock, product, mailing, import, notification, paymentbybanktransfer
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT d.rowid, d.ref, d.login, d.lastname, d.firstname, d.gender, d.societe as company, d.fk_soc, d.civility, d.datefin, d.address, d.zip, d.town, d.state_id, d.country, d.email, d.phone, d.phone_perso, d.phone_mobile, d.birth, d.public, d.photo, d.fk_adherent_type as type_id, d.morphy, d.statut, d.datec as date_creation, d.tms as date_update, d.note_private, d.note_public, d.import_key, s.nom, (CASE WHEN d.societe IS NULL THEN s.nom ELSE d.societe END) as companyname, t.libelle as type, t.subscription, state.code_departement as state_code, state.nom as state_name FROM llx_adherent as d LEFT JOIN llx_c_country as country on (country.rowid = d.country) LEFT JOIN llx_c_departements as state on (state.rowid = d.state_id) LEFT JOIN llx_societe as s on (s.rowid = d.fk_soc), llx_adherent_type as t WHERE d.fk_adherent_type = t.rowid AND cm.fk_categorie IS NULL AND d.entity IN (1)
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'cm.fk_categorie' in 'where clause'

Dolibarr a détecté une erreur technique.
Ces informations peuvent être utiles à des fins de diagnostic (vous pouvez définir l'option $dolibarr_main_prod sur '1' pour masquer les informations sensibles):
Date: 20220630073711
Dolibarr: 15.0.2 - https://www.dolibarr.org
PHP: 7.4.25
Server: Apache
OS: Linux paas_15464 5.16.12-paas #307 SMP PREEMPT Tue Mar 8 10:08:07 CET 2022 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

Url sollicitée: /htdocs/adherents/list.php
Referer: http://dolibarr.inkoozing.fr/htdocs/adherents/list.php?leftmenu=members
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, dbadmin, categorie, export, workflow, accounting, banque, don, facture, fournisseur, margin, service, modulebuilder, societe, debugbar, fckeditor, propal, prelevement, adherent, stock, product, mailing, import, notification, paymentbybanktransfer
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT d.rowid, d.ref, d.login, d.lastname, d.firstname, d.gender, d.societe as company, d.fk_soc, d.civility, d.datefin, d.address, d.zip, d.town, d.state_id, d.country, d.email, d.phone, d.phone_perso, d.phone_mobile, d.birth, d.public, d.photo, d.fk_adherent_type as type_id, d.morphy, d.statut, d.datec as date_creation, d.tms as date_update, d.note_private, d.note_public, d.import_key, s.nom, (CASE WHEN d.societe IS NULL THEN s.nom ELSE d.societe END) as companyname, t.libelle as type, t.subscription, state.code_departement as state_code, state.nom as state_name FROM llx_adherent as d LEFT JOIN llx_c_country as country on (country.rowid = d.country) LEFT JOIN llx_c_departements as state on (state.rowid = d.state_id) LEFT JOIN llx_societe as s on (s.rowid = d.fk_soc), llx_adherent_type as t WHERE d.fk_adherent_type = t.rowid AND cm.fk_categorie IS NULL AND d.entity IN (1) ORDER BY d.lastname ASC LIMIT 76
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'cm.fk_categorie' in 'where clause'

![Screenshot 2022-06-30 at 09-39-30 Adhérents](https://user-images.githubusercontent.com/108454953/176621241-c7b736d9-a5d3-4536-b980-35768fbce6e0.png)

**Comment by daraelmin** [comment]
Hi @inkoozing ,

Could you try the fix please ?

Cheers

**Comment by inkoozing** [comment]
Hi @daraelmin. It's working. Thanks you ;)
