### ISSUE TITLE
Bug #7650 again: When delete a supplier invoice, stocks don't decrease

### ISSUE THREAD

**Issue by cesar-bsd-com-br** [Dolibarr/dolibarr#21428]
I have the same problem now, with version 15.0.1.

I've created a supplier invoice, and validate it - stocks increase OK.

When I delete the invoice, the stocks are the same - Dolibarr didn't decrease.

My configuration is to increase stock when validate the supplier invoice.
![Animação (1)](https://user-images.githubusercontent.com/59903458/170044017-ffca652a-5b7c-4c14-901e-e1f48a7430e0.gif)

_Originally posted by @cesar-bsd-com-br in https://github.com/Dolibarr/dolibarr/issues/7650#issuecomment-1135912027_

**Comment by cesar-bsd-com-br** [comment]
Important thing about this bug: if I DELETE the supplier invoice, the stocks don't change; when I select to change the invoice, Dolibarr calls a setDraft() method that changes the stocks and everythings looks OK.

The problem ocurrs only when I use the DELETE option.

[log_delete.txt](https://github.com/Dolibarr/dolibarr/files/9080512/log_delete.txt)
[log_setDraft.txt](https://github.com/Dolibarr/dolibarr/files/9080513/log_setDraft.txt)
n.

**Comment by cesar-bsd-com-br** [comment]
This problem still exists on version 16.0.5: the stock only reduces if I change the invoice to draft mode first; if I delete it, the stock remains untouched :(

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
