### ISSUE TITLE
External users cannot use tickets

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#21434]
### Bug

Hello!

I've just tried to give an external user access to the ticket module, but it doesn't work.

What happened:

I gave the user full access to tickets, but he cannot create tickets or see the details of any ticket.

Is there a way for external users to see tickets they've created so that they can see the progress of their ticket?

Thanks!

**Comment by emheyarssi** [comment]
Hi. Have you try to find help on the dolibarr forum first? https://www.dolibarr.fr/forum/
