### ISSUE TITLE
Services on BOM

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#21441]
### Bug

The list of services does not appear in the search form in Bill of Materials

### Environment Version

15.0.2, beta 16.0.0

### Environment OS

openSUSE Leap 15.2

### Environment Web server

Apache

### Environment PHP

7.4.6

### Environment Database

5.5.5-10.4.17-MariaDB

### Environment URL(s)

dolibarr/htdocs/bom/bom_card.php

### Expected and actual behavior

Expected behavior:
I find that on the main page of Dolibarr, in the "Features" section, under "Manufacturing" the following description, "Create your nomenclatures (BOM) to define how to consume raw products or services to produce manufactured products (Amount to consume, efficiency, stock market impact, ...)."

Actual behavior:
However, in version 15 and 16, when I try to put SERVICES in the lists they don't even appear in the list to select, I have already activated/deactivated treating services as if they were products (stock control) and nothing, so I deduce which must be a Dolibarr error, and at the moment, for it to "work" I can only change the services to products, and then, IF THEY APPEAR.

Best regards and thank you very much.

### Steps to reproduce the behavior

Go to the MRP>Bill of Materials>New Bill of Materials> page (fill in the requested fields), and on the next page, when trying to add a service to the bill of materials, such as "labor", " welding time", "turning time"... that is, SERVICES, do not appear in the search form unless said services are in Dolibarr, in its file, as products.

### Attached files

[Features Dolibarr](https://www.dolibarr.org/presentation-production-mrp.php)
_No response_

**Comment by dolibit-ut** [comment]
Hello, 
in my opinion this is not really a bug - but maybe a feature request.
In classic Bills of **Materials** there are no Services.  (nomen est omen)

But i support your request to have an option to use services directly in BOM.

**Comment by JuanBrillo** [comment]
I don't know if it will be a bug or not, but the reality is that on the web, it clearly indicates that materials and services can be added to the BOM.

If services cannot be added, then cost prices can be misleading, as they do not reflect reality at all.

If it is not a bug, and it is, I think the function should be added... Someone who is dedicated to making, for example, furniture, which is higher, the cost of wood and screws, or the cost of having to cut the wood, measure, drill, and if that were the case, apply paints or varnishes... I think it is clear that if the option of knowing the costs of services added to manufacturing is not given, the module is lame.

In fact, on the page dedicated to this module in dolibarr, we can see an image, in which, A SERVICE APPEARS, (from the icon you can see that it is a service, not a product) in the list of materials, so I emphasize that I think it is a bug.

**Comment by atm-maxime** [comment]
#19661

**Comment by ckeydel** [comment]
Any news on this? I just found out that we can no longer have service items in out BOMs. We still have older BOMs from the time when we ran version 14 but since then we have upgraded to version 15 and now 16.
This is clearly a regression. What is the current state?

**Comment by hello-world-dot-c** [comment]
Any news on this? I just found out that we can no longer have service items in our BOMs. We still have older BOMs from the time when we ran version 14 but since then we have upgraded to version 15 and now 16.
This is clearly a regression. What is the current state?

**Comment by Raffael50** [comment]
Same issue here, running v 16.0.1.
I do not see related changes with v17, but should we still update the ERP in order to have a chance to get Services selectable in BOMS? Any other advice?

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
