### ISSUE TITLE
Price request status in listing says Open, what ever the real status is

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#21449]
### Bug

Price request status in listing says Open, what ever the real status is

### Environment Version

15.0.2

### Environment OS

Debian 10

### Environment Web server

Apache2 

### Environment PHP

fpm-fcgi 7.3.33-1+020211119.91+debian101.gbp618351

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0+deb10u1

### Environment URL(s)

/supplier_proposal/list.php?leftmenu=supplier_proposals

### Expected and actual behavior

When the status of a price request is changed to Accepted, Refused or Closed that should be reflected in the listing, but it is not. In the listing everything is marked as Ouvert (Open) as can be seen on the attached picture. But if the filtering fuction above the colmun is used, it will filter correctly, but the marking is still wrong; everthing is marked as Open.

### Steps to reproduce the behavior

Create a price request, play around with with its status and see what appears in the listing.

### Attached files

![status](https://user-images.githubusercontent.com/24247236/171917260-205f902d-0c6a-46fa-8ace-e46db2da77d1.jpg)

**Comment by emheyarssi** [comment]
Fixed through another pull request -> #21557
