### ISSUE TITLE
Stripe payment from an order

### ISSUE THREAD

**Issue by L33thium** [Dolibarr/dolibarr#21457]
### Bug

yesterday a customer paid it's order via stripe.
The invoice and payment was created automatically, fine
but the invoice is not a draft but still have a temporary number.
Reopening and revalidating it don't give it a definitive number.

I'm not sure if this is an issue or normal path, maybe dolibarr is waiting an API signal indicating the transaction to my account is done ?

### Environment Version

15.0.2

### Environment OS

Debian GNU/Linux 11 (bullseye)

### Environment Web server

nginx 1.18.0-6.1

### Environment PHP

php 7.4.28-1+deb11u1

### Environment Database

Mariadb 1:10.5.15-0+deb11u1

### Expected and actual behavior

invoice created validated with a definitive number

### Steps to reproduce the behavior

receive an online payment via stripe

### Attached files

![80c83b48302b23e43b30df58ddb8861ba09a15e3](https://user-images.githubusercontent.com/17518651/177524813-91285811-ba09-4cd3-a9d4-62027e3413b5.jpeg)

**Comment by JuanBrillo** [comment]
The normal thing in Dolibarr is to make the payment on an invoice, with its official number, not on an order and then the invoice is made... that sounds more like some kind of configuration error to me, and when Dolibarr detects that the invoice has already been paid, classifies it as such, without allowing validation.

**Comment by L33thium** [comment]
So if Dolibarr allow that, this is a bug ?

**Comment by JuanBrillo** [comment]
I think so, but I would recommend that the next time you follow the normal dolibarr procedure, that is, make the payment on the validated invoice, never before.

**Comment by L33thium** [comment]
Ok i will rework my email models but how can i fix that invoice for now ?
in that state it's not valid now for my accountant

**Comment by JuanBrillo** [comment]
I don't know for sure, but, if I were you, I eliminated the payment in dolibarr, reopened the invoice, validated it, and then generated the payment that you know was made, putting the day it was made and all the data that the previous payment had eliminated. It's the only thing that comes to mind, maybe a developer can tell you something.

**Comment by priojk** [comment]
Just some addition: Since (I think) v15 there is an "official" mechanism in Dolibarr to create a Stripe payment link for an order (which can be mailed out) and if it gets paid, a proper invoice will automatically be created and validated and the payment associated. I am using this successfully for some automated online self-service processes and can confirm that this usually works. (It's useful since some customers start an order process which they don't complete. If a validated invoice would be used, the system gets filled up with validated invoices that once validated cannot be deleted any more).

I don't know, if this exact mechanism has been used in this case. If so, possibly the automatic validation of the invoice went wrong (maybe user rights?) and all this ended up in this indeed inconsistent state.

**Comment by L33thium** [comment]
It's a vanilla dolibarr without any external module i use the link generated in emails with __ONLINE_PAYMENT_URL__

**Comment by priojk** [comment]
Was the generated link referring to a validated order or rather to the draft invoice? Maybe you can have a look at the contents of the sent mail.

A stripe payment link to a validated order looks like this (note the source=order and the order ref):

` https://your-domain.com/public/payment/newpayment.php?source=order&ref=PO1234&securekey=ag345238fhfg373464`

If this was the case, it should have ended up with a validated invoice and a related payment both automatically created after successful payment processing.

**Comment by L33thium** [comment]
It was on an opened order, the link generated is https://fqdn/public/payment/newpayment.php?source=order&ref=CO2207-XXXX
(without securekey)
it ened up with my issue, an invoice validated (not draft) but without a definitive number (PROVXXX)

**Comment by L33thium** [comment]
ok same issue with the payment for a proforma invoice
it was a draft before the payment, it's not after but still have (PROV127) number
it was with paypal this time.
No errors in the log
