### ISSUE TITLE
Linked account code (double accountancy) between EEC countries is import and not intra for supplier invoices

### ISSUE THREAD

**Issue by Toge-lab** [Dolibarr/dolibarr#21483]
### Bug

When creating a supplier invoice for a supplier in other countries belonging to EEC (e.g. Company = France, Supplier = Belgium) the code proposed to link the transaction in the double accountancy module is the one coming from the "import" field of the product and not the one of the "intra" field of the product.

There is no issue with customer invoices.

I checked:

1. Both countries are well set on 1 (eec) in c_country table (no value set in "Divers" section)
2. Issue is same with various company and supplier countries
3. Issue is the same on a fresh install of Dolibarr
4. Issue is the same either for existing or new invoices
5. Issue was already present in v15.0.1

### Environment Version

15.0.2

### Environment OS

Linux

### Environment Web server

Debian 10

### Environment PHP

5.6

### Environment Database

MariaDB

### Expected and actual behavior

Linked code should be infra and not import.

### Steps to reproduce the behavior

Prerequesite: Company should belong to an EEC country.

1. Create third party supplier in other EEC country
2. Create a product and set 3 different codes for Accounting code (purchase), Accounting code (purchase intra), Accounting code (purchase import)
3. Set a buy price for this product for the supplier created at point 1
4. Create a supplier invoice with this product and validate
5. Go in the accountancy and click on **Lines to link** under **Linking supplier invoices**
6. The proposed code is the import and not the infra

**Comment by AurelienBISOTTI** [comment]
Also exist in v18 : 

Account suggested in this example is 604, should be 605

![Capture d’écran du 2023-06-10 12-10-48](https://github.com/Dolibarr/dolibarr/assets/12530585/fc2c188e-a026-43e5-a1e4-c2021b1cd672)
![Capture d’écran du 2023-06-10 12-11-55](https://github.com/Dolibarr/dolibarr/assets/12530585/470ffe29-a946-490b-bbfe-38ec228d5434)
![Capture d’écran du 2023-06-10 12-14-00](https://github.com/Dolibarr/dolibarr/assets/12530585/b4ea25c4-f5a0-4628-b609-5faec2881055)
![Capture d’écran du 2023-06-10 12-10-31](https://github.com/Dolibarr/dolibarr/assets/12530585/4980c98e-1a2b-4007-84f9-e73415bf5d1a)
![Capture d’écran du 2023-06-10 14-11-58](https://github.com/Dolibarr/dolibarr/assets/12530585/4888f85d-ff07-4a36-9f75-c7bb81760fe0)

**Comment by AurelienBISOTTI** [comment]
Using default accounts in accounting module did not change the result

![image](https://github.com/Dolibarr/dolibarr/assets/12530585/bf065c01-f556-47ac-87bb-a37d0282e983)
