### ISSUE TITLE
Feature request: Add Sociétés Civiles Immobilières à l'IR et à l'IS in the dictionnaires des Formes juridiques des Tiers

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#21486]
### Feature Request

Dolibarr: 15.0.2

Hello,

"Sociétés Civiles Immobilières à l'IS et à l'IR" are very common in France and I think they should be natively present in Dolibarr dictionnaries without adding them manually.
So the feature request is to have these two forms added in dolibarr 16.x

Regards

**Comment by emheyarssi** [comment]
Hi.
According the comment in the source file, the "categories juridiques" was (or still) filled from "http://www.insee.fr/fr/nom_def_met/nomenclatures/cj/cjniveau2.htm" (now available hier: https://www.insee.fr/fr/information/2028129)   which doesn't contain “Sociétés Civiles Immobilières à l'IS et à l'IR".
So, could any one from Dolibarr team take a decision?
@eldy maybe?

**Comment by mikygee** [comment]
Hello all,
Actually, "Société Civile Immobilière" is in the list that emheyrassi pointed out
https://www.insee.fr/fr/information/2028129
![image](https://user-images.githubusercontent.com/2222550/179373742-ebe066b6-78db-47dc-803d-5e67f1ec319c.png)
So I don't know if IR or IS should be distinguished but I would suppose yes.

**Comment by ksar-ksar** [comment]
https://www.dolibarr.fr/forum/t/que-choisir-comme-type-de-societe-si-lon-est-sci-a-lir-ou-a-lis/40506/7
