### ISSUE TITLE
Color changes to theme not working

### ISSUE THREAD

**Issue by karozans** [Dolibarr/dolibarr#21501]
### Bug

When changing the menu, background and other colors for the Eldy theme, the colors will initially be set, but then when you click save, the colors revert back to the default Eldy theme colors.

### Environment Version

15.0.2

### Environment OS

Mac OS Monterey

### Environment Web server

Apache 2.4.46 on MAMP

### Environment PHP

7.4.21 on MAMP

### Environment Database

Mysql 5.7.34 on MAMP

### Environment URL(s)

/admin/ihm.php?mode=template

### Expected and actual behavior

The color changes to the background, menus, and so on should be permanent after save.

The color changes revert back to the default eldy theme.

Also, the color swatch picker will disappear.

### Steps to reproduce the behavior

Under Setup -> Display -> Skins and Colors.

Pick the Eldy theme.  Then try to change the default colors below.

The color will initially set, then when you click the save button, the colors will revert back to the standard Eldy default theme color.

**Comment by Quatadah** [comment]
Hi @karozans , it's working for me in the same version (15.0.2). Are you sure you click on validate after choosing the color ?

**Comment by karozans** [comment]
Yes, I hit validate and it does indeed change the colors, but when I hit save, the color reverts back to the original eldy theme color.  This is on a totally new installation of dolibarr.  No upgrade.

Okay this is odd.  It does work for me too.  Sort of.  If I set the colors, it will change immediately.  When I click save, the colors revert back to the eldy theme.  However, if I do a hard refresh after, the color comes back.  A regular page refresh will not do it.

It was working fine in 14.0.5.

**Comment by hregis** [comment]
@karozans

Clear your browser cache

**Comment by karozans** [comment]
I did that and I also flushed the memcached.  Still works the same on Mac.  I used firefox, Chrome, and Safari and they all behave the same.

**Comment by hregis** [comment]
@karozans 
no probleme with 15.0.3 !

**Comment by karozans** [comment]
I haven't tried 15.0.3.  I am still on 15.0.2 since it's the last stable version.

It's not super important.  So I can wait till 15.0.3 is released and see if that changes anything.  Then reopen a new case if the problem still exists.
