### ISSUE TITLE
Cannot add new Currency

### ISSUE THREAD

**Issue by vithanagevms** [Dolibarr/dolibarr#21508]
When we want to add a new currency, it is referring to currency_code which is a string, 

I tried with PHP 8.0

Error line
https://github.com/Dolibarr/dolibarr/blob/75693ce34a23f6c732402e4020b0b39c126c87df/htdocs/admin/dict.php#L861

**Comment by ksar-ksar** [comment]
Hello,

What is your dolibarr version ?

**Comment by vithanagevms** [comment]
This is V15.0.2 and also development branch also has the same code. 

basically, the bug is, trying to increment currency_code (it's a string, not a digit).

It can be fixed by removing the selected line.

**Comment by edupulpillo** [comment]
I can not reproduce the problem in Dolibarr 16.0.3 with PHP 7.4.33 and is possible to add currencies in setup/dictionaries/currencies without any problem in my case.

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by edupulpillo** [comment]
I can not reproduce the problem in Dolibarr 18.0.2 with PHP 7.4.33 and is possible to add currencies in setup/dictionaries/currencies without any problem in my case.
Using PHP 8.0 or PHP 8.1, trying to access to the dictionaries result in an empty white page.
So even the access to /admin/dict.php?mainmenu=home fails, and returns an empty page in v18.0.2

**Comment by ksar-ksar** [comment]
Hello,

Can you have a look on your hosting logs?

**Comment by edupulpillo** [comment]
in wich folder?
