### ISSUE TITLE
Customer invoices list with field selector

### ISSUE THREAD

**Issue by hazel0602** [Dolibarr/dolibarr#21510]
### Bug

Customer invoices list shows only one (probably the first) line when "sales representative of third party" is activated in selected fiels tab.

### Environment Version

15.0.1

### Environment OS

Linux dolibarr-host 5.4.0-1074-azure #77~18.04.1-Ubuntu SMP Wed Mar 30 15:36:02 UTC 2022 x86_64

### Environment Web server

Apache/2.4.29 (Ubuntu)

### Environment PHP

7.2.34-32+ubuntu18

### Environment Database

MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0ubuntu0.18.04.1

### Environment URL(s)

/compta/facture/list.php?leftmenu=customers_bills#selectedfields

### Expected and actual behavior

Expected: The customer invoice list should show the sales representative. Comparable with the column "invoice date" "third-party" "amount" etc.

Actual: The customer invoice list shows only the first entry. The selection menu for the active columns can no longer be activated. 

### Steps to reproduce the behavior

- Go to "Billing | Payment" -> "customer invoices" -> "list" 
- Activate the "column selector" next to the "select all"-checkbox
- Active "Sales representative of third party"

To get the list displayed correctly again the following command must be triggered via phpmyadmin:

UPDATE `llx_user_param` SET `value` = 'f.ref,f.datef,f.date_lim_reglement,p.ref,s.nom,s.zip,f.total_ht,f.total_ttc,rtp,f.fk_statut,' WHERE `llx_user_param`.`fk_user` = 1 AND `llx_user_param`.`entity` = 1 AND `llx_user_param`.`param` = 'MAIN_SELECTEDFIELDS_invoicelist';

**Comment by ibuiv** [comment]
fixed in 15.0.3
![image](https://user-images.githubusercontent.com/50403308/204059295-ee807f98-7420-494d-95d7-b2c82b9a7a1a.png)
