### ISSUE TITLE
When uploading a new logo for third party, old logo files are not deleted from disk

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#21518]
### Bug

Dolibarr 15.0

File system for a third party before uploading new logo:

>./documents/societe/711/logos/logo-ab-horizontal.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_small.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_mini.png

Then we upload a new logo named "logo-ab-horizontal2.png" to the same third party:

>./documents/societe/711/logos/logo-ab-horizontal.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_small.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_mini.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal2_small.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal2_mini.png
./documents/societe/711/logos/logo-ab-horizontal2.png

Now both logo files exist on disk while only one of them is in use, making the old logo orphaned and waste disk space for no reason.

### Environment Version

15.0.0

### Environment OS

Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Environment PHP

7.4.30

### Expected and actual behavior

Expected behaviour is that when uploading a new logo, Dolibarr should delete all references (including disk files) to the old logo.

**Comment by emheyarssi** [comment]
Bug or feature? 😁
