### ISSUE TITLE
Erreur dans l'url des réseaux sociaux

### ISSUE THREAD

**Issue by fanhtech** [Dolibarr/dolibarr#21525]
Bonjour,
Sur mon environnement de test, j'ai installé la version 16 Bêta de Dolibarr. J'ai activé le module Réseaux Sociaux. Par-contre, sur la fiche utilisateur, la fiche des tiers et la fiche société, l'url de Dolibarr est ajouté comme préfix à l'url des réseaux sociaux.
Exemples avec facebook:
Société: https://mondolibarr.test/admin/www.facebook.com/monentreprise
Utilisateur: https://mondolibarr.test/user/www.facebook.com/monprofilfb
tiers: https://mondolibarr.test/societe/www.facebook.com/client1

Ci-joint la configuration du module Réseaux Sociaux
![image](https://user-images.githubusercontent.com/94901405/179721658-aa025ca4-10e0-4708-855f-4c061a3b3d5b.png)

Merci de votre aide

**Comment by comaiteseb** [comment]
Bonjour,

Je n'arrive pas à reproduire le problème (sur la version Dolibarr 15.0.3), pourriez vous apporter des précisions comme par exemple la version de Dolibarr.

**Comment by fanhtech** [comment]
> Bonjour,
> 
> Je n'arrive pas à reproduire le problème (sur la version Dolibarr 15.0.3), pourriez vous apporter des précisions comme par exemple la version de Dolibarr.

Bonjour @comaiteseb , il s'agit de Dolibarr 16.0.0-beta

**Comment by comaiteseb** [comment]
Ce problème est déjà corrigé sur la future version 16.0 (votre beta est obsolète)
Je vous invite à la télécharger directement sur github. (branche 16.0)

**Comment by fanhtech** [comment]
> Ce problème est déjà corrigé sur la future version 16.0 (votre beta est obsolète) Je vous invite à la télécharger directement sur github. (branche 16.0)

Bonsoir @comaiteseb,
Merci de ton retour. Je n'avais pas vu la branche 16.0
