### ISSUE TITLE
Time change problem with cron

### ISSUE THREAD

**Issue by atm-quentin** [Dolibarr/dolibarr#21523]
### Bug

Hello,

When there's a time change on a server, planned tasks (cron) are executed on the wrong time (for example, we change of time during summer, all planned task will be executed 1 hour later or sooner)

Does anyone already encounter this problem ? What can i do to solve this ?

Thank you !

### Environment Version

12.0.3

### Environment OS

Debian 10

### Environment PHP

7.4

**Comment by atm-maxime** [comment]
@eldy any tips regarding this issue ?
