### ISSUE TITLE
API Invoice Delete error

### ISSUE THREAD

**Issue by TedinfoRegis** [Dolibarr/dolibarr#21536]
### Bug

In file /compta/facture/class/api_invoices.class.php in function delete on line 669 a test is made if $result is lower than 0 in order to check if invoice has been deleted
> 
		$result = $this->invoice->delete(DolibarrApiAccess::$user);
		if ($result < 0) {
			throw new RestException(500, 'Error when deleting invoice');
		}

But, in file /compta/facture/class/facture.class.php in function delete in line 2582 value 0 is returned if invoice is not erasable
> 
		// Test to avoid invoice deletion (allowed if draft)
		$result = $this->is_erasable();

		if ($result <= 0) {
			return 0;
		}

The check in API should be lower or equal to 0

**Comment by emheyarssi** [comment]
Hi
Sorry but I don't understand what your problem is.

Moreover you do not specify your version of Dolibarr and your system.

**Comment by TedinfoRegis** [comment]
System used isn't needed because it's a logic problem.
I got the code from latest version in GIT in order to check if that was already spoted

Problem is when you try to delete an invoice through API and this invoice is not erasable (understand is_erasable return false) then API will answer :
> return array(
			'success' => array(
				'code' => 200,
				'message' => 'Invoice deleted'
			)
		);

**Comment by emheyarssi** [comment]
Yes, you've right, `$this->invoice->delete(...)` return 0 **or <0** if the delete failed.
