### ISSUE TITLE
Ban Not Valid

### ISSUE THREAD

**Issue by Mohaamaad7** [Dolibarr/dolibarr#21544]
### Bug

Hello 

I got that error

BAN not valid

![333](https://user-images.githubusercontent.com/77267270/180198954-52f0fbfd-8b48-4967-96ed-e9748aee58dc.jpg)

I have founded the same question from 2017 but there are no resposne 

https://www.dolibarr.org/forum/t/ban-not-valid-bank-account/16055

I am sure that the iban code is correct

i checked it in 

https://www.iban.com/iban-checker

And idea

### Environment Version

15.0.2

### Environment OS

linux

### Environment PHP

7.4

### Environment Database

10.3.35-MariaDB-cll-lve

**Comment by emheyarssi** [comment]
Hi,
I can't reproduce-

![Screenshot from 2022-07-22 17-39-35](https://user-images.githubusercontent.com/99648320/180474909-2848c8e4-f3fa-489a-b226-880b5e8d1eef.png)

In which country are you located?

**Comment by Mohaamaad7** [comment]
@emheyarssi Egypt

**Comment by frederic34** [comment]
php-iban lib has been updated in v16, can you try with this version ?

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/186500065-e97d771f-c1eb-49d4-9985-47c95bd923d0.png)
with v17

**Comment by lmag** [comment]
IBAN is ok 
EG350004158000005805010006383
Banque is ok - France
![image](https://user-images.githubusercontent.com/3288514/204055683-d06d3956-5358-4fca-bc01-89b20873a40a.png)
Banque is ok - Egypt
![image](https://user-images.githubusercontent.com/3288514/204055753-ec457e33-a77d-4c2f-a8c1-ca74072ef355.png)
Ok for tiers and employees
![image](https://user-images.githubusercontent.com/3288514/204056071-e9cf8818-debb-4681-b7fa-7c5367c59706.png)
