### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by Mohaamaad7** [Dolibarr/dolibarr#21545]
### Feature Request

Hello , 

Arabic is my mother tongue , The Arabic language provided by dolibarr is contains incorrect and incomprehensible terms.

And I corrected it by 70% and I am still completing the correction .

How can I send you what I did as my contribution to introducing the system to Arabic speakers?

And what are the required conditions to approved this translation in future versions?

**Comment by hregis** [comment]
@Mohaamaad7 
you can contribute here : https://explore.transifex.com/dolibarr-association/dolibarr

**Comment by Mohaamaad7** [comment]
> @Mohaamaad7 you can contribute here : https://explore.transifex.com/dolibarr-association/dolibarr

@hregis 

thank you so much 

I sent a join request and I am waiting for approval.

**Comment by ksar-ksar** [comment]
> > @Mohaamaad7 you can contribute here : https://explore.transifex.com/dolibarr-association/dolibarr
> 
> @hregis
> 
> thank you so much
> 
> I sent a join request and I am waiting for approval.

@eldy
