### ISSUE TITLE
Vendor VAT rate on service/product is not respected on invoice

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#21543]
### Bug

For shipping ("Fraktbeställning"), we have set up that the vendor Postnord has got 0% tax on this particular product. No other vendors have a link to this product. When adding the product to a vendor invoice, the tax setting is not respected and the invoice says 25% tax on this product, while it should be 0% (since we set that up).

### Environment Version

Dolibarr 15.0.0

### Expected and actual behavior

Expected value on invoice is 0% tax for this product / vendor.

### Attached files

![service_1](https://user-images.githubusercontent.com/11036018/180152171-e12dfccc-3a34-48df-be1e-a50ff038ae5d.png)
![service_2](https://user-images.githubusercontent.com/11036018/180152173-7c31caef-36ff-4824-9160-c1ea1743b300.png)

**Comment by TomNok** [comment]
Hi, this might be the same issue as I reported on #20287 . Patiently waiting for a fix..

**Comment by Ants-In** [comment]
i found the problem in v16 and my v15 works good. i fixed it for v16 and will set a pull request now

**Comment by TomNok** [comment]
Strange, as my first tests in v16 showed that the problem was fixed..

**Comment by Ants-In** [comment]
oh, in my v16 it is not working.
