### ISSUE TITLE
TimeSpent : object standardization

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#21548]
### Feature Request

The goal is to have a real technical object to manage time spent, so in the future we can use it on tickets or mo in addition of tasks.

### Use case

I'd like to enter times I spent regarding a ticket or a manufacturing order

### Suggested implementation

Creation of a TimeSpent object and use of it in the project/task module/class

### Suggested steps

- [ ] Rename llx_projet_task_time to llx_element_time
- [ ] Rename column fk_task to fk_element and add column element_type
- [ ] Fill the element_type column with the value 'task' for existing data
- [ ] Replace current usage of time spent by the new object (card, class, export, ...)

**Comment by atm-maxime** [comment]
@eldy could you tell us if such a standardization is ok for you so we get started on it ?

**Comment by JoAnMaFe** [comment]
the idea of a technical object to track, has long been demanded in Dolibarr, in fact some of us do this process by calling our project with the serial number of the technical object to be monitored and tracking from the tasks or tickets associated with it.
I think it would not be enough to change the name of some tables and fields and could disrupt some ideas settled in the projects.
It is possible that I do not understand your approach, but in my point of view, this new function should be somehow associated to the new equipment module (Assets).

**Comment by atm-maxime** [comment]
Our goal is to standardize the current timespent management, which only works with project tasks. After this standardization, we will be able to use timespent on tickets or manufacturing orders for example.

I don't see how timespent can be related to "the new equipment module (Assets)." which to my knowledge is an asset management regarding accountancy.

**Comment by algonomp** [comment]
Would it be possible for you guys to generalize it even more? In my case i would use it to record how much time my employees spent cleaning someones house.

My case: Customers sign a cleaning contract, it generates monthly invoices with a fixed cost amount and the cleaners get payed via the hours they spent cleaning. I don't use the Projekt/Leads module for this, just the contract and invoicing modul. It would be overkill to use the projekt modul and create a projekt for every customer.

**Comment by atm-maxime** [comment]
> Would it be possible for you guys to generalize it even more? In my case i would use it to record how much time my employees spent cleaning someones house.
> 
> My case: Customers sign a cleaning contract, it generates monthly invoices with a fixed cost amount and the cleaners get payed via the hours they spent cleaning. I don't use the Projekt/Leads module for this, just the contract and invoicing modul. It would be overkill to use the projekt modul and create a projekt for every customer.

The point is to standardize so we can use the timespent structure with any object. But this is only the structure. If after that you want to have timespent on contracts, you'll need a development to have the screens dealing with it. It seems to me that timespent on tasks, tickets and manufacturing orders are prioritary because it meets main needs.
