### ISSUE TITLE
Bug: preview

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#21559]
When I try to preview the created document of the project I get this message
![Screenshot 2022-07-22 at 12-49-54](https://user-images.githubusercontent.com/19837231/180433795-f38a8458-f62b-42c4-8d10-3b1f6f7e74d0.png)

**Comment by mikygee** [comment]
Hello,
You didn't display your permissions on the system.
Are you sure it's a bug and not a misconfiguration on your side ?
Regards
