### ISSUE TITLE
mail.collector not adding Attachments to Tickets

### ISSUE THREAD

**Issue by notyettested** [Dolibarr/dolibarr#21550]
### Bug

i saw that the mail-collector is supposed to put attachments on created tickets which is a function i´d like to use.

i tried several different mail providers after it did not work with my own mailserver just to be sure, no difference.

### Environment Version

15.0.2

### Environment OS

Ubuntu 20.4

### Environment Web server

Apache 2.4.41

### Environment PHP

7.4

### Expected and actual behavior

Expectation:
collector collects mail, creates ticket with attachment, marks mail as read and moves it to the target folder

actual behavior:
collector collects mail, marks it as read and moves it to target folder. ticket is created but without any Attachments.

**Comment by freechelmi** [comment]
Duplicate of #19569
