### ISSUE TITLE
Fix to do on website template for #21546

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#21568]
### Bug

This is a list of trouble to fix into the website template merged with #21546:
 
- After an import the image is not visible. This is surely a problem during the export . Because the export export only files with name  [image|js]/name_of_website/*   and your images are stored into   ./images/
Move images into the media dir called   /image/name_of_website

- The css of website overwritten the CSS of Dolibarr. You can fix this by changing like this
`htmltag or .mycsstag`
into
`.bodywebsite  htmltag or .mycsstag`
All css declarations must be prefixed with .bodywebsite so it has effect only into the website frame.

- The link for social networks must reuse the values defined into the setup of company. The list seems hardcoded and no value for links are inserted.   You can insert here php to loop on  $mysoc->social_networks  array.  Example is available into the page "footer" of the template-corporate.

- The button "Contact us" point to nothing, same for link "Pre Order" now. You can add a small page behind "contact us" (similar to the page "contact" of the template "corporate"), and for link "Pre Order" now, add a onclick  alert to say "Please edit the website page to define the URL you want the link to point to..."
-

**Comment by Quatadah** [comment]
all done (y)
