### ISSUE TITLE
Onlinesign proposal Download link

### ISSUE THREAD

**Issue by Teokun** [Dolibarr/dolibarr#21576]
### Bug

Hi, 

when the user open the Onlinesign link, the web page is ok, but the proposal downloadlink is in http:// format, if not using http redirect to https, link does not work properly, so i resolve this by editing the newonlinesign.php file and add before each printed link (3 times) : $directdownloadlink = str_replace("http://", "https://", $directdownloadlink);

is there another option to resolve my issue ?

### Environment Version

15.0.2

### Environment OS

Ubuntu 16.04

### Environment Web server

apache2

### Environment PHP

7.3

### Environment Database

mariadb 10.5

**Comment by emheyarssi** [comment]
`apache3` really?

**Comment by Teokun** [comment]
Sorry apache2, just missclicking :)

**Comment by hregis** [comment]
@Teokun have you https in your conf.php?

**Comment by Teokun** [comment]
> @Teokun have you https in your conf.php?

Yes, https option is set to 1 and url link too.

**Comment by emheyarssi** [comment]
> does not work with _my_ http to https redirect

What did you mean with _my redirect_?

**Comment by Teokun** [comment]
> > does not work with _my_ http to https redirect
> 
> What did you mean with _my redirect_?

http to https redirect rule on haproxy

**Comment by emheyarssi** [comment]
Okay... I don't know haproxy. 😑
Have you open a thread on the Dolibarr forum? There's more confortable to have a discussion. 
And maybe there is someone with a similar configuration

**Comment by Teokun** [comment]
Oh man, thank you for your post ! 

> Okay... I don't know haproxy. 😑
> Have you open a thread on the Dolibarr forum? There's more confortable to have a discussion.
> And maybe there is someone with a similar configuration

Oh man, thanks for your post ! I just check and finally my redirect was disabled. So it is normal that the online sign http url doesn’t be redirect automatically.
But think still be an issue, because if all conf use https, links have to be so, accordingly !

**Comment by hregis** [comment]
@Teokun
If you have this in your conf.php, no need for http redirect as you say. Moreover if you call dolibarr already in https the redirection is useless!

`$dolibarr_main_force_https="1";`

Maybe a configuration problem with your apache (missing https in apache) or your haproxy!

**Comment by rycks** [comment]
with your configuration dolibarr can't imagine that your haproxy will do http -> https rewrites so dolibarr will build all URI in plain http
the good solution is explained by @hregis : please use $dolibarr_main_force_https="1";
