### ISSUE TITLE
Error validating customer order

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#21582]
### Bug

I am writing a third-party module, that uses an external user, attached to a third-party contact, to create customer order, add lines, update extra fields and then validates the order. However, I am not able to validate the order.

### Environment Version

15.0-16.0

### Expected and actual behavior

When the external user is logged in, it has enough permissions and can create and validate customer orders.

When using `$commande->valid($user)` in the module same thing must happen. However, I get a response `Commande::valid NotEnoughPermissions` while the user has ALL permissions.

Module works fine on v14.0.4 - order is created and validated.

On v15 and v16, the order is created, all lines are added and extra fields are updated but cannot validate.

### Attached files

[dolibarr13.log](https://github.com/Dolibarr/dolibarr/files/9192255/dolibarr13.log)

**Comment by atm-maxime** [comment]
I just tested on the last version 15.0.3 and I had no trouble validating an order with an external user. Can you check ?
Do you have advanced rights management activated ?

**Comment by lmag** [comment]
I just tested on 16.0.2 it is ok for me to
