### ISSUE TITLE
Support different vat rates for purchase and selling of products

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#21629]
### Feature Request

In Sweden there is a special lower VAT rate on repairs of bikes. If I mount a product on a bike I bought with 25% VAT I only charge 6% VAT to the customer.

The goal of this is to increase incentives of repair over buying new bikes (which has 25% VAT). 

Dolibarr currently can only set one VAT rate per product. This makes it hard for me to buy/sell products with the correct VAT rate.

**Comment by dpriskorn** [comment]
Maybe this is already implemented as I can set tva_tx on purchase prices?

**Comment by hasse-basse** [comment]
You can can change the VAT per line when making the invoice. As SuperAdmin you can create as many VAT rates as you like and when you create the document, may it be the price proposal or the invoice you can choose the VAT rate you prefere, and in that way override the setting you have made in the the product card.
