### ISSUE TITLE
Wrong error message in dictionnary edition (Leaves)

### ISSUE THREAD

**Issue by Amael-PE** [Dolibarr/dolibarr#21624]
### Bug

Hello dev team,
The bug concern a too broad and not understandable error in Dictionnary - Leaves - Edit.
When the leave Code is too long, the error reported have no clear meaning.
The same problem arise if text is filled inside "compteur" field instead of binary value.

I suppose this fix should not be so long, and will help Dolibarr newcommers when configuring their instance...

Thanks for your amazing work !

### Environment Version

15.0.1

### Environment OS

Linux xxx.xxx.fr 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64

### Environment Web server

Apache

### Environment PHP

7.4.30

### Environment Database

MySQL or MariaDB 5.5.5-10.3.34-MariaDB-0ubuntu0.20.04.1

### Environment URL(s)

https://xxx.XXX.com/htdocs/admin/dict.php?id=28

### Expected and actual behavior

When:

-  leave code is too long (LEAVE_WEDDING_FAMILY is too long, LEAVE_WED_FAMILY passed, so probably >15 chars) 
- OR text is putted in "Compteur" field, instead of binary value

... Dolibarr just "crashed" and print a top-page black on white error message, indicating to look at the logs.

Instead, it should give a pretty red notification, indicating that the code is too long and should not exceed x characters OR to put only binary value in the corresponding field.

### Steps to reproduce the behavior

1. Go to Home > Config > Dictionnaries
2. Select "Leaves - Types"
3. Try to add a leave with code LEAVE_WEDDING_FAMILY, and proper information on other fields
4. Try to add a leave while puting some random text inside the "Compteur" field.

In both 3. and 4. case, you will get the following error shown:
```
This website or feature is currently temporarly not available or failed after a technical error.

This may be due to a maintenance operation. Current status of operation (2022-07-30T13:43:04Z) are on next line...

Dolibarr a détecté une erreur technique. Vous pouvez lire le fichier log ou définir l'option $dolibarr_main_prod sur '0' dans votre fichier de configuration pour obtenir plus d'informations
```

**Comment by atm-maxime** [comment]
Thanks for your feedback. The fact is that if the code is too long, it throws a database error message which was not displayed properly. I proposed a fix for this.
