### ISSUE TITLE
Check Lists for Tickets

### ISSUE THREAD

**Issue by git-putz** [Dolibarr/dolibarr#21628]
### Feature Request

I think it would be a great addition to be able to add check lists to tickets.

### Use case

Having checklists in tickets allows for a basic structure of direction for people that are assigned the tickets.
It ensures that routine and import items are performed based on type of ticket.

### Suggested implementation

This could be done 2 ways:
1 - ad-hoc after a ticket is created, click a "+" under checklist section within the ticket to add each checklist item
2 - the ability to create checklist templates and add the checklist template to the ticket which would import all the items from the template into the ticket.

You should be able to check off each item as completed and have it show date/time it was completed and by who marked it complete.

I googled "ticketing checklists" and these are a few examples

https://documentation.solarwinds.com/en/success_center/whd/content/helpdeskcreateticketchecklist.htm
https://www.youtube.com/watch?v=zCTKyuPOmTk

### Suggested steps

Unfortunately I am a systems engineer and not a developer so I do not have any insight on how to code this.

**Comment by EvoGamer** [comment]
This is something that could be easily implemented with the Project Tasks system. If a ticket could automatically make a task (or a series of tasks defined by a template), that should fill this role.

Personally, I'd want it to be separate from projects, as not every ticket needs a project, even if there are tasks to perform.
