### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by pedrouva** [Dolibarr/dolibarr#21651]
# Bug

At on https://mydomain.com.br/compta/resultat/result.php?leftmenu=accountancy_report

I have this error message below

Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.1) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59') ...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.1) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59') ...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.13,2.1.3.1,2.1.3.2,2.1.3.3,2.1.4,2.1.5,2.1.7,2.1.8) AND (t.doc_date BETWEEN ...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.1) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59') ...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.13,2.1.3.1,2.1.3.2,2.1.3.3,2.1.4,2.1.5,2.1.7,2.1.8) AND (t.doc_date BETWEEN ...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.1,1.2.2,1.2.3,1.2.4,1.2.5) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND...' at line 1

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: nginx/1.20.2
- **PHP**: fpm-fcgi 7.4.30
- **Database**: MySQL or MariaDB 5.5.5-10.5.16-MariaDB-1:10.5.16+maria~bionic-log
- **URL(s)**: /compta/resultat/result.php?leftmenu=accountancy_report

![image](https://user-images.githubusercontent.com/6031649/182707870-db19acdc-10a6-46e4-9a36-d46353cbaae5.png)

**Comment by daraelmin** [comment]
Hi @aspangaro ,

Do you understand this one ? I van mot identify thé number format between the comas.

Cheers
