### ISSUE TITLE
Hide 0,00 values in tables (reports)

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#21652]
### Feature Request

Here is what i have with a "normal dolibarr" on reports and others tables : all zero values are displayed

![avec_les_zero](https://user-images.githubusercontent.com/1468823/182715131-ae2b6b81-54d7-48dc-8539-4f37196288e9.png)

And here is what a wish, hide all zero values, table is now really more clear isn't it ?

![sans_les_zero](https://user-images.githubusercontent.com/1468823/182715271-7d91d5ca-eb85-488c-a236-e2a884f78f74.png)

**Comment by emheyarssi** [comment]
For me it should be configurable.

**Comment by edupulpillo** [comment]
Same opinion than @emheyarssi here.
Sometimes "copy/paste" in the screen is enough to import in a excel file, and is better to have the "0", but also is cool to be able to avoid it to read it more easily in the screen.
