### ISSUE TITLE
Invoice classed abandonned

### ISSUE THREAD

**Issue by atm-arnaud** [Dolibarr/dolibarr#21659]
### Bug

Abandonned invoice aren't used in reporting (annual sales)
They arn't in dashboard graphs

I have some doubt about the two possibilities :
- Replacment invoice : i'm ok to not count this invoice
- My customer is bankroute. How should i classify my invoice if not abandonned ?

### Environment Version

15.0

### Environment OS

Linux

**Comment by atm-maxime** [comment]
Abandoned invoices should be in reporting. The action of closing an unpaid invoice is related to the accounting action of adding an operation to put the unpaid amount in a specific third account (suspicious customer) or in losses. But the turnover of the invoice should remain. Same goes for a partially paid invoice.

**Comment by atm-maxime** [comment]
@aspangaro can you confirm?

**Comment by atm-maxime** [comment]
As for replacement invoices, I think it should be disabled by default for a french company because we can't use it, we have to use a credit note to cancel an invoice
