### ISSUE TITLE
TakePOS is not compatible with Lot/Serial module

### ISSUE THREAD

**Issue by mohamettarik** [Dolibarr/dolibarr#21680]
### Feature Request

I am using TakePOS in pharmacy, and as you know medicine have expiry. 

So the workflow is ordering, receiving order, then record quantities, lot numbers and expiry for each LOT as new stock. 

normally it is logic when i sell from POS, stock should decrease. but in case of using lot module, it is a impossible and not allowed to modify terminal or POS module settings. 

Any recommendation ?

**Comment by atm-maxime** [comment]
My guess is that takepos and the lot module have not been made compatible together. Maybe you need to find a developer to add this for you.

**Comment by Adventurousdonut** [comment]
There's a module for that on the dolistore made by the TakePOS devs:
https://www.dolistore.com/en/products-services-or-stock/1486-TakePOS-Lots---Serials.html?search_query=takepos&results=42

**Comment by Zulgrib** [comment]
"Compatible with | Dolibarr 13.x - 14.x"
Not a solution if it doesn't officially support last version.
