### ISSUE TITLE
RefCustomer in global Invoice

### ISSUE THREAD

**Issue by jbthevard** [Dolibarr/dolibarr#21693]
### Feature Request

Add RefCustomer in description in one grouped invoice of several command

### Use case

When I select several commands in the customer profil and I do a mensual invoice with several commands, Ref. Customer is not inclued in the description.
There is the dolibarr reference but not customer reference.
I have to add manually all of them.
In this attach file you can see the grouped invoice automatic, and after my intervention

![0gj1CDVOSvS8z9rR](https://user-images.githubusercontent.com/110894291/183603960-9024e256-f8f8-4dd8-ba35-af4e3554c55f.png)
![jhrbFg8Hc3BVTtQs](https://user-images.githubusercontent.com/110894291/183603964-78f0d824-8740-4cb6-9f9b-03c9363c6cf5.png)

**Comment by jbthevard** [comment]
Bonjour
Merci pour votre retour.
Effectivement la référence apparait maintenant.
En vous remerciant

**Comment by RaVaHgNu** [comment]
> Bonjour Merci pour votre retour. Effectivement la référence apparait maintenant. En vous remerciant

Bonjour, je rencontre le même problème, 
que faut-il faire pour faire apparaitre refcustomer sur les facture svp?
Merci.

**Comment by jbthevard** [comment]
![Capture d’écran 2023-08-11 105641](https://github.com/Dolibarr/dolibarr/assets/110894291/b940e911-360d-4cfc-b84a-e64de2b1874b)
ça apparait dans le PDF en "référence commande" et non dans la désignation des produits

**Comment by jbthevard** [comment]
Dans l'idéal si ça pouvait paraitre dans la désignation du produit ça serait top

**Comment by RaVaHgNu** [comment]
oui je sais pour la ref commande, mais a partir d'un nombre important de commandes, ça ne marche plus,
je facture régulièrement jusqu’à 70 commandes en une facture et rien ne s'affiche, seulement pour les factures avec une diazène se commandes,

**Comment by jbthevard** [comment]
Effectivement, c'est donc bien un problème.
Je ne sais pas comment modifier le modèle PDF pour configurer la désignation et l'objet de la facture groupée.
Merci aux codeurs !
