### ISSUE TITLE
Bug: Error 403 - Online Signature trying to Approve document.

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#21697]
# Bug
Online signature button doesn't work when trying to approve document, after sing.

Not commented yet in the forums (https://www.dolibarr.org/forum/t/online-signature-sign-button-inactive/22595)

## Environment
- **Version**: 15.0.3
- **OS**: Linux
- **Web server**: nginx/1.16.1
- **PHP**: fpm-fcgi 7.4.9
- **Database**:  5.5.5-10.3.29-MariaDB
- **URL(s)**: https://my.dolibarr.com/public/onlinesign/newonlinesign.php

## Expected and actual behavior
Button ACCEPT in online signature must approve the document with customer´s sign, but nothing happens and an error is shown in the browser console, in this case Mozilla Firefox 103.0.2, **also in other browsers.**

When the propal is declined, the button works well, it shows a warning to confirm the declination, but after decline, into the Dolibarr propal, there is no information about when or who (even the IP from were it was declined), even having an specific section on the flow of the document, (Budget Events in the lower right area of dolibarr), when has been validated, sent by mail, etc.

_¿How the Dolibarr user is expected to be notified when a quote is approved or rejected online?
Is it mandatory to activate all notifications about budget approval for this, or should online approval notify separately?_

## Steps to reproduce the behavior
After sing online and push accept button in Firefox, viewing the console:
**Error 403 - strict-origin-when-cross-origin -** Attached image

## Attached files
![Online_SING_Error](https://user-images.githubusercontent.com/15174724/183725621-d0cdff49-5bcd-450a-a0a9-2a9fcb339c79.jpg)

**Comment by hregis** [comment]
@PlanPc
The URL in your error message is the same of your dolibarr?

**Comment by PlanPc** [comment]
Hello @hregi

Sorry, If you mean the URL posted, (**URL(s): /comm/propal/card.php?id=1083**) I used the dolibarr button to create GitHub bug in the propal I was testing, sorry I missed to change it.

The real URL where the error occurred, is shown in the attached picture.

Don't think is important but the dolibarr where this ocurrs is in a subdomain:

https://my.dolibarr.com/

The real URL (I'll change it in this bug info) is this:

https://my.dolibarr.com/public/onlinesign/newonlinesign.php

**Comment by PlanPc** [comment]
Sorry, I closed this by error, editing and posting from a mobile device...

**Comment by avmecca** [comment]
I am also experiencing this issue on my VPS. 

It would appear that I'm getting a 403 error whenever I try to click the "submit" button. 

Is something broken on 15.0.3?

**Comment by PlanPc** [comment]
Also in 15.0.3 I'm experiencing problems with the import native module, since it's impossible pass the step 2, (on every type of import, clients, products, invoices, etc) where must select the type of file to import, CSV, XLSX, nothing is shown there...

If you have it enabled, ¿could you please tell me if that's also occurs in your dolibarr @avmecca ?

**Comment by avmecca** [comment]
@PlanPc 
I don't usually import. 

I've tried but keep getting random regex and data validation errors which would imply I can at least upload the sample file. 

Are you able to provide a known good sample import? I seem to be having trouble getting any import to work.

**Comment by hregis** [comment]
@avmecca https://github.com/Dolibarr/dolibarr/pull/21794/files

**Comment by avmecca** [comment]
@hregis Testing but this looks promising. I could at least sign in my test instance.

**Comment by avmecca** [comment]
@hregis This resolved the issue in my test sandbox. Now I have a different problem with the signature pad being missing on my prod instance but I think it's a different issue. Thank you and good work!

**Comment by PlanPc** [comment]
> @PlanPc I don't usually import.
> 
> I've tried but keep getting random regex and data validation errors which would imply I can at least upload the sample file.
> 
> Are you able to provide a known good sample import? I seem to be having trouble getting any import to work.

Thank you for your help @avmecca, my problem is that I can´t even select any file to import, in step 2 where file type is selected, nothing is shown below the message to pick a file. Even the native module "**DebugBar**" disappears when step 2 of any import is reached and the below error appears, the variable being **$dolibarr_main_prod='0';**.

[import_product_test.csv](https://github.com/Dolibarr/dolibarr/files/9376988/import_product_test.csv)


Attached is a file of some productos to import, create a file for import it's a horrible task for humans, also on dolibarr. Just was curious if it had anything to do with the problem with this issue.

In my case I get this, at step 2:


Warning: require_once(MyDolibarr.com/includes/phpoffice/phpspreadsheet/src/autoloader.php): failed to open stream: No such file or directory in MyDolibarr.com/core/modules/import/import_xlsx.modules.php on line 115 Fatal error: require_once(): Failed opening required 'MyDolibarr.com/includes/phpoffice/phpspreadsheet/src/autoloader.php' (include_path='MyDolibarr.com/**htdocs**') in MyDolibarr.com/core/modules/import/import_xlsx.modules.php on line 115

But in this Dolibarr instance there is no **htdocs** folder at all..., it only exists in the original packages downloaded from sourceforgue.net but the contect of htdocs is all pasted at my root folder, so no htdocs.

![Import_Error](https://user-images.githubusercontent.com/15174724/185594079-a7e3a0af-c4ec-4484-8843-59fafd2315c5.jpg)


in MyDolibarr.com/core/modules/import/**import_xlsx.modules.php on line 115** there only this:

`115		require_once DOL_DOCUMENT_ROOT.'/includes/phpoffice/phpspreadsheet/src/autoloader.php';`

I will try to investigate a little more, although the truth is that I do not know where to start after reviewing the files that this error points to.


-----------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------

About the online sign, I must make some test, but replacing the lines of code from here https://github.com/Dolibarr/dolibarr/issues/21697#issuecomment-1219607185, shows another errors in my dolibarr, cant reach the page of online sign, because an error about the security code in not correct.

**Comment by PlanPc** [comment]
Hello, I have applied [changes by](https://github.com/Dolibarr/dolibarr/issues/21697#issuecomment-1219607185) @hregis, but I'm having the same error.

1. By the way, the Dolibarr instance where I'm testing is not a multicompany scenario, I don't know if that detail can be of help, I hope so.

2. Another detail I didn't mentioned before is, the budget mask I'm trying to sign online is formed with an / in it. [**PO2022/1878**
](https://user-images.githubusercontent.com/15174724/185694203-889ff9de-2145-4fbc-b621-2f076216445e.jpg)
The error shown is exactly that:




[**Bad value for securitykey. Value provided aebb920fa6ec7eb5538075bdc85269b4 does not match expected value for ref=**
](https://user-images.githubusercontent.com/15174724/185692491-3ef293c5-98a5-40fc-8cc5-3423a2173fcf.jpg)


The reject button is working well and updates the status of the document in dolibarr, except that there is absolutely no notification into dolibarr, nor to the document creator, nor in the Budget Events, neither in the updated PDF budget, etc.

**Comment by PlanPc** [comment]
I have changed the budget numbering mask ( at doli/admin/propal.php), changed symbol **/** by the symbol  **-** ([Mentioned before](https://github.com/Dolibarr/dolibarr/issues/21697#issuecomment-1221046232))

Now it seems to work well for me, so I think this was the main problem to sign online. (Only I need to place the signature correctly as it appears above the total budget amounts.)

However, **the PDF propal must be generated before sending the link to sign it, and PDF file must exist in \DolibarrDocs** or it will fail when signing online, but there will be no error shown on screen.

I suppose that this functionality is still in testing, but I add this comment in case any developer reads it.

In case of sending a link to sign a quote, in version 15.0.3, it is possible to do it even if the PDF document does not exist, which will cause an error, difficult to detect for any normal user.

It will be great if the link to sign online, could be show only if the PDF file exists, (when you are at /comm/propal/card.php?id=xxx), to avoid unnecessary errors and problems with communication to customers.


Hope this could help other with same problem.

**Comment by JoSoG89** [comment]
I have 403 Error forbidden in my VPS
![imagen](https://user-images.githubusercontent.com/106213922/188297559-901b51ce-4804-4047-996c-e444304d1693.png)

**Comment by hregis** [comment]
can you try with this fix https://github.com/Dolibarr/dolibarr/pull/22471
