### ISSUE TITLE
Button "Corriger le stock"

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#21698]
### Bug

When we click on the line corresponding to a lot number of a item to adjust its stock, the lot number of the adjusting page is not written automatically.

### Environment Version

15.0.3

### Environment OS

Linux dolionline 5.15.39-1-pve #1 SMP PVE 5.15.39-1 (Wed, 22 Jun 2022 17:22:00 +0200) x86_64

### Environment Web server

Linux dolionline 5.15.39-1-pve #1 SMP PVE 5.15.39-1 (Wed, 22 Jun 2022 17:22:00 +0200) x86_64

### Environment PHP

7.0.33-0+deb9u12

### Environment Database

MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2

### Environment URL(s)

/product/stock/product.php?id=46&id_entrepot=1&action=correction&pdluoid=582

### Expected and actual behavior

After clicking on the line, the lot number should be automatically filled.

### Attached files

<img width="1755" alt="image" src="https://user-images.githubusercontent.com/3815422/183726941-e7d214d3-a86a-4c0f-ba8e-79b436b03a9c.png">

**Comment by Ants-In** [comment]
works for me.!

**Comment by syrinx75** [comment]
It doesn't work also on 16.0.3.
