### ISSUE TITLE
bug getCustomerOrderPieChart() with multicompany

### ISSUE THREAD

**Issue by pascaldaugeron** [Dolibarr/dolibarr#21717]
### Bug

With plugin MultiCompany activated, url `/comm/index.php` 
=> return all commands of all entities in the Chart

**Solution :**

file `core/lib/order.lib.php` => `function getCustomerOrderPieChart`

change `$sql .= " AND c.entity IN (".getEntity('societe').")";` by `$sql .= " AND c.entity IN (".getEntity($commandestatic->element).")";`

------------------------------

En français : avec le plugin Multicompany d'activé, la page d'accueil "Commerce" affiche le récap de toutes les commandes de toutes les entités dans le camembert de la box "Statistiques - Commandes". Seules les commandes de l'entité en cours devraient remonter.
Pour résoudre cela, il suffit de changer la fonction `getCustomerOrderPieChart` du fichier `core/lib/order.lib.php` à l'endroit indiqué plus haut.

### Environment Version

14.0.5

### Environment OS

Debian 9

### Environment Web server

Apache/2.4.25 (Debian)

### Environment PHP

PHP : 7.4.28 

### Environment Database

10.1.48-MariaDB-1~stretch - mariadb.org binary distribution

**Comment by frederic34** [comment]
@hregis
