### ISSUE TITLE
Contextual menus don't close after clicking on another one

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#21711]
### Bug

In the page with the list of all the invoices, it's possible to click and to download/visualise the invoice. When clicking on other invoices, the previous menus remain visible.

### Environment Version

15.0.3

### Environment OS

Linux dolionline 5.15.39-1-pve #1 SMP PVE 5.15.39-1 (Wed, 22 Jun 2022 17:22:00 +0200) x86_64

### Environment Web server

Apache

### Environment PHP

7.0.33-0+deb9u12

### Environment Database

MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2

### Environment URL(s)

/compta/facture/list.php?leftmenu=customers_bills

### Expected and actual behavior

To close after clicking on another contextual menu.

### Attached files

<img width="162" alt="image" src="https://user-images.githubusercontent.com/3815422/183964768-d07b5525-419a-4777-9645-d1b47a500fef.png">

**Comment by emheyarssi** [comment]
Ho, it's funny, I noticed yesterday for the first time the same issue on a v9.0.4 of Dolibarr

**Comment by emheyarssi** [comment]
> the same issue on a v9.0.4 of Dolibarr

Curiously I'm now unable to reproduce on this issue on the same installation with the same set of invoices.
