### ISSUE TITLE
leave request error , working date is not correct

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#21730]
### Bug

When you create a leave request in 15/08/2022 , set the country to  taiwan , then it will show the error that is " Your leave request does not contain working day. " .

But that is a working date in taiwan .
![image](https://user-images.githubusercontent.com/78349579/184361101-8f04a8d8-a459-47dd-b38c-82d50032c3eb.png)
 

### Environment Version

v15.0.2 and v15.0.3

### Environment OS

Deian 10

### Environment Web server

Apache/2.4.38 Apache/2.4.41

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.4.1

### Environment URL(s)

/holiday/card.php

### Expected and actual behavior

not show the error 

### Steps to reproduce the behavior

1. set country to taiwan
2. create a leave request and include 8/15/2022 .
3. it will not count 8/15 is a working day .

**Comment by lmag** [comment]
Work on 16.0.1
![image](https://user-images.githubusercontent.com/3288514/204056346-d7e627c1-fb59-4cf2-9018-152a70d7631d.png)

**Comment by lmag** [comment]
15/08/2022 is a Monday did you check this box ?
![image](https://user-images.githubusercontent.com/3288514/204056788-3520c93f-6227-4db2-908f-cc6e71f1971e.png)
