### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by giorgiobernardini** [Dolibarr/dolibarr#21737]
# Bug
Module: Park Management.
extra fields in any object get deleted when any record is modified and saved.

## Environment
- **Version**: 15.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.30
- **Database**: MySQL or MariaDB 5.5.5-10.3.32-MariaDB
- **URL(s)**: /custom/gestionparc/admin/setup.php?idmenu=253&mainmenu=gestionparc&leftmenu=

## Expected and actual behavior
Expected: Open a record, modify any record, save.
Actual: after saving one or more extra fields get deleted.

## Steps to reproduce the behavior
Modify any record when extra fields are present and save.

## [Attached files]
[bug_dollibar_compressed.pdf](https://github.com/Dolibarr/dolibarr/files/9330284/bug_dollibar_compressed.pdf)
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/9330298/dolibarr.log)

**Comment by ksar-ksar** [comment]
Hello,

This bug is related to an external module, please contact the developer of that module.
