### ISSUE TITLE
Personnaliser une réaction sur ajout d'un produit existant

### ISSUE THREAD

**Issue by vdegrandpre** [Dolibarr/dolibarr#21748]
### Feature Request

Ajouter un maillage pour réagir à l'erreur « ErrorProductAlreadyExists » lors de la création d'un nouveau produit (p. ex., rediriger automatiquement la navigation vers la page du produit existant).

### Use case

La création d'un produit avec un numéro de référence d'un produit existant génère une erreur d'interface sans donner de détail.
L'usager doit faire une recherche pour retrouver le produit existant à celui qu'il a tenté de créer, ce qui génère de la frustration.
L'usager aimerait soit voir un lien cliquable ou mieux, être simplement redirigé vers la page du produit existant, ou autre.

### Suggested implementation

Ajouter l'appel à une fonction de maillage « onProductAlreadyExists » sur la gestion de l'erreur ErrorProductAlreadyExists dans la carte produit, au moment où l'événement d'erreur est signalé à l'usager.

### Suggested steps

Développement fait, en attente de soumission et de validation.

**Comment by ksar-ksar** [comment]
Hello,

Can you write in English ?

I think it is quite nice idea, you said that you had developed this functionality ?
If yes you can open a PR on the develop branch ?

**Comment by vdegrandpre** [comment]
Oui, je le peux.

Je suis toujours surpris quand une personne vivant à Paris me demande d'écrire en langue étrangère ... Le PR a été fait et est déjà fusionné en develop.

Ja vais clore ce fil. Belle journée !

**Comment by ksar-ksar** [comment]
> Oui, je le peux.
> 
> Je suis toujours surpris quand une personne vivant à Paris me demande d'écrire en langue étrangère ... Le PR a été fait et est déjà fusionné en develop.
> 
> Ja vais clore ce fil. Belle journée !

Merci.

C'est juste que la langue du projet et l'anglais, c'est pour ça !

**Comment by BebZ** [comment]
Its Just because it is Always written in english so if you landed here, it means you can actually write it

**Comment by vdegrandpre** [comment]
Ha ! bien désolé, je travaille en français (surtout pour tout ce qui est gestion et créatif). Pour le code, par contre, vous trouverez des commentaires en anglais.
