### ISSUE TITLE
Bug: Company can't save if a linked User is already settet.

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#21771]
### Bug

Company can't save if a linked User is already settet.
I think the problem in the code is the following section:
https://github.com/Dolibarr/dolibarr/blob/f8dfe886ac67aff9e088c6b0c03e6c219a6f2162/htdocs/user/card.php#L491-L493

### Environment Version

15

### Environment OS

Windows 10

### Environment Web server

xxamp

### Environment PHP

7.4

### Environment Database

mariaDB

### Steps to reproduce the behavior

If you have a User with linked contact, looks like this:
![image](https://user-images.githubusercontent.com/78662388/184994456-a8b21c8a-a4d9-4902-8e9e-0cb35000892a.png)

If you like to add a link to a company (Modify => Select Company), looks like this:
![image](https://user-images.githubusercontent.com/78662388/184994687-8f4b2fe3-d0fd-443f-a3f4-ed3460e0038f.png)

All looks fine. But if you save the changes, the company link is lost.
![image](https://user-images.githubusercontent.com/78662388/184994866-37caeaf6-aeca-49e5-b2c6-840d54a09cb2.png)

**Comment by Humml87** [comment]
@eldy: What is the expected behavior?

**Comment by gschratzer** [comment]
An understandable error-message would in example help?!
for me it works fine, only you have to know, if you change you have to change for me understandable first other company and a contact of the same company.

what's sure false is this Info:
![image](https://user-images.githubusercontent.com/3923753/192133254-f3c97e7b-5a80-4165-b3f4-d02b1b0b31eb.png)

there is no field "type"
it is in Versions 15.0.3 and also in 16.0
