### ISSUE TITLE
Can't use API when mounted on server

### ISSUE THREAD

**Issue by jmielh** [Dolibarr/dolibarr#21788]
### Bug

For some reason when i'm working con localhost everything with the API is going well, but when I deploy on production server I get  a "weird" message because it is not an error message. I'm letting an image to show what I get, maybe i'm doing something wrong idk. 

### Attached files

![Dolibarr](https://user-images.githubusercontent.com/51181955/185350702-359b37d5-79de-41c6-b997-6bbc940d734b.png)

**Comment by frederic34** [comment]
missing directory htdocs/includes/restler/framework/Luracast/Restler/explorer ?

**Comment by lmag** [comment]
The access to the API seems correct, more information is needed to reproduce the issue
