### ISSUE TITLE
Inventory Rest API

### ISSUE THREAD

**Issue by invaderb** [Dolibarr/dolibarr#21781]
### Feature Request

Not sure if I'm missing a config setting but I'm not seeing an API for listing inventory of creating

### Use case

Looking for an API CRUD API for inventories

### Suggested implementation

Rest implamentation

**Comment by Humml87** [comment]
Hi,
you´re right. The resource have no REST API Class ("api_resource.class.php").
![image](https://user-images.githubusercontent.com/78662388/185229777-57701672-e820-46f5-ab84-99dc6f733b4a.png)

- [ ] GET /resources
- [ ] GET /resources/{id}
- [ ] POST /resources
- [ ] DELETE /resources/{id}
- [ ] PUT /resources/{id}
- [ ] POST/resources/{id}/contact/{contactid}/{type}
- [ ] DELETE /resources/{id}/contact/{contactid}/{type}

Best regards
Christian

**Comment by invaderb** [comment]
Also is there a discord or gitter chat for the community?

**Comment by atm-maxime** [comment]
Still relevant
