### ISSUE TITLE
Signed proposal makes the PDF put the signature outside the box

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#21787]
### Bug

This bug is reproducable in all doc templates for proposals ("azur" is seen in the screenshot), even our own which are based upon azur. The signature itself is created as it should, but it is placed below the signature box which kind of makes the document look very unprofessional. It should be moved upwards like 50-80 pixels.

### Environment Version

Dolibarr 15.0.0

### Expected and actual behavior

Expected behaviour is that the signature should fit right in the box.

### Steps to reproduce the behavior

Reproducable every time.

Create a proposal, use the link to digitally sign it, and the error appears.

### Attached files

![doli_sign_propale](https://user-images.githubusercontent.com/11036018/185336789-d95665d3-20af-47a5-9904-2aef96291890.png)

**Comment by Bertrand-22** [comment]
The better it will be to expand the signature square in the template azur

**Comment by bos4711** [comment]
Fair point. We solved this by changing `$tab_hl = 4;` to `$tab_hl = 6;` in the function `_signature_area()` in file `core/modules/propale/doc/pdf_azur.modules.php`. That enlarged the box and the signature fit nicely in it without going through any borders.

**Comment by bos4711** [comment]
@grandoc Did you even test your fix before commiting? This is what it looks like after applying your patch. The result is even worse than the original report.

Ping @eldy 


![Untitled](https://user-images.githubusercontent.com/11036018/205004684-55dd1ea3-4895-4bc4-a32e-f241341aea97.png)

**Comment by grandoc** [comment]
@bos4711 Yes I did test, and it was working
![it_works](https://user-images.githubusercontent.com/881589/205035798-c501bf45-ce52-4411-9c67-e0207eb7585f.png)

**Comment by grandoc** [comment]
@bos4711
There is this comment within the code :
// FIXME Position will be wrong with non A4 format. Use a value from width and height of page minus relative offset.

**Comment by bos4711** [comment]
We use A4 paper.
