### ISSUE TITLE
Task ODT template generation error when Project Ref has a grave accent in it's string name

### ISSUE THREAD

**Issue by berbascum** [Dolibarr/dolibarr#21795]
### Bug

Hi,

I'm using Dolibarr 15.0.3 in Debian Bookworm with mariadb 10.6.8  and a database with collation utf8mb3_spanish_ci, and php7.4

I'm trying to generate a Task ODT report with the native doc_generic_task_odt.modules.php and a custom template_task_summary.odt

When i set the "Project Ref" name including any grave accent char, the document is not generated.

But when renaming the Project Reference without any grave accent, the document generation works fine.

As additional information, the problem is only with Project Ref. If the Project Ref has no grave accent char in it's name, but the Task Ref does have it, the ODT generation also works fine.

Best Regards.

### Environment Version

15.0.3

### Environment OS

Debian 12 Bookworm

### Environment Web server

apache2 2.4.54-2

### Environment PHP

7.4

### Environment Database

mariadb 10.6.8-1 Collation:utf8mb3_spanish_ci

### Environment URL(s)

https://localhost/projet/tasks/task.php?id=1&withproject=1
./core/modules/project/task/doc/doc_generic_task_odt.modules.php

### Expected and actual behavior

Actual behavior:
When Project Ref name contains a grave accent, odt task report generation is not working

### Steps to reproduce the behavior

Configure a Project Ref with a name containing any grave accent.

**Comment by ksar-ksar** [comment]
Hello,

One remark : `Collation:utf8mb3_spanish_ci` => This is not good, Dolibarr collation needs to be utf8_general_ci

Regarding the bug, could you activate dolibarr log and also check hosting logs ?

**Comment by berbascum** [comment]
Hi ksar-ksar,

Thanks very much for the response.
Interesting information about general collation.
First i will deploy a new Dolibarr installation in a utc8_general_ci database and i will try again.

What is recomended utfmb3 or mb4?

If problem persist i can get apache2 and Dolibarr logs and post here.

Thanks again!
