### ISSUE TITLE
closed third parties

### ISSUE THREAD

**Issue by T3nS** [Dolibarr/dolibarr#21799]
### Bug

In orders, supplier orders and invoices it is possible to select a closed third party. This shouldn't be possible.

### Environment Version

15.0

### Environment OS

Windows 10

### Environment PHP

7.4

**Comment by dolibit-ut** [comment]
'closed third parties'  means with status inactive (?)

I can confirm the described behavior in Dolibarr 14 / 15 / 16
and think also that should not be possible - at least not for orders and invoices!

**Comment by T3nS** [comment]
Yes, when status value is not 1.
I fixed the bug temporarily but next update it will break.

For example in commande/card.php

`print img_picto('', 'company').$form->select_company('', 'socid', '((s.client = 1 OR s.client = 2 OR s.client = 3) AND s.status=1)', 'SelectThirdParty', 0, 0, null, 0, 'minwidth175 maxwidth500 widthcentpercentminusxx');`

**Comment by priojk** [comment]
Pull request #22393 provided.

**Comment by T3nS** [comment]
Thanks
