### ISSUE TITLE
Online signature not working in V15.0.3

### ISSUE THREAD

**Issue by Bertrand-22** [Dolibarr/dolibarr#21791]
### Bug

After the upgrade from V15.0.2 to V15.0.3 the sign online of proposal don't working.
The final file with signature is not create, not possible to validate the proposal online.

PS: the signature on n-page correction working with the V15.0.2 (with the copy of onlineSign.php)
Hence the bug cause is not the modification in the onlineSign.php file.

### Environment Version

V15.0.3

### Environment OS

Windows 11

### Environment PHP

7.4.28

**Comment by adpal06** [comment]
Hello, i have the same problem on 15.0.3

**Comment by Bertrand-22** [comment]
Yes, the problem is on the V15.0.3 (not 15.0.2)

**Comment by matDOTviguier** [comment]
Same problem here

**Comment by PlanPc** [comment]
A few weeks ago I opened the issue [21697](https://github.com/Dolibarr/dolibarr/issues/21697) about a similar problem.

¿Can anyone specify which is the error you ca see in your browser when trying the online signature, if any?

**Comment by fahadismail986** [comment]
Anyone have the fix of online signature issue?

**Comment by hregis** [comment]
can you try with this fix https://github.com/Dolibarr/dolibarr/pull/22471

**Comment by inoveaconseil** [comment]
I can't reproducce
