### ISSUE TITLE
Manufacturing Order OF: to be able to change their status

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#21801]
### Bug

An order 'Validated' or 'InProgress' can't be set manually into status 'Produced'.

### Environment Version

15.0.3

### Environment OS

Linux dolionline 5.15.39-3-pve #2

### Environment Web server

Apache

### Environment PHP

7.0.33-0+deb9u12

### Environment Database

MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2

### Environment URL(s)

/mrp/mo_production.php?id=1

### Expected and actual behavior

To be able to change the status of a Manufacturing Order, with the same flexibility than the Sales Orders.

**Comment by ksar-ksar** [comment]
Hello,

Sounds to be a Feature request not a bug no ?

**Comment by syrinx75** [comment]
Hello, as user, it seems to be a bug. But maybe the designer didn't see the feature like me.

**Comment by Humml87** [comment]
Hello,
i think this is not a Bug and i think it´s not a good idea to set a MO manually into status 'Produced'.
The premission to set the status to 'Produced' is all products to consum are consumed and the product to produce are produced.
![image](https://user-images.githubusercontent.com/78662388/185665002-fad88d6f-b343-43de-91a4-96a1a7af9d13.png)

**Comment by syrinx75** [comment]
You probably know better than me how Doli is built.

But I would say it's the same with a delivery not done or partially done. It's possible to change its status to 'delivered' or 'invoiced' without any contraint.

Also, a manufacturing order can partially produced and for external raisons coming from the factory, the management decides to not execute it fully. In this case, it's better to change its status to 'produced' because nobody will use any more.

**Comment by Humml87** [comment]
Hi,
in the MO you can click "CANCEL":
![image](https://user-images.githubusercontent.com/78662388/185687572-b4d11852-f220-4081-8d92-e7b91ae9a251.png)
is this what you mean?

**Comment by syrinx75** [comment]
I would say that an order partially produced is not cancelled.
An order cancelled is not at all produced and will never be produced.

**Comment by Humml87** [comment]
Hm, i think this is a special behavior that you can realise with "hooks" in your own environment.
