### ISSUE TITLE
Can't Create New User

### ISSUE THREAD

**Issue by observart** [Dolibarr/dolibarr#21812]
### Bug

When I fill out a form to create a new user, the page reloads, but no new user is created.
Please help me, I have tried to reinstall everything several times without success.

### Environment Version

15.0.3

### Environment OS

Windows 10

### Environment Web server

Nginx

### Environment PHP

PHP 7.2.5

### Environment Database

MySQL 5.7.24-winx64 started

### Expected and actual behavior

Expected: When I click the Create User button, a new user should be created
Actual Behavior: When I click the Create User button, the page reloads, but no new user is created.

**Comment by ksar-ksar** [comment]
Hello,

Can't reproduce it on my V15.0.3

Could you activate the dolibarr logs and have a look at them ?
Do you have any external module ? If yes, try to remove them one by one.

**Comment by komali2** [comment]
I had this issue when I tried to create a user with password with special characters (this password was not used in the end, it's safe to share) : `+m@7e=bc|uzbu'jN0bfGwv]p|` 

I can't figure out how to see logs
