### ISSUE TITLE
Delivery: warehouse selection is not applied

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#21828]
### Bug

I made a warehouse name 'Keg repair' which is a son of the warehouse 'Buzau'. We have a 3rd warehouse named 'Bucarest' which is at the same level than 'Buzau'.

When we make a delivery from 'Buzau', at the page to select the lot numbers of the items to deliver, the item in stock at 'Buzau' and at 'Bucarest' are proposed. It should have been listed only the items from Buzau,

### Environment Version

15.0.3

### Environment OS

Linux dolionline 5.15.39-3-pve #2

### Environment Web server

Apache

### Environment PHP

7.0.33-0+deb9u12

### Environment Database

MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2

### Environment URL(s)

/expedition/card.php?action=create&shipping_method_id=&origin=commande&origin_id=1338&projectid=&entrepot_id=1

### Expected and actual behavior

To list only the items of the location selected for a delivery.

### Attached files

![image](https://user-images.githubusercontent.com/3815422/185844945-eb718f67-9b57-4bf5-94e4-411801f4f605.png)
![image](https://user-images.githubusercontent.com/3815422/185845181-047cd138-63d2-442c-916b-c5a81360f47a.png)
![image](https://user-images.githubusercontent.com/3815422/185845566-ba2b9044-56b4-4cd1-b882-9263d3f73a62.png)
![image](https://user-images.githubusercontent.com/3815422/185845613-70a22c49-d663-4288-a113-8fab1bc6ab5d.png)

**Comment by milenmk** [comment]
This can happen if you do not have enough quantity in the originally selected warehouse

**Comment by syrinx75** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/3815422/186250062-c50902c9-5783-438c-854b-5ee138341f75.png">

The stock of the first item was enough quantity to be delivered from the selected warehouse.

**Comment by syrinx75** [comment]
This happens only if Keg repair' is a son of the warehouse 'Buzau'. If the 3 warehouses are the same level, all works as it should be.
