### ISSUE TITLE
$ID$ filter not working for Complementary attributes

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#21823]
### Bug

When I try to use the `$ID$` filter for a complementary attribute with the type "Select from table" it doesn't work.

### Environment Version

13,14

### Environment OS

ubuntu

### Environment Web server

apache

### Environment PHP

7.4

### Steps to reproduce the behavior

let's say I want to see the supplier ref for a product on the list and the product card

1. Create a Complementary attribute for a product, name it whatever you want.
2. For type set "Select from table"
3. For value type "product_fournisseur_price:ref_fourn:fk_product::$ID$"

The resulting query should be `SELECT fk_product as rowid, ref_fourn FROM llxlj_product_fournisseur_price WHERE fk_product = 'current_id'` while it is `SELECT fk_product as rowid, ref_fourn FROM llxlj_product_fournisseur_price WHERE fk_product = ''` i.e. the current product ID is blank

**Comment by atm-maxime** [comment]
I just tried on a 13.0 version and it works for me. I think you just made a little mistake on the "value" of your extrafield. Try with product_fournisseur_price:ref_fourn:rowid::fk_product=$ID$

The 3rd parameter is the column of your target table containing the ID that will link your object to the one of your table.
The 5th parameter is the full filter (e.g. fk_product=$ID$)

If you can make it work, please close the issue :wink:
