### ISSUE TITLE
V13+ word break of notes not working properly

### ISSUE THREAD

**Issue by altairis-arre** [Dolibarr/dolibarr#21822]
### Bug

since V13, word break of notes does not work anymore :

![image](https://user-images.githubusercontent.com/104210915/185779553-b2f93d58-413f-40ca-8d68-48639cda97e4.png)

it seems to come from CSS, core/tpl/notes.inc.php

replacing wordbreak by wordbreakimp correct the problem, but i do not know if it's the correct fix

line 120 (public notes)
`print '<div class="tagtd wordbreakimp table-val-border-col'.($editmode ? '' : ' sensiblehtmlcontent').'">'."\n";`

line 131 (private notes)
`print '<div class="tagtd wordbreakimp table-val-border-col'.($editmode ? '' : ' sensiblehtmlcontent').'">'."\n";`

![image](https://user-images.githubusercontent.com/104210915/185779683-0795b96a-be2e-4371-9942-cdbab68c1eb9.png)

### Environment Version
V13+

**Comment by FHenry** [comment]
/theme/eldy/global.inc.php

```
.wordbreakimp {
	word-break: break-word;
}
.wordbreak {
	word-break: break-all;
}
```
