### ISSUE TITLE
wording duplication

### ISSUE THREAD

**Issue by T3nS** [Dolibarr/dolibarr#21830]
### Bug

When I pass a proposal to an invoice, the label is duplicated if I have not defined a description for the item. See screenshot.

### Environment Version

14.0.5

### Environment OS

Windows 10

### Environment PHP

7.4

### Steps to reproduce the behavior

Create a commercial proposal for item without description and transform it into a customer invoice

### Attached files

Propal
![propal](https://user-images.githubusercontent.com/8088878/185876070-e01bfd8a-fb1d-4c1b-91cb-ee78076e155e.JPG)
 
become invoice
![invoice](https://user-images.githubusercontent.com/8088878/185876212-fdb681cc-d3de-4b8a-9d78-3c929e6055b1.JPG)

**Comment by ksar-ksar** [comment]
Hello,

I can't reproduce on V15.03, what is your dolibarr version ?

**Comment by T3nS** [comment]
Hello,
Sorry, I got the version wrong. this happens on version 14.0.5

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 14.0.5
