### ISSUE TITLE
how long will be the support for Dolibarr 15 ? 

### ISSUE THREAD

**Issue by RoseBlueRed** [Dolibarr/dolibarr#21857]

**Comment by aspangaro** [comment]
Hi,

In general, the last three version are maintained officialy. When version 18 is coming, version 15 will not support. But in fact, version 10 are already maintened today...

**Comment by RoseBlueRed** [comment]
Thanks for the answer. To have an idea, how long it will be supported for example 2 or 3 years minimum ? I need to know a range of years for the support

**Comment by aspangaro** [comment]
Officially, we are on 1 year and a half (3 versions with a new version every 6 months).
Unofficially, the versions are maintained for about 3-4 years but it may be necessary to call upon a prefered partner
