### ISSUE TITLE
Smiley encoding report

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#21892]
### Bug

Hello,

I installed a few months ago dolibarr on docker. However, I cannot add smileies to email templates according to the html standard (https://www.w3schools.com/charsets/ref_emoji_smileys.asp).

When I try to do this, I get an error message (I enabled debug mode):

```
**Requête dernier accès en base en erreur:** INSERT INTO llx_c_email_templates (label,lang,type_template,fk_user,private,position,topic,joinfiles,content,entity, active, enabled) VALUES('essai', '', 'all', null, 0, 1, 'dsfs', 1, 'I will display 😀', '1', 1, 1)
**Code retour dernier accès en base en erreur:** DB_ERROR_1366
**Information sur le dernier accès en base en erreur:** Incorrect string value: '\xF0\x9F\x98\x80' for column `basedetest`.`llx_c_email_templates`.`content` at row 1
```

After some searches on the internet, I realize that the problem comes from a database transport encoding problem (mysql in my case). All tables are encoded in `utf8mb4_unicode_ci`.

Can you correct this encoding issue ?

Thank you for your assistance 😄 

### Environment OS

15.0.3

### Environment Web server

apache 2

### Environment PHP

php 7

### Environment Database

mariadb:10.8.3

### Expected and actual behavior

No error when using html emojis

### Steps to reproduce the behavior

1. Configuration > emails > Email template
2. add new template 
3. add content `🥹`
4. on save the error occured

### Attached files

`docker-compose.yml`

version: '3.8'

services:
  mariadb:
    image: mariadb:10.8.3
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MARIADB_DATABASE: ${MARIA_DB_NAME}
      MARIADB_USER: ${MARIA_DB_USER}
      MARIADB_PASSWORD: ${MARIA_DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - perso

  dolibarr:
    image: upshift/dolibarr
    depends_on:
        - mydb
    ports:
        - 8089:80
    environment:
        DOLI_DB_HOST: mydb
        DOLI_DB_NAME: ${MARIA_DB_NAME}
        DOLI_DB_USER: ${MARIA_DB_USER}
        DOLI_DB_PASSWORD: ${MARIA_DB_PASSWORD}
        DOLI_ADMIN_LOGIN: ${DOLIBARR_ADMIN_LOGIN}
        DOLI_ADMIN_PASSWORD: ${DOLIBARR_ADMIN_DEFAULT_PASSWORD}
        DOLI_URL_ROOT: http://192.168.1.8
        DOLI_PROD: 0
    dns:
      - 8.8.8.8
      - 8.8.8.4
    networks:
      - perso

networks:
  perso:

**Comment by ksar-ksar** [comment]
Hello,

Dolibarr tables are supposed to be encoded in utf8_general_ci not in utf8mb4_unicode_ci.

**Comment by ghost** [comment]
Hello,

I have read many documents that explain that smiley are only compatible
with "utf8mb4_unicode_ci" encoding.

**Comment by frederic34** [comment]
Look at https://github.com/Dolibarr/dolibarr/pull/16483/files

**Comment by ghost** [comment]
> Look at https://github.com/Dolibarr/dolibarr/pull/16483/files

Thanks for this pull request.

I have change dolibarr database parameters on my dockerfile : 

DOLI_DB_CHARACTER_SET utf8mb4
DOLI_DB_COLLATION utf8mb4_unicode_ci

Now, there are no more error but when i save smiley into database, it is transform to ??? 

Is there an other configuration to do ?

**Comment by eldy** [comment]
smileys are binary data. They are not compatible with database feature for sorting and searching. It is no possible to insert them in a table with utf8mb4 format.
Tables must be converted into utf8mb4_bin (but you may experience other troubles). Solution has not been validated yet.

**Comment by shoorick** [comment]
The similar bug was found at https://demo.dolibarr.org/recruitment/recruitmentjobposition_note.php
I tried to add text, containing Unicode character above U+FFFF (Lady Beetle 🐞 U+1F41E) and see an error message:

> Incorrect string value: '\xF0\x9F\x90\x9E' for column `dolibarrdemo`.`llx_recruitment_recruitmentjobposition`.`note_public` at row 1

![image](https://user-images.githubusercontent.com/190892/235307885-ddb83e25-a130-4da3-b270-05c14e3362d2.png)

**Comment by shoorick** [comment]
> smileys are binary data

Not always. There are smiles which are pictures — they are binary data. But there are Unicode characters U+1xxxx — they are not binary, they are text, rendered with color fonts.

**Comment by frederic34** [comment]
see https://github.com/Dolibarr/dolibarr/pull/24561
