### ISSUE TITLE
Leave Balance always zero

### ISSUE THREAD

**Issue by kinqsley** [Dolibarr/dolibarr#21893]
### Leave Balance always zero
![image](https://user-images.githubusercontent.com/22793808/186830733-d38261ab-f1a9-4be6-ad50-bd00f06883fc.png)

### Dictionary setup - Leave - Types of leave
![image](https://user-images.githubusercontent.com/22793808/186830848-adacdaff-affe-488d-a672-b34b3d206769.png)

### Environment Version

15.0.3

### Environment OS

Ubuntu 20.04 (LTS) x64

### Environment Web server

Apache/2.4.41 (Ubuntu)

### Environment PHP

7.4.3

### Environment Database

MySQL 8.0.30

### Environment URL(s)

http://127.0.0.1/dolibarr/holiday/define_holiday.php?mainmenu=hrm&action=request

### Expected and actual behavior

Expected correct counters to be shown for all leaves type. But the page always shows the following message: 

**There is no leave types defined that need to be followed by a counter.**
**Go into Home - Setup - Dictionaries - Type of leave to setup the different types of leaves.**

### Attached files

![image](https://user-images.githubusercontent.com/22793808/186831979-f51b0b87-433c-4d4d-b3b5-3a3206563f53.png)

**Comment by ksar-ksar** [comment]
Hello,

The leave balance are calculated asynchronously via the "Schedule Job" module.
Be sure that Schedule Job is running well

![image](https://user-images.githubusercontent.com/35605507/186911365-a2ce8151-1cff-495e-8946-d2035cddb210.png)

**Comment by Terry-4ever-i** [comment]
The leave balance problem may be due to php-calendar not being installed

**Comment by kinqsley** [comment]
> Hello,
> 
> The leave balance are calculated asynchronously via the "Schedule Job" module. Be sure that Schedule Job is running well

It have enabled and scheduled but got a warning icon next to it.
![image](https://user-images.githubusercontent.com/22793808/187899295-cd065a0b-caa6-4a1d-a0b0-0ce19b18aa75.png)

After the job execution, still same issue.

**Comment by kinqsley** [comment]
> The leave balance problem may be due to php-calendar not being installed

Just checked, the **php-calendar** is enabled.
![image](https://user-images.githubusercontent.com/22793808/187899679-d9a3c292-6fa2-4c7f-9a1a-7fb82b2ce91f.png)

**Comment by frederic34** [comment]
You need to configure the value in New by Month column

**Comment by kinqsley** [comment]
Add value in New by Month column  
![image](https://user-images.githubusercontent.com/22793808/188532554-d0530a00-a2f1-4e68-a56b-e538893aa381.png)

Rerun the job (but it always show the warning icon - **Late**)
![image](https://user-images.githubusercontent.com/22793808/188532663-0d7b706b-ef58-4521-a8ef-572083da35bf.png)

Still same issue.
![image](https://user-images.githubusercontent.com/22793808/188532986-2edc1344-3b48-4d36-ab42-37a17e148e98.png)

![image](https://user-images.githubusercontent.com/22793808/188532947-5c6582b2-9c64-4d86-9507-a599cb2c7dfd.png)

**Comment by frederic34** [comment]
**Manage a counter** 0 or 1 if need to manage a counter

**Comment by kinqsley** [comment]
> **Manage a counter** 0 or 1 if need to manage a counter

Thank you. Now it works!
