### ISSUE TITLE
Proposal Chinese version

### ISSUE THREAD

**Issue by Bertrand-22** [Dolibarr/dolibarr#21891]
### Feature Request

The Chinese's proposal version is almost completed for the V15.0.2, missing Translates (zh_CN):
PaymentByTransferOnThisBankAccount       汇款至以下银行账户
PaymentConditions                                     付款条件
TotalHT                                                       不含税总额
BICNumber                                                 BIC/SWIFT 代码
IBANNumber                                              IBAN 帐号

**Comment by ksar-ksar** [comment]
Hello,

This needs to be proposed on https://www.transifex.com/dolibarr-association/dolibarr/language/zh_CN/
