### ISSUE TITLE
SQL errors on fresh install v16 / v17

### ISSUE THREAD

**Issue by aspangaro** [Dolibarr/dolibarr#21940]
### Bug

On a fresh install with version 16.0.0 & 17.0-alpha, SQL error on table llx_c_asset_disposal_type.

![image](https://user-images.githubusercontent.com/2341395/187200185-66d9d1cd-d826-4f3b-a1b5-64bc2eac2bca.png)

Table don't exist because asset module must be enabled. yet it tries to deploy the data

![image](https://user-images.githubusercontent.com/2341395/187200461-d39805da-2ed5-47ad-ab54-0d0f3bce5510.png)

Thanks for your return

### Environment Version

16,0,x / 17.0-alpha

### Environment PHP

8.1.7

### Environment Database

Mysql 5.7.36

### Environment URL(s)

http://localhost/v17/install/step2.php

**Comment by atm-maxime** [comment]
Hi @aspangaro , I don't have this issue any more. Ok to close ?
