### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by lokdocBelgium01** [Dolibarr/dolibarr#21974]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.4.16
- **Database**: MySQL or MariaDB 5.5.5-10.1.47-MariaDB-0+deb9u1
- **URL(s)**: /custom/btp/achat/btp_sales/card.php?action=add

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Report
- **Multicompany**: 15.0.2

**Comment by ksar-ksar** [comment]
Hello,

There is no bug description.

On the URL you report : /custom/btp/ => This is an external module. 
You need to ask the developer of that module.
