### ISSUE TITLE
The re-edition of the invoices is not done in the language of the customer

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#22005]
### Bug

When we regenerate a couple of invoices in the same time, the new invoices produced are in the language of the user (French) instead in the language established in the specs of the customers (Romanian).

### Environment Version

15.0.3

### Environment OS

Linux dolionline 5.15.39-3-pve #2 SMP PVE 5.15.39-3

### Environment Web server

Apache

### Environment PHP

7.0.33-0+deb9u12

### Environment Database

MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2

### Environment URL(s)

/compta/facture/list.php?leftmenu=customers_bills

### Expected and actual behavior

To regenerate all the invoices in the language of the customers.

### Attached files

![image](https://user-images.githubusercontent.com/3815422/187725978-dc2d886b-20b4-4ffc-a6fa-04b4651dfd2d.png)

**Comment by gschratzer** [comment]
See the same problem will try to do a bugfix pull request
