### ISSUE TITLE
Pas de création d'évènement sur les fiches d'interventions

### ISSUE THREAD

**Issue by Moonskytracer** [Dolibarr/dolibarr#22002]
### Bug

Sur les fiches d'interventions quand on envoie un mail avec la création d'événement automatique, l'évènement n'est pas créé.
Cela fonctionne parfaitement sur les commande et tous les autres documents

### Environment Version

14.0.4

### Environment OS

windows 10

**Comment by frederic34** [comment]
Dolibarr Version ?
Did you check agenda setup ?

**Comment by Moonskytracer** [comment]
Bonjour 


je n'avais pas validé sur le module agenda



Merci beaucoup


​Bechard Sébastien 

Direction Technique

09.72.52.04.97 / 06.61.71.11.03



SARL SBL CREATION

5158B Rue de la traverse Neuve

30460 LASALLE ( France) 

www.deslumieresdefeux.com







De : Frédéric FRANCE ***@***.***>
À : Dolibarr/dolibarr ***@***.***>
Sujet : Re: [Dolibarr/dolibarr] Pas de création d'évènement sur les fiches d'interventions (Issue #22002)
Date : 01/09/2022 16:30:53 Europe/Paris
Copie à : Moonskytracer ***@***.***>;
   Author ***@***.***>


Dolibarr Version ?
Did you check agenda setup ?

**Comment by frederic34** [comment]
Can you close the issue ?

**Comment by Moonskytracer** [comment]
Ys of corse


​Bechard Sébastien 

Direction Technique

09.72.52.04.97 / 06.61.71.11.03



SARL SBL CREATION

5158B Rue de la traverse Neuve

30460 LASALLE ( France) 

www.deslumieresdefeux.com







De : Frédéric FRANCE ***@***.***>
À : Dolibarr/dolibarr ***@***.***>
Sujet : Re: [Dolibarr/dolibarr] Pas de création d'évènement sur les fiches d'interventions (Issue #22002)
Date : 01/09/2022 16:58:47 Europe/Paris
Copie à : Moonskytracer ***@***.***>;
   Author ***@***.***>


Can you close the issue ?
