### ISSUE TITLE
Addition of a generic schedule table for all objects

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#22038]
### Feature Request

Addition of a generic schedule table for all objects

- [ ] DateStart
- [ ] DateEnd
- [ ] time zone

### Use case

Case 1 : 
management of company opening time slots
Case 2 : 
Third-party schedule management
Case 3 : 
Management of intervention or maintenance schedules on a contract
Etc...

### Suggested implementation

Validate datamodel
Add database
Transfert
![image](https://user-images.githubusercontent.com/3288514/188089335-ae4aab8e-13ed-4e07-bee1-ca820eecef70.png)
add a working time slot on the users
![image](https://user-images.githubusercontent.com/3288514/188092047-9eefd9e0-fb9e-454c-a8f6-6bb1c9e7f4ae.png)
add opening jours on third party
![image](https://user-images.githubusercontent.com/3288514/188092925-8751d050-9add-40e9-9a98-28109bd574a9.png)

**Comment by dolibit-ut** [comment]
Good idea.

But please with an option to hide this Tab (we have sometimes to much Tabs and loose clarity).

And until now this are 'only' text fields without function. 
In the future it would be a nice option to use the real clock time for more features like 
create agenda events only in the opening hours.
