### ISSUE TITLE
Question - AccountingJournalType9=Has-new

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#22051]
What is this for: 'Has New' ? 
Is that for 'Beginning of Balance? or for 'New Assets' or something else??

**Comment by aspangaro** [comment]
Hello @dolibit-ut 

In french, it's the term for an "A-nouveaux" journal.
This corresponds to an opening journal in accounting.
It will be used for the closing function of the accounting

**Comment by dolibit-ut** [comment]
Thank you

**Comment by priojk** [comment]
In German, this covers the "Eröffnungsbuchungen". I think, also the English translation as "has new" is not correct and misleading. On Transifex this literal translation propagated into many languages. Also in German it was originally the "HatNeu-Journal" and it took quite some investigation to find the intended meaning.
