### ISSUE TITLE
Bug: Import de champ de certains types de sociétés: Startup, Wholesale, Retail ne fonctionne pas

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22061]
### Bug

Version: 15.0.2

Bonjour,
Lorsque j'importe un Tiers et que je mets son type à 1,6 ou 7 correspondant respectivement à Startup, Wholesale ou Retail ce type n'est pas affiché
![image](https://user-images.githubusercontent.com/2222550/188266912-b9c5ead4-243f-4467-b99d-34063614f62a.png)

Pourtant en base, je vois bien que cela a été importé
> select nom,name_alias,fk_typent from llx_societe;
+---------------+------------+-----------+
| nom           | name_alias | fk_typent |
+---------------+------------+-----------+
| Legal Type1   | TE_STARTUP |         1 |
| Legal Type6   | TE_WHOLE   |         6 |
| Legal Type7   | TE_RETAIL  |         7 |
| Legal Type100 | TE_OTHER   |       100 |
+---------------+------------+-----------+

Les autres types fonctionnent, ici le type 100 correspondant à Autre fonctionne comme attendu.

Il existe ces types
> select id,code,libelle from llx_c_typent;
+-----+------------+-----------------------------------+
| id  | code       | libelle                           |
+-----+------------+-----------------------------------+
|   1 | TE_STARTUP | Start-up                          |
|   2 | TE_GROUP   | Grand groupe                      |
|   3 | TE_MEDIUM  | PME/PMI                           |
|   4 | TE_SMALL   | TPE                               |
|   5 | TE_ADMIN   | Administration                    |
|   6 | TE_WHOLE   | Grossiste                         |
|   7 | TE_RETAIL  | Revendeur                         |
|   8 | TE_PRIVATE | Particulier                       |
| 100 | TE_OTHER   | Autres                            |
| 231 | TE_A_RI    | Responsable Inscripto (typo A)    |
| 232 | TE_B_RNI   | Responsable No Inscripto (typo B) |
| 233 | TE_C_FE    | Consumidor Final/Exento (typo C)  |
+-----+------------+-----------------------------------+

Ci-joint un fichier csv de test

Cdt

### Environment Version

15.0.2

### Attached files

[Dolibarr-Tiers_Type_Entreprise-03Sep2022.csv](https://github.com/Dolibarr/dolibarr/files/9482409/Dolibarr-Tiers_Type_Entreprise-03Sep2022.csv)

**Comment by frederic34** [comment]
Are they active or inactive ?

**Comment by mikygee** [comment]
Hello, Active, See column D.

**Comment by frederic34** [comment]
Active in Dictionary ?

**Comment by mikygee** [comment]
Hello Frederic,
Thank you for this answer. Indeed, they are not activated.
![image](https://user-images.githubusercontent.com/2222550/188609133-7e460de1-3c0f-4748-a91e-12d5cde77237.png)
I'm going to retry with thses activated.

**Comment by mikygee** [comment]
Yes i tested, the problem was that they were not active in the dictionnary.

Do you know why are they disabled by default, it doesn't sound logical  to me.
As a small busines I'm interested in having wholesale for instance. Actually all these types should be enabled

**Comment by tiaris** [comment]
Activating/deactivating  things in dictionnaries is part of a dolibarr loacla configuration, in standard some datas are activated, but each user should adpat it to is needs.

**Comment by mikygee** [comment]
Those should be activated by default. There is no reason why they are not activated.
