### ISSUE TITLE
Bug: Terme Payment methods non traduit dans la version française

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22065]
### Bug

Version: 15.0.2

Bonjour,
Le terme "Payment methods" n'est pas traduit en français.
![image](https://user-images.githubusercontent.com/2222550/188268092-b17d9f6b-0d0e-4b5d-90d4-de50934bf8d7.png)

Cordialement

### Environment Version

15.0.2

**Comment by atm-maxime** [comment]
Hi. Thanks for feedback. Translations are made on transifex.

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 15.0.3

**Comment by mikygee** [comment]
Yes indeed, I see "mode de règlement".
Have a nice day
