### ISSUE TITLE
Bug: Message erreur en anglais pour mauvaise configuration du modele Elephant

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22079]
### Bug

Version: 15.0.2

Bonjour,
Dans la version française le message d'erreur du modèle Elephant est en anglais
![image](https://user-images.githubusercontent.com/2222550/188334801-2186cc0f-d9e2-4d20-96fc-a6d31aa770f0.png)
Cdt

### Environment Version

15.0.2

**Comment by ksar-ksar** [comment]
Hello,

I have the same behavior

**Comment by mikygee** [comment]
I tried it in 15.0.3 and it's the same. Thank you for the fix
![image](https://user-images.githubusercontent.com/2222550/188501899-bfd7b3c7-9296-4839-a5e8-b41ba9803520.png)
