### ISSUE TITLE
conf.php permissions are blocking installation

### ISSUE THREAD

**Issue by MedLabs** [Dolibarr/dolibarr#22077]
### Bug

Setup is not allowed by conf.php permissions
I get this message everytime I try to install Dolibarr.
I tried :
chmod -R 755 and even 777 for the whole dolibarr folder
chown apache.apache and nginx.nginx and my own user:group
and the check step is frozen in the same error message
I cleaned the cache and retried again, but Dolibarr install script can't write conf.php file
Tried with 15.0 15.0.3 and 16.0 same thing

### Environment Version

15.0.3,  16.0

### Environment OS

fedora linux

### Environment Web server

ngin

### Environment PHP

8.1.9

### Environment Database

mysql

### Expected and actual behavior

Expected, I get a start install button instead of the permission error message

### Steps to reproduce the behavior

git clone https://github.com/dolibarr/dolibarr -b 15.0
touch dolibarr/htdocs/conf/conf.php
sudo chmod -R 755 dolibarr
sudo chown -R apache.apache dolibarr
BONUS: sudo chmod 777 dolibarr/htdocs/conf/conf.php

**Comment by ksar-ksar** [comment]
Hello,

I have just tried, and I can't reproduce the issue.
Most probably something in your environment, prevent Dolibarr to access to this file.

**Comment by dolibit-ut** [comment]
Hello, 
are you sure with your 'chown -R  apache.apache'  ???
Because you wrote in your Environment you are using nginx?

Usually one you should take 'www-data.www-data' by chown.

**Comment by h3ssan** [comment]
Same issue in my Fedora 40,

and yes: `even 777 for the whole dolibarr folder` still says `Setup not allowed by conf.php permissions`

**Comment by h3ssan** [comment]
Just find out the solution.

The problem was occurred because of `SELinux` was enabled. Disable your SElinux and try again.
