### ISSUE TITLE
Feature Request: Importing "commerciaux" for Tiers should use the name of the Tiers and name of commercial

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22074]
### Feature Request

Version 15.0.2

Hello,

It's not convenient to import en masse commerciaux/sales people.
![image](https://user-images.githubusercontent.com/2222550/188304896-ca6dbfcd-a740-419b-afc1-8eb3d18c1a15.png)
What is requieried in the import file are primary keys
![image](https://user-images.githubusercontent.com/2222550/188304871-0d8aefb5-96cc-44a9-a391-2df6d28f3634.png)
So here as you can see I need to guess the primary key for Tiers and for the salesperson by doing all sorts of exports

What needs to be done is replacing "Nom du tiers* (sr.fk_soc)" by it's real name. For example, when importing bank accounts
![image](https://user-images.githubusercontent.com/2222550/188305086-faa3e2b2-0115-4c48-b129-85e2317304d4.png)
You can see that "TPBigCompany" is requiered not its id
![image](https://user-images.githubusercontent.com/2222550/188305026-2c5742a0-6e15-4648-bda7-d1d269e44ec1.png)

And replacing Utilisateur* (sr.fk_user) by login name Identifiant* (u.login)

The result should be something like that
![image](https://user-images.githubusercontent.com/2222550/188305204-68b2e6fe-7f6d-4895-bd2c-4e321bc3437a.png)

PS: It's also very strange that when importing sales people sr.fk_soc expects an id but when importing bank accounts sr.fk_soc expects "TPBigCompany"
Probably when we import bank accounts the proper term is not sr.fk_soc but it's something else.

Regards

**Comment by apio-sys** [comment]
Just came across the same issue and it works for me in 15.0.3 with name of tiers and login of sales rep.

**Comment by apio-sys** [comment]
Yes close it, as I mentioned above, works since 15.0.3.
