### ISSUE TITLE
Pièce jointe des relances factures

### ISSUE THREAD

**Issue by Max84** [Dolibarr/dolibarr#22096]
### Bug

Quand une tâche planifiée envoi les relances de factures automatiquement, la pièce jointe n'est pas présente dans l'email.

### Environment Version

14.0.4

### Environment OS

Debian

### Environment Web server

Apache

### Environment PHP

7.1

### Environment Database

MariaDB

### Steps to reproduce the behavior

1) Créer un modèle d'email en activant l'envoi de la pièce-jointe
2) Activer le module tâches planifiées et activer l'envoi des relances factures

L'email reçu ne contient pas de pièce-jointe.

**Comment by freechelmi** [comment]
Please could you translate your ticket to english , easier for contributors to help you.
