### ISSUE TITLE
Module Ressources - not use origin - but location address

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#22121]
### Feature Request

at module ressources we have a field  'Country of origin'

but in my opinion this makes not really sense

we need instead a location address

**Comment by braito4** [comment]
it should be location and time zone

**Comment by dolibit-ut** [comment]
hey, why timezone? 
Can you explain it briefly?

**Comment by braito4** [comment]
Well, resources: cars, conference both,... cold be part of a company in another country or timezone. If you book or use that resource you should when is in use from your timezone. (the data is introduce in the timezone of user)

**Comment by dolibit-ut** [comment]
okay

but if we use a complete address, the time zone could also be derived from it

**Comment by josett225** [comment]
Still required unless already there.
