### ISSUE TITLE
Setup -> Dictionaries -> Contact/Address types - problem with additions of extra modules

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#22140]
### Bug

Setup -> Dictionaries -> Contact/Address types - problem with additions of extra modules

if ou have an additional third-party module with own entries in this dictionary
you can not edit (e.g. change label), because the Element (Source Module) is not displayed
and cannot be selected or typed in

### Environment Version

Dolibarr 15.0.3 tested

### Environment OS

Linux Debian 10

### Environment Web server

Apache2

### Environment PHP

PHP 7.4.30

### Environment Database

MariaDB

**Comment by eldy** [comment]
I tested with 15.0.3 and di not experience trouble. Even if entry was added by an external module with field module = 'mymodule', i am still able to edit the line.

**Comment by dolibit-ut** [comment]
my Screenshots:

Pic 1 - Order - all okay
![Dolibarr-15 0 3_Dictionaries_Contact-Address-Types_#1_Element_ok](https://user-images.githubusercontent.com/45215329/189479244-5e574fed-0847-47f7-ad0b-6fe5fe17230c.png)

Pic 2 - ConfBooth - Element not shown
![Dolibarr-15 0 3_Dictionaries_Contact-Address-Types_#2_Element_not-ok](https://user-images.githubusercontent.com/45215329/189479265-361e5952-4d26-40e1-b153-1c5089ff20ef.png)

Pic 3 - no Element ConfBooth in List
![Dolibarr-15 0 3_Dictionaries_Contact-Address-Types_#3_Element_cannot-choose](https://user-images.githubusercontent.com/45215329/189479270-5990b118-7531-4002-8cff-72517e8f249f.png)

Pic 4 - can not save edits
![Dolibarr-15 0 3_Dictionaries_Contact-Address-Types_#4_cant_edit_save](https://user-images.githubusercontent.com/45215329/189479280-2be88e9d-960f-440b-8c91-300e0196fa28.png)
