### ISSUE TITLE
improve front accessibility

### ISSUE THREAD

**Issue by kevinderome** [Dolibarr/dolibarr#22150]
Hello,
I want to improve Dolibarr accessibility for blind people.
However I would like to do it in the best way. The "theme" folder seems to load only CSS.
How to identify frontend parts?

I will start with the core and then the modules.

Thank you very much for your advice.

**Comment by eldy** [comment]
You must not start to identify frontend part.
You must first identify what kind of change you plan to do. Once done we will be able to tell you where to change this.
