### ISSUE TITLE
Multipe warnings in PHP 8.1 with Dolibarr 16.0.0

### ISSUE THREAD

**Issue by JorgeCarousel** [Dolibarr/dolibarr#22163]
### Bug

Hey guys,

I just installed Dolibarr 16.0.0 on a WAMP Server with PHP 8.1, evrything looks fine, but Apache error.log shows these:

> [Thu Sep 08 14:42:55.759778 2022] [fcgid:warn] [pid 24404:tid 484] [client 192.168.1.10:4934] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_IHM_PARAMS_REV in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\modules.php on line 249, referer: https://dolibarr.example.com/admin/modules.php?mainmenu=home
> [Thu Sep 08 15:15:12.216690 2022] [fcgid:warn] [pid 24404:tid 980] [client 192.168.1.10:5259] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_TLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 218, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 15:15:12.216690 2022] [fcgid:warn] [pid 24404:tid 980] [client 192.168.1.10:5259] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_STARTTLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 220, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 15:15:12.216690 2022] [fcgid:warn] [pid 24404:tid 980] [client 192.168.1.10:5259] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_SMTP_ALLOW_SELF_SIGNED in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 222, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 15:15:12.216690 2022] [fcgid:warn] [pid 24404:tid 980] [client 192.168.1.10:5259] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_TLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 245, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 15:15:12.216690 2022] [fcgid:warn] [pid 24404:tid 980] [client 192.168.1.10:5259] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_STARTTLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 247, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 15:15:12.216690 2022] [fcgid:warn] [pid 24404:tid 980] [client 192.168.1.10:5259] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_SMTP_ALLOW_SELF_SIGNED in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 249, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 15:15:12.216690 2022] [fcgid:warn] [pid 24404:tid 980] [client 192.168.1.10:5259] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_DKIM_ENABLED in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 251, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:14:28.136243 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5897] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_TLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 218, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:14:28.137236 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5897] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_STARTTLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 220, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:14:28.137236 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5897] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_SMTP_ALLOW_SELF_SIGNED in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 222, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:14:28.137236 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5897] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_TLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 245, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:14:28.137236 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5897] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_STARTTLS in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 247, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:14:28.137236 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5897] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_SMTP_ALLOW_SELF_SIGNED in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 249, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:14:28.137236 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5897] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_EMAIL_DKIM_ENABLED in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 251, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home
> [Thu Sep 08 16:15:52.970801 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5912] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_SMTPS_ID in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 613, referer: https://dolibarr.example.com/admin/mails.php?action=edit&token=217f3ec85860343e71dd2c0d9d6ce320
> [Thu Sep 08 16:15:52.970801 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5912] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_SMTPS_PW in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 618, referer: https://dolibarr.example.com/admin/mails.php?action=edit&token=217f3ec85860343e71dd2c0d9d6ce320
> [Thu Sep 08 16:16:23.752914 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5924] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_SMTPS_ID in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 613, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home&leftmenu=setup
> [Thu Sep 08 16:16:23.752914 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5924] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_SMTPS_PW in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 618, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home&leftmenu=setup
> [Thu Sep 08 16:16:23.752914 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5924] mod_fcgid: stderr: PHP Warning:  Undefined array key "fileinit" in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\core\\class\\html.formmail.class.php on line 426, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home&leftmenu=setup
> [Thu Sep 08 16:16:23.752914 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5924] mod_fcgid: stderr: PHP Warning:  Undefined property: FormMail::$errorstomail in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\core\\class\\html.formmail.class.php on line 1182, referer: https://dolibarr.example.com/admin/mails.php?mainmenu=home&leftmenu=setup
> [Thu Sep 08 16:16:45.717698 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5926] mod_fcgid: stderr: PHP Warning:  Undefined array key "tomail" in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\core\\actions_sendmails.inc.php on line 189, referer: https://dolibarr.example.com/admin/mails.php?action=test&mode=init
> [Thu Sep 08 16:16:45.717698 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5926] mod_fcgid: stderr: PHP Warning:  Undefined array key "cc" in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\core\\class\\smtps.class.php on line 1243, referer: https://dolibarr.example.com/admin/mails.php?action=test&mode=init
> [Thu Sep 08 16:16:45.717698 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5926] mod_fcgid: stderr: PHP Warning:  Undefined property: SMTPs::$_moreinheader in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\core\\class\\smtps.class.php on line 307, referer: https://dolibarr.example.com/admin/mails.php?action=test&mode=init
> [Thu Sep 08 16:16:45.807927 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5926] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_SMTPS_ID in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 613, referer: https://dolibarr.example.com/admin/mails.php?action=test&mode=init
> [Thu Sep 08 16:16:45.808929 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:5926] mod_fcgid: stderr: PHP Warning:  Undefined property: stdClass::$MAIN_MAIL_SMTPS_PW in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\admin\\mails.php on line 618, referer: https://dolibarr.example.com/admin/mails.php?action=test&mode=init

I sent a test email from Dolibarr and it worked.

### Environment Version

16.0.0.0

### Environment OS

Windows 11 Pro for Workstations

### Environment Web server

Apache 2.4.53 x64

### Environment PHP

8.1

### Environment Database

MariaDB 10

### Expected and actual behavior

N/A

### Steps to reproduce the behavior

N/A

**Comment by emheyarssi** [comment]
AFAIK php 8 isn't fully supported yet.
https://wiki.dolibarr.org/index.php/Releases

**Comment by JorgeCarousel** [comment]
Here are more from other modules, by the way, I know it's not fully supported, I'm just telling you where issues are:

[Thu Sep 08 17:46:37.678172 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:7119] mod_fcgid: stderr: PHP Warning:  Undefined variable $projectid in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\projet\\tasks.php on line 742, referer: https://dolibarr.example.com/projet/index.php?mainmenu=project&leftmenu=
[Thu Sep 08 17:46:37.679167 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:7119] mod_fcgid: stderr: PHP Warning:  Undefined variable $nbrows in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\projet\\tasks.php on line 783, referer: https://dolibarr.example.com/projet/index.php?mainmenu=project&leftmenu=
[Thu Sep 08 17:48:22.709234 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:7133] mod_fcgid: stderr: PHP Warning:  Undefined variable $projectid in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\projet\\tasks.php on line 742, referer: https://dolibarr.example.com/projet/tasks.php?leftmenu=tasks&action=create
[Thu Sep 08 17:48:22.711229 2022] [fcgid:warn] [pid 24404:tid 500] [client 192.168.1.10:7133] mod_fcgid: stderr: PHP Warning:  Undefined variable $nbrows in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\projet\\tasks.php on line 783, referer: https://dolibarr.example.com/projet/tasks.php?leftmenu=tasks&action=create
[Fri Sep 09 08:50:17.746694 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:9981] mod_fcgid: stderr: PHP Warning:  Undefined variable $virtualurl in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2782, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=1872
[Fri Sep 09 08:50:17.746694 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:9981] mod_fcgid: stderr: PHP Warning:  Undefined variable $virtualurl in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2786, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=1872
[Fri Sep 09 08:50:17.746694 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:9981] mod_fcgid: stderr: PHP Warning:  Undefined variable $virtualurl in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2787, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=1872
[Fri Sep 09 08:50:17.746694 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:9981] mod_fcgid: stderr: PHP Warning:  Undefined variable $dataroot in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2801, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=1872
[Fri Sep 09 08:50:17.746694 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:9981] mod_fcgid: stderr: PHP Warning:  Undefined variable $dataroot in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2828, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=1872
[Fri Sep 09 08:51:33.445111 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:10073] mod_fcgid: stderr: PHP Warning:  Undefined variable $virtualurl in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2782, referer: https://dolibarr.example.com/core/tools.php?mainmenu=tools&leftmenu=
[Fri Sep 09 08:51:33.445111 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:10073] mod_fcgid: stderr: PHP Warning:  Undefined variable $virtualurl in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2786, referer: https://dolibarr.example.com/core/tools.php?mainmenu=tools&leftmenu=
[Fri Sep 09 08:51:33.445111 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:10073] mod_fcgid: stderr: PHP Warning:  Undefined variable $virtualurl in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2787, referer: https://dolibarr.example.com/core/tools.php?mainmenu=tools&leftmenu=
[Fri Sep 09 08:51:33.445111 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:10073] mod_fcgid: stderr: PHP Warning:  Undefined variable $dataroot in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2801, referer: https://dolibarr.example.com/core/tools.php?mainmenu=tools&leftmenu=
[Fri Sep 09 08:51:33.445111 2022] [fcgid:warn] [pid 24404:tid 1076] [client 192.168.1.10:10073] mod_fcgid: stderr: PHP Warning:  Undefined variable $dataroot in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 2828, referer: https://dolibarr.example.com/core/tools.php?mainmenu=tools&leftmenu=
[Fri Sep 09 08:54:46.958185 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pagetitle in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3814, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.958185 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pageurl in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3821, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.958185 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pagealiasalt in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3828, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.958185 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pagedescription in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3834, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.958185 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pageimage in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3841, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.958185 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pagekeywords in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3849, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.958185 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pagelang in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3874, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.959180 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined property: WebsitePage::$fk_page in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3920, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.959180 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pageallowedinframes in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 3940, referer: https://dolibarr.example.com/website/index.php?website=project-folder
[Fri Sep 09 08:54:46.959180 2022] [fcgid:warn] [pid 24404:tid 1028] [client 192.168.1.10:10100] mod_fcgid: stderr: PHP Warning:  Undefined variable $pagehtmlheader in D:\\Apache24\\htdocs\\dolibarr\\htdocs\\website\\index.php on line 4031, referer: https://dolibarr.example.com/website/index.php?website=project-folder
