### ISSUE TITLE
does not load the es_VE dictionary

### ISSUE THREAD

**Issue by geralbertortiz** [Dolibarr/dolibarr#22166]
### Bug

In the environment configuration I have the default language: Spanish Venezuela, es_VE

In the forms when creating a new third party and selecting the country Venezuela, the RIF and RIF Verification boxes do not load. "Professional ID 1" "Professional ID 2" "Professional ID 3" "Professional ID 4" continues to appear. . . etc.

any way to fix this?

If I select the country Colombia, for example, the "Professional ID" boxes are removed and the RUT box appears.

it just doesn't happen with Venezuela.

### Environment Version

15.0.3

### Environment OS

windows

### Attached files

![image](https://user-images.githubusercontent.com/113158916/189269765-17d4d2ae-6845-4dda-84bd-97d5125f3033.png)

![image](https://user-images.githubusercontent.com/113158916/189269810-ac63f008-37e9-4929-a76e-49c4b60c336d.png)

**Comment by eldy** [comment]
In translation files we found the lines for CO
ProfId1CO=Prof Id 1 (R.U.T.)
ProfId2CO=-
ProfId3CO=-
ProfId4CO=-
ProfId5CO=-
ProfId6CO=-
But no specific name for the field for venezuela. So translation appears as ID Professional 1, ...
What should be the list of professionnal ID label that is used in VE ?
