### ISSUE TITLE
Table not created during install

### ISSUE THREAD

**Issue by JorgeCarousel** [Dolibarr/dolibarr#22164]
### Bug

Hey guys,

I just installed Dolibarr 16.0.0.0, it showed no errors during installation, I enabled the modules I needed (Projects one of them), created a test project, bu when i tried to delete it, it said that table llx_don did not exist, i checked the database and it didn't, luckily I found the sql file to create it, but this should have been created during install.

### Environment Version

16.0.0.0

### Environment OS

Windows 11 Pro for Workstations

### Environment Web server

Apache 2.4.53 x64

### Environment PHP

8.1

### Environment Database

MariaDB 10

### Expected and actual behavior

Create the Table during install

### Steps to reproduce the behavior

Run a clean install of Dolibarr 16.0.0.0

**Comment by emheyarssi** [comment]
AFAIK php 8 isn't fully supported yet
https://wiki.dolibarr.org/index.php/Releases
