### ISSUE TITLE
vendor order approval

### ISSUE THREAD

**Issue by dallenrpccs** [Dolibarr/dolibarr#22243]
Fatal error: Uncaught Error: Call to undefined function mime_content_type() in C:\dolibarr\www\dolibarr\htdocs\core\class\notify.class.php:824 Stack trace: #0 C:\dolibarr\www\dolibarr\htdocs\core\triggers\interface_50_modNotification_Notification.class.php(79): Notify->send('ORDER_SUPPLIER_...', Object(CommandeFournisseur)) #1 C:\dolibarr\www\dolibarr\htdocs\core\class\interfaces.class.php(183): InterfaceNotification->runTrigger('ORDER_SUPPLIER_...', Object(CommandeFournisseur), Object(User), Object(Translate), Object(Conf)) #2 C:\dolibarr\www\dolibarr\htdocs\core\class\commonobject.class.php(5559): Interfaces->run_triggers('ORDER_SUPPLIER_...', Object(CommandeFournisseur), Object(User), Object(Translate), Object(Conf)) #3 C:\dolibarr\www\dolibarr\htdocs\fourn\class\fournisseur.commande.class.php(1091): CommonObject->call_trigger('ORDER_SUPPLIER_...', Object(User)) #4 C:\dolibarr\www\dolibarr\htdocs\fourn\commande\card.php(976): CommandeFournisseur->approve(Object(User), '', 0) #5 {main} thrown in C:\dolibarr\www\dolibarr\htdocs\core\class\notify.class.php on line 824

**Comment by ksar-ksar** [comment]
Hello,

mod_mime it's missing in your PHP installation

**Comment by dallenrpccs** [comment]
Are you able to add it or can I add it without breaking it Get Outlook for Android

**Comment by ksar-ksar** [comment]
Hello,

In your hosting environment you need to install/activate PHP-mime extension

**Comment by dallenrpccs** [comment]
We're can I get the install file we are on server 2019Get Outlook for Android
