### ISSUE TITLE
Bug on prelevement module

### ISSUE THREAD

**Issue by Liammer** [Dolibarr/dolibarr#22244]
### Bug

Hi there!
I installed Dolibarr 15.0.2 (working on 14 before) and hav an issue with prelevement module. I can't create a new prelevement. When I click on the button I have a blank page. Here is the error log:
`[Mon Sep 12 15:59:36.470599 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1208, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470617 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 2290, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470624 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1220, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470657 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1208, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470663 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1220, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470682 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1208, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470688 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1220, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470705 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1208, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:36.470710 2022] [php:warn] [pid 3931668] [client ] PHP Warning:  Undefined property: BonPrelevement::$type in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1220, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:44.300946 2022] [php:warn] [pid 3932165] [client 78.204.125.136:62492] PHP Warning:  Undefined variable $socid in /home/[...]/compta/prelevement/create.php on line 364, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:44.301466 2022] [php:warn] [pid 3932165] [client 78.204.125.136:62492] PHP Warning:  Undefined variable $socid in /home/[...]/compta/prelevement/create.php on line 390, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 15:59:44.301474 2022] [php:warn] [pid 3932165] [client 78.204.125.136:62492] PHP Warning:  Undefined variable $option in /home/[...]/compta/prelevement/create.php on line 393, referer: https://mywebsite.com/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
[Mon Sep 12 16:00:00.100436 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_BANQUE in /home/[...]/compta/prelevement/create.php on line 125, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.100470 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_GUICHET in /home/[...]/compta/prelevement/create.php on line 125, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.132760 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Trying to access array offset on value of type null in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 934, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143174 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143197 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143207 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143219 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143227 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143238 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143245 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143253 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143261 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143276 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143282 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143290 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143296 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143303 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143310 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep
 12 16:00:00.143318 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143324 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143331 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143337 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143344 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143351 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143360 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143367 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143374 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143380 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143388 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143394 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143402 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143408 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143415 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143421 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143428 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143435 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143443 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143450 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143459 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143466 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143473 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143479 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143486 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143493 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143500 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143508 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143516 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143523 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon
 Sep 12 16:00:00.143531 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143539 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143546 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143552 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143559 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143565 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143573 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143579 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143586 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143593 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143599 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143606 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143613 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143620 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143629 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143635 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143642 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143648 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1842, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.143655 2022] [php:warn] [pid 3931394] [client 78.204.125.136:62493] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1878, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
[Mon Sep 12 16:00:00.189584 2022] [php:error] [pid 3931394] [client 78.204.125.136:62493] PHP Fatal error:  Uncaught TypeError: chmod(): Argument #1 ($filename) must be of type string, resource given in /home/[...]/compta/prelevement/class/bonprelevement.class.php:1697\nStack trace:\n#0 /home/[...]/compta/prelevement/class/bonprelevement.class.php(1697): chmod()\n#1 /home/[...]/compta/prelevement/class/bonprelevement.class.php(1064): BonPrelevement->generate()\n#2 /home/[...]/compta/prelevement/create.php(125): BonPrelevement->create()\n#3 {main}\n  thrown in /home/[...]/compta/prelevement/class/bonprelevement.class.php on line 1697, referer: https://mywebsite.com/compta/prelevement/create.php?mainmenu=bank
`

I saw that the T220901.xml was created on the ftp server...
Can someone help me please?
Thanks!

### Environment Version

15.0.2

### Environment OS

Ubuntu 22.04.1 LTS

### Environment Web server

Ubuntu 22.04.1 LTS

### Environment PHP

8.1.12

### Environment Database

phpmyadmin 5.1

**Comment by ksar-ksar** [comment]
Hello,

Just for better reading the error is : 

```
 PHP Fatal error:  Uncaught TypeError: chmod(): Argument #1 ($filename) must be of type string, resource given in [...]/htdocs/compta/prelevement/class/bonprelevement.class.php:1696
 Stack trace:
 #0 [...]/htdocs/compta/prelevement/class/bonprelevement.class.php(1696): chmod()
 #1 [...]/htdocs/compta/prelevement/class/bonprelevement.class.php(1070): BonPrelevement->generate()
 #2 [...]/htdocs/compta/prelevement/create.php(125): BonPrelevement->create()
 #3 {main}
 thrown in [...]/htdocs/compta/prelevement/class/bonprelevement.class.php on line 1696, referer: https://monsite.com/compta/prelevement/create.php?mainmenu=bank
```

And it's also confirmed on V16.0 with PHP V8

**Comment by tiaris** [comment]
Works for  me in v15

**Comment by tiaris** [comment]
Works also v 16
