### ISSUE TITLE
get_default_tva : wrong check between FR and MC

### ISSUE THREAD

**Issue by TedinfoRegis** [Dolibarr/dolibarr#22241]
### Bug

In `core/lib/functions.lib.php`, `function get_default_tva` 

There is a test to check if buyer and seller are in the same country.
An exception is hard coded between France (FR) and Monaco (MC) which should be considered as same country for VAT calculation.

This is the concerned code from develop branch :
```	// Si le (pays vendeur = pays acheteur) alors la TVA par defaut=TVA du produit vendu. Fin de regle.
	if (($seller_country_code == $buyer_country_code)
	|| (in_array($seller_country_code, array('FR,MC')) && in_array($buyer_country_code, array('FR', 'MC')))) { // Warning ->country_code not always defined
		//print 'VATRULE 2';
		return get_product_vat_for_country($idprod, $thirdparty_seller, $idprodfournprice);
	}
```

The first `in_array` test is wrong and should be `in_array($seller_country_code, array('FR','MC'))`

### Environment Version

\>=4.0

### Environment OS

n/a

### Environment Web server

n/a

### Environment PHP

n/a

### Environment Database

n/a

### Steps to reproduce the behavior

1) Have a dolibarr whom company is based in France
2) Have a customer based in Monaco **with a well formatted VAT number** (MC123456789)
3) Create a bill : default VAT is 0% which is an error

**Comment by ksar-ksar** [comment]
Hello,

Seems to be an old bug, this code exist since V3.3 ! https://github.com/Dolibarr/dolibarr/blob/3.3/htdocs/core/lib/functions.lib.php#L2963

**Comment by TedinfoRegis** [comment]
Even if it's an old bug shouldn't it be corrected ?
