### ISSUE TITLE
Dolibarr integration with Moodle?

### ISSUE THREAD

**Issue by zenny** [Dolibarr/dolibarr#22257]
### Feature Request

Hi,

Is there any previous instance or currently ongoing project to integrate dolibarr with moodle? Thanks!

### Use case

An integration between dolibarr and moodle makes it easier of SMBs to run educational portals which require a small sum of transaction or recurring payments which is currently provided by third parties like <edwiser bridge> or <brigato> for laravel.

### Suggested implementation

An integration between dolibarr and moodle makes it easier of SMBs to run educational portals which require a small sum of transaction or recurring payments which is currently provided by third parties like <edwiser bridge> or <brigato> for laravel.

### Suggested steps

1. Dolibarr serves as the ERP/CRM for the SMB as well as the front end for the educational products under Moodle
2. Moodle serves as the backend for Dolibarr web frontend where learners can self register and make the payments via Dolibarr ERP/CRM
3. This may be possible (don't know exactly) by using moodle api of user registration and ACL with the Dolibarr users or vice versa.

Thanks!

**Comment by frederic34** [comment]
@zenny can you correct issue title module -> moodle

**Comment by zenny** [comment]
> @zenny can you correct issue title module -> moodle

@frederic34 Apology for the typo. Thanks for pointing me out.

**Comment by atm-maxime** [comment]
@atm-quentin 😉

**Comment by gschratzer** [comment]
> ### Feature Request
> Hi,
> 
> Is there any previous instance or currently ongoing project to integrate dolibarr with moodle? Thanks!
> 
> ### Use case
> An integration between dolibarr and moodle makes it easier of SMBs to run educational portals which require a small sum of transaction or recurring payments which is currently provided by third parties like or for laravel.
> 
> ### Suggested implementation
> An integration between dolibarr and moodle makes it easier of SMBs to run educational portals which require a small sum of transaction or recurring payments which is currently provided by third parties like or for laravel.
> 
> ### Suggested steps
> 1. Dolibarr serves as the ERP/CRM for the SMB as well as the front end for the educational products under Moodle
> 2. Moodle serves as the backend for Dolibarr web frontend where learners can self register and make the payments via Dolibarr ERP/CRM
> 3. This may be possible (don't know exactly) by using moodle api of user registration and ACL with the Dolibarr users or vice versa.
> 
> Thanks!

Dear @zenny!
I am agree that an api interface between dolibarr and moodle would be great. Only for each interface we need a target group which is interested. So, how was the response about this topic next to github. You know in the meantime some people which are searching this feature link you? 
Next step would be to write a project description before we can look how many ressources we need.

Best
Guido
