### ISSUE TITLE
Bug: Dolibarr code expects rowid and not a parent account number when importing data into plan comptable

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22265]
### Bug

Version: 15.0.3

Hello,

When I'm importing an item in the plan comptable, the parent id is not imported
![image](https://user-images.githubusercontent.com/2222550/190030153-d5a47261-5106-4183-ae91-6a10c7435b1d.png)
![image](https://user-images.githubusercontent.com/2222550/190030309-d196da93-639e-4363-9a67-c3640e20e983.png)

And when I'm in the importing process, I do have the parent account number
![image](https://user-images.githubusercontent.com/2222550/190030837-66cee773-dfe4-40c7-91cd-2ca29c384aa9.png)
And it doesn't work because for the parent account number field, the rowid is expected by dolibarr code instead of the parent account number.

The problem is that if I want to prepare an import file, I'm not supposed to know the rowid which is a data internal to dolibarr. As a user, I'm supposed to know the parent account number the same way we create a new input in GUI
![Compa1](https://user-images.githubusercontent.com/2222550/190031870-df012e6d-3c2d-40e4-b324-d61d427245d3.jpg)

That bug should be treated together with #22263 

Regards

### Environment Version

15.0.3

**Comment by priojk** [comment]
If I remember this right, there was a change in v16. I just had a look at the sample data for an import, and at least the relevant column is labeled "aa.account_parent".

It's worth to check with v16, if the import works as expected.

**Comment by mikygee** [comment]
I tested in 16.0.0, it's the same behavior
![image](https://user-images.githubusercontent.com/2222550/190151942-c709d7b4-a179-42be-888b-039a9efde5ab.png)
The help text seems to be kind of correct but it seems to say that either the rowid or the parent account number can be used.
rowid is working, parent account number is not working

**Comment by mikygee** [comment]
Hello,
I'm not sure the fix works for imports. Can you confirm it's the fix 22265 ?
It seems to work for exports though.
In which version is it supposed to be implemented natively ?
