### ISSUE TITLE
Bug: Broken new import functionnality in 16.0.0

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22271]
### Bug

Hello,

I'm trying to import a line in plan comptable
![image](https://user-images.githubusercontent.com/2222550/190150544-b6e28df2-4ca2-46c7-9967-9d5b83e4ffce.png)
![image](https://user-images.githubusercontent.com/2222550/190150009-0f19acf1-f041-4739-993a-84bc75e765d9.png)

But the final output tells me I have an error
![image](https://user-images.githubusercontent.com/2222550/190150158-ff8911d1-7b5c-4102-bbfa-e0ecb2a092af.png)
It complains about field F not being 1 or 0 but as you can see in the previous capture field F is not supposed to be EXPENSE, it's supposed to be 1.
[Plan_Comptable_Import2.txt](https://github.com/Dolibarr/dolibarr/files/9566169/Plan_Comptable_Import2.txt)

It seems to me that when there's an empty field withing the line, everything messes up.

Regards

### Environment Version

16.0.0

**Comment by mikygee** [comment]
I made the same test by removing the void column (use of double commas) and it's working.
So it means that when you have a void column, the Step when you match column ignores it
![image](https://user-images.githubusercontent.com/2222550/190153263-90ac51d9-36a0-4686-aad9-1a73593e3487.png)
But when it tries to make the import it takes into account the void column.

The problem is in this new functionnality that appears in version 16 about the form that matches columns (see this capture)

**Comment by mikygee** [comment]
Tested on 17-alpha, the problem exists there too

**Comment by eldy** [comment]
Can you paste what is the content of your table llx_c_accounting_category ?

**Comment by mikygee** [comment]
Hello,

I'm now in 16.0.3, on my dolibarr instance.

I can see this in llx_c_accounting_category
```
> select * from llx_c_accounting_category;
+-------+--------+----------+-------------------------------+-----------------+------+---------------+------------------+----------+------------+--------+
| rowid | entity | code     | label                         | range_account   | sens | category_type | formula          | position | fk_country | active |
+-------+--------+----------+-------------------------------+-----------------+------+---------------+------------------+----------+------------+--------+
|     1 |      1 | INCOMES  | Income of products/services   | Example: 7xxxxx |    0 |             0 |                  |       10 |          0 |      1 |
|     2 |      1 | EXPENSES | Expenses of products/services | Example: 6xxxxx |    0 |             0 |                  |       20 |          0 |      1 |
|     3 |      1 | PROFIT   | Balance                       |                 |    0 |             1 | INCOMES+EXPENSES |       30 |          0 |      1 |
+-------+--------+----------+-------------------------------+-----------------+------+---------------+------------------+----------+------------+--------+
```

**Comment by eldy** [comment]
So value must be EXPENSES or INCOMES or empty
Also, when you make your import, you must not import the line 1 but start with line 2.

**Comment by mikygee** [comment]
Here's the test again

I'm in 16.0.3 and one entry is there
![image](https://user-images.githubusercontent.com/2222550/210187794-d0b901c9-c040-4cc8-9009-3fbbf245aa50.png)

I want to add this entry using the import module
PCG99-BASE,62513066,Frais Repas 15% - TEST,62,,EXPENSE,1,

At step 2
![image](https://user-images.githubusercontent.com/2222550/210187823-06e7ab71-2eca-4556-a5c5-6f1defad0aac.png)
Then at step 4
![image](https://user-images.githubusercontent.com/2222550/210187857-914f8b61-bb37-4a17-a2b0-5256ca00ccb7.png)
Then at step 5
![image](https://user-images.githubusercontent.com/2222550/210187870-15bd0a9c-3e74-4d6e-9be4-b2907ffe90c2.png)
Then the simulation fails
![image](https://user-images.githubusercontent.com/2222550/210187955-b09d080c-eda6-4621-a960-65fc1b3d4014.png)

But according to my file
PCG99-BASE,62513066,Frais Repas 15% - TEST,62,,EXPENSE,1,
Column 5 is 1,
At step 4 the information was correct, field F was 1 not EXPENSE.

**Comment by mikygee** [comment]
I restart the test but this time I remove the double comma (before EXPENSE)
PCG99-BASE,62513066,Frais Repas 15% - TEST,62,EXPENSE,1,

It works
![image](https://user-images.githubusercontent.com/2222550/210188097-be9a467a-696c-4049-a88f-8eacc78b43d0.png)

![image](https://user-images.githubusercontent.com/2222550/210188106-2354e2b5-60d3-4939-a0b8-c68600b118da.png)

The result is imported
![image](https://user-images.githubusercontent.com/2222550/210188126-dc82adbc-50fb-4742-a409-24d1efe81898.png)

So the import module is not matching field, it's just matching columns
