### ISSUE TITLE
Bug: Missing french translations in module partenariats - 17-alpha

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22275]
### Bug

Version: 17- alpha

Hello,
There's a missing translation when I list the partenariats
![image](https://user-images.githubusercontent.com/2222550/190211104-30573281-12c2-490c-9ffb-45f10dc34cae.png)

In the error message when I try to create a partenariat but I forget on field
![image](https://user-images.githubusercontent.com/2222550/190210755-a587f80a-f1bf-429e-93db-ec0130189e9e.png)

Regards

### Environment Version

17- alpha

**Comment by atm-maxime** [comment]
Thanks for your feedback. Translation are made on transifex and regularly synced in Dolibarr project by @eldy . So this is not a Dolibarr issue, can you close it ?

**Comment by mikygee** [comment]
Hello Maxime,
IT IS a Dolibarr issue.
The problem is that I opened an account on transifex asked rights on Dolibarr. Nobody approves !!!
Maybe you can do the change, since you might have a working transifex account.

**Comment by IC-faycal** [comment]
![image](https://user-images.githubusercontent.com/90305154/208651302-7675e228-bc05-4594-9d41-50082c0c99b7.png)

The translation is good on my side.
