### ISSUE TITLE
Installation failed (17.0.0-alpha)

### ISSUE THREAD

**Issue by FrancoisSauterey** [Dolibarr/dolibarr#22274]
### Bug

Line 110:  a comma is missing at the end of the line in the table definition

**Comment by frederic34** [comment]
which file ?

**Comment by FrancoisSauterey** [comment]
Le 14/09/2022 à 21:54, Frédéric FRANCE a écrit :
> which file ?
> 

Ooops, of course, whith the file it's better ;-)

mysql/tables/llx_product.sql

best regard
FS

**Comment by inoveaconseil** [comment]
Now, present in develop branch
