### ISSUE TITLE
ERROR: 42803: column "u.short_label" must appear in the GROUP BY clause

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#22280]
I get the error below when I want to access the stock section:

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to hide sensitive information):
Date: 20220915105706
Dolibarr: 15.0.3 - https://www.dolibarr.org
Level of features: 0
PHP: 7.4.30
Server: Apache
OS: Linux  5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0

Requested URL: /product/reassort.php?type=0&leftmenu=
Menu manager: eldy_menu.php

Modules/Applications: user, api, product, modulebuilder, stock, expedition, blockedlog, propal, supplier_proposal, incoterm, contrat, ficheinter, projet, categorie, tax, notification, workflow, emailcollector, productbatch, accounting, agenda, bom, banque, barcode, cron, commande, ecm, expensereport, facture, fournisseur, holiday, mrp, resource, service, societe, variants, multicurrency
Database type manager: pgsql
Latest database access request error: SELECT p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.tms as datem, p.duration, p.tosell as statut, p.tobuy, p.seuil_stock_alerte, p.desiredstock, SUM(s.reel) as stock_physique, u.short_label as unit_short FROM llx_product as p LEFT JOIN llx_product_stock as s ON p.rowid = s.fk_product LEFT JOIN llx_entrepot as e ON s.fk_entrepot = e.rowid AND e.entity IN (1) LEFT JOIN llx_c_units as u on p.fk_unit = u.rowid WHERE p.entity IN (1) AND p.fk_product_type <> '1' GROUP BY p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.tms, p.duration, p.tosell, p.tobuy, p.seuil_stock_alerte, p.desiredstock ORDER BY p.ref ASC LIMIT 26
Return code for latest database access request error: DB_ERROR_42803
Information for latest database access request error: ERROR: 42803: column "u.short_label" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: ...e, p.desiredstock, SUM(s.reel) as stock_physique, u.short_la...\n ^\nLOCATION: check_ungrouped_columns_walker, parse_agg.c:1381

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
