### ISSUE TITLE
Bug: Income and expense balance, By custom groups

### ISSUE THREAD

**Issue by pedrouva** [Dolibarr/dolibarr#22294]
# Bug
[*SQL Error on Income and expense balance, By custom groups at /compta/resultat/result.php*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: nginx/1.22.0
- **PHP**: fpm-fcgi 7.4.30
- **Database**: MySQL or MariaDB 5.5.5-10.5.17-MariaDB-1:10.5.17+maria~ubu1804-log
- **URL(s)**: /compta/resultat/result.php

## Expected and actual behavior
[*When I need to show report to Custom Groups, I receive the error below*]

## Steps to reproduce the behavior
[*Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.4.101,2.4.102,2.4.103,2.4.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.4.101,2.4.102,2.4.103,2.4.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.5.101,2.5.102,2.5.103,2.5.109) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.4.101,2.4.102,2.4.103,2.4.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.5.101,2.5.102,2.5.103,2.5.109) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.6.101,2.6.102,2.6.103,2.6.104,2.6.105,2.6.106,2.6.107,2.6.108,2.6.109,...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.4.101,2.4.102,2.4.103,2.4.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.5.101,2.5.102,2.5.103,2.5.109) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.6.101,2.6.102,2.6.103,2.6.104,2.6.105,2.6.106,2.6.107,2.6.108,2.6.109,...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.7.101,2.7.102,2.7.103) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' A...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.4.101,2.4.102,2.4.103,2.4.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.5.101,2.5.102,2.5.103,2.5.109) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.6.101,2.6.102,2.6.103,2.6.104,2.6.105,2.6.106,2.6.107,2.6.108,2.6.109,...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.7.101,2.7.102,2.7.103) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' A...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.8.101,2.8.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.4.101,2.4.102,2.4.103,2.4.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.5.101,2.5.102,2.5.103,2.5.109) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.6.101,2.6.102,2.6.103,2.6.104,2.6.105,2.6.106,2.6.107,2.6.108,2.6.109,...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.7.101,2.7.102,2.7.103) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' A...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.8.101,2.8.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.9.101,2.9.102,2.9.103) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' A...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.1.101) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 2...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021-12-31 23:59:59'...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,1.3.101,1.3.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109)...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.2.101,2.2.102,2.2.103,2.2.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.3.101,2.3.102,2.3.103,2.3.105,2.3.106,2.3.107) AND (t.doc_date BETWEEN...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.4.101,2.4.102,2.4.103,2.4.104) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.5.101,2.5.102,2.5.103,2.5.109) AND (t.doc_date BETWEEN '2021-01-01 00:...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.6.101,2.6.102,2.6.103,2.6.104,2.6.105,2.6.106,2.6.107,2.6.108,2.6.109,...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.7.101,2.7.102,2.7.103) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' A...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.8.101,2.8.102) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' AND '2021...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100,2.9.101,2.9.102,2.9.103) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' A...' at line 1
Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.104,3.0.100,3.0.101,5.0.100) AND (t.doc_date BETWEEN '2021-01-01 00:00:00' A...' at line 1*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*![image](https://user-images.githubusercontent.com/6031649/190452732-bfa4e6bf-a205-4039-a084-5e44f3ce2a8c.png)*]

**Comment by priojk** [comment]
Cannot reproduce this error on a 14.0.5 test installation with just some arbitrarily created data. Would be helpful to get more detailed information, e.g. which chart of accounts is used, kinds of transactions that shall be reported etc.

**Comment by pedrouva** [comment]
> Cannot reproduce this error on a 14.0.5 test installation with just some arbitrarily created data. Would be helpful to get more detailed information, e.g. which chart of accounts is used, kinds of transactions that shall be reported etc.

OK

![Captura de tela_2022-09-25_16-08-11](https://user-images.githubusercontent.com/6031649/192161550-02d7ccb2-221d-4e24-bcf2-ccda5a1c7dd2.png)
![Captura de tela_2022-09-25_16-10-35](https://user-images.githubusercontent.com/6031649/192161554-1f618cf2-638b-4aa6-afc6-8fb66885db84.png)
![Captura de tela_2022-09-25_16-11-54](https://user-images.githubusercontent.com/6031649/192161555-cb5cab56-5841-4658-a684-3c5ebf3fdcbe.png)
![Captura de tela_2022-09-25_16-12-10](https://user-images.githubusercontent.com/6031649/192161556-5e6bd956-90d3-45e0-a974-98ea058b3571.png)
![Captura de tela_2022-09-25_16-12-30](https://user-images.githubusercontent.com/6031649/192161557-2c9181d3-9916-4b65-a8e1-b8eba9cc06a6.png)
![Captura de tela_2022-09-25_16-12-51](https://user-images.githubusercontent.com/6031649/192161558-dc024df9-8b7e-48d8-80fc-1606cc8d5abc.png)
![Captura de tela_2022-09-25_16-13-20](https://user-images.githubusercontent.com/6031649/192161559-12caf64a-e21e-40e2-b32c-ea2aefe1b90d.png)
![Captura de tela_2022-09-25_16-15-57](https://user-images.githubusercontent.com/6031649/192161560-41af1635-f1f0-4793-87e0-8814d429bd1d.png)
[export_accounting_1.csv](https://github.com/Dolibarr/dolibarr/files/9641609/export_accounting_1.csv)
[export_accounting_1.xlsx](https://github.com/Dolibarr/dolibarr/files/9641610/export_accounting_1.xlsx)


I did a new, clean installation of version 16 on the same server (contains the specs of it in my first post).

I exported the "chart of accounts" from version 14 in production, and imported it to this new installation of version 16, to know if the error refers only to version 14 or if in version 16 it would also exist.

I am sending the attached "chart of accounts" in three formats: .csv, .xlsx, .tsv, so that you can import it in your test environment, configure the "custom groups" according to the screenshots I sent to reproduce the error, and try to help us somehow solve it.

**Comment by priojk** [comment]
Looking at the account numbering scheme in your chart of accounts, I think we are getting closer in identifying the cause of the error:

- the numbers are numerical, but with several decimal points
- in the query, which is stated in the error message, the syntax looks like this:
'.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109) AND ...'

The problem seems to be that the values of the account numbers are placed as numerical values in the SQL query. The system tries to interpret the number 2.1.100 as a decimal number, which is fine for the first part up to 2.1 and then it says that it can't handle the next decimal point (in the error message, the problem shows directly at this remaining value .100).

To fix this, in the source code the creation of the query needs to be changed to include the account numbers as strings like '1.1.100', '2.1.101'...

**Comment by pedrouva** [comment]
> Looking at the account numbering scheme in your chart of accounts, I think we are getting closer in identifying the cause of the error:
> 
> * the numbers are numerical, but with several decimal points
> * in the query, which is stated in the error message, the syntax looks like this:
>   '.100,2.1.101,2.1.102,2.1.103,2.1.104,2.1.105,2.1.106,2.1.107,2.1.108,2.1.109) AND ...'
> 
> The problem seems to be that the values of the account numbers are placed as numerical values in the SQL query. The system tries to interpret the number 2.1.100 as a decimal number, which is fine for the first part up to 2.1 and then it says that it can't handle the next decimal point (in the error message, the problem shows directly at this remaining value .100).
> 
> To fix this, in the source code the creation of the query needs to be changed to include the account numbers as strings like '1.1.100', '2.1.101'...

Your comment makes sense, though. I would like to know how we can fix this, and what the next step is so that I can contribute to solving the problem. If necessary, I can send you the URL, username and password of my test system so you can investigate the bug further. Is there anything I can do to fix this as a stopgap? Thanks in advance.

**Comment by ksar-ksar** [comment]
@aspangaro ?

**Comment by pedrouva** [comment]
@eldy please, can u help identify the bug and help to resolv it? Thx in advance.

**Comment by pedrouva** [comment]
Greetings to all!

@aspangaro @eldy @priojk 

I was wondering if you could help me with a stopgap fix. We are without a cash flow projection. I have to export the data to Excel and do the data treatment there, and if I could fix it, I could do it directly from dolibarr. 

Thanks in advance.

**Comment by pedrouva** [comment]
Dear @aspangaro @eldy @priojk

I would like to finish this post. I have solved the "problem". It is not exactly a BUG, but a specific format for the numbering of the "chart of accounts".

I removed all the "dots" from the numbering, leaving: 11101 instead of 1.1.100, from this change that I made in the "chart of accounts", I had to redo the linkages and subsequently pay the journal and the ledger, and redo the "Registration in Accounting". It closed everything correctly and no longer showed the error in the "custom groups".

As a suggestion, could you include a fill-in mask in the numbering of the "chart of accounts" where I could not include a dot, or only one dot.

Thank you in advance.

Pedro.
