### ISSUE TITLE
SUBIR IMAGENES AL SERVER 

### ISSUE THREAD

**Issue by M0RDEL0N** [Dolibarr/dolibarr#22299]
### Bug

Warning: Constant DOL_URL_ROOT already defined in dolibarr\core\filemanagerdol\connectors\php\config.php on line 40

Warning: Undefined variable $themeparam dolibarr\core\filemanagerdol\browser\default\browser.php on line 51

### Environment Version

1600

### Environment OS

windows

### Environment Web server

xampp

### Environment PHP

8.1.6

### Environment Database

10.4.24-MariaDB 

### Environment URL(s)

http://localhost/dolibarr/admin/ihm.php?mode=login

### Expected and actual behavior

subia las imagenes

### Steps to reproduce the behavior

al intentar cargar una imagen no sube

**Comment by Daviid-P** [comment]
Esos 2 mensajes son Advertencias, podrían no tener  que ver con cualquier error que te impida subir imágenes.

La variable $themepath se define en `filemanagerdol\browser\default\browser.php` en la [linea 39](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/filemanagerdol/browser/default/browser.php#L39)
```php
$themepath = dol_buildpath($conf->css, 1);
```

Y la linea que a ti te advierte es la [51](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/filemanagerdol/browser/default/browser.php#L51):
```php
//print 'themepath='.$themepath.' themeparam='.$themeparam;exit;
```

Que versión tienes de Dolibarr? Has hecho algún cambio en el código?
