### ISSUE TITLE
Installation fail on step2

### ISSUE THREAD

**Issue by tarun1982** [Dolibarr/dolibarr#22307]
### Bug

SQL Error DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'integer DEFAULT NULL )ENGINE=innodb' at line 88

### Environment Version

17.0.0-alpha

### Environment OS

 CentOS Linux 8.5.2111

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

MariaDB 	10.3.28

### Environment URL(s)

https://erp.projectstatus.co.in/install/step2.php

### Steps to reproduce the behavior

At the time of installation - on step 2.

### Attached files

https://tinyurl.com/2pzm7bsv

**Comment by tarun1982** [comment]
Any update on this issue.. as we stuck on step2.

**Comment by ksar-ksar** [comment]
Hello,

Alpha versions are for developers only, it's not a priority to fix it

**Comment by zetaScout** [comment]
Hello,

Problem is SQL syntax at last column, **no comma separator between ( NULL fk_default_workstation )**.
```
Create table llx_product
Request 230 : create table zl_product ( rowid integer AUTO_INCREMENT PRIMARY KEY **[SKIP]**  fk_default_bom integer DEFAULT NULL fk_default_workstation integer DEFAULT NULL );
```
Maybe some one can fix it and push changes. Thank you
Best regards
