### ISSUE TITLE
Rapport - Chiffre d'affaires encaissé

### ISSUE THREAD

**Issue by fjfleury** [Dolibarr/dolibarr#22305]
### Bug

Turnover collected and Turnover Invoiced show 0 for all moth. 
In the detailed sections you can see the right / correct numbers
![Stats-Income](https://user-images.githubusercontent.com/52704911/190607779-70f8162e-45c7-4b4a-8932-16bc6be3a51a.JPG)

### Environment Version

16.0

### Environment OS

Ubuntu 20.04

### Environment Web server

Apache

### Environment PHP

7.4.3

### Environment Database

MySQL Ver 14.14 Distrib 5.7.39

### Environment URL(s)

compta/stats/index.php?leftmenu=accountancy_report&modecompta=BOOKKEEPING, compta/stats/index.php?leftmenu=accountancy_report&modecompta=RECETTES-DEPENSES

### Expected and actual behavior

Values schould be sum of Invoiced amounts or amounts collected (paid) 

### Steps to reproduce the behavior

Go to section and show report

**Comment by alexolait** [comment]
+1 Same problem for me after upgrade from 15.0.3 to 16

**Comment by ksar-ksar** [comment]
https://github.com/Dolibarr/dolibarr/commit/7d7a9597c1acb36790fb051b6d8f764ce08aa652
