### ISSUE TITLE
Ticket List Menu

### ISSUE THREAD

**Issue by xbloq** [Dolibarr/dolibarr#22315]
### Bug

We have a problem in ticket list with a blank page

The problem it's with php (version 8.1.9)

PHP Fatal error:  Uncaught TypeError: html_entity_decode(): Argument #1 ($string) must be of type string, array given in /var/www/html/dolibarr/htdocs/core/lib/functions.lib.php:1453
Stack trace:
/var/www/html/dolibarr/htdocs/core/lib/functions.lib.php(1453): html_entity_decode()
/var/www/html/dolibarr/htdocs/bookmarks/bookmarks.lib.php(46): dol_escape_htmltag()
/var/www/html/dolibarr/htdocs/main.inc.php(2591): printDropdownBookmarksList()
/var/www/html/dolibarr/htdocs/main.inc.php(2079): top_menu_bookmark()
/var/www/html/dolibarr/htdocs/main.inc.php(1379): top_menu()
/var/www/html/dolibarr/htdocs/ticket/list.php(491): llxHeader()
{main}
thrown in /var/www/html/dolibarr/htdocs/core/lib/functions.lib.php on line 1453

### Environment Version

16.0.0

### Environment OS

Linux Fedora 36

### Environment Web server

Apache/2.4.54

### Environment PHP

8.1.9

### Environment Database

MariaDB 10.5.16

### Environment URL(s)

/ticket/list.php?search_fk_status=non_closed&idmenu=22863&mainmenu=ticket&leftmenu=

**Comment by chrkorn** [comment]
Same here. Any search for tickets using the search_fk_status parameter results in a blank page. No error message in the debug log. We are on the same environment as the thread opener with the exception of the OS (Ubuntu 22 LTS in our case).

**Comment by julbroa** [comment]
Same here
Environment Version
16.0.0

Environment OS
Linux us-imm-web398.main-hosting.eu 4.18.0-305.12.1.lve.el7h.x86_64 #1 SMP Tue Aug 17 03:13:08 EDT 2021 x86_64

Environment Web server
LiteSpeed

Environment PHP
8.0.7

Environment Database
MySQL or MariaDB 5.5.5-10.5.12-MariaDB-cll-lve

Environment URL(s)
htdocs/ticket/list.php?search_fk_status=non_closed&idmenu=7284&mainmenu=ticket&leftmenu=
htdocs/ticket/list.php?mode=mine&search_fk_status=non_closed&idmenu=7285&mainmenu=ticket&leftmenu=

Expected and actual behavior
No response

Steps to reproduce the behavior
No response

Attached files
No response
![photo_2022-09-23_13-30-04](https://user-images.githubusercontent.com/105558823/192033762-2bc7dfdf-dd55-413e-b012-a18a4459cb0a.jpg)

**Comment by mafi85** [comment]
same here, is there any solution or workaround to fix it?

Environment Version 16.0.0

Environment OS
Ubuntu 22. 04

Environment Web server
Apache 2.0

Environment PHP
8.1.2

Environment Database
MariaDB 10.6.7

Environment URL(s)


Expected and actual behavior
No response

Steps to reproduce the behavior
No response

Attached files
No response

**Comment by xbloq** [comment]
Comment in line 1453 worked for me
file /htdocs/core/lib/functions.lib.php
//		$tmp = html_entity_decode($stringtoescape, ENT_QUOTES, 'UTF-8');

but BAD IDEA. problems with another menus

**Comment by hregis** [comment]
@xbloq @chrkorn @julbroa @mafi85 
this is already fixed. Wait 16.0.1 or update your dolibarr with 16 branch.
Dolibarr 16 is not completely compatible with php8.x ! Wait Dolibarr 17 !
