### ISSUE TITLE
wrong timezone / timestamp in log

### ISSUE THREAD

**Issue by scaleo-hds** [Dolibarr/dolibarr#22330]
### Bug

The timezone handling is wrong.
In all my timestamps php shows me times 2 hours earlier than done. (Europe/Berlin). But when I check logs, then the timstamp is 2 hours later then the real time I did the modifications.

### Environment Version

V 15.0.3

### Environment OS

windows 10

### Environment Web server

standard windwos installation package

### Environment PHP

7.3.33

### Environment Database

maria

### Expected and actual behavior

best would be: dolibarr uses the real server time.

**Comment by trekmorris** [comment]
Have you checked your timezone setting in  php.ini ?

**Comment by scaleo-hds** [comment]
yes. I did a double check and found out there is a wrong written comment line:
_; date.timzeone = Europe/Paris_
I have activated this line, but with the wrong written name timzeone
I corrected that now, but I have to check the logfile entries.

Is it possible to set this value within the dolibarr environment? This would be the most comfortable way.

**Comment by trekmorris** [comment]
@scaleo-hds 

If you want this function  , i think you will need create a feature request for this .

**Comment by scaleo-hds** [comment]
OK, I will create a feature request.
But the wrong written name was not my mistake. I only reactivated a commend, which is in php.ini (line 686 +/- 2lines) .

If the "_date.timezone_" is written correctely, it works fine.
