### ISSUE TITLE
Wrong document number when validating an intervention through the REST API

### ISSUE THREAD

**Issue by DomDevAdd** [Dolibarr/dolibarr#22332]
### Bug

If the field {cccc} is part of the doc. number format of the Intervention module, it is incorrectly filled with '####' when using the API to validate the intervention.

### Environment Version

15.0.3

### Environment PHP

7

### Expected and actual behavior

If the field {cccc} is part of the format of the Intervention document #, it is filled OK with the client code when validating manually but it is incorrect (filled with ####) when using the API to validate the intervention.

### Steps to reproduce the behavior

send a /intervention/<id>/validate POST through the REST API

I suspect it is linked to this line in setValid of intervention.class.php where $this->thirdparty does not appear to be initialized.
>> $num = $this->getNextNumRef($this->thirdparty);

**Comment by ksar-ksar** [comment]
https://www.dolibarr.fr/forum/t/numero-dune-intervention-creee-par-api-rest/41033/3

Need to add `thirdparty: {id`} in the POST Json

**Comment by DomDevAdd** [comment]
> thirdparty:

Thank you, just to make sure I get it in the posted json dictionary I add the 'thirdparty' key but what is the associated value ? the third party's integer id ? the id between curly braces ? a dictionary ?

**Comment by ksar-ksar** [comment]
Normally should be third party ID between curly braces

**Comment by DomDevAdd** [comment]
Thanks. Still doesn't work, here is the JSON I'm sending
 {"socid":"19","thirdparty":"{19}","description":"test ticket","array_options":{"options_fam":1,"options_tech":4},"fk_project":0,"model_pdf":"soleilsign"}
Intervention created OK but numbering still has #### instead of {cccc}
