### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) 

### ISSUE THREAD

**Issue by hlumati** [Dolibarr/dolibarr#22349]
# Bug
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\MalipoERP\htdocs\custom\lreport\lib\koolreport\core\src\datasources\PdoDataSource.php:114 Stack trace: #0

## Environment
- **Version**: 13.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.3
- **PHP**: apache2handler 7.4.3
- **Database**:  5.5.5-10.4.11-MariaDB
- **URL(s)**: /MalipoERP/htdocs/custom/lreport/funcionarios.php?idmenu=17605&mainmenu=lreport&leftmenu=

## Expected and actual behavior
When I go to Reports>See Reports I was suposed to see the reports, but instead I see an error

## Steps to reproduce the behavior
Login as a superadmin>Reports>See reports

**Comment by ksar-ksar** [comment]
Hello,

It's a custom module, you should ask the developer of that module
