### ISSUE TITLE
error 500 on paiement.php

### ISSUE THREAD

**Issue by guiltekmdion** [Dolibarr/dolibarr#22359]
### Bug

When we want to add a paiement to several invoices, we have an error 500 on the page /compta/paiement.php

### Environment Version

16.0

### Environment OS

Linux

### Environment Web server

apache

### Environment PHP

7.4

### Environment Database

MariaDB 5.5.5-10.3.36-MariaDB

### Environment URL(s)

/compta/paiement.php

### Expected and actual behavior

Invoice have to be on status "paid" and the paiement to be registred

### Steps to reproduce the behavior

we choose an invoice -> "saisir le règlement" -> list all the invoices which waits for paiement -> "Are you sure" : "yes" -> error 500

### Attached files

![image](https://user-images.githubusercontent.com/114142370/191699889-1a7b3798-9228-48da-aef5-b1380f38f228.png)
![image](https://user-images.githubusercontent.com/114142370/191700721-b203893b-38c0-41cd-b179-a0d512dc5a2c.png)

I check all the invoices 
![image](https://user-images.githubusercontent.com/114142370/191701215-51e17ce3-d01c-456c-bd04-9f3ac277ee4a.png)
![image](https://user-images.githubusercontent.com/114142370/191701335-39baefae-2e27-4f9d-8f43-c8b5e3ce251a.png)
![image](https://user-images.githubusercontent.com/114142370/191701510-32e8a80f-6514-449d-b1e8-7b3075b85d47.png)

**Comment by hregis** [comment]
@guiltekmdion i don't have this problem !
can you see the dolibarr.log and/or the Apache/Php log ?
have you externals modules ?

**Comment by guiltekmdion** [comment]
@hregis I have the AddRemise module installed but not activated 

I have a pretty stacktrace as you can see :
[error_log.txt](https://github.com/Dolibarr/dolibarr/files/9625629/error_log.txt)

**Comment by ksar-ksar** [comment]
There is no  /compta/paiement.php in the logs...

**Comment by Ants-In** [comment]
for me paiement.php works normally

**Comment by tiaris** [comment]
works for me
should be closed

**Comment by guiltekmdion** [comment]
Hello, i have news :
That problem appears when I want to "pay" an invoice classified in the "Grand journal" (I guess in English it's the ledger)
No problem when the invoice is not export to ledger.

Can you test that by your side ?
Thanks a lot
