### ISSUE TITLE
Special storage for blocked materials 

### ISSUE THREAD

**Issue by scaleo-hds** [Dolibarr/dolibarr#22354]
### Feature Request

We need a storage type for blocked material. 
This material must not calculated into the sum of available material.

### Use case

material with manufaturing failures mut be transfered in a storage for blocked material.

**Comment by AndreasSt-2022** [comment]
I support this feature request. This would not only be useful for manufacturing companies but for dealers, too. If a customer returns an item it must be added to the stock again but it must not be shipped to another customer until it is checked or repaired or gets a new retail packaging. Therefore it would be useful to have a (virtual) warehouse/stock that is available for transfer to or from another warehouse but not for direct shipping to customers.

**Comment by priojk** [comment]
Subset/duplicate of #18740
