### ISSUE TITLE
sql error /mrp/mo_list.php when filtering by status

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#22356]
### Bug

When filtering the list of manufacturing orders by status (draft, validated, in progress, produced, canceled) the following sql error happens:

Modules/Applications: api, user, incoterm, expedition, multicurrency, categorie, fckeditor, notification, propal, reception, asset, projet, product, stock, productbatch, oauth, tax, comptabilite, modulebuilder, productspecs, workstation, socialnetworks, label, supplier_proposal, abricot, deliveryaddress, productbycompany, removeconf, partnership, agenda, bom, banque, cron, commande, ecm, facture, fournisseur, margin, mrp, service, societe, ticket, fastupload, debugbar, budget, propal2supplierorder, supplierorderfromorder

Database type manager: mysqli

Latest database access request error: SELECT t.rowid,t.ref,t.fk_bom,t.mrptype,t.fk_product,t.qty,t.label,t.fk_soc,t.fk_project,t.fk_warehouse,t.date_start_planned,t.date_end_planned,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.import_key,t.status,t.model_pdf,t.fk_parent_line FROM llx_mrp_mo as t LEFT JOIN llx_mrp_production lineparent ON t.fk_parent_line = lineparent.rowid LEFT JOIN llx_mrp_mo moparent ON lineparent.fk_mo = moparent.rowid WHERE t.entity IN (1) AND (status IN (0)) ORDER BY t.ref ASC LIMIT 251
Return code for latest database access request error: DB_ERROR_1052
I**nformation for latest database access request error: Column 'status' in where clause is ambiguous**

### Environment Version

16.0.0

### Environment OS

ubuntu 

### Environment Web server

apache

### Environment PHP

7.4

### Environment Database

mysql

### Environment URL(s)

/mrp/mo_list.ph

### Steps to reproduce the behavior

filter the list on any status

**Comment by atm-jpb** [comment]
posted a pr to fix it https://github.com/Dolibarr/dolibarr/pull/22357

**Comment by erikvanberkum** [comment]
thanks that works

**Comment by tiaris** [comment]
issue closed
