### ISSUE TITLE
V16 no release note ?

### ISSUE THREAD

**Issue by VoidScute** [Dolibarr/dolibarr#22362]
there is no release note for the v16 on github ?

**Comment by priojk** [comment]
There is the changelog at [https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog
](https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog)

**Comment by VoidScute** [comment]
wrong link i guess and i talk about : https://github.com/Dolibarr/dolibarr/releases which i currently use as RSS to be notify and to know what is new.

**Comment by eldy** [comment]
Version has been added on github
