### ISSUE TITLE
Rest API contact, PUT format phone numbers

### ISSUE THREAD

**Issue by Marssouss** [Dolibarr/dolibarr#22377]
Hi Evryone,

I have an issue when atemping to update phones numbers for contacts with API.

The Dolibarr version is : 15.0.3

When I trying to update phones numbers from contacts ( phone_pro, phone_perso, phone_mobile, fax) the phone number is transformed and I lost the first "0" of number.
An serie of screenshot can help you ton understand me :)

Here I used GET /contacts/{id} method from Swagger UI
![GET_contacts_API](https://user-images.githubusercontent.com/37174003/191940222-9596936a-0ed2-407c-ab4f-353ee4163410.png)

I want to format my phone number  like this : 0123456789

So i used PUT /contacts/{id} like this : 
![PUT_contacts_API](https://user-images.githubusercontent.com/37174003/191940765-a8ae282d-1da0-46cc-874a-ffac68e1f35f.png)

But when I get this result : 
![PUT_contacts_API_result](https://user-images.githubusercontent.com/37174003/191941236-3ff8fc0c-8be7-4983-839b-392ab8276376.png)

And the modification is also visible in database : 
![BDD_contact_result](https://user-images.githubusercontent.com/37174003/191941289-f905e35a-3d4e-4977-a423-4d73e01ebf77.png)

I have tested if I add only one "-" if the result is same, but no : 

I just add "-" at the end of pone numbers
![PUT_contacts_API_2](https://user-images.githubusercontent.com/37174003/191941859-06c3fa89-d8db-4a76-b55f-ed8058f33795.png)

And here, I have first "0" of my number : 
![PUT_contacts_API_result_2](https://user-images.githubusercontent.com/37174003/191941955-98d279a6-e5d4-416c-9e2f-91377ab00cd7.png)

So if someone have an idea why I have this  behaviour, I'm interested.
Thank's a lot for your responses, have a nice day ;)

**Comment by eldy** [comment]
I tested with v16. I can't reproduce with v16. Can you try with it ?

**Comment by Marssouss** [comment]
Hello, thank's tfor your reply.
I have update Dolibarr to v16, but the problem is same.

I suppose phone number is converted to integer, because if I put "0000000000" in phone_perso, I get "0" in DB and API result : 
Sending modification : 
![CONTACTS_PUT_tel_0000000000](https://user-images.githubusercontent.com/37174003/193008764-45e77641-c161-4a97-a259-bd6af84407b3.png)

Result : 
![CONTACTS_PUT_result](https://user-images.githubusercontent.com/37174003/193008838-1ff97994-4ffd-4cb9-89d9-2a63210f019e.png)

If someone known where is the method who put data in database, I can control the pre-treatment of this field ?

Thank's lot for your responses
