### ISSUE TITLE
MO Card ability to change "Label" and "Date end planned" fields after validation  

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#22370]
### Feature Request

Currently, when a Manufacturing Order is validated, it's not possible to change any of the fields. 
In our workflow, it would be favourable to have the option to change the "Label" and "Date end Planned" fields after the manufacturing order is validated. 

Conform other cards (invoices proposals orders) they have this feature.  BOM currently doesn't have the option to change any fields after validation. 

### Use case

In many cases the Label or Date end Planned of a manufacturing order might change after validation. The proposed above solution is an easier workflow. 

### Suggested implementation

Implementation as with other cards with an edit button pencil icon.

**Comment by eldy** [comment]
Feature has been implemented for v17
