### ISSUE TITLE
Missing Tools > Resources

### ISSUE THREAD

**Issue by dumitrugrl** [Dolibarr/dolibarr#22373]
### Bug

Unable to see the Resources module interface.

![image](https://user-images.githubusercontent.com/230109/191690765-f4c46e28-9c28-49be-a8e1-2179c20a1981.png)

![image](https://user-images.githubusercontent.com/230109/191690824-f097a235-e2e9-4ae8-becd-3b219c1bd445.png)

![image](https://user-images.githubusercontent.com/230109/191690869-7925470e-0c22-4ae5-9866-a44e19752df9.png)

Am I missing some other configuration?

### Environment Version

17.0.0-alpha

### Environment OS

Windows 10.0 build 19043 (Windows 10) AMD64

### Environment Web server

Nginx 1.23.1

### Environment PHP

PHP Version 8.0.0

### Environment Database

MySQL 8.0.30

### Environment URL(s)

/core/tools.php?mainmenu=tools&leftmenu=

### Expected and actual behavior

Clean Install.
Enable Resource Module.
Module UI showing under Tools.

### Steps to reproduce the behavior

Clean Install.
Enable Resource Module.
Module UI not showing in Tools.

**Comment by eldy** [comment]
Th resource module may appears in the menu Agenda or Tools, depending on your version.
Check in both of rhem.

**Comment by dumitrugrl** [comment]
Thank you @eldy.
Is it indeed under Agenda. (v 17.0.0-alpha)

**Comment by gschratzer** [comment]
@dumitrugrl, please close the issue, because it isn't a bug, it only moved to a other menu
