### ISSUE TITLE
Wennn sending an email from project card, no event is stored in Agenda

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#22385]
### Feature Request

From most cards (thirdparty, contact, invoice, ....) 
There are configuration of Agenda modul, who create an automatic event in agenda with content of email.
For project it seems to be no configuration. (like COMPANY_SENTBYMAIL, ORDER_SENTBYMAIL....) 

And no trigger for PROJECT_SENTBYMAIL is in Agenda triggers

### Use case

normal action of sending project to an email

### Suggested implementation

Add a trigger for acrion PROJECT_SENTBYMAIL as it is done for invoices, companies...

**Comment by aspangaro** [comment]
Copy of issue #20912. PR already proposed #22396
