### ISSUE TITLE
IBAN not mandatory for International Export Countries

### ISSUE THREAD

**Issue by josett225** [Dolibarr/dolibarr#22386]
### Bug

When adding bank information in thirdparty, if country is outside EEU (as Taiwan) the IBAN and BIC are not mandatory.

When action == update, there is an issue when saving. The following error message appears : 
Le champ 'Identifiant IBAN' est obligatoire

Sorry if the code does not display in a clean way as I don't know how of display it...

### Environment Version

14.0.5

### Environment URL(s)

/societe/paymentmodes.php?socid=6893&id=1&action=edit

### Expected and actual behavior

After reviewing the code it seems that the following fetch is done too late in /societe/paymentmodes.php =
$companybankaccount->fetch($id)  therefore the the value $companybankaccount->needIBAN() is always 1

Actual code =
`
if ($action == 'update') {
		// Modification
		if (!GETPOST('label', 'alpha') || !GETPOST('bank', 'alpha')) {
			if (!GETPOST('label', 'alpha')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("Label")), null, 'errors');
			}
			if (!GETPOST('bank', 'alpha')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("BankName")), null, 'errors');
			}
			$action = 'edit';
			$error++;
		}
		
		if ($companybankaccount->needIBAN() == 1) {
			if (!GETPOST('iban')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("IBAN")), null, 'errors');
				$action = 'edit';
				$error++;
			}
			if (!GETPOST('bic')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("BIC")), null, 'errors');
				$action = 'edit';
				$error++;
			}
		}

		$companybankaccount->fetch($id);

		if (!$error) {`

New Code =
`if ($action == 'update') {
		// Modification
		if (!GETPOST('label', 'alpha') || !GETPOST('bank', 'alpha')) {
			if (!GETPOST('label', 'alpha')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("Label")), null, 'errors');
			}
			if (!GETPOST('bank', 'alpha')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("BankName")), null, 'errors');
			}
			$action = 'edit';
			$error++;
		}
		// FETCH EARLIER BEFORE needIBAN() call
               $companybankaccount->fetch($id);

		if ($companybankaccount->needIBAN() == 1) {
			if (!GETPOST('iban')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("IBAN")), null, 'errors');
				$action = 'edit';
				$error++;
			}
			if (!GETPOST('bic')) {
				setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("BIC")), null, 'errors');
				$action = 'edit';
				$error++;
			}
		}
// REMOVE AND MOVE UP THIS LINE		$companybankaccount->fetch($id);

		if (!$error) {`

### Steps to reproduce the behavior

Prerequesite: Company should belong to international country.

- Create third party supplier in outside EEC country
- go to payment methods tab
- add a bank account
- try to save or modify

**Comment by tiaris** [comment]
We are on the Vienna Devcamp with german Community, we will try to fix this
greetings
