### ISSUE TITLE
Bug: Import products error V 15.0.3

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#22390]
# Bug
Error when trying to import products (also in other types of imports).

I´ll thank if anyone can confirm if this could be something related to my server configuration, (nginx about capital/lowercase directories), or something that can affect everybody with Dolibarr V 15.0.3, since I had no problem with previous versions, using exactly the same enviroment.

## Environment
- **Version**: 15.0.3
- **OS**: Linux
- **Web server**: nginx/1.16.1
- **PHP**: fpm-fcgi 7.4.9
- **Database**: MySQL or MariaDB 5.5.5-10.3.29-MariaDB
- **URL(s)**: /imports/import.php?step=2&datatoimport=produit_1&excludefirstline=2&separator=%2C&enclosure=%22

## Expected and actual behavior

Must be shown the selector of the type of file to import, Excel 2077 XLSX or CSV.

Instead, when try to import products, at step 2, I'm getting this error, and the selector of file type (XLSX or CSV) is missing:

`Warning: require_once(mydolibarr/includes/phpoffice/phpspreadsheet/src/autoloader.php): failed to open stream: No such file or directory in mydolibarr/core/modules/import/import_xlsx.modules.php on line 115 Fatal error: require_once(): Failed opening required 'mydolibarr/includes/phpoffice/phpspreadsheet/src/autoloader.php' (include_path='mydolibarr/htdocs') in mydolibarr/core/modules/import/import_xlsx.modules.php on line 115
`

After many tries and test, can´t view what's the problem, I´m not programmer, just dolibarr user since V 3.

## Steps to reproduce the behavior

Simply follow the steps for import process like normally, error is at step 2, I only get this error in V 15.0.3 that never before I saw. (Must note that updated from 13.x.x [It worked well with v13], to 15.0.3)

## Attached files

At dolibarr path **\includes\phpoffice** can see directory called **PhpSpreadsheet** (Note letters P and S are capital)
![Imagen103 2022-09-24, 13_02_58](https://user-images.githubusercontent.com/15174724/192094662-68dd0ba4-512c-4b6e-9a5d-fc580683e446.jpg)

Instead, at file **\core\modules\import\import_xlsx.modules.php** where error was refered, at line 115, the path that is pointed is at lowercase **"phpspreadsheet"**

![Imagen104 2022-09-24, 13_03_21](https://user-images.githubusercontent.com/15174724/192094810-61bc54f6-1c63-4a7d-a098-de883592eb11.jpg)

## Report

I just create this issue to share with others, if anyone is having the same problem.
Not sure as mention before if this could be a configuration problem of my own server, or really the path nomenclature has been change for any reason, or has change the code that points to that folder.

## My solution to this
My solution to be able to import files, is change the name of directory:

**From**: mydolibarr/includes/phpoffice/**PhpSpreadsheet**/

**To**: mydolibarr/includes/phpoffice/**phpspreadsheet**/

And the import function seems to works well again.

I let this open for a while, If no one of the team answers this, I will close it.

Regards

Jose Manuel

**Comment by ksar-ksar** [comment]
Hello,

In the V15.0.3, you do not have capital letters : https://github.com/Dolibarr/dolibarr/tree/15.0/htdocs/includes/phpoffice
Between the V13 and the V14 the folder has been renamed (PhpSpreadsheet in V13 and phpspreadsheet in V14).

Most probably, something was not properly uploaded during upgrade

**Comment by PlanPc** [comment]
Yes, this happened in an update from V13 to V15.

I supouse that when update and rewrite folders, that capitalization donest change and stay as it was before, (while the folder name is the same, capitalization doestn change, al least in windows enviroment this is what happends, though my server is based on linux) , at least in my case, dont know to others, thats why I decided to share it.

![Imagen111 2022-09-25, 22_20_53](https://user-images.githubusercontent.com/15174724/192163696-09f309d4-5e49-45a7-877e-fc905ecf6c74.jpg)


@ksar-ksar do you think something similar could have happened with the WYSIWYG CKEditor plugin called **scayt** between those versions? It has also disappeared in the update from version 13 to 15. Trying to solve, but can find nothing that helps me to bring it back again. https://github.com/Dolibarr/dolibarr/issues/20903

Regards
