### ISSUE TITLE
languaje ES_ar main.lang file is not correct -> set it right )date and number format)

### ISSUE THREAD

**Issue by caciquemar** [Dolibarr/dolibarr#22394]
### Bug

main.lang file settings for ES_ar is set EN_us
I just corrected de file (only concerning date and number format) 
and im attaching it in case you want to add the patch

### Attached files

[main.zip](https://github.com/Dolibarr/dolibarr/files/9639510/main.zip)

**Comment by ksar-ksar** [comment]
Hello,

All the languages patch must be done in transifex : https://explore.transifex.com/dolibarr-association/dolibarr/
