### ISSUE TITLE
Big Note (publique) (public bote) broken PDF of offer

### ISSUE THREAD

**Issue by Shnoulle** [Dolibarr/dolibarr#22419]
### Bug

Big public not break PDF of offer (propal)

### Environment Version

17.0.0-alpha
15.03

### Environment OS

debian

### Environment Web server

nginx and apache

### Environment PHP

7.4

### Environment Database

MariaDB

### Environment URL(s)

http://localhost/dolibarr/htdocs/comm/propal/card.php?id=1

### Expected and actual behavior

Expected :
- Table for the price line start after all Note
- Note margin top are OK (2dn page)

Actual
- Table for the prince line start before end of Note
- Note margin top are totally broken

### Steps to reproduce the behavior

- Create a new offer and add more than one page content on Public Note 
- Add a line in offer
- Get the PDF generated

### Attached files

17 version : [PR2209-0001.pdf](https://github.com/Dolibarr/dolibarr/files/9648545/PR2209-0001.pdf)
15.03 version (with html) :[PR2209-0053-1503.pdf](https://github.com/Dolibarr/dolibarr/files/9648546/PR2209-0053-1503.pdf)

**Comment by ksar-ksar** [comment]
Hello,

What is the use case of that (putting more than one page of note) ?

**Comment by Shnoulle** [comment]
> Hello,
> 
> What is the use case of that (putting more than one page of note) ?

I need a reason ?

Adding specifi terms for example
