### ISSUE TITLE
Invoice balance amount false if there are down payments made before migration to v16

### ISSUE THREAD

**Issue by eric-lamy-agerix** [Dolibarr/dolibarr#22413]
### Bug

Hello,
Since the migration to V16, if I want to make a standard invoice having already had deposit invoices, the final invoice amount is wrong. The lines of the invoice are also wrong, some disappearing completely, others changing milestones...
Thank you for your answers

### Environment Version

16.0.0

### Environment OS

Linux champagne.o2switch.net 4.18.0-348.12.2.lve.el7h.x86_64 #1 SMP Mon Jan 24 05:45:10 EST 2022 x86_64

### Environment Web server

Apache 

### Environment PHP

8.0.23

### Environment Database

MySQL or MariaDB 10.5.17-MariaDB

### Steps to reproduce the behavior

Create one or two deposit invoices form a command
create a standart invoices for the command

**Comment by eldy** [comment]
Can you reproduce a case on demo dolibarr.org and provide the ref of the document that is wrong.

**Comment by eric-lamy-agerix** [comment]
I have reproduced on demo and it works fine on demo but I don't have millestone on demo so it can change way of Dolibarr to create my santard invoice...

**Comment by eric-lamy-agerix** [comment]
For information if I try to delete the millestone, I have this message 
`Access to this page this way (POST method or GET with a sensible value for 'action' parameter) is refused by CSRF protection in main.inc.php. Token not provided. If you access your server behind a proxy using url rewriting and the parameter is provided by caller, you might check that all HTTP header are propagated (or add the line $dolibarr_nocsrfcheck=1 into your conf.php file or MAIN_SECURITY_CSRF_WITH_TOKEN to 0 instead of 2 into setup).`

**Comment by hregis** [comment]
@agerix what id the version of your Milestone module ?
can you contact me directly ? this an external module.

**Comment by eric-lamy-agerix** [comment]
@hregis version is 10.0+2.4.0. I also have a 500 error when I try to click on the About tab..

**Comment by hregis** [comment]
An upgrade of Milestone v16 is needed

**Comment by eric-lamy-agerix** [comment]
Issue fixed by upgrade
