### ISSUE TITLE
Turnover invoice set to 0€

### ISSUE THREAD

**Issue by sebastienserre** [Dolibarr/dolibarr#22426]
### Bug

Hello,

The total of Turnover invoices are set to "0"...
![2022-09-27_07-28](https://user-images.githubusercontent.com/3902621/192440132-3811561b-d4a5-4c69-80cd-0d8ead700d78.jpg)

### Environment Version

16.0.0

### Environment OS

Linux ns3107431.srvsi.com 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64

### Environment Web server

Apache/2.4.54

### Environment PHP

 7.4.30

### Environment Database

MySQL or MariaDB 5.5.5-10.5.15-MariaDB-0+deb11u1

**Comment by ksar-ksar** [comment]
Duplicated #22305

And according to @eldy, allready corrected

https://github.com/Dolibarr/dolibarr/commit/7d7a9597c1acb36790fb051b6d8f764ce08aa652

**Comment by ksar-ksar** [comment]
https://github.com/Dolibarr/dolibarr/commit/7d7a9597c1acb36790fb051b6d8f764ce08aa652
