### ISSUE TITLE
English strings does not make sense for translator

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#22433]
### Bug

![image](https://user-images.githubusercontent.com/68460690/192496464-fb34274c-314a-4f39-b61a-681579248182.png)
What is this "thumb"? A thumbnail? I need more context to translate this.

**Comment by ksar-ksar** [comment]
Hello,

You can also have a look on the key : DashboardDisableBlockBank : Basically is to disable the Bank block on the dashboard.

**Comment by dpriskorn** [comment]
It is still not clear to me what "thumb" means. Is it a type of UI element?

**Comment by ksar-ksar** [comment]
THis is it : 
![image](https://user-images.githubusercontent.com/35605507/194951402-35f22879-86b3-491f-9c80-8ce7ed25e56a.png)

**Comment by dpriskorn** [comment]
So my guess was correct. I never heard about that ui element before. 
What about renaming it to card to follow the kanban way of naming that thing?
Alternatively I suggest documenting this new type og UI element with an example image in Wikidata.
