### ISSUE TITLE
MODULE TICKET ERROR

### ISSUE THREAD

**Issue by rebootit** [Dolibarr/dolibarr#22434]
### Bug

Just after the upgrade to V16 from the latest V15 if you change anything on the ticket module configuration there is an error when trying to open a new ticket from the public page (it say something about a wrong number entered) after looking at the log it call for a capcha code that we never used.
Once deactivated on security it is working as before

### Environment Version

16

### Environment OS

Ubuntu server 20.04

### Environment Web server

Apache2

### Environment PHP

7.4.3

### Environment Database

MariaDB 15.1

**Comment by hregis** [comment]
fix with PR https://github.com/Dolibarr/dolibarr/pull/22435
