### ISSUE TITLE
Missing error message when uploading the company logo and its size is bigger than maxfilesize

### ISSUE THREAD

**Issue by thibdrev** [Dolibarr/dolibarr#22436]
### Bug

Dolibarr shall through an error message when a user tries to upload the company logo (or logo squared) and its file size is bigger than the maximum size allowed by the Dolibarr instance.

### Environment Version

16.0.0

### Environment OS

Linux builder.o2switch.net 4.18.0-348.12.2.lve.el7h.x86_64

### Environment Web server

Apache

### Environment PHP

7.4.30

### Environment Database

MySQL or MariaDB 5.5.5-10.5.17-MariaDB

### Environment URL(s)

/admin/company.php

### Expected and actual behavior

When uploading your company "Logo" (or "Logo (squarred)") with a file which size is bigger than the maximum allowed by Dolibarr (defined in Configuration > Security > Files, and by default 2 048 Kb), then:
- Expected behaviour:
    * Dolibarr shall through an error message stating that the size of the file is too big (and probably also state this maximum value).
- Actual behaviour:
    * Dolibarr shows a confirmation message stating "Configuration sauvegardée" (in French) but nothing has been uploaded.

### Steps to reproduce the behavior

1. Go to: Configuration > Company/Organisation > Company > Logo > Select a file
2. Select an image file which size is bigger than the maximum size allowed by your Dolibarr instance (for example [this big wallpaper image](https://images.pexels.com/photos/842711/pexels-photo-842711.jpeg?cs=srgb&dl=pexels-christian-heitz-842711.jpg&fm=jpg&w=5472&h=3648) if your max is 2 048 Kb)
3. Hit the "Save" button and observe Dolibarr's behaviour

**Comment by hregis** [comment]
@thibdrev fix with this PR https://github.com/Dolibarr/dolibarr/pull/22437
your PR is good too !

**Comment by thibdrev** [comment]
@hregis thanks!
I just need to get my head around this GitHub process (fork, branches, commits, pull requests) to avoid messing around :smile:

**Comment by ksar-ksar** [comment]
Available on V16.0.1
