### ISSUE TITLE
Custom Module Dependency is missing, but is enabled

### ISSUE THREAD

**Issue by jerichoc239** [Dolibarr/dolibarr#22448]
### Bug

Using dolibarr 15.0.3, I have created a series of custom modules. One module is dependent upon dolibarr modules (like societe/third parties) and 2 custom module I’ve made. So, Custom Module A → Custom Module B → dolibarr modules. When I enable Custom Module A, it correctly enables all the dependent modules as intended, however it raises a false error message saying it cannot find modCustomModuleB even though it enables it and the dependencies of modCustomModuleB without issue. What can I do to prevent this error message from appearing even though functionality seems to be perfectly fine.

### Environment Version

15.0.3

### Environment OS

Linux

### Environment PHP

7.4

### Attached files

![2022-09-23T13_55_04](https://user-images.githubusercontent.com/8879335/192817975-f1572fb9-8579-4186-939d-5d2fdf1cd484.png)

**Comment by hregis** [comment]
@jerichoc239 
Do you have a module called "common"?

**Comment by jerichoc239** [comment]
Yes!

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
