### ISSUE TITLE
Orçamentos e Encomendas

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#22449]
### Bug

Não permite alterar o rodapé dos documentos

**Comment by ksar-ksar** [comment]
Hello,

In English please ?

What does that mean :  "Does not allow changing the footer of documents" ? Error message ? screenshot ?

**Comment by ksar-ksar** [comment]
Hello,

Without your reply, we can't investigate.
I close it for now, you can always re-open if you can provide additional data's.
