### ISSUE TITLE
error 500 when I pay an invoice already in Ledger

### ISSUE THREAD

**Issue by guiltekmdion** [Dolibarr/dolibarr#22445]
### Bug

When we want to add a paiement to several invoices, we have an error 500 on the url /compta/paiement.php

That problem appears when I want to "pay" an invoice classified in the "Grand journal" (I guess in English it's ledger)
No problem when the invoice is not export to ledger.

### Environment Version

16.0

### Environment OS

Linux

### Environment Web server

apache

### Environment PHP

7.4 & 8.1

### Environment Database

MariaDB 5.5.5-10.3.36-MariaDB

### Environment URL(s)

/compta/paiement.php

### Expected and actual behavior

Invoice have to be on status "paid" and the paiement to be registred

### Steps to reproduce the behavior

we choose an invoice -> "saisir le règlement" -> list all the invoices which waits for paiement, I select my invoices already on the Ledger > "Are you sure" : "yes" -> error 500

### Attached files

![191701215-51e17ce3-d01c-456c-bd04-9f3ac277ee4a](https://user-images.githubusercontent.com/114142370/192760034-5858c9ac-bdf7-4218-b60e-2d022b1cf0a7.png)
![191701335-39baefae-2e27-4f9d-8f43-c8b5e3ce251a](https://user-images.githubusercontent.com/114142370/192760039-86f7e593-13b9-4640-9be6-61462c10c547.png)
![191701510-32e8a80f-6514-449d-b1e8-7b3075b85d47](https://user-images.githubusercontent.com/114142370/192760043-7906b58d-6ed1-49c9-8dff-22cafd3f1ec0.png)

**Comment by guiltekmdion** [comment]
I want to add that it works with invoices not registred on Ledger

**Comment by ksar-ksar** [comment]
Hello,

Error 500 means PHP error : Can you check your hosting logs and send it ?

**Comment by guiltekmdion** [comment]
(Photo)


Hi,
Here is the stack when I have the error 500.
I don't understand why the module AddRemise is there because I disabled it...

**Comment by hregis** [comment]
@guiltekmdion 
Given the error, the "addremise" module must add information about the pdf that is generated, but this module instantiates the "Facture" class by not sending anything in the "$db" parameter which manages the calls of the database.
So it creates an error. 
You must contact the module developer and ask him to correct this error.
