### ISSUE TITLE
Database query error when listing invoice statistics for a particular tag

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#22441]
### Bug

We go to `/compta/facture/stats/index.php` to list statistics and it shows up fine, but as soon as we select a customer tag / category and click Refresh, Dolibarr throws up:

`Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to hide sensitive information):
Date: 20220928051639
Dolibarr: 15.0.0 - https://www.dolibarr.org
Level of features: 0
PHP: 7.4.30
Server: Apache
OS: Linux CENSORED 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 SeaMonkey/2.53.13

Requested URL: /compta/facture/stats/index.php
Referer: https://CENSORED/compta/facture/stats/index.php?leftmenu=customers_bills_stats
Menu manager: eldy_menu.php

Modules/Applications: syslog, user, fckeditor, multicurrency, agenda, banque, commande, ecm, expensereport, facture, workflow, fournisseur, salaries, service, societe, propal, categorie, tax, bookmark, product, stock, expedition, reception
Database type manager: mysqli
Latest database access request error: SELECT date_format(datef,'%Y') as year, COUNT(*) as nb, SUM(f.total_ht) as total, AVG(f.total_ht) as avg FROM llx_facture as f LEFT JOIN llx_categorie_societe as cat OmdN (f.fk_soc = cat.fk_soc) WHERE f.fk_statut >= 0 AND f.entity IN (1) AND (f.fk_statut <> 3 OR f.close_code <> 'replaced') AND f.type IN (0,1,2,3,5) AND cat.fk_categorie IN (1) GROUP BY year ORDER BY year DESC

Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OmdN (f.fk_soc = cat.fk_soc) WHERE f.fk_statut >= 0 AND f.entity IN (1) AND ...' at line 1
`

### Environment Version

15.0.0

**Comment by hregis** [comment]
@bos4711 this bug is already fixed, updrade to dolibarr 15.0.3
