### ISSUE TITLE
Leave Types: Missing column

### ISSUE THREAD

**Issue by valtbern** [Dolibarr/dolibarr#22447]
### Bug

Missing column "block_if_negative" in dictionary: LEAVE - TYPES OF LEAVE

### Environment Version

16.0.0

### Environment OS

Linux 3.10.0-962.3.2.lve1.5.68.el7.x86_64

### Environment Web server

LiteSpeed

### Environment PHP

7.4.30

### Environment Database

MariaDB 5.5.5-10.3.36-MariaDB-cll-lve

### Environment URL(s)

/admin/dict.php?id=28

### Expected and actual behavior

Expected to list the types of leave, however returns error of missing table column:

Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'h.block_if_negative' in 'field list'

### Steps to reproduce the behavior

Navigate to Dictionaries -> Open LEAVE - TYPES OF LEAVE

**Comment by hregis** [comment]
@valtbern can you check if "block_if_negative" field is present in llx_c_holiday_types table with phpmyadmin ?
if the field is not present, try to execute this query in phpmyadmin

`ALTER TABLE llx_c_holiday_types ADD COLUMN block_if_negative integer NOT NULL DEFAULT 0 AFTER fk_country;`

**Comment by valtbern** [comment]
Hi hregis
No, this column is somehow gone. Was cheking the migration script v15->v16 however I didn't find this column being dropped.
The command solves the issue. Thanks a lot!
