### ISSUE TITLE
Memory limit exhausted when exporting CSV/Excel

### ISSUE THREAD

**Issue by jerichoc239** [Dolibarr/dolibarr#22450]
### Bug

Attempting to export Third-parties table  (companies/foundations/physical people) and their properties of 130,000 rows into a CSV brings up this error "Fatal error: Allowed memory size of 1342177728bytes in C:\...\documentRoot\htdocs\includes\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Style\Color.php" on line 400. Zip Code. I am exporting these fields Id, Name, Alias Name, Parent company, Status, Customer, Vendor, Address, Zip Code, City, State/Province, Country, Country code. However, my first attempt to export with even more data was successful, when all other attempts failed. To make matters more odd the only successful export I was able to generate was a single CSV file that came from the same table BUT had more fields, additionally Customer Code, Vendor Code, Accounting Code, Vendor accounting code, City, State/Province. Any assistance would be greatly appreciated.

### Environment Version

15.0.3

### Environment OS

Linux

### Environment PHP

7.4

**Comment by ksar-ksar** [comment]
Hello,

Need to update your PHP settings, how dolibarr is installed ?
https://www.groovypost.com/howto/howto/how-to-solve-php-fatal-error-allowed-memory-size-of-8388608-bytes-exhausted/


For this kind of questions you should go on Dolibarr forums, not GitHub : https://www.dolibarr.org/forum/
