### ISSUE TITLE
Bug V16 banque  account

### ISSUE THREAD

**Issue by surmurthag** [Dolibarr/dolibarr#22451]
### Bug

Hello! I just wanted to report a bug on version 16.0.0, it is impossible to create a bank account even with a super-admin account. the problem came in locahost is also on the remote server. to correct this problem I am simply going back on the V15 

### Environment Version

16

### Environment PHP

7.4.30

### Environment Database

 libmysql - mysqlnd 7.4.30

### Attached files

![image](https://user-images.githubusercontent.com/78571137/192883708-672fcc78-c6f0-4d13-8183-cf6d2111dfb7.png)

**Comment by ksar-ksar** [comment]
Link to : https://www.dolibarr.fr/forum/t/acces-refuse-admin-creation-compte-bancaire-v16-0-0-beta/40514

Can't reproduce this behavior on my testing environment.

Can you reproduce and send the dolibarr logs ?

**Comment by hregis** [comment]
@surmurthag i can't reproduce your bug !
have you externals modules ?

**Comment by surmurthag** [comment]
> Link to : https://www.dolibarr.fr/forum/t/acces-refuse-admin-creation-compte-bancaire-v16-0-0-beta/40514
> 
> Can't reproduce this behavior on my testing environment.
> 
> Can you reproduce and send the dolibarr logs ?

I let you watch by yourself is delete access once you have watched .

**Comment by ksar-ksar** [comment]
Hello,

I have just created two bank account on your environment without issues : 
![image](https://user-images.githubusercontent.com/35605507/193049964-042e7932-5cfc-4f07-8711-2aa90f96bd68.png)

**Comment by surmurthag** [comment]
bonjour ! je viens de comprendre si ont rentre un numéros dans la ref du compte ça mais une erreur 

Hello! I just understood if have entered a number in the ref of the account that but an error 

![testnumber](https://user-images.githubusercontent.com/78571137/193056392-f2c329b4-d8ea-4c54-a720-5947cab5037d.PNG)
![bug](https://user-images.githubusercontent.com/78571137/193056405-22f6a6d7-a992-49e1-9e96-806c3702eec1.PNG)

**Comment by surmurthag** [comment]
> Bonjour
> 
> Je viens de créer deux comptes bancaires sur votre environnement sans problème : ![image](https://user-images.githubusercontent.com/35605507/193049964-042e7932-5cfc-4f07-8711-2aa90f96bd68.png)

pouvez-vous essayer avec des numéros dans la ref ?? 

can you try with numbers in the ref??

**Comment by surmurthag** [comment]
dans la version 15 les numéros dans la ref ne pose aucun problème 

in version 15 the numbers in the ref does not cause any problems
![image](https://user-images.githubusercontent.com/78571137/193058137-7125eb37-ebd7-47b9-a2d4-5fc0c107a716.png)
