### ISSUE TITLE
Wrong VAT for Products in Vendor Purchase Order

### ISSUE THREAD

**Issue by mokacit** [Dolibarr/dolibarr#22455]
### Bug

Good Morning,

we detected that, while preparing a Purchase order with Dolibar Version 16, the system ignores the default VAT rate set for the specific product and uses instead the value written in the form field name "tva_tx" reserved for free text items.

Version 15 works fine.

### Environment Version

16.0.0

### Environment OS

Linux Debian 5.10.136-1

### Environment Web server

Apache

### Environment PHP

7.4.30

### Environment Database

MySQL or MariaDB 5.7.39-1

### Environment URL(s)

/fourn/commande/card.php

**Comment by hregis** [comment]
@mokaffee i can't reproduce your problem !
maybe a conflict with an external module ?

**Comment by mokacit** [comment]
@hregis Thanks for checking. We do not have external modules.

We tested that everything goes back to normal behaviour if we remove the "if" condition (not present in version 15) at line 558 of the file /htdocs/fourn/commande/card.php.
But this modification should be for a reason and we have not identified what could be the root cause of the issue (we have no advanced skills in coding).

**Comment by hregis** [comment]
@mokaffee what is the country of your reseller ? and what is the tva of buying product ?

**Comment by mokacit** [comment]
@hregis The Country of the suppliers is Germany. The defined tva's of the products can be 7% or 19%. However, they are ignored and the system takes what it is written in the form field "tva_tx" reserved for free-text products. Same issue also with Vendors from other countries. VAT for product is set 0% but it is not taken into account.

**Comment by hregis** [comment]
and your country ?

**Comment by mokacit** [comment]
Germany

**Comment by hregis** [comment]
@mokaffee can you contact me directly to see your dolibarr with remote maintenance ?

**Comment by mokacit** [comment]
@hregis I think I can show you the behaviour sharing the screen via some videocon tools. If this is what you mean.

**Comment by mokacit** [comment]
Issue seems to be fixed with version 16.0.1

**Comment by ksar-ksar** [comment]
> Issue seems to be fixed with version 16.0.1

Ok, so can we close the Bug report ?

**Comment by mokacit** [comment]
I was not able to reproduce it anylonger with 16.0.1.
Bug report can be closed.
