### ISSUE TITLE
UNIQUE index for _extrafields table

### ISSUE THREAD

**Issue by fgarciapatino** [Dolibarr/dolibarr#22467]
### Bug

facturedet extrafield table allows multuple fk_object records

### Environment Version

14.0.2

### Environment OS

LAMP

### Environment Web server

Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.21

### Environment PHP

7.4.21

### Environment Database

5.5.5-10.2.39-MariaDB

### Expected and actual behavior

Expected: only one record for foreign key
Actual: multiple records for the same fk 

### Steps to reproduce the behavior

insert into llx_facturedet_extrafields (fk_object, XXX) values ([Valid FK], [Valid value]);
-- And again
insert into llx_facturedet_extrafields (fk_object, XXX) values ([Valid FK], [Valid value]);

**Comment by vmaury** [comment]
I confirm !

**Comment by mc2contributor** [comment]
This is a problem for all `_extrafields` tables, except for `ged_files` and `societe`.  The concept of extra fields, as I understand it, is to add fields to the base table without modifying the base table, so there should be a one-to-one correlation.
