### ISSUE TITLE
The employee status should be linked to the entity and not a boolean

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#22463]
### Feature request

The employee status should be linked to the entity and not a boolean

**Comment by atm-maxime** [comment]
Hi @lmag , I have to say I'm not sure what you mean on this issue :sweat_smile:

**Comment by lmag** [comment]
Effectively without the incomprehensible screenshots

Simple : Pecheur Martin is an employes
![image](https://user-images.githubusercontent.com/3288514/199425632-f25f3318-bc43-4108-9956-51040b334093.png)

Mulicompany: part-time employee in 2 companies
In this case what to do ?

**Comment by hregis** [comment]
@atm-maxime @lmag 
it is not possible for the moment to personalize the parameters of a user, it is necessary to develop the use of the table "llx_user_perentity" present in the module.

**Comment by lmag** [comment]
SoDid you put this issue on your side?

**Comment by hregis** [comment]
@lmag  yes, it concerns Multicompany
