### ISSUE TITLE
import_key deleted when object->fetch and object->update

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#22474]
### Bug

On objects Propal, Commande,Facture,Propal when you call 
$object->fetch($id);
then modify some properties
then
$object->upadte($user);
The property **import_key** is reseted
it's a (big) problem if you're writing import scripts from another database

Solution : add import_key field in function fetch in all objects

In object Product, there's inverted problem with import_key
It's fetched, but not updated

### Environment Version

All including dev

### Environment OS

all

**Comment by milenmk** [comment]
When writing a custom module, I always create a custom extra field to keep MY import keys. I presume those default fields are there for a reason so ...
