### ISSUE TITLE
Fields missing in import

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#22483]
### Bug

When trying to import after having worked with the Product DB in Excel, some fields are missing in the Import tool, among them Supplier and Supplier reference.

All fields are present in the Excel sheet after having done a full export, but when using the Import tool it is not possible to import the above mentionned fields as they don't exisit in the import tool.

### Environment Version

16.0.0

### Environment OS

Debian 11

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

Maria 10.5.15

### Expected and actual behavior

When importing an Excel file or a CSV file the columns shall in the import tool be connected to a field, but in the field listing where the fields shall be choosed, there are some fields missing, among them Supplier and Supplier reference. Please see the attached image

### Steps to reproduce the behavior

Use the export tool to export Products including the fields Supplier and Supplier reference. Then use the import tool to import the same file and you will see that Supplier and Supplier reference are not possible to import as they are not available in the scrollable window where the fields are listed.

### Attached files

![import](https://user-images.githubusercontent.com/24247236/193817875-4f764946-1ddf-4f25-927e-f60f5c882e03.jpg)

**Comment by AndroHunit** [comment]
Same issue on V16,

Excel file has A to AA columns. Depending on Import Type, i was able to find that number of columns shown in source file is the same as available target columns number, for example : 

- Import Tags/Categories show 4 first column of source file for the same file (4 target available)
- Link tag/categories show 2 first column of source file for the same file (2 targets available)

Seems like import function use target available as reference for listing source fields instead of checking if data available in source to list all columns even if not used in this type of import (i have a single file with multiple data like stocks, categories, ...)

It seems to be caused count loop inside file.

I will try to remove it and see how it goes, or replace this with a test loop to find data in each field.

**Comment by AndroHunit** [comment]
**Fixed and tested, check it out, both counting loops were removed. Fields used can't be set another time so maybe should be pulled on next release**

You need to edit the file **/imports/import.php** by : 

Removing this part of code at line 1128-1130 : 
`		if ($i == $minpos) {
			break;
		}`

Removing this part of code at line 1077-1079 : 
`		if ($lefti > count($fieldstarget)) {
			break; // Other fields are in the not imported area
		}`

**Comment by hasse-basse** [comment]
Thanks, I will try and I'll be back with the result, but the line references 1128-1130 are not correct in my version. I find that code at 1133-1135. I'm on 16.0.1

**Comment by hasse-basse** [comment]
Hi again
Sorry to say that it didn't change anything. It is not a matter of number of columns that the import tool can read, it is a matter of that the fileds Fournisseur (Supplier) and Réf. produit fourniesseur (Supplier product reference) does not exisit in the import tool. When you are at Etape 4 (Step 4) in the Import procedure, the fields Fournisseur and Réf. produit fourniesseur does not exist as options to choose in the drop-down menu as can be seen on the below image. As you can see I only exported  6 columns and for the columns E and F (5 and 6) there are no equivalents in the dropmenu to the right when using the Import tool.
![import-produits-step-4](https://user-images.githubusercontent.com/24247236/194846387-d0393196-d82d-4250-ab37-b125fd3949ea.JPG)

**Comment by AndroHunit** [comment]
> Hi again Sorry to say that it didn't change anything. It is not a matter of number of columns that the import tool can read, it is a matter of that the fileds Fournisseur (Supplier) and Réf. produit fourniesseur (Supplier product reference) does not exisit in the import tool. When you are at Etape 4 (Step 4) in the Import procedure, the fields Fournisseur and Réf. produit fourniesseur does not exist as options to choose in the drop-down menu as can be seen on the below image. As you can see I only exported 6 columns and for the columns E and F (5 and 6) there are no equivalents in the dropmenu to the right when using the Import tool. ![import-produits-step-4](https://user-images.githubusercontent.com/24247236/194846387-d0393196-d82d-4250-ab37-b125fd3949ea.JPG)

Hi, 

That's because you select the **wrong** import type on step1.

To import supplier prices or references, you need to select : 

![image](https://user-images.githubusercontent.com/106123483/195901186-0c5d04f5-6e16-4bd1-b28d-5dbfcd6c8ad1.png)

**Comment by hasse-basse** [comment]
Hello

It's weird because with the export tool I can export these fields from the Products category and then it should be possible in the import tool to import them into the Products category, simply by using the same Excel sheet that is the result of the export, in the import procedure. In other words, the export tool and the import tool cannot handle the same fields in the same category, Products. I find this strange if it is supposed to be so and so I still consider it a bug, if there is no technical reason to keep it as is.

It's also not very user friendly as I then have to do two separate imports if I change many things in the product. I may have to live with it, but I think it should be possible to import and export the same fields within the same category.

**Comment by AndroHunit** [comment]
> Hello
> 
> It's weird because with the export tool I can export these fields from the Products category and then it should be possible in the import tool to import them into the Products category, simply by using the same Excel sheet that is the result of the export, in the import procedure. In other words, the export tool and the import tool cannot handle the same fields in the same category, Products. I find this strange if it is supposed to be so and so I still consider it a bug, if there is no technical reason to keep it as is.
> 
> It's also not very user friendly as I then have to do two separate imports if I change many things in the product. I may have to live with it, but I think it should be possible to import and export the same fields within the same category.

I understand, but that can't be part of a bug, as it works, just _slightly differently than you would want it._ 
You should consider editing the module itself or developping an all-in-one import system, but it requires time and some skills.

I will have a look at the script **tomorrow** and get back with what can be done. 
Import tool works basically as a CSV/XSLX parser with basic SQL queries filling DB tables.
