### ISSUE TITLE
Radio button empty value gives ErrorBadValueForParamNotAString

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#22494]
### Bug

I try to make a Radio button in "Attributs supplémentaries (commandes)" but when there is no value chosen this message appear: "ErrorBadValueForParamNotAString"

### Environment Version

16

### Environment OS

Debian 11

### Environment Web server

Apache

### Environment PHP

7.4.30

### Environment Database

Maria 10.5.15

### Expected and actual behavior

When making a Radio button list in "Attributs supplémentaries (commandes)" it is not possible to leave an empty value as it gives the message "ErrorBadValueForParamNotAString" both in the listing and on the card, as can bee seen on the 2 attached images.

I assume it should be possible to leave an empty value?

The Radio button list looks like this

1,Reçu
2,Confirmé
3,Refusé

I've temporarly solved it by checking Required and added one more row like this

1,Pas d'réponse
2,Reçu
3,Confirmé
4,Refusé

### Attached files

![listing](https://user-images.githubusercontent.com/24247236/194125721-fc891f99-fe59-4d44-ba1c-b078f7c19335.jpg)
![card](https://user-images.githubusercontent.com/24247236/194125737-acb214c7-670e-40cf-9443-056f899f911c.jpg)

**Comment by ns-info90** [comment]
impossible to reproduce the problem
![image](https://user-images.githubusercontent.com/45969285/200133362-2b5f9631-fcc8-4a94-9ede-d58ab430d171.png)

**Comment by hasse-basse** [comment]
Hi

I created a new field in Commercial proposals module

![1](https://user-images.githubusercontent.com/24247236/200183564-2854d729-c106-4367-af87-5506b8a9d59c.jpg)

and then I made a price proposal, and as you can see the problem remain.

![2](https://user-images.githubusercontent.com/24247236/200183601-44ba129c-48a8-4321-b853-14ba54d1f357.jpg)

This message is not unknown to Dolibarr

https://www.dolibarr.fr/forum/t/errorbadvalueforparamnotastring-si-trad-vide/19508
https://github.com/Dolibarr/dolibarr/issues/6770
https://www.javierrguez.com/errorbadvalueforparamnotastring-la-gestion-contratos-dolibarr/
https://imprecates3.rssing.com/chan-3280461/all_p1036.html

Could it have to do with what DB engine being used? I'm on Maria.

**Comment by hasse-basse** [comment]
I made a clean intallation of 16.0.1 and the same occeurs there

**Comment by ibuiv** [comment]
![image](https://user-images.githubusercontent.com/50403308/204059984-e9dcd0dd-ffb6-455c-9b0f-18d611939c74.png)

Looks fine to me 16.0.3

**Comment by hasse-basse** [comment]
Hi

It seem like we are talking about diffrent things, because you don't do it as I do it. I just made a test installation of 17.0.0-beta (couldn't find 16.0.3) and the problem remain, the problem as per my definition. Pls see below.

I created a radio button attribut with the values
1,One
2,Two
3,Three

![1](https://user-images.githubusercontent.com/24247236/204096315-1c452e10-5b52-4ed6-80b5-77709176cc3d.jpg)

**Then created a New price request leaving all 3 values empty**

![2](https://user-images.githubusercontent.com/24247236/204096336-bb07a1e7-a2d9-427d-9b5f-5f3dc13cb36f.jpg)

**and clicked save, and as you can see the text "ErrorBadValueForParamNotAString" appears**

![3](https://user-images.githubusercontent.com/24247236/204096555-0756aa17-4b8b-4f95-95c3-278d9e754e41.jpg)

**Then I choose one value ......**

![4](https://user-images.githubusercontent.com/24247236/204097023-bcb8cccb-50bf-4c65-9cb7-cbe981d46535.jpg)

**And and saved and the message is gone**

![5](https://user-images.githubusercontent.com/24247236/204097054-795c4920-10f6-473b-bf57-a74aa9b9aa34.jpg)

So what I think is a problem, remain. You got another result because your setup of the problem is different than mine. A value must be choosen, otherwise the message "ErrorBadValueForParamNotAString" will appear at Save. There is a workaround, and it is to give the list a Default value:

![6](https://user-images.githubusercontent.com/24247236/204097600-37872a14-12f7-447b-ac19-9f0fb9464f2f.jpg)

**And then the problem is gone**

![7](https://user-images.githubusercontent.com/24247236/204097627-734f1ed2-f005-443b-a131-1204ebfeaa20.jpg)

![8](https://user-images.githubusercontent.com/24247236/204097738-40f91b46-a14e-466f-8258-6977f9a3e12b.jpg)

If it is not possible to avoid the message "ErrorBadValueForParamNotAString" when no value is choosen I think  it should be enforced to set a Default value.

**Comment by ibuiv** [comment]
Thanks a lot for the details 
sorry for the first misunderstanding
I just PR a bugfix (two changes : missing trans is fixed and the error message was not the best choice)
Will be updated

Warning : I think the radio button on extrafield should be always required and the default value in the range of the list. With an example : 0, No value => to be continued ?

**Comment by hasse-basse** [comment]
Great, at least there should be a clear instruction about it. I don't know what is possible to do in programming.

So then I can close it, I guess?
