### ISSUE TITLE
in Module Builder on interger filed with default if it is not displayed the default value is not used

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#22509]
### Bug

On New module create a field

'status_custom' => array('type'=>'integer', 'label'=>'Status', 'enabled'=>'1', 'position'=>2000, 'notnull'=>1, 'visible'=>5, 'default'=>1, 'index'=>1, 'validate'=>'1',),

Create the object
value is 0

### Environment Version

15.0, 16.0

### Attached files

https://user-images.githubusercontent.com/1050053/194341786-79e4c043-2b9c-498d-a0ae-256c0bd35ea3.mp4

**Comment by ksar-ksar** [comment]
@FHenry Just by curiosity, what is the nice tool you use to developp ?

**Comment by FHenry** [comment]
Phpstorm (my only "breaking rule" to open source or do not use it)

**Comment by ksar-ksar** [comment]
Thanks!

**Comment by eldy** [comment]
I don't see what's wrong.
If field has property "not null" and default to 1, it meas it will be 1 if no info is provided.
Bu if you set the value to 0 = draft explicitely, we must store 0. Default value must apply only if we enter nothing (if we keep combo with no value)

**Comment by FHenry** [comment]
@eldy The field status_custom is not provided as it visibility set 5 and default is 1 and notnull=1, I just copy the status field for sample, but it's another field, it's confusing but check it again
