### ISSUE TITLE
Projects permissions

### ISSUE THREAD

**Issue by jsbrassard** [Dolibarr/dolibarr#22504]
### Bug

The "Create/Modify projects (shared and projects of which I am a contact)" permissions doesn't allow to modify or delete time consummed in the time spent of the task

![image](https://user-images.githubusercontent.com/51123237/194310183-f70d718d-c1cc-4dc4-a0e3-8dbb39615028.png)

In 15.0.3 this permession allowed to do that.

### Environment Version

16.0.0

**Comment by ksar-ksar** [comment]
In V16, you have a new permission to do that : 
![image](https://user-images.githubusercontent.com/35605507/194315302-8462758e-8cfc-473a-9df1-37089e9ee237.png)

Was not existing in V15 : 
![image](https://user-images.githubusercontent.com/35605507/194315454-be7a0746-b215-411d-acb5-9f71c0461d1e.png)

**Comment by jsbrassard** [comment]
Hi ksar, I did try that, but it's not working. This permissions is to enter time consummed. I am talking about the ability to modify or delete time.

As you can see, the option is not displayed even if I have added this new permission

![image](https://user-images.githubusercontent.com/51123237/194316766-f00d4b0b-dc79-4495-be5e-9ea0e3e0dcdb.png)
