### ISSUE TITLE
Constant INVOICE_CAN_ALWAYS_BE_EDITED not working in 16.0.0

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#22516]
### Bug

When you enable constant INVOICE_CAN_ALWAYS_BE_EDITED you must be able to edit invoice lines no matter the status. In our particular case we use it to add serial numbers to the invoice.  
Since version 16.0.0 this is no longer working, no pencils show up for editing. 

### Environment Version

16.0.0

### Environment OS

Ubuntu 

### Environment Web server

apache

### Environment PHP

7.4

### Environment Database

mysql

### Environment URL(s)

/compta/facture/card.php?facid=xxx

### Expected and actual behavior

Should be able to edit invoice lines

### Steps to reproduce the behavior

Reopen an invoice for editing

**Comment by erikvanberkum** [comment]
got it working my mistake

**Comment by biosk4hvd** [comment]
Hello,

i have the same issue on 2 separate Dolibarr installations. It started when I upgraded from 15.x to 16.0.3.

Could you please tell me how you solved it?

**Comment by erikvanberkum** [comment]
Sorry to inform you but i havent got this solved. This issue still persists in my 16.0.2 version.

**Comment by IC-Mathieu** [comment]
I don't find an instance of INVOICE_CAN_ALWAYS_BE_EDITED on v16.0.3, is that normal? @eldy

**Comment by erikvanberkum** [comment]
@IC-Mathieu can you explain what you mean by an **instance** of INVOICE_CAN_ALWAYS_BE_EDITED

**Comment by IC-Mathieu** [comment]
I don't find any line in the code where there is INVOICE_CAN_ALWAYS_BE_EDITED in v16

**Comment by erikvanberkum** [comment]
It looks like 
INVOICE_CAN_ALWAYS_BE_EDITED
needs to be replaced with 
INVOICE_CAN_BE_EDITED_EVEN_IF_PAYMENT_DONE
to have the functionality back. 

Let me know if it works, than I will close the issue.

**Comment by biosk4hvd** [comment]
Hello.

It fixes the issue for the customer invoice, however the Vendor Invoice can still not be modified.

Any fix around that?

**Comment by erikvanberkum** [comment]
I never had that enabled. Which config->global word is used for that? Something like VENDOR_CAN_????
Then I will have a look in the code if that is also changed.

**Comment by biosk4hvd** [comment]
To be quite frank, I had it enabled in the 15.x version of Dolibarr but I do not know how I achieved that... I looked through my global words, i do not have a specific config word for it.

Maybe same config word enabled editing both kinds or invoices in the previous builds?

**Comment by erikvanberkum** [comment]
if i go to this url: /fourn/facture/card.php?facid=22 could be any other number add the end, and that vendor invoice is paid. I have the following option available:

![image](https://user-images.githubusercontent.com/7335299/209631657-2789af5d-64c0-440c-ac35-9ae28a0c040f.png)

with reopen you are able to edit it again aren't you?

**Comment by erikvanberkum** [comment]
Added "updated constant" to Dolibarr wikipage Setup other

https://wiki.dolibarr.org/index.php?title=Setup_Other#Invoice_Module


INVOICE_CAN_ALWAYS_BE_EDITED changed in version 15 or 16 to INVOICE_CAN_BE_EDITED_EVEN_IF_PAYMENT_DONE ► Allow to edit invoices even if payment was started. Note: If the module "BlockedLog" is active (required in some countries for legal reasons), this will not change content of archived logs tracked by this module. By definition there is no way to change or remove archived records. It will just update data in your application and a new record to track your change into the read-only archive log.
