### ISSUE TITLE
Implement the view "message" found into ticket in "Event/Agenda" tab into tab "Event/Agenda" for Project and Thirdparty

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#22527]
### Feature Request

Implement the view "message" found into ticket in "Event/Agenda" tab into tab "Event/Agenda" for Project and Thirdparty
We must add a page "messaging.php" that can be a copy of ticket, saved into same dir than pages "agenda.php" and store it into 
societe/messaging.php
project/messaging.php
Like for ticket, we must be able to switch between the view "agenda" and the view "message".
View message that exists only for tickets:
![image](https://user-images.githubusercontent.com/883887/194682171-a46cca5e-9d97-40ae-9bf2-e0aa848f743f.png)
View agenda that already exists for tickets, thirdparties and proejcts:
![image](https://user-images.githubusercontent.com/883887/194682195-7ce0495b-a626-4fd0-bd1a-a37ab76f1e9c.png)

The button "Send email" and "Add message" can be removed (commented in code) for the version for thirdparties and project.

**Comment by fboitel** [comment]
Should the buttons "Send email" and  "Add message" have also to be implemented ?
