### ISSUE TITLE
Introduce access right to view / edit / create e-mail templates

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#22534]
### Feature Request

Currently every user has to ability to view / edit / create e-mail templates. Therefore also every user can see the menu option "Tools" ⇨ "E-Mail Templates".

There should be a new access right for viewing / editing / adding e-mail templates. If a user has no rights the menu option "Tools" ⇨ "E-Mail Templates" should not be shown. If there are not other menu items in the left menu, also the main menu entry "Tools" should not be shown.

### Use case

Espacially when a user has very limited access rights it is very confusing that there is always the menu item "Tools" ⇨ "E-Mail Templates".

E.g. lets assume a user has just the right to view a list of contact / thirdparties. The user will not understand why he/she can see also the menu item "Tools"

### Suggested implementation

Add new access rights to view / edit / create e-mail templates

OR

Just remove this menu item, because e-mail templates can also be edited / added via "Settings" ⇨ "E-Mails" ⇨ "-Mail Templates"

**Comment by atm-maxime** [comment]
Is it still relevant?

**Comment by glu000** [comment]
Yes, still relevant
