### ISSUE TITLE
Supplier order: wrong price format when selecting a product

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#22535]
### Bug

When creating a new line in a supplier order and selecting a pre-defined product with a supplier price, the format of the price is always using "." as decimal char instead of correct local setting. This is a) an optical problem and b) leads to follow-up problems in following case which is typical German setting:

* local setting decimal char = ','
* local setting thousands char = '.'
* pre-defined price has 3 digits after comma

Let's make an example with a price of 1.553. The correct German view would be 1,553 (because decimal character is ',') When selecting the product with the pre-defined price then the line is saved as 1553, because when saving the line the input is assumed to be in correct local format and the "." is interpreted as thousands char.

### Environment Version

16

### Environment OS

n/a

### Environment Web server

n/a

### Environment PHP

7.4

### Environment Database

na

### Environment URL(s)

/fourn/commande/card.php

### Expected and actual behavior

The correct local price setting should be used when selecting a pre-defined product

### Steps to reproduce the behavior

* Set local settings to German
* Create a product
* Create a supplier price for that product with 3 digits after comma (e.g. 1.553)
* Create a new supplier order
* Create a new line and select the pre-defined product
* Save the line

The unit price will be 1553 instead of 1.553

**Comment by atm-maxime** [comment]
@glu000 can this issue be closed ?

**Comment by glu000** [comment]
Yes, it works
