### ISSUE TITLE
Bug: Solde initial indiqué "short" - module accountancy

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22539]
### Bug

Version: 16.0.0

Hello,

In
![image](https://user-images.githubusercontent.com/2222550/194981256-b9402566-46c1-480b-a237-f6e18fc45a6f.png)

I wrote a "solde initial", edited it, changed type to whatever value and changed it back to void
![image](https://user-images.githubusercontent.com/2222550/194981323-84e1c8f2-d897-4f35-81fc-dc5073b3e91a.png)
But at the end it's written "short"
![image](https://user-images.githubusercontent.com/2222550/194981455-db571f07-65d5-420d-8d16-fb49d151c46c.png)

I don't know what that means but it should be written in french, and I suppose this field should be blank, the way I configured it when editing the "écriture comptable".

Regards

### Environment Version

16.0.0

**Comment by Delthair** [comment]
Hello, 

Have you tried to pass on the 16.0.2 version ?

**Comment by mikygee** [comment]
![image](https://user-images.githubusercontent.com/2222550/204114491-0a39a9a6-60f4-4ebf-9091-0bddc21af30e.png)

**Comment by daraelmin** [comment]
Hi,

I do mot understand the process you followed. Could you explain it better ?

To me, the first amount is only set when you create the new account, ans I do mot expriment issue on that. But you seems to have register it by an other way.

Cheers

**Comment by mikygee** [comment]
Closed but not solved in 18.0.3
Please reopen !

**Comment by mikygee** [comment]
I'm going to retest this before the end of the year.
I'm working on the installation of accountancy Dolibarr module at the moment.

**Comment by mikygee** [comment]
Hello,
The problem is still here in version 20.0.1.
![image](https://github.com/user-attachments/assets/4535916e-ed53-4c04-a4c3-1284917c3a2a)

To reproduce the problem, create a bank account with an initial amount of 2000.
Then in Ecritures bancaires, édit the amount and change it to 3000 and/or change the date.
The term "short will appear"

**Comment by inoveaconseil** [comment]
I can't reproduce in 20.0.2
![Capture d’écran du 2024-11-15 14-26-30](https://github.com/user-attachments/assets/5acfc3d3-e7ab-4a47-8bec-e3149de1df12)
