### ISSUE TITLE
Sum of order values should take into account already delivered parts.

### ISSUE THREAD

**Issue by scaleo-hds** [Dolibarr/dolibarr#22547]
### Feature Request

We often get a customer order (order for a whole year) which will be delivered in 6 to 12 part - deliveries.
In the list of all orders, we wish to see a column with the undelivered part values of the customer order. Actually we only see the overall order value and the sum of it (this shall remain, because is also necessary to know). 
 

### Use case

if I check how big are the value of all open customer order positions, I need a additional column with those values.

### Suggested implementation

subtraction : cost of all goods of an order subtracted with cost of the delivered goods of that order.

**Comment by Julian-Dumitrascu** [comment]
This seems a simple calculation that could be done with a module like Odoo Studio. Does Dolibarr include such functions?

**Comment by scaleo-hds** [comment]
If it would be possible that I can combine a user defined field with a formular, then such features will be realized very easy in furture.
