### ISSUE TITLE
Typo kills extra vars in proposal lines

### ISSUE THREAD

**Issue by st31ny** [Dolibarr/dolibarr#22557]
### Bug

Since version 16.0.0 extra fields in lines of proposals stopped working. I believe the bug was introduced in af73f2b68305 there: https://github.com/Dolibarr/dolibarr/blob/95b69eaefbea97b0d7f1e7bd5296a7eaac07ce5e/htdocs/core/class/commondocgenerator.class.php#L953
This line checks whether the key `'option_'.$key` exists, however the next line uses (as the code before the change) the key `'options_'.$key` ("option" vs "options"). Indeed, adding the "s" to "option" in the `if` fixes the issue for me.

### Environment Version

16.0.0

### Environment OS

Debian

### Environment Web server

nginx 1.14

### Environment PHP

7.3

### Environment Database

MariaDB 10.3

### Environment URL(s)

/comm/propal/card.php

**Comment by hregis** [comment]
@st31ny fixed with this PR https://github.com/Dolibarr/dolibarr/pull/22563
