### ISSUE TITLE
Complementary attributes (lines) not printed on PDF Aurore for Vendor qoutes

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#22554]
### Bug

I've set up a number of Complementary attributes and Complementary attributes (lines) and it all works fine except in Vendor qoutes where Complementary attributes (lines)  are not being printed on the PDF document, what ever setting I use for the PDF printing using the Aurore PDF template (Aurore is all what I have).

### Environment Version

16.0.1

### Environment OS

Debian 11

### Environment Web server

Apache 2

### Environment PHP

7.4.30

### Environment Database

Maria 10.5.15

### Environment URL(s)

/htdocs/supplier_proposal/card.php and /htdocs/supplier_proposal/admin/supplier_proposaldet_extrafields.php

### Expected and actual behavior

When creating "Complementary attributes (lines)" in htdocs/supplier_proposal/admin/supplier_proposaldet_extrafields.php

for "Vendor qoutes" the content should be printed on the PDF if "Display on PDF" is set to 1, 3 or 4, but nothing is printed what ever setting I use.  "Aurore"  PDF template.

All looks just fine on the card /htdocs/supplier_proposal/card.php

**Comment by ksar-ksar** [comment]
Hello,

It's because it is not implemented yet.

**Comment by hasse-basse** [comment]
Hi and thanks

But why is it there? Have I happend to start something experimental, or? It is sort of annoying as I've spent some 1h+ to work with it.

**Comment by ksar-ksar** [comment]
New document template has been gradually introduced since V12.
Nobody worked yet on a new document template for supplier quotes.

But dolibarr is open source you can work on it !

For the moment, you can also modify aurore to get what you want : https://wiki.dolibarr.org/index.php?title=Add_Extrafields_on_PDF_Models

**Comment by hasse-basse** [comment]
Thanks.

I wasn't sure if it was about a setting or the PDF template. I'll se what I can do, but I'm not that savy in coding so I'm not sure the result will be that good if I add something to Github. I will have a look at your link and see if I can do something, and if the result is good,, I might be posting it.
