### ISSUE TITLE
v16.0.0 - Calculated attribute is now shown on the list of objects

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#22552]
### Bug

If an attribute is added into an object (like Order) with a calculated value based on a existing "core" attribute like the ID, the value is not automatically shown in the list. 

### Environment Version

16.0.0

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.3

### Environment Database

MySQL

### Environment URL(s)

16.0.0

### Steps to reproduce the behavior

How to reproduce ? 

1. Goto http://_**XXXX**_/admin/order_extrafields.php
2. Create an extrafield on the object "Order" named "**_magasin_**" (string)
3. Add the following code to the calculated value 

`($object->id ? $object->id : $obj->id)`

Check a detail order : http://_**XXXXX**_/commande/card.php?id=_**12345**_

In field "magasin, you will see the value of the ID -> OK

Check the list of orders =: http://_**XXXXXX**_/commande/list.php

neither $object or $obj display the expected value. 

### Attached files

![Commandes](https://user-images.githubusercontent.com/26635105/195356185-7cd23f36-4769-401f-bf2e-8237289fc665.jpg)

**Comment by hregis** [comment]
@daxitsolutions try this instead

`($object->id ? $object->id : ($obj->id ? $obj->id : $obj->rowid))`

**Comment by daxitsolutions** [comment]
@hregis you're right ! this topics can be closed. 
Thanks for the help.
