### ISSUE TITLE
SQL Error in related items on the product page

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#22555]
### Bug

I get the following error when clocking on the related items for a product: 

Date: 20221012174347
Dolibarr: 16.0.1 - https://www.dolibarr.org
Level of features: 0
PHP: 7.4.32
Server: Apache
OS: Linux  5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

Requested URL: /product/stats/facture.php?showmessage=1&id=964
Referer: xxxxx
Menu manager: eldy_menu.php

Modules/Applications: user, api, product, modulebuilder, stock, expedition, blockedlog, propal, supplier_proposal, incoterm, contrat, ficheinter, projet, categorie, tax, notification, workflow, emailcollector, resource, service, societe, variants, accounting, agenda, banque, barcode, cron, commande, ecm, expensereport, facture, fournisseur, holiday, bom, multicurrency
Database type manager: pgsql
Latest database access request error: SELECT COUNT(DISTINCT f.fk_soc) as nb_customers, COUNT(DISTINCT f.rowid) as nb, COUNT(fd.rowid) as nb_rows, SUM('fd.qty') as qty FROM llx_facturedet_rec as fd, llx_facture_rec as f, llx_societe as s WHERE f.rowid = fd.fk_facture AND f.fk_soc = s.rowid AND f.entity IN (1) AND fd.fk_product = 964
Return code for latest database access request error: DB_ERROR_42725
Information for latest database access request error: ERROR: 42725: function sum(unknown) is not unique\nLINE 1: ...TINCT f.rowid) as nb, COUNT(fd.rowid) as nb_rows, SUM('fd.qt...\n ^\nHINT: Could not choose a best candidate function. You might need to add explicit type casts.\nLOCATION: ParseFuncOrColumn, parse_func.c:562

**Comment by hregis** [comment]
@GMellar fixed with this PR https://github.com/Dolibarr/dolibarr/pull/22564
