### ISSUE TITLE
PHP 8.1 LDAP Error when having dol_syslog enabled

### ISSUE THREAD

**Issue by palexandri** [Dolibarr/dolibarr#22570]
### Bug

PHP8.1 outputs the following error when using ldap test:
PHP message: PHP Fatal error:  Uncaught Error: Object of class LDAP\Connection could not be converted to string in /var/www/dolibarr/htdocs/core/class/ldap.class.php:1043

The issue is resolved when the line is commented out.

 The LDAP\Connection can no longer be converted to string 

### Environment Version

16.0.1

### Environment Web server

nginx

### Environment PHP

8.1

**Comment by madecto** [comment]
Hi, I can confirm this happening also in 16.0.4 at line 1061.

**Comment by samea-innovation-it-team** [comment]
Bonjour,
Same problem on a Synology LDAP server, dolibarr 16.0.4, Tuxgasy docker.
Pascal
