### ISSUE TITLE
[IHM]-Only allow a quantity of 1 when adding stock if the product is managed with a serial number

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#22582]
### Bug

Only allow a quantity of 1 when adding stock if the product is managed with a serial number

### Attached files

![image](https://user-images.githubusercontent.com/3288514/195809089-f0a1f83d-6f5e-4407-8aaa-b2ef925950fc.png)

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
