### ISSUE TITLE
Shipping multiple products that have unique serial numbers

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#22581]
### Bug

When shipping product with serial number We can ship a quantity greater than 1

### Expected and actual behavior

- [ ] Step 1 : Solve #22582 
- [ ] Step 2 : add the link between shipment lines and stock movements

**Comment by FHenry** [comment]
![image](https://user-images.githubusercontent.com/1050053/195807330-014286ce-39ad-4724-8ff6-dd9cd9899499.png)

**Comment by FHenry** [comment]
https://user-images.githubusercontent.com/1050053/195807426-f65ea679-1947-4f33-aaad-70e2ba2c2c33.mp4
