### ISSUE TITLE
Isn't facturedet->ventil supposed to be facturedet->fk_code_ventialtion

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#22585]
I have Dolibarr 13 and there on fournisseur.facture.class when creating a line $ventil is assigned to the line's property $ventil

On the latest version I can see this was fixed so $ventil got assigned to the line's property $fk_code_ventilation.
https://github.com/Dolibarr/dolibarr/blob/51ab54dc3cf03ef5fc3ef988b29515d216edd8a4/htdocs/fourn/class/fournisseur.facture.class.php#L2202

Currently on customer's invoice when creating a line $ventil is still assigned to the line's $ventil property, if you ctrl-f `->ventil` it's never used anywhere else, meanwhile `->fk_code_ventilation` is used.
Is this the same error from fournisseur.facture.class?
https://github.com/Dolibarr/dolibarr/blob/51ab54dc3cf03ef5fc3ef988b29515d216edd8a4/htdocs/compta/facture/class/facture.class.php#L3770

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by Daviid-P** [comment]
Seems like it is:

https://github.com/Dolibarr/dolibarr/blob/f8d81e3ae00b1aa344d97fa4d1d135f97b22af27/htdocs/fourn/class/fournisseur.facture.class.php#L2207

https://github.com/Dolibarr/dolibarr/blob/f8d81e3ae00b1aa344d97fa4d1d135f97b22af27/htdocs/compta/facture/class/facture.class.php#L3991

On `facture.class.php` `ventil` is never used:
![Sgqv8Hi 1](https://github.com/Dolibarr/dolibarr/assets/7734808/d24c205f-a0cb-44b6-9193-58c4bf76759b)


When doing `addline` the line's property `ventil` is filled but when doing `insert` it'll try to look for `fk_code_ventilation`
