### ISSUE TITLE
Bug: New installation with Dolibar 16, it shows the error that the inventory table does not exist.

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#22593]
# Bug
Código de retorno de error para la última petición de acceso a la base de datos: DB_ERROR_NOSUCHTABLE
Información del último error de petición de acceso de base de datos: Table 'zenged_rainges.llxbx_inventory' doesn't exist

## Environment
- **Version**: 16.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /product/inventory/list.php?leftmenu=stock_inventories

## Expected and actual behavior
When performing a new installation with Dolibar 16, it shows the error that the inventory table does not exist.

**Comment by hregis** [comment]
@leninrivas try to disable/enable "stock" module

**Comment by leninrivas** [comment]
Hello.
I did and the problem persists. I also disabled the products module and re-enabled it and the problem persists. Attach log.
[ErrorDolibarr16.log](https://github.com/Dolibarr/dolibarr/files/9792071/ErrorDolibarr16.log)

**Comment by hregis** [comment]
@leninrivas can try a fresh install without your externals modules and llx_ instead llxon_ ?

**Comment by leninrivas** [comment]
I disabled product module and updated to version 16.0.1 and the problem fixed
Thank you for your help.
