### ISSUE TITLE
MO Creation Error

### ISSUE THREAD

**Issue by fgarciapatino** [Dolibarr/dolibarr#22609]
### Bug

When creating a new MO from a BOM, the materials list is truncated because of an execution error. 

There is a $form instance missing.
Just add before line 63 at /mrp/tpl/originproductline.tpl.php on line 63: 

$form = new Form($db);

### Environment Version

16.0.1

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.2

### Environment Database

MySQL 5.7

### Environment URL(s)

/mrp/mo_card.php?action=create&fk_bom=1

### Expected and actual behavior

Expected: the MO card completely shown
Actual: **Fatal error**: Uncaught Error: Call to a member function textwithpicto() on null... /mrp/mo_card.php(350): Mo->printOriginLinesList('', Array) #3 {main} thrown in /srv/disk3/3253267/www/socarratt.atwebpages.com/mrp/tpl/originproductline.tpl.php on line 63

### Steps to reproduce the behavior

Just ask for a new MO

**Comment by IC-Ilies** [comment]
Hello, i can't reproduce the bug after several tries in this version of Dolibarr. Is this issue persisting ? Have you got more info ?
