### ISSUE TITLE
dolibarr.org is down

### ISSUE THREAD

**Issue by jeritiana** [Dolibarr/dolibarr#22606]
### Bug

I am not sure this is the right place to report this, but the [Dolibarr official website](https://www.dolibarr.org/) is down since this morning (08:00 GMT).

In my case, this especially impacts the access to the forum.

Thanks!

### Environment URL(s)

https://www.dolibarr.org/

### Expected and actual behavior

The Dolibarr official website is available.

### Attached files

![image](https://user-images.githubusercontent.com/5649605/196130442-fef3f9ee-d236-4686-b908-fe7237da030e.png)
![image](https://user-images.githubusercontent.com/5649605/196130369-9dcf51ed-82df-4188-9039-d1280f4227e1.png)

**Comment by ksar-ksar** [comment]
It's back online
