### ISSUE TITLE
Bug: Recruitment cannot update from draft to validated

### ISSUE THREAD

**Issue by openITservice** [Dolibarr/dolibarr#22608]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Recruitment cannot update from draft to validated

## Environment
- **Version**: 16.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: apache2handler 7.2.24-0ubuntu0.18.04.13
- **Database**: MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0ubuntu0.18.04.1
- **URL(s)**: /dolibarr/recruitment/recruitmentjobposition_card.php?id=1&action=confirm_validate&token=41cc09c154135f19445ce98818b67356&confirm=yes

## Expected and actual behavior
create Recruitment new and it stay in concept when you validate it 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by edupulpillo** [comment]
Can not reproduce the problem in 16.0.3

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by edupulpillo** [comment]
In V18.0.2 the problem is fixed and works fine with PHP8.1 and PHP 7.4
