### ISSUE TITLE
Missing proposal box on dashboard

### ISSUE THREAD

**Issue by ivanfelicite** [Dolibarr/dolibarr#22601]
### Bug

Since 16.0, the proposal box is not available on the dashboard.
It was the box on the homepage that display the number of open proposals and the number of outdated proposals (like for invoices, orders...).

<img width="1819" alt="Missing proposal box on dashboard widget" src="https://user-images.githubusercontent.com/17528584/196032107-74144374-4d90-4de6-8885-c6d53b1fabc8.png">

### Environment Version

16.x

### Environment PHP

8.0

**Comment by hregis** [comment]
@ivanfelicite 
fixed with this PR https://github.com/Dolibarr/dolibarr/pull/22602
thanks
