### ISSUE TITLE
Margin module dot/comma confusion

### ISSUE THREAD

**Issue by svewa** [Dolibarr/dolibarr#22614]
### Bug

Margin module uses "." (dot) as decimal delimiter, no matter the language settings.

### Environment Version

16.0.0

### Environment OS

Ubuntu 22.4

### Environment Web server

Apache

### Environment PHP

8

### Expected and actual behavior

For countries like [Countries_using_decimal_comma](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma) I'd expect the "," (comma) in stead of the "." (dot).

### Steps to reproduce the behavior

Use German language, enter a cost price, enter a margin and see the resulting U.P. explode due to misinterpretation of the decimal delimiter, at least if the result contains a fraction.

**Comment by priojk** [comment]
Seems similar to #22536

**Comment by svewa** [comment]
fixed in 17.0.1
