### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by amrelsharaby** [Dolibarr/dolibarr#22612]
# Bug
[No possibility to add sub-BOMs to BOM]

## Environment
- **Version**: 16.0.0
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: apache2handler 7.1.33-50+ubuntu18.04.1+deb.sury.org+2
- **Database**: MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0ubuntu0.18.04.1
- **URL(s)**: /dolibarr/htdocs/bom/bom_list.php

I expected Either to have a multiple add field for others boss to be add in a main bom, or to have the ability to add a bom as a consumable for other bom .
 But what's really happening there is no difference than old version except for the NetsofBom

**Comment by ksar-ksar** [comment]
Hello,

Not sure to understand your issue.

On V16, the sub BOM is a hidden configuration : BOM_SUB_BOM
https://github.com/Dolibarr/dolibarr/pull/19935

**Comment by amrelsharaby** [comment]
Thanks a lot,  the issue was that I didn't know it is a hidden configuration, so I didn't know where the sub-box option is,
So is there an option to automaticly create a manufacturing order for the sub_boms while creating MO for the main bom?

Also where I could find an updated list with the hidden configurations?

Thank you so much.

**Comment by ksar-ksar** [comment]
> Also where I could find an updated list with the hidden configurations?

https://wiki.dolibarr.org/index.php?title=Setup_Other
