### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#22621]
### Bug

Hello, is Dolibarr compatible and stable with PHP version 7.4.32?

### Environment Version

16.0.1

**Comment by hregis** [comment]
@alimentarius yes it's compatible

**Comment by alimentarius** [comment]
but I tried to update and it just shows me a blank screen

**Comment by hregis** [comment]
@alimentarius update dolibarr ? from which version to which version ?

**Comment by alimentarius** [comment]
7.4 to 7.4.32

**Comment by alimentarius** [comment]
I had to go back... but I have Projectsend that needs this version 7.4.32

**Comment by hregis** [comment]
@alimentarius check your Apache or Nginx logs !

**Comment by alimentarius** [comment]
apache php 7

**Comment by hregis** [comment]
@alimentarius sorry, you must contact a professional for your web hosting, Github is made for application developers, you have a problem with your hosting, nothing can be done for you!

**Comment by alimentarius** [comment]
thanks

**Comment by hregis** [comment]
@alimentarius https://wiki.dolibarr.org/index.php?title=List_of_Dolibarr_partners_and_providers
