### ISSUE TITLE
Bug: Bill "fournisseur" + service: rate=20% instead of 0%

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#22623]
### Bug

Version 15.0.3

Hello,
I created a service which has a VAT rate of 0% (that's how some banks  bill their services)
![image](https://user-images.githubusercontent.com/2222550/196568378-cecd264d-a94b-4041-87b5-f39031019601.png)

I create it with
Tiers > Fournisseur > Créer une facture
NB: The third party is in France.
When I select « Services prédéfinis à acheter », the price that I had previously written is correct but after adding the line I can see a 20% VAT which is wrong.
![image](https://user-images.githubusercontent.com/2222550/196568671-3b09c1ee-b4ca-4afd-9ce8-c2a3d87cbf00.png)
As a workaround I need to reedit it and type 0% but that's not how it should work.

When I change the thirdparty from France to Panama for example, the rate is now 0%

So, the problem is that the bill takes into account the location of the thirdparty and applies a default VAT rate and doesn't take into account that VAT rate I indicated in the service.

French translation here
https://www.dolibarr.fr/forum/t/facture-fournisseur-service-taux-a-20-au-lieu-de-0/41243

Regards

### Environment Version

15.0.3

**Comment by SylvainLegrand** [comment]
It's not a bug.

This behavior was made to apply the vat rules between different countries.

**Comment by mikygee** [comment]
It's a bug, french VAT is not always 20% !
Assuming french VAT is only 20% is an error.
No !
