### ISSUE TITLE
Multiple Undefined property: stdClass:: since 16.0.1

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#22631]
### Bug

Hi, since last update to 16.0.x, I experience here and there warning messages such as:

- under /user/param_ihm.php?id=1 
<div class="div-table-responsive-no-min" style="overflow-x: auto; min-height: 0.01%; color: rgb(0, 0, 0); font-family: arial, tahoma, verdana, helvetica; font-size: 14.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Simplify interface for blind person | Warning: Undefined property: stdClass::$MAIN_OPTIMIZEFORTEXTBROWSER in /homepages/18/d319076814/htdocs/dolibarr/htdocs/core/lib/usergroups.lib.php on line 1047No   Default: No
-- | --
</div><br class="Apple-interchange-newline">

- under /product/admin/product.php

standard | Standard PDF template |   | Warning: Undefined property: stdClass::$PRODUCT_ADDON_PDF in /homepages/18/d319076814/htdocs/dolibarr/htdocs/product/admin/product.php on line 459 |   |  
-- | -- | -- | -- | -- | --

<br class="Apple-interchange-newline">

### Environment Version

16.0.1

### Environment OS

Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux

### Environment Web server

Apache

### Environment PHP

8.0.24

### Environment Database

10.5.17-MariaDB-1:10.5.17+maria~deb11-log

### Environment URL(s)

See message

### Expected and actual behavior

No warning messages.

**Comment by ksar-ksar** [comment]
Hello,

This is related to PHPV8, and Dolibarr V16 is compatible with PHP V8 but with a lot of such warnings.
Correction is forseen for V17

**Comment by manu-p** [comment]
Ok thanks @ksar-ksar 
Reverted back to PHP 7.4 and looking forward for v17.
