### ISSUE TITLE
Timesheet.js is spamming the console

### ISSUE THREAD

**Issue by loicsevrin** [Dolibarr/dolibarr#22637]
### Bug

Hello,

When entering time spent in /projet/activity/perday.php, my browser gets extremely slow. I displayed the console and there is a huge amount of useless and duplicate messages. I made a video of this behaviour : [video](https://piwio-my.sharepoint.com/:v:/g/personal/loic_sevrin_piwio_fr/EeDz2WABi5FKlviL821I35oBDAl1QtsRFgmGaPOsWO04Vg)

The bug is more visible with many projects and tasks (I have 57 tasks in 15 projects)

According to my test, the logs comes from timesheet.js (htdocs\core\js\timesheet.js), lines 195, 206, 219, 230. 

Every time I edit a time spent value, the updateTotal function is called 44 times (maybe firefox stopped at some point and it is more) from perday.php and then timesheet.js logs all fields on each call => thousands of logs. 

Could you trigger updateTotal less often (or remove these logs)?

I use Dolibarr 16.0.1 and Firefox 106.0
The bug also appears on Chrome 106.0

Regards 

### Environment Version

16.0.1

### Environment OS

Ubuntu 22.04.1 LTS VPS at Scaleway

### Environment Web server

Apache/2.4.52 (Ubuntu)

### Environment PHP

PHP 8.1.2

### Environment Database

10.6.7-MariaDB-2ubuntu1.1

### Environment URL(s)

https://dolibarr.piwio.fr

### Expected and actual behavior

When entering time spent in /projet/activity/perday.php, my browser gets extremely slow. I displayed the console and there is a huge amount of useless and duplicate messages. I made a video of this behaviour : [video](https://piwio-my.sharepoint.com/:v:/g/personal/loic_sevrin_piwio_fr/EeDz2WABi5FKlviL821I35oBDAl1QtsRFgmGaPOsWO04Vg). 

### Steps to reproduce the behavior

Go to /projet/activity/perday.php. Try to enter time spent in hours. Press tab to get to the minutes field, it takes several seconds to process.

The bug is more visible with many projects and tasks (I have 57 tasks in 15 projets)

### Attached files

![all logs](https://user-images.githubusercontent.com/1481809/196924985-c91dd045-8ae5-4fc9-a0aa-f89baddf922c.png)

![1 field edit produces more than 25 000 logs](https://user-images.githubusercontent.com/1481809/196925352-879f135c-9d86-4144-92ed-3197554cfe6c.png)

**Comment by hregis** [comment]
@loicsevrin 
the jquery script reacts on the class of the input and we load as many scripts as there are lines, so it necessarily launches as many lines as there are lines, it's nonsense! :-)
must be corrected.

**Comment by hregis** [comment]
@loicsevrin @eldy fixed with this PR https://github.com/Dolibarr/dolibarr/pull/22641

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
