### ISSUE TITLE
Bug:  GRH : modify number of holidays days not stored in the history

### ISSUE THREAD

**Issue by FredBl79** [Dolibarr/dolibarr#22630]
# Instructions
The history of holidays is not updated when you refresh NOTES after a first text too long error

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3
- **Database**:  8.0.30-0ubuntu0.20.04.2
- **URL(s)**: /holiday/view_log.php?mainmenu=hrm&leftmenu=holiday&action=request

## Steps to reproduce the behavior
add a very long text in NOTES, save the update of the number of days
Error message : text is too long
Modify the text in NOTES and save again
the number of days is saved but no line is added into the history of holidays

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
