### ISSUE TITLE
Manufacturing order cost incorrect -> 'manufacturing cost' is double BOM 'total cost

### ISSUE THREAD

**Issue by ajrstoke** [Dolibarr/dolibarr#22638]
### Bug

The price of a BOM double when a manufacturing order is created so when the product is consumed the PMP price 

BOM cost 93.93
![image](https://user-images.githubusercontent.com/107613575/196939563-bb5a7787-b1b7-4725-bbce-649aa80ad89d.png)

MO cost 187.86
![image](https://user-images.githubusercontent.com/107613575/196939664-9e038410-353b-4cf9-ba06-9012efab2e51.png)

### Environment Version

16.0.1

### Environment OS

Linux dolibarr 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64

### Environment Web server

Chrome

### Environment PHP

 7.4.28

### Environment Database

5.5.5-10.5.15-MariaDB-0+deb11u1

### Expected and actual behavior

Manufacturing order unit cost should be the same as the BOM cost

### Steps to reproduce the behavior

Raise a manufacturing order via the BOM tab. Check the unit price on production tab of the MO, it is double that on the BOM card.

**Comment by Hystepik** [comment]
Hello,
It works for me i cannot reproduce the behavior.

**Comment by Dounia-kazi** [comment]
I confirm it is a bug since 16.0.0
