### ISSUE TITLE
Expense report / Milage costs - incorrect UP after validation

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#22636]
### Bug

A user creates an expense report with milage costs lines as follows:
date of expense | type: milage costs | Vehicule category: 5cv | Description: blabla | Sales tax: 0 | U.P.: 0.603 | Qty: 20

For the 2 first lines, the calculation done by dolibarr is correct, i.e. 20 x 0.603 = 12.06€

By entering the 3rd line, although it is entered exactly like the two previous ones, the U.P. value is forced to another totally different value (5.22) at the time of validation of the line, which is then false and not correctable.

So the users need to enter new lines until the normal calculation reverts back to correct values and then remove incorrect lines...

### Environment Version

16.0.1

### Environment OS

Ubuntu server 20.04

### Environment Web server

Apache 2.4

### Environment PHP

7.4

### Environment Database

MySQL 8

### Environment URL(s)

expensereport/card.php

### Expected and actual behavior

Correct calculation as of the 1st line of the expense report for all new lines.

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
