### ISSUE TITLE
Bug: Dolibarr user rights not showing projects attached to third-party.

### ISSUE THREAD

**Issue by mbacklund** [Dolibarr/dolibarr#22640]
# Dolibarr user rights not showing projects attached to third-party.

# Bug
Dolibarr user rights not correct.

## Environment
- **Version**: 16.0.1
- **OS**: Windows Server 2019 Datacenter
- **Web server**: DoliwampMySQL
- **Database**: Doliwampapache

## Expected and actual behavior
Adding a dolibarr user the following rights should allow the user to see the projects attached to the third-party but it shows nothing:
Dolibarr user right management, I am adding rights to Projects or Leads:
Read projects and tasks (shared projects and projects of which I am a contact).
Create/modify projects (shared projects and projects of which I am a contact). Can also assign users to projects and tasks
Delete projects (shared projects and projects of which I am a contact)
Export projects

When I add the user these rights, it shows all projects, even the ones that are not attached to that specific third-party:
Read all projects and tasks (as well as the private projects for which I am not a contact)
Create/modify all projects and tasks (as well as the private projects for which I am not a contact)
Delete all projects and tasks (as well as the private projects I am not a contact)
Can enter time consumed, for me or my hierarchy, on assigned tasks (Timesheet)

## Steps to reproduce the behavior
Following the same steps when adding another user, same problem.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/36900083/196942646-4eeb2c8a-ad18-459c-bf76-2df626f28ffb.png)

**Comment by mbacklund** [comment]
No one has commented or reacted any way to this. Over a month already. What is this?

**Comment by ksar-ksar** [comment]
> What is this?

It's open source project, people are volunteers!

Is it still the case on V18 ?
