### ISSUE TITLE
Create  Bank account is forbidden 

### ISSUE THREAD

**Issue by philou15** [Dolibarr/dolibarr#22654]
### Bug

Hye
On Dolibarr 16.0.1 not possible to create a new Bank account
Dolibarr say do not authorisations. 
But I'am admin and full permissions. 

Tks

### Environment Version

16.0.1

### Environment OS

Ubuntu

**Comment by hregis** [comment]
@philou15 fixed with this PR https://github.com/Dolibarr/dolibarr/pull/22655

**Comment by philou15** [comment]
> @philou15 fixed with this PR #22655

Hye
Ok tks, i'm a newby on github, i dont see solution ? 
it is normal ? 
is is just the ticket for problem ?
tks

**Comment by hregis** [comment]
@philou15  you can wait for the next release or fix your dolibarr with this correction https://github.com/Dolibarr/dolibarr/pull/22655/files

**Comment by philou15** [comment]
ok it is the php file... 
i understand 
tks
