### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by joff13** [Dolibarr/dolibarr#22653]
### Bug

it_CH/main.lang file is badly translated/localization.
at every update  I've to edit
could someone update the file in repos?

### Attached files

[main.lang.txt](https://github.com/Dolibarr/dolibarr/files/9839308/main.lang.txt)

**Comment by ksar-ksar** [comment]
Hello,

All the translations must be done on https://www.transifex.com/dolibarr-association/dolibarr/
