### ISSUE TITLE
Cron Tab - Work Plans 

### ISSUE THREAD

**Issue by philou15** [Dolibarr/dolibarr#22660]
### Bug

Hye

Then i change the URL for script on Work Pland ( Travaux programmés) 
I need to change the command line for cron tab, 
i change, i put Registred and Dolibarr no apply the change 

*/5 * * * * /pathtoscript/scripts/cron/cron_run_jobs.php KEYSECURE admin > /home/philou15/www/documents/cron_run_jobs.php.log

I Woulg like to change to 
*/5 * * * * //home/philou15/www/scripts/cron/cron_run_jobs.php KEYSECURE admin > /home/philou15/www/documents/cron_run_jobs.php.log

And No registred
Dolibarr don't save the configuration

Tks

### Environment Version

16.0.1

### Environment OS

Ubuntu 20

### Environment PHP

7.4

**Comment by hregis** [comment]
@philou15 
try this instead : 

`*/5 * * * * php -f /home/philou15/www/scripts/cron/cron_run_jobs.php KEYSECURE admin > /home/philou15/www/documents/cron_run_jobs.php.log`

the cron must be executed by the Apache/Nginx user of your hosting (example: www-data)

this is not a bug of the application, for system setting questions it is best to ask your question on the Dolibarr forum.

https://www.dolibarr.org/forum.php

Thanks

**Comment by philou15** [comment]
Tks
But the probleme is not the configuration for now. 

Then i Change the script, i valide for registred, but **dolibarr don't save the configuration.** 

French
Quand je modifie le script, je fais enregister, dolibarr n'enregistre pas la modif. il reviens à la config par defaut.
Merci

**Comment by hregis** [comment]
@philou15 in the cron config in dolibarr this is just an example, you can not modify this field

**Comment by philou15** [comment]
je te repond en francais, je vois que tu est francais. 

Je ne comprend pas, il y a le champs dans dolibarr on en peux pas le modifier dans configuration du module ?

**Comment by hregis** [comment]
@philou15 c'est un champ certe, mais ce n'est qu'un exemple, cette configuration est à créer sur votre système Linux, dolibarr ne peut pas intervenir sur la configuration du serveur.

**Comment by philou15** [comment]
Ok, merci, donc je vais modifier mon fichier crontab dansubuntu.... 
c'etait pas clair ça.... 
merci
