### ISSUE TITLE
Prospect Status Cannot be Set to 'Do not contact' 

### ISSUE THREAD

**Issue by bubdev101** [Dolibarr/dolibarr#22669]
### Bug

In the third parties list it's not possible to set the prospect status to 'Do not contact' (at least since version 6). Instead it switches to 'Never contacted'.  
  
I've found the issue to be inside '\societe\class\societe.class.php', on line: 

`$sql .= ",fk_stcomm=".($this->stcomm_id > 0 ? $this->stcomm_id : "0");`

We must check for a prospect status ID ranging from '-1' to '3' to account for all possible status IDs, not only for a positive number. Changing the comparison to '>= -1' solved the problem for me. Otherwise, if the 'Do not contact' link ist clicked, always '0' (= 'Never contacted') will be returned.

I've reported this years ago in the English forum, but the post has been deleted shortly after. I guess it was the wrong place, so I'm giving it another try here.

### Environment Version

16.0.1 (and older)

### Environment OS

Linux

### Environment PHP

8 (and older)

### Environment Database

MySQL 5.7

### Environment URL(s)

/societe/list.php

### Steps to reproduce the behavior

Click on 'Do not contact'.

**Comment by hregis** [comment]
@livebuch 
yes you rights, i send a fixed https://github.com/Dolibarr/dolibarr/pull/22670
thank you

**Comment by ksar-ksar** [comment]
Hello,

Thanks for the report.

> I've reported this years ago in the English forum, but the post has been deleted shortly after. I guess it was the wrong place, so I'm giving it another try here.

Sorry if your post has been deleted. We usually delete only SPAM messages. Don't know exactly what happened....

**Comment by bubdev101** [comment]
No problem. Thanks for the reply.
