### ISSUE TITLE
Table 'dolibarr.llx_don' doesn't exist

### ISSUE THREAD

**Issue by vlad-dc** [Dolibarr/dolibarr#22677]
Hello,

I have the next error with Dolibarr: 16.0.0:

Menu manager: eldy_menu.php
Information for latest database access request error: Table 'dolibarr.llx_don' doesn't exist
And:
Information for latest database access request error: Table 'dolibarr.llx_ticket' doesn't exist

How can I fix this?

Regards.

**Comment by Hystepik** [comment]
Hello,
I cannot reproduce the error. Have you tried to make a migration of your Dolibarr by calling install/ in url
