### ISSUE TITLE
SQL Error message: DB_ERROR_1406 Data too long for column 'ext_payment_id' at row 1

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#22684]
### Bug

That's seems to be race conditions where we have that bug !

### Environment Version

15

### Environment OS

linux

### Environment Web server

apache

### Environment PHP

7.4

### Environment Database

mysql

**Comment by lamrani002** [comment]
can you please explain more the behavior for this Bug with precise the version of  environement and also the URL .

**Comment by SylvainLegrand** [comment]
May you give us a screenshot to understand the problem ?
