### ISSUE TITLE
row deleted in DB table

### ISSUE THREAD

**Issue by joff13** [Dolibarr/dolibarr#22686]
### Bug

`/accountancy/admin/productaccount.php?mainmenu=accountancy&leftmenu=accountancy_admin`

gives me 

`Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='`

I run

`/install/repair.php?force_utf8_on_tables=confirmed`

the procedure deletes some row in table

a least this rows are affected

`SELECT * FROM `xxx_accounting_account` WHERE `fk_pcg_version` LIKE  'PCG_SUISSE'`

### Environment Version

16.0.1

### Environment OS

Debian 4.9.210

### Environment Web server

Apache

### Environment PHP

7.4.32

### Environment Database

5.5.5-10.4.21-MariaDB

### Expected and actual behavior

expected to solve

`Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='`

with no data lost

actually

`Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='`

has been solved but with data lost

**Comment by SylvainLegrand** [comment]
We can't reproduce this behavior.
