### ISSUE TITLE
Taxes not displayed properly in purchase order

### ISSUE THREAD

**Issue by rejlafond** [Dolibarr/dolibarr#22683]
### Bug

When you edit qty of an item in a purchase order the tax amount (percentage) is displayed incorrectly.
It's also displayed incorrectly in the pdf.
GST should be 5% 
PST should be 7%
![dolibarr taxes](https://user-images.githubusercontent.com/116751167/198093191-c926a470-0028-4378-97fc-46763b633ba7.png)
![dolibarr taxes pdf](https://user-images.githubusercontent.com/116751167/198093349-946048b8-d8b0-431b-9005-e12d5d0dfecc.png)

### Environment Version

15 or 16

### Environment OS

Win64

### Environment Web server

Apache/2.4.41 

### Environment PHP

PHP/7.3.12

### Environment Database

10.4.10

### Expected and actual behavior

I expect it to display the actual tax percentage as setup in VAT Rates or Sales Tax Rates
I've tried changing the Tax type and it didn't make any difference

The tax total dollar amount is correct but it confuses vendors when they see random percentages.

### Steps to reproduce the behavior

When you edit the Qty of an item it displays random tax percentage.

**Comment by SylvainLegrand** [comment]
Fixed !
I can't reproduce this behavior.
