### ISSUE TITLE
VAT value not supported for imported products in proposals

### ISSUE THREAD

**Issue by marwenj** [Dolibarr/dolibarr#22713]
### Bug

After importing products via csv file , vat rate included, when i select that products in new proposals it doesn't take the vat rate (it shows it as 0%)

### Environment Version

16

### Environment OS

winnt

### Environment Web server

Apache/2.4.51 (Win64)

### Environment PHP

PHP/7.3.33

### Environment Database

MySql

**Comment by SylvainLegrand** [comment]
I can't reproduce this behavior
already fixed
