### ISSUE TITLE
Change default value for employee "1" to "0"

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#22715]
### Feature Request
Change value for 
Employee from "Yes" to "No" by default
/user/card.php?leftmenu=users&action=create

### Use case

It is rare to create employees but common to create internal contacts

**Comment by emheyarssi** [comment]
Why?

**Comment by lmag** [comment]
Because it is all the same much rarer to create employees than internal contacts

**Comment by aspangaro** [comment]
This prevents the user from complaining that I don't see this or that user in the salary module, however....
