### ISSUE TITLE
Module Bank - Add Bank Account: If Ref.Nr. is a number, than permission is denied - even for SuperAdmin [Docker only?]

### ISSUE THREAD

**Issue by rorar** [Dolibarr/dolibarr#22725]
### Bug

On a freshly deployed Dolibarr Docker Container:
If you add the Bank Module, create a Bank Account, add a number as Ref. Nr. like 1 (as it's mentioned in the YouTube instruction video) or 9000 and hit save, you'll get a permission denied screen.

**Quick-Fix Solution**
To fix that, you have to enter a letter beforehead like
B1 or B1000 (for bank)
C1 or C1000 (for cash)
...

Version Dolibarr: 16.0.1
Datenbase: MariaDB
Tested Docker Container:
https://hub.docker.com/r/upshift/dolibarr
https://hub.docker.com/r/tuxgasy/dolibarr

Have a look at this error log from another user:
https://forum.dolibarr.de/forum/t/nach-docker-installation-kein-recht-um-bankkonto-zu-erstellen/8275/2

### Environment Version

16.0.1

### Environment OS

Linux / Unraid server Pro, version 6.11.1

### Environment Web server

Apache/2.4.54 (Unix)

### Environment PHP

8.0.24

### Environment Database

10.9.3

### Expected and actual behavior

EB: If you enter a number, it just works.

AB: The process gets abortet and a permission denied screen appears - even for SuperAdmin.

### Steps to reproduce the behavior

add the Bank Module, create a Bank Account, add a number as Ref. Nr. like 1 (as it's mentioned in the YouTube instruction video) or 9000 and hit save, you'll get a permission denied screen.

**Comment by hregis** [comment]
@rorar it's already fixed and ready for Dolibarr 16.0.2
https://github.com/Dolibarr/dolibarr/pull/22655/files
