### ISSUE TITLE
Error al visualizar el PDF de Presupuesto de proveedor

### ISSUE THREAD

**Issue by ritchy125** [Dolibarr/dolibarr#22723]
### Bug

Al momento de visualizar o imprimir el PDF que representa al presupuesto del proveedor el PDF no muestra correctamente la información, 

[PDF.js viewer.pdf](https://github.com/Dolibarr/dolibarr/files/9905789/PDF.js.viewer.pdf)

### Environment Version

16.0

### Environment OS

Windows

### Environment Web server

Firefox

### Environment PHP

6

**Comment by grandoc** [comment]
It's a normal behavior. You just ask to have a price, so the price columns should be empty
