### ISSUE TITLE
Permisiion error when creating bank account

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#22726]
### Bug

When creating a new bank account, if you enter for Ref. only digits, you get an error "Access denied.
You try to access to a page, area or feature of a disabled module or without being in an authenticated session or that is not allowed to your user."

If you enter digits + letter or letters, no matter in what order or combination, everything is OK.

Also, if you update existing bank account and change the Ref. to digits only, everything is fine.

The bug exists only when creating new `record```

### Environment Version

16.0.1

### Environment OS

linux, windows

### Environment Web server

apache

### Environment PHP

7.3, 7.4

### Steps to reproduce the behavior

Try to create a new bank account and for "Ref." enter digits only, let's say 123.

**Comment by hregis** [comment]
@milenmk  it's already fixed and ready for Dolibarr 16.0.2
https://github.com/Dolibarr/dolibarr/pull/22655/files
