### ISSUE TITLE
The vendor invoices widget on the home page counts abandoned invoices as payable.

### ISSUE THREAD

**Issue by loutremaline** [Dolibarr/dolibarr#22721]
### Bug

I have a supplier invoice classified as abandoned because its amount was incorporated into a subsequent invoice. 
On the home page, the supplier (vendor) invoices widget tells me that there is still an invoice to pay which corresponds to the abandoned one (the amounts correspond).
When you click on this widget link, the list of supplier invoices to pay opens, without displaying an invoice. Which is normal since in my case all invoices have been paid or abandoned.

### Environment Version

16.0.0, 16.0.1

### Environment OS

Linux Debian

### Environment Web server

Nginx

### Environment PHP

8.0.13

### Environment Database

MariaDB 10.3.36

### Expected and actual behavior

The vendor invoices widget should show no bills to pay if they have all been paid or abandoned.

### Steps to reproduce the behavior

Create an vendor invoice and mark it as abandoned.

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by loutremaline** [comment]
Hello,
Yes, it's still the case on V18.0.1.

**Comment by romanschenk37** [comment]
Hello, I've noticed that the bug discussed here is still present in Dolibarr version 19.0.0. Any updates or would be greatly appreciated.

**Comment by bos4711** [comment]
@eldy This bug was solved by atm-maxine in #19404 but it was introduced later on and now it exists again in a fresh v19-install.

Did the fix get lost somewhere in upstream?
