### ISSUE TITLE
AGENDA_ADDACTIONFOREMAIL and AGENDA_ADDACTIONFORPHONE error in backtopage

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#22720]
### Bug

Error in backtopage

### Environment Version

15,16

### Environment OS

All

### Environment Web server

All

### Environment PHP

All

### Environment Database

All

### Expected and actual behavior

- [ ] Repair url backtopage (error 1)
- [ ] Change 'oui/non' by '0/1' in configuration (improvement 1)

### Steps to reproduce the behavior

Step 1 : error 1
![image](https://user-images.githubusercontent.com/3288514/199055656-0dc26b53-7add-4a2f-a163-b19bc420e3e0.png)

Step 2 : clic
![image](https://user-images.githubusercontent.com/3288514/199055433-89ff1293-9430-4fd8-a24b-016476acdf3a.png)

step 3 : improvement 1
![image](https://user-images.githubusercontent.com/3288514/199055304-2867af23-3a67-4df8-8c54-fe092998fc3f.png)

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
