### ISSUE TITLE
Add a mass action "Assign a user to projects" as a mass action on project list.

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#22735]
### Feature Request

Add a mass action "Assign a user" as a mass action on project list.

### Suggested implementation

You can follow example on "Assign a tag".
Except that we ask a user. Assignment of a user is a similar action than the one when we assign a user on the tab "Contacts" of a project.

**Comment by fboitel** [comment]
How should assignment to project tasks be managed? I guess we won't be asking for each selected project which tasks we want the user to be assigned to, so either we can automatically assign all tasks to the user or not assign any tasks to the user
