### ISSUE TITLE
Stocks are not reverted back to previous value when order is cancelled

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#22746]
### Bug

When the option to decrement stock is when the order is validated, stocks are not incremented back to their previous values for the related products when the order is cancelled.
So, it is needed to correct stocks, with the possible errors it means.

### Environment Version

16.0.1

### Environment OS

Debian 11

### Environment Web server

Apache 2.4

### Environment PHP

7.0

### Environment Database

MySQL 

### Expected and actual behavior

The order being cancelled, the stocks are not actually affected and should be returned to the current value plus the number of kits/products mentioned in this order.

Instead, the stocks are not recalculated and become false.

**Comment by hasse-basse** [comment]
I can confirm this issue! I've noted since long but haven't taken the time to write a note about it! I'm on the same setup as manu-p except for the DB where I use Maria.

**Comment by fappels** [comment]
Can't reproduce in current 16
![Liste des mouvements de stock 11-25-2022 10-39-14 PM](https://user-images.githubusercontent.com/4573808/204057738-5d8159f8-e649-414e-a215-9c687bb78eac.png)

**Comment by manu-p** [comment]
Sorry, but it is not when a bug is not reproduced by one person while it is noticed by several that it justifies its closure.
