### ISSUE TITLE
Bug: Not possible to create a bank account with number in ref field 

### ISSUE THREAD

**Issue by TechServiceConseil** [Dolibarr/dolibarr#22759]
Hi, 
It's no more possible to create a bank account with number in ref field. That return an error wich is permission denied. 

Accès refusé.
Vous essayez d'accéder à une page, région ou fonctionnalité d'un module désactivé, ou sans être dans une session authentifiée, ou avec un utilisateur non autorisé.

We can do it in V15 so i assume it's a bug in V16. 

Cordially   

## Environment
- **Version**: 16.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.32
- **Database**: MySQL or MariaDB 5.7.30-log
- **URL(s)**: /compta/bank/card.php?action=create&leftmenu=

**Comment by hregis** [comment]
@TechServiceConseil it's already fixed and ready for 16.0.2

**Comment by TechServiceConseil** [comment]
@hregis Hi, 
That was a quick response :)
Thank you

By the way, there are regular meetings about the devellopement wich are accesible for the community ?
