### ISSUE TITLE
[API]: can't update a bank account for a third party

### ISSUE THREAD

**Issue by trebel68** [Dolibarr/dolibarr#22751]
### Bug

When I use these API operation: PUT /thirdparties/{id}/bankaccounts/{bankaccount_id}, I have this error:

<b>Type gestionnaire de base de donn&eacute;es:</b> mysqli<br>
<b>Requ&ecirc;te dernier acc&egrave;s en base en erreur:</b> SELECT rowid, type, fk_soc, bank, number, code_banque, code_guichet, cle_rib, bic, iban_prefix as iban, domiciliation, proprio, owner_address, default_rib, label, datec, tms as datem, rum, frstrecur, date_rum FROM llx_societe_rib WHERE rowid = 1544 WHERE fk_soc  = 8440<br>
<b>Code retour dernier acc&egrave;s en base en erreur:</b> DB_ERROR_SYNTAX<br>

### Environment Version

13.0.4

### Environment OS

Linux dolibarr 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02: 23: 37 UTC 2022 x86_64

### Environment Web server

Apache

### Environment PHP

7.4.3

### Environment URL(s)

API: PUT /thirdparties/{id}/bankaccounts/{bankaccount_id}

### Expected and actual behavior

**Actual behavior:**
The method `updateCompanyBankAccount` from `Thirdparties` (into htdocs/societe/class/api_thirdparties.class.php) call the `fetch` method from `CompanyBankAccount` (into /htdocs/societe/class/companybankaccount.class.php)
`$account->fetch($bankaccount_id, $id, -1, ''); # row 1285`
And the code of this method doesn't manage very well (double WHERE) the two valid ids for building the SQL query (rows 243-247)
```
if ($id) {
	$sql .= " WHERE rowid = ".((int) $id);
}
if ($socid) {
	$sql .= " WHERE fk_soc  = ".((int) $socid);
```

**Comment by lvessiller-opendsi** [comment]
It works in the latest version of Dolibarr 14.0 and the code for method "$account->fetch($bankaccount_id, $id, -1, ''); # row 1285" was fixed.
