### ISSUE TITLE
Delete product using API Rest

### ISSUE THREAD

**Issue by snadal86** [Dolibarr/dolibarr#22766]
### Bug

I'm trying to delete some products using the API Rest and I receive error 403 Forbidden.

### Environment Version
Dolibarr 15

### Environment OS
Linux (OVH)

### Environment Web server
Linux (OVH)

### Environment PHP
7.3

### Environment Database
MySQL

### Expected and actual behavior

- Curl curl -X DELETE --header 'Accept: text/html' --header 'DOLAPIKEY: mykey' 'http://mydomain/api/index.php/products/66830'
- Request URI: http://mydomain/api/index.php/products/66830 and product with ID 66830 should be deleted

I get an error 403 Forbidden access and product is not deleted. I don't understand why.

Response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>

**Comment by rycks** [comment]
Hello, error 403 : it seems to be unauthorized access ... please check if your user can delete that object in dolibarr backend.
i don't have that problem here ... but server returns http status 200 ... but product is not deleted because that product is used into an invoice

**Comment by rycks** [comment]
HTTP status should return something else than "200" in case of "delete is impossible due to foreign keys references" like explained here https://stackoverflow.com/questions/62528499/correct-http-response-code-for-delete-api-if-resource-is-in-use-and-cannot-be-de
