### ISSUE TITLE
Issue with Takepos product research feature

### ISSUE THREAD

**Issue by Earfalass** [Dolibarr/dolibarr#22773]
### Bug

Hi everyone, 
I am using the latest version of Dolibarr, with the dolicloud platform. I have installed the takepos module. On the takepos module, when I try to search a product on the search bar, nothing appears. I enter a letter, a word but nothing is listed. I press enter but no product appears.
However my product are listed on the category window below, this means my products are recognised by takepos. But the search feature doesn't work at all.
Would you have any idea how to make it working ?
Thank you very much for your help,
Vincent

### Environment Version

V16

### Environment Web server

Dolicloud

### Expected and actual behavior

I expect the search bar to effectively show products linked to the searched terms.

### Steps to reproduce the behavior

Go on the takepos module and search a product using the search bar.

**Comment by Hystepik** [comment]
It seems to be fixed in the last v16 version so I close the issue.
Feel free to reopen if not.
