### ISSUE TITLE
email connector does not set all used db fields

### ISSUE THREAD

**Issue by fds2610** [Dolibarr/dolibarr#22770]
### Bug

email collector does not set llx_projet.fk_statut to requested value.

### Environment Version

16.0.1

### Environment OS

debian

### Environment Web server

11.5

### Environment PHP

7.4

### Environment Database

mariadb

### Environment URL(s)

-

### Expected and actual behavior

in Dolibarr 16.0.1 on a newly setup server I need to configure the email connector to create new leads when a mail arrives in an IMAP folder. To be able to start my workflow in DoliDroid I want to create the Leads in status "approved" what is indicated as soon as field "fk_statut" in table "llx_projet" is set to 1 instead of 0. 0 means draft.

When i modify the collector action string to: tmp_from=EXTRACT:HEADER:^From:(.*);socid=SETIFEMPTY:NULL;fk_statut=SET:1;usage_opportunity=SET:1;description=EXTRACT:BODY:(.*);title=SET:Lead or message from __tmp_from__ received by email

the necessary field fk_statut is not set to 1 as requested. Has anyone an idea why the field is not set as requested or in which php file can I modify my needs to make it happen?

### Steps to reproduce the behavior

activate email-collector and add the string fk_statut=SET:1; to the default action-string

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
