### ISSUE TITLE
Email Collector named attachments  as (1).

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#22775]
### Bug

Sometimes email collector names the attachments as (1)., (2). etc...
A name like (1). cannot be used on something ...

### Environment Version

16.0.1

### Environment OS

All Linux versions

### Environment Web server

apache

### Environment PHP

7.4.30

### Environment Database

5.5.68-MariaDB

### Environment URL(s)

/scripts/cron/cron_run_jobs.php

### Expected and actual behavior

It should name the attachments according the name of the attachment....

### Steps to reproduce the behavior

Execute the email collector

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
