### ISSUE TITLE
Email Collector uses Server Root (/) As Temporary folder

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#22774]
### Bug

After upgrading to the 16.0.1 version of dolibarr when email collector executes and checks a email account for new emails to insert as tickets… i am getting in the Root Linux Server the attachments that the emails has…

### Environment Version

16.0.1

### Environment OS

All Linux versions

### Environment Web server

apache

### Environment PHP

7.4.30

### Environment Database

5.5.68-MariaDB 

### Environment URL(s)

/scripts/cron/cron_run_jobs.php

### Expected and actual behavior

Nothing to leave on the Linux Root Server

### Steps to reproduce the behavior

Just run the email collector...

**Comment by ksar-ksar** [comment]
Link to https://www.dolibarr.org/forum/t/ticket-attachments-on-server-root/22994

But I'm still not sure to understand, you have the attachments of the email on the root folder ?

**Comment by VaderD** [comment]
Hello there,

Exactly .. I have the attachments on the root folder and on the ticket folder also .... 
I have them in both places...

It is like it uses the Root Folder for temporary issue and after it ends the process it never deletes them ....but i should use the Root Folder as temp in any way !

**Comment by VaderD** [comment]
Here is my Root Folder after executing the calling the email collector through a cron job.
I hope this attached file clears out what i mean 

[RootFolder.txt](https://github.com/Dolibarr/dolibarr/files/9951967/RootFolder.txt)

The command i run from contab

php /var/www/html/dolibarr-3.6.0/scripts/cron/cron_run_jobs.php 5g8da3d573sd12f3d12g3s21dghhasd1dghjq1vf issues > /var/www/html/dolibarr-3.6.0/scripts/cron/cron_run_jobs.log

**Comment by ksar-ksar** [comment]
What user do you use to run the crontab ? root ?

**Comment by VaderD** [comment]
Yes As root

**Comment by VaderD** [comment]
When i run the same command with some other user tickets are inserted but i get the following warnings in the log file.
Because i think it tried to open the file in the root but it does not have any permission....

Here is the log 

***** cron_run_jobs.php (16.0.1) pid=5086 ***** userlogin=doliuser ***** 2022-11-08T17:35:02Z *****
cron_run_jobs.php cronjobid: 44 priority=50 entity=0 label=PurgeDeleteTemporaryFilesShort - not qualified
cron_run_jobs.php cronjobid: 42 priority=50 entity=1 label=Email collector - qualifiedPHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
PHP Warning:  file_put_contents(/ (1).): failed to open stream: Permission denied in /var/www/html/dolibarr-3.6.0/htdocs/emailcollector/class/emailcollector.class.php on line 2651
 - run_jobs OK result = 1 - reprogrammed
cron_run_jobs.php cronjobid: 43 priority=50 entity=1 label=HolidayBalanceMonthlyUpdate - not qualified

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by VaderD** [comment]
Hellot here,

Yes it is !
