### ISSUE TITLE
After upgrade (15.x -> 16.x), amount of non-paid Vendor invoices is incorrectly shown in widget

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#22787]
This was not a problem in 15.x, but immediately after the upgrade to 16.0.1 the widget shows "82 unpaid". When clicking this number in the widget, the Vendor invoice page is shown with only 4 (which is the correct value) unpaid invoices.

![doli1_Untitled](https://user-images.githubusercontent.com/11036018/200562578-975bafc7-e8f0-4e1b-9899-bcd163cf8d39.png)
![doli2_Untitled](https://user-images.githubusercontent.com/11036018/200562583-06fb5a7e-21c3-41f1-ae8c-a37ef2cd0c79.png)

**Comment by ksar-ksar** [comment]
Duplicated of #22721
