### ISSUE TITLE
Third-party information visibility for Supirvisor

### ISSUE THREAD

**Issue by artemChernitsov** [Dolibarr/dolibarr#22798]
### Feature Request

Right now to see Third party information and have permission to all related items need to add Member to Sales Representatives. 
Maybe should give the same permissions to supervisors if 'employee' has permission to see all related items of third party?

**Comment by LukeNK** [comment]
I highly support this feature, and I am trying to add this by manually fixing the code. However, I got stuck because I didn't know how to add new permissions (and PHP is pretty new to me). I will definitely get back on this.
