### ISSUE TITLE
Massaction to assign a sale representatives on a selection of thirdparties has non-intuitive behavior

### ISSUE THREAD

**Issue by artemChernitsov** [Dolibarr/dolibarr#22797]
### Bug

Hello dear community,
regarding this commit https://github.com/Dolibarr/dolibarr/commit/c4a96957aff5cdc3a2f671831f414b0dfe5e9be9 Dolibarr received good function, but it non-intuitive. 
I want to add new sale representative to third parties, but all my old sales representatives are gone.
Maybe system should add new one to existing sales representatives team, instead of replace all team and add new?

**Comment by lvessiller-opendsi** [comment]
Sorry I don't understand, can you provide a screenshot please ?

**Comment by artemChernitsov** [comment]
Actual result:
For example, if you have two Sales Representatives in third party (in my installation I renamed it to Team Members) 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/18346730/214054675-634fe189-e23d-4612-ab0f-251ec19dd090.png">
and you will try to assign to sales representative through mass action in list 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/18346730/214055040-6e1b6da4-5cc8-4794-8b5d-5edb68d20bd2.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/18346730/214055108-1dff22ba-6679-4089-9718-08ea269d0f75.png">

then other old Sales Representatives are gone 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/18346730/214055461-cd78d2c3-8420-4899-96d1-0352a2706afe.png">


Expected result:
Add new Sales Representative to current list of Sales Representatives.

**Comment by lvessiller-opendsi** [comment]
This is the expected behavior.

What you ask is an evolution of the behavior. This may be conditioned to an option.

This is a feature request.
