### ISSUE TITLE
intervention sheet

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#22811]
### Bug

Good evening
I have this lag when creating an intervention sheet on the second page

![image](https://user-images.githubusercontent.com/26550824/201076239-20f487a6-ff50-4640-b161-1475ff3197ed.png)

### Environment Version

Dolibar 16.0.1

### Environment OS

Linux shared hosting

### Environment Web server

LAMP

### Environment PHP

7.4

### Environment Database

5.6

**Comment by ns-info90** [comment]
Which template do you use for the PDF edition?

**Comment by DATUC** [comment]
Hi @ns-info90 

> Which template do you use for the PDF edition?

<html>
<body>


soleil | Standard PDF template
-- | --



</body>
</html>

**Comment by ns-info90** [comment]
I have just done a test and I do not encounter your problem
Do you have any external modules installed?
![image](https://user-images.githubusercontent.com/45969285/201347392-e308bcf3-1a00-4ef3-901d-aad30887a3b1.png)

**Comment by DATUC** [comment]
> I have just done a test and I do not encounter your problem Do you have any external modules installed? ![image](https://user-images.githubusercontent.com/45969285/201347392-e308bcf3-1a00-4ef3-901d-aad30887a3b1.png)

Yes i have some external modules wil desactivate and do the test to confirm

**Comment by lmag** [comment]
It is ok for me to
