### ISSUE TITLE
ldap to dolibarr sync throws error if user already exists

### ISSUE THREAD

**Issue by maxkreg** [Dolibarr/dolibarr#22827]
### Bug

Dolibarr is installed via Cloudron. Their ldap sync script calls [sync_users_ldap2dolibarr.php](https://github.com/Dolibarr/dolibarr/blob/develop/scripts/user/sync_users_ldap2dolibarr.php).

In its first run, sync works fine. If I add another user to the LDAP server, the script remarks that the users synced before exist, that the new user does not and that it will create it (all good so far), and then it stalls with an error, revoking the newly synced user (see below). Is there anything I am doing wrong or is this expected bahaviour? Many thanks!

> root@c8d9a4b7-94bc-4850-ade5-xxxxxxxxxxx:~# /usr/sbin/sync-users.sh
==> Syncing LDAP users into dolibarr
***** sync_users_ldap2dolibarr.php (16.0.1) pid=1048 *****
Mails sending disabled (useless in batch mode)
----- Synchronize all records from LDAP database:
host=172.18.0.1
port=3002
login=cn=c8d9a4b7-94bc-4850-xxxxxxxxxxxxxxxx,ou=apps,dc=cloudron
pass=********************************************************************************************************************************
DN to extract=ou=users,dc=cloudron
Filter=(&(objectclass=user))
----- To Dolibarr database:
type=mysqli
host=mysql
port=3306
login=ee86bxxxxxxxxxxx
database=ee86bfxxxxxxxxxxxx
----- Options:
commitiferror=0
excludeuser=
Mapped LDAP fields=cn,sn,givenName,username,telephonenumber,facsimiletelephonenumber,mobile,mail
UserCreate # Mxxxxxxxxx Kxxxxxxxx: login=m.xxxxxxxxxxxx, fullname=Mxxxxxxx Kxxxxxxxxxxx --> -6 Benutzername m.kxxxxxxxxxx existiert bereits.
UserCreate # test: login=test, fullname=test --> -6 Benutzername test existiert bereits.
UserCreate # testi: login=test2, fullname=testi --> Created user id=29 login=test2
Einige Fehler wurden gefunden. Änderungen wurden rückgängig gemacht.

### Environment Version

16.0.1

### Environment PHP

7.4.3

### Environment Database

MySQL or MariaDB 8.0.30-0ubuntu0.20.04.2

**Comment by hregis** [comment]
@maxkreg the script is to run only once, then when add a new dolibarr user you can associate it with an ldap user

**Comment by hregis** [comment]
@maxkreg can you check (llx_const table) if 

`LDAP_KEY_USERS = LDAP_FIELD_SID`
or
`LDAP_KEY_USERS = LDAP_FIELD_LOGIN
`

if `LDAP_KEY_USERS = LDAP_FIELD_SID` can you check if the field "ldap_sid" has a value in llx_user table ?

**Comment by maxkreg** [comment]
> @maxkreg the script is to run only once, then when add a new dolibarr user you can associate it with an ldap user

okay, so it is a transmission, not a synchronization ;)


> mysql> SELECT * FROM dolibarr_const WHERE name = 'LDAP_FIELD_LOGIN';
+-------+------------------+--------+----------+--------+---------+------+---------------------+
| rowid | name             | entity | value    | type   | visible | note | tms                 |
+-------+------------------+--------+----------+--------+---------+------+---------------------+
|   537 | LDAP_FIELD_LOGIN |      1 | username | chaine |       1 | NULL | 2022-11-11 12:07:39 |
+-------+------------------+--------+----------+--------+---------+------+---------------------+


`LDAP_KEY_USERS` and `LDAP_FIELD_SID` return an empty set. 
`ldap_sid` is empty (not `NULL`) for all existing users.

**Comment by hregis** [comment]
@maxkreg what is the finality ? dolibarr -> ldap or ldap ->dolibarr ?

**Comment by hregis** [comment]
@maxkreg have you activated and configured the ldap module in Dolibarr?
it must be configured before using the ldap user import script in Dolibarr !

**Comment by maxkreg** [comment]
I am trying to sync ldap -> dolibarr (using [sync_users_ldap2dolibarr.php](https://github.com/Dolibarr/dolibarr/blob/develop/scripts/user/sync_users_ldap2dolibarr.php)).

LDAP is configured, proven by the fact I can see entries from my LDAP server in Dolibarr´s user creation panel:
![grafik](https://user-images.githubusercontent.com/71139234/201370274-ede9641a-e291-4869-baf1-edf6b47a5ede.png)

**Comment by hregis** [comment]
@maxkreg it's very dificult to see a problem without to see the context... can you send me a private mail to see with remote maintenance please ?

**Comment by maxkreg** [comment]
I can´t find a way to contact you, please shoot me an email (see profile). I will be back in office on monday. Thank you!

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
