### ISSUE TITLE
Information of the total quantity of items in Invoice

### ISSUE THREAD

**Issue by DenysLP** [Dolibarr/dolibarr#22828]
### Feature Request

I would like to have information on the total quantity of items on an invoice as is already done in the price

### Use case

![image](https://user-images.githubusercontent.com/15112491/201425246-619c387f-2eb8-4b38-9bf3-f992ca9c1db5.png)

**Comment by ns-info90** [comment]
Quantities are managed on the delivery note and not on the invoice
