### ISSUE TITLE
addMoreActionsButtons without modifying core file. ticket/card.php

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#22834]
### Feature Request

I'm trying to add a custom action to create a child ticket that should be completed before the parent ticket.
The problem is that the **addMoreActionsButtons** is inside a:
```
elseif (empty($action) || $action == 'view' || $action == 'addlink' || $action == 'dellink' || $action == 'presend' || $action == 'presend_addmessage' || $action == 'close' || $action == 'delete' || $action == 'editcustomer' || $action == 'progression' || $action == 'reopen'
	|| $action == 'editsubject' || $action == 'edit_extras' || $action == 'update_extras' || $action == 'edit_extrafields' || $action == 'set_extrafields' || $action == 'classify' || $action == 'sel_contract' || $action == 'edit_message_init' || $action == 'set_status' || $action == 'dellink')
```
So I get the following case:

- $action == 'view'
- **addMoreActionsButtons** hook is executed and I show a button "Create Subticket"
- Click the new button
- $action == 'create_subticket'
- Now we don't enter the `elseif` because action is not on that big condition, we dont reach **addMoreActionsButtons** so I can't show the confirmation form

### Use case

Want to add new actions to `/ticket/card.php`

### Suggested implementation

Move the calls to `$hookmanager->executeHooks` out of conditions and let the developer decide when to show/print/execute whatever based on currentcontext and action.

Also make sure all calls to hookmanager have the following `print $hookmanager->resPrint`

**Comment by milenmk** [comment]
It is missing "$hookmanager->executeHooks('formConfirm', ...)". If you want to code it yourself, you can look at order card ot invoice card, and then can add "public function formConfirm($parameters, &$object, &$action, $hookmanager){ ... }" to your actions file.

**Comment by Daviid-P** [comment]
> It is missing "$hookmanager->executeHooks('formConfirm', ...)". If you want to code it yourself, you can look at order card ot invoice card, and then can add "public function formConfirm($parameters, &$object, &$action, $hookmanager){ ... }" to your actions file.

Seems to work fine, thanks!
