### ISSUE TITLE
Wrong $action on formObjectOptions hook for html.formticket.class.php

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#22837]
### Bug

On `htdocs\core\class\html.formticket.class.php` there is this constructor
```php
public function __construct($db)
{
  $this->db = $db;
  
  $this->action = 'add';
  
  $this->withcompany = 1;
  $this->withfromsocid = 0;
  $this->withfromcontactid = 0;
  //$this->withthreadid=0;
  //$this->withtitletopic='';
  $this->withnotifytiersatcreate = 0;
  $this->withusercreate = 1;
  $this->withcreatereadonly = 1;
  $this->withemail = 0;
  $this->withref = 0;
  $this->withextrafields = 0; // Show extrafields or not
  //$this->withtopicreadonly=0;
}
```

`$this->action` is used to create the form but it is also passed on to `$hookmanager->executeHooks('formObjectOptions', $parameters, $ticketstat, $this->action);` on line 426 (line 639 on latest v17)

Like this, in our own formObjectOptions function we end up with `$action == "add"` even if we're still at the creation form and should have `$action == "create"`

I'm not sure if this is a bug or it is supposed to be this way.

### Environment Version

13 but it's the same on latest

**Comment by lvessiller-opendsi** [comment]
Fixed in #23018
