### ISSUE TITLE
Supplier name in Cost Price on Propsals, Orders, Invoices

### ISSUE THREAD

**Issue by petper** [Dolibarr/dolibarr#22831]
### Feature Request

When using Cost Price in Proposals, Orders, Invoices there appears several rows when same product have multiple suppliers.
This might cause a confusion of what supplier have that price.
<img width="548" alt="Commercial proposal CostPrice" src="https://user-images.githubusercontent.com/23406198/201542653-aa21a555-a472-4355-90ab-6458b0ebbed1.png">

### Use case

When there is a prefered supplier, but several suppliers have been added into the products buying price, it causes confusion of what price is the buying price.

### Suggested implementation

For ease of use, it should have "VendorName: xxxx (currency)/unit" or anything similar.

**Comment by petper** [comment]
I'm not good enough on the PR.
Found that the data already is beeing used.

Attached file contains diff
[objectline_create.tpl.diff.txt](https://github.com/Dolibarr/dolibarr/files/9998149/objectline_create.tpl.diff.txt)

**Comment by hregis** [comment]
@petper maybe the better is to show when the mouse is is above a price ?
`
options += '<option value="'+this.id+'" price="'+this.price+'" title="'+this.title+'">'+this.label+'</option>';`

**Comment by petper** [comment]
> @petper maybe the better is to show when the mouse is is above a price ?
> ` options += '<option value="'+this.id+'" price="'+this.price+'" title="'+this.title+'">'+this.label+'</option>';`

Actually I dont know where you might see that popup, but it doesnt work for me (tried in both Chrome and Safari)
Wouldnt it be better to have it show directly which supplier you want to base the price from? See attached picture
<img width="306" alt="image" src="https://user-images.githubusercontent.com/23406198/202006128-5cb21315-bbb6-48f5-b69e-a413a11c0c16.png">

**Comment by hregis** [comment]
@petper if the supplier name and ref is big you have a big select!

**Comment by hregis** [comment]
@petper with my fix try to open the select and move your mouse and stay under a price
