### ISSUE TITLE
After upgrade to 16.0.1 the Proposal box can no longer be seen on the main page

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#22833]
### Bug

On the main page there has always been the Proposals box, where amount of proposals need signing, billing etc could be seen. This box has been there up to and including v15, but when we upgraded to v16 last week the box disappeared and won't re-appear even if we disable + enable the Proposals module.

![Untitled](https://user-images.githubusercontent.com/11036018/201609106-3ef19222-9638-40d3-9171-7de8fd5b1009.png)

### Environment Version

16.0.1

### Environment PHP

8

**Comment by sonikf** [comment]
It's fixed in 16.0.2

**Comment by bos4711** [comment]
Fixed by #22602
