### ISSUE TITLE
Impossible to put notes on product

### ISSUE THREAD

**Issue by ns-info90** [Dolibarr/dolibarr#22846]
### Bug

Unable to put notes on product 
the edit button (pen) is missing

### Environment Version

16.0.2

### Environment OS

Linux

### Environment PHP

7.4

### Environment Database

MariaDB

### Environment URL(s)

/product/note.php?id=

**Comment by JoAnMaFe** [comment]
Still happening in 16.03 with W10

**Comment by inoveaconseil** [comment]
We can't reproduce in 16.0.3

**Comment by ns-info90** [comment]
I reproduced the problem in 16.0.3

**Comment by ns-info90** [comment]
The correction was made in the version present in Github but not in the last version delivered in 16.0.3 
Can you release a 16.0.4?
Thanks
