### ISSUE TITLE
Error duplicate import Vendor prices

### ISSUE THREAD

**Issue by faysu** [Dolibarr/dolibarr#22853]
### Bug

When we want to update purchase prices from an excel "Vendor prices (of products or services)", it tells us that the entry is duplicated, it tells us that the entry is duplicated.

With these times of inflation, it is essential to be able to update them

### Environment Version

15.0.3

### Environment OS

Ubuntu 22.04

### Environment Web server

Apache

### Environment PHP

php 7.3

### Expected and actual behavior

Being able to update the price from an excel called "Vendor prices (of products or services)", even if the product is already in Dolibarr

**Comment by ksar-ksar** [comment]
Hello,

Most probably you are not using import correctly because it's supposed to work.
What is your import file ?
