### ISSUE TITLE
Phone numbers in Dolibarr

### ISSUE THREAD

**Issue by karozans** [Dolibarr/dolibarr#22891]
### Feature Request

It would be nice if Dolibarr was able to store phone numbers as just numeric values and then just display the phone number in a nice format that is based upon the region of the user and/or thirdparty.

### Use case

I understand that phone numbers can be very difficult to handle given the fact that so many different ways of storing phone numbers, but when you want to do a database search this becomes a problem unless MySQL 8 is supported where you can do regular expressions.  But even then, it can be slow to perform a search.

### Suggested implementation

It would be nice to store the phone number as a pure numeric value.  Then have an option to display the phone number in a formatted way on the php pages.

**Comment by priojk** [comment]
While I understand the reasoning for your request, I am afraid that phone numbers are not always only numeric. Just thinking about the inital +sign for the standardized format including the country code like +49 331 123456.

**Comment by edupulpillo** [comment]
Also sometimes have the "extension" number of 3 digits, to select the person you need to contact after the telephone be pickup. Specially useful to do a pause and send the tones to select the extension.

**Comment by akliewer99** [comment]
Count me in too! I love this feature
