### ISSUE TITLE
Editing field in lists and not just in Cards

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#22898]
### Feature Request

I would like to be able to edit fields in the listings and not just in the Cards

### Use case

When placing transportorders with Schenker or someone else, I will a little later recive an order confirmation and a tracking number attached to that transport order. I have created some special fields for that, and for many other purposes, and I would like to be able to edit those fields already in the listing so I don't have to open up the Card to do this.

It might seem as a small thing to do to open up the card, but if there are 5, 10 or more orders to handle, it is time consuming to open up the cards.
![1a](https://user-images.githubusercontent.com/24247236/202720673-d6e07580-e29c-4ee0-9e1a-ea8d8962e298.jpg)

**Comment by milenmk** [comment]
It is possible, via a third-party module, to add additional mass action. I.e. mark the checkboxes at the end for all rows you need and then choose the mass action from the top list. However, this needs some coding. 

As you can imagine, not everything can or should be included in the "base product", not referring only to Dolibarr and having an edit button for each column and row will be, to my opinion, very messy and ugly. :)

**Comment by hasse-basse** [comment]
If you look at the image I have added above, in the column Réf. Command you will on the second line find a field with the text "kerroumi-3405947". My idea was that just by clicking on the field it opens up for editing. No buttons, nothing, just clicking on the field, and it would close and save by clicking somewhere outside the field.

In the below picture there are pencil-styled buttons telling us to click on them to edit the field, but shouldn't it be possible to make an OnClick event on the field itself and like that avoid all ugly buttons in the listings?

![edit-01](https://user-images.githubusercontent.com/24247236/202773171-3a4774a0-46c7-4407-8ad3-c44895fa2871.jpg)

In Drupal, in the module Views, it is possible to create any kind of listings, of any content. It is then  possible to use the fuction Editable fields as an alternative to "normal" fields. When doing so, the fields choosen to be editable, will then in the listing be open to edit. To save, a save button, valid for the full list, must be clicked.

**Comment by hasse-basse** [comment]
The fuction exist as a module so I close the request. Below the link to the module

Edition rapide produits services
https://www.dolistore.com/fr/modules/1258-Edition-rapide-produits-services.html
