### ISSUE TITLE
Chek integrity fail on new install 16.0.2

### ISSUE THREAD

**Issue by oldu9412** [Dolibarr/dolibarr#22914]
### Bug

On new installation, check integrity fails...
![image](https://user-images.githubusercontent.com/10073396/203169663-6da5660a-de6f-4923-bec1-03f420e4a4a0.png)

3 missing files in /include
1594 missing files in /theme/common/fontawesome-5/svgs/

### Environment Version

16.0.2

### Environment Web server

Apache

### Environment PHP

7.4.29

### Attached files

![image](https://user-images.githubusercontent.com/10073396/203170283-3f8539f6-a712-4922-805c-f53f4b437b53.png)

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
