### ISSUE TITLE
No permissions to add time consumed to project after upgrade from 14->16

### ISSUE THREAD

**Issue by gregor-tusar** [Dolibarr/dolibarr#22910]
### Bug

I upgraded Dolibarr vesrion 14 to 16 via Softaculus script.
The DB migrations went well from 14->15 and from 15->16.
After trying to add some time spent to a project, I get a disabled button and a message "You don't have permission for this action".
I can't find any permissions that would be logically connected to this issue.
I am the only user and administrator.

### Environment Version

16.0.2

### Environment OS

cPanel hosted - Linux

### Environment Web server

LiteSpeed

### Environment PHP

7.4.33

### Environment Database

MySQL 

### Environment URL(s)

private

### Expected and actual behavior

Click on a button to add Time consumed is available

**Comment by ns-info90** [comment]
Is your project validated before the task time is entered ?

**Comment by gregor-tusar** [comment]
It actually is, because I already added some spent time records to this project before the system update.
The warning is in Slovene language, but it says "You don't have the permission for this activity".
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/18527163/203273855-68a7f1bc-d09f-44e8-938b-62fc5a0bbb8f.png">

I tried:
- changing the project and saving it
- adding a new task
- editing existing task
- assigning me to a task

but I can't add new entries in time-consumed tab.

**Comment by JoAnMaFe** [comment]
Solution Projects permissions #22504

**Comment by gtusar** [comment]
Hi,
I added all permissions, but still can't add any time consumed to project.
![image](https://user-images.githubusercontent.com/18527163/204124574-9a6465f0-97ce-4c8c-81fc-de8e403ad614.png)
![image](https://user-images.githubusercontent.com/18527163/204124591-a34579b9-37b6-4020-bd3d-ae69f745a767.png)

**Comment by gregor-tusar** [comment]
This solved my issue.
Thank you.
