### ISSUE TITLE
Can't change user or member details when connected

### ISSUE THREAD

**Issue by 1337gut** [Dolibarr/dolibarr#22918]
When changing any user's or member's details (like adding a name or something) I only get the message "_Die eingegebene Kundennummer ist unzulässig_" ("The entered customer number is invalid").
I get this error only if the user is connected to a member and vice versa. If it is only a member without a user/login (and vice versa) I don't get this error.

Tested with dolibarr 16.0.1 and 16.0.2.

Messages in logfile:
`WARNING Societe::Update fails verify ErrorBadCustomerCodeSyntax`
`ERR          Adherent::update`

**Comment by 1337gut** [comment]
Okay, I think I've found the root of this problem: If the member is connected to a client whis has a customer number (i.e. from import) that number will be marked as incorrect. After reimporting the clients without customer numbers, the error doesn't appear.
How does a customer number for a client to look like to not be marked as incorrect?

**Comment by priojk** [comment]
You can define the structure of the customer and supplier numbers under Start -> Settings -> Modules and there in the third parties module (Geschäftspartner). If the system finds a customer number, which does not follow this structure, it issues a warning.
If you import customer numbers, they may be arbitrary. If you import without customer numbers, the system will assign new ones according to the spec.

**Comment by 1337gut** [comment]
Good to know, thank you!
