### ISSUE TITLE
Redirect after add a new product not working -> Warning headers already sent by...

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#22916]
### Bug

After click the safe button at a new product the browser show the following Error:
![image](https://user-images.githubusercontent.com/78662388/203261599-6a1a89ad-8649-426a-a0d4-18071c5d6c82.png)

P.S. I don´t know if its a problem of my php update on v8.1, please give me a feedback.

### Environment Version

16.0 (Git Clone)

### Environment OS

Windows 10

### Environment Web server

xampp

### Environment PHP

PHP 8.1.10

### Environment Database

mariaDB

### Environment URL(s)

/htdocs/product/card.php

### Expected and actual behavior

redirect to the added product.

### Steps to reproduce the behavior

try to add a new product.

**Comment by ksar-ksar** [comment]
Hello,

As written on the Changelog, DOlibarr is compatible with PHP V8 but with warnings.

```
NEW: PHP 8.0 and 8.1 compatibility:
     Warning!! Application works correctly with PHP 8.0 and 8.1 but you will experience a lot of PHP warnings into the PHP server
     log files (depending on your PHP setup). Removal of all PHP warnings on server side is planned for v17.
```

You need to hide to warnings by putting $dolibarr_main_prod='1'; in conf/conf.php
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/conf/conf.php.example#L277

**Comment by Humml87** [comment]
Thank you!
