### ISSUE TITLE
API Explore doesn't run

### ISSUE THREAD

**Issue by oldu9412** [Dolibarr/dolibarr#22915]
### Bug

Swagger doesn't work, in https. A lot of time to run, and that : 
![image](https://user-images.githubusercontent.com/10073396/203170841-b775da5f-4ae7-48e8-be69-3ea696573647.png)

Nothing appen when I put de API key
When I remove forced redirection https and remove the cookie on browser, it work
The API call works

### Environment Version

16.0.2

### Environment PHP

7.4.29

**Comment by atm-maxime** [comment]
I can't reproduce, so I think this issue is related to your environnment.
