### ISSUE TITLE
Link invoice to contrat via the api

### ISSUE THREAD

**Issue by romain-neil** [Dolibarr/dolibarr#22929]
### Feature Request

Hello, It would be nice if we could link an invoice from the api, to an contrat.

The web interface allow it, as he send an post request to 'addlink' related to an invoice, but this is not visible in the code.

### Use case

- Get the related invoices from contrat api
- Get the related contrat from invoice api (I think this is already done)
- Link an recently created invoice, to an existing contrat

**Comment by romain-neil** [comment]
So, the issue is already working, by specifing the 'linkedObjectsIds' property in the request to create the invoice

**Comment by Cyrdona** [comment]
Hello sir, I am a novice developer but I would like to add an Api electronic invoice from my country in my local dolibarr but I do not know how to go about it, can you help me?
