### ISSUE TITLE
Attached files and documents in products

### ISSUE THREAD

**Issue by jasch0825** [Dolibarr/dolibarr#22920]
### Bug

If you add more as 9 image to a product under linked files, then you can't sort the attached files any more, like you wanted.

### Environment Version

16.0.2

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

Mysql

### Steps to reproduce the behavior

By more as 9 image, the sorting function is not working proper any more.

**Comment by priojk** [comment]
I did not verify the problem myself. However, it sounds like the position of the files could be a number, which is sorted as a string. This would mean a sorting order of 1, 10, 2, 3 ... 9 instead of 1, ..., 10. Could you check, if the tenth element always ends up in position 2? Or is not sorting possible at all?

**Comment by jasch0825** [comment]
I checked again and made some pictures:

![Web capture_23-11-2022_94529_tecsit de](https://user-images.githubusercontent.com/56758697/203503872-ee5f25d5-77a0-4601-b963-ebf3a383bdb0.jpeg)
Product with 10 pictures

![Web capture_23-11-2022_94846_tecsit de](https://user-images.githubusercontent.com/56758697/203504419-76dc5089-c3d5-4923-842d-41b28137f4e8.jpeg)
Result after moving position 1 to 2 **and reload** the page 

![Web capture_23-11-2022_95225_tecsit de](https://user-images.githubusercontent.com/56758697/203505092-67202d70-d010-4c18-8480-b7b0f74d3cba.jpeg)
Result after moving position 1 to 2 **and reload the page again**

Just let me know if you need more information.

**Comment by priojk** [comment]
I think your screenshots confirm my reasoning. On the second screenshot, the last two images presumably have the index 10 and 11. After the movement and reload, they get to the first positions, then following the image with index 2 and so on, so the sorting goes 10, 11, 2, 3, ..., meaning it is alphabetically sorted as strings and not as numbers. We see the same behaviour also with account numbers, where this happens as well.

In the case of product image positions, this indeed seems to be a bug.

**Comment by ksar-ksar** [comment]
Hello,

It is still the case with V18 ?
