### ISSUE TITLE
Bug in Module Builder

### ISSUE THREAD

**Issue by karozans** [Dolibarr/dolibarr#22930]
### Bug

There is some bug somewhere in the code of Module Builder that automatically deletes the api_claims.class.php files.

### Environment Version

v16.0.2

### Environment OS

Mac OS 13.0

### Environment Web server

Apache 2.4.46

### Environment PHP

7.4.21

### Environment Database

5.7.34

### Expected and actual behavior

When you perform some actions in the Module Builder and have an API class specified, on some occasions, it will automatically remove the respective api_claims.class.php.

### Steps to reproduce the behavior

Create an api_claims.class.php and edit it.

Add a new object to the same module using the module builder.  Then remove the same object using the module builder.

The api_claims.class.php is automatically removed.

**Comment by Hystepik** [comment]
This is not a bug this is a feature that is not already develop
So I close the issue

**Comment by karozans** [comment]
What?  It's a feature that deletes your code automatically?  That's completely absurd.  Did you even replicate the issue?

**Comment by Hystepik** [comment]
You didn't understand the part that

**Comment by Hystepik** [comment]
Sorry if you didn't understand. 
What I was saying to you is that yes that is a bug but the way to fix this is by introducing a new feature so it's a feature request too

**Comment by karozans** [comment]
Oh yes.  I did misunderstand you.  Thanks
