### ISSUE TITLE
Add "Send Email Expiration Alert" on module Contract/Subscription

### ISSUE THREAD

**Issue by relaxibus** [Dolibarr/dolibarr#22942]
### Feature Request

Using the module Contract/Subscrition, an "subscription expiration email alert" to the admin/user is missing to stay up to date and to advice customers without the need to login into Dolibarr. 

### Use case

Better Subscription expirations handling

### Suggested implementation

In the "Contract/Subscription" card, add a tab "Alerts" and then a field to add destination email addresses. Set the period in days when to send the email alert.

### Suggested steps

In the "Contract/Subscription" card, add a tab "Alerts" and then a field to add destination email addresses. Set the period in days when to send the email alert.

**Comment by johnbonn13** [comment]
That is something i would definitely use. +1 for this feature!

**Comment by relaxibus** [comment]
Any update from the developer? Will this feature be integrated?
