### ISSUE TITLE
[Feature Request] Supplier Payment Email Templates Config

### ISSUE THREAD

**Issue by toni-mx** [Dolibarr/dolibarr#22946]
# Feature Request
Template configuration for recent feature file attached to supplier payments to homologue functions with the rest of modules.

## Environment
- **Version**: 16.0.1
- **OS**:  Win 11 22H2
- **Web server**: Apache
- **PHP**: litespeed 7.4.33
- **Database**: MySQL or MariaDB 5.7.39-log-cll-lve
- **URL(s)**: /admin/mails_templates.php
## Expected and actual behavior
Be able to config and save email templates.
As today, you can't config templates of this particular documents. Temp workarround is saving them with no module linked.

## Steps to reproduce the behavior
Try to do an email template for supplier payments.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![imagen](https://user-images.githubusercontent.com/79340841/203666717-27f0f324-a6b7-43bb-a6dd-121aa95bccd0.png)
![imagen](https://user-images.githubusercontent.com/79340841/203666733-35d76e32-b666-40ed-80ee-ca82138a244a.png)

**Comment by papoteur-mga** [comment]
I just wanted to file the same request.
There templating available to send the the supplier invoice, which I found of limited interest, but for sending the payment recepisse, this is possible to send, but without template. This is however more important for communication with suppliers.
Please reopen.
PS: I use v18
