### ISSUE TITLE
Extrafields' visibility cannot contain square brackets anymore (worked until Dolibarr 14 but do not work in 15-16)

### ISSUE THREAD

**Issue by joanahead** [Dolibarr/dolibarr#22949]
### Bug

Updated on 28-nov-2022 for simpler explanation and simpler example.

When creating an extrafield anywhere (societe, invoice, propal, etc.), visibility can be defined with a conditional statement. This is crucial because it can, for example, determine who can view and work with that extrafield.
The exemple of visibility that Dolibarr gives is this
`preg_match('/public/', $_SERVER['PHP_SELF'])?0:1`

Now, in Dolibarr 16 (it also failed in Dolibarr 15) such a condition does not work because the function that evaluates the condition does not accept square brackets ("[" and "]"). The function is located in /htdocs/core/lib/functions.lib.php (line 8596 in Dolibarr's 16.0 file) and is defined as...
`function dol_eval($s, $returnvalue = 0, $hideerrors = 1, $onlysimplestring = '1'){...`

It looks that the $onlysimplestring could be set to 2 in order to get the previous behaviour (it worked in Dolibarr 14) but it doesn't.

So, the error with conditions that we use (like the one presented in the next line) are not possible and we are stuck to Dolibarr 14 (because they worked there) and should not upgrade to 15 or 16.
`($user->array_options[options_importance]?1:0)`
It will not work because the use of this kind of brackets "[" do not satisfy the preg_match inside the function dol_eval(...){...}

**Possible solution:**
Option 1 (DOES NOT WORK). When calling the function in htdocs/core/tpl/extrafields_view.tpl.php (lines 75, 78 and 83) add the parameters hideerrors (to 1) and onlysimplestrings (to 2) like this:
`$enabled = dol_eval($extrafields->attributes[$object->table_element]['enabled'][$tmpkeyextra], 1, _**1, 2**_);`
IT DOES NOT WORK. Although this change would let our Dolibarr work again the field becomes visible but not editable! 
Option 2 (ANYWAY IT DOESN'T MAKE A CHANGE BECAUSE OPTION 1 DOES NOT WORTK). ¿Make the $onlysimplestring value depend on a global configuration in dolibarr?
**Option 3 (THIS DOES WORK).** In https://github.com/Dolibarr/dolibarr/blob/16.0/htdocs/core/lib/functions.lib.php (line 8613) we changed the following line in order to add square brackets...
Instead of this_
`if (preg_match('/[^a-z0-9\s'.preg_quote('^$_+-.*>&|=!?():"\',/@', '/').']/i', $s)) {`
We did this:
`if (preg_match('/[^a-z0-9\s'.preg_quote('^$_+-.*>[]&|=!?():"\',/@', '/').']/i', $s)) {`

### Environment Version

16.0.2 (although it fails in Dolibarr 15 to 16)

### Environment OS

Centos 7 (irrelevant)

### Environment Web server

Apache (irrelevant)

### Environment PHP

7.4 (irrelevant)

### Environment Database

MySQL (irrelevant)

### Expected and actual behavior

We expect extrafields with visibility based in other extrafields (like `($user->array_options[options_importance]?1:0)`) to be valid.
They did work perfectly in Dolibarr 14. 
As the code in the function dol_eval (inside /htdocs/core/lib/functions.lib.php) has changed those extrafields are not editable anymore in Dolibarr 15 or 16 (because square brackets are not allowed in the preg_match function).

### Steps to reproduce the behavior

(Simpler example as 28-nov-2022:)
1. Create extrafield (in any of these: societe, propal, invoice...) with the example visibility proposed by Dolibarr:
`preg_match('/public/', $_SERVER['PHP_SELF'])?0:1`
2. Go and edit the object as a Dolibarr user.
3. Change the visibility in the extrafield's config to the opposite definition:
`preg_match('/public/', $_SERVER['PHP_SELF'])?1:0`
4. Go to the object's card and observe that the behaviour has not changed. That's because the square brackets are no longer allowed in Dolibarr 15-16

(Older exemple) As an example...
1. Create extrafield (it can be an integer) called "importance" in user. So, the user can have an "importance" of 0, 1, 2...
6. Create extrafield "secret-text" in propal (it can be a simple text string). The visibility of this field will depend on the user "importance". Users with importance of 1 will be able to edit the field. So, that field should have a visibility like this `($user->array_options[options_importance]?1:0)`, meaning that if the user is important ("importance==1") visibility will be 1, and 0 in any other case.
7. Set "importance" for your current user to 0.
8. Go to a propal and you cannot see/edit the "secret-text" extrafield of the propal. Ok.
9. Set "importance" for your current user to 1.
10. Go to a propal and you cannot still see/edit the "secret-text" extrafield of the propal. THAT'S AN ERROR, you should be able to see it. The cause of the error is the visibility does not fit the preg_match in /htdocs/core/lib/functions.lib.php.

**Comment by ksar-ksar** [comment]
Hello,

It is still the case with V18 ?
