### ISSUE TITLE
Product - The link in an error message is badly formatted

### ISSUE THREAD

**Issue by thibdrev** [Dolibarr/dolibarr#22952]
### Bug

See attached in a French instance of Dolibarr 16.0.2:
<img width="826" alt="Capture" src="https://user-images.githubusercontent.com/7697736/203857465-8f44a8e9-8d77-478d-a1b4-56878916225a.PNG">

### Environment Version

16.0.2

### Environment OS

LInux

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

MariaDB

### Environment URL(s)

htdocs/product/fournisseurs.php

### Expected and actual behavior

Expected: error message with URL correctly formatted.
Actual: error message with URL badly formatted.

### Steps to reproduce the behavior

1. Create a 1st product. Give it a price and supplier reference.
2. Create a 2nd product. Give it a price and the same supplier reference as in 1.
3. The error shall pop up.

### Attached files

I think the key to the translated error message is: `ReferenceSupplierIsAlreadyAssociatedWithAProduct`.

Located in Transifex here: https://www.transifex.com/dolibarr-association/dolibarr/translate/#fr_FR/suppliers/12458879

And called in the code here: https://github.com/Dolibarr/dolibarr/blob/53a1867be8ae6a9bc5634119d4a1e25e46786bc1/htdocs/product/fournisseurs.php#L277

**Comment by eldy** [comment]
Seems fixed with #22987
