### ISSUE TITLE
Event type changes to AC_EMAIL when editing an event related to a Ticket

### ISSUE THREAD

**Issue by veronicacletizia** [Dolibarr/dolibarr#22957]
### Bug

Hi there,

I'm performing some tests in dolibarr 16.0.2 and found the folliwing:

1. I created a ticket with the mandatory fields
2. Secondly, I created 3 events related from the ticket so they are related to it to follow up those events.
3. I opened one of the events to modify its progress and when saving the event its type got changed to AC_EMAIL

I try the same thing but creating an isolated event from the agenda and not related to a ticket and event type remained correctly.

I'm also pasting some images for reference:

**Events just created in ticket - before editing**
![image](https://user-images.githubusercontent.com/74732581/203874515-d51eab83-411e-4f57-b70c-1709319e815b.png)

![image](https://user-images.githubusercontent.com/74732581/203874630-f3210fb5-1a1a-4562-9b81-d5fbb69a0e1c.png)

**Event editing**
![image](https://user-images.githubusercontent.com/74732581/203874762-157305f3-35a6-4107-add0-f1057b58f6bd.png)

**After changing event progress**
![image](https://user-images.githubusercontent.com/74732581/203874866-c94fea2d-e68d-4990-8370-5c62513f3b93.png)

Then, I compared the view and edit card for a regular event not related to a ticket and it looks like **the event type is missing** when the event is related to the ticket. For example:

![image](https://user-images.githubusercontent.com/74732581/203875205-6e1c32a0-16b5-45f4-9f6d-6480d881c312.png)

Thank you so much for the help!

Regards,
Vero

### Environment Version

16.0.2

### Environment OS

Windows 10

### Environment Web server

Apache 2.4.51

### Environment PHP

PHP 7.4.26

### Environment Database

Maria DB 5.7.36

**Comment by veronicacletizia** [comment]
Oh, One more comment I cehck back in 16.0.0 and it works ok.

**Comment by eldy** [comment]
I pushed a more complete fix into develop for v17
