### ISSUE TITLE
Impossible to add task times to an existing draft invoice

### ISSUE THREAD

**Issue by sebastien-prudhomme** [Dolibarr/dolibarr#23019]
### Bug

Impossible to add task times to an existing draft invoice, Dolibar greys all the draft projects because they are linked to another company, which is not the case.

File projet/tasks/time.php is calling selectInvoice method with string 'invoice' parameter instead if the company id, I guess '$projectstatic->thirdparty->id'

### Environment Version

16.0.1

**Comment by lamrani002** [comment]
can i have more explanation about the behavior , i try to reproduce the problem in **projet/tasks/time.php**  but it works fine for me

**Comment by sebastien-prudhomme** [comment]
@lamrani002 maybe related to PHP version, i'm using this Docker image https://github.com/tuxgasy/docker-dolibarr and the image upgrades from Dolibarr 16.0.0 on PHP 7.4 to Dolibarr 16.0.1 on PHP 8.1. All was working fine before upgrading to 16.0.1.

I can confirm that the patch I propose is working.
