### ISSUE TITLE
FIX Third party should get notification upon first ticket creation by email collector class

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#23062]
### Feature Request

Dolibarr has a other setup key, **TICKET_CHECK_NOTIFY_THIRDPARTY_AT_CREATION**. Upon setting the value **1** to this key, third party gets notification on new ticket creation by Dolibarr users. But when tickets are created first time with the help of **Email Collector Class**, this doesn't happen.

### Suggested implementation

When a third party sends an email to the mailbox of the Email Collector Class, emaill collector class will collect email and creates a ticket. Now if the vale of the key **TICKET_CHECK_NOTIFY_THIRDPARTY_AT_CREATION** is _**1,**_ then third party should get an confirmation email about the new ticket creation.

**Comment by alsoft10** [comment]
@eldy new feature created #23063

**Comment by priojk** [comment]
I would even think, this could be classified as a bug fix (meaning it could go in v16 instead of v18), since not auto-sending the e-mail would be unexpected, when the global variable for doing so is set.
