### ISSUE TITLE
Wrong invoice amount when billing Project task spent time

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#23075]
### Bug

When creating an invoice for project tasks time spent, the amount in the invoice is wrong.

### Environment Version

14-16

### Expected and actual behavior

When the task is for 10 hours and the user pay rate is 15 currency/h, the invoice line should be for QTY = 10 and U.P net = 15.

In reality, the invoice QTY is correct, but the U.P net is not the hourly rate, but the total for the task (i.e. 150)

### Steps to reproduce the behavior

Create a project, create a task, add time spent to this task, and then bill it.

![1](https://user-images.githubusercontent.com/4587305/205131290-09b97066-b0c0-4559-902a-ec8c3ec48f8d.png)
![2](https://user-images.githubusercontent.com/4587305/205131304-e52121f7-d96d-4a1b-b211-c43fdd31fe04.png)
![3](https://user-images.githubusercontent.com/4587305/205131313-0977fd8a-5d5c-4213-aec6-3b5703adf623.png)

**Comment by milenmk** [comment]
P.S.: If in file "/projet/tasks/time.php" line 465 is uncommented and changed to `$pu_ht = $fuser->thm;` the invoice is correct.

**Comment by eldy** [comment]
It seems fix was already pushed into v16. So it will be merged up in higher version (17, develop, ) automatically. No need to repush the pr in develop
