### ISSUE TITLE
Bug:  Complementary User Attributes

### ISSUE THREAD

**Issue by karozans** [Dolibarr/dolibarr#23078]
### Bug

The option for the Complementary User Attributes has an option under it for "Can always be edited" doesn't seem to have any effect.

### Environment Version

16.0.3

### Environment OS

Mac OS 13.0

### Environment Web server

Apache 2.4.46

### Environment PHP

PHP 7.4.21

### Environment Database

MySQL 5.7.34

### Environment URL(s)

/user/admin/user_extrafields.php

### Expected and actual behavior

It should be expected if the checkbox is unchecked, it should not be editable.

However, it seems like to me that you should be allowed to put in a conditional statement for edit.

It would be nice to have some complementary attributes that the user cannot edit, but an admin or manager can.

### Steps to reproduce the behavior

1.  Create a complementary attribute.
2. Remove the check in the box for edit.
3. Try to edit the attribute.

**Comment by milenmk** [comment]
"Can always be edited" when checked, should add a "pencil" to the field in view mode so it can be edited directly, without editing the card itself i.e. for fast edit of the field value for the currently viewed "card.php".

**Comment by karozans** [comment]
I see.  I didn't know that's what that meant.

Don't you think there should be a field for editablity, the same as the field for visibility?

For instance.  What if an admin creates an account for a non-admin, and they have a complementary attribute in the list for something like an employee number and they do not want the user to be able to edit this, but they want the user to be able to edit other fields in their own account?

**Comment by hregis** [comment]
@milenmk @karozans 
for "extrafields" the "alwayseditable" parameter can only limit editing when the object is in "draft" mode

**Comment by bos4711** [comment]
> "Can always be edited" when checked, should add a "pencil" to the field in view mode so it can be edited directly, without editing the card itself i.e. for fast edit of the field value for the currently viewed "card.php".

I agree. Adding the "fast edit" feature for extrafields would be incredibly useful. In 17.x "Can always be edited" does not add the "fast edit", but I wish it did.

**Comment by ksar-ksar** [comment]
Hello,

It is still the case with V18 ?
