### ISSUE TITLE
Bug: Purchase Order (New Line) shows "NaN" on selected "Predefined products/services to purchase"

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#23091]
### Bug

The values (exempt Vendor SKU) from the "Vendor prices" are not take in the PO Line.

P.S. i don´t know, how i can debug the Javascript. My knowledge is not enough to fix this problem on my self.

### Environment Version

17.0.0-beta

### Environment OS

Windows 10

### Environment Web server

xampp

### Environment PHP

PHP 8.1.10

### Environment Database

mariaDB

### Steps to reproduce the behavior

1. Add a Vendor Price on a Product.
2. Create a Purchase Order.
3. Select the Product with the Vendor Price
![image](https://user-images.githubusercontent.com/78662388/205461383-1eae1220-f3da-4671-858e-91586bd8cd80.png)
4. Now you can see... No values are loaded.
![image](https://user-images.githubusercontent.com/78662388/205461390-47cb1211-22d0-4e88-8a5d-166c42d1d445.png)

**Comment by ksar-ksar** [comment]
Hello,

It is still the case with V18 ?
