### ISSUE TITLE
Cannot validate orders in v17

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#23096]
### Bug

When trying to validate a customer order, the following error appears:  "Failed to insert event : Unknown column 'ip' in 'field list'" and the problem comes from inserting into llx_actioncomm. Full SQL query from the debug tool is:

`INSERT INTO llx_actioncomm(ref,datec,datep,datep2,durationp,fk_action,code,ref_ext,fk_soc,fk_project,note,fk_contact,fk_user_author,fk_user_action,fk_user_done,label,percent,priority,fulldayevent,location,transparency,fk_element,elementtype,entity,extraparams,email_msgid,email_from,email_sender,email_to,email_tocc,email_tobcc,email_subject,errors_to,recurid,recurrule,recurdateend,num_vote,event_paid,status,ip) VALUES ('(PROV)', '2022-12-04 11:11:08', '2022-12-04 11:11:08', '2022-12-04 11:11:08', null, 40,'AC_ORDER_VALIDATE', null, 1, null,  'Поръчка SO2212-0001 е валидирана', null, 1, 1, null, 'Поръчка SO2212-0001 е валидирана', '-1', '0', '0', '', '0', 1, 'order', 1,null, null, null, null, null, null, null, null, null, null, null, null, null, 0, 0, null)7.98
[DB_ERROR_NOSUCHFIELD] Unknown column 'ip' in 'field list'`

In "install/tables/llx_actioncomm" there is NO field named "ip"

### Environment Version

17

### Expected and actual behavior

The order should be validated and action record inserted into llx_actioncomm. Add field "ip" into "install/tables/llx_actioncomm"

### Steps to reproduce the behavior

Create customer order and try to validate

**Comment by SHENMIYANG** [comment]
I also had the same error when I added a user.
