### ISSUE TITLE
BUG when creating new user！

### ISSUE THREAD

**Issue by SHENMIYANG** [Dolibarr/dolibarr#23101]
### Bug

Failed to insert event : Unknown column 'ip' in 'field list'

### Environment Version

17.0.0-beta

### Environment OS

windows

### Environment Web server

Apache2.4.39

### Environment PHP

php 8.0.2

### Environment Database

mysql 8.0.12

### Environment URL(s)

http://mywebname/user/card.php

### Expected and actual behavior

This problem occurs when creating a user to create a product

### Attached files

![微信图片_20221205160626](https://user-images.githubusercontent.com/49553147/205587598-3b0d90d5-73c2-4225-9228-d01ae01988ff.png)

**Comment by lamrani002** [comment]
I tried to produce the same bug when i create a user but everything works fine and we don't have anyway a IP field in the page.
can you tell us more information about it ?

**Comment by SHENMIYANG** [comment]
> I tried to produce the same bug when i create a user but everything works fine and we don't have anyway a IP field in the page. can you tell us more information about it ?

Sorry no, even I have this problem when adding products.

**Comment by SHENMIYANG** [comment]
> I tried to produce the same bug when i create a user but everything works fine and we don't have anyway a IP field in the page. can you tell us more information about it ?

Does your version match mine?

**Comment by SHENMIYANG** [comment]
> I tried to produce the same bug when i create a user but everything works fine and we don't have anyway a IP field in the page. can you tell us more information about it ?

![image](https://user-images.githubusercontent.com/49553147/205594539-84403964-9fda-40bf-9426-b3b03c3fd8d7.png)
Version 17.0.0 has this update, is there something wrong with my installation method?

**Comment by milenmk** [comment]
I guess it is the same as [HERE](https://github.com/Dolibarr/dolibarr/issues/23096). The query to add a record to llx_actioncomm has an "ip" field/column in it, but this column is not created during installation and is missing from "install/tables/llx_actioncomm"

**Comment by SHENMIYANG** [comment]
> I tried to produce the same bug when i create a user but everything works fine and we don't have anyway a IP field in the page. can you tell us more information about it ?
![image](https://user-images.githubusercontent.com/49553147/205608727-3a71af54-0953-44d7-bf32-ae187f399efc.png)

I seem to have found my problem, is this value required? I just checked my config file and it is null.

**Comment by puntogestioncl** [comment]
Hello, I have the same error. How did they solve it???

![screen](https://user-images.githubusercontent.com/59832219/205666112-56e3bbd7-36b9-4c62-b070-a388e6e51162.png)

**Comment by milenmk** [comment]
I've edited the `llx_actioncomm` table to add a new column named "ip", type "int" and size "11". Nothing is added to this field anyway, guess it is still in development.

**Comment by SHENMIYANG** [comment]
> 你好，我有同样的错误。他们是怎么解决的？？？
> 
> ![屏幕](https://user-images.githubusercontent.com/59832219/205666112-56e3bbd7-36b9-4c62-b070-a388e6e51162.png)

Sorry, it's not resolved yet, I'll try it with version 16.0.

**Comment by ksar-ksar** [comment]
Hello,

It is still the case with V18 ?
