### ISSUE TITLE
Cannot create new expense report after upgrading 15->16: Dolibarr breaks

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#23105]
### Bug

When doing to HRM->Expense report->New, Dolibarr persishes completely showing only this error message:

>Warning: Undefined property: Conf::$project in /customers/2/b/5/DOMAIN.COM/httpd.www/doli/expensereport/card.php on line 120
>Warning: Attempt to read property "enabled" on null in /customers/2/b/5/DOMAIN.COM/httpd.www/doli/expensereport/card.php on line 120
>Warning: Cannot modify header information - headers already sent by (output started at /customers/2/b/5/DOMAIN.COM/httpd.www/doli/expensereport/card.php:120) in /customers/2/b/5/DOMAIN.COM/httpd.www/doli/main.inc.php on line 1408
>Warning: Cannot modify header information - headers already sent by (output started at /customers/2/b/5/DOMAIN.COM/httpd.www/doli/expensereport/card.php:120) in /customers/2/b/5/DOMAIN.COM/httpd.www/doli/main.inc.php on line 1414
>Warning: Cannot modify header information - headers already sent by (output started at /customers/2/b/5/DOMAIN.COM/httpd.www/doli/expensereport/card.php:120) in /customers/2/b/5/DOMAIN.COM/httpd.www/doli/main.inc.php on line 1416 

We got this after we upgraded from 15.0 to 16.0. 

### Environment Version

16.0.1

### Environment PHP

8

**Comment by milenmk** [comment]
Can't reproduce, but on fresh v16.0.3 install. Can you tell if the Project module is enabled, if not, check that you don't have `EXPENSEREPORT_PROJECT_IS_REQUIRED` set to 1 in Home>Setup>Other settings.

Also, you can try upgrading to latest v16.0.3

**Comment by bos4711** [comment]
False alarm: this was caused by the Web provider who turned on "PHP Error messages".

Closing.
