### ISSUE TITLE
Unable to bulk delete leave requests

### ISSUE THREAD

**Issue by paddatrapper** [Dolibarr/dolibarr#23117]
### Bug

From the Awaiting approval list of leave requests, selecting records with the checkbox and using the Select action drop-down menu to delete them does not actually delete the records. It prompts for validation and then returns 'No records deleted' in green like the front-end did not include the list of leave items to delete when POSTing to the server.

### Environment Version

16.0.3

### Environment OS

Debian Bullseye

### Environment Web server

Apache 2.4.54

### Environment PHP

8.0.24

### Environment Database

MariaDB 10.9.3

### Environment URL(s)

/holiday/list.php

### Expected and actual behavior

The selected leave should be deleted

### Steps to reproduce the behavior

1. Go to HRM
2. Click on Leave -> List -> Awaiting approval
3. Select a leave request using the checkbox at the end of the row
4. Select Delete from the Select action dropdown and click Confirm
5. Are you sure you want to delete the 2 selected record(s)? Select Yes and click Validate
6. See bubble reporting 'No record deleted'

**Comment by milenmk** [comment]
There is a restriction, so only Draft, Cancelled or Refused holiday requests can be deleted.

**If you want to delete ONLY approved holiday requests:** in "htdocs/core/actions_massactions.inc.php" on line 1043 change `if ($objectclass == 'Holiday' && !in_array(` to `if ($objectclass == 'Holiday' && in_array(`

**If you want to delete ANY holiday requests**, no matter what their status is, add `/*` before line 1042 and `*/` after line 1046

**Comment by paddatrapper** [comment]
Thanks. This was an attempt to work around #22752. I don't think I'll end up modifying the code as I run it in Docker.

Perhaps the message to the user should be more clear? Perhaps a warning that all selected requests cannot be deleted, or x selected requests cannot be deleted
