### ISSUE TITLE
Error when creating a new asset (Dolibarr Vers.16.03)

### ISSUE THREAD

**Issue by grossfr** [Dolibarr/dolibarr#23112]
### Bug

MySQL or MariaDB 5.7.40-0ubuntu0.18.04.1
When creating a new asset, I get the following error:

Error in calculation of depreciation items (recovery and future)
error getting recorded depreciation lines: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘in_accounting_bookkeeping(fk_docdet) AS ( SELECT DISTINCT fk_docdet FROM hdbd_ac’ at line 1

### Environment Version

16.03

### Environment OS

0ubuntu0.18.04.1

### Environment Web server

Apache

### Environment PHP

 7.4.33

### Environment Database

MySQL or MariaDB 5.7.40

**Comment by aspangaro** [comment]
Hello @grossfr 

Your database is not compatible with function 'WITH'.

In v17beta, function WITH are removed on asset module from the request.

See this PR : https://github.com/Dolibarr/dolibarr/pull/22958/commits/035f7c57c4d54004a7714db6cd5dc8dab53b088e
