### ISSUE TITLE
Error on validating bill to update stock

### ISSUE THREAD

**Issue by BeMins** [Dolibarr/dolibarr#23122]
### Bug

Hi all.
When I try to validate a incoming bill, that must modify my stock, I get a 500 error. When I go in the log file to see what's happening : 

`[Tue Dec 06 15:09:25.317282 2022] [proxy_fcgi:error] [pid 233260:tid 140457568888384] [client ######:61824] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/######/billing/htdocs/custom/ecommerceng/class/data/eCommerceSite.class.php:612\nStack trace:\n#0 /var/www/######/billing/htdocs/custom/ecommerceng/core/triggers/interface_90_modECommerceng_ECommerceng.class.php(1014): eCommerceSite->listSites()\n#1 /var/www/######/billing/htdocs/core/class/interfaces.class.php(183): InterfaceECommerceng->runTrigger()\n#2 /var/www/######/billing/htdocs/core/class/commonobject.class.php(5787): Interfaces->run_triggers()\n#3 /var/www/######/billing/htdocs/product/stock/class/mouvementstock.class.php(594): CommonObject->call_trigger()\n#4 /var/www/######/billing/htdocs/product/stock/class/mouvementstock.class.php(819): MouvementStock->_create()\n#5 /var/www/######/billing/htdocs/fourn/class/fournisseur.facture.class.php(1834): MouvementStock->reception()\n#6 /var/www/######/billing/htdocs/fourn/facture/card.php(225): FactureFournisseur->validate()\n#7 {main}\n  thrown i...', referer: https://######/fourn/facture/card.php?id=91&action=valid`

I tried to read the code and it's here : 

```
 function listSites($mode='array')
        {
                global $langs;

                $list = array();

        $sql = "SELECT";
                $sql.= " t.rowid,";
                $sql.= " t.name,";
                $sql.= " t.last_update";
        $sql.= " FROM ".MAIN_DB_PREFIX."ecommerce_site as t";

        $result = $this->db->query($sql);
```

### Environment Version

17.0.0 Beta

### Environment OS

Ubuntu 22.04.1

### Environment Web server

Apache2

### Environment PHP

8.1.12

### Environment Database

mysql  Ver 8.0.31-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

### Expected and actual behavior

Actual : 500 error
Expected : Validate the bill and update the stock

### Steps to reproduce the behavior

Create a product in stock
Create incoming bill using this product
Validate bill

### Attached files

![image](https://user-images.githubusercontent.com/96686174/205943410-9087e20b-f2d7-4ed5-962e-e6fa31929077.png)
![image](https://user-images.githubusercontent.com/96686174/205943492-e4dbd7f6-f223-4810-a69c-4821af6050c8.png)
![image](https://user-images.githubusercontent.com/96686174/205943583-073a5473-c50d-41b3-ba75-cd851e3c3beb.png)

**Comment by milenmk** [comment]
Deactivate the third-party module named "ecommerceng" and try again. If no error, the problem is with the third-party plugin itself or wrong module configuration.

If after deactivation everything works, contact the module developer. 

Keep in mind that 17 is a beta and is still in development. :)

**Comment by BeMins** [comment]
Hi Milenmk, thanks for answering

> Keep in mind that 17 is a beta and is still in development. :)

Sure I know. that's why I test and report it :) 

I'd love to deactivate the module, but I'm stuck with a blank page.

![image](https://user-images.githubusercontent.com/96686174/205955160-2613c401-5af4-4f5f-ad42-74d320d97e49.png)

Do you know where I can manually deactivate it ? Nevertheless, it was working perfectly fine on former versions. :(

**Comment by milenmk** [comment]
There are changes in v17 that may cause the module not to work correctly. As for the blank page, check your log for errors. It could be a server issue or file(s) permission/ownership issue.

A workaround is to create a file named "modulebilder.txt" in "/custom/ecommerceng", activate the "Module builder" from Home->Setup->Modules/Applications and then click the "bug" icon at the top right. This will lead you to the module builder setup, where you will be able to deactivate any third-party module.

**Comment by BeMins** [comment]
OK. Thanks. 
I now get it. My module was correctly configured on the 15.0 and 16.0 . Now on the 17, it doesn't work anymore. 

I had to completely remove the directory to make it work. You can close this bug, it's a bug in EcommerceNG. 

Thanks for helping.
