### ISSUE TITLE
Bug: Since the check box is at left with MAIN_CHECKBOX_LEFT_COLUMN variable

### ISSUE THREAD

**Issue by TechServiceConseil** [Dolibarr/dolibarr#23126]
# Bug
Since the check box is at left with MAIN_CHECKBOX_LEFT_COLUMN variable, the menu is display on the left like when the variable is at 0 instead of beeing display on the right. 
At the actual stage we can not see the menu when we click on the hamburger button in list.

## Environment
- **Version**: 16.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.33
- **Database**:  5.7.30-log
- **URL(s)**: /societe/list.php?leftmenu=thirdparties

**Comment by milenmk** [comment]
This is a new feature available for v17+, so on v16, it will not work correctly

![Screenshot_2](https://user-images.githubusercontent.com/4587305/205987222-79e79363-53e4-433f-9eab-1397b663a34a.png)
.

**Comment by milenmk** [comment]
Can confirm "MAIN_CHEKBOX_LEFT_COLUMN" works correctly on v17 and the menu is shown as expected.

![Screenshot_2](https://user-images.githubusercontent.com/4587305/206515332-04a43588-78ab-48bf-9b46-34e6cd854e13.png)
