### ISSUE TITLE
Core Class Override

### ISSUE THREAD

**Issue by GaetanMedas** [Dolibarr/dolibarr#23150]
### Feature Request

After a few weeks of using Dolibarr, I miss one very important thing... An override system for Dolibarr core files.

Any changes to a core file will be lost with the next update and will need to be reintegrated manually. It's really not practical.

Giving priority to files stored in a particular folder would correct this defect.

### Use case

If I want to modify the newMessage() function of the htdocs/ticket/class/ticket.class.php file, I create a htdocs/custom/ticket/class/ticket.class.php file containing a CustomTicket class inheriting from the class Ticket and containing the modified newMessage() function.

---

Version FR

Après quelques semaines d'utilisation de Dolibarr, une chose très importante me manque... Un système d'override des fichiers core de Dolibarr.

Toute modification d'un fichier core sera perdue lors de la prochaine mise à jour et devra être réintégrée manuellement. Ce n'est vraiment pas pratique.

Donner la priorité à des fichiers stockés dans un dossier particulier permettrait de corriger ce défaut.

Par exemple, si je veux modifier la fonction newMessag() du fichier htdocs/ticket/class/ticket.class.php, je crée un fichier  htdocs/custom/ticket/class/ticket.class.php contenant une classe CustomTicket héritant de la classe Ticket et contenant la fonction newMessage() modifiée.

Pour que cela fonctionne, il faudrait que Dolibarr, à chaque appel d'une classe, vérifie si une class CustomMaClass existe et si elle contient la fonction recherchée est présente. Si elle existe elle est exécutée à la place de la classe du core.

### Suggested implementation

For this to work, Dolibarr should, at each call of a class, check if a class CustomMyClass exists and if it contains the sought function is present. If it exists it is executed instead of the core class.

### Suggested steps

Create an autoload of custom classes.
Create a function that checks if a CustomXxxx class exists and if it contains the called function.

**Comment by milenmk** [comment]
Why not create a custom module and use action_hooks or triggers?

**Comment by GaetanMedas** [comment]
Hello Milenmk,

Hooks and triggers do not replace core files, they only add code, not modify existing code.

For example if I want to modify an email built by the Ticket class, I cannot do it without modifying the class because it is this class which manages the construction of the content of the email then which calls the function of sending email.

I already had 4 cases where it was impossible for me to make my modifications with triggers or hooks because the code must be replaced.

**Comment by milenmk** [comment]
1. Go to "Home > Setup> Email" and there you can edit the templates for emails. 
2. You can use the hook to modify the action named "add_message" from "ticket.card.php".

![Screenshot_1](https://user-images.githubusercontent.com/4587305/206499371-3c62b78c-bbda-4c39-b998-07b81d235c6a.png)

**Comment by GaetanMedas** [comment]
Thank you Milenmk,

Unfortunately, some things cannot be done from email templates. For example, it is not possible to put an image in the intro email. This is just an example, but there are always limitations expected when customizing a tool.

Another example, I wanted to have the company name added to the "from" of emails that only had the email. For this I had to modify the file htdocs\includes\swiftmailer\lib\classes\Swift\Mime\SimpleMessage.php
Again, the Dolibarr options do not allow this modification. It would therefore be practical to be able to override certain files without risking losing the modifications with each update.

It is a system that is used by many CMS, for example Prestashop or WordPress allows overrides.

**Comment by daraelmin** [comment]
Hello, 

That looks pretty touchy to me. Indeed, most core modules are interrelated. An action on an element, for example the payment of a membership fee, can involve an invoice, an event, an accounting, etc.

How to manage the update of the child file if the parent file has been modified ?

Cheers

**Comment by GaetanMedas** [comment]
Hello Daraelmin,

Indeed, there are risks of malfunction during updates, but this is already the case when modifying the core files.
