### ISSUE TITLE
Duplicate mentions in takepos

### ISSUE THREAD

**Issue by manunord** [Dolibarr/dolibarr#23168]
### Bug

When we add mentions on the ticket these are displayed in duplicate

### Environment Version

V16

### Environment Web server

Linux

### Environment PHP

7

### Steps to reproduce the behavior

In the configuration of takepos, tab printers/Received we add an additional mention on the invoices. On the ticket the mention is displayed twice.

**Comment by manunord** [comment]
Dans receipt.php lignes 121 à 123 et lignes 326 à 328 sont en double

**Comment by IC-Florian** [comment]
I just checked on the latest version 16 of dolibarr. It is not exactly the same lines. Line 123 corresponds to the header (TAKEPOS_HEADER) and Line 319 corresponds to the footer (TAKEPOS_FOOTER). These 2 variables are configurable in the admin of the takepos module.
Moreover it is possible to add text in footer or in top of page by terminal
Issue to close

**Comment by manunord** [comment]
Yes it's ok in the last version
