### ISSUE TITLE
HTML code in ODT

### ISSUE THREAD

**Issue by Cyril35** [Dolibarr/dolibarr#23162]
Add line 160 in htdocs\includes\odtphp\odf.php

**160   $value = html_entity_decode(strip_tags($value),ENT_QUOTES);**
161          $value = $encode ? htmlspecialchars($value) : $value;
162		$value = ($charset == 'ISO-8859') ? utf8_encode($value) : $value;
163		$convertedValue = $value;

**Comment by jtraulle** [comment]
Ce problème a été mentionné sur **Forum Dolibarr france**. Il pourrait y avoir des détails pertinents ici :

https://www.dolibarr.fr/forum/t/impossible-de-mettre-des-notes-sur-produit-en-v16-0-2/41505/7

**Comment by edupulpillo** [comment]
It works fine for me, but some attributes of the HTML are not passed to the ODF document like font color and numbering of lines, etc. 
How can be improved the html decoding to respect better the format that is included in the notes made in html in the notes with the CKEditor enabled?

**Comment by edupulpillo** [comment]
[Cyril35](https://github.com/Cyril35) Great! It works fine for me.
But some attributes of the HTML notes made with the CKEditor enabled are not passed to the ODF document, like font color, numbering of lines, etc. 
How can be improved the html decoding to respect better the format that is included in the notes made in html in the notes ?

**Comment by ksar-ksar** [comment]
Hello,

It is still the case with V18 ?

**Comment by Cyril35** [comment]
Bonjour,

A priori non avec la 18.02 ça parrait réglé.
Merci pour cette mise à jour.
