### ISSUE TITLE
Price article not disponible in ORDER and INVOICE - 16.0.3

### ISSUE THREAD

**Issue by zhaoyankaichartres** [Dolibarr/dolibarr#23187]
### Bug

Dear All,

When I make an order, the price was show in line, but when we put in the order, the price take 0,00.

Best regards,

Yann

### Environment Version

16.0.3

### Environment OS

Linux 4.9.182

### Environment Web server

Apache

### Environment PHP

8.1.0

### Environment Database

mysqli (mysqlnd 8.1.0)

**Comment by ksar-ksar** [comment]
Hello,

It is still the case with V18 ?
