### ISSUE TITLE
Change product description in shipment sheet

### ISSUE THREAD

**Issue by JoWiel** [Dolibarr/dolibarr#23189]
### Feature Request

Add the possibility to modify the products descriptions in the shipment sheet. For now, the description is automatically taken from the order sheet without possibility to modify in the shipment sheet.

**Comment by milenmk** [comment]
The product description is a global feature and can be edited from the product card. Even in the order, you cannot modify the description of a product, as it is automatically taken from the product unless it's a free text entry.

As for the shipment, currently, it links the lines to the order, so they cannot be modified as it should be. There is no way to add a product to a shipment that is not present in the order and shipment lines can be edited only to change the shipped quantity, if needed.

**Comment by JoWiel** [comment]
Thanks for your reply.
In the order, we can still modify the description of an existing product (it only edit the description for this order, not in the product card). I thought it would be useful to use the same possibility in the shipment card (or at least have an option to show/not show the entire product description on the delivery note).

**Comment by milenmk** [comment]
Well, you can create a custom pdf generator in "/core/modules/expedition/doc" and change the file to not show the product label but only its ref.
