### ISSUE TITLE
German Mail Adresses

### ISSUE THREAD

**Issue by bugfishtm** [Dolibarr/dolibarr#23183]
### Feature Request

German Mail Adresses and URLs containing ä/ö/ü are not working.
Would be really nice if this could be implemented in some way (for contacts, customers and all specific areas)

If you give me permissions to do pull requests 
i could take care of that, otherwhise would be nice to see this implemented.

Thanks for your time and have great christmas!

### Use case

German Country URL and Mails

### Suggested implementation

In Customer Area
In Contact Area for 3rd Parties

**Comment by priojk** [comment]
Just to be precise: This refers to **E-Mail**-Addresses (not regular Mail addresses, which work ok), where e.g. Umlauts (äöü) are allowed in German, but also other languages allow special characters.

Can confirm that currently these special characters are just filtered out from the entry, so the rest is stored without any notification to the user leading to potentially critical situations, where the stored address may belong to someone else who then could accidentally receive sensitive information via E-Mail.

I therefore think this issue could/should be classified as a bug.

@bugfishtm There are no special permissions required to create a pull request.

**Comment by emheyarssi** [comment]
> @bugfishtm There are no special permissions required to create a pull request. 
> 

Just have a look [here](https://github.com/Dolibarr/dolibarr/blob/develop/.github/CONTRIBUTING.md)
