### ISSUE TITLE
Customer invoice contact takes wrong VAT number

### ISSUE THREAD

**Issue by JoWiel** [Dolibarr/dolibarr#23191]
### Bug

In an order, when selecting a 'Customer invoice contact' from a different third party (not the third party the order is linked to) and generating the corresponding invoice, the VAT number displayed in the PDF is the one from the original third party (not from the new 'Customer invoice contact' as one would expect).

### Environment Version

16.0.2

### Expected and actual behavior

Expected behaviour: when selecting a 'Customer invoice contact' from a different third party (not the third party the order is linked to) and generating the corresponding invoice, the VAT number displayed in the PDF should be the one from the new 'Customer invoice contact' (not from the original customer linked to the order).

### Steps to reproduce the behavior

1. Get two third parties with different VAT numbers (**ThirdParty1** & **ThirdParty2**)
2. Create a new order and select **ThirdParty1** as customer
3. In the sales order sheet, go to 'Contacts/Adresses' tab
4. Select **ThirdParty2** and set 'Customer invoice contact' in the 'contact type' dropdown
5. Click on add
6. Back on the sales order sheet, click on 'Create Invoice', then 'Create draft'
7. Generate the pdf file
8. in the recipient field, the contact address is correct (corresponding to **ThirdParty2**), but the VAT number displayed is the one from **ThirdParty1**)

**Comment by milenmk** [comment]
Not a bug.

The field says "Customer invoice contact" so it's natural, if the customer is ThirdParty One the contact belongs to it, not ThirdParty Two.

On the other hand, adding invoice contact changes only the info in the customer box at the top i.e. adds the contact name and changes the address/phone with those of the contact. Adding a contact does not interfere with the VAT number in any way.

Why should VAT change on contact adding, when the contact itself does not have a VAT number?

And if you issue an invoice to ThirdParty One with a VAT number that does not belong to this company, I think this is not legal or at least makes the invoice incorrect. How do you expect a company to accept an invoice with the wrong VAT number?

**Comment by eldy** [comment]
I confirm, the contact must defin the address or email. But thevat must remain the one of the thirdparty. This is a legal requirement. If you need to invoice to another vaat, it means invoice must be done on another thirdparty.
