### ISSUE TITLE
Locking language to last used value when generating PDF

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#23195]
### Feature Request

When working with documents like invoices etc. I would like that the chosen PDF language reamin at the last set value until changed.

### Use case

When generating a PDF from an invoice, order or price proposal or other similar, the choosen language goes back to default value as soon as anything is changed, and the wanted language must be set again.

It is possible to change document modle and language as seen on the below image. The document model remain on the set value until changed, but the language value goes back to the defaul value (in my case French) as soon as the card is saved or any other action is taken, like sending an email etc.

![1](https://user-images.githubusercontent.com/24247236/207092997-e08c7fe7-fdb3-4a3a-9a3f-bf42b86a6a44.jpg)

**Comment by milenmk** [comment]
Add default language to the customer. This way, all PDFs will be generated in the language assigned to the customer and you won't have to change it every time.

**Comment by hasse-basse** [comment]
Aha !

Thanks!
