### ISSUE TITLE
Editing an existing third party - Parent company is removed on save

### ISSUE THREAD

**Issue by mattcole-42** [Dolibarr/dolibarr#23202]
### Bug

When editing an existing third party the parent company is removed when saved, as the edit form has no field for parent company.

Version used Dolibarr 16.0.3

### Expected and actual behavior

Expected
The non edited fields including parent company would remain untouched

Actual:
the third party was saved, however the parent company was removed.

### Steps to reproduce the behavior

Pre-Requisite:
Third party exists with a parent company linked.

Steps:
Open Third Party
select modify
change any field
save

**Comment by milenmk** [comment]
Confirmed. I'll make a fix.

Same bug is on v17 also.
