### ISSUE TITLE
Impossible to delete multiples products

### ISSUE THREAD

**Issue by Franckapik** [Dolibarr/dolibarr#23215]
### Bug

when several products are selected with another left empty in the list, it seems that the products in database are not deleted after confirming the deletion ...

![image](https://user-images.githubusercontent.com/21478769/207541231-8befb238-929d-4acc-8da5-d5f0c63314e0.png)

### Environment Version

16.0.0

### Environment OS

Linus

### Environment Web server

Apache

**Comment by Franckapik** [comment]
Oh sorry it seems that we should probably delete variants before the parent products ? 
That's a shame to not have advertissement for this is the Dolibarr UI ....

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 16.0.3
