### ISSUE TITLE
No contacts selection by tag in the emailing module 

### ISSUE THREAD

**Issue by Larsene** [Dolibarr/dolibarr#23238]
### Bug

Hi,

Since this version, i encounter an error from the emailing module. When my users tries to add emails to recipients, selecting them by tags, this is not working.

![image_2022-12-15_155854285](https://user-images.githubusercontent.com/8544729/207893560-327b654b-7ef5-4204-ab2a-ef772efd70fb.png)

### Environment Version

16.0.3

### Environment OS

 Debian GNU/Linux 10 (buster)

### Environment Web server

apache 2.41

### Environment PHP

7.4.33

### Environment Database

mariadb 10.5

### Environment URL(s)

[dolibarr dir]/comm/mailing/cibles.php?*****

### Expected and actual behavior

expected : after selecting contacts by tags and clicking to "add", the contact emails were added to the emailing recipients

actual : no contact added.

### Steps to reproduce the behavior

1- create a new emailing
2- add recipients from the recipient page : select contact by tag and choose the right tag (the number of recipients corresponding to the tag is indicated between commas
3- clic the add button

### Attached files

![image](https://user-images.githubusercontent.com/8544729/207896843-197e7994-a10a-4b1e-b825-f4de45c07da6.png)

**Comment by IC-Ilies** [comment]
Hello, i'm working on this fix but i just wanted to remind you that you selected a default language and that the thirdparties linked with this tag might not have a default language. 

However, i also notice a bug if nothing is selected as default language as filter criteria.

**Comment by comaiteseb** [comment]
Hi, I solve this bug in the pull request [23413]( https://github.com/Dolibarr/dolibarr/pull/23413)
This is due to language filter
