### ISSUE TITLE
Incorrect VAT application

### ISSUE THREAD

**Issue by fgarciapatino** [Dolibarr/dolibarr#23235]
### Bug

When creating a commande from a customer card, VAT is applied even when the customer is defined with not to use VAT

### Environment Version

14.0.2

### Environment OS

Linux monvacloud 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64

### Environment Web server

Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.21

### Environment PHP

7.4.21

### Environment Database

5.5.5-10.2.39-MariaDB

### Expected and actual behavior

Expected: no VAT applied
Actual: VAT is applied

### Steps to reproduce the behavior

Create an Order from customer card with having not VAT defined for the customer

**Comment by milenmk** [comment]
Cannot reproduce. Tested on 14.0.4 and it works as expected - no VAT applied. try to upgrade your Dolibarr. The latest version is 16.0.3
