### ISSUE TITLE
Prices not updated when external user (client) create a propal or command

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#23248]
### Bug

I just found (and hope to have resolved) a quite tricky bug:
In one of my projects, we allow some clients to connect to Dolibarr to create themselves their commands
They can add lines to the command, but if they choose a predefined product or service, its price is not copied in #price_ht input
A dive in the code shows that /core/tpl/objectline_create.tpl.php make an ajax call to /product/ajax/products.php
In this file line ~68 (65 in dev branch)
`restrictedArea($user, 'produit|service', 0, 'product&product');`
doesnt allow access to external users, and the ajax call throw an error which in not logged :-\
(because of line ~320 
`if (!empty($user->socid) && !empty($conf->global->MAIN_MODULES_FOR_EXTERNAL) && !in_array($featureforlistofmodule, $listofmodules)) {	// If limits on modules for external users, module must be into list of modules for external users`
in /core/lib/security.lib.php)

I suggest after tests to change line ~68 in /product/ajax/products.php
to
`restrictedArea($user, 'produit|service|commande|propal', 0, 'product&product');`

### Environment Version

All including dev

**Comment by vmaury** [comment]
Waiting this bug corrected, its possible to circumvent to it by adding this lines
in actions_xxxx.class.php of a module, method doAction :
```
if ((get_class($object) == 'Commande' || get_class($object) == 'Propal') && $user->socid >0) {
	$conf->global->MAIN_MODULES_FOR_EXTERNAL = 'product,service';
}
```

**Comment by milenmk** [comment]
As I see I think this is a permission issue. Do those external users have permission to "read" products? If they don't have permission this may be the issue, because this is what the restriction you've mentioned is about.

**Comment by vmaury** [comment]
No, because I don't want external users to see (all) the products. And now when they're creating a new order, they see the select with the product they're able to buy. But the price of the product is not updated when it's selected, that's the bug

**Comment by vmaury** [comment]
And If you dive in the code like I did, you'll see (in  in /core/lib/security.lib.php) that if you want the external users to (directly) see products and services, you're obliged to set the global conf var $conf->global->MAIN_MODULES_FOR_EXTERNAL and that's not secure !

**Comment by vmaury** [comment]
I add a pull request to solve this
