### ISSUE TITLE
Bug: RSS feeds don't update

### ISSUE THREAD

**Issue by m10ust** [Dolibarr/dolibarr#23258]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1
- **URL(s)**: /index.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Report

We have several RSS feeds configured and they stopped updating months ago...

**Comment by m10ust** [comment]
https://fsiec.with4.dolicloud.com

no WWW.

**Comment by ksar-ksar** [comment]
Hello,

This is not clear what is your question exactly and it seems that you are using Dolicloud, could you first ask them ?

**Comment by m10ust** [comment]
We have several RSS feeds configured, and they stopped updating months ago...
