### ISSUE TITLE
Allow Negative Stock Option is ignored

### ISSUE THREAD

**Issue by Basti-Fantasti** [Dolibarr/dolibarr#23308]
### Bug

In the stock management I have set the option to allow negative amounts for products.
In past versions of Dolibarr this was working without issues.
So some products in our stock have a current actual amount of -10 or -20 - which is fine and expected.
But now in the 2 or 3 latest 16.0.x Dolibarr versions this is not working anymore.
When the stock amount is 0 or negative I can not create a delivery anymore. 
I always get the error that there's not enough of each product in question in stock.

### Environment Version

16.0.x

### Environment OS

ubuntu 20.04

### Environment Web server

apache

### Environment PHP

7.4.3

### Environment Database

mysql 8.x

### Expected and actual behavior

**Expected:** Amount in stock is ignored as before when option is enabled accordingly

**Actual:** Error message coming up, showing that the delivery can not be created due to amount of products in stock

### Steps to reproduce the behavior

- Create an OC containing a product
- Create a delivery
- try to add the products for delivery from stock with an actual amount of 0 or less

**Comment by Basti-Fantasti** [comment]
This issue is still present in Dolibarr v17.0.x

**Comment by inoveaconseil** [comment]
I can't reproduce in 18.0.3
