### ISSUE TITLE
Missing Dashboard after migration dolibarr windows 10 22h 2 version to Linux Ubuntu 22.04 server version

### ISSUE THREAD

**Issue by YhveSt** [Dolibarr/dolibarr#23326]
### Bug

After try migrate Dolibarr to Linux version; My dashboard missing displaying
dolibarr version 16.0.1

### Environment Version

16.0.1

### Environment OS

Ubuntu 22.04

### Environment Web server

Apache

### Environment PHP

8

### Environment Database

MariaDB

**Comment by mlhostis** [comment]
error in main.inc.php => replace chart.min.js by Chart.min.js on line 1725

**Comment by emheyarssi** [comment]
Linux is case sensitive. For a migration to linux, reinstall Dolibarr from scratch is better. Keep only the documents folder and the database. Of course, make a backup before you start the procedure.

**Comment by mlhostis** [comment]
yes of course by there was a case sensitive bug on v16.0.3 in main.inc.php

**Comment by YhveSt** [comment]
Thx for your answers.
I do this change => replace chart.min.js by Chart.min.js on line 1725, but the result is the same.

**Comment by ksar-ksar** [comment]
Hello,

Can you investigate what do you have on` /htdocs/includes/nnnick` folder ?
https://github.com/Dolibarr/dolibarr/tree/develop/htdocs/includes/nnnick

**Comment by mlhostis** [comment]
thanks, 
updage on windows doesn't rename files and then the copy to linux raise de case sensitive problem
on my side it is now ok without modifying main.inc

**Comment by ksar-ksar** [comment]
Perfect!
