### ISSUE TITLE
Nested projects

### ISSUE THREAD

**Issue by mschamp** [Dolibarr/dolibarr#23331]
### Feature Request

For a project that consists of multiple sub projects, it would be a nice feature to be able to assign a 'parent' project.
When loading the parent project, the card and overview screen give a total overview including the status of the child projects.
This way, more structure can be added.

**Comment by JoAnMaFe** [comment]
This would certainly be a very interesting feature.
It should be accompanied by appropriate GANTT diagrams.

**Comment by edupulpillo** [comment]
the feature is not present in v 19.0.0

**Comment by JonBendtsen** [comment]
In case anyone wonders how to enable this feature, then see this comment

https://github.com/Dolibarr/dolibarr/pull/24856#issuecomment-2213513998
