### ISSUE TITLE
Encoding issues in Serbian language for PDF outputs

### ISSUE THREAD

**Issue by ymollard** [Dolibarr/dolibarr#23356]
### Bug

In Serbian language (and maybe other ones?) it looks like the output PDF files, such as, here, an invoice, meet encoding troubles:

For instance, see the "already paid" table here under, that should be `Plaćanje već izvršeno`:

![image](https://user-images.githubusercontent.com/3295098/209703445-cb629e90-52d5-49b4-8eb9-e91fed58c6ce.png)

In this example my Dolibarr 16.0.3 is configured in French, but I selected Serbian only for the PDF generation.

### Environment Version

16.0.3

### Environment PHP

8.1

### Environment Database

MySQL

**Comment by milenmk** [comment]
Can you try setting in `Home > Setup > Other` option `MAIN_PDF_FORCE_FONT` with the value `DejaVuSans` and try again?

![Screenshot_1](https://user-images.githubusercontent.com/4587305/209804959-93bcc9cd-fcc4-4d25-a232-f27ab765dad7.png)

**Comment by ymollard** [comment]
Thanks it works very well @milenmk! 

How can we improve this? Should we make this font change automatic for some languages? Or at least inform the user about this trick, in a ℹ️ bubble close to the "Generate" button?

**Comment by milenmk** [comment]
All those options can be found [HERE](https://wiki.dolibarr.org/index.php?title=Setup_Other). However, they are meant for experienced users, thus they are not propagandised freely.

**Comment by ymollard** [comment]
Yeah, but producing a valid PDF file in the language of your client should not be reserved to experienced users, that's why I was proposing options integrated to the UI.
