### ISSUE TITLE
Suppression des lignes dans le grand livre

### ISSUE THREAD

**Issue by nagoz** [Dolibarr/dolibarr#23358]
### Feature Request

Bonjour,
j'essaye de réinitialiser le grand livre pour remettre les écritures comptables dedans suite à des erreurs.
En regardant le code, je vois les lignes suivantes dans les fichiers htdocs/accountancy/bookkeeping/listbyaccount.php et listbysubaccount.php :
// TODO Replace this with mass delete 
//if ($user->rights->accounting->mouvements->supprimer_tous) {
//	print '<div class="tabsAction tabsActionNoBottom">'."\n";
//	print '<a class="butActionDelete" name="button_delmvt" href="'.$_SERVER["PHP_SELF"].'?action=delbookkeepingyear&token='.newToken().($param ? '&'.$param : '').'">'.$langs->trans("DeleteMvt").'</a>';
//	print '</div>';

Va t il y avoir une mise à jour de cette partie ?

**Comment by emheyarssi** [comment]
Bonjour, veuillez utiliser le forum pour ce genre de questions. Merci

**Comment by aspangaro** [comment]
Oui, il y a eu une mise à jour de cette partie à partir de la v16 de Dolibarr.
Nous utilisons les actions en masse désormais pour la cohérence de l'interface.
