### ISSUE TITLE
Bug: API REST for SupplierPrices can't update Vendor SKU

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#23357]
### Bug

If i change the Vendor SKU over the REST API ("ref_fourn"), it creates a new price.

I think the problem is the combination of Add & Update in the POST Statement.
![image](https://user-images.githubusercontent.com/78662388/209704341-8f1c79fa-d30f-419d-8b30-44d81ff191f6.png)

I think it's not a clean/good implementation.
Also the POST Statement has a different Modelbase.

What is the correct way to clean it?

### Expected and actual behavior

Actual behavior:
If i change the Vendor SKU over the REST API ("ref_fourn"), it creates a new "price".

Expected behavior:
If i change the Vendor SKU over the REST API ("ref_fourn"), the "price" are updateing.

**Comment by Yamilestebangarcia** [comment]
Hello,
Could you tell me how to activate the rest api.
I have tried generating the api key but when I go to
 http://dolibarr/api/index.php/explorer

and I put the api key I get the error "failed to parse JSON/YAML response"

thank you
