### ISSUE TITLE
Création de contrat - montant disparaît sur la première saisie.

### ISSUE THREAD

**Issue by jimmygruau** [Dolibarr/dolibarr#23361]
### Bug

Bonjour, 
Lors de la création d'un contrat, lorsque je sélectionne un service prédéfini et que je modifie son P.U HT, en cliquant sur enregistrer, la modification disparaît, et il faut que je le fasse une deuxième fois pour que cela fonctionne.

### Environment Version

16.0.3

### Environment OS

Ubuntu Server v20.04.5 LTS

### Environment Web server

Apache2

### Environment PHP

v7.4

### Environment Database

MariaDB Server v8

**Comment by ksar-ksar** [comment]
Hello,

All the issues should be in English on GitHub.

**Comment by inoveaconseil** [comment]
I can't reproduce in 16.0.5
