### ISSUE TITLE
Can't create a product with Ref ending by equal sign =

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#23372]
### Bug

Hello,
I want to create a product with a reference such as  SFP-10G-SR= in the field Ref.
But Dolibarr replaces the sign = (equal) with a _ (underscore)
The company Cisco uses an equal sign at the end of their products for spare parts.
Regards

### Environment Version

16.0.3

**Comment by ksar-ksar** [comment]
Hello,

This is one of the characters that can't be accepted by Dolibarr, you can't pass a '=' on GET for exemple.

**Comment by mikygee** [comment]
Hello Ksar,

I understand the problem, but the value can't be encoded ?
I suppose the problem is the same if I use an exclamation mark or a slash...

I tried to create tiers= and it works
![image](https://user-images.githubusercontent.com/2222550/210261278-e39dcab8-1765-4ab2-86bd-e614ef127870.png)
So the Tiers module and the product module don't behave the same way.

![image](https://user-images.githubusercontent.com/2222550/210261729-110eb456-87e9-4ef4-bec1-6b5f0f03fe41.png)

**Comment by eldy** [comment]
Yes, encoding is possible but it has a lot of side effect. Encoding can be done once, but need of decoding must be done everywhere and if forgotten, introduce security vulnerabilities. As the need to have special characters = into a ref is very not common, we preferred to choose to replace them automatically and not allow them.
The annoyance with replacing the = by _ is very much lower than the annoyance we have on security if we allow special chars, this is why we prefer keeping this as it is.
