### ISSUE TITLE
unable to create anything via post

### ISSUE THREAD

**Issue by Justin-Jordan** [Dolibarr/dolibarr#23374]
### Bug

For unknown reason, I am not able to create any entity by using create action. The only thing I know is that I saw a warning saying that Post request on create action was disabled.

I look a long time for a solution but I found nothiing.  The method I found for that is to change the action in the url parameters.  I change "create" by "add".

I have to problem to edit an entity. When I try to create one, the page just reload with no changes, it does not create the entity.

### Environment Version

16.03

### Environment OS

ubuntu 20.4

### Environment Web server

caddy server

### Environment PHP

php 8.1

### Environment Database

mariadb

### Expected and actual behavior

When I click to create a new entity i create it. But when I click it just reload the page.

**Comment by ksar-ksar** [comment]
Hello,

Entity modification is possible only with multi company module : You should ask the Multi Company module developer

**Comment by Justin-Jordan** [comment]
For example, I am not able to create a tier without change the action to "add"
