### ISSUE TITLE
Bug: Bulle explicative du modele mercure dans module facture contient des balises HTML

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#23394]
### Bug

Version: 16.0.3

Hello,

In the Facture configuration thumbnail Divers there's a template named mercure.
When I want to dispplay the information help it's not easily readable and it containts HTML.
The applies for all 4 fields.

![image](https://user-images.githubusercontent.com/2222550/210294100-befae2cc-99b0-4e11-a576-23ad86a82dd0.png)

Regards

### Environment Version

16.0.3

**Comment by ksar-ksar** [comment]
Hello,

I can't reproduce it on my installation
![screen](https://user-images.githubusercontent.com/35605507/210342451-bb064ae9-6d1d-49ea-a595-16847fb2e3f6.png)

**Comment by mikygee** [comment]
Hello Ksar,
I checked on 18.0.0-alpha and I don't see it. On my 15.0.3 instance I don't see the problem also.
So I close this issue, until I find if there's a side effect leading to this behavior.
Regards
