### ISSUE TITLE
Bug: BOM 'Create' View are broken (to much content...)

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#23393]
### Bug

![image](https://user-images.githubusercontent.com/78662388/210274644-5c3ee183-2640-4ed8-888c-0af3a7395e1c.png)

### Environment Version

18

**Comment by ksar-ksar** [comment]
Hello,

What is your dolibarr version ?
I do not have problem on V16.0.3

**Comment by Humml87** [comment]
Hello,
this is in the develop Branch (v18).

**Comment by ksar-ksar** [comment]
Hello,

As far as I know, bug reports are for stable version or during Dolibarr code freeze.
Not for developp
