### ISSUE TITLE
Direct Printing not working anymore 

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#23399]
### Bug

Direct Printing stopped working in development branch end of december.

The List of Printers is now empty and the button to add a printer does not shown.

Printing with the small Printer Icom in an Invoice:
/dolibarr/compta/facture/card.php?facid=1343&action=print_file&token=d793a5dda770f486004ff38d86fcb353&printer=facture&file=RE2023-01103%2FRE2023-01103.pdf&entity=1&page_y=495.5555725097656

shows Error 500

Disabling / reenabling the Modul did not help.

### Environment Version

18.0.0 alpha

### Environment OS

Debian Linux

### Environment Web server

Apache2

### Environment PHP

7.4

### Steps to reproduce the behavior

try to "direct print"
try to add a direct printer

**Comment by ksar-ksar** [comment]
Hello,

As far as I know, bug reports are for stable version or during Dolibarr code freeze.
Not for developp version !

**Comment by mwelters** [comment]
Ok, sorry.
I did not find the commit which maybe caused this problem, so I cannot contact the autor of the commit. 
Shall I close this  ?

**Comment by mwelters** [comment]
The Issue turned out to be an interaction of the Oauth Module with expired Token.
Diabling Oauth Module brought back the Direct Printing Functionality
