### ISSUE TITLE
Bug: parent account output should be the parent account number and not the rowid

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#23406]
### Bug

Reopen #22265 

Tested on version: Version 15.0.3, Version 16.0.3, Version 18.0.0-alpha

Hello,

When I'm importing an item in the plan comptable, the parent id is not imported
![image](https://user-images.githubusercontent.com/2222550/210468958-c75514fb-b067-4678-a717-3f31b8b25738.png)
![image](https://user-images.githubusercontent.com/2222550/210468973-c9d7a4a0-8ba4-4823-9646-d315e62c1419.png)

And when I'm in the importing process, I do have the parent account number
![image](https://user-images.githubusercontent.com/2222550/210468997-2cb4797e-b724-41e9-b23a-0a6cc186da5e.png)
And it doesn't work because for the parent account number field, the rowid is expected by dolibarr code instead of the parent account number.

The problem is that if I want to prepare an import file, I'm not supposed to know the rowid which is a data internal to dolibarr. As a user, I'm supposed to know the parent account number the same way we create a new input in GUI
![image](https://user-images.githubusercontent.com/2222550/210469032-55ddd6df-2322-4ade-a058-42eeb65f890c.png)

Regards

### Environment Version

15.0.3,16.0.3,18.0.0-alpha

**Comment by mikygee** [comment]
The fix that was supposed to fix this problem seems to be related with the export #22263 (other problem that was really fixed) but not related with the import.
https://github.com/Dolibarr/dolibarr/commit/3fdd34400ff56e922ef729135a917b9b38ad3f95

**Comment by mikygee** [comment]
La ligne d'import à reinjecter est
`PCG99-BASE,62513061,Frais Repas 10% - TEST,62,,EXPENSE,1,`

**Comment by eldy** [comment]
Hi. When i look at exemple for the import file (when generating the sample or into tooltip of the field), i see the example can be
ref:123 or id:123
The field accept both an id and the code (ref). But the import process don't know if you provide an id or code so it assumes it is an id (the default). To help the import process, try to use ref:value as value for your parent account. So in your example:
"ref:62"
Is it better that way ?

**Comment by mikygee** [comment]
Hello Laurent,

Yes indeed, the workaround works as expected
`PCG99-BASE,625130612,Frais Repas 10% - TEST,ref:62,,EXPENSE,1,`

After the import (version 16.0.3), everything is correct
![image](https://user-images.githubusercontent.com/2222550/211448321-cf000eb2-1e0d-492b-86ab-7af761e328b6.png)

In my opinion, if no ref or id is specified then ref: should be considered as a default behavior.
In other words, if the imported file contains
`PCG99-BASE,625130612,Frais Repas 10% - TEST,62,,EXPENSE,1,`
it should be treated the same way as
`PCG99-BASE,625130612,Frais Repas 10% - TEST,ref:62,,EXPENSE,1,`

and not like
`PCG99-BASE,625130612,Frais Repas 10% - TEST,id:62,,EXPENSE,1,`

It's even more true considering that the Plan comptable is now exported with the Compte père and not the id of the compte père.
https://github.com/Dolibarr/dolibarr/issues/22263
It make sense when you want to export and reimport using the same file.

Thank you again for having a look at my request.

**Comment by AurelienBISOTTI** [comment]
Then it's more a documentation improvement that is needed and not a bug ?
Can we close the ticket ?

**Comment by mikygee** [comment]
Hello Aurélien,
Yes as long as there's a working solution, it's ok.
It should be written in the documentation.
