### ISSUE TITLE
Wrong database superuser during installation with PostgreSQL

### ISSUE THREAD

**Issue by rmaziere** [Dolibarr/dolibarr#23428]
### Bug

There is a problem during the installation for a new deployment when you choose PostgreSQL as DBMS.
I've selected psql as db_type in the form but the app try to connect to Postgresql with root.

### Environment Version

16.0.3

### Environment OS

Debian

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

Postgresql 13

### Environment URL(s)

http://127.0.0.1/dolibarr/install/fileconf.php

### Steps to reproduce the behavior

During the installation process on http://127.0.0.1/dolibarr/install/fileconf.php I selected psql as db_type.
When you do that, the db_user_root input is updated with "postgres", BUT on the next page, I have an error message about the db connexion.
In the postgresql logs I have : 
``log
root@postgres FATAL:  password authentication failed for user "root"
``

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case for newer Dolibarr versions ?

**Comment by rmaziere** [comment]
Hello,
I can't answer. I didn't test this new version.
