### ISSUE TITLE
Group social networks field on a thirdparty creation into one link "Social networks..."

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#23436]
### Feature Request

On creation of a thirdparty:
Group social networks field on a thirdparty creation into one link "Social networks..."
Clicking on link show all social networks fields under the link, and change text into "Hide social networks links..."

Next step is saving a cookie called DOLUSER_SOCIALNETWORKS_SHOW when links are shown or not so next time, the links are automatically shown or hidden depending on last situation.

### Suggested implementation

See example of show/hide link into the page "Backup database" to show/hide advanced option

**Comment by emheyarssi** [comment]
Hi, I would like to take this issue.

Is anyone else currently working on it?

Because I can't self-assign.

**Comment by eldy** [comment]
I have merged recently a PR about this feature. From you i think. So i close the issue.

**Comment by emheyarssi** [comment]
> I have merged recently a PR about this feature. From you i think. So i close the issue.

Yes, you've right.
It still for me to add the translation like you indicated me in the #23583 thread. 
Since you closed this issue and merge my commit I don't know how to push this translation. Should I open a new pull request?

**Comment by eldy** [comment]
> > I have merged recently a PR about this feature. From you i think. So i close the issue.
> 
> Yes, you've right.
> It still for me to add the translation like you indicated me in the #23583 thread. 
> Since you closed this issue and merge my commit I don't know how to push this translation. Should I open a new pull request? 

Yes, just create a new PR...

**Comment by emheyarssi** [comment]
> > > I have merged recently a PR about this feature. From you i think. So i close the issue.
> > 
> > 
> > Yes, you've right.
> > It still for me to add the translation like you indicated me in the #23583 thread.
> > Since you closed this issue and merge my commit I don't know how to push this translation. Should I open a new pull request?
> 
> Yes, just create a new PR...

Thank you. Done.
