### ISSUE TITLE
Feature request - Group Sales order per customer

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#23431]
### Feature Request

When a customer order multiple times per day and the delivery is only once a week, the warehouse should be able to "merge" all orders into a signle one. 

### Use case

Customer order 10 orders a day and the delivery & preparation of the goods only occurs at the end of the week.
This will allow to generate a shipment file based on one order and not 70 wich is a mess for the delivery team (10 orders x 7 days)

### Suggested implementation

On the list of Sales order, add a mass option that allow to "merge" the multiple sales order (from the same customer) and create one big sales order.

**Comment by daxitsolutions** [comment]
Still a feature request

**Comment by JonBendtsen** [comment]
@daxitsolutions  how do your customers order? If using the API why can't you just add more lines to an existing order?

How would you think a merge of 2 distinct orders should handle the situations where the orders are not in the same status?

What if they have a different thirdparty contact?

What if the orders does not have the same sale representative ? (some Bonus might be wrong)?


Who should be allowed to merge an order? which permissions are needed?

What if the sum of all these small orders exceed a treshold for how much credit any given customer can be granted?

**Comment by daxitsolutions** [comment]
Hello @JonBendtsen very good questions, this may complicate the merge of 2+ orders. 
This feature request can be canceled
