### ISSUE TITLE
Can’t see preview button in expense report line

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#23430]
### Bug

I have upgraded to 15.0.3 from 14.0.3 . And the other dolibarr is upgrade to v16.0.3 from 15.0.3 .
And i notice the expense report line should have a preview button when i attach a pdf file with it .
But i can’t find it .
![image](https://user-images.githubusercontent.com/78349579/210922341-91d7178b-eb89-4714-bf73-411f8c7539d2.png)

### Environment Version

v15.0.3 and v16.0.3

### Environment OS

Deian 10

### Environment Web server

 Apache/2.4.38 Apache/2.4.41 

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.3.36

### Environment URL(s)

expensereport/card.php?id=5

### Expected and actual behavior

should can preview each pdf file .

**Comment by rqi14** [comment]
Confirm this is not fixed until now (v18)
