### ISSUE TITLE
On thirdparty creation / edition, replace the combo yes/no of "sales tax is used"

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#23437]
### Feature Request

Replace the selection into a combo list than need 2 click by a checkbox that need 1 click for the field 
"Use sale tax"
"Use localtax 2"     (you need to enable use second tax on the setup of the company to see it)
"Use localtax 3"     (you need to enable use second tax on the setup of the company to see it)

- In create form

- In update form

- In view form, replace the 3 lines into one.

**Comment by aspangaro** [comment]
I'm taking this feature request
