### ISSUE TITLE
PHP 8.2: Dynamic Properties are deprecated

### ISSUE THREAD

**Issue by frederic34** [Dolibarr/dolibarr#23433]
https://github.com/Dolibarr/dolibarr/pull/23464
https://github.com/Dolibarr/dolibarr/pull/23500
https://github.com/Dolibarr/dolibarr/pull/23625
https://github.com/Dolibarr/dolibarr/pull/23627

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/23500

**Comment by ksar-ksar** [comment]
Hello Frederic,

Seems that all your PR has been merged.
Could be closed?

**Comment by frederic34** [comment]
@ksar-ksar yes we can
