### ISSUE TITLE
For some sales orders the shipping can not be made because of fatal error

### ISSUE THREAD

**Issue by vrmaurice** [Dolibarr/dolibarr#23447]
### Bug

When creating a shipment from sales order sometimes there is no button to create the shipping. Other sales orders can create the shipping.

> Fatal error: Uncaught TypeError: array_push(): Argument #1 ($array) must be of type array, int given in /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php:4849 Stack trace: #0 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php(4849): array_push(8, '899') #1 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php(4849): Product->getChildsArbo('376', 0, 2, 8) #2 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php(4875): Product->getChildsArbo('386') #3 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/expedition/shipment.php(815): Product->get_sousproduits_arbo() #4 {main} thrown in /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php on line 4849

### Environment Version

16

### Environment OS

Ubuntu Server

### Environment Web server

	Apache

### Environment PHP

8

### Environment Database

MySQL or MariaDB 10.3.37-MariaDB-1:10.3.37+maria~ubu2004

### Expected and actual behavior

Expected : 
a list of all items in the order is displayed
Selection of stock location present
Button to create shipping present

Actual : 
List of items stuck at first line
Selection of stock location not present
Button to create shipping not present
Fatal error

> Fatal error: Uncaught TypeError: array_push(): Argument #1 ($array) must be of type array, int given in /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php:4849 Stack trace: #0 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php(4849): array_push(8, '899') #1 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php(4849): Product->getChildsArbo('376', 0, 2, 8) #2 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php(4875): Product->getChildsArbo('386') #3 /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/expedition/shipment.php(815): Product->get_sousproduits_arbo() #4 {main} thrown in /customers/3/3/0/metron-technics.be/httpd.www/erp/htdocs/product/class/product.class.php on line 4849

### Attached files

![Untitled-2](https://user-images.githubusercontent.com/75036859/211190640-ee396de7-66e2-4ca5-af01-4ffc40dbdf06.jpg)

**Comment by vrmaurice** [comment]
This seems to work:
In file `htdocs\product\class - kopie\product.class.php` on line 4849 to 4850, paste this code.

`array_push($parents, $rec['rowid']);
$listofchilds = $this->getChildsArbo($rec['rowid'], 0, $level + 1, $parents);`

**Comment by ksar-ksar** [comment]
Hello,

Dolibarr V16 was not compatible with PHP V8.
Have you tries with V18 ?
