### ISSUE TITLE
Discussion / Logical Bug: Limited duration for Services and also for Products

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#23449]
### Feature Request

Can also set a limited duration for Products.

### Use case

In some (in our company in the most cases) business events its necessary to deliver also products to a different date.

### Suggested implementation

![image](https://user-images.githubusercontent.com/78662388/211195541-9a4f06fe-24b6-459e-af87-43feb00ff99e.png)

### Suggested steps

Variant 1:
Remove all if-statements where is requesting "its a service...".

Variant 2:
Integrate a configuration variable to say "PRODUCT_LIMITED_DURATION_FOR_PRODUCTS"

---
@eldy: What do you think is the best implementation?

**Comment by dolibit-ut** [comment]
Hello, this "Limited Duration" feature is actually for subscription services 
and not for a targeted delivery date (If I understand your intention right).

But i think it can is also be useful for products - 
e.g. to map seasonal products, product changes or serials/lots or whatever else.

In my opinion it could be the 'simple' variant 1.

**Comment by Humml87** [comment]
Hi, thank you for the feedback.

> (If I understand your intention right)

You right.

> In my opinion it could be the 'simple' variant 1.

i think this variant 1 is good. I can't found problems for this integration.
Then i do it ;-)
