### ISSUE TITLE
missing button creat proposal dolibarr 16.0.3

### ISSUE THREAD

**Issue by said4020** [Dolibarr/dolibarr#23469]
### Bug

Hi,

Can not view create button for a new commercial proposal and it's impossible to modify or see a no validate proposal.

any issue.

thanks

### Environment Version

16.0.3

### Environment OS

5.15.0-48-generic #54-Ubuntu 

### Environment Web server

Apache 2.4.25 x86

### Environment PHP

8.0

### Environment Database

MySQL or MariaDB 5.7.17

### Attached files

![Screenshot 2023-01-09 at 15-44-38 Proposition commerciale - Fiche](https://user-images.githubusercontent.com/122290651/211340153-513d28b8-1011-4fa6-8175-111fd287d96b.png)

**Comment by ksar-ksar** [comment]
Hello,

Try to deactivate/re-activate the module.

It's working for me : 
![image](https://user-images.githubusercontent.com/35605507/211358524-7c8e3d3d-2d45-45c6-8be9-f9d58a73866d.png)

**Comment by ksar-ksar** [comment]
Hello,

It's seems also that you are not using the standard template (eldy), could you try to use it ?

**Comment by said4020** [comment]
Hi Ksar,

Thanks for response, but deactivate/re-activate the module and using the standard template (eldy) same problem.
Creating invoice It's working fine but not for commercial proposal.

i think that the problem it's php 8 compatibility.

**Comment by ksar-ksar** [comment]
If its PHP V8 problem, can you have a look on your hosting logs ?

Thanks.

**Comment by said4020** [comment]
Hi thanks here is hosting log.

[Tue Jan 10 11:43:49.296348 2023] [php:error] [pid 18400:tid 1320] [client 127.0.0.1:56262] PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php:722\nStack trace:\n#0 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php(722): sprintf('Supprimer les l...', '', '', '', '', '')\n#1 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php(684): Translate->transnoentitiesnoconv('SimplyDelete', '', '', '', '', '')\n#2 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\custom\\split\\class\\actions_split.class.php(58): Translate->transnoentities('SimplyDelete')\n#3 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\hookmanager.class.php(283): ActionsSplit->formObjectOptions(Array, Object(Propal), 'create', Object(HookManager))\n#4 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\tpl\\extrafields_add.tpl.php(43): HookManager->executeHooks('formObjectOptio...', Array, Object(Propal), 'create')\n#5 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\card.php(1860): include('C:\\\\Program File...')\n#6 {main}\n  thrown in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php on line 722, referer: http://127.0.0.1/gestion_7/comm/propal/card.php
[Tue Jan 10 11:43:59.237340 2023] [php:error] [pid 18400:tid 1320] [client 127.0.0.1:56267] PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php:722\nStack trace:\n#0 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php(722): sprintf('Supprimer les l...', '', '', '', '', '')\n#1 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php(684): Translate->transnoentitiesnoconv('SimplyDelete', '', '', '', '', '')\n#2 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\custom\\split\\class\\actions_split.class.php(58): Translate->transnoentities('SimplyDelete')\n#3 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\hookmanager.class.php(283): ActionsSplit->formObjectOptions(Array, Object(Propal), 'create', Object(HookManager))\n#4 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\tpl\\extrafields_add.tpl.php(43): HookManager->executeHooks('formObjectOptio...', Array, Object(Propal), 'create')\n#5 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\card.php(1860): include('C:\\\\Program File...')\n#6 {main}\n  thrown in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php on line 722, referer: http://127.0.0.1/gestion_7/comm/propal/card.php?action=create&leftmenu=propals
[Tue Jan 10 11:45:35.817277 2023] [php:warn] [pid 18400:tid 1320] [client 127.0.0.1:56289] PHP Warning:  Undefined array key "val" in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\list.php on line 1852, referer: http://127.0.0.1/gestion_7/comm/propal/card.php
[Tue Jan 10 11:45:35.817277 2023] [php:warn] [pid 18400:tid 1320] [client 127.0.0.1:56289] PHP Warning:  Undefined array key "p.total_ht" in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\list.php on line 1852, referer: http://127.0.0.1/gestion_7/comm/propal/card.php
[Tue Jan 10 11:45:35.817277 2023] [php:warn] [pid 18400:tid 1320] [client 127.0.0.1:56289] PHP Warning:  Undefined array key "p.total_ttc" in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\list.php on line 1874, referer: http://127.0.0.1/gestion_7/comm/propal/card.php
[Tue Jan 10 11:45:39.934337 2023] [php:warn] [pid 18400:tid 1320] [client 127.0.0.1:56289] PHP Warning:  Undefined array key "val" in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\list.php on line 1852, referer: http://127.0.0.1/gestion_7/comm/propal/list.php?leftmenu=propals
[Tue Jan 10 11:45:39.934337 2023] [php:warn] [pid 18400:tid 1320] [client 127.0.0.1:56289] PHP Warning:  Undefined array key "p.total_ht" in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\list.php on line 1852, referer: http://127.0.0.1/gestion_7/comm/propal/list.php?leftmenu=propals
[Tue Jan 10 11:45:39.934337 2023] [php:warn] [pid 18400:tid 1320] [client 127.0.0.1:56289] PHP Warning:  Undefined array key "p.total_ttc" in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\list.php on line 1874, referer: http://127.0.0.1/gestion_7/comm/propal/list.php?leftmenu=propals
[Tue Jan 10 11:45:43.910048 2023] [php:error] [pid 18400:tid 1320] [client 127.0.0.1:56289] PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php:722\nStack trace:\n#0 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php(722): sprintf('Supprimer les l...', '', '', '', '', '')\n#1 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php(684): Translate->transnoentitiesnoconv('SimplyDelete', '', '', '', '', '')\n#2 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\custom\\split\\class\\actions_split.class.php(58): Translate->transnoentities('SimplyDelete')\n#3 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\hookmanager.class.php(283): ActionsSplit->formObjectOptions(Array, Object(Propal), '', Object(HookManager))\n#4 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\tpl\\extrafields_view.tpl.php(55): HookManager->executeHooks('formObjectOptio...', Array, Object(Propal), '')\n#5 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\comm\\propal\\card.php(2608): include('C:\\\\Program File...')\n#6 {main}\n  thrown in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\gestion_7\\core\\class\\translate.class.php on line 722, referer: http://127.0.0.1/gestion_7/comm/propal/list.php?sortfield=p.datep&sortorder=desc&begin=&search_status=&contextpage=proposallist

**Comment by ksar-ksar** [comment]
Hello,

Your issue seems to be due to custom\split\class\actions_split.class.php(58)
It's an external module, try to contact the devlopper

**Comment by said4020** [comment]
Hi,

Thanks a lot, i deactivate the external module it's work fine now.
