### ISSUE TITLE
Choose default mail sender and recipient

### ISSUE THREAD

**Issue by oldu9412** [Dolibarr/dolibarr#23476]
### Feature Request

Choose a default sender in an email template
Choose a default recipient in an email template
It's really annoying not being able to do this. For exemple an sender for customer order, for a supplier order...

And possibly write an email list in an email template (for recipient et sender)/

Thanks
Olivier

**Comment by BB2A-Anthony** [comment]
I fully support you in this feature I had also created an issue but without an answer

#16132
