### ISSUE TITLE
Add PDF generation to ODT document generation

### ISSUE THREAD

**Issue by vpicavet** [Dolibarr/dolibarr#23529]
### Feature Request

The current ODT document generation from an ODT template works very well. We want to use it for commercial proposal generation. However, we do not want to send the ODT document to the prospect, but a PDF rendered from the generated ODT.

This does not seem to be  currently doable. We have to download the generated odt file, render it to pdf locally, re-join the PDF to the commercial proposal and send it to the client. This process is cumbersome and could be fully automated.

### Use case

The following workflow would be great : 
- upload a custom ODT template in the configuration
- create a new commercial proposal
- select the ODT template and generate a "new PDF proposal document from ODT"

Dolibarr generates the ODT commercial proposal, and then generate a PDF from the ODT in the background, and the PDF file is joined to the commercial proposal

- We send the PDF to the prospect

### Suggested implementation

Do the same workflow but behind the scene, convert to PDF.

Libreoffice allows for PDF generation through script / command line with the following command : 

`soffice --convert-to pdf $1 --headless`

**Comment by vpicavet** [comment]
FYI @marc-dll

**Comment by nutsflag** [comment]
Hello @vpicavet,
There is already a feature : https://wiki.dolibarr.org/index.php?title=G%C3%A9n%C3%A9rer_automatiquement_des_documents_PDF_%C3%A0_partir_de_fichier_ODT_avec_Doliwamp

**Comment by vpicavet** [comment]
Wow, great, I did not find it in the documentation, sorry.
