### ISSUE TITLE
v16.0.3 : Unable to update BomLines from the import file

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#23531]
### Bug

From the import "Bill of Materials lines" page 
URL : https://xxxx/imports/import.php?step=2&datatoimport=bom_lines_2&excludefirstline=2&enclosure=%22
The template doesn't include the Bomline ID wich should be used to update lines. 
As of today only creation of lines can be made from the import screen.

### Environment Version

16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

https://xxxx/imports/import.php?step=2&datatoimport=bom_lines_2

### Expected and actual behavior

The template should add a "BOMLINE ID" in order to be able to update the bom lines

**Comment by Hystepik** [comment]
With this fix you can update a Bill of Materials lines with the couple (Bom ID , ProductRef)

**Comment by daxitsolutions** [comment]
Hello @Hystepik thanks for the fix, I will test this asap.

**Comment by daxitsolutions** [comment]
Tested on V16.0.3 - Works like a charm.
