### ISSUE TITLE
[ Invoice ] Credits can be null 

### ISSUE THREAD

**Issue by pierrejego** [Dolibarr/dolibarr#23548]
### Feature Request

As Invoice, credits can be null.

### Use case

For exemple, in our case. 
Society create 0€ invoice to move stock, sometime it's necessary for stock correction to create a credits 0€ to adapt stock mouvement.

### Suggested implementation

Modify file https://github.com/Dolibarr/dolibarr/blob/a074c89960b506e60aa2f7b33c5c8717342a6bae/htdocs/compta/facture/card.php#L325

remove equals for result  
`if ($object->total_ht > 0) {`

### Suggested steps

I will create a PR linked if you think this could be usefull for others.

**Comment by eldy** [comment]
If invoice amount is null, it means you don't need invoice. Why don't you create a simple stock movement or inventory to correct stock ?
Also my understanding here is that you succeed in creating an invoice of 0 ? Do you have also a VAT of 0 ?
