### ISSUE TITLE
Events/Agenda Module: Odd behavior with type of event search filter

### ISSUE THREAD

**Issue by dnutan** [Dolibarr/dolibarr#23563]
### Bug

Wrong text label for manually inserted events (at least for English and some other languages).
Wrong classification of type of event after enabling and disabling the use of event types.

### Environment Version

16.0.3

### Environment OS

Centos 7.9

### Environment Web server

Apache 2.4.6

### Environment PHP

7.3.33

### Environment Database

MariaDB 5.5.68

### Environment URL(s)

/dolibarr/comm

### Expected and actual behavior

Exptected behavior:
 - Different text label for default types of events when "event types" from Dictionaries are not enabled.
 - After enabling and then disabling types of events from module settings, manually inserted events should be classified accordingly.

Actual behavior:
 - Duplicate text label for "event types" when use of event types from Dictionaries is not enabled.
 - After enabling and then disabling types of events from module settings, manually inserted events are internally classified as "Automatically inserted events".

### Steps to reproduce the behavior

With Agenda module settings at default: **"Use events types (managed in menu Setup -> Dictionaries -> Type of agenda events)"**  **not enabled**: Both types of events search filter are shown with the same text label:  **"Automatically inserted events"** instead of one for "Manually inserted events" and another one for "Automatically inserted events", but filter works as expected.
 
Once **"Use events types (managed in menu Setup -> Dictionaries -> Type of agenda events)"**  is **enabled**, then the types of event search filter is populated with more options (from Dictionaries) and works correctly.

If **"Use events types (managed in menu Setup -> Dictionaries -> Type of agenda events)"**  **was enabled and later disabled**, then new events created manually are classified as "Automatically inserted events" and selecting the first option (which I assume is a wrong text label for manually inserted events) the search results returns empty. That happens even with all **"Automatic Filling"** options ticked **off**.

### Attached files

Default types of events (duplicate text label) in Events/Agenda module settings:
![image](https://user-images.githubusercontent.com/15559754/212471401-b7d8402b-f700-47b1-80ce-b713512563ee.png)

Default types of events (duplicate text label) Search Filter:
![image](https://user-images.githubusercontent.com/15559754/212471450-aa4ecf99-324c-4d0e-8016-e65513871cce.png)

**After enabling/disabling Event Types module settings:**

Search filtered by date with all events for a specific day:
![image](https://user-images.githubusercontent.com/15559754/212472552-de5ccf83-7cdb-41c0-8207-336a01d82766.png)

List of results for manually inserted events search filter (wrongly labeled) for the same specific day (not listing the event inserted manually):
![image](https://user-images.githubusercontent.com/15559754/212472577-bb10766d-5128-4ae4-917e-5704192a11eb.png)

List of results for Automatically inserted events search filter for the same specific day (wrongly showing manually inserted event):
![image](https://user-images.githubusercontent.com/15559754/212472603-1181c3f6-dca4-4412-8a7b-4e835b8dd6e6.png)

**Comment by JoAnMaFe** [comment]
The same behaviour also occurs in Windows 10.
with the same MariadB and Apache configuration.
