### ISSUE TITLE
Bug: Missing flag

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#23565]
# Bug
[*That flag seems to be missing : theme/common/flags/xk.png*]

## Environment
- **Version**: 17.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 8.1.14
- **Database**: MySQL or MariaDB 10.3.36-MariaDB-0+deb10u2-log
- **URL(s)**: /custom/ultimatepdf/admin/setup.php?action=edit&id=5

**Comment by frederic34** [comment]
kosovo ? :kosovo:

**Comment by grandoc** [comment]
xk is a temporary, unofficial country code top-level domain for Kosovo

**Comment by frederic34** [comment]
added in v18 https://github.com/Dolibarr/dolibarr/pull/23733

![image](https://user-images.githubusercontent.com/3624836/217102596-9ac2d122-2eb9-4462-888e-f8c5c1653fa5.png)

**Comment by IC-faycal** [comment]
Hello
I can't reproduce, i think is resolve on 17.0.2
