### ISSUE TITLE
v16.0.3 - (CLOSED) Increase real stocks on validation of reception is impossible

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#23606]
### Bug
The stock is never decrease because shipment validation on purshase order if not possible (button not set)

### How to reproduce - Steps
Actual configuration on Stock module : “Increase real stocks on validation of reception”

![image](https://user-images.githubusercontent.com/26635105/212941932-9a2dabe9-e549-45ed-aabe-ab61424d3adc.png)

We use a test product 
![image](https://user-images.githubusercontent.com/26635105/212942034-d00c07a3-adb6-46c7-963c-0ed343f2d4cb.png)
Current stock : 10 

Create a PO with 10x test 
![image](https://user-images.githubusercontent.com/26635105/212942154-a627200b-9a56-4c13-a547-f6e966aee1ed.png)

Validate @ approuve

-> There is no button availavle to validate the receipts of the goods and therefore the stock is never decrease.
![Purchase_order_-_Card](https://user-images.githubusercontent.com/26635105/212942990-8722d615-3ee0-4a3b-a23b-3f073ec89196.png)

### Environment Version

16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

Mysql

**Comment by fappels** [comment]
You still have to 'make order'

**Comment by daxitsolutions** [comment]
not an issue.
