### ISSUE TITLE
change minimum qty on product-supplier price not possible

### ISSUE THREAD

**Issue by fbosman** [Dolibarr/dolibarr#23624]
### Bug

It is not possible to change the minimum qty on a product-supplier-price line.
Is there a specific reason for this?
I know how to solve this, but there must be some reason that this is not possible. Before I submit the pr I want to make sure that I did not miss anything

### Environment Version

>= 14.0.4

### Environment OS

ubuntu

### Environment Web server

apache

### Environment PHP

7.4.13

### Environment Database

mysql

### Expected and actual behavior

one should be able to correct/change the minimum quantity

**Comment by inoveaconseil** [comment]
Yes we have some conflict with the primary key (qty,supplier, ref supplier). You must create an other price for this product.
