### ISSUE TITLE
CSS not loading at all

### ISSUE THREAD

**Issue by jerichoc239** [Dolibarr/dolibarr#23623]
### Bug

All dolibarr pages are suddenly not loading CSS, attmepting to load dolibarr/htdocs/index.php causes the system exception listed below. Restarting the system/apache corrects this issue, but the behaviour is quite strange. See exception and screenshots below

Exception has occurred.
Fatal error: Uncaught TypeError: Unsupported operand types: string - int in /home/jericho/Documents/fig_deploy_platform/htdocs/theme/eldy/global.inc.php:1515
Stack trace:
#0 .../dolibarr/htdocs/theme/eldy/style.css.php(328): require()
#1 {main}
  thrown
![Screenshot from 2023-01-18 11-35-28](https://user-images.githubusercontent.com/8879335/213249033-a74d1ee2-2ea3-419e-b68a-c8e91b148048.png)
![Screenshot from 2023-01-18 11-34-50](https://user-images.githubusercontent.com/8879335/213249034-23719d52-6505-468d-836b-26c5b5f2e7d7.png)
![Screenshot from 2023-01-18 12-14-05](https://user-images.githubusercontent.com/8879335/213249260-9cd87237-6137-4ce7-875b-80e495db4d34.png)

### Environment Version

16.0.3

### Environment OS

Ubuntu 22.04 

### Environment PHP

8.1

### Environment Database

Mysql 

### Expected and actual behavior

I expected CSS to load, CSS is not loading for any pages of dolibarr platform

### Steps to reproduce the behavior

Seems to happen when a machine is restarted or dolibarr has been not been used since the day prior

### Attached files

[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/10448914/dolibarr.log)

**Comment by hansemschnokeloch** [comment]
This bug is fixed with https://github.com/Dolibarr/dolibarr/commit/6734f7a6aa090c53227bb334efb1e68124c38968

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
