### ISSUE TITLE
POS Issues: Categories and Ticket Printing

### ISSUE THREAD

**Issue by pajariko** [Dolibarr/dolibarr#23630]
### Bug

Hello,

There are 2 problems found:
1) In the POS, when the subcategories are displayed on the right, if the number of subcategories exceeds those that can be displayed, the "arrows" do not work and you cannot move forward. However, if it is about products, they do work.

2) To include more fields within the POS ticket (module-> POS-> printers) some tags like "__THIRDPARTY_NAME__" do not work.

### Environment Version

16.0.3

### Environment OS

Linux

### Environment Web server

LiteSpeed

### Environment PHP

7.4

**Comment by emheyarssi** [comment]
Hello,

all issues should be write in English on Github.

Thanks.

**Comment by pajariko** [comment]
Ok! 
Translated

**Comment by pajariko** [comment]
Hi,

The error is still in the latest version. Any way to fix it? Does it happen to anyone else?

thanks
