### ISSUE TITLE
Unable to find the latest releases on SourceForge

### ISSUE THREAD

**Issue by Pitouflin** [Dolibarr/dolibarr#23632]
### Bug

Hello, I'm trying to use Dolibarr in my company. I already tested an installation process on release 16.0.3-4_all.deb for Debian and I was trying to use it for production today. I'm now unable to find the latest releases on SourceForge.
The folders for releases after 14.0.0 are GONE.
https://sourceforge.net/projects/dolibarr/files/
![image](https://user-images.githubusercontent.com/99023646/213467697-eb6ae834-f6d2-44d2-ae52-b87ff3ecc6c2.png)

### Environment Version

After 14.0.0

**Comment by Pitouflin** [comment]
Also this button will make you downoad the 14.0.0 release instead of the 16.0.1
![image](https://user-images.githubusercontent.com/99023646/213468584-4f7e0e9b-c113-4570-b5b3-6815c4f24f47.png)

**Comment by hasse-basse** [comment]
As far as I can see, they are all there.

https://sourceforge.net/projects/dolibarr/files/Dolibarr%20installer%20for%20Debian-Ubuntu%20%28DoliDeb%29/

Could it be a cashe issue in your browser? Try Ctrl+Space+F5

**Comment by ksar-ksar** [comment]
Hello,

Sourceforge experienced a temporary bug for a fews hours, but now, all ok.
