### ISSUE TITLE
Wrong priority Default value conf and get parameter

### ISSUE THREAD

**Issue by ibuiv** [Dolibarr/dolibarr#23635]
Version : 16, 17 (and older maybe)

## Bug explanation : 
If a default value has been set up on Configuration -> Values/Filters/Sort... it seems to be more important than a get parameter

## To reproduce the bug : 
From a fresh version you can enter these values
 
![image](https://user-images.githubusercontent.com/50403308/213492643-80c0e596-4b4d-4bf8-9db1-7e6f5c5fb49a.png)

And then try to access a creation page for a supplier using the link below 
![image](https://user-images.githubusercontent.com/50403308/213492947-858e50a9-991b-49c9-8b9d-9afe2a2e1b65.png)

The Get parameter type=f is ignored.  

## Expected behaviour :
The Get parameter must be more important and the default choice for the selectors should be considering the get parameter and look at the config if no parameter has been supplied.

P.S. : If nobody manages this, I'll take care of this as soon as I can.

**Comment by ksar-ksar** [comment]
Hello,

Sounds like the expected behavior no ?

**Comment by ibuiv** [comment]
Hello, 
I think it is not intuitive this way. 
Because your administrator decided to have a default value, these links don't do what they announce. 

If you click to new Supplier, you made the choice to create specifically a supplier. And the default value specified by your administrator fill the select form Supplier to No.
