### ISSUE TITLE
Can't repair database if database name has - (hyphen)

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#23643]
### Bug

https://github.com/Dolibarr/dolibarr/blob/7a13ca65b503a8161b73f67d1d47e7a42bbcacd5/htdocs/core/db/mysqli.class.php#L708

![image](https://user-images.githubusercontent.com/7734808/213686716-25bf89ff-571e-44cc-975f-cd5b4d99b8a7.png)

### Expected and actual behavior

Change

```sql
$sql = "SHOW TABLES FROM ".$tmpdatabase." ".$like.";";
```

to

```sql
$sql = "SHOW TABLES FROM `".$tmpdatabase."` ".$like.";";
```

### Steps to reproduce the behavior

Create a database with hyphen or simply try the SQL `SHOW TABLES FROM test-test;` in MySQL.

**Comment by hasse-basse** [comment]
The reccomendation is to not use hyphens in database names, because it might screw things up. I use Virtualmin for my webistes and it never creates a DB name using hyphens, insted it uses underscore and I suppose there is good reason to that. Hyphens should never be used in table and column names.
