### ISSUE TITLE
"Stocks at date" function under Warehouse does not respect the selection of a warehouse

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#23640]
### Bug

"Stocks at date" is a useful function to see what's in stock. However, no matter which value of "Warehouse" you use, the list will return all the stock for all the warehouses instead of the selected warehouse.

Example:
Warehouse 1: 50 items in stock
Warehouse 2: 25 items in stock
Warehouse 3: 25 items in stock

"Stocks at date" with today's date and "Warehouse 3" => 100 items.

![Untitled](https://user-images.githubusercontent.com/11036018/213650245-8e28b60b-d7c0-4b5c-9606-506dcdaf567c.png)

### Environment Version

16

### Environment PHP

8

**Comment by bos4711** [comment]
I found the error.

In `/product/stock/stockatdate.php`, near line 260:
```
if ($fk_warehouse > 0) {
    $sql .= ' LEFT JOIN '.MAIN_DB_PREFIX.'product_stock as ps ON p.rowid = ps.fk_product AND ps.fk_entrepot = '.((int) $fk_warehouse);
}
```

LEFT JOIN is the culprit. When we use RIGHT JOIN the selected warehouse is respected and the list gets populated with proper values.

**Comment by Hystepik** [comment]
It works for me. Are you in the last verion of 16.0.4 ?

**Comment by bos4711** [comment]
I use latest stable version 16.0.3.

**Comment by bos4711** [comment]
Bug is still there in version 17.0.2.

**Comment by bos4711** [comment]
@aspangaro Is the issue fixed, or why did you close?

**Comment by bos4711** [comment]
Bug still exists in v19.

**Comment by bos4711** [comment]
@aspangaro Why did you close this issue? The bug still exist in v19.
