### ISSUE TITLE
(SOLVED) v16.0.3 - List of unpaid invoice displays paid invoices

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#23659]
### Bug

http://XXXXX/compta/facture/list.php?leftmenu=customers_bills_notpaid shows paid invoices 

![Factures_clients](https://user-images.githubusercontent.com/26635105/214097505-09ccb6e2-9a12-46c9-9d1b-0e1c7a9bb78c.png)

### Environment Version

16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

Mysql

### Environment URL(s)

http://XXXXX/compta/facture/list.php?leftmenu=customers_bills_notpaid shows paid invoices 

### Expected and actual behavior

This screen should not display paid invoices

**Comment by Daviid-P** [comment]
The URL is actually `/compta/facture/list.php?leftmenu=customers_bills_notpaid&search_status=1`

`&search_status=1` is what's added when you select **Impayée** in the dropdown and click the magnifying glass.

I've tested on 16.0.3 and it's working fine.

@daxitsolutions can you verify that when you click the menu item **Impayée** the parameter `&search_status=1` gets added?

**Comment by daxitsolutions** [comment]
@Daviid-P 
search_status=1 is set, still the issue : 

![Factures_clients](https://user-images.githubusercontent.com/26635105/214272400-cdf1828b-9523-4606-9424-83930d9125cb.png)

**Comment by Daviid-P** [comment]
@daxitsolutions I can't reproduce, does your `compta/facture/list.php` file have any modification or do you have any hook that might affect the search?

**Comment by daxitsolutions** [comment]
Hello @Daviid-P 
- No hook
- No modification either on the original file

**Comment by Daviid-P** [comment]
I'm out of ideas then, sorry.

**Comment by daxitsolutions** [comment]
It was an error due to a pluggin. 
Thanks for the help @Daviid-P !
