### ISSUE TITLE
Intervention Module Bug with the date

### ISSUE THREAD

**Issue by gomgom42** [Dolibarr/dolibarr#23669]
### Bug

Hi
If I custom date instead date of the day on Intervention Module, i have an error.

Below is a copy about log

`Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Unsupported operand types: string * int in /var/www/vhosts/xxx/www2/core/lib/date.lib.php:210\nStack trace:\n#0 /var/www/vhosts/xxx/www2/fichinter/card.php(595): convertTime2Seconds()\n#1 {main}\n thrown in /var/www/vhosts/xxx/www2/core/lib/date.lib.php on line 210', referer: https:/xxx/fichinter/card.php?id=9&action=editline&token=0b9d8a469e98d309f93fbff91f9ebb3b&line_id=18 `
`

Si réponse en français, cela me convient 

### Environment Version

16.0.3

### Environment OS

Ubuntu 20.04.5 LTS

### Environment PHP

8.0.27

### Environment Database

MariaDB 10.3.37	

### Steps to reproduce the behavior

Ajouter une intervention en choisissant une autre date que celle du jour et valider

**Comment by rueBejo** [comment]
Hello,

This error is coming from PHP 8, it works under PHP 7.4.
This could be solved by modifying /core/lib/date.lib.php.
"convertTime2Seconds" function is waiting for int parameters, empty strings are received, throwing a fatal error in PHP 8.X.
To reproduce the error, simply modify an existing Intervention.
Workaround : change line 210 in  /core/lib/date.lib.php to convert string into int :
`$iResult = (intval($iHours) * 3600) + (intVal($iMinutes) * 60) + intVal($iSeconds);`

Regards,
Bruno

**Comment by gomgom42** [comment]
Still have a 503 error after change line 210 but not dolibarr fault
Back to PHP 7.4 and works fine
