### ISSUE TITLE
ODT template showing unix timestamp instead of human readable date and time

### ISSUE THREAD

**Issue by mpractic** [Dolibarr/dolibarr#23673]
### Bug

I created some templates for proposals an quotes, and some extrafields containing date and time fields.

When generating the odt, those fields are displayed as unix timestamp instead of normal date and time fields.

### Environment Version

16.0.3

### Environment OS

 Ubuntu 20.04.5 LTS

### Environment Web server

Apache/2.4.41 (Ubuntu)

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.3.37-MariaDB-0ubuntu0.20.04.1

**Comment by Daviid-P** [comment]
You have to use `dol_print_date` to format your extrafields, dolibarr does the same when generating odt from a template in their base code.

**Comment by mpractic** [comment]
> 

Thank you! I thought this was a bug, sorry.

I know I can't add this directly to the ODT but I've been looking and I don't know exactly where to put the code to format my extrafields. If I put it on commondocgenerator.class.php won't those changes be lost with the next update?

**Comment by Daviid-P** [comment]
You probably need something like https://wiki.dolibarr.org/index.php?title=Create_an_ODT_document_template#Other_personalized_tags

**Comment by fideliopark** [comment]
I have the same issue and I don't quite get the solution implemented yet.

Can someone be so kind to tell me as concretely as possible:
- What entries I need to make in the odt template.
- which entries have to be made in other files, if any.

In my example it is about an extrafield "startuse" in the module proposals

**Comment by mpractic** [comment]
Thanks, David!

Sorry Fideliopark but I haven't done it yet so I can't explain it in detail.

As I understood, you need to create a new module, create the substitutions file as explained in the link provided by David, and in this file add something like this:

```
function dolimarc_completesubstitutionarray(&$substitutionarray,$langs,$object)
{
   global $conf,$db;

   $fieldwithdatetime='dol_print_date($date, 'day', 'tzserver', $outputlangs)';
   $substitutionarray['object_options_yourextrafield']=$fieldwithdatetime;
}
```

Then activate the module and that's it, but I'm not sure if the code is OK or if this procedure is correct.
