### ISSUE TITLE
Can't handle excess payment on deposit invoices

### ISSUE THREAD

**Issue by Amael-PE** [Dolibarr/dolibarr#23704]
### Bug

My client overpaid a deposit invoice, du to currency changes.
Now, I convert the excess in credit, but I can't convert the original amount into credit.
I can't classify the invoice as paid neither.

### Environment Version

16.0.1

### Environment OS

Linux www.domain.tld 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64

### Environment Web server

Apache

### Environment PHP

8.0.27

### Environment Database

MySQL or MariaDB 10.3.37-MariaDB-0ubuntu0.20.04.1

### Environment URL(s)

htdocs/compta/facture/card.php

### Expected and actual behavior

**Situation** (fictive numbers)

1. I have a deposit invoice of 1500 €.  I edit it, and send it to my client. The invoice is passed in accountability. No modification are longer authorized on this invoice.
2. Then, my client paid 1500 USD on the € account, reaching 1501 €, as the bank convert it. 
I need thus a 1501 € payment record, amount indicated in my bank record.
3. I add the payment record, resulting in an excess of 1 €.
4. I converted the excess to a credit note, using a corrective invoice of 1 €, and marked as credit for my client.

**Bug/Actual behaviour**
However, can't convert the amount paid (1500 €) to a credit (nor reduction), neither classify the invoice as paid. 
Both buttons are disabled.
The invoice is somehow "blocked".
This is a functional bug, it doesn't work as intented.
No one ever though that a client can overpay a deposit invoice.

** Expected situation**
I should be able to convert the normal amount (1500 €) of the invoice to a credit for my client.
With it, plus the corrected amount, I reach the 1500 + 1 € = 1501 € credit, wihch is the amount paid by the client.
I should also be able to classify the invoice as paid.

### Steps to reproduce the behavior

1. Create deposit invoice, and push it to accountability. 
2. Add a payment record excessing the invoice amount, as can happen with currency exchange. 
3. Convert the excess to credit note, corrective invoice.
4. Back on the deposit invoice see that you can't classify as paid neither convert into credit.

**Comment by eldy** [comment]
If a deposit invoice (down payment) of 1501 euros has been done and the deposit invoice is 1500 euros, why not  create a second deposit invoice of 1 euros and then record a payment of 1501 for the 2 deposit invoices. 
So you have 1501 euros of deposit invoice recorded, and 1501 euros received ?

**Comment by Amael-PE** [comment]
It van work also indeed, the fact is that this way we artificially create an invoice that was never sent to the client.
We try to adapt the situation to Dolibarr, not enable Dolibarr to handle the situation 🙃

**Comment by Amael-PE** [comment]
Don't you think the change is worth it @eldy ?
