### ISSUE TITLE
Document generated with API Rest

### ISSUE THREAD

**Issue by Brice-VINCENT** [Dolibarr/dolibarr#23705]
### Bug

Hello,
When the document is generated with the rest api, the document does not take into account the special_code

### Environment Version

V15.2

### Environment PHP

PHP 7.4

### Environment Database

MySQL

### Attached files

![image](https://user-images.githubusercontent.com/110855142/214887766-7984dff3-d1fe-4a79-a074-7f79afe53362.png)

**Comment by ksar-ksar** [comment]
Hello,

What do you mean by "special_code” ?
Anyway seems related to external module, have you asked the développeur of the subtotal module?

**Comment by Brice-VINCENT** [comment]
Thank you for your answer.
Attached is the xml file of a proposal with a title on the first line and a subtotal on the third line. Note that this line has a special code. Code that probably allows to format the PDF.
[260.txt](https://github.com/Dolibarr/dolibarr/files/10674370/260.txt)
