### ISSUE TITLE
DB_ERROR_NOSUCHFIELD - Dictionary Setup - Types of leave

### ISSUE THREAD

**Issue by Crashone** [Dolibarr/dolibarr#23711]
### Bug

When I try to edit the types of leave in the dictionary setup, I got a database error. This bug is very similar to a previous I reported, also in the GRH module ( https://github.com/Dolibarr/dolibarr/issues/22530 )

**Modules/Applications:** user, api, adherent, oauth, ldap, propal, expedition, contrat, ficheinter, agenda, banque, commande, don, ecm, expensereport, facture, fournisseur, holiday, supplier_proposal, margin, recruitment, reception, incoterm, resource, blockedlog, salaries, service, societe, ticket, tax, takepos, loan, export, import, workflow, comptabilite, ecommerceng, product, prelevement, webservices, stock, paymentbybanktransfer, knowledgemanagement, paybox, debugbar, barcode, categorie
**Database type manager:** mysqli
**Latest database access request error:** SELECT h.rowid as rowid, h.code, h.label, h.affect, h.delay, h.newbymonth, h.fk_country as country_id, c.code as country_code, c.label as country, h.block_if_negative, h.sortorder, h.active FROM llx_c_holiday_types as h LEFT JOIN llx_c_country as c ON h.fk_country=c.rowid WHERE 1 = 1 ORDER BY sortorder ASC, country ASC, code ASC LIMIT 1001
**Return code for latest database access request error:** DB_ERROR_NOSUCHFIELD
**Information for latest database access request error:** Unknown column 'h.block_if_negative' in 'field list'

### Environment Version

16.0.3

### Environment OS

Linux vps-39218615 5.19.0-29-generic #30-Ubuntu SMP PREEMPT_DYNAMIC

### Environment Web server

Apache/2.4.54 (Ubuntu)

### Environment PHP

8.1.11

### Environment Database

 10.6.11-MariaDB-0ubuntu0.22.10.1

### Environment URL(s)

 /admin/dict.php?id=28

**Comment by ksar-ksar** [comment]
Same as #22447

**Comment by Crashone** [comment]
Ok. I have the bug on two different instances of Dolibarr, one is relatively old (initial version : 10.0.4)
