### ISSUE TITLE
ER Diagram for Dolibarr DB

### ISSUE THREAD

**Issue by UndercoverCat** [Dolibarr/dolibarr#23720]
### Feature Request

Hi! / Bonjour! @eldy ? 
(Je suis aussi française, j'écris en anglais pour que la majorité comprenne)

I'm fairly new to coding, and I don't know PHP, but I know some SQL and python, inter alia. ^^' I am trying to help someone who uses Dolibarr in his company, and needs **stringent traceability** for his **organic certification**, but we are struggling to find the relationships between tables... 

Is there a way to get an ER Diagram of the massive Dolibar DB so that we can find out how to link tables together?

In particular, we are trying to find a way to query the database to get **all batch numbers for each product in a specific shipment** (batches of material can be linked to several different praducts, and a same product can come from multiple batches). 

So far, we understand that shipments are referenced in the `llx_expedition` table, which is linked to `llx_expeditiondet` on `llx_expedition.rowid = llx_expeditiondet.fk_expedition`.  
Then `llx_expeditiondet` is linked to `llx_expeditiondet_batch` on `llx_expeditiondet.rowid = llx_expeditiondet_batch.fk_expeditiondet`.
We linked `llx_expeditiondet_batch` to `llx_product_batch` on `llx_expeditiondet_batch.fk_origin_stock = llx_product_batch.rowid`.
We then linked `llx_product_batch` to `llx_product_stock` on `llx_product_stock.rowid = llx_product_batch.fk_product_stock`.
(We can also link `llx_expeditiondet_batch` on `llx_expeditiondet_batch.batch = llx_product_batch.batch`. )
Finally, we linked `llx_product_stock` to `llx_product` on `llx_product_stock.fk_product = llx_product.rowid`.
However so far our attempts failed... Maybe my JOINs are wrong, but we are stuck and end up with products which were made from the same batch, but were not actually those sent in this shipment. 

Now, there is a `batch` field in `llx_expeditiondet_batch`, which we can link to several different tables such as `llx_product_batch`, `llx_stock_movement` or  `llx_mrp_production` for example, but we are not sure how to link them together. 
Also, some products are not coming from a manufacturing order because they were imported, so they won't be found in the `llx_mrp_mo` table for example...

An ER Diagram would be really helpful... Any idea, please? ^^'

**Comment by frederic34** [comment]
Hello
Look here for some info https://github.com/Dolibarr/dolibarr/tree/develop/dev/resources/dbmodel

**Comment by UndercoverCat** [comment]
> Hello Look here for some info https://github.com/Dolibarr/dolibarr/tree/develop/dev/resources/dbmodel

Thank you!!
