### ISSUE TITLE
PHP error 500 returned when saving an edited item line in customer proposal

### ISSUE THREAD

**Issue by hazel0602** [Dolibarr/dolibarr#23724]
### Bug

As described in the title, editing a line in a customer proposal and then saving the made changes results in a "blank" php error 500 screen. 
The dolibarr.log-file doesnt show anything suspicious. However the apache-log show that php is giving us a "Fatal error: Unsupported operand types on line xy".

This happend instantly after a fresh installation of dolibarr v16.0.3 and dolibarr v17.x combined with php8.x
When i tried with php7.4 the error didn't occur.

I guess php8 in some form is more strict with operand types than php7.4. Maybe its an "old" bug which wasn't noticed in the first place with php7.x just "dropping" unsupported operands.

### Environment Version

Dolibarr 16.x.x, 17.x.x

### Environment OS

Ubuntu 22.04.1 LTS

### Environment Web server

Apache/2.4.52 (Ubuntu)

### Environment PHP

8.0.26

### Environment Database

MySQL or MariaDB 5.5.5-10.6.11-MariaDB-0ubuntu0.22.04.1

### Environment URL(s)

https://yourdomain.com/comm/propal/card.php?id=YXZ

### Steps to reproduce the behavior

Setup a completly new environment e.g. in docker and edit an item line in a customer proposal. Then try to save it.

**Comment by ksar-ksar** [comment]
Hello,

Can you share your hosting logs?
