### ISSUE TITLE
I improved the script given by @stephanehofman to make it more verbose and more efficient (use all the CPUs to recompress):

### ISSUE THREAD

**Issue by eroeinformatico** [Dolibarr/dolibarr#23747]
I improved the script given by @stephanehofman to make it more verbose and more efficient (use all the CPUs to recompress):
```bash
#!/bin/bash

set -e

# dolibarr_16.0.2-4_all.deb
filename=$1

# => 16.0.2-4_all.deb
filename=${filename/dolibarr_/}

# => 16.0.2
VERSION=${filename/-4_all.deb/}

echo "Using dolibarr_${VERSION}-4_all.deb"

if [ ! -f dolibarr_${VERSION}-4_all.deb ]
then
	echo "File not found"
	exit
fi

set -x

ar x dolibarr_${VERSION}-4_all.deb
unzstd control.tar.zst
unzstd data.tar.zst
xz --threads=0 --verbose control.tar
xz --threads=0 --verbose data.tar
rm dolibarr_${VERSION}-4_all.deb
ar cr dolibarr_${VERSION}-4_all.deb debian-binary control.tar.xz data.tar.xz

rm -f debian-binary \
	control.tar control.tar.xz control.tar.zst \
	data.tar data.tar.xz data.tar.zst
```

Save it as `dolibarr_repack.sh` and use it like this:
```
$ dolibarr_repack.sh dolibarr_16.0.2-4_all.deb
```

_Originally posted by @LudovicRousseau in https://github.com/Dolibarr/dolibarr/issues/20894#issuecomment-1323495701_

**Comment by eroeinformatico** [comment]
Follow this guide debian give me back error with it:

root@dolibarr:/home/administrator# nano /home/administrator/dolibarr_repack.sh 
root@dolibarr:/home/administrator# ./dolibarr_repack.sh dolibarr_16.0.3-4_all.deb
Using dolibarr_16.0.3-4_all.deb
+ ar x dolibarr_16.0.3-4_all.deb
+ unzstd control.tar.zst
./dolibarr_repack.sh: riga 25: unzstd: comando non trovato

**Comment by LudovicRousseau** [comment]
The `unzstd` command is provided by the package [zstd](https://packages.debian.org/bullseye/zstd). Install it first.

**Comment by eroeinformatico** [comment]
> The `unzstd` command is provided by the package [zstd](https://packages.debian.org/bullseye/zstd). Install it first.

Done, thanks.
