### ISSUE TITLE
Bug: Can't create invoice from ODT template - Error "Nothing to parse - Check that the content.xml file is correctly formed in source file '/var/lib/dolibarr/documents/doctemplates/invoices/template_invoice.odt'" - Ubuntu 22.04 - PHP 8.1.2 - Dolibarr Deb 16.0.3-4

### ISSUE THREAD

**Issue by abcnet-lu** [Dolibarr/dolibarr#23753]
Dear Dolibarr community,

I've been using Dolibarr on Ubuntu 20.x and PHP 7.4 for a long time without any problem, and very stable.

Since the migration to Ubuntu 22.x and PHP 8.1, I experience the following issue: every time I try to generate an invoice based on an ODT template, the following error occurs on the GUI:

`Nothing to parse - Check that the content.xml file is correctly formed in source file '/var/lib/dolibarr/documents/doctemplates/invoices/template_invoice.odt'`

The PHP error:
`
[Wed Feb 01 18:37:50.154062 2023] [php:warn] [pid 57527] [client xxx.xxx.xxx.xxx:52755] PHP Warning:  Undefined array key "propal" in /usr/share/dolibarr/htdocs/core/modules/facture/doc/doc_generic_invoice_odt.modules.php on line 337, referer: https://xxx.xxx.xx/dolibarr/compta/facture/card.php?facid=113&mainmenu=home
[Wed Feb 01 18:37:50.154130 2023] [php:warn] [pid 57527] [client xxx.xxx.xxx.xxx:52755] PHP Warning:  Trying to access array offset on value of type null in /usr/share/dolibarr/htdocs/core/modules/facture/doc/doc_generic_invoice_odt.modules.php on line 337, referer: https://xxx.xxx.xx/dolibarr/compta/facture/card.php?facid=113&mainmenu=home
`

The thing is that the ODT templates have not been modified at all, and they were working perfectly with Ubuntu 20.x and PHP 7.4.

OS: 22.04.1 LTS
PHP version: 8.1.2
Dolibarr: Deb 16.0.3-4

Any idea on how to fix this?

Thank you and best regards.

Alexandre

**Comment by alexboss** [comment]
Thanks everybody for contributing and for the fix delivered.

The fix fixes the warning, but not the issue with the ODT not being generated.

Anyway, after investigating, I managed to fix the issue by simply commenting in `/etc/dolibarr/conf.php` the following line:

```
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='/usr/share/php';
```

(replacing by the following also works
```
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='/usr/share/dolibarr/htdocs/includes/odtphp/zip/pclzip';
```
)

So I guess the error was related to `/usr/share/php/pclzip.lib.php` provided by the package `php-pclzip` not able to access / write resources of dolibarr.

Thank you and best regards.

Alexandre.

**Comment by abcnet-lu** [comment]
Thanks everybody for contributing and for the fix delivered.

The fix fixes the warning, but not the issue with the ODT not being generated.

Anyway, after investigating, I managed to fix the issue by simply commenting in `/etc/dolibarr/conf.php` the following line:

```
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='/usr/share/php';
```

(replacing by the following also works
```
$dolibarr_lib_ODTPHP_PATHTOPCLZIP='/usr/share/dolibarr/htdocs/includes/odtphp/zip/pclzip';
```
)

So I guess the error was related to `/usr/share/php/pclzip.lib.php` provided by the package `php-pclzip` not able to access / write resources of dolibarr.

I let you decide what to do with this ticket.

Thank you and best regards.

Alexandre.
