### ISSUE TITLE
Something like `->fields` for base dolibarr objects

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#23768]
### Feature Request

I created a module to log stuff.

I log creation, modification, deletion and other things using triggers, I started using it just for custom module's objects so I use `->fields` to obtain something like this:

```php
ClassName {
	rowid => ,
	ref => (PROV3),
	status => ,
	field[n] => ,
	field[n] => ,
	field[n] => ,
	field[n] => ,
	date_creation => ,
	date_validation => , 
	Extrafields {
			ExtraField (extrafield_1 => 1),
			ExtraField (extrafield_2 => 2),
			ExtraField (extrafield_3 => 3),
			ExtraField (extrafield_4 => 4), 
	}
}
```

and to that I add stuff like, user, IP address, GET/POST data, etc...

Problem is, now that I want to use it with objects like `BookKeeping` I get 

```php
BookKeeping {

}
```

because BookKeeping has no `fields` property.

I don't want to use var_dump because the output is not that easy to read.

Is there a way to do this? Or do I need to modify core files and add a `fields` property myself?

**Comment by rycks** [comment]
Hello @Daviid-P,
that is an important point i try to explain during last devcamp about dolibarr "introspection" datamodel ... for the moment you can use https://www.php.net/ReflectionClass ...
