### ISSUE TITLE
Add new {myuser_civility} tag for user that use on odt template

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#23796]
### Feature Request

Add new {contact_civility} tag for odt template .
So user can use it and prevent the error position for traditional chinese  .

### Use case

In taiwan , it will be last name , first name and civility .
If use {myuser_fullname} , then it will be civility , last name and first name .

**Comment by dolibarr95** [comment]
Hello 
According to the wiki this tag already exists  : 
https://wiki.dolibarr.org/index.php?title=Cr%C3%A9er_un_mod%C3%A8le_de_document_ODT

**Comment by trekmorris** [comment]
Hi

Sorry , i can only find the tag " {contact_civility} " not " {myuser_civility} " .

**Comment by dolibarr95** [comment]
In the wiki we can  :
![Capture](https://user-images.githubusercontent.com/24292300/217545582-b7587ef4-f0e0-464f-9dcc-ad645f1d587b.PNG)

Does it works ?

**Comment by trekmorris** [comment]
Hi 

That works for customer not for user . And what i request is for user .

**Comment by dolibarr95** [comment]
Ok sorry for misunderstanding.
Just to let you know, I you create a module you can add custom {tags} :
```php
function mymodule_completesubstitutionarray(&$substitutionarray,$langs,$object)
{
   global $conf,$db;

   $myvalue='Put here calculated value to insert';
   $substitutionarray['myowntag']=$myvalue;
}
```

**Comment by trekmorris** [comment]
Hi 

Thanks , but how do i use your module ?

**Comment by dolibarr95** [comment]
You have to create a module.
you can have more help here : 

 https://www.dolibarr.org/forum.php

**Comment by trekmorris** [comment]
Hi 
Thanks for your reply .
Create a module is not easy for me , i may wait for new update .
Thanks .
