### ISSUE TITLE
Theorical stock calculation error

### ISSUE THREAD

**Issue by euchmax** [Dolibarr/dolibarr#23822]
### Bug

Good morning,
I think there is an oversight in the load_stats_command function of the product.class.php file in the htdocs/products/class/ folder

In theorical stock management, if the DECREASE_ONLY_UNINVOICEDPRODUCTS option is on, we have a compensation. But in the SQL query of this part, we do not make the difference between an invoice (stock that we no longer have) and a credit note (stock that we recover). In this query, we just sum all quantities without distinction, invoice quantities are counted as positive.

I therefore suggest modifying the SELECT with this proposal: SELECT SUM(IF(f.type=2,-1,1)*fd.qty) as count
The goal is that if the type of invoice is a credit (type=2) to multiply by -1 to have a negative quantity otherwise to multiply by 1 and that does not change anything for an invoice.

Thank you in advance for your feedback because maybe I'm wrong :)

Good day,

### Environment Version

16.0.0

### Environment OS

Ubuntu 18.04.6 LTS

### Environment Web server

HTTP/2 - Apache -  Nginx/1.20.2 

### Environment PHP

7.4.33

### Environment Database

MySQL 5.7.41

**Comment by atm-maxime** [comment]
Hi ! Nice catch ! I'll get on it !
