### ISSUE TITLE
Ticket : User assigned during creation formis not correctly assigned ?

### ISSUE THREAD

**Issue by FredBl79** [Dolibarr/dolibarr#23838]
### Bug

Hi,

Just discover that if you assign an user during the ticket creation form and validate, the ticket remains into 'not assgined' status and the trigger 'TICKET_ASSIGNED' is not executed, you have to manually reselect the user on the View form in order to execute correctly the functions 'assign_user' and launch the trigger (TICKET_ASSIGNED'

Fred

### Environment Version

16.0.4

**Comment by FredBl79** [comment]
**### here the fix to apply :** 

in htdocs/ticket/class/ticket.class.php

Function create : 

if (!$error && $this->fk_user_assign > 0) {
				if ($this->add_contact($this->fk_user_assign, 'SUPPORTTEC', 'internal') < 0) {
					$error++;
				}
				$ret = $this->assignUser($user, $this->fk_user_assign);
				if ($ret < 0) {
					$error ++;
					setEventMessages($this->error, $this->errors, 'errors');
				} 
			}

**Comment by ReproductriceDeBugs** [comment]
Hello
This problem is not there in v18
For the v16, you can pull request your solution if you want

**Comment by atm-maxime** [comment]
Hi ! I can't reproduce with 16.0.5. Seems fixed to me ! Thanks !
