### ISSUE TITLE
Can choose any apporver even set a user for " Force leave request validator "  and " Force expense report validator " 

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#23842]
### Bug

In user card , i can see a option  " Force leave request validator " and " Force expense report validator " .
And as description , the default should be supervisor of user .
There are not difference between i choose a user to apporve or not , i can choose any one who has permission to apporve .

### Environment Version

16.0.4

### Environment OS

Deian 11

### Environment Web server

Apache/2.4.54

### Environment PHP

 7.4.33

### Environment Database

MariaDB 5.5.5-10.5.18

### Environment URL(s)

/holiday/card.php?mainmenu=hrm&leftmenu=holiday&action=create

### Expected and actual behavior

If not choose a approver , then the choose box should show user's supervisor only .
Or if user choose wrong approver , then it should show a message to warning user to choose his / her supervisor .
And if set an approver , then it should show out his / her approver .

**Comment by atm-maxime** [comment]
Hi ! Thanks for your feedback. I think the term "force" is wrong here. This field you can define on the user card is used as a default value for the validator. As indicated on the  "?" next to the field, this field is used to overload the default validator that is the supervisor.
