### ISSUE TITLE
Bug:  New module document does not delete document

### ISSUE THREAD

**Issue by karozans** [Dolibarr/dolibarr#23845]
### Bug

When creating a new module with the module builder, and then adding a document to a record, you cannot delete the document from the card.php page using the trash can icon.

A message is returned saying that it was deleted, but it does not actually delete it.

I believe this is due to main.inc.php.  For security, main.inc.php removing any action that is not of a specific format.  When you delete a file, it is supposed to call action == remove_file.  However the action is automatically removed from the URL.

### Environment Version

Dolibarr 16.0.4

### Environment OS

Mac OS 13.2

### Environment Web server

Apache 2.4.54

### Environment PHP

PHP 7.4.33

### Environment Database

MySQL 5.7.39

### Environment URL(s)

custom/xxx/yyy_card.php

### Expected and actual behavior

The trash can icon should delete the document.

When you click on the trash can icon, the document says it is delete, but it does not.

### Steps to reproduce the behavior

Create a new module using the module builder.
Create a new record in the module.
Add any document to the record.
Try to delete the document from the card.php of the record.

**Comment by playcock** [comment]
I thought I did something wrong, but it looks like I am not alone. The same thing happens to me in 16.0.5.

 cannot generate new files either.

**Comment by playcock** [comment]
Even though I am unable to delete the linked file from the card.php page, I can delete the file on the Linked files tab.

In order for me to regenerate a new document after deleting the previous one, I have to go back to draft mode and then validate the status.

**Comment by Dewenir** [comment]
Hola, después de trazar la variable $upload_dir es incorrecta, debes cambiar en mi caso, en la pestaña de documentos mymodule_documents.php 
La siguiente linea por esta otra:
if ($id > 0 || !empty($ref)) {
	$result = $object->fetch($id, $ref);
	$upload_dir = $conf->mymodule->dir_output."/".$id;
	// $upload_dir = $conf->mymodule->multidir_output[$object->entity ? $object->entity : $conf->entity]."/".get_exdir(0, 0, 0, 1, $object);	
}
Saludos
