### ISSUE TITLE
Can't validate expenses

### ISSUE THREAD

**Issue by CKSpringbok** [Dolibarr/dolibarr#23882]
### Bug

After updating to version 16.0.4 I couldn't validate the expenses. It turned out a mask was missing in the settings. 

### Environment Version

16.0.4

### Environment OS

Ubuntu 22.04

### Environment Web server

Apache 2.4.52

### Environment PHP

7.4/8.1

### Environment Database

MariaDB 10.6.11

### Expected and actual behavior

After updating a missing mask: home->modules->expenses Sand: {yy}-{mm}-{000000} did the trick.

### Steps to reproduce the behavior

Create Expense and add some lines
'Request validating'

**Comment by atm-maxime** [comment]
Thanks for your feedback. I can't reproduce on my hand. If it was simply a setup missing, I guess we can close this issue.
