### ISSUE TITLE
Object cannot be updated for trigger BILL_CREATE

### ISSUE THREAD

**Issue by splohmer** [Dolibarr/dolibarr#23900]
### Bug

For the trigger BILL_CREATE the object cannot be updated with ->update as it runs into an SQL error if the object is adapted and updated. After debugging it looks like the root cause is that remise_percent is an empty string instead of null and fk_project is 0 instead of null if not set during the creation of the invoice. The error doesn't occur for the other triggers of the invoice, means once it is stored in the database the two values are loaded properly and the object can be adapted.

SQL Error from $this->db->lasterror(): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' remise_absolue=0, close_code=null, close_note=null, total_tva=0, localtax1=0...' at line 1

Currently used workaround:

if ($action == 'BILL_CREATE') {
    // additional logic
    if ($object->remise_percent == '') {
        $object->remise_percent = null;
    }
    if ($object->fk_project == 0) {
        $object->fk_project = null;
    }
    $object->update($user, 1);
}

### Environment Version

16.0.3, 16.0.4

### Environment OS

Windows 11

### Environment Web server

Apache 2.4.54

### Environment PHP

7.4.33

### Environment Database

MySQL or MariaDb 5.5.5.-10.4.27-MariaDB

### Environment URL(s)

/htdocs/compta/facture/card.php?action=create

### Expected and actual behavior

**Expected:** The trigger BILL_CREATE can be used to modify the object without running into an SQL error on the update.

**Actual behavior:** If the object invoice is updated within the trigger BILL_CREATE an SQL error occurs.

### Steps to reproduce the behavior

Steps to reproduce the behavior

1. Create a new module and use the trigger BILL_CREATE
2. Add logic to the trigger to update a value of the object and call then the update function
3. Activate the module
4. Create a new invoice, then the object is not updated properly in the trigger

### Attached files

[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/10729637/dolibarr.log)

**Comment by hregis** [comment]
@splohmer and what is the content of your trigger action BILL_CREATE ?

**Comment by splohmer** [comment]
Hi @hregis,

I attached an example module to reproduct the issue. In the end I want to set the type of the invoice depending on some logic, but it can be reproduced easier - so the module sets the value hardcoded. Also changing other values like the ref is not working because of this issue. Please see attached code "interface_99_modTest_TestTriggers.class.php". The lines 98 to 105 are commented because this is my current workaround to make it work.

Thanks for the fast reply and best regards,
Sven

[module_test-1.0.zip](https://github.com/Dolibarr/dolibarr/files/10736168/module_test-1.0.zip)

**Comment by splohmer** [comment]
HI @hregis,

I didn't hear from you. Where you able to reproduce the issue?

Regards,
Sven

**Comment by splohmer** [comment]
Hi,

as of now there is no feedback on the mentioned issue. It would be great to get feedback on the topic to know if the issue can be reproduced. Also please let me know if I can provide more details, etc.

Regards,
Sven
