### ISSUE TITLE
No hook result treatment by class eldy in case of left menu

### ISSUE THREAD

**Issue by werewolf7160** [Dolibarr/dolibarr#23916]
### Bug

I tried to modify a redirection of a left menu by hooking to "menuLeftMenuItems" but that didn't work very well.

if I set my hook return at 0, nothing change and if I set it at 1 I have the following error

`Warning: count(): Parameter must be an array or an object that implements Countable in /home/server/public_html/dev/htdocs/core/menus/standard/eldy.lib.php on line 2037`

### Environment Version

15.0.3 -> dev (verified)

### Environment OS

cpanel

### Expected and actual behavior

after investigation i found there is a call in eldy.lib.php to 
`$hookmanager->results` that don't exist (anymore?)

and there are no other call with it

by replacing 
`if ($reshook == 0 && !empty($hookmanager->results)) {
	$menu_array[] = $hookmanager->results; // add
} elseif ($reshook == 1) {
	$menu_array = $hookmanager->results; // replace
}`

by

`if ($reshook == 0 && !empty($hookmanager->resArray)) {
	$menu_array[] = $hookmanager->resArray; // add
} elseif ($reshook == 1) {
	$menu_array = $hookmanager->resArray; // replace
}`

it work just fine

**Comment by werewolf7160** [comment]
wanted to submit a pull request from this issue but apparently I can't T.T

**Comment by ksar-ksar** [comment]
Hello,

Are you sure to respect the coding recommendation : https://wiki.dolibarr.org/index.php?title=Hooks_system

Returns:

    The return code from a hook ($reshook) is 0 / 1 if successful, or negative if in error.

Return Code 0. In this case if the subsequent core module code function is enclosed by if (empty($reshook)) {...} it will execute as normal but with the data modified by your custom function.

Return Code 1. In this case if the subsequent core module code function is enclosed by if (empty($reshook)) {...} it will not execute at all. So this means it has been replaced by your custom function.

Return code is negative if an error has occurred in your function. You can also set $this->errors[]='Error message to report to user'

    If the method sets the property $this->results with an array, then the array $hookmanager->resArray will automatically be loaded with the contents of this array, may be reused later.

**Comment by werewolf7160** [comment]
here my code with a return in "results" and return 0 : 

```php
function menuLeftMenuItems($parameters, &$object, &$action, $hookmanager){
        $error = 0; // Error counter
        $arr = [];
        foreach($object as $obj){
        	if(strpos($obj['url'],'replenish.php')){
	        	$obj['url'] = 'compta/bank/list.php';
	        }
	        $arr[] = $obj;
        }
        if (! $error)
        {
        	$this->results = $arr;
	        //$this->resprints = 'A text to show';
	        return 0; // or return 1 to replace standard code
        }
        else
        {
	        $this->errors[] = 'Error message';
	        return -1;
        }
}
```

there is not modification on the left menu.
if I replace the return with a 1 you have the following errors : 
![image](https://user-images.githubusercontent.com/31860486/219310034-0d586ee2-a03d-43fb-b540-05714e7b9565.png)

and as said in the explaination of HookManager::executeHooks() 
`Things to return are returned into ->results by hook and set into ->resArray for caller`

the caller this time is the file htdocs/core/standart/eldy.lib.php line 2003 (in my version)
`$reshook = $hookmanager->executeHooks('menuLeftMenuItems', $parameters, $hook_items);`

so It should use resArray and not results if I read the explanation right ?
a quick replace allow the return 1 to function as I tough it would be

> If the method sets the property $this->results with an array, then the array $hookmanager->resArray will automatically be loaded with the contents of this array, may be reused later.

that line prove that all I add in "results" is put in resArray, but in this case resArray is not user by the caller and so the mentionned error occured
