### ISSUE TITLE
Not able to modify an invoice line

### ISSUE THREAD

**Issue by Yobipro** [Dolibarr/dolibarr#23917]
### Bug

I reopened an invoice. After trying to modify a line (text and amount), I got this message:
La progression ne peut être inférieure à la valeur de progression du point de situation précédent
which seems unrelated to an invoice.
Adding a line or delete it is possible but modification is NOT possible.

Thank you.

### Environment Version

13.0.2

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

8.0.27

### Environment Database

MySQL 

### Environment URL(s)

htdocs/compta/facture/card.php?id=712#line_1088

### Expected and actual behavior

Line should be modified.
The message shouldn't be displayed.

### Steps to reproduce the behavior

Reopen an invoice.
Modify a line
Edit text and amount
Clic on "Enregistrer" and get the error.

### Attached files

![image](https://user-images.githubusercontent.com/125455313/219009334-e7424c65-4e18-4a5e-bf91-23cb1cd8efe5.png)

**Comment by thiyagarajan17** [comment]
Assign the issue.. would love to work in it

**Comment by Daviid-P** [comment]
I don't think you'll get a fix release for v13, I don't know if it's current + 3 older versions or current + 2 older versions

But 13 is probably out of range.

This error only happens when
```php
$object->type == Facture::TYPE_CREDIT_NOTE && $object->situation_cycle_ref > 0
```
and you're trying to set a progress less than the current progress.

I've never used this so I can only assume that is something like paying in installments??

**Comment by ksar-ksar** [comment]
And also, first thing to do : Upgrade to latest V13 : 13.0.5

**Comment by Yobipro** [comment]
> ```
> ```
> $object->type == Facture::TYPE_CREDIT_NOTE && $object->situation_cycle_ref > 0
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Hello,
How to disable this script without impacting general code ?
Thank you
