### ISSUE TITLE
Cron job no longer works after upgrade from 15.0.2 to 16.0.3 or 16.0.4

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#23920]
### Bug

After i upgrade dolibarr from 15.0.2 to V16 , the cron job has no longer working .
But i still can see cron_run_jobs.php.log has upgraded every 5 minutes .

### Environment Version

v16.0.3 and v16.0.4

### Environment OS

Deian 10

### Environment Web server

Apache/2.4.38

### Environment PHP

 7.4.3

### Environment Database

MariaDB 5.5.5-10.3.36

### Environment URL(s)

cron/list.php?leftmenu=admintools&idmenu=552

### Expected and actual behavior

Should run well as in v15.0.2 .

**Comment by ksar-ksar** [comment]
Link to forum : https://www.dolibarr.org/forum/t/scheduled-jobs-no-longer-run-after-apgrade-to-v16/23342

Can you post the logs ?

**Comment by trekmorris** [comment]
Hi

The log is as below now :
![image](https://user-images.githubusercontent.com/78349579/219203971-4ece3b0f-d665-4304-8b97-da63f82b2086.png)

**Comment by hregis** [comment]
@trekmorris 
What is the cron that doesn't work? 
What are the errors? 
Do you have the logs of the Cron, do you have the logs of Dolibarr? 
Do you have the Apache logs? Have you checked the functions called by the Cron? 
How do you want us to help you with so little information?!

**Comment by trekmorris** [comment]
Hi Hregis

Actually , all my cron jobs are not working now .
All jobs will not active in the planed time .
But i can execute all cronjob by browser or command line correctly .
![image](https://user-images.githubusercontent.com/78349579/219226881-d25a269d-e8c1-4654-8fdc-32d6ce711225.png)


![image](https://user-images.githubusercontent.com/78349579/219224953-b568af91-ed91-44a8-9a42-08f50e64957f.png)
In cron_run_jobs.php.log , i can only see that information , does that correct ? Or maybe you could show me what is correct .

The cron log is as below :
![image](https://user-images.githubusercontent.com/78349579/219225628-8c22956e-a5ac-42ae-a9ce-2b1d9df2d9c1.png)

Where do i find the log of dolibarr ?

Apache error log is as below :
[Apache error.log](https://github.com/Dolibarr/dolibarr/files/10750717/Apache.error.log)

**Comment by hregis** [comment]
@trekmorris for the Dolibarr logs enable the "Debug Logs" in "Modules/Application setup" and check the file "dolibarr.log" in "documents" directory.
and in the file "/var/lib/dolibarr/documents/cron_run_jobs.php.log" ?

**Comment by trekmorris** [comment]
@hregis  
Please find the dolibarr.log and cron_run-jobs.php.log as attachment .
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/10751466/dolibarr.log)
[cron_run_jobs.php.log](https://github.com/Dolibarr/dolibarr/files/10751510/cron_run_jobs.php.log)

**Comment by trekmorris** [comment]
Hi 

I think i make a mistake that i forgot i have replaced the cron_run_jobs.php file in the same time  when i upgrade dolibarr .

Therefore i have not to correct the  line  " require_once $path."../../htdocs/master.inc.php";  " .
Now all cron jobs are working now .
