### ISSUE TITLE
not able to acces to order and products Bug: 

### ISSUE THREAD

**Issue by YASSIRKHADFY** [Dolibarr/dolibarr#23923]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 16.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.4.33
- **Database**: MySQL or MariaDB 5.7.23-23
- **URL(s)**: /dolibarr/core/tools.php?mainmenu=tools&leftmenu=

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

What is exactly your issue ?
There is no description.

**Comment by YASSIRKHADFY** [comment]
Hello ,

Thank you for your response .

I have Dolibarr 16.0.3, and from 3 days I could not access to products page, commerce or the menu page (see attached examples) , I have only access to invoice page .
Please if you could help and support, it will be highly appreciated.

Best regards,


De : ksar ***@***.***>
Date : mercredi, 15 février 2023 à 17:26
À : Dolibarr/dolibarr ***@***.***>
Cc : YASSIRKHADFY ***@***.***>, Author ***@***.***>
Objet : Re: [Dolibarr/dolibarr] not able to acces to order and products Bug: (Issue #23923)

Hello,

What is exactly your issue ?
There is no description.

**Comment by hregis** [comment]
@YASSIRKHADFY i can not see your "attached examples" ! 
can you answer directly in github please !
