### ISSUE TITLE
Génération du RUM dépasse la taille de la BDD

### ISSUE THREAD

**Issue by huc48** [Dolibarr/dolibarr#23980]
### Bug

Lors de la génération d'un RUM pour les prélèvements, le RUM généré est trop long (>32 car)

### Environment Version

16.0.3

### Steps to reproduce the behavior

Créer un client avec un code client long Exemple : PERFORMANCECONSEIL
Saisir un compte bancaire avec génération du RUM 
`Data too long for column 'rum' at row 1`

**Comment by huc48** [comment]
* \file       htdocs/compta/prelevement/class/bonprelevement.class.php
 
 	/**
	 * Generate dynamically a RUM number for a customer bank account
	 *
	 * @param	string		$row_code_client	Customer code (soc.code_client)
	 * @param	int			$row_datec			Creation date of bank account (rib.datec)
	 * @param	string		$row_drum			Id of customer bank account (rib.rowid)
	 * @return 	string		RUM number
	 */
	public static function buildRumNumber($row_code_client, $row_datec, $row_drum)
	{
		global $langs;
		$max=32;
		$pre = substr(dol_string_nospecial(dol_string_unaccent($langs->transnoentitiesnoconv('RUM'))), 0, 3); // Must always be on 3 char ('RUM' or 'UMR'. This is a protection against bad translation)
		$taille_sans_code_client = strlen($pre.'--'.$row_drum.'-'.date('U', $row_datec));
		$row_code_client=substr($row_code_client,0,$max-$taille_sans_code_client);//  32 chars max 
		return $pre.'-'.$row_code_client.'-'.$row_drum.'-'.date('U', $row_datec); 
	}

**Comment by rycks** [comment]
Bonsoir, je suis en plein dans le code pour le plugin Stancer je regarde cette histoire de RUM que j'ai déjà corrigé pour une installation custom ici ...


Hello, as i'm in stancer dev time (an other solution than stripe), i could have a look to that bug !

**Comment by rycks** [comment]
![image](https://user-images.githubusercontent.com/1468823/220454157-3144ccdf-6d09-4507-bd20-ff837affc6be.png)

**Comment by rycks** [comment]
damned, that bug was already fixed ... with https://github.com/Dolibarr/dolibarr/pull/23981 ... but still open and no link between bug and PR :-(
