### ISSUE TITLE
`FileUpload` class can't be used without an object

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#24001]
### Bug

The class constructor has all arguments set to null by default
https://github.com/Dolibarr/dolibarr/blob/78b0ce6b24c611ae35f4b021abde30238679253e/htdocs/core/class/fileupload.class.php#L44

However actually using it like that leads to
```
$dir_output = null;
$pathname = null;
$filename = null;
$classname = null;
```

all of which have to be not null and related to valid dolibarr classes for the code to work.
https://github.com/Dolibarr/dolibarr/blob/78b0ce6b24c611ae35f4b021abde30238679253e/htdocs/core/class/fileupload.class.php#L107-L117

Is it possible to upload files without needing to use or assign a class to that file?

### Environment Version

16.0.3

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
