### ISSUE TITLE
BUG - BOM - Purschasing price not updated at the line level with the PMP of the product

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#24017]
### Bug

We have a product with a PMP = 0,25€ 
![image](https://user-images.githubusercontent.com/26635105/220874309-accfd9ca-5e6b-44fa-b179-f48e8b655605.png)

But at the BOM line level the price of the unit is not set 
![image](https://user-images.githubusercontent.com/26635105/220874689-1d9a5b2c-12db-4ed5-a663-b9f0d5b6a922.png)

Double check in the database 
![image](https://user-images.githubusercontent.com/26635105/220874873-889c2103-7348-432d-badb-dc43385de628.png)

### Environment Version

v16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

https://<XXXXX>/bom/bom_card.php?id=3

**Comment by daxitsolutions** [comment]
Hi ! Any update on this topic ?

**Comment by atm-maxime** [comment]
Hi ! Thanks for your feedback. I just checked on a version 16.0.5 and can't reproduce. I think it has been fixed ! Can you check ?
