### ISSUE TITLE
v16.0.3 - BUG Minor - Import of the products (PMP required)

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#24021]
### Bug

When importing product, the PMP is mandatory, it should be optional (and by default 0)

Column concerned : Prix moyen pondéré (PMP) (p.pmp)

### Environment Version

v16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

http://xxxx/imports/import.php

**Comment by AurelienBISOTTI** [comment]
I believe that inventory valuation is a legal obligation for many companies.
I'm not shocked that it's mandatory by default.

**Comment by daxitsolutions** [comment]
That's not mandatory in any way, should be optional.

**Comment by eldy** [comment]
I did not see any rule to have pmp mandatory in v19. Is this still true in v19 ?
If yes, what happen if you fill the field with value '0' ? Can you make a screenshot of error ?

**Comment by daxitsolutions** [comment]
Retested on v20, PMP is not mandatory anymore. 
Case closed 
[Exemple_de_fichier_import_produit_1.xlsx](https://github.com/user-attachments/files/17293816/Exemple_de_fichier_import_produit_1.xlsx)
