### ISSUE TITLE
mercure numbering not incrementing

### ISSUE THREAD

**Issue by bzarzecki** [Dolibarr/dolibarr#24020]
### Bug

In invoice module config I have selected mercure.

My mask for invoices is FV/{000@0}/{mm}/{yyyy}
I want the counter to reset every month.

however When I create first invoice - for example first invoice in Ferbruary it get (PRO_something)
When I confirm/accept it -  the invoice it get number:
FV/001/02/2023 **- that is what I expected.**

When I create a next invoice.
When I try to accept it it tries to get the same number FV/001/02/2023

I got error: DB_ERROR_RECORD_ALREADY_EXISTS
Duplicate entry ‘FV/001/02/2023-1’ for key ‘uk_facture_ref’

### Environment Version

15.* 16.*

### Environment OS

Linux

### Environment Web server

Server version: Apache/2.4.37 (rocky)

### Environment PHP

PHP 7.4.x , PHP 8.0.20

### Environment Database

mysql  Ver 15.1 Distrib 10.3.35-MariaDB, for Linux (x86_64) using readline 5.1

### Expected and actual behavior

I expect the next invoice to have the next availiable number not the same as the first.

**Comment by atm-maxime** [comment]
Hi. Thanks for the feedback. Currently if you want to use yy, mm and 000 in your numbering mask, they must be in that order in the mask for the numbering system to work.

**Comment by atm-maxime** [comment]
Maybe you can transform your issue in a Feature Request to have the numbering system working another way
