### ISSUE TITLE
traces from previous domain

### ISSUE THREAD

**Issue by r9guy** [Dolibarr/dolibarr#24036]
### Bug

Then dolibar is being restored on webserver on a new domain from backup made on old domain, the payment module has traces of old domain.
such as if old domain is 
aaa.com and new on is bbb.com, after restoration in invoice the's a payment link showing with old domain.
![image](https://user-images.githubusercontent.com/9428627/221176789-cd2c0aad-7264-46f8-a3b3-c5a76b3ef281.png)
I cannot find any place where I can change the domain. the company setup page has all the data correct.

### Environment Version

16-17

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

 8.1.14

### Environment Database

MySQL or MariaDB 10.3.38-MariaDB-log

### Expected and actual behavior

Some user interface which would be used to setup company url.

**Comment by hregis** [comment]
@r9guy and in your conf.php file?

**Comment by r9guy** [comment]
@hregis thanks for pointing out. the conf/conf.php contained 
`$dolibarr_main_url_root='http://erp.olddomain.com';`

however I would argue if this shall be parametrized from Dolibarr itself.
