### ISSUE TITLE
Intervention ne fonctionne pas comme attendu.

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#24030]
### Bug

Lorsqu'une intervention est crée, elle est ajoutée automatiquement dans l'agenda, mais les éléments constitutifs eux n'apparaissent pas et les limitations de ressources ne fonctionnent pas.

Explication détaillée:

Création d'une intervention le 24/02/2023 10:08
Contenu : Intervention Test Le 25/02/2023 10:00 Durée 1h
Ressources: Voiture 1
Intervenant : Mario Le Plombier

La création de l'intervention apparaît bien le 24/02/2023 à 10:08
mais le contenu de l'intervention, lui n’apparaît pas dans l'agenda le 25/02/2023 à 10:00 pour Mario Le Plombier.

De plus en cas de création d'une nouvelle intervention à la même date et heure (25/02/2023 à 10:00) avec Luigi le plombier et la Voiture 1, la limitation d'usage de la ressource ne fonctionne pas (i.e. le véhicule est accepté dans la création de l'intervention).

### Environment Version

16.0.3

### Environment OS

Ubuntu Server LTS 20.04.5

### Environment Web server

Apache/2.4.41

### Environment PHP

PHP 7.4.3

### Environment Database

MySQL 8.0.31

**Comment by ksar-ksar** [comment]
Hello,

In english please ?

**Comment by dom-breizh** [comment]
### Bug
When an intervention is created, the event is recorded in the agenda automatically, however, the individual components are neither itemized in the agenda nor are the ressources limited in multiple use.

Detailed explanaton:

Creation of an intervention on 24/02/2023 10:08
Content : Intervention Test Le 28/03/2023 10:00 Duration 1h
Ressources: Car 1
Intervenant party : Mario The Plumber

The creation appears correctly in the agenda on 24/02/2023 à 10:08
But the intervention elements are not itemized in the agenda on 28/03/2023, hence if Mario is looking for tasks to perform in his agenda, nothing shows.

Furthermore, if a new intervention is created for the same date/hour  (28/03/2023 10:00) with Luigi and using the same ressource ('Car 1'), the usage limitation does not work (i.e. the use of the car is accepted in the creation of the event although it was already allocated in an other intervention.

### Expected Behavior
The items of the invervention are shown individually in the agenda of the assigned individual. The ressources are assigned to this item and cannot be re-assigned at the same time frame.
