### ISSUE TITLE
 List of time consumed on tasks of project

### ISSUE THREAD

**Issue by bordur12** [Dolibarr/dolibarr#24058]
### Bug

Warning: is_dir(): open_basedir restriction in effect. File(/TK2302-0004) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103

### Environment Version

16.0.4

### Environment OS

(Windows 10) 

### Environment Web server

Apache/2.4.51 (Win64) 

### Environment PHP

PHP/7.3.33

### Environment Database

MySQL or MariaDB 5.5.5-10.6.5-MariaDB

**Comment by atm-maxime** [comment]
We can't reproduce with the little information we have. Can you fill the "Steps to reproduce the behavior" section and/or add a screenshot ?
And first check that this issue is still present in version 16.0.5
