### ISSUE TITLE
Make the Ticket messages (event) searchable in Ticket Listing.

### ISSUE THREAD

**Issue by ff55lab** [Dolibarr/dolibarr#24057]
### Feature Request

Make the Ticket messages (event) searchable in Ticket Listing.

### Use case

The ticket's [initial message] is searchable in Ticket Listing, however, the Messages (Event) is not searchable in Ticket listing.

Previous: The ticket's [initial message] is searchable and is useful if we write in the message into it. Even better if we could add in a manual timestamp for every message we have written in. 

Other suggestion would be, auto add in Timestamp into initial message for each [Modify], and the previous message is not editable.

### Suggested implementation

Make both [Initial message] and [Message (Event)] searchable in Ticket Listing.

**Comment by Daviid-P** [comment]
Are regular messages not enough?

![image](https://user-images.githubusercontent.com/7734808/221797498-519172c5-264f-479b-a8cb-16e6474d4c23.png)

Probably the better feature would be to add a way to search ticket messages.

**Comment by ff55lab** [comment]
I love the regular message which are non-editable and with all timestamp. And yes, it is not searhable in the Ticket listing. Shall we create new feature request or using this as starting point?

**Comment by Daviid-P** [comment]
> I love the regular message which are non-editable and with all timestamp. And yes, it is not searhable in the Ticket listing. Shall we create new feature request or using this as starting point?

I think you can edit the issue and change the title, make it something like "Make ticket messages searchable"
