### ISSUE TITLE
 Problem with decimal separator in creating purchase price causing SQL syntax error

### ISSUE THREAD

**Issue by BoguslawBu** [Dolibarr/dolibarr#24053]
### Bug

Hello, when trying to add purchase price to item I see issue connected to decimal separator.

Decimal separator is set to: “,”

![scr4](https://user-images.githubusercontent.com/126334629/221360008-3d4fd0ea-010d-4ea2-833d-ab22f3ad7198.jpg)

`UPDATE llxno_product_fournisseur_price SET fk_user = 1 , ref_fourn = ‘Test item’, desc_fourn = ‘’, price = 26,19, quantity = 20, remise_percent = 0, remise = 0, unitprice = 1,31, fk_availability = 0, multicurrency_price = ‘5.5’, multicurrency_unitprice = ‘0.28’, multicurrency_tx = ‘0.21’, fk_multicurrency = ‘3’, multicurrency_code = ‘EUR’, entity = 1, tva_tx = 0, default_vat_code=null, info_bits = 0, charges = 0, delivery_time_days = null, supplier_reputation = NULL, barcode = NULL, fk_barcode_type = NULL WHERE rowid = 20
[DB_ERROR_SYNTAX] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ‘19, quantity = 20, remise_percent = 0, remise = 0, unitprice = 1,31, fk_avail…’ at line 1`

### Environment Version

16.0.4

### Environment OS

Linux Ubuntu 

### Environment Web server

Apache/2

### Environment PHP

7.4.33

### Environment Database

5.5.5-10.5.17-MariaDB-log

### Environment URL(s)

htdocs/product/fournisseurs.php?id=1

**Comment by atm-maxime** [comment]
I just tried on the version 16.0.5 and I can't reproduce. Even with multi-currency activated, when I have a coma in the price fields the price is correctly saved.
Can you check ?
