### ISSUE TITLE
Separator error if changed language, run well if using language (en_US)

### ISSUE THREAD

**Issue by bordur12** [Dolibarr/dolibarr#24056]
### Bug

Separator error if changed language, run well if using language (en_US)

### Environment Version

16.0.4

### Environment OS

Windows NT LAPTOP-46BUFI10 10.0 build 19043 (Windows 10) AMD64

### Environment Web server

	Apache/2.4.51 (Win64) 

### Environment PHP

PHP/7.3.33

### Environment Database

MySQL or MariaDB 5.5.5-10.6.5-MariaDB

**Comment by ksar-ksar** [comment]
Hello,

Can you post the error message at least ?
