### ISSUE TITLE
Why this check on localtaxes?

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#24065]
### Bug

https://github.com/Dolibarr/dolibarr/blob/49a403b4a578d88ba163a68939f92e472bbcf631/htdocs/core/lib/price.lib.php#L128-L133

I have localtax2 that can be -19, -15 and -7

And I have it set up as such on `llx_c_tva` (honestly it would be way easier to set up localtax 2 separate of tva)
So I wouldn't have to create all the permutations which in a select would end up as
```
TVA 0 - LocalTax2 7
TVA 4 - LocalTax2 7
TVA 5 - LocalTax2 7
TVA 10 - LocalTax2 7
TVA 21 - LocalTax2 7

TVA 0 - LocalTax2 15
TVA 4 - LocalTax2 15
TVA 5 - LocalTax2 15
TVA 10 - LocalTax2 15
TVA 21 - LocalTax2 15

TVA 0 - LocalTax2 19
TVA 4 - LocalTax2 19
TVA 5 - LocalTax2 19
TVA 10 - LocalTax2 19
TVA 21 - LocalTax2 19
```

I could just have 
```
TVA 0
TVA 4
TVA 5
TVA 10
TVA 21

LocalTax2 7
LocalTax2 15
LocalTax2 19
```

![image](https://user-images.githubusercontent.com/7734808/221785376-819580b8-dc29-4d5a-8cb1-fa909fa75356.png)

And I'm ignoring the code (which I have commented out)
```php
// Some test to guess with no need to make database access
if ($mysoc->country_code == 'ES') { // For spain localtaxes 1 and 2, tax is qualified if buyer use local tax
```
and 
```php
// For some country MAIN_GET_LOCALTAXES_VALUES_FROM_THIRDPARTY is forced to on.
if (in_array($mysoc->country_code, array('ES'))) {
    $conf->global->MAIN_GET_LOCALTAXES_VALUES_FROM_THIRDPARTY = 1;
}
```
because aparently this company has some special cases and whatnot, so I'd rather go with a select and have them always specify what tax is added instead of using default values.

### Environment Version

16.0.3

### Expected and actual behavior

As I have set up localtax2 on the tva dictionary I expect the program to use those values when selected.

Instead lines L128-L133 set it to 0 because I can't set `$conf->global->FACTURE_LOCAL_TAX2_OPTION` since not ALL sales are subject to localtax2

Once I commented these lines I created an invoice line with IVA0-IRP19 that set the correct values:

![image](https://user-images.githubusercontent.com/7734808/221789230-3711a25a-e49e-4a17-8933-16fdd28974d6.png)

**Comment by simnandez** [comment]
If you create a new VAT tax, you  must indicate the localtax2 values exactly like the others (-19:-115:-7) and in the customer/vendor tab indicate if it is subject and in what value

**Comment by Daviid-P** [comment]
> If you create a new VAT tax, you must indicate the localtax2 values exactly like the others (-19:-115:-7) and in the customer/vendor tab indicate if it is subject and in what value

What if localtax2 is only applied in some products? I can't set localtax2 to a customer/vendor as default if it's only for a few specific cases.
