### ISSUE TITLE
Third party empty after event modify

### ISSUE THREAD

**Issue by amaurydixx** [Dolibarr/dolibarr#24061]
### Bug

When I modify an event, the third party is set to blank and when i put the third party again, the contact will be blank too.

### Environment Version

16.0.3

### Environment OS

Windows & Mac

**Comment by ReproductriceDeBugs** [comment]
This doesn't seem to occur in v18, everything is working correctly.
Can you provide screenshots?

**Comment by atm-maxime** [comment]
Fixed in 16.0.5
