### ISSUE TITLE
main context supersedes other contexts in hooks

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#24067]
I want to bring this up again, in my case I have my module's hook contexts set up like this.

![image](https://user-images.githubusercontent.com/7734808/214820583-c0d79505-d25a-4e2f-953d-219594d2f415.png)

And when the debugger reaches this line https://github.com/Dolibarr/dolibarr/blob/d36acc63dd68aa2d8382ab4044d848a87ed46456/htdocs/accountancy/bookkeeping/list.php#L1165

it seems like currentcontext is set to `main`, I thought I could just press F5 and the debugger would stop again there and current context would be `bookkeepinglist`

![image](https://user-images.githubusercontent.com/7734808/214820887-64fa5016-d481-462f-8660-0b2c28c9aae1.png)

Should hooks execute once per context? Should the current context be set to the most specific?

_Originally posted by @Daviid-P in https://github.com/Dolibarr/dolibarr/issues/12717#issuecomment-1404859296_

**Comment by Daviid-P** [comment]
My workarround is, 

instead of 

```php
in_array($parameters['currentcontext'], $contexts_in_where_to_run)
```

do this

```php
if (!empty(array_intersect(explode(":", $parameters['context']),  $contexts_in_where_to_run))) {
```

So get 2 arrays of contexts and intersect them, if the result is not an empty array then execute the hooked code.

**Comment by Daviid-P** [comment]
Mor readable way for the workarround:
```php

public function doActions($parameters, &$object, &$action, $hookmanager)
{
	$error = 0; // Error counter
	$this->db->begin();
	$contexts_array = explode(":", $parameters['context']);
	$contexts_where_to_execute_code = array('supplierpaymentcard','paymentcard');
	$matched_contexts = array_intersect($contexts_array, $contexts_where_to_execute_code);
	$in_context = !empty($matched_contexts);
	if ($in_context) {
		$current_context = array_values($matched_contexts)[0];
		switch ($current_context) {
			case 'paymentcard':
				$table = MAIN_DB_PREFIX.'facture';
				$invoice_class = 'Facture';
				break;
			case 'supplierpaymentcard':
				$table = MAIN_DB_PREFIX.'facture_fourn';
				$invoice_class = 'FactureFournisseur';
				break;
		}

		// Do stuff here
	}
	// handle errors
}
```

**Comment by eldy** [comment]
>               I want to bring this up again, in my case I have my module's hook contexts set up like this.
> 
> ![image](https://user-images.githubusercontent.com/7734808/214820583-c0d79505-d25a-4e2f-953d-219594d2f415.png)
> 
> And when the debugger reaches this line https://github.com/Dolibarr/dolibarr/blob/d36acc63dd68aa2d8382ab4044d848a87ed46456/htdocs/accountancy/bookkeeping/list.php#L1165
> 
> it seems like currentcontext is set to `main`, I thought I could just press F5 and the debugger would stop again there and current context would be `bookkeepinglist`
> 
> ![image](https://user-images.githubusercontent.com/7734808/214820887-64fa5016-d481-462f-8660-0b2c28c9aae1.png)
> 
> 
> Should hooks execute once per context? Should the current context be set to the most specific?
> 
> _Originally posted by @Daviid-P in https://github.com/Dolibarr/dolibarr/issues/12717#issuecomment-1404859296_
>             

Yes, hooks are executed only once per call if at least 1 context match.
