### ISSUE TITLE
does not make direct payment Takepos with version 8.1 of PHP

### ISSUE THREAD

**Issue by cistelsa** [Dolibarr/dolibarr#24064]
### Bug

I thought about this issue a lot until I changed the PHP version to 7.4 and it worked, before I had version 8.1 and the problem is that when configuring direct payment in Takepos it doesn't make the payment but stays in "pending payment".

### Environment PHP

8.1

**Comment by andreubisquerra** [comment]
Solved with https://github.com/Dolibarr/dolibarr/pull/25041
