### ISSUE TITLE
Membership end date pre-filled

### ISSUE THREAD

**Issue by dbitouze** [Dolibarr/dolibarr#24082]
### Feature Request

On the `.../adherents/subscription.php?rowid=...&action=addsubscription&token=...` page, the membership date (in fact, the start date) is pre-filled with the date of 1 January of the current year, which is convenient. On the other hand, the end of membership date is empty and needs to be filled in each time. It would be nice for the latter to be pre-filled with that of 31 December of the current year.

AFAICT, the "default value" on page `.../admin/defaultvalues.php`:

- Relative URL: `members/subscription.php?action=addsubscription`
- Field: `end`
- Value: `31/12/2023`

doesn't work.[](url)

### Use case

We use `Dolibarr` (16.0.0, “HR module” enabled) to manage an association of about 100 members. Regardless of its date, the membership applies to the current financial year, i.e. from 1 January to 31 December, without pro rata calculation.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/24099

**Comment by daraelmin** [comment]
Hi @ksar-ksar,

 I think this one could be closed as theses PR:
 https://github.com/Dolibarr/dolibarr/pull/26428 
https://github.com/Dolibarr/dolibarr/pull/24099
have been merged

Cheers
