### ISSUE TITLE
Modify product extra field (mass action) : translation not done

### ISSUE THREAD

**Issue by code42fr** [Dolibarr/dolibarr#24080]
### Bug

When we use mass action "modify extra field" on product listing, the extra field select values are not translated.

### Environment Version

16.0.4

### Environment OS

Linux homestead 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64

### Environment Web server

Apache/2.4.41 (Ubuntu)

### Environment PHP

7.4.33

### Environment Database

MySQL or MariaDB 8.0.31-0ubuntu0.20.04.1

### Environment URL(s)

/product/list.php

### Expected and actual behavior

Values in extra field select should be translated using $langs->trans() function.

In this case, values in extra field select should be :  
- "Attribut supplémentaire 2"
- "Attribut supplémentaire 1"
- "Attribut supplémentaire 3"

### Steps to reproduce the behavior

- Add a product extrafield with translation key
- Add translation of translation key
- Go to product listing
- Select one product or more
- Select "Modify extra field" mass action
- Extra field select values are not translated

### Attached files

![1](https://user-images.githubusercontent.com/9167207/222087129-b917a60b-445e-4472-9478-aa4471d5838f.png)

![2](https://user-images.githubusercontent.com/9167207/222087134-93e9e601-afbb-421e-b61b-d429ee12c093.png)

![3](https://user-images.githubusercontent.com/9167207/222087137-52c21f15-f8eb-4a26-9c16-426b0e6a87d4.png)

**Comment by atm-maxime** [comment]
Fixed
