### ISSUE TITLE
Graph for projects not showing

### ISSUE THREAD

**Issue by milenmk** [Dolibarr/dolibarr#24097]
### Bug

When opening `projet/index.php`, the graph is not showing. Labels are visible but not the graph. Tested after upgrade from 16.0.3 to 16.0.4.

Then tested on a fresh install of v17 on PHP 7.4.33, and then on PHP 8.2 - still not visible

### Environment Version

16.0.3, 16.0.4, 17.0.0

### Environment OS

Windows, Linux

### Environment Web server

apache 2.4.41 / 2.4.54

### Environment PHP

7.3.33, 7.4.33, 8.2.0

### Steps to reproduce the behavior

![Screenshot_1](https://user-images.githubusercontent.com/4587305/222513282-59617297-63cd-4052-940b-271be4197d9d.png)

**Comment by KiVoilaJe** [comment]
I tested it on v17 and it works
![Capture d’écran du 2023-06-30 09-46-19](https://github.com/Dolibarr/dolibarr/assets/36703787/fdb25626-f9b4-4ff3-a0ce-14da2942bafc)
