### ISSUE TITLE
Update Error 16.0.4 to 17.0.0

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#24122]
### Bug

I had the below error when updating

Error DB_ERROR_1833: ALTER TABLE llx_accounting_system MODIFY COLUMN pcg_version varchar(32) NOT NULL;
Cannot change column 'pcg_version': used in a foreign key constraint 'fk_accounting_account_fk_pcg_version' of table 'barr.llx_accounting_account'

### Environment Version

16.0.4 to 17.0.0

### Environment OS

Debian 11

### Environment Web server

Apache

### Environment PHP

7.4.33

### Environment Database

MariaDB version 10.5.18

**Comment by hasse-basse** [comment]
I solved by  the below solution. Can this cause issuses later?


Drop the foreign key constraint 'fk_accounting_account_fk_pcg_version' of table 'barr.llx_accounting_account' using the following command:

`ALTER TABLE llx_accounting_account DROP FOREIGN KEY fk_accounting_account_fk_pcg_version;`

**Comment by MuschelInBlau** [comment]
I have the same Issue with the same Enviroment... :( I will wait for a fix... dont wanna crash my dolibarr. I will wait/hope for a offical feedback ;D

**Comment by hasse-basse** [comment]
Yeah, I went back to the backup and will remain there until there’ a solution.

**Comment by hregis** [comment]
@hasse-basse @MuschelInBlau 
https://github.com/Dolibarr/dolibarr/pull/24130

**Comment by hasse-basse** [comment]
Closing this reffering to @hregis pull request mentionned above.
