### ISSUE TITLE
Missing settings - V17 - Proposal - Bill

### ISSUE THREAD

**Issue by philou15** [Dolibarr/dolibarr#24129]
### Bug

Hye
Sorry For my english
I update Dolibarr V16 to V17 and now, on propal and bill the setting for text on bottom is not present. 

J'ai fait la mise a jour de V16 a V17 et depuis je n'ai plus les réglages dans les parametres pour les mentions complementaires sur les devis et factures. 

### Environment Version

V17

### Environment OS

Linux

### Environment Web server

Apache 2.4.52 ubuntu

### Environment PHP

7.4.32

### Environment Database

	MySQL or MariaDB 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1

### Attached files

![V17](https://user-images.githubusercontent.com/11060597/223031133-a5de28ae-1936-4c2b-a6d6-5ff2e0453f09.png)

**Comment by hregis** [comment]
@philou15 tu dois avoir une erreur php avec un modèle pdf qui du coup bloque l'affichage du reste des paramètres, vérifie les logs d'erreurs php.

**Comment by philou15** [comment]
Peut tu me dire comment les voirs les logs ? 
merci

**Comment by philou15** [comment]
Ah, peut etre ça : 
`[Mon Mar 06 00:00:08.745853 2023] [ssl:warn] [pid 172700] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Mon Mar 06 00:00:08.746195 2023] [mpm_prefork:notice] [pid 172700] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Mon Mar 06 00:00:08.746210 2023] [core:notice] [pid 172700] AH00094: Command line: '/usr/sbin/apache2'
[Mon Mar 06 06:42:35.662706 2023] [proxy_fcgi:error] [pid 390374] [client 192.168.1.1:44202] AH01071: Got error 'PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221', referer: https://82.64.97.254:2202/erp/index.php?mainmenu=home
[Mon Mar 06 06:42:39.641056 2023] [proxy_fcgi:error] [pid 392045] [client 192.168.1.1:44216] AH01071: Got error 'PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221', referer: https://82.64.97.254:2202/erp/index.php?mainmenu=home
[Mon Mar 06 06:42:50.215889 2023] [proxy_fcgi:error] [pid 390372] [client 192.168.1.1:44252] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://82.64.97.254:2202/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 06:42:57.757423 2023] [proxy_fcgi:error] [pid 392044] [client 192.168.1.1:44260] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://82.64.97.254:2202/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 07:00:50.944964 2023] [proxy_fcgi:error] [pid 390373] [client 192.168.1.215:49336] AH01071: Got error 'PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221', referer: https://192.168.1.4/erp/
[Mon Mar 06 07:03:18.783830 2023] [proxy_fcgi:error] [pid 392043] [client 192.168.1.215:49970] AH01071: Got error 'PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221', referer: https://192.168.1.4/erp/
[Mon Mar 06 07:03:26.928981 2023] [proxy_fcgi:error] [pid 392073] [client 192.168.1.215:49986] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 07:19:58.629241 2023] [proxy_fcgi:error] [pid 392078] [client 192.168.1.215:53592] AH01071: Got error 'PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221'
[Mon Mar 06 07:20:56.643021 2023] [proxy_fcgi:error] [pid 392281] [client 192.168.1.215:53740] AH01071: Got error 'PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/FactureStats_getAllByProductEntry_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 331PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getNbByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 119PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 120PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/philou15/www/htdocs/core/class/stats.class.php on line 121PHP message: PHP Warning:  fopen(/home/philou15/www/documents/users/temp/CommandeStats_getAmountByMonthWithPrevYear_customer_fr_FR_entity.1_user1.cache): failed to open stream: Permission denied in /home/philou15/www/htdocs/core/class/stats.class.php on line 221', referer: https://192.168.1.4/erp/comm/index.php?mainmenu=commercial&leftmenu=
[Mon Mar 06 07:21:02.866458 2023] [proxy_fcgi:error] [pid 390374] [client 192.168.1.215:53743] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 07:21:04.510210 2023] [proxy_fcgi:error] [pid 390374] [client 192.168.1.215:53743] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 07:21:12.557218 2023] [proxy_fcgi:error] [pid 392046] [client 192.168.1.215:53742] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 07:21:25.420414 2023] [proxy_fcgi:error] [pid 390373] [client 192.168.1.215:53795] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 07:21:35.731947 2023] [proxy_fcgi:error] [pid 392078] [client 192.168.1.215:53820] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home
[Mon Mar 06 07:21:51.699487 2023] [proxy_fcgi:error] [pid 392281] [client 192.168.1.215:53850] AH01071: Got error 'PHP message: PHP Fatal error:  Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home
`

**Comment by hregis** [comment]
@philou15 donc voilà le soucis : 
`Got error 'PHP message: PHP Fatal error: Access level to pdf_echeancier::$marge_gauche must be public (as in class ModelePDFPropales) in /home/philou15/www/htdocs/custom/echeancier/core/modules/propale/doc/pdf_echeancier.modules.php on line 0', referer: https://192.168.1.4/erp/admin/modules.php?mainmenu=home`

`pdf_echeancier.modules.php` n'est pas un modèle Dolibarr par défaut et il ne doit plus être compatible

**Comment by philou15** [comment]
Module desactivé, toujours pareil. 
D'ailleur j'ai supprimer le log pour voir si il allait refaire des erreurs. et bien non.. 
bizard

**Comment by hregis** [comment]
@philou15 il faudrait désactiver tous les modules complémentaires et voir ce que ça donne

**Comment by philou15** [comment]
Echeancier + Sous total...... 

Fais c**ier 

Deux modules importants pour moi 
Merci

**Comment by hregis** [comment]
@philou15 il faut demander des mises à jour aux développeurs de ces modules

**Comment by philou15** [comment]
Oui je vais le faire, a leur bon vouloir :) 
Mais dolibarr integre un paiement par echeance, peut'on faire plusieurs echeance ou remplacer echeancier justement ? 
merci
