### ISSUE TITLE
Bug: Cannot access menu : Dictionnary - Holiday - Type

### ISSUE THREAD

**Issue by Dounia-kazi** [Dolibarr/dolibarr#24120]
# Instructions
*Cannot access menu :*
*Dictionnary - Holiday - Type*

# Bug
[Error message : This website or feature is currently temporarly not available or failed after a technical error.

This may be due to a maintenance operation. Current status of operation (2023-03-04T10:55:04Z) are on next line...

Dolibarr a détecté une erreur technique. Vous pouvez lire le fichier log ou définir l'option $dolibarr_main_prod sur '0' dans votre fichier de configuration pour obtenir plus d'informations.]

## Environment
- **Version**: 16.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.33
- **Database**: MySQL or MariaDB 5.7.41-log
- **URL(s)**: /htdocs/admin/dict.php?id=28

## Expected and actual behavior
[access to menu Dictionnary - Holiday - Type]

## Steps to reproduce the behavior
[go to menu  Dictionnary - Holiday - Type ]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Report
- **Multicompany**: 16.0.0

**Comment by Larsene** [comment]
same for me

**Comment by Larsene** [comment]
This is related to https://github.com/Dolibarr/dolibarr/issues/22447

This correct the bug : https://github.com/Dolibarr/dolibarr/issues/22447#issuecomment-1260932678

`ALTER TABLE llx_c_holiday_types ADD COLUMN block_if_negative integer NOT NULL DEFAULT 0 AFTER fk_country;`
