### ISSUE TITLE
Migration issue 15.0.4 -> 17.0.0: SQL error on "birthday for this month"

### ISSUE THREAD

**Issue by alexandre-janniaux** [Dolibarr/dolibarr#24138]
### Bug

After migrating from 15.0.4 to 17.0.0, the following error happens in the birthday panel (in french "anniversaire de ce mois").

```
 ERROR: 0A000: invalid UNION/INTERSECT/EXCEPT ORDER BY clause LINE 1: ...te_format( u.dateemployment, '%c') = '3' ORDER BY DAY(datea)... ^ DETAIL: Only result column names can be used, not expressions or functions. HINT: Add the expression/function to every SELECT, or move the UNION into a FROM clause. LOCATION: transformSetOperationStmt, analyze.c:1776 sql=SELECT u.rowid, u.firstname, u.lastname, u.birth as datea, 'birth' as typea,…
```

There were no errors in 15.0.4.

### Environment Version

17.0.0

### Environment OS

Debian bullseye

### Environment Web server

Nginx

### Environment PHP

PHP 7.4

### Environment Database

Postgres Scaleway

### Expected and actual behavior

Expected : no birthday this month

Actual behaviour: SQL error message

### Steps to reproduce the behavior

Install a 15.0.4 instance, upgrade to 17.0.0 with `php upgrade.php / upgrade2.php 15.0.4 17.0.0`.

I can produce such instance in a few days to ensure it can be reproduced from scratch, and share database anyway.

### Attached files

In 15.0.4:

![image](https://user-images.githubusercontent.com/413037/223069421-93b1c754-966c-4674-a9aa-36cb23d4b650.png)

In 17.0.0:

![image](https://user-images.githubusercontent.com/413037/223069325-11441485-d1f8-4458-a795-4c766e18e795.png)

**Comment by lastmikoi** [comment]
Reproduced the bug on Dolibarr 17.0, RockyLinux 8, Apache HTTPd 2.4, PHP 7.4 & PostgreSQL 12.

It turns out https://github.com/Dolibarr/dolibarr/pull/21631/files has introduced a SQL query that isn't compatible with PostgreSQL.

The full PostgreSQL error is as follows:

```sql
SELECT u.rowid, u.firstname, u.lastname, u.birth as datea, 'birth' as typea, u.email, u.statut as status FROM llx_user as u WHERE u.entity IN (0,1) AND u.statut = 1 AND  date_format( u.birth, '%c') = '3' UNION SELECT u.rowid, u.firstname, u.lastname, u.dateemployment as datea, 'employment' as typea, u.email, u.statut as status FROM llx_user as u WHERE u.entity IN (0,1) AND u.statut = 1 AND  date_format( u.dateemployment, '%c') = '3' ORDER BY DAY(datea) ASC;
ERROR:  invalid UNION/INTERSECT/EXCEPT ORDER BY clause
LINE 1: ...te_format( u.dateemployment, '%c') = '3' ORDER BY DAY(datea)...
                                                             ^
DETAIL:  Only result column names can be used, not expressions or functions.
HINT:  Add the expression/function to every SELECT, or move the UNION into a FROM clause.
```

I've managed to hotfix the issue with the following unpublished patch: https://github.com/Dolibarr/dolibarr/commit/8be998a9066d5f5c9d3282f106f8c9f81e833357

I'm however not familiar enough with Dolibarr and SQL to be confident in how my fix will impact MariaDB/MySQL deployments, so I would welcome feedback about the proposed patch.

**Comment by lastmikoi** [comment]
@atm-maxime feels like to me you're the most likely to know about whether my hotfix would work, but I may be mistaken. Is there a specific reason to specifically sort on the day of the month instead of the the whole birthday date ? If so, my fix would not be correct.

**Comment by atm-maxime** [comment]
@lastmikoi yes there is a reason. If I sort on the day of the month, it's to have them in the correct way. Otherwise the 31th of March 2012 would appear before the 1st of March 2023.
If I introduced a pgsql incompatibility, my bad, I don't master this dbtype enough :)

**Comment by lastmikoi** [comment]
Oooh that's right ! the birthday's year is the... birth year, not the current year. That's a facepalm for me on this one :laughing:
