### ISSUE TITLE
Missing Column for User Module in llx_const Table During Dolibarr 17.0.0 Installation

### ISSUE THREAD

**Issue by RoodyCode** [Dolibarr/dolibarr#24139]
### Bug

When I installed Dolibarr 17.0.0, I noticed that the user module was not activated and I couldn't find a corresponding column for it in the llx_const table. As a result, I had to manually insert a new column in the table in order to activate the module. It would be great if this issue could be addressed in a future release to save users from having to modify the database themselves.

### Environment Version

17.0.0

### Environment OS

Debian

### Environment Web server

Apache

### Environment PHP

8.1

### Environment Database

MySQL

### Steps to reproduce the behavior

Fresh installation of Dolibarr 17.0.0

**Comment by virtualvox** [comment]
Hi RoodyCode,

I have the same problem. Would you like to tell me which data you inserted into the llx_const table to make it work?

Thanks in advance
Dominik

**Comment by RoodyCode** [comment]
@virtualvox 
Sure, I added "MAIN_MODULE_USER"
