### ISSUE TITLE
Oauth Office 365

### ISSUE THREAD

**Issue by Fado84** [Dolibarr/dolibarr#24163]
### Bug

Hi,
I have a problem with OAuth services andemail collector. I generate the token but when I try to login in email collector I receive this error:

>> TAG1 AUTHENTICATE XOAUTH2 dX_blabla << NO AUTHENTICATE failed.

I tryed with differents scope:
https://outlook.office365.com/IMAP.AccessAsUser.All
https://outlook.office.com/IMAP.AccessAsUser.All
https://graph.microsoft.com/IMAP.AccessAsUser.All

But I still have the same issue..

Any suggestion??

Please let me know if i do something wrong.

Kind Regards

### Environment Version

17.0

### Attached files

![do1](https://user-images.githubusercontent.com/66804075/223814199-38bf5441-bd41-4ace-bada-b26eaace58a2.JPG)
![do2](https://user-images.githubusercontent.com/66804075/223816798-39753351-b02f-4fa1-8289-0971b163f92a.JPG)

**Comment by sebcapside** [comment]
hi, same issue Dolibarr 17, token is ok in oauth tab, but collector is in error :
connection setup failed - authenticate

**Comment by Fado84** [comment]
Hi, 
I found a solution (i hope). Please read my solution in the forum:

https://www.dolibarr.org/forum/t/oauth-office-365-and-email-collector/23437

I hope the developers find and try my solution..

**Comment by rmdes** [comment]
Any news about this ? 

`Échec de l'envoi de l'email (émetteur=*************@************.com>, destinataire=**********@*****.**)
Error [120]: Ran into problems sending Mail. Response: 535 5.7.3 Authentication unsuccessful [AM0PR02CA0173.eurprd02.prod.outlook.com 2025-06-03T12:41:34.433Z 08DDA2768592275C] Error [130]: Error when asking for AUTH XOAUTH2 Error [130]: Invalid Authentication Credentials.`
