### ISSUE TITLE
Create expedition without commande

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#24178]
### Feature Request

Create expedition without commande

### Use case

Creating shipments to our own warehouses in other cities generates an output, it is not a sale to a customer.

### Suggested implementation

Implement expedition card with action=create

### Suggested steps

Module products, Sends, New send.

**Comment by josett225** [comment]
@leninrivas 
In my side I have same needs as we have multiple warehouses. 
As a workaround, we are using advanced stock feature available starting v16 il I am not wrong.

**Comment by josett225** [comment]
If I am not wrong this is linked 

https://github.com/Dolibarr/dolibarr/pull/28975
