### ISSUE TITLE
WYSIWYG by default

### ISSUE THREAD

**Issue by Thatoo** [Dolibarr/dolibarr#24172]
### Feature Request

Not so much a feature request but an enhancement request : activate the WYSIWYG editor module by default.

### Use case

I witness some dolibarr users using dolibarr for a while without it and complaining that Dolibarr was lacking edition functionality until I showed them they needed to activate the WYSIWYG editor module.
I guess most of people need this module and will apprecaite to have it working by default and those who don't want it will find a way to deactivate it.

**Comment by sonikf** [comment]
Hi @ksar-ksar 
Please close this, it has been implemented
