### ISSUE TITLE
from release 16 onwards: pdf merge result for Intervention doesn't show up

### ISSUE THREAD

**Issue by Rendscode** [Dolibarr/dolibarr#24185]
### Bug

The merged file doesn't show up after performing a pdf merge for object type "Intervention".
The merged file is being created and can be found in the documents folder, but that's inconvenient.

I would expect the link to the merged file being displayed below the single files.

This has to be considered as a bug, because it worked up to release 15 and still works in current versions for all other relevant object's I've tested.

### Environment Version

16 and newer, including alpha of R18

### Environment OS

Linux Debian 5.10

### Environment Web server

Apache

### Environment PHP

8.1

### Environment Database

MariaDB 10.5.18

### Environment URL(s)

/htdocs/fichinter/list.php?leftmenu=ficheinter

### Expected and actual behavior

I would expect the link to the merged file being displayed below the single files.
Instead the file is being created and can be found in the respective subfolder of the document folder, but there's no link displayed in the window.

### Module Commerce, section Interventions:
* Create more than one object of type interventions, including the validation, so that a pdf document is generated for each object
* Navigate to Interventions -> list
* Select at least two objects via the checkbox
* Select action -> pdf merge, confirm
* Realise the pop up message that a document has been created
* Realise that no result link is being displayed.
* Navigate to document subfolder and find the merged pdf

**Comment by Timoune974** [comment]
For info 
Same issue, in V17.0.1 corrected by modify fichinter/list.php

at the end of the file , i removed line 920 _if (in_array('builddoc', $arrayofmassactions) && ($nbtotalofrecords === '' || $nbtotalofrecords))_
don't forget to remove the closing bracket in line 938

**Comment by catrielr** [comment]
Same issue in version 18.0.2 /htdocs/commande/list.php
FIX:  line 2776
`//if (in_array('builddoc', $arrayofmassactions) && ($nbtotalofrecords === '' || $nbtotalofrecords)) {
if ($contextpage != 'poslist') {
`

**Comment by routmoute** [comment]
Same in "Sales Orders" with Dolibarr v18.0.4, pdf are merged but not showing in list.

**Comment by routmoute** [comment]
I see it's already fixed in develop branch for all lists:
https://github.com/Dolibarr/dolibarr/blob/961deffd352844a0e10de457aaef81df5d1d1730/htdocs/commande/list.php#L2793

Why not use
```php
array_key_exists('builddoc', $arrayofmassactions)
```
instead of
```php
in_array('builddoc', array_keys($arrayofmassactions))
```
?

And how to have this fix in next release ? You need a PR @eldy ?
Thank you

**Comment by eldy** [comment]
No reason for in_array compared to array_key_exists. Same result.

Because PR has been merged in develop branch it will be available in next release (v19).
To have it into a maintenance release of an old version, you can make a pr into an old branch (branch v17, 18, ...)

**Comment by routmoute** [comment]
nice, I will do that. thank you.
