### ISSUE TITLE
Bug: No update date and hour in line of intervention

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#24190]
To edit line.
Update date not change and the hour change 00.

# Bug
[*Short description*]

## Environment
- **Version**: 17.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /fichinter/card.php?id=846

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
Try change date 10/03/2023 and hour 16:30
![Screenshot_248](https://user-images.githubusercontent.com/53640168/224481509-77838087-e978-46c1-a1c0-dfbb061120a1.png)

**Comment by aspangaro** [comment]
Fix in v17.0.2 on https://github.com/Dolibarr/dolibarr/commit/077c3312cea9f58396e9000f266608ac83c53fb7
