### ISSUE TITLE
PROJECT_ELEMENTS_FOR_MINUS_MARGIN doesn't work. 

### ISSUE THREAD

**Issue by fparrar** [Dolibarr/dolibarr#24192]
### Bug

I'm trying to minus project margin that has an intervention (60€ estimated) but it returns N/A. I tried the PROJECT_ELEMENTS_FOR_MINUS_MARGIN command but still not working

### Environment Version

17

### Attached files

![image](https://user-images.githubusercontent.com/49676621/224512384-bc783121-f966-49ad-8c57-ef2d28fe234b.png)
![image](https://user-images.githubusercontent.com/49676621/224512441-f7760782-ed57-43a1-91c4-031983fd23be.png)
![image](https://user-images.githubusercontent.com/49676621/224512468-3a9b132d-876b-47a2-be09-2154101241bf.png)

**Comment by inoveaconseil** [comment]
This constant defined the object to minus margin of project. To write it for example propal, invoice
