### ISSUE TITLE
v16.0.3 - BUG - Import Stock - "Ref not taken into account when starting with 0000"

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#24195]
### Bug

When a product has a reference like "0000000001893" for example, the import procedure does not update the related stock.

No warning is given to the user, no stock updated.

Sample file : 
[SAMPLE_import_stock_2023-03-12_v2 copie.xlsx](https://github.com/Dolibarr/dolibarr/files/10951425/SAMPLE_import_stock_2023-03-12_v2.copie.xlsx)

How to reproduce : 
1. Create a sample product : 
![image](https://user-images.githubusercontent.com/26635105/224558453-8e176d43-908b-4399-a5c7-1a555e5bd1ea.png)

2. Upload stock using the reference 

--> nothing will be updated.

### Environment Version

v16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

http://xxx/imports/import.php?leftmenu=import

**Comment by AurelienBISOTTI** [comment]
Cannot reproduce in V18
![Capture d’écran du 2023-06-10 18-01-33](https://github.com/Dolibarr/dolibarr/assets/12530585/eace7dac-f184-4e9f-b6cc-3cdf74ad5af1)
![Capture d’écran du 2023-06-10 18-01-52](https://github.com/Dolibarr/dolibarr/assets/12530585/054d052c-57da-45a1-a1a1-b6808dc9d1c3)

**Comment by daxitsolutions** [comment]
if ok on 18, we can close the case.
