### ISSUE TITLE
v16.0.3 - BUG - Layout on invoice doesn't take into account long text on Additional statement

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#24202]
### Bug

When addong an "Additional statement" on invoices from the module configuration, there is no restriction on the length of the content. 
Therefore when you have a text with more than 10 lines, the PDF is messy
Used PDF model for the invoice : Crabe

Example of a text thatwe would like to add on the invoice : 

![Configuration_du_module_Factures](https://user-images.githubusercontent.com/26635105/224924600-202b26c3-e8ce-408b-9bcc-8c20bfe5adcf.png)

The related PDF 
![Facture_client_-_Fiche](https://user-images.githubusercontent.com/26635105/224924831-c9e00ba6-c6f9-47ac-b5bc-bbb55827ee3f.png)

### Environment Version

v16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

/admin/facture.php & /compta/facture/card.php

### Expected and actual behavior

The text should jump to another page

**Comment by AurelienBISOTTI** [comment]
I don't see why this would be a bug.

Use less text.

You might eventually ask for a new function that limit the number of characters depending on PDF model, but I don't think that's worth it
