### ISSUE TITLE
v17.0.0 upload of external module fails to copy from incorrectly generated temp source dir

### ISSUE THREAD

**Issue by vdegrandpre** [Dolibarr/dolibarr#24201]
### Bug

Since 17.0.0 it is not possible to install an external module using the provided form because the system fails to copy from an unexisting source path.

Not related to file permission, but bad source file path.

![Capture d’écran de 2023-03-13 20-42-25](https://user-images.githubusercontent.com/3855975/224863344-8155e91a-c0ba-421d-8e4a-f475575e4e24.png)

### Environment Version

17.0.0

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.4, 8.1

### Environment Database

MySQL

### Environment URL(s)

/admin/modules.php

### Expected and actual behavior

**Expected**

Uploading a custom module shall copy it to /htdocs/custom/ folder and install the module.

**Actual**

System is trying to copy a source folder that does not exzist, therefore breaking the installation of external module.
In detail, the system append a _htdocs_ folder in the temporary path of the uploaded module, that does not exist on disk, creating the error.

![Capture d’écran de 2023-03-13 20-35-29](https://user-images.githubusercontent.com/3855975/224862471-c19a7bfb-a2d2-483a-be4e-d19511cc0d25.png)

### Steps to reproduce the behavior

Upload any external module using the form in /admin/modules.php .

### Attached files

![Capture d’écran de 2023-03-13 20-35-29](https://user-images.githubusercontent.com/3855975/224862509-ca08b307-d293-4773-8c59-2c6682cbdab8.png)

![Capture d’écran de 2023-03-13 20-37-05](https://user-images.githubusercontent.com/3855975/224862647-ffedd1e5-b3ab-42f9-9eee-34e27e4d6aac.png)

**Comment by sonikf** [comment]
I can confirm the bug,
Correct path should be
 /documents/admin/temp/module_modulename-x.x.dir/modulename 
instead of 
/documents/admin/temp/module_modulename-x.x.dir/**htdocs**/modulename
