### ISSUE TITLE
Payments List doesn't show. But I think I've an easy fix for you.

### ISSUE THREAD

**Issue by Crooked-Krokr** [Dolibarr/dolibarr#24211]
### Bug

When trying to reach the list of payments in the module "Commerce>Vendor invoices>Payments" the page goes blank. I think that is because the link for this is "/fourn/facture/paiement.php?mainmenu=billing&leftmenu=suppliers_bills_payment" when it should be "fourn/paiement/list.php?mainmenu=billing&leftmenu=suppliers_bills_payment" instead.

Hope that helps. :)

### Environment Version

v15 to v17

### Environment OS

Ubuntu 20

### Environment Web server

Apache2

### Environment PHP

17 i think

**Comment by simnandez** [comment]
Works for me in v15, v16 and V17, in all versions the link is "/fourn/paiement/list.php" 
![vendor_payments]
(https://user-images.githubusercontent.com/881833/226057664-4f8c460f-65a3-45ec-990c-db8ae0d834f9.png)
