### ISSUE TITLE
VAT not applied for products and services with VAT configured

### ISSUE THREAD

**Issue by paddatrapper** [Dolibarr/dolibarr#24217]
### Bug

When adding existing services to a vendor's invoice, the VAT associated with them is not included. The VAT rate is always 0%. This is a new bug with 17.0.0

Could be related to the Sales Tax Used option being 'Not used', but this worked as expected before the upgrade

### Environment Version

17.0.0

### Expected and actual behavior

The VAT rate configured in the service should be brought into the vendor quote

### Steps to reproduce the behavior

1. Configure a service with a VAT rate for buying
2. Create a vendor invoice
3. Add the service as a line item
4. Observe the VAT rate to be 0%

**Comment by simnandez** [comment]
It works for me, are you sure that the seller is located in a country where VAT is applied?

Tax rate follows  standard rule:
If the seller is not subject to VAT, then VAT defaults to 0. 
If the (seller's country = buyer's country), then VAT by default equals VAT of the product in the seller's country. 
If the seller and buyer are both in the European Community and goods are transport-related products (haulage, shipping, airline), the default VAT is 0. This rule is dependant on the seller's country - please consult with your accountant. The VAT should be paid by the buyer to the customs office in their country and not to the seller.
If the seller and buyer are both in the European Community and the buyer is not a company (with a registered intra-Community VAT number) then the VAT defaults to the VAT rate of the seller's country.
If the seller and buyer are both in the European Community and the buyer is a company (with a registered intra-Community VAT number), then the VAT is 0 by default. 
In any other case the proposed default VAT=0.

**Comment by paddatrapper** [comment]
Yes, both the company and the supplier/client are in the same country, subject to 15% VAT. It was working correctly in 16.0.4, but is not after upgrading to 17.0.0 without changing anything around the service, company or suppliers/clients

**Comment by sonikf** [comment]
I can confirm this bug. Everything works fine in 17.0.0-beta
