### ISSUE TITLE
E-mail (multipart HTML) not sent correctly on PHP 8.1

### ISSUE THREAD

**Issue by gertvermeersch** [Dolibarr/dolibarr#24222]
I recently upgrade my webserver to php 8.1. My clients complained about malformed mails which seems to go away when switching back to PHP 7.4. I used the Test mail function with the same results. I use the PHP mail function.

Emails are received as follows (in plain text):

This is a message with multiple parts in MIME format.
--multipart_x.1678644108.x_boundary
Content-Type: multipart/alternative;
 boundary="mul_780c5cfc7a756041a93ab742d447c162"

--mul_780c5cfc7a756041a93ab742d447c162
Content-Type: text/plain; charset=UTF-8

// message continyes, then comes the html:

--mul_780c5cfc7a756041a93ab742d447c162
Content-Type: text/html; charset=UTF-8

<html><head><title></title></head><body>Beste klant,<br />
<br />

// next comes the pdf 

--mul_780c5cfc7a756041a93ab742d447c162--

--multipart_x.1678644108.x_boundary
Content-Disposition: attachment; filename="F0165.pdf"
Content-Type: application/pdf; name="F0165.pdf"
Content-Transfer-Encoding: base64
Content-Description: F0165.pdf

JVBERi0xLjcKJeLjz9MKNiAwIG9iago8PCAvVHlwZSAvUGFnZSAvUGFyZW50IDEgMCBSIC9MYXN0
TW9kaWZpZWQgKEQ6MjAyMzAzMTIxOTAxMTYrMDEnMDAnKSAvUmVzb3VyY2VzIDIgMCBSIC9NZWRp
YUJveCBbMC4wMDAwMDAgMC4wMDAwMDAgNTk1LjI3NTU5MSA4NDEuODg5NzY0XSAvQ3JvcEJveCBb

// and so on

**Comment by ksar-ksar** [comment]
Hello,

What is your Dolibarr version?

**Comment by gertvermeersch** [comment]
Hi, I'm using 17.0.0
