### ISSUE TITLE
v17.0.0  Customer invoice: Text in the free text field is not encoded when creating the pdf file from an odt template

### ISSUE THREAD

**Issue by lucky4ever2** [Dolibarr/dolibarr#24224]
### Bug

If a text in the free text field contains umlauts. E.g. äöü, or has a formatting, these are shown as source code but not as characters.
Here is an example:

Text in free text field:
`Free text: ökjögsdg9@+´ß0ßt428 test`

Text in PDF:
`Free text: &ouml;kj&ouml;gsdg9@+&acute;&szlig;0&szlig;t428 <strong>test</strong>`

In the ODT Template we use the {line_desc} and {line_product_label} tag.
If the text comes on a predefined products/services, the encoding works.

We only have the problem after the update from 14.0.4 to 17.0.0.
With version 14.0.4 there is no problem and we haven't changed anything else

### Environment Version

17.0.0

### Environment OS

Ubtuntu 20.04

### Environment Web server

Apache2.4

### Environment PHP

7.4

**Comment by KlaasOl** [comment]
Has to do with FCK editor. In the setup there is a warning not to use this editor in the product details. The best thing to do is to disable this function on this place.

**Comment by fappels** [comment]
If you should still have problems even without FCK editor, please re-open.
