### ISSUE TITLE
Leave will not show on agenda

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#24242]
### Bug

When staff create a leave , that will not show on leave agenda view .
![image](https://user-images.githubusercontent.com/78349579/225770971-7d8264a8-f519-4993-a20c-f7063981334c.png)

![image](https://user-images.githubusercontent.com/78349579/225771219-8a51e084-dd0e-46ff-8c29-09f78ff3cd7a.png)

### Environment Version

v16.0.3 and v16.0.4

### Environment OS

Deian 10

### Environment Web server

Apache/2.4.38 Apache/2.4.41

### Environment PHP

 7.4.33

### Environment Database

5.5.5-10.5.15-MariaDB-0+deb11u1

### Environment URL(s)

/comm/action/index.php?mode=show_month&year=&month=&day=&contextpage=actioncommlist&search_filtert=6&search_showbirthday=1

### Expected and actual behavior

When create a new leave , the leave days will show on agenda .
And if i click the  leave check box on agenda , leave days will show up .

### Steps to reproduce the behavior

Request any days to leave , then go to genda to see if those days show up or not ( have to choose " LEAVE " calendar and go to next month then go back to check . ) .

**Comment by simnandez** [comment]
It works well, when i create a new leave it is showing on agenda if the leave check is checked

**Comment by trekmorris** [comment]
Hi 

What is your dolibarr version and what is your host OS ?

**Comment by simnandez** [comment]
I have tested it onto :
Dolibarr 16.0.5, php 7.4
Dolibarr 16.0.5, php 8.0

**Comment by trekmorris** [comment]
Hi 
I found the problem is .
The fullcalendar module on dolistore make this issue .
