### ISSUE TITLE
v17.0.0 - New BOM product field show only raw material instead of finished product

### ISSUE THREAD

**Issue by ojaulent** [Dolibarr/dolibarr#24241]
Hi,

On v17.0.0 when creating a new BOM, we have to bind it to a finished product.
But in the product list there is only raw materials instead of finished product.

Regards,

Olivier

**Comment by frank6106** [comment]
Had the same problem. Seems to be sql-language.
Find /htdocs/bom/class/bom.class.php.

Around Line 106 change (finished:!=:0) to (finished:<>:0)

		'fk_product' => array('type'=>'integer:Product:product/class/product.class.php:1:(finished:<>:0)', 'label'=>'Product', 'picto'=>'product', 'enabled'=>1, 'visible'=>1, 'position'=>35, 'notnull'=>1, 'index'=>1, 'help'=>'ProductBOMHelp', 'css'=>'maxwidth500', 'csslist'=>'tdoverflowmax100'),

**Comment by syrinx75** [comment]
Same problem here.

**Comment by priojk** [comment]
Please check with the latest v17, I think this is fixed already.
