### ISSUE TITLE
Extrafield TicketPublic interface

### ISSUE THREAD

**Issue by MaximilienR-easya** [Dolibarr/dolibarr#24250]
### Feature Request

I would like to have the possibility to choose if I want to display specific extrafields on the ticket public interface or not.

### Use case

For example, there are some extrafields that I need to display on the public ticket interface, but others that I don’t want to see on them. So I would like to have the possibility to choose whether or not I want to show them.

### Suggested implementation

I have two options :

    1. Add numbers on the creation page of extrafields for the visibility variable

    2. Add on the ticket module the possibility to choose the extrafields I want to display among the available ones.

**Comment by MaximilienR-easya** [comment]
Hello @eldy ,
I would like to have your opinion on the question before starting to develop this feature

**Comment by eldy** [comment]
Hi, you can already define if an extrafield is visible on public page or not because you can enter an expression.
For example if you enter 
preg_match('/public/', $_SERVER['PHP_SELF'])?0:1
You will have field hidden on public page.
