### ISSUE TITLE
Bug on TakePos Mobile Only - Not View all product/categorie

### ISSUE THREAD

**Issue by cenamikou** [Dolibarr/dolibarr#24265]
### Bug

Hello, 

When i use TakePos on mobile (or tablet). I see my product categories on the TakePos. However the first 3 are not clickable at the beginning. On the other hand, if I click on one of the following categories then the first 3 become selectable. In addition in all the categories I unfortunately do not see all my products. I only see 8 per category and cannot view the products afterwards. This for all categories

### Environment Version

17.0.0

### Environment OS

Android 13

### Environment Web server

CentOS 7.9 - Plesk Obsidian V18.0.49

### Environment PHP

8.0.28

### Environment Database

MariaDB 5.5.68

### Environment URL(s)

takepos/index.php?idmenu=54&mainmenu=takepos&leftmenu=

### Steps to reproduce the behavior

Open TakePos on mobile or tablet
Click 3 first categorie don't work
Click another else
The 3 first work
But i see only 8 product on all categorie

### Attached files

Cannot click to the 3 first category (for information, the 3 first category are children category inside) : 
![cannot click the 3 first category](https://user-images.githubusercontent.com/84474411/226144178-fdcd5784-b405-4e1d-a030-196d694b22e1.PNG)

After i click another category, for example i click to "04 - Confiseries" : 
![Click other category](https://user-images.githubusercontent.com/84474411/226144205-cc62e904-2050-48b2-9d3b-c0635475ff3d.PNG)

Now the 3 first category work : 
But in all category i view alors 8 product i cannot scroll more :

![not view all product](https://user-images.githubusercontent.com/84474411/226144275-0f02e044-d58d-4719-a35f-8f619161f63e.PNG)

**Comment by Jea-takepos** [comment]
Hello,
We have not been able to reproduce the error that you reported.
In our installation it works correctly.

**Comment by cenamikou** [comment]
Hello,

@Jea-takepos After more test the bug happens when they are children catégorie.
On the dolibarr forum french they are other have see the bug
https://www.dolibarr.fr/forum/t/bug-affichage-takepos-mobile-dolibarr-v17/43219/12

Thanks

**Comment by peyo0** [comment]
Hello, same probleme here on V17.0.3

**Comment by Arifpsubair** [comment]
Same problem here on Dolibarr v18.0.2 , v18.0.3, v18.0.4. Can anyone solve this issue. Issue facing only on mobile view. Only 6 Categories are loading and maximum 10 products per category. Other products we have to search and find out. When i check the code, it seems to load the item, but not displaying on the screen. Don't know how to fix this.

There are some other issues like, in android mobile with multiple screen resolutions, the number of items shows when scrolled are different. When the same is used in iphone with safari or google chrome, the items shown are again less. Also when we rotate the screen to landscape, Android shows the display as we see on desktop, all categories and items are able to see with arrow to scroll left and right. But this is not the case with iphone in landscape mode. 

Dolibarr is a very good application, but a lot of bugs need to be fixed. I have more issues and am testing multiple versions as well. But, those issues cannot be listed here.
