### ISSUE TITLE
Bug: Notifications Module 

### ISSUE THREAD

**Issue by tescsonaa** [Dolibarr/dolibarr#24273]
Hello, 

I'm using Dolibarr 16.0.3. If enable the Notifications on business event module and setup the emails, once approve any purchase order, the page will freeze. If disable the Notifications module, everything goes smoothly. This issue also happen when sending notification in enter payment.

**Comment by eldy** [comment]
Can provide step by step the action you do before being freeze (explain what is the last screen you have before you freeze)
Can you also test with 17.0 ?

**Comment by tescsonaa** [comment]
1. Enable the Notification Module

![Screenshot_1](https://user-images.githubusercontent.com/96901985/228728654-fd866817-0ba1-4368-bbc9-5e44b691fe61.jpg)

2. Add relative email address 

![Screenshot_2](https://user-images.githubusercontent.com/96901985/228728868-ad386553-8dfd-4ba5-9149-d44355dd516d.jpg)

3. Approve a Purchase Order 

![Screenshot_3](https://user-images.githubusercontent.com/96901985/228729019-ec9f430a-9f12-46c1-97b1-ec8c72a25753.jpg)

4. Once validate the oder, the page will freeze 

![Screenshot_4](https://user-images.githubusercontent.com/96901985/228729165-ee01ca9e-c6f6-4ee8-8fc6-15eb4902e252.jpg)

If remove the relative email in Notification Module, the Purchase Order will run as normal. 

![Screenshot_5](https://user-images.githubusercontent.com/96901985/228729568-4f5c88b5-12bf-4832-b2e0-7a0f2d4e7dfd.jpg)
