### ISSUE TITLE
Missing TAG on Proposal

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#24282]
### Feature Request

Missing TAG on Proposal

![image](https://user-images.githubusercontent.com/3288514/226363163-430de087-05df-4adf-8beb-a16c66c61037.png)

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/226606821-d6f85def-5a3f-4416-b622-742b27e4df45.png)

and here https://github.com/Dolibarr/dolibarr/pull/23927 i tried to depostopned one of them
