### ISSUE TITLE
Intervention - failed to update the date of item 

### ISSUE THREAD

**Issue by bravox-sg** [Dolibarr/dolibarr#24289]
### Bug

After creating Intervention with items, the date is not updated when Edit and update. 

![image](https://user-images.githubusercontent.com/94149928/226513747-92344fc1-afae-4358-8530-8d592e77fb58.png)

**Comment by bravox-sg** [comment]
Version: 17.0.0 
OS: Linux CentOS 
Database: MySQL 8

**Comment by aspangaro** [comment]
Fix in v17.0.2 on https://github.com/Dolibarr/dolibarr/commit/077c3312cea9f58396e9000f266608ac83c53fb7
