### ISSUE TITLE
Dolibarr V17.0.0 PHP8 fatal error dans htdocs/core/class/conf.class.php

### ISSUE THREAD

**Issue by Mx74** [Dolibarr/dolibarr#24293]
### Bug

Error 500 at launch:

Unsupported operand types: string * int in /var/www/html/xxxx/htdocs/core/class/conf.class.php

Error occurs at Lines 837, 870 871.

Added a (float) at the beginning and everything seems to work so far:

```
$this->adherent->subscription->warning_delay =(float) (isset($this->global->MAIN_DELAY_MEMBERS) ? $this->global->MAIN_DELAY_MEMBERS : 0) * 86400;

$this->contrat->services->inactifs->warning_delay = (float)(isset($this->global->MAIN_DELAY_NOT_ACTIVATED_SERVICES) ? 

$this->global->MAIN_DELAY_NOT_ACTIVATED_SERVICES : 0) * 86400;
                                $this->contrat->services->expires->warning_delay = (float)(isset($this->global->MAIN_DELAY_RUNNING_SERVICES) ? $this->global->MAIN_DELAY_RUNNING_SERVICES : 0) * 86400;
```

### Environment Version

17.0.0

### Environment OS

Ubuntu 22.04

### Environment Web server

Apache 2

### Environment PHP

PHP 8.0

### Environment Database

Mariadb 10.6

### Environment URL(s)

Login page

**Comment by Mx74** [comment]
Still valid with 17.0.1

**Comment by Jozmichne** [comment]
I encounter the same.. works fine on php 7.4 though

**Comment by frederic34** [comment]
which version of php, PHP8.0 or PHP8.1 or PHP8.2 ?

**Comment by Jozmichne** [comment]
> which version of php, PHP8.0 or PHP8.1 or PHP8.2 ?

i was trying it on php 8

**Comment by frederic34** [comment]
8.0. 8.1 and 8.2 are different, it is not ready for 8.2

**Comment by Jozmichne** [comment]
> 8.0. 8.1 and 8.2 are different, it is not ready for 8.2
I understand, I meant to say PHP 8.0
