### ISSUE TITLE
Opensurvey Date display error

### ISSUE THREAD

**Issue by GregChant** [Dolibarr/dolibarr#24311]
### Bug

The day is not correctly displayed in the summary table.
The bug is induced by an erroneous call to the function dol_print_date($cur, "%a %e"). The %e does not exist. I propose to replace the %e by %d in the files:
public/opensruvey/studs.php lines 427, 430 and opensurvey/result.php lines 760 and 763

### Environment Version

v17

### Environment OS

linux

### Environment Web server

Apache2 

### Environment PHP

php 8.1.14

### Environment Database

MariaDB 10.4.25

### Environment URL(s)

opensurvey/results.php?id= and public/opensurvey/studs.php?sondage=

### Expected and actual behavior

Display of the day

### Steps to reproduce the behavior

Create a survey type by date
add some dates (full day)
and finish the survey
click on the share link > the default is present in the table
In the admin tools tab
click on tools - survey - list
click on survey - results > the default is present in the table

**Comment by oussamanhairech** [comment]
The suggestion is already implemented and the date is displayed correctly.
