### ISSUE TITLE
Product Variants Not Loading if not Localhost

### ISSUE THREAD

**Issue by jumping69** [Dolibarr/dolibarr#24313]
### Bug

**Context**:
Dolibarr installation (16.0.4) on Windows server and configured with a dedicated IP address and a "dolibarr.mydomain.lan" DNS.
Use through my LAN with "dolibarr.mydomain.lan"

**Issue**:
Page: Products > Variants
When I click on "CREATE" after selecting a combination, the "localhost" URL is used instead of "dolibarr.mydomain.lan":
http://localhost/dolibarr/variants/combinations.php?id=nnn
Because localhost is not a valid URL for remote use, the page cannot be displayed.
If I replace the URL on the browser with "http://dolibarr.mydomain.lan/dolibarr/variants/combinations.php?id=nnn", the page is displayed and the combination is created.

I checked and adapted the Apache configuration files to replace localhost with dolibarr.mydomain.lan but without success for this creation of combinations.

I haven't encountered this problem with the other functions I use on Dolibarr.

### Environment Version

16.0.4

### Environment OS

Windows Server 2019

### Environment Web server

Apache/2.4.51 (Win64)

### Environment PHP

PHP/7.3.33

### Environment Database

MariaDB 5.5.5-10.6.5-MariaDB

### Environment URL(s)

http://localhost/dolibarr/variants/combinations.php?id=nnn

### Expected and actual behavior

Using configured domain instead of localhost

### Steps to reproduce the behavior

Use with domain other than localhost pour la page "http://localhost/dolibarr/variants/combinations.php?id=nnn"

**Comment by ksar-ksar** [comment]
Hello,

Have you checked the url you have in conf/conf.php ?

**Comment by jumping69** [comment]
Hello,
I checked APACHE configuration files but not PHP.
I didn't know that the conf.php file also had to be adapted.
Now it works correctly.
THANKS !
