### ISSUE TITLE
BUG - Trigger - When the supplier buy price change "SUPPLIER_PRODUCT_BUYPRICE_UPDATE" not launched

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#24319]
### Bug

The trigger doesn't take into account the action "SUPPLIER_PRODUCT_BUYPRICE_UPDATE" neither "SUPPLIER_PRODUCT_BUYPRICE_CREATE"

Explanation : When the supplier buy price change, the trigger is not activate. 

Sample code : 
`<?php

require_once DOL_DOCUMENT_ROOT.'/core/triggers/dolibarrtriggers.class.php';

/**
 *  Class of triggers for MyModule module
 */
class InterfaceEcommerceSyncTrigger extends DolibarrTriggers
{
	/**
	 * Constructor
	 *
	 * @param DoliDB $db Database handler
	 */
	public function __construct($db)
	{
		$this->db = $db;

		$this->name = preg_replace('/^Interface/i', '', get_class($this));
		$this->family = "DAXIT";
		$this->description = "xxxx";
		// 'development', 'experimental', 'dolibarr' or version
		$this->version = '0.1';
		$this->picto = 'info@daxit.be';
	}

	/**
	 * Trigger name
	 *
	 * @return string Name of trigger file
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Trigger description
	 *
	 * @return string Description of trigger file
	 */
	public function getDesc()
	{
		return $this->description;
	}

	public function runTrigger($action, $object, User $user, Translate $langs, Conf $conf)
	{
		
		
		// You can isolate code for each action in a separate method: this method should be named like the trigger in camelCase.
		// For example : COMPANY_CREATE => public function companyCreate($action, $object, User $user, Translate $langs, Conf $conf)
		$methodName = lcfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', strtolower($action)))));
		$callback = array($this, $methodName);
		if (is_callable($callback)) {
			dol_syslog(
				"Trigger '".$this->name."' for action '$action' launched by ".__FILE__.". id=".$object->id
			);

			return call_user_func($callback, $action, $object, $user, $langs, $conf);
		};

		switch ($action) {
			// Products
			case 'PRODUCT_CREATE':
			case 'PRODUCT_MODIFY':
			case 'PRODUCT_DELETE':
			case 'PRODUCT_PRICE_MODIFY':
			case 'PRODUCT_SET_MULTILANGS':
			case 'PRODUCT_DEL_MULTILANGS':
			case 'STOCK_MOVEMENT':
			case 'SUPPLIER_PRODUCT_BUYPRICE_UPDATE':
			case 'SUPPLIER_PRODUCT_BUYPRICE_CREATE':
				dol_syslog("DAXIT -- HOWHOWHOW should be deplayed ", LOG_DEBUG);
			break;
		}

		return 1;
	}
}
`

### Environment Version

16.0.4

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.3

### Environment Database

MySQL

### Environment URL(s)

http://xxx/product/card.php?id=xxxx

**Comment by tiaris** [comment]
Works for me.
trigger 'SUPPLIER_PRODUCT_BUYPRICE_UPDATE' is launched on Create and modify supplier price
