### ISSUE TITLE
Inconcistency - Size of string is not the same on the product ref than on the orderline ref

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#24323]
### Bug

When trying to create an order from a product having a big reference, the system raise an error. 

![error_ref_png](https://user-images.githubusercontent.com/26635105/226972361-8f6ccdee-749b-4b7e-8b46-269eb56b5364.jpg)

Proposed solution : 
ALTER TABLE llx_commande_fournisseurdet MODIFY COLUMN `ref` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL NULL;

varchar(50) >> varchar(250)

### Environment Version

16.0.3

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

xxxx/fourn/commande/card.php?id=123

### Steps to reproduce the behavior

Create a product with reference "Las_Pizarras_Vina_Alarba_Garnacha-2020-Rouge-75,0_cl"
Create a new order 
Add an order line with product "Las_Pizarras_Vina_Alarba_Garnacha-2020-Rouge-75,0_cl" 
-> error.

**Comment by ksar-ksar** [comment]
Hello,

This has been already corrected : https://github.com/Dolibarr/dolibarr/commit/8bd6f070aab2fd5efe01c4ce78fd274ee8002ac5

**Comment by daxitsolutions** [comment]
Perfect @ksar-ksar thanks !
