### ISSUE TITLE
Bug: Buy and sell prices

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#24320]
Hello
Buy price and sell price tabs are no longer editable on products

**Comment by alimentarius** [comment]
![Captura de ecrã 2023-03-22 113945](https://user-images.githubusercontent.com/19837231/226893303-c368172c-a46f-454a-a604-c51e661342c9.png)

**Comment by sonikf** [comment]
I can confirm this bug it was introduced in v 17.0.0. It has also affected the vat rate when creating a supplier invoice it now defaults to zero instead of the saved percentage of product or service. It is working fine in 17.0.0-beta

**Comment by sonikf** [comment]
@eldy it is related to commit #21873. When i set MAIN_USE_ADVANCED_PERMS to 0 in other setup, selling and buying price works again
