### ISSUE TITLE
Bug v17 when sending emails to @gmail.com

### ISSUE THREAD

**Issue by WilliamThx** [Dolibarr/dolibarr#24332]
### Bug

Dolibarr version 17
SPF and DKIM are set correctly on mail server

Bug: when emails are sent by dolibarr (order, invoice, test) to a person using @gmail.com address, the email does not reach destination.

When emails are sent with Wordpress with the same mail server, emails are correctly received by @gmaill.com

My Dolibar v16 set-up did not have this issue

### Environment Version

17

### Environment OS

CentOS

### Environment PHP

7.4

### Environment Database

mySQL

**Comment by WilliamThx** [comment]
Problem occurs when SMTP socket library is used
It did work well when Swift Mailer socket library is used

**Comment by ksar-ksar** [comment]
Hello,

Do you have any error message back from gmail ?
Or on the mail server ?

**Comment by WilliamThx** [comment]
Hello no nothing back from gmail.CheersWilliamLe 26 mars 2023 à 21:17, ksar ***@***.***> a écrit :﻿
Hello,
Do you have any error message back from gmail ?
Or on the mail server ?

**Comment by FlorentLeterme** [comment]
I am experiencing the same issue with Dolibarr version 17.0.1. It seems that only sending emails (gmail) from Dolibarr to Gmail addresses is not functioning properly. I receive a confirmation that the email has been sent successfully, but I do not see anything in my Gmail inbox at gmail.com.

**Comment by Elron72** [comment]
Hello, after having the same problem I found something else. This problem is with Microsoft email services. Also accounts not Gmail but using Microsoft 365 email services.
Thanks

**Comment by tranKILL** [comment]
Same thing here, Dolibarr 17.0.2.
Was working on .com, and now that the email are on the real url server it don't work (.be).
If someone got something..

Dolibarr (check server ok, says sended but nothing is send even in spam) :
Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: localhost) | SSL0.OVH.NET
Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: 25) | 465
Méthode d'authentification | Utiliser mot de passe
ID SMTP (si le serveur d'envoi nécessite une authentification) | ***@***.be
Mot de passe SMTP (si le serveur d'envoi nécessite une authentification) | *********
Utilisation du chiffrement TLS (SSL) | Oui
Utiliser le cryptage TTS (STARTTLS) | Non
Autoriser les certificats auto-signés | Non

OVH :
SPF "v=spf1 ip4:146.59.209.152 ~all"

**Comment by tranKILL** [comment]
> Same thing here, Dolibarr 17.0.2. Was working on .com, and now that the email are on the real url server it don't work (.be). If someone got something..
> 
> Dolibarr (check server ok, says sended but nothing is send even in spam) : Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: localhost) | SSL0.OVH.NET Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: 25) | 465 Méthode d'authentification | Utiliser mot de passe ID SMTP (si le serveur d'envoi nécessite une authentification) | _**@**_.be Mot de passe SMTP (si le serveur d'envoi nécessite une authentification) | ********* Utilisation du chiffrement TLS (SSL) | Oui Utiliser le cryptage TTS (STARTTLS) | Non Autoriser les certificats auto-signés | Non
> 
> OVH : SPF "v=spf1 ip4:146.59.209.152 ~all"

Seems to be corrected with Swift mailer, and DKIM :

Méthode d'envoi d'email | Swift Mailer socket library
-- | --
Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: localhost) | SSL0.OVH.NET
Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: 25) | 465
Méthode d'authentification | Utiliser mot de passe
ID SMTP (si le serveur d'envoi nécessite une authentification) | ***@***
Mot de passe SMTP (si le serveur d'envoi nécessite une authentification) | ***************
Utilisation du chiffrement TLS (SSL) | Oui
Utiliser le cryptage TTS (STARTTLS) | Non
Autoriser les certificats auto-signés | Non
Utiliser DKIM pour signer les emails | Oui
Nom de domaine pour la signature DKIM | Your.Domain
Nom du sélecteur DKIM | YourSelector
Clé privée pour générer la signature DKIM | -----BEGIN RSA PRIVATE KEY----- ND...r4HT -----END RSA PRIVATE KEY-----

Use one of these DKIM generator : https://easydmarc.com/tools/dkim-record-generator
