### ISSUE TITLE
No automatic end date of membership

### ISSUE THREAD

**Issue by Nikobalt** [Dolibarr/dolibarr#24367]
### Bug

The end date of membership is not calculated accordingly to the membership duration.

### Environment Version

16.0.5

### Environment OS

Linux 5.15.0-69 (Kubuntu)

### Environment Web server

Apache/2.4.52

### Environment PHP

8.1.2-1ubuntu2

### Environment Database

MariaDB 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1

### Expected and actual behavior

In the member module, I created several member types : one for each payment frequency (monthly, quarterly, etc.), and I filled the _duration_ field accordingly.
When I register a contribution, the _end date of membership_ is supposed to be calculated automatically when left empty. But instead of this, it registers the membership for one year, no matter the membership duration.

### Steps to reproduce the behavior

Happens every time.

### Attached files

![image](https://user-images.githubusercontent.com/77627672/228382601-e240ae59-e209-4c40-9816-ae4a0c2ab563.png)

![image](https://user-images.githubusercontent.com/77627672/228382844-4c505ffe-0171-4d1f-a014-1f4739aa341f.png)

![image](https://user-images.githubusercontent.com/77627672/228383053-1ede58de-5469-41c0-88ad-c01e1bc6f301.png)

**Comment by daraelmin** [comment]
I did not provide a default end date in the "end date" box, because it is too complicated to modify it on the fly when the start date is changed.
However, the default duration defined in the membership type is applied if no end date is entered.
However, a little help text should probably be added so that the user knows that if they leave the box empty, the default duration applies.
To be done in a future version.

**Comment by Nikobalt** [comment]
> However, the default duration defined in the membership type is applied if no end date is entered.

That's the point : whatever the default duration in the membership (1, 2, 3 or 6 months), it always applies one year when I leave blank.
BTW, in the meantime I upgraded to 18.0.2 and it's still the same.

**Comment by daraelmin** [comment]
The fix has been pushed. Issue should be corrected in 18.0.3
