### ISSUE TITLE
Other price with divisa in products

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#24377]
### Feature Request

The product can have other price of sell with other divisa

### Use case

El producto puede tener un precio local para las ventas generales sin embargo se presentan clientes que sólo manejan una divisa en particular, también podría usar para las exportaciones, etc.

### Suggested implementation

Database, table products add multicurrency_price, multicurrency_price_ttc, multicurrency_code, multicurrency_tx and the product/price.php, add this values

### Suggested steps

In the price of sell insert this values

**Comment by ksar-ksar** [comment]
Divisa = currency

**Comment by JonBendtsen** [comment]
Can we re-open this? I wish that products could have different prices in different currencies, not just based on the exchange rate

**Comment by ksar-ksar** [comment]
Hello @JonBendtsen,
Better to open a new one, I think, because the title of this one is not very "comprehensive".
