### ISSUE TITLE
Variable of substitution __ONLINE_SIGN_URL__ dont working

### ISSUE THREAD

**Issue by julbroa** [Dolibarr/dolibarr#24384]
### Bug

the variable __ONLINE_SIGN_URL__ don´t work, If I send an email with all the substitution variables, that variable is left without generating the expected link

### Environment Version

17.0.0

### Environment OS

Linux us-imm-web176.main-hosting.eu 4.18.0-372.16.1.lve.el8.x86_64 #1 SMP Thu Jul 14 07:23:57 EDT 2022 x86_64

### Environment Web server

LiteSpeed

### Environment PHP

8.0.28

### Environment Database

MySQL or MariaDB 10.5.16-MariaDB-cll-lve

### Environment URL(s)

htdocs/contrat/card.php?id=2&action=presend

### Expected and actual behavior

On Contract section when I generated an email to send to customer, the link to be replaced and to be able to be signed is generated and sent to the client.
Actual behavior: If I generate an email to be sent to the client with all the substitution variables, that link is not replaced with the link so that the contract can be signed. 

### Attached files

![image](https://user-images.githubusercontent.com/105558823/228635325-102c91ad-4a86-43c4-b236-b40db631cae4.png)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/24385

**Comment by julbroa** [comment]
Working for me, thank you very much
