### ISSUE TITLE
contact address on tickets

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#24394]
When creating a ticket, there is only the option to send it to 1 customer's email address.
How to send to more than 1?

**Comment by lmag** [comment]
Hi @alimentarius 
Il think that is not the good place to ask help, you may use the forum for this kind of questions

Add Contact
![image](https://user-images.githubusercontent.com/3288514/229319579-3564f74d-25e8-4781-83a4-29c7f6ccc701.png)
So you can send-it to this contacts
![image](https://user-images.githubusercontent.com/3288514/229319598-8148fdee-2655-4936-adab-fe5cde42ad44.png)
