### ISSUE TITLE
ODT tag for document author

### ISSUE THREAD

**Issue by mpractic** [Dolibarr/dolibarr#24392]
### Feature Request

I'd like to have an ODT tag for the document author ({object_author} or somethink similar). In my case I need it for proposals/invoices, but I bet it can be helpfull to others in other situations. 

### Suggested implementation

Add {object_author} to the list of available tags.

**Comment by mpractic** [comment]
I just noticed I already opened a feature request for this 4 months ago. Sorry, this one can be closed.
https://github.com/Dolibarr/dolibarr/issues/23211

**Comment by mpractic** [comment]
Thank you @ksar-ksar . You've marked it as "completed". Is this right? If it's done, maybe you should mark https://github.com/Dolibarr/dolibarr/issues/23211 also as completed.

Thanks a lot.

**Comment by ksar-ksar** [comment]
@mpractic my bad, I was thinking that you request to close this one.
Sorry for that

**Comment by mpractic** [comment]
My fault, maybe I explained it wrong.
This issue is duplicated; I opened it without remembering that I had already created another issue for the same matter 4 months ago. I don't know if the problem is better explained here or in the other issue, but one of the two can be closed (as a duplicate, not as completed).
Thank you very much for your effort! It is really much appreciated.
