### ISSUE TITLE
DEPOSIT_PERCENT est affiché au lieu de la valeur réelle dans le document 

### ISSUE THREAD

**Issue by Magissia** [Dolibarr/dolibarr#24405]
Lors de la creation d'une proposition commerciale sur un tiers ayant la condition de règlement « DEP30PCTDEL », sur la proposition commerciale apparaît DEPOSIT_PERCENT% acompte, reste à la livraison au lieu de la valeur que devait avoir cette variable.

Plus de détails ici
https://www.dolibarr.fr/forum/t/demande-davis-sur-fonctionnalite-acompte-automatique/37824/43

Test en 16.0.3

**Comment by ksar-ksar** [comment]
Hello,

All the bugs reports needs to be done in English.

May be @FHenry has done something on that ?

**Comment by didi31** [comment]
I added this Line, as a workaround, into the pdf model before printing:
$lib_condition_paiement = str_replace('__DEPOSIT_PERCENT__', $object->deposit_percent, $lib_condition_paiement);
