### ISSUE TITLE
remote mysql server with ssl transport ?

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#24404]
### Feature Request

Hello all,
i'm looking for a way to configure dolibarr with a remote mysql/mariadb server using ssl layer

> php mysqli will do it with https://www.php.net/manual/fr/mysqli.ssl-set.php

but i can't find any trace of ssl_set into dolibarr php code

may i make a PR for that or that's not important ?

**Comment by olad32** [comment]
I think this feature would definitely improve Dolibar security
