### ISSUE TITLE
Question about socid

### ISSUE THREAD

**Issue by robmr88** [Dolibarr/dolibarr#24419]
### Bug

Hello, I would like to use the create orders api to insert an order in Dolibarr that was created on an external app.
I believe socid to be the user id but Dolibarr creates the user id as CUxxxx-xxxxx, so it's a String but the socid required in the orders api is expected to be an int.
So I was wondering what is socid

**Comment by V-Py** [comment]
Hi, the socid is not the user id, but the unique id of the third party (entity/company) who is the customer for your order. 
For example, if you have a company created in Dolibarr named "MyCompany", it also has a unique id (integer) to identify it, in that case, let's say 27. So when you will create your order, the socid expected will be 27.

**Comment by robmr88** [comment]
Thank you, I figured that out at the end. Now the problem that I am having is that the products for the order that I create appear at 0 euros. How can I fix this?

**Comment by V-Py** [comment]
When you create your commande lines, you have to set the price of the product for each line, even if you have set up a general price in your catalog.

**Comment by robmr88** [comment]
Thank you!
so the lines should be like this:
fk_product
quantity
price?
What is the exact name I must give to the price field?
And why isn't this information anywhere on the documentation?
In the orders api it only says to add fk_product and quantity for the lines

**Comment by V-Py** [comment]
You mean this comment above the function ? 
`* Exemple: { "socid": 2, "date": 1595196000, "type": 0, "lines": [{ "fk_product": 2, "qty": 1 }] }`

You're right it lacks the price precision. But sometimes I think the documentation also assumes you know how Dolibarr works globally, that's why it is not always exhaustive ..! If I have time I'll send a PR to update the documentation to see what they think about it. 

Anyway, if you look into the **commande.class.php** file, you'll find the function **create()** to create order. 
In this function you'll also find a call to the function **addline()** to add line to the order. 
```
$result = $this->addline(
		$line->desc,
		$line->subprice,
		$line->qty,
		$vatrate,
		$line->localtax1_tx,
		$line->localtax2_tx,
		$line->fk_product,
		$line->remise_percent,
		$line->info_bits,
		$line->fk_remise_except,
		'HT',
		0,
		$line->date_start,
		$line->date_end,
		$line->product_type,
		$line->rang,
		$line->special_code,
		$fk_parent_line,
		$line->fk_fournprice,
		$line->pa_ht,
		$line->label,
		$line->array_options,
		$line->fk_unit,
	                $origintype,
	                $originid
	)
```

In this, you can see all the parameters you can choose for your order lines.
In your case, you might want to specify the **subprice** and the **tva_tx** params.

**Comment by robmr88** [comment]
@V-Py Thank you

**Comment by Jahnzeb** [comment]
@robmr88 hy... i am Android Engineer.. i am working on Serial Port printer.. i read your comments on @Danstu library that you have passed the Serial connection to its library and then it was printing by using their commands.. 
i have tried this but it was not printing at CtiaqH10 printer.. can you please help men in this? 
Note : 
Sorry this Thread is not related to this, but that thread was closed so i could not approached you.. kindly help me in this..

**Comment by robmr88** [comment]
@Jahnzeb hey, really busy right now. I'll try and send details of the integration by end of the day

**Comment by Jahnzeb** [comment]
@robmr88 okey thank you so much.. i you have no issue. can you please send me your email?

**Comment by Jahnzeb** [comment]
@robmr88 hey.. i was waiting for you.. my client going crazy on me.. kindly guide me on this.

**Comment by robmr88** [comment]
Send me your email, I'll send you the classes

**Comment by robmr88** [comment]
@Jahnzeb

**Comment by robmr88** [comment]
@Jahnzeb 

1- find the google serial port api library, add it as a class in your project. Add a folder at the same level with your main package, like this:

<img width="303" alt="Screenshot at Sep 21 19-16-12" src="https://github.com/Dolibarr/dolibarr/assets/60899275/62fd001a-3b66-4be8-9f8e-28ca5aece837">

2-  make sure the SerialPort class looks like this:

`public class SerialPort {

	private static final String TAG = "SerialPort";

	/*
	 * Do not remove or rename the field mFd: it is used by native method close();
	 */
	private FileDescriptor mFd;
	private FileInputStream mFileInputStream;
	private FileOutputStream mFileOutputStream;

	public SerialPort(File device, int baudrate, int flags, boolean flowCon)
			throws SecurityException, IOException {

		/* Check access permission */
		if (!device.canRead() || !device.canWrite()) {
			try {
				/* Missing read/write permission, trying to chmod the file */
				Process su;
				su = Runtime.getRuntime().exec("/system/bin/su");
				String cmd = "chmod 666 " + device.getAbsolutePath() + "\n"
						+ "exit\n";
				su.getOutputStream().write(cmd.getBytes());
				if ((su.waitFor() != 0) || !device.canRead()
						|| !device.canWrite()) {
					throw new SecurityException();
				}
			} catch (Exception e) {
				e.printStackTrace();
				throw new SecurityException();
			}
		}

		mFd = open(device.getAbsolutePath(), baudrate, flags, flowCon);
		if (mFd == null) {
			Log.e(TAG, "native open returns null");
			throw new IOException();
		}
		mFileInputStream = new FileInputStream(mFd);
		mFileOutputStream = new FileOutputStream(mFd);
	}

	// Getters and setters
	public InputStream getInputStream() {
		return mFileInputStream;
	}

	public OutputStream getOutputStream() {
		return mFileOutputStream;
	}

	// JNI
	private native static FileDescriptor open(String path, int baudrate,
                                              int flags, boolean flowCon);
	public native void close();
	

}`

it's the class from the serial port library, just make shure everything is in place, I've made this a long time ago and I can't remember if I edited it. It was so long ago I might not make it work again 😅

3 - make a method that creates a Serial Port when you need to print:

`    public static SerialPort getPrintSerialPort() throws SecurityException, IOException, InvalidParameterException {
        if (mSerialPort == null) {
            /* Open the serial port */
            mSerialPort = new SerialPort(new File("/dev/ttyS1"), 115200, 0, true);
        }
        return mSerialPort;
    }`

4- use it with the dant su library:

`                SerialConnection serialConnection = new SerialConnection();

                EscPosPrinter printer = new EscPosPrinter(serialConnection, 203, printerWidthMM, charPerLine);
                printer.printFormattedTextAndCut(txtvalue);`

Your device should print now.

**Comment by danstu** [comment]
Why the fuck am I on this email thread? Remove me.

**Comment by Jahnzeb** [comment]
@robmr88 here is my email mehmoodjahnzeb@gmail.com

**Comment by Jahnzeb** [comment]
> Send me your email, I'll send you the classes

here is my email mehmoodjahnzeb@gmail.com
