### ISSUE TITLE
how can I use the substitution variable  __SECUREKEYPAYMENT_CONTRACTLINE__ ?

### ISSUE THREAD

**Issue by julbroa** [Dolibarr/dolibarr#24412]
that is, in the email template, how can I refer to the line or lines of the contract so that the variable automatically generates the payment link? 
Or what else has to be done so that the substitution variable generates the link since when I put it in the template of email and try to send the email, no substitution is made

**Comment by ksar-ksar** [comment]
Hello,

As far as I know, there is no payment by line possible.

**Comment by julbroa** [comment]
![image](https://user-images.githubusercontent.com/105558823/229907306-8cfcf355-28b8-4859-b69b-5db80efac7e3.png)
The PayPal module generates links that allow you to make the payment online and if you add the ID of the contract line, it generates the link to make the payment for it. Dolibarr even has a substitution variable which is why I ask how to use it when sending emails, how do I have to specify the line to which I want the payment link to be generated?

**Comment by julbroa** [comment]
still present in new versions

**Comment by julbroa** [comment]
still present in new versions
