### ISSUE TITLE
In the wiki the URL reference for Transifex is broke

### ISSUE THREAD

**Issue by apradoc** [Dolibarr/dolibarr#24418]
### Bug

On the dolibarr wiki the address of the Transifex repository appears as http://transifex.com/projects/p/dolibarr/ and it is out of date. In the case of the software, the new URI would be https://explore.transifex.com/dolibarr-association/dolibarr/. 

I took advantage of reporting this detail since there is a failure in the export of users that I will publish after exploring the location files. Thank you

### Environment Version

16.0.3, 17.0.0

**Comment by lmag** [comment]
Done
https://wiki.dolibarr.org/index.php?title=Dolibarr_Project#Developer_grade_Z-6PO_.28Translators_on_transifex.com.29
