### ISSUE TITLE
Focus lost after clicking select2 field

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#24429]
### Bug

Focus lost after clicking select2 field

see screenshot

https://user-images.githubusercontent.com/25256186/229614677-72308a8b-1aa2-4d98-b9f2-8a1a677fb45c.mp4

### Environment Version

16.0.x

### Environment OS

na

### Environment Web server

na

### Environment PHP

na

### Environment Database

na

### Environment URL(s)

every list.php

### Expected and actual behavior

Focus should stay at input field

### Steps to reproduce the behavior

1. Open a list.php (eg ticket/list.php)
2. Click into a select2 field (eg ticket status)
3. Click into a normal input field (eg thirdparty)

see screenshot in bug description

**Comment by eldy** [comment]
After upgrade to jquery 3.6.4, problem seems to have disappear on develop branch.

Errata:  Ns. When you click on a combo the focus still does not appear so i finally applied your patch manually...
