### ISSUE TITLE
Can only close by year

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#24450]
### Bug

```php
$validatemonth = GETPOST('validatemonth', 'int');
$validateyear = GETPOST('validateyear', 'int');
```

The accountancy closure page has these 2 variables but only lets you close by year.

I think it'd be good to be able to close monthly.

"Ok, I know 100% that January is OK and won't need to be touched again, close it."

### Environment Version

16.0.3

**Comment by aspangaro** [comment]
Mensual closure is on the way... See you in v19
