### ISSUE TITLE
Problem displaying the amount including tax in the customer order

### ISSUE THREAD

**Issue by ammounammouni** [Dolibarr/dolibarr#24453]
### Bug

Good evening, about dolibarr v17
problem displaying the amount including tax in the customer order when editing the order.
as described in the photos
![image](https://user-images.githubusercontent.com/85039431/230387243-2ee6a20b-9071-4210-9bd0-c315bfafb02f.png)

for the supplier order and the customer and supplier invoices, we do not find this problem.
THANKS

### Environment Version

17

### Environment OS

linux

### Environment PHP

8

**Comment by ReproductriceDeBugs** [comment]
For the v18 :
That's very strange, it did it several times for the first line, but not for the next lines. (image 1) What's more, when I created other commands it didn't happen... 
Also, in the order the amount before tax is correct (image 1). However, when you create the invoice, the tax-free amount changes (image 2).

<img width="943" alt="Capture d'écran_20230610_161955 - Copie" src="https://github.com/Dolibarr/dolibarr/assets/135996360/fb235b46-0902-4275-ad5a-163a696acc7f">

<img width="943" alt="Capture d'écran_20230610_162141" src="https://github.com/Dolibarr/dolibarr/assets/135996360/f2a017ca-6249-41c2-be41-1a609f37bbd8">

**Comment by ammounammouni** [comment]
same problem for version 19
