### ISSUE TITLE
missing bank account on proposal, and order

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#24451]
### Feature Request

Missing bank account on proposal, and order

Customer : 
![image](https://user-images.githubusercontent.com/3288514/230369903-54b048bd-fed2-4864-b25d-06fac3208a6d.png)
Proposal : 

![image](https://user-images.githubusercontent.com/3288514/230368566-9a3d3ad7-c5e4-428a-a00e-d11e23afc71e.png)

Order : 
![image](https://user-images.githubusercontent.com/3288514/230367267-82122cd1-8ef8-4071-a186-9ad91c6ce9c5.png)

Blling : 

![image](https://user-images.githubusercontent.com/3288514/230367777-73497f99-4630-47d2-886d-7cc5d5028855.png)

**Comment by frederic34** [comment]
@lmag are you looking for that :

![image](https://user-images.githubusercontent.com/3624836/230609380-7ed18d7f-0c01-4329-b657-d2e011397f77.png)
