### ISSUE TITLE
Several issues with loan feature.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#24457]
### Bug

I experienced this in 16.0.1 .

- [ ] When setting the insurance amount, I thought this was monthly, but it was the total amount.  Then I wanted to updated it to something like "1365,20" and then I got an SQL error complaining about the number of columns.  I had to write "1365.20".  I now realize this might be even a potential risk for SQL injection.
- [ ] I was not sure about the initial date, so I set it to the date that the money was lent, not the date of first installment.  I then changed that (probably after validating the table), but the first installment was still at the wrong date.
- [ ] I noticed that after validating a number of past installments.  So I decided to Delete the loan.  The loan was deleted, but not the payments that were registered.  The payments could not be deleted using the UI.  I updated the database directly.
- [ ] After adding the new loan, the installments table was showing the expected amounts times 2.  I delete the old installments from llx_loan_schedule directly.
- [ ] When trying to equalize the payment amounts in the table, I also ran into "Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' amount_interest=, fk_typepayment=3, num_payment=null, note_private=null, not...' at line 1"
- [ ] Double submission of a payment was also possible (my server was too slow at some point, I validated twice and had to delete a payment).
- [ ] When deleting individual loan payments to correct them, they remain in th ellx_bank table.
- [ ] The accountancy report (compta/resultat/index.php?leftmenu=report&mainmenu=accountancy) does not take the interests and insurance paid into account.

### Environment Version

16.0.1

**Comment by AurelienBISOTTI** [comment]
Hello,
For the sake of readability and good pull request practice, can you make an issue per bug?
Thank you

**Comment by mdeweerd** [comment]
Just to make sure: you want me to create 8 issues out of this?

I can understand that some items need clarification.

Creating 8 issues is a matter of point of view - my argument is that they are all related to the loan feature and be the subject of a single PR.

EDIT: Created 8 new issues from this one.

**Comment by AurelienBISOTTI** [comment]
Great !
Thanks.
