### ISSUE TITLE
Improve public ticket interface

### ISSUE THREAD

**Issue by BenjaminFlr** [Dolibarr/dolibarr#24463]
### Feature Request

Automatically hide non allowed fields and corresponding columns.

### Use case

When we make an extrafield unavailable for visitors from tickets configuration, I would like to see the corresponding column disappear  from the ticket list.

### Suggested implementation

In public/ticket/list.php, add a filter on the rights before adding a field in the list of the ones which are available.
@eldy : I really would like to work on it, but first of all, what do you think?

**Comment by hregis** [comment]
@altairis-benjamin and if you try to hide this extrafields with check if you are in public ticket context ?

**Comment by BenjaminFlr** [comment]
@hregis My changes would only be in the public context. But as you can define the visibility of each extrafield, I thought that I could just add a check and, if the user can't see the information, we also hide the entire column and remove it from the ones which can be selected.
In fact, for now, the column is displayed but remains empty, which could be improved for a professional use.

**Comment by eldy** [comment]
You should be able to completely hide an extrafields on public pages by setting property visibility to
`preg_match('/public/', $_SERVER['PHP_SELF'])?0:1`
instead of 
`1`

**Comment by BenjaminFlr** [comment]
It seems that it's not working properly.
We use another domain for the public ticket interface, but event with a $_SERVER['SERVER_NAME'] or anything containing the domain, it still set the value to 1. I'll take a look at the code :)

**Comment by hregis** [comment]
@eldy @altairis-benjamin fix here https://github.com/Dolibarr/dolibarr/pull/24589

**Comment by BenjaminFlr** [comment]
https://github.com/Dolibarr/dolibarr/pull/24589

**Comment by eldy** [comment]
It seems pr #24589has fixed the trouble. Can we close this ticket ?

**Comment by BenjaminFlr** [comment]
You're right, it has been fixed. I close the issue.
