### ISSUE TITLE
Internal Tranfer/Payment with different currency

### ISSUE THREAD

**Issue by solairion2023** [Dolibarr/dolibarr#24480]
### Bug

Since update to 17.0.1 (16.0.4 before) we can't create internal transfer with 2 currency, the field for the amount after change currency does not appear.

Error : Field 'AmountTo' is required

### Environment Version

17.0.1

### Environment OS

Linux

### Environment PHP

7.4.33

### Environment Database

Mysql 5.5.5

### Steps to reproduce the behavior

Go to bank, Internal Transfer, set account from ($,€...), set account to with an other currency, and set description and amount.

### Attached files

![image](https://user-images.githubusercontent.com/130468087/231165920-feb57b98-03b6-4d33-9fd8-080a946488e2.png)

**Comment by solairion2023** [comment]
Solution found :
- File compta/bank/transfer.php
- Line 275 set : `print '<td class="multicurrency">' . $langs->trans("AmountToOthercurrency") . '</td>';`
- Line 298 `set : print '<td class="multicurrency"><input name="amountto" class="flat" type="text" size="6" value="' . dol_escape_htmltag($amountto) . '"></td>';`

After all is ok

**Comment by Delthair** [comment]
Please check / upodate with Dolibarr V17.0.2 the bug has been corrected

**Comment by emuchogu** [comment]
In version 19, enable the MULTICURRENCY module to resolve the error.
