### ISSUE TITLE
active import button for third parties

### ISSUE THREAD

**Issue by Libaud** [Dolibarr/dolibarr#24487]
### Bug

The import button remains active when importing from third parties. This, when the volume is large, poses a relative comprehension problem for the user.

### Environment Version

17.0.0

### Environment OS

Linux Debian

### Environment Web server

Apache2

### Environment PHP

PHP 7.x

### Environment Database

Maria DB

### Expected and actual behavior

Lors d'un import massif de tiers, le bouton d'importation pour la phase de simulation et où d'importation reste actif. Il n'y a pas d'information pour l'utilisateur affichant que l'importation est en cours ou terminée.

**Comment by yledoare** [comment]
Hello,
Bug or feature request ?
