### ISSUE TITLE
Unknown column 'fk_prospectcontactlevel' in 'field list'

### ISSUE THREAD

**Issue by herbs99** [Dolibarr/dolibarr#24496]
### Bug

When trying to create a new contact I get a "Unknown column 'fk_prospectcontactlevel' in 'field list'" error. 

Would be happy if this could be solved, kind regards, Herbert

### Environment Version

17.0.1.

### Environment URL(s)

areopa.brandscore.at

**Comment by ksar-ksar** [comment]
Hello,

I can't reproduce the error.

Can we have the full error code ?

**Comment by herbs99** [comment]
Where can I find this?

Thank you for looking into it


brandscore.at

Herbert Kling

Hauptstraße 39/1/1

3400 Weidling

Tel: +43 650 319 18 39

Mail: ***@***.******@***.***>

www.brandscore.at<http://www.brandscore.at/>

Linkedin<https://www.linkedin.com/in/herbertkling/>

________________________________
Von: ksar ***@***.***>
Gesendet: Freitag, 14. April 2023 09:19
An: Dolibarr/dolibarr ***@***.***>
Cc: Herbert Kling ***@***.***>; Author ***@***.***>
Betreff: Re: [Dolibarr/dolibarr] Unknown column 'fk_prospectcontactlevel' in 'field list' (Issue #24496)


Hello,

I can't reproduce the error.

Can we have the full error code ?

**Comment by herbs99** [comment]
Here you are with the error code:

2023-04-26 08:57:33 ERR     213.142.96.17    Contact::create Unknown column 'fk_prospectcontactlevel' in 'field list'
error
2023-04-26 08:57:33 ERR     213.142.96.17      DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'fk_prospectcontactlevel' in 'field list'

Database:
Version | 5.7.41-log

PHP 7.4.33

Hope this helps. Besides this issue, everything is working perfetly. 

CU, Herbert

**Comment by doriansimeha** [comment]
Hi, I'm just starting to use Dolibarr and I run into the same bug.

I still can access the /contact/card.php page to try to create new contact, but can't go to /contact/list.php.

I get (sorry for the french): 

Dolibarr a détecté une erreur technique.
Ces informations peuvent être utiles à des fins de diagnostic (vous pouvez définir l'option $dolibarr_main_prod sur '1' pour masquer les informations sensibles):
**Date:** 20230427121345
**Dolibarr:** 17.0.1 - https://www.dolibarr.org
**Niveau de fonctionnalités:** 0
**PHP:** 7.4.33
**Server:** Apache
**OS:** Linux webm136.cluster011.gra.hosting.ovh.net 5.15.74-ovh-vps-grsec-zfs-classid #1 SMP Wed Oct 26 09:50:47 UTC 2022 x86_64
**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

**Url sollicitée:** /contact/list.php?leftmenu=contacts
**Referer:** https://dolibarr.projeta.fr/contact/card.php?leftmenu=contacts&action=create
**Gestionnaire de menu:** eldy_menu.php

**Modules/Applications:** user, export, import, fckeditor, accounting, facture, societe, banque, tax, fournisseur, product, service, ecm, blockedlog
**Type gestionnaire de base de données:** mysqli
**Requête dernier accès en base en erreur:** SELECT s.rowid as socid, s.nom as name, s.name_alias as alias, p.rowid, p.lastname as lastname, p.statut, p.firstname, p.address, p.zip, p.town, p.poste, p.email, p.socialnetworks, p.photo, p.phone as phone_pro, p.phone_mobile, p.phone_perso, p.fax, p.fk_pays, p.priv, p.datec as date_creation, p.tms as date_update, p.import_key, st.libelle as stcomm, st.picto as stcomm_picto, p.fk_stcommcontact as stcomm_id, p.fk_prospectcontactlevel, co.label as country, co.code as country_code FROM llx_socpeople as p LEFT JOIN llx_c_country as co ON co.rowid = p.fk_pays LEFT JOIN llx_societe as s ON s.rowid = p.fk_soc LEFT JOIN llx_c_stcommcontact as st ON st.id = p.fk_stcommcontact WHERE p.entity IN (1) AND (p.priv='0' OR (p.priv='1' AND p.fk_user_creat=1)) AND p.statut = 1 ORDER BY p.lastname ASC LIMIT 21
**Code retour dernier accès en base en erreur:** DB_ERROR_NOSUCHFIELD
**Information sur le dernier accès en base en erreur:** Unknown column 'p.fk_prospectcontactlevel' in 'field list'

**Comment by doriansimeha** [comment]
Hi, I'm just starting to use Dolibarr and I run into the same bug.

I still can access the /contact/card.php page to try to create new contact, but can't go to /contact/list.php.

I get (sorry for the french):

Dolibarr a détecté une erreur technique.
Ces informations peuvent être utiles à des fins de diagnostic (vous pouvez définir l'option $dolibarr_main_prod sur '1' pour masquer les informations sensibles):
**Date:** 20230427121345
**Dolibarr:** 17.0.1 - https://www.dolibarr.org/
**Niveau de fonctionnalités:** 0
**PHP:** 7.4.33
**Server:** Apache
**OS:** Linux webm136.cluster011.gra.hosting.ovh.net 5.15.74-ovh-vps-grsec-zfs-classid 
**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

**Url sollicitée:** /contact/list.php?leftmenu=contacts
**Referer:** https://dolibarr.*******.fr/contact/card.php?leftmenu=contacts&action=create
**Gestionnaire de menu:** eldy_menu.php

**Modules/Applications:** user, export, import, fckeditor, accounting, facture, societe, banque, tax, fournisseur, product, service, ecm, blockedlog
**Type gestionnaire de base de données:** mysqli
**Requête dernier accès en base en erreur:** SELECT s.rowid as socid, s.nom as name, s.name_alias as alias, p.rowid, p.lastname as lastname, p.statut, p.firstname, p.address, p.zip, p.town, p.poste, p.email, p.socialnetworks, p.photo, p.phone as phone_pro, p.phone_mobile, p.phone_perso, p.fax, p.fk_pays, p.priv, p.datec as date_creation, p.tms as date_update, p.import_key, st.libelle as stcomm, st.picto as stcomm_picto, p.fk_stcommcontact as stcomm_id, p.fk_prospectcontactlevel, co.label as country, co.code as country_code FROM llx_socpeople as p LEFT JOIN llx_c_country as co ON co.rowid = p.fk_pays LEFT JOIN llx_societe as s ON s.rowid = p.fk_soc LEFT JOIN llx_c_stcommcontact as st ON st.id = p.fk_stcommcontact WHERE p.entity IN (1) AND (p.priv='0' OR (p.priv='1' AND p.fk_user_creat=1)) AND p.statut = 1 ORDER BY p.lastname ASC LIMIT 21
**Code retour dernier accès en base en erreur:** DB_ERROR_NOSUCHFIELD
**Information sur le dernier accès en base en erreur:** Unknown column 'p.fk_prospectcontactlevel' in 'field list'

**Comment by herbs99** [comment]
Solved it, the column was missing in the database.

**Comment by doriansimeha** [comment]
Can you help with where to put it ?

**Comment by herbs99** [comment]
I added it in table llx_socpeople.

Dont know why it was skipped during installation...


brandscore.at

Herbert Kling

Hauptstraße 39/1/1

3400 Weidling

Tel: +43 650 319 18 39

Mail: ***@***.******@***.***>

www.brandscore.at<http://www.brandscore.at/>

Linkedin<https://www.linkedin.com/in/herbertkling/>

________________________________
Von: doriansimeha ***@***.***>
Gesendet: Samstag, 29. April 2023 10:16
An: Dolibarr/dolibarr ***@***.***>
Cc: Herbert Kling ***@***.***>; State change ***@***.***>
Betreff: Re: [Dolibarr/dolibarr] Unknown column 'fk_prospectcontactlevel' in 'field list' (Issue #24496)


Can you help with where to put it ?

**Comment by MarcRaij** [comment]
@herbs99 

Hi,

I have the same error. 
I looked in the database and the column is missing.
On row 26 I do have a column named  fk_prospectlevel.
Do I change this to fk_prospectcontactlevel or do I have to add a new column? 
And if so is there a specific place I have to put the column or just add it to the end?

And can you inform me also what all the values are for this column (fk_prospectcontactlevel)

Thanks for your help!

**Comment by herbs99** [comment]
hi! just add it, thats it.

good luck

brandscore.at - mobile
________________________________
