### ISSUE TITLE
Possible bug in Order alerts/warnings 17.0.1

### ISSUE THREAD

**Issue by RaVaHgNu** [Dolibarr/dolibarr#24519]
### Bug

Good morning,
I have exactly the same problem after upgrading from 16.0.4 to 17.0.1.

https://www.dolibarr.org/forum/t/possible-bug-in-order-alerts-warnings-17-0-1/23594

(After upgrade from 16.0.4 to 17.0.1 I have noticed the following problem: the dashboard shows the real number of overdue orders, but in the list of validated orders all warnings are wrongly shown (see attached images):

Dashboard: [Dropbox - Dashboard.png - Simplify your life 6](https://www.dropbox.com/s/d0ugjljfwfkxf9r/Dashboard.png?dl=0)
Orders list: [Dropbox - Orders.png - Simplify your life 5](https://www.dropbox.com/s/vj1i5d4a7l52fwn/Orders.png?dl=0)

In addition: the language preferences do not work, so I cannot post screenshots in English :slight_smile: )

MERCI

### Environment Version

17.0.1

### Environment OS

linux

### Environment Web server

apache

### Environment PHP

php 7

### Environment Database

mariadb

### Environment URL(s)

https

![alerte commande 7](https://user-images.githubusercontent.com/92171284/232438567-37c4193c-0f40-4c5c-9182-2a0895dad87e.jpg)
![alertes en liste de commande](https://user-images.githubusercontent.com/92171284/232438582-f66cc28a-dc1b-44f3-9b9b-2841bb9a93c1.jpg)

**Comment by ReproductriceDeBugs** [comment]
This problem is not there in the v18

<img width="255" alt="Capture d'écran_20230610_105651" src="https://github.com/Dolibarr/dolibarr/assets/135996360/44067864-de3e-4e43-8415-799969040576">

<img width="191" alt="Capture d'écran_20230610_105731" src="https://github.com/Dolibarr/dolibarr/assets/135996360/2f10ad49-4a0e-4da3-a258-3c1e7d9f9252">
