### ISSUE TITLE
Fatal error: Uncaught Error: Class "CommonObjectLine" not found in "htdocs\bom\class\bom.class.php:1609"

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#24521]
### Bug

I got a copy with git:  git clone https://github.com/Dolibarr/dolibarr.git
After a fresh install, step 5, try to login, but shows me this error:

Fatal error: Uncaught Error: Class "CommonObjectLine" not found in C:\laragon\www\dolibarr\htdocs\bom\class\bom.class.php:1609 Stack trace: #0 C:\laragon\www\dolibarr\htdocs\core\lib\functions.lib.php(1094): include_once() #1 C:\laragon\www\dolibarr\htdocs\core\commonfieldsinexport.inc.php(12): dol_include_once('/bom/class/bom....') #2 C:\laragon\www\dolibarr\htdocs\core\modules\modBom.class.php(281): include('C:\\laragon\\www\\...') #3 C:\laragon\www\dolibarr\htdocs\install\step5.php(329): modBom->__construct(Object(DoliDBMysqli)) #4 {main} thrown in C:\laragon\www\dolibarr\htdocs\bom\class\bom.class.php on line 1609

I saw this script php file and I found that there is missing this line: (before "class BOMLine exteneds CommonObjectLine")
"require_once DOL_DOCUMENT_ROOT.'/core/class/commonobjectline.class.php';"

I put this instruction and all works fine.
Regards
JPFarber

### Environment Version

18.0.0-alpha

### Environment OS

Windows 10

### Environment PHP

8.1.8

### Environment Database

MariaDB 10.5.16 64bits

### Environment URL(s)

dolibar.test (localhost)

**Comment by ksar-ksar** [comment]
Hello,

Alpha versions are for developpers only, don't need to post bug reports.
