### ISSUE TITLE
Enterred Text not visible on Invoices / Order Confirmations

### ISSUE THREAD

**Issue by Basti-Fantasti** [Dolibarr/dolibarr#24528]
### Bug

When Adding products to an Invoice there is an issue when manually adding some text to the description.
Sometimes (yes only sometimes) the enterred text gets formatted like this:

```html
<span style="font-size:calc(var(--scale-factor)*8.00px)">My Text</span><br />
<span style="font-size:calc(var(--scale-factor)*8.00px)">- Some Row Data</span><br />
<span style="font-size:calc(var(--scale-factor)*8.00px)">Some more text</span><br />
```

The data enterred is:

My Text
- Some Row Data
Some more text

This style makes the text invisible.
When the span instructions are manually remove in the **SourceCode** view, the text becomes visible.

### Environment Version

17.0.0

### Environment OS

Ubuntu

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

mysql

### Expected and actual behavior

Enterred text is displayed

### Steps to reproduce the behavior

- Add a product to invoice
- click on the pen icon next to the product
- manually add some text
- save the changes
- generate PDF preview
- check result

**Comment by ReproductriceDeBugs** [comment]
In v18, I've tried several times and it doesn't happen, I can't reproduce this problem.
