### ISSUE TITLE
Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#24522]
### Bug

I got the following message after proceeding to linking supplier invoices in accountancy:

```
Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='
```

I am going to check the encodings of the database and make them uniform.

### Environment Version

16.0.1

**Comment by hregis** [comment]
@mdeweerd create a dump of your database, edit and replace all utf8_general_ci with utf8_unicode_ci and restore the dump. Check in conf.php if you use utf8_unicode_ci...

**Comment by mdeweerd** [comment]
To resolve the issue, I essentially did the following:

```sql
SET FOREIGN_KEY_CHECKS = 0;
ALTER DATABASE `MABDD` CHARACTER SET utf8 COLLATE utf8_unicode_ci;
/* And for every table: */
ALTER TABLE `MABDD`.`llx_accounting_account` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
```

EDIT: Backup, edit and restore would also work, but I find it somewhat more risky/work.  I created a copy of my DB first before doing the above.

EDIT2: Following @hregis advice, I also checkt conf.php where the collation was set to 'utf8_general_ci' - I changed that to `$dolibarr_main_db_collation='utf8_unicode_ci';`

FYI: the `conf.php` file shows `# File generated by Dolibarr installer 3.1.0 on 2011-12-17 20:11:13`

Another install I recently upgraded to 17.0.1 still had:
```
# File generated by Dolibarr installer 2.8.1 on jun 02, 2010
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
```

Suggestion: notify the user when upgrading.

**Comment by ksar-ksar** [comment]
https://wiki.dolibarr.org/index.php?title=Troubleshooting#I_encounter_a_DB_ERROR_message

`/install/repair.php?force_utf8_on_tables=confirmed for Mysql only, when Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=' `

**Comment by mdeweerd** [comment]
@ksar-ksar Having a repair script is helpfull, but I think this type of issue should be detected during the upgrade process.

I can see the following in the Changelog:
```
***** ChangeLog for 5.0.0 compared to 4.0.* *****
[...]
NEW: Default collation for mysql is now utf8_unicode_ci
```

Maybe it was not required back then, but it seems to be required now, so detected and updated during the update process.  The installation process checks prerequisited - I did not have php_imap installed the last upgrade and I could not upgrade.
The DB and configuration can be checked for invalid collations and the the update could be blocked until the users performs the "repair" if there is no plan to implement this automatically.

**Comment by ksar-ksar** [comment]
Dolibarr is open source, there is no plan, until someone makes one ;-)

**Comment by mdeweerd** [comment]
@ksar-ksar I already have enough open-source to manage on my hands 😺

**Comment by mdeweerd** [comment]
Thank you to both of you for your follow-ups.

Given my past experience on dolibarr issues, the importance of this one, the backlog, and a preference for not being reigned by bots that close issues for us because they are stale, I am fine with the [Won't be fixed/implemented](https://github.com/Dolibarr/dolibarr/labels/Won%27t%20be%20fixed%2Fimplemented) label which is likely close to reality.

I close this issue hoping that it frees up some attention for other more important stuff.
