### ISSUE TITLE
Product list is not showing V 17.0.1

### ISSUE THREAD

**Issue by MrZang101** [Dolibarr/dolibarr#24520]
### Bug

Hello, the product list is not showing at all even the products are listed and it shows the total 

![image](https://user-images.githubusercontent.com/51847523/232262043-74e668c1-00b7-4a59-800e-050071f4a024.png)

### Environment Version

17.0.1

### Environment OS

Linux  Ubuntu 

### Environment Web server

apache

### Environment PHP

8.1.17

### Environment Database

MySQL 

### Attached files

![Screenshot 2023-04-16 015731](https://user-images.githubusercontent.com/51847523/232262217-9f7e248e-6c99-4b8e-a2f6-e888da08151a.png)

**Comment by ksar-ksar** [comment]
Hello,

Blank page = PHP Error => Check your hosting logs.

**Comment by malikmami** [comment]
i have the same problem

**Comment by MrZang101** [comment]
hello, i did activate the php error logs and i got this error, i did make the installation  with Softaculos aswell jut for the information.
Ihappens also in Service List.

![image](https://user-images.githubusercontent.com/51847523/232324562-1a74fb91-393c-466a-97f9-f66905c4a7f4.png)


Looks like db missing

![image](https://user-images.githubusercontent.com/51847523/232324502-bd2e472d-102f-4baa-9a46-83243ce14064.png)

**Comment by ksar-ksar** [comment]
Hello,

Seems to be linked to workstation module, do you have it activated ?
![image](https://user-images.githubusercontent.com/35605507/232336497-4c5f3b83-11bd-4b32-9abb-a152c7e2e1b8.png)

**Comment by MrZang101** [comment]
i do not have this module in my version.

**Comment by hregis** [comment]
@MrZang101 this is fixed in futur 17.0.2
you can define MAIN_FEATURES_LEVEL with value 2 and enable/disable the "Workstation" module

**Comment by MrZang101** [comment]
Can you help a bit with this " MAIN_FEATURES_LEVEL 2 "  and i do not have workstation module in my version.

Can you help to update to 17.0.2? as i try to update from the panel it gives me last version.

**Comment by DTDM-Odin** [comment]
> Can you help a bit with this " MAIN_FEATURES_LEVEL 2 " and i do not have workstation module in my version.
> 
> Can you help to update to 17.0.2? as i try to update from the panel it gives me last version.

it's _Setup_ -> _Other Setup_ you can set this value, it solved the exact same issue for me.

**Comment by MrZang101** [comment]
![image](https://user-images.githubusercontent.com/51847523/232833407-10ac1143-23df-4407-ac10-b1f23bac860a.png)


If you talk about same thing, for me it did not work, did you restart the server or do something else? or the changes was done instantly?

**Comment by ksar-ksar** [comment]
It's instantaneous.
As soon as you put MAIN_FEATURES_LEVEL = 2 
Go to you module list and you will see the module WORKSTATION.
Then activate + desactivate it.

**Comment by hregis** [comment]
@MrZang101 this bug in product list is fixed in the next stable version of Dolibarr 17.0.2

**Comment by MrZang101** [comment]
@ksar-ksar  Thanks, your method made it works. 

thats good. Thanks again.
