### ISSUE TITLE
Dolibarr(version:17.0.1) product list not visible

### ISSUE THREAD

**Issue by pinalgirkar** [Dolibarr/dolibarr#24533]
### Bug

We have successfully installed Dolibarr (Version:17.0.1) on CentOS 7 PHP 8.1.2, Apache 2.2.34, MYSQL 5.5.62. However after complete installation when we login to admin panel and click on "Setup - Modules/Applications" and enable Products module and when we create a new product and go to view list it's not visible. Whereas when we install Dolibarr(Version:17.0.1)on PHP 8.0 and do the following the product list is visible. 

### Environment OS

CentOS Linux (Core 7)

### Environment Web server

 Apache/2.2.34

### Environment PHP

8.1.2

### Environment Database

MySQL5.5.62

### Expected and actual behavior

The added products should be visible when we try to view the list.

### Steps to reproduce the behavior

1. Install Dolibarr(Version: 17.0.1) on PHP version 8.1
2.  Then go to setup Modules/Applications and there search for product and refresh the search
3. Enable the product module and on header Product will be visible between home and tools 
4. Create a new product and save the form and click on list to view the added product

**Comment by hregis** [comment]
@pinalgirkar this is fixed in futur 17.0.2
you can define MAIN_FEATURES_LEVEL with value 2 and enable/disable the "Workstation" module
