### ISSUE TITLE
It's slow to open supplier's card with lots of invoices

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#24537]
### Bug

This supplier I have has 39000+ invoices

![image](https://user-images.githubusercontent.com/7734808/232691579-d09cd921-dba1-44bc-8d71-f01777597204.png)

Since it goes to check each invoice individually (`SELECT ******** WHERE fk_invoice_supplier = <invoice_id_N>`) it takes a while:

![image](https://user-images.githubusercontent.com/7734808/232692212-c03ccbdd-828e-4314-9c17-14eae305a9f9.png)

Here it only took 3 minutes (Lines inbetween deleted) but if I were to try and do something else in Dolibarr at the same time it would've been running for way way longer.

### Environment Version

16.0.3

**Comment by AurelienBISOTTI** [comment]
I wouldn't call this a bug.

On which page do you have these slow responses ? Can you do screenshots ?
Do you think these are unnecessary request, ie. you don't need this information ? 
Or you need this information but not every time and would like a button to load the data instead of loading it every time ?

**Comment by Daviid-P** [comment]
It's not a bug just inefficient and this is on my laptop, in the server is faster but I assume this depends on hardware.

Laptop running XAMPP:
- Processor: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz 2.42 GHz
- Installed RAM: 16.0 GB (15.8 GB usable)
- PHP Version: 7.4.33
- Apache Version: Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/7.4.33
- Apache API Version: 20120211
- Disks: 500GB nvme SSD

QNAP NAS Server Runing Linux:
- Processor: Intel(R) Xeon(R) CPU D-1622 @ 2.60GHz
- Installed RAM: 32.0 GB 
- PHP version: 7.4.30
- Server API: FPM/FastCGI
- Disks: 4 HDD

[CPU Comparison](https://www.cpubenchmark.net/compare/4278vs3830/Intel-Xeon-D-1622-vs-Intel-i5-1135G7)


> On which page do you have these slow responses ?

/htdocs/fourn/card.php?socid=
A provider has over 40k invoices so, for each invoice it has to call
`getSumCreditNotesUsed`
`getSumDepositsUsed`
`getSommePaiement`

Then in some invoices also `SELECT fk_invoice_supplier FROM llx_societe_remise_except WHERE fk_invoice_supplier_source = `

> Can you do screenshots ?

I can add logs. 
On my laptop page load starts at 07:37:40 and finishes at 07:40:30, so 3 minutes.
On the server page load starts at 07:41:41 and finishes at 07:41:47, so 6 seconds.


> Do you think these are unnecessary request, ie. you don't need this information ? Or you need this information but not every time and would like a button to load the data instead of loading it every time ?

The information is needed, AFAICS these kind of situations where you need to retrieve a huge amount of data ar usually done with a big query at the start of the page load with JOINS.


Why do you think is the difference in performance between laptop and server, it seems like the laptop is on par with the server in terms of CPU, it has less RAM but faster SSD.
[dolibarr_laptop.log](https://github.com/Dolibarr/dolibarr/files/11719971/dolibarr_laptop.log)
