### ISSUE TITLE
Email Collector php class fetch funtionality does not work

### ISSUE THREAD

**Issue by kilian099** [Dolibarr/dolibarr#24548]
### Bug

Menu manager: eldy_menu.php

Modules/Applications: user, syslog, emailcollector, mailing, stripe, clicktodial, externalsite, cron, notification, printing, debugbar, blockedlog, adherent, contrat, partnership, holiday, expensereport, ficheinter, recruitment, multicurrency, facture, export, banque, tax, hrm, salaries, loan, prelevement, propal, paymentbybanktransfer, fournisseur, societe, commande, expedition, margin, knowledgemanagement, product, comptabilite, service, projet, eventorganization, agenda, categorie, ecm, website, fckeditor, ticket, opensurvey
XDebug informations:
File: crm-erp/htdocs/emailcollector/class/emailcollector.class.php
Line: 2531
Function: fetch

### Environment Version

Dolibarr: 17.0.0 

### Environment OS

Rocky Linux

### Environment Web server

LiteSpeed

### Environment PHP

7.4.33

### Environment Database

mySQL

### Environment URL(s)

htdocs/emailcollector/class/emailcollector.class.php

### Expected and actual behavior

It Seems when I press test collector for collecting emails, it gives me an error:

Failed to create ticket: Error Incorrect string value: '\xEF\xBF\xBD Bo...' for column `admin_dolibarr`.`llx_ticket`.`message` at row 1

and I suspect, following other articles my DB is not reading emojis. However, I set the collation to all my tables into utf8mb4_unicode_ci and still the issue persist

### Steps to reproduce the behavior

Clicking Test email collector

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/24561

there is also a repair script at install/repair.php?force_utf8mb4_on_tables=confirmed
