### ISSUE TITLE
17.0.1 - Missing Formatting in de_CH translation causes lists in UI to break

### ISSUE THREAD

**Issue by LukOfDecen** [Dolibarr/dolibarr#24552]
### Bug

When choosing de_CH as default language: Whenever I try to add an item to an offer, invoice, contract or other, the whole table is missing and "Add item to list" fields are not showing.

In the standard log I see an exception:
```
PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in /var/www/html/core/class/translate.class.php:641\nStack trace:\n#0 /var/www/html/core/class/translate.class.php(641): sprintf()\n#1 /var/www/html/core/tpl/objectline_create.tpl.php(137): Translate->trans()\n#2 /var/www/html/core/class/commonobject.class.php(4873): include('...')\n#3 /var/www/html/comm/propal/card.php(2823): CommonObject->formAddObjectLine()\n#4 {main}\n  thrown in /var/www/html/core/class/translate.class.php on line 641, referer: https://crm.ibex.host/comm/propal/list.php?leftmenu=propals
```

It's tuxgasy/dolibarr container btw.

Here is a screenshot of the UI:

![grafik](https://user-images.githubusercontent.com/24474696/233121705-c3622598-c241-4d7d-b157-3e9e67fe648f.png)

Temporary fix is to choose de_DE as language and go with that translation.

**Comment by ReproductriceDeBugs** [comment]
This problem is still here in the v18
