### ISSUE TITLE
V17.0.0, V17.0.1 et V17.0.2 - Module Marges

### ISSUE THREAD

**Issue by nekoinformatique** [Dolibarr/dolibarr#24550]
### Bug

Souci sur le module marge depuis upgrade v16 vers v17

### Environment Version

17.0.0

### Environment OS

Debian 11

### Environment Web server

Apache/2.4.56

### Environment PHP

8.1.17

### Environment Database

MariaDB 10.5.18

### Expected and actual behavior

Accès refusé.
Vous essayez d'accéder à une page, région ou fonctionnalité d'un module désactivé, ou sans être dans une session authentifiée, ou avec un utilisateur non autorisé.

Quelque soit l'utilisateur avec les droits ok, test avec un nouvel utilisateur idem sur l'onglet "Marges par produit". Désactivation et réactivation du module idem.

### Steps to reproduce the behavior

Upgrade 16.04 to 17.0.0

**Comment by nekoinformatique** [comment]
J'ai pu résoudre le problème temporairement en commentant les lignes suivantes dans le fichier htdocs/margin/productMargins.php :

$result = restrictedArea($user, 'produit|service', $fieldvalue, 'product&product', '', '', $fieldtype);
if (empty($user->rights->margins->liretous)) {
	accessforbidden();
}

**Comment by ksar-ksar** [comment]
Hello,

On GitHub, you need to write in English please !

**Comment by inoveaconseil** [comment]
I can't reproduce in 17.0.3
