### ISSUE TITLE
The CKE Editor tools bar has disappeared from the notes (Invoices)

### ISSUE THREAD

**Issue by ghislainseguy** [Dolibarr/dolibarr#24551]
### Bug

When adding / editing a note linked to an invoice, the CKE toolbar does not appear anymore. 

This toolbar continues to be accessible when editing other text fields. 

Tested on my installation in preprod & prod (both in the same version).
The same behavior is visible on demo.dolibarr.org (version 17.0.1 too).

### Environment Version

17.0.1

### Environment OS

Lunix Ubuntu 22.04

### Environment Web server

nginx 1.18.0

### Environment PHP

8.1.12

### Environment Database

10.6.12

### Environment URL(s)

No access

### Steps to reproduce the behavior

Issue an invoice
Click on the note tab
Edit a note (public or private)

**Comment by hregis** [comment]
@ghislainseguy go to setup of "Advanced editor" module to activate this options

**Comment by ghislainseguy** [comment]
my bad. 
I had not checked all the options of this module. :(
