### ISSUE TITLE
Search functionnality in stock list doesn't work

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#24569]
### Bug

Search functionality in does not work

![Stock_à_date](https://user-images.githubusercontent.com/26635105/233768015-f905b7e7-1993-44ea-a428-c7f5f3dacfba.png)

### Environment Version

16.0.5

### Environment OS

Debian

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

MySQL

### Environment URL(s)

http://xxxxx/product/stock/stockatdate.php

### Expected and actual behavior

Search title should display element using the keyword

**Comment by ReproductriceDeBugs** [comment]
Seems to work in the v18.

<img width="931" alt="Capture d'écran_20230609_151015" src="https://github.com/Dolibarr/dolibarr/assets/135996360/96c2b0b3-f311-42bf-8107-8e16508830c9">

<img width="928" alt="Capture d'écran_20230609_151041" src="https://github.com/Dolibarr/dolibarr/assets/135996360/830baed1-c627-4844-9bfb-37a2e95a8f90">

**Comment by tiaris** [comment]
Done devcamp Bordeaux 
https://github.com/Dolibarr/dolibarr/pull/25056
