### ISSUE TITLE
Bug: incorrect VAT

### ISSUE THREAD

**Issue by ArnaudFR67** [Dolibarr/dolibarr#24570]
Hello all.

Below is the problem I am experiencing with version 17.0.1. 
The problem was already present with version 17.0.0.
I waited for version 17.0.1 before making the bug report in case the update fixes the bug.

Thank you all for your help.

# Bug
When I want to enter an invoice line with a product with 20% VAT, the VAT box is displayed at 0. If the product has a VAT other than 20% there is no problem.

## Environment
- **Version**: 17.0.1
- **OS**: Linux
- **Web server**: nginx/1.20.1
- **PHP**: fpm-fcgi 7.4.30
- **Database**: MySQL or MariaDB 5.5.5-10.3.32-MariaDB
- **URL(s)**: /dolibarr/htdocs/fourn/facture/card.php?facid=1349&save_lastsearch_values=1

## Expected and actual behavior
Expected : Auto filing with the good VAT rate.
Actual : VAT box at 0 only with the VAT 20% rate

## Steps to reproduce the behavior
Every time I enter a 20% VAT line.
The products have a registered purchase price at VAT 20%

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

Screen view sample : PRICE LIST
![image](https://user-images.githubusercontent.com/81926163/233785494-51660278-a303-43da-82fb-417e9514f79c.png)
Screen view sample: INVOICE
![image](https://user-images.githubusercontent.com/81926163/233785351-f8936073-3ac7-43e0-907f-9efd4b552a05.png)

**Comment by freechelmi** [comment]
Please edit the title with an explicit text

**Comment by ArnaudFR67** [comment]
Done
