### ISSUE TITLE
MAIN_ODT_AS_PDF can work , but the font type is different between odt and pdf

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#24575]
### Bug

When using MAIN_ODT_AS_PDF ( the value is libreoffice ) on dolibarr  , it will create a odt and a pdf file .
But it will show different font type .
![image](https://user-images.githubusercontent.com/78349579/233936202-96424185-14d1-4084-9bfd-ebbbae7e8669.png)

![image](https://user-images.githubusercontent.com/78349579/233936346-0a8caff3-a981-4490-8c42-a4fbf2219bd0.png)

And if you execute the command on terminal of the host , it will make a same font type pdf file .

### Environment Version

v16.0.5

### Environment OS

Deian 11

### Environment Web server

Apache/2.4.56 

### Environment PHP

7.4.33

### Environment Database

MariaDB 5.5.5-10.5.18

### Environment URL(s)

/comm/propal/card.php

### Expected and actual behavior

Should create a same pdf with same font type .

**Comment by michalhana99** [comment]
You have to install the font directly on the server in libreoffice if you have a different font

C:\Program Files\LibreOffice\program\resource\common\fonts

**Comment by trekmorris** [comment]
Hi 
My host is linux system , and i have installed the font that i need in host .

**Comment by michalhana99** [comment]
It is not enough to have the font installed in the system, but it must be found directly in all fonts in libre office

**Comment by trekmorris** [comment]
Hi

Yes , i have corrected it and works , thanks .

**Comment by trekmorris** [comment]
Install fonts in system , then this issue is gone .
