### ISSUE TITLE
REST API Explorer not working with Dolibarr 16.0.4 (error: ```failed to parse JSON/YAML response```) 

### ISSUE THREAD

**Issue by HichTala** [Dolibarr/dolibarr#24584]
### Bug

Hello,

I am trying to use REST API but it seems to have a bug...

### Environment Version

16.0.4

### Environment OS

Linux localhost 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 x86_64

### Environment Web server

Apache/2.4.52 (Ubuntu)

### Environment PHP

8.1.2-1ubuntu2

### Environment Database

MySQL or MariaDB 8.0.32-0ubuntu0.22.04.2

### Environment URL(s)

/api/index.php/explorer/

### Expected and actual behavior

As said in the documentation, I should be able to access the services available by accessing the following address:
http://yourdolibarrurl/api/index.php/explorer

But the following error appears instead:
```
failed to parse JSON/YAML response
```

Since the same error appear when I try to access to demonstration instance:
https://demo.dolibarr.org/api/index.php/explorer

I saw a similar problem on version 13.0.4, but since my version is 16.0.4 which is different from the demo instance version which is 17.0.1 I don't think it is related to the dolibarr version.

Everything suggests that this is a bug, however, I can't find any similar report on the internet. Any help is welcome.

**Comment by frederic34** [comment]
@HichTala try with php 7.4

**Comment by alexboin** [comment]
What is the message displayed when you go to the URL http://yourdolibarrurl/api/index.php/explorer/swagger.json ?

On the demo instance for example (https://demo.dolibarr.org/api/index.php/explorer/swagger.json), the page displays "Error temp dir api/temp not writable", you have probably the same problem

**Comment by HichTala** [comment]
Yeah, I have the same error ("Error temp dir api/temp not writable"), I am downgrading to php 7.4 to see if I got the same issue

**Comment by HichTala** [comment]
Ok, it works fine with php 7.4, is there any plan to fix the bug with the latest version of php ?

**Comment by frederic34** [comment]
not for v16, https://github.com/Dolibarr/dolibarr/pulls?q=is%3Apr+php8

**Comment by HichTala** [comment]
Okay, thank you !
