### ISSUE TITLE
Filter on categories of warehouses faulty

### ISSUE THREAD

**Issue by priojk** [Dolibarr/dolibarr#24631]
### Bug

After creating and assigning a tag/category to a warehouse, filtering for this category in the list of warehouses does not work correctly. 

### Environment Version

17.0.1 and 18.0.0-alpha

### Steps to reproduce the behavior

Create several warehouses in a hierarchy (not sure yet, if hierarchy is a contributing factor).
Create a category for warehouses.
Assign category to warehouse on top of hierarchy.
Go to list of warehouses and filter for the new category. Either nothing is found or even unrelated warehouses are shown instead.

**Comment by tiaris** [comment]
error on sql join

PR https://github.com/Dolibarr/dolibarr/pull/25055
