### ISSUE TITLE
Start and end date of contract lines not available in API anymore

### ISSUE THREAD

**Issue by st31ny** [Dolibarr/dolibarr#24661]
### Bug

In version 17 the contract start and end dates of contract lines are not exposed in the API anymore but are [cleaned before](https://github.com/Dolibarr/dolibarr/blob/b1e62d729754b94d8a50a83f1903ef3197a061e7/htdocs/contrat/class/api_contracts.class.php#L664).

### Environment Version

17.0.1

### Environment URL(s)

/api/index.php/contracts/93

### Expected and actual behavior

Until version 16, start and end dates of individual contract lines were included in the API response in the fields `date_start`, `date_start_real`, `date_end` and `date_end_real`. This was apparently changed in d597eb8 when the legacy field names were permanently removed. I would expect that the dates continue to be sent in the API as they are not particularly sensitive.

**Comment by jordiboschmartinez** [comment]
**Bug**
We have the same problem, we need a solution.

**Environment Version**
17.0.2

Thank you.

**Comment by akiraspa** [comment]
We have the same problem, please any help ? 
thank you
