### ISSUE TITLE
Take POS Ticket model bug v17 Dolibarr

### ISSUE THREAD

**Issue by phoneup** [Dolibarr/dolibarr#24662]
### Bug

Hello, we are having a problem with version 17 of Dolibarr and the "TakePOS" module.

When moving from v.16 to v.17 - the choice of a custom ticket template disappeared.

![01](https://user-images.githubusercontent.com/132357333/235660705-f8091226-b63b-4faf-b280-23cd0da871cd.png)

![02](https://user-images.githubusercontent.com/132357333/235660725-79060288-2be1-4b53-8f24-0bc0d30630d8.png)

This choice was available in version 16 of the TakePOS module in the Terminal 1 tab.

We have the possibility to reactivate this field by entering the following values in
“Configuration/Miscellaneous”:

TAKEPOS_PRINT_METHOD with value “receiptprinter or takeposconnector”

But the printer with the POS does not print the desired ticket, it no longer prints the ticket at all, I noticed that in the TakePOS module after entering the values "receiptprinter or takeposconnector"

Some of the options are missing compared to v16, the whole part called "printing method" In the "Printers / Receipt tab "

![03](https://user-images.githubusercontent.com/132357333/235661712-9cc173ef-1ab0-424f-af76-e1755fc05f68.png)

![Capture d’écran 2023-05-02 à 14 04 33](https://user-images.githubusercontent.com/132357333/235661814-b545847f-d361-43a9-ae2c-8569c3d265a0.png)

This part allowed to put the TakePOS Connector url required to print the ticket that we have personalized.

### Environment Version

17

**Comment by andreubisquerra** [comment]
You need install this module:
https://www.dolistore.com/en/modules/1889-TakePOS-Connector-17.html

**Comment by c3iserviciosinformaticos** [comment]
Hello

I installed mentioned module (takeposconnector 17) but it doesn't appear anything in "Modules" menu. I can´t turn on  the module becouse I can´t  find it.

Am I doing anything wrong ?

Thanks

**Comment by andreubisquerra** [comment]
It's working for us without a problem. Can you verify that it has been unzipped correctly? For some users the problem has been with the decompression.
