### ISSUE TITLE
Margin module not working in proposal/invoices (/comm/propal/card.php?id=92)

### ISSUE THREAD

**Issue by svewa** [Dolibarr/dolibarr#24673]
### Bug

While in the list view (/comm/propal/list.php) the margin is still visible, the detail view of any proposal or invoice does not show anything underneath the header of the margin module

### Environment Version

17.0.1

### Environment OS

Debian GNU/Linux 11

### Environment Web server

Apache 2.4.51

### Environment PHP

7.4.28

### Environment Database

mariadb

### Environment URL(s)

/comm/propal/card.php?id=92 /compta/facture/card.php?facid=104

### Expected and actual behavior

Before the update the module showed the margin while viewing propal/factura, also the header is still present.

### Steps to reproduce the behavior

Update to 17.0.1 and open any proposal/invoice

### Attached files

![Screenshot from 2023-05-03 11-14-57](https://user-images.githubusercontent.com/20936492/235877334-198987e0-6ad9-4dde-a02a-13895c236ef4.png)

**Comment by atm-maxime** [comment]
Hi ! I just checked with a 17.0.2 version and the margin table is correctly displayed.
Can you check on your end ?

**Comment by svewa** [comment]
I'm on 17.0.2 and it does not work. do I guess it's somehow database/config... how to debug this?

**Comment by svewa** [comment]
It was due to the product module being deactivated. Sadly module dependencies are not checked/enforced/warned about, anyway, user error, fixed now.
