### ISSUE TITLE
Internal transfer - Virement interne - issue with 2 different currency banks

### ISSUE THREAD

**Issue by Studio3Points** [Dolibarr/dolibarr#24692]
### Bug

Currently cannot do a transfer from a bank account to another because the field "AmountTo" is missing, it's happen with 2 different currency account.
![2023-05-05 17_42_10-Virement interne - Opera](https://user-images.githubusercontent.com/42969476/236438323-44159fd4-8900-4830-9682-7976724b4e9c.png)

### Environment Version

Dolibarr 17.0.2

### Environment OS

Apache

### Environment Web server

Apache

### Environment URL(s)

htdocs/compta/bank/transfer.php

**Comment by ReproductriceDeBugs** [comment]
This message does not appear in the v18

<img width="943" alt="Capture d'écran_20230609_153151" src="https://github.com/Dolibarr/dolibarr/assets/135996360/7508b5de-3e0f-46e5-b012-9cde688e0212">

<img width="953" alt="Capture d'écran_20230609_153211" src="https://github.com/Dolibarr/dolibarr/assets/135996360/42d9f6af-9067-42b0-8c79-e675d3c90aa4">

**Comment by AurelienBISOTTI** [comment]
You should have another field on the right of "amount"

I tried both in v17.0.2 and v18 and got the field.

Cannot reproduce your bug

Have you tried with other currencies ? Or reloading the page ?

![image](https://github.com/Dolibarr/dolibarr/assets/12530585/c5a50987-5326-47f1-bd44-7e013636a5ee)

**Comment by Studio3Points** [comment]
Problem solved for me on 17.02
