### ISSUE TITLE
Impossible to import data exported from another dolibarr installation

### ISSUE THREAD

**Issue by mjrfxci** [Dolibarr/dolibarr#24700]
### Bug

Hi all, I was asked to migrate a dolibarr installation from another due to a lot of problems with the admin of the site... I'm trying to import data (users, etc) from an exported dolibarr file installation and it's impossible to perform... I always get this error: **Incorrect value for field number 33: '2015-01-01 or 2015-01-01 12:30:00' does not match the rule ^[0-9][0 -9][0-9][0- 9]-[0-9][0-9]-[0-9][0-9]( [0-9][0-9]:[0- 9][0-9]:[0-9][0-9])?$**

This error corresponds to company field or column, also, I tried to use an example file given, with 0 or 1, even company names, THE SAME HAPPENS....

Note: I'm doing this without superuser privileges because the superuser wasn't given to me and no chance to access the database.

Any ideas about how to solve this Issue?

### Environment Version

17.0.1

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

Latest

### Environment Database

Mysql

### Environment URL(s)

https://comercialaxon.cl/erp/  and http://axon.pymeconectada.cl/

**Comment by emheyarssi** [comment]
Hi, did you have an access to the old instance of Dolibarr? If yes, why did you not try to restore the whole database and documents repository?
If so you'll got more help on the dolibarr forum. https://www.dolibarr.fr/forum/ or https://www.dolibarr.org/forum/

**Comment by mjrfxci** [comment]
> Hi, did you have an access to the old instance of Dolibarr? If yes, why did you not try to restore the whole database and documents repository? If so you'll got more help on the dolibarr forum. https://www.dolibarr.fr/forum/ or https://www.dolibarr.org/forum/

Hi! I don't have access to any other instance... I guess it's installed with softaculous from a cpanel.

**Comment by AurelienBISOTTI** [comment]
"from an exported dolibarr file installation"
What do you mean ? Do you have a database file, .sql ? Or just a copy of the server files ?

**Comment by hkwhitten** [comment]
When I have encountered this, it is due to a date format error. The error message string indicates 'or' of two date formats in your input for some reason. Please check the input csv file and verify the date column in question has only yyyy-mm-dd in it. That said, I am trying to do the same thing (export one instance, import to another), and encountering some minor issues that I will document shortly. Good luck.

**Comment by eldy** [comment]
Pb seems int the source file that contains "2015-01-01 or 2015-01-01 12:30:00" into a field date instead of
'2015-01-01' 
or (you must chooe)
'2015-01-01 12:30:00'
So i close ticket.
