### ISSUE TITLE
V17.00 and V17.01 "Nested" labels/categories do not work correctly in products and projects.

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#24707]
### Bug

V17.0.0 After upgrading from v16.04 to v17, "nested" tags/categories do not work correctly.
In previous versions, categories were nested in such a way that one product or project could have the final feature applied to it and assigned to all previous ones.
Now this function has disappeared and each feature is unique, requiring more steps to filter products and projects. It also forces us to re-label all our products and re-categorise all our projects.
It is a loss of functionality so important that it forces us to rethink the use of dolibarr.
We go back to version 16.04.
I have run several tests again.
Upgrading from version 16.04, 16.07, 17.00 and 17.01
The problem persists, I have also tried deleting the database and performing a clean install from 17.01 and loading the database.
The problem remains. 

### Environment Version

Versión actual 17.01

### Environment OS

W10 (Win64)

### Environment Web server

Apache/2.4.48 (Win64)

### Environment PHP

PHP/7.4.23

### Environment Database

MariaDB 5.5.5-10.10.2-MariaDB

### Environment URL(s)

localhost

### Expected and actual behavior

The problem is in the **filtering by categories in Products and Projects** (you can easily check it with the image provided).
If you use a category structure with a lot of branching, the way in which the selection is made until version 16.05 was in a single step, since version 17.00 the nesting ">>" between sub-categories has disappeared, creating a problem, where it did not exist before. 

### Steps to reproduce the behavior

Create a nested category structure for 10-level products in version 16.05 and the same in version 17.00 or 17.01 and now imagine working with thousands of products and even deeper structures.  The work becomes extremely exhausting.

### Attached files

![Productos listado por Categorias  ](https://user-images.githubusercontent.com/73311267/236692507-0cadae73-a580-4783-9777-bc6a61064544.jpg)

**Comment by AurelienBISOTTI** [comment]
Can reproduce in v18

I don't think this is a bug, but a default design choice
I think there might be a possibility to switch to old view.



![Capture d’écran du 2023-06-10 18-59-35](https://github.com/Dolibarr/dolibarr/assets/12530585/fc9a7fe9-6e2c-4d43-a012-694663667917)
![Capture d’écran du 2023-06-10 18-59-51](https://github.com/Dolibarr/dolibarr/assets/12530585/8f721cb3-35a9-4736-b2b0-3b5fba89b91f)

**Comment by AurelienBISOTTI** [comment]
In another menu, I have all the categories correctly displayed

![Capture d’écran du 2023-06-11 11-48-26](https://github.com/Dolibarr/dolibarr/assets/12530585/860abb8c-a3fb-4117-bc05-4fafbbdd0672)
