### ISSUE TITLE
EXPORT ASISTENT 18.0.0-alpha

### ISSUE THREAD

**Issue by mirnes81** [Dolibarr/dolibarr#24715]
### Bug

I am using version 18 Alpha I know this a devlepement version but I am using it as emme

I will report to you the beug follow a letap 5 extraction nothing more

![Capture web_9-5-2023_152041_mirnes ch](https://github.com/Dolibarr/dolibarr/assets/45318125/a397555e-a4ab-42a9-9231-b8835fea391e)

### Environment Version

18

### Environment OS

Windows

### Environment PHP

7.3

**Comment by ksar-ksar** [comment]
Hello,

Blank page = PHP Error => What does the PHP logs said ?

**Comment by ozit** [comment]
Hello,
almost the same bug
I don't have a completely blank page, just the "below" part (see attached image)
I don't believe there is an error in the logs.
![Capture d'écran 2023-05-15 155853](https://github.com/Dolibarr/dolibarr/assets/8665615/4e6211fa-6ec3-4673-bc4c-70c24eb0a6b3)
![Capture d'écran 2023-05-15 155844](https://github.com/Dolibarr/dolibarr/assets/8665615/e43fefcd-fdac-4dc6-8ed6-4b3948679157)

**Comment by ksar-ksar** [comment]
Yes, just the below part means PHP error
Can you check the logs ?

Edit, I have reproduced the error on the latest Dev version : 
`PHP Fatal error:  Cannot declare class ExportCsv, because the name is already in use in /var/www/doli/dev/core/modules/export/export_csv.modules.php on line 0`

**Comment by mirnes81** [comment]
I want but I don't know how to do it sorry

**Comment by tiaris** [comment]
works for me 18.0-beta devcamp Boirdeaux

**Comment by AurelienBISOTTI** [comment]
From a fresh install, I cannot reproduce

Do those who have been able to reproduce upgraded from an older version ?
![Capture d’écran du 2023-06-11 11-18-32](https://github.com/Dolibarr/dolibarr/assets/12530585/0f1b294e-cdfa-48fa-bf08-76ce53858ccc)

**Comment by apio-sys** [comment]
I can still reproduce this but with an upgraded version to 18.0.0 from 17.0.3 (initial installation 3.6.2).

**Comment by ksar-ksar** [comment]
Hello,

Explained here : #25654 

In V18, the file htdocs/core/modules/export/exports_csv.modules.php has been renamed to htdocs/core/modules/export/exportscsv.modules.php

Do you have both files or only one?

FIX #25741

**Comment by apio-sys** [comment]
Thanks @ksar-ksar . Indeed my issue was there for the same reason by upgrading by copying the new files over the old ones. Cleaned all out and did it again and it's working OK again. Thanks for that.

I usually upgrade as follows:

cd /var/www/[dolibarr_webdir]
git clone https://github.com/dolibarr/dolibarr -b 18.0.0

\cp -r dolibarr/htdocs/* htdocs
\cp -r dolibarr/scripts/* scripts

So it's really better to clear the code dirs first I presume to avoid such errors.
