### ISSUE TITLE
Special Characters button in CKEditor is missing in v17

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#24710]
### Bug

After updating to V17, the special characters button disappeared from ckeditor. We use that button to insert characters that are not easily found in the standard Spanish keyboard, such as the multiplication symbol × 

I saw that the button was removed by this commit https://github.com/Dolibarr/dolibarr/commit/9f0eaf58a9c88fb956064c1f38ae7330324b9d24

Please restore the button, or allow enabling it in some way (maybe through setup other?)

### Environment Version

17.0.1

### Environment OS

Linux webm074.cluster003.gra.hosting.ovh.net 5.15.80-ovh-vps-grsec-zfs-classid

### Environment Web server

Apache (from OVH shared hosting, no idea on the version)

### Environment PHP

7.4.33

### Environment Database

MySQL or MariaDB 5.7.42-log

### Expected and actual behavior

Special chars button should appear in the WYSIWYG editor (CKEditor)

### Steps to reproduce the behavior

Install or update Dolibarr to V17+

**Comment by AurelienBISOTTI** [comment]
I wouldn't call it a bug.
If it was removed, there might be a reason.
@eldy do you remember why special character were removed from ckeditor ?

**Comment by eldy** [comment]
The features was not used a lot and brings a lot of troubles (security, pb with pdf generation, page code incompatibility with some browsers...). So it was removed.
An option to disable/enable it would have been a better option. 

I add a tag to convert it as a feature request...
We must add an option WYSIWYG_ALLOW_SPECIAL_ CHAR into module wysiwyg to allow special char, enabling this option must restore old code.

**Comment by oussamanhairech** [comment]
Hi, I  restored the  code https://github.com/Dolibarr/dolibarr/commit/9f0eaf58a9c88fb956064c1f38ae7330324b9d24 but I don't see the special character button. Did I miss something?

**Comment by eldy** [comment]
After you have modified the code of ckeditor/config.js
Try to clear you browser cache, to see if the change appears...

**Comment by eldy** [comment]
Note; into doleditor.class.php, we have this 
$pluginstodisable = 'elementspath,save,flash,div,specialchar,anchor';
Must be

```
$pluginstodisable = 'elementspath,save,flash,div,anchor';
if (!getDolGlobalInst('WYSIWYG_ALLOW_SPECIAL_CHAR')) {
$pluginstodisable .= ',specialchar';
}
```

**Comment by eldy** [comment]
Option FCKEDITOR_ENABLE_SPECIALCHAR has been introduced for v19
