### ISSUE TITLE
Allow a contact to be associated to multiple third parties

### ISSUE THREAD

**Issue by mattcole-42** [Dolibarr/dolibarr#24720]
### Feature Request

Allow a contact to be associated to multiple third parties

### Use case

We deal with several contacts (sporting coaches) that work at several schools and or clubs, it would be great if we could have a single contact linked to multiple third parties so we are not duplicating data, and it is easier to maintain contact details.

**Comment by edupulpillo** [comment]
Also useful when a Sales man is representing several companies.

**Comment by leninrivas** [comment]
That is function ok with contacts from Parent Company

**Comment by edupulpillo** [comment]
But maybe a contact work in several companies that are not parent/child companies

**Comment by mattcole-42** [comment]
Exactly we have sport coaches who work for a school, and for a private club, that has no link to the school. We would like to be able to add the 1 contact to 2 or more third parties where there is no link between the third parties.
