### ISSUE TITLE
Transifex pull resulting in error

### ISSUE THREAD

**Issue by priojk** [Dolibarr/dolibarr#24723]
### Bug

Installed transifex client according to wiki. While it was possible before to pull the latest transifex translations, I get now constantly an error message, even for tx status:

tx ERROR: ValueError: not enough values to unpack (expected 2, got 1)

This seems to be some internal error of the python client, maybe due to some config file contents. Did anyone else see this behaviour recently? Don't find any hint on the Web, but this happens on two different machines (Ubuntu 20 and 22).

**Comment by eldy** [comment]
Same trouble for me...
Updating tx client from 1.6.4 to 1.6.7 has solved the trouble for me.
