### ISSUE TITLE
Accountancy - Chart of accounts

### ISSUE THREAD

**Issue by Zoszko92** [Dolibarr/dolibarr#24726]
### Bug

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set $dolibarr_main_prod to '1' to hide sensitive information):
Date: 20230509174808
Dolibarr: 17.0.1 - https://www.dolibarr.org
Functions level: 0
PHP: 7.3.12
Server: Apache/2.4.41 (Win64) PHP/7.3.12
OS: Windows NT DESKTOP-ODH758O 10.0 build 19044 (Windows 10) AMD64
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

Requested URL: /dolibarr/accountancy/admin/account.php?mainmenu=accountancy&leftmenu=accountancy_admin
Referer: http://192.168.0.196/dolibarr/accountancy/index.php?leftmenu=accountancy_admin
Menu manager: eldy_menu.php

Modules/Applications: user, label, debugbar, accounting, export, import, knowledgemanagement, workflow, modulebuilder, eventorganization, propal, expedition, test module, tax, ficheinter, fckeditor, partnership, incoterm, contrat, stocktransfer, supplier_proposal, product, stock, agenda, bom, banque, barcode, productbatch, cron, commande, ecm, expensereport, projet, facture, fournisseur, mrp, categorie, multicurrency, asset, resource, service, societe, ticket, variants, hrm
Database type manager: mysqli
Error message for last database access: SELECT aa.rowid, aa.fk_pcg_version, aa.pcg_type, aa.account_number, aa.account_parent, aa.label, aa.labelshort, aa.fk_accounting_category, aa.reconcilable, aa.active, aa.import_key , a2.rowid as rowid2, a2.label as label2, a2.account_number as account_number2 FROM llx_accounting_account as aa LEFT JOIN llx_accounting_system as asy ON aa.fk_pcg_version = asy.pcg_version AND aa.entity = 1 LEFT JOIN llx_accounting_account as a2 ON a2.rowid = aa.account_parent AND a2.entity = 1 WHERE asy.rowid = 2 ORDER BY aa.account_number ASC LIMIT 26
Error code for last database access: DB_ERROR_NOSUCHTABLE
Description of the last database access error: Table 'dolibarr.llx_accounting_account' doesn't exist

### Environment Version

17.0.0

### Environment OS

Windows

### Environment Web server

Apache/2.4.41 (Win64) PHP/7.3.12

### Environment PHP

7.3.12

### Environment Database

	5.5.5-10.4.10-MariaDB

**Comment by AurelienBISOTTI** [comment]
"Table 'dolibarr.llx_accounting_account' doesn't exist"
Did you update from an older version or your 17.0.1 is a fresh install ?

This is an obvious problem, the table should exist.
You never used accounting before ?

First, make a backup
Then try updating to a newer version

**Comment by aspangaro** [comment]
No answer -> Close

**Comment by Confeder8** [comment]
![image](https://github.com/Dolibarr/dolibarr/assets/63389186/6ae04c29-7119-4fed-9c78-b87cf19f8640)
i have created a fresh table, and it works
