### ISSUE TITLE
Solved - After first time setup can´t go further - because of PHP8.2 ?

### ISSUE THREAD

**Issue by WeT-Klb** [Dolibarr/dolibarr#24725]
### Bug

I installed Dolibarr 18.0.0-Alpha and did the first setup on my NAS. Even i was told my PHP was too high it did all the installation.
The table in MariaDB are created and the admin user and passwort of Dolibarr are set.
I am told the setup was successfull - but the installer keep on adress http://192.168.1.241/dolibarr/htdocs/install/step5.php.
What do i need to do to use it?
If i enter http://192.168.1.241/dolibarr/ on a secon tab i get a "403 Forbidden" - i have no idea how to make Dolibarr run.

### Environment Version

18.0.0-Alpha

### Environment OS

QNAP-NAS

### Environment Web server

QNAP-NAS (Apache)

### Environment PHP

8.2.4

### Environment Database

MariaDB 10.5.8

### Expected and actual behavior

At least after creating the admin user and passwort i should see the login page.

**Comment by AurelienBISOTTI** [comment]
Did you try switching to PHP 8.0 ? Can you go after step 5 with 8.0 ?

**Comment by WeT-Klb** [comment]
No i didn´t switch to PHP 8.0 - but after trying release 17.0.0 the setup worked fine - i even updated to 17.0.2.
So it seems somehow my 18.0-alpha-trial only made trouble.
