### ISSUE TITLE
FIX: SUPPLIER_ORDER_MORE_THAN_WISHED does not work as expected

### ISSUE THREAD

**Issue by aluquerivas-dev** [Dolibarr/dolibarr#24728]
### Bug

When activating the SUPPLIER ORDER MORE_THAN_WISHED option, the calculation of the expected and received lines is not correct, so even adding 1 single item of N, if it exceeds the expected quantity, the status of the supplier order will change to fully received.

### Environment Version

16.0.4

### Environment OS

Debian

### Environment Web server

Debian Buster

### Environment PHP

7.4

### Environment Database

MariaDB

### Expected and actual behavior

A supplier order must be given in full with the SUPPLIER_ORDER_MORE_THAN_WISHED option active when each of its lines is equal to or greater than the expected quantity

### Steps to reproduce the behavior

Activate the SUPPLIER_ORDER_MORE_THAN_WISHED option, create a supplier order with N lines, fully receive one of the lines, exceeding or not the expected stock and you will see how the order changes status, there are still N-1 unprocessed lines.

### FIX

```php
elseif (!empty($conf->global->SUPPLIER_ORDER_MORE_THAN_WISHED)) {
						//set livraison to 'tot' if more products received than wished. (and if $closeopenorder is set to 1 of course...)

						$close = 0;

						if (count($this->lines) > 0) {
							//there are some difference between  the two arrays
						
							//scan the array of results
							foreach ($this->lines as $key => $value) {
								
								//if the quantity delivered is greater or equal to wish quantity
								if ($qtydelivered[$value->fk_product] >= $qtywished[$value->fk_product]) {
									$close++;
								}
							}
						}

						if (count($this->lines)==$close) {
							//all the products are received equal or more than the wished quantity
							if ($closeopenorder) {
								$ret = $this->Livraison($user, $date_liv, 'tot', $comment); // GETPOST("type") is 'tot', 'par', 'nev', 'can'
								if ($ret < 0) {
									return -1;
								}
								return 5;
							} else {
								//Diff => received partially
								$ret = $this->Livraison($user, $date_liv, 'par', $comment); // GETPOST("type") is 'tot', 'par', 'nev', 'can'
								if ($ret < 0) {
									return -1;
								}
								return 4;
							}
						} else {
							//all the products are not received
							$ret = $this->Livraison($user, $date_liv, 'par', $comment); // GETPOST("type") is 'tot', 'par', 'nev', 'can'
							if ($ret < 0) {
								return -1;
							}
							return 4;
						}
					}
```

**Comment by aluquerivas-dev** [comment]
To solve on CommandeFournisseur.class.php:

elseif (!empty($conf->global->SUPPLIER_ORDER_MORE_THAN_WISHED)) {
						//set livraison to 'tot' if more products received than wished. (and if $closeopenorder is set to 1 of course...)

						$close = 0;

						if (count($this->lines) > 0) {
							//there are some difference between  the two arrays
						
							//scan the array of results
							foreach ($this->lines as $key => $value) {
								
								//if the quantity delivered is greater or equal to wish quantity
								if ($qtydelivered[$value->fk_product] >= $qtywished[$value->fk_product]) {
									$close++;
								}
							}
						}
						if (count($this->lines)==$close) {
							//all the products are received equal or more than the wished quantity
							if ($closeopenorder) {
								$ret = $this->Livraison($user, $date_liv, 'tot', $comment); // GETPOST("type") is 'tot', 'par', 'nev', 'can'
								if ($ret < 0) {
									return -1;
								}
								return 5;
							} else {
								//Diff => received partially
								$ret = $this->Livraison($user, $date_liv, 'par', $comment); // GETPOST("type") is 'tot', 'par', 'nev', 'can'
								if ($ret < 0) {
									return -1;
								}
								return 4;
							}
						} else {
							//all the products are not received
							$ret = $this->Livraison($user, $date_liv, 'par', $comment); // GETPOST("type") is 'tot', 'par', 'nev', 'can'
							if ($ret < 0) {
								return -1;
							}
							return 4;
						}
					}

**Comment by ReproductriceDeBugs** [comment]
Do a pull request inside GitHub please
