### ISSUE TITLE
Bad original file scheme for supplier invoices returned

### ISSUE THREAD

**Issue by romain-neil** [Dolibarr/dolibarr#24733]
### Bug

Hello,

It's seems that the function `dol_check_secure_access_document` return an invalid original file path, for the supplier invoices:

On the file files.lib.php (lines 3019 to 3025), the path returned follow the same scheme as for 'standard' invoices
> documents/fournisseur/facture/SI2304-0001/SI2304-0001.pdf

which is incorrect regarding of real path
> documents/fournisseur/facture/(arbitrary interger)/0/SI2304-0001/SI2304-0001.pdf

I don't know what the arbitrary number refer to, i don't see any link to the supplier (I create 2 suppliers following, but the id jump from 1 to 3)

I currently work on adding the support to generating supplier invoices on api, the supplier invoice is correctly generated, but he say that the file doesn't exists, according to the file path return by the function.

### Environment Version

17.0.0

### Environment OS

linux

### Environment Web server

apache

### Environment PHP

8.1.18

### Environment Database

mariadb 10.6.12

**Comment by eldy** [comment]
The 2 number 
.../x/y/refinvoice...

are 
x  = unit of id of invoice
y = the tens digit (0) if id <10
When you mention a supplier incoive you must use the relative path
x/y/ref/ref.pdf

**Comment by GuillaumeHullin** [comment]
Is there a specific reason why this architecture is for supplier invoices, it seems that it is not used for any other objects.
