### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ObscurHell** [Dolibarr/dolibarr#24744]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 17.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.52 (Ubuntu)
- **PHP**: apache2handler 8.1.2-1ubuntu2.11
- **Database**: MySQL or MariaDB 8.0.33-0ubuntu0.22.04.1
- **URL(s)**: /societe/index.php?mainmenu=companies&leftmenu=

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

Can you describe the bug you are facing ?
