### ISSUE TITLE
Picture from contact not visible

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#24757]
### Bug

I uploaded a pic from a contact and it is saved in directorey /documents/societe/contact/3066/photos
if I open modify it is visible
else (in list info or in view mode) it isn't visible

/htdocs/contact/card.php

edit-mode:
![image](https://github.com/Dolibarr/dolibarr/assets/3923753/24de66c1-a0a0-4e87-9a1e-4946d09b3f7b)

view-mode:

![Screenshot_2023-05-13_09-14-47](https://github.com/Dolibarr/dolibarr/assets/3923753/02fe8117-254b-4bf1-a766-54a98a61d996)

### Environment Version

17.0.1

### Environment OS

linux

### Environment PHP

PHP7.4

**Comment by Hystepik** [comment]
It seems to be fixed in last version of 17.0.2.

**Comment by EchoLoGeek** [comment]
Can't reproduce too

**Comment by Tr4sK** [comment]
Hi, I can reproduce the bug when the source file is webp.  
If I convert the file to .png it works.

Dolibarr 18.0.4
