### ISSUE TITLE
Report in Module Bank

### ISSUE THREAD

**Issue by ptagesen** [Dolibarr/dolibarr#24756]
### Bug

In version 17.0.1 (using php 8.0) the sums in monthly report in the module "bank" are incorrect. I found a problem in the file compta/bank/annuel.php. In line 199 and 200 the annual sums for "sorties" and "entrees" are set to zero every month in the loop over years. So as a final result I only see the sum of December.
Instead of 
```
for ($annee = $year_start; $annee <= $year_end; $annee++) {
$totsorties[$annee] = 0;
$totentrees[$annee] = 0;

```
it should be like this:
```
$totsorties[$annee] = 0;|
$totentrees[$annee] = 0;|
for ($annee = $year_start; $annee <= $year_end; $annee++) {
```

I'm not a developer, so maybe someone can fix this for future releases.

thx, Peter

### Environment Version

17.0.1

### Environment OS

synology disk station - linux

### Environment Web server

nginx

### Environment PHP

8.0

### Environment Database

MariaDB 10

### Expected and actual behavior

explained in Bug-Description.

### Steps to reproduce the behavior

In the menu Bank open the monthly report. The sum for the year is incorrect.

**Comment by aspangaro** [comment]
#24996
