### ISSUE TITLE
Exporting Invoices with free-text item doesn't export item description

### ISSUE THREAD

**Issue by Adventurousdonut** [Dolibarr/dolibarr#24763]
### Bug

When you create a vendor invoice for example with a free-text item and you try to export all the vendor invoices using the data exports module it doesn't display the item description.

### Environment Version

17.0.1

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

PHP 8.1.18

### Environment Database

MySQL

**Comment by EchoLoGeek** [comment]
Seems to work in v18

**Comment by AurelienBISOTTI** [comment]
![Capture d’écran du 2023-06-08 23-49-43](https://github.com/Dolibarr/dolibarr/assets/12530585/45df7b2e-a9e6-4093-b3ac-8af4f09a2894)
Works in V18

**Comment by Adventurousdonut** [comment]
Yeah seems to work in V18, thanks!
