### ISSUE TITLE
problem using dolibar 17.1 with a reverse proxy nginx

### ISSUE THREAD

**Issue by soros7575** [Dolibarr/dolibarr#24778]
### Bug

it shows a security problem  ; which has no solution.

### Environment Version

ubuntu 22

### Environment OS

ubuntu 22

### Environment Web server

nginx reverse proxy

### Environment PHP

7.4

### Environment Database

mariadb

**Comment by HLFH** [comment]
@soros7575 What is the problem? I use nginx as a reverse proxy and I was recently testing the latest dolibarr.
