### ISSUE TITLE
500 Error - Serialization error during update of custom field

### ISSUE THREAD

**Issue by matll42** [Dolibarr/dolibarr#24780]
### Bug

When I attempt to update a custom field from the facture card, I have a unhandled 500 error.

I just updated :
- dolibarr from 16.0.4 to 17.0.1
- ubuntu 20.04 to 22.04
  - php from 7.4 to 8.1
  - pgsql from 12.x to 14.7)

This custom field is a simple boolean and was working before the bunch of update.

Here is the apache log.
```
[Mon May 15 21:54:34.209985 2023] [php:error] [pid 5655] [client 12.34.56.78:50449] PHP Fatal error:  Uncaught Exception: Serialization of 'PgSql\\Connection' is not allowed in /opt/dolibarr/htdocs/core/lib/functions.lib.php:1167\nStack trace:\n#0 /opt/dolibarr/htdocs/core/lib/functions.lib.php(1167): serialize()\n#1 /opt/dolibarr/htdocs/compta/facture/card.php(2875): dol_clone()\n#2 {main}\n  thrown in /opt/dolibarr/htdocs/core/lib/functions.lib.php on line 1167, referer: https://myowidolibarr.ca/compta/facture/card.php?id=61&action=edit_extras&token=hiddentoken&attribute=quickbooks&ignorecollapsesetup=1
```

### Environment Version

17.0.1

### Environment OS

Ubuntu 22.04 LTS

### Environment Web server

Apache 2.4

### Environment PHP

php 8.1.2

### Environment Database

postgresql 14.7

### Environment URL(s)

/compta/facture/card.php

### Expected and actual behavior

**Expected behaviour:**
Just refresh the page with updated custom field (box checked in my case)

**Actual behaviour:**
After submit the update of the single custom field, I see the 500 error on my browser.

### Steps to reproduce the behavior

Pre-requisite: have a (boolean) custom field on invoice card.
Create an invoice without filling the custom field.
once created (and validated), click the pen near the custom field to enable input, update the custom field and click Update <- and showtime

### Attached files

Concern my "quickbooks" field
<img width="694" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/1232923/ed62bed1-d20e-48a8-b53c-0d03f57017bd">
<img width="1475" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/1232923/bdd21b75-8db6-4dfb-a482-b6e61a4d16f9">

**Comment by Hystepik** [comment]
Hello,
It works for me in last version of 16.0.5
and in last version of 17.0.2

**Comment by faveurs9** [comment]
same problem as matll42 after upgrade postgres 14.7 php 8.1.9. Custom field is a date in shipment

**Comment by Daviid-P** [comment]
It seems like there's already code for the case of trying to seriealize `PgSql\Connection`, could it be that it's not matching `PgSql\Connection` with `PgSql\\Connection` because of the double \\?

Or is that just for printing?

https://github.com/Dolibarr/dolibarr/blob/4c7f54fc4136cba8bc1f9b6831343c15c626e167/htdocs/core/lib/functions.lib.php#L1159-L1172


If that's not the problem maybe try changing in `htdocs\compta\facture\card.php`

`$object->oldcopy = dol_clone($object);`
to
`$object->oldcopy = dol_clone($object, 2);`

Or directly on https://github.com/Dolibarr/dolibarr/blob/4c7f54fc4136cba8bc1f9b6831343c15c626e167/htdocs/core/lib/functions.lib.php#L1157

change the default $native value to 2

**Comment by faveurs9** [comment]
change the default $native value to 2, works for me

**Comment by matll42** [comment]
Worked for me too, thanks @Daviid-P (changed directly info `dolibarr/htdocs/core/lib/functions.lib.php`

**Comment by Daviid-P** [comment]
It does say that method 0 is deprecated so someone probably forgot to change the default argument value

**Comment by zengoxz** [comment]
Change PHP to v. 8.0
