### ISSUE TITLE
Uncaught mysqli_sql_exception: Invalid character set was provided

### ISSUE THREAD

**Issue by HLFH** [Dolibarr/dolibarr#24784]
### Bug

At the end of the Dolibarr setup (branch develop, last commit used: https://github.com/Dolibarr/dolibarr/commit/bc63d70e0266efac8914a2b0122d6e1595280c88), I got this error with HTTP 500: "Uncaught mysqli_sql_exception: Invalid character set was provided".
It may have been fixed with the following commits, but it is best to state that this issue happened.

### Environment Version

develop branch

### Environment OS

Arch Linux

### Environment Web server

nginx

### Environment PHP

php-fpm-legacy

### Environment Database

MariaDB

**Comment by ksar-ksar** [comment]
Hello,

V18 was not stable at that time, do you still have the issue with the current V18 ?

**Comment by TiJof** [comment]
The same error in the stable 18.0.0
The trace :
```
GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XXXXXX"
2023/08/18 15:47:34 [error] 3011086#3011086: *422364 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Invalid character set was provided in /var/www/dolibarr/htdocs/core/db/mysqli.class.php:121
Stack trace:
#0 /var/www/dolibarr/htdocs/core/db/mysqli.class.php(121): mysqli->set_charset()
#1 /var/www/dolibarr/htdocs/core/lib/functions.lib.php(245): DoliDBMysqli->__construct()
#2 /var/www/dolibarr/htdocs/master.inc.php(140): getDoliDBInstance()
#3 /var/www/dolibarr/htdocs/main.inc.php(358): require_once('...')
#4 /var/www/dolibarr/htdocs/index.php(31): require('...')
#5 {main}
  thrown in /var/www/dolibarr/htdocs/core/db/mysqli.class.php on line 121" while reading response header from upstream, client: 127.0.0.1, server: XXXXXX, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XXXXXX"

```

I use php-fpm, 8.2 and nginx on Debian. No warning nor Error in 17.0.3

EDIT : Same on 18.0.1

**Comment by saygonka** [comment]
I encountered the same error while upgrading from 17.0.2 to 18.0.1.

**Comment by saygonka** [comment]
I have found a solution to the issue. To make Dolibarr 18.0.1 work correctly, I needed to update the htdocs/conf/conf.php file and modify two parameters as follows:

```
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
```

**Comment by ttheghost** [comment]
i encountered the same problem with mariaDB afret upgrading to version 10.4.32-MariaDB 
`Fatal error: Uncaught mysqli_sql_exception: Invalid character set was provided in C:\xampp\htdocs\**********\lib\classes\Db.php:26 Stack trace: #0 C:\xampp\htdocs\**********\lib\classes\Db.php(26): mysqli->set_charset('UTF-8') #1 C:\xampp\htdocs\**********\lib\classes\Db.php(53): Paradise\Db->__construct() #2 C:\xampp\htdocs\**********\lib\classes\Schema\User.php(201): Paradise\Db::getInstance() #3 C:\xampp\htdocs\**********\lib\common.php(75): Paradise\User::session() #4 C:\xampp\htdocs\**********\index.php(8): require_once('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\**********\lib\classes\Db.php on line 26`

my code was 
```php
parent::__construct(Core::sanitizeMySQLHost(DB_CONFIG['HOST']), Core::sanitizeMySQLUser(DB_CONFIG['USER']), DB_CONFIG['PASSWORD'], DB_CONFIG['DATABASENAME']);
$this->set_charset('UTF-8');
```
after some search i found that the UTF-8 character set need to be utf8 (without dash)

```php
$this->set_charset('utf8');
```

sorry for my English
