### ISSUE TITLE
Setting GitHub issues labels (First)

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2481]
This is a great move.

But you ask us to set labels in the annonce and we can't :(

Only team members and project owners can set labels!

**Comment by rdoursenaud** [comment]
See: https://help.github.com/articles/permission-levels-for-an-organization-repository/ for more informations.

**Comment by BebZ** [comment]
how you set lables finally ? is it made by core team ?

**Comment by eldy** [comment]
For the moment, just put "FEATURE REQUEST" or "BUG" at begin of title.

**Comment by rdoursenaud** [comment]
I'd like to separate the "Bug" label from the urgency labels ("Minor", "Major", "Critical","Security").
This way we can use the same urgency labels on "Feature Requests" and remove the "Feature Request High Priority" label.
This will allow more granularity when filtering issues and will be true to the label paradigm.

Eg: I want to work on all security issues
I just filter on the "Security" tag and have related bugs and feature requests.
On the other hand, if I want to tackle critical bugs only in the 3.6.3 version, I filter on "Bugs", "Critical" and "version 3.6.3".

Any arguments against this change? @eldy @simnandez

**Comment by simnandez** [comment]
For my part, no arguments against. Although I would add "Blocking" label.

**Comment by ndrosis** [comment]
I think must be there a detailed description of the "BUG"
example

Version: Dolibarr
Version: PHP
Version: Dadabase
Host: Linux, Windows, Mac or Web Hosting

**Comment by simnandez** [comment]
You can see and use the #2704

**Comment by rdoursenaud** [comment]
I think we have a pretty robust system now.
