### ISSUE TITLE
refactoring of statut to status not finished?

### ISSUE THREAD

**Issue by tmulzer** [Dolibarr/dolibarr#24811]
### Bug

Angefragte URL: /product/stock/list.php?restore_lastsearch_values=1
Referer: http://dolibarr.innovisionlab.de/product/stock/card.php?id=352
Menüverwaltung: eldy_menu.php

Module/Anwendungen: syslog, user, propal, knowledgemanagement, ficheinter, contrat, partnership, expedition, supplier_proposal, reception, incoterm, tax, product, stock, productbatch, projet, categorie, fckeditor, bookmark, ldap, accounting, workflow, agenda, bom, banque, barcode, commande, don, ecm, facture, fournisseur, mrp, opensurvey, resource, service, societe, ticket, variants
Datenbank Type Manager: pgsql
Letzter Fehlerhafter Datenbankzugriff: SELECT t.rowid, t.ref,t.lieu FROM llx_entrepot as t WHERE 1=1 AND t.entity IN (1) AND ((status = 1 AND entity IN (1))) ORDER BY t.ref ASC, t.lieu ASC
Rückgabewert des letzten fehlerhaften Datenbankzugriff: DB_ERROR_NOSUCHFIELD
Information zum letzten fehlerhaften Datenbankzugriff: ERROR: 42703: column "status" does not exist\nLINE 1: ...entrepot as t WHERE 1=1 AND t.entity IN (1) AND ((status = 1...\n ^\nHINT: Perhaps you meant to reference the column "t.statut".\nLOCATION: errorMissingColumn, parse_relation.c:3504

### Environment Version

17.0.1

### Environment PHP

7.4.28

### Environment Database

postgresql

### Environment URL(s)

/product/stock/list.php?restore_lastsearch_values=1

### Expected and actual behavior

Should print the header - especially the "fk_parent" column.
The field in the postgres-table is named "statut" (after migrating the database, I don't know how it's been named before).

### Steps to reproduce the behavior

updated today from 16.0.3 to 17.0.1 .. get the error message above, since then.

**Comment by tmulzer** [comment]
![Screenshot_20230518_222233](https://github.com/Dolibarr/dolibarr/assets/13216768/1bc25052-4537-4169-9f90-46c0e4673b3c)

**Comment by ksar-ksar** [comment]
Hello,

Have you any external module ?
Or can you try to re-upload all the PHP file of V17.0.1 ?

Strange to have "status" on PHP
