### ISSUE TITLE
Stock of products with lot number: getting a very small quantity that we can't pass to 0 stock

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#24816]
### Bug

In the page stock of a product, for a specific lot number, ze get a stock of -9.9746599868666e-17. We can't turn it to 0 in anyway (excepted accessing to the database).

/product/stock/product.php?id=263&save_lastsearch_values=1

The transactions for this lot number were few: some consumptions  with the GPAO and a tentative to turn to 0 the stock after constating that the physical stock is 0.

### Environment Version

17.0.0

### Environment OS

Linux on1 5.15.107-1-pve #1 SMP PVE 5.15.107-1 (2023-04-20T10:05Z) x86_64

### Environment Web server

Apache/2.4.56 (Debian)

### Environment PHP

7.4.33

### Environment Database

MySQL or MariaDB 5.5.5-10.5.19-MariaDB-0+deb11u2

### Environment URL(s)

/product/stock/product.php?id=263&save_lastsearch_values=1

### Expected and actual behavior

The stock should be have exactly 0.

In my opinion, it's missing a button to turn easily a stock to 0. (without be obliged to add the opposite value to the current stock)

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/3815422/467b83c1-8175-43d2-b6ac-10e3ad269940)

![image](https://github.com/Dolibarr/dolibarr/assets/3815422/1e80cba0-0e1a-418c-9658-44145414781d)

**Comment by ksar-ksar** [comment]
Hello,

Can you try the update to V17.0.2 ?

**Comment by syrinx75** [comment]
I've updated to v 17.0.2. The quantity in stock remains the same and I can't reset it.
