### ISSUE TITLE
Create milestones for dolibarr versions

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2482]
Milestones are a great way to keep issues organised.

I think we should have milestones for all future versions:
- 3.5.7
- 3.6.3
- 3.7.0
- 3.8.0

**Comment by rdoursenaud** [comment]
I propose that we use milestones to organise features, bug fixes and pull requests we want in a particular release.

Only Yodas (@eldy @simnandez) would be allowed to decide whether a particular feature or bug has to go in a milestone unless the issue is security related or critical — these issue automatically qualifies for milestone integration once verified.

Putting pull requests under milestones would allow for semi-automatic changelog generation just by looking at the milestone. GitHub API allows this to be automated.

This should help focusing on issues that needs fixing before a release and gather an estimate of the remaining work.

Now that 3.6.3 and 3.7.0 are released, I suggest creating the following:
- 3.5.7
- 3.6.4
- 3.7.1
- 3.8.0

Just in case, here's the [documentation](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/).

**Comment by simnandez** [comment]
I agree with Raphael, any objections?

**Comment by simnandez** [comment]
We could create a milestone "Next" to include issues in it that we do not have clear, which made for an upcoming version specifically

**Comment by rdoursenaud** [comment]
Can @Dolibarr/owners close the 3.7.0 milestone since the release is in the wild?

Other than that, the system's in a rather good shape.
