### ISSUE TITLE
option to hide the footer of tickets on the public interface

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#24834]
### Feature Request

Now the ticket module setup have an option to display or hide the logo of the company in the public interface.
Also will be great  to have an option to  display or hide the footer. 
This is necessary to be able to offer a white label looking urll of the ticket portal to the third parties that can use the public interface, and do not want to see the data of our company when they integrate out link in their websites.
Please kindly implement the option "**Display the footer of the company in the public interface**" as is detailed in the next screenshot:

![image](https://github.com/Dolibarr/dolibarr/assets/7486607/633beff6-6607-46f4-97cf-f8efec38ce8c)

This is the current apparience of the ticket public portal that will be great to improve enabling an option to hide the footer:

![image](https://github.com/Dolibarr/dolibarr/assets/7486607/63521e5c-28ae-43e3-bb77-0e157372f020)

### Suggested implementation
Add a new option in the setup of the tickets module, and implement the option

**Comment by codejx** [comment]
Hi. Is this published?
Can't find the mentioned option in 18.02

**Comment by edupulpillo** [comment]
![image](https://github.com/Dolibarr/dolibarr/assets/7486607/f3d9925a-affa-4841-b2fd-5cd655bc3f3f)

**Comment by codejx** [comment]
Not available...
<img width="416" alt="dolibarr" src="https://github.com/Dolibarr/dolibarr/assets/11404077/27ec77cb-c611-4795-af55-7d41edb43c36">

**Comment by edupulpillo** [comment]
The option is not released in the v18.0.3 by default. 
Maybe the commit was missed in the dolibarr version release?

You can aply by hand the changes of the merged commit [dcc0159](https://github.com/Dolibarr/dolibarr/commit/dcc01599d4b12682aecd1fa2a49ec4fafbaf6772) then you will have the option available.

**Comment by edupulpillo** [comment]
The option is not released yet in the v18.0.4 .
Maybe the commit was missed in the dolibarr version release?

You can aply by hand the changes of the merged commit [dcc0159](https://github.com/Dolibarr/dolibarr/commit/dcc01599d4b12682aecd1fa2a49ec4fafbaf6772) then you will have the option available.

**Comment by codejx** [comment]
Manually changing the mentioned files worked properly.
Thank your so much.
However the lang-files had already the correct version.
