### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by clicqueur2** [Dolibarr/dolibarr#24848]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 16.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 8.1.16
- **Database**:  5.7.42-log
- **URL(s)**: /htdocs/comm/propal/card.php?socid=898&action=create

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Report
- **Multicompany**: 16.0.1

Bonjour la communauté Dolibarr,

Je me permets de vous solliciter car je rencontre un problème assez préoccupant sur ma version Dolibarr 16.0.5. Je suis également sous PHP 8.

Depuis quelques jours, sans avoir installé quoi que ce soit de nouveau, je ne parviens plus à accéder aux propositions commerciales. Je ne peux ni accéder à la liste, ni valider une nouvelle proposition directement depuis le profil d'un client.

De plus, j'ai constaté que le module multi-sociétés génère un message d'erreur : "Échec de la vérification de version". Pourtant, je suis bien en version 16.0.1 pour ce module, ce qui est d'autant plus étrange.

Le fait de ne plus avoir accès aux propositions commerciales est particulièrement gênant dans mon activité, d'autant plus que c'est une fonctionnalité de base de Dolibarr.

Si quelqu'un a déjà rencontré ce problème ou si vous avez des pistes pour m'aider à résoudre cette situation, je serais très reconnaissant.

Merci d'avance pour votre aide et votre temps.

Cordialement,

**Comment by daraelmin** [comment]
Bonsoir,

Sauf erreur de ma part, la version 16 de dolibarr n'est pas entièrement compatible avec PHP 8. Il faudrait donc essayer en repassant à PHP 7.4.

Bonne soirée

**Comment by emheyarssi** [comment]
> # Instructions
> *This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*


Hi

For this kind of request please use the forum. https://www.dolibarr.org/forum.php

Please follow the template when you post here.

Thanks
