### ISSUE TITLE
List of Manufacturing Order ordered by descending date by default (instead of ascending date)

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#24852]
### Feature Request

To sort the list of Manufacturing Orders by descending date by default, instead of ascending date.

It's easier because we usually look for the most recent orders, instead of the first orders since Dolibarr is used in the company.

/mrp/mo_list.php?leftmenu=mo

### Suggested implementation

To sort the list of Manufacturing Orders by descending date by default.

==>
/mrp/mo_list.php?sortfield=t.date_creation&sortorder=desc&begin=&contextpage=molist

**Comment by priojk** [comment]
I don't think a feature request is required: you can configure sort orders under Home->Setup->Default sorting.

**Comment by syrinx75** [comment]
Thanks, it works well.
