### ISSUE TITLE
INVOICE_SHOW_SHIPPING_ADDRESS issue

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#24861]
### Feature Request

The new feature INVOICE_SHOW_SHIPPING_ADDRESS is a great thing, but at least here in France it is not a legal requirement to mention the delivery address on invoices when conducting B2B sales. This requirement is typically applicable when selling to consumers (B2C). Therefore, it would be beneficial to have a checkbox option on invoices, allowing users to choose whether or not to include the delivery address for each specific invoice.

For professional clients there can be multiple orders on one invoice and each order can be for a unique delivery adress.

**Comment by yledoare** [comment]
Hello, what is your need ?

In France shipping Address on invoices will be soon required for B2B
https://bpifrance-creation.fr/encyclopedie/gerer-piloter-lentreprise/piloter-gerer-son-entreprise/facturation-electronique  
_"l’adresse de livraison des biens si elle est différente de l’adresse du client ; "_
