### ISSUE TITLE
The notification module should be able to send an attachment if it is generated by an ODT template.

### ISSUE THREAD

**Issue by FlorentPoinsaut** [Dolibarr/dolibarr#24869]
### Feature Request

If a PDF is generated via an ODT template and transformed into a PDF, it will not be attached to an email notification even if the "joinfiles" field is at 1.

Indeed, when a PDF is generated via an ODT template, it suffixes the generated PDF with the name of the template preceded by the character `_`

Example for a supplier order:
- Name of the template: `example.odt`
- Ref of the supplier order: `SO290-1019`
=> Name of the PDF: `SO290-1019_example.pdf`

While the notification system is limited to search if `SO290-1019.pdf` exists.

### Suggested implementation

I wonder how to correct this.
In my humble opinion, it would be better to remove or make optional this suffix story when generating via ODT.

### Suggested steps

What do you think about it?

If you agree, I can take care of creating the fix pretty quickly.

**Comment by FlorentPoinsaut** [comment]
Hi @eldy 
Could you please tell me what do you think about this when you get a chance?

**Comment by eldy** [comment]
Adding a pdf on the main pdf generated (even if generated from an odt) will generate a lot of trouble. The main pdf must be the ref.odt or ref .pdf
Other alternative files will contains suffix or another name.
We must keep this rule to get an easy to find rule of the main file.
For extra information, a better place is the table llx_ecm_files.

**Comment by FlorentPoinsaut** [comment]
Thanks for your answer.
Okay, but how could we find a way to attach a file that has been generated by an ODT and transformed into a PDF?
