### ISSUE TITLE
Expedition: automatically, Dolibarr tries to deliver a negative quantity from a product with has a negative stock

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#24865]
### Bug

When we do an expedition of products with lot numbers, Dolibarr tries to deliver a negative quantity from a product which has a negative stock.

/expedition/card.php?action=create&shipping_method_id=&origin=commande&origin_id=1864&projectid=&entrepot_id=1

### Environment Version

17.0.0

### Environment URL(s)

/expedition/card.php?action=create&shipping_method_id=&origin=commande&origin_id=1864&projectid=&entrepot_id=1

### Expected and actual behavior

As the stock of this line is already negative, Dolibarr should deliver 0, there is no product in stock.

### Steps to reproduce the behaviour

To have a negative stock for one of the lot numbers listed for the product.

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/3815422/f5d4ab51-20eb-4083-8897-7b379c1daad4)

**Comment by ksar-ksar** [comment]
Hello,

You are using V7.0.0 => Upgrade to V7.0.5 is mandatory

Dolibarr foundation is following bugs of the 3 last stable releases, so V15 to V17
V7 is 4 years old, any reason not to upgrade to V17 ?

**Comment by syrinx75** [comment]
Sorry, it's in fact v 17.
