### ISSUE TITLE
BUG: Lost suggested update highlight 

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2487]
Version: develop

When upgrading from 3.5.2 to 3.8.0, suggested update choice is not highlighted as it was in past versions.

![captura de pantalla 2015-03-27 a las 12 05 02](https://cloud.githubusercontent.com/assets/168744/6866546/a4c04828-d479-11e4-95cb-a27f3503cf69.png)

**Comment by eldy** [comment]
Did you get also problem after upgradint it to 3.6 ?
Or is it only when coming from 3.5.2 ?

**Comment by marcosgdf** [comment]
It seems to have been fixed or to be a cache thing
