### ISSUE TITLE
Bug: Emailing - Recipients (advanced selection) 

### ISSUE THREAD

**Issue by jasch0825** [Dolibarr/dolibarr#24879]
# Bug
Wrong behaviour of "Type of targeted email"
If I use this filter see picture, then only contacts which are connected to a third-party will selected. I would expect, that all contacts without third-party will be selected. Does anyone know how to fix this?
![image](https://github.com/Dolibarr/dolibarr/assets/56758697/376c8499-f3bd-41f6-b299-338b00494c3e)

## Environment
- **Version**: 17.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: apache2handler 7.4.33
- **Database**:  5.5.5-10.5.18-MariaDB-0+deb11u1
- **URL(s)**: /erp/htdocs/comm/mailing/advtargetemailing.php?id=69

**Comment by ksar-ksar** [comment]
Hello,

I think it has been corrected in V17.0.2, can you check ?

**Comment by jasch0825** [comment]
Hi

The problem also exists in version 17.0.2.
