### ISSUE TITLE
Free text is under banking information on invoices.

### ISSUE THREAD

**Issue by finalbeta** [Dolibarr/dolibarr#24874]
### Bug

When you define free text for Invoices. 
And you define a bank account for the invoice. 
The free text is below the banking information: 
See screenshot
![image](https://github.com/Dolibarr/dolibarr/assets/22134261/7409ca34-88d5-40d4-ad7e-10bd7e96604b)

### Environment Version

16.0.3

### Environment OS

Debian 11

### Environment Web server

Apache

### Environment PHP

7.4.33

### Environment Database

MariaDB

### Environment URL(s)

/compta/facture/card.php?facid=

### Expected and actual behavior

The invoice footer should be below the banking information.

### Steps to reproduce the behavior

Add free text to invoices by changing the module settings.
Define a bank account and use the bank account on the invoice.

**Comment by ksar-ksar** [comment]
Hello,

What invoice model are you using ?

Try also to update to V16.0.5

**Comment by finalbeta** [comment]
Hi, I upgraded to V17.0.2, same result. 
I'm using crabe as a model for invoices (default, changed nothing).

**Comment by finalbeta** [comment]
I've had a customer that payed an invoice partially. And this gives the same result when recreating the invoice. 
The free text on invoices is above the extra info about the payment. 

I've done some cutting in the screenshot below to hide some information. But this is the invoice bottom right. 
Where you can see the free text running over the payment info.

![image](https://github.com/Dolibarr/dolibarr/assets/22134261/75708f04-f082-4ed8-beff-6b10b9220352)
