### ISSUE TITLE
Installation needs some php packages

### ISSUE THREAD

**Issue by ehsabd** [Dolibarr/dolibarr#24876]
I noticed that installation requires packages like `php-curl`,`php-mbstring`,`php-gd`, etc.. So it's good to add this in the README.md documentation for manual install. For example in ubuntu:
```
apt install php-curl php-gd php-mbstring php-xml php-intl php-zip php-imap
```

**Comment by Daviid-P** [comment]
I'd suggest putting the install commands in the error message in `/install/check.php`.

https://github.com/Dolibarr/dolibarr/blob/1c403537523f758b40ee4c1ac07ea68397490fb9/htdocs/install/check.php#L130-L137

That way PHP can check OS and present one install command or another.
