### ISSUE TITLE
Module: "POLL, SURVEY OR VOTE"

### ISSUE THREAD

**Issue by FrancoisDigitel** [Dolibarr/dolibarr#24878]
### Bug

I am having an issue with the poll tool as it is displaying %Europe/Luxembourg instead of the actual dates.

![8c3be0087d9c4176eabeb5e790d64a4878ea5e08](https://github.com/Dolibarr/dolibarr/assets/8442896/51eba333-4a82-4fc8-8b37-3160ce1c6e1c)

### Environment Version

17.0.1

### Environment OS

SMP Debian 4.19.269-1

### Environment Web server

apache 2.4.38-3+deb10u10

### Environment PHP

8.1.19

### Environment Database

MariaDB 10.3.38-MariaDB-0+deb10u1 - Debian 10

### Environment URL(s)

public/opensurvey/studs.php?sondage=n33mwtefrew936zu

### Expected and actual behavior

Normal date 

### Steps to reproduce the behavior

I have successfully installed Dolibarr and activated the poll module.

### Attached files

![8c3be0087d9c4176eabeb5e790d64a4878ea5e08](https://github.com/Dolibarr/dolibarr/assets/8442896/51eba333-4a82-4fc8-8b37-3160ce1c6e1c)

**Comment by ksar-ksar** [comment]
Hello,

Can't reproduce on V17.0.2 
![image](https://github.com/Dolibarr/dolibarr/assets/35605507/cb433e2a-1a62-41aa-b5c4-fbf67189f0d7)

May be due to update to V17.0.2 ?

**Comment by FrancoisDigitel** [comment]
will try update and update 👍
