### ISSUE TITLE
Regression: "Actions on invoice" not updated since 17.0.1 (or before?)

### ISSUE THREAD

**Issue by svewa** [Dolibarr/dolibarr#24890]
### Bug

since 17.0.1 (I believe) my invoices don't get actions any more. Before everything was shown in the bottom right corner. Sent as email. approved, payed etc. Now nothing new gets added there.

### Environment Version

17.0.1, 17.0.2

### Environment OS

Debian 11

### Environment Web server

Apache 2.4.51

### Environment PHP

7.4.28

### Environment Database

mariadb 10.5.12-0+deb11u1

### Environment URL(s)

/compta/facture/card.php

### Expected and actual behavior

New lines should be added for relevant actions, but nothing new is added. Lines added while it was working are still visible.

### Steps to reproduce the behavior

Do anything that should get logged, observe nothing being added in the actions box

### Attached files

![grafik](https://github.com/Dolibarr/dolibarr/assets/20936492/49a68b49-084a-46c0-961e-c946efd79ed9)
payed invoice with zero actions, was send as email, marked as payed etc.

**Comment by ksar-ksar** [comment]
Hello,

Can you check dolibarr and hosting logs ?

**Comment by svewa** [comment]
Hi,

I enabled dolibarr log, apache error log is empty, I send an email and collected the logs afterwards. The email was actually sent, nothing was added in the actions thing.

[apache.log](https://github.com/Dolibarr/dolibarr/files/11593900/apache.log)
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/11593901/dolibarr.log)

**Comment by svewa** [comment]
I was not aware that the actions are in a module, and this got deactivated (by update, error or most likely misclick by me). sorry & thanks for your time.
