### ISSUE TITLE
White screen when pressing preview of supplier payment pdf

### ISSUE THREAD

**Issue by sonikf** [Dolibarr/dolibarr#24908]
### Bug

This occurs only in php 8.0 and 8.1.

In php 7.4 it works as expected and preview pdf is generated

### Environment Version

17.0.2

### Environment OS

Debian 5.10.178-3 (2023-04-22) x86_64

### Environment Web server

Apache

### Environment PHP

php 8.0, php 8.1

### Environment Database

MySQL or MariaDB 5.5.5-10.5.19

### Environment URL(s)
admin/supplier_payment.php?action=specimen&module=standard

### Steps to reproduce the behavior

See attached screenshot

### Attached files

![v](https://github.com/Dolibarr/dolibarr/assets/93765174/de5da2d2-12df-46ed-abc2-3e4170d65c53)

**Comment by ksar-ksar** [comment]
Hello,

What does the hosting logs say ?

**Comment by sonikf** [comment]
Sorry it's a shared host with no access to logs...if you can't recreate it, feel free to close it.

**Comment by TiBz0u** [comment]
Hi,
I came from a 9 version and I have exactly the same problem. I cannot see any preview file from the configuration page of the module.

Once I'm on a invoice, if nothing is generated yet, an image is well shown. Once I generate (sponge or crabe), it's broken. Same for the PDF to download. Impossible to access it...

PHP 7.4 FPM
Dolibarr 17.0.2
Kr.

**Comment by sonikf** [comment]
Hi @TiBz0u 
You should open a new issue because it's a different problem in different code base.
Fyi invoice preview works for me in 17.0.2
