### ISSUE TITLE
Fails to create new user

### ISSUE THREAD

**Issue by faveurs9** [Dolibarr/dolibarr#24902]
### Bug

Fails to create a new user with no error message

### Environment Version

17.01

### Environment OS

Ubuntu 22.04

### Environment Web server

NGINX

### Environment PHP

8.1

### Environment Database

postgres 15

### Expected and actual behavior

error in NGINX PHP message: PHP Warning:  Undefined property: stdClass::$Mnttot

**Comment by ksar-ksar** [comment]
Hello,

Can you try to update to V17.0.2 ?

**Comment by faveurs9** [comment]
same issue

**Comment by ksar-ksar** [comment]
Hello,

Can you activate the Dolibarr log module, recreate the fault and send the log ?

**Comment by faveurs9** [comment]
Actually my mistake. update to V17.0.2 fixed it.
