### ISSUE TITLE
BUG: when emitting a payment

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2491]
the emitter is lost when recording a payment on 3.6.2 and 3.7 (sometimes it works, i guess it is linked to the ode of payment : cheque, deposit, withdrawal, bank transfer...)

Lors d'une saisie de règlement le champ émetteur ne se remplis plus automatiquement :
Est ce normal ? Dans les version précédentes c’était possible.

http://www.dolibarr.fr/forum/8-mise-a-jour/52755-perte-de-l-emetteur-dans-un-reglement

**Comment by eldy** [comment]
I can't reproduce pb on 3.7. The make of cheque is correctly filled when you choose payment by cheque.

**Comment by BebZ** [comment]
![image](https://cloud.githubusercontent.com/assets/3694135/6882230/e277b336-d57d-11e4-87be-c23b8822c507.png)

woah copy paste works with image clipper of windows (capture)

**Comment by BebZ** [comment]
with cheque and bank transfer its ok it works, but on with other payment modes, it doesn't 

Strange behaviour, dont you think ? 
it's not big problem, you can sort it as "not prioritary" if we can manage issues with some labels...

![image](https://cloud.githubusercontent.com/assets/3694135/6958670/78587734-d90f-11e4-8ac9-a02159225619.png)

**Comment by eldy** [comment]
This field is dedicated to store the name of who make the cheque (to generate cheque receipt), so i think it is standard behaviour to have this working only when payment mode is cheque.

**Comment by BebZ** [comment]
Ok, i'll explain it on the guy asking it on the forum, thanks Eldy ;) Close #2490
