### ISSUE TITLE
Broken group card and permissions pages

### ISSUE THREAD

**Issue by mc2contributor** [Dolibarr/dolibarr#24921]
### Bug

The `user/group/card.php?id=1` and `user/group/perms.php?id=1` pages are empty and result in error messages (the following is for card.php):

```
PHP Fatal error:  Uncaught Error: Call to undefined method UserGroup::getFullName() in /var/www/dolibarr/htdocs/core/class/html.form.class.php:9540
Stack trace:
#0 /var/www/dolibarr/htdocs/core/lib/functions.lib.php(2484): Form->showrefnav()
#1 /var/www/dolibarr/htdocs/user/group/perms.php(210): dol_banner_tab()
#2 {main}
  thrown in /var/www/dolibarr/htdocs/core/class/html.form.class.php on line 9540, referer: https://dolibarr.local/user/group/card.php?id=1&save_lastsearch_values=1
```

This was working in 17.0.2 before we upgraded to 18.0.0-beta.

### Environment Version

18

### Environment OS

Debian 11

### Environment Web server

apache2

### Environment PHP

8.2.6

### Environment Database

MariaDB 10.5.19

**Comment by goc1966** [comment]
Solución (ES): 
1. Abrir el archivo /dolibarr/htdocs/recruitment/class/recruitmentcandidature.class.php
2. A partir de la línea 677 esta la función "getFullName()"
3. Seleccionar hasta la línea 700 y copiar.
4. Abrir el archivo /dolibarr/htdocs/user/class/usergroup.class.php
5. Pegar dentro de las llaves de la clase "UserGroup"
6. Guardar y recargar.

_Solution (EN):
1. Open the file /dolibarr/htdocs/recruitment/class/recruitmentcandidature.class.php
2. From line 677 is the function "getFullName()"
3. Select up to line 700 and copy.
4. Open the file /dolibarr/htdocs/user/class/usergroup.class.php
5. Paste inside the braces of the "UserGroup" class
6. Save and reload._
