### ISSUE TITLE
Suplier commercial proposal-External user-Acces refused

### ISSUE THREAD

**Issue by N3miroff** [Dolibarr/dolibarr#24927]
### Bug

Dear All,

External user (with appropriate rules) show connection refused for show supplier proposal list (working correctly for new proposal)
For other modules this works correctly, below message (in French sorry).

Accès refusé.
Vous essayez d’accéder à une page, région ou fonctionnalité d’un module désactivé, ou sans être dans une session authentifiée, ou avec un utilisateur non autorisé.
Identifiant courant: XXXXXXXXX
Les permissions pour cet identifiant peuvent être attribuées par l’administrateur Dolibarr via le menu Accueil → Utilisateurs.Remarque : effacez les cookies de votre navigateur pour détruire les sessions existantes pour cette connexion.

Regards

### Environment Version

17.0.2

### Environment OS

Ubuntu Server 20.04

### Environment Web server

Apache

### Environment PHP

PHP8.1

### Environment Database

Postgresql

**Comment by AurelienBISOTTI** [comment]
Hello,
Can you make a screenshot of "supplier proposal list" and refusal + permissions of the user relative to suppliers ?

**Comment by Delthair** [comment]
I have tried on V17.0.2 and i do not reproduce the bug. 
the following rights were given : 
![Capture d’écran 2023-06-10 à 15 38 54](https://github.com/Dolibarr/dolibarr/assets/41671350/7e9a667f-cd1f-4824-affc-ebb85c672867)

**Comment by N3miroff** [comment]
Dear All,
Thanks for your concern regarding this topic.
I had updated again to 17.0.2 with done procedure again without success.
![230612_Screen autorisation](https://github.com/Dolibarr/dolibarr/assets/94848390/aed03b2a-c286-425c-9cb4-0320d7e4ae68)

![230612_Screen list](https://github.com/Dolibarr/dolibarr/assets/94848390/3eee9561-1e69-4c44-aef6-02de5da80ac7)
Attached print screen error when trying to get list of quote.
Best regards

**Comment by Delthair** [comment]
Can you confirm that the rights for seeing the product and services are on ? 
Could you post confirm that the user is linked with a company in Dolibarr ?

**Comment by N3miroff** [comment]
Hello,
Thanks for prompt support, product module was not installed first of all, I install it and give permission to external user for it without success then try to add test product and again identical error (cache purged as well to test).

Regarding user it is linked to tier indetified as supplier 
Regards
