### ISSUE TITLE
Two people of the same hierarchy can't approve each other their leave request

### ISSUE THREAD

**Issue by FraJH** [Dolibarr/dolibarr#24928]
### Bug

Hello,

In some environment, small companies, we don't have much levels of hierarchy and sometimes a member who is not the direct superior may have to valid a leave request from another coworker.

Currently, the approver has the notification but can't see / approve the leave request, see steps to reproduce below.

### Environment Version

17.0.0

### Expected and actual behavior

A user on the same hierarchy of the requester, should see the leave request when marked as approver.

### Steps to reproduce the behavior

Hello,

How to reproduce :

Take John, create a leave request, but instead of selecting the direct superior as approver, take someone at the same hierarchy.

Send for approval.

The approver, through his notification, is well updated of this new leave request to approve :

![image](https://github.com/Dolibarr/dolibarr/assets/135129302/6c4f03d6-021a-49d5-86c5-cec869be4dfe)

It gets incremented by one.

But, we can't see the new leave request to be approved or not in the listing :

![image](https://github.com/Dolibarr/dolibarr/assets/135129302/63e771f8-ea7e-4fa3-a204-727aa1b583ae)

**Comment by AurelienBISOTTI** [comment]
Reproducible in v18

![Capture d’écran du 2023-06-09 12-10-32](https://github.com/Dolibarr/dolibarr/assets/12530585/db9ecfd8-c71a-4a8f-b1ae-6569eeefcfbf)
![Capture d’écran du 2023-06-09 12-10-57](https://github.com/Dolibarr/dolibarr/assets/12530585/f33bb945-1464-495f-a193-b06a36c82158)

**Comment by AurelienBISOTTI** [comment]
Possibly not a bug : I fixed it by giving the correct permissions to the user
Does your user have necessary rights ?

![Capture d’écran du 2023-06-09 12-15-07](https://github.com/Dolibarr/dolibarr/assets/12530585/3509e72c-bfce-4e1b-8794-07f35390c807)
![Capture d’écran du 2023-06-09 12-14-56](https://github.com/Dolibarr/dolibarr/assets/12530585/41766ef9-4138-4bd7-851f-96383460579c)

**Comment by rlm6** [comment]
Hi!

The main issue here is that we can choose as validator, a user that cannot validate the request because he doesn't have the rigth to see the request (due to hierarchy). 

2 solutions for resolution:
-let user see request on which it's validator or
-don't let user be validator if he cannot see request (due to current rights)
