### ISSUE TITLE
Wrong currency symbol in product dropdown list

### ISSUE THREAD

**Issue by ronetix** [Dolibarr/dolibarr#24942]
### Bug

The currency symbol in the product dropdown list when add product into Proposal/Sales Order/Invoice, don't depend on the 'Price Level' configured in "Third Patry -> Customer -> Price Level".
The price value in the list is correct (depends on selected 'Price Level'), but not the currency symbol.

### Environment Version

all

### Environment OS

Ubuntu 22.04

### Environment Web server

Apache 2

### Environment PHP

8.1.2

### Environment Database

MariaDB 5.5.5-10.6.12

**Comment by AurelienBISOTTI** [comment]
Could you make two screenshots, one for the config and one where the problem occurs ?

**Comment by ronetix** [comment]
Screenshot 1: Multi-currency setup
Screenshot 2: Third-party setup: "Price Level 2 - USD"
Screenshot 3: Product selling price: Price Level 2 - 15 USD
Screenshot 4: Drop-down list with products - it shows 15 €, should be $15

![1](https://github.com/Dolibarr/dolibarr/assets/57989366/9ffebe73-18be-4a8a-8786-0ec6320418dc)
![2](https://github.com/Dolibarr/dolibarr/assets/57989366/d74adc19-8ced-492d-a6a6-c9fcbbb2cb9f)
![3](https://github.com/Dolibarr/dolibarr/assets/57989366/c3d68a27-e29a-4b82-b5ca-984d5aedc66a)
![4](https://github.com/Dolibarr/dolibarr/assets/57989366/a6a928d2-0fbb-4233-8701-acca83415084)

**Comment by EchoLoGeek** [comment]
The price level is not used for multi-currency, it's just different prices depending on a level.
You must edit the currency params on third party card for this, and configure your exchange rate
Exemple:
1 - I have a product A with 2 price levels: the first for all customers (10€), the second for my best customers (8€). 
2 - In multi-currency, I edit my exchanges rates (1€ = 1,5$ by example )
3 - I edit the currency to use with my Third-Party
4 - I choose the price-level I want to apply

This list depends on the price levels, but the currency used is that of your instance, not that of your client
