### ISSUE TITLE
Project event mail dont create after sending mail action

### ISSUE THREAD

**Issue by eoxia-izza** [Dolibarr/dolibarr#24945]
### Bug

No trace of the email sent in the project in the list of events

### Environment Version

16.0.3

### Environment OS

Windows 11

### Environment Web server

Linux

### Environment PHP

7.4.33

### Environment Database

MySQL or MariaDB 5.5.5-10.3.39-MariaDB

### Expected and actual behavior

I would like an event to be added

### Steps to reproduce the behavior

I wrote an email directly in the project and it was not added to the list of events.

**Comment by AurelienBISOTTI** [comment]
Not reproducible in v18
![Capture d’écran du 2023-06-09 12-03-56](https://github.com/Dolibarr/dolibarr/assets/12530585/2bbbc905-bad8-441f-96bf-8bf0ba77bb04)

**Comment by aspangaro** [comment]
Already fix in v17. Need to modify database. Not reportable in v16.

https://github.com/Dolibarr/dolibarr/commit/ea8759e627cef4cc15b50c9a2d7d9128e5c5f911
