### ISSUE TITLE
Displaying third-party donors in bank entries

### ISSUE THREAD

**Issue by Asso-eIDL** [Dolibarr/dolibarr#24946]
### Feature Request

Would it be possible to display the Third Parties linked to a bank entry created by a donation in the Third Parties/Users column of the list of bank entries?

### Use case

See: [https://www.dolibarr.fr/forum/t/liste-des-ecritures-bancaires-et-dons/35062](url)

**Comment by emheyarssi** [comment]
Please write your issue in english to catch more developers

**Comment by manu-p** [comment]
Same question!

Maybe another solution would be to add a third-party type such as donator / funder or whatever is not a customer/prospect/vendor and allow to reference this type of third-party in Donations?

**Comment by zahwyrix** [comment]
I'll make a note of it and deal with it later tonight!

**Comment by manu-p** [comment]
> Maybe another solution would be to add a third-party type such as donator / funder or whatever is not a customer/prospect/vendor and allow to reference this type of third-party in Donations?

Maybe this is a bit too much for a faster solution?

To return to the initial request, although these fields are not mandatory, the Third Parties/Users column could be filled with the **Company** field, and in case it is empty the concatenation of the **Last name** and **First name** of the donator?

**Comment by manu-p** [comment]
I've been investigating a bit, and I think I found a bug. If so, this issue should be converted to a bug, not a feature request as it is since created.

I found the admin can choose in Donations parameters to "Use the address of an existing third party as the address of the donor", which in my case at least was not activated.

So I activated the option and was glad to see I had to choose a third party from the existing list (or create a new one).

I then created a donation for an existing third party, followed the donation process til payment and went to the Bank Entries list to find the Third Party remains empty. :-(

**Comment by emheyarssi** [comment]
Could you please add a screen shot of the bank entries where you see the empty third party field. I'm not sure to understand what your problem is.

**Comment by manu-p** [comment]
Sure @emheyarssi! here it is:
![Capture d’écran du 2024-06-19 19-30-51](https://github.com/Dolibarr/dolibarr/assets/14906222/ad8fa289-872e-424f-b820-b29ec6be8df9)

**Comment by manu-p** [comment]
Just in case, you get to this page following **Banks | Cash** > **List entries**

**Comment by emheyarssi** [comment]
Correction until I make the PR:
```
diff --git a/htdocs/compta/bank/bankentries_list.php b/htdocs/compta/bank/bankentries_list.php
index a972d18257d..16a67f78bf4 100644
--- a/htdocs/compta/bank/bankentries_list.php
+++ b/htdocs/compta/bank/bankentries_list.php
@@ -1690,7 +1690,7 @@ if ($resql) {
                                        $type_link = 'payment_salary';
                                }
 
-                               if ($links[$key]['type'] == 'company') {
+                               if ($links[$key]['type'] == 'company' || $links[$key]['type'] == 'payment_donation') {
                                        $companylinked_id = $links[$key]['url_id'];
                                }
                                if ($links[$key]['type'] == 'user') {

```

**Comment by manu-p** [comment]
Thanks @emheyarssi 

Just gave it a try and the Third Party shown in the Bank Entries List is not the one I associated to the donation... 
The Third Party shown has id 2 while the donation was done by Third Party id 91.

2 is the donation id, I'd say since it's the second donation I tried on my testing config.

**Comment by emheyarssi** [comment]
Which version of Dolibarr you use?

**Comment by manu-p** [comment]
> Which version of Dolibarr you use?

19.0.2

fk_soc in llx_don is the third party id.

**Comment by emheyarssi** [comment]
This should now work as you expect.
Right now it has been only tested on version 20.0-beta.

Please on feed back
```
diff --git a/htdocs/compta/bank/bankentries_list.php b/htdocs/compta/bank/bankentries_list.php
index a972d18257d..aed446f0857 100644
--- a/htdocs/compta/bank/bankentries_list.php
+++ b/htdocs/compta/bank/bankentries_list.php
@@ -1310,7 +1310,6 @@ if ($resql) {
        while ($i < $imaxinloop) {
                $objp = $db->fetch_object($resql);
                $links = $bankaccountstatic->get_url($objp->rowid);
-
                // If we are in a situation where we need/can show balance, we calculate the start of balance
                if (!$balancecalculated && (!empty($arrayfields['balancebefore']['checked']) || !empty($arrayfields['balance']['checked'])) && ($mode_balance_ok || $search_conciliated === '0')) {
                        if (!$search_account) {
@@ -1680,6 +1679,7 @@ if ($resql) {
                        $companylinked_id = 0;
                        $userlinked_id = 0;
                        $type_link = "";
+                       $thirdstr = "";
 
                        //payment line type to define user display and user or company linked
                        foreach ($links as $key => $value) {
@@ -1689,6 +1689,16 @@ if ($resql) {
                                if ($links[$key]['type'] == 'payment_salary') {
                                        $type_link = 'payment_salary';
                                }
+                               if ($links[$key]['type'] == 'payment_donation') {
+                                       $paymentdonationstatic->fetch($links[$key]['url_id']);
+                                       $donstatic->fetch($paymentdonationstatic->fk_donation);
+                                       $companylinked_id = $donstatic->socid;
+                                       if(!$companylinked_id) {
+                                               $thirdstr = ($donstatic->societe !== "" ? 
+                                                                       $donstatic->societe : 
+                                                                       $donstatic->firstname." ".$donstatic->lastname);
+                                       }
+                               }
 
                                if ($links[$key]['type'] == 'company') {
                                        $companylinked_id = $links[$key]['url_id'];
@@ -1714,6 +1724,8 @@ if ($resql) {
                                        $conf->cache['user'][$userlinked_id] = $tmpuser;
                                }
                                print $tmpuser->getNomUrl(-1);
+                       } elseif($thirdstr) {
+                               print $thirdstr;
                        } else {
                                print '&nbsp;';
                        }
```

**Comment by manu-p** [comment]
And it works!

Thank you so much @emheyarssi, the third party who paid the donation is now displayed in the Bank Entries list.

**Comment by emheyarssi** [comment]
You're welcome!

Thanx for the feedback.
