### ISSUE TITLE
HRM Establishment 404 error 

### ISSUE THREAD

**Issue by tony-sar** [Dolibarr/dolibarr#24953]
### Bug

Missing setup.php and about.php in HRM module. 
in hrm section of dolibarr , I have setup tab and about tab that shows 404 error . those tabs pointing to 
htdocs/hrm/admin setup.php and about.php respectively but there are no files in the folder . 

### Environment Version

17.0.1

### Environment OS

Ubuntu

### Environment Web server

Apache2

### Environment PHP

8.1

### Environment Database

Mariadb

### Steps to reproduce the behavior

Setup / Modules  Application . click on Gear Icon of HRM module . 
Create Establishment 
Once created . There are 4 tabs . Establishment , Log , Setup, About. 
Setup and about producing 404 error.

**Comment by Hystepik** [comment]
Hello,
It works for me in last version of 17.0.2 can you test on this version

**Comment by tony-sar** [comment]
Hi . 
installed version 17.0.2 and still getting same 404 error for two tabs.
