### ISSUE TITLE
bug in version 17.0.2 in 

### ISSUE THREAD

**Issue by Pyhot** [Dolibarr/dolibarr#24950]
### Bug

Hello, 

I found a Bug in Dollibarr (at least) in the version 17.0.2. I don't try in previous version. I hope it can help ....

The ERROR is in /htdocs/product/stock/list.php?leftmenu=
(appears when you check option column 'Parent Wharehouse'

I have tried after a brand new clean install of Dolibarr (without datas import)
activate Product's Module, 
Go to Wharehouse / List 
check for column Parent Wharehouse
then following ERROR appears : 

Dolibarr: 17.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 8.1.16
Server: Apache
OS: Linux webd003.cluster021.gra.hosting.ovh.net 5.15.80-ovh-vps-grsec-zfs-classid #1 SMP Wed Nov 30 08:49:06 UTC 2022 x86_64
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15

Url sollicitée: /htdocs/product/stock/list.php?leftmenu=
Referer: ...... /htdocs/product/index.php?mainmenu=products&leftmenu=
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, syslog, product, expedition, notification, categorie, bookmark, fckeditor, workflow, incoterm, reception, supplier_proposal, projet, propal, stock, productbatch, agenda, barcode, cron, commande, ecm, facture, fournisseur, margin, printing, service, societe, banque, tax, bom, mrp, debugbar, export

Type gestionnaire de base de données: mysqli

Requête dernier accès en base en erreur: SELECT t.rowid, t.ref,t.lieu FROM llx_entrepot as t WHERE 1=1 AND t.entity IN (1) AND ((status = 1 AND entity IN (1))) ORDER BY t.ref ASC, t.lieu ASC
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD

Information sur le dernier accès en base en erreur: Unknown column 'status' in 'where clause'

Is the ERROR will be fixed ? 

Thanks for your help, Dolibarr is a great ERP with very good job made by the community !

**Comment by ksar-ksar** [comment]
Hello,

You have already reported this bug : #24877
