### ISSUE TITLE
Groups Detail in Users & Groups is empty page both Card and Permission on Dolibarr 18

### ISSUE THREAD

**Issue by nandorusrin** [Dolibarr/dolibarr#24975]
### Bug

Fatal error: Uncaught Error: Call to undefined method UserGroup::getFullName() in C:\laragon\www\erp\htdocs\core\class\html.form.class.php:9540 Stack trace: #0 C:\laragon\www\erp\htdocs\core\lib\functions.lib.php(2484): Form->showrefnav(Object(UserGroup), 'id', '<a href="/erp/h...', true, 'rowid', 'ref', '', '', 0, '<!-- No photo t...', '', '') #1 C:\laragon\www\erp\htdocs\user\group\card.php(333): dol_banner_tab(Object(UserGroup), 'id', '<a href="/erp/h...', true) #2 {main} thrown in C:\laragon\www\erp\htdocs\core\class\html.form.class.php on line 9540

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
