### ISSUE TITLE
Do not allow creating commercial documents with VAT if company has no country set

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2499]
Type: feature request

When we create a customer invoice, proposal, etc. that uses taxes, we will see a warning in objectline_create pointing that we have to complete the configuration first. It would be nice if we actually warn the user before creating it.

**Comment by braito4** [comment]
+1
I've that problem when i have clients from outside Europe.

**Comment by rdoursenaud** [comment]
Making the country field mandatory on third party creation could mitigate this problem in a simple way.
