### ISSUE TITLE
Unknown column 'h.block_if_negative' in 'field list'

### ISSUE THREAD

**Issue by yledoare** [Dolibarr/dolibarr#25008]
### Bug

From demo database, I wanted to add a new item for holidays, on admin/dict.php?id=28 

I have this error 

Dolibarr a détecté une erreur technique.
You use an experimental or develop level of features, so please do NOT report any bugs or vulnerability, except if problem is confirmed after moving option MAIN_FEATURES_LEVEL back to 0.
Ces informations peuvent être utiles à des fins de diagnostic (vous pouvez définir l'option $dolibarr_main_prod sur '1' pour masquer les informations sensibles):
Date: 20230608210514
Dolibarr: 18.0.0-beta - https://www.dolibarr.org
Niveau de fonctionnalités: 2
PHP: 7.3.33
Serveur: Apache/2.4.52 (Debian)
OS: Linux 1a1b4296915c 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0

Url sollicitée: /admin/dict.php?id=28
Referer: http://XXXXX/admin/dict.php?mainmenu=home
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, api, webservices, externalrss, scaninvoices, categorie, emailcollector, supplier_proposal, expedition, accounting, agenda, bom, knowledgemanagement, banque, barcode, projet, cron, commande, don, ecm, export, expensereport, import, facture, fournisseur, holiday, margin, loan, mrp, blockedlog, prelevement, opensurvey, printing, recruitment, productbatch, tax, contrat, stock, ficheinter, product, paypal, resource, salaries, service, propal, societe, stripe, ticket, hrm, takepos, variants, website, partnership, sellyoursaas, fckeditor, ftp, geoipmaxmind, dav, multicurrency, webhook, bookmark, adherent, concatpdf, reception, paymentbybanktransfer, incoterm, google, skype, gravatar, mailing, workflow, numberwords, notification, oauth, modulebuilder, socialnetworks
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT h.rowid as rowid, h.code, h.label, h.affect, h.delay, h.newbymonth, h.fk_country as country_id, c.code as country_code, c.label as country, h.block_if_negative, h.sortorder, h.active FROM llx_c_holiday_types as h LEFT JOIN llx_c_country as c ON h.fk_country=c.rowid WHERE 1 = 1 ORDER BY sortorder ASC, country ASC, code ASC LIMIT 1001
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'h.block_if_negative' in 'field list'

### Environment Version

18.0.0-beta

### Environment OS

linux

### Environment Web server

docker

**Comment by Hystepik** [comment]
Hello,
Try to call htdocs/install to migrate your database

**Comment by yledoare** [comment]
Fixed with https://github.com/Dolibarr/dolibarr/pull/25012
