### ISSUE TITLE
Add Visibility parameter in the setup of Public self-registration form in projects/leads

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#25044]
### Feature Request

Now the self registered leads are always created with visibility to everybody.
This is a problem, since all external users that have permissions to see only their own projects, also can see the new leads. 

### Suggested implementation

To fix it is necessary to be able to specify in the public self-registration form a Visibility parameter that allows to specify  wich user or group of users will attend the new leads created using the Public self-registration portal.
Also can be fixed adding the permission "everydody except external users" to the permissions system.

The Setup of the projects module could be similar than this screenshot as below
![image](https://github.com/Dolibarr/dolibarr/assets/7486607/0ebd752f-ce35-46a2-9bf7-04f03613e7ed)

**Comment by eldy** [comment]
Right, by default the property ->public is set to 1.
We must add the param in setup to choose "Tout le monde" (0), "Contacts assignés" (1)
