### ISSUE TITLE
Bug: Non-available thumbnails are shown when placing mouse over a link

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2505]
Version: develop

It happens everywhere.

![captura de pantalla 2015-03-30 a las 3 51 42](https://cloud.githubusercontent.com/assets/168744/6889141/520656e0-d690-11e4-9d04-5883f56dceed.png)

**Comment by frederic34** [comment]
What contains the field "photo" of user? can you add a photo and then remove it.
For me it never happen.

**Comment by marcosgdf** [comment]
Try with the bundled initdata

**Comment by frederic34** [comment]
bundled Initdata contain "01.jpg" as logo for SuperAdminName and you don't have this file, in this case nophoto is shown.

**Comment by marcosgdf** [comment]
Oh, sorry then.

**Comment by frederic34** [comment]
For the non existent logo:
https://github.com/Dolibarr/dolibarr/pull/2523
