### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Pyhot** [Dolibarr/dolibarr#25079]
Hello, 

We are working with Dolibarr since v5.0.4. It’s a very  good ERP and we like it. Congratulation to developers ! 

We have done all upgrades up to 17.0.2 but now, it is a big mess in our SQL (due to old External Modules with their specific tables and columns remaining everywhere).

So we would like to re-start from a clean install, and insert all our datas (customers, products, stock, GPAO, etc). 
Fresh  install is ready.

The question is : 

-> how to be sure to import all datas with all links, foreign keys, … to be sure nothing will break or be instable ? 
We tried several ways, but ...

Problems observed : 

1- some tables structures are very different from 5.0.4. to 17.0.2 (number, names and place of several columns) 

So when doing Backup from Dolibarr + import in all table in new SQL, this generate [error #1054 - Unknown column (…) in 'Field List'] !
 

2- when doing export from Dolibarr => import to Dolibarr, … it’s VERY difficult to map. Names / fields are too much different.

3- we also tried Export in TVS, but Import in TVS is not available… (Bug ?)

4- and if we go trough Restauration process, it will create the SAME tables as old version (corresponding to old uninstalled external modules, I guess )

So it will a great help if somebody could tell us : the safe  procedure to Insert all our datas in newly installed Dolibarr. 

Thanks in advance, 

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 17.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 8.1.16
- **Database**:  8.0.32

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Hello,

The only way is to try to remove as much as possible all the fields from the external module, then do the upgrade.
