### ISSUE TITLE
product price change in the order / invoice

### ISSUE THREAD

**Issue by michalhana99** [Dolibarr/dolibarr#25078]
### Bug

if I edit the price of the product with VAT in the order, an erroneous recalculation occurs on the line
The total amount is correct, but subsequently when generating the invoice, the wrong price is overwritten

### Environment Version

17.0.1, 17.0.2

### Environment OS

Windows 

### Environment Web server

IIS

### Steps to reproduce the behavior

Create an item in the order with a price of 250 excluding VAT
confirm
Subsequently, modify and adjust the price of the already entered item with VAT to 350 and confirm

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/60580110/9ca3d51d-b8fa-40db-afbe-3c24a410c138)

![image](https://github.com/Dolibarr/dolibarr/assets/60580110/69ff7b3b-b063-4ef4-ba92-f90d6c79263c)

**Comment by sonikf** [comment]
~~v. 17.0.2 works as expected for me.~~ What is the (z) in the vat ?

I can confirm this bug. it also applies to 18.0.0 beta
For clarity when trying to edit - update the U.P. (inc. tax) field  value the U.P. (net) field is updated instead, calculations are correct.

**Comment by michalhana99** [comment]
VAT is europe, price inc. tax
![image](https://github.com/Dolibarr/dolibarr/assets/60580110/f563d31f-b50a-4564-bf56-d216227aecf0)


**EDIT**
![image](https://github.com/Dolibarr/dolibarr/assets/60580110/c8ce7f87-5975-4066-ab1d-2f36c43d70c9)

![image](https://github.com/Dolibarr/dolibarr/assets/60580110/d0d63950-6869-4d58-9e5a-ad73b93f0b82)

**Comment by sonikf** [comment]
Can you post a screenshot of  your vat rates Dictionary.

**Comment by michalhana99** [comment]
![Screenshot_2023-06-14-14-27-03-807_com android chrome](https://github.com/Dolibarr/dolibarr/assets/60580110/69343449-f5a9-4b37-8bef-adb9ba8f881b)

**Comment by michalhana99** [comment]
![Uploading IMG_20230614_143013.jpg…]()

**Comment by michalhana99** [comment]
![IMG_20230614_143013](https://github.com/Dolibarr/dolibarr/assets/60580110/9e11ae1f-1e2a-48f4-9afa-56c3c1371723)

**Comment by michalhana99** [comment]
This problem was not fixed in version 18.0.3 or previous :-(

**Comment by manunord** [comment]
fixed in version 20

**Comment by Delthair** [comment]
> fixed in version 20
