### ISSUE TITLE
IMPORTANT : add at least dolibarr_main_instance_unique_id into backup

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#25093]
### Bug

Please add conf/conf.php file into backup or at least dolibarr_main_instance_unique_id value ...

**Comment by ksar-ksar** [comment]
Hello,

Can you explain a bit why ?

**Comment by rycks** [comment]
@ksar-ksar 
here is "the" problem:

![image](https://github.com/Dolibarr/dolibarr/assets/1468823/fea03b38-531b-4282-ac52-8b5a941ca2cc)


then if you store data into your database using dolEncrypt function and restore it on an other dolibarr but with an other value for dolibarr_main_instance_unique_id you can't be able to decrypt the data ...

and dolEncrypt is used to store sensible configurations data with keyword like

_KEY|_EXPORTKEY|_SECUREKEY|_SERVERKEY|_PASS|_PASSWORD|_PW|_PW_TICKET|_PW_EMAILING|_SECRET|_SECURITY_TOKEN|_WEB_TOKEN

So ... that is REALLY IMPORTANT if you don't want to looose hours after restoring a dolibarr database if you only have sql and no idea about conf/conf.php content !!!!!
