### ISSUE TITLE
Clone various payment

### ISSUE THREAD

**Issue by citananda** [Dolibarr/dolibarr#25096]
### Bug

On the [various payment details page](/compta/bank/various_payment/card.php?id=xx) when I click on clone, the debit/credit is not copied
If I save the payment without selecting debit or credit, the payment appears in the list of payments without amount in debit/credit columns

### Environment Version

17.0.2

**Comment by lamrani002** [comment]
hello, can you provide more info because I tried to reproduce your problem but it works for me if I specify whether it is credit or debit and the amount would appear in the right column.

**Comment by citananda** [comment]
As I said : "If I save the payment without selecting debit or credit"
So the problem occurs when I select neither debit or credit, it should not be possible to save because it is a required information

**Comment by citananda** [comment]
To be more precise, when I clone a various payment with a credit entry, the cloning popup opens correctly, and the entry direction is correctly set to credit.

However, if I clone a various payment with a debit entry, the cloning popup opens without selecting the entry direction (empty) => this is the first bug.

The second bug is that I can save the various payment without selecting debit ou crédit

**Comment by citananda** [comment]
This issue is fixed, you can close it
Christophe BOURGOIS
https://laxmi.digital/
