### ISSUE TITLE
Bug: Ref is not shown in the bubble that appears when the mouse is over an agenda link

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2509]
Version: develop

![captura de pantalla 2015-03-31 a las 10 07 53](https://cloud.githubusercontent.com/assets/168744/6914727/d688a97e-d78d-11e4-931a-8f7a7e02d6fb.png)
![captura de pantalla 2015-03-31 a las 10 07 59](https://cloud.githubusercontent.com/assets/168744/6914728/d69c8e4e-d78d-11e4-9bde-ee18b209043a.png)

**Comment by fappels** [comment]
Automatic event bubble also misses ref and shows html tags

![image](https://cloud.githubusercontent.com/assets/4573808/6915180/3c15bf80-d792-11e4-8ea9-6a92c176327f.png)

**Comment by frederic34** [comment]
For html tags:
https://github.com/Dolibarr/dolibarr/pull/2517

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/2523
