### ISSUE TITLE
Commandes validées+en cours

### ISSUE THREAD

**Issue by nagoz** [Dolibarr/dolibarr#25094]
Bonjour,

Avant la mise à jour 17, lorsque l'on cliquait sur les commandes dans le tableau de bord de l'accueil,
![image](https://github.com/Dolibarr/dolibarr/assets/6176810/28644c73-6ee7-4e30-aa40-bb95081cc492)
nous arrivions sur la liste des commandes "Validée + en cours".
Désormais, on arrive sur les commandes "Validée + encours + livrée".
Est ce possible de paramétrer le filtre par défaut ? ou de revenir en arrière sur cette fonctionnalité ?

Merci

**Comment by ksar-ksar** [comment]
Hello,

Can you write in English ?

**Comment by lamrani002** [comment]
hello, all you have to do is select your choice in the filtering system: Validated+in progress

**Comment by atm-maxime** [comment]
See #18600
