### ISSUE TITLE
PHP error message when loading company image

### ISSUE THREAD

**Issue by meowchine1** [Dolibarr/dolibarr#25103]
### Bug

System throws an error when loading the company logo. But logo is successfully loaded into the database. 

### Environment Version

18.0.0

### Environment OS

Windows 10

### Environment Web server

Apache 2.4.51

### Environment PHP

8.0.13

### Environment Database

MySQL 5.7.36

### Environment URL(s)

http://mydomain/dolibarr-develop/htdocs/admin/company.php?mainmenu=home

### Expected and actual behavior

**Expected**: Success report
**Actual**: php error message
![unnamed](https://github.com/Dolibarr/dolibarr/assets/56365201/4642865b-4268-4aa1-b889-9caf2bda092f)

### Steps to reproduce the behavior

1. move to main section
2. move Company/Organization section
3. upload logo (png, jpg, jpeg. Size <= 2048)
4. press save button

**Comment by ksar-ksar** [comment]
Hello,

Thanks for the report, but it's warning messages not error
Can be hidden with $dolibarr_main_prod=1 in conf/conf.php
