### ISSUE TITLE
Bug: Event Start and End Date

### ISSUE THREAD

**Issue by hannus07** [Dolibarr/dolibarr#2510]
Good day,

I am situated in South Africa (+2) and using v3.6.2 and would like to know why does my events dates year change from 2015 to 19xx when creating a event or task within the third party Agenda?

Regards
Hannu

**Comment by BebZ** [comment]
Can't reproduce on my 3.7
maybe can you write more infos on the steps
maybe check the date and time of your server ?

**Comment by hannus07** [comment]
Just to clarify, from the third party agenda this is when it happens but it works fine if I do create an event from the agenda on the dashboard and the date on the server is correct?

**Comment by hannus07** [comment]
![eventdate](https://cloud.githubusercontent.com/assets/11735250/6963407/5829d04a-d93f-11e4-82bb-e6fd8d607cd5.JPG)

**Comment by eldy** [comment]
What is your PHP version ?

**Comment by hannus07** [comment]
Hi Eldy,

It will be v5.3.2-1ubuntu4.28

**Comment by eldy** [comment]
This is very strange. Do you enter date using the calendar/mouse or using the keyboard ?

**Comment by hannus07** [comment]
both?

**Comment by marcosgdf** [comment]
Take a screenshot of the Info Dolibarr page to see how Dolibarr is processing the time

**Comment by hannus07** [comment]
![image](https://cloud.githubusercontent.com/assets/11735250/7110479/44d46322-e1b2-11e4-9acf-2da7a40db9c0.png)

**Comment by hannus07** [comment]
Problem solved, I have changed the language from South Africa to United Kingdom and now it is working.

**Comment by rdoursenaud** [comment]
What do languages has to do with date management?

Still sounds like a bug to me!
