### ISSUE TITLE
v17.0.2 - form setup: "yesno" type field (setAsYesNo) does not register in DB

### ISSUE THREAD

**Issue by adlmr** [Dolibarr/dolibarr#25104]
### Bug

In form setup, "yesno" type fields (setAsYesNo) do not register in DB.

### Environment Version

17.0.1 17.0.2

### Environment OS

Debian 4.19.282-1 (2023-04-29) x86_64

### Environment Web server

nginx/1.14.2

### Environment PHP

7.4.33

### Environment Database

5.5.5-10.3.38-MariaDB-0+deb10u1

### Steps to reproduce the behavior

Create a test module:
![image](https://github.com/Dolibarr/dolibarr/assets/521092/bece9dd7-2c02-4d10-93af-4dcca8b40e39)

Go to the setup:
![image](https://github.com/Dolibarr/dolibarr/assets/521092/774bc7d6-f73f-44da-aa48-c7e3a529a030)

Give a value to each variable :
![image](https://github.com/Dolibarr/dolibarr/assets/521092/427a4c89-def4-4c4b-b356-87d711959f7d)

All values are saved except PARAM 4 of type yesno:
![image](https://github.com/Dolibarr/dolibarr/assets/521092/bd599d88-0b48-4c6f-ad18-0c031de44e09)

The debug displays a DELETE for PARAM4 but no INSERT :

```sql
SELECT transkey, transvalue FROM llx_overwrite_trans where lang='fr_FR' OR lang IS NULL AND entity IN (0, 1) ORDER BY lang DESC0.16
SELECT m.rowid, m.type, m.module, m.fk_menu, m.fk_mainmenu, m.fk_leftmenu, m.url, m.titre, m.prefix, m.langs, m.perms, m.enabled, m.target, m.mainmenu, m.leftmenu, m.position FROM llx_menu as m WHERE m.entity IN (0,1) AND m.menu_handler IN ('eldy','all') AND m.usertype IN (0,2) ORDER BY m.position, m.rowid0.23
DELETE FROM llx_const WHERE name = 'NO_PARAM_JUST_TEXT' AND entity = 10.36
DELETE FROM llx_const WHERE name = 'TEST1701_MYPARAM1' AND entity = 10.31
INSERT INTO llx_const(name, value, type, visible, note, entity) VALUES ('TEST1701_MYPARAM1', 'mon param 1', 'chaine', 0, '', 1)0.26
DELETE FROM llx_const WHERE name = 'TEST1701_MYPARAM2' AND entity = 10.22
INSERT INTO llx_const(name, value, type, visible, note, entity) VALUES ('TEST1701_MYPARAM2', 'mon param 2', 'chaine', 0, '', 1)0.23
DELETE FROM llx_const WHERE name = 'TEST1701_MYPARAM3' AND entity = 10.21
INSERT INTO llx_const(name, value, type, visible, note, entity) VALUES ('TEST1701_MYPARAM3', '2', 'chaine', 0, '', 1)0.2
DELETE FROM llx_const WHERE name = 'TEST1701_MYPARAM4' AND entity = 10.24

-- AN 'INSERT' IS MISSING HERE FOR MYPARAM4 --

DELETE FROM llx_const WHERE name = 'TEST1701_MYPARAM5' AND entity = 10.24
INSERT INTO llx_const(name, value, type, visible, note, entity) VALUES ('TEST1701_MYPARAM5', '-1', 'chaine', 0, '', 1)
```

I see the same bug in 17.0.1 and 17.0.2.

**Comment by lamrani002** [comment]
hello, you don't need to click on modify to change the PARAM4 field, you just need to activate it directly, so that when you want to change the other fields, it is deactivated by default.

**Comment by adlmr** [comment]
> hello, you don't need to click on modify to change the PARAM4 field, you just need to activate it directly, so that when you want to change the other fields, it is deactivated by default.

Hmm why not, let's give it a try:

- Without clicking on the MODIFY button, I check the yesno switch, which is now YES
- I reload the page: the button is still YES.
- I click on MODIFY: the button is still YES.
- I click on SAVE: the button is now set to **NO** => this is no expected
=> this is because of
```sql
DELETE FROM llx_const WHERE name = 'TEST1701_MYPARAM4' AND entity = 10.24
-- AN 'INSERT' IS MISSING HERE FOR MYPARAM4 --
```

possible solutions:
- This may be due to bad behavior: The user shouldn't be able to activate this button without clicking on the EDIT button.
BUT I can see that this is an evolution: https://github.com/Dolibarr/dolibarr/pull/21673
=> make all entries editable without the MODIFY button and remove the button? (that's a lot of work)

- Add an INSERT to the yesno field that takes the state of the button?

- More globally : why does the MODIFY action does **DELETE and INSERT** and not **UPDATE**?

**Comment by Hystepik** [comment]
Hello,
as you can see with https://github.com/Dolibarr/dolibarr/pull/21673 the issue has been fixed
Can you please retry with the last version of this branch

**Comment by adlmr** [comment]
> Hello, as you can see with #21673 the issue has been fixed Can you please retry with the last version of this branch

My dev server is running 17.0.2. Which "last version of this branch" do you want me to test?

**Comment by Hystepik** [comment]
What I meant was that the last update of the version 17.0.2 the bug seems fixed because I cannot reproduce
