### ISSUE TITLE
empty line product when create sales order or invoice from a propal

### ISSUE THREAD

**Issue by said4020** [Dolibarr/dolibarr#25111]
### Bug

Hello, for the past few days I have not been able to create orders or invoices from a commercial proposal, the problem is that the products added to the proposal are not included in the order or invoice. a solution?

### Environment Version

17.0.2

### Environment OS

Linux slinux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64

### Environment Web server

Apache 

### Environment PHP

8.0

### Environment Database

MySQL or MariaDB 10.6.12-MariaDB-1:10.6.12+maria~ubu2204

### Attached files

![Screenshot 2023-06-15 at 14-12-13 D0007-23 - Fiche](https://github.com/Dolibarr/dolibarr/assets/122290651/20fdd123-bd85-45fd-bfb9-c9605ab15dee)

![Screenshot 2023-06-15 at 14-12-53 (PROV66) - Fiche](https://github.com/Dolibarr/dolibarr/assets/122290651/e81cfefb-6e9a-44c3-bf4b-700b935fdf12)

**Comment by anthonyvdberghe** [comment]
Hi,

having the same problem here. Disabling all the external modules does not resolve the issue. This problem has surfaced about a week ago.

As far as I can see in the debug bar there are no specific errors referencing to this problem.

A newer install I host doesn't seem to have this problem.

**Comment by said4020** [comment]
Hi,

what is your hosting company?

**Comment by anthonyvdberghe** [comment]
This one is hosted on One.com. The other one without issues at Combell. I'm planning to put a copy of the faulty version on Combell to see if it resolves the issues.

**Comment by said4020** [comment]
Ah ok me too is hosted on one.com, I think the problem comes from one.com, I have a colleague who has the same problem and his dolibarr is hosted on one.com too
