### ISSUE TITLE
Unable to use cancel action on form with mandatory fields defined in llx_default_values table

### ISSUE THREAD

**Issue by hansemschnokeloch** [Dolibarr/dolibarr#25127]
### Bug

If you set a field as mandatory on the /admin/defaultvalues.php page, you can't use the CANCEL button on the form without filling out the mandatory field.

Issue is due to the fact that the CANCEL button is a SUBMIT button with name set to cancel. So you have to submit the form if you want to cancel your action. And because the field has now the property "required", the browser will not allow you to submit the form.

Property required is set with the following JS code
https://github.com/Dolibarr/dolibarr/blob/128b31feccd9edc7c1087c55b9eba9e1800b2dad/htdocs/core/lib/functions.lib.php#L9834

### Environment Version

16, 17, 18

### Expected and actual behavior

Actual behavior : unable to use the cancel button without filling out user configured mandatory fields

Expected behavior : ability to use the cancel button without filling out the form

### Steps to reproduce the behavior

1. Define the field `accountancy_code_sell` as mandatory on url `product/card.php` on the admin page `/admin/defaultvalues.php`
2. Create a new product
3. Clic on cancel button

**Comment by oussamanhairech** [comment]
Hi, the bug seems to be already fixed.

**Comment by hansemschnokeloch** [comment]
HI, which PR fixed the bug ? I still have this bug.

**Comment by oussamanhairech** [comment]
I don't know which PR, it works fine for me in a fresh install 17.0.2

**Comment by hansemschnokeloch** [comment]
For me the bug isn't fixed. Tested on dolibarr 19.0.0-dev
See screenshot below, if you use the cancel button, you have to fill in custom defined mandatory fields.

![Annotate-a-local-image](https://github.com/Dolibarr/dolibarr/assets/792829/24f98344-3dc4-46b6-9b1d-2ab05379a9a6)

**Comment by oussamanhairech** [comment]
you are right, now I am able to reproduce the bug
