### ISSUE TITLE
Filter in Stocks at date broken

### ISSUE THREAD

**Issue by WebWalker3D** [Dolibarr/dolibarr#25128]
### Bug

When navigating to the stock at date, previous versions (prior to 17x) would be able to filter either by "Ref." or by "Label".  The current version (17.0.1) when you attempt to add a filter, it still shows all of the products

### Environment Version

17.0.1

### Environment OS

Ubuntu 22.04

### Environment Web server

Apache2 with Nginx SSL Termination

### Environment PHP

8.2.7

### Environment Database

Server version: 8.0.33-25 Percona Server (GPL), Release '25', Revision '60c9e2c5'

### Environment URL(s)

/product/stock/stockatdate.php

### Expected and actual behavior

Expected:  Content will only show based on the word in the filter

Actual:  The filter does not filter anything and shows entire list regardless

### Steps to reproduce the behavior

1. Navigate to the Stocks at date /product/stock/stockatdate.php
2. Apply a date, but not a product or warehouse, to get all products from all warehouses at the specified date
3. Add a word to filter by in either the "Ref." column or the "Label" column (I used "box" to only show my box stock)
4. Hit the search magnifying glass to the right to apply the filter
5. Nothing changes

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/136760393/314aa9b2-7a9c-45d8-a6a0-32ff698e5955)

**Comment by EchoLoGeek** [comment]
It seem to be fixed in the 17.0.2
#24569
