### ISSUE TITLE
Include local taxes in unit price ttc

### ISSUE THREAD

**Issue by Doggy987** [Dolibarr/dolibarr#25145]
Hello, I don't know if I'm doing it right, I managed to get the "PU_TTC" line in my invoices. 
Thing is when I enter a price in it, all the calculation are good except it doesn't include the local taxes. Those taxes are only calculated in Total_TTC.
Is there a way to get the local tax included in unit price?
![Capture d’écran 2023-06-17 080622](https://github.com/Dolibarr/dolibarr/assets/67211631/4f31c3c9-6ed0-44f6-bbbb-8bf06f296661)

**Comment by ksar-ksar** [comment]
Hello,

if you have PU_TTC means that you manage to make your own pdf template.
So then, you can add the tax2 * total_line_ttc/total_ttc no ?
