### ISSUE TITLE
Default values for extrafields does not work on lists

### ISSUE THREAD

**Issue by V-Py** [Dolibarr/dolibarr#25143]
### Bug

I'm trying to use the default search filters on one of my list, and it seems to not be working for the extrafields of the object, mainly because of this line `$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_')`

where the `getOptionalsFromPost()` function is using the `GETPOSTISSET()` function which doesn't check for values inside user->default_values unlike the `GETPOST()` function

Shall I do a PR updating the `getOptionalsFromPost` function with GETPOST instead of GETPOSTISSET (seems to work at least for the `type boolean` just tried in local) or is there a reason we're using the GETPOSTISSET function inside of it ? 

Thanks!

**Comment by V-Py** [comment]
I might just do the PR and it will be rejected if needed

**Comment by eldy** [comment]
Can you provide a small step by step action to do to reproduce easily one case of the bug you mention and you try to fix with your PR ?

**Comment by V-Py** [comment]
Yes sure, here is a screenshot displaying what I'm talking about : 

<img width="1283" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/59333024/d588dd09-6cf4-4046-96e0-a05554932999">

If I got on projet/list.php, it isn't filtered on my boolean extrafield by default. However, after the modifications done by my PR, it is indeed filtered on this extrafield, and only the projects with urgent = 1 are visible by default.

Hope it's clear!

**Comment by GregChant** [comment]
I also have the same problem, on an 18.01.
I searched for a long time before finding this post.
:-)
