### ISSUE TITLE
Clone User

### ISSUE THREAD

**Issue by simon1tan1** [Dolibarr/dolibarr#25151]
### Feature Request

We need to be able to clone a user. This makes setting permissions easier. 

### Use case

Add a user and their permissions. Cloning this user's permissions to create a new user will save a lot of time updating permissions.

### Suggested implementation

Copy all permissions from user to a hidden field, When saving user, use that hidden info to update permissions.

### Suggested steps

Clone user. Allow user to edit details. Save. Permissions from the cloning process will already be there.

**Comment by atm-maxime** [comment]
Hi ! Thanks for your feedback.
Did you try to use the user groups to set permissions only once and then add users in the same group to have the same permissions?
A cloning function is useful when a large part of the datas are the same, and in my opinion datas between 2 users are rarely common, except for the permissions which can be set by user groups.
