### ISSUE TITLE
Preffered shipping method (SOCIETE_ASK_FOR_SHIPPING_METHOD) broken by #24716

### ISSUE THREAD

**Issue by jobrien2001** [Dolibarr/dolibarr#25152]
### Bug

#24716

```$form->selectShippingMethod(((GETPOSTISSET('shipping_method_id')` && GETPOST('shipping_method_id', 'int') != 0) ? GETPOST('shipping_method_id') : $shipping_method_id), 'shipping_method_id', '', 1, '', 0, 'maxwidth200 widthcentpercentminusx');```

Should be > 0 not != 0 ??

I dont know php but this seems to fix it.

Looks like other fields may be affected by the same change?

### Environment Version

17.02

### Environment OS

win10

### Environment Web server

WAMP

### Environment PHP

7.4

### Environment Database

mariadb

### Steps to reproduce the behavior

-Set default shipping on third party
-Create order, shipping is not selected

**Comment by bos4711** [comment]
Where do you set default shipping on third party?

**Comment by jobrien2001** [comment]
> Where do you set default shipping on third party?

"Other setup", set SOCIETE_ASK_FOR_SHIPPING_METHOD to 1

You can find most vars in the docs.

**Comment by bos4711** [comment]
Works fine for me (v17.0.2 / PHP 7.0).

![2023-06-29_001507](https://github.com/Dolibarr/dolibarr/assets/11036018/6b1d1e9b-533d-43dd-97da-2fd633ff50eb)
![2023-06-29_001514](https://github.com/Dolibarr/dolibarr/assets/11036018/85f51f05-f3b4-4d91-836b-e86dc424f6a3)

**Comment by jobrien2001** [comment]
Thats odd, it doesnt work for me.  Im on php 7.4.  Are you using the sourceforge 17.02 release?

**Comment by bos4711** [comment]
Yes, we use the SF-release.

**Comment by bos4711** [comment]
Just tested this with PHP 8.0 / Doli 17.0.2 and it works fine there as well.
