### ISSUE TITLE
When ussvag caldav fromthunderbird, full days do not appera on the correct date

### ISSUE THREAD

**Issue by c-orazio** [Dolibarr/dolibarr#25164]
### Bug

We are using dolibarr 16.4 and caldav in thunderbird.
Normal meeting of few hours are displayed perfectly in thunderbird calendar
Full day event appear on day before in thundebird. for example a full day event of the 5th of May will appear on the 4th of may in thunderbird.
It was not the case with previous version, they were displayed properly..

**Comment by emheyarssi** [comment]
I guess you use an external module. If so please contact the developer of the module.
