### ISSUE TITLE
Reception of goods with serial numbers broken in v18-beta

### ISSUE THREAD

**Issue by priojk** [Dolibarr/dolibarr#25166]
### Bug

I just tried the regular process for reception of goods:

After creating the reception from the supplier order (product with unique serial number) and after entering the serial numbers I validated the reception but the new stock did not get recorded (no error message neither). 

No stock movement was created for this transaction.

I just checked: the process is working correctly with 17.0.2.

### Environment Version

v18-beta as of 2023-06-21

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case with the stable V18 ?

**Comment by priojk** [comment]
I just re-tested it and with the latest version of v18 on git it worked without issues.
