### ISSUE TITLE
TVA 20% à 0 lors des saisies de facture/commande

### ISSUE THREAD

**Issue by ArnaudFR67** [Dolibarr/dolibarr#25187]
# Instructions
Hi all.
When I enter invoices or orders, for products with TAV 20% the rate is 0 when I validate the product line.
Only 20% products are concerned.

# Bug
At the validation of the line the VAT rate is 0 instead of 20%
![image](https://github.com/Dolibarr/dolibarr/assets/81926163/5dbd6cd1-da15-4945-8053-6a1eb77684e2)
The purchase price is however well captured for this supplier
![image](https://github.com/Dolibarr/dolibarr/assets/81926163/84468169-10f1-4d7c-bf80-3eecc94766f2)

## Environment
- **Version**: 17.0.2
- **OS**: Linux
- **Web server**: nginx/1.20.1
- **PHP**: fpm-fcgi 7.4.30
- **Database**: MySQL or MariaDB 5.5.5-10.3.32-MariaDB
- **URL(s)**: /dolibarr/htdocs/fourn/facture/card.php?id=1614

## Expected and actual behavior
The invoicing or order line should automatically enter VAT at 20%
I am obliged to correct the lines after typing... Double entry/validation.

The error occurs only with 20% VAT

## Report
At each invoicing/ordering line including a product at 20% VAT
To correct the error I am forced to modify the line.

Is it a parameter or a bug?
Thank you for your help.

**Comment by emheyarssi** [comment]
Hi, to get a better reply please write you issue in English and for such question please ask better first on the forum before posting here.
Having said that, how did you configure your product? Have you set a TVA in the sale tab?

**Comment by ArnaudFR67** [comment]
Hello.

Thank you for your quick answer.

I have searched on the forum and did not find anything could help me .
I translated my request as suggested.

It is a web installation on my Synology NAS wich is reserved to Dolibarr only.
I did not change anything on my installation... and I do not change parameters during installation
I have this problem since V16.
I thought the update would fix the problem

Do I have to change a parameter?
Thank you for your help

**Comment by atm-maxime** [comment]
What are the country of your supplier and yours ?

**Comment by ArnaudFR67** [comment]
Hello.
For me and my supplier : all in France.
Same VAT rate.
This is the same with all suppliers, not only one...

**Comment by guiltekmdion** [comment]
Hi
We have the same problem around here since we upgrade in 18.0.
