### ISSUE TITLE
"select" type extra fields don't work on ODT documents

### ISSUE THREAD

**Issue by IvanBUL** [Dolibarr/dolibarr#2518]
Hi guys i have test on 3.6.2 and 3.5 extrafields on proposal are not working any ideas when they will be fix ?

**Comment by BebZ** [comment]
LABEL : more info 
need more infos on your problem

**Comment by IvanBUL** [comment]
i have created a extra filed on proposal Setup->Modules->Proposals afterwords setup on Proposal->complementary attributes i add new attribute with code "about" and values see attached file 
![capture](https://cloud.githubusercontent.com/assets/11728170/6951777/6fc0cf3e-d8c6-11e4-8191-0c3a1cd994f8.JPG)
, then i try to call this field in odt template with {object_options_about} and its not working

**Comment by BebZ** [comment]
Did you read closely http://wiki.dolibarr.org/index.php/Cr%C3%A9er_un_mod%C3%A8le_de_document_ODT
For complete list of available tags, see on user documentation about using ODT templates on wiki:
http://wiki.dolibarr.org/index.php/Create_an_ODT_document_template

**Comment by IvanBUL** [comment]
hi BebZ thanks for quick reply .I have read the instruction ,but its not working if i miss something please point it out to me i relay want to make this work.

**Comment by IvanBUL** [comment]
Hello BebZ i just wanted to ask you if u have any info on my problem or any ideas ?
i will appreciate any help

**Comment by BebZ** [comment]
i'm really sorry i didnt try to call extrafields yet on odt...
maybe you can try to see with the module that has been set free to open source recently.
CustomFields Pro and Prodcuts esay acces.
https://github.com/lrq3000/dolibarr_customfields

**Comment by IvanBUL** [comment]
hi BebZ in the past i have tried CustomFields and i have some issues with some warnings and stuff, i did not know that pro version is free now i will give it a try.
but plz try to call extrafields on odt just to be sure that i'm not making any mistake ,for me extrafields is far more clean way to make nessery changes.
10x for the update : )

**Comment by IvanBUL** [comment]
Hello i have tried custom fields again and same warnings appear ,i don't like them. 
i have tried extrafields on 3.7 and they still don't work on proposal.

**Comment by IvanBUL** [comment]
Hi @BebZ ,did you find some free time to try extra fields on your environment ?

**Comment by rdoursenaud** [comment]
Confirmed.
Simple extra fields (string, int) work properly but as soon as a select exists all the extra fields replacement in ODTs stop working.
I suspect an SQL issue.

**Comment by IvanBUL** [comment]
Hello @rdoursenaud thank you for your effort to try it ,i hope that soon we can have resolution to this problem it will be a really good if we can use this option : )
10x and awaiting for more update when possible

**Comment by IvanBUL** [comment]
Hi guys just t let you know in 3.7 this bug still exists

**Comment by IvanBUL** [comment]
Hello guys any update this i setback for me can anyone pls fix this

**Comment by IvanBUL** [comment]
Hi @rdoursenaud , @genezys and @asirinelli can guys someone fix this ,on 3.7.1 its not working too

**Comment by aconits** [comment]
Hi,
I can't reproduce the bug in 3.7.4
Probably it had fixed but i didn't find the commit
I tried in 3.9.2 and it's work too

@eldy I think this issue can be close

**Comment by eldy** [comment]
Seems fixed so i close

**Comment by IvanBUL** [comment]
Hi Guys i just have tested and it seams that works only with string list and other options still don't work

**Comment by IvanBUL** [comment]
i tested on 3.9.3

**Comment by DATUC** [comment]
This isue is not solve on v19.0.2
