### ISSUE TITLE
 dolibarr/htdocs/public/cron/cron_run_jobs.php line 136 wrong "...&& $line->dateend < $now)

### ISSUE THREAD

**Issue by javieralapps4up** [Dolibarr/dolibarr#2519]
I think must be "...&& $line->dateend > $now)"

**Comment by simnandez** [comment]
The job must be executed if dateend is less than now. Why do you think the opposite?

**Comment by javieralapps4up** [comment]
I thought that the dateend was the deadline to execute the task. Reading your response, I think I was in error. Now I think that I do not understand so there is that field.

If dateend is empty or does not have one date less than now, the work not be executed

**Comment by rdoursenaud** [comment]
Reopened (see #3281)

**Comment by javieralapps4up** [comment]
Not fixed, NEVER fixed.

**Comment by javieralapps4up** [comment]
Good job, rdoursenaud. Your closed  #3281 but this not reopened.

**Comment by javieralapps4up** [comment]
Thanks.

**Comment by rdoursenaud** [comment]
@javieralapps4up Yeah, sorry, shit happens… I'll leave your #3798 opened to prevent another fiasco…
