### ISSUE TITLE
Add MAIN_INFO_EEREX

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#25214]
### Feature Request

Hello 🙂

It could be usefull to add in main company information this number : "exportateur enregistré" registered exporter
As it done for MAIN_INFO_SIREN, MAIN_INFO_TVAINTRA...
The name of the constant could be : 
`MAIN_INFO_EEREX`

### Use case

Ad this information in the pdf footer
> Any operator established in the EU, manufacturer or trader of products originating in the EU exported to Canada, Japan, Vietnam and the United Kingdom or the countries of the Generalized Scheme of Preferences (only in the event of bilateral cumulation for countries of the Generalized Scheme of Preferences).

### Suggested implementation

Create the constant MAIN_INFO_EEREX and edit in admin/company.php

### Suggested steps

1. Create constant MAIN_INFO_EEREX

2. Edit admin/company.php
```php
// Registered exporter number
print '<tr class="oddeven"><td><label for="eerex">'.$langs->trans("eerex").'</label></td><td>';
print '<input name="eerex" id="eerex" class="minwidth200" value="'.dol_escape_htmltag(!empty($conf->global->MAIN_INFO_EEREX) ? $conf->global->MAIN_INFO_EEREX: '').'">';
print '</td></tr>';
```

3. Edit societe/class/societe.class.php 
```php
//setMysoc()
$this->eerex= empty($conf->global->MAIN_INFO_EEREX) ? '' : $conf->global->MAIN_INFO_EEREX;
```
5. Edit  core/lib/pdf.lib.php

```php
// Registered exporter number
	if (!empty($fromcompany->eerex)  && $fromcompany->eerex!= '') {
		$line4 .= ($line4 ? " - " : "").$outputlangs->transnoentities("eerex").": ".$outputlangs->convToOutputCharset($fromcompany->eerex);
	}
```

### More infos
https://www.douane.gouv.fr/demarche/deposer-une-demande-dexportateur-enregistre-ee-systeme-rex

Tks for reading

**Comment by ns-info90** [comment]
Why don't we start with extrafields at company level instead, so that we don't have to re-list at the end of the year ?

**Comment by dolibarr95** [comment]
Hello
@ns-info90 extrafield is a very good option !!
Could be 

> admin/company_extrafields.php

**Comment by dolibarr95** [comment]
Hello
@eldy can you please give advice?
Should we create an new constant or a new page extrafield?

**Comment by hansemschnokeloch** [comment]
Hi,
we currently have profid1 to profid5 as fields to store customisable company info.
Suggestion: add profid6 to profid10 fields, that should cover most of the requirements for every use case of Dolibarr

**Comment by dolibarr95** [comment]
@hansemschnokeloch it's a good option too!

**Comment by dolibarr95** [comment]
Hello
In my case
Just editing the file 
```
langs\xx_XX\companies.langs
```
prof id n°6
```
ProfId6XX=Id. prof. 6 (numéro EE)
```
Does the job.

@eldy what about creating new constants ?
MAIN_INFO_PROFID7 to MAIN_INFO_PROFID10
And/or edit the companies.lang with EE (exportateur enregistré)

_If we want more ProfId (7,8,9..) we have to edit the file pdf.lib.php too_

Tks for reading

**Comment by eldy** [comment]
profid1 to 6 are available to manage very usual fields that are specific to country.
It is not possible to manage all fields by extending profid, if we extend to 10 then we will need 20, then 30...

When we need more data as simple property of a thirdparty, the extrafields are currently designed for this.

If we need a specific business behaviour depending on the value of this field, that is enough generic for the world, adding a new field is a better solution.

**Comment by dolibarr95** [comment]
Hello @eldy 

Yes extrafields are the best solution !
So should we create the ```admin/company_extrafields.php``` file ?
As we have ```societe/admin/societe_extrafields.php```

With this solution, instead of modifying pdf.lib pdf_pagefoot() users will only have to use ```pdf_pagefoot hook```

Tks

**Comment by eldy** [comment]
> Hello @eldy 
> 
> Yes extrafields are the best solution !
> So should we create the ```admin/company_extrafields.php``` file ?
> As we have ```societe/admin/societe_extrafields.php```
> 
> With this solution, instead of modifying pdf.lib pdf_pagefoot() users will only have to use ```pdf_pagefoot hook```
> 
> Tks

Why adding a file ? Extrafields on thirdparties are already supported.

**Comment by dolibarr95** [comment]
So we should use extrafiled of ```societe/admin/societe_extrafields.php``` to manage extrafiled of ```admin/company.php``` ?

**Comment by dolibarr95** [comment]
So what about creating a new constant  (or else) to link : 
The main dolibarr company ```admin/company.php``` to a company ```societe/card.php?socid=x```
ex
societe/card.php?socid=800 is the card of the main company also described in admin/company.php

```MAIN_INFO_SOCIETE_FKSOC```
type int
value 800

This constant will be registered in ```admin/company.php```


Could be : 
```php
// Third party
	print '<tr class="oddeven">';
	print '<td>'.$langs->trans('Customer').'</td>';
	print '<td>';
	print img_picto('', 'company').$form->select_company($conf->global->MAIN_INFO_SOCIETE_FKSOC, 'MAIN_INFO_SOCIETE_FKSOC');
	print '</td>';
	print '</tr>'."\n";
```

**Comment by eldy** [comment]
What is the goal of the data MAIN_INFO_EEREX.
Storing a thirdparty ID. But then , when this data will be used ?
Only in the PDF comment, at the bottom ?

If this is just a legal information to add at bottom of PDF, why not adding this sentence into the "Legal mention" section into invoice PDF setup.

**Comment by dolibarr95** [comment]
Hello @eldy 

_Tks for this reply_
This number can be used in document as invoices (in pdf or other) and can be asked whe you book an expedition (depending of the country).
This number is important for export (for European countries)

**Comment by eldy** [comment]
> Hello @eldy
> 
> _Tks for this reply_ This number can be used in document as invoices (in pdf or other) and can be asked whe you book an expedition (depending of the country). This number is important for export (for European countries)

Do you need such a number for the managed company of for each thirdparty ?
Also can yu confirm is it just a number ? (so a string). It also seems that such a number exists only if a EORI number already exists ?

**Comment by dolibarr95** [comment]
Hello @eldy 

In my case only for the main company, but depending of the activty of each Dolibarr user (import/export..)  maybe for each thirdparty.
The EORI and the FFREX  are not the same. It contains only number(or letters)
In my case we have those mandatory informations :

- EORI : [numéro d’identification communautaire](https://www.douane.gouv.fr/service-en-ligne/connaitre-son-numero-didentification-communautaire-eori) 
- EE FFREX : [exportateur enregistré](https://www.douane.gouv.fr/demarche/deposer-une-demande-dexportateur-enregistre-ee-systeme-rex)
- EA : [bureau de douane](https://www.douane.gouv.fr/sites/default/files/bod/src/dana/da_annexes/F2_15-065_2.pdf)

Tks

**Comment by eldy** [comment]
> Hello @eldy
> 
> In my case only for the main company, but depending of the activty of each Dolibarr user (import/export..) maybe for each thirdparty. The EORI and the FFREX are not the same. It contains only number(or letters) In my case we have those mandatory informations :
> 
> * EORI : [numéro d’identification communautaire](https://www.douane.gouv.fr/service-en-ligne/connaitre-son-numero-didentification-communautaire-eori)
> * EE FFREX : [exportateur enregistré](https://www.douane.gouv.fr/demarche/deposer-une-demande-dexportateur-enregistre-ee-systeme-rex)
> * EA : [bureau de douane](https://www.douane.gouv.fr/sites/default/files/bod/src/dana/da_annexes/F2_15-065_2.pdf)
> 
> Tks

OK for the definion, but how and when this data need to be used in real life and in Dolibarr ?

**Comment by dolibarr95** [comment]
Hi @eldy 
In real case can be used in all "official" documents (orders, invoices, origin of products).
