### ISSUE TITLE
Missing TAG on tiers

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#25219]
### Feature Request

Missing TAG on tiers only

![image](https://github.com/Dolibarr/dolibarr/assets/3288514/0d79e8e2-aebd-49cf-94ae-75fcb6e59e7d)

**Comment by FHenry** [comment]
THIRDPARTY_CAN_HAVE_CUSTOMER_CATEGORY_EVEN_IF_NOT_CUSTOMER_PROSPECT ?

**Comment by lmag** [comment]
ADD conf : https://wiki.dolibarr.org/index.php?title=Setup_Other#Third_Parties_Module
