### ISSUE TITLE
PHP Warnings on multiple pages / actions

### ISSUE THREAD

**Issue by cngJo** [Dolibarr/dolibarr#25224]
### Bug

When e.g. adding a payment to a invoice, after saving the payment, I end up on `/compta/paiement.php` showing only the below PHP Warnings and not the usual UI.
```txt
Warning: Undefined property: TCPDI::$page_largeur in /[...]/_production/htdocs/core/lib/pdf.lib.php on line 1241

Warning: Undefined property: TCPDI::$margin_left in /[...]/_production/htdocs/core/lib/pdf.lib.php on line 1241

Warning: Undefined property: TCPDI::$margin_right in /[...]/_production/htdocs/core/lib/pdf.lib.php on line 1241

Warning: Cannot modify header information - headers already sent by (output started at /[...]/_production/htdocs/core/lib/pdf.lib.php:1241) in /[...]/_production/htdocs/compta/paiement.php on line 310
```

I experienced this on multiple actions in the "Invoice Creation" process. When creating / editing an invoice position, i get similar messaged rendered at the top of the `body` which messes with the UI.

Everything I did seems to have worked properly, apart from that the mentioned warnings got written to the PHP Output.

### Environment Version

17.0.2

### Environment Web server

Apache 2.4.57

### Environment PHP

8.1.18

### Expected and actual behavior

**Expected behavior**
No PHP Warnings when using Dolibarr

**Actual behavior**
PHP Warnings on different places mess with the UI

### Steps to reproduce the behavior

- Creating a new invoice
- Editing an invoice position
- Saving a payment for an invoice

### Attached files

- When creating a new Invoice
![create-invoice](https://github.com/Dolibarr/dolibarr/assets/17183555/05421384-285a-4d86-ae2a-6191a5121dfe)
- When creating a new invoice position
![create-invoice-position](https://github.com/Dolibarr/dolibarr/assets/17183555/c4c17e90-f0dc-4652-9c9e-5377106758d7)

**Comment by ksar-ksar** [comment]
Hello,

I know that it is not solving the issue, but you can hide this warnings by putting $dolibarr_main_prod=1 in conf/conf.php

**Comment by cngJo** [comment]
Hi

Thank you, that at least suppresses the warnings ;)

**Comment by daraelmin** [comment]
Hi,

Dolibarr v17 is not (fully) compatible with PHP 8.1. Use PHP 7 to avoid these warning and error.

cheers
