### ISSUE TITLE
Not able to uplad documents to donations 

### ISSUE THREAD

**Issue by hanneshier** [Dolibarr/dolibarr#25223]
### Bug

I want to upload a written receipt to a donation in the donations module, but I cannot view the uploaded file. I get the success message for the uploaded document, but when I want to view the file I get the following error message

`ErrorFileDoesNotExists: 1/Scanned Document 2022 002.pdf`

<img width="1726" alt="Screenshot 2023-06-28 at 20 51 06" src="https://github.com/Dolibarr/dolibarr/assets/11063798/d728b71b-6849-449e-b3db-0a238bdc64fb">

I use the https://github.com/tuxgasy/docker-dolibarr Docker install

### Environment Version

17.0.2

### Environment OS

Docker Container on Linux 3c459c7be176 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64

### Environment Web server

Apache

### Environment PHP

8.1.20

### Environment Database

MySQL or MariaDB 10.8.8-MariaDB-1:10.8.8+maria~ubu2204

### Environment URL(s)

/don/card.php?id=29&save_lastsearch_values=1

### Expected and actual behavior

Be able to view the file

### Steps to reproduce the behavior

Add a donation in the donations module, add a file (pdf), view the file

**Comment by ksar-ksar** [comment]
Hello,

What is the name of the file ?
if it contains "/" it is "normal"

**Comment by hanneshier** [comment]
I've tried several documents, also one just called "test.pdf", but withe the same behavior. I've just discovered that the number before the "/" in the error message corresponds to the id of the donation. So another error message looks like thie 
`ErrorFileDoesNotExists: 29/test.pdf`
