### ISSUE TITLE
Custom Module Related Objects

### ISSUE THREAD

**Issue by playcock** [Dolibarr/dolibarr#25236]
### Bug

I believe I have discovered a bug within the Custom Modules you can create with the Module Builder.

When I select a Related Object to Link the Custom Module card to, the card does not save the selection I made.

### Environment Version

16.0.5

### Environment OS

ubuntu0.18.04.17

### Environment PHP

7.2.24

### Environment Database

10.1.48-MariaDB

### Steps to reproduce the behavior

Scroll down to Related Objects and click "Link to"
![image](https://github.com/Dolibarr/dolibarr/assets/9416592/5fd8dda1-7c86-4628-b70f-9637ce2d70f9)

Select one and click the LINK button
![image](https://github.com/Dolibarr/dolibarr/assets/9416592/0fc33201-fec5-4e51-9f9c-f6f27f9a452f)

The page reloads and the object is not linked
![image](https://github.com/Dolibarr/dolibarr/assets/9416592/767dc6c4-15ba-4c38-b5b8-6d8ded2196ba)

I also created a Sales Order for the third party and tried to link to the Sales Order and it doesn’t link.

**Comment by priojk** [comment]
Can confirm the same bug in v18-beta but did not yet have time to analyse the root cause.

**Comment by playcock** [comment]
@priojk 

Would you guys consider this reported bug also relevant to this one?

[Bug: New module document does not delete document #23845 ](https://github.com/Dolibarr/dolibarr/issues/23845)
