### ISSUE TITLE
Implement protection against bruteforce

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2524]
I've seen some utilities that take advantage of bruteforce to guess the password of users. Because Dolibarr doesn't provide any protection against those attacks, It would be nice if we tracked those errors and forbid them to login for X minutes.

It is important to have it enabled by default.

**Comment by rdoursenaud** [comment]
There is one available protection: the captcha. It is not enabled by default but should do the trick pretty well.

**Comment by BebZ** [comment]
Yes, I didn't notice it too, it's in /admin/security_other.php

**Comment by simnandez** [comment]
Possibles ways to implement:
-Blocking IP for X minutes
-Deactivate user after X failed logins

**Comment by BebZ** [comment]
@darkjeff ;)

**Comment by frederic34** [comment]
On linux system, it's possible to use fail2ban with analyse of dolibarr.log

**Comment by marcosgdf** [comment]
? It just compares $_POST['code'] to $_SESSION['dol_antispam_value']. It is not exposed.

BTW Bundled captcha code provides very little protection. It can be easily read with OCR.

**Comment by frederic34** [comment]
Oh I understand my error, $_SESSION are only on the server....

**Comment by eldy** [comment]
There is also a feature to limit brute force. When a login/pass is tried, if it fails, dolibarr will return result after a 1 or 2 seconds delay. This make brute force very slow because attacker need to wait, to know if result is ok or not. The attacker must run a very high number of thread if he want to make enough tests to have brute force a chance to find, and apache will restrict this with its thread limit per ip.

**Comment by rdoursenaud** [comment]
If that's the case, the implementation can be improved by making the delay exponential with the number of failed login attempts.
:+1:

**Comment by marcosgdf** [comment]
That would be great.

**Comment by Darkjeff** [comment]
Use failtoban on server side

captcha isn't enough

2015-05-04 15:33 GMT+02:00 Marcos García notifications@github.com:

> That would be great.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/issues/2524#issuecomment-98705267.

## 

_Olivier Geffroy__Consultant Informatique_

_Jeffinfo a 15 ans cette année
http://www.jeffinfo.com/ma-petite-entreprise-15-ans/-------------------------------------_

_Jeffinfo SARL__295 rue d'aire *_59660 Merville*

_jeff@jeffinfo.com jeff@jeffinfo.comGsm : 0608632740__Skype : darkj3ff_

**Comment by eldy** [comment]
OK to increase delay with exponential time for next tries. 
But this is not always usefull because a hacker will not keep session and may use different ip. Current delay should be enough.

**Comment by eldy** [comment]
Fail2ban seems definetely the best solution.
But we shoud save failed login events into a dedicated log so fail2ban can analyse the file.

**Comment by Darkjeff** [comment]
I agree 
and give the information to add in etc/fail2ban/jail.local
and the filter : dolibarr.conf (in etc/fail2ban/filder.d/ )

**Comment by eldy** [comment]
Failed login are now visible into the log file with log level = Notice or higher.
So fail2ban can be used now.

**Comment by c-orazio** [comment]
Please can you elaborate on how to configure fail to ban?
