### ISSUE TITLE
Bad BOM cost calculation

### ISSUE THREAD

**Issue by fgarciapatino** [Dolibarr/dolibarr#25254]
### Bug

Cost of BOM are not well calculated when nesting products

### Environment Version

17.0.2

### Environment OS

Linux 3.10.0-1160.31.1

### Environment Web server

Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.21

### Environment PHP

7.4.33

### Environment Database

5.5.5-10.2.39-MariaDB

### Expected and actual behavior

Expected: calculate cost of BOM based on real costs
Actual: there is a nonsense factor applied

### Steps to reproduce the behavior

0. Create a raw materials product catalog
1. Create a BOM for a product composed with the two raw material products
![image](https://github.com/Dolibarr/dolibarr/assets/4846366/95167758-8237-4879-9290-01b75358bd50)
Cost defined at BOM for a unit of the product is 1,88€
3. Create a MO from the created BOM for 1000 units 
5. See the cost price

**Comment by eldy** [comment]
Can you provide a screenshot of the wrong result you have ?
