### ISSUE TITLE
Add a third status to time spent: "processed"

### ISSUE THREAD

**Issue by isamuse2** [Dolibarr/dolibarr#25268]
### Feature Request

Timespent, for billable projets, has currently two status: billed: yes or no.

I may occur for many different reasons that timespent may not be billed. I would be helpful that Dolibarr allows to identify such timespent with a third statuts, that may be named "processed".

"Processed" would identify time that will never be billed although the project is billable.

Without this third status, timespend remain with the statuts "Not invoiced" which apply to time that will be invoiced, thus creating confusion.

### Use case

They are several user cases for this "processed" statuts

1. in circumstances where the proposal provided that timespent should be caped to a certain level. If the supplier exceed this level of timespent, then excessive time spent will not be invoiced. 
2.  the supplier decides that the time spent on the project is excessive and decides not to invoice this excessive timespent (ift would also be helpful to be able to split a timespent into billable and not billable timespent)
3. the project includes tasks that are not invoiceable, like administrative tasks relating to the project

### Suggested implementation

On the page projet/tasks/time.php:

- add in the column "billed" a third status "treated"

![image](https://github.com/Dolibarr/dolibarr/assets/51233081/95b7c178-4a06-4db7-88d4-d6665ba641d9)

- allow the mass action "mark as treated" when several timespent are selected.
- allow to filter time spend with this third status "treated"

**Comment by rycks** [comment]
Hello all,
i spent some hours on that idea / question / feature request ...

there is no "status" field on database for llx_projet_task_time and that is the reason why there is (for the moment) only "invoiced yes / no" filter
