### ISSUE TITLE
Delete Donation Button not working

### ISSUE THREAD

**Issue by hanneshier** [Dolibarr/dolibarr#25314]
### Bug

The delete Button for donations is greyed and not working. If a manually add "action=delete" to the url, the donation can be removed.

### Environment Version

17.0.2

### Environment OS

Docker Linux 3c459c7be176 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64

### Environment Web server

Apache

### Environment PHP

Ok 8.1.20

### Environment Database

MySQL or MariaDB 10.8.8-MariaDB-1:10.8.8+maria~ubu2204

### Environment URL(s)

/societe/card.php?socid=96&save_lastsearch_values=1

### Expected and actual behavior

Expected: be able to delete a donation via the UI with the delete button

Actual: deletion is only possible by changing the url

### Steps to reproduce the behavior

Activate Unalterable Archives
Set INVOICE_CAN_ALWAYS_BE_REMOVED=1

Create a donation, remove the payment, try to delete the donation with the delete button.

### Attached files

<img width="1330" alt="Screenshot 2023-07-09 at 12 39 37" src="https://github.com/Dolibarr/dolibarr/assets/11063798/5087070f-1e67-42c5-8a4d-46c588681bc5">

**Comment by lamrani002** [comment]
Hi, i tried to reproduce the same behavior, for delete a donation you should delete all payments before, and after that a new button will appear where you can class it "drop out". And then you can delete donation properly.

**Comment by eldy** [comment]
We must add a title="xxxx" with xxx = message to say that deletion is not possible because there is at least 1 payment.
