### ISSUE TITLE
Extrafield of thirdparty deleted during editing if visibility = 5

### ISSUE THREAD

**Issue by nat-itopie** [Dolibarr/dolibarr#25330]
### Bug

Hello

When the visibility value of a thirdparty extrafield is set to "5" (= Visible on read lists and forms (not for creation or modification), the value is deleted when a thirdparty is edited.

If the visibility value is "0", the extrafield value is retained.
And if the visibility value is an expression, the value is also overwritten, for example: `('edit' == $action ) ? 0 : 1`

I've tested this on contact and member extrafields and the value is retained when you edit the object with a visibility of "0" or "5" or the expression.

### Environment Version

16.0.3 + 16.0.4 + 17.0.2

### Environment OS

Ubuntu 20.04 + Debian 4.9.210

### Environment Web server

Apache 2.4.41 + Apache 2.4.51

### Environment PHP

7.4.3

### Environment Database

MySQL  8.0.33 + MariaDB : 10.4 

### Expected and actual behavior

If a value exists for the extrafield of a thirdparty, it should not be overwritten with the default value when the extrafield is not displayed by visibility = 5.

### Steps to reproduce the behavior

- Create a varchar thirdparty extrafield and set visibility to 5.
- In the main view of the thirdparty, modify the value of the additional field (edit_extras) to give it a value.
- Switch to edit mode and save: the value is deleted.

**Comment by atm-maxime** [comment]
Hi !
I tried to reproduce in 16.0.5, but when I create a thirdparty extrafield with visibility = 5, the field is not editable at all on the main view. So how do you modify the value ?

**Comment by nat-itopie** [comment]
Hello Maxime,

We don't, they are updated via triggers (companyCreate and companyModify) - and the values are visible on records and lists.

On other Dolibarr elements, extrafields with visibility 5 are not deleted when the element is edited; this only happens on thirdparties.

Have a nice evening

**Comment by nat-itopie** [comment]
Resolved in v18.04.
