### ISSUE TITLE
Bug: unable to create an event in the agenda from thunderbird

### ISSUE THREAD

**Issue by c-orazio** [Dolibarr/dolibarr#25345]
# Bug
I have an agenda under thunderbird connected to dolibarr via a link of this type : 
https://dolibarr.mondomainne.com/public/agenda/agendaexport.php?format=ical&type=event&exportkey=XXXXXXX&notactiontype=systemauto&logint=cot_al
## Environment
- **Version**: 16.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: apache2handler 7.4.3-4ubuntu2.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.38-MariaDB-0ubuntu0.20.04.1
- **URL(s)**: /index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
I would expect that when I create an event in thunderbird, it appears in the agenda under dolibarr. But it is not the case. 
The events created in dolibarr appear in thunderbird, so it is a one way process, no a two ways.

## Steps to reproduce the behavior
create a remote access from thunderbird to a dolibarr agenda
try to insert a new event from thunderbird.

**Comment by ksar-ksar** [comment]
Hello,

Yes for now it's one way
