### ISSUE TITLE
Show company logo from link instead of a file

### ISSUE THREAD

**Issue by elpreto** [Dolibarr/dolibarr#25341]
### Feature Request

Currently, while creating a new Customer, Prospect, Vendor or Partner, if you want to add a logo, you have to upload an image, which is stored in the server and it has to be saved to recover later in case of an upgrade.

By using a link, we save the disk space and we remove the need of having to restore the image after an upgrade.

=D

### Suggested implementation

Add a link option, keeping the current upload image option

**Comment by ksar-ksar** [comment]
Hello,

But then you need to download it each time you create a document.
Not sure it's a good idea....

**Comment by elpreto** [comment]
Thank you for the quick reply.

Ok, maybe then use the link to add it the first time, and then save it?
It makes it easier for user, so you don't need to download, you could even use linkedin link to get the logo from. Some other ERPs are doing that way and it makes a lot easier for ens users.

Normally, if I have to go and download the photo, then put a name to it to recognize it later and then go and upload the photo to Dolibarr, I would probably keep the Company without a logo.

**Comment by elpreto** [comment]
I was checking how Odoo does it to have a reference, and it takes it from online sources. Would that be an option?

When you start typing the company name, it suggest some companies, and if you pick one, it fills most of the company data, including the logo, so I would assume it's taking in from LinkedIn
