### ISSUE TITLE
Bug: Untranslated string in "Linked objects" page of a project

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2535]
Version: 3.6.2
Page: /projet/element.php?id=3

![captura de pantalla 2015-04-03 a las 4 07 24](https://cloud.githubusercontent.com/assets/168744/6977114/fa961b6e-d9b6-11e4-8469-95433667ac9c.png)

**Comment by eldy** [comment]
Fix merged
