### ISSUE TITLE
Product Page Stock Tab - Correct Stock feature is not working

### ISSUE THREAD

**Issue by decentmanni** [Dolibarr/dolibarr#25367]
### Bug

Product Page Stock Tab - Correct Stock feature is not working

it is asking for put number of units....but in number of units feild there is a drop down list of add / delete. 

and add delete feild is missing from this correct stock option

PL fix this bug.

Manish Kumar

### Environment Version

Dolibarr current version : 17.0.2

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/139702134/6d8e903a-cadf-4a7a-be74-78891949295e)

**Comment by lamrani002** [comment]
Hello, the input field for number of units is just near the dropdown and it's required.
![s](https://github.com/Dolibarr/dolibarr/assets/10623583/6f1845d5-9d0c-42c0-94b8-4f71ab40855c)
