### ISSUE TITLE
Forms Style of Radiobuttons & Checkboxes

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#25362]
### Feature Request

Since Dolbarr 17 radiobuttons and checkboxes in forms have a new display style.
Now you must first go to the selection line and can only then see the options / texts for it.

Request:
An Option to choose old forms style.

Use Case:
This is not always practical or desirable for legal reasons:
Sometime you want to show it on screen like on paper. So it is better to 
display all options in a special order and not as a selectable list like as tags.
If you make a radiobutton for consent to GPDR - the legal text must always be displayed at first  - not only after selection.

**Comment by eldy** [comment]
I don't understand the request.
What do you mean with selectbox has changed ?
Can you make a screenshot?
