### ISSUE TITLE
Default customer payment terms not taken when creating an invoice

### ISSUE THREAD

**Issue by mokacit** [Dolibarr/dolibarr#25361]
### Bug

The default payment terms, method and Banck Account values set for the customer are not taken when I create an invoice and select the customer from the dropdown list.

### Environment Version

17.0.2

### Environment OS

Apache

### Environment PHP

8.1.21

### Environment Database

MySQL or MariaDB 10.5.19-MariaDB-0+deb11u2

### Environment URL(s)

/compta/facture/card.php?action=create&leftmenu=

### Expected and actual behavior

Payment Terms, Payment Method and Bank Account should be set in the form according to the values specified in the Customer card.

### Steps to reproduce the behavior

Create a customer and set the Payment Terms, Payment Method and Bank Account
Click on New Invoce within the menu "Billing | Payment menu/Customer invoices/"
Select a third party from the drop down menu.

### Attached files

Default values are taken if I comment the lines 3221 and 3222 of /compta/facture/card.php and add the lines of code taken from a previous version of dolibarr as follows:

					// jQuery("#formtocreateaction").val("create");
					// jQuery("#formtocreate").submit();
					var socid = $(this).val();
			                var fac_rec = $(\'#fac_rec\').val();
        			        window.location.href = "'.$_SERVER["PHP_SELF"].'?action=create&socid="+socid+"&fac_rec="+fac_rec;

**Comment by mokacit** [comment]
Thanks, it works.
Perhaps the same approach could be used for 
/comm/propal/card.php
/commande/card.php
/fourn/commande/card.php
all of which suffer from the same problem that is reported for the creation of a new invoice.

**Comment by mokacit** [comment]
The proposed fix introduces an issue when creating the invoice from an order. In this case, the payment fields defined in the order are not taken in the invoice.

**Comment by eldy** [comment]
Seems fixed in v18 for proposal/card.php
Must align invoice in v18 with this.
Rules acted:
If a value were already set BEFORE selecting the thirdparty, the value must be replace by the one of the thirdparty. If no value is set on thirdparty, it must remains as it was set.
