### ISSUE TITLE
HELLO THANK YOU FOR THIS SYSTEM

### ISSUE THREAD

**Issue by ilyasse005** [Dolibarr/dolibarr#25385]
### Feature Request

I HAVE QUESTION IT IS POSIBLE TO SETUP THIS :  
    Statistique Sociéte
    Gestion De Stock Colis
    Bon De Livraison / Paiement / Distribution
    Factures
    Gestion Des Réclamations
    Gestion Client
    Client Dashboard

**Comment by dolibarr95** [comment]
Hello 
https://www.dolibarr.fr/forum.php?lang=fr&l=fr

**Comment by ksar-ksar** [comment]
Hello,

What is your question exactly ?

As indicated above, forum is better for general question on how to use Dolibarr.
