### ISSUE TITLE
mailmanspip undefined function getURLContent()

### ISSUE THREAD

**Issue by memeciredutemps** [Dolibarr/dolibarr#25399]
### Bug

If the module mailmanspip is activated, when i want to modify a member's card, the browser displays "error 500"

### Environment Version

Dolibarr 16.0.5

### Environment OS

SMP Debian 5.10.162-1

### Environment Web server

Apache/2.4.56 (Debian)

### Environment PHP

7.4.33

### Environment Database

MariaDB 5.5.5-10.5.19-

### Expected and actual behavior

I want to  modify the mail of a member.
If mailmanspip is activated: the browser displays "error 500"
If mailman is not activated: the modification is saved.

### Steps to reproduce the behavior

Activate mailmanspip
Try to modify a member 's card.

### Attached files

/var/log/apache2/dolibarr-ssl.error.log
excerpt:
PHP Fatal error:  Uncaught Error: Call to undefined function getURLContent() in /usr/share/dolibarr/htdocs/mailmanspip/class/mailmanspip.class.php:150\nStack trace:\n#0 /usr/share/dolibarr/htdocs/mailmanspip/class/mailmanspip.class.php(336): MailmanSpip->callMailman()\n#1 /usr/share/dolibarr/htdocs/admin/mailman.php(112): MailmanSpip->add_to_mailman()\n#2 {main}\n  thrown in /usr/share/dolibarr/htdocs/mailmanspip/class/mailmanspip.class.php on line 150

**Comment by IC-Ilies** [comment]
Fixed with  #26694
