### ISSUE TITLE
Tickets list and permission

### ISSUE THREAD

**Issue by artemChernitsov** [Dolibarr/dolibarr#25406]
### Bug

Regarding this issue https://github.com/Dolibarr/dolibarr/issues/16117 and option TICKET_LIMIT_VIEW_ASSIGNED_ONLY we can limit a list of tickets and display only users' tickets. But exist 2 bugs:
1) List of tickets doesn't display tickets for which user as a collaborator
2) Anybody can paste any ticket ID in link and open it /ticket/card.php?id=ANY_ID. The ticket doesn't check access permissions by user at all.

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
