### ISSUE TITLE
Error traduction for automatic event in propal

### ISSUE THREAD

**Issue by eoxia-izza** [Dolibarr/dolibarr#25408]
### Feature Request

PropalClassifiedBilledInDolibarr | Proposition %s classée payée 
ShipmentClassifyClosedInDolibarr	Expédition %s classée payée

should be : 
Proposition %s classée facturée 
Expédition %s classée facturée

**Comment by ksar-ksar** [comment]
Hello,

Already modified by @aspangaro  : 
![image](https://github.com/Dolibarr/dolibarr/assets/35605507/ad36f152-d1bd-4b94-9702-a1c5dafefb26)

and @eldy : 
![image](https://github.com/Dolibarr/dolibarr/assets/35605507/57d9a738-1f94-4fc7-8635-a523189b1013)
