### ISSUE TITLE
REST API : possibility to filter on extra-fields

### ISSUE THREAD

**Issue by LesCarnets** [Dolibarr/dolibarr#25413]
### Feature Request

Hello,

It would be great to add the possibility to filter on an extrafield when do a get call from the REST API.

Thank you by advance for your help.

### Use case

For example, I have an extra field on thirdparties. I need to do a request via the API to get all custemers with a specific value of this extrafield [ie : (t.customfield:=:'Yes')]

Unfortunatly, as the filed « customfield » is not directly created by Dolibarr in the table société but in the table société_extrafileds, sqlfilters are not working.

**Comment by hansemschnokeloch** [comment]
Hi,

feature already added with https://github.com/Dolibarr/dolibarr/pull/24635

**Comment by JonBendtsen** [comment]
@hansemschnokeloch  would you mind elaborate a bit on how one would use that?

I want to use it to select orders. Preferably just to see which services are sold in a order line, but I could also just use one of the Complementary Attributes that I added myself.

**Comment by JonBendtsen** [comment]
In case anyone else ever needs to understand how to correlate

- extrafield which is called Complementary attributes in the module configuration, and array_options in the json, and `__EXTRAFIELD_` when sending emails.
- Complementary attributes as defined under a module, in this case the product module
- sqlfilters in the API
- keys in the json exported by the API

Screenshot of definition of an Complementary attribute
![image](https://github.com/user-attachments/assets/fc8f8923-3d53-4b14-ae86-eb0c40b41e6a)

So as you can see I have one defined which I call `service_type` and which values I allow it to have.


**sqlfilters**
In the API under the `sqlfilters` field I would write this
```
(ef.service_type:like:'Workshop')
```

**JSON output**
In the resulting JSON output I would get something like this
```
    "array_options": {
      "options_service_type": "Workshop",
```


You can also combine multiple queries in the `sqlfilters` field like this
```
(t.tosell:=:1) and (ef.service_type:like:'Workshop')
```

**Comment by hregis** [comment]
@JonBendtsen I don't really understand your request. This type of filter on extrafields already works!

**Comment by JonBendtsen** [comment]
> [@JonBendtsen](https://github.com/JonBendtsen) I don't really understand your request. This type of filter on extrafields already works!

yeah, and I just found out yesterday, I've wanted to do this for a long time - but I never found any documentation for how to actually do it.

**Comment by hregis** [comment]
@JonBendtsen ok ! is see your contribution in the wiki, thank you
https://wiki.dolibarr.org/index.php?title=Universal_Search_Filter_Syntax
