### ISSUE TITLE
Bug: Contracts store localtax preferences

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2542]
Version: 3.6.2.

If you create a contract with some service and the client is not subject to Localtax2, then the configuration is saved in the contract line. If you change that setting and then try to create an invoice from a contract, the invoice will be without Localtax2 even if the client is subject to it.

**Comment by eldy** [comment]
What do you mean with " If you change that setting ". Do you mean if you change property of client to tell he IS subject to localtax2 after creating crontract ?
Does this occurs frequently ?

**Comment by marcosgdf** [comment]
Imagine that the Spanish tax administration reduces Localtax2 from 21 % to 20 % since 1 january of 2015.

If you have a contract created in 2014, it stores the 21 % of the localtax2 amount which is correct in 2014.

Now in 2015, I change the localtax2 percentage in the settings and when I create an invoice from the contract, Localtax2 contains a wrong amount until I edit and save each line of the invoice.

**Comment by simnandez** [comment]
If you change the localtax2 percentage and you create an invoice from te contract, localtax2 containg the correct amont (tested in 3.6.3)

**Comment by marcosgdf** [comment]
Maybe what I tested was that when I created the contract, the client was not subject to Localtax2, but I change it later and create an invoice from the contract. The invoice has no Localtax2 amount.

This was tested in 3.6.2
