### ISSUE TITLE
Products aren't show in Product->Products->List after the importation

### ISSUE THREAD

**Issue by erwinpalma** [Dolibarr/dolibarr#25459]
### Bug

After importing a list of products, those are not showing in the Product List, but yes in the **Latest 15 products/services which were modified**.

It is a fresh installation.

![image](https://github.com/Dolibarr/dolibarr/assets/30660343/2ac331fe-8188-4f44-b1c5-a60d3492525b)

### Environment Version

17.0.1

### Environment OS

Ubuntu 22.04.2 LTS

### Environment Web server

Edge, Safari, Chrome

### Environment PHP

8.1.2-1ubuntu2

### Environment Database

MySQL or MariaDB 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1

### Expected and actual behavior

The products should be listeable into the Product->Products->List

### Steps to reproduce the behavior

1. Install Dolibarr 17.0.1 from github (clone it or download the release)
2. Follow the Wizard for one installation from scratch.
3. Make the basic configuration **Home->Setup->Company/Organization**
4. Activate the modules THIRD PARTIES, PRODUCTS, TAGS/CATEGORIES and DATA IMPORTS
5. Go to Tools->Import Assistant->New Import->Products
6. Import the file Ejemplo_de_archivo2.xlsx
7. After the importation, go to Products->Products->List

### Attached files

[Ejemplo_de_archivo2.xlsx](https://github.com/Dolibarr/dolibarr/files/12146015/Ejemplo_de_archivo2.xlsx)

No error, no logs

**Comment by oussamanhairech** [comment]
I cannot reproduce the bug in a fresh install **17.02**; and  the products are displayed correctly.

**Comment by erwinpalma** [comment]
I have run other testing and the problem (as you mentioned) is not present.

I am closing the issue because a couldn't reproduce it again.
