### ISSUE TITLE
Some Products dont show up in List when creating an invoice

### ISSUE THREAD

**Issue by goldenwt** [Dolibarr/dolibarr#25453]
### Bug

When creating an invoice from billing, upon getting to pick the product from the list of products, some products dont show up. It returns not found, meanwhile stock shows it has enough products in the warehouse being selected from. 

Using TakePOS shows the same products that "billing(invoice)" says "not found"

![image](https://github.com/Dolibarr/dolibarr/assets/24619120/642043f8-8690-4461-994a-0cbd24d98704)
![image](https://github.com/Dolibarr/dolibarr/assets/24619120/43b4cd40-32dc-46c5-a99d-4a50c4906983)

### Environment Version

17.0.2

### Environment OS

Linux

### Environment PHP

 7.4.27

### Environment Database

10.5.20-MariaDB-cll-lve-log

### Expected and actual behavior

It is expected that upon clicking the product list to select from, all products in the product list should show

Actual: Only some products show in the list, some others would return as not found while they still have quantities in their warehouses

### Steps to reproduce the behavior

1. Click billing
2. Click on New Invoice
3. Select a customer or create a new one
4. Select predefined products - in the space provided, click to generate product list
5. Test some sample products with quantities

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/24619120/642043f8-8690-4461-994a-0cbd24d98704)
![image](https://github.com/Dolibarr/dolibarr/assets/24619120/43b4cd40-32dc-46c5-a99d-4a50c4906983)

**Comment by atm-maxime** [comment]
Did you check in the product setup the list limit ? If you have more products than a certain number, maybe you should switch to a search field instead of a drop-down.

**Comment by goldenwt** [comment]
Thank you Maxime,

I just remembered I added more products to our list of products.

I adjusted the limit and the products are showing now

Thank you once again


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by goldenwt** [comment]
Hello maxime,

Pls a quick discovery.

If you activate product lot so you can use bulk stock change, the POS stock decrease would be disable.

If you disable the product lot/serial, you can use the bulk stock change under product – warehouse – stock bulk change.

We use POS and also want to use the Bulk stock change cos its easier for us to move items from  different warehouse through one entry as against each stock items to do stock transfer

Any help or guide?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
