### ISSUE TITLE
Not able to translate the string "Done" (intervention status)

### ISSUE THREAD

**Issue by calbasi** [Dolibarr/dolibarr#25458]
### Bug

The interventions list shows some status: validated, done... but "Done" can not be translated, there is no string to do it.

### Environment Version

17.0.2

**Comment by emheyarssi** [comment]
Translation must be made in transifex (https://app.transifex.com/dolibarr-association/dolibarr/dashboard/)

**Comment by calbasi** [comment]
By the way, you can see this string here, for example:

/fichinter/list.php?leftmenu=ficheinter

@emheyarssi Trying transifex, but I think it's not the case, because this string is shown in English in the Catalan, Spanish and French interface. And I can not find it in the Translation admin section ( /admin/translation.php?mainmenu=home ).

**Comment by calbasi** [comment]
> Translation must be made in transifex (https://app.transifex.com/dolibarr-association/dolibarr/dashboard/)

By the way, Catalan translation is at 100% and there are 2 "Done" strings traslated as "Realitzades":


> Tags
> robotonet
> Key
> ActionsDoneShort
> Character Limit
> 0
> More Info
> Size
> 1 word
> Context
> None
> Resource
> main
> String Hash
> ea34cbc06b35cbb04d98dbf581dce4c9

and 


> Key
> EvntOrgDone
> Character Limit
> 0
> More Info
> Size
> 1 word
> Context
> None
> Resource
> eventorganization
> String Hash
> 9837d8996a6a4166750e33d505d451b9

But they don't apply the missing string at /fichinter/list.php?leftmenu=ficheinter

**Comment by W1W1-M** [comment]
Hello, 
From what I can see the word "_done_" is not in any of **en_US** or **fr_FR** `.lang` files. I imagine it should be in the `main.lang` file. I've fixed this for English & French localizations in a related PR for interventions #26127 
Regards

**Comment by W1W1-M** [comment]
This is fixed for **fr_FR** but still needs to be done 😅 for **ca_ES** & **es_ES**

**Comment by calbasi** [comment]
> This is fixed for **fr_FR** but still needs to be done 😅 for **ca_ES** & **es_ES**

It seems it is not available at Transifex right now:

https://app.transifex.com/dolibarr-association/dolibarr/translate/#ca_ES/main?q=text%3AInvoiced+key%3ADone

In fact, the source hasn't been updated since Nov, 7th in Transifex
