### ISSUE TITLE
Material List getting wrong numbers

### ISSUE THREAD

**Issue by BanMePlox** [Dolibarr/dolibarr#25454]
### Bug

![image](https://github.com/Dolibarr/dolibarr/assets/15201580/a60da469-4a6f-4dfe-a374-cd9b4692adff)
When i upload a material list, when i want to generate 10 of the item, it is getting wrong quantities. It's using 0.1x of the quantity it should be using:
![image](https://github.com/Dolibarr/dolibarr/assets/15201580/e7fae78a-9d3a-4e24-8956-902b5d546962)

### Environment Version

17.0.5

### Environment PHP

8

### Environment Database

MySQL

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 17.0.3
