### ISSUE TITLE
Export ICS result in html escaped chars

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#25487]
### Bug

If I subscribe to the ics holiday calendar with thunderbird with an URL like https://dolibarr.FQDN/public/agenda/agendaexport.php?format=ical&exportkey=somekey&includeholidays=1&notactiontype=systemauto I get some events with title like `Cong&eacute;s - Beniamine`

A quick (and probably bad) fix is to change line 2095 of `comm/action/class/actioncomm.class.php`  

```php
$title = $langs->trans("Holidays");
```

to 

```php
$title = $langs->transnoentitiesnoconv("Holidays");
```

I think this probably breaks the RSS export.

### Environment Version

17.0.2

### Environment OS

Debian 11

### Environment Web server

Apache 2 2.4.56

### Environment PHP

7.4.33

### Environment Database

mariadb 10.3

### Environment URL(s)

public/agenda/agendaexport.php?includeholiday=1

### Expected and actual behavior

In ICS format accentued chars should not be escaped, but they are

### Steps to reproduce the behavior

subscribe to the ics holiday calendar with thunderbird with an URL like https://dolibarr.FQDN/public/agenda/agendaexport.php?format=ical&exportkey=somekey&includeholidays=1&notactiontype=systemauto with a French system

**Comment by hansemschnokeloch** [comment]
Fixed by https://github.com/Dolibarr/dolibarr/pull/24983
