### ISSUE TITLE
Bug: movement stock origin not linked

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#25495]
# Bug
No more link of movement stock origin for personnal modules (used to work on v14, no more on v17)

## Environment
- **Version**: 17.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.2.34
- **Database**: MySQL or MariaDB 5.5.5-10.6.14-MariaDB
- **URL(s)**: /17/product/stock/movement_list.php?idproduct=1447

## Expected and actual behavior

With a personal module that creates stock movements. To point to the origin of the movement it was necessary to declare this:
```php
//Personnal module Truc

$mouvementstatic = new MouvementStock($this->db);
$mouvementstatic->origin = new Truc($this->db);
$mouvementstatic->origin->id = $this->id;//2619
$mouvementstatic->origin->origin_type = $this->origin_type;//truc@truc;
```
```php
//mouvementstock.class.php _create() in V14

// Set $origintype, fk_origin, fk_project
$fk_project = 0;
if (!empty($this->origin)) {			// This is set by caller for tracking reason
  $origintype = empty($this->origin->origin_type) ? $this->origin->element : $this->origin->origin_type;
  $fk_origin = $this->origin->id;
  if ($origintype == 'project') {
    $fk_project = $fk_origin;
  } else {
    $res = $this->origin->fetch($fk_origin);
    if ($res > 0) {
        if (!empty($this->origin->fk_project)) {
            $fk_project = $this->origin->fk_project;
         }
    }
 }
} else {
  $origintype = '';
  $fk_origin = 0;
  $fk_project = 0;
}

```
In this case in db ```llx_stock_mouvement``` we have : 
| fk_product| label | fk_origin | origintype |
| -------- | -------- | ------- | ------- |
| 1447 | product used for... | 2619 | truc@truc |

```php
//mouvementstock.class.php _create() in V17
// Set $origin_type, origin_id and fk_project
$fk_project = $this->fk_project;
if (!empty($this->origin_type)) {			// This is set by caller for tracking reason
  $origin_type = $this->origin_type;
  $origin_id = $this->origin_id;
  if (empty($fk_project) && $origin_type == 'project') {
    $fk_project = $origin_id;
    $origin_type = '';
    $origin_id = 0;
  }
} else {
  $fk_project = 0;
  $origin_type = '';
  $origin_id = 0;
}
```
In this case in db ```llx_stock_mouvement``` we have : 
| fk_product| label | fk_origin | origintype |
| -------- | -------- | ------- | ------- |
| 1447 | product used for... | 0|  |

## Screenshot
In v14 link vas done in v17 we lose the link

![Capture](https://github.com/Dolibarr/dolibarr/assets/24292300/c747d34a-f42f-40da-b8d3-be51136910b8)

## Forum
[Discussion about the 'bug' since v15](https://www.dolibarr.fr/forum/t/dolibarr-v15-et-les-mouvements-de-stock-changement/38467)

Tks for reading
----------------------
I ❤️ v17

**Comment by dolibarr95** [comment]
I've just see : 
```php
	/**
	 * @var int ID
	 * @deprecated
	 * @see $origin_id
	 */
	public $fk_origin;

	/**
	 * @var int		Origin id
	 */
	public $origin_id;

	/**
	 * @var	string	origintype
	 * @deprecated
	 * see $origin_type
	 */
	public $origintype;

	/**
	 * @var string Origin type ('project', ...)
	 */
	public $origin_type;
```
I test and give feedback

**Comment by goldenwt** [comment]
Hi,

Does this mean that with this code, it will show opening stock when stock movement is done on a particular product?

Currently it doesnt start with the opening stock, it starts from when an addition is done to the opening stock or when a deduction or sale decrease is done.

So pls what is the benefit of this code and how can we implement it if it meets the explanation i gave above

Thank you

**Comment by dolibarr95** [comment]
Hello
_I don't think we are talking about the same thing._
The bug I think I found (need to check) is only that the link to the item that generated the stock (increment or decrement) no longer displays. On the other hand, the movements are done correctly.
