### ISSUE TITLE
Control default permissions add check/uncheck box

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#25491]
### Feature Request

- [ ] Some permissions are check by default 

![image](https://github.com/Dolibarr/dolibarr/assets/3288514/22aedd61-b16f-417f-8188-62287d77d131)

**Comment by dolibarr95** [comment]
Hello 
Is it for an external module ?

**Comment by atm-maxime** [comment]
Hi @lmag. I found in Dolibarr core modules giving permissions by default : label, zapier, barcode, debugbar, deplacement, don.
I removed them in #25575

**Comment by lmag** [comment]
Thank Maxime !
