### ISSUE TITLE
Project names are truncated in project list and in project select

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2551]
Version: 3.6.2

Project names are too short and there is enough room to show larger ones.
![captura de pantalla 2015-04-04 a las 18 09 15](https://cloud.githubusercontent.com/assets/168744/6993455/b9e81f6e-daf5-11e4-8398-90ad918ed51e.png)

![captura de pantalla 2015-04-04 a las 18 08 54](https://cloud.githubusercontent.com/assets/168744/6993453/ab9b03cc-daf5-11e4-850d-cdd8c50eac85.png)

**Comment by eldy** [comment]
With 3.8, i think i have removed trunc into combo list.

**Comment by marcosgdf** [comment]
Can we remove it for 3.5~3.7 then? It is very annoying when having large project names

**Comment by marcosgdf** [comment]
Closing as it has been done in 3.8
