### ISSUE TITLE
Refus authent si + de n echec d'authent en 24h

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#25512]
### Feature Request

Add an option in home - setup - security  called
Max nb of failed authentication attempt in last 24h to allow login
Value 100 by default

Then into file functions_dolibarr, before testing password, we do a select count into llx_event for login and ip and code = USER_LOGIN_FAILED and date > now - 24h. If result is higher than param (so 100), we return an error "Too many attempts". No need to check password.

**Comment by eldy** [comment]
For lucas, you can do it or ask abdel of oussama to do it.

**Comment by atm-maxime** [comment]
Great function !
This will make the login audit option enabled by default?

What do you think about a "locked account" field (or simply user disabling) when too many wrong pass have been tried ? Needing an admin to reactivate the account?

And a password validity time forcing user to change it every x days ?
