### ISSUE TITLE
Generate repeatable invoice

### ISSUE THREAD

**Issue by IvanBUL** [Dolibarr/dolibarr#2553]
Hi guys i dont know if its right to suggest new features here but i will do it : )
1.repeatable invoices invoice that is issued automatically every month or week and send to an email defined as default contact for that invoice.
2.when making payment to an customer invoice can we have some button or link in the line to automatically add total of the amount not to typed every time if all its payed.
3.repeatable events in agenda to be able to set event to be yearly or weekly or Mount or every chosen day of the week repeatable
thanks for the attention i have other ideas too ,but i think those few options will be very useful.

**Comment by BebZ** [comment]
1. Repeatable invoices are possible, with contracts module i guess, or pre-defined invoices. 
   but never tried.
   Issued automatically, as draft, or you mean really automatically ? 
   (developpers didn't agree because it's quite source of errors and dangerous ;)
2. for me it used to work with 
   USE_JAVASCRIPT_AJAX set to 1 
   and
   MAIN_JS_ON_PAYMENT set to 1
   now on 3.7 it works with 
   MAIN_JS_ON_PAYMENT set to 0
   and
   FAC_AUTO_FILLJS

there is nothing on the wiki about it i guess...
1. repeatable events for agenda are being discussed sometimes on the forum... don't know who will : 
   -make and sell a module
   -make the beginning of work to be integrated on github, and then rely on community to finish and maintain

**Comment by IvanBUL** [comment]
Hi BebZ again : ) i also thought pre-defined invoice to be some type of repeatable invoice but i did not manage to get it to work ,how ever i will take a look at contracts and how to set repeatable invoice from there.
2. i have try your suggestion and it works great for me on 3.7(test) and 3.6.2(production) with MAIN_JS_ON_PAYMENT set to 1 for 3.6.2 and FAC_AUTO_FILLJS set to 1 for 3.7  ,10x a lot about that info : )))
3. i hope we can see them soon it will be useful feature.

**Comment by IvanBUL** [comment]
Hi guys i did not manage to create repeatable invoice using contract module , if anyone can give some tip it will be appreciate thanks.

**Comment by rdoursenaud** [comment]
@IvanBUL You should seek help using [the forum](http://www.dolibarr.org/forum).
Issues are **not** for support. Please keep the discussion on topic.

**Comment by IvanBUL** [comment]
Hi @rdoursenaud thank you for your reply ,i just want to point out a few things here :
1.dolibarr forum i pretty much inactive.
2.repeatable invoices are nice feature to have. 
and i think that topic here is "Feature Request" and we discus ideas how and ware to be able to create such invoices e.t. do we need contract to create repeatable invoices yes may be sounds logical. Can they be available outside of this module yes i looks like more easy way for more lite configurations of dolibarr and so on....... so my point is if you can't provide any useful ideas or information ,just don't write useless comments

**Comment by eldy** [comment]
For repeatable invoice, table is already ready. It is llx_facture_rec.
Still looking for dev to do this:
- [ ] enhance form of predefined invoice to be able to edit/view the date start, date end, period to repeat creation and date of first/next generation (file htdocs/compta/facture/fiche-rec.php)
- [ ] create a class with a method "generatePlannedInvoice" that will look table llx_facture_rec with field date_next_gen < current date, and clone invoice into a draft invoice (with date = date_next_gen) then update date_next_gen according to frequency. If new date is still lower than current date, restart the cloning until date > current date.
- [ ] then add a page "Generate scheduled invoices" with just an explanation and a button "Generate scheduled invoices".

**Comment by BebZ** [comment]
Ok, i will make the tests when someone will try to make it :) 
When a subject is labelled Feature Request, it should be allowed to discuss it here.

Rdoursenaud says right if you're looking for support for config, it's the wrong place here (example : Fac_autofill_js you could find the answer on the forum, which is not inactive for intelligent questions ;)

**Comment by IvanBUL** [comment]
Hi @eldy thank for the info : ))) i have to say i sounds very nice and will love to try or test it as soon is ready or possible thanks for the input again very much appreciated.

**Comment by IvanBUL** [comment]
hi @BebZ i have to say i'm dolibarr forum every day i have posted intelligent questions about some issues but i did not receive any info or reply ,how ever probably far more intelligent questions with topic "Login from any PC" are far more discussed. How ever i don't find my comment to be tell me how i was looking for something that i may have mist or dependency e.t.c.....

**Comment by BebZ** [comment]
You not obliged to close it reopen #2553 :) as Eldy gave some nice advices please.
I'm sorry you didnt find any help on ENGLISh forum, i was misunderstanding with french one...
There is a lot of internationalization being made in Dolibarr in the code now, hope this will encourage more people speak english

**Comment by IvanBUL** [comment]
Hi guys i'm new to this system and i did not know i'm opening it again ,and awaiting for more input from Eldy : )

**Comment by eldy** [comment]
Work on this feature is on the road...

**Comment by IvanBUL** [comment]
Nice ,i think that it will be very useful feature to have ,i can help with testing.

**Comment by bblaha** [comment]
Hi, are there any news regarding this or any further help required on a technical/ side?
I just tried Dolibarr for the first time and will stick with it, if recurring invoices are available, so I would be happy to contribute in order to get this going.

**Comment by atm-maxime** [comment]
Hi, I close this issue, work has been done and will be release with 4.0
