### ISSUE TITLE
Generating invoices with date and duration into line description

### ISSUE THREAD

**Issue by tdockx** [Dolibarr/dolibarr#25571]
### Bug

When you select your project and go to tab "time spent".  
You select your list of time consumed and click on "generate invoice"

There you select the mode "One line for each time spent declaration"  
You tick the box : "With date and duration into line description"  

![image](https://github.com/Dolibarr/dolibarr/assets/66223503/f3f75570-b423-43a2-b8f5-29e4a94cd137)

When the invoice is created as draft, the time spent is seen without the date.
Like this (E.g) 

![image](https://github.com/Dolibarr/dolibarr/assets/66223503/1f3c333f-b08d-4cbd-b643-7caf48288bf3)

### Environment Version

18

### Environment OS

Debian 12

### Environment Web server

Apache2

### Environment PHP

PHP 8.2.7

### Environment Database

mariadb  Ver 15.1 Distrib 10.11.3-MariaDB

### Environment URL(s)

compta/facture/card.php

### Expected and actual behavior

I would expect the date to be seen before the actual time spent on the invoice generated.

### Steps to reproduce the behavior

Simple create an invoice based on time consumed for a task's project as described in the picture above.

**Comment by tdockx** [comment]
Hey there,

I was just wondering if this is issue is only linked to version 18.0; I just realized that 17.x was the official “stable”.
Thank you for letting me know.

Kind regards.

**Comment by atm-maxime** [comment]
Hello ! Thanks for your feedback. I just checked on my side an it works fine. Can you check on your side and close the issue if it's ok for you ?

V17 :
![image](https://github.com/Dolibarr/dolibarr/assets/2097773/a8634243-af39-4981-9425-1d4fad480af3)

V18 :
![image](https://github.com/Dolibarr/dolibarr/assets/2097773/29aadfa3-c27c-401c-b047-f91979288ea6)

**Comment by tdockx** [comment]
Hi Maxime,

Thanks for your reply, I'll check later today after I've performed possible updates.

I will let you know by closing the issue if fixed.

Kind regards.

**Comment by tdockx** [comment]
Hi Maxime.

Thank you very much for your work, it is now working perfectly.
Really appreciate it !

Kind regards,
Thibault
