### ISSUE TITLE
Bug: Untranslated "Total" in Bank module

### ISSUE THREAD

**Issue by IvanBUL** [Dolibarr/dolibarr#2559]
minor bug in general view of bank module i did not find any way to translate this from BG-bg lang or US for that mater 

hope this helps.
![capture](https://cloud.githubusercontent.com/assets/11728170/7010322/d6389072-dca8-11e4-976e-4be85584727d.JPG)

**Comment by IvanBUL** [comment]
its not anything urgent just letting you know ,this bug appear after migrating from 3.5 to 3.6.2

**Comment by frederic34** [comment]
Hello, can you try this:
https://github.com/Dolibarr/dolibarr/pull/2561

**Comment by IvanBUL** [comment]
it works
Hello frederic34 i have replaced the code with new that you have provided and its fix ,done

p.s. i have made same changes in rows 182 and 242 so that can take effect for other types of bank accounts
