### ISSUE TITLE
Keep Github Releases up to date

### ISSUE THREAD

**Issue by Basti-Fantasti** [Dolibarr/dolibarr#25591]
### Feature Request

When searching for new Dolibarr versions, very often a new version is shown and available on dolibarr.org but the release is not tagged on github - and so no changelog is available prior to installation.

### Use case

stay informed about new releases 😄 

### Suggested steps

Please keep the Release tags with included changelogs on github up to date with the dolibarr.org `latest version` info

**Comment by hansemschnokeloch** [comment]
This issue is back on the agenda !
