### ISSUE TITLE
new product button disappear after submitting an empty form in BOM

### ISSUE THREAD

**Issue by oussamanhairech** [Dolibarr/dolibarr#25594]
### Bug

When submitting the BOM form with an empty required field, the button of new product disappear. 

![Screenshot from 2023-08-08 22-43-23](https://github.com/Dolibarr/dolibarr/assets/47675588/a2de2ba1-c8ea-4851-b889-ed5a89c09a20)

![Screenshot from 2023-08-08 22-43-48](https://github.com/Dolibarr/dolibarr/assets/47675588/c251b041-36f6-4241-ba89-9cb41cd9082c)

The button is displayed by the line 7375 in commonobject.class.php, if  the condition : `(!GETPOST('backtopage') && empty($val['disabled']) && empty($nonewbutton)) `   is true. When submitting the page,`!GETPOSTISSET('backtopage')` is True, thus the button isn't displayed.

### Environment Version

17.02

### Environment OS

ubuntu

### Environment PHP

8.1

### Environment Database

Mysql

### Environment URL(s)

htdocs/bom/bom_card.php?leftmenu=bom&action=create

**Comment by eldy** [comment]
Fixed in develop branch
