### ISSUE TITLE
Add a PDF option to show the value (number) of the barcode of product (just under the ref) 

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#25600]
### Feature Request

Add a PDF option to show the value (number) of the barcode of product (just under the ref) 
shipment documents
proposal
order
invoice
purchase proposal
purchase order
purchase invoice

Output on PDF is 
Ref - Label or product
Description

Must be 
Ref - Label or product
Barcode (if exists and if module is on)
Description

**Comment by finalbeta** [comment]
After enabling the module. I noticed that I had no way to get the serial numbers on invoices. 

We continu to place serial numbers on invoices manually as a legal obligation for warranty exists, and invoices are the proof that the product with that serialnumber came from us. 
So this would definitly be a usefull feature.
