### ISSUE TITLE
ODT Generation on Propal: ExtraField empty on generation and erased from record

### ISSUE THREAD

**Issue by Draekmus** [Dolibarr/dolibarr#25604]
### Bug

I have an extra field on my proposal (Propal) page to link commercial proposals to a ticket number.  So far, I have been linking it by using a complimentary attribute set as "Link to an Object".

I noticed that whenever I try to generate an ODT document and reference the object, not only is the field blank on the document (it sees the tag, but replaces it with empty space), but the link is erased from the proposal as well.

### Environment Version

17.0.2

**Comment by priojk** [comment]
I just noticed a problem with the generation of odt-based documents for proposals in v17.0.3:

After clicking on the "generate" button, only the tabs are shown and the rest of the screen remains blank. Only after clicking on one of the tabs, the message "document successfully generated" appears. 

Is this also the case with your installation? My first guess would be that those issues may be related.
