### ISSUE TITLE
PHP Error when sending invoice email

### ISSUE THREAD

**Issue by comaiteseb** [Dolibarr/dolibarr#25613]
### Bug

Hi,

When I want to send an email, I have this error:  Call to undefined function getDomainFromURL()

### Environment Version

18.0

### Environment PHP

7.4

### Environment Database

Percona SQL 8.0

### Expected and actual behavior

```
[10-Aug-2023 17:08:52 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function getDomainFromURL() in /space/www/dolibarr/htdocs/core/class/smtps.class.php:697
Stack trace:
#0 /space/www/dolibarr/htdocs/core/class/CMailFile.class.php(1004): SMTPs->sendMsg()
#1 /space/www/dolibarr/htdocs/core/actions_sendmails.inc.php(372): CMailFile->sendfile()
#2 /space/www/dolibarr/htdocs/compta/facture/card.php(2878): include('/space/www/doli...')
#3 {main}
  thrown in /space/www/dolibarr/htdocs/core/class/smtps.class.php on line 697
```
If I add in htdocs/core/class/smtps.class.php the line below it works... but I think it is not the right place for this.
`require_once(DOL_DOCUMENT_ROOT.'/core/lib/geturl.lib.php');`

### Steps to reproduce the behavior

Inside an invoice, click on sendemail and then click again on send email.

**Comment by Je2fb** [comment]
Thanks, i got the same error and your line fix the issue

**Comment by git-putz** [comment]
Having similar issues when I create other records like tickets.
Get HTTP 500.
If I go into Setup > Emails and turn off emails I do not get the error and can create records w/o issue.

I have had the same email configuration for years in Dolibarr and can confirm the settings are still valid.  This just started happening recently.

`[Tue Sep 05 12:41:07.904279 2023] [php:error] [pid 36] [client 172.20.255.4:41688] PHP Fatal error: Uncaught Error: Call to undefined function getDomainFromURL() in /var/www/html/core/class/smtps.class.php:697\nStack trace:\n#0 /var/www/html/core/class/CMailFile.class.php(1004): SMTPs->sendMsg()\n#1 /var/www/html/core/triggers/interface_50_modTicket_TicketEmail.class.php(353): CMailFile->sendfile()\n#2 /var/www/html/core/triggers/interface_50_modTicket_TicketEmail.class.php(184): InterfaceTicketEmail->composeAndSendAdminMessage()\n#3 /var/www/html/core/class/interfaces.class.php(183): InterfaceTicketEmail->runTrigger()\n#4 /var/www/html/core/class/commonobject.class.php(5790): Interfaces->run_triggers()\n#5 /var/www/html/ticket/class/ticket.class.php(569): CommonObject->call_trigger()\n#6 /var/www/html/ticket/card.php(244): Ticket->create()\n#7 {main}\n thrown in /var/www/html/core/class/smtps.class.php on line 697, referer: https://www.mydolibarr.com/ticket/card.php`

Here is my DB information:

![image](https://github.com/Dolibarr/dolibarr/assets/52859696/a072283e-35df-482a-9c97-235da3f41d2c)

![image](https://github.com/Dolibarr/dolibarr/assets/52859696/87cae447-7dd1-40fa-a6c0-5b8125d7a02e)

![image](https://github.com/Dolibarr/dolibarr/assets/52859696/1f706951-097e-4645-9ed7-caf6054a7e73)

![image](https://github.com/Dolibarr/dolibarr/assets/52859696/4d4cef6b-d90d-4282-b475-fe1f9045da21)
