### ISSUE TITLE
Access refused by CSRF protection

### ISSUE THREAD

**Issue by JiroMusik** [Dolibarr/dolibarr#25638]
### Bug

Hi guys, 
on my Docker Container I got a problem with CSRF protection.
I could do most actions for some days but after a cold reboot or just after some time I cant do most actions like Deleting documents or sending invoices.
I need that functions and tried to set the CSRF Protection env variables to 0 or 1 but it wont work.
When changing the ENV for the web-server it does not get changed inside the container after Recreating

What can I do to resolve that problem?

### Environment Version

Docker Env

### Environment OS

Docker

Dolibarr 17.0.2

### Expected and actual behavior

Access to this page this way (POST method or GET with a sensible value for 'action' parameter) is refused by CSRF protection in main.inc.php. Token not provided. If you access your server behind a proxy using url rewriting and the parameter is provided by caller, you might check that all HTTP header are propagated (or add the line $dolibarr_nocsrfcheck=1 into your conf.php file or MAIN_SECURITY_CSRF_WITH_TOKEN to 0 instead of 2 into setup).

**Comment by coop2540** [comment]
I have the same problem on Dolibarr 18
with
$dolibarr_nocsrfcheck='1';
and
MAIN_SECURITY_CSRF_WITH_TOKEN set to 0
