### ISSUE TITLE
Product variants - mother product populated

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#25645]
### Bug

When creating product variants, the "mother" product is still available in the search, stock, etc. If I set it unavailable, all the variants get set unavailable. Example creating a product: Cat5e cable, and the variants: blue, yellow. But when searching, all three are available, however the mother product is not a real one.

### Environment Version

17.0.3

### Expected and actual behavior

Expected: mother product should be unavailable

**Comment by atm-maxime** [comment]
Hi @vanyolai .
You can set your parent product to "Not for sale" status. It will change all your variants with the same status, but then you can set the variants back to "On sale".

**Comment by vanyolai** [comment]
Thanks, so far I got too, but it's rather a workaround, than a real solution...
