### ISSUE TITLE
Wrong product status in Buy Price and sell price page

### ISSUE THREAD

**Issue by BlueGarm** [Dolibarr/dolibarr#25647]
### Bug

On dolibarr 18 there is a problem with the statuses on the Sales and Purchase Price pages.

If a product is "On Buy", the Buy Price page is available, but if it is "Not On Sell" at the same time, both statuses are "inactive".

![FireShot Capture 226 - Produit Chips - Fiche - demo dolibarr org](https://github.com/Dolibarr/dolibarr/assets/52456749/5e0173a0-8988-48a7-b0b4-b191e1cab413)

![FireShot Capture 227 - Produit Chips - Prix d'achat - demo dolibarr org](https://github.com/Dolibarr/dolibarr/assets/52456749/305a004e-c11e-40ab-aaf9-e1a47b7337f8)

If a product is "On Sell" but "Not On Buy", it is still possible to add a buy price, and both statuses are "active".

![FireShot Capture 224 - Produit PP-001 - Fiche - demo dolibarr org](https://github.com/Dolibarr/dolibarr/assets/52456749/be0a07ae-2785-4ef4-8246-586a3bbe2df5)

![FireShot Capture 225 - Produit PP-001 - Prix d'achat - demo dolibarr org](https://github.com/Dolibarr/dolibarr/assets/52456749/21379318-7f0e-4d02-86ec-bfc8713f89d0)

Visible bugs on the shared test platform

### Environment Version

18

### Environment URL(s)

https://demo.dolibarr.org/product/fournisseurs.php?id=619, https://demo.dolibarr.org/product/fournisseurs.php?id=30

**Comment by W1W1-M** [comment]
Seems to work as wanted in v19.

**Comment by Hystepik** [comment]
Works for me in last version of 18
