### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2566]
A while ago, after attending [a talk at RMLL about using Dolibarr being blind](https://2014.rmll.info/conference223), I started working on improving Dolibarr accessibility (#1730, #1737) and documented some insights [on the wiki](http://wiki.dolibarr.org/index.php/Accessibility).

Unfortunately, I don't have the time to do all the required work on my own.

I open this issue in the hope we can gather more insights and allow/motivate interested developers to join the effort.

I believe an issue is better suited to have a discussion than the wiki.

Feel free to add comments or pick a task and start working on it ;)
# What needs to be addressed
- [ ] Title on each and every page to help identify them #3292
- [ ] `<th>` tag for table headers. Keeping in mind you may need to fix some bugs in javascript libs.
- [ ] `label` attribute for each and every form element. Same here, some javascript libs may need fixing.
- [ ] Shortcuts to content/search/action/submenu above the menu
- [ ] Avoid reloading the page as much as possible
- [ ] Accessible PDFs (Elements generation order matters)
- [ ] Get rid of messages at the bottom of the page and prefer modal popups
- [ ] Completely avoid messages that automatically disappear (Like confirmation JS popups)

Each list element may need its own issue # at some point. If you plan working on it, create an issue and reference this one, I'll try and do my best to update it accordingly.

Keep in mind that accessibility doesn't only benefit the blind or visually impaired. If done well, it improves the experience for all users.
## Miscellaneous other stuff to check
- [ ] Default theme and color blindness
- [ ] Keyboard shortcuts #2965 
## References
- [Web Accessibility Initiative](http://www.w3.org/WAI)
  - [Web Content Accessibility Guidelines](http://www.w3.org/WAI/intro/wcag)
  - [Accessible Rich Internet Applications](http://www.w3.org/WAI/intro/aria)

**Comment by eldy** [comment]
I woul prefer one issue per type of development action. It will be easier to get contrib than one very large request.

**Comment by rdoursenaud** [comment]
@eldy That's the plan.
I created this issue as the master canvas to keep track of all ongoing work on the subject.
This way, any issue related to accessibility can reference this one and I'm committed to keeping the description clean and up to date.
This keeps things neat and organized making it easier for people interested in the broad subject to find what's going on.
This issue may very well never be closed since this is a work of every moment.
Removing the volunteer wanted tag kinda defeats the purpose…
