### ISSUE TITLE
Bug: Dolibarr on Dolicloud can't calculate taxes anymore for Québec, Canada

### ISSUE THREAD

**Issue by m10ust** [Dolibarr/dolibarr#25665]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 16.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3
- **Database**: MySQL or MariaDB 5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1
- **URL(s)**: /compta/facture/card.php?facid=217

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Report

I have an invoice to send and the taxes are all over the place. Not a single number is right. I double checked with a taxes calculator from my government and ChatGPT 4.0. 

Those are the numbers from Dolibarr 

"Description | Taxes | Prix | Qté | Réduc. | Prix ​​de revient | Total HT |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
111065 - Longeron 3'6 (1.065M) | 5/9.975% | 30,16 | 25 |   | 0,00 | 754,00 |   |   |  
111150-F - Longeron 1.15m (3'10) | 5/9.975% | 28,87 | 50 |   | 0,00 | 1 443,50 |   |   |  
111572-F - Longeron 5'2 (1.572M) | 5/9.975% | 32,40 | 30 |   | 0,00 | 972,00 |   |   |  
100280-F - Collier de base | 5/9.975% | 11,26 | 10 |   | 0,00 | 112,60 |   |   |  
142130-F-E - Lattice Modulaire Fin 7' | 5/9.975% | 151,80 | 14 |   | 0,00 | 2 125,20 |   |   |  
140010-F - Connecteur Modulaire a Boulon Gradés | 5/9.975% | 25,20 | 14 |   | 0,00 | 352,80 |   |   |  
500020-F - Tube aluminium 20' | 5/9.975% | 99,75 | 1 |   | 0,00 | 99,75 |   |   |  
121572-F - Contreventement 5'2 | 5/9.975% | 37,46 | 20 |   | 0,00 | 749,20 |   |   |  
420306-F - Planche d'acier 3'6 | 5/9.975% | 38,77 | 70 |   | 0,00 | 2 713,90 |   |   |  
420310-F - Planche d'acier 3'10 x 9,5 | 5/9.975% | 35,90 | 20 |   | 0,00 | 718,00 |   |   |  
420502-F - Planche d'acier 5'2 x 9.5 | 5/9.975% | 50,62 | 25 |   | 0,00 | 1 265,50 |   |   |  
420700-F - Planches d'Acier 7' | 5/9.975% | 65,63 | 14 |   | 0,00 | 918,82 |   |   |  
190261-F - Barrure a Rosette a rosette | 5/9.975% | 22,98 | 4 |   | 0,00 | 91,92 |   |   |  
500606-F - Raccord Papillon / Rosette a rosette | 5/9.975% | 12,61 | 4 |   | 0,00 | 50,44 |   |   |  
400306-F - Plinthe 3'6 (1.065 M) | 5/9.975% | 19,05 | 30 |   | 0,00 | 571,50 |   |   |  
250511-F - Potence de levage | 5/9.975% | 248,74 | 1 |   | 0,00 | 248,74 |   |   |  
250513-F - Potence pour homme | 5/9.975% | 373,82 | 1 |   | 0,00 | 373,82 |   |   |  
400502-F - Plinthes 5'2 (1,527 M) | 5/9.975% | 26,40 | 30 |   | 0,00 | 792,00 |   |   |  
400700-F - Plinthe 7' (2.130 M) | 5/9.975% | 34,60 | 10 |   | 0,00 | 346,00 |   |   |  
400310-F - Plinthe 3'10 (1.150 M) | 5/9.975% | 20,22 | 30 |   | 0,00 | 606,60 |   |   |  

Maths are off for taxes by large numbers on all items. Never had such a problem before or did I? Makes me wonder...

**Comment by marclaporte** [comment]
@m10ust There has been work done in last few years on tax handling for Québec. Any chance you could test with latest Dolibarr version?

Thanks!

**Comment by hregis** [comment]
@marclaporte download and install the last version and try your request !
qu'est-ce que tu veux qu'on te dise de plus ?

**Comment by francksefu** [comment]
<img width="1084" height="672" alt="Image" src="https://github.com/user-attachments/assets/a3929f9d-8eb3-4607-8676-51b7aa7994ae" />


**Hello** @marclaporte, @hregis , @m10ust , I tested this issue in my Dolibarr instance (Dolibarr 22). As you can see, I created an invoice with the same products you provided, and my Dolibarr shows the same numbers as yours.

After analyzing, I found that Dolibarr first calculates the entire invoice excluding tax. Then, in a separate section, it calculates the tax related to the whole invoice, as shown in the image above.

<img width="1107" height="479" alt="Image" src="https://github.com/user-attachments/assets/f4df7448-f053-41fd-b5f2-576750a1f5de" />

On the generated PDF, you can see that the taxes are displayed and calculated after the table. Therefore, I believe Dolibarr did not make an error—it simply placed the figures in a slightly different position.

[SO2605-0003.pdf](https://github.com/user-attachments/files/27405494/SO2605-0003.pdf)
