### ISSUE TITLE
Accountancy code for VAT payments

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2567]
In module "Special expenses (tax, social contributions, dividends)"

Default setting for France: 445510

ping @aspangaro ;)

**Comment by aspangaro** [comment]
Thanks @rdoursenaud 

I take this feature request but not before two or three weeks.

The first step is also to replace all accountancy fields with a select list from chart of accounts. It's more user friendly.

**Comment by BebZ** [comment]
With a select list of a "personnalised" chart of accounts ? because to choose from default lists is a headache ;)

**Comment by aspangaro** [comment]
Hi @BebZ 

Charts of accounts is the same page than a dictionnary page, it's possibly to disable some accounts.

Maybe... To limit the problem, according to the field, it is necessary to display a list based on the class of account. If we are on the product, we show list only with the accounts of the class product (class 7 in France, not the same in different country).

**Comment by rdoursenaud** [comment]
@BebZ You should fill a separate feature request because of the broad spectrum and implications.

**Comment by aspangaro** [comment]
@rdoursenaud 

This feature request can be closed.
Referred to PR #3148 and PR #3149 (For Accountancy Expert)

Thanks

**Comment by rdoursenaud** [comment]
Very nice! You rule @aspangaro :+1:
