### ISSUE TITLE
Error when recording sales invoices in accounting

### ISSUE THREAD

**Issue by fanhtech** [Dolibarr/dolibarr#25674]
### Bug

Hello community,
I'm experiencing an error when recording sales invoices in accounting.
The product and third-party accounts are correctly configured. I don't charge vat and I don't use tax stamps. However, after having correctly linked the customer invoices when I try to record in accounting I get an error message.
It sems like during this operation, a revenue stamp line is automatically created and blocks the recording of the invoices.
Do you think this is a bug or an incorrect configuration? 
![img Erreur](https://github.com/Dolibarr/dolibarr/assets/94901405/50d2c749-004f-414c-ab1c-d4928d15a1c1)
![config société](https://github.com/Dolibarr/dolibarr/assets/94901405/9f6a26cc-95b5-495b-9b11-416ebc05bed5)
![Capture d’écran 2023-08-24 095324](https://github.com/Dolibarr/dolibarr/assets/94901405/d3af0409-14d3-438e-a443-4296b4ad7150)
 
Thank you for your help

### Environment Version

18.0.0

### Environment OS

Linux Debian 10

### Environment Web server

Apache 2

### Environment PHP

PHP 7.4.26

### Environment URL(s)

https://xxxxx/accountancy/journal/sellsjournal.php?id_journal=1

**Comment by ksar-ksar** [comment]
https://github.com/Dolibarr/dolibarr/commit/4fa0c037e060f1879d52fd273c65b1a8bf3e3614
