### ISSUE TITLE
add option in admin/mails.php - MAIN_EMAIL_SUPPORT_ACK

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#25678]
### Feature Request

Add option Oui/Non
I did not find any informations about depriciation of this option by mailer ?

### Suggested implementation

![image](https://github.com/Dolibarr/dolibarr/assets/3288514/20310bee-6c98-41cf-af17-af8a42e247c7)

**Comment by eldy** [comment]
See the analysis reported in PR #25679
