### ISSUE TITLE
BUG: Strange behaviour moving task in projects

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#2568]
Version 3.7

If you drag the task it can go above the title.
![screen shot 2015-04-08 at 17 54 11](https://cloud.githubusercontent.com/assets/1913498/7049250/6791e54e-de18-11e4-9f46-1bcecad99b76.png)

**Comment by rdoursenaud** [comment]
Confirmed :+1: 

Also happens in 3.6 current branch, _not_ in 3.5.

**Comment by braito4** [comment]
Also in the div total
