### ISSUE TITLE
phpcs check

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#25717]
It seems that phpcs now works with stricter rules and then blocking errors occur 
because of spaces at the end of a comment or tabs in empty lines.

**Comment by frederic34** [comment]
it runs with the sames rules than before (dev/setup/codesniffer/ruleset.xml) but a check is done in PR

https://github.com/Dolibarr/dolibarr/pull/25682

**Comment by dolibit-ut** [comment]
maybe a problem with files that have not been edited for longer time

**Comment by frederic34** [comment]
if test reports errors you have to fix them
https://github.com/Dolibarr/dolibarr/blob/9ce9eac595c687ae83b37cbeb8768c554e6fd9ad/dev/setup/codesniffer/ruleset.xml#L202-L207
