### ISSUE TITLE
Replace tab for tags/category with new select2 multiselect component

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#2571]
Replace tab for tags/category with new select2 multiselect component

For reference:
- [x] Products/services (done in f0b10c14d70d647e44022955e997c7637e9bc464)
- [x] Customers (cf #2932)
- [x] Suppliers (cf #3415)
- [x] Contacts (cf #3016)
- [x] Members
- [X] Bank transactions

**Comment by rdoursenaud** [comment]
For reference:
- [x] Products/services (done in f0b10c14d70d647e44022955e997c7637e9bc464)
- [ ] Customers
- [ ] Suppliers
- [ ] Contacts
- [ ] Members

**Comment by rdoursenaud** [comment]
I'm starting work on customers!

**Comment by rdoursenaud** [comment]
Starting work on contacts.

**Comment by rdoursenaud** [comment]
@eldy I took the liberty to edit your first post with the references. This way GitHub displays the remaining work nicely in the list of issues.
