### ISSUE TITLE
rounded VAT  + problem in limits and precison

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#25713]
### Bug

I'm so sorry to put this subject again in front of stage :-\

### First problem
For one of my client, I want to use MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND=2 (tva calculated and rounded on sums)

But it doesn't run as expected.

I examined the code of  update_price in commonobject.class.php

Even in mode 2, the sum of vat is calculated with sum of vat lines (rounded to 2 dec by default) That's seems to me unlogical.
I thought the total(s) vat should be calculated at the end using $total_ht_by_vats array * vat_rate, no ?

So I made another try : by setting MAIN_MAX_DECIMALS_TOT=5 (direct in db) the vat in lines in db aren't rounded, it's ok for my need, but ...

### 2nd problem
But in the backend, it's impossible to set MAIN_MAX_DECIMALS_TOT=5 and MAIN_MAX_DECIMALS_SHOWN=2, it throws an error and I don't understand why ? I think the test is inverted ?

see in /htdocs/admin/limits.php round line 95:
` if (! $error && ((float) $valmainmaxdecimalsshown < $valmainmaxdecimalsunit || (float) $valmainmaxdecimalsshown < $valmainmaxdecimalstot))` ...

### Environment Version

all

**Comment by hansemschnokeloch** [comment]
For the second problem, I made a comment on the relevant commit a while ago but it was apparently ignored 
https://github.com/Dolibarr/dolibarr/commit/509c85672e4f6510ff6dc6cc69146292280dcc2c#commitcomment-99154012

**Comment by Daviid-P** [comment]
> For the second problem, I made a comment on the relevant commit a while ago but it was apparently ignored [509c856#commitcomment-99154012](https://github.com/Dolibarr/dolibarr/commit/509c85672e4f6510ff6dc6cc69146292280dcc2c#commitcomment-99154012)

Same, https://github.com/Dolibarr/dolibarr/issues/24180

**Comment by vmaury** [comment]
Issue splited in 2 differents issues, #27273 and #27265
