### ISSUE TITLE
missing fields in LLX_tickets table 

### ISSUE THREAD

**Issue by Timoune974** [Dolibarr/dolibarr#25726]
### Bug

hello,
When, I create a new dolibarr instance somme fields are missing on ticket table. 

Indead, I have only 25 columns in the table instead 28, missing 

- date_last_msg_sent
- email_date
- ip

Dolibarr a détecté une erreur technique.
Ces informations peuvent être utiles à des fins de diagnostic (vous pouvez définir l'option $dolibarr_main_prod sur '1' pour masquer les informations sensibles):
Date: 20230830033751
Dolibarr: 17.0.3 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 8.1.22
Server: Apache/2.4.57 (Debian)
OS: Linux vpsdemo01 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 OPR/101.0.0.0

Url sollicitée: /dolidemotransport//ticket/list.php?search_fk_status=non_closed&idmenu=3&mainmenu=ticket&leftmenu=
Referer: https://www.lavarun.re/dolidemotransport/ticket/index.php?mainmenu=ticket&leftmenu=
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, ticket, agenda
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT t.rowid,t.entity,t.ref,t.track_id,t.fk_user_create,t.origin_email,t.subject,t.type_code,t.category_code,t.severity_code,t.fk_soc,t.notify_tiers_at_create,t.fk_project,t.datec,t.date_read,t.date_last_msg_sent,t.fk_user_assign,t.date_close,t.tms,t.message,t.email_msgid,t.progress,t.email_date,t.resolution,t.fk_statut,t.import_key FROM llx_ticket as t LEFT JOIN llx_societe as s ON (t.fk_soc = s.rowid) WHERE t.entity IN (1) AND (fk_statut IN (0,1,2,3,5,7)) ORDER BY t.datec DESC LIMIT 21
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 't.date_last_msg_sent' in 'field list'

### Environment Version

17.0.3

### Environment OS

linux

### Environment Web server

Apache/2.4.57 (Debian)

### Environment PHP

php 8.1 

### Environment Database

mariaDB

**Comment by ksar-ksar** [comment]
Hello,

I can't reproduce and the LLX_TICKET creation script seems to be OK : https://github.com/Dolibarr/dolibarr/blob/17.0.3/htdocs/install/mysql/tables/llx_ticket-ticket.sql

**Comment by Timoune974** [comment]
hello,  
ok I found the issue, I always have a file  llx_ticket.sql in my repository,  the format of the name of sql script changed for ticket module  an I didn't see it when I apply it on my template.
