### ISSUE TITLE
Replace "Réouvrir" by "Rouvrir"

### ISSUE THREAD

**Issue by OnyXxL** [Dolibarr/dolibarr#25735]
The word "Réouvrir" is incorrect in French. Instead, the word "Rouvrir" should be used.

_Sources :_
_[Académie française](https://www.dictionnaire-academie.fr/article/A9R3130) : "réouvrir" doesn't exist
[Larousse](https://www.larousse.fr/dictionnaires/francais/r%C3%A9ouvrir/68304) "Attention, dans l’expression soignée, et en particulier à l’écrit, on emploie rouvrir et non *réouvrir : le magasin a rouvert. En revanche, on dit la réouverture : la réouverture du magasin (et non la *rouverture)."_

Links to problematic files:

https://github.com/Dolibarr/dolibarr/blob/9ce9eac595c687ae83b37cbeb8768c554e6fd9ad/htdocs/langs/fr_FR/main.lang#L206
https://github.com/Dolibarr/dolibarr/blob/9ce9eac595c687ae83b37cbeb8768c554e6fd9ad/htdocs/langs/fr_FR/supplier_proposal.lang#L39
https://github.com/Dolibarr/dolibarr/blob/9ce9eac595c687ae83b37cbeb8768c554e6fd9ad/htdocs/langs/fr_FR/propal.lang#L61
https://github.com/Dolibarr/dolibarr/blob/9ce9eac595c687ae83b37cbeb8768c554e6fd9ad/htdocs/langs/fr_CA/admin.lang#L108
https://github.com/Dolibarr/dolibarr/blob/9ce9eac595c687ae83b37cbeb8768c554e6fd9ad/htdocs/langs/fr_FR/stocks.lang#L256
https://github.com/Dolibarr/dolibarr/blob/9ce9eac595c687ae83b37cbeb8768c554e6fd9ad/htdocs/langs/fr_FR/projects.lang#L131

**Comment by ksar-ksar** [comment]
Hello,

All the translations from English are made on https://explore.transifex.com/dolibarr-association/dolibarr/
You can create an account to modify it.

**Comment by aspangaro** [comment]
Hello,

I have fixed the french traduction for the term "Rouvrir".
Thanks for your return.

![image](https://github.com/Dolibarr/dolibarr/assets/2341395/cc0a5cd2-66ab-404b-bf23-be7dfbbf4dd1)
