### ISSUE TITLE
Shipping Adress (France Requirement)

### ISSUE THREAD

**Issue by lgeologic** [Dolibarr/dolibarr#25739]
### Feature Request

Hi, 
Thanks for adding the shipping adress part in invoices.
Nevertheless, is it possible to make it more conditionnal.
It's mandatory only if, the shipping adress is different from the invoice adress.
So here an idea : 

### Suggested implementation

- Call the first insert " Facturation et Livraison" ; but if in contact tab, there is an contact the shipping role then, call it "Facturation" and make a second insert "Livraison"?

**Comment by aspangaro** [comment]
Hello,

It's already ready, depending on your version of Dolibarr.

See this discussion on french forum:
https://www.dolibarr.fr/forum/t/factures-4-nouvelles-mentions-obligatoires-des-maintenant/41284/72

**Comment by lgeologic** [comment]
Ok, thank you for your reply.
I've tried in 17.3 and dev and it did not work ,but it does in 18
