### ISSUE TITLE
Bug: Clone product: Call to undefined method stdClass::check()

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#25748]
# Bug
[*Clone Error stdClass::check() in product/card.php:915*]

Fatal error: Uncaught Error: Call to undefined method stdClass::check() in /product/card.php:915

## Environment
- **Version**: 18.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.3.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /product/card.php?id=253

**Comment by ksar-ksar** [comment]
Duplicated of #25671 
FIX : #25675 

Will be availlable in V18.0.1
