### ISSUE TITLE
Rewrite module selection for a nicer tool

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#2574]
Merge all tabs for module and replace with an area with a badge for each module (one div per module)

<div>
------------------------<br>
| Module name    |<br>
| v1.0 - Category |<br>
|       Logo            | <br>
| More info link...  |<br>
|    Activated      |<br>
------------------------<br>
</div>

With at top, a search form with criteria:
Installed (checked by default)
Not installed (checked by default)
A combo list to filter on category
A search box to search on module name or description.

**Comment by rdoursenaud** [comment]
Related: #2573

**Comment by rdoursenaud** [comment]
A quick and dirty idea:
I think an optional "About" page for external modules would also be a nice addition for publishers.
This may even be standardised and parsed automatically to feed dolistore.

**Comment by eldy** [comment]
What you called the "About" is what i called the "More info link..." into the module badge. Idea is to output a popup with information inside the module descripor (what permission module brings, what table, what trigger and what hook. We could also add information of editor)

**Comment by rdoursenaud** [comment]
Ah, ok, I thought the "more info" was leading to the setup page.
So, may I ask where you envision the setup page link? On the module name?

**Comment by atm-maxime** [comment]
Hi @rdoursenaud ,

I'm reviewing old issues and I think this one can be closed. Is it ok ?

**Comment by rdoursenaud** [comment]
Hey @atm-maxime, the OP is @eldy, not me ;)
AFAIK, some of the features are not yet implemented (Search and filter…).

**Comment by eldy** [comment]
Search and filter were implemented in 5.0.
Still missing the "about" page. This is addressed by the property ->descriptionlong where editor can put html content but output of this page content must still be done into a dedicated popup.
