### ISSUE TITLE
Bank Statement Empty

### ISSUE THREAD

**Issue by DH88UK** [Dolibarr/dolibarr#25761]
### Bug

Bank account statement is empty.

I have an account statement with 3 entries, these are shown in the account entries tab and have been reconciled against the statement.

Clicking on the statement under the 'account statements' tab opens the statement but there are no entries.

Also, the balance shown does not match
<img width="1740" alt="Screenshot 2023-09-01 095830" src="https://github.com/Dolibarr/dolibarr/assets/58177104/8b557e59-da98-4c84-92e4-21e0a729ce41">
<img width="1742" alt="Screenshot 2023-09-01 095848" src="https://github.com/Dolibarr/dolibarr/assets/58177104/1973ee0a-afa1-45a7-91ff-b007b0059305">

### Environment Version

18.0

### Environment OS

DSM 7.1.1-42962 Update 6

### Environment Web server

Apache HTTP Server 2.4

### Environment PHP

8.0

### Environment Database

MariaDB 10.0

**Comment by AshleyButcher** [comment]
I have the same problem with 18.0.0 - looks like @eldy may have already fixed this a week ago with commit 19f85c65a2251a9ddc50b355294eb3045edfcb1b so it's possible this will be repaired in 18.0.1. The data is not lost, but it does make checking the opening and closing balance of a statement impossible at the moment.

**Comment by AshleyButcher** [comment]
Confirmed, this has been fixed in 18.0.1 - I can now see statements in the Dolibarr environments I manage after updating this evening.

**Comment by DH88UK** [comment]
Thanks, patched the file and its working as expected 👍
