### ISSUE TITLE
Timbre fiscal/stamp (sales) appears for no reason in sale journal

### ISSUE THREAD

**Issue by apio-sys** [Dolibarr/dolibarr#25764]
![Screenshot from 2023-09-01 10-39-12](https://github.com/Dolibarr/dolibarr/assets/26541964/c5c62ce1-55f6-476e-b0ab-abbe007e7663)
### Bug

When importing the sale journal as every month, a new line per invoice is added as "Timbre fiscal/stamp 'sales). This should only happen in certain countries as defined in llx_c_revenuestamp. My country is FR so should not be affected.

As a result, the sale journal of the month can no longer be imported, since errors out as follows:

Account (from the Chart of Account) for the revenue stamp (sales) not defined in setup
La valeur pour le compte comptable n'a pas été définie à la ligne (FA202308-0396, Compte comptable: NotDefined)

This behaviour is new since upgrade to 18.0.0 from 17.0.3 a few days ago.

### Environment Version

18.0.0

### Environment OS

Debian 11.7

### Environment Web server

Apache/2.4.56

### Environment PHP

7.4.33

### Environment Database

10.5.19-MariaDB-0+deb11u2 Debian 11

### Expected and actual behavior

Expected behaviour:

Comptabilité > Enregistrement en comptabilité > Vente (Sale journal) => Enregistrer les transactions en comptabilité => OK

Actual behavior:

Comptabilité > Enregistrement en comptabilité > Vente (Sale journal) => Enregistrer les transactions en comptabilité => Errors out with multiple:

"La valeur pour le compte comptable n'a pas été définie à la ligne (FA202308-0396, Compte comptable: NotDefined)"
On for each invoice.

### Steps to reproduce the behavior

Comptabilité > Enregistrement en comptabilité > Vente (Sale journal) => Enregistrer les transactions en comptabilité

### Attached files

Screenshot from 2023-09-01 10-39-12.png

**Comment by eldy** [comment]
Has been fixed for 18.0.1

**Comment by apio-sys** [comment]
Thanks Laurent for the quick fix. Can I apply it before the branch 18.0.1 becomes available?

**Comment by apio-sys** [comment]
I see 18.0.1 is avail. Just upgraded and confirm that this is fixed. Thanks again.
