### ISSUE TITLE
Redirecting to non-existent page when cancelling a line edit within a customer invoice

### ISSUE THREAD

**Issue by Okoss13** [Dolibarr/dolibarr#25779]
### Bug

When modifying a line inside a customer invoice the cancel button redirect to a 404 page.
Same problem in 18.0.0 and 18.0.1

### Environment Version

18.0.0 - 18.0.1

### Environment OS

Ubuntu 22.04 LTS

### Environment Web server

Apache/2.4.57

### Environment PHP

7.4.33

### Environment Database

MariaDB 10.11.5

### Environment URL(s)

/compta/facture/card.php?id={id}&action=editline&token={token}&lineid={lineid}

### Expected and actual behavior

Expected behavior : Return to the previous page to cancel the edit
Actual behavior : When clicking on the cancel button the page gets redirected to /compta/facture/3D{invoiceid}

### Steps to reproduce the behavior

When modifying a line inside a customer invoice the cancel button redirect to a 404 page.
You can reproduce this issue on demo.dolibarr.org

**Comment by loxK** [comment]
Confirmed, I have same issue on multiple installations of Dolibarr. (18.0.1 with Nginx and PHP 8.1.x)

**Comment by hregis** [comment]
@loxK @Okoss13 @eldy 
fix with https://github.com/Dolibarr/dolibarr/pull/25807
