### ISSUE TITLE
Miscellaneous payment in billing/payment is broken with PHP 8+

### ISSUE THREAD

**Issue by Okoss13** [Dolibarr/dolibarr#25780]
### Bug

The miscellaneous payment page appears blank when using PHP 8+ but works fine on PHP 7.4

### Environment Version

18.0.0 - 18.0.1

### Environment OS

Ubuntu 22.04 LTS

### Environment Web server

Apache/2.4.57

### Environment PHP

8.0 - 8.2

### Environment Database

MariaDB 10.11.5

### Environment URL(s)

/compta/bank/various_payment/list.php?leftmenu=tax_various&mainmenu=billing

### Expected and actual behavior

Expected behavior : The page should list all the recorded miscellaneous payments.
Actual behavior : The page is broken

### Steps to reproduce the behavior

/compta/bank/various_payment/list.php?leftmenu=tax_various&mainmenu=billing

### Attached files

![Screenshot_1](https://github.com/Dolibarr/dolibarr/assets/131163465/5a71e2fe-6ed4-457a-9ec8-b7bbd6f5fe9a)

**Comment by ksar-ksar** [comment]
Hello,

Can you provide the Apache Error log ?

Thanks.

**Comment by Okoss13** [comment]
Here the log :)

AH01071: Got error 'atal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /PATH/public_html/core/class/html.form.class.php:830\nStack trace:\n#0 /PATH/public_html/compta/bank/various_payment/list.php(427): Form->selectMassAction('', NULL)\n#1 {main}\n  thrown in /PATH/public_html/core/class/html.form.class.php on line 830', referer: https://domain/compta/bank/various_payment/list.php?leftmenu=tax_various&mainmenu=billing

AH01071: Got error 'PHP message: PHP Warning:  Undefined variable $toselect in /PATH/public_html/compta/bank/various_payment/list.php on line 370PHP message: PHP Warning:  Undefined variable $arrayofmassactions in /PATH/public_html/compta/bank/various_payment/list.php on line 427PHP message: PHP F', referer: https://domain/compta/bank/various_payment/list.php?leftmenu=tax_various&mainmenu=billing

**Comment by ksar-ksar** [comment]
Same issue there : https://www.dolibarr.fr/forum/t/resolu-jai-perdu-les-paiements-divers/44052
