### ISSUE TITLE
V18.0.1 : Cannot add time spent

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#25793]
### Bug

Cannot add time spent 

### Environment Version

18.0.1

### Environment OS

Debian 10.10

### Environment Web server

nginx 1.23.1

### Environment PHP

7.3.31

### Environment Database

PostgreSQL 13.12

### Environment URL(s)

/projet/tasks/time.php?action=createtime

### Expected and actual behavior

Expected : When user add time spent, everything is OK
Actual : When user add time spent, there is a crash and error message :
`ERREUR: 42P01: la relation « llx_element_time_rowid_seq » n'existe pas LINE 1: SELECT currval('llx_element_time_rowid_seq') ^ LOCATION: RangeVarGetRelidExtended, namespace.c:435`

### Steps to reproduce the behavior

Go to a project
Choose time spent
Click on add time
Choose values and submit

### Attached files

Before add time spent
![2023-09-05_093419](https://github.com/Dolibarr/dolibarr/assets/11213740/559a92d9-c72c-4ff2-b7de-6ac5dec9f1dd)

After submit
![2023-09-05_093813](https://github.com/Dolibarr/dolibarr/assets/11213740/ed921ab7-a36c-4f61-a286-fdebae293973)

**Comment by ludovicandrieux** [comment]
To resolve this issue, you can apply SQL commands directly in PostgreSQL:
```sql
CREATE SEQUENCE public.llx_element_time_rowid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.llx_element_time_rowid_seq OWNER TO <your_username_of_owner>;

ALTER SEQUENCE public.llx_element_time_rowid_seq OWNED BY public.llx_element_time.rowid;

ALTER TABLE ONLY public.llx_element_time ALTER COLUMN rowid SET DEFAULT nextval('public.llx_element_time_rowid_seq'::regclass);

SELECT nextval('llx_element_time_rowid_seq');

SELECT pg_catalog.setval('public.llx_element_time_rowid_seq', (SELECT max(rowid)+1 FROM llx_element_time), true);

SELECT currval('llx_element_time_rowid_seq');
```
You have to change this part : <your_username_of_owner>

**Comment by symacx** [comment]
Hello Ludovic,

Indeed, it fixes the issue.
Thank you !
Olivier.
