### ISSUE TITLE
Accountancy option use date of payment instead date of invoice

### ISSUE THREAD

**Issue by hanneshier** [Dolibarr/dolibarr#25792]
### Feature Request

Add an option to use the (actual) payment date of an invoice instead of the invoice date in the Accountancy Module. This is needed for some types of simplified accountancy.

### Use case

For small businesses and and associations in Germany, there is an option to use the simplified Einnahmen-Überschuss-Rechnung/EÜR ([Cash method of accounting](https://en.wikipedia.org/wiki/Cash_method_of_accounting)) for taxation. The flow of cash is the important date, not the invoice date.

### Suggested implementation

Add a (hidden) option to only transfer invoices that have been paid into accountancy, and use the payment date for the transaction.

**Comment by dolibit-ut** [comment]
hello, 
maybe it helps you if you try at first the option  INVOICE_POINTOFTAX_DATE

**Comment by hanneshier** [comment]
Thanks for the reply, I didn't know about that option. But it does not seem to work it that case anyways. I could not find any real documentation, but from what I found in a quick test, this does only effect outgoing invoices, and not the supplier invoices. But most importantly, it does not take effect in the accountancy module.

![Screenshot 2023-09-07 at 19 08 28](https://github.com/Dolibarr/dolibarr/assets/11063798/ecdae4eb-ff4e-4019-bbbe-f7534754c87f)
![Screenshot 2023-09-07 at 19 08 38](https://github.com/Dolibarr/dolibarr/assets/11063798/0ec7cc55-8a39-417e-bd53-2670071fbc26)

**Comment by aspangaro** [comment]
Hello,

Dolibarr currently has commitment accounting.

There are no plans to integrate cash accounting at present. You can use the following module to meet your needs : [Dolistore](https://www.dolistore.com/fr/modules/1211-Comptabilit---de-tr--sorerie.html?search_query=tresorerie&results=11)

If you need some informations : Email to support AT open-dsi DOT fr

**Comment by hanneshier** [comment]
Hi @aspangaro, 
I've sent an email, but didn't get an answer yet, so I try it here. I have a few questions regarding the Treasury accounting module:
- What languages are supported by the module? Is there an English or a German demo version available.
- Is it integrated with the membership module?
- Is it integrated with the donations module?
- Is the accounting part of the Double Entry Accounting module or is the module separate from that?
