### ISSUE TITLE
Bad display duration enter data on intervention

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#2579]
Version 3.7

![screen shot 2015-04-09 at 10 48 16](https://cloud.githubusercontent.com/assets/1913498/7063342/2a78617c-dea6-11e4-8368-5031ca73e289.png)

**Comment by rdoursenaud** [comment]
@braito4 can you please confirm @marcosgdf fix is working for you?

**Comment by braito4** [comment]
Yes it's fixed. Works fine

**Comment by rdoursenaud** [comment]
Thanks :)
