### ISSUE TITLE
Module to suggest payment with caisse d'épargne

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#2580]
Need a module to suggest payment with caisse d'épargne (copy of paybox module but using the societe general API)
Also the callback must record the payment of invoice (currently the paybox module receive the callback but do nothing with it)
This will save a lot of time of foundation board team

**Comment by hregis** [comment]
i can make it

**Comment by BebZ** [comment]
i have the paybox module with magento 
and all the documentation if you are interested, or do you still have it ?

**Comment by rdoursenaud** [comment]
Please don't fall into old habbits of copy/pasting and refactor it to share as much code as possible.
Understanding, debugging and generally maintaining copy/pasted code is a nightmare.

**Comment by jfefe** [comment]
There is a version working with SystemPay (used by Caisse d'épargne) : https://git.aternatik.net/dolibarr/systempay

**Comment by rdoursenaud** [comment]
@simnandez Any reason you removed the labels on this issue?

**Comment by simnandez** [comment]
@rdoursenaud Yes, a regression in the labels reorganization

**Comment by eldy** [comment]
No more required
