### ISSUE TITLE
Object linked with external module

### ISSUE THREAD

**Issue by atm-quentin** [Dolibarr/dolibarr#25816]
### Bug

When you link an element to an external module you have a module prefix : https://github.com/Dolibarr/dolibarr/blob/94950bee7d08417bee1b36f13dc78839552ac9e0/htdocs/core/class/commonobject.class.php#L3849

But when we read it we're just checking element : 
https://github.com/Dolibarr/dolibarr/blob/94950bee7d08417bee1b36f13dc78839552ac9e0/htdocs/core/class/commonobject.class.php#L3965
What would be the good way to solve this ?

### Environment Version

18.0

**Comment by atm-quentin** [comment]
@eldy

**Comment by eldy** [comment]
If the property ->module is defined into the objeft class, id to define an element is modulename_objectname
If property is not defined, it should be objectname only. Recent module should have ->module defined.
