### ISSUE TITLE
Authentication not possible to send mail with SMTP/SMTPS socket library

### ISSUE THREAD

**Issue by AlbanDurrheimer** [Dolibarr/dolibarr#25822]
### Bug

Hello,  

Since I switched to Dolibarr 18, no mail (notification, error...) can be sent. Before, it worked perfectly.  
When I try to send a mail from the test tool, I get the following error:  
```
Failed to send mail (sender=xxxx <xxxx@xxx.xx>, receiver=xxxx@xxx.xx)
Error [120]: Ran into problems sending Mail. Response: 535 5.7.1 Authentication failed Error [130]: Invalid Authentication Credentials.
```

### Log
```
2023-09-06 14:02:01 DEBUG   172.18.0.1      CMailFile::CMailfile: charset=UTF-8 from=xxxx <xxxx@xxx.xx>, to=xxxx@xxx.xx, addr_cc=, addr_bcc=, errors_to=, replyto= trackid=test sendcontext=standard
2023-09-06 14:02:01 DEBUG   172.18.0.1      CMailFile::CMailfile: subject=Test, deliveryreceipt=, msgishtml=-1
2023-09-06 14:02:01 DEBUG   172.18.0.1      CMailFile::CMailfile: sendmode=smtps addr_bcc=, replyto=xxxx <xxxx@xxx.xx>
2023-09-06 14:02:01 DEBUG   172.18.0.1      CMailFile::sendfile: sendMsg, HOST=ssl://ssl0.ovh.net, PORT=465
2023-09-06 14:02:11 WARNING 172.18.0.1      CMailFile::sendfile: mail SMTP error code 535
2023-09-06 14:02:11 ERR     172.18.0.1      CMailFile::sendfile: mail end error with smtps lib to HOST=ssl://ssl0.ovh.net, PORT=465 - Error [120]: Ran into problems sending Mail.
``` 

### Environment Version

18.0.1 (with docker image: Docker tuxgasy/docker-dolibarr:18)

### Environment OS

Debian Buster

### Environment Web server

Apache

### Environment PHP

8.1

### Environment Database

mariadb 11.1.2

### Expected and actual behavior

Mails to be sent without errors.

**Comment by ksar-ksar** [comment]
Server answer is : Invalid Authentication Credentials
Do you try to re-enter Credentials on the email module ?

Could be linked to the warning in the changelog : 

> Sensitive datas like keys in setup pages, that need encyption (for example the API keys of users, the CRON security key, the keys into the Stripe module, or 
> external modules setup pages that store sensitive keys or password), are using the $dolibarr_main_instance_unique_id as part of the key for encryption. So,
> if you restore or duplicate the data from another instance dump, you must also update this parameter in ther conf.php file to allow decryption in the new instance, or 
> better, you must reenter the sensitive data into the setup pages of the new instance to resave them correctly.
> Note that to find all the parameters that are encrypted into the setup database, you can do a "SELECT * FROM llx_const WHERE value LIKE '%dolcrypt%';"

**Comment by AlbanDurrheimer** [comment]
Thank you for your reply.  

> Do you try to re-enter Credentials on the email module

Yes, I've already tried re-entering the email credentials as well as testing with the SMTP configuration of another email address hosted with another provider. But in both cases, it didn't work.  

I've also tried using "swift mailer socket library" instead of "SMTP/SMTPS socket library" without any improvement.

**Comment by ksar-ksar** [comment]
Ok,

And do you have a $dolibarr_main_instance_unique_id defined in conf.php?

**Comment by AlbanDurrheimer** [comment]
No, that's right!  
I hadn't seen the warning, because it's not in the release changelog...  
Thank you @ksar-ksar
