### ISSUE TITLE
odt Generator Problem wrong colors and styles

### ISSUE THREAD

**Issue by tronx2100** [Dolibarr/dolibarr#25828]
### Bug

When generating odt it happens wrong and mixed styles and colors when using html code.

To Fix this we need to change line 299 ff.

from $key = floatval(str_replace('.', '', microtime(true))) + rand(0, 10);

$key = str_replace('.', '', microtime(true)) . uniqid() . rand(0, 10); // fixed by tronx2100 

now it will work perfect without errors.

### Environment Version

18.0.1

### Environment OS

linux debian bookworm

### Environment Web server

nginx

### Environment PHP

8.2.7

**Comment by a-schild** [comment]
The file to change it is

includes/odtphp/odt.php, line 299 (also in 18.0.4)
