### ISSUE TITLE
Unable to update User

### ISSUE THREAD

**Issue by naskio** [Dolibarr/dolibarr#25833]
### Bug

When trying to update a user (for example the Gender from male to female), I get the error: Identifier already exists.

### Environment Version

18.0.1

### Environment OS

Linux Server

### Environment Database

Postgres

### Expected and actual behavior

I should be able to update an existing user.	

### Steps to reproduce the behavior

- Create a new User.
- Try to update the User.
- Click save.
- See the error: Identifiant existe déjà.

**Comment by Technick-1** [comment]
Same config, same problem. Dolibarr project is now on pause because of this bug.

**Comment by atm-maxime** [comment]
I tried with the 18.0.2 from Github and I can't reproduce. A user update works fine.

**Comment by naskio** [comment]
@atm-maxime as mentioned, the problem happened in version 18.0.1.

**Comment by atm-maxime** [comment]
@naskio and has been fixed apparently because no longer happens in next minor version

**Comment by naskio** [comment]
@atm-maxime Great, thanks. 
I am waiting for the release of version 18.0.2 in [docker-dolibarr](https://github.com/tuxgasy/docker-dolibarr).

**Comment by apple9004** [comment]
Partially, there is an issue where user information cannot be changed or deleted.
I backed up the db from Dolibarr 17.0.2 and migrate to Doli 18.0.2.
The probelm is the old users, who are created at Doli 17.0.2, are **NOT** modified or removed. 
(The users created at Doli 18.0.2 are OK. )
