### ISSUE TITLE
stripe link related to generated invoice pdf

### ISSUE THREAD

**Issue by tanguychenier** [Dolibarr/dolibarr#25835]
### Bug

in pdf_sponge_modules.php 
missing argument for the mode :
`$paiement_url = getOnlinePaymentUrl('', 'invoice', $object->ref, '', '', '');`
ref will allways be null and printed pdf ref will too.

Exemple:
`$paiement_url = getOnlinePaymentUrl(0, 'invoice', $object->ref, '', '', '');`

in core/libs/paiments.lib.php :
```
...
elseif ($type == 'invoice') {
		$out = $urltouse.'/public/payment/newpayment.php?source='.$type.'&ref='.($mode ? '<span style="color: #666666">' : '');
		if ($mode == 1) {
			$out .= 'invoice_ref';
		}
		if ($mode == 0) {
			$out .= urlencode($ref);
		}
```
actually : 
`$paiement_url = getOnlinePaymentUrl('', 'invoice', $object->ref, '', '', '');`
The first argument to `getOnlinePaymentUrl` in `pdf_sponge_modules.php`, which is `$mode`, will never give a valid reference because `''` is defined and not an expected `$mode` defined by the `payment_url logic` in `pdf_sponge_modules.php`

### Environment Version

18.0.1

### Environment OS

Debian

### Environment PHP

8.2.1

**Comment by thomasb22** [comment]
This bug exist since Dolibarr 17.0.x, I think.

**Comment by Nashbore** [comment]
Is there any solution?

**Comment by Nashbore** [comment]
It looks like PHP version compatibility, I have issues with PHP V8.1, The stripe payment link on invoice does not work, However, with PHP 7.4, it works fine!!!.

**Comment by tanguychenier** [comment]
Interesting.
Good to know.

**Comment by Nashbore** [comment]
I have tried several time PHP 8 and the payment link is incomplete. Same process I repeated with PHP 7.4. It worked all the time. the payment link printed on the PDF is complete and works! It could be the compatibility or Database Driver. I am using Maria Data base, which is fully compatible to Mysql.So try yourself rolling back to PHP 7.4

**Comment by thomasb22** [comment]
I confirm than with a first parameter at 0 the link is good:

```
$paiement_url = getOnlinePaymentUrl(0, 'invoice', $object->ref, '', '', '');
```

But I don't know if is useful to create a mode variable…
