### ISSUE TITLE
Display of addresses (sender and recipient) with unintentional space

### ISSUE THREAD

**Issue by EmergyCH** [Dolibarr/dolibarr#25836]
### Bug

Display of addresses (sender and recipient) on PDF documents with unintentional? space if the address field has two lines (same with the address of the issuing company)  

### Environment Version

18.0.1

### Environment PHP

7.4

### Environment Database

MySQL

### Steps to reproduce the behavior

Create a costumer (or edit compagny details) with min. 2 adress lines and generate a PDF

![ksnip_20230907-173159](https://github.com/Dolibarr/dolibarr/assets/22157096/fa2c81b2-d039-4a54-a67d-cf5400b063c0)
![ksnip_20230907-173130](https://github.com/Dolibarr/dolibarr/assets/22157096/a32db75b-b7a3-4830-bbe6-7490184f0a10)

**Comment by leonbrehme** [comment]
Same here. I tested on a fresh install. (PHP 8.1)

The error has something to do with line breaks. I added a empty second line.
If you don't fill in any line breaks, it work fine.

Update: Works well on version 17.0.2

![image](https://github.com/Dolibarr/dolibarr/assets/115941074/fc480827-4a2c-488b-ae0d-8f8f3a13220a)

**Comment by sebastien-prudhomme** [comment]
Bug introduced by this commit: https://github.com/Dolibarr/dolibarr/commit/5e4102386217e9f4dc5e9dac66046ae35cf4e9b3

Regex '/[\n\r]/' replaces the string '\r\n' by '\n\n' when using default separator.

Maybe use this regex: '/\r\n|\n|\r/'

@eldy do you remember the purpose of this regex replace?

**Comment by hregis** [comment]
@sebastien-prudhomme @EmergyCH @leonbrehme 

it's fixed https://github.com/Dolibarr/dolibarr/pull/26085
