### ISSUE TITLE
additional spaces in innertext after <br /> in odf.php

### ISSUE THREAD

**Issue by tronx2100** [Dolibarr/dolibarr#25841]
### Bug

After <br> inodt pdf generation we have a leading space because <br \> instead of <br> tag so we need to ltrim the text to fix it . the next line will then not start with a space

change in odf.php in line 369 ff.

					array_push($tags, array(
						'text' => substr($tempHtml, 0, $tagOffset)
					));

to

					array_push($tags, array(
						'text' => ltrim(substr($tempHtml, 0, $tagOffset)) 
					));

will fix this bug

### Environment Version

18.0.1

### Environment OS

linux debian bookworm

### Environment Web server

nginx

### Environment PHP

8.2.7

### Environment Database

mariadb

**Comment by lucky4ever2** [comment]
I have exactly the same problem. Thank you for the provided solution. It works for me as well. Hopefully, the developers will incorporate this into the code.
