### ISSUE TITLE
Feature request: A tool to scan language files from not used language keys

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#2584]
Build a command line tool that report key into en_US lang files that are not used into code and report them into a file.

**Comment by marcosgdf** [comment]
I think there is already a FR made by you for this exact thing in Doliforge:

https://doliforge.org/tracker/?group_id=144&func=detail&atid=247&aid=300

**Comment by eldy** [comment]
Yes, but because we will just drop the doliforge for task and bug report, i just recopy it on new tool.

**Comment by novalore** [comment]
[DevCamp 2015]We're working on the issue this morning with  @tbasilici .
The idea is to have a tool that is able to detect duplicate as well as unused language keys (in en_US files by default).
