### ISSUE TITLE
Can't access to documents folder

### ISSUE THREAD

**Issue by OzanYDZ51** [Dolibarr/dolibarr#25873]
### Bug

Hello,

I'm actually in my custom module page, i would like to get an image from documents folder

![image](https://github.com/Dolibarr/dolibarr/assets/25532852/01041f50-6063-4232-a76b-d91f51d4148c)

I can't access to this image by any way because it's in documents folder and my website "localhost" is routing to htdocs folder.

Any idea please ?

Thanks.

**Comment by ksar-ksar** [comment]
Hello,

Sorry, but it's quite difficult to understand what you want.
What do you mean by Image ?

**Comment by OzanYDZ51** [comment]
It's ok, i found the solution with $viewimage, thanks.
