### ISSUE TITLE
Feature Request: SEPA Credit Transfer

### ISSUE THREAD

**Issue by IonAgorria** [Dolibarr/dolibarr#2587]
Hello, my idea is to implement SEPA credit transfers for supplier invoices in same or similar way as 
"Standing orders" (prevelent) module in customer invoices, the idea was to change or copy current code for suppliers.

After looking the standing orders code I am quite worried about the state of code, and I'm questioning
if it's better to do it from ground instead of trying to fix non translated stuff, old code, etc

Previously I made a SEPA credit transfer module for dolibarr (https://github.com/IonAgorria/sepadolibarr) 
using an old version of this library (https://github.com/AbcAeffchen/Sephpa) obviously the GUI would be similar to "standing orders" as is much more complete than the module, but the actual SEPA generation code might be translated to that library which has support for both credit transfers and direct debit.

I'm open to any suggestion, hints and improvements about how to do this, if just only do the credit transfer part and leave the current standing order code or try to use the same library for both...

as a sidenote I find the SQL table, classes and some functions names confusing and sould be refactored or replaced. Also the prevelement module uses 4 or 5 tables which 3 of them don't have their corresponding class.php file, The pages access them directly IIRC and results hard to track the workings of each table

**Comment by rdoursenaud** [comment]
Hi @IonAgorria,

Thanks for your interest in contributing to Dolibarr.

History have proved that factoring existing code is almost always easier and more valuable than rewriting from scratch.

AFAIK The preferred way for refactoring Dolibarr code is to PR small readable changes into the develop branch. @eldy may chime in to fill in more details.

SQL table name changes are not to be taken lightly though because of the great impact it can have on out-of-tree modules and should always be documented in great details ensuring a smooth upgrade path.

Any improvements are very welcome and built-in SEPA capability sounds awesome!

**Comment by IonAgorria** [comment]
And what about using the mentioned library for generating both direct debit and credit transfer while refactoring the rest of code?
That would imply to replace the current direct debit generator code, but having a common library for both would be nice.

**Comment by rdoursenaud** [comment]
Nothing against an external library to manage such excruciating things as SEPA details.

Refactoring existing code to keep duplication away is certainly the path to follow!

**Comment by IonAgorria** [comment]
My approximated plan is:
- move those SQL Select in pages to classes
- separate code for each table in their corresponding class (at this moment for example lignes has no CRUD methods, bons class accesses the lignes table...) 
- create tables and classes for transfers (Im not still sure if to make them similar to prevelement ones)
- use the pages and add some way for switching classes between prevelement and transfer versions
- replace prevelement sepa generation with library

Where should be the sepha library go?
