### ISSUE TITLE
How to generate a file

### ISSUE THREAD

**Issue by OzanYDZ51** [Dolibarr/dolibarr#25881]
Hello,

I'm trying to generate a custom pdf file programmatically by this way : 
![image](https://github.com/Dolibarr/dolibarr/assets/25532852/43a212b4-d2d3-488d-adea-593d30755237)

But i'm not able to access to documents folder from inside the htdocs folder which is my localhost path (with my router)

Any way to do this properly please ?

Thanks,
Best regards.

**Comment by dolibarr95** [comment]
Hello

https://www.dolibarr.org/forum.php

**Comment by atm-maxime** [comment]
Remove ../documents/ and use $entity in your path

**Comment by hregis** [comment]
@OzanYDZ51  try this :

```
$filename = uniqid() . 'client.pdf';
$folderPath  = $conf->societe->multidir_output[$object->entity].'/'.$object->id;
$file = $folderPath.'/'.$filename;
addFileIntoDatabaseIndex($folderPath, $filename, '', 'uploaded', 1);
```

**Comment by hregis** [comment]
@OzanYDZ51  try this :

```
$filename = uniqid() . 'client.pdf';
$folderPath  = $conf->societe->multidir_output[$object->entity].'/'.$object->id;
$file = $folderPath.'/'.$filename;
$pdf->Output($file, 'F');
addFileIntoDatabaseIndex($folderPath, $filename, '', 'generated', 0, $object);
```

**Comment by OzanYDZ51** [comment]
Oh thanks guys :) ! working fine ;)
