### ISSUE TITLE
When creating a new user you cannot define a pasword begining with a symbol [SOLVED]

### ISSUE THREAD

**Issue by caos30** [Dolibarr/dolibarr#25886]
### Bug

Hi again, @eldy, i found (and solved) this other bug which has take to me 2 hours to debug and find the cause!! The solution is an absolute stupid change on an IF condition ... 😅

On `/user/card.php` file (Dolibarr 18.0) line #356 appear this:
```
$id = $object->create($user);
if ($id > 0) {
$resPass = 0;
if (GETPOST('password', 'none')) {
	$resPass = $object->setPassword($user, GETPOST('password', 'none'));
}
if ($resPass < 0) { // <------- THIS IS THE WRONG CONDITION TO FIX
	$langs->load("errors");
	$db->rollback();
	setEventMessages($object->error, $object->errors, 'errors');
	$action = "create"; // Go back to create page
} else { ...
```
Which cause a ROLLBACK when the password (returned by `$object->setPassword`) is "minor than zero"... for example a password like `!1234` or `.1234` !! So the new user is not being added to database.

I got the solution in other part of the same file: replace the current condition
```
if ($resPass < 0) {
```
by this other condition:
```
if (is_numeric($resPass) && $resPass < 0) {
```
Please, Eldy, can you add it to the code of that file? 😁 

Thanks! I saw now that you already did it for the issue/fix i added 2 hours ago. I'm testing today the compatibility of my module TOTP2FA (on Dolistore) with Dolibarr 18, and i'm finding these issues. And i like to do a little of effort to collaborate to make better Dolibarr... obviously!!! Although we all are in debt with you! Have a nice day.  

### Environment Version

Dolibarr 18.0

**Comment by hregis** [comment]
@caos30 https://github.com/Dolibarr/dolibarr/pull/25887

**Comment by caos30** [comment]
Oh, yes, that commit is quite more complete than my fix! Excellent. Thanks @hregis. I close this issue then. Let me know if you need i do something else.

**Comment by caos30** [comment]
I close it.

**Comment by caos30** [comment]
I close this issue.

**Comment by caos30** [comment]
I close this issue.
