### ISSUE TITLE
Add user in script mailing-send.php

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2589]
If sending a mailing, the tag **SIGNATURE** will not be replaced by user sigature, as it is when sending mailing from IHM.
This is not coherant.
Insoure we find 
'**SIGNATURE**' => '',  // Signature is empty when ran from command line (user is a bot)

why not giving a user login as a parameter to script, so this tag can be replaced ?
Or setting a variable in configuration. 

email sending is limited in IHM (thats OK), and user are encouraged to use script. So this is a little confusing

**Comment by tiaris** [comment]
here a forum discussion

http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/52846-attribut-signature-dans-l-envoi-de-courriels

**Comment by rdoursenaud** [comment]
Closed by #2634
