### ISSUE TITLE
Ticket Module - Add New Message - Attach File Uploads File but DOES NOT Attach to Ticket

### ISSUE THREAD

**Issue by carmelchas** [Dolibarr/dolibarr#25906]
### Bug

Dolibarr version 16.0

When trying to attach a file to a Ticket it does not get linked to the ticket despite being uploaded successfully.

The issue is that the "Add Message" form submits the request with parameter "track_id" but the following file is looking for "trackid".

htdocs/core/actions_sendmails.inc.php

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

### Environment Version

16.0

### Environment OS

Ubunto

### Environment Web server

Apache2

### Environment PHP

PHP 7.x

### Environment Database

10.11.3-MariaDB-1 - Debian 12

### Expected and actual behavior

Ticket should be linked to the uploaded file.

### Steps to reproduce the behavior

1.  From Ticket card click "Add a Message" button.
2. In the add message form at the bottom of the page click the "Choose file" button.
3. Click the "ATTACH THIS FILE" button.

### Attached files

Debug test code in file  [dolibarr/htdocs/core/actions_sendmails.inc.php]
<img width="709" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/445543/07825235-64e6-4892-80c4-3e23cf2ab506">

Debug Log Output identifying the GETPOST parameter name mismatch.
<img width="753" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/445543/71056782-d986-4e69-bb6c-49d79986d1e2">

**Comment by freechelmi** [comment]
I can confirm this , very annoying. 

I will test on 17 soon

**Comment by carmelchas** [comment]
Dolibarr v.18 allows you attach a file to an existing Ticket.  However, it DOES NOT attach a file uploaded during ticket creation.

**Comment by carmelchas** [comment]
The file attachment stuff appears to be working in Dolibarr v.18
