### ISSUE TITLE
Bill several shipments for a customer with one invoice

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2590]
As it is done for orders, it would be fine to have the possibility to create one inoice for several shippments fo a special customer.

http://www.dolibarr.fr/forum/15-retours-dexperiences-utilisateursintegrateurs/52821-lier-plusieurs-expeditions-dans-la-meme-facture

**Comment by atm-maxime** [comment]
FYI, there's our module doing exactly this functionality : https://www.dolistore.com/fr/autres/381-Exp--dition-facturable-3-4-3-5.html

We can discuss it during devcamp if you want :)

Several options are available and subtotal module can be used with too.

Regroup shipments in one invoice
Adds title and subtotal for each shipment (need subtotal module)
Keep invoice as draft or automatically validate it (and generates PDF)
Generate a global PDF with all invoices generated
Retrieve services from the original order (if services are not present in shipment)

**Comment by rdoursenaud** [comment]
@atm-maxime would you be so kind as to integrate you module upstream? :p
Also any useful devcamp discussion to report?

**Comment by atm-maxime** [comment]
@rdoursenaud I think we'll integrate this module in Dolibarr core soon. But it uses subtotal module too...
@tiaris didn't asked me about this topic during devcamp so no discussion to report.

**Comment by BebZ** [comment]
@rdoursenaud @atm-maxime @tiaris 
A future 6.0 good news for this functionnality ?
Anyway if you don't expect to integrate, is it worth it to buy it, woud you provide a long term support for such a "small" module ?
