### ISSUE TITLE
Empty line in the address field - Invoice and PDF documents

### ISSUE THREAD

**Issue by Studio3Points** [Dolibarr/dolibarr#25908]
### Bug

![issue dolibarr](https://github.com/Dolibarr/dolibarr/assets/42969476/6b0bb75c-aece-4fbb-bb8a-04884d703173)

As the print screen above, there is an unknown empty line in the middle of the address

### Environment Version

18.0.1

### Environment OS

Apache

### Environment Web server

Apache

### Environment PHP

8.0.3

### Attached files

![issue dolibarr](https://github.com/Dolibarr/dolibarr/assets/42969476/a8a82937-23df-4b5c-ba99-f22c4f3e3043)

**Comment by erwinpalma** [comment]
I have found where to enable that info.

Go to **Home->Setup-PDF** and the **enable the option** _Show professional ID with addresses - Prof Id 1 (R.F.C). - Third-party address_

![image](https://github.com/Dolibarr/dolibarr/assets/30660343/eb6a3106-87f5-435c-a3e8-87acb47e6fa3)

**Comment by Studio3Points** [comment]
This problem happens when have 2 lines in the address field (company information and customer information), I tried to write only one line and the problem disappear. 
![Dolibarr address](https://github.com/Dolibarr/dolibarr/assets/42969476/337027bb-8cb4-45b2-ba83-704dca5eea69)

**Comment by sebastien-prudhomme** [comment]
Same bug as #25836
