### ISSUE TITLE
OpenID creates user and sync groups

### ISSUE THREAD

**Issue by battosai30** [Dolibarr/dolibarr#25922]
### Feature Request

Hi,

So cool that OpenID comes up :)

To be complete (in my point of view) two features are missing : 

- Create new user if it doesn't exist in Dolibarr database : like a lot of other softwares, when you link your solution to an OpenID server (or any ID server) you do not want to have to create user in your solution. You want it to be created automatically (and it's not a safety issue as your ID server is considered as safe). 
- Groups synchronization : also a good feature when you have and ID server is to manage users, groups and roles from a single tool. So it would be cool if groups could be synchronized like with LDAP module so users would be in the same groups as they are on OpenID server.

Thanks !

### Use case

User select "Connect with OpenID" on login screen. If login is succesfull, user account is created in Dolibarr if it doesn't exist.
When a user login, groups membership are synchronized.

### Suggested implementation

functions_openid_connect.php seems the good place :) 
I'm not a good php dev and I don't have the time during next weeks to try something but the request is done  at least :)

**Comment by Soushi888** [comment]
We made a PR for this issue (https://github.com/Dolibarr/dolibarr/pull/37314). We integrated the auto creation logic, but kept group syncing and avatar handling for other PRs. At least we have the grounds set !

**Comment by marclaporte** [comment]
@battosai30 This issue should be re-opened.
