### ISSUE TITLE
in da_DK language one permission text says read, but it is write

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr#25924]
### Bug

in da_DK language one permission text says read, but it is write.

It is under "Vare varianter" (product variations?)

The 2. permission text is: "Læs attributter for varianter" but when you click on the little i on the right it says:
"ID 611
User->Rights->Variants->Write"

And "Læs" means read. Perhaps also notice that the line above ID 610 the text is in English.

### Environment Version

18.0.1

### Environment OS

linux container from upshift (running in podman)

### Environment Web server

Probably apache inside the container, but I have a nginx as a proxy infront

### Environment PHP

PHP 8.2.10 (cli) (built: Aug 31 2023 20:34:52) (NTS)

### Environment Database

mariadb from 11.1.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper

### Environment URL(s)

/user/group/perms.php?id=3&action=addrights&token=_-TOKEN-REDACTED-_&entity=1&rights=611&confirm=yes&page_y=9715

### Expected and actual behavior

I would expect that the text would say "Opret/rediger attributter for varianter"

**Comment by JonBendtsen** [comment]
oops, forgot to add the file :-(

**Comment by ksar-ksar** [comment]
Thanks, but all the translations issues should be done here : https://explore.transifex.com/dolibarr-association/dolibarr/

**Comment by JonBendtsen** [comment]
@ksar-ksar  I now think that the error is actually somewhere else, because even in en_US there is the same kind of error, it says Read twice. And when I mouse over the little i it says that the 2. read is actually a write and that the 3. is actually delete. It also says 610, 611 and 612.

Looking at line 909 in https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/langs/en_US/admin.lang
```
Permission611=Read attributes of variants
Permission612=Create/Update attributes of variants
Permission613=Delete attributes of variants
```

it seems that the numbers are 1 off somewhere compared to above?

![variant_permission_all3](https://github.com/Dolibarr/dolibarr/assets/2551481/e04858b5-2769-413e-848b-c0e52b1ad801)
![variant_permission_read](https://github.com/Dolibarr/dolibarr/assets/2551481/1720827f-a7f3-4be4-9ab8-b4dfcf619708)
![variant_permission_wread](https://github.com/Dolibarr/dolibarr/assets/2551481/527b88ee-674d-48e4-9403-c1d09fc32db9)
![variant_permission_delete](https://github.com/Dolibarr/dolibarr/assets/2551481/caa5180e-3081-4ff7-843d-e6b9ad74ab01)


I tried writing 611 in line 49 in
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/modules/modVariants.class.php
```
		$this->numero = 610;
```
but it didn't seem to remove the 2 read lines in a row, and I ended up with the mess seen in the last picture and I figured I'd better report it to you.


![variant_permission_mess](https://github.com/Dolibarr/dolibarr/assets/2551481/0a3fbf9d-7a57-4a66-83c0-36221f8f4835)
