### ISSUE TITLE
error on api_proposals.class.php

### ISSUE THREAD

**Issue by fernandomacho** [Dolibarr/dolibarr#25929]
### Bug

if call to endpoint 
/api/index.php/proposals/xxxxx/lines without sql filter
this generate an exception
The line 319 of file htdocs/comm/propal/class/api_proposals.class.php
say:
$this->propal->getLinesArray($sql); 
and $sql is not set 
this line would set into if at line 311
if (!empty($sqlfilters)) {

### Environment Version

18.0.1

### Environment OS

Ubuntu 22.04

### Environment Web server

Nginx

### Environment PHP

8.2

### Environment Database

mariadb 10

### Expected and actual behavior

2023/09/15 13:02:57 [error] 704889#704889: *47475930 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $sql in /xxxxx/htdocs/comm/propal/class/api_proposals.class.php on line 319" while reading response header from upstream, client: xxx.xxx.xxx.xx, server: xxxxxxxt, request: "GET /api/index.php/proposals/nnnnn/lines HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "xxxxxxx"

### Steps to reproduce the behavior

curl -X GET --header 'Accept: application/json' --header 'DOLAPIKEY: xxxxxx' 'https://xxxxxxx/api/index.php/proposals/nnnnnn/lines'

**Comment by atm-maxime** [comment]
Fix pending approval
