### ISSUE TITLE
incorrect link in google agenda export

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2592]
Whn exporting dolibarr agenda to googel calendar, the link for a third party seems to be false (submitted y user of forum)
http://www.dolibarr.fr/forum/507-agenda/52657-lien-vers-google-calendar

link is http://siteweb/htdocs/societe/soc.ph?socid=263 inste of http://siteweb/htdocs/societe/soc.php?socid=263

**Comment by marcosgdf** [comment]
Can you please be more specific like... which version is affected and how to reproduce it?

**Comment by eldy** [comment]
This is a bug into the module Google, not into dolibarr. Will be fixed into next module version of module google released just after 3.7 release.

**Comment by rdoursenaud** [comment]
I think this kind of issues would benefit from an "invalid" tag.
My 2 cents~
