### ISSUE TITLE
ODT {object_total_..._x} v 17.0.3

### ISSUE THREAD

**Issue by michalhana99** [Dolibarr/dolibarr#25932]
### Bug

When trying to generate a sum of a specific VAT rate in the odt file, the sum is not generated, but only {object_total_vat_20} remains here

I tried:
  {object_total_vat_20}
{object_total_vat_20.000}
{object_total_vat_20.00}

and also for other VAT assessments, but the specific sum will not appear in the document

I am attaching a test file

### Environment Version

17.0.3, 16.0.3

### Environment PHP

8.1

### Expected and actual behavior

[template_invoicetest.odt](https://github.com/Dolibarr/dolibarr/files/12620296/template_invoicetest.odt)

### Steps to reproduce the behavior

Create an odt file where you specify the specific VAT rate to be added.
Have this document generated, for example an invoice.
Where {object_total_vat_20} is should contain the sum of the rows that contain 20% VAT
  {object_total_vat_20}
{object_total_vat_20.000}
{object_total_vat_20.00}

**Comment by priojk** [comment]
I just tried to reproduce this on 17.0.3, just changed it to the 19% VAT we are using here. The result for the keys is as follows:

3229.05
{object_total_vat_19.000}
{object_total_vat_19.00} 

So the first version worked as expected.

What might have happened in your template is that you either corrected something in the key or used copy/paste. In this case, LibreOffice might have added invisible data for internal version history which makes the placeholder key undetectable for dolibarr.

Could you try to select your keys and remove all formatting with this button 
![image](https://github.com/Dolibarr/dolibarr/assets/10772984/756e813c-1953-453b-b247-5d78136bc81d)
 in LibreOffice?

**Comment by michalhana99** [comment]
Hello, I had to first edit it in notepad and then insert it into LibreOffice.

Unfortunately, only "{object_total_vat_19}" works for me, but e.g. "{object_total_ht_x}" no longer works.

**Comment by KlaasOl** [comment]
Hi, 
Tested with the percentage of 21.5% and no problem with the format {object_total_vat_21,5}
If there is only one digit, I put in my variable , (comma!) 5, (No dot)
For an percentage of 21.25% it also works. I used a comma, not a dot in the variable.
So it looked like: {object_total_vat_21,25}

**Comment by michalhana99** [comment]
Thanks, but how can i get the **ht** or **ttc** rating there?

**Comment by KlaasOl** [comment]
The only way to get de VAT rate in a variable is in the table-line: {line_vatrate}.
At the bottom of an invoice you have to "hard" edit it as: VAT 25% = {object_total_vat_25}

**Comment by fappels** [comment]
object_total_ht_x does not exist, only object_total_ht
