### ISSUE TITLE
Note privée visible par tous les utilisateurs sur dolibarr V17.2

### ISSUE THREAD

**Issue by sacko32** [Dolibarr/dolibarr#25933]
### Bug

Bonjour
Nous rencontrons un problème sur la V17.2 , les notes privées des utilisateurs sont visibles par tous les autres utilisateurs.
un gros problème de confidendialité sur la notre plateforme actuellement.
<img width="497" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/102553732/67d52d25-2873-45f1-a825-d6ce16830af1">

Aviez vous une idée de la source du problème ? 

### Environment Version

V17.2

### Environment OS

linux

### Environment Web server

Apache

### Environment PHP

 8.0.28

### Environment Database

10.5.19-MariaDB-cll-lve

**Comment by atm-maxime** [comment]
The private note is not made to be private for the user, but for the customer. The public note is shared to the customer because it's printed in the pdf, the private note remains in Dolibarr, shared within the company.
