### ISSUE TITLE
Merge Greek (el_GR) into Greek (el_CY) in Transifex

### ISSUE THREAD

**Issue by sonikf** [Dolibarr/dolibarr#25945]
Hi @eldy 
Greek (el_CY) is unmaintained and not translated in Transifex.
Since Greek (el_GR) is fully translated it would be usefull to merge Greek (el_GR) into Greek (el_CY) and if there are any subtle differences in terms, then it would be easier for any Greek Cypriot to step up and fix them.

**Comment by eldy** [comment]
> Hi @eldy 
> Greek (el_CY) is unmaintained and not translated in Transifex.
> Since Greek (el_GR) is fully translated it would be usefull to merge Greek (el_GR) into Greek (el_CY) and if there are any subtle differences in terms, then it would be easier for any Greek Cypriot to step up and fix them.

There is no need to have el_CY complete in transifex. Only string that differs from el_GR is required because there isna fallback into dolibarr : if string not translated in el_CY then we use el_GR
