### ISSUE TITLE
Bug - URL not found when cancelling edit on an order line

### ISSUE THREAD

**Issue by AshleyButcher** [Dolibarr/dolibarr#25942]
### Bug

If you edit an order line, but then press the Cancel button, you are taken to an invalid URL (`/commande/3Dnnnn` where `nnnn` = the order number)

### Environment Version

18.0.1

### Environment OS

Debian 12.1

### Environment Web server

Apache 2.4.57

### Environment PHP

7.4.33

### Environment Database

MySQL 8.0.33

### Expected and actual behavior

Expected: When you press cancel on an order line, you are returned to the order properly as per previous versions of Dolibarr.

Actual: You are taken to an invalid URL

### Steps to reproduce the behavior

1. Create an order
2. Add a line to the order (save it)
3. Click the pencil to edit the line
4. Click the cancel button
5. Observe: The browser is directed to an invalid URL

**Comment by leonbrehme** [comment]
I tested the bug: same here.
It seams to appear on any line item. I tested it on invoices, proposals and orders.

If you save the line, all fine. But if you cancel the changes you will be sent to a "404 page". The URL is the same as on Ashley-Butchers discription: .../comm/propal/3D<number>

My test was done on a fresh installation of 18.0.1

**Comment by fappels** [comment]
@leonbrehme Can you add:
/*var_dump($cancel);var_dump($backtopage);var_dump($backtopageforcancel);exit;*/
before line 164 on htdocs/comm/propal/card.php and check dump output

**Comment by AshleyButcher** [comment]
@fappels for me if I do this for a proposal I get this response (for proposal with ID `12`):

`string(6) "Cancel" string(4) "3D12" NULL`

**Comment by hregis** [comment]
@fappels @Ashley-Butcher it's already fixed and merged in https://github.com/Dolibarr/dolibarr/pull/25807/files
