### ISSUE TITLE
Bug - 500 server error generating sponge invoice PDF with high number of payments on invoice

### ISSUE THREAD

**Issue by AshleyButcher** [Dolibarr/dolibarr#25943]
### Bug

When using the `sponge` invoice template, generating an invoice PDF for an invoice with a high number of payments (i.e. 60) yields a 500 internal server error.

This occurs when we handle invoices paid in instalments, i.e. 50-60 payments, and we need to generate an invoice with a payment statement attached so the customer can see their payment history.

The `crabe` template is not impacted and generates correctly.

### Environment Version

18.0.1 (also older versions)

### Environment OS

Debian 12.1

### Environment Web server

Apache 2.4.57

### Environment PHP

7.4.33

### Environment Database

MySQL 8.0.33

### Expected and actual behavior

Expected: The PDF is generated with the payments listed

Actual: a 500 internal server error is generated

### Steps to reproduce the behavior

1. Create an invoice with a number of lines (i.e. 20 lines)
2. Create incremental payments on the invoice, i.e. 50-60 payments
3. Generate a PDF for the invoice using the `sponge` template
4. Observe: 500 internal server error returned

**Comment by ksar-ksar** [comment]
Hello,

Erroe 500 means php error = Can you provide the PHP logs ?

**Comment by AshleyButcher** [comment]
@ksar-ksar Woops yes I was going to include this detail but I forgot to come back to this after the bookkeeping was done :)

The important bit in the log for the PDF generation:

`[Sun Sep 17 11:57:37.733756 2023] [proxy_fcgi:error] [pid 517345] [client XXXX] AH01071: Got error 'PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/XXXX/htdocs/includes/tecnickcom/tcpdf/tcpdf.php on line 21279', referer: https://XXXX/compta/facture/card.php?facid=4930&action=confirm_paid_partially&confirm=yes&token=XXXX&close_code=other&close_note=Round-off`

Important to note, increasing the memory limit to 1 GiB, 2 GiB, etc. still results in the same problem, so some sort of infinite loop perhaps, but I haven't had a chance to look closer. It's been an issue for a few years now, I just haven't gotten around to logging the bug.

**Comment by ksar-ksar** [comment]
Hello,

Try to increase the PHP memory_limit, 256MB seems not enough

**Comment by leonbrehme** [comment]
I tryed to recreate the error: I added the payments manually. It works all fine for the first 39 payments. But when i enter the 40th one, I also get an 500 error.
