### ISSUE TITLE
various payment list error on php 8.x

### ISSUE THREAD

**Issue by funsurfer2008** [Dolibarr/dolibarr#25949]
### Bug

if i change php from 7.4 to 8.x the various payments are not displayed anymore.

### Environment Version

18.0.1

### Environment OS

Linux srv04.ms-hosting.local 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64

### Environment Web server

Apache/2.4.57 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1n

### Environment PHP

8.x

### Environment URL(s)

https://erp.a-square.at/compta/bank/various_payment/list.php?leftmenu=tax_various&mainmenu=billing

### Expected and actual behavior

Expected: show list of payments
actual: no list

**Comment by funsurfer2008** [comment]
![image](https://github.com/Dolibarr/dolibarr/assets/59434775/026befb0-99b3-46b7-a92f-6e6573252d28)

**Comment by leonbrehme** [comment]
If the other modules are working maybe you need to adjust your user rights.

**Comment by funsurfer2008** [comment]
> If the other modules are working maybe you need to adjust your user rights.

Maybe you need to learn how to reed a description:
"if i change php from 7.4 to 8.x the various payments are not displayed anymore." has nothing to do with user rights

**Comment by leonbrehme** [comment]
But the other core modules are working? Do you have any third party modules installed working the various payments?

**Comment by funsurfer2008** [comment]
No, i dont have installed other third party modules. it is working under php 7.4 but not under 8.x

**Comment by leonbrehme** [comment]
Just to be clear: The other modules are working fine.

**Comment by funsurfer2008** [comment]
i had not looked into detail. but at the first view i would say so

**Comment by fappels** [comment]
Seems to be fixed here: #25861
