### ISSUE TITLE
isExistingObject fails on ActionComm due to rowid vs id

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#25952]
https://github.com/Dolibarr/dolibarr/blob/65a2761a83981c48cb4efdf586efc94a5e1e482c/htdocs/core/class/commonobject.class.php#L737-L742

`llx_actioncomm` uses `id` as column name instead of `rowid` so the `isExistingObject` function always returns false even if the object does exist.

I think there are more tables with id instead of rowid too.

<strike>I think rowid should be replaced with `$this->table_rowid`</strike>

Nevermind, method is static.

```php

public static function isExistingObject($element, $id, $ref = '', $ref_ext = '')
	{
		global $db, $conf;

		$id_column_name = 'rowid';
		if ($element == 'actioncomm') {
			$id_column_name = 'id';
		}

		$sql = "SELECT $id_column_name, ref, ref_ext";
		$sql .= " FROM ".$db->prefix().$element;
		$sql .= " WHERE entity IN (".getEntity($element).")";

		if ($id > 0) {
			$sql .= " AND $id_column_name = ".((int) $id);
		} elseif ($ref) {
			$sql .= " AND ref = '".$db->escape($ref)."'";
		} elseif ($ref_ext) {
			$sql .= " AND ref_ext = '".$db->escape($ref_ext)."'";
		} else {
			$error = 'ErrorWrongParameters';
			dol_print_error(get_class()."::isExistingObject ".$error, LOG_ERR);
			return -1;
		}
		if ($ref || $ref_ext) {		// Because the same ref can exists in 2 different entities, we force the current one in priority
			$sql .= " AND entity = ".((int) $conf->entity);
		}

		dol_syslog(get_class()."::isExistingObject", LOG_DEBUG);
		$resql = $db->query($sql);
		if ($resql) {
			$num = $db->num_rows($resql);
			if ($num > 0) {
				return 1;
			} else {
				return 0;
			}
		}
		return -1;
	}

```

Searching for `table_rowid ?=` in vscode I can only find `actioncomm.class.php`, is that the only case?

**Comment by hansemschnokeloch** [comment]
Question is: why do we have here `id` instead of `rowid`, for one single class.
Best solution seems to be to get rid of this oddity in order to simplify the whole code.
@eldy is there any particular reason why  `llx_actioncomm` uses `id` and not `rowid`?

**Comment by Daviid-P** [comment]
I think `id` was the original and it's been changed to `rowid` everywhere else, like how columns in French are being changed to English.
This one must've slipped through.
