### ISSUE TITLE
Filter for late proposals ,projects etc. is not working properly 

### ISSUE THREAD

**Issue by pmr94209** [Dolibarr/dolibarr#25963]
### Bug

If you click at the mainpage in the different boxes shwoing the number of items for example Proposals on the yellow marked box for late items the filter won´t work except for suplier invoices and invoices

**Comment by leonbrehme** [comment]
Hi, thanks for the issues but could you provide at least the version of your Dolibarr installation?

**Comment by pmr94209** [comment]
Yes , sorry the version is 18.0.1.

**Comment by leonbrehme** [comment]
I'm sorry. I tried to reproduce the error, but it was not possible. The filters are applied correctly.

**Comment by pmr94209** [comment]
If you go on the dolibarr demo at dolibarr.org https://demo.dolibarr.org/public/demo/ an login and the click on the startpage the late projects, which are curretly 92 and the click on the number 92 the opcoming page shows 540 projects and not just the 92 which are overdue , see enclosed pics 
<img width="2353" alt="Bildschirmfoto 2023-09-22 um 16 23 28" src="https://github.com/Dolibarr/dolibarr/assets/38521120/7dbebc66-046c-4318-bf63-5d8042899db4">
<img width="2345" alt="Bildschirmfoto 2023-09-22 um 16 23 18" src="https://github.com/Dolibarr/dolibarr/assets/38521120/3f1194a0-4769-43fc-bbb3-353f215f06d5">
<img width="2353" alt="Bildschirmfoto 2023-09-22 um 16 23 04" src="https://github.com/Dolibarr/dolibarr/assets/38521120/62d51127-f4cd-4f45-9e0a-efbf0ac068b0">

**Comment by leonbrehme** [comment]
I've investigated: your were right. It's not working for projects because they don't have the option to filter for overdue (today after enddate). For the invoices there is a filter option. So maybe this needs to be feature request.

![Screenshot 2023-09-22 16 50 28](https://github.com/Dolibarr/dolibarr/assets/115941074/dcbfbe93-fb75-41a7-a0a3-16c3e0957ef3)

**Comment by pmr94209** [comment]
In the past versions 11.x it did work for example for quotations or orders  which are overdue. Now it does only work for invoices anymore

**Comment by leonbrehme** [comment]
Do you know at witch version it stops? As fare as I now, there was a change in the way there filters were built. Maybe this feature was lost during the harmonization. Right know I don't have any other idea.

Could you provide me a list of all lists where you miss the feature? Then we can create a new issue for the fix. From my point if view it would be the best to create a new feature request, as this not a bug right know - but a missing features (that was lost).

Thank you for your help :)

**Comment by pmr94209** [comment]
Unfortunately i have no idea at which version it was lost. 
It does not work anymore with any of the items except invoices and supplier invoices. In all other items like Agenda, orders etc. the filter does not work anymore. So is there a difference in the filter for the invoices and supplier invoices compared to other documents ?

**Comment by leonbrehme** [comment]
"So is there a difference in the filter for the invoices and supplier invoices compared to other documents ?" yeah there is. It's just not build in.

I wrote a feature request to add the filter option for alert.
https://github.com/Dolibarr/dolibarr/issues/26056

Add things if i missed some :)
