### ISSUE TITLE
Move notes for Expense Reports to an individual tab

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2596]
![captura de pantalla 2015-04-12 a las 21 39 04](https://cloud.githubusercontent.com/assets/168744/7107176/848015ee-e15c-11e4-89f8-0d62caf932b0.png)

**Comment by BebZ** [comment]
why so much hate of the Notes on the page, it makes a clic less when we want to edit it.
and users forget less to fill it when it's already in front of their eyes. Except if the field is mandatory.

**Comment by aspangaro** [comment]
This module is deprecated in 3.8. A new module called Expense Report is present.

**Comment by rdoursenaud** [comment]
I agree with @aspangaro. This module being deprecated, I don't believe it's wise to invest in it.

**Comment by eldy** [comment]
Old module is deprecated but new module has same behaviour for notes.

**Comment by ghost** [comment]
@eldy Done, sould be close, in 7.0 notes are in separates notes
