### ISSUE TITLE
Orders to process main menu bug

### ISSUE THREAD

**Issue by nagoz** [Dolibarr/dolibarr#25973]
### Bug

In the main menu, when I click on Orders (Commandes in French),
![image](https://github.com/Dolibarr/dolibarr/assets/6176810/fcfcc418-e664-4300-9983-527f2436c468)
the link go to 
https://myserver/commande/list.php?search_status=-3&mainmenu=commercial&leftmenu=orders
instead of
https://myserver/commande/list.php?search_status=-2&mainmenu=commercial&leftmenu=orders
In the code, the search_status is set in hard.

### Environment Version

17.0.3

### Environment Web server

Hosted

### Environment Database

MySQL

**Comment by soerpoers** [comment]
same for me. version is 18.01

**Comment by tiaris** [comment]
right pull request made for more consistancy between widget and pointed list (version 17-18)
https://github.com/Dolibarr/dolibarr/issues/25973
