### ISSUE TITLE
Bug - Cannot create payment mode dictionary entry - "Field 'entity' is required"

### ISSUE THREAD

**Issue by AshleyButcher** [Dolibarr/dolibarr#25983]
### Bug

Since 18.0.x it's no longer possible to create a payment mode (under `/admin/dict.php?id=13`). An error is shown: `Field 'entity' is required`

### Environment Version

18.0.x

### Environment OS

Debian 12.1

### Environment PHP

7.4.33

### Environment Database

MySQL 8.0.33

### Expected and actual behavior

Expected: Payment mode is created

Actual: Payment mode cannot be created as Dolibarr is not populating the mandatory `entity` database field correctly.

### Steps to reproduce the behavior

In an environment with no additional modules (i.e. no multicompany support added):

1. Navigate to the "Payment modes" dictionary page (`/admin/dict.php?id=13`)
2. Create a new payment mode, i.e. code `TEST`, label `Test`, type `Payment Type - Customer and Vendor`, click 'ADD"
3. Observe: Error is shown: `Field 'entity' is required`

**Comment by AshleyButcher** [comment]
It's worth noting that there is an unlabelled field that has been added to this screen when you add a payment mode which allows you to specify the entity ID. It's not obvious, and it allows you to put anything in there you like. You can even put text in there, and it will create the record.

Using the scenario described in the reproduction steps, no matter what you put in this mystery field the record will then be created correctly with the entity set to `1` as you would expect.

This behaviour is unexpected and does not match the user's experience, especially since the field is not even marked with a title, leaving the user baffled as to what they have done wrong when creating the payment mode.

**Comment by tiaris** [comment]
pull request with correction sended https://github.com/Dolibarr/dolibarr/pull/26004

**Comment by hregis** [comment]
@tiaris i always send a fix with this PR https://github.com/Dolibarr/dolibarr/pull/26001

**Comment by sonikf** [comment]
@ksar-ksar 
This is fixed in 18.02

**Comment by AshleyButcher** [comment]
@sonif Confirmed. I'll close this out myself. Thanks :)
