### ISSUE TITLE
defined currency of customer is not populated on card.php

### ISSUE THREAD

**Issue by evansgl** [Dolibarr/dolibarr#25982]
### Bug

A customer has been configured with e.g USD currency but the card.php does not select the correct currency.
 

### Environment Version

18.0.1

### Environment OS

RHEL

**Comment by sonikf** [comment]
Ηι @evansgl can you elaborate a little bit..path of card.php, a screenshot maybe

**Comment by AshleyButcher** [comment]
I've tested this in an environment which uses **EUR** as the company currency, with a customer who has **GBP** set as their default currency.

My observations:
 - When creating an invoice from the customer record directly, the currency code **GBP** is correctly applied on the new invoice page (`/compta/facture/card.php?action=create&socid=nnn`) - this is copied over to the draft invoice.
 - When creating an invoice from the billing/payment page (i.e. "new invoice" - `/compta/facture/card.php?action=create`), the currency is set to **EUR** as expected, but when specifying the test customer account the currency switches to **GBP** correctly.

I can't reproduce this based on the information provided.

**Comment by evansgl** [comment]
The invoice works fine but a **new sales order does not.** It does not automatically select the selected currency of the customer and keeps the default option (in my case is EUR)
The bug seems to be in the order section. (commande/card.php?action=create)
Any other field is populated correctly such as "Payment Terms"
