### ISSUE TITLE
Period selecting in accounting personalized groups  reporting goes wrong

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#26011]
### Bug

It is not possible to select a part of a year in personalized groups. It always display the whole year. 

### Environment Version

already from 16.x

### Environment OS

Linux Ubunty 22.04.01

### Environment Web server

Apache

### Environment PHP

7.4.33

### Environment Database

MySQ L8.0.34

### Expected and actual behavior

Normal selection of a period

**Comment by eldy** [comment]
Can you provide a screenshot of the concerned page ?
