### ISSUE TITLE
PHP Streams - Dolibarr's Recommandation 

### ISSUE THREAD

**Issue by K-razy** [Dolibarr/dolibarr#26026]
### Bug

Hi,

I've just installed Dolibarr succesfully, and I was looking for hardening the solution.
So I Went into Section Admin Tools --> About Security
There is a line showing recommandation about available streams which should be active.

![image](https://github.com/Dolibarr/dolibarr/assets/62814529/797e242d-be24-4dfc-8e5d-a474fba0b9b5)

I wanted to configure it but, it seems not that easy.
I'm aware about the function `stream_wrapper_unregister` i put in a file which Apache Rights and running it by calling the page whether with a curl ou via browser.

It doesn't do anything.
I tried with php 8.1, php7.4, still the same issue.

Could you please help me figure this recommendation out ?

Thanks in advance

Kind Regards

### Environment Version

18.0.1

### Environment OS

Debian 12.1

### Environment Web server

Apache 2.4.52

### Environment PHP

8.1 or 7.4

### Environment Database

Mariadb 10

**Comment by priojk** [comment]
Please ask your general questions regarding Dolibarr in the forum: https://www.dolibarr.org/forum/

**Comment by K-razy** [comment]
Hi, sorry then i'm closing this request
