### ISSUE TITLE
Stock decrease problem when invoiced

### ISSUE THREAD

**Issue by abhimanyumohan** [Dolibarr/dolibarr#2602]
I have a major issue with dolibarr. Our client has two warehouses, when invoicing , the products are taken from two warehouses. But while validating,the stock decreases from only one warehouse. How is possible to change this feature. Please help

**Comment by rdoursenaud** [comment]
You certainly don't want stock to be decreased from the two warehouses at once. That would mean you remove 2 products from your inventory each time you sell 1.

**Comment by abhimanyumohan** [comment]
The first situation  

I have a product name X. When Invoicing , I am going to add 10 numbers of product X from 1st warehouse and 5 numbers of products X from 2nd warehouse. so when invoice is validated, It just asks for reducing it from any one of the warehouse. So later we have to manually correct stock again. which is quite troubling and time consuming.

Second Situation:
Product X and product Y . X is in warehouse 1 and Y in warehouse 2. When Invoicing, It can be deducted only from 1 warehouse. Product Y will show a minus stock in Warehouse 1 if the warehouse 1 is selected for stock decrease. Isn't there any other way of reducing it? So the stock has to be managed manually, which is quite easier in doing it in an excel sheet rather than doing it through dolibarr.

**Comment by BebZ** [comment]
use orders and manual ventilation of supplier's and customer's orders, no ? 
If you want to keep track of stocks it's the only way I guess.
Or the Excel sheet.

**Comment by rdoursenaud** [comment]
Thanks, I understand the use case better now.

Automatically decreasing stock from multiple warehouses is not supported currently. You have to make separate invoices for each warehouse or manage stock manually.

Looks like you'd want to be able to select the warehouse the product has been taken from when inserting the lines.

This way it could work for the two use cases. Just insert two lines of the same product but from different warehouses for the first case.

Sounds like a reasonable feature request to me but might be cumbersome for huge invoices.

**Comment by simnandez** [comment]
You must use the Shipments module and make orders and  corresponding shipments (you can decreasing product stock from multiple warehouses in the shipments). After you can make the invoice of complete order.

**Comment by rdoursenaud** [comment]
Thanks for the insight @simnandez. I didn't think of that option.

Would this fit your workflow @abhimanyumohan?

**Comment by rdoursenaud** [comment]
No answer in more than two months: closing.
