### ISSUE TITLE
Bug :  Not possible to filter by Products tags in Supplier invoices listing

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#26032]
# Bug
When trying to filter on product tags/categories in the table listing of Suppliers invoices, it is not possible to do, it does not show up any result at all, while it works fine in Client invoices and in Supplier order.

## Environment
- **Version**: 18.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 8.1.23
- **Database**: MySQL or MariaDB 10.5.19-MariaDB-0+deb11u2
- **URL(s)**: /azert/htdocs/fourn/facture/list.php

**Comment by hasse-basse** [comment]
This issue is still present in 19.0.1

**Comment by hregis** [comment]
@hasse-basse try with this fix https://github.com/Dolibarr/dolibarr/pull/29074

**Comment by hasse-basse** [comment]
Wonderful, it works !
Thanks !
