### ISSUE TITLE
Aborting a value change in a document leads to a dead end / error page

### ISSUE THREAD

**Issue by Basti-Fantasti** [Dolibarr/dolibarr#26044]
### Bug

When modifying an item in a document (e.g. invoice) it's not possible to abort the change.

Saving works fine, but aborting leads to this page:

![grafik](https://github.com/Dolibarr/dolibarr/assets/1663072/e8cc80f3-a977-4754-a2fe-b1bb8d1ebe36)

### Environment Version

18.0.1

### Environment OS

Ubuntu 22.04

### Environment Web server

Apache 2

### Environment PHP

PHP 8.1

### Environment Database

MySQL

### Expected and actual behavior

Option to save or abort the changes

### Steps to reproduce the behavior

- add an item to an invoice
- click the pencil button to modify the entry
- press **Abort** button

**Comment by hregis** [comment]
@Basti-Fantasti it's already fixed with https://github.com/Dolibarr/dolibarr/pull/25807
and will be included with v18.0.2
