### ISSUE TITLE
we can't disable $conf->global->MAIN_PROFID1_IN_ADDRESS 

### ISSUE THREAD

**Issue by atm-quentin** [Dolibarr/dolibarr#26045]
### Bug

Basically, this is the test performed in master.inc.php (i.e. each time a Dolibarr page is loaded):

    if ($mysoc->country_code == 'FR' && !isset($conf->global->MAIN_PROFID1_IN_ADDRESS)) {
        // For FR, default value of option to show profid SIRET is on by default
        $conf->global->MAIN_PROFID1_IN_ADDRESS = 1;
    }

The problem is in admin/pdf.php  that when you deactivate a conf with ajax on off ( e MAIN_PROFID1_IN_ADDRESS ), it deletes the element from the table and doesn't set it to 0, so the !isset test is true even though you've forced the value to 0.

What corrective action should be taken? Make ajax contantonoff.php set const to 0 instead of del ?

### Environment Version

17

### Environment PHP

7.4

### Steps to reproduce the behavior

Try to disable MAIN_PROFID1_IN_ADDRESS in admin/pdf.php and reload page to see the conf is still enable

**Comment by atm-quentin** [comment]
@eldy

**Comment by atm-thibaultf** [comment]
@eldy

**Comment by eldy** [comment]
Defaut behaviour is to not have a constant defined when value is 0 into llx_const, it works for 99% of cases so we must NOT change the ajaxconstinoff and find a solution to keep this rule (and reach 100%)

For compatibility purpose, when we introduced the option, we add a test to !isset for france so for old instance when option not defined, the option is automatically set. I think we must remove this completely the special case, to force to 1 the option for france.
So what rule is the option on or off.
And to have option on fornfrance automatically, instead i suggest to set the value to 1 when we set the country to fr into the setup of company. So if user set fr, with no knowledge and implicitly, the option is correctly set by default, but if user want to change after explicitly, it remains possible.

**Comment by atm-lucasmantegari** [comment]
If I understand, you have to force the conf to 1 for France and be able to modify it in the confs later?  @eldy

**Comment by eldy** [comment]
> If I understand, you have to force the conf to 1 for France and be able to modify it in the confs later?  @eldy 

We have to force option to 1 when we set the country on france, then we remove the part of code "if france..." that force the value if option not defined.
So we are able to edit the option.
