### ISSUE TITLE
Dolibarr V.18  - Ticket Module Bug SQL Syntax Error 

### ISSUE THREAD

**Issue by carmelchas** [Dolibarr/dolibarr#26052]
### Bug

Dolibarr V.18 introduces a new error in the Ticket module.

dolibarr/htdocs/ticket/class/ticket.class.php
LINE: 1287

function loadCacheCategoriesTickets

### Environment Version

18.0

### Environment OS

Ubuntu

### Environment Web server

Apache2

### Environment PHP

PHP 7.x

### Environment Database

10.11.3-MariaDB-1 - Debian 12

### Expected and actual behavior

SQL Syntax error not expected.

### Steps to reproduce the behavior

Visit the public ticket create page.

### Attached files

<img width="826" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/445543/93cacd5d-a799-4710-a347-cd7eaccf1b54">

<img width="953" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/445543/58403380-7f7f-4bd2-8d32-38e15d08b99f">

<img width="1351" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/445543/28f2d482-2b14-477c-84e4-092977655021">

**Comment by aspangaro** [comment]
https://github.com/Dolibarr/dolibarr/commit/72b995d568113bf56b9f58834813fff2d3828ab0
