### ISSUE TITLE
In Accounting > Reporting, if I click on a month expenses, the dates are incorrectly loaded

### ISSUE THREAD

**Issue by xabitrigo** [Dolibarr/dolibarr#26050]
### Bug

I want to go Accounting > reporting and click on a month to see the details of that month.

It goes to this url: /compta/resultat/clientfourn.php?year=2023&month=6&modecompta=CREANCES-DETTES

But the first date of the reporting period is a year in the future and I don't see the data

### Environment Version

18.0.1

### Environment OS

CloudLinux 7.x Linux hl109.lucushost.org 3.10.0-962.3.2.lve1.5.77.el7.x86_64 #1 SMP Mon Dec 12 07:06:14 EST 2022 x86_64

### Environment Web server

LiteSpeed

### Environment PHP

7.4.33

### Environment Database

MySQL or MariaDB 10.6.11-MariaDB-cll-lve

### Environment URL(s)

/compta/resultat/clientfourn.php?year=2023&month=6&modecompta=CREANCES-DETTES

### Expected and actual behavior

To load the detailed expenses for the month 6 of the year 2023

### Steps to reproduce the behavior

- Go to Accounting > Reporting
- Click on a month's detail

### Attached files

<img width="503" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/7525839/8a2aaf52-10fa-4ae6-8376-54c439626af5">

**Comment by xabitrigo** [comment]
I think the file `compta/resultat/clientfourn.php` has something wrong in lines:

81
```php
$year_start = $year - $nbofyear + (getDolGlobalInt('SOCIETE_FISCAL_MONTH_START') > 1 ? 0 : 1);

``` 

92 
```php
$year_end = $year_start + $nbofyear - (getDolGlobalInt('SOCIETE_FISCAL_MONTH_START') > 1 ? 0 : 1); 
``` 

This `getDolGlobalInt('SOCIETE_FISCAL_MONTH_START') > 1 ? 0 : 1` is messing with the dates.

My Organization has the `SOCIETE_FISCAL_MONTH_START` set to January, which is month `1`, and then this code adds 1 year to the `$year_start` and removes 1 year to the `$year_end`

**Comment by valtbern** [comment]
Analyzing other reports from that directory, I'm guessing that one parameter is missing upon report initialization.
As a workaround, until the official bug fix, I've added variable **$nbofyear = 1;**  at the beginning of the report file /compta/resultat/clientfourn.php (where number 1 stands for the number of years you'd like to analyse, taking into account that in the v17 it was a current year, I've put 1). Works perfect for now.

See the screenshot below:

<img width="551" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/21037425/6dde9276-7521-4d67-aeb1-8ed826cf77bc">

After:

![image](https://github.com/Dolibarr/dolibarr/assets/21037425/028fcabf-cf46-422e-8d64-3fa2ced0d672)

**Comment by grti-fr** [comment]
Same issue here

**Comment by nicoleunen** [comment]
Same issue with Dolibarr 18.0.2 and PHP 8.1
