### ISSUE TITLE
Supplier Price Request converting in an order, pricefourn, pdf...

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2605]
1/ There is a problem when converting a supplier price asking in an order (like when you validate a proposal into an order) (bouton clôturer")
http://localhost/dolibarr/fourn/commande/card.php?action=create&origin=askpricesupplier&originid=1&socid=639
RESULT is blank screen for me 
http://localhost/dolibarr/fourn/commande/card.php?id=

BUT it creates the order anyway.
http://localhost/dolibarr/fourn/commande/card.php?id=1125

2/ The supplier price request, when accepted, doesn't add a "new supplier price" in the product card : 
http://localhost/dolibarr/product/fournisseurs.php?id=1023
it erases and replaces the old supplier price (if there was a previous one) and not the supplier's name if it has changed ! it keeps the old supplier's name, but changes its ref and price... 
![image](https://cloud.githubusercontent.com/assets/3694135/7247664/1a7bb296-e80c-11e4-994e-47a7745ee7bc.png)

It should keep old supplier name, price and ref, and create a new entry, with the new data of the suplier's price request.

3/ There is no "requested" price on the pdf 
![image](https://cloud.githubusercontent.com/assets/3694135/7131221/98e35f20-e27c-11e4-8104-c0c52a42effd.png)

4/ Where is the box to follow the price request on the supplier's card ?
there are boxes for supplier's products orders and invoices, but not price requests yet.
![image](https://cloud.githubusercontent.com/assets/3694135/7247617/a4c8253e-e80b-11e4-9ebc-294fec452b53.png)

5/ On the product's stats there is no mention about a price request 
http://localhost/dolibarr/product/stats/facture.php?id=1023

Very useful module :) but still some cosmetics apsects to care about.

**Comment by rdoursenaud** [comment]
@BebZ Can you tell us which version is affected?

This also look like 4 different issues.
If you think they are related enough to be fixed together, you can organise them better using a [list](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments) as a summary of your issue.

Else, please create a different issue for each. This makes thing more manageable for the core team.

Thanks!

**Comment by BebZ** [comment]
Oh, sorry for the delay, it was the latest built develop version
i will make new tests with newer develop version and if those bugs are confirmed, i will create 4 or 5 different ones

**Comment by marcosgdf** [comment]
Is this still happening with latest develop version?

**Comment by BebZ** [comment]
it's better to keep issues separated, as you suggested... my bad ! 
like this you can correct them one after the other if you wish. 
I will close and create different issues, ok ?

**Comment by rdoursenaud** [comment]
@BebZ yes, please, go ahead!

**Comment by BebZ** [comment]
This is definitely a killer feature for noobs ;) recently added... or recently noticed ahahah ! 

![image](https://cloud.githubusercontent.com/assets/3694135/12643347/d56f1574-c5bb-11e5-897d-100df1996529.png)

**Comment by BebZ** [comment]
Will the "stable" module of supplier price request appear in the demo.dolibarr.org to make tests and report it in a neat list ?
