### ISSUE TITLE
Bug: Delivery card is not associate in expedition

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#26055]
# Bug
When you create the delivery, it is not associated with the shipment

## Environment
- **Version**: 18.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.3.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /expedition/card.php?id=130&save_lastsearch_values=1

**Comment by eldy** [comment]
A fix was pushed in 18 branch 2 days ago...
