### ISSUE TITLE
Make service orders signable

### ISSUE THREAD

**Issue by bastolino** [Dolibarr/dolibarr#26069]
### Feature Request

a good improval for automated workflows would be to be able to sign service orders online
(I'm talking about /fichinter/card.php?id=<id>). Basically the same logic as for proposals should be implemented. The internal worker should sign it when logged in, the customer when sent via mail.

### Use case

automation enhancement

**Comment by bastolino** [comment]
any ideas?
As there is already a signing tool for the proposals, this should be somehow a low hanging fruit, I'd think?

**Comment by sonikf** [comment]
Hi @bastolino 
You can close this as implementation is on the way!
https://github.com/Dolibarr/dolibarr/issues/28871

**Comment by bastolino** [comment]
Hah, I was simply way too early ;)
