### ISSUE TITLE
Ticket module does not populate default fields.

### ISSUE THREAD

**Issue by evansgl** [Dolibarr/dolibarr#26073]
### Bug

When you create a new ticket from ticket module (ticket/card.php) some fields do not use the default value. 

### Environment Version

18.0.1

### Environment OS

RHEL

### Environment Web server

Apache

### Environment PHP

8

### Environment Database

MySQL

### Steps to reproduce the behavior

When you browse to ticket/card.php 

The **request type** and **severity** fields are not populated correctly. There is default option for both files in the ticket dictionary but it is not used. You have to click on each combobox and select the default value.

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/17259889/0ede92e6-d94f-43e7-b0b2-2619e9846565)

**Comment by plizafr** [comment]
Hi, i have the same problem.
I solve it by doing this : 
![defaut dolibarr](https://github.com/Dolibarr/dolibarr/assets/42703918/95d2e6b5-2f68-4e89-a2c9-b86989bfe85b)

**Comment by ghost** [comment]
Bug confirmed

**Comment by ghost** [comment]
Fix available in next v18 maintenance release
