### ISSUE TITLE
Upload a square logo

### ISSUE THREAD

**Issue by zahwyrix** [Dolibarr/dolibarr#26079]
### Bug

When I upload my company's square logo (512x512) everything works fine.
But when I activate "Show company logo in menu" in "View", "Theme and colors", it doesn't appear.
I have the Dolibarr logo both in my menu and in Favicon, even though I've imported my square logo.
I use the default eldy theme.

In the theme files we have this code :
`  if (!empty($mysoc->logo_squarred_mini) && is_readable($conf->mycompany->dir_output.'/logos/thumbs/'.$mysoc->logo_squarred_mini)) {
       $urllogo = DOL_URL_ROOT.'/viewimage.php?cache=1&amp;modulepart=mycompany&amp;file='.urlencode('logos/thumbs/'.$mysoc->logo_squarred_mini);
       /*} elseif (!empty($mysoc->logo_mini) && is_readable($conf->mycompany->dir_output.'/logos/thumbs/'.$mysoc->logo_mini))
        {
        $urllogo=DOL_URL_ROOT.'/viewimage.php?cache=1&amp;modulepart=mycompany&amp;file='.urlencode('logos/thumbs/'.$mysoc->logo_mini);
        }*/
     }`

When I look at my company object I have :
`[logo] => 9318e470.png [logo_small] => 9318e470_small.png [logo_mini] => 9318e470_mini.png [logo_squarred] => carre.png [logo_squarred_small] => [logo_squarred_mini] => `

And finally when I look at the FTP I have :
`documents/mycompany/logos/ :
9318e470.png
carre.png
documents/mycompany/logos/thumbs :
9318e470_mini.png
9318e470_small.png
`
Without getting too far ahead of myself, it seems that the minis and small versions of the square logo are not generated.

To correct the bug I created :
- MAIN_INFO_SOCIETE_LOGO_SQUARRED_MINI
- MAIN_INFO_SOCIETE_LOGO_SQUARRED_SMALL
- thumbs/square_mini.png
- thumbs/square_small.png

After that, it works. You'll have to look at the problem in the code.

### Environment Version

18.0.1

### Environment PHP

8.1

**Comment by hregis** [comment]
@zephyriony i don't have your problem with Dolibarr 18.0.1 !
