### ISSUE TITLE
isModEnabled version 18.0.1 doesnt seem to be working correctly

### ISSUE THREAD

**Issue by miguelasribeiro** [Dolibarr/dolibarr#26075]
### Bug

The function isModEnabled on the version 18 doesnt seem to be working correctly, for the modules that i have active it always returns false for example "agenda".

### Environment Version

18

### Environment OS

Windows Server

### Environment Web server

Apache

### Environment PHP

7.3.30

**Comment by hregis** [comment]
@miguelasribeiro I don't have this problem! what context is this in?

**Comment by miguelasribeiro** [comment]
I'm having this issue on the main page for the boxes:

// Number of actions to do (late)
	if (isModEnabled('agenda') && empty($conf->global->MAIN_DISABLE_BLOCK_AGENDA) && $user->rights->agenda->myactions->read) {
		include_once DOL_DOCUMENT_ROOT.'/comm/action/class/actioncomm.class.php';
		$board = new ActionComm($db);
		$dashboardlines[$board->element] = $board->load_board($user);
	}

**Comment by hregis** [comment]
@miguelasribeiro strange ! with dolibarr 18 this is this code :

`if (isModEnabled('agenda') && empty($conf->global->MAIN_DISABLE_BLOCK_AGENDA) && $user->hasRight('agenda', 'myactions', 'read')) {`

**Comment by miguelasribeiro** [comment]
Ah yes sorry, i changed the last part to try to find the issue but its really on the isModEnabled because if i change it to the old method:

if ($conf->agenda->enabled && empty($conf->global->MAIN_DISABLE_BLOCK_AGENDA) && $user->hasRight('agenda', 'myactions', 'read')) {

This one works!

**Comment by miguelasribeiro** [comment]
Oh wait no, actually just realized that it only works this way:

if ($conf->agenda->enabled && empty($conf->global->MAIN_DISABLE_BLOCK_AGENDA) && $user->rights->agenda->myactions->read) {

Even stranger

**Comment by hregis** [comment]
@miguelasribeiro have you this code inside isModEnabled function?

`return !empty($conf->modules[$module]);`

**Comment by miguelasribeiro** [comment]
Yes its unchanged:

function isModEnabled($module)
{
	global $conf;

	// Fix special cases
	$arrayconv = array(
		'project' => 'projet',
		'contract' => 'contrat',
		'bank' => 'banque'
	);
	if (empty($conf->global->MAIN_USE_NEW_SUPPLIERMOD)) {
		$arrayconv['supplier_order'] = 'fournisseur';
		$arrayconv['supplier_invoice'] = 'fournisseur';
	}
	if (!empty($arrayconv[$module])) {
		$module = $arrayconv[$module];
	}

	return !empty($conf->modules[$module]);
	//return !empty($conf->$module->enabled);
}

**Comment by hregis** [comment]
@miguelasribeiro I'm sorry but I don't have this problem. Do you have an external module that could cause this problem?

**Comment by miguelasribeiro** [comment]
@hregis No nothing, i am coming from an older version and the problem seems to be this like return !empty($conf->modules[$module]); 
So im missing something....
