### ISSUE TITLE
API GET /contacts/email/{email} - would be nice with a list when more than 1 contact with identical email

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr#26082]
### Feature Request

I am in doubt where to report this. It's not super important, it could be a tiny bug, or it could be a feature request.

At the moment - 18.0.1 - if you search for a contact by email it will just provide a json with null's everywhere. It would be nice if it was a list of all the contacts with that email address. If there is only one contact it provides a fine json, but not for 2. (have not tried higher numbers).

I detected this while getting started with using Dolibarr for dance class registrations. I create a thirdparty with some of the data from the form. If there is already one thirdparty with the same email plan to add a new contact to detect and preserve those data rather than just overwritting them in the thirdparty. Later I could then run through all thirdparties, see if they have contacts and if so notice the changes and potentially contact the thirdparty asking if they moved or changed phone or what ever was the course. If data are identical I would just delete the contact, or even better, not create in the first place.

```
{
  "module": null,
  "id": null,
  "entity": null,
  "import_key": null,
  "array_options": [],
  "array_languages": null,
  "contacts_ids": null,
  "linked_objects": null,
  "linkedObjectsIds": null,
  "oldref": null,
  "canvas": null,
  "fk_project": null,
  "contact_id": null,
  "user": null,
  "origin": null,
  "origin_id": null,
  "ref": null,
  "ref_ext": null,
  "statut": 1,
  "status": null,
  "country_id": null,
  "country_code": null,
  "state_id": null,
  "region_id": null,
  "barcode_type": null,
  "barcode_type_coder": null,
  "mode_reglement_id": null,
  "cond_reglement_id": null,
  "demand_reason_id": null,
  "transport_mode_id": null,
  "shipping_method_id": null,
  "shipping_method": null,
  "multicurrency_code": null,
  "multicurrency_tx": null,
  "model_pdf": null,
  "last_main_doc": null,
  "fk_bank": null,
  "fk_account": null,
  "note_public": null,
  "note_private": null,
  "name": null,
  "lastname": null,
  "firstname": null,
  "civility_id": null,
  "date_creation": null,
  "date_validation": null,
  "date_modification": null,
  "date_update": null,
  "date_cloture": null,
  "user_author": null,
  "user_creation": null,
  "user_creation_id": null,
  "user_valid": null,
  "user_validation": null,
  "user_validation_id": null,
  "user_closing_id": null,
  "user_modification": null,
  "user_modification_id": null,
  "specimen": 0,
  "labelStatus": null,
  "showphoto_on_popup": null,
  "nb": [],
  "output": null,
  "extraparams": [],
  "civility_code": null,
  "civility": null,
  "gender": null,
  "egroupware_id": null,
  "birthday_alert": null,
  "civilite": null,
  "fullname": null,
  "address": null,
  "zip": null,
  "town": null,
  "poste": null,
  "socid": null,
  "fk_soc": null,
  "socname": null,
  "code": null,
  "email": null,
  "mail": null,
  "url": null,
  "no_email": null,
  "socialnetworks": null,
  "skype": null,
  "twitter": null,
  "facebook": null,
  "linkedin": null,
  "jabberid": null,
  "photo": null,
  "phone_pro": null,
  "phone_perso": null,
  "phone_mobile": null,
  "fax": null,
  "priv": null,
  "birthday": null,
  "default_lang": null,
  "ref_facturation": null,
  "ref_contrat": null,
  "ref_commande": null,
  "ref_propal": null,
  "user_id": null,
  "user_login": null,
  "roles": null,
  "cacheprospectstatus": [],
  "fk_prospectlevel": null,
  "stcomm_id": null,
  "statut_commercial": null,
  "stcomm_picto": null
}
Response Code
200
```

### Use case

I don't really know if I have a hard usecase, but I certainly find the behaviour different than expected.

### Suggested implementation

just provide a list of all contacts with the same email address.

**Comment by hansemschnokeloch** [comment]
Unfortunately the fetch method used under the hood is designed to return a single result. The method returns an error if there are two or more contacts with the same email.
As an alternative you can use `GET /contacts` and use the `sqlfilters` parameter to get the list of contacts `(t.email:like:'john.doe@example.com')`

**Comment by JonBendtsen** [comment]
Great idea @hansemschnokeloch  this solves all my issues.

**Comment by JonBendtsen** [comment]
FYI: this also works for finding members, something which I also need to do :-)

**Comment by JonBendtsen** [comment]
@hansemschnokeloch  is there a way to make the sqlfilter more precise than like? because I'm guessing the above would find a hit with both `john.doe@example.com` and with `john.doe@example.com.au`

**Comment by hansemschnokeloch** [comment]
There's a lack of documentation on sqlfilters.
AFAIK `like` make's a strict comparaison on text (although I'm not absolutely sure).
But you can use `=` instead.
`(t.email:=:'john.doe@example.com')`
