### ISSUE TITLE
Deliveries are not visible out of the moment of their creation for shipments

### ISSUE THREAD

**Issue by bafbes** [Dolibarr/dolibarr#26088]
### Bug

Recently, the handling of shipments deliveries has changed. Previously, for each shipment we had a “delivery” tab which listed its single associated delivery. The id associated with this tab was that of the shipment. With the probable aim of being able to associate several deliveries to a shipment, the current id of this tab is that of the delivery. The problem is that the delivery tab no longer appears, even when the shipment has several deliveries. There is also no isolated way to view deliveries out of shipments. This means that we can only see the deliveries at the time of their creation. It therefore becomes urgent to resolve this problem or to return back to the old mode of viewing shipment deliveries.

### Environment Version

18.0.1

**Comment by eldy** [comment]
A fix was pushed in 18 branch 2 days ago...
