### ISSUE TITLE
Is not allowed to select closed projects at tickets creation

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#26100]
### Bug

Is not allowed to select closed projects in Tickets.
Even when a ticket is closed, remains under garantee, and new support tickets can arise over an alreaady closed project.

### Environment Version

ALl

### Environment OS

All

### Environment Web server

All

### Environment PHP

All

### Environment Database

All

### Environment URL(s)

https://myserver.com/ticket/card.php?action=create&idmenu=6596&mainmenu=ticket&leftmenu=

### Expected and actual behavior

Now all the closed projects appears in grey color and is not possible to select it when a ticket is created.
This force the user to reopen the project, then assign the project to the ticket, and close again the project.

**Comment by aspangaro** [comment]
Thanks for your return.
Fix proposed in branch v14. The fix will go up on higher versions as time goes by if it's accepted.

I closed this issue.

**Comment by edupulpillo** [comment]
Thank you, at the moment the problem still is present in v17.0.3, and updating in the file public_html/core/class/html.formticket.class.php the  call to select_projects(-1, GETPOST('projectid', 'int'), 'projectid', 0, 0, 1, **0**, 0, 0, 0, '', 1, 0, 'maxwidth500'); is not fixing the problem, since still appears in grey and unselectionable the projects that are closed in the project list.

![image](https://github.com/Dolibarr/dolibarr/assets/7486607/75840038-b4e7-4121-806c-2b018334ff53)

**Comment by edupulpillo** [comment]
Hi the problem still is present in Dolibarr v18.0.4
