### ISSUE TITLE
Count in the list of holidays is not correct

### ISSUE THREAD

**Issue by rlm6** [Dolibarr/dolibarr#26119]
### Bug

Whatever the filter is, the count seems to be twice the correct value.

### Environment Version

18.0.1

### Environment OS

Linux Debian 12.0

### Environment Web server

Apache 2.4.57

### Environment PHP

7.4.33

### Environment Database

10.11.3-MariaDB

### Expected and actual behavior

![Screenshot_2](https://github.com/Dolibarr/dolibarr/assets/59738521/148ec516-7896-485d-b6c6-bd572d70c082)
Whatever the filter is, the count seems to be twice the correct value.

In the capture, the count should be 22.5 and it's 45!

### Steps to reproduce the behavior

- Go to the list of holidays

**Comment by eldy** [comment]
I think this has been fixed for 18.0.2

**Comment by rlm6** [comment]
I confirm, I have upgraded to 18.0.2 and the issue seems to be resolved. I close the issue.
