### ISSUE TITLE
Error with document preview 

### ISSUE THREAD

**Issue by lelex86** [Dolibarr/dolibarr#26129]
### Bug

Hello everyone,

When we send the expedition document by mail, we get an error message with the preview of the document. This happened on lots of URLs with different OS/server and database.

This is the error message:
"ErrorFileDoesNotExists: sending/SH2310-0001/SH2310-0001.pdf"

### Environment Version

15/16/17

### Environment PHP

7.4

### Expected and actual behavior

When we click on the preview button, we should see the document. Instead, we have the error message.

### Steps to reproduce the behavior

Create an expedition, send by mail, click on the preview button.

### Attached files

![Capture d’écran 2023-10-06 à 17 11 28](https://github.com/Dolibarr/dolibarr/assets/75493227/bfca8d04-ba19-40bf-ad97-baf2c9ba3f39)
![Capture d’écran 2023-10-06 à 17 12 41](https://github.com/Dolibarr/dolibarr/assets/75493227/16dfd14b-ec72-451d-b7d6-2881dce23b58)

**Comment by atm-maxime** [comment]
Hi. This was fixed in version 17.0.2 on the 19th of june 2023. I just pushed the fix in version 15.

**Comment by lelex86** [comment]
Hi! Wonderful, thank you!
