### ISSUE TITLE
The Categories Customer/Provider are always shown when a third party is created.

### ISSUE THREAD

**Issue by erwinpalma** [Dolibarr/dolibarr#26123]
### Bug

There are four alternatives To create a third party. 

1. New Third Party
2. New Prospect
3. New Customer
4. New Vendor

When I created a New Third Party, I could see both Categories.

![image](https://github.com/Dolibarr/dolibarr/assets/30660343/5571e0c9-e2b0-47e9-bb14-7077faa852a4)

The problem is that regardless of the third party, both categories are showing on the card.

### Environment Version

18.0.1

### Environment OS

Ubuntu

### Environment Web server

Apache 2

### Environment PHP

7.4

### Environment Database

mariadb

## Actual behavior

1. Add a New Third Party and see the categories section
- Cust./Prosp. tags/categories
- Vendors tags/categories
2. Add a New Prospect and see the categories section
- Cust./Prosp. tags/categories
-Vendors tags/categories
3. Add a New Customer and see the categories section
- Cust./Prosp. tags/categories
- Vendors tags/categories
4. Add a New Vendor and see the categories section
- Cust./Prosp. tags/categories
- Vendors tags/categories

## Expected behavior

1. Add a New Third Party and see the categories section
- Cust./Prosp. tags/categories
- Vendors tags/categories
2. Add a New Prospect and see the categories section
- Cust./Prosp. tags/categories
3. Add a New Customer and see the categories section
- Cust./Prosp. tags/categories
4. Add a New Vendor and see the categories section
- Vendors tags/categories

### Steps to reproduce the behavior

login in Dolibarr
Go to Third-Parties Meno

Add a New Third Party and see the categories section
Add a New Prospect and see the categories section
Add a New Customer and see the categories section
Add a New Vendor and see the categories section

**Comment by erwinpalma** [comment]
## Solution,

To solve this issue, I have added the folowing code into `htdocs\societe\card.php: 1850`

```php
// Categories
		if (isModEnabled('categorie') && $user->hasRight('categorie', 'lire')) {
			$langs->load('categories');
			if ($object->client != 0) {
				// Customer
				print '<tr class="visibleifcustomer"><td class="toptd">' . $form->editfieldkey('CustomersProspectsCategoriesShort', 'custcats', '', $object, 0) . '</td><td colspan="3">';
				$cate_arbo = $form->select_all_categories(Categorie::TYPE_CUSTOMER, null, 'parent', null, null, 1);
				print img_picto('', 'category', 'class="pictofixedwidth"') . $form->multiselectarray('custcats', $cate_arbo, GETPOST('custcats', 'array'), null, null, 'quatrevingtpercent widthcentpercentminusx', 0, 0);
				print "</td></tr>";
			}
			if ($object->client <= 0) {
				// Supplier
				if (isModEnabled("supplier_proposal") || isModEnabled("supplier_order") || isModEnabled("supplier_invoice")) {
					print '<tr class="visibleifsupplier"><td class="toptd">' . $form->editfieldkey('SuppliersCategoriesShort', 'suppcats', '', $object, 0) . '</td><td colspan="3">';
					$cate_arbo = $form->select_all_categories(Categorie::TYPE_SUPPLIER, null, 'parent', null, null, 1);
					print img_picto('', 'category', 'class="pictofixedwidth"') . $form->multiselectarray('suppcats', $cate_arbo, GETPOST('suppcats', 'array'), null, null, 'quatrevingtpercent widthcentpercentminusx', 0, 0);
					print "</td></tr>";
				}
			}
			if (!empty($conf->global->THIRDPARTY_SUGGEST_ALSO_ADDRESS_CREATION)) {
				print '<tr class="individualline"><td class="toptd">' . $form->editfieldkey('ContactCategoriesShort', 'contcats', '', $object, 0) . '</td><td colspan="3">';
				$cate_arbo = $form->select_all_categories(Categorie::TYPE_CONTACT, null, 'parent', null, null, 1);
				print img_picto('', 'category', 'class="pictofixedwidth"') . $form->multiselectarray('contcats', $cate_arbo, GETPOST('contcats', 'array'), null, null, 'quatrevingtpercent widthcentpercentminusx', 0, 0);
				print "</td></tr>";
			}
		}
```

**Comment by eldy** [comment]
Fixed by https://github.com/Dolibarr/dolibarr/commit/aea0083abc3e5ff4e4eff12b068cbb98c79860c9
