### ISSUE TITLE
Photos / Pictures link not available after updating to 3.7

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2612]
Strange behaviour :+1: 
it's possible to upload a picture / photo of a product from the product's photo's tab, 
but it doesnt display any link to check the picture.
/product/photos.php?id=...

but it displays a message of success, file transfered to the server.
Le fichier a été transféré avec succès

if I check the server, the file is there BUT there's a difference in the path of the file uploaded in 3.7, images land in hte root folder, not in some subfolder of the document/produit/.../...

it seems it makes the option : MAIN_GENERATE_PROPOSALS_WITH_PICTURE 
dead

**Comment by BebZ** [comment]
@darkjeff @eldy  Maybe ? 
https://github.com/Dolibarr/dolibarr/commit/90d47cffae315f235aadb77373f8e0aaa553de6c#diff-fe61cc4ccf92c29cf5236bfdfb0b6aa0L62

**Comment by marcosgdf** [comment]
What do you mean? I get this when I upload a photo to a product.

![captura de pantalla 2015-04-18 a las 10 52 33](https://cloud.githubusercontent.com/assets/168744/7214727/0ea7aace-e5b9-11e4-8777-5cc5fd4a0b27.png)

**Comment by rdoursenaud** [comment]
File appears in the right path for me and provide a link to the picture in the form //viewimage.php?modulepart=product&entity=1&file=%2FProductRef%2Ftestfile.jpg

MAIN_GENERATE_PROPOSALS_WITH_PICTURE is an hidden feature and unsupported as such.

**Comment by BebZ** [comment]
Aw, I am sorry for late reply... On my 3.7 version the photo doesn't
appear, nor the link.
Files are uploaded at the root of product documents folder, and doesn't
follow the naming of folders like 1/0/abc i had before...
It is quite a strange behaviour, maybe i'll ask to my host to reinstall the
3.7 "bugfree latest version" and this will disappear because even him, said
it was no problem except the files not following the right path.

Thanks for you investigations, i'll keep u in touch with new sever and
version.

_Hubert ANDRIOLO_
_Gérant F.M. MEDICAL et NORD HYGIENE_
Mobile: +33 (0) 6 23 10 17 31
Fax: +33 (0) 9 56 51 95 71
Site: www.fournisseur-medical.com

_FM MEDICAL - NORD HYGIENE_
280, rue berthie Albrecht
62110 Hénin-Beaumont
SIRET : 532 788 700 00021
N° de TVA : FR15 532 788 700

2015-04-30 15:41 GMT+02:00 Raphaël Doursenaud notifications@github.com:

**Comment by marcosgdf** [comment]
Could this be related with #2743?

**Comment by tiaris** [comment]
I think so, I have comitted a batch script to move photos from old directory to new. wainting for integration. 
pictures are moved to new directory, but got errors for removing old empty directories (bug ? ). please test it in several contexts (win, mac, linux...)
We should also integrate this in product.class.php code for automatic migration

**Comment by rdoursenaud** [comment]
Oh, nice catch @marcosgdf. So this is an issue on the upgrade path to 3.7.
I believe we should mark #2743 as a duplicate (since this one predates it). What's our policy on duplicates @Dolibarr/owners ?

**Comment by simnandez** [comment]
This is previus but #2743 has more activity and best registry of the problem...  I thinks we should mark this as duplicate....

**Comment by rdoursenaud** [comment]
OK, so I close this one.
Please add to the discussion at #2743.
