### ISSUE TITLE
When pressing "6" in the stock correction field, "Add" is automatically changed to "Delete"

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#26134]
### Bug

In stock correction, "Add" is selected normally and we can enter any number to positively correct the stock.

However, as soon as the number "6" is entered in the field "Number of units", the method is automatically changed to "Delete". This causes a lot of problems. See screenshots.

### Environment Version

17.0.2

### Expected and actual behavior

The "Add" method should never change automatically unless we actually change it manually.

### Attached files

![2023-10-08_185823](https://github.com/Dolibarr/dolibarr/assets/11036018/d95a6440-ee37-435a-a6a2-48dc3e506913)
![2023-10-08_185828](https://github.com/Dolibarr/dolibarr/assets/11036018/29ec4c79-cfb7-49cd-9955-afe107e7f5bc)

**Comment by hregis** [comment]
@bos4711 fixed with this PR https://github.com/Dolibarr/dolibarr/pull/26135
thank you
