### ISSUE TITLE
Merge two thirdparties into one

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#2613]
Add a new page to select third party to keep and thirdparty to delete (the duplicate record).
All objects linked to second thirdparty are moved into first one by doing an update set fk_soc = newid where fk_soc = oldid.
There is a loop onto a list of all tables that contains a field fk_soc.

So once this is done, the second third party can be deleted.

**Comment by BebZ** [comment]
Woah ! Eldy is magic ! 

Would it be possible to have a page to merge "products" ? 
Sometimes you create 2 products, as you do for thirdparties, not knowing there's already an existing one. and you put it on proposal, orders, invoices... so you can't delete one of the 2 almost same ref anymore.
a loop onto a list of all tables containing the field fk_product ?

I will open a new feature request is you say it's possible.

**Comment by marcosgdf** [comment]
This can be closed as the PR is already merged.
