### ISSUE TITLE
Invoice filters not working

### ISSUE THREAD

**Issue by TanguyP** [Dolibarr/dolibarr#26146]
### Bug

On the invoice page (customer invoices -> list), when I'm trying to apply any kind of sorting/filter, there are no results whatever I use: dropdown lists or if I type something, like a customer name for example.
It just returns "Aucun enregistrements trouvé" (No records found) every time.

Note: I recently migrated from Dolibarr v. 10.0.6 to 18.0.1 and followed assisted steps for database migration. The problem started occurring after that.

### Environment Version

18.0.1

### Environment PHP

8

**Comment by ksar-ksar** [comment]
Hello,

If you speak about compta/facture/list.php , it's working for me :
![image](https://github.com/Dolibarr/dolibarr/assets/35605507/d96f07d4-0d82-45bf-812b-30f3844d7d3d)

Try to activate dolibarr logs to understand

**Comment by TanguyP** [comment]
Thanks for your reply. In the logs, I found the SQL query used to apply the filter: it contains an `AND s.code_client LIKE '%-1%'` part in the `WHERE` clause, When I run the query myself, it indeed returns no results. However, if I remove the `AND s.code_client LIKE '%-1%'` bit, then it returns some results.

Anyway, I've migrated to 18.0.2 and that fixed the issue.

**Comment by sonikf** [comment]
@ksar-ksar 
Same as #26145
