### ISSUE TITLE
Make product description available as a column

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#26142]
### Feature Request

Today, in v17.0.2, when listing products it is not possible to select Product Description column when browsing through the product list. You can select Label, Weight, Cost price, or whatever, but not Description. Having the Description visible when listing all products would really help when many products are similiar.

![2023-10-09_064235](https://github.com/Dolibarr/dolibarr/assets/11036018/043042c0-da63-4ef0-b2a6-da587f1c656c)

### Suggested implementation

Add relevant code in `/product/list.php`

**Comment by ksar-ksar** [comment]
Hello,

It's the actual choice, because Description could be very big and not adapted to be displayed in List format.

**Comment by bos4711** [comment]
I agree that for very big descriptions it will be a mess, but how about just using a short excerpt of the description (like first 200 chars) or similiar, so the list won't be ruined?

**Comment by bos4711** [comment]
@ksar-ksar In PR #26193 @eldy suggested the use of `dolGetFirstLineOfText() ` which I think will solve the issue here as well.

**Comment by bos4711** [comment]
Fixed by PR #26287
