### ISSUE TITLE
Limit sales representatives permissions to their elements

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#2615]
Hi,

I think that would be a nice option if We can change permissions to module proposals, orders, invoices in this same way like in Third Parties - Extend access to all third parties (not only those linked to user).

The situation:
I have user. I want give him access to read / see all third-parties but i want he can read only this proposals, orders, invoices which ale linked to third-parties linked to the user (Sales representatives)

**Comment by pat15** [comment]
Is there any chance to implement this modification? :)

**Comment by eldy** [comment]
This is a big change. No work are planed for this so chance are very low.
But may be someday someone will provide a patch for this...
