### ISSUE TITLE
SetInGroup / RemoveFromGroup can be slow with Ldap

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#26182]
### Bug

If we use a Ldap mapping `dolibarr2Ldap`, then when we call `$user->SetInGroup` or `$user->RemoveFromGroup` for a given user, instead of sending a query to add / remove the user from the Ldap group, Dolibarr seems to send a query replacing the `member` field of the group.

So adding (or removing) one user from a group can generate a write of the whole group.

In our case this make these request quite slow (up to 30 seconds).

### Environment Version

17.0.3

### Environment OS

Debian 11

### Environment Web server

Apache 2.4.54

### Environment PHP

7.4.30

### Environment Database

11.0.2-MariaDB-1:11.0.2+maria~ubu2204

### Expected and actual behavior

Calling `$user->SetInGroup` or `$user->RemoveFromGroup` should either only create a minimalist LDAP patch (add / remove the user in the group) or there should be a ldap setting `Synchronize full group on each user add / remove` if set to true, then use the current behavior, else try to send minimalistic patches

**Comment by hregis** [comment]
@dbeniamine I don't have this problem! how many users do you have in a group?

**Comment by dbeniamine** [comment]
About 500, it's not that much ...

Do you see the query sent by dolibarr ?

In my cas I see that when I update a user, a query MOD to the group Member field is sent.

My groups are `groupOfNames` with `member` attribute and the `memberOf` plugin (using openLdap)

**Comment by hregis** [comment]
@dbeniamine the functions are present but I no longer know why I chose to modify the whole thing! In the "ldap" class there is "addAttribute(), updateAttribute() and deleteAttribute()" which would manage the addition or removal of users in a group one by one. I would have to do some testing and implement it in the development version.

**Comment by dbeniamine** [comment]
> @dbeniamine the functions are present but I no longer know why I chose to modify the whole thing! In the "ldap" class there is "addAttribute(), updateAttribute() and deleteAttribute()" which would manage the addition or removal of users in a group one by one. I would have to do some testing and implement it in the development version.

Yes I thought so.

I guess that the goal of the full rewrite is to ensure that dolibarr group is fully synced to the ldap backend, i.e if someone manually modified the ldap, dolibarr changes takes over.

This seems to be an acceptable use case, but having a parameter to switch between the "patch" and the "replace" mode would be great.

With this parameter, the default behavior can be kept.

**Comment by dbeniamine** [comment]
I've just tested, we still have this issue with 20.0.4, @hregis are you planning to write a fix ?

**Comment by dbeniamine** [comment]
Hi,

Can someone reopen this issue, this is quite problematic for us ...

Best regards

**Comment by dbeniamine** [comment]
> [@dbeniamine](https://github.com/dbeniamine) the functions are present but I no longer know why I chose to modify the whole thing! In the "ldap" class there is "addAttribute(), updateAttribute() and deleteAttribute()" which would manage the addition or removal of users in a group one by one. I would have to do some testing and implement it in the development version.

Hello @hregis this issue is still very annoying for one of my customers, I am ok to try to implement this by myself, but do you have a branch or something I can start with, your last message, implied that you might have one ...
