### ISSUE TITLE
Advanced Stock Transfer: Adding a line causes an HTTP ERROR 500

### ISSUE THREAD

**Issue by SmartLiving-Rocks** [Dolibarr/dolibarr#26194]
### Bug

I would like to transfer some items from one warehouse to another one.  I am using the experimental Module `Advanced Stock Transfer `. As soon as I have inserted the desired quantity and click add line, I am getting an HTTP 500 error. 

### Environment Version

18.0.2

### Environment OS

Ubuntu 23.04 

### Environment Web server

Apache/2.4.55 (Ubuntu)

### Environment PHP

PHP 8.1.12-1ubuntu4.3 

### Environment Database

MariaDB 1:11.1.2+maria~ubu2204

### Environment URL(s)

/dolibarr/product/stock/stocktransfer/stocktransfer_card.php?id=2#addline

### Expected and actual behavior

1. In `Products` under `Advanced Stock Transfer` click on `New stock transfer`
2. Fill out the `Label` and select an existing `Project` as well as the Warehouses `Entrepôt source` and `Entrepôt de destination`
3. A new window opens. Insert the desired `Qty ` you want to move and click `Add`
4. The line with the desired quantity will be added to the `Advanced Stock Transfer` and continue adding further items. 

### Steps to reproduce the behavior

1. In `Products` under `Advanced Stock Transfer` click on `New stock transfer`
2. Fill out the `Label` and select an existing `Project` as well as the Warehouses `Entrepôt source` and `Entrepôt de destination`
3. A new window opens. Insert the desired `Qty ` you want to move and click `Add`
4. 💥 Getting the HTTP Error 500  `/dolibarr/product/stock/stocktransfer/stocktransfer_card.php?id=2#addline`

**Comment by ksar-ksar** [comment]
Hello,

Error 500 means PHP Error => Can you check the Apache Logs ?

**Comment by SmartLiving-Rocks** [comment]
Hello, I have just created a brand-new installation of 18.0.3 on Ubuntu with this image https://sourceforge.net/projects/dolibarr/files/Dolibarr%20installer%20for%20Debian-Ubuntu%20%28DoliDeb%29/18.0.3/dolibarr_18.0.3-4_all.deb/download

Initially, I have set company name and country. 
Then, I have created two warehouses and some products (also corrected the stock and added a stock value)

Here is the error log of the Apache after I hit "ADD"

`[Wed Nov 15 10:31:26.782922 2023] [php:error] [pid 682] [client xxxxxx:50458] PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /usr/share/dolibarr/htdocs/product/stock/stocktransfer/stocktransfer_card.php:198\nStack trace:\n#0 {main}\n thrown in /usr/share/dolibarr/htdocs/product/stock/stocktransfer/stocktransfer_card.php on line 198, referer: http://xxxxxxxxx/dolibarr/product/stock/stocktransfer/stocktransfer_card.php?id=1`

**Comment by TheRealBeef** [comment]
I can confirm that I have the same issue with a fresh local install of 18.0.3 (installed via Git and not .deb), whether from a blank database or using the restored database/documents from my existing remote installation. The restored database from my remote server was originally version 14 and has been upgraded to 18.0.3 over time.

[Mon Nov 20 14:17:44.862045 2023] [php:warn] [pid 232549] [client 192.168.1.111:56902] PHP Warning:  Undefined array key "arrayofkeyval" in /var/www/html/dolibarr/htdocs/product/stock/stocktransfer/class/stocktransferline.class.php on line 150, referer: http://192.168.1.111/dolibarr/htdocs/product/stock/stocktransfer/stocktransfer_card.php?id=233&save_lastsearch_values=1

[Mon Nov 20 14:17:44.862531 2023] [php:error] [pid 232549] [client 192.168.1.111:56902] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/dolibarr/htdocs/product/stock/stocktransfer/stocktransfer_card.php:198\nStack trace:\n#0 {main}\n  thrown in /var/www/html/dolibarr/htdocs/product/stock/stocktransfer/stocktransfer_card.php on line 198, referer: http://192.168.1.111/dolibarr/htdocs/product/stock/stocktransfer/stocktransfer_card.php?id=233&save_lastsearch_values=1

**Comment by TheRealBeef** [comment]
Found the lines referenced and added some null checks and it appears to function properly now

**Comment by ksar-ksar** [comment]
The FIX is on develop branch, V18 still have the Bug

**Comment by SmartLiving-Rocks** [comment]
> Found the lines referenced and added some null checks and it appears to function properly now

Yes, I can confirm that on a fresh installation of Dolibarr 18.0.3 🥳

✅ New lines of products can be added without a crash. 
✅ Increasing, Decreasing using UI buttons are also working. 
![Bildschirmfoto 2023-11-21 um 10 09 14](https://github.com/Dolibarr/dolibarr/assets/76279896/ee43177f-de72-44b0-bcdb-5b441a898f9d)


### Additional Observations

- [ ] Project Overview `/dolibarr/projet/element.php?id=1`→ "List of stock movements associated to project" does not show any movement. (STOCK_MOVEMENT_INTO_PROJECT_OVERVIEW is activated (1) in `/dolibarr/admin/const.php?mainmenu=home`
![Bildschirmfoto 2023-11-21 um 10 10 31](https://github.com/Dolibarr/dolibarr/assets/76279896/58e4d45b-808d-46f0-bd52-0ea7fec35367)

- [ ] After Validation, the generated PDF `ST2311-0001.pdf` is empty
![Bildschirmfoto 2023-11-21 um 09 54 49](https://github.com/Dolibarr/dolibarr/assets/76279896/9641dba0-c3a5-4d23-ba44-9ffef38e8de2)
![Bildschirmfoto 2023-11-21 um 10 06 11](https://github.com/Dolibarr/dolibarr/assets/76279896/818b53ec-439f-42ed-953a-43170af0258d)

- [ ] SEND MAIL Button is not working and gives a blank space
