### ISSUE TITLE
FIX - Add project with thirdparties when modify various payement

### ISSUE THREAD

**Issue by Jonathan42800** [Dolibarr/dolibarr#26195]
### Bug

When we create an various payement, we are able to select all the projects validated, but when it is create,
if we modify the various payement to modify/add a project, we can't have all the projects.
[card.zip](https://github.com/Dolibarr/dolibarr/files/12879829/card.zip)

### Environment Version

17.0.1

### Environment OS

Linux dolibarr 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64

### Environment Web server

Apache/2.4.41 (Ubuntu)

### Environment PHP

7.2.34-18+ubuntu20

### Environment Database

MySQL or MariaDB 5.5.5-10.3.38-MariaDB-0ubuntu0.20.04.1

### Environment URL(s)

https://transantico.srv01.gpca.fr/compta/bank/various_payment/card.php

### Expected and actual behavior

When we create an various payement, we are able to select all the projects validated, but when it is create,
if we modify the various payement to modify/add a project, we can't have all the projects but only projects which haven't thirdparties affected (it had a filtrer SQL to the selector of projects in the modify form).

### Steps to reproduce the behavior

#FIX
modify the line 572 : "$morehtmlref .= $formproject->select_projects(0, $object->fk_project, 'projectid', $maxlength, 0, 1, 0, 1, 0, 0, '', 1);" in the file /compta/bank/various_payement/card.php 
by the line "$morehtmlref .= $formproject->select_projects(-1, $object->fk_project, 'projectid', $maxlength, 0, 1, 0, 1, 0, 0, '', 1);"

=> Change the first parameter of the function select_projects() by -1 to be able to select all projects 

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/147707369/5e28b398-a946-4fbf-a090-a476e0ae0241)

**Comment by aspangaro** [comment]
Thanks for your return. 
Fix proposed in branch v14. The fix will go up on higher versions as time goes by if it's accepted. 

I closed this issue.
