### ISSUE TITLE
Period start from year + 1 to year witch lead to empty report

### ISSUE THREAD

**Issue by Zephyrien** [Dolibarr/dolibarr#26203]
### Bug

In `compta/resultat/clientfourn.php` the variable nbofyear is not initialized witch lead to a start year higher than end year and then empty report

please add `$nbofyear = 1;`

### Environment Version

18.0.

### Environment OS

Fedora 38

### Environment Web server

Apache

### Environment PHP

8.2.11

**Comment by xabitrigo** [comment]
I think this is the same as #26050

**Comment by Zephyrien** [comment]
> I think this is the same as #26050

Oh, you're right

**Comment by Zephyrien** [comment]
Duplicate as #26050

**Comment by Zephyrien** [comment]
Duplicate as #26050
