### ISSUE TITLE
Incorrect Sender Name in CRON-triggered Emails from Members Module

### ISSUE THREAD

**Issue by Steph501** [Dolibarr/dolibarr#26224]
### Bug

Hi,
Emails sent via CRON from the Members module in Dolibarr display 'admin' as the sender name instead of the organization's name.
I haven't found a variable or a way to configure it otherwise.

### Environment Version

V18

### Environment PHP

8

### Environment Database

mySQL

**Comment by Daoud-mohamed** [comment]
Would you like to share a screenshot or provide more details to reproduce the behavior? I checked in my Dolibarr instance, and I didn't have any problems.

**Comment by Steph501** [comment]
Sure, when a payment is made following online registration (domain.tld/public/members/new.php), a confirmation email is sent to the address entered. The sender is "admin".
![Screenshot](https://github.com/Dolibarr/dolibarr/assets/3607196/86083bb2-112c-4ef2-bd0c-6eb0a1a25ffd)
