### ISSUE TITLE
"Stock can be negative" not respected

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#26241]
### Bug

In the stock settings it is possible to check the box for "Stock can be negative" and I have used that fucntion for years without any problems. Today when trying to create a delivery note, I couldn't do so until I manually added the article to the stock

### Environment Version

18.0.2

### Environment OS

Debian 11

### Environment Web server

Apache version 2.4.56

### Environment PHP

7.4.33

### Environment Database

MariaDB version 10.5.21

### Environment URL(s)

https://domain.com/htdocs/expedition/card.php

### Expected and actual behavior

In the "Stock" module, there a setting "Stock can be neagtive"

![can be negative](https://github.com/Dolibarr/dolibarr/assets/24247236/45126248-77e2-4d20-bcf6-c5eafde5d492)

**When** it is checked it should be possible to create delivery notes even if there is no stock. This has worked fine until now. When trying to create a delivery note with a product not in stock as per the below picture

![2](https://github.com/Dolibarr/dolibarr/assets/24247236/a19f8e18-518d-49eb-80c6-17e51520afd2)

**it** doen't work and the below Error pops up

![3](https://github.com/Dolibarr/dolibarr/assets/24247236/23e8a4c2-7ebb-4775-b38b-c85a3213326f)

**and** when I again have a look at the checkboxes, the column for "Qté. à expédier" is empty and no delvery note has been created.

![4](https://github.com/Dolibarr/dolibarr/assets/24247236/866832ed-f25f-464a-a632-69717bed08c4)

**The only way** to get around it is to manually make a stock adjustment and add so many units as there should be on the delivery note.

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 18.0.5

**Comment by hasse-basse** [comment]
Hi

It work now, but it could be that it has been OK for a while before 18.0.5. I'l not sure about it but I have note encountered the problem for a while. In any case, it seem to be OK now.

Thanks
