### ISSUE TITLE
projet/tasks/time.php no entity filter in query

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#26243]
### Bug

Filter on entity field is missing, so with multicompany module installed every company can see worked hour of other company

### Environment Version

all version

### Environment OS

all version

### Environment Web server

all version

### Environment PHP

all version

### Environment Database

all version

### Environment URL(s)

projet/tasks/time.php

### Expected and actual behavior

$sql .= " WHERE p.entity IN (".getEntity('project').")";

**Comment by hregis** [comment]
@aschio fixed with this PR https://github.com/Dolibarr/dolibarr/pull/26247 thank you
