### ISSUE TITLE
Workstation not working in multicompanys mode

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#26256]
### Bug

When creating a new workstation, entity set to 1 instead of $conf->entity
In code we see $ismultientitymanaged = 0;
Wich is not logical

### Environment Version

all

### Environment OS

all

**Comment by ksar-ksar** [comment]
@hregis ?

**Comment by hregis** [comment]
@vmaury @ksar-ksar can you test with this fixed, thanks ? https://github.com/Dolibarr/dolibarr/pull/26267

**Comment by vmaury** [comment]
@hregis pull request is exactly the same as the one I sent some hours ago : https://github.com/Dolibarr/dolibarr/pull/26257
