### ISSUE TITLE
SQL Exception when saving in llx_element_time (relation llx_element_time_rowid_seq does not exist)

### ISSUE THREAD

**Issue by matll42** [Dolibarr/dolibarr#26266]
### Bug

A SQL database structure is wrong with postgresql.
Due to new migration from project_task_* to element_*, a sequence(serial) has been forgotten to be changed on the `llx_element_time` table.

### Environment Version

18.0.2

### Environment OS

Ubuntu 22.04 LTS

### Environment Web server

Apache 2.4

### Environment PHP

php 8.1.24

### Environment Database

postgresql 12.14

### Environment URL(s)

/projet/tasks/time.php

### Expected and actual behavior

an exception appear when saving a new time in a task

for dolibarr 18 with postgresql, in order to be able to create a time spent, I had to run those three adjustments and it runs fine:
```sql
create sequence llx_element_time_rowid_seq;
select setval('llx_element_time_rowid_seq', (select max(rowid) from llx_element_time));
alter table llx_element_time alter column rowid set default nextval('llx_element_time_rowid_seq'::regclass);
```

### Steps to reproduce the behavior

1. Go to a project page / Tab Time spent (/projet/tasks/time.php?withproject=1&projectid=2)
2. Click on + to add time
3. Fill all fields
4. Submit
5. That's it

### Attached files

apache-error.log:
```
AH01071: Got error 'PHP message: PHP Warning:  pg_query(): Query failed: ERROR:  42P01: relation &quot;llx_element_time_rowid_seq&quot; does not exist\nLINE 1: SELECT currval('llx_element_time_rowid_seq')\n                       ^\nLOCATION:  RangeVarGetRelidExtended, namespace.c:424 in /opt/dolibarr/htdocs/core/db/pgsql.class.php on line 852', referer: https://myown.dolibarr.ca/projet/tasks/time.php?withproject=1&projectid=10&action=createtime&token=8bbe73018813ce390bb266498c5f82fc&backtopage=%2Fprojet%2Ftasks%2Ftime.php%3Fprojectid%3D10%26withproject%3D1
```

**Comment by Saarbremer** [comment]
Note to the SQL script: Make sure the sequence belongs to the database user of the dolibarr DB user.

**Comment by FlorentPoinsaut** [comment]
Duplicates #25793
