### ISSUE TITLE
Time spent on projects 

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#26288]
### Bug

Whenever I clock add on a time spent for a task I get the following error message: 

ERROR: 42P01: relation "llx_element_time_rowid_seq" does not exist LINE 1: SELECT currval('llx_element_time_rowid_seq') ^ LOCATION: RangeVarGetRelidExtended, namespace.c:432

### Environment Version

18.0.2

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

8

### Environment Database

PostgreSQL

**Comment by Saarbremer** [comment]
Here's a possible workaround for those who don't bother to update the database directly. 

https://github.com/Dolibarr/dolibarr/issues/26266

**Comment by FlorentPoinsaut** [comment]
Duplicates https://github.com/Dolibarr/dolibarr/issues/25793
