### ISSUE TITLE
Contract list services filter error with "expired service"

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#26283]
### Bug

![image](https://github.com/Dolibarr/dolibarr/assets/1215488/ca6f14f2-5b1f-40b3-858b-3142b99a5e4b)

With filter EXPIRED, in list we see also "NOT EXPIRED". 

I suppose that sql query is not correct.

### Environment Version

Dolibarr >= 18.x

### Environment OS

all version

### Environment Web server

all version

### Environment PHP

all version

### Environment Database

all version

### Environment URL(s)

/contrat/services_list.php?leftmenu=contracts&search_status=4&filter=expired

### Expected and actual behavior

Do not show "not expired" services.

### Steps to reproduce the behavior

Click on top menu "COMMERCIAL"
Click on left menu "Expired Services"

**Comment by PascalB67** [comment]
Hello, I see the same thing in 18.0.1

**Comment by W1W1-M** [comment]
Hi, in dev v19 switching between : 
- `running, not expired` and `running` 
- `running, expired` and `running `

does not show the correct results. This seems to be related to your bug. 

This could be fixed with updated code to PR #21647
