### ISSUE TITLE
Problème fichier joint et tiers sur réglement Fournisseur

### ISSUE THREAD

**Issue by Cyril35** [Dolibarr/dolibarr#26290]
### Bug

Depuis le passage en V18.02, le fournisseur affiché dans l'onglet fichier joint et sur le fichier joint corresponds à un client et non au fournisseur à qui on vient de faire le réglement.
Si vous prenez des anciens réglements, le fichier joint est bon (puisque généré avec une autre version) mais le fournisseur affiché dans l'onglet est mauvais (il semble être à chaque fois un client et non un fournisseur)

Ci-joint une capture d’écran d’un fichier créé en V18.01 (qui est au bon fournisseur) mais si on regarde l’onglet Fichiers joints, le fournisseur décrit est en fait un client.
Si je regénère ce fichier en V18.02 le pdf est au nom du client et non plus au nom du fournisseur 

### Environment Version

V18.02

### Environment OS

Windows serveur 2019

### Environment Web server

Apache/2.4.57 (Win64) OpenSSL/3.0.8 PHP/7.4.28

### Environment PHP

PHP/7.4.28

### Environment Database

MySQL 8.0.28

### Attached files

![Capture d'écran 2023-10-20 102203](https://github.com/Dolibarr/dolibarr/assets/89453445/fab15d41-216c-4612-bdee-4f80631ad354)

**Comment by hansemschnokeloch** [comment]
Same as #26291
