### ISSUE TITLE
Inverted label of "Calculation mode" radio field in Accounting -> Report

### ISSUE THREAD

**Issue by nicoleunen** [Dolibarr/dolibarr#26301]
### Bug

"Calculation mode" labels are inverted in Accounting -> Report. Results of "payments" are "documents" and results of "documents" are "payments".

Radio field name is `modecompta`.

![image](https://github.com/Dolibarr/dolibarr/assets/10208113/3c65cba8-21bd-422a-9e01-b9ed5d93b3ba)

### Environment Version

18.0.2

**Comment by aspangaro** [comment]
Bug confirmed. Work on it
