### ISSUE TITLE
Lessc::parenValue Assignment to true in condition of $this->inParens 

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#26308]
https://github.com/Dolibarr/dolibarr/blob/b23dc8478c5122a038524e64ca08dc01d32f211c/htdocs/core/class/lessc.class.php#L3112

This assignment of true to inParens in the condition is likely wrong, ideally a test case should catch it.

**Comment by hansemschnokeloch** [comment]
I don't think there's anything wrong here. We have an open parenthesis so we are "in Parens" and therefore `$this->inParens` has  to be set to true.

```php
        if ($this->literal("(") &&
            ($this->inParens = true) && $this->expression($exp) &&
            $this->literal(")")
            ) {
                $out = $exp;
                $this->inParens = $inParens;
                return true;
        } else {
```

**Comment by mdeweerd** [comment]
On further analysis:

If `$this->literal("(")` is true and then `$this->expression($exp) && $this->literal(")")` is false,  $this->inParens  will not be true but set to the value that `$this->inParens` had before the test while the `(` token is eaten.  However the pointer backtracks to the position it had on entry.

Not recommendable coding because '$this->inParens' likely has to be set to true for the remainder of the calls in the test itself!

I found upstream which seems to have sufficient test cases.

However, I note that an update is proposed for PHP 8.2 compatibilty:
https://github.com/leafo/lessphp/issues/663
