### ISSUE TITLE
Account (from the Chart of Account) for the revenue stamp (sales) not defined in setup

### ISSUE THREAD

**Issue by Essamsamy** [Dolibarr/dolibarr#26319]
### Bug

When importing the sale journal as every month, a new line per invoice is added as "Tax stamp"

### Environment Version

18.0.2

### Attached files

![Screenshot 2023-10-21 205925](https://github.com/Dolibarr/dolibarr/assets/108088042/f8badb01-7f80-4b6e-96a2-c3712ead75e2)
![Screenshot 2023-10-21 210100](https://github.com/Dolibarr/dolibarr/assets/108088042/b67aa9b4-62a5-493e-91e9-cb3c26e29c95)

**Comment by aspangaro** [comment]
Hello, not a bug.

You can define account for "Tax stamp" in Accounting > Configuration > Default accounts

Have a nice day
