### ISSUE TITLE
[bank accounts & invoicing modules] Missing Intermediary BIC / BIC intermédiaire 

### ISSUE THREAD

**Issue by HLFH** [Dolibarr/dolibarr#26312]
### Bug

Hi, 

Intermediary BIC field is missing in the bank accounts & invoicing modules.
It should be added as default.

### Environment Version

18.0.2

### Environment OS

ArchLinux

### Environment Web server

Nginx 1.25.2

### Environment PHP

8.2.11

### Environment Database

mariadb from 11.1.2-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

### Expected and actual behavior

Intermediary BIC field should be present in the bank accounts & invoicing modules after the BIC field.
It is not the case and they should be added as default.

### Steps to reproduce the behavior

Go into the bank accounts or the invoicing module.
Issue an invoice or look at your bank details. Intermediary BIC is missing.

**Comment by aspangaro** [comment]
The intermediate BIC is completely absent. I push a first PR for prepare the database
