### ISSUE TITLE
Bad permissions on documents directory during install

### ISSUE THREAD

**Issue by jfefe** [Dolibarr/dolibarr#2632]
With a fresh install, documents directory is created with wrong permissions.
d--x--x--x

Later, there is error when trying to copy document templates

**Comment by eldy** [comment]
Which package did you use ?
Do you still have pb with package 3.7 ?

**Comment by rdoursenaud** [comment]
No package, same result here straight from git.

**Comment by rdoursenaud** [comment]
Reverified today. 3.7 is not affected, only develop.

**Comment by rdoursenaud** [comment]
Regression is introduced by 2ec55952 which introduced a new `$newmask` parameter to the `dol_mkdir()` function.
The problem is that it defaults to `$conf->global->MAIN_UMASK` which does not exist at installation time.
