### ISSUE TITLE
Error 500 when try to edit an existing line in Intervention

### ISSUE THREAD

**Issue by Studio3Points** [Dolibarr/dolibarr#26337]
### Bug

Error 500 when try to edit an existing line in Intervention

path : /htdocs/fichinter/card.php?id=109

error : this page isn't working

### Environment Version

18.0.2

### Environment OS

Apache

### Environment Web server

Apache

### Environment PHP

8.0.30

**Comment by jmorize** [comment]
Hello same Problem

Error 500 HTTP

Edition d'une fiche d'intervention impossible

Array merge attendu dans ficheinter/card.php line 611

	if ($objectline->fetch($lineid) <= 0) {
			dol_print_error($db);
			exit;
		}

		if ($object->fetch($objectline->fk_fichinter) <= 0) {
			dol_print_error($db);
			exit;
		}

**Comment by jmorize** [comment]
Merci @Hystepik

**Comment by Studio3Points** [comment]
Merci
