### ISSUE TITLE
Activity module

### ISSUE THREAD

**Issue by adiatis** [Dolibarr/dolibarr#26362]
### Feature Request

Call for Collaboration in Developing an All-in-One Activity Module for Task and Ticket Management in Dolibarr

We are seeking collaboration to develop a versatile Activity module that enables the management of various streams of information in one integrated module, evolving into tasks and tickets. Currently, there are separate modules for Tasks, Tickets, Interventions, and more, but none of these modules is comprehensive and user-friendly for many businesses. The process of converting a ticket into a task or intervention is administratively cumbersome, and there is limited flexibility to assign products used in a specific job. Furthermore, the ability to link service products to time spent is lacking, currently only possible at the billing stage and restricted to a single service type for all time spent.

The ideal goal is to create a single Activity object that can represent both tasks, tickets, and interventions, significantly streamlining the management of these various activities. This module is intended to meet the needs of both freelancers and companies with multiple employees, making activity management more efficient and flexible for all Dolibarr users.

We are looking for developers and contributors within the Dolibarr community who are willing to collaborate on developing this comprehensive Activity module. Together, we can create a powerful tool that will significantly enhance the workflow and productivity of Dolibarr users.

Interested? Let me know ;-)

**Comment by JonBendtsen** [comment]
maybe integrate with other open source projects that does the same?

**Comment by josett225** [comment]
Hi @adiatis 
If I understand correctly this has to be a core modification. 
Before starting, I believe this has to be approved by @eldy to avoid losing time in dev cycles.
Thoughts?

**Comment by josett225** [comment]
Still interesting
