### ISSUE TITLE
Error on SQL query on List of services pages

### ISSUE THREAD

**Issue by sebastienserre** [Dolibarr/dolibarr#26369]
### Bug

![2023-10-26_07-54](https://github.com/Dolibarr/dolibarr/assets/3902621/9929b84c-c51a-4f9a-b193-0dd45632885d)

```
Error in request SELECT rowid, FROM llx_llx_entrepot WHERE 1=1 ORDER BY You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM llx_llx_entrepot WHERE 1=1 ORDER BY' at line 1. Check setup of extra parameters.
```

### Environment Version

18.0.2

### Environment OS

Debian

### Environment Web server

Apache/2.4.56

### Environment PHP

php 8.1.23

### Environment Database

MySQL or MariaDB 10.5.21-MariaDB-0+deb11u1

### Environment URL(s)

https://example.com/product/list.php?leftmenu=service&type=1

### Expected and actual behavior

It should list the services

**Comment by hregis** [comment]
@sebastienserre have you an external module ? "Taille" is not a field in Dolibarr by default

**Comment by sebastienserre** [comment]
Thank you @hregis , I 've no idea from which external module it may come.
Do you know how to manage this ?

**Comment by sebastienserre** [comment]
Ok found in a "extra attributes"... don't know why I had this...
The list of service is now working.
