### ISSUE TITLE
__THIRDPARTY_NAME__ Substitution variable not substituted during automatic notifications on proposal validation

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr#26396]
### Bug

The emails I sent to my thirdparties includes the line `__THIRDPARTY_NAME__` when sending notification on proposal validation. If I send manually it actually writes the thirdparty name?

### Environment Version

18.0.1

### Environment OS

upshift dolibarr docker image 18.0.1

### Environment Web server

upshift dolibarr docker image 18.0.1

### Environment PHP

PHP 8.2.10 (cli) (built: Aug 31 2023 20:34:52) (NTS)

### Environment Database

1:11.0.3+maria~ubu2204

### Environment URL(s)

automatic notification during proposal validation

### Expected and actual behavior

actual behaviour: __THIRDPARTY_NAME__ are not substituted during automatic notifications, but it works when sending manually using the same email template.

Expected behavoiur: automatic and manual sending emails would look identical

### Steps to reproduce the behavior

create thirdparty
create contact for thirdparty
setup notifications on proposal validation
create template for proposal validation. I write `Hi __THIRDPARTY_NAME__`
validate draft proposal
Receive email with the literal text `Hi __THIRDPARTY_NAME__`

Manually send email and select the very same template, and the __THIRDPARTY_NAME__ Substitution variable are now actually substituted.

**Comment by JonBendtsen** [comment]
related to https://github.com/Dolibarr/dolibarr/issues/25738

**Comment by inoveaconseil** [comment]
I can't reproduce in 18.0.3

**Comment by JonBendtsen** [comment]
@inoveaconseil I totally agree, the __THIRDPARTY_NAME__ is now in tuxgasy 18.0.3 substituted correct
