### ISSUE TITLE
Missing SQL Migration 15.0 -> 16.0 for llx_c_type_contact

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#26403]
### Bug

In mysql migration from 15.0 to 16.0 there is 2 lines commented:

-- VMYSQL4.3 ALTER TABLE llx_c_type_contact ADD PRIMARY KEY(rowid);
-- VMYSQL4.3 ALTER TABLE llx_c_type_contact CHANGE COLUMN rowid rowid INTEGER NOT NULL AUTO_INCREMENT;

then, dolibarr 16.0 17.0 and other does not have a AUTO_INCREMENT rowid for that table !

**Comment by atm-maxime** [comment]
These commands are correctly executed. They are commented because they must execute only for MYSQL, not PGSQL.
You can still run the /install and replay the 15 > 16 migration.

**Comment by rycks** [comment]
OK, thanks !
