### ISSUE TITLE
Expense report line pdf preview button missing

### ISSUE THREAD

**Issue by rqi14** [Dolibarr/dolibarr#26429]
### Bug

When I upload a file for a line in an expense report, the preview function works normally for a jpg file but not for a pdf file. The preview button is missing. I can see it should be there at [line 2213 in card.php](https://github.com/Dolibarr/dolibarr/blob/440baec6e7b6eba482539d9eb606ae5cd829339f/htdocs/expensereport/card.php#L2213C13-L2213C17). But in reality it is missing, the pdf icon does not take any click.
![image](https://github.com/Dolibarr/dolibarr/assets/26152437/7d797a32-cb7e-4fee-84c1-c396b8f3ae52)

### Environment Version

18.0.2

### Environment OS

Official docker container

### Environment Web server

Official docker container

### Environment PHP

Official docker container

### Environment Database

Official docker container

### Environment URL(s)

Official docker container

**Comment by EchoLoGeek** [comment]
is Imagick enable in your PHP Server ?

**Comment by rqi14** [comment]
> is Imagick enable in your PHP Server ?

TBH not sure. I used the official docker image. Is it enabled in that image?

**Comment by rqi14** [comment]
> is Imagick enable in your PHP Server ?

Hi. I installed Imagick 3.7.0 but it is still not working.

**Comment by rqi14** [comment]
Fixed by installing imagick. An extra step needed is to change the security policy of imagick to allow pdf conversion. ghostscript is also needed in addition to imagick
