### ISSUE TITLE
Issue with changing product type in Dolibarr's GPAO module

### ISSUE THREAD

**Issue by elfibro** [Dolibarr/dolibarr#26442]
### Bug

When changing the product type of a BOM nomenclature from "fabrication" to "disassembly" within a manufacturing order (MO), I expect the system to update the data accordingly, inverting the "toproduce" and "toconsume" values.

### Environment Version

18.0.3

### Environment OS

Linux

### Environment Web server

nginx/1.20.1

### Environment PHP

8.0.23

### Environment Database

10.3.32-MariaDB

### Expected and actual behavior

After creating a BOM nomenclature set to the "fabrication" type within the GPAO module, changing the product type to "disassembly" in an MO does not update the line's status. Even after editing and validating the document, the database records do not reflect the change (they should ideally invert the "toproduce" and "toconsume" values).

### Steps to reproduce the behavior

1.     Create a BOM nomenclature set to the "fabrication" type in the GPAO module.
2.     Create a manufacturing order (MO) using this nomenclature.
3.     Change the product type of the order from "fabrication" to "disassembly".
4.     Validate the change and check the database records.

**Comment by priojk** [comment]
I think this is rather a feature request than a bug. And I am not sure, if a disassembly is just the switched version of a fabrication in the majority of cases.

**Comment by elfibro** [comment]
Thank you for your input. The ability to select assembly or disassembly types is indeed a fundamental feature. The configuration in the BOM is considered the primary setting because it determines the default behavior of the production process. The function is designed to accommodate the disassembly of an assembly and vice versa. It's important that the coding of the type in the BOM reflects the intended use.

However, the issue arises when there is a need to switch the operation type after the BOM has been set. While you are correct that a disassembly is not simply a reversed version of a fabrication, the system's flexibility to adapt to changes during the production planning phase is critical. In certain use cases, the capability to switch from assembly to disassembly on-the-fly is necessary and should be reflected in the system without having to revert to the original BOM settings.

I believe this feature would enhance the adaptability of the production module to various scenarios that may not have been considered during the initial BOM configuration. I appreciate your perspective and hope we can work towards a solution that accommodates a wider range of manufacturing processes.

**Comment by dolibarr95** [comment]
Hello 🙂
I also noticed that when I create an OF in 'Désassemblage/Disassembly' when I validate it it automatically goes to 'Fabrication/Manufacturing'
