### ISSUE TITLE
Missing sending in mail on product card and service card

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#26452]
### Feature Request

Add Email on product card
![image](https://github.com/Dolibarr/dolibarr/assets/3288514/4f787fe7-120b-4967-b22b-f9cc70f7a50f)

Add Email model
![image](https://github.com/Dolibarr/dolibarr/assets/3288514/7216ba61-21fd-49f1-812b-f119afa2083a)

Add Event on email sent
Add Standard Subtitution variable for product/Service

### Use case

- [ ] Send product card for pre-sell
- [ ] Obligation to send information to all client on a product

**Comment by mrcooll** [comment]
I think it's a good feature to add in upcoming versions, and why not de attache a technical manual as PDF in email and send it to one or more clients
