### ISSUE TITLE
Make Objectline_add form in object card behave like the rest of Dolibarr

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2646]
Version: develop

![captura de pantalla 2015-11-07 a las 15 49 08](https://cloud.githubusercontent.com/assets/168744/11015667/1dff82d2-8567-11e5-8e00-f8ce9fa58e74.png)

**Comment by rdoursenaud** [comment]
I believe this is a developer feature request.
You'd want to have it in a template, right?

**Comment by marcosgdf** [comment]
Yes.

Well, I find it a "bug" because it does not meet Dolibarr UI standards. But it can be considered as a Feature Request.

**Comment by accett** [comment]
Also this form don't have the generate pdf format button in case the
contract have been modified.
