### ISSUE TITLE
Select template customize in email notification module

### ISSUE THREAD

**Issue by Farneyaurelio** [Dolibarr/dolibarr#26470]
### Bug

I don't receive the email as configured in the notification module.

### Environment Version

v18.0.2

### Environment OS

Linux

### Environment Web server

Apache 2

### Environment PHP

PHP 7.3

### Environment Database

libmysql - mysqlnd 8.1.16

### Environment URL(s)

email notification module

### Expected and actual behavior

I’m running into something I couldn’t understand. The email notification module allows you to automatically send emails in some situations. I customized an email format for confirming a sales order, as shown below.
![e7ac6593d74464d5d561ad73f8b05a34952a56b1_2_690x97](https://github.com/Dolibarr/dolibarr/assets/116181924/fb56bd0d-60ef-45d9-ba65-e9d284b11f28)
![e9e03542ba20c281209822c632f23f50ef851f71](https://github.com/Dolibarr/dolibarr/assets/116181924/2811ec79-2522-474b-88d9-8b6d5b0e0ba7)
However, I receive the email with this format below, where the information is limited only to the sales order number. This gets in the way a lot, because I have to enter the platform and search for this number to have more information about the confirmed sale.
![4a4751994031a5bed82b09ff3d906f346bc7f261](https://github.com/Dolibarr/dolibarr/assets/116181924/25e8c7d5-5d6e-4c95-88f2-2596d4c113c7)

### Steps to reproduce the behavior

the system generates the email automatically when a sale is closed. But in a different format than formatted.

**Comment by JonBendtsen** [comment]
If you try to send the email manually, and you look in this "Select an email template:" drop down menu, what do you see?

**Comment by Farneyaurelio** [comment]
If you carry out the manual submission procedure, the template works perfectly. However, my question is regarding the automatic email sending that is not accepting the selection of this template.

**Comment by JonBendtsen** [comment]
I know it works fine manually, but I'd like to see what is listed in the dropdown menu, to ensure that there is only one template.

**Comment by Farneyaurelio** [comment]
Yes, here is a printout to view. I currently have 2 templates. But automatic shipping is none of them.

![image](https://github.com/Dolibarr/dolibarr/assets/116181924/0307c6f7-f062-4b01-b99d-2f80ec3d0d00)
![image](https://github.com/Dolibarr/dolibarr/assets/116181924/e99e8339-c9a2-4234-ae68-4aeff2d83e0e)
![image](https://github.com/Dolibarr/dolibarr/assets/116181924/9699a410-eae3-4bcd-b491-cd2d008ce87a)


The automatic email arrives like this:
![280711726-25e8c7d5-5d6e-4c95-88f2-2596d4c113c7](https://github.com/Dolibarr/dolibarr/assets/116181924/f905285d-a655-489c-b1e4-3bce460b0cdf)

**Comment by JonBendtsen** [comment]
> Yes, here is a printout to view. I currently have 2 templates. But automatic shipping is none of them.

Then I think it must be using a different system. What do you see in this place:
Home, setup, emails, email templates

**Comment by Farneyaurelio** [comment]
Yes, this is the location you indicated.

![image](https://github.com/Dolibarr/dolibarr/assets/116181924/2526fe67-0321-4338-b2d4-4478c9481245)
