### ISSUE TITLE
When trying to modify the user, who is migrated from 17.0.2 , I get the error: Identifier already exists. No one can change the user (i.e. admin nor the user himself as well.) 

### ISSUE THREAD

**Issue by apple9004** [Dolibarr/dolibarr#26482]
### Bug

No one can chage the migrated **users** from old version db.

### Environment Version

18.0.2

### Environment OS

linux server

### Environment Database

mySql

### Expected and actual behavior

The users, who is migrated from 17.0.2, are **not** modified nor deleted by administrator or him/her-self. 
The new created users at the Doli 18.0.2 are OK. (modifed or delete) by him/her-self and admin. 

### Steps to reproduce the behavior

Migrate DB from old version(17.0.2) Doli to new version Dolibarr (18.0.2)

**Comment by ksar-ksar** [comment]
Hello,

I can't reproduce on V18.0.3.
I can modify old user without issues.
![image](https://github.com/Dolibarr/dolibarr/assets/35605507/97893f99-aa19-4a5b-9a3b-deb4d18a9770)

![image](https://github.com/Dolibarr/dolibarr/assets/35605507/bd1a8f48-c35a-4376-8887-17798d2bed55)

Do you have any error messages or can you activate Dolibarr logs ?

**Comment by Daviid-P** [comment]
Can you screenshot the error? I can't find `Identifier already exists` in the code. Is it `Identifier XXXX already exists`?

**Comment by apple9004** [comment]
I attache the screen file. The problem, the even user(ID holder) can NOT change him/her-self nor Admin as well.
![NO_change](https://github.com/Dolibarr/dolibarr/assets/26739592/17d4ab71-8af4-4df0-b90a-533ae04d4770)
 
* The users, created at 17.0.1, have the same prbem but new created users at 18.0.x have no problem.
 
When the admin try to add the email address but failed.
![NO_admin](https://github.com/Dolibarr/dolibarr/assets/26739592/724e8c1c-4eb1-4237-bc1a-6e9e8a1657b9)
![NO_admin2](https://github.com/Dolibarr/dolibarr/assets/26739592/375056f0-5af8-4966-9a32-ad5e25fe3fca)

I don't check the 18.0.3 version yet. I hope to update the new version if it is available

**Comment by apple9004** [comment]
> Can you screenshot the error? I can't find `Identifier already exists` in the code. Is it `Identifier XXXX already exists`?

I just add the screen dumps. Thank you.

**Comment by apple9004** [comment]
> Hello,
> 
> I can't reproduce on V18.0.3. I can modify old user without issues. ![image](https://user-images.githubusercontent.com/35605507/281815634-97893f99-aa19-4a5b-9a3b-deb4d18a9770.png)
> 
> ![image](https://user-images.githubusercontent.com/35605507/281815589-bd1a8f48-c35a-4376-8887-17798d2bed55.png)
> 
> Do you have any error messages or can you activate Dolibarr logs ?

Thank you for your intention. I am not familiar with the logs, added or monitoring in docker container. I will check how to check the doli logs. Thank you again.

**Comment by apple9004** [comment]
The problem is solved. I updated from 18.0.2 to 18.0.3. 
Thank you all for your intention.
