### ISSUE TITLE
ticket creation duplicated

### ISSUE THREAD

**Issue by joff13** [Dolibarr/dolibarr#26509]
### Bug

when 2 users create a ticket at the same time, the same id is given by system (eg TS2311-1337)

in version 17.0.2 while confirming the ticket one of 2 users got "duplicated key error" which is expected.

in 18.0.3 the system modify the id but the owner (created by) is wrong: both ticket got the same user. In the relate event user is correct, though 

### Environment Version

18.0.3

### Environment OS

freeBSD 12.4

### Environment Web server

apache

### Environment PHP

8.1

### Environment Database

10.6-MariaDB

### Expected and actual behavior

expected beheviour no error, while creating the ticket and correct user owner

### Steps to reproduce the behavior

create a ticket with 2 user at the same time. To test we just reverse counted (3-2-1-click) on 2 differents machine, 2 persons

**Comment by leninrivas** [comment]
Hi. Me too un version 18.0.1
