### ISSUE TITLE
Fatal error on update 

### ISSUE THREAD

**Issue by sebastienserre** [Dolibarr/dolibarr#26507]
### Bug

Hello,

I'm upgrading to Dolibarr 18.0.3 and occurs this fatal error:

```
[Wed Nov 08 13:29:17.080494 2023] [proxy_fcgi:error] [pid 2557226:tid 139695284631296] [client 82.6078] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Attempt to assign property "enabled" on null in /htdocs/install/inc.php:342\nStack trace:\n#0 /htdocs/install/inc.php(117): conf()\n#1 /htdocs/install/index.php(26): include_once('...')\n#2 {main}\n  thrown in /home/seb/compta.thivinfo.com/htdocs/install/inc.php on line 342

```

Can someone help ?

Regards

### Environment Version

18.0.3

### Environment OS

Debian

### Environment PHP

PHP8.1

### Environment URL(s)

/install/index.php

**Comment by alexandre-janniaux** [comment]
Which version did you start the upgrade from? Is there any special setup on you end that would help reproduce the issue?
