### ISSUE TITLE
Generate technical notice as PDF 

### ISSUE THREAD

**Issue by mrcooll** [Dolibarr/dolibarr#26523]
### Feature Request

Good morning,
I suggest adding a functionality to be able to generate a technical notice for a product following a model with all the details when creating a quote, especially with a check box and also having the choice of ultimately having a single PDF file containing the quote and the technical instructions or have both separately

**Comment by julbroa** [comment]
Dolibarr has the function of attaching the PDF with technical information to the quotes. Doesn't it work for you?

**Comment by mrcooll** [comment]
> Dolibarr has the function of attaching the PDF with technical information to the quotes. Doesn't it work for you?

yes indeed in the case where you are a reseller of the product, but if you are the producer?

**Comment by mrcooll** [comment]
> Dolibarr has the function of attaching the PDF with technical information to the quotes. Doesn't it work for you?

Oh OK i haven't seen that this function already exist. I'm suggesting to add a function that can add a technical notice to a propal pdf
