### ISSUE TITLE
“Bad link. Bad value for parameter modulepart” 

### ISSUE THREAD

**Issue by mrcooll** [Dolibarr/dolibarr#26532]
### Bug

Hello everybody,
So here is my problem, it is the external link to download my documents (quotes, invoices, etc.) which does not work, I have an error message “Bad link. Bad value for parameter module part »

I just tested from the DoliDroid app it works well, but from a mobile browser it's the same problem as on a PC

I enabled both parameters INVOICE_ALLOW_EXTERNAL_DOWNLOAD & PROPOSAL_ALLOW_EXTERNAL_DOWNLOAD but the problem still persists

The problem also affects the GED, I have the same message (“Bad link. Bad value for parameter modulepart”) when downloading a document from a private or public link (same thing)

I also noticed that on my own business card from the menu at the top right, the generated link displays the same error 'Bad link…something…', I noticed that the link is in http://…, so when I test in https:// it works.
I then checked my config.php the parameter $dolibarr_main_force_https it is indeed at the value '1'.
I wonder what would be the cause for these links to be generated in http instead of https

### Environment Version

18.0.2

### Environment OS

Linux

### Environment Web server

Apache server 

### Environment PHP

18

### Environment Database

MySQL

### Environment URL(s)

Externe generated links

### Attached files

[[](url)](https://www.dolibarr.fr/forum/uploads/default/original/2X/1/11b587e9dc6fa336c67880580af6c13830d2d95e.png)

https://www.dolibarr.fr/forum/uploads/default/original/2X/e/e594585042fb83b96e8858b8f8e4ed96efc05422.png

https://www.dolibarr.fr/forum/uploads/default/original/2X/a/a2579220862f4745ffc4ca09c02b340b0bececdb.png

https://www.dolibarr.fr/forum/uploads/default/original/2X/c/cac1d6ee8e2ad7fe8fc696dbf31ab7eda843e754.png

https://www.dolibarr.fr/forum/uploads/default/original/2X/e/e3199ab81d09e4df8b4800a6ddc24540af0228da.png

**Comment by hregis** [comment]
@mrcooll you have "https" in "$dolibarr_main_url_root" in conf.php?

**Comment by mrcooll** [comment]
> @mrcooll you have "https" in "$dolibarr_main_url_root" in conf.php?

Yes Indeed

**Comment by mrcooll** [comment]
> @mrcooll you have "https" in "$dolibarr_main_url_root" in conf.php?

Perfect bro it was that parameter, it was in http:// insteed of https://...
everythink works well now

Thank you
