### ISSUE TITLE
Divided lines in the bank account balance

### ISSUE THREAD

**Issue by Themiller12** [Dolibarr/dolibarr#26536]
### Bug

[EN] We migrated from version 16 to version 18.0.2. Since, some accounts are divided into several lines in the balance. The total remains correct, but impossible to find a common point between these divided lines. Yesterday, we updated to version 18.0.3.
On 2023 some lines have disappeared, only 2 accounts remain (5121110 and 602250), but on 2022 it's worse than before, new divided lines appeared. I can send more screeshots or give you access to our Dolibarr online if needed. 

[FR] Nous avons migré de la version 16 à la version 18.0.2. Depuis, certains comptes sont divisés en plusieurs lignes dans la balance. Le total reste bon, mais impossible de trouver un point commun entre ces lignes divisées. Hier, nous avons fait la mise à jour vers la version 18.0.3, sur 2023 certaines lignes ont disparues, il n'en reste plus que sur 2 comptes (5121110 et 602250), par contre sur 2022 cela a empiré, d'autres lignes sont apparues. Je peux envoyer d'autres captures d'écran ou vous donner la main sur notre instance en ligne. 

### Environment Version

18.0.3

### Environment OS

Debian 5.10.197-1

### Environment Web server

Apache 2

### Environment PHP

8.1.25

### Environment Database

mysqlnd 8.1.25 

### Environment URL(s)

accountancy/bookkeeping/balance.php

### Attached files

![exemple 1](https://github.com/Dolibarr/dolibarr/assets/45743169/35af795e-601d-4ea6-a28b-7f1b82dd42e0)
![exemple 2](https://github.com/Dolibarr/dolibarr/assets/45743169/921e9706-cf5b-412b-858c-09481d7f2789)

**Comment by aspangaro** [comment]
Hello,

I proposed a fix. 
Account groupings are done by account name and account number. This should only be done by account number, because if you have modified or imported data, a different account name is enough to break the grouping...

**Comment by aspangaro** [comment]
Can you test this fix and give us some returns ?

**Comment by Themiller12** [comment]
> Can you test this fix and give us some returns ?

I just tried and I think everything is fixed thank you so much you're awesome !! We'll check next week with my accountant and I'll keep you posted :)

**Comment by saudgaronlines** [comment]
Bagaimana cara menambah atau memasukan saldo ke perusahaan sebagai modal awal dari investor maupun pribadi?
