### ISSUE TITLE
Add new internal barcode engine 'tcpdf'

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#2655]
Add new barcode engine which uses the build in tcpdf barcode encoding

**Comment by fappels** [comment]
Reason for this request, new Dolibarr users often start generating EAN13 or ISBN codes without following the EAN guidelines described in http://wiki.dolibarr.org/index.php?title=Module_Barcode. This because the other commonly used codes like C39 or C128 are not included in the standard Dolibarr installation. So I will like to add more barcode types to the basic Dolibarr installation.

Started some coding on my request:

![dolibarr - barcode setup](https://cloud.githubusercontent.com/assets/4573808/7337212/0c935e12-ec22-11e4-8ee0-1e01104ac2d9.png)

Will also need some rewiting of printing barcode sheets, tcpdf barcode png's don't show barcode text.
So will do next:
- Create new class htdocs/core/class/pdf_label.class.php from htdocs/core/modules/printsheet/doc/pdf_standardlabel.class.php
- extend htdocs/core/modules/printsheet/doc/pdf_standardlabel.class.php, htdocs/core/modules/member/doc/pdf_standard.class.php and new htdocs/core/modules/printsheet/doc/pdf_tcpdflabel.class.php from htdocs/core/class/pdf_label.class.php
- htdocs/core/modules/printsheet/doc/pdf_tcpdflabel.class.php will use barcode functions from pdf object (which do show code text) in stead of showing temp image file.

**Comment by eldy** [comment]
Great !!  I am waiting for the PR :-)
