### ISSUE TITLE
Packages for NAS

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2656]
- [ ] QNAP
- [ ] Turnkeylinux
- [ ] OpenNAS
- [ ] Synology
- [ ] …

**Comment by ndrosis** [comment]
Hi  @rdoursenaud  i will try next week to create a package for Synology.

**Comment by rdoursenaud** [comment]
Hey @ndrosis.
I just reported it during last devcamp while we were video conferencing with the new german community manager.
He thought these were good outlets to help the software gain popularity.
AFAIK @defrance has already worked on something for the Synology platform. I just forgot to ping him…

**Comment by defrance** [comment]
Exact, one of my friend have worked on it but it's expérimental and not realy stable
créate a syhnology package is not really complex, the main problem is to automatise the process and skip some install step (create the database by example)

**Comment by rdoursenaud** [comment]
@defrance To skip/force some install step, you can use a `forced.install.php` file.
Just generate it within your package.
I improved it a lot with #4673 and even provided a fully featured sample configuration file that should make everything clear: https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/install.forced.sample.php

**Comment by tehnoinstyle** [comment]
Hi.
Where can I find a package for Synology NAS?
Or install the manually?
Thankyou.

**Comment by casati-dolibarr** [comment]
I have both 3.8.2 and 3.9.0GA up and runníng on ZYXEL NAS540.

It was easy to install & to configure with already available mySQL/phpMyAdmin package and Dolibarr source tarballs.

And it "purrs" ... ;-)

Given the fact, that someone should already be experienced administering servers & ERPs before he starts dealing with Dolibarr, I doubt the value of an investment into "packaging" it for any of the consumer NASs on the market.

Best regards

**Comment by tehnoinstyle** [comment]
@casati-dolibarr Thanks for the answer, I will try.
