### ISSUE TITLE
Unable to delete a "Reduction or Available Credit". Attempting to refund an invoice using another invoice generates an SQL error.

### ISSUE THREAD

**Issue by guiltekmdion** [Dolibarr/dolibarr#26563]
### Bug

**### Français**
Titre du Ticket : Erreur SQL lors de la suppression d'une réduction ou d'un crédit

Description du Problème :
Il est impossible de supprimer une "Réduction ou crédit disponible". Lorsque nous tentons de rembourser une facture en utilisant une autre facture, cela génère une erreur SQL.

Étapes pour Reproduire :

Effectuer le remboursement d'une facture directement sur un avoir pour le "rembourser" avant de le faire payer sur une autre facture.
Observer le message d'erreur similaire à celui mentionné dans ce [post](https://www.dolibarr.fr/forum/t/you-have-an-error-in-your-sql-syntax/44136/3).
Dans les logs de la base de données, la requête suivante semble bloquer : "UPDATE llxfc_facture set paye=0, fk_statut=1 WHERE (type IN (2,3) AND rowid = 171".
Résultat Attendu :
Le système devrait supprimer la ligne de remboursement sans erreur.

Résultat Observé :
La suppression ne se réalise pas, une erreur SQL "[DB_ERROR_SYNTAX] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ‹ › at line 1" apparaît.

Environnement :
Le problème est observé depuis la version 18.0 et persiste dans la version 18.3.

**### English**
Ticket Title: SQL Error When Deleting a Discount or Credit

Problem Description:
Unable to delete a "Reduction or Available Credit". Attempting to refund an invoice using another invoice generates an SQL error.

Steps to Reproduce:

Refund an invoice directly on a credit note to "refund" it before paying it on another invoice.
Observe the error message similar to the one mentioned in this [post](https://www.dolibarr.fr/forum/t/you-have-an-error-in-your-sql-syntax/44136/3).
In the database logs, the following query seems to be causing a block: "UPDATE llxfc_facture set paye=0, fk_statut=1 WHERE (type IN (2,3) AND rowid = 171".
Expected Result:
The system should delete the refund line without any errors.

Observed Result:
The deletion does not occur due to an SQL error "[DB_ERROR_SYNTAX] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ‹ › at line 1".

Environment:
This issue has been observed since version 18.0 and continues in version 18.3.

### Environment Version

18.3

### Environment OS

nginx

### Environment PHP

7.4

### Environment Database

mysql

### Expected and actual behavior

Expected Result:
The system should delete the refund line without any errors.

Observed Result:
The deletion does not occur due to an SQL error "[DB_ERROR_SYNTAX] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ‹ › at line 1".

### Steps to reproduce the behavior

Steps to Reproduce:

Refund an invoice directly on a credit note to "refund" it before paying it on another invoice.
Observe the error message similar to the one mentioned in this [post](https://www.dolibarr.fr/forum/t/you-have-an-error-in-your-sql-syntax/44136/3).
In the database logs, the following query seems to be causing a block: "UPDATE llxfc_facture set paye=0, fk_statut=1 WHERE (type IN (2,3) AND rowid = 171".

**Comment by ksar-ksar** [comment]
FIX : #26517
