### ISSUE TITLE
User cannot be deleted. Maybe it is associated to Dolibarr entities.

### ISSUE THREAD

**Issue by apple9004** [Dolibarr/dolibarr#26582]
### Bug

When I try to remove an old user, who is no more use. 
I deactivated the user ID and try to delete the ID but the Doli messages "**User cannot be deleted. Maybe it is associated to Dolibarr entities.**"
I've delete any request by the old ID in Doli but the result is the same; cannot erase the old ID. 

### Environment Version

18.0.3

### Environment OS

linux server

### Expected and actual behavior

delete the ID, which is no more use

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/26739592/1a715849-09fd-468c-8243-8d0b4364a9a7)

**Comment by hregis** [comment]
@apple9004 maybe this user is linked to customer invoices or others?

**Comment by apple9004** [comment]
> @apple9004 maybe this user is linked to customer invoices or others?

So I try to remove all list about the user ID's (not 100% sure) Let me check them again. Thank you for your concerning.
I'm just suspicius that the removed record might be concened.

**Comment by gschratzer** [comment]
I tried to delete users in version 17 and version 18.0.3 and it was working for me! Looks like you have dataentries on this users I guess.

**Comment by apple9004** [comment]
In the 19.0.1 version, it works correctly. Thank for all who were work on.
