### ISSUE TITLE
Réf produit fournisseur empty

### ISSUE THREAD

**Issue by gstax** [Dolibarr/dolibarr#26584]
### Bug

Hi,

The field Réf produit fournisseur (supplier) is empty in the supplier invoice page fourn/facture/card.php.

The bug seems to have appeared around mid-august (v17 -> v18), see

[https://www.dolibarr.fr/forum/t/v18-ref-produit-fournisseur-dans-facture-fournisseur-est-maintenant-vide-bug/44162](url).

I unfortunately don't have a patch to provide.

Thank you!

### Environment Version

18

### Environment OS

Debian

### Environment Web server

Apache

### Environment PHP

8.1

### Environment Database

Mysql

**Comment by EchoLoGeek** [comment]
The problem does not seem to be a display problem but a problem with recording data when creating the invoice.

When the SUPPLIER_INVOICE_WITH_PREDEFINED_PRICES_ONLY variable is enabled in the configuration, it seems to work.

However, I do not know the other impacts of this variable.

**Comment by gstax** [comment]
Setting this variable does indeed work for new invoices but not for old ones.

**Comment by EchoLoGeek** [comment]
Yes, because if this variable is not set, the variable does not fill and does not save.
I've found what happens:
In v17 and before, when you select a product when creating the invoice, the supplier ref field was hidden and automatically filled in. On v18, the field is no longer hidden and remains empty.

**Comment by EchoLoGeek** [comment]
Changes are :
https://github.com/Dolibarr/dolibarr/commit/2c940c5bf85a4759b67b90708c88c917f8665766
https://github.com/Dolibarr/dolibarr/commit/b2a7894f724858113f1d27d6cdd6b1436789c881
