### ISSUE TITLE
ADD Systemwide default unit

### ISSUE THREAD

**Issue by tronx2100** [Dolibarr/dolibarr#26602]
### Feature Request

Adding a default unit for all is so simple.

adding this line to /core/class/html.form.class.php

on line 4765 insert 

        /* tronx2100 for default unit P */
        if(!empty($conf->global->PRODUCT_DEFAULT_UNIT) && $conf->global->PRODUCT_DEFAULT_UNIT) {
                if ($selected == '' || $selected == 1 ){
                  $selected = $conf->global->PRODUCT_DEFAULT_UNIT;
                }
        }
        /* end */

and change global $langs; to global $conf,$langs;   in line 4759

and then ADD 
PRODUCT_DEFAULT_UNIT    28 
to  the additional settings and done. 
Now you have Piece systemwide

here the fill function:

    public function selectUnits($selected = '', $htmlname = 'units', $showempty = 0, $unit_type = '')
    {
        global $conf,$langs;

        $langs->load('products');

        $return = '<select class="flat" id="' . $htmlname . '" name="' . $htmlname . '">';
        
        /* tronx2100 for default unit P */
        if(!empty($conf->global->PRODUCT_DEFAULT_UNIT) && $conf->global->PRODUCT_DEFAULT_UNIT) {
                if ($selected == '' || $selected == 1 ){
                  $selected = $conf->global->PRODUCT_DEFAULT_UNIT;
                }
        }
        /* end */
        
        $sql = "SELECT rowid, label, code FROM " . $this->db->prefix() . "c_units";
        $sql .= ' WHERE active > 0';
        if (!empty($unit_type)) {
            $sql .= " AND unit_type = '" . $this->db->escape($unit_type) . "'";
        }
        $sql .= " ORDER BY sortorder";

        $resql = $this->db->query($sql);
        if ($resql && $this->db->num_rows($resql) > 0) {
            if ($showempty) {
                $return .= '<option value="none"></option>';
            }

            while ($res = $this->db->fetch_object($resql)) {
                $unitLabel = $res->label;
                if (!empty($langs->tab_translate['unit' . $res->code])) {    // check if Translation is available before
                    $unitLabel = $langs->trans('unit' . $res->code) != $res->label ? $langs->trans('unit' . $res->code) : $res->label;
                }

                if ($selected == $res->rowid) {
                    $return .= '<option value="' . $res->rowid . '" selected>' . $unitLabel . '</option>';
                } else {
                    $return .= '<option value="' . $res->rowid . '">' . $unitLabel . '</option>';
                }
            }
            $return .= '</select>';
        }
        return $return;
    }

**Comment by sonikf** [comment]
Hi @tronx2100 

PRODUCT_USE_UNITS is considered unstable, from my experience you can use it safely to output label in pdfs other than that use at your own risk. 

See discussions here https://github.com/Dolibarr/dolibarr/issues/25370
