### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by raqibulhassan** [Dolibarr/dolibarr#26616]
# Bug
*Creates phantom stock movement entries*

## Environment
- **Version**: 18.0.3
- **OS**: Linux
- **Web server**: Apache/2.4.6
- **PHP**: cgi-fcgi 7.4.33
- **Database**: MySQL or MariaDB 5.5.5-10.7.8-MariaDB
- **URL(s)**: /erp/htdocs/product/inventory/inventory.php?id=6

## Expected and actual behavior
*The function must do stock corrections according to the real quantity input but in some random SKUs alongside the correct entries it generates another movement entry with a random number so in some SKUs there are 2 stock movement entries where it should be only one. And the movement reference numbers of the phantom entries are not stipulated on the top of the page*

## Steps to reproduce the behavior
*When using the function as usual it creates the erroneous entries randomly without any explanation.*

## [Attached files]

<img width="1376" alt="Screenshot 2023-11-16 at 2 11 13 AM" src="https://github.com/Dolibarr/dolibarr/assets/65133694/7b5ee579-1766-43cc-bf43-5c6790a1ffd9">
<img width="1369" alt="Screenshot 2023-11-16 at 2 09 32 AM" src="https://github.com/Dolibarr/dolibarr/assets/65133694/1e472b0d-c9f8-4b59-bd92-27e381a7690d">
<img width="1422" alt="Screenshot 2023-11-16 at 2 09 08 AM" src="https://github.com/Dolibarr/dolibarr/assets/65133694/a35e8b71-d4f7-4753-b7fe-09353e0fbd8d">
<img width="1371" alt="Screenshot 2023-11-16 at 2 07 46 AM" src="https://github.com/Dolibarr/dolibarr/assets/65133694/afcc7267-ff65-4916-8f3d-ab13d328bd7b">

**Comment by W1W1-M** [comment]
Hello, in order to help project maintainers please give your bug report a proper title.
