### ISSUE TITLE
Add Products in interventions

### ISSUE THREAD

**Issue by bettersafe** [Dolibarr/dolibarr#26654]
### Feature Request

It would be good to be able to add products from the database to the intervention. This would make it possible to create a shippement and an invoice.

In other words, a combination of delivery note (products) and intervention (service order).

### Use case

We currently use the interventions in such a way that the technician at the customer either creates the intervention out of an order, a ticket or a even a new intervention.

The work performed is written down there, but the technicians have to write the material in the description, because it is not possible to add products.

It would be possible to create a new order with the material used and insert it there and then write the intervention out of the order, but this is very cumbersome and impractical.

If it were possible to insert products directly in the intervention, there could be no failures with the article number and also when creating the invoice from it.

You would only have to insert the link to the table and book out the material from the corresponding warehouse.

**Comment by dolibit-ut** [comment]
Maybe i don't unterstand your intention.
But it is always possible to add products (from your catalog) to an intervention.
This is an option in the intervention module.

**Comment by BurksEngineering** [comment]
From what I can tell, intervention *templates* support products and services, but interventions themselves do not. #26057 looks like a work in progress to add products and services as lines to interventions.
