### ISSUE TITLE
Wrong install wizard redirection

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2666]
Version: develop

If you are in some page of Dolibarr like '/comm/propal/note.php' and then remove the file conf/conf.php, it is expected that Dolibarr redirects you to the install wizard. But it redirects you to http://dolibarr.local/comm/install/index.php, so you get a "File not found" error.

**Comment by eldy** [comment]
I'am afraid there is no real solution to this.
If conf file is not here, there is no way to know what is relative url to use to find dolibarr. PHP-Apache does not provide any global variable for this. So code was done to work when url is the most common one, i mean the main page index.php.
If we use a redirect to /install/index.php and server is inside an alias http://myserver/myalias, then the redirect will be break too, so relative url, working in some cases only, keeps the best choice i see.

**Comment by rdoursenaud** [comment]
Can't we use the known path of the caller to infer the install directory path?
In the example given, we know where comm/propal/note.php is supposed to be located relative to the install/ directory.
