### ISSUE TITLE
Missing substitution variables

### ISSUE THREAD

**Issue by evarisk-micka** [Dolibarr/dolibarr#26676]
### Feature Request

In list when choosing massaction to send object by mail, in the list of available substitution variables we need the following:
__ONLINE_PAYMENT_URL__
__ONLINE_PAYMENT_TEXT_AND_URL__
__THIRDPARTY_NAME__ 
__PROJECT_NAME__

**Comment by JonBendtsen** [comment]
ohh, this seems really interesting. Do you know if this fixes any of these bugs and feature requests?


BUG    https://github.com/Dolibarr/dolibarr/issues/25738
BUG    https://github.com/Dolibarr/dolibarr/issues/26396

Feature    https://github.com/Dolibarr/dolibarr/issues/26577
