### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by apio-sys** [Dolibarr/dolibarr#26681]
### Feature Request

I noticed from the changelog that the PHP 8.2 compatibility is not yet finalised :+1: 

***** ChangeLog for 18.0.0 compared to 17.0.0 *****
NEW: PHP 8.2 compatibility (not yet complete).

but it would be great if that could be completed asap. Debian 12 current stable (currently 12.2) ships with 8.2 by default and I never find it a good idea to fiddle around with Debian packages and use 3rd party (Sury) to install other PHP versions. It can work but it is usually synonym with unexpected trouble. If you are a Debian fan - especially for it's proven stability without searching to be always "latest version" - you probably don't want to do that. And you neither would want to start a brand new server for a client with 11.8 oldstable... I think it's worthwhile trying to keep up with the official Debian releases which are always prudent and stable. At present I'm stuck to install several servers and reluctant to "downgrade" (ie. reinstall) the OS to oldstable... I can imagine I'm not alone in this particular situation.

### Use case

Fresh Debian 12.2 / PHP 8.2 server from customer wanting to use Dolibarr.

### Suggested implementation

Nothing much to suggest other then rendering it compatible. If some stuff is flagged as deprecated, it's not a big issue and could wait until next major release. But at least all obsolete stuff should be fixed (and maybe if it is, the warning in the auto-upgrader could could advise in that direction).

**Comment by JonBendtsen** [comment]
Until the transition to PHP8.2 is complete, one method of getting the PHP version and Dolibarr version you want could be to run Dolibarr as a container. This is what I do, and the users will not feel any difference.

**Comment by coxe87b** [comment]
I would also appreciate 8.2 support. I can't even get installed using php8.2 it would seem... It hangs at step1.php

**Comment by apio-sys** [comment]
That would suggest you have another issue there. The full compatibility not yet there will not prevent you from installing it, it will just warn you (and you will have to deal with some known or unknown bugs). If your install hangs there is probably another reason. Did you find some clue in your webserver logs?

**Comment by apio-sys** [comment]
I am now running 18.0.4 since a few days/weeks on 2 (small) production instances and it looks like the last compatibility issues with PHP 8.2 (i.e. the official package in Debian 12 current) are ironed out. Hence I think the 8.2 compatibility is complete. But maybe others have more to add here. For me it can be closed. off.
