### ISSUE TITLE
MAIN_DIRECT_STATUS_UPDATE has failed on v18.0.3

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#26740]
### Bug

The quick status button for product are not working on v 18.0.3 sine i just upgrade from 16.0.5 .

### Environment Version

18.0.3 

### Environment OS

 Debian 4.19.67-2+deb10u2

### Environment Web server

Apache/2.4.38 (Debian)

### Environment PHP

7.4.3

### Environment Database

MariaDB 5.5.5-10.3.39

### Environment URL(s)

/product/card.php?id=550

### Expected and actual behavior

Should could change status of product by click quick button .

**Comment by frederic34** [comment]
![image](https://github.com/Dolibarr/dolibarr/assets/3624836/36f0d2df-92a4-40b6-b252-8694141f4831)
