### ISSUE TITLE
Store money values as cents (Only integers)

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#26755]
### Feature Request

I'm sure this is a known problem but I've only found mentions of rounding errors, not any suggestion to switch to integers only.

https://dba.stackexchange.com/questions/333275/sum-of-round-vs-round-of-sum/333277

I'm sure this kind of change may cause a lot of problems for already store data but I think it's necessary.

columns with double type
---
| table_name | column_name | 
| --- | --- | 
| llx_accounting_bookkeeping | debit | 
| llx_accounting_bookkeeping | credit | 
| llx_accounting_bookkeeping | montant | 
| llx_accounting_bookkeeping | multicurrency_amount | 
| llx_accounting_bookkeeping_tmp | debit | 
| llx_accounting_bookkeeping_tmp | credit | 
| llx_accounting_bookkeeping_tmp | montant | 
| llx_accounting_bookkeeping_tmp | multicurrency_amount | 
| llx_actioncomm | durationp | 
| llx_adherent_type | amount | 
| llx_asset | reversal_amount_ht | 
| llx_asset | acquisition_value_ht | 
| llx_asset | recovered_vat | 
| llx_asset | qty | 
| llx_asset | disposal_amount_ht | 
| llx_asset_depreciation | depreciation_ht | 
| llx_asset_depreciation | cumulative_depreciation_ht | 
| llx_asset_depreciation_options_economic | degressive_coefficient | 
| llx_asset_depreciation_options_economic | amount_base_depreciation_ht | 
| llx_asset_depreciation_options_economic | amount_base_deductible_ht | 
| llx_asset_depreciation_options_economic | total_amount_last_depreciation_ht | 
| llx_asset_depreciation_options_fiscal | degressive_coefficient | 
| llx_asset_depreciation_options_fiscal | amount_base_depreciation_ht | 
| llx_asset_depreciation_options_fiscal | amount_base_deductible_ht | 
| llx_asset_depreciation_options_fiscal | total_amount_last_depreciation_ht | 
| llx_bank | amount | 
| llx_bank | amount_main_currency | 
| llx_blockedlog | amounts | 
| llx_bom_bom | qty | 
| llx_bom_bom | efficiency | 
| llx_bom_bom | duration | 
| llx_bom_bomline | qty | 
| llx_bom_bomline | efficiency | 
| llx_bordereau_cheque | amount | 
| llx_budget_lines | amount | 
| llx_chargesociales | amount | 
| llx_commande | amount_ht | 
| llx_commande | remise_percent | 
| llx_commande | remise_absolue | 
| llx_commande | remise | 
| llx_commande | total_tva | 
| llx_commande | localtax1 | 
| llx_commande | localtax2 | 
| llx_commande | total_ht | 
| llx_commande | total_ttc | 
| llx_commande | multicurrency_tx | 
| llx_commande | multicurrency_total_ht | 
| llx_commande | multicurrency_total_tva | 
| llx_commande | multicurrency_total_ttc | 
| llx_commandedet | tva_tx | 
| llx_commandedet | localtax1_tx | 
| llx_commandedet | localtax2_tx | 
| llx_commandedet | qty | 
| llx_commandedet | remise_percent | 
| llx_commandedet | remise | 
| llx_commandedet | price | 
| llx_commandedet | subprice | 
| llx_commandedet | total_ht | 
| llx_commandedet | total_tva | 
| llx_commandedet | total_localtax1 | 
| llx_commandedet | total_localtax2 | 
| llx_commandedet | total_ttc | 
| llx_commandedet | buy_price_ht | 
| llx_commandedet | multicurrency_subprice | 
| llx_commandedet | multicurrency_total_ht | 
| llx_commandedet | multicurrency_total_tva | 
| llx_commandedet | multicurrency_total_ttc | 
| llx_commande_fournisseur | amount_ht | 
| llx_commande_fournisseur | remise_percent | 
| llx_commande_fournisseur | remise | 
| llx_commande_fournisseur | total_tva | 
| llx_commande_fournisseur | localtax1 | 
| llx_commande_fournisseur | localtax2 | 
| llx_commande_fournisseur | total_ht | 
| llx_commande_fournisseur | total_ttc | 
| llx_commande_fournisseur | multicurrency_tx | 
| llx_commande_fournisseur | multicurrency_total_ht | 
| llx_commande_fournisseur | multicurrency_total_tva | 
| llx_commande_fournisseur | multicurrency_total_ttc | 
| llx_commande_fournisseurdet | tva_tx | 
| llx_commande_fournisseurdet | localtax1_tx | 
| llx_commande_fournisseurdet | localtax2_tx | 
| llx_commande_fournisseurdet | qty | 
| llx_commande_fournisseurdet | remise_percent | 
| llx_commande_fournisseurdet | remise | 
| llx_commande_fournisseurdet | subprice | 
| llx_commande_fournisseurdet | total_ht | 
| llx_commande_fournisseurdet | total_tva | 
| llx_commande_fournisseurdet | total_localtax1 | 
| llx_commande_fournisseurdet | total_localtax2 | 
| llx_commande_fournisseurdet | total_ttc | 
| llx_commande_fournisseurdet | multicurrency_subprice | 
| llx_commande_fournisseurdet | multicurrency_total_ht | 
| llx_commande_fournisseurdet | multicurrency_total_tva | 
| llx_commande_fournisseurdet | multicurrency_total_ttc | 
| llx_commande_fournisseur_dispatch | cost_price | 
| llx_contratdet | tva_tx | 
| llx_contratdet | localtax1_tx | 
| llx_contratdet | localtax2_tx | 
| llx_contratdet | qty | 
| llx_contratdet | remise_percent | 
| llx_contratdet | subprice | 
| llx_contratdet | price_ht | 
| llx_contratdet | remise | 
| llx_contratdet | total_ht | 
| llx_contratdet | total_tva | 
| llx_contratdet | total_localtax1 | 
| llx_contratdet | total_localtax2 | 
| llx_contratdet | total_ttc | 
| llx_contratdet | buy_price_ht | 
| llx_contratdet | multicurrency_subprice | 
| llx_contratdet | multicurrency_total_ht | 
| llx_contratdet | multicurrency_total_tva | 
| llx_contratdet | multicurrency_total_ttc | 
| llx_c_availability | qty | 
| llx_c_ecotaxe | price | 
| llx_c_exp_tax_range | range_ik | 
| llx_c_format_cards | leftmargin | 
| llx_c_format_cards | topmargin | 
| llx_c_format_cards | spacex | 
| llx_c_format_cards | spacey | 
| llx_c_format_cards | width | 
| llx_c_format_cards | height | 
| llx_c_format_cards | custom_x | 
| llx_c_format_cards | custom_y | 
| llx_c_holiday_types | newbymonth | 
| llx_c_lead_status | percent | 
| llx_c_price_global_variable | value | 
| llx_c_revenuestamp | taux | 
| llx_c_tva | taux | 
| llx_delivery | total_ht | 
| llx_deliverydet | qty | 
| llx_deliverydet | subprice | 
| llx_deliverydet | total_ht | 
| llx_deplacement | km | 
| llx_don | amount | 
| llx_element_resources | duree | 
| llx_eventorganization_conferenceorboothattendee | amount | 
| llx_expeditiondet | qty | 
| llx_expeditiondet_batch | qty | 
| llx_expedition_package | value | 
| llx_expensereport | total_ht | 
| llx_expensereport | total_tva | 
| llx_expensereport | localtax1 | 
| llx_expensereport | localtax2 | 
| llx_expensereport | total_ttc | 
| llx_expensereport | multicurrency_tx | 
| llx_expensereport | multicurrency_total_ht | 
| llx_expensereport | multicurrency_total_tva | 
| llx_expensereport | multicurrency_total_ttc | 
| llx_expensereport_det | qty | 
| llx_expensereport_det | subprice | 
| llx_expensereport_det | value_unit | 
| llx_expensereport_det | remise_percent | 
| llx_expensereport_det | tva_tx | 
| llx_expensereport_det | localtax1_tx | 
| llx_expensereport_det | localtax2_tx | 
| llx_expensereport_det | total_ht | 
| llx_expensereport_det | total_tva | 
| llx_expensereport_det | total_localtax1 | 
| llx_expensereport_det | total_localtax2 | 
| llx_expensereport_det | total_ttc | 
| llx_expensereport_det | multicurrency_subprice | 
| llx_expensereport_det | multicurrency_total_ht | 
| llx_expensereport_det | multicurrency_total_tva | 
| llx_expensereport_det | multicurrency_total_ttc | 
| llx_expensereport_ik | coef | 
| llx_expensereport_ik | ikoffset | 
| llx_expensereport_rules | amount | 
| llx_facture | amount | 
| llx_facture | remise_percent | 
| llx_facture | remise_absolue | 
| llx_facture | remise | 
| llx_facture | total_tva | 
| llx_facture | localtax1 | 
| llx_facture | localtax2 | 
| llx_facture | revenuestamp | 
| llx_facture | total_ht | 
| llx_facture | total_ttc | 
| llx_facture | retained_warranty | 
| llx_facture | multicurrency_tx | 
| llx_facture | multicurrency_total_ht | 
| llx_facture | multicurrency_total_tva | 
| llx_facture | multicurrency_total_ttc | 
| llx_facturedet | tva_tx | 
| llx_facturedet | localtax1_tx | 
| llx_facturedet | localtax2_tx | 
| llx_facturedet | qty | 
| llx_facturedet | remise_percent | 
| llx_facturedet | remise | 
| llx_facturedet | subprice | 
| llx_facturedet | price | 
| llx_facturedet | total_ht | 
| llx_facturedet | total_tva | 
| llx_facturedet | total_localtax1 | 
| llx_facturedet | total_localtax2 | 
| llx_facturedet | total_ttc | 
| llx_facturedet | buy_price_ht | 
| llx_facturedet | situation_percent | 
| llx_facturedet | multicurrency_subprice | 
| llx_facturedet | multicurrency_total_ht | 
| llx_facturedet | multicurrency_total_tva | 
| llx_facturedet | multicurrency_total_ttc | 
| llx_facturedet_rec | tva_tx | 
| llx_facturedet_rec | localtax1_tx | 
| llx_facturedet_rec | localtax2_tx | 
| llx_facturedet_rec | qty | 
| llx_facturedet_rec | remise_percent | 
| llx_facturedet_rec | remise | 
| llx_facturedet_rec | subprice | 
| llx_facturedet_rec | price | 
| llx_facturedet_rec | total_ht | 
| llx_facturedet_rec | total_tva | 
| llx_facturedet_rec | total_localtax1 | 
| llx_facturedet_rec | total_localtax2 | 
| llx_facturedet_rec | total_ttc | 
| llx_facturedet_rec | buy_price_ht | 
| llx_facturedet_rec | multicurrency_subprice | 
| llx_facturedet_rec | multicurrency_total_ht | 
| llx_facturedet_rec | multicurrency_total_tva | 
| llx_facturedet_rec | multicurrency_total_ttc | 
| llx_facture_fourn | amount | 
| llx_facture_fourn | remise | 
| llx_facture_fourn | tva | 
| llx_facture_fourn | localtax1 | 
| llx_facture_fourn | localtax2 | 
| llx_facture_fourn | total | 
| llx_facture_fourn | total_ht | 
| llx_facture_fourn | total_tva | 
| llx_facture_fourn | total_ttc | 
| llx_facture_fourn | multicurrency_tx | 
| llx_facture_fourn | multicurrency_total_ht | 
| llx_facture_fourn | multicurrency_total_tva | 
| llx_facture_fourn | multicurrency_total_ttc | 
| llx_facture_fourn_det | pu_ht | 
| llx_facture_fourn_det | pu_ttc | 
| llx_facture_fourn_det | qty | 
| llx_facture_fourn_det | remise_percent | 
| llx_facture_fourn_det | tva_tx | 
| llx_facture_fourn_det | localtax1_tx | 
| llx_facture_fourn_det | localtax2_tx | 
| llx_facture_fourn_det | total_ht | 
| llx_facture_fourn_det | tva | 
| llx_facture_fourn_det | total_localtax1 | 
| llx_facture_fourn_det | total_localtax2 | 
| llx_facture_fourn_det | total_ttc | 
| llx_facture_fourn_det | multicurrency_subprice | 
| llx_facture_fourn_det | multicurrency_total_ht | 
| llx_facture_fourn_det | multicurrency_total_tva | 
| llx_facture_fourn_det | multicurrency_total_ttc | 
| llx_facture_fourn_det_rec | pu_ht | 
| llx_facture_fourn_det_rec | pu_ttc | 
| llx_facture_fourn_det_rec | qty | 
| llx_facture_fourn_det_rec | remise_percent | 
| llx_facture_fourn_det_rec | tva_tx | 
| llx_facture_fourn_det_rec | localtax1_tx | 
| llx_facture_fourn_det_rec | localtax2_tx | 
| llx_facture_fourn_det_rec | total_ht | 
| llx_facture_fourn_det_rec | total_tva | 
| llx_facture_fourn_det_rec | total_localtax1 | 
| llx_facture_fourn_det_rec | total_localtax2 | 
| llx_facture_fourn_det_rec | total_ttc | 
| llx_facture_fourn_det_rec | multicurrency_subprice | 
| llx_facture_fourn_det_rec | multicurrency_total_ht | 
| llx_facture_fourn_det_rec | multicurrency_total_tva | 
| llx_facture_fourn_det_rec | multicurrency_total_ttc | 
| llx_facture_fourn_rec | amount | 
| llx_facture_fourn_rec | remise | 
| llx_facture_fourn_rec | localtax1 | 
| llx_facture_fourn_rec | localtax2 | 
| llx_facture_fourn_rec | total_ht | 
| llx_facture_fourn_rec | total_tva | 
| llx_facture_fourn_rec | total_ttc | 
| llx_facture_fourn_rec | multicurrency_tx | 
| llx_facture_fourn_rec | multicurrency_total_ht | 
| llx_facture_fourn_rec | multicurrency_total_tva | 
| llx_facture_fourn_rec | multicurrency_total_ttc | 
| llx_facture_rec | amount | 
| llx_facture_rec | remise | 
| llx_facture_rec | remise_percent | 
| llx_facture_rec | remise_absolue | 
| llx_facture_rec | total_tva | 
| llx_facture_rec | localtax1 | 
| llx_facture_rec | localtax2 | 
| llx_facture_rec | revenuestamp | 
| llx_facture_rec | total_ht | 
| llx_facture_rec | total_ttc | 
| llx_facture_rec | multicurrency_tx | 
| llx_facture_rec | multicurrency_total_ht | 
| llx_facture_rec | multicurrency_total_tva | 
| llx_facture_rec | multicurrency_total_ttc | 
| llx_fichinter | duree | 
| llx_fichinterdet_rec | total_ht | 
| llx_fichinterdet_rec | subprice | 
| llx_fichinterdet_rec | tva_tx | 
| llx_fichinterdet_rec | localtax1_tx | 
| llx_fichinterdet_rec | localtax2_tx | 
| llx_fichinterdet_rec | qty | 
| llx_fichinterdet_rec | remise_percent | 
| llx_fichinterdet_rec | remise | 
| llx_fichinterdet_rec | price | 
| llx_fichinterdet_rec | total_tva | 
| llx_fichinterdet_rec | total_localtax1 | 
| llx_fichinterdet_rec | total_localtax2 | 
| llx_fichinterdet_rec | total_ttc | 
| llx_fichinterdet_rec | buy_price_ht | 
| llx_fichinter_rec | duree | 
| llx_holiday | nb_open_day | 
| llx_holiday_users | nb_holiday | 
| llx_hrm_skill | temps_theorique | 
| llx_inventorydet | qty_stock | 
| llx_inventorydet | qty_view | 
| llx_inventorydet | qty_regulated | 
| llx_inventorydet | pmp_real | 
| llx_inventorydet | pmp_expected | 
| llx_loan | capital | 
| llx_loan | insurance_amount | 
| llx_loan | nbterm | 
| llx_loan | rate | 
| llx_loan | capital_position | 
| llx_loan_schedule | amount_capital | 
| llx_loan_schedule | amount_insurance | 
| llx_loan_schedule | amount_interest | 
| llx_localtax | amount | 
| llx_mrp_mo | qty | 
| llx_mrp_production | qty | 
| llx_multicurrency_rate | rate | 
| llx_paiement | amount | 
| llx_paiement | multicurrency_amount | 
| llx_paiement | pos_change | 
| llx_paiementcharge | amount | 
| llx_paiementfourn | amount | 
| llx_paiementfourn | multicurrency_amount | 
| llx_paiementfourn_facturefourn | amount | 
| llx_paiementfourn_facturefourn | multicurrency_tx | 
| llx_paiementfourn_facturefourn | multicurrency_amount | 
| llx_paiement_facture | amount | 
| llx_paiement_facture | multicurrency_tx | 
| llx_paiement_facture | multicurrency_amount | 
| llx_payment_donation | amount | 
| llx_payment_expensereport | amount | 
| llx_payment_loan | amount_capital | 
| llx_payment_loan | amount_insurance | 
| llx_payment_loan | amount_interest | 
| llx_payment_salary | salary | 
| llx_payment_salary | amount | 
| llx_payment_various | amount | 
| llx_payment_vat | amount | 
| llx_pos_cash_fence | opening | 
| llx_pos_cash_fence | cash | 
| llx_pos_cash_fence | card | 
| llx_pos_cash_fence | cheque | 
| llx_prelevement_bons | amount | 
| llx_prelevement_facture_demande | amount | 
| llx_prelevement_lignes | amount | 
| llx_product | price | 
| llx_product | price_ttc | 
| llx_product | price_min | 
| llx_product | price_min_ttc | 
| llx_product | cost_price | 
| llx_product | tva_tx | 
| llx_product | localtax1_tx | 
| llx_product | localtax2_tx | 
| llx_product | stock | 
| llx_product | pmp | 
| llx_product | fifo | 
| llx_product | lifo | 
| llx_product_association | qty | 
| llx_product_attribute_combination | variation_price | 
| llx_product_attribute_combination | variation_weight | 
| llx_product_attribute_combination_price_level | variation_price | 
| llx_product_batch | qty | 
| llx_product_customer_price | price | 
| llx_product_customer_price | price_ttc | 
| llx_product_customer_price | price_min | 
| llx_product_customer_price | price_min_ttc | 
| llx_product_customer_price | tva_tx | 
| llx_product_customer_price | localtax1_tx | 
| llx_product_customer_price | localtax2_tx | 
| llx_product_customer_price_log | price | 
| llx_product_customer_price_log | price_ttc | 
| llx_product_customer_price_log | price_min | 
| llx_product_customer_price_log | price_min_ttc | 
| llx_product_customer_price_log | tva_tx | 
| llx_product_customer_price_log | localtax1_tx | 
| llx_product_customer_price_log | localtax2_tx | 
| llx_product_fournisseur_price | price | 
| llx_product_fournisseur_price | quantity | 
| llx_product_fournisseur_price | remise_percent | 
| llx_product_fournisseur_price | remise | 
| llx_product_fournisseur_price | unitprice | 
| llx_product_fournisseur_price | charges | 
| llx_product_fournisseur_price | tva_tx | 
| llx_product_fournisseur_price | localtax1_tx | 
| llx_product_fournisseur_price | localtax2_tx | 
| llx_product_fournisseur_price | multicurrency_tx | 
| llx_product_fournisseur_price | multicurrency_unitprice | 
| llx_product_fournisseur_price | multicurrency_price | 
| llx_product_fournisseur_price | packaging | 
| llx_product_fournisseur_price_log | price | 
| llx_product_fournisseur_price_log | quantity | 
| llx_product_fournisseur_price_log | multicurrency_tx | 
| llx_product_fournisseur_price_log | multicurrency_unitprice | 
| llx_product_fournisseur_price_log | multicurrency_price | 
| llx_product_perentity | pmp | 
| llx_product_price | price | 
| llx_product_price | price_ttc | 
| llx_product_price | price_min | 
| llx_product_price | price_min_ttc | 
| llx_product_price | tva_tx | 
| llx_product_price | localtax1_tx | 
| llx_product_price | localtax2_tx | 
| llx_product_price | multicurrency_tx | 
| llx_product_price | multicurrency_price | 
| llx_product_price | multicurrency_price_ttc | 
| llx_product_pricerules | var_percent | 
| llx_product_pricerules | var_min_percent | 
| llx_product_price_by_qty | price | 
| llx_product_price_by_qty | quantity | 
| llx_product_price_by_qty | remise_percent | 
| llx_product_price_by_qty | remise | 
| llx_product_price_by_qty | unitprice | 
| llx_product_price_by_qty | multicurrency_tx | 
| llx_product_price_by_qty | multicurrency_price | 
| llx_product_price_by_qty | multicurrency_price_ttc | 
| llx_product_stock | reel | 
| llx_projet | opp_percent | 
| llx_projet | opp_amount | 
| llx_projet | budget_amount | 
| llx_projet | price_registration | 
| llx_projet | price_booth | 
| llx_projet_task | duration_effective | 
| llx_projet_task | planned_workload | 
| llx_projet_task | budget_amount | 
| llx_projet_task_time | task_duration | 
| llx_projet_task_time | thm | 
| llx_propal | price | 
| llx_propal | remise_percent | 
| llx_propal | remise_absolue | 
| llx_propal | remise | 
| llx_propal | total_ht | 
| llx_propal | total_tva | 
| llx_propal | localtax1 | 
| llx_propal | localtax2 | 
| llx_propal | total_ttc | 
| llx_propal | multicurrency_tx | 
| llx_propal | multicurrency_total_ht | 
| llx_propal | multicurrency_total_tva | 
| llx_propal | multicurrency_total_ttc | 
| llx_propaldet | tva_tx | 
| llx_propaldet | localtax1_tx | 
| llx_propaldet | localtax2_tx | 
| llx_propaldet | qty | 
| llx_propaldet | remise_percent | 
| llx_propaldet | remise | 
| llx_propaldet | price | 
| llx_propaldet | subprice | 
| llx_propaldet | total_ht | 
| llx_propaldet | total_tva | 
| llx_propaldet | total_localtax1 | 
| llx_propaldet | total_localtax2 | 
| llx_propaldet | total_ttc | 
| llx_propaldet | buy_price_ht | 
| llx_propaldet | multicurrency_subprice | 
| llx_propaldet | multicurrency_total_ht | 
| llx_propaldet | multicurrency_total_tva | 
| llx_propaldet | multicurrency_total_ttc | 
| llx_salary | salary | 
| llx_salary | amount | 
| llx_societe | capital | 
| llx_societe | customer_rate | 
| llx_societe | supplier_rate | 
| llx_societe | remise_client | 
| llx_societe | remise_supplier | 
| llx_societe | localtax1_value | 
| llx_societe | localtax2_value | 
| llx_societe | outstanding_limit | 
| llx_societe | order_min_amount | 
| llx_societe | supplier_order_min_amount | 
| llx_societe_remise | remise_client | 
| llx_societe_remise_except | amount_ht | 
| llx_societe_remise_except | amount_tva | 
| llx_societe_remise_except | amount_ttc | 
| llx_societe_remise_except | tva_tx | 
| llx_societe_remise_except | multicurrency_amount_ht | 
| llx_societe_remise_except | multicurrency_amount_tva | 
| llx_societe_remise_except | multicurrency_amount_ttc | 
| llx_societe_remise_supplier | remise_supplier | 
| llx_societe_rib | max_total_amount_of_all_payments | 
| llx_societe_rib | total_amount_of_all_payments | 
| llx_stock_mouvement | value | 
| llx_stock_mouvement | price | 
| llx_subscription | subscription | 
| llx_supplier_proposal | price | 
| llx_supplier_proposal | remise_percent | 
| llx_supplier_proposal | remise_absolue | 
| llx_supplier_proposal | remise | 
| llx_supplier_proposal | total_ht | 
| llx_supplier_proposal | total_tva | 
| llx_supplier_proposal | localtax1 | 
| llx_supplier_proposal | localtax2 | 
| llx_supplier_proposal | total_ttc | 
| llx_supplier_proposal | multicurrency_tx | 
| llx_supplier_proposal | multicurrency_total_ht | 
| llx_supplier_proposal | multicurrency_total_tva | 
| llx_supplier_proposal | multicurrency_total_ttc | 
| llx_supplier_proposaldet | tva_tx | 
| llx_supplier_proposaldet | localtax1_tx | 
| llx_supplier_proposaldet | localtax2_tx | 
| llx_supplier_proposaldet | qty | 
| llx_supplier_proposaldet | remise_percent | 
| llx_supplier_proposaldet | remise | 
| llx_supplier_proposaldet | price | 
| llx_supplier_proposaldet | subprice | 
| llx_supplier_proposaldet | total_ht | 
| llx_supplier_proposaldet | total_tva | 
| llx_supplier_proposaldet | total_localtax1 | 
| llx_supplier_proposaldet | total_localtax2 | 
| llx_supplier_proposaldet | total_ttc | 
| llx_supplier_proposaldet | buy_price_ht | 
| llx_supplier_proposaldet | multicurrency_subprice | 
| llx_supplier_proposaldet | multicurrency_total_ht | 
| llx_supplier_proposaldet | multicurrency_total_tva | 
| llx_supplier_proposaldet | multicurrency_total_ttc | 
| llx_tva | amount | 
| llx_user | thm | 
| llx_user | tjm | 
| llx_user | salary | 
| llx_user | salaryextra | 
| llx_user | weeklyhours | 
| llx_user_employment | salary | 
| llx_user_employment | salaryextra | 
| llx_user_employment | weeklyhours | 
| llx_workstation_workstation | thm_operator_estimated | 
| llx_workstation_workstation | thm_machine_estimated | 

### Use case

Avoid 0.01 cents errors in invoices and accounting.

### Suggested implementation

Store values and do calculations with integers, then, when printing divide by 10^max number of decimals allowed to be shown then round to the number of decimals the user wishes to see.

Judging by `DOUBLE(24,8)` I assume the developer never intended to store more than 8 decimals so:

An invoice like:
tax_base 10.57
vat 10% 1.06
total 11.63

Would be stored in the database like:
total_ht 1057000000
total_tva 105700000
total_ttc 1162700000

shown as:
total_ht (1057000000/10^8) = 10.57
total_tva (105700000/10^8) = 1.057
total_ttc (1162700000/10^8) = 11.627

rounded as:
total_ht 10.57 = 10.57
total_tva 1.057 = 1.06
total_ttc 11.627 = 11.63

**Comment by hansemschnokeloch** [comment]
ETH can have up to 18 decimals

**Comment by Daviid-P** [comment]
> ETH can have up to 18 decimals

Sure, but if we're working with PHP we have to store the values as integers. A 64 bit unsigned integer can only go up to 18446744073709551615

That leave us with 8 fractional digits (09551615) and 12 integer digits (184467440737)

I don't think Dolibarr is geared toward crypto but if you chose to use 18 decimals you would be left with 2 integer digits, meaning you couldn't sell anything for over 18.446744073709551615 of whatever cryptocurrency you use.

Meanwhile 184467440737.09552 currency, even in the weakest Iranian Rial is 4,363,511.27 USD, probably not something a Dolibarr user will reach in a single invoice, and if someone does they'd probably move onto a more specialized software for accounting.

**Comment by hansemschnokeloch** [comment]
> Sure, but if we're working with PHP we have to store the values as integers

Why not use decimals ? 
https://dev.mysql.com/doc/refman/8.0/en/precision-math-decimal-characteristics.html
https://www.postgresql.org/docs/current/datatype-numeric.html

Beside of that, the rouding flaw given as example with python on [stackexchange](https://dba.stackexchange.com/questions/333275/sum-of-round-vs-round-of-sum/333277) doesn't exist with php.
The php rounding algorithm is more accurate that the one used with python https://wiki.php.net/rfc/rounding

**Comment by Daviid-P** [comment]
DECIMAL is fine for MySQL but once we're in PHP we still have to deal with floating point precision errors so why not get rid of floating point numbers all together?

**Comment by hansemschnokeloch** [comment]
How do you plan to handle data entry which will always be in decimal form ?
For example data import from excel files, data from external software (prestashop, woocommerce...)

**Comment by jawira** [comment]
I agree using floats is not a good idea, float's precision is system dependent, it can be configured in `php.ini` <https://www.php.net/manual/en/ini.core.php#ini.precision>.

IMHO even if you display floats to user, they should be stored as integers. This is called _Money pattern_, with a PHP implementation <https://github.com/moneyphp/money> (which also explains why you shouldn't store money as float).
