### ISSUE TITLE
Allow in future invoice

### ISSUE THREAD

**Issue by VoidScute** [Dolibarr/dolibarr#26764]
### Feature Request

Allow to create invoice for a future date

### Use case

In order to prepare invoices for next months instead of waiting and do it one by one. 

### Suggested implementation

delete some "security" checks

**Comment by sonikf** [comment]
Hi @HumanG33k,
It is already implemented through the use of template invoice.
Enable and setup module Scheduled jobs for automation
Create a draft invoice for a client and hit convert into template invoice button, from there you can set creation date, reccurence etc.

**Comment by ksar-ksar** [comment]
You have also an Hidden option for that : 
INVOICE_MAX_FUTURE_DELAY ► Numbers of seconds allowed for billing in the future ► (V14.0)

**Comment by leonbrehme** [comment]
Great to know! I think the templates are to much work for just one invocie. But the tag for INVOICE_MAX_FUTURE_DELAY should solve this for all other use cases.

Is there a document, where all tags like this one are stored? (sorry if this a dump questions - right know i'm not that familiar with the documentation)

**Comment by ksar-ksar** [comment]
> Is there a document, where all tags like this one are stored? (sorry if this a dump questions - right know i'm not that familiar with the documentation)

https://wiki.dolibarr.org/index.php?title=Setup_Other
