### ISSUE TITLE
Install error with dolideb

### ISSUE THREAD

**Issue by Sebastian1984** [Dolibarr/dolibarr#2681]
Hi, I tried to install  fresh dolideb and it is unable because it can't find php5-common so there seems to be something wrong. 
tried to install fresh on debian wheezy dolibarr 3.7
Thx for fixing.
I think it has got a new adress because I also ran into this in 3.5.4 when trying to install it over the deb

**Comment by Sebastian1984** [comment]
after installing it (php5 apache...) over synaptic all the packages it seems to work, but not out of the box

**Comment by Sebastian1984** [comment]
Totally crap was unable to install over deb... will give it a retry... setting back the virtualbox

**Comment by eldy** [comment]
Does the dolideb package were downloaded from sourceforge ?

**Comment by Sebastian1984** [comment]
Yes it was the dolideb from sourcefourge. But I had that problem before, 
when I start a fresh machine of debian it simply doesn't find all 
dependencies.... 3.5.4 and 3.7.0

Am 23.04.2015 um 21:17 schrieb Laurent Destailleur:

**Comment by eldy** [comment]
The dolideb package include a dependency on php5. And php5 package has a dependency on php5-common.
So you should not get this error.
How do you launch the dolideb install ? With
apt-get install dolidebfile.deb 
?

**Comment by rdoursenaud** [comment]
@eldy that would not work. The correct command would be `dpkg -i dolidebfile.deb`.

**Comment by rdoursenaud** [comment]
I tried reproducing and didn't meet your problem apart from the fact that dpkg does not install dependencies automatically. But that's a well known Debian quirk which requires you to run `apt-get -f install` to resolve dependencies.

The procedure was:
- Install a fresh Debian Wheezy
- wget dolibarr_3.7.1-3_all.deb from Sourceforge.net
- `dpkg -i dolibarr_3.7.1-3_all.deb`
- `apt-get -f install`

**But** I met another bug. There is a syntax error in /etc/apache2/conf.d/dolibarr.conf at line 30.
It reads `Order allow, deny` but should be a single argument: `Order allow,deny` (Notice there is no space before deny).
After solving that and restarting apache, the setup procedure ran fine.
Fix incoming!

**Comment by rdoursenaud** [comment]
Fix for Apache syntax error in #3535
