### ISSUE TITLE
Create Shipment on Sales Order and PHP 8.2 incompatibility (Works with PHP 7.4)

### ISSUE THREAD

**Issue by TheRealBeef** [Dolibarr/dolibarr#26843]
### Bug

When attempting to create a shipment, the webpage crashes silently and refuses to finish loading the buttons for creating the shipment or loading the debug bar at the bottom to see what happens. There is unfortunately nothing written to the dolibarr or apache logs either so I wasn't able to figure out how to fix this issue.

### Environment Version

18.0.3

### Environment OS

LinuxMint 21

### Environment Web server

Apache 2

### Environment PHP

8.2

### Expected and actual behavior

Neither the buttons to create the shipment nor the debug bar at the bottom load. When viewing page source it appears to be incomplete as it ends abruptly.

![c2548562d1e120bce13214c6a05c922b6e12f7e4](https://github.com/Dolibarr/dolibarr/assets/84393940/be163e08-3873-4deb-b2b8-c350b4c29c22)

More details on the forum post https://www.dolibarr.org/forum/t/no-buttons-to-create-shipment/24593/7

### Steps to reproduce the behavior

Attempt to create a shipment on a Sales Order. It will fail to load if you're using PHP 8.2

I was able to resolve the issue on my particular install by following the steps at https://ostechnix.com/how-to-switch-between-multiple-php-versions-in-ubuntu/ and changing back to PHP 7.4 instead, so it seems to indicate it is a compatibility/syntax issue with 8.2.

**Comment by ksar-ksar** [comment]
Hello,

Thanks, just to let you know that Dolibarr V18 is not yet fully compatible with PHP V8.2.
https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog#L408

**Comment by TheRealBeef** [comment]
> Hello,
> 
> Thanks, just to let you know that Dolibarr V18 is not yet fully compatible with PHP V8.2. https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog#L408

Yeah, that's what I figured - I just wish it threw me some kind of error in a log somewhere so I could help improve that compatibility instead of presenting an issue with no pull request ... :(
