### ISSUE TITLE
BANK, Account statements : loose linked files if change Ref. 

### ISSUE THREAD

**Issue by Be0rn01** [Dolibarr/dolibarr#26844]
### Bug

If we change or correct the reference name of an Account statement on the Bank account, the linked files were not available anymore. But if we change back the ref for the previous name, the files will be refund.

### Environment Version

18.03

### Environment Web server

Debian GNU/Linux 8.11 (jessie)

### Environment PHP

8.1.22

### Environment Database

MariaDB 10.4.18

### Expected and actual behavior

We expect that the attached files were all the time available independently of the ref name.

### Steps to reproduce the behavior

1. On the 'Bank entries' make a 'reconcile' with few of your entries and use the value '20231113'
2. On the 'Account statement' open the statement '20231113' and upload an attached file ex. 'EXTRACT_20231112.pdf'
3. On the 'Account statement' edit the statement '20231113' and change the name of it for '20231112'

Now you can check back the attached file of the account statement '20231112' and there is no attached file..

But if you change back the ref for '20231113' and check again, the attached file will be back.

**Comment by Daviid-P** [comment]
I think that happens with invoices too.
On llx_ecm_files filepath and filename are not updated IIRC.
