### ISSUE TITLE
Bug: édition facture génération pdf

### ISSUE THREAD

**Issue by MaxTassart** [Dolibarr/dolibarr#26842]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
les génération de factures pdf pour Tellus Ceram sont impossibles depuis hier. j'ai deux factures à envoyer et ne peux le faire : 
"Cette page ne fonctionne pasImpossible de traiter cette demande via www.tassart.snsgestion.fr à l'heure actuelle.
HTTP ERROR 500"

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 8.2.10
- **Database**: MySQL or MariaDB 5.7.42-log
- **URL(s)**: /htdocs/compta/facture/list.php?restore_lastsearch_values=1

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by rycks** [comment]
Bonjour @MaxTassart 
je pense que le mieux est de faire appel à votre prestataire qui s'est chargé de l'installation & de la mise à jour de  votre serveur dolibarr ... 

Si vous n'en avez pas je vous invite à prendre contact auprès d'un partenaire labellisé expert dolibarr dont la liste est ici : https://www.dolibarr.org/partners.php

En l'occurence votre problème est très probablement lié à la version PHP que vous utilisez ... ou un module complémentaire.
