### ISSUE TITLE
Offers: sign online - does not support stylus on touch displays

### ISSUE THREAD

**Issue by leonbrehme** [Dolibarr/dolibarr#26857]
### Bug

I tried to use a stylus to sign offers directly in Dolibarr. The problem is that it's only supported to use the stylus to sccroll and click. The drawing pad is not supportet.

Intereseting detail: When you load the page for the first time - and if you tip directly on the sign fild, the stylus will work until you lift it. Than it's broken agin.

From my point of view it looks like the sign fild only excepts mous input. Im using ans USI stylus and differnt convertable Chromebooks.

### Environment Version

17

### Environment OS

ChromeOS

**Comment by JonBendtsen** [comment]
Not to diminish or invalidate your bug report, just some extra info for developers.

I just tried signing a proposal on my iPad Pro, both with my finger and my apple pencil and both worked fine. I did it in Firefox browser.
