### ISSUE TITLE
Order by unity, invoice by weight ?

### ISSUE THREAD

**Issue by JLBA** [Dolibarr/dolibarr#26867]
### Feature Request

Hello,
How can I do when customers order pieces number (1 chicken, 300 apples) but invoiced are by exact weight (2.4 kg, 34.3 kg...) ?
Thanks.

### Use case

For example : 
- order : 1 chicken -> invoice : 2.4kg x price/kg
- order :  300 apples -> invoice 34.3 kg x price/kg

**Comment by JonBendtsen** [comment]
What if you add a Complementary Attribute to the proposal, order and invoice lines which is a synonym for quantity, like number, bulk, load, quota, batch, pile, portion, sum, variety, lot, allotment, pieces, ... and then in the quantity you write the weight, and the price is pr. quantity? 

This would probably influence your stock management, but if you don't need that?

Maybe your stock management should be in grams and not kilograms. So you sell 2400 grams of chicken and 34300 grams of apples?
