### ISSUE TITLE
Simple text line in orders and invoices

### ISSUE THREAD

**Issue by JLBA** [Dolibarr/dolibarr#26868]
### Feature Request

Hi,
Just for better orders and invoices presentation, I miss a simple text line or text box that will better than using service or product line with 0 in price, qty...
Thankscould we have the ability to add simple text line for not using product or service line with 0 in price, qty... ?

**Comment by ksar-ksar** [comment]
Hello,

I agree that it would be nice.

In the meantime, you can use subtotal external module that does the job : https://github.com/ATM-Consulting/dolibarr_module_subtotal

It seems that someone tried in the past : https://github.com/Dolibarr/dolibarr/issues/18380

**Comment by JLBA** [comment]
Thanks @ksar-ksar for your answer. I'll try it even if last release is 2018. Hope it will come soon a core feature...
