### ISSUE TITLE
sendEmailsRemindersOnInvoiceDueDate attachment not present

### ISSUE THREAD

**Issue by everysoftbe** [Dolibarr/dolibarr#26862]
### Bug

When send mail with cron, not attachment present.

### Environment Version

18.0.2

### Environment OS

Ubuntu server 22.04

### Environment PHP

8.1

### Environment Database

mysql

**Comment by JonBendtsen** [comment]
can you include a link to download the PDF?

**Comment by everysoftbe** [comment]
Yes it's possible, but in version 17.x the pdf was automatically included
as an attachment.

Le lun. 27 nov. 2023 à 20:57, Jon Bendtsen ***@***.***> a
écrit :

**Comment by rycks** [comment]
that was a very very old bug ... i fix it on 14.0 ... as i remember there was never ever file automatically joined on sendEmailsRemindersOnInvoiceDueDate call ...

**Comment by rycks** [comment]
and @eldy will be super happy because i fix it on 14.0 branch 🌴

**Comment by eldy** [comment]
My ubderstanding is that this has been implemented into v17. 

Broken in v18 ?
