### ISSUE TITLE
Adding extrafields to product Batch / Lot / Expiry Date 

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2687]
@fappels said : 
14/01/2015
Dispatching products can have a lot of parameters.
So I propose to add extrafields to productbatch and work like this:
In Product Stock Tab: 
show list of batches with link on batch code.
When clicked, new card is shown with all parameters of batch including created extrafields.
The card will also contain the "correctstock" and "transfer" buttons like the stock card.
In Supplier Dispatch Tab: also add 'batch code with link' to dispatched list.
When clicked also show editable batch card
Add 'return to stock button' or 'return to dispatch button' depending on Source.

@BebZ said : 
There are many extrafields that could be created... 
For each batch/lot (received or stocked) :
-locations (stock's shelve, row, column...etc..)
-barcodes (if specific ones printed for the "batch / expiry" couple), especially RFID / NFC codes. 
-colli number (from supplier, so you may know how it transited)
-notes...

**Comment by BebZ** [comment]
it is really closely related to 
#2274 New: Added Extrafields for Supplier invoice lines and Supplier order lines

@aschio

**Comment by simnandez** [comment]
We are currently developing a module for the batch/ expiry date / sales deatline. You can test it if you have Dolibarr >=3.7.0 and you have activated MAIN_FEATURES_LEVEL to 2

**Comment by BebZ** [comment]
Oh, I use it since centuries with Mobilid and my mobile phone + bluetooth barcode sanner :) for my stock, supplier receptions, and shipments, etc...
Maybe i was not clear, but it's a feat req. to know if some people is interested in having extrafields linked to a specific "batch", do you see what i mean ?
it's to add some more characterisitcs to "lots", maybe it's a bit too much details for a Dolibarr user... ?

**Comment by simnandez** [comment]
Ops! Sorry, now I understand

**Comment by BebZ** [comment]
can you add maybe the label discussion... useful to get some extrafields on taches to store more infos on the batch with an external application like Mobilid...
(measurements, weight, localisation in stock, specific 2d barcode printed... etc...)

**Comment by onoffspices** [comment]
Great to see support for batch/ expiry date / sales dateline. Can these be also printed to packlists?

**Comment by BebZ** [comment]
this is printed  on the shipments (merou and rouget models)

**Comment by BebZ** [comment]
https://github.com/Dolibarr/dolibarr/commit/5ea9fc7467f22281c5525f18055ead800e85fb98
