### ISSUE TITLE
Double discount on updateline in contract

### ISSUE THREAD

**Issue by tomtom0013** [Dolibarr/dolibarr#26871]
### Bug

When you update a line on a contract to change the discount, the discount is applied twice.

### Environment Version

17, 18

### Environment OS

Debian

### Environment Web server

Apache

### Environment PHP

php 8.0

### Environment Database

mysql

### Expected and actual behavior

1. create a contract
2. add a line
3. save the line
4. modify the line
5. change discount
6. save
7. see the new price with discount

### Steps to reproduce the behavior

1. create a contract
2. add a line
3. save the line
4. modify the line
5. change discount
6. save
7. the price in database is incorrect

### Attached files

Workaround: on file contrat/card.php

change : 
			// update price_ht with discount
			// TODO Use object->updateline instead objedtline->update

			$price_ht =  price2num(GETPOST('elprice'), 'MU');
			$remise_percent = price2num(GETPOST('elremise_percent'), 2);
			if ($remise_percent > 0) {
				$remise = round(($price_ht * $remise_percent / 100), 2);
				$price_ht = ($price_ht - $remise);
			}

to : 

			// update price_ht with discount
			// TODO Use object->updateline instead objedtline->update

			$price_ht =  price2num(GETPOST('elprice'), 'MU');
			$remise_percent = price2num(GETPOST('elremise_percent'), 2);
			if ($remise_percent > 0) {
				$remise = round(($price_ht * $remise_percent / 100), 2);
				//$price_ht = ($price_ht - $remise);
			}

**Comment by hansemschnokeloch** [comment]
I confirm that total_ht in database is currently incorrect if discount is updated on a contract line
