### ISSUE TITLE
Bug: Wrong translations of Permission descriptions in "Variante de produits“ (French localisation)

### ISSUE THREAD

**Issue by kupfair** [Dolibarr/dolibarr#26898]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 18.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.33
- **Database**: MySQL or MariaDB 5.5.5-10.4.25-MariaDB-1:10.4.25+maria~stretch-log
- **URL(s)**: /user/group/perms.php?id=1

## Expected and actual behavior
The first permission in "Variantes de produits" in French version is still in English and states “Read attributes of variants" instead of “Lire les attributs des variantes produits“. 
The second permission (in French) incorrectly states “Lire les attributs des variantes produits“, whereas it should say “Ecrire les attributs des variantes produits“.
## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
<img width="695" alt="details" src="https://github.com/Dolibarr/dolibarr/assets/147659158/d5815358-b452-44b7-8f78-c858a9ac9b41">

**Comment by ksar-ksar** [comment]
Hello,

The translations issues, other than US language must be corrected on https://app.transifex.com/dolibarr-association/dolibarr/dashboard/
Not on GitHub.
