### ISSUE TITLE
Barcode module: too few arguments to function modPhpbarcode

### ISSUE THREAD

**Issue by HLFH** [Dolibarr/dolibarr#26912]
### Bug

When I try to open the barcode module configuration page.
2023/12/01 06:45:51 [error] 2729620#2729620: *742754 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function modPhpbarcode::info(), 0 passed in /usr/share/dolibarr/htdocs/admin/barcode.php on line 184 and exactly 1 expected in /usr/share/dolibarr/htdocs/core/modules/barcode/doc/phpbarcode.modules.php:64
Stack trace:
#0 /usr/share/dolibarr/htdocs/admin/barcode.php(184): modPhpbarcode->info()
#1 {main}
  thrown in /usr/share/dolibarr/htdocs/core/modules/barcode/doc/phpbarcode.modules.php on line 64" while reading upstream, client: MYIPV6ADDRESS, server: MY_DOMAIN_NAME, request: "GET /admin/barcode.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php%3Fsearch_keyword%3Dcode HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm-legacy/php-fpm.sock:", host: "MY_DOMAIN_NAME", referrer: "MY_DOMAIN_NAME/admin/modules.php"

### Environment Version

18

### Environment OS

Arch Linux

### Environment Web server

nginx version: nginx/1.25.3

### Environment PHP

PHP 8.1.26 (fpm-fcgi) (built: Nov 23 2023 18:18:52) Copyright (c) The PHP Group Zend Engine v4.1.26, Copyright (c) Zend Technologies     with Zend OPcache v8.1.26, Copyright (c), by Zend Technologies

### Environment Database

mariadb from 11.2.2-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

### Environment URL(s)

https://MY_DOMAIN_NAME/admin/barcode.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php%3Fsearch_keyword%3Dcode

### Expected and actual behavior

the barcode module configuration page is blank and should not

### Steps to reproduce the behavior

open the barcode module configuration page and see it blank

### Attached files

<img width="1207" alt="Screenshot 2023-12-01 at 06 47 21" src="https://github.com/Dolibarr/dolibarr/assets/2359059/40f4d29c-a68d-4b7f-8015-f30eacbba036">

**Comment by GroupeVingeanne** [comment]
Same thing on 19.0.0-beta 
PHP 8.1.26
Nginx 1.25.3
