### ISSUE TITLE
No result when I search for product to add kits

### ISSUE THREAD

**Issue by GroupeVingeanne** [Dolibarr/dolibarr#26913]
### Bug

Date: 20231201110144
Dolibarr: 19.0.0-beta - https://www.dolibarr.org
Niveau de fonctionnalités: 2
PHP: 8.1.26
Serveur: nginx/1.25.3
OS: Linux erp 6.2.16-14-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-14 (2023-09-19T08:17Z) x86_64
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0

Url sollicitée: /product/composition/card.php?id=66
Referer: https://erp.mydomain.com/product/composition/card.php?id=66
Gestionnaire de menu: eldy_menu.php

Modules/Applications: twofactorauth, multicompany, syslog, user, api, resource, cron, agenda, propal, contrat, loan, supplier_proposal, margin, reception, paymentbybanktransfer, barcode, prelevement, bookmark, fckeditor, variants, printing, opensurvey, accounting, export, import, tax, asset, eventorganization, debugbar, projet, categorie, stocktransfer, stock, product, service, expedition, commande, fournisseur, societe, facture, banque
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT DISTINCT p.rowid, p.ref, p.label, p.fk_product_type as type, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.tms as datem, p.tobatch, p.tosell as status, p.tobuy as status_buy FROM llx_product as p LEFT JOIN llx_categorie_product as cp ON p.rowid = cp.fk_product WHERE p.entity IN (1,2,4,3) AND (te.rowid IN (0) OR te.entity = 3) ORDER BY p.ref ASC
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'te.rowid' in 'where clause'

### Environment Version

19.0.0-beta

### Environment OS

Linux erp 6.2.16-14-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-14 (2023-09-19T08:17Z) x86_64

### Environment Web server

Nginx 1.25.3

### Environment PHP

8.1.26

### Environment Database

10.6.16-MariaDB-1:10.6.16+maria~deb11

### Environment URL(s)

/product/composition/

### Expected and actual behavior

List the products to attach to the kit

### Steps to reproduce the behavior

Search for a product in the kits tab

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 19
