### ISSUE TITLE
Uncheck SIREN box on PDF didn't update 

### ISSUE THREAD

**Issue by GroupeVingeanne** [Dolibarr/dolibarr#26918]
### Bug

When I want to uncheck SIREN box on PDF settings and save 
I have toast notification indicates that's everithing is save but it isn't 

### Environment Version

19.0.0-beta

### Environment OS

Linux erp 6.2.16-14-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-14 (2023-09-19T08:17Z) x86_64

### Environment Web server

Nginx 1.25.3

### Environment PHP

8.1.26

### Environment Database

10.6.16-MariaDB-1:10.6.16+maria~deb11

### Environment URL(s)

/admin/pdf.php?mainmenu=home

### Expected and actual behavior

When I want to uncheck SIREN box on PDF settings and save 
I have toast notification indicates that's everithing is save but it isn't 

### Steps to reproduce the behavior

Uncheck SIREN and save

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/blob/a99135a92bcab0c479a20ae45eed5e4e24102683/htdocs/master.inc.php#L222-L225
you can't desactivate this param for FR

**Comment by GroupeVingeanne** [comment]
Thanks for your answer and sorry it was accounting requests, 
I didn't check the source code
Have a nice day
