### ISSUE TITLE
19.0 branch: please create

### ISSUE THREAD

**Issue by HLFH** [Dolibarr/dolibarr#26933]
### Bug

Hi,

Can you please create the 19.0 branch.
If it is not created, it prevents me to submit PRs.

Thanks,
HLFH

**Comment by ksar-ksar** [comment]
Hello,

For now V19 = develop no ?

**Comment by HLFH** [comment]
yes @ksar-ksar but v19 at the database level is frozen according to @aspangaro.
https://github.com/Dolibarr/dolibarr/pull/26750#issuecomment-1818332530

Develop branch would need to be v20 tu submit my changes.

**Comment by atm-maxime** [comment]
You can submit your changes to develop branch, it just won't be merged until the 19 branch is created. During beta phase, only fix PRs are merged, PRs for new features are postponed and reviewed after stable branch is created and alpha phase starts again.

**Comment by frederic34** [comment]
@HLFH @atm-maxime @ksar-ksar Issue can be closed
