### ISSUE TITLE
Feature Request: Kullo# as encrypted email alternative

### ISSUE THREAD

**Issue by Sebastian1984** [Dolibarr/dolibarr#2693]
Hi, I have an API  where they have a really easy to implement email alternative for encrypted communication.
https://www.kullo.net/protocol/http-api.html
this is the API, if it would be easy to make it work, this would be a really unique feature against all other ERP or CRM in the market, because they all send unencryptet.
We would enable our customers to send encryptet invoices to their customers. And these customers just have to install a one click installer. Nothing complex, for the noob. Where end to end matters this would be a nice add-on. I am not even sure if they will survive, but I thing the project should adress, IT security issues of the industry. We would have a feature where everybody else still has no answer to the question: Can I send encrypted? And basic account is free with 1GB and you can send 100MB attachments.
Thanks Sebastian

**Comment by BebZ** [comment]
And Dolimail can't send encrypted ?@guerrierk

**Comment by Sebastian1984** [comment]
That is not the problem, but I found many people reluctant to make this step on exchanging public keys. Last projekt I needed to put up a complete Server including an enviroment where to exchange data. Ending that half of the people send me emails with very sensetive stuff because they are unable to use my server, because " I don't have time for this." So it is more about beeing easy to use at the customer side, then beeing possible. Because often they are just to lazy to do anything themself. Kullo is easy and has client based thing called ./shooter i am asking for the prog right now.
But should be easy to be implemented because we don't want to get mails with it... 

this are the controls:
$ ./shooter 
Options:
--help Print help message
--masterKey arg The masterKey file (PEM format)
--fromAddress arg The sender's Kullo address
--fromName arg The sender's name
--fromOrganization arg The sender's organization
--fromAvatar arg The sender's avatar file
--fromFooterFile arg The sender's footer text
--messageFile arg The message text
--to arg The recipient's Kullo address
Hope I get the client soon enough (I get binaries Monday) and I didn't saw any PGP or else, did you? @BebZ

**Comment by guerrierk** [comment]
Hi all,

Dolimail use the dolibarr sending email configuration. If the Dolibarr is
able to send encrypted mail then Dolimail will be able too.

I have one question about your request : you want that the sent email from
dolibarr is globally encrypted or the file attached (order, invoice, or
other) ?

Thanks a lot ;-)

Kevin GUERRIER

**Comment by Sebastian1984** [comment]
globally encrypted... every other scenario has a flaw... the guy infront 
of the computer.  It is a big topic here in germany. IT security, PRISM. 
Would give us something that MS dynamics is not capable of...realy 
unique value proposition.

Kullo is not email.
it is kullo.
striebig#kullo.net is my adress there, if you want to try you can talk 
with me. They also make smartphone clients at the moment...

Am 23.04.2015 um 21:45 schrieb GUERRIER Kevin:

> Hi all,
> 
> Dolimail use the dolibarr sending email configuration. If the Dolibarr is
> able to send encrypted mail then Dolimail will be able too.
> 
> I have one question about your request : you want that the sent email from
> dolibarr is globally encrypted or the file attached (order, invoice, or
> other) ?
> 
> Thanks a lot ;-)
> 
> Kevin GUERRIER

**Comment by rdoursenaud** [comment]
I believe this would be a neat feature if implemented as an external module.
I don't think this qualifies for core integration though…

**Comment by webmaster128** [comment]
Hi everyone and a happy new year!

It is great to see this positive feedback on the idea of integrating Kullo Secure Comminication into Dolibarr. I am one of the Kullo co-founders and happy to provide all the resources to make things work. It took us some time but I have great news for the integrations. First of all, we just launched Kullo client software for iOS and Android, making it even more convenient for end users to receive messages via the secure channel. In the process we entirely redesigned our internal library, making it as easy as possible for you to integrate the _Kullo Shooter_, a command line tool to send Kullo messages.

The Kullo Shooter is a one-file tool running on all mayor Linux systems staring from Ubuntu 13.10+ and similar date.

To use the shooter, you need a Kullo account, that will later be the sender of messages. Create one via www.kullo.net. This will provide you a Kullo address and a "MasterKey". Those two are the basic information you need to send a message. Make your self a second account for testing, which will be the receiver. The Kullo desktop software lets you switch easily between those accounts.

Let's assume you register `foo#example.com` and your MasterKey is

```
-----BEGIN KULLO PRIVATE MASTER KEY-----
Version: 1 (256 bit)

113514 151068 205914 511279
253906 501312 406389 462028
615153 034892 331280 598185
468900 513796 270181 441808
-----END KULLO PRIVATE MASTER KEY-----
```

you store the MasterKey in a text file called `foo_example_com.kpem` ("Kullo PEM") and you're ready to send:

```
kullo-shooter --to=receiver#example.com --fromAddress=foo#example.com --fromMasterKey=./foo_example_com.kpem --fromName="Foo Bar" 
```

This is missing a message text, which you can provide via file or stdin, e.g.

```
echo "Confidential Hello World" | kullo-shooter --to=receiver#example.com --fromAddress=foo#example.com --fromMasterKey=./foo_example_com.kpem --fromName="Foo Bar" --messageFile=-
```

You get the full list of options using `kullo-shooter --help`. The binary can be downloaded on our website: https://www.kullo.net/download/files/shooter/
