### ISSUE TITLE
Bug: Warning: Invalid argument supplied for foreach() in commande.class.php on line 852

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2694]
Version: 3.7

An user from dolibarr.es forum at http://www.dolibarr.es/foro/viewtopic.php?f=18&t=2216&p=7779#p7779 is compalining about this problem. I was not able to reproduce it.

Steps:
1. Create a quote
2. Validate it
3. Close it (closed)

Warning: Invalid argument supplied for foreach() in C:\dolibarr\www\dolibarr\htdocs\commande\class\commande.class.php on line 852

**Comment by fappels** [comment]
$this->errors does not always contain errors. We should make it an empty array in commonobject.class.php
