### ISSUE TITLE
Adding complementary attribute fails if code is numerics

### ISSUE THREAD

**Issue by aaujon** [Dolibarr/dolibarr#2696]
Adding a complementary attribute for third parties (in module config page) fails without any messages if the field 'attribute code' only contains numerics.
Should be working or display an error message.
This bug is present in both 3.6.x and 3.7 release

**Comment by aaujon** [comment]
The limitation has been introduced by c69565fd69f826f3fc3c846a849f8e088828f4a1, but not properly checked when submiting the form to create the attribute

**Comment by rdoursenaud** [comment]
The code introducing the regression is for all extrafields so I believe all extrafields are affected.
