### ISSUE TITLE
Bug: contact Bug

### ISSUE THREAD

**Issue by BKF29** [Dolibarr/dolibarr#2697]
Hello
![selection](https://cloud.githubusercontent.com/assets/12070402/7278480/0ae8b378-e916-11e4-9dfe-961cfd3b6e22.jpg)
![adre](https://cloud.githubusercontent.com/assets/12070402/7278636/f7066bce-e916-11e4-880d-12dcf508a400.jpg)

For a main customer there are 15 contacts Delivery.
With Dolibarr  3.7.0 version it is not possible to select a contact for shipping. 
Dolibarr automatically selects the last record regardless of the selection made.

**Comment by rdoursenaud** [comment]
AFAIK the status you point has nothing to do with it being picked or not.
It's the contact's general status, so its unrelated.

Now on the main defect: I believe one should not be able to pick more than one delivery contact. This makes no sense.

**Comment by BKF29** [comment]
ok but we have an order with 15 different deliveries.
we must be able to select a different address for each shipment.
How can we do ?

**Comment by simnandez** [comment]
Put contact address Into each shippment?

**Comment by BKF29** [comment]
yes but it does not work. It is always the last adress which is on the shipping

**Comment by eldy** [comment]
When you create a shipment, application choose on contact from order. If there is several contacts, the last one is used. If you need to have shipments to different address, why not editing the shipment after creation to change the delivery address with the one you want on each shipment ?
