### ISSUE TITLE
Bug - The option to mark invoice lines as an asset in vendor invoices doesn't work

### ISSUE THREAD

**Issue by Daoud-mohamed** [Dolibarr/dolibarr#26985]
### Bug

The option to mark invoice lines as an asset in vendor invoices doesn't work

![4](https://github.com/Dolibarr/dolibarr/assets/16115679/c9fa71b1-f322-426a-8b49-20cbbafa70da)

### Steps to reproduce the behavior

To reproduce the bug, go to “Billing and payment - Vendor invoices – List,” choose an invoice, and navigate to the invoice lines. You can observe that there is no icon to add it as an asset.

**Comment by josett225** [comment]
For now it works when invoice is in draft and product has the right accounting number. 
Several options for future:
Improve the product line process
And/or create a new list in asset menu to handle all the product lines from supplier invoices to generate several actions.

**Comment by josett225** [comment]
For now it works when invoice is in draft and product has the right accounting number. 
Several options for future:
Improve the product line process
And/or create a new list in asset menu to handle all the product lines from supplier invoices to generate several actions.
