### ISSUE TITLE
Add support for categories on projects

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#2701]
Implementation must work by copy and past of implementation used for thirdparty or product.

**Comment by rdoursenaud** [comment]
PLEEAAAASSSE, no more copy/paste extravaganza. There's already more than enough already!
Make code generic enough to be shared.
How are you not tired of maintaining gazillion slightly out-of-sync versions of copy pasta?

**Comment by accett** [comment]
It would be very harder make a branch writing Dolibarr in an Framework like
CakePHP?

Im new with this tool, but develop new request and debugging code is faster
and cleanner in this kind of tools, also the security is better.

What do you think?

Its so crazy like its seems?

By the way... how can I get the diagrams ER of the database? Sometimes I
need modify or add a field (no the extrafields) of the database to make a
particular request of the user but I dont know yet how the database works.

Thanks in advantage.

**Comment by rdoursenaud** [comment]
@accett You can view/navigate the database model from a GUI tool like [MySQL Workbench](https://www.mysql.com/products/workbench/) or an advanced IDE (I use IntelliJ IDEA / PhpStorm).

**Comment by accett** [comment]
2015-04-23 16:44 GMT-05:00 Raphaël Doursenaud notifications@github.com:

> IntelliJ IDEA

Thanks @rdoursenaud I use NetBeans and now thanks to you MySQL WorkBench to
view the database.

## 

Gracias por no enviar cadenas.
Ing. Víctor Ortiz Pérez
AcceTT - Soluciones Computacionales
Mártires 28 de Agosto #134 esq. Ruiz Cortines
Col. Ferrer Guardia Xalapa, Veracruz CP 91020
Tel. (228) 840 3284
WA 228 840 3284
victor@accett.com.mx
www.accett.com.mx

**Comment by maikaspanring** [comment]
Is the title correct to this topic?
I am searching for a way to use the categories module in my/other modules, like stated in the issues title.

is there a plan to implement this feature? Example: Categories in ecm

If we change the llx_categorie.type database field from the nummeric field type
from:
0 -> product
1 -> supplier
2 -> customer
3 -> member
4 -> contact

to: varchar type with $conf->modules

we could enable other modules to use categories.

**Comment by rdoursenaud** [comment]
@nspanring What you are asking for is a completely different feature I'd call "categories extensibility".
AFAIK there's no plan for that but you're welcome to open a separate feature request.

**Comment by ghost** [comment]
I've done a PR on this subject. I done it mostly by copy/paste actual feature, but I will continue on dev branch, and if possible (@eldy ?) rename folder and right to be "englished" (projet/fk_projet vs project/fk_project)

**Comment by eldy** [comment]
I got PR and fix minor bugs. Thanks very much. A long awaited need to address a lot of feature.

**Comment by edupulpillo** [comment]
categories extensibility will simplify the code maintenance, also will be great to use categories in variant attributes and product complementary attributes
