### ISSUE TITLE
Create new unit for product or service will not show unit correctly .

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#27020]
### Bug

When create a new unit , for example pcs , in product card page  , you will see unitpcs not pcs .
But when you modify product page , you will see pcs .
![image](https://github.com/Dolibarr/dolibarr/assets/78349579/2c3ec5e2-d00b-4675-957a-17dc51792a9c)
![image](https://github.com/Dolibarr/dolibarr/assets/78349579/25b17a79-3c2c-4dfb-b9bf-f12b8e3a0afe)

### Environment Version

v16.0.5

### Environment OS

Deian 10

### Environment Web server

Apache/2.4.38 Apache/2.4.41

### Environment PHP

7.4.33

### Environment Database

5.5.5-10.5.15-MariaDB-0+deb11u1

### Environment URL(s)

/product/card.php?id=912

### Expected and actual behavior

Should not show unitpcs in producd or service card page , it should show pcs when the unit label is pcs .

**Comment by ksar-ksar** [comment]
Confirmed also on V18.0.3.

It's because, Dolibarr is trying to display the translation of the key 'unit'+Shortcode
For all the default units, it's defined, but of course not for the user one.

A workaround is to define a new translation key, on the Home->Setup->Translation
