### ISSUE TITLE
Thirdparty email missing in send message form for ticket

### ISSUE THREAD

**Issue by TedinfoRegis** [Dolibarr/dolibarr#27034]
### Bug

Code error in /core/class/html.formticket.class.php @ line 1535

Actual code : 
if (**is_array**($ticketstat->thirdparty->email) && !in_array($ticketstat->thirdparty->email, $sendto)) {
Correct code :
if (**!empty**($ticketstat->thirdparty->email) && !in_array($ticketstat->thirdparty->email, $sendto)) {

### Environment Version

>=18

### Expected and actual behavior

Should include thirdparty email address

### Steps to reproduce the behavior

From any ticket issued on thirdparty having an email address : add message and check "send by mail"
Should send to thirdparty mail by default

**Comment by JonBendtsen** [comment]
why not make a pull request yourself?

https://github.com/Dolibarr/dolibarr/edit/develop/htdocs/core/class/html.formticket.class.php

**Comment by TedinfoRegis** [comment]
Because I don't have enough confidence in myself to pull a request

**Comment by JonBendtsen** [comment]
> Because I don't have enough confidence in myself to pull a request

Don't worry, you won't ruin anything, as the pull request will be reviewed by the Dolibarr maintainers before any approval, so you won't break anything.
