### ISSUE TITLE
Bug: Le module Etats de Compte (etatscompteArea) me retourne une page blanche. 

### ISSUE THREAD

**Issue by m10ust** [Dolibarr/dolibarr#27056]
J'aimerais bien utiliser le module États de Compte, mais lorsque activé, il me retourne une page blanche avec le header "EtatscompteArea"

# Bug
[Module ne fonctionne pas]

## Environment
- **Version**: 16.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3-4ubuntu2.19
- **Database**: MySQL or MariaDB 5.5.5-10.3.38-MariaDB-0ubuntu0.20.04.1
- **URL(s)**: /custom/etatscompte/etatscompteindex.php?idmenu=5558&mainmenu=etatscompte&leftmenu=

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Bonjour,

On doit s'exprimer en anglais sur GitHub, pour le support en français, vous avez le forum : https://www.dolibarr.fr/forum/
Au vu de l'URL : " /custom/etatscompte/" c'est un module externe : Veuillez prendre contact avec son développeur.
