### ISSUE TITLE
Bug: TVA disparait une fois qu'on ajoute un produit dans devis/commande/facture

### ISSUE THREAD

**Issue by xpisson** [Dolibarr/dolibarr#27059]
# Bug
Bonjour, 
Je suis ennuyé, je viens de passer de V14 à V18.0.3 et lorsque j'ajoute des produits en devis, la tva disparait quand je clique sur ajouter.
TVA renseignée, entreprise soumise à TVA dans paramètres, client bien enregistré en pays.
Ci joint 2 capture. Je cherche produit menu déroulant, il a de la TVA et quand j'ajoute, elle disparait. 
Merci par avance 
XP

![pb appui sur ajouter et plus de tva](https://github.com/Dolibarr/dolibarr/assets/153546019/91ca2b5f-c751-46e5-a889-b0067c704730)
![pb ajouter produit, il y a de la tva](https://github.com/Dolibarr/dolibarr/assets/153546019/2b371f74-8e59-4315-afc0-cfb44f9b4456)
## Environment
- **Version**: 18.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.4.33
- **Database**: MySQL or MariaDB 5.5.5-10.6.16-MariaDB
- **URL(s)**: /index.php?mainmenu=home&leftmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment]
Bonjour,

On doit s'exprimer en anglais sur GitHub, pour le support en français vous avez le forum : https://www.dolibarr.fr/forum/
En tout cas je ne reproduis pas ce bug, c'est forcément quelque chose sur votre installation, surement un module externe.

---------------------------------------------------------------

Hello,

You have to speak English on GitHub, for support in French you have the forum: https://www.dolibarr.fr/forum/
In any case I don't reproduce this bug, it must be something on your installation, probably an external module.
