### ISSUE TITLE
New signed status for interventions

### ISSUE THREAD

**Issue by W1W1-M** [Dolibarr/dolibarr#27064]
### Feature Request

Currently _Interventions_ can have **Draft**, **Validated** or **Done** status. They can be signed by the client (paper or online). In the same way quotes have a **signed** (or **unsigned**) status, interventions could too.

### Use case

For example: an intervention with a **signed** status gives extra information to the person in charge of billing or organizing team. This is an extra guarantee that the intervention is complete and can be properly finalized and billed. 

### Suggested implementation

Add an extra status with associated logic.

### Suggested steps

- [x] Add data structure
- [x] Add new signed status
- [x] Add _Set signed_ button (like Accepted button for quotes) & associated logic
- [x] Add notification for signed status
- [x] Add logic for status update with online signing
- [x] Update intervention module Wiki page: https://wiki.dolibarr.org/index.php?title=Module_Interventions

**Comment by lmag** [comment]
- [ ] Add signed status company
- [ ] Add signed status thirdparty
- [ ] Add pdf filename sign company
- [ ] Add pdf filename thirdparty

**Comment by FHenry** [comment]
suggest 3 value possible for signed field
1 => sign by senders(company)
2 => sign by receiver (thridparty)
3 => Sign by both

**Comment by eldy** [comment]
> suggest 3 value possible for signed field 1 => sign by senders(company) 2 => sign by receiver (thridparty) 3 => Sign by both

Agree. Signed status must be a separated field. Ok for the 3 values.

**Comment by W1W1-M** [comment]
Feel free to work on this. I haven't done anymore since #27856

**Comment by W1W1-M** [comment]
Thanks to @eldy @evarisk-micka @FHenry @lmag @mdeweerd for all your input, work and help on this 😄
