### ISSUE TITLE
Install directory missing step3.php

### ISSUE THREAD

**Issue by coxe87b** [Dolibarr/dolibarr#27070]
### Bug

Following the install.php process, it leads into http://localhost/install/step2.php and then there is no button to proceed. Manually changing URL to end in step3.php displayed error 404, but on listing the directory, there is a step4.php and step5.php. It seems like the steps need to be re-aligned and if step3 is missing then re-add it, otherwise rename step4 to step3 and likewise for step5.

### Environment Version

19.0.0-beta

### Environment OS

Arch Linux 6.6.1-zen1-1-zen

### Environment Web server

Apache 2.4.58

### Environment PHP

php v8.1.26

### Environment Database

mariadb 11.2.2-MariaDB

### Environment URL(s)

http://localhost/install/step2.php

### Expected and actual behavior

Expected to have a "Next" button but there is none. There is also no step3.php file to progress to.

### Steps to reproduce the behavior

Follow the install process

**Comment by laurentlt** [comment]
In step2.php file, comment this line to continue the installation : $hash_unique_id = dol_hash('dolibarr'.$conf->file->instance_unique_id, 'sha256');
