### ISSUE TITLE
Postal mail / mass campaign

### ISSUE THREAD

**Issue by Sebastian1984** [Dolibarr/dolibarr#2710]
Hi,
I would like to do some mail campaign, was already 2 requests in the forum.
http://www.dolibarr.org/forum/12-howto-help/24268-marketing-campaign
http://www.dolibarr.org/forum/12-howto-help/20209-marketing-campaigns
to send letters to members or leads or customers.
Best with odt modul to create this letter, but anything would be nice.
Or a predefined export function or something for massmailing physical letters in an easy way.
Think about the clubs they often have members who still don't have an email or need to send them physical stuff like calendars and so on. It hits a need of our customer base big time.
Thank you.

**Comment by rdoursenaud** [comment]
There was a DocumentGeneration module in development.
Not much work seems to have been done though… I can't seem to find any feature beyond the module descriptor.

**Comment by eldy** [comment]
Yes, the module DocumentGeneration was started, but nothing was done yet. We are still looking for people to develop it :-(
