### ISSUE TITLE
Partnertime / localtime

### ISSUE THREAD

**Issue by Sebastian1984** [Dolibarr/dolibarr#2711]
Hi, I wish to have a clock next to the partnercard 
Story:
A customer mixed up timezones and called somebody at 3 am. Somebody was angry.
 And then I remembered, that it happened to me also because of timezones missing calls, interviews. 
And then stories from other people getting calls in the middle of the night, with some minor question. 
Other scenario you get a call and you are already on a party, its midnight.  Your heart goes to the bottom because your biggest customer is calling in the middle of the night: " Hi, Bob i just want to say that your product is working fine and that I send you an email that is not so urgent. are you at a party in the midle of the day?" Bob probably lost some hours of his lifetime while answering that call.
No problem at 9 - 18 but at 22 you don't like it, between 22 and 5 you assume it is worstcase scenario.

Solution:
I open the partnercard and there is a clock next to his country, from 8 - 19 it is black during business time it is green and from 19 - 8 it is red. 
I like to see it like this Country: israel  local-time: 15:30 Business/ contact hours: 10 - 16 
a simple trafficlight.
Thanks a lot.

**Comment by eldy** [comment]
This requests contains 2 different changes:
- first one is easy, we must just show "current local time" of partner near its country information.
- second part need a new module "Opened business time". This would add a new tab to define start and opened hours for business time. A good topic for a new module development.

**Comment by Sebastian1984** [comment]
Sorry that I mixed it up. Had forgotten that "current local time" is 
ready to use. Then if it is that easy lets try it and ask how people 
think about it, maybe the other feature is waste, even if i would really 
like it.
Am 25.04.2015 um 15:20 schrieb Laurent Destailleur:
