### ISSUE TITLE
Members export fails

### ISSUE THREAD

**Issue by matlopes** [Dolibarr/dolibarr#2712]
Adherent export gets an error at step 3:
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20150425142146
Dolibarr: 3.7.0
Niveau de fonctionnalités: 0
PHP: 5.5.9-1ubuntu4.9
Serveur: Apache/2.4.7 (Ubuntu)
OS: Linux dell 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

Url sollicitée: /extranet/www/exports/export.php?step=3&datatoexport=adherent_1
Referer: http://localhost/extranet/www/exports/export.php?step=2&datatoexport=adherent_1&action=selectfield&field=all
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT rowid as rowid, libelle as label FROM llx_fk_adherent_type
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHTABLE
Information sur le dernier accès en base en erreur: Table 'extranet.llx_fk_adherent_type' doesn't exist

Final error is:
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20150425141732
Dolibarr: 3.7.0
Niveau de fonctionnalités: 0
PHP: 5.5.9-1ubuntu4.9
Server: Apache/2.4.7 (Ubuntu)
OS: Linux dell 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

Url sollicitée: /extranet/www/exports/export.php?step=5&datatoexport=adherent_1
Referer: http://localhost/extranet/www/exports/export.php?step=5&datatoexport=adherent_1
Gestionnaire de menu: eldy_menu.php

Message: Bad value for field with code=a.civilite. Try to redefine export.

**Comment by eldy** [comment]
Did you used an old predefined export with a previous versious version ?
You probably have to redefine it.

**Comment by matlopes** [comment]
Maybe i did. I don't know.

This time, i just checked "all fields", at step 2, not using any predefined export.

Here's what i get at step 3, at the "Type d'adhérent Id type adhérent" [fr] line:

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20150426170739
Dolibarr: 3.7.0
Niveau de fonctionnalités: 0
PHP: 5.5.9-1ubuntu4.9
Serveur: Apache/2.4.7 (Ubuntu)
OS: Linux dell 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

Url sollicitée: /extranet/www/exports/export.php?step=3&datatoexport=adherent_1
Referer: http://localhost/extranet/www/exports/export.php?step=2&datatoexport=adherent_1&action=selectfield&field=all
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT rowid as rowid, libelle as label FROM llx_fk_adherent_type
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHTABLE
Information sur le dernier accès en base en erreur: Table 'extranet.llx_fk_adherent_type' doesn't exist

If I ignore this message and continue further, export file generation (Excel 95, but same goes with other filetypes) fails without any error message (blank page).

**Comment by rdoursenaud** [comment]
`fk_adherent_type` is a field from `llx_adherent` not a table. Strange error…

**Comment by matlopes** [comment]
The fix works perfectly. Thanks
