### ISSUE TITLE
Bug: 3.7.0 mailing-unsubscribe.php not unsubscribe

### ISSUE THREAD

**Issue by javieralapps4up** [Dolibarr/dolibarr#2713]
Wrong line 89: $sql = "UPDATE ".MAIN_DB_PREFIX."socpeople SET no_email=1 WHERE rowid IN (SELECT sc.rowid FROM ".MAIN_DB_PREFIX."socpeople AS sc INNER JOIN ".MAIN_DB_PREFIX."mailing_cibles AS mc ON mc.tag = '".$db->escape($tag)."' AND mc.source_type = 'contact' AND mc.source_id = sc.rowid)";

Reason:  In mySQL, you have to create another layer of abstraction when trying to update a table with values from the same table.

Correct (I think):

$sql = "UPDATE ".MAIN_DB_PREFIX."socpeople SET no_email=1 WHERE rowid IN (SELECT scrowid FROM (SELECT sc.rowid as scrowid FROM ".MAIN_DB_PREFIX."socpeople AS sc INNER JOIN ".MAIN_DB_PREFIX."mailing_cibles AS mc ON mc.tag = '".$db->escape($tag)."' AND mc.source_type = 'contact' AND mc.source_id = sc.rowid) as subtable)";

Best regards.

**Comment by eldy** [comment]
Can you try this instead
$sql = "UPDATE ".MAIN_DB_PREFIX."socpeople SET no_email=1 WHERE rowid IN (SELECT source_id FROM ".MAIN_DB_PREFIX."mailing_cibles WHERE tag = '".$db->escape($tag)."' AND source_type='contact' AND source_id is not null)";

**Comment by javieralapps4up** [comment]
Perfect! (and better)
