### ISSUE TITLE
BUG:Members -> Memberxy-> Agenda -> technical Error

### ISSUE THREAD

**Issue by Sebastian1984** [Dolibarr/dolibarr#2714]
Hi, so we tried a new dolibarr (thanks france! ) And I have got a new member account and got a new password. So I went to Members -> my own card -> and saw this in Agenda. 

Aktionen zu diesem Mitglied (Actions for this Member)

( ! ) Xdebug: user triggered in /home/dolibarr.de/dolibarr/htdocs/core/lib/functions.lib.php on line 2490
Call Stack
# Time    Memory  Function    Location

1   0.0005  144924  {main}( )   ../agenda.php:0
2   0.1374  5503056 show_actions_todo( )    ../agenda.php:170
3   0.1406  5734528 dol_print_error( )  ../company.lib.php:1053
4   0.1445  5771060 xdebug_print_function_stack ( ) ../functions.lib.php:2490
Das System hat einen technischen Fehler festgestellt.
Diese Informationen könnten bei der Diagnose des Fehlers behilflich sein:
Datum: 20150426103609
Dolibarr: 3.7.0
Funktionslevel: 0
PHP: 5.4.39-0+deb7u2
Server: Apache/2.2.22 (Debian)
OS: Linux hivaoa 2.6.32-6-pve #1 SMP Tue Sep 13 10:44:10 CEST 2011 i686
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36 OPR/28.0.1750.51

Angeforderte URL: /adherents/agenda.php?id=2
Referer: http://management.dolibarr.de/adherents/card_subscriptions.php?rowid=2
Menüverwaltung: eldy_menu.php

Datenbanktyp-Verwaltung: mysqli
Anfrage des letzten fehlerhaften Datenbankzugriffs: SELECT a.id, a.label, a.datep as dp, a.datep2 as dp2, a.percent, a.fk_user_author, a.fk_contact, a.fk_element, a.elementtype, c.code as acode, c.libelle, u.login, u.rowid, m.lastname, m.firstname FROM llx_user as u, llx_actioncomm as a, llx_adherent as m LEFT JOIN llx_c_actioncomm as c ON a.fk_action = c.id WHERE u.rowid = a.fk_user_author AND a.entity IN (1) AND a.fk_element = m.rowid AND a.elementtype = 'member' AND a.fk_element = 2 AND ((a.percent >= 0 AND a.percent < 100) OR (a.percent = -1 AND a.datep > '20150426123609')) ORDER BY a.datep DESC, a.id DESC
Return-Code des letzten fehlerhaften Datenbankzugriffs: DB_ERROR_NOSUCHFIELD
Inhalt des letzten Datenbankzugriffs mit Fehler: Unknown column 'a.fk_action' in 'on clause'

XDebug informations:
File: /home/dolibarr.de/dolibarr/htdocs/core/lib/company.lib.php
Line: 1053
Function: show_actions_todo

( ! ) Xdebug: user triggered in /home/dolibarr.de/dolibarr/htdocs/core/lib/functions.lib.php on line 2490
Call Stack
# Time    Memory  Function    Location

1   0.0005  144924  {main}( )   ../agenda.php:0
2   0.1448  5761588 show_actions_done( )    ../agenda.php:173
3   0.1452  5763372 dol_print_error( )  ../company.lib.php:1148
4   0.1456  5765816 xdebug_print_function_stack ( ) ../functions.lib.php:2490
Das System hat einen technischen Fehler festgestellt.
Diese Informationen könnten bei der Diagnose des Fehlers behilflich sein:
Datum: 20150426103609
Dolibarr: 3.7.0
Funktionslevel: 0
PHP: 5.4.39-0+deb7u2
Server: Apache/2.2.22 (Debian)
OS: Linux hivaoa 2.6.32-6-pve #1 SMP Tue Sep 13 10:44:10 CEST 2011 i686
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36 OPR/28.0.1750.51

Angeforderte URL: /adherents/agenda.php?id=2
Referer: http://management.dolibarr.de/adherents/card_subscriptions.php?rowid=2
Menüverwaltung: eldy_menu.php

Datenbanktyp-Verwaltung: mysqli
Anfrage des letzten fehlerhaften Datenbankzugriffs: SELECT a.id, a.label, a.datep as dp, a.datep2 as dp2, a.note, a.percent, a.fk_element, a.elementtype, a.fk_user_author, a.fk_contact, c.code as acode, c.libelle, u.login, u.rowid as user_id, m.lastname, m.firstname FROM llx_user as u, llx_actioncomm as a, llx_adherent as m LEFT JOIN llx_c_actioncomm as c ON a.fk_action = c.id WHERE u.rowid = a.fk_user_author AND a.entity IN (1) AND a.fk_element = m.rowid AND a.elementtype = 'member' AND a.fk_element = 2 AND (a.percent = 100 OR (a.percent = -1 AND a.datep <= '20150426123609')) ORDER BY a.datep DESC, a.id DESC
Return-Code des letzten fehlerhaften Datenbankzugriffs: DB_ERROR_NOSUCHFIELD
Inhalt des letzten Datenbankzugriffs mit Fehler: Unknown column 'a.fk_action' in 'on clause'

XDebug informations:
File: /home/dolibarr.de/dolibarr/htdocs/core/lib/company.lib.php
Line: 1148
Function: show_actions_done

Couldn't find anything about this bug here. pls fix thx

**Comment by eldy** [comment]
A fix has been done. Ask an upgrade of your instance with patch #2714
