### ISSUE TITLE
Add a new listen trigger event 'ORDER_MODIFY' 

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#27177]
### Feature Request

Add the ability to launch an event when an order gets modified 

### Use case

When changing a field on the order we would like to catch the event 

### Suggested implementation

On **`commande.class.php `** add a new trigger when an order gets modified 'ORDER_MODIFY' 

### Suggested steps

Add it to https://wiki.dolibarr.org/index.php?title=Triggers

**Comment by nat-itopie** [comment]
Hi, the trigger ORDER_MODIFY already exists in Commande class (I check in 18.04 and 16.04).

**Comment by daxitsolutions** [comment]
ORDER_MODIFY exists
Documentation Updated.
