### ISSUE TITLE
Opensurvey with enddate today or in the past leads to technical error 

### ISSUE THREAD

**Issue by Sebastian1984** [Dolibarr/dolibarr#2717]
Result:
( ! ) Xdebug: user triggered in /home/dolibarr.de/dolibarr/htdocs/core/lib/functions.lib.php on line 2490
Call Stack
# Time    Memory  Function    Location

1   0.0006  185388  {main}( )   ../card.php:0
2   0.0880  4566596 dol_print_error( )  ../card.php:49
3   0.0920  4603376 xdebug_print_function_stack ( ) ../functions.lib.php:2490
Das System hat einen technischen Fehler festgestellt.
Diese Informationen könnten bei der Diagnose des Fehlers behilflich sein:
Datum: 20150427150008
Dolibarr: 3.7.0
Funktionslevel: 0
PHP: 5.4.39-0+deb7u2
Server: Apache/2.2.22 (Debian)
OS: Linux hivaoa 2.6.32-6-pve #1 SMP Tue Sep 13 10:44:10 CEST 2011 i686
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36 OPR/28.0.1750.51

Angeforderte URL: /opensurvey/card.php?id=rhikguo3jkhbhvsd
Referer: http://management.dolibarr.de/opensurvey/wizard/choix_autre.php
Menüverwaltung: eldy_menu.php

Datenbanktyp-Verwaltung: mysqli
Anfrage des letzten fehlerhaften Datenbankzugriffs: Keine Anfrage im Fehler
Return-Code des letzten fehlerhaften Datenbankzugriffs: Keine Anfrage im Fehler
Inhalt des letzten Datenbankzugriffs mit Fehler: Keine Anfrage im Fehler

Message: Fetch no poll found for sondageid=rhikguo3jkhbhvsd
XDebug informations:
File: /home/dolibarr.de/dolibarr/htdocs/opensurvey/card.php
Line: 49
Function: {main}

Should be: Error, you can't end the survey today or in the past.

**Comment by marcosgdf** [comment]
Happening also in 3.6.3

For some reason this bug was introduced in commit 41ab5a0ce2e4473f1a68641e7d36837a4469cd0e. @eldy: Can you give us a clue why was the test removed?

**Comment by eldy** [comment]
@marcosgdf  May be because field is not mandatory. Does this bug occur also with 3.8 ?

**Comment by rdoursenaud** [comment]
@eldy Couldn't reproduce on 3.8.

**Comment by eldy** [comment]
Seems fixed into 3.8 so i close bug
