### ISSUE TITLE
The time in the log tab does not display AM or PM.

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2719]
Version: 3.6.2

When using Dolibarr in English the time in the logged dates is missing the AM or PM discriminent.
I.e:
- 18h59 is displayed 06:59
- 6h59 is displayed the very same 06:59

**Comment by eldy** [comment]
You say the time in the logged dates. Which logged date ? Which page ?

**Comment by rdoursenaud** [comment]
The log tab of each pages aka "suivi" in french.
Issue appears fixed in 3.8 anyway.
