### ISSUE TITLE
Avoid ugly messages / eventMessage not displayed

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#27203]
### Bug

If a plugin or another core bug send to setEventMessage something which's not a string, you'll see an ugly message in the footer like

`Fatal error: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, __PHP_Incomplete_Class given in /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php:8309 Stack trace: #0 /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php(8309): preg_match(‹ /class=« error »/… ›, Object(__PHP_Incomplete_Class)) #1 /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php(8184): dol_htmloutput_mesg(‹  ›, Array, ‹ error ›) #2 /home/asheuroptw/erpdev/htdocs/main.inc.php(3182): dol_htmloutput_events(0) #3 /home/asheuroptw/erpdev/htdocs/compta/facture/card.php(5762): llxFooter() #4 {main} thrown in /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php on line 8309`

And the other Eventmessages, even if ther'e Ok, are not displayed

That's because the type of string message isn't controlled

### Environment Version

All

### Environment OS

All

**Comment by hregis** [comment]
@vmaury what is the version of your Dolibarr ?? and what is the version of your php ??

**Comment by vmaury** [comment]
Dolibarr versions : 16, 17, 18, 19, developp
Php : 7.3, 8.0, 8.1
It doesnt depend on this 

Here's the message I sent to Eric Seigne :
Bonsoir Eric,

Je viens de trouver un dysfonctionnement vraiment capillotracté dans factur-x.
J’utilise conjointement factur-x avec 2 plugins qui utilisent aussi le hook afterPdfCreation (un qui rajoute les conditions générales de vente au pdf de la facture, et un à moi qui rajoute une page spéciale à mon client).
Et je me retrouvais avec un message dégueu en bas de ma page de facture (*)
J’ai mis un sacré moment à trouver : il vient de la ligne #421 de actions_facturx.class.php
setEventMessages($pdfCheck->validateDocument(), null, ‹ errors ›);
$pdfCheck->validateDocument() renvoie un objet au lieu d’une string, et l’affichage des erreurs dolibarr il aime pas du tout.
C’est d’autant plus ballot que le validateur dit que la facture est pas conforme, ce qui est peut-être vrai, mais en tout cas le xml extrait semble ok, et mon client balance ses factures factur-x avec mes rajouts sur ChorusPro qui les avale sans sourciller.
Je vais quand même soumettre un PR qui cleane les messages dans setEventMessage pour ne plus jamais avoir ce genre d’affichage…

Voilà, une bonne soirée et de bonnes fêtes !

Vincent

(*)
Fatal error: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, __PHP_Incomplete_Class given in /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php:8309 Stack trace: #0 /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php(8309): preg_match(‹ /class=« error »/… ›, Object(__PHP_Incomplete_Class)) #1 /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php(8184): dol_htmloutput_mesg(‹  ›, Array, ‹ error ›) #2 /home/asheuroptw/erpdev/htdocs/main.inc.php(3182): dol_htmloutput_events(0) #3 /home/asheuroptw/erpdev/htdocs/compta/facture/card.php(5762): llxFooter() #4 {main} thrown in /home/asheuroptw/erpdev/htdocs/core/lib/functions.lib.php on line 8309
