### ISSUE TITLE
Unable to remove a "social/fiscal Charge"

### ISSUE THREAD

**Issue by bv74** [Dolibarr/dolibarr#27207]
### Bug

When I would like to remove a "Charges fiscal/sociale", I got two opposite messages underline on screen shot. 
The general ledger is empty. 
![image](https://github.com/Dolibarr/dolibarr/assets/43907350/0745a36f-a317-4792-a19d-424268f0a380)
Removing charge is not possible. 

### Environment Version

16.0.3

### Environment OS

4.19.194-3

### Environment Web server

apache

### Environment PHP

7.4.13

### Environment Database

MarieDB : 5.5.5-10.3.34

### Environment URL(s)

gpa/htdocs/compta/sociales/card.php?id=147&save_lastsearch_values=1

### Expected and actual behavior

removing charge is possible. 

### Steps to reproduce the behavior

Create a fiscal/social charge
try to remove it

**Comment by atm-maxime** [comment]
Hi !
I just tested with latest 16.0.5 and I can't reproduce the issue. The payment is correctly removed. Can you try and confirm ?

**Comment by bv74** [comment]
Hi ! 
shame on me, it's working, and I can't reproduce too. I'll put my procedure [https://www.dolibarr.fr/forum/t/suppression-paiement-charge-sociale-impossible/44471/7](https://www.dolibarr.fr/forum/t/suppression-paiement-charge-sociale-impossible/44471/7) .

Thank you nevertheless for your help.

**Comment by bv74** [comment]
Can't reproduce
