### ISSUE TITLE
E-Mailcollector: Filter "is an answer" not working  in languages other than English

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#27223]
### Bug

see htdocs/emailcollector/class/emailcollector.class.php, line #1675 (V18):

```
$isanswer = 0;
if (preg_match('/Re\s*:\s+/i', $headers['Subject'])) {
	$isanswer = 1;
}
```

This solution to check if there is a "Re" in the subject of the mail is not working if the language of the mail-client is different than English. Eg in German there is "AW" instead of "Re"

### Environment Version

V18

### Environment OS

n/a

### Environment Web server

n/a

### Environment PHP

n/a

### Environment Database

n/a

### Expected and actual behavior

There should be a solution that does not refer to the text in the subject of the mail. Two lines are also commented out in the code, but it is not clear why:

```
//if ($headers['In-Reply-To'] != $headers['Message-ID'] && empty($headers['References'])) $isanswer = 1;	// If in-reply-to differs of message-id, this is a reply
//if ($headers['In-Reply-To'] != $headers['Message-ID'] && !empty($headers['References']) && strpos($headers['References'], $headers['Message-ID']) !== false) $isanswer = 1;
```

@eldy Do you know why these two lines are commented out? For me it seems that this would be a much better solution

**Comment by eldy** [comment]
What if you replace with

if (preg_match('/^(Re|AW)\s*:\s+/i', $headers['Subject'])) { 	$isanswer = 1; }

Is it ok for german language ?

The 2 lines were commented because test shows it was not reliable. Rfc 2822 says that "In-Reply-To" header is optionnal. And when doing tests, i found too much case without this header.
But may be best is combination of the 2 methods.
If we have the regex OR if we find the in-reply-to in header...

**Comment by ksar-ksar** [comment]
Hello,

"Re" could be written "Re" or "RE".

But you have a lot of different subjects : https://en.wikipedia.org/wiki/List_of_email_subject_abbreviations
`if (preg_match('/^(回复|回覆|SV|Antw|VS|RE|Re|AW|ΑΠ|השב| תשובה | הועבר|Vá|R|RIF|BLS|Atb|RES|Odp|பதில்|YNT|ATB)\s*:\s+/i', $headers['Subject'])) { $isanswer = 1; }`
It looks like a "gaz power plant" ;-)
