### ISSUE TITLE
External user can have access to supplier's products, but not to products

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2724]
It's a strange behaviour, an external user can access Produit fournisseurs 
![image](https://cloud.githubusercontent.com/assets/3694135/7370694/375dbaf2-edbc-11e4-8cd6-6df51f5a7313.png)

but not product/list.php
![image](https://cloud.githubusercontent.com/assets/3694135/7370704/4881b3b0-edbc-11e4-8a84-dbdfdca79243.png)

**Comment by rdoursenaud** [comment]
Cosmetic bug: the search fields should be hidden if the user does not have the permissions to use them.
Permissions are obviously correctly enforced on the pages.

**Comment by marcosgdf** [comment]
Under which conditions this is reproduced? Can you please describe the steps?

**Comment by eldy** [comment]
Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by simnandez** [comment]
No response, I can reproduce It, so I close it.
