### ISSUE TITLE
Installation v18.0.4

### ISSUE THREAD

**Issue by fansch** [Dolibarr/dolibarr#27246]
### Bug

Hi,
I am trying to install Dolibarr v18.0.4, downloaded from github:
wget https://github.com/Dolibarr/dolibarr/archive/refs/tags/18.0.4.tar.gz

The page https://doli.strasorgues.fr/install/index.php shows up as expected, right page, right version, but the next page, https://doli.strasorgues.fr/install/check.php
sends :
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
A  phpinfo() dropped in the file htdocs/info.php shows up as expected. The page htdocs/install/phpinfo.php shows up as expected.

No idea to look further.
Thanks for your suggestion.

### Environment Version

18.0.4

### Environment OS

Ubuntu 22.04.3 LTS

### Environment Web server

Apache 2.4.52-1

### Environment PHP

PHP 8.1.2-1ubuntu2.14

### Environment Database

mariadb  Ver 15.1 Distrib 10.6.12-MariaDB

### Environment URL(s)

https://doli.strasorgues.fr/install/check.php

### Expected and actual behavior

Expected : doing the check
Actual : sends the page
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

### Steps to reproduce the behavior

Reload the page https://doli.strasorgues.fr/install/check.php

### Attached files

On loading the page

Apache access.log:
doli.domain.fr:443 xxx.xxx.xxx.xxx - - [29/Dec/2023:03:06:01 +0100] "POST /install/check.php HTTP/1.1" 503 4868 "https://doli.domain.fr/install/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"

Apache error.log:
[Fri Dec 29 03:06:02.042138 2023] [proxy_fcgi:error] [pid 24276:tid 139703961425472] [client xxx.xxx.xxx.xxx:53956] AH01067: Failed to read FastCGI header, referer: https://doli.domain.fr/install/index.php
[Fri Dec 29 03:06:02.042190 2023] [proxy_fcgi:error] [pid 24276:tid 139703961425472] (104)Connection reset by peer: [client xxx.xxx.xxx.xxx:53956] AH01075: Error dispatching request to : , referer: https://doli.domain.fr/install/index.php

php8.1-fpm.log:
[29-Dec-2023 03:06:02] WARNING: [pool www] child 24379 exited on signal 11 (SIGSEGV - core dumped) after 1914.151305 seconds from start
[29-Dec-2023 03:06:02] NOTICE: [pool www] child 24873 started

syslog
Dec 29 03:11:09 obelix kernel: [ 5643.755038] php-fpm8.1[24873]: segfault at 0 ip 00005614c8a631c1 sp 00007fffa769a8f0 error 4 in php-fpm8.1[5614c8a1c000+2f6000]
Dec 29 03:11:09 obelix kernel: [ 5643.755050] Code: …

**Comment by hansemschnokeloch** [comment]
Hi,
can you try to change your php configuration and add (or update) the following line in php.ini
```
opcache.jit=function 
```
if it doesn't solve the issue try with
```
opcache.jit=off
```

**Comment by fansch** [comment]
Hi, thanks from not far from schokenloch :-).
I had to add the line. No change.
In the check.php file, with echo and die(), the first line producing the error is the next one :
dolibarr_install_syslog("- check: Dolibarr install/upgrade process started");

Thanks.
