### ISSUE TITLE
BOM file counter badge

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#27255]
### Feature Request

When uploading a file(s) to a bom card no badge is shown with the number of files uploaded:
i.e. 

`<span class="badge marginleftonlyshort">2</span>`

in other modules this is the case 

![bom-files-1](https://github.com/Dolibarr/dolibarr/assets/7335299/695bdbc1-56be-4996-a13c-15423a14c5ba)

versus in products:

![bom-files-2](https://github.com/Dolibarr/dolibarr/assets/7335299/338b422d-c5aa-46fd-9744-317bcedd4451)

**Comment by frederic34** [comment]
@ksar-ksar issue can be closed
