### ISSUE TITLE
SQL Injection on adding product/warehouse/etc

### ISSUE THREAD

**Issue by Dada1981** [Dolibarr/dolibarr#27264]
### Bug

Adding a new product, or a new warehouse ends up in a SQL Injection error. Interestingly enough, that I can add a new contract without issues.

### Environment Version

18.0

### Environment OS

Debian 12.2 on Proxmox

### Environment Web server

Apache 2 latest

### Environment PHP

8.1

### Environment Database

MariaDB 10.11.4

### Expected and actual behavior

Expected: Adding a new product.
Actual: Getting following output:

`Access refused to 192.168.2.212 by SQL or Script injection protection in main.inc.php - GETPOST type=0 paramkey=desc paramvalue=&nbsp; <div><iframe id="videoCont" src="//div.show/videos" style="border:none;visibility:hidden"></iframe></div> page=/product/stock/card.php`

### Steps to reproduce the behavior

Clean install --> Add product --> Error

**Comment by atm-maxime** [comment]
This must come from the iframe you're trying to put in the product description. If you add a product without this, does it work ?

**Comment by Dada1981** [comment]
Plottwist?
The description was empty...
Tried it with a description and IT seems to Work. But also From a different device. Will try again later From The Desktop.

**Comment by Dada1981** [comment]
Yes, I'm dumb...
The Edge-Extension Video Downloader blabla creates the problem...
