### ISSUE TITLE
Object of class User could not be converted to string in .../htdocs/fourn/class/fournisseur.facture-rec.class.php

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#27262]
### Bug

While generating recurrent invoice in Dolibarr 18.0.4 

 AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Object of class User could not be converted to string in .../htdocs/fourn/class/fournisseur.facture-rec.class.php:1330
Stack trace:
#0 .../htdocs/cron/class/cronjob.class.php(1290): FactureFournisseurRec->createRecurringInvoices()
#1 .../htdocs/cron/card.php(105): Cronjob->run_jobs('...')
#2 {main}
  thrown in .../htdocs/fourn/class/fournisseur.facture-rec.class.php on line 1330', referer: https://.../cron/card.php?action=execute&token=...&id=3&securitykey=...

### Environment Version

18.0.4

### Environment OS

(Synology) Linux 3.2.101 #42962 SMP PREEMPT Fri Mar 24 00:27:46 CST 2023 i686

### Environment Web server

Apache/2.4.54

### Environment PHP

php 7.4.30

### Environment Database

MariaDB 5.5.5-10.3.32-MariaDB

### Environment URL(s)

cron/card.php?action=execute

### Expected and actual behavior

Generate recurrent invoice without error

### Steps to reproduce the behavior

Started recurrent invoice generation fomr 

### Attached files

cron/list.php?leftmenu=admintools&idmenu=15701

Not sure how to reproduce it - the issue seems to be with User to string conversion.

**Comment by apio-sys** [comment]
Had the same issue. I can confirm the patch works fine. Thanks!
