### ISSUE TITLE
Project can't link supplier orders ?

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2727]
I can link to a supplier's invoices but not a supplier's order on the projects module..

when you leave the third "blank" and you activate the
 PROJECT_CAN_ALWAYS_LINK_TO_ALL_SUPPLIERS
then it displays some supplier's orders, 
but for my part, not after october 2012 (CF1210148) 
Also, not all supplier's orders are available (because of status?)
AND finally, you can't select it to add it to the project.

![image](https://cloud.githubusercontent.com/assets/3694135/7399234/a500af08-eeb4-11e4-9e01-e606645d6a6b.png)

I want to keep track of problems of deliveries 
(when suppliers deliver wrong products / damaged ones...) 
for each supplier with the project module, and maybe the thirds that will be implied (customers, mainly). 

Is it a good way ?

**Comment by rdoursenaud** [comment]
Linking a supplier order to a project is done from the supplier order.

Also PROJECT_CAN_ALWAYS_LINK_TO_ALL_SUPPLIERS is a hidden feature so it's unsupported.

**Comment by braito4** [comment]
...You can't add a supplier order when you create it; but when the supplier is already created you are able to add it.

**Comment by eldy** [comment]
PROJECT_CAN_ALWAYS_LINK_TO_ALL_SUPPLIERS has been set to 1 by default with 3.9 fixing this problem.
