### ISSUE TITLE
Access Forbidden

### ISSUE THREAD

**Issue by fgarciapatino** [Dolibarr/dolibarr#27271]
### Bug

Access forbidden at modulebuilder

### Environment Version

18.0.4

### Environment OS

Windows

### Environment Web server

XAMPP

### Environment URL(s)
modulebuilder/index.php

### Expected and actual behavior
Expected: custom module activated
Actual: access forbidden error
If comment the line
$result = restrictedArea($user, 'modulebuilder', null); 
at modulebuilder index it seems to work. security check its made at the beggining of the file
I suppose an objectid is missing when passing null

### Steps to reproduce the behavior
1.- Add permissions for modulebuilder to admin user
2.- Create a new module
3.- Try to enable de module

**Comment by nat-itopie** [comment]
Hi, you can activate you module in Setup > Modules/Applications.
The bug is fixed by https://github.com/Dolibarr/dolibarr/pull/25354
