### ISSUE TITLE
Impossible de modifier une fiche d'intervention une fois qu'elle a été validée

### ISSUE THREAD

**Issue by jerome-duchene** [Dolibarr/dolibarr#27313]
### Bug

Hello,

When I want to update an intervention that I have validated, I got a server error 500.

Please find the message log I had from Apache:
[Sat Jan 06 22:09:26.135078 2024] [proxy_fcgi:error] [pid 20255] [client xxx.xxx.xxx.xx:53727] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Serialization of 'PgSql\\Connection' is not allowed in /var/www/dolibarr/htdocs/core/lib/functions.lib.php:1272\nStack trace:\n#0 /var/www/dolibarr/htdocs/core/lib/functions.lib.php(1272): serialize()\n#1 /var/www/dolibarr/htdocs/fichinter/class/fichinter.class.php(529): dol_clone()\n#2 /var/www/dolibarr/htdocs/fichinter/card.php(203): Fichinter->setDraft()\n#3 {main}\n  thrown in /var/www/dolibarr/htdocs/core/lib/functions.lib.php on line 1272', referer: https://xxxx/fichinter/card.php?id=87&action=modify

I try with another record marked as Done, I can re-open it but if I want to modify, I receive the same error.

I have updated my version (18.0.4) and the error still present.

### Environment Version

18.0.3, 18.0.4

### Environment OS

Linux ubuntu server

### Environment Web server

apache2

### Environment PHP

8.1.2

### Environment Database

postgresql 12.12

### Environment URL(s)

fichinter/card.php?id=89&save_lastsearch_values=1

**Comment by edupulpillo** [comment]
Works fine for me with PHP8.1 and PHP8.2 MySQL/MariaDB 10.6.16-MariaDB with Dolibarr version v18.0.4 mysql

**Comment by ksar-ksar** [comment]
@jerome-duchene can you write in English please ?

It would be helpful to have the Dolibarr logs also, because it seems to be related to postgresql  ?

Thanks

**Comment by jerome-duchene** [comment]
Of course. 

I scratch my log file and retry to modify a validated intervention.
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/13854223/dolibarr.log)

**Comment by frederic34** [comment]
@jerome-duchene can you try https://github.com/Dolibarr/dolibarr/pull/27323

**Comment by jerome-duchene** [comment]
Bug corrected, I put comment on the pull request

**Comment by frederic34** [comment]
@jerome-duchene  can you test with dol_clone($this, 2)

**Comment by jerome-duchene** [comment]
It's working with the magic value 2 ;-)

Just to be sure that my bug it's not linked with a side effect, if I remove the value 2, the page crash (status code 500).
