### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2732]
All pull requests are in a false positive state.

Looks like it does not want to work with MySQL 3.6

Log excerpt:

```
/opt/mysql/server-5.6/bin/my_print_defaults: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 2 - No such file or directory)
Fatal error in defaults handling. Program aborted
Starting MySQL
. * The server quit without updating PID file (/opt/mysql/server-5.6/data/testing-worker-linux-3da96de7-1-3554-linux-20-60670620.pid).
The command "sudo /etc/init.d/mysql.server start" failed and exited with 1 during .
```

**Comment by simnandez** [comment]
I think this is a travis problem:
"In light of reported errors, we are going to cancel the 2015-04 updates at 1300 UTC 2015-04-28. Details: https://twitter.com/traviscistatus/status/592902357144498176"

Before doing anything we should expect ...

**Comment by rdoursenaud** [comment]
Good catch!
Lets see if it resolves itself…

**Comment by rdoursenaud** [comment]
Looks like the issue resolved itself.
