### ISSUE TITLE
Default barcode can not be set

### ISSUE THREAD

**Issue by abilbaotm** [Dolibarr/dolibarr#2733]
In the configurations of bar codes the default barcode for products and coustomers can not be set.
After clicking apply the change is lost.
Dolibarr 3.7.0
![captura](https://cloud.githubusercontent.com/assets/12185014/7411879/c7e9240e-ef3c-11e4-8dde-46e4aff7dd96.PNG)

**Comment by abilbaotm** [comment]
Ok. The problem is half solved.
The problem is that the module tries to modify a line of the database that does not exist.
I create the line manually and works but i can not modify the default value via web interface.
INSERT INTO `facturas`.`fac_const` (`rowid`, `name`, `entity`, `value`, `type`, `visible`, `note`, `tms`) VALUES (NULL, 'PRODUIT_DEFAULT_BARCODE_TYPE', '1', '2', 'chaine', '1', NULL, CURRENT_TIMESTAMP);

**Comment by rdoursenaud** [comment]
Unable to reproduce.
It's strange that you have a `fac_const` table here. The table is supposed to be `llx_const`…

**Comment by abilbaotm** [comment]
The table prefix was changed at the installation of dolibarr. Instead of fac_const use llx_const
Any way thanks.

**Comment by rdoursenaud** [comment]
Oh, sorry. I didn't even think you could choose `fac_` as your table prefix!
Anyway, if you have a reliable way to reproduce it from a new install, I could look into it.

**Comment by abilbaotm** [comment]
After a fresh installation of dolibarr using DoliWamp seem to occur also the problem. 
I've noticed that you can change the default barcode type if the module of products is disabled, otherwise is not possible to change the parameter.
![captura](https://cloud.githubusercontent.com/assets/12185014/7445235/bbcfee12-f1aa-11e4-8b51-e2506a4904e0.PNG)

**Comment by marcosgdf** [comment]
Cannot reproduce. Could this problem be related with DoliWamp?
