### ISSUE TITLE
French fiscal services needs special accounting export (FEC)

### ISSUE THREAD

**Issue by jpfox** [Dolibarr/dolibarr#2736]
Hi,

Is it possible to export accounting data as needed by french fiscal services ?

Here is a description of theses files : http://bofip.impots.gouv.fr/bofip/9028-PGP.html

A test tools : http://www.economie.gouv.fr/dgfip/outil-test-des-fichiers-des-ecritures-comptables-fec

Thank you for your help.

**Comment by rdoursenaud** [comment]
Dolibarr is **not** an accounting software so it's unlikely we'll ever have that even if it contains _some_ accounting informations. Plus being a FLOSS software, it will never comply with the rules enforced by the fiscal administration.

**Comment by jpfox** [comment]
Thanks for your quick answer.
Which accounting software do you recommend, easy to interface with Dolibarr ?

**Comment by rdoursenaud** [comment]
Any reasonably modern software should do.

You can use the native advanced accounting module but it's still under heavy development and things are bound to break. It's also unsupported until stable.

Another option (but I may be biased since I'm the module author) is to use the accounting export module available at https://dolistore.com.

**Comment by rdoursenaud** [comment]
Then it's your accounting software's duty to provide the FEC report and yours to keep the data up to date.

**Comment by aspangaro** [comment]
The problem in Dolibarr to be compatible with FEC data is the button "delete" in customer invoice for example.

The French fiscal services want what all data are blocked. If you want to cancel operation, you need to have a credit note.

Personnaly, I use Cegid Expert.

**Comment by eldy** [comment]
Export FEC is available if you enable the module accountancy with v10.
