### ISSUE TITLE
Missing '$sql =' before dangling filter condition in VAT filter for product_tools.php

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#27376]
### Bug

Phan reports:
```text
Unused result of a string literal " AND default_vat_code = IS NULL" near this line
```

The condition probably needs to be applied but it has not been since 6.0.2 (Fix #7473).

https://github.com/Dolibarr/dolibarr/blame/f45f5c3291b060bdd25df3777b5957a5e5e00317/htdocs/product/admin/product_tools.php#L96-L100

https://github.com/Dolibarr/dolibarr/blame/f45f5c3291b060bdd25df3777b5957a5e5e00317/htdocs/product/admin/product_tools.php#L198-L202

### Environment Version

6.0.2 to develop (since #7473)

**Comment by altairis-tof** [comment]
hello, i've just commit a fix.

**Comment by altairis-tof** [comment]
@mdeweerd you can close the issue please

**Comment by mdeweerd** [comment]
Yes, I am surprised it was not closed automatically by the integration in develop.
