### ISSUE TITLE
Bug in photo System

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2743]
in 3.7 products  photo storage system has been changed, why not. 
But without a solution for users migrating from older versions.
They all will no more find pictures of their products. Big migration issue for many users ...

must be rapidly corrected

http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/52980-disparition-des-images-produits-dans-mon-stock#59841

**Comment by jfefe** [comment]
See also #2716

**Comment by simnandez** [comment]
The #2716 only patch a bug for the new photo storage system, but we have no script migration from the old system to the new system.

**Comment by tiaris** [comment]
Yes Juanjo and this is a big hint for migrating older dolibarrs to 3.7 (and next versions).

**Comment by tiaris** [comment]
I think so, I have comitted a batch script to move photos from old directory to new. wainting for integration. 
pictures are moved to new directory, but got errors for removing old empty directories (other bug ? ). please test it in several contexts (win, mac, linux...)
We should also integrate this in product.class.php code for automatic migration

**Comment by simnandez** [comment]
But ... What is the reason for changing photo storage system?  I see: With the new storage system and depending on the file system, we have limited creation of directories images for products, for example 32000 for a ext3 file system....

**Comment by tiaris** [comment]
I don't know, we will now have a produit directory with many subdirs (one per ref), I know users with 60 000 references ...
Wheb I tested a beta (jan/feb), this update was not in the release, so I did ,ot test it

**Comment by rdoursenaud** [comment]
Seems that this regression has been introduced in 553181a5d92a52bd3b2d22ddaac8525fc8290540.

**Comment by simnandez** [comment]
I repeat: The new system is limited by the file system into subdirectories creation (ex: ext3 to 32000, ext4 to 64000), I think the best is maintain the old system by default and use hidden option for use new system (the opposite of how it is working now), @eldy What is the reason for the new system and that is by default?

**Comment by tiaris** [comment]
juanjo is right, because ther are user who manage big catalogs with Dolibarr, more than 64 000 references.
this new file system will not work for them.
We have to go back to old file system and as Junjo suggest it, add an option for thoose who want to use this new one.
I don't understand what is the sense of this new (and buggy) system file system

**Comment by tiaris** [comment]
@Juanjo : you meen that a unix file system can not have more than 32000 or 64000 directories ?
This can become an issue also in Orders, shippments, Invoices documents storage. We should have a global reflexion and solution for all this.
Sure, most Dolibarr user have less invoices or orders, but it will happen one day for a dolibarr user...
So we should find a solution before !

**Comment by simnandez** [comment]
@tiaris : yes. ext3 file system can not have more than 32000 directories at the same level, ext4 and FAT32 64000, NTFS unlimited (in theory). I tested ext3 and ext4 only.

Good catch! propals, orders, invoices.... may have the same problem!

**Comment by jfefe** [comment]
Regarding http://kernelnewbies.org/Ext4#head-97cbed179e6bcc48e47e645e06b95205ea832a68 : 

> Right now the maximum possible number of sub directories contained in a single directory in Ext3 is 32000. Ext4 breaks that limit and allows an unlimited number of sub directories. 

We must mention this bug (also with a big warning!), for me it's the same level than mysql bug if all images show off just after update.

**Comment by simnandez** [comment]
@jfefe the limit for ext4 is 64000. Until you enable the file system feature flag dir_nlink, only then will be unlimited.

**Comment by hregis** [comment]
@jfefe @simnandez @tiaris @rdoursenaud 

Right now the maximum possible number of sub directories contained in a
single directory in Ext3 is 32000. Ext4 breaks that limit and allows a
unlimited number of sub directories.

**Comment by eldy** [comment]
@simnandez Goal of change was to uniformize way of working. All dolibarr elements are stored into 1 directory, into parent directory of module. Also it makes things easier for user to manage their directories/files and backup like that.
It is also a way to find easily product dir from its ref.
So we must keep the move to the uniformed solution (one element = one dir = ref)

So this must be the default behaviour and if we have filesystem limits, we should use an option to have the get_exdir returning a subdir.

The solution to use is this one:
When we build a dir for any object, we must use get_exdir($id, 2, 0, 0, $ref, 'xxx') with xxx=invoice or order, etc..., everywhere to forge the path.

The get_exdir will return empty or subdir according to current way of working. 
In a future version, we will have to modify only the function "get_exdir" to change this, so we will be able to introduce option to change the subdir, element type by element type.

**Comment by simnandez** [comment]
@eldy Ok, We undertake the shift to get_exdir.

**Comment by tiaris** [comment]
Its a good to have an uniformed solution for pathes, but we are limiting Dolibarr's functions : there will be problems if item number will be greater than filesystem limit. We find this opportunily with the late change introduced by @eldy  for products. But this will happen also for orders, invoices, shipments... And this is a big functionnal issue ! ok with @jfefe we must mention this bug and work on a working solution for all users. 
In my sense, it will be better to have a general system with subdirectories, than a cosmetic change based on reference.

**Comment by eldy** [comment]
We can have both a uniform way of working and manage correctly path for very large number of elements.
This must be managed by the get_exdir function (the function, according to option may decide to use another storage path rule). I started to show the way into 3.8.

**Comment by rdoursenaud** [comment]
So, what's the current status of this issue?

**Comment by eldy** [comment]
In doubt, i lose the ticket because i think it is fixed.
