### ISSUE TITLE
Missing hook main.inc inf fonction top_htmlhead

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#27458]
### Feature Request

Missing hook main.inc inf fonction top_htmlhead

**Comment by altairis-tof** [comment]
top_htmlhead is called by main.inc.php so your issue is strange

**Comment by altairis-tof** [comment]
in fact top_htmlhead is a function inside main.inc.php

**Comment by altairis-tof** [comment]
@lmag there is already a hook addHtmlHeader at the end of the function; do you want another one at the beginnning to replace header ?

**Comment by FHenry** [comment]
@altairis-tof Yes that it, for replace the current manifest.json force by main.inc.php

**Comment by FHenry** [comment]
I close the issue as the PR was merged
