### ISSUE TITLE
Price format on ODT template

### ISSUE THREAD

**Issue by fred151** [Dolibarr/dolibarr#2748]
Hi developers, i'm new and hope to give a contributor for dolibarr.
In Dolibarr ERP 3.7.0 and under versions the price format on ODT template is "1000" without decimal. To solve this problem i changed some lines in the file htdocs/core/class/commondocgenerator.class.php

The language of dolibarr is set to Italian.

I Replace the function "price2num" to "price" from line 356 to 361 and from 513 to 515. Here an example:
[...]
$array_key.'_total_ht'=>price($object->total_ht),
$array_key.'_total_vat'=>price($object->total_tva),
$array_key.'_total_localtax1'=>price($object->total_localtax1),
$array_key.'_total_localtax2'=>price($object->total_localtax2),
$array_key.'_total_ttc'=>price($object->total_ttc),
$array_key.'_total_discount_ht' => price($object->getTotalDiscount()),
[...]

In general i replace the function near the tags "_ht", "_ttc", "tva" and it works.
Can i suggest to apply this fix in the next release?
Thanks folks for this great free ERP!

**Comment by marcosgdf** [comment]
Have you tried the _locale keys?

**Comment by ndrosis** [comment]
Hi @fred151 see the wiki dolibarr Amounts (in output format language) http://wiki.dolibarr.org/index.php/Create_an_ODT_document_template#Object_information_.28invoice.2C_commercial_proposal.2C_order.2C_....29

**Comment by fred151** [comment]
I copied the original file htdocs/core/class/commondocgenerator.class.php and used the
object_total_ht_locale
object_total_vat_locale
object_total_ttc_locale

And all it's ok, thanks.

## OUTPUT for a product with price 10,00

// Amount (in output language format)
object_total_ht_locale = 10,00
object_total_vat_locale = 2,20
object_total_ttc_locale = 12,20

//Amount
object_total_ht = 10
object_total_vat = 2.2

## object_total_ttc = 12.2

Maybe is better modify template_invoice.odt with the last versions.
