### ISSUE TITLE
Shipments should not depend on stocks

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2749]
Seen on Forum
http://www.dolibarr.org/forum/527-bugs-on-a-stable-version/24794-errorwarehouserequiredintoshipmentline-on-delivery

Is it right to activate shipments module without any stock management .?

**Comment by rdoursenaud** [comment]
Yes, I think we should be able to ship orders without any stock management in place since one could want to print a shipment note for its package even if he's not managing his stock in Dolibarr.

**Comment by rdoursenaud** [comment]
Fixed by @eldy  in f437bd2d6da63002ad366ea5bead1253d27fa98a
Fix available since 3.7.2.
