### ISSUE TITLE
Make MAIN_JS_ON_PAYMENT a stable feature

### ISSUE THREAD

**Issue by abilbaotm** [Dolibarr/dolibarr#2754]
Hello! 
If a customer has multiple pending invoices and is going to pay it simultaneously the operator of doli have to divide the payment into the multiple invoices manually.
I do not how to program this feature but this is how it could be:
![captura](https://cloud.githubusercontent.com/assets/12185014/7445409/d65d809e-f1b1-11e4-9007-6ddbd338cbca.PNG)
Ex: When the operator adds 15€ to the 'given' input the values of 'amount' of each invoices should change automatically.

**Comment by eldy** [comment]
A hidden option aleady exists to fill lines automaticaly withjavascriptbut was never tested nor debugged. It will be better to make it stable instead of implementing a new way to reach same goal.

**Comment by simnandez** [comment]
The hidden option is "MAIN_JS_ON_PAYMENT", and I use it a long time ago it for payments of customers and suppliers invoices without problems

**Comment by rdoursenaud** [comment]
In the light of your comments, I took the liberty to rename this issue.
I'll test this feature ASAP.
Other testers feedback welcome!

**Comment by eldy** [comment]
Hidden option seems to be FAC_AUTO_FILLJS.
I suggest to rename it into INVOICE_AUTO_FILL_PAYMENT_JS and set it to 1 by default into conf.class.php if constnat not yet defined.

**Comment by eldy** [comment]
I think something not as complete but similar is included into 5.0 by adding a picto you can click to autofill fields, so i close this one
