### ISSUE TITLE
Script injection protection in main.inc.php

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#27588]
### Bug

I'm trying to use the REST API to get thirdparty data from a PHP script, using curl.
This was working fine until recently. The problem occurred in version 16.0.4, thus I updated to 18.0.4, but the problem is the same.
`[client 127.0.0.1:49670] Access refused to 127.0.0.1 by SQL or Script injection protection in main.inc.php - GETPOST type=1 paramkey=0 paramvalue=sqlfilters=(t.nom:like:&quot;AAAAAA%&quot;) page=/dolibarr/htdocs/api/index.php/thirdparties?sqlfilters=%28t.nom%3Alike%3A%22AAAAAA%25%22%29`

My code forming the request is this one.
```

        // Search for client correspondence in Dolibarr
        $curl = curl_init();
        $httpheader = ['DOLAPIKEY: '.$apikey];
        $data = ['sqlfilters' => '(t.nom:like:"'.$client.'%")'];
        // Get from config/renewal.php
        $url = config('renewal.api.dolibarr_url').'/thirdparties?'.http_build_query($data);
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $httpheader);
        $result = curl_exec($curl);
        curl_close($curl);
```

### Environment Version

18.0.4

### Environment OS

Mageia 9

### Environment Web server

Apache 2.4.58

### Environment PHP

8.2.14

### Environment Database

MARIADB

### Environment URL(s)

/dolibarr/htdocs/api/index.php/thirdparties?sqlfilters

**Comment by fappels** [comment]
Can you try to use single quotes: $data = ['sqlfilters' => "(t.nom:like:'".$client."%')"];

**Comment by papoteur-mga** [comment]
Indeed, this seems to be OK, now. Thanks.
I don't understand why this was working, but the error raises now.

**Comment by fappels** [comment]
> Indeed, this seems to be OK, now. Thanks. I don't understand why this was working, but the error raises now.

Dolibarr security issues always get fixed. Double quotes are not secure.
