### ISSUE TITLE
Fatal error when trying to merge 2 companies in 18.0.4

### ISSUE THREAD

**Issue by sonikf** [Dolibarr/dolibarr#27599]
### Bug

Trying to merge 2 companies  in 18.0.4 throws Fatal error: Uncaught Error: Call to undefined method Societe::mergeCompany() in /societe/card.php:213 Stack trace: #0 {main} thrown in /societe/card.php on line 213
Tested also in 19.0.0 works fine

### Environment Version

18.0.4

### Environment OS

DEBIAN

### Environment Web server

APACHE

### Environment PHP

7.4

### Environment Database

MySQL

### Expected and actual behavior

The companies should be merged

**Comment by JonBendtsen** [comment]
How sure are you that you are indeed running 18.0.4?

If I do a git checkout 18.0.4 and then grep -irl mergeCompany * I get no hits

**Comment by sonikf** [comment]
Nice catch there @JonBendtsen thank you.
I'm in 18.0.4 alright, the timestamp is on par with the upgrade, but the file is different...I have to check things.
I'm closing as invalid bug.
