### ISSUE TITLE
Create a team for each contributor rank

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2764]
Reference: http://wiki.dolibarr.org/index.php/Developer_FAQ

Could we create a team for each contributor rank and add known contributors to their respective teams?

This would allow assigning bugs to volunteers.

I believe only @Dolibarr/owners has the power to do that.

**Comment by atm-maxime** [comment]
:+1:

**Comment by jfefe** [comment]
:+1:

**Comment by ndrosis** [comment]
:+1:

**Comment by rdoursenaud** [comment]
Sorry guys, this isn't working. Looks like we can only assign issues to users with write access to the repo even if it's not stated in the documentation…

Waiting for an answer:
https://twitter.com/rdoursenaud/status/621622136873091072

References:
https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
https://help.github.com/articles/adding-or-inviting-members-to-a-team-in-an-organization/
