### ISSUE TITLE
Warning: Undefined array key ticket/class/ticket.class.php L 1426 + 1427

### ISSUE THREAD

**Issue by codejx** [Dolibarr/dolibarr#27670]
### Bug

Hi - I just Upgraded to Dolibarr 19 running on Apache / Linux / PHP 8.1
An get the mentioned warning on the Dashboard.

### Environment Version

19.0

### Environment OS

Debian GNU/Linux 11

### Environment Web server

Apache

### Environment PHP

PHP Version 8.1.27

### Environment Database

0.5.21-MariaDB-0+deb11u1

### Expected and actual behavior

No Warning on the Dashboard

**Comment by codejx** [comment]
in addition:
Deleting all tickets from staging-environment let the warning disappear, 
creating new tickets let it come up again on the dashboard

**Comment by W1W1-M** [comment]
I can also see this error in v20
