### ISSUE TITLE
Parent company field value not shown in list

### ISSUE THREAD

**Issue by garciave** [Dolibarr/dolibarr#27705]
### Bug

When selected the parent company field to be shown in Third Party list, the values are not shown in the list.
If the filter is used, the behavior is correct (the list is filtered) however the parent company value is not shown.
This applies to any of the third parties list: general, prospects, customers and vendors.

### Environment Version

18.0.4

### Environment OS

Ubuntu 22.04.3 LTS

### Environment Web server

Apache/2.4.52 (Ubuntu)

### Environment PHP

PHP 8.1.2-1ubuntu2.14

### Environment Database

mysql  Ver 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

### Environment URL(s)

crm.treverdo.es

### Expected and actual behavior

When selected the parent company field to appear in the list, the name of the parent companies should appear in the list instead of all blanks.

### Steps to reproduce the behavior

Go to Third Party and click any list. Within the list, you should have the parent company selected to appear.

**Comment by ksar-ksar** [comment]
Hello,

If I understand well, this is related to multicompany external module ?
@hregis

**Comment by garciave** [comment]
Hi, it's not related. It also happens in a different environment with no multi-company module installed.

**Comment by garciave** [comment]
If you need any further info, pls let me know. Tks

**Comment by ksar-ksar** [comment]
Ok I see,

Bug confirmed on my dolibarr V18.0.4 : 
![image](https://github.com/Dolibarr/dolibarr/assets/35605507/f8aae006-43de-45cd-891a-38f61b09290b)

**Comment by W1W1-M** [comment]
Bug is also present in v19 & v20

**Comment by W1W1-M** [comment]
This regression is fixed in 18.0.5 0aae72b6
