### ISSUE TITLE
Can't use RFC 2822 email adresses with display name anymore

### ISSUE THREAD

**Issue by hameau** [Dolibarr/dolibarr#2772]
An email address in the format `John Smith <john.smith@gmail.com>` shows the alert `EMail John Smith <john.smith@gmail.com> is wrong`. This error appears in all displayed email address fields.

Dolibarr v3.7.0, upgraded with DoliDeb from v3.6.2.

This is a regression from previous versions.

**Comment by rdoursenaud** [comment]
Could you please be a bit more explicit as to where the problem occurs (thirdparty card, contact card, emailing module?).

**Comment by hameau** [comment]
Sorry, more details.

Warning symbol (eldy theme) shows, for example, in the following views:
- Third-party
  - (societe/soc.php)
  - (comm/card.php)
  - Contacts/Addresses summary for these two views
- Contacts/Addresses card (contact/card.php)

These are for cases where an email address was already present in the third-party record before upgrading to v3.7.0.

Perhaps a greater issue, in v3.7.0 it is no longer possible to enter an email address in the form `Name Lastname <name.lastname@domain.tld>`, as the whitespace and <, > characters are stripped before saving, which breaks the email address completely. There is nothing wrong with the form `Name Lastname <name.lastname@domain.tld>` to include a human-friendly name within an email address, especially if the email address itself does not include the addressee's name.

**Comment by rdoursenaud** [comment]
OK, I now better understand. It's a feature I had never experienced!
So this is a regression in 3.7 that don't interpret [RFC 2822](https://tools.ietf.org/html/rfc2822) display names as it used to.

**Comment by rdoursenaud** [comment]
I think it's been introduced in cfe35f32 which introduced stricter email address sanitization.
Don't know if it's a bug or a feature.
I kinda like that the string is better sanitized but I understand your frustration to see that a useful feature disappeared in the process.
We need an insight from @Dolibarr/owners

**Comment by hameau** [comment]
Thank you for distilling my comments ! The title now accurately reflects my intention.

I understand the need to sanitise form input, but this is definitely a bug for me. In Dolibarr, the email field becomes a clickable `mailto:` link in the third-party and contact cards, so if a local mail client is used, the email field becomes the mail message `To:`.

**Comment by eldy** [comment]
Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by hameau** [comment]
This is still evident in v3.9.3.

I have been manually removing `FILTER_SANITIZE_EMAIL` from `htdocs/societe/soc.php` for each upgrade.

This is fine for me – I am single-user on a localhost installation, which is not public-facing.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by hameau** [comment]
In case of future searchers:

The loss of RFC2822 formats for Dolibarr email entry is by design, in the interests of security. If this is important for an individual case, it is possible to make local changes (see my [earlier comment](https://github.com/Dolibarr/dolibarr/issues/2772#issuecomment-244484869)) to restore the previous behaviour.
