### ISSUE TITLE
Proposal Bug when approve

### ISSUE THREAD

**Issue by mariamanc28** [Dolibarr/dolibarr#2773]
Hi, i note that from ultimat update of dollibar version, the proposal workflow non run correcly. In particular when i close an proposal and sign with "Signed" the status seems update, ma real not updated , the proposal is yet opened. The the workflow of not signed proposal run correctly. Can you verify?

**Comment by marcosgdf** [comment]
Tested with 3.7.0 and it works OK for me. Could you check the log to see if there is any error? Have you got any external module enabled?

**Comment by mariamanc28** [comment]
i don't have external module active on proposal, i have active in another part of dolibar external module.  You have testing complete workflow? because when i upadate a proposal as sign, the next step appear me that proposal are signed,infact the check change color, but when i select list of proposal active that proposal appear me again.  i make you a screen if necessary. how i can read the log?

**Comment by mariamanc28** [comment]
i have find error:  DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'namecostume' in 'field list'
2015-05-11 10:41:42 ERR     93.57.79.98      Interfaces::run_triggers action=PROPAL_CLOSE_SIGNED Files found: 7, Files launched: 4, Done: 1, Failed: 1
2015-05-11 10:42:34 ERR     93.57.79.98      Contact::fetch 
2015-05-11 10:42:34 ERR     93.57.79.98        DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'namecostume' in 'field list'
2015-05-11 10:42:34 ERR     93.57.79.98      Interfaces::run_triggers action=PROPAL_CLOSE_SIGNED Files found: 7, Files launched: 4, Done: 1, Failed: 1

i have added in table form dolibar a new field called name costume.... i aspect that program mange automatically update of new added field or not?

**Comment by rdoursenaud** [comment]
Modifying the database schema and/or the code is unsupported. You should use the attributes or a custom module if you need extra data.

**Comment by mariamanc28** [comment]
i have used att5ribute of module proposal for create filed! and before upgrade on ultimate version all are run correcly! now what i do? i use attribute of original module, please help me for resolve the problem. before update all run

**Comment by marcosgdf** [comment]
Maria, you must try to give us as many information as possible to diagnose the error. From the logs I can see something is trying to write into a non-existing field. An update wouldn't erase erase complementary attributes.

**Comment by mariamanc28** [comment]
then i try to explain the situation... i have create e new field in module proposal, an simplex field text. Before dolibar update all run correctly and i can update the proposal with this field compilated or not. Now after dollibar update an 3.7 version this update not run more. This is error log:
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'namecostume' in 'field list'
2015-05-11 10:41:42 ERR     Interfaces::run_triggers action=PROPAL_CLOSE_SIGNED Files found: 7, Files launched: 4, Done: 1, Failed: 1
2015-05-11 10:42:34 ERR           Contact::fetch 
2015-05-11 10:42:34 ERR          DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'namecostume' in 'field list'
2015-05-11 10:42:34 ERR         Interfaces::run_triggers action=PROPAL_CLOSE_SIGNED Files found: 7, Files launched: 4, Done: 1, Failed: 1

**Comment by marcosgdf** [comment]
Which was your previous version?

**Comment by mariamanc28** [comment]
3.6.2

**Comment by marcosgdf** [comment]
I'm sorry I can't reproduce.

**Comment by mariamanc28** [comment]
and how you suggest me to proceed?

**Comment by marcosgdf** [comment]
You could try to create an additional atribute again with the same name so that the query to the database doesn't fail again...

**Comment by mariamanc28** [comment]
i have already think this, i try and tell you :)

**Comment by dreggy** [comment]
Edit: i opened a new bug #4789

hi, i had the same problem without adding fields, the workflow doesn't show up errors and the proposal seems to get closed, but if i reload the proposal is not closed.

The log shows
2016-03-10 22:35:58 ERR     79.21.237.100                           DoliDBMysqli::close Closing a connection with an opened transaction depth=24

so i checked the code and found that on file
        **comm\propal\class\propal.class.php**
if i comment the line **1982**
       **$this->generateDocument($modelpdf, $outputlangs, $hidedetails, $hidedesc, $hideref);**
all start working good.

it seems to me that this line mess up the **$this->transaction_opened** counter, so the next call  **$this->db->commit();** on the line **1994** will fail

data to reproduce
   Dolibarr version 3.8.3
   Pdf model "azur"

**Comment by mariamanc28** [comment]
try to disable module proposal and riactivate it. it run for me.

**Comment by dreggy** [comment]
i updated to 3.9 and now it is all working good
