### ISSUE TITLE
vcard issues

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#27771]
### Bug

The vcard feature is very prominent now in in version 18-

There are some issues:

- [ ] encoding issue (problems with umlauts in vcf download file)
- [ ] email is not usermail but company mail
- [ ] personal address in vcf file -- should at least be selectable to use company address

### Environment Version

18.x (git)

### Environment OS

linux

### Environment Web server

apache

### Environment PHP

7.4/8.1

Replaces #16945

**Comment by eldy** [comment]
The option to show the address has been inverted. Now named USER_PUBLIC_SHOW_ADDRESS and False by default.
