### ISSUE TITLE
External modules "depends" property is not respected when module is missing

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2777]
Version: 3.5.6 and 3.7.0 (maybe 3.6 and 3.8 are affected)

Given an external module with this piece of code in module descriptor:

```
$this->depends = array(
            'modProducts'
        );      // List of modules id that must be enabled if this module is enabled
```

As you can see, "modProducts" is incorrect because the correct name is "modProduct". So the module should not be enabled and an error message with the content "This module requires %s module but it is not available in your system" should be displayed.

**Comment by eldy** [comment]
OK, to add an error message. "Module X depends on module Y that is missing, so module X may not work correclty. Please install module Y or disable module X if you want to be safe from any surprise."
However, module X must not be disabled except if user do it.

**Comment by marcosgdf** [comment]
What about not allowing the user to enable the module if any dependencies are missing? Let's say that an external module does some operations in the init function... That would be a problem, right? Maybe not in core modules but in a 3rd party module depends on another 3rdparty module...
