### ISSUE TITLE
Project contacts add UserGroup

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#27774]
### Feature Request

add the possibility to add usergroups as contacts to projects

### Use case

you can add a usergroup (with all members) in one step 
and do not have to add the members of this individually

### Suggested implementation

1. insert a line to select groups   at  /projet/contact.php

2. after selection & adding:  i see two options to handle
   A)  copy all members of the group into contacts  
       or
   B)  keep the group and link always to actual group members

**Comment by JonBendtsen** [comment]
good idea
