### ISSUE TITLE
mass action to create member subscriptions

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#27777]
### Feature Request

in member list select members to make mass action create new subscription

**Comment by JonBendtsen** [comment]
which dolibarr version?

**Comment by dolibit-ut** [comment]
> which dolibarr version?

it is a feature request - not a bug  (as far as i know), so no version - i hope maybe yet in version 19 ;-)

**Comment by dolibit-ut** [comment]
@Hystepik   Thank you very much for your work.  I will try it out.  Did you tested at v19 (develop) or v18?
