### ISSUE TITLE
v19-beta needs transifex synch

### ISSUE THREAD

**Issue by priojk** [Dolibarr/dolibarr#27785]
### Bug

I just noticed a missing transifex synch for the upcoming v19. One example: the new fiscal year feature is missing the translation on the setup page (the step displayed in English instead):
<img width="675" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/10772984/13512abb-f72f-4a89-9c6c-680a266da0fa">

The translation is already availabl in Transifex.

### Environment Version

v19-beta

**Comment by priojk** [comment]
@eldy Could you do this Transifex synch?

**Comment by eldy** [comment]
I will...

**Comment by priojk** [comment]
Thanks!
