### ISSUE TITLE
Add field warehouse in product/list.php

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#27810]
### Feature Request

Missing filter by warehouse
![image](https://github.com/Dolibarr/dolibarr/assets/3288514/f9af9a38-2749-4fc9-b06e-f6210baf550a)

see
https://github.com/Dolibarr/dolibarr/issues/12712

**Comment by FHenry** [comment]
I close the issue because it can be done by warehouse card 
![image](https://github.com/user-attachments/assets/3745cd67-0c44-48bb-a48e-8012cc2dbc4d)
