### ISSUE TITLE
Merge pdf doesn't work for commande

### ISSUE THREAD

**Issue by dgfmdrv** [Dolibarr/dolibarr#27815]
### Bug

When I run a merge pdf on commande I get a message "File generated" but the list at bottom is empty.
![image](https://github.com/Dolibarr/dolibarr/assets/1451834/5356e120-c3d7-41f3-b35d-8f1a85b4913f)
![image](https://github.com/Dolibarr/dolibarr/assets/1451834/1c357b82-1cb0-4232-a168-9568a957afef)

It works for "propale" for example. 

I can see the file on disk but not on the web.

### Environment Version
Reproducible on 18.0.0 (https://demo.dolibarr.org) and 18.0.4.

**Comment by altairis-tof** [comment]
it works on my local 18.0.4 version; i dont understand why it is not working on demo instance

**Comment by AlexVare** [comment]
I had the same issue, I'm using the 18.0.4 version and when I try to merge commande the "File has been generated" message pops up but I can't see it on the web.
![merge1](https://github.com/Dolibarr/dolibarr/assets/81935216/936fb249-a33b-4624-9240-cb8b722fdce2)
![merge2](https://github.com/Dolibarr/dolibarr/assets/81935216/e673abce-8c12-4278-b302-044a774e3c31)
![merge3](https://github.com/Dolibarr/dolibarr/assets/81935216/8dd2525a-196c-49a5-8fe9-9bcffe9baf60)

It works also for other parts but not on that one especifically.

**Comment by hregis** [comment]
@dgfmdrv @AlexVare I don't have this problem with 18.0.5

**Comment by dgfmdrv** [comment]
I suspect the problem was with the directory permissions. I will close the issue.
