### ISSUE TITLE
Add product label to Third Parties - Customers Prices tab

### ISSUE THREAD

**Issue by studiostarstuff** [Dolibarr/dolibarr#2785]
Hello!

i'm testing dolibarr 3.7.0 and i noticed after adding prices to a customer that the data shown in Customers Prices tab does not include a "label" for the products, it shows the product Ref only (i use numbers only in reference), it needs to show the product labels so one can quickly look up at the prices per customer.

im using the option DIFFERENT PRICE FOR EACH CUSTOMER, 

you can find the Customers prices tab in
1. Third Parties
2. Select a customer
3. look for Customers Prices 

Thank you Dolibarr Team!

**Comment by rdoursenaud** [comment]
File: //societe/price.php
In-place edition has the same defect than the list. Makes it difficult to assess which product we're working with.

**Comment by eldy** [comment]
Price edition now show a combo with ref+label
We miss the label in the list  /societe/price.php
