### ISSUE TITLE
Objectline_add template shows "0" for non-vat suppliers

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2786]
Version: 3.6.3

It shows "0" in VAT column instead of "0%".

![captura de pantalla 2015-05-07 a las 10 15 55](https://cloud.githubusercontent.com/assets/168744/7511037/3e45bfe4-f4a2-11e4-80ff-3931a81b9d0e.png)

**Comment by rdoursenaud** [comment]
Needs testing on 3.5.6 and 3.6.3

**Comment by marcosgdf** [comment]
Happening in 3.6.3 too. 3.5.6 is not having the same behaviour:

![captura de pantalla 2015-05-10 a las 1 01 00](https://cloud.githubusercontent.com/assets/168744/7552354/0bc82646-f6b0-11e4-9dd2-4e229385c54f.png)

**Comment by rdoursenaud** [comment]
I don't see how 3.5.6 behavior is not correct. What's expected?

**Comment by marcosgdf** [comment]
The problem is not in 3.5.6 but in 3.6.2. I tested in 3.5.6 but since the objectline_add has changed so much between those versions, it only happens since 3.6.

**Comment by rdoursenaud** [comment]
Ok, sorry, didn't understand you correctly.
