### ISSUE TITLE
Keyboard Shortcut Support

### ISSUE THREAD

**Issue by studiostarstuff** [Dolibarr/dolibarr#2787]
Hello!

How about adding keyboard shortcut support? this will make you faster working with Dolibarr using the keyboard

Some examples of shortcuts are

Create Draft = Alt + C

Add new line -- [Add] = Alt + A

Validate = Alt + V

Create Invoice = Alt + I

Classify Paid = Alt + P

link below is my post in the forum
http://www.dolibarr.org/forum/11-suggest-new-features/24726-keyboard-shortcut-support#25690

Thank you Dolibarr Team!

**Comment by laudeco** [comment]
Hi @studiostarstuff ;
Do you expect those shortcuts editable?

**Comment by cfoellmann** [comment]
is there some kind of (jquery) javascript "library" for soomething like this?
Without a good project getting dolibarr half-way there......

**Comment by laudeco** [comment]
Yup I already implemented it in another library https://github.com/ccampbell/mousetrap

**Comment by cfoellmann** [comment]
the moustrap library looks promising.

**Comment by laudeco** [comment]
> Hi @studiostarstuff ;
> Do you expect those shortcuts editable?

No response ? 
I have some time to develop it
