### ISSUE TITLE
getDolGlobalString and string "0" returns '' or default value

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#27883]
### Bug

Hello
i think there is a big fail on getDolGlobalString function in race condition where we store "0" string as value ...

```
	return (string) (empty($conf->global->$key) ? $default : $conf->global->$key);
```

-> empty(0) return true then the function return default value, not "0"

just try that php code:

```
echo 'empty("0") returns ' . empty("0") . "\n";
echo 'empty(0) returns ' . empty(0) . "\n";
echo "empty('0') returns " . empty('0') . "\n";
```

results:

```
empty("0") returns 1
empty(0) returns 1
empty('0') returns 1
```

**Comment by altairis-tof** [comment]
Hello, this was fixed in dolibarr v18

**Comment by rycks** [comment]
@altairis-tof yes that is in 18.0 but here is the situation:

- in old versions before "getDolGlobalString" we can store "0" string in conf values then people who as that sort of data in their dolibarr are "ok"
- do an upgrade in dolibarr 14 ... 15 ... 16 ... 17 ... and "boum" the bug is here, "0" is empty then return '' ...
- but in 18.0 you can have it again

So my fix / bug is for 14

**Comment by rycks** [comment]
https://github.com/Dolibarr/dolibarr/pull/27904

**Comment by altairis-tof** [comment]
i let @edy decide.

**Comment by altairis-tof** [comment]
ok @rycks your PR has been merged; i close the issue.
Good job ;-)
