### ISSUE TITLE
Import Customer Prices

### ISSUE THREAD

**Issue by studiostarstuff** [Dolibarr/dolibarr#2789]
Hello!

i would like to request a way to mass/batch import of customer prices into Dolibarr, currently adding it one at a time, this request is similar to the import of Suppliers prices (of products or services) but for customers

Thank you Dolibarr Team!

**Comment by rdoursenaud** [comment]
FYI You can already do that with the product and service import.

**Comment by technoartista** [comment]
i need this feature too

**Comment by eldy** [comment]
A first try should be available in 7.0 with this commit
e14087845883657bcf4e9469480d4c7ac9845fb0

**Comment by torvista** [comment]
I believe this can be closed now.

**Comment by atm-maxime** [comment]
Not sure, I think the feature is to add an import of product prices by cutomer.

**Comment by torvista** [comment]
To clarify further, this request is

NOT for the import of multiple prices per levels. This is implemented.

it IS for the import of special prices per product, per customer, requiring the import to llx_product_customer_price. This import is not currently implemented.

Anyone else need this functionality?

**Comment by ma0dubois** [comment]
> To clarify further, this request is
> 
> NOT for the import of multiple prices per levels. This is implemented.
> 
> it IS for the import of special prices per product, per customer, requiring the import to llx_product_customer_price. This import is not currently implemented.
> 
> Anyone else need this functionality?

Hi,

Yes me, so for moment, i am developing a specific module
