### ISSUE TITLE
Import updated Product data

### ISSUE THREAD

**Issue by studiostarstuff** [Dolibarr/dolibarr#2790]
Hello!

Would it be possible to add an import for updated Product data? this is similar to importing Products but will be used only for products that needs to be updated regularly / mass update

i'm coming from a spreadsheet with the all the product data, i'm able to import most of the data successfully, the problem i see in the future is updating the prices and some product details, i use the spreadsheet to compute for multiple discounts given by the supplier, sometime more than 5,
(ex. base price of 100 less discount 20%-10%-10%-5% =  61.56) , its crazy but thats the way they do business, and also they update their prices so i need to update the products prices. to update these changes in Dolibarr alone will take more time than needed, so i request this feature to import updates to make the user more productive in a way.

Thank You Dolibarr Team!

**Comment by torvista** [comment]
I believe this can be closed now.

**Comment by atm-maxime** [comment]
Yes I close this one, now with 8.0 version the standard import tool allows to update data based on a key.
