### ISSUE TITLE
Missing Mobile Phone field on thirdParty

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#28070]
### Feature Request

Missing Mobile Phone field on thirdParty

**Comment by bos4711** [comment]
Bug confirmed for v17.0.2. The field "Mobile Phone" can be found under a Thirdparty contact, but not under the Thirdparty itself (which OP is reporting about).

**Comment by JonBendtsen** [comment]
18.0.4 - there is a phone field on thirdparties, and I just use that for my mobilePhone.
