### ISSUE TITLE
Dolibarr 18.0.4 BITNAMI AWS INSTANCE, SSL Issue HTTPS / 

### ISSUE THREAD

**Issue by doliflex** [Dolibarr/dolibarr#28073]
PHP_OS | Linux
Version | Linux ip-172-31-40-156 5.10.0-27-cloud-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64

Hello Good community 

i'm new when it comes to hosting, so my problem is about HTTPS, i have used BITNAMI package to setup Dolibarr 18.0.4  on AWS EC2 Instance, i have requested SSL certificate through AWS ACM and linked it to my domain through Route 53, now i think i need to configure apache to use HTTPS using AWS Cloudshell, but i can't find apache root, i searched everywhere through bitnami documentation and even using chat GPT to do so, this might be a simple task for you guys, but for us the newbies it could take ages ! 

for information; securty group on AWS are up and working, also support HTTPS port 443
could anyone please help with this issue, we struggling donw here :(

**Comment by ksar-ksar** [comment]
Hello,

This is a question to be raised to Bitnami.
Dolibarr has no clue on this
