### ISSUE TITLE
Merge that went wrong?

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#28071]
### Bug

@eldy  Sorry for tagging directly, but this concerns a merge

https://github.com/Dolibarr/dolibarr/compare/2a28248..854292e

Something went wrong when merging 2a28248d to 854292e .  

I double confirmed that this is a direct transition (7db64c5bcc0 is the commit just before 2a28248d):
```
$ git rev-list --ancestry-path 7db64c5bcc0..854292ea47d
854292ea47ddb87714fae56e2dc4d338a5dd238f
2a28248dd4e9202d7cadfc9e91de35d29ab16173
```

I discovered this when I went looking for the reason some changes that I made in PR's went missing in the develop branch.

**Comment by frederic34** [comment]
@mdeweerd, ah, thank you for finding my pull requests, I thought I dreamed them 👴🏼 
@thibdrev @W1W1-M

**Comment by thibdrev** [comment]
Thanks @mdeweerd.
Indeed I was also wondering why phpstan was still throwing a bunch of errors related to getNextValue() while I had patiently corrected them one by one 😃

**Comment by mdeweerd** [comment]
I managed to put together a script/method to reconstruct a branch that could be proposed as a PR to recover the lost commits.

[recover-merge.txt](https://github.com/Dolibarr/dolibarr/files/14215887/recover-merge.txt)

**Comment by mdeweerd** [comment]
Maybe you ( @frederic34,@thibdrev,@W1W1-M) can help out to make the right decisions on the merge conflicts in #28083 - especially if it concerns code that you updated ?
A PR to my branch redo-1 ?  Currently set as the main branch of https://github.com/mdeweerd/dolibarr .

**Comment by thibdrev** [comment]
Happy to help but my git knowledge is probably not sufficient.
My PRs shall be relatively simple since they're only phpstan/phpdoc fixes.
