### ISSUE TITLE
Show warning sign in homescreen if dolibarr database version differs from actual dolibarr version

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2810]
Because you cannot notice this until you access "Info Dolibarr" page, it would be _very_ nice to warn the user in the homescreen when the dolibarr database version differs from the version of the code.

![captura de pantalla 2015-05-11 a las 12 30 43](https://cloud.githubusercontent.com/assets/168744/7563024/ba8327a6-f7d9-11e4-8b10-37b5dd6213db.png)

**Comment by rdoursenaud** [comment]
IMHO even logging-in shouldn't be allowed with such discrepancies.
