### ISSUE TITLE
Computed field (complimentary attribute) no longer working in version 19.0.0

### ISSUE THREAD

**Issue by garciave** [Dolibarr/dolibarr#28165]
### Bug

We had a complimentary attribute for the Project module to calculate the quantity of days the project was running. It was working ok but stopped working after upgrading to v19.0.0

The formula used was: round((($object->date_end ? idate('U', $object->date_end) : idate('U')) - idate('U', $object->date_start)) / 60 / 60 / 24, 0)

It was working like a charm upto v18.0.4 but now is giving the following error:
Bad string syntax to evaluate (found call of a function or method without using direct name): round((($object->date_end ? idate('U', $object->date_end) : idate('U')) - idate('U', $object->date_start)) / 60 / 60 / 24, 0)

Unless there is a change on how to call the object, it seems an issue on how the new version is processing the formulas.

### Environment Version

19.0.0

### Environment OS

Ubuntu 22.04.3 LTS

### Environment Web server

Apache/2.4.52 (Ubuntu)

### Environment PHP

PHP 8.1.2-1ubuntu2.14

### Environment URL(s)

mysql Ver 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

### Expected and actual behavior

It's expected an integer with the number of days lapsed between today (or the date the project ended) and the start date.

It's giving the error above mentioned: Bad string syntax to evaluate (found call of a function or method without using direct name)...

### Steps to reproduce the behavior

Create a complimentary attribute within the module (in this case Project) and define a new addtional / custom attribute.
Follow the process to create a a new attribute and in the computed field enter the formula:
round((($object->date_end ? idate('U', $object->date_end) : idate('U')) - idate('U', $object->date_start)) / 60 / 60 / 24, 0)

**Comment by hregis** [comment]
@garciave Hello, and what is the type and config of your "complimentary attribute" ? integer, text, varchar, etc... ?

**Comment by garciave** [comment]
It is integer.
Regards

**Comment by hregis** [comment]
@garciave you can not execute a "round" with an integer !!! this is not a float !
try this instead : 

`($object->date_end ? idate('U', $object->date_end) : idate('U')) - idate('U', $object->date_start)/86400`

**Comment by hregis** [comment]
@garciave and try with this : 

gmdate('Y-m-d', ($object->date_end ? idate('U', $object->date_end) : idate('U')) - idate('U', $object->date_start)/86400)

**Comment by hregis** [comment]
for replace timestamp with a formated date

**Comment by hregis** [comment]
this is just a wrong computed php request, i close this issue... have a good day

**Comment by garciave** [comment]
@hregis Tks for the response that sent me in the right direction. 
Couple of comments:
1- if you look into the round function, it was a float to no decimals; however the response it's a float, PHP will cast it as an int. This is why if you try in version 18.0.4, it works.
2- your solutions brings a date and not an integer number with the number of days lapsed in between the two dates

I fixed it simply setting the complimentary attribute to a float with 0 decimals and eliminated the call to round.

Tks for taking the time in any case.

Regards
