### ISSUE TITLE
Install dolibarr 19 not botom

### ISSUE THREAD

**Issue by edsonblwolf** [Dolibarr/dolibarr#28178]
### Bug

![Captura de tela_2024-02-14_16-21-08](https://github.com/Dolibarr/dolibarr/assets/50527894/c879ccb5-a0bf-4cf2-b889-1f3cb4ac16a0)
![Captura de tela_2024-02-14_16-26-21](https://github.com/Dolibarr/dolibarr/assets/50527894/5f53e93a-489f-4fd5-9a1e-578855271aa5)

### Environment Version

19

### Environment OS

Alpine Linux 3;19

### Environment Web server

lighthttpd

### Environment PHP

1.4.73

### Environment Database

postgresql 16

### Environment URL(s)

192.168.1.96

### Expected and actual behavior

The button to continue installation does not appear.

**Comment by frederic34** [comment]
do you have php-pgsql extension installed ?

**Comment by edsonblwolf** [comment]
It wasn't, I installed it, restarted it and it doesn't appear to continue.

apk list|grep php82-pgsql 
php82-pgsql-8.2.16-r0 x86_64 {php82} (PHP-3.01 BSD-3-Clause LGPL-2.0-or-later MIT Zend-2.0) [installed]

**Comment by hregis** [comment]
@edsonblwolf this a php error, check your logs

**Comment by edsonblwolf** [comment]
I had to install php82-mysqli to continue, but I'm not going to use mysql, is that really the case?

**Comment by Elnaril** [comment]
Hi!
I got the very same issue while trying to install Dolibarr V19.0.1. I solved it just by installing Dolibarr v18.0.5.

Software | Version
--- | ---
Ubuntu Server | 22.04.4 LTS
postgresql | 14+238
php | 2:8.1+92ubuntu1
php-pgsql | 2:8.1+92ubuntu1
apache2 | 2.4.52-1ubuntu4.8
