### ISSUE TITLE
Class name of the resource module's CRUD is reserved

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2820]
The classname `Resource` is reserved in PHP for [resources](https://php.net/manual/fr/resource.php) (file handlers, database handlers, sockets…).
Using it messes with type hinting in IDEs.
I think it should be renamed to something like `DolResource`.
ping @jfefe

**Comment by jfefe** [comment]
:(

Ok I'll do this asap.

**Comment by marcosgdf** [comment]
Still called Resource in 3.9 branch

**Comment by jfefe** [comment]
Fixed into PR #4473 and waiting tests

**Comment by eldy** [comment]
Done
