### ISSUE TITLE
Line to setup MAIN_BUGTRACK_ENABLELINK should be always visible

### ISSUE THREAD

**Issue by jfefe** [Dolibarr/dolibarr#2821]
# Environment
- **Version**: 3.7.0
- **OS**: Linux
- **Web server**: Apache/2.2.22 (Debian)
- **PHP**: fpm-fcgi 5.4.40-1~dotdeb+wheezy.1
- **Database**: MySQL 5.5.37-0+wheezy1
- **URL**: /Dolibarr/dolibarr-3.7/htdocs/admin/const.php
# Report

Into admin setup, line for set MAIN_BUGTRACK_ENABLELINK is shown only if MAIN_FEATURES_LEVEL > 1.

Maybe the link to bug tracker should be visible by default ?

**Comment by jfefe** [comment]
@rdoursenaud pushed #2822 for this :+1:

**Comment by eldy** [comment]
Option is now visible for all setup.
