### ISSUE TITLE
No signature in propal after onlinesign

### ISSUE THREAD

**Issue by antho2305** [Dolibarr/dolibarr#28210]
### Bug

When a customer sign the proposal using the link the propal is accepted but the sign doesnt show in the the PDF the square is blank whereas the customer signed it

### Environment Version

19

### Environment OS

Cpanel 

### Environment PHP

8.1

### Environment Database

MariaDB

### Environment URL(s)

https

### Expected and actual behavior

The sign doesnt show on propal PDF

### Steps to reproduce the behavior

Create à propal go to the link to onlinesign the propral validate, sign it but the generated doc doesnt show the signature on the pdf file

**Comment by sonikf** [comment]
Works for me as expected in v. 19.0.0 and PHP 7.4, 8.0, 8.1, 8.2

**Comment by antho2305** [comment]
Yes It was due to a module sorry you can close it as solved
