### ISSUE TITLE
 Bug on the display of date extrafields

### ISSUE THREAD

**Issue by ipdeveloppement44** [Dolibarr/dolibarr#28222]
### Bug

After modifying a line on a contract, the date extrafields appear identical on all lines of the contract. This is a bug only at the display level, as the data in the database is correct.

### Environment Version

18.0.3

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

8.1

### Environment Database

MariaDB 10.3.39

### Expected and actual behavior

When updating a date extrafield on an invoice, order, contract, or other entity, after submitting the modification, the display of this extrafield on all lines of the contract, for example, is identical as if it had been modified for all lines. If the page is reloaded, it is evident that the values are different, and the modification has been correctly applied only to the line that was edited.

### Steps to reproduce the behavior

To replicate the issue, add a date-type extrafield to an object (contract, invoice, order, etc.). For the example of a contract, create a contract and add multiple lines to it. Validate the contract and then modify the date-type extrafield on one of the contract lines and save the modification. In terms of display, the extrafield seems to have the same value on all lines of the contract. Reloading the page reveals the correct values, and it becomes apparent that the extrafield no longer has the same value on all lines.

### Attached files

Before modification:
![Before modification](https://github.com/Dolibarr/dolibarr/assets/132068748/988d979a-a2e0-4660-925a-e8e2b3863710)
during modification:
![during modification](https://github.com/Dolibarr/dolibarr/assets/132068748/6dc452fd-51e9-4f88-96f6-14839b03dbec)
after modification:
![after modification](https://github.com/Dolibarr/dolibarr/assets/132068748/07dcd8f5-ecda-4406-9b10-6780b608d0b1)
once the page is reloaded:
![once the page is reloaded](https://github.com/Dolibarr/dolibarr/assets/132068748/67fcba23-3529-4c7a-a5a6-61839bede8a7)

**Comment by FHenry** [comment]
fix by https://github.com/Dolibarr/dolibarr/pull/31914
