### ISSUE TITLE
Warning: Undefined array key "totalbalance" in htdocs/accountancy/bookkeeping/listbyaccount.php on line 1278

### ISSUE THREAD

**Issue by AWeerWolf** [Dolibarr/dolibarr#28296]
### Bug

Warning: Undefined array key "totalbalance" in htdocs/accountancy/bookkeeping/listbyaccount.php on line 1278

![Screenshot 2024-02-20 001131](https://github.com/Dolibarr/dolibarr/assets/74211972/7621f68f-7ecb-45e4-bfd8-23d757995f94)

**Comment by AWeerWolf** [comment]
Only with PHP 8.0
No warning with PHP 7.4

**Comment by sonikf** [comment]
No errors in v 19.0.0 PHP 7.4, 8.0, 8.1, 8.2

**Comment by lunoshist** [comment]
I have the same warning, 
I'm in v19.0.1 and PHP 8.1.25, and above all I'm developing my own module so I activated 'display_errors=On' in my php.ini and xdebug.

I personnaly removed the warning with this simple change : 
```
$totalarray['val']['totalbalance'] += $line->debit - $line->credit;
```
into
```
isset($totalarray['val']['totalbalance']) ? $totalarray['val']['totalbalance'] += $line->debit - $line->credit : $totalarray['val']['totalbalance'] = $line->debit - $line->credit;
```
