### ISSUE TITLE
ER: In PDF, status have a problem with accents

### ISSUE THREAD

**Issue by aspangaro** [Dolibarr/dolibarr#2832]
Version develop
Language French

In the new module expense report, the status is traduced but in the pdf, little problem with accents. I don't find the way to correct this, thanks.

![2015_05_14_07_25_26_aspangaro_er00006_150504_3_ pdf_adobe_reader](https://cloud.githubusercontent.com/assets/2341395/7626522/d1b24b72-fa0a-11e4-82e0-19156f0ab81c.png)

**Comment by marcosgdf** [comment]
Probably just needs a Translate::transnoentities instead of Translate::trans

**Comment by marcosgdf** [comment]
Cannot reproduce. In fact, it is not even translated...

![captura de pantalla 2015-07-07 a las 12 15 26](https://cloud.githubusercontent.com/assets/168744/8544016/e022431c-24a1-11e5-860e-0dd8271ebcd3.png)

**Comment by aspangaro** [comment]
Thanks @marcosgdf
