### ISSUE TITLE
New Module WebPortal

### ISSUE THREAD

**Issue by K-razy** [Dolibarr/dolibarr#28320]
### Feature Request

Hello, I may be wrong but i thought, a new module called WebPortal should be available in version 19.0
I tried to find it, with no success. I wanted to know if this module has been abandoned ?

Thanks a lot.

Best Regards

**Comment by sonikf** [comment]
Ηι @K-razy 
WebPortal module is not available in v 19.0.0 as it was merged quite recently in branch develop.
It should be available in a future release, hopefully 20.0.0

**Comment by K-razy** [comment]
Hi @sonikf Thanks a lot for your answer.
Hope it will be available soon 🙏
