### ISSUE TITLE
Using 2 digits (yy) for the date format goes to 19XX

### ISSUE THREAD

**Issue by AWeerWolf** [Dolibarr/dolibarr#28334]
### Bug

Specifying 2 digit in the date format : FormatDateShortJavaInput
The date generated is in 1900...
Bug in file : lib_head.js.php 
line 347 : var year=now.getYear(); if (year.length < 4) { year=""+(year-0+1900); }
and
line 372 : if (substr == "yy")   year=""+(getIntegerInString(val,d,2,2)-0+1900);

### Environment Version

19.0.0

### Environment PHP

7.4

### Environment Database

MariaDB

### Attached files

![Dolibarr-001](https://github.com/Dolibarr/dolibarr/assets/74211972/4cfbd0d6-67e1-49f1-be58-ff18ccc5f382)
![Dolibarr-002](https://github.com/Dolibarr/dolibarr/assets/74211972/7c60a36f-dd0f-447d-a372-c4f8d2e918d1)

**Comment by JonBendtsen** [comment]
please edit the file here https://github.com/Dolibarr/dolibarr/edit/develop/htdocs/core/js/lib_head.js.php and submit a pull request, and mention this number #28334 in the commit message
