### ISSUE TITLE
BUG : product/stats/commande false when canceled orders

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2834]
It would be a great move forward to verify the stats of sold and ordered products.
When an order is canceled the total qty of product goes in the stat and is not substracted

![image](https://cloud.githubusercontent.com/assets/3694135/7648266/612851ee-fae1-11e4-9afb-2168c6863e18.png)

More than that, and i can open a Feature Request to display also total qty shipped or waiting to be shipped...

**Comment by marcosgdf** [comment]
This looks OK for me. That page is meant to show how many times was referenced that product, not actually "consumed". This is not the same as a stock page.
