### ISSUE TITLE
sales order to p.o.

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#28347]
### Bug

By creating a purchase order from a sales order, even if the purchase prices are correctly entered, the purchase order reflects the sales prices.

### Environment Version

19.0.0

### Environment OS

Linux

### Environment Web server

Litespeed

### Environment PHP

8.2

### Expected and actual behavior

the purchase order should show the purchase prices for that specific supplier, as entered in the product sheet

**Comment by Akuket** [comment]
Seems to be the same problem as the issue #28962 ?
