### ISSUE TITLE
Bug:  impossible to add IBAN CODE in a bank account in Dolibarrbt

### ISSUE THREAD

**Issue by clubdes** [Dolibarr/dolibarr#28363]
my version of Dolibarr : 14 0 5

problem : impossible to add IBAN CODE
Can you tell me how to add an IBAN code to a Dolibarr bank account
regards
![pb dolibarr IBAN](https://github.com/Dolibarr/dolibarr/assets/160932171/c5d8cfc2-0027-4bde-8b23-89c9f848b975)

**Comment by Daviid-P** [comment]
Is it not right under?

![image](https://github.com/Dolibarr/dolibarr/assets/7734808/fcdc4609-6303-42dd-8f46-a3f1228f007e)


Also, if you're on 14.0.5, you're about 4 or 5 versions old. if you can't see the same fields as me update at least to 16.0.3

**Comment by clubdes** [comment]
Quand je clique sur MODIFIER les données bancaires n'apparaissent pas ( voir copie écran)
![pb dolibarr IBAN2](https://github.com/Dolibarr/dolibarr/assets/160932171/61fd58b7-2481-4a29-a39f-832d4a9d5149)

**Comment by Daviid-P** [comment]
Then I can only suggest you upgrade Dolibarr versions. 14.0.5 is pretty old.

**Comment by clubdes** [comment]
je viens d'installer la version 18.0.5 sur Dolibarr et le problème du code IBAN a été traité
Merci pour votre aide
cordialement
Gérard
