### ISSUE TITLE
Impossible to add an IBAN CODE to a account bank on dolibarr

### ISSUE THREAD

**Issue by clubdes** [Dolibarr/dolibarr#28366]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
how to add the IBAN code to a bank account in dolibarr

## Environment
- **Version**: 14.0.5
- **OS**: windows
- **Web server**: Apache
- **PHP**: litespeed 8.0.30
- **Database**: MySQL or MariaDB 10.6.17-MariaDB
- **URL(s)**: /compta/bank/card.php?action=edit&token=8f3a3246d954e695e9fe335a07b70a5c&id=4

## Expected and actual behavior
it is not a bug but an help

![pb dolibarr IBAN](https://github.com/Dolibarr/dolibarr/assets/160932171/e3435e5c-fcdb-4dc7-a5d2-17e9571919be)

**Comment by Daviid-P** [comment]
Hi, did my previous answer not help with your issue?
https://github.com/Dolibarr/dolibarr/issues/28363

**Comment by ksar-ksar** [comment]
Close is #28363
