### ISSUE TITLE
Access a third party from the contact list

### ISSUE THREAD

**Issue by kuscoo** [Dolibarr/dolibarr#28431]
### Bug

In the contact list: /contact/list.php

If we display the Third Party column.

If you choose a prospect/client company: no mistake.
If you choose a company, neither prospect nor customer: error.

I noticed that each time, we are redirected to a link:
/comm/card.php?socid=12345

There is no error when using the following link:
/societe/card.php?socid=12345

So, if the company is not a customer, the link must be /societe/card.php

### Environment Version

18/19

### Environment PHP

8.2

### Environment URL(s)

/contact/list.php

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/16688970/a0f7a8a8-d6bd-41ef-94a3-79781139cef4)

**Comment by sonikf** [comment]
Hi @kuscoo 
I can confirm that the bug exists but at the same time I can't figure out your use case.
What is the point of having a third party that is not customer, prospect or vendor?

**Comment by kuscoo** [comment]
Thanks @eldy !
To answer you, @sonikf :
We can also use Third Parties and Contacts as an address book with our partners or other institutions which do not necessarily have a financial link with our structure.
