### ISSUE TITLE
Wrong SQL table called

### ISSUE THREAD

**Issue by ahaedv** [Dolibarr/dolibarr#2843]
The upgrade script from 3.7.0 changed the field llx_categorie_societe.fk_societe to llx_categorie_societe.fk_soc. categorie.class.php tries to insert or delete fk_societe. Columnname and tablename differ.
Solution
Added  if ($type=='societe') $column_name='soc';  in categorie.class.php line 493 and 598.

hope this helpes
b.r.

**Comment by marcosgdf** [comment]
Column name **MUST** be the same in all tables because of the "merge thirds" function so conditionals are not a choice.

I'll take a look at this.
