### ISSUE TITLE
Clotûre expédition impossible

### ISSUE THREAD

**Issue by fanhtech** [Dolibarr/dolibarr#28464]
### Bug

Bonjour,
Je ne parviens pas à clôturer les expéditions clients. Même en cliquant sur le bouton <<Clôturer>>, l'expédition reste au statut <<Validée>>. Mais la commande est marquée <<Livrée>>

### Environment Version

19.0

### Environment OS

Linux Debian

### Environment Web server

Apache

### Attached files

![Screenshot_20240227_154819](https://github.com/Dolibarr/dolibarr/assets/94901405/a9ce5996-1812-4e60-b5f9-171492366871)
![Screenshot_20240227_155022](https://github.com/Dolibarr/dolibarr/assets/94901405/a5bbfcb8-4015-407c-9e35-d5d8498996ff)

**Comment by LOLO91STGLC** [comment]
Bonjour Nous avons le même problème quand je clique sur cloturer il ne se passe rien.
Du coup compliqué de voir les colis livrés ou pas
merci et bonne journée

**Comment by comaiteseb** [comment]
Bonjour avez vous mis à jour votre dolibarr.
Il y a deux semaines le problème a été corrigé avec cette PR https://github.com/Dolibarr/dolibarr/pull/28174
Si ce correctif n'est pas suffisant pour votre problème merci de fournir plus de détails.

**Comment by fanhtech** [comment]
Merci @comaiteseb
