### ISSUE TITLE
Customer series numbering for invoices does not work as advertised

### ISSUE THREAD

**Issue by swbraun** [Dolibarr/dolibarr#2847]
I want to have document numbers with the customer number plus separate counters per customer, e.g.:
customer: 1234
first invoice: INV12340001
second invoice: INV12340002

customer: 2345
first invoice: INV23450001
second invoice: INV23450002
etc.

I hoped the mask {cccc0000} would do the trick, but when I entered "INV{cccc0000}" I got a "ErrorBadMask" error.
I found out that it "works" when I add a "global" counter: "INV{cccc0000}{000}"
But the resulting numbers are useless and not what I wanted:
customer: 1234
first invoice: INV12340001001
second invoice: INV12340002002

customer: 2345
first invoice: INV23450001003
second invoice: INV23450002004
etc.

Checking the code in "htdocs/core/lib/functions2.lib.php" I found out that you always need the "global" counter, but with a customer counter available this should not be required and should be considered a bug.

As a quick and dirty hack, I changed the code in the functions "get_next_value" and "check_value":

``` php
    // Extract value for mask counter, mask raz and mask offset
$hasCounter=true;
if (preg_match('/\{(0+)([@\+][0-9\-\+\=]+)?([@\+][0-9\-\+\=]+)?\}/i',$mask,$reg))
{
    $masktri=$reg[1].(! empty($reg[2])?$reg[2]:'').(! empty($reg[3])?$reg[3]:'');
    $maskcounter=$reg[1];
}
else
{
    $masktri='00000';
    $maskcounter='00000';
    $hasCounter=false;
}
    $maskraz=-1;
    $maskoffset=0;
    $resetEveryMonth=false;
    if (dol_strlen($maskcounter) < 3 && empty($conf->global->MAIN_COUNTER_WITH_LESS_3_DIGITS)) return 'CounterMustHaveMoreThan3Digits';
```

And after the code block for "// Extract value for third party mask counter":

``` php
if (! $hasCounter && ($maskrefclient_maskcounter == ''))
{
    return 'ErrorBadMask';
}
```

I haven't checked it for any side effects, but my tests all looked fine.
It would be nice if you could fix this in a similar way, at least so that the result is the same as described above.

**Comment by accett** [comment]
Have you tried INV{cccc}{0000}

?

2015-05-19 10:34 GMT-05:00 swbraun notifications@github.com:

> I want to have document numbers with the customer number plus separate
> counters per customer, e.g.:
> customer: 1234
> first invoice: INV12340001
> second invoice: INV12340002
> 
> customer: 2345
> first invoice: INV23450001
> second invoice: INV23450002
> etc.
> 
> I hoped the mask {cccc0000} would do the trick, but when I entered
> "INV{cccc0000}" I got a "ErrorBadMask" error.
> I found out that it "works" when I add a "global" counter:
> "INV{cccc0000}{000}"
> But the resulting numbers are useless and not what I wanted:
> customer: 1234
> first invoice: INV12340001001
> second invoice: INV12340002002
> 
> customer: 2345
> first invoice: INV23450001003
> second invoice: INV23450002004
> etc.
> 
> Checking the code in "htdocs/core/lib/functions2.lib.php" I found out that
> you always need the "global" counter, but with a customer counter available
> this should not be required and should be considered a bug.
> 
> As a quick and dirty hack, I changed the code in the functions
> "get_next_value" and "check_value":
> 
> ```
> // Extract value for mask counter, mask raz and mask offsetif (preg_match('/\{(0+)([@\+][0-9\-\+\=]+)?([@\+][0-9\-\+\=]+)?\}/i',$mask,$reg)){    $masktri=$reg[1].(! empty($reg[2])?$reg[2]:'').(! empty($reg[3])?$reg[3]:'');    $maskcounter=$reg[1];}else{    $masktri='00000';    $maskcounter='00000';}    $maskraz=-1;    $maskoffset=0;    $resetEveryMonth=false;    if (dol_strlen($maskcounter) < 3 && empty($conf->global->MAIN_COUNTER_WITH_LESS_3_DIGITS)) return 'CounterMustHaveMoreThan3Digits';
> ```
> 
> And after the code block for "// Extract value for third party mask
> counter":
> 
> if (! $hasCounter && ($maskrefclient_maskcounter == '')){    return 'ErrorBadMask';}
> 
> I haven't checked it for any side effects, but my tests all looked fine.
> It would be nice if you could fix this in a similar way, at least so that
> the result is the same as described above.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/issues/2847.

## 

Gracias por no enviar cadenas.
Ing. Víctor Ortiz Pérez
AcceTT - Soluciones Computacionales
Mártires 28 de Agosto #134 esq. Ruiz Cortines
Col. Ferrer Guardia Xalapa, Veracruz CP 91020
Tel. (228) 840 3284
WA 228 840 3284
victor@accett.com.mx
www.accett.com.mx

**Comment by swbraun** [comment]
Sure I did, this was actually my first try.
But as you can also see on my example above, the {0000} part works as a "global" counter, and not per customer.
To clarify things:
when I use INV{cccc}{0000} and create 3 new invoices with different customers, I get this result:
INV12340001
INV23450002
INV34560003
but I need this:
INV12340001
INV23450001
INV34560001

**Comment by accett** [comment]
ooh... sorry, now I understand.

2015-05-19 16:23 GMT-05:00 swbraun notifications@github.com:

> Sure I did, this was actually my first try.
> But as you can also see on my example above, the {0000} part works as a
> "global" counter, and not per customer.
> To clarify things:
> when I use INV{cccc}{0000} and create 3 new invoices with different
> customers, I get this result:
> INV12340001
> INV23450002
> INV34560003
> but I need this:
> INV12340001
> INV23450001
> INV34560001
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/issues/2847#issuecomment-103670496.

## 

Gracias por no enviar cadenas.
Ing. Víctor Ortiz Pérez
AcceTT - Soluciones Computacionales
Mártires 28 de Agosto #134 esq. Ruiz Cortines
Col. Ferrer Guardia Xalapa, Veracruz CP 91020
Tel. (228) 840 3284
WA 228 840 3284
victor@accett.com.mx
www.accett.com.mx

**Comment by swbraun** [comment]
@rdoursenaud just to understand, why you consider this a feature request and not a bug:
The mask {cccc0000} is offered in the tooltip as a valid mask, right?
For what numbering scheme would using this mask - in your opinion - make any sense?
Some examples would be helpful, thanks!

**Comment by rdoursenaud** [comment]
@swbraun Sorry, I misinterpreted the feature and didn't check what was the tooltip wording.
Of course if a feature does not behave as advertised, it's a bug ;)

Could you tell us what Dolibarr version you've been using or you know are affected?

**Comment by swbraun** [comment]
Don't worry, this happens ;-)
I use version 3.7.0 but I also checked here on github and the source code in "htdocs/core/lib/functions2.lib.php" (at least for these functions) seems still to be the same.

**Comment by rdoursenaud** [comment]
I just had a closer look and it seems it never ever worked the way it's advertised.
Pull request welcome!

**Comment by swbraun** [comment]
OK, but I'm not a developer, so I don't know if my solution is the best, it just works for me ;)
I'll send a pull request as soon as I figure out how...
