### ISSUE TITLE
PHP Warning:  Undefined variable $facture in /fourn/facture/paiement.php on line 840

### ISSUE THREAD

**Issue by PsyCrow-code** [Dolibarr/dolibarr#28485]
### Bug

This warning occur when apply a payment for a vendor invoice

### Environment Version

19.0

### Environment OS

Linux CentOS

### Environment Web server

Apache

### Environment PHP

8.1

### Environment Database

MariaDB

### Environment URL(s)

/fourn/facture/paiement.php

### Expected and actual behavior

Expect do not generate a php warning

### Steps to reproduce the behavior

On a vendor invoice, enter payment, full fill the form and press Pay button

**Comment by sonikf** [comment]
Works for me in v19.0.0 PHP 7.4, 8.0, 8.1, 8.2 
Can't replicate error

**Comment by PsyCrow-code** [comment]
On line:
print $form->formconfirm($_SERVER['PHP_SELF'].'?facid='.$facture->id.'&socid='.$facture->socid.'&type='.$facture->type, $langs->trans('PayedSuppliersPayments'), $text, 'confirm_paiement', $formquestion, $preselectedchoice);

almost at the endo of the file.

The object $facture is not defined and/or assigned any where on this file so php generate the warning

I heva not found where is $facture created or assigned... Do you know?

**Comment by sonikf** [comment]
Can you try changing $facture with $object to see if it works cause somehow it works for me as is and can't reproduce error

**Comment by PsyCrow-code** [comment]
$object works !

**Comment by sonikf** [comment]
Nice!
