### ISSUE TITLE
External user product menu not available

### ISSUE THREAD

**Issue by N3miroff** [Dolibarr/dolibarr#28494]
### Bug

After setting external user account and permissions for product, unfortunately user does not have access to menu and products well.

### Environment Version

19.0.0

### Environment OS

Ubuntu 23.10

### Environment PHP

php 8.2

### Environment Database

postgresql

**Comment by JonBendtsen** [comment]
which permissions have you set?

**Comment by N3miroff** [comment]
Hello, all permissions for product were set (create product, edit/delete...)
Tested with supplier quote, and works correctly.
regards

**Comment by sonikf** [comment]
Hi @N3miroff 
When entering the user permissions tab the following info is displayed

"Note, only the following modules are available to external users (**irrespective of the permissions of such users**) and only if permissions are granted:
Users & Groups, Members, Third Parties, Invoices, Sales Orders, Vendors, Projects or Leads, Events/Agenda, Resources, Tags/Categories, Vendor Commercial Proposals, Receptions, Shipments, Interventions, Contracts/Subscriptions, Unalterable Archives"

No mention of products, so this is not a bug.

**Comment by N3miroff** [comment]
Hello @sonikf,
Thanks for this comment, this looks right, I'll check in another way how to reach access product and create product for external users.
Regards
