### ISSUE TITLE
Upgrade from 18 to 19: DB_ERROR_SYNTAX

### ISSUE THREAD

**Issue by Extarys** [Dolibarr/dolibarr#28529]
### Bug

Cannot upgrade from 18 to 19, SQL migration error. Not sure how to fux or what happened.

### Environment Version

19.0.5

### Environment OS

Linux

### Expected and actual behavior

I expected the upgrade to be flawless

### Steps to reproduce the behavior

Upgrade from 17 to 18 and then 18 to 19

```
Error DB_ERROR_SYNTAX (Req 98): ALTER TABLE llx_expensereport DROP INDEX idx_expensereport_fk_refuse, ADD INDEX idx_expensereport_fk_refuse(fk_user_refuse);
ERROR: 42601: syntax error at or near "INDEX" LINE 1: DROP INDEX idx_expensereport_fk_refuse, ADD INDEX idx_expens... ^ LOCATION: scanner_yyerror, scan.l:1176
```

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/11581433/9841dcba-4a3c-4347-82b6-8c81be3f5e2d)

**Comment by frederic34** [comment]
I see you are using postgresql ?
can you try this https://github.com/Dolibarr/dolibarr/pull/28538

**Comment by Extarys** [comment]
Thanks for your reply.

> can you try this https://github.com/Dolibarr/dolibarr/pull/28538

SQL Error [42704]: ERROR: type "idx_expensereport_fk_refuse" does not exist

I'm running postgresql version 14. 

I did find a similar index: 
![image](https://github.com/Dolibarr/dolibarr/assets/11581433/83de2386-55ba-4d9d-8265-56406603778e)
 But I wanted to confirm it wasn't already created.

**Comment by frederic34** [comment]
it's in relation with https://github.com/Dolibarr/dolibarr/pull/26614

**Comment by frederic34** [comment]
i think it's to replace the first which is duplicate and keep the second

![image](https://github.com/Dolibarr/dolibarr/assets/3624836/e45b962f-f810-4e0c-9a2e-85e4167fb09e)

**Comment by hregis** [comment]
@Extarys @frederic34 fixed with this PR https://github.com/Dolibarr/dolibarr/pull/28542

**Comment by Vaadasch** [comment]
Hi, @Extarys 
To be close, then ?

**Comment by Extarys** [comment]
Well, I wasn't sure how to apply the fix, so I didn't :joy: but the instance seems to be working without error for now.

**Comment by Vaadasch** [comment]
You tried to update to 19.0.0.
In a more generic consideration, first major versions are often missing some things. X.0.0 need to be used carefully 

19.0.1 has been released. The first minor version after a major release often fixes little bugs like this.
Try to update to 19.0.1, see if you still have the problem.
That being said, keep doing backup before upgrade ! :-)

**Comment by Vaadasch** [comment]
You tried to update to 19.0.0.
In a more generic consideration, first major versions are often missing some things. X.0.0 need to be used carefully.

My previous comment (deleted) was in the case you've stayed in v18.
So in order to fix your situation, you should connect to your database (with PHPMyAdmin or cli) and execute the following commands : 

`DROP INDEX idx_expensereport_fk_refuse ON llx_expensereport;`
PGSQL doesn't need to have specified the table it seems, so maybe this will work better : 
`DROP INDEX idx_expensereport_fk_refuse;`

And create the new index with the new name : 
`ALTER TABLE llx_expensereport ADD INDEX idx_expensereport_fk_user_refuse(fk_user_refuse);`

**Comment by Extarys** [comment]
I'm using docker and I didn't really notice I pulled the new image when it happened, I simply needed access to dolibarr, that is on me :)
The upgrade to 19.0.1 was without hiccups. I'll eventually run your command. :smile: I recently had to wipe my HDD, so a lot needs to be done. :joy: 

I'll close this now and save the command. Thank you for the commands!

**Comment by artisad** [comment]
Hey @Extarys, 
Contact me on the following address, I would love to exchange with you if you want to pursue further tests with dolibarr :smile:

```
emailtemplate="email@domain.fr"
echo $emailtemplate | sed 's#[a-z]*\(.\)[[:alpha:]]*\(\.[rf]*\)#no-reply\1adalon\2#
```
