### ISSUE TITLE
Gestion de la longueur des données dans le champs QRCode

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#28541]
### Bug

![image](https://github.com/Dolibarr/dolibarr/assets/3288514/34ae5c04-536e-4488-a836-4aa8831be646)

**Comment by frederic34** [comment]
another case
![image](https://github.com/Dolibarr/dolibarr/assets/3624836/f4fbe729-57fa-418c-9e18-567d53bf1027)
