### ISSUE TITLE
Wrong translation key in localtax report page

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2855]
Version: 3.7.0
URL: http://dolibarr.local/compta/localtax/quadri_detail.php?leftmenu=tax_vat&localTaxType=2

![captura de pantalla 2015-05-20 a las 10 59 30](https://cloud.githubusercontent.com/assets/168744/7722323/4ce4f28a-fedf-11e4-872e-d45fad836628.png)

**Comment by rdoursenaud** [comment]
Bad concatenation in
htdocs/compta/localtax/clients.php
line 112
htdocs/compta/localtax/quadri_detail.php
line 132 and 164

Introduced in 747b6a9f by @simnandez

**Comment by marcosgdf** [comment]
@rdoursenaud Thanks for the hints!
