### ISSUE TITLE
Stock module allows making product transfer between warehouses even if no stock available

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2858]
Version: 3.7.0
Reported by a dolibarr.es forum user at http://www.dolibarr.es/foro/viewtopic.php?f=18&t=2241

Steps to reproduce:
1. Create product A
2. Create warehouse A and B
3. Make a stock transfer of product A between warehouse A and B of 5 units
4. See that warehouse A is -5 and B is +5

Negative stock should not ever happen.

**Comment by accett** [comment]
I think that this needs a global variable to decide that, cause the
negative in the stock are very comun. Sometimes the sale happen before the
buy, then the product stock temporaly is negative. But if we have a
variable in the stock module config name ALLOW_NEGATIVE_STOCK or something
like that check the flag in the procedure of move stock.

**Comment by marcosgdf** [comment]
It is not the same thing. One thing is to make a sell (we could argue if negative stock should be allowed but this is not the topic), and another one is to make an unexisting stock transfer.

**Comment by accett** [comment]
I understand. But if the stock is less qty than the move needs (perhaps is
for a invoice of supplier that hasn't sent yet) maybe is necessary allow
the move with negatives qty.

I still think that can be managed with a global variable that config in the
settings of the module stock. Maybe I'm wrong.

Something like ALLOW_MOVES_NEGATIVE

:)

It is not the same thing. One thing is to make a sell (we could argue if
negative stock should be allowed but this is not the topic), and another
one is to make an unexisting stock transfer.

**Comment by marcosgdf** [comment]
No. It is still not the same thing. You can correct the stock or make a
stock transfer. You cannot move unexisting items.

**Comment by BebZ** [comment]
in his case : for a invoice of supplier that hasn't sent yet
because he manages stock with invoicies, not with shipments
it could happen to be a negative qty, no ?

**Comment by fappels** [comment]
I agree with Marcos, stock transfer is physical transfer of goods. If you do have 5 existing items in A but a count of 0 in Dolibarr, you should first correct stock in A to 5 (after you check your stock, inspect the goods and all warehouses) and then tranfer 5 from A to B. Dolibarr should show a message on transfer that results in negative stockcount.

**Comment by marcosgdf** [comment]
If he manages stock with invoices and not with shipments then he is not using Dolibarr properly.

**Comment by atm-maxime** [comment]
FIXED IN #5301
