### ISSUE TITLE
Unable to add customer orderline when product units enabled

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#2859]
Version 3.8.0

Objectline_create stops at units

![unitsissue 1](https://cloud.githubusercontent.com/assets/4573808/7723115/6e8c1d8a-fee6-11e4-8807-d517539deda5.png)

**Comment by BebZ** [comment]
I confirm :)

**Comment by marcosgdf** [comment]
Is it a fresh install? The database changed after the PR

**Comment by fappels** [comment]
It's a rebase from yesterday, and I always run the migration script when I replace the htdocs folder on my test-server.
Just started xdebug, on line 2849 of htdocs/core/class/html.form.class.php there is 'if ($selected == $res[0])' but $res is not an array

**Comment by rdoursenaud** [comment]
Only triggered if unit support (PRODUCT_USE_UNITS) is enabled in the products and services module.
