### ISSUE TITLE
COMMERCIAL PROPOSAL NUMBERING  \

### ISSUE THREAD

**Issue by terhoy** [Dolibarr/dolibarr#28608]
### Bug

Greetings to the team that provides us end user with a great product, thank you!

Commercial proposal numbering and online signature.

Reproduced in both 18.0.4 in production and 19.0.0 in test, I made a discover regarding Commercial proposal numbering and online signature.
In configuration of the “COMMERCIAL PROPOSALS MODULE SETUP», I have added a numbering mask containing a space: Proposal {000+22}. This works fine in all other modules and situations, except from tab, Commercial proposal and Link for online signature.
In line 77 of the code of /core/lib/signature.lib.php, there is a str_replace. To me it looks like it removes space/blank in the proposal ref. When this blank/space is removed, the online signature form fails in displaying all the information.

### Dolibarr Version

19.0 develop

### Environment PHP

 8.1.27

### Environment Database

MySQL or MariaDB 5.7.44-cll-lve

### Steps to reproduce the behavior and expected behavior

If the mask of Commercial proposal numbering contains a blank/white space, then the online signature form does not show the name of the customer and amount.

### Attached files

[Setup COMMERCIAL PROPOSAL NUMBERING MODELS.pdf](https://github.com/Dolibarr/dolibarr/files/14474153/Setup.COMMERCIAL.PROPOSAL.NUMBERING.MODELS.pdf)

**Comment by JonBendtsen** [comment]
there seem to be only 3 lines in all of Dolibarr that has a this str_replace

```
core/lib/signature.lib.php:	$ref = str_replace(' ', '', $ref);
core/lib/payments.lib.php:	$ref = str_replace(' ', '', $ref);
recruitment/lib/recruitment_recruitmentjobposition.lib.php:	$ref = str_replace(' ', '', $ref);
```

Have you tried removing it in your own dolibarr and test if it has any negative consequences?

**Comment by terhoy** [comment]
I have tried to remove it in my own Dolibarr. It has so far no negative consequences, except that online signing works as it should.

**Comment by JonBendtsen** [comment]
do you plan on using online payments as well?

**Comment by JonBendtsen** [comment]
when you remove that, which character is the blank space replaced with?

**Comment by terhoy** [comment]
> do you plan on using online payments as well?
> 
> 

Not at the moment. Consider the online signature to be an interesting possibility

**Comment by JonBendtsen** [comment]
> > do you plan on using online payments as well?
> 
> Not at the moment. Consider the online signature to be an interesting possibility

The reason I ask is because that same str_replace is also used in core/lib/payments.lib.php

I've looked in all 3 files, the one you mention, core/lib/payments.lib.php and recruitment/lib/recruitment_recruitmentjobposition.lib.php.

Based on your test I think it can also be removed in the payment thing, so I think you should edit the 2 files and submit a Merge request.

I don't think it should be done in this file recruitment/lib/recruitment_recruitmentjobposition.lib.php

**Comment by JonBendtsen** [comment]
When you submit your pull request, make sure to mention #28608

**Comment by terhoy** [comment]
It's actually the opposite. Before I commented out line 77, online signing was not working because the numbering mask contained a space. When the code on line 77 is "gone" it works as expected. The space will be included in the URL and online signing will work.

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Jon Bendtsen ***@***.***>
Sendt: Sunday, March 3, 2024 10:48:56 PM
Til: Dolibarr/dolibarr ***@***.***>
Kopi: terhoy ***@***.***>; Author ***@***.***>
Emne: Re: [Dolibarr/dolibarr] COMMERCIAL PROPOSAL NUMBERING \ (Issue #28608)


when you remove that, which character is the blank space replaced with?

**Comment by JonBendtsen** [comment]
I kinda expected that the space would be a + 

`Returns a string in which all non-alphanumeric characters except -_. have been replaced with a percent (%) sign followed by two hex digits and spaces encoded as plus (+) signs.`

https://www.php.net/manual/en/function.urlencode.php#:~:text=It%20is%20encoded%20the%20same,encoded%20as%20plus%20(%2B)%20signs.

But if it works it is great :-)

**Comment by terhoy** [comment]
> When you submit your pull request, make sure to mention #28608

I've never done it before but I'll give it a try. 😄

**Comment by JonBendtsen** [comment]
> > When you submit your pull request, make sure to mention #28608
> 
> I've never done it before but I'll give it a try. 😄

great :-)

If there is only 1 file you can edit it here
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/lib/signature.lib.php

but since there are 2 files 
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/lib/payments.lib.php

you probably want to click the ▼ next to the pencil icon and edit both files before submitting the merge request.

**Comment by JonBendtsen** [comment]
@terhoy  I don't think it worked, please try making the pull request again
