### ISSUE TITLE
Undefined array key 0

### ISSUE THREAD

**Issue by JeromeBARBOTIN** [Dolibarr/dolibarr#28622]
### Bug

Undefined array key 0 in htdocs/core/class/CMailFile.class.php on line 317

### Dolibarr Version

19.0

### Environment PHP

8.1

### Environment Database

MySQL

### Steps to reproduce the behavior and expected behavior

When the user wants to send a document by an e-mail (bill, proposal...).

**Comment by hansemschnokeloch** [comment]
Fixed with https://github.com/Dolibarr/dolibarr/commit/05ed5dbe6a8fca09c7edc7aaf91a00ae7fa4a522

@eldy  Issue can be closed
