### ISSUE TITLE
Invoices Draft & Open broken. No pagination possible

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#28634]
### Bug

Hi,

Invoices (Bills) listing is broken for Drafts and Open Invoices. "connected with Contact" is preselected to current User.
To see invoices you have to reset the filter.
Pagination does not work as expected, Changing Limit to 100 helps, but not all invoices are shown.
Search by Customer or Invoice Number doesnt work anymore
 

### Dolibarr Version

20.0.0-alpha develop from today

### Environment PHP

8.1,27

### Environment Database

10.5.23-MariaDB-0+deb11u1

### Steps to reproduce the behavior and expected behavior

Klick on Invoices

**Comment by mwelters** [comment]
maybe related to #28635

**Comment by mwelters** [comment]
Things changed a little after the last commits, but it is more or less unusable:

If I click /compta/facture/list.php?leftmenu=customers_bills it shows only canceled and paid invoices:
![image](https://github.com/Dolibarr/dolibarr/assets/11374733/d641794e-d4df-42dc-acef-92c7ef55b7f3)

If I press the X "Clear Filters" it shows all types of invoices (leftout Partner in list)
![image](https://github.com/Dolibarr/dolibarr/assets/11374733/27795794-a43a-455a-8b82-8756b11e76ae)

But if I want to see the second page of the list it switches back to the behaviour with only showing paid and canceled invoices.
![image](https://github.com/Dolibarr/dolibarr/assets/11374733/37698660-4e87-427a-9565-b41f4d7c9032)

Again X "Clear Filter" pressed and tried to search for Postcode 40472  (exists)
![image](https://github.com/Dolibarr/dolibarr/assets/11374733/0772e853-5e37-4c8e-91ce-13181e5c455a)

**Comment by fappels** [comment]
Best wait for deep testing until #28512 is merged, quite some features are broken in actual V20 alpha.

**Comment by mwelters** [comment]
> Best wait for deep testing until #28512 is merged, quite some features are broken in actual V20 alpha.

Thank you for this hint. Then I'll wait !

**Comment by mwelters** [comment]
> Best wait for deep testing until #28512 is merged, quite some features are broken in actual V20 alpha.

I reverted back to 
git checkout aa37b755e06745752250e55bb8ee51169142dd41

this was the commit before the GETPOST -> GETPOSTINT changes
Fix: GETPOST(...,'int') to GETPOSTINT(...) (#28448) 

now working and writing invoices is possible again.

**Comment by mwelters** [comment]
Listing is fixed with one of the last commits
