### ISSUE TITLE
Services lists only products

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#28635]
### Bug

in Services the type defaults to "products"
Selecting Services in Offers and Invoices is impossible. Search for ARticle to add with the p.ref shows no result from services

### Dolibarr Version

20.0.0-alpha develop from today

### Environment PHP

8.1.27

### Environment Database

10.5.23-MariaDB-0+deb11u1

### Steps to reproduce the behavior and expected behavior

Click on Products/Services

**Comment by JonBendtsen** [comment]
pictures might have been nice

**Comment by hregis** [comment]
@mwelters @eldy the problem is in line 140 of list.php !

`$search_type == '0'` before this test, and never `$search_type == '' `

```
if ((string) $type == '1') {
	$contextpage = 'servicelist';
	if ($search_type == '') {
		$search_type = '1';
	}
}
```

**Comment by hregis** [comment]
try with this fix https://github.com/Dolibarr/dolibarr/pull/28643

**Comment by hregis** [comment]
@eldy why GETPOST("search_type", "int") is not the same result of GETPOSTINT("search_type") ??

**Comment by mwelters** [comment]
> try with this fix #28643

yes, helps in this particular case.
But I think better fix the behavior of GETPOSTINT cause it is causing problems also in Propal and Invoices (as far as I discovered)

**Comment by mwelters** [comment]
Problem is solved with one of the last commits to develop

**Comment by mwelters** [comment]
Problem is solved with one of the last commits to develop

@eldy why GETPOST("search_type", "int") is not the same result of GETPOSTINT("search_type") ??

**Comment by mwelters** [comment]
Checked out develop today 4. April 2024 and the problem is still there.

In an Invoice, you cannot insert a Service, only a product. Listing Services and Products is fine.
![image](https://github.com/Dolibarr/dolibarr/assets/11374733/67190c23-ebc6-46e7-8acc-691b2ddbbdfd)

The Invoice draft was created with an earlier pull, just to demonstrate the existing Service "ABB" is not selectable for an Invoice

**Comment by mwelters** [comment]
The problem appeared again a few commits ago...
Tested with commit c5751a970a1
