### ISSUE TITLE
warning for missing ChromePhp.php

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2863]
in 3.7.0 when activating syslog I get warning message
Warning: include_once(ChromePhp.php): failed to open stream: No such file or directory in htdocs/core/modules/syslog/mod_syslog_chromephp.php  on line 58

**Comment by rdoursenaud** [comment]
Looks like SYSLOG_CHROMEPHP_INCLUDEPATH is not properly set at install time.
It should point to `htdocs/includes/chromephp` by default.

**Comment by rdoursenaud** [comment]
I fixed it in e6cde6a3cc1142f5b0d7be473350a5e48b6d4e90
Awaiting merge of it in PR #3352
