### ISSUE TITLE
FEATURE REQUEST : Add option for choosing PMP instead of best buying Price

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2864]
Dolibarr always chooses the latest(or the best ?) buying price recorder in the product fournisseur price's tab 
I think it should be checked, what is chosen : latest, best, or pmp price. 
There should be an option for the default price chose.

What do you think ?

In my opinion, it should be the pmp chosen by default, and this pmp should be calculated, accordingly to what is in STOCK. 
If I bought product A 3 times : 
in january : 10 pieces at 10€  pmp is 10€ 
in february : 10 pieces at 8€  pmp is  9€ 
in march : 10 pieces at 7€  pmp is 7.3333€

WHEN stock is full ! 

BUT if I sell 20 pieces of productA on end of february 
in march "new" pmp should be 7€, not 7,33 ? (because 10 Pieces + 10 pieces bought in january/february would be sold)

or maybe what i try to calculate is not pmp... but another method for calculating FIFO value of stock... If I mistake, I will go back to school, reading my logistics lessons :) !

**Comment by rdoursenaud** [comment]
The price you get in the supplier price is the minimum price at which you can buy the product (according to the buying prices you set under it). It has nothing to do with stock!

As for the PMP calculations, I believe they are good:
PMP = (Qty × PMP + NewQty × Price) ÷ QtyTotal
<=>
(20 × 9 + 10 × 7) ÷ 30 = 8,33333

So your PMP is ok if it's 8,33 (not 7, not 7,33?).

**Comment by peartreegil** [comment]
PMP in that case is definitely 8,33...
The problem is, when you create an offer (or invoice), the PMP is not used to evaluate the margin.... but the supplier price indicated in the item proposed or invoiced.... 
It should be possible to choose what data to use for margin evaluation... don't you think?

**Comment by BebZ** [comment]
ok, more simple ... and tell me if I am wrong to think like that 

I have 10 products in stock bought at 1€ each, my product supplier's price recoreded is 1€ 
i sell it 2€ : FINE i have a good margin :)
Now i buy 20 products at 0,9€ each and i sell them 2€ 
i have an even better margin, but the price recorded in product supplier's price is the same, so i got the same margin, but the price i recorded in the order is 0,9€ each, so PMP is affected by this, no ?
tell me if I'm wrong PMP is calculated with the products ventilated to stock multiplied by it's buying price on supplier order ?
I think most of us can't change the supplier's price recorded in the product card... as suppliers often offer discounts... and sometimes complicated discounts !

but on a supplier order, or supplier invoice, the price should reflect this specific discount, so the buying price there is a good price "normally".

There is no tool to compare all the "encoded" prices of supplier's prices product card 
VS 
buying price set up on the supplier order 
VS
invoiced priced by the supplier ?

...my 2000 cents...

**Comment by rdoursenaud** [comment]
Once set, the weighted average price (PMP in french) does not change in any circumstances but new purchases.
You may want to manage your purchase prices with other methods like FIFO or FILO but calculations and data needed are way more complex. I don't think we have the tooling to do this right now in Dolibarr.
As for having a parameter to set the purchase price to use for margin calculations, I'm all for it!
You should indeed be allowed to choose between best buying price or current PMP.
Anything else sounds way too complex for now though…

**Comment by BebZ** [comment]
eldy introduced it ? 
https://github.com/Dolibarr/dolibarr/commit/1485ead215145c5afda1edce4f88ac16e928c6ba

![Uploading image.png…]()

**Comment by rdoursenaud** [comment]
@BebZ Can you test and report if it fits your use case?

**Comment by peartreegil** [comment]
I am not sure to understand.....

Cordialement,

Gilles POIRIER
Net Logic
gilles.poirier@netlogic.frmailto:gilles.poirier@netlogic.fr
+33(0)1 43 05 92 37tel:+33(0)1%2043%2005%2092%2037
+33(0)7 61 01 10 61tel:+33(0)7%2061%2001%2010%2061

Le 8 juil. 2015 à 19:48, Raphaël Doursenaud <notifications@github.com<mailto:notifications@github.com>> a écrit :

@BebZhttps://github.com/BebZ Can you test and report if it fits your use case?

**Comment by eldy** [comment]
Option to use pmp instead of best buying price for margin calculation were already introduced into 3.7, but code and setup was not clear. With 3.8, you should find option easily and it should work. I hope.

**Comment by eldy** [comment]
Closed. Should be ok with 3.8 if i correctly understood the request.

**Comment by peartreegil** [comment]
Thanks for the answer!

Gilles POIRIER
Net Logic
gilles.poirier@netlogic.frmailto:gilles.poirier@netlogic.fr
+33(0)1 43 05 92 37tel:+33(0)1%2043%2005%2092%2037
+33(0)7 61 01 10 61tel:+33(0)7%2061%2001%2010%2061

Le 12 sept. 2015 à 16:03, Laurent Destailleur <notifications@github.com<mailto:notifications@github.com>> a écrit :

Closed. Should be ok with 3.8 if i correctly understood the request.

**Comment by peartreegil** [comment]
Hi,

I am testing that new option... looks great thanks !

---

De : Laurent Destailleur [notifications@github.com]
Date d'envoi : jeudi 23 juillet 2015 22:01
À : Dolibarr/dolibarr
Cc : Gilles Poirier
Objet : Re: [dolibarr] FEATURE REQUEST : Add option for choosing PMP instead of best buying Price (#2864)

Option to use pmp instead of best buying price for margin calculation were already introduced into 3.7, but code and setup was not clear. With 3.8, you should find option easily and it should work. I hope.
