### ISSUE TITLE
Shipments - cannot be closed

### ISSUE THREAD

**Issue by michalhana99** [Dolibarr/dolibarr#28658]
### Bug

When a shipment is created, the shipment cannot be closed and the products are not removed from the warehouse.

The close button is still active

![image](https://github.com/Dolibarr/dolibarr/assets/60580110/ff1602f2-6120-4d3c-9c12-faeba33a86f7)

### Dolibarr Version

19.0.0

### Steps to reproduce the behavior and expected behavior

Set Deduction from Stock to "Decrease actual stock when shipment is closed"

Then create an order from the stock product

Then create the shipment and press the "close" button

**Comment by JanneAnnefors** [comment]
Having the same problem after updating to 19.0.0

**Comment by andsmedeiros** [comment]
I can also confirm this happens on version 19.0.0. Clicking the close button does nothing and the shipment stays the same. 

I am a new admin so cannot check whether this happened in older versions.

**Comment by JanneAnnefors** [comment]
I changed the setting in the stock module from 'Decrease real stocks when shipping is set to closed' to 'Decrease real stocks on shipping validation' so now the stock decreases when I validate the delivery instead. But I think before 19.0.0 it was not possible to select that setting if you had enabled module Lot/Serial.

**Comment by AnggaRifandi** [comment]
I also have the same issue since upgrading to 19.0.0.

Temporary solutions is by changing the options to "Decrease real stocks on shipping validation", but with this option the icon color not changing into green.

**Comment by le-reparateur** [comment]
Hi
Tested to : same problem

Bug solved in current file v19 on git !
