### ISSUE TITLE
Use templates

### ISSUE THREAD

**Issue by sebj54** [Dolibarr/dolibarr#2868]
Hi everyone,

I represent a French web agency and we are using Dolibarr to deploy an ERP for our customers. They are very satisfied by the functionality but the main problem of Dolibarr is the user experience. 

I saw an issue dealing with accessibility, but I would go further in thinking: Dolibarr needs to separate template from the Controller. Actually there is no MVC in Dolibarr, view and controller are mixed and view is generated with print functions, making HTML comprehension difficult.

So we thought we would have to separate at least views from controllers, removes all `print` functions by variables sent from controllers to the templates and code in a separate template files. We first thought to do this in a fork of Dolibarr, but we would lost updates by doing this.

So I am here to ask if there is anything planned or if we could participate to the development of this feature (or even doing it completely). If we do it, have we a chance to see our changes merged in Dolibarr?

Thanks in advance for your help!

**Comment by BebZ** [comment]
@dolibarr owners ;)
for a better future Dolibarr 4.0 or even 3.9 ?
How much time do you think it will take, and how many devs of Dolibarr can manage/understand the MVC model ?

**Comment by sebj54** [comment]
I don't have actually any ideas of the time it will take. I just know it isn't impossible :)

Everyone can understand such a system, especially if its implementation is built with ease of use in mind. I only thought of VC model. It will already be a big improvement.

I imagine something like that:

#### Controller

``` php
$template = new Template('third_parties/index'); // Initiate template
$template->var = 'something'; // Adds data to the template
```

#### template file

``` php
<div class="something"><?php echo $this->var; ?></div>
```

#### Template Class

``` php
class Template
{
    private $data = array();

    public function __get($var)
    {
        if (isset($this->data[$var]))
        {
            return $this->data[$var];
        }

        return '';
    }

    public function __set($var, $value)
    {
        $this->vars[$var] = $value;
    }
}
```

The Template class will find the template in a specific folder. There will be several folders, one for the default templates and theme folders. If a template doesn't exist in a theme folder, system will display the default one.
The Template class will also use overloading (http://php.net/manual/en/language.oop5.overloading.php) to store data. Using this way, we can add any variable and use it in the template file, even if it doesn't exist in the class, because overloading will return an empty string.

With a few documentation, it won't be too hard to understand. I think it will also be possible for developers to code like they do today, Template class will only include a file and store variables in order to use them in a template file.

**Comment by accett** [comment]
Could be in Cake/PHP?

Its a very good framework that use MVC.

**Comment by sebj54** [comment]
If a framework has to be used, all the core should be rewritten in order to take profit of all the advantages of the framework. I don't think that's a good idea to use a framework just for one feature.

**Comment by sebj54** [comment]
Just coming to up the issue, I wanted to know if we have a chance to see this feature added to future versions of Dolibarr if we develop it. Thanks :)

**Comment by BebZ** [comment]
Discussion with devs may take a long time as they are all really busy...
@eldy knows the best, and can start the discussion ?

**Comment by sebj54** [comment]
Can I hope to get an answer for this simple question actually?
My company would like to contribute to Dolibarr with this feature, but we can't do it if we can't update Dolibarr after having developped it.

Thanks for your answer.

**Comment by BebZ** [comment]
I think this subject has to be debated by developpers inside a DevCamp, not on the Git Platform...
Who will take in charge the MVC "adaptation" ? 
I don't think the foundation will accept, nor the developpers here that are used to the framework.
BUT i'm not a dev, i'm not a foundation member. Just a 2cents giver.

**Comment by sebj54** [comment]
Thanks for your devotion anyway 👍 
I am ready to discuss this feature with developpers but I don't know where to contact them except here. 

Like I said in the previous comment, my web agency is ready to develop this feature and then make a pull request. We would just like to know if we have a chance to see this feature merged. 

The idea here is to make module files more understandable by separating backend from frontend.

**Comment by aspangaro** [comment]
Please, send an email to laurent@destailleur.fr to propose this  functionality. 

Laurent will say yes or no...

Good luck

**Comment by sebj54** [comment]
Thanks for the email, I'll contact him!

**Comment by altairis-tof** [comment]
hello, i am very interested by this discussion; i would be happy to know about the answer you received.

**Comment by cfoellmann** [comment]
This is how most of the UI works in the current version (v9/10), right?
This is issue is very old and still open.

Is the governance still like one man says yes or no?

**Comment by nelero** [comment]
Hi,
is there a chance to state on this subject?
I know Dolibarr has history and is known to be stable since it's creation some long times ago.
The work created by developers and founders is amazing and thanks for that project and the time spent for this.
But a better modern code organization like MVC could be a great improve in maintenance and evolution. Quite sure it could be done with small steps, in a middle term vision without employing cake/Php or doing such a big revolution in code with all that implies.
With a step on a better modularization, we could help Dolibarr evolve to some nice projects or modules.
But it must be done smartly and smoothly and needs some time and devs to focus on the same direction.
Is it possible?
