### ISSUE TITLE
__ONLINEPAYMENTLINK_MEMBER__ doesn't work

### ISSUE THREAD

**Issue by daraelmin** [Dolibarr/dolibarr#28680]
### Bug

In mass mailing the __ONLINEPAYMENTLINK_MEMBER__ give a wrong link witch hors nower

### Dolibarr Version

18.0

**Comment by JonBendtsen** [comment]
How do you mass email your members?

Which kind of online payment provider are you using?

**Comment by daraelmin** [comment]
I use the mailing tool ans Stripe.

It worked on 14.0, or doesn't anymore on v18.0.5

I've found that it didn't work anymore in v17 
See Here : 
https://www.dolibarr.fr/forum/t/v17-0-bug-dans-le-lien-de-paiement-fiche-adherent/42708/4?u=daraelmin

**Comment by daraelmin** [comment]
I'm not sur but it seems that the ref ID in the link that os sens to the members is the user ID ref of the user witch click on Sending the mail.

And the __SECUREKEYPAYMENT_MEMBER__ send is not the same either

Maybe the $this->source_id is not the right variable to call

**Comment by daraelmin** [comment]
I wanted to select a few members who hold positions in our association to remind them that they must renew their membership to keep them. I had therefore selected the emails from the "user" line to go faster, but what interested me was their membership status.

In short, when selecting recipients from the "user" line, the ID refers to the user and not the member. So we don't have the right link. 

It's not very clear, but it seems complicated to change this element.

Closed
