### ISSUE TITLE
Stripe Webhook live key incorrect

### ISSUE THREAD

**Issue by BimwerxNZ** [Dolibarr/dolibarr#28726]
### Bug

Stripe Webhook live key incorrect, it defaults to 'https://mywebsite.com/crm/crm/htdocs/public/stripe/ipn.php' in my case instead of 'https://mywebsite.com/crm/htdocs/public/stripe/ipn.php'. I seem to be unable to edit this value.

Same happens with Virtual Business Card for some reason.

Other features seem to work fine.

### Dolibarr Version

19.0.0

### Environment PHP

8.1.27

### Environment Database

MySQL or MariaDB 5.7.44

**Comment by ksar-ksar** [comment]
Hello,

What is your dolibarr address configured in setup ?

**Comment by BimwerxNZ** [comment]
I reinstalled Dolibarr, that seemed to fix the issue. I did something wrong with setup and changed the local folder on installation.
