### ISSUE TITLE
Ticket update function sets fk_statut to NULL

### ISSUE THREAD

**Issue by carmelchas** [Dolibarr/dolibarr#28721]
### Bug

The default value for fk_statut is set to null when it appears it ought to be set to zero(0).

Ticket::update function:
                $sql .= " fk_statut=".(isset($this->fk_statut) ? $this->fk_statut : "null").",";

Ticket::create function:
                $sql .= " ".(!isset($this->fk_statut) ? '0' : "'".$this->db->escape($this->fk_statut)."'").",";

### Dolibarr Version

18.0

### Environment PHP

PHP 7.x

### Environment Database

10.11.3-MariaDB-1 - Debian 12

### Steps to reproduce the behavior and expected behavior

Perform an update to a ticket that was just created using the "$object".

For example, I have an extra field named "latestactivity".

            $object->array_options['options_latestactivity'] = $this->db->idate(dol_now());
            $object->update($user, 1);  // update with no trigger.

**Comment by carmelchas** [comment]
This bug causes the ticket card not to display status button options.

**Comment by carmelchas** [comment]
<img width="1088" alt="image" src="https://github.com/Dolibarr/dolibarr/assets/445543/fe64f35a-a94b-45ff-a7e7-e4fde2cee3c9">

**Comment by JonBendtsen** [comment]
> ### Bug
> The default value for fk_statut is set to null when it appears it ought to be set to zero(0).
> 
> Ticket::update function: $sql .= " fk_statut=".(isset($this->fk_statut) ? $this->fk_statut : "null").",";
> 
> Ticket::create function: $sql .= " ".(!isset($this->fk_statut) ? '0' : "'".$this->db->escape($this->fk_statut)."'").",";


If you edit the file here https://github.com/dolibarr/dolibarr/blob/develop/htdocs/ticket/class/ticket.class.php#L1074 using the pencil icon and change it to your code, and include #28721 in the commit message, and you create a Pull Request also including #28721, then the Dolibarr developers can take a look at it and possibly include it.

**Comment by carmelchas** [comment]
Thank you.  I created the following pull request based on your instructions.


https://github.com/Dolibarr/dolibarr/pull/28731


Sincerely,

Charles A Beasley

**Comment by carmelchas** [comment]
Pull request created.

https://github.com/Dolibarr/dolibarr/pull/28731
