### ISSUE TITLE
Wrong price when using comma as decimal

### ISSUE THREAD

**Issue by jjkoa** [Dolibarr/dolibarr#28830]
### Bug

Using Spanish locale (decimal separator is a comma), when adding a product to an order, if the price has 3 decimals, it removes the decimal.

### Dolibarr Version

18.0.4

### Environment PHP

7.2

### Environment Database

MariaDB 11.3.2

### Steps to reproduce the behavior and expected behavior

It should just replace the point with a comma in the unit price.

Test with spanish locale, with a 3 decimals product.

Examples: 
- Add a free product, in unit price use: 0.225 -> It changes it to 225.00.
- Add an existing product, with a unit price of 0.225 -> This example works fine, value is set to 0,225
- Edit an existing product, with a unit price of 0.225 -> it changes the value to 225.00.

**Comment by ksar-ksar** [comment]
Hello,

if Spanish locale, decimal separator is a comma, why do you enter point and not Comma.
If you do the same on Excel for example, it will treat it as String and not number.

**Comment by jjkoa** [comment]
Hi. Excel does treat it as numeric and convert the point to a comma. The numeric keypad has a point, so it would be very annoying to use the numeric keypad and having to type a comma for every decimal. 

This was how older versions of dolibarr worked. I have just test it in a dolibarr 5.0.6, and it works fine, it converts the 0.225 to 0,225.

I've seen this issue that is kind of similar: https://github.com/Dolibarr/dolibarr/issues/22535 which seems to fix one of the examples, but It does not work with the other ones.

**Comment by ksar-ksar** [comment]
And what is your local setting thousands char ?

**Comment by jjkoa** [comment]
a point: '.'  same settings as in the mentioned issue.

**Comment by ksar-ksar** [comment]
So you understand why if you put a . Dolibarr think that's thousand

**Comment by jjkoa** [comment]
I don't, it does not make any practical sense, no localized software would behave like that, and it was working fine in previous versions. But as you please, I close.
