### ISSUE TITLE
BUG: Modul - does not match expected name syntax

### ISSUE THREAD

**Issue by zunami** [Dolibarr/dolibarr#28848]
### Bug

i want to install a module via a zip file and it leads to a syntax error

### Dolibarr Version

19.0

### Environment PHP

8.2.7

### Environment Database

MariaDB 11.3.2-MariaDB-1:11.3.2+maria~ubu2204

### Steps to reproduce the behavior and expected behavior

I would like to add the cdav module via the "Deploy/install external app/module". 

It then triggers this message which makes no sense
The name of the module package (cdav-2.24.zip) does not match expected name syntax: module_*-x.y*.zip

I use a docker container from
https://github.com/tuxgasy/docker-dolibarr

and would like to add the module cdav
https://github.com/Befox/cdav

### Attached files

![2024-03-14 16_29_49-cdav](https://github.com/Dolibarr/dolibarr/assets/4697822/f42082eb-86b7-4f1b-bff8-a88a8141ba1b)

**Comment by ksar-ksar** [comment]
Hello,

This is not a Dolibarr bug. 
Rename the ZIP to `module_cdav-2.2.4.zip`

**Comment by zunami** [comment]
oooohhhhhhh
that's the structure and i thought "cdav" = "module".

you're right, that's not how the syntax message came out. nevertheless, this module still works like this

thanks
