### ISSUE TITLE
[Qual] Use parameterized SQL (aka prepared statements or parameter binding)

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2885]
Prepared statements are less error prone, provide better injection prevention and have better performance.

That's why our database library should provide a facility to use them and all Dolibarr request should progressively switch to using them.

All the supported database backends provide prepared statements so we should still be able to keep our custom abstraction layer.

Here's a breakdown of the work to be done:
- [ ] Database interface
- [ ] DoliDb abstract class
- [ ] MySQL(i) class
- [ ] PgSQL class
- [ ] SQLite classes
- [ ] MSSQL class
- [ ] Wiki documentation
- [ ] Deprecate direct queries
- [ ] Update all core queries

**Comment by marcosgdf** [comment]
I'd really love to see PDO used in Dolibarr. We could mix PDO advantages with ours.

We should also check Doctrine DBAL (based on PDO) http://www.doctrine-project.org/projects/dbal.html or Zend_Db

**Comment by IonAgorria** [comment]
Also some guidelines for dealing with different data (String escaping, number checks, date/time conversions, etc) storing/reading between SQL/PHP would be nice.

**Comment by rdoursenaud** [comment]
@IonAgorria These already exist: http://wiki.dolibarr.org/index.php/Language_and_development_rules#SQL_rules

But feel free to improve them ;)

@marcosgdf Using doctrine DBAL seems reasonable to me. Now we need to convince @eldy that it's a good thing to use a community supported project rather than rolling our own!

**Comment by eldy** [comment]
History prooved that using an external "supported project" instead of a working layer, often provide more problems than solving.
Does the doctrine DBAL provide also abstraction on error messages (one error message code, for exemple "index already exists" whatever is the database ?)
Is it able to manage multi level transactions as we do with the counter into begin/commit methods ?
We must first be sure to have answer of this question to yes. More question will come after.

**Comment by marcosgdf** [comment]
Yes it does. Also, with DBAL there is no need to count transactions, it already handles the counter internally.

```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO llx_user (login) VALUES(?)' with params ["a"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a-1' for key 'uk_user_login' in /var/www/dolibarr/untitled/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 66
```

I have to note that DBAL is more cost expensive than PDO but it has some features that allow writing code faster, so we should consider if using more server resources or using more human resources is prioritary.
