### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2888]
With the design changes in 3.7.0 and the upcoming 3.8.0, I think screenshots should be updated to reflect the more modern look and feel.
- [ ] `doc/images` [folder](../tree/develop/doc/images)
- [ ] [Readme](../blob/develop/README.md) (could point to the doc/images folder instead of the website)
- [ ] [Website(s)](http://dolibarr.org)

**Comment by eldy** [comment]
Done with 4.0
