### ISSUE TITLE
Prelevement prefix table in card.php

### ISSUE THREAD

**Issue by xbloq** [Dolibarr/dolibarr#28938]
### Bug

My tables prefix isn't llx. I have a error with  htdocs/compta/prelevement/card.ph in line 463 

$sql .= " FROM llx_prelevement_lignes as pl";

I think should be 

$sql .=" FROM ".MAIN_DB_PREFIX."prelevement_lignes as pl";

### Dolibarr Version

19.0.0

**Comment by JonBendtsen** [comment]
if you edit this file using the pencil icon https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/prelevement/card.php#L463

Then you write this number #28938 in both your commit message and your pull request.

Then in a few days hopefully the project maintainer has time to look at it and it should get fixed for everyone just be approving that pull request you made.
