### ISSUE TITLE
Button enabled disabled

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr#28945]
### Bug

Hi actualy find out that we have some bugs wen editing modules configurations many button to enabled or disabled fonction are freez
Like in the PDF module
![image](https://github.com/Dolibarr/dolibarr/assets/26550824/6bb802c4-8ed3-4860-84f8-6d9fc2b65863)

### Dolibarr Version

19.0, 19.0.1

### Environment PHP

8.1

### Environment Database

10.6.16-MariaDB-cll-lve

### Steps to reproduce the behavior and expected behavior

Done a full backup of our production enviroment en donne update from 18.5 to 19.0.1

**Comment by sonikf** [comment]
Hi @DATUC 
Everything works fine for me with same settings, so i can not confirm this bug.
Please check file and folder permissions inside htdocs.

**Comment by hregis** [comment]
@DATUC maybe a jquery error, have you externals modules ?

**Comment by DATUC** [comment]
tks @ll
@hregis you are right it was the template i'm using that cause the issue i just disable it and enable it back to find it out
