### ISSUE TITLE
Ticket email not compliant with RFC 5322

### ISSUE THREAD

**Issue by BenjaminFlr** [Dolibarr/dolibarr#28959]
### Bug

When a ticket is created from the collector, two `References:` headers are added and emails are rejected by some providers.

### Dolibarr Version

18 and following

### Steps to reproduce the behavior and expected behavior

When a ticket is created from the collector, two `References:` headers are added.
One related to the Message-ID (already available in a previous header), and another related to the email from which it has been created.

It looks like it's linked to this line:
https://github.com/Dolibarr/dolibarr/blame/c527cb27fb8db1c6e30e50e9dcb61083471137ef/htdocs/ticket/class/ticket.class.php#L3037

Regarding [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322) (page 20), it should appear only once.
Currently, some mail providers reject the emails with many References headers, where some others accept it without any problem.

I think that we should remove this header, or see if we can use another?

@eldy : while you worked on this part, what do you think? I'm not really sure regarding the consequences of changing it.

**Comment by eldy** [comment]
Hi
I have pushed a fix into v20 already.
And lucas is working to enhance it by saving the references into database for v20.The fix in v20 was cherry picked into v19. I have just cherrypicked it into v18 too. Can you test it ?

**Comment by BenjaminFlr** [comment]
The test, on my side, has to be made on a 18.0.x version.
Could you please let me know which commit ID I have to cherry pick in order to test it?

**Comment by BenjaminFlr** [comment]
Ok I found it and cherry-picked the commit. Looks good to me, we can close this issue.

Just in case for other readers: https://github.com/Dolibarr/dolibarr/commit/b705dd80948d9a18c8973b769545157dd6302dd1
