### ISSUE TITLE
FactureFourn does not fetch `last_main_doc`, unlike Facture

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#28958]
### Bug

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/fourn/class/fournisseur.facture.class.php
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/facture/class/facture.class.php

Self explanatory, CTRL+F last_main_doc on both classes.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/29020
