### ISSUE TITLE
When an order is invoiced, its status does not change to “Billed” in the list of orders

### ISSUE THREAD

**Issue by developmentOYR** [Dolibarr/dolibarr#28963]
### Bug

To check the error we carry out this process:

1) We create an order and its status is correctly shown as “not billed”

![image](https://github.com/Dolibarr/dolibarr/assets/120027058/540a94ac-a37c-4b38-bee6-8f49d0b20eb3)

2) We proceed to create an invoice from that order. To do this, I open the order and create the invoice.

![image](https://github.com/Dolibarr/dolibarr/assets/120027058/89d6cb6e-df1c-47b5-8130-a669966b3251)

I validate the invoice and, as you can see, the invoice is linked to the order.

![image](https://github.com/Dolibarr/dolibarr/assets/120027058/4f0f773d-b2ea-4884-bb0e-37375ce75f39)

Finally I go to the order list and as you can see the invoice thas was validated is not shown as (Billed) as it should.

![image](https://github.com/Dolibarr/dolibarr/assets/120027058/23da6008-b331-47cd-8393-f6946b884ca0)

To fix this error, the way I found to fix it is:

In the file  “htdocs/fourn/facture/card.php” i add this after line  231.

We insert the following code after line 238

 “elseif($acion==’confirm_valid’ && $confirm==’yes’ && $usercanvalidate){“

This coniditional applies when the user has validaled and confirmed an order.

and within that conditional there is another conditional:

 “if(!$error){“ 

which tells us that no error has ocurred.

Then it calls the validate function and then there is a conditional in which we indicate if there has been an error.

If there is and error , we show it. If not, then this is where I have added the additional lines of code that correct the error.

$object→fechObjectLinked();

I load all items associated with that invoice.

I check that there is an element of type order supplier associated with that invoice:

if(array_key_exists(“order_supplier”,$object→linkedObjects)){

$linkedObjectBlock=$object→linkedObjects[“order_supplier”];

I check that there only one order associated with an invoice because when there are several orders associated with an invoice, it is done correctly.

if(count($linkedObjectBlock)==1){

In case that there is only one order associated with an invoice, I go through all the elements associated with the invoice of type “order_supplier” and I classify that order using the "ClassifyBilled" method.

foreach($linkedObjectBlock as $key =>$objectlink){

$objectlink->classifyBilled($user)
}
} 
}

![image](https://github.com/Dolibarr/dolibarr/assets/120027058/cec680d0-62d2-415a-b816-97860610a174)

### Dolibarr Version

19.0

### Environment PHP

8.1

**Comment by sonikf** [comment]
Ηι @developmentOYR 
I cannot confirm this bug, works as expected for me in v. 19.0.0 and PHP 8.1

**Comment by JonBendtsen** [comment]
you are talking about supplier orders, right?

**Comment by JonBendtsen** [comment]
If you edit this file by using the pencil icon then you can make a Merge Request with your changes.

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/fourn/facture/card.php

When you do that, please write a reasonable commit and Merge Request message and in both cases please include #28963



I would also kindly ask you to check if the comparable file here for regular orders has the same issue.
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/facture/card.php

**Comment by developmentOYR** [comment]
@JonBendtsen  Yes, I mean supplier orders.

**Comment by developmentOYR** [comment]
@JonBendtsen 

The file for regular orders has the same problem. 

In addition, it also has the problem that if you perform the billing action in bulk, the field does not change to billed either. Something that did happen in supplier orders.


![image](https://github.com/Dolibarr/dolibarr/assets/120027058/efb98505-88c8-4f6a-b53e-58e9fdf841ec)

**Comment by JonBendtsen** [comment]
> @JonBendtsen
> 
> The file for regular orders has the same problem.
> 
> In addition, it also has the problem that if you perform the billing action in bulk, the field does not change to billed either. Something that did happen in supplier orders.


I hope you are going to fix that too.

**Comment by hregis** [comment]
@JonBendtsen check the "workflow" module!

**Comment by JonBendtsen** [comment]
> @JonBendtsen check the "workflow" module!

@hregis  for what?

**Comment by hregis** [comment]
<img width="1668" alt="Capture d’écran 2024-03-24 à 13 24 24" src="https://github.com/Dolibarr/dolibarr/assets/454387/f910084d-43c0-4672-821d-fd463c789c36">

**Comment by developmentOYR** [comment]
@hregis 
Thank you very much for the information. Now it works correctly. If you want you can close the request
