### ISSUE TITLE
Converting Customer Order to Supplier Order Uses Selling Price Instead of Buying Price

### ISSUE THREAD

**Issue by Steph501** [Dolibarr/dolibarr#28962]
### Bug

Problem Description

When converting a customer order into a supplier order, the product prices are incorrectly taken from the selling prices instead of the buying prices.

Expected Behavior
The prices of the products in the supplier order should be their buying prices.

### Dolibarr Version

19

### Environment PHP

8

### Steps to reproduce the behavior and expected behavior

- Navigate to a customer order.
- Click on "Create" then "Create purchase order".
- Notice that the product prices in the supplier order correspond to the selling prices, not the buying prices.

**Comment by ksar-ksar** [comment]
Hello,

Can you write in English please ?

**Comment by sonikf** [comment]
Hi @Steph501 
I can confirm this bug
