### ISSUE TITLE
Can't create events

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2899]
Error message: Failed to insert event : Unknown column 'fk_user_done' in 'field list'

fk_user_done has been removed in e6e263d13ffc9e24d8e888b7c59b0397e9d51119 but code is still referring to it in htdocs/core/boxes/box_actions.php and htdocs/comm/action/class/actioncomm.class.php

Also the migration script does not remove the field.

Has this been removed by error or is this a work in progress?

Ping @eldy.

**Comment by rdoursenaud** [comment]
Also blocks creating "normal" calendar events.

**Comment by rdoursenaud** [comment]
Of course, this only manifests on a fresh 3.8 install since the field isn't removed in the upgrade script.

Since I didn't receive any reply, I'll consider this an error and reintroduce the missing field in an upcoming PR!

**Comment by eldy** [comment]
There is still a hidden option AGENDA_ENABLE_DONEBY to keep feature/compatibility with version that were using the "done user". I am not sure it is used and we must keep it. Let's see at net version.
