### ISSUE TITLE
Very annoying problems with documents layout

### ISSUE THREAD

**Issue by Alysko** [Dolibarr/dolibarr#29]
1/ When choosing a contact for invoice - (or other document), If he has no contact information (address), company details are not included although this is the most common case.

2/ There are page breaks faaar before the page is filled.

3/ The page numbering is buggy (1/{nb})

Since at least version 2.6.

**Comment by hregis** [comment]
Hi,
you must use the bugtracker on the Dolibarr project in doliforge.org

https://doliforge.org/projects/dolibarr/
https://doliforge.org/tracker/index.php?group_id=144
