### ISSUE TITLE
Bug with security GETPOST

### ISSUE THREAD

**Issue by zahwyrix** [Dolibarr/dolibarr#29004]
### Bug

I discovered by chance that one of my codes was working when it wasn't supposed to, the magic of computing :)
I have a JS code that calls an Ajax page with a "type" variable that is equal to 0, 1 or 2.

In my php page I have :
$type = GETPOST('type', 'alpha');

This was an oversight on my part, I should have put :
$type = GETPOST('type', 'int');

But I found that the code still worked with GETPOST('type', 'alpha') !
Isn't alpha supposed to be just letters?

### Dolibarr Version

19.0.1

### Environment PHP

7.4

### Environment Database

mysql

### Steps to reproduce the behavior and expected behavior

Transmit an integer with the alpha filter to the GETPOST method

**Comment by JonBendtsen** [comment]
which URL are you talking about?

**Comment by sonikf** [comment]
Hi @zephyriony 
https://github.com/Dolibarr/dolibarr/blob/fd1322c095fab3eeb2bb44587f431a55a88b3e79/htdocs/core/lib/functions.lib.php#L674

**Comment by Daviid-P** [comment]
https://github.com/Dolibarr/dolibarr/blob/fd1322c095fab3eeb2bb44587f431a55a88b3e79/htdocs/core/lib/functions.lib.php#L676-L676

https://github.com/Dolibarr/dolibarr/blob/fd1322c095fab3eeb2bb44587f431a55a88b3e79/htdocs/core/lib/functions.lib.php#L1111-L1126

I assume alphanohtml means Alphanumeric, no html, so maybe it's just like aZ09 with spaces, commas and whatnot
