### ISSUE TITLE
Converting customer order to supplier order, customers payment terms are used instead of supplier terms 

### ISSUE THREAD

**Issue by SysUserR** [Dolibarr/dolibarr#29035]
### Bug

When converting a customer order to a supplier order the payment terms are incorrect. The payment terms of the customer are used insted of the payment terms of the supplier.

### Dolibarr Version

19.0.1 running on Windows11

### Environment PHP

7.3.33

### Environment Database

mariadb 10.6.5

### Steps to reproduce the behavior and expected behavior

- Navigate to customer order
- Create a supplier order out of the customer order
- After the supplier order is generated you can see the wrong payment terms.

**Comment by Akuket** [comment]
Seems to be the same problem as the issue #28962 ?
