### ISSUE TITLE
Purchase Order Back to list produces DB_ERROR_NOSUCHFIELD

### ISSUE THREAD

**Issue by playcock** [Dolibarr/dolibarr#29031]
### Bug

I am receiving DB_ERROR_NOSUCHFIELD Unknown column 'Array' in 'where clause' when I click the link "Back to list" on Purchase Orders.

### Dolibarr Version

18.06

### Environment PHP

7.2.24

### Environment Database

0.11.3-MariaDB-1 - Debian 12

### Steps to reproduce the behavior and expected behavior

On the Purchase Orders list page: fourn/commande/list.php
I will set a single status or multiple statuses to filter the list of Purchase Orders in my website,
I will get updated results and then open the card for one of the Purchase Orders.
On the Purchase Order card, I will then click on "Back to list" link and get taken: fourn/commande/list.php?restore_lastsearch_values=1
I then get an error reading:
```
Latest database access request error: SELECT s.rowid as socid, s.nom as name, s.name_alias as alias, s.town, s.zip, s.fk_pays, s.client, s.fournisseur, s.code_client, s.email, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, cf.rowid, cf.ref, cf.ref_supplier, cf.fk_statut, cf.billed, cf.total_ht, cf.total_tva, cf.total_ttc, cf.fk_user_author, cf.date_commande as date_commande, cf.date_livraison as date_livraison,cf.date_valid, cf.date_approve, cf.localtax1 as total_localtax1, cf.localtax2 as total_localtax2, cf.fk_multicurrency, cf.multicurrency_code, cf.multicurrency_tx, cf.multicurrency_total_ht, cf.multicurrency_total_tva, cf.multicurrency_total_ttc, cf.date_creation as date_creation, cf.tms as date_update, cf.note_public, cf.note_private, p.rowid as project_id, p.ref as project_ref, p.title as project_title, u.firstname, u.lastname, u.photo, u.login, u.email as user_email, u.statut as user_status, ef.signature_link as options_signature_link, ef.yardi_po_number as options_yardi_po_number, ef.tracking_number as options_tracking_number FROM llx_societe as s LEFT JOIN llx_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN llx_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN llx_c_departements as state on (state.rowid = s.fk_departement), llx_commande_fournisseur as cf LEFT JOIN llx_commande_fournisseur_extrafields as ef on (cf.rowid = ef.fk_object) LEFT JOIN llx_user as u ON cf.fk_user_author = u.rowid LEFT JOIN llx_projet as p ON p.rowid = cf.fk_projet WHERE cf.fk_soc = s.rowid AND cf.entity IN (1) AND cf.fk_statut IN (Array) AND s.fk_pays IN (11) ORDER BY cf.ref DESC LIMIT 26
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'Array' in 'where clause'
```

**Comment by JonBendtsen** [comment]
@playcock  Could you provide links from the page and the link of the "back to list".

Also some pictures would be nice too :-)

**Comment by playcock** [comment]
@JonBendtsen I'll do that.

**Comment by playcock** [comment]
@JonBendtsen 

1) On the list page: fourn/commande/list.php
![image](https://github.com/Dolibarr/dolibarr/assets/9416592/2d3ddf26-9af1-4a9c-9da5-279ed596f800)
2) I'll filter by status, like Validated.
![image](https://github.com/Dolibarr/dolibarr/assets/9416592/51463d40-0f54-4aab-b69d-1e7e61434a1f)
3) Open a PO: fourn/commande/card.php?id=937&save_lastsearch_values=1
![image](https://github.com/Dolibarr/dolibarr/assets/9416592/80ee18df-885d-44f3-b38c-4d8dd6b17243)
4) Clicked on "Back to list": fourn/commande/list.php?restore_lastsearch_values=1
5) Then I get the following: fourn/commande/list.php?restore_lastsearch_values=1
![image](https://github.com/Dolibarr/dolibarr/assets/9416592/329b1bb9-527c-4a24-9a61-c68321694844)

**Comment by playcock** [comment]
@carmelchas I tested your commit and the error message is no longer and the list page remembers the filters I had.

**Comment by JonBendtsen** [comment]
@playcock  Do the regular customer orders page have the same issue? or was it only purchase orders?

**Comment by playcock** [comment]
@JonBendtsen I tested sales orders and it does not have the same issue. 

Purchase Orders is one of the only, if not only, pages that has it built in  to select more than one status to filter on using the select2 dropdown.

@carmelchas has a commit I tested and the error message is no longer and the list page remembers the filters I had. htdocs/fourn/commande/list.php

**Comment by carmelchas** [comment]
https://github.com/Dolibarr/dolibarr/pull/29059

**Comment by carmelchas** [comment]
@JonBendtsen Is there a specific protocol for getting an expedited review on a pull request?

**Comment by JonBendtsen** [comment]
> @JonBendtsen Is there a specific protocol for getting an expedited review on a pull request?

My biggest commit took 3.5 days to get merged, and it might be the longest I ended up getting merged.

https://github.com/Dolibarr/dolibarr/pull/28823

I have another one that is still open, but it is also rejected as it is not the correct path I was taking to fix something. I'm waiting for Eldy to reply back with some comments about where I need to look for how to fix it the correct way.

Given that it is easter I think you should be a little more patient unless it is a security fix. Also, it doesn't matter much when it is merged in because it will take some time to get into the next release like 19.0.2 given that 19.0.1 was just release 2 weeks ago.

https://github.com/Dolibarr/dolibarr/tags
