### ISSUE TITLE
Credit/Debit records in 19.0.1 version

### ISSUE THREAD

**Issue by flgllc** [Dolibarr/dolibarr#29045]
### Bug

Hi all,
i have a new company that i am setting up to work with Dolibarr 19.0.1 and there is something strange i have noticed in the Double Accounting module. IT is not normal, at least as per my logic but i’d like to ask, just in case.
Now, the initial amount of the bank account should be 1000 EUR and i have enter it directly in the bank section and reconciled it. Now, the strange thing for me is then the record is being transferred to the Bank Journal and it is looks like this:
![Screenshot 2024-03-23 231334](https://github.com/Dolibarr/dolibarr/assets/164756701/613d2e74-d912-435c-b5a8-282b537c5673)

In my logic, the bank account here (512) should have amount in Credit section of the entry, and the Capital account (101) should be in Debit section. Instead the entry is reversed but at the same time the amount in the bank account is as it should be - 1000 EUR positive. Any suggestions? I could revers the posting manually but i want to see what are you suggesting here, because i am not that in to accounting, just yet.
Thanks!

### Dolibarr Version

19.0.1 

### Environment PHP

8.1.27

### Environment Database

10.6.12-MariaDB

**Comment by aspangaro** [comment]
Hello,

No, this is totally normal. When you pay the start-up capital, it is credited to your bank account. In accounting, not in relation to your bank statement, the direction will always be reversed. If your bank account is in credit, it will be in debit in accounting.
And when an account is in credit, we usually display a "-" (minus) to read it.

Have a nice day
