### ISSUE TITLE
Supplier invoices do not generate pdf

### ISSUE THREAD

**Issue by alihusseinc** [Dolibarr/dolibarr#29068]
### Bug

Good morning, can someone help me solve this error in the supplier's invoice, it won't let me generate the invoice in PDF and everything is enabled in the modules, in this area http://localhost/dolibarr/fourn/facture/card.php
![error](https://github.com/Dolibarr/dolibarr/assets/104669840/75e4385a-2dd6-4522-a6e0-51b363df90af)

![image](https://github.com/Dolibarr/dolibarr/assets/104669840/01fe0d5e-8a49-4e7b-832c-d29a6fdb8a1b)

### Dolibarr Version

19.0.1

**Comment by ksar-ksar** [comment]
Hello,

You are on the wrong module parameters.
The screenshot is for customer invoice, not supplier invoice.
![image](https://github.com/Dolibarr/dolibarr/assets/35605507/3f1f044c-03b6-4856-8780-56f51f7ab9aa)

![image](https://github.com/Dolibarr/dolibarr/assets/35605507/9973f743-07a5-4284-8345-37dbccc583c1)

**Comment by alihusseinc** [comment]
correct, thank you very much @ksar-ksar
