### ISSUE TITLE
Module builder : Error in the export model

### ISSUE THREAD

**Issue by kuscoo** [Dolibarr/dolibarr#29103]
### Bug

Tiny error.
In the builder module, suggestions are offered by default.
Just remove the comments for this to work.

Except for this line:
//$this->export_sql_end[$r] =' LEFT JOIN '.MAIN_DB_PREFIX.'competence_line as tl ON tl.fk_competence = t.rowid';

A "point" is missing before the "equal":
//$this->export_sql_end[$r] .=' LEFT JOIN '.MAIN_DB_PREFIX.'competence_line as tl ON tl.fk_competence = t.rowid';

The problem is the overwriting of part of the query, if we want to couple other tables.
Tiny error, but will improve the no-code module.

Thanks!

### Steps to reproduce the behavior and expected behavior

ourmodule**/core/modules/**modObject**.class.php**

**Comment by JonBendtsen** [comment]
@kuscoo  if you have tested in your own dolibarr installation and it works there then I'd suggest that you send in a merge request by editing this file using the pencil icon.
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/modulebuilder/template/core/modules/modMyModule.class.php#L402

Both when you commit and when you write the merge request text you should include #29103. Also please write a short meaning full text, not just `Update modMyModule.class.php`. Longer for the merge request.

**Comment by kuscoo** [comment]
First commit done!
The mechanics are not complex. I will try to find time to make further corrections. Thank you for the information and education!
