### ISSUE TITLE
Sort by email template fails with DB_ERROR_NOSUCHFIELD Unknown column 'type_templatetype_template' in 'order clause'

### ISSUE THREAD

**Issue by terhoy** [Dolibarr/dolibarr#29101]
### Bug

Hi team,

thank you for your outstanding efforts to make Dolibarr a great solution.

In setting up emails, displaying email templates and sorting by Type of template, Dolibarr returns an error: DB_ERROR_NOSUCHFIELD Unknown column 'type_templatetype_template' in 'order clause'

### Dolibarr Version

19.0.1

### Environment PHP

8.1.27

### Environment Database

	MySQL or MariaDB 5.7.44-cll-lve

### Steps to reproduce the behavior and expected behavior

Pick Home, Setup, Emails, Email templates. Click Type of template.

[Type of template](mails_templates.php?sortfield=type_templatetype_template,lang,position,label&sortorder=asc,asc,asc,asc&begin=&id=25&search_type_template=)

### Attached files

[Dolibarr.log](https://github.com/Dolibarr/dolibarr/files/14789032/Dolibarr.log)

**Comment by terhoy** [comment]
Posible solution: Edit mails_templates.php, line 1043. $sortfieldtouse.= 'type_template,lang,position,label'; by removing the key word "type_template".

**Comment by JonBendtsen** [comment]
Fix works for me too on PHP 8.2.7 Tuxgasy container image.

@terhoy  If you follow this link and edit the file using the pencil icon.
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/admin/mails_templates.php#L1044

In both the commit message - which should be meaningful, and in the merge request message please write #29101
