### ISSUE TITLE
API PUT call issue (product extra fields)

### ISSUE THREAD

**Issue by valtbern** [Dolibarr/dolibarr#29115]
### Bug

Unexpected behavior of PUT method upon updating product's extra fields

### Dolibarr Version

19.0.1

### Environment PHP

8.1.27

### Environment Database

MariaDB 10.6.17-MariaDB-cll-lve

### Steps to reproduce the behavior and expected behavior

Trying to call a product update through PUT method to update an extra field of the product:

1. Extrafield (checkbox) underlined: API must uncheck the box

![image](https://github.com/Dolibarr/dolibarr/assets/21037425/1875d81d-321c-48c3-b40d-cbd43c45230a)

2. API request body:

![image](https://github.com/Dolibarr/dolibarr/assets/21037425/ea436e65-20b3-492a-98c0-f7e5b7ac5c79)

3. After the call checkbox is unchecked which is right,
however, previously set values for extra fields are now gone.
NOTE: some of the extra fields didn't lose their values and it seems that those fields having _default value_ defined in extrafield settings don't lose the values, in fact, they **change** to default value from settings, regardless of what was set before or defined in API schema.

![image](https://github.com/Dolibarr/dolibarr/assets/21037425/d0341db0-3d4a-4468-9dbd-863b0b7fd67e)

Obviously, standard fields are not affected, they're not changing (unless defined in schema) or loosing the values.

**Comment by JonBendtsen** [comment]
1. what is the API url you use?  this one? `PUT /api/index.php/products/`
2. what if you first use `GET /api/index.php/products/`
3. modify the contents of `array_options` 
4. send the full array_options back with `PUT /api/index.php/products/`

Does that work?

**Comment by valtbern** [comment]
Hi @JonBendtsen,
Thank you for reaching our.
1. The URL is /api/index.php/products/{id}

Honestly, I already obtain the details of the product via GET and then, after certain operations in the middle, update the this single checkbox. 
I was thinking to overwrite all those extrafields at the end of my loop, however I find it really weird that update of any standard field through PUT wouldn't require the whole list of fields if just one of them needs to be updated (thanks god),
Whereas, extrafields, apparently, other than storing all original values of them prior to call PUT, and then repatching again at the end is the only way to keep their original values (apart from the ones I'd like to actually change).

Is that how this PUT method is supposed to function with the extrafields?

**Comment by JonBendtsen** [comment]
> however I find it really weird that update of any standard field through PUT wouldn't require the whole list of fields if just one of them needs to be updated (thanks god), Whereas, extrafields, apparently, other than storing all original values of them prior to call PUT, and then repatching again at the end is the only way to keep their original values (apart from the ones I'd like to actually change).
> 
> Is that how this PUT method is supposed to function with the extrafields?

I don't know, but I too find it strange that all extra fields are changed. 

Have you looked in this file https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/product/class/api_products.class.php and perhaps even followed it to different files to see what it actually does?

**Comment by JonBendtsen** [comment]
@valtbern  I think that this is the culprit

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/product/class/api_products.class.php#L372

```
		foreach ($request_data as $field => $value) {
			if ($field == 'id') {
				continue;
			}
			if ($field == 'stock_reel') {
				throw new RestException(400, 'Stock reel cannot be updated here. Use the /stockmovements endpoint instead');
			}
			if ($field === 'caller') {
				// Add a mention of caller so on trigger called after action, we can filter to avoid a loop if we try to sync back again with the caller
				$this->product->context['caller'] = $request_data['caller'];
				continue;
			}

			$this->product->$field = $value;
```

so when the `array_options` in the request_data is just the new field, then this last line 372 will just set it to what is in the request_data.

So if you wanted to merge the new changes into `array_options` there should be some code that did just that and only updated the lines from $request_data->array_options - or something like that.

**Comment by JonBendtsen** [comment]
`array_options` are not only used in products, perhaps there is already some code in the other API's that could be reused?

**Comment by JonBendtsen** [comment]
@valtbern yeah, here is a segment of code that will probably do exactly what you want

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/societe/class/api_contacts.class.php#L343

```
			if ($field == 'array_options' && is_array($value)) {
				foreach ($value as $index => $val) {
					$this->contact->array_options[$index] = $val;
				}
				continue;
			}
```

Can you try it in your Dolibarr installation? and if it does work then I suggest that you edit the file here using the pencil icon
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/product/class/api_products.class.php#L372

When you commit it, and also when you submit the merge request you need to include `#29115` and please write some meaning ful messages.


There are probably several other API files that could have the same issue and be in need of a fix.

**Comment by JonBendtsen** [comment]
Here's the tools and method I used to find that file and code

1. use find to find all api*class.php files
2. for all those files run a little script that checks for `public function put(` and for `array_options` - only files with both will be sent to output
3. for those output files, I run `grep -nE "public function|array_options"` and that allows me to quickly find a file where the `public function put(` does something with `array_options`

Then it's just open that file and see what it actually does with `array_options`

If there was none I would have looked at those api that had a `public function updateline(`, but there was one so I did not have to do that.

**Comment by JonBendtsen** [comment]
@valtbern  have you had the chance to test if my proposed change was working?

**Comment by valtbern** [comment]
Hi @JonBendtsen,
Thank you for detailed observation.
Carefully analysing the system behavior, I noticed that the logic for _extra fields_ works the way that it gets re-inserted upon any value change, regardless whether it happens on the UI or through the API means.

Upon update in UI, the values do not vanish due to different re-insertion class used.
Hereby, if the original _extra fields_ values are not supplied via API (apart from the ones we intend to change), they'll be lost on re-insertion.

For myself it's alright, no issues storing/reusing values until the moment I need to update something in extra fields, however, out of curiosity, what would happen if there are hundreds of extra fields for very specific business lines :)

**Comment by JonBendtsen** [comment]
> For myself it's alright, no issues storing/reusing values until the moment I need to update something in extra fields, however, out of curiosity, what would happen if there are hundreds of extra fields for very specific business lines :)

@valtbern I think that if one uses the current API to only change one field, then the rest will be gone :-(
