### ISSUE TITLE
When validating interventions you do not get a message about who will receive a notification just like you do when validating an order

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr#29117]
### Feature Request

When validating interventions you do not get a message about who will receive a notification just like you do when validating an order.

![no_information_about_who_gets_an_email_orders_has_this](https://github.com/Dolibarr/dolibarr/assets/2551481/8f063b2b-a3bd-41b8-93d7-04582fd1ccab)

### Use case

it is always nice to know what happens behind your back, especially when contact has intervention notifications enabled.

![thirdparty_has_intervention_notification_enabled](https://github.com/Dolibarr/dolibarr/assets/2551481/c7f85a4f-6b8d-464f-a307-fd4df89a7b78)

### Suggested implementation

copy code from order validation?

### Suggested steps

create thirdparty, create contact, on thirdparty notifications setup notification to contact.

create intervention, validate intervention

**Comment by W1W1-M** [comment]
This is working in v21. Which version are you using ?

**Comment by JonBendtsen** [comment]
> This is working in v21. Which version are you using ?

Back then it was probably some v18 on my production server which is today still 18.0.5 but it could have been a prior v18

it could also have been my development which is a v19, I can check it again later

**Comment by JonBendtsen** [comment]
works for me today in 18.0.5, let's close it
