### ISSUE TITLE
Bug: order card price_ttc not calculated in line

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#29125]
# Bug
[*Order card to edit line price_ttc not calculated with price_ht*]

## Environment
- **Version**: 19.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.3.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /commande/card.php?id=744

**Comment by bos4711** [comment]
Possibly duplicate of #29122
