### ISSUE TITLE
Problem with action BILL_SENTBYMAIL

### ISSUE THREAD

**Issue by PKeidel** [Dolibarr/dolibarr#2913]
We updated to 3.7.0 a few weeks ago. Since then there are no "INSERT INTO llx_actioncomm" in dolibarr.log shown and so we can't see at what date we send the bills.
It's the language item "InvoiceSentByEMail".

Which files do I have to edit to get it working again?

Thanks for an answer and the great tool dolibarr.

**Comment by rdoursenaud** [comment]
Can't reproduce. BILL_SENTBYMAIL is correctly triggered for me.

Are you sure that the automatic action is enabled in the calendar module?

**Comment by eldy** [comment]
Can you check into setup of module Agenda that the event has been selected to create automatic event into agenda ?

**Comment by eldy** [comment]
Closed, missing answer to progress.

**Comment by guillaume-uH57J9** [comment]
I noticed the same issue in Dolibarr 3.5.5. It's not clear why/when it stopped working. 

@rdoursenaud @eldy We are using the Compta/Facture module, not the Agenda module, thus the Agenda module is disabled in our configuration.

Is enabling the Agenda module required to have the Facture module working properly? 
If so consider enforcing this dependency, for instance by preventing module Agenda from being disabled if Facture is enabled.

**Comment by guillaume-uH57J9** [comment]
It works again after enabling the Agenda module. 

Thanks for your suggestions, I couldn't have figured it out otherwise.
