### ISSUE TITLE
Travis Horreur !

### ISSUE THREAD

**Issue by hregis** [Dolibarr/dolibarr#29160]
### Bug

c'est quoi toutes ces erreurs Travis qui apparaissent sans rien faire d'autres et qui n'ont rien à voir d'une PR à une autres ?
c'est gavant et chronophage !

```
##[group]SecurityTest::testRestrictedArea failed - .
## PHPUnit\Framework\Error\Warning: Cannot modify header information - headers already sent by (output started at /home/******/build/Dolibarr/dolibarr/test/phpunit/AllTests.php:27)
## No new lines in 'dolibarr.log' since start of this test.
##[endgroup]
E
Time: 9.3 seconds, Memory: 58.99 MB
There was 1 error:
1) SecurityTest::testRestrictedArea
Cannot modify header information - headers already sent by (output started at /home/******/build/Dolibarr/dolibarr/test/phpunit/AllTests.php:27)
/home/******/build/Dolibarr/dolibarr/htdocs/main.inc.php:1611
/home/******/build/Dolibarr/dolibarr/htdocs/main.inc.php:1748
/home/******/build/Dolibarr/dolibarr/htdocs/main.inc.php:1563
/home/******/build/Dolibarr/dolibarr/htdocs/core/lib/security.lib.php:1219
/home/******/build/Dolibarr/dolibarr/htdocs/core/lib/security.lib.php:589
/home/******/build/Dolibarr/dolibarr/test/phpunit/SecurityTest.php:824
ERRORS!
Tests: 2461, Assertions: 106248, Errors: 1.
```

**Comment by hregis** [comment]
c'est super la détection d'erreurs de code ou autres... mais si à un moment donné ça crée plus de problèmes que ça en résous ce n'est pas la peine ! Trop de ... tue le... ;-)

**Comment by hregis** [comment]
serait-il possible qu'une erreur soit plus parlante afin de la régler plus facilement/rapidement ?
parce que là c'est... no way !

**Comment by mdeweerd** [comment]
@hregis 
L'analyse du backtrace nou permets de le comprendre.

Ce que cela indique c'est que la ligne 27 de AllTests.php a déjà généré un résultat avant d'émettre les entêtes:

Ligne 27:
```
print "PHP Version: ".phpversion()."\n";
print "Memory limit: ". ini_get('memory_limit')."\n";
```
et l'entête ligne 1611 de main.inc.php:
```
        header("Content-Type: text/html; charset=".$conf->file->character_set_client);
```

Et cela provient d'un accessforbidden dans restrictedArea() .
Qui est provoqué par ce test:
```
    /**
     * testRestrictedArea
     *
     * @return void
     */
    public function testRestrictedArea()
    {
        global $conf,$user,$langs,$db;
        $conf = $this->savconf;
        $user = $this->savuser;
        $langs = $this->savlangs;
        $db = $this->savdb;

        //$dummyuser=new User($db);
        //$result=restrictedArea($dummyuser,'societe');

        $result = restrictedArea($user, 'societe');
        $this->assertEquals(1, $result);
    }
```

Je suppose donc que c'est une modification de la gestion des droits qui a entrainé cela.

On voit qu'il y a plus de tests qui plantent sous windows-ci.  Et une aperçu est disponible dans l'onglet des fichiers modifiés:
https://github.com/Dolibarr/dolibarr/pull/29150/files#annotation_19908537659

**Comment by mdeweerd** [comment]
Pour info, pour reproduire le résultat de ce test en local, j'ai du reconstruire la BDD (j'utilise dev/setup/phpunit/setup_conf.sh).  Avec la version de la BDD précédente (=généré il y a une semaine ou deux) je n'avais pas le même résultat.

Pour info, un fichier SQL d'initialisation est disponible dans les artefacts de windows-ci ([win-ci-logs](https://github.com/Dolibarr/dolibarr/actions/runs/8500479130/artifacts/1372993130) ) à partir de la page sommaire du workflow CI: https://github.com/Dolibarr/dolibarr/actions/runs/8500479130?pr=29150 .

**Comment by mdeweerd** [comment]
Le PR a visiblement cassé qqchse dans l'initialisation de la BDD.  En passant à la version "develop" après la génération de la BDD avec la version du PR #29150 , le SecurityTest plante aussi sous develop et après reinitialisation de la BDD à partir de develop le test passe à nouveau.

C'est donc bien lié au PR.

**Comment by mdeweerd** [comment]
J'ai des pistes: la traduction des labels.la conversion de 'lire' et 'créer' en '0':

J'ai modifié les dates dans les fichier sqls qui correspondent à l'initialisation des branches:
[sqlpr.zip](https://github.com/Dolibarr/dolibarr/files/14825381/sqlpr.zip)

J'ai appliqué mon alias pour comparer les fichiers:
alias wdiff='git diff -U0 --word-diff --word-diff-regex="[^,]+" --no-index --'


Début du diff:
```diff
diff --git a/db_init.sql.20 b/db_init.sql.pr
index e24febcc670..9fb7275a48d 100644
--- a/db_init.sql.20
+++ b/db_init.sql.pr
@@ -19191,0 +19192 @@ CREATE TABLE `llx_rights_def` (
{+  `module_origin` varchar(64) DEFAULT NULL+},
@@ -19196,0 +19198 @@ CREATE TABLE `llx_rights_def` (
{+  `enabled` text DEFAULT NULL+},
@@ -19210,306 +19212,301 @@ INSERT INTO `llx_rights_def` VALUES
(11,[-'Read invoices'-]{+'Read customer invoices (and payments)'+},'facture',{+''+},1,[-'lire',NULL-]{+'0',''+},'a',0,{+'1'+},0,0,'2024-04-01 00::00:00'),
(11,'Lire les factures','facture',{+NULL+},2,'lire',NULL,'a',1,{+NULL+},0,0,'2024-04-01 00::00:00'),
(12,[-'Create and update invoices'-]{+'Create/modify customer invoices'+},'facture',{+''+},1,[-'creer',NULL-]{+'0',''+},'a',0,{+'1'+},0,0,'2024-04-01 00::00:00'),
(12,'Creer/modifier les factures','facture',{+NULL+},2,'creer',NULL,'a',0,{+NULL+},0,0,'2024-04-01 00::00:00'),
(13,[-'Devalidate invoices'-]{+'Invalidate customer invoices'+},'facture',{+''+},1,[-'invoice_advance','unvalidate'-]{+'0',''+},'a',0,{+'1'+},0,0,'2024-04-01 00::00:00'),
(13,'Dévalider les factures','facture',{+NULL+},2,'invoice_advance','unvalidate','a',0,{+NULL+},0,0,'2024-04-01 00::00:00'),
(14,[-'Validate invoices'-]{+'Validate customer invoices'+},'facture',{+''+},1,[-'invoice_advance','validate'-]{+'0',''+},'a',0,{+'1'+},0,0,'2024-04-01 00::00:00'),
```

**Comment by hregis** [comment]
@mdeweerd ok j'ai compris, j'ai rajouté la possibilité de mettre la traduction dans le champ "libelle" de "llx_rights_def" mais c'est un varchar(255) et il doit y avoir des traductions qui dépassent cette lilmite :  `data too long for column 'libelle'`
Je te remercie de ton aide
