### ISSUE TITLE
Issue when update ticket

### ISSUE THREAD

**Issue by mithun1980r** [Dolibarr/dolibarr#29173]
### Bug

![image](https://github.com/Dolibarr/dolibarr/assets/164975907/32cababd-d3a1-42d8-9ad9-4d1f586e6e96)

**Comment by JonBendtsen** [comment]
can you show us the contents of dolibarr.log?

**Comment by mithun1980r** [comment]
Location of log file?

**Comment by JonBendtsen** [comment]
> Location of log file?

in my installation it is in the documents folder

**Comment by mithun1980r** [comment]
[ChangeLog.zip](https://github.com/Dolibarr/dolibarr/files/14830604/ChangeLog.zip)

file attached

**Comment by fappels** [comment]
See #29319
