### ISSUE TITLE
Cannot create directory in documents

### ISSUE THREAD

**Issue by AnteUjcic** [Dolibarr/dolibarr#29213]
### Bug

In my attempt to redirect the user who wanted to access 192.168.0.74(dolibarr IP) to 192.168.0.74/dolibarr, i changed some lines in /etc/apache2/apache2.conf and /etc/apache2/sites-available/dolibarr.conf, the following error: "Cannot create dir /var/www/html/dolibarr/documents/propale/PR2404-0224" it appears every time someone tries to generate a pdf, which also creates a new directory in the documents/propale, I tried to change the ownership of the documents folder to root:www-data and same with the propale folder. 

### Dolibarr Version

16.0.0

### Environment PHP

8.1.9

### Environment Database

PostgreSQL

### Attached files

[confs.txt](https://github.com/Dolibarr/dolibarr/files/14851284/confs.txt)

**Comment by Akuket** [comment]
Seems to be the same problem as the issue #28962 ?
