### ISSUE TITLE
New user right -> create user for customer access

### ISSUE THREAD

**Issue by Movix** [Dolibarr/dolibarr#29222]
### Feature Request

Allow the creation of user accounts for customers without granting rights for creation of internal user, groups, and rights assignements

### Use case

The goal would be to allow users to create customer accounts getting the defaults rights upon creation.
User having this right should not be able to create internal users, modifying permissions, modifying users groups, changing group members.

**Comment by hregis** [comment]
@Movix you can create a group allowing or not allowing certain things and associate external users with this group

**Comment by Movix** [comment]
Hello Regis,

Thank you for your answer.
Correct me if i'm wrong.
What you say is right but this also needs to give a user the right to modify users, groups and permissions, in a first place to create the external user and in a second step to allow the association of the user to the said group.
Movix

**Comment by hregis** [comment]
@Movix ok i see... maybe waiting the webportal module for the v20 ;-) https://github.com/Dolibarr/dolibarr/tree/develop/htdocs/webportal

**Comment by Movix** [comment]
SETUP -> Security -> enable extended permissions
Was as simple as that. Shame on me for not seen this before after so long time using Dolibarr
