### ISSUE TITLE
Third party merging does not work

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2923]
# Environment
- **Version**: 3.8.0-alpha
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.9
- **Database**: MySQL 5.5.5-10.0.18-MariaDB-log
- **URL**: /societe/soc.php?socid=9&action=confirm_merge&confirm=yes
# Report

**Error message**: The Origin thirdparty is mandatory

**Comment by aaujon** [comment]
This is caused by #2807

**Comment by marcosgdf** [comment]
This is now working
