### ISSUE TITLE
Not admin that can create group have disabled button for group creation

### ISSUE THREAD

**Issue by Elikill58** [Dolibarr/dolibarr#29279]
### Bug

As not admin, I have a greyed "New group" button :
![image](https://github.com/Dolibarr/dolibarr/assets/17381066/d5e32baa-6488-4fa7-a3e8-be096e2f3a5c)

But, the top right button stay available to click:
![image](https://github.com/Dolibarr/dolibarr/assets/17381066/74c3af99-7344-46fb-a4ac-3bc6bc04a484)

And going to this page doesn't return 403. It seems I should have the permission to do it:
![image](https://github.com/Dolibarr/dolibarr/assets/17381066/cdca44db-731f-43de-be9a-946bfcf17188)

So why is this button greyed ?

### Dolibarr Version

18.0.5

### Environment PHP

8.1.27

### Environment Database

MariaDB 10.11.6

### Steps to reproduce the behavior and expected behavior

- Login with not admin account
- Clic on "Users and groups"
- See disabled button

**Comment by JonBendtsen** [comment]
V 19.0.0 tuxgasy + some unknown modifications from develop has the same issue.

**Comment by JonBendtsen** [comment]
v19.0.0 switching to the md theme will not show "New group" in grey, BUT there is no link, it is just not greyed.


![eldy_menu_theme_greys_group](https://github.com/Dolibarr/dolibarr/assets/2551481/532bcc34-a0d4-4995-adfb-b99790d4e51a)
![md_menu_theme_shows_group](https://github.com/Dolibarr/dolibarr/assets/2551481/181e20ce-65bd-426e-9fd6-16094921194f)

**Comment by hregis** [comment]
@JonBendtsen @Elikill58 the error come from the hook "doActions"... you have externals modules ?

**Comment by JonBendtsen** [comment]
@hregis  I _think_ this is the issue.

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/menus/standard/eldy.lib.php#L1225

**Comment by JonBendtsen** [comment]
```
$newmenu->add("/user/group/card.php?leftmenu=users&action=create", $langs->trans("NewGroup"), 2, ((getDolGlobalString('MAIN_USE_ADVANCED_PERMS') ? $user->hasRight("user", "group_advance", "create") : $user->hasRight("user", "user", "create")) || $user->admin) && !(isModEnabled('multicompany') && $conf->entity > 1 && getDolGlobalString('MULTICOMPANY_TRANSVERSE_MODE')));
```

I don't think I have MAIN_USE_ADVANCED_PERMS and it doesn't check for `$user->hasRight('user', 'user', 'creer')`

**Comment by Elikill58** [comment]
> @JonBendtsen @Elikill58 the error come from the hook "doActions"... you have externals modules ?

Yes, how can I easily get list of modules ?

**Comment by JonBendtsen** [comment]
> > @JonBendtsen @Elikill58 the error come from the hook "doActions"... you have externals modules ?
> 
> Yes, how can I easily get list of modules ?

Home, Setup, Modules/Applications

**Comment by JonBendtsen** [comment]
> > @JonBendtsen @Elikill58 the error come from the hook "doActions"... you have externals modules ?
> 
> Yes, how can I easily get list of modules ?

@Elikill58 Home, Admin Tools, About Dolibarr, Modules/Applications

**Comment by hregis** [comment]
@Elikill58 have you Multicompany module ?

**Comment by Elikill58** [comment]
I will answer tomorrow as I'm not at my job, I don't know

**Comment by hregis** [comment]
@Elikill58 @JonBendtsen Multicompany module can create this error if the user have the right to create a group and if the option of centralization of the management of the users is in the first entity ! I check to fix this bug...

**Comment by JonBendtsen** [comment]
@hregis  I do not use the Multicompany module

**Comment by hregis** [comment]
@JonBendtsen if you don't use multicompany that means you've wasted your life!! ;-) (joke)

**Comment by hregis** [comment]
@JonBendtsen @Elikill58 https://github.com/Dolibarr/dolibarr/pull/29287

**Comment by Elikill58** [comment]
> @Elikill58 have you Multicompany module ?

I do not have this one. Thanks for fixing this bug so much faster :)
