### ISSUE TITLE
Customer shipping deletion

### ISSUE THREAD

**Issue by all3kcis** [Dolibarr/dolibarr#2927]
Develop version :
ERROR: "ErrorBadValueForParamNotAString"
By removing a shipment containing batch products.

In versions 3.6 and 3.7 :
shipping is deleted but not well re-increment for batch products.

![01](https://cloud.githubusercontent.com/assets/9413626/7885153/9835e790-0622-11e5-81ec-8353b625a7b2.jpg)

starting quantity
lot-001     5
lot-002     5

After shipping
![02](https://cloud.githubusercontent.com/assets/9413626/7885007/d1203818-0621-11e5-83c4-d1e5cc790287.jpg)

After delete in 3.6 or 3.7
![03](https://cloud.githubusercontent.com/assets/9413626/7885068/2b76cea8-0622-11e5-9a5b-f4ae00d0efdd.jpg)

**Comment by BebZ** [comment]
double posted issue but your post is better, so i will close mine ;)
https://github.com/Dolibarr/dolibarr/issues/2907

**Comment by fappels** [comment]
Something to check when debugging:
Warning: array_merge(): Argument #1 is not an array in ...\dolibarr\htdocs\expedition\class\expedition.class.php on line 1193

**Comment by marcosgdf** [comment]
AFAIK, ProductBatch module is marked as experimental and therefore not supported...

**Comment by fappels** [comment]
In 3.8 it's out of experimental. So if fix in 3.7 we can merge to 3.8.

**Comment by all3kcis** [comment]
I just edit my first post.
Without considering the problem on version 3.6 and 3.7 (where the productbatch module is experimental).

Bug "ErrorBadValueForParamNotAString" in develop version is still present.

As said by fappels :
Warning: array_merge(): Argument #1 is not an array in ...\dolibarr\htdocs\expedition\class\expedition.class.php on line 1193

**Comment by all3kcis** [comment]
For me this bug is still there.
"ErrorBadValueForParamNotAString" after shipping deletion
