### ISSUE TITLE
TICKET ERROR WHEN TRY TO DELET 

### ISSUE THREAD

**Issue by mithun1980r** [Dolibarr/dolibarr#29297]
### Bug

![image](https://github.com/Dolibarr/dolibarr/assets/164975907/50e901a3-8bf8-42b4-ac36-bca2a2259897)
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/14921011/dolibarr.log)

Error when try to delete ticket

**Comment by JonBendtsen** [comment]
@mithun1980r  your file is 60454 lines and it spans from

```
JonSweet16:tmp jonbendtsen$ head -1 dolibarr.log.txt 
2024-04-04 16:46:40 DEBUG   106.216.255.230 - This is an already logged session. _SESSION['dol_login']=mithun.roy _SESSION['dol_entity']=1
```
to 
```
JonSweet16:tmp jonbendtsen$ tail -1 dolibarr.log.txt 
2024-04-09 15:53:01 INFO    49.37.97.170    document.php download /home4/omnistr1/public_html/dolibarr/documents/dolibarr.log filename=dolibarr.log content-type=text/plain
```

SURELY we do not need 5 days of logs. Cut out the relevant part, the rest is irrelevant.

**Comment by mithun1980r** [comment]
is there any solution  for this issue

**Comment by JonBendtsen** [comment]
@mithun1980r  maybe you should use the support forum on https://www.dolibarr.org/forum/

**Comment by fappels** [comment]
PR here https://github.com/Dolibarr/dolibarr/pull/29319
@JonBendtsen V20 issue best report on Github, forum for help on stable version.
