### ISSUE TITLE
Add a note in Ubuntu/Debian's Dolibarr installer's documentation about a system error message

### ISSUE THREAD

**Issue by q2dg** [Dolibarr/dolibarr#29309]
### Feature Request

When installing Dolibarr using the Debian/Ubuntu installer, at the end appears this error message: _"APT Error Download that is performed unsandboxed as root as file '/var/cache/apt/archives/partial/ couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)"_  You can see this message on next capture (in catalan):

![apt-warning](https://github.com/Dolibarr/dolibarr/assets/7274874/2537517f-85da-4dc8-b412-e806b2651cf8)

Fortunately, as it is explained in https://orcacore.com/fix-apt-error-download-is-performed-unsandboxed-as-root, this error is innoquous, but it scares. So...could be some comment about this added in Dolibarr documentation, specifically here: (https://wiki.dolibarr.org/index.php/Dolibarr_for_Ubuntu_or_Debian) ?

Thanks

**Comment by sonikf** [comment]
Hi @q2dg,
This is a long standing issue with apt related programs in Debian/Ubuntu distros and is actually a note(see N:).
Bare in mind though that nothing that disables a security feature can be called innocuous.
Also the solution in the link you provided is to elevate privileges and download as root just to suppress a warning, which in case of a security vulnerability it could potentially compromise your system...

In this case a regular user installing a .deb will never see that message but feel free to open an account in Dolibarr wiki and document this.

**Comment by q2dg** [comment]
Thanks a lot for your explanation. I'll close this issue, then. Sorry for the inconvenience
