### ISSUE TITLE
Message: Ticket::fetch ErrorWrongParameters

### ISSUE THREAD

**Issue by XBIOMED** [Dolibarr/dolibarr#29324]
### Bug

When assigne a third part to a ticket opned by mail collector 
$_GET
array:1 [ "track_id" => "cyun2pimx5deocir" ]
$_POST
array:3 [
  "action" => "set_thirdparty"
  "token" => "edd786f5e1c331ccac44bc33b91d6103"
  "editcustomer" => "4"
]
$_SESSION
array:24 [
  "newtoken" => "edd786f5e1c331ccac44bc33b91d6103"
  "dol_loginmesg" => ""
  "token" => "edd786f5e1c331ccac44bc33b91d6103"
  "dol_login" => "xxx"
  "dol_logindate" => 1712829667
  "dol_authmode" => "xxxxxx"
  "dol_tz" => "4"
  "dol_tz_string" => "Indian/Reunion"
  "dol_dst" => 0
  "dol_dst_observed" => 0
  "dol_dst_first" => ""
  "dol_dst_second" => ""
  "dol_screenwidth" => "1280"
  "dol_screenheight" => "762"
  "dol_company" => "Mycompagny"
  "dol_entity" => 1
  "mainmenu" => "ticket"
  "leftmenuopened" => ""
  "idmenu" => ""
  "PHPDEBUGBAR_STACK_DATA" => []
  "leftmenu" => ""
  "ticket-view-type" => "messaging"
  "lastsearch_values_tmp_ticket/list.php" => "{"search_fk_status":"non_closed","search_fk_statut":["openall"]}"
  "lastsearch_contextpage_tmp_ticket/list.php" => "ticketlist"
]
$_COOKIE
array:2 [
  "DOLSESSID_b1b94de7074b19151960e8a79ef871422bc53bee" => "*****hidden*****"
  "DOLUSERCOOKIE_boxfilter_task" => "all"
]
$_SERVER
array:55 [
  "USER" => "mywebsite.com_coz3c6ohncb"
  "HOME" => "/var/www/vhosts/mywebsite.com"
  "SCRIPT_NAME" => "/ticket/card.php"
  "REQUEST_URI" => "/ticket/card.php?track_id=cyun2pimx5deocir"
  "QUERY_STRING" => "track_id=cyun2pimx5deocir"
  "REQUEST_METHOD" => "POST"
  "SERVER_PROTOCOL" => "HTTP/1.0"
  "GATEWAY_INTERFACE" => "CGI/1.1"
  "REMOTE_PORT" => "53434"
  "SCRIPT_FILENAME" => "/var/www/vhosts/mywebsite.com/httpdocs/ticket/card.php"
  "SERVER_ADMIN" => "[no address given]"
  "CONTEXT_DOCUMENT_ROOT" => "/var/www/vhosts/mywebsite.com/httpdocs"
  "CONTEXT_PREFIX" => ""
  "REQUEST_SCHEME" => "https"
  "DOCUMENT_ROOT" => "/var/www/vhosts/mywebsite.com/httpdocs"
  "REMOTE_ADDR" => "xx.xxx.xxx.xx"
  "SERVER_PORT" => "443"
  "SERVER_ADDR" => "xxx.xxx.xxx.XXx"
  "SERVER_NAME" => "mywebsite.com"
  "SERVER_SOFTWARE" => "Apache"
  "SERVER_SIGNATURE" => "<address>Apache Server at mywebsite.com Port 443</address>\n"
  "PATH" => "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  "HTTP_COOKIE" => "DOLSESSID_b1b94de7074b19151960e8a79ef871422bc53bee=jnod918ubbiu8p752g0relhfbm; DOLUSERCOOKIE_boxfilter_task=all"
  "HTTP_ACCEPT_LANGUAGE" => "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7"
  "HTTP_ACCEPT_ENCODING" => "gzip, deflate, br, zstd"
  "HTTP_REFERER" => "https:///"
  "HTTP_SEC_FETCH_DEST" => "document"
  "HTTP_SEC_FETCH_USER" => "?1"
  "HTTP_SEC_FETCH_MODE" => "navigate"
  "HTTP_SEC_FETCH_SITE" => "same-origin"
  "HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
  "HTTP_USER_AGENT" => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
  "CONTENT_TYPE" => "application/x-www-form-urlencoded"
  "HTTP_ORIGIN" => "https://mywebsite.com"
  "HTTP_UPGRADE_INSECURE_REQUESTS" => "1"
  "HTTP_SEC_CH_UA_PLATFORM" => ""Linux""
  "HTTP_SEC_CH_UA_MOBILE" => "?0"
  "HTTP_SEC_CH_UA" => ""Chromium";v="123", "Not:A-Brand";v="8""
  "HTTP_CACHE_CONTROL" => "max-age=0"
  "CONTENT_LENGTH" => "75"
  "HTTP_CONNECTION" => "close"
  "HTTP_X_ACCEL_INTERNAL" => "/internal-nginx-static-location"
  "HTTP_X_REAL_IP" => "xx.xxx.xxx.Xx"
  "HTTP_HOST" => "mywebsite.com"
  "proxy-nokeepalive" => "1"
  "HTTPS" => "on"
  "PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY" => "0"
  "PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY" => "0"
  "SCRIPT_URI" => "https:///ticket/card.php"
  "SCRIPT_URL" => "/ticket/card.php"
  "UNIQUE_ID" => "Zhe2qeF6O1ctRBvtLANSPwAAAEQ"
  "FCGI_ROLE" => "RESPONDER"
  "PHP_SELF" => "/ticket/card.php"
  "REQUEST_TIME_FLOAT" => 1712830121.914
  "REQUEST_TIME" => 1712830121

### Dolibarr Version

20.0 alpha

### Environment PHP

DE 7.3.33  to 8.2.17

### Environment Database

maria DB  

### Steps to reproduce the behavior and expected behavior

open a ticket created by mail collector 
modify third part  
issue

**Comment by fappels** [comment]
PR made #29319

**Comment by XBIOMED** [comment]
Perfect !! it works without problem thanks
