### ISSUE TITLE
Sales Orders module next/previous links not working

### ISSUE THREAD

**Issue by support337** [Dolibarr/dolibarr#29330]
### Bug

When "<" or ">" button is clicked in the top right corner at page 

http://localhost/commande/card.php?id=4

User is redirected to wrong url instead of next or previous Sales Order card:

http://localhost/commande/card.php

Also using keyboard shortcuts ALT+P or ALT+N redirects to http://localhost/commande/card.php instead of next or previous Sales Order card 

### Dolibarr Version

19.0.1

### Environment PHP

8.2.17

### Environment Database

Postgres 15.6

### Steps to reproduce the behavior and expected behavior

1) Create multiple Sales Order
http://debian.local/commande/card.php?action=create&leftmenu=orders
2) Open Sales Order detail
http://debian.local/commande/card.php?id=4&save_lastsearch_values=1
3) click on next or previous navigation arrows or use keyboard shortcuts ALT+P or ALT+N 
![image](https://github.com/Dolibarr/dolibarr/assets/76212923/3f858ca7-84fc-404b-b94c-e66e939f2f61)
4) after click or keyboard shortcut user is redirected to
http://debian.local/commande/card.php

![image](https://github.com/Dolibarr/dolibarr/assets/76212923/bfb35225-6cef-464a-91a7-0903c1d35f56)

Desired effect: Navigate to next or previous Sales Order item

**Comment by sonikf** [comment]
Hi @support337 
Can you please upgrade to v. 19.0.1 and report back?

**Comment by support337** [comment]
> Hi @support337 Can you please upgrade to v. 19.0.1 and report back?

19.0.1 has the same problem, redirects to commande/card.php after click. 

Just in case tried the Third Parties module at URL: 

societe/card.php?socid=3641&save_lastsearch_values=1

next/previous buttons work, after click redirects to 

societe/card.php?socid=3642

**Comment by fappels** [comment]
Can't reproduce in latest V19. Note that for orders navigation switches to ?ref= not like societe ?socid=
Please re-open if this still an issue.
