### ISSUE TITLE
Link type extrafields on supplier order line are no longer working 

### ISSUE THREAD

**Issue by IC-Ilies** [Dolibarr/dolibarr#29333]
### Bug

Hello,

When i attempted to create an extrafield (link to an other object) on a supplier order line, this error showed up : 
selectForForms: Error bad setup of field objectdescorig=Contact, objectfield=commande_fournisseurdet:options_buyprice

![Capture d’écran du 2024-04-12 11-01-26](https://github.com/Dolibarr/dolibarr/assets/86972374/8b8423a2-4946-4aed-a91c-9f1bf39f9e7e)

I already found the origin of this bug and i will make a pull request, but i suspect that this problem will possibily occur on many other elements, since the problem comes from the 'getElementProperties' function (core/lib/functions.lib.php) and that many elements may not have been integrated into this function (maybe) 
![Capture d’écran du 2024-04-12 11-05-05](https://github.com/Dolibarr/dolibarr/assets/86972374/2fd6dd0b-4d00-4f9c-bea6-baa34ff0e0b2)

### Dolibarr Version

19.0.1

### Environment PHP

8.1.27

### Environment Database

10.5.23-MariaDB

### Steps to reproduce the behavior and expected behavior

Set up an extrafield of type link on supplier order lines (from code or dolibarr's interface)
Link it to whatever you want (even the basic examples provided into the help tooltip)
Create it 
When you go to the line form on any order supplier, you'll see the error

**Comment by JonBendtsen** [comment]
@IC-Ilies  what if you searched for the old text string(s) in other modules? would you then find them?

**Comment by IC-Ilies** [comment]
> @IC-Ilies what if you searched for the old text string(s) in other modules? would you then find them?

I don't think it is as simple as that, because i would have to search for every class that has en element attribute that is not in correlation with it's name (and there is a lot of dolibarr classes :p ) . For now i think i will just check the issues and let this one open if another similar bug shows

**Comment by eldy** [comment]
Can you provide the definition (screenshot of extrafield setup) of your extrafield coefficient ?

**Comment by IC-Ilies** [comment]
![image](https://github.com/Dolibarr/dolibarr/assets/86972374/d4051b31-a6e5-44e6-b534-2422d55e41a7)

@eldy Here it is :)

**Comment by eldy** [comment]
So yes, trouble is surely into
getElementProperties that does not handle all the cases, you can send a pr to add support for commande_fournisseurdet
Previoudly all cases non standard were handled at different places. We introduced getElementProperties to have this handled in 1 place only but may have forgotten cases...

**Comment by joetheinventor** [comment]
Even though in changelog it says fixed, It seems this bug continues in 19.02
Also interventions have same problems.
