### ISSUE TITLE
v19.0.1 : Cannot view turnover invoiced by third parties

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#29338]
### Bug

Cannot view turnover invoiced by third parties
URL : /compta/stats/casoc.php?leftmenu=report&modecompta=CREANCES-DETTES

### Dolibarr Version

19.0.1

### Environment PHP

8.2.7

### Environment Database

PostgreSQL 15.6

### Steps to reproduce the behavior and expected behavior

Go to Accounting > Reporting > Turnover invoiced > By third parties
Expected : You should see all row
Actual : Crash during first line

In log : 
PHP Fatal error:  Uncaught Error: Array callback must have exactly two elements in /home/crm/dolibarr-19.0.1/htdocs/compta/stats/casoc.php:638

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/11213740/02693f6d-b0bf-4dd4-a8e4-7c9f04b8652a)

**Comment by fredol** [comment]
Same here with:
- PHP: 7.4
- MariaDB: 10.11

**Comment by fredol** [comment]
After upgrading to 19.0.2 on two instances, this bug is not fixed.

Please reopen this issue

**Comment by ludovicandrieux** [comment]
@fredol > I confirm, fix is in develop for future 20.x
Perhaps it will be backport to 19.0.3
