### ISSUE TITLE
Dolibarr ticket system should show unread messages at ticket list page

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#29355]
### Feature Request

Currently there is no way to see unread messages from customers end at the ticket list page for the following tickets.

1. Assigned
2. In Progress
3. Read
4. Waiting For Feedback

### Use case

Generally ERP/CRM users or admin will just access the Ticket Listing page (if they have access to it), and they should easily see that there is a customer reply on the ticket for the same. There is no way of do so. No information of unread messages. User need to checkout every ticket card for checking for new messages. Which is very unproductive. 

### Suggested implementation

While any customer is replying from Public Interface or using the Email reply, upon adding the message to the particular ticket, the message should be in **_Unread_** status. Now when the internal users visit the ticket card and the navigate to the tab, Events/Agenda. Those messages should be marked as **Read**.

On the ticket list page, if a ticket has unread messages from customers end, it should show the messages using Icons and number of unread messages, at the first column of the row. Please check the attached image for a sample. Or we can simply change the background for that ticket row.

Tickets having unread replies from the customer end should be in the top of the list first. 
![message-icon](https://github.com/Dolibarr/dolibarr/assets/1249577/c1a629fc-9946-4729-a182-823d7d6ed864)

### Suggested steps

I think we can easily implement this feature if we introduce a new column for the MySQL table named, **_is_read_**. The type of the column should be TINYINT. It's value will be 0 or 1. 0 is the default value while messages will be added, that the message is not read yet. 1 means message already read.

**Comment by nicolasVr** [comment]
Hello, I agree it is a problem.
There is already a fk_statut variable that can have the value STATUS_NOT_READ (  https://github.com/Dolibarr/dolibarr/blob/048f7e360f0af4b2bff98f3ec0420b253cc58e7f/htdocs/ticket/index.php#L186C35-L186C50 ). Why not change the value of this variable when a new comment/message is linked to the ticket ? In such a way, we don't need to modify a Mysql Table.

**Comment by alsoft10** [comment]
Hello @nicolasVr ,

In that case you will loose the Assigned, In Progress and Waiting For Feedback status. Let's say a ticket is created for a complex task and it will take long time time may be a month  to complete it. Now admin has assigned a Dolibarr user to the ticket with the status In Progress. Now User is communication with the customer weekly. Now how a new unread message status will you represent easily? 

If you simply set the Status to the value STATUS_NOT_READ, you will loose the In Progress status. So to make things run smoothly, I think ticket will remain in In Progress status, but we need to find out a way to show that the ticket has an Unread messages.

**Comment by nicolasVr** [comment]
I understand your point of view. But would it be ok if the status is set back to "In Progress" as soon as the the message is read ?

**Comment by alsoft10** [comment]
I got your point. We can do things like this so it will be more easier for you as the developer.

If the ticket has one of the following status before reading the message, set the status as it is as it was before receiving the new message.

1. Read
2. Assigned
3. In Progress
4. On Hold
5. Waiting For Feedback

**Comment by nicolasVr** [comment]
Unfortunately, I am not a developer !

**Comment by nicolasVr** [comment]
I think https://github.com/Dolibarr/dolibarr/pull/30556 fulfill this need, but can it be backported in v19 ? One should try...

**Comment by alsoft10** [comment]
This feature is implemented.
