### ISSUE TITLE
Missing an "Y" on 3.7.0-3.8.0.sql inside dolibarr_3.8.0-3_all.deb

### ISSUE THREAD

**Issue by viruslox** [Dolibarr/dolibarr#2935]
Hi All,

sorry for disturb, I would just notice that dolibarr_3.8.0-3_all.deb packet has a very little bug on 3.7.0-3.8.0.sql script that affect people that try to upgrade to last alfa using dpkg on debian/ubuntu.
Once installed, on Debian the script is located in:
/usr/share/dolibarr/htdocs/install/mysql/migration
Solution: search on the script for "AUTO_INCREMENT PRIMAR KEY"
You'll find only one occurence, so change it to "AUTO_INCREMENT PRIMARY KEY".

Thanks

**Comment by rdoursenaud** [comment]
3.8 is an unreleased version.
The problem you mention seems fixed.

If you use an alpha version, you're expected to know how to debug it and pull request a fix.
If you're not able to do that, please wait for the beta.

Thanks.

**Comment by viruslox** [comment]
Man, I found a bug and I provided you a workaround.
I don' t need help: I just gave my 5cents to you.
Cheers
