### ISSUE TITLE
PHP errors on separator type extrafield update

### ISSUE THREAD

**Issue by code42fr** [Dolibarr/dolibarr#29371]
### Bug

When we update a separator type extrafield (on company configuration for example), we have two errors due to a variable not instantiated on extrafield.class.php file and explode() function on actions_extrafields.inc.php.

![Capture d’écran 2024-04-17 à 11 22 41](https://github.com/Dolibarr/dolibarr/assets/9167207/52789dcb-a0d5-4209-a5ab-fdf17cbbb30a)

$param_ligne does not always contain a comma and in this case, we get the warning.
![Capture d’écran 2024-04-17 à 11 41 42](https://github.com/Dolibarr/dolibarr/assets/9167207/0240decf-6e7c-4803-91fd-1eb77209bbcd)
If $type is "separate", $result is not instantiated.
![Capture d’écran 2024-04-17 à 11 17 51](https://github.com/Dolibarr/dolibarr/assets/9167207/c2b96c85-a20c-4a38-afa1-6ad017bfc666)

I updated separator without parameters :   

![Capture d’écran 2024-04-17 à 11 43 39](https://github.com/Dolibarr/dolibarr/assets/9167207/e4d89195-3312-4f47-8a86-1e434000e565)

### Dolibarr Version

19.0.1

### Environment PHP

8.2.10

### Environment Database

MySQL or MariaDB 10.3.39-MariaDB-0+deb10u1

### Steps to reproduce the behavior and expected behavior

Add a separator extrafield on an object and modify it :   
![Capture d’écran 2024-04-17 à 11 43 39](https://github.com/Dolibarr/dolibarr/assets/9167207/88a00b58-9c71-4f17-98c3-ae337673eb01)

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 19.0.2

**Comment by code42fr** [comment]
Hello, 
Unfortunately, this problem is still effective on version 19.0.2. 

Updating a separate extra field on contracts :
![Capture d’écran 2024-09-10 à 09 15 32](https://github.com/user-attachments/assets/d0296b52-e6e8-42fe-927d-98cace0b7a29)
