### ISSUE TITLE
HRM : User have access to monthly statement without permission

### ISSUE THREAD

**Issue by HiroKX** [Dolibarr/dolibarr#29372]
### Bug

Even if a user doesn't have the right to read all leave requests [1], the user can still access them by using the associated URI that goes to the monthly statement.

I can handle the PR if you'd like :)

[1] : 
![image](https://github.com/Dolibarr/dolibarr/assets/57806687/4bec1157-1632-4a16-a3d2-62098884e22c)

[2]
![image](https://github.com/Dolibarr/dolibarr/assets/57806687/87f0e8d8-fada-4d8a-a497-4d486a7f7473)

### Dolibarr Version

19.0.1

### Environment PHP

8.1

### Environment Database

MariaDB

### Steps to reproduce the behavior and expected behavior

Create a user that has no access except "read leaves request"
Log with this account and access to the URI : https://yourdomain.com/holiday/month_report.php?mainmenu=hrm&leftmenu=holiday

**Comment by JonBendtsen** [comment]
@HiroKX 

> I can handle the PR if you'd like :)

I think you should just submit a small well tested PR - that is how I got started with not only fixing bugs but also adding a few new features.
