### ISSUE TITLE
Unable to delete a skill in the job profile

### ISSUE THREAD

**Issue by SandraMazingant** [Dolibarr/dolibarr#29403]
### Bug

it's impossible to delete a skill in the list for a job profile.
when you click on the trash; there is a message "skill delete Ok"
but nothing happens. the skill is always in the list

![delete-skill](https://github.com/Dolibarr/dolibarr/assets/167513680/039cd676-ecef-4af1-96df-15388406b5ea)

### Dolibarr Version

19.0.1

### Environment PHP

8.0.23

### Environment Database

MySQL or MariaDB 10.3.32-MariaDB

### Steps to reproduce the behavior and expected behavior

In GRH module / evaluation
create a new job profile
add skills 
try to delete skill in the list

### Attached files

![delete-skill](https://github.com/Dolibarr/dolibarr/assets/167513680/6cfd5181-0669-46df-bfc9-cd10b6d772ba)

**Comment by joetheinventor** [comment]
This bug continues in 19.02
