### ISSUE TITLE
fiche intervention model list => ouvrir model 

### ISSUE THREAD

**Issue by Sos-ME** [Dolibarr/dolibarr#29422]
### Bug

User
SELECT f.title as title, f.fk_soc, f.datec, f.duree, f.fk_projet, f.fk_contrat, f.description, f.note_private, f.note_public, f.fk_user_author, f.frequency, f.unit_frequency, f.date_when, f.date_last_gen, f.nb_gen_done, f.nb_gen_max, f.auto_validate, f.note_private, f.note_public, f.fk_user_author FROM llx_fichinter_rec as f WHERE f.rowid = 31.12
[DB_ERROR_NOSUCHFIELD] Unknown column 'f.title' in 'field list'

In sql table llx_fichinter_rec : the field is named titre, changing it  to title solve the issue but creat another one in the same fiche inter model : SELECT MAX(te.ref) FROM llx_fichinter_rec as te WHERE te.ref < 'rapport intervention1.08
[DB_ERROR_NOSUCHFIELD] Unknown column 'te.ref'    in 'field list' and  in list because it need title  not titre :  [DB_ERROR_NOSUCHFIELD] Unknown column 'f.titre' in 'field list'

### Dolibarr Version

20.0.0-alpha 

### Environment PHP

7.4.33

### Environment Database

sql maria DB 

### Steps to reproduce the behavior and expected behavior

Fiche inter model => select one model to open => issu

**Comment by Sos-ME** [comment]
![fichinter rec class](https://github.com/Dolibarr/dolibarr/assets/93753953/140714b7-62c2-4459-ac41-f7b9a2d64784)
![card rec php](https://github.com/Dolibarr/dolibarr/assets/93753953/ef26bc2c-bb2f-49b6-aaa8-efbaf09f43ff)
resolve but still the error te.ref

**Comment by ghost** [comment]
Hello, tested on dolibarr v20 & develop. This seems fixed with mentionned PR #29537
