### ISSUE TITLE
langs/de_AT/main.lang translation error

### ISSUE THREAD

**Issue by vsatmydynipnet** [Dolibarr/dolibarr#29420]
### Bug

There is
Ref=Bezeichnung

Should be
Ref=Ref.Nr.

### Dolibarr Version

19.0.0

**Comment by ksar-ksar** [comment]
Hello,

Thanks for the report, but all the translations issues should be reported in Transifex not GitHub : https://explore.transifex.com/dolibarr-association/dolibarr/

**Comment by vsatmydynipnet** [comment]
Done.
