### ISSUE TITLE
Impossible to add a Service in Invoice

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#29429]
### Bug

In an Invoice, you cannot insert a Service, only a product. Listing Services and Products is fine.
![image](https://github.com/Dolibarr/dolibarr/assets/11374733/ed58e14b-9ed4-4584-9e40-7cef045f7450)

The Invoice draft was created with an earlier pull, just to demonstrate the existing Service "ABB" is not selectable for an Invoice

### Dolibarr Version

develop  a409b9b53bc

### Environment PHP

8.2.16

### Environment Database

10.5.23-MariaDB-0+deb11u1

### Steps to reproduce the behavior and expected behavior

Create an Invoice Draft and try to add a Service. Adding a product works fine.

**Comment by JonBendtsen** [comment]
Works fine for me. Are your service configured to be for sale?

![image](https://github.com/Dolibarr/dolibarr/assets/2551481/e27abbd5-3b1c-48ae-88e6-405c3267ee73)

**Comment by mwelters** [comment]
Yes, the Service ABB is for sale.

My production system is on a earlier commit. I copied the database and up migrated with /install ... 
If I remember right, the problems started around the GETPOST -> GETPOSTINT changes...

**Comment by JonBendtsen** [comment]
@mwelters  anything in the documents/dolibarr.log file? and the webservers log?

**Comment by hregis** [comment]
@mwelters I don't have this problem either! Do you have any other add-ons? because very often it comes from that! and if not, and if you are not a developer, then do not use the development version because you will inevitably have bugs!!!

**Comment by frederic34** [comment]
@mwelters can you check if ajax search is still broken for services ?

**Comment by mwelters** [comment]
Thank you Frederic for trusting my problem report

Yes, I checked out fresh a minute ago and the issue is solved.
