### ISSUE TITLE
incorrect page numbering in PDF

### ISSUE THREAD

**Issue by GildDart** [Dolibarr/dolibarr#29458]
### Bug

In v18.0.5 (php 8.0.30) the page numbering in the Propale pdf is incorrect. It is in the form: 1/2, 2/3, 3/4, 4/4 instead of 1/4, 2/4, 3/4, 4/4 (azure and cyan models).

On the same server and configuration it is correct for v17.0.3

### Dolibarr Version

18.0.5

### Environment PHP

8.0.3

### Environment Database

	10.6.17-MariaDB

**Comment by sonikf** [comment]
Hi @GildDart 
Can you check if PDF_USE_GETALIASNBPAGE_FOR_TOTAL set to 1 fixes your problem and if numbering is in correct position?

**Comment by GildDart** [comment]
Great it works !!!
Thank you sonikf.

**Comment by sonikf** [comment]
Hi @GildDart 
Can you reopen? This is actually a bug and is reproducible in 19.0.1 and 20.0.0-alpha

**Comment by GildDart** [comment]
Done...

**Comment by fappels** [comment]
Have put this on high priority, had more complaints on this. Some Authorities do not accept invoices with incorrect page numbering.

**Comment by sonikf** [comment]
Hi @fappels,
Can we collaborate on this?
Problem is here
https://github.com/Dolibarr/dolibarr/blob/e2eb4e9168fc61de192f96122d1ad87541b8cee2/htdocs/core/lib/pdf.lib.php#L1355-L1365
For countries using Freemono or DejaVuSans  instead of default Helvetica font only const PDF_USE_GETALIASNBPAGE_FOR_TOTAL works but renders wrong 

![2024-04-25_11-44](https://github.com/Dolibarr/dolibarr/assets/93765174/c03503d9-cdb3-46c5-ad4d-b884062327a0)
line 1365 should change from
`$pdf->MultiCell(18, 2, $pagination, 0, 'R', 0);`
to
`$pdf->MultiCell(30, 2, $pagination, 0, 'R', 0);`

**Comment by fappels** [comment]
Maybe make PR for V18 like:
```
if (in_array(pdf_getPDFFont($outputlangs), array('Freemono',  'DejaVuSans'))) {
    $pdf->MultiCell(30, 2, $pagination, 0, 'R', 0);
} else {
    $pdf->MultiCell(18, 2, $pagination, 0, 'R', 0);
}
```
and remove PDF_USE_GETALIASNBPAGE_FOR_TOTAL to keep only getAliasNbPages

**Comment by sonikf** [comment]
@fappels , @GildDart 
Can you test following code? It works for me in 18.0.5, 19.0.1 and 20.0.0-alpha

```
	// Show page nb only on iso languages (so default Helvetica font)
		$pdf->SetXY($dims['wk'] - $dims['rm'] - 18 - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_X', 0), -$posy - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_Y', 0));
		$pagination = $pdf->PageNo().' / '.$pdf->getAliasNbPages();
		if (in_array(pdf_getPDFFont($outputlangs), array('Freemono',  'DejaVuSans'))) {
    		$pdf->MultiCell(30, 2, $pagination, 0, 'R', 0);
		} else {
    		$pdf->MultiCell(18, 2, $pagination, 0, 'R', 0);
		}
```

**Comment by fappels** [comment]
@sonikf , @GildDart
Was still not working for 'Freemono', should be 'freemono'
Changed code also a bit, can you test?
I tested on all font found in main.lang

**Comment by GildDart** [comment]
It is working with my v18.0.5.

**Comment by sonikf** [comment]
@fappels 
Somehow both 'Freemono' and  'freemono' works for me!
Tested again in 18.0.5, 19.0.1 and 20.0.0-alpha and it works!
Position with your code is a little bit off though even with` $paginationWidth = 30;`, can't figure out why...
freemono

![2024-04-25_17-58](https://github.com/Dolibarr/dolibarr/assets/93765174/a62e59cb-c67e-4fd9-8d51-ae1f5cf96cad)

DejaVuSans

![2024-04-25_17-40](https://github.com/Dolibarr/dolibarr/assets/93765174/73576072-ffe4-4c3c-b024-b54fadca94f2)


@GildDart 
is position ok for you?

**Comment by GildDart** [comment]
![Capture d’écran 2024-04-25 à 17 16 32](https://github.com/Dolibarr/dolibarr/assets/24959970/1181a0b1-c79e-4697-a3b1-abc7fe70181b)

Could be a little lower and aligned at the right with the line above...

**Comment by fappels** [comment]
I put PR on draft, if you have better value for width and position I change in PR.

**Comment by GildDart** [comment]
@fappels  Where can I find the values ?

**Comment by sonikf** [comment]
@fappels
Initial code you proposed worked better, apart from 'Freemono' and 'freemono' problem what else was wrong with your tests?

@GildDart 
Did you test initial code proposal?
reposting with freemono correction....
```
	// Show page nb 
		$pdf->SetXY($dims['wk'] - $dims['rm'] - 18 - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_X', 0), -$posy - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_Y', 0));
		$pagination = $pdf->PageNo().' / '.$pdf->getAliasNbPages();
		if (in_array(pdf_getPDFFont($outputlangs), array('freemono',  'DejaVuSans'))) {
    		$pdf->MultiCell(30, 2, $pagination, 0, 'R', 0);
		} else {
    		$pdf->MultiCell(18, 2, $pagination, 0, 'R', 0);
		}
```

**Comment by fappels** [comment]
I pushed some correction, put 28 not 30, because think will have problem with doc more the 10 pages.
Also keep original alignment for standard font (others then freemone and DejaVuSans). Is patch for fix page numbering, not a patch for better alignment. Better alignment fix should be pushed only to V20.

**Comment by sonikf** [comment]
Hi @fappels 
ok much better now!

**Comment by GildDart** [comment]
@sonikf

Here is what I put...

`	// Show page nb only on iso languages (so default Helvetica font)

	$pdf->SetXY($dims['wk'] - $dims['rm'] - 18 - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_X', 0), -$posy - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_Y', 0));

	$pagination = $pdf->PageNo().' / '.$pdf->getAliasNbPages();

		if (in_array(pdf_getPDFFont($outputlangs), array('Freemono',  'DejaVuSans'))) {
    		$pdf->MultiCell(30, 2, $pagination, 0, 'R', 0);
		} else {
    		$pdf->MultiCell(18, 2, $pagination, 0, 'R', 0);
		}
`

instead of 

`	
	// Show page nb only on iso languages (so default Helvetica font)
	$pdf->SetXY($dims['wk'] - $dims['rm'] - 18 - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_X', 0), -$posy - getDolGlobalInt('PDF_FOOTER_PAGE_NUMBER_Y', 0));

	if (getDolGlobalString('PDF_USE_GETALIASNBPAGE_FOR_TOTAL')) {
		// $pagination = $pdf->getAliasNumPage().' / '.$pdf->getAliasNbPages(); 	// works with $pdf->Cell
		$pagination = $pdf->PageNo().' / '.$pdf->getAliasNbPages();	// seems to not works with all fonts like ru_UK
	} else {
		$pagination = $pdf->PageNo().' / '.$pdf->getNumPages();		// seems to always work even with $pdf->Cell. But some users has reported wrong nb (no way to reproduce)
	}

	$pdf->MultiCell(18, 2, $pagination, 0, 'R', 0);
`

**Comment by fappels** [comment]
I close this one, is now fixed in branch 18.
@sonikf & @GildDart , thanks for helping on this.
