### ISSUE TITLE
'llx_contact' table called instead of 'llx_socpeople' in categories export

### ISSUE THREAD

**Issue by Dartaban** [Dolibarr/dolibarr#2946]
Dans l'assistant export, Module " Tag/Catégories / List of contact tags/categories and contact " à l'étape 3 j'ai l'erreur suivante :

Dolibarr a détecté une erreur technique.
Type gestionnaire de base de données: mysql
Requête dernier accès en base en erreur: SELECT rowid as rowid, lastname as label FROM llx_contact
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHTABLE
Information sur le dernier accès en base en erreur: Table 'dolibarr.llx_contact' doesn't exist

La table 'Ilx_contact' est appelée au lieu de 'llx_socpeople'

**Comment by rdoursenaud** [comment]
Quelle version ?

**Comment by Dartaban** [comment]
3.7.0.
Désolé.

**Comment by rdoursenaud** [comment]
Pas de souci. Pouvez-vous vérifier que le défaut est encore présent en 3.7.1 (dernière version stable).
Merci !

**Comment by aspangaro** [comment]
J'ai vérifié, encore présent en develop donc surement dans la 3.7.1.

Par contre pas vu d'où vient le problème

**Comment by Dartaban** [comment]
Je confirme qu'en 3.7.1. le problème est toujours là.

**Comment by aspangaro** [comment]
Je viens de proposer un PR qui fonctionne sous une version develop. Non testé sur une 3.7 car pas d'instance sous la main.

**Comment by eldy** [comment]
Closed, since fixed into 3.8
