### ISSUE TITLE
We can no longer relate if the previously free format had not been initiated in YYYMM

### ISSUE THREAD

**Issue by cmfpmatik** [Dolibarr/dolibarr#29470]
### Bug

see that : https://github.com/Dolibarr/dolibarr/commit/65b0086cfb7b5cd666a1f523397f89bd9aac27ff

@klugfr said : 

Could it be possible to have a way to disable/enable this from the admin?

We've been naming our bank receipt according to the bank for years.
For this month we have for example: BPOP202310, SG202310, CIC202310, etc.

Forcing this change means changing our naming convention and that all bank receipts for the same month will have the same name (YYYYMM), less easy to read/check.

### Dolibarr Version

19

**Comment by akhamar** [comment]
Well I was looking deep in the code for a way to fix/bypass that.
Discovered that on develop there was a if statement allowing to bypass the restriction, looked at git history and found this issue thread !

Thanks @cmfpmatik for suggesting the fix and thanks @eldy to fixing that !

**Comment by akhamar** [comment]
@eldy could you please give the location where to set the value for `NW_RECEIPTNUMBERFORMAT` param ?
Also how this field/param works. Could you provide an example of values etc.

I know that this version is not yet available, but I'll setup the value for this param in advance for the next version.

**Comment by eldy** [comment]
> @eldy could you please give the location where to set the value for `NW_RECEIPTNUMBERFORMAT` param ?
> Also how this field/param works. Could you provide an example of values etc.
> 
> I know that this version is not yet available, but I'll setup the value for this param in advance for the next version.

Go into Home Setup Other to add the entry with value 1

**Comment by cmfpmatik** [comment]
[heart]         Benjamin de l'agence OARCES WEB reacted to your message:
________________________________

**Comment by akhamar** [comment]
Only available on 20.x, can it be ported to 19.x ?
