### ISSUE TITLE
migration dolibarr 

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2951]

**Comment by tiaris** [comment]
migration script has an error

Request 111 sql='ALTER TABLE llx_product_price ADD CONSTRAINT fk_product_price_user_author FOREIGN KEY (fk_user_author) REFERENCES llx_user (rowid);'
Erreur DB_ERROR_2013: ALTER TABLE llx_product_price ADD CONSTRAINT fk_product_price_user_author FOREIGN KEY (fk_user_author) REFERENCES llx_user (rowid);
Lost connection to MySQL server during query

error occurs when migrating migration 3.7 -> 3.7.1, if statrting from a 3.6 it works

**Comment by FHenry** [comment]
It's a problem of Mysql Version, not Dolibar, Edly explain that last time during DevCamp. Your mysql version must be at least 5.5.43 to not loose data if this mysql bug occurs. But to play correctly migration script if you still have error message (ARLTER TABLE => connexion lost), the only solution is to upgrade to mysql 5.6.*

**Comment by jfefe** [comment]
Yep @FHenry  it seems to be this case. 
@tiaris please take a look at https://github.com/Dolibarr/dolibarr/blob/3.7/ChangeLog and give us mysql client and server version.

**Comment by eldy** [comment]
The error "Lost connection to MySQL server" during an alter table is a bug in mysql 5.5.40+ (and not in dolibarr)
The only solution i found to avoid this is to upgrade to 5.6.\* or move to mariadb.

**Comment by tiaris** [comment]
I am not using a bugged version (I hope so...http://www.dolibarr.fr/86-actualites/annonces/188-la-version-3-7-de-dolibarr-n-a-pas-ete-publie-en-janvier-pourquoi)
server mysql version 5.5.41-0+wheezy1
driver mysqli (5.5.41)
Ok seen in changelog.

But if it is a version problem, why it works for a migration from 3.6 -> 3.7.1, and not with 3.7.0 to 3.7.1 on the same system (debian wheezy stable)

**Comment by hregis** [comment]
@tiaris 

peux-tu essayer en renommant les contraintes ?
(ex: fk_product_price_user_author ==> fk_product_price_fk_user_author)

ALTER TABLE  llx_product_price ADD CONSTRAINT fk_product_price_fk_user_author FOREIGN KEY (fk_user_author) REFERENCES  llx_user (rowid);

ALTER TABLE  llx_product_price ADD CONSTRAINT fk_product_price_fk_product FOREIGN KEY (fk_product) REFERENCES  llx_product (rowid);

sinon la migration de mysql à mariadb est très simple : 

https://www.abyssproject.net/2014/07/migrer-mysql-vers-mariadb/

**Comment by hregis** [comment]
en fait il faudrait rajouter un DROP de ces 2 contraintes avant de faire un ALTER TABLE sinon mysql plante. Avec MariaDB pas de soucis, il dit bien que les contraintes existent déjà.

**Comment by hregis** [comment]
see this PR https://github.com/Dolibarr/dolibarr/pull/2980

**Comment by simnandez** [comment]
Closed by #2980
