### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by zahwyrix** [Dolibarr/dolibarr#29526]
### Bug

When I link an .htaccess to my Dolibarr, none of the Dolibarr external modules work. It returns an internal 500 error.
Content of htaccess:
```
#PHP 8.1 : 
<FilesMatch \.php$>
SetHandler application/x-httpd-php81
</FilesMatch>
AddHandler application/x-httpd-php81 .php
suPHP_ConfigPath /home/********/*********
```

Content of php.ini :

```
[PHP]

; Basic directives
allow_url_fopen = On
default_charset = "UTF-8"
expose_php = On
file_uploads = On
short_open_tag = On
display_errors = Off
include_path = ".:/opt/alt/php81/usr/share/pear"

; Error handling
error_reporting = E_ALL
log_errors = On
error_log = "/home/**********/*******/logs/**********.log"

; Data handling
max_input_time = 3600
max_input_vars = 250000
post_max_size = 512M
upload_max_filesize = 512M

; Execution time
max_execution_time = 3600
default_socket_timeout = 3600
memory_limit = 2048M
output_buffering = 4096

; Date and Timezone
date.timezone = "Europe/Paris"

; Session management
session.save_path = "/opt/alt/php81/var/lib/php/session"
session.gc_maxlifetime = 28800

; Extensions
extension=mysqlnd.so
extension=nd_mysqli.so
extension=nd_pdo_mysql.so
extension=json.so
extension=intl.so
extension=mcrypt.so
extension=gd.so
extension=xml.so
extension=xmlreader.so
extension=xmlrpc.so
extension=xmlwriter.so
extension=soap.so
extension=tidy.so
extension=bcmath.so
extension=dom.so
extension=fileinfo.so
extension=imap.so
extension=zip.so
extension=mbstring.so
extension=imagick.so
extension=pdo.so
```

This poses a real problem for me, since I need php ini to manage session times and timeouts in particular.

### Dolibarr Version

19.0.1

### Environment PHP

PHP 8.1

### Steps to reproduce the behavior and expected behavior

Create an .htaccess with this content in a Dolibarr parent directory

**Comment by sonikf** [comment]
Hi @zephyriony 
This is not a bug.
A 500 error is a generic response and indicates a misconfiguration on your part.
Also i noticed you use suPHP, why? What is your distro and version?
suPHP has been removed from Debian/Ubuntu distros for nearly a decade because is unmaintained and insecure..
https://smarsching.github.io/suphp/Home.html
