### ISSUE TITLE
warning on migration /install/upgrade2.php

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2952]
Migration des évènements pour ajouter les propriétaires dans la table des utilisateurs assignés
Déjà migré
( ! ) Notice: Undefined variable: res in /home/jean/projets/EnvTest/doli37/htdocs/install/upgrade2.php on line 3831
Call Stack
# Time    Memory  Function    Location

1   0.0199  961736  {main}( )   ../upgrade2.php:0
2   0.4249  11452144    migrate_reload_modules( )   ../upgrade2.php:385

**Comment by rdoursenaud** [comment]
Version ?

**Comment by marcosgdf** [comment]
Duplicate of #2861
