### ISSUE TITLE
Error on Alter table llx_payment_salary migration script 3.7.0 to 3.8.0

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#2953]
Hi
On **htdocs/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=3.7.0&versionto=3.8.0**
there is this error 
[
Version du serveur de base de données  5.5.43-0+deb8u1
Choix du script de migration    3.7.0-3.8.0.sql
Request 1 sql='UPDATE llx_facture_fourn set ref=rowid where ref IS NULL;'
Request 2 sql='ALTER TABLE llx_facture_fourn MODIFY COLUMN ref varchar(255) NOT NULL;'
Request 3 sql='insert into llx_c_tva(rowid,fk_pays,taux,recuperableonly,localtax1,localtax1_type,localtax2,localtax2_type,note,active) values (211, 21, '0','0',0,0,0,0,'IVA Rate 0',1);'
Request 4 sql='insert into llx_c_tva(rowid,fk_pays,taux,recuperableonly,localtax1,localtax1_type,localtax2,localtax2_type,note,active) values (212, 21, '18','0',7.5,2,0,0,'IVA standard rate',1);'
Request 5 sql='insert into llx_c_tva(rowid,fk_pays,taux,recuperableonly,note,active) values ( 2131, 213, '5', '0', 'VAT 5%', 1);'
Request 6 sql='ALTER TABLE llx_societe_rib ADD COLUMN rum varchar(32) after default_rib;'
Request 7 sql='ALTER TABLE llx_societe_rib ADD COLUMN frstrecur varchar(16) default 'FRST' after rum;'
Request 8 sql='create table llx_loan(rowid integer AUTO_INCREMENT PRIMARY KEY,entity integer DEFAULT 1 NOT NULL,datec datetime,tms timestamp,label varchar(80) NOT NULL,fk_bank integer,capital real default 0 NOT NULL,datestart date,dateend date,nbterm real,rate double NOT NULL,note_private text,note_public text,capital_position real default 0,date_position date,paid smallint default 0 NOT NULL,accountancy_account_capital varchar(32),accountancy_account_insurance varchar(32),accountancy_account_interest varchar(32),fk_user_author integer DEFAULT NULL,fk_user_modif integer DEFAULT NULL,active tinyint DEFAULT 1 NOT NULL)ENGINE=innodb;'
Request 9 sql='create table llx_payment_loan(rowid integer AUTO_INCREMENT PRIMARY KEY,fk_loan integer,datec datetime,tms timestamp,datep datetime,amount_capital real DEFAULT 0,amount_insurance real DEFAULT 0,amount_interest real DEFAULT 0,fk_typepayment integer NOT NULL,num_payment varchar(50),note_private text,note_public text,fk_bank integer NOT NULL,fk_user_creat integer,fk_user_modif integer)ENGINE=innodb;'
Request 10 sql='ALTER TABLE llx_extrafields ADD COLUMN fieldrequired integer DEFAULT 0;'
Request 11 sql='ALTER TABLE llx_extrafields ADD COLUMN perms varchar(255) after fieldrequired;'
Request 12 sql='ALTER TABLE llx_extrafields ADD COLUMN list integer DEFAULT 0 after perms;'
Request 13 sql='ALTER TABLE llx_payment_salary ADD COLUMN salary real after datev;'
Request 14 sql='ALTER TABLE llx_payment_salary ADD INDEX idx_payment_salary_ref (num_payment);'
Erreur DB_ERROR_1072: ALTER TABLE llx_payment_salary ADD INDEX idx_payment_salary_ref (num_payment);
Key column 'num_payment' doesn't exist in table
Request 15 sql='ALTER TABLE llx_payment_salary ADD INDEX idx_payment_salary_user (fk_user, entity);'
Request 16 sql='ALTER TABLE llx_payment_salary ADD INDEX idx_payment_salary_datep (datep);'
Request 17 sql='ALTER TABLE llx_payment_salary ADD INDEX idx_payment_salary_datesp (datesp);'
Request 18 sql='ALTER TABLE llx_payment_salary ADD INDEX idx_payment_salary_dateep (dateep);'
Request 19 sql='ALTER TABLE llx_payment_salary ADD CONSTRAINT fk_payment_salary_user FOREIGN KEY (fk_user) REFERENCES llx_user (rowid);'
Request 20 sql='UPDATE llx_projet_task_time SET task_datehour = task_date where task_datehour IS NULL;'
]

**Comment by ozit** [comment]
Thanks for the labels, the DB_ERROR is still here with the actual Developp sources

**Comment by marcosgdf** [comment]
Can't reproduce.

**Comment by ozit** [comment]
After days, I've tryed to delete the empty table and the migration script create it again. Now, the script don't blocked on it. It was an old Dolibarr version I upgraded, may be the table was not with the correct structure. I close the issue. Thanks
