### ISSUE TITLE
International text appearance "&aacute;"

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#29536]
### Bug

In pdf_cyan.modules.php when a document is electronically signed, the word "Aláírás" appears as `Al&aacute;&iacute;r&aacute;s:`

### Dolibarr Version

20.0.0-alpha

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 20.0.0-beta
Feel free to reopen it if it's not
