### ISSUE TITLE
[3.7.1] Unable to "Déposer un chèque"

### ISSUE THREAD

**Issue by jpyrat** [Dolibarr/dolibarr#2961]
Quand je clique sur nouveau dépôt ou liste, j'ai : 
The requested URL /compta/paiement/cheque/fiche.php was not found on this server.

http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/53223-3-7-1-remises-de-cheques-impossible state : replace fiche.php by card.php

**Comment by aspangaro** [comment]
Bonjour,

Vous utilisez un thème en particulier ? Je n'ai pas retrouvé ce bug sur une version 3.7.

**Comment by eldy** [comment]
If you use the auguria menu manager, try to disable it by switching to eldy menu then go back to auguria.

**Comment by jpyrat** [comment]
I use "bureau2crea" (the only one with hovering on table lines (mandatory on screen 1920 wide).

Same isue with eldy, and auguria.

Hint : i use svn sw https://github.com/Dolibarr/dolibarr.git/tags/3.7.1/htdocs to update dolibarr since 2 years (works like a charm).

**Comment by jpyrat** [comment]
I've done this to correct the isue : 
UPDATE `llx_menu` SET `url` = '/compta/paiement/cheque/card.php?leftmenu=checks&amp;action=new' WHERE `llx_menu`.`rowid` =1796;
UPDATE `mydatabase`.`llx_menu` SET `url` = '/compta/paiement/cheque/list.php?leftmenu=checks' WHERE `llx_menu`.`rowid` = 1797;

Here is the content of these to line : 
1796    auguria 1       left    accountancy     1795    NULL    NULL    0   /compta/paiement/cheque/card.php?leftmenu=checks&amp;action=new     NewCheckDeposit compta  1   $user->rights->banque->lire ! empty($conf->banque->enabled) && (! empty($conf->facture->enabled)) || ! empty($conf->global->MAIN_MENU_CHEQUE_DEPOSIT_ON)    2   09/06/2015 13:40
1797    auguria 1       left    accountancy     1795    NULL    NULL    1   /compta/paiement/cheque/list.php?leftmenu=checks        List    bills   1   $user->rights->banque->lire ! empty($conf->banque->enabled) && (! empty($conf->facture->enabled)) || ! empty($conf->global->MAIN_MENU_CHEQUE_DEPOSIT_ON)    2   09/06/2015 13:51

**Comment by eldy** [comment]
bureau2cra is the theme. I am speaking about the "menu manager". Do you use auguria (into setup - menu) ?

**Comment by jpyrat** [comment]
This was the trick. Thanx !
