### ISSUE TITLE
Reverse movement

### ISSUE THREAD

**Issue by Madeuh** [Dolibarr/dolibarr#29622]
### Bug

On the movement module, if you check a movement and choose "reverse", if you select "no" for the action, the movement is still canceled.

The "reverse" function cancels the movement line but does not recalculate the stock of the item.

### Dolibarr Version

19.0.2

**Comment by mannybiker** [comment]
Sorry, but what about the part of the bug: "The "reverse" function cancels the movement line but does not recalculate the stock of the item." ? I think only the first part of the issue has been fixed but not the recalculation. Am I wrong?
