### ISSUE TITLE
Document Generation with ODT Template leads http 500 error

### ISSUE THREAD

**Issue by joetheinventor** [Dolibarr/dolibarr#29632]
### Bug

It happens only in v19
As it happens in most modules, it does not happen in all entries.
For example we have multiple BOMS, only some BOMS is not able generate document and gives http 500 error.

### Dolibarr Version

19.02

### Environment PHP

7.4.33

### Steps to reproduce the behavior and expected behavior

Open a project or a BOM, create document with ODT template.

**Comment by joetheinventor** [comment]
It happens due to external module (CustomTabs)

**Comment by eldy** [comment]
> It happens due to external module (CustomTabs)

I can't reproduce with 19.0.3. So the clue of @joetheinventor about the external module is probably good. To be sure, may be you can add your odt template file so we are sure to test with same case.
