### ISSUE TITLE
Allow adding multiple contacts on events

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2963]
We can now affect events to multiple users, allowing affectation of multiple contacts (and third parties) seem reasonable. (Task about Contact/Task about company fields).

**Comment by glu000** [comment]
This is implemented with dolibarr 7

**Comment by choybe** [comment]
No still in version 9 only one third party can be chosen - there is no multiple choice
and consequently only the contacts of the chosen third party are addable 
but what to do when you have multiple partie meeting with more than one third party contacts?
