### ISSUE TITLE
Email Headers Included in Email Body when Using "Send Email" Button in Tickets

### ISSUE THREAD

**Issue by hcal** [Dolibarr/dolibarr#29648]
### Description:
I have encountered an issue where emails sent using the "Send Email" button from the ticket interface in our Dolibarr system include email header information directly in the email body. This results in recipients seeing technical email headers mixed with the intended message content, which is confusing and unprofessional.

### Dolibarr Version

19.0.1

### Environment PHP

8.0.30

### Environment Database

MySQL or MariaDB 10.5.22-MariaDB

### Version:
Dolibarr 19.0.1

### Expected Behavior:
Emails sent from Dolibarr should not display SMTP header information or other technical metadata within the body content visible to the email recipients. The email body should only contain the intended message content.

### Actual Behavior:
When using the "Send Email" button in the ticket interface, the emails include SMTP headers like Mime-Version, Content-Type, and various other headers and boundary identifiers within the body of the email. However, other automated emails from the system, such as new ticket notifications and other system-generated emails, do not exhibit this issue and are formatted correctly.

### Steps to Reproduce:
1. Open a ticket in the Dolibarr system.
2. Use the "Send Email" button to send an update or information to a recipient.
3. Check the received email in any standard email client.

### Example Email Showing the Issue:

```
helpdesk@<REDACTED> via us-east-2.amazonses.com 
Wed, May 8, 10:55 AM (2 days ago)
to me

References <REDACTED>
Reply-To: helpdesk@<REDACTED>
X-Mailer: Dolibarr version 19.0.1 (using SMTPs Mailer)
X-Dolibarr-Option: MAIN_MAIL_USE_MULTI_PART
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="REDACTED"
Content-Transfer-Encoding: 8bit
Feedback-ID: REDACTED
X-SES-Outgoing: REDACTED

--REDACTED
Content-Type: multipart/alternative; boundary="REDACTED"

--REDACTED
Content-Type: text/plain; charset=UTF-8

Hello,
A new answer has been added to a ticket that you follow. Here is the message: Hello

Sincerely
```

### Additional Information:

- The issue has been specifically observed when using the "Send Email" button within tickets.
- Email setup uses Amazon SES for sending.
- The problem has not been noted in other types of automated or manually triggered emails from the system.

I was unable to find a reference to this issue online.  Is it a known issue and if so, is there a fix or workaround?  If it is not a bug do I have a misconfiguration somewhere?

**Comment by nicolasVr** [comment]
I have exactly the same problem. My version is 18.0.5 (managed by Dolizen). Emails are sent via SMTP (ovh)  Have you found a solution ?

**Comment by nicolasVr** [comment]
Further testing shows that the problem exists only when answering a ticket created by email collector, not when the ticket is created inside Dolibarr.
When the ticket is opened as an answer to a mail, there is an empty line in the headers before the line"`References <0dd9ae1d-f18b-4ff5-a391-6d7b75675b33@xxx.fr>` I think is what makes the file misreaded by mailreader.

**Comment by hcal** [comment]
I'm pleased to report that after updating to version 19.0.2, the issue we were experiencing appears to be     
resolved. It was the first thing we checked post-update, and everything seems to be functioning correctly now.

I'll be closing this ticket as the problem seems to have been addressed in the latest release. However, if  you (or anyone else)  continues to encounter similar issues, please don't hesitate to open a new ticket or comment here, and 
I can revisit this one.                                                                                       

Separately, we've noticed that replies to certain emails are generating new tickets instead of appending to   
existing ones. I believe this to be a different issue and will look into it further.

**Comment by nicolasVr** [comment]
I can confirm that v19.0.2 solve the problem. I am surprised that this bug have "survived" till v 18.0.5.
