### ISSUE TITLE
db_error=Unknown column 'alle' in 'where clause' since Update to  Maintainance 19.0.2

### ISSUE THREAD

**Issue by tschupo** [Dolibarr/dolibarr#29650]
### Bug

While changing Connected Project in Invoice the following Error comes up:

2024-05-10 21:05:50 ERR     95.90.199.52    DoliDBMysqli::query Exception in query instead of returning an error: Unknown column 'alle' in 'where clause'
2024-05-10 21:05:50 ERR     95.90.199.52    DoliDBMysqli::query SQL Error query: SELECT p.rowid, p.ref, p.title, p.fk_soc, p.fk_statut, p.public, s.nom as name, s.name_alias FROM llx_projet as p LEFT JOIN llx_societe as s ON s.rowid = p.fk_soc WHERE p.entity IN (1) AND (p.fk_soc IN (6,alle) OR p.fk_soc IS NULL) ORDER BY p.ref ASC
2024-05-10 21:05:50 ERR     95.90.199.52    DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'alle' in 'where clause'
2024-05-10 21:05:50 ERR     95.90.199.52    Error url=/compta/facture/card.php?action=classify&amp;token=b8369ad819581682014adfcee21ef070&amp;id=296, query_string=action=classify&amp;token=b8369ad819581682014adfcee21ef070&amp;id=296, sql=SELECT p.rowid, p.ref, p.title, p.fk_soc, p.fk_statut, p.public, s.nom as name, s.name_alias FROM llx_projet as p LEFT JOIN llx_societe as s ON s.rowid = p.fk_soc WHERE p.entity IN (1) AND (p.fk_soc IN (6,alle) OR p.fk_soc IS NULL) ORDER BY p.ref ASC, db_error=Unknown column 'alle' in 'where clause'

The Error appears in duplicated/Prov invoices and also in live invoices. 

### Dolibarr Version

19.0.2

### Environment PHP

8.1.27

### Environment Database

MySQL or MariaDB 10.11.4-MariaDB-1:10.11.4+maria~deb11-log

### Steps to reproduce the behavior and expected behavior

In Tab Invoices, Customer-Invoices
Headlines just under Customer, the connected project click "pencil", then the Error appears

### Attached files

[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/15280317/dolibarr.log)

**Comment by frederic34** [comment]
@tschupo what is your projetc module setup ?
![image](https://github.com/Dolibarr/dolibarr/assets/3624836/babdc1aa-acfa-48a3-8fa1-83c73313e52a)

**Comment by atm-florianm** [comment]
I think this is a translation problem. The German translation reads:

> `AllowToLinkFromOtherCompany=Element mit einem Projekt einer anderen Firma verknüpfen <br> <br> <u> Unterstützte Werte: </u> <br>- Leer lassen: Kann Elemente mit beliebigen Projekten in derselben Firma verknüpfen (Standard) <br>- "alle": Verknüpfung mit allen Projekten, auch denen  anderer Unternehmen  <br>- Eine durch Kommas getrennte Liste von Drittanbieter-IDs: kann Elemente mit beliebigen Projekten dieser Drittanbieter verknüpfen (Beispiel: 123,4795,53) `

`all` should have been kept as is and not translated, but I'm not blaming the translators because this is not obvious.


German is not the only language where `all` was translated (I sampled some of the langs files: `es_CU` and `sw_SW` have it too, I didn't look at all of them but it is very likely that more translation files have this issue).

**Comment by tschupo** [comment]
> @tschupo what is your projetc module setup ? ![image](https://private-user-images.githubusercontent.com/3624836/330682054-babdc1aa-acfa-48a3-8fa1-83c73313e52a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzQzNDQsIm5iZiI6MTcxNTg3NDA0NCwicGF0aCI6Ii8zNjI0ODM2LzMzMDY4MjA1NC1iYWJkYzFhYS1hY2ZhLTQ4YTMtOGZhMS04M2M3MzMxM2U1MmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTU0MDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM5MWVmZTQ2M2Y2YTBiYTA4NmY3YTc1MWRjNWQ2ZWRkZDJjMzUyYmM0Y2Q5Y2JiNWE2NjkyZTdjMzRlN2NmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NoZLQ_MMwB3K5yjs9KQnDDqsVLGpQOV3EYw0Uc8KtAc)

That was exactly the Problem. 😀
Thanks a lot for your quick help!!

**Comment by tschupo** [comment]
> I think this is a translation problem. The German translation reads:
> 
> > `AllowToLinkFromOtherCompany=Element mit einem Projekt einer anderen Firma verknüpfen <br> <br> <u> Unterstützte Werte: </u> <br>- Leer lassen: Kann Elemente mit beliebigen Projekten in derselben Firma verknüpfen (Standard) <br>- "alle": Verknüpfung mit allen Projekten, auch denen  anderer Unternehmen  <br>- Eine durch Kommas getrennte Liste von Drittanbieter-IDs: kann Elemente mit beliebigen Projekten dieser Drittanbieter verknüpfen (Beispiel: 123,4795,53) `
> 
> `all` should have been kept as is and not translated, but I'm not blaming the translators because this is not obvious.
> 
> German is not the only language where `all` was translated (I sampled some of the langs files: `es_CU` and `sw_SW` have it too, I didn't look at all of them but it is very likely that more translation files have this issue).

Yes! With "all" filled in the form field it works perfect again.
Thanks für your Help, too! 😀
