### ISSUE TITLE
Password encryption should be enabled by default

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2968]
- **URL**: /admin/security.php

Storing user passwords in plain text is so _dangerous_ and **plain wrong**.

The corresponding setting is
"Do no store clear passwords in database but store only encrypted value (Activated recommended)"

I even believe that we should remove the plain text field altogether.

**Comment by tomours** [comment]
Hi,

I was actually surprised that I had to activate this.
I agree, and I think this should be also applied to the setting "Encrypt db password in conf.php file", that is just under.

**Comment by eldy** [comment]
We still need the plain text field because a lot integration with external system stil need it.
I agree however that we should have this option set to on by default.
