### ISSUE TITLE
Loss of filter set on list pages

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#29698]
### Bug

I have migrated from version 16.05 to 19.02 and I have detected a malfunction when applying the filtering in the listing pages.

After making a list (projects, products, etc.), having applied some kind of filter, for example categories, we can access any element of the list and work with it. However, when we go back to the page with the list, the filter that we had applied disappears, having to set the filter again, resulting in a much longer and tedious task. 

### Dolibarr Version

19.0.2

### Environment PHP

7.4.23

### Environment Database

MariaDB 11.3.2

### Steps to reproduce the behavior and expected behavior

Display a page with a list of products, set a filter by category, access any of the items in the list and now return to the list page. The filter has disappeared and all unfiltered items are displayed again.

**Comment by frederic34** [comment]
try
![image](https://github.com/Dolibarr/dolibarr/assets/3624836/8bead1ad-16c3-4606-b355-ad0cad17eabf)

this happen since https://github.com/Dolibarr/dolibarr/commit/1552fac711177f376dee15e39812107619d681db
