### ISSUE TITLE
Failed to load doc generator Error when trying to make a Manufacturing Order for a Bill of Materials in Dolibarr 19.0.1

### ISSUE THREAD

**Issue by stevenadaniel60** [Dolibarr/dolibarr#29699]
### Bug

Trying to make a Manufacturing Order for a Bill of Materials. When I create the MO and then try to Validate it, It says "Validated (To produce)" but this Error comes up. "Error Failed to load doc generator with modelpaths=core/modules/mrp/doc/ - modele=alpha" The demand for the parts in the BOM do not show up in the Replenishment tab when it should show how much is needed to be ordered to meet the new manufacturing demand. 
![image 2](https://github.com/Dolibarr/dolibarr/assets/169934199/26afa590-5636-4cbe-ae55-1d2f2bc52fc9)
![image 1](https://github.com/Dolibarr/dolibarr/assets/169934199/25a92e00-7b5c-464e-91c8-0b45705d3ec8)

### Dolibarr Version

19.0.1

### Steps to reproduce the behavior and expected behavior

I chose a BOM and then selected "Create MO" then selected how many I wanted to produce and selected "Validate" Then the statuse would change to "Validated (To produce)" and the Error line would pop up.

### Attached files

![image 2](https://github.com/Dolibarr/dolibarr/assets/169934199/508e50d6-536d-4e23-ad6e-02276e61eb15)
![image 1](https://github.com/Dolibarr/dolibarr/assets/169934199/d32ec36c-1427-4655-a9fc-8563d302653d)

**Comment by byte123** [comment]
How did you solve it ?

**Comment by zeug-it** [comment]
Had the same Error @byte123  - there was no default / german standard set for the template 

![Image](https://github.com/user-attachments/assets/c30fc50c-7188-4072-87a2-4f03ba39ecb5)
