### ISSUE TITLE
Reordering lines in proposals are not permanent

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#29714]
### Bug

After reordering (drag'n drop) lines, the changes are not permanent (not written to the database).

### Dolibarr Version

20.0.0-alpha

**Comment by atm-maxime** [comment]
Hi ! Thanks for your feedback. I can't reproduce in the 20 beta version, can you check ?

**Comment by vanyolai** [comment]
Hello, thanks for checking it. Looks like in the beta version the bug is gone.
