### ISSUE TITLE
Webservices doesn't work with PHP 5.6

### ISSUE THREAD

**Issue by jfefe** [Dolibarr/dolibarr#2973]
Since HTTP_POST_RAW_DATA is deprecated into PHP 5.6, nusoap seems to be broken :(

Here is a beginning of replacement for SOAP PHP native methods : https://github.com/aternatik/dolibarr/commit/eba4269c1a3625de7cdac3647d2858540f7929b4

Please anyone can confirm this (critical) bug?

**Comment by eldy** [comment]
Yes HTTP_POST_RAW_DATA is deprecated and must be replaced with php://input
deprecated in 5.6 and removed in php 7.

**Comment by jfefe** [comment]
Yep @eldy but with nuSoap I always get warnings "Missing argument 1..." error when calling any webservices method... so it doesn't work, even when tweak php.ini to avoid these warning .

**Comment by FHenry** [comment]
I try on customer server, and I can't reproduce the famous Missing argument 1... with PHP 5.6.1 on Dolibarr 3.6

**Comment by rdoursenaud** [comment]
Anyway, this may be a good time to migrate to [PHP's native SOAP extension](https://secure.php.net/manual/book.soap.php).

Looks like last version of NuSOAP is from 2011 and unmaintained.
The PHP SOAP extension has been introduced in PHP 5.0.1 and is now mature.
Since our minimum requirements is PHP 5.3, the switch should be a no-brainer.

**Comment by jfefe** [comment]
ok @rdoursenaud you can assign it to me for next version (3.9)
But to achieve this goal, we are missing a tool to generate wsdl (webservices descriptor), which isn't present into PHP's native SOAP extension.

**Comment by rdoursenaud** [comment]
@jfefe That's exactly what SCA is for.
https://secure.php.net/manual/en/book.sca.php
http://www.ibm.com/developerworks/library/ws-soa-scasdo/

**Comment by eldy** [comment]
I recommand instead to work on using json services to replace web services.

**Comment by tiaris** [comment]
I suggest to use php webservices.
look for a tool to generate wsdl, or write a php script to do it...
or try https://code.google.com/p/php-wsdl-creator/

**Comment by rdoursenaud** [comment]
@eldy Could you elaborate on that? Never heard of json services before.

**Comment by eldy** [comment]
Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?
