### ISSUE TITLE
Bug: Fatal error: Uncaught Error: Function name must be a string

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#29740]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
When opening the report section for Turnover invoiced by customer in accounting menu, I have the following message : 

Fatal error: Uncaught Error: Function name must be a string in /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/compta/stats/casoc.php:638 Stack trace: #0 {main} thrown in /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/compta/stats/casoc.php on line 638

or 

If I asked for turnover invoiced : the April month is providing me an error

Warning: Division by zero in /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/compta/stats/index.php on line 465
+INF%

## Environment
- **Version**: 19.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.33
- **Database**: MySQL or MariaDB 5.5.5-10.4.25-MariaDB-1:10.4.25+maria~stretch-log
- **URL(s)**: /compta/stats/casoc.php?leftmenu=accountancy_report&modecompta=BOOKKEEPING

## Expected and actual behavior
Should get the customer turnover breakdown but I don't have any report.

## Steps to reproduce the behavior
When opening the report section for Turnover by customer in accounting menu, choose turnover by customer
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![2024-05-22_18-28-11](https://github.com/Dolibarr/dolibarr/assets/58973675/228f1bbd-49e2-493e-aa5e-1b90c24710a9)

![2024-05-22_18-27-19](https://github.com/Dolibarr/dolibarr/assets/58973675/955182dc-fd8e-4cef-af53-84c46147d666)

**Comment by pierrehenrymuller** [comment]
I have this bug too and I confirm that the patch is working.

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.

**Comment by fpav** [comment]
Not fully fixed the following error is still remaining :

If I asked for turnover invoiced : the April month is providing me an error

Warning: Division by zero in /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/compta/stats/index.php on line 465
+INF%

**Comment by fpav** [comment]
Sorry but it still alive for one of them, one is solved but the other is not, I don’t know how to reopen so I made another comment on the same one.

Thanks for your help,


 <https://mysig.io/gA0rg8qb>	
Franck PAVAN 
General Manager EUROCOM
☎️ : +33 661 573 000 <tel:+33 661 573 000>
🌐 : www.red-limo.com <https://www.red-limo.com/>
✉️ : ***@***.*** ***@***.***>
📬 : 6 Chemin des Garennes 31260 Touille - France
 <https://www.linkedin.com/in/franck-pavan-b6493013/>
 <https://mysignature.io/editor/?utm_source=expiredpixel>
 ***@***.***/>
	Please consider the environment before printing this email
IMPORTANT: The contents of this email and any attachments are confidential. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.
