### ISSUE TITLE
Bug: "Salaries" section in compta/resultat/clientfourn.php is not translated

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2974]
Version: 3.6.2
URL: /compta/resultat/clientfourn.php?year=2015&month=4&modecompta=CREANCES-DETTES

![captura de pantalla 2015-06-06 a las 9 39 08](https://cloud.githubusercontent.com/assets/168744/8018843/f76f61ce-0c2f-11e5-9cbd-2df5cc4ae632.png)

**Comment by rdoursenaud** [comment]
Token exists in langs/en_US/salaries.lang in 3.6.3 and up.
Translator needs to provide the translation at transifex.com.

**Comment by simnandez** [comment]
The translation at transifex.com is provided a year ago... 
Anyway I think is a bad idea report bugs for a old version (in this case a bug for 3.6.2 when 3.6.3 came out two months ago...)

**Comment by marcosgdf** [comment]
@simnandez I see... 3.6.3 was never announced so I didn't know about it. ¯_(ツ)_/¯

**Comment by braito4** [comment]
Actually the last version published is 3.6.4
https://github.com/Dolibarr/dolibarr/releases

**Comment by rdoursenaud** [comment]
Official releases are at [sourceforge](http://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/).
3.6.4 is still considered unreleased at this point.

If you ask me, I think the current (undocumented) release process is messy and unclear.
I drafted my ideal release process on the [wiki](http://wiki.dolibarr.org/index.php/ReleaseProcess) but didn't have the time to work more on it yet. It's in my TODO list but very far from the top.
Comments and help appreciated ;)

(Sorry for the issue hijacking, couldn't resist…)

**Comment by accett** [comment]
Hi everyone!

I don't understand then.

3.7.0 is not official? Is beta?

3.6.3 then is the current oficial?

3.7.0 is another branch?

Why have 2 current official versions 3.6.3 and 3.7.0?

What are the difference between both?

Where can I read about this changes?

Thanks.

**Comment by marcosgdf** [comment]
@accett If you have any question about releases, just check the wiki or drop a mail at the developers list.
