### ISSUE TITLE
Focus supplier invoice ref. after cloning a supplier invoice

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2975]
When we clone a supplier invoice, the first thing to do is edit the ref field, but it does not have input focus. It would save some time if the input is automatically focused after cloning an invoice.

**Comment by rdoursenaud** [comment]
There's a lot of places in Dolibarr that could benefit from autofocusing on the right form field.

Here's what I gathered so far:
- [ ] New product/service
- [ ] New warehouse
- [ ] New proposal
- [ ] New order
- [ ] New contract
- [ ] New intervention (second step after third party selection)
- [ ] New customer invoice
- [ ] New supplier invoice
- [ ] New donation
- [ ] New contribution (social contributions submenu)
- [ ] New payment (sales tax submenu)
- [ ] New financial account
- [ ] New deposit (check deposits)
- [ ] New project
- [ ] New task
- [ ] Make a leave request
- [ ] New expense report
- [ ] New emailing
- [ ] New member
- [ ] New member type
- [ ] …
