### ISSUE TITLE
Typo in "comments" filter on accountancy/expensereport/lines.php

### ISSUE THREAD

**Issue by adlmr** [Dolibarr/dolibarr#29756]
### Bug
Dolibarr 19.0.2

On accountancy/expensereport/lines.php (Lignes de notes de frais liées), using the "comments" filter returns the following error: `Unknown column 'er.comments' in 'where clause'` .
The "comment" filter works perfectly on accountancy/expensereport/list.php (Lignes de notes de frais à lier).

It looks like a typo as a **D** is missing on the filter

in accountancy/expensereport/lines.php: SQL SELECT statement contains  er**d**.comments
https://github.com/Dolibarr/dolibarr/blob/d62bd87f067bff51cfae8323967d0430af4307d3/htdocs/accountancy/expensereport/lines.php#L196
but filter is natural_search("er.comments", $search_desc); https://github.com/Dolibarr/dolibarr/blob/d62bd87f067bff51cfae8323967d0430af4307d3/htdocs/accountancy/expensereport/lines.php#L222
in accountancy/expensereport/list.php , you can see that the filter contains er**d** : 
https://github.com/Dolibarr/dolibarr/blob/d62bd87f067bff51cfae8323967d0430af4307d3/htdocs/accountancy/expensereport/list.php#L267

### How to fix
replace "er" by "erd" on line 222:
https://github.com/Dolibarr/dolibarr/blob/d62bd87f067bff51cfae8323967d0430af4307d3/htdocs/accountancy/expensereport/lines.php#L222

**Comment by aspangaro** [comment]
Thanks, fix proposed !
