### ISSUE TITLE
Missing automatic activation of the "canelle" pdf module for supplier invoice

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#29765]
### Bug

![image](https://github.com/Dolibarr/dolibarr/assets/3288514/68fadc8b-8663-4799-b3be-54607291620c)

### Dolibarr Version

19.0.2

**Comment by aspangaro** [comment]
Hello @lmag , in my opinion, it's not a bug, this is deliberate because it's better to load real invoices rather than generate facsimiles that have no legal value.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/blob/06579013df8bed3e9499a489c4891bc93e2d9672/htdocs/core/modules/modFournisseur.class.php#L101-L108

**Comment by lmag** [comment]
Thank you so much for your Answer I found this proposion very strange ! Changing a behavior depending on the element is not very intuitive for ordinary people.
