### ISSUE TITLE
SQL errors are registered as Warnings and not Errors

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2977]
Version: 3.6.2

**Comment by marcosgdf** [comment]
I see that in the code, SQL errors are logged as Warnings in the code. Is that expected?

**Comment by rdoursenaud** [comment]
That's strange indeed.
ping @eldy.

**Comment by eldy** [comment]
Is is true with dev too ?
I can't reproduce.

**Comment by marcosgdf** [comment]
No, it doesn't happen in dev. But the bug report is for 3.6.2.

Should it be closed?
