### ISSUE TITLE
MAIN_SECURITY_FORCERP - HTTP_REFERER

### ISSUE THREAD

**Issue by atm-irvine** [Dolibarr/dolibarr#29780]
### Bug

Because of the MAIN_SECURITY_FORCERP set by default on strict-origin, in v19, it's impossible to keep the list filter in the URL when you clic on "return list" from an object.
Because of this, HTTP_REFERER is equal to the domain name only and not the page you was from.
In v18, MAIN_SECURITY_FORCERP is set on same-origin and the filters are kept when you clic on "Return list" from an object.
HTTP_REFERER works fine.
I would like to know the reasons of this modification.
Normally, it should be the same problem for all users v19.
Will this have any impact on safety ?

### Dolibarr Version

19.0

**Comment by ksar-ksar** [comment]
https://www.dolibarr.fr/forum/t/memoire-filtre-de-recherche/46100

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/issues/29698
