### ISSUE TITLE
No option for creating purhcase order from sales order, for some cases only

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#29782]
### Bug

There is a feature that makes it possible to create a purchase order directly from the sales order, but is same cases that option does not appear, and I can't see any pattern in this behavior. I can't say anything else than sometimes the option is not there.

### Dolibarr Version

19.0.2

### Environment PHP

7.4

### Environment Database

MariaDB version 10.11.6

**Comment by ns-info90** [comment]
Hello

Do you have a specific module for this operation?

**Comment by hasse-basse** [comment]
Hi

Isn't it core? Or have I installed a module and forgot about it?

**Comment by hasse-basse** [comment]
I think it is core and that the function arrived with Dolibarr 19, because I'm quite sure I haven't installed any module with this functionality.

**Comment by ns-info90** [comment]
For me it's not in Dolibarr's core
Check your external modules

**Comment by hasse-basse** [comment]
This is core, I found the below line in Changelog for 18.0.2

`FIX: link to create purchase order from sale order`

**Comment by vmaury** [comment]
In the code, the button is enabled if 
- sale order is draft
- user has right to create supplier order
- sale order has at least one line of service : may be it's the problem, if the're only products, button is not displayed.

May be another test would be usefull : that products or services are 'to buy'

**Comment by hasse-basse** [comment]
Hello and thanks for looking into it.

1. Sales order is a Draft : **I find this odd, it should of course be possible to use the function for a confirmed / saved order.**
2. User has right to create supplier order ; **This i reasonable, nothing to say about it.**
3. Sale order has at least one line of service : may be it's the problem, if the're only products, button is not displayed. **From my perspective this is outright nuts. I sell products and not services. Many times there goes a service with the product, but far away from always. This must be changed to EITHER service OR product. This is probably the culprit to my problems.**

I will make a test when I have time for it, but I'm sure it is #3 for me.

When knowing this, I can make make a workaround by always adding a line of service

Thanks again.
