### ISSUE TITLE
Margin informations are missing on some products

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#2982]
VERSION 3.7.2 :
--Bug on margin module, choice of a specific product's margin can't be made on every products, 
some products seem to be missing on the list of choice, dropdown list incomplete
translate :
Au passage, il a un bug au niveau de marge par produit, le choix peut se faire uniquement sur la liste déroulante de x produit. La liste est pas complète.

Reported from Forum, user kbmbc
http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/52810-module-point-de-vente-marge#60712

**Comment by rdoursenaud** [comment]
From the forum thread, I believe the issue is on 3.6.x and the user has made a typo stating 3.7.x

**Comment by rdoursenaud** [comment]
Could you reproduce with 3.6.3?

**Comment by eldy** [comment]
Does this is still true with 3.8 ?

**Comment by BebZ** [comment]
it is different now, i will open another bug report and detail as much as possible.
