### ISSUE TITLE
third party quick info shows wrong third party status

### ISSUE THREAD

**Issue by Adventurousdonut** [Dolibarr/dolibarr#29841]
### Bug

When you close a third party, if you hover over the third party's name somewhere, it still shows them as active.

### Dolibarr Version

19.0.2

### Environment PHP

8.1.27

### Environment Database

MariaDB

### Attached files

![grafik](https://github.com/Dolibarr/dolibarr/assets/110562645/63be37c4-2440-4fa1-ba75-2b05ee0cb231)
![grafik](https://github.com/Dolibarr/dolibarr/assets/110562645/361505a3-27f8-4de7-9d8d-6cfed0a62cc4)

**Comment by ems-co** [comment]
mine is showing correct status V19.0.2 & PHP 8.2.19
<img width="1186" alt="Screenshot 2024-06-04 at 8 20 31 PM" src="https://github.com/Dolibarr/dolibarr/assets/171037140/c9f3298e-34dd-4772-ab42-52ff13da50fa">
<img width="1169" alt="Screenshot 2024-06-04 at 8 20 26 PM" src="https://github.com/Dolibarr/dolibarr/assets/171037140/ea41d4c3-98dc-49b2-8c1b-e44e0ad28c5c">

**Comment by ems-co** [comment]
<img width="1186" alt="Screenshot 2024-06-04 at 8 20 31 PM" src="https://github.com/Dolibarr/dolibarr/assets/171037140/6dd41be3-def9-4049-9df7-69df47242c66">
<img width="1169" alt="Screenshot 2024-06-04 at 8 20 26 PM" src="https://github.com/Dolibarr/dolibarr/assets/171037140/7bd0e967-d88c-4b06-af76-10b28b2ddfd7">

**Comment by frederic34** [comment]
you can try option MAIN_ENABLE_AJAX_TOOLTIP

**Comment by Adventurousdonut** [comment]
I just launched a new 19.0.2 Dolibarr instance in docker and created a new supplier and everything and i get the same results (supplier is closed for both pictures):
![grafik](https://github.com/Dolibarr/dolibarr/assets/110562645/54b7a5e9-3d31-4b85-b5d5-987d70c8ddef)
Dolibarr Version: 19.0.2
PHP Version: 8.2.7
Database: 11.4.2-MariaDB-ubu2404

@frederic34 when i add MAIN_ENABLE_AJAX_TOOLTIP it now works:
![grafik](https://github.com/Dolibarr/dolibarr/assets/110562645/fa7237b7-ea75-4450-b9cd-0362efa43ab7)

(aktiv = active; geschlossen = closed)

**Comment by frederic34** [comment]
with ajax it's dynamically loaded, so the tooltip is the same everywhere. You can also add extrafields to your object, you will see them in ajax tooltip

**Comment by Adventurousdonut** [comment]
Ah ok, thank you
