### ISSUE TITLE
Extrafields for stock movement not working with API ?

### ISSUE THREAD

**Issue by PikowTh** [Dolibarr/dolibarr#29968]
### Bug

The extrafields for stock movements are not filled in the database via API.

### Dolibarr Version

19.0.2

### Environment PHP

8.0.30

### Environment Database

MySQL or MariaDB 8.0.37

### Steps to reproduce the behavior and expected behavior

I've add two extrafields for stock movements (via "Stock" module in dolibarr)
![image](https://github.com/Dolibarr/dolibarr/assets/62541694/d19f4c94-a2ef-46af-ab9a-7d46afdc017c)
But i can't filled this two extrafields via API, here's what i try to send
![image](https://github.com/Dolibarr/dolibarr/assets/62541694/a263bae9-5e25-4954-9117-0aa4c3fd8c6c)

```
{
   "product_id":"id",
   "warehouse_id":"id",
   "qty":"3",
   "movementlabel":"Test",
   "array_options":{
      "lib_ean_produit":"ean",
      "lib_nom_produit":"Test"
   }
}
```
(the "id" are replaced by product and warehouse ids when the call is made)

When I try to send the JSON, I don't get any apparent error, the movement is created correctly, but the extrafields are not filled in.

**Comment by homer8173** [comment]
same error 
{
   "product_id":"id",
   "warehouse_id":"id",
   "qty":"3",
   "movementlabel":"Test",
   "array_options":{
      "options_lib_ean_produit":"ean",
      "options_lib_nom_produit":"Test"
   }
}
