### ISSUE TITLE
Displaying user who received an expense payment in bank entries

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#30067]
### Bug

Following [#24946](https://github.com/Dolibarr/dolibarr/issues/24946), the same occurs for expense payments : the name of the user who received the payment is missing in the bank entries, remains empty while it appears for salary payments.

![image](https://github.com/Dolibarr/dolibarr/assets/14906222/27d4e09f-fc09-4029-b0c9-2970911e2fab)

### Dolibarr Version

19.0.2

**Comment by zahwyrix** [comment]
Hi, can you describe step by step what you do to get to your writing? I'll take a look at the problem.

**Comment by manu-p** [comment]
A registered user enters an expense in Dolibarr (**HRM** > **Expenses**) which is then submitted to his/her manager who eventually approves and pays it, this is all standard process in Dolibarr.

Then when the allowed user goes to the **bank entries page** (https://_domain_/compta/bank/bankentries_list.php?sortfield=b.datev%2Cb.dateo%2Cb.rowid&sortorder=desc%2Cdesc%2Cdesc) he finds the **Third party/User** column remains empty as show in the 1st post. 
There should be the name of the user who had his expense report paid. Just as for Salary payments, for instance.

**Comment by zahwyrix** [comment]
Did you make any special settings? I've created a bank account and validated an expense claim, but it doesn't create any bank entries for me.

**Comment by zahwyrix** [comment]
Silly me, you've got to put it with the button !

**Comment by manu-p** [comment]
You have to **pay** the expense to see it in bank entries...

**Comment by zahwyrix** [comment]
Don't judge me, I'm an airhead :)

**Comment by zahwyrix** [comment]
Ah yes, it works better when you pay :) I'll look into it and keep you posted.

**Comment by zahwyrix** [comment]
It's been corrected in my pull request!

**Comment by manu-p** [comment]
Good job @zephyriony thanks so much!
Tested and validated !

**Comment by manu-p** [comment]
BTW, do you think you could have a look to https://github.com/Dolibarr/dolibarr/issues/24946 ?
