### ISSUE TITLE
Setup Default values doesn't work on all pages

### ISSUE THREAD

**Issue by battosai30** [Dolibarr/dolibarr#30120]
### Bug

Hi,

Trying to use "[Default values/filters/sorting](https://wiki.dolibarr.org/index.php?title=Setup_Default_values/filters/sorting)" function I met some issues ...

Apparently, it doesn't not work on some pages. For example, invoice is ok, not project or proposal :

![image](https://github.com/Dolibarr/dolibarr/assets/5184702/9b705d5e-494b-492a-a809-94de25103d20)

Regards 

### Dolibarr Version

18.0.4 & 19.0.2

**Comment by jman482002** [comment]
v19.02
There are some problems with Product page as well.
![image](https://github.com/Dolibarr/dolibarr/assets/173647972/f4d05ce2-9b69-4325-8231-5a3728666d69)
![image](https://github.com/Dolibarr/dolibarr/assets/173647972/a9f2a512-f357-418d-9bc7-303a47d28175)
In particular, I realize dropdowns are known to be an issue. But the following should work, but don't:
- Product ref.
- Barcode value

In fact, I tested it and Barcode works fine on Third Party:
![image](https://github.com/Dolibarr/dolibarr/assets/173647972/978cfc96-93c2-4984-85e6-04c224aa9c30)
![image](https://github.com/Dolibarr/dolibarr/assets/173647972/18c4e46c-a8c2-4bac-a83f-1bb7415e8d69)

Upon taking a second glance, it looks like there isn't an ID assigned to Barcode Value on Products page:
![image](https://github.com/Dolibarr/dolibarr/assets/173647972/718a1747-041a-41fe-a0a4-7d0b74e9c8df)

Thanks a bundle!

**Comment by battosai30** [comment]
@eldy 

The fix is only"for propal ? I observe the issue in project too
