### ISSUE TITLE
Allow to create several partial invoices for one proposal.

### ISSUE THREAD

**Issue by VincentJousse** [Dolibarr/dolibarr#3017]
Man can send a proposal to its customer that contains a long time process (like software development).
In that case, it is desirable to have the possibility to create several partial invoices corresponding to the progressing development state.

**Comment by rdoursenaud** [comment]
Situations invoices included in the upcoming 3.8 exactly fit this use case.

See: https://github.com/Dolibarr/dolibarr/pull/2020

**Comment by VincentJousse** [comment]
Question -> answer !! thanks for your high velocity !!

Discussion closed !

**Comment by rdoursenaud** [comment]
You're welcome :)

**Comment by BebZ** [comment]
so Fast and many new contributors on github, it seems good to have changed the bug platform :)
