### ISSUE TITLE
New search function in POS, make impossible to use barcode reader.

### ISSUE THREAD

**Issue by nach41710** [Dolibarr/dolibarr#3019]
I install version 3.7.1. Normally I use POS with a bar code reader.
With version 3.6 I have no problem because the system start searching from the 3rd digit.
With new 3.7.1, the search start from the first character and when I use the barcode reader,  dolibarr only takes the first character. The reader is quicker than dolibarr searching for the first digit.
I really think that this behaviour is really a bug.
Can someone test it, thanks.

**Comment by rdoursenaud** [comment]
I believe that the search behavior is user-configurable in the product module.

Can you confirm that setting this to a greater value still triggers your problem?

If the POS module don't apply the configuration, it's clearly a bug.

**Comment by nach41710** [comment]
Hi:
POS dont apply the configuration, it strart searching from the first character.
My configuration is to search after 3 character.
Can anyone take a look?
Thanks a lot.

**Comment by hregis** [comment]
@nach41710 @rdoursenaud 

I confirm the code has been changed and it no longer uses the search field of products with configuration.

**Comment by hregis** [comment]
https://github.com/Dolibarr/dolibarr/pull/3036

**Comment by nach41710** [comment]
Hi hregis:

I took the files you change and put them in my actual version and  when I try to enter a reference POS still start searching from the first character, may be I did something wrong, can you please confirm that you solve the issue, thanks?

**Comment by nach41710** [comment]
I wonder why the system in version 3.7 start searching each time you enter a character in the ref field, instead of waiting an enter like 3.6 does.

**Comment by hregis** [comment]
Add this constant with value 12
BARCODE_USE_SEARCH_TO_SELECT

**Comment by nach41710** [comment]
Hi hregis:
   I change the constant with the same behaviour.
   Can you please check it?

**Comment by nach41710** [comment]
Excuse me, I made a mistake. during the upload, I will test again your solution....
Sorry

**Comment by nach41710** [comment]
The system still start the search when you enter one character. With this behaviour the Bar code reader still do not work properly.
Can you please check it?

**Comment by nach41710** [comment]
The problem still the same when you start searchin in the POS it takes a while, it take arround a second to accept the second digit and after that it takes again a second with the second digit.
The conclusion is that when you use the Barcode it will take only the first number you enter.
Can anyone confirm it, thanks?

**Comment by andrela** [comment]
I have the very same problem and i have applied the fix in this commit Fix: broken feature: barcode search #3019 + i have set the constant BARCODE_USE_SEARCH_TO_SELECT to 12

Now it works OK for me on  dolibarr 3.7.1

I don't understand why the commit from #3019 hasn't been merged in 3.7.1
And it was very strange for me to understand this issue in the first place, with chrome the behavior was different and the barcode was inserted correctly in the field but taked more than one or two seconds for the search so not usable in production where we need rapidity

Thanks hregis for the fix

**Comment by rdoursenaud** [comment]
Fix merged. Will be available in the next 3.7.x release.
