### ISSUE TITLE
"Tester envoi" impossible dans la configuration des emails

### ISSUE THREAD

**Issue by arkium** [Dolibarr/dolibarr#30204]
### Bug

Suite Message d'erreur : 

> Got error 'PHP message: PHP Parse error: syntax error, unexpected token ";", expecting ")" in [/var/www/vhosts/xxx.xxx/httpdocs/htdocs/core/class/html.formmail.class.php] on line 874', referer: https://xxx.xxx/admin/mails.php?action=testconnect&date=1719746754

Extrait de la ligne 874 :

`$out .= ' '.$formfile->showPreview(array(), $formfile_params[2], $formfile_params[4], 0, ($entity == 1 ? '' : 'entity='.((int) $entity));`

Il manque la parenthèse

`$out .= ' '.$formfile->showPreview(array(), $formfile_params[2], $formfile_params[4], 0, ($entity == 1 ? '' : 'entity='.((int) $entity)));`

### Dolibarr Version

20 et plus ... pas vérifié pour 19

### Environment PHP

8.2.20

### Environment Database

MariaDB

### Steps to reproduce the behavior and expected behavior

Dans la page de configuration : 

> Configuration des mails

Après configuration du mode :

> SMTP/SMTPS socket library

et quand on clique sur le bouton :

> TESTER ENVOI

Nous n'avons pas le formulaire permettant d'envoyer le message par email.
Page blanche après le titre :

> Tester envoi

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/7915871/9395ed30-32d9-4340-819e-0b37eb39d034)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/30201
