### ISSUE TITLE
Move custom document templates out of the core

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3021]
It does make sense to separate user-generated content from the core. Also it is easier to find all the document templates in a common folder instead of navigating through all internal module folders.

**Comment by rdoursenaud** [comment]
You mean the `htdocs/core/modules/*modulename*/doc` folders for PDF generation, right?

Because AFAIK the ODT templates already are at `documents/doctemplates`.

I believe that consolidating templates in this folder can make sense.

**Comment by marcosgdf** [comment]
Well, that folder is the default custom folder for ODT templates but it is not mandatory. I propose making it at least mandatory for PDF and HTML templates.
