### ISSUE TITLE
before the ajax line the reference to the error function is missing from dolibarr 13 to current

### ISSUE THREAD

**Issue by mstoluca** [Dolibarr/dolibarr#30274]
https://github.com/Dolibarr/dolibarr/blob/ac136ec1aeee17edf8ab5f02e567fabdbb320600/htdocs/main.inc.php#L1814

current
	if (GETPOST('dol_resetcache')) {

			dolibarr_set_const($db, "MAIN_IHM_PARAMS_REV", getDolGlobalInt('MAIN_IHM_PARAMS_REV') + 1, 'chaine', 0, '', $conf->entity);
		}

correction
	if (GETPOST('dol_resetcache')) {
			include_once DOL_DOCUMENT_ROOT.'/core/lib/admin.lib.php';
			dolibarr_set_const($db, "MAIN_IHM_PARAMS_REV", getDolGlobalInt('MAIN_IHM_PARAMS_REV') + 1, 'chaine', 0, '', $conf->entity);
		}

**Comment by ksar-ksar** [comment]
Hello,
Seems to have been introduced in V16 not V13 ? 
https://github.com/Dolibarr/dolibarr/commit/9b1f04209dacf7d2478a88601fc5a149f46f534c

**Comment by mstoluca** [comment]
That reference fails from version 13 to v19. Well, it doesn't fail, it wasn't included, and when trying to do a forced update of the Ajax switches, it crashes. It needs to be included in the main file.

**Comment by mstoluca** [comment]
I tried to make a pull request, but I don't have permissions.
