### ISSUE TITLE
Allow iframe embeding

### ISSUE THREAD

**Issue by gortium** [Dolibarr/dolibarr#30275]
### Bug

I want to bring back attention to this issue because I have the same problem and it was reported on the dolibarr forum without real fix: https://www.dolibarr.fr/forum/t/iframe-nextcloud/29812

And the issue here seems to have been closed automaticaly: https://github.com/Dolibarr/dolibarr/issues/19055

**Comment by hansemschnokeloch** [comment]
This in not a bug but a security feature.
You can disable it with the constant `XFRAMEOPTIONS_ALLOWALL` that was introduced in Dolibarr v10 
https://github.com/Dolibarr/dolibarr/blob/196e90cfe83c5ff94fddda350f148029851745ad/ChangeLog#L5287

**Comment by gortium** [comment]
Thank you for pointing that out!

How would i go about setting this constant?
I tried to add it as a docker compose environment variable, also adding it to the conf.php file, without success.

Could it be added as a setting in the GUI?

**Comment by ksar-ksar** [comment]
/admin/const.php
