### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#30284]

**Comment by hregis** [comment]
Les badges... c'est aussi inconnu que Klaus Nomi !

https://www.youtube.com/watch?v=HmLk2vSXXtk&list=RDGMEMJQXQAmqrnmK1SEjY_rKBGA&index=5

Big shots
Argue about what they've got
Making the planet so hot
Hot as a holocaust
Blow up
Everything's gonna go up
Even if you don't show up
In your Chemise Lacoste
Total eclipse
It's a total eclipse
It's a total eclipse of the sun
Can't come to grips with the total eclipse
Just a slip of the lips and you're done
Fall out
Nobody left to crawl out
If someone calls
We're all out
Turning in to French fries
Last dance
Let the entire cast dance
Do the dismembered blast dance
As we get atomized!
Total eclipse
It's a total eclipse
It's a total eclipse of the sun
Can't come to grips with the total eclipse
Just a slip of the lips and you're done
