### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#30289]

**Comment by hregis** [comment]
La Progress Bar d'un gorille...

https://www.youtube.com/watch?v=KVfwvk_yVyA

C'est à travers de larges grilles
Que les femelles du canton
Contemplaient un puissant gorille
Sans souci du qu'en-dira-t-on
Avec impudeur, ces commères
Lorgnaient même un endroit précis
Que, rigoureusement, ma mère
M'a défendu d'nommer ici
Gare au gorille!
Tout à coup la prison bien close
Où vivait le bel animal
S'ouvre, on n'sait pourquoi, je suppose
Qu'on avait dû la fermer mal
Le singe, en sortant de sa cage
Dit "c'est aujourd'hui que j'le perds!"
Il parlait de son pucelage
Vous aviez deviné, j'espère!
Gare au gorille!
L'patron de la ménagerie
Criait, éperdu "nom de nom!
C'est assommant, car le gorille
N'a jamais connu de guenon!"
Dès que la féminine engeance
Sut que le singe était puceau
Au lieu de profiter de la chance
Elle fit feu des deux fuseaux!
Gare au gorille!
Celles-là même qui, naguère
Le couvaient d'un œil décidé
Fuirent, prouvant qu'elles n'avaient guère
De la suite dans les idées
D'autant plus vaine était leur crainte
Que le gorille est un luron
Supérieur à l'homme dans l'étreinte
Bien des femmes vous le diront!
Gare au gorille!
Tout le monde se précipite
Hors d'atteinte du singe en rut
Sauf une vieille décrépite
Et un jeune juge en bois brut
Voyant que toutes se dérobent
Le quadrumane accéléra
Son dandinement vers les robes
De la vieille et du magistrat!
Gare au gorille!
"Bah! soupirait la centenaire
Qu'on pût encore me désirer
Ce serait extraordinaire
Et, pour tout dire, inespéré!"
Le juge pensait, impassible
"Qu'on me prenne pour une guenon
C'est complètement impossible"
La suite lui prouva que non!
Gare au gorille!
Supposez que l'un de vous puisse être
Comme le singe, obligé de
Violer un juge ou une ancêtre
Lequel choisirait-il des deux?
Qu'une alternative pareille
Un de ces quatre jours, m'échoie
C'est, j'en suis convaincu, la vieille
Qui sera l'objet de mon choix!
Gare au gorille!
Mais, par malheur, si le gorille
Aux jeux de l'amour vaut son prix
On sait qu'en revanche il ne brille
Ni par le goût ni par l'esprit
Lors, au lieu d'opter pour la vieille
Comme l'aurait fait n'importe qui
Il saisit le juge à l'oreille
Et l'entraîna dans un maquis!
Gare au gorille!
La suite serait délectable
Malheureusement, je ne peux
Pas la dire, et c'est regrettable
Ça nous aurait fait rire un peu
Car le juge, au moment suprême
Criait "maman!", pleurait beaucoup
Comme l'homme auquel, le jour même
Il avait fait trancher le cou
Gare au gorille!
