### ISSUE TITLE
Event message

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#30296]

**Comment by hregis** [comment]
@lmag en tant que chien actif tu vas révolutionner Dolibarr ! 
Merci pour ton implication Laurent  ;) !
je suis et je resterait un développeur de merde qui t'encourage !

Au village, sans prétention
J'ai mauvaise réputation
Que je me démène ou que je reste coi
Je passe pour un je-ne-sais-quoi
Je ne fais pourtant de tort à personne
En suivant mon chemin de petit bonhomme
Mais les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Non, les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Tout le monde médit de moi
Sauf les muets, ça va de soi
Le jour du quatorze juillet
Je reste dans mon lit douillet
La musique qui marche au pas
Cela ne me regarde pas
Je ne fais pourtant de tort à personne
En n'écoutant pas le clairon qui sonne
Mais les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Non les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Tout le monde me montre au doigt
Sauf les manchots, ça va de soi
Quand je croise un voleur malchanceux
Poursuivi par un cul-terreux
Je lance la patte et pourquoi le taire
Le cul-terreux se retrouve par terre
Je ne fais pourtant de tort à personne
En laissant courir les voleurs de pommes
Mais les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Non les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Tout le monde se rue sur moi
Sauf les culs-de-jatte, ça va de soi
Pas besoin d'être Jérémie
Pour d'viner l' sort qui m'est promis
S'ils trouvent une corde à leur goût
Ils me la passeront au cou
Je ne fais pourtant de tort à personne
En suivant les chemins qui ne mènent pas à Rome
Mais les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Non les braves gens n'aiment pas que
L'on suive une autre route qu'eux
Tout le monde viendra me voir pendu
Sauf les aveugles, bien entendu

**Comment by hregis** [comment]
il va falloir aboyer plus fort pour imposer ta vision ;-)

**Comment by hregis** [comment]
https://www.youtube.com/watch?v=lQRgym8IDGM

**Comment by hansemschnokeloch** [comment]
Could you add the giff-ui-ux label to theses issues so that it's easy to sort them out ? You can add them automatically with github actions.
