### ISSUE TITLE
Problem upgradind 19.0.1 to 19.0.2

### ISSUE THREAD

**Issue by KassCroute** [Dolibarr/dolibarr#30303]
### Bug

Hello,

I am encountering an update issue with my Dolibarr running on Docker Debian 11. I modified the environment variable to upgrade from version 19.0.1 to 19.0.2. The DOLI_INSTALL_AUTO variable is correctly set to 1. However, at a certain stage of the update process, the "Next" button no longer appears, and I cannot proceed further.
The installer correctly detects that I am upgrading from version 19.0.1 to 19.0.2.
![image](https://github.com/Dolibarr/dolibarr/assets/118261726/4aca0885-fc49-463d-8711-70da6138d90b)
![image](https://github.com/Dolibarr/dolibarr/assets/118261726/31ccac7d-0e87-4907-8814-0b6715a62069)
And at this moment I can do nothing else but waiting undefinitely nothing happened
![image](https://github.com/Dolibarr/dolibarr/assets/118261726/0a0c08a5-2b5d-47dd-a968-63cfc832c20a)

Thanks for your help!

### Dolibarr Version

19.0.1

### Environment PHP

8.2.7

### Environment Database

PostgreSQL 16.2

**Comment by ksar-ksar** [comment]
Hello,

If you do not have next means PHP error => What does your server logs says ?

**Comment by KassCroute** [comment]
Bonjour,
Voici le contenu de mon dolibarr.log.
L’upgrade bug car il y a collision de nom dans la bdd. Je pensais que le script allait s’en occuper lui même ? Est ce que je dois supprimer des trucs moi même ?

`2024-07-10 09:32:50 WARNING 192.168.1.202   main.inc: database version 19.0.1 is lower than programs version 19.0.2. Redirect to install/upgrade page.
2024-07-10 09:32:50 INFO    192.168.1.202   --- End access to /index.php
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_user ADD COLUMN birth date
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "birth" of relation "llx_user" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_user ADD COLUMN dateemployment date
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "dateemployment" of relation "llx_user" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_user ADD COLUMN dateemploymentend date
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "dateemploymentend" of relation "llx_user" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_user ADD COLUMN default_range integer
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "default_range" of relation "llx_user" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_user ADD COLUMN default_c_exp_tax_cat integer
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "default_c_exp_tax_cat" of relation "llx_user" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_extrafields ADD COLUMN langs varchar(24)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "langs" of relation "llx_extrafields" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_extrafields ADD COLUMN fieldcomputed text
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "fieldcomputed" of relation "llx_extrafields" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_extrafields ADD COLUMN fielddefault varchar(255)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "fielddefault" of relation "llx_extrafields" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_extrafields ADD COLUMN enabled varchar(255) DEFAULT '1'
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "enabled" of relation "llx_extrafields" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_extrafields ADD COLUMN help text
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "help" of relation "llx_extrafields" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   sql=ALTER TABLE llx_user_rights ADD COLUMN entity integer DEFAULT 1 NOT NULL
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "entity" of relation "llx_user_rights" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:7245 (DB_ERROR_COLUMN_ALREADY_EXISTS)
2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error usesavepoint = 1
2024-07-10 09:33:02 DEBUG   192.168.1.202   BEGIN Transaction`

**Comment by hregis** [comment]
@KassCroute and otherwise do you have skills to install software with something other than Docker? This is a newbee method. Will take lessons in installing a real web server first.

**Comment by KassCroute** [comment]
Lol je pense qu'il est plus difficile d'installer Dolibarr avec docker avec les problèmes associés qu'avec une méthode classique. Tu ne connais rien de mon environnement et tu te permets de parler pour juger. Si tu n'est pas la pour apporter de l'aide avec bienveillance passe ton chemin.

**Comment by hregis** [comment]
à force de tout pré-macher et en rajoutant l'intelligence artificielle par dessus nous allons faire des générations de débiles ! misère !

**Comment by KassCroute** [comment]
Retourne dans ton coin boomer.

**Comment by hregis** [comment]
@KassCroute écoute boutonneux, je n'ai aucunes leçons de recevoir de toi... ici c'est pour les bugs, pas les problèmes d'installation... va sur le forum et arrête de nous faire chier...

**Comment by eldy** [comment]
> Bonjour,
> Voici le contenu de mon dolibarr.log.
> L’upgrade bug car il y a collision de nom dans la bdd. Je pensais que le script allait s’en occuper lui même ? Est ce que je dois supprimer des trucs moi même ?
> 
> `2024-07-10 09:32:50 WARNING 192.168.1.202   main.inc: database version 
...
> 2024-07-10 09:33:02 DEBUG   192.168.1.202   BEGIN Transaction`

This error is expected. The error means the upgrade tool try to dobthing already done. They are filtered by the upgrader.
If you don't have the button, it means there is a system error (different of errors that you see in dolibarr.log).
The information of error can be found into the error.log file of the web server, not into dolibarr.log

If you can paste end of lines of this error.log file, we may help...

**Comment by KassCroute** [comment]
> > Bonjour,
> > Voici le contenu de mon dolibarr.log.
> > L’upgrade bug car il y a collision de nom dans la bdd. Je pensais que le script allait s’en occuper lui même ? Est ce que je dois supprimer des trucs moi même ?
> > `2024-07-10 09:32:50 WARNING 192.168.1.202   main.inc: database version  ... 2024-07-10 09:33:02 DEBUG   192.168.1.202   BEGIN Transaction`
> 
> This error is expected. The error means the upgrade tool try to dobthing already done. They are filtered by the upgrader. If you don't have the button, it means there is a system error (different of errors that you see in dolibarr.log). The information of error can be found into the error.log file of the web server, not into dolibarr.log
> 
> If you can paste end of lines of this error.log file, we may help...

Hello, 

Thank you for your answer. Here is the apacha2 logs : 
```
Current Version is : 19.0.2
[Thu Jul 18 15:16:02.976969 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.59 (Debian) PHP/8.2.7 configured -- resuming normal operations
[Thu Jul 18 15:16:02.977137 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET / HTTP/1.1" 302 478 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /install/index.php HTTP/1.1" 302 246 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /install/check.php?testget=ok HTTP/1.1" 200 3185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /install/default.css HTTP/1.1" 200 3339 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /includes/jquery/css/base/jquery-ui.min.css HTTP/1.1" 200 7911 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /theme/common/octicons/build/svg/gear.svg HTTP/1.1" 200 730 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /includes/jquery/js/jquery.min.js HTTP/1.1" 200 31381 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /theme/eldy/img/tick.png HTTP/1.1" 200 471 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:28 +0000] "GET /includes/jquery/js/jquery-ui.min.js HTTP/1.1" 200 68333 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:29 +0000] "GET /favicon.ico HTTP/1.1" 200 2522 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
127.0.0.1 - - [18/Jul/2024:15:17:35 +0000] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.59 (Debian) PHP/8.2.7 (internal dummy connection)"
192.168.1.202 - - [18/Jul/2024:15:17:35 +0000] "GET /install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=18.0.0&versionto=19.0.0 HTTP/1.1" 200 8352 "http://192.168.1.204/install/check.php?testget=ok" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.1.202 - - [18/Jul/2024:15:17:36 +0000] "GET /theme/common/octicons/build/svg/database.svg HTTP/1.1" 200 796 "http://192.168.1.204/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=18.0.0&versionto=19.0.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
127.0.0.1 - - [18/Jul/2024:15:17:42 +0000] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.59 (Debian) PHP/8.2.7 (internal dummy connection)"
[Thu Jul 18 15:17:46.356222 2024] [php:warn] [pid 56] [client 192.168.1.202:40409] PHP Warning:  Attempt to read property "localtax1_assuj" on null in /var/www/html/core/modules/modFournisseur.class.php on line 312, referer: http://192.168.1.204/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=18.0.0&versionto=19.0.0
[Thu Jul 18 15:17:46.356249 2024] [php:warn] [pid 56] [client 192.168.1.202:40409] PHP Warning:  Attempt to read property "localtax2_assuj" on null in /var/www/html/core/modules/modFournisseur.class.php on line 313, referer: http://192.168.1.204/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=18.0.0&versionto=19.0.0
[Thu Jul 18 15:17:46.576769 2024] [php:error] [pid 56] [client 192.168.1.202:40409] PHP Fatal error:  Uncaught TypeError: pg_fetch_object(): Argument #1 ($result) must be of type PgSql\\Result, bool given in /var/www/html/core/db/pgsql.class.php:600\nStack trace:\n#0 /var/www/html/core/db/pgsql.class.php(600): pg_fetch_object()\n#1 /var/www/html/core/modules/modSociete.class.php(526): DoliDBPgsql->fetch_object()\n#2 /var/www/html/install/upgrade2.php(4320): modSociete->__construct()\n#3 /var/www/html/install/upgrade2.php(555): migrate_reload_modules()\n#4 {main}\n  thrown in /var/www/html/core/db/pgsql.class.php on line 600, referer: http://192.168.1.204/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=18.0.0&versionto=19.0.0
192.168.1.202 - - [18/Jul/2024:15:17:45 +0000] "POST /install/upgrade2.php?versionfrom=18.0.0&versionto=19.0.0 HTTP/1.1" 500 3461 "http://192.168.1.204/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=18.0.0&versionto=19.0.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
```

**Comment by hregis** [comment]
Bonjour @KassCroute 
je suis désolé d'avoir été aussi con la dernière fois... je n'ai rien contre toi... j'ai mal compris ton problème !
J'ai testé la mise à jour de dolibarr 19 en postgresql et je n'ai pas eu de problème...
par contre je ne suis pas en Postgresql 16 !
je vais essayer de faire des tests avec cette version... par contre... je ne suis pas en docker ! Tu as pu sentir mon aversion envers "docker" ! ;-)
je te tiendrais au courant....

@eldy merci d'avoir retirer nos messages de merdes ! ;-)

**Comment by hregis** [comment]
@KassCroute postgresql est imbuvable... le changement de version n'a pas de sens... tu es obligé de fonctionner sur postgresql ?

**Comment by hregis** [comment]
@KassCroute postgresql a surement été développé par le KGB pour t'embrouiller dans une complexité qui n'est faite que pour dépendre de leurs idées... un peu comme LFI !

**Comment by KassCroute** [comment]
Bonjour, 

Reconnaitre son erreur est le principal. J'ai finalement fait une sauvegarde down mon conteneur, clear les volumes et j'ai relancé avec la version 19.0.2 vu que le saut n'est pas grand je pense pas que ça va impacter la sauvegarde précédente je suis en environnement de test je peux me permettre d'essayer. Cependant c'est incompréhensible que personne d'autre n'est signalé le pb.

**Comment by KassCroute** [comment]
> Bonjour,
> 
> Reconnaitre son erreur est le principal. J'ai finalement fait une sauvegarde down mon conteneur, clear les volumes et j'ai relancé avec la version 19.0.2 vu que le saut n'est pas grand je pense pas que ça va impacter la sauvegarde précédente je suis en environnement de test je peux me permettre d'essayer. Cependant c'est incompréhensible que personne d'autre n'est signalé le pb.

Bon je viens de faire le @hregis ça ne marche pas car il détecte que ma précédente sauvegarde était sur du 19.0.1.....

**Comment by KassCroute** [comment]
> Bonjour,
> 
> Reconnaitre son erreur est le principal. J'ai finalement fait une sauvegarde down mon conteneur, clear les volumes et j'ai relancé avec la version 19.0.2 vu que le saut n'est pas grand je pense pas que ça va impacter la sauvegarde précédente je suis en environnement de test je peux me permettre d'essayer. Cependant c'est incompréhensible que personne d'autre n'est signalé le pb.

Bon je viens de faire le test @hregis ça ne marche pas car il détecte que ma précédente sauvegarde était sur du 19.0.1.....

**Comment by hregis** [comment]
@KassCroute je viens de faire une install de dolibarr 19.0.1 avec php8.2 et Postgresql 16 puis une mise à jour en 19.0.2 et je n'ai toujours pas d'erreurs ! Par contre je ne suis toujours pas avec "docker" ! C'est peut-être propre à Docker ? Mais là je ne pourrais pas t'aider... :-)

**Comment by hregis** [comment]
@KassCroute par contre tu as des erreurs qui ne devraient pas être dans l'upgrade:

`DoliDBPgsql::query SQL Error message: ERROR:  42701: column "help" of relation "llx_extrafields" already exists`

as-tu des modules externes ?

**Comment by hregis** [comment]
@KassCroute et ce qui est bizarre c'est que cette erreur proviendrait de la mise à jour de 6.0.0 vers 7.0.0 !!

`sql=ALTER TABLE llx_user ADD COLUMN birth date 2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "birth" of relation "llx_user" already exists`

et ça c'est 5.0.0 vers 6.0.0 !!

`sql=ALTER TABLE llx_user_rights ADD COLUMN entity integer DEFAULT 1 NOT NULL 2024-07-10 09:33:02 ERR     192.168.1.202   DoliDBPgsql::query SQL Error message: ERROR:  42701: column "entity" of relation "llx_user_rights" already exists`

c'est comme-ci il passait tous les fichiers de migrations ! :-)

**Comment by hregis** [comment]
@KassCroute ok j'ai trouvé ! désactive le module "social network" avant de faire ta mise à jour, je vais regrader pourquoi pourquoi il fait planté la maj avec postgresql

**Comment by hregis** [comment]
@KassCroute @eldy il a fallu aller le chercher loin celui là !! ;-)  https://github.com/Dolibarr/dolibarr/pull/30443

**Comment by KassCroute** [comment]
Bonsoir, désolé pour la réponse tardive ! Je vais essayer ça je vous retiens au courant ! C'est fou quand même qu'un module puisse faire planter une maj ! Merci encore de vous être penché sur mon cas @hregis !

**Comment by KassCroute** [comment]
> @KassCroute @eldy il a fallu aller le chercher loin celui là !! ;-) #30443

Je confirme ça fonctionne parfaitement avec le module désactivé ! Merci encore !
