### ISSUE TITLE
Extrafield for intervention lines not working with API

### ISSUE THREAD

**Issue by PikowTh** [Dolibarr/dolibarr#30342]
### Bug

The extrafields for intervention lines are not filled in the database via API.

### Dolibarr Version

19.0.2

### Environment PHP

8.0.30

### Environment Database

MySQL or MariaDB 8.0.37

### Steps to reproduce the behavior and expected behavior

I've add one extrafield for intervention lines (via "Interventions" module in dolibarr)
![image](https://github.com/Dolibarr/dolibarr/assets/62541694/798fd851-985c-4797-8df8-570976e916f4)
But i can't filled this extrafield with API, here's what i try to send
![image](https://github.com/Dolibarr/dolibarr/assets/62541694/fc56441d-2ad0-43ab-b982-1fe2cded3507)
```
{
  "description": "test",
  "date": "1720598400",
  "duree": "1800",
  "array_options": {
    "intervenant_custom": "Test"
  }
}
```
When I try to send the JSON, I don't get any apparent error, the line is created correctly, but the extrafield isn't filled in.
![image](https://github.com/Dolibarr/dolibarr/assets/62541694/ecd0294c-417e-46b5-98cf-f3193dd0f365)
I've highlighted where the data need to be filled

**Comment by homer8173** [comment]
Hello I haven't open the code but your naming doesn't follow the dolibarr rules
if you created a intervenant_custom, the naming is options_intervenant_custom
{
  "description": "test",
  "date": "1720598400",
  "duree": "1800",
  "array_options": {
    "options_intervenant_custom": "Test"
  }
}

**Comment by PikowTh** [comment]
> Hello I haven't open the code but your naming doesn't follow the dolibarr rules if you created a intervenant_custom, the naming is options_intervenant_custom { "description": "test", "date": "1720598400", "duree": "1800", "array_options": { "options_intervenant_custom": "Test" } }

I'm sending informations via this route

![image](https://github.com/user-attachments/assets/7fbdb656-a828-4576-a774-284263e194c4)

It's the same as [this post](https://github.com/Dolibarr/dolibarr/issues/29968) , i don't need to add "options_" in "array_options" when sending informations (like with ticket extrafields), only when retrieving informations ?.

I still tested it with "options_"

![image](https://github.com/user-attachments/assets/c359aacb-0fcd-423f-b1e5-d692e4b8fbf4)

```
{
  "description": "test",
  "date": "1736774140",
  "duree": "3600",
  "array_options": {
    "options_intervenant_custom": "Test"
  }
}
```

Still the same problem

![image](https://github.com/user-attachments/assets/2bbf651f-9295-443f-84d2-619703001b27)
