### ISSUE TITLE
Recording in accounting section for Sales or Purchases error with PostGreSql

### ISSUE THREAD

**Issue by Ericl92220** [Dolibarr/dolibarr#30353]
### Bug

Hello,

On a fresh Dolibarr installation with PostGreSql,
Click on "recording in accounting" section for "Sales" or "Purchases" produces a white page
The "Bank" section is OK
No PB with a MySQL database configuration

(Error below in the web server's logs)

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: pg_num_rows(): Argument #1 ($result) must be of type PgSql\\Result, bool given in /dlb_dmo_pgsql/htdocs/core/db/pgsql.class.php:652\nStack trace:
\n#0 /dlb_dmo_pgsql/htdocs/core/db/pgsql.class.php(652): pg_num_rows()
\n#1 /dlb_dmo_pgsql/htdocs/accountancy/journal/sellsjournal.php(400): DoliDBPgsql->num_rows()
\n#2 {main}\n  thrown in /dlb_dmo_pgsql/htdocs/core/db/pgsql.class.php on line 652'

Regards,

### Dolibarr Version

Dolibarr 19.0.2

### Environment PHP

PHP 8.2.20

### Environment Database

PostgreSQL 15.7

### Steps to reproduce the behavior and expected behavior

Go to the accounting tab
Click on "Recording in accounting" (Sales or Purchases)

**Comment by mkaag** [comment]
Same here with Dolibarr 19.0.0 and FreeBSD 14.0p9 (php and postgresql15 are the very same):

[Mon Aug 19 18:51:17.926772 2024] [proxy_fcgi:error] [pid 7178:tid 34393495296] [client 10.67.0.176:39930] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: pg_num_rows(): Argument #1 ($result) must be of type PgSql\\Result, bool given in /usr/local/www/dolibarr-19.0.0/htdocs/core/db/pgsql.class.php:652\nStack trace:\n#0 /usr/local/www/dolibarr-19.0.0/htdocs/core/db/pgsql.class.php(652): pg_num_rows()\n#1 /usr/local/www/dolibarr-19.0.0/htdocs/accountancy/journal/sellsjournal.php(400): DoliDBPgsql->num_rows()\n#2 {main}\n  thrown in /usr/local/www/dolibarr-19.0.0/htdocs/core/db/pgsql.class.php on line 652', referer: http://dolibarr.example.com/accountancy/customer/index.php?leftmenu=accountancy_dispatch_customer&mainmenu=accountancy

**Comment by hregis** [comment]
@mkaag this PR fix this bug, thanks : https://github.com/Dolibarr/dolibarr/pull/30678
