### ISSUE TITLE
Product selection dropdown on the order page does not display all available products

### ISSUE THREAD

**Issue by medAmineRg** [Dolibarr/dolibarr#30376]
### Bug

The product selection dropdown on the order page does not display all available products. It appears to be limited to a fixed number.

Page URL : https://domain_name/commande/card.php?id=43

### Dolibarr Version

19.0.2

### Environment PHP

8.1

### Environment Database

mysql V 8.0.38

### Steps to reproduce the behavior and expected behavior

- Steps to Reproduce:
1. Go to the Order page in Dolibarr.
2. Select "Predefined products/services to sell."
3. Scroll through the dropdown list of products.

- Expected Behavior:
The dropdown list should display all available products.

### Attached files

<img width="794" alt="Screenshot 2024-07-12 165324" src="https://github.com/user-attachments/assets/a19dc005-d7ec-4938-8e43-08afe6388f0e">

**Comment by sonikf** [comment]
Hi @medAmineRg 
Works fine for me, can't reproduce bug!
Combo shows only products/services with status for sale.

**Comment by medAmineRg** [comment]
Hi @sonikf thanks for replying, well yeah it works for me to but it doesn't show all available products, there's like a limit in the query or the select drop down. 

Yeah i Know it only shows the product listed for sale, but i have products listed for sale and the dropdown doesn't show them.

**Comment by backstageel** [comment]
> Hi @sonikf thanks for replying, well yeah it works for me to but it doesn't show all available products, there's like a limit in the query or the select drop down.

What is the current limit that you are seeing? I can test here and if so submit a fix

**Comment by medAmineRg** [comment]
@backstageel, we have 1381 product but I only see 1036.
<img width="561" alt="Screenshot 2024-07-15 151122" src="https://github.com/user-attachments/assets/8bc79a6b-e7d0-4efc-8062-1e2c25ba1ad7">

**Comment by sonikf** [comment]
@medAmineRg, @backstageel 
I see what you mean, 
Are there any products you miss and can't select? Why do you need all of them?
You don't need to load all ids because in long lists it is counter productive to scroll through the list instead you search and thus rearrange query parameters.

**Comment by medAmineRg** [comment]
@sonikf, I don't need all of the products but some of them are missing when trying to select them.

**Comment by sonikf** [comment]
Do you search for them and they do not show up?

**Comment by medAmineRg** [comment]
Yeah I do but they doesn't show up, i tried to read the code and fix it but i find it to hard its in php native.

**Comment by sonikf** [comment]
Ok, can you search with ref of product. Does it show up?

**Comment by medAmineRg** [comment]
Yeah i try but nothing show's up.


<img width="397" alt="Screenshot 2024-07-15 164759" src="https://github.com/user-attachments/assets/739dd62c-683f-4afa-8e3b-1d7218ca88dc">

<img width="595" alt="Screenshot 2024-07-15 164829" src="https://github.com/user-attachments/assets/215fed93-2701-48d8-883c-2cdd271e1fa9">

here's a screenshot !

**Comment by hregis** [comment]
@medAmineRg go to configuration of product module and select "yes" for this option
<img width="1656" alt="Capture d’écran 2024-07-15 à 18 04 53" src="https://github.com/user-attachments/assets/cc828558-74fa-4c79-a237-6f71956d488b">

**Comment by medAmineRg** [comment]
Sorry it wasn't a bug, the solution was setting the combo select limit to 0 in the product module. 
<img width="752" alt="Screenshot 2024-07-15 221218" src="https://github.com/user-attachments/assets/eadb03b7-851f-4cb3-8e14-acb6bcb3b9c5">

Thank you @hregis, @backstageel, @sonikf.
