### ISSUE TITLE
Export/print list of transactions

### ISSUE THREAD

**Issue by olipanis** [Dolibarr/dolibarr#3038]
is there any way to export or print the list of transactions? (url: .../compta/bank/search.php)

**Comment by rdoursenaud** [comment]
Hi @olipanis.
You should have read https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md before asking your question.
This is not a support forum.
Please ask your question on the [forum](http://www.dolibarr.org/forum) or the [user mailing list](https://lists.nongnu.org/mailman/listinfo/dolibarr-user).
Thanks.
