### ISSUE TITLE
Bug: Incorrect date year selector in Google Chrome for Android

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3039]
Version: 3.6.4 (probably 3.5 and 3.7 affected)

As you can see in the following screenshots, years are shown in a different format than it used to.

![screenshot_2015-06-14-11-20-00](https://cloud.githubusercontent.com/assets/168744/8148017/a3ddabca-1287-11e5-9de2-30d4ef11f44b.png)
![screenshot_2015-06-14-11-20-03](https://cloud.githubusercontent.com/assets/168744/8148018/a3e09ae2-1287-11e5-8f48-0af4f39b8e16.png)

**Comment by hregis** [comment]
https://github.com/Dolibarr/dolibarr/pull/3041
