### ISSUE TITLE
Unable to modify client_code through thirdparties rest API

### ISSUE THREAD

**Issue by m2miage-lorenzo** [Dolibarr/dolibarr#30432]
Hello,

I am currently trying to modify a client_code through the Thirdparties Rest API. I have adjusted Dolibarr's Thirdparties configuration to allow custom client codes (via the Leopard Module). However, it appears that modifying the client code through the API is not allowed. Could you please explain the reasoning behind this restriction? Additionally, is there any solution to bypass this issue without having to manually modify every code?

After some investigation, it seems the issue originates from the following line: https://github.com/Dolibarr/dolibarr/blame/1b5eb2de22ccee5377549a219d0448f1e3026117/htdocs/societe/class/api_thirdparties.class.php#L299

**Steps to Reproduce:**
- Execute the following CURL command : curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: key' -d '{ "code_client" :  "new code" }' 'https://dolibarr-server.fr/api/index.php/thirdparties/id'
- Attempt to modify the client code via the API, the Swagger UI, or the above CURL command
- Observe that the API returns a 200 code without modifying the client.

**Expected Behavior:**
I expected to be able to update the client code through the API.

**Actual Behavior:**
The client code remains unchanged and the modification is blocked.

Thank you very much for your assistance.

Best regards,
Lorenzo

**Comment by lebouquetin** [comment]
(I'm working with @l3miage-porcul on the current issue).

What I intuite is that `$allowmodcodeclient` and `$allowmodcodefournisseur` are using default value (falsee) in order to avoid conflict with client/supplier code auto-generation.

Unfortunately, the API returns a `HTTP 200` which is false.

What we are trying to do, actually, is to generate client codes like `AL-000123` where AL are two first letters of the client name.

It looks like the only way to do so is to externally (ie not in dolibarr) define the client code - Elephant model does not seem to allow this. Another way to do so would be to implement our own client code generator.

**Comment by lebouquetin** [comment]
According to 

I created a module based on `mod_codeclient_monkey.php` which generates client codes accordign to the following rules:

- do nothing for suppliers - we keep standard behavior
- generate a client code only if the object is already defined (so it will work on edit only). The rules are:
  - use 2 first not empty chars of the name
  - increment a 6-digit counter

Client codes are like `AL-000123` for a client name starting by AL.

Here is the code of `mod_codeclient_algoo.php`:

```
<?php
/* Copyright (C) 2004		Rodolphe Quiedeville	<rodolphe@quiedeville.org>
 * Copyright (C) 2006-2007	Laurent Destailleur		<eldy@users.sourceforge.net>
 * Copyright (C) 2006-2012	Regis Houssin			<regis.houssin@inodbox.com>
 * Copyright (C) 2024			Damien Accorsi			<damien.accorsi@algoo.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 * or see https://www.gnu.org/
 */

/**
 *       \file       htdocs/core/modules/societe/mod_codeclient_monkey.php
 *       \ingroup    societe
 *       \brief      Fichier de la classe des gestion lion des codes clients
 */

require_once DOL_DOCUMENT_ROOT.'/core/modules/societe/mod_codeclient_monkey.php';


/**
 *	Classe permettant la gestion monkey des codes tiers
 */
class mod_codeclient_algoo extends mod_codeclient_monkey
{
	/**
	 * @var string model name
	 */
	public $name = 'Algoo';

	public $code_modifiable; // Code modifiable

	public $code_modifiable_invalide; // Code modifiable si il est invalide

	public $code_modifiable_null; // Code modifiables si il est null

	public $code_null; // Code facultatif

	/**
	 * Dolibarr version of the loaded document
	 * @var string
	 */
	public $version = 'dolibarr'; // 'development', 'experimental', 'dolibarr'

	/**
	 * @var int Automatic numbering
	 */
	public $code_auto;

	public $prefixcustomer = 'CU';  // INFO - D.A. - 2024-07-23 - This part of the code is now useless

	public $prefixsupplier = 'SU';  // INFO - D.A. - 2024-07-23 - This part of the code is now useless

	public $prefixIsRequired; // Le champ prefix du tiers doit etre renseigne quand on utilise {pre}


	/**
	 * 	Constructor
	 */
	public function __construct()
	{
		$this->code_null = 1;
		$this->code_modifiable = 1;
		$this->code_modifiable_invalide = 1;
		$this->code_modifiable_null = 1;
		$this->code_auto = 1;
		$this->prefixIsRequired = 0;
	}


	/**
	 *  Return description of module
	 *
	 *  @param	Translate	$langs	Object langs
	 *  @return string      		Description of module
	 */
	public function info($langs)
	{
		return "Renvoie une numérotation au formaXX-nnnnnn pour le code client et pour le code fournisseur o&ugrave; XX sont les 2 premi&egrave;res lettres du nom du tiers et nnnnnn est un compteur sans rupture ni retour &agrave; 0.";
	}


	/**
	 * Return an example of result returned by getNextValue
	 *
	 * @param	Translate	$langs		Object langs
	 * @param	societe		$objsoc		Object thirdparty
	 * @param	int			$type		Type of third party (1:customer, 2:supplier, -1:autodetect)
	 * @return	string					Return string example
	 */
	public function getExample($langs, $objsoc = 0, $type = -1)
	{
		return 'AL-000001<br>'.$this->prefixsupplier.'AL-000001';
	}


	/**
	 *  Return next value
	 *
	 *  @param	Societe		$objsoc     Object third party
	 *  @param  int			$type       Client ou fournisseur (1:client, 2:fournisseur)
	 *  @return string      			Value if OK, '' if module not configured, <0 if KO
	 */
	public function getNextValue($objsoc = 0, $type = -1)
	{
		global $db, $conf, $mc;

		$field = '';
		$prefix = '';

		if ($type == 0) {
			$field = 'code_client';
			if ($objsoc) {
				// INFO - D.A - 2024-07-23 Use first 2 letters of company name
				$name_with_no_space = preg_replace('/\s+/', '', $objsoc->name);
				$first_two_chars = substr($name_with_no_space, 0, 2);
				$prefix = strtoupper($first_two_chars);
			}
		} elseif ($type == 1) {
			$field = 'code_fournisseur';
			$prefix = $this->prefixsupplier;
		} else {
			return "";
		}

		// First, we get the max value (reponse immediate car champ indexe)
		$posindice = 4; // client code is something like XX-000000 so we need to cast numbers from 4th char
		$sql = "SELECT MAX(CAST(SUBSTRING(".$field." FROM ".$posindice.") AS SIGNED)) as max"; // This is standard SQL
		$sql .= " FROM ".MAIN_DB_PREFIX."societe";
		$sql .= " WHERE ".$field." LIKE '__-%'";
		$sql .= " AND entity IN (".getEntity('societe').")";

		// HACK - D.A. - 2024-07-25 - A dirty way to investigate and fix SQL query strategy
		// print($sql);
		// exit();
		dol_syslog(get_class($this)."::getNextValue", LOG_DEBUG);

		$resql = $db->query($sql);
		if ($resql) {
			$obj = $db->fetch_object($resql);
			if ($obj) {
				$max = intval($obj->max);
			} else {
				$max = 0;
			}
		} else {
			return -1;
		}

		if ($max >= (pow(10, 6) - 1)) {  // INFO - D.A. - 2024-07-23 - Use 6 digits like on all galae clients
			$num = $max + 1; // If counter > 999999, we do not format on 5 chars, we take number as it is
		} else {
			$num = sprintf("%06d", $max + 1);
		}

		// INFO - D.A. - 2024-07-23 Removed date related part of the default client code generation
		dol_syslog(get_class($this)."::getNextValue return ".$prefix."-".$num);
		return $prefix."-".$num;
	}


	/**
	 * 	Check validity of code according to its rules
	 *
	 *	@param	DoliDB		$db		Database handler
	 *	@param	string		$code	Code to check/correct
	 *	@param	Societe		$soc	Object third party
	 *  @param  int		  	$type   0 = customer/prospect , 1 = supplier
	 *  @return int					0 if OK
	 * 								-1 ErrorBadCustomerCodeSyntax
	 * 								-2 ErrorCustomerCodeRequired
	 * 								-3 ErrorCustomerCodeAlreadyUsed
	 * 								-4 ErrorPrefixRequired
	 */
	public function verif($db, &$code, $soc, $type)
	{
		global $conf;

		$result = 0;
		$code = strtoupper(trim($code));

		if (empty($code) && $this->code_null && empty($conf->global->MAIN_COMPANY_CODE_ALWAYS_REQUIRED)) {
			$result = 0;
		} elseif (empty($code) && (!$this->code_null || !empty($conf->global->MAIN_COMPANY_CODE_ALWAYS_REQUIRED))) {
			$result = -2;
		} else {
			if ($this->verif_syntax($code) >= 0) {
				$is_dispo = $this->verif_dispo($db, $code, $soc, $type);
				if ($is_dispo <> 0) {
					$result = -3;
				} else {
					$result = 0;
				}
			} else {
				if (dol_strlen($code) == 0) {
					$result = -2;
				} else {
					$result = -1;
				}
			}
		}

		dol_syslog(get_class($this)."::verif code=".$code." type=".$type." result=".$result);
		return $result;
	}


	// phpcs:disable PEAR.NamingConventions.ValidFunctionName.ScopeNotCamelCaps
	/**
	 *		Renvoi si un code est pris ou non (par autre tiers)
	 *
	 *		@param	DoliDB		$db			Handler acces base
	 *		@param	string		$code		Code a verifier
	 *		@param	Societe		$soc		Objet societe
	 *		@param  int		  	$type   	0 = customer/prospect , 1 = supplier
	 *		@return	int						0 if available, <0 if KO
	 */
	public function verif_dispo($db, $code, $soc, $type = 0)
	{
		// phpcs:enable
		global $conf, $mc;

		$sql = "SELECT rowid FROM ".MAIN_DB_PREFIX."societe";
		if ($type == 1) {
			$sql .= " WHERE code_fournisseur = '".$db->escape($code)."'";
		} else {
			$sql .= " WHERE code_client = '".$db->escape($code)."'";
		}
		$sql .= " AND entity IN (".getEntity('societe').")";
		if ($soc->id > 0) {
			$sql .= " AND rowid <> ".$soc->id;
		}

		dol_syslog(get_class($this)."::verif_dispo", LOG_DEBUG);
		$resql = $db->query($sql);
		if ($resql) {
			if ($db->num_rows($resql) == 0) {
				return 0;
			} else {
				return -1;
			}
		} else {
			return -2;
		}
	}


	// phpcs:disable PEAR.NamingConventions.ValidFunctionName.ScopeNotCamelCaps
	/**
	 *  Renvoi si un code respecte la syntaxe
	 *
	 *  @param  string      $code       Code a verifier
	 *  @return int                     0 si OK, <0 si KO
	 */
	public function verif_syntax($code)
	{
		// phpcs:enable
		$res = 0;
		if (dol_strlen($code) < 9) {  // INFO - D.A. - 2024-07-23 Expected code is like AL-000001
			$res = -1;
		} else {
			$res = 0;
		}
		return $res;
	}
}
```

Note: it is working on Dolibarr 18. 

Question: Is it interesting for inclusion in upstream? If so, is their a sepcific process in order to propose a PR?

**Comment by lebouquetin** [comment]
@philippe-opendsi @eldy  what do you think of this? Do you think it's a good idea to create a PR?

The PR would be about a new codeclient stratagy which would be `AL-000017` for example for a client called Algoo (2 first letters of the client name + iterator)

**Comment by eldy** [comment]
> @philippe-opendsi @eldy  what do you think of this? Do you think it's a good idea to create a PR?
> 
> The PR would be about a new codeclient stratagy which would be `AL-000017` for example for a client called Algoo (2 first letters of the client name + iterator)

Creating a new numbering module is not necessary. Enhancing elephant to accept tags {n...} too use first letters of name like we do for {u...} or {t...} can be done.

**Comment by eldy** [comment]
> Hello,
> 
> I am currently trying to modify a client_code through the Thirdparties Rest API. I have adjusted Dolibarr's Thirdparties configuration to allow custom client codes (via the Leopard Module). However, it appears that modifying the client code through the API is not allowed. Could you please explain the reasoning behind this restriction? Additionally, is there any solution to bypass this issue without having to manually modify every code?
> 
> After some investigation, it seems the issue originates from the following line: https://github.com/Dolibarr/dolibarr/blame/1b5eb2de22ccee5377549a219d0448f1e3026117/htdocs/societe/class/api_thirdparties.class.php#L299
> 
> **Steps to Reproduce:**
> - Execute the following CURL command : curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'DOLAPIKEY: key' -d '{ "code_client" :  "new code" }' 'https://dolibarr-server.fr/api/index.php/thirdparties/id'
> - Attempt to modify the client code via the API, the Swagger UI, or the above CURL command
> - Observe that the API returns a 200 code without modifying the client.
> 
> **Expected Behavior:**
> I expected to be able to update the client code through the API.
> 
> **Actual Behavior:**
> The client code remains unchanged and the modification is blocked.
> 
> Thank you very much for your assistance.
> 
> Best regards,
> Lorenzo

No reason to not being able to edit customer code from api, surely a bug...

**Comment by lebouquetin** [comment]
> Creating a new numbering module is not necessary. Enhancing elephant to accept tags {n...} too use first letters of name like we do for {u...} or {t...} can be done.

You right. The particularity, here, is we can predefine the client code: when creating a new client the name is empty at very beginning. So my strategy does only work at the first update (or it requires a javascript part)

What do you think @eldy ?

**Comment by iLLixM** [comment]
The original problem that you cannot currently change the `code_client` or the `code_compta` via API should, in my opinion, be able to be solved. According to the "REST API Explorer", the API call `put /thirdparties/{id}` is only permitted if an existing third-party ID is provided as a parameter. Therefore, interactions or errors with the auto-generation of the "customer code" / code_client should be excluded by design.

There is also a thread running in the forum about this:
https://www.dolibarr.org/forum/t/third-parties-changing-customer-code-code-client-via-api-isnt-possible/29520

It was already assessed in an earlier issue #18146 that the current code implementation must be an error. Unfortunately, the issue was not pursued further.

If there are no opposing views, I will make a change via pull request to branch 20.0 as follows:
Change the parameters # 4 and 5 in `api_thirdparties.php` on line [324 ](https://github.com/Dolibarr/dolibarr/blob/8e1e980aae2134464a360c65960397c432620eb2/htdocs/societe/class/api_thirdparties.class.php#L324) from unset to the value 1
`if ($this->company->update($id, DolibarrApiAccess::$user, 1, '', '', 'update')) {` (before)
`if ($this->company->update($id, DolibarrApiAccess::$user, 1, 1, 1, 'update')) {` (after)

**Comment by lebouquetin** [comment]
Thanks all !
