### ISSUE TITLE
Misleading title for purchase orders

### ISSUE THREAD

**Issue by leonbrehme** [Dolibarr/dolibarr#30456]
### Bug

I have just noticed that the PDFs of the supplier orders are unclear. If you create an order in the system and have not placed an order, the PDF can still be read as if the order has been placed.

There is a small red note at the top. But I think most people overlook it. In the case of a draft (e.g. for a quotation), it is very clear that it has not been released.

For us, the problem arises in connection with tenders that we agree orders that we only commission after approval. As the partners (often smaller offices) still want to have something for their records, these documents are useful. However, they are misleading.

To solve this, we should add a large note at the top of the PO number stating that the order has not been placed.

### Dolibarr Version

19

### Attached files

![Screenshot 2024-07-24 16 29 04](https://github.com/user-attachments/assets/3888712a-8e4a-4a93-a295-81fc62ab1c8c)

**Comment by leonbrehme** [comment]
Since I unfortunately don't know how and where to change this, I have to report it as a bug ...

**Comment by sonikf** [comment]
Ηι @leonbrehme 
I think that we should replicate other templates default behavior like "VendorOrder (PROV25) - Not validated" and ommit "Order to process" message.
Do you agree?

**Comment by leonbrehme** [comment]
I agree.
We just have to remember that purcase orders have one step more than the others:
![Screenshot 2024-07-25 15 55 57](https://github.com/user-attachments/assets/0afab633-cd8a-459f-9f0c-92d08793fce5)
