### ISSUE TITLE
Add due amount for invoice in compta/facture/list.php

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#30495]
### Feature Request

Missing total rest due
![image](https://github.com/user-attachments/assets/47c49978-c036-40cf-a007-027628fb9181)
Total Due is 0,02
![image](https://github.com/user-attachments/assets/220b0127-a70b-4b30-b022-4f843f2e7eba)

**Comment by aspangaro** [comment]
@lmag The column already exists since long years... and is summable, it is called "Pending" ("Créance" in French) and "Received" ("Reçu" in French)

![image](https://github.com/user-attachments/assets/fb091cc5-d513-4cbf-90fb-44c845a0089b)
