### ISSUE TITLE
when creating a service, duration doesn't save if the value is lower than 1 (ex: 0.5 or 0,5) 

### ISSUE THREAD

**Issue by maurerdidier** [Dolibarr/dolibarr#30503]
### Bug

when creating a service, duration doesn't save if the value is lower than 1 (ex: 0.5 or 0,5) 

environment:
Apache/2.4.59 (Win64) PHP/8.2.18 mod_fcgid/2.3.10-dev
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
System is running on wampserver 3.3.5 64 bits, in a virtual machine.

### Dolibarr Version

21.0.0-alpha

### Environment PHP

8.2.18

### Environment Database

MySQL or MariaDB 8.3.0 (mysqli (mysqlnd 8.2.18))

### Steps to reproduce the behavior and expected behavior

Create a new service (ex: consulting service), fille the values, save. the duration value is not saved when the value is less than 1, for example 0.5/d man. There is no error showing.

**Comment by ems-co** [comment]
because thats why there are many units for the duration, you should write 12hours instead of 0.5day. 

The issue you’re encountering happens because of the substr function in PHP, it can cause problems with numeric values that have a decimal point.

and the other units are available for a reason

**Comment by maurerdidier** [comment]
Hello, maybe just add a comment for the user to enter integer value (?) 

Thank you for your reply in the previous comment.
