### ISSUE TITLE
Odt to PDF generation error in draft mode

### ISSUE THREAD

**Issue by alainabbas** [Dolibarr/dolibarr#3050]
when the script is called odf2pdf.sh with draft piece (with '(') the filename is not escaped that makes an error
in htdocs/includes/odtphp/odf.php the filename is not escaped 
## this is the patch to resolve the issue  : 

--- sources/doli/htdocs/includes/odtphp/odf.php 2015-04-13 13:02:06.000000000 +0
200
+++ new/doli/htdocs/includes/odtphp/odf.php 2015-06-15 10:17:44.000000000 +0
200
@@ -488,9 +488,9 @@

```
    $name=str_replace('.odt', '', $name);
    if (!empty($conf->global->MAIN_DOL_SCRIPTS_ROOT)) {
```
-           $command = $conf->global->MAIN_DOL_SCRIPTS_ROOT.'/script
  s/odt2pdf/odt2pdf.sh '.$name;
-           $command = $conf->global->MAIN_DOL_SCRIPTS_ROOT.'/script
  s/odt2pdf/odt2pdf.sh '.escapeshellcmd($name);
      }else {
-           $command = '../../scripts/odt2pdf/odt2pdf.sh '.$name;
-           $command = '../../scripts/odt2pdf/odt2pdf.sh '.escapeshe
  llcmd($name);
      }
  --------------

**Comment by rdoursenaud** [comment]
Hi @alainabbas.
Your patch has been mangled by the markdown renderer. Please make a pull request.
See https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md for basic instructions.
Thanks.

**Comment by alainabbas** [comment]
Hello i did it
Regards

**Comment by rdoursenaud** [comment]
@alainabbas Almost there, now you just need to create a pull request from your forked repository: https://help.github.com/articles/creating-a-pull-request/

**Comment by alainabbas** [comment]
Hello 
Done
