### ISSUE TITLE
Bad VAT rate in adding supplier order line with product without price and Supplier without VAT

### ISSUE THREAD

**Issue by jere63fr** [Dolibarr/dolibarr#30514]
### Bug

When we add a product without a buying price  to a supplier order, with a supplier with no VAT the fonction select_produits_fournisseur force the VAT rate in hidden input field to the default VAT. It should be 0.

### Dolibarr Version

19.0.2

### Environment PHP

7.3

### Environment Database

MySQL 8.0.27

### Steps to reproduce the behavior and expected behavior

- Set a supplier with no VAT
- Set a product without buying price
- Create a supplier order 
- Add a line with the product ("Be careful the VAT showed is good 0, but when you validate you have the default tva rate cause it's set in the hidden field") 

### Attached files

![image](https://github.com/user-attachments/assets/7b782f14-8e09-4d33-becc-a7ae8dae56fc)
![image](https://github.com/user-attachments/assets/c6a98bff-e2b4-4cc8-80d1-c01974bd54a6)

In html.form.class.php  function select_produits_fournisseurs_list there is no check on Supplier VAT management

`				if (is_null($objp->idprodfournprice)) {
					// There is no supplier price found, we will use the vat rate for sale
					$objp->tva_tx = $objp->tva_tx_sale;
					$objp->default_vat_code = $objp->default_vat_code_sale;
				}`

**Comment by IC-faycal** [comment]
The issue was resolved in version 21. Now, for suppliers not subject to VAT, the VAT rate is set to 0 by default when adding a product line. traduit
