### ISSUE TITLE
Bug: Acconting --> Reports --> By third parties

### ISSUE THREAD

**Issue by swoop124** [Dolibarr/dolibarr#30549]
# Bug
Accounting --> Reporting --> Turover invoiced/Turover collected --> By third parties displays only one Customer

## Environment
- **Version**: 19.0.2
- **OS**: Linux
- **Web server**: Apache/2.4.59 (Debian)
- **PHP**: apache2handler 7.4.33
- **Database**: MySQL or MariaDB 5.5.5-10.5.23-MariaDB-0+deb11u1
- **URL(s)**: /dolibarr/compta/stats/casoc.php

## Expected and actual behavior
When displaying "By third praties" there should be a list of invoiced/collected Income, when selected a category or tag also.

## Steps to reproduce the behavior
1. go to Accounting --> Reporting --> Turover invoiced or Turover collected
 2. click "By third parties"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![grafik](https://github.com/user-attachments/assets/56f69d8c-83f1-4702-b17e-8affe0504872)

**Comment by swoop124** [comment]
hey everyone,

am i the only one with this problem?

**Comment by sonikf** [comment]
Hi @swoop124 
Please search before creating new issues, this bug has been reported and fixed since end of May.
Apply fix from here https://github.com/Dolibarr/dolibarr/pull/29763/files or wait for 19.0.3 to be released.
Please close this!

**Comment by swoop124** [comment]
hello, 

thank you.
i have just updated to 19.0.3 and now it is working, but when i want to group Tag/category then nothing happens, even when i click refresh.

**Comment by swoop124** [comment]
hello,

sorry for the late answer.
19.0.3 is working fine
