### ISSUE TITLE
Salary payment date not displayed in card

### ISSUE THREAD

**Issue by Movix** [Dolibarr/dolibarr#30576]
### Bug

When looking at the card of a salary payment the date is not displayed.
Thus editing is working.

### Dolibarr Version

19.01

### Steps to reproduce the behavior and expected behavior

look at a salary payment

**Comment by Movix** [comment]
Hello,

seems the error is in paymentsalary.class.php at line 334.
it should be 
`$this->datep = $this->db->jdate($obj->datep);`
instead of
`$this->datepay = $this->db->jdate($obj->datep);`

**Comment by aspangaro** [comment]
Thanks. I reproduced this problem in v19.0.2. I proposed another PR to simplify correction  and avoid side effects.

**Comment by Movix** [comment]
Hi,

nice :)
Just to improve my knowledge, why did you changed the code in the card file since i appears to me that the class file has a missmatch about the field name of the database ?

Movix
