### ISSUE TITLE
White screen when password is wrong using LDAP login

### ISSUE THREAD

**Issue by GMellar** [Dolibarr/dolibarr#30588]
### Bug

I recently switched to LDAP login but when the password is wrong there is just a white page but no feedback to the user comparable to using normal login using the database. 

### Dolibarr Version

19.0.2

### Environment PHP

8.2

### Environment Database

postgresql

**Comment by W1W1-M** [comment]
I've managed to reproduce this bug on a standard Dolibarr 19.0.3 install with Apache 2.4 & PHP v8.2, a fix will need to be made.

FYI, no problem with PHP 8.0
