### ISSUE TITLE
Multicompany_page.php

### ISSUE THREAD

**Issue by MUzayr** [Dolibarr/dolibarr#30598]
### Bug

I saw multicompany_page.php in the repository but there is no module or page in the Current dolibarr branch when serve .

### Dolibarr Version

21.0.0

### Environment PHP

8.1

### Environment Database

Mysql current version

### Steps to reproduce the behavior and expected behavior

Serve on localhost

**Comment by hregis** [comment]
@MUzayr  it's for the DoliDroid application when the Dolibarr uses the Multicompany module.
