### ISSUE TITLE
Delete button should be the last button in the action bar

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3059]
Version: 3.7.1
Page: /contact/card.php?id=1

![captura de pantalla 2015-06-16 a las 19 55 03](https://cloud.githubusercontent.com/assets/168744/8190237/c90d5f04-1461-11e5-86a9-6105068704e5.png)

**Comment by rdoursenaud** [comment]
:+1:

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
