### ISSUE TITLE
`Facture::createFromContract()` used for Contract and Facture which is incompatible

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#30600]
### Bug

`Facture::createFromContract()` is used two times, in [api_invoices.class.php](https://github.com/Dolibarr/dolibarr/blob/a940b54fcf41bb5c3629ee9ede4409f4132b7dd4/htdocs/compta/facture/class/api_invoices.class.php#L395)
 where the object is a `Contrat` and once in
[htdocs/public/payment/paymentok.php](https://github.com/Dolibarr/dolibarr/blob/a940b54fcf41bb5c3629ee9ede4409f4132b7dd4/htdocs/public/payment/paymentok.php#L1759)

`Facture::createFromContract()` is not compatible with Contrat and `Facture::createFromCurrent()` seems more appropriate to clone an invoice.

### Dolibarr Version

develop

**Comment by homer8173** [comment]
Hello, 
I just tested it and it seems to work pretty well.
I close, feel free to reopen with more information.
thanks
