### ISSUE TITLE
Dispatch and ventilate to stocks impossiblr

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#3062]
It seems on a 3.8 Version dernière mise à jour    3.8.0-alpha

not possible to ventilate a supplier'rs order to the stocks ...

/fourn/commande/dispatch.php?id=11

![bug 3 8 impossible to ventilate](https://cloud.githubusercontent.com/assets/3694135/8203717/276ba218-14e4-11e5-9ced-ed27f4d4a680.JPG)

![image](https://cloud.githubusercontent.com/assets/3694135/8203792/a05f31da-14e4-11e5-89cc-8265545aff8a.png)

**Comment by fappels** [comment]
@BebZ Fixed in PR #3068
