### ISSUE TITLE
ldap + php 8 : dolibarr native user not able to connect

### ISSUE THREAD

**Issue by maiido** [Dolibarr/dolibarr#30669]
### Bug

Hello,

if I want to be able to connect with the dolibarr admin user but ldap is active, I have to modify the following lines (dolibarr/htdocs/core/login/functions_ldap.php) otherwise I get this error: Uncaught Error: LDAP connection has already been closed

![image](https://github.com/user-attachments/assets/81041b2e-5088-4d01-8e9e-f808b1c859c9)

I have this issue since dolibarr supports php 8 (no issue in php 7.4)

### Dolibarr Version

19.0.3

### Environment PHP

8.3

**Comment by W1W1-M** [comment]
Hello,
In order to analyse the problem, can you provide the LDAP conf from your Dolibarr `conf.php` ?

**Comment by maiido** [comment]
![image](https://github.com/user-attachments/assets/676ead87-e98f-4256-a866-b77066557622)

**Comment by W1W1-M** [comment]
I've managed to reproduce this bug on a standard Dolibarr 19.0.3 install with Apache 2.4 & PHP v8.2, a fix will need to be made.

FYI: 
- no problem with PHP 8.0
- PHP 8.3 isn't _officially_ supported by Dolibarr v19: https://wiki.dolibarr.org/index.php/List_of_releases,_change_log_and_compatibilities
- https://www.php.net/manual/en/function.ldap-errno.php
- https://www.php.net/manual/en/function.ldap-connect.php
