### ISSUE TITLE
Can't upgrade from 19.0.2 to 19.0.3 (DB error)

### ISSUE THREAD

**Issue by ro78** [Dolibarr/dolibarr#30686]
### Bug

Hello,

I can't upgrade from 19.0.2 to 19.0.3, I'm getting this error:

`Request 108 sql='UPDATE llx_c_tva SET taux = 3, note = 'Νήσων υπερμειωμένος Φ.Π.Α.' WHERE fk_pays = 102 AND taux = 16;'
--
Erreur DB_ERROR_1366 (Req 108): UPDATE llx_c_tva SET taux = 3, note = 'Νήσων υπερμειωμένος Φ.Π.Α.' WHERE fk_pays = 102 AND taux = 16;Incorrect string value: '\xCE\x9D\xCE\xAE\xCF\x83...' for column `dolibarr`.`llx_c_tva`.`note` at row 187`

### Dolibarr Version

19.0.3

### Environment PHP

8.2.22

### Environment Database

MariaDB 10.11.6-MariaDB-0+deb12u1

### Steps to reproduce the behavior and expected behavior

Upgrade from 19.0.2 to 19.0.3

**Comment by ro78** [comment]
I fixed it by removing the note from
`UPDATE llx_c_tva SET taux = 3, note = '' WHERE fk_pays = 102 AND taux = 16;`
in /install/mysql/migration/18.0.0-19.0.0.sql

**Comment by edupulpillo** [comment]
is possible to update this fix in the current 19.0.3 version? or is needed to launch a new 19.0.4 version with this fix included?
The update in my installation also fails.

**Comment by sonikf** [comment]
Ηι @ro78 @edupulpillo 
This error is not a bug, but means that your db does not support Greek characters.
If you had proceeded with the upgrade the result would have been the same with the removal of the line from migration file.
If you change your db collation to utf8mb4_unicode_ci you will not have errors like this again cause it supports also non latin languages, emojis, math expressions etc.

**Comment by ro78** [comment]
@sonikf the encoding of each tables was defined by Dolibarr installation wizard, so if a change is required, why not changing the encoding during the upgrade wizard ?

**Comment by sonikf** [comment]
Dolibarr uses utf8_unicode_ci which is the current suggested collation
where  utf8 is a deprecated alias for utf8mb3.
The "problems" started with the growth and adoption of Dolibarr from non latin users like me. Greetings from Greece by the way.
Full disclosure  I'm the "culprit" commiting  the change in 18.0.0-19.0.0.sql for my country.
As you can see here https://dev.mysql.com/doc/refman/8.4/en/charset-unicode-sets.html
They suggest using utf8mb4 now and in a feature update that will be the alias for utf8.

**Comment by edupulpillo** [comment]
HI. In my case i am using english characters, but the update procedure is stopped. How to update a running installation to utf8mb4? ( currently using utf8)

**Comment by edupulpillo** [comment]
> @sonikf the encoding of each tables was defined by Dolibarr installation wizard, so if a change is required, why not changing the encoding during the upgrade wizard ?

Exactly

**Comment by sonikf** [comment]
Usually you can ignore the error and continue.
What is your db collation?
You can run this script /install/repair.php?force_utf8mb4_on_tables=confirmed to try and remedy
Sorry edited for correct script...

**Comment by ro78** [comment]
@sonikf I use utf8mb4_general_ci

**Comment by sonikf** [comment]
Hi @ro78 
see previous comment and run script to change to utf8mb4_unicode_ci

**Comment by ro78** [comment]
@sonikf applied it (but I'm still running 19.0.3 with my own fix described in my first answer), should be good for next updates.

**Comment by sonikf** [comment]
@ro78
Please close this

**Comment by edupulpillo** [comment]
/admin tools/about Dolibar: 19.0. 3
/admin tools/about PHP: 8.1.29
MySQL or MariaDB 10.6.19-MariaDB
Inside Dolibarr  /admin tools/about database
Database charset to store data	latin1
Database charset to sort data	latin1_swedish_ci

as i can see, migrating from one charset to another have risk of data loose.
Is it necessary to manuually run this commands to change the current content of the tables in a production environment of Dolibarr?

Change the default charset and collation for new tables
ALTER DATABASE database_name
CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

Automating the Charset Change for the content of All the Tables:
SELECT CONCAT('ALTER TABLE `', table_name, '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;') 
FROM information_schema.TABLES 
WHERE table_schema = "database_name";

Charset Change for one table:
ALTER TABLE table_name CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

How can is needed to specify and update the connection to the database with the new charset in Dolibar?
SET collation_connection = 'utf8mb4_unicode_ci'

**Comment by sonikf** [comment]
Hi @edupulpillo 
For many years the default for MySQL would be latin1_swedish_ci just because the developer is Scandinavian. Do you think it is a sane default to have in your db?
If you are in doubt back up your db and try the script in my previous comment, you don't have to do this manually.

**Comment by edupulpillo** [comment]
@sonikf Hi! We did my first dolibarr installation with version 9.0.3 and all the following updates was performed following the update scripts of each version from cpanel in a shared hosting, without any another manual intervention by our side.
So if the charset and collation was need to be updated, we think it should be managed by the update scripts, since there is no present any warning explaining this task is needed to do it in any of the previous updates.
So if i understood well, we need to use in the browser the url:
`www.mydomain.com/install/repair.phpforce_utf8mb4_on_tables=confirmed
`then a repair database process will start am i right ?
thanks for your message and support!

**Comment by sonikf** [comment]
Ηι @edupulpillo yes but there is an error in your path(? is missing) 
`www.mydomain.com/install/repair.php?force_utf8mb4_on_tables=confirmed`

**Comment by edupulpillo** [comment]
Hi @sonikf  after run the url you mentioned
https://www.mydomain.com/install/repair.php?force_utf8mb4_on_tables=confirmed
two tables return this failure message:
llxzn_accounting_account - Done (KO)
llxzn_accounting_system - Done (KO)
all the anothers return OK.

But seems nothing was really changed, since checking inside Dolibarr the menu Admin Tools/About Dolibarr
https://www.mydomain.com/admin/system/dolibarr.php?mainmenu=home&leftmenu=admintools_info

the info displayed about the charset and collation still is the same: 
Database charset to store data	dolibarr_main_db_character_set	**utf8**
Character sorting order	dolibarr_main_db_collation	**utf8_general_ci**

and  checking the menu Admin Tools/About Database
https://www.mydomain.com/admin/system/database.php?mainmenu=home&leftmenu=admintools
still displays the same:

Database charset to store data	**latin1**
Database charset to sort data	**latin1_swedish_ci**

so we have the same values we had before running the repair tool.
do we need to do somethng else to make dolibarr use the new charset/collation?

**Comment by hregis** [comment]
@edupulpillo the best solution is to dump the database and edit it, then search for "latin1_swedish_ci" and replace it with "utf8mb4_unicode_ci", then search for "latin1" and replace it with "utf8mb4". Then you restore the database and you have to modify the conf.php file, the variables "$dolibarr_main_db_character_set" and "$dolibarr_main_db_collation"
If you have problems, you can also use "utf8mb3" and "utf8mb3_unicode_ci"

**Comment by edupulpillo** [comment]
Hi again.
We have updated the conf.php file
before `$dolibarr_main_db_character_set='utf8'` now is `$dolibarr_main_db_character_set='utf8mb4'`
before `$dolibarr_main_db_collation='utf8_general_ci'`  now is `$dolibarr_main_db_collation='utf8mb4_unicode_ci'`
then checking inside Dolibarr the menu Admin Tools/About Dolibarr, now is updated and the info displayed is 
```
Database charset to store data dolibarr_main_db_character_set utf8mb4
Character sorting order dolibarr_main_db_collation utf8_general_ci utf8mb4_unicode_ci
```
After running the repair script, we did a dump of the DB and we did not find any string "latin1" or "latin1_swedish_ci" inside, but dolibarr still display the same in Admin Tools/About Database
```
Database charset to store data latin1
Database charset to sort data latin1_swedish_ci
```
QUESTION1: do we need to do anything else to make Dolibarr understand that the DB now use another charset and another collation?

Here the part of the dump of the table **llxzn_accounting_account**  that the repair tool returns a KO
```
CREATE TABLE `llxzn_accounting_account` (
  `rowid` bigint(20) NOT NULL,
  `entity` int(11) NOT NULL DEFAULT 1,
  `datec` datetime DEFAULT NULL,
  `tms` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `fk_pcg_version` varchar(32) NOT NULL,
  `pcg_type` varchar(60) DEFAULT NULL,
  `account_number` varchar(32) NOT NULL,
  `account_parent` int(11) DEFAULT 0,
  `label` varchar(255) NOT NULL,
  `labelshort` varchar(255) DEFAULT NULL,
  `fk_accounting_category` int(11) DEFAULT 0,
  `fk_user_author` int(11) DEFAULT NULL,
  `fk_user_modif` int(11) DEFAULT NULL,
  `active` tinyint(4) NOT NULL DEFAULT 1,
  `reconcilable` tinyint(4) NOT NULL DEFAULT 0,
  `import_key` varchar(14) DEFAULT NULL,
  `extraparams` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC;
```
Here the part of the dump of the table **llxzn_accounting_system** that the repair tool returns a KO
```
CREATE TABLE `llxzn_accounting_system` (
  `rowid` int(11) NOT NULL,
  `pcg_version` varchar(32) NOT NULL,
  `label` varchar(128) NOT NULL,
  `active` smallint(6) DEFAULT 0,
  `fk_country` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC;
```
QUESTION2:  maybe do we need specify in the repair tool any additional parameter to repair the both tables mentioned and get a OK instead a KO answer?  

Using phpMyAdmin and searching "latin1" in the structure of the table, we get the following (it seems the dump do not include this)

![image](https://github.com/user-attachments/assets/fabce11d-835c-456f-825f-151178a8b761)

QUESTION3:  maybe we still need to manually update the database with phpMyAdmin using
`ALTER DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`
or the dolibarr repair tool have any parameter to do it? (We did it already manually using phpMyAdmin) 
QUESTION4:  Is here any danger that can corrupt the data of the database? What still do we need to do to update the charset and collation in the db? 
QUESTION5: After the update of the db to the ne charset and the new collattion, the repair tool, still returns a KO for the both tables mentioned. What can we do to fix it?

Thanks in advance for your kind support!

**Comment by sonikf** [comment]
Hi @edupulpillo 
1. No
2. No
3. See 5.
4. There is always a danger mostly in case you use special characters.
That's why we always backup, backup and backup and test in a backup instance before making any changes or upgrade.
5. I tested and there is a constraint on 'fk_pcg_version' between those 2 tables.
To overcome this press the operations button in phpMyAdmin but before this again backup and check after the 2 tables(this really matters only if you use the double accounting module) 
![2024-08-30_10-22](https://github.com/user-attachments/assets/6322ceda-3fc9-4d5f-a66d-6f39bad62119)

**Comment by edupulpillo** [comment]
Hi!.
4.) Yes, backups always performed before any operations procedure as a first rule!
I guess that there is not another way to check that the data are ok, except check it visually inside the table, am i right? 
5) We did it but unfortunately PhpMyadmin return this error
![image](https://github.com/user-attachments/assets/03f6afe8-9abe-430c-8c1e-191fad10352f)


THank you for your patience and support.
We hope fixing this case help anothers, and help to improve the upgrading script!

**Comment by sonikf** [comment]
5. Try again from database level, don't select any tables.

**Comment by edupulpillo** [comment]
We get the error message doing it at database level without any table selected.
Is possible to delete the foreign key involved, and then run the dolibarr's repair tool again to make that foreign key be recreated ?
Can you help with the commands steps necessary ?

**Comment by edupulpillo** [comment]
After performing the sql command at database level without any table selected, even no errors arise, still the 2 tables do not change the collation and charset. 

QUESTION1:  Maybe a solution is to delete in the database the foreign key, apply the update of the collation to the both tables,  and create the foreign key again ? (Maybe also a solution to implement in the dolibarr repair tool?  What is the sql command necessary to use? 
QUESTION2: Is safe to keep these 2 tables with different charset and collation in the fields that the rest of the database?
QUESTION3: If the end user allows to loose the data of the accounting, is possible to delete the two tables in the database, and then activate the double accounting module again, to make dolibarr generate the 2 tables again with the right collation and charset? 

The export of the tables involved are the following, to understand well the fields involved in both tables:
**llxhh_accounting_account**
`CREATE TABLE `llxhh_accounting_account` (
  `rowid` bigint(20) NOT NULL,
  `entity` int(11) NOT NULL DEFAULT 1,
  `datec` datetime DEFAULT NULL,
  `tms` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `fk_pcg_version` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `pcg_type` varchar(60) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `account_number` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `account_parent` int(11) DEFAULT 0,
  `label` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `labelshort` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `fk_accounting_category` int(11) DEFAULT 0,
  `fk_user_author` int(11) DEFAULT NULL,
  `fk_user_modif` int(11) DEFAULT NULL,
  `active` tinyint(4) NOT NULL DEFAULT 1,
  `reconcilable` tinyint(4) NOT NULL DEFAULT 0,
  `import_key` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `extraparams` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
`
**llxhh_accounting_system**
`CREATE TABLE `llxhh_accounting_system` (
  `rowid` int(11) NOT NULL,
  `fk_country` int(11) DEFAULT NULL,
  `pcg_version` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `label` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `active` smallint(6) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
`

**Comment by sonikf** [comment]
Hi @edupulpillo 

1. I think it's the safest way
` ALTER TABLE `llx_accounting_account` DROP INDEX `idx_accounting_account_fk_pcg_version`; `
`ALTER TABLE llx_accounting_account ADD INDEX idx_accounting_account_fk_pcg_version (fk_pcg_version);`

2. Yes it is safe

3. Better to not go that way

**Comment by edupulpillo** [comment]
Hi!
Unfortunately 1 still is not working.
`ALTER TABLE llxzn_accounting_account DROP INDEX idx_accounting_account_fk_pcg_version;`
returns the following error:
`#1553 - Cannot drop index 'idx_accounting_account_fk_pcg_version': needed in a foreign key constraint`
this is the list of indexes in the both  tables:

`SHOW INDEX FROM llxzn_accounting_account;`
![image](https://github.com/user-attachments/assets/73320af3-7d48-4594-83cb-947a1e8a1c37)
`SHOW INDEX FROM llxzn_accounting_system;`
![image](https://github.com/user-attachments/assets/011f8f0e-2718-4f4b-9435-6ec9fbb1e0a4)

**Comment by sonikf** [comment]
Hi @edupulpillo 

Please move the discussion to the Dolibarr  [forum](https://www.dolibarr.org/forum/) or wait for v 20 to try again since it's now fixed there.
