### ISSUE TITLE
Eldy theme issue.

### ISSUE THREAD

**Issue by ems-co** [Dolibarr/dolibarr#30731]
### Bug

i have just encountered with an issue on the Eldy theme, which is the placement of side menu on the right or left for rtl or ltr languages, for ltr languages there is no problem, but for the rtl languages the side menu is supposed to be on the Right but in some tabs it is going back to Left! and the Md theme is not having this problem! 

i have searched deeply inside the theme style.css.php file but could not figure out how to fix it

### Dolibarr Version

19.0.2

### Environment PHP

8.3

### Environment Database

mysql 

### Steps to reproduce the behavior and expected behavior

1- Change the display language to Arabic.
2- go to products -> product card
3- now go to the selling prices or buying prices
4- the menu is moving to the left side and goes back to the right when changing the tabs
<img width="1446" alt="Screenshot 2024-08-23 at 12 07 13 AM" src="https://github.com/user-attachments/assets/63dff087-078e-4c9b-865b-347385c857a1">
<img width="1443" alt="Screenshot 2024-08-23 at 12 07 23 AM" src="https://github.com/user-attachments/assets/daeb1ff3-82cc-4ce7-ae4a-90e6c9cc440c">

**Comment by hregis** [comment]
@ems-co and for the Jews, are they on the left or on the right for you?

**Comment by ems-co** [comment]
> @ems-co and for the Jews, are they on the left or on the right for you?

what do you mean by jews?

**Comment by hansemschnokeloch** [comment]
It's an issue with `classforhorizontalscrolloftabs`

**Comment by eldy** [comment]
Thanks for solution [hansemschnokeloch](https://github.com/hansemschnokeloch). This help me to add other similar fixes. Now (in v20+):
![image](https://github.com/user-attachments/assets/3454535c-ea18-4135-8243-adb789c58e3b)
