### ISSUE TITLE
Accruals accounting use payment date instead of commitment date in turnover reports for salaries

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3074]
When using accruals accounting, the salaries should be accounted at the commitment date, not the payment date.

Ping @aspangaro for confirmation.

**Comment by aspangaro** [comment]
Hi @rdoursenaud 

For the question, I confirm this information for income statement but not in the journal, the date is the date of the payment in the last step.

(En français (Peur de mal m'exprimer) : Pour la question, je te confirme que pour le compte de résultat, il faut tenir compte de la période concernée (Principe de séparation des exercices) mais pour le reste, c'est la date de paiement qui joue dans le journal de banque et le bilan. Le comptable repasse une provision de charge à payer au pire. En plus, nous sommes sur des montants nets, nous sommes donc plus sur le dernier cas. N'hésite pas à me traduire au besoin.

Salaries module are not in the branch 3.5.x, can you remove it in labels ?

**Comment by rdoursenaud** [comment]
Yep, I was talking about the income reports at `/compta/resultat/index.php` and `compta/resultat/clientfourn.php`. Thanks for the confirmation :)
