### ISSUE TITLE
Payment date on invoice and writebank date

### ISSUE THREAD

**Issue by aconits** [Dolibarr/dolibarr#3075]
Currently if we modify the payment date, the writebank date isn't modify.
Is it logical to automatise the process if I modify the payment date and this automatically change the writebank date ?

**Comment by rdoursenaud** [comment]
I have mixed feeling about it. I'd say yes but if and only if the bank entry is not reconciliated.

**Comment by eldy** [comment]
I agree with Raphael. Let's go for the enhancement.
If reconciliated ($bankline->rappro is set), just do not update the date
