### ISSUE TITLE
Email templates dictionary page should use relative width

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3077]
Version: 3.7.1

![captura de pantalla 2015-06-21 a las 14 44 03](https://cloud.githubusercontent.com/assets/168744/8271671/fe039140-1823-11e5-9bd6-76d9be3baccd.png)

**Comment by marcosgdf** [comment]
All the rest of dictionary pages are working this way, so this might be more a Feature request than a bug

**Comment by atm-maxime** [comment]
Has been done now I think ;)
