### ISSUE TITLE
Add Hook in dol_print_socialnetworks function

### ISSUE THREAD

**Issue by catrielr** [Dolibarr/dolibarr#30796]
### Feature Request

Add a Hook like in the dol_print_phone function. (../htdocs/core/lib/function.lib.php)
One of the reasons is, for example, adding unread chats on WhatsApp or Telegram, etc.

![imagen](https://github.com/user-attachments/assets/9ae60bee-8f71-4e53-981b-51f6b9af06e1)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/30797
