### ISSUE TITLE
erreur MySQL dans le script de migration 3.6 -> 3.7.1

### ISSUE THREAD

**Issue by cy-altern** [Dolibarr/dolibarr#3079]
lors de la migration 3.6 -> 3.7.1 le script de migration donne l'erreur suivante:
Request 97 sql='ALTER TABLE llx_c_regions ADD CONSTRAINT fk_c_regions_fk_pays FOREIGN KEY (fk_pays) REFERENCES llx_c_country (rowid);'
Erreur DB_ERROR_2013: ALTER TABLE llx_c_regions ADD CONSTRAINT fk_c_regions_fk_pays FOREIGN KEY (fk_pays) REFERENCES llx_c_country (rowid);
Lost connection to MySQL server during query
Les symptômes sont identiques à ceux de https://github.com/Dolibarr/dolibarr/issues/2951
version de MySQL: 5.5.43-0+deb7u1-log

**Comment by atm-maxime** [comment]
This issue seems to be solved in #2951 . Should we close this ont as a duplicate ?

**Comment by cy-altern** [comment]
in #295 comments says: "Your mysql version must be at least 5.5.43" 
=> this ticket may be a duplicate except the fact I have a 5.5.43 MySQL version wich is supposed to be not affected

**Comment by eldy** [comment]
This is a mysql 5.5.\* bug.
Mysql must be at leat 5.5.43 to be sure to not loose data when this bug ocurs. But if it ocurs also with 5.5.43' the only solution is to upgrade to mysql 5.6.\* or mariadb
no way to fix this in dolibarr since it is mysql bug.
