### ISSUE TITLE
Ressources non prise en compte lors de la création d'un évènement dans l'agenda

### ISSUE THREAD

**Issue by Jereld52** [Dolibarr/dolibarr#30845]
In english :

Bug
When creating an event in the calendar, even though it is possible to add a resource, it is not taken into account after submitting the form.

We are forced to return to the event to add the resource again.

Resources not taken into account when creating an event in the calendar.

Dolibarr Version
19.0.3

Environment PHP
No response

Environment Database
No response

Steps to reproduce the behavior and expected behavior
Create an event and add a resource via the form.
Return to the event in the calendar to find that it was not taken into account.

Attached files
No response

En francais :

### Bug

Lors de la création d'un évènement dans l'agenda, malgré la possibilité d'ajouter une ressource, celle ci n'est pas prise en compte après la validation du formulaire.

Nous sommes obligés de retourner sur l'évènement pour ajouter à nouveau la ressource.

Ressources non prise en compte lors de la création d'un évènement dans l'agenda

### Dolibarr Version

19.0.3

### Steps to reproduce the behavior and expected behavior

Créer un évènement et ajouter une ressource via le formulaire.
Retourner sur l'évènement dans l'agenda pour constater que celui-ci n'est pas pris en compte.

**Comment by W1W1-M** [comment]
Hello, 
I can also confirm that this bug is in v21

**Comment by freechelmi** [comment]
Can you please convert your issue in english language ? 
Thanks

**Comment by adminuc** [comment]
Hi, I think the issue is the same as : https://github.com/Dolibarr/dolibarr/issues/29732

You can't link anymore an Object or a Ressource to an event since the 19.0.2.

**Comment by adminuc** [comment]
Hello, 

The issue is still present in version 20.0.1.

**Comment by adminuc** [comment]
Hello, 

The issue is still present in version 20.0.1.

**Comment by adminuc** [comment]
Fixed in v20.0.2 @Jereld52

**Comment by Jereld52** [comment]
> Fixed in v20.0.2 @Jereld52

Thank you for your feedback; unfortunately, it still doesn't work in 20.0.2. :-(
