### ISSUE TITLE
Dispatch to stock multiple batches impossible

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#3085]
![image](https://cloud.githubusercontent.com/assets/3694135/8306149/f9d6077c-19b5-11e5-9d89-caa1d1665933.png)

ths samll button doesn't work anymore on 3.7.1, migrated recently !
help ! that was a non-tested function we are blocked for some reeptions of products
@KreizIT @fappels @eldy

**Comment by fappels** [comment]
You can fix it by changing line 22 in htdocs/core/js/lib_batch.js
change 
`function AddLineBatch(index) {` 
to 
`function addLineBatch(index) {`

**Comment by BebZ** [comment]
closed #3087

**Comment by rdoursenaud** [comment]
@fappels The syntax for closing issues automatically is Fix [space] #bugnum.
See https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md#commits
This reduces the burden on maintainers ;)
Thanks!

**Comment by BebZ** [comment]
Fix#3085 viahttps://github.com/fappels/dolibarr/commit/63df278ecaf724199e087311d7566c7368d47925

**Comment by rdoursenaud** [comment]
@BebZ The message was for fappels and this only works into commits _not_ comments…
