### ISSUE TITLE
Cron task error to backup on PHP 8.2

### ISSUE THREAD

**Issue by ns-info90** [Dolibarr/dolibarr#30863]
### Bug

In the task scheduler, when a local database backup is launched
The result is this message 
External command execution fails. Check that it is available and executable by the user of your PHP server. Also check that the command is not protected at shell level by a security layer such as apparmor.

### Dolibarr Version

19.0.3

### Environment PHP

Php 8.2

### Environment Database

MariaDB 10.6.18

**Comment by ksar-ksar** [comment]
Hello,

There are a lot of possibilities for this not to work :

- Are you sure that the backup command is OK ?
- Did you check the server logs ?
- How do you know it"s a PHPV8.2 issue ,

**Comment by ns-info90** [comment]
Hello,
Same test performed with PHP 7.4 without any error
The version of Maria DB is not the same, so we could also blame Maria DB.

**Comment by ns-info90** [comment]
Error related to the database and not to Dolibarr
