### ISSUE TITLE
Extra Field tag for ODT

### ISSUE THREAD

**Issue by ayssi** [Dolibarr/dolibarr#30891]
### Bug

Hi everyone,
Knowing that I'm using Dlibarr 19.0.3, I want to display a customer's extra field on an ODT file using the tag: {options_XXX} but it doesn't work.
Any suggestions?
**N.B**: I also use this tag : [company_options_XXX} but with no result.

### Dolibarr Version

Dolibarr 19.0.3

### Environment PHP

php 8.2

### Environment Database

Mysql

**Comment by ems-co** [comment]
Try using this
{contact_options_xxx}
or
{object_options_xxx}

**Comment by hregis** [comment]
@ayssi this is {company_options_xxx} but maybe sometimes there can be issues with the tag in the template, for example when a brace doesn't have the same font or size as the rest... have you tried generating the example ODT template?

https://wiki.dolibarr.org/index.php?title=Create_an_ODT_document_template

**Comment by hregis** [comment]
@ayssi try to copy/paste a tag from a simple texte edit and copy/paste after in the ODT

**Comment by hregis** [comment]
@ayssi It is also better to do ODTs with Libreoffice than with Word! I won't hide from you that Microsoft is not our friend! ;-)

**Comment by ayssi** [comment]
@hregis the problem has been solved. it was a bad copy and paste from MS Word. To solve this problem I've used Libreoffice directly.
Thank you.
