### ISSUE TITLE
Blank Dashboard V19.0.3 when enabling PHP8.1

### ISSUE THREAD

**Issue by erikvanberkum** [Dolibarr/dolibarr#30890]
### Bug

Today update my dolibarr installation to 19.0.3 and PHP to version 8.1.
This results in a Blank dashboard home screen all users. 
Switching back to 7.4 the dashboard screen is good again, but with the following warning.

```
A non-numeric value encountered (/var/www/html/dolibarr/htdocs/ticket/class/ticket.class.php:3054)
```
Staying on PHP7.4 for now. 

### Dolibarr Version

19.0.3

### Environment PHP

PHP8.1

### Environment Database

mysql

**Comment by hregis** [comment]
@erikvanberkum Do you have any external modules? and do you have the apache/php logs when you have this blank page with php8.1?

**Comment by erikvanberkum** [comment]
I did disable all external modules that did not make a difference.
Have to check the logs if i can find somethings, just reading out from the error handler at the bottom.

**Comment by erikvanberkum** [comment]
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int in /var/www/html/dolibarr/htdocs/ticket/class/ticket.class.php:3045\nStack trace:\n#0 /var/www/html/dolibarr/htdocs/index.php(243): Ticket->load_board()\n#1 {main}\n  thrown in /var/www/html/dolibarr/htdocs/ticket/class/ticket.class.php on line 3045

**Comment by hregis** [comment]
@erikvanberkum That's strange, what do you have on line 3045?

**Comment by erikvanberkum** [comment]
![ticketclass](https://github.com/user-attachments/assets/462b78c3-8d35-4e3e-937e-081de3ae7403)

**Comment by erikvanberkum** [comment]
sorry 3054 and 3045
![ticketclass2](https://github.com/user-attachments/assets/1cafdf99-4ff8-4b9a-8735-bcab5f329da5)

**Comment by hregis** [comment]
@erikvanberkum 
it is possible to have this error with this :

`$datelimit = $this->db->jdate($obj->datec) + $delay_warning;`

but not with this! it's strange!

`$response->label = $label;`

**Comment by hregis** [comment]
@erikvanberkum try to change 3054

`$datelimit = (int) $this->db->jdate($obj->datec) + (int) $delay_warning;`

**Comment by hregis** [comment]
@erikvanberkum are you sure it's 19.0.3 and not 19.0.2 ?

**Comment by erikvanberkum** [comment]
> $datelimit = (int) $this->db->jdate($obj->datec) + (int) $delay_warning;

changed to this on version 19.0.3 and enabled php 8.1 now working without error

**Comment by erikvanberkum** [comment]
![1903](https://github.com/user-attachments/assets/7d48f14a-b092-4411-902e-0bdd9f6d76bb)

Went through the upgrade.
Did not get any error during the process.

**Comment by hregis** [comment]
@erikvanberkum and change line 3045 : 

`$response->label = '';  //$label;`

**Comment by hregis** [comment]
> > $datelimit = (int) $this->db->jdate($obj->datec) + (int) $delay_warning;
> 
> changed to this on version 19.0.3 and enabled php 8.1 now working without error

@erikvanberkum ok good.... but this is the line 3054 ! and this line is for 19.0.2 ! big strange :-)

**Comment by erikvanberkum** [comment]
@hregis I have redownloaded the file from sourceforge:
https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/19.0.3/ zip version
Open the file and it looks like no error on my side with copy files:
![Screenshot 2024-09-09 081252](https://github.com/user-attachments/assets/03893641-df0f-48aa-80a0-c9573fda54e6)
Maybe the commit is not committed to the 19.0.3 branch?

**Comment by erikvanberkum** [comment]
This issue is back: blank dashboard. After upgrading from 19.0.3 to version 20.0.2

issue is fixed again, 
by changing line 3195 in /dolibarr/htdocs/ticket/class/ticket.class.php

```
$datelimit = $this->db->jdate($obj->datec) + $delay_warning;
```

to 

```
$datelimit = (int) $this->db->jdate($obj->datec) + (int) $delay_warning;
```

I am still on PHP8.1
