### ISSUE TITLE
Calculating the total weight of items on a document

### ISSUE THREAD

**Issue by easyconnect83** [Dolibarr/dolibarr#30907]
### Bug

Hi,

I noticed a bug regarding the calculation of the total weight of the items.

On a product sheet the weight indicated is 1.2 Kg.
On all quote, order, invoice and delivery note documents it is indicated 1200 Kg :slight_smile:

The calculation would not be wrong if the unit was correct in Gr.
For example If I put several items the calculation would be good for a weight in Gr. But I need the weight in Kg.

Here are the screenshots of the documents and the product sheet:

Product sheet field

![fiche produit poids - db](https://github.com/user-attachments/assets/cc47d725-0ba3-4cc3-9867-aeca8d366ffb)

Calculation on the quote

![devis poids db](https://github.com/user-attachments/assets/115e3748-8da8-4de2-9a5f-68102195aeb7)

Calculation on order

![commande poids db](https://github.com/user-attachments/assets/30770ae3-a91b-4c82-adc5-e8495f6c1452)

Calculation on the delivery note

![bon de livraison poids db](https://github.com/user-attachments/assets/fd9bcec5-9a65-4258-84e3-b198307a56fa)

Do you have an idea?
Thank you in advance.

Server environment:
Infomaniak Cloud Server

### Dolibarr Version

19.03

### Environment PHP

8.2.20

### Environment Database

MariaDB 10.6.15

**Comment by ksar-ksar** [comment]
Hello,

As explained on the French forum you should enter 1,2 not 1.2

**Comment by easyconnect83** [comment]
Hello,

Yes indeed I corrected by 1.2 and it works. On the other hand, I am obliged to correct the 1 by /1 products because in the database it is in the 1.2 format that the data is recorded. I would have liked to do an SQL query to correct 1.2 by 1.2 on the entire products table.

Thanks
