### ISSUE TITLE
Able to create an Invoice/order once a Third Party is closed

### ISSUE THREAD

**Issue by akhalz** [Dolibarr/dolibarr#3097]
Still able to create invoices for a Third Party after that third party status is closed.

**Comment by rdoursenaud** [comment]
Good catch. Seen that a while ago and forgot to report. :+1:

**Comment by eldy** [comment]
This happens rarely. And it is possible to reopen the thirdparty to make the invoice. Thisbis better than allow invoicing when we should not.

**Comment by akhalz** [comment]
Thanks for closing Eldy. The point is that once a thirdparty is closed you dont want unauthorised invoices to be created.
