### ISSUE TITLE
Nommage des fichiers PDF lorsqu'il y a un "/" dans le numéro de facture

### ISSUE THREAD

**Issue by mistraloz** [Dolibarr/dolibarr#3100]
Voici le format du numéro de facture que j'utilise : V{yy}{mm}/{000@99}

Le fait d'avoir un / dans le format fait que le fichier PDF se renomme avec un _ à la place (V{yy}{mm}_{000@99}). Le soucis c'est que pour la fusion PDF, il y a une recherche récursive sur les noms de fichier. Le filtre prends en compte "\/" à la place du "/" mais comme le fichier se nomme avec un _, il ne le trouve pas. 

J'ai résolu le problème avec un hook (voir plus bas) mais c'est du bricolage. D'autant que le problème se pose peut-être ailleurs dans dolibarr (pas constaté pour le moment). Il serait certainement judicieux de voir pour créer une fonction qui nomme le fichier pdf à partir du numéro de facture et qui génère le masque de recherche. Ainsi, les deux étant centralisés, ils auront un usage cohérent. 

Ce n'est qu'une suggestion. 

``` php
public function getNodesList($parameters, &$object, &$action, $hookmanager) {
                if(!preg_match('#\\\\/#', $parameters['filter'])) {
                        return 0;
                }
                $parameters['filter'] = preg_replace('#\\\\/#', '_', $parameters['filter']);
                $this->results = array('nodes' => dol_dir_list($parameters['path'],$parameters['types'],$parameters['recursive'],$parameters['filter'],$parameters['excludefilter'],$parameters['sortcriteria'],$parameters['sortorder']));
                return 0;
        }
```

**Comment by rdoursenaud** [comment]
Would you mind providing an english version of your report? The community is now international so we need to keep in mind that non-french people are around.

Also, please tell us what version you're running.

Thanks.

**Comment by marcosgdf** [comment]
Should we close the issue? It's been ~ 5 months

**Comment by rdoursenaud** [comment]
Yeah. Closing.
@mistraloz please reply if you want this to be reopened.
