### ISSUE TITLE
Feature Request: API help within Dolibarr

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#31029]
### Feature Request

I use another application called Netbox

And when you click on a link at the bottom of the page you have an explanation about the API calls
![image](https://github.com/user-attachments/assets/eeee24e4-6fdc-4858-a66d-84c69cfbea72)

![image](https://github.com/user-attachments/assets/88df3c22-92bf-4183-82c9-f54b146d4080)

And you get details about the structure, here's an example for the devices
![image](https://github.com/user-attachments/assets/2c4cb236-f948-4a4a-bbb5-6b15045a3237)

You can see what it's like here
https://demo.netbox.dev/plugins/demo/login/
Create a user dolibarr dolibarr
Login
Go to device/Appareil and clic at the bottom of the page as indicated in my first screenshot

### Use case

API developpement

**Comment by hansemschnokeloch** [comment]
There's a swagger in Dolibarr. 

![Swagger-UI](https://github.com/user-attachments/assets/de528d2c-76e0-40a1-a00c-e6ba44d6242a)

**Comment by mikygee** [comment]
Hello @hansemschnokeloch,
Indeed I didn't know this functionnality and after you showed me I had a hard time to configure my server to display it.
I think that page suits the needs that I requested in this request.
Thank you
