### ISSUE TITLE
SQL error return using filters in extrafields

### ISSUE THREAD

**Issue by catrielr** [Dolibarr/dolibarr#31028]
### Bug

**Extrafields Type**: sellist

**Extrafields value:**
In version 19 work with this value:  ` product:label:rowid::tosell=0`
in version 20 not work

I'm change to:  `product:label:rowid::(tosell:=:0) `

**Return error:** 
_Error in request SELECT rowid as rowid, label FROM llx_product AND ((tosell = 0)) ORDER BY label You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND ((tosell = 0)) ORDER BY label' at line 1. Check setup of extra parameters._

### Dolibarr Version

20 producction

**Comment by catrielr** [comment]
Fix in;
[https://github.com/Dolibarr/dolibarr/commit/283bd723ec22f17e12314fde811b11ddbda87b78#diff-702512a44b095fd252a95352acf21598e7066c84da1bc96ce10cc64008a6ae54](url)

**Comment by JonBendtsen** [comment]
@catrielr  thank you for posting the correct'er filter syntax, it works for me :-)
