### ISSUE TITLE
In v20 25 lists fail and returns an error and only 18 lists still are working fine.

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#31084]
### Bug

Almost all the lists are failing in V20 after updating from v19 to v20 returning the following error
```
This website or feature is currently temporarily not available or failed after a technical error.
This may be due to a maintenance operation. Current status of operation (2024-09-22T08:46:10Z) are on next line...
Dolibarr has detected a technical error. You can read log file or set option $dolibarr_main_prod to '0' in your config file to get more information.
```

The lists that fail and return an error are the fllowing:
1. TOOLS/Emailings
2. TICKETS/Tickets
3. TICKETS/articles
4. AGENDA/events
5. HRM/Employees
6. HRM/Leaves
7. BANKS/Banks
8. BILLING/Customer invoices
9. BILLING/Supplier invoices
10. BILLING/Billable orders
11. COMMERCE/Commercial proposals
12. COMMERCE/sales orders
13. COMMERCE/vendor proposals
14. COMMERCE/purchase orders
15. COMMERCE/contracts-subscriptions
16. PROJECTS/Leads'projects
17. PROJECTS/Tasks
18. PROJECTS/Organized events
19. PRODUCTS/Products lists
20. PRODUCTS/Services
21. PRODUCTS/Warehouses
22. PRODUCTS/Shipments
23. THIRD PARTIES/Third parties
24. THIRD PARTIES/Contacts
25. users

The lists that do not have that error and are working fine are:
1. AGENDA/resources
2. HRM/Expense reports
3. HRM/List of Job positions
4. HRM/List of applications
5. BILLING/Taxes
6. BILLING/Salaries
7. BILLING/Miscellaneous payments
8. COMMERCE/Interventions
9. PROJECTS/Time tracking
10. PROJECTS/Conference or Booth
11. MRP/Bills o material
12. MRP/Manufacturing orders
13. MRP/Workstations
14. PRODUCTS/Stock transfers lists
15. PRODUCTS/Receptions
16. THIRD PARTY/List of Partnership
17. HOME/List of users
18. HOME/List of groups

### Dolibarr Version

20.0.0

### Environment PHP

8.1.29

### Environment Database

MySQL or MariaDB 10.6.19-MariaDB

**Comment by aspangaro** [comment]
No problems found on my side. I do not reproduce this problem on the lists mentioned.

Have you tried disabling the plug-ins one by one?

If you have the server's php logs, you'll have additional information on this problem. Please let us know

**Comment by edupulpillo** [comment]
the problem still is present
sorry i had no time for more info before

**Comment by edupulpillo** [comment]
Please do not close this issue.
The problem is present and i have tested in two instances.
Sorry i could not provide more info  yet, i will do in next 2 days

**Comment by edupulpillo** [comment]
We did a backup, restore the instance to v19 and repeat the update.
Then the problem is not present, and we can not reproduce it anymore.
In the previous instance of testing that was failing, after update it to 20.0.1 the problem is fix. 
Thank you for your kind support.
