### ISSUE TITLE
Custom theme JS file rendering issue

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#31131]
### Bug

As there is no instruction to the browser that the ALLOW_THEME_JS file is JavaScript file. Because there is no type attribute in the line `print '<script nonce="'.getNonce().'" src="'.DOL_URL_ROOT.'/theme/'.$conf->theme.'/'.$conf->theme.'.js'.($ext ? '?'.$ext : '').'"></script>'."\n";` This would be normal Dolibarr behavior if you you would render the file with `.php` extension. 

### Dolibarr Version

20.0

### Environment PHP

8.1.25

**Comment by alsoft10** [comment]
@eldy still this bug is present at Dolibarr 20.0.1

**Comment by eldy** [comment]
Pb seems into the js file you call.
Can youbcheck this file is sending a mime type ?

**Comment by alsoft10** [comment]
@eldy I checked it once again carefully. And it is solved. Thank you.
