### ISSUE TITLE
Bug: error when see equipement list page

### ISSUE THREAD

**Issue by ProveGhost** [Dolibarr/dolibarr#31145]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 14.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: apache2handler 7.4.3-4ubuntu2.23
- **Database**: MySQL or MariaDB 5.5.5-10.3.39-MariaDB-0ubuntu0.20.04.2
- **URL(s)**: /custom/gmao/core/ilot/ilot_card.php?id=8

## Expected and actual behavior
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20240926181628
Dolibarr: 14.0.5 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 7.4.3-4ubuntu2.23
Server: Apache/2.4.41 (Ubuntu)
OS: Linux srverpnsinfo 5.4.0-196-generic #216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

Url sollicitée: /custom/gmao/core/equipement/equipement_list.php?idmenu=247&mainmenu=gmao&leftmenu=
Referer: https://gmao.erpnsinfo.fr/custom/gmao/core/ilot/ilot_card.php?id=8
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, categorie, fckeditor, cron, dpersoplus, societe, propal, commande, expedition, fournisseur, facture, product, nsinfo, service, stock, projet, agenda, salaries, gmao
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT t.rowid,t.ref,t.label,t.description,t.poids,t.tension,t.puissance,t.aircomp,t.fk_ilot,t.fk_soc,t.date_service,t.date_sortie,t.noserie,t.paht,t.note_public,t.note_private,t.date_creation,t.tms,t.fk_user_creat,t.fk_user_modif,t.last_main_doc,t.status,t.import_key,t.model_pdf FROM llx_gmao_equipement as t WHERE 1 = 1 ORDER BY t.rowid ASC LIMIT 21
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 't.paht' in 'field list'

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Uploading Capture.PNG…]()

**Comment by ksar-ksar** [comment]
Hello,

This error is related to external module GMAO : `/custom/gmao/`
Need to ask the developer of that module.
It is not part of Dolibarr core.
