### ISSUE TITLE
Add SERVICE new line on a BOM tiny DB error when not enabled Workstations module [EASY FIX PROPOSED]

### ISSUE THREAD

**Issue by caos30** [Dolibarr/dolibarr#31152]
### Bug

**If you have not enabled STILL the Workstations module**, then there is database error when you access to BoM still in draft mode:

![imagen](https://github.com/user-attachments/assets/f818afcf-8518-46e4-99ce-954b0bc807e8)

This is because in the `/bom/tpl/objectline_create.tpl.php` appear this:
```
print $formproduct->selectWorkstations('', 'idworkstations', 1);
```
before to check if the module Workstations is enabled. So it could be fixed adding this:
```
if (isModEnabled('workstation')) {
	$coldisplay++;
	print '<td class="bordertop nobottom nowrap linecolworkstation">';
	print $formproduct->selectWorkstations('', 'idworkstations', 1);
	print '</td>';
}
```
as it appears on `/product/card.php` , but if you ask me would be a better solution (to avoid similar error on the future) to modify the function `selectWorkstations()` to **return empty string** when the module workstations is not enabled:
```
public function selectWorkstations($selected = '', $htmlname = 'idworkstations', ...)
{
	global $conf, $langs, $user, $hookmanager;

	if (!isModEnabled('workstation')) return ''; // <------ my proposed solution to avoid this error in the future
...
}
```
Note: this function is defined on `/product/class/html.formproduct.class.php`.

### Dolibarr Version

19, 20

### Steps to reproduce the behavior and expected behavior

1. create a BoM draft, without having enabled the module Workstations

Note: if you have enabled ONCE the module Workstations, then the table workstatiosn_workstations has been created and then you will not get the error. So, **this error only happens when you have not enabled never this module**.

**Comment by caos30** [comment]
Please, @eldy check it. I'm sure that you will find obvious to apply any of my both fixes... it's only a reasonable `IF` check. Thanks!

**Comment by sonikf** [comment]
Ηι @caos30 
Why don't you make a pull request?
