### ISSUE TITLE
 09/27/2024 - Meeting minutes

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#31158]
Révision de la première proposition et changement de position du dossier
https://github.com/Dolibarr/dolibarr/pull/30735

**Intégration des icônes**

![Image](https://github.com/user-attachments/assets/edff54b3-53a3-4579-a1fc-d68b270775c3)

**Intégration des badges**

![Image](https://github.com/user-attachments/assets/1bcba9aa-7392-41ce-b94b-3667bab25c99)

**Échanges sur la proposition**

https://github.com/Dolibarr/dolibarr/pull/30808
https://github.com/Dolibarr/dolibarr/pull/31023

Intégration de la partie HLS dans les boutons

**Préparation d'une présentation pour le DevCamp de Nancy**

Partie : Utilisateurs
Améliorations pour les utilisateurs

Partie : UI/UX designer
Intégration Figma

Partie : Developpeur
Présentation de la documentation

**Reflexions UX**

Possibilité d'afficher ou non des boutons en fonction du workflow
Dans une page, identifier les éléments importants. Il faudrait mettre en place plusieurs niveaux de lectures en fonction de l’importance des éléments. Exemple Bouton Primary / Secondary / etc... (Actuellement, tous les boutons sont violets, et donc visuellement au même niveau) https://github.com/Dolibarr/dolibarr/issues/30942

**Comment by eoxia-amandine** [comment]
**Reflexions UX**
- Possibilité d'afficher ou non des boutons en fonction du workflow
- Dans une page, identifier les éléments importants. Il faudrait mettre en place plusieurs niveaux de lectures en fonction de l’importance des éléments. Exemple Bouton Primary / Secondary / etc... (Actuellement, tous les boutons sont violets, et donc visuellement au même niveau) https://github.com/Dolibarr/dolibarr/issues/30942

**Comment by lmag** [comment]
Post ok sur le forum
https://www.dolibarr.fr/forum/t/giff-experience-utilisateur-et-interface-ui-ux/46658/17
