### ISSUE TITLE
Batch/Lot/Serial choice not proposed in transfer stock panel

### ISSUE THREAD

**Issue by jpfox** [Dolibarr/dolibarr#3116]
With Dolibarr 3.7.2 (with MAIN_FEATURES_LEVEL=2), it is not possible to choose which batch/lot/serial when transferring stock from a warehouse to another.

If you transfer a product, a random batch/lot/serial is decreased and stock in destination warehouse has no affected batch/lot/serial. It is a problem because this information is required in next treatments.

Thanks for this great feature.

**Comment by BebZ** [comment]
On my testserver (3.8 alpha) with mobilid ( @fappels ) i can choose transfer a specific batch to another warehouse, but only on clicking on what i have surrounded by red : 

![image](https://cloud.githubusercontent.com/assets/3694135/8427813/89f2b062-1f1a-11e5-89e1-4eb953d912d4.png)

**Comment by BebZ** [comment]
It's true that in mass stock transfers, or by clicking on the simple "transfer" button it doesn't propose the  choice of batches... 

![image](https://cloud.githubusercontent.com/assets/3694135/8427959/7a23c6f2-1f1b-11e5-887e-d1c26de152b8.png)

I don't know if it will be possible, it's not very practical when you want 
-to make a manual movement of stock, if some products are damaged/unsellable, etc...

Solution would be to create a specific warehouse called 
"TRASH/LOSS of stock" to transfer the products to put in "quarantine/to destroy/send back to supplier"
where 
it's not possible to choose the products for sending to customers 
and that won't count in the total theoretical/physical stocks

@eldy : good solution ?

**Comment by jpfox** [comment]
Thanks for these notes... so it will be possible in 3.8 branch

**Comment by jpfox** [comment]
I have upgraded to 3.8beta and stock transfer works fine.

Shipping seems to not fill stock movement correctly. It permit to choose which batch/lot to decrease (perfect) but stock movement does not list this information.

![Shipping with batch/lot](https://cloud.githubusercontent.com/assets/5191640/9277244/20071b18-42a9-11e5-97c6-e5fbb0f4f282.png)

![Stock movements listing](https://cloud.githubusercontent.com/assets/5191640/9277252/2f5960d0-42a9-11e5-97cb-b1bbdb5fdcd2.png)

How can I correct this ?

**Comment by BebZ** [comment]
I will try on mine and keep u informed

**Comment by BebZ** [comment]
I will try on mine and keep u informed. True it doesn't populate in 3.8.0 beta
