### ISSUE TITLE
Email with attachment is not sent on Ticket Add or Send message reply

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#31197]
### Bug

Dolibarr is not sending email to the customer email at the time of Adding a message on a ticket reply, if message has an attachment. Please check the attached screenshot.
![Ticket-email-send-attachment-issue](https://github.com/user-attachments/assets/e614573c-d19f-44a7-a87a-1d20af88c75f)

### Dolibarr Version

20.0

### Environment PHP

8.1.25

### Environment Database

MySQL

### Steps to reproduce the behavior and expected behavior

1. Go to any ticket details page
2. Now click on **Events/Agenda** tab.
3. Click on, **Add or send a message**.
4. Now check, "Send message by email" only.
5. Now write something and add an attachment.
6. Now send the message.

**Comment by alsoft10** [comment]
@hregis this bug is still unsolved in Dolibarr 20.0

**Comment by eldy** [comment]
I revert a change (the feature enhancement to get files linked to event) to restore a stable situation in v20 on ticket file attachement.

We will have to make a different implementation for v21 to get the feature to have files linked to each event.

**Comment by alsoft10** [comment]
This is solved now in 20.0.1
