### ISSUE TITLE
Product Customer price not updated in card when price updated

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#3120]
Noticed in 3.8 June 26,  3.6 OK

![cardnotupdated 1](https://cloud.githubusercontent.com/assets/4573808/8432027/b9a773b0-1f3d-11e5-95dc-72ac8fb5be0d.png)

Updated after page reload.

**Comment by rdoursenaud** [comment]
Looks like it's the sorting algorithm since you made 2 changes in the same minute.
The 8% line is just below!

**Comment by eldy** [comment]
Can't reproduce in 3.8
There is an order by date, rowid so this should not happen any more.
