### ISSUE TITLE
Invoice lines export bugged

### ISSUE THREAD

**Issue by matlopes** [Dolibarr/dolibarr#3124]
On step 3 when exporting Invoice lines, i get the following error message on the Product Id line:

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20150701155703
Dolibarr: 3.7.0
Niveau de fonctionnalités: 0
PHP: 5.4.41-0+deb7u1
Serveur: Apache
OS: Linux xvm-168-139.ghst.net 3.2.65-xenU-19-0e6777a-x86_64 #2 SMP Mon Dec 15 10:33:55 UTC 2014 x86_64
UserAgent: Mozilla/5.0 (Windows NT 5.1; rv:38.0) Gecko/20100101 Firefox/38.0

Url sollicitée: /exports/export.php?step=3&datatoexport=facture_1
Referer: https://HOSTURL/exports/export.php?step=2&datatoexport=facture_1&action=selectfield&field=all
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT rowid as rowid, label as label FROM llx_Product
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHTABLE
Information sur le dernier accès en base en erreur: Table 'extranet.llx_Product' doesn't exist

**When proceeding to the end, no line with a product is exported, only the membership lines**

**Comment by rdoursenaud** [comment]
Fixed in 467ee7b77128edf28c9536d6c9d5f1eaddc73a4f.
Will be available in the upcoming 3.7.2 release.

On a side note, you are already running an outdated version. 3.7.1 is available.
