### ISSUE TITLE
Extrafields of type "Select list" are not working V20.0.0

### ISSUE THREAD

**Issue by Gilles-L-Artaban** [Dolibarr/dolibarr#31253]
### Bug

> societe:nom:rowid::extra.remisettc_organisme_1=1

throws this error

> Error in request SELECT main.rowid as rowid, nom FROM llx_societe as main, llx_societe_extrafields as extra WHERE extra.fk_object = main.rowid AND extra.remisettc_organisme_1=1 AND Filter error - Bad syntax of the search string ORDER BY nom Erreur de syntaxe près de 'error - Bad syntax of the search string ORDER BY nom' à la ligne 1. Check setup of extra parameters.

>societe:nom:rowid::
extra.remisettc_organisme_1:=:1

and

>societe:nom:rowid::
(extra.remisettc_organisme_1:=:1)

List all the thirdparties

M'I doing something wrong or this is a bug ?

### Dolibarr Version

20.0.0

### Environment PHP

7.4.11

**Comment by sonikf** [comment]
Hi @Gilles-L-Artaban 
It is a bug but has already been fixed.
The correct syntax from here on out  is 

`societe:nom:rowid::(extra.remisettc_organisme_1:=:1)`

See https://wiki.dolibarr.org/index.php?title=Universal_Search_Filter_Syntax

You can replace your extrafields.class.php file with  this https://github.com/Dolibarr/dolibarr/blob/20.0/htdocs/core/class/extrafields.class.php or wait for v. 20.0.1

**Comment by Gilles-L-Artaban** [comment]
Thank you.
