### ISSUE TITLE
phpdoc and phpstan for never !

### ISSUE THREAD

**Issue by hregis** [Dolibarr/dolibarr#31261]
### Feature Request

Google translator ne pourra jamais traduire ma lassitude sur le fait de recevoir chaque jour des centaines de mails github me disant qu'une correction a été faite sur des soucis phpdoc ou phpstan ou autres soucis du non respect du code imposé !
serait-il possible de filtrer ceci ? perso ça devient irrespectueux face à l'environnement ! plus tu envois des emails inutiles et plus tu pollues la planètes ! ;-)

**Comment by hregis** [comment]
à la limite faites une PR groupée !!!

**Comment by hregis** [comment]
je vais encore passer pour le con de service... ;-)

**Comment by frederic34** [comment]
et sur ignore ?

![image](https://github.com/user-attachments/assets/697f960d-1a1f-4761-8fc8-4109a9b814ed)

**Comment by hregis** [comment]
Ça ne va pas tarder !
