### ISSUE TITLE
PRELEVEMENT_BIC row not created in llx_const

### ISSUE THREAD

**Issue by ram111** [Dolibarr/dolibarr#3127]
3.7.1
The PREVELEMENT_\* globals I think are only saved when saving changes in withdrawal mode setup.

I think these rows have to be updated when related changes are made. 

For example I go to a bank account, add a BIC, and this BIC is not added to the globals until I go to 
to modules standing orders and press save, which is a bug, info related to the bank has to be updated when changes to the bank are made.

**Comment by atm-maxime** [comment]
Hello,

That's normal for me. The PRELEVEMENT_\* const (there are 4 of them) are here to define a global conf for the module.
When you create a new bank account or when you enter a BIC or IBAN, it stays on the account data (table llx_account). Only the PRELEVEMENT_ID_BANKACCOUNT points to the bank account that is used for withdrawal.

**Comment by simnandez** [comment]
@atm-maxime you're right. This issue should close
