### ISSUE TITLE
Bug in prevelement file creation (SEPA)

### ISSUE THREAD

**Issue by ram111** [Dolibarr/dolibarr#3128]
3.7.1 
ISO20022 states that EndToEndId has a MaxLength of 35 characters. Said limitation has not been contemplated in the creation of the file and with many payments together will exceed that limit.

Just a substr would work?

```
function EnregDestinataireSEPA...
$XML_DEBITOR .='<EndToEndId>'.('AS-'.$row_facnumber.'-'.$Rowing).'</EndToEndId>'.$CrLf;
TO 
$XML_DEBITOR .='<EndToEndId>'.substr(('AS-'.$row_facnumber.'-'.$Rowing),0,35).'</EndToEndId>'.$CrLf;
```

**Comment by eldy** [comment]
Rowing is sprintf("%06d", $row_idfac); with 3.8 so limited to 6 chars.
row_facnumber is an id, so a short number too. So we should not go up to 35 chars.
But a substr may be a good security.

**Comment by ram111** [comment]
But if you group several invoices in one payment you will go over the limit.

Example in generated file of 3 invoices together: 

```
<EndToEndId>
AS-INF15108,INF15095,INF15191,-000167
</EndToEndId>
```

**Comment by marcosgdf** [comment]
Any update on this?

**Comment by alaunay** [comment]
I just hit that bug too, on a 3.9.1.

6 invoices made the field goes up to 46 chars:

<EndToEndId>AS-FC0005FC0007FC0003FC0007FC0003FC0008-000487</EndToEndId>

(fake FC numbers obviously)
