### ISSUE TITLE
Bug: Attempt to read property "rowid" on null - Fournisseurs

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#31288]
### Bug

Version: 20.0.0

Hello,

When I go to configure the Fournisseurs module I see this Warning. I just did a fresh install
![image](https://github.com/user-attachments/assets/1b0af362-b153-4740-a2b7-8007cec9e23d)

My PHP version is 8.1.29

### Dolibarr Version

20.0.0

### Environment PHP

8.1.29

### Steps to reproduce the behavior and expected behavior

Fresh install and configure Fournisseurs module

**Comment by lemathou** [comment]
This appears only if your database has no products. I will fix it.

**Comment by lemathou** [comment]
I dit a PR to fix it : https://github.com/Dolibarr/dolibarr/pull/31859
