### ISSUE TITLE
Feature request: Remove "Confirm clone" dialog when cloning a supplier invoice

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3129]
Because we are able to delete the cloned invoice just after confirming the clone action, I find it better to just clone the invoice right after clicking "Clone". If the user regrets doing that, he can delete it.

**Comment by eldy** [comment]
The goal of popup was also to introduce question on what we want to clone or change data during clone, like the thirdparty.
but for the moment only products and proposal are using this but in future supplier invoice may also need it.

**Comment by eldy** [comment]
The popup is now also used to ask the date and new ref of cloned invoice.
