### ISSUE TITLE
[EPC-QR, Sponge]: No translation of "INVOICE_ADD_EPC_QR_CODEPay", Runtime error/misplaced text when INVOICE_ADD_EPC_QR_CODE==bottom

### ISSUE THREAD

**Issue by shasta123** [Dolibarr/dolibarr#31305]
### Bug

Hi,

While playing with the account name issue in EPC QR, I also noticed that there is no translation of "INVOICE_ADD_EPC_QR_CODEPay" due to a missing domain in loadlangs.

When placing the QR code at the bottom with "INVOICE_ADD_EPC_QR_CODE"==bottom I got a runtime error because $langs was not available there (outputlangs is) and the descriptory text was placed within the QR code.

The attached patch fixes all issues for me. Maybe it's of some use.

Cheers,
Michael

### Dolibarr Version

20.0

### Environment PHP

8.2.20-1~deb12u1

### Environment Database

PostgreSQL 15.8-0+deb12u1

### Attached files

Patch fixing translation, QR Text placement (bottom) and runtime error (bottom)
[epc-translation.patch.txt](https://github.com/user-attachments/files/17281419/epc-translation.patch.txt)

**Comment by iLLixM** [comment]
@shasta123
it seems like you are actively using the EPC QR codes as well. can you take a look at my description in the issue #31538 and share your opinion on it?
