### ISSUE TITLE
Docker image for Dolibarr 20.0.1

### ISSUE THREAD

**Issue by n-rodriguez** [Dolibarr/dolibarr#31338]
### Bug

The Docker image for Dolibarr 20.0.1 is not available.

Thank you!

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr-docker/commit/7e6666f7e097f81430a9e0f01ef15414f9c6046d

**Comment by n-rodriguez** [comment]
@frederic34 Actually I prefer waiting for a solution to https://github.com/Dolibarr/dolibarr/issues/30995 before ugprading

Thank you!
