### ISSUE TITLE
Web portal login fails when using PostgreSQL DB

### ISSUE THREAD

**Issue by jturello-ulink** [Dolibarr/dolibarr#31350]
Hi,

There is a bug in the following file, line 687:
https://github.com/Dolibarr/dolibarr/blob/42089e3542d8e32b2538a9379122d42ebf2bacd0/htdocs/webportal/class/context.class.php#L687

The "SELECT .... WHERE **BINARY** sa.login ...." in the "getThirdPartyAccountFromLogin" function is not recognized by PostgreSQL, which result in a login error. When removing "BINARY" (which seems specific to MySQL), it works.

Best regards

**Comment by lvessiller-opendsi** [comment]
see PR https://github.com/Dolibarr/dolibarr/pull/31864

**Comment by lvessiller-opendsi** [comment]
The login is not case sensitive
