### ISSUE TITLE
Bug: Unauthorized access to Paypal module brings an UI with too much information

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3138]
Version: 3.7.1 (should test in 3.6 and 3.5)

FYI I'm not even logged in

![captura de pantalla 2015-07-02 a las 21 08 14](https://cloud.githubusercontent.com/assets/168744/8485534/7ef140e4-20fe-11e5-876a-08df0840b57b.png)

**Comment by rdoursenaud** [comment]
Just for the record: #2992 duplicate
