### ISSUE TITLE
VAT on supplier invoices (tva_assuj flag)

### ISSUE THREAD

**Issue by dieperie** [Dolibarr/dolibarr#31402]
### Bug

Creating a supplier invoicing where supplier is **not** subject to VAT, the VAT rate should be 0. This is not the case.

### Dolibarr Version

V19 and V20

**Comment by IC-faycal** [comment]
The issue was resolved in version 21. Now, for suppliers not subject to VAT, the VAT rate is set to 0 by default when adding a product line.
