### ISSUE TITLE
Bug: Condition and Mode de reglement not propagated to the facture template

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#31451]
### Bug

Version: 20.0.1

Hello,

I have a facture fournisseur, on which
Mode de reglement = Ordre de prélèvement
Condition de reglement = A réception

![image](https://github.com/user-attachments/assets/9eab07d6-5f4e-4331-be22-fbe8a5dbbaaf)

And I convert it in a facture template

On the next screen I add a name
![image](https://github.com/user-attachments/assets/d00953b5-4f03-4f82-bcf2-d6d3444bdb0e)
And I still see Mode de reglement = Ordre de prélèvement / Condition de reglement = A réception
I validate it by Create

But the problem, is that once my template is created Mode de reglement and Condition de reglement modes are lost
![image](https://github.com/user-attachments/assets/5a94d6f5-e706-432a-a432-7430b1571cf6)

So these informations are not propagated,but they should have.

### Dolibarr Version

20.0.1

**Comment by alex10843** [comment]
Fixed in 20.0.2
