### ISSUE TITLE
Bug: impossible to select  <a href="#selectedfields">      

### ISSUE THREAD

**Issue by Pyhot** [Dolibarr/dolibarr#31513]
Hello, 

First I want to congratulate teams' developpement of Dolibarr ! I LOVE this ERP/CRM :)

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug

 I always have troubles in appearance of page /product/reassort.php?type=0&leftmenu= : there is NO POSSIBILITY TO SELECT COLUMNS (no  <a href="#selectedfields">    button ?) 
This page seems too wide, for every screens, or navigators, even after upgrade. 

Looks like <a href="#selectedfields">
              <span class="fas fa-list" style=""></span>
            </a>
is missing.

Somebody has any clue to fix this page ? 

## Environment
- **Version**: 20.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 8.1.29
- **Database**: MySQL or MariaDB 8.0.35
- **URL(s)**: /htdocs/product/reassort.php

## Expected and actual behaviour
Columns selection  works perfectly with other pages such as Products (see images attached). 

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging information…)

<img width="1818" alt="Capture d’écran 2024-10-22 à 09 47 04" src="https://github.com/user-attachments/assets/a13d358f-cd7c-4793-a41c-7a0120dd3cfe">
<img width="1815" alt="Capture d’écran 2024-10-22 à 09 32 27" src="https://github.com/user-attachments/assets/4420df98-c0d8-4e04-803d-1408cd27e888">

**Comment by frederic34** [comment]
is the right link `htdocs/product/reassort.php` ? not `htdocs/product/stock/reassort.php`

**Comment by Pyhot** [comment]
Hello Frederic, 

the problematic link is indeed with link (copy-pasted)  htdocs/product/reassort.php.

but also almost the same problem (no button to SELECT COLUMNS)  with htdocs/product/reassortlot.php

(URL "htdocs/product/stock/reassort.php" was not found on this server)

**Comment by Pyhot** [comment]
Hello, any help ? Do you have the same problem ?

**Comment by Pyhot** [comment]
I just found the solution, while checking on demo : there is no columns selection tool in /product/reassort.php nor in /product/reassortlot.php

Now, it could be a good tool to install in futur upgrades ;)
