### ISSUE TITLE
Bug with FTP Upload

### ISSUE THREAD

**Issue by GildDart** [Dolibarr/dolibarr#31519]
### Bug

I have the following message when I try to upload the 20.0.1 version with FTP on o2switch 

Le chargement du fichier dolibarr-20.0.1.zip, car celui-ci contient un virus : {HEX}Malware.Expert.php.base64.decode.passthru.UNOFFICIAL FOUND

### Dolibarr Version

20.0.1

**Comment by frederic34** [comment]
https://www.dolibarr.fr/forum/t/virus-detecte-dolibarr-v20-1-zip-chargement-vers-cpanel-via-filemanager/47734

**Comment by ksar-ksar** [comment]
According to this message : https://www.dolibarr.fr/forum/t/dolibarr-v20-est-sorti-mise-a-jour-la-v20-0-1-est-sortie/47434/30
The ZIP encryption seems to create the issue.

**Comment by iouston** [comment]
This line triggers the alert :

$forbiddenphpfunctions = array_merge($forbiddenphpfunctions, array("base64_decode", "rawurldecode", "urldecode", "str_rot13", "hex2bin")); // decode string functions used to obfuscated function name dans dol_eval()

we test with eldy to remplace this line by $forbiddenphpfunctions = array_merge($forbiddenphpfunctions, array("base64"."_"."decode", "rawurl"."decode", "url"."decode", "str."_rot13", "hex"."2bin")); // no comment

At this time the alert is nos triggered

O2switch support opened a ticket at cpanel to fix this false positive

**Comment by iouston** [comment]
Eldy replaced the line by $forbiddenphpfunctions = array_merge($forbiddenphpfunctions, array("base64"."_"."decode", "rawurl"."decode", "url"."decode", "str."_rot13", "hex"."2bin")); // no comment
in the developp.
So this problem will be solved in next version
