### ISSUE TITLE
Email templates dictionnary page should filter by entity

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3155]
Because several companies may use different email templates, it would be useful to only show the ones created in that entity.

**Comment by FHenry** [comment]
A tricks to solve this issues will be to add for exemple 
$models='propal_send'.(($conf->entity!=1)?$conf->entity:'');
I also prefers adding a column entity and create a nice template editor

**Comment by clCglAvt** [comment]
@eldy 
to be closed
