### ISSUE TITLE
link to open pdf file in "bordereau de remise de chèque"

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#3156]
The PDF document is correctly generated, but the link does not point to the document, in "Bank", "Deposit slip"
[link to dolibarr.fr forum](http://www.dolibarr.fr/forum/5-bugs-sur-la-version-cvs-ou-demo/53401-fichier-joint-pdf-des-bordereaux-de-remise-de-cheq)
Dolibarr 3.8.0-alpha on debian

**Comment by marcosgdf** [comment]
Can you give a little bit more information about the problem? I'm afraid I don't speak french.
