### ISSUE TITLE
can't change date in invoices

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#3158]
when editing a **draft** invoice or even modification of an **existing** invoice, changing the date of the invoice can not be validated, it says _"The 'Date' field is compulsory."_ (in french : _"Le champ 'Date' est obligatoire"_)
No problem with proposals
[link to Dolibarr Forum](http://www.dolibarr.fr/forum/5-bugs-sur-la-version-cvs-ou-demo/53400-impossible-de-changer-la-date-d-une-facture)
Dolibarr 3.8.0-alpha (git of today)
PHP 5.6.9 on debian

**Comment by all3kcis** [comment]
Indeed, the input field are outside of the form.
See file : compta/facture.php Line 3000

**Comment by ozit** [comment]
I select the date in the "java?" box

**Comment by ozit** [comment]
cool

**Comment by ozit** [comment]
it works, waiting for applying under dev brach
