### ISSUE TITLE
Booking loan payment not possible in bank

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#31599]
### Bug

Payments made can not booked into bankjournal due error. 
There is no balance in booking. No part of payment, interest of assurance. All the same amount.

### Dolibarr Version

20.0.1

### Environment PHP

8.2.24

### Environment Database

MySQL or MariaDB 8.0.39-0ubuntu0.22.04.1

### Steps to reproduce the behavior and expected behavior

Make payment into loan section and try to get it booked into bankjournal

### Attached files

![afbeelding](https://github.com/user-attachments/assets/de48ee48-03fc-4177-a849-f8dd2ac2905f)

**Comment by aspangaro** [comment]
Already correct in fix #31546
