### ISSUE TITLE
Change the user card to use the html select with select2 component to set groups of a user

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#3161]

**Comment by FHenry** [comment]
Do you mean like the "Test 5: a multiselect" in public/test/test_forms.php ?

**Comment by rdoursenaud** [comment]
@FHenry Yes, that's the select2 component.
You may want to also take a look at https://github.com/Dolibarr/dolibarr/issues/2571.

**Comment by eldy** [comment]
I close this request. If we do so, we wont' be able to manage multicompany needs.
