### ISSUE TITLE
Not escaped/not casted SQL argument not detected by flow verification

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#31616]
@eldy 

I think that the checks should detect this case where '$this->next_update' is not escaped and not casted to int:

https://github.com/Dolibarr/dolibarr/blob/b3b8f52cc9e7497120d3676717260cede0931dc2/htdocs/product/dynamic_price/class/price_global_variable_updater.class.php#L579

**Comment by eldy** [comment]
> @eldy 
> 
> I think that the checks should detect this case where '$this->next_update' is not escaped and not casted to int:
> 
> https://github.com/Dolibarr/dolibarr/blob/b3b8f52cc9e7497120d3676717260cede0931dc2/htdocs/product/dynamic_price/class/price_global_variable_updater.class.php#L579

Done, i added a phpunit test for such cases.
