### ISSUE TITLE
Feature Request: Facture fournisseur list should be sorted by invoice's date of issue

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#31612]
### Feature Request

Version: 20.0.1

Hello,

I don't know what kind of sort is used but the list of invoices should be sorted by their date of issue (date de facturation).
![image](https://github.com/user-attachments/assets/66309e5e-9a3e-45d7-bf89-4bcbf12b5787)

There are multiple criterias that could be used to sort these invoices but the most logical should be the invoice date of issue.
So when we clic on list in the facture fournisseurs, the invoices should be sorted by their date of issue.
![image](https://github.com/user-attachments/assets/f4452704-46d7-4023-8e0b-eb7ebc82f6be)

**Comment by sonikf** [comment]
Ηι @mikygee 
Ι can't see the issue here, both screenshots are sorted by Invoice date

**Comment by mikygee** [comment]
Hello,
I don't know how to show you if you don't see the screenshots but they are not sorted by invoice date.
It's provider invoices not invoices for clients.

**Comment by sonikf** [comment]
Can you explain more? In both screenshots fournisseur invoice dates are correctly sorted from latest(top 3/7/2024) to oldest(bottom 31/3/2023)

**Comment by mikygee** [comment]
Kalispera,
Indeed, you are right, it's already working properly.
It seems I was confused when I opened the tiket.
Thank you for your messages.
