### ISSUE TITLE
DB_Error_1265 when adding a leave type

### ISSUE THREAD

**Issue by tjerkkamstra** [Dolibarr/dolibarr#31624]
### Bug

When trying to add a leave type in the dictonary menu via the GUI, it comes back with a technical error:

`Dolibarr heeft een technische fout gedetecteerd.
Deze informatie kan nuttig zijn voor diagnostische doeleinden (u kunt optie $dolibarr_main_prod instellen op '1' om gevoelige informatie te verbergen):
Datum: 20241029130456
Dolibarr: 20.0.1 - https://www.dolibarr.org
Niveau van de functionaliteiten: 0
Login: tucker
PHP: 8.1.12-1ubuntu4.3
Server: Apache/2.4.55 (Ubuntu)
OS: Linux dolibar 6.8.12-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2 (2024-09-05T10:03Z) x86_64
Gebruikersagent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

Gezochte URL: /dolibarr/admin/dict.php?id=28
Referer: https://icehrm.tucker.nl/dolibarr/admin/dict.php?action=create&id=28&backtopage=%2Fdolibarr%2Fadmin%2Fdict.php
Standaard menuverwerker: eldy_menu.php

Modules / Applicaties: user, cron, holiday, expensereport, import, fckeditor, salaries, agenda, knowledgemanagement, eventorganization, projet, categorie, banque, tax, ticket, export, ecm, hrm, blockedlog, facture, societe, stock, product, resource
Database Type Manager: mysqli
Database fout bij laatste verzoek: INSERT INTO llx_c_holiday_types (code,label,affect,delay,newbymonth,fk_country,block_if_negative,sortorder,entity,active) VALUES('bwetvak','Bovenwettelijke vakantie','1','0','2','17','1',5,'0,1',1)
Retourcode voor de meest recente fout bij het toegangsverzoek voor de database: DB_ERROR_1265
Informatie voor de meest recente database-toegangsverzoekfout: Data truncated for column 'entity' at row 1`

### Dolibarr Version

20.0.1

### Environment PHP

8.1.12-1ubuntu4.3

### Environment Database

 10.11.2-MariaDB-1 - Ubuntu 23.04

### Steps to reproduce the behavior and expected behavior

1) Go to dolibarr/admin/dict.php?id=28
2) Click on the + icon
3) Fill in the form
4) See the error

What did work though, is to go to phpmyadmin and just change it there. Which suggests to me that the problem rests with dolibarr.

![Afbeelding van WhatsApp op 2024-10-29 om 13 26 12_89e62768](https://github.com/user-attachments/assets/fbe391e9-43dd-418b-afb8-f056e3817e7a)

**Comment by hregis** [comment]
@tjerkkamstra thanks, this PR fix this bug : https://github.com/Dolibarr/dolibarr/pull/31625

**Comment by tjerkkamstra** [comment]
Thanks. Would this also correct the UPDATE, because when you alter the lines in the GUI, nothing seems to happen too but no error shows up.

**Comment by hregis** [comment]
@tjerkkamstra yes the update is ok

**Comment by fappels** [comment]
Confirmed completed in V20.0.2
