### ISSUE TITLE
CKEditor removes class attribute from simple SPAN tag on submit

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#31650]
### Bug

At the time of creating Knowledge Base article, we need some little bit repetitive formatting of texts. For that tho most simple and effective way to do that, to use a CSS class.  When we write  a span tag with class name like, `<span class="test">Some text</span>`, at the time of submit the article, **CKEditor** remove that class attribute. 

This problem should be solved. Because user needs rich content editing and CSS class are a great tool for that.

### Dolibarr Version

20.0.1

### Environment PHP

8.1.25

### Environment Database

MySQL

**Comment by alsoft10** [comment]
@eldy Dolibarr should have this important feature.

**Comment by zahwyrix** [comment]
Unless I'm mistaken, this behavior is native. You need to use the style attribute of your span tag, and it will work.

**Comment by alsoft10** [comment]
Yes with the style tag we can use CSS. But for repetitive CSS commands it is not productive. Because to do a small change to you have to change in a lot of places. On the other hand, Dolibarr must more flexible for users. So it should be more dynamic that user can change look and feel without going to hands on coding.

**Comment by alsoft10** [comment]
@eldy is there any update regarding this feature?

**Comment by alsoft10** [comment]
In general Dolibarr restricts any HTML contents to be inserted into the system. So this feature is already implemented using global configuration key `FCKEDITOR_ALLOW_ANY_CONTENT`. So as it is an already developed feature, so it's solved.
