### ISSUE TITLE
ability to use char in accountancy accounting account not only numeric

### ISSUE THREAD

**Issue by elarifr** [Dolibarr/dolibarr#3166]
we need ability to save account number with alpha not only number. 
some accounting software can store an account like 704MO not only numbers
it is mandatory for my customer who want to use same customer account and account number
Table: llx_accountingaccount account_number is already a varchar(32) 

Maybe we can add an optional ACCOUTING_ACCOUNT_ALLOW_CHAR

**Comment by rdoursenaud** [comment]
Sounds like a bug to me.
Affected version(s)?
ping @aspangaro

**Comment by aspangaro** [comment]
Yes it's a bug, an accounting account will be alphanumeric. I propose a PR to fix this.

**Comment by elarifr** [comment]
not really a bug, most accounting software use only number. only few one can use alpha. 
should really be an optional feature to avoid mistake for most users.

**Comment by aspangaro** [comment]
In this case, it is a bug because this possibility existed before in particular for EBP
