### ISSUE TITLE
accountingaccount missing an account class notion not accountingsystem dependant

### ISSUE THREAD

**Issue by elarifr** [Dolibarr/dolibarr#3167]
for example in french system TIERS are in class 4, FINANCIAL class 5, buy class 6, sell are in class 7...
but no way to know what is the equivallent class in othe account system

this is needed to be able to limit select_account only to the corresponding class when we create customer / product...

As dolibarr is not an accounting system we don't need to display all accountingaccount when you creae a product.
so when making a new product we can display only BuyClass for buy account, SellClass for sell account according to account system

Alex Spangaro should help to define most necessary class range / type
ClassCustomer
ClassSupplier
ClassBuy
ClassSell
ClassFinancial
ClassVAT
ClassTemp
ClassBank

we can't use pcg_type that provide the same meaning but it is language dependant

this should be achieved by adding a field accountingaccountclass and set parent class in all system

**Comment by eldy** [comment]
I think the field pcg_type and pcg_sub_type into table llx_accounting_account may be used for that ?
