### ISSUE TITLE
Possible misuse of field customcode in products table 

### ISSUE THREAD

**Issue by sonikf** [Dolibarr/dolibarr#31679]
### Bug

In product card the following field is displayed

![taric](https://github.com/user-attachments/assets/27932740-3954-4451-8d6c-2c7ea94527ec)

According to 
https://en.wikipedia.org/wiki/Harmonized_System
https://en.wikipedia.org/wiki/TARIC_code
The maximum is 10 digits and should be varchar(10)

Instead  it corresponds to field customcode in db table product with wrong size and a misleading comment for developers

https://github.com/Dolibarr/dolibarr/blob/1619c103cd538bb687a42c3cfe68500b5788605d/htdocs/install/mysql/tables/llx_product.sql#L41

@eldy 
Please advise 

Related to #31652

**Comment by eldy** [comment]
Even if official value must contains 10 char max, we can standardize code to use 32 char everywhere to be consistent.
Adding your link into the comment of the sql will help to retreive goal of field.
If we can store 32, we can store 10.
