### ISSUE TITLE
Resources are created empty

### ISSUE THREAD

**Issue by EnjoyFelix** [Dolibarr/dolibarr#31712]
### Bug

When creating a **resource**, the fields are not taken into account and the resource is created with empty fields.
However, this isn't the case when modifying a resource. 

### Dolibarr Version

20.X

### Environment PHP

7.4

### Environment Database

Mariadb:latest (11.5.2)

### Steps to reproduce the behavior and expected behavior

1. Enable the _resource_ module
2. Create a new resource
![image](https://github.com/user-attachments/assets/aae2e610-9e44-4241-bf05-81f5df98369d)

3. The newly created resource doesn't have the informations filled out.
![image](https://github.com/user-attachments/assets/17c3adf0-58ae-4cff-acee-fcce0b98c7a5)
![image](https://github.com/user-attachments/assets/30c4c21d-b344-48b3-b60a-f0e124137222)

**Comment by ghost** [comment]
Hello, I couldn't manage to reproduce this bug on a standard Dolibarr v20 or develop. Do you have any warnings or fatal errors in your logs when trying to create a ressource ?

**Comment by alex10843** [comment]
FIX in PR https://github.com/Dolibarr/dolibarr/pull/31844
