### ISSUE TITLE
pdf invoice crabe model bug

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#3173]
the header is not well positionned, there are too much informations in header when invoice is linked to a shipping or several shippings.....
recovers customer's address

![bug_facture](https://cloud.githubusercontent.com/assets/919513/8574135/63862bd0-2595-11e5-871b-7f3e531c9242.png)

Adressé à:

**Comment by rdoursenaud** [comment]
Ah, the infamous overlapping PDF bugs :)

Affected version(s)?
