### ISSUE TITLE
 Fiscal stamp Bug after Updating to version 20.0.1

### ISSUE THREAD

**Issue by abdouap** [Dolibarr/dolibarr#31752]
### Bug

Hello,

After updating to version 20.0.1 of Dolibarr, I encountered an issue with the fiscal stamp. Before the update, the calculation of the fiscal stamp worked correctly, but now it remains stuck at 0.00. Although the amount of the fiscal stamp is added to the total invoice amount, it no longer appears in the generated invoice.
Amount excl. tax 	20.00 MAD
VAT Amount 	       4.00 MAD
**Fiscal Stamp 	       0,00**
Total Amount          24.**06** MAD

### Dolibarr Version

20.0.1

### Environment PHP

8.2

### Attached files

![Screenshot 2024-11-09 at 20-03-48 IN2410-0132 - Fiche](https://github.com/user-attachments/assets/fcfa4851-8ad8-4b1a-b3c0-c7d203a02f61)
![Screenshot 2024-11-09 at 20-03-14 IN2410-0132 - Fiche](https://github.com/user-attachments/assets/7fad847a-2be0-4ee7-bbd9-4b768f64568f)
![Screenshot 2024-11-09 at 20-05-32 IN2410-0132 - Fiche](https://github.com/user-attachments/assets/3776a1e9-2c67-401e-aa6c-d72498ce9749)

**Comment by marc-dll** [comment]
Hi,

I will try to reproduce.

Greetings
