### ISSUE TITLE
Supplier order only validated with using 'Validate and Approve' button

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#3178]
On Dolibar 3.8, clicking 'Validate and Approve' button only validates supplier order. (also popup asks only validation confirmation)

**Comment by all3kcis** [comment]
Works for me.
Valid and approve with date and fk_user ok.

**Comment by rdoursenaud** [comment]
Same here.

**Comment by fappels** [comment]
Seems I only have see the issue when the order has one of my predefined test products.
Closing issue and see what wrong with the testproduct, will reopen if indeed bug.
