### ISSUE TITLE
Impossible to complete installation on develop

### ISSUE THREAD

**Issue by Delthair** [Dolibarr/dolibarr#31816]
### Bug

The step 5 of the installation is blocked : 

Fatal error: Uncaught TypeError: Cronjob::create(): Argument #1 ($user) must be of type User, int given, called in /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/core/modules/DolibarrModules.class.php on line 1701 and defined in /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/cron/class/cronjob.class.php:235 Stack trace: #0 /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/core/modules/DolibarrModules.class.php(1701): Cronjob->create(1) #1 /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/core/modules/DolibarrModules.class.php(570): DolibarrModules->insert_cronjobs() #2 /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/core/modules/modAgenda.class.php(615): DolibarrModules->_init(Array, '') #3 /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/core/lib/admin.lib.php(1228): modAgenda->init() #4 /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/install/step5.php(360): activateModule('modAgenda', 1) #5 {main} thrown in /Users/pragma-tech/Documents/000000 DEV/DEVELOP/dolibarr/htdocs/cron/class/cronjob.class.php on line 235

Impossible to finalise installation

### Dolibarr Version

develop

### Environment PHP

8.2

### Environment Database

Mysql version 5.7.39

### Steps to reproduce the behavior and expected behavior

Install a develop dolibarr

**Comment by tiaris** [comment]
you must also add 
		include_once DOL_DOCUMENT_ROOT . '/user/class/user.class.php';

**Comment by FHenry** [comment]
fix by https://github.com/Dolibarr/dolibarr/pull/31820
