### ISSUE TITLE
dol_fiche_head() is often used without dol_fiche_end()

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3182]
`dol_fiche_head()` when used without the tab parameter set opens a `<div>` that needs to be closed by the corresponding `dol_fiche_end()` function.
Failing to do so results in an unbalanced HTML tag tree.

Review all `dol_fiche_head()` usages and check for `dol_fiche_end()` presence.
Add it if needed ;)

**Comment by elarifr** [comment]
only 31 files with dol_fiche_head()
only found 4 where dol_fiche_head() was not followed by dol_fiche_end()
checked only php files with ultrafinder

**Comment by rdoursenaud** [comment]
Nothing beats regular expressions for this kind of work.
My tool of choice is [ACK](http://beyondgrep.com/):

``` sh
ack --php dol_fiche_head|wc -l
428
ack --php dol_fiche_end|wc-l
289
```

But let's not forget that it's perfectly legit to not call `dol_fiche_end()` when `dol_fiche_head()` is called with the `tab` parameter set.

**Comment by marcosgdf** [comment]
LOL

```
/**
 *  Return tab footer of a card
 *
 *  @param  int     $notab      0=Add tab footer, 1=no tab footer
 *  @return string
 */
function dol_get_fiche_end($notab=0)
{
    if (! $notab) return "\n</div>\n";
    else return '';
}
```

**Comment by rdoursenaud** [comment]
@marcosgdf Yes, the code is hideous, but it's the intended behavior. What can I do…

**Comment by eldy** [comment]
Difference should have been a lot of reduced with 3.9, shouldn't it ?

**Comment by rdoursenaud** [comment]
Yep, 3.9:

```
ag --php --count --ignore-dir=htdocs/custom dol_fiche_head |wc -l
350
ag --php --count --ignore-dir=htdocs/custom dol_fiche_end|wc -l 
257
```

develop:

```
ag --php --count --ignore-dir=htdocs/custom dol_fiche_head|wc -l
363
ag --php --count --ignore-dir=htdocs/custom dol_fiche_end|wc -l 
267
```

**Comment by eldy** [comment]
Should be correctly balanced now in v10
Counting head and start may not be enough to compare because some function call are inside if else so exists several times.
