### ISSUE TITLE
rounded corners not  on total of pdf

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#31838]
### Bug

setup up Frames with rounded corners on 3
PDF of proposals show

![image](https://github.com/user-attachments/assets/cf312259-ff59-4fb4-8787-e3beb6208963)

### Dolibarr Version

dlbdev devcamp Nancy

### Environment PHP

8.2

### Environment Database

20.0.0 beta

### Steps to reproduce the behavior and expected behavior

set param Frames with rounded corners on 3

![image](https://github.com/user-attachments/assets/77f35230-882a-4e60-8680-c42ebf3c4d4c)

**Comment by MaximilienR-easya** [comment]
I made a PR #31882 to Fix this issue
