### ISSUE TITLE
sendMail Hook in CMailFile class sendfile() can't trigger error

### ISSUE THREAD

**Issue by dev2info** [Dolibarr/dolibarr#31833]
### Bug

sendfile() method in CMailFile class returns true or false so returning -1 via sendMail Hook do not trigger any error

### Dolibarr Version

18.0.5

### Environment PHP

7.3.27

### Environment Database

sql

**Comment by marc-dll** [comment]
Hello,

Thank you for you contribution.

This issue has already been fixed in Dolibarr version 20.0.

Greetings.

**Comment by bafbes** [comment]
Why do you need to return -1 ?

**Comment by kkhelifa-opendsi** [comment]
It's fixed in develop
PR in progress https://github.com/Dolibarr/dolibarr/pull/31460
