### ISSUE TITLE
condition of sale

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#31847]
### Bug

Where to store the "conditions of sale" ?
![image](https://github.com/user-attachments/assets/703c84d1-86c2-4689-832c-66bff73549ab)

### Dolibarr Version

20.0.0.beta

### Environment PHP

8.2

**Comment by RomainDeschamps** [comment]
The question applies on orders
![image](https://github.com/user-attachments/assets/f33e0446-c9da-44b3-bb13-3e3639b5ba65)

**Comment by lvessiller-opendsi** [comment]
see PR #31879 : add a help in a tooltip
The file can be uploaded at the end of this form
