### ISSUE TITLE
Assets: error 500 when creating asset with no depreciation

### ISSUE THREAD

**Issue by marc-dll** [Dolibarr/dolibarr#31856]
### Bug

Division by zero when creating an asset with no depreciation
![Uploading Capture d’écran de 2024-11-15 15-20-14.png…]()

### Dolibarr Version

20.0

### Environment PHP

8.2.x

### Environment Database

MariaDB

**Comment by FHenry** [comment]
fix by https://github.com/Dolibarr/dolibarr/pull/31858
