### ISSUE TITLE
Allow using lines extra fields data in ODT templates

### ISSUE THREAD

**Issue by jpfox** [Dolibarr/dolibarr#3185]
As mentionned on [forum](http://www.dolibarr.org/forum/12-howto-help/24019-line-tag-for-extra-field-odt), it is impossible to use custom extra field defined in modules configuration on ODT generated documents.

Something like {line_options_xxxx} (like object_options_xxx) should be great.

In which source file does it happen, I could try to add this feature and share code.

**Comment by FHenry** [comment]
for exemple on invoice it should be done by htdocs/core/modules/facture/doc/doc_generic_invoice_odt.modules.php around line 376. Or more probably in core/class/commondocgenerator.class.php on method get_substitutionarray_lines that do not implement extrafield like others

**Comment by jpfox** [comment]
We have developed a module to allow some new tags in odt : 
- billing and shipping contact address in orders and invoices (according to attached contacts)
- line extrafields

You can get it here : https://github.com/Befox/adrodt

**Comment by pat15** [comment]
Is it working with 3.8.2 ? When i try example file i still have in line:
adrodt_debug_lines = {adrodt_debug_lines}

I try change to my own product extra line field -> {adrodt_jm} but not working... Checking on commande module.

**Comment by jpfox** [comment]
Have you enabled adrodt module ?

if your line field is named jm, use {line_options_jm} in your odt model

**Comment by rdoursenaud** [comment]
@jpfox Why don't you contribute your changes to the native module? These seem useful for everyone.

**Comment by pat15** [comment]
@jpfox - Yes i have it enabled, and still not working. 
[!-- BEGIN row.lines --]{line_options_jm} ..... <- this is in odt template, when i generated and download this file i have: **{line_options_jm}**
