### ISSUE TITLE
User Class not found on new installation dolibarr developp

### ISSUE THREAD

**Issue by iouston** [Dolibarr/dolibarr#31918]
### Bug

At the step 5 on a new installation dolibarr developp, we have an error user class is not found
![Capture d’écran 2024-11-15 à 17 29 29-fullpage](https://github.com/user-attachments/assets/40a30bee-1d84-4d59-89c8-92a784705c28)
![Capture d’écran 2024-11-15 à 17 29 23-fullpage](https://github.com/user-attachments/assets/e8ecda37-86cb-4c0e-a30b-e0913837bae5)

### Dolibarr Version

developp

### Environment PHP

7.4

**Comment by Delthair** [comment]
Already corrected on ISSUE #31820  FIX PR #31820

**Comment by iouston** [comment]
Sorry this bug is still present ! I reopen this issue

**Comment by FHenry** [comment]
Fix by https://github.com/Dolibarr/dolibarr/pull/31954
