### ISSUE TITLE
Fatal error: Uncaught Error: Class "User" not found in C:\xampp\htdocs\ERP16\core\modules\DolibarrModules.class.php:1613 Stack trace: #0

### ISSUE THREAD

**Issue by Aloof-All** [Dolibarr/dolibarr#31941]
### Bug

<html>
<body>

Fatal error: Uncaught Error: Class "User" not found in C:\xampp\htdocs\ERP16\core\modules\DolibarrModules.class.php:1613 Stack trace: #0 C:\xampp\htdocs\ERP16\core\modules\DolibarrModules.class.php(570): DolibarrModules->insert_cronjobs() #1 C:\xampp\htdocs\ERP16\core\modules\modUser.class.php(386): DolibarrModules->_init(Array, '') #2 C:\xampp\htdocs\ERP16\install\step5.php(185): modUser->init() #3 {main} thrown in C:\xampp\htdocs\ERP16\core\modules\DolibarrModules.class.php on line 1613
--

</body>
</html>

**Comment by FHenry** [comment]
[Fix by 31954](https://github.com/Dolibarr/dolibarr/pull/31954)
