### ISSUE TITLE
Interrupting insertion of invoice, quote and commande object lines via trigger does not show error message

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3196]
Version: 3.7.2

Unlike invoices and customer orders, quotes module does not show the error message provided by the trigger when interrupting the execution.

**Comment by marcosgdf** [comment]
This is an error triggered by the new `errors` and the old `error` object property.

Most parts of the code use `error` but trigger errors are stored in `errors`.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
