### ISSUE TITLE
oldcopy not set

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#31985]
### Bug

In all objects, there's a property "oldcopy" supposed to be object's clone before its modification.
But oldcopy is nearly never correctly set (see [issue #25956 ](https://github.com/Dolibarr/dolibarr/issues/25956), closed by bot

Yet It would be very usefull : when using update trigger on an object, we can't know if a particular property has changed or not !
I'm working on such a use case : we wan't to send a mail when start date of a task has changed. I cannot achieve this with a trigger till I have no solution to retrieve the old value

### Dolibarr Version

all

### Environment PHP

all

### Environment Database

all

**Comment by hregis** [comment]
@vmaury and what will happen if you have several triggers or hooks which modify the object and which do a fetch!! the original oldcopy will no longer be valid!! the oldcopy can't be in fetch function !!

**Comment by vmaury** [comment]
In fetch function it's maybe not the best, but better than now as the oldcopy is always empty 
If you've a better idea you're welcome

**Comment by hregis** [comment]
@vmaury why oldcopy is always empty ? i don't understand

**Comment by hregis** [comment]
@vmaury When you want to modify an object in an action, you must make a clone of the object before modification at a time T... if this is not the case, you must add the oldcopy!

**Comment by vmaury** [comment]
I don't know why ... 
If you search "oldcopy" in CommonObject, the only place it's set is in  setStatusCommon and in setValueFrom methods..

**Comment by hregis** [comment]
@vmaury if we add the oldcopy in the fetch, we risk having side effects because triggers or hooks risk doing fetches which will make the oldcopy not so old! :-)

**Comment by vmaury** [comment]
I don't wand to modify an object, I want to detect in a xxx_MODIFY trigger if a propertie has been modified or not

**Comment by vmaury** [comment]
@hregis : I understand set oldcopy in fetch is not the best solution. 
What do you suggest ?

**Comment by hregis** [comment]
@vmaury actually I would have a solution when I understood the problem... what is your problem? do you have a blocking example?

**Comment by vmaury** [comment]
@hregis : read again the end of the orig bug description :

_I want to send a mail when start date of a task has changed. I cannot achieve this with a trigger till I have no solution to retrieve the old value_

**Comment by hregis** [comment]
@vmaury est-ce qu'après notre conversation téléphonique tu as pu comprendre ?

**Comment by vmaury** [comment]
@hregis oui j'ai compris que la propriété oldcopy était settée essentiellement dans les écrans, en l'occurence pour les tâches dans project/task/task.php

Ce n'est pas l'idéal mais a le mérite d'exister et fonctionner dans la majorité des cas, ce qui pourrait être la devise de Dolibarr en général :-)

**Comment by hregis** [comment]
@vmaury on pourrait l'inclure dans un fetch mais il faudrait ajouter un paramètre permettant de ne pas le définir si besoin afin de ne pas écraser la valeur d'origine lorsqu'on a des triggers susceptibles de refaire un fetch de l'objet qui pourrait créer des effets de bords...
