### ISSUE TITLE
Dolibarr 20.0.1: HTTP 500 Error When Adding Supplier Prices via API

### ISSUE THREAD

**Issue by ElaaxMarketing** [Dolibarr/dolibarr#32039]
### Bug

Attempting to create or update supplier prices via the Dolibarr 20.0.1 API results in a 500 Internal Server Error. Manual entry via the Dolibarr interface works correctly, but API calls with valid payload data fail consistently.

The API responds with an HTTP 500 Internal Server Error when a POST request with the payload is sent to the endpoint /products/{PRODUCT_ID}/purchase_prices.

### Dolibarr Version

20.0.1

### Environment PHP

8.2

### Environment Database

MariaDB 11.3.2-MariaDB-1:11.3.2+maria

### Steps to reproduce the behavior and expected behavior

import requests
import json

# API Configuration
api_url = "https://xxxx/api/index.php/"
api_key = "xxxxxxxxxxxxxxxx"

PRODUCT_ID = 68198  # Example product ID
url = f"{api_url}products/{PRODUCT_ID}/purchase_prices"

# Payload
payload = {
    "qty": 1,
    "buyprice": 15.99,
    "price_base_type": "HT",
    "fourn_id": 3,
    "availability": 7,
    "ref_fourn": "449452",
    "tva_tx": 19.00,
    "charges": "SU2411-00030",
    "delivery_time_days": 2,
    "supplier_reputation": "Favorit",
    "desc_fourn": "string",
    "barcode": "string",
    "fk_barcode_type": 0
}

# Headers
headers = {
    "DOLAPIKEY": api_key,
    "Content-Type": "application/json",
    "Accept": "application/json",
}

# Send POST request
response = requests.post(url, json=payload, headers=headers)

# Check result
if response.status_code == 200:
    print("Supplier price successfully updated.")
    print(response.json())
else:
    print(f"Error {response.status_code}: {response.text}")
    print("Payload:")
    print(json.dumps(payload, indent=4))

### Attached files

![Bildschirmfoto vom 2024-11-21 17-25-17](https://github.com/user-attachments/assets/48529768-294d-4c19-a843-181bf0b2ee2d)
![Bildschirmfoto vom 2024-11-21 17-25-32](https://github.com/user-attachments/assets/cf6a760e-dd0d-48b6-977d-23256382a652)

**Comment by ElaaxMarketing** [comment]
Hi @FHenry, could you please take a look at this issue? It seems to be a problem with the API for supplier prices.

**Comment by FHenry** [comment]
@ElaaxMarketing Could you check and paste the error message in your Dolibarr hosting  server log ?
Error 500 in dolibarr = PHP error in log of web server or php-fpm (depending of you install)
It will help to solve the problem

**Comment by ElaaxMarketing** [comment]
@FHenry Thank you for your response. There are no logs on my PHP installation or server indicating any configuration issues—neither with Nginx nor with PHP. Last night, I upgraded to Dolibarr 20.0.0.2, and now everything works. It seems the issue was a bug in the previous version.
