### ISSUE TITLE
PropaleLigne, OrderLine and FactureLigne given to triggers through update function does not contain all the information

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3206]
Version: 3.5.7

When editing this line, fk_product is not set in the $object that is given to the trigger.

![captura de pantalla 2015-07-15 a las 0 14 43](https://cloud.githubusercontent.com/assets/168744/8686426/81fd1a74-2a86-11e5-8b3a-7e0d4da8a5cb.png)

![captura de pantalla 2015-07-15 a las 0 14 32](https://cloud.githubusercontent.com/assets/168744/8686424/815a1d74-2a86-11e5-92a9-d455b1bb3232.png)

![captura de pantalla 2015-07-15 a las 0 19 13](https://cloud.githubusercontent.com/assets/168744/8686499/35c19d32-2a87-11e5-9b22-282115853847.png)

![captura de pantalla 2015-07-15 a las 0 22 36](https://cloud.githubusercontent.com/assets/168744/8686552/a30e790a-2a87-11e5-8ef5-b567bf9abf7a.png)

**Comment by rdoursenaud** [comment]
Ah! Dolibarr partial objects. I remember leaving a comment about it somewhere… #PrivateJoke
