### ISSUE TITLE
NEW Prelevement - Use structured payment data for Suisse

### ISSUE THREAD

**Issue by Cirillo007** [Dolibarr/dolibarr#32070]
### Feature Request

Hello,

I have clients that need to work with entities in Switzerland.

As they use the creation of xml for banking Prélèvements, Dolibarr says it is not permitted today.

Can we plan to add the CH country. I saw that Belgium has been added recently.

Thank you,

**Comment by sonikf** [comment]
Hi @Cirillo007 
Switzerland uses RF
See https://github.com/Dolibarr/dolibarr/issues/31378
