### ISSUE TITLE
Error about sold to pay (Montant encours)

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#3211]
Hi with 3.7.1, i've a problem with the sum of sold to pay (Montant encours)

On previous invoice, I've sold it with 0,01€ "escompte" and this invoice is act as partially paid. But "Montant encours" list this missing 0,01€ it's wrong. On previous version, the sum was correct : 0€

**Comment by marcosgdf** [comment]
Can you please provide a list of steps to reproduce it?

**Comment by camlafit** [comment]
HI

It's a old invoice about 2012, with an amount of 215,28€ . This invoice has
a 215,27 payment and last centime is done a "remise" to set as paid
(partialy)
Two invoice are as this. Then 2 centimes are set as "remise" to close
invoices.

Before 3.7.1, theses invoices were considered as paid and was perfect. With
3.7.1, this centime is calculate in "reste à payer", then I've now 2
centime in this "reste à payer"

**Comment by marcosgdf** [comment]
When you say that you've got 2 cents in "reste à payer", what do you mean?

I've made a test and this is the result:

![captura de pantalla 2015-07-20 a las 10 45 33](https://cloud.githubusercontent.com/assets/168744/8772439/7a3ca68e-2ecc-11e5-9a55-e3421ab92ced.png)

**Comment by camlafit** [comment]
As you can see you've a _current outsanding bill_ (reste à payer) with
0,020[...]1 € but invoices are sold.
Must be 0€ in this case

**Comment by marcosgdf** [comment]
I think this is related to PR #1240
