### ISSUE TITLE
Impossible to set the date of a payment using API

### ISSUE THREAD

**Issue by ggppdk** [Dolibarr/dolibarr#32111]
### Bug

At
`htdocs/compta/facture/class/api_invoices.class.php`
you have:
`$paymentobj->datepaye = dol_stringtotime($datepaye);`

So the code expects a date string: 2024/11/26 (instead timestamp)

but if I try to give a date string I get a response (from DOLIBARR API):

Message: Bad Request: Invalid value specified for `datepaye`. Expecting unix timestamp, such as 1732638616

It is not possible to workaround this in my code, so I patched the code to be:
`$paymentobj->datepaye = (int) $datepaye;`

I don't know/have not checked if other part code of the code is sending date string instead of a timestamp

Whatever is the write way to fix this (date string or timestamp), I will use it when this is addressed in a future release,
thanks

### Dolibarr Version

20.0.1

### Environment PHP

8.2

### Steps to reproduce the behavior and expected behavior

Use API to created/update a payment

**Comment by homer8173** [comment]
Hello,
the requested formats are "2024-01-01 00:00:00" or "2024-01-01T00:00:00Z" or "20240101T000000Z"
a deprecated format "12/08/2023" can also be used.

What caused your troubles was the in header of the functions : {@type timestamp}
it runs a validator on the input datepaye

As the code below wants to offer both type of date input, I suggest to disable it
