### ISSUE TITLE
[Services] Invalid dates are silently ignored

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3213]
This issue affects:
- Proposals
- Orders (customers and suppliers)
- Invoices (customers and suppliers)
- Contracts
### Defect

When entering an invalid date in the planned start or end date and adding or modifying the line.
The invalid date is silently ignored and and the line saved.
### What's expected

The user should be informed that he put an invalid date and be asked to input a correct one.

**Comment by clCglAvt** [comment]
@eldy
non corrigée en V7
