### ISSUE TITLE
Customer Invoice Search

### ISSUE THREAD

**Issue by keenclick** [Dolibarr/dolibarr#32147]
### Bug

In the customer invoice module I want the customer to see his/her own invoices. Although there are invoices for the customer somehow it does not see it when logged in as this customer.
When performing a search in the LIST section of Customer Invoices the search crashes.

### Dolibarr Version

20.0.2

### Environment PHP

8.1

### Environment Database

Server: Localhost via UNIX socket Server type: MySQL Server connection: SSL is not being used Documentation Server version: 8.0.40-cll-lve - MySQL Community Server - GPL Protocol version: 10

### Steps to reproduce the behavior and expected behavior

login as a 3rd party
head over to Billing/Payment which the 3rd party has permission to
Search.

### Attached files

![2](https://github.com/user-attachments/assets/ad35e461-2080-4961-ad83-ac0cdc437b6c)
![1](https://github.com/user-attachments/assets/ad58d181-7417-42aa-8d84-64551380922f)

**Comment by ITResitve** [comment]
Hi 
Please check in database if exist table llx_element_contact or llx4e_element_contact. 
Thanks

**Comment by keenclick** [comment]
Hello

It does, see screenshot.
And there is info in the table with several rows created from July 2024 to November  2024

![Screenshot 2024-11-29 152535](https://github.com/user-attachments/assets/eb9c8804-1019-4920-9786-b77b7555e55b)

**Comment by ITResitve** [comment]
in file /factura/list.php

![image](https://github.com/user-attachments/assets/5c8a92f2-63d3-412f-b9cd-7f733e549665)

must to chage :

![image](https://github.com/user-attachments/assets/8782704e-99e6-4bb7-aeeb-23a5b008e058)

**Comment by keenclick** [comment]
great, after making the change I still had the same problem however you see that the following line also use the PREFIX llx_, I changed that also to ".MAIN_DB_PREFIX." and the search does not crash anymore.

For me it is solved and assume that someone just forgot to update that part of the code.

thanks for the help.
