### ISSUE TITLE
[Supplier invoices] Reference and label are not displayed in lines

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3214]
![capture d ecran de 2015-07-16 17-26-15](https://cloud.githubusercontent.com/assets/1210367/8727413/d656df1a-2bdf-11e5-91a0-d0a357b2c6dd.png)

**Comment by rdoursenaud** [comment]
They are also gone in edit which suggest they are not stored.
![capture d ecran de 2015-07-16 17-28-06](https://cloud.githubusercontent.com/assets/1210367/8727458/2996872a-2be0-11e5-906d-103d2db6cbb3.png)

**Comment by eldy** [comment]
Can't reproduce with last 3.8 branch. And you ?

**Comment by simnandez** [comment]
It is solved with the last 3.8 branch.
