### ISSUE TITLE
[User card] [Contact card] [Member card] Error in LDAP tab

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3215]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /user/ldap.php?id=x
# Report

Using dev/initdata:
`Fatal error: Call to undefined function ldap_connect() in htdocs/core/class/ldap.class.php on line 175`

**Comment by simnandez** [comment]
@rdoursenaud: have you installed and enabled the php ldap extension?

**Comment by rdoursenaud** [comment]
Nope, but that should not matter.
No such error should be displayed.
I'm OK with a user friendly error saying to get in touch with it's administrator.

Oh and error is even worse with the PHP LDAP extension enabled:

```
( ! ) Xdebug: user triggered in /htdocs/core/lib/functions.lib.php on line 2605
Call Stack
#   Time    Memory  Function    Location
1   0.0005  304920  {main}( )   .../ldap.php:0
2   0.3884  15257552    dol_print_error( )  .../ldap.php:214
3   0.3902  15305480    xdebug_print_function_stack ( ) .../functions.lib.php:2605
Dolibarr has detected a technical error.
This is information that can help diagnostic:
Date: 20150716183700
Dolibarr: 3.8.0-beta
Level of features: 0
PHP: 5.6.11
Server: nginx/1.8.0
OS: Linux mini1 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36

Requested Url: /user/ldap.php?id=4&mainmenu=home
Referer: https://host/user/ldap.php?id=4
Menu manager: eldy_menu.php

Message: Failed to connect to LDAP: -1 Can't contact LDAP server
XDebug informations:
File: /htdocs/user/ldap.php
Line: 214
Function: {main}
```

Again, LDAP server outage is to be expected so this should be displayed as a nice error message to the user.

**Comment by rdoursenaud** [comment]
Also applies to /contact/ldap.php?id=x

**Comment by rdoursenaud** [comment]
Of course the same applies to adherents/ldap.php?id=x
