### ISSUE TITLE
[User card] Leaves tab leads to "File not found"

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3216]
/htdocs/holiday/index.php?mainmenu=holiday&id=x

**Comment by aspangaro** [comment]
Already corrected in my PR

https://github.com/aspangaro/dolibarr/commit/4ae15adc69c04fd3612263a3007199131a916279

**Comment by rdoursenaud** [comment]
Thanks for letting me know @aspangaro
PR is #3209

**Comment by aspangaro** [comment]
@rdoursenaud 

My PR are integrated, you can closed this issue.
Thanks
