### ISSUE TITLE
[Project] Strange icon position

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3219]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /projet/element.php?id=1
# Report

Strange icon position. See screen capture below.

![capture d ecran de 2015-07-16 19-00-19](https://cloud.githubusercontent.com/assets/1210367/8729712/fe03e3f2-2bec-11e5-833a-b0b911e1efab.png)

**Comment by gschratzer** [comment]
fixed in PR 3414
Fix: htdocs/projet/element.php Logoposition #3414
