### ISSUE TITLE
[Leaves] Access to change logs refused

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3221]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /holiday/view_log.php?&action=request
# Report

The user has all permissions and yet access to this page is refused.
![capture d ecran de 2015-07-16 19-04-41](https://cloud.githubusercontent.com/assets/1210367/8729817/ae6d8d42-2bed-11e5-80a5-b210578dbbea.png)
![capture d ecran de 2015-07-16 19-05-40](https://cloud.githubusercontent.com/assets/1210367/8729833/bbd2daf0-2bed-11e5-96fe-5ebc84fcece0.png)

**Comment by simnandez** [comment]
I can't reproduce it.

**Comment by rdoursenaud** [comment]
Yes fixed by b6efa5ed
