### ISSUE TITLE
[Leaves] Access to monthly statements refused

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3222]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /holiday/month_report.php?&action=request
# Report

The user has all permissions and yet access to this page is refused.
![capture d ecran de 2015-07-16 19-04-41](https://cloud.githubusercontent.com/assets/1210367/8729861/e96ec4c4-2bed-11e5-8b2b-407f8c7f08bc.png)
![capture d ecran de 2015-07-16 19-07-35](https://cloud.githubusercontent.com/assets/1210367/8729874/fe068804-2bed-11e5-8bb2-6470b91120db.png)

**Comment by simnandez** [comment]
I can't reproduce it

**Comment by rdoursenaud** [comment]
Fixed in b6efa5ed too ;)
