### ISSUE TITLE
OAuth fails because user query returns nothing. "WHERE u.entity IN (0, 0)" is an set. 

### ISSUE THREAD

**Issue by nubjub** [Dolibarr/dolibarr#32223]
### Bug

The query for user includes `WHERE u.entity IN (0, 0)` this is going to always return a null result.

### Dolibarr Version

develop

### Environment PHP

8.2

### Environment Database

mariadb 10.11.6

### Steps to reproduce the behavior and expected behavior

The following query returns 1 result: `SELECT * FROM `llx_user` WHERE entity IN (1, 2) AND (email = 'testuser@wtfllc.com' OR email_oauth2 = 'testuser@wtfllc.com');`
However the query shown in the log returns nothing:
`SELECT u.rowid, u.lastname, u.firstname, u.employee, u.gender, u.civility as civility_code, u.birth, u.job, u.email, u.email_oauth2, u.personal_email, u.socialnetworks, u.signature, u.office_phone, u.office_fax, u.user_mobile, u.personal_mobile, u.address, u.zip, u.town, u.fk_state as state_id, u.fk_country as country_id, u.admin, u.login, u.note_private, u.note_public, u.pass, u.pass_crypted, u.pass_temp, u.api_key, u.fk_soc, u.fk_socpeople, u.fk_member, u.fk_user, u.ldap_sid, u.fk_user_expense_validator, u.fk_user_holiday_validator, u.statut as status, u.lang, u.entity, u.datec as datec, u.tms as datem, u.datelastlogin as datel, u.datepreviouslogin as datep, u.flagdelsessionsbefore, u.iplastlogin, u.ippreviouslogin, u.datelastpassvalidation, u.datestartvalidity, u.dateendvalidity, u.photo as photo, u.openid as openid, u.accountancy_code_user_general, u.accountancy_code, u.thm, u.tjm, u.salary, u.salaryextra, u.weeklyhours, u.color, u.dateemployment, u.dateemploymentend, u.fk_warehouse, u.ref_ext, u.default_range, u.default_c_exp_tax_cat, u.national_registration_number, u.ref_employee, c.code as country_code, c.label as country, d.code_departement as state_code, d.nom as state, s.label as label_establishment, u.fk_establishment FROM llx_user as u LEFT JOIN llx_c_country as c ON u.fk_country = c.rowid LEFT JOIN llx_c_departements as d ON u.fk_state = d.rowid LEFT JOIN llx_establishment as s ON u.fk_establishment = s.rowid WHERE u.entity IN (0, 0) AND (u.email = 'testuser@wtfllc.com' OR u.email_oauth2 = 'testuser@wtfllc.com') ORDER BY u.entity ASC;`
if this were `WHERE u.entity IN (1, 2)` the query would be successful.
Where is this query coming up with "IN (0, 0)"

**Comment by hregis** [comment]
@nubjub can you try with this fix : https://github.com/Dolibarr/dolibarr/pull/32224

**Comment by eldy** [comment]
> @nubjub can you try with this fix : https://github.com/Dolibarr/dolibarr/pull/32224

This change introduce security vulnerability. If param to find a user was forced to entity 0, then we must search for 0 only. The value to search on any entity in function is -1.
The question is why function is called with 0 and not -1.
I do not experience trouble on using oauth withbmukticomoanybon my side. So there is surely a setup not compatible yet with oauth.
@nubjub what is the value for field entity in database for user testuser@wtflcc ?
What is your mode of multicompany use. Donyoubuse the "transverse mode or not"

**Comment by hregis** [comment]
@eldy @nubjub check this better PR : https://github.com/Dolibarr/dolibarr/pull/32228

**Comment by eldy** [comment]
> @eldy @nubjub check this better PR : https://github.com/Dolibarr/dolibarr/pull/32228

Looks better. I think i can close this one.

**Comment by nubjub** [comment]
This fix was very good, it went from failed and needing to work out from nowhere what's wrong. To dropping my successful authentication into an error state that was comprehensible. Thank you very much.

**Comment by nubjub** [comment]
> > @nubjub can you try with this fix : #32224
> 
> This change introduce security vulnerability. If param to find a user was forced to entity 0, then we must search for 0 only. The value to search on any entity in function is -1. The question is why function is called with 0 and not -1. I do not experience trouble on using oauth withbmukticomoanybon my side. So there is surely a setup not compatible yet with oauth. @nubjub what is the value for field entity in database for user testuser@wtflcc ? What is your mode of multicompany use. Donyoubuse the "transverse mode or not"

The value of field entity of testuser is 1. I'm not sufficiently knowledgeable yet to say if this introduces a vulnerability, if it does I'd hope for a middle ground where you get comprehensible error without successful authentication. 

I think Eldy is likely correct, I was using 20.0.2 and had some issues with oauth I wont go into here. I created a fresh company on develop branch and went straight to oauth without stopping to setup anything else. The user couldn't auth because it was created in a company lacking other necessary requirements?
