### ISSUE TITLE
Email notification on recurring invoice validation, PDF file is missing

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#32232]
### Bug

if you have setup a notification for the client from the notification module (/admin/notification.php)
when you validate an invoice manually, the mail have the file attached.

But if the invoice is validated by the recurring invoice (/compta/facture/invoicetemplate_list.php) the file is missing and it's really annoying because the email template was supposed to include the PDF.

The notification module seems to be called before file generation. I can't propose a fix without impacting your development strategy.

### Dolibarr Version

from 13 to develop

### Environment PHP

ANY

**Comment by Cirillo007** [comment]
I’ve mentionned this bug on this issue #32069

**Comment by homer8173** [comment]
Thank you, I haven't found your issue
