### ISSUE TITLE
[Export] Missing translation in supplier orders

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3227]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /exports/export.php?step=2&datatoexport=fournisseur_3
# Report

Missing translation in supplier orders.
![capture d ecran de 2015-07-16 19-18-58](https://cloud.githubusercontent.com/assets/1210367/8730165/941af130-2bef-11e5-9b94-0830945b434d.png)

**Comment by aspangaro** [comment]
Ok for me with clean install

![2015-09-13 16_52_19-debut](https://cloud.githubusercontent.com/assets/2341395/9837209/f9de00f4-5a37-11e5-8c9b-fe34cc204126.png)

**Comment by rdoursenaud** [comment]
Thanks for the fix @aspangaro.
Confirmed working.
