### ISSUE TITLE
Windows git client cannot pull latest update from Dolibarr git repository

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#32286]
### Bug

We wanted to update our Dolibarr git forked repository to the latest version.  But git pull command is not working, it is giving the following error.

`$ git pull origin develop
From github.com:alsoft10/dolibarr
 * branch                    develop    -> FETCH_HEAD
error: invalid path '.github/changed-lines-count-labeler.yml '
Updating 2b264ae5d07..8ca831ff885
`

### Dolibarr Version

20.0, develop

### Environment PHP

8.1.12

### Environment Database

MySQL

### Steps to reproduce the behavior and expected behavior

1. Use an Windows 10 machine
2. Fork the Dolibarr git repository
3. Clone your forked repository
4. Now run the command, "git pull"

**Comment by alsoft10** [comment]
@eldy it's a serious issue. All community developers who use Windows 10 machine, they can't sync to the latest Dolibarr to work on. It should be fixed at the earliest.

**Comment by eldy** [comment]
Should be fixed. Thanks to retry...

**Comment by alsoft10** [comment]
Thank you @eldy, the problem is fixed.
