### ISSUE TITLE
Product list search not working

### ISSUE THREAD

**Issue by alexschmidtca** [Dolibarr/dolibarr#32292]
### Bug

When viewing the product list and searching by any of the available criteria (category, reference, label, etc) no results appear after clicking the search button (magnifying glass). However, after then clicking the change view buttons, the results show up normally. For subsequent searches I must change the keyword, click the search button (no results), and then click the view (list or tile) button to be presented with the search results.

### Dolibarr Version

20.0.1

### Environment PHP

7.1.33

### Environment Database

MySQL or MariaDB 8.0.22

### Steps to reproduce the behavior and expected behavior

Navigate to product list (/htdocs/product/list.php?leftmenu=product&type=0)
Enter keyword or select filter criteria
Click magnifying glass to search/refresh results
This will return "No record found" result
Click 'list view' or 'tile view' button
Nominal search/filter results will appear

### Attached files

Uploading Dolibarr Product Search Bug.mp4…

**Comment by Cirillo007** [comment]
Yes the error has been identified, I'm trying to make my first pull request

**Comment by Cirillo007** [comment]
in the httdocs/product/list.php on line 122
$search_units = GETPOST('search_units', 'alpha');
must be replaced by
$search_units = GETPOST('search_units', 'int');

I'm not a collaborator, and I cannot create a PR so we need help.

**Comment by alexschmidtca** [comment]
@Cirillo007 
I checked the code in that file, but I think it was line 112 you mean, not line 122?

I changed the code on line 112 and it works now.

Hope the developers/collaborators can implement the fix globally.
