### ISSUE TITLE
[Leaves] Module setup page is stupid

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3230]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /holiday/admin/holiday.php?leftmenu=setup
# Report

Module setup page is stupid.
This screen is useless.
Don't waste my time and get me there directly.
Or at least give me a freaking link!
![capture d ecran de 2015-07-16 19-44-29](https://cloud.githubusercontent.com/assets/1210367/8730759/229b5e74-2bf3-11e5-9541-22824e44342f.png)

**Comment by aspangaro** [comment]
Fix integrated in branch 3.8. Can be closed. Thanks.
