### ISSUE TITLE
[Members] Public subscription page displays GeoIP error

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3231]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /public/members/new.php
# Report

![capture d ecran de 2015-07-16 19-46-40](https://cloud.githubusercontent.com/assets/1210367/8730797/719e6ef8-2bf3-11e5-8327-a99de56f2ab5.png)

**Comment by eldy** [comment]
Did the geoip module was enabled or not ?
If module geoip is enabled and setup not complete, you get this error. If module is not enabled, you should not.

**Comment by rdoursenaud** [comment]
Yes, I believe the module was enabled.
But even unconfigured, we should not spit out error messages to the user.

**Comment by marcosgdf** [comment]
You can close this issue now
