### ISSUE TITLE
Cant Post Large PO's to Inventory

### ISSUE THREAD

**Issue by plp05045** [Dolibarr/dolibarr#32315]
### Bug

When creating large replenishment orders, when you try and receive the order it will not let you post it unless you break it down into several smaller reception 
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/62adbfb3-a306-4dcc-bd4f-37fdf9ec7428">
<img width="702" alt="image" src="https://github.com/user-attachments/assets/850cb505-a05b-4ad0-8b0a-dd2da48adb09">
Reception warehouse listed for each product last one I cannot change to "Halifax". 

### Dolibarr Version

20.0.2

### Environment PHP

Docker

### Environment Database

Docker

### Steps to reproduce the behavior and expected behavior

1. Create a large PO
2. Recevice PO
3. Post PO to Inventory

**Comment by frederic34** [comment]
what is your php ini config for `max_input_vars`

**Comment by plp05045** [comment]
> what is your php ini config for `max_input_vars` 1000

**Comment by plp05045** [comment]
actually I think its commented out

**Comment by frederic34** [comment]
set a higher value, 1000 is not enough, restart server

**Comment by plp05045** [comment]
That worked!! Thanks!
