### ISSUE TITLE
Table 'dolibarr.llx_c_accounting_category' doesn't exist

### ISSUE THREAD

**Issue by nubjub** [Dolibarr/dolibarr#32321]
### Bug

Table 'dolibarr.llx_c_accounting_category' doesn't exist
Some expertise on how I wound up here? How did I wind up without the table? What else is likely broken?
I found the htdocs/install/mysql/tables/llx_c_accounting_category-accounting.sql and inserted it. Is that what you would do?

### Dolibarr Version

21.0.0-beta

### Environment PHP

8.2

### Environment Database

mariadb 10.11.6

### Steps to reproduce the behavior and expected behavior

Modules/Applications: api, syslog, user, export, fckeditor, import, propal, product, paymentbybanktransfer, tax, prelevement, accounting, agenda, banque, commande, facture, fournisseur, ficheinter, loan, margin, salaries, service, societe, ticket, oauth, projet
Database type manager: mysqli
Latest database access request error: SELECT a.rowid as rowid, a.datec, a.tms, a.fk_pcg_version, a.pcg_type, a.account_number, a.account_parent, a.label, a.labelshort, a.fk_accounting_category, a.fk_user_author, a.fk_user_modif, a.active, a.reconcilable, ca.label as category_label FROM llx_accounting_account as a LEFT JOIN llx_c_accounting_category as ca ON a.fk_accounting_category = ca.rowid WHERE a.rowid = 101101010 AND a.fk_pcg_version IN (SELECT pcg_version FROM llx_accounting_system WHERE rowid = 42)
Return code for latest database access request error: DB_ERROR_NOSUCHTABLE
Information for latest database access request error: Table 'dolibarr.llx_c_accounting_category' doesn't exist

Message: Error Table 'dolibarr.llx_c_accounting_category' doesn't exist

**Comment by nubjub** [comment]
Inserting llx_c_accounting_category-accounting.sql seems to have worked, but I haven't ventured beyond the accounting module yet.

**Comment by hregis** [comment]
@nubjub On which page do you have this error?

**Comment by nubjub** [comment]
> @nubjub On which page do you have this error?

Accounting > Setup > Chart of accounts > any Account number link. They all make the query expecting that table to exist.

**Comment by aspangaro** [comment]
Yes, but if we're in the chart of accounts, i.e. in the accounting module (Double entries), this table should exist or should have been created when the module was activated.

llx_c_accounting_category-accounting.sql
“-accounting” is there for this purpose

You updated an alpha from v21 without restarting the update script?

**Comment by hregis** [comment]
@aspangaro @eldy @nubjub 
I just tested a dev installation and indeed, when I activate the advanced accounting module, the two tables "llx_c_accounting_category" and "llx_c_accounting_report" are not created

**Comment by hregis** [comment]
@aspangaro @eldy @nubjub 
ok look this PR : https://github.com/Dolibarr/dolibarr/pull/32348

**Comment by nubjub** [comment]
I am most pleased that there was some value in my asking about this rather than just manually inserting the sql and moving on.
