### ISSUE TITLE
User and Group Links Not Working After Upgrade to Dolibarr 19.0.3

### ISSUE THREAD

**Issue by F-Fatih** [Dolibarr/dolibarr#32327]
### Bug

Hello,

After upgrading Dolibarr from version 5.0.3 to 19.0.3, I noticed that the links for users and groups are no longer working. When navigating to these sections, the application fails to load the expected pages.

user :
![image](https://github.com/user-attachments/assets/d9fa410c-331c-460e-9550-54dcbcd2b423)

group :
![image](https://github.com/user-attachments/assets/69ff3e9f-6fb8-4e03-98c2-cccbe45dece0)

Upon investigating, I found that the index.php file is missing in the htdocs/user/ and htdocs/group directory.

user :
![image](https://github.com/user-attachments/assets/4920df32-eb25-4513-864d-6a991a82db36)

Is there a fix or workaround available for this problem?

Thank you for your help

### Dolibarr Version

19.0.3

**Comment by hregis** [comment]
@F-Fatih maybe you use the Auguria menu ? this menu is in database, and is not updated

**Comment by F-Fatih** [comment]
@hregis Thanks for your help, that's where the problem comes from.
