### ISSUE TITLE
[Agenda] Setup page tab order is weird

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3232]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /admin/agenda.php
# Report

Setup page tab order is weird.
The first tab presented to the user is the second one.
Expected to be on the first…
![capture d ecran de 2015-07-16 19-49-21](https://cloud.githubusercontent.com/assets/1210367/8730856/d49765a0-2bf3-11e5-9018-08431a4fde83.png)

**Comment by aspangaro** [comment]
Fix integrated in branch 3.8. Can be closed. Thanks.
