### ISSUE TITLE
[Barcode] Setup page engine lists should only show generators supporting the format

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3233]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /admin/barcode.php
# Report

Setup page engine lists should only show generators supporting the format.
![capture d ecran de 2015-07-16 19-52-33](https://cloud.githubusercontent.com/assets/1210367/8730916/4555e1a4-2bf4-11e5-9e33-e59e772e8b74.png)

**Comment by simnandez** [comment]
This is not really a bug. When an eninge is not able to manage a generation, it says "not supported". This does not look like a bug
