### ISSUE TITLE
MRP module, doc template "Vinci" is broken when there are more pages

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#32367]
### Bug

Doc template "Vinci" works fine if the amount of material is few (fits in one page) but as soon as number of material becomes a lot, so the document gets more than one page large, the template breaks completely. Tables are bad, text is overwritten, it is completely unusable.

![untitled](https://github.com/user-attachments/assets/a222da5d-2b52-441a-90fd-23e14f338630)

### Dolibarr Version

19.0.3

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/issues/30175
