### ISSUE TITLE
[Printing] Selecting a target without proper configuration should not be allowed

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3236]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /printing/admin/printing.php?mode=test&driver=printipp
# Report

Selecting a target without proper configuration should not be allowed.
Or a nice error message should be displayed to the user.
This looks so unfinished:
![capture d ecran de 2015-07-16 20-06-15](https://cloud.githubusercontent.com/assets/1210367/8731237/37ed8bc8-2bf6-11e5-85c4-6e29a1e7c292.png)

**Comment by aspangaro** [comment]
Maybe @frederic34 can fix the problem ?

**Comment by marcosgdf** [comment]
Related bug: https://doliforge.org/tracker/?func=detail&aid=1762&atid=246&group_id=144
