### ISSUE TITLE
[Dict] State dict encoding issues?

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3237]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /admin/dict.php?id=2
# Report

The greek states are displayed with a bunch of question marks.
I have a unicode compatible font and an UTF-8 configured database.
Data is also question marks in the database.
So the issue seem to be on data install!
Verified and 3.6 and 3.7 are also affected.

![capture d ecran de 2015-07-16 20-10-50](https://cloud.githubusercontent.com/assets/1210367/8731316/d64e9690-2bf6-11e5-9c82-c09b8d532e1a.png)

**Comment by marcosgdf** [comment]
Which is the character set of the table?

**Comment by rdoursenaud** [comment]
``` sql
SELECT character_set_name FROM information_schema.`COLUMNS`
WHERE table_schema = "dolibarr"
      AND table_name = "llx_c_departements"
      AND column_name = "nom";

character_set_name = utf8
```

**Comment by marcosgdf** [comment]
It works fine here...

![captura de pantalla 2015-07-20 a las 10 52 59](https://cloud.githubusercontent.com/assets/168744/8772547/85442f2e-2ecd-11e5-81ae-ead0f7193d84.png)

Tested with 3.6

**Comment by rdoursenaud** [comment]
Did a fresh 3.8.0-beta install and unable to reproduce either.
Closing for now…
Sorry for the noise.
