### ISSUE TITLE
[Dict] Civility dictionary should also provide an abbreviated label

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3238]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /admin/dict.php?id=5
# Report

Civility dictionary should also provide an abbreviated label.
It is common to have abbreviated civilities.
e.g.:
Mister -> Mr
Monsieur -> M.

**Comment by clCglAvt** [comment]
@eldy 
Le dictionnaire civilité fait le lien entre le libellé complet d'une civilité et son abréviation qui est le code de l'enregistrement. Si on a une abréviation, on peut créer un enregistrement avec ce code et un libellé complet.
Donc je ne ressent pas que ceci soit une évolution.
Claude

**Comment by torvista** [comment]
Just a note for future reference for non native-english speakers.

This term that is being used "civility" is incorrect in this context:
https://en.wikipedia.org/wiki/Civility

The correct noun for these prefixes (Mr, Mrs, Sir, Doctor) etc. is an "honorific":
https://en.wikipedia.org/wiki/English_honorifics
