### ISSUE TITLE
[Printing] Module tools page miss error handling

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3239]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /printing/index.php?idmenu=108512
# Report

Module tools page miss error handling.
Network printer unavailability is to be expected.
A nice user error should be displayed instead.
![capture d ecran de 2015-07-16 20-23-45](https://cloud.githubusercontent.com/assets/1210367/8731579/a02e9216-2bf8-11e5-9bd7-b906e8c26c5f.png)

**Comment by marcosgdf** [comment]
I changed the way this error is displayed. Can you please try in the latest version?

**Comment by rdoursenaud** [comment]
Thanks @marcosgdf, way better :+1: .
Not quite understandable though and still trying to execute remaining code (`list_jobs()`) despite knowing it won't work (issues several warnings).
I'll keep it open ;)

**Comment by simnandez** [comment]
I test it into 3.9 branch and seems it work ok

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
