### ISSUE TITLE
Employee is dropped on social update

### ISSUE THREAD

**Issue by rmaziere** [Dolibarr/dolibarr#32402]
### Bug

When I update a social expense, at the moment I saved, the employee input is blanked.

### Dolibarr Version

20.0.0

### Environment PHP

8.2.25

### Environment Database

PostgreSQL

### Steps to reproduce the behavior and expected behavior

Create a social expense with an employee, clik save.
Then edit the social expense and save.

**Comment by aspangaro** [comment]
Thanks for report. Fix proposed
