### ISSUE TITLE
Filtering on "late" elements in lists

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3241]
We should be able to filter lists with "late" ![image](https://cloud.githubusercontent.com/assets/1210367/8731794/ea2fefee-2bf9-11e5-88c8-3817c8c35248.png) elements.
This way we could also make useful links in the homepage dashboard.

**Comment by marcosgdf** [comment]
Related bug 1668 https://doliforge.org/tracker/?func=detail&aid=1668&atid=246&group_id=144

**Comment by alsoft10** [comment]
I have the same issue. I have few hundredes of tasks. From those I want to easily filter out the late tasks. But current dolibarr doesn't have the option. @eldy Please help.
