### ISSUE TITLE
[Dashboard] Checks waiting for deposit bad main menu

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3242]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /index.php
# Report

Checks waiting for deposit links with "accounting" main menu expect check deposits feature is under "bank"!

**Comment by aspangaro** [comment]
@rdoursenaud Sorry, I don't understand this problem. Can we have a picture ?

**Comment by rdoursenaud** [comment]
A picture, no. More words, certainly!

In the homepage "Work tasks board" on the right, you have numbers with links.
The link for "Checks waiting for deposit" is to `/compta/paiement/cheque/index.php?leftmenu=checks&mainmenu=accountancy`.
It should be `/compta/paiement/cheque/index.php?leftmenu=checks&mainmenu=bank`.

Simple, really ;)

**Comment by aspangaro** [comment]
Thanks @rdoursenaud

**Comment by aspangaro** [comment]
Fix integrated in branch 3.8. Can be closed. Thanks.
