### ISSUE TITLE
[Homepage] Last n members link broken

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3244]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /index.php
# Report

Last 5 members link broken. The link on the ref does not have the rowid parameter populated leading to a blank page.

**Comment by aspangaro** [comment]
Fix integrated in branch 3.8. Can be closed. Thanks.
