### ISSUE TITLE
BUG: No State/Province in Add member form, but add thirdparty does have it

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr#32446]
### Bug

When adding a new member, and you select a country which has states/provinces, it does not show any states/provinces based on the selected country. This does work when adding a new thirdparty.

### Dolibarr Version

20.0.0 docker image

### Environment PHP

8.2.7

### Environment Database

MariaDB 11.5.2-MariaDB-ubu2404

### Steps to reproduce the behavior and expected behavior

Enable member and thirdparty modules

click create new member, select France as country, no states/provinces appear which I would expect because I get states/provinces when I do the same with a new thirdparty

### Attached files

![add_member_france_no_provinces](https://github.com/user-attachments/assets/4fa8020a-9173-4d64-9ab6-bbf37edbafc9)
![add_thirdparty_in_france_which_does_have_provinces](https://github.com/user-attachments/assets/7d810ff5-5bb0-4f3d-b242-1c4ab8e86259)

**Comment by JonBendtsen** [comment]
Same issue with United Kingdom and United States. This works under Thirdparties, but not under Members

**Comment by hregis** [comment]
@JonBendtsen i don't have this problem in v20 !

**Comment by JonBendtsen** [comment]
> @JonBendtsen i don't have this problem in v20 !

oh, that is particular. Are you also running 20.0.0? or one of the other versions?

How do we track down why we experience a difference?

**Comment by hregis** [comment]
@JonBendtsen i use 20.0.2 ( + last fixes in 20 branch)... try to upgrade to 20.0.2

**Comment by JonBendtsen** [comment]
Hey @hregis the bug persists even with v20.0.2 docker image. How can we track down other differences between your and my installation?

**Comment by hregis** [comment]
@JonBendtsen line 1082 of "adherents/card.php"

```
if ($soc->country_id || GETPOSTISSET('country_id')) {
	print img_picto('', 'state', 'class="pictofixedwidth"');
	print $formcompany->select_state(GETPOSTISSET('state_id') ? GETPOSTINT('state_id') : $soc->state_id, GETPOSTISSET('country_id') ? GETPOSTINT('country_id') : $soc->country_code);
} else {
	print $countrynotdefined;
}
```

**Comment by JonBendtsen** [comment]
@hregis  this worked, I suppose it will end up in v20 or v21?

**Comment by hregis** [comment]
@JonBendtsen 20.0.3 :-)

**Comment by JonBendtsen** [comment]
@hregis how come I didn't find another issue with similar title when I searched for it?

**Comment by hregis** [comment]
@JonBendtsen maybe fix in develop branch and backported to 20 branch ?

https://github.com/Dolibarr/dolibarr/commit/670e6464e8d08ea4fd26517ebb080bc2d3e4e73c

**Comment by JonBendtsen** [comment]
@hregis  okay, I would not have found that even when searching for member and state/province in Pull Requests.
