### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Pyhot** [Dolibarr/dolibarr#32451]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[The Incoterm field overwrites the location with a "0"]

## Environment
- **Version**: 20.0.2 
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 8.1.29
- **Database**: MySQL or MariaDB 8.0.37
- **URL(s)**: /htdocs/commande/card.php?id=318

## Expected and actual behavior
[The Incoterm text field should allow the location to be entered, but it is systematically overwritten with 0]

## Steps to reproduce the behavior
[this behavior is since update 20.0.2 ]

## [Attached files]
[*<img width="376" alt="Capture d’écran 2024-12-22 à 23 40 04" src="https://github.com/user-attachments/assets/48b6c951-4a92-4841-8ad7-059cc7aa11e2" />*]

**Comment by hregis** [comment]
@Pyhot it's already fixed for 20.0.3 : https://github.com/Dolibarr/dolibarr/commit/1a752c16cfcab8703c3c80258e9e5ea9ec564184

**Comment by hregis** [comment]
@Pyhot and again with this new PR : https://github.com/Dolibarr/dolibarr/pull/32452/files

**Comment by Pyhot** [comment]
@hregis thanks for patches. 

One is missing /htdocs/expedition/card.ph , Line 186

**Comment by Pyhot** [comment]
@hregis thanks for patches.

and also maybe :

- htdocs/delivery/card.php, Line 196
- htdocs/reception/card.php, Line 247
- htdocs/reception/card.php, Line 635
-  htdocs/company/card.php, Line 810

**Comment by hregis** [comment]
@Pyhot yes it's already fixed : https://github.com/Dolibarr/dolibarr/pull/32452

**Comment by Pyhot** [comment]
@hregis Well done 👍
Thanks for your help !
