### ISSUE TITLE
Deprecated error on doleditor

### ISSUE THREAD

**Issue by ALYMBEK-KG** [Dolibarr/dolibarr#32467]
### Bug

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/htdocs/core/class/doleditor.class.php on line 169

### Dolibarr Version

20.0.0

### Environment PHP

8.2

### Environment Database

mariadb-10.11

**Comment by hregis** [comment]
@ALYMBEK-KG where are you this error ?

**Comment by hregis** [comment]
@ALYMBEK-KG i send a PR : https://github.com/Dolibarr/dolibarr/pull/32469
