### ISSUE TITLE
Bug: Warning: Undefined variable $morehtmlright - Loan Module

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#32475]
### Bug

Version: 20.0.2

Hello,
I created a loan (emprunt) but I also have the Project module activated and I attached a project to the loan.
With the thumbnail attached files, notes, suivi, I can see a warning
`Warning: Undefined variable $morehtmlright`

![image](https://github.com/user-attachments/assets/b27da2f0-89a3-4a31-9d82-1957053ed1d6)

On develop I see this error on thumbnail Notes
`Fatal error: Uncaught Error: Class "FormProjets" not found in /htdocs/applications/dolibarr-develop/htdocs/loan/note.php:85 Stack trace: #0 {main} thrown in /htdocs/applications/dolibarr-develop/htdocs/loan/note.php on line 85`

### Dolibarr Version

20.0.2,develop

**Comment by hregis** [comment]
@mikygee this is fixed with this PR : https://github.com/Dolibarr/dolibarr/pull/32478 and https://github.com/Dolibarr/dolibarr/pull/32479

**Comment by mikygee** [comment]
Hello Regis,
Thank you.
I modified manually the different files on my 20.0.2 installation following your fixes and it worked.
I close this issue.
