### ISSUE TITLE
[Insight] PHP debug statements found - in htdocs/…/admin/productaccount.php, line 125

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3251]
**[in htdocs/accountancy/admin/productaccount.php, line 125](https://github.com/dolibarr/dolibarr/blob/1d0a8ceca9ca09e807eb1fca674ca36baca11550/htdocs/accountancy/admin/productaccount.php#L125)**

> `print_r()` should only be used for debug, and not committed to the source code repository.

``` php
    $sql1 = "UPDATE " . MAIN_DB_PREFIX . "product as p";
    $sql1 .= " SET p.accountancy_code_sell=" . $account_number_sell;
    $sql1 .= ' WHERE p.rowid IN (' . implode(',', $changeaccount) . ')';

    dol_syslog('accountancy/customer/lines.php::changeaccount product sell sql= ' . $sql1);
print_r ($sql1);
    $resql1 = $db->query($sql1);
    if (! $resql1) {
        $error ++;
        setEventMessage($db->lasterror(), 'errors');
    }
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b83b8ab4-e851-4233-896d-2b9f8d89312f/analyses/139)_

**Comment by aspangaro** [comment]
Fix integrated in branch 3.8. Can be closed. Thanks.
