### ISSUE TITLE
[Insight] PHP debug statements found - in htdocs/…/admin/productaccount.php, line 150

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3252]
**[in htdocs/accountancy/admin/productaccount.php, line 150](https://github.com/Dolibarr/dolibarr/blob/1d0a8ceca9ca09e807eb1fca674ca36baca11550/htdocs/accountancy/admin/productaccount.php#L150)**

> `print_r()` should only be used for debug, and not committed to the source code repository.

``` php
    $db->begin();

    $sql1 = "UPDATE " . MAIN_DB_PREFIX . "product as p";
    $sql1 .= " SET p.accountancy_code_buy=" . $account_number_buy;
    $sql1 .= ' WHERE p.rowid IN (' . implode(',', $changeaccount) . ')';
print_r ($sql1);    
    dol_syslog('accountancy/customer/lines.php::changeaccount product buy sql= ' . $sql1);
    $resql1 = $db->query($sql1);
    if (! $resql1) {
        $error ++;
        setEventMessage($db->lasterror(), 'errors');
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b83b8ab4-e851-4233-896d-2b9f8d89312f/analyses/139)_

**Comment by aspangaro** [comment]
Fix integrated in branch 3.8. Can be closed. Thanks.
