### ISSUE TITLE
[Insight] PHP debug statements found - in dev/examples/get_contracts.php, line 75

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3253]
**[in dev/examples/get_contracts.php, line 75](https://github.com/Dolibarr/dolibarr/blob/1d0a8ceca9ca09e807eb1fca674ca36baca11550/dev/examples/get_contracts.php#L75)**

> `print_r()` should only be used for debug, and not committed to the source code repository.

``` php
// Create invoice object
$obj = new Contrat($db);
$obj->socid=$argv[1];

$listofcontractsforcompany=$obj->getListOfContracts('all');

print_r($listofcontractsforcompany);


// -------------------- END OF YOUR CODE --------------------

```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b83b8ab4-e851-4233-896d-2b9f8d89312f/analyses/139)_

**Comment by aspangaro** [comment]
Fix integrated in branch 3.8. Can be closed. Thanks.
