### ISSUE TITLE
Datable JQuery Component (and extra) do not work fine with new theme and jQury 1.11

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#3258]
only solution is to upgrate datatable component

**Comment by rdoursenaud** [comment]
Upgrading **all** the libraries should really be the first thing we do _before_ a new development cycle.
That way, we'd have the time to fix these problems earlier.
Also upgrading jQuery without upgrading it's plugins is reckless IMHO.
My 2 cents.
