### ISSUE TITLE
inconsistency between htdocs/core/tpl/notes.tpl.php and htdocs/core/actions_setnotes.inc.php

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#3259]
in htdocs/core/actions_setnotes.inc.php "permissions" variable is $permissionnote but in htdocs/core/tpl/notes.tpl.php is $permission.
If it work for standard module, for external module that wish to use this template, it is needed to decalre two "persission" variables
$permission=$user->rights->module->write
$permissionnote=$user->rights->module->write

**Comment by marcosgdf** [comment]
Version?

There is no need to use `$user->rights->module->write`, we can now use `$object->getRights()->write` in develop or `$object->getRight('write')`

**Comment by FHenry** [comment]
In 3.8
