### ISSUE TITLE
Translation ViewList into htdocs/user/hierarchy.php is missing

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#3260]

**Comment by FHenry** [comment]
In en_US file ViewList key is define in main.lang
but in all other language it is define into agenda.lang

**Comment by FHenry** [comment]
I've update french translation file into Transiflex, sould be solve on next translation update process

**Comment by rdoursenaud** [comment]
Yes, moved in 3ace9405050fda8b28130bf11f9557f6bbe39d25. So definitely a translation issue.
