### ISSUE TITLE
unable to create user duplicate entry for key uk_user_api_key in card

### ISSUE THREAD

**Issue by elarifr** [Dolibarr/dolibarr#3264]
dolibarr 3.8.0 beta
when i try to create user 
![2015-07-17 18_56_01-dolibarr 3 8 0 create user bug api_key](https://cloud.githubusercontent.com/assets/6930199/8752703/51c5c3ba-2cb6-11e5-9f18-c9c5a8832658.png)

**Comment by elarifr** [comment]
i have dropped key 
ALTER TABLE llx_user DROP KEY `uk_user_api_key` 

and then i can create my new user

in db all row 'api_key' are empty (not NULL)

install was from 3.8.0 alpha updated to 3.8.0beta

only diff found in the table llx_user between 3.8.0a and 3.8.0beta is  
KEY `idx_user_api_key` (`api_key`)

mysql version 5.5.43 (ovh mut)

**Comment by elarifr** [comment]
edited row api_key add any unique value value

re-added unique key in mysql
ALTER TABLE llx_user ADD UNIQUE KEY `uk_user_api_key` (`api_key`)

activate api module in dolibarr

regenerate api key 

because of api check if api is not enable there is also a bug in user / card.php that can't select admin role. the } is wrong placed after admin select

**Comment by rdoursenaud** [comment]
Is this bug triggered on a fresh install or an upgrade from 3.7.x?
Upgrading from alpha to beta is unsupported (the user is supposed to know what he's doing and make a fresh install or restore backups) .

**Comment by elarifr** [comment]
this is not an update issue.
problem is with api rest module
if not enable no api key is generated and it can not store twice empty api_key 

an other mistake if api is not enable you can't select admin role

**Comment by elarifr** [comment]
tried to provide a pr #3267

**Comment by elarifr** [comment]
closed #3282
