### ISSUE TITLE
Salaries module shows amounts with currency symbol unlike the rest of Dolibarr

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3289]
Version: 3.7.1

In Dolibarr we almost never show the currency next to the amount because we don't usually know which currency are we dealing with, but Salaries module does.

Page: http://dolibarr.local/compta/salaries/index.php

![captura de pantalla 2015-07-20 a las 11 28 58](https://cloud.githubusercontent.com/assets/168744/8773188/9d2fcf9e-2ed2-11e5-94b5-37306a104176.png)
vs
![captura de pantalla 2015-07-20 a las 11 29 08](https://cloud.githubusercontent.com/assets/168744/8773189/9dd7a020-2ed2-11e5-8e46-db98b2b43f82.png)

**Comment by marcosgdf** [comment]
It looks like this was made on purpose by @eldy at 59042a30e10245486c291b9c6f9a72a07a2ccbc2

So... is this a bug or not?

**Comment by rdoursenaud** [comment]
I'd say yes. Still looks weird to me!
