### ISSUE TITLE
[Accessibility] Make sure each and every page displays a title

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3292]
The page title is essential to help contextualize.

A lot of pages miss a proper title or have weak titles that don't convey enough informations.

A good title should be short and meaningful.

Repeating the application name in the title should be avoided.
### References:

http://www.w3.org/QA/Tips/good-titles.html
#2566

**Comment by eldy** [comment]
The hidden option MAIN_HTML_TITLE address this need.
With 3.9, it was reverted to be set by default to go in direction you suggest. Thirparties, contacts, and proejcts card are supported to show directly ref of object. We should port other pages.
Also all pages are supported to not show anymore application name (logo into tab of browser looks enough)
