### ISSUE TITLE
Login page form icons not shown

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3293]
The code makes it clear that an icon is supposed to be shown before the login and password fields.

But there is no space provisioned for them making the form field overlap them.

Here I've hacked a few `&nbsp;` in `login.tpl.php` before the login form input to show that the icon is indeed loaded:
![capture d ecran de 2015-07-20 20-05-15](https://cloud.githubusercontent.com/assets/1210367/8783204/a84cf396-2f1a-11e5-97c0-d03e358b83c0.png)

**Comment by marcosgdf** [comment]
It looks like this is intended. Check commit 4d7f3cb741d0c6480736115212c31e3f9aaf3a3f
