### ISSUE TITLE
VAT/Tax Calculation Error with multiple line items

### ISSUE THREAD

**Issue by pdt256** [Dolibarr/dolibarr#33]
Dolibarr is calculating VAT/Tax rates by rounding per order-line and then summing them to get the total tax due. This causes the sales tax totals to be off by a few pennies in some cases.

I have 39 line items with a quantity of 400 products.

Here are the calculations from Dolibarr:
Amount (net of tax): $2,097.60
Amount Sales Tax: $173.11
Amount (inc. tax): $2,270.71

The correct calculation using 8.25% Texas sales tax: (2097.6 \* .0825)
Amount (net of tax): $2,097.60
Amount Sales Tax: $173.05
Amount (inc. tax): $2,270.65

Dolibarr is charging $0.06 more than it should in this case.

**Comment by hregis** [comment]
Hi,
you must use the bugtracker on the Dolibarr project in doliforge.org

https://doliforge.org/projects/dolibarr/
https://doliforge.org/tracker/index.php?group_id=144
