### ISSUE TITLE
Propal permission problem

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#3321]
In 3.7.1 i found problem with permissions. When user have permission to Read third parties linked to user and Read commercial proposals + Create/modify commercial proposals

Propal is creating but can't open it... When i give permission: Extend access to all third parties (not only those linked to user). the propal can be normally open.

**Comment by marcosgdf** [comment]
Bug introduced in bc672c2c2365a1dd682505983d7e7ad40cd9e66b
