### ISSUE TITLE
invoice on shipping warning

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#3336]
displays says 
 Attention, une ou plusieurs factures existent déjà
but there is no invoice for this shipping 

SH1507-0003 (Dernière facture en rapport FA1507-0003 Montant HT FA1507-0003) 
but invvoice shown is linked to another shippment  SH1507-0002 in my case

**Comment by rdoursenaud** [comment]
Steps to reproduce?
Which version please?

**Comment by tiaris** [comment]
dolibarr 3.8 beta
create a shippment and an invoice for this shippment
then create another shippment from same order (partial shippments) and try creating an invice on this new shippment

**Comment by marcosgdf** [comment]
Can't reproduce. Probably due to bug #3515

**Comment by rdoursenaud** [comment]
@tiaris , can you confirm that the issue has been resolved by the #3515 fix?

**Comment by aconits** [comment]
Hi,

This comportement is normal, each invoice generate from shipment are linked to shipment and the original order
So the event message is not a bug it say to be careful because you have already one or more invoices linked to your order

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
