### ISSUE TITLE
broken links on shippment card

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#3338]
Id of shippment is empty when editi,g "origine" and "délai de livraison"

doli38/expedition/shipment.php?action=editavailability&id=
and 
doli38/expedition/shipment.php?action=editdemandreason&id=

So it results in a blank page

**Comment by rdoursenaud** [comment]
Version please?

**Comment by tiaris** [comment]
dolibarr 3.8 beta
