### ISSUE TITLE
[Proposals] Revision index

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3339]
It is often useful to keep all proposals made for a business deal until agreement is found.
One common implementation is to rely on an incremental revision index that is postfixed to the reference.
### Rough specification

Add an option for revision indexes in proposals numbering module(s).

When active, postfix new proposal references with eg. "-1".

On proposal page, add a "New revision" button that would:
- close the proposal to "Not signed" status with a "New revision" comment.
- create a clone of the proposal on the same thirdparty with the same reference but with the postfixed index incremented.
- link both so they appear related to each other

**Comment by eldy** [comment]
Another approach would be to archive all pdf generated with date/version (but only pdf is archived). Very light and simple, this way may be an external module idea.

For your solution, i would suggest no postfix at all for active proposal and we add date or version for each old version.
