### ISSUE TITLE
[Travis-CI] Upgrade to new infrastructure

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3343]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by eldy** [comment]
This is only possible for packages not doing sudo.
For dolibarr we need this to install mysql 5.6 instead of the defautl ysql that is bugged.

Other action are done into travis script with sudo but i am not sure it is required to use the sudo for them

**Comment by rdoursenaud** [comment]
MariaDB is now available with that syntax:

```
addons:
    mariadb: "10.0"
```

See https://github.com/travis-ci/travis-ci/issues/1081

It should be ok for our requirements, don't you think?

**Comment by jfefe** [comment]
:+1:

**Comment by rdoursenaud** [comment]
Even with the new Travis configuration, we still need sudo for enabling modules.
This is currently unachivable for Dolibarr.
