### ISSUE TITLE
Checking a VAT number with spaces

### ISSUE THREAD

**Issue by tomours** [Dolibarr/dolibarr#3349]
Hi,

One of the first things I did, while starting to try Dolibarr, was to fill info about my company. I filled my VAT number : "FR 13 794..." and saw the "check" button. Oh, that's nice ! Click. Didn't work :(
In fact, it didn't work because the webservice Dolibarr uses to check VAT numbers doesn't understand spaces.
Would it be possible to change, in societe/checkvat, around line 53, to change 
`$vatNumber=substr($_REQUEST["vatNumber"],2);`
into something like
`$vatNumber=preg_replace('/\s/', '', substr($_REQUEST["vatNumber"],2));`

By doing this we could enter good looking VAT numbers (with spaces) and still check them.

**Comment by rdoursenaud** [comment]
Hey, if you want to suggest code, the best way is to make a pull request ;)
I would have used `\w` instead of `\s` in the regex to catch any type of whitespace (like non breakable spaces, tabs…) by the way.

**Comment by tomours** [comment]
All right, I'll try ! (never done that before)

**Comment by rdoursenaud** [comment]
Great!
A good Git tutorial is at https://try.github.io
You may also want to have a look at the awesome documentation at https://git-scm.org/doc
Please also have a look at our developer documentation http://wiki.dolibarr.org/index.php/Developer_documentation
Good luck ;)

**Comment by rdoursenaud** [comment]
Oh, and not to forget our contributors doc: https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md#basic-workflow
