### ISSUE TITLE
Install dependencies from composer

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3351]
# Summary
- [ ] ACE
- [X] CKEditor done in d7139df broken by a4ab5f55529ce0e4e586044b22a1ece31f0e45d7 hopefully restored with 38538e617e97b6d7eb453c99e22f339c36e7f954
- [X] DebugBar
- [ ] EvalMath
- [X] Escpos-php
- [ ] GeoIP2
- [X] Mobiledetect 5a4dbae
- [ ] NuSOAP
- [ ] OAuth
- [ ] ODTPHP
- [ ] Pear Mail_MIME
- [ ] ParseDown
- [X] PHPExcel de3c8be
- [ ] php-iban
- [ ] PHPoAuthLib
- [ ] php-ipp (aka PHPPrintIPP?)
- [X] Restler b12be0a
- [ ] Swift Mailer
- [X] Stripe
- [X] TCPDF 26bb942
- [ ] TCPDI (See https://github.com/Dolibarr/dolibarr/issues/4207#issuecomment-167430352)

## CKEditor

Update available.

["ckeditor/ckeditor": "4.8.0"](https://packagist.org/packages/ckeditor/ckeditor)

## EvalMath

["webit/eval-math": "1.0.1"](https://packagist.org/packages/webit/eval-math)

TODO

## Escpos-php

Update available.

["mike42/escpos-php": "1.6"](https://packagist.org/packages/mike42/escpos-php)

## FPDI

ABANDONED

Changes in ba98f6f9 prevents composer installation.
@eldy What is the rationale behind these changes?
The commit message is not very helpful…

Same version:
["setasign/fpdi": "1.5.2"](https://packagist.org/packages/setasign/fpdi)
Latest version:
["setasign/fpdi": "1.5.4"](https://packagist.org/packages/setasign/fpdi)

## GeoIP

Very old 1.4 version used.

Latest versions:
- ["geoip/geoip": "v1.15"](https://packagist.org/packages/geoip/geoip)
- ["geoip2/geoip2": "2.3.1"](https://packagist.org/packages/geoip2/geoip2)

## Mobiledetect

OK

Update available.

["mobiledetect/mobiledetectlib": "2.8.3"](https://packagist.org/packages/mobiledetect/mobiledetectlib)

## NuSOAP

Evaluate local changes in
- 5d1e7c2d85806deace7ff94f0d44b48ac00a474d
- 02e4a29baab66058ab108d6eeb057e2641105a1c
- 03711cf6f285929dc40d5bea842b6070a4f8686d
- d34c4518d2efd7df05f366cfccf861d97b236359
- d2a718d0e6c22d3e78f630daca78f11cd6507eb6

["fergusean/nusoap": "0.9.5"](https://packagist.org/packages/fergusean/nusoap)

## Pear Mail_Mime

NuSOAP dependency

["pear/mail_mime": "1.8.9"](https://packagist.org/packages/pear/mail_mime)

## OdtPHP

Very old version 1.0.1 used and tweaked to death.
Why not use and contribute upstream?
Stop reinventing the wheel!

Latest version:
["cybermonde/odtphp": "v1.7"](https://packagist.org/packages/cybermonde/odtphp)

## ParseDown

TODO

["erusev/parsedown": "1.6.4"](https://packagist.org/packages/erusev/parsedown)

## PHPExcel

OK

["phpoffice/phpexcel": "1.8.0"](https://packagist.org/packages/phpoffice/phpexcel)

Could be updated.

## php-iban

TODO

Update 2.1.6 available 

["globalcitizen/php-iban": "2.1.6"](https://packagist.org/packages/globalcitizen/php-iban)

## PHPoAuthLib

TODO

## php-ipp

Changes in bfe85cbf3781daa2d2991a893224996c3ddf2491

["pigult/php-ipp": "dev-master"](https://packagist.org/packages/pigult/php-ipp)

## Restler

OK

["restler/framework": "3.0-RC6"](https://packagist.org/packages/restler/framework)

## TCPDF

OK

["tecnick.com/tcpdf": "6.2.6"](https://packagist.org/packages/tecnick.com/tcpdf)

Could be updated.

## TCPDI

Customized version.

["propa/tcpdi": "dev-master"](https://packagist.org/packages/propa/tcpdi)

## Swift Mailer

TODO

Update available.

["swiftmailer/swiftmailer": "6.0.2"](https://packagist.org/packages/swiftmailer/swiftmailer)

## Stripe

TODO

Update available.

["stripe/stripe-php": "6.3.1"](https://packagist.org/packages/stripe/stripe-php)

**Comment by marcosgdf** [comment]
So we're finally implementing Composer? Remember when I proposed it and Laurent didn't agree

**Comment by rdoursenaud** [comment]
@marcosgdf I try again with the proposed strategy that @eldy agreed on in your #1759 PR comments.
That is:
- vendor path set to /htdocs/includes
- no autoloader (yet)
- composer.lock and libraries committed to tree

**Comment by aspangaro** [comment]
@rdoursenaud For Geoip who are too old, we can replace it by Geocoder https://github.com/geocoder-php/Geocoder maybe ?

**Comment by rdoursenaud** [comment]
@aspangaro I don't know what purpose the geoip module serves in Dolibarr. I just listed all currently used libraries for completion.
AFAIK geoip and geocoding are two different processes. GeoIP tries to match an IP to a geographical location whereas geocoding maps an address to geographical coordinates.
Of course one might chain the two processes to geocode and IP X)

**Comment by rdoursenaud** [comment]
Now that my PR has been accepted, "freshness" status of composer-managed dependencies may be found at https://www.versioneye.com/user/projects/55ea3201211c6b0014001116?child=summary

I believe we should try and upgrade to the latest available releases at each development cycle start so we have time to fix any potential API changes or regressions during the cycle.

**Comment by eldy** [comment]
About question "What is the rationale behind these changes?".
There is a lot of source of error when generating pdf. Without the path, you have no luck to see error reason. This make understand what's wrong not possible.

**Comment by marcosgdf** [comment]
Why don't you catch the exception outside the library? That change is not very useful there...

**Comment by eldy** [comment]
It was not possible, because no exception was thrown (lib cleaned it). Code was added just to be able to get something outside the library.

**Comment by rdoursenaud** [comment]
@eldy Thanks for the clarifications. I now grasp why it was needed as a short term fix. But that sounds like an upstream bug to me. Why not work with them to solve the issue for everyone? Same goes for OdtPHP.

**Comment by rdoursenaud** [comment]
@eldy Also on second thought adding an application wide exception handler should do the trick without the need to modify upstream code:
https://secure.php.net/manual/function.set-exception-handler.php
That's what FirePHP and Raven (Sentry) does.

**Comment by bsene** [comment]
> @marcosgdf I try again with the proposed strategy that @eldy agreed on in your #1759 PR comments.
> That is:
> 
>     * vendor path set to /htdocs/includes
> 
>     * no autoloader (yet)
> 
>     * composer.lock and libraries committed to tree

Hi,

Despite I'm new to this project I wondered why uses this strategy ?
At first why are you putting vendor directory in `htdocs` ? What the main reason
As far as I know you could use all dependencies under it with the proper autolading strategy.

Regards,
Birame

**Comment by dpriskorn** [comment]
What is the status of this?

**Comment by bsene** [comment]
@eldy @rdoursenaud up please

**Comment by bsene** [comment]
@eldy  @rdoursenaud I've made a PR for Stripe dependency

**Comment by cfoellmann** [comment]
can we move the list to the wiki?

**Comment by cfoellmann** [comment]
@eldy I am just getting back to needing some composer packages which can result in requirement issues.

Can we make the composer "feature" ready for production?

- properly use composer.json to "update" packages in includes
- commit these files to the repo as it is now
- users can use the autoloader if they want in custom code
  - core should adopt the autoloader over time
- "advanced" users can delete the include/ files and composer.lock + modify the composer.json to fetch additional packages


our current issue as an example:
I want to integrate `microsoft/microsoft-graph` and need `guzzlehttp/guzzle`.
There is no way to know if any dependency of these packages clash with the versions of packages in the dolibarr core.

**Comment by gnovaro** [comment]
The package swiftmailer is abandoned and no longer maintained. The author suggests using the [symfony/mailer](https://packagist.org/packages/symfony/mailer) package instead.

**Comment by eldy** [comment]
Due to too many troubles with libraries coming form composer (unsolvable conflicts, not up to date library compared to official sources, introduction of a lot of security vulnerabilities when updating using composer that install tons of unwanted sub-libraries), we abandon this task.

**Comment by OdyX** [comment]
Sorry to say, but this leaves the Dolibarr sourcecode as a terrifying mess of code copies, not using standard autoloading or dependencies' resolution, with the argument that composer dependencies are hard to maintain properly (not untrue). This is going to make introduction to the Dolibarr sourcecode harder and harder for PHP developers (who, I'm sure, use composer, autoloading and dependencies resolutions as granted and standard in all modern PHP environments).

Please re-consider this decision! Using proper dependencies' resolution will make your code base smaller, easier to understand, easier to maintain (1/3 of the size is in `includes`, that are not even git submodules), at the expense of getting a proper hand on composer & co. It also makes introduction of new features much easier, without having to integrate an unversionned code copy from third-party repositories.

**Comment by cfoellmann** [comment]
I am with @OdyX 
Composer makes updates possible and therefore increases security by regular updates.
"unwanted sub-libraries" are used by the packages either way. When you get a downloaded zip from a package all these dependencies are included. Also with composer duplicated dependencies are replaced with shared ones.

I can say that I really like Dolibarr but the usage of external packages is a real mess (`includes/`).

Composer has become THE standard package manager for PHP.
You have to balance the lack of enough manpower to do everything custom vs the "overhead" that a package manager introduces.

So my vote is still for proper usage of composer for the `includes/` packages.
Maybe introduce a custom autoloader or something.

**Comment by lucprefontaine** [comment]
Hi,

just spent a few hours integrating Nette/Latte in a new Dolibarr module I have been working on for 3 weeks.
Latte uses composer in the latest versions only.
I had to go back years ago on github to find a previous version using the autoloader to get an initial recipe that I had to tweak and merge in my module class. Getting there was a pain in the axx.

Sorry, I do not see myself generating HTML by hand with string concatenations. We're in 2024...
Now I can hope for a cleaner separation between the backend and the UI.

The JVM world uses maven, Python has pip, PipEnv,... .Net has NuGet, Rails has gems, etc.
Dependency management can be hellish.
Been using all of the above in the last 15 years.
And still there are issues remaining but w/o these ? 
I'm not bald in part because of these tools...

Not having a dependency manager has the following consequences;
- no refactoring of the existing code base possible w/o using hacks.
- hinders development for newcomers.
- prevents using more recent tools to improve the code base and shrink it. Copy an paste is not the way to go. At all.
- Any hack to integrate new plugins/libraries is not guaranteed to work in the future. What if someone else tries to integrate another version of Latte in their own module ? Oupse... 
- 
I understand that Dolibarr has been created 20 years ago but certainly there are ways to keep the code base in check.

Please reconsider. If there's something in the works and it's stalled, 
let me know. I can have a shot at it.


Thank you,
Luc P.
