### ISSUE TITLE
Error while trying to modify a contract reference

### ISSUE THREAD

**Issue by tomours** [Dolibarr/dolibarr#3355]
When I try to modify a contract reference, I have the following error :

Date: 20150807113947
Dolibarr: 3.8.0-beta
Niveau de fonctionnalités: 0
PHP: 5.5.9-1ubuntu4.11
Server: Apache/2.4.7 (Ubuntu)
OS: Linux ours-IMEDIA-D5322-FR 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:39.0) Gecko/20100101 Firefox/39.0

Url sollicitée: /contrat/card.php
Referer: https://dolibarr.dev.ogest.fr/contrat/card.php?action=editref&id=1
Gestionnaire de menu: eldy_menu.php

Message: Contract not found

Warning: trim() expects parameter 1 to be string, array given in /var/www/dolibarr/htdocs/contrat/class/contrat.class.php on line 1150.

**Comment by rdoursenaud** [comment]
Reproduced with numbering module Olive.

**Comment by rdoursenaud** [comment]
Ping @FHenry, you're the Olive module author ;)
