### ISSUE TITLE
Migrate all Perl scripts to PHP

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3366]
Because just a few people of the project know Perl, I think it would be much better if we migrate them to PHP

**Comment by rdoursenaud** [comment]
Perl's not that hard but I guess having everything under the same hood could help collaboration.

**Comment by rdoursenaud** [comment]
Here's a handy list of current perl scripts:
- [ ] ./build/makepack-dolibarrmodule.pl
- [ ] ./build/makepack-dolibarr.pl
- [ ] ./build/makepack-dolibarrtheme.pl
- [ ] ./build/doxygen/dolibarr-doxygen-build.pl
- [ ] ./build/doxygen/dolibarr-doxygen-filter.pl
- [ ] ./build/doxygen/dolibarr-doxygen-getversion.pl
- [ ] ~~./build/perl/virtualmin/dolibarr.pl~~
- [ ] ./dev/initdata/dolibarr-mysql2pgsql.pl

**Comment by eldy** [comment]
Script  ./build/perl/virtualmin/dolibarr.pl  must stay in perl. It is designed for virtualmin that is a perl tool.
Ok for others.

**Comment by marcosgdf** [comment]
It would be interesting to use Symfony/Console component to group all scripts.

**Comment by rdoursenaud** [comment]
@eldy Yes, and looks totally unmaintained (from current develop, post 3.8.0 release):

``` perl
# script_dolibarr_versions()
sub script_dolibarr_versions
{
return ( "3.7.2", "3.6.3", "3.5.6" );
}
```

**Comment by marcosgdf** [comment]
I've got a working port of makepack-dolibarrmodule.pl but there are some features that are not used/not useful: like compress all modules (this script is for publishing to dolistore so it doesn't make sense).

What do you think about removing it?

**Comment by rdoursenaud** [comment]
I certainly have nothing against it. Where can we find your port?

**Comment by marcosgdf** [comment]
You can find it here https://github.com/marcosgdf/dolibarr/tree/fr-3366 and the code is in https://github.com/marcosgdf/dolibarr/blob/873477d375e774719eb892204b3a4f9b3ed37cff/build/Command/BuildModuleCommand.php, to test it:
1. Execute `composer.phar install`
2. `chmod +x build/console.php`
3. `./build/console.php build:module` and follow the wizard

(I assume you don't need that much info but if anybody else wants to check it)

It is a little bit more powerful than the makepack-dolibarrmodule.pl because it doesn't require the module descriptor (as it doesn't supply relevant information). It uses symfony/console component because I think it would be interesting to merge all Dolibarr scripts and access them from one single file (build/console.php). It also supports verbose mode to show debug messages.

**Comment by rdoursenaud** [comment]
Great work! Thanks for sharing.
I'll have a look ASAP.

**Comment by eldy** [comment]
@marcosgdf 
What do you mean with "compress all modules" ? Do you mean removing the option "all".
It is a feature I use a lot but may be i am alone, so i can add the feature myself if necessary.

Also, If it does no require the file descriptor, how can we exclude some files we don't want into the zip ? This is need to be sure to have only required files into zip and not some tests or data files also in the git.
Same question for the module descriptor to find the version of module automatically ?

**Comment by marcosgdf** [comment]
@eldy yeah. That is what I meant. To me it doesn't make much sense because
all the modules are not going to be published in Dolistore. Also, it looks
more like a function that is appropriate for the dolibar-makepack.pl
script. If you can tell us under which circumstances is this useful we can
understand it better.

**Comment by eldy** [comment]
When a new dolibarr version is released, i run the makepack-dolibarrmodules.pl with option all so i build all dolistore modules in one script compatible with the new dolibarr version. This save me a lot of time and is a guarante i don't forget any module to be packaged and updated. But don't worry about this, it is just a loop.
What about way to find version automatically and to exclude files from package ?
