### ISSUE TITLE
Price function does not round properly

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3367]
Version: 3.7

When having the number "0,0099999999999909" instead of rounding to "0.01" it shows "0.0099999999999909".

This is not the expected behaviour.

**Comment by marcosgdf** [comment]
I also noticed that the funcion does some operations that seem to reimplement the rounding function. Why is that?

**Comment by eldy** [comment]
Goal of price function is more enhanced than a simple round. It is desinged to get this if no second parameter is provided:
0,009999999999990 -> 0,00999999999999     (no accurancy provided, so no rounding done, only last zero is removed)
0,0099999999999909 -> 0,0099999999999909   (no accurancy provided, so no rounding done)

if a second parameter is provided, then a rounding is also done
0,0099999999999900 -> 0.01   if parameter is 2 or 'MT'  (MT means rounding for total amount)

So everything is ok for me, I close the issue.
