### ISSUE TITLE
Most dates not shown with postgresql

### ISSUE THREAD

**Issue by tomours** [Dolibarr/dolibarr#3372]
Hello,
I've a problem with most dates in the application : they are either not shown or show 01/01/1970.
I've seen this problem in contracts, expenses, contacts...

Here is for instance what I see for expenses :
My db :
![bug dates](https://cloud.githubusercontent.com/assets/4772473/9169082/5ddcc4b2-3f5a-11e5-8e62-73af22eec772.png)
Expenses list :
![frais](https://cloud.githubusercontent.com/assets/4772473/9169340/34d90c8c-3f5b-11e5-8902-d3da8163bb5e.png)
Expense detail :
![frais detail](https://cloud.githubusercontent.com/assets/4772473/9169454/9a4413dc-3f5b-11e5-8be2-dae2db0f25a2.png)

For what I've understood, it looks like the db jdate function expects a date with YYYY-MM-DD HH:MM:SS format, which causes a problem with my db returning a DD/MM/YYYY format.

I don't know what would be the best fix : force "datestyle" when conecting to db ? or when creating db (during install) ? or modify date functions to take into account different date formats ?

**Comment by marcosgdf** [comment]
Version? It does work fine here.
