### ISSUE TITLE
Bug: Untranslated text in Contacts > Note tab

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3384]
Version: 3.7.1

Key: DateToBirth

![captura de pantalla 2015-08-13 a las 21 14 44](https://cloud.githubusercontent.com/assets/168744/9259299/920be134-4200-11e5-95b9-3ba79715a702.png)

**Comment by simnandez** [comment]
Works into branch 3.7 (future 3.7.2)
