### ISSUE TITLE
date and duration unknown PDF contract

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#3397]
Hello to all.

Suspected bug in 3.7.1

I created a computer maintenance contract service.
Duration 1 month
A price XX (per month so if I understand correctly)

When the PDF is generated from the contract record, it put me in the body of the PDF:

Date: Unknown - Duration: Unknown

Translation french : Date : Inconnu - Durée : Inconnu

I knowledgeable concerning the start and end date when I entered my line contract with the service.
and the contract line, I see the start and end dates indicated when I validate the line.

I reproduced what seems a bug successfully on the demo site.

here is the link to the PDF:

http://demo.dolibarr.org/document.php?modulepart=contract&file=%28PROV388%29%2F%28PROV388%29.pdf

**Comment by eldy** [comment]
Fixed into dev branch

**Comment by ghost** [comment]
Thanks. A link for diff ?

**Comment by ghost** [comment]
because I can not find the link for me to see the code change has resolved the error in Git

**Comment by ghost** [comment]
or, what are the changes to make the 3.7.1 version?

**Comment by rdoursenaud** [comment]
@bazzanellat I believe it's in 4541d189acadffcd9808b3422558d4006633278d
