### ISSUE TITLE
Bug All module

### ISSUE THREAD

**Issue by karouani** [Dolibarr/dolibarr#3401]
Bonjour,

Bonjour,
Suite à une bug grave dans les modules (Tiers , Factures..) concernant la duplication de l’opération suite à multiple clic successive sur le bouton envoyer , le problème relie à l'utilisation de système de transaction .
Pourquoi pas ajouter une alerte dialog,comme sa sans avoir une confirmationl'operation inserte jamais s'executé.

![capture d ecran 25](https://cloud.githubusercontent.com/assets/4655630/9361850/4cb12bfa-4695-11e5-9fb7-3a33318cbcc4.png)
![capture d ecran 24](https://cloud.githubusercontent.com/assets/4655630/9361851/4cb4ab04-4695-11e5-8be1-9c1ad5f53aa0.png)

**Comment by eldy** [comment]
Can you describe better the way to reproduce your bug. I am not affected by the thing you describe.

**Comment by karouani** [comment]
Hello,


I don't know if that's problem is just detected by me or you have other
person , so the movie attached in the link below explain more my problem.

https://www.youtube.com/watch?v=uGrnMjL6rvg



N.B : Sorry for my bad english

**Comment by FHenry** [comment]
Upgrade your dolibarr version.... you play with 3.5.2, upgrade to 3.8

**Comment by karouani** [comment]
that's what I want, but i have a difficult i can upgrade version 3.5 to 3.6
but 3.6 to 3.7 i have a problemes discubed in the youtube video.
Where i past all files of 3.7.X, i don't know why the button of upgrade has
not visible , jut the new install

Cordialement




2015-12-04 9:13 GMT+00:00 HENRY Florian <notifications@github.com>:
