### ISSUE TITLE
Optioncss value is not respected when changing filters in the list of customer orders

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3410]
Version: 3.5.6

If I press the print button and then I change the order of a column in the list of customer orders, then the full page is loaded again (instead of loading the print page)

**Comment by rdoursenaud** [comment]
Support of 3.5.x versions has ended. Are following versions also affected?

**Comment by marcosgdf** [comment]
Yep. This is happening also in latest 3.7 and in almost every page that lists objects with filters.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/3658

**Comment by rdoursenaud** [comment]
Thanks @frederic34 but this has been merged to develop. The fix needs to be backported to 3.7 ;)

**Comment by marcosgdf** [comment]
Closing as no intention to backport to 3.7 anymore
