### ISSUE TITLE
Sending several mails w/ attachments at the same time

### ISSUE THREAD

**Issue by atm-aurelien** [Dolibarr/dolibarr#3436]
Hello,

Attachments in mails are managed by session variables. However, If we open several tabs to send several mails (with several mail form opened at the same time), the last opened tab will erase session variables with its attachments datas.

I suggest to add 3 hidden inputs into mail form, containing file name, file path and file mime, for each attachment. Then to retrieve these informations on form submit (via $_POST). 

Anyway, if these post informations are not present, session variables are still used.

**Comment by eldy** [comment]
Saving data with post will need to propagate datas all the time for every form email action. This is a pb because this form will support more and more ajax action.
I suggest another fix : add a prefix into post and only one prefix. Then we saved into session values but with the prefix into names.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by webrdinfo** [comment]
Hello,

I introduce myself, Julien Mutzenhardt, I allow myself to reopen this ticket, because I just had this bug on our version of dolibarr:

php 5.6
Dolibarr 9.0.3

Regards,
Julien Mutzenhardt

**Comment by atm-maxime** [comment]
Please open a new issue mentioning this one and give us the details of your issue, screenshots. You can't reopen another one's issue.
