### ISSUE TITLE
Error when adding or removing permission

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3444]
This seem to be tied to the thirdparty module and triggered from commonobject.class.php.
I've been unable to reproduce on 3.8 nor develop despite the fact that I can't pinpoint what changed.

```
DoliDBMysqli::query SQL Error message: DB_ERROR_NOSUCHFIELD Unknown column 'te.fk_soc' in 'where clause'
```

or

```
DoliDBMysqli::query SQL error: SELECT MAX(te.rowid) FROM llx_user as te, llx_societe as s LEFT JOIN llx_societe_commerciaux as sc ON s.rowid = sc.fk_soc WHERE te.rowid
 < '1' AND sc.fk_user = 1 AND te.fk_soc = s.rowid AND te.entity IN (0,1) DB_ERROR_NOSUCHFIELD
```

**Comment by eldy** [comment]
Into 3.8, all fields fk_societe were renamed into fk_soc to match other.
That's why the generic code now works correctly with 3.8+.
