### ISSUE TITLE
Email templates that can be combined

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#3452]
now the email template types are hardcoded - new types are not easy to include or selectable.
with a table we can also create private or public textmodules to paste it like the signatur on a position in a new mail.

my wish is to create a table 
![email-template_types](https://cloud.githubusercontent.com/assets/3923753/9629739/4571d480-5175-11e5-8b99-c1ce0ec0397f.PNG)

next step is to create the manager to setup -> email 
in a new tab with label email-templates

![email-template](https://cloud.githubusercontent.com/assets/3923753/9629766/6f2f543c-5175-11e5-9c55-2c181ab0775b.PNG)

like this:
![email-template2](https://cloud.githubusercontent.com/assets/3923753/9629773/7f8dddee-5175-11e5-8888-f0ada4dbdf34.PNG)

the code is finish. If that is ok i will add it in a pull request.

**Comment by marcosgdf** [comment]
We already have that in 3.7

**Comment by eldy** [comment]
With 3.8, you can edit email templates from dictionaries area.
We may introduce a hook so external modules coule be able to complete the list of email template types.

**Comment by gschratzer** [comment]
The goal would be to introduce a template system that make selectively available email templates without losing the sight of the standard types.

Then we make a template editor, Where templates can be set to private and public, as they can also be switched to active and Inactive and the order can be placed. 
On this screen you see it's not really different to your version 3.8 in dictionary area.

![email_temp](https://cloud.githubusercontent.com/assets/3923753/9718894/dd04acf6-557f-11e5-969d-07a38fec1052.PNG)

Look on our video-example. If you integrate it in our style you can also integrate the function of email templates it is possible to integrate email module blocks. that's the step to integrate public text modules to write mails easy in corporate identity!

![email_temp_select](https://cloud.githubusercontent.com/assets/3923753/9718703/70e97890-557e-11e5-917f-eb241d3d9684.gif)

**Comment by ghost** [comment]
@gschratzer  Does or would this work for standard emailings and mass email?

**Comment by gschratzer** [comment]
Sorry i can't understand your question. In this topic we are discussing about email templates.
Yes it is possible to use the email templates it in all email functions, and no it is currently not included in the  dolibarr core system. But we discuss it here for future.
