### ISSUE TITLE
Rounding issue when dispatching non-integer qty caused by SQL.

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#3471]
Version 3.5+

Calculation of already dispatched qty is not rounded properly.

![erreur reception](https://cloud.githubusercontent.com/assets/4573808/9699148/0a4c0564-53d8-11e5-9e6d-5591949d5faa.jpg)

Caused by mysql sum function.
Can I use round(sum(a_float_value), 2) to fix this, or is this against SQL guidelines.

**Comment by eldy** [comment]
Can t you keep only the sum(floatvalue) into sql and then, once data is into a php var, do
$thevar = price2num($thevar, 'MT')

**Comment by eldy** [comment]
Rounding should never be done by sql but by php using the price2num function and parameter 'MT', 'MU' or a numeric with number of digits (even if it s not a price, function is an advanced rounding function). We never decided what is the highest number of decimal possible for qty. You can use 5 as parameter for price2num. So keep only the sum(floatvalue) into sql and then, once data is into a php var, do
$thevar = price2num($thevar, 5)
