### ISSUE TITLE
Wrong error message when not filling an extrafield of a supplier invoice

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3490]
Version: 3.7.2.

If we create a mandatory extrafield for supplier invoices and then do not fill it when creating one, an incorrect error message is shown.

"No se indicaron algunos campos obligatorios : Tipo
ErrorBadValueForParamNotAString"

**Comment by rdoursenaud** [comment]
Sounds like we'll have to change the order of the tests:
- required first
- then type matching
