### ISSUE TITLE
Columns in German PDF files not with correct width

### ISSUE THREAD

**Issue by low5** [Dolibarr/dolibarr#3492]
The columns in the German PDF generated files are not correct. This is due to the translation of discount. As this is the typical translation for discount and an abrrivation is not common the column size needs to be adapted. This is for all PDF generated documents. Issue is in 3.7.1 as well as in 3.8 beta

![image](https://cloud.githubusercontent.com/assets/14179741/9735118/b0b50f6a-5638-11e5-8947-9e4b15689586.png)

**Comment by rdoursenaud** [comment]
Unfortunately this is a widespread issue with our PDF generation code. Width are hardcoded and changing them is not trivial. I just opened a broader issue to try and get a long-term solution to this problem.
In the meantime, you'll have to tweak the dimensions in the code (complex) or settle to use an abbreviation even if not widespread in your country (simple).

**Comment by gschratzer** [comment]
In lang file from "de_DE" this word is changed from "Ermäßigung" to "Rabatt" since current version. Now it should work in the facture.

![facture1](https://cloud.githubusercontent.com/assets/3923753/9789111/4d25f350-57ce-11e5-9e65-4319a0d46123.PNG)

**Comment by eldy** [comment]
@gschratzer Do you mean it is fixed in current version ? Do you mean 3.7.1 or 3.8 ?
Does this means we can close the bug ?

**Comment by low5** [comment]
From my opinion you can close it. For 3.7.1 and 3.8

**Comment by gschratzer** [comment]
it is fixed with new translation (transflex - de_DE) which is used on installation 3.8.0.
In 3.7.1 the discount already is translated with "Ermässigung". This word is to large for the PDF row discount.

you can close it.
