### ISSUE TITLE
[Boxes] if info_box_contents[]['text'] equals to "0", then nothing is printed on the screen

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3502]
Version: 3.7.1

Setting info_box_contents[]['text'] to 0, causes nothing to be printed.

**Comment by rdoursenaud** [comment]
Welcome to PHP :sweat_smile:

**Comment by marcosgdf** [comment]
😂

**Comment by eldy** [comment]
Seems to be ok into 3.8.

I did
$this->info_box_contents[$line][] = array(
                        'text' => 0
);
And I see 0.

Can you confirm it's ok for your case on 3.8 ?

**Comment by marcosgdf** [comment]
It is working OK in 3.8

**Comment by eldy** [comment]
Fixed into 3.8, that will be released this week-end, so i close ticket.
