### ISSUE TITLE
[Question] - Is it possible to export to a Belgian accounting

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#3507]
Hello,
Is it possible to export Doliarr data in a document required by a Belgian accounting ?
So by category get a value in an Excel document.

Kind regards
Laurent

**Comment by aspangaro** [comment]
Hello,

Maybe, have you a list of data needed by a belgian accounting ?

Best regards
Alex

**Comment by laudeco** [comment]
Hello,
Not specially, we have to group our amount by post (category) something like this : 
![image](https://cloud.githubusercontent.com/assets/3658458/9898747/25986f94-5c55-11e5-92ab-af3c746cf256.png)

It could be in a CSV

L.

**Comment by openthink-laurent** [comment]
Dolibarr is not an accounting software and cannot generate such an income statement, but you can export your sales and purchase journals to an accounting software. Take a look at https://www.dolistore.com/fr/modules/250-Export-vers-comptabilit--.html.

**Comment by aspangaro** [comment]
In dolibarr 3.7 & 3.8, you can do the same thing without any external module.

We need to go in feature level 2 and activate the module Accounting Advanced.

**Comment by laudeco** [comment]
Thanks for your replies ! 
I'll analyse that 
Thanks
Laurent
