### ISSUE TITLE
Useless tooltip in 3.8 boxes

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3508]
In 3.8, a useless tooltip with the text "Show" is shown in links of boxes of external modules:

![captura de pantalla 2015-09-12 a las 12 44 18](https://cloud.githubusercontent.com/assets/168744/9831170/027866ec-594c-11e5-8f6f-e2bf3cede187.png)

Code used:

```
$tmp = array();

$tmp[] = array('td' => 'align="left"',
    'text' => --::----($---, 4));
$tmp[] = array('td' => 'align="right"',
    'text' => $----,
    'url' => dol_buildpath('/----', 2));

$this->info_box_contents[] = $tmp;
```

**Comment by eldy** [comment]
Are you sure this is not a bug into the external module (in the way the box is coded) ?

**Comment by marcosgdf** [comment]
It appeared in 3.8. In 3.7 there was no tooltip... I'll take a look at the
code but to me looks like a bug...

**Comment by marcosgdf** [comment]
Bug is caused by commit 925aa2039bb8a7445e0573427a4ba31d34af6ebd. When a 'url' param is set, then the text "Show" is automatically added to the title tag, causing an useless tooltip to show. See line 290 of dolibarr/htdocs/core/boxes/modules_boxes.php
