### ISSUE TITLE
Add a numbering module for payments

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#3509]
So payment will have ref = "PAYYYMM00001" instead of 1, 2, 3...
- [x] Payment ref for customers
- [ ] Payment ref for suppliers

**Comment by aspangaro** [comment]
High priority ?

**Comment by eldy** [comment]
@aspangaro Yes high priority. 
Missing this make not possible to mutualize a lot of code and we need to reduce/mutualize code if we don't want to loose control of it.

**Comment by wilsukina** [comment]
hi i wanna save it in pdf, can u help me?
