### ISSUE TITLE
Create user with LDAP

### ISSUE THREAD

**Issue by all3kcis** [Dolibarr/dolibarr#3524]
Fresh install 3.8
After choice the user and put the get button
The button "Create user" is no longer displayed

Pressing the enter button you get to validate the form, but the error "Duplicate entry '' for key 'uk_user_api_key'" appears.

Effectively in bdd the first user as empty uk_user_api_key.

**Comment by rdoursenaud** [comment]
Looks related to @jfefe work on the REST webservice.

**Comment by eldy** [comment]
Try to change line 1194 of user.class.php

Move
$sql.= ", api_key = '".$this->db->escape($this->api_key."'";
into
$sql.= ", api_key = ".($this->api_key ? "'".$this->db->escape($this->api_key)."'" : "null");
