### ISSUE TITLE
Timout/list too large when retrieving contacts in user card modification

### ISSUE THREAD

**Issue by Dartaban** [Dolibarr/dolibarr#3528]
By going on the card of an internal user (/htdocs/user/card.php?id=xx) - action "Change" - and opening the menu "Type" ("Internal" by default), this list all the Contacts/Third Parties of the database.

This can become very heavy when there are thousands of Contacts/Third Parties in the database. We met "error 500" with 12,000 contacts.

The problem is the same in the Calendar module when i want to modify the Sheet Event -> List "Task about Company / Contact".

Does an adaptation of the lists with "autocompletion" or anything else in order to settle this problem could be envisaged ?
Thanks

**Comment by rdoursenaud** [comment]
Even if we have a vibrant french community, the bugtracker is english spoken only.
Could you please edit your issue in english. Thanks.

**Comment by Dartaban** [comment]
By going on the card of an internal user (/htdocs/user/card.php?id=xx) - action "Change" - and opening the menu "Type" ("Internal" by default), this list all the Contacts/Third Parties of the database.

This can become very heavy when there are thousands of Contacts/Third Parties in the database. We met "error 500" with 12,000 contacts.

The problem is the same in the Calendar module when i want to modify the Sheet Event -> List "Task about Company / Contact".

Does an adaptation of the lists with "autocompletion" or anything else in order to settle this problem could be envisaged ?
Thanks

**Comment by eldy** [comment]
12000 contacts should not be a problem.
It is just one request that should last few milliseconds and return a page
of 200 Ko.

Which browser and version do you use ?
Which version of Dolibarr ?

2015-09-16 22:16 GMT+02:00 Dartaban notifications@github.com:

> By going on the card of an internal user (/htdocs/user/card.php?id=xx) -
> action "Change" - and opening the menu "Type" ("Internal" by default), this
> list all the Contacts/Third Parties of the database.
> 
> This can become very heavy when there are thousands of Contacts/Third
> Parties in the database. We met "error 500" with 12,000 contacts.
> 
> The problem is the same in the Calendar module when i want to modify the
> Sheet Event -> List "Task about Company / Contact".
> 
> Does an adaptation of the lists with "autocompletion" or anything else in
> order to settle this problem could be envisaged ?
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/issues/3528#issuecomment-140873752.

## 

EMail: eldy@destailleur.fr

## Web: http://www.destailleur.fr

Google+: https://plus.google.com/+LaurentDestailleur/
Facebook: https://www.facebook.com/Destailleur.Laurent

## Twitter: http://www.twitter.com/eldy10
- Dolibarr (Project leader): http://www.dolibarr.org (make a donation for
  Dolibarr project via Paypal: contact@destailleur.fr)
- AWStats (Author) : http://awstats.sourceforge.net (make a donation for
  AWStats project via Paypal: contact@destailleur.fr)
- AWBot (Author) : http://awbot.sourceforge.net
- CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by Dartaban** [comment]
I'm using FireFox 40.0.3
We have two similars Dolibarr 3.7.1. installed on two servers.
With the first one when i save the "/htdocs/user/card.php?id=6&action=edit" in html" file it is 11 M°
And i have a js alerte (see doc attached).
The second one is behind a proxy. This is where we have the 500 Error. We change the "SecResponseBodyLimit" from 685000 to 2M to solve the problem.
GD
![capture d ecran 2015-09-17 a 21 25 49](https://cloud.githubusercontent.com/assets/12734307/9944043/3568b8ee-5d85-11e5-8f29-823edd81f441.png)

**Comment by eldy** [comment]
Pb analyzed.
WIP by @atm-florian

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
