### ISSUE TITLE
Bug: Version 3.8 -> Fatal Error on Class Categorie ( html.form.class.php)

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#3529]
see third party -> Supplier Page see following error on new version 3.8

![bug_categ_supplier](https://cloud.githubusercontent.com/assets/3923753/9898654/5700a1d8-5c54-11e5-8806-81c0c3d179fa.PNG)

**Comment by rdoursenaud** [comment]
Do you have this on your own install ? The demo has not yet been upgraded to the stable release and I can't reproduce it.

**Comment by gschratzer** [comment]
yes, i have the same result on my new version 3.8 installations

**Comment by eldy** [comment]
Did the module category enabled or not ?

**Comment by gschratzer** [comment]
yes the module category is enabled 

it could be the same error from issue 3531. 

![fourn_cat](https://cloud.githubusercontent.com/assets/3923753/9915805/52076ba2-5cb9-11e5-9bf7-a661a1f6e863.PNG)

**Comment by gschratzer** [comment]
now i have the next error

Warning: include_once(/var/www/html/portal/htdocs/categories/class.categorie.class.php): failed to open stream: No such file or directory in /var/www/html/portal/htdocs/core/class/html.form.class.php on line 4678 Warning: include_once(): Failed opening '/var/www/html/portal/htdocs/categories/class.categorie.class.php' for inclusion (include_path='/var/www/html/portal/htdocs/htdocs') in /var/www/html/portal/htdocs/core/class/html.form.class.php on line 4678 Fatal error: Class 'Categorie' not found in /var/www/html/portal/htdocs/core/class/html.form.class.php on line 4680

path error 
i think class.categorie.class.php is false
it should be class/categorie.class.php
