### ISSUE TITLE
Bug: Version 3.8 societe/soc.php Translation Categories

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#3533]
@rdoursenaud 

you changed from language tag "Categories" to "SuppliersCategoriesShort". This you find only in categories.lang and that is not included in /societe/soc.php

![soc php_translation](https://cloud.githubusercontent.com/assets/3923753/9899950/784e33d8-5c5d-11e5-9500-853ad2136eed.PNG)

that is the reason that it is not translated

![soc php_translation2](https://cloud.githubusercontent.com/assets/3923753/9899986/cd4b1cf2-5c5d-11e5-8127-f9a957043017.PNG)

include the categories.lang or change it back to "Categories"

**Comment by rdoursenaud** [comment]
@gschratzer Sorry for that. Fix PR'd.
