### ISSUE TITLE
FIX Bypass authentication when user was created using LDAP

### ISSUE THREAD

**Issue by all3kcis** [Dolibarr/dolibarr#3541]
Clean install 3.8

With LDAP set up but not used for authentication.
If a new user is created from LDAP data the field pass_crypted and pass in the database will be "null"
The user can connect to this account without password.

Proposed solution:
File: core/login/functions_dolibarr.php
Line 94: ($passtyped === $passclear))

**Comment by all3kcis** [comment]
more: this bug was already there on 3.6 version

**Comment by eldy** [comment]
If you do line 94
&& ($passclear && ($passtyped == $passclear)))
does it solve too ?
