### ISSUE TITLE
Feature Request: Implement Content-Security-Policy

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3545]
Content security policy allows to completely eliminate XSS by only allowing to load content from trusted resources.

For more informations, please see:
- 1.1 Specification: http://www.w3.org/TR/2014/WD-CSP11-20140211/
- Nice introduction: http://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by rdoursenaud** [comment]
If you want to help and/or test, prototype implementation is at https://github.com/GPCsolutions/dolibarr/tree/content-security-policy

**Comment by eldy** [comment]
Let's test hidden option MAIN_HTTP_CONTENT_SECURITY_POLICY introduced into 6.0
