### ISSUE TITLE
Bug: orderline drag drop not working when touch-events enabled in chrome and firefox.

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#3551]
~~Orderline drag drop does not work on Chrome 45. Firefox 40 and IE 11 are OK.~~
Disable drag drop when orderline extrafields are added, they should not be dragable because extrafields don't drag and rang is not stored. http://youtu.be/kgKVMoyIpmY
Is not only a 3.8 issue

**Comment by rdoursenaud** [comment]
Works for me on Chrome 45/Linux. Do you have any error on the Javascript Console (F12)?
Maybe share a screencast with us. (I use Screencastify on Chrome)

**Comment by fappels** [comment]
No errors in console (windows 8.1)
Chrome screencast: http://youtu.be/2a8EUXYweLM. On the screencast you don't see the drag cross, but I do see it in chrome.
Firefox screencast: http://youtu.be/kgKVMoyIpmY
Thanks for the Screencastify tip, works really good.

Seems to be a windows chrome bug, dropbox drag-drop also stopped working. Will change title to put focus on extrafields issue.

**Comment by rdoursenaud** [comment]
From what I see, drag and drop doesn't seem to work quite well in Firefox either. Extrafields are supposed to follow the lines they are attached to.

Needs further investigation.

**Comment by rdoursenaud** [comment]
For the record, here's what we are supposed to see: http://youtu.be/tEgcChMhwpM
(Made with a 3.8.0 straight from git's tag with initdata and Chrome 45/Linux)

**Comment by fappels** [comment]
Dragging solved with chrome and firefox config, see #6493 for settings. Dragging extrafields tested OK.

**Comment by rdoursenaud** [comment]
Hummm. From what I understand, the issue is restricted to touch screen computers. I think this qualifies as a bug. Dolibarr should work as expected in this situation. I'd keep the issue open and investigate the libraries and code used for drag and drop further if I were you.
If only I had a touchscreen enabled computer handy… ;)

**Comment by fappels** [comment]
I will reopen and change title. I'm not a dom events guru, but will check the code. Meanwhile my dropbox drag-drop is working even with touch-events enabled, so dropbox fixed it. Will take my touchscreen laptop with me to the upcoming devcamp. 
Just noticed you can also simulate on a non touch device with chrome, the touch event settings are: automatic, enabled and disabled. Default is automatic (will be enabled when a touch screen is detected). So when you force to enabled you can simulate the issue.

**Comment by fappels** [comment]
There is already an issue reported on the used Jquery [plugin](https://github.com/isocra/TableDnD/issues/67)

**Comment by jpyrat** [comment]
I confirm that drag'n'drop of lines does't work with chrome if the Win 10 PC has a touch screen.

But if I disable touch via chrome://flags/
![image](https://user-images.githubusercontent.com/763100/27682068-85a2cdf8-5cc1-11e7-9c1f-972a840ebb7b.png)
it works again !

**Comment by fappels** [comment]
Made an upstream PR. Let's hope, if not merged, we can take my fork.
