### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3552]
Version: 3.8-beta

Page: http://dolibarr.local/admin/modules.php?mode=common

![captura de pantalla 2015-09-18 a las 12 22 46](https://cloud.githubusercontent.com/assets/168744/9957403/0687c15c-5e00-11e5-94fe-c2969831d4f1.png)

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/3657
