### ISSUE TITLE
[3.8] blockUI requires jQuery v1.2.3 or later!  You are using v1.11.3 !

### ISSUE THREAD

**Issue by MaamuT** [Dolibarr/dolibarr#3554]
Hi all,

I just updated my Dolibarr installation from 3.7.1 to 3.8.

And now, when i want to open the Dolibarr File manager, i see this funny message :

`blockUI requires jQuery v1.2.3 or later!  You are using v1.11.3`

[Edit : add infos :]
It's a clear Dolibarr installation with no additionals plug-ins and no add-ons, from the .tgz archive found here on Github.

No fusion for this upgrade, just deleted old Dolibar 3.7.1 folder and uploaded the new folder 3.8, just copy the old config file : Dolibarr/htdocs/conf/conf.php to the new place.

[Edit :] Why i can't select labels or millestone ?

**Comment by hregis** [comment]
I do not have this message! what browser you use?

**Comment by MaamuT** [comment]
Hi,

Firefox 40.0.03

The same who work with no problem a couple minutes before upgrading Dolibarr… no problem to browse file manager in 3.7.1

I think it's a mistake for the Jquery version, but i dont see where is stored to corect by myself…

Regards,

**Comment by fappels** [comment]
Don't have this message on Firefox, but noticed refresh button doesn't work. Refresh starts but does not end.

**Comment by hregis** [comment]
@MaamuT you use dolideb (debian) version ?
@fappels you can see the fix : https://github.com/Dolibarr/dolibarr/pull/3557

**Comment by MaamuT** [comment]
@hregis no, web version downloaded here in github and uploaded to replace old version (previously totaly deleted).

I work in SSH… wget… tar -xf… cp… but i don't think this affect the software…

Can you show me where is the JQuery directory requested, i test on my side and i come here to show my progress ?

**Comment by hregis** [comment]
@MaamuT 

can you edit the file:
/includes/jquery/plugins/blockUI/jquery.blockUI.js

and tell me if you have this version?
Version 2.70.0-2014.11.23

**Comment by MaamuT** [comment]
Yep :

/*!
- jQuery blockUI plugin
- Version 2.70.0-2014.11.23
- Requires jQuery v1.7 or later

**Comment by hregis** [comment]
when you speak of "file manager", you speak well of integrated dolibarr module? not an external module?

**Comment by MaamuT** [comment]
Yep off course, i speak for the Dolibarr module…

You want an access to the website to see by yourself ?

I can create account for you, with just the permission for the file module ?

In private… bien sûr ! (off course !)

**Comment by rdoursenaud** [comment]
Weird.
This BlockUI bug is supposed to not be in the Dolibarr shipped version. Better check the version of the jquery-ui.js served at http://yourdolibarrinstall.tld/[htdocs]/includes/jquery/plugins/blockUI/jquery.blockUI.js.
Maybe you're still serving files from an older version.

**Comment by rdoursenaud** [comment]
@fappels This sounds like an unrelated bug. Could you please open a separate issue?
Oh. damn. I didn't read the thread carefully. This is already fixed by @hregis. Sorry for the noise.

**Comment by fappels** [comment]
@rdoursenaud Deleted my comment. 
Not going to create new issue, because already fixed. @hregis Can you remove the ref 'you can see the fix :'

**Comment by MaamuT** [comment]
Ok,

Solved !

But why ?

After a couple of hours of investigations, i see a folder /Dolibarr-install/htdocs/documents/facture in my backup folder who are not present in my online installation, i just create it and the bug disapeared…

But i'm not sure that are the better explanation :/

The folder already created by myself are now a different owner and i can't modify…

I can't reproduce the bug by deleting "facture" folder to verify… and i don't want use SSH for this website… except for the last option !

I use SSH for download and untar only, because this required root access, for the rest, i use FTP who are not all the permissions…

**Comment by ppena2000** [comment]
To me he gave me the same problem, but I was solved by restarting the services. (Apache, Dolibarr, mysql. etc.)

Solved!

**Comment by eldy** [comment]
So i close issue. Seems to be fixed by regis.
