### ISSUE TITLE
New request: List of products by ordered/delivered under product statistic module

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#3559]
Dolibarr current version is v3.8

Hi, all! How to enable this function?

Thanks!

**Comment by rdoursenaud** [comment]
Is this a feature request or a question about an existing feature?

**Comment by bgenere** [comment]
For your information I have developed a php page that's provide this basic information i.e products ordered/delivered for a time period and a list of products.
I am happy to share : 

https://github.com/bgenere/vignoble/blob/master/ordersandshipments.php

Let me know if you plan to add it to core module so I will remove it from mine.

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.

**Comment by bgenere** [comment]
I have just installed version 10 and I do not see any statistic screen  giving:
- quantity and total amount of products  ordered 
- quantity and total amount of products  delivered
- between 2 dates
- for a list of products.

This is basically what my ordersandshipments.php code mentioned previously is doing.
I will be happy to integrate this feature in the core product but it needs Product, Orders and Delivery modules to work. So i am not sure where and how this code could be integrated in core product.
