### ISSUE TITLE
Localtax not calculated when creating/updating a supplier's invoice line

### ISSUE THREAD

**Issue by chuot** [Dolibarr/dolibarr#3561]
System setup on v3.8.0, configured for Quebec/Canada taxes system.

When creating a new supplier's invoice line, either adding, or updating, the LT1 isn't being calculated as it should. I tracked it down to supplier/facture/card.php which tries to get the localtax  base upon $_POST['tauxtva'], while core/tpl/objectline_edit.tpl.php uses tva_tx in the input form.

Without going further, I don't know which of tauxtva or tva_tx should be used.

I hope that helps, it was my first issue posted in here.

**Comment by chuot** [comment]
As of version 3.9.3, the bug is still present. The file at htdocs/fourn/facture/card.php should have lines 590 and 591 changed like so:

$localtax1_tx= get_localtax($_POST['**tva_tx**'], 1, $mysoc,$object->thirdparty);
$localtax2_tx= get_localtax($_POST['**tva_tx**'], 2, $mysoc,$object->thirdparty);

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
