### ISSUE TITLE
Impossible to attach project in order

### ISSUE THREAD

**Issue by lesmyrmidons** [Dolibarr/dolibarr#3572]
# Environment
- **Version**: 3.8.0
- **OS**: Linux
- **Web server**: Apache/2.2.22 (Debian)
- **PHP**: apache2handler 5.4.45-0+deb7u1
- **Database**: MySQL or MariaDB 10.0.21-MariaDB-1~wheezy-log
- **URL**: /commande/card.php?id=4
# Report

http://mydomain.com/projet/ajax/projects.php?socid=2&htmlname=projectid&projectid=PJ [HTTP/1.1 404 Not Found 7ms]

**Comment by rdoursenaud** [comment]
@marcosgdf seems you forgot to commit the ajax file with 65d3f7968a758758470faf8c501d2ddb2806c0c8
Can you please have a look?

**Comment by marcosgdf** [comment]
@rdoursenaud you were right. thanks!
