### ISSUE TITLE
Search don't work in customer invoice list

### ISSUE THREAD

**Issue by aspangaro** [Dolibarr/dolibarr#3579]
Version 3.8.0

When you launch a search in customer invoice list, we have no result no matter the search

**Comment by defrance** [comment]
need to change
if ($search_status !='' ) $sql.= " AND f.fk_statut = '".$db->escape($search_status)."'";
by
if ($search_status > 0) $sql.= " AND f.fk_statut = ".$db->escape($search_status);

else we have allways an "AND f.fk_statut = '-1'" on the query

**Comment by eldy** [comment]
Le bug a été corrigé il me semble dans develop.
