### ISSUE TITLE
SQL error during install

### ISSUE THREAD

**Issue by jfefe** [Dolibarr/dolibarr#3581]
During installation of Dolibarr 3.8.1 (freshly cloned) with a new database : 

Création des clés étrangères et des index pour la table llx_c_email_templates.key
Request 271 : ALTER TABLE llx_c_email_templates ADD UNIQUE INDEX uk_c_email_templates(entity, label, lang)  
Erreur SQL DB_ERROR_1072 Key column 'lang' doesn't exist in table

This is not blocking for installation process.

**Comment by eldy** [comment]
Are you sure it was on an empty database ?
The field lang is into table llx_c_email_templates with 3.8

**Comment by marcosgdf** [comment]
Can this issue be closed?

**Comment by simnandez** [comment]
I close this issue, because is not reproducible in maintened versions
