### ISSUE TITLE
Replace deprecated dol_print_graph() by DolGraph objects

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3585]
`dol_print_graph()` is deprecated and should be replaced by `DolGraph` objects.

It's still used in the following files:
- [x]  htdocs/adherents/index.php
- [x] htdocs/comm/propal/index.php
- [x] htdocs/comm/askpricesupplier/index.php
- [x] htdocs/commande/index.php
- [x] htdocs/compta/deplacement/index.php
- [x] htdocs/contrat/index.php
- [x] htdocs/fichinter/index.php
- [x] htdocs/fourn/commande/index.php
- [x] htdocs/product/index.php
- [x] htdocs/projet/index.php
- [x] htdocs/don/index.php
- [x] htdocs/societe/index.php
- [x] htdocs/expensereport/index.php

**Comment by bsene** [comment]
Hello,
I'm new to the project, I fixed it [here](https://github.com/Dolibarr/dolibarr/pull/7447)
