### ISSUE TITLE
expenses VAT not in purchases journal

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#3601]
VAT registered in expenses are not displayed in purchases journal

La TVA des notes de frais n'apparait pas dans le journal d'achats

**Comment by rdoursenaud** [comment]
Same homework as previously…

**Comment by RomainDeschamps** [comment]
Dolibarr 3.8.0.

Bug or missing feature ?

VAT registrered on expenses (HRM > Expenses reports) and unpaid, partially paid or totally paid
are not in the purchase journal (Bank/Cash > Reporting > Purchases Journal)

Using the basic accountancy module (same result using Accounting (advanced))

Purchase journal only displays my supplier invoices of my base.

**Comment by rdoursenaud** [comment]
I don't think they have to. These are mere banking transactions.
What's your take on this @aspangaro ?

**Comment by rdoursenaud** [comment]
Since @aspangaro seems busy, let's ask @jpdoursenaud
Should personnel expenses reimbursement appear in the purchase journal?

**Comment by aspangaro** [comment]
Sorry @rdoursenaud,  don't view this "old" issue. I work on a expense report journal. I want to separate  the purchase journal and the expense report for more clear accountancy.

**Comment by aspangaro** [comment]
@rdoursenaud @patas-monkey Sorry I need some money to create my company. I created an external module available on the Dolistore for this function. Need some sell before integrate this complementary module in the core.

https://www.dolistore.com/fr/modules/579-Journal-comptable-des-notes-de-frais-3-8---3-9.html

**Comment by jpdoursenaud** [comment]
A purchase journal or a spécific journal for travel expenses is useful for deductibility VAT.
However for most companies the VAT deductible of travel and reception expenses are not significant.
In this case use a bank journal is simpler.
