### ISSUE TITLE
VAT per customer : no separation FR/Abroad

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#3602]
Sorting VAT per customer FR/other doesn't work
LE tri des TVA par clients FR et étrangers ne fonctionne pas.

**Comment by BebZ** [comment]
Did you try with the module comptabilité  expert there's a nice way to separate it @darkjeff told me

**Comment by RomainDeschamps** [comment]
Done. not better. In the case below, My VAT num is FR..., a cust is FR... and the other is DE...
![vat fr_abroad](https://cloud.githubusercontent.com/assets/11922840/10096612/47a74748-6373-11e5-9f2f-9fe7e52c9502.png)

**Comment by rdoursenaud** [comment]
I don't understand, is it a bug or a feature request?
Where does the thing occur?
What version is affected?
You better than anyone should know we need details!
Please read the [contributing guidelines](https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md) once again ;)
Thanks.

**Comment by BebZ** [comment]
Yes you should just tell us where this report is available and where it is not working...
I think it is not in comptabilité expert, and i never saw thi new functionnality in core... maybe 3.8?

I use compta expert module; namely : 
/accountingex/customer/index.php?idmenu=5676&mainmenu=accounting&leftmenu=

and on my test server it works, when all qties of products are ventilated in the good accounting account. They even have now made tools to correct in mass the accounts.
I think on Jeffinfo.com you can find all the capabilites of module accounting.

SORRY I DIDNT FOUND THE WAY TO MAKE A SCREENSHOT WITH A QWERTY LENOVO CHROMEBOOK; now my keyboard's is crazy and write capital letters AHAHA

70770000    Ventes mat  20% 
77 676,13   87 014,54   98 040,17  
70712000    Ventes mat CEE  
0,00    0,00    3 654,30  
70710100    Ventes mat 5.50%  
0,00    0,00    180,00
70850000    Ports et frais accessoires  
0,00    0,00    25,98   

OK it

**Comment by RomainDeschamps** [comment]
OK OK ! On se calme. me suis fouetté toute la nuite en guise de repentance !

Bug on 3.8.0.
In Financial > Special expenses > Sales tax > Report by customers > Extra reports in checkbox

the details line says "Based on the two first letters of the VAT number being different from your own company's country code"

One of my customer VAT code is FR XX...X and the other one is DE XX...X

Yet, I have no result line in "National customers report".

I tried selling products and services to my customers.

**Comment by BebZ** [comment]
Hey, It seems it's a bug on 3.8, fuctionnality introduced by @ywarnier 
solution could be in this file ? 
https://github.com/Dolibarr/dolibarr/pull/3112/files

**Comment by BebZ** [comment]
@ywarnier maybe you can review this part ? 
https://github.com/Dolibarr/dolibarr/pull/3112/files#diff-ad8857206d3f59edd4e10a75d81bf8f8R399

**Comment by ywarnier** [comment]
Hi, sorry about the delay. Is this issue still active?

**Comment by BebZ** [comment]
yes it should be still active
VAT Is buggy

**Comment by eldy** [comment]
Seems to be an experimental feature

**Comment by ywarnier** [comment]
We use it pretty much in production for our quarterly reports to VAT in Belgium (you have to deliver a list of customers whom you charged VAT to, and a list of customers whom you charged without VAT), but on an older version of Dolibarr. I've been postponing this over and over again because of lack of time, but as soon as I can make the time I'll look at it. You can remove it if you want. Whenever I look at it I will do it through a proper merge request with a better integration.
This being said, I'd probably need a bit of input on how you do your VAT declarations in France (at least) to make it more useful to more people.

**Comment by eldy** [comment]
A rewrite of VAT reports were done in 8.0
I suppose this PR is obsolete since. If not, reopen the issue.

**Comment by ywarnier** [comment]
Probably. We have a pending update of our system, so I'll come back at some point if that doesn't work for me.
