### ISSUE TITLE
Margins and permissions

### ISSUE THREAD

**Issue by fonkyzeus** [Dolibarr/dolibarr#3606]
# Environment
- **Version**: 3.8.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.3.29
- **Database**: MySQL or MariaDB 5.1.73-2+squeeze+build1+1-log
- **URL**: /341/htdocs/margin/tabs/thirdpartyMargins.php?socid=1
# Report

when I allow an employee to see his clients or view all clients via the client card it accesses its margin, even though I did not authorize it to see the commercial proposal or marging.
I would like employees to work on projects and tasks while connecting them to customers -> it is essential that they can have access to clients to connect to projects or tarsk, but they shouldn't have access to financial data as margins ...

**Comment by rdoursenaud** [comment]
Again, please edit your reports in english. Thanks!

**Comment by fonkyzeus** [comment]
In english :
Environment

Version: 3.8.0
OS: Linux
Web server: Apache
PHP: cgi-fcgi 5.3.29
Database: MySQL or MariaDB 5.1.73-2+squeeze+build1+1-log
URL: /341/htdocs/margin/tabs/thirdpartyMargins.php?socid=1

when I allow an employee to see his clients or view all clients via the client card it accesses its margin, even though I did not authorize it to see the commercial proposal or marging.
I would like employees to work on projects and tasks while connecting them to customers -> it is essential that they can have access to clients to connect to projects or tarsk, but they shouldn't have access to financial data as margins ...

Best regards

Laurent MOUREN

**Comment by fonkyzeus** [comment]
Done !

Best regards

Le 25/09/2015 15:33, Raphaël Doursenaud a écrit :
>
> Again, please edit your reports in english. Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Dolibarr/dolibarr/issues/3606#issuecomment-143224404>.
>

-- 

*ATTENTION CHANGEMENT D'ADRESSE !
*Nouvelle Adresse à compter du 24/01/2014 : Immeuble "Le Verdi", rue 
Joseph Lafond 13400 AUBAGNE
*Tel.**0950 355 432
**Fax. **0955 355 432*

**Comment by BebZ** [comment]
How did you succeed it ? COmment avez-vous fait ? en ajustant les autorisations de l'utilisteur sur le module marge ?

**Comment by fonkyzeus** [comment]
I did not succeed ! It was a respond email to tell you that i did the english translation of the problems. Didn't know that it will automatically be seen in github !

**Comment by fonkyzeus** [comment]
when not allowed to see margin, a user should not have (see in the image capture) this item on the client card (or unable to click).
Best regards

![dolibarr](https://cloud.githubusercontent.com/assets/14835228/10102403/74fbcf54-639e-11e5-863c-e2ef642bcda3.JPG)

**Comment by BebZ** [comment]
I agree, or permissions are useless on the margin module...
maybe ping @altatof that created the module ? or @someone? that created the permission ?

**Comment by altairis-tof** [comment]
it's strange because those tabs (in customer card or product card) should not be visible if not authorized because in the module descriptor, there is : 
$this->tabs = array(
                'product:+margin:Margins:margins:$user->rights->margins->liretous:/margin/tabs/productMargins.php?id=**ID**',
                'thirdparty:+margin:Margins:margins:empty($user->societe_id) && $user->rights->margins->liretous && ($societe->client > 0):/margin/tabs/thirdpartyMargins.php?socid=**ID**'
        );

i dont understand except if permission management system has been changed ?

**Comment by altairis-tof** [comment]
it works well on my 3.7 release; i dont have a 3.8 installed yet !

**Comment by fonkyzeus** [comment]
One direction : when I put off the margin module off and I try to put it on, I've got this error message
"Error Duplicate entry 'all--1-100-/margin/index.php-1' for key 'idx_menu_uk_menu'"

**Comment by fonkyzeus** [comment]
One solution : http://www.dolibarr.fr/forum/12-howto--aide/48136-pb-module-marges-avec-la-3-5
But the tab margin menu won't come back on the top of the "client" page : it will only be visible on the "compatbility" page
