### ISSUE TITLE
NotABug: unable to change commercial proposition status to status charged

### ISSUE THREAD

**Issue by fonkyzeus** [Dolibarr/dolibarr#3622]
![dolibarr proposition](https://cloud.githubusercontent.com/assets/14835228/10161351/cb9886e2-66a3-11e5-9fb0-a47cfcfc537c.JPG)
# Environment
- **Version**: 3.8.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.3.29
- **Database**: MySQL or MariaDB 5.1.73-2+squeeze+build1+1-log
- **URL**: /341/htdocs/comm/propal.php?id=351
# Report

Hi, on a commercial proposition sheet i don't have the button "facturé" (in french or charged in English) to change the status of the proposition. I had it on the 3.7.1
I changed the proposition to "closed to charge" ("cloturée, à facturer") status, i did the invoice linked to this proposition, but not able to change the status to "charged" ("facturé") after : no button to do it

Best regards

**Comment by rdoursenaud** [comment]
This feature now depends on the workflow module.
The proposal will then be set billed as soon as the linked invoice is billed.

You can reenable the old behavior with the [documented hidden setting](http://wiki.dolibarr.org/index.php/Setup_Other#Proposals_module) WORKFLOW_PROPAL_CAN_CLASSIFIED_BILLED_WITHOUT_INVOICES.

**Comment by HugoHeneault** [comment]
I now have a lot of bill charged but still "to charge" (à facturé in french)... How can I put them in "charged" while keeping the new behavior?

**Comment by rdoursenaud** [comment]
The workaround is to enable the hidden setting, classify manually and disable it when done.

**Comment by HugoHeneault** [comment]
That's what I've done. Have to check if this won't happen another time...
