### ISSUE TITLE
Bug: Fatal error: Cannot access private property ActionsAssortment::$error www\dolibarr\htdocs\core\class\hookmanager.class.php on line 182

### ISSUE THREAD

**Issue by smartboy23** [Dolibarr/dolibarr#3623]
# Environment
- **Version**: 3.8.0
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/admin/system/database.php?mainmenu=home&leftmenu=admintools
# Report

**Comment by FHenry** [comment]
Seems to be related to external module Assortment not actually compatible with 3.8.
You should disabled the Assortment ( in french Assortiment) module

**Comment by smartboy23** [comment]
thanks it works.
