### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by willyotto** [Dolibarr/dolibarr#3624]
# Environment
- **Version**: 3.8.0
- **OS**: FreeBSD
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.4.41
- **Database**: MySQL or MariaDB 5.5.43-log
- **URL**: /erp/htdocs/compta/facture.php?facid=75
# Report

Since the installation of V3.8 date notations, number notations are written in an other locale. Using other browser doesn't help. I use NL_Be, dates are shown in american format and thousand separators and comma's are switched! I can't find any topic on the web for helping me out, with these issues I'm no longer able to use the software in a normal way, please help me, all my data is in it!!!

**Comment by ndrosis** [comment]
Go Home-> Setup -> Other setup and add line
Name -> MAIN_OVERWRITE_TRANS_xx_XX
Value -> SeparatorDecimal:.,SeparatorThousand:,

where xx_XX the language you are using

**Comment by willyotto** [comment]
Hi there, thanks for your response, but now it’s even worse!

We use a comma for decimals and if it is necessary a point as thousand separator, so I changed SeparatorDecimal:.,SeparatorThousand:, to SeparatorDecimal:,,SeparatorThousand:.

And now I get xxx.xx instead of xxx,xx :s

Regards,

W. Otto

 http://www.groencreaties.be/ logo

Web:  http://www.groencreaties.be/ http://www.groencreaties.be

Mail :  mailto:willy@groencreaties.be willy@groencreaties.be

Tel.  : 0472 / 655.105

Van: Drosis Nikos [mailto:notifications@github.com] 
Verzonden: dinsdag 29 september 2015 20:35
Aan: Dolibarr/dolibarr
CC: willyotto
Onderwerp: Re: [dolibarr] Bug: (#3624)

Go Home-> Setup -> Other setup and add line
Name -> MAIN_OVERWRITE_TRANS_xx_XX
Value -> SeparatorDecimal:.,SeparatorThousand:,

where xx_XX the language you are using

**Comment by willyotto** [comment]
Hi there, thanks for your response, but now it’s even worse!
We use a comma for decimals and if it is necessary a point as thousand separator, so I changed SeparatorDecimal:.,SeparatorThousand:, to SeparatorDecimal:,,SeparatorThousand:.
And now I get xxx.xx instead of xxx,xx :s

Regards,

W. Otto

**Comment by eldy** [comment]
Try to edit file htdocs/langs/nl_BE/main.lang and change line with 
SeparatorDecimal
SeparatorThousand

**Comment by willyotto** [comment]
This works! Thank you so very much!
