### ISSUE TITLE
Signature in proposal pdf is in English, has to be Dutch

### ISSUE THREAD

**Issue by willyotto** [Dolibarr/dolibarr#3625]
# Environment
- **Version**: 3.8.0
- **OS**: FreeBSD
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.4.41
- **Database**: MySQL or MariaDB 5.5.43-log
- **URL**: /erp/htdocs/comm/propal.php?id=15&action=confirm_validate&confirm=yes
# Report

In versoin 3.8 there is a signature box added with the text "Written acceptance, company stamp, date and
signature". I tried to change this in Propals.lang under en_US, I use nl_BE, but the propal.lang of that directory doens't contain much information, there is a line added that en_US in stead is used? How do I change the text of the signature box?

Kind regards,
Otto W.

**Comment by rdoursenaud** [comment]
This is most likely due to having no dutch translation available for that specific string.
Dolibarr translations are managed at [Transifex](https://www.transifex.com/dolibarr-association/dolibarr/) and you are very welcome to join and help making Dolibarr better in your language :)

**Comment by willyotto** [comment]
I'd love to, but how do i solve this on this very moment?  :)
It can't be that I send proposals in our language andere then suddenly english at the bottom of the page, its a bit messy, don't you think? :)

Regards, W.Otto

-------- Origineel bericht --------
Van:Raphaël Doursenaud notifications@github.com
Verzonden:Wed, 30 Sep 2015 16:32:10 +0200
Aan:Dolibarr/dolibarr dolibarr@noreply.github.com
Cc:willyotto willy@groencreaties.be
Onderwerp:Re: [dolibarr] Bug: Signature in proposal pdf is in English, has to be Dutch (#3625)

**Comment by willyotto** [comment]
Dear Raphaël,

I’ve found it, I figured out that it is possible to add a line yourself in the propals.lang file. 

So I added: ProposalCustomerSignature=Stempel, Datum en handtekening met vermelding "Voor Akkoord"

This is the correct translation and suitable to put on a proposal in nl_BE

Regards,

W.Otto

Van: Raphaël Doursenaud [mailto:notifications@github.com] 
Verzonden: woensdag 30 september 2015 16:32
Aan: Dolibarr/dolibarr
CC: willyotto
Onderwerp: Re: [dolibarr] Bug: Signature in proposal pdf is in English, has to be Dutch (#3625)

This is most likely due to having no dutch translation available for that specific string.
Dolibarr translations are managed at Transifex https://www.transifex.com/dolibarr-association/dolibarr/  and you are very welcome to join and help making Dolibarr better in your language :)

**Comment by ndrosis** [comment]
Hi the Proposals.lang nl_BE is empty?

**Comment by rdoursenaud** [comment]
Great!
I was about to point you to the right translation token.
Please take the time to contribute it at Transifex so you won't need to do it at every upgrade and everyone speaking your language can benefit from it.
Looking forward to your contribution.
Thanks.

**Comment by rdoursenaud** [comment]
@ndrosis This is to be expected since the main translation is in nl_NL and only differences are to be added to sublanguages like nl_BE.

@willyotto I forgot to add that our translator documentation is at https://wiki.dolibarr.org/index.php/Translator_documentation

**Comment by willyotto** [comment]
Hi,

Not completely, it doesn’t contain the number of lines like the fr_FR file does for example.

 http://www.groencreaties.be/ logo

Web:  http://www.groencreaties.be/ http://www.groencreaties.be

Mail :  mailto:willy@groencreaties.be willy@groencreaties.be

Tel.  : 0472 / 655.105

Van: Drosis Nikos [mailto:notifications@github.com] 
Verzonden: woensdag 30 september 2015 18:57
Aan: Dolibarr/dolibarr
CC: willyotto
Onderwerp: Re: [dolibarr] Signature in proposal pdf is in English, has to be Dutch (#3625)

Hi the Proposals.lang nl_BE is empty?

**Comment by ndrosis** [comment]
@rdoursenaud  :+1: 

@willyotto  Go to Transifex project dolibarr team your language. More at the link that gave you the @rdoursenaud

**Comment by willyotto** [comment]
How can I add translations? I have to be member of the right language team or something? I’m subscribed by the way.

Van: Raphaël Doursenaud [mailto:notifications@github.com] 
Verzonden: woensdag 30 september 2015 18:57
Aan: Dolibarr/dolibarr
CC: willyotto
Onderwerp: Re: [dolibarr] Signature in proposal pdf is in English, has to be Dutch (#3625)

Great!
I was about to point you to the right translation token.
Please take the time to contribute it at Transifex so you won't need to do it at every upgrade and everyone speaking your language can benefit from it.
Looking forward to your contribution.
Thanks.

**Comment by willyotto** [comment]
Ok, I joined the team I think J

As soon as I’ll be accepted, I will add some translations.

 http://www.groencreaties.be/ logo

Web:  http://www.groencreaties.be/ http://www.groencreaties.be

Mail :  mailto:willy@groencreaties.be willy@groencreaties.be

Tel.  : 0472 / 655.105

Van: Drosis Nikos [mailto:notifications@github.com] 
Verzonden: woensdag 30 september 2015 19:07
Aan: Dolibarr/dolibarr
CC: willyotto
Onderwerp: Re: [dolibarr] Signature in proposal pdf is in English, has to be Dutch (#3625)

@rdoursenaud https://github.com/rdoursenaud   :+1: https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png 

@willyotto https://github.com/willyotto  Go to Transifex project dolibarr team your language. More at the link that gave you the @rdoursenaud https://github.com/rdoursenaud

**Comment by rdoursenaud** [comment]
@willyotto Yes, you need to join or request a language team and be accepted by a project manager. Please refer to the [Transifex help](http://docs.transifex.com/introduction/translators/) for the exact process. Requests for joining are generally handled quickly.

**Comment by rdoursenaud** [comment]
Just edited the (english version of the) wiki to try and make the process description more streamlined and accurate. Please let me know if this is not enough ;)

**Comment by fappels** [comment]
I'm also nl_BE speaking, but I'm an nl_NL translator (and user) because nl_BE is only recently added to transifex. Didn't know nl_BE was available. Just had a look at nl_BE in transifex and noticed that nl_BE is the same as nl_NL with the difference that the unstranslated are in en_EN and review is 0%. So nl_BE - nl_NL diffs are gone, but new translations will be synced to nl_BE in github (noticed from 3.8 the nl_BE folder only contains new syncs). You should translate "Written acceptance, company stamp, date and
signature" in nl_NL because it can be translated in 'common' dutch readable by dutch and flamish speaking.  To be continued...

**Comment by willyotto** [comment]
Are you sure that nl_BE is always synched by nl_NL?

Most of the language is the same, I agree, but there are some slight differences, BE has other words and meanings as NL and vice versa. Especially when it comes to specific words used in accountancy for example, other rules, other laws, etc.

 http://www.groencreaties.be/ logo

Web:  http://www.groencreaties.be/ http://www.groencreaties.be

Mail :  mailto:willy@groencreaties.be willy@groencreaties.be

Tel.  : 0472 / 655.105

Van: Francis Appels [mailto:notifications@github.com] 
Verzonden: woensdag 30 september 2015 22:50
Aan: Dolibarr/dolibarr
CC: willyotto
Onderwerp: Re: [dolibarr] Signature in proposal pdf is in English, has to be Dutch (#3625)

I'm also nl_BE speaking, but I'm an nl_NL translator (and user) because nl_BE is only recently added to transifex. Didn't know nl_BE was available. Just had a look at nl_BE in transifex and noticed that nl_BE is the same as nl_NL with the difference that the unstranslated are in en_EN and review is 0%. So nl_BE - nl_NL diffs are gone, but new translations will be synced to nl_BE in github (noticed from 3.8 the nl_BE folder only contains new syncs). You should translate "Written acceptance, company stamp, date and
signature" in nl_NL because it can be translated in 'common' dutch readable by dutch and flamish speaking. To be continued...

**Comment by fappels** [comment]
No, think it happened during the first upload of nl_BE to transifex. The major problem now is that the special flamish terms form the past are lost in 3.8 (you will still have them because you probably did an update to 3.8, but a fresh install will not have the special terms). I think the best solution is to re-upload the 3.7 nl_BE to transifex and keep all 'untranslated' untranslated except the specials.
Please reply online.
