### ISSUE TITLE
Total HT on "Object Linked Block" for proposals with invoice are wrong if use FACTURE_DEPOSITS_ARE_JUST_PAYMENTS 

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#3627]
Dolibarr 3.7 and 3.8
Set FACTURE_DEPOSITS_ARE_JUST_PAYMENTS=1
Create a proposal (ref:PR0001) about 100 €
create a deposit invoice (ref:AC0001) from PR0001 about 50 €
Set AC0001 as paid and convert it in future discount
Create complete invoice (ref:FA0001) about 100€ from PR0001
Valid invoice FA0001. Add payment from AC0001. So now rest to paid is 50 €
Complete payment FA0001 about 50 €. FA0001 is completely paid 100€

Go on Proposal PR0001 
The invoice linked block show two element
AC0001 : 50 €
FA0001 : 100 €
TOTAL HT 150 €

Even it is true, the problem is the real amount accounted is 100€ not 150 €.
How should we output this ?
AC0001 : 50 €
FA0001 : 100 € (-50 € from AC0001)
TOTAL HT 100 €
??

**Comment by eldy** [comment]
To show the (-50 from ...), you must check all payments done for each invoice and look if there is a payment that is in fact a deposit invoice. You should be abale to detect this by scanning table
societe_remise_except
field fk_facture and fk_facture_source can be used to know wich deposit invoice was used.
You must also filter on description ='(DEPOSIT)'

**Comment by FHenry** [comment]
@eldy Shall we consider it as a FIX or NEW ?

**Comment by eldy** [comment]
A fix. Be aware to add code for fix only when option is on.

**Comment by FAPMLIL** [comment]
Hi,

@eldy, Is a fix available for 3.8.3 ?

Thanks :)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
