### ISSUE TITLE
Not able to add Task to Project

### ISSUE THREAD

**Issue by apachler** [Dolibarr/dolibarr#3628]
(Dolibarr 3.8.0)

If I want to add the following task to a Project
![neue_aufgabe](https://cloud.githubusercontent.com/assets/3908272/10215458/e6ca5a7e-6821-11e5-88f9-6eea045d452c.jpg)

I get the following result
![neue_aufgabe_fehler](https://cloud.githubusercontent.com/assets/3908272/10215465/ef49a506-6821-11e5-9585-1d00f37310c9.jpg)

The Task is not created at all ...

**Comment by eldy** [comment]
Can you reproduce on demo.dolibarr.org ?

**Comment by apachler** [comment]
Yes, see the screenshots ...
![task_add](https://cloud.githubusercontent.com/assets/3908272/10221201/58826f82-684d-11e5-8086-f8b61215f26f.jpg)
![task_fehler](https://cloud.githubusercontent.com/assets/3908272/10221203/5af79c38-684d-11e5-9f1e-be7689c5eb42.jpg)

**Comment by eldy** [comment]
Thanks. I've got it. Before official fix, you can create task from the tab task of a project.

**Comment by apachler** [comment]
Thanks

**Comment by caBBAlainB** [comment]
Good, thks Eldy
