### ISSUE TITLE
Layout glitch on Partners/Supplier

### ISSUE THREAD

**Issue by apachler** [Dolibarr/dolibarr#3629]
(Dolibarr 3.8.0)

![partner_lieferant](https://cloud.githubusercontent.com/assets/3908272/10215497/49d1e984-6822-11e5-9804-23eb79627d16.jpg)

**Comment by FHenry** [comment]
What is your browser ?

**Comment by apachler** [comment]
Firefox 40.0.3

**Comment by eldy** [comment]
Do you use external module ?
Can you try to clear your browser cache ?
Don't experience problem with firefox 41.0

**Comment by apachler** [comment]
No, i dont use any external modules, the installation is about 3 days old and there are no modifications done. Clearing the browser cache did not resolve the problem.

**Comment by ndrosis** [comment]
You can try it with the chrome?

**Comment by apachler** [comment]
Problem occours with FF37.0.2 also ...
I am going to try other Browsers soon

**Comment by apachler** [comment]
Same with
FF 41.0.1
Safari 5.1.7
Chrome 45.0.2454.101 m

**Comment by FHenry** [comment]
Did you add extrafields ?

**Comment by ndrosis** [comment]
Try to change theme

**Comment by eldy** [comment]
Which package did you use for install .tgz , .deb , .zip , .exe ?

**Comment by rdoursenaud** [comment]
This occurs when the page is not completely rendered because it's been interrupted by a bug.
Your server logs should tell us more.

**Comment by rdoursenaud** [comment]
Thinking a bit more about it, I remember we have a categories bug in 3.8.0 that's triggering this behavior.
Disable categories or wait for the fix that will be shipped with 3.8.1.

**Comment by rdoursenaud** [comment]
Duplicate #3529

**Comment by apachler** [comment]
Oh ok, thanks for your efforts!

**Comment by eldy** [comment]
Close as duplicate
