### ISSUE TITLE
Unknown column 'NaN' in 'field list'

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#3661]
Version 3.8.1
try to add a product to an order
if you select other 'buy price" like pmp or another buy price, it doesnt display this message.

Smells ike a bug on margin module

cant reproduce on http://demo.dolibarr.org/commande/card.php?id=1374#add 
because cray messages of VAt and brazil

**Comment by eldy** [comment]
Can you provide a screenshot of your seup of marin module ?

**Comment by BebZ** [comment]
Marin module ? i dont understand, here is 
the screenshot 1 i select the product
the screenshot 2 i try to add and there's error message

![1 unknow column nan](https://cloud.githubusercontent.com/assets/3694135/10278251/100b0ab8-6b5c-11e5-80e5-cfc875193d25.JPG)
![2 unknow column nan](https://cloud.githubusercontent.com/assets/3694135/10278252/102bcf96-6b5c-11e5-9606-14af84787860.JPG)

**Comment by BebZ** [comment]
and the screenshot showing it works when u select another p.p.f.
![image](https://cloud.githubusercontent.com/assets/3694135/10278310/82369864-6b5c-11e5-9345-5a0a23ed456d.png)

**Comment by BebZ** [comment]
Priority Low ? On forum it's complaining already...

http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/54143-bug-prix-d-achat-module-marges#64472

http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/54024-bug-saisie-de-commande-client-3-8-1#63888

(and it's not me, for once !)

Sur la version 3.8.1, il est simplement impossible de saisir une commande. La saisie d'un article provoque le message d'erreur suivant :
"Unknown column 'NaN' in 'field list'"

A noter que la ligne de commande n'est pas validé, du coup il est impossible de saisir une commande.

**Comment by BebZ** [comment]
closed by #3986

**Comment by marcosgdf** [comment]
The fix for this bug is not present in 3.8.2…

**Comment by eldy** [comment]
Fix is in 3.8 branch but was commited after 3.8.2 release
