### ISSUE TITLE
main.inc.php have an syntax error

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#3662]
I installed today dolibarr from git. After installing everything as needed i tried to log in, but the login screen didnt appear. The problem is showed in the apache log file:

[Sun Oct 04 22:57:00.661772 2015] [:error] [pid 3532:tid 140394545207040] [client 127.0.0.1:40069] PHP Parse error:  syntax error, unexpected '}' in /home/sasa/public_html/dolibarr/htdocs/main.inc.php on line 169, referer: http://localhost/~sasa/dolibarr/htdocs/install/index.php

--- cut-here---
diff --git a/htdocs/main.inc.php b/htdocs/main.inc.php
index 826d4e7..8b41958 100644
--- a/htdocs/main.inc.php
+++ b/htdocs/main.inc.php
@@ -165,7 +165,6 @@ if (! defined('NOSCANPOSTFORINJECTION'))
 // This is to make Dolibarr working with Plesk
 if (! empty($_SERVER['DOCUMENT_ROOT']) && substr($_SERVER['DOCUMENT_ROOT'], -6) !== 'htdocs') {
                set_include_path($_SERVER['DOCUMENT_ROOT'] . '/htdocs');
-   }
  }
  
  // Include the conf.php and functions.lib.php
  ---cut-here---

**Comment by eldy** [comment]
Fixed

**Comment by rdoursenaud** [comment]
My bad. Sorry!
