### ISSUE TITLE
Bug: Second field in project-box list does contain wrong url. Links to product-card instead of project-card.

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#3669]
# Environment
- **Version**: 3.8.0
- **OS**: Linux
- **Web server**: Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/1.0.1j PHP/5.5.19 mod_wsgi/4.2.5 Python/2.6.2
- **PHP**: apache2handler 5.5.19
- **Database**: MySQL 5.1.72-log
- **URL**: /MyWeb/dolibarr/htdocs/index.php?mainmenu=home
# Report

Second field in project-box list does contain wrong url. Links to product-card instead of project-card

./core/boxes/box_project.php  
 ...
 if ($result) {
                $num = $db->num_rows($result);
                $i = 0;
                while ($i < $num) {
                    $objp = $db->fetch_object($result);

```
                $tooltip = $langs->trans('Project') . ': ' . $objp->ref;
                $this->info_box_contents[$i][0] = array(
                    'td' => 'align="left" width="16"',
                    'logo' => 'object_project',
                    'tooltip' => $tooltip,
                    'url' => DOL_URL_ROOT."/projet/card.php?id=".$objp->rowid,
                );

                $this->info_box_contents[$i][1] = array(
                    'td' => 'align="left"',
                    'text' => $objp->ref,
                    'tooltip' => $tooltip,
                    'url' => DOL_URL_ROOT."/product/card.php?id=".$objp->rowid,
                );
```

...

**Comment by rdoursenaud** [comment]
Introduced in ee1bc22e79313e8937020bdb641aa637d7231dd2
Fixed in e3f225e0
@eldy could you assign the bug to you and reference it in your commit so that we know it's handled . Would have saved me a dozen minutes… Thanks.
