### ISSUE TITLE
Merge documents error TCPDF

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#3674]
Hi

It is possible to merge old invoices (2013, 2014), but not new one.
All I have is a blanck page, but here is the log in /var/log/apache2/error.log : 

[Mon Oct 05 15:09:18.754390 2015] [:error] [pid 14445] [client x.y.z.w:48337] PHP Fatal error:  Uncaught exception 'Exception' with message 'TCPDF_PARSER ERROR: decodeFilterFlateDecode: invalid code' in /var/www/html/htdocs/includes/tecnick.com/tcpdf/include/tcpdf_filters.php:474\nStack trace:\n#0 /var/www/html/htdocs/includes/tecnick.com/tcpdf/include/tcpdf_filters.php(359): TCPDF_FILTERS::Error('decodeFilterFla...')\n#1 /var/www/html/htdocs/includes/tecnick.com/tcpdf/include/tcpdf_filters.php(94): TCPDF_FILTERS::decodeFilterFlateDecode(';\x9C\xF1lB\x8E\x10\xF9\xD5\xB4\xD6\x10j\xF9\xF6...')\n#2 /var/www/html/htdocs/includes/tcpdi/tcpdi_parser.php(1279): TCPDF_FILTERS::decodeFilter('FlateDecode', ';\x9C\xF1lB\x8E\x10\xF9\xD5\xB4\xD6\x10j\xF9\xF6...')\n#3 /var/www/html/htdocs/includes/tcpdi/tcpdi_parser.php(1218): tcpdi_parser->_rebuildContentStream(Array)\n#4 /var/www/html/htdocs/includes/tcpdi/tcpdi.php(192): tcpdi_parser->getContent()\n#5 /var/www/html/htdocs/compta/facture/mergepdftool.php(324): TCPDI->importPage(1)\n#6 {main}\n  thrown in /var/www/html/htdocs/includes/tecnick.com/tcpdf/include/tcpdf_filters.php on line 474, referer: http://www.yyyy.com/htdocs/compta/facture/mergepdftool.php?sortfield=f.date_lim_reglement&sortorder=ASC

Thanks

**Comment by rdoursenaud** [comment]
Can you please tell us what version you are using.
https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md

**Comment by ozit** [comment]
Sorry, I forgot, 
Version : 3.9.0-beta (develop branch)

# Environment
- **Version**: 3.9.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.13-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.44-0+deb8u1
- **URL**: /htdocs/compta/facture/mergepdftool.php

**Comment by ozit** [comment]
Correction seems ok
