### ISSUE TITLE
Stock values incorrectly tracked

### ISSUE THREAD

**Issue by akhalz** [Dolibarr/dolibarr#3680]
Stock was received after validating a supplier invoice.
The stock increased as expected
The supplier invoice was reopened and modified to receive a larger amount.
The stock increased without decreasing first. Double counting

**Comment by rdoursenaud** [comment]
AFAIK, such a workflow is not supported. Reopening is at the user's risk.
What stock management rules do you use?

**Comment by akhalz** [comment]
Sorry for the delayed response

Rules currently being used :
Decrease real stocks on customers invoices/credit notes validation
Increase real stocks on suppliers invoices/credit notes validation

The stock management works correctly for customers, even increases stock when reopening and editing an invoice. It just doesn't work the same for suppliers. 

There also needs to be a way to input the actual stock count instead of adding and deleting from the figure.

**Comment by rdoursenaud** [comment]
Thanks for the response. I've added your feedback as a feature request.

**Comment by akhalz** [comment]
Thanks
Well the stock management for suppliers is still a bug.
The stock count insertion would be a feature request.

**Comment by gorgoi** [comment]
hello, please can you help me?
I can not activate YES boutton for  "Increase real stocks on suppliers invoices/credit notes validation "
Do you have any ideea why?

**Comment by akhalz** [comment]
Bug has been corrected and stock management works correctly
