### ISSUE TITLE
Can't set Parent company 

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#3681]
Hi

On 3.8.0 It's impossible to set a parent company, search list provide correct information but can't set link between companies.
After save parent company stay empty

**Comment by atm-gauthier** [comment]
Hi Raphael, you're right, i didn't see this issue.
Thank you

**Comment by marcosgdf** [comment]
So I guess this issue can be closed, right?

**Comment by atm-gauthier** [comment]
Yes now that it has been merged we can close it =)

**Comment by camlafit** [comment]
Yes looks solved on 3.8.2
