### ISSUE TITLE
ER pdf with more than 11 lines show a middle blank page

### ISSUE THREAD

**Issue by aspangaro** [Dolibarr/dolibarr#3685]
In Dolibarr 3.8, the new module Expense Report add a blank page in the middle of standard pdf when you are more than 11 lines.

Sorry impossible to link a pdf file to show the problem

**Comment by rdoursenaud** [comment]
Self-reminder: #3499

**Comment by DrSParis** [comment]
Hi there, I have as well the problem, very problematic for me as I need to produce those files officially.
Could the priority be revaluated to something higher than low?
Or perhaps would you have a workaround?

**Comment by be-neth** [comment]
Hi,

Same bug for me but with the last version of dolibarr (5.0.3) and the bug appears with more than 16 expense entries.

**Comment by alaunay** [comment]
I can confirm I still have this problem with Dolibarr 7.0.3.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by laudeco** [comment]
I agree with @eldy I think this issue has been fixed last year.
