### ISSUE TITLE
modWorkflow - Not an order is created when a propal is closed signed

### ISSUE THREAD

**Issue by fmarcet** [Dolibarr/dolibarr#3689]
# Environment
- **Version**: 3.8
# Report

The problem is that when trigger is called, the value status of propal is still 1 (validated) so the function createFromProposal on commande.class.php doesn't pass the first "if" (if ($object->statut == 2)) so does nothing.

I don't know what is better solution, remove this "if" and create an order every time function is called or on modWorkflow trigger change the status to 2 before call the function.

For now, createFromProposal is only called by this trigger.

**Comment by rdoursenaud** [comment]
The `Commande::createFromProposal()` code has not changed since 2011. I think the problem lies in the trigger itself.

**Comment by rdoursenaud** [comment]
The trigger is launched on the same (local) status condition, so I believe that the status "protection" in `commande.class.php` can go away. It serves no purpose anymore.
