### ISSUE TITLE
Special payment type 0 is not rounded in Financial report by company

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3690]
Version: 3.7.2

Page: /compta/resultat/clientfourn.php?leftmenu=report

![captura de pantalla 2015-10-08 a las 10 47 45](https://cloud.githubusercontent.com/assets/168744/10361691/07685168-6daa-11e5-9f7e-f45058845223.png)

**Comment by marcosgdf** [comment]
In 3.8.3 benefits are not rounded

![captura de pantalla 2016-03-06 a las 20 36 08](https://cloud.githubusercontent.com/assets/168744/13556487/149ff5aa-e3db-11e5-878a-19e035b48917.png)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
