### ISSUE TITLE
Bug: Classify billed not active

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#3692]
Hi
# Environment
- **Version**: 3.9.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.13-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.44-0+deb8u1
- **URL**: /htdocs/comm/propal.php?id=1993
# Report

Since weeks, it seems that the button "Classify billed" is no longer available for a quote with a related bill.

Thanks

**Comment by rdoursenaud** [comment]
Not a bug. See #3622 .
