### ISSUE TITLE
Events created from member pages are not linked to the member

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3693]
Events/tasks created from `/adherents/agenda.php` are not linked to the member as expected.

**Comment by marcosgdf** [comment]
I see it is not even implemented… Should we consider it a feature request or a bug?

**Comment by rdoursenaud** [comment]
Let's say it's a bit of both…

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
