### ISSUE TITLE
Allow linking events to multiple companies and/or contacts

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3697]
Meetings often takes place with multiple parties. Linking to them all would be a great time-saver.

**Comment by gschratzer** [comment]
a very good idea, i had this also sometimes a meeting with more than on customer.

Recurring events were also great in this job.
i.E. Joir Fix on each first Wednesday in month at 10 am

**Comment by choybe** [comment]
Why this isn't fixed until more than 2 years later?
