### ISSUE TITLE
Add postal address informations in users card

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3699]
Now that we use users as employees for HRM purposes, having their address is a must.

**Comment by aspangaro** [comment]
Hi @rdoursenaud , 

I begin to work on a complete hrm module.
I take this feature request.

See #3705

Have a nice day

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
