### ISSUE TITLE
Use employee address for expense reports PDF

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3700]
The current text in the usual address space makes no sense and should just be a foot note.

Using the employee address would make better sense… After #3699!

**Comment by aspangaro** [comment]
I'm ok, the current text in the block address should be a foot note... but why add employee address ? The expense concern company, not the employee. 

I prefer to transform this block for signature or electronic signature and move it to the footer page.

**Comment by rdoursenaud** [comment]
Well, in my experience, the workflow generally is:
- The employee pays the expenses and declares them (so it's very much their concern)
- The company reimburse the expenses

Having a nice document to send (or give) your employee along with the reimbursement would be nice.
I'm talking small size companies here.
Of course bigger ones will have this integrated with their payroll.

**Comment by mwelters** [comment]
I agree with @rdoursenaud 

Should it be changed in general or should there be a config switch  ?
If my employees file in a expense report, then they will receive the money, not my company...
