### ISSUE TITLE
Panel de proyectos en inicio

### ISSUE THREAD

**Issue by marioastur** [Dolibarr/dolibarr#3702]
El panel de proyectos que se coloca en el Area Inicio, enlaza con los productos.
Dolibarr 3.8.0
![dolibarr](https://cloud.githubusercontent.com/assets/6816370/10375424/b572cf06-6df8-11e5-803b-8880fb4d487b.png)

**Comment by rdoursenaud** [comment]
Duplicate #3669. Already fixed. Fix will be available in next release.
Also, please interact in english with the community.
