### ISSUE TITLE
Do not display supply prices whe user does not have rights on margin module

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#3706]
Issue from Forum
http://www.dolibarr.fr/forum/526-autres-modules/53986-module-marge-gestion-des-droits-version-3-8-0

If use has o rights on margin, he shoould not see supplier prices

**Comment by tiaris** [comment]
If user has no rights on margin, he should not see supplier prices on dolibarr pages

**Comment by tiaris** [comment]
If user has no rights on margin, he should not see supplier prices on dolibarr pages

**Comment by marcosgdf** [comment]
Which pages?

**Comment by marcosgdf** [comment]
More information will be appreciated…

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
