### ISSUE TITLE
Rename RUM to UMR and add a tooltip explaining the acronym 

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3708]
Version: 3.7.2

![captura de pantalla 2015-10-09 a las 10 05 24](https://cloud.githubusercontent.com/assets/168744/10388801/56aefb46-6e6d-11e5-81e3-7fbcfcc07d95.png)

**Comment by rdoursenaud** [comment]
Took me a few minutes to find some informations.
The page is `societe/rib.php`.

It stands for "Référence Unique de Mandat".
It's the french for SEPA's Unique Mandate Refererence.
It really should be renamed to UMR with a tooltip help bubble!

Looks like this RUM code structure is expected.
It's generated by `BonPrelevement::buildRumNumber()`.

**Comment by marcosgdf** [comment]
Oh. Then I'll transform it to a feature request.
