### ISSUE TITLE
No product images after migration to 3.8.0

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#3726]
examples 
http://www.dolibarr.fr/forum/8-mise-a-jour/54029-retour-d-experience-d-un-petit-entrepreneur#63945
http://www.dolibarr.fr/forum/8-mise-a-jour/53987-images-produits

This issue was raised in 3.7, and largely discussed, a patch has been made in 3.7, why do we still have this problem ?

**Comment by rdoursenaud** [comment]
Well, the #2743 is still open so I believe that the proper fix is not there yet.
@eldy What's your opinion on this?

**Comment by eldy** [comment]
The trouble seems to be on external modules only when a module build for 3.7 is used with 3.8.

I can't reproduce myself when using standard dolibarr.
If old version of dolibarr is used, the constnat to keep compatibility is set by migration from 3.6 to 3.7 with line.
INSERT INTO llx_const (name, value, type, note, visible, entity) SELECT **ENCRYPT('PRODUCT_USE_OLD_PATH_FOR_PHOTO')**,**ENCRYPT('1')**,'chaine','Use old path for products images',1,0 FROM llx_const WHERE **DECRYPT('name')** = 'MAIN_VERSION_LAST_INSTALL' AND **DECRYPT('value')** < '3.7.0'; 

If this is a new version, the trouble does not exists.

@tiaris From wich version to which one did you experience the trouble into a STANDARD dolibarr feature ?
