### ISSUE TITLE
POS ticket (suggest feature)

### ISSUE THREAD

**Issue by ilvinc3nt** [Dolibarr/dolibarr#3730]
Generate a choice between invoices or tickets in pos module (or different invoices numbers)
watch this (Dolipos BAR):
http://www.doliposbar.com/?wpdmpro=dolipos-bar-ultima-version

ty

**Comment by marcosgdf** [comment]
Due to European Union regulation, we are not able to create tickets in Spain in most of the businesses, they were replaced by Simplified Invoices (which main difference is that the customer is not identified).

**Comment by rdoursenaud** [comment]
The native POS will soon be able to print tickets thanks to @frederic34's hard work.
Get in touch with him ;)

**Comment by frederic34** [comment]
:+1:  and if someone wants to lend me a printer ...
