### ISSUE TITLE
Unknown column 'u.tjm' in 'field list'

### ISSUE THREAD

**Issue by krisjis** [Dolibarr/dolibarr#3736]
After I upgraded from 3.8, I got the following error when trying to log-in:

Unknown column 'u.tjm' in 'field list'

Anyone else got this message or knows how to fix it?

Chris

**Comment by krisjis** [comment]
![image](https://cloud.githubusercontent.com/assets/15128258/10490851/d6aded56-7292-11e5-9be4-0f88a8a02828.png)

**Comment by rdoursenaud** [comment]
Have you followed the upgrade path by upgrading one version at a time?

The tjm column has been introduced in 3.7
Relaunching the 3.6->3.7 and 3.7->3.8 migrations should do the business.
Please let us know!

**Comment by krisjis** [comment]
I try to upgrade 3.6->3.7 and in the process i got an error : Erreur DB_ERROR_1072: ALTER TABLE llx_facture_fourn ADD UNIQUE INDEX uk_facture_fourn_ref (facnumber, fk_soc, entity);
Key column 'facnumber' doesn't exist in table
can you help me again please? i will the creen print picture

**Comment by krisjis** [comment]
![image](https://cloud.githubusercontent.com/assets/15128258/13675741/ee09231e-e6da-11e5-997c-a676c8cf23b4.png)
![image](https://cloud.githubusercontent.com/assets/15128258/13675779/0fdd9bd2-e6db-11e5-89fb-68a34ac678ef.png)

**Comment by hregis** [comment]
it's not 3.6->3.7 in your pictures, but 2.6->2.7 !!!
it's not possible with Dolibarr 3.8 !?!

**Comment by krisjis** [comment]
yes that's true
i got 3.7.1 package for update but when i extract the contain in C:/dolibarr/www/dolibarr/ and delete the install.lock file in the installation page i don't show the option update 3.6 to 3.7

**Comment by hregis** [comment]
it's Doliwamp ?

**Comment by krisjis** [comment]
No

**Comment by hregis** [comment]
the officials packages are here : https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/3.8.3/
you can upgrade 3.0->3.8 includes 3.6->3.7 and 3.7->3.8 with the 3.8 version

**Comment by krisjis** [comment]
ok think you, i will try to download in few minutes
