### ISSUE TITLE
Enforce a strict module compatibility policy

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3738]
Dolibarr has a great modules ecosystem thanks to the [Dolistore](http://dolistore.com) and fellow developers.

Unfortunately, most do not follow Dolibarr development closely and end up being incompatible with recent releases creating various users and integrators frustration.

To mitigate this, I suggest we add a mandatory explicit compatibility declaration to modules.
This way, we can assess if a module is compatible or not and warn users during the upgrade process.
We should also require the publisher's contact informations so we can display an email address or a web link for the user to contact the module developer to ask for compatibility informations or upgrade support.

This is just a draft. Feel free to add your suggestions.

**Comment by atm-maxime** [comment]
:+1:
Personnaly, we (ATM) already are tagging all of our modules on Dolistore with the support email address and the compatible versions. Even more, the compatible versions are part of the module title on Dolistore.

I'd say users should check out if external modules are compatible before doing any upgrade, but having a check function before the migration process sounds good !

**Comment by eldy** [comment]
Adding min and max version is mandatory on dolistore according to the 
https://www.dolistore.com/en/content/3-terms-and-conditions-of-use

Works are on road to have better search on a dedicated version.

**Comment by eldy** [comment]
A work to enhance dolistore has been launched to be able to filter on version
