### ISSUE TITLE
Adding extrafields to shipments module

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#3749]

**Comment by BebZ** [comment]
Hello is it a feature request or a pull request ?
do yo want extrafields on the lines of shipment or on the shipment simply ?
I think the extrafield's master is @FHenry 
but the master is out of time

**Comment by aschio** [comment]
I've created this features request because in next days I will develop this features.
I need extrafields only in shipment, but I could develop it also for shipment lines. Here in Italy, we need more fields to use shipment pdf as a legal document of shipment.
