### ISSUE TITLE
Bug: Form::selectarray function adds the id of the form to class attribute

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3750]
Version: develop

Using: 

``` php
echo Form::selectarray("fk_level[$i]", $price_options)
```

Results in:
![captura de pantalla 2015-10-16 a las 13 01 10](https://cloud.githubusercontent.com/assets/168744/10540187/12fe1c94-7406-11e5-8b0b-88245dde356f.png)

Which is not necessarily a wanted behaviour

**Comment by eldy** [comment]
Goal is to be able to set css style one field per one field. We can do it using the id, but for any css manipulation, i prefer to use class when possible, event if only one object has the class.

**Comment by rdoursenaud** [comment]
So? It's not a bug it's a feature?

**Comment by marcosgdf** [comment]
But if I just want to use the ID there must be a way for the developer to say it so...
