### ISSUE TITLE
Bug: Classify billed button not active

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#3753]
# Environment
- **Version**: 3.9.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.13-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.44-0+deb8u1
- **URL**: /htdocs/comm/propal.php?id=1862
# Report

Hi
For quite some time, the "billed" button is unavailable when an invoice is validated
thanks

**Comment by eldy** [comment]
What is the remain to pay on invoice ? Do you have the buttom "Create payment" ?

**Comment by ozit** [comment]
The remain to pay on invoice is all of it.
On the invoice, yes, I have the buttom "Create payment" in the invoice web page.
I have no error on apache log

**Comment by ozit** [comment]
Actual developp source code resolve the probleme.
