### ISSUE TITLE
Feature Request: class "button-save", "button-cancel" ... instead of

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#3756]
```
print '<input type="submit" class="button" value="' . $langs->trans("Save") . '">';
```

Proposed change would result in:

```
print '<input type="submit" class="button-save">';
```

and would allow for colourizing buttons in one place only (eg. include once  buttons.php).

**Comment by eldy** [comment]
Better change would be

`print '<input type="submit" class="button button-save" value="' . $langs->trans("Save") . '">';`

So we keep compatibility and can introduce button-save into CSS at no risk.
PR are welcome.

**Comment by casati-dolibarr** [comment]
???

**Comment by rdoursenaud** [comment]
@casati-dolibarr I updated @eldy's comment markup. It should be readable now ;)
