### ISSUE TITLE
Move Help Button to top if possible

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#3760]
Follow up of discussion and idea on forum : 
Help is asked on the forums when the wiki can answer most of the questions.
Maybe users (like me) never noticed there is a contextual help button on the bottom left
on products page
http://demo.dolibarr.org/product/index.php?mainmenu=products&leftmenu=
links to :
http://wiki.dolibarr.org/index.php/Module_Produits
or not : 
on commercial page
http://demo.dolibarr.org/comm/index.php?mainmenu=commercial&leftmenu=
no link, except on sub-modules like proposals; orders, etc...

it' linking to the part of the wiki corresponding to section and language of user is using. 
It's pratical but i think never used (do you have stats of visitor's referer to wiki ?)

It woud be good to make it more notice-able, top right or near the body table and description of each module...

**Comment by eldy** [comment]
The help link is on any page where it was coded.
We can add a link on any page. We can't set such a link at top because in current usage of dolibarr, the link is just not used. Setting a priority on feature that are used only 0.01 % of time is not a good thing. We should put first links that are always used.
With 3.9 the size of left banner should be reduced so link should be more visible.

**Comment by BebZ** [comment]
I know it was arround 0% using because if you want help you don't search in the bottom left.
Support "chat" is always bottom right and traditional help should be near logout button.
(where it is now on recent browsers)

it was my 2 cents to make users more aware there is a wiki, and de-congestionnate the forum.
everytime i will see a post on the forum, that can be solved by help wiki and the user didn't see it i will come and put a +1 here ;)

Thanks for your answer

**Comment by rdoursenaud** [comment]
Well, I tend to agree with @BebZ on this one.
The stats showing that it's not used is exactly why it should be put in a more prominent place!
While working with Dolibarr day in and day out for over four years now, I only discovered it a few months ago!
The feature is not easily discoverable, hence it's not used.

**Comment by marcosgdf** [comment]
Help button is now on top right of the screen in 3.9.

**Comment by rdoursenaud** [comment]
Thanks @marcosgdf for the heads up.
Closing…
