### ISSUE TITLE
Help links on 3.9.0 beta login page not visible

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#3771]
![dolibarr - login dolibarr 3 9 0-beta](https://cloud.githubusercontent.com/assets/4573808/10572008/90a1a66c-7644-11e5-9140-e18c2c4af6ed.png)

![dolibarr - login dolibarr 3 9 0-beta 1](https://cloud.githubusercontent.com/assets/4573808/10572007/8cd295c8-7644-11e5-9e58-170caa615688.png)

**Comment by marcosgdf** [comment]
I noticed that too

**Comment by marcosgdf** [comment]
It seems to have been fixed in latest develop
