### ISSUE TITLE
Erreur DB_ERROR_1071: ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files_fullpath(fullpath);

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#3772]
Environment

```
Version: 3.9.0-beta
OS: Linux
Web server: Apache/2.4.10 (Debian)
PHP: apache2handler 5.6.13-0+deb8u1
Database: MySQL or MariaDB 5.5.44-0+deb8u1
URL: /htdocs/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=3.8.0&versionto=3.9.0
```

Report

```
Hi, 
```

When trying to test devopp branch, here is the scrip error : 
Migration du format de la base de données
Connexion au serveur : localhost    OK
Connexion à la base de données : dolibarr OK
Version du serveur de base de données  5.5.44-0+deb8u1
Merci de patienter quelques instants…
Choix du script de migration    3.8.0-3.9.0.sql
Request 1 sql='INSERT INTO llx_const (name, value, type, note, visible) values (**ENCRYPT('MAIN_DELAY_EXPENSEREPORTS_TO_PAY')**,**ENCRYPT('31')**,'chaine','Tolérance de retard avant alerte (en jours) sur les notes de frais impayées',0);'
Request 2 sql='ALTER TABLE llx_accounting_system MODIFY COLUMN pcg_version varchar(32);'
Request 3 sql='ALTER TABLE llx_accountingaccount MODIFY COLUMN fk_pcg_version varchar(32);'
Request 4 sql='UPDATE llx_const SET name = **ENCRYPT('ACCOUNTING_EXPORT_PREFIX_SPEC')** WHERE **DECRYPT('name')** = 'EXPORT_PREFIX_SPEC';'
Request 5 sql='UPDATE llx_const set value = **ENCRYPT('eldy')** WHERE **DECRYPT('value')** = 'auguria';'
Request 6 sql='UPDATE llx_const set value = **ENCRYPT('eldy')** WHERE **DECRYPT('value')** = 'bureau2crea';'
Request 7 sql='UPDATE llx_const set value = **ENCRYPT('eldy')** WHERE **DECRYPT('value')** = 'amarok';'
Request 8 sql='UPDATE llx_const set value = **ENCRYPT('eldy')** WHERE **DECRYPT('value')** = 'cameleo';'
Request 9 sql='ALTER TABLE llx_accountingaccount RENAME TO llx_accounting_account;'
Request 10 sql='ALTER TABLE llx_societe ADD COLUMN model_pdf varchar(255);'
Request 11 sql='ALTER TABLE llx_societe_commerciaux ADD COLUMN import_key varchar(14) AFTER fk_user;'
Request 12 sql='ALTER TABLE llx_categorie ADD COLUMN color varchar(8);'
Request 13 sql='create table llx_overwrite_trans(rowid integer AUTO_INCREMENT PRIMARY KEY,lang varchar(5),transkey varchar(128),transvalue text)ENGINE=innodb;'
Request 14 sql='ALTER TABLE llx_payment_salary ADD COLUMN datec datetime after tms;'
Request 15 sql='ALTER TABLE llx_payment_salary CHANGE COLUMN fk_user_creat fk_user_author integer;'
Request 16 sql='ALTER TABLE llx_adherent ADD COLUMN pass_crypted varchar(128) after pass;'
Request 17 sql='ALTER TABLE llx_paiement ADD COLUMN ref varchar(30) NOT NULL AFTER rowid;'
Request 18 sql='ALTER TABLE llx_socpeople ADD COLUMN photo varchar(255) AFTER skype;'
Request 19 sql='ALTER TABLE llx_user_param MODIFY COLUMN value text NOT NULL;'
Request 20 sql='ALTER TABLE llx_expedition ADD COLUMN import_key varchar(14);'
Request 21 sql='ALTER TABLE llx_expedition ADD COLUMN extraparams varchar(255);'
Request 22 sql='ALTER TABLE llx_bank_account MODIFY COLUMN code_banque varchar(128);'
Request 23 sql='ALTER TABLE llx_prelevement_facture_demande MODIFY COLUMN code_banque varchar(128);'
Request 24 sql='ALTER TABLE llx_prelevement_lignes MODIFY COLUMN code_banque varchar(128);'
Request 25 sql='ALTER TABLE llx_societe_rib MODIFY COLUMN code_banque varchar(128);'
Request 26 sql='ALTER TABLE llx_contrat ADD COLUMN ref_customer varchar(30);'
Request 27 sql='ALTER TABLE llx_ecm_directories MODIFY COLUMN fullpath varchar(10000);'
Request 28 sql='CREATE TABLE llx_ecm_files(rowid integer AUTO_INCREMENT PRIMARY KEY,label varchar(64) NOT NULL,entity integer DEFAULT 1 NOT NULL,filename varchar(255) NOT NULL,fullpath varchar(10000) NOT NULL,fullpath_orig varchar(10000),description text,keywords text,cover text,extraparams varchar(255),date_c datetime,date_m timestamp,fk_user_c integer,fk_user_m integer,acl text) ENGINE=innodb;'
Request 29 sql='ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files_fullpath(fullpath);'
Erreur DB_ERROR_1071: ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files_fullpath(fullpath);
Specified key was too long; max key length is 767 bytes
Exécution du script    KO

thanks

**Comment by eldy** [comment]
If you run manually this request:
CREATE TABLE llx_ecm_files(rowid integer AUTO_INCREMENT PRIMARY KEY,label varchar(64) NOT NULL,entity integer DEFAULT 1 NOT NULL,filename varchar(255) NOT NULL,fullpath varchar(10000) NOT NULL,fullpath_orig varchar(10000),description text,keywords text,cover text,extraparams varchar(255),date_c datetime,date_m timestamp,fk_user_c integer,fk_user_m integer,acl text) ENGINE=innodb;'

and replace 10000 with 1000. Does it work for you ?

**Comment by ozit** [comment]
Do you mean that you test lower value or you asking me to do it ?
I saw you change the value from 10000 to 1000, but the  max key lenght is 767.

Request 28 sql='CREATE TABLE llx_ecm_files(rowid integer AUTO_INCREMENT PRIMARY KEY,label varchar(64) NOT NULL,entity integer DEFAULT 1 NOT NULL,filename varchar(255) NOT NULL,fullpath varchar(750) NOT NULL,fullpath_orig varchar(750),description text,keywords text,cover text,extraparams varchar(255),date_c datetime,date_m timestamp,fk_user_c integer,fk_user_m integer,acl text) ENGINE=innodb;'
Request 29 sql='ALTER TABLE llx_ecm_directories MODIFY COLUMN fullpath varchar(1000);'
Request 30 sql='ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files_fullpath(fullpath);'
Erreur DB_ERROR_1071: ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files_fullpath(fullpath);
Specified key was too long; max key length is 767 bytes
Request 31 sql='ALTER TABLE llx_product ADD COLUMN onportal tinyint DEFAULT 0 after tobuy;'
Exécution du script
