### ISSUE TITLE
Missing "set as  invoiced" in propal pages

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#3775]
Hi

Since, at least 3.8.x, is no more possible to class "propal"  as invoiced. I don't see any new option on configuration page and superadmin doesn't have anymore this possibility.

How to restore this status ?

**Comment by eldy** [comment]
The button appears if you have at least on invoice created on the signed proposal.
Do you have one invoice created ?

Another solution is to add constant WORKFLOW_PROPAL_CAN_CLASSIFIED_BILLED_WITHOUT_INVOICES to 1 into home - setup - other.

I will replace option with its opposite WORKFLOW_PROPAL_NEED_INVOICE_TO_BE_CLASSIFIED_BILLED in next release for better compatilbity with old behaviour.

**Comment by camlafit** [comment]
Yes of course, I've many propals check as "to invoice" with full paid invoice. 

And since 3.8, without change in my configuration, button has disappeared. Follow a screen picture where previously a "close as invoiced" was here.

![propalwithoutclosebutton](https://cloud.githubusercontent.com/assets/209915/10587152/21c5ecd8-76a0-11e5-8b8a-f85016f8b872.png)

I don't understand why propose new constant to solve this problem.

**Comment by camlafit** [comment]
Hi

No news , can you explain why to close this issue. Must be open a new.

**Comment by FHenry** [comment]
could you trun of "Utiliser les droits avancés dans les permissions des modules" desactivate  propal module, activate propal module, check your use rights, test button are ok, then only turn on ""Utiliser les droits avancés dans les permissions des modules", and check your user right, may be force it again or paly with user group, and tell us if button are now ok

**Comment by camlafit** [comment]
Follow my response to this message : 
"could you trun of "Utiliser les droits avancés dans les permissions des modules" desactivate propal module, activate propal module, check your use rights, test button are ok, then only turn on ""Utiliser les droits avancés dans les permissions des modules", and check your user right, may be force it again or paly with user group, and tell us if button are now ok"

Hi

I've tried these steps :
- turn off "Utiliser les droits avancés dans les permissions des modules" ,
  was yet disable
- desactivate propal module
- activate propal module
- check your use rights
- test button are ok
  Any change at this step, my user can't close as paid. And superadmin
  neither
- turn on ""Utiliser les droits avancés dans les permissions des modules",
- check your user right,
- check button

Nothing, button is again missing

Any group are created. Mine users don't have group set.

**Comment by eldy** [comment]
Bug was fixed and should be available for 3.8.2
