### ISSUE TITLE
dev/initdata dumps contains fields that are not native

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3789]
I just checked my database initialized with developers initial data and figured it has fields that are not part of the original Dolibarr distribution.
While they seem to not do any harm, I find that rather odd…

I didn't review all the tables. Here are the fields I came across:
- llx_user.phenix_login
- llx_user.phenix_pass

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
