### ISSUE TITLE
Add hook or trigger for detection to displaying a page.

### ISSUE THREAD

**Issue by all3kcis** [Dolibarr/dolibarr#3791]
[Discussion]
Would it be possible to have a hook or trigger to detect the display of a page or URL detection in main.inc.php?

This would allow for a module to perform actions (treatments, checks) before displaying a page.

**Comment by eldy** [comment]
Currently, output of pages are done step by step with no buffer. So there is no way to intercept the output of all page to change it.
If goal is to perform actions before the standard code that display a page is run, this should be done into action part of pages. However, there is no "full common" code for controller code. We should have a call to the doActions hook everywhere, so you can use it, we it is not implemented into all pages.

**Comment by all3kcis** [comment]
Yes, it might be possible to do something from the "main" file?

**Comment by rdoursenaud** [comment]
@All-3kcis Could you provide real world use cases for such a feature that are not covered by available facilities (hooks, triggers…)?

**Comment by all3kcis** [comment]
@rdoursenaud  Yes, for example the tab is a very good option overload, but it has the defect that the tabs still available if you know the URL (bookmarks).
For the needs of one of my modules I have to be sure that the person can not access the old tab.
If I can detect the display of an old page I could for example redirect the user to the new.

**Comment by rdoursenaud** [comment]
Hum, we're talking about a routing framework here. Unfortunately Dolibarr is not designed that way.
I guess that a short term solution would be to use your webserver's URL rewriting capabilities.
Nothing prevents you from doing a redirect in the old tab either. It's not elegant but it should work.

**Comment by all3kcis** [comment]
My temporary solution is to add an include at the end of main.inc.php (Automatically upon activation of the module) that redirects to a file containing this:

$var = (!empty($_SERVER['QUERY_STRING'])) ? $var='?'.$_SERVER['QUERY_STRING'] : '';
if(strpos($_SERVER['SCRIPT_FILENAME'], "htdocs/product/stock/product.php")){
    header('Location: /var/www/htdocs/mymodule/product/stock/product.php'.$var);exit;
}

**Comment by altairis-tof** [comment]
studying @All-3kcis use-case, i think he points a security failure. If a module specify to remove a tab, the tab should not be accessible anymore, even by typing its url.
I think we should find a way to do it, maybe in the restrictedarea() function.

**Comment by all3kcis** [comment]
"If a module specify to remove a tab, the tab should not be accessible anymore, even by typing its url."
We are agreement.

**Comment by rdoursenaud** [comment]
Well a module can't remove a tab, it can just merely hide it.
Even the wiki documentation states that it's an illusion.
I don't see any security issue there. Using Dolibarr core code should not open any vulnerability.
What you really want is a tab override feature that would help you replace a tab by you own, for good, right?

**Comment by altairis-tof** [comment]
a module can ask to remove a tab : http://wiki.dolibarr.org/index.php/Tabs_system#To_remove_an_existing_tab
maybe dolibarr just hide it, but the feature exists

but tab overriding would be a nice feature ;-)

**Comment by rdoursenaud** [comment]
@altatof That's exactly the page I was quoting when I said it's an illusion. The section title is misleading. Technically it just hides it.

**Comment by marcosgdf** [comment]
Aren't you talking about updateSession hook?

**Comment by eldy** [comment]
I think the hook updateSession should address the need.
