### ISSUE TITLE
Box Informations add version and last stable version

### ISSUE THREAD

**Issue by ndrosis** [Dolibarr/dolibarr#3797]
Hi

To run needs a csv file accessible to an on line server.*
Will be must update when available a new release.*

*Can there be this a possibility?

CSV
version,description,type,downloadlink
3.8.2,Stable,0,http://sourceforge.net/projects/dolibarr/files/

Best regards
Nikos DROSIS
![update](https://cloud.githubusercontent.com/assets/4933899/10714590/5c7d5a66-7afe-11e5-8a46-992db10d3d19.png)

**Comment by rdoursenaud** [comment]
This is already done in `admin/system/about.php` without any CSV(?!?)

**Comment by rdoursenaud** [comment]
In terms of design, losing two lines for such a small feature is a big waste of space. A single line should be enough. Also, this feature, if implemented, should really be only available to admins!
