### ISSUE TITLE
dolibarr/htdocs/public/cron/cron_run_jobs.php wrong "...&& $line->dateend < $now)

### ISSUE THREAD

**Issue by javieralapps4up** [Dolibarr/dolibarr#3798]
eldy closed this issue (#2519) from a commit on 2 Apr, but he repaired the script, not the file htdocs/public/cron/cron_run_jobs.php.

it is not the same.

**Comment by marcosgdf** [comment]
So is this fixed or a new bug is introduced? :laughing:

**Comment by javieralapps4up** [comment]
Marcos, never fixed. It is the same error. Eldy corrected the cron script, not the php file. Has you read the above FIX #2519 link (where Eldy photo)?
