### ISSUE TITLE
function facture->is_last_in_cycle needs debugging

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#3805]
Version Develop
- missing check on empty situation_cycle_ref
- should return 0 or null in case error
- should not do rollback in case of error

**Comment by eldy** [comment]
@rdoursenaud this is for you...

**Comment by FHenry** [comment]
@rdoursenaud, @eldy 
Right now (with this commit #3805 c534f5bcd51485747c808c76128b22b60e7cc9f8 it become impossible to change invoice if invoice not into cycle feature.
Return false if situation_cycle_ref is empty is not a good idea. An invoice without cycling stuff can be modified if it is not paid yet.
Check facture.php line 3560

**Comment by rdoursenaud** [comment]
Thanks @FHenry. Rushed that…
