### ISSUE TITLE
Cant login with git 0a3ba3a

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#3808]
Hi I just updated to the latest git develop tree and I can not login anymore.

When I try to login I get this:
Unknown column 'u.employee' in 'field list' 

Any ideas ?

**Comment by saxa** [comment]
Ok sorry for spamming, running install/index.php solved the issue.

**Comment by rdoursenaud** [comment]
Yep this is a good habit to have when following develop ;)
