### ISSUE TITLE
Call to undefined function local_by_date()

### ISSUE THREAD

**Issue by calidadesystems** [Dolibarr/dolibarr#3815]
This error appears when I go to Financiera tab ( a coins stack) and go to Pagos especiales (Special payments) IRPF (Spain tax) and select Report by tax (last option ).
I attach a capture for clarify where this happens.

![dolibar_error](https://cloud.githubusercontent.com/assets/13454204/10786557/21fbfc7a-7d6b-11e5-98f4-fc4ef00cd2a4.png)

In Php-fpm log appears this message

[28-Oct-2015 11:52:55 Europe/Madrid] PHP Fatal error:  Call to undefined function local_by_date() in htdocs/compta/localtax/quadri_detail.php on line 213

In file htdocs/compta/localtax/quadri_detail.php at line 213  and 215 appears a call to function local_by_date()

``` php
// Load arrays of datas
$x_coll= local_by_date($db, 0, 0, $date_start, $date_end, $modetax, 'sell', $local);
//$x_coll = vat_by_date($db, 0, 0, $date_start, $date_end, $modetax, 'sell');
$x_paye = local_by_date($db, 0, 0, $date_start, $date_end, $modetax, 'buy', $local);
```

I have searched in git log for references to these function but I haven't found nothing 

I suppose that these function should be implemented at file  htdocs/core/lib/tax.lib.php
and should be similar to vat_by_date implementation.

I can try to create this function with some help copying vat_by_date and make some modifications.
it's the right way?

Thanks

**Comment by eldy** [comment]
@simnandez Have you an idea where this function is coming from ?

**Comment by rdoursenaud** [comment]
@simnandez FYI, introduced in 747b6a9f94ce26d96b69237306fc8d70d0300088

**Comment by marcosgdf** [comment]
@simnandez Could you please review this?

**Comment by simnandez** [comment]
Fixed  (better late than never), also with bad day correction included :sweat:
