### ISSUE TITLE
foundations module's ldap2dolibarr script synchs anything including groups

### ISSUE THREAD

**Issue by dethegeek** [Dolibarr/dolibarr#3822]
The script imports anything because no search filter hard coded to *

This makes the script useless as is.

I suggest when modules LDAP and foundation are both enabled, that a new tab provides a customizable search filter.

**Comment by eldy** [comment]
Fixed by a8d28b5e4649d700bb2ed94299be8f4351d961c5
Fix will however be available only with 3.9
