### ISSUE TITLE
Bug: impossible to register a payment with the 3.8.1 release

### ISSUE THREAD

**Issue by xhubier** [Dolibarr/dolibarr#3825]
# Environment
- **Version**: 3.8.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.4.38
- **Database**: MySQL or MariaDB 5.1.31
- **URL**: /dolibarr-3.6.2/htdocs/
# Report

With de 3.8.1 it is impossible to registre a payement (htdocs/fourn/facture/paiement.php not round).
This file is in thé gold repository.
This bug is repliable with edge ans chrome.

**Comment by eldy** [comment]
Do you experience problem with demo.dolibarr.org ?

**Comment by rdoursenaud** [comment]
Sounds like a hosting issue.
Have you checked that the file is correctly installed and has the right permissions?

**Comment by marcosgdf** [comment]
I think this issue should be closed

**Comment by rdoursenaud** [comment]
@marcosgdf Agreed, no reply from OP. Closing.
