### ISSUE TITLE
Required boolean extrafield shows error if boolean not checked

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3828]
Version: 3.7.2

If I create an extrafield for supplier invoices with the following characteristics:
- Type: Boolean (checkbox)
- Unique: no
- Required: yes
- Default: 0

When I want to modify the value and I do not check the input, an error showing me that the field is required is shown.

But checkboxes can hold either true or false values so that message shouldn't be shown to the user.

**Comment by rdoursenaud** [comment]
:+1: Seen that and forgot to report.

**Comment by rdoursenaud** [comment]
On second thought, that's probably a feature. There's no point in setting a boolean extrafield to required except to make sure it's checked!

**Comment by marcosgdf** [comment]
That sounds reasonable...

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
