### ISSUE TITLE
Bug: Unable to upload a document to an invoice under some circunstances

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3836]
Version: 3.7.2 (not tested in latest 3.6)

If I try to upload a PDF document named "123/2015.pdf" to the invoice "123/2015" and I have checked the input that says it will save the document as 123/2015-123/2015, then an error is shown. If not, then it can be uploaded.

```
PHP Warning:  move_uploaded_file(/XXX/documents/facture/XXX_2015/XXX/2015-XXX_2015.pdf): failed to open stream: No such file or directory in XXXX/htdocs/core/lib/files.lib.php on line 706, referer: https://XXX/compta/facture/document.php?id=83
PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpKL7Fbi' to '/XXX/documents/facture/XXX_2015/XXX/2015-XXX_2015.pdf' in /XXX/htdocs/core/lib/files.lib.php on line 706, referer: https://XXX/compta/facture/document.php?id=83
```

**Comment by rdoursenaud** [comment]
Well, the problem seems to be the name of your file. The forward slash is the directory separator on *nix OS! I'm even surprised you can have such a file!

**Comment by marcosgdf** [comment]
I can upload it just if I don't let Dolibarr rename it

**Comment by rdoursenaud** [comment]
Any chance you can do a screencast? I'm just curious to see how you store a file with a forward slash in its name :) There's so much that can go wrong, both on the client and server sides. What OSs are you using?

**Comment by marcosgdf** [comment]
Mac OS X 10.11.1.

Here you are: https://www.dropbox.com/s/m3j3hobzzfw614t/Screencast%20upload%20bug.mov?dl=0

**Comment by altairis-tof** [comment]
it's amazing that this OS allows slashes in filenames; of course when you upload it to a linux server, it fails.

**Comment by marcosgdf** [comment]
The problem is not uploading but Dolibarr renaming it. See that it only fails when the "rename" checkbox is checked

**Comment by rdoursenaud** [comment]
Wow, ok, this is definitely a bug.
I'm also amazed at the filename handling of MacOSX.
I wonder how it encodes it internally. Looks like I'll have to do some research tonight. You struck my interest with this one!

**Comment by marcosgdf** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by marcosgdf** [comment]
I noticed that the problem is not when the file has a slash in its name, but when the invoice has a slash in its reference.

**Comment by rdoursenaud** [comment]
Good catch!
