### ISSUE TITLE
Bug: Selector matches an unknown element "options"

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3864]
Version: develop
File: /htdocs/core/tpl/objectline_create.tpl.php
Line: 509

```
$("#fournprice_predef options").remove();
```

**Comment by rdoursenaud** [comment]
Looks like it's supposed to be shown it the same code a few lines later(545 in current develop):

``` js
$("#fournprice_predef").html(options).show();
```

**Comment by marcosgdf** [comment]
But options is not a valid HTML tag. Right?

**Comment by rdoursenaud** [comment]
Oh, you're right, it should be option and read something like

``` php
$("#fournprice_predef option").each.remove();
```

Could this possibly be related to #3661?
