### ISSUE TITLE
Loose filter with pagination in customer invoice

### ISSUE THREAD

**Issue by jbruitte** [Dolibarr/dolibarr#3872]
Hello,

When I filter the customer invocies "unpaid", then click on the pagination, the unpaid filter disappears...

Do you have any idea ?

Version : 3.8.1

Thank you,

**Comment by jbruitte** [comment]
Resolved by adding : 

``` php
if ($search_status != '' && $search_status >= 0) $param.='&search_status='.$search_status;
```

before the : 

``` php
print_barre_liste($langs->trans('BillsCustomers').' '.($socid?' '.$soc->name:''),$page,$_SERVER["PHP_SELF"],$param,$sortfield,$sortorder,'',$num,$nbtotalofrecords,'title_accountancy.png');
```

line 273 .

**Comment by rdoursenaud** [comment]
And where's the pull request?

**Comment by jbruitte** [comment]
Not really good at using Github. This is why, I post the code :)

**Comment by rdoursenaud** [comment]
Let's help you get started then.

You can do it in just 3 steps:
- clone the repository to your account
- edit the file (You can do that directly online, not harder than a comment)
- make a pull request

For more informations, you can have a peek at our [contributing guidelines](https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md) and GitHub [help pages](https://help.github.com/).

You must understand that we won't extract code from issues. Even less so when they're closed!
Lucky I try to read them all :)

Looking forward to your contributions!
