### ISSUE TITLE
HTML encoded strings when searching for a supplier invoice

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3877]
Version: develop (not tested in 3.8)
Page: http://dolibarr.local/fourn/facture/list.php?sall=aaa

![captura de pantalla 2015-11-04 a las 10 54 50](https://cloud.githubusercontent.com/assets/168744/10934832/7ef24c50-82e2-11e5-821a-3a98a1d02161.png)

**Comment by rdoursenaud** [comment]
Why priority high? Because a forged link can be used to insert arbitrary HTML and JS to steal your credentials…

**Comment by marcosgdf** [comment]
I think you misinterpreted the bug, it is just that $langs->trans is called instead of $langs->transnoentities
