### ISSUE TITLE
Impossible to edit detail of one line in supplier invoice

### ISSUE THREAD

**Issue by jfbaillette** [Dolibarr/dolibarr#3880]
Details one line of a supplier invoice can't be edited.
Fields not displayed (see below)1: 
![doli-invoice](https://cloud.githubusercontent.com/assets/3332281/10944063/9c6a8dee-8317-11e5-9132-88b1b7d2abbf.png)

**Comment by rdoursenaud** [comment]
Looks like the page has been interrupted by a fatal error.
Could you please check your logs and post the error?
Also please try to follow the [contributing guidelines](https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md) and provide the version you're using when reporting a bug.

**Comment by rdoursenaud** [comment]
Fix in #3884

**Comment by jfbaillette** [comment]
Perfect Thank you Raphaël / Lot of thanks to Florian for his help in debugging.
