### ISSUE TITLE
Generated ODT files are corrupted

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3881]
While LibreOffice opens them without any problem, other viewers such as Microsoft Word and Google Docs report that the file is corrupted.
Word will let you open it after the scary message but Google Docs won't even touch it!
I'm not familiar with the way ODTs are generated by Dolibarr but I suppose it's searching and replacing values and omits to update checksums or something like that.
Can anyone more familiar give me a clue?

**Comment by marcosgdf** [comment]
Does this happen with the bundled ODT template or with a customized one?

**Comment by rdoursenaud** [comment]
This seem to only materialize with custom templates prepared with Microsoft Word (in ODT mode of course).
Another proprietary software fuck up?
