### ISSUE TITLE
JS Tooltip does not escape HTML 

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3896]
Version: 3.8

![captura de pantalla 2015-11-05 a las 13 37 45](https://cloud.githubusercontent.com/assets/168744/10968559/73e1c666-83c2-11e5-9933-c1b935821d6c.png)

**Comment by rdoursenaud** [comment]
Yeech, that's indeed an ugly bastard :/

**Comment by eldy** [comment]
Is it really a bug.
If data is correctly escaped against security attack, why not keeping the posssiblity to do that.
Even if this is useless, why not ?

**Comment by marcosgdf** [comment]
??? I don't find it OK…

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by marcosgdf** [comment]
Some XSS injection were fixed but the problem won't be solved until we change the library itself I think

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
