### ISSUE TITLE
Remove deprecated Product::hidden property

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3898]
Introduced in 2010 (8980d9acc21f28e040f6a7fe87e614e659c6b97b)

Is it dead code? The value is not being used anywhere

![captura de pantalla 2015-11-05 a las 14 23 35](https://cloud.githubusercontent.com/assets/168744/10969470/d1f569b4-83c8-11e5-95cb-8c4518743fcf.png)

**Comment by rdoursenaud** [comment]
The field is indeed marked as deprecated in `llx_product.sql` but I don't see the bug…

**Comment by marcosgdf** [comment]
I first reported as a bug because the property was declared dynamically, but then I realized it is no longer used. Should we file it as a FR and remove the code?

**Comment by rdoursenaud** [comment]
Agreed!
