### ISSUE TITLE
Upgrade from 3.7 to 3.8 fails on Postgres due to llx_don.fk_country

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#3912]
I'm running the upgrade process with this page :

/install/upgrade.php?action=upgrade_3.8.0&selectlang=fr_FR&versionfrom=3.7.0&versionto=3.8.0

And I get this error 

```
Erreur DB_ERROR_23502: ALTER TABLE llx_don ADD COLUMN fk_country integer NOT NULL after country;
ERROR: 23502: column "fk_country" contains null values SCHEMA NAME: public TABLE NAME: llx_don COLUMN NAME: fk_country LOCATION: ATRewriteTable, tablecmds.c:4179
```

There's 2 problems here: 
- AFTER is not a standard SQL command and PostgreSQL does not support it. Basically it's just another  MySQL trick. Anyway I'm curious why you'd need to enforce the order of columns in a table... I think you should simply remove this AFTER thing because it introduces more non-standard SQL in the schema for no apparent benefit
- You're setting the new column to NOT NULL but you don't specify a default value for the lines that already exists in the llx_don table. When Postgres add the columns to the existing lines, it will set automatically  fk_country to NULL and immediatly breaking the NOT NULL constraints. I don't know how MySQL handles that.... But the syntax is not good : if you want the colum to be not null you need to specify a default value for the existing lines like this:

``` sql
ALTER TABLE llx_don ADD COLUMN fk_country integer NOT NULL DEFAULT 0;
```

or just allow the columm to be NULL for the existing lines:

``` sql
ALTER TABLE llx_don ADD COLUMN fk_country integer;
```

**Comment by FHenry** [comment]
Hello Damian,
The pgsql.class.php remove the AFTER instruction during execution so it should not be a problem, on the NOT NULL I'm on it

**Comment by FHenry** [comment]
OK, on this "after", the problem is that some contributor put "after" instead of "AFTER". the pgsql db class only remove "AFTER"...  will send information on dev newletters about that

**Comment by daamien** [comment]
Ok thanks...

Anyway what's the point of specifying the order of columns in MySQL if you can't do it with Postgres ? 

This means the order of columns will be different between MySQL and Postgres. If a developper does not know that, he may use the column order (for instance doing a SELECT \* and then accessing the data with the column number, which is a bad idea but quite common).

This may lead to strange behaviours.... And again I don't see the benefit of order the columns

**Comment by FHenry** [comment]
the SELECT \* is "forbidden" into dolibarr (http://wiki.dolibarr.org/index.php/Langages_et_normes : "Les SELECT \* sont interdits ! Chaque SELECT doit spécifier la liste complète des champs à récupérer. Cela permet d'éviter les confusions. Exemple: ")
