### ISSUE TITLE
Upgrade from 3.8 to 3.9 fails on Postgres due to  llx_product.price_autogen

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#3916]
Page:
/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=3.8.0&versionto=3.9.0

Error:

```
Request 80 sql='ALTER TABLE llx_product ADD COLUMN price_autogen TINYINT(1) DEFAULT 0;'
Erreur DB_ERROR_SYNTAX: ALTER TABLE llx_product ADD COLUMN price_autogen TINYINT(1) DEFAULT 0;
ERROR: 42601: syntax error at or near "(" LINE 1: ...ABLE llx_product ADD COLUMN price_autogen smallint(1) DEFAUL... ^ LOCATION: scanner_yyerror, scan.l:1082
```

Here's the problem:

``` sql
ALTER TABLE llx_product ADD COLUMN price_autogen TINYINT(1) DEFAULT 0;
```

is rewritten this way:

``` sql
ALTER TABLE llx_product ADD COLUMN price_autogen smallint(1) DEFAULT 0;
```

The correct syntax for Postgres is 

``` sql
ALTER TABLE llx_product ADD COLUMN price_autogen SMALLINT DEFAULT 0;
```

http://www.postgresql.org/docs/9.5/static/datatype-numeric.html

**Comment by daamien** [comment]
Futhermore the  ALTER TABLE is inconsistent with the original schema here:

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/tables/llx_product.sql#L85

 price_autogen is defined as TINYINT not TINYINT(1)

**Comment by FHenry** [comment]
I've already send a mail when we start to work together to mailling list dev to warn about that, i'll do it again.PR is ongoing

**Comment by marcosgdf** [comment]
My bad! I usually develop with PostgreSQL to avoid these kind of problems but this time I didn't... Should I correct this or you will, @FHenry ?

**Comment by FHenry** [comment]
done PR #3918

**Comment by daamien** [comment]
thanks guys
