### ISSUE TITLE
Handle product/service properties

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3922]
Some products need to be managed with properties (colors, sizes…) and modifiers (XL costs 2€ more).
Stock would have to be modified to handle items with specific properties.

**Comment by marcosgdf** [comment]
I'm going to submit in the following days a feature to handle product attributes, and generate product combinations that have price and weight modifiers. It doesn't handle stock but it can be improved

**Comment by eldy** [comment]
Module "declinaison" from atm seems to deal with that.

**Comment by atm-maxime** [comment]
Module variant available in recent versions
