### ISSUE TITLE
Error updating from 3.8.0 to develop

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3940]
Error DB_ERROR_1072: ALTER TABLE llx_budget_lines ADD UNIQUE INDEX uk_budget_lines (fk_budget, fk_project);
Key column 'fk_project' doesn't exist in table

Error DB_ERROR_1072: ALTER TABLE llx_budget_lines ADD INDEX idx_budget_lines (fk_project);
Key column 'fk_project' doesn't exist in table

**Comment by rdoursenaud** [comment]
Can't reproduce…
Looks like it's been fixed by @eldy at fa8863d2eac449b2105419f610afae5c84ef9d66
