### ISSUE TITLE
Supplier price should not be rounded in margin computations

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#3953]
![bug pfp rounding](https://cloud.githubusercontent.com/assets/3694135/11059966/6fda122e-879d-11e5-9ecd-bc731565e53c.PNG)
It seems there is a rounding problem, when we add a product to an order, the selected buying price is rounded, for example we got a product with 1,8525€ buying price, is rounded at 2€.
I tried to solve it in the limits configuration, but it didn't solve it.

**Comment by BebZ** [comment]
Am i the only one to have this problem of rounding ? 
Ping @eldy @altatof

**Comment by melbus** [comment]
Hi
Same problem for me on 3.8.1

**Comment by BebZ** [comment]
Ping again !! ?

**Comment by BebZ** [comment]
What the hell is wrong with the margins, please , what has been introduced that gets all my monthly margin, wrong wrong and more wrong. I have made a screenshot and explained it quite well. 
So please... 

it's a stable version and this bug is ignored ??? it's not a bug ???

Then, some will complain that users don't test enough and dont report bugs.

Thanks for ignoring such small bugs...

@rdoursenaud @eldy @altatof

**Comment by rdoursenaud** [comment]
@BebZ You know we are not machines, right?
Please show a little bit more respect and be patient.
Thanks!

**Comment by BebZ** [comment]
OK sorry. I am respectful of your work but always impatient when it concerns on-production problems. Deciding to change rounding computations (so dealing with potentially the heart of the heart : numbers...), and not flag it on the admin side of Dolibarr in "limits and precisions" shoud normally "light up" some big warnings not to fall in bad calculations for essential business matters.

**Comment by rdoursenaud** [comment]
@BebZ Sorry for being harsh, I was in a bad mood that day.
For business critical issues, you always have the opportunity to ask a [Preferred Partner](https://wiki.dolibarr.org/index.php/List_of_Dolibarr_partners_and_providers) for a timely fix. Of course, this will come attached to a fee…
In the meantime, community support happens on a best effort basis.

**Comment by BebZ** [comment]
@fappels referenced this issue, maybe he corrected it ?
If not, i will pay the fee for the correction to be PR'd here ;) 
I know everything can't be corrected and checked twice on "free time".

**Comment by rdoursenaud** [comment]
Looking into the issue a bit more closely for @bebz, I don't see any reason for rounding at that stage.
The supplier price is already rounded when inserted on the product page.
Furthermore, this data is multiplied by the quantity to compute margin totals. Reducing the mantissa at that stage greatly reduces the precision and can have disastrous effects.
PR incoming…
