### ISSUE TITLE
BUG : 3.8.2 stock correction impossible to "save"

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#3954]
There is a problem on manual stock movements, when we try to correct, the "save" button has no effect, reloads the page and leaves the fields populated with the data but doesn't implement/decrement stocks...
/product/stock/product.php?id=1131

![bug correction stock imposible 3 8 2 dolibarr](https://cloud.githubusercontent.com/assets/3694135/11060625/a88980f6-87a1-11e5-9fd7-f2b3cbcc8446.PNG)

**Comment by frederic34** [comment]
@BebZ can you try: https://github.com/frederic34/dolibarr/commit/61eb7f48aac77279cf3c6543816cc9abc20cd605

**Comment by marcosgdf** [comment]
Is there any record in the log?

**Comment by BebZ** [comment]
It happens when there are 2 times the same number of batch... prevents the recording of 2 or 3 times the same batch... S172025 for example.
let's close it ;)
