### ISSUE TITLE
Bug: Unable to add a product to a customer order with margins module enabled

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3986]
Version: 3.8.2

Page: http://dolibarr.local/commande/card.php?id=124

If I select, "Input price", this is shown:
![captura de pantalla 2015-11-15 a las 13 18 02](https://cloud.githubusercontent.com/assets/168744/11168700/551eb50a-8b9b-11e5-8fbd-2c6e0138f40c.png)

But even if I don't manually enter the price, then an error "Unknown column 'NaN' in 'field list'" is shown

**Comment by marcosgdf** [comment]
$_POST['buying_price'] = 'NaN';

Caused by /dolibarr/htdocs/fourn/ajax/getSupplierPrices.php returning a localtax number in "price" attribute

**Comment by marcosgdf** [comment]
Already fixed in latest 3.8

**Comment by BebZ** [comment]
https://github.com/Dolibarr/dolibarr/issues/3661
