### ISSUE TITLE
Bug: Undefined variable $num in Formmail::fetchAllEmailTemplate

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3990]
Version: 3.8.2

File: dolibarr/htdocs/core/class/html.formmail.class.php
Line: 886

**Comment by FHenry** [comment]
@marcosgdf pull request merged, you can close the issues

**Comment by marcosgdf** [comment]
@FHenry Are you sure? Github says the commit is only in fhenry/dolibarr
