### ISSUE TITLE
Bug: Supplier unpaid invoices page missing in menu

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3998]
Version: 3.8.2

Page: /htdocs/fourn/facture/impayees.php

It is now only available when accessing from "pending supplier invoices" box in financial area while in previous versions it was available in Supplier Invoices > Pending

Caused by commit 8061ec90840489d8b2177010be46399e99d2f7c3

**Comment by atm-maxime** [comment]
Hi @marcosgdf ,

I think it has been done on purpose to uniformize list management. impayees.php should disappear and be replaced by "list.php?leftmenu=suppliers_bills&search_status=1"

**Comment by marcosgdf** [comment]
But they are not the same… You don't expect the same information in those two pages. When you seek for unpaid bills you do not look for the same information as when you want to see your latest invoices.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
