### ISSUE TITLE
Bug: Unable to create an invoice with total amount = 0

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4001]
Version: 3.7.2

Having the following services:
1. UP: -45 VATTX = 0 TOTAL: -45
2. UP: 37,19 VATTX = 21 TOTAL: 45

TOTAL HT = -7,81
TOTAL VAT = 7,81
TOTAL TTC= 0

An error is shown to the user telling that the invoice should have a positive amount. Is Total HT or Total TTC used to compare? Is this considered as a negative invoice?

**Comment by atm-maxime** [comment]
Hi @marcosgdf 

Old topic, but I think that an invoice can not be negative (otherwise it's a credit note).
Since 3.8, negative lines are not possible in invoices.

**Comment by marcosgdf** [comment]
But I am not trying to create a negative invoice. I am trying to create an
invoice with total amount = 0.

**Comment by simnandez** [comment]
One invoice with lines but with amount = 0 (ex: with 100% credit note) should be validated

**Comment by braito4** [comment]
I use this constant FACTURE_ENABLE_NEGATIVE

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
