### ISSUE TITLE
Bug: Incorrect log priority when trying to fetch a non-existing customer invoice

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4019]
Version: 3.8.2

If we call Facture::fetch() to retrieve an invoice and the invoice is not found, a message is logged with ERR priority. This is not an error, it is just giving the information that the invoice could not be found… Also a SQL query is logged too and that does not give relevant information in this particular case…

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
