### ISSUE TITLE
Bug: Direct printing module without any driver configured, shows an unformatted error message

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4036]
Version: 3.8.2

Page: htdocs/printing/index.php
![captura de pantalla 2015-11-19 a las 9 01 29](https://cloud.githubusercontent.com/assets/168744/11265383/265f685a-8e9c-11e5-81f0-f6c6813a7fa6.png)

**Comment by rdoursenaud** [comment]
Looks awfully similar to #3236

**Comment by marcosgdf** [comment]
Yep. And it is still present in 3.8.2. So it probably didn't get fixed…
