### ISSUE TITLE
Add an option to prevent free field when products/services is enabled

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4037]
Some companies policy may want to prevent using free form documents and enforce using products and/or services available in the database.
Provide an option to disable free input when products and/or services are available.

**Comment by BebZ** [comment]
@Defrance did a module in this direction. Or it is an option of one of his modules I guess.

**Comment by defrance** [comment]
YES please see customLine, it's Cheap (5€) and use simply jquery for do the job

**Comment by elarifr** [comment]
@defrance, using jquery is a trick that help to change such feature but it can also be reverted using dev tool by an "advanced" user. 
it should be optional (separatly) in products / services module ( and maybe managed by a user permission too ? )

**Comment by defrance** [comment]
They are many native thing who be change by an "advanced" user (quit all edit and delete button by exemple)
Is dolibarr must be soo secure to prevent "advanced" user? I don't know

**Comment by eldy** [comment]
A hidden option was introduced in v10 i think to disable the free entries.
