### ISSUE TITLE
particulier property is unused

### ISSUE THREAD

**Issue by ParisLiakos** [Dolibarr/dolibarr#4042]
When creating a third party, the form asks you whether you want a company or private individual.
No matter what you choose, always company is used.

After digging a bit seems that "particulier" property of societe class is unused.

**Comment by marcosgdf** [comment]
When creating a thirdparty, if you select "particular" a contact is created as well. Probably it should be merged with thirdparty type.

![captura de pantalla 2015-11-20 a las 10 06 31](https://cloud.githubusercontent.com/assets/168744/11295813/6c1dbbd0-8f6e-11e5-9cfc-9fbefea3de11.png)
