### ISSUE TITLE
Crabe PDF template should not issue red messages with a perfectly valid configuration

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4071]
When set to:
![capture d ecran de 2015-11-23 11-19-48](https://cloud.githubusercontent.com/assets/1210367/11334285/5eb2700e-91d4-11e5-87b1-ee784068abde.png)

The result on the PDF should not be:
![capture d ecran de 2015-11-23 11-20-03](https://cloud.githubusercontent.com/assets/1210367/11334288/6100e21e-91d4-11e5-8f4b-a8014928b295.png)

**Comment by marcosgdf** [comment]
I see it like an invalid configuration. You've set up the invoice to be paid by check but Dolibarr has no information of the check details.

**Comment by rdoursenaud** [comment]
This is a perfectly valid configuration. I asked Dolibarr to not suggest a specific address.
My customers are not dumb enough to not know to send their checks at the corporate address in the invoice's header!

Even if this was an invalid configuration, the PDF document is not the right place to display such a message! This should refuse to generate the document and issue the error to an interface notification or something like that, certainly not on the document itself.
Keep in mind that we can generate these documents unattended and that they may not be reviewed before being sent out (i.e. with a script or a cron task). Generating documents with errors embedded in them is insane.

**Comment by marcosgdf** [comment]
I agree that it is not the right place to show that information. And I also agree that if a specific address is not selected, the company address should be used.

**Comment by eldy** [comment]
This occurs when setup is not complete (for example after a migration that introduce the option when it does not exists in previous version).
PR here is request to put the warning when generating document and not into PDF itself.
