### ISSUE TITLE
Credit note for supplier invoice

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#4077]
Hi,

I think this usefull function should be in Dolibarr. Sometimes when You received credit note to supplier invoice we must enter it to the system. Actually this not possible.

**Comment by ndrosis** [comment]
Hi @pat15 

see here https://wiki.dolibarr.org/index.php/Module_Suppliers_Invoices#Example_of_use_cases

**Comment by BebZ** [comment]
Hello, My 2 cents because now when you record a supplier invoice, it is not possible to "re-open" it anymore... It is only possible to clic on "modifier" then you have an error displaying at the top right : 
ErrorDesignIsNotValid

**Comment by atm-maxime** [comment]
Done in late versions
