### ISSUE TITLE
[Organization] Milestones management

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4084]
@eldy @simnandez 

Just a reminder.
If you decide to do a release, could you please move bugs that are still opened on the corresponding milestone to the next milestone. I just moved a bunch from 3.7.2 and 3.8.2…
You can manage milestones at https://github.com/Dolibarr/dolibarr/milestones

A formal community announcement and review a week or two before release would be great. This would give us the opportunity to gather people to help tackle remaining bugs before release.

Thanks!

**Comment by rdoursenaud** [comment]
Oh, and creating the newly released versions labels at  https://github.com/Dolibarr/dolibarr/labels so we can tag bug effectively.

**Comment by eldy** [comment]
I would like to manage milestone github. But it seems it can't be automated.
For issue, we can make a fix #xxx when we make a commit but i do not find a way to automatcally assign a commit to a milestome. If you know a trick for that...
