### ISSUE TITLE
#tags behind all categories in German translation

### ISSUE THREAD

**Issue by low5** [Dolibarr/dolibarr#4085]
see picture
![unbenannt](https://cloud.githubusercontent.com/assets/14179741/11345920/483fba20-921a-11e5-9179-cea3198734fa.PNG)

**Comment by rdoursenaud** [comment]
This is what the de_DE translator choose.
Please subscribe and contribute at https://www.transifex.com/dolibarr-association/dolibarr/dashboard/
Thanks!
