### ISSUE TITLE
Cannot change the date of a contract

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#4088]
Dolibarr Version  : 3.7.2

On this page  /contrat/card.php

We're unable to change the date of contract. We're able to modify the project or ref_supplier but there's no icon to modify the date

**Comment by FHenry** [comment]
https://github.com/Dolibarr/dolibarr/pull/4144

**Comment by FHenry** [comment]
Can't do a PR on 3.7 or 3.8 branch (it will be consider as new feature...)

**Comment by marcosgdf** [comment]
I believe this can be closed as well
