### ISSUE TITLE
Contract date inconsistency between /comm/card.php and 

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#4089]
The llx_contrat table has 2 date fields:  datec and date_contrat

On the main "client" panel ( /comm/card.php ) datec is displayed in the contract box

On the contract card (/contrat/card.php) date_contrat is displayed

**Comment by FHenry** [comment]
https://github.com/Dolibarr/dolibarr/pull/4145

**Comment by marcosgdf** [comment]
I believe this can be closed now
