### ISSUE TITLE
Display the ref_supplier inside the contract list of /comm/card.php

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#4090]
Dolibarr Version 3.7.2

The contract box in the main "client" panel of a company (/comm/card.php)

For Instance the box may contain :
###### 

CT1501-0890  30/06/2015      9 Services
CT1501-0079 28/01/2013  1 Services
CT1411-0142 20/11/2014  3 Services
###### 

The contract ref is hard to understand and I would be easier to display also the ref_supplier filed:
###### 

CT1501-0890  contract_A   30/06/2015      9 Services
CT1501-0079 contract_B   28/01/2013     1 Services
CT1411-0142 contract_Z   20/11/2014     3 Services
######

**Comment by marcosgdf** [comment]
You mean ref. client, right? Contracts are for customers and not for suppliers

**Comment by daamien** [comment]
In the dolibarr 3.7, the field is called ref_supplier  https://github.com/Dolibarr/dolibarr/blob/3.7/htdocs/install/mysql/tables/llx_contrat.sql#L25

The ref_customer was added last month: 
https://github.com/Dolibarr/dolibarr/commit/91a2341e888f1039880b83ab975236147ab18665

Anyway whatever the name of the field, I would be great to have more info in the "contract" box in /comm/card.php

**Comment by FHenry** [comment]
https://github.com/Dolibarr/dolibarr/pull/4145

**Comment by marcosgdf** [comment]
I believe this can be closed now
