### ISSUE TITLE
Add option to allow searching all third parties (Closed/Active)

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4091]
In older versions, the third party search used to return all third parties regardless of their status (Closed/Active).
Newer versions prioritize searching active third parties except if there is a perfect match.
- [ ] Add an option in the third parties module to restore the old behavior.
- [ ] Add a "blank" search option in the third party list to allow searching all third parties.

**Comment by eldy** [comment]
With 3.9, search field active is set to on by default on search into thirdparty list, by you can remove filter if you want to extend search to all.
