### ISSUE TITLE
31 of December at 23:xx as January

### ISSUE THREAD

**Issue by IonAgorria** [Dolibarr/dolibarr#4112]
When using UTC/GM for dol_print_date($time, 'daytext', 1) sets the month name as january instead of december:

Code for reproducing
$last = dol_get_last_day(2015, 12, true);
print dol_print_date($last, 'daytext', true);

At 22:59 the months displays correctly, so probably has something to do with the month name calculation not being correctly set as UTC

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
