### ISSUE TITLE
Impossible to "unactivate" or "deactivate" a contact in Dolibarr 3.8

### ISSUE THREAD

**Issue by jfbaillette** [Dolibarr/dolibarr#4113]
# Problem

Some of the contacts that are retired have to be un or de-activated.
There's no way to de-activate the contact.
Bug reported in 3.6.0
See http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/51513-modification-d-un-contact
# Views where the impossibility was identified
## "Contacts list" view.

![1](https://cloud.githubusercontent.com/assets/3332281/11456084/9a37a1ba-967c-11e5-9887-e270f08931fe.png)
## "Show contact" view :

![2](https://cloud.githubusercontent.com/assets/3332281/11456083/86737b9a-967c-11e5-85e4-6cfc898d0bc6.png)
## "Modify contact" view.

![3](https://cloud.githubusercontent.com/assets/3332281/11456085/a90773fa-967c-11e5-93a4-20262429366c.png)
## "Company" view with the list of contacts.

![4](https://cloud.githubusercontent.com/assets/3332281/11456086/b24ee132-967c-11e5-8aaf-7d35705ed71f.png)

Tks

**Comment by fappels** [comment]
Did you have the disable/enable buttons?

![dolibarr - contacts-adresses 1](https://cloud.githubusercontent.com/assets/4573808/11456186/3bf98e6a-9681-11e5-98b4-971ac015e22e.png)
![dolibarr - contacts-adresses 2](https://cloud.githubusercontent.com/assets/4573808/11456187/428f8c0c-9681-11e5-8a5c-42b5be6f7fdb.png)

**Comment by jfbaillette** [comment]
Working - not intuitive but perfect.
Maybe a new feature : enable/disable contacts directly from the mark "Active" on a single click ?
Tks
