### ISSUE TITLE
[Regression] Password in user card should be hidden

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4121]
It's an industry standard security practice to not display passwords in any circumstances.
I remember having done a patch for that in the past.

Self reminder @rdoursenaud: audit other versions for the same problem.

**Comment by rdoursenaud** [comment]
Can't reproduce…
Sorry for the noise.

**Comment by rdoursenaud** [comment]
Found it again.
At user creation, a clear password is suggested.
The problem is that the field stays clear if we enter a new password.

**Comment by rdoursenaud** [comment]
Suggestion should be done another way to allow secure input of a different password.

**Comment by eldy** [comment]
May be a javascript component can be added: 
As soon as we change one char of the suggested password (clear because user must be able to read it), type for field can be modified into a type "password" instead of "text". Not sure it is possible, but if yes, should be perfect.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by rdoursenaud** [comment]
Still valid!

**Comment by eldy** [comment]
The common use is that the password is suggested by application according to rules (number of char, etc...) in setup.
How the user can communicate password when user is manually created if not visible at least once ?
