### ISSUE TITLE
Add option to not list savings accounts on bank proposition list

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4127]
Parameter in admin/propal.php: BANK_ASK_PAYMENT_BANK_DURING_PROPOSAL
When enabled, an account list is proposed on proposal creation.
This list contains savings account.
Since getting paid on a saving account is not possible, I believe only "standard" accounts should be listed.

**Comment by marcosgdf** [comment]
Well, at least here is possible to get paid in a savings account. Savings accounts allow receiving payments but they do not allow paying through direct debit and some banks, like ING, restrict the receiver of bank transactions.

**Comment by rdoursenaud** [comment]
Ok, this may be a bank by bank policy. Mine certainly does not allow that!
Turning this to a feature request ;)

**Comment by rdoursenaud** [comment]
One nice implementation IMHO would be to add a flag to the account properties that allows or disables receiving payments (as opposed to transfers) on that particular account.
