### ISSUE TITLE
Use "WHERE true" instead of "WHERE 1"

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#4132]
Dolibarr version: 3.7.2
PostgreSQL : 9.5 beta 1

Since we've updated to 3.7, we're getting errors the following error when we try to create a company here: /societe/soc.php?action=create

```
#  SELECT rowid as rowid, login FROM llx_user WHERE 1;
ERROR:  argument of WHERE must be type boolean, not type integer
LINE 1: SELECT rowid as rowid, login FROM llx_user WHERE 1;
```

MySQL may understand "WHERE 1" but it's not the correct way to do this and by default PostgreSQL will refuse to convert an integer into a bool. The WHERE operator must be followed by a boolean statement, so it's better to provide directly a boolean value

**Comment by FHenry** [comment]
My question is why dolibarr need to do WHERE 1 ? ... I'll check

**Comment by FHenry** [comment]
Do you use user extrafeilds ?

**Comment by daamien** [comment]
yes we use extrafields on the user card

**Comment by daamien** [comment]
Fixed
