### ISSUE TITLE
Detail IBAN

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#4135]
Today when printing an account information on a PDF, all details are given (according to country). Shouldn't we use simple IBAN / BIC display for all europeans country ?

See /htdocs/compta/bank/class/account.class.php, function useDetailedBBAN()

**Comment by marcosgdf** [comment]
Agree.

SEPA participating countries can be found at http://www.ecb.europa.eu/paym/retpaym/html/index.en.html

I've done an interesting refactor of the way the details are handled in #4381, so I suggest waiting until that is merged to address this task

**Comment by atm-maxime** [comment]
I close, option PDF_BANK_HIDE_NUMBER_SHOW_ONLY_BICIBAN is available now
