### ISSUE TITLE
Bug: duration in interventions

### ISSUE THREAD

**Issue by vgrioche** [Dolibarr/dolibarr#4141]
# Environment
- **Version**: 3.8.1
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/fichinter/card.php?id=4
# Report

when i want to update an event, the duration is not updatable, so set up to 0

**Comment by marcosgdf** [comment]
Cannot reproduce in 3.8.2.
