### ISSUE TITLE
Cancel edit weight of a shipment give a shipment page without id

### ISSUE THREAD

**Issue by frederic34** [Dolibarr/dolibarr#4142]
![2015-12-03 10_17_41-dolibarr - expedition](https://cloud.githubusercontent.com/assets/3624836/11556495/516e99f6-99a7-11e5-9417-1e0d28a99955.png)
![2015-12-03 10_18_19-dolibarr - expedition](https://cloud.githubusercontent.com/assets/3624836/11556497/53b10d84-99a7-11e5-9ef2-a4d70964f0b1.png)

**Comment by marcosgdf** [comment]
Cannot reproduce in latest develop version. Also, please do not report bugs when using MAIN_FEATURES_LEVEL higher than 0 as the message in the screen says.
