### ISSUE TITLE
Warning: mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50546 Library:50627 in ...htdocs/core/db/mysqli.class.php on line 196

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#4143]
Branch Devellop
Ubuntu 14.04 
php 5.5.9
mysql 5.6

**Comment by rdoursenaud** [comment]
Sounds like a local problem on your computer.
Check that mysql and mysql-client are the same version and use PHP's mysqlnd driver.
See:
https://www.dotdeb.org/2014/04/04/about-the-mysql_connect-headers-and-client-library-minor-version-mismatch-warning-2/
https://stackoverflow.com/questions/10759334/headers-and-client-library-minor-version-mismatch
https://mariadb.com/kb/en/mariadb/installation-issues-with-php5/

**Comment by FHenry** [comment]
solve by sudo apt-get install php5-mysqlnd
more information https://www.skyminds.net/mysql-resoudre-lerreur-mysql_connect-headers-and-client-library-minor-version-mismatch/

**Comment by FHenry** [comment]
@rdoursenaud Yes true, local problem, use of php5-mysqlnd solve problem

**Comment by rdoursenaud** [comment]
Glad to read that.
mysqlnd is awesome anyway ;)

**Comment by rahulpiana** [comment]
if i install php5-mysqlnd.. have i to install phpmyadmin again?

**Comment by rdoursenaud** [comment]
@rahulpiana please refrain from resurrecting (very) old issues for support requests.
You'd be better use the forums at dolibarr.org.
Thanks for your understanding.

**Comment by blickrichtung** [comment]
switch to php  5.6.x from 5.5
