### ISSUE TITLE
Prevelement file - wrong text in reference

### ISSUE THREAD

**Issue by ram111** [Dolibarr/dolibarr#4151]
3.8.2
When creating a prevelement file (SEPA) with many lines from different invoices, in the file it generates, the <Ustrd> tag (which is reference text that is seen by the client on the bank charge) on the file contains all the invoices comma separated.
This is wrong because each line belongs to an invoice, and it can be the case that each line may belong to an invoice of a different client.

Please correct me if I'm wrong but to solve it I just modified the line 1312 on bonprevelement.class

```
$fileDebiteurSection .= $this->EnregDestinataireSEPA($obj->code, $obj->nom, $obj->address, $obj->zip, $obj->town, $obj->country_code, $obj->cb, $obj->cg, $obj->cc, $obj->somme, $ListOfFactures, $obj->idfac, $obj->iban, $obj->bic, $this->db->jdate($obj->datec), $obj->drum);                                           
```

to:

```
$fileDebiteurSection .= $this->EnregDestinataireSEPA($obj->code, $obj->nom, $obj->address, $obj->zip, $obj->town, $obj->country_code, $obj->cb, $obj->cg, $obj->cc, $obj->somme, $objfac->fac, $obj->idfac, $obj->iban, $obj->bic, $this->db->jdate($obj->datec), $obj->drum);                                        
```

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
