### ISSUE TITLE
Search Categories error

### ISSUE THREAD

**Issue by javieralapps4up** [Dolibarr/dolibarr#4155]
3.8.1, 3.8.2 and development version

In categories/class/categorie.class.php there is a mistake.

Function rechercher, where $type = $map_type; must be: $type = $map_type[$type];

(I think)

**Comment by marcosgdf** [comment]
Can you please explain why there is a mistake there? Where do you experience the problem?

**Comment by javieralapps4up** [comment]
Version 3.8.1 or development, go to thirdparty - categories. Type something in "search" and press button.

I see a error message (several).

En español, (sorry). Marcos, si activo el módulo categorías, me creo algunas (de clientes, por ejemplo) y uso el campo "Buscar", me da un error. He comprobado que si cambio la línea que digo, el error desaparece y busca la categoría correctamente.

$map_type es un array y nunca será igual a $type, que es un cadena (o un entero).

**Comment by marcosgdf** [comment]
Next time please paste the errors :)

```
( ! ) Warning: Illegal offset type in /var/www/dolibarr/htdocs/categories/class/categorie.class.php on line 1304
Call Stack
#   Time    Memory  Function    Location
1   0.0004  244352  {main}( )   .../index.php:0
2   0.1182  2514504 Categorie->rechercher( )    .../index.php:105

Encontradas etiquetas/categorías
( ! ) Warning: Invalid argument supplied for foreach() in /var/www/dolibarr/htdocs/categories/index.php on line 111
Call Stack
#   Time    Memory  Function    Location
1   0.0004  244352  {main}( )   .../index.php:0
```
