### ISSUE TITLE
3.8.0 - Cosmetics Bank Account screens

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#4158]
Pls. find attached a patched version of 3.8.0 htfocs/societe/rib.php 

(Neither drag 'n drop nor Select worked to include zipped code. Pls. advise)

This is a proposal - and very much a shot from the hip, because I could not find an easy way to include CSS in the tables (w/o editing the characteristics of each and every field).

Better solutions are welcome ;-)
- Fixed screen estate isues
- Fixed differentiation between Labels and Input-Fields (same strategy is used here on all screens / cards /fichiers)

**Comment by aspangaro** [comment]
Sorry. You have forgotten the attachement

**Comment by casati-dolibarr** [comment]
That's why I've added "Neither drag 'n drop nor Select worked to include zipped code. Pls. advise". 
According to THIS editor we are currently using, attaching files should work - but doesn't. And because it's more a proposal than an educated code change yet, I deliberately don't wan to use the (complicated) Github code insertion process.

**Comment by BebZ** [comment]
Really complicated ? but widely shared to not miss any issues with compatibility. I think the devs Won't accept modifications done without github code insertions. 
Just fork on develop version,  modify your branch, and Pull Request on dev branch... is that so complicated ?

**Comment by casati-dolibarr** [comment]
> is that so complicated ?

For the kind of info I wanted to exchange: Yes.
Again: THIS Editor here, allows for "Attach files by dragging & dropping or ...", BUT THIS didn't work for .zip

![Uploading Selection_804.png…]()

And doesn't work for .png too.

**Comment by rdoursenaud** [comment]
@casati-dolibarr ZIP attachments are not supported on GitHub. PNGs should work though: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
If you don't want to be bothered with a pull request (don't know what code insertion is…) I advise that you use our developper mailing list: https://lists.nongnu.org/mailman/listinfo/dolibarr-dev to post your RFC.
Thanks.

**Comment by casati-dolibarr** [comment]
> PNGs should work though

That's what I've tried. Are there size-constraints?

I'll set-up GIT now ...

**Comment by rdoursenaud** [comment]
Not that I'm aware of. You can also try copy-pasting your image.

**Comment by casati-dolibarr** [comment]
This IS copy & paste

![Uploading Selection_805.png…]()

**Comment by braito4** [comment]
you can use a online service like https://gyazo.com/ to share screenshots

**Comment by rdoursenaud** [comment]
@casati-dolibarr You seem to have something wrong going on with your browser's javascript support and GitHub. Nothing we can do here. Please contact the GitHub support team: https://github.com/contact
