### ISSUE TITLE
3.8.0 - Irritating behaviour in Bank Account

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#4160]
From Third Party choose Bank Account.

Outermost right Tab is "Sales representative" and below is a user list.

The irritation arises because an arrow is displayed too, which by onclick changes the Third Party.

Is this an intentional behavior and why?

**Comment by BebZ** [comment]
http://demo.dolibarr.org/societe/rib.php?socid=777

u mean here ?

Where is the arrow ? can u make a screen capture and paste it here ?
i use screen capture of windows and paste no need to save it n computer

**Comment by casati-dolibarr** [comment]
It's a PITA that neither pasting, dropping or selecting a .png file works:

> Something went really wrong, and we can’t process that file. 

Therefore I attached my screnshots to the URL you've supplied (Linked Files)

2nd picture is after pressing left arrow

**Comment by BebZ** [comment]
It is not the intended behaviour ?  You click an arrow and you switch the third.
What behaviour u expected?

**Comment by casati-dolibarr** [comment]
> What behaviour u expected? 

That it is only possible when in "Card". Because if you hit the arrow in error (say you are a clerk, distracted by a phone call) and leave the Sales Representative screen to add an account afterwards, it will be connected to the wrong Third Party - unless you recognize you are in error immediately ...

**Comment by casati-dolibarr** [comment]
Will reopen as Bug.
