### ISSUE TITLE
3.8.2 -Setup Module Members misses Product for Subscription

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#4163]
- during Setup of Modules.

User will Setup from Top to Bottom.

As an example *): He will NOT be aware, that after he enabled Products below, an additional option will be enabled in Members Module Setup.

PR: During Setup such "dependent fields" should be displayed too (although greyed out).

So customer is aware of such option. An additional pictogramm or an info message is required then. 

*) Other parts of Module Setup are effected as well eg.:

Products: "Visualization of products descriptions in the thirdparty language" 

is only visible if Multilanguage in Setup -> Display has been choosen already

**Comment by marcosgdf** [comment]
This looks more like a Feature Request than a bug… I don't really think this is possible as the user can be overwhelmed by so many fields that depend on other modules… Also, because the behaviour can be modified by external modules this can be a little bit confusing…

**Comment by casati-dolibarr** [comment]
Could we have an information/warning box like:

"Your choice made additional options in Setup available. Pls recheck your Dolibarr Setup!" 

once triggered by a user action?

PS: Certainly you are right as long as Dolibar Partners setup the customer's installation. The described issue wont't occur.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
