### ISSUE TITLE
BUG 3.8.0 - WAS: Irritating behaviour in Bank Account #4160

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#4167]
Missing entry for displaying
- Third Party
- Navigation

**Comment by marcosgdf** [comment]
Can you please explain the issue?

**Comment by casati-dolibarr** [comment]
Throughout Dolibarr the navigation arrows are displayed e.g. to switch between Third Parties etc. easily w/o leaving the actual canvas (say Supplier Card, Personal Data Card etc.) 

This is not the case with Third Party Bank Accounts Card.

That led me to the wrong perspective on the problem in #4167.

So: My initial impression of "erroneously allowing to switch between Third Parties" is wrong - BUT "not displaying Third Party Name and the navigation arrows" in the Bank Account card is a BUG, because it is missing a programm part, used everywhere else.

Best regards

**Comment by marcosgdf** [comment]
To me it looks like a Feature Request. But good news is that it is working in the next 3.9 release.
