### ISSUE TITLE
Invoice edit

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#4180]
In older version i can edit validated invoice - now i look on this (i must change payment term) and there's no edit option
![invoice_no_edit](https://cloud.githubusercontent.com/assets/6292835/11639719/be828d24-9d2e-11e5-8290-7328a6ee1ce8.png)

**Comment by marcosgdf** [comment]
Version? Can you edit other invoices? Have you got enough permissions?

**Comment by pat15** [comment]
I have newest version 3.8.2 - i have admin permission for all items. I try with 3 different invoice - all the same - can't edit ;/

**Comment by marcosgdf** [comment]
Try removing and applying permissions again and see if anything changes…

**Comment by pat15** [comment]
I remove all invoice permission and apply all - without change ;/

**Comment by marcosgdf** [comment]
Could it be related to some external module?

The conditions the button is shown are:
- Status = Valid (without any payment)
- If the amount remaining to pay is equal to the invoice total
- Not exported to accountancy
- If the invoice is not corrected by another one
- Something related to cycles (sorry, I don't really know what it is)
- Enough permissions to create invoices or to invalidate them

**Comment by pat15** [comment]
When i update to 3.8.3 - problem disappear :)

**Comment by marcosgdf** [comment]
Great. Can you please close the issue then?

**Comment by vp1985** [comment]
I had a similar problem. I can't edit any valid invoice. The edit button shows "This invoice in not the last in cycle and must not be modified.".
I solved this Problem for me by deleting the if query in htdocs\compta\facture.php:

Deleted Lines:
if (! $objectidnext && $object->is_last_in_cycle()) 
                    {

} else if (!$object->is_last_in_cycle()) {

Does someone know something about this feature?
Or something about "Situation Invoice"?

I can't find a description about this.
