### ISSUE TITLE
Bug: Help inline from left menu is no more displayed

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#4184]
# Environment
- **Version**: 3.9.0-beta
- **OS**: Windows NT
- **Web server**: Apache/2.2.22 (Win64) PHP/5.4.3
- **PHP**: apache2handler 5.4.3
- **Database**: MySQL 5.5.24-log
- **URL**: /dolibarr_dev/admin/ihm.php?mainmenu=home&leftmenu=setup
# Report

**Comment by marcosgdf** [comment]
Can you please explain the issue?

**Comment by grandoc** [comment]
Hello Marcos
Help is now on right top, I have found it.

**Comment by BebZ** [comment]
+1

**Comment by marcosgdf** [comment]
Haha. Then can you please close the issue?
