### ISSUE TITLE
E-mails templates substitutions not work in 3.9 (from german forum)

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#4187]
here the post http://www.dolibarr.de/forum/bugs-fuer-development-oder-demo-versions/52118-angebot-per-e-mail-versenden-textvorlagen-fuer-emai#55762

It seems that only FACREF and SIGNATURE are replaced, other fields not.
A core or a translation issue ?

**Comment by atm-maxime** [comment]
Hi @tiaris 

After checking, other fields are available too.
__CONTACTCIVNAME__ is ok when you select a Billing Contact in the contact tab.
