### ISSUE TITLE
DoliBD, wrong limit implementation

### ISSUE THREAD

**Issue by sugenganthos** [Dolibarr/dolibarr#4188]
I see plimit function in database.interface.
This should be implemented in driver.class instead of doliDB.class.php
The LIMIT and OFFSET syntax is different between MySQL and pgSQL

dolibarr 3.8.2
PHP 5.6.15 with mysql, mysqli, sqlite3, and PDO support
MySQL 5.7.9

**Comment by eldy** [comment]
The plimit function as a default implementation into DoliDb.class.php but is correctly defined into the pgSQL driver. So everything looks good to me.

**Comment by sugenganthos** [comment]
MySQL syntax : LIMIT offset,numberOfLine
PostgreSQL : LIMIT numberOfLine OFFSET offset
That is according to Postgre and MySQL manual.

I'm sorry... looks like it because i'm not fully aware of PHP OOP features.
Actually it doesn't matter. If I need to create another plimit, I just create new function in pgsql.class, it will override the one in DoliDB.class
