### ISSUE TITLE
HTML5 input types

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4193]
HTML5 provides a bunch of new input types that could be leveraged to provide a better interface for Dolibarr: http://www.w3schools.com/html/html_form_input_types.asp

Explore the possibility of migrating relevant fields to them while maintaining backward compatibility.

**Comment by eldy** [comment]
Some new html5 were introduced recently (type of input field, required, ...)
Html5 is now new standard for dev so we can close bug.
