### ISSUE TITLE
virtual in llx_product is keyword

### ISSUE THREAD

**Issue by sugenganthos** [Dolibarr/dolibarr#4195]
Hello,
I'm failed installing dolibarr 3.8.2 at llx_product table. I found out that column name "virtual" is a keyword for MySQL, therefore it should not be used as column name. I change the name and installed successfully. But this break other modules (i'm not using it at the moment).

dolibarr 3.8.2
mysql 5.7.9

**Comment by eldy** [comment]
Fixed for 3.9
