### ISSUE TITLE
Command line upgrade should update MAIN_VERSION_LAST_UPGRADE

### ISSUE THREAD

**Issue by cbrunet** [Dolibarr/dolibarr#4202]
Dolibarr 1.8.0, 1.8.1, 1.8.2...

When performing upgrade from command line (using upgrade.php and upgrade2.php), configuration variables are not updated in the database (usually performed by step5.php in the upgrade wizard). Therefore, Dolibarr does not know it was upgraded, and shows the upgrade wizard when I log into the web interface.

The command line upgrade should also upgrade those conf variables.

**Comment by eldy** [comment]
In fact step5.php should be rename into installorupgradeend.php and include this script ran as command line into upgrade process.
I will update doc to mention this

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
