### ISSUE TITLE
Fields are not checked properly when adding and updating lines

### ISSUE THREAD

**Issue by IonAgorria** [Dolibarr/dolibarr#4204]
Some pages don't check fields properly or don't do any check when updating a line, the check should be consistent with the checks when adding a line.

Which speaking of adding lines, quantity is not checked for negativity or zero some pages, some other pages don't inform correctly the "wrong" fields or don't show any error at all.

Some common code for checking all the fields across pages would reduce all this mess...

Affected:
- Proposals
- Client order
- Supplier order
- Supplier invoice
- ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
