### ISSUE TITLE
invoice reference

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4218]
If I create invoice from order, all % gain are right!
Instead if I create customer invoice from shipping all % gain = 0
And it would be better in custoemr invoice to have customer invoice related to shipping

**Comment by marcosgdf** [comment]
Version? Also... could you please explain it a little bit more? I don't really understand

**Comment by WhiteCarcosa** [comment]
I'm having the same issue. I'm running dolibarr 3.9 and when an invoice is created from shipping document (instead of an order) the cost price = the sell price. The margins are therefore 0% and the sales reports are skewed.

**Comment by marcosgdf** [comment]
Can you please then open a separate issue? They might be related but not the same bug

**Comment by WhiteCarcosa** [comment]
Done. See #4964 

Thanks. Hopefully this is an easy one.
