### ISSUE TITLE
auguria line on llx_menu not suppress when menu change

### ISSUE THREAD

**Issue by defrance** [Dolibarr/dolibarr#4225]
when we change menu to auguria we add many line on llx_menu table
but when we change again menu to eldy the line stay on llx_menu table
propose to delete auguria line when auguria menu is no more active

**Comment by eldy** [comment]
The erase is done when going back to auguria in setup.
What will be the benefit to delete when we leave the menu handler ?

**Comment by defrance** [comment]
No the auguria line stay on llx_menu : 
1 - change to auguria menu: line are create
2 - return to eldy menu : auguria line still present
3 - when i add new menu i have a problem to détermine the fk_menu value on lookin on llx_menu

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
