### ISSUE TITLE
Bug : incorrect VAT when delivering in origin country

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#4241]
Example : 
A customer wants to be invoiced in switzerland but delivered in France (customs...)
I must register the sale with VAT on the products.
My Thirdparty is registered in Switzerland (Headquarters) with "subject to VAT" to YES
My Contact for delivery, and suivicommande is in France

> problem : when I add a line on his order, the product registers with VAT 0% by default.

So, even if the Thirdparty is abroad, when contact for delivery is in France, order should be subject to VAT.

**Comment by eldy** [comment]
Not really a bug. Dolibarr does not include all rules to define vat (there is an infinite case). Only few to have default vat set correctly in most cases but it is role of user to set the correct vat depending on situation.
But may be an enhancement of default vat calculation.
