### ISSUE TITLE
Bug 3.9 multiprice VAT not stored in product_price

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#4255]
VAT from product with multiprices not added by default when adding to customer orders/proposals/invoices. 
Should be stored in product_price table or product object fetch should be adapted to read vat from product table.

**Comment by eldy** [comment]
By default with 3.9, there is on vat for all customer prices.
To have vat for each price, you must enable option PRODUIT_MULTIPRICES_USE_VAT_PER_LEVEL. Does you problem is with this option on ?

**Comment by fappels** [comment]
The problem seems to be that the common vat for all multiprices is not added to the lines.
With this option on it works, but on < 3.9 it also worked with the common vat.
