### ISSUE TITLE
Bug : Total customer invoice in bottom of page

### ISSUE THREAD

**Issue by lucasgehin** [Dolibarr/dolibarr#4258]
Total of customer invoices list not displayed in the bottom of the page when there is more than 1 page.

**Comment by marcosgdf** [comment]
Version?

**Comment by lucasgehin** [comment]
3.8.2

**Comment by marcosgdf** [comment]
This is an expected behaviour and not a bug. You can access the total amount of invoiced services through Financial > Reports menu
