### ISSUE TITLE
Include join files of emails into saved actions (3.8)

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#4263]

**Comment by tiaris** [comment]
If you sen a mail with a joined document, and if you activate the automatic creation o action (COMPANY_SENTBYMAIL), action is created, bud joined document is not saved on action.

**Comment by eldy** [comment]
Currently, joined files are not saved on the actions (whatever is the way action is created, automatic or from the "send by email" button of object).
This is a feature request to develop.
