### ISSUE TITLE
issue when try print by customers product list

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4272]
Dolibarr ha rilevato un errore tecnico.
Si tratta di informazioni utili alla diagnostica:
Data: 20151222095550
Dolibarr: 3.8.2
Livello di funzionalità: 0
PHP: 5.6.16
Server: Apache
OS: Linux 100asa.it 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

URL richiesto: /societe/consumption.php?optioncss=print
Referer: http://erp.100asa.it/societe/consumption.php
Gestore dei menu: eldy_menu.php

Gestore del tipo di database: mysqli
Richiesta dell'ultimo accesso al database in errore: Nessuna richiesta in errore
Codice di ritorno per ultimo accesso al database in errore: Nessuna richiesta in errore
Informazioni sull'ultimo accesso errato al database: Nessuna richiesta in errore

Why I can't print the product list by customers sheet?

**Comment by rdoursenaud** [comment]
Could you please describe what you were trying to do? (Pages visited, actions performed, expected results…)
This page is supposed to be called with a 'socid' parameter that seem to be missing from your request but we can't assess what's gone wrong without context.
Thanks!

**Comment by centoasa** [comment]
See this screenshot:
https://www.evernote.com/shard/s272/sh/86adbce3-7fd1-470e-8756-b9172c9ec90d/251b25f03f2aa786c71bf745f8304b8a
from customer, reference object, product lists

**Comment by rdoursenaud** [comment]
Can't reproduce on a clean 3.8.2 install.
Could you please give us the URL you have on the print button when on that page?

**Comment by centoasa** [comment]
http://erp.100asa.it/societe/consumption.php?optioncss=print

**Comment by marcosgdf** [comment]
Works for me as well in 3.8.1, 3.8.2 and latest 3.8 code.

**Comment by centoasa** [comment]
please, see my video:
https://youtu.be/6zXGUJIJSKE

**Comment by marcosgdf** [comment]
Next time please describe all the steps to get to the bug because you didn't mention that you searched for some kind of object in the page.

Now I could reproduce it.

**Comment by centoasa** [comment]
sorry, it's right!

**Comment by centoasa** [comment]
on 3.8.3 release still this issue
Dolibarr ha rilevato un errore tecnico.
Si tratta di informazioni utili alla diagnostica:
Data: 20160102123131
Dolibarr: 3.8.3
Livello di funzionalità: 0
PHP: 5.6.16
Server: Apache
OS: Linux 100asa.it 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

URL richiesto: /societe/consumption.php?optioncss=print
Referer: https://erp.100asa.it/societe/consumption.php
Gestore dei menu: eldy_menu.php

Gestore del tipo di database: mysqli
Richiesta dell'ultimo accesso al database in errore: Nessuna richiesta in errore
Codice di ritorno per ultimo accesso al database in errore: Nessuna richiesta in errore
Informazioni sull'ultimo accesso errato al database: Nessuna richiesta in errore

**Comment by marcosgdf** [comment]
@centoasa 3.8.3 has been released before fixing the error

**Comment by rdoursenaud** [comment]
Screencasts FTW \o/
(Sorry, couldn't resist…)

**Comment by djouonang** [comment]
Hello

am having a problem trying to get the direct printing module to work with google cloud print. I have succeeded in getting the google secret id in place now to give authorisation to google to access the application each time i give the authorisation nothing changes it still says no token saved into local database. 

What could i be doing wrong

**Comment by marcosgdf** [comment]
@djouonang Please post a new topic in the forum or a new bug, this one has been resolved.
