### ISSUE TITLE
FR: Colorize Calls, Meetings, Todos by event type

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#4276]
Eventually for priority as well.

Anticipated problem: External calendars with their own color schemes.

**Comment by eldy** [comment]
It seems with 3.8, setting a color on event type is already available.

**Comment by casati-dolibarr** [comment]
Setting a user-defined event with a color in 3.8.2 ist not honored (tried 'red' and '#FF0000').

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
