### ISSUE TITLE
services issue

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4278]
When services come from proposal, when became an order service changes as a product, and order is not shippable because service is signed as low stock
https://www.evernote.com/shard/s272/sh/fbdc30ab-ed3d-4cdf-bb66-83664b52f387/b14dc26889df062d375f242c29a9e067

**Comment by marcosgdf** [comment]
Version?

**Comment by centoasa** [comment]
3.8.2

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
