### ISSUE TITLE
module Google Cloud Print

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4279]
I've a printer installed and working on Google Cloud Print, but the dolibarr module say me no printer in module Google Cloud Print.

**Comment by marcosgdf** [comment]
Version?

**Comment by centoasa** [comment]
3.8.2

**Comment by eldy** [comment]
Some changes were done into 3.9. I suggest to wait it to see if it is now fixed for you.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
