### ISSUE TITLE
stock provisioning bug

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4283]
as you can see in image attached, on 3.8.2 release when virtual stock is negative (-2) and product is coming (2) the qty suggested is 0; instead it must be 2 ! 
https://www.evernote.com/shard/s272/sh/e572db4c-9242-419e-9b4c-bef9e35fdcbd/4f17b8d5ef82321dcce5b56b9f0f2172

**Comment by BebZ** [comment]
It must be 2 because you have customer orders for 4 units and supplier order for 2 units  ?
So you mean you will theoretically miss 2 items in stock to be sold later ?

**Comment by centoasa** [comment]
It's right: I've 4 pcs in customers order and 2 in supplier order. So the restock module maybe suggest me 2 pcs to buy

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
