### ISSUE TITLE
HTML Injection not filtered correctly

### ISSUE THREAD

**Issue by naxonez** [Dolibarr/dolibarr#4291]
Hi,

You have a html injection in field "url" from the external calendar. You only need to edit the url parameter like: http://">< h1>injection< /h1> to see the html injection.

Regards

![untitled](https://cloud.githubusercontent.com/assets/7959568/11996942/55132300-aa6f-11e5-92f8-b9f626517b6a.png)

I see others fields like the bank name that is suceptible to html injection because all fields are not correctly parsed to avoid this issue:

![image](https://cloud.githubusercontent.com/assets/7959568/12004314/c7575e00-ab4f-11e5-81ab-5a258fdf0793.png)

**Comment by naxonez** [comment]
The injection is with http:// like this:

Http://">< h1>injection< /h1>

Sorry for mistake

**Comment by rdoursenaud** [comment]
Well, except it is not saved (If you refresh the page, the field is empty). No big deal.
Will push a patch anyway since this shouldn't hit the page in the first place.
Thanks!
