### ISSUE TITLE
Cron tasks do not run as expected if task runtime is high

### ISSUE THREAD

**Issue by fmarcet** [Dolibarr/dolibarr#4314]
# Environment
- **Version**: 3.6
# Report

For example, we have a cron task that must be executed every day at 9:00 AM. The first day it is executed (function run_jobs) at 9:00 AM and then it is reprogrammed (function reprogram_jobs) for the next day. If the execution time is, for example, three seconds, the next run is reprogrammed to 9:00:03 AM. So the second day, the cron is launched again at 9:00AM but the task is not executed because 9:00 < 9:00:03. The task will not be executed until the third day

I think there are two possible solutions:
1.- In checking before run tasks, reset seconds to zero to not consider delays by runtime.
2.- In reprogram_jobs function, reset seconds to zero to not consider delays by runtime.

**Comment by eldy** [comment]
If script start at 9:00, next run should be next 9:00 whatever is duration of script.
If fixed for 3.9
