### ISSUE TITLE
Configuration for showdetails for page footer in pdf generation

### ISSUE THREAD

**Issue by srehlig** [Dolibarr/dolibarr#4331]
The parameter showdetails of function `pdf_pagefoot`in pdf.lib.php is always 0. It is called from all PDF templates in function `_pagefoot`. Would it make sense to make the value configurable for all PDF documents?

**Comment by eldy** [comment]
Why not.
We could replace $showdetails = 0  
with   $showdetails = $conf->global->PDF_SHOW_COMPANY_DETAILS_IN_FOOTER ? $conf->global->PDF_SHOW_COMPANY_DETAILS_IN_FOOTER : 0

**Comment by yehanny** [comment]
Hi eldy, this solution is great but what if I want to show only FREE TEXT without footer? Thanks!
