### ISSUE TITLE
Feature request: send email button also for draft

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4342]
Send email button should be enabled also for draft document, so operator can send to customer draft document for approve it!

**Comment by marcosgdf** [comment]
There is a hidden constant for that. FACTURE_SENDBYEMAIL_FOR_ALL_STATUS

**Comment by centoasa** [comment]
This hidden constant is valid also for customer/supplier orders?

**Comment by marcosgdf** [comment]
Woops. I guess not. I agree it would be interesting to have that option available

**Comment by centoasa** [comment]
You can assign this thread as enhancement

**Comment by ghost** [comment]
Also for invoiced proposal
