### ISSUE TITLE
Feature Request: drop shipping visible on PDF

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4345]
For drop shipping, when I select third parties contact address for shipping, should be another box on pdf document
1st box left: dolibarr company
2nd box right: invoice customer/supplier
3rd box right: recipient products/services

**Comment by BebZ** [comment]
please post a screenshot ! ? 
Drop shipping is when you order to your supplier to deliver directly to your customer.
Is it this cse you are talking about ? 
So you suggest to add a box with a THIRD party to deliver on the Supplier's oreders, isn't it ?

If it is so, it needed more precise informations to be understood.

**Comment by centoasa** [comment]
it's all right!
or maybe more simply to have the company data in the header of pdf document, and 2 box with supplier at left and customers shipping address to right
