### ISSUE TITLE
BUG: Auguria Theme: in list display, not see category when selected

### ISSUE THREAD

**Issue by benlo06** [Dolibarr/dolibarr#4348]
Since dolibarr 3.8 

This bug is with  Auguria Theme. When I list products (/product/list.php) or list invoices, when I selected category, it display in white color in white background :/,

**Comment by eldy** [comment]
Theme is abandonned with 3.9, so i am not sure this will be fixed.

**Comment by benlo06** [comment]
Ok, no problem. I have fix this:
---/htdocs/theme/auguria/style.css.php  2016-01-07 11:06:01.856996385 +0100
**************\* div.ecmjqft {
**\* 2472,2477 ****
--- 2472,2479 ----
  a span.select2-chosen
  {
    font-weight: normal !important;
- /\* BLT */
-         color: #000;
  }
  .select2-container .select2-choice {
    background-image: none;
