### ISSUE TITLE
negative value for free input

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4351]
When add a negative value for price (ie occasional discount ) for free input, dolibarr show me error for qty and price; input the same positive value, that's ok, and after can change to negative.
Also negative value for price should be permitted.

**Comment by marcosgdf** [comment]
It is not allowed because standard invoices cannot have a negative amount.

**Comment by centoasa** [comment]
But if I add default row on invoice with positive amount, and after change this value in negative amount, invoice works well and the total is right!

**Comment by marcosgdf** [comment]
Well, that should be reviewed. But I think discounts are managed through the "Discounts" tab in the thirdparty

**Comment by centoasa** [comment]
Example: on customers order I add a special discount for first purchase, example 5 euro
So into order I must to add -5
Una tantum
