### ISSUE TITLE
invoice supplier bank account

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4353]
On supplier invoice, when no bank account is selected, dolibarr choose the first bank on bank account list and related invoice to this account. (3.8.3 release)

**Comment by eldy** [comment]
I can't reproduce with 3.8.3. Can you provide a screenshot ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
