### ISSUE TITLE
Validate phone numbers and always store international format

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4361]
https://packagist.org/packages/giggsey/libphonenumber-for-php provides a very handy way to validate and parse phone numbers.

Validating and storing them in international format would ensure that the data is coherent and clicktodial works every time.

This can also be leveraged to improve the UI and provide a user-friendly way of inputting international phone numbers (a la Google Contacts) with cute flags and all.

**Comment by vendeka** [comment]
I would love to have this feature.
