### ISSUE TITLE
Make shipment easier to understand

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4365]
[X] Store id of order line in shipment
[X] Add list of shipments and qty on each line of detail on the tab "shipments" of order and when we clic we see id/nb and date of other shipments
[X] remove the area "other shipments"
[] Add a status "shipped" instead validated (1) and shipped (2)      (new status will be 2 and billed to 0)

**Comment by BebZ** [comment]
Where do you plan to detail this "already shipped" ? 
on pdf ? or on the screen o the shipment linked to the order ?

If you want to add a field "order ref" on the line of shipment detail, 
does it mean you plan to make available shipping from multiple orders from a same customer ?
where is the area other other shipments ?

**Comment by eldy** [comment]
@BebZ  Yes, by adding the missing id, in a future it should be possible to have one shipment for several orders.

**Comment by BebZ** [comment]
Thanks for your answer Eldy I would love to see this one day...
Planned in a near future or just a project waiting for volunteers ?
Or waiting for finance ?

**Comment by AlbioB** [comment]
Hi @eldy ,
our firm would need this feature in order to start using Dolibarr.
Do you think we'll be available in the near future?
Thanks
