### ISSUE TITLE
NEW: Add hook in propals to rewrite propal_prepare_head

### ISSUE THREAD

**Issue by benlo06** [Dolibarr/dolibarr#4368]
Hello,
I have write a module who create propals, and for this propals I notes this propals with special demand_reason_id .
I would like if user open this propal I display specific tabs only if demand_reason_id field is set to my special value.
I would like use  complete_head_from_modules to rewrite tabs but, it is not possible to rewrite tab with condition on current object.

I would like to add hook to modify $head values in function of propal.

Regards,

**Comment by BebZ** [comment]
Ask @Defrance he has a module to manage custom tabs ;)
Maybe he has implemented hooks inside ?

**Comment by defrance** [comment]
better way is to use $reshook=$hookmanager->executeHooks('printTabsHead',$parameters);
in function in core/lib/functions.lib.php near line 835
in your way just an additionnal jquery script who hide your additionnal tabs

**Comment by benlo06** [comment]
Yes,
I dont see this hook before, it is perfect.
