### ISSUE TITLE
Bug: Delivery order and date are not displayed 

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#4372]
# Environment
- **Version**: 3.9.0-beta
- **OS**: Windows NT
- **Web server**: Apache/2.2.22 (Win64) PHP/5.4.3
- **PHP**: apache2handler 5.4.3
- **Database**: MySQL 5.5.24-log
- **URL**: /dolibarr_dev/livraison/card.php?id=1&action=confirm_valid&confirm=yes
# Report

Delivery order and date are not displayed within Shipments and receivings for this order.
And when you click on Shipment card tab, delivery card tab disappears

**Comment by eldy** [comment]
I can' t reproduce.
Can you reproduce on demo.dolibarr.org and provide link to page with missing display

**Comment by grandoc** [comment]
```
Salut Laurent

va sur ce lien :
```

http://demo.dolibarr.org/livraison/card.php?id=135&action=confirm_valid&confirm=yes
    j'y ai reproduit le problème.
    1) il n'y a rien de marqué en bas sous Bon de réception, et date de
    livraison.
    2) Si tu clic sur l'onglet "Fiche expédition" tu vois disparaitre
    l'onglet "Fiche réception" sans moyen de retrouver le BL, sauf à
    faire un retour page en arrière.
    @+
    Philippe

```
Le 13/01/2016 18:51, Laurent
  Destailleur a écrit :


  I can' t reproduce.
    Can you reproduce on demo.dolibarr.org and provide link to page
    with missing display
  —
    Reply to this email directly or view
      it on GitHub.









-- 








          Philippe GRAND
                ATOO.NET
                SIREN 432 991 636 - APE 6202A
                E-mail : philippe.grand@atoo-net.com
                GSM : 06 80 22 33 18 
                Tel : 02 38 63 90 20
                Web : http://www.atoo-net.com
```

**Comment by eldy** [comment]
Fixed into 3.9 and develop
