### ISSUE TITLE
Products stats

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4391]
![image](https://cloud.githubusercontent.com/assets/5500935/12222354/4fe5c2fe-b7ba-11e5-8bb2-45a0c63eb9a2.png)
Sorry, but on products stat there are only products on proposal: stats for products shouldn't show best seller products or most seller?

**Comment by marcosgdf** [comment]
This place is for bug reports or feature requests… Please refer to the french forum at dolibarr.fr if you want to clear any doubts

**Comment by centoasa** [comment]
This mine is a feature request, because dolibarr don't seems have a products stats.

**Comment by centoasa** [comment]
Please close this bucause report is on comta area! Thank you
