### ISSUE TITLE
Bug: Date filter in customer invoices show future years

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4395]
Version: 3.7.2

We shouldn't be able to filter by future invoices as that doesn't make much sense…

![captura de pantalla 2016-01-11 a las 11 21 21](https://cloud.githubusercontent.com/assets/168744/12231143/98081a32-b855-11e5-9350-b6e6312edb69.png)

**Comment by atm-maxime** [comment]
Hi @marcosgdf ,

Is it really that annoying ?

**Comment by marcosgdf** [comment]
Well, I find it very odd to suggest a lot of future years
