### ISSUE TITLE
dashboard link for late document

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4396]
https://www.evernote.com/shard/s272/sh/6bd4cfe0-ef79-4397-b9be-ee1fa4b117de/d5dec9c2568f5a8816cb43e10afdb330
as you can see the link for late order is the same for nr. orders and for late orders

**Comment by marcosgdf** [comment]
Duplicate of bug #3241

**Comment by eldy** [comment]
Right, link is same until we have a way to filter on "late" status
