### ISSUE TITLE
Replacement invoice for customer

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#4398]
I make invoice for customer, validate it. Now i wan change sales tax. I create Replacement invoice, edit line change tax 23% -> 0% and then i received info: 
**The progress can't be smaller than its value in the previous situation.**

How can i change sales tax? I can't modify original invoice because it's posted.

**Comment by ndrosis** [comment]
Hi,
create an credit note and create new standard invoice with correct vat.

**Comment by pat15** [comment]
There's no other way?

**Comment by ndrosis** [comment]
I tried in the way you mention and changed it without a problem.
Which version do you have?
Did you put a minimum discount to the product?

My version is 3.8.2.

**Comment by pat15** [comment]
I have 3.8.3. 
No i don't have set minimum price. I try do it on demo site here:
Invoice: http://demo.dolibarr.org/compta/facture.php?facid=6717
Replacement invoice: http://demo.dolibarr.org/compta/facture.php?id=6718

And it's not work ... ;/

**Comment by marcosgdf** [comment]
Replacement invoices are for amounts higher than 0. Credit notes are for amounts lower than 0. If you reduce the VAT, then the total amount will be negative, so a credit note must be issued.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
