### ISSUE TITLE
Link to sub-category

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#4405]
Hi, 
Example of simple category structure:
COULEUR
COULEUR => ROUGE
COULEUR => BLEU
If the option to link the parent category is activated upon addition of ROUGE, the COULEUR will be added automatically. By cons we can not add BLEU except disable "link to the parent category"

Reproduce on 3.8.3

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
