### ISSUE TITLE
Bug: Company administration page shows incorrect information

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4406]
Version: 3.7.3
Page: http://dolibarr.local/admin/company.php

In a fresh install, the admin page of the company shows that the month the fiscal exercise is started is "January", while `$conf->global->SOCIETE_FISCAL_MONTH_START` equals to 0.

If I try to modify the configuration, then it shows that no month is selected.

We should be able to see that no month is selected without having to access to the edit action

![captura de pantalla 2016-01-12 a las 11 02 27](https://cloud.githubusercontent.com/assets/168744/12260459/2354c664-b91c-11e5-8582-5b60aa86c23c.png)
![captura de pantalla 2016-01-12 a las 11 02 32](https://cloud.githubusercontent.com/assets/168744/12260460/250dc96a-b91c-11e5-9ffe-095c893ec685.png)

**Comment by eldy** [comment]
When nothing is defined, dolibarr will use by default "january". Thats why we show it.
If user edit it, nothing is filled because there is no default value. We should instead have here january selected (because unknow = january in rest of software)

**Comment by eldy** [comment]
Seems to be fixed with recent versions
