### ISSUE TITLE
Bug: Supplier invoices use FAC_FORCE_DATE_VALIDATION client invoices property

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4414]
Version: 3.7

Supplier invoices module uses FAC_FORCE_DATE_VALIDATION property of client invoices that force the date of the invoice to be the validation date.

This causes a problem when you add a supplier invoice of another year and it uses the current year for the reference.

**Comment by eldy** [comment]
This may be also a problem for customer invoices. This option should just not exists i think, don't you think so ?

**Comment by marcosgdf** [comment]
In fact it does make sense for customer invoices. A customer invoice does not officially exist until it is validated, but a supplier invoice has been issued in the date that we have entered in the input. So... it does even make sense to force that option to be enabled by default in Dolibarr for customer invoices.
