### ISSUE TITLE
Bug: shipping pdf with serial error

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4419]
# Environment
- **Version**: 3.8.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.16
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /expedition/card.php?id=101
# Report

 When is enabled the multilingual, instead of serial will print "printBatch-printQty"

**Comment by centoasa** [comment]
same issue on relase 4.0.0 beta

**Comment by atm-maxime** [comment]
Hi @centoasa 

Can you give us more informations ? I just tried and it seems to print correctly :

![image](https://cloud.githubusercontent.com/assets/2097773/21073148/6f7cfc66-bed7-11e6-915e-46b805dc76c0.png)

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug
