### ISSUE TITLE
Strange behaviour for translation in Expensereport

### ISSUE THREAD

**Issue by pscoffoni** [Dolibarr/dolibarr#4429]
Hello,
Something I d'ont understand in the way translation are made in expensereport module.
In card.php,  the selection list of value is transalated based on the field label in the function
function select_type_fees_id (expensereport.class.php)
`if ($obj->code != $langs->trans($obj->code)) print $langs->trans($obj->code);
else print $langs->trans($obj->type);`

but when the label is displayed in the list , the translations is based on 
Line 1681 : `print '<td style="text-align:center;">'.$langs->trans("TF_".strtoupper($objp->type_fees_libelle)).'</td>';`

The result is when you add new fees, the label of the type of fees is correctly displayed in the selection list. But when the fee is saved the type of fees appears like TF_LABEL DU FEES

One example
![selection_144](https://cloud.githubusercontent.com/assets/805000/12358851/92d8ec14-bbaf-11e5-9ba6-d70d7e9cd8a8.png)

Should not be something like this in card.php ?

`print '<td style="text-align:center;">';
if ($objp->type_fees_code != $langs->trans($objp->type_fees_code)) print $langs->trans($objp->type_fees_code);
else print $langs->trans($objp->type_fees_libelle);
print '</td>';`

If not, it means, we have to update trips.lang everey time a label is added or changed ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
