### ISSUE TITLE
Will double entry accounting be supported soon? 

### ISSUE THREAD

**Issue by faridprogrammer** [Dolibarr/dolibarr#4431]
hi.
When double entry accounting will be supported on application? 
In first page of project's github it was mentioned that it is not fully supported yet.

**Comment by rdoursenaud** [comment]
This is a bug tracker, not a forum.
Please direct your question to http://www.dolibarr.org/forum.
Thanks for your understanding.

**Comment by faridprogrammer** [comment]
so sorry
