### ISSUE TITLE
Bug: product stats

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4435]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.16
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /product/stats/card.php?id=all&type=0&action=recalcul&mode=bynumber
# Report

impossible create dir
http://prntscr.com/9qyj3p
Why stats don't include a way to export data, so to see the list of selling products per period.
Why in List of products by popularity is there only products in proposal and not in order?

**Comment by atm-arnaud** [comment]
The problem comes from your folder rights. Try with that command : chmod -R 755 documents/
and update the develop version now. This tip should resolve your problem.

**Comment by eldy** [comment]
This issue does not look to be a Bug neither a Feature request, so I close it.
For questions, you can try on forums.
