### ISSUE TITLE
Bug: customer card

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4436]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.16
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /comm/card.php
# Report

when try to print the customer card/sheet
Dolibarr ha rilevato un errore tecnico.
Si tratta di informazioni utili alla diagnostica:
Data: 20160116225115
Dolibarr: 4.0.0-beta
Livello di funzionalità: 0
PHP: 5.6.16
Server: Apache
OS: Linux 100asa.it 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

URL richiesto: /comm/card.php?optioncss=print
Referer: https://erp.100asa.it/comm/card.php
Gestore dei menu: eldy_menu.php

Gestore del tipo di database: mysqli
Richiesta dell'ultimo accesso al database in errore: Nessuna richiesta in errore
Codice di ritorno per ultimo accesso al database in errore: Nessuna richiesta in errore
Informazioni sull'ultimo accesso errato al database: Nessuna richiesta in errore

Message: Bad value for socid parameter

**Comment by aschio** [comment]
works for me. @eldy

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug
