### ISSUE TITLE
Bug: The module descriptor modUser must have a numero property

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4437]
Version: develop (maybe 3.9)?

Found in the log:
2016-01-17 10:11:09 ERR     192.168.42.1    The module descriptor modUser must have a numero property

**Comment by eldy** [comment]
Currently numero is '0'. 
Can you argue why we should use a non zero number ?

**Comment by marcosgdf** [comment]
I'm just posting an entry that I found in the log

**Comment by rdoursenaud** [comment]
@eldy
I'm getting the same error in my logs.
Either give it a number or fix the offending logging code at `htdocs/admin/modules.php`!

**Comment by rdoursenaud** [comment]
Oh, it's been fixed by dbb84601803b743eb28d64cf1df19f8d73820534

Let's cherry-pick this and close the issue.

**Comment by PlanPc** [comment]
In 3.9.2 also, dolibarr.og:

The module descriptor modUser must have a numero property

**Comment by rdoursenaud** [comment]
@PlanPc Yes, commit dbb8460 is on the 4.0.0 branch. It will only be included then…
