### ISSUE TITLE
Bug: search head bar order

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4445]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.16
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /fourn/commande/list.php
# Report

for supplier and customers order, search head bar don't work; left link woks well.

**Comment by aschio** [comment]
Fixed with #4643 @eldy
