### ISSUE TITLE
Bug: Direct debit module not working properly

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4447]
Version: 3.8

Page: http://dolibarr.local/compta/prelevement/fiche-stat.php?id=1

```
( ! ) Warning: Division by zero in /var/www/dolibarr/htdocs/compta/prelevement/fiche-stat.php on line 144
Call Stack
#   Time    Memory  Function    Location
1   0.0041  289136  {main}( )   .../fiche-stat.php:0
0 %
```
- Broken direct debit file in http://dolibarr.local/compta/prelevement/factures.php?id=1
- Missing total amount in all the tabs except the main one
- Missing total amount in direct debit area
- Missing total amount in http://dolibarr.local/compta/prelevement/bons.php?mainmenu=bank
- Missing total amount in http://dolibarr.local/compta/prelevement/create.php?mainmenu=bank
- UI Glitch in http://dolibarr.local/compta/prelevement/create.php?mainmenu=bank

![captura de pantalla 2016-01-18 a las 12 49 23](https://cloud.githubusercontent.com/assets/168744/12390617/f3d9ee3a-bde1-11e5-97a8-59bf8500bc81.png)

**Comment by aconits** [comment]
Hi Marcos,

Work's for me in 3.9 and 3.8,
I can't reproduce this error, how you make a withdraw request with 0 as amount ?

**Comment by marcosgdf** [comment]
Well, that is part of the bug. It happened in 3.8 (january version) so there is no way it is working in 3.8…
