### ISSUE TITLE
Bug: ICS translate key does not give enough information for translators or developers to understand what it is

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4449]
Version: 3.8
Page: /htdocs/admin/prelevement.php

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by marcosgdf** [comment]
Still there in 6.0.4

![image](https://user-images.githubusercontent.com/168744/34083317-a3e2843c-e36e-11e7-89fa-079278f4351e.png)
