### ISSUE TITLE
Feature Request: Do not alert the user if the IBAN code is valid

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4450]
Version: 3.8

Page: http://dolibarr.local/societe/rib.php?socid=1

If the given IBAN is valid, then why showing an icon to the user like there is any relevant information available to show? If the IBAN code is invalid, then a warning should be shown, but if it is a valid code I don't think that is relevant information to the user.

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
