### ISSUE TITLE
Bug: "All orders" counter in /fourn/card.php stops at 5

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#4455]
# Environment
- Version: 3.8.3
- OS: Linux
- Web server: Apache
- PHP: 5.6.15
- Database: MySQL MySQL 5.1.73-log
- URL: /fourn/card.php?socid=123
# Report

The small label behind the box title "All orders" will always show the number "5" even though /fourn/commande/list.php?socid=123 contains more than 5 orders.

**Comment by atm-arnaud** [comment]
I'm currently working on
