### ISSUE TITLE
Feature request: alert for late orders

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4459]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /commande/list.php?mainmenu=commercial
# Report

if customers orders was shipping, the triangle yellow for late orders must be disappear.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
