### ISSUE TITLE
Bug: order ready to ship

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4462]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /commande/list.php?page=0&sortfield=c.rowid&sortorder=DESC&sortfield=c.rowid&sortorder=DESC
# Report

passing the mouse on van icon with red arrow, the products are the same of upper order (and wrong). But enter into order (124) the products are different (and right)
https://www.evernote.com/shard/s272/sh/90b5b2b0-00ff-4a13-a73c-d5fda068815d/50e671ce5edb18aeb96629f0ac12fbfd

**Comment by aschio** [comment]
cannot reproduce. I think it was already fixed. @eldy

**Comment by eldy** [comment]
Seems fixed, i close
