### ISSUE TITLE
FEATURE REQUEST: Decrement stock by warehouse and product when I validate invoice

### ISSUE THREAD

**Issue by benlo06** [Dolibarr/dolibarr#4466]
Hello,

I have 2 warehouse and I generate invoice with product of my 2 warehouse. But when I validate the invoice, the confirmation popup permit de decrease stock of only one warehouse.
Is it possible to choose the warehouse to decrease for each line of my invoice ?

Regards,
Ben

**Comment by BebZ** [comment]
It's a FEATURE REQUEST, NEW: is only for new functions implemented, can you change the title ?
you may use the functions of decrease/increase manually... if possible in your workflow in /admin/stock.php 
![image](https://cloud.githubusercontent.com/assets/3694135/12456082/93c79d80-bf9e-11e5-8eca-b80fafc4051e.png)
