### ISSUE TITLE
Tiers particuliers Individuals (version 3.5 to 3.9)

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#4472]
Les id prof (SIREN, RCS....) sont toujours visibles me pour des particuliers où cette info n'a aucun sens.
Ca pose problème si on active le contrôle sur un de ces champ (SIREN unique) : impossible de saisir un particulier.

Prof ids are always active even for indivuiduals, where they have no sense. If control of this fields is activated, then ther is no more possible to create a physical thirdparty.

**Comment by eldy** [comment]
I think i fixed this recently on 3.9
Do you still have problem to create an individual when control on siren is on ?

**Comment by tiaris** [comment]
ok in 4.0
