### ISSUE TITLE
Feature request: product list

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4477]
It would a very good thing to have the list of products with column of ordered, so per product the operator can see how many in stock and how many in supplier order.
And very important thing, have the print option on stock list.
this features are very important for who sell by phone.

**Comment by BebZ** [comment]
Can you specify more,a nd maybe with a screenshot ? 
did you know this screen ? 
/product/stock/replenish.php
there are columns for Commandé À commander     (Ordered / to order)

**Comment by centoasa** [comment]
I refer to /product/reassort.php?type=0
