### ISSUE TITLE
external users cannot access external modules even they have rights

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#4481]
i guess this statement " Remarque, seuls les modules suivants sont ouverts aux utilisateurs externes (quelles que soient les permissions de ces utilisateurs) : Projets/Opportunités/Affaires, Fournisseurs, Libellés/Catégories, Tiers, Utilisateurs & groupes, Commandes clients, Adhérents, Expéditions, Agenda, Contrats/Abonnements, Factures et avoirs, Interventions" should not apply to external modules

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
