### ISSUE TITLE
Feature request: simplify mysql backup wizard

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4482]
Show only a simple wizard to create a backup with the most common options and hide under an "advanced options" menu the rest of the options.

**Comment by elarifr** [comment]
the backup tool should be splitted in two parts
- one admin tool for settings 
- and a user tool that run backup

this is what i try to do in extrabackup module for documents folder, htdocs folder and also mysql db.

settings are managed in admin tool by an admin who has rights 
https://www.dropbox.com/s/8v4lyzyyuluv8yv/2016-03-06%2014_16_22-Greenshot.png?dl=0

then a user with no admin privilege but who have only module rights can run the backup but not download the zip
https://www.dropbox.com/s/fucp6crbbtq2qni/2016-03-06%2014_16_38-Greenshot.png?dl=0

This should also allow to run backups by cron jobs

**Comment by eldy** [comment]
In first step, adding js to hide/show advanced option on page htdocs/admin/tools/dolibarr_export.php   would be enough

**Comment by eldy** [comment]
Has been implemented into v17
