### ISSUE TITLE
Replace jflot with chart.js

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4486]

**Comment by laudeco** [comment]
isn't a conflict with #9429 ?

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/9620

**Comment by eldy** [comment]
Done in develop by d0839350db1c87c486154ef288c41d59b7f5f8a9 and aa1552dbc02b188b6d4cbc5118dbb1618bfb9ea7
