### ISSUE TITLE
New request: show unit column under package product page/table

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#4489]
Thanks very much!

**Comment by wankwaiwing** [comment]
UNIT: PCS,SET,M,KG,G.....

**Comment by marcosgdf** [comment]
There is already a function like that in Dolibarr but it is hidden. 
Go to config > misc and add "PRODUCT_USE_UNITS" with value 1.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
