### ISSUE TITLE
Bug: payment condition dafault

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4490]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.2
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /commande/orderstoinvoice.php?orders_to_invoice%5B%5D=139&autocloseorders=on&socid=133&action=create&origin=commande
# Report

when generate invoice from cusotmers order, the payment condition and type was filled by default and not how setup into order.

**Comment by eldy** [comment]
Can't reproduce. Is it still true with current dev ?

**Comment by aschio** [comment]
It's true. Works for me too. @eldy

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug
