### ISSUE TITLE
Feature request: php 7 compatibility

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4491]
php >=7 compatibility

**Comment by eldy** [comment]
3.9 seems to be ok. Can you make some tests ?

**Comment by centoasa** [comment]
I'm using 4.0 beta and seem don't work only export

**Comment by marcosgdf** [comment]
Any news on this?

**Comment by simnandez** [comment]
I close this issue, because is implemented in maintened versions
