### ISSUE TITLE
error when cloning product with extra fields

### ISSUE THREAD

**Issue by nes61** [Dolibarr/dolibarr#4492]
When I tried to clone a product with Extrafields I had this error:

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20160124182728
Dolibarr: 3.8.3
Niveau de fonctionnalités: 0
PHP: 5.4.45
Serveur: Apache
OS: Linux oberon.kreativmedia.ch 2.6.18-407.el5 #1 SMP Wed Nov 11 08:12:41 EST 2015 x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4

Url sollicitée: /doli/htdocs/product/card.php?id=3&action=confirm_clone&confirm=yes&clone_ref=pos02.0260&clone_content=on&clone_prices=&clone_composition=
Referer: http://msinformatique.ch/doli/htdocs/product/card.php?id=3
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: INSERT INTO llx_product_extrafields (fk_object,pos,nb) VALUES (4,'02.0210','9')
Code retour dernier accès en base en erreur: DB_ERROR_RECORD_ALREADY_EXISTS
Information sur le dernier accès en base en erreur: Duplicate entry '02.0210' for key 'uk_product_extrafields_pos'

Message: Duplicate entry '02.0210' for key 'uk_product_extrafields_pos'

Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/msinformatique.ch/httpdocs/doli/htdocs/core/lib/functions.lib.php:2607) in /home/httpd/vhosts/msinformatique.ch/httpdocs/doli/htdocs/main.inc.php on line

**Comment by eldy** [comment]
What are property of extrafield "pos" ?
Is it a "unique" field and/or "mandatory" ?
Do you set a default value ?

**Comment by aljawaid** [comment]
I get the same error if I select "unique" field. I avoid unique field as a habit now.

Was initially hoping (saves time when doing multiple products of the same range), as the unique option was there, that dolibarr would duplicate the unique field and maybe add a digit on the end with a reminder alert to correct the unique field.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
