### ISSUE TITLE
Feature request: more email address operator

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4502]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: 
# Report

To send email for orders and others documents, it would be better to have more than one email address for operator, so email can send by different email address.

**Comment by fredt34** [comment]
+1 - it would be nice to allow multiple email address & signatures per user, or to allow to select other users. This allows to change the signature when chasing money on late invoices...
