### ISSUE TITLE
impossible to input quantity lesser than 1 when adding free service line in supplier order

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#4504]

**Comment by altairis-tof** [comment]
version 3.8.3

**Comment by eldy** [comment]
I tested with 3.9 and it works. Is it ko for you on 3.9 ?

**Comment by altairis-tof** [comment]
i will test asap; none of my customer neither us work with this release, but i will try. thanks

**Comment by simnandez** [comment]
I close this issue, because is not reproducible in maintened versions
