### ISSUE TITLE
why have minimum quantity on supplier service prices ?

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#4505]

**Comment by marcosgdf** [comment]
It is a price rule.

**Comment by altairis-tof** [comment]
so imagine you have a SERVICE supplier that have prices per day (very uncommon isn't it ?)... he tells you that he will charge you half a day... how to make an order with dolibarr ? and please don't tell me to enter his prices by half days or hours...

**Comment by eldy** [comment]
If you decide to enter qty lower than 1 and you enter into supplier price that qty should not be lower than 1, then you have an error. This is expected behaviour
If you want to ba able to enter qty with 0.1 parts, you must enter than minimum qty is 0.1 and price according to this.

**Comment by altairis-tof** [comment]
i understand your point but i think it's not very easy to implement with services based on time; it's a normal behaviour for products but maybe we can find an easier way to manage supplier services, allowing input of time instead of quantity.
(i agree it will work using 0.1 minimum quantity, but it is not so easy for everyone to convert time units to 10 based numbers)

**Comment by nka11** [comment]
Noticed a bug on this feature, I have re-activated phpunit tests (#5181) in travis and one fails with :

```
1) CommandeFournisseurTest::testCommandeFournisseurCreate

Failed asserting that 21 matches expected -1.

/home/travis/build/Dolibarr/dolibarr/test/phpunit/CommandeFournisseurTest.php:164
```

with this specific use case : while trying to set up a quatity of 1 while min supplier quantity is 10, order is created, but according to assertions, and behavior description, it should not.

**Comment by marcosgdf** [comment]
@nka11 Can you please file a new bug?
