### ISSUE TITLE
Expose accounting account number in Dolibarr exports

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4511]
The accounting account number is available in the database and can be useful in exports alongside traditional datas for external processing.

Identified affected modules:
- [X] Thirdparties
- [X] Products/Services
- [x] Users

**Comment by aspangaro** [comment]
Sorry @rdoursenaud. I don't understand your request. The accounting accounts are already available on the export, no?

**Comment by rdoursenaud** [comment]
@aspangaro Yes, you're right. Thirdparties and Products/Services account numbers are exposed in current develop exports. Guess I didn't sleep well that day ;)
Still missing for users though.

**Comment by aspangaro** [comment]
You're right for users. 

It's done ! Check #4543
