### ISSUE TITLE
Bug: line refused but not deleted

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4515]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /fourn/commande/dispatch.php?id=100
# Report

what mean reinit/refused if after line not will deleted?

**Comment by centoasa** [comment]
So, I had to get only 4 phones, but I mistakenly loaded a wrong serial, so now, unfortunately, I am a stock of 5 phones. How do I delete one?
http://prntscr.com/9vvhp8

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
