### ISSUE TITLE
Bug ? email template and other code (dictionary)

### ISSUE THREAD

**Issue by FAPMLIL** [Dolibarr/dolibarr#4522]
Good evening,

I back you a new bug in 3.8.3

Example, dictionary, email templates (llx_c_email_templates)

When I insert a new record, this one is empty.

I also noticed that the country codes, Monnais, etc ... the code is empty and does not appear

![doliprob](https://cloud.githubusercontent.com/assets/16575944/12655100/9bf4ee4a-c5f7-11e5-937a-33846238b304.png)

Fabien.

**Comment by eldy** [comment]
Can you switch to a supported them like eldy ?
Are things still empty ?

**Comment by FAPMLIL** [comment]
Hi eldy

On php 7.0.2 => ko ... => 5.6.17 => OK 

;)

sorry
