### ISSUE TITLE
Feature request: link customer invoice to shipping

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4526]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /compta/facture.php?facid=118
# Report

It would be very useful if customers invoice have a link to own shipping

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
Invoice can be created from shipment so there's a link between them.
