### ISSUE TITLE
Feature request: van always present

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4550]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /commande/list.php
# Report

Even when the order was already sent, still appears the van. Instead when the oridne was already sent, the van should disappear.
https://www.evernote.com/shard/s272/sh/c168a47d-94d8-4774-8749-50ffc9ace7e0/814ee9e2f379d72a1f985dad25ac4a11

**Comment by eldy** [comment]
The "van" provide a tooltip with information to know if we can ship or not and how much.
Even if order was shipped, we may decide to ship again (if shipment was lost for example). That's why we always show the van information.

**Comment by centoasa** [comment]
The van is very useful to the warehouse man to see what orders can be sent. If he continues to always display the van, he thinks that order is still to be shipped. An already sent order could replace with a van crossed for example
