### ISSUE TITLE
sql error when deleting batch products (v3.8.3)

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#4565]
On german Forum
http://www.dolibarr.de/forum/bugs-mit-einer-dolibarr-stabilen-version/52136-cannot-delete-or-update-a-parent-row#55808

It seems that some products can not been deleted sql error 
Cannot delete or update a parent row: a foreign key constraint fails (`dbxxxxxx-dolibarr`.`llx_product_batch`, CONSTRAINT `fk_product_batch_fk_product_stock` FOREIGN KEY (`fk_product_stock`) REFERENCES `llx_product_stock` (`rowid`))

**Comment by atm-maxime** [comment]
Fixed in #6113
