### ISSUE TITLE
Feature Request: Generic supplier's prices

### ISSUE THREAD

**Issue by philippe-opendsi** [Dolibarr/dolibarr#4596]
Hello,
In ordrer to simplify the process of adding generic's products in invoices or supplier's orders, it will be great to have the ability to define "generic's product" with default price. It would require to add a check box and a default price to the products/services. So this products will allways be usable in invoices or supplier's orders. 

This needs is related to the management of accounting codes associated with products. Without use of a real product/service, using free lines to solve this issue will no longer allows automatic accounting ventilation.

Example: Using a service "Shipping" in supplier invoices which needs to be assigned to a specific accounting code. Actually you need to defined a price for each suppliers. Heavy job for a structure that is trading with hundreds of suppliers.

Related discussions on the forum :
http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/36423-ajout-de-produits-sur-facture-fournisseur
http://www.dolibarr.fr/forum/3-installation/54154-service-produit-selectionnable-sans-fournisseur

Better idea ?
A patch to the core will be proposed as soon as possible...

Regards

**Comment by aljawaid** [comment]
This, if I understand it, would be a nice idea.
Maybe a "generic price" and a "generic product" which could be used as checkboxes to link to new or current products and then can be pulled up in a list.

**Comment by altairis-tof** [comment]
i have done it for a customer simply by adding a "generic_product" extrafield of boolean type (checkbox).

**Comment by philippe-opendsi** [comment]
Yes of course, you can do it like this, but you need to change  the standard behaviour of Dolibarr too in supplier orders ou invoices in order to be able to add this generic product for all suppliers.

**Comment by altairis-tof** [comment]
yes you are right; i've also made some improvements in dolibarr to make it work well. if i had more time it will be a good PR... if someone is interested to adapt it to latest develop branch, i will gladly send the code (based on 3.5.4)

**Comment by susan5in7** [comment]
I need to insert two fields for other charges while creating an Invoice and those should be added in Total Invoice value. How to do that? please help. 
I need to set a default sale price value for all products which must be updated daily.

**Comment by eldy** [comment]
With v8, you should be able to add a predefined product/service into a supplier order or invoice even if no price are defined. In such a case, the price 0 will be used and you have to set it manually.
