### ISSUE TITLE
PHP7 Uniform Variable Syntax (was export permissions don't work with PHP7)

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4597]
When using PHP7, export is always unavailable.
The interface always displays `NotEnoughPermissions`.

After a deep analysis, the defect is caused by a backward incompatible change introduced by the ["Uniform Variable Syntax" RFC](https://wiki.php.net/rfc/uniform_variable_syntax#backward_incompatible_changes).

I've published a condensed example in the following gist to help understanding the behavior differences: https://gist.github.com/rdoursenaud/224ac8dff52518402cc5

In Dolibarr the offending code is in `export.class.php` around line 134.
Eg.:

``` php
$bool = $user->rights->$perm[0]->$perm[1]->$perm[2];
```

In PHP7, this is interpreted as

``` php
$bool = ((($user->rights->$perm)[0]->$perm)[1]->$perm)[2];
```

and triggers a "Notice: Array to string conversion" and "Notice:  Undefined property".
$bool then becomes a null.

The workaround is to explicitly require the old behavior by adding braces to force precedence:

``` php
$bool = $user->rights->{$perm[0]}->{$perm[1]}->{$perm[2]};
```

I believe that this problem is widespread in Dolibarr codebase and can have very uncontrolled behavior.
IMHO, we should warn users that Dolibarr is incompatible with PHP7 for the moment and should not be used with it before this bug is ironed out.

Edit – List of affected files and number of occurrences:
- [x] htdocs/admin/oauth.php:2
- [x] htdocs/admin/delais.php:4
- [x] htdocs/admin/dict.php:51
- [x] htdocs/core/class/extrafields.class.php:16
- [x] htdocs/core/lib/functions2.lib.php:1
- [x] htdocs/core/lib/files.lib.php:12
- [x] htdocs/imports/class/import.class.php:5
- [x] htdocs/exports/class/export.class.php:5
- [x] htdocs/includes/phpoffice/phpexcel/Classes/PHPExcel/Worksheet/AutoFilter/Column.php:2

**Comment by jfefe** [comment]
Following regex can be used to find related code : 

```
^.*\$[a-z]+->rights->\$[a-z]+.*$
```

**Comment by rdoursenaud** [comment]
@jfefe The best matching simple one is `->\$\w+\[`

Using `ag --php --ignore-dir=/htdocs/custom "\-\>\\\$\w+\[" -c`, I got a list with the affected files and number of occurrences. I added this list to the original report for completeness.

**Comment by rdoursenaud** [comment]
OK, now that we have a proper search, I'm preparing a fix.

**Comment by rdoursenaud** [comment]
Reported PHPExcel bug upstream: https://github.com/PHPOffice/PHPExcel/issues/818
