### ISSUE TITLE
Supplier proposal issue

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#4599]
Requested Url: /supplier_proposal/card.php?id=1
Referer: /comm/index.php?mainmenu=commercial&leftmenu=
Menu manager: eldy_menu.php
Message: Unknown column 'd.fk_supplier_proposal' in 'field list'

**Comment by atm-gauthier** [comment]
Hi,
I made a test on Dolibarr 3.8, can't reproduce.
Do your problem persists ?
In which dolibarr version are you ?
Gauthier.

**Comment by atm-maxime** [comment]
Fixed in #5349
