### ISSUE TITLE
pdf_crevette.modules : bugs & missing (from Crabe)

### ISSUE THREAD

**Issue by aruben-c** [Dolibarr/dolibarr#4602]
Hello,
I see a new pdf model for invoice: crevette.
But, it's a copy of an old version of Crabe and corrections/adds on Crabe are not did in Crevette.

Ex:
$objphoto for get_exdir function in line 195 (bug?)
nblignes in line 253 ("Set nblignes with the new facture lines content after hook") (bug?)
multicurrency in line 659 & 1141 & 1335 (perhaps not need)
$object->fk_bank in line 1082 (perhaps not need)
EscompteOfferedShort instead of EscompteOffered in line 1373 (perhaps not need)
&& !empty($object->fk_facture_source) in line 1893
MAIN_PDF_USE_ISO_LOCATION at the end of _pagehead function (perhaps not need)
'INVOICE_FREE_TEXT' instead of 'FACTURE_FREE_TEXT' (bug to correct)

I see that the multicurrency parameter is omitted in "_tableau" : it's a new function in the develop branch (I not see it in v3.9rc).

With 2 similar models, we need to correct the 2 models at same time.

Well, I don't test the file (I only do a comparison between Crabe and Crevette in Develop branch 2016-02-10).

Thanks,
Ruben

**Comment by eldy** [comment]
This was a bad commit. There is no reason to have a second pdf template. I removed it.
