### ISSUE TITLE
Debian package wrong dependencies

### ISSUE THREAD

**Issue by furynick** [Dolibarr/dolibarr#4608]
The Debian/Ubuntu package depends of mysql-server AND mysql-client
mysql-server should not be required as the mysql server can be hosted on another system.
mysql-client is sufficient to access the database wherever it is.

Regards,
Nicolas.

**Comment by eldy** [comment]
The goal of debian package is to have a dolibarr working with no need of technical knowledge when installing the package. So all component to reach this goal are included.
If goal is to do a custom install, a better choice is to use the package to make custom install so the .zip file.

**Comment by furynick** [comment]
I doubt anyone without technical knowledge choose a linux platform to install dolibarr.
Moreover, the installation wiki might include the mysql-server installation, it's just one command line (sudo apt-get install mysql-server) so people without technical knowledge can also install dolibarr.

**Comment by rdoursenaud** [comment]
I agree.
It should be a recommended package, not a hard dependency. ("Recommends:" control field).
See the [Debian Policy](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps) and the [Maintainer's Guide](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control).

**Comment by autra** [comment]
> The goal of debian package is to have a dolibarr working with no need of technical knowledge when installing the package

But those with technical knowledge will be fooled by this when installing the deb. It should really be a "Recommends".

**Comment by GillesMocellin** [comment]
Another problem : If the user wants to use **MariaDB** instead of MySQL.
The correct way is to depend on `virtual-mysql-server` and `virtual-mysql-client` instead of `mysql-server` and `mysql-client`.
