### ISSUE TITLE
Feature request: all info about shipping

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4621]
On pdf document add all information about shipping: number of packages, weight of packages, dimension

**Comment by BebZ** [comment]
Hey Remigio ! you have very good ideas ;) maybe a little bit too "advanced" !?

When you prepare an order, you have to clic on "ship it" 
to know what is in stock or not, and the "stock location" (if you have multiple locations, or whatever : boxes, rows, shelves, etc...)
then when you're done with preparing and checking batches/dates + quantities... 
you validate the shipment, 
and before validating the shipment you want to implement all these infos ? 

Did you start this work yet ?

**Comment by centoasa** [comment]
Information packs and so on are the basis for shipments.
The total weight of the shipment can be detected by the weights of individual items, multiplied by the number of prepared parcels.
Near the tracking number can isnerire the number of parcels prepared, and the relative dimensions / overall weight

**Comment by BebZ** [comment]
the number of prepared parcels. 
how do you detect/input it ? 

tracking number is for one parcel only...

do you make one shipment for one parcel ? 
so how you/your customer/dolibarr consolidate the total shipments of an order ?

**Comment by centoasa** [comment]
Total Weight of parcel can be detected. But number of packages better input, because warehouseman could prepare only one carton!
