### ISSUE TITLE
FACTURE_DEPOSITS_ARE_JUST_PAYMENTS =1

### ISSUE THREAD

**Issue by FAPMLIL** [Dolibarr/dolibarr#4627]
Hi,

When using ODT and FACTURE_DEPOSITS_ARE_JUST_PAYMENTS = 1

{object_already_payed} : Amount already payed (numeric)
{object_remain_to_pay} : Remaining to pay amount (numeric)
{object_already_payed_locale} : Amount already payed (output language format)
{object_remain_to_pay_locale} : Remaining to pay amount (output language format)

Dolibarr does not deduct the payment on REMAIN to pay, no on already payed ..

It's OK PDF it
ODT is it's KO

Is there a solution ?

Thanks ALL :)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
