### ISSUE TITLE
Bug: father product don't update parents

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4631]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /product/composition/card.php?id=129
# Report

http://prntscr.com/a3mxb6
I've a product kit, composed by 4 ipcam bullet and 1 NVR
When I prepared a shipping, dolibarr ask me only the father item (with serial) and don't ask me the parents serials (ipcam and NVR)
And (bug) don't subtract the parents items
(I hope I'm clear)

**Comment by atm-maxime** [comment]
This seems to be fixed in latest version.
