### ISSUE TITLE
Feature request: delete supplier order/shipping

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4635]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.18
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /product/stock/mouvement.php?idproduct=297
# Report

http://prntscr.com/a3y6lz
as in this printscreen is it possible delete order and then shipping of supplier? or simply delete the product line/serial? Because sometimes in case of drop-shipping supplier communicate wrong serial number of products and it's very important edit/delete item/serial.

**Comment by BebZ** [comment]
Unfortunately if there is a mistake in batch serial there is few possibilites to edit it.
especially in your case, the datas are stocked in another table which is llx shipment batch.
You have to erase the supplier order, erase customer shipment erase stock movements linked to those manually, and "replay" another reception and shipment...
If you have another idea of workflow, be our guest and tell us ;)

**Comment by centoasa** [comment]
when you say "erase stock movements linked to those" what do you mean? how can I do it?
I don't see no trash bin
http://prntscr.com/a4bz25

**Comment by BebZ** [comment]
manually... i meant going in the Phpmyadmin and erase lines of SQL. But that's very unstable if you don't know how to do.

It should be feat request to put an incon trash bin on stock movements and delete linked objects (supplier recpetions/ and order shipments)

but i think we need @eldy 's point of view or @fappels ?

**Comment by centoasa** [comment]
this could be a fantastic idea to add a basket to erase stock movements lines. Surely this must be included in the user permissions, otherwise any warehouseman "crafty" could erase warehouse operations.

**Comment by fappels** [comment]
@centoasa I think @bebz means a shortcut to delete the linked object from within the stock movement list, but a linked object can contain more stock movements. For customer shipments you can click the linked object and delete it, so you have better control on what you are doing.  For correcting lot/serial (supplier dispatch), feature request could be:
1- Be able to make a zero stock movement to same stock location, so it gets listed in the stock mouvements with reason and user who did it.
or 2- Make dispatches delete-able.

**Comment by BebZ** [comment]
Hello @centoasa 
did you try deleting customer shipment and did you get back batches in the stock ?
For customer shipments you can click the linked object and delete it,

Do you plan to invest, someone plans to invest on module batch to make it able to : 
-edit batch lines in stock
-delete batch dispatched lines on supplier order if there is a mistake and if there is not already a shipment linked to a product batch...

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
