### ISSUE TITLE
Bug: add "good customers" dashboard disappear

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4647]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.18
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /index.php?mainmenu=home&leftmenu=home
# Report

just add "good customers" and all dashboard disappear!

**Comment by centoasa** [comment]
Now how can I do to restore dashboard?

**Comment by eldy** [comment]
What do you see into home - setup - boxes ?

**Comment by centoasa** [comment]
http://prntscr.com/a67z1v
here what I see

**Comment by atm-geoffrey** [comment]
Reproduce bug on 3.9.2. Error linked to custom boxe and just append when custom boxe is to show.
I think bug is linked to mysql connection $db.

Error in error.log  PHP Fatal error:  Call to a member function fetch_object() on a non-object in /var/www/dolibarr/htdocs/core/db/mysqli.class.php on line 293

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
