### ISSUE TITLE
Bug Business objects for adherent

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#4653]
i have several bugs since last version. I can't create with my scrip new adherent.

My user have this:

DolibarrHasDetectedError.
 InformationToHelpDiagnose:
Date: 20160218235654
Dolibarr: 3.8.3
PHP: 5.6.15
Server: Apache
OS: Linux DiskStation 3.10.77 #7274 SMP Wed Jan 20 20:25:24 CST 2016 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/14.14267

MenuManager: 

DatabaseTypeManager: mysqli
RequestLastAccessInError: SELECT rowid,name,label,type,size,elementtype,fieldunique,fieldrequired,param,pos,alwayseditable,perms,list FROM llx_extrafields WHERE entity IN (0,) AND elementtype = 'user' ORDER BY pos
ReturnCodeLastAccessInError: DB_ERROR_SYNTAX
InformationLastAccessInError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND elementtype = 'user' ORDER BY pos' at line 1

 DolibarrHasDetectedError.
 InformationToHelpDiagnose:
Date: 20160218235654
Dolibarr: 3.8.3
PHP: 5.6.15
Server: Apache
OS: Linux DiskStation 3.10.77 #7274 SMP Wed Jan 20 20:25:24 CST 2016 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/14.14267

MenuManager: 

DatabaseTypeManager: mysqli
RequestLastAccessInError: SELECT r.module, r.perms, r.subperms FROM llx_usergroup_rights as gr, llx_usergroup_user as gu, llx_rights_def as r WHERE r.id = gr.fk_id AND r.entity = AND gr.fk_usergroup = gu.fk_usergroup AND gu.fk_user = 11 AND r.perms IS NOT NULL
ReturnCodeLastAccessInError: DB_ERROR_SYNTAX
InformationLastAccessInError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND gr.fk_usergroup = gu.fk_usergroup AND gu.fk_user = 11 AND r.perms IS NOT NUL' at line 1

Message: ErrorWrongValueForParameterX
 --- end error code=1 

when i try a clean and simple script, i have an error too with a strange field 'fk_statut ' in llx_adherent

Type gestionnaire de base de données: mysql
Requête dernier accès en base en erreur: UPDATE llx_adherent SET fk_statut = 1 WHERE rowid=62
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'fk_statut' in 'field list'

Message: Unknown column 'fk_statut' in 'field list'
 --- end error code=1

**Comment by eldy** [comment]
Did you set the variable $user to an existing user in your script ?

**Comment by ptibogxiv** [comment]
Yes i use an existing user with admin right

i set several customs fields for adherent and type of adherent. is there a bug with this ?

**Comment by marcosgdf** [comment]
Without an example of your script we can't debug anything.
