### ISSUE TITLE
Emailing module : adresses are not add

### ISSUE THREAD

**Issue by microniko** [Dolibarr/dolibarr#4672]
# Bug

When I want to create a new emailing :
Creating : OK
Adding recipients : Nothing works. When I want to add recipients, Dolibarr says "X recipients added into target list" but the target list is empty !
## Environment
- **Version**: 3.8.2, 3.8.3, 3.9.0, 3.9.2
- **OS**: GNU/Linux Debian Jessie
- **Web server**: Apache
- **PHP**: 5.6.17
- **Database**: PostgreSQL 9.4.6  ⇐

**Comment by ghost** [comment]
Work on develop

**Comment by microniko** [comment]
Which database engine are you using ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
