### ISSUE TITLE
Feature request: send email with default sender

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4678]
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.18
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /admin/mails.php?mainmenu=home
# Report

Send email with default sender, not with email account of employees.

**Comment by eldy** [comment]
A way to adress that is to be able to enter a list of alternative "emails" on user card.
On email send form, a combo appear with list of defaut email + alternative.

**Comment by centoasa** [comment]
Sorry @eldy , how can I do to add other emails on user card?

**Comment by centoasa** [comment]
User without email is not possible; add email separated by , or ; or <email> don't be valid
@eldy @marcosgdf @rdoursenaud ho can I do to add more email to user?

**Comment by elarifr** [comment]
maybe should be set in two part
- in module setting (invoice, order, ...) add an option to select a default mail sender from dolibarr-system default / user / input alternate mail for the module, option to allow change by sender (add a permission?) 
  ex by default :all propal are send by user mail, shipping by dolibarr_system@me, order by management@me;  invoices are sent by invoice@me... and user can't change sender mail..
- when sending mail according to module option a dropdown is display where user can select sender mail if he is allowed 

it make sense that invoice are not sent by user mail but by company mail or a robot unmonitored adress

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
