### ISSUE TITLE
Bug: UI logout/print icons are misplaced when having a long user name

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4745]
# Bug

UI logout/print icons are misplaced when having a long user name
## Environment
- **Version**: 3.8.3

![captura de pantalla 2016-03-06 a las 20 39 56](https://cloud.githubusercontent.com/assets/168744/13556506/9ac91148-e3db-11e5-9593-cb58031a2156.png)

**Comment by atm-arnaud** [comment]
I'm currently working on

**Comment by atm-arnaud** [comment]
This bug is resolved in 3.9. And for this version, it appears only with ALL leters in CAPS without "i".

**Comment by marcosgdf** [comment]
Closed as resolved in 3.9.
