### ISSUE TITLE
Bug: UI glitch in project stats

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4751]
# Bug

UI glitch in project stats
## Environment
- **Version**: 3.8.3
- **URL(s)**: /projet/stats/index.php?leftmenu=projects

![captura de pantalla 2016-03-06 a las 21 04 00](https://cloud.githubusercontent.com/assets/168744/13556627/f822d7c2-e3de-11e5-8103-31727a48b8f0.png)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
