### ISSUE TITLE
Bug: UI glitch in tasks page

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4752]
# Bug

The text is white and not legible
## Environment
- **Version**: 3.8.3
- **URL(s)**: /projet/tasks/index.php

![captura de pantalla 2016-03-06 a las 21 05 05](https://cloud.githubusercontent.com/assets/168744/13556635/2029566a-e3df-11e5-9f01-d2d2417fb011.png)

**Comment by ghost** [comment]
Able to reproduce it on very small screen definition

**Comment by ghost** [comment]
Appear to be fix in 4.0 with a css display : table .

**Comment by marcosgdf** [comment]
Closing as old version involved
