### ISSUE TITLE
Bug: supplier invoices pending payment box should show total amount

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4771]
# Bug

It does not make sense to show me the total amount before taxes if I have to pay the total amount.
## Environment
- **Version**: 3.8.3
- **URL(s)**: /index.php?mainmenu=home&leftmenu=

**Comment by eldy** [comment]
It's a point of view. Most companies prefer to see due amount without tax (that is real amount because vat will be retreive).
Also for consistency, currently, it seems that all boxes show amount without tax.
I would prefer to see a hidden option  MAIN_BOXES_SHOW_AMOUNT_WITH_TAX
