### ISSUE TITLE
Feature request: create a function to retrieve the images of a product

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4779]
# Feature Request

Currently each page uses lots of code to find the images attached to a product. They compare if we are using the constant PRODUCT_USE_OLD_PATH_FOR_PHOTO, if we are actually looking for the photos of a product of service… And we want to change the way photos are stored we might have to change _A LOT_ of pages, and also thirdparty developers must face the problem that their module might stop working the next day.

Having a function like Product::getPhotos that only returns an array of the fullpath of images associated to that product of service will be a relief.

**Comment by hregis** [comment]
this new way to store photos is a big regression !!! how to differentiate photos of product with pictures in attached files ??

**Comment by marcosgdf** [comment]
I'm not talking about storing photos but retrieving them. There is no difference in the way they are stored. To give you an example, I'm talking about replacing:

```
if (! empty($conf->product->enabled)) $upload_dir = $conf->product->multidir_output[$object->entity].'/'.get_exdir(0, 0, 0, 0, $object, 'product').dol_sanitizeFileName($object->ref);
    elseif (! empty($conf->service->enabled)) $upload_dir = $conf->service->multidir_output[$object->entity].'/'.get_exdir(0, 0, 0, 0, $object, 'product').dol_sanitizeFileName($object->ref);

    if (! empty($conf->global->PRODUCT_USE_OLD_PATH_FOR_PHOTO))    // For backward compatiblity, we scan also old dirs
    {
        if (! empty($conf->product->enabled)) $upload_dirold = $conf->product->multidir_output[$object->entity].'/'.substr(substr("000".$object->id, -2),1,1).'/'.substr(substr("000".$object->id, -2),0,1).'/'.$object->id."/photos";
        else $upload_dirold = $conf->service->multidir_output[$object->entity].'/'.substr(substr("000".$object->id, -2),1,1).'/'.substr(substr("000".$object->id, -2),0,1).'/'.$object->id."/photos";
    }

// Construit liste des fichiers
    $filearray=dol_dir_list($upload_dir,"files",0,'','(\.meta|_preview\.png)$',$sortfield,(strtolower($sortorder)=='desc'?SORT_DESC:SORT_ASC),1);

    if (! empty($conf->global->PRODUCT_USE_OLD_PATH_FOR_PHOTO))    // For backward compatiblity, we scan also old dirs
    {
        $filearrayold=dol_dir_list($upload_dirold,"files",0,'','(\.meta|_preview\.png)$',$sortfield,(strtolower($sortorder)=='desc'?SORT_DESC:SORT_ASC),1);
        $filearray=array_merge($filearray, $filearrayold);
    }

```

with

```
$filearray = $object->getPhotos()
```

PD: This is just a backend FR and I'm talking only about photos, I c&p this code to give you an example. The pages won't be affected, just the method that they call

**Comment by hregis** [comment]
yes but PRODUCT_USE_OLD_PATH_FOR_PHOTO is a hidden option that is not enabled by default on a fresh install. how a newbie, do not know this constant, it can make the difference between the attached images and product images?

**Comment by marcosgdf** [comment]
That is not the thing this feature request is wanting to address, this is just a refactor. Also, it looks like the goal of next Dolibarr versions (see #2572) its to merge both documents and product photos.
