### ISSUE TITLE
Bug: Porposal, cannot close

### ISSUE THREAD

**Issue by dreggy** [Dolibarr/dolibarr#4789]
# Bug

Hi, i had a similar problem to bug #2773, the workflow doesn't show errors, the proposal appear closed but when i reload it, it is again unclosed
## Environment
- **Version**: 3.8.3
- **URL(s)**: http://www.friulsicurezza.it/dolibarr_/comm/propal.php
## Expected and actual behavior

Expected: get the proposal closed or get some error shown
Actual behavior: the proposal does not get closed but the ui show it closed and no errors shown
## Steps to reproduce the behavior

Log file shows
       2016-03-10 22:35:58 ERR 79.21.237.100 DoliDBMysqli::close Closing a connection with an opened transaction depth=24

so i checked the code and found that on file
       **comm\propal\class\propal.class.php**
if i comment the line **1982**
       **$this->generateDocument($modelpdf, $outputlangs, $hidedetails, $hidedesc, $hideref);**
all start working good.

it seems to me that this line mess up the **$this->transaction_opened** counter, so the next call **$this->db->commit();** on the line **1994** will fail

the pdf model used is the default "azur"

**Comment by eldy** [comment]
Did you try 3.8.4 ?

**Comment by dreggy** [comment]
I updated to 3.9 and all is working well now

**Comment by marcosgdf** [comment]
Can you please close this issue if it is working OK now?
