### ISSUE TITLE
Bug: Unable to enable customer invoices module

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4793]
# Bug
## Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: fpm-fcgi 5.6.19-1+deb.sury.org~trusty+1
- **Database**: PostgreSQL 9.3.11
- **URL**: /admin/modules.php?mode=common&page_y=784
## Report

```
ERROR: 22P02: invalid input syntax for integer: '' LINE 1: ...,null,'Generate recurring invoices','1', '86400', '', '', 1,... ^ LOCATION: pg_atoi, numutils.c:52
```

**Comment by Trenard2016** [comment]
I'm having this issue too.
