### ISSUE TITLE
Bug: Unable to create a supplier invoice

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4794]
# Bug
## Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: fpm-fcgi 5.6.19-1+deb.sury.org~trusty+1
- **Database**: PostgreSQL 9.3.11
- **URL**: /fourn/facture/card.php
## Report

```
ERROR: 42601: zero-length delimited identifier at or near '''' LINE 1: SELECT rowid FROM llx_multicurrency WHERE code = '' ^ LOCATION: scanner_yyerror, scan.l:1052
```

**Comment by aschio** [comment]
In the title you wrote "Customer" invoice, but in report URL is fourn/facture/card.php

**Comment by marcosgdf** [comment]
@aschio good catch

**Comment by marcosgdf** [comment]
It is working in 6.0 beta so I guess it is OK now
