### ISSUE TITLE
Mixup in attachment when working on two e-mail in the same time

### ISSUE THREAD

**Issue by ygini** [Dolibarr/dolibarr#4801]
# Bug

If you prepare two quote and send them in the same time from the same browser via e-mail by the built-in feature, attachment are mixed. The e-mails are sent with the good subject and message but the attachment is same in both mail (in my case the one sent last).
## Environment
- **Version**: 3.8.3
- **OS**: Debian 8
- **Web server**: Apache 2.4.10
- **PHP**: 5.6.14-0+deb8u1
- **Database**: MySQL 5.5.46-0+deb8u1
- **URL(s)**: comm/propal.php?id=16&action=presend&mode=init
## Expected and actual behavior

The use case is: I want to send two quote to a customer in the same time. I open two browser window from the same computer and work on the two quote and validate them. Then I use the built-in e-mail feature to send the quote. I write the two content and clic on the send button from the two windows at few seconds of intervals.

I except from Dolibarr to send the two quote correctly with right subject, content and attachment.

At this time the subject and content are OK but the attachment are mixed, both e-mails are sent with the attachment of the last one.

Interesting things is the attachment name is the real name of the file (ie. it has the good number for the attachement file, it's not the name of the requested one).

The quote sent last is right. For exemple quote ID in subject is 16, message body talk about piece 16 and attachement is named 16 and show the actual quote 16.

The quote sent first is wrong. The quote ID is 15, the message body is 15 but the name of the attachment is 16 and the content is actually the quote 16.
## Steps to reproduce the behavior

Prepare your setup to send e-mail and add a customer in your database with e-mail info
1. login to dolibarr
2. open two new quote in two different window
3. add some content to both quote and validate them
4. clic on the e-mail function on both
5. personalize your message in both to have specific content for each
6. clic on the send button on both quote as fast as you can (it took me a second or so to do it)

Check the received e-mails and look at the attachment.

**Comment by BebZ** [comment]
Woha, this is really concerning security piece of stuff...

**Comment by eldy** [comment]
This bug has been fixed in 5.0 branch (may be in 4.0 too, not sure).

**Comment by attritionorg** [comment]
@eldy can you link to the fixing commit please?
