### ISSUE TITLE
BUG: problem with class heritage

### ISSUE THREAD

**Issue by hregis** [Dolibarr/dolibarr#4809]
il y a un soucis depuis la 3.8

lorsqu'on envoi un document (propal, commande, facture, etc..?) par mail via "Envoyer par mail" et que le pdf n'existe pas il le crée à la volé et affiche le formulaire d'envoi de mail.
jusqu'ici on est d'accord... :-)

Si on met un "var_dump($object->lines[$i])" dans la fonction "pdf_getlinedesc" de pdf.lib.php et qu'on génère le pdf normalement, les variables sont ok et le pdf aussi.
par contre si on efface ce pdf et qu'on clique sur "Envoyer par mail", certaines variables ont une valeur NULL alors que d'autres ont les bonnes valeurs.
du coup il peut y avoir des soucis de présentation dans le pdf.
non seulement dans un dolibarr de base, mais aussi avec des modules externes (ultimatepdf, milestone, etc...)

je soupçonne un héritage de classe excessif (orderline par exemple !) qui à force écrase des données avec des valeurs NULL !
déjà pour moi le commonobject, vu qu'il est partagé entre l'object et les lignes de l'object, il ne devrait pas contenir la déclaration des variables de l'object !
car ces dernières se retrouve dans l'object de la ligne, avec une valeur NULL, ce qui est complètement inutile, engendre la confusion et augmente le risque d'erreurs !

le commonobject, comme son nom l'indique, ne devrait contenir que les variables "communes" (style db, error, etc...)

```
class Commande extends CommonOrder
abstract class CommonOrder extends CommonObject
abstract class CommonObject


class OrderLine extends CommonOrderLine   (variables des lignes de commandes)
abstract class CommonOrderLine extends CommonObjectLine     (variables des lignes de commandes)  <---  est-ce utile ????
abstract class CommonObjectLine extends CommonObject    (variables communes aux lignes d'objects)
abstract class CommonObject        (variables communes aux objects)
```

**Comment by hregis** [comment]
@eldy 

place un "var_dump($object->lines[$i])" dans la fonction "pdf_getlinedesc" de pdf.lib.php
génère normalement le pdf, tu obtiendras les variables à gauche dans mon exemple.

supprime le pdf et clique sur "Envoyer par mail", tu obtiendras les variables à droite dans mon exemple.

si tu compares chaque variable, tu verras qu'il y en a avec une valeur NULL alors que ça ne devrait pas l'être. De plus il y a des variables supplémentaires.

c'est ce qui me fait dire qu'il y a un schmilblick dans l'héritage des classes et que des variables sont écrasées avec une valeur NULL !

**Comment by hregis** [comment]
mon exemple en fichier attaché,
c'est un var_dump de la même ligne !
à gauche je génère le pdf, à droite je clique sur "Envoyer par mail" après avoir supprimé le pdf.
[diff.pdf](https://github.com/Dolibarr/dolibarr/files/171505/diff.pdf)

**Comment by eldy** [comment]
When did you remove the PDF file. Just after opening the form to send email ?

**Comment by hregis** [comment]
before opening the form. 
and just after this delete, click to open the form. you can close the form without send the mail. the pdf is recreate.

**Comment by hregis** [comment]
j'ai trouvé la cause du problème ! un exemple : 
dolibarr 3.8 -> fichier /commande/card.php
ligne 2164 : $result = $object->getLinesArray();

un var_dump($object) avant et après et comparer les valeurs des variables de ligne !

et d'ailleurs si je met cette ligne en commentaire ça ne change rien à l'affichage des lignes !!!
cette fonction est-elle utile ?
vu que le fetch_lines est déjà dans le fetch ! pourquoi en remettre une couche ?

**Comment by hregis** [comment]
getLinesArray() fait double emploi avec fetch_lines() !

**Comment by eldy** [comment]
Yes. I pushed a fix.

**Comment by hregis** [comment]
thanks
