### ISSUE TITLE
Bug: Won translation for the key OppStatusWON instead OppStatusWIN

### ISSUE THREAD

**Issue by joseplluis** [Dolibarr/dolibarr#4813]
# Bug

"Won" opportunity translation not applied for OppStatusWON.
In .lang files there are OppStatusWIN instead.
## Environment
- **Version**: 3.9.0

**Comment by marcosgdf** [comment]
Can you please give more details about the problem?

**Comment by joseplluis** [comment]
All the lang files have the key OppStatusWIN.
But in the code this key doesn't exist. 
For example in projet/card.php there is the following translation: trans("OppStatus".$code);
The $code WIN doesn't exist in the types of opportunities. The real code is WON.

There are 2 possible solutions:
- Change all the keys in lang files from OppStatusWIN to OppStatusWON.
- Change the code WON to WIN in the types of opportunity.

**Comment by marcosgdf** [comment]
Changing the key to WIN could lead to unexpected behavior in external modules, so renaming the translation key seems a better approach.
