### ISSUE TITLE
Feature Request: Show selling prices on product card

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#4814]
## Environment
- **Version**: [_3.9.0_]
# Feature Request

[_The selling price and minimum selling price should show on the product card header to help quick product price lookup when searching or scanning_]

**Comment by marcosgdf** [comment]
It is not possible because selling price and minimum selling price is sometimes calculated on-the-fly, like it can vary depending on a customer, on a customer level, and so on.

**Comment by aljawaid** [comment]
Thanks for the reply.

In that case could you recommend a way to do a quick price lookup of a product?

**Comment by aljawaid** [comment]
What if in the new search box under Product and Services there was an option "Product Selling" and "Product Buying" so when we search and choose that option in the dropdown, it takes us to the selling price tab page of the product?

That would be a good work around if it could work.
