### ISSUE TITLE
Bug: suppliers invoices : empty list displayed on applying filters

### ISSUE THREAD

**Issue by toufikoj** [Dolibarr/dolibarr#4825]
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.46-0+deb7u1-log
- **URL**: /index.php?mainmenu=home&leftmenu=
# Report

On the supplier invoices, when applying filters on column head (supplier name for example), the request returns zero line.

**Comment by Numerals-SAC** [comment]
The same in version 3.9.1, filters doesn´t work.
