### ISSUE TITLE
Bug: upgrade 3.8.4 to 3.9.0 : Erreur DB_ERROR_1452: INSERT INTO llx_c_departements

### ISSUE THREAD

**Issue by Lenglemetz** [Dolibarr/dolibarr#4826]
Bug 3.8.4 to 3.9.0 upgrade script, update 3.8.3 to 3.8.4 it's OK

Request 159 sql='INSERT INTO llx_c_departements ( code_departement, fk_region, cheflieu, tncc, ncc, nom, active) VALUES ('011', 5202, '', 0, '', 'Abel Iturralde', 1);'
Erreur DB_ERROR_1452: INSERT INTO llx_c_departements ( code_departement, fk_region, cheflieu, tncc, ncc, nom, active) VALUES ('011', 5202, '', 0, '', 'Abel Iturralde', 1);
Cannot add or update a child row: a foreign key constraint fails (`dolibarr`.`llx_c_departements`, CONSTRAINT `fk_departements_code_region` FOREIGN KEY (`fk_region`) REFERENCES `llx_c_regions` (`code_region`))

Screenshot

![Alt text](https://www.lenglemetz.com/p/dolibarr.png?raw=true)

**Comment by eldy** [comment]
Don't you have any error before first one on screenshot ?

Can you run manually the sql command

INSERT INTO  llx_c_regions (fk_pays, code_region, cheflieu, tncc, nom, active) values ( 52, 5202, '', 0, 'La Paz', 1);

what happened ?

**Comment by Lenglemetz** [comment]
Not any errors before the screenshot.

the sql command returns

Erreur
Requête SQL :

INSERT INTO llx_c_regions (fk_pays, code_region, cheflieu, tncc, nom, active) values ( 52, 5202, '', 0, 'La Paz', 1)
MySQL a répondu: Documentation

#1062 - Duplicate entry '0' for key 'PRIMARY'

I solved the problem by : SET FOREIGN_KEY_CHECKS=0; in the 3.8.0-3.9.0.sql file
but I do not think this is a solution

**Comment by eldy** [comment]
It seems the field   rowid of table llx_c_regions has not flag "autoincrement". Can you check ?

**Comment by Lenglemetz** [comment]
Screenshot

![Alt text](https://www.lenglemetz.com/p/github/1.png?raw=true)
![Alt text](https://www.lenglemetz.com/p/github/2.png?raw=true)
![Alt text](https://www.lenglemetz.com/p/github/3.png?raw=true)
![Alt text](https://www.lenglemetz.com/p/github/4.png?raw=true)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by Lenglemetz** [comment]
Hi, ok...

It's not fixed

Regards
