### ISSUE TITLE
bug : can't add a projet on event

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#4828]
Project dropdown list on event creation card remains empty. Yet, I have project (linked to the customer and open status) 
![image](https://cloud.githubusercontent.com/assets/11922840/13785925/d909840a-ead5-11e5-9956-aa2c128c489d.png)

Have to create the event and to edit to modify and save the project

**Comment by eldy** [comment]
I can't reproduce on 3.9
Are you sure you are a contact of at leas one project (to see them) ?
Can you reproduce on demo.dolibarr.org ?

**Comment by RomainDeschamps** [comment]
Works on your environnement

Yes, my user is assigned to all project (draft or open)

I use 3.9.0 zip version. Do you use backported version ?
Is there another setting allowing superadmin user to see the project list ?

![image](https://cloud.githubusercontent.com/assets/11922840/13880134/2b441a9a-ed1b-11e5-8078-a0b3c5e95b9e.png)
