### ISSUE TITLE
Bug: supplier invoice list filtering not working

### ISSUE THREAD

**Issue by lucanot** [Dolibarr/dolibarr#4830]
When I try to filter the list of supplier invoices from left menu , and I just put the year/month, no results are shown. 
However, if I manually force the query (without the unrequested parameters): /dolibarr/htdocs/fourn/facture/list.php?action=list&sortorder=desc&month=02&year=2016  
from the address bar, it works
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache/2.2.15
- **PHP**: apache2handler 5.5.32
- **Database**: MySQL or MariaDB 5.5.48
- **URL**: /dolibarr/htdocs/fourn/facture/list.php?token=6b4734c1166cb189bea 1a2297b6137f5&action=list&sortfield=fac.datef%2Cfac.rowid&sortorder=desc&viewstatut=&search_ref=&search_ref_supplier=&month=03&year=2016&month_lim=&year_lim=&search_label=&search_company=&search_amount_no_tax=&search_amount_all_tax=&search_status=-1&button_search.x=0&button_search.y=0&button_search=Ricerca
# Report

**Comment by lucanot** [comment]
sorry!!
I did not noticed that someone else opened the same issue... 
Is possible to merge both?

**Comment by eldy** [comment]
Just mention the other issue into a comment by adding the # and number of issue in your comment.

**Comment by cdtadel** [comment]
you must change code at "fourn\facture\list.php" and replace 
if ($search_status != '  ')
{
    $sql.= " AND fac.fk_statut = ".$search_status;
}
at line  228   

if ($search_status != ' '**&& $search_status >= 0**)
{
    $sql.= " AND fac.fk_statut = ".$search_status;
}

**Comment by lucanot** [comment]
It works!!! 
many thanks,
