### ISSUE TITLE
Bug: Fatal error: photo utilisateur

### ISSUE THREAD

**Issue by hprieur** [Dolibarr/dolibarr#4832]
# Environment
- **Version**: 3.9.0
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/user/card.php?id=2
# Report

Après avoir téléchargé une photo au format JPG pour un profil d'utilisateur, et clic sur la photo : 
j'ai le message suivant
Fatal error: Call to a member function trans() on a non-object in C:\dolibarr\www\dolibarr\htdocs\user\class\user.class.php on line 259

**Comment by jccs1953** [comment]
The same problem is occurring on the Linux Platform as well but in this case it generates a server 500 error and crashes the program

**Comment by frederic34** [comment]
Related with https://github.com/Dolibarr/dolibarr/commit/83dd3081d5f39139b16f71f67ad0bdffdc41a71b

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
