### ISSUE TITLE
Mot de passe modifié aléatoirement

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#4833]
# Bug

Je viens de mettre à jour mon Doli vers 3.9. Et quand je modifie des informations dans mon profil sans remplir le champ mot de passe (car je ne veux pas le modifier), mon mot de passe est alors modifié sans raison.
J'ai testé sur un Dolibarr fraichement installé, j'ai constaté le même problème. Idem lors d'une modification sur un autre utilisateur.
## Environment
- **Version**: 3.9
- **OS**: Debian 8 Jessie
- **Web server**: Apache 2.4.10
- **PHP**: PHP 5.6.17
- **Database**: MySQL 5.5.47 // Mariadb 10.0.23

**Comment by hregis** [comment]
effectivement, la correction : https://github.com/Dolibarr/dolibarr/pull/4834
