### ISSUE TITLE
Emails : allow more constants

### ISSUE THREAD

**Issue by fredt34** [Dolibarr/dolibarr#4838]
## Environment
- Dolibarr 3.9.0 (upgraded today from 3.8.3 - had the same bug)
- Ubuntu 14.04
- MySQL 5.5.47
- php 5.5.9
## Feature Request

It would be nice to have at least those constants:
### Orders
- Date of order
- Total price (with and without VAT)
- Delivery date
### Invoices
- Date of invoice
- Date due
- Total price (with and without VAT)

Thanks for this software & the recent versions !

**Comment by atm-maxime** [comment]
I think this is done now :)
