### ISSUE TITLE
bug : e-mails background color not applied

### ISSUE THREAD

**Issue by RomainDeschamps** [Dolibarr/dolibarr#4841]
# Bug

background color for emailing selected in creation is not applied in memail body
## Environment
- **Version**: 3.9.0 (lower version too)

**Comment by atm-gauthier** [comment]
Hi,
I tried on Dolibarr 3.8
It works, but it depends on your webmail.
In Gmail, css background color display is not allowed.
In hotmail, color is available.
Gauthier.

**Comment by atm-gauthier** [comment]
Gmail :
![image](https://cloud.githubusercontent.com/assets/5585819/16491743/6dd3dc68-3edf-11e6-9e4a-6e74ddf7cb52.png)

**Comment by atm-gauthier** [comment]
Hotmail :
![image](https://cloud.githubusercontent.com/assets/5585819/16491793/a46efaf0-3edf-11e6-9db3-3c67c008dd9f.png)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
