### ISSUE TITLE
Bug: error in third party list with an extrafield separator

### ISSUE THREAD

**Issue by joseplluis** [Dolibarr/dolibarr#4846]
# Bug

If you have a Separator extrafield for Third parties and shows any list of Third parties, an exception is thrown. 
Last DB code error: DB_ERROR_NOSUCHFIELD
Last DB description error: Unknown column 'ef.separator1' in 'field list'
## Environment
- **Version**: 3.9.0
- **OS**: Linux 3.16.0-67-generic #87~14.04.1-Ubuntu SMP
- **Web server**: Apache/2.4.17 (Unix) OpenSSL/1.0.1q PHP/5.6.15 mod_perl/2.0.8-dev Perl/v5.16.3
- **PHP**: 5.6.15
- **Database**: MySQL or MariaDB 5.5.5-10.1.9-MariaDB
- **URL(s)**: 
  htdocs/societe/list.php?type=c&leftmenu=customers
  htdocs/societe/list.php?leftmenu=thirdparties
## Steps to reproduce the behavior

1) Add a Separator extrafield for Third parties
2) Show any list of Third parties

**Comment by aljawaid** [comment]
This happens to any extra field seperators

I had to remove my seperators in extra fields to access the product list and search function

**Comment by joseplluis** [comment]
Solved with #4812
