### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by debastiani** [Dolibarr/dolibarr#4848]
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
- **PHP**: cgi-fcgi 7.0.3
- **Database**: MySQL or MariaDB 5.5.48-cll
- **URL**: /compta/tva/index.php?leftmenu=tax_vat&mainmenu=accountancy
# Report

When make a partial payment (type 50-50) to an invoice, the INSS receive a duplicated payment if the payment is made in different months.

**Comment by marcosgdf** [comment]
Which is the INSS?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
