### ISSUE TITLE
Password Erasure 

### ISSUE THREAD

**Issue by jccs1953** [Dolibarr/dolibarr#4854]
**# Bug
[Password erasure]**
## Environment
- **Version**: [ 3.9.0-4 ]
- **OS**: [LInux Mint 17.3 - Ubuntu 14.04*]
- **Web server**: [Apache/2.4.7 (Ubuntu)]
- **PHP**: [5.5.9-1ubuntu4.14]
- **Database**: [MySQL or MariaDB 5.5.47-0ubuntu0.14.04.1]
- **URL(s)**: [localhost and production servers to many to list]

**## Expected and actual behavior**
**Expected :** When changing a picture it should accept the picture and not erase the password
**Actual:** When you enter any user to change the picture on it using *\* modify*\* it erases the password field and leaves it blank this is especially bad if you do it to the superuser account as you will not be able to access the database on your next login.  

**Work around :**
I always create a second superuser to  give me access to the database should the super user account become corrupted. 

**## Steps to reproduce the behavior**
1. Create a user and save
2. Access that user to add a picture 
3. Add a picture ( usually this fails) creates a broken link to it
**Fatal error: Call to a member function trans() on a non-object in /home/content/73/8131273/html/main3/crm390/system/user/class/user.class.php on line 259**
**_4. NOTE: the password field is blank if you save it at this point this user will be unable to access the database_**
5. **NOTE : My work around:** always re-enter the password in the blank password field
then save this puts the password back in the field

**Comment by aljawaid** [comment]
I did this too and since I managed to use the work around...now my pictures and barcodes all show up broken on the site...Dunno if its related.

**Comment by jccs1953** [comment]
No it isn't related the erasure issue is what I discovered after trying and failing to load pictures on my user accounts fortunately I created a second superuser and was able to access the database otherwise I would have been SOL without a key to get back in

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
