### ISSUE TITLE
Feature Request : Remove all "PROV"

### ISSUE THREAD

**Issue by mrsof** [Dolibarr/dolibarr#4867]
# Feature Request

Add option to remove all the "PROV" at once
## Use case

This day I have 106 proposals...
So I'd like to not have to delete them one by one. 
## Suggested implementation

By feature (Order, Invoice...) or globally.

**Comment by marcosgdf** [comment]
Why do you have so many provisional proposals?

**Comment by mrsof** [comment]
I am not sure to understand the question.

**Comment by marcosgdf** [comment]
Why do you have more than 1 PROV proposal open at a time?

**Comment by mrsof** [comment]
Well I'm still don't understand...
Some explanations to be more explicit. All the staff uses proposals to calculate prices. But they don't always validates the proposals. They prefer to let it open and jump to another customer. So if your question is about practice, I know we should do as expected by Dolibarr. We are working on this...

If your question is specifically technic, I don't know...

Anyway, we should be able to delete all "non validated" pieces (PROV) at once for cleaning purposes, IMHO.

**Comment by jccs1953** [comment]
Actually they should be trained to validate them and not leave them open like this, Even if you do validate them you can still go back in and change the proposals there is no need to leave them open as PROV's 
it serves no purpose except to do what is happening now in your system having 100's of them open. Try it it works believe me validate them after you create them

**Comment by mrsof** [comment]
OK excellent :+1: . Now I know what to do. Thank you so much.

**Comment by clamisch** [comment]
Just I wanted to mention that I do not see in many cases need to go through a PROV. Ought may be optional in each module or as a parameter (Settings / Other) example MAIN_DISABLE_PROV_IN_MODULES

**Comment by mardonioe** [comment]
Hello guys!

I'm new here at GIT, I've been studying and used Dolibarr for some time.

I have already tested some versions and still is not a solution.

The Ideal, for this PROV question, was that the Dolibarr allowed the use of one name for the other, in my case here in BRAZIL would be ORDERING {XXX}

Can you tell me if any version higher than 5.0.4 exists this option?

Thank you so much!

**Comment by atm-maxime** [comment]
Dolibarr base document creation process always starts by a draft document which is the status in which the user can add/modify data in the document. The document reference at this point is PROV. When user validates the document (saying "I finished working on it") then the "real" reference is generated.
Exactly the same when you create a new .doc document on your computer, the draft doc default name is "untitled document.doc".

And with last versions you can mass delete documents from the lists, so it's easy to remove draft proposal with a bulk action.
