### ISSUE TITLE
Bug: user Avatar gets bigger and covers the entire screen in all the therms except the default eldy.

### ISSUE THREAD

**Issue by priyarajpr** [Dolibarr/dolibarr#4868]
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache Phusion_Passenger/4.0.10 mod_bwlimited/1.4 mod_fcgid/2.3.9
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL or MariaDB 5.5.45-37.4-log
- **URL**: /erp/admin/ihm.php?mainmenu=home&leftmenu=setup
# Report

**Comment by aspangaro** [comment]
In Dolibarr 3.9. All themes are deprecated. Only Eldy and MD are compatible.
