### ISSUE TITLE
Bug: Dolimail thirdparty code is integrated into Dolibarr core code

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4875]
# Bug

In 3.9, there is some code referencing a thirdparty module called "Dolimail". In Dolibarr wiki we can read that code from external modules should not be included in Dolibarr and this can be also considered as unfair competition to modules published in Dolistore that follow the rules.

**Comment by BebZ** [comment]
This module is useful to send mails from thirdparty card but the author didn't know his code was integrated...
Complete integration is a good solution ?

**Comment by marcosgdf** [comment]
What do you mean by saying that the author didn't know his code was integrated? 

It looks like it was accepted by Eldy here https://github.com/Dolibarr/dolibarr/pull/3412

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by marcosgdf** [comment]
Still happening in the latest version.
