### ISSUE TITLE
Bug: Product Pic and Barcode suddenly fail to load/generate

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#4880]
![capture](https://cloud.githubusercontent.com/assets/10233708/13983379/3d954c8a-f0e7-11e5-94a8-1e516669a6a0.PNG)
# Bug

_Loading any product normally when I upgraded to 3.9.0 showed the picture and barcode of the product on the main product page and in the tooltips. For the last two days, both the picture and the barcode fail to generate showing a broken image link_

When I download the picture file it is ok. When I find the picture file from the documents area it exists but will not load anymore.  I have only started using product pictures with 3.9.0.
## Environment
- **Version**: [_3.9.0_]
- **OS**: [_Server OS type and version_]
- **Web server**: [_Webserver type and version_]
- **PHP**: [_PHP version_]
- **Database**: [_Database type and version_]
- **URL(s)**: http://domain.co.uk/workflow/viewimage.php?modulepart=product&entity=1&file=%2Fpasabahce-generation-bowl-13%2Fpasabahce-generation-bowl-13.jpg
## Expected and actual behavior

Picture and barcode should load as they did up to a few days ago.

**Comment by aljawaid** [comment]
Can anybody help with this?

**Comment by aljawaid** [comment]
Google Chrome Inspector Tools say this:

**_Failed to load resource: the server responded with a status of 500 (Internal Server Error)**_

VM786:61 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Am I the only one who cannot get the product pics and barcodes to show up?

**Comment by hregis** [comment]
you tried a different browser?
you have installed or you use external modules?
can you test with Firefox with firebug plugin and look the error console ?

**Comment by aljawaid** [comment]
Hello, thanks for replying.
- I have tried chrome and firefox (latest versions) with the same problem.
- no external modules
- firebug shows this error on a product with just a barcode (no pic):
  "NetworkError: 500 Internal Server Error - http://domain.co.uk/workflow/viewimage.php?modulepart=barcode&generator=phpbarcode&code=6291100737413&encoding=EAN13"

**Comment by aljawaid** [comment]
....on a product with a picture and a barcode this is the error from firebug:
"NetworkError: 500 Internal Server Error - http://domain.co.uk/workflow/viewimage.php?modulepart=product&entity=1&file=%2Fkitchen-devils-large-cook%2Fkitchen-devils-large-cook.jpg"

"NetworkError: 500 Internal Server Error - http://domain.co.uk/workflow/viewimage.php?modulepart=barcode&generator=phpbarcode&code=5010624437446&encoding=EAN13"

"NetworkError: 500 Internal Server Error - http://domain.co.uk/workflow/viewimage.php?modulepart=product&entity=1&file=%2Fkitchen-devils-large-cook%2Fkitchen-devils-large-cook.jpg"

**Comment by hregis** [comment]
and in the Apache logs ?
you are this in the /conf/conf/php ? : 
`$dolibarr_main_prod='0';`

**Comment by aljawaid** [comment]
**this is from my server error log:**
domain.co.uk [Tue Mar 29 09:12:10 2016] [error] [client 79.77.247.50:60555] AH01215: PHP Fatal error:  Call to a member function trans() on a non-object in /home/sites/domain.co.uk/public_html/workflow/user/class/user.class.php on line 259: /home/sites/domain.co.uk/public_html/workflow/viewimage.php

*_yes *_ the conf.php has `$dolibarr_main_prod='0';`

**Comment by hregis** [comment]
edit the file viewimage.php and comment this line : 

`if (! defined('NOREQUIRETRAN'))        define('NOREQUIRETRAN','1');`

with

`//if (! defined('NOREQUIRETRAN'))      define('NOREQUIRETRAN','1');`

**Comment by aljawaid** [comment]
wow it works!

product pictures and barcodes now show up properly.

Thank you so much for your help. It is very much appreciated.  I hope this is corrected in the next version.
