### ISSUE TITLE
Bug：Attach document can't be remove

### ISSUE THREAD

**Issue by leangjia** [Dolibarr/dolibarr#4889]
1.[user]->SuperAdmin ->[Linked files ]->[Attached files and documents]
2.remove failed
3.Tip show removed.

tks.
@eldy

**Comment by marcosgdf** [comment]
Can you please tell us which version is facing the problem?

**Comment by eldy** [comment]
Looks fixed in last version. If not confirm your version and tell use on which object do you have this. Can you reproduce on demo.dolibarr.org ?

**Comment by leangjia** [comment]
@eldy Very good.
By the way,what is Prof. mean in https://www.transifex.com/dolibarr-association/dolibarr/translate/#zh_CN/$/12453213?q=Prof

**Comment by eldy** [comment]
Prof. Is shortcut for professional.
Prof phone = business phone
