### ISSUE TITLE
Extrafield error with object reference and another extrafield

### ISSUE THREAD

**Issue by neo7-studio-web** [Dolibarr/dolibarr#4897]
Dolibarr 3.9.0
Centos 6.7
- Create a contract extrafield, linked to object : 
  Societe:/societe/class/societe.class.php
- Create another contract extrafield, text

In the contract card : 
- Fill-up linked extrafield
- Fill-up text extrafield

> Reference error

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
