### ISSUE TITLE
software name

### ISSUE THREAD

**Issue by costa06** [Dolibarr/dolibarr#4902]
hello, i am looking  in vain for files including declaration of the software name; may I have your help please
thank you

**Comment by marcosgdf** [comment]
?

**Comment by BebZ** [comment]
For what ? Erasing it ?

**Comment by rdoursenaud** [comment]
MAIN_APPLICATION_TITLE?
https://wiki.dolibarr.org/index.php/Setup_Other#List_of_known_hidden_options

**Comment by rdoursenaud** [comment]
Anyway, not an issue, closing.
