### ISSUE TITLE
REST explorer error

### ISSUE THREAD

**Issue by nka11** [Dolibarr/dolibarr#4912]
# Activating REST services -> navigation link
- bug with PHP 7 :
  Fatal error: Cannot use Luracast\Restler\Data\String as String because 'String' is a special class name in dolibarr/includes/restler/framework/Luracast/Restler/Resources.php on line 4
- referenced in Luracast/Restler#505 - fix by moving to RC6

**Comment by eldy** [comment]
The REST explorer become completely ok with Dolibarr 5.0. Fixed in dev
