### ISSUE TITLE
Bug: N° NAF-APE

### ISSUE THREAD

**Issue by jimibi** [Dolibarr/dolibarr#4918]
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.17
- **Database**: MySQL or MariaDB 5.5.46-0+deb7u1-log
- **URL**: /htdocs/societe/soc.php?socid=80
# Report

Dans la fiche Tiers(Prospect / Client) le code NAF-APE ne peut jamais être en doublon.

**Comment by hregis** [comment]
ce n'est pas un bug, dans la configuration du module Tiers, mettre à Off le bouton "Doit être unique ?" du code NAF/APE

**Comment by jimibi** [comment]
OK Merci, je n'avais pas vu cette option.
