### ISSUE TITLE
Delivery is not related to shipping.

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#4930]
On 3.8.4, when generating a delivery order, everything works except that the information is not related to shipping, but stored in the database. In short, impossible to see a BL without ID, and thereby generating a multitude of delivery believing that this is not taken into account.

**Comment by BebZ** [comment]
Do you mean this box is not displayed on order card (/commande/card.php?id=...) ? 
![image](https://cloud.githubusercontent.com/assets/3694135/14201984/9b96f454-f7f5-11e5-8ccb-b691fb7e7a81.png)

**Comment by philazerty** [comment]
Hi !
I talk about delivery, not shipping
![delevery1](https://cloud.githubusercontent.com/assets/3629675/14217386/eddf3a52-f84d-11e5-893a-06a3ea39afbc.png)
After validation delivery
![delevery2](https://cloud.githubusercontent.com/assets/3629675/14217396/06883f04-f84e-11e5-9641-68f597621fe7.png)
Once out of the order, no trace of delivery except to know the ID of the delivery is recovered by livraison/card.php?Id=333 for example

**Comment by philazerty** [comment]
ça ressemble à https://github.com/Dolibarr/dolibarr/issues/4372 corrigé sur une 3.9

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
