### ISSUE TITLE
Feature Request: Please improve "Build RUM number" for a customer bank account

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#4932]
At the moment there is no possibility to edit or set an own RUM number for SEPA direct credit mandates, because Dolibarr supports the static function "buildRumNumber" in `/compta/prelevement/class/bonprelevement.class.php` only.

In case that you will inform your clients at a later time about the RUM this is more or less okay. But in any other case this is not a really good solution. The RUM should really be stored in the Database so that one can be absolutely sure that it will not change e.g. because of some adoptions in later versions of Dolibarr.

And in any case it should be possible to change or set the number at least one time - when creating the new bank account.

**Comment by sbschumacher** [comment]
By the way: the date of the mandate is also missing...

**Comment by eldy** [comment]
Fields rum and date_rum are ready into table llx_societe_rib for 4.0.
Still waiting a dev for implement screen to edit/store them.

**Comment by camlafit** [comment]
Hi

On 5.0 edit RUM is possible but must save first with autogeneration and edit after to set own RUM value
