### ISSUE TITLE
Feature Request: Add SELECT ALL BOX for Reconcile Bank Transactions

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#4941]
## Environment
- **Version**: 3.9.0
# Feature Request

Add a _Select All_ checkbox when reconciling transactions in bank accounts.  It is hard to manually tick 200 checkboxes per month to reconcile into a statement.  

A Select All checkbox would make it easier to select all on the page.

**Comment by marcosgdf** [comment]
I don't recommend it. Reconciliation is to check every bank transaction in Dolibarr with the bank statement. If you mark them all as reconciled without checking them one by one then you are not doing it properly. You can disable it if you want to.

**Comment by aljawaid** [comment]
@marcosgdf I sort of agree with you but what If was an advanced user permission?

Use Case:  We use some dolibarr bank accounts as internal accounts to log certain transactions to payments for a service.  It has nothing to do with a real bank.  The money is separated from the business daily and then at the end of the month that money is compared/reconciled to whatever was recorded in the dolibarr bank account.  As long as the total matches the actual money we reconcile all the transactions to that month.  So in this case if a supervisor could just reconcile all transactions it would be easier.
