### ISSUE TITLE
Introduce a Ticket module

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4948]
Introduce a Ticket module

**Comment by rdoursenaud** [comment]
AFAIK @jfefe has already made one

**Comment by jfefe** [comment]
Yes @rdoursenaud and one day or another it will be merged into core. Wait and see ;)

**Comment by MvErven** [comment]
Currently we are sort of "abusing" the projects with assigning tasks to achieve this. But it's not perfect. Missing a few features. (Like moving a completed task to another project) Also, the project never closes and tasks remain on 100%  Looking forward for such a feature. (Currently wrote my own small ticket system (not in Dolibarr) and in testing stage. Will follow this ;)

**Comment by cmmata** [comment]
@jfefe is it available as a module or something we can take a look at before that day comes? :)
