### ISSUE TITLE
Enhance the CMS module to build web sites. Must support edition inline, edit with mouse and drag and drop.

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4949]
Introduce a web site module

**Comment by QuentinSu** [comment]
I made one module which allow dolibarr user to add multiple external websites. He have just to add an URL, a name for top menu, and (optionnal) a website logo.

**Comment by eldy** [comment]
This is not the topic. The topic here is to add a CMS feature to allow a user to develop its own web site inside dolibarr. To remove completely prestashop or magento.
Dev is already seriously advanced into develop branch.

**Comment by eldy** [comment]
To keep
