### ISSUE TITLE
Introduce a bank reconciliation module from a bank file

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4950]
Introduce a bank reconciliation module that can do the work automatically from bank receipts

**Comment by pangoSE** [comment]
I would like to know what is needed to implement this.
I see we already include phpspeadsheet.

As an aside: This function is implemented in Python in Odoo that might be of help https://www.odoo.com/apps/modules/12.0/muk_account_bank_statement_import_sheet/ 
Here after upload the contents of the statement columns are displayed to the user as a table and the user can map the data to the data types in Odoo. E.g. specify the date-format in the date column. And specify which columns contain data worth importing (label, date, etc.)
This is useful as the export from different banks in different regions of the world is not uniform at all.

**Comment by atm-maxime** [comment]
Allow to import a file containing bank statements, then the user will be presented each line and reconcile them with Dolibarr elements.

**Comment by mannp** [comment]
I was loving Dolibarr until I found I had to enter my bank statements in line by line :(

Hoping bank statement import could be added.

**Comment by AshleyButcher** [comment]
Changes I describe in #25771 might be needed here (to create a new table to store statement header details).

There are a number of standard statement formats banks provide in Europe, but Swift MT940 format is commonly available for export from banks which would make it an ideal candidate as an initial format.

It would be interesting to tackle this, I wish I had the time.
