### ISSUE TITLE
Introduce an inventory feature

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4951]
Introduce a feature to make quickly an inventory in one screen.

**Comment by aljawaid** [comment]
It would be nice to use the stock module or something similar where we could scan the batch barcode of the product or each product and add the quantity received and cost price and select the supplier from our list or have the option to create a new one.

At the moment, Dolibarr relies on the supplier invoices to use the stock module. An inventory feature would be an advanced separate type of stock module where we can quickly add stock where dolibarr supplier invoices are not used.

This is my suggestions on an inventory feature anyway, similar to what I have seen for offline windows-based software and very helpful to shop owners.

**Comment by BebZ** [comment]
Maybe you know http://mobilid.eu/fr/index.html
it's a mobile app that access your supplier / customer orders.

it can scan batch codes with barcodes like EAN128  and autopopulate when you dispatch products to stock or make the picking of an order.

> batch barcode of the product or each product and add the quantity received

Application Identifier (AI) Data elements
00  Serial Shipping Container Code (SSCC) – SSCC (n2 + n18)
01  EAN of the trading unit (n2 + n14)
10  Batch or Lot Number / Charge Number (n2 + an..20)
11  Production Date (n2 + n6)
15  Best Before (YYMMDD)

7001    Stockkeeping Unit (SUK)

The dev @fappels is really reactive ;)

> cost price and select the supplier from our list or have the option to create a new one.

For this one you may want to ask him a quotation for a small modification of code of his module free dispatch, maybe... this quote we can share if you want ;)

**Comment by QuentinSu** [comment]
I made one but very specific for my company. Despite, i can help you on your development.

**Comment by atm-maxime** [comment]
Module inventory is in experimental status, must be debugged :)

**Comment by BebZ** [comment]
on which version is it on experimental ? I need to experiment    :) !!
:package: :package::package: :package::package: :package:

@aljawaid  "scan the batch barcode of the product or each product and add the quantity received "
mobilid does it when you select the correct supplier order you can populate fields by scanning "batch" barcode if it recognizes
 like this one (many of our suppliers use this one) :
 
![image](https://user-images.githubusercontent.com/3694135/49364161-ee404a80-f6e3-11e8-8631-fe8bd4b5348c.png)
https://stackoverflow.com/questions/34040995/how-to-properly-generate-a-gs1-128-formerly-ean-128-barcode-in-tcpdf

For this end of year's inventory I am thinking of printing all the sticker's products (one for each product batch with qty) : i will put one sticker on the last product batch to pick and one on the shelve to check where it is stored visually.

**Comment by eldy** [comment]
To keep

**Comment by eldy** [comment]
@Hystepik You can ignore previous point of this thread. This is the step to do to complete this tasks.
Move your dolibarr into experimental mode by setting in home - setup - other the constant MAIN_FEATURES_LEVEL to 2
you should see menu Inventory into home - product.
Create a new inventory, click on "Start". Goal is to finish the feature... (we can exchange by visio on this)
