### ISSUE TITLE
Debug expert accountancy module and add reports

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4953]
Debug expert accountancy module

**Comment by Darkjeff** [comment]
@eldy tell me what we need to correct
we will soon commit the account result (next week)
And next month we work on VAT

**Comment by eldy** [comment]
@Darkjeff I have no specific/bug thing to report yet. The task is a genric task to say one of priorities of project is to test and make module mature.

**Comment by eldy** [comment]
v7 contains enough reporting feature so I close this FR
