### ISSUE TITLE
Add Extra Fields into new search box

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#4970]
## Environment
- **Version**: 3.9.0
# Feature Request

Example:
I have product barcode (standard ean) and package barcode (saved as extra field in products).
When i scan the barcode for the product and choose Products and Services it finds the product.
If I scan the package barcode which i know is saved in my extra field it won't find it.

Does anyone know how to include the extra fields into search?

**Comment by eldy** [comment]
Currently list of fields used after a search is defined into array
$fieldstosearchall
into the file list.php of the object searched.
So list is currently hard coded. This may change in a future but i cant tell when.

**Comment by aljawaid** [comment]
Thanks for the reply.  I hope in future versions we can choose which fields to include in the search box.
