### ISSUE TITLE
Feature request: SQL errors in login page should not be shown to the user

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4971]
Version: 3.7

The error was forced, but the problem should be logged and not printed to the screen

![captura de pantalla 2016-04-08 a las 20 05 17](https://cloud.githubusercontent.com/assets/168744/14393081/40b8861c-fdc5-11e5-8740-7ff194b13b1f.png)

**Comment by gnovaro** [comment]
I think maybe you need run again the installation. Something is wrong with your db "missing column". Check your config, In local env is common see errors.
