### ISSUE TITLE
user.login should be same type as email

### ISSUE THREAD

**Issue by nka11** [Dolibarr/dolibarr#4988]
# Feature Request

user.login should be same type as email
## Use case

Allowing users to use email as login identifier
## Suggested implementation

`ALTER TABLE`llx_user`CHANGE`login` `login` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;`
## Suggested steps

push alter table SQL update script

**Comment by marcosgdf** [comment]
Why?

**Comment by nka11** [comment]
Allowing a user to use his email as login id.
Otherwise, allow login using username OR email (like github for example), I know it's a bit more complicated to implement, but I could plan to send PR for it if you think this will be appropriate.

**Comment by hregis** [comment]
heuuuu ! the email address of a user can already be used for login ! :-)

**Comment by nka11** [comment]
indeed, that's not explicit on the login screen. Thanks for this information.

**Comment by hregis** [comment]
@nka11 yes you're right
