### ISSUE TITLE
Store the "vat code" with product prices 

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#4993]
So in a future we will be able to manage several vat with same rate, like we need to manage vat with NPR with OM-OMR and vat NPR without OM-OMR by keeping the vat combo box always visible.

**Comment by eldy** [comment]
Done

**Comment by BebZ** [comment]
So it is possible to sell a product, let's say to 
a "country" customer with VAT (example 20%)
an "outside country" customer without VAT (0%) ?

> Is it automatic to have VAT of the product defined in accordance to customer (subject to VAT : yes/no)... ?
