### ISSUE TITLE
Bug: creating an invoice doesn't make supplier order "Billed"

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#4994]
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL or MariaDB 5.6.29-log
- **URL**: /dolibarr/fourn/commande/list.php?leftmenu=orders_suppliers
# Report

Having a supplier order, delivered, and I hit the "Create invoice", make the supplier invoice and set the payment at the due date of the invoice, the system shows the order unbilled, however, at the order card I'm seeing the invoice at "Related supplier invoices" part.

**Comment by marcosgdf** [comment]
Where do you see the system shows an order unbilled?

**Comment by vanyolai** [comment]
fourn/commande/list.php?leftmenu=orders_suppliers
Supplier orders/list rightmost column "Billed"

**Comment by marcosgdf** [comment]
I see the property is only updated when using the "Mass Invoice orders" function

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
