### ISSUE TITLE
Bug: Product list filter

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#4995]
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL or MariaDB 5.6.29-log
- **URL**: /dolibarr/product/list.php
# Report

When listing all the product and apply a filter (Without tag/category) and you want to go to the second page of the result list, the filter is gone.

**Comment by simnandez** [comment]
Solved in future 3.9.1
