### ISSUE TITLE
Feature Request: Create OFFLINE Mode

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#4996]
## Environment
- **Version**: 3.9.0
# Feature Request

Create "offline mode" in dolibarr on self-hosted web install so that we can continue working when there is no internet connection and push changes to database manually or when the internet is active.
## Use case

The POS is slow when a customer is standing in front of you to make a sale. The search and browsing is slow and in a shop environment it is not possible (too many clicks/steps) to create a customer for everybody who walks in. Dolibarr is fantastic but not so easy for simple walk-in random customers.
## Suggested implementation

A temporary offline cache file of some sort which will store the database changes and upload to server when the connection is next alive. Or allow self-hosted version to work with maybe DoliWamp so both versions would work together.

This would speed up browsing alot I'm guessing in offline mode.

**Comment by BebZ** [comment]
You may want to contribute for an open crowdfunding here ? 
http://www.dolipro.org/campaigns/module-standalone-phase-1/

all the details are welcomed.

**Comment by marcosgdf** [comment]
There is no need to install Dolibarr in a remote web server…

**Comment by aljawaid** [comment]
@marcosgdf What do you mean? The only reason why I installed it on my own domain was so that I could access dolibarr from home and work.  Is there a better and faster way?

**Comment by marcosgdf** [comment]
There are multiple ways of configuring it.

For example, you can load Dolibarr from a local webserver and retrieve the data from a remote SQL server. This way the scripts will be processed locally (faster), but the data is loaded from a remote server.

You can also install it locally in your work and allow accessing from a virtual private network at home. This way you will get a faster Dolibarr at work and a slower one at home.

**Comment by aljawaid** [comment]
@marcosgdf Thanks for the reply and apologies for the delay...

I only have a shared-hosted web space which is why I use my webhost for Dolibarr.  I don't have a VPN or local server.
