### ISSUE TITLE
Bug: IRPF (Localtax2) disappears after payment 

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5000]
# Bug

The calculation of the Spanish IRPF (localtax2) works fine when generating a supplier invoice. But after a payment for the given invoice, the localtax2 disappears in `llx_facture_fourn`.`localtax2` (= NULL).
## Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.20
- **Database**: MySQL 5.1.73-log

**Comment by marcosgdf** [comment]
You should sum the lines of llx_facture_fourndet.localtax2 to get the total IRPF amount of an invoice. Previous versions did not calculate it properly and set wrong info in that field

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
