### ISSUE TITLE
Ability to add to draft supplier order

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#5001]
# Feature Request

At the product card the ability to add the product to a draft supplier order
## Suggested implementation

The bottom "Add" part of the product card can include a dropdown list to add the product to the draft supplier order

**Comment by aljawaid** [comment]
oh I really do wish this was implemented :+1:

**Comment by atm-maxime** [comment]
The add section at the bottom of the product card has been removed.
