### ISSUE TITLE
Bug: Random End of script output results in 500 error

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5003]
# Bug

On shared hosting, yesterday I kept getting **500 Internal Server Error** blocking access to the site. I check with the hosting company and they said everything was fine on their side and told me to monitor the access logs due to so many errors. Below is an extract from my server error log related to Dolibarr.
## Environment
- **Version**: 3.9.0
## Server Error Log

`domain.co.uk [Tue Apr 12 14:46:03 2016] [error] [client 81.129.202.200:34602] End of script output before headers: datepicker.js.php
domain.co.uk [Tue Apr 12 14:46:04 2016] [error] [client 79.77.241.19:37179] End of script output before headers: card.php
domain.co.uk [Tue Apr 12 14:48:34 2016] [error] [client 81.129.202.200:45192] End of script output before headers: list.php
domain.co.uk [Tue Apr 12 14:49:39 2016] [error] [client 79.77.241.19:33098] End of script output before headers: style.css.php
domain.co.uk [Tue Apr 12 14:49:54 2016] [error] [client 79.77.241.19:53203] End of script output before headers: select2_locale.js.php
domain.co.uk [Tue Apr 12 14:49:56 2016] [error] [client 79.77.241.19:55325] End of script output before headers: lib_head.js.php
domain.co.uk [Tue Apr 12 14:51:09 2016] [error] [client 81.129.202.200:51429] End of script output before headers: viewimage.php
domain.co.uk [Tue Apr 12 14:52:43 2016] [error] [client 79.77.241.19:45473] End of script output before headers: index.php`

**Comment by ricweb74** [comment]
On version 3.8.3 suddenly following situation happened:
[Fri May 27 20:28:03.247841 2016] [fcgid:warn] [pid 90115:tid 139849971345152](104)Connection reset by peer: [client 2.234.xxx.xxx:59442] mod_fcgid: error reading data from FastCGI server, referer: http://mydomain/gestione/htdocs/comm/propal.php?id=25&action=editline&lineid=171
[Fri May 27 20:28:03.247923 2016] [core:error] [pid 90115:tid 139849971345152] [client 2.234.xxx.xxx:59442] End of script output before headers: propal.php, referer: http://mydomain/gestione/htdocs/comm/propal.php?id=25&action=editline&lineid=171

The output throws:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@mydomain to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

At the moment no idea how to solve that.
