### ISSUE TITLE
Bug: MySQL-Warning in /societe/consumption.php

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5004]
# Instructions

https://[...]/societe/consumption.php?socid=1234
# Bug

Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in /homepages/22/d563458159/htdocs/_mediasounddesign.com/office/core/db/mysql.class.php on line 343
## Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.20
- **Database**: MySQL 5.1.73-log
- **URL(s)**: https://[...]/societe/consumption.php?socid=1234

**Comment by atm-arnaud** [comment]
i'm currently working on this issue.
