### ISSUE TITLE
BUG : supplier invoice editing locked ?

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#5005]
# Bug

Supplier invoice not editable
even with no payment recorded
you can re-open it (after being classified paid)
but you can not modify it
## Environment
- **Version**: 3.8.3
- **URL(s)**: [_Affected URL(s)_] /fourn/facture/card.php?id=5612&action=edit
## Expected and actual behavior

I understand on customer side, any invoice validated should be corrected by a credit note.
On supplier side, this is not the expected behaviour, what we input should be possible to modify, no ?
Imagine you make a mistake when you record a supplier invoice... or your supplier decides to modify its invoice, and resends you...
## Steps to reproduce the behavior

Try to re-open and "edit" a recorde supplier invoice on 3.8.3
## [Attached files]

![image](https://cloud.githubusercontent.com/assets/3694135/14492741/a927385a-0181-11e6-8f25-1338edc3a7f8.png)

![image](https://cloud.githubusercontent.com/assets/3694135/14492768/d08861c6-0181-11e6-872f-b5a677855b92.png)

**Comment by marcosgdf** [comment]
I'm sorry but this is not caused by Dolibarr. Please do not report errors caused by 3rd-party modules

![captura de pantalla 2016-04-16 a las 18 08 26](https://cloud.githubusercontent.com/assets/168744/14582175/3e106454-03fe-11e6-9052-f67b53534e66.png)

**Comment by BebZ** [comment]
Sorry for this mistake. I will close it and report to @dark jeff or the editor of external module.

**Comment by BebZ** [comment]
Reope

**Comment by BebZ** [comment]
@darkjeff
