### ISSUE TITLE
3.9 impossible to modify user to be an admin

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#5014]
# Bug

When a user has been created not as an admin, when you want to modify its card to became admin, no acces to field admin. So it is not possible to chaneg the admin status from the user card 
Not possible even for Superadmin
# Feature Request

it shoud be possible to manage this through Dolibarrs IHM

**Comment by marcosgdf** [comment]
Confirmed.

**Comment by ghost** [comment]
Hi, i can't reproduce it on 3.9.1, maybe it was solved

**Comment by marcosgdf** [comment]
It is not…  It is reproductible in latest 3.9 commit
