### ISSUE TITLE
Bug: Clear text input when entering password in a new user form

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5021]
Version: 3.9 

![captura de pantalla 2016-04-16 a las 18 18 13](https://cloud.githubusercontent.com/assets/168744/14582232/940a9662-03ff-11e6-8fda-583bfe075c80.png)

**Comment by aschio** [comment]
@Eldy do you agree with @marcosgdf to replace text input type with password input type?

**Comment by atm-maxime** [comment]
For now it seems the right way. If we want  a hidden password field we should have 2 of them to check after POST...

**Comment by marcosgdf** [comment]
This might be the first time I see a clear text field for password purposes. I don't think everyone is wrong except Dolibarr.

**Comment by atm-maxime** [comment]
I agree, I didn't say everyone is wrong. I say this is a feature request.

**Comment by marcosgdf** [comment]
Oh, I understood your comment in another way. I now see the bug is reported in #4121
