### ISSUE TITLE
unexpected end of file on line 15401 tcpdf.php

### ISSUE THREAD

**Issue by lefablab** [Dolibarr/dolibarr#5040]
# Bug

[_A bug occurs when generating the PDF of an invoice: "unexpected end of file" in the script /htdocs/includes/tecnickcom/tcpdf/tcpdf.php one line 15401._]
## Environment
- **Version**: [_3.9.0_]
- **OS**: [_Linux webm247.60gp.ha.ovh.net 3.14.60-grsec-hosting-web-3.14 #1 SMP Wed Feb 17 13:41:21 UTC 2016 x86_64_]
- **Web server**: [_Apache_]
- **PHP**: [_5.6.20_]
- **Database**: [_MySQL 5.5.46-0+deb7u1-log_]
  ## Suggested steps
  [_I commented this line for now and everything seems to work again_]

**Comment by marcosgdf** [comment]
"I commented this line for now and everything seems to work again". Which line? The one that is causing the error?

**Comment by hregis** [comment]
@lefablab 
you have full details of the error? (XDebug)
often the error is an error to another file.

**Comment by lefablab** [comment]
@marcosgdf yes the line 15404 like this :
`//case 'C':`

**Comment by lefablab** [comment]
@hregis xdebug is not available on my shared hosting.
But the case "c" is not followed by an instruction that can be a problem?

**Comment by hregis** [comment]
@lefablab 
do you use a custom template pdf?
do you use external modules related to pdf or module where you generate the PDF?

**Comment by lefablab** [comment]
No we use the default module and the default template.

You can access a snapshot of the configuration of the "pdf" and "invoice" modules here: https://webcloud.zaclys.com/index.php/s/LPiWNeEZVzkC0NQ

I do not encounter this error on another installation of dolibarr with the same host and the same version. Amazing.

**Comment by marcosgdf** [comment]
Have you considerer replacing the file with a recently-downloaded one? Maybe it is an error of C&P files
