### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Knut33** [Dolibarr/dolibarr#5074]
# Bug
## Environment
- **Version**: 4.0.0-beta
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/supplier_proposal/card.php?id=11
## Report

Fatal error: Call to undefined method CommandeFournisseur::log() in C:\dolibarr\www\dolibarr\htdocs\fourn\class\fournisseur.commande.class.php on line 1159

Creating "Order" from a Accepted "Supplier proposals", "**Create draft**" Get "**Fatal error**"

**Comment by eldy** [comment]
Looks fixed
