### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Knut33** [Dolibarr/dolibarr#5075]
# Bug
## Environment
- **Version**: 4.0.0-beta
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/product/stats/card.php?id=all&leftmenu=stats&type=0
## Report

Statistics under Product and Service 
Get:
Warning: is_file() [function.is-file]: open_basedir restriction in effect. File(//propal12m_type0_byunit.png) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 698

**Comment by aconits** [comment]
Hi,
This looks like to a problem with permission
Can check the right access for www-data user about "documents" folder in you installation ? (recursivly access)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
