### ISSUE TITLE
Bug: Project list page does not list projects

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5088]
Version: 3.9.1
DB Type: Postgres

I create a project but the page does not list any project

**Comment by eldy** [comment]
Can't reproduce.
Can you reproduce on demo.dolibarr.org 
Are you sure your project is "opened" and not draft so it is visible in list ?

**Comment by marcosgdf** [comment]
It is happening with Postgres SQL. AFAIK, Demo site is working with Mysql

The project should be seen even if it is a draft or is not opened. This is happening with admin rights

**Comment by eldy** [comment]
I will be seen as draft, if the filter is not set on "Open" (which is default behaviour).
Do you have an error into the dolibarr.log file ?

**Comment by marcosgdf** [comment]
Oh. That's it. The filter was set to "Open" and because the page is not responsive I didn't notice the filter until I scrolled
