### ISSUE TITLE
Feature request: package product buying price is 0

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#5093]
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL or MariaDB 5.6.29-log
- **URL**: /dolibarr/commande/info.php?id=6
# Report

When adding a package product including children products wizh buying price, the buying price of the product will be 0 not the sum of the buying prices of the children products.

**Comment by atm-maxime** [comment]
I don't think this is a bug. Currently the buying price you have when you add a line on an order card is a select list containing suppliers buying prices and PMP. Your product doesn't have a supplier buying price because it's composed with sub-products.

So we should think about a feature request to add in the select list a buying price that is dynamically calculated from the sub-products.

**Comment by BebZ** [comment]
I agree, currently Dolibarr is poor on this side, we should calculate a mix of Pmp (average price of subproducts in stock) when we encode a sale with composed products to get a decent "buying" price...

Maybe the module of Altairis @altatof does this calculation with "produits composés" ?

**Comment by altairis-tof** [comment]
when you want to know if your business is ok, you use the margin module... and if you dont have costprices on packages, your margin reports are useless

**Comment by BebZ** [comment]
@altatof I don't understand link with " packages "  ? Is it like 2 subproducts make a package ?

**Comment by altairis-tof** [comment]
sorry my customer talk about "packs" more than "virtual products"

**Comment by Regimbal** [comment]
I second this request. That would be great.
Doing this would also allow the margin module to determine the cost of a virtual product and thus determine the margin when filling an offer or invoice...

**Comment by altairis-tof** [comment]
i did not check if it is done in last versions but it is very important to be done
