### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by DHPM** [Dolibarr/dolibarr#5109]
# Environment
- **Version**: 3.9.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.4.45-0+deb7u2
- **Database**: MySQL or MariaDB 5.5.47-0+deb7u1-log
- **URL**: /dolibarr/htdocs/margin/admin/margin.php
  Bonjour, je test la dernière version 3.9.1
  j'ai effectué la modification pour afficher les photos produits, tiers,...
  Cela fonctionne, par contre toujours des problèmes avec certains boutons on/off ajax.
- dans le partie "Configuration du module Commandes", le bouton "Demander pour l'entrepôt-source pour la commande" reste inactif.
- dans la partie "Paramétrage de la gestion des marges", tous les boutons reste inactif. 
  # Report
  ![bug dolibarr 1](https://cloud.githubusercontent.com/assets/18668083/14808258/19bee53e-0b84-11e6-89b5-3edf3913bef2.png)

**Comment by atm-maxime** [comment]
Hello,

Thanks for the feed back but I just tested on the last 3.9 version and I have no trouble with on/off ajax buttons. On both example you gave it works fine for me.

Maybe some cache in your browser?
