### ISSUE TITLE
Problem with users photos

### ISSUE THREAD

**Issue by remy38** [Dolibarr/dolibarr#5113]
hello,

After uploading a photo in JPG format to a user profile ,there isn't this photo but i did this modification (https://github.com/Dolibarr/dolibarr/commit/83dd3081d5f39139b16f71f67ad0bdffdc41a71b) i have always the same problem.
![capture du 2016-04-27 15 29 38](https://cloud.githubusercontent.com/assets/18398429/14853740/0d79ff34-0c8d-11e6-82f6-280a05f6a1eb.png)
when click on the photo i have this screen :
![capture du 2016-04-27 15 43 08](https://cloud.githubusercontent.com/assets/18398429/14854159/dd41b904-0c8e-11e6-86e7-1bcdae304e2b.png)

think of your attention,

**Comment by aconits** [comment]
Hi,
I can't reproduce probably fix in develop version
Maybe you had some specials characters or space in the name of picture or yourJPG file is in reality a PNG (extention renamed)
Last idea your file is corrupted

Give more informations if you can

**Comment by remy38** [comment]
hi,
but these are all pictures on my Dolibarr are like that.(logo compagny,pictures users or pictures products)

**Comment by remy38** [comment]
I just find  this error if a person with this problem go to the file I had to conf.php the end of my line conf.php file returns that I create without express with copy paste so you must remove any line breaks until:?>

cordially

**Comment by eldy** [comment]
Thanks for information.
Yes, no line break must ne present at end of conf.php file after the ?>. You can also completely remove the ?>.

So we can close request.
