### ISSUE TITLE
stability of base 'develop' branch

### ISSUE THREAD

**Issue by nka11** [Dolibarr/dolibarr#5117]
Some PR'ed contributions propose compliant code for travis check, unfortunately, these PR are marked failed in travis beacause code in master branch is itself wrong, due to commits pushed on it without being checked by continuous integration.
This is annoying for 2 reasons : 
- the base branch should _always_ remains stable
- PR's are maked as failing but they are totally clear in terms of code proposed

It's just a matter of process, lead devs should not push commits to base branch directly. Just like any other contributor, they should create PR's then merge when travis build is OK.
In fact, they should just be allowed to merge Travis-successed PR's.
This will avoid situations where the base branch is unstable.

Adopting such a process may also allow to re-enable unit tests in travis build. This is crucial for non-regression of base branch.

**Comment by eldy** [comment]
Sometimes PR are accepted even if travis fails because they are strategic work we don't want to loose and must interated quickly to reduce conflict of work of other. But when they are accepted, this is done with in mind to have travis error fixed just after. Travis error report should never last more than 1 days...
In a perfect word.

**Comment by rdoursenaud** [comment]
Or you could learn how to use git properly. Do the merge and required fixes on your local machine push them to your fork, make a PR and wait until the CI says it's OK for merging in the mainline. This way you wouldn't disrupt a whole community.
But I guess it's too much work…
I already voiced for this process a long time ago (many times actually) but it never caught on despite other developers approval. :disappointed: 

On the side problem of merges, a good way of **not** getting merge problems is to **enforce** a coding style.

**Comment by nka11** [comment]
In a not so perfect world of other big projects (like mailman for a personal experience), base branch **always** builds, allowing any contributor to contribute on a stable codebase, and know at first sight if it's contribution is right instead of having to scroll a build log to wonder if it's it contribution or base branch which blame it's commit.

This might constraint and give a bit of extra work for projects manager, but it's a signal of respect regarding contributors who gave debugging and coding time for free.

For my point of view, loosing time scrolling a log to discover a coding style error or whatever that breaks the build, that I've not authored makes me just flame the karma of the one who makes me loose that time, I had better spent it coding or debugging something else, giving, that way, more contributions...
