### ISSUE TITLE
Bug: Creating 2 customers/suppliers at same time

### ISSUE THREAD

**Issue by joseplluis** [Dolibarr/dolibarr#5128]
# Bug

When 2 users are adding new thirdparties with automatic Customer Code, on saving the second one appears an error of "Duplicated value".
## Environment
- **Version**: 3.9.1
## Expected and actual behavior

On saving the thirdparty, recalculate again the next Customer Code.
## Steps to reproduce the behavior

The user 1 starts adding a new Third party, and the next automatic Customer Code is assigned.
Before the user 1 save the new Third party, the user 2 stars to add a new Third party, and the same automatic Customer Code is assigned.
The first user who saves the Third party is OK, but the second one get an error of "Duplicated value".

**Comment by BebZ** [comment]
Maybe same behaviour when adding a new product, no ?
this is a minor bug i guess...
