### ISSUE TITLE
Error on migration 3.9 to 4.0

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#5138]
# Bug

[_When trying to apply last update_]
## Environment
- **Version**: _4.0.0-beta_
- **OS**: _Linux Debian_
- **Web server**: _Apache/2.4.10_
- **PHP**: _PHP 5.6.19-0+deb8u1_
- **Database**: _mysqld  Ver 5.5.47-0+deb8u1_
- **URL(s)**: _/htdocs/install/upgrade.php?action=upgrade&selectlang=fr_FR&versionfrom=3.9.0&versionto=4.0.0_
## Expected and actual behavior

After copying last git content to try and test content, I have this error in step 2 (file 3.9.0-4.0.0.sql)
**Erreur DB_ERROR_1072: ALTER TABLE llx_website ADD UNIQUE INDEX uk_website_ref (ref, entity);**
**Key column 'ref' doesn't exist in table**
## Steps to reproduce the behavior

_Request 41 sql='ALTER TABLE llx_facturedet ADD COLUMN fk_contract_line integer NULL AFTER rang;'
Request 42 sql='ALTER TABLE llx_facturedet_rec ADD COLUMN import_key varchar(14);'
Request 43 sql='CREATE TABLE llx_website(rowid integer AUTO_INCREMENT NOT NULL PRIMARY KEY,entity integer DEFAULT 1,ref varchar(24) NOT NULL,description varchar(255),status integer,date_creation datetime,date_modification datetime,tms timestamp) ENGINE=innodb;'
Request 44 sql='ALTER TABLE llx_website ADD UNIQUE INDEX uk_website_ref (ref, entity);'
*_Erreur DB_ERROR_1072: ALTER TABLE llx_website ADD UNIQUE INDEX uk_website_ref (ref, entity);**
Key column 'ref' doesn't exist in table
Request 45 sql='CREATE TABLE llx_website_page(rowid integer AUTO_INCREMENT NOT NULL PRIMARY KEY,fk_website integer,pageurl varchar(16) NOT NULL,title varchar(255),description varchar(255),keywords varchar(255),content text,status integer,date_creation datetime,date_modification datetime,tms timestamp) ENGINE=innodb;'
Request 46 sql='ALTER TABLE llx_website_page ADD UNIQUE INDEX uk_website_page_url (fk_website,pageurl);'
Request 47 sql='ALTER TABLE llx_website_page ADD CONSTRAINT fk_website_page_website FOREIGN KEY (fk_website) REFERENCES llx_website (rowid);'*

**Comment by aconits** [comment]
Hi,
I think this bug has been fix because i can't reproduce the bug in migration 3.9 > 4.0
Your sql request who return an error is correctly executed for my part

@eldy

**Comment by eldy** [comment]
You probably run a migration when dev on 4.0 for website feature was not stable enough.
You must delete table llx_website and run migration again.
