### ISSUE TITLE
Bug: import 'profil' is not possible.

### ISSUE THREAD

**Issue by grandlarge** [Dolibarr/dolibarr#5147]
# Environment
- **Version**: 3.9.0
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/imports/import.php?
  # Report
  I can not load my file save of the import/supplierprice.
  Eric

**Comment by atm-maxime** [comment]
This is a duplicate #5185 
Fixed here https://github.com/Dolibarr/dolibarr/pull/5273
