### ISSUE TITLE
Bug: SQL error when trying to enable OAuth module

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5152]
Version: 3.9.2

```
ERROR: 42601: syntax error at end of input LINE 1: ...BLE IF NOT EXISTS llx_oauth_state ( rowid SERIAL PRIMARY KEY ^ LOCATION: scanner_yyerror, scan.l:1044
```

**Comment by tomours** [comment]
I've got the same issue with the following settings : 
-    Version: 3.9.1
-   OS: Linux
-   Web server: Apache
-   PHP: 5.5.9-1ubuntu4.16
-   Database: Postgresql 9.3.12

**Comment by aschio** [comment]
cannot reproduce on 4.0.0-beta

**Comment by aconits** [comment]
Works for me in 3.9.2
Probably fix
