### ISSUE TITLE
Bug: New expense page asks for a project even if Projects module is not enabled

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5154]
Version: 3.8.4

![captura de pantalla 2016-05-02 a las 14 37 18](https://cloud.githubusercontent.com/assets/168744/14954535/66df132c-1073-11e6-9ba1-ffc8a0ff5b99.png)

**Comment by aschio** [comment]
bug already fixed

**Comment by atm-maxime** [comment]
Fixed in 3.9
