### ISSUE TITLE
Bug: Unable to view a expense even if having enough rights

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5155]
Version: 3.8.4

Reported by a dolibarr.es forum user http://www.dolibarr.es/foro/viewtopic.php?f=18&t=3045&p=9824#p9824

Users:
- User SUPERVISOR: With rights to read his expenses and his subordinates' and to approve them.
- User "a": With enough rights to create expenses.

Steps to reproduce:
1. User a creates an expense and sends it to approve
2. User supervisor tries to view the expense
3. NotUserRightToView error

**Comment by atm-maxime** [comment]
Hi @marcosgdf,

I was not able to reproduce on a 3.8.4 version.
Anyway, I fixed some rights issues.

**Comment by marcosgdf** [comment]
It is working fine now.
