### ISSUE TITLE
Bug: Customer invoices Fusion PDF feature does not merge abonement invoices

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5157]
Version: 3.8.3

Reported by a dolibarr.es forum user http://www.dolibarr.es/foro/viewtopic.php?f=18&t=2692&p=9828#p9828

**Comment by eldy** [comment]
Tested with 3.9 and can't reproduce the trouble.

**Comment by marcosgdf** [comment]
Tested with 3.9 and **can** reproduce the problem. Please check again.

**Comment by simnandez** [comment]
I close this issue, because is not reproducible in maintened versions
