### ISSUE TITLE
Bug: customers order

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#5160]
# Environment
- **Version**: 3.9.1
- **OS**: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.20
- **Database**: MySQL or MariaDB 5.5.47-0+deb7u1-log
- **URL**: /commande/list.php?viewstatut=-3
# Report

by menu, when I click on "customer order to process" dolibarr show me all orders (also the shipping), and the layers on track show me the first order info in the list for all convalidated orders.
![2016-05-04](https://cloud.githubusercontent.com/assets/5500935/15007712/45ce191c-11db-11e6-9f65-91bcef4a7130.png)

**Comment by atm-alexis** [comment]
Hi,

Can't reproduce it because i don't find how you get this link with "viewstatut=-3". Can you give us some details ?

**Comment by ghost** [comment]
Hi,

Status -3 show validated, in process or closed but not billed order. Think the process is ok . 

Can you provide us more details about "  the layers on track show me the first order info in the list for all convalidated orders " ? Can't reproduce it.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
