### ISSUE TITLE
Feature request: send proposal/order by email for all status

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#5162]
# Environment
- **Version**: 3.9.1
- **OS**: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.20
- **Database**: MySQL or MariaDB 5.5.47-0+deb7u1-log
- **URL**: /admin/const.php
# Report

As the "setup other" FACTURE_SENDBYEMAIL_FOR_ALL_STATUS, maybe great to send email for all status of customers orders and proposal.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
