### ISSUE TITLE
Bug: Some Alerts not working on index page

### ISSUE THREAD

**Issue by sergibyte** [Dolibarr/dolibarr#5173]
# Bug

Some alerts are not working on the index page, our problem is specific with **Signed commercial proposals to bill** and **Unpaid customer invoices**

In our case, the number for these sections is working fine, but the alert isn't, as it's showing always 0 for late, even when there are elements that are later than the days set for it.

When clicking on the number, you can enter the list and then you're shown the ones that are late with the correspondent warning symbol, so the _late_ setting is working fine, but it's not displayed on the index page as it does with the rest of sections.

That's an issue for us as it's not warning us when invoices are unpaid for more than a month or signed proposal haven't been invoiced after seven days.
## Environment
- **Version**: 3.8.2 and 3.9.1
- **OS**: Linux Debian
- **Web server**: Apache 2.4.10
- **PHP**: 5.6.20
- **Database**: MySQL 5.5.49
## Expected and actual behavior

The _Late_ column should show the number of elements above the given days, but it's showing always 0.

**Comment by atm-maxime** [comment]
Thanks for the feedback.

I just tested and for the customer invoices, it's working fine for me. The warning delay is based on the invoices due date.
Regarding the proposal signed to bill, the warning indicator is not yet developed because the rule has not been defined. It's a bit tricky, because from a proposal to another the delay before billing can be very different.

What's your opinion on this ?

**Comment by sergibyte** [comment]
Thank you for your reply.

On the Proposals signed to bill, what my client is expecting is to see those proposals that have been signed but are not invoiced yet, and have a warning/alert when they are over 7 days after signing/closing it. We thought that's what it meant but I realise it can be very different for other companies.

Does that make sense? I'll check your answer with my client and let you know.

**Comment by simnandez** [comment]
I Close the issue because there are no more entries
