### ISSUE TITLE
Bug: Catchable fatal error: Argument 3 passed to InterfaceLogevents::runTrigger() must be an instance of User, null given, called in /home/httpd/vhosts/atoo-net.com/domains/compta.atoo-net.com/httpdocs/core/class/interfaces.class.php on line 160 and defined in /home/httpd/vhosts/.../domains/compta.atoo-net.com/httpdocs/core/triggers/interface_20_all_Logevents.class.php on line 50

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#5178]
# Environment
- **Version**: 3.9.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.20-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.23-MariaDB-0+deb8u1-log
- **URL**: /fourn/facture/card.php?action=editref_supplier&id=647
# Report

Display that error when cloning an invoice and changing supplier ref.

**Comment by marcosgdf** [comment]
Duplicate of bug #5156

**Comment by grandoc** [comment]
Duplicate of bug #5156
