### ISSUE TITLE
Bug groupe/adhérents et cotisation

### ISSUE THREAD

**Issue by boscorelly** [Dolibarr/dolibarr#5180]
Lorsque l'on crée un groupe qui n'est pas soumis à cotisation (configuré dans le groupe), et qu'on y ajoute un adhérent, l'adhérent est automatiquement en "non à jour" et donc en manque de cotisation alors qu'il n'y est pas soumis (typiquement les membres du bureau)

**Comment by eldy** [comment]
Ceci est normal. Même si un adhérent n'est pas soumis à cotisation il a une adhésion (un mandat avec une durée) qui est certes gratuite, mais qui est un acte volontaire d'adhésion de l'adhérent (car un membre du bureau est aussi adhérent).
Il faut donc lui saisir son adhésion avec sa durée de fin de validitée. Le "non à jour" doit etre vue comme "non à jour en terme de période d'adhésion" et non comme "non à jour en terme de paiement".
La confusion vient de la traduction qui emploie le terme cotisation au lieu de "adhésion".
