### ISSUE TITLE
Hooks: $this->resprints not fully implemented

### ISSUE THREAD

**Issue by lrq3000** [Dolibarr/dolibarr#5184]
[According to the wiki](https://wiki.dolibarr.org/index.php/Syst%C3%A8me_de_Hooks#Impl.C3.A9menter_un_Hook), 3rd-party modules relying on hooks to print things should now store their output in `$this->resprints` instead of printing directly.

Issue: in Dolibarr v3.9.1, "Third-party" module correctly implements this, but other core modules do not.

Workaround: Always print, but then the output is displayed twice in Third-party module...

Solution: provide in `$object` a boolean field indicating the support of `$this->resprints`?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
