### ISSUE TITLE
Bug: impossible de sélectionner un import prédéfini

### ISSUE THREAD

**Issue by grandlarge** [Dolibarr/dolibarr#5185]
# Environment
- **Version**: 3.9.0
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/imports/import.php?step=4&datatoimport=produit_supplierprices&format=csv&separator=%3B&enclosure=%22&filetoimport=20160504153458-Fichier_complet_cr%C3%A9ation_Polos_NOOS_North-56_Dolibarr.csv
# Report

Bonjour, impossible de sélectionner mes imports prédéfinis.
Help me.
Merci.
Eric

**Comment by grandlarge** [comment]
Bonjour, impossible de sélectionner mes imports prédéfinis.
 Help me.
 Merci.
 Eric

**Comment by grandlarge** [comment]
Hi Maxime,

Thank you for your answer.

I have made the change but the problem is alway present. 

Best regard

Eric

**Comment by atm-maxime** [comment]
I just verified and it's working for me.
The old import model you saved are corrupt, you must save new ones or change in the import_model table to have correctly "produit_supplierprices" in the type column
