### ISSUE TITLE
Bug: Supplier min quantity not respected [TEST FAIL]

### ISSUE THREAD

**Issue by nka11** [Dolibarr/dolibarr#5186]
# Bug Supplier min quantity not respected

Noticed a bug on this feature, I have re-activated phpunit tests (#5181) in travis and one fails with :

```
1) CommandeFournisseurTest::testCommandeFournisseurCreate

Failed asserting that 21 matches expected -1.

/home/travis/build/Dolibarr/dolibarr/test/phpunit/CommandeFournisseurTest.php:164
```

with this specific use case : while trying to set up a quatity of 1 while min supplier quantity is 10, order is created, but according to assertions, and behavior description, it should not.

**Comment by tiaris** [comment]
Test if ordered qty is >= to min quantity is done in fournisseur.commande.class.php.
the add_line method returns -1 when ordered quantity is < min qty with error field has the message 
So this case must be tested correctly in phpunit class

**Comment by tiaris** [comment]
works for me after creating product with ref PIDRESS
CommandeFournisseurTest::setUpBeforeClass
.CommandeFournisseurTest::setUp
CommandeFournisseurTest::testCommandeFournisseurCreate result=-1
CommandeFournisseurTest::testCommandeFournisseurCreate result=5
CommandeFournisseurTest::tearDown

Test made in 4.0

**Comment by tiaris** [comment]
works also in version 3.8.3

.CommandeFournisseurTest::setUp
CommandeFournisseurTest::testCommandeFournisseurCreate result=-1
CommandeFournisseurTest::testCommandeFournisseurCreate result=2
CommandeFournisseurTest::tearDown

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
