### ISSUE TITLE
Bug: CommandeFournisseur incorrect rowid after adding a product line 

### ISSUE THREAD

**Issue by lrq3000** [Dolibarr/dolibarr#5192]
After adding a product line, the CommandeFournisseur `$object` will have the `rowid` property set to the CommandeFournisseurDet id (ie, the product line id) instead of being equal to `$object->id`.

**Comment by marcosgdf** [comment]
Which version?

**Comment by lrq3000** [comment]
Latest stable: v3.9.1. Don't know when it appeared, but it was already present from v3.8.0.

**Comment by marcosgdf** [comment]
Yes. I can confirm it is present in 3.8.0.

```
(From CommandeFournisseur::addline function)
$this->rowid = $this->db->last_insert_id(MAIN_DB_PREFIX.'commande_fournisseurdet');
```
