### ISSUE TITLE
Deb not installable on ubuntu 16.04.

### ISSUE THREAD

**Issue by autra** [Dolibarr/dolibarr#5199]
# Bug

The deb declares dependencies that apt cannot meet on Ubuntu 16.04.
## Environment
- **Version**: 3.9.1
- **OS**: Ubuntu 16.04
- **Web server**: not relevant
- **PHP**: 7.0
- **Database**: mysql 5.7.12
## Expected behaviour

The deb installs successfully
## actual behavior

I have this error:

``` bash
ᐅ sudo dpkg -i dolibarr_3.9.1-4_all.deb                                                     
Selecting previously unselected package dolibarr.
(Reading database ... 397535 files and directories currently installed.)
Preparing to unpack dolibarr_3.9.1-4_all.deb ...
Unpacking dolibarr (3.9.1-4) ...
dpkg: dependency problems prevent configuration of dolibarr:
 dolibarr depends on libapache2-mod-php5 | libapache2-mod-php5filter | php5-cgi | php5-fpm | php5; however:
  Package libapache2-mod-php5 is not installed.
  Package libapache2-mod-php5filter is not installed.
  Package php5-cgi is not installed.
  Package php5-fpm is not installed.
  Package php5 is not installed.
 dolibarr depends on php5-cli; however:
  Package php5-cli is not installed.
 dolibarr depends on php5-mysql | php5-mysqli; however:
  Package php5-mysql is not installed.
  Package php5-mysqli is not installed.
 dolibarr depends on php5-curl; however:
  Package php5-curl is not installed.
 dolibarr depends on php5-gd; however:
  Package php5-gd is not installed.
 dolibarr depends on php5-ldap; however:
  Package php5-ldap is not installed.
 dolibarr depends on php5-geoip; however:
  Package php5-geoip is not installed.
 dolibarr depends on php-mail-mime; however:
  Package php-mail-mime is not installed.

dpkg: error processing package dolibarr (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160415-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 dolibarr
```
## Steps to reproduce the behavior
- Download the official deb from sourceforge
- execute `sudo dpkg -i <deb file>`

Thanks

**Comment by simnandez** [comment]
dpkg not solve the dependences, after execute dpkg -i , you must execute apt-get install -f

**Comment by autra** [comment]
@simnandez if I have this error, it's because the specified dependencies are not resolvable for ubuntu 16.04. Specifically, if I'm not mistaken, some of these dependencies don't even exist in the repo for this version of ubuntu. I've already tried to fix this by hand, sorry if that wasn't clearly stated. I'm speaking about:
- php5-mysql (removed on xenial)
- php5-mysqli
- php5-curl
- php5-ldap
- php5-geoip

So I guess `-f` won't be of any help here...

**Comment by marcosgdf** [comment]
Are php5-ldap, php-geoip and php5-curl really required dependencies? They shouldn't be!

**Comment by autra** [comment]
Yep they are defined as so in the .deb

**Comment by marcosgdf** [comment]
ping @eldy

**Comment by rdoursenaud** [comment]
Ubuntu 16.04 ships with PHP 7 by default.
AFAIK only Dolibarr 4.0 and maybe a subset of 3.9 are compatible.

The workaround is to switch to PHP 5.6 using a PPA:

```
add-apt-repository ppa:ondrej/php
apt update
apt install php5.6 libapache2-mod-php5.6 php5.6-cli php5.6-mysqli php5.6-curl php5.6-gd php5.6-ldap php5.6-geoip php5.6-mbstring php5.6-mcrypt  php5.6-xml php5.6-xmlrpc php5.6-zip
a2dismod php7.0
a2enmod php5.6
systemctl restart apache2
```

Please report if you are successful or not so we could include an install note on the wiki.

For further versions, we should make sure to only depend on a PHP provider that is ≥ 5.3 so that PHP 7 is considered valid. (Provided that Dolibarr pass all tests against PHP 7).

Thanks.

**Comment by jajaX** [comment]
Hi (sorry for my bad english !)

same problem today with kubuntu 14.04 with php 7 (from ppa:ondrej/php) and Dolibarr deb (from Sourceforge) 4.0.2 !!

I know Kubuntu 14.04 use php 5 but I want keep php 7 only !

I try tgz...

regards !

**Comment by rdoursenaud** [comment]
@jajaX If you want PHP7, you'll need to do a manual install. Keep in mind that Dolibarr PHP7 support is still very much beta for the moment.

**Comment by jajaX** [comment]
Hi,

ok, Dolibarr works very well with tgz ;)

**Comment by simnandez** [comment]
I close this issue, as it will not be implemented
