### ISSUE TITLE
Bug: PMP buying price option should not be shown if stocks module is not enabled

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5205]
# Bug

Version: 3.8.4
Page: http://dolibarr.local/commande/card.php?id=5&action=confirm_modif&confirm=yes

**Comment by atm-maxime** [comment]
Hi Marcos,

I Just fixed it in 3.8. We are missing you in this year's DevCamp in Genova !

Cheers

**Comment by marcosgdf** [comment]
@atm-maxime had to study for some exams :( hope you enjoyed it!
