### ISSUE TITLE
Bug: Impossible to delete import files

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5213]
Version: 3.9.1
Browser: Firefox 43.0.1

Hello,
I can upload import files (Tools) but when I click on the trashbin in order to delete the file it doesn't work.
To reproduce the problem upload an import file and try to delete it using the trashbin

**Comment by eldy** [comment]
Can't reproduce with 3.9.2.
Can you reproduce on demo.dolibarr.org ?

**Comment by mikygee** [comment]
The import functionality is not available in the demo

**Comment by atm-maxime** [comment]
Hello,

I just made a test on a 3.9.2 and my uploaded file is correctly deleted.

![image](https://cloud.githubusercontent.com/assets/2097773/15794277/e97a9240-29e9-11e6-96d5-936f0bffc407.png)

![image](https://cloud.githubusercontent.com/assets/2097773/15794292/07285700-29ea-11e6-8b10-211fcd5f381d.png)

**Comment by mikygee** [comment]
Hello,
It worked for you but not for me !!!
I'm not sure closing issues is the good way to solve problems.
I tried it in version 3.9.2
NB: I also have a delete problem when I try to delete Tiers
