### ISSUE TITLE
Bug: Import file for bank account incorrect

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5214]
Version: 3.9.1

Hello,
The import file example for bank settings account seems to be incorrect
a) Fileds "Nom du tiers\* (sr.fk_soc)" are specified when "Nom du tiers" is expected
b) When there are whitespaces the fields should be between double quotes
c) The last column is named IBAN but dolibarr expects "Identifiant IBAN"
d) Most column are in french but Bank is in english
e) At step 5, I specify not to import the first line but dolibarr tries to do it anyway and there is an error. That's the same when we import Tiers

**Comment by atm-maxime** [comment]
Hello,

a) First column accepts either the thirdparty name, or its rowid
b) why ? csv needs double quotes when a field contains a new line character
c) I don't understand the difference
d) Dolibarr coders are progressively replacing french codes to english ones
e) I just tested to import the demo file in a 3.9.2 and the first line was correctly ignored

Don't hesitate to add screenshots or links to help us understand the issue.

**Comment by mikygee** [comment]
Hello Maxime,

You seem to be in a hurry to close bugs. You ask me a screenshot but don't even wait for it.

a) ME: Fileds "Nom du tiers\* (sr.fk_soc)" are specified when "Nom du tiers" is expected
MAX: First column accepts either the thirdparty name, or its rowid
ME: Did you try to download the example file, and then use it without ignoring the first line ?

b) I will test again and explain you why.

c) ME: The last column is named IBAN but dolibarr expects "Identifiant IBAN"
MAX: c) I don't understand the difference
ME: I do. Did you try to download the example file, and then use it without ignoring the first line ?

d) OK

e) I will test again
