### ISSUE TITLE
Bug: Delete Tiers Impossible

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5215]
Version: 3.9.1
Browser: Firefox 43.0.1

Hello,
I cannot delete Tiers
Go to Tiers menu, select a Tiers and do delete (Supprimer) it doesn't work.
When I roll over the button there's no link, probably a <a href...> </a> is missing in the code

**Comment by mikygee** [comment]
For some reason, it works fine on http://demo.dolibarr.org

**Comment by atm-maxime** [comment]
Hi,

Can you provide a screenshot or more informations ? I tested in a 3.9 and it works fine for me.

**Comment by mikygee** [comment]
Hello,
It doesn't work for me, retested in version 3.9.2
Modifier works, Fusion seems to work because I can see "?action=merge&socid=1" in the URL, Supprimer doesn't work and the URL is not updated, I still see "?action=merge&socid=1"
Regards

**Comment by mikygee** [comment]
Also when I rollover Modifier or Fusion I can see the URL (bottom left on the browser) that is going to be called if I do a clic.
But I don't see that if I rollover Supprimer

**Comment by simnandez** [comment]
I close this issue, because works fine in maintened versions
