### ISSUE TITLE
Old "Notes de Frais" missing after a 3.9.1 update !

### ISSUE THREAD

**Issue by AlainG95** [Dolibarr/dolibarr#5223]
# Environment
- **Version**: 3.9.1
- **OS**: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.21
- **Database**: MySQL 5.1.73-log
- **URL**: /compta/hrm.php?mainmenu=hrm&leftmenu=
# Report

**Comment by AlainG95** [comment]
Until now old and new GRH was shown on the left menu. 
Now all the past is not available !
Thank you to advise.

**Comment by eldy** [comment]
Go into home - setup - miscellaneous.
You can set MAIN_LEVEL_FEATURES to -1 so abandonned module should be visible.

**Comment by AlainG95** [comment]
Bonjour,

Merci beaucoup pour cette information qui va me permettre de clore 2015
et de continuer 2016 avec le nouveau module beaucoup plus efficace.

A.Guirauton

Cordialement,

Alain GUIRAUTON
Tél : +33(0)6 8865 8521
