### ISSUE TITLE
Bug: Importing bank account with semi colon

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5229]
Version: 3.9.1
Browser: Firefox 43.0.1

Hello,
Importing a bank account doesn't work with semi colon but works with comma
I select ; the modify
I expect the same behavior regardless of the separator.
NB: Create the Tiers SOC first
Find file with comma that works fine and file with semi colon that doesn't work

[Dolibarr-Bug_Import_RIB_pointvirgule-04Jan2016.txt](https://github.com/Dolibarr/dolibarr/files/273539/Dolibarr-Bug_Import_RIB_pointvirgule-04Jan2016.txt)

[Dolibarr-Bug_Import_RIB_virgule-04Jan2016.txt](https://github.com/Dolibarr/dolibarr/files/273541/Dolibarr-Bug_Import_RIB_virgule-04Jan2016.txt)

**Comment by eldy** [comment]
Can you provide a screenshot with error message ?
