### ISSUE TITLE
Bug: error on export on complex fields

### ISSUE THREAD

**Issue by dreggy** [Dolibarr/dolibarr#5231]
# Bug

I don't really know if it is a bug or can be consider as feature request, I put it here
I'm using a custom plugin and i defined an export "profile" in the plugin. If in the export_fields_array i use something like this 
`$this->export_fields_array[$r]=array(
          "date_format(b.dateo,'%d-%m-%Y')"=>'Data operazione [invertita]',
          'b.label'=>'Label',
          'b.amount'=>'Dare',
          'IF(ba.ref NOT LIKE \'Cassa\' AND ba.ref NOT LIKE \'BCC_Manzano\',NULL,-b.amount)'=>'Avere [PFC]',
          'IF(ba.ref NOT LIKE \'Cassa\' AND ba.ref NOT LIKE \'BCC_Manzano\',-b.amount, NULL)'=>'Partita fuori cassa',
          "concat_ws(' - ',IF(STRCMP(ba.ref,'Cassa') LIKE '0',NULL,Concat('','Anticipo da ',ba.ref)),IF(ba2.label IS NULL,NULL,IF(ba2.label LIKE 'C.C. BCC Manzano', ba2.label, Concat('','Rimborso a ',ba2.label))),s.nom,IF(ff.ref_supplier IS NULL,NULL,Concat('','Fatt.n ',ff.ref_supplier)),IF(fa.facnumber IS NULL,NULL,Concat('','Fatt.n ',fa.facnumber)))"=>"Dettagli");`
but the export procedure trows warning and errors
## Environment
- **Version**: 4.0.0-beta
## Expected and actual behavior

The export procedure should accept an export field like date_format(b.dateo,'%d-%m-%Y'), but actually it accept only fields in the format b.dateo

**Comment by dreggy** [comment]
I found that if I change in "exports\class\export.class.php"
      all occurences of

> str_replace(array('.', '-','(',')'),'_',$key);

```
  with
```

> substr(str_replace(array('.', '-', '(', ')', ' ', '\'', '"', '%', ',', '>', '<', '='),'_',$key),0,100);

and change in "core\modules\export\export_excel.modules.php";
      line 322

> $alias=str_replace(array('.','-','(',')'),'_',$code);

```
  with
```

> substr(str_replace(array('.', '-', '(', ')', ' ', '\'', '"', '%', ',', '>', '<', '='),'_',$code),0,100);

the export will work, but still a warning message appear in some pages

> Warning: preg_match(): Compilation failed: missing ) at offset 35 in exports/export.php on line 1196
> i'm not good in regex so i don't know how to fix this

**Comment by atm-geoffrey** [comment]
Hi @dreggy ,

I think one thing make some trouble in this code : 
`substr(str_replace(array('.', '-', '(', ')', ' ', '\'', '"', '%', ',', '>', '<', '='),'_',$code),0,100);`

I think you're warning append because you have '\'' in regex expression. Test replace by "\'"

**Comment by dreggy** [comment]
I tried, but the warning is still there.
The problem is in the function "getablenamefromfield" in the file exports/export.php at line 1188.
The export fields are too complex to extract data using the "preg_match" at line 1196, something does not match but i'm not good in regex strings :stuck_out_tongue_closed_eyes: to debug it

**Comment by dreggy** [comment]
I checked the code a bit. It seems to me that to fully support what i am asking, it has to be rewrite a lot of code, even in other functions, because it is not planned to work as i'm trying to do. 

With my edits something works, but it can't save and reload the models and some warnings appear.

If there is no interest in fix this, I can close the issue.
Thank you

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
