### ISSUE TITLE
Field "" is obligatory in V 3.9.1

### ISSUE THREAD

**Issue by AMAP44119** [Dolibarr/dolibarr#5238]
# Bug

[Field '' is oblligatory]
## Environment
- **Version**: [3.9.1]
- **OS**: [Debian 8]
- **Web server**: [Apache2]
- **PHP**: [5.6.17]
- **Database**: [MySQL]
- **URL(s)**: [http://gamapgdf.no-ip.org]
## Expected and actual behavior

[No possibility to modify a field in menu Adherent]
## Steps to reproduce the behavior

[My language: French. In the menu Adherents when i want to modify a field: Type for example, i got the message: Field '' is obligatory. It apears, if this adherent is also a user. If it not not, all is OK. But if I delete this user and keep the adherent, it stays the same probleme.]
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[_Files_]
# Feature Request

[_Short description_]
## Use case

[_Verbose description_]
## Suggested implementation

[_Verbose description_]
## Suggested steps

[_List of tasks to achieve goal_]

**Comment by Xebax** [comment]
Hi,

Please don't keep the entire template when creating an issue, this makes it hard to read. You'll have more assistance if you write a good issue. So edit the issue, please, and remove the instructions and all the parts that are not relevant.

Now, about your problem: I don't reproduce the bug. Can you give more details? I have tested with the version 3.9.1, with a member linked to a user, and I have no problem to edit the member.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
