### ISSUE TITLE
[Security] - XSS on htdocs/viewimage.php

### ISSUE THREAD

**Issue by coh7eiqu8thaBu** [Dolibarr/dolibarr#5239]
# Bug

The file htdocs/viewimage.php as an XSS.
## Environment
- **Version**: at least from 3.5.2 to now
- **OS**: ALL
- **Web server**: ALL
- **PHP**: ALL
- **Database**: ALL
- **URL(s)**: /viewimage.php
## Expected and actual behavior

The problem is that the code :
`
$original_file = str_replace("../","/", $original_file);
`
convert "../" to "/" so the second part of code :
`
if (preg_match('/\.\./',$original_file) || preg_match('/[<>|]/',$original_file))
`
match and
`
dol_print_error(0,'Error: File '.$_GET["file"].' does not exists');
`
Display what you want of code
## Suggested implementation

do not display $_GET["file"] but just an generic error

**Comment by fgeek** [comment]
Does this vulnerability have CVE identifier assigned?
