### ISSUE TITLE
Adding spent time in project tasks by user assigned

### ISSUE THREAD

**Issue by henryseron** [Dolibarr/dolibarr#5249]
# Bug

[Users can not add spent time on assigned tasks in module Projects]
## Environment
- **Version**: [3.9.0]
- **OS**: [Redhat 7]
- **Web server**: [Apache 2.4.6]
- **PHP**: [5.4.16]
- **Database**: [MariaDB 5.5.44]
- **URL(s)**: [http://dol.shakingweb.com]
## Expected and actual behavior

Any user who has an assigned task in a project should add its spent time, but it does not work correctly.
## Steps to reproduce the behavior

According the description on User -> tab Permissions, a user can add its spent time on its assigned tasks:
![image](https://cloud.githubusercontent.com/assets/11153444/15639576/619fc346-25fb-11e6-8d99-b3bdb5895eef.png)
But it does not work!
The user only can add its spent time when I enable the permission to create or modify projects, but I only want they can add their time, not modify any project.
## Feature Request

I would like to ask for adding a new kind of permission, something like "Add spent time on assigned tasks" to control this issue.

Thanks in advance.

**Comment by atm-maxime** [comment]
Please open a new issue as a feature request for having new rights in the project module on time spent (read / create / delete / export)
