### ISSUE TITLE
Warning when connecting through ldaps

### ISSUE THREAD

**Issue by davlord** [Dolibarr/dolibarr#5250]
# Bug

Warning appears on first page when connecting through ldaps :
Warning: ldap_get_values_len(): Cannot get the value(s) of attribute Decoding error in /usr/share/nginx/html/htdocs/core/class/ldap.class.php on line 1083
## Environment
- **Version**: 3.9.1
- **OS**: Linux  3.14.32-xxxx-grs-ipv6-64 
- **Web server**: nginx/1.8.1
- **PHP**: 5.5.9
- **Database**: PostgreSQL 9.5.1
- **URL(s)**: /index.php?mainmenu=home
## Expected and actual behavior

Access the page without any errors or warning
## Steps to reproduce the behavior

Configure dolibarr access through ldaps :
$dolibarr_main_auth_ldap_host='ldaps://domain.com';
$dolibarr_main_auth_ldap_port='636';
$dolibarr_main_auth_ldap_version='3';
$dolibarr_main_auth_ldap_servertype='openldap';
$dolibarr_main_auth_ldap_login_attribute='uid';
$dolibarr_main_auth_ldap_dn='ou=people,dc=domain,dc=com'
$dolibarr_main_authentication='ldap';
## Additional information
- Please note the same configuration without ldaps doesn't show any errors or warning.
- The warning disappear as soon as we start to navigate
- It doesn't block the user, Dolibarr is still functional

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by fkoessler** [comment]
Hello @simnandez,

The warning is still present on 6.0.3
