### ISSUE TITLE
Extra colums ad client field "= ="

### ISSUE THREAD

**Issue by Snakeballz** [Dolibarr/dolibarr#5257]
If you add a client, or something else you will see  = = as extra fields.
See screenshot, bug or problem at my version? got the latest 

![schermafbeelding 2016-06-01 om 21 19 02](https://cloud.githubusercontent.com/assets/11150767/15722581/bddc1c28-283e-11e6-8f41-f6afc1ff6879.png)

**Comment by eldy** [comment]
Sorry, i did not understand how to reproduce. In which dolibarr version ?
Can you describe how to reproduce ?

**Comment by grandoc** [comment]
No answer from user. We close it.
