### ISSUE TITLE
Unused strings in lang files

### ISSUE THREAD

**Issue by novalore** [Dolibarr/dolibarr#5267]
SearchBankMovement in the [banks.lang](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/langs/en_US/banks.lang) file is not used anywhere  in the code.
The same goes for ChooseLangage in [main.lang](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/langs/en_US/main.lang).
Should they be stripped from lang files or are they used in some place I am not looking at?

**Comment by eldy** [comment]
The ChooseLanuage can be removed.
However the SearchBankMovement was introduce to add the search on movement on he quick search left box.
