### ISSUE TITLE
Bug: Users can not add spent time on assigned tasks

### ISSUE THREAD

**Issue by henryseron** [Dolibarr/dolibarr#5319]
# Bug

[Users can not add spent time on assigned tasks in module Projects]
## Environment
- **Version**: [3.9.0]
- **OS**: [Redhat 7]
- **Web server**: [Apache 2.4.6]
- **PHP**: [5.4.16]
- **Database**: [MariaDB 5.5.44]
- **URL(s)**: [http://dol.shakingweb.com]
## Expected and actual behavior

Any user who has an assigned task in a project should add its spent time, but it does not work correctly.
## Steps to reproduce the behavior

According the description on User -> tab Permissions, a user can add its spent time on its assigned tasks:
![image](https://cloud.githubusercontent.com/assets/11153444/15639576/619fc346-25fb-11e6-8d99-b3bdb5895eef.png)
But it does not work!
The user only can add its spent time when I enable the permission to create or modify projects, but I only want they can add their time, not modify any project.

**Comment by eldy** [comment]
Can you check with 3.9.2 ?
