### ISSUE TITLE
Feature Request: Affichage de l'IBAN au lieu du RIB dans la fiche de la société

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5323]
Version: 3.9.2

Bonjour,
J'ai effectué l'import des coordonnées bancaires pour la société SOC.
Après cet import c'est le numéro de compte bancaire qui est affiché dans la fiche (globale) de la société SOC, à mon avis ce serait mieux que cela soit l'IBAN qui est maintenant la norme pour les numéros de compte.

Cordialement

**Comment by BebZ** [comment]
You must, if you want your request to be qualified, write in English
IF you don't translate it will be NOT QUALIFIED.

**Comment by mikygee** [comment]
Hello,
I imported the bank account number for the firm SOC.
But after this import, that's the bank account number that is displayed for the firm SOC whereas imho it should be the IBAN that is considered as the official bank account number now.
Regards

**Comment by mdeweerd** [comment]
I think that this can be closed - both the IBAN and the historical account number is shown in the accounts overview (6.0.4).
