### ISSUE TITLE
[Hook] formObjectOptions() don't print resprints

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5327]
# Bug

According to `HookManager` documentation, hooks are supposed to print `$this->resprints` but `formObjectOptions()` don't do that.

I've worked around it using:

``` php
public function formObjectOptions($parameters, CommonObject &$object, &$action, HookManager $hookmanager)
{
    // Do some hook processing

    // FIXME: upstream code is supposed to do that on its own!
    print $this->resprints;

    return 0;
}
```
## Expected behavior

Setting `$this->resprints` should result in a print of its content on trigger exit.

**Comment by rdoursenaud** [comment]
Related to #5184

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
