### ISSUE TITLE
[EventMessages] Not displayed by the contract card page

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5328]
# Bug

Errors set into `Contrat::errors[]` during trigger processing are not displayed.
This is most likely because the code uses the deprecated `setEventMessage()` instead of its plural cousin `setEventMessages()`

I've worked around it using a hook:

``` php
function addMoreActionsButtons($parameters, CommonObject &$object, &$action, HookManager $hookmanager)
{
    // Hack to get contract errors to display
    if ($parameters['currentcontext'] == 'contractcard') {
        $this->displayContractsTriggerErrors($object);
    }
}

/**
 * Hack to display contracts trigger errors
 *
 * @param Contrat $contract
 */
private function displayContractsTriggerErrors(Contrat $contract)
{
    // FIXME: upstream code should take care of that!
    setEventMessages($contract->error, $contract->errors, 'errors');
}
```
## Expected and actual behavior

Errors should be automatically displayed by the contract card page.

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
