### ISSUE TITLE
problem in installation in online server. 

### ISSUE THREAD

**Issue by shakil247** [Dolibarr/dolibarr#5331]
when I am installing dolibarr in my pc or localhost it's working properly. but when I am trying to install it in online server it's creating some problem. when I am completing the installation and try to watch the home page, it's show me something like this.
"Error: Dolibarr config file content seems to be not correctly defined.
Please run dolibarr setup by calling page /install. "
you can see it http://erptest.ml/dolibarr-develop/htdocs/ on this url. how can I fix this problem??

**Comment by rdoursenaud** [comment]
Hi,
this is an issue tracker, not a support forum.
Please ask your question at https://www.dolibarr.org/forum
Thanks.
