### ISSUE TITLE
Bug: time zone, hour incorrect

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#5333]
# Environment
- **Version**: 3.9.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.33
- **Database**: MySQL or MariaDB 5.6.30
- **URL**: /auditorias/projet/tasks/task.php?id=476&withproject=1
# Report

**Comment by atm-maxime** [comment]
Hello @alimentarius ,

Can you provide more informations please ? Perhaps a screen shot ?

**Comment by alimentarius** [comment]
Hello

When try to put a hour, ex: 09:00, the houre thare apears is 08:00, 
after save de changes

Às 08:24 de 11-06-2016, Maxime Kohlhaas escreveu:

**Comment by atm-maxime** [comment]
How is Dolibarr installed ? On a server ? On your own computer ? Do you have the same hour than your server ?

**Comment by rdoursenaud** [comment]
Please also include your localization parameters from ```admin/system/dolibarr.php?mainmenu=home&leftmenu=admintools_info```.
