### ISSUE TITLE
Sorting on lists doesn't work

### ISSUE THREAD

**Issue by Gilles-Lengy** [Dolibarr/dolibarr#5337]
# Bug

The sorting in lists don't work...
## Environment
- **Version**: 3.9.1 et 3.9.2
  Detected on our dev Dolibarr 3.9.1
  Checked on the online demo 3.9.2
## Expected and actual behavior

Expected  behavior :
Sort a column by using small arrows beside Label of the column.
Actual behavior :
Only one arrow after the first column wich doesn't event work
## Steps to reproduce the behavior

Go to this page : http://demo.dolibarr.org/contact/list.php?sortfield=p.lastname&sortorder=asc&begin=&begin=&view=&userid=&contactname=&type=c&view=&search_lastname=&search_firstname=&search_societe=&search_email=&search_status=1
## Comment

I've tried to debug this...
I've discover that the functions img_down and img_up seems involved...
I've remplaced those fonction with a string and it seems to work...
See the attached file. This extracted code is around the line 2847 of the file htdocs/core/lib/functions.lib.php...
See the attached file to discover how I make it works even if isn't a real solution...

**Comment by atm-maxime** [comment]
Hello @Gilles-Lengy ,

I just went on the demo with the link you provided and the sorting seems to be working for me. I can click on the columns title and the list refreshes with the right sorting. I have tested on Chrome 51 and Firefox 46.

In 3.9 version, the arrows are no longer here to be clicked, they just tell which way is the sort. It's by clicking the column title that you can sort the list.

**Comment by Gilles-Lengy** [comment]
Yes ! I understand now...
I didn't notice the new behavior.
I think this is a good improvement.
