### ISSUE TITLE
Bug: Agenda / hour is reset when adding or deleting the user attributed to an action

### ISSUE THREAD

**Issue by PeartreeG** [Dolibarr/dolibarr#5338]
# Bug

[Agenda / hour is reset when adding or deleting the user attributed to an action]
## Environment
- **Version**: [_3.8.4 to 3.9.2_]
- **OS**: [_Wamp & ubuntu_]
- **Web server**: [_Webserver type and version_]
- **PHP**: [_PHP version_]
- **Database**: [_Mysql_]
- **URL(s)**: [_http://localhost/vs/htdocs/comm/action/card.php_]
## Expected and actual behavior

[_action hour should not be affected wether by adding or deleting a user attributed to the action_]

**Comment by atm-maxime** [comment]
See #5407
