### ISSUE TITLE
Bug: Importing Tiers problem with capital field

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5340]
Version: 3.9.2
Browser: Firefox 43.0.1

Hello,

There's a problem when importing the capital with spaces in it
In my tests a number is not properly imported when there's a space in the capital number and even it's between double quotes (during import I let " as encadrement des chaines de caracteres)

My thoughts about the future fix
I think the capital field is between the separator ";" or "," so
;17 500;
Should be imported with the space, there should be no need to add double quotes.
What I mean is, I would like to see 17 500 in the capital of the company, not 17500 and not having the need to add "

Here's a file to reproduce the problem (ignore the first line)
[Dolibarr-Bug_Import_Capital_Societes-11Jun2016.txt](https://github.com/Dolibarr/dolibarr/files/310155/Dolibarr-Bug_Import_Capital_Societes-11Jun2016.txt)

**Comment by mikygee** [comment]
I'm not sure if I have been clear.
When I import a Tiers with a capital of: 37 000
It doesn't work because of the whitespace. I think Dolibarr should handle this case.
With a postal adress Dolibarr handles white spaces and import them properly
Maybe whitespaces should be stripped when the field separator is not a white space

**Comment by atm-geoffrey** [comment]
Hi @mikygee 
That's not a bug but just a database structure constraint. In Dolibarr database capital field is in double format so you can't insert text format in double format.

**Comment by mikygee** [comment]
Hello Geoffrey,
I understand what you wrote but the capital is always written with whitespaces (Infogreffe, on the KBIS, on Dolibarr GUI).
You use the import function because you want to automatise the import from a source (another ERP, data from Internet etc.)
Maybe, the whitespaces could be stripped in the import functionnality so that the database constraint is respected.
Regards

**Comment by eldy** [comment]
Using a price2num() function during import could be a solution as it is done by GUI.

**Comment by aljawaid** [comment]
is there any docs to explain what the 'capital' field is for and how it is used by dolibarr?
