### ISSUE TITLE
[Install] Admin doesn't have permissions to edit the company

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5352]
# Bug

Just after a fresh install, the admin user don't have permissions to edit it's own company!

All configuration access is refused.
## Environment
- **Version**: develop
## Expected and actual behavior

Have sufficient permissions to handle the next step proposed after install: creating the company.
## Steps to reproduce the behavior

Make a fresh install from current develop (6711b7fbd11f9e13e0ce44de3c6758fb4bb34825)

**Comment by ghost** [comment]
user admin->admin = 0 after fresh install cause of bad test in user object. PR #5402

**Comment by eldy** [comment]
Fixed by commit 5950178
