### ISSUE TITLE
Montrer le numéro de remise de chèque auquel appartient un chèque 

### ISSUE THREAD

**Issue by Bagu** [Dolibarr/dolibarr#5366]
# Feature Request

Dans /compta/bank/rappro.php il serait intéressant d'ajouter le numéro de remise de chèque auquel appartient un chèque afin d'en faciliter le rapprochement
## Suggested implementation

Ajouter le numéro de remise de chèque entre parenthèse, avec un lien vers la remise dans le champ description.
EX : Règlement client (52)
Où 52 est le numéro de la remise, avec un lien pointant vers cette dernière.

http://www.dolibarr.fr/forum/11-suggestionsnouvelles-fonctionnalites/54692-rapprochement-bancaire-sur-une-remise-de-cheque

**Comment by atm-maxime** [comment]
Hello @Bagu 
Thanks for this feedback, it's indeed an important information to display.
I also think that when recording a check receipt, all bank lines related to the checks should be replaced by one line that is the check receipt. What do you think ?

Please try to open issues / feature requests in english so everyone can understand.

Regards

**Comment by Bagu** [comment]
I am not sure. Indeed, some banks do appear a line by bank deposit, although some banks appear a line check.

**Comment by Bagu** [comment]
It's not a bug, bug it's still a demand

**Comment by eldy** [comment]
Page is now htdocs/compta/bank/bankentries_list.php
Add a column with "Cheque receipt" (column ref into table ll_bordereau_cheque linked to llx_bank with field fk_bank_account)

**Comment by Bagu** [comment]
Still no plan for this feature ?

**Comment by lmag** [comment]
@Bagu
