### ISSUE TITLE
Division by zero in /compta/prelevement/fiche-stat.php on line 144

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5378]
# Bug

Division by zero in /compta/prelevement/fiche-stat.php on line 144
## Environment
- **Version**: 3.9.2
- **URL(s)**: .../compta/prelevement/fiche-stat.php?id=1

**Comment by marcosgdf** [comment]
Duplicate of bug #4447

**Comment by aconits** [comment]
Hi Marcos,

Work's for me in 3.9 and 3.8,
I can't reproduce this error, how you make a withdraw request with 0 as amount ?

**Comment by eldy** [comment]
Closed as duplicate of #4447
