### ISSUE TITLE
Translation already done check in class Translate

### ISSUE THREAD

**Issue by mowensen** [Dolibarr/dolibarr#5390]
In translate.class.php:
$this->_tab_loaded['newdomain'] remembers if 'newdomain' (part of $domain variable) has already been translated.
When you create new modules, there is a bug: forgets the modules translation folders.
My way out is to remember $this->_tab_loaded[$domain] for complete $domain variable (on lines 329 and 331) and check (line 187).

**Comment by mowensen** [comment]
I forgot toasy in previous message that i was talking about translate.class.php file

**Comment by ghost** [comment]
Hi, what Dolibarr's version was concern ?

**Comment by mowensen** [comment]
Version is 3.9.1

**Comment by eldy** [comment]
Do you mean you create a module with same name than an existing core module ?

**Comment by rdoursenaud** [comment]
I don't get it either. @mowensen mind elaborating a bit more?

**Comment by atm-maxime** [comment]
With no answer since last comment, I close this issue.
