### ISSUE TITLE
Bug with Azur model and localtax1

### ISSUE THREAD

**Issue by JeanSiB** [Dolibarr/dolibarr#5394]
# Bug

When generating a PDF with the Azur model, the LocalTax1 is not shown. 
## Environment
- **Version**: 3.9.2 and 4.0.0
- **OS**: Linux
## Expected and actual behavior

The LocalTax should appear on the generated document has it does with the version 3.8.3
## Steps to reproduce the behavior

Generate a propal with the Azur model
## [Attached files]

![image](https://cloud.githubusercontent.com/assets/20114503/16313956/a84fe6e8-3949-11e6-8272-5b3078b793de.png)
![image](https://cloud.githubusercontent.com/assets/20114503/16313966/b30d3dce-3949-11e6-9b38-01eab4a8b517.png)

**Comment by eldy** [comment]
On the setup of company, did you enable Manage second tax to yes ?
![image](https://cloud.githubusercontent.com/assets/883887/17252261/4bd9e786-55ac-11e6-9966-5de67705a1a5.png)

**Comment by rdoursenaud** [comment]
No reply from OP. Closing.
Feel free to comment below so we can reopen if need be.
