### ISSUE TITLE
Dolibarr Security Vulnerability Notification

### ISSUE THREAD

**Issue by HTBridge** [Dolibarr/dolibarr#5397]
Hello,

High-Tech Bridge Security Research Lab has discovered a security vulnerability in Dolibarr.

Preview available here: https://www.htbridge.com/advisory/HTB23302

Developers can contact us by email for details: advisory (at) htbridge.com

For any questions related to this notification message - please visit our General Information & Disclosure Policy page: https://www.htbridge.com/advisory/disclosure_policy.html

Best regards,
High-Tech Bridge Security Research Lab

**Comment by eldy** [comment]
@HTBridge 
Can you send me the describtion of the vulenrability to eldy@users.sourceforge.net ?

**Comment by fdelorenzi** [comment]
Dear all,
are there any updates on this vulnerability?

**Comment by gnovaro** [comment]
For fix this we need to include a session token and include in every form for POST and js variable for include in ajax request
http://stackoverflow.com/questions/6287903/how-to-properly-add-csrf-token-using-php/31683058#31683058

**Comment by rdoursenaud** [comment]
@eldy mind sharing details privately?
I'd also be interested at looking at an outline of the impact.
I'll get in touch with @HTBridge independently anyway.

**Comment by eldy** [comment]
@rdoursenaud Take a look at option MAIN_SECURITY_CSRF_WITH_TOKEN.
We are looking for people to test and debug application with this option on.

Before that, several fixes were added for 4.0.6 and 5.0.2, more are coming in 4.0.7 and 5.0.3

**Comment by simnandez** [comment]
No response, and this issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
