### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by clamisch** [Dolibarr/dolibarr#5409]
# Environment
- **Version**: 3.9.2
- **OS**: Linux
- **Web server**: Apache/2.2.22 (Ubuntu)
- **PHP**: apache2handler 5.3.10-1ubuntu3.21
- **Database**: MySQL or MariaDB 5.5.47-0ubuntu0.12.04.1-log
- **URL**: /commande/card.php?id=1161
# Report

In your demo site is OK preview the price of product in combobox PROPALE, but in mi site (upgrade of 3.5.2 to 3.9.2... preview the OLD price, but NOT the NEW price.
//clamisch@hotmail.es, clamisch@gmail.com
Thank you

**Comment by atm-maxime** [comment]
Hi @clamisch ,

As you say, the issue is not within Dolibarr code, but probably related to your own installation and upgrade. To have assistance with this, you should contact a Dolibarr partner. partners.dolibarr.org

Thanks.

**Comment by rdoursenaud** [comment]
No reply from OP. Considering fixed.
Feel free to comment if need be so we can reopen.
