### ISSUE TITLE
Bug: Importing Services with a simple quote

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5413]
Version: 3.9.2
Browser: Firefox 47.0.1

Hello,
When I import a service with a simple quote in desciption, note and libellé this simple quote is replaced by a question mark after the import.

Import the following service
`CODE,Mon service d’expertise,Mon service d’expertise,,,,Mon service d’expertise,,,,,1d,,10,12,20,1,0,1,,2016-01-01`
Then go to Services and you'll notice
`Mon service d?expertise`
in the fileds desciption, note and libellé

Regards

**Comment by ghost** [comment]
Hi, your problem seem come from the word quote. But can't reproduce the bug on 3.9 (also test on 3.8)

I think you should check your file encodage

**Comment by mikygee** [comment]
Hello Alexis,

What did you mean by word quote ?

I used a notepad with windows, resulting in a txt file.
I went to dolibarr/documents/import/temp on my *nix server

```
file 20160630074640-Dolibarr-Services-29Jun2016.txt
20160630074640-Dolibarr-Services-29Jun2016.txt: Non-ISO extended-ASCII text
```

When I edit the file with vi I see
`d\x92expertise`
The thing is that the e cute is properly handled/imported even is it appears as `\xe9` in the file
Regards

**Comment by Xebax** [comment]
@mikygee I suppose that "word quote" means "Microsoft Word quote". The quote character written by Microsoft Word is not the ASCII quote. Could you attach the file that is not imported correctly please?

**Comment by mikygee** [comment]
[Dolibarr-Services-02Jul2016.txt](https://github.com/Dolibarr/dolibarr/files/348578/Dolibarr-Services-02Jul2016.txt)

Voilà

**Comment by Xebax** [comment]
As pointed by @atm-alexis your file contains a right quote character that is specific to Microsoft Office. It is why the file command says that it is "Non-ISO extended-ASCII text".
You can convert your file to UTF-8 with:
`iconv -f CP1250 -t UTF-8 Dolibarr-Services-02Jul2016.txt > Dolibarr-Services-02Jul2016.utf8.txt`
[Dolibarr-Services-02Jul2016.utf8.txt](https://github.com/Dolibarr/dolibarr/files/348783/Dolibarr-Services-02Jul2016.utf8.txt)
Or you can simply edit the file and replace the right quote character by a single quote.
