### ISSUE TITLE
Bug: Date filter on customer invoices list not kept when printing central zone

### ISSUE THREAD

**Issue by oandradesanchez** [Dolibarr/dolibarr#5442]
# Bug

["Date filter on customer invoices list not kept when printing central zone*]
## Environment
- **Version**: [_3.9.2_]
- **OS**: [_Synology last DSM or Ubuntu_]
- **Web server**: [_Apache 2_]
- **PHP**: [_5.6 and 7.0_]
- **Database**: [_MariaDB 5.5.49-0065 et MySQL 5.7.12_]
## Expected and actual behavior

[_When i put a date filter on my list of customer invoices and apply it, it shows only invoices of the month selected. If i open the printer view, i expect to see the list with the filter applied without the window decoration in order to print the list i want... It doesn't work and the list is full without any filter applied._]

**Comment by oandradesanchez** [comment]
I have just tested by changing the action method from POST to GET in compta/facture/list.php file and it works know. So there  is a problem using POST method in the search form...

**Comment by eldy** [comment]
Seems fixed in 4.0. Can you confirm ?

**Comment by rdoursenaud** [comment]
No reply from OP. Considering it fixed.
Please comment if need be so we can reopen.
