### ISSUE TITLE
Export Excel from datatable component do not work

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#5444]
# Bug

on http://localhost/dolibarr/public/test/test_arrays.php the PDF button on Example 2 do not work
## Environment
- **Version**: dev
- **OS**:debian
- **Web server**: apache
- **PHP**: 7.0
- **Database**: mysql 5.7
- **URL(s)**: http://localhost/dolibarr/public/test/test_arrays.php

**Comment by rdoursenaud** [comment]
AFAIK pdfmake dep has never hit the repo, so I believe @eldy never intended to support this.
Feel free to comment so we can reopen if need be…
