### ISSUE TITLE
Bug: Expenses Form : SQL error on updating line

### ISSUE THREAD

**Issue by toufikoj** [Dolibarr/dolibarr#5450]
# Environment
- **Version**: 3.9.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.6.21
- **Database**: MySQL or MariaDB 5.5.46-0+deb7u1-log
- **URL**: /expensereport/card.php
# Report

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20160705170323
Dolibarr: 3.9.2
Niveau de fonctionnalités: 0
PHP: 5.6.21
Server: Apache
OS: Linux webm636.60gp.ha.ovh.net 3.14.60-grsec-hosting-web-3.14 #1 SMP Wed Jun 1 13:57:11 UTC 2016 x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

Url sollicitée: /expensereport/card.php
Referer: https://server/expensereport/card.php?id=8&action=editline&rowid=116
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: UPDATE llx_expensereport_det SET comments='Abonnement mensuel TCL',value_unit=17,8,qty=1,date='20160606000000',total_ht=15.45,total_tva=1.55,total_ttc=17,tva_tx=10,fk_c_type_fees=12,fk_projet=null WHERE rowid = 116
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '8,qty=1,date='20160606000000',total_ht=15.45,total_tva=1.55,total_ttc=17,tva_tx=' at line 1

**Comment by olsesacl** [comment]
[Fix #5450 Bug: Expenses Form : SQL error on updating line #5496](https://github.com/Dolibarr/dolibarr/pull/5496)
