### ISSUE TITLE
problem when clone facture 2nd Tax not work 0

### ISSUE THREAD

**Issue by bobo635** [Dolibarr/dolibarr#5452]
# Instructions

_This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report._
_Please:_
- _only keep the "Bug" or "Feature Request" section_
- _replace the bracket enclosed texts with meaningful informations_
- _remove any unused sub-section_
# Bug

[_Short description_]
## Environment
- **Version**: 3.9+
- **OS**: ubuntu server 14.04 LTS
- **Web server**:apache 2
- **PHP**: [_PHP version_]
- **Database**: [_Database type and version_]
- **URL(s)**: [_Affected URL(s)_]
## Expected and actual behavior

[_Verbose description_]
## Steps to reproduce the behavior

[_Verbose description_]
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[_Files_]
# Feature Request

[_Short description_]
## Use case

[_Verbose description_]
## Suggested implementation

[_Verbose description_]
## Suggested steps

[_List of tasks to achieve goal_]

**Comment by simnandez** [comment]
works ok with lastest github sources, branch 3.9

**Comment by simnandez** [comment]
@bobo635  I close the Issue because works fine with 3.9.4. If you still have the probleme with a 3.9.4 open a new Issue
