### ISSUE TITLE
Set MAIN_USE_JQUERY_DATATABLES give 404 on pdfmake.js

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#5455]
# Bug

Set MAIN_USE_JQUERY_DATATABLES give 404 on pdfmake.js
## Environment
- **Version**:develop

**Comment by rdoursenaud** [comment]
I don't see any pdfmake code in the current repos except in a test comment. O_o
Looks fixed to me. Closing.
Feel free to comment if need be so we can reopen.
