### ISSUE TITLE
Bug: Untranslated key

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5468]
# Bug

Untranslated key "EmailNotValid" in /expensereport/card.php

![captura de pantalla 2016-07-09 a las 14 04 04](https://cloud.githubusercontent.com/assets/168744/16707852/1a327384-45de-11e6-8544-2b2780145168.png)
## Environment
- **Version**: 3.9.2

**Comment by eldy** [comment]
String seems to be no more present into 4.0 code so i suppose it is fixed.
