### ISSUE TITLE
Bug: Trying to cancel a expense and nothing happens

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5469]
# Bug

Canceling an expense does not work
## Environment
- **Version**: 3.9.2
- **Database**: Postgresql
- **URL(s)**: http://dolibarr.local/expensereport/card.php?id=1&action=confirm_cancel&confirm=yes&detail_cancel=a
## Expected and actual behavior

I expect to see something
## Steps to reproduce the behavior
1. Click Cancel and then write a comment

**Comment by eldy** [comment]
Can't reproduce on 4.0

**Comment by marcosgdf** [comment]
Bug report is for 3.9

**Comment by rdoursenaud** [comment]
@eldy If we really want to maintain three versions (aka n, n-1 and n-2) we should backport fixes.
IMHO we don't have enough manpower for that.
Maybe we should reduce the number of maintained versions to 2 like LibreOffice. A stable (Let's say for 2 years) and a fresh (current velocity of 6 months). This would also make people asking for a LTS and bothered by the velocity of the release cycle shut up ;)

@marcosgdf Sorry to have hijacked your issue.

**Comment by marcosgdf** [comment]
Closing as ignored until deprecation
