### ISSUE TITLE
Bug: Products listing performance issue

### ISSUE THREAD

**Issue by azzi907** [Dolibarr/dolibarr#5483]
# Bug Products listing performance issue

_When we have large products data in database like 100000+ products products list page takes too long to load around 8 to 10 sec for me, its because of total products count query not implemented correctly_
## Environment
- **Version**: _3.9.1_
- **OS**: _Mac OS_
- **Web server**: _apache2_
- **PHP**: _7_
- **Database**: _Mysql 5.5_
- **URL(s)**: _/htdocs/product/list.php?leftmenu=product&type=0_
## Expected and actual behavior

_it should count total number products count with select count(something) from products table instead of querying all records_
## Steps to reproduce the behavior

_Login to admin , go to products and click on list from left menu, Make sure you have 100000+ products in database_
## Suggested steps

_Fix the list.php to count total products from database with select count(something) query_

**Comment by simnandez** [comment]
If you have a very important number of data, you need to activate the constant MAIN_DISABLE_FULL_SCANLIST, this disable complete scan of tables to know the total amount of element to allow the pagination to show total number of pages

**Comment by azzi907** [comment]
@simnandez 

yes but it creates issue with pagination when you enable that..

**Comment by azzi907** [comment]
```
    $nbtotalofrecords = 0;
    if (empty($conf->global->MAIN_DISABLE_FULL_SCANLIST))
    {
        $result = $db->query($sql);
        $nbtotalofrecords = $db->num_rows($result);
    }
```

So $nbtotalofrecords will be always zero if(MAIN_DISABLE_FULL_SCANLIST) is enabled

**Comment by simnandez** [comment]
As I said:  this disable complete scan of tables to know the total amount of element to allow the pagination and show total number of pages, and you have not long time to load the list page

**Comment by simnandez** [comment]
I close this issue, as it will not be implemented
