### ISSUE TITLE
Bug: execute hook getFromMail

### ISSUE THREAD

**Issue by maikaspanring** [Dolibarr/dolibarr#5484]
## Bug:

The Hook getFormMail in the file html.formmail.class.php do not show the result because the if statement is not passable:

https://github.com/Dolibarr/dolibarr/blob/5ebbe028531240c2deb0ed4073e157237003491f/htdocs/core/class/html.formmail.class.php#L259

if statement:
if(**!empty**($reshook)
## Environment
- **Version**: 3.8 - 4.0
- **PHP**: 5.6.17
- **Database**: MySQL 5.5.47
## Expected and actual behavior

The hook getFormMail get executed but did not get returned.
## Suggested steps

change line 259 in the file html.formmail.class.php to:
if (**is_numeric**($reshook))
like the header.php hook at line 1472
https://github.com/Dolibarr/dolibarr/blob/f256de323e8c07391657b306b422cf0eccf94307/htdocs/main.inc.php#L1472

or put the getFormMail hook in the array list for the **addreplace** hooks (hookmanger.class.php line 133 - 174)
https://github.com/Dolibarr/dolibarr/blob/5ebbe028531240c2deb0ed4073e157237003491f/htdocs/core/class/hookmanager.class.php#L135

**Comment by eldy** [comment]
Fixed by 0f4f4ea
