### ISSUE TITLE
Source and destination accounts

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5503]
# Bug

Source and destination accounts hints in account entries don't use the same field.
Source seem to use the label and destination the reference.

![image](https://cloud.githubusercontent.com/assets/1210367/16919549/6d0fbe08-4d0a-11e6-924c-94adc16cac13.png)

![image](https://cloud.githubusercontent.com/assets/1210367/16919555/75f75206-4d0a-11e6-8a8a-d7371857fd87.png)

![image](https://cloud.githubusercontent.com/assets/1210367/16919560/7a53a4a8-4d0a-11e6-96c1-6ce04a7c8034.png)
## Environment
- **Version**: 3.9.2
- **URL(s)**: /compta/bank/account.php

**Comment by BebZ** [comment]
Can't reproduce and don't know what you mean by "Source seem to use the label and destination the reference."

**Comment by rdoursenaud** [comment]
@BebZ Well make a transfer between two accounts and look at the entries in each account.
You will see that they mix the label and the reference of the accounts in the descriptive text.

What's expected for the example I posted is "De Cartes bancaires vers Caisse d'épargne" _OR_ "de CB vers BQ" with the first being the preferred one. Not a mix of the two like it is now.

**Comment by BebZ** [comment]
Understood and True : can't mix a label and a reference 
![image](https://cloud.githubusercontent.com/assets/3694135/16988022/40e1ba26-4e8f-11e6-988e-d7ef706f9f47.png)
