### ISSUE TITLE
# Bug: when you change the check number after receipt of the invoice

### ISSUE THREAD

**Issue by nicoxygen** [Dolibarr/dolibarr#5506]
When you decide to change the check number after the bill is passed to pay, the number is well taken into account but it is not included in the checks for deposit.

Version: 3.9.2
URL: htdocs/compta/paiement/cheque/index.php?leftmenu=checks&mainmenu=bank

**Comment by eldy** [comment]
This could be implemented if check deposit is not yet validated.
But what if it is ? I think we should not in such a case, because it means we won't have same information than deposit provided to the bank.
Or we should replace bad value xxx with 
yyy (old value xxx)

**Comment by atm-maxime** [comment]
This seems to be fixed in latest version.
Please check and reopen the issue if needed.
