### ISSUE TITLE
Bug: Translation menu resets left menu

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5509]
# Bug

Accessing the translation menu from setup resets the left menu.
## Environment
- **Version**: 4.0.0-rc
- **URL(s)**: /admin/translation.php
## Expected and actual behavior

Keeping the left menu "setup" unfolded is expected
## Steps to reproduce the behavior

Install dolibarr 4.0.0-rc and access Home > Setup > Translation

**Comment by eldy** [comment]
Fixed by 5fa8a6c311f03d20daf8a3ea405425cd3a50142b
