### ISSUE TITLE
Bug: wrong page after change thirdparty on bank transactions

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#5513]
# Instructions

_This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report._
_Please:_
- _only keep the "Bug" or "Feature Request" section_
- _replace the bracket enclosed texts with meaningful informations_
- _remove any unused sub-section_
# Bug

Bug: wrong page after change thirdparty on bank transactions
## Environment
- **Version**: 4.0
- **OS**: [_Server OS type and version_]
- **Web server**: [_Webserver type and version_]
- **PHP**: [_PHP version_]
- **Database**: [_Database type and version_]
- **URL(s)**: [_Affected URL(s)_]
## Steps to reproduce the behavior

Go bank transactions, put a thirdparty on field box; select the first page of the transactions. 
After that change the thirparty to another with less transactions; the page it will be -1.
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[_Files_]
# Feature Request

[_Short description_]
## Use case

[_Verbose description_]
## Suggested implementation

[_Verbose description_]
## Suggested steps

[_List of tasks to achieve goal_]

**Comment by simnandez** [comment]
I Can't reproduce it in 4.0.0-rc2

**Comment by braito4** [comment]
![screen shot 2016-08-04 at 20 12 46](https://cloud.githubusercontent.com/assets/1913498/17413095/2394f97c-5a80-11e6-9bb2-aac28c34997b.png)
4.0 rc 2

First you hace to select a thirdparty with which one you hace a lot of transactions, select a page; and the switch to another thirdparty which less transactions,

**Comment by Xebax** [comment]
Affected URL: compta/bank/account.php
