### ISSUE TITLE
Bug: should not be able to use a not customer nor prospect on contract creation

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5518]
# Bug

Thirdparty selector on contract creation allows selecting a thirdparty that does not have the customer nor prospect status.
## Environment
- **Version**: 4.0.0-rc
- **URL(s)**: /contrat/card.php?action=create&leftmenu=contracts
## Expected and actual behavior

I believe this should be avoided and only customer status thirdparties should be presented.

**Comment by eldy** [comment]
Contract can also be used to follow supplier contracts. (for example a subscription to a ssl certificate to know when it will expire)

**Comment by rdoursenaud** [comment]
OK, didn't think about that use case.

Thanks!
