### ISSUE TITLE
Expense / Income report shows VAT return with wrong sign (cash accounting only)

### ISSUE THREAD

**Issue by NilsWalkowiak** [Dolibarr/dolibarr#5558]
# Bug

[_Short description_]
If there is a VAT return, in the "income / expense report" (htdocs/compta/resultat/index.php) the amount returned reduces the income. The returned amount should actually increase the income.
## Environment
- **Version**: [_tested with 3.9.2 and the shared online demo_]
## Possible Solution

The reason is tax returns have negative amounts in llx_tva, but they are added to the income. I think the following is causing the problem (in a.m. file on line 359):
$encaiss[$obj->dm] += $obj->amount;

It should be 
$encaiss[$obj->dm] += $obj->amount*-1;
or
$encaiss[$obj->dm] -= $obj->amount;

Line 362 needs an adjustment accordingly.
## Steps to reproduce the behavior

Create a supplier invoice with VAT, pay it and create a matching tax return. In the "Income / Expense Report" the returned amount shows as negative income. See attachment (100 EUR net, 20 EUR VAT)
![incomeexpense](https://cloud.githubusercontent.com/assets/3833451/17186145/44818d96-5434-11e6-80cb-0743c5344a9f.PNG)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
