### ISSUE TITLE
Bug: Margin doesnt calculate properly 3.9.3 (Same that 3.9.2)

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#5565]
# Environment
- **Version**: 3.9.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: apache2handler 5.4.45
- **Database**: MySQL 5.5.50-cll-lve
- **URL**: /erp/comm/propal.php?id=613
# Report

Same problem persists after update from 3.9.2 to 3.9.3
Test are made only with official Dolibarr modules activated, (not all), and WYSIWYG Off
Test from various web browsers, delete cache, etc

As can see here
https://youtu.be/tYcXs6So2pA

**Comment by PlanPc** [comment]
I have also tried disabling third, commercial modules, budgets, invoices, suppliers and activating them again, same result in video.

Regards

**Comment by altairis-tof** [comment]
i think it is fixed with the #5534 fix : https://github.com/Dolibarr/dolibarr/blob/3.9/htdocs/core/js/lib_head.js.php

**Comment by PlanPc** [comment]
Thank you for your speed!, I will test it later and post here results.

Regards
