### ISSUE TITLE
Bug: Error when creating withdraw 

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5574]
# Bug

When creating an new withdraw (clicking on "withdraw all"-button), two warnings are shown and it is not possible to finish this task.
### The warnings are:

> Warning: fopen(/.../documents/prelevement/receipts/receipts/T160801.xml): failed to open stream: No such file or directory in /.../compta/prelevement/class/bonprelevement.class.php on line 1236
> 
> Warning: Cannot modify header information - headers already sent by (output started at /.../compta/prelevement/class/bonprelevement.class.php:1236) in /.../main.inc.php on line 954
## Environment
- **Version**: 3.9.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.24
- **Database**: MySQL 5.1.73-log
- **URL(s)**: https://.../compta/prelevement/create.php?mainmenu=bank
## Steps to reproduce the behavior

1) create an invoice
2) switch to tap "Standing orders" at the invoice
3) click on "Make a withdraw request"-button
4) go to Bank/Cash -> Standing orders -> New standing order
5) click on "withdraw all"

**Comment by eldy** [comment]
It looks like this was fixed with patch c1c44ce9964ad831a606a39a3b9bf4d34d93ab3e

**Comment by sbschumacher** [comment]
Yes, it is working right after the patch. Thank you @eldy !
