### ISSUE TITLE
Possible XSS

### ISSUE THREAD

**Issue by AppChecker** [Dolibarr/dolibarr#5581]
Greetings!

We've checked your source code with ["AppChecker"](https://npo-echelon.ru/en/solutions/appchecker.php) static analyzer and found number of defects that can be used for xss.

We don't want to post it here so you can contact us (appchecker@cnpo.ru) or tell us who to contact so we can tell the details.

**Comment by eldy** [comment]
Thanks for your feedback.
You can submit your reports to me eldy@destailleur.fr or contact@dolibarr.org

**Comment by eldy** [comment]
Your report has been processed. Fix should be available into 5.0 in january.
