### ISSUE TITLE
NEW: save outgoing mails additional to your imap mailbox in folder sent messages

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#5587]
# Instructions

In form, we has discussed with @eldy in Genova we will integrate our imap dolimail function and the range of outgoing mail functions from dolimail in the core version
# Feature Request
1.  Benefit

That is a additional function in mail Settings to save all sent outgoing mails to the users sent mails Mailbox
## Suggested steps

we will add a if Statement to the cmailfile.class.php and add additional form fields in the /admin/mail.php
## Additional Form-Fields in /admin/mail.php

![image](https://cloud.githubusercontent.com/assets/3923753/17433981/118711ba-5b08-11e6-8bec-5fc9bf989d27.png)

**Comment by BebZ** [comment]
Hello Guido ! What a nice move towards ,)
for EACH user of dolibarr, there will add the mails in their sent mailboxes ? 
is it also working on google apps environment ? 
Thanks

**Comment by sanjiiiv** [comment]
Dolibarr 6.0.2, sent mails are not showing in user's IMAP folder but in earlier version the same feature was available.

**Comment by TonchoTonchev** [comment]
Hi all,
Have any action been taken here?
