### ISSUE TITLE
Feature request: Remove non-maintained jquerytreeview plugin 

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5590]
In the project page the developer states that the plugin is not maintained anymore. I think we should only use maintained libraries to ensure the future of the project.

https://github.com/jzaefferer/jquery-treeview

**Comment by rdoursenaud** [comment]
Do you know what we're using it for and if there's any viable alternative?

**Comment by marcosgdf** [comment]
AFAIK it is used for the tree view of categories. Viable alternatives… idk, maybe treetable? https://github.com/ludo/jquery-treetable

**Comment by rdoursenaud** [comment]
I just had a look.
The jquery-treeview recommends https://mbraak.github.io/jqTree/ as an alternative.
There's also a TODO comment from @eldy in ```htdocs/core/lib/treeview.lib.php``` suggesting https://www.jstree.com. 30dae3def2a
