### ISSUE TITLE
Feature request: Extra fields like Skype (Twitter & Github)

### ISSUE THREAD

**Issue by GrandadEvans** [Dolibarr/dolibarr#5591]
# Feature Request

At the minute I have Twitter as a custom property of both third parties and contacts and I have just altered the code so that a Twitter logo and username link appears alongside the other contact information.

I would like there to be other contact fields such as Github links etc. The list is endless really as other users may want other social networks links including.

Do you think this would be a good addition?

![image](https://cloud.githubusercontent.com/assets/896346/17459334/d679b392-5c2a-11e6-8e0e-66092e2c4eef.png)
## Use case

Idea 1: add a new social category that has a link, logo, username and an option to display the information on the cards contact information.

Idea 2: Add an option to the custom properties that will mark the property as a contact address, maybe with some custom formatting associated with it.

Idea 3: Failing that there is always the option to add each individual property by itself and just keep adding them to the codebase as and when they appear (to an extent you would have to do that anyway).
## I'll do the work

I have added this as an issue as I am willing to carry out the work and create all the tests etc as I normally work in a test driven OOP manner.
What I will need is guidance. I have only been using Dolibarr for a week or so and I am not familiar with the philosophy (although I have seen a code guide or similar).

I am probably going to do this anyway, I'd just rather do it with the cooperation and help of the regular contributors then I can help others out in return. If I do it myself I shall just fork and keep rebasing when this gets updated.

Thanks in advance and I look forward to any suggestions.
John

**Comment by aljawaid** [comment]
From a user's (business operational) point of view, this would be excellent as it would help store all of the relevant (social) contact details in place per company and/or contact.  I hope this gets to the core of the software.

**Comment by aspangaro** [comment]
Today, it's interessant to show this information but which social networks at large to use ?

Maybe, use the module Skype to transform it in module Social Networks and add a panel option to select the social network to use or not in dolibarr.

I propose this longer list : 
- Facebook
- Twitter
- Google +
- Linkedin
- Viadeo
- Instagram
- Flickr
- Pinterest
- Youtube
- Dailymotion
- Vimeo
- Vine
- Periscope
- Slideshare
- Skype
- BBM
- Telegram
- Google Hangouts
- Viber
- Line
- Whatsapp

**Comment by rdoursenaud** [comment]
Nice idea :+1: 
You're right @aspangaro, this should be in an extensible social network module.

Looking forward to your contribution @GrandadEvans.

**Comment by GrandadEvans** [comment]
Cheers for the responses,
I think the way forward is an interface that can be extended. Like I may have said above, I am not up on the coding styles etc for Dolibarr so I will have to have a good look at that first. I also have quite a bit of work on at the minute so I'm looking at 2-3 weeks plus before I can do it.

**Comment by eldy** [comment]
I +1 the idea of changing module skype to rename it social networks. Then an option to choose which service to manage (skype, ...)

**Comment by aljawaid** [comment]
**Replace skype module with social networks module to support more fields**
https://github.com/Dolibarr/dolibarr/commit/af2e19eba8375a71f934dd90b5f4c9f58a3c4bee

**Add field twitter and facebook**
https://github.com/Dolibarr/dolibarr/commit/72895bebbf02d5f90d6f0a75e4fd95d9f611e795#diff-781a2378349cec2e95e27634866f9fb2

**Comment by hregis** [comment]
@eldy 
I think it would require a complementary table so that user can have different email addresses, twitter, etc. Because in multicompany a user can be part of several different companies, with different addresses!

**Comment by frederic34** [comment]
I think we must introduce a new dictionary instead adding field after field

**Comment by aljawaid** [comment]
I agree but it is beyond my development skills :(

**Comment by atm-maxime** [comment]
I think this can be closed now. Implemented in v11 ?!

**Comment by eldy** [comment]
@frederic34 I think you was the guy that introuce array instead of n fields for social networks ?
If yes, can you help me to solve this deprecated code (property skipe, twitter, ...): https://scrutinizer-ci.com/g/Dolibarr/dolibarr/issues/develop/files/htdocs/adherents/class/adherent.class.php?orderField=path&order=asc&honorSelectedPaths=0
I think we can replace with the new array ?

**Comment by frederic34** [comment]
@eldy https://github.com/Dolibarr/dolibarr/pull/15354
