### ISSUE TITLE
Following the task : #5473 - Can not Classify Canceled a donation

### ISSUE THREAD

**Issue by rassakali** [Dolibarr/dolibarr#5606]
The task https://github.com/Dolibarr/dolibarr/issues/5473 is not yet resolved completely.
(View comments on the task)

**Here a copy of the comment:**
Have you also seen the conditions "$remaintopay == 0"?
I propose to change it with "$totalpaid == 0"

because: the "$remaintopay == 0" means the button "ClassifyCanceled" is displayed if is fully paid. ie it can be classified canceled even if is fully paid!

but, normally it is possible to "ClassifyCanceled" if there is no payment. then the code will be:
if (($object->statut == 0 || $object->statut == 1) && **$totalpaid** == 0 && $object->paid == 0)

**Comment by Mavyre** [comment]
Please up, it's not a feature request, it's a bug.

EDIT: Created PR #8888

**Comment by eldy** [comment]
Fixed by #8888
