### ISSUE TITLE
mssql is not available in PHP 7.0 anymore

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5607]
The mssql extension has been [removed from PHP 7.0](https://wiki.php.net/rfc/removal_of_dead_sapis_and_exts?s%5B%5D=mssql).

Is there anyone maintaining that code ?

Should we remove the mssql class and installer options like we did for the mysql driver ?

The alternative is to refactor the code to use [Microsoft's Azure's driver](https://github.com/Azure/msphpsql/releases).

**Comment by eldy** [comment]
@hregis Do you use this driver ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by rdoursenaud** [comment]
Well mssql is still there…
