### ISSUE TITLE
sqlite_select_db() is not available since PHP 5.4

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5609]
# Bug

sqlite has been removed from PHP 5.4.

This means no SQLite 2 support.
SQLite 3 support has been added at 0ef46b06f400487e7350e94fe8d6346ccbdf0df2 using the maintained sqlite3 extension.

Is there anyone maintaining that code ?

Should we remove the sqlite class and installer options like we did for the mysql driver ?

**Comment by marcosgdf** [comment]
In fact, Dolibarr does not support SQLite 2, but there is one driver that uses PDO and another one that does not use it. They are not deprecated like mysql driver was.

![captura de pantalla 2016-08-11 a las 15 36 25](https://cloud.githubusercontent.com/assets/168744/17590293/85de0ec6-5fd9-11e6-9b90-5bb956f8e8a5.png)
![captura de pantalla 2016-08-11 a las 15 36 31](https://cloud.githubusercontent.com/assets/168744/17590292/85dc8aa6-5fd9-11e6-9e28-9c5f7d333d7b.png)

I think we should maintain only one of them.

**Comment by rdoursenaud** [comment]
Oh, I knew that but didn't remember :(

The thing is that the PDO version `sqlite.class.php` uses `sqlite_select_db()` which I believe to be  an sqlite provided function. I already added a fixme a while ago but never got around fixing it.

Running PHPCompatibility against the current source code revealed that again, hence this report.

**Comment by rdoursenaud** [comment]
Upon closer inspection both versions are affected!

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
