### ISSUE TITLE
Bug: There is no possible way to prevent an user from logging in with afterLogin hook

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5623]
If the code contained in `afterLogin` function returns -1, the hook will always return 0 to the code in main.inc.php and therefore an error is never triggered.

Until this is fixed, the deprecated trigger USER_LOGIN is the only one that fulfills the needs of developers.

Seen in 3.9

**Comment by eldy** [comment]
Both trigger and hook afterlogin are designed to be ran AFTER login. So they can't prevent a loggin because logging is already done, at leas partially.
If you want to change rules to test login, can't you replace the login manager (file into htdocs/core/login ?)

**Comment by marcosgdf** [comment]
Yes, they are designed to be ran after log in, but the code expects the trigger/hook to reject the login and stop the user from doing it.
