### ISSUE TITLE
Bug: ThirdParty translation in customer docs or supplier docs

### ISSUE THREAD

**Issue by joseplluis** [Dolibarr/dolibarr#5632]
# Bug

On listing Customer documents (propals, orders or invoices list) appears the column Third party.
And the same case for Supplier documents.

I think that the correct text to translate should be "Customer" for Customer documents, and "Supplier" for Supplier documents.

**Comment by eldy** [comment]
Sometimes, things are not so clear. For example, for a shipment, the customer is not always a customer but may be a partner, or a reseller.

Also, there is no object "customer" nor "supplier" dolibarr but only "thirdparties" with a status "customer", "prospect" and/or "supplier".
To have a common behaviour on all screen, because field is related to a third party object, name of column was renamed "ThirdParty" everywhere.
For this reason, i am not sure we must move back again.
What are thinking other users ?

**Comment by joseplluis** [comment]
The shipment case is more complex, but I think that the ThirdParty/Customer of the shipment should be the same Customer of the Order and Invoice, in other words, the company who will pay.
In case of partners, resellers, o other adresses for the shipment, could be informed in the Contacts/Adresses tab.

A third party in a selling channel should be a Customer.
And a third party in a buying channel should be a Supplier.

I'm expecting also other users opinions ;)

**Comment by BebZ** [comment]
So you want to restrain display of only Supplier in selling channels and only Customers in Selling Channel ? 
Why not, but what if, as you say, for partners, (or in my case, for large multi entities groups) the thirdparty who is "ordering" is not the "paying" one, and has to be changed on the invoice ? 

Maybe you could explain with a screenshot this sentence : 
"On listing Customer documents (propals, orders or invoices list) appears the column Third party.
And the same case for Supplier documents."

**Comment by joseplluis** [comment]
This is a minor fix.

The object is a thirdparty with a status (customer, prospect and/or supplier). 
But when a thirdparty is in a customer invoice acts only as a customer, and a thirdparty in a supplier invoice acts only as a supplier.

The change try to show how is acting the thirdparty in a particular place.

In the orders case could be different. Maybe the thirdparty could be "Receiver"?

**Comment by eldy** [comment]
I understand the idea "try to show how is acting the thirdparty in a particular place". 
The patch did it on place where things are not amibugous, so it is not a so bad idea. Where things are ambiguous (proposal, shipments, intervention, ...) we won't be able to change. This means sometimes we will use thirdparty and sometime not and i hate when things are not homogeneous. I keep more time to reflect on this.
