### ISSUE TITLE
Can't create a draft customer invoice after migrating from 3.6.2 to 3.9.2

### ISSUE THREAD

**Issue by CyrilBrulebois** [Dolibarr/dolibarr#5636]
# Bug

Starting from a functional dolibarr 3.6.2 setup, we upgraded (apparently successfully, at least at first) to 3.9.2, and it's no longer possible to create a draft customer invoice. The upgrade was done using dpkg with the new package, then by validating the 3.6→3.7 & 3.7→3.8 & 3.8→3.9 migration scripts.
## Environment
- **Version**: 3.9.2
- **OS**: Debian 8
- **Web server**: Apache 2.4
- **PHP**: 5.6.22
- **Database**: MySQL 5.5.49
- **URL(s)**: `/compta/facture.php`

(Note: It seems 3.9.3 was released but the website still claims 3.9.2 is the latest stable release; the changelog doesn't seem to indicate this particular issue is fixed in 3.9.3 anyway.)
## Expected and actual behavior + Steps to reproduce the behavior

Clicking the new invoice button works, as I'm taken to the following URL: `/compta/facture.php?action=create&leftmenu=customers_bills` but after having filled out all items, validating the form through “Create draft” leads to a blank page. I can see the POST request through FireBug though, and it's indeed received by Apache. Nothing in error.log.

I'm not sure how to debug this further, any assistance is welcome.

**Comment by CyrilBrulebois** [comment]
As a side note, the “Compta Expert” module (accountingex) was enabled in 3.6, in its 3.5.x form; but it was disabled, then removed before upgrading. I'm not sure whether this could have any influence on this particular/gross bug, but I thought I'd mention it just in case.

**Comment by eldy** [comment]
Whan you get error blank page, what do you have into your apache log file ?
Try also to run page
/install/repair.php

**Comment by CyrilBrulebois** [comment]
Apache log file (IP & HOSTNAME anonymized):

`$IP - - [17/Aug/2016:18:07:53 +0200] "POST /dolibarr/compta/facture.php HTTP/1.0" 200 5354 "https://$HOSTNAME/dolibarr/compta/facture.php?action=create&leftmenu=customers_bills" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"`

`/install/repair.php` gives me:

> Install pages have been disabled for security reason (by lock file install.lock into dolibarr root directory).

and once `install.lock` moved away, I'm getting a successful execution of the repair script, yet the problem stays exactly the same (including the line in access.log file).

**Comment by eldy** [comment]
So can you enable module syslog and then take a look into dolibarr.log file ?

**Comment by CyrilBrulebois** [comment]
Thanks for the pointer, you'll find an excerpt of the log in attachment.
[dolibarr.txt](https://github.com/Dolibarr/dolibarr/files/491302/dolibarr.txt)

**Comment by CyrilBrulebois** [comment]
Is there anything I can do to help investigate this further?

**Comment by eldy** [comment]
It seems you are using an external module called "Note de frais". Can you disable it ?
Then clean log file and retry to execute the error and repost the log file

**Comment by CyrilBrulebois** [comment]
Thanks @eldy! Disabling it seems to have fixed or worked around the regression.

Just in case somebody else stumbles upon this issue, current version is 1.6.1.

My contact will be checking what's happening on the ndfp (for “Notes de frais+”) plugin front; an update might be required to work with 3.9.x; at least I can see a version available for 3.7, 3.8, and 3.9 on dolistore. Which seems like good news, the module seems maintained at the very least.

Thanks for pinpointing this module as a suspect, highly appreciated. I'll post an update to this bug report when I get some more feedback (e.g. after installing an updated plugin). If you don't hear from me for a while, feel free to close this bug report altogether.

Thanks again!

**Comment by rdoursenaud** [comment]
No news in a while. Closing.
@CyrilBrulebois Feel free to add a comment if need be.
