### ISSUE TITLE
Dolibarr 4.0 RC2 bug when create new contract

### ISSUE THREAD

**Issue by mjromero** [Dolibarr/dolibarr#5641]
When I try to change the price of one line of product in a contract, I get this error:

"Error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' fk_user_ouverture=NULL, fk_user_cloture=1, commentaire='', fk_unit=NULL WHERE r' at line 1"

![1](https://cloud.githubusercontent.com/assets/21090416/17753853/0e55f5dc-64d2-11e6-97c0-9398b55f0679.jpg)

**Comment by nicolasb827** [comment]
Hi,

I found the error, and the fix may be (not sure):
$sql.= " fk_user_author=".(!empty($this->fk_user_author)?$this->fk_user_author:"NULL").",";
line 2628.
It seems to work for me now.
I do not create a pull request, I am not sure that there is no side effect.
