### ISSUE TITLE
Bug: lot serial

### ISSUE THREAD

**Issue by panypunk** [Dolibarr/dolibarr#5642]
# Environment
- **Version**: 3.9.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.36
- **Database**: MySQL or MariaDB 5.5.49-37.9-log
- **URL**: /dolibarr/product/stock/product.php?id=397
# Report

Questo lotto/numero seriale (BB0J043-02) esiste già con una differente data di scadenza o di validità (trovata 01 gen 1970, inserita 01 gen 1970 )

Problem with dolibarr lot serial, see up for detail

**Comment by BebZ** [comment]
what is the scenario ? stock modification / stock transfer to another warehouse / dispatch from supplier order ? 

Thanks for your details and screenshots if possible

**Comment by BebZ** [comment]
Hey perché non risponde ?
FIxed by Eldy's PR on 4.0
Should  cherry pick for 3.9 fr backward compatibility @fappels

**Comment by panypunk** [comment]
scusa ma non avevo letto.
il problema si presenta quando si effettua una modifica della giacenza, indicando il lotto e la data di scadenza del prodotto correttamente uguali a quelli del prodotto da modificare, viene indicato l'errore.
Purtroppo il problema si presenta con  prodotti gestiti a lotti e data di scadenza anche durante l'eliminazione di una bolla. Il messaggio è uguale a quello che esce durante i movimenti di magazzino.

**Comment by BebZ** [comment]
in table llx_product_batch
you must transform field datetime in "date" for dlc and dluo fields
and cherry pick last changes of Eldy on 4.0.
I updated and it works, dont forget to backup before changing those f*cking fields

**Comment by fappels** [comment]
I will make a manual cherry pick PR of the change into 3.9. 
When changed you don't need to change the datetime fields, the change ignores the time part in the value check.
