### ISSUE TITLE
Bug: transifex keys BoxTitleLatestModifiedSupplierOrders and BoxTitleLastModifiedCustomerBills doesn't exist in other language

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#5643]
# Bug
## Environment
- **Version**: 4.0.0-rc2
- **OS**: Windows NT
- **Web server**: Apache/2.2.22 (Win64) PHP/5.4.3
- **PHP**: apache2handler 5.4.3
- **Database**: MySQL 5.5.24-log
- **URL**: /dolibarr_dev/index.php?mainmenu=home

**Comment by eldy** [comment]
They will appears as soon as a sync dolibarr -> transifex will be done.
