### ISSUE TITLE
Error editing Sell Price on products/services

### ISSUE THREAD

**Issue by Alfil3k** [Dolibarr/dolibarr#5646]
# Bug

Error : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':-15:-9:-7, localtax1_type = '3', localtax2_type = '5', barcode = null, fk_barco' at line 1 - UPDATE cnt_product SET label = 'Alquiler/Mantenimiento Grandstream GXP1620', ref = 'SRV00020', ref_ext = null, tva_tx = 4, recuperableonly = 0, localtax1_tx = 0.5, localtax2_tx = -19:-15:-9:-7, localtax1_type = '3', localtax2_type = '5', barcode = null, fk_barcode_type = null, tosell = 1, tobuy = 1, tobatch = 0, finished = 0, weight = null, weight_units = null, length = null, length_units = null, surface = null, surface_units = null, volume = null, volume_units = null, seuil_stock_alerte = null, description = '', url = null, customcode = '', fk_country = null, note = '', duration = '', accountancy_code_buy = '', accountancy_code_sell= '', desiredstock = null, fk_unit= NULL, price_autogen = 0, fk_price_expression = NULL, fk_user_modif = 1 WHERE rowid = 53
## Environment

Dolibarr ha detectado un error técnico.
He aquí la información que podrá ayudar al diagnóstico:
Fecha: 20160819194720
Dolibarr: 3.9.3
Nivel de funciones: 0
PHP: 5.3.10-1ubuntu3.14
Server: Apache/2.2.22 (Ubuntu)
OS: Linux portal 2.6.32-27-pve #1 SMP Tue Feb 11 16:18:29 CET 2014 i686
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

URL solicitada: /product/price.php?id=53
Referer: https://crm.costanetworks.es:8443/product/price.php?action=edit_price&id=53
Gestor de menú: eldy_menu.php
## Expected and actual behavior

Can't modified Min sell prince on product/Service when enable IRPF with multiple values  like -19:-15:-9:-7
## Steps to reproduce the behavior

Change the IRPF values on dictionaries -> IVA.
Add Values -19:-15:-9:-7 on Type 3 column.
Go to Change on Sell Price over any product or service and click on save.

**Comment by simnandez** [comment]
I can't reproduce it
