### ISSUE TITLE
Feature Request: Show Badge on Product tab for Packaged Products

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5653]
# Feature Request

_Show badge on Product page (Package tab) when Product is package - just like on the Linked Files tab_
## Environment
- **Version**: [_3.9.3_]
## Use case

_When on a product, it would be easier to see that the displayed product is part of a package instead of having to go through the package tab every time.  This helps a lot when looking up and displaying a product._

**Comment by BebZ** [comment]
Yes exactly and same for a product being a package containing other products
