### ISSUE TITLE
Webservices SOAP : bug in updateOrder function

### ISSUE THREAD

**Issue by nonopoubelle** [Dolibarr/dolibarr#5659]
# Bug

UpdateOrder function return 500 Soap fault error

Line 927 of server_order.php 
    $result->generateDocument($order->modelpdf, $outputlangs);
should be :
    $object->generateDocument($order->modelpdf, $outputlangs);
## Environment

**Version**: 3.9.2

**Comment by eldy** [comment]
Seems fixed in 3.9.3
