### ISSUE TITLE
SQL query error

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#5663]
Unknown column 'd.fk_supplier_proposal' in 'field list'

URL htdocs/supplier_proposal/class/supplier_proposal.class.php
LINE 1192

**Comment by simnandez** [comment]
Dolibarr version?

**Comment by wankwaiwing** [comment]
Version: 5.0.0

**Comment by eldy** [comment]
Drop table llx_supplier_proposaldet and recreate it.
You probably install the module when it was not stable yet.
