### ISSUE TITLE
4.0.0-rc2 can't add stock

### ISSUE THREAD

**Issue by nim65s** [Dolibarr/dolibarr#5674]
# Bug

Hi,

Trying to add a stock raises this exception:

> ERROR: 42703: column 'p' of relation 'llx_product' does not exist LINE 1: UPDATE llx_product as p SET p.pmp = 22, stock=(SELECT SUM(p... ^ LOCATION: transformUpdateStmt, analyze.c:1997
## Environment
- **Version**: 4.0.0-rc2
- **OS**: Debian Jessie
- **Web server**: nginx 1.6.2
- **PHP**: 5.6.24
- **Database**: PostgreSQL 9.4.8
- **URL(s)**: /product/stock/product.php?id=3
## Expected and actual behavior

=> error raised instead of saving the stock
## Steps to reproduce the behavior

Correct the stock -> fill required fields -> save

**Comment by simnandez** [comment]
I have tested with last sources from GIT (4.0.0) and it works

**Comment by eldy** [comment]
@simnandez Did you test with postgresql ?

**Comment by eldy** [comment]
@simnandez Pb of syntax was specific to postgresql

**Comment by nim65s** [comment]
Thanks!
