### ISSUE TITLE
Repeat events in time (eg monthly), not shown in external calendar

### ISSUE THREAD

**Issue by grafity** [Dolibarr/dolibarr#5677]
# Bug

By adding an external calendar events with repetition over time, not shown in the calendar
## Environment
- **Version**: [_4.0.0_]
- **OS**: [_RedHat Linux 2.6.32-573.12.1.el6.x86_64_]
- **Web server**: [_Apache 2.2.15_]
- **PHP**: [_PHP 5.4.40_]
- **Database**: [_MySQL 5.5.50_]
- **URL(s)**: [_Affected URL(s)_]
## Expected and actual behavior

By adding an external calendar events with repetition over time (eg recurring monthly), not shown in the calendar.

However those without repetition, are usually displayed.
## Steps to reproduce the behavior

 add cexternal google calendar in
setup->modules->Agenda  Events/tasks and agenda management->setup->Import extenal calendars
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

Event with repeat:
https://k60.kn3.net/F/4/F/B/9/B/33C.jpg

Setup external calendar:
https://k61.kn3.net/1/5/C/D/D/D/37D.jpg

Show events in Agenda
https://k60.kn3.net/1/D/E/4/A/4/D1A.jpg
# Feature Request

[_Short description_]
## Use case

[_Verbose description_]
## Suggested implementation

[_Verbose description_]
## Suggested steps

[_List of tasks to achieve goal_]

**Comment by eldy** [comment]
This is due to the lack of repeating event support in Dolibarr.
This could be fixed once recurring events will be supported.

**Comment by eldy** [comment]
Still awaited...
