### ISSUE TITLE
Bug: in html_print_paypal_footer (Paypal Module (v 4.0.0))

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5698]
# Bug

Error in the Footer of https://.../public/paypal/newpayment.php
## Environment
- **Version**: 4.0.0

**The footprint in 4.0.0 looks like this (language: German):**

```
Companyname S.L.
Sociedad Limitada - Frankreich): Numéro d'identification fiscale\nCIF (Spanien: B12345678
Klassifikation der Wirtschaftszweige: 1234 - USt-IdNr.: ESB12345678
```

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
