### ISSUE TITLE
Feature Request: Add shipment line deleting and editing for draft shipments.

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#5711]
# Feature Request

Add shipment line deleting and editing for draft shipments.
## Use case

Change shipment when something is wrong with goods ready to deliver or when shipment doc contains wrong information.
## Suggested implementation

Adapt and cleanup shipment class with commonobjectline crud class. Add updateline and deleteline methods. Also cleanup error handling (not all errors are reported now ref #5710).
Update shipment card for deleting and updating lines.
## Suggested steps
1. adapt expedition.class
2. update shipment card, if someone volunteers to help for this should be welcome, I'm not so fast on creating dolibarr views.

**Comment by BebZ** [comment]
Maybe a good request / resolution for 2017 ?
Do you plan to have time to make the P.R. for the 6.0 ?
Cotact me by mail for final quotation of draft shipments and adding each product scanned to the draft, with the stoc movement done.
