### ISSUE TITLE
BUG: supplier proposal to order suplier no product line add

### ISSUE THREAD

**Issue by ummira** [Dolibarr/dolibarr#5721]
when a proposal supplier  is converted to order,  product lines are not added on order draft.
bug in developer version

**Comment by ummira** [comment]
problem occurs when price and subprice of `llx_supplier_proposaldet` table are NULL,
if are 0 (zero) lines are right added on supplier order

**Comment by ummira** [comment]
seems is missing an ajax call to identify price, 
check file objectline_create.tpl
and add 
$.post('<?php echo DOL_URL_ROOT; ?>/fourn/ajax/getSupplierPrices.php?bestpricefirst=1', { 'idprod': $(this).val() }, function(data) {
.....
this call is used only for some business object (see   $usemargins=1;), but is needed for supplier_proposal too

many things have todo...

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by aljawaid** [comment]
In v4.0.1 (I'm not sure if this is a separate issue) but once you add a product to supplier proposal there are no buttons to confirm/delete/cancel and there is no new blank line to add a product too.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
