### ISSUE TITLE
Feature Request: Add Product Picture in Supplier Order

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5728]
# Feature Request

There is a hidden option (which does not seem to work anyway on 4.0) **MAIN_GENERATE_INVOICES_WITH_PICTURE**
It would be more useful if the same was working and added to supplier orders a we take a copy of the order when we go to purchase stock and the picture of the product on the invoice might help with certain products.

**Comment by BebZ** [comment]
product supplier (product_fournisseur) 
doesn't handle product pictures, as picture would be supplier-specific in your example.., 
and as you can have 2 suppliers for the same product with different pictures supplied by the supplier
I think you have to work a little bit more, before seeing this implemented next to product_supplier_reference.

**Comment by aljawaid** [comment]
@BebZ Thanks for the reply.  I was referring to the main product picture.  But it's good to know.
