### ISSUE TITLE
Feature Request: Add More Product Volumes

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5729]
## Environment
- **Version**: 4.0
# Feature Request

Is there any way to add more types of volume for a product?  Currently there is no ML/CL/Litre

**Comment by BebZ** [comment]
Hey, here is not a forum, it is a real dev tool ;)
There is a solution, coded in the core, called product units, with a dictionnary...
search and find ;) and close the feat.req.

**Comment by aljawaid** [comment]
@BebZ Thanks for the reply.  I'm aware it is not a forum but the english forum is hardly active and I was merely suggesting a feature which when I searched ( in the dictionary) it does not suit the purpose.

At the moment, I can set a product unit as **set** or **pack** in the dictionary. If I add Millilitres there is no way for me to set it as **400 ML** for example.  I can set a product as 4oz (in volume field) but not 4ML.

That was my point basically to see if there was a way to increase the values in the volume field or if the option could be added in a future version.

**Comment by yehanny** [comment]
@aljawaid you can try this module, it's a great solution for new PDF formats and also includes the feature your searching for where you can add all types of "Units" per product or services like: m, cm, inch, lt, ml, oz and so on. Check: https://www.dolistore.com/en/modules/620-Ultimatepdf-3-9.html

**Comment by BebZ** [comment]
/admin/dict.php
Thats why I said its not a forumoption existe in 3.8.4. Unless you dont know every option of dolibarr, like product units... please dont post here.

**Comment by eldy** [comment]
Into dictionnary, by default liter is same than dm3.
It is than unit, so label of unit is "dm3 (liter)" but you can rename it into liter.
