### ISSUE TITLE
Feature Request: Create Simple Product from Supplier Order/Invoice

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5730]
## Environment
- **Version**: 4.0
# Feature Request Use Case

Telephone supplier, discuss new product and obtain cost price. Add product onto order/invoice as static free entry text with trigger button to automatically convert into live-product. Dolibarr then converts product static text to new product (minimum data with only product code, label, cost price). Once business order is complete (before dolibarr stock dispatching) the user could easily amend newly auto-created product selling price and product information at later stage.

For business use, this step would be very handy I think.

**Comment by BebZ** [comment]
I think if it is not ready yet, it has to populate 3 tables : llx_product, and llx_product_fournisseur and product_fournisseur_price... all linked with a fk_product and then fk_product_fourn for price...
if fk_product is not "created", not possible to make a link between the other table.. 
True ? 

I have made a quick draw...

![creation rapide produit avec fourn](https://cloud.githubusercontent.com/assets/3694135/18411258/6fbd7b7e-7774-11e6-8816-daf131c3c74a.png)

**Comment by aljawaid** [comment]
@BebZ Thanks for the reply. Yes I think it makes sense to have that as popup but I was thinking all that could be auto-populated from the core required information in a popup.

I'm not a developer so I am just suggesting a business use case which may work for us users. :+1:
