### ISSUE TITLE
[Feature Request] Add RNA id number for French associations

### ISSUE THREAD

**Issue by daamien** [Dolibarr/dolibarr#5732]
French associations  are now identified by a unique number called RNA :
https://www.service-public.fr/associations/vosdroits/F1926

The  page /admin/company.php should have a RNA field too when the company is a French association.

**Comment by hregis** [comment]
@daamien, may need to add the ability to add custom fields, because a company can have numbers diverse and varied according to its activity ?

**Comment by popindavibe** [comment]
This was never implemented, though it would still be quite valuable for any non-profit using Dolibarr as their CRM.

**Comment by HLFH** [comment]
This is being solved here: https://github.com/Dolibarr/dolibarr/issues/29516.
