### ISSUE TITLE
Bug: Update 3.9.3 to 4.0.0

### ISSUE THREAD

**Issue by debastiani** [Dolibarr/dolibarr#5737]
# Environment
- **Version**: 3.9.3
- **OS**: Linux
- **Web server**: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.31
- **URL**: /index.php?mainmenu=home
# Report

I un an update via Cpanel fron version 3.9.3 to 4.0.0 but it dont work:
This is the screen that dollibar upgrade system retun:

Estrutura de migração de dados
Conexão ao servidor : localhost    OK
Login à Base de Dados : report_doli984 OK
Versão do Servidor da Base de Dados    5.6.31
Por favor aguarde....
Migrar script selecionado   3.9.0-4.0.0.sql

**Comment by eldy** [comment]
I'am afraid we will need the install.log and dolibarr.log to investigate more

**Comment by debastiani** [comment]
Hello eldy

Can i share this file here?
Is it safe?

Thank you

**Comment by eldy** [comment]
If you prefer, you can send them to me at eldy@users.sourceforge.net

**Comment by rdoursenaud** [comment]
Any update?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
