### ISSUE TITLE
PHP compatilibility issues

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5744]
I've been toying with the [PHPCompatibility](https://github.com/wimg/PHPCompatibility) sniffer for PHPCS and looking into automating it in our CI process ([PR incoming](https://github.com/GPCsolutions/dolibarr/tree/4.0-php-compatibility)).

Doing that revealed a bunch of incompatibilities in the current codebase with various versions of PHP. (Test checks 5.3 to 7.0 versions).
Most against our very own recommended 5.3 version! (In the [README.md](https://github.com/Dolibarr/dolibarr/blob/develop/README.md) and the [wiki](https://wiki.dolibarr.org/index.php/Prerequisite)).

There is so many that I don't feel like opening an issue for each.
I believe these need to be addressed ASAP.

Some are related to #5607 and #5609. 

If you want to replicate the test procedure, here's how to do it:
- ~~First make sure you're running PHP 7 so all the tests can run.~~ (PHPCompatibility is designed to run on any PHP5+).
- Install the required dependencies:

```
composer require --dev wimg/php-compatibility:^7
```

Workaround a [bug](https://github.com/wimg/PHPCompatibility/issues/102) in PHPCompatibility with composer:

```
rm -fr "htdocs/includes/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility"
cp -a "htdocs/includes/wimg/php-compatibility" "htdocs/includes/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility"
```

Run the check:

```
./htdocs/includes/bin/phpcs -n -p -d memory_limit=-1 -d max_execution_time=-1 --standard=PHPCompatibility --runtime-set testVersion 5.3-7.0 --ignore=custom/\*,includes/\* .
```

So here's the full report of a scan against current 4.0 branch:
[check.txt](https://github.com/Dolibarr/dolibarr/files/470045/check.txt)

**Comment by rdoursenaud** [comment]
Upon closer analysis, the PHP 5.3 messages are false positives.
Reported upstream: wimg/PHPCompatibility#226

**Comment by eldy** [comment]
Currently i don't see any reason to remove PHP 5.3 compatibility.
There is still a lot of server that need it and application is fully compatible with 5.3. And keeping this compatibility does not need an extra charge for developer if coding is done cleverly.
