### ISSUE TITLE
Bug: Longueur maximale par défaut des listes 25 

### ISSUE THREAD

**Issue by ab-distrib** [Dolibarr/dolibarr#5762]
# Environment
- **Version**: 3.9.1
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/admin/ihm.php?mainmenu=home
# Report

Longueur maximale par défaut des listes 25 et la liste reste toujours à 5 au lieu de 25

**Comment by eldy** [comment]
Which screen does not respect rule. 
Also can you check the user doesn't have also a number defined (used in priority before global setup)

**Comment by ab-distrib** [comment]
Bonjour Eldy,
A quel endroit puis je voir un paramètre prioritaire?
Cordialement

**Comment by ab-distrib** [comment]
Bonjour Voici une capture d'écran du bug toujours pas résolu.
Personne n'a une idée?
Merci d'avance et bonne année 2017
![erreur liste](https://cloud.githubusercontent.com/assets/22303438/21944106/a57d92f4-d9d4-11e6-98ad-e6329b012501.png)

**Comment by BebZ** [comment]
regardé dans la config d'un utilisateur ?
regardé avec un autre theme ?


2017-01-13 21:10 GMT+01:00 ab-distrib <notifications@github.com>:

**Comment by ab-distrib** [comment]
Super, enfin une réponse qui fonctionne.

Merci à toi

 

De : BebZ [mailto:notifications@github.com] 
Envoyé : samedi 14 janvier 2017 17:12
À : Dolibarr/dolibarr
Cc : ab-distrib; Author
Objet : Re: [Dolibarr/dolibarr] Bug: Longueur maximale par défaut des listes 25 (#5762)

 

regardé dans la config d'un utilisateur ?
regardé avec un autre theme ?


2017-01-13 21:10 GMT+01:00 ab-distrib <notifications@github.com>:

**Comment by ab-distrib** [comment]
Maintenant, comment ferme-t-on le topic ?

Cordialement

 

De : BebZ [mailto:notifications@github.com] 
Envoyé : samedi 14 janvier 2017 17:12
À : Dolibarr/dolibarr
Cc : ab-distrib; Author
Objet : Re: [Dolibarr/dolibarr] Bug: Longueur maximale par défaut des listes 25 (#5762)

 

regardé dans la config d'un utilisateur ?
regardé avec un autre theme ?


2017-01-13 21:10 GMT+01:00 ab-distrib <notifications@github.com>:

**Comment by bgenere** [comment]
Pour fermer le topic (issue), il faut utiliser le bouton close.

That's it. ;-)
