### ISSUE TITLE
Bug: Unable to add to Proposal from Product page

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#5767]
# Bug

can not add a product from its page in an invoice or a quote
## Environment
- **Version**: 5.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.24-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.52-0+deb8u1
- **URL**: /htdocs/product/card.php?id=2475

**Comment by eldy** [comment]
The form to add a product to a draft proposal/order/invoice from the product card is hidden by default.
It was not commonly used and usage generates some problems (cost price for margin calculation not entered, vat setting).  
Set constant PRODUCT_ADD_FORM_ADD_TO to retrieve it.

**Comment by ozit** [comment]
Thanks, it works
