### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by walix** [Dolibarr/dolibarr#5769]
# Bug

When I want to generate a recurring invoice get the following error

Error ERROR: 23502: null value in column 'maxrun' violates not-null constraint DETAIL: Failing row contains (2, 2016-09-20 17:05:29.176708, 2016-09-20 16:58:07, method, RecurringInvoices, null, compta/facture/class/facture-rec.class.php, FactureRec, createRecurringInvoices, null, null, facture, 0, 2016-09-20 16:05:29, null, 2016-09-20 16:58:07, null, null, , , 86400, 1, null, 1, 0, 1, , null, 1, null, Generate recurring invoices, null, 1). SCHEMA NAME: public TABLE NAME: llx_cronjob COLUMN NAME: maxrun LOCATION: ExecConstraints, execMain.c:1636
Error ERROR: 23502: null value in column 'maxrun' violates not-null constraint DETAIL: Failing row contains (2, 2016-09-20 17:05:29.176708, 2016-09-20 16:58:07, method, RecurringInvoices, null, compta/facture/class/facture-rec.class.php, FactureRec, createRecurringInvoices, null, null, facture, 0, 2016-09-20 16:05:29, null, 2016-09-20 16:58:07, null, null, , , 86400, 1, null, 1, 0, 1, , null, 1, null, Generate recurring invoices, null, 1). SCHEMA NAME: public TABLE NAME: llx_cronjob COLUMN NAME: maxrun LOCATION: ExecConstraints, execMain.c:1636, Error ERROR: 23502: null value in column 'maxrun' violates not-null constraint DETAIL: Failing row contains (2, 2016-09-20 17:05:29.176708, 2016-09-20 16:58:07, method, RecurringInvoices, null, compta/facture/class/facture-rec.class.php, FactureRec, createRecurringInvoices, null, null, facture, 0, 2016-09-20 16:05:29, null, 2016-09-20 16:58:07, null, null, , , 86400, 1, null, 1, 0, 1, , null, 1, null, Generate recurring invoices, null, 1). SCHEMA NAME: public TABLE NAME: llx_cronjob COLUMN NAME: maxrun LOCATION: ExecConstraints, execMain.c:1636, Error ERROR: 23502: null value in column 'maxrun' violates not-null constraint DETAIL: Failing row contains (2, 2016-09-20 17:05:29.194988, 2016-09-20 16:58:07, method, RecurringInvoices, null, compta/facture/class/facture-rec.class.php, FactureRec, createRecurringInvoices, null, null, facture, 0, 2016-09-20 16:05:29, 2016-09-21 16:58:07, 2016-09-20 16:58:07, 
only error in BD PostgreSQL in MySQL not
## Environment
- **Version**: [Dolibar 4.0.0]
- **OS**: [*Debian 8 *]
- **Web server**: [_NGINX_]
- **PHP**: [_PHP version_]
- **Database**: [_PostgreSQL_]

Thanks

**Comment by eldy** [comment]
Waiting 4.0.1. I see it is fixed for future 4.0.1

**Comment by rdoursenaud** [comment]
4.0.1 released a while ago. Closing.

Please comment below if this didn't fix your issue so we can reopen it.
