### ISSUE TITLE
development and experimental modules are not shown with PHP 7.0

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5774]
# Bug

When running PHP 7.0, modules with version `development` or `experimental` are not shown in the `admin/modules.php` page even though `MAIN_FEATURES_LEVEL` is set to `2`.

Setting any other version string shows the modules.

Running PHP 5.x also displays the modules.
## Environment
- **Version**: 4.0.x
- **PHP**: 7.0.x
- **URL(s)**: admin/modules.php

**Comment by rdoursenaud** [comment]
Investigating. If anyone has a clue, please chime in!

**Comment by rdoursenaud** [comment]
OK, I think I figured it out.

I had two `MAIN_FEATURES_LEVEL` constants set respectively to `2` and `0`.
This resolved `$conf->global->MAIN_FEATURES_LEVEL` to `1` under PHP 7.0 and `2` under PHP 5.6. O_o
How's that even possible?
I smell something fishy here…

**Comment by rdoursenaud** [comment]
Oh my let's report a feature request to prevent duplicate Dolibarr constants.

**Comment by BebZ** [comment]
Did you try with constant -1 and 0 ?
Migrating on php7 duplicates the constants ?

**Comment by rdoursenaud** [comment]
@BebZ No, it doesn't. I just happened to have `MAIN_FEATURES_LEVEL` already declared twice.
One on entity `0` (the default install-time one) and one on entity `1` (I must have created sometime for whatever reason).
Then, there is a difference in processing between PHP 5.x and PHP 7:
Running PHP 5.x, the global `$conf->global->MAIN_FEATURES_LEVEL` is set the "master" entity's constant value.
Running PHP 7, its set to the "local" entity's value.
Hence the different behavior.

**Comment by hregis** [comment]
@BebZ @rdoursenaud 
I do not see why the php version will change the operation of a constant !! it would not rather a coincidence?

**Comment by rdoursenaud** [comment]
@hregis This should not be the case but is fairly easy to reproduce.
