### ISSUE TITLE
Prevent setting a Dolibarr constant multiple times

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#5775]
# Feature Request

Dolibarr constants should be unique for each entities.
## Use case

To prevent unexpected behaviors like #5774, I believe that Dolibarr constants should be unique.
## Suggested implementation

Since we can't enforce a `UNIQUE` field because of entities management (Multi Company support), the task should be entrusted to `dolibarr_set_const()` declared in `core/lib/admin.lib.php`.
Errors should be resurfaced at `admin/const.php`.

**Comment by hregis** [comment]
@rdoursenaud it's not possible to have the multiple times the same constant in an entity with this key : 
ALTER TABLE llx_const ADD UNIQUE INDEX uk_const (name, entity);

**Comment by hregis** [comment]
you had to create a "MAIN_FEATURES_LEVEL" with a different entity value of 0. can be-it would add a check to not duplicate constants that have value 0 in the field entity?

**Comment by rdoursenaud** [comment]
@hregis Thanks for your insights!

Yes, that's exactly what happened. One on entity `0` and one on entity `1`.

This raises the following questions:
What should be the priority when this happens? Local entity seems reasonable to me. But this is clearly not enforced in the code.
Shouldn't we have a list of core constants that should only appear on entity `0`?

**Comment by hregis** [comment]
normally global constants that are unique for all entities must have a value of 0 in the field entity...(all globals constants are in /install/mysql/data/llc_const.sql)... then if by mistake we find this constant with a different entity value, it is this constant that will take over. So avoid that one can create duplicate a constant having an entity value to 0
