### ISSUE TITLE
Bug: Field 'File' is required 

### ISSUE THREAD

**Issue by AbbyBE** [Dolibarr/dolibarr#5779]
# Bug
## Environment
- **Version**: 4.0.0
- **OS**: Linux
- **Web server**: Apache/2.4.7 (Ubuntu)
- **PHP**: apache2handler 5.5.9-1ubuntu4.19
- **Database**: MySQL or MariaDB 5.5.52-0ubuntu0.14.04.1
- **URL**: /dolibarr/ecm/index.php
## Report

When trying to add or upload a file I always get the error "Field 'File' is required" all the time in 
Dolibarr 4.0 . Already checked permissions on Folder level for de Document folder.
Even gave it full access temporarily but still the same above error keeps on poping up.

No idea were to look any more, check all kind of setting in dolibarr.

Please check if there is a solution for this issue.
![field file is required](https://cloud.githubusercontent.com/assets/22395372/18787003/1a0ada78-81a1-11e6-815f-cc40d6d8c4d5.png)

**Comment by eldy** [comment]
What is the size of the file you try to upload ?

**Comment by AbbyBE** [comment]
Hi, the size is 226 KB, so that should not be te problem.

But I gave full acces to the document folder (777) and now the error is
gone, but the file uploaded ('send to) is not save on tha dolibarr
application.
=> any ideas here ?

Thanks again.
Kind regards
Ab

---

Abdallah Kerkab
Akkerstraat 26
2460 Kasterlee
GSM +32 491 723 711

2016-10-01 14:03 GMT+02:00 Laurent Destailleur notifications@github.com:

**Comment by eldy** [comment]
Can you try to upgrade to 4.0.1 ?
