### ISSUE TITLE
Stock Alert limit.

### ISSUE THREAD

**Issue by nach41710** [Dolibarr/dolibarr#5783]
# Bug

When I try to modify the stock alert limit, I put the number, click modify but the number is not entered in the field. I cant enter any number in this field.
## Environment
- **Version**: 3.9.3
## Steps to reproduce the behavior

[_Just try to enter a stock alert in version 3.9.3_]

**Comment by nach41710** [comment]
I review 5f4154: FIX : update limit stock on ....
This solve the issue.
will it be included in version 3.9.X?
Thanks.

**Comment by aljawaid** [comment]
@nach41710 it was definitely fixed from 4.0 as I had the same issue in 3.9.x

**Comment by eldy** [comment]
Yes patch was included for future 3.9.4
