### ISSUE TITLE
Bug: Recurrent events created in Google calendar are not displayed in Dolibarr Calendar.

### ISSUE THREAD

**Issue by johnotoole68** [Dolibarr/dolibarr#5787]
# Bug
## Environment
- **Version**: 4.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.35
- **Database**: MySQL or MariaDB 10.0.20-MariaDB
- **URL**: /htdocs/index.php?mainmenu=home&leftmenu=
## Report

Modulo: Agenda.
Description of the issue: Recurrent events created in Google calendar are not displayed in Dolibarr Calendar.

Create a recurrent event (an event with multiple repetitions) in Google Calendar, those events are not displayed in Dolibarr Agenda Module. However, if you create a single event in Google Calendar, it will be dispalyed properly in Dolibarr Agenda. 

It looks like the interfase does not support syncrhonization of events with multiple repetitions.

I do not know if this is working as designed, or it is actually an issue.

Regards,
Juan O'Toole

**Comment by eldy** [comment]
Yes, recurring events are not yet supported into Dolibarr

**Comment by johnotoole68** [comment]
Hello, Thank you for reaching out! I appreciate your clarification.

In this case, next year I will try to develop this functionality. I will do my best.

Thanks!
John
