### ISSUE TITLE
Feature Request - Show lot / serial on shipment card

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#5797]
On shipment card when we have turn on lot / serial number for products - it will be nice to show directly this number not only when hover on barcode icone. It's hard to copy this number in this way. 
It will be also usefull that could use this number when generating ODT document.

**Comment by BebZ** [comment]
Hum, there is display on pdfs, but on shipment cards ODT i think you will have to work on it by yourself, or just "call" the right field on your ODT ;)
you didnt find anything about lot fields to write on ODT ?

**Comment by pat15** [comment]
I can search how to modify module but always when i upgrade dolibarr the problem come back, and must do it again :) Yes on PDF it's display in nice way. But you agree with me that in module shipments inconvenient to copy serial / lot if it's only appears when you hover the mouse a barcode ico. Better way that will be show this number - You can copy it :)

About ODT i don't find how "call" this field - maybe i must write my own substitution function?

**Comment by fappels** [comment]
For the 'hover' part I ref your request to mine #5711
