### ISSUE TITLE
Feature Request: Generate all the pdf's invoices when merging if not yet generated

### ISSUE THREAD

**Issue by Back-Sephiroth** [Dolibarr/dolibarr#5798]
Hello, 

I have modified the template pdf for my use, and i would like to update all the invoices generated in pdf format.

How can i do to generate all the pdf instead of generate one by one ?

Thank's for your help

**Comment by sbschumacher** [comment]
Just for info: Once you have send invoices to your customer, you should not edit this documents (see for example the latest EU directive). Electronic invoices must be kept unchangeable.

**Comment by BebZ** [comment]
Did you check documentation ? I think there is a way to re-generate all invoices...
Especially useful for displaying payments and a "STAMP"  PAYED ;)
is it allowed by EU directive to "STAMP" invoices with references of payments ?

**Comment by Back-Sephiroth** [comment]
Thanks for your help,

i know that invoices must be kept unchangeable, but it concern only invoices that never be sent.

I checked the documentation, and i haven't found anything about that.

**Comment by eldy** [comment]
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.
