### ISSUE TITLE
Feature Request: Complementary attributes of products on ODT

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#5816]
# Bug

We have additional field for example on product (prod_customer_name). I want generate ODT where i can use this value (instead product_name it should generate prod_customer_name) - but it's not work.
## Environment
- **Version**: 4.0.0

**Comment by eldy** [comment]
Currently only additional attributes for the invoice, proposal, order can be reused into ODT.
Not the one for products, so i turned the ticket as a feature request.

**Comment by BebZ** [comment]
Maybe could be more available with @marcosgdf development ? 
https://github.com/Dolibarr/dolibarr/pull/5533

**Comment by pat15** [comment]
Something's going on? :)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
I think this has been implemented in last Dolibarr versions.
