### ISSUE TITLE
Feature Request: Allow Generic E-mail Sender NOT User

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5830]
## Environment
- **Version**: 4.0.1
## Expected and actual behavior

When sending an e-mail to customer/supplier from order/invoice page, Dolibarr will send from the user credentials i.e. user display name + user e-mail.
## Suggested implementation

Allow drop down option to select sending from logged-in user (user credentials) or from generic system credentials (main business e-mail).
## Example

User: John
User Display Name: John Doe
User E-mail: john@mycompany.com
System Generic Display Name: My Company
System Generic E-mail: dolibarrsystem@mycompany.com

If we have the option to choose the logged in user or the business general e-mail address/name it would be very helpful.

**Comment by olsesacl** [comment]
are these changes correct?
#5855 
![select_email](https://cloud.githubusercontent.com/assets/6471493/19250206/6c0a209a-8f39-11e6-820c-9567a4e994c3.jpg)

**Comment by aljawaid** [comment]
@olsesacl Thanks for this feature.  This was exactly what I was hoping for!

Would it work on all customer/supplier invoices and orders where we have the e-mail options?
Also, can it be defaulted to the company as the sender and not the user?

I can't wait for @eldy to approve it 💯

**Comment by olsesacl** [comment]
Add config email to be used by default (User / Company)
![default](https://cloud.githubusercontent.com/assets/6471493/19252467/48ea9282-8f45-11e6-8c4c-705be2056b9c.jpg)

**Comment by aljawaid** [comment]
Excellent! Thank you!

Just need the final approval now... :)

**Comment by aljawaid** [comment]
Thanks for merging this into the core.
