### ISSUE TITLE
SMTPS socket library with STARTTLS (php7)

### ISSUE THREAD

**Issue by Yotouille** [Dolibarr/dolibarr#5832]
Hi there,
# Bug

We've just setup our new environment with Ubuntu 16.04 and PHP7, but the function to test 'mail sending' seems broken. STARTTLS support for mail server was _the_ huge enhancement in v4 we were waiting for, to get rid of our local Postfix relays and lighten our environment. Beside this, STARTTLS support in v4 is working like a charm onto our previous environment (Ubuntu 14.04 + PHP5).

This is the big red error message (top of page) we got when trying to send a mail (TRUNCATED, for it's too long):
**line1**: `Échec de l'envoi de l'email (émetteur=noreply-dolibarr@ourdomain.com , destinataire=me@ourdomain.com)`
**line2**:
`Error [132]: STARTTLS connection failed.`
`Error [121]: Couldn't get mail server response codes` (repeated 400 times)
`Error [120]: Ran into problems sending Mail. Response:` (note the empty response)
(there is no line feed in **line2**, only here for readability)
## Environment
- **Version**: 4.0.1
- **OS**: Ubuntu 16.04
- **Web server**: nginx/1.10.0
- **PHP**: 7
- **Database**: MariaDB (latest)
- **URL(s)**: ./dolibarr/htdocs/admin/mails.php?action=test&mode=init
## Steps to reproduce the behavior

Migrate Dolibarr v4 from Ubuntu 14.04 to 16.04
## What else ?

I've tried to install every packages I could think of, concerning encryption, certificates, etc.., with no luck.

I can connect from Dolibarr server to our Mail relay using `openssl` command without issue. (It's seems cleaner on Ubuntu 16.04 with a `Verify return code: 0 (ok)` for StartTLS Handshake. With Ubuntu 14.04 it's: `Verify return code: 20 (unable to get local issuer certificate)`, but it's working)

Something has moved, but I can't find a clue...

BTW, Thanks for this great work.

La bise,
Y.

**Comment by eldy** [comment]
PHP 5.6 is more restrictive for STARTTLS access.

Can you try to use 
"tls://yourhost"
instead of
"yourhost"
into page of emails setup.

And make a test sending (no need to make a test server connectivity with this, it will fail)

Check also that the host name is same than the CN name in the certificate or mail server

**Comment by Yotouille** [comment]
Ho thanks !

This was exactly my problem: different CN name in cert and hostname configured in mail !
Cert CN name is `mydomain.com`
Relay hostname is `mydomain.net`,
Tweaking `/etc/hosts` on dolibarr box and using `.com` hostname in mail config, I am now able to send mail from dolibarr !

BTW, trying `tls://` did not help:
`Error [99]: tls://myrelay.mydomain.net is either offline or is an invalid host name.`
(same for .com)

I will check about this CN/Hostname diff, a chance I'd never had issue about it until now !

Thanks again !
Mille merci !
Y.
