### ISSUE TITLE
MySQL Dump (mysqldump) not working

### ISSUE THREAD

**Issue by virtilia** [Dolibarr/dolibarr#5840]
# Bug

[_MySQL Dump (mysqldump) not working_]
## Environment
- **Version**: [4.0.0, 4.0.1]
- **OS**: [CentOS Linux release 7.2.1511]
- **Web server**: [ Apache/2.4.6 (CentOS)]
- **PHP**: [PHP 5.3.29]
- **Database**: [5.5.50-MariaDB]
## Expected and actual behavior

[Expected: Generate a MySQL dump using a locally present mysqldump app using /Applications/MAMP/Library/bin/mysqldump on a Mac running OS X 10.11.6.

Actual behavior: Error message displayed: "sh: /Applications/MAMP/Library/bin/mysqldump: No such file or directory". Instead of compressed dump file an error message file with a warning sign in front of it is generated containing the same error message as above.]
## Steps to reproduce the behavior

[Choose "MySQL Dump (mysqldump)" as export method. Choose either of the available compression methods (None, GZIP or BZIP2). Click "generate Backup" button.
Replacing the path /Applications/MAMP/Library/bin/mysqldump with different paths to mysqldump apps as part of other program implementations like MySQLWorkbench leads to identical result.]
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[
![bildschirmfoto](https://cloud.githubusercontent.com/assets/10794798/19121650/83f466b8-8b27-11e6-8460-4ea99fcedf93.jpg)
]

**Comment by Yotouille** [comment]
Hi,

I don't think you can do that, `mysqldump` binary must be located on your dolibarr server and will be run from there.

**Comment by virtilia** [comment]
Alas, that solved it: /bin/mysqldump has to be within the server environment.

Thanks!
