### ISSUE TITLE
Bug: unable to create an Invoice model

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#5857]
# Bug

When trying to create an invoice model, I have a blank page, without error. On the "Report", there is the error in apache log
## Environment
- **Version**: 5.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.24-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.52-0+deb8u1
- **URL**: /htdocs/compta/facture/fiche-rec.php?facid=3&action=create
## Report

 tail /var/log/apache2/error.log  
[Tue Oct 11 01:37:44.603775 2016] [:error] [pid 27439] [client xx.yy.zz.ww:37996] PHP Fatal error:  Class 'FormProjets' not found in /var/www/html/htdocs/compta/facture/fiche-rec.php on line 887, referer: http://toto.com/htdocs/compta/facture.php?facid=3&action=confirm_modif&confirm=yes

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version.
If not, can you close ticket ?

**Comment by ozit** [comment]
with today dolibarr source code (develop branch), it does not work
Same error in apach2 log

## Environment
- **Version**: 5.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.27-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.52-0+deb8u1
- **URL**: /htdocs/compta/facture/fiche-rec.php?facid=9&action=create

**Comment by ozit** [comment]
Here is the same error on last git sources.

[Fri Nov 25 18:57:48.933048 2016] [:error] [pid 24028] [client client xx.yy.zz.ww:62350] PHP Fatal error:  Class 'FormProjets' not found in /var/www/html/htdocs/compta/facture/fiche-rec.php on line 888, referer: http://toto.com/htdocs/compta/facture.php?facid=40

I'm going to try a new installation on a virtual server and will write here if it work

**Comment by ozit** [comment]
I've done a new installation from scratch (on a new web server)
I activate only 2 modules : "Tiers" and Invoices
And I have a blank page when trying to convert a draft invoice in template

**Comment by PMickael** [comment]
Hello,

You need to have module project enable https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/compta/facture/fiche-rec.php#L36
```php
if (! empty($conf->projet->enabled)) {
    require_once DOL_DOCUMENT_ROOT . '/projet/class/project.class.php';
    require_once DOL_DOCUMENT_ROOT . '/core/class/html.formprojet.class.php';
}
```

**Comment by ozit** [comment]
Hello, 

You're right @PMickael , we have to have module project enable.
I suggest to hide "Create an invoice Model" button when this module is not enabled.
Thanks to all
