### ISSUE TITLE
Consider commas as a decimal digit in the search

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5860]
# Bug

It is not possible to search for decimal amounts when using "," (comma) instead of "." (dot) as decimal digit in many lists. So for example in the list of outstanding invoices.
## Environment
- **Version**: 4.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.26
- **Database**: MySQL 5.1.73-log
- **URL(s)**: https://[...]/**compta/facture/impayees.php**?leftmenu=customers_bills
## Expected and actual behavior

If "," (comma) is set as decimal digit in the settings of the current user/company, it should be adopted to the filter rules.
## Steps to reproduce the behavior

Create an invoice with an odd amount (for example 100,41 EUR).
Search for the amount "100**,**41" in the table of /facture/impayees.php. The result will be "empty". Search again for the amount "100**.**41" and you will find your invoice.

**Comment by eldy** [comment]
This page is no more a page of version 4.0.
Are you sure of url ?

**Comment by sbschumacher** [comment]
Sorry @eldy.
You are right. I mixed up the versions.
