### ISSUE TITLE
Feature Request: Add link format for extrafields

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#5869]
# Feature Request

_Add link format for extrafields_

Open the Link:
1 follow link in a Windows Tab or new Windows

Field Config:
2 Only Link Field or 
3 Linkfield and Description show Description or Link in Dollibar, or truncut Link
## Use case

_https://drive.google.com/open?id=0B8GiSKdtgDuMeGpKb0FPdjZGOUU_

**Comment by atm-maxime** [comment]
I think this has been implemented with the extrafield type "URL". Reopen if needed
