### ISSUE TITLE
Bug: unable to send mail smtp.office365.com sur le port 587 - Error 0 -

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#5877]
# Bug

On last git sources, it is not possible to send email using o365 smtp server (it works when I test last month)
## Environment
- **Version**: 5.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.26-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.52-0+deb8u1
- **URL**: /htdocs/admin/mails.php
## Report

Here is the official documentation : https://support.office.com/en-us/article/POP-and-IMAP-settings-for-Outlook-Office-365-for-business-7fc677eb-2491-4cbc-8153-8e7113525f6c

Here is my configuration on Dolibarr 
SMTP/SMTPS socket library
smtp.office365.com
587
myuser@mydomaine.com
<mypassword>
TLS/SSL : Yes
TTS/STARTTLS : NO
sender : myuser@mydomaine.com
reply : myuser@mydomaine.com
cci : myuser@mydomaine.com

When I clic on test server
Server not disponible at the adress smtp.office365.com on  port 587 - Error 0 - 

When I try to send an email
Échec de l'envoi de l'email[error in sending mail](from=myuser@mydomaine.com , to=myuser@mydomaine.com)
Error [0]: Failed to connect with fsockopen host=ssl://smtp.office365.com port=587

there is nothing in error.log or access.log

The port 587 is not blocked

---

/opt/dolibarr> nmap -PN -p 587 -sN smtp.office365.com                                                                                  [develop ✔]

Starting Nmap 6.47 ( http://nmap.org ) at 2016-10-14 20:13 CEST
Nmap scan report for smtp.office365.com (132.245.49.242)
Host is up (0.0080s latency).
Other addresses for smtp.office365.com (not scanned): 132.245.50.66 132.245.61.210 40.96.19.210 40.101.5.114 40.101.7.178 40.101.16.178 40.101.16.194 40.101.28.194 132.245.34.242
PORT    STATE  SERVICE
587/tcp closed submission

Nmap done: 1 IP address (1 host up) scanned in 1.13 seconds

**Comment by philippe-opendsi** [comment]
Hi

> TTS/STARTTLS : NO

I think you should set YES to STARTTLS. For me port 587 is the default port for STARTTLS.

**Comment by ozit** [comment]
Hi
Look [here](https://support.office.com/en-us/article/POP-and-IMAP-settings-for-Outlook-Office-365-for-business-7fc677eb-2491-4cbc-8153-8e7113525f6c), it's the official documentation, for Office 365, we have to use TTL(SSL).
It can't work with STARTTLS.
I tried antoher SMTP server, with TTL(SSL) and it works (ssl0.ovh.net on port 465).
Is there something special with the certificat of smtp.office365.com ?

**Comment by philippe-opendsi** [comment]
Sorry, but did you try STARTTLS and Office365 ? I'me quite sure to have done it successfully with a customer in the past. But I don't have any Office365 to test it again.

**Comment by ghost** [comment]
With Dolibarr 4.0, you can setup SwiftMailer, in this case you should be able to use SSL

**Comment by eldy** [comment]
In most cases if you use 
TLS/SSL, port is 465
or
STARTTTLS and ports is 587

Here, you say microsoft need TLS but on port 587 ? This looks strange.
Can you try STARTTLS or if TLS/SSL, try port 465.

**Comment by ozit** [comment]
Hi all, 
I've tried TLS/SSL, port is 465 ==> Server not available on smtp.office365.com on port 465 - Error 110 - Connection timed out
I've tried TTS/STARTTLS, port is 465 ==> Server not available on smtp.office365.com on port 465 - Error 110 - Connection timed out
I've tried TLS/SSL, port is 587 ==> Server not available on smtp.office365.com on port 465 - Error 110 - Connection timed out
When I test TTS/STARTTLS, port is 587 (the test pass : Server is available on smtp.office365.com on port 587)
When I try to send an email : not OK
Here is the error message
Failed to send the email (from=<my email>, to=<my email>)
Error [120]: Ran into problems sending Mail. Response: 501 5.5.4 Invalid domain name Error [126]: 'tls: //smtp.office365.com' does not mount authenticated connections.

**Comment by ozit** [comment]
@atm-florian  I tried the Swiftmailer solution : it works !

May be the problem is on SMTP/SMTPS socket library ?

Did I have to close the issue or let it open to solve the SMTP/SMTPS socket library ?
