### ISSUE TITLE
* Problem installing

### ISSUE THREAD

**Issue by leonakos** [Dolibarr/dolibarr#5880]
Guys sorry for silly question but i have to ask.

I have a clean install of Dolibarr V4.0 installes and working.

I would like to add the modules that are listed in the post or make a clean install with the provided version.

Can someone instruct me how to make an install from the files that are provided here? or install only the modules?

Thanlks in advance

only keep the "Bug" or "Feature Request" section
replace the bracket enclosed texts with meaningful informations
remove any unused sub-section
Bug

[Short description]

Environment

Version: [4)]
OS: [Windows 10]

**Comment by eldy** [comment]
This issue does not look to be a bug or a feature request, so I close it.
For questions, you can try on forums.
This issue does not look to be a Bug neither a Feature request, so I close it.
For questions, you can try on forums.
