### ISSUE TITLE
Bug: Warning: is_dir(): open_basedir restriction in effect. File(/169) is not within the allowed path

### ISSUE THREAD

**Issue by odm69** [Dolibarr/dolibarr#5900]
# Bug
## Environment
- **Version**: 4.0.1
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/projet/element.php?id=31
## Report

Bonjour,
dans la page projet sous l'onglet évènement, il y a l'avertissement suivant:
Warning: is_dir(): open_basedir restriction in effect. File(/169) is not within the allowed path(s): **(c:/dolibarr)** in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 98
est-il possible qu'il y ait un bug dans le script ?

**Comment by eldy** [comment]
I think this is fixed for 4.0.2

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by odm69** [comment]
Hello,

Thank you for your reply. I am using the version 4.0.1. I will install the update…

Thank you for your support.

Olivier

De : Laurent Destailleur [mailto:notifications@github.com] 
Envoyé : jeudi 3 novembre 2016 10:30
À : Dolibarr/dolibarr dolibarr@noreply.github.com
Cc : odm69 odemagny@yahoo.fr; Author author@noreply.github.com
Objet : Re: [Dolibarr/dolibarr] Bug: Warning: is_dir(): open_basedir restriction in effect. File(/169) is not within the allowed path (#5900)

I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by grandoc** [comment]
Ce bug ne semble plus avéré dans la dernière version stable. Réouvrir ce bug si avéré.

**Comment by simnandez** [comment]
@odm69 I can not reproduce the pb with the new version stable. So I close the issue. If you have the same problem with the last version stable open a new Issue

**Comment by carotene922** [comment]
Hello,
Just try to use the system and seems there is bugs "HOME".  May I have your comment and advice?


Warning: is_dir(): open_basedir restriction in effect. File(c:/dolibarr/dolibarr_documents/produit/20mm_9??) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 101

Warning: is_dir(): open_basedir restriction in effect. File(c:/dolibarr/dolibarr_documents/produit/25mm_9??) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 101

Warning: is_dir(): open_basedir restriction in effect. File(c:/dolibarr/dolibarr_documents/produit/17mm_9??) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 101

Warning: is_dir(): open_basedir restriction in effect. File(c:/dolibarr/dolibarr_documents/produit/????????_????_(?)) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 101

**Comment by hregis** [comment]
@carotene922 
just to understand, the question marks are you who replaced them?

**Comment by carotene922** [comment]
There are Chinese in the name.  Seemse those "?" are those Chinese name.  SO, should I revise the name in English?

**Comment by hregis** [comment]
@carotene922 
this is the same problem with "international" character ?
