### ISSUE TITLE
Bug: error after setting Barcode value

### ISSUE THREAD

**Issue by Christian-Seiler** [Dolibarr/dolibarr#5911]
# Bug

Warning: preg_match(): No ending delimiter '^' found in /kunden/351322_8001/web/2039205/A2039205/erpbsm/htdocs/core/lib/functions2.lib.php on line 1161
Warning: Cannot modify header information - headers already sent by (output started at /kunden/351322_8001/web/2039205/A2039205/erpbsm/htdocs/core/lib/functions2.lib.php:1161) in /kunden/351322_8001/web/2039205/A2039205/erpbsm/htdocs/main.inc.php on line 975
## Environment
- **Version**: 4.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.6
- **Database**: MySQL or MariaDB 5.6.19-67.0-log
- **URL**: /opensurvey/index.php?mainmenu=tools&leftmenu=opensurvey&idmenu=5271
## Report

After setting the Value of the Barcode in a product I get the two messages above.

**Comment by eldy** [comment]
Go into setup of module barcode. 
What do you have for Manager to auto define barcode numbers (Product) ?

**Comment by Christian-Seiler** [comment]
I have the Standard Type for Products as "Code 39"

**Comment by eldy** [comment]
Can you provide a screen shot of setup page ?

**Comment by Christian-Seiler** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5319752/21743364/d4b83c96-d500-11e6-9c15-dadc2e3a097d.png)
Sorry for taking so long. Attached the settings of the barcode modul
auto define is {000000+100@12}-CSS-{mm}{yy}

**Comment by Christian-Seiler** [comment]
in functions2.lib.php:1161
    // If an offset is asked
    if (! empty($reg[2]) && preg_match('/^\+/',$reg[2])) $maskoffset=preg_replace('/^\+/','',$reg[2]);
    if (! empty($reg[3]) && preg_match('^\+',$reg[3])) $maskoffset=preg_replace('/^\+/','',$reg[3]);

seems like there's a missing / in pret_match

**Comment by rdoursenaud** [comment]
@Christian-Seiler There's indeed two '/' missing.

Since I can't seem to be able to reproduce the error, could you please try replacing the line 1161 by the code below and report back if it fixed the issue so I can prepare the fix for everyone.
```php
if (! empty($reg[3]) && preg_match('/^\+/',$reg[3])) $maskoffset=preg_replace('/^\+/','',$reg[3]);
```

Thanks!

FWIW, this code dates back to v2.8.1 and no one seem to have stumbled upon it until now.
This means the fix should be made in the n-2 supported version (3.8.x) at the time of writing.
