### ISSUE TITLE
BUG ON INVOICE LIST WHILE USING INVOICE HEADER EXTRAFIELD

### ISSUE THREAD

**Issue by zarveg** [Dolibarr/dolibarr#5912]
Hi all,
When using extrafield on invoice header, SQL request is not correctly build by ..compta/facture/list.php 

1) in SQL request,  ..LEFT JOIN doli_c_departements as state on (state.rowid = s.fk_departement), doli_facture as f  << this part should be better something like ..left join doli_facture as f  on s.rowid = f.fk_soc 

2) GROUP BY issue with ef.myextrafield, should be included in the GROUP BY statement.

Hope this will help.

Here is the php error log.

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20161022193546
Dolibarr: 4.0.1
Niveau de fonctionnalités: 0
PHP: 5.6.25
Server: Apache/2.4.23 (Win32) PHP/5.6.25
OS: Windows NT ALEX-LAPTOP 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) i586
UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

Url sollicitée: /dolibarr/root/compta/facture/list.php?leftmenu=customers_bills
Referer: http://localhost/dolibarr/root/compta/facture/list.php?leftmenu=customers_bills
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT f.rowid as facid, f.facnumber, f.ref_client, f.type, f.note_private, f.note_public, f.increment, f.fk_mode_reglement, f.total as total_ht, f.tva as total_vat, f.total_ttc, f.datef as df, f.date_lim_reglement as datelimite, f.paye as paye, f.fk_statut, f.datec as date_creation, f.tms as date_update, s.rowid as socid, s.nom as name, s.town, s.zip, s.fk_pays, s.client, s.code_client, typent.code as typent_code, state.code_departement as state_code, state.nom as state_name, SUM(pf.amount) as am,ef.regate as options_regate FROM doli_societe as s LEFT JOIN doli_c_country as country on (country.rowid = s.fk_pays) LEFT JOIN doli_c_typent as typent on (typent.id = s.fk_typent) LEFT JOIN doli_c_departements as state on (state.rowid = s.fk_departement), doli_facture as f LEFT JOIN doli_facture_extrafields as ef on (f.rowid = ef.fk_object) LEFT JOIN doli_paiement_facture as pf ON pf.fk_facture = f.rowid WHERE f.fk_soc = s.rowid AND f.entity = 1 GROUP BY f.rowid, f.facnumber, ref_client, f.type, f.note_private, f.note_public, f.increment, fk_mode_reglement, f.total, f.tva, f.total_ttc, f.datef, f.date_lim_reglement, f.paye, f.fk_statut, f.datec, f.tms, s.rowid, s.nom, s.town, s.zip, s.fk_pays, s.code_client, s.client, typent.code ,state.code_departement, state.nom ORDER BY f.datef DESC, f.rowid DESC LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_1055
Information sur le dernier accès en base en erreur: Expression #29 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dolibarr.ef.regate' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

XDebug informations:
File: C:\wamp\www\dolibarr\root\compta\facture\list.php
Line: 1499
Function: {main}

**Comment by olsesacl** [comment]
Fix: #5873
