### ISSUE TITLE
Bug on multitaxe

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#5914]
# Bug

Taxes in Canada (multi taxes)
When a customer is not subject to taxation 1 and / or 2 tax, both taxes are being systematically. It must be able to separate the two.

Ref : http://entreprisescanada.ca/fr/gouvernement/impots-et-taxes-tps-tvh/renseignements-sur-limpot-federal/vue-densemble-de-la-facturation-et-de-la-perception-de-la-taxe-de-vente/
## Environment
- **Version**: 3.9.4 and 4.0.1
- **PHP**: 5.6

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
