### ISSUE TITLE
Bug on ODT to PDF generation in propals

### ISSUE THREAD

**Issue by Skitprat** [Dolibarr/dolibarr#5930]
Hello,

When I try to generate a PDF from an ODT file of a proposal in Dolibarr 4.0.x , I get an error message.
My templates were working fine under 3.9 and I have no issue in orders / shipment / invoces with the same file, it works fine.

In the proposal section, it generates the ODT file fine, but it fails when converting it to PDF
Here is the error message :

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20161026115446
Dolibarr: 4.0.1
Niveau de fonctionnalités: 0
PHP: 5.4.45-0+deb7u4
Server: Apache
OS: Linux vds2732.sivit.org 2.6.38.4 #1 SMP PREEMPT Thu Apr 28 11:05:01 CEST 2011 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

Url sollicitée: /htdocs/comm/propal/card.php?id=9
Referer: http://***/htdocs/comm/propal/card.php?id=9
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur

Message: Error generating document for CommonObject. Error: ODT to PDF convert fail :

**Comment by rdoursenaud** [comment]
I'm not familiar with this feature but I believe it needs some tooling on the server side to work properly.

Anyone more familiar with this feature can confirm?

**Comment by Skitprat** [comment]
Hi,
I just tested out with a clean install on the 4.0.4 version, and the issue is still the same. ODT to PDF generation doesn't work in propals whereas it works fine everywhere else.

Did you manage to reproduce the bug ?
thanks

there is the log again :
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20170213173025
Dolibarr: 4.0.4
Niveau de fonctionnalités: 0
PHP: 5.4.45-0+deb7u4
Server: Apache
OS: Linux vds2732.sivit.org 2.6.38.4 #1 SMP PREEMPT Thu Apr 28 11:05:01 CEST 2011 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

Url sollicitée: : /htdocs/comm/propal/card.php?id=1
Referer: http://****/htdocs/comm/propal/card.php?id=1
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur

Message: Error generating document for CommonObject. Error: ODT to PDF convert fail :

**Comment by marcosgdf** [comment]
We need you to enable Syslog module with LOG_DEBUG scope and then post here the lines recorded in the file just after performing the action in order to check what happened

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
