### ISSUE TITLE
Feature Request: Add Width/Height on Product Card (available in database only currenlty)

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5933]
# Bug

v4.0 introduced Width/Height fields in Product Card (according to the change log). The database table shows the columns but the product card does not show the fields to add values or even display values.
## Environment
- **Version**: 4.0.1
- **Database**: MySQL
- **URL(s)**: /product/card.php

**Comment by eldy** [comment]
Are you sure your product is of type "product" and not "service" ?

**Comment by aljawaid** [comment]
Yes, the product is of type 'product' as we rarely use services.

I will send a screenshot later to show the form in edit mode and view mode.  Like I said, the column is in the database but there is nothing on the form.

**Comment by aljawaid** [comment]
@eldy If you advise me what code to look for, I can check if it is my version of the card.php on 4.0.1?

**Comment by aljawaid** [comment]
- **This is the product Create Form:**
  ![create-product-form](https://cloud.githubusercontent.com/assets/10233708/19833255/48c42488-9e33-11e6-8913-a3ff8f4bef7b.png)
- **I have checked the shared hosting server access/error logs** and nothing is showing.
- **I have checked the dolibarr.log file** and I noticed this section which showed the database fields **never had any width or height fields** in it but all the other fields:

`2016-10-29 23:46:05 DEBUG   79.77.241.109   sql=SELECT rowid, ref, ref_ext, label, description, url, note, customcode, fk_country, price, price_ttc, price_min, price_min_ttc, price_base_type, cost_price, default_vat_code, tva_tx, recuperableonly as tva_npr, localtax1_tx, localtax2_tx, localtax1_type, localtax2_type, tosell, tobuy, fk_product_type, duration, seuil_stock_alerte, canvas, **weight, weight_units, length, length_units, surface, surface_units, volume, volume_units,** barcode, fk_barcode_type, finished, accountancy_code_buy, accountancy_code_sell, stock, pmp, datec, tms, import_key, entity, desiredstock, tobatch, fk_unit, fk_price_expression, price_autogen FROM llx_product WHERE rowid = 115`
- **Also noticed a 'duration' column in database** but again **nothing** showing on the form.  No information on it but I assume it is to set a time limit on a product?

**Comment by aljawaid** [comment]
@eldy 

I have looked through product/card.php for v4.0.0 and v4.0.1.

In comparison, from around line 1015 it shows the code for Weight/Length/Volume/Surface **but not** Height or Width.

I have also cross-checked this with the same file in the develop branch of v4.0.1 and found the same issue - no reference to the width or height.

Maybe I am looking in the wrong place.  Not sure if this helps.

**Comment by aljawaid** [comment]
The same problem for 4.0.2 :(

**Comment by BebZ** [comment]
Did you check HIDDEN OPTIONS ?

_Hub_ to this thread.

**Comment by aljawaid** [comment]
@BebZ Hi, do you mean the 'hidden options' in the Dolibarr Setup>Other Setup?

I'm not sure what the hidden option would be to enable it?  It is not listed here? [https://wiki.dolibarr.org/index.php/Setup_Other](url)

**Comment by grandoc** [comment]
It's not a bug. Changelog was not clear, because width and height have only been added within database.

**Comment by eldy** [comment]
Ticket moved as feature requests

**Comment by aljawaid** [comment]
@grandoc Thank you for the explanation.  Makes a lot more sense now.  Hope the field to the table gets added soon to the product card.

**Comment by aljawaid** [comment]
#6114
