### ISSUE TITLE
Bug: Can't delete thirdparty

### ISSUE THREAD

**Issue by StefAngel** [Dolibarr/dolibarr#5944]
# Bug
lors d une suppression de tiers depuis la fiche tiers...

demande de validation puis

Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

redirection vers la form de creation de tiers 

et le tiers n est pas supprimer.

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.12
- **Database**: MySQL or MariaDB 10.1.18-MariaDB
- **URL**: /societe/soc.php?socid=

**Comment by jpfox** [comment]
Should be corrected with this commit 
https://github.com/Dolibarr/dolibarr/commit/5f432bd738a90c8c762475ed9b599391b8481ca9

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
