### ISSUE TITLE
Who's decide what is include or not in the Core???

### ISSUE THREAD

**Issue by defrance** [Dolibarr/dolibarr#5951]
Is not an issue but i think that point need to be discuss URGENTLY with the dolibarr team development!
We have inside the core some code specific for some specific additional module (ex : memcached, multicompany, pdf font, ...) and it seem ok for everybody. But for some other plugin element used by many additionnalS plugin used by MORE many USER, someone decide to suppress..

This behavior is not worthy of a open source development!!!

very angry i am!

**Comment by rdoursenaud** [comment]
Quite frustrating indeed. But in the end it's always @eldy and you know it. You're not a newborn here ;)

**Comment by rdoursenaud** [comment]
Also, would you be so kind as to link us to the particular piece of code you need that's been removed. It would make for a better case than a generic rant.

**Comment by gnovaro** [comment]
@defrance always you can made a fork and a pull request. If you want to add the multicompany feature maybe i can take some hour to involve, if you make a fork we can made a feature branch and when done we made a pull request for @eldy  include in dev branch.

**Comment by gnovaro** [comment]
@eldy Do you want to make a branch to multicompany and we made pull request to this branch for add this feature in core under your approval.

**Comment by eldy** [comment]
After each version, some code specific to an external dedicated module are replaced with hook.
multicompany module has less and less code into the core
I close the ticket because it's content is too generic. It is better to have a dedicated ticket for each case with particular piece of code reported.
