### ISSUE TITLE
Feature Request: To bill a order to another third party

### ISSUE THREAD

**Issue by clamisch** [Dolibarr/dolibarr#5954]
[*Third party selectable when checking an order.*]

![captura de pantalla de 2016-11-04 02-00-40](https://cloud.githubusercontent.com/assets/14363962/19995119/13dedcfa-a233-11e6-910d-940422e71a83.png)

[*For example as you can change a contact from a third party*]

![captura de pantalla de 2016-11-04 02-01-40](https://cloud.githubusercontent.com/assets/14363962/19995123/1dc58ea8-a233-11e6-908a-f88f2629bca0.png)

**Comment by BebZ** [comment]
No ! You have to go in contact/adresses tab to change it.
/commande/contact.php?id=7429

My opinion is also to set the third parties as "mother" and "subsidiary" on the Thirds card
/societe/soc.php?action=editparentcompany&socid=9459

![screenshot 2016-11-05 at 08 53 29](https://cloud.githubusercontent.com/assets/3694135/20028560/6ffea710-a335-11e6-8d0e-1ef5bbb6a20a.png)

**Comment by clamisch** [comment]
In our company daily exercise and also other businesses that use dolibarr in our country, it is commonly given to staff requesting quotes(PROPALE), but end up requiring billing (FACTURE) of its other businesses.
That's what is interesting, to be able to choose which is billed (facture) third a quote or order.
//Of course I'm ignoring the fact that our users have good dolibarr permits / advanced
