### ISSUE TITLE
Feature Request: Avoiding such much confirmation to VALIDATE events

### ISSUE THREAD

**Issue by clamisch** [Dolibarr/dolibarr#5956]
[*Action validate (Quotes, Orders, Invoices, etc.) immediately according to user privilege (expediting the use for advanced users)*]

**Comment by aljawaid** [comment]
If you mean there is too many confirmation screens I agree with you.  I would rather there was no confirmation but an 'undo' button after each event (quote, order, invoice etc) in case of mistakes.

Another idea could be to have a user permission so that we can choose which user needs to confirm each action etc

Just my thoughts :)

**Comment by eldy** [comment]
The confirmation button goal is to leave status draft to say "now this object exists and all data are consistent".
If we accept an order confirmed even when all lnes were not yet entered, the logistic may start to send data.
The accountancy may start to pay the invoice when amount is not yet complete,...
The button is not here for "permission purpose" but to allow a "draft" period. A module or an option should be able to avoi this step but side effect may be dangerous on companies with large number of users.

**Comment by aljawaid** [comment]
Thanks for the explanation.  It makes a lot more sense now.  Is there a hidden option to avoid this step?

**Comment by rdoursenaud** [comment]
While I don't agree there's too much confirmations, I do believe we could optimize these by making it fully JavaScript (when enabled and available). This would avoid the intermediate page reload and related round-trip times and backend delays.

**Comment by ksar-ksar** [comment]
Hi,

I try to make a module to solve this issue, I would like to use the hook formConfirm
But this hook is called only if $formconfirm is empty (no confirmation form).

This was really the goal of the formConfirm hook ?
Or it is a BUG and we need to change the condition to run the hook ?
Thanks

Edit : I have made a PR : https://github.com/Dolibarr/dolibarr/pull/9298
