### ISSUE TITLE
Bug: lotti e date scadenza

### ISSUE THREAD

**Issue by panypunk** [Dolibarr/dolibarr#5957]
# Bug

## Environment
- **Version**: 4.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.36
- **Database**: MySQL or MariaDB 5.5.52-38.3-log
- **URL**: /dolibarr/product/stock/mouvement.php?idproduct=1927

## Report

Buon giorno,
ho un problema sulla gestione dei lotti e date di scadenza. Nei carichi di magazzino per ordini da fornitore, riporto il numero del lotto e la data di scadenza, ma quando viene effettuata il ddt di scarico per il cliente, viene scaricato il lotto ma nei movimenti di magazzino non viene riportata la data di scadenza.

Come posso risolvere questo problema??

Grazie
![dolibarr_errore_lotti](https://cloud.githubusercontent.com/assets/21103886/20029195/469145ac-a346-11e6-862c-e67188e084a3.jpg)

**Comment by eldy** [comment]
Can you try to upgrade to 4.0.2 ?
This shoud be fixed in 5.0 but may be also in 4.0.2 (not sure)

**Comment by panypunk** [comment]
I installed the version 4.0.2 but the problem is not solved.
is a major problem, when version 5 will come out?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
