### ISSUE TITLE
no discount on supplier command made by replenishment

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#5958]
# Bug
When the replenish fonction create Prov supplier command and add product line, price, code and description are ok, but there are no discount from supplier price.

## Environment
- **Version**: 4.0.2
- **OS**: Wamp server 3.0.6 on Windows 10 pro v. 1607
- **Web server**: Apache 2.4.23
- **PHP**: 5.6.27
- **Database**: innodb MySQL 5.7.16

If you use the replenish fonction to create new supplier command from the stock menu, The prov command was create, the right product line was add with supplier code, description and unit price, but no discount, so the price after discount became false.

The problem came from replenish.php in .../htdocs/product/stock/replenish.php
Around lines 119 and 150 : miss instructions "$sql .= ', tva_tx, unitprice, **remise_percent** FROM ';"
and : "**$line->remise_percent = $obj->remise_percent;**"

For instance see the file i modify to correct it. 
[replenish.zip](https://github.com/Dolibarr/dolibarr/files/573107/replenish.zip)

Thanks in advance.

**Comment by eldy** [comment]
:-)
Thanks for your solution, your help is precious.
