### ISSUE TITLE
Wrong results from function calcul_price_total

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#5960]
# Bug
In some case the results from the function calcul_price_total was wrong : the function return the amount of VAT tax instead of total HT.

## Environment
- **Version**: 4.0.2
- **OS**: Wamp server 3.0.6 on Windows 10 pro v. 1607
- **Web server**: Apache 2.4.23
- **PHP**: 5.6.27
- **Database**:  innodb MySQL 5.7.16

## Expected and actual behavior
In case of rounding price not using base 10 ; the function calcul_price_total[0] return wrong value.
We expect Total HT.
We have VAT tax amount. 

## Solution
This problem came from .../htdocs/core/lib/price.lib.php on line 325.
This line was : "**$result[0]=price2num($result[2]-$result[0], 'MT');**"
It should be : "**$result[0]=price2num($result[2]-$result[1], 'MT');**"

## The corrected file
[price.lib.php.zip](https://github.com/Dolibarr/dolibarr/files/573121/price.lib.php.zip)

Thanks in advance.

**Comment by eldy** [comment]
Can you provide value of setup "rounding" you use and then input value sent to function and result you get and result you expect to get so we can a a phpunit test to avoid future regressions

**Comment by SylvainLegrand** [comment]
Below, you will see the page : 
![erreur arrondis](https://cloud.githubusercontent.com/assets/23272229/20235240/cadacebc-a89d-11e6-9dfa-d506ff03a900.png)

As i explain before when i expected the Total HT of a bill i found the VAT amount.

**Comment by eldy** [comment]
Will be available with 4.0.3
