### ISSUE TITLE
Bug: do not change the theme 

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#5962]
# Bug

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.33
- **URL**: /auditorias/admin/ihm.php?theme=auguria

**Comment by eldy** [comment]
The theme auguria is no more supported kdoes not exists anymore) with version 4.0.
