### ISSUE TITLE
Error in calculations of customer preview when FACTURE_DEPOSITS_ARE_JUST_PAYMENTS = 1

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5963]
# Bug
If FACTURE_DEPOSITS_ARE_JUST_PAYMENTS is set to "1", the payments are not correctly calculated in the recap-compta.php, respectively one accounting transaction is missing. 

## Environment
- **Version**: 4.0.2
- **URL(s)**: https://[…]/compta/recap-compta.php?socid=1234

## Actual behavior
![wrong](https://cloud.githubusercontent.com/assets/14094327/20060829/50c5bc84-a4fd-11e6-8cab-c5b64e0d226e.jpeg)

## Expected behavior (for example)
![corrected2](https://cloud.githubusercontent.com/assets/14094327/20061233/4d090f54-a4ff-11e6-8e26-a3a229f03421.jpg)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
