### ISSUE TITLE
Cannot create supplier invoice

### ISSUE THREAD

**Issue by dreggy** [Dolibarr/dolibarr#5964]
# Bug
I cannot create a supplier invoice and appear a page full of warnings.

## Environment
- **Version**: 5.0 alpha
- **OS**: ubuntu
- **Web server**: apache2.0
- **PHP**: 7.0.8-0ubuntu0.16.04.3
- **URL(s)**: /dolibarr/fourn/facture/card.php?action=create&mainmenu=accountancy

When i click on Create it should create the supplier invoice but a page full of warnings appear and the invoice is not created.
I found in the code that in the file \dolibarr\fourn\facture\card.php there are 4 $db->begin(); and only 3 $db->commit();
I commented the line 
575      $db->begin();
and now the page is working good.

**Comment by eldy** [comment]
Should be fixed now.
