### ISSUE TITLE
Incorrect calculated margin in the margin report

### ISSUE THREAD

**Issue by fastm3** [Dolibarr/dolibarr#5965]
# Bug
Incorrect calculated margin in the margin report.

## Environment
- **Version**: 4.02
- **OS**:  Linux debian 2.6.32-22-pve 
- **Web server**: Apache/2.2.9
- **PHP**: 5.3.8-1
- **Database**: MySQL
- **URL(s)**: /margin/customerMargins.php

## Expected and actual behavior.
The displayed margin in an invoice card should be the same value in the margin report.

## Steps to reproduce the behavior
Create an invoice with only 1 product. Sell price will be 400€. Cost price will be 200€.
Add a discount line ( negative value ) of 100€.
Margin is correctly calculated and displayed as 100€
Now, go to  /margin/customerMargins.php
For the customer with the previous invoice, the margin calculated will be 200€ instead of 100€
Same info at 2 different screens and 2 different values for same info. This is the margin report which is incorrect.

**Comment by BebZ** [comment]
Margin should be stored at order level you think ?

**Comment by fastm3** [comment]
It could be a way to avoid such issue. But for sure , margin should be calculated or stored in only one place to avoid such inconsistent report.

**Comment by fastm3** [comment]
This issue is still existing in 5.04. Actually , this issue exists since 2014 for all versions.
Reports with margins are wrong. ( ok at the invoice level ) . I live with that. But it should be disabled or you should mention they are wrong as some business could make wrong decisions based on some wrong infos displayed by Dolibarr.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
