### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by StefAngel** [Dolibarr/dolibarr#5976]
# Bug

Lors de la tentative de suppression d'un tiers, 

validation du popup puis

Error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.12
- **Database**: MySQL or MariaDB 10.1.18-MariaDB
- **URL**: /societe/soc.php?socid=

**Comment by eldy** [comment]
Can't reproduce. The url you are coming from  /societe/soc.php?socid= looks strange.
Which path do you use to reach on page but the delete button ?

**Comment by StefAngel** [comment]
Bonjour laurent,

Je vais sur ma liste de prospects.

Clique pour avoir la fiche. Puis sur le bouton supprimer...

Demande de confirmation avec suppression des infos dépendantes.

Puis reload d une url sans l id de la fiche...

**Comment by StefAngel** [comment]
Bonjour je vais sur ma liste de prospects.

Clique pour avoir la fiche. Puis sur le bouton supprimer...

Demande de confirmation avec suppression des infos dépendantes.

Puis reload d un url sans le socid...

Le 11 nov. 2016 15:16, "Laurent Destailleur" notifications@github.com a
écrit :

**Comment by eldy** [comment]
Enable module log. Do you have error message into dolibarr.log file ?
Can you reproduce on demo.dolibarr.org ?

**Comment by StefAngel** [comment]
je viens d activer le log module...
vais chercher ou trouver lesdits log.
et essayer de trouver la cause avant de revenir vers vous...

2016-11-22 20:59 GMT+01:00 Laurent Destailleur notifications@github.com:
