### ISSUE TITLE
Feature Request: Allow Expense Reports for the same Date Ranges

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5985]
# Feature Request
Expense Reports seem to only allow users to create one expense report for one date period.  That means only one expense report per user.  **The date period should never be cross-checked** so the user can create multiple expense reports for the same date period.

## Use Case
We use expense reports to record business expenses so that we can have a statement-style breakdown of all expenses.  The expenses are recorded in groups.  We need to create 21 different expense reports all for the same date period.  Dolibarr currently is allowing only one report to be created.

## Environment
- **Version**: 4.0.2

**Comment by aljawaid** [comment]
I would highly appreciate if somebody could show me how to hide the date range checking in the code.

**Comment by aljawaid** [comment]
I have managed to find a temporary fix.  I hope this continues to work and maybe @eldy can make it a hidden option in the future.

In expensereport/card.php I have commented out the below lines.

```

    /*if ($object->periode_existe($user,$object->date_debut,$object->date_fin))
    {
        $error++;
        setEventMessages($langs->trans("ErrorDoubleDeclaration"), null, 'errors');
        $action='create';
    }*/
```

**Comment by dolibarr95** [comment]
https://github.com/Dolibarr/dolibarr/commit/8352aee9f7c273478d460f7fa505854c86c1b984
