### ISSUE TITLE
Feature Request: Autoset status of expense report when remain to pay is zero

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#5987]
# Bug
Paid the full amount in the expense report but it is still showing as a remaining balance of too many zeros and not automatically marking it as paid (complete).

![rounding](https://cloud.githubusercontent.com/assets/10233708/20240922/5f19581c-a91d-11e6-9f3c-55af9a52af54.png)

## Environment
- **Version**: 4.0.2
- **File**: expensereport/card.php

**Comment by eldy** [comment]
Problem for amount with two many 0 seems fixed.
Also for setting status of expense report automatically to payed, i moved the ticket as a feature request to have same behaviour than invoices.

**Comment by atm-maxime** [comment]
Hi @aljawaid 

Sorry I can't reproduce on the 4.0.2 Dolibarr official demo.

![image](https://cloud.githubusercontent.com/assets/2097773/21072970/aa611cee-bed3-11e6-9147-b7f46bef2c00.png)

Maybe something wrong with your installation / envrionnement

**Comment by aljawaid** [comment]
Thank you for the explanation
