### ISSUE TITLE
Feature Request: Add a warning to confirm deletion of product that has stock not null

### ISSUE THREAD

**Issue by defrance** [Dolibarr/dolibarr#5998]
create a product
add a stock movement
I can delete the product when I should not

before delete i need to controle that all stock_product of this product is equal to zero

**Comment by eldy** [comment]
This could be a warning into the confirm box.

**Comment by defrance** [comment]
A simple warning is not enough to block something who impact the valuation of the stock. It should not be possible to delete a product if there is present stock of it. It is an important functional bug
