### ISSUE TITLE
Feature Request - Add agenda event from customer order, invoice card

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#6002]
# Feature Request
In proposal, customer order, invoice add button to make new agenda event, it's good feauture to fast make follow up linked to proposal, order, invoice or other items.

**Comment by aljawaid** [comment]
Hello, this is already available as a hidden option:
MAIN_ADD_EVENT_ON_ELEMENT_CARD => Allow to create an event from a document (proposal, order, invoice)

[https://wiki.dolibarr.org/index.php/Setup_Other](url)

**Comment by pat15** [comment]
Thank's for help :) i don't see it.
