### ISSUE TITLE
Feature Request  - Support for stock increase/decrease using lot/serials

### ISSUE THREAD

**Issue by svalo** [Dolibarr/dolibarr#6005]
## Environment
- **Version**: 4.0.2
- **OS**: Ubuntu 14.04
- **Web server**: Nginx
- **PHP**: PHP5 5.5.9
- **Database**: Postgres 9.3.15

# Feature Request
Support for automatic stock decrease/increase when a customer order or a supplier order is validated while using lot.

## Use case
When an invoice is created and validated items quantity in the warehouse gets adjusted and it's no longer needed to manually adjust them

It would be nice to provide a UI to select from which lot to take the amount of desired items while generating the invoice or Draft.

As of now it's not possible because of:
![screenstock](https://cloud.githubusercontent.com/assets/2277997/20388018/36ae5b8a-acc3-11e6-9295-9e776171d6c8.png)

**Comment by BebZ** [comment]
I think you should activate "supplier orders" and "customer orders" 
to "select" the lots to "ship" it works like a charm.
did you try ?
for answering your : 
"provide a UI to select from which lot to take the amount of desired items while generating the invoice or Draft."

**Comment by svalo** [comment]
Hello @BebZ  I already have both modules active and correctly configured (as far as I understand) 
At my company we don't use the shipping feature, so I went to check and maybe it can be what I'm searching for.
As probably I'm not using dolibarr the right way can you point me to some resource where I can learn a typical workflow? Thanks

**Comment by BebZ** [comment]
sorry for long answer this is quite old but still useful ;)
[test of dluo and how-to.pdf](https://github.com/Dolibarr/dolibarr/files/622537/test.of.dluo.and.how-to.pdf)
