### ISSUE TITLE
Bug: Webservice SOAP function createInvoiceFromOrder doesn't work

### ISSUE THREAD

**Issue by philippe-opendsi** [Dolibarr/dolibarr#6006]
# Bug
This method seems to have never been tested/used. Input parameters are invoice reference ?
In fact using it with an order_id returns KO. It have no sense to send the invoice id we want to create... 

The declaration of SOAP function
```
$server->register(
		'createInvoiceFromOrder',
		// Entry values
		array('authentication'=>'tns:authentication','invoice'=>'tns:invoice'),
		// Exit values
		array('result'=>'tns:result','invoice'=>'tns:invoice'),
...
```

The declaration of function createInvoiceFromOrder

```
function createInvoiceFromOrder($authentication,$id_order='', $ref_order='', $ref_ext_order='', 
		$id_invoice='', $ref_invoice='', $ref_ext_invoice='')
```

## Environment
- **Version**: developp and previous

**Comment by atm-maxime** [comment]
This issue seems to have been fixed, invoice parameters no longer available in the method.
