### ISSUE TITLE
close one intervention ticket

### ISSUE THREAD

**Issue by Madumtv** [Dolibarr/dolibarr#6007]
# Bug
impossible to close one ticket intervention in commercial part.
I don't see the bouton present in version 5.

## Environment
- **Version**: 4.0.2
- **OS**: Raspbian Jessie

## Steps to reproduce the behavior
create cmr,
create case intervention
save
status "valide"
impossible to putt in close

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
a button to close the intervention

**Comment by eldy** [comment]
Fix should be available with 4.0.3 released during next devcamp

**Comment by Madumtv** [comment]
i see now the buton classify done but when i click on it, nothing append...
the page is reloaded without actions.... and buton is still avaible
