### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by StefAngel** [Dolibarr/dolibarr#6011]
# Bug
la fonction envoi par mail des shipments ne fonctionne pas...

j ai un "popup" indiquant que le mail est parti mais je ne recois rien...

propal/commande ca fonctionne...

je vais tester facture...

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.12
- **Database**: MySQL or MariaDB 10.1.18-MariaDB
- **URL**: /expedition/card.php?id=1

**Comment by marcosgdf** [comment]
Can you please report your bug in English?

**Comment by philippe-opendsi** [comment]
Hi
Sending email from shipments works for me. Please post the error message.

**Comment by simnandez** [comment]
@StefAngel  Works fine with 4.0.2 version. I close the Issue.
