### ISSUE TITLE
Bug: lateral menu is reset after reconnecting

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#6016]
# Bug
After a delay, action starts with a connection screen. After this reconnection, the menu is not in the specific context, but the generic one.

## Environment
- **Version**: 4.0.2
- **OS**: Linux - Mageia - Firefox
- **URL(s)**: /htdocs/compta/tva/clients.php (one example)

## Expected and actual behavior
I expect that the menu is the one for compta/tréso
But I get this one
![dolibarr-menu](https://cloud.githubusercontent.com/assets/5154580/20458276/9efc42c2-aea0-11e6-9196-ebbd15e41741.png)

**Comment by eldy** [comment]
The context where use is is store into connection. When session expired, we loose this so e start again to the default context, so the home.
This will probably won't be fixed because this need a very important work for a minor enhancement.
