### ISSUE TITLE
Bug: EXPORT MODULE AFFAIRES

### ISSUE THREAD

**Issue by odm69** [Dolibarr/dolibarr#6021]
# Bug

## Environment
- **Version**: 4.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/exports/export.php?step=5&datatoexport=lead_1

## Report

Bonjour,

au moment de l'export des données des Affaires, l'export a rpoduit le message suivant :
"Unknown column 'extra.dongen' in 'field list' - sql=SELECT DISTINCT l.rowid as l_rowid, l.ref as l_ref, l.ref_ext as l_ref_ext, l.ref_int as l_ref_int, so.nom as so_nom, dictstep.code as dictstep_code, dictstep.label as dictstep_label, dicttype.code as dicttype_code, dicttype.label as dicttype_label, l.date_closure as l_date_closure, l.amount_prosp as l_amount_prosp, l.description as l_description, extra.dongen as extra_dongen, extra.exwp as extra_exwp, extra.dapp as extra_dapp, extra.lotsize as extra_lotsize, extra.annualvol as extra_annualvol, extra.dev as extra_dev, extra.protorder as extra_protorder, extra.presprot as extra_presprot, extra.valprot as extra_valprot, extra.won as extra_won, extra.presppap as extra_presppap, extra.valppap as extra_valppap, extra.sop as extra_sop, extra.eop as extra_eop, extra.anfnr as extra_anfnr, extra.angnr as extra_angnr, extra.artreflv as extra_artreflv, extra.artrefcust as extra_artrefcust, extra.plant as extra_plant FROM llx_lead as l LEFT JOIN llx_societe as so ON so.rowid=l.fk_soc LEFT JOIN llx_user as usr ON usr.rowid=l.fk_user_resp LEFT JOIN llx_c_lead_status as dictstep ON dictstep.rowid=l.fk_c_status LEFT JOIN llx_c_lead_type as dicttype ON dicttype.rowid=l.fk_c_type LEFT JOIN llx_lead_extrafields as extra ON extra.fk_object=l.rowid WHERE l.entity IN (1)"

Est-ce lié aux attributs supplémentaires que j'ai créés?
aux séparateurs de champs ?

Merci d'avance pour votre aide.

**Comment by eldy** [comment]
The external module affaire is not a module supported by dolibarr core team. You should submit your bug to the bug tracker of the company that provide the external module.
