### ISSUE TITLE
Bug: PROSPECT/CUSTOMER

### ISSUE THREAD

**Issue by ab-distrib** [Dolibarr/dolibarr#6022]
# Bug

## Environment
- **Version**: 4.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/societe/soc.php?action=create&leftmenu=

## Report
Hello,
A lot of my clients say that a third party can either be a prospect OR a Customer but never both. It would be nice to get rid of that option with a variable called SOCIETE_DISABLE_PROSPECTS/CUSTOMERS_ONLY for instance.
Best regards

**Comment by aljawaid** [comment]
Hello, as an opinion I disagree...
On v4.0.2 we have these options:
![prospect-customer](https://cloud.githubusercontent.com/assets/10233708/20501446/de2634ac-b031-11e6-8c3c-c5892f70ca83.png)
My understanding:
Prospect - potential customer in all entirety with no goods/services purchased
Customer - paying customer with previous or ongoing goods/services purchased
Prospect/Customer - Same as _Customer_ but potentially a prospect for future goods/services/projects etc
Nor Prospect, Nor Customer - I use this for Accountant/Council/Government/Tax name/address/notes/agenda/events details etc.

So for me and my business set up, it works as it is. But if there was a switch to activate or deactivate that would be fine too as long as the option is not permanently removed.

**Comment by ab-distrib** [comment]
Hello,
Clients think differently but I respect your consideration... as long as a variable would allow us to drop this 'beween the two' option.
Regards

**Comment by dunhamjared** [comment]
This is not a typical feature found is most ERP systems. But this does shows how flexible Dolibarr has been developed and can really benefit a few unique businesses i.e. @aljawaid  

I would have the Prospect / Customer feature disabled and give an option to have this enabled. In the options section, it would also be nice to explain why you would want to enable this feature.

**Comment by eldy** [comment]
The definition of prospect in Dolibarr means (we can make proposal) and customer mean (we can make invoice). Considering this, disabling choice "prospect+customer" is dangerous. In most cases, you still have to do proposal for existing prospects.
With 5.0 hidden constant SOCIETE_DISABLE_PROSPECTSCUSTOMERS will be able to deal this, but it looks dangerous.

**Comment by ab-distrib** [comment]
Sorry, but in France, a third party can't be a prospect and a client at the same time. 
True that you can't invoice a prospect, but true also that you can both propose AND invoice a client, so needless to specify he is a prospect.
If I was to follow the definition specified above, with all the due respect, there isn't anybody on earth I could not make a proposal to. Thus, the very status of Prospect shouldn't even exists. If it exists, it is to clearly define the client FROM the prospect.

Problems is that when busyness men create a new third party on Dolibarr, they forget to specify either one.
Thus, statistics are wrong.

But then again, SOCIETE_DISABLE_PROSPECTSCUSTOMERS is the corporate answer.
Best regards

**Comment by dunhamjared** [comment]
A **prospect** is someone who is a potential or likely customer.
A **customer** is someone who has already purchased something from you.

The proposal function should be included for customers. We should not have to set it to both Customer/Prospect. Odd design choice.

**Comment by ab-distrib** [comment]
Hello BlueJ130,
I totally agree with you. 
But somme people need it, so at least, we should have the choice. Appearently, it shoul be set on version 5.0.
Can't wait for it :-)
Regards
