### ISSUE TITLE
Bug date of value over 30/10/2016

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#6027]
# Bug
date of value in bank section is blocked at 30/10/2016 and not go over this date in 4.0.1 or 4.02 with my install or on the dolibarr.fr online demo

note functional with + /  - button ,  but it's good with manual update of the date after validation

**Comment by eldy** [comment]
Can you provide dolibarrr version and url concerned ?

**Comment by ptibogxiv** [comment]
i see this bug with 4.0.1 and 4.0.2 on my server, i see this bug too  with the online demo of dolibarr.fr

the url is  /compta/bank/rappro.php?account=1

**Comment by eldy** [comment]
Looks ok with 5.0

**Comment by ghost** [comment]
it is due to old version of mysql and driver use (mysql instead of mysqli)

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug
