### ISSUE TITLE
Bug: I can receive product when the supplier order is closed.

### ISSUE THREAD

**Issue by jmsandovalp** [Dolibarr/dolibarr#6028]
I MUST NOT RECEIVE PRODUCT IF THE SUPPLIER ORDER HAS THE STATUS EVERYTING RECEIVED.

In the version Dolibarr 3.6.0, the supplier order had that restriction that if the supplier order has the status Closed, everything can’t receive product, AND if you want to receive more product you have to reopen the supplier order, but in the version 3.7.0 that restriction was erased

**Comment by simnandez** [comment]
You must use the hidden option SUPPLIER_ORDER_DISABLE_STOCK_DISPATCH_WHEN_TOTAL_REACHED to use this functionality
