### ISSUE TITLE
Bug: Moving between invoice/proposal with the arrow get an error

### ISSUE THREAD

**Issue by jmsandovalp** [Dolibarr/dolibarr#6030]
When I access to an invoice or commercial proposals (Both have the same problem), already created, I want to access to the next of before invoice/proposal using the arrows, I get the next error:

Fatal error: Call to a member function fetch_object() on boolean in /var/www/html/dolicemsa/core/db/mysqli.class.php on line 285

Access
Commercial > Search a proposal > Access to any proposal

**Comment by simnandez** [comment]
Works for me in 3.8.x, 3.9.x, 4.0.x and develop branch
