### ISSUE TITLE
Converting to discount when there is a credit note inside

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#6053]
Converting a credit note that was generated from an invoice that contains a deposit inside, lead in 2 discounts lines. It should lead into only one line that is amount of invoice less deposit.

**Comment by atm-maxime** [comment]
Works for me in 8.0
Attention, the conversion to discount creates several discounts ragarding each VAT rates, that's the expected behaviour. If the customer had no VAT in the deposit but VA in the invoice, the credit note containing all the lines will result in several discounts.

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
