### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ab-distrib** [Dolibarr/dolibarr#6068]
# Environment
- **Version**: 3.9.3
- **OS**: Windows NT
- **Web server**: Apache/2.4.23 (Win64) PHP/7.0.10
- **PHP**: apache2handler 7.0.10
- **Database**: MySQL or MariaDB 5.7.14
- **URL**: /dolibarr-aratice-test/htdocs/compta/facture.php?facid=610

# Report
Why have I this error message after installing version 3.9.3?

"Warning: Declaration of FactureRec::create($user, $facid) should be compatible with Facture::create($user, $notrigger = 0, $forceduedate = 0) in C:\wamp64\www\dolibarr-aratice-test\htdocs\compta\facture\class\facture-rec.class.php on line 641"

Regards
![capture](https://cloud.githubusercontent.com/assets/22303438/20761614/d5371354-b723-11e6-945e-6f7ca8a8936a.PNG)

**Comment by ab-distrib** [comment]
Anybody to help me , plizzzzzzzzzzzzzzzzzzzzz

**Comment by braito4** [comment]
This bug is corrected in 4.0
It's related to php 7.0

**Comment by ghost** [comment]
It is more related to web server configuration that output warning. Check apache configuration

**Comment by ab-distrib** [comment]
Hi, everybody.
Changing version of Apapche to 5. worked fine.
Thanks a lot to everyone.
