### ISSUE TITLE
Dolimed Demo Not Working

### ISSUE THREAD

**Issue by deniscaron** [Dolibarr/dolibarr#6069]
Page : http://www.dolimed.com/onlinedemo
Link : http://demo.dolimed.com/?username=demo

Result :
DolibarrHasDetectedError.
InformationToHelpDiagnose:
Date: 20161130193210
Dolibarr: 4.0.1
PHP: 5.3.28
Server: Apache
OS: Linux apollon1.nltechno.com 2.6.24.5-grsec-xxxx-grs-ipv4-64 #3 SMP Tue May 27 19:09:58 CEST 2008 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

RequestedUrl: /?username=demo
Referer: http://www.dolimed.com/onlinedemo
MenuManager: 

DatabaseTypeManager: mysql
RequestLastAccessInError: ErrorNoRequestInError
ReturnCodeLastAccessInError: ErrorNoRequestInError
InformationLastAccessInError: ErrorNoRequestInError

Message: host=localhost, port=0, user=dolibarrdemo, databasename=dolibarrdemodolimed, Access denied for user 'dolibarrdemo'@'localhost' (using password: YES)
0

**Comment by marcosgdf** [comment]
This is not the place to report this issues. Please contact the developer of Dolimed
