### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by gnovaro** [Dolibarr/dolibarr#6071]
# Feature Request
Code Refactoring, please use english names. 

Rename compta -> account
Rename fichinter -> file
Rename societe -> company
Rename commande -> order
Rename contrat -> contract
Rename fichinter -> file ??
Rename livraison -> delivery / distribution
Rename projet -> project
Rename fourn -> supply
No more Franglish.

**Comment by eldy** [comment]
Such tasks are heavy work with high risk. That's why we do it version after version (for example, in 4.0, we did in on "expensereport" to replace "deplacement", in 5.0 the normalization was done on "notes".
We progress one topic per topic but due to risk, such actions are currently done by myself or few experimented core developers.

**Comment by BebZ** [comment]
Not only high risk 
but also interpretation / translation
Has to be read by natives speakers in context

**Comment by rdoursenaud** [comment]
@BebZ These are internal variables to be red by developers. Bad english is still better than frenglish for non french devs.
Even french devs like myself are often confused by the crazy language mix in Dolibarr source code.

Anyway, these change are for the better but should be done with baby steps considering the ramifications of the changes, some of which are not under our control (Most notably external modules).
Extra care has also to be taken on communicating about these changes to give module developers a chance to catch on.
Nerve wracking decisions, hence the baby steps ;)
Keep up the good work @eldy.

**Comment by absnc** [comment]
Hi everyone,

It sounds like the wording `workorder` is suited for `fichinter`.
Then, each line of a work order, whether it refers to a product or a service could be called `deliverable`,

I'm looking after bringing some enhancements to the delivery related processes, right now.
So, if anyone using the existing naming or having done some research on the subject, can relate..


Regards,
