### ISSUE TITLE
[Bug][advandced comptability] label says TVA 0% where it should be 20%

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#6073]
# Bug
The sales journal (journal des ventes) has a column "Type" with a label including successively the name of the client, the invoice number and the type of the line. For the TVA line, I get for this type : "TVA 20%" in one case, and "TVA 0%" in a second case. The "code comptable" 445712 is the same in the two case and is personalised. The second case is false, because the TVA is not null.
## Environment
- **Version**: 4.0.2
- **URL(s)**: htdocs/accountancy/journal/sellsjournal.php?mainmenu=accountancy&leftmenu=accountancy_journal

## Expected and actual behavior
Should display "TVA 20%"

## [Attached files]
![dolibarr-jdv](https://cloud.githubusercontent.com/assets/5154580/20787552/b782abbe-b7ac-11e6-9e07-b5cc3e0d5288.png
Screenshot

**Comment by philippe-opendsi** [comment]
Hi
Can not reproduce on 4.02 and develop version

**Comment by simnandez** [comment]
I can't reproduce

**Comment by papoteur-mga** [comment]
To reproduce the bug:
create an invoice with a service, amount 100 EUR, TVA 20%
add a line with a service, amount 20 EUR, TVA 0%

**Comment by papoteur-mga** [comment]
Is it possible to reopen the bug?
Or should I file a new one?
It is still valid, I get it each month.
