### ISSUE TITLE
Bug: 5.0 Beta bank Balance doesn't match real amount

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#6075]
## Environment
- **Version**: [5.0Beta]
- **PHP**: [*PHP 7*]
- **URL(s)**: [*http://localhost:8888/dolalfa/compta/bank/bankentries.php*]

## Expected and actual behavior
bank entries are omitted in the calculation of the balance. The problem is not in the page that we are seen.

## Steps to reproduce the behavior
Just pick a line in the bank transfers list.

The change the number of entries listed; and check de balance of the bank for that entry
![screen shot 2016-12-01 at 12 52 54](https://cloud.githubusercontent.com/assets/1913498/20793163/faadc662-b7c5-11e6-8141-392abe4af4d7.png)
![screen shot 2016-12-01 at 12 53 18](https://cloud.githubusercontent.com/assets/1913498/20793164/faaf62f6-b7c5-11e6-99b2-e68ea3ea7780.png)

**Comment by atm-florian** [comment]
Can't reproduce

**Comment by ghost** [comment]
Can't reproduce

**Comment by simnandez** [comment]
It's not a bug. If you have multiple pages list, you must move between them and at the least page you have the final balance.
