### ISSUE TITLE
Bug: Excess amount of image thumbnails in Financial area

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6091]
# Bug

![captura de pantalla 2016-12-08 a las 14 28 02](https://cloud.githubusercontent.com/assets/168744/21011675/9024c722-bd52-11e6-8ed0-902e3a803677.png)

They are too much and distort the box

## Environment
- **Version**: 3.9.3
- **URL(s)**: /compta/index.php?mainmenu=accountancy&leftmenu=

**Comment by simnandez** [comment]
Works fine in 3.9.4

![captura de pantalla de 2016-12-10 12-15-34](https://cloud.githubusercontent.com/assets/881833/21072940/7c56c890-bed2-11e6-81a2-40436d90eb88.png)

**Comment by marcosgdf** [comment]
No.

It only happens under specific circumstances but it does happen in 3.9.4.
Check the code to see why and you'll get it

**Comment by marcosgdf** [comment]
No.

It only happens under specific circumstances but it does happen in 3.9.4.
Check the code to see why and you'll get it

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/class/html.formfile.class.php
Function getDocumentsLink
```php
$file_list=dol_dir_list($filedir, 'files', 0, preg_quote(basename($modulesubdir),'/').'[^\-]+', '\.meta$|\.png$');	// Get list of files starting with name of ref (but not followed by "-" to discard uploaded files)
```

As you can see it looks for files with extension different than .png and with a name that starts with the invoice number

**Comment by simnandez** [comment]
Confirmed

**Comment by eldy** [comment]
@simnandez What did you do to have the problem reproduced ?

**Comment by simnandez** [comment]
I added images to the invoice, but now I can not reproduce it

**Comment by eldy** [comment]
So i suppose bug was fixed silently, so i close.
