### ISSUE TITLE
BUG with the supplier proposals modules V4.0.2

### ISSUE THREAD

**Issue by nicoeis** [Dolibarr/dolibarr#6092]
Hi,

**I'm on dolicloud.com solution,**

Everytime im tryin' to do a new supplier proposal (demande de prix fournisseur) i have a message error and i cannot complete the file by adding items on it.

Plus the generated files are not deletable 

I really don't get it --> On the Online Demo version of Dolibarr it works perfectly !!
https://demo.dolibarr.org/public/demo/index.php

and i'm on the same version ...

My instance of Dolibarr / Dolicloud is brand new and clean the only thing i did is the upgrade from 3.9.2 to 4.0.2 .

Please someone help me i need this for my company ...

![capture d ecran 2016-12-08 a 13 37 12](https://cloud.githubusercontent.com/assets/24410971/21014736/6d949a90-bd5f-11e6-8a8d-617575bc967d.png)
![capture d ecran 2016-12-06 a 21 49 21](https://cloud.githubusercontent.com/assets/24410971/21014737/6dcd9d90-bd5f-11e6-8142-67c1ba672c87.png)

- **Version**: [4.0.2]
- **OS**: [OSX 10.10]

**Comment by ghost** [comment]
this should be fix by Upgrade SQL from 3.8 to 3.9.
ALTER TABLE llx_supplier_proposaldet CHANGE COLUMN fk_askpricesupplier fk_supplier_proposal integer NOT NULL;

**Comment by simnandez** [comment]
You must upgrade from 3.8 to 3.9
