### ISSUE TITLE
Add Supplier Price "Price for this min. qty (w/o discount)" always sets item in database to "Net of Tax" so unable to set "Inc. Tax"

### ISSUE THREAD

**Issue by cleverthings** [Dolibarr/dolibarr#6138]
# Bug
When adding a Supplier Price or editing an existing Supplier Price, whether the user selects "Net of Tax" or "Inc. Tax" the system records it as "Net of Tax" and so user is unable to change it (without SQL which I'm sure is discouraged).

## Environment
- **Version**: 4.0.2
- **OS**: Ubuntu Linux 64-bit
- **Web server**: Apache HTTPD 2.4.23
- **PHP**: 7.0.14-1+deb.sury.org~xenial+1
- **Database**:  MySQL or MariaDB 5.7.16-0ubuntu0.16.04.1
- **URL(s)**:  https://demo.dolibarr.org/product/fournisseurs.php?id=21

## Expected and actual behavior
Expected: The "Price for this min. qty (w/o discount)" should be either "Net of Tax" or "Inc. Tax" based on user selection.  Actual: Always being set to "Net of Tax" regardless of user selection.

## Steps to reproduce the behavior
To reproduce: go to BUYING PRICES tab and either edit an existing entry or add a new one.
Select "Inc. Tax" and save the entry.
Look at the BUYING PRICES tab again, and the system saved the selection as "Net of Tax" for that item.

## Use case
Users who need to add supplier prices that include tax.

## Suggested implementation
Connect user selection to database.

## Suggested steps
Workaround: Set tax rate to 0 for those items.

**Comment by cleverthings** [comment]
When I look at the database tables by logging in through MySQL, it looks like the data is correct in the database. price_base_type shows "TTC" which is correct, yet display of those items show "Net of Tax" which should be "HT" - or do I not understand this correctly? The same behavior is on the demo system.  (I apologize if I am missing something obvious - I'm a newbie to Dolibarr.)

**Comment by jfefe** [comment]
Hi @cleverthings and welcome to the Dolibarr galaxy!

It seems it's not a bug but correct behavior : we always store (and work) with 'net of tax' value. The choice 'Inc tax' is just a help for user : field 'Inc tax' is filled and Dolibarr calculate for us the price 'Net of tax'.

**Comment by cleverthings** [comment]
Thanks, I'll close this as not a bug and as resolved. I apologize. I'm trying to walk through the source code to understand it, but I don't speak French so I have TWO learning curves to tackle. ;) I really appreciate the quick response and love the software. Great work!
