### ISSUE TITLE
BUG: 5.0 Beta. Convert supplier order to invoice loses lines and project related

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#6161]
# Bug
create a supplier order and convert it to invoice

## Environment
- **Version**: [5.0 Beta]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [PHP 7]
- **Database**: [*Database type and version*]

**Comment by SBA18** [comment]
Same problem losing products line and other infos about the supplier order.

**Comment by SBA18** [comment]
Did someone saw this issue to future correction Allow someone is here? The same issue is present for v5.0.0RC1.
