### ISSUE TITLE
Bug: Don’t save the fields eatby and sellby in the table  llx_expeditiondet_batch

### ISSUE THREAD

**Issue by jmsandovalp** [Dolibarr/dolibarr#6162]
When I do an expedition with products that have batch (lot/serials), don’t save the information in the fields eatby and sellby in the table  llx_expeditiondet_batch.

Commercial > Customer order > New order > Shipments with product with lot/serials
Dolibarr 4.0.2

**Comment by eldy** [comment]
Should be fixed with 5.0.
When you add a lot with data for eatby or sellby date, they are store into new table llx_product_lot that track all lots. All other table keep only the lot number and all properties specific to lot are into llx_product_lot.

**Comment by BebZ** [comment]
Does it mean the rowid of product_batch table "lot number" is a fk_ on the product lot table ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
