### ISSUE TITLE
Feature Request : Command_add_delivery_address ?

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#6170]
# Feature Request

When you choose a thirparty or contact/adress for delivery contact, it could be nice to "add" it also on the PDF and on the llx_commande table to check if it is a specific address to deliver...

On the french forum there is someone speaking about an hidden option 
commande_... or propale_add_delivery_address
http://www.dolibarr.fr/forum/12-howto--aide/17610-seconde-adresse-de-livraison#56943

I checked and it doesn't exist on https://wiki.dolibarr.org/index.php/Setup_Other#List_of_known_hidden_options

## Use case
When you choose a third customer for invoicing and another one for receiving the products, it could be nice to display it on "lists of shipments", pdfs, to inform the warehouse.

**Comment by aljawaid** [comment]
That makes sense.  Maybe allow an extra address per company/contact to be set as a 'delivery' address and then have a hidden option to switch the company address to the contact address.  Separate switch for billing (invoice) and a separate switch for shipments (deliveries) which show on the related pdfs.

**Comment by GheeEasy** [comment]
I am struggeling with exactly the same issue. Would be great if you can mark added contacts as delivery/invoice/etc... address and that the corresponding pdf uses this address

**Comment by cun** [comment]
I'm still struggling wth this issue. The Shipments screen takes the postcode from the invoice address as default, when it should use the delivery contact address.... this makes it difficult for anyone tracing the delivery of a shipment as the postcode is completely the wrong one.
