### ISSUE TITLE
Create master branch

### ISSUE THREAD

**Issue by gnovaro** [Dolibarr/dolibarr#6175]
# Feature Request
Create master branch for current stable version

**Comment by laudeco** [comment]
Why do you want create a master branch? @eldy creates branches for each version. Since we have to maintain multiple versions, it's more logical to work like that.

Our master branch = develop branch.

**Comment by gnovaro** [comment]
Normally the master branch has the last stable version or the current version.

**Comment by laudeco** [comment]
Totally agree, you can also rename development to master on your local repository ;)

Not seriously it's an option, but it's 'just' another naming convention to follow.
I don't have preference if the owner decides to change I follow the new rules
