### ISSUE TITLE
Replace NuSOAP

### ISSUE THREAD

**Issue by gnovaro** [Dolibarr/dolibarr#6178]
# Bug
NuSOAP don't support newer php version generates warnings to for deprecated code.

## Environment
- **PHP**: 5.3+

Implement php Soap Native Client

**Comment by rdoursenaud** [comment]
I'm all in favor for it.
We already started discussing this at #2973 and this would make one less dependency to care for at #3351.

**Comment by rdoursenaud** [comment]
Want to give it a go? Show me the code ;)

**Comment by BebZ** [comment]
Do you have any successful examples of other libraries than NuSoap implemented ?
We are looking for replacing NuSoap with something else... because with our usage (more than 2 requests per second, SOAP instructions doesn't reach our other VM / server...)
@Darkjeff @kevins62
