### ISSUE TITLE
Bug: Page 1 of ventilation changes order if returned from other page

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#6183]
# Bug
The first time we get the "A ventiler" page, the lines are ordered by creation date (I think). If we go to page 2, then come back to page 1, we get other lines, with another order.

## Environment
- **Version**: 4.0.2
- **Module**: Advanced accountability
- **URL(s)**: 
/htdocs/accountancy/customer/list.php?mainmenu=accountancy&leftmenu=accountancy_dispatch_customer
/htdocs/accountancy/customer/list.php?page=0&sortfield=f.datef,%20f.facnumber,%20l.rowid&sortorder=DESC

## Expected and actual behavior
The order should not change when we commute between pages. The second should be displayed already at first time.

## Steps to reproduce the behavior
Form lateral menu, select "A ventiler". Select page 2, then page 1.

## [Attached files]
![ventilation1-premier](https://cloud.githubusercontent.com/assets/5154580/21236189/534954c8-c2fa-11e6-8805-d030690a2df6.png)
![ventilation1-suivant](https://cloud.githubusercontent.com/assets/5154580/21236204/5f7769f6-c2fa-11e6-971a-1f92a210692d.png)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
