### ISSUE TITLE
/fourn/commande/info.php?id=ORDERNUMBER

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#6188]
Since 4.0 and this commit 
https://github.com/Dolibarr/dolibarr/commit/b9ffc18c27c89554be436ef9ea3bf77257687677
Logs written in supplier CARD 
fourn/commande/card.php
 are not recorded anymore...
/fourn/commande/history.php?id=4022
has been replaced by : 
/fourn/commande/info.php?id=4022
![screenshot 2016-12-17 at 09 31 59](https://cloud.githubusercontent.com/assets/3694135/21285549/e194b118-c43b-11e6-8902-e7e3a46abf26.png)

Will we re display it like it was before or doest it have to be re-integrated uder the board ?
![screenshot 2016-12-17 at 09 35 41](https://cloud.githubusercontent.com/assets/3694135/21285562/44e4d518-c43c-11e6-813c-02ca0d79fba3.png)

**Comment by eldy** [comment]
Are you sure you enable the event to be logged into the setup of agenda modules ?
