### ISSUE TITLE
Bug: Random -1 shown in Project list

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6209]
# Bug
Page: http://dolibarr.local/projet/list.php?leftmenu=projects&mode=mine&search_status=1
## Environment
- **Version**: 3.9.4

![captura de pantalla 2016-12-22 a las 16 33 53](https://cloud.githubusercontent.com/assets/168744/21430706/82c9ec66-c864-11e6-8b12-33f4c17f66a4.png)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
