### ISSUE TITLE
Decrease real stocks not working direct invoice

### ISSUE THREAD

**Issue by SBA18** [Dolibarr/dolibarr#6213]
When I make a direct invoice for a customer, the stock is not decrease automatically.

# Bug
[*Short description*]

## Environment
- **Version**: [*5.0.0beta*]
- **OS**: [*windows 10*]
- **Web server**: [*Xampp*]
- **PHP**: [*5.6.24*]

**Comment by simnandez** [comment]
Have you correctly configured the stocks module? Note if you have activated the productbatch module the decrease of stocks made only into shippments

**Comment by SBA18** [comment]
Thank you for your response, yes I correctly done but as normal dolibarr make this auto when you activate the module. I try in default mode and try to configure. but not working.

**Comment by simnandez** [comment]
I close this issue, because is not reproducible in maintened versions
