### ISSUE TITLE
New subscription URL not working

### ISSUE THREAD

**Issue by SBA18** [Dolibarr/dolibarr#6214]
The URL for New subscription redirect me all time to the list of subscription. Can make new subscription for members.

# Bug
[*Short description*]

## Environment
- **Version**: [*5.0.0beta*]
- **OS**: [*Windows 10*]
- **Web server**: [*Xampp*]
- **PHP**: [*5.6*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*http://*****/adherents/list.php?leftmenu=members&statut=-1,1&mainmenu=members*]

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
