### ISSUE TITLE
New : add country area

### ISSUE THREAD

**Issue by defrance** [Dolibarr/dolibarr#6216]
Propose to create a new dictionnary : country area (europa, sud america, asia, ...)
new table llx_c_country_area
new key on llx_country : fk_country_area
displayed as additionnal info on country
usage : for statistic feature

**Comment by gnovaro** [comment]
Maybe llx_continent sound better for me.
llx_country : fk_continent

**Comment by gnovaro** [comment]
I think we use ISO for continent code for example: South America is "SA"
http://www.countrycallingcodes.com/iso-country-codes/
List of countries by continent code
https://www.drupal.org/files/issues/location_continent.txt

**Comment by defrance** [comment]
👍 good idea
