### ISSUE TITLE
Images not added to Emailing (dolibarr 4.0.2)

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#6217]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
When you add an image to a emailing the email does not contain the image but the html code 
<img alt="" src="/doli40/viewimage.php?modulepart=medias&file=image/xxx.jpg"
style="height:300px; width:405px" /><br />

## Environment
- **Version**: 4.0 and more
- **OS**: all
- **Web server**: apache
- **PHP**: 5.6
- **Database**: mysql
- **URL(s)**: 

## Expected and actual behavior
In previous versions (3.9) we had a correct html code like 
<img alt="" src="cid:fa576579502deefd1b662edb8f2108ba" style="height:300px;
width:405px" /><br />

## Steps to reproduce the behavior
Create an emailing with embedded image. It shows right in emlaing tool, but when sending emailing, image is lost (view source of received email)

## Suggested implementation
Problem is :+1: 
since dolibarr 4.0, images uploaded by fckeditor are stored in <document>/media and no more in <document>/fckeditor. (path seems to be renamed by migration)
In class Cmailing  we check if there are images by based on $conf->fckeditor->dir_output, 
This value is initialised in class conf.class.php by the loop  $this->$module->dir_output	= $rootfordata."/".$module; 
and so it contains allways <document>/fckeditor instead of <document>/media

## Suggested steps
adding an overwrite of this constant as for other modules with 
// Module fckeditor
$this->fckeditor->dir_output = $rootfordata."/medias";

**Comment by eldy** [comment]
With dolibarr 4.0, images are stored into /media. Yes.
But the url that point to them should be something like
src="/dolibarr_4.0/htdocs/viewimage.php?modulepart=medias&amp;entity=1&amp;file=image/myimagesforemailing/dolicloud_logo_white.png" 

so with "medias" in module part. Do you have this in your URLs ?

**Comment by jpyrat** [comment]
I confirm the bug.
When I send an emailing with Dolibarr 4.0.4, the parth to the images is something like : 
src="/viewimage.php?modulepart=fckeditor&file=image/IMG_8448.JPG"

and it doesn't contains the domain name : mail clients can't find the image because its relative path, not absolute :(

**Comment by jpyrat** [comment]
I've just tested with the full domain, and it can't work for an emailing because the images is not displayed, but the logon :(

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug
