### ISSUE TITLE
Bug: Functionality is no longer usable

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6235]
# Bug

## Environment
- **Version**: 5.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.29-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.28-MariaDB-0+deb8u1
- **URL**: /comm/mailing/card.php?id=129

## Report
Functionality is no longer usable within a javascript popup. We can't do any  more copy-paste.

**Comment by eldy** [comment]
Which Functionality ?

**Comment by grandoc** [comment]
To copy and paste substitutional variables

**Comment by rdoursenaud** [comment]
Still unclear to me…

**Comment by grandoc** [comment]
The "Available substitution variables" are no more available...because within a java script windows...
can't do copy

**Comment by atm-maxime** [comment]
This issue is old and has probably been fixed since then. Please reopen if needed and give us more details.
