### ISSUE TITLE
Bug: Mail server malfunction

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6238]
# Bug

## Environment
- **Version**: 4.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.2.11 (Win32) PHP/5.3.0
- **PHP**: apache2handler 5.3.0
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/admin/mails.php

## Report
Serveur disponible à l'adresse mail.toto.fr sur le port 25
Échec de l'envoi de l'email (émetteur=erp@toto.fr , destinataire=contact@atoo-net.com)
Too much recipients in to:

**Comment by ptibogxiv** [comment]
same bug in 5.0 RC1

**Comment by jerash** [comment]
confirmed with 5.0rc1 here too

**Comment by Darkjeff** [comment]
This problem : htdocs/core/class/CMailFile.class.php
uncomment 484 to 515
the problem is the constant : MAIL_MAX_NB_OF_RECIPIENTS_IN_SAME_EMAIL
I try to add manually the constant, but it doesn't work  so I uncomment the code and now I can send email

**Comment by jerash** [comment]
@Darkjeff effectively commenting the checks makes the email sending work for me too.
So obviously something is wrong with MAIL_MAX_NB_OF_RECIPIENTS_IN_SAME_EMAIL use

**Comment by hregis** [comment]
https://github.com/Dolibarr/dolibarr/pull/6265
