### ISSUE TITLE
Bug: Project Module - Tasks visibility and user actions not managed properly

### ISSUE THREAD

**Issue by bgenere** [Dolibarr/dolibarr#6241]
# Bug

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 5.6.29
- **Database**: MySQL or MariaDB 5.5.5-10.0.28-MariaDB
- **URL**: /projet/card.php

## Report
I need to use this module as a basis to manage cultivation tasks in Vineyard. Before extending the existing features, I like to understand fully the existing.

I made some tests to find out how non admin users could use this module to participate to projects. In the same time I am updating the user documentation for the project module with my findings.

I find out that if you are a normal user with default rights on the module you could not see tasks you are allocated on and neither enter time spend on these tasks.

You could see the details of conditions tested in the table I am trying to set-up, see the link below :
https://wiki.dolibarr.org/index.php/Module_Projects#Project_visibility_and_user_actions

Let me know if something is wrong in my approach. May I suggest that before we fix theses issues, we build the proper table of what the behavior should be.

**Comment by eldy** [comment]
Should be fixed now with f185a09693859720e85501d9613fcdae52e92dce and 3a2f44adaca76269c8883461e554e1c27deb377d

**Comment by bgenere** [comment]
Just tested the patch and yes it's solved it.
