### ISSUE TITLE
Bug: Proposal Invoice Button Not Working

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6242]
# Bug
When clicking on the button 'Mark as Invoiced' after agreeing a sales quote nothing happens.  The page seems set with url `/comm/propal/card.php?id=5&action=classifybilled&socid=52` but the status stays as **'Agreed (Not Invoiced)'**

## Environment
- **Version**: 4.0.3

**Comment by rdoursenaud** [comment]
[Redacted. My mistake.]

Could not reproduce on a vanilla 4.0.3 install.
