### ISSUE TITLE
Bug: Module Agenda - Vue liste avec filtre "Événements affectés à"

### ISSUE THREAD

**Issue by TiffC31** [Dolibarr/dolibarr#6243]
Les événements qui ont un propriétaire mais qui n'ont pas d'enregistrement dans la table llx_actioncomm_resources n'apparaissent pas dans la liste des résultats si le propriétaire est sélectionné avec le filtre "Événements affectés à".

La requête exécutée est:
```
SELECT s.nom as societe, s.rowid as socid, s.client, a.id, a.label, a.datep as dp, a.datep2 as dp2, a.fk_user_author,a.fk_user_action, a.fk_contact, a.note, a.percent as percent, c.code as type_code, c.libelle as type_label, sp.lastname, sp.firstname 
FROM llx_c_actioncomm as c, llx_actioncomm as a 
LEFT JOIN llx_societe as s ON a.fk_soc = s.rowid 
LEFT JOIN llx_socpeople as sp ON a.fk_contact = sp.rowid, llx_actioncomm_resources as ar 
WHERE c.id = a.fk_action AND a.entity IN (1) 
AND ar.fk_actioncomm = a.id 
AND ar.element_type='user' 
AND ((ar.fk_element = 1108 OR (ar.fk_element IS NULL AND a.fk_user_action=1108))) 
ORDER BY a.datep DESC
```
Cette requête est générée dans le fichier _htdocs/comm/action/listactions.php_ à la ligne 172.
C'est la jointure gauche qui contient l'erreur car les deux conditions _ar.fk_actioncomm = a.id_ et _ar.element_type='user'_ ne sont pas remplies.

En remplaçant la requête les événements sont affichés:
```
SELECT s.nom as societe, s.rowid as socid, s.client, a.id, a.label, a.datep as dp, a.datep2 as dp2, a.fk_user_author,a.fk_user_action,
a.fk_contact, a.note, a.percent as percent, c.code as type_code, c.libelle as type_label, sp.lastname, sp.firstname  
FROM llx_c_actioncomm as c, llx_actioncomm as a  
LEFT JOIN llx_societe as s ON a.fk_soc = s.rowid  
LEFT JOIN llx_socpeople as sp ON a.fk_contact = sp.rowid 
LEFT JOIN llx_actioncomm_resources as ar ON ar.fk_actioncomm = a.id  
WHERE c.id = a.fk_action AND a.entity IN (1) 
AND ((ar.fk_element = 1108 AND ar.element_type='user') OR (ar.fk_element IS NULL AND a.fk_user_action=1108))
ORDER BY a.datep DESC
```

**Comment by eldy** [comment]
When record is not visible on the list view, is it visible on the month view ?

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?
