### ISSUE TITLE
Bug: Add Dispatch Location Line Does Not Work

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6254]
# Bug
We cannot dispatch stock into different warehouses form the supplier order as the button (green circle does not work) - clicking on the button does nothing.  At the same time, the language translation seems to be missing (red circle).

## Environment
- **Version**: 4.0.2 + 4.0.3
- **URL(s)**: /fourn/commande/dispatch.php

![dispatch](https://cloud.githubusercontent.com/assets/10233708/21749494/3bd34c4a-d597-11e6-8399-0a8735e3e9ce.png)

**Comment by fappels** [comment]
@aljawaid if you already have dispatched QTY 6 = QTY 6 ordered you can not dispatch anymore.
Maybe edit your bug into 'translation missing for AddStockLocationLine in supplier dispatch'

**Comment by aljawaid** [comment]
Sorry the screenshot shows the wrong figures as I did it after I had dispatched that order.

The problem applies when trying to add a stock location where QTY dispatched = 0

**Comment by BebZ** [comment]
Can't reproduce on 4.0.2

Hubert ANDRIOLO. FM MEDICAL. 0623101731

**Comment by aljawaid** [comment]
I noticed with the batch module enabled it works and the translation string is fine too.

I will try without the batch module again shortly and get back to you.

**Comment by aljawaid** [comment]
It works!  The user needs to reduce the quantity to be able to add a new dispatch line.

The translation string is missing so I have found and added that into a PR to make it easier for users.

#6276
