### ISSUE TITLE
Bug: Warning: Creating default object from empty value in /home/httpd/vhosts/.../compta.atoo-net.com/httpdocs/core/actions_sendmails.inc.php on line 340

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6270]
# Bug

## Environment
- **Version**: 5.0.0-rc1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.29-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.28-MariaDB-0+deb8u1
- **URL**: /admin/mails.php?action=test&mode=init

**Comment by farostegui** [comment]
Is there any solution to this issue? I am facing the same problem with myModuleIndex.php when trying to list draft orders. Please if any one has a solution on this could please send me an e-mail to "Francisco.Arostegui@aflicss.com" I will really appreciate it. Thank you in advance for your help and support.
