### ISSUE TITLE
Bug v5.0.0RC1 not decreasing real stocks for orders, shipment or direct invoices automatically

### ISSUE THREAD

**Issue by SBA18** [Dolibarr/dolibarr#6281]
Hi,

I'm testing the 5.0 RC1 and when I make a order or direct invoicing the stock is not decreasing automatically when a shipment is closed or when I make a direct invoice for a customer.

Thanks.

Environment

Version: 5.0.0RC1
OS: Windows 10 with Xampp webserver
Web server: Apache/2.2.22
PHP: 5.6
Database: MySQL 5.6

**Comment by eldy** [comment]
Go into setup of module stock.
What did you choose as option for "decrease stock" ?

**Comment by SBA18** [comment]
Thank you for your quick response.

First I didn't choose any option because the default setting automatic as the message above the setting telling me.
After I enable to Yes decease stock on shipping closed. And it works only when I make an order and after make a shipping.  but if I process direct invoice nothing happen. I can't choose 2 options to make Yes like(on shipment closed and validated invoice).

So maybe I miss something you can help me.

Thanks.

**Comment by marcosgdf** [comment]
This behaviour looks OK to me

**Comment by BebZ** [comment]
You already opened a bug for this, 
https://github.com/Dolibarr/dolibarr/issues/7002
and it is a feature request that can't be fulfilled. 
We cannot permit to choose "manual decreasing of stocks" 
and  decrease of stocks when direct invoicing

As far as I know... 
maybe it could be possible, but you can still close this request and stick to the previously created.
