### ISSUE TITLE
Bug: lang module doesn't load

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6282]
# Bug
If the module is not activated. The module name doesn't load.

## Environment
- **Version**: 4.0.0
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: /admin/modules.php

## Expected and actual behavior
I've got a some externals modules.
When I disable one of them the name, his name doesn't display properly in the page /admin/modules.php.
Instead of loading the text (in the module folder langs) Modulexx0001Name = My module name  (xx is an unused module number : https://wiki.dolibarr.org/index.php/List_of_modules_id) it's display the value : 
`$this->name = preg_replace('/^mod/i', '', get_class($this));`

So, is it a normal behavior because the module is not active ? or a bug i don't know...

## Steps to reproduce the behavior
Disable a module.

tks

**Comment by rdoursenaud** [comment]
Can't reproduce.

Could you first upgrade to the latest 4.0.3.

Have you considered that the bug might be in the module itself? Are all modules affected?

**Comment by dolibarr95** [comment]
Hello

You're right everything is ok know (still 4.0.0). The error was here (in the module) :
`$this->langfiles = array("langfiles@anothermodule");` (in this case the lang files loads only if module is activated)
instead of :
`$this->langfiles = array("anothermodule@anothermodule");`

tks
