### ISSUE TITLE
No field to add the hourly cost (`htm`) to a project_task_time.

### ISSUE THREAD

**Issue by tarrsalah** [Dolibarr/dolibarr#6283]
# Bug
No field to add the cost (`htm`) to a project_task_time.
## Environment
- **Version**: 5.0.0-rc1
- **OS**: Centos 7
- **Web server**: Apache 2.4
- **PHP**: 5.6
- **Database**: MariaDB 5.7
- **URL(s)**: /projet/tasks/time.php?id=9&withproject=1

## Expected and actual behavior
When you add a new consumed time to a task, there is no field to enter hourly rate, so it will be always `0`.

**Comment by eldy** [comment]
The hourly rate is not entered when you enter time but on the user card. Each user can have only one hourly rate.
