### ISSUE TITLE
Bug: The page index.php has an error

### ISSUE THREAD

**Issue by jmsandovalp** [Dolibarr/dolibarr#6300]
The index.php has an error, this error appears when the user that access has this permission disactivated:
Extend access to all third parties (not only those linked to user). Not effective for external users (always limited to themselves).

And obviously this user is asigned like Sales representatives in a customer.

Dolibarr has detected a technical error.
This information can be useful for diagnostic:
Date: 20170118093812
Dolibarr: 4.0.3
Level of features: 0
PHP: 5.6.11-1ubuntu3.3
Server: Apache/2.4.12 (Ubuntu)
OS: Linux AIMECLOUDv 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

Requested Url: /dolicemsa/index.php?mainmenu=home
Referer: http://cloud.dolibarrmexico.com:88/dolicemsa/index.php
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT count(sp.rowid) as nb FROM llx_socpeople as sp OUTER JOIN llx_societe as s ON sp.fk_soc = s.rowid OUTER JOIN llx_societe_commerciaux as sc ON s.rowid = sc.fk_soc WHERE sc.fk_user = 33 AND sp.entity IN (1)
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OUTER JOIN llx_societe as s ON sp.fk_soc = s.rowid OUTER JOIN llx_societe_commer' at line 1

Dolibarr 4.0.3

**Comment by marcosgdf** [comment]
Does it happen with 5.0?

**Comment by jmsandovalp** [comment]
No, it doesn´t happen anymore.

This error was resolved in the version 5.0.3

Thanks.
