### ISSUE TITLE
Bug v5.0.0RC1 - no mail sent SMTP/SMTPS socket library or PHP mail function

### ISSUE THREAD

**Issue by AlainRnet** [Dolibarr/dolibarr#6302]
# Bug
No mail sent in test section or from an invoice.
Red message displays on right top corner :
"Failed to send mail (sender=NAME , receiver=EMAIL@DOMAIN.COM)
Too much recipients in to: "

## Environment
- **Version**: 5.0.0-rc1
- **OS**: Linux lighthouse.easygiga.com 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64
- **Web server**: Apache
- **PHP**: 5.6.26
- **Database**: MySQL or MariaDB 5.5.5-10.0.27-MariaDB
- **URL(s)**: ???

## Expected and actual behavior
I want to send an invoice by email and it doesn't work.
I try to send in Setup -> E-mails section and it doesn't work too.
My "Dolibarr test" (5.0.0-rc1) is on the same server as my dolibarr in production (4.0.3)

## Steps to reproduce the behavior
create an invoice and try sending by email.
or : Setup -> E-mails -> Test sending

**Comment by SBA18** [comment]
Yes I have the same problem for me. Testing this RC version I couldn't sent any mail or notification.

**Comment by eldy** [comment]
Should be fixed with 5.0.0-rc2. Can you confirm ?

**Comment by SBA18** [comment]
Yes this issue is fix I'd tested in RC2. 

Thanks.

**Comment by AlainRnet** [comment]
I confirm too, many thanks.
