### ISSUE TITLE
German Accounting SKR03/04

### ISSUE THREAD

**Issue by rongworks** [Dolibarr/dolibarr#6303]
# Feature Request
Accounting template for German accounting (SKR03/SKR04)

## Use case
German accounting for invoices, expenses etc.

## Suggested implementation
Add german accounts SKR03/04 to default accounts in:
  * llx_accounting_account
  * llx_accounting_system

## Suggested steps

1. Write/edit migration for 
  * llx_accounting_account
  * llx_accounting_system

**Comment by rongworks** [comment]
For my use case, I already integrated a SKR03 accounting version to my instance of dolibarr.
I've attached my tables (SQL).
[accounting_SKR03_dolibarr_example.zip](https://github.com/Dolibarr/dolibarr/files/718742/accounting_SKR03_dolibarr_example.zip)

I could try a pull request, but I don't find the corresponding code in the repo for (accounting advanced)/db-migrations.

**Comment by mwelters** [comment]
We are currently reviewing/sorting  Data to be able to contribute SKR04 in a short while.

**Comment by SmetsysOver** [comment]
Can you estimate approximately when the accounting template (SKR04) is available?

**Comment by mwelters** [comment]
Hi SmetsysOver,

good reminder...
I just pushed https://github.com/mwelters/dolibar-skr
it is the unchecked raw data as CSV and SQL for SKR03 and SKR04

BUT BE AWARE:  no bookkeeper looked over it, no laywer checked it.

We compiled it from different sources. We are very positive it is nearly complete.

Maybe someone can send dokumentation how to build the mentioned migrations... then we will provide this also someday.

Markus

**Comment by mwelters** [comment]
Sorry, forgot to mention: @rongworks Data is included for completeness

**Comment by mwelters** [comment]
Ok, I checked source tree for migrations and will provide code to be merged  hopefully in 8.0 or maybe before...

**Comment by mwelters** [comment]
eldy merged 4 commits into Dolibarr:develop from mwelters:develop an hour ago

https://github.com/Dolibarr/dolibarr/pull/8954/commits
