### ISSUE TITLE
Bug 5.0 RC1 - multi currency and supplier order

### ISSUE THREAD

**Issue by ChristopheRaoult** [Dolibarr/dolibarr#6308]
# Bug
when creating a supplier  order with the multi currency available.
By adding a free product with a price in the devise and a quantity of it , the order is pretty good.
when creating the order with the muscadet templates, the order is not good.

1 - the order is generated with the currency of the company and not of the one of the supplier.
There is always the note "Montants exprimes en  in Euros" and it should be in thecurrency of the supplier.
2 - there is a mismatch between the PU used and the total price .
One refer to the PU in the devise and the total price is in euros.
we can arrive with a PU in the devise the quantity and the total not follow PU x Qty = Total

## Environment
- **Version**: 5.0 RC1
- **OS**: 	Linux imu388 3.10.55-imu #1 SMP Thu Sep 18 10:35:23 CEST 2014 x86_64]
- **Web server**: Apache
- **PHP**: 5.5.23
- **Database**: mysql ver 14.14 distrib 5.5.37

## Expected and actual behavior
when a curracy is enable and given to  a specific supplier or client, all information displayed and generated are inside this currency.

## Steps to reproduce the behavior
Enable multi currency 
Create a supplier
create an invoice with one currency choosen other than defaut one
Add a free product by entering the PU in the choosen curency
Generate Muscadet order.
[(PROV1).pdf](https://github.com/Dolibarr/dolibarr/files/719145/PROV1.pdf)
![c1](https://cloud.githubusercontent.com/assets/24266277/22147179/b872a43e-df07-11e6-8db8-58b25ca57cfc.PNG)

**Comment by marcosgdf** [comment]
I tested it and I no longer find the problem in 5.0.4

**Comment by webartis** [comment]
still there in 6.0.3 ;)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
