### ISSUE TITLE
Prices including VAT support

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#6311]
# Feature Request
Fully implement entering unit prices with or without VAT for each and every document type Dolibarr supports.

## Use case
Many businesses "think" their prices including VAT. Especially in the B2C realm. Allowing them to enter, review and display (print) prices including VAT saves the hassle of converting back and forth for both the user and the customer.

## Suggested implementation
There seem to be early dirty work relying on an undocumented global constant ```$inputalsopricewithtax```.
Scrap it completely in favor of a better design relying on runtime configurable flags.
Make sure values are computed correctly in the unused field. The value excluding VAT remains the reliable one we use for further computations so there should not be any unforeseen side-effects.

## Suggested steps
- [ ] Find a suitable place for adding a global setting to optionally add:
    - [ ] Input unit prices including VAT
    - [ ] Print unit prices including VAT
- [ ] Implement such settings
- [ ] Dynamically compute and display the other field's unit price (JavaScript).
- [ ] Implement printing unit prices including VAT on:
    - [ ] PDF documents
    - [ ] ODF documents

**Comment by rdoursenaud** [comment]
I have a hard time finding a suitable place in Dolibarr UI for this rather global setting.
I'd prefer not to replicate the setting on each supported module.
I was thinking of "Setup > Display" for the input field setting but I don't think this is a good place for the printing setting.
Any ideas?

**Comment by prietojc** [comment]
Yes, it's old, but never too late. Thanks **rdoursenaud** by your explanation: 

> There seem to be early dirty work relying on an undocumented global constant $inputalsopricewithtax.

This issue seems to be usefull, by the way I did a small hook to add this feature:

```
function doActions($parameters, $object, $action) 
{ 
    global $conf,$langs, $db, $user;
		
    if($parameters['currentcontext']=='propalcard' || $parameters['currentcontext']=='ordercard' || $parameters['currentcontext']=='invoicecard')
    {
	global $inputalsopricewithtax;
	$inputalsopricewithtax=1;
	$pu_ttc = price2num(GETPOST('price_ttc'), 'MU');
	if(($action=='addline' || $action=='updateline') && $pu_ttc!=0)
        {
	        $tva_tx = GETPOST('tva_tx');
		$pu_ht = price2num($pu_ttc / (1 + ($tva_tx / 100)), 'MU'); // $pu_ht must be rounded according to settings
		$_POST["price_ht"]=$pu_ht;
	}
    }
}
```
