### ISSUE TITLE
ODT templates od interventions, contracts

### ISSUE THREAD

**Issue by pat15** [Dolibarr/dolibarr#6312]
# Feature Request
Allow create and use ODT templates on module: interventions, contracts,

**Comment by atm-maxime** [comment]
Has been done on contracts.
Still have to work on interventions

**Comment by boardnick0815** [comment]
Hello atm-maxime,

could you please tell us how far the development process is for odt templates on the module interventions?

I would really appreciate if we could use odt templates for interventions.

Thank you very much!
Aaron

**Comment by boardnick0815** [comment]
Hello atm-maxime,

As far as i can see it is still not implemented in version 11.0.0.
Is this still active or has the "odt template project for interventions" been given up?

Thank you very much!
Aaron

**Comment by atm-maxime** [comment]
Nothing is given up, there's just no one in the community who picked this up...

**Comment by boardnick0815** [comment]
OK, that sounds fine. Thanks for your fast reply!
