### ISSUE TITLE
5.0rc2 php 7.1 Apache error. Also not loading project page

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#6316]
[20-Jan-2017 19:55:29 Europe/Madrid] PHP   1. {main}() /Applications/MAMP/htdocs/dolalfa/projet/tasks/list.php:0
[20-Jan-2017 19:55:37 Europe/Madrid] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /Applications/MAMP/htdocs/dolalfa/projet/element.php:820
Stack trace:
#0 {main}
  thrown in /Applications/MAMP/htdocs/dolalfa/projet/element.php on line 820

**Comment by gnovaro** [comment]
Current versions do not support PHP 7 yet, there are likely to be exceptions, unmanaged. Deprecated code , and validations probs, PHP 7 is is quite moremore  scrub in its default configuration.

**Comment by braito4** [comment]
I know.

This affects also to 6.0 this why i reported. Eventually we have to face php 7.1

**Comment by gnovaro** [comment]
Maybe we can run some test tools for test compatibilty
https://github.com/sstalle/php7cc
https://github.com/Alexia/php7mar

**Comment by braito4** [comment]
I use mamp and i change the php version when it suits me. 

For this i use a copy of my database in order to know if it's save to upgrade.


This errors were the ones that i notice. Most of then its just functions that changed the way to writing down on php 7.1. So take care of them it's "easy"


The complicated ones are the false postives, like the ones that @rdoursenaud reported the last time (migration to 7.0)

**Comment by rdoursenaud** [comment]
FWIW some PHP 7.1 tests are now running on our Travis-CI instance (https://travis-ci.org/Dolibarr/dolibarr)
I think it would be worth it to add more checks to avoid regressions. @gnovaro maybe you'd be willing to have a go at this?
Feel free to ping me if you need more informations on how to integrate these. I've got some experience ;)
