### ISSUE TITLE
Bug: Missing translation (German) ListOfCustomers

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#6317]
# Bug

## Environment
- **Version**: 4.0.3
- **OS**: Darwin
- **Web server**: Apache
- **PHP**: apache2handler 7.0.13
- **Database**: MySQL or MariaDB 5.6.34
- **URL**: /societe/list.php?type=c&leftmenu=customers

## Report
In the file langs/de_DE/companies.lang the entry for for ListOfCustomers is missing.

Adding following line fixes the bug
ListOfCustomers=Liste der Kunden

**Comment by rdoursenaud** [comment]
Translations are managed at Transifex: https://www.transifex.com/dolibarr-association/dolibarr/dashboard/
Please consider contributing your fix there.
Thanks.

**Comment by glu000** [comment]
Thanks - will contribute there
