### ISSUE TITLE
Bug: Inconsistent handling in list view of third parties and contacts

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#6318]
# Bug

## Environment
- **Version**: 4.0.3
- **OS**: Darwin
- **Web server**: Apache
- **PHP**: apache2handler 7.0.13
- **Database**: MySQL or MariaDB 5.6.34
- **URL**: /societe/list.php?type=c&leftmenu=customers

## Report

The "Status" field in the list-view has a different behavior for third parties and contacts. For contacts it's possible to select both (active and inactive) in the search bar, for third parties only active or inactive can be selected. Following changes fixes the issue:

**_File /Applications/MAMP/htdocs/societe/list.php_**
Line 227: $search_status=-1;
Line 399: if ($search_status != '' && $search_status >= 0) $sql .= " AND s.status = ".$db->escape($search_status);
Line 839: print $form->selectarray('search_status', array('-1'=>'', '0'=>$langs->trans('ActivityCeased'),'1'=>$langs->trans('InActivity')),$search_status);

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
