### ISSUE TITLE
Bug: Supplier Price Request Missing Buttons

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6319]
# Bug
After adding a product to a supplier price request the buttons are missing.

## Environment
- **Version**: 4.0.3
- **URL(s)**: /supplier_proposal/card.php?id=1

![snip_20170121124956](https://cloud.githubusercontent.com/assets/10233708/22174645/87b66572-dfdb-11e6-9888-c15c3b50cbff.png)

**Comment by aljawaid** [comment]
Initial install: 3.8.2
Current version: 4.0.3
Upgraded on every minor/major version from the sourceforge zip

Theme: eldy

PHP: 5.5.38

**Comment by simnandez** [comment]
Works for me in a 4.0.4

**Comment by aljawaid** [comment]
- **Version:** 4.0.4
Still the same issue.  I noticed no buttons, so can't really do anything to go further.  Also noticed the search combo box has gone wrong on this page.

**Comment by eldy** [comment]
Can you in the javascript console if you have errors after a F5 ?
If not, can you see into your apache error log file for strange message ?

**Comment by aljawaid** [comment]
@eldy Thanks for replying.

The browser javascript console returned nothing.
The apache server logs returned the below:
`[Thu Feb 02 00:05:57 2017] [error] [client 79.77.253.18:51615] AH01215: PHP Parse error:  syntax error, unexpected ')' in /home/sites/domain.co.uk/public_html/workflow/core/modules/supplier_order/pdf/pdf_supporder.modules.php on line 1026: /home/sites/domain.co.uk/public_html/workflow/admin/supplier_order.php`

**Comment by aljawaid** [comment]
This seems to have worked for me from 5.0.1
