### ISSUE TITLE
Feature request: Add possibility to enter code_compta for manual cash bookings

### ISSUE THREAD

**Issue by a-schild** [Dolibarr/dolibarr#6324]
Version: 4.0.3

Currently when creating manual booking entries for the cash account, we have no way to specify the accountancy code for these bookings.

To allow the accountancy code to be entered when a new manual entry is created, I think these steps would be required:
1. Expand table bank with a new column fk_account referencinf the llx_accounting_account table
2. Show this account in the list (compta/bank/account.php)
3. Allow the account to be selected when creating and editing transactions (As show in a sample printscreen), but only when it's not a entry from another module. (compta/bank/account.php?action=addline and bank/ligne.php)
4. When taking over the bookings to the accountancy module, add the logic to use this account if specified (accountancy/journal/bankjournal.php)

Would a pull request for this new funcationality be accepted, or is there a another/better way to implent such an enchancement?

![2017-01-24 12_44_08-finanzkonto-transaktionen](https://cloud.githubusercontent.com/assets/1441009/22246147/a8460ea0-e233-11e6-8bcc-aa1d4e6ca6af.png)

**Comment by eldy** [comment]
When you make a direct entry into bank, we don't know origin of entry, so we have accounting code for bank but not for the second double entry. So i suppose that's the reason why you need this ?
But i think this accounting account should be set when using the double party accounting module available with v5 when you make the recording of bank record into the journals. It is at this moment that we should choose accounting account, isn't it ?

**Comment by a-schild** [comment]
I haven't looked into the v5 branch, but (for our customers) its more logical to say at the moment when they create the entry in the cash book what the reason (second double entry) is.
If we postpone this to the moment when we take it over into the journal, then we have to relook at each entry, search the papers for this booking and add it then.
So in fact we do the work almost double...

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
Accountancy module has improved since then.

**Comment by a-schild** [comment]
Has been implemented in the 9.x version.
Thanks
