### ISSUE TITLE
Bug: can't add a loan payment  "Column count doesn't match value count"

### ISSUE THREAD

**Issue by dauge** [Dolibarr/dolibarr#6325]
# Bug
Can't use comma in amount

## Environment
- **Version**: 4.0.3
- **OS**: Linux lrv 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.36-1+deb8u1~bpo70+1 (2016-09-08) x86_64
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: 5.6.29-0+deb8u1
- **Database**: MySQL 5.5.53-0+deb8u1
- **URL(s)**: https://vm.laressourcerieverte.com/dolibarr/loan/payment/payment.php?id=1&action=create

## Expected and actual behavior
Trying to add a loan payment with amount contain comma (','). The payment is not registered, errot message saying "Column count doesn't match value count at row 1"
Using amount containing dot ('.') instead work.

**Comment by aspangaro** [comment]
Hi,

Work in 5.0.0, apply this patch : 
[Github](https://github.com/Dolibarr/dolibarr/commit/a75000715536fbf2e8b9e11d4d535770802e60d0)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
