### ISSUE TITLE
503 error delete temporary files

### ISSUE THREAD

**Issue by nicoxygen** [Dolibarr/dolibarr#6327]
# Bug
In dolibarr 4.0.3 when you want to delete all the temporary files it leads to a 503 error

## Environment
Version: 4.0.2
OS: Linux
Web server: LiteSpeed
PHP: 5.6.28 and 7.0.14
Database: MySQL or MariaDB 10.1.19-MariaDB
URL(s):htdocs/fourn/paiement/card.php?id=...
URL(s):htdocs/fourn/paiement/info.php?id=

**Comment by rdoursenaud** [comment]
This is a webserver configuration issue. It timeouts if the cleanup takes too long, We don't have control over it expect in the prepackaged installations.

**Comment by nicoxygen** [comment]
it's not a problem of max execution time i have take 1440 and is the same problem
