### ISSUE TITLE
Bug: incomplete url link for activating new password after forgotten 

### ISSUE THREAD

**Issue by StefAngel** [Dolibarr/dolibarr#6334]
# Bug

when using forgotten password feature we get a mail with incomplete link for activating new password.
---------------
Vous devez toutefois auparavant cliquer sur le lien suivant, afin de
valider ce changement de mot de passe :
/user/passwordforgotten.php?action=validatenewpassword&username=s.giraud&passwordhash=f09b49fcbadb1cecdcade9d8e083a928
-----------------------
apparently it "forgot" the DOL_URL_ROOT ...
couldn't find in the code on which file the email is generated...

## Environment
- **Version**: 4.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.29
- **Database**: MySQL or MariaDB 5.5.5-10.0.29-MariaDB
- **URL**: /admin/system/dolibarr.php?mainmenu=home&leftmenu=admintools_info

**Comment by igolubic** [comment]
Hi @StefAngel ,
you can fix this issue doing the following:
In **user.class.php** usually located in **/htdocs/user/class/user.class.php** near the line 1656 you will se variable **urlwithroot** setting to external domain name from config file (DOL_URL_ROOT). You have to comment this line and uncoment line where you will set variable to DOL_MAIN_URL_ROOT.

Finally you will have something like this:

```
		// Define $urlwithroot
		//$urlwithouturlroot=preg_replace('/'.preg_quote(DOL_URL_ROOT,'/').'$/i','',trim($dolibarr_main_url_root));
		//$urlwithroot=$urlwithouturlroot.DOL_URL_ROOT;		// This is to use external domain name found into config file
		$urlwithroot=DOL_MAIN_URL_ROOT;						// This is to use same domain name than current

```

**Comment by StefAngel** [comment]
Thanx for fix...

it works fine.

it seems to appeared in 4.03 and is still in 5 RC2 ...

Regards.


2017-02-01 0:22 GMT+01:00 Ivan Golubic <notifications@github.com>:

**Comment by laudeco** [comment]
@eldy it's actually what has been done in #6416

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
