### ISSUE TITLE
bug: expenses reports - required field VAT block modification of accounting doc. 

### ISSUE THREAD

**Issue by dauge** [Dolibarr/dolibarr#6341]
# Bug

Can't modify an accounting doc. for required field VAT, defined à 0%

## Environment
- **Version**: 4.0.3
- **OS**: Linux lrv 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.36-1+deb8u1~bpo70+1 (2016-09-08) x86_64
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: 5.6.29-0+deb8u1
- **Database**: MySQL 5.5.53-0+deb8u1
- **URL(s)**: expensereport/card.php

## Expected behavior

For a company where  VAT is not used. 
An expenses report with accounting docs, VAT unused (displayed at 0%).
Accounting doc should be modifiable. 

## Actual behavior

When saving a modified accounting doc, save not changed and message displayed "Field 'Vat' is required".

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
