### ISSUE TITLE
Module dependency detection fails

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#6347]
# Bug
Since Dolibarr 5.0, my module's dependencies are not evaluated properly and issues an error.

## Expected and actual behavior
When enabling a module with a dependency to another module:
```php
 $this->depends = array('modMyDependencyModuleClassName');
```
Dolibarr issues the ```activateModuleDependNotSatisfied``` error telling the user that the dependency could not be found even when the dependency is available (and/or enabled).

Dolibarr 4.x and previous behave correctly by only displaying the error message when the dependency is not found or cannot be enabled.

## Steps to reproduce the behavior
Try enabling a module with a dependency to another module.

**Comment by rdoursenaud** [comment]
Issue in stable release. What a shame!
@eldy Could you please make sure the milestone is actually complete before releasing.
It feels I'm working on it for nothing :(

**Comment by rdoursenaud** [comment]
Screencast of the bad behavior:
https://drive.google.com/file/d/0B2ODG5fp26wXWWJHTUljeUF2S2s/view
Explanation:
Module ZenFusion Contacts depends on ZenFusion OAuth.
Module is present and activated but we still get an erroneous error message.

**Comment by marcosgdf** [comment]
I complained about it in #2777. As you can see per @eldy statement, it is the expected behaviour

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?
