### ISSUE TITLE
Bug: Dosen't save the new configuration of layout

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#6357]
# Bug

## Environment
- **Version**: 4.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.34
- **URL**: /auditorias/admin/ihm.php?action=edit&theme=md

**Comment by eldy** [comment]
Check that theme is not also forced on the user card.

**Comment by simnandez** [comment]
No response
