### ISSUE TITLE
BUG: The dolibarr TPV(POS) module ALWAYS adds the equivalence surcharge even if the customer has the option of equivalence surcharge in NO. 

### ISSUE THREAD

**Issue by LucasComseis** [Dolibarr/dolibarr#6366]
# Bug

The dolibarr TPV(POS) module ALWAYS adds the equivalence surcharge even if the customer has the option of equivalence surcharge in NO. 
Dolibarr should only add it if the customer to whom we are selling through the TPV (POS), has the active equivalence surcharge.

## Environment
- **Version**: 4.0.0 - 4.0.4
- **OS**: CentOS release 6.6 (Final)
- **Web server**: Apache Version: 2.2
- **PHP**:  PHP Version 5.4.45
- **Database**: Server version: 5.5.38-log MySQL Community Server (GPL)
- **URL(s)**: https://doliseis.com/comseis/

## Expected and actual behavior
Expected: 
1.Under Setup> Company, the equivalence surcharge has to be ACTIVE.
2.Customer has to be VENTAS AL CONTADO, and equivalence surcharge NOT ACTIVE. 
3.Go to TPV module and sell PRUEBA - PRUEBA product.
4. Total has to be 19€ (IVA included) because PRODUCT: PRUEBA , has selling price (IVA included ) 19€.

Actual:
1.Under Setup> Company, the equivalence surcharge has to be ACTIVE.
2.Customer has to be VENTAS AL CONTADO, and equivalence surcharge NOT ACTIVE. 
3.Go to TPV module and sell PRUEBA - PRUEBA product.
4. Total is 19.82€ (IVA included) but PRODUCT: PRUEBA , has selling price (IVA included ) 19€. So It's adding equivalence surcharge even if It's not correct because VENTAS AL CONTADO (customer) has equivalence surcharge NOT ACTIVE.

## Steps to reproduce the behavior
1.Under Setup> Company, the equivalence surcharge has to be ACTIVE.
2.Customer has to be VENTAS AL CONTADO, and equivalence surcharge NOT ACTIVE. 
3.Go to TPV module and sell PRUEBA - PRUEBA product.
4. Look at total.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
