### ISSUE TITLE
Translation problem between Dolibarr 3.9.3 and 4.0.3

### ISSUE THREAD

**Issue by fred1201** [Dolibarr/dolibarr#6368]
# Bug
Translation problem between Dolibarr 3.9.3 and 4.0.3 in the mailing module lang file fr_FR

## Environment
- **Version**: 4.0.3
- **OS**: LINUX
- **Web server**: Apache
- **PHP**: 5.6.30

## Expected and actual behavior
I upgrade Dolibarr from 3.9.0 to 4.0.3 and discover in the mailing module i lose some translation . See print screen in the attached file
The probleme is the same if i make a clean install

## Steps to reproduce the behavior
Afer a check in the mails.lang  file in the 3.9.0 version i have for exemple the key MailingModuleDescContactsByFunction=Contacts de tiers (par poste/fonction) 
If i check the file in 4.0.3 the key is missing.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![print screen-3 9](https://cloud.githubusercontent.com/assets/25524020/22583674/70281b04-e9ee-11e6-9c7c-552722368e4f.png)
![print screen-4 0 3](https://cloud.githubusercontent.com/assets/25524020/22583673/70280402-e9ee-11e6-817e-956872c33ca9.png)

Steps to temporary fixe the problem

I copy the file from 3.9 to 4.0.3 and the translation was fixed.
Is it a problem when we raise the translation file or is the key version 4.0.3 disapear from the 4.0.3 version.

Please advise.

Thanks

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
