### ISSUE TITLE
New: Add contact tab to an event (action)

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#6373]
# Feature Request
It would be very helpful to attach more than one contact to events as it is possible for projects.
With 5.0 it's only possible to attach one contact to an event (action)

## Use case
Assign more than one contacts to events would allow to better organize customer events, meetings, trainings, ...

## Suggested implementation
Same implementation which is used for attaching contacts to projects

**Comment by choybe** [comment]
Yes in deed i miss this option urgently. Is there any reason why it is not yet applied in dolibarr 6.0.* ?

**Comment by glu000** [comment]
This is solved in dolibarr 7
