### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tetus** [Dolibarr/dolibarr#6378]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
[Cash Account balance on page 2 not accurate]

## Environment
- **Version**: [5.0.0rc2]
- **OS**: [Linux]
- **Web server**: [Linux web 3.8.2-grsec #6 SMP Mon Apr 22 15:03:58 ART 2013 x86_64]
- **PHP**: [PHP 5.6.25]
- **Database**: [MySQL or MariaDB 5.5.24-log]
- **URL(s)**: [http://aeroatelier.com/dolibarr/htdocs/compta/bank/bankentries.php?id=18]

## Expected and actual behavior
[Checking account balance from Bank menu, lands on page 2 of transaction list. Balance shown is not accurate. When selecting more than 25 lines to see all transactions on one page balance is correct]

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
