### ISSUE TITLE
Bug: can't edit Bank account in Template invoice

### ISSUE THREAD

**Issue by dauge** [Dolibarr/dolibarr#6381]
# Bug

## Environment
- **Version**: 4.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.29-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.54-0+deb8u1
- **URL**: /dolibarr/compta/facture/fiche-rec.php?id=7

## Report

There's no edit button on bank account line in template invoice

**Comment by eldy** [comment]
Seems fixed with 5.0beta
