### ISSUE TITLE
Bug: Browse third party liste (next / prev button) issue

### ISSUE THREAD

**Issue by laussetdelon** [Dolibarr/dolibarr#6382]
# Bug
*Browse third party list (next / prev button) issue*

## Environment
- **Version**: [*4.0.4*]
- **OS**: [*Debian 8 - 32 bits*]
- **Web server**: [*Apache 2.4.10*]
- **PHP**: [*5.6.26*]
- **Database**: [*MySQL Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (i686) using readline 6.3*]
- **URL(s)**: [*http://mysite/societe/soc.php?*]

## Expected and actual behavior
*< and > button are suppose to parse item one by one in the proper order. Since 4.0.4, It doesn't*

## Steps to reproduce the behavior
*Display third party list. Pick the fist one. Click on next button. I created a list of 12 third parties, i can only parse 5 of them in a strange order. It happended on my upgraded site (from 4.0.2). I installed a fresh 4.0.4 with a fresh database. The problem occurs as well*

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
