### ISSUE TITLE
Feature Request / File attachment during estimate acceptation

### ISSUE THREAD

**Issue by ygini** [Dolibarr/dolibarr#6383]
In the estimate form, when we set the status to signed by the customer, we've a text field, but it would be interesting to also have a file attachment option.

## Use case
Customers who accepts my offers return me a signed paper or PDF as an proof en engagement. Companies need to keep track of those document.

## Suggested implementation
The status form (where we can change to signed or not signed) should be improved with an additional file attachement field (like we've for e-mails) and should be uploaded and recorded with the original estimate.

**Comment by BebZ** [comment]
👍 
maybe this attachment would also be even more practical if we could : 
copy and paste from clipboard a screen capture (we do it with the basic snipping tool)
drag and drop a file from hard drive to a specific field (java or javascript ?)...

My 2 cents

**Comment by jerash** [comment]
This exactly what i need too.
The drag'n'drop option is very convevient, and in most situations, the drop zone is also clickable so you can still choose a file to upload

**Comment by atm-maxime** [comment]
I don't know if this is going to be implemented, but in the meantime we add the file the customer send in the attached files tab...
