### ISSUE TITLE
Bug: membership tolerance delays definition not taken in account

### ISSUE THREAD

**Issue by dauge** [Dolibarr/dolibarr#6385]
# Bug

## Environment
- **Version**: 4.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.29-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.54-0+deb8u1
- **URL**: /dolibarr/index.php?mainmenu=home&leftmenu=

## Report

Defined Tolerance delay before alert on delayed membership fee at 365 days. 
All Members with subscription to receive and Subscription's end date defined are counted as late.

**Comment by eldy** [comment]
Seems fixed with 5.0beta

**Comment by dauge** [comment]
Is it possible to get a correction in next 4.0 release ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
