### ISSUE TITLE
Bug: Muscadet doesn't read MAIN_GENERATE_DOCUMENTS_WITHOUT_VAT_COLUMN

### ISSUE THREAD

**Issue by jfposi** [Dolibarr/dolibarr#6389]
# Bug
Muscadet model ( Supplier Orders) doesn't read MAIN_GENERATE_DOCUMENTS_WITHOUT_VAT_COLUMN and put the column anyway

## Environment
- **Version**: *4.0.0*

## Expected and actual behavior
It should check if MAIN_GENERATE_DOCUMENTS_WITHOUT_VAT_COLUMN is activated and dont show the column.

## TODO List
Around line 394 and 920 modify the if to check also this

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
