### ISSUE TITLE
STOCK_MOVEMENT trigger not executed for inventoring and transfering

### ISSUE THREAD

**Issue by cyberesprit** [Dolibarr/dolibarr#6392]
Is it normal for the STOCK_MOVEMENT trigger to be executed correctly when validating an invoice / credit / order but not when correcting the inventory of a product or when transferring product from one warehouse to another ?

Is not it a movement of stock?

If I am not mistaken, there is no trigger (or hook?) Executed during these two operations.

**Comment by cyberesprit** [comment]
FRENCH VERSION
-------------------------

Est-ce normal que le trigger STOCK_MOVEMENT soit bien exécuté quand on valide une facture/avoir/commande mais ne l'est pas quand on corrige le stock d'un produit ou quand on fait un transfert de produit d'un entrepôt à un autre ?

N'est-ce pas un mouvement de stock ?
D'ailleurs, si je ne me trompe pas, il n'y a aucun trigger (ou hook ?) exécuté lors de ces deux opérations.

Merci pour vos précisions.

**Comment by cyberesprit** [comment]
up ?

**Comment by eldy** [comment]
It seems in 5.0, this is correctly managed (trigger seems to be called). Please confirm after upgrade to 5.0

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
