### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#6396]
4.0.4
/product/admin/product.php
level of prices are displayed in french and english... makes it less understandable

line of translate missing  ?

The option you choose makes the form vary when you create a product

## Expected and actual behavior
It should be the same form when you create a product
independently from the option you choose in admin for level of prices, as prices should be defined AFTER creation...

## Steps to reproduce the behavior
Choose option "prix differents pour chaque client"
try to create a product, you see price proposed on creation
![image](https://cloud.githubusercontent.com/assets/3694135/22733295/75b3dd86-edf1-11e6-8e49-ee80dcf62150.png)

choose this other option
![image](https://cloud.githubusercontent.com/assets/3694135/22733334/a1349d10-edf1-11e6-9f81-29423a341c07.png)

the price field disappears
![image](https://cloud.githubusercontent.com/assets/3694135/22733356/b7960788-edf1-11e6-92ad-c4fae3f26613.png)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
