### ISSUE TITLE
Feature request : Add signature intervention PDF

### ISSUE THREAD

**Issue by SBA18** [Dolibarr/dolibarr#6398]
Hi,

Can you add a feature that allow to open and sign the intervention PDF by using for example this library : http://willowsystems.github.io/jSignature/#/about/ 

Thanks.

**Comment by laudeco** [comment]
Interesting but, why do you want to introduce this kind of library in Dolibarr, do you sign your bills before sending them ?

In which workflow do you want this feature ?

**Comment by SBA18** [comment]
Yes because I make interventions and before I invoice the customer sign. Now I have to print the PDF and when customer sign I scan and join the file. Is 3 more steps to do for technicians. I would like I open the PDF in iPad and the customer sign directly and I close the intervention and make invoice.

Maybe they can do with another library. But this feature is important and I saw many person demand in french forum. So I'm not the only one asked

**Comment by PlanPc** [comment]
Hello, also in Spain, I think this could be great feature too, anyone who uses dolibarr around the world when assisting customers in field need something like that.

Adding a time tracking to intervention will also could be great, where worker starts and stops a clock related to a task or service from some customer (something like https://toggl.com inside dolibarr, this could help in field work but also in project based works, like programming or so) since then, technicians only need intervention module to access to control times, report works and customers signs ready to invoice.

This is totally a dream also for me.

**Comment by boardnick0815** [comment]
Hello alltogether,

it really would be a great thing if a signature solution could be implemented into Dolibarrs intervention module.

In our company we use signature capture pads from Signotec (the small ones they have are inexpensive and as a big advantage you can make a legally binding signature with these kinda pads!).
Signotec also supplies an interface [https://en.signotec.com/download/sdk-api/websocket-pad-server/](https://en.signotec.com/download/sdk-api/websocket-pad-server/) between browsers <--> Pad which could maybe implemented in Dolibarr.

Best regards from Germany

**Comment by boardnick0815** [comment]
Hello alltogether,

i  would still appreciate if such a feature would be implemented.
In the meanwhile i have a Signotec Sigma signature device.

If it helps and maybe Laurent or another developer is interessted in integrating a signature solution i could provide my device as a loan.

**Comment by PlanPc** [comment]
> Hello alltogether,
> 
> i would still appreciate if such a feature would be implemented.
> In the meanwhile i have a Signotec Sigma signature device.
> 
> If it helps and maybe Laurent or another developer is interessted in integrating a signature solution i could provide my device as a loan.

There's a simple solution in the module InfraS Pack, where you can manually sign with any tactile screen in many documents, also intervention, people, etc, the sign is after printed in PDF documents also (only for infraspack document models).

Module is in dolistore.
