### ISSUE TITLE
Bug (v2) in prevelement file creation (SEPA) 

### ISSUE THREAD

**Issue by ram111** [Dolibarr/dolibarr#6404]
dolibarr 4.0.0
Related to the fixed problem on this issue:  [https://github.com/Dolibarr/dolibarr/issues/3128](url)

Same problem (and same fix needed) occurs on that very same function at the end, row_facnumber on <Ustrd> may become too long and validation fails.

`$XML_DEBITOR .='<Ustrd>'.$row_facnumber.'</Ustrd>'.$CrLf;`

**Comment by dolibarr95** [comment]
Hello
`<Ustrd>` must be 140 char max.
_Note: why don't we use Dom xml php in this function ?_
