### ISSUE TITLE
Bug: no pagination in warehouse card

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6418]
# Bug
In the warehouse module there is no pagination, all the products (more than 2800 in my case) display in the same page. In my user page the Max length for list is set to default value (50).

## Environment

- **Version**: 4.0.0
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**:  5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**:  product/stock/card.php?id=1

## Expected and actual behavior
Displays only 50 products and links to pagination but displays all products.

Tks

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by dolibarr95** [comment]
Hi
Still have no pagination in Dolibarr 6.
Tks
