### ISSUE TITLE
Bug: product import example file

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6426]
# Bug
Missing or bad information in the product import file example.

## Environment
- **Version**: 4.0.0
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: imports/import.php?step=2&datatoimport=produit_1&excludefirstline=1&separator=%2C&enclosure="

## Expected and actual behavior
For an extrafield displays the label instead of an example or the default value.

## Steps to reproduce the behavior
Create an extrafied of product. 
E.g.  :

- [ ] label: my new indice

- [ ] attribute code: indice

- [ ] type: string

- [ ] size: 5

- [ ] default value: y

- [ ] go to import product page and download the example in .csv or .xlsx

 Tks

**Comment by atm-maxime** [comment]
This is expected behaviour, not a bug. Example value is not possible so we choose to display the extrafield label.
