### ISSUE TITLE
[Question] - How see future expenses

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#6438]
Hello @eldy, 

For some weeks, I'm looking for a way to see future expense in the system.

My problem:
I don't have any open billing but I know that every septembre, I have to pay the bill of houses,... 

Question:
* How can I see in Dolibarr (without any bill)  futures expenses ? Do we have a module for that ?
* Is it a way to see my balance in 2 months ?

Thanks
L.

**Comment by dolibarr95** [comment]
hello
in Contracts/Subscriptions ?

**Comment by laudeco** [comment]
I don't see them ... how can I?

**Comment by dolibarr95** [comment]
Activate Customer Relation Management (CRM) -> Contracts/Subscriptions & displays in commercial.

**Comment by laudeco** [comment]
Ok I have it but on which url can I see how many expense are incoming?

**Comment by dolibarr95** [comment]
Sorry i don't use this module. I don't know :( more about it.

**Comment by BebZ** [comment]
You may not have a bill for it, but you can see them in this report screen, even for expenses : 
/compta/resultat/clientfourn.php?year=2017&month=2&modecompta=RECETTES-DEPENSES

for future balance it may be here, in the last column : 
/compta/bank/treso.php?account=1

I am on 3.8.2, it will maybe need some refreshment ;)

**Comment by laudeco** [comment]
Thanks to you, but I don't see the expense note and other expenses.
 This view only group billing, tva... but not the expense note by exemple

Is it possible to add it 

/cc @eldy

**Comment by BebZ** [comment]
can you post a screenshot of what you want ?

**Comment by laudeco** [comment]
![image](https://cloud.githubusercontent.com/assets/3658458/23210807/7a9e214e-f8ff-11e6-92ec-5e4bf2e1bc00.png)

In this view I want to have a view on expense note

**Comment by laudeco** [comment]
It's already the case if we use the latest expense note module.
