### ISSUE TITLE
[Security] Download files from filesystem

### ISSUE THREAD

**Issue by PostalBlab** [Dolibarr/dolibarr#6443]
# Bug
With this bug any user, regardless of the permissions, who can login to the system can download any file from the filesystem to which the php user has access to. How can i contact you to send you the details?

## Environment
- **Version**: 4.0.4 and 5.0.0 (didn't test 3.x)
- **OS**: GNU/Linux
- **Web server**: lighttpd
- **PHP**: PHP 5.6.30-pl0-gentoo (cli) (built: Feb  5 2017 08:59:18) 
- **Database**: postgresql

**Comment by rdoursenaud** [comment]
I'd be interested to have a look. Please see my GitHub profile for contact informations.
Please also forward the informations to @eldy which is our project leader.
