### ISSUE TITLE
[Security] Privilege escalation

### ISSUE THREAD

**Issue by PostalBlab** [Dolibarr/dolibarr#6445]
# Bug
Under some circumstances a user can take over the SuperAdmin account. How can i contact you to send you the details?

## Environment
- **Version**: 4.0.4 and 5.0.0 (didn't test 3.x)
- **OS**: GNU/Linux
- **Web server**: lighttpd
- **PHP**: PHP 5.6.30-pl0-gentoo (cli) (built: Feb  5 2017 08:59:18) 
- **Database**: postgresql

**Comment by rdoursenaud** [comment]
I'd be interested to have a look. Please see my GitHub profile for contact informations.
Please also forward the informations to @eldy which is our project leader.

**Comment by eldy** [comment]
@PostalBlab Thank you for your previous feeback. I fixed the bugs into 4.0 and higher.
You can send direct feedback like this to me at eldy@users.sourceforge.net
