### ISSUE TITLE
Feature Request: Ability to disabe or move global search field at top of vertical menu

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#6456]
# Feature Request

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL 5.5.52-cll-lve
- **URL**: /index.php?mainmenu=home&leftmenu=

## Report

Hope this feature request is correctly endorse, sorry if not, I´m not programmer and github is a new world for me.

In every page the search field must be mandatorily shown (Top of vertical menu). 

There is no module or any option to disable this search when it is not needed or other third party search is installed. Maybe can be moved to logout button zone?

In my humble opinion there is always more free space for a search field in that place that always can be accessed. Vertical menu is where most used options are placed.

Thank you for your attention and good work!

**Comment by atm-maxime** [comment]
I think the last versions have changed the way the search field works and now it's better.
