### ISSUE TITLE
Bugs 4.0.4

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#6462]
# Bug
Module contrat : pas de retour d'info sur le Modifier par 
Module Projet : pas de retour d'info sur le Modifier par 
Module product : impossible de supprimer l'onglet Suivi

## Environment
- **Version**: 4.0.4

**Comment by homer8173** [comment]
j'ai essayé différents noms pour supprimer l'onglet suivi du produit mais rien ne marche : 
            'product:-info',
            'product:-suivi',
            'product:-Suivi',

**Comment by atm-maxime** [comment]
This issue is old and has probably been fixed since then. Please reopen if needed and give us more details.
