### ISSUE TITLE
Bug in facture list

### ISSUE THREAD

**Issue by ayalejo** [Dolibarr/dolibarr#6470]
# Bug
[When you select the size of the paginate in facture list, lost the socid filter]

## Environment
- **Version**: [4.0.4]
- **OS**: [Windows]
- **Web server**: [Apache 2.2]
- **PHP**: [*PHP version*]
- **Database**: [Mysql 5.7]
- **URL(s)**: [htdocs/compta/facture/list.php]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[Go to one societe page, select client tag, and click in "See all the invoices". Now select in the selec box for the number of rows for page 100, you lose the societe (client) filter  ]

## Suggested implementation
[I solved it with this code

Line 857
	if ($socid != "") {
		print '<input type="hidden" name="socid" value="'.$socid.'">';
	}
]

**Comment by eldy** [comment]
This bug seems to be fixed into 5.0, so I close the bug
