### ISSUE TITLE
Bug: RSS Failure PHP7?

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6473]
# Bug
External RSS fields fail to be retrieved on homepage and in RSS module settings.

## Environment
- **Version**: 4.0.4 / 5.0.0
- **OS**: VPS Linux server.domain.co.uk 3.10.0-514.6.1.el7.x86_64 1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64
- **Web server**: Apache
- **PHP**: 7.0.16
- **Database**: MySQL or MariaDB 5.5.54-cll
- **URL(s)**: `/admin/external_rss.php` + dashboard

## Expected and actual behavior
Since moving to PHP7 on v4.0.4 and now v5.0.0 the RSS has not worked.

In the homepage, I get this error in the tooltip:
`Filed to refresh RSS flux`

In the RSS Module settings, I get this error:
`Offline - Fails to get RSS feed. Try to add constant MAIN_SIMPLEXMLLOAD_DEBUG if error messages does not provide enough information.`

After setting constant `MAIN_SIMPLEXMLLOAD_DEBUG` to `1` in Setup>Other Setup, this is the only noticeable lines I could find possibly related:
`
2017-02-28 23:28:04 INFO    84.13.148.180   RssParser::parser cache file /home/pewsedofitsc/public_html/dolibarr/documents/externalrss/temp/cb86514456de58d4b767c1eb42dfe6c3 is not found or older than now - cachedelay (1488324484 - 3600) so we can't use it.
2017-02-28 23:28:04 INFO    84.13.148.180   box_external_rss::showBox
2017-02-28 23:28:04 INFO    84.13.148.180   ModeleBoxes::showBox
`

Looking into the `dolibarr/documents/externalrss/temp/` directory I noticed there are no files.

**Comment by eldy** [comment]
Do you have php module simplexml installed ?

**Comment by aljawaid** [comment]
@eldy yes

**Comment by eldy** [comment]
Hum, strange. No way to reproduce the problem with my php7.

**Comment by aljawaid** [comment]
@eldy According to my hosts (eUKhost) `simplexml` has been installed on php7 from their side and apache has been restarted.  I still have the problem.

**Comment by aljawaid** [comment]
This issue seemed to be fixed when php was auto-updated on the server
