### ISSUE TITLE
Bug: Setup-Modules-Projects/Opportunities/Leads - Project numbering module

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#6477]
# Bug
Project numbering module - Customizable number
Shows always "Error on mask"

## Environment
- **Version**: [*5.0.0 - rc2 and 4.0.4*]

**Comment by eldy** [comment]
Can you provide a screenshot of page

**Comment by FritzBrause66** [comment]
Here it is…

[cid:image001.jpg@01D29428.640F4250]

Mit freundlichen Grüßen,

Bernd Dietz


Bernd Dietz
Geschäftsführer / Managing Director

nortus Optronic GmbH
In den Niederwiesen 4a
D-76744 Wörth am Rhein
Germany

Tel +49-7271-12990-0
Fax +49-7271-12990-19

Internet www.nortus-optronic.de<http://www.nortus-optronic.de/>
Mail info@nortus-optronic.com<mailto:info@nortus-optronic.com>

Bankverbindung / Account details
Volksbank Ettlingen eG
BIC / Swift: GENODE61ETT
IBAN: DE95 6609 1200 0009 6442 02

USt-IdNr.: DE812066128
AG Landau in der Pfalz
HRB 31122

Geschäftsführer / Managing Director
Bernd Dietz

Von: Laurent Destailleur [mailto:notifications@github.com]
Gesendet: Freitag, 3. März 2017 14:07
An: Dolibarr/dolibarr
Cc: Bernd Dietz; Author
Betreff: Re: [Dolibarr/dolibarr] Bug: Setup-Modules-Projects/Opportunities/Leads - Project numbering module (#6477)


Can you provide a screenshot of page

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
