### ISSUE TITLE
Bug: No possible to drag and organize lines in documents (Chrome 56 and Firefox 52)

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#6493]
# Bug

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.7
- **Database**: MySQL 5.5.52-cll-lve
- **URL**: /comm/propal/card.php?id=662

## Report

Previously since a few month ago it was not possible with Chrome but usually I use Mozilla, after update today to Firefox V. 52, as happened with Chrome, is not possible to select a line on any document and drag it to chose another position (up or down). The selector near the trash is not usable and is a big problem as it was pretty utile. That function still works in Internet Explorer 11. 

(The cursor still change when pointing mouse there, something like that https://cdn4.iconfinder.com/data/icons/cursors-gestures/100/cursor_3-512.png)

![imagen018 2017-03-08 01_19_33](https://cloud.githubusercontent.com/assets/15174724/23684189/64bcce5e-039d-11e7-893e-0f60a89c33e4.jpg)

Thank you

**Comment by dolibarr95** [comment]
Works for me on Chrome 56 & Firefox 52 with Dolibarr 4.0.0

_What is Internet Explorer ? (joke)_

**Comment by fappels** [comment]
I have a related issue #3551.
I confirm firefox stopped dragging from v51 to v52. But I only have this on a windows system.

**Comment by PlanPc** [comment]
In my case, tested in Chrome 56 x64 and Firefox 52 (32 & 64 bits), both in Windows system. 
Firefox 52 x32 uninstalled and fresh installation of Firefox 52 x64, same result.

Cleared chaché, disable all modules, and some other test, no way.

Tried to debug javascript, with no successfull at all..., I´m not programmer, so do not discourage if somebody want to do some tests.

**Comment by PlanPc** [comment]
Sorry, must add, if this could be related with [#3551](https://github.com/Dolibarr/dolibarr/issues/3551). I have extrafields in both documents, propal and facture, before this happened, I coud drag lines, but those extrafields always remain in the same position, after refresh page, every line was in correct place with the master line its belong to.

I Have no extrafields in supplier "commande", but also is not possible to drag lines.

Hope this could also help to determine if there is a bug.

**Comment by fappels** [comment]
Seems to be only on touch-screen computers.
To solve in chrome: disable 'enable touch events' in chrome://flags

Don't know if there is a setting in firefox for this.

**Comment by PlanPc** [comment]
You are right, thank you @fappels

Chrome is working again with your solution.

In firefox must use:
**About:config**
And set "**dom.w3c_touch_events.enabled**" to **0** default value is 2

**Comment by fappels** [comment]
I will reopen and change title. I'm not a dom events guru, but will check the code. Meanwhile my dropbox drag-drop is working even with touch-events enabled, so dropbox fixed it. Will take my touchscreen laptop with me to the upcoming devcamp. 
Just noticed you can also simulate on a non touch device with chrome, the touch event settings are: automatic, enabled and disabled. Default is automatic (will be enabled when a touch screen is detected). So when you force to enabled you can simulate the issue.

**Comment by apio-sys** [comment]
I confirm that works on Firefox as well like this. Better later than never so thanks!

**Comment by fappels** [comment]
@apio-sys thanks, but I still have seen some external modules around who did not pickup the required tableDnD config modifications as described in changelog of 7.0:

> Jquery plugin tableDnd updated. You now need to use decodeURI on the return value of tableDnDSerialize() 
  and add 'td.' to the beginning of the dragHandle match string.
