### ISSUE TITLE
Bug: when i put a product or service in my system

### ISSUE THREAD

**Issue by nemprinter** [Dolibarr/dolibarr#6495]
# Bug

## Environment
- **Version**: 4.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Debian)
- **PHP**: apache2handler 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.54-0+deb8u1
- **URL**: /dolibarr/index.php?mainmenu=home&leftmenu=

## Report
Dolibarr har opdaget en teknisk fejl.
This information can be useful for diagnostic:
Dato: 20170309064628
Dolibarr: 4.0.4
Niveau funktionsliste: 0
PHP: 5.6.30-0+deb8u1
Server: Apache/2.4.10 (Debian)
OS: Linux Dolibarr 3.16.0-4-686-pae #1 SMP Debian 3.16.39-1 (2016-12-30) i686
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

Anmodede webadresse: /dolibarr/product/list.php?leftmenu=service&type=1
Referer: http://192.168.1.110/dolibarr/product/index.php?mainmenu=products&leftmenu=
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT DISTINCT p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.duration, p.tosell, p.tobuy, p.seuil_stock_alerte, p.desiredstock, p.tobatch, p.accountancy_code_sell, p.accountancy_code_buy, p.datec as date_creation, p.tms as date_update, MIN(pfp.unitprice) as minsellprice FROM llx_product as p LEFT JOIN llx_product_fournisseur_price as pfp ON p.rowid = pfp.fk_product LEFT JOIN llx_product_lang as pl ON pl.fk_product = p.rowid AND pl.lang = 'da_DK' WHERE p.entity IN (1) AND p.fk_product_type = '1' GROUP BY p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.fk_product_type, p.duration, p.tosell, p.tobuy, p.seuil_stock_alerte, p.desiredstock, p.datec, p.tms, p.entity, p.tobatch, p.accountancy_code_sell, p.accountancy_code_buy ORDER BY p.ref ASC LIMIT 26
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'p.tobatch' in 'field list'

this is what i get on screen i have tryed to search dolibarr forum with out any help

**Comment by eldy** [comment]
Is it a first install in 4.0.4 or did you make a migration of a previous version ? Which one ?

**Comment by nemprinter** [comment]
was coming from version 3.5.6 that is the on that comes with Debian 8,6

**Comment by atm-maxime** [comment]
I think this is linked to your upgrade. the missing column is present in the 3.5 to 3.6 migration script.
