### ISSUE TITLE
Partner Import phone number parsing fails without useful error message

### ISSUE THREAD

**Issue by LordVan** [Dolibarr/dolibarr#6496]
# Bug
Short summary:
on step 5 of the import i just get this error:

ERROR: 25P02: current transaction is aborted, commands ignored until end of transaction block LOCATION: exec_simple_query, postgres.c:973

This error is hardly helpful at all as it does not tell which part fails or even which line. Through trial and error I figured out, that some data exported (by suitecrm) was rather bogus - in this case phone numbers with like 30-40 whitespaces either end, or simply non-valid characters. It would be nice if the error message said that there's a problem with phone number parsing on Line XY of the input or something like that.

First I asked about it in the forum: https://www.dolibarr.org/forum/12-howto-help/26641-error-when-trying-to-import-partners-from-csv

## Environment
- **Version**: 4.0.4
- **OS**:  (Gentoo) Linux
- **Web server**: apache 2.4
- **PHP**: php 5.6
- **Database**:  postgresql 9.4

## Expected and actual behavior
Useful error message which at least should contain which line of the CSV failed, but preferrably also which field/column (or that parsing /validation of a phone number/email/ .. failed)

## Steps to reproduce the behavior
import csv with invalid phone number fields

**Comment by eldy** [comment]
You should get an error on line and field that fails when using the impot module.
Can you provide a screenshot of page just after clicking on "simulate import" ?

**Comment by LordVan** [comment]
I don't think I have a screenshot , but that message is really all I got. Other errors show up as you said.
I can probably reproduce this though

**Comment by LordVan** [comment]
So anyway .. I did recreate it with the faulty data (mind you that too long telefon type field *or* invalid chars gives the same error) -- 
![suitecrm firmen - dolibarr partner fehler tel](https://cloud.githubusercontent.com/assets/3889283/23832716/cc865564-073a-11e7-840a-cdca75b0ea1c.png)

[suitecrm firmen - dolibarr partner FEHLER tel.txt](https://github.com/Dolibarr/dolibarr/files/836572/suitecrm.firmen.-.dolibarr.partner.FEHLER.tel.txt)

As you can see that error message is not helpful in the slightest to find the problem. I did find it by trial and error by doing first 10 lines, 50, ... tehn checking that line and fixing what looked bogus. but at least the extra whitespaces could've easily been ignores with a trim() ;)
