### ISSUE TITLE
Universal namming project issue on {cccc} mask

### ISSUE THREAD

**Issue by laussetdelon** [Dolibarr/dolibarr#6501]
# Bug
*Browse third party list (next / prev button) issue*

## Environment
- **Version**: [*4.0.4*]
- **OS**: [*Debian 8 - 32 bits*]
- **Web server**: [*Apache 2.4.10*]
- **PHP**: [*5.6.26*]
- **Database**: [*MySQL Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (i686) using readline 6.3*]
- **URL(s)**: [*http://mysite/societe/soc.php?*]

## Expected and actual behavior
[Project universal namming mask creates #### instead of third party code reference ({cccc}) ]

## Steps to reproduce the behavior
[*In module, change namming mask to universal create mask : PJ-{cccc}*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by atm-maxime** [comment]
{cccc} will only work if you create your project from the thirdparty card. If you go in project > new project, the reference is already generated but the third is not selected yet...
