### ISSUE TITLE
Bug: Wrong amount for devise within total block

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6506]
# Bug

## Environment
- **Version**: 5.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.29-MariaDB-0+deb8u1
- **URL**: /fourn/facture/card.php?id=1

## Report
Within supplier invoice using multicurrency module, amount within columns is good (example US$) but it displays € amount within total block

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?
