### ISSUE TITLE
Bug: Balance in bankentries.php does not match statement

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#6515]
# Bug
The balance in bankentries.php is not correct and is not similar to the bank statement. The end balance of the statement is the correct value.

https://[...]/**compta/bank/bankentries.php**?id=3
![bankentries](https://cloud.githubusercontent.com/assets/14094327/23847961/2be66e32-07d5-11e7-95f2-7a2785ca0e7f.png)

https://[...]/**compta/bank/releve.php**?num=201703&account=3
![statement](https://cloud.githubusercontent.com/assets/14094327/23847967/2ed5f464-07d5-11e7-914a-c2bf1a5b8f98.png)

## Environment
- **Version**: 5.0.0

**Comment by braito4** [comment]
they said isn't a bug...
https://github.com/Dolibarr/dolibarr/issues/6075

**Comment by sbschumacher** [comment]
@braito4 I didn't know about #6075... the explanation of @simnandez (multiple pages) is not resolving the problem, as you can see in the screenshots before.

So, it doesn't make any sense... either the balance on date d is `x` or `x-/+whatever`. Definitively a bug. If I go back to Dolibarr 4.0.4 the numbers are correct.

**Comment by sbschumacher** [comment]
Maybe this "observation" can help to find the error...

When …/compta/bank/bankentries.php is displayed in several pages, the **balance is wrong**
![ohne titel 1](https://cloud.githubusercontent.com/assets/14094327/23894400/3e02115c-08a2-11e7-8d99-8731fa6a8a29.png)

but if you could display all entries in one page (if you have less than 5000 entries), than the **balance is correct**:
![ohne titel 2](https://cloud.githubusercontent.com/assets/14094327/23894404/41872b00-08a2-11e7-89b5-08918acecbcf.png)

**Comment by bgenere** [comment]
Hello,

I assume that if you have multiple pages, the bottom at each page is the balance from the first entry (on first page) to the last entry of the page.   So normally the last entry of the last page should be OK.

However I have tested for one of my installation and it seems there is an issue with the number of page. I have 199 entries. If I use a page size from 40 or above, so I get 5 pages maximum it works fine, if I get more than 5 pages total, it is a mess. The balance is wrong !
So definitely there is a bug !

**Comment by braito4** [comment]
The bug still in 5.0.1 (and at this point in 5.0.2)
Just to summarise the bug. The entries in balance should be always the same, and should not change if you change the entries listed

**Comment by pangoSE** [comment]
5.x is no longer supported. Close this
