### ISSUE TITLE
Bug: Agenda to slow - if you have/use many thirdparties

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#6517]
# Instructions
The different calendarviews (daily, weekly, monthly) are very slow, if you manage several thousand addresses in the Dolibarr. My question is why all thirdparties will be loaded into the selection listbox "Thirdparties"  when I can choose anyway only those already used in the calendar thirdparties which in my case would be only a few hundred. 
 
 If nobody see a benefit to load all thirdparties in this views it shoult be changed to save hardware ressources.
 
 

 ## Environment
 
- **Version**: Version: 5.0.0
- **OS**:  CentOs7
- **Web server**: Apache/2.2.15
- **PHP**: 5.6.30
- **Database**: MySQL or MariaDB 5.5.54
- **URL(s)**: [*Affected URL(s)*]
 
  
 
## Suggested implementation
my solution you can find in my Pull Request  #6525

**Comment by fappels** [comment]
Are you using ajax autocompleter for third parties select?

**Comment by gschratzer** [comment]
yes, that's comfortable. The question is, why we load all existing thirdparties in the select in this function where we need only the thirdparties which are used in the agenda ..... 

If you have no idea, it is easy to change it and load only the in the agenda used thirdparties - needs not so many ressources from the SQL-Server and works very fast.
