### ISSUE TITLE
Dolibarr 4.0 / email template

### ISSUE THREAD

**Issue by mzaimi** [Dolibarr/dolibarr#6522]
Hello,
I wanted to create an email template but problem ... see below the report displayed ...
thank you for your answer
---------------------------------------------------------------
Bonjour,
J'ai voulu créer un modèle de courriel mais problème ... voir ci-dessous le rapport affiché ...
Merci pour votre réponse

**Rapport / Report**
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20170314094037
Dolibarr: 4.0.4
Niveau de fonctionnalités: 0
PHP: 5.5.9-1ubuntu4.21
Serveur: Apache
OS: Linux YYYYY.ovh.net 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

Url sollicitée: /dolibarr/admin/dict.php?id=25
Referer: https://www.yyyy.fr/dolibarr/admin/dict.php?id=25
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: INSERT INTO llx_c_email_templates (label,type_template,private,position,topic,content,entity,active) VALUES('Test Modele Mail','propal_send','Test1','1','Test Mail','texte test mail','1',1)
Code retour dernier accès en base en erreur: DB_ERROR_1366
Information sur le dernier accès en base en erreur: Incorrect integer value: 'Test1' for column 'private' at row 1

**Comment by dolibarr95** [comment]
Hello
Private seems to be a smallint value try with 1 instead of Test1.

**Comment by marcosgdf** [comment]
Can you please translate to English?

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
