### ISSUE TITLE
Bug: Progression feature within invoice doesn't work any more

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6536]
# Bug

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.29-MariaDB-0+deb8u1
- **URL**: /compta/facture.php?id=2167

**Comment by akhalz** [comment]
Hi
By progression feature, do you mean that you cannot validate an invoice?

I am having that issue. I can create a provisional invoice, once I try validate and affirm on the pop-up window to deduct from the assigned warehouse, the window returns to the provisional invoice and does not get validated.

## Environment
- **Version**: [5.0.0]
- **OS**: [Linux]
- **Web server**: [Apache/2.4.23]
- **PHP**: [5.6.27]
- **Database**: [MySQL or MariaDB 5.6.35]
- **URL(s)**: [*Affected URL(s)*]

**Comment by grandoc** [comment]
No, it's a specific feature that can be activated with that key :
      INVOICE_USE_SITUATION
    
    Le 17/03/2017 à 15:45, akhalz a écrit :
    
    
      Hi
        By progression feature, do you mean that you cannot validate an
        invoice?
      I am having that issue. I can create a provisional invoice,
        once I try validate and affirm on the pop-up window to deduct
        from the assigned warehouse, the window returns to the
        provisional invoice and does not get validated.
      Environment
      
        Version: [5.0.0]
        OS: [Linux]
        Web server: [Apache/2.4.23]
        PHP: [5.6.27]
        Database: [MySQL or MariaDB 5.6.35]
        URL(s): [Affected URL(s)]
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Dolibarr/dolibarr","title":"Dolibarr/dolibarr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Dolibarr/dolibarr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@akhalz in #6536: Hi\r\nBy progression feature, do you mean that you cannot validate an invoice?\r\n\r\nI am having that issue. I can create a provisional invoice, once I try validate and affirm on the pop-up window to deduct from the assigned warehouse, the window returns to the provisional invoice and does not get validated.\r\n\r\n## Environment\r\n- **Version**: [5.0.0]\r\n- **OS**: [Linux]\r\n- **Web server**: [Apache/2.4.23]\r\n- **PHP**: [5.6.27]\r\n- **Database**: [MySQL or MariaDB 5.6.35]\r\n- **URL(s)**: [*Affected URL(s)*]\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Dolibarr/dolibarr/issues/6536#issuecomment-287373644"}}}
    
    
    -- 
      
        
          
            
              
              
            
            
              Philippe GRAND
                    ATOO.NET
                    SIREN 432 991 636 - APE 6202A
                    E-mail : philippe.grand@atoo-net.com
                    GSM : 06 80 22 33 18 
                    Tel : 02 38 63 90 20
                    Web : http://www.atoo-net.com

**Comment by akhalz** [comment]
Resolved my bug - In the stocks setting I had to allow stock to be negative. There was no warning or error message to indicate the error. It was simply returning to the invoice window. 
Perhaps that would resolve your issue

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
