### ISSUE TITLE
BUG: since 4.0.4 to 5.0.0 autofill zip/town not working

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#6541]
# Instructions
*I have always liked the comfort of the function htdocs/core/ajax/ziptown.php great with filled out the fields in the address creation (soc.php) after you written the first characters from the zip or the town.
 
*Unfortunately, since the upgrade from 4.04 to 5.0.0 in our installation this function is not working. 
 
*I found the problem and changed it on my side.
 
*On the very hidden position for non software specialists, i found in the htdocs/core/class/conf.class.php this line:
 
`if (! isset($this->global->MAIN_USE_ZIPTOWN_DICTIONNARY)) $this->global->MAIN_USE_ZIPTOWN_DICTIONNARY=1;`
 
That's means if you don't have set the variable which is using the new Table ZIPTOWN - Set IT !
 
My Solution that the function on my side is working again was to set it back to Value:0;
 
 htdocs/core/ajax/ziptown.php 
 htdocs/core/class/conf.class.php 
 htdocs/societe/soc.php
 
 
 ## Environment
 
- **Version**: Version: 5.0.0
- **OS**:  CentOs7
- **Web server**: Apache/2.2.15
- **PHP**: 5.6.30
- **Database**: MySQL or MariaDB 5.5.54
- **URL(s)**: [*Affected URL(s)*]
 
 
 
## Suggested implementation
@eldy 
*is it not better to make it in the modul settings from thirdparties i.E. societe/admin/societe.php to change it in the modul settings. 
 
*The current solution is now for none software-specialist not working - they can't solve it....

**Comment by bharatkaushik1** [comment]
Thanks at least we can manually solve it by changing below in htdocs/core/class/conf.class.php

if (! isset($this->global->MAIN_USE_ZIPTOWN_DICTIONNARY)) $this->global->MAIN_USE_ZIPTOWN_DICTIONNARY=1;
to 
if (! isset($this->global->MAIN_USE_ZIPTOWN_DICTIONNARY)) $this->global->MAIN_USE_ZIPTOWN_DICTIONNARY=0;

Perfect!!!
Thanks

**Comment by marcosgdf** [comment]
After some research, the problem relays on using ziptown table instead of thirdparties table. Ziptown table is never filled with data.

To disable/correct it, you can set MAIN_USE_ZIPTOWN_DICTIONARY key with value "0" in Config > Misc.
I am now pushing a fix so that the default value is 0 and not 1.

**Comment by amoreira1** [comment]
Hi
I cant find the htdocs . Does anyone can help me ?
Thank you in advance

**Comment by bharatkaushik1** [comment]
Hi Amoreira,

Please let me know which hosting you from using? 

Kindly check if there is an folder called Public_html or www it will be treated as htdocs.

**Comment by amoreira1** [comment]
Hi bharatkausshik

Thanks so much for your answer. Im not a professional in computers, so can you tell me more specificly what do you mean by hosting?
i have the software installed in www.moreira.pt/porto
Appreciate your answer

Best regards

**Comment by bharatkaushik1** [comment]
Hi Amoreira,

Kindly check where you have uploaded the files of ERP, I means where you have loaded files in porto folder.

Kindly go to porto folder, then go to /core/class/conf.class.php & change 

if (! isset($this->global->MAIN_USE_ZIPTOWN_DICTIONNARY)) $this->global->MAIN_USE_ZIPTOWN_DICTIONNARY=1;
to
if (! isset($this->global->MAIN_USE_ZIPTOWN_DICTIONNARY)) $this->global->MAIN_USE_ZIPTOWN_DICTIONNARY=0;

Kindly share your email, or drop me an email on bharat_kaushik@baboon.co.in

**Comment by amoreira1** [comment]
Dear Bharatkaushik

I have this information in line 491

// By default, we do not use the zip town autofill
if (! isset($this->global->MAIN_USE_ZIPTOWN_DICTIONNARY)) $this->global->MAIN_USE_ZIPTOWN_DICTIONNARY=0;

What can i do ?
My problem is that i would like to access to dictionary to change some details and when i click in dictionary, it appears HTTP500

Your help is very appreciated .

best regards

Antonio

**Comment by bharatkaushik1** [comment]
Hi,

If you are getting HTTP 500 error, it could be due to many reasons. Kindly check with the hosting service provider (The company from where you have bought the hosting).

Also please check what is the web url shown the address bar. Kindly upload the page again on the web hosting.
