### ISSUE TITLE
bug traductions

### ISSUE THREAD

**Issue by Madumtv** [Dolibarr/dolibarr#6542]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
a lot of text is in english in place of french

## Environment
- **Version**: 5.0
- **OS**: Linux
- **Web server**: php / mysql
- **PHP**: 5
- **Database**: unknow
- **URL(s)**: a lot of pages

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
after update to 5.0 a lot of pages are in english...
Some pages are correctly in french

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
adapt a correct translation

**Comment by marcosgdf** [comment]
You see English sentences because they were not translated when releasing 5.0 version, and they are not updated until the next major release

**Comment by atm-maxime** [comment]
Translations are done on transifex.
Too old version, please upgrade and reopen if needed.
