### ISSUE TITLE
Bug: Unable to send emails - Dolibarr 5.0 / 6.0 

### ISSUE THREAD

**Issue by yorkhood** [Dolibarr/dolibarr#6544]
# Bug
Emails cannot be sent when upgrade from Dolibarr 4.0.4 to Dolibarr 5.0 or Dolibarr 6.0-Alpha

## Environment
- **Version**: 5.0.0-stable and 6.0.0-Alpha
- **OS**: Centos 7.0
- **Web server**: Apache
- **PHP**: 5.6.29
- **Database**: MariaDB 5.5.52-MariaDB
- **URL(s)**:  admin/mails.php?mainmenu=home

## Expected and actual behavior
Email sent 

## Steps to reproduce the behavior
Set the emails to office 365 or Gmail, test sending 

Failed to send mail (sender=xx , receiver=xx)
Error [120]: Ran into problems sending Mail. Response: 501 5.5.4 Invalid domain name [HK2PR02CA0042.apcprd02.prod.outlook.com] Error [126]: 'tls://smtp.office365.com' does not support authenticated connections.

**Comment by saxa** [comment]
It is also happening to me over here, it seems that when you add a cc field it automatically adds an "@"
simbol at the end. Here is working, also if it issues the error I get the email sent.

**Comment by gderouze** [comment]
Hi, same issue with my configuration.
It works with the previous version, but since I upgrade to 5.0.0 or 5.0.1, this error occurs and the email wasn't sent.

**Comment by mikeveeckmans** [comment]
same here

**Comment by mikeveeckmans** [comment]
try setting it in the e-mail settings to 	Swift Mailer socket library

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
