### ISSUE TITLE
BUG: multicurrency in product prices and orders

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#6548]
# Bug
Multicurrency settings are not available in product prices and amounts/currencies are mixed in outputs

## Environment
- **Version**: 5.0.0
- **OS**: Linux
- **Web server**: Apache/2.2.31
- **PHP**: 5.6.28
- **Database**: MariaDB 5.5.53

## Expected and actual behavior
Something is missing in the new multicurrency function, when applied to product prices and correspondent documents.
With Dolibarr set to a company currency (i.e. Euros), once multicurrency has been enabled and a given currency has been set for a supplier and for a Purchase Order (i.e. USD), I expect to be able to manage product prices in the same currencies. For example, when placing an order, I expect to have products prices expressed in the currency of the supplier (i.e. USD) and get an order sheet in the same currency for the supplier. There is no any apparent reference to the currency inside the product sheet (selling or purchasing prices), but when loading a product to an order expressed in foreign currency the suggested prices are clearly in the currency of the company (not that of the supplier!).

If the prices are forced as supplier by entering them in the proper fields, the totals are correct and expressed in both the currencies. But the order sheet (Muscadet doc template) is not expressed in the foreign currency. To be precise, the total amount and the U.P. (net) are in the company currency, while line totals are in foreign currency. Label says "Amount in Euros currency", that is the currency of the company.
A similar behaviour with some additional misformat errors happens in the generated supplier invoices.

The expected beahavior is that I can set a product (purchasing/selling) price and a product (purchasing/selling) currency. So, when the product is loaded to an order, it can be automatically loaded in the proper currency (if defined for that order/supplier). For a purchase order, the supplier currency should prevail. Similarly, the company currency should prevail for a selling order.

## Steps to reproduce the behavior
1- Define a new product/service and the related purchasing prices expected in foreign currency
2- Create a purchasing order with these products/services (see that product prices are loaded as expressed in the company currency; prices can be forced in the foreign currency column)
3- Generate the order document (Muscadet template) and look at the result. Amounts are expressed in both the currencies in a mixed and wrong output

**Comment by caos30** [comment]
Oh my god... this is not "fixed" yet in 5.0.3 at this dates... 19/June/2017 :(

Eldy... whats is supposed i must do now? After 2 weeks thinking about take Dolibarr as the best ERP solution for my customer and it results that it simply cannot manage well 2 currencies ¿?¿? It's basic for people who buy/sell in USD, EUR, and other local currencies (in my case MXN).

Which is the sense of assign a currency to a customer/supplier if afterwards i cannot assign their currency to my products/services/orders/etc.... ?

I understand that this is not a simple thing (to develop a multicurrency accounting system), but man... please NOTE IT in the README file of the project, instead to announce that it works with multicurrency :(

My partner will kill me tomorrow... :S

**Comment by caos30** [comment]
Any idea about progress of the development of this feature (multicurrency prices for services and products). Someone is working on it? I'm working with Doli 5.0.4 and i see that it's possible to include products or services in an invoice if you add it as "free style", and not taking them from your list of products/services.

I would like to work this week to get this running. Please, i'm a newbie with Dolibarr. I would appreciate some orientation about to get this working... and maybe to save a lot of hours. I've read the wikis and docs for developers, but some guideline about this specific issue would be greatful! Eldy? ;)

Indeed, i know that the improvements made in such a "new features" on core modules (products/services) are not able to be added to the main dev branch by newbie developers like me. So, please tell me how to share my improvements around this bug to someone who could check it and add it to dev branch.

**Comment by moataztealab** [comment]
yes thats a bug:
1- UP Price and Original price are mixed on screen and on PDF when u change currency
2- currency not linked with accounting module , which means ull have drama in accounting with multicurency

**Comment by eldy** [comment]
Fixed for 5.0.7 and 6.0.1

**Comment by jimhtwong** [comment]
Do you mean that there is multicurrency for product?

**Comment by webartis** [comment]
not yet in 6.0.3 apparently :)

**Comment by caos30** [comment]
I think i solved it very simple inserting 5 lines in the supplier order class method addLine() (Dolibarr 5.0.4, but i suspect that it would run fine for whatever 5.X). I explained my "patch" here: [https://github.com/Dolibarr/dolibarr/issues/7700#issuecomment-343328764](https://github.com/Dolibarr/dolibarr/issues/7700#issuecomment-343328764)
