### ISSUE TITLE
Bug: default autofill - edit the adherents/card.php (fields email, password)

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#6549]
# Instructions
*Since Version 5.0.0 if the fields email empty by modify card (adherents/card.php) autodata will by filled in both fields (email and password).

# Bug
if in module member the switch "Manage a Login for each member" ON and
In the field email from a user my system is filling automatically my username and in the password (it was not empty) he is filling the password from the username his is founding for this imput box. But in most case it is a new email and not the email-address from the admin or the last one. So if you have members without email you lose the password true autofill always if you modify a record without email address.

if autofill, the email field should not be filled with autofill from browserhistory! 
If the email field has the name member_email  and not "email" it should fixed!

And if it is possible the password should stay after login.

## Environment
- **Version**: Version: 5.0.0
- **OS**:  CentOs7
- **Web server**: Apache/2.2.15
- **PHP**: 5.6.30
- **Database**: MySQL or MariaDB 5.5.54
- **URL(s)**: adherents/card.php?rowid=276&action=edit

![image](https://cloud.githubusercontent.com/assets/3923753/24148897/ffa7b00c-0e40-11e7-88bf-24e5eab547ea.png)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
