### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mithublue** [Dolibarr/dolibarr#6553]
When installing the project the error is found with this string.

SQL Error DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')ENGINE=innodb' at line 10

**Comment by tenkodoy** [comment]
I had the same problem. Have you got the solution yet?

**Comment by braito4** [comment]
https://github.com/Dolibarr/dolibarr/pull/6562

**Comment by samseen** [comment]
@mithublue and @tenkodoy. How were you able to resolve this?
