### ISSUE TITLE
Unable to direct recording of transaction in bank account

### ISSUE THREAD

**Issue by mondecans** [Dolibarr/dolibarr#6556]
# Bug
Can´t register a direct bank entry.

## Environment
Version: 5.0.0
OS: Linux
Web server: Apache
PHP: 5.4.45
Database: MySQL or MariaDB 5.5.54
URL(s): 
compta/bank/bankentries.php?action=addline&page=&contextpage=banktransactionlist-1&id=1&account=1

## Steps to reproduce the behavior
Go to bank/cash > Bank entries
Click on "Add entry"
Fill the fields with a new transaction
Click on "add"
Dolibarr do nothing

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![image](https://cloud.githubusercontent.com/assets/2051349/24256590/dc84f6a8-0fe8-11e7-9b5f-f26de835fdf8.png)

![image](https://cloud.githubusercontent.com/assets/2051349/24256181/bcbf922a-0fe7-11e7-9af6-f52150d18079.png)

![image](https://cloud.githubusercontent.com/assets/2051349/24256097/8b6a8db0-0fe7-11e7-9acf-3db1d14a6e9a.png)

**Comment by mondecans** [comment]
Related with issue #6640

**Comment by BetoVega** [comment]
see https://github.com/Dolibarr/dolibarr/issues/6640
