### ISSUE TITLE
Bug: How can i put a image of a product in to client request?

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#6561]
# Bug

## Environment
- **Version**: 5.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.35
- **URL**: /auditorias/index.php?mainmenu=home

**Comment by henryseron** [comment]
Hi, I have the same problem. I want to add images to the products and services but there is no option. Do I have to activate or configure something?

My Dolibarr version is 5.0.1

**Comment by simnandez** [comment]
For adding images, use the documents tab
