### ISSUE TITLE
install error with doc_template

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#6563]
# Bug
Echec de la copie du fichier '/var/www/html/dolidev/install/doctemplates/usergroups/template_usergroups.odt' en '/home/jean/projets/dev_internes/dolibarr/dolidev/documents/doctemplates/usergroups/template_usergroups.odt'.

## Environment
- **Version**: 6.0
- **OS**: Linux
- **Web server**: apache
- **PHP**: 7.0
- **Database**: mariadb
- **URL(s)**: install step1

## Steps to reproduce the behavior
install

juste rename odt from template_usergroup.odt to template_usergroups.odt  template for
the instruction foreach($docs as $cursordir => $cursorfile)
at line 413

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
