### ISSUE TITLE
Bug: PDF footer overlayed by the table's frame and content

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#6565]
# Bug
PDF footer overlayed by the body table in case of long lists when the footer is extended to 4 lines

## Environment
- **Version**: 5.0.0
- **OS**: Linux
- **Web server**: Apache/2.2.31
- **PHP**: 5.6.28
- **Database**: MariaDB 5.5.53

## Expected and actual behavior
When adding more details into footer of PDF files, like the company address, the resulting 4-lines footer is overlayed by the table's frame and content in case the table list is longer than 1 page. The frame shifts down towards the bottom margin, the footer text appears overlayed and the document mis-formatted.
A resize of the body table is necessary in order to avoid this issue.

**Comment by philazerty** [comment]
This problem still exists in version 7.
To correct the customer invoice "crabe" after line 269 add 
`// Add by Philazerty - Fix #6565
if ($conf->global->MAIN_GENERATE_DOCUMENTS_SHOW_FOOT_DETAILS >0) $heightforfooter = $this->marge_basse + 14;`

**Comment by minigitmax** [comment]
Thanks philazerty,
the same problem affects proposals (azur), orders (einstein, muscadet) and probably others modules...

**Comment by philazerty** [comment]
Fix Crabe for 7.0.3
[pdf_crabe.modules.php.zip](https://github.com/Dolibarr/dolibarr/files/2133435/pdf_crabe.modules.php.zip)
