### ISSUE TITLE
Bug: Automatically created core files are filling the disk

### ISSUE THREAD

**Issue by debastiani** [Dolibarr/dolibarr#6566]
# Bug
The files are created after atualization, and do note heve beem removed.
They have about 140MB of size.

## Environment
- **Version**: 5.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.35
- **URL**: /admin/ihm.php?mainmenu=home&leftmenu=setup

**Comment by marcosgdf** [comment]
Which type of files are generated automatically? It should not happen.

**Comment by atm-maxime** [comment]
With no answer since last comment, I close this issue.
