### ISSUE TITLE
Bug: Listing of open orders results in a blank page.

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#6567]
# Bug
[*Short description*]
Clicking on the http://localhost/htdocs/commande/list.php?viewstatut=-3&mainmenu=commercial&leftmenu=orders results in a blank page.

## Environment
- **Version**: [*5.0 , develop*]
- **OS**: [*Linux*]
- **Web server**: [*Apache 2.4.25*]
- **PHP**: [*5.6.30*]
- **Database**: [*MariaDB 10.0.29*]
- **URL(s)**: [*http://localhost/htdocs/commande/list.php?viewstatut=-3&mainmenu=commercial&leftmenu=orders*]

## Expected and actual behavior
It should show a list of open customer orders.

## Steps to reproduce the behavior
Clicking on the number which shows the nr. of open customer orders.

**Comment by marcosgdf** [comment]
Can you please check the log of PHP errors to have a clue about what is it happening?

**Comment by saxa** [comment]
Ok, after the last updates started to work again without any fixing. So I consider this closed.
