### ISSUE TITLE
Default Log in and password

### ISSUE THREAD

**Issue by tenkodoy** [Dolibarr/dolibarr#6568]
Please what is the default login username and password

**Comment by inoveaconseil** [comment]
On What ?
A bug on install in version 6 was fixed and the install loasd correctly.

**Comment by marcosgdf** [comment]
The administration login is defined by the user and created in the install wizard. Therefore there is no default login

**Comment by ReemKatmeh** [comment]
Can I create a module that enables me to log in with Microsoft account? And How can I do that?

**Comment by atm-maxime** [comment]
@ReemKatmeh Why post a comment on a 3 years old closed issue and about a different subject ?

**Comment by Vaadasch** [comment]
On this day, I've installed Dolibarr through docker.
Default credentials for this instance was : admin / admin 
Some would try those too : admin / changeme
