### ISSUE TITLE
Bug: Clone error

### ISSUE THREAD

**Issue by StefAngel** [Dolibarr/dolibarr#6580]
# Bug
when trying to clone a product...
with or without choosing options and clicking for validating cloning
i get error on "no cloning options set"...
and so no clone created :(
## Environment
- **Version**: 5.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.16
- **Database**: MySQL or MariaDB 10.1.22-MariaDB
- **URL**: /product/composition/card.php?id=7

**Comment by inoveaconseil** [comment]
I can't reproduce this bug. If you clone without option an normal error message appear and if you clone with option the product clone was created.

**Comment by StefAngel** [comment]
Effectivement.  I used # caracter in ref... And i get the error....

Le 25 mars 2017 3:43 PM, "Inovea Conseil" <notifications@github.com> a
écrit :

**Comment by inoveaconseil** [comment]
WIP
