### ISSUE TITLE
Cronjobs may be launched multiple times

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#6587]
# Bug
When setting a cron task to launch /scripts/cron/cron_run_jobs.php every 5 minutes (f E), if the task takes longer than 5 minutes it will be launched several times.
Big problem when task is importing big files or sending emailing

## Environment
- **Version**:all
## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
create a task wich takes several minutes (use a sleep 300s) and set a crontask with */1 * * * *

## Suggested implementation
before launching a task setting its status to 9 (Processing) and after execution, status back to old status.

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by atm-maxime** [comment]
This seems to be fixed in latest version.
