### ISSUE TITLE
Search on extra fields not working in services

### ISSUE THREAD

**Issue by saphirblanc** [Dolibarr/dolibarr#6591]
# Bug
You should be able to search in columns from extra fields shown on services.php. Showing the column and then making the search does not give any results and list the current view.

## Environment
- **Version**: 5.0.0
- **OS**: Debian 8
- **Web server**: 	Apache/2.4.10 (Debian)
- **PHP**: 7.0.16-1~dotdeb+8.1
- **Database**: MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u1
- **URL(s)**: services.php

## Steps to reproduce the behavior
List services from https://XXX/contrat/services.php?leftmenu=contracts&mode=4, show the extra column (for the extra field), write something, press enter, the list remains the same (with all services, nothing is searched).

**Comment by saphirblanc** [comment]
Note : the problem is still present in 5.0.1, I'm still unable to search through custom fields.

Moreover, there is another bug when browsing to the list of the services : https://XXX/contrat/services.php?leftmenu=contracts nothing is shown (even if there are hundreds of services) :
![services](https://cloud.githubusercontent.com/assets/16269066/26092106/62636322-3a0f-11e7-94d7-20f0ee163078.png)

Thank you very much.

**Comment by atm-maxime** [comment]
This seems to be fixed in latest version. (since 6.0)
Please check and reopen the issue if needed.
