### ISSUE TITLE
Possible bugs in source code (CWE-480)

### ISSUE THREAD

**Issue by AppChecker** [Dolibarr/dolibarr#6594]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bugs:

1)
https://github.com/Dolibarr/dolibarr/blob/9abe0940e7ec3234302388956a63fae7e5e6bc35/htdocs/user/card.php#L2377

```
if (! empty($conf->ldap->enabled) && ! empty($object->ldap_sid)) $ldap->close;
```
Maybe it should be $ldap->close(); instead? Like here: https://github.com/Dolibarr/dolibarr/blob/a1ba4aa9419e1998997de6ef1de559104009e4bc/htdocs/core/login/functions_ldap.php#L121

2)
https://github.com/Dolibarr/dolibarr/blob/9abe0940e7ec3234302388956a63fae7e5e6bc35/htdocs/theme/md/style.css.php#L2436

```
 background-color: <?php $colorbackhmenu1 ?>;
```

3) https://github.com/Dolibarr/dolibarr/blob/9abe0940e7ec3234302388956a63fae7e5e6bc35/htdocs/theme/eldy/style.css.php#L2550

```
 background-color: <?php $colorbackhmenu1 ?>;
```

In both cases maybe echo missed.

Possible defects were found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by atm-maxime** [comment]
This seems to be fixed in latest version.
