### ISSUE TITLE
Feature request : add folders in Linked files 

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6595]
# Add folders in Linked files 
It could be useful to add folders in the linked files, in order to classify the elements.

## Use case

- For an third party customer allow to add a folder "pictures of engines" "pictures of small parts" "pdf from Tomy" "pdf from Anna".
- For a product could be "exploded view" "plan" "shaders"....
- ...

 _Because today the only way to keep clear this unique folder is to prefix the elements._

## Suggested implementation
In linked files allow to manage a folder.

## Suggested steps
Create a folder for an elements (product, third party...)
Put picture or other in this folder
Remove folder
Displace pictures or other from a folder to another

Tks

**Comment by BebZ** [comment]
Nice idea!
Some "folders" are common, for example when you say for products : 
"pictures of engines" "pictures of small parts" "pdf from Tomy" "pdf from Anna".
For a product could be "exploded view" "plan" "shaders"....

These are common folders of the products. 
It is maybe better to put a "tag"/ extrafield 
on your picture, or to "choose" a tag between a list of extrafields which would be available such as 
"exploded view" "plan" "shaders"....

Do you have an initial development, some files to modify ? / plans / screenshots ?

**Comment by dolibarr95** [comment]
Hi
No i have start nothing. Your idea about choosing a tag in a list of extrafields seems to be very good (it should displays document in fake folders, for better user understanding i think) . The commons folders are a good idea too.

tks

**Comment by eskimo-roll** [comment]
+1 for a way to organise linked/attached files. Either by tags (best) or directories (good enough) would help. Hopefully the mechanism could apply to the linked files of all entities: Contacts, Contracts, Projects etc..

thanks
