### ISSUE TITLE
Bug: line 1163 core/lib/function2.lib.php

### ISSUE THREAD

**Issue by KLINPC** [Dolibarr/dolibarr#6601]
# Bug

## Environment
- **Version**: 5.0.0
- **OS**: Darwin
- **Web server**: Apache/2.4.17 (Unix) PHP/5.6.17 mod_wsgi/3.5 Python/3.5.1 OpenSSL/1.0.1p
- **PHP**: apache2handler 5.6.17
- **Database**: MySQL or MariaDB 5.6.25
- **URL**: /dolibarr/societe/soc.php?socid=20

## Report
Warning: preg_match(): No ending delimiter '^' found in core/lib/functions2.lib.php on line 1163
modify the line with
    if (! empty($reg[3]) && preg_match('/^\+/',$reg[3])) $maskoffset=preg_replace('/^\+/','',$reg[3]);

## Comment
No issue after correction in customer page using model Elephant for code generation

**Comment by atm-maxime** [comment]
This issue is old and has probably been fixed since then. Please reopen if needed and give us more details.
