### ISSUE TITLE
Bug: Aucun PDF n'est disponible pour la génération du document parmi les enregistrements cochés

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6604]
# Bug
This message appears after selecting a list of proposals and trying to launch an action (pdf merge)
## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u1
- **URL**: /comm/propal/list.php

**Comment by kamilmedia** [comment]
Bonjour
Du nouveau par rapport à ce bug 

Zak

**Comment by atm-maxime** [comment]
This is not a bug, if you try to merge PDF for several proposal and that these proposals have not PDF already generated, there's nothing to merge :)
