### ISSUE TITLE
Bug: Permanent warning message UserHasNoPermissions when accessing a user card (like admin)

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6610]
# Bug
Permanent warning message UserHasNoPermissions when accessing a user card (like admin), but when accessing user card it does have permissions defined.

![captura de pantalla 2017-03-29 a las 20 14 35](https://cloud.githubusercontent.com/assets/168744/24469619/5a1feabe-14bc-11e7-9d08-aada357ca5b6.png)

## Environment
- **Version**: 5.0

**Comment by atm-maxime** [comment]
Done
