### ISSUE TITLE
Addition of an account (in a chart of accounts)

### ISSUE THREAD

**Issue by microniko** [Dolibarr/dolibarr#6611]
When I try to add an account on a char of accounts, I had this error :

> Error ERREUR: 23505: la valeur d'une clé dupliquée rompt la contrainte unique « llx_accountingaccount_pkey » DETAIL: La clé « (rowid)=(19) » existe déjà. SCHEMA NAME: public TABLE NAME: llx_accounting_account CONSTRAINT NAME: llx_accountingaccount_pkey LOCATION: _bt_check_unique, nbtinsert.c:406

_unique constraint with llx_accountingaccount_pkey_

The rowid seems to change every time.

Thx.

Informations 
Dolibar 5.0.0
PHP 5.6.30-0+deb8u1
PostgreSQL 9.4.10

**Comment by gschratzer** [comment]
please only english issues here!

**Comment by microniko** [comment]
gnarf… Just I do it…

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
