### ISSUE TITLE
Fatal error converting an invoice draft to template

### ISSUE THREAD

**Issue by loxK** [Dolibarr/dolibarr#6614]
# Instructions

# Bug
When converting an invoice draft to template I get a PHP fatal error:
 `Fatal error: Uncaught Error: Class 'FormProjets' not found in /home/lox/public_html/Tests/dolibarr/erp/htdocs/compta/facture/fiche-rec.php on line 892`

## Environment
- **Version**: 	5.0.0
- **OS**: Ubuntu 16.04.4 x64
- **Web server**: 	Apache/2.4.18 (Ubuntu)
- **PHP**: 7.0.15-0ubuntu0.16.04.4
- **Database**: MariaDB 5.5.5-10.0.29-MariaDB-0ubuntu0.16.04.1
- **URL(s)**: compta/facture/fiche-rec.php?facid=1&action=create

## Expected and actual behavior
Should create an invoice template, throws a fatal error an the conversion doesn't happen.

## Steps to reproduce the behavior
Create an invoice draft click convert to template

![selection_928](https://cloud.githubusercontent.com/assets/136687/24480267/229179f0-152f-11e7-9fd5-b454ba38fce3.png)

**Comment by AlainRnet** [comment]
Same problem in 5.0.1
I check in htdocs/compta/facture/fiche-rec.php file, the call to the class, line 38. In line 36, we can see the requirement that projects must be enabled.
Isn't it possible to convert an invoice draft to template without the project's module ?
