### ISSUE TITLE
Error in CRM

### ISSUE THREAD

**Issue by Dimensionsint** [Dolibarr/dolibarr#6615]
# Bug
[Error in CRM]

## Environment
- **Version**: [Dolibarr CRM 4.0.4]
Current theme: eldy

Dear Technical support,

A few weeks ago, an error started in our CRM. Please find attached screen shot error in CRM. Now I can’t make Invoice, Supplier Orders and do payment in CRM, cant attached files, etc.

Kindly help us immediately to avoid further delay in our records.

Thanks in advance.
![crm error b](https://cloud.githubusercontent.com/assets/26786636/24492812/aca07a2a-153d-11e7-9c7e-b61d3c698d4b.JPG)
![crm error](https://cloud.githubusercontent.com/assets/26786636/24492818/b15d77fc-153d-11e7-9028-ffa324b9f2f2.JPG)

**Comment by dolibarr95** [comment]
hi
It's your database error, some fields are missing : fk_multicurrency and fk_shipping_method

**Comment by BebZ** [comment]
Dolibarr's community doesn't provide free support on Github.
Please close subject and follow guidelines to report a bug if you think it is one.
(it is not sufficient to say : A few weeks ago, an error started in our CRM. Please find attached screen shot error in CRM.)

If not, open a subject on the forum maybe some people of goodwill will provide you free support.

If no one answers, you have to see with the technician hosting your CRM interface if you have a subscription.

If you don't have one you can find reliable hosts on Dolibarr's preferred partner's list, also more reactive for you business workflow not to stop.

Thanks for you Understanding.

**Comment by atm-maxime** [comment]
This issue is old and has probably been fixed since then. Please reopen if needed and give us more details.
