### ISSUE TITLE
Creazione Fattura da Ordini cliente

### ISSUE THREAD

**Issue by panypunk** [Dolibarr/dolibarr#6618]
# Instructions
ho riscontrato un errore sulla creazione di Fattura partendo dagli ordini dei clienti.
Anagrafica Cliente, ordini da fatturare, seleziono più ordini da fatturare, clicco su crea fattura.
Viene visualizzata la pagina di generazione della fattura, ma al click della generazione, ritorna sulla schermata degli ordini del cliente, non generando la Fattura.

Qualcuno ha qualche souzione???*

# Bug
Creazione Fattura da ordini cliente

## Environment
- **Version**: DOLIBARR 5.0

**Comment by marcosgdf** [comment]
Can you please report bugs in English? Thanks.

**Comment by panypunk** [comment]
I found an error on creating invoice starting from customer orders.
Customer master data, orders to be billed, select the orders to be invoiced, I click on create invoice.
This opens the page of the invoice generation, but at the click generation, return on customer orders screen, not generating the invoice.

Does anyone have any souzione ??? *

**Comment by panypunk** [comment]
I don’t speak english very well, this is a translation:

 

 

I found an error on creating invoice starting from customer orders.
Customer master data, orders to be billed, select the orders to be invoiced, I click on create invoice.
This opens the page of the invoice generation, but at the click generation, return on customer orders screen, not generating the invoice.

Does anyone have any souzione ???

 

 

 

Alessandro Alberti

 



 

Remag s.r.l.

Via Ticino, 149 – 28066 Galliate (NO)

Tel.  0321 1646579

Cell. 346 7584678

 <http://www.grupporemag.com/> www.grupporemag.com

 

 

Da: Marcos García [mailto:notifications@github.com] 
Inviato: giovedì 30 marzo 2017 13:44
A: Dolibarr/dolibarr <dolibarr@noreply.github.com>
Cc: panypunk <alessandro.alberti@grupporemag.com>; Author <author@noreply.github.com>
Oggetto: Re: [Dolibarr/dolibarr] Creazione Fattura da Ordini cliente (#6618)

 

Can you please report bugs in English? Thanks.

**Comment by Germano0** [comment]
@panypunk you should remove URLs and other sensitive data from your last comment

**Comment by marcosgdf** [comment]
We need more information about the problem, like the entry recorded in errors.log right after reproducing the problem

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
