### ISSUE TITLE
https://www.dolibarr.org has bogus DNSSEC signature

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#6624]
# Bug

https://www.dolibarr.org has bogus DNSSEC signature

## Environment
N/A

## Expected and actual behavior

**Expected:** https://www.dolibarr.org shows information about Dolibarr. [DNSSEC Validator](https://www.dnssec-validator.cz/) reports no DNSSEC signature or valid DNSSEC signature.

**Actual:** Browser reports server not found. DNSSEC Validator reports bogus DNSSEC signature.

## Steps to reproduce the behavior
Visit https://www.dolibarr.org with [DNSSEC Validator](https://www.dnssec-validator.cz/) installed.

**Comment by eldy** [comment]
We are migrating our servers.
dnssec has been disabled. I will test this later once reactivated...
