### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#6626]
Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes:
Date: 20170401122215
Dolibarr: 6.0.0-alpha
Level of features: 0
PHP: 5.5.30
Server: Apache
OS: Linux 127233 2.6.18-243.el5 #1 SMP Mon Feb 7 18:47:27 EST 2011 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

Requested URL: /compta/facture/list.php?leftmenu=customers_bills
Referer: /compta/index.php?mainmenu=accountancy&leftmenu=
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT u.rowid, u.lastname, u.firstname, u.statut, u.login FROM opto_user as u WHERE u.entity IN (0,1) AND u.rowid = 4 AND u.fk_soc = 22 UNION SELECT u2.rowid, u2.lastname, u2.firstname, u2.statut, u2.login FROM opto_user as u2, opto_societe_commerciaux as sc WHERE u2.entity IN (0,1) AND u2.rowid = sc.fk_user AND sc.fk_soc=22 ORDER BY u.statut DESC, lastname ASC
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'u.statut' in 'order clause'

**Comment by wankwaiwing** [comment]
**Another similar issue**
------------------
Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes:
Date: 20170401122659
Dolibarr: 6.0.0-alpha
Level of features: 0
PHP: 5.5.30
Server: Apache
OS: Linux 127233 2.6.18-243.el5 #1 SMP Mon Feb 7 18:47:27 EST 2011 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

Requested URL: /commande/list.php?leftmenu=orders&viewstatut=-3&billed=0&contextpage=billableorders
Referer: /compta/facture/stats/index.php?leftmenu=
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT u.rowid, u.lastname, u.firstname, u.statut, u.login FROM opto_user as u WHERE u.entity IN (0,1) AND u.rowid = 4 AND u.fk_soc = 22 UNION SELECT u2.rowid, u2.lastname, u2.firstname, u2.statut, u2.login FROM opto_user as u2, opto_societe_commerciaux as sc WHERE u2.entity IN (0,1) AND u2.rowid = sc.fk_user AND sc.fk_soc=22 ORDER BY u.statut DESC, lastname ASC
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'u.statut' in 'order clause'

**Comment by Yvan-KM** [comment]
I have same problems

**Comment by tcarterfrance** [comment]
I have same problem. Fix is :
/core/class/html.formother.class.php, line 412
Replace :  
$sql_usr.= " ORDER BY u.statut DESC, lastname ASC";
with : 
$sql_usr.= " ORDER BY statut DESC, lastname ASC"; 
 
Regards, Thomas CARTER

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
