### ISSUE TITLE
Bug: when creating export of supplier invoices

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#6627]
Das System hat einen technischen Fehler festgestellt.
Diese Informationen können für die Fehlersuche hilfreich sein:
Datum: 20170401135343
**Dolibarr: 5.0.0**
Funktionslevel: 0
**PHP: 5.6.30**
**Server: Apache**
**OS: Linux** info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Angefragte **URL: /exports/export.php?step=5&datatoexport=fournisseur_2**
**Referer: https://[…]/exports/export.php?step=5&datatoexport=fournisseur_2**
Menüverwaltung: eldy_menu.php

**Message: Bad value for field with code=f.facnumber. Try to redefine export.**
_(The field f.facnumber is empty in export-settings)_

Das System hat einen technischen Fehler festgestellt.
Diese Informationen können für die Fehlersuche hilfreich sein:
Datum: 20170401135343
**Dolibarr: 5.0.0**
Funktionslevel: 0
**PHP: 5.6.30**
**Server: Apache**
**OS: Linux** info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Angefragte **URL: /exports/export.php?step=5&datatoexport=fournisseur_2**
**Referer: https://[…]/exports/export.php?step=5&datatoexport=fournisseur_2**
Menüverwaltung: eldy_menu.php

**Message: Bad value for field with code=f.total. Try to redefine export.**
_(The field f.total is empty in export-settings)_

Das System hat einen technischen Fehler festgestellt.
Diese Informationen können für die Fehlersuche hilfreich sein:
Datum: 20170401135343
**Dolibarr: 5.0.0**
Funktionslevel: 0
**PHP: 5.6.30**
**Server: Apache**
**OS: Linux** info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Angefragte **URL: /exports/export.php?step=5&datatoexport=fournisseur_2**
**Referer: https://[…]/exports/export.php?**step=5&datatoexport=fournisseur_2
Menüverwaltung: eldy_menu.php

**Message: Bad value for field with code=f.tva. Try to redefine export.**
_(The field f.tva is empty in export-settings)_

**Warning: Cannot modify header information - headers already sent by (output started at /[…]/core/lib/functions.lib.php:2979) in /[…]/main.inc.php on line 977**

**Comment by marcosgdf** [comment]
Can you please try with the latest 5.0 version? It is working for me
