### ISSUE TITLE
Bug: Template invoices do not store Localtax information

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6629]
# Bug

Invoices generated by templates do not respect localtax preferences and create lines of recurring invoices with localtax2=0

## Environment
- **Version**: 4.0

**Comment by dom-breizh** [comment]
The problem remains with version 5.0.4

**Comment by dom-breizh** [comment]
Can anyone have a look at that. Not a huge bug, but it's kind of a negating the use of templates if all the conditions are not respected...

**Comment by marcosgdf** [comment]
@dom-madrid Done! The code looks outdated but I think this fix does the trick

**Comment by dom-breizh** [comment]
Hi,
Just updated to version 5.0.5 and then to 6.0 and it is not fixed in either one...

**Comment by dom-breizh** [comment]
Hi,
Just updated to version 6.0.1 and it is not fixed

**Comment by marcosgdf** [comment]
It is fixed for me, but local taxes are not copied when creating a template invoice. I have to remove the line and create it again for the taxes to appear.

**Comment by dom-breizh** [comment]
Hi,
Updated to 6.0.4 and it is still not fixed... Please someone have a look at this. For Xmas ? or New Year ?
Happy Holidays Everyone.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
