### ISSUE TITLE
Bug: PDF invoice crabe template shows an empty account when payment is through bank transfer and the account does not have a number defined

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6635]
# Bug

![captura de pantalla 2017-04-03 a las 13 26 14](https://cloud.githubusercontent.com/assets/168744/24607287/3839e0ae-1871-11e7-840e-053e1753bf29.png)

## Environment
- **Version**: 4.0.5

**Comment by braito4** [comment]
For this situation you have this option: PDF_BANK_HIDE_NUMBER_SHOW_ONLY_BICIBAN
