### ISSUE TITLE
Propal date extrafield auto-increment when update

### ISSUE THREAD

**Issue by grusgrus** [Dolibarr/dolibarr#6637]
# Bug
In commercial proposal, I have two extrafield date type : datedepart and dateretour
Each time the field is updated, the value of the other extrafield is automatically incremented by 2 hours.
Example, I fill in 26/08/2017 11:03 datedepart, after clicking on "update", the extfield dateretour changes to 17/10/2017 20H00.

## Environment
- **Version**: 5.0.0
- **OS**: Debian 8
- **Web server**: Apache 2
- **PHP**: 5.6.30-0+deb8u1
- **Database**: mysql  Ver 14.14 Distrib 5.5.54
- **URL(s)**: 

## Steps to reproduce the behavior
Open proposal 
Change extrafield 1 date type
Look the second extrafield date type (incremeted  by 2 hours)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
Step 1 : before change
![2](https://cloud.githubusercontent.com/assets/5463908/24613051/65a6232a-1887-11e7-8133-332db766ff7b.JPG)

Step 2 : change extrafield datedepart 1
![3](https://cloud.githubusercontent.com/assets/5463908/24613050/65a392fe-1887-11e7-80ee-8aad5f372bc7.JPG)

Step 3 : after change, look dateretour
![1](https://cloud.githubusercontent.com/assets/5463908/24613049/65a2e02a-1887-11e7-957d-00f05afc3c31.JPG)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
