### ISSUE TITLE
Bug: Unable to add manual bank entries

### ISSUE THREAD

**Issue by arnoldsuperstar** [Dolibarr/dolibarr#6640]
# Bug
Unable to add manual bank entries

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.25
- **Database**: MySQL or MariaDB 5.1.73
- **URL**: /compta/bank/bankentries.php

## Report
When adding a manual bank entry, nothing happens. The bank entry is not created and no error message is shown.

**Comment by simnandez** [comment]
Works for me. Can you provide more info about it?

**Comment by braito4** [comment]
https://github.com/Dolibarr/dolibarr/commit/31f580ad936ddbf4621b93af0c3f7afdba9e6cd8

**Comment by BetoVega** [comment]
Hi!,

I see that table llx_bank_categ, if this have records not insert, but this table es empty.

In a 5.0.1 install clean if you allow me to insert and that's where I notice this table

**Comment by arnoldsuperstar** [comment]
Well it works now in 5.0.4

**Comment by BetoVega** [comment]
Thanks !
