### ISSUE TITLE
Bug: Standard currency for supplier order when multi currency is on

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#6645]
# Bug
When creating a new supplier order via `https://[...]/**fourn**/commande/card.php?action=create&leftmenu=orders_suppliers` the currency is not set to the standard company currency like for example in the customer order form `https://[…]/**commande**/card.php?action=create&leftmenu=orders`.

## Environment
- **Version**: 5.0.1

## Steps to reproduce the behavior
- activate module "Multi currency"
- add GBP as second curreny in the Multi currency settings
- visit https://[…]/commande/card.php?action=create&leftmenu=orders and "Euro" should be the preselected currency
- visit https://[...]/fourn/commande/card.php?action=create&leftmenu=orders_suppliers and "British Pound" should be the preselected currency

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
