### ISSUE TITLE
Code enhancement 

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6652]
# html5
I think we could simplify a lot the select_date() function in the file html.form.class.php by using : 
`<input type="date">` or`<input type="datetime-local">`
This tags displays a calendar too witout js or php function

- You can select the current date by clicking on the circle
- You can select the calendar by clicking the triangle

I know that all browser don't support it : http://caniuse.com/#feat=input-datetime

But we can prepare ourselves for it, or just add in the todo list. And it could more easy to manage on mobile, or responsive...

tks

**Comment by dolibarr95** [comment]
Hi!
Tks for reading

We could also use stepUp() and  instead of 
`// Add a "Plus one hour" link`
eg : 
```html
<label for="myDate" >Date and time : </label>
<input type="datetime-local" id="myDate" value="2017-04-18T09h00" />
<button id="myButton">+1h</button>
```

```javascript
<script>
document.getElementById("myButton").addEventListener("click", addOneHour);
function addOneHour() {
   document.getElementById("myDate").stepUp(60);
}
</script>
```

tks

**Comment by dolibarr95** [comment]
This tag  can be used with Firefox 

about:config :
- dom.forms.datetime true
- dom.form.datetime.timepicker true

**Comment by dolibarr95** [comment]
Hi

We can create a constant something like : MAIN_HTML5_DATE
And if it's set to TRUE we use 
```html
<input type="date">
``` 
instead of 
```php
$form = new Form($db);
$form->select_date();
``` 

This html tag :
- returns : YYYY-MM-DDTHH:MM with datetime-local 
- returns : YYYY-MM-DD with date 


tks

**Comment by dolibarr95** [comment]
Check the variables : 
date :
```php
$date = GETPOST('date',
                $check='custom',
                $method=0,
                $filter=FILTER_VALIDATE_REGEXP,
                $options=array("options" => array("regexp"=>"/^((\d{4})-(\d{2})-(\d{2}))$/","default"=>"false"))
                );

```
datetime-local
```php
$dateTime = GETPOST('dateTime',
                    $check='custom',
                    $method=0,
                    $filter=FILTER_VALIDATE_REGEXP,
                    $options=array("options" => array("regexp"=>"/^((\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}))$/","default"=>"false"))
                    );
```

_Maybe thoses regex can be shorter by deleting some parentheses_

**Comment by dolibarr95** [comment]
Hi the 🤖!
This issue is still relevant and not yet covered by latest stable version :p

**Comment by dolibarr95** [comment]
tks @atm-maxime

**Comment by atm-maxime** [comment]
Still relevant. @eldy do you think it's a good idea to replace all select_date by HTML5 date component ?

**Comment by atm-maxime** [comment]
Still relevant

**Comment by dolibarr95** [comment]
up 😁

**Comment by eldy** [comment]
Not a so good idea because this is not always supported. But the main important problem is that it is using the timezone of the browser. 
We need to use the timezone of the Dolibarr setup (autodetected at login) and on php side (not on javascript side)
Also the date provided is a string and we need all formated components (day, month, year) to be able to manage correctly in all situation the received parameter with no trouble of parsing a string.

**Comment by dolibarr95** [comment]
Hello
@eldy tks for the feedback.
