### ISSUE TITLE
PostgreSQL SQL syntax patches

### ISSUE THREAD

**Issue by sberthelot** [Dolibarr/dolibarr#6656]
# Bug
Many SQL statements does not work with PostgreSQL since at least Dolibarr 3.7.x.
I am usually applying those patches on release we manage for our customers but I think it would be better if they are included in main release.
They fix only SQL statements that are invalid on PostgreSQL 9.5+

## Environment
- **Version**: 3.7.0 to 5.0.1 included (at least)
- **OS**: Ubuntu Server LTS 16.04
- **Web server**: Apache HTTPD 2.4.18
- **PHP**: PHP 7.0.15 (FPM)
- **Database**: PostgreSQL 9.5.6
- **URL(s)**: many

## Expected and actual behavior
All statements are expected to work fine, they do with those patches (mainly unquoted integers, quoted strings, unquoted nulls and no SQL alias on UPDATE)

## Steps to reproduce the behavior
Edit objects affected by those bugs with a PostgreSQL backend (accountancy customer, expensereport, supplier, account, command, deposit)

## [Attached files]
[dolibarr-pgsql-accountancycustomer.patch.txt](https://github.com/Dolibarr/dolibarr/files/905281/dolibarr-pgsql-accountancycustomer.patch.txt)
[dolibarr-pgsql-accountancyexpensereport.patch.txt](https://github.com/Dolibarr/dolibarr/files/905286/dolibarr-pgsql-accountancyexpensereport.patch.txt)
[dolibarr-pgsql-accountancysupplier.patch.txt](https://github.com/Dolibarr/dolibarr/files/905284/dolibarr-pgsql-accountancysupplier.patch.txt)
[dolibarr-pgsql-accountingaccount.patch.txt](https://github.com/Dolibarr/dolibarr/files/905282/dolibarr-pgsql-accountingaccount.patch.txt)
[dolibarr-pgsql-commande.patch.txt](https://github.com/Dolibarr/dolibarr/files/905283/dolibarr-pgsql-commande.patch.txt)
[dolibarr-pgsql-remisecheque.patch.txt](https://github.com/Dolibarr/dolibarr/files/905285/dolibarr-pgsql-remisecheque.patch.txt)

**Comment by AndreZH** [comment]
Version: 7.0.0 beta 
OS: Windows 10
Web server: Apache HTTPD 2.4.4
PHP: PHP 7.2.0
Database: PostgreSQL 10.1-3 win x64

# Bug
When installing Dolibarr following error shows up  CREATE TABLE llx_expensereport_rules( rowid	integer AUTO_INCREMENT PRIMARY KEY, datec	datetime DEFAULT NULL,  -> SQL fout DB_ERROR_SYNTAX ERROR: 42601: syntax error at or near "ENGINE" LINE 1:
C:\server\htdocs\install\mysql\tables\llx_expensereport_rules.sql

switching from MySQL to PostgreSQL and was wondering how I can do autoincrement values. I saw in the PostgreSQL docs a datatype "serial", but I get syntax errors when using it (in v8.0).

https://stackoverflow.com/questions/787722/postgresql-autoincrement
https://www.postgresql.org/docs/10/static/datatype-numeric.html

**Comment by sberthelot** [comment]
Those patches have been integrated on 6.0.3+ at least.
I have another patch for a new pgsql incompatibility that I will submit on a new bug.

This one gets polluted by questions that have nothing to do with code fixing :)
