### ISSUE TITLE
Feature request: Categories in proposals and orders

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#6661]
# Feature Request
Add categories to proposals (both supplier and customer) and orders (both supplier and customer)

## Use case
For instance when you create a proposal for a customer that requested a Technical Assistance, in which you need to buy various products and subcontract various services. 
In this case it would be handy to be able to classify that the proposal was done for a Technical Assistance requested by the customer.
This would make filtering much easier, for proposals and orders in general. Companies could create their own categories.

As an added bonus, if these categories could be added to the filters in the modules Statistics. It would help in generating monthly reports. 
Currently products also can't be filtered by categories in Statistics, by enabling this we could observe stats for a specific category of products. Helping in determine which type is the best seller for example.

## Suggested implementation
[*Verbose description*]

**Comment by BebZ** [comment]
You can use Extrafields (constrained by adropdown list) 
on proposals which are copied on orders and /or invoices 
if you set it up well
Are you filtering when you close proposal ? It's useless. you have to filter on an extrafield, or put something in customer reference for filtering. Create own categories, mean you want to have "proposal categories" ? it will be one more "tab" to put categories. Better is to stick with what exists, extrafields do the job.

For statistics it's another subject, which cannot be handled on a bug tracking platform, but on a forum or a mailing list. It's a long-term work which needs an initial input, and more technical thinking than just sentences and ideas.

I think this subject can close.

**Comment by ruistrecht-alt** [comment]
Thank you
