### ISSUE TITLE
Bug: Bank transaction list search does not translate payment types

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6664]
# Bug
![captura de pantalla 2017-04-08 a las 23 46 43](https://cloud.githubusercontent.com/assets/168744/24832704/b0ad1806-1cb5-11e7-95b6-20b88d3e1cf2.png)

## Environment
- **Version**: 4.0.5
- **URL(s)**: /compta/bank/search.php

**Comment by simnandez** [comment]
Works for me in 4.0.6 (Next minor release)
![seleccion_001](https://cloud.githubusercontent.com/assets/881833/24836449/5753a952-1d1c-11e7-99a5-26a89b232f21.png)

**Comment by marcosgdf** [comment]
It also works in 4.0.5 It looks like it only happens under some circumstances. Will investigate…
