### ISSUE TITLE
The validation messages of the form "Add a subscription" are not displayed

### ISSUE THREAD

**Issue by rassakali** [Dolibarr/dolibarr#6693]
# Bug
[*The validation messages of the form "Add a subscription" for a membre are not displayed*]

## Environment
- **Version**: [*5.0.1*]

- **URL(s)**: [*/adherents/subscription.php*]

## Steps to reproduce the behavior
- Go to member
- Click on Subscriptions Tab and Click on "Create subscription"
- Leaves fields mandatory blank and click "Create subscription"
- No error message is displayed!

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
