### ISSUE TITLE
Hooks are not implemented in "/adherents/subscription.php"

### ISSUE THREAD

**Issue by rassakali** [Dolibarr/dolibarr#6694]
# Bug
[*Hooks are not implemented in "/adherents/subscription.php"*]

## Environment
- **Version**: [*5.0.1*]
- **URL(s)**: [*/adherents/subscription.php*]

## Steps to reproduce the behavior
in source "" we have:
`$reshook=$hookmanager->executeHooks('formObjectOptions',$parameters,$object,$action);    // Note that $action and $object may have been modified by hook`
But it does not work, because, there is not `$hookmanager->initHooks(array('subscription'));` for exemple

## Solution
Add `$hookmanager->initHooks(array('subscription'));` and `$hookmanager->executeHooks('doActions', $parameters, $object, $action);`
 [*/adherents/subscription.php*]

**Comment by dolibarr95** [comment]
hi
could you make a pr for that ?

**Comment by dolibarr95** [comment]
:+1:
