### ISSUE TITLE
Bug: Syntax Error PDF's Template Dolibarr 5.0.1

### ISSUE THREAD

**Issue by catrielr** [Dolibarr/dolibarr#6696]
# Bug
Syntax Error PDF's Template Dolibarr 5.0.1 in $object->mylticurrency_tx 

## Environment
- **Version**: [5.0.1]

**pdf_einstein.mudules.php**
Line 834:  $total_ht = ($conf->multicurrency->enabled && $object-**>mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

**pdf_crabe.modules.php**
Line 1056: $total_ht = ($conf->multicurrency->enabled && $object->**mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

**pdf_azur.modules.php**
Line 1008: $total_ht = ($conf->multicurrency->enabled && $object->**mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

**pdf_canelle.modules.php**
Line 599: $total_ht = ($conf->multicurrency->enabled && $object->**mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

**pdf_muscadet.modules.php**
Line 696: $total_ht = ($conf->multicurrency->enabled && $object->**mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
