### ISSUE TITLE
Bug: Declaration of PaiementFourn::getNomUrl($withpicto = 0, $option = '') should be compatible with Paiement::getNomUrl($withpicto = 0, $option = '', $mode = 'withlistof...')

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#6703]
# Bug
Declaration of PaiementFourn::getNomUrl($withpicto = 0, $option = '') should be compatible with Paiement::getNomUrl($withpicto = 0, $option = '', $mode = 'withlistof...') in /htdocs/fourn/class/paiementfourn.class.php on line 0

## Environment
- **Version**: 6.0.0 alpha (latest develop)
- **OS**: ubuntu
- **Web server**: Apache
- **PHP**: 7.0
- **Database**: MariaDB
- **URL(s)**: /compta/bank/bankentries.php?leftmenu=

**Comment by ruistrecht-alt** [comment]
It happened again:

Warning: Declaration of PaiementFourn::getNomUrl($withpicto = 0, $option = '') should be compatible with Paiement::getNomUrl($withpicto = 0, $option = '', $mode = 'withlistof...') in /htdocs/fourn/class/paiementfourn.class.php on line 35

Fatal error: Uncaught TypeError: Argument 1 passed to FactureFournisseur::delete() must be an instance of User, string given, called in /htdocs/fourn/facture/card.php on line 220 and defined in /htdocs/fourn/class/fournisseur.facture.class.php:862 Stack trace: #0 /htdocs/fourn/facture/card.php(220): FactureFournisseur->delete('2') #1 {main} thrown in /htdocs/fourn/class/fournisseur.facture.class.php on line 862

**Comment by frederic34** [comment]
can't reproduce in recent version, does this still happen?

**Comment by jtraulle** [comment]
@ruistrecht-alt Since we haven't heard back from you in a while ; I will close this issue.
Feel free to reopen a new one if this is still happening :wink:
