### ISSUE TITLE
Bug:  Langue FR (Belgique) = Anglais

### ISSUE THREAD

**Issue by gthesin** [Dolibarr/dolibarr#6713]
# Bug 

La langue (Français Belgique) correspond à de l'anglais dans les onglets. 

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.15
- **Database**: MySQL or MariaDB 5.5.5-10.1.22-MariaDB-1~xenial
- **URL**: /dolibarr/htdocs/admin/ihm.php?mainmenu=home&leftmenu=setup

**Comment by eldy** [comment]
Can you provide a screenshot ?

**Comment by simnandez** [comment]
No response
