### ISSUE TITLE
Querys extremely slow performance

### ISSUE THREAD

**Issue by mykaelog** [Dolibarr/dolibarr#6726]
# Bug
The query is extremelly ineficient, just finished upgrading dolibarr to 5.0 version, and the query on tab "Customer -> List" is not developed for a big database from customer.

## Environment
- **Version**: 5.0
- **OS**:  12.04.5 LTS 4GB ram server
- **Web server**: Apache2 
- **PHP**: PHP 5.6
- **Database**:Mysql 5.5

## Expected and actual behavior
Expected to be a fast query with about 500k lines on llx_societe table.
There are some extrafields created with societe module.

## Steps to reproduce the behavior
`SELECT s.rowid, s.nom AS name, s.barcode, s.town, s.zip, s.datec, s.code_client, s.code_fournisseur, st.libelle AS stcomm, s.fk_stcomm AS stcomm_id, s.fk_prospectlevel, s.prefix_comm, s.client, s.fournisseur, s.canvas, s.status AS STATUS, s.email, s.phone, s.url, s.siren AS idprof1, s.siret AS idprof2, s.ape AS idprof3, s.idprof4 AS idprof4, s.fk_pays, s.tms AS date_update, s.datec AS date_creation, s.code_compta,s.code_compta_fournisseur, typent.code AS typent_code, state.code_departement AS state_code, state.nom AS state_name,ef.gastos_envio_distribuidor AS options_gastos_envio_distribuidor,ef.plazo_entrega AS options_plazo_entrega,ef.apellidos AS options_apellidos,ef.nif_duplicado AS options_nif_duplicado
FROM llx_societe AS s
LEFT JOIN llx_societe_extrafields AS ef ON (s.rowid = ef.fk_object)
LEFT JOIN llx_c_country AS country ON (country.rowid = s.fk_pays)
LEFT JOIN llx_c_typent AS typent ON (typent.id = s.fk_typent)
LEFT JOIN llx_c_departements AS state ON (state.rowid = s.fk_departement),llx_c_stcomm AS st
WHERE s.fk_stcomm = st.id AND s.entity IN (1) AND s.status = 1
ORDER BY s.nom ASC`

# Feature Request
Please implement querys with correct syntaxis, limiting it correctlly to avoid that bad performance

## Use case
With a big produccion server with 128GB ram it takes 4secs running this query. Thats not acceptable.

## Suggested implementation
I asked before in Dolibarr forum, if in a future is going to use some kind of ORM, they answer that not because you want speed database performance, but this... is not performance exactly.

## Suggested steps
Thanks, and sorry my english.

**Comment by marcosgdf** [comment]
Is that the original query? I see some spanish fields

**Comment by eldy** [comment]
Did you run the update of statistics on your database ?
Such request should provide a result instantly. I can't reproduct the time you have with a very old 4 GB server and 100 000 thirdparties.
May be try to upgrade to 7.0

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
