### ISSUE TITLE
when detailled right are activated we can no longer validate proposal

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [Dolibarr/dolibarr#6727]
# Bug
When i actived the fine (aka detailed acces rights) we can no longer validate a proposal even if the user have the right to do so

## Environment
- **Version**: 4.0.4
- **OS**: Debian 8 fully updated
- **Web server**: apache 2.4
- **PHP**: 5.6.30
- **Database**:5.5.54
- **URL(s)**: all proposal inside a customer

## Expected and actual behavior
After activating fine rights (aka detail acces rights) and giving acces to the validation of proposal, we should be able to validate proposal. The actual behaviour is that the button to valide never appears even with full rights on proposal

## Steps to reproduce the behavior
idem a above

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
