### ISSUE TITLE
Warning error on dolibarr 5.0.1 with php 7.1.1 Warning :  A non-numeric value encountered in

### ISSUE THREAD

**Issue by SBA18** [Dolibarr/dolibarr#6733]
# Bug
I get some warnings for some pages like .../comm/card.php?... and other links :

**Warning :  A non-numeric value encountered in** 

## Environment
- **Version**: Dolibarr 5.0.1
- **OS**: windows 10
- **Web server**: Apache 2.4.25, MariaDB 10.1.21, PHP 7.1.1
- **PHP**: 7.1.1

**Comment by braito4** [comment]
https://github.com/Dolibarr/dolibarr/issues/6712

**Comment by simnandez** [comment]
Duplicate
