### ISSUE TITLE
Bug: Text on wrong position. Pls see attached .jpg

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#6736]
![dolibarr_position](https://cloud.githubusercontent.com/assets/24247236/25223566/fd142c5c-25bb-11e7-9121-5e9742d7a853.jpg)
# Bug

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.17-1~dotdeb+8.1
- **Database**: MySQL or MariaDB 5.5.54-0+deb8u1-log
- **URL**: /dolibarr/htdocs/comm/propal/list.php?sall=DE300140

**Comment by aljawaid** [comment]
I have the same issue on 5.0.1

**Comment by inoveaconseil** [comment]
Where we are a multichoicedoc on the right in Dolibarr ? 
This menu appears just when we have a pdf file is linked. So I have found this menu in the widgets and in the list of documents.

**Comment by hasse-basse** [comment]
I marked out line 4260 in /theme/eldy/style.css.php, so from  `right:0px` to ` /*right:0px*/;`

**Comment by inoveaconseil** [comment]
To closed
