### ISSUE TITLE
New lines of products or service goes to the top

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#6739]
# Bug

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.17-1~dotdeb+8.1
- **Database**: MySQL or MariaDB 5.5.54-0+deb8u1-log
- **URL**: /dolibarr/htdocs/fourn/facture/card.php?id=33

When adding new lines of product or service the new line goes to the top and not to the bottom, after the already added lines. This is a new behavior, wasn't like this in the 4-versions

**Comment by eldy** [comment]
Can't reproduce with develop. Can you try with 5.0.2 ?

**Comment by hasse-basse** [comment]
Seem to be fine in 5.0.2

I havn't been anoyed by it for a while so it might have gone with 5.0.2. I'll let you know if I experience it again.

**Comment by hasse-basse** [comment]
Hi again. I'm in 5.0.4 now and I've experienced the problem again. It only seem to happends when adding a line to a supplier invoice; i didn't notice that earlier

**Comment by aljawaid** [comment]
I have the same issue with 5.0.3 and now 5.0.4 :(

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
