### ISSUE TITLE
User Permissions are not shown

### ISSUE THREAD

**Issue by torresfrank1** [Dolibarr/dolibarr#6746]
# Bug
User Permissions are not shown

## Environment
- **Version**: Dolibarr 5.0.1
- **OS**: macOS Server 5.3
- **Web server**: Apache 2
- **PHP**: PHP 7.1
- **Database**: MySQL Workbench 6.3

## Expected and actual behavior
This should let me assign permissions and restrictions to users.  Instead of showing a list of modules and functions to work with the restrictions, it does not shows modules to assign or deny access.

**Comment by gauravnarula1** [comment]
I can confirm that this issue is there in 5.0.1 version.
Hope someone sees to it on priority as the whole software does not mean anything without this.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
