### ISSUE TITLE
Bug: Withdraw XML does not use individual UMR (mandate reference)

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#6754]
# Bug
If you set an own UMR number for withdraws mandates (https://[…]/societe/rib.php?socid=12345&id=12345&action=edit) this UMR will not be insert into the generated XML file for the bank at https://[…]/office/compta/prelevement/card.php?id=123. Instead of your individual UMR the automatically generated from Dolibarr itself is used.

![sepa](https://cloud.githubusercontent.com/assets/14094327/25382886/d429dd44-29b9-11e7-9573-f7dbe8be3907.jpg)

Dolibarr 5.0.1

**Comment by sbschumacher** [comment]
Still in 6.0.1.

The SEPA-XML file created by Dolibarr cannot be used if you have created your own URM number for the direct debit mandate.

**Comment by atm-maxime** [comment]
Fixed here : #11469
