### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by israolaya** [Dolibarr/dolibarr#6758]
# Bug

Tengo un inconveniente con el IVA   por ejemplo tengo:

Subtotal  $462.175
IVA  $87.813,25   (Dolibarr lo redondea a $87.814 ... debería redondear de 0.50 para arriba)

Gracias por la ayuda.

## Environment
- **Version**: 5.0.1
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/compta/facture.php?facid=1112

**Comment by yehanny** [comment]
Hola @israolaya revisa en tu Configuración - Limites y precisión y revisa que el "Salto de rango y redondeo" esté en 0.05 si usas saltos de dos (2) decimales si lo prefieres de tres (3) usas 0.005 y así sucesivamente, recuerda que sólo permite un máximo de ocho (8) decimales, me dejas saber tus comentarios, Saludos ... :)

**Comment by israolaya** [comment]
Hola @yehanny , gracias por tu pronta respuesta. Intente lo que me sugeriste pero al colocar 0.05, sale un aviso con error que dice "ErrorMAIN_ROUNDING_RULE_TOTCanMAIN_MAX_DECIMALS_TOT", hago algo mal?, Saludos.

**Comment by yehanny** [comment]
Trata de colocar los valores iguales a la cantidad de decimales:

Decimales máximos para los precios unitarios = 2
Decimales máximos para los precios totales	= 2
Decimales máximos para los importes mostrados en pantalla (Poner ... después del máximo si quiere ver ... cuando el número se trunque al mostrarlo en pantalla) = 2

Eso si en tu país se utiliza como redondeo dos (2) decimales. Saludos

**Comment by israolaya** [comment]
Lo hice tal cual y funciono, muestra 2 decimales
Base imponible	462.175,00 $
Importe IVA	87.813,25 $    (El IVA acá es de 19%)
Importe total	549.988,25 $

pero si lo paso a 1 decimal y 0.5  y sucede lo siguiente:
Base imponible	462.175,0 $
Importe IVA	87.813,5 $
Importe total	549.988,5 $

Debería redondear a: 
Base imponible	462.175,0 $
Importe IVA	87.813,3 $
Importe total	549.988,3 $

En mi país cuando es = o menor que 0.49 no se redondea pero si es = o mayor que 0.50 si se redondea) y debería quedar sin decimales así:
Base imponible	462.175 $
Importe IVA	87.813 $
Importe total	549.988 $
y Dolibarr lo deja así 1 peso por arriba:
Base imponible	462.175 $
Importe IVA	87.814 $   ( no debería redondear a 4 porque los decimales son .25) 
Importe total	549.989 $   
Lo cual es Incorrecto.

Agradezco nuevamente el haber respondido prontamente y espero tanto numero sea claro para ti.

**Comment by yehanny** [comment]
Creo que en ese caso tendrás que realizar una condición dentro de la
factura vía PHP si utilizas el formato PDF para poder procesar el
comportamiento que requieres y haga el cálculo con 2 o 0 decimales,
Dolibarr te permite trabajar sólo con una cantidad de decimales, es decir,
1, 2, 3, 4 hasta 8 y realiza el redondeo según el criterio que
especifiques, allí si tienes que personalizar un poco más la factura,
saludos


2017-04-27 2:07 GMT+02:00 israolaya <notifications@github.com>:
