### ISSUE TITLE
install dolibarr_5.0.1-4_all.deb on Debian 8.7

### ISSUE THREAD

**Issue by Crush33** [Dolibarr/dolibarr#6761]
Hi,

According to [this thread](https://www.dolibarr.fr/forum/3-installation/58602-install-dolibarr-5-0-1-4-all-deb-sur-debian-8-7) on doli's forum, we have trouble installing dolibarr_5.0.1-4_all.deb on Debian 8.7 Jessie due to dependencies issue.

Here are the log :

```
# dpkg -i dolibarr_5.0.1-4_all.deb
(Lecture de la base de données... 45056 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de dolibarr_5.0.1-4_all.deb ...
Dépaquetage de dolibarr (5.0.1-4) sur (5.0.1-4) ...
Run the dolibarr postrm script
postrm upgrade
dpkg: des problèmes de dépendances empêchent la configuration de dolibarr :
 dolibarr dépend de libapache2-mod-php | libapache2-mod-phpfilter | php-cgi | php-fpm | php ; cependant :
  Le paquet libapache2-mod-php n'est pas installé.
  Le paquet libapache2-mod-phpfilter n'est pas installé.
  Le paquet php-cgi n'est pas installé.
  Le paquet php-fpm n'est pas installé.
  Le paquet php n'est pas installé.
 dolibarr dépend de php-cli ; cependant :
  Le paquet php-cli n'est pas installé.
 dolibarr dépend de php-mysql | php-mysqli ; cependant :
  Le paquet php-mysql n'est pas installé.
  Le paquet php-mysqli n'est pas installé.
 dolibarr dépend de php-curl ; cependant :
  Le paquet php-curl n'est pas installé.
 dolibarr dépend de php-gd ; cependant :
  Le paquet php-gd n'est pas installé.
 dolibarr dépend de php-ldap ; cependant :
  Le paquet php-ldap n'est pas installé.
 dolibarr dépend de php-xml ; cependant :
  Le paquet php-xml n'est pas installé.
 dolibarr dépend de php-mbstrin
dpkg: erreur de traitement du paquet dolibarr (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour mime-support (3.58) ...
Des erreurs ont été rencontrées pendant l'exécution :  dolibarr
```
Could you please help us ?

Thanks !

**Comment by laurentdinclaux** [comment]
It looks like a simple dependency issue. Not a bug.

**Comment by Crush33** [comment]
Yes it is dependency issue. 
But the package dolibarr_4.0.1-4_all.deb works fine on Debian 8.7 Jessie. 
We can't figure it out why it doesn't work with the dolibarr_5.0.1-4_all.deb.

Thanks for any help

**Comment by newbeewan** [comment]
Dependency issue is a packaging bug...

**Comment by Crush33** [comment]
it works with [5.0.2 package](https://sourceforge.net/projects/dolibarr/files/Dolibarr%20installer%20for%20Debian-Ubuntu%20%28DoliDeb%29/)

**Comment by guillaume-uH57J9** [comment]
The error message you provided suggest you haven't followed all the instructions for Debian installation. 
This doesn't look like a packaging bug. 

Does the issue persist when following these instructions, especially running "sudo apt-get install -f" ? 

Instructions in English : https://wiki.dolibarr.org/index.php/Dolibarr_for_Ubuntu_or_Debian
Instructions in French : https://wiki.dolibarr.org/index.php/Dolibarr_pour_Ubuntu_ou_Debian
