### ISSUE TITLE
Bug: Validating Expense Report attempts to send as user

### ISSUE THREAD

**Issue by biodland** [Dolibarr/dolibarr#6764]
# Bug
When a user is validating and submitting an expense report for approval the system tries to send email from the user email. This would work if the user is only going to send to internal email.

## Environment
- **Version**: 5.0.1
- **OS**: Debian 8.7
- **Web server**: Apache/2.4.10
- **PHP**: 5.6.30
- **Database**: MySQL or MariaDB 5.5.55
- **URL(s)**: /dolibarr/expensereport/list.php

## Expected and actual behavior
When validate and submit for approval is submitted and fault occurs, this fault is due to mail setup.
Failed to send mail (sender=*@gmail.com, receiver=*@gmail.com)
Expected response code 250 but got code '550', with message '550 5.7.60 SMTP; Client does not have permissions to send as this sender [AMSPR02MB216.eurprd02.prod.outlook.com] '

I understand why, since I'm using gmail for users and have an Office365 mail for the system it is failing due to I cannot send as gmail from Office365.

## Steps to reproduce the behavior
Create an expense report, add your expenss and make it ready to validate. Use a user with other email domain than the system is setup with and validate expense report.

**Comment by biodland** [comment]
## Workaround
Edit the file expensereport/card.php
Scroll down to you find the section for validate action 
```php
if ($action == "confirm_validate" && GETPOST("confirm") == "yes" && $id > 0 && $user->rights->expensereport->creer) {
 // FROM
$expediteur = new User($db);
$expediteur->fetch($object->fk_user_author);
$emailFrom = $expediteur->email;_
// replace above line with this
$emailFrom = $conf->global->MAIN_MAIL_SMTPS_ID;
}
```
this is to be done under all the other emailFrom instances coming on the other actions.
confirm_save_from_refuse
confirm_approve
confirm_refuse
confirm_cancel
set_paid

Updated card.php where $emailFrom is replaced
[card.txt](https://github.com/Dolibarr/dolibarr/files/962217/card.txt)

**Comment by marcosgdf** [comment]
I am afraid that is the expected behaviour

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
