### ISSUE TITLE
Bug: 4.0.2 - Various recurrent invoices can´t have same title, must be unique?

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#6765]
# Bug

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.7
- **Database**: MySQL or MariaDB 5.5.52-cll-lve
- **URL**: /compta/facture/fiche-rec.php

## Report

https://www.dropbox.com/s/j9wgxqbut701gpg/imagen018%202017-04-27%2C%2021_01_32.jpg?dl=1

This is related to Ver.  4.0.2, maybe is solved later, but I think it is an error in DB, as many people may need to invoice the same product/service to different customers reguarly o recurrently, but actually it is not possible as you will get this error . 

**Duplicate entry '_tittle-of-invoice-product/service_-1' for key 'idx_facture_rec_uk_titre'**

In the table "**llx_facture_rec**" the field "**titre**" is marked as unique, so if need to invoice various customers monthly with the same service "Garbage collection", I must change this tittle in every recurrent invoice or I am not able to create them:

Garb. collection
G. collection
Garbage coll.
Garbage collect
Garbage Service
Garbage ant other....

Thank you

**Comment by eldy** [comment]
Yes. The name must be a unique reference to be able to distinguish them. Because it is just a name ans not use for invoice generation, you can set different name freely. Put a number or date of recurring invoice init.
