### ISSUE TITLE
Bug: En las propuestas (cotizaciones) el valor del IVA no se muestra correctamente. 

### ISSUE THREAD

**Issue by omarangaritaj** [Dolibarr/dolibarr#6766]
# Bug

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.19
- **Database**: MySQL or MariaDB 5.5.51-38.1-log
- **URL**: /DigiRED/htdocs/comm/propal/card.php?id=200

**Comment by marcosgdf** [comment]
Could you please give us information about the error? I am afraid we are not able to diagnose it otherwise

**Comment by omarangaritaj** [comment]
Gracias, puede ver más información en [https://youtu.be/8C9SW8ZTrSc](url) así verá más detalles

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
