### ISSUE TITLE
Bug: Can't insert services in prices requests after new constraints on supplier proposal detail table

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#6768]
# Bug
After commit 1c20bbb2871808e3e6ee4d5ecf7874a3721c5f4e I can't add services to price requests.
Message:
`
Cannot add or update a child row: a foreign key constraint fails (`aliartalentos_dolibarr`.`llx_supplier_proposaldet`, CONSTRAINT `fk_supplier_proposaldet_fk_unit` FOREIGN KEY (`fk_unit`) REFERENCES `llx_c_units` (`rowid`)) sql=INSERT INTO llx_supplier_proposaldet (fk_supplier_proposal, fk_parent_line, label, description, fk_product, product_type, fk_remise_except, qty, tva_tx, localtax1_tx, localtax2_tx, localtax1_type, localtax2_type, subprice, remise_percent, info_bits, total_ht, total_tva, total_localtax1, total_localtax2, total_ttc, fk_product_fournisseur_price, buy_price_ht, special_code, rang, ref_fourn, fk_multicurrency, multicurrency_code, multicurrency_subprice, multicurrency_total_ht, multicurrency_total_tva, multicurrency_total_ttc, fk_unit) VALUES (4, null, 'Mão de Obra - Instalações Elétricas', '', '25', '1', null, 1, 0, 0, 0, '0', '0', null, 0, '0', 0, 0, 0, 0, 0, null, '0', 0, 2, '', null, 'EUR', 0, 0, 0, 0, 0)
`

## Environment
- **Version**: 6.0.0
- **Web server**: Apache
- **PHP**: 7.0.0
- **Database**: MariaDB
- **URL(s)**: /supplier_proposal/card.php

## Steps to reproduce the behavior
1 . Create a draft price request
2. Add a service to the PR

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![dolibarr_supprop](https://cloud.githubusercontent.com/assets/23050598/25525485/046db90e-2c07-11e7-98d7-f8f30e2616df.gif)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
