### ISSUE TITLE
ErrorBadValueForParamNotAString displayed for Label value in Config / Dictionaries

### ISSUE THREAD

**Issue by yaaax** [Dolibarr/dolibarr#6770]
# Bug
In the Config / Dictionaries page, "ErrorBadValueForParamNotAString" is displayed under "Label" (as a value in the text field)
Also, it is Impossible to add a "DictionarySource" ("_Origine des propales/commandes_")

## Environment
- **Version**: 5.0
- **OS**: Debian 8 (jessie)
- **Web server**: Apache 2.4.10
- **PHP**: 5.6.30-0+deb8u1
- **Database**: mysql  Ver 15.1 Distrib 10.1.22-MariaDB
- **URL(s)**: /admin/dict.php?id=22

## Expected and actual behavior
ACTUAL : "ErrorBadValueForParamNotAString" displayed
EXPECTED : blank text field

## Steps to reproduce the behavior
Just go to page /admin/dict.php?id=22 ("_Dictionnaires - Origines des propales/commandes_")

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
Screenshot: 
<img width="1214" alt="issue_ errorbadvalueforparamnotastring" src="https://cloud.githubusercontent.com/assets/11678850/25536125/d659fe3c-2c39-11e7-94e1-c029e92cc79e.png">

## Suggested implementation
dict.php l.1832
Change
`if ($langs->trans($transkey) != $transkey)`
by
`if (isset($transkey) && $langs->trans($transkey) != $transkey)`

**Comment by marcosgdf** [comment]
Cannot reproduce. Can you please test it with the latest 5.0 version?

**Comment by yaaax** [comment]
Sorry, I was not on the right version. 5.0 is fine
