### ISSUE TITLE
Bug: Broken UI 4.0.6

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6776]
# Bug
Broken UI

![captura de pantalla 2017-05-01 a las 13 01 25](https://cloud.githubusercontent.com/assets/168744/25578363/4df32f3c-2e6e-11e7-8b42-5e2079906ab3.png)

## Environment
- **Version**: 4.0.6

**Comment by eldy** [comment]
Hum, no error messages in apache log ?

**Comment by eldy** [comment]
It is a clean install from which package ? Deb, tgz,... ?

**Comment by marcosgdf** [comment]
Yes, a CSS file that makes references to `eldy` theme has some warnings in it

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
