### ISSUE TITLE
Documents show a closed bank account

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#6778]
# Bug
Even a closed bank account is shown on documents

## Environment
- **4.0**: [*Affected Dolibarr version(s)*]
- **All**: [*Server OS type and version*]
- ## Expected and actual behavior

[*Verbose description*]
When a bank account is set to be shown on documents on Invoice configuration (that means it will appear on all documents), and this bank account is than closed by user, Documents will continue to show it, if the user forgets to change his configuration.

https://www.dolibarr.de/forum/howto-hilfe/52321-angabe-von-konto-in-angebots-pdf-azur

**Comment by eldy** [comment]
If an invoice was created at day d, bank account closed at day d+10 and invoice regenerated with no change at day d+20, then we must show the bank account. If we hide it, the invoice must have same content if we print it at day d and d+20 since we don't change nothing on it. Do you think so ?

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
