### ISSUE TITLE
Bug: GETPOST('XXX', 'int') returns a string if the variable is not a string

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6781]
Seriously… this does not make any sense.

![captura de pantalla 2017-05-02 a las 14 03 16](https://cloud.githubusercontent.com/assets/168744/25616977/1d9b3190-2f40-11e7-88fd-debca9ae6b63.png)

**Comment by eldy** [comment]
The parameter 'int' does not mean, 'return me an int', but means 'sanitize the string data to keep only content that is int'
