### ISSUE TITLE
Connect user with LDAP without password?

### ISSUE THREAD

**Issue by scith** [Dolibarr/dolibarr#6782]
# Bug
My openLDAP provider encrypts passwords with a salt. I didn't manage to log users to Dolibarr because the password stored in Dolibarr is not encrypted the same way.
Would it be possible to log users with LDAP using some sort of ldap_bind rather than having to store their passwords in Dolibarr?

## Environment
- **Version**: 5.0.1

## Expected and actual behavior
Expected: log users with LDAP without having to store their passwords in Dolibarr
Actual: user passwords are stored in Dolibarr either in clear or MD5 encrypted. If the user password on the LDAP side is encrypted differently, Dolibarr cannot log in.

## Suggested implementation
ldap_bind ?

Thanks

**Comment by hregis** [comment]
Hello

look -> https://github.com/Dolibarr/dolibarr/pull/6516

**Comment by scith** [comment]
Hello, I have tried with md5 password but my user password in the LDAP database has a custom encryption with a salt...
I would need to add the salt in a custom code for dolibarr? That doesn't seem easy.
Why can't we just send the inputted username/password to LDAP and let LDAP authenticate like other apps seem to do? 
I don't remember coming across an app that stored the LDAP password on its side for authentication?

**Comment by hregis** [comment]
yes, look the function "dol_hash" in security.lib.php

When you look at a password in openldap do you have this in the beginning : {md5} ?

i add this md5 for ldap :

else if ($type == 4) return '{md5}'.base64_encode(mhash(MHASH_MD5,$chain)); // For OpenLdap with md5

**Comment by scith** [comment]
Hi, this is my LDAP password https://github.com/YunoHost/yunohost/blob/5e8743892815b2d6e55df381b6e5a26c793d00fd/src/yunohost/user.py#L146

Code
salt = ''.join(random.sample(char_set, 8))
salt = '$1$' + salt + '$'
user_pwd = '{CRYPT}' + crypt.crypt(str(password), salt)

**Comment by hregis** [comment]
Ok, that's why I put a TODO, you should add a drop-down list in the configuration of the LDAP module to choose the type of encryption of the password, and add CRYPT method in the function "dol_hash"

**Comment by hregis** [comment]
but... warning !!! this salt is specific for "yunohost" !!!

**Comment by scith** [comment]
Yes that is why I was wondering why Dolibarr uses this authentication method (storing the password on its side)?
It is the first app I encountered that asks for the LDAP password field, so I suppose that the other apps authenticate users on LDAP side without storing their password

**Comment by eldy** [comment]
You should be able to authenticate using a simple ldap bind. For this you must edit your conf.php file to change parameters to make authentication to use ldap instead of dolibarr crypted password.

**Comment by scith** [comment]
Thanks @eldy it works with conf.PHP! Thanks also @hregis for the insight into dolibarr code.

But why isn't this behavior part of or linked to the dolibarr LDAP module then? 
Thanks
