### ISSUE TITLE
Bug cron showing bad hour off execution time

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#6783]
# Bug
in cronjobs module the hour indiqcated is not the hour set on job

## Environment
- **Version**: 5.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6
- **Database**: mysql
- **URL(s)**: /cron/list.php?status=-2

## Expected and actual behavior
when setting the next execution time on a task eg 14:15  on /cron/card.php   on the list it will show 16:15 for next execution time
A timezone issue ?

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
