### ISSUE TITLE
Bug: everybody can write on database

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6784]
Hi
I found a bug in a case that anyone can write on Dolibarr 4.0.0. (sorry but today i can not check under dolibar 5)

I don't want to public publish here.
Can you give me an email to private report ?

tks

**Comment by eldy** [comment]
You can send to security@dolibarr.org

**Comment by eldy** [comment]
However check before with the 4.0.6 that contains fixes of 4.0.0

**Comment by dolibarr95** [comment]
Hi
I've send you an email.
I will try on other version and give you a feedback.
Tks

**Comment by dolibarr95** [comment]
Hi
With Dolibarr 5.0.0 everything is ok, no more bugs.
tks
