### ISSUE TITLE
Bug: PHP 7.1 and Direct Printing

### ISSUE THREAD

**Issue by StefAngel** [Dolibarr/dolibarr#6788]
# Bug
When Configuring Direct Printing.

can't get the Google Printers...

file_get_contents(https://www.google.com/cloudprint/search): failed to open stream: no suitable wrapper could be found

This Error doesn't happen if using PHP 7.0.18

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.4
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB
- **URL**: /printing/admin/printing.php?mode=test&driver=printgcp

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
