### ISSUE TITLE
Bug: Suppliers Invoice Mask Record

### ISSUE THREAD

**Issue by StefAngel** [Dolibarr/dolibarr#6789]
# Bug
when configuring supplier invoice module.
it doesn't "record" the masks except usual invoice...

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.18
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB
- **URL**: /admin/supplier_invoice.php

**Comment by atm-maxime** [comment]
Not a bug, only standard invoice are supported on the supplier side. Credit note are coming with 8.0 version.
