### ISSUE TITLE
Bug: Supplier N° automatic increase doesn't work

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#6790]
# Bug

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.18-1~dotdeb+8.1
- **Database**: MySQL or MariaDB 5.5.54-0+deb8u1-log
- **URL**: /dolibarr/htdocs/societe/soc.php?socid=17057&action=edit

## Report

The below problem was already in 4.9 and it remains in 5.0.1

I try to add a supplier N° to an existing client because I both buy and sell with them. When activating the supplier function Dolibarr gives him a too low number, one step too low, and I get a warning saying that the number is already taken. To get around this I have to figure out what was the last number used and based on that manually create a supplier number

_The first picture shows what it looks like before I try to save the client/supplier. It says that the new N° should be C200106, but it is taken already_

![supplier_dolibarr_01](https://cloud.githubusercontent.com/assets/24247236/25662596/61928580-3015-11e7-8b0d-152eed131cb9.jpg)

_This picture shows what it looks like in the module configuration_

![supplier_dolibarr_02](https://cloud.githubusercontent.com/assets/24247236/25662696/b47810ee-3015-11e7-8538-ef1d1769247c.jpg)

_And lastly, this is the warning message I get when trying to save_

![supplier_dolibarr_03](https://cloud.githubusercontent.com/assets/24247236/25662725/c95ee1ae-3015-11e7-8953-7e52f032e4a9.jpg)

All the best

Hans

**Comment by hasse-basse** [comment]
It is actualy worse than what I said; the new number should be F201010 and not F201007 so it hasn't increased for the last 4-5 suppliers I have created.

**Comment by atm-maxime** [comment]
Sorry I can't reproduce. Still have the issue ?

**Comment by hasse-basse** [comment]
Hi. I’m on the latest version of 6 and I still have the issue.

**Comment by atm-maxime** [comment]
Ok I reproduced. I think it's not a bug, it's related to the data already in your database. I think one of your thirds has a code that does not respect the mask, and it's making a mess for the system to find the right next value. My test is the following :
Mask : F{000}
In database F001, F002, F003 => system propose F004 for next
In database F001, FA02, F003 => system propose F001 for next
I think you should export your suppliers and check all your codes.

**Comment by hasse-basse** [comment]
Makes sense to me. I imported suppliers from another system and then created a mask that weren’t in line with the the old codes. I will clear this up and let you know the outcome

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hasse-basse** [comment]
Your were right, it did not respect the mask and that was the cause of the problem.
