### ISSUE TITLE
Bug: 4.0.6 records Internal transfer as Direct Debit

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6793]
# Bug
When recording an internal transfer in Dolibarr, the record of the origin account is saved with type "direct debit" instead of "bank transfer".

## Environment
- **Version**: 4.0.6`
- **URL(s)**: /compta/bank/virement.php?leftmenu=

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version (5.0)

**Comment by marcosgdf** [comment]
Is it going to be cherrypicked to 4.0 branch?

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
