### ISSUE TITLE
Bug: agenda movable css

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6797]
# Bug
Some events are moveable by unauthorized and non admin user

## Environment
- **Version**: 4.0.0 & 5.0.0
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: [*Database type and version*]
- **URL(s)**: /comm/action/index.php

## Expected and actual behavior
A user can not move an event that is not his.

## Steps to reproduce the behavior

- [ ] create a non admin user called A can edit and create only his agenda/events
- [ ] create a non admin user called B can edit and create only his agenda/events
- [ ] use account A to move some of B user events in the agenda view

## Part of code
In the code to be moveable the conditions are : 

```
if ($event->type_code =='AC_OTH_AUTO')

if ($event->type_code == 'ICALEVENT')

else if ($event->date_end_in_calendar && date('Ymd',$event->date_start_in_calendar) != date('Ymd',$event->date_end_in_calendar))

```

## Suggested implementation
A unauthorized user can not drag and drop an event that is not his.

Tks

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
