### ISSUE TITLE
Error during update from git to git

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#6803]
# Bug
[*Short description*]
I have tried to update the dolibarr install from a git version of about one month ago to the git version of today May 5th. I got the following error during running the installer:

## Environment
- **Version**: git date 20170505
- **OS**: Linux
- **Web server**: *Apache*
- **PHP**: *5.6.30*
- **Database**: *MariaDB*
- **URL(s)**: *Installer*

Request 80 sql='ALTER TABLE llx_supplier_proposaldet ADD CONSTRAINT fk_supplier_proposaldet_fk_unit FOREIGN KEY (fk_unit) REFERENCES llx_c_units (rowid);'
Errore DB_ERROR_1452: ALTER TABLE llx_supplier_proposaldet ADD CONSTRAINT fk_supplier_proposaldet_fk_unit FOREIGN KEY (fk_unit) REFERENCES llx_c_units (rowid);
Cannot add or update a child row: a foreign key constraint fails (`banco_dolibarr`.`#sql-4a2_7784`, CONSTRAINT `fk_supplier_proposaldet_fk_unit` FOREIGN KEY (`fk_unit`) REFERENCES `llx_c_units` (`rowid`))
Request 81 sql='ALTER TABLE llx_supplier_proposaldet ADD CONSTRAINT fk_supplier_proposaldet_fk_supplier_proposal FOREIGN KEY (fk_supplier_proposal) REFERENCES llx_supplier_proposal (rowid);'
Request 82 sql='CREATE TABLE llx_inventory(rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,datec datetime DEFAULT NULL,tms timestamp,fk_warehouse integer DEFAULT 0,entity integer DEFAULT 0,status integer DEFAULT 0,title varchar(255) NOT NULL,date_inventory datetime DEFAULT NULL)ENGINE=InnoDB;'
Request 83 sql='CREATE TABLE llx_inventorydet(rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,datec datetime DEFAULT NULL,tms timestamp,fk_inventory integer DEFAULT 0,fk_warehouse integer DEFAULT 0,fk_product integer DEFAULT 0,batch varchar(30) DEFAULT NULL,qty_view double DEFAULT NULL,qty_stock double DEFAULT NULL,qty_regulated double DEFAULT NULL,pmp double DEFAULT 0,pa double DEFAULT 0,new_pmp double DEFAULT 0)ENGINE=InnoDB;'
Request 84 sql='ALTER TABLE llx_inventory ADD INDEX idx_inventory_tms (tms);'
Request 85 sql='ALTER TABLE llx_inventory ADD INDEX idx_inventory_datec (datec);'
Request 86 sql='ALTER TABLE llx_inventorydet ADD INDEX idx_inventorydet_tms (tms);'
Request 87 sql='ALTER TABLE llx_inventorydet ADD INDEX idx_inventorydet_datec (datec);'
Request 88 sql='ALTER TABLE llx_inventorydet ADD INDEX idx_inventorydet_fk_inventory (fk_inventory);'
Request 89 sql='insert into llx_c_tva(fk_pays,taux,code,recuperableonly,note,active) values (1, '8.5', '85', '0','VAT standard rate (DOM sauf Guyane et Saint-Martin)',0);'
Request 90 sql='insert into llx_c_tva(fk_pays,taux,code,recuperableonly,note,active) values (1, '8.5', '85NPR', '1','VAT standard rate (DOM sauf Guyane et Saint-Martin), non perçu par le vendeur mais récupérable par acheteur',0);'
Request 91 sql='insert into llx_c_tva(fk_pays,taux,code,recuperableonly,localtax1,localtax1_type,note,active) values (1, '8.5', '85NPROM', '1', 2, 3, 'VAT standard rate (DOM sauf Guyane et Saint-Martin), NPR, Octroi de Mer',0);'
Request 92 sql='insert into llx_c_tva(fk_pays,taux,code,recuperableonly,localtax1,localtax1_type,localtax2,localtax2_type,note,active) values (1, '8.5', '85NPROMOMR', '1', 2, 3, 2.5, 3, 'VAT standard rate (DOM sauf Guyane et Saint-Martin), NPR, Octroi de Mer et Octroi de Mer Regional',0);'
Elaborazione dello script	KO

Any ideas on how to fix this ?

**Comment by saxa** [comment]
Here is just the error line for clarity:

Errore DB_ERROR_1452: ALTER TABLE llx_supplier_proposaldet ADD CONSTRAINT fk_supplier_proposaldet_fk_unit FOREIGN KEY (fk_unit) REFERENCES llx_c_units (rowid);
Cannot add or update a child row: a foreign key constraint fails (`banco_dolibarr`.`#sql-4a2_7784`, CONSTRAINT `fk_supplier_proposaldet_fk_unit` FOREIGN KEY (`fk_unit`) REFERENCES `llx_c_units` (`rowid`))

**Comment by eldy** [comment]
Can you try to run this request.

UPDATE llx_supplier_proposaldet SET fk_unit = NULL where fk_unit not in (SELECT rowid from llx_c_units);

Then restart migration process.

**Comment by saxa** [comment]
Ok, that seems to made it. I run the above command in mysql and tehn re-run the install process and no error appeared. Thanks Eldy.

**Comment by saxa** [comment]
It seems that the problem here still persists, today during the upgrade of the dolibarr
I again got this same error during the run of the installer:

Errore
 DB_ERROR_1452: ALTER TABLE llx_bank_account ADD CONSTRAINT 
fk_bank_account_accountancy_journal FOREIGN KEY (fk_accountancy_journal)
 REFERENCES llx_accounting_journal (rowid);Cannot add or update a 
child row: a foreign key constraint fails 
(`banco_dolibarr`.`#sql-4af_277f9`, CONSTRAINT 
`fk_bank_account_accountancy_journal` FOREIGN KEY 
(`fk_accountancy_journal`) REFERENCES `llx_accounting_journal` 
(`rowid`))
 
Also I get the following errors in the next step:
Errore: Impossibile rimuovere il file '../compta/facture/class/api_invoice.class.php'. Rimuovere manualmente e premere F5 per continuare.
Errore: Impossibile rimuovere il file '../commande/class/api_commande.class.php'. Rimuovere manualmente e premere F5 per continuare.
Errore: Impossibile rimuovere il file '../user/class/api_user.class.php'. Rimuovere manualmente e premere F5 per continuare.
Errore: Impossibile rimuovere il file '../product/class/api_product.class.php'. Rimuovere manualmente e premere F5 per continuare.
Errore: Impossibile rimuovere il file '../societe/class/api_contact.class.php'. Rimuovere manualmente e premere F5 per continuare.
Errore: Impossibile rimuovere il file '../societe/class/api_thirdparty.class.php'. Rimuovere manualmente e premere F5 per continuare.

**Comment by saxa** [comment]
Running the command Eldy suggest here no longer solves the issue. This is from git to git update.
