### ISSUE TITLE
WYSIWYG editor - bug with permissions

### ISSUE THREAD

**Issue by henryseron** [Dolibarr/dolibarr#6812]
# Bug
When the WYSIWYG editor module is activated, the users are unable to modify their own information. Below you will find an screenshot of the error message.
If the module keeps inactive there is no problem.

## Environment
- **Version**: 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.30
- **Database**: MariaDB 5.6.28-76.1
- **URL(s)**: https://url-to-dolibarr/user/card.php?id=1

## Steps to reproduce the behavior
Activate the module WYSIWYG editor in the Modules Setup and try to modify the user information. I wanted to modify my signature and got the error.

## Screenshot
![image](https://cloud.githubusercontent.com/assets/11153444/25814175/7d18507c-33ea-11e7-84fd-2ac27cd03425.png)

**Comment by eldy** [comment]
Do you have problem with "admin" user ?
Did you try with 5.0.2 ?

**Comment by henryseron** [comment]
I am admin user. I will update to 5.0.2 and try again.

Thanks.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
