### ISSUE TITLE
Bug: Can't move (change order) products/services in propale when extra fields (lines) were added

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#6823]
# Bug
Can't move (change order) products/services in propale when extra fields (lines) were added

![dolibarr_prop](https://cloud.githubusercontent.com/assets/23050598/25895120/7deaa576-3576-11e7-8b2e-6bff23207042.gif)

## Environment
- **Version**: develop
- **URL(s)**: /comm/propal/card.php

**Comment by eldy** [comment]
Can't reproduce.
Do you experience same trouble with another browser ?
Do you see any javascript error in your console ?

**Comment by ruistrecht-alt** [comment]
I'm using Opera 45.
There are no errors on the console, and I can move the items:
card.php?id=23:194 Prepare tableDnd for #tablelines
card.php?id=23:198 tableDND onDrop
card.php?id=23:199 tablelines[]=&tablelines[]=64&tablelines[]=63&tablelines[]=&tablelines[]=&tablelines[]=&tablelines[]=&tablelines[]=&tablelines[]=&tablelines[]=&tablelines[]=trlinefordates
card.php?id=23:214 tableDND end of ajax call

The extra lines won't move with the item though... maybe a future feature request?

**Comment by fappels** [comment]
This is related to #3551.
Think we have to drop tableDND and replace by UI.sortable
