### ISSUE TITLE
Bug: El impuesto no se muestra correctamente al ingresar un artículo en la cotización. 

### ISSUE THREAD

**Issue by omarangaritaj** [Dolibarr/dolibarr#6825]
[#](url) Bug 
El impuesto predeterminado no se muestra correctamente al ingresar un artículo en una cotización o factura. Pueden ver mas detalles en [https://youtu.be/8C9SW8ZTrSc]

## Environment
- **Version**: 5.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.19
- **Database**: MySQL or MariaDB 5.5.51-38.1-log
- **URL**: /DigiRED/htdocs/societe/soc.php?action=create&idmenu=26563&mainmenu=companies

**Comment by simnandez** [comment]
Works for me. Have you correctly configured the VAT dictionary for your country?

**Comment by simnandez** [comment]
I close this issue, because is not reproducible in maintened versions
