### ISSUE TITLE
Bug: No more dropbox to select a thirdparty when cloning a proposal

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6826]
# Bug

## Environment
- **Version**: 6.0.0-alpha
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u2
- **URL**: /comm/propal/card.php?id=33&socid=28203&action=clone&object=propal&mainmenu=home

**Comment by eldy** [comment]
Can't reproduce. Check you are not in a develop mode (MAIN_FEATURES_LEVEL is 0)

**Comment by simnandez** [comment]
I close this issue, because is not reproducible in maintened versions
