### ISSUE TITLE
Bug: El campo población no se llena

### ISSUE THREAD

**Issue by omarangaritaj** [Dolibarr/dolibarr#6827]
# Bug 
En las versiones anteriores (4.x) el campo "población" y "código postal" de las fichas "tercero" y "contacto" aparecía una lista con los registros anteriormente diligenciados. A partir de la versión 5.x esta funcionalidad dejó de aparecer. Vea más detalles en [https://youtu.be/m8EnNdhvo_Q](url)

## Environment
- **Version**: 5.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.19
- **Database**: MySQL or MariaDB 5.5.51-38.1-log
- **URL**: /DigiRED/htdocs/societe/list.php?delsoc=drqaw

**Comment by olsesacl** [comment]
Puedes añadir la variable MAIN_USE_ZIPTOWN_DICTIONNARY en "Inicio ->Configurcion -> Varios" y funcionará como antes.
Por lo visto se ha añadido en conf.class.php:
	

> if (! isset($this->global->MAIN_USE_ZIPTOWN_DICTIONNARY)) $this->global->MAIN_USE_ZIPTOWN_DICTIONNARY=1;

**Comment by simnandez** [comment]
Please use English for report issues or feature requests

**Comment by simnandez** [comment]
I close this issue, as it will not be implemented
