### ISSUE TITLE
Bug: Invalid argument supplied for foreach() in thirparty (with MAIN_SECURITY_CSRF_WITH_TOKEN on)

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#6839]
# Bug
Warning: Invalid argument supplied for foreach() in ******/htdocs/main.inc.php on line 1474

## Environment
- **Version**: develop
- **PHP**: 7.0
- **URL(s)**:  main.inc.php; /societe/card.php?action=create&leftmenu=

## Steps to reproduce the behavior
- Open a new third party form
- Fill form and submit => foreach error
- Fill form again with same data and submit
- Third party is created with no foreach error

**Comment by ghost** [comment]
Hi, can't reproduce the bug with current develop branch and php 7.0. Wich kind of navigator do you use ? Appear to be an empty $_POST var

**Comment by ruistrecht-alt** [comment]
This happened on Microsoft Edge, but good point. The bug did not occur on Opera

**Comment by ruistrecht-alt** [comment]
So I found out what the problem is. It's something related to the new CSRF token check, the verification ain't passing and it shows different tokens for the same user session in the same browser:
`
Invalid token in /societe/card.php?socid=33&action=edit, action=update, _POST['token']=d27408508af1f562b2be317a561ad97a, _SESSION['token']=1e6fa79fe61a26c1d7eebf33da2436e9
`
`
This is an already logged session. _SESSION['dol_login']=************** _SESSION['dol_entity']=1
`

**Comment by eldy** [comment]
Can you confirm you enable the constant MAIN_SECURITY_CSRF_WITH_TOKEN ?
This option is not yet fully supported.

**Comment by ruistrecht-alt** [comment]
Confirmed. I resolved the issue by disabling the MAIN_SECURITY_CSRF_WITH_TOKEN option.
