### ISSUE TITLE
Error during upgrade to 5.0.2

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#6846]
# Bug
I am trying to set up a new fresh install of dolibarr 5.0.2 and during install process I got the following errors.

## Environment
- **Version**: 5.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.x
- **Database**: Mysql
- **URL(s)**: htdocs/install/index.php

Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (1,'RECEP', 1,1, 'Due Upon Receipt','Due Upon Receipt',0,1); - Unknown column 'type_cdr' in 'field list'
Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (2,'30D', 2,1, '30 jours','Réglement à 30 jours',0,30); - Unknown column 'type_cdr' in 'field list'
Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (3,'30DENDMONTH', 3,1, '30 jours fin de mois','Réglement à 30 jours fin de mois',1,30); - Unknown column 'type_cdr' in 'field list'
Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (4,'60D', 4,1, '60 jours','Réglement à 60 jours',0,60); - Unknown column 'type_cdr' in 'field list'
Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (5,'60DENDMONTH', 5,1, '60 jours fin de mois','Réglement à 60 jours fin de mois',1,60); - Unknown column 'type_cdr' in 'field list'
Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (6,'PT_ORDER', 6,1, 'A réception de commande','A réception de commande',0,1); - Unknown column 'type_cdr' in 'field list'
Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (7,'PT_DELIVERY', 7,1, 'Livraison','Règlement à la livraison',0,1); - Unknown column 'type_cdr' in 'field list'
Errore di SQL : DB_ERROR_NOSUCHFIELD - insert into llx_c_payment_term(rowid, code, sortorder, active, libelle, libelle_facture, type_cdr, nbjour) values (8,'PT_5050', 8,1, '50 et 50','Règlement 50% à la commande, 50% à la livraison',0,1); - Unknown column 'type_cdr' in 'field list'
Connessione al server : viaberp.mysql.dbaas.com.br	Ok
Versione database	5.6.35-81.0-log
Nome del database	viaberp
Creazione tabelle e chiavi primarie	Ok
Creazione vincoli e indici per la tabella llx_accounting_account.key
Request 240 : ALTER TABLE llx_accounting_account ADD UNIQUE INDEX uk_accounting_account (account_number, entity, fk_pcg_version) 	Errore di SQL DB_ERROR_RECORD_ALREADY_EXISTS Duplicate entry '2300-1-PCMN-BASE' for key 'uk_accounting_account'
Creazione funzioni	Ok
Caricamento dei dati di riferimento	Error

Failed to create Dolibarr administrator account. Unknown column 'dateemployment' in 'field list'

Here is the step after:

Dolibarr ha rilevato un errore tecnico.
This information can be useful for diagnostic purposes:
Data: 20170514222328
Dolibarr: 5.0.2
Livello di funzionalità: 0
PHP: 5.6.27
Server: Apache
SO: Linux hm8274 3.14.79-grsec-2.x86_64 #1 SMP Fri Dec 23 20:42:32 GMT 2016 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

Requested URL: /dolibarr/htdocs/install/step5.php
Referer: http://viabilizelog2.hospedagemdesites.ws/dolibarr/htdocs/install/step4.php
Gestore dei menu:

Message: step5.php: unknown choice of action

**Comment by saxa** [comment]
PS: Previous install of database is 4.0.1 . I forgot to mention that I have run the install after I have put the old database data into the mysql server.

**Comment by saxa** [comment]
Ok, I decided to try with a clean database. So removed the previous database and went from zero,
This is the error I get:

Request 41 sql='ALTER TABLE llx_categorie_project ADD CONSTRAINT fk_categorie_project_categorie_rowid FOREIGN KEY (fk_categorie) REFERENCES llx_categorie (rowid);'
Errore DB_ERROR_CANNOT_ADD_FOREIGN_KEY_CONSTRAINT: ALTER TABLE llx_categorie_project ADD CONSTRAINT fk_categorie_project_categorie_rowid FOREIGN KEY (fk_categorie) REFERENCES llx_categorie (rowid);
Cannot add foreign key constraint
Request 42 sql='ALTER TABLE llx_categorie_project ADD CONSTRAINT fk_categorie_project_fk_project_rowid FOREIGN KEY (fk_project) REFERENCES llx_projet (rowid);'
Errore DB_ERROR_CANNOT_ADD_FOREIGN_KEY_CONSTRAINT: ALTER TABLE llx_categorie_project ADD CONSTRAINT fk_categorie_project_fk_project_rowid FOREIGN KEY (fk_project) REFERENCES llx_projet (rowid);
Cannot add foreign key constraint
Request 43 sql='ALTER TABLE llx_societe_remise_except ADD COLUMN entity integer DEFAULT 1 NOT NULL after rowid;'

**Comment by saxa** [comment]
Ok, basically the problem is that the installer have no idea that the database have already data in it. Therefore in the first try have not proposed me the upgrade. Maybe would be a good idea to make a test for the database if it exists or not.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
