### ISSUE TITLE
Bug: REST API not possible to add agendaevents

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#6860]
# Bug: not possible to add agendaevents (API)
 
Response body : no content
Response code : 500

Example : 

{
"table_rowid": "id",
"type_id": "1",
"type_code": "AC_TEL",
"type": "Appel téléphonique",
"code": "AC_TEL",
"label": "Label of call",
"datec": 1493571243,
"datem": 1493571243,
"authorid": "1",
"datep": 1493571120,
"datef": 1493571180,
"durationp": -1,
"fulldayevent": "0",
"punctual": "1",
"percentage": "100",
"location": "",
"transparency": "1",
"priority": "0",
"userassigned": [],
"userownerid": "1",
"socid": "37515",
"actions": [],
"array_options": [],
"linkedObjectsIds": [],
"context": [],
"note": "La description de l'appel"
}

## Environment
- **Version**: 5.0.2
- **OS**: Ubuntu server]

**Comment by eldy** [comment]
Fixed by #3898cfe02f4acf744595eee9fdd51fac5a562a57
