### ISSUE TITLE
Error when adding a subscription

### ISSUE THREAD

**Issue by microniko** [Dolibarr/dolibarr#6865]
When I try to add a subscription for a member I obtain this error :
> ERREUR: 42P01: la relation « llx_subscription_rowid_seq » n'existe pas LINE 1: SELECT
> currval('llx_subscription_rowid_seq') ^ LOCATION: RangeVarGetRelidExtended, namespace.c:418

Thx :)
Informations
Dolibar 5.0.2
PHP 5.6.30-0+deb8u1
PostgreSQL 9.4.10

**Comment by eldy** [comment]
Can you check the field rowid of table llx_subscription has the type
SERIAL PRIMARY KEY

**Comment by microniko** [comment]
Not serial type for rowid :
```
\d llx_subscription
                                        Table « public.llx_subscription »
   Colonne    |            Type             |                           Modificateurs
--------------+-----------------------------+--------------------------------------------------------------------
 rowid        | integer                     | non NULL Par défaut, nextval('llx_cotisation_rowid_seq'::regclass)
 tms          | timestamp without time zone |
 datec        | timestamp without time zone |
 fk_adherent  | integer                     |
 dateadh      | timestamp without time zone |
 datef        | date                        |
 subscription | real                        |
 fk_bank      | integer                     |
 note         | text                        |
Index :
    "llx_cotisation_pkey" PRIMARY KEY, btree (rowid)
    "uk_cotisation" UNIQUE, btree (fk_adherent, dateadh)
    "uk_subscription" UNIQUE, btree (fk_adherent, dateadh)
```

But if I try to change the rowid type :
```
# alter table llx_subscription alter column rowid type SERIAL;
ERREUR:  le type « serial » n'existe pas
```

**Comment by microniko** [comment]
I'm just migrating Dolibarr to 5.0.3 and I'm obtaining the same error :\

**Comment by microniko** [comment]
I'm just migrating Dolibarr to 5.0.4 and obtains this error : 

> ERREUR: 55000: la valeur courante (currval) de la séquence « llx_subscription_rowid_seq » n'est pas encore définie dans cette session LOCATION: currval_oid, sequence.c:774

I resolved the problem with :  
`alter table llx_subscription alter column rowid SET DEFAULT nextval('llx_subscription_rowid_seq'::regclass);`

DEFAULT was on `nextval('llx_cotisation_rowid_seq'::regclass)` (old name of table ?!)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
