### ISSUE TITLE
Bug: Error in some hooks afterLogin (or old trigger USER_LOGIN)

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6870]
# Bug
Error when login
## Environment
- **Version**: 5.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u2
- **URL**: /index.php?mainmenu=home

## Report
Dolibarr a détecté une erreur technique.
You use an experimental or develop level of features, so please do NOT report any bugs, except if problem is confirmed moving option MAIN_FEATURES_LEVEL back to 0.
Voici les informations qui pourront aider au diagnostic:
Date: 20170520144121
Dolibarr: 5.0.2
Niveau de fonctionnalités: 1
PHP: 5.6.30-0+deb8u1
Server: Apache
OS: Linux dolifarm1 4.4.59-1-pve #1 SMP PVE 4.4.59-87 (Tue, 25 Apr 2017 09:01:58 +0200) x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Url sollicitée: /index.php?mainmenu=home
Referer: http://dol500.aflac.fr/index.php
Gestionnaire de menu: 

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur

Message: Error in some hooks afterLogin (or old trigger USER_LOGIN)
XDebug informations:
File: /home/httpd/vhosts/aflac.fr/domains/dol500.aflac.fr/dolibarr/htdocs/main.inc.php
Line: 704
Function: {}

**Comment by marcosgdf** [comment]
Duplicate of #5624

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
