### ISSUE TITLE
Bug: Mauvaise valeur de paramètre. Ceci arrive lors d'une tentative de traduction d'une clé non renseigné.

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6873]
# Bug

## Environment
- **Version**: 5.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u2
- **URL**: /projet/card.php

**Comment by eldy** [comment]
The part report is empty

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
