### ISSUE TITLE
Feature Request: import csv from old version to new version doesn't work

### ISSUE THREAD

**Issue by SamuelBenard** [Dolibarr/dolibarr#6882]
# Bug
I exported companies and contacts from a 3.1.1 version. Couldn't import it in 5.0.1 version. The order of fields is different between 2 versions.

## Environment
- **Version**: 3.1.1 to 5.0.1
- **OS**: Linux
- **Web server**: Apache
- **Database**: Mysql

## Expected and actual behavior
when importing and exporting to/from different versions of Dolibarr, it doesn't work because fields order has changed with time. So, the columns are not at the same place between 2 different versions.

## Steps to reproduce the behavior
Export companies from version 3.1.1, import in 5.0.1. The values are not where they should be after importing

# Feature Request
either add sql to change fields order when upgrading. or in csv, add a line with column fields name

**Comment by eldy** [comment]
We should make a detection on field name to automatically make the mapping of field instead of a default mapping based on order of field.
