### ISSUE TITLE
Database update err hint while installation

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#6909]
DB_ERROR_1452: ALTER TABLE dol_bank_account ADD CONSTRAINT fk_bank_account_accountancy_journal FOREIGN KEY (fk_accountancy_journal) REFERENCES dol_accounting_journal (rowid);
Cannot add or update a child row: a foreign key constraint fails (`Test_db`., CONSTRAINT `fk_bank_account_accountancy_journal` FOREIGN KEY (`fk_accountancy_journal`) REFERENCES `dol_accounting_jou)

URL: /install/upgrade.php?action=upgrade&selectlang=us_EN&versionfrom=5.0.0&versionto=6.0.0

**Comment by aconits** [comment]
Hi @wankwaiwing 

I tried fresh install 6.0 and 5.0 and tried upgrading from 5.0 to 6.0 and don't met this error
I think this error has been fix
@eldy

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
