### ISSUE TITLE
Bug: Supplier Proposal PDF not Fetching Product Prices and Totals

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6938]
# Bug
Supplier Price Requests work a lot better except for one thing which makes it very useless as we cannot send to the supplier. The PDF generated file does not pull up any prices.

## Environment
- **Version**: 5.0.2, 5.0.3
- **PHP**: 7.0
- **Database**: MySQL

![quote](https://cloud.githubusercontent.com/assets/10233708/26753149/d0bc0134-4857-11e7-8bfc-abc16032f4d0.png)

**Comment by aconits** [comment]
Hi @aljawaid 

Actually this behaviour is totally normal
The goal of this document is to ask prices for any products for one supplier, so the document will be fill by the supplier and he will give you an answer for each line
After editing each line this should be used to create a supplier order

**Comment by aljawaid** [comment]
@atm-ph Thanks for the explanation.  Would you know why one column seems to be missing?  Is it because I have the config set up to show product units (piece/pack/set/box etc) ?

**Comment by aconits** [comment]
@aljawaid it's probably the product unit, I pushed this feature (supplier proposal) in a Dolibarr 3.7 and other developers have followed the feature but I don't know if the all integrations are done

**Comment by aljawaid** [comment]
@atm-ph Hello, just so you know it was actually the product picture as I had the hidden option on.  Any idea how to include the product unit on the pdf?  I think that would be very very useful when sending the proposal to the supplier.

**Comment by aconits** [comment]
@aljawaid take example from proposal PDF (azur) 
If you aren't able to code, your best way is to open a issue for that
