### ISSUE TITLE
Feature Request: Allow Supplier Proposal Send by Email

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6940]
# Feature Request
Can we please have a button so that we can send the Supplier Proposal by e-mail?  It is not currently available.

Not seen on 5.0.2 or 5.0.3

**Comment by eldy** [comment]
Seems available in 6.0 beta

**Comment by aljawaid** [comment]
Thank you, I shall wait for 6.0 to be released :)
