### ISSUE TITLE
Bug: Supplier Invoice Doesn't Show Linked Supplier Proposal

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6941]
# Bug
On Supplier Invoice under Related Objects section, the Supplier Order is shown but NOT the Supplier Quote.

Also, on Supplier Proposal, the related Supplier Order is shown but not the related Supplier Invoice.

_(Supplier Order shows correct links for Supplier Quote and Supplier Invoice)_

It becomes a confusing long-winded issue if all linked orders/quote/invoices are not shown under Related Objects.

## Environment
- **Version**: 5.0.2, 5.0.3
- **OS**: CentOS
- **PHP**: 7.0
- **Database**: MySQL

**Comment by atm-maxime** [comment]
This is not a bug, this is the way it works. Exactly the same on the customer side.
A quote generates an order, an order generates an invoice. So the quote is linked to the order, the order is linked to the quote and to the invoice, the invoice is linked to the order.

**Comment by hregis** [comment]
@atm-maxime
And if i not use order module !

**Comment by atm-maxime** [comment]
You can't "not use" the supplier order module because a supplier proposal can only generate a supplier order.
