### ISSUE TITLE
Bug: LINEORDER_SUPPLIER_CREATE  bad values

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6953]
# Bug
When we call the trigger LINEORDER_SUPPLIER_CREATE the object is not sent with correct values

## Environment
- **Version**: 4.0.0
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: fournisseur.commande.class.php

## Steps to reproduce the behavior
1. Create a new supplier order
2. Add a line predefined product (with eg.  qty 100 and reduction 0)
2. Use the trigger LINEORDER_SUPPLIER_CREATE  $object
3. The datas send in $object are not correct

Eg :
the array $line is empty : `[lines] => Array ( )`
the total is equal to 0 : `[total_ttc] => 0.00000000 `

# Feature Request
The trigger LINEORDER_SUPPLIER_CREATE  should contain the rights values. 

Tks

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
