### ISSUE TITLE
Bug: Private input is not translated in dictionnary settings

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6972]
# Bug
Private input is not translated in dictionnary settings

## Environment
- **Version**: 5.0.4
- **URL(s)**: http://dolibarr.local/admin/dict.php?id=25

![captura](https://user-images.githubusercontent.com/168744/27003077-975d13c6-4df0-11e7-8e26-cdbdf6134bf7.PNG)

**Comment by eldy** [comment]
I think this is fixed in develop branch.
