### ISSUE TITLE
Bug: FormMail::getEmailTemplate returns an array instead of a ModelMail object

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6980]

**Comment by eldy** [comment]
I don't understand the bug. How can you reproduce it ?

**Comment by marcosgdf** [comment]
It is a code quality issue.

We are using ModelMail objects to represent mail templates, but this function does not use them, it returns an array opposite to the rest of the code in Dolibarr

**Comment by frederic34** [comment]
![2018-03-11 10_23_30-commande - firefox developer edition](https://user-images.githubusercontent.com/3624836/37251783-982fdb6e-2516-11e8-8cff-50e0f6c3401b.png)
