### ISSUE TITLE
Feature request: Remove restriction on no-subject emails of CFileMail

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6984]
Emails can be sent without subject. This restriction in the class does not answer to anything technical

**Comment by eldy** [comment]
Do you mean we can have empty subject and you would like always a subject
Or there is a restriction that does not allow empty email and you would like to be able to send email without topic ?

**Comment by marcosgdf** [comment]
The latter.

There is a restriction in CMailFile and I think we should let users and developers decide if they want to send it with or without topic. It would make sense to make an alert for users but not to forbid them from sending emails without it

**Comment by feliserv** [comment]
I think this is a good restriction... It answer to the netiquette.
Maybe I am a dinosaur, but I hate the emails without topic. :)

**Comment by eldy** [comment]
Sending email without topic become today useless.
Nearly 90% of emailing systems move emails into SPAM (or at least decrease SPAM score) when no topic is provided. So i don't think this is a good idea, even if protocol allows it.

**Comment by marcosgdf** [comment]
Well, we could let the user and the developer decide.

**Comment by simnandez** [comment]
I think is a good restriction, @eldy thinks is a good restriction, @feliserv tinks is a good restriction... there have been no more opinions... I close the issue.
