### ISSUE TITLE
Feature request: can't kill dolibarr Session

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#6988]
# Feature request
- I want to kill dolibarr user sessions. 
- I want to use dolibarr without user login.
- I need to know how does it work with PHP sessions.

## Environment
- **Version**: *5.0.4*
- **PHP**: *7.0.1*
- **Database**: *MySQL*

## Expected and actual behavior
- I want  to use Dolibarr without session login.

**Comment by eldy** [comment]
The only solution to be able to kill session from dolibarr is to introduce a hole in your infrastructure setup.
Configure your php and apache so directory that contains session can be read by web app. Then into menu admin tools, session, you will be able to see and delete a session. But this is a security hole.

Using without session is not possible.

**Comment by simnandez** [comment]
I close the issue
