### ISSUE TITLE
Minimum price control for supplier proposals

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#6993]
# Bug
When updating a supplier proposal with the new prices the minimum price control prevents the update

## Environment
- **Version**: 5.0.3
- **OS**: Windows 10 pro 64 bits
- **Web server**: Apache 2.4.25 on Wampserver 3.0.8
- **PHP**: 7.1.6
- **Database**: MariaDB 10.2.6
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
When updating the prices on supplier proposal, if the new one is lower than the minimum selling price we are not allowed to change that price.
This kind of control is very nice for custommer proposal but not for supplier ones !

## Steps to reproduce the behavior
On a line type a value 
lower than the minimum selling price.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[card.zip](https://github.com/Dolibarr/dolibarr/files/1070410/card.zip)

## Suggested implementation
On "../htdocs/supplier_proposal/card.php" comment the lines 813, 814, 815 to avoid the minimum price checking.
See the attached file behind.

**Comment by atm-arnaud** [comment]
@eldy this issue could be closed thank to a previous merge
