### ISSUE TITLE
Bug : Variables in mass mails do not work

### ISSUE THREAD

**Issue by WideeFr** [Dolibarr/dolibarr#6998]
# Bug
When I want to send bulk invoices, I can not use the variable __THIRDPARTY_NAME__.

The variable __REF__ is set to __REFCLIENT__
The variable __REFCLIENT__ is set to __THIRDPARTY_NAME__.
These variables are correctly assigned when sending mail from the third party invoice page.
The problem only arises from the form of mass mailing of invoices by mail

## Environment
- **Version**: [*since 5.0.1*]
- **OS**: [*Debian 8*]
- **Web server**: [*nginx 1.10.3*]
- **PHP**: [*PHP 7.0.20*]
- **Database**: [*Mysql 5.5.55*]
- **URL(s)**: [*/compta/facture/list.php*]

**Comment by eldy** [comment]
A lot of changes were done into 6.0 around variable for emailings. So let's wait to see if it is fixed in 6.0

**Comment by WideeFr** [comment]
Thanks for your response. i'll wait.

**Comment by eldy** [comment]
Is it ok with 6.0.1 ?

**Comment by WideeFr** [comment]
Sorry for the response time, but I had to install Dolibarr 6.0 on a test server.

I just tested with version 6.0.3 and the problem is still present

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
