### ISSUE TITLE
Bug: Champ 'c.fk_input_reason' inconnu dans field list

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#6999]
# Bug

## Environment
- **Version**: 6.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u2
- **URL**: /commande/card.php?id=21

## Report
Champ 'c.fk_input_reason' inconnu dans field list

**Comment by eldy** [comment]
Do you have the field fk_input_reason into table "commande" ?

**Comment by grandoc** [comment]
Yes I do have it

**Comment by eldy** [comment]
Still pb with stable version 6.0.1 ?

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
