### ISSUE TITLE
#bug Decrease real stocks on direct invoicing

### ISSUE THREAD

**Issue by SBA18** [Dolibarr/dolibarr#7002]
Hi,

I already report this issue before for the version 4/above but I'm dealing with the same. Let me explain :

I configure in stock module to decrease the real stock at shipping classification closed and it works good when the work-flow start by a customer order/shipment. But if I make a direct invoice for a customer the stock is not decreasing. So I have to chose one of this options in stock module either in shipment closed of in invoice validation.

Why it didn't decease the stock automatically like the POS do and who can I chose these two options because I need the two.

Thanks.

## Environment
- **Version**: Dolibarr v6 beta
- **OS**: windows 10
- **Web server**: xampp
- **PHP**: v7.1

**Comment by BebZ** [comment]
If you use both methods, you will decrease the stock twice when you create invoice after the wor-flow start by a customer order/shipment.
I think it's not the behaviour you would like to have.
When creating direct invoices there is no possibility to distinguish a direct invoice from another type which is sourced from an order/shipement.
Except if you would like to code something that allows it.

**Comment by SBA18** [comment]
Thanks for the reply, but first you can not use now the 2 options. You have to chose one.
When invoice is sourced from order there are relationship and you see the source. but direct invoicing you don't need a source. customer come buy some stuffs and you make a invoice. But this product is not decrease in the stock as it would be. Already the POS do auto decrease stock and I just went to apply to direct invoicing without dealing to make a order , shipment etc....

Hope you understand..

**Comment by BebZ** [comment]
True and hopefully it is mandatory to choose one. You have to read carefully what i said, please : 
you will decrease the stock twice when you create invoice after the "work-flow start by a customer order/shipment."
Maybe you can add some code to Dolibarr to say "i want to use the 2 options" but only decrease stock one time when I create the invoice and the decreasing is alreday done by order...
Good luck

**Comment by eldy** [comment]
As BebZ sais, if you enable the two choice, your stock will be decreased twice.
Note that you have an option into POS module to say decrease stock from POS because we know when creating invoice from POS that there is no order, so we are sure to not have stock already decreased. For all other cases, only user know if stock was already decreased or not when you make the invoice. For this reason, you have to change tock manually depending if you need or not decrease on manual invoice. But if you choose to decrease on order, your should not make invoice without order, or there is a fails in your process.

**Comment by SBA18** [comment]
Thank you for your reply @eldy. But I have a simple question : Why there is a possibility to create a direct invoice if I don't have to make a invoice without a order. Like shipment you have make a order to make a shipment. Why is not the same case for invoicing. 

Sorry but I don't understand yet by make direct invoice the stock is not decreasing like it should be.
