### ISSUE TITLE
Bug: Supplier Proposal Errors

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#7006]
# Bug
When creating a supplier proposal, the following issues occur:

- [ ] When selecting a predefined product, the quantity is not maintained - always defaults to 1.  If price is for 12pcs then it should preselect 12 and not 1.  At present, we have to manually enter the required quantity.
- [ ] When selecting a predefined product, the line asks for supplier reference.  It should pre-fill the existing reference but it doesn't.  Typing a new reference is accepted but does not show anywhere.  The field remains blank.  Nothing shows on the pdf either.

## Environment
- **Version**: 5.0.3

**Comment by aljawaid** [comment]
- [ ] If using product units in hidden options, the units show on the screen but do not follow through on the order or the invoice.

**Comment by frederic34** [comment]
This is an old version, it's probably closed in a recent version, if not please reopen.
