### ISSUE TITLE
Bug: Customer Outstanding Balance Missing

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#7007]
# Bug
In v4.0.4, the customer pending unpaid balance was shown on draft invoice screen and also on the 'not paid' invoice screen.

Since v5.0.0 the remaining unpaid amount is only shown on the draft invoice screen.  The outstanding balance should be shown at all time instead of having to go to the customer tab each time to find the total remaining to pay by the customer.

## Environment
- **Version**: 5.0.0, 5.0.1, 5.0.2, 5.0.3

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
