### ISSUE TITLE
SPEC : use database type "numeric" to store monetary values

### ISSUE THREAD

**Issue by ffries** [Dolibarr/dolibarr#7013]
# Present behavior

Some modules use "numeric" type, others use "real" type:

llx_paiement.amount = numeric(24,8)
llx_don.amount = real
llx_chargesociales.amount = real
llx_paiementcharge.amount = real
llx_payment_donation.amount = real
llx_payment_expensereport.amount = real
llx_payment_loan.amount_capital  = real
llx_payment_loan.amount_insurance = real
llx_payment_loan.amount_interest = real
llx_payment_salary.salary = real
llx_prelevement_bons.amount = real
llx_prelevement_facture_demande.amount = real
llx_prelevement_lignes.amount = real
llx_societe.capital = real
llx_tva.amount = real

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/tables/llx_accounting_bookkeeping.sql
debit double NOT NULL, -- FEC:Debit
credit double NOT NULL, -- FEC:Credit
montant double NOT NULL, -- FEC:Montant (Not necessary)
multicurrency_amount double, -- FEC:Montantdevise

# Expected behavior
SQL standards require to use "numeric" type to store monetary values. Using "real" type may result in rounding errors, which is not acceptable for accounting.

All types should be numeric(24,8).

References:
dev.mysql.com/doc/refman/5.7/en/floating-point-types.html

> MySQL permits a nonstandard syntax: FLOAT(M,D) or REAL(M,D) or DOUBLE PRECISION(M,D). Here, (M,D) means than values can be stored with up to M digits in total, of which D digits may be after the decimal point. For example, a column defined as FLOAT(7,4) will look like -999.9999 when displayed. MySQL performs rounding when storing values, so if you insert 999.00009 into a FLOAT(7,4) column, the approximate result is 999.0001.

dev.mysql.com/doc/refman/5.7/en/fixed-point-types.html :

> The DECIMAL and NUMERIC types store exact numeric data values. These types are used when it is important to preserve exact precision, for example with monetary data. In MySQL, NUMERIC is implemented as DECIMAL, so the following remarks about DECIMAL apply equally to NUMERIC.

www.postgresql.org/docs/10/static/dataty...type-numeric-decimal

> The type numeric can store numbers with a very large number of digits. It is especially recommended for storing monetary amounts and other quantities where exactness is required. Calculations with numeric values yield exact results where possible, e.g. addition, subtraction, multiplication. However, calculations on numeric values are very slow compared to the integer types, or to the floating-point types described in the next section.

* Modification of the PHP code with correct type (when needed to store money).
* Upgrade of database using: ALTER TABLE nom_table
ALTER COLUMN nom_colonne TYPE numeric;
* Modify developer guide to inform developers:
https://wiki.dolibarr.org/index.php/Langages_et_normes

# Discussion
Please discuss this proposal and I will modify the SPEC.

**Comment by kellogsgit** [comment]
It might be interesting to modify developer rules:
https://wiki.dolibarr.org/index.php/Langages_et_normes

Please add:
"- numeric(24,8) pour une valeur monétaire"

**Comment by kellogsgit** [comment]
Same question here, in the new developments around accounting, monetary values are stored using double, which are "cents" or "centimes" in French:

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/tables/llx_accounting_bookkeeping.sql
  debit                 double NOT NULL,			-- FEC:Debit
  credit                double NOT NULL,			-- FEC:Credit
  montant               double NOT NULL,			-- FEC:Montant (Not necessary)
  multicurrency_amount  double,						-- FEC:Montantdevise

Those values should be simply "numeric", otherwize it might conflict with other numeric values when doing joins using modules.

Furthermore, it is the job of databases to optimize numeric queries. PostgreSQL will treat them as long and you don't need to worry about optimizing them.

**Comment by aspangaro** [comment]
@kellogsgit I'm ok with your reflection.
I proposed a first patch on v7 for type real. (v6 is closed. Beta status since one week. SQL change not possible except major bug).
Type double also used on a lot of other field, it's aproximate but with 15 digits. It's enough to store money but for the uniformity. Another patch coming.

**Comment by eldy** [comment]
Oops, i validated the PR, instead of setting it to "pending", before creating the branch 6, so i have to revert it ?
Can you resubmit it ? If not, don't worry, i will find a solution to reapply it after branch v6 has been created using advanced git commands

**Comment by aspangaro** [comment]
@eldy Don't worry, I push a new PR more complete as soon as possible. You can revert it for the moment.
Sorry for the inconvenience

**Comment by ffries** [comment]
Great news, thanks.
