### ISSUE TITLE
SPEC : accounting periods within accounting year

### ISSUE THREAD

**Issue by ffries** [Dolibarr/dolibarr#7015]
# SPEC
This is a public discussion about the possible implementation of accounting periods within an accounting year. Before implementing a feature, I would like to discuss it in public.

# Present behavior
Only the notion of fiscal year is supported.

# Expected behavior
OpenERP/Odoo has the notion of accounting periods within an accounting year. 
A fiscal period has a starting date and an end date within a fiscal year.
A fiscal period is attached using N-1 relationship to a fiscal year.
A fiscal year can be split in N fiscal periods.

Most of the time, a period can be a month or a trimester. Examples : there can be 12 monthly periods in a fiscal year or 4 trimestrial periods in a fiscal year. 

In fact, this is completely configurable. Example : a first fiscal year can last 1 year and 45 days. In this case, upon agreement of the fiscal administration, you may configure a starting period of 45 days and then add monthly periods. It may also solve issues when you are switching from a monthly VAT declaration to a trimestrial VAT declaration.

Also, it serves as a base to VAT declaration, as each financial period is designed to be the reference (as for dates) of a VAT declaration.

# Discussion
Let us please discuss this issue in public and I will modify the SPEC accordingly.

**Comment by papoteur-mga** [comment]
Helo,
Seems to me to be a good idea. This is a manner to deal with Vat declarations.
