### ISSUE TITLE
Link chart of accounts and bookkeping using rowIDs

### ISSUE THREAD

**Issue by ffries** [Dolibarr/dolibarr#7023]
This will not be implemented.

****

Any change in the accounting chart might break bookeeping, because bookkeeping and chart of accounts are linked using account names, not IDs. We propose to link with IDs.

# Current behavior

llx_accounting_bookkeeping is linked to llx_accounting_account using account name.
Therefore, it is difficult to run SQL joins and later build a complete journal.

# Expected behavior

Replace 
llx_accounting_bookkeeping.numero_compte         varchar(32) NOT NULL,	
with
llx_accounting_bookkeeping.numero_compte_rowID         int NOT NULL,	

I will comment later, have no time to comment now.
We might need to duplicate chart of accounts on each year.

**Comment by eldy** [comment]
We don't want to have strict link.
When record are wrote into bookeeping, if you change something on the business side, it must not be changed on bookeeping side. Once an account has been affected, it must not be modified. This is important to be compiant with most countries laws. If you need to modifiy it, this must be done using the bookeeping tool, but there is then no more link with business events.

**Comment by ffries** [comment]
Okay, you are right, sounds clear.
