### ISSUE TITLE
Feature Request: Check VAT number from VIES

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#7037]
VIES service provide a SOAP webservice to check any VAT Number
More details on http://ec.europa.eu/taxation_customs/vies/technicalInformation.html

> For the SOAP service you may send your xml request by using the following WSDL link:
> http://ec.europa.eu/taxation_customs/vies/checkVatTestService.wsdl
> and by using the below values (common for all Member States/ CountryCodes) for each required result:
> 
>  
> “vatNumber” value=100, response= VALID
> “vatNumber” value=200, response = INVALID
> 
>  Please note that for the actual use of SOAP service you may refer to Question 16 of the FAQ page.
> Thank you in advance for your understanding.

**Comment by eldy** [comment]
This feature seems to be already implemented, from the third party sheet.

**Comment by camlafit** [comment]
I know we have a popup action to get vies information, but not an automatic control on save action for example.
