### ISSUE TITLE
Bug: Cannot change multicurrency code in 5.0 with PostgreSQL databases

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#7040]
# Bug

## Environment
- **Version**: 5.0.4

**Comment by eldy** [comment]
Are you talking about edition or rate from page .../htdocs/admin/multicurrency.php ?

**Comment by marcosgdf** [comment]
I am talking about edition.

**Comment by kellogsgit** [comment]
PostgreSQL support might be broken, read: 
https://github.com/Dolibarr/dolibarr/issues/7049

**Comment by ffries** [comment]
Please point out the exact page or feature that is failing and I will check the SQL code.
