### ISSUE TITLE
Bug: Calculations aren't being done correctly in "Customer Invoices"

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7046]
# Bug
Calculations aren't being done correctly in "Customer Invoices".

## Environment
- **Version**: develop
- **URL(s)**: /compta/facture/card.php

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![screenshot-dolibarr-2017-06-20-11-45-47](https://user-images.githubusercontent.com/23050598/27329846-1369a8d8-55af-11e7-8d0f-f746eb5f837e.png)

**Comment by simnandez** [comment]
Works for me

![screenshot_select-area_20170706120816](https://user-images.githubusercontent.com/881833/27906478-fa1cbf9a-6243-11e7-9958-56523cc5e2cd.png)

**Comment by ruistrecht-alt** [comment]
I created a new invoice and the calculations were done correctly, maybe it was an issue regarding number accuracy, rounding and limits.
To fix the issue regarding this specific invoice and payment, I recalculated and changed the values in the DB tables.
If this happens again in the future I'll repost and reopen this issue, thank you for your attention.
