### ISSUE TITLE
Incoterms are not maintained when confirming and quote

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#7047]
Just tested this on a demo server, and I can confirm that incoterms are not maintained when confirming one quote.

Steps to reproduce:
1. Create a quote and just select the desired incoterm.
2. Confirm that quote by clicking on Configure accepted/refused.
3. Click on the (PROVxxx) created, and you will see that the incoterms are no longer there.

Expected behavour:
To have incoterms conditions maintained all through from quote up to the invoice.

**Comment by eldy** [comment]
Do mean lost on order create from proposal/quote or lost on invoice created from proposal/quote ?

**Comment by saxa** [comment]
Yes, they do not get forward on both. Neither on creation of the order from the quote, neither from creation of the invoice from the order.

**Comment by saxa** [comment]
I will check this if this is still presend in the 11.x series.
