### ISSUE TITLE
FIX: Use Multicompany with REST API

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#7054]
# Bug

## Environment
- **Version**: 5.0.4 and 6.0.0 beta
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Unix)
- **PHP**: fpm-fcgi 7.0.16
- **Database**: MySQL or MariaDB 5.5.54-MariaDB
- **URL**: /api/index.php

## Report
login functionnal but not get,post,delete function because only first entity is call

Correction: add  this lines before the include of  main.inc.php in the api/index.php file
then you need to add in your  header DOLAPIENTITY  with your DOLAPIKEY with your Curl request

$DOLAPIENTITY = $_SERVER['HTTP_DOLAPIENTITY'];
$entity=(! empty($DOLAPIENTITY) ? (int) $DOLAPIENTITY : (! empty($DOLAPIENTITY) ? (int) $DOLAPIENTITY : 1));
if (is_numeric($entity)) define("DOLENTITY", $entity);

**Comment by eldy** [comment]
Added into v7

**Comment by pciavald** [comment]
This issue description helped me solve my issue but i think the current behavior is not correct (dolibarr 12.0.2, REST 12.0.2, multicompany 12.0.0).

When using the API explorer, i can login specifying the entity i'm interested in (entity 4) and get a token. From there i can query the products with the token but only the products from entity 1 come up, while generating a token for entity 4 should imo get products for entity 4 by default. Specifying '&entity=4' in the product query also does not help.

Specifying DOLAPIENTITY in the headers does work but it seems getting a token for the right entity should work.

Thanks
