### ISSUE TITLE
Issue with PHP timezone on dict.php (Doli 5.0.4)

### ISSUE THREAD

**Issue by caos30** [Dolibarr/dolibarr#7061]
# Bug
When accessing to Dictionaries (/admin/dict.php), Dolibarr 5.0.3-4, the browser remain empty (blank page). if you activate displaying of PHP errors at the top of the dict.php script it show a message like this:

> **Fatal error:**  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /var/www/vhosts/imasdeweb.com/sergi.imasdeweb.com/htdocs/core/lib/date.lib.php:129
> 
> Stack trace:
> 
> #0 /var/www/vhosts/imasdeweb.com/sergi.imasdeweb.com/htdocs/core/lib/date.lib.php(129): DateTime->__construct()
> #1 /var/www/vhosts/imasdeweb.com/sergi.imasdeweb.com/htdocs/core/modules/modAdherent.class.php(333): dol_time_plus_duree(1498531126, 1, 'y')
> #2 /var/www/vhosts/imasdeweb.com/sergi.imasdeweb.com/htdocs/core/lib/admin.lib.php(952): modAdherent->__construct(Object(DoliDBMysqli))
> #3 /var/www/vhosts/imasdeweb.com/sergi.imasdeweb.com/htdocs/admin/dict.php(504): compl in **/var/www/vhosts/imasdeweb.com/sergi.imasdeweb.com/htdocs/core/lib/date.lib.php** on line **129**

It doesn't happen on every server, only if the timezone settings are not well setted up.

## Environment
- **Version**: 5.0.3, 5.0.4
- **OS**: Linux 3.10.0-514.6.2.el7.x86_64
- **Web server**: Apache
- **PHP**: 5.4.16
- **Database**: MySQL
- **URL(s)**: htdocs/admin/dict.php?mainmenu=home

## Expected and actual behavior

I edited the file /htdocs/conf/conf.php adding this line:

`date_default_timezone_set('America/Hermosillo');`

with my timezone and the error disappear on visiting again the dict.php URL ! ;)

# Feature Request
Be able to set the timezone from the admin panel on Dolibarr. Maybe on Settings/Environment? Because this would be recommended anyway, because in a same server perhaps we need to install more than dolibarr to different companies located on different timezones! 

Excuse me if maybe it's already possible to set the timezone on Dolibarr... i've not found it.

**Comment by eldy** [comment]
It is not a good practice to have this set by application (it is just a work around to avoid error).
Having this error message means the PHP was not correctly installed. I think bug should be reported to the team that make the php distribution package.

**Comment by caos30** [comment]
Yes, i know that the error is because a not correctly PHP installation on server. But i think that Dolibarr can be smart enough to avoid it, or even to let admin user to set timezone on Settings section, or in conf.php file, or even ask for timezone during installation.

I'm newbie with Dolibarr, **can the admin user set timezone from admin panel? i've not found on forums or wiki, but i would appreciate an explicit confirmation.** If not, then i will add a new issue about this matter, proposing to let set timezone on admin panel. Even a user timezone settings would be interesting.

You must know that in Mexico there are people with 3 different timezones. So a same instance of Dolibarr should display datetimes in the timezone of each user... ideally.

Well, it really is a pain this matter of timezones... always.
Cheers.

**Comment by caos30** [comment]
Hey, i found the solution. @eldy i means that Dolibarr has natively a solution for this, at least since 5.X.
You only must go to `Setup -> Other setup` and indicate the timezone you wants simply adding a new system constant called 'MAIN_SERVER_TZ' (see attached picture below). Great!

![seleccio_567](https://user-images.githubusercontent.com/1767547/32867623-72b441d6-ca2b-11e7-86bd-202455311b7d.png)

Although it would be nice that Dolibarr don't let it empty if you don't put nothing, because this continue generating execution errors in some server [bad] configurations.

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...
