### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7064]
Hi sorry i'm not sure if i have to post this here or elsewhere.
The link in wiki to the dolibarr-module-template is dead

- https://wiki.dolibarr.org/index.php/Developpement_module#Exemple_de_mod.C3.A8le_de_module_externe
- https://github.com/rdoursenaud/dolibarr-module-template

tks

**Comment by dolibarr95** [comment]
@rdoursenaud can you help please ?

**Comment by eldy** [comment]
Fixed

Note that with 6.0, a rewrite on this tool has been started.
The goal is to manage the generation of modules and files directly from interface with more code generated and more powerfull feature.
New template in 6/develop is in directory htdocs/modulebuilder/template

**Comment by dolibarr95** [comment]
Hi
Ok it's perfect !
Does it mean that the module created in the old way won't be compatible with Dolibarr 6 ?

tks
