### ISSUE TITLE
Bug: Error Champ 't.default_vat_code' inconnu dans field list

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#7065]
# Bug

## Environment
- **Version**: 6.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u2
- **URL**: /product/price.php?id=98

**Comment by eldy** [comment]
Can you provide the full error and original message ?

**Comment by grandoc** [comment]
It is a copy-paste of the original message

**Comment by simnandez** [comment]
I tested, access to price, modify default price, delete old prices without issues

**Comment by simnandez** [comment]
I close this issue, because is not reproducible in maintened versions
