### ISSUE TITLE
Cant access to dictionary to introduce options

### ISSUE THREAD

**Issue by amoreira1** [Dolibarr/dolibarr#7067]
since we made the upgrade to version 5.0.3 i cant access to the library. It appears HTTP 500 error code 

Help appreciated .

Thanks

**Comment by eldy** [comment]
Can you have a look into your apache error.log ?

**Comment by eldy** [comment]
Can you try with 5.0.4 ?

**Comment by amoreira1** [comment]
How can i search that ?

**Comment by amoreira1** [comment]
I delete all files and re-installed the new version .

To avoid any problems i put English language.

Result was exactly the same. I cant have acess to dictionary

Help is very very much apreciated
