### ISSUE TITLE
Feature: Free text line in documents (commercial proposals, etc.)

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7071]
# Feature Request
Free text line in documents (commercial proposals, etc.). Add a new type of entry instead of just Product and service, called Free text (suggestion)

## Use case
Sometimes we need to customize a certain line with a small introductory line, like so:
Article 4.1 - Electrical goods <- Free text line
XB64 Power cord <- Product line

## Suggested implementation
Add a new type of entry instead of just Product and service, called Free text with a text box. Ignore rest of the columns to the right

**Comment by atm-maxime** [comment]
In the meantime, the external module subtotal does that.

**Comment by hregis** [comment]
and Milestone ;-)
