### ISSUE TITLE
Bug: Documents in commande/card.php can not be removed

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#7075]
# Bug
In https://[…]/fourn/commande/card.php you can not remove a document by clicking on the "trash-icon" (?id=x&action=remove_file&file=[…]). Nevertheless, the success-message will be displayed. 

Removing the same document at https://[…]/fourn/commande/document.php works as expected.

## Environment
- **Version**:5.0.3 - 5.0.4
- **OS**: Linux
- **Web server**: Apache

**Comment by aljawaid** [comment]
I have the same issue
