### ISSUE TITLE
Feature Request: when trad not found in language XX_yy, Dolibarr shoud check in XX_zz before EN_us

### ISSUE THREAD

**Issue by delcroip** [Dolibarr/dolibarr#7076]
# Feature Request
 when trad not found in language XX_yy, Dolibarr shoud check in XX_zz before EN_us so only specificities of version yy could be documented in XX_yy

## Use case
when I set dolibarr in fr_BE, and instead of having half french and half english ( some module don't have fr_BE but only FR_fr) I will have everything in french.

**Comment by delcroip** [comment]
Original discussion: https://www.dolibarr.fr/forum/12-howto--aide/59175-probleme-de-langue-d-affichage-francais-anglais

**Comment by eldy** [comment]
when trad is not found in language XX_yy, Dolibarr already check in XX_xx before EN_us
So for fr_BE, all you have to translate is the delta with fr_FR
