### ISSUE TITLE
BUG: Dont save the data of the extrafields of expense report

### ISSUE THREAD

**Issue by jmsandovalp** [Dolibarr/dolibarr#7085]
Dolibarr 5.0.4

I did the next actions to get the error:
1. I click in the option New (Expense Report)
2. I write the information that I need it, including the extrafields (../expensereport/card.php)
3. When I click in the button _Create expense report_ the information that I had written in the extrafields, it lost. In another words, the information of extrafields of that expense report didn't save in that step.

Thanks.

**Comment by atm-maxime** [comment]
Has been fixed in 6.0
