### ISSUE TITLE
Feature Request: Add Multiple Products to Category at Once

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#7090]
## Environment
- **URL(s)**: /categories/viewcat.php

## Expected and actual behaviour
Only one product can be added to the category at one time.

# Feature Request
Ability to allow to add multiple products categories at once based on unique search criteria (i.e. by knowing their reference)

## Use case
Mass entry of products per category instead of one by one through the same form.

## Suggested implementation
Allow use of `comma` or `+` to allow multiple products to be added to category at once.  Keep ajax search for single products but allow to also include `product1,product2` or `product1+product3` so that both mentioned products are added to the category.

**Comment by klikict** [comment]
Any update on this request? Would make Dolibarr even better!
