### ISSUE TITLE
Bug: ; is missing and SQL DB ERROR on 5.0.0-6.0.0.sql file

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#7098]
# Bug
Hi
I try develop branch on a new Debian 9 server : 

SQL commands give error 
For Request 200, there is a ";" that is forgottent, 
But no idea for Error of the 41 and 42 sql commands

## Environment
- **Version**: 6.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.0.19-1
- **Database**: MySQL or MariaDB 5.5.5-10.1.23-MariaDB-9+deb9u1
- **URL**: install/upgrade.php?action=upgrade&selectlang=en_US&versionfrom=5.0.0&versionto=6.0.0

## Report
Request 41 sql='ALTER TABLE llx_adherent MODIFY COLUMN state_id integer DEFAULT NULL;'
Error DB_ERROR_1067: ALTER TABLE llx_adherent MODIFY COLUMN state_id integer DEFAULT NULL;
Invalid default value for 'datefin'
Request 42 sql='ALTER TABLE llx_adherent MODIFY COLUMN country integer DEFAULT NULL;'
Error DB_ERROR_1067: ALTER TABLE llx_adherent MODIFY COLUMN country integer DEFAULT NULL;
Invalid default value for 'datefin'
Request 43 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('PRODUCT_CREATE','Product or service created','Executed when a product or sevice is created','product',30);'
Request 199 sql='ALTER TABLE llx_blockedlog_authority ADD INDEX signature (signature);'
Request 200 sql='INSERT IGNORE INTO llx_product_lot (entity, fk_product, batch, eatby, sellby, datec, fk_user_creat, fk_user_modif) SELECT DISTINCT e.entity, ps.fk_product, pb.batch, pb.eatby, pb.sellby, pb.tms, e.fk_user_author, e.fk_user_author from llx_product_batch as pb, llx_product_stock as ps, llx_entrepot as e WHERE pb.fk_product_stock = ps.rowid AND ps.fk_entrepot = e.rowidUPDATE llx_bank SET label= '(SupplierInvoicePayment)' WHERE label= 'Règlement fournisseur';'
Error DB_ERROR_SYNTAX: INSERT IGNORE INTO llx_product_lot (entity, fk_product, batch, eatby, sellby, datec, fk_user_creat, fk_user_modif) SELECT DISTINCT e.entity, ps.fk_product, pb.batch, pb.eatby, pb.sellby, pb.tms, e.fk_user_author, e.fk_user_author from llx_product_batch as pb, llx_product_stock as ps, llx_entrepot as e WHERE pb.fk_product_stock = ps.rowid AND ps.fk_entrepot = e.rowidUPDATE llx_bank SET label= '(SupplierInvoicePayment)' WHERE label= 'Règlement fournisseur';
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'llx_bank SET label= '(SupplierInvoicePayment)' WHERE label= 'Règlement fourniss' at line 1
Request 201 sql='UPDATE llx_bank SET label= '(CustomerInvoicePayment)' WHERE label= 'Règlement client';'

**Comment by eldy** [comment]
For line 200, it has been fixed.
For request 41 and 42, pb comes because of old corrupted data in mysql (old bug in old mysql version)

What happen if you launch alone
ALTER TABLE llx_adherent MODIFY COLUMN datefin datetime NULL;

If you have an error, try to run this 
ALTER TABLE llx_adherent MODIFY COLUMN datefin datetime DEFAULT '2001-01-01 00:00:00';
then rerun migration
