### ISSUE TITLE
payment class name conflict

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#7109]
# Bug
In an external module I get this message
Fatal error: Cannot redeclare class ModeleNumRefPayments in /dolibarr/htdocs/core/modules/supplier_payment/modules_supplier_payment.php on line 25

## Environment
- **Version**: 5.0.3
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 5.6
- **Database**: mysql
- **URL(s)**: module

## Expected and actual behavior
In the same function a payment is created for a customer invoice , and a payment is created for a supplier invoice.
Problem is that the classes handling payment on customer invoices and on supplier invoice has the same name "ModeleNumRefPayments"
definitions in htdocs/core/modules/payment/modules_payment.php for customer
and /htdocs/core/modules/supplier_payment/modules_supplier_payment.php

Suggesting Rename class in /htdocs/core/modules/supplier_payment/modules_supplier_payment.php to ModeleNumRefSupplierPayments

**Comment by atm-arnaud** [comment]
@eldy This issue could be closed thank a previous merge
