### ISSUE TITLE
Unable to edit third party in client invoice

### ISSUE THREAD

**Issue by svalo** [Dolibarr/dolibarr#7118]
# Bug
Unable to edit third party in client invoice when in draft status

As stated in the [wiki](https://wiki.dolibarr.org/index.php/Setup_Other#Invoice_module) the variable `FACTURE_CHANGE_THIRDPARTY` should allow one to edit the thirdparty when the invoice is in draft status.

The commit which removed the functionality probably is https://github.com/Dolibarr/dolibarr/commit/3599f2c840ce3af24f7ed7af0005d4c2383ebcf1#diff-4ad8edad73c00c24c7cf271a2bdce679L2989

## Environment
- **Version**: 5.0 - 5.0.3
- **OS**: Linux
- **Web server**: Nginx
- **PHP**: 7.0
- **Database**: postgres
- **URL(s)**: http://doli.url/compta/facture.php?facid=xyz

## Expected and actual behavior
Expected: When visualizing a client invoice which is in draft mode a button allowing editing the third party should appear next to the third party name

Actual: No button is showed

## Steps to reproduce the behavior
Open or create an invoice and ensure status is draft

**Comment by eldy** [comment]
Option FACTURE_CHANGE_THIRDPARTY was a hidden feature. It has been removed because it become useless. If you need to have a draft invoice on another third party, just clone the invoice an the other thirdparty and delete previous draft invoice.

**Comment by nach41710** [comment]
Hi I also think it was really useful and save a lot of steps:
You have to clone the invoice,
Delete the old one, if possible, if it is not possible you will need to modify the database.
Is there any plan to get this functionality again, please.

**Comment by simnandez** [comment]
I close the issue because the functionality has been removed

**Comment by ssbisoutions** [comment]
> Option FACTURE_CHANGE_THIRDPARTY was a hidden feature. It has been removed because it become useless. If you need to have a draft invoice on another third party, just clone the invoice an the other thirdparty and delete previous draft invoice.

but after using clone option the invoice number will be new....we will not get the same invoice number.....and in India this is common practice hence need some option to edit Third party name and keep the invoice number intact

**Comment by edupulpillo** [comment]
Completely agree.
If an option to "renumber" an invoice will be possible, then no problem. But that option does not exist.
Until the trimester declaration of invoices occurs, or until any communication to the tax authorities, changes/updates in the invoices should be allowed, under the responsibility of the user with enough rights.

**Comment by edupulpillo** [comment]
Also the attached files to the original invoice are not copied to the cloned one.

**Comment by orloxgr** [comment]
Please bring back this feature. It can save hours of work.

**Comment by hregis** [comment]
If it is a draft invoice, there is no incrementation yet and a renumbering option is not essential!
If the invoice has already been validated and a number has been assigned, then a replacement invoice or a credit note must be made in order to cancel this invoice.

**Comment by orloxgr** [comment]
> If it is a draft invoice, there is no incrementation yet and a renumbering option is not essential! If the invoice has already been validated and a number has been assigned, then a replacement invoice or a credit note must be made in order to cancel this invoice.

You are correct and this is why this function is needed.

**Comment by edupulpillo** [comment]
When a invoice is in draft mode can not be send by email.
Usually the draft mode for us is a "proforma invoice" that should be able to be send.
then if is approved, we convert it in normal invoice.
Also sometimes if the customer has branch companies, and they decide later to change the brother company that need to be invoiced and payed. So this means that now we need to do a new negative invoice canceling teh previous one, and invoice again with the another customer company.
So a lot of extra work, and a lot of more confusion in the accounting.

So please kindly bring back this feature, since is really useful.
