### ISSUE TITLE
Feature request : with email template choose if documents are attached or not

### ISSUE THREAD

**Issue by jfefe** [Dolibarr/dolibarr#7120]
# Feature Request
Add a parameter for templates to decide if documents are attached or not to email.

## Use case
With some emails templates, some users doesn't want to have document file attached to message.

## Suggested implementation
Add a flag `nodoc` into `llx_c_emails_templates` to store by template if we don't want attached doc. Modify `FormMail::get_form()` method.

**Comment by atm-maxime** [comment]
This has been implemented since then.
