### ISSUE TITLE
Feature Request: Print table heading on following pages

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#7151]
In my opinion it should be "standard" to print and repeat every table headings on subsequent PDF documents like invoices, supplier-orders and so on…

**Comment by SylvainLegrand** [comment]
Hello,

You right.
Some external module do it now, like mine : '[InfraSPack](https://www.dolistore.com/fr/modules/722-InfraSPack.html?search_query=infras&results=3)'.
You may find it on the [Dolistore](https://www.dolistore.com/fr/recherche?controller=search&orderby=position&orderway=desc&search_query=infras&submit_search=).
And the documentation [here](http://www.infras.fr/index.php/component/jdownloads/category/11-modules-dolibarr?Itemid=395).

Greetings,
Sylvain Legrand.
