### ISSUE TITLE
FIX: décalage de colonne paiement.php

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#7155]
# Bug

## Environment
- **Version**: 5.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Unix)
- **PHP**: fpm-fcgi 7.0.16
- **Database**: MySQL or MariaDB 5.5.54-MariaDB
- **URL**: /compta/paiement.php?facid=1174&action=create&accountid=

## Report

changer colspan=3 en colspan=2 en raison d'une colonne en trop entrainant un décalage
ligne 748 print '<td colspan="2" align="left">'.$langs->trans('TotalTTC').'</td>';

**Comment by atm-arnaud** [comment]
Bonjour,

Il est possible que le problème provienne d'un module complémentaire qui rajoute une colonne à cette liste.
Pourriez-vous nous faire une capture d'écran et nous la présenter ici afin de voir votre affichage. Car je n'ai actuellement pas d'erreur visible sur cette page (Version 5.0.7).

Peut être ceci est simplement résolu depuis une mise à jour récente.

Cordialement,

**Comment by ptibogxiv** [comment]
ça a été corrigé en V6 ( je n'utilise plus la v5 mais ça a sans doute été corrigé)

**Comment by atm-arnaud** [comment]
Très bien merci pour ce retour. @eldy cette issue peut donc être cloturée
