### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tetus** [Dolibarr/dolibarr#7156]
# Bug
While merging 2 third parties, got the following message
Warning: Invalid argument supplied for foreach() in /dolibarr/htdocs/societe/soc.php on line 171

## Environment
- **Version**: [5.0.3]
- **OS**: [Linux web 3.8.2-grsec #6 SMP Mon Apr 22 15:03:58 ART 2013 x86_64]
- **Web server**: [* Apache*]
- **PHP**: [* 5.6.30*]
- **Database**: [* MySQL or MariaDB 5.5.24-log*]
- **URL(s)**: [*Affected URL(s)*]

[<img width="1188" alt="captura de pantalla 2017-07-13 a la s 22 25 51" src="https://user-images.githubusercontent.com/7516807/28194474-dc6d967c-681a-11e7-8aff-8c8fd6c29556.png">
]

**Comment by tetus** [comment]
Update, I checked and the merge was completed. not sure why the error screen.

**Comment by eldy** [comment]
Fixed for 5.0.5 and +
