### ISSUE TITLE
USA Accounting Tables

### ISSUE THREAD

**Issue by cleverthings** [Dolibarr/dolibarr#7159]
I've created the SQL entries for USA Accounting tables (six digit GAAP), but since I don't know the French language, there were a few areas in the documentation that I was uncertain about.  I'd like for someone with Dolibarr expertise to check my work before I contribute it back to the core. I'd be happy to share the tables, but I'd like to have it reviewed before I do an official Pull Request to add them.  I'll work on a patch to submit for your review and approval.  Is anyone else already working on this or interested?

**Comment by cleverthings** [comment]
Here's where I'm at: I created USA-BASE (probably should call it US-GAAP) with Chart of Accounts which was pretty straightforward. For six digit GAAP, is this right?
select * from x_c_accounting_category;
| ASSETS       | Assets                                     | 1xxxxx                   |
| LIABILITIES  | Liabilities                                | 2xxxxx                   |
| STOCK-EQUITY | Stockholders Equity                        | 3xxxxx                   |
| REVENUE      | Revenue                                    | 4xxxxx                   |
| EXPENSES     | Expenses                                   | 5xxxxx                   |
| OTHER        | Other Revenue, Expenses, Gains, and Losses | 6xxxxx                   |
| INCTAX       | Income Tax Benefit                         | 7xxxxx                   |

I'm unsure of the default account table and need better documentation because the demo data didn't make sense to me. I need to make sure these get mapped to the right GAAP number:
ACCOUNTING_ACCOUNT_SUPPLIER
ACCOUNTING_ACCOUNT_CUSTOMER

SALARIES_ACCOUNTING_ACCOUNT_PAYMENT

ACCOUNTING_PRODUCT_BUY_ACCOUNT
ACCOUNTING_PRODUCT_SOLD_ACCOUNT
ACCOUNTING_SERVICE_BUY_ACCOUNT
ACCOUNTING_SERVICE_SOLD_ACCOUNT

ACCOUNTING_VAT_BUY_ACCOUNT
ACCOUNTING_VAT_SOLD_ACCOUNT
ACCOUNTING_VAT_PAY_ACCOUNT

ACCOUNTING_ACCOUNT_SUSPENSE
ACCOUNTING_ACCOUNT_TRANSFER_CASH

DONATION_ACCOUNTINGACCOUNT

LOAN_ACCOUNTING_ACCOUNT_CAPITAL
LOAN_ACCOUNTING_ACCOUNT_INTEREST
LOAN_ACCOUNTING_ACCOUNT_INSURANCE

**Comment by Darkjeff** [comment]
Hi cleverthings, I will check but to add a chart of account, we use external module. You can send me an excel sheet with the accounts in order to build the module

**Comment by cleverthings** [comment]
Perfect! I know the current focus is on the new branch, so I'll continue working and testing and then submit those to you later. I'll go ahead and close this issue. Thanks!

**Comment by WWE-Corey** [comment]
Was this ever completed? I am setting up Dolibarr but cannot find a US module
