### ISSUE TITLE
Bug: Shipments - Extrafields not working in ODT template

### ISSUE THREAD

**Issue by AlbioB** [Dolibarr/dolibarr#7168]
# Bug
Shipments - Extrafields not working in ODT template

## Environment
- **Version**: 5.0.1, 5.0.4
- **OS**: Debian GNU/Linux 8.8 (jessie)
- **Web server**: Apache 2.4.10
- **PHP**: PHP 5.6.30-0+deb8u1
- **Database**: MySQL Ver 14.14 Distrib 5.5.55

## Expected and actual behavior
When setting document extra fields and line extra fields, placing them in ODT template produces no effect. In output ODT is printed {object_options_xxx} and {line_options_xxx} instead of values.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

Document extra field:
![extrafield_doc](https://user-images.githubusercontent.com/13927690/28248344-9366871a-6a43-11e7-86aa-3fa6b2fa59a9.png)

Line extra field:
![extrafield_line](https://user-images.githubusercontent.com/13927690/28248346-97f456ae-6a43-11e7-8f07-9b041fc80d0e.png)

Document output:
![output](https://user-images.githubusercontent.com/13927690/28248349-99b2c03e-6a43-11e7-9200-140e0ac6b3c7.png)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
