### ISSUE TITLE
Bug: Unknown column 'ba.accountancy_journal' in 'field list'

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#7169]
# Bug

## Environment
- **Version**: 6.0.0-beta
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Unix)
- **PHP**: fpm-fcgi 7.0.16
- **Database**: MySQL or MariaDB 5.5.54-MariaDB
- **URL**: /adherents/subscription.php?rowid=1

## Report
Dolibarr a détecté une erreur technique.
You use an experimental or develop level of features, so please do NOT report any bugs, except if problem is confirmed moving option MAIN_FEATURES_LEVEL back to 0.
Voici les informations qui pourront aider au diagnostic:
Date: 20170717013139
Dolibarr: 6.0.0-beta
Niveau de fonctionnalités: 2
PHP: 7.0.16
Server: Apache/2.4.25 (Unix)
OS: Linux DiskStation 3.10.102 #15152 SMP Thu Jul 13 04:19:29 CST 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063

Url sollicitée: /adherents/subscription.php?rowid=1

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT d.rowid, d.firstname, d.lastname, d.societe, c.rowid as crowid, c.subscription, c.datec, c.dateadh as dateh, c.datef, c.fk_bank, b.rowid as bid, ba.rowid as baid, ba.label, ba.bank, ba.ref, ba.account_number, ba.accountancy_journal, ba.number FROM llx_adherent as d, llx_subscription as c LEFT JOIN llx_bank as b ON c.fk_bank = b.rowid LEFT JOIN llx_bank_account as ba ON b.fk_account = ba.rowid WHERE d.rowid = c.fk_adherent AND d.rowid=1
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'ba.accountancy_journal' in 'field list'

**Comment by aspangaro** [comment]
@ptibogxiv  Thanks, it's correct now !
