### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Mantraxyz** [Dolibarr/dolibarr#7177]
# Bug

## Environment
- **Version**: 5.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.31
- **Database**: MySQL or MariaDB 5.6.35
- **URL**: /index.php?mainmenu=home&leftmenu=

## Report
Warning: getdate(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/datacent/tst1.datacentersolutions.cl/core/lib/functions.lib.php on line 1456

**Comment by eldy** [comment]
This is not a dolibarr bug but a problem into your php installation that is not complete.
You must edit you php.ini to define explicitely the timezone.
