### ISSUE TITLE
Feature Request: API invoices, CRUD lines

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7180]
Like proposals, let's add get, push, put and delete instruction to the API for invoices.

**Comment by dolibarr95** [comment]
Hi

https://www.dolibarr.fr/forum/12-howto--aide/58888-documentation-api-rest?start=15#85664

**Comment by vvnt** [comment]
Thank you but sorry, I was not clear. CRUD for **lines** inside the invoice (like for proposals).

If we update an invoice, only the header of the invoice is updated (not the lines). For now, we need to delete the original invoice and to rebuild it (new PROV number).

**Comment by eldy** [comment]
Does this is still missing with 6.0 ?

**Comment by vvnt** [comment]
Yes, still missing with 6.0.

![dolibarr_api_invoice_no_line_level](https://user-images.githubusercontent.com/5360027/29990811-8f118a42-8f7e-11e7-8bcc-198216bbda73.png)

CRUD for lines exists for proposals, not for invoices.
