### ISSUE TITLE
Feature Request: Export invoices - Description for DEPOSIT missing - no reference info like in the view

### ISSUE THREAD

**Issue by fred-mevia** [Dolibarr/dolibarr#7208]
# Instructions
When you do an export of your invoices with each lines of invoices, if you have an Deposit invoice linked you don't find the reference in the "Description" column. 

# Bug
In the web view and the PDF export, you will find the information "Acompte + Référence". This information could not be found in the export file (invoices and lines)

**Comment by eldy** [comment]
Information is stored into field fk_remise_except that is not yet into list of exported field.
I move the PR as a feature request to add discounts details into export
