### ISSUE TITLE
This user is blocked. now what? 

### ISSUE THREAD

**Issue by THUFIR** [Dolibarr/dolibarr#7209]
How do I contact an adminstrator for your forum???

On the dolibarr forum I get this message:

×
Notice

Reminder failed: This user is blocked. If this is an error, please contact an administrator.

see also:

https://www.kunena.org/forum/general-questions-and-how-tos/148485-this-user-is-blocked-now-what#194129

**Comment by eldy** [comment]
You can send an email to contact@dolibarr.org with your login.
