### ISSUE TITLE
Feature request: Packing list

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#7210]
# Feature Request
Packing list is a list used to describe the goods shipped and how they are packed. It have only 
part number, short description, quantity, unit weight , total weight andd box number. It optionally
can have the container number. Would be nice to have a button in the shippments which would 
simply generate the packing list for the invoice created.

## Use case
It is used when you ship goods in bigger lots or batches. So noramlly a factory loading a container
prepares the list of items it has loaded into it, with the packing number and what exactly each packing contents are. Mostly used in international business, and reflects all the items which are invoiced.

## Suggested implementation
The easiest way would be to expand the shippment module and make it able to sort the items 
and quantities and create a sort of packing refference and then indicate the quantity
of the item. The module should then automatically caalculate the exact weight and voluem of the box
and prepare the total number of boxes or other packages the container have been loaded with.

## Suggested steps
To verify it yet.

**Comment by BebZ** [comment]
Who will be able to create such a module ? 
Who has implemented weight height and width of products ?
... it would be very useful also for customer to know in which carton is what product...
I have many examples of suppliers doing it well :)

**Comment by saxa** [comment]
To be honest I am willing on start working on it, but since its only in my free time i can do that it will for sure take long :) 
I have all the products or nearly all of them with weight and dimensions. In the spare parts business is quite useful to have this.
Examples are always welcome but I am doing it by hand for at least 15 years already :)

**Comment by Malaysiatic** [comment]
I am very interested in having this feature.
Just to have the item name, ref number and quantity would be fantastic.
If it had the weight, dimensions and volume that would be even better but not necessary at first.
Would it be possible to create a basic version of this first and then maybe build on it to add the extra information fields you mentioned?

**Comment by BebZ** [comment]
Yes, it is possible to finance a basic version... with finance :)
Let's start a funding campaign ! How much you want to put ? I can invest 300 € in the basic, and more in customizations.
Who can develop it and wirhte the detailled specifications ?

**Comment by BebZ** [comment]
Hello @saxa 

any news on te projetc ? My budget doubled, i can put 600€ if wished :)

**Comment by saxa** [comment]
Hi, I have not had any time to work on that unfortunately. I am also still in the will to go further with it. Let me see if I can work out anything in the upcoming month.

**Comment by najot36** [comment]
Hi, I'd be definitely interested in this feature. Could contribute a bit up to 150usd if needed.

**Comment by saxa** [comment]
Ok, lets try to define what would be the best way to implement it. My initial idea is to have a button in the sales order with written "Create Packing List" , clicking this button would then open a new tab where you could see all items in the order and have possibility to describe or select the preconfigured package types. By adding a package type we could have the possibility to add items to it and of course dimensions and tare weight. By having this info, I think the total weight would be easy to calculate and
we could end up with a report where items would be listed one by one with the package code or name in front of it.

Maybe I have to do a mockup or something to make it more clear.

Other option would be to extend the shippment module and add it these functionalities.

I am open to suggestions.

**Comment by najot36** [comment]
The features here seem good. My idea was an extension of expédition module
because you have to have in the packing list the exact list of items that
are in your shipment (sh slip).

What would be good would be to send both docs (sh slip and packing list)
through an email from the shipment tab. Like this our remote warehouse
receives the how to pack easily.

Thx
Dj

**Comment by dolibarr95** [comment]
Hi all
Please read :

- https://github.com/Dolibarr/dolibarr/pull/11653
- https://github.com/Dolibarr/dolibarr/issues/11636
