### ISSUE TITLE
Bug : supplier DISPATCH BATCH to stocks not working

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#7211]
# Bug
When you want to receive a supplier order with more than one batch per product the small button to explode the line is not working
## Environment
6.0.0-beta
fourn/commande/dispatch.php?id=4312
![image](https://user-images.githubusercontent.com/3694135/28678139-e00807f6-72ef-11e7-9a85-114781553373.png)

## Expected and actual behavior

![image](https://user-images.githubusercontent.com/3694135/28678237-23835968-72f0-11e7-8c10-80e03c445104.png)

## Steps to reproduce the behavior
try to clic on the surrounded by red small button on 6.0.0-beta

**Comment by fappels** [comment]
Works for me. Qty to dispatch has to be less then Qty ordered to be able to explode.

**Comment by eldy** [comment]
@BebZ do you still have trouble with release candidate ?

**Comment by BebZ** [comment]
![image](https://user-images.githubusercontent.com/3694135/29625738-d3c40056-882c-11e7-8711-2a6c7a92e233.png)

It works strangely , but you are right, it is necessary to decrease input field qty to dispatch 
to be able to input the field
BUT
the behaviour is anyway strange : 
for example on this screenshot, unable to edit qty on last input field it is not possible to edit it even if total qty is inferior !

![image](https://user-images.githubusercontent.com/3694135/29626032-c4dc1172-882d-11e7-9ea3-e2532f2e0959.png)

**Comment by fappels** [comment]
@BebZ can you check if my PR #7502 solves your issue?
@eldy did you remove the 'lessone' mode from batch products for easy input of batches and preserved the 'lessone' mode for a new future mode of easy input of serial numbers?

**Comment by eldy** [comment]
@fappels Yes, the "lessone" mode is for a future need:
Adding a button called "Enter by barcode scan". This will open a popup with an input field. When the user flash a barcode with its barcode reader and send the CR (send by the barcode reader to) it may fill the serial in line and the execute the lessone and reopen the popup for next input.
So a user can record a reception of a lot of products without using the keyboard.
