### ISSUE TITLE
BUG : Delete Variants on product card not workin

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#7213]
Dolibarr 6.0.0-beta

Delete a variant of product on product card doesn't work

To reproduce you need to first activate experimental and the module 
create variant attributes 
/variants/list.php?idmenu=16440&mainmenu=products&leftmenu=
 and variants values 
/variants/create_val.php?id=4
 

![image](https://user-images.githubusercontent.com/3694135/28678397-8f2cf098-72f0-11e7-9067-c4851246c0fc.png)

**Comment by ghost** [comment]
https://github.com/Dolibarr/dolibarr/pull/7216
