### ISSUE TITLE
Proposal PDF generation does not reduce number of pages when needed

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#7217]
# Bug
When reducing the volume of content of a proposal from 2 pages (possibly more) content to 1 page, the PDF does not reduce the number of pages.

## Environment
- **Version**: 5.0.4
- **OS**: Ubuntu Server LTS 16.04.2
- **Web server**: Apache 2.4.18
- **PHP**: 7.0.18
- **Database**: Mysql 5.7.19
- **URL(s)**: N/A

## Expected and actual behavior
Expected behavior
When generating a new proposal PDF after reducing the number of elements in the proposal list from 2 pages to 1 page, the PDF previously created with 2 pages should be reduced to a one page document.

Actual behavior
When generating a new proposal PDF after reducing the number of elements in the proposal list from 2 pages to 1 page, the PDF previously created with 2 pages, remains with 2 pages (the second one only having empty table)

## Steps to reproduce the behavior
Generate a new proposal with enough elements to be printed on 2 pages. Generate the PDF. Reduce the number of elements in the proposal to be a one page document. Generate the PDF. Still 2 pages produced, one being empty table with the total at the bottom.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-arnaud** [comment]
Hello,

I can't reproduce your request. Are you sure that you have enough space to include Payments list / BANK code etc.

Regards,

**Comment by dom-breizh** [comment]
Well, since them, I upgraded several times to version 7.0.1 and I cannot reproduce it any longer. But I had enough space for all the Payment information as I can remember.
