### ISSUE TITLE
Feature Request : Multiple add to propal/order/invoice

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#7218]
# Feature Request
There is a subject 7 years ago on the forum wich was seen almost 2 000 times (as of today)
People wanting to add more than one product at a time... it was really well described, but I am sure if no one answered it's because of this "addline" class, that is a nightmare to develop ?

Currently during Proposal/Order creation etc, We generally type the parts of ref code or label of the product to be entered in the product search box and then the drop down list get populated with the related products.
## Use case
For Example say we type "Choi" in the search text box
the drop down list gets populated with
Choi Kwang Do Uniform Red/Blue No. 13 Size 26
Choi Kwang Do Uniform Red/Blue No. 14 Size 28
Choi Kwang Do Uniform Red/Blue No. 15 Size 30
Choi Kwang Do Uniform Red/Blue No. 16 Size 32
Choi Kwang Do Uniform Red/Blue No. 17 Size 34

and say we need to add 1 of each product, this is not possible as currently we are able to select only one product at a time and after we click on the add button the list is lost and the text field gets reset and we have to retype the word Choi to get the list all over again, which is serious waste of time.

## Suggested implementation
What we suggest is that it would be great if we could select multiple products, from the populated list, to add in one go. (maybe the drop down list could be changed to a multi-select list box)

## Suggested steps
Once the related products are selected they should get displayed the same way it is currently displayed when only product is selected.
Next we then have the option to enter the quantity of each product and modify the price of each product if needed.
Finally we click on the add to add them all to the proposal, order etc.

## Alternative ?
Even if this feature cannot be implemented, it would still be of some help if the search text box and the related drop down list do not get refreshed after adding each product.

https://www.dolibarr.org/forum/11-suggest-new-features/16432-multiple-product-selection

**Comment by jameszhang023** [comment]
Good idea
