### ISSUE TITLE
BUG: Free Product or Service on Supplier Order didn't work

### ISSUE THREAD

**Issue by jeroedel** [Dolibarr/dolibarr#7219]
# Bug
[*Free Product or Service on Supplier Order didn't work*]

## Environment
- **Version**: [*6.0.0 beta*]
- **OS**: [*Linux*]
- **Web server**: [*Appache*]
- **PHP**: [*7.0.21*]
- **Database**: [*mysqlnd 5.0.12*]
- **URL(s)**: https://xxxx.xxx/fourn/commande/card.php

## Expected and actual behavior
In the past it was possible to add free product or services on the supplier order Form. Now on Version 6.0.0 I enter the description and select the type (product/service) enter price etc. and i press "add" I get an error to select an product or service, but this was already done

## Steps to reproduce the behavior
[*Verbose description*]

![unbenannt](https://user-images.githubusercontent.com/17620774/28732453-396fa2a2-73d8-11e7-98be-a1e016b48ca1.JPG)

**Comment by jeroedel** [comment]
Hi,

I've found the Issue. It was missing some variables from GETPOST.

I add to the File /fourn/command/card.php the following 2 lines starting at 296

![unbenannt](https://user-images.githubusercontent.com/17620774/28873203-f31a85d4-778c-11e7-922a-a96b8b7959f8.PNG)

**Comment by dolibarr95** [comment]
Hi
Can you create a PR for that please ?

**Comment by jeroedel** [comment]
PR???

**Comment by dolibarr95** [comment]
a pull request : 
https://github.com/Dolibarr/dolibarr/pulls

**Comment by jeroedel** [comment]
done

**Comment by dolibarr95** [comment]
tks !

**Comment by eldy** [comment]
Fixed in release candidate
