### ISSUE TITLE
how to setup Indian GST?

### ISSUE THREAD

**Issue by suryacaprice** [Dolibarr/dolibarr#7221]
I am trying to edit the default indian tac but we have CGST , IGST and SGST and HSN code for every product.. Each state has a specific state code . How to customize dolibarr and customize invoice with these fields

i can see this was enabled in 6.0.0 
NEW: Tax system more compatible with the new tax roollout in India (IGST / CGST / SGST).

but when i installed it i can only see the old tax options .. can you please hile me

**Comment by eldy** [comment]
6.0 will be available a a release candidate in few days. May be you can can try with it when it will be available.

**Comment by suryacaprice** [comment]
Thank you eldy , I will wait for it . I have designed the invoice and others pdf template manually and using the dolibarr with local tax 1 and 2 to compensate for CSGT,IGST and SGST . Will it be any helpful for your development? or those designs are already over?

**Comment by kanand81** [comment]
Thank You Eldy and Surya.
I am looking open ERP which can support india new TAX system.  it will be very good for India user if you can add the  CSGT, IGST and SGST  in the system.

**Comment by eldy** [comment]
@suryacaprice design for 6.0 are closed. But you can help us to say if change in 6.0 is working correctly for india...

**Comment by suryacaprice** [comment]
@eldy Ya sure . You need to add HSN code for each product , State code for third party , Electronic reference number if the invoice cross over Rs.50,000 , Po Number , Delivery Details , Transporter details , Invoice total amount in words . I see these are missing in the 6.0 I added them by using extra fields .

**Comment by rahulbindroo** [comment]
Hi Eldy,
All invoices will need one more column which can have HSN /SAC  codes and PO's as well.
In case you need any help in understanding this and changes do let me know I will definitely help you here .
I am reachable at rahulbindru@gmail.com 
Regards
Rahul Bindroo

**Comment by rahulbindroo** [comment]
I am even ready to contribute in forming GSTR1 forms etc  to help this open source community

**Comment by suryacaprice** [comment]
when is 6.0 going to be released as stable?

**Comment by raghukr80** [comment]
Hi,
I am also facing the same issue, we have tax rate as IGST, CGST & SGST with tax rate of 5%, 12%, 18% and 28% where IGST we will charge those amount as full and for CGST and SGST we will spilt the tax and charge ex: the tax rate is 18% the we will split that as 9% CGST and 9% SGST.
As described i can add the tax rates for IGST but it is not allowing me to add the CGST and SGST more than one tax rate because the taux is part of unique index  so it is not allowing us to add additional tax rate .


Surya, if you don't mind could you please share the pdf invoices which you designed.

**Comment by anbalaganr** [comment]
@suryacaprice , i am using 6.0 version. Could you tel me how to enable Indian GST?
I have done the following in Organization setup:
1. Country -> India
2. Disabled VAT
3. Enabled "Use Second Tax"
3. Enabled "Use Third Tax"
But i couldn't see IGST option while creating quotation. Could you please help me?

**Comment by suryacaprice** [comment]
you need to enable VAT as well .. I made a manual config but as per dolibarr 6.0 VAT is IGST .. 2nd and 3rd tax are CGST and SGST

**Comment by raghukr80** [comment]
Thank you for the update Surya, i did the change in the template to display GST. If you add HSC code (complimentary attribute) in the template, please share with me and that will really helpful for my coding.

**Comment by suryacaprice** [comment]
can you share me the coding you have done so far . I have finished the setup but made many custom changes in settings from the default dolibarr . You can reach me at surya (at) technoartista (dot) com .

**Comment by suryacaprice** [comment]
if you add in complimentary attribute it wont be available for the free entry products.

**Comment by raghukr80** [comment]
I updated 2 templates one is for intrastate and other is for interstate sales, you can check the code in the below link
https://github.com/raghukr80/doli

**Comment by suryacaprice** [comment]
hi @raghukr80 thank you . I will also upload my codes . Its more customised not sure if anyone will use it

**Comment by raghukr80** [comment]
Even i did some changes in the language files to display GST for India

**Comment by suryacaprice** [comment]
ya same here

**Comment by suryacaprice** [comment]
@raghukr80 does the default dilibarr installer will come with  your updated to the db changes for languages and custom fields? can you upload your db aswell

**Comment by raghukr80** [comment]
yes, if you use this code it will come with the changes except the rupee symbol you can update the the below unicode 0x000020B9 in the lix_c_currencies table with this value to display rupee symbol.

**Comment by suryacaprice** [comment]
ok sure tnx . I will check it out

**Comment by raghukr80** [comment]
Custom fields will not be coming in the installer, you have to manually create those, i am trying to find out the way to display custom field in the invoice and for the same reason i am asking you if you did any change to display custom fields

**Comment by suryacaprice** [comment]
https://wiki.dolibarr.org/index.php/Extrafields i used this .. Its working out fine for me

**Comment by raghukr80** [comment]
Thank you, please share the code which will help me to do it quickly

**Comment by suryacaprice** [comment]
ok sure .. Will do it tonight or tomorrow ..

**Comment by suryacaprice** [comment]
@raghukr80 are you from TN , thirunelveli man? I am from Coimbatore seems our template is same from the code i saw . I havent tested it out as I am viewing in mobile . Contact me at surya (at) technoartista (dot) com we will work on this offline and upload the code .

**Comment by raghukr80** [comment]
yes, Surya, Sure we will do it, i started this for My brother for his business. i did all those changes for version 5 and now doing it for 6 i may be missed something, which i am identifying and fixing it, we will in touch to update the code, my contact is raghukr80(at)yahoo(dot)com

**Comment by parthaero** [comment]
Hi, I am trying to do the same thing, add Indian taxation system. My invoices as of now show only SGST. I checked my ‘Lang’ file, it has and entry ‘VAT=SGST’ by default. I haven been able to figure out how to setup Tax 2 and Tax 3 as CGST AND IGST. Any help is appreciated.

**Comment by rohittheozzy** [comment]
Hello @suryacaprice , I am also building Dolibarr for my company. Can you help me out with the settings for  Indian tax system. Also if I can get some pdf templates for invoice etc. that would be much help.

**Comment by raghukr80** [comment]
Hi Rohit,

The current dolibarr repo which is done for a pharma company. You can download the source and install it first, I have updated the language files, also updated most of the templates including invoice to display GST split like CGST SGST etc.

Please configure the tax as per the default example.

For more help please ask the specific question, I'll try to answer.
Thanks
Raghu

**Comment by rohittheozzy** [comment]
Hello Raghu,

Thank you for the Update. 
Most of the requirements are solved in the latest version, and are highly simplified. Simple changes in the Lang files makes wonders. Only need to learn how to update the PDF template for Invoice. Then will go into accounting. We had been using Dolibarr only for Quotations and inventory till now, We are planning to use Dolibarr for the complete process this year.

Best Regards
Rohit Potdar

**Comment by sadmanhuq** [comment]
Dear @suryacaprice how can i add Invoice total amount in words at Dolibarr. can you help me please

**Comment by asif1001** [comment]
Hi Raghu,

I am new to FA, and I am seeking for GST update
can anyone help me to get indian GST update

**Comment by dipen10** [comment]
@asif1001 . what kind of update are you expecting. Im using the full fledged INDIAN GST system for my client including trial balance,vendor balance,vendor outstanding,vendor ledger,customer ledger and many more

**Comment by asif1001** [comment]
@dipen10  I am new to Dolibarr and while generating TAX invoice system is not calculating GST (SGST+CGST) and not reflecting in the tax invoice
please help me with TAX invoice Templet as per Indian Tax rules

**Comment by smthakor1979** [comment]
ooooo
