### ISSUE TITLE
SQL error using external users

### ISSUE THREAD

**Issue by appoloniaSrc** [Dolibarr/dolibarr#7230]
# Bug
SQL Error on the following  request file ( **html.formother.class.php )**, syntax error on the ORDER BY statut. 

It seems that the reference during an ORDER to a heading included in the same file on a UNION is problematic, so I simply deleted the reference to the status file instead of u.statut

// Get list of users allowed to be viewed
$sql_usr = "SELECT u.rowid, u.lastname, u.firstname, u.statut, u.login";
$sql_usr.= " FROM ".MAIN_DB_PREFIX."user as u";
$sql_usr.= " WHERE u.entity IN (0,".$conf->entity.")";
if (empty($user->rights->user->user->lire)) $sql_usr.=" AND u.rowid = ".$user->id;
if (! empty($user->societe_id)) $sql_usr.=" AND u.fk_soc = ".$user->societe_id;
// Add existing sales representatives of thirdparty of external user
if (empty($user->rights->user->user->lire) && $user->societe_id)
{
$sql_usr.=" UNION ";
$sql_usr.= "SELECT u2.rowid, u2.lastname, u2.firstname, u2.statut, u2.login";
$sql_usr.= " FROM ".MAIN_DB_PREFIX."user as u2, ".MAIN_DB_PREFIX."societe_commerciaux as sc";
$sql_usr.= " WHERE u2.entity IN (0,".$conf->entity.")";
$sql_usr.= " AND u2.rowid = sc.fk_user AND sc.fk_soc=".$user->societe_id;
}
// $sql_usr.= " ORDER BY **u.statut** DESC, lastname ASC";
$sql_usr.= " ORDER BY **statut** DESC, lastname ASC"; // Don't use 'ORDER BY u.statut' here,pb with the UNION.

## Environment
- **Version**: 5.0.4
- **OS**: Windows 10
- **Web server**: XAMPP
- **PHP**: 5.4.31
- **Database**: [MySQL 5.6.16]
- **URL(s)**: html.formother.class.php

**Comment by eldy** [comment]
Fixed for 5.0.5
