### ISSUE TITLE
Feature evolution on propal/list.php

### ISSUE THREAD

**Issue by appoloniaSrc** [Dolibarr/dolibarr#7231]
# Feature Request
Possibilty to CANCEL a selected list of propal to keep them in DB. Actually only DELETE is available.

## Use case
Go to COMMERCIAL >> Liste
Check a selection of propals

## Suggested implementation
Add the flag "Annuler / Cancel" in the ACTION combo box

![dol_propales](https://user-images.githubusercontent.com/29565150/28816097-d9cea798-76a3-11e7-965b-2c6b0004848e.jpg)

**Comment by atm-maxime** [comment]
This feature is present in the 9.0 version. You have a new mass action called "Close".
