### ISSUE TITLE
Unable to enter a product on a supplier order if no supplier price defined

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#7239]
# Bug
Even with the hidden option SUPPLIER_ORDER_WITH_NOPRICEDEFINED is set to 1 we can't add a product line in a supplier order if there no supplier price set for this couple (supplier / product).

## Environment
- **Version**: 5.0.4
- **OS**: Windows 10 pro 64bits
- **Web server**: Apache 2.4.27 on Wamp 3.0.9
- **PHP**: 7.1.8
- **Database**: innodb on MariaDB 10.2.7

## Expected and actual behavior
Need to order some products to supplier with no price on the product card for that supplier (ex : new product or new supplier for that product, or no time to update the data base).
The hidden option SUPPLIER_ORDER_WITH_NOPRICEDEFINED is set to 1.
When we try to add the product to the order Dolibarr answer a error about no references or no price for that product with this supplier !

Greetings,
Sylvain Legrand.

**Comment by aljawaid** [comment]
I have the same problem on 5.0.4
