### ISSUE TITLE
Index column size too large on install

### ISSUE THREAD

**Issue by MartijnBraam** [Dolibarr/dolibarr#7240]
# Bug
When installing dolibarr on a mariadb database I get the following error:
```
Executed query : CREATE TABLE llx_holiday_config ( rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR( 255 ) NOT NULL UNIQUE, value TEXT NULL ) ENGINE=innodb;

DB_ERROR_1709 Index column size too large. The maximum column size is 767 bytes.
```

## Environment
- **Version**: 5.0.4
- **OS**: Debian 9
- **Web server**: Apache 2.4
- **PHP**: 7.0.19-1
- **Database**: Ver 10.1.23-MariaDB-9+deb9u1

## Expected and actual behavior
The installer works

## Steps to reproduce the behavior
Create a debian 9 VM and install a lamp stack with:
```bash
$ apt-get install mysql-server phpmyadmin
```
Install dolibarr with the webinterface and it should crash with the error above.

![screenshot from 2017-08-04 16-21-26](https://user-images.githubusercontent.com/6928199/28972729-03b02138-7931-11e7-8eb9-78fbcada1e40.png)

**Comment by MartijnBraam** [comment]
It seems to work if I let dolibarr create its own database instead of creating one from the mysql shell.

**Comment by eldy** [comment]
When creating the database from the shell, you may result in having a pagecode that need more than 3 bytes per char so the field value(255) need more than 767 bytes for the unique index.
In 7.0, field is 128 char so it will solve the problem.
