### ISSUE TITLE
Liste des modèles de facture vide en cas de tri

### ISSUE THREAD

**Issue by alain-ahs** [Dolibarr/dolibarr#7246]
Bonjour,

Dans la version 5.0.4, le lien "Liste des modèles" du menu de gauche fonctionne normalement. Mais le changement du nombre maxi d'enregistrements ou les tentatives de filtrage aboutissent à une liste vide. Sans mention d'une erreur. 

Amitiés à tous.

**Comment by eblanc66** [comment]
Bonjour,
Je rencontre ce même bug en version 5.0.3. En attendant je dois faire un tri par tiers et défiler page par page pour retrouver mon modèle ce qui est très contraignant lorsque l'on a plus de 10 pages.
Cordialement,

**Comment by atm-maxime** [comment]
Hi guys. This has been fixed in 6.0. Thanks.
