### ISSUE TITLE
Question: Single Project involving multiple Third Parties, how to do this?

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7247]
# Question
Single Project involving multiple Third Parties, how do we approach this situation? Do we have to create individual projects for each third party, something like PRJ201706-1, PRJ201706-2 and PRJ201706-3? Is this the only route?

# Scenario
Let's say we got 3 clients that belong to the same group, let's call it Group X. In which our clients are Group X - Hygiene, Group X - Chemicals and Group X - Pharmaceuticals and we have the opportunity to start a project for said clients with 3 initial identical commercial proposals and at the end of the project we want to have an overview of the total profit of the project involving the groups clients.

**Comment by eldy** [comment]
If you need an overview on project, just create 1 project X. Set no dedicated third party on this project.
Then after creating each proposal for Hygine, set the project to X.
Then after creating each proposal for Pharmaceuticals, set the project to X.
