### ISSUE TITLE
Error Create Facture from shipping

### ISSUE THREAD

**Issue by fmatias1** [Dolibarr/dolibarr#7251]
# Bug
Error Create Facture from shipping

## Environment
Dolibarr ha detectado un error técnico.
Esta información puede ser útil para el diagnóstico:
Fecha: 20170810094035
Dolibarr: 5.0.4
Nivel de funciones: 0
PHP: 5.6.31
Server: Apache
OS: Linux xxxxxxx 2.6.32-042stab123.2 #1 SMP Mon Apr 17 17:27:00 MSK 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

URL solicitada: /compta/facture.php
Referer: http://xxxxxxx/compta/facture.php?action=create&origin=shipping&originid=32&socid=35
Gestor de menú: eldy_menu.php

**Comment by eldy** [comment]
Can you enable module syslog, reproduce error and paste content of file dolibarr.log found into directory documents ?
