### ISSUE TITLE
Feature Request: optional product

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#7254]
# Environment
- **Version**: nearly all versions of Dolibarr

# Report
there's an annoying approche around products with quantity at zero : they are considered as optional products.
First, if you want **10 optional products**, it became impossible.
Secondly, if you want to make a **discount on optional products**, discount are not displayed.

I know there's a big impact around this, but i think it's important to dissociate quantity = 0 and optional product. Side effects start to impact product stability and their understanding.

# Suggestion
add an optional checkbox on each product lines (yes everywhere)

**Comment by eldy** [comment]
You can still add your own extra field "optional product" on the line level.

**Comment by homer8173** [comment]
It was easy to make a workaround for me,  I just suggest that to improve software on a user point of view.
