### ISSUE TITLE
Bug: VAT for EU Customers

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#7256]
# Bug
VAT for EU Customers not respected.

## Environment
- **Version**: 5.0.4
- **OS**: Ubuntu 16.04 server
- **Web server**: Apache 2.4
- **PHP**: PHP 7.0
- **Database**: MySQL 5.7
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Small setup problem or Bug. I have my business in Spain but a few customers in other EU countries. When I setup the invoice with the VAT of the product/service (@ 21%), I was expecting the invoice calculation to set the VAT (i.e 0%) at the end based on the presence of Intra EU VAT number availability. If present, set VAT to 0, if not apply VAT from Spain. Is this the proper way to create an invoice to EU countries or should I set the VAT to 0 for each product/service when the invoice is created ?

## Steps to reproduce the behavior
Setup business in Spain with EU VAT number
Create customer in France with EU VAT number
Create invoice with Spain VAT in the product
Get invoice with VAT

**Comment by eldy** [comment]
Yes, vat should be set automatically to 0.
Are your sure the customer is a company (check third party type and that vat number is filled)

**Comment by dom-breizh** [comment]
I found what went wrong. No bug. 
For reference for others: When creating a proposal with existing predefined products/services (with their normal VAT rate), the VAT rate is reset to 0 when the customer is in the EU with valid Intra EU VAT number. When using custom product/services, created just for that proposal, you have to set the VAT rate at 0 manually, else if you set your 'standard VAT rate' it keeps it when validating the proposal instead of forcing it back to 0. A warning message might be useful, or a very explicit note should be added in the manual.
Sorry for the confusion.

**Comment by BebZ** [comment]
Thanks @dom-madrid dom-Madrid ! 
For reference when you say : 
> with valid Intra EU VAT number. 
i could add "or not"' 
you can try with anything (like "123456" ) 
in the VAT code field, and it removes VAT when adding the products to propal, order or invoice
even if the customer is in France
it should be explaine with a tooltip here : 
![image](https://user-images.githubusercontent.com/3694135/29653841-630fc974-88ab-11e7-959c-adf1b3375c70.png)
