### ISSUE TITLE
Feature Request: Add column project to the list of invoice, order, proposal

### ISSUE THREAD

**Issue by reeperbahnause** [Dolibarr/dolibarr#7257]
# Feature Request
Add column project to the list of commande.  

## Use case
In case of many commandes it is not easy to find the relevant entry. Therefore it would be very helpful to be able to add the project to the list.

## Suggested implementation
I will try to dig into the code to see if I could make any suggestions.

## Suggested steps
- Add Project to the list of columns which could be selected
- If column is selected how column in the list

**Comment by atm-arnaud** [comment]
Hello,

This feature has been added in Dolibarr v7.0.

Regards,

@atm-maxime  Issue to close

**Comment by reeperbahnause** [comment]
Hi,

i just checked it with version 7.0.1 but I still don't see the project in the lists.
For some lists there is an option to select the project column but even after activating it, the project is not shown.

Do I have to set an extra property or something similar?

Cheers

**Comment by atm-maxime** [comment]
I just checked on a 8.0 version, the column "project ref" has been added on merely all lists (proposal, orders and invoice)
