### ISSUE TITLE
Supplier prices import: Use codes instead of keys

### ISSUE THREAD

**Issue by mgribaudo** [Dolibarr/dolibarr#7259]
Hi, 
when importing supplier prices from a csv, actually the internal key (rowid columns in products and suppliers table) are required. 
For users it's impossible to know these codes without accessing the database, it will be very useful to use the code instead.

Marcello

**Comment by MartijnBraam** [comment]
I've just ran into this, it actually looks up the supplier name and product code but not in all cases.

- For product references it only works if your product codes are not fully numeric, solved this for me by appending a letter to all product codes
- For suppliers it breaks if you have both a customer and supplier with the same name which aren't merged into a single third party

I've tried finding somewhere to at least propose changes to the documentation but haven't found it yet.

**Comment by mgribaudo** [comment]
Thanks,
in my case products are pharmaceutical codes, coming from an external standard database and are fully numeric. I can also try to modify somehow the code if necessary.
Do you know what's the procedure to purpose me for modify sources?

**Comment by torvista** [comment]
Imports should accept any  product code. In my opinion this is a bug or an incomplete implementation of the import lookup.

If you wish to manipulate/prepare a csv prior to import, I use Pentaho Data Integration Community. It can do anything.

**Comment by walterdonda** [comment]
the only way for the user to see the row_id is to export the product with the export data module, the first column of the export is the field row_id.
