### ISSUE TITLE
dolibarr 5.0.4 multicurrency

### ISSUE THREAD

**Issue by moataztealab** [Dolibarr/dolibarr#7260]

**Comment by jimhtwong** [comment]
I cannot set multicurrency in product and service. I cannot use it without it.

**Comment by eldy** [comment]
Can you try with version 6.0.1 ?

**Comment by jimhtwong** [comment]
I tried it. There is no way for me to set currency in adding product and service.
If the vendor is from US, we have to turn to HKD. 
If the vendor is from Euro, we have to turn to HKD. etc
For currency rate changes, we have to update product price from time to time.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
