### ISSUE TITLE
Automatic send email events have wrong actiontype code

### ISSUE THREAD

**Issue by tcarterfrance** [Dolibarr/dolibarr#7264]
# Bug
When I send a quote by email the event gets logged with code AC_OTH_AUTO instead of AC_PROP. It's correctly set by the propal card then incorrectly overwritten in the trigger : 

/comm/propal/card.php line 639:
 $actiontypecode='AC_PROP'; -- OK

/core/triggers/interface_50_modAgenda_ActionsAuto.class.php line 140
$object->actiontypecode='AC_OTH_AUTO'; -- KO

As far as I can see the same error occures for commandes, invoices etc.

## Environment
- **Version**: 5.0.1
- **PHP**: Version 7.0.22-0ubuntu0.16.04.1
- **Database**: mysql - mysqlnd 5.0.12-dev - 20150407
- **URL(s)**: [*Affected URL(s)*]

## Steps to reproduce the behavior
Create a quote, send it by mail. Check the new line added to table llx_actioncomm

## Why is it important
I'm using Reportico for reporting and the grouping by action type is wrong.

## Workaround
Add manual action type and ask user to modify the event each time

Thanks, Thomas CARTER

**Comment by eldy** [comment]
Seems to be fixed with 6.0 (soon released)

**Comment by tcarterfrance** [comment]
Cool, thx.

Cordialement
Thomas CARTER
----------------------------
CERGY INTERNET
Courrier : 16, rue Ampère, CS7001, 95307 CERGY PONTOISE CEDEX
GPS : POLE-MULTIMEDIA,16 rue Ampère, 95300 Pontoise
Mobile : 06 03 51 10 15
cergy-internet.fr, polemultimedia.fr
