### ISSUE TITLE
requête scandir non supportée par OVH vs scan_dir supportée

### ISSUE THREAD

**Issue by pmdbr** [Dolibarr/dolibarr#7275]
Suite à une migration de mon Dolibarr (de la version 3.4 à 5.04), je me suis retrouvée privée de la configuration des modèles de documents. Tout le reste marchait bien.
Mais quand je voulais activer par exemple le modèle Proforma du module Commandes clients, j'obtenais une erreur indiquant que je n'avais pas les droits en écriture sur le fichier htdocs/admin/command.php. Or je les avais bien.
Mon Dolibarr est installé sur un serveur mutualisé OVH.

Après différentes recherches, j'ai fini par identifier le problème grâce à ce post sur le forum qui décrit précisément la situation :
https://www.dolibarr.fr/forum/3-installation/59115-configuration-des-modeles-de-documents-bloquee#85151

Pour ma part, je me suis contentée de changer la requête à la main dans la barre d'URL, remplaçant scandir par scan_dir, et le tour était joué. Mais ce n'est clairement pas une solution.

Serait-il possible de remplacer dans le code natif de Dolibarr les scandir par des scan_dir? cela éviterait quelques déboires et sueurs froides aux utilisateurs qui font tourner leur Dolibarr sur un serveur mutualisé d'OVH.

**Comment by hregis** [comment]
@pmdbr 
j'ai soumis la correction https://github.com/Dolibarr/dolibarr/pull/7280

**Comment by pmdbr** [comment]
Bravo pour la réactivité :) Bonne continuation !
