### ISSUE TITLE
no meaningful response from contact@dolibarr.org

### ISSUE THREAD

**Issue by THUFIR** [Dolibarr/dolibarr#7279]
in response to issue:

https://github.com/Dolibarr/dolibarr/issues/7209#issuecomment-323854417

all they did was to write back:
The Dolibarr Fundation goal is to promote Dolibarr with, for exemple website :
(www.dolibarr.org, www.dolibarr.fr, www.doliforge.com, www.dolistore.com,wiki.dolibarr.org) or by promote Dolibarr REP/CRM during congress/manifestation.
To learn more about Dolibarr Fundation : http://wiki.dolibarr.org/index.php/Dolibarr_foundation

The Dolibarr fundation don't do support or specifics developpement for Dolibarr ERP/CRM
For this matter you can contact any of the dolibarr partner :
http://wiki.dolibarr.org/index.php/List_of_Dolibarr_partners_and_providers

There is a label given by the association : "Dolibarr Preferred Partners"
http://wiki.dolibarr.org/index.php/Dolibarr_Preferred_Partner#What_is_a_Dolibarr_Preferred_Partner_.28Provided_services.29

This label is given to companies that are actives on dolibarr developpement and do it in a fair way.

For users questions you can go to the forum 
    www.dolibarr.org/forum
Or
   wiki.dolibarr.org 

The Dolibarr association

to tell me what they don't do or to direct me to the forums.

**Comment by eldy** [comment]
Your email was probably not clear.
Can you resubmit an email with this message.

"Hi, it seems my login AAAAA (replace with your login) on the forum of web site XXXX (replace with correct url) is locked. Can you unlock it please ?"

**Comment by THUFIR** [comment]
Hi, it seems my login THUFIR on the forum of web site
https://www.dolibarr.org/forum is locked. Can you unlock it please ?


reference:

https://github.com/Dolibarr/dolibarr/issues/7279
