### ISSUE TITLE
Feature Request: Add Customer while creating a New commercial proposal

### ISSUE THREAD

**Issue by jlegido** [Dolibarr/dolibarr#7282]
# Feature Request
*Add Customer while creating a New commercial proposal*

## Use case
You want to create a new commercial proposal for a new client. You don't want to waste time now creating the customer, so you should be able to quickly create a customer from within the same "New commercial proposal" view.
Actually is the way Odoo 8 works with "Sales / Opportunities"

## Suggested implementation
Same as  Actually is in Odoo 8 works with "Sales / Opportunities":
Introduce a value "Create customer" as first option in the dropdown of the field "Customer" in "New commercial proposal" view, which is a link.
When selected a new popup opens with this content:
http://example.com/societe/soc.php?leftmenu=customers&action=create&type=c
Once the client is added, the popup closes, and the field "Customer" in  "New commercial proposal" is filled with the newly added customer.

## Suggested steps
No idea, sorry :(

**Comment by dolibarr95** [comment]
Hi
Good idea.
Instead of a pop-up we could display/hide (when the field "new customer is selected") a div with only the mandatory fields to create a customer : 

- Third party type:    Company/Foundation      Private individual
- Third party name
- Prospect / Customer
- Supplier
