### ISSUE TITLE
Bug in payment terms translation

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#7284]
# Bug
Payment terms field in supplier proposal not displaying in any other language than Franch. I have tried to translate the string in Dolibarr but without a luck. I have also tried to find this in transifex but again without a luck. The issue occurs with UltimatePDF template as this field does not display in muscadet template. If it is possible for me to change this value into English then, please point me in the right direction, if not, then, please fix it. Thank you in advance.

## Environment
- **Version**: 5 stable, 6 beta, 7 alpha
- **OS**: Linux 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.31
- **Database**: MySQL or MariaDB 5.5.5-10.2.8-MariaDB

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
<img width="1310" alt="screen shot 2017-08-23 at 15 24 37" src="https://user-images.githubusercontent.com/28427270/29621870-d21c8312-8819-11e7-8e03-6b59a1e00e73.png">
<img width="1408" alt="screen shot 2017-08-23 at 15 32 13" src="https://user-images.githubusercontent.com/28427270/29621883-d970e888-8819-11e7-803a-b1010c2926d9.png">

**Comment by eldy** [comment]
Do you get value also in french on an invoice using "crabe" template ?

**Comment by futurehousestore** [comment]
No. The problem is only with UltimatePDF invoices. I have contacted Philippe about it but he said the problem is with translations and I can change it in the menu Setup -> Translation but it didn’t work for me as this just changing the terms at the bottom of the invoices but doesn’t change the top terms and to be honest I haven’t noticed and French in customer or supplier invoices but only in Supplier proposals. Thank you very much for your email I was trying to sort it be myself but I cannot find it anywhere.
Kind regards,
Marcin

**Comment by futurehousestore** [comment]
Very odd error but I have finally found a solution. I've deleted all payment terms in Dictionaries (they were all in English) and created new and now it works and display payment terms in English :)
