### ISSUE TITLE
Bug: Third Parties and Agenda

### ISSUE THREAD

**Issue by ryecoder** [Dolibarr/dolibarr#7286]
# Bug

## Environment
- **Version**: 5.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/comm/action/index.php?idmenu=1&mainmenu=agenda&leftmenu=

## Report

When activating permission of  "read third parties" at a user when the user goes to Agenda and click a certain agenda to view its details system shows "no permission". How are this connected? The temporary solution is to turn off that 1 permission setting or turn on all permissions under "Third Parties"

**Comment by hregis** [comment]
@ranman09 
Give me the details of the user's "Events/Agenda" and "Third parties" permissions when you have "no permission".

**Comment by ryecoder** [comment]
Here you can try seeing this screen shots

**Comment by hregis** [comment]
@ranman09 
ok, i submit a PR https://github.com/Dolibarr/dolibarr/pull/7287

**Comment by ryecoder** [comment]
Thanks @hregis

**Comment by ryecoder** [comment]
Is it good now? Sorry Im kinda new to Git

**Comment by hregis** [comment]
@ranman09 
yes, try to edit the file :  /core/lib/security.lib.php
line 378
replace : 
`$checkother = array('contact');`
by
`$checkother = array('contact','agenda');`

**Comment by ryecoder** [comment]
Wow! thanks!

**Comment by ryecoder** [comment]
Thank you at @hregis
