### ISSUE TITLE
Missing User Data in thirdparty REST API

### ISSUE THREAD

**Issue by areaeuro** [Dolibarr/dolibarr#7288]
# Bug
thirdparty REST API returns NULL on "user_modification" & "user_creation" fields

## Environment
- **Version**: 5.0.4
- **OS**: Linux - Ubuntu 17.04
- **Web server**: Apache/2.4.25 (Ubuntu)
- **PHP**: cgi-fcgi 5.6.31
- **Database**: MySQL 5.6.36-82.1-log
- **URL(s)**: /api/index.php/thirdparties/ /api/index.php/thirdparties/1

### Expect to receive userId in JSON response such as:
.....
"date_modification": 1503362993,
  **"user_modification": 1,**
  "date_creation": 1503337445,
  **"user_creation": 2,**
.....

### Actual response is:
.....
"date_modification": 1503362993,
  **"user_modification": null,**
  "date_creation": 1503337445,
  **"user_creation": null,**
.....

## Steps to reproduce the behavior
Make the thirdparty REST API call

**Comment by eldy** [comment]
Can you confirm you get http code 200 ?

**Comment by areaeuro** [comment]
@eldy Yes;
API returns a response code of 200 when viewing in explorer, and a "HTTP/1.1 200 OK" header when making call via http client (curl).

It's strange because most of the other information on third party is there (nom, name_alias, address, zip, town, etc) but I get null on the mentioned fields.

I am making the API call with the superuser account, incase there was a user permissions issue that i hadn't noticed.

Any ideas would be appreciated.

**Comment by areaeuro** [comment]
That fixed it. Thanks !!
