### ISSUE TITLE
Bug : class already declared in API

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7289]
# Bug
Try to run api by accessing to dolibarr/api url got an error 500 and give me this error : 
`
[24-Aug-2017 11:59:33 Europe/Paris] PHP Fatal error:  Cannot redeclare class CategoryApi in /home/dolibarr/categories/class/api_category.class.php on line 0
`

## Environment
- **Version**:  5.0.4
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: [*Database type and version*]
- **URL(s)**: api/

## Expected and actual behavior
My dolibarr is version 3 that have been ( gradually ) updated to 5.0.4 and runs perfectly...
I think normaly this file should be deleted when an upadate is done but not.

tks for reading

**Comment by eldy** [comment]
Try to run upgrade 4.0 to 5.0 again.
When you make the upgrade, don't you have some messages that tell you wizard fails to delete some files ?

**Comment by dolibarr95** [comment]
Hi i've done what you ask me to do. And this time the message displays.
So everything is ok for me :

![screencapture-1blow-dolibarr5-install-upgrade2-php-1505113777074](https://user-images.githubusercontent.com/24292300/30269420-072cdb64-96e9-11e7-96bf-c7559babfc5a.png)

Tks
