### ISSUE TITLE
New Picto for Mobile Phone Number

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#7290]
# Feature Request
*Add a new picto for mobile phone number*

## Use case
Now we use the same picto for standard phone number and mobile one.

## Suggested implementation
I suggest to add a different picto for mobile phone number.
Like ![object_phoning_mobile](https://user-images.githubusercontent.com/23272229/29666902-040850ee-88e3-11e7-8b08-80c3dfc68606.png) for instance.

## Suggested steps
2 files should be change : 
../core/class/commonobject.class.php => lines 498 and 510
../core/lib/functions.lib.php => line 1876

A example of these two files already change is uploading.
[new_mobile_phone_picto.zip](https://github.com/Dolibarr/dolibarr/files/1248824/new_mobile_phone_picto.zip)

**Comment by dolibarr95** [comment]
Hi  see #7607
