### ISSUE TITLE
tag error

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#7291]
# Bug
tag error

## Environment
- **Version**: 5.0.4

## Expected and actual behavior
on file "../core/class/commondocgenerator.class.php" line 399 the expression 'already_payed_all' need '_' before to become '_already_payed_all'

See the file already corrected below

## Attached files
[commondocgenerator.class.php.zip](https://github.com/Dolibarr/dolibarr/files/1248868/commondocgenerator.class.php.zip)

**Comment by atm-maxime** [comment]
I checked and this has been fixed. Thanks
