### ISSUE TITLE
Bug: Cant view PDF files

### ISSUE THREAD

**Issue by ryecoder** [Dolibarr/dolibarr#7292]
Hi in Agenda I linked files via a certain user after upload I tried to view the file but cant access it show error. please see attached.

![linked files](https://user-images.githubusercontent.com/28801036/29701512-c5d7e2a0-899e-11e7-894a-b777e7eba7dd.PNG)
![linked files 1](https://user-images.githubusercontent.com/28801036/29701511-c5bd96ca-899e-11e7-862b-9041b42c1d37.PNG)

**Comment by ranman09** [comment]
I tried a while ago again it worked by downloading the file.. Now it doesnt work again??

**Comment by ryecoder** [comment]
## Environment
- **Version**: 5.0.4
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/comm/action/card.php?id=9

**Comment by eldy** [comment]
Do you have pb with 5.0.5 ?

**Comment by AurelienC** [comment]
Hello,

Same error with all permissions (on all modules). User must be administrator to be able to download an attached file on event.

Environment
Version: 6.0.4
OS: Linux
Web server: Apache
PHP: 7.0.27
Database: MySQL or MariaDB 5.5.55-0+deb7u1-log
