### ISSUE TITLE
BUG: Password doesn't show in the E-mail received in case of member validation

### ISSUE THREAD

**Issue by julien-garrigue** [Dolibarr/dolibarr#7296]
# Bug
Hello,
Password doesn't show in the e-mail received by the member when I click on "create user"

## Environment
- **Version**: 6.0.4
- **OS**: Linux edu.cloudhostdns.net 2.6.32-042stab123.3 #1 SMP Fri May 5 12:29:05 MSK 2017 x86_64
- **Web server**: Apache 2.4.27
- **PHP**: 5.5.38
- **Database**: MySQL 5.6.35
- **URL(s)**: https://www.publiconf.net/adherents/card.php?leftmenu=members&action=create

## Expected and actual behavior
Expected : In the email received by the member after validation of its membership, there are all information including the ID and password
Actual behavior : the password field is empty

I use the default %INFOS% tag in the EMail for member validation and all the field are shown but the password one is empty

## Steps to reproduce the behavior
Create a new member (manually or from the public page auto-subscription form), validate it, read the email received : the password is missing. Create the user: the password is still missing

The setting for The EMail for member validation is available at Setup > Module > Members > Miscellanous > other
I just use the default setting. Password is encrypted as by default (even not encrypted, the Password doesn't show)

**Comment by julien-garrigue** [comment]
Hello,

I also found that if I create a Dolibarr user then I click on "regenerate and send password" in the user card, in the email received, the password is visible

Regards,

Julien

**Comment by julien-garrigue** [comment]
Hello,
BUG still there with the version 6.0.4 @asirinelli @genezys @azawawi @rodo @remyyounes 
Thank you

**Comment by hregis** [comment]
@julien-garrigue 
this is not a bug, passwords are encrypted by default since version 6 for users and for the member module. as a result, it can no longer be visible when validating a member.

**Comment by julien-garrigue** [comment]
@hregis 
As the password is auto generated, how the user knows it ? it is not shown in the automatic email

**Comment by hregis** [comment]
@julien-garrigue 
you speak well of the module member?
A new password should be regenerated automatically when validating the member.

**Comment by julien-garrigue** [comment]
Yes I do but it's not the case...
The only case where the passwords shows it's when I click on regenerate new password and send by email

**Comment by hregis** [comment]
@julien-garrigue 
yes it is not implemented

**Comment by julien-garrigue** [comment]
ok. Thanks for your answer
