### ISSUE TITLE
Bug: Unicode Vietnamese characters does not show correctly in PDF

### ISSUE THREAD

**Issue by tiennguyenpy** [Dolibarr/dolibarr#7324]
# Bug
Generated PDF file show '?' for Vietnamese characters.
For example:

-  The text:  '9545.023 - Tủ điện Rittal 12'
-  Show as '9545.023 - T? ?i?n Rittal 12'

## Environment
- **Version**: Dolibarr 5.0.4
- **OS**: Linux 2.6.32-673.26.1.lve1.4.30.el6.x86_64
- **Web server**: Apache
- **PHP**: 5.6.31
- **Database**: MySQL 5.6.37
- **URL(s)**: /commande/card.php?id=xx

## Expected and actual behavior
Generated PDF file should show actual character instead of '?'.

## Steps to reproduce the behavior
Create new 'Customer orders', create on entry enter '9545.023 - Tủ điện Rittal 12' as description text.
In the section 'Linked files', press 'Generate'.
Check generated file.

## Attached files
Generated sample file
[CO1708-0001 (1).pdf](https://github.com/Dolibarr/dolibarr/files/1272693/CO1708-0001.1.pdf)

## Cause
PDF fonts in /htdocs/includes/tecnickcom/tcpdf/fonts does not have all unicode vietnamese characters.

## Suggestion
Update all fonts in /htdocs/includes/tecnickcom/tcpdf/fonts to have all unicode character.

## Workaround
the font 'freeserif' support Vietnamese characters.
We can change pdf font from 'helvetica' to 'freeserif'.
How:
Change FONTFORPDF value, it located in 'langs/en_US/main.lang'
#FONTFORPDF=helvetica
FONTFORPDF=freeserif

**Comment by eldy** [comment]
What was you language set ?
Did you set it to vi_VN
The font that should be used is DejaVuSans if language used to generate PDF is vi_VN.

**Comment by tiennguyenpy** [comment]
Hi eldy,
The language set to 'en_US' (as shown in attached image), FONTFORPDF=helvetica.
With pdf font DejaVuSans, the content displayed in '?' with some char.

![image](https://user-images.githubusercontent.com/5093202/30550607-189391d4-9cc2-11e7-801a-841949601988.png)
Regards,

**Comment by eldy** [comment]
What happen if you generate the doc into language vn_VN ?

**Comment by tiennguyenpy** [comment]
The same result, vn_VN uses font DejaVuSans, the content displayed in '?' with some char.
I had to set font to 'freeserif' in both 'vn_VN' and 'en_US'.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
