### ISSUE TITLE
Feature Request: Filtering contracts by service status in main contract list

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7332]
# Feature Request
Filtering contracts by service status in main contract list. 

## Environment
- **Version**: develop
- **URL(s)**: /contrat/list.php

![screenshot-2017-09-05-17-10-09](https://user-images.githubusercontent.com/23050598/30072551-986d09a4-9262-11e7-9614-4acc503d8813.png)

**Comment by ruistrecht-alt** [comment]
It is worth noting that I added extra fields to the module and chose to display them.
I now understand how it works, the number is to represent the number of services with that status.
But this does not allow contract filtering by service status, this could be improved.

**Comment by atm-maxime** [comment]
In the left menu, you already have links to show list of contract's services by status (4 links). Is it what you seek ?

**Comment by ruistrecht-alt** [comment]
Yes this works. Sorry for the inconvenience.
