### ISSUE TITLE
BUG: Bulk mail sending of Ivoices

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#7338]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
[*When sending bulk emails with invoices customer invoice address is not used but regular email address and "send copy to" function does not work*]

## Environment
- **5 & 6**: [*Affected Dolibarr version(s)*]
- **?? runs on a web server **: [*Server OS type and version*]
- ****: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Maria DB**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*When sending bulk emails with invoices customer invoice address is not used but regular email address and "send copy to" function does not work*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![image](https://user-images.githubusercontent.com/24621070/30115809-12fcd578-931c-11e7-8bae-048760b21448.png)

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by eldy** [comment]
This looks correct to me.
You selected invoice with different recipients. In such a case the recipient will be different for each email sent.

**Comment by GheeEasy** [comment]
Sorry bad formulation. If I add a specific client contact (e.g. for invoices) to an order and invoice the bulk action email function does not pick this email address but the general client contact (asigened in the client card). Furthermore the cc function does not work.

**Comment by eldy** [comment]
Yes, currently this is a limitation of the bulk send email feature. We are using the email of the thirdparty because in bulk actions, there is no interaction to choose which email to use.

**Comment by GheeEasy** [comment]
Ok then I will continue using the main email address as invoice address!
