### ISSUE TITLE
Intervention PDF Fails

### ISSUE THREAD

**Issue by sylvain-fano** [Dolibarr/dolibarr#7339]
# Bug
[*Generating Interventions fails*]

## Environment
- **Version**: [*6.0.1*]
- **OS**: [*Ubuntu server 16.04*]
- **Web server**: [*Apache2*]
- **PHP**: [*PHP5*]
- **Database**: [*MySQL*]
- **URL(s)**: [*fichinter/card.php?id=xxx*]

## Expected and actual behavior
[*When trying to generate an Intervention PDF document (using soleil template), it fails and get a 500 error page*]

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last files in branch ?
If not, can you close ticket ?

**Comment by sylvain-fano** [comment]
bug resolved !
