### ISSUE TITLE
BUG: CONSTANTS not know as super global

### ISSUE THREAD

**Issue by delcroip** [Dolibarr/dolibarr#7343]
# Bug
for some user, module using the constant as super variable don't work because the constants are not recognized.

$conf->global->CONSTANT_NAME seems to be required instead of CONSTANT_NAME

## Environment

* Version actuelle de Dolibarr : 6.0.0
* OS : Linux serveur 4.2.0.16-generic #19-Ubuntu SMTP
* Web serveur : Apache/2.4.12
* PHP : 5.6.11-1ubuntu3.4
* Database : MySQL or MariaDB 5.6.31-0ubuntu0.15.10.1
* Type du pilote : mysqli (5.6.30)

## Expected and actual behaviour
Expected : CONSTANT_NAME should be replaced by its value defined in llx_const
Actual  : CONSTANT_NAME not recognised

## Steps to reproduce the behavior
Unable to reproduce

**Comment by hregis** [comment]
@delcroip 
i don't understand !
where do you have this problem?

**Comment by delcroip** [comment]
In my module I used the constant I defined in the modMymodul... like CONSTANT_1 but a user faced an issue because the constant was not reconised for its value (constant was correctly saved, log confirmed it) 

see NMX meesage:
https://www.dolibarr.fr/forum/11-suggestionsnouvelles-fonctionnalites/49379-timesheet-vue-pour-les-projets?start=270

Br

**Comment by hregis** [comment]
@delcroip 
ok j'ai regardé vaguement le code de ton module et ça vient de lui pas de dolibarr !
tu dois avoir une incompatibilité avec la version 6...

**Comment by hregis** [comment]
@delcroip je pencherais pour un problème ajax !

**Comment by delcroip** [comment]
Bonjour, Merci d'avoir regardé mais mon module fonctionne sur la version 6 et les pages concernées n'ont pas toutes de l'ajax, (mon module est téléchargé une dizaine de fois par semaine et seulement quelques uns ont le soucis). 

Pour les rares cas problématiques c'est très dur à débuger:
le variables sont bien dans la db, elle sont mis à jours par le module mais leur lecture ne fonctionne pas si on utilise seulement les super global; exemple:
`if(CONSTANTE==3)`
le code semble comparer le string CONSTANTE à trois au lieu de la valeur de celle-ci .
J'ai fais passé tout mes appels de constantes via $conf->global->CONSTANT_NAME afin que mon module ne soit plus impacté mais j'ai créer ce defect afin que le problème soit résolu ou que les constantes ne soit plus des super global car si d'autre module les utilisent ils vont aussi galérer.

bien à toi

**Comment by hregis** [comment]
@delcroip 
jusqu'à la version 5 de dolibarr les "constantes" de llx_const étaient convertie en
"$conf->global->MY_CONST" et en constante PHP : MY_CONST
ceci a été supprimé en version 6 pour éviter les conflits.

effectivement tu dois soit redéfinir tes constantes php si tu veux les garder : 

`define("MY_CONST", $conf->global->MY_CONST);`

soit remplacer MY_CONST par $conf->global->MY_CONST de partout...

**Comment by delcroip** [comment]
Ayant developpé sur la clone de la version 6 en dev j'etait persuadé de la compatibilité.... Merci.

Est il possible de trouver les changements d'approche fait avec les version ?

**Comment by hregis** [comment]
@delcroip 
normalement dans le fichier "changelog", mais apparemment ce changement n'a pas été signalé !
