### ISSUE TITLE
Supplier order creation from RFQ impossible if there is no purchace price in the product.

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#7347]
# Bug
When creating an supplier order from the RFQ and you do not have the supplier price set up in the product you end up not be able to create the supplier order.

## Environment
- **Version**: 6.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.30
- **Database**: MariaDB 10.x
- **URL(s)**: https://demo.dolibarr.org/supplier_proposal/card.php?id=168 

## Expected and actual behavior
The expected behavior would be that an supplier order would be created normally and the purchase price of the product would be added to the supplier price tag in the product.

## Steps to reproduce the behavior
1. Create a new product without the supplier price for purchase.
2. Create a request for quote for a supplier with that newly created product.
3. Insert the price of the product into the RFQ and confirm the purchase by make it
assigned and accepted.
4. Click on create order, it will open you the new window for creating a DRAFT,
5. After all data is in the DRAFT, you can click the Create draft button to create a
draft and it will clear all data and reload the same page. Expected would be to get
the new screen with the draft purchase order created and ready to finalize.

#Files
See the demo server: https://demo.dolibarr.org/supplier_proposal/card.php?id=168 

I think that the correct thing would be to automatically add the prices in the RFQ to the 
product supplier price with the supplier information too, as logically we have a quote from a supplier
so we have a supplier name, and all the necessary data like price, product name , taxes , etc 
to be able to automatically fill in the supplier price in the product tab. 

If you have the purchase price in the product tab this bug does not appear.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
