### ISSUE TITLE
Bug: Empty invoice and proposal pages after generating "doc template" pdf (or if pdf already exists)

### ISSUE THREAD

**Issue by paolocesari** [Dolibarr/dolibarr#7352]
# Bug
After upgrading Dolibarr from 5.0.6 to 6.0.0, the pages invoice and poposal become empty trying to generate pdf (or if exists previuous pdf). The problem can temporaly solved deleting pdf files in "main data root" /documents/facture and /documents/propale but, in this case, there's no way to get pdf.

## Environment
- **Version**: Dolibarr 6.0.0 (after upgrading from 5.0.6)
- **OS**: Linux
- **Web server**: Apache 2.0
- **PHP**: 5.6.30
- **Database**: MySQL 5.0.11

## Steps to reproduce the behavior
Upgrade a previous working version of Dolibarr (in this case from 5.0.6) to 6.0.0

Select "Commercial" from menu bar and then a proposal (or create it).
In linked file section, select "generate" to get pdf proposal file.

<img width="1050" alt="proposal_page" src="https://user-images.githubusercontent.com/31792800/30239018-87a85d14-9553-11e7-9f87-2a65cff31af4.png">

After that the page becomes empty

<img width="1050" alt="proposal_empty_page" src="https://user-images.githubusercontent.com/31792800/30239019-9e162c7a-9553-11e7-811a-2e2783401152.png">

**Comment by hregis** [comment]
@paolocesari 
I do not have this problem, it is probably a conflict with an external module that is not compatible with Dolibarr 6. Try to disable your external modules little by little in order to determine which problem is.

**Comment by paolocesari** [comment]
I also thought so, but when I tried to disable external modules (little by little) the problem remained.
I accept other tips,
Thanks!

**Comment by hregis** [comment]
@paolocesari 
try to activate "Logs" module  and send me the last logs of dolibarr.log located in "documents" directory when you have this problem

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
