### ISSUE TITLE
[Bug] Online files checker failed

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#7354]
# Bug
On run files checker online (with https://www.dolibarr.org/files/stable/signatures/filelist-6.0.0.xml), the /product/inventory/class/inventory.class.php is marked as modified.

The correct sum is 895170ad1f3f5db0a162729cd8d38843 (and not 9b0e82da7dd3f63c5cd565ea6296f7a1 as in https://www.dolibarr.org/files/stable/signatures/filelist-6.0.0.xml).

## Environment
- **Version**: 6.0
- **OS**: Debian 9
- **Web server**: Apache2
- **PHP**: PHP7
- **Database**: MariaDB10
- **URL(s)**: /admin/system/filecheck.php

**Comment by dolibarr95** [comment]
Hi
i've got error too with dolibarr 6.0 (distant or local check)


|Filename | Somme de contrôle attendue | Somme de contrôle actuelle | Taille
-- | -- | -- | --
/product/inventory/class/inventory.class.php | 9b0e82da7dd3f63c5cd565ea6296f7a1 | 895170ad1f3f5db0a162729cd8d38843 | 10275 Octets


I have overwritten the file with the original file contained in dolibarr-6.0.0.zip but still got the error.

**Comment by eldy** [comment]
Hum, i hope to have this fixed in 6.0.1
But i don't understand why file is not inline with checksum.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by dolibarr95** [comment]
Hi
I have to update from 600 to 601, i will upgrade and check.

**Comment by tuxgasy** [comment]
Hi

I still have the bug in 6.0.1.

**Comment by eldy** [comment]
@tuxgasy Can you provide screenshot of error

**Comment by tuxgasy** [comment]
Below a screenshot for a fresh installation.
![screenshot-2017-10-6 dolibarr](https://user-images.githubusercontent.com/3997123/31289473-2456ac44-aac9-11e7-80c9-c1bf8cbf6825.png)

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
