### ISSUE TITLE
BUG: Permission error for salaries after update to 6.0.0 

### ISSUE THREAD

**Issue by reeperbahnause** [Dolibarr/dolibarr#7355]
# Bug
After updating to 6.0.0 the menu entry for salaries was disabled. So I checked the permissions added the new permissions but the menu entry for creating new salarie payments was still disabled.

## Environment
- **Version**: 6.0.0
- **OS**: Windows 10 64bit
- **Web server**: Apache/2.4.17 
- **PHP**: 7.0.14
- **Database**: mysql 5.7.11
- **URL(s)**: http://localhost/dolibarr-6.0.0/htdocs/compta/salaries/card.php?leftmenu=tax_salary&action=create

## Expected and actual behavior
menu entry shoul be active and usable

## Steps to reproduce the behavior
Update dolibarr from 5.0.x to 6.0.0 add the permissions 511 and 512

### Initial menu after update
![image](https://user-images.githubusercontent.com/14199872/30240460-050e31c6-9571-11e7-8d56-a085b5b460ae.png)

### permission management
![image](https://user-images.githubusercontent.com/14199872/30240481-45519a5c-9571-11e7-8dea-c2fae597ead4.png)

### added permissions
![image](https://user-images.githubusercontent.com/14199872/30240493-8b56c630-9571-11e7-9367-865979a99b5a.png)

### menu after permission change
![image](https://user-images.githubusercontent.com/14199872/30240500-acf69c8e-9571-11e7-8260-62a388e42ec3.png)

**Comment by hregis** [comment]
@reeperbahnause 
try to disable/enable the module

**Comment by reeperbahnause** [comment]
Works!
Case closed, but shouldn't this be done during the update process?

Thank you 
Phillip

**Comment by hregis** [comment]
@reeperbahnause 
thank you, i send a fix https://github.com/Dolibarr/dolibarr/pull/7356
