### ISSUE TITLE
BUG: Intervention amount calculation in project overview is wrong

### ISSUE THREAD

**Issue by reeperbahnause** [Dolibarr/dolibarr#7359]
# Bug
After updating to 6.0.0 I had a look at the project overview and saw that the calculation of the intervention amounts was wrong (see image).

## Environment
- **Version**: 6.0.0
- **OS**: Windows 10 64bit
- **Web server**: Apache/2.4.17 
- **PHP**: 7.0.14
- **Database**: mysql 5.7.11
- **URL(s)**: http://localhost/dolibarr-6.0.0/htdocs/projet/element.php?id=1

## Expected and actual behavior
Calculation should be correct ;-)

## Steps to reproduce the behavior
Update dolibarr from 5.0.x to 6.0.0 and have a look at the project overview. 

### example
![image](https://user-images.githubusercontent.com/14199872/30242338-b0746e9a-9594-11e7-8850-f63cf10d922a.png)

### expected
![image](https://user-images.githubusercontent.com/14199872/30242348-0ae3d974-9595-11e7-8240-79560a9711ef.png)

**Comment by eldy** [comment]
Thanks. I pushed what i think to be a better fix.
