### ISSUE TITLE
Error creating invoice from Shipment or Customer Order

### ISSUE THREAD

**Issue by sanjiiiv** [Dolibarr/dolibarr#7364]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

Getting error CODE_NOT_VALID_FOR_THIS_ELEMENT while creating Invoice from Shipment or Customer Order.
Error Log in compta/facture shows PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/shalexov/public_html/vision/htdocs/core/lib/functions.lib.php:3253) in /home/shalexov/public_html/vision/htdocs/main.inc.php on line 1022.

Kindly check the bug
![codenotvalid](https://user-images.githubusercontent.com/31779307/30249095-d182ceb6-9651-11e7-9b03-66c1e0ba445f.png)

**Comment by hregis** [comment]
@sanjiiiv 
check the invoice module configuration !

**Comment by sanjiiiv** [comment]
@hregis 
But what shall I check in invoice module configuration?
Kindly guide as I am new to coding.

**Comment by hregis** [comment]
@sanjiiiv 
sorry, this is an error with the "type of contact"
Did you personalize contact types? (dictionaries)
or do you have an external module that would have added contact types ?

**Comment by sanjiiiv** [comment]
@hregis 
Yes I have personalized dictionaries for CONTACT TYPES, as I am using numbering module with TT.
Didn't face any such problem with Customer Order, Proposal & Shipment and even when generating Invoice manually without using generated Customer Order / Shipment. Moreover, there is no problem on a parallel instance of Dolibarr installation which was an upgrade from 5.04 to 6.0 but having problem of Local Tax not being added in the total.
And why the error log shows PHP Warning: Cannot modify header information - headers already sent by (output started at /home/shalexov/public_html/vision/htdocs/core/lib/functions.lib.php:3253) in /home/shalexov/public_html/vision/htdocs/main.inc.php on line 1022.

**Comment by sanjiiiv** [comment]
@hregis @eldy 
Dear Sirs, I have found the problem,bug is with Turning on feature in stocks module **"Stock level must be enough to add product/service to invoice (check is done on current real stock when adding a line into invoice whatever is rule for automatic stock change)"** the same has to be corrected if the Invoice is created from shipment or order the same check shall not be required, but if the invoice is created manually then only this shall be applicable.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
