### ISSUE TITLE
Bug: errortotallspaid when trying to pay invoice with extra paiement from previous invoice

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#7371]
# Bug
When allocating the excess payment from one invoice to another, the new invoice cannot be marked as Paid. -> Error : errortotallspaid

## Environment
- **Version**: 6.0.0
- **OS**: Ubuntu Server LTS 16.0.4
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: PHP 7.0.22-0ubuntu0.16.04.1
- **Database**: Mysql 5.7.19
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Expected: When allocating the excess payment from one invoice to another, the new invoice should correctly close.
Actual: When allocating the excess payment from one invoice to another, the new invoice get the money allocation, the it is not possible to mark it paid.

## Steps to reproduce the behavior
Create two invoices
Pay the first one with excess amount.
Mark it paid
Pay the the second invoice with allocating the excess amount from the first one.
Mark it Paid -> failure and error message : errortotallsnull

## [Attached files]
![image](https://user-images.githubusercontent.com/5640062/30273482-7259fa38-96f9-11e7-8972-9dba3fd9988e.png)

**Comment by eldy** [comment]
What if you record the payment in 2 steps ?

**Comment by BebZ** [comment]
I had the issue too on previous versions. 
Recording payment in 2 steps, means 2 movements in the bank account, and the accountant doesn't like when there are "ghosts" payments not linkable with something real on the bank account.
What we did to correct it is to wait another payment from the customer and record : 
-69.95
+69.95
+36 (for example)

But it's ot really practical ;)

**Comment by dom-breizh** [comment]
It actually comes from a problem with a supplier... I was billed for all the initial invoice but invoiced for it in a split bill, with two different invoices due to delays in delivery. Not the right way to do it, but the way it was done anyway. I only have one bank transaction, and two invoices for it. As BebZ mentionned, you can find way around it, but the accountant was not happy for the workaround.
Food for though: What is strange is that in a different transaction, with several invoices from the same supplier prepared but not paid individually, when going to prepare record for payment, the program offers to pay all pending invoices in a single operation and mark them paid all at once without error.
