### ISSUE TITLE
Bug: Supplier price is incorrect when you create a new supplier order

### ISSUE THREAD

**Issue by mondecans** [Dolibarr/dolibarr#7375]
# Bug
if you have registered suppliers prices, when you create or modify a supplier order, the price of some products are wrong.
I think the problem is that it is being used the column **rowid** instead **fk_product** in the table **prx_product_fournisseur_price**.
I have tried with a few products and it seems the values are exchanged (compare prices between the two products in the attached files)

## Environment
Version: 5.0.5, 5.0.6 and 6.0.0
OS: Linux
Web server: Apache
PHP: 5.4.45
Database: MySQL or MariaDB 5.5.54

## Steps to reproduce the behavior
This only happens when you create a supplier order.
If you create a supplier proposal or a supplier invoice the prices are correct.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

SUPPLIER PRICES:
![image](https://user-images.githubusercontent.com/2051349/30285936-28ce582e-9720-11e7-98d6-3f9afc15eda4.png)
![image](https://user-images.githubusercontent.com/2051349/30286578-5b3fa856-9722-11e7-9161-504727cd336d.png)

SUPPLIER ORDER:
![captura](https://user-images.githubusercontent.com/2051349/30285126-63cdf090-971d-11e7-9533-2b4a30220098.PNG)

TABLE:
![captura2](https://user-images.githubusercontent.com/2051349/30285170-87e4882c-971d-11e7-9f72-f90e95acbfd8.PNG)

**Comment by dolibarr95** [comment]
Hi
Got the same error with Dolibarr 5.0.5
tks

**Comment by dolibarr95** [comment]
Hi i think we can close this issue : 
https://github.com/Dolibarr/dolibarr/pull/7446
