### ISSUE TITLE
[Feature] Multi-currency: use main currency as default for orders, etc.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#7376]
Dolibarr V6.0.0:

I have activated multicurrency to see how it copes with some of the rare invoices that are in foreign currency.

Upon the creation of an order, the default currency was set to the foreign currency, not to the local currency.

I suggest that the default would be set to the main currency.

In my setup I have added "USD - dollars ($)" as a second currency.

**Comment by mdeweerd** [comment]
When creating a supplier invoice, the default currency shown is EUR.

So the default currency may be correct for some document types and not for others.

**Comment by mdeweerd** [comment]
This may also be related to the upgrade - I noticed that the old entries (suppliers, etc) do not have a currency but that one is suggested when updating the third party.
So this could be related to the lack of a currency for a third party.

**Comment by gregober** [comment]
For suppliers order the currency shall be set to the currency specified by default **in the supplier's account**. 

For the time being all products seems to be **added in EUR** (default currency in my case). 
Even for suppliers defined with USD as currency. 

We need the ability to add a product in USD or whatever currency the supplier has defined. 
If one has to define the price of a product in EUR the whole currency management is useless.

**Comment by mdeweerd** [comment]
Complement, confirmation of "misbehavior" in 6.0.5.

For (several) pre-existing suppliers, when creating a new invoice, the currency slected is "Dollar US ($)" in my setup.

Concretely, I have a supplier for which the Currency is empty:
![image](https://user-images.githubusercontent.com/1504752/37864677-78dfc128-2f72-11e8-88c3-a86dbf80067e.png)

My default currensy is Euros (€).
]I create a new order for the supplier and the default currency for the order is $:
![image](https://user-images.githubusercontent.com/1504752/37864689-a827ca20-2f72-11e8-8eb4-525de371fd34.png)

When I "Modify" the suppliers record, the default selected currency is "Euro (€)" (I remind the reader that the currency shown before modification is empty):
![image](https://user-images.githubusercontent.com/1504752/37864704-def35d9e-2f72-11e8-9859-6335df11f2b2.png)

So I juste Validate/Save [French: "Enregistrer"] the record without doing any actual modification to the proposed fields.

The suppliers record now shows:
![image](https://user-images.githubusercontent.com/1504752/37864717-0d6904bc-2f73-11e8-9047-903e387649f1.png)

An naturally a new order reflects the expected currency:
![image](https://user-images.githubusercontent.com/1504752/37864730-38ee99bc-2f73-11e8-91a5-657f23cf4795.png)


I have performed the following SQL QUERY on my database to solve the issue:
`UPDATE `llx_societe` SET `fk_multicurrency`=1,`multicurrency_code`="EUR" WHERE `fk_multicurrency` IS NULL AND `multicurrency_code` IS NULL`

This suggestion has been open for 6 months without effect, so I am closing it as I have the solution.
