### ISSUE TITLE
Bug product price on supplier order

### ISSUE THREAD

**Issue by PlatiScript** [Dolibarr/dolibarr#7378]
# Bug
When you add a product in a supplier order, the price HT of this product is false.
I see that we are many people in this case like @mondecans 
## Environment
- **Version**: 6.0
- **OS**: Windows Server
- **Web server**: Apache
- **Database**: SQL

## Expected and actual behavior
This bug is only happening on a Dolibarr that was migrate from 3.92->4.0->5.0->6.0 because on a Dolibarr that was migrate from 4.0->5.0->6.0 is ok.

**Comment by dolibarr95** [comment]
Hi
Got the same error with dolibarr 5.0.5

Discuss here ( https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/59700-bug-prix-d-achat-commande-fournisseur)
![rect4178](https://user-images.githubusercontent.com/24292300/30314138-1294372e-97a0-11e7-90d6-37ced0ab0aef.png)

I try to upgrade to version 6.

Tks

**Comment by dolibarr95** [comment]
Same error with Dolibarr 6.0.0

**Comment by dolibarr95** [comment]
I don't know if it a good way but display right prices : 
in `htdocs/fourn/commande/card.php`
line 412
replace 
```php
$productsupplier->id
``` 
with 
```php 
GETPOST('idprodfournprice') 
```

**Comment by dolibarr95** [comment]
Hi
@eldy can you please give your advice about this fix :
Do you think it's a good pratice to replace
```php
$result=$object->addline(
	    			$desc,
	    			$productsupplier->fourn_pu,
	    			$qty,
	    			$tva_tx,
	    			$localtax1_tx,
	    			$localtax2_tx,
	    			$idprod,
	    			$productsupplier->rowid,//id du produit
	    			$productsupplier->fourn_ref,
	    			$remise_percent,
	    			'HT',
	    			$pu_ttc,
	    			$type,
	    			$tva_npr,
	    			'',
	    			$date_start,
	    			$date_end,
	    			$array_options,
				$productsupplier->fk_unit
	    		);
```
by

```php
$result=$object->addline(
	    			$desc,
	    			$productsupplier->fourn_pu,
	    			$qty,
	    			$tva_tx,
	    			$localtax1_tx,
	    			$localtax2_tx,
	    			$idprod,
	    			GETPOST('idprodfournprice'),//id du produit
	    			$productsupplier->fourn_ref,
	    			$remise_percent,
	    			'HT',
	    			$pu_ttc,
	    			$type,
	    			$tva_npr,
	    			'',
	    			$date_start,
	    			$date_end,
	    			$array_options,
				$productsupplier->fk_unit
	    		);
```
If yes i will make a PR.

Tks

**Comment by dolibarr95** [comment]
Hi i think we can close this issue : 
https://github.com/Dolibarr/dolibarr/pull/7446
