### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Clicqueur** [Dolibarr/dolibarr#7389]
# Bug

## Environment
- **Version**: 6.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.5.51-MariaDB
- **URL**: /index.php?mainmenu=home&leftmenu=home

## Report
I have a problem with commercial proposition its impossible to see my proposal
Do you have a solution to fix this problem
Kinds regards

**Comment by atm-maxime** [comment]
With this little information, you won't have any answer. If you still have this issue please add a screenshot and more information!

**Comment by atm-maxime** [comment]
Same than #7394
