### ISSUE TITLE
PRODUCT_USE_UNITS does not work

### ISSUE THREAD

**Issue by Mickaelb06** [Dolibarr/dolibarr#7393]
I activate PRODUCT_USE_UNITS: 1 and when I go to propal I have that unit unit and nothing else I also activate MAIN_VOLUME_DEFAULT_UNIT and MAIN_WEIGHT_DEFAULT_UNIT but the same does not work

I use dolibarr 6.0.0

**Comment by dark666link** [comment]
After activating the PRODUCT_USE_UNITS=1 option I have the same problem, searching for the problem, the error is in htdocs/core/class/html.form.class.php line 3277 "selectUnits", the SQL statement is missing the 'code' column. Hope it helps you.

**Comment by nicolas-it** [comment]
Seems to be fixed in #7434

**Comment by atm-maxime** [comment]
Can you confirm it's fixed ?

**Comment by Mickaelb06** [comment]
Yes its fixed
