### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Clicqueur** [Dolibarr/dolibarr#7394]
# Bug

## Environment
- **Version**: 6.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.5.51-MariaDB
- **URL**: /comm/index.php?mainmenu=commercial&leftmenu=

## Report
Hello,
In commercial space I see the proposals that have been made. But when I click on it is impossible to see them and I can not get my hands on them and find them.
Would you have a solution to solve my problem?
cordially

**Comment by eldy** [comment]
Can you upgrade to 6.0.1
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by simnandez** [comment]
Works for me in 6.0.1

**Comment by BebZ** [comment]
works on 6.0.0 beta too
