### ISSUE TITLE
BUG: Validating invoices fails if selected in bulk action

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#7400]
# Bug
Validating invoices fails if selected in bulk action in version 6.0.0

## Environment
- **Version**: 6
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by eldy** [comment]
Can you provide a screenshot on page where you make the Validate ?
Can't find such feature in bulk action in 6.0

**Comment by GheeEasy** [comment]
![image](https://user-images.githubusercontent.com/24621070/30597537-916aff94-9d57-11e7-9c91-e0e05a9043a2.png)

**Comment by GheeEasy** [comment]
Any news on this? Really annoying if you make e.g. 20 invoices in one go...

**Comment by simnandez** [comment]
I Think this is a external module, Can you provide the url of this page?

**Comment by GheeEasy** [comment]
@simnandez No this is standard feature and also worked in version 5

**Comment by atm-maxime** [comment]
Please give us the URL of the page you are on. I don't recall such a functionality in the dolibarr standard code...

**Comment by GheeEasy** [comment]
Hi Maxime,

 

Issue has been resolved in 6.0.2

 

 

Fom: Maxime Kohlhaas [mailto:notifications@github.com] 
Sent: zondag 5 november 2017 08:27
To: Dolibarr/dolibarr <dolibarr@noreply.github.com>
Cc: GheeEasy <administratie@ghee-easy.nl>; Author <author@noreply.github.com>
Subject: Re: [Dolibarr/dolibarr] BUG: Validating invoices fails if selected in bulk action (#7400)

 

Please give us the URL of the page you are on. I don't recall such a functionality in the dolibarr standard code...
