### ISSUE TITLE
Unable to setup modules

### ISSUE THREAD

**Issue by rajitha-bandara** [Dolibarr/dolibarr#7418]
# Module Setup with a fresh install
When proceed with module setup, giving message "Can not access to https://www.dolistore.com" and script terminated. Did I miss anything?

## Environment
- **Version**: 7-alpha
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by hregis** [comment]
@rajitha-bandara 
you have this message if your dolibarr does not have access to the internet or if the dolistore site is not accessible. I just tested and it works! check if your dolibarr has internet access.

**Comment by rajitha-bandara** [comment]
@hregis For me this happens as a web service exception in dolistore.class.php line 202.
```
$this->api = new PrestaShopWebservice($conf->global->MAIN_MODULE_DOLISTORE_API_SRV,
$conf->global->MAIN_MODULE_DOLISTORE_API_KEY, $this->debug_api);
```

Apache can open url. Looks I need to check further.

**Comment by hregis** [comment]
@rajitha-bandara 
it works for me! your dolibarr is on your computer or on a server? this server has internet access? What is the version of your php? is that from the machine where dolibarr is installed you have access to dolistore? (in case the firewall blocks your ip address)

**Comment by rajitha-bandara** [comment]
@hregis I'm running it on my local XAMPP server, Windows 7, php 5.6, 
yes it can access internet. I disabled firewall & virus guard, still failed.

Dolibarr version is 7-alpha

**Comment by hregis** [comment]
@rajitha-bandara 
php-curl is present ?
contact me by mail for a teamviewer session : https://github.com/hregis

**Comment by rajitha-bandara** [comment]
@hregis php-curl is enabled. Thank you for your time. I'll contact you by email.

**Comment by rajitha-bandara** [comment]
version 6 [stable] works for me, so this is a problem with v7-alpha
