### ISSUE TITLE
dolibarr 6 [!-- BEGIN row.lines --] not working odt

### ISSUE THREAD

**Issue by orloxgr** [Dolibarr/dolibarr#7420]
# Bug
Using an ODT template the [!-- BEGIN row.lines --] do not show anymore. Upgraded from version 5.4 to 6

## Environment
- **Version**: 6
- **OS**: centos 7
- **Web server**: apache 2.4
- **PHP**: 7
- **Database**: maria 10.1

I attach the odt template i use and the outcome.

[invoices.zip](https://github.com/Dolibarr/dolibarr/files/1310139/invoices.zip)

**Comment by camlafit** [comment]
Hello

I find this issue in the week end also :/

Problem come from https://github.com/Dolibarr/dolibarr/commit/f460d2e705ede1ee91420f48fb0a92606f01ee78#diff-da8f7bdc72828ad63c663abdb8484ef3

I search a patch.

**Comment by camlafit** [comment]
Hello @mikee2 

This issue should related to your commit. Disable macroreplaces restore row loop

**Comment by eldy** [comment]
@camlafit 
If you replace code of macroReplace with this, does it works ?

    public function macroReplace($text)
    {
        global $langs;

        $patterns=array( '__CURRENTDAY__','__CURRENTDAYTEXT__','__CURRENTMONTHSHORT__','__CURRENTMONTH__','__CURRENTYEAR__' );
        $values=array( date('j'), $langs->trans(date('l')), $langs->trans(date('M')), $langs->trans(date('F')), date('Y') );

        $text=preg_replace($patterns, $values, $text);

	return $text;
    }

**Comment by camlafit** [comment]
hello @eldy

This code looks same at original. No change on result preg_replace return NULL

**Comment by eldy** [comment]
Oops sorry. the line $patterns should be

  $patterns=array( '/__CURRENTDAY__/','/__CURRENTDAYTEXT__/','/__CURRENTMONTHSHORT__/','/__CURRENTMONTH__/','/__CURRENTYEAR__/' );

is it ok with that for you ?

**Comment by camlafit** [comment]
Was trying a similar patch. Looks ok now :)

**Comment by orloxgr** [comment]
now it is ok.
Thank you.

**Comment by mikee2** [comment]
Hi all.

Yes. The code that is in the repo is not the right one (not my latest code and do not know why the latest one is not in the repo) . Version 6 code that I have just downloaded suffers the same issue.

 

As you have found you have to enclose the macro tags between ‘/’ marks and you should append an ‘u’ at the end of each one like this:

 

/__<pattern>__/u

 

Else you may have problems with if someone is using small caps

 

Regards,

 

Miguel Erill

Doymer Consultores

 

 

De: camlafit [mailto:notifications@github.com] 
Enviado el: lunes, 18 de septiembre de 2017 15:37
Para: Dolibarr/dolibarr
CC: mikee2; Mention
Asunto: Re: [Dolibarr/dolibarr] dolibarr 6 [!-- BEGIN row.lines --] not working odt (#7420)

 

Was trying a similar patch. Looks ok now :)
