### ISSUE TITLE
Bug: Formatting a Product Description

### ISSUE THREAD

**Issue by ozit** [Dolibarr/dolibarr#7444]
# Bug

## Environment
- **Version**: 7.0.0-alpha
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.0.19-1
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL**: /product/card.php?id=2651

## Report
Hello,

When I format a description of a product, all content disappears.

Without formatting, the content is saved normally.

The module of the WYSIWYG editor is of course enabled.

The problem occurs on editing a product in the product module or even in publishing a product in the business proposal part

Thanks

**Comment by eldy** [comment]
Should be fixed with
https://github.com/Dolibarr/dolibarr/commit/e3da4188e2fabb92b8e3302f081aab275aa86ff0
