### ISSUE TITLE
plan comptable mélange langues

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#7449]
Il y a un bug au niveau du plan comptable de Dolibarr 6.0.0.

Le code comptable est indiqué en espagnol dans le fiches produits et services, uniquement pour les achats par exemple : Code comptable (achat) | 607000 - Trabajos realizados por otras empresas

Toutefois, quand je veux modifier la fiche, je le retrouve en Français.

**Comment by eldy** [comment]
Can you try with 6.0.1 ?

**Comment by simnandez** [comment]
Avez-vous activé tous les plans disponibles? Vous devriez avoir activé uniquement le plan qui lui convient
