### ISSUE TITLE
bug : dépenses spéciales

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#7450]
Bonjour,

Un ensemble d'erreurs apparaissent quand on clique sur "dépenses spéciales". Ma version de dolibarr est la 6.0.0.

Je vous transmet la copie en pdf (c'est assez long)

Merci à vous

[Espace des paiements particuliers.pdf](https://github.com/Dolibarr/dolibarr/files/1320418/Espace.des.paiements.particuliers.pdf)

**Comment by eldy** [comment]
Seems to be fixed with 6.0.1

**Comment by ghost** [comment]
same problem in 6.0.2 : 

> 

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20171028062322
Dolibarr: 6.0.2
Niveau de fonctionnalités: 0
PHP: 7.0.19-1
Server: Apache/2.4.25 (Debian)
OS: Linux vps452769 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36

Url sollicitée: /compta/charges/index.php?leftmenu=tax&mainmenu=accountancy
Referer: http://dolibarr.bouddhismes.net/compta/charges/index.php?leftmenu=tax&mainmenu=accountancy
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT c.id, c.libelle as lib, cs.rowid, cs.libelle, cs.fk_type as type, cs.periode, cs.date_ech, cs.amount as total, pc.rowid as pid, pc.datep, pc.amount as totalpaye, pc.num_paiement as num_payment, pc.fk_bank, pct.code as payment_code, ba.rowid as bid, ba.ref as bref, ba.number as bnumber, ba.account_number, ba.accountancy_journal, ba.label as blabel FROM llx_c_chargesociales as c, llx_chargesociales as cs LEFT JOIN llx_paiementcharge as pc ON pc.fk_charge = cs.rowid LEFT JOIN llx_c_paiement as pct ON pc.fk_typepaiement = pct.id LEFT JOIN llx_bank as b ON pc.fk_bank = b.rowid LEFT JOIN llx_bank_account as ba ON b.fk_account = ba.rowid WHERE cs.fk_type = c.id AND cs.entity = 1 AND ( (cs.periode IS NOT NULL AND cs.periode between '20170101000000' AND '20171231235959') OR (cs.periode IS NULL AND cs.date_ech between '20170101000000' AND '20171231235959')) ORDER BY cs.date_ech DESC
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'ba.accountancy_journal' in 'field list'

**Comment by atm-maxime** [comment]
It has been fixed while working on accountancy module
