### ISSUE TITLE
Feature request : Add  birth date for users

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7451]
# Date
For Dolibarr users, it could be usefull to store the birth date.
This information is already stored for the contacts in ```llx_socpeople.birthday```

Tks

**Comment by simnandez** [comment]
For this, you can use the Complementary attributes feature.

**Comment by dolibarr95** [comment]
;)

**Comment by simnandez** [comment]
Your ;) means that this issue can be closed?

**Comment by dolibarr95** [comment]
If it could be a feature request i let this open :p  because this kind of information like gender address is common and could be usefull for hrm module.
If no i will close and use (actually that's what i've done) the complementary attributes.
Tks

**Comment by eldy** [comment]
Done in 7.0
