### ISSUE TITLE
ODT > PDF generation error in factures / propales

### ISSUE THREAD

**Issue by Skitprat** [Dolibarr/dolibarr#7452]
Documents don't generate properly PDF files from ODT files.
ODT files work fine but the conversion fails at some point in propales and factures (work fine in orders with the same document template, which have been working fine for months)

It's not exactly the same bug I already pointed some months ago, factures used to work fine, but don't since 6.0.0 update. Propales don't work since 5.0.0 update.

PDF generation work though when using a .PDF template.

# Bug
2017-09-21 09:09:32 ERR     89.82.36.8      Error url=/htdocs/compta/facture/card.php?facid=188, query_string=facid=188, sql=SELECT rowid,name,label,type,size,elementtype,fieldunique,fieldrequired,param,pos,alwayseditable,perms,list,ishidden,fielddefault,fieldcomputed FROM dol_extrafields WHERE entity IN (0,1) AND elementtype = 'facturedet' ORDER BY pos, db_error=, msg=Error generating document for CommonObject. Error: ODT to PDF convert fail : 

## Environment
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20170921090932
Dolibarr: 6.0.1
Niveau de fonctionnalités: 0
PHP: 7.1.6
Server: Apache
OS: Linux vds2732.sivit.org 2.6.38.4 #1 SMP PREEMPT Thu Apr 28 11:05:01 CEST 2011 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

Url sollicitée: /htdocs/compta/facture/card.php?facid=188
Referer: http://***/htdocs/compta/facture/card.php?facid=188
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur

Message: Error generating document for CommonObject. Error: ODT to PDF convert fail : 

## Expected and actual behavior
Getting a proper PDF file converted from the ODT file

## Steps to reproduce the behavior
In factures or propales, use a .odt template to generate documents. Fails immediately to convert it in .PDF

I use these triggers for automatic generation
MAIN_ODT_AS_PDF
MAIN_DISABLE_PDF_AUTOUPDATE
MAIN_ODT_AS_PDF_DEL_SOURCE

**Comment by mtinfo** [comment]
I have the same problem with Dolibarr 6.0.1 on Ubuntu 16.04.

Here it is the Dolibarr.log line 👍 
Error url=/ERP/compta/facture/card.php?facid=16, query_string=facid=16, sql=SELECT rowid,name,label,type,size,elementtype,fieldunique,fieldrequired,param,pos,alwayseditable,perms,list,ishidden,fielddefault,fieldcomputed FROM llx_extrafields WHERE entity IN (0,1) AND elementtype = 'facturedet' ORDER BY pos, db_error=, msg=Error generating document for CommonObject. Error: ODT to PDF convert fail :

in mysql command line, the query work fine, no result line ,and no error.

using 👍 
MAIN_ODT_AS_PDF     with /folder to /podconverter-cli-2.2.2.jar
MAIN_DOL_SCRIPTS_ROOT

**Comment by danilo1988** [comment]
Hello Skitprat , mtinfo
a pleasure in knowing them both, could solve this problem ?, I am with the same problem :(

**Comment by mtinfo** [comment]
Hi danilo,

Here it is my solution here https://www.dolibarr.fr/forum/12-howto--aide/59961-bugg-conversion-odt-2-pdf-en-v6-0-1-resolu.

it work fine but do not already test with 6.0.2

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
