### ISSUE TITLE
Bug: error 500 in inventory module

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7454]
# Bug
Error 500 on product/inventory/card.php & product/inventory/list.php

## Environment
- **Version**: 6.0.0 (works well with Dolibarr 4.0.0)
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: product/inventory/

```
[21-Sep-2017 11:26:48 Europe/Paris] PHP Fatal error:  Class 'Inventory' not found in /home/server/public_html/dolibarr6/product/inventory/list.php on line 86
[21-Sep-2017 11:26:52 Europe/Paris] PHP Fatal error:  Class 'Inventory' not found in /home/server/public_html/dolibarr6/product/inventory/card.php on line 68
```
If i replace 
```php
dol_include_once('/inventory/class/inventory.class.php');
//with
dol_include_once('/product/inventory/class/inventory.class.php');
```

Get an new error instead 
```
Message: include of actions_massactions.inc.php is done but var $massaction or $objectclass or $uploaddir was not defined
```
tks

**Comment by BebZ** [comment]
Where is this module i don't have access ?

**Comment by dolibarr95** [comment]
In product page :)

**Comment by eldy** [comment]
Module Inventory is still in development and not available with a stable version
Can you make a screenshot where you find this menu ?

**Comment by dolibarr95** [comment]
Hi
![dolibarr6-product-index-php-1506321549886](https://user-images.githubusercontent.com/24292300/30795447-e4fd51f0-a1cd-11e7-8d55-6f4d04ee845e.png)
![dolibarr6-product-inventory-card-php-1506321561377](https://user-images.githubusercontent.com/24292300/30795458-ee554ffa-a1cd-11e7-876b-1b8a2d343271.png)

**Comment by dolibarr95** [comment]
Ok i understand...the constant MAIN_FEATURES_LEVEL value was set to 2. sorry
Tks

**Comment by BebZ** [comment]
Maybe it is an ATM consulting module ?

**Comment by dolibarr95** [comment]
Hi
No it's a Dolibarr module, i have a constant that activate all dev module ```MAIN_FEATURES_LEVEL```

**Comment by hregis** [comment]
@dolibarr95 @BebZ 
this is an external module included in product module need to adapt

https://github.com/Dolibarr/dolibarr/pull/7485

**Comment by dolibarr95** [comment]
tks ;)
