### ISSUE TITLE
Bug: extrafield boolean default value not working

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7456]
# Bug
Default value for boolean field in extrafields menu is not working. Not working for propal and invoices' extrafields at least. I tested with 1 as default value in order to get this field checked by default. The boolean field always appears unchecked by default. Manual check is working.

![image](https://user-images.githubusercontent.com/5360027/30690812-b33aadee-9ec5-11e7-86d7-1feb22f075ef.png)

## Environment
- **Version**: 6.0.1
- **OS**: Ubuntu
- **Database**: MySQL
- **URL(s)**: dolibarr/htdocs/comm/admin/propal_extrafields.php

**Comment by eldy** [comment]
The default value is the default value in database. Not in screen. So it will be value if you make technical import using sql files.
For default values on "screen/form", you must use the menu Home - setup - default values of 6.0

**Comment by vvnt** [comment]
Understand. Thank you.

**Comment by lcaufrie** [comment]
Hi Eldy,

Thanks for this clarification. Without distrub you: do you have an example how to set up a default value in default value screen for extra fields?
Best Regards
Laurent
