### ISSUE TITLE
bug saisie reglement facture

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#7458]
Bonjour,

Un bug plutôt très génant se présente à moi quand je souhaite saisir un reglement pour un fournisseur. j'ai le message suivant 
Incorrect datetime value: '' for column 'date_object' at row 1

j'ai l'impression que l'information saisie dans la date n'est pas inscrite dans la base

dans les logs j'ai :  DB_ERROR_1292

Ma version de dolibarr : 6.0.0

Merci à vous

**Comment by P4ndaFR** [comment]
Bonjour, j'ai exactement le même problème en 6.0.2, vous avez trouvé une solution ?

Merci d'avance

**Comment by ghost** [comment]
Avez vous activé le module "Logs non réversibles" qui est en développement ? (MAIN_FEAUTURE_LEVEL=2)

**Comment by P4ndaFR** [comment]
Le module était effectivement activé, je ne le l'avait pas vue. merci du coup de main et de la réactivité.
