### ISSUE TITLE
[Bug] Multi-currency - supplier invoice description is lost after changing currency

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#7461]
Dolibar 6.0.0

Bug:
Description of service is lost after changing currency of supplier invoice.

How to repeat:
- Setup multicurrency - have euros (main currency) and dollars.  Define an exchange rate.
- Create a supplier invoice in Euros with a service having a description and a value in euros, validate it.
- Clone that validated supplier invoice.
- Change the currency of the cloned supplier invoice from EUR to DOL.
- Note that the service value is updated, but the service description is lost.

**Comment by MartinFulgueiras** [comment]
Hi, this bug has been happening since 4.0. It also happens with products. When you change a proposal to a customer order or invoice it happens too. 

Thanks
