### ISSUE TITLE
Change order in dict (Conditions de règlement - id = 12) get sort error in SQL

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7465]
# Bug : change order in dict (Conditions de règlement - id = 12) get sort error in SQL

Once you change sort order in an existing record on the Dict page for "Conditions de règlement" (dict : 12), you get an error. The SQL query is wrong :

SELECT c.rowid as rowid, c.code, c.libelle, c.libelle_facture, c.nbjour, c.type_cdr, c.decalage, c.active, c.sortorder FROM llx_c_payment_term AS c WHERE 1 = 1 ORDER BY **sortorder 2,** sortorder ASC, code ASC LIMIT 1001

**sortorder 2** should not exist.

------

Dolibarr a détecté une erreur technique.

Date: 20170922101545
Dolibarr: 6.0.1
Niveau de fonctionnalités: 0
PHP: 7.0.18-0ubuntu0.16.04.1
Serveur: Apache/2.4.18 (Ubuntu)
OS: Linux ubuntu 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

Url sollicitée: /dolibarr/htdocs/admin/dict.php?id=12
Referer: http://192.168.0.0/dolibarr/htdocs/admin/dict.php?sortfield=sortorder&sortorder=0&rowid=2&code=30D&&id=12&action=edit&page_y=0
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT c.rowid as rowid, c.code, c.libelle, c.libelle_facture, c.nbjour, c.type_cdr, c.decalage, c.active, c.sortorder FROM llx_c_payment_term AS c WHERE 1 = 1 ORDER BY sortorder 2, sortorder ASC, code ASC LIMIT 1001
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2, sortorder ASC, code ASC LIMIT 1001' at line 1

**Comment by eldy** [comment]
Looks fixed for 6.0.2
