### ISSUE TITLE
Feature Request: Contracts have their own address, zip, town, state and country

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7466]
# Feature Request
Contracts have their own address, zip, town, state and country instead of using the designated third party's address, zip, town, state and country.

## Use case
In some cases a contract is made between the company and the destined third party, but the provided services will not be done at the third party's headquarters address. It will be done at one of the third party's branch offices.

## Suggested implementation
Instead of adding multiple addresses to the third party for each of it's branch offices (that won't appear in the contract list or card) the contract could have it's own address to designate to where the listed hired services will be provided.
It should be noted that adding a third party for each branch office is not practical, they share much of the information except for name and address. And there is the downside that the VAT number will be duplicated several times.

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by atm-maxime** [comment]
For me this already exists.
You don't have to create a third-party for each address, but you have to create all addresses on the same third-party. Then in the contract, you can select the concerned address in the contact/address tab.
This is like this that shipping and billing addresses are managed, I think this applies to contracts too!

**Comment by ruistrecht-alt** [comment]
I have seen that, but that isn't very intuitive for me.
Using that method I can't filter contracts by their "destination" address, I have to guess that address by filtering the third-party and opening all contracts.
Besides I don't see the usefulness of filtering by the third-parties address in the contracts. If you filter by the third-party name and open the third-party, you'll get the address.
