### ISSUE TITLE
Feature request: Set standard shipping method in client card (just like payment options)

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#7468]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 6
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
Would be fantastic to be able to set default shipping method in client card.

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by BebZ** [comment]
Maybe you could describe a little bit more your request, as a "frame" is proposed
Your request is not readable as you kept all the fields you did not want to use.

**Comment by GheeEasy** [comment]
Sorry for this...I new here and thought everything had to stay in.
So the request is as follows:
When setting up a client numerous things can be set for this client. E.g. payment option and terms. It would be great to be able to set a default shipping method (table llx_c_shipment_mode)

Thanks

**Comment by atm-maxime** [comment]
There's a hidden option called SOCIETE_ASK_FOR_SHIPPING_METHOD which does exactly what you need. I'll add it on the wiki.

**Comment by atm-maxime** [comment]
It's now an option available in the thirdparty module setup.
