### ISSUE TITLE
Supplier order PDF the local tax 1 and local tax 2 are messed up

### ISSUE THREAD

**Issue by suryacaprice** [Dolibarr/dolibarr#7471]
Local tax 1 and Local tax 2 are displayed individually for each product in Supplier order PDF

![image](https://user-images.githubusercontent.com/24731040/30770392-3eaabaee-a04d-11e7-9c04-8c4d71f89a0f.png)

how to fix it in pdf

**Comment by eldy** [comment]
Fix in 
https://github.com/Dolibarr/dolibarr/commit/270aba99faabfd561fddfa8f7e94a8b413db2508
