### ISSUE TITLE
Bug Upadate 5.0.0 to 6.0.1

### ISSUE THREAD

**Issue by dedioweb** [Dolibarr/dolibarr#7472]
# Bug
Problème dans Interfaces avec des systèmes externes / Problem in Interfaces with external systems

## Environment
- Version: 6.0.1
- OS: Linux
- Web server: Apache
- PHP: 5.6.31
- Database: MySQL or MariaDB 5.6.37
- URL(s): /htdocs/admin/modules.php?mainmenu=home

## Expected and actual behavior
Manque configuration Paybox, PayPal, Stripe / Lack of configuration Paybox, PayPal, Stripe

## [Attached files]
![sur-mon-serveur-web](https://user-images.githubusercontent.com/20359968/30773425-8e9a8b9c-a070-11e7-831f-5e324f0ecbd2.png)

**Comment by eldy** [comment]
Sorry, i don't understand what's wrong ?

**Comment by dedioweb** [comment]
@eldy 
I did the update from version 5.0.0 to 6.0.1, but in the modules, I do not find Paypal, Stripe etc, so I think there is a bug

**Comment by eldy** [comment]
Wich package do you use to make your upgrade ?

**Comment by eldy** [comment]
It looks the showing of page is stop before end.
Can you have a look into your apache error file ?

**Comment by dedioweb** [comment]
https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/6.0.1/ 
Download dolibarr-6.0.1.zip (44.5 MB)

**Comment by dedioweb** [comment]
I'm not sure how to find them, I think I have access in SSH, would you know the command to access the log apache? I am running Linux Centos

**Comment by eldy** [comment]
You can send me a private message with the ssh access to eldy@destailleur.fr so i can have a look.

**Comment by dedioweb** [comment]
@eldy le mail vient de partir

**Comment by dolibarr95** [comment]
Hi
This error often happens in my Dolibarr(all version) when I declare badly a new module. So i delete all my modules and their constants and reinstall one by one.

**Comment by dedioweb** [comment]
the change from php 5.6 to php 7 solved the problem
![capture d ecran 2017-09-27 a 12 43 46](https://user-images.githubusercontent.com/20359968/30909485-8eb56dea-a381-11e7-8d7a-065d916154df.png)
