### ISSUE TITLE
Mass vat change and product tax import not working in 6.0.1 with India GST settings

### ISSUE THREAD

**Issue by technoartista** [Dolibarr/dolibarr#7473]
![image](https://user-images.githubusercontent.com/19356598/30775450-5abb9910-a0b1-11e7-8343-9963ec3640f8.png)
![image](https://user-images.githubusercontent.com/19356598/30775456-6b7695c0-a0b1-11e7-8fc0-af27b05db076.png)

Dolibarr v6.0.1 unable to do the mass vat change 

Country India 

IGST : VAT
CGST : lt1
SGST : lt2

vat is 0 when using lt1 and lt2 ..

when importing its by default updated to 0% tax even when i use 9/9 . Please help me .. How to mass change the vat rate of products

I want to change from 0% to 9/9 CGST+SGST

**Comment by suryacaprice** [comment]
is it also applicable to import 0/9/9 as tax ? When will be the next version released with this fix ?
