### ISSUE TITLE
Commercial proposal not displying LT1 and LT2 in PDF

### ISSUE THREAD

**Issue by technoartista** [Dolibarr/dolibarr#7475]
I am using 6.0.1 Commercial proposal not displaying LT1 and LT2 in PDF , can you send me the code fix for that if anyone has it?

**Comment by eldy** [comment]
Find a fix here:
https://github.com/Dolibarr/dolibarr/commit/3a7aea48d76d82f2a4de61785b13caa014d641be
+
https://github.com/Dolibarr/dolibarr/commit/adb3827d1eeb3c6ce963155b776b35f922f2417d
