### ISSUE TITLE
Proposal page width too large when using units

### ISSUE THREAD

**Issue by jhardy08** [Dolibarr/dolibarr#7478]
# Bug
When the product units are enabled via the hidden option "PRODUCT_USE_UNITS" the page use to create the proposal becomes too wide for the screen.

## Environment
- **Version**: 6.0.1
- **OS**: OVH Cloud
- **Web server**: Apache
- **PHP**: 5,6,30
- **Database**: MySQL or MariaDB 5.5.55-0+deb7u1-log
- **URL(s)**: /comm/propal/card.php?id=1

## Expected and actual behavior
The page layout doesn't seem to take into account the added column for the units.

Page without units enabled

![capture2](https://user-images.githubusercontent.com/32248964/30787285-7a444e42-a185-11e7-9b55-ded140c6c572.PNG)

Page with units enabled
The right part of the proposal is out of screen. It is necessary to scroll or zoom out to view the full page width.

![capture](https://user-images.githubusercontent.com/32248964/30787286-7a4d2558-a185-11e7-8a92-6f624ff8907f.PNG)

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by atm-maxime** [comment]
After some tests, this is not related to the unit dropdown.
The width of the add line form is directly related to the width of the product/service select, which is directly related to the width of your product/service labels.
Switch to a search box instead of a dropdown, you'll see.
