### ISSUE TITLE
Indian GST tax percentage and HSN code update

### ISSUE THREAD

**Issue by suryacaprice** [Dolibarr/dolibarr#7479]
https://cleartax.in/s/gst-rates

https://cleartax.in/s/what-is-sgst-cgst-igst

http://economictimes.indiatimes.com/news/economy/policy/a-quick-guide-to-india-gst-rates-in-2017/articleshow/58743715.cms

https://www.teachoo.com/5985/1942/IGST-Tax-Rates-and-Computation/category/Understanding-Output-and-Input-GST/

There are 5 tax slab in india

0% , 5% , 12% , 18% and 28% with CGST , SGST and IGST

For 5% 
CGST/SGST - 0 / 2.5% / 2.5%

IGST - 5%/0/0
similar for all other percentages .. As of now only 9% is added in Dolibarr.

You also have to add the HSN code for the products in both product module and free entry and display in invoice , quotes etc ..

https://cleartax.in/s/gst-hsn-lookup
https://gstindia.net/hsn/

**Comment by eldy** [comment]
I suggest to add new vat entries with a vat code that will be :
I-28
C+S-28
I-18
C+S-18
I-12
C+S-12
I-5
C+S-5

**Comment by eldy** [comment]
For the HSN, i think this is what is called the 
"Commodity Code"
Currently in dolibarr, this field exists on products. It is called "Custom code" but we will rename it "Custom/Commodity/HS code" in a future version
It it is defined, it will appear on quotes, invoices, ...

**Comment by suryacaprice** [comment]
oh ok . How to enable it in the free entry products . 
As of now I have created a extra field in products but unable to get the values in the invoice pdf for the free entry 

$pdf->MultiCell (0,5, $outputlangs->convToOutputCharset($object->lines[$i]->array_options['options_hsn']),0,'L');

this code is not displaying anything

![image](https://user-images.githubusercontent.com/24731040/30842654-704c7d20-a2a1-11e7-9ad4-12ffeb8e3231.png)

**Comment by eldy** [comment]
Yes, extrafields are managed on screen but not on PDF output (surely available in a next version).

Once you have defined the custom/HS code on product, each time you enter a product in a quote or invoice or order, the description of product is completed at end with 
(Customs code: xxxx)
This means a change in the hs code is effective only for line inserted into document AFTER you set it.

For free entry product, we can't complete this information as we don't know the value. So you must enter the value yourself. There is no dedicated field, but you can complete data at end of description, so it will be visible on PDF.

**Comment by hussain-attari** [comment]
Hi,

Can you create a dedicated field for Customs Code [HSN]. 

It is now going to become mandatory in India for the HSN to be mentioned on all invoices. 

I use the free entry product option while creating my quotes and invoices as I deal in a lot of custom made products I am unable create a product for each of them.

Another benefit of creating this column is that it will ensure that the HSN Code for product is mentioned in all the necessary documents and will avoid unnecessary omissions while creating the documents.

A line tag for ODT will also be required column creation and insertion at individual product level in custom ODT Formats

Regards
Hussain
