### ISSUE TITLE
Can't join any file to a supplier proposal

### ISSUE THREAD

**Issue by mapiolca** [Dolibarr/dolibarr#7480]
An error is appearing when we want join a file

![capture d ecran 2017-09-25 a 08 18 27](https://user-images.githubusercontent.com/32256817/30794888-0fc1a47a-a1cb-11e7-8dab-56bd5618d7bc.png)

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by mapiolca** [comment]
Fixed with 6.0.0
Not for 5.0.6
