### ISSUE TITLE
Bug  : can edit less than minimum quantity of an article in a supplier order.

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7492]
# Bug
Can add less than minimum quantity of an article in a supplier order.
eg : 
- supplier : Elec1
- product : bulb45
- purchasing price : 2€ minimum quantity 20 ; 1€75 minimum quantity 100 ; 1€ minimum quantity 500

1. Create the supplier order PROV9988 (Elec1)
2. Add 19 bulb45 : ko because not enough bulb45
3. Add 25 bulb45 :  ok because enough bulb45
4. Edit quantity 25 to 19 :  **ok but should be ko because not enough bulb45**

## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: fourn/commande/card.php?id=

Tks

**Comment by dolibarr95** [comment]
We could check before updateline :
```php
$productsupplier = new ProductFournisseur($db);
$productsupplier->get_buyprice(0, $qty, $line->fk_product, 'none', $this->fk_soc);
```

**Comment by atm-arnaud** [comment]
Hello,

@eldy  this is not a bug but a missing feature. In ProductFournisseur get_buyprice function, we can't fetch without rowid (product fourn price). And in CommandeFournisseurLigne there is no data about rowid(product fourn price) in database. I think that we need to save this data in CommandeFournisseurLigne But it will be a NEW comportment.

So @dolibarr95, I could understand your problem and i agree with this mind. But we definitivly can't fix this in a current branch. It will change many things about Suppliers Order.

(I already spend 1 hour on this issue to understand supplierOrderLine procces). Sorry for my english, I do my best.

Regards,

**Comment by dolibarr95** [comment]
Hi !
Tks for this reply :-) You're right :

>  I think that we need to save this data in CommandeFournisseurLigne 

Actually in this pr we only display a warning but still update the line (#7500 & #7507) even if the quantity is not enough.

Here what i've done with a little module because we create order with hundreds lines and modify very often (import lines via csv file) a draft order :

In supplier order edit mode, when insert new line, edit or import new lines : 

Check if this product still exist in the order
- if no : check if qty is enough if yes insert line
- if yes : quantity = new quantity + quantity in the other lines and retrive the best supplier price for this quantity

_In my case for eg:_
We validate our order before 2pm to be deliverd the next morning.
A supplier order draft exists with 50 lines with 10 products bulb45.
We launch a new production a need more products from this supplier so we import (in csv file) 110 lines with perhaps 5 bulb45.

Tks
