### ISSUE TITLE
Bug: Users can't input Hollidays/leave/sick/Maternity days

### ISSUE THREAD

**Issue by MartinFulgueiras** [Dolibarr/dolibarr#7515]
# Bug

## Environment
- **Version**: 6.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.37
- **URL**: /crmd/user/perms.php?id=32&action=addrights&entity=1&rights=20005&page_y=3685

## Report

There seems to be a small bug in the user permissions section for new leaves requests. If the user doesn't have the permission to create for everyone, then he can't create for himself either. When the permissions are set as the image below, everything is fine:
![screenshot-2017-9-27 permissions](https://user-images.githubusercontent.com/32270312/30928813-3db8050a-a382-11e7-8d7f-9f3f687a6c32.png)

But if the admin user unchecks the "Create/modify leave requests for everybody" for the user:
![screenshot-2017-9-27 permissions 1](https://user-images.githubusercontent.com/32270312/30928942-9761b7ea-a382-11e7-9246-2d117321f0a5.png)

Then when wanting to input a personal request for leave there appears a blank page and can't place the request:

![screenshot-2017-9-27 leaves](https://user-images.githubusercontent.com/32270312/30928982-c42cb9e6-a382-11e7-9ee1-ed73099acb77.png)

When returning the permissions to the first image, everything comes back to normal:
![screenshot-2017-9-27 leaves 1](https://user-images.githubusercontent.com/32270312/30929059-f39cb6a4-a382-11e7-9e17-945b8e267d13.png)

Muchas gracias for the incredible work. I hope these reports help for further versions. 

Martín

**Comment by eldy** [comment]
Can you disable and re enable module leave request and tell if you still can reproduce problem ?

**Comment by MartinFulgueiras** [comment]
Hi, just did, still the same issue. Thanks

**Comment by eldy** [comment]
Can reproduce.
Can you upgrade to 6.0.3 ?

**Comment by MartinFulgueiras** [comment]
It's solved

Thanks

Martín
Inst. @mistermacarti
