### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by servitecpc** [Dolibarr/dolibarr#7519]
# Bug

## Environment
- **Version**: 6.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL or MariaDB 5.5.5-10.1.28-MariaDB
- **URL**: /ERP/comm/card.php?socid=192

## Report
Fatal error: Cannot redeclare class modWebsites in /home/servite1/public_html/ERP/htdocs/core/modules/modWebsites.class.php on line 126

**Comment by dolibarr95** [comment]
hi
works for me : 
## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: comm/card.php?socid=192

**Comment by servitecpc** [comment]
alguna idea de que sera el error ?

**Comment by dolibarr95** [comment]
hi
Could be an external module.

**Comment by atm-maxime** [comment]
Seems related to an external module, works for me
