### ISSUE TITLE
Bug : error in translation

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7522]
# Bug
Syntax error in alert message.

## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**:societe/rib.php?socid=2104&id=137&action=delete

![traduction](https://user-images.githubusercontent.com/24292300/31007810-0a5b747c-a502-11e7-9aec-cea512fe48e2.png)

I looked for this value in https://www.transifex.com/dolibarr-association/dolibarr/dashboard/ with no result.
The label should be : 
 **Etes-vous sur de vouloir supprimer ce compte bancaire ?**

Tks

**Comment by atm-maxime** [comment]
Fixed in transifex. Thanks
