### ISSUE TITLE
Infinite loop in Agenda per user view if workinghours not set correctly

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#7533]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
Infinite loop in Agenda view peruser.php if workinghours config is wrong set

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [Linux]
- **Web server**: [Apache]
- **PHP**: [5.6]
- **Database**: mysql
- **URL(s)**: [/comm/action/peruser.php]

## Expected and actual behavior
infinite loop in hour display instaead of workinghours loop
lines 603-639 
Problem comes if you set the workings hour in admin/ihm.php  with a space : 9 -18 instead of 9-18

## Steps to reproduce the behavior
set wotkinghours as 9 -18 and go to /comm/action/peruser.php

**Comment by atm-arnaud** [comment]
Hi,

Thank you about this bug reporting. We only need one more information about. In which Dolibarr version do you have this error ?
- 4.0.6
- 5.0.7
- 6.0.1
- other

To find this information you could connect to your Dolibarr and it will be written **under the left menu**.
If you don't find it you will see it into the disconnection popin notice (information bubble)

Regards,

**Comment by tiaris** [comment]
Détecté en 5.0 voir dans les autres versions
