### ISSUE TITLE
Bug: Localtax2 rate shows in invoice preparation and PDF invoice mixed with VAT in each line

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#7536]
# Bug
Localtax2 rate shows in invoice preparation and invoice mixed with VAT in each service line. The calculation is not affected.

## Environment
- **Version**: 6.0.0 & 6.0.1
- **OS**: Ubuntu 16.04.3
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- **Database**: MySQL 5.7.19
- **URL(s)**: N/A

## Expected and actual behavior
If localtax2 rate is to be displayed in each service line (which was not the case in version 5.x) , it should be identified as such and not mixed under the VAT description to avoid confusion. Furthermore, if it is the desired effect (maybe should be a user option to display it or not), it should show in all service line. If the service line is offered, the localtax2 rate does not show. Finally, the rates for localtax2 rate should show the same way (i.e. negative).

## Steps to reproduce the behavior
Create an invoice with localtax2 activated (IRPF for Spain).
Localtax2 is added to the online invoice and the produced PDF under VAT - One time negative (online invoice), one time positive (PDF)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

Online Invoice Creation for service with amount:
![image](https://user-images.githubusercontent.com/5640062/31074192-b78e389a-a76f-11e7-86d4-591a7894005a.png)

Online Invoice Creation for service with amount offered (zero):
![image](https://user-images.githubusercontent.com/5640062/31074357-8d66de22-a770-11e7-8ef5-87ef63525e49.png)

PDF Invoice for service with amount:
![image](https://user-images.githubusercontent.com/5640062/31074203-c8b0a68a-a76f-11e7-9d26-0e6ade6c2e16.png)

PDF Invoice for service with amount offered (zero):
![image](https://user-images.githubusercontent.com/5640062/31074389-afa4222e-a770-11e7-9cd7-b1b2d03e2bc2.png)

**Comment by simnandez** [comment]
This is not a bug, For India compatibility in dolibarr 6 this is a new feature, your can enable and disable it into pdf setup page.

**Comment by dom-breizh** [comment]
OK. It is not a bug. But could it be at least formatted consistently ? Or is it part of the requirement ?
