### ISSUE TITLE
Error importing stocks

### ISSUE THREAD

**Issue by pyorokun7** [Dolibarr/dolibarr#7540]
# Bug
When mass importing stocks through Excel or CSV, if the value in Product* (ps.fk_product) is fully numeric, it creates a new fk_product in llx_product_stock, instead of looking up the rowid from llx_product through the ref value. This causes the stock from the original product in llx_product to continue to be NULL.

Edit: confirmed to happen in CSV as well.

Actual behaviour (this is from MariaDB)

>select rowid, ref, label, stock from llx_product;
|  1396 | 9837-292    | REDUCTOR CPVC SCH80 2 1/2"X2"                 |     5 |
|  1397 | 9837-338    | REDUCTOR CPVC SCH80 3"X2"                     |     3 |
|  1398 | 9837-422    | REDUCTOR CPVC SCH80 4"X3"                     |     3 |
|  1399 | 9847-010    | TAPA CPVC SCH80 1"                            |    10 |
|  1400 | 10004070    | CODO 45° DR11 POLIETILENO 10"                 |  NULL |
|  1401 | 10001045    | CODO 45° DR11 POLIETILENO 12"                 |  NULL |
|  1402 | 10007359    | CODO 45° DR7 POLIETILENO 2"                   |  NULL |
|  1403 | 10002941    | CODO 45° DR11 POLIETILENO 3"                  |  NULL |

> select fk_product, reel from llx_product_stock;
|       1396 |    5 |
|       1397 |    3 |
|       1398 |    3 |
|       1399 |   10 |
|   10004070 |    2 |
|   10001045 |    4 |
|   10007359 |   10 |
|   10002941 |   10 |

This happens even if the ps.fk_product column in the stocks Excel file and the p.ref column in the Excel product file are both forced to be TEXT. It happens in CSV as well.

## Environment
- **Version**: Confirmed to happen in 6.0.0 and 6.0.1
- **OS**: Windows NT WSPERU 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586
- **Web server**: Apache/2.4.26 (Win32) OpenSSL/1.0.2l
- **PHP**: PHP/5.6.31
- **Database**: MySQL or MariaDB 5.5.5-10.1.25-MariaDB
- **URL(s)**: imports/import.php

## Expected and actual behavior
Expected behaviour: fully numerical ps.fk_product column in the stocks Excel file will lookup the correct ref key from llx_product, and update the corresponding stock value

Actual behaviour: instead of looking up ref values from llx_product, it creates a new value for fk_product in llx_product_stock, and therefore doesn't update the stock value.

## Steps to reproduce the behavior
* Import products, then stock amounts through Excel or CSV, where the ps.fk_product column in the stocks file and the p.ref column in the product file are both fully numerical

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[2017-10-02 - Example Products.xlsx](https://github.com/Dolibarr/dolibarr/files/1349940/2017-10-02.-.Example.Products.xlsx)
[2017-10-02 - Example Stocks.xlsx](https://github.com/Dolibarr/dolibarr/files/1349939/2017-10-02.-.Example.Stocks.xlsx)

**Comment by eldy** [comment]
You can try this:
If the value of column is id,   use  value like this
"id:123456"
If it is ref, use
"ref:abcdef"
So the import will known if it is the id or the ref and should not fails.
