### ISSUE TITLE
[Bug] [Projects/Tasks] Bad dates shown for task time spent in project/task.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#7550]
# Bug
Dates shown for time spent are incorrect on /projet/tasks/time.php 
## Environment
- **Version**: 6.0.1
- **URL(s)**: /projet/tasks/time.php 

## Expected and actual behavior
Show correct dates.

## Steps to reproduce the behavior
Assign time on tasks on different days for two weeks.
View the task time spent in the project task detail.

![image](https://user-images.githubusercontent.com/1504752/31120181-db5dac46-a833-11e7-8adb-a48b12791873.png)

Time sheet detail showing different dates (second week):
![image](https://user-images.githubusercontent.com/1504752/31120105-9531c6e4-a833-11e7-9ace-fc4ebce6824f.png)

**Comment by mdeweerd** [comment]
Extra information regarding this bug.

I added details to the time spent on the tasks (first image above).  The date that is shown when editing the task is the same as shown in the task detail view and no the date in the Time sheet view.

After changing the date in the task detail view, the date of the time spent on the task is correct in that same view.

Therefore, it seems that there are multiple dates for a tasks and that the one shown on the task detail view can be corrected.
I hope that this helps to identify the bug.

**Comment by eldy** [comment]
This is a request to fix data
select * from llx_projet_task_time where task_datehour < task_date or task_datehour > DATE_ADD(task_date, interval 1 day)

Then fix will be available on 6.0.2
