### ISSUE TITLE
[Bug] [Projects/Task/Time sheet] Task repeated on timesheet if different roles for user.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#7554]
# Bug
When a User has different roles on a project/task, the task is appearing multiple times in the time sheet overview.

## Environment
- **Version**: 6.0.1
- **URL(s)**: /projet/activity/perweek.php?leftmenu=tasks

## Expected and actual behavior
Every task should appear only once.

## Steps to reproduce the behavior
Assign User several times on task (/project).

## Suggested implementation
Group by on SQL query to get each task only once?

**Comment by eldy** [comment]
I can't reproduce.
Can you try to reproduce on  demo.dolibarr.org ?
