### ISSUE TITLE
Issues on statistic view by customer

### ISSUE THREAD

**Issue by IswariBenoit** [Dolibarr/dolibarr#7556]
# Bug
If you want to see the stat for a specific customer with only this information.
- the stat will be empty ! ( on previous version it was working ...)
- And the "customer field" is also clear when the page is refreshed !

## Environment
- **Version**: 6.0.0

## Expected and actual behavior
- We are expecting a stat view like the previous version of Dolibarr with only the customer field filled ! 
- An also to keep the name of the customer inside the customer field ! 

## Steps to reproduce the behavior
- on top select : "Compta/Tréso"
- on left select : "Statistique"
- Select one customer
- Leave empty the other field ! 
- Click "Refresh"

**Comment by atm-maxime** [comment]
Fixed in 6.0.4
