### ISSUE TITLE
Bug [HOLIDAY] Blank page on new holiday request

### ISSUE THREAD

**Issue by Larsene** [Dolibarr/dolibarr#7557]
# Bug
since the v5.0.5, it is impossible to create new holiday requests : there's a blank page

![bug-dolibarr](https://user-images.githubusercontent.com/8544729/31169847-5051b26a-a8fa-11e7-93ea-6f2ce35124f1.jpg)

## Environment
- **Version**: since 5.0.5
- **OS**: Windows Server 2013
- **Web server**: Wamp Server x64 / Apache 2.4.23 
- **PHP**: 5.6.25
- **Database**: MySQL : 5.7.14

## Expected and actual behavior
show the page to create a new holiday request

## Steps to reproduce the behavior
update the 5.0.4 dolibarr install to 5.0.5 or newer, then try to create a new holiday request

## Suggested implementation
copying the old /holiday/card.php file from the 5.0.4 version and replacing the new one works.

**Comment by eldy** [comment]
Can you see if you have an error message into your apache error.log file ?

**Comment by steschuser** [comment]
This could be the same as in #8029 
Fix has already been merged.

Can you try with https://github.com/Dolibarr/dolibarr/commit/7e8fda2d71ef31181c104c9eec81f1001cdb7511

**Comment by Larsene** [comment]
right. this bug is gone.
