### ISSUE TITLE
BUG [Holiday] - does not display type in the list

### ISSUE THREAD

**Issue by Larsene** [Dolibarr/dolibarr#7558]
# Bug
The type of holiday is not listed, then you can't see it in the holiday's list.

![bug-dolibarr2](https://user-images.githubusercontent.com/8544729/31170195-83859434-a8fb-11e7-9251-bfd8b4d9d262.jpg)

## Environment
- **Version**: since 5.0.5
- **OS**: Windows Server 2013
- **Web server**: Wamp Server x64 / Apache 2.4.23 
- **PHP**: 5.6.25
- **Database**: MySQL : 5.7.14

## Expected behavior
show the holiday type .
![bug-dolibarr2b](https://user-images.githubusercontent.com/8544729/31170375-1bc5e654-a8fc-11e7-9037-5f8af854d220.jpg)

## Steps to reproduce the behavior
Juste take a look on the holiday's list.

**Comment by eldy** [comment]
Fixed by 20b91a8d5f4aa2b0257f436040cb4d787cc55aa2
