### ISSUE TITLE
Bug [Holiday] display the holiday type ID instead of human readable text

### ISSUE THREAD

**Issue by Larsene** [Dolibarr/dolibarr#7559]
# Bug
In the Holiday's list, when you're connected as an admin, you did'nt see the Holiday's type in the column, but the Holiday's type database ID.
![bug-dolibarr3](https://user-images.githubusercontent.com/8544729/31170640-2121d59e-a8fd-11e7-9a34-905db24ae786.jpg)
 
## Environment
- **Version**: since 5.0.5
- **OS**: Windows Server 2013
- **Web server**: Wamp Server x64 / Apache 2.4.23 
- **PHP**: 5.6.25
- **Database**: MySQL : 5.7.14

## Expected and actual behavior
Display the correct, human readable Holiday's type instead of his ID

## Steps to reproduce the behavior
Connect as an admin, the take a look at the Holiday's list on one of your employee

**Comment by eldy** [comment]
Fixed for 7.0
