### ISSUE TITLE
upgrade path from 3.5.5 to 6.0

### ISSUE THREAD

**Issue by LuisBL** [Dolibarr/dolibarr#7564]
What is the correct path to migrate from 3.5.5 to 6.0?

1. to install 6.0 and follow instructions 
or 
2. install 4.x upgrade, then install 5.x and upgrade and 6.0 and upgrade ?

**Comment by eldy** [comment]
install 6.0 programs, then follow instructions that will tell you to upgrade data from 3.5 to 3.6 then wizard will ask you to upgrade from 3.6 to 3.7 etc..
