### ISSUE TITLE
[BUG] Rest API endpoints conflict (dictionnarytowns)

### ISSUE THREAD

**Issue by JavierNR** [Dolibarr/dolibarr#7566]
# Bug
API Explorer returns: Unable to read api 'dictionnarytowns' from path https://dolibarrurl/api/index.php/explorer/resources.json/dictionnarytowns (server returned undefined).
Note that my actual dolibarr version is 6.0.1 and it's installed since 3.4.1

## Environment
- **Version**: 6.0.0+
- **OS**: Linux Debian 9
- **Web server**: Apache/2.4.25
- **PHP**: 5.6.30-0+deb8u1
- **Database**: MariaDB 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL(s)**: .../api/index.php/explorer/#!/login/list

## Steps to reproduce the behavior
Just login into api explorer with our API key previously generated. The error appears on top as soon as restler loads the api endpoints.
Cannot navigate thru endpoints (doesn't expand). Also attaching a screenshot.. you will observe two similar endpoints (dictionnarycountries and dictionarycountries) and (dictionnarytowns and dictionarytowns)

## [Attached files]
![image](https://user-images.githubusercontent.com/1872120/31232525-6e6d8d14-a9ea-11e7-8407-77127c14473c.png)

**Comment by hregis** [comment]
@Javierete 
do you crush the files of your dolibarr during an update instead of replacing the entire directory? If you overwrite the files, there may be old files that create a conflict

**Comment by JavierNR** [comment]
Hello @hregis thinking about it, probably overwrite the folder with new update. Do you mean I need to remove all directories and upload the new ones?
Will try that later today and post here the results, probably you are correct and I raise an issue too soon (apologies for that)...

**Comment by hregis** [comment]
@Javierete 
try to replace "/htdocs/api/"  directory

**Comment by JavierNR** [comment]
Hello again, I've replaced the directory and it works flawlessly.
Many thanks, closing issue now..
