### ISSUE TITLE
[Feature Request] Reject payment

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#7572]
# Feature Request
I need to mark some payments as rejected.

## Use case
When I receive checks, sometimes they are refused in bank.
I have seen that the paiement class already has a method **reject** but it does not seem to use.
I want to code it but I want to be sure of the implementation before.

## Suggested implementation
Add option BILL_ADD_PAYMENT_REJECT to enable this feature.
Add "Reject" button on payment card.
After user confirmation of payment reject, it will be generate a new negative payment and reopen customer invoice.

@eldy if you agree, I will code it.

**Comment by atm-maxime** [comment]
This function already exists on a check receipt card. You have an icon to declare the check rejection in the check list on a check receipt card.

**Comment by tuxgasy** [comment]
@atm-maxime Thank you, I did not know that.
