### ISSUE TITLE
Extra fields not importing for products

### ISSUE THREAD

**Issue by technoartista** [Dolibarr/dolibarr#7581]
![image](https://user-images.githubusercontent.com/19356598/31288658-76baa250-aae3-11e7-852f-e7ff87fb3414.png)
i have 2 extra fields in the products when importing with excel . its not importing . the value is empty in the database

Version 6.0.1

**Comment by hderiau** [comment]
I encountered the same issue. In both products and third parties (i'm suspecting the same happens with any kind of attribute). All attribute fields data present in the csv files is ignored when imported. All other standard fields are imported without any problem. No error message was displayed.

VErsion 6.0.3

**Comment by hderiau** [comment]
same issue
both for products and third parties

Version 6.0.3

No error message during import

![safariscreensnapz072](https://user-images.githubusercontent.com/33991466/33235833-59346a7e-d1f6-11e7-984f-01b2d383512f.jpg)
![safariscreensnapz073](https://user-images.githubusercontent.com/33991466/33235834-594726e6-d1f6-11e7-9055-12e8a3c73399.jpg)
