### ISSUE TITLE
[Bug] No descriptions when creating credit invoice from supplier invoice.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#7591]
# Bug
When creating a credit invoice ("Facture avoir" (FR)) from a  Supplier invoice, the descriptions are not copied.

## Environment
- **Version**: 6.0.1

## Expected and actual behavior and steps
- Create a supplier invoice, validate it.
- From the supplier invoice, create a credit invoice ("Facture avoir" (FR)) and choose to copy the product/service lines.
- Actual behavior: the descriptions are empty on the new invoice.
- Expected behavior: the descriptions are copied to the new invoice.

**Comment by atm-maxime** [comment]
I think that credit note on supplier invoice is not a standard feature but a hidden one. This feature will continue to be developed.

**Comment by nicoxygen** [comment]
i have same problem with 6.0.3 version and you can not click on enter refund because Remaining amount to be repaid is null ( 0.00 )

**Comment by mdeweerd** [comment]
The button "Créer facture avoir" is available in the demo (6.0.4) but no problem, we can add the lines ourselves.

**Comment by nicoxygen** [comment]
ok i have tested thank you
