### ISSUE TITLE
Bad PDF generation in Expense Report using standard template

### ISSUE THREAD

**Issue by steel67** [Dolibarr/dolibarr#7594]
# Bug
Using the standard template in French to generate a complex (many lines) Expense report I notices that:
 * the type column is to small and cannot fit a text like Transport, Autre or even Repas without a line break
* The column Total TTC is too large
 * Some page break appears at the middle of an expense row

## Environment
- **Version**: 6.01 & 6.02 tested
- **Web server**: OVH
- **PHP**: 7

## [Attached files]
[*Files*]
Largeur colonne
![columnswidth_2017-10-08_110027](https://user-images.githubusercontent.com/32610497/31315444-22282e42-ac19-11e7-96ee-f4d22d399990.png)

Sauts de lignes
![pageberak_1_2017-10-08_110704](https://user-images.githubusercontent.com/32610497/31315443-2225f99c-ac19-11e7-8392-e53640a984ac.png)
![pageberak_2_2017-10-08_110704](https://user-images.githubusercontent.com/32610497/31315446-222ddf72-ac19-11e7-92d7-bc274596e760.png)
![pageberak_3_2017-10-08_110704](https://user-images.githubusercontent.com/32610497/31315445-2229dff8-ac19-11e7-8580-e6f18fb110a1.png)

**Comment by laudeco** [comment]
I had the same issue, already investigated but not found the exact error ...

**Comment by frederic34** [comment]
with module project enabled -> good
without module project -> bad

**Comment by frederic34** [comment]
in /htdocs/core/modules/expensereport/doc/pdf_standard.modules.php
try to replace about lines 115 ... 120
        if (empty($conf->projet->enabled)) {
            $this->posxtva-=20;
            $this->posxup-=20;
            $this->posxqty-=20;
            $this->postotalttc-=20;
        }

with
        if (empty($conf->projet->enabled)) {
            $this->posxtva-=15;
            $this->posxup-=15;
            $this->posxqty-=15;
            $this->postotalttc-=10;
        }

**Comment by steel67** [comment]
Nice catch @frederic34 !

**Comment by steel67** [comment]
Unfortunately it has not been fixed in 6.0.3

**Comment by n15c** [comment]
Same here

**Comment by aljawaid** [comment]
This has been extremely improved in #10064 which I think will be in `v9.0` thanks to @frederic34

**Comment by n15c** [comment]
> 
> 
> This has been extremely improved in #10064 which I think will be in `v9.0` thanks to @frederic34

I just tried the fixed file but still have the same problem. Is there something else i have to change?

**Comment by aljawaid** [comment]
@n15c I had a new expense report created to improve the overrall layout after the @frederic34 patch.... will share it to the forum today or tomorrow https://www.dolibarr.org/forum/index but it is tested for v7 and v8

**Comment by aljawaid** [comment]
@n15c https://www.dolibarr.org/forum/community-templates/28569-theresa-expense-report-pdf-model

**Comment by reivaxm** [comment]
Same in 9.0.3
