### ISSUE TITLE
Feature Request: VAT calculation Method 1 & Method 2 in other documents

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7598]
# Bug
VAT isn't being calculated correctly on Amount (net of tax). Check attached images.
![screenshot-2017-10-9 price requests](https://user-images.githubusercontent.com/23050598/31336496-f363e3fe-acee-11e7-961d-fdb876fb9bae.png)

Here's a screenshot of the configured Limits and Accuracy:
![screenshot-2017-10-9 limits](https://user-images.githubusercontent.com/23050598/31336612-776e3c1c-acef-11e7-8513-862b1234973b.png)

## Environment
- **Version**: develop
- **URL(s)**: /supplier_proposal/card.php

**Comment by mdeweerd** [comment]
Please check if this is the sum of all rounded VAT values?

On invoices one can select Mode 1/Mode 2 to select how VAT is calculated.  There does not seem to be such an option for the supplier_proposal.
It is not very usefull as in the end the supplier will apply his rule "Mode 1" or "Mode 2" and you will be able to match that on the invoice.

**Comment by ruistrecht-alt** [comment]
I've created an Excel and copied the a new dolibarr Price Request into it (check attached images). I've redone all calculations and the results don't add up. All calculated VATs in Excel have the same result 338.80€ which is not the same as Dolibarr (and yes I've updated every line of the price request to force a VAT recalculation)
I think that the problem is in the prices decimals or the rounding of the many calculations.

Excel:
![dolibarr vat math](https://user-images.githubusercontent.com/23050598/31435592-ef452370-ae77-11e7-96b5-f0b2c02aa5ea.png)

Dolibarr Price Request:
![screenshot-2017-10-11 price requests](https://user-images.githubusercontent.com/23050598/31435597-f54d10de-ae77-11e7-9ace-1003b4dba9e1.png)

Dolibarr Limits and Accuracy:
![screenshot-2017-10-11 aliartalentos crm](https://user-images.githubusercontent.com/23050598/31435997-6a65f394-ae79-11e7-813e-af608aa5738e.png)

**Comment by BebZ** [comment]
Did you try adding with 3or4 decimals on excel with no rounding at all ?

**Comment by ruistrecht-alt** [comment]
Like this?

![dolibarr vat math](https://user-images.githubusercontent.com/23050598/31443434-5a8acea0-ae91-11e7-8d8c-3bf887f4e010.png)

You can have a copy of my Excel:
[Dolibarr VAT Math.xlsx](https://github.com/Dolibarr/dolibarr/files/1375768/Dolibarr.VAT.Math.xlsx)

**Comment by ruistrecht-alt** [comment]
And here's another and simpler example with no discount applied to the product/services price:

![screenshot-2017-10-11 price requests 1](https://user-images.githubusercontent.com/23050598/31443654-f4656a4e-ae91-11e7-9aae-da722673ea71.png)

VAT of 481.29€ (23%) should be 110.70€ (110.6967€) it is over by 0.01€

**Comment by ruistrecht-alt** [comment]
OK, now something even stranger happened. I change the rounding Limits and accuracy in Dolibarr to the values shown bellow. Look at what happened to a flat price in one of the product lines.

New Limits and Accuracy:
![screenshot-2017-10-11 aliartalentos crm](https://user-images.githubusercontent.com/23050598/31445848-ebedeb7a-ae96-11e7-8e15-382018c773e3.png)

Same Price request as above:
![screenshot-2017-10-11 price requests](https://user-images.githubusercontent.com/23050598/31445856-eff9b2da-ae96-11e7-8a29-b9c8c1afef86.png)

**Comment by mdeweerd** [comment]
Ragarding you simpler example, the values fit perfectly.
I computed the rounded VAT values in Excel to 2 digits after the decimal point and I summed the rounded values:

Unit price | Units | Total | VAT (23%, rounded)
-- | -- | -- | --
399 | 1 | 399 | 91,77
2,43 | 3 | 7,29 | 1,68
0,71 | 50 | 35,5 | 8,17
0,79 | 50 | 39,5 | 9,09
  |   |   | 110,71


The VAT total is 110.71 as mentionned

**Comment by ruistrecht-alt** [comment]
Yes I know, but there should be a away to allow computation of VAT be over the final amount (Total net) instead of each value.
Many customers only look at the final price and calculate VAT over it (when VAT is equal across the document).
As stated by @mdeweerd and very correctly, the rounded VAT adds up with what Dolibarr calculates.
But as we saw with previous statements, sometimes:
Total amount net * VAT is different from Sum of VAT of all products.

Rounding should be applied to all calculations and results, it should be uniform. To prevent situations like:
2.43 (price) * 0.55 (discount) = 1.3365 (price with discount)
1.3365 * 3 = 4.0095 (final price) -> Not good
1.34 * 3 = 4.02 (final price) -> Good

**Comment by mdeweerd** [comment]
Personnally, I do not agree that rounding has to be applied before multiplication of the value excl. tax.

On the invoices there is Mode 1 and Mode 2 - maybe that just has to be replicated on the supplier request.

Maybe it is already in place if the option parameter is set as explained in the documentation:
https://wiki.dolibarr.org/index.php/VAT_calculation_and_rounding_rules


By not rounding the value before VAT, in case of multiple products the end price should still be the rounded VAT included price.
Then I think that Mode 1 or Mode 2 will be giving the result you want.

However, Mode 1 or Mode 2 may depend on the supplier it the method is not mandatory by tax regulations.

I suggest that you check if the general variable has an influence.  I think that should be the default, but that selecting Mode 1 or Mode 2 should still be possible as it is proposed on other supplier invoices.

**Comment by ruistrecht-alt** [comment]
@mdeweerd Implementing Mode 1 and Mode 2 calculations, on other documents like supplier proposals, would indeed be the best possible solution. This would avoid disparity between the resulting VAT on supplier proposals and on supplier invoices, thus avoiding confusion for the users.
Many suppliers use their own invoice/product managing systems and we cannot guarantee that the method of calculation will be the same one for all.
Another solution could be not calculating VAT on commercial/supplier proposals at all, only calculate for orders and invoices. This is not ideal.

I tried to change MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND to 1, and the value of VAT did not change.
Maybe it isn't influencing the output? Or VAT isn't being recalculated.

Either way this turned out to be a Feature Request.

**Comment by eldy** [comment]
There is 2 method for vat calculation.
Rounding lines then sum, or summing lines then round.
Mode 1 and 2 was introduced on supplier invoice, because you can't know what the supplier has chosed for calculation method.
For for customer invoice, you are the one who decide which method to use. And commonly the method rounding then sum, is the method that is replacing the old method (summing then rouding, often used when using excel but creating a lot of problem when doing accurate accounting on line level). Most computer system/application now provides only the method 1. And because you are the guy that decide how you make your rounding, and because it is better to use always the same method for all your invoices, there is no really need to introduce method 2 for customer invoices (method 2, rouding after the sum, is less ans less used now that everybody are using another software than excel to make their invoices).

**Comment by mdeweerd** [comment]
@eldy - The issue was transformed into a request to add the "Mode 1"/"Mode 2" option also on the "Request for Quote" towards a supplier (supposing that the user knows the method that the supplier uses).

Also, I find myself "correcting" the "Mode 1/Mode 2" method "repeatedly" on supplier invoices for suppliers that do not use the "default method" so it would be nice to be able to set the default method for a supplier.
I believe that OVH is one of them [invoiced that I download using your module :-) ).
