### ISSUE TITLE
Bug: The need/required list is wrong in Technical services provided page

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7604]
## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: admin/modules.php

# Bug
I don't know if this is a bug or a misunderstanding on my part. The need/required list is wrong in Technical services provided page.

## Actual behavior
_In a module descriptor modmymod.class.php:_ 

Case 1. 

```php
//$this->depends = array('thirdparty');
//$this->requiredby = array('factory');
```
_will display in Technical services provided page:_

**This module need the module(s):** None
**This module is required by module(s):** None

Case 2. 
```php
//$this->depends = array('thirdparty');
$this->requiredby = array('factory');
```
**This module need the module(s):** None
**This module is required by module(s):** factory

Case 3. 
```php
$this->depends = array('thirdparty');
//$this->requiredby = array('factory');
```
**This module need the module(s):** None
**This module is required by module(s):** None

Case 4. 
```php
$this->depends = array('thirdparty');
$this->requiredby = array('factory');
```
**This module need the module(s):** thirdparty
**This module is required by module(s):** factory

## Expected behavior
Case 3. 
```php
$this->depends = array('thirdparty');
//$this->requiredby = array('factory');
```
**This module need the module(s):** thirdparty
**This module is required by module(s):** None

Tks!

**Comment by hregis** [comment]
@dolibarr95 
file /admin/modulehelp.php line 368
wrong test : 

`if (count($objMod->requiredby)) $text.=join(',', $objMod->depends);`

change with : 

`if (count($objMod->depends)) $text.=join(',', $objMod->depends);`

**Comment by dolibarr95** [comment]
Tks for this quick reply
I will make the PR know

**Comment by dolibarr95** [comment]
PR done tks.
