### ISSUE TITLE
BUG  The new (?) `Multicurrency_total_ht` and` multicurrency_total_ttc` fields are not populated after updating Dolibarr

### ISSUE THREAD

**Issue by AlainRnet** [Dolibarr/dolibarr#7612]
# Bug
fields multicurrency_total_ht and multicurrency_total_ttc don't have amounts like total and total_ttc after upgrading Dolibarr

## Environment
- **Version**: 6.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.0.24
- **Database**: mysqli (mysqlnd 5.0.12-dev - 20150407) 5.5.5-10.0.27-MariaDB
- **URL(s)**: /compta/facture/card.php?facid=

## Description of the problem :
There seems to be a problem with invoices created before, except for error, switching to v.6 and adding a second field for the amounts.
I have two down payment invoices in CHF and a final invoice also in CHF but created after the Dolibarr update from v.5 to v.6
In the total, the deduction is well taken into account, but not in the PDF. In the invoice lines, Total HT does include the amount of the down payment, whereas Total HT (original currency) is 0. And it is apparently this column that is taken into account to generate the PDF, because the total does not deduct the down payments.

I spotted a similar problem 1 or 2 days ago when the total amount was 0 in the PDF, so I added the amount in the multicurrency_total_ht andmulticurrency_total_ttc fields of the llx_facture table.

I just checked my llx_facturedet table and the lines of the two installments have a total and atotal_ttc but 0 in multicurrency_total_ht andmulticurrency_total_ttc.

**Comment by eldy** [comment]
Can you try with 6.0.2 ?

**Comment by eldy** [comment]
What about if you create a new invoice in a different currency. Does the total is populated ?

**Comment by AlainRnet** [comment]
Est-ce que ce bug est semblable à celui-ci : #7864 ?

**Comment by AlainRnet** [comment]
8.0.3 : le bug semble résolu. Merci!!
