### ISSUE TITLE
Outdated source documentation (doxygen.dolibarr.org)

### ISSUE THREAD

**Issue by FopherC** [Dolibarr/dolibarr#7618]
# Bug
Doxygen documentation shows me dolibarr 5.0.0-rc1 version.
Dolibarr actual version 6.0.2.

## Environment
- **Version**: 5.0.0-rc1
- **URL(s)**: https://doxygen.dolibarr.org

## Expected and actual behavior
I hope to see the documentation updated to the current version (6.0.2). There is outdated information.

## Steps to reproduce the behavior
- Open browser.
- Access to URL: https://doxygen.dolibarr.org

![screenshot from 2017-10-11 15-34-33](https://user-images.githubusercontent.com/1615875/31465486-c069397a-ae99-11e7-9cf8-8459d3468ec2.png)

**Comment by atm-maxime** [comment]
Doc is generated regularily. Thanks for the heads up
