### ISSUE TITLE
Bug: Reference Data upload fail on new install

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#7624]
# Bug
During install, reference data fail to load into some tables.

## Environment
- **Version**: 6.x
- **OS**: Ubuntu 16.04 server
- **Web server**: Apache 2.4.18
- **PHP**: PHP 7.0.22
- **Database**: MySQL 5.7.19
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Expected: During install reference data are loaded.
Actual: Some tables do not load due to SQL errors (Constraints). The following tables are created but empty: llx_c_regions, llx_c_department, llx_c_forme_juridique, llx_c_tva

## Steps to reproduce the behavior
[*Verbose description*]
Install Dolibarr 6.x
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

## Identified problems
when looking at mysqldump_dolibarr_6.0.0.sql, it creates llx_c_pays and llx_c_country
however llx_c_pays is nowhere to be found in the database (when searching for it with phpmyadmin)
and both llx_c_regions and llx_departement seem to depend from llx_c_pays for an foreignl key constraint fails.
nothing found so far for the other two tables.

## Upgrading from Dolibarr 5.x
It seems that the Dolibarr 5.x install process was not impacted by the same problem. Further updates (to higher 5.x or 6.x) do no impact the process. In a 5.x install with updates to 6.x, the llx_c_pays does not exist either (anymore ?)

**Comment by dom-breizh** [comment]
Ok, it would seem the way the install options are used are actually creating the problem.
When reaching the database setup part, you can actually do 2 main things: either create everything from Dolibarr, or if you so choose, use a pre created database and user.
The process works well if you do create everything from Dolibarr.
If you pre create the DB and main user (in MySQL in my case), it fails as described earlier.
I just retested this theory with a clean VM and Dolibarr 6.0.3 and it works as described.
So it kind of works. No a huge bug.

**Comment by d3v2a** [comment]
check the default collation, maybe it's not 'utf8_unicode_ci'
