### ISSUE TITLE
Multi currency / round number between order and invoice

### ISSUE THREAD

**Issue by Meliwine** [Dolibarr/dolibarr#7629]
Good day,

Not sure I will explain well. Let me know if you need more information

# Bug
round number between Order and Invoice are not the same if you use the multi currency

## Environment
- **Version**: Dolibarr 6.0.3 on dolicloud
- **OS**: Windows 10
- **Web server**: Google Chrome
- **PHP**: ?
- **Database**: ?
- **URL(s)**: ?

## Expected and actual behavior
Same prices on Order and invoice but it's not

## Steps to reproduce the behavior
Double currency - 1 € = 420 NGN
Create a product (price in €)
Create an order in NGN 
validate the order : round number is ok
Validate the invoice: no rounding number

**Comment by eldy** [comment]
Can you provide a screenshot of order and invoice that show the difference

**Comment by Meliwine** [comment]
Good day,

I'm sorry I don't have anymore the access of the dolibarr 6.0.3 (it was a
text with dlicloud). Dolicloud should upgrade my professional dolibarr soon
so i will be able to do it again for u.

But you can create again this bug with the explanation I gave, no?

Thank you

--
REFAUVELET Mélissa
m.refauvelet@gmail.com
France: +33(0)6.81.42.22.05

2017-10-22 13:19 GMT+01:00 Laurent Destailleur <notifications@github.com>:
