### ISSUE TITLE
Add automaticly a date of order valid

### ISSUE THREAD

**Issue by amoreira1** [Dolibarr/dolibarr#7631]
Hi All
When we are making an order, i would like that appears automaticly the valid of the order .
For an example: I open today an order and it will de diliver till after 120 days from the actual date .
How can we add this choice to be automaticly?

Thanks

**Comment by BebZ** [comment]
mabe you could first respect some rules of syntax
and also post screenshots or URLs where you want this to appear ?
and then, you will be advised on how to modify it in the core...
