### ISSUE TITLE
Bug: install.lock

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7632]
## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: domain.com/dolibarr/install/

# Bug
...or misunderstanding from me.
As explained here : 
https://wiki.dolibarr.org/index.php/Installation_-_Upgrade

> For security reason, we recommend, once setup is finished, to create a file install.lock into Dolibarr installed directory that only root user can delete. This will lock the call of the install process again (you will have to remove this file for upgrades).

 but the in domain.com/dolibarr/install/inc.php
```php
// Security check
if (preg_match('/install.lock/i',$_SERVER["SCRIPT_FILENAME"]))
{
    print 'Install pages have been disabled for security reason (directory renamed with .lock suffix).';
    if (! empty($dolibarr_main_url_root))
    {
        print 'Click on following link. ';
        print '<a href="'.$dolibarr_main_url_root .'/admin/index.php?mainmenu=home&leftmenu=setup'.(isset($_POST["login"])?'&username='.urlencode($_POST["login"]):'').'">';
        print 'Click here to go to Dolibarr';
        print '</a>';
    }
    exit;
}
```
this checks if the current folder name is not domain.com/dolibarr/install.lock/ (folder)
that is different of domain.com/dolibarr/install/install.lock (file)

So if I : 

- Put this file  domain.com/dolibarr//install/install.lock the security check fails (locks nothing)
- Rename this folder domain.com/dolibarr/install.lock the security goes right (lock everything)

the file check comes later
```php
$lockfile = DOL_DATA_ROOT . '/install.lock';
if (constant('DOL_DATA_ROOT') === null) {
	// We don't have a configuration file yet
	// Try to detect any lockfile in the default documents path
	$lockfile = '../../documents/install.lock';
}
if (@file_exists($lockfile))
{
    print 'Install pages have been disabled for security reason (by lock file install.lock into dolibarr documents directory).<br>';
    if (! empty($dolibarr_main_url_root))
    {
        print 'Click on following link. ';
        print 'If you always reach this page, you must remove install.lock file manually.<br>';
        print '<a href="'.$dolibarr_main_url_root .'/admin/index.php?mainmenu=home&leftmenu=setup'.(isset($_POST["login"])?'&username='.urlencode($_POST["login"]):'').'">';
        print 'Click here to go to Dolibarr';
        print '</a>';
    }
    else
    {
        print 'If you always reach this page, you must remove install.lock file manually.<br>';
    }
    exit;
}
```
And should be stored in DOL_DATA_ROOT wich is different from dolibarr/install directory. This is not mentioned in the wiki or anywhere else.

So please tell me if i should :
- update  the wiki
- make a pr
- read again the wiki beacause, I did not understand
 
Tks.

**Comment by dolibarr95** [comment]
Hi
@eldy can you please give advice.
Tks

**Comment by atm-maxime** [comment]
For as long as I remember, the install.lock file must be in the document folder but this might depend on how you install Dolibarr (deb, zip, doliwamp, ...)

**Comment by dolibarr95** [comment]
Hi tks for reply
I've installed dolibarr under a Listespeed server (just  put all the dolibarr file on my server then install).
But as a write before, the first code checks the file into the current script folder (this check doesn't work for me).
Tks

**Comment by eldy** [comment]
The first check is for old way of working (when we rename the install dir into install.old dir). Just forget it.
The file must be into documents dir and not into install dir.
I have updated the wiki.

**Comment by dolibarr95** [comment]
ok.
Tks a lot
