### ISSUE TITLE
Bug: Column 'lt1' cannot be null

### ISSUE THREAD

**Issue by KLINPC** [Dolibarr/dolibarr#7648]
# Bug

## Environment
- **Version**: 6.0.2
- **OS**: Darwin
- **Web server**: Apache/2.4.25 (Unix) PHP/7.0.16 mod_wsgi/4.5.11 Python/3.6 OpenSSL/1.0.1p
- **PHP**: apache2handler 7.0.16
- **Database**: MySQL or MariaDB 5.6.36
- **URL**: /dolibarr/fourn/facture/card.php?id=398

## Report
Products and services for New Caledonia suppliers, have only one tax in their buy price, but drop-down tax list for sell price. 
In supplier invoice, cannot change the wrong tax for service or product due to error "Column 'lt1' cannot be null"
![achat](https://user-images.githubusercontent.com/26755005/31650326-95009238-b362-11e7-9a42-71c8e8debb27.png)
![vente](https://user-images.githubusercontent.com/26755005/31650330-9b5d0cf6-b362-11e7-8242-496dc3c3d883.png)

**Comment by eldy** [comment]
Are you sure that column name in message is "lt1" ?
