### ISSUE TITLE
Payment terms editing not allowed

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#7653]
# Bug
This is a resume of the closed issue #7523. The DB syntax error has been corrected in the version 6.0.2, but editing of Payment Terms (in Home/Setup/Dictionaries) is still not permitted. 
Now it's possible to add new "payment terms" without DB syntax errors but it's still not possible to edit and modify existing terms because fields "label" and "label on documents" look constrained by an available translation. When trying to save the modified record (also without any change), a warning appears saying that the two above mentioned fields are required and it's not possible to apply any change.

## Environment
- **Version**: 6.0.2
- **OS**: Linux 3.10.102 #15152 SMP Fri Oct 6 18:13:57 CST 2017 x86_64
- **Web server**: Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141
- **PHP**: 5.6.31
- **Database**: MariaDB 5.5.57
- **URL(s)**: /dolibarr/htdocs/admin/dict.php?id=12

## Expected and actual behavior
Expecting to modify current records (e.g. the sort order).
Any change is not allowed.

**Comment by eldy** [comment]
Seems fixed for 6.0.3 as i can't reproduce it.
