### ISSUE TITLE
Extrafields - Can't transfer same extrafields from propal to contract

### ISSUE THREAD

**Issue by code42fr** [Dolibarr/dolibarr#7657]
# Bug
I try to make cross(spend) additional attributes between a commercial proposal and a contract and unfortunately nothing passes. Between a proposal and a customer command(order), everything is OK but nothing aimed at(bound for) a contract.

## Environment
- **Version**: Dolibarr 3.9.x & 4.0.x
- **OS**: DEBIAN 7,8 & Mac OS
- **Web server**: APACHE 2.2
- **PHP**: 5.4 & 5.6
- **Database**: MYSQL 5.6

**Comment by atm-maxime** [comment]
New feature comming with #7822
