### ISSUE TITLE
WYSIWYG editor - bug with permissions

### ISSUE THREAD

**Issue by henryseron** [Dolibarr/dolibarr#7658]
# Bug
When the WYSIWYG editor module is activated, the users are unable to modify their own information. Below you will find an screenshot of the error message.
If the module keeps inactive there is no problem. By the way, I am admin user.

## Environment
- **Version**: 6.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.30
- **Database**: MariaDB 5.6.28-76.1
- **URL(s)**: /user/card.php?id=1

## Steps to reproduce the behavior
Activate the module WYSIWYG editor in the Modules Setup and try to modify the user information. I wanted to modify my signature and got the error.

## Screenshot
![image](https://cloud.githubusercontent.com/assets/11153444/25814175/7d18507c-33ea-11e7-84fd-2ac27cd03425.png)

**Comment by simnandez** [comment]
I thinks this it no a dolibarr bug, It is a message of your server hosting. 
You should talk to your hosting provider to find out what is the security rule.

**Comment by henryseron** [comment]
It is not a hosting issue due to I manage my own server.

**Comment by eldy** [comment]
The error message is not a message coming from Dolibarr.
You probably have an apache setup or an apache module that must be tuned to avoid this filtering.
Don't you have more information into your apache error log ?
