### ISSUE TITLE
SQL Error when installing

### ISSUE THREAD

**Issue by novafragger** [Dolibarr/dolibarr#7659]
# Bug
SQL Error DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'smallint DEFAULT 0,	active tinyint DEFAULT 1 NOT NULL, )ENGI' at line 11

**Comment by atm-maxime** [comment]
Please add the Dolibarr version, a screenshot or anything that can help find the issue
