### ISSUE TITLE
FEATURE REQUEST: Calculation of landed cost

### ISSUE THREAD

**Issue by cperrot** [Dolibarr/dolibarr#7666]
# Feature Request
It would be great if the landed cost could be integrated as this is a functionality most ERP system provide.

**Comment by BebZ** [comment]
did you succeed in making an appropriate specification's sheet and explain deeply what you meant ?
Thanks

**Comment by cperrot** [comment]
This video explains pretty much what landed costs should do.
http://www.bluelinkerp.com/landed-cost-tracking-software/

It should be a separate module which calculates the distributed landed costs on each item based on type of landed costs.

The landed cost includes:
    The weighted average input price of the product (already present in Dolibarr)
    All transportation fees
    Customs
    Duties
    Tax
    Insurance
    Currency conversion
    Crating
    Handling
    Payment fees and any other costs outside our direct inventory purchase cost.

The rules to distribute the landed costs can be manifold:
e.g. Weight, percentage of prices, per item or a manual allocation

Average landed costs should be aligned with the weighted average input stock price of each item. In Dolibarr's case FIFO weighted average.

Since many invoices related to one shipment of goods can come in from different service providers such as transport, duty and insurance, these additional supplier invoices should be able to be assigned to existing goods supplier invoice as landed costs and then distributed as per the active distribution rules as landed cost.

If you need more help writing a specification let me know. I am interested in getting this feature implemented.

Cheers 
Cedric

**Comment by BebZ** [comment]
Hello, it should be the goal of a separate module, don't you think

i remember there was a specific field for additional costs, but as you wish to link lines from supplier orders / forwarder's invoices, etc... i don't think it could be sufficient.

Do you have any budget / time frame to set it up ? 
(i'm not a developper nor a company selling development, but can see with crowd funding and specifications for dolibarr fields / objects...) I know Dolibarr deeply and try to add more specifications to it / for me / the community

**Comment by cperrot** [comment]
Hi
It should most definitely be a separate module. 
It looks like someone was already anticipating some sort of extra costs with the additional costs field, however, the field leaves every user for themselves to calculate and distribute the landed costs on their own. 

As per budget and time frame, I have none. 
I am a developer and business advisor but new to Dolibarr, I find Dolibarr to be one of the most intuitive open source ERP on the market. I'd be happy to invest some time and effort into specifying and developing this module.

It is my strong belief that every ERP should have a good landed cost module as this is the foundation of every margin and price calculation. From a business perspective you cannot calculate your product price properly when the business has no or little idea about landed cost per SKU.
I am open to any approach be it crowd funding, community effort and otherwise.

**Comment by cperrot** [comment]
I find it terrible that an important topic such as this for an ERP is stale. 
How is everyone calculating landed costs?

**Comment by atm-maxime** [comment]
The issue is stale because nothing happened on it since 1 year. This doesn't mean it's not interesting or will not be done, just that for now no one in the community started a work on it.

**Comment by atm-maxime** [comment]
You can reopen the issue of course !

**Comment by farizno** [comment]
For me this is extremely important. I dont understand how Dolibarr can have so many great features but is missing this. This is very important in order to calculate actual cost of an item, profit margins, sale prices, commissions, etc. By not having this feature, I am afraid I will not be able to use Dolibarr effectively. How can you know the true cost of an item without being able to calculate landed cost?

**Comment by peterromao** [comment]
I do restate the importance of such a document and I do think that what @farizno mentioned previously is right on spot.
>How can you know the true cost of an item without being able to calculate landed cost?

If you want to know a bit more how other erp's do this take [this example](https://help.sap.com/doc/saphelp_sbo900/9.0/en-US/45/07dde4cc1a2462e10000000a1553f7/content.htm?loaded_from_frameset=true).

**Comment by cperrot** [comment]
I do second that. Flabbergasted that nothing is happening on this front.

**Comment by Kinsodsol** [comment]
Is there any updated on this?
