### ISSUE TITLE
Feature Request : Name of invoice when they are Draft (instead of "Prov....")

### ISSUE THREAD

**Issue by mistraloz** [Dolibarr/dolibarr#7669]
# Feature Request
![selection_001](https://user-images.githubusercontent.com/2956113/31816106-417a458a-b58f-11e7-850a-77e4a28279a0.png)

I propose to replace in the page "Compta / Tréso" the indication of the temporary number of the invoice by the name given for this invoice. And the same for supplier and customer invoices.
Finding an invoice from database ID does not really usefull until the final number has been assigned.
I can do the resquest pull of the feature once agree on how to implement it. Eventually, for backward compatibility, I can keep the information "(PROV240)" in front of the name. In addition, to keep the interface compact, I can display only the first X characters.
What do you think about ?

Same, in french :

Je propose de remplacer dans le tableau "Compta/Tréso" l'indication du numéro temporaire de la facture par le nom donné pour cette facture. Que ce soit pour les factures fournisseur ou client. 
Retrouver une facture à partir de son ID en base n'a pas vraiment d'intérêt tant que le numéro définitif n'a pas été attribué. 
Je peux faire le pull resquest de la fonctionnalité une fois d'accord sur la manière de l'implémenter. Eventuellement, pour la rétrocompatibilité, je peux maintenir l'information "(PROV240)" devant le nom. De plus, pour garder l'interface compacte, je peux n'afficher que les X premiers caractères. 
Qu'en pensez-vous ?

**Comment by eldy** [comment]
You speak about "name of invoice", but currently, except for supplier invoices, there is no "Label".
We can add suche a field like in supplier invoice, but it must not be mandatory (most users won't need it).

**Comment by mistraloz** [comment]
Ok, i would like add informations (ref_supplier/client, and labelle) in name of link... but it too difficult for the moment. So, i have just add informations on the tooltip, and without the labelle (just ref_client/supplier, if provided). 

For the moment, i think is more retrocompatible for all users.
