### ISSUE TITLE
Bug: erreur lors de la création d'un nouvel utilisateur

### ISSUE THREAD

**Issue by Gerber-Francois** [Dolibarr/dolibarr#7672]
![2017-10-20 12_26_02-contacts_adresses](https://user-images.githubusercontent.com/32956209/31819083-52db9d7c-b59b-11e7-8906-93439fed5c4a.jpg)
![2017-10-20 12_26_39-test](https://user-images.githubusercontent.com/32956209/31819096-5a1e2096-b59b-11e7-8138-939d83faf87a.jpg)

# Bug

## Environment
- **Version**: 6.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.23 (Win64) PHP/5.6.25
- **PHP**: apache2handler 5.6.25
- **Database**: MySQL or MariaDB 5.7.14
- **URL**: /dolibarrgip/htdocs/contact/card.php?id=435

## Report
erreur lors de la création d'un nouvel utilisateur depuis la nouvelle version après mise à jour

**Comment by dolibarr95** [comment]
Hi
Have you tested with ne user name : ```letest``` instead of ```le.test``` ?

**Comment by eldy** [comment]
I can't reproduce, can you try to disable all external modules and tel if you still have error when creating without external modules ?
