### ISSUE TITLE
Text Box Pulldown Page Load Delay - Scalability with 100,000 Third Parties

### ISSUE THREAD

**Issue by cleverthings** [Dolibarr/dolibarr#7674]
# Bug
As my Dolibarr installation is getting up to around 100,000 Third Parties, the pull down text selection boxes loading time is starting to slow down page load times significantly. 

## Environment
- **Version**: Dolibarr 6.0.2
- **OS**:  Linux 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64
- **Web server**: Apache
- **PHP**:  7.0.22-0ubuntu0.17.04.1
- **Database**: MySQL or MariaDB 5.7.19-0ubuntu0.17.04.1 and mysqli (mysqlnd 5.0.12-dev)
- **URL(s)**: Projects -> List -> Click on Project -> Modify -> Third Party

## Expected and actual behavior
I'd expect all pages to load within a few seconds, regardless of size of database. I'm using for hosting a Google Cloud instance n1-standard-2 (2 vCPUs, 7.5 GB memory) and my CPU utilization is quite low, no latency between database server and web server.  When I drop below 50,000 records the performance is quite reasonable. The more records I add, the slower the dropdown box loads affecting page load times. 

## Steps to reproduce the behavior
Load the system with test data for large number of records.  An example would be if I go into Projects and try to Create or Modify a Project. When the page tries to load the pulldown text menu for Third Party it tries to load all of the records in the system. The more records you add, the more probability of page timeouts and end user frustration.

**Comment by frederic34** [comment]
Hello
Did you activate "ajax search" in thirdparty module (at the bottom of the page)

**Comment by simnandez** [comment]
This is not a bug. You must configure Dolibarr if you have a large number of records.
Use the option "Wait you press a key before loading content of product combo list (This may increase performance if you have a large number of products, but it is less convenient)" of the products module.

And for have a great perfomance,  you can use the hidden option PRODUCT_DONOTSEARCH_ANYWHERE

**Comment by cleverthings** [comment]
No,  I honestly missed that setting. That is EXACTLY what I was looking for, so I apologize for creating a bug report for this. It was my mistake, I should have caught that misconfiguration.  I'll close this, but just want to say a big THANK YOU to all of the hard-working Dolibarr developers. I've been using I think since v4 and I know how much love and hard work you put into this project. THANK YOU for all that you do!
