### ISSUE TITLE
Upgrade 5.0.4 ⇒ 6.02

### ISSUE THREAD

**Issue by microniko** [Dolibarr/dolibarr#7678]
I'm trying to upgrade Doliobarr to 6.0.2 but having this error :

> Request 227 sql='ALTER TABLE llx_mailing_cibles MODIFY COLUMN source_url varchar(255);'
> Request 228 sql='CREATE TRIGGER  update_customer_modtime BEFORE UPDATE ON llx_website FOR EACH ROW  EXECUTE PROCEDURE update_modified_column_tms();'
> Erreur  DB_ERROR_42883: CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON  llx_website FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();ERREUR:  42883: la fonction update_modified_column_tms() n'existe pas LOCATION:  LookupFuncName, parse_func.c:1925
> Request 229 sql='CREATE TRIGGER  update_customer_modtime BEFORE UPDATE ON llx_website_page FOR EACH ROW  EXECUTE PROCEDURE update_modified_column_tms();'
> Erreur  DB_ERROR_42883: CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON  llx_website_page FOR EACH ROW EXECUTE PROCEDURE  update_modified_column_tms();ERREUR:  42883: la fonction update_modified_column_tms() n'existe pas LOCATION:  LookupFuncName, parse_func.c:1925
> Request 230 sql='insert into  llx_c_tva(rowid,fk_pays,code,taux,localtax1,localtax1_type,localtax2,localtax2_type,recuperableonly,note,active)  values (1178, 117, 'C+S-5',   0, 2.5, '1', 2.5, '1', 0, 'CGST+SGST -  Same state sales', 1);'

I'm using PostgreSQL 9.6.4…

Dolibarr seems work fine but I don't test all functionalities…

**Comment by eldy** [comment]
The execution of file  
function  pgsql/functions/functions.sql probably failed during the first install.
Try to run it manually. Or the field "date of last update" will not be updated correctly in your tables with no other effect.

**Comment by microniko** [comment]
Run the file `functions.sql` has worked.
But with an error :
> psql:/tmp/functions.sql:30: ERREUR:  la fonction date_format(timestamp with time zone, text) n'existe pas

Run it again doesn't show this error (but triggers already exists).

**Comment by pitchum** [comment]
I had the same error in migration script 5.0.0 -> 6.0.0 while upgrading from 3.5.5 (package from Debian jessie).

I wonder how function `update_modified_column_tms` did disappear.
That function was introduced in dolibarr 3.3.0 (cf. dbe00e9fbd9).

@eldy from what I understand `functions.sql` is only executed on a fresh install. Assuming this script is idempotent would it be possible to also run it when starting an upgrade?
