### ISSUE TITLE
Feature Request: Allow external users to see product with "List products" permission.

### ISSUE THREAD

**Issue by suryacaprice** [Dolibarr/dolibarr#7697]
1. login as external user
2 see that product search box
3) If external user is a supplier . all the products supplied by them should be seen with the stock limits

**Comment by eldy** [comment]
Currently there is a protection that disable all the module "product" to external.
Hower, there is a bug in v6 that let use see the box or products even if external user.
I fixed this for consistency in v7.

We can make product module visible for external user by adding a constant MAIN_MODULES_FOR_EXTERNAL with list of all modules allowed to external users
By default it is 'user,societe,propal,commande,facture,categorie,supplierproposal,fournisseur,contact,projet,contrat,ficheinter,expedition,agenda,resource,adherent'
But we can set it to
'product,service,stock,user,societe,propal,commande,facture,categorie,supplierproposal,fournisseur,contact,projet,contrat,ficheinter,expedition,agenda,resource,adherent'

But it means that user will see all products if he has permission.
Having restriction if product is supplied by company is possible but there is currently nothing to make a difference between i want to give the external user ability to see the product and ability to see only if product has a supplier price for external user.
