### ISSUE TITLE
Bug : unable to create multiple invoices with "Invoice template" functionnality

### ISSUE THREAD

**Issue by oas-services** [Dolibarr/dolibarr#7709]
# Bug
[*When i want to create 3 invoices from one standard invoice, i had the following error message : Unkown column 'vat_scr_code' in field list*]

## Environment
- **Version**: [*6.0.2 newly installed*]
- **OS**: [*Linux Debian 9*]
- **Web server**: [*Apache 2 webserver*]
- **PHP**: [*PHP 7*]
- **Database**: [*Mariadb*]
- **URL(s)**: [*/compta/facture/fiche-rec.php*]

## Expected and actual behavior
[*When i want to create 3 invoices from one standard invoice, i had the following error message : Unkown column 'vat_scr_code' in field list instead of having my 3 invoices being generated.*]

## Steps to reproduce the behavior
[*Verbose description*]

**Comment by atm-maxime** [comment]
I can't reproduce, I think this has been fixed, do you still have the issue ?
