### ISSUE TITLE
Warning: Class 'Luracast\Restler\mixed' not found error in Dolibarr 6

### ISSUE THREAD

**Issue by ahmadbadpey** [Dolibarr/dolibarr#7710]
First I activated API module in dolibarr. 

Then to use API I got a token via `http://dolibarr.dev/api/index.php/login?login=zarsam&password=myPass` url and all things was successful hitherto.

But when go to `http://dolibarr.dev/api/index.php/explorer` to see API I got this error about 5 times: 

`Warning: Class 'Luracast\Restler\mixed' not found in D:\wamp\www\dolibarr\htdocs\includes\restler\framework\Luracast\Restler\AutoLoader.php on line <i>307</i>` 

I'm using **php 7.0.10** first and then switch to **5.6.25** but no things is changed.

**Comment by eldy** [comment]
Can you check that into file AutoLoader.php, you have the line

        if ($className == 'Luracast\Restler\mixed') return;
