### ISSUE TITLE
Products & Services search only returns products

### ISSUE THREAD

**Issue by hameau** [Dolibarr/dolibarr#7714]
# Bug
Products & Services search only returns products.

## Environment
- **Version**: 6.0.2
- **OS**: - public demo : demo.dolibarr.org -
- **Web server**: - public demo -
- **PHP**: - public demo -
- **Database**: - public demo -
- **URL(s)**: /product/list.php?sall=test (example result page)

## Expected and actual behavior
Expected:
Searching using the global Search box, top of the left column (Eldy theme), should return result from both Products and Services.

Actual:
Search only returns results of type Product, does not include Services, even when there are services that fit the search criteria.

## Steps to reproduce the behavior
Example for demo.dolibarr.org.
* From any page, type the word 'test' in the Search box.
* From the list of search targets, select 'Products or Services'.
* The search result page(s) only show search results of type Product, even when there are services that fit the search criteria.

For comparison, starting with a list of services.
* Select the Products|Services top-level menu option.
* In the left column, select Services->List.
* Type the word 'test' in the search box above the Label column; press Enter or click the search icon.

It can be seen that there are services that include 'test' in the label text, but these are not found by the global search feature.

**Comment by hameau** [comment]
It seems that the call to ```/product/list.php``` should have ```&type=-1``` appended.

For the global search test described above for demo.dolibarr.org, if I manually edit the results list page url to ```/product/list.php?sall=test&type=-1```, I get the search results expected (results show products and services).

**Comment by hurricane66750** [comment]
I have the same result, can you take into account this request for correction please.

**Comment by atm-maxime** [comment]
Hello,

Thanks for the feedback. It has been fixed in #7758
