### ISSUE TITLE
Bug: Cannot delete product after having Qty Prices

### ISSUE THREAD

**Issue by cperrot** [Dolibarr/dolibarr#7716]
# Bug
[*Short description*]

## Environment
- **Version**: [6.0.2]
- **OS**: [*Ubuntu 16.04*]
- **Web server**: [*Apache 2.4*]
- **PHP**: [7.0.22-0ubuntu0.16.04.1]
- **Database**: [5.7.20-0ubuntu0.16.04.1]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Cannot delete product due to DB constraints with price by qty.

## Steps to reproduce the behavior
Activated Qty pricing on product then added a few prices and tried to delete the product with following result.

Cannot delete or update a parent row: a foreign key constraint fails (`dolibarr`.`llx_product_price_by_qty`, CONSTRAINT `fk_product_price_by_qty_fk_product_price` FOREIGN KEY (`fk_product_price`) REFERENCES `llx_product_price` (`rowid`))

**Comment by atm-maxime** [comment]
Can you explain how do you activate price by qty in 6.0 ?
Officially there's 3 pricing options : simple price, price by level and price by customer.
Price by quantity is perhaps a hidden feature. In this case, this is a develop issue.

**Comment by cperrot** [comment]
check out my forum entry https://www.dolibarr.org/forum/12-howto-help/24397-how-to-activate-price-by-qty-in-dolibarr

**Comment by atm-maxime** [comment]
Price by quantity is not a finished feature.
Too old version, please upgrade and reopen if needed.
