### ISSUE TITLE
[Bug] Credit note not reimbursable

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#7720]
# Bug
Supplier credit note not reimbursable.

## Expected and actual behavior
Should be able to reimburse credit note.

## Steps to reproduce the behavior
- I created and validated a credit note on a supplier account ("Facture account") that I attached to a random old invoice (I could not create the credit note without an invoice).
- The button to Pay back the credit note ("Remboursement") is not functionnal.

**Comment by atm-maxime** [comment]
The credit note for supplier invoices is not functionnal in 6.0 (I'm guessing you in the 6.0 version). This is an experimental feature. For the moment you should create a standard supplier invoice with a negative amount to make it work.

**Comment by mdeweerd** [comment]
The function is available in the demo (https://demo.dolibarr.org/fourn/facture/card.php?facid=267 ):
![image](https://user-images.githubusercontent.com/1504752/32972294-d8b51268-cbf1-11e7-9643-d5246c4d8042.png)

After that, I created the following invoice:
https://demo.dolibarr.org/fourn/facture/card.php?id=529

Which resulted in an error:
```
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20171117235235
Dolibarr: 6.0.2
Niveau de fonctionnalités: 0
PHP: 5.3.10-1ubuntu3.25
Server: Apache/2.2.22 (Ubuntu)
OS: Linux vmprod 2.6.32-19-pve #1 SMP Wed May 15 07:32:52 CEST 2013 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Url sollicitée: /fourn/facture/card.php?id=529&action=confirm_valid&confirm=yes
Referer: https://demo.dolibarr.org/fourn/facture/card.php?id=529&action=valid
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur

Message: Error generating document for CommonObject. Error: Impossible de créer le répertoire /home/dolibarr/demo.dolibarr.org/dolibarr_documents/fournisseur/facture/9/2/SI1711-0178
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20171117235235
Dolibarr: 6.0.2
Niveau de fonctionnalités: 0
PHP: 5.3.10-1ubuntu3.25
Server: Apache/2.2.22 (Ubuntu)
OS: Linux vmprod 2.6.32-19-pve #1 SMP Wed May 15 07:32:52 CEST 2013 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Url sollicitée: /fourn/facture/card.php?id=529&action=confirm_valid&confirm=yes
Referer: https://demo.dolibarr.org/fourn/facture/card.php?id=529&action=valid
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur
```
Apparently the invoice directory could not be created.

Then I clicked to pay the invoice (https://demo.dolibarr.org/frn/facture/card.php?facid=529 ).

The reimbursment of the standard invoice worked.

I understand that an actual credit note is a future feature.
