### ISSUE TITLE
Unable to import Products & Third Parties 6.0.2 from 6.0.0

### ISSUE THREAD

**Issue by sanjiiiv** [Dolibarr/dolibarr#7724]
<img width="775" alt="screenshot1" src="https://user-images.githubusercontent.com/31779307/32103951-14ab03f8-bb40-11e7-9c82-a6d13203ec9e.PNG">

Please check the bug and update.

**Comment by atm-maxime** [comment]
The error occurs on line 1. I guess your line 1 contains the columns headers. So it's normal that the value "Creation date" is not importable in a date field. You must tell the import process to start at line 2.
