### ISSUE TITLE
Bug: Stock is increased twice against a Supplier invoice.

### ISSUE THREAD

**Issue by mudassar791** [Dolibarr/dolibarr#7729]
![invoice](https://user-images.githubusercontent.com/32223328/32136468-305a9414-bbc3-11e7-9f04-993350f4234a.png)
# Bug

## Environment
- **Version**: 6.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/product/stock/mouvement.php?idproduct=25

**Comment by mudassar791** [comment]
Again found it in a invoice,any body here who did face it?

**Comment by mudassar791** [comment]
any body here?

**Comment by atm-maxime** [comment]
Hello,

I can't reproduce the issue in 6.0.4. When I reopen the supplier invoice, the system asks a warehouse to decrease the stock. And when I validate again it increases again, but it's correct because there was a decrease before.
