### ISSUE TITLE
Remove added items from category page product dropdown

### ISSUE THREAD

**Issue by lampi87** [Dolibarr/dolibarr#7730]
# Feature Request
On category page it is possible to add products to one category. But the list contains all products including already added ones. On adding an already added product, an error is shown.

## Suggested implementation
Already added elements should be removed from list. This will increase user experience and reduce effort to find not added products.

**Comment by ATM-Marc** [comment]
Hello,

I'm working on this feature.

Best regards,
Marc.

**Comment by atm-arnaud** [comment]
Hello,

I fixed your request in develop branch. The code was already proposed but not working. This feature will be able in the next version : 8.0.

Regards,
