### ISSUE TITLE
Issue: Income Statement and balance sheet.

### ISSUE THREAD

**Issue by mudassar791** [Dolibarr/dolibarr#7731]
# Issue: Income Statement and balance sheet.

## Environment
- **Version**: 6.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/

## Report
In finance, there is no proper report for Income Statement and balance sheet.
I have sql queries to find it from database, but i dont know how to use them in php.
Can any body here?

**Comment by eldy** [comment]
What do you mean "no poper report"
Can you describe exactly what wrong ?  Screenshots are welcome
