### ISSUE TITLE
Fatal error in commonobject.class.php (6.0.3)

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#7733]
# Bug
Fatal error: Uncaught Error: Cannot access empty property in /[…]/core/class/commonobject.class.php:2673 Stack trace: #0 /[…]/core/class/html.form.class.php(5506): CommonObject->fetchObjectLinked() #1 /[…]/fourn/facture/card.php(2858): Form->showLinkedObjectBlock(Object(FactureFournisseur), '\n \t\t<dl clas...') #2 {main} thrown in /[…]/core/class/commonobject.class.php on line 2673

## Expected and actual behavior
After upgrading from 6.0.2 to 6.0.3

## Steps to reproduce the behavior
Supplier -> Settle purchase orders
Select and confirm several purchase orders

**Comment by eldy** [comment]
Can you provide more information on how to reproduce the pb.
When you say "Supplier -> Settle purchase orders". Which menu are you taking about ?

**Comment by sbschumacher** [comment]
Hi eldy,

I will try to explain how to reproduce the error:

Please choose a supplier and create a new supplier order and then set this supplier order as "completely received".

Afterwards you can try to reproduce the bug:

1. Open the Third party page of an supplier
2. Click on "Supplier"
3. Scroll down and click on the "Bill orders"-button
4. Then choose one or more of the orders on the page "List of supplier orders - Products received" and click on "Generate invoice"
5. On the "New invoice" page guess a "Ref. supplier" number and click on "Create draft"

Now you can already see the first error message below the "Linked files" section:
<img width="1062" alt="1" src="https://user-images.githubusercontent.com/14094327/32468387-56af7fca-c34e-11e7-9482-983af028ab1e.png">

6. Now you can validate the supplier invoice by clicking on "Validate" and then "Yes" in the pop-up window.

After clicking on "Yes" there is a "full page" error message:
<img width="1250" alt="2" src="https://user-images.githubusercontent.com/14094327/32468548-00c61474-c34f-11e7-9ca6-d5a274e50153.png">

The only way to proceed is the "go back"-button of the internet browser. Then the Supplier invoice page will be displayed, showing still the "validate invoice"-popup but already a valid reference number instead of "Draft". After closing this pop-up with a click on the "x" at the right corner, you can proceed as usual, despite of the error message, which is still present below the "Linkes files"-section.

**Comment by BebZ** [comment]
Bill orders of supplier is not a function of dolibarr core i guess since 6.0
"List of supplier orders - Products received" especially this one,  may be an ATM module ?

**Comment by sbschumacher** [comment]
```
/**
 * \file htdocs/fourn/commande/orderstoinvoice.php
 * \ingroup commande
 * \brief Page to invoice multiple supplier orders
 */
```

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
