### ISSUE TITLE
Feature Request: Avoid user to access another bank account

### ISSUE THREAD

**Issue by julien-garrigue** [Dolibarr/dolibarr#7734]
# Feature Request
To be able to give access to a specific bank account at a specific user or group of users

## Use case
In the framework of an organisation which needs a financial representative for the entry of funds (donations, memberships), the representative is completely independent of the association and does not have to be a member, he also has his own bank account to receive all the funds.

He must be able to enter each amount received (or validate it in the case of a CB payment), validate the membership of the member who has paid and validate the donations or even any other form of funding received for the association. Then make a transfer of all the money from his account to the organisation's account.

It is therefore necessary to partition the access to the bank account of the organisation from the Mandatory User and vice versa.

There are also some similar requests here in French:
https://www.dolibarr.fr/forum/12-howto--aide/55740-empecher-un-utilisateur-de-voir-d-autres-comptes#89346
https://www.dolibarr.fr/forum/11-suggestionsnouvelles-fonctionnalites/60181-module-mandataire-financier#89361

## Suggested implementation
2 suggestions:

In the users / groups rights
/user/group/perms.php
/user/perms.php

Or in a module 

## Suggested steps
In "Banks and cash" select in a list, to which account the rights are applied

**Comment by julien-garrigue** [comment]
up

**Comment by aljawaid** [comment]
This would be perfect but it seems like demand is low in the community.
