### ISSUE TITLE
 Mise à jour 6.0.3 impossible valider factures Fournisseur

### ISSUE THREAD

**Issue by hugo49** [Dolibarr/dolibarr#7736]
Bonjour,

je viens de passer à la version à la version dolibarr 6.0.3
je viens de m'apercevoir qu'il est impossible de valider les factures fournisseurs.

Voici le message.Cette page ne fonctionne pas. Impossible de traiter cette demande via ******.fr à l'heure actuelle.HTTP ERROR 500

Merci de votre aide.

## Environment
- **Version**: [6.0.3] 
- **OS**: [*ubuntu 16*]
- WebServeur:Apache/2.4.18 (Ubuntu)
- **PHP**: [*7.0.22-0ubuntu0.16.04.1*]
- **Database**: [*Database type and version*]
- **URL(s)**: tiers et factures fournisseurs

UserAgent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
-- | --
Nom du navigateur | chrome
OS du navigateur | windows
Version | 62.0.3202.62
Présentation (phone/tablet/classic) | classic

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by hugo49** [comment]
[dolibarr (1).log](https://github.com/Dolibarr/dolibarr/files/1427831/dolibarr.1.log)

**Comment by atm-arnaud** [comment]
Bonjour,

Pouvez-vous modifier vos log dolibarr en ne sauvegardant que les erreurs ?
Apparement, il n'y aurait pas d'erreurs dans le fichier transmis. Avez-vous essayez de désactiver, réactiver les modules suivants : 
- Société
- Fournisseurs

En regardant la date de votre dernier commentaire, je pense que ce problème est désormais résolu, mais pouvez-vous nous éclairer sur les modalités de résolution ?

Cordialement,

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
