### ISSUE TITLE
Dont save the data of the extrafields of expense report

### ISSUE THREAD

**Issue by nanoxp** [Dolibarr/dolibarr#7737]
# Bug
Dont save the data of the extrafields of expense report

## Environment
- **Version**: [5.0.4 to 6.0.3]
- **OS**: [*ubuntu 16.04*]
- **Web server**: [*Apache*]
- **PHP**: [*PHP version 7]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

I did the next actions to get the error:

1. I click in the option New (Expense Report)
2. I write the information that I need it, including the extrafields (../expensereport/card.php)
3. When I click in the button Create expense report the information that I had written in the extrafields, it lost. In another words, the information of extrafields of that expense report didn't save in that step.
4. In the detail of the expense report when wanting to modify the second or third extrafields, the previous ones are deleted

**Comment by dolibarr95** [comment]
@eldy
## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**:

Hi i've try this fix but still doesn't work for me. Only store the current extrafield the other ones are lost.
Tks

@nanoxp does this fix work for you ?

**Comment by dolibarr95** [comment]
@eldy 
Hi i've try this fix but still doesn't work for me.
Tks for your help.
