### ISSUE TITLE
Can't add links to microsoft.com in the documentation wiki

### ISSUE THREAD

**Issue by MagicFab** [Dolibarr/dolibarr#7744]
The wiki documentation needs an update indicating a required Windows component to be installed.

I tried to add this to [this page](https://wiki.dolibarr.org/index.php?title=Prerequisite):

```
== Windows 7 ==

When using Windows 7 the  Visual C++ Redistributable for Visual Studio 2012 Update 4 must be already installed. It can be obtained here:

* https://www.microsoft.com/en-us/download/details.aspx?id=30679
```

The wiki blocks this edit with this message:

> **Spam protection filter**
> 
> The text you wanted to save was blocked by the spam filter. This is probably caused by a link to a blacklisted external site.
> 
> The following text is what triggered our spam filter: https://www.microsoft.com 

Please remove this filter so this kind of information can be added. AFAIK anonymous edits aren't allowed so I trust other editors to be accepted on their understanding and values, not to spam with unneeded Microsoft.com links.

**Comment by eldy** [comment]
domain has been added into the white list
