### ISSUE TITLE
multicurrency internal transfer error

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#7756]
# Bug
When I need make internal transfer between bank account with different currencies next error appear:
"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the syntax to use near ''1',null,'1','VIR',null,null,0,'')' at line 1"

## Environment
- **Version**: 6.0.3
- **OS**: Linux us-imm-web16.main-hosting.eu 2.6.32-673.26.1.lve1.4.30.el6.x86_64 #1 SMP Wed Jun 21 19:37:37 EDT 2017 x86_64
- **Web server**: Apache 
- **PHP**: 5.6.31
- **Database**: MySQL or MariaDB 10.1.25-MariaDB
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
It is expected that when transfers are made between bank accounts of different currencies, they are made by converting currencies so that in the bank account of orgien the withdrawal appears in its currency and in the deposit account it appears the same but in its converted currency at your exchange rate. Currently when trying to make the movement the error already described occurs.

## Steps to reproduce the behavior
In the section of "Banks" -> internal transfer I select a bank account that I have registered in USD currency in the "From" part and in the "Towards" part I select a bank account that has a MXN currency. I fill in the data that asks me for a description, date and amount.

## [Attached files]![2017-11-02 1](https://user-images.githubusercontent.com/28205134/32355725-1939f356-bff6-11e7-98cb-d785b9d5d32d.png)
screen capture of error

**Comment by eldy** [comment]
Right.
Transfer between account with different currency will be supported with v7 only.
