### ISSUE TITLE
Bug: Multiple Currencies don't work as expected

### ISSUE THREAD

**Issue by MartinHold** [Dolibarr/dolibarr#7767]
# Bug
Using multiple currencies does not yield expected results when issuing Purchase Orders

Example:  Company Currency €, Supplier Currency is $ and INR (i.e. 1 € equal 75 INR)
Supplier Pricelist for Product:  provided in $ and INR

Setting up Purchase Order for INR based Supplier:  
1 x Item for 1.000,- (INR)  gets on the Purchase Order for 75.000,- INR with a value of €1.000,-

Expected Behavior would be (when Setting up Purchase Order for INR based Supplier):
1 x Item for 1.000,- (INR) gets on the Purchase Order for 1.000,- INR  with a value of €13.33

## Environment
- **Version**: 6.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.31
- **Database**: MySQL or MariaDB 5.6.23-cll-lve
- **URL**: /ERP/supplier_proposal/card.php?id=2&action=actualizemulticurrencyrate

## Report

Workaround:  Simplify exchange rates, do not use live exchange rates, enter products with supplier price translated into € (most definitely not desired approach)

**Comment by atm-maxime** [comment]
For now it's not a bug, it's a feature not implemented yet. You can do sells and purchase with multi currencies, but you can't specify the currency on a product purchase price. So this price should still be dealed in your company currency. Next step is to allow to define the currency with the purchase price. Like this we'll have everything to better deal with purchase orders.

**Comment by MartinHold** [comment]
@atm-maxime I hear you, but offering an option (multiple currencies) which then yields incorrect results is not exactly a "feature not implemented" - especially since it would be easy to fix...

**Comment by MartinHold** [comment]
So, it's now 3 versions later and still the same issue:

Say, I have a supplier in India who gets paid in INR and I do business in Europe and pay in EUR. The supplier has a product he offers for 200 INR and the Exchange Rate is 80:1 (to make it easy to calculate), the system calculates correctly 200 (currency) and 2,5 (EUR) on the 3rd Party - Product - Price page.

However, when I go to create a Purchase Order and I order, say 50x that product, the system calculates a whopping 10.000 EUR (50 x 200) instead of 50 x 2,5...

C'mon guys, that can't be that hard to correct... right?  I mean, you offer multiple currencies - if you don't want to implement/correct that, take it out!
Or do you actually never want to close the gap to, say, ODOO?

**Comment by atm-maxime** [comment]
Hi @MartinHold,

Thanks for your kind comments. I took the time to check on a fresh 9.0 version and followed exactly your steps. And for me the result is OK, I have a purchase of 125 EUR / 10 000 INR. I created my purchase order from my supplier page, with the INR currency. Can you give us screenshots of your results ?

Usually, the features you will find in our software are added by volunteers, mostly to fit a customer need. As I'm sure you don't work for free, we don't either.

And just so you know, the multi-currency function was added to Dolibarr core by my company at first, because we developed it for a customer who needed only to sale with several currencies. So yes, first version of the module was not made for purchases. But overtime it has been added by some other people of the community, and yes again, we're not foolproof and cannot foresee all user needs and use cases.

Cheers.

**Comment by MartinHold** [comment]
Dear Maxime:

I believe the Dolibarr software is quite nice, given the fact it’s Open-Source - that’s why I’ve chosen it for my (now ex-)wife’s company…

And we’ve been able to work around the short-comings - my feed-back was merely an attempt to make the software even better since the issue seemed (and I was correct with my assumption) a minor one: As I recall, only a change to a few lines of code fixed it…!

I’m currently running 9.0.1, I didn’t upgrade as an other issue with printing a Delivery Receipt form also is pending to be fixed (again, a minor issue: an incorrect function was used - I submitted a change-request).

All in all, it’s a great piece of work and I appreciate it a lot, please do keep it up!

Best wishes,
Martin.

**Comment by atm-maxime** [comment]
Thanks for this reply.
Let us know if all is OK for you about this subject by closing this issue :)
And what about #7967 ?

**Comment by MartinHold** [comment]
Hello Maxime,

 

I am terribly sorry since i did not recognize, my previous email never made it through (it actually bounced).

 

I remember you asking what I changed to get it to work (at least for me).  Well, here it is:

Version 9.0.1, in file card.php, (or better ".../fourn/commande/card.php"). in section "Create an order" I have replace line 1024

from "$object->multicurrency_code = GETPOST('multicurrency_code', 'alpha');"

to "$object->multicurrency_code = $fourn->multicurrency_code;"

 

in order to make it work as advertised.

 

Since I wasn't sure about the implications I've added the following code to that section (added code in bold):

 

[...]

// Creation commande


$object->ref_supplier      = GETPOST('refsupplier');
$object->socid             = $socid;
$object->cond_reglement_id = GETPOST('cond_reglement_id');
$object->mode_reglement_id = GETPOST('mode_reglement_id');
$object->fk_account        = GETPOST('fk_account', 'int');
$object->note_private  = GETPOST('note_private','none');
$object->note_public       = GETPOST('note_public','none');
$object->date_livraison = $datelivraison;
$object->fk_incoterms = GETPOST('incoterm_id', 'int');
$object->location_incoterms = GETPOST('location_incoterms', 'alpha');
         if (! empty($conf->multicurrency->enabled)) {
             $object->multicurrency_code = $fourn->multicurrency_code;
         }
         else {
             $object->multicurrency_code = GETPOST('multicurrency_code', 'alpha');
         }
$object->multicurrency_tx = GETPOST('originmulticurrency_tx', 'int');
$object->fk_project       = GETPOST('projectid');

// Fill array 'array_options' with data from add form


[...]

 

 

Hope this helps. Sorry for the delay.

 

Best regards,

Martin Hold.

 




Gesendet: Sonntag, 02. Juni 2019 um 16:38 Uhr
Von: "Maxime Kohlhaas" <notifications@github.com>
An: Dolibarr/dolibarr <dolibarr@noreply.github.com>
Cc: "Martin Hold" <martin.hold@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [Dolibarr/dolibarr] Bug: Multiple Currencies don't work as expected (#7767)


Thanks for this reply.
Let us know if all is OK for you about this subject by closing this issue :)
And what about #7967 ?
