### ISSUE TITLE
Untranslated strings in Financial > Accountacy menus (en_US and en_CA, possibly others)

### ISSUE THREAD

**Issue by MagicFab** [Dolibarr/dolibarr#7774]
I noticed some untranslated strings in en_US and en_CA, possibly others. My understanding is the en_US locale is the default/fallback.

While my default language setting is fr_CA, I then switch to en_US or en_CA in **User display setup**, "Use personal value" option:

![image](https://user-images.githubusercontent.com/317514/32419644-31dc9ede-c24b-11e7-9c7f-e61164d36ce3.png)

I then noticed some strings remain untranslated under the Financial > Accountancy menu:

![selection_104](https://user-images.githubusercontent.com/317514/32419652-69555c7a-c24b-11e7-901c-7664aefc4def.png)

While looking at the source code and Transifex I noticed en_CA is is 0.41% translated, only a few files are in dolibarr/htdocs/langs/en_CA and I couldn't find any French strings in the en_US/accountancy.lang file.

Is it OK to just copy the missing files from en_US to get started in fixing en_CA ?

I am also fixing some grammar and inconsistencies in the en_US locale. How can this be done while keeping en_CA accordingly synchronized (at least for the first complete review)?

**Comment by eldy** [comment]
To fix en_US, you can make PR (we are missing contributors for this, your help will be previous).

To fix any other language code (en_CA, ...), only transifex can be used. Note that when a sync is done from transifex, only data in en_CA that differs from en_US are saved into file en_US, and dolibarr switch automatically on en_US when translation is not found, so you can update transifex only for trnalsation that differs from en_US
It is same between  fr_CA and fr_FR.

For the journal, you should have translation in accountancy.lang for en_US:
ACCOUNTING_SELL_JOURNAL=Sell journal
ACCOUNTING_PURCHASE_JOURNAL=Purchase journal
ACCOUNTING_MISCELLANEOUS_JOURNAL=Miscellaneous journal
ACCOUNTING_EXPENSEREPORT_JOURNAL=Expense report journal
ACCOUNTING_SOCIAL_JOURNAL=Social journal
