### ISSUE TITLE
problem in sending compound products

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#7782]
# Bug
When I try to send a composite product, although I have enough items in stock to compose this article, the system tells me that I do not have enough stock

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
It is expected that the system will detect the stocks of the parent product and that it will discount the stock of the same product and allow the shipment of the compound product, but this is not the case. The system does not allow to send the product because it says that there is not enough stock.

## Steps to reproduce the behavior
A product composed of others already in the system is created and enough stock is obtained. When that composite article is sold and the system is intended to ship it, although there is stock of the parent item, it does not stop shipping and sends an alert that there is not enough stock.

## [Attached files]
![2017-11-07](https://user-images.githubusercontent.com/28205134/32523176-cf428c02-c3df-11e7-9bbc-049002a56543.png)
![2017-11-07 1](https://user-images.githubusercontent.com/28205134/32523177-cf59e6ae-c3df-11e7-8753-6c779d4165dd.png)
![2017-11-07 2](https://user-images.githubusercontent.com/28205134/32523178-cf6ebe26-c3df-11e7-847f-1f5b964d74af.png)
![2017-11-07 3](https://user-images.githubusercontent.com/28205134/32523179-cf8b3b5a-c3df-11e7-93af-7d7e4979ba1f.png)
![2017-11-07 4](https://user-images.githubusercontent.com/28205134/32523180-cfa08dac-c3df-11e7-9fc6-870e824ffc7b.png)

**Comment by atm-maxime** [comment]
For now, when you ship a composed product, both the product and its components are decreased from stock. I agree that the product should not and only the components should.
In the meantime, there's an option in the stock module that says "Allow negative stock". You can use it until a fix is found to deal with this use case.
