### ISSUE TITLE
BUG : Multi prices level

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#7788]
# Bug
 When editing a price level it saves it in the product level, but also in llx_product.price field.

It is disturbing behaviour, the error should lie somewhere here under, full description below ;)
______
	 *	Modify customer price of a product/Service
	 *
	 *	@param  	double	$newprice		    New price
	 *	@param  	string	$newpricebase	    HT or TTC
	 *	@param  	User	$user        	    Object user that make change
	 *	@param  	double	$newvat			    New VAT Rate (For example 8.5. Should not be a string)
	 *  @param		double	$newminprice	    New price min
	 *  @param		int		$level			    0=standard, >0 = level if multilevel prices
	 *  @param     	int		$newnpr             0=Standard vat rate, 1=Special vat rate for French NPR VAT
	 *  @param     	int		$newpsq             1 if it has price by quantity
	 *  @param 		int 	$ignore_autogen     Used to avoid infinite loops
     *	@param      array	$localtaxes_array	Array with localtaxes info array('0'=>type1,'1'=>rate1,'2'=>type2,'3'=>rate2) (loaded by getLocalTaxesFromRate(vatrate, 0, ...) function).
     *  @param      string  $newdefaultvatcode  Default vat code
	 * 	@return		int						    <0 if KO, >0 if OK
	 */
	function updatePrice($newprice, $newpricebase, $user, $newvat='',$newminprice='', $level=0, $newnpr=0, $newpsq=0, $ignore_autogen=0, $localtaxes_array=array(), $newdefaultvatcode='')
	{
		global $conf,$langs;
		$id=$this->id;
		dol_syslog(get_class($this)."::update_price id=".$id." newprice=".$newprice." newpricebase=".$newpricebase." newminprice=".$newminprice." level=".$level." npr=".$newnpr." newdefaultvatcode=".$newdefaultvatcode);
		// Clean parameters
		if (empty($this->tva_tx))  $this->tva_tx=0;
        if (empty($newnpr)) $newnpr=0;
		// Check parameters
		if ($newvat == '') $newvat=$this->tva_tx;
		// If multiprices are enabled, then we check if the current product is subject to price autogeneration
		// Price will be modified ONLY when the first one is the one that is being modified
		if (!empty($conf->global->PRODUIT_MULTIPRICES) && !$ignore_autogen && $this->price_autogen && ($level == 1))
		{
			return $this->generateMultiprices($user, $newprice, $newpricebase, $newvat, $newnpr, $newpsq);
		}
		if (! empty($newminprice) && ($newminprice > $newprice))
		{
			$this->error='ErrorPriceCantBeLowerThanMinPrice';
			return -1;
		}
		if ($newprice!='' || $newprice==0)
		{
			if ($newpricebase == 'TTC')
			{
				$price_ttc = price2num($newprice,'MU');
				$price = price2num($newprice) / (1 + ($newvat / 100));
				$price = price2num($price,'MU');
				if ($newminprice!='' || $newminprice==0)
				{
					$price_min_ttc = price2num($newminprice,'MU');
					$price_min = price2num($newminprice) / (1 + ($newvat / 100));
					$price_min = price2num($price_min,'MU');
				}
				else
				{
					$price_min=0;
					$price_min_ttc=0;
				}
			}
			else
			{
				$price = price2num($newprice,'MU');
				$price_ttc = ( $newnpr != 1 ) ? price2num($newprice) * (1 + ($newvat / 100)) : $price;
				$price_ttc = price2num($price_ttc,'MU');
				if ($newminprice!='' || $newminprice==0)
				{
					$price_min = price2num($newminprice,'MU');
					$price_min_ttc = price2num($newminprice) * (1 + ($newvat / 100));
					$price_min_ttc = price2num($price_min_ttc,'MU');
					//print 'X'.$newminprice.'-'.$price_min;
				}
				else
				{
					$price_min=0;
					$price_min_ttc=0;
				}
			}
			//print 'x'.$id.'-'.$newprice.'-'.$newpricebase.'-'.$price.'-'.$price_ttc.'-'.$price_min.'-'.$price_min_ttc;
			if (count($localtaxes_array) > 0)
			{
			    $localtaxtype1=$localtaxes_array['0'];
			    $localtax1=$localtaxes_array['1'];
			    $localtaxtype2=$localtaxes_array['2'];
			    $localtax2=$localtaxes_array['3'];
			}
			else     // old method. deprecated because ot can't retreive type
			{
	       		$localtaxtype1='0';
			    $localtax1=get_localtax($newvat,1);
	       		$localtaxtype2='0';
			    $localtax2=get_localtax($newvat,2);
			}
			if (empty($localtax1)) $localtax1=0;	// If = '' then = 0
			if (empty($localtax2)) $localtax2=0;	// If = '' then = 0
			$this->db->begin();
			// Ne pas mettre de quote sur les numeriques decimaux.
			// Ceci provoque des stockages avec arrondis en base au lieu des valeurs exactes.
			$sql = "UPDATE ".MAIN_DB_PREFIX."product SET";
			$sql.= " price_base_type='".$newpricebase."',";
			$sql.= " price=".$price.",";
			$sql.= " price_ttc=".$price_ttc.",";
			$sql.= " price_min=".$price_min.",";
			$sql.= " price_min_ttc=".$price_min_ttc.",";
			$sql.= " localtax1_tx=".($localtax1>=0?$localtax1:'NULL').",";
			$sql.= " localtax2_tx=".($localtax2>=0?$localtax2:'NULL').",";
			$sql.= " localtax1_type=".($localtaxtype1!=''?"'".$localtaxtype1."'":"'0'").",";
			$sql.= " localtax2_type=".($localtaxtype2!=''?"'".$localtaxtype2."'":"'0'").",";
            $sql.= " default_vat_code=".($newdefaultvatcode?"'".$this->db->escape($newdefaultvatcode)."'":"null").",";
			$sql.= " tva_tx='".price2num($newvat)."',";
            $sql.= " recuperableonly='".$newnpr."'";
			$sql.= " WHERE rowid = ".$id;
			dol_syslog(get_class($this)."::update_price", LOG_DEBUG);
			$resql=$this->db->query($sql);
			if ($resql)
			{
				$this->multiprices[$level] = $price;
				$this->multiprices_ttc[$level] = $price_ttc;
				$this->multiprices_min[$level]= $price_min;
				$this->multiprices_min_ttc[$level]= $price_min_ttc;
				$this->multiprices_base_type[$level]= $newpricebase;
				$this->multiprices_default_vat_code[$level]= $newdefaultvatcode;
				$this->multiprices_tva_tx[$level]= $newvat;
				$this->multiprices_recuperableonly[$level]= $newnpr;
				$this->price = $price;
				$this->price_ttc = $price_ttc;
				$this->price_min = $price_min;
				$this->price_min_ttc = $price_min_ttc;
				$this->price_base_type = $newpricebase;
				$this->default_vat_code = $newdefaultvatcode;
				$this->tva_tx = $newvat;
				$this->tva_npr = $newnpr;
				//Local taxes
				$this->localtax1_tx = $localtax1;
				$this->localtax2_tx = $localtax2;
				$this->localtax1_type = $localtaxtype1;
				$this->localtax2_type = $localtaxtype2;
				// Price by quantity
				$this->price_by_qty = $newpsq;
				$this->_log_price($user,$level);	// Save price for level into table product_price
				$this->level = $level;				// Store level of price edited for trigger
__________________________

## Environment
- **Version**: LATEST (i checked also in develop) oldest where it happens is 4.0.4 

## Expected and actual behavior
It should not record a product price level in llx_product.price field, but only in llx_product_price
 WHERE  `price_level` = blabla

## Steps to reproduce the behavior
activate option 
/product/admin/product.php

![image](https://user-images.githubusercontent.com/3694135/32545280-79531c52-c47b-11e7-8412-0187df8b0fc2.png)

record a new product level price

and see the results in the field llx_product.price
and in the field llx_product_price.price (where fk_product ...=

**Comment by torvista** [comment]
I am looking at this subject and found your unanswered post.
I do not understand what the bug is.

I my checks I make these observations.
1) When products are set to have a **single** price, the  price in stored in two places:
llx_product.price
llx_product_price.price, with price level 1 (although price levels are not activated).

2) When products are set to have **multiple price levels** (e.g. two levels), the entered prices are still stored in two places:
price level 2 is stored in llx_product.price
both prices are stored in llx_product_price.price with their corresponding levels.

This does not seem logical to me.
Given that in 1), the stored price in llx_product_price.price is assigned level 1, I would expect that in 2) the level 1 price would be always assigned to llx_product.price. But it is not, the level price 2 is used.

Now while this seems inconsistent, I have not yet seen where this actually causes a problem.
The only point to make is, if products are returned to have a single price, it will be using the level 2 price. 

So, you say

> It should not record a product price level in llx_product.price field, but only in llx_product_price...

Why? What is the problem that this causes?
