### ISSUE TITLE
Barcodes not generating as expected

### ISSUE THREAD

**Issue by VPlatt** [Dolibarr/dolibarr#7793]
# Bug
[*Barcode not using user value and not matching system generated value*]

## Environment
- **Version**: [*3.7.0*]
- **OS**: [*Win 7 Pro SP1*]
- **Web server**: [*I don't what is required here*]
- **PHP**: [*phpMyAdmin ???*]
- **Database**: [*MySQL*]
- **URL(s)**: [*???*]

## Expected and actual behavior
[*When I create a new product, I select EAN13 from the barcode type and enter in a 13 digit value. I expect that upon clicking create that my image and barcode value entered would be shown in the product card.
However what happens is my value is replaced by an auto value and this value is not shown on the image generated barcode, the last digit is in correct. I tried to see if the different drop downs influence the barcode generated but they do not. I also can't edit the barcode once generated, meaning I can edit the value but it reverts.*]

## Steps to reproduce the behavior
[*I am not a developer or programmer so do not know how the code was or is written. The screen shots that I have from the dev show the expected behaviour but since he has left it isn't acting like that, I have since gone into his products in other DBs and the barcode values do not match the generated image.
I have no idea where this code lives in the server files or what I should check for or change, can someone help me please, I am sorry that I am a super n00b to github and programming
!*]

## Attached files
![barcode image not matching recorded product barcode](https://user-images.githubusercontent.com/33545146/32655640-209c14ea-c617-11e7-95b4-b5e2449da889.PNG)
![barcode module settings](https://user-images.githubusercontent.com/33545146/32656157-574393b8-c619-11e7-90fb-cab98d13342a.PNG)

**Comment by fappels** [comment]
Is the checksum valid of your 13 digit code? -> Your screendump shows an invalid EAN13 code.
If you want to generate an EAN13 you need to enter 12 digit, digit 13 is generated checksum.

Better post these kind of issues on the dolibarr.org forum. Also 3.7 support has stopped.

**Comment by VPlatt** [comment]
Hi :)

If I understand you correctly I should enter 12 digits as a value and the 13th will be inserted? I am sorry I am having to learn so much so quickly.

And I have posted on the doli forum but it seems to be really poorly supported (English version that is). Thanx for the heads up on the version. How do I go about upgrading, is there a clear guide?

**Comment by fappels** [comment]
https://wiki.dolibarr.org/index.php/Installation_-_Upgrade explains basic how to do it. I think there are more detailed books on dolistore. Always backup your database and files and don't skip any migration step. 

Please close the issue.

**Comment by VPlatt** [comment]
Thank you :)
How do I resolve the barcoding issue or will the upgrade do this?

**Comment by VPlatt** [comment]
Issue closed at request.

**Comment by fappels** [comment]
You will need to use another type of barcode for your code, which is not a legal EAN13 code. EAN13 is a very strickt code which must be conform to the guidelines of the EAN13 spec. You can use CODE39 or CODE128 which are code types that can contain anything you want. If you share your original barcode I can check the correct format.

**Comment by VPlatt** [comment]
Thanx you for the info. We are still making up the format of the barcodes that we want to use, but as soon as we have it, I will share. Do you have any other advise for using code39 for barcodes for the use in manufacturing, inventory taking and the stock in and out process.
We have 1D scanners and are still trying the figure out how to get Dolibarr to read the scans directly so that we don't have to go to a DB and then upload to Doli manually at the end of COB. Or is Doli not supposed to be able to read the scans of codes itself?

**Comment by fappels** [comment]
I will reply your message on the dolibarr.org forum, so other dolibarr users can benefit. Is your dolibarr.org alias Vera? Github if for bugs and development, so this discussion not really added value.
