### ISSUE TITLE
Creating new user data cloning

### ISSUE THREAD

**Issue by VPlatt** [Dolibarr/dolibarr#7794]
# Bug
[*When trying the create a new user the data fro a deleted user populates the fields and when trying to edit a user a different set of data (active existing user) populates the fields, not the actual user's details*]

## Environment
- **Version**: [*3.7.0*]
- **OS**: [*Win 7 Pro SP1*]
- **Web server**: [*hosted*]
- **PHP**: [*???*]
- **Database**: [*MySQL*]
- **URL(s)**: [*???*]

## Expected and actual behavior
[*When I want to create a new user I click on new user and the fields for the user come up but are prepopulated with the details of an old, delete user.
The other this is when wanting the edit a user the fields are populated with another active users details and NOT the current selected user's details. 
Please can someone help with this? Is it a known bug or is there something wrong in the code that the previous dev broke?*]

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug

**Comment by VPlatt** [comment]
Thank you For the info Eldy
