### ISSUE TITLE
Bug: Tooltips are showing HTML markup

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7795]
# Bug
Tooltips are showing literal HTML markup instead of applying it.

![untitled](https://user-images.githubusercontent.com/23050598/32656695-e0241b44-c60a-11e7-860d-2bd2e09f20d3.png)

## Environment
- **Version**: develop

**Comment by eldy** [comment]
You probably have javascript error.
Try to clear your browser cache.

**Comment by ruistrecht-alt** [comment]
You're totally right. After updating my repo to the latest develop and clearing the cache, all is well
CLOSED
