### ISSUE TITLE
Error al crear facturas en dolibarr 6.0.3 (fecha facturación)

### ISSUE THREAD

**Issue by netecperu** [Dolibarr/dolibarr#7805]
# Bug
[*No se pueden crear facturas cliente ni proveedor porque no se puede ingresar la fecha, ni manualmente ni por calendario ni ahora*]

## Environment
- **Version**: [*6.0.3*]
- **OS**: [*Debian 8.9‬*]
- **Web server**: [*Apache*]
- **PHP**: [*PHP version 7.1.11*]
- **Database**: [*Database type and version

  | MySQL or MariaDB 5.5.5-10.0.32-MariaDB-0+deb8u1
-- | --

**Comment by atm-maxime** [comment]
Sorry, you need to report issues in english.
