### ISSUE TITLE
Bug: Send Email

### ISSUE THREAD

**Issue by ias-ceo** [Dolibarr/dolibarr#7807]
# Bug

## Environment
- **Version**: 6.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.32
- **Database**: MySQL or MariaDB 10.1.24-MariaDB-cll-lve
- **URL**: /Dolibarr/admin/pdf.php?mainmenu=home

## Report
While use send email option any where at system, it does not save a copy of the email at the sent folder at email server. This cause mis-tracking the emails for follow up. Please fix it.

**Comment by atm-maxime** [comment]
Hello,

If the e-mail sent via Dolibarr is through the webserver, you won't have any trace of it in your mailbox. If you configure a SMTP to use, maybe you will have a trace in your "sent" folder (eg : google mail smtp doest that).

Anyhow, this is not an issue of Dolibarr.

**Comment by thom4parisot** [comment]
I have configured the SMTP sender via `SwiftMailer` but no email seems to be added to the `Sent` folder (or any folder) on the SMTP account.

How can I know in which folder I'm supposed to check?

Thanks a lot :-)
