### ISSUE TITLE
Bug Products Full list

### ISSUE THREAD

**Issue by Meliwine** [Dolibarr/dolibarr#7812]
I can't see the movement of my products, I have this error:
![full list doli](https://user-images.githubusercontent.com/32768094/32777638-3a3b7aee-c937-11e7-9f84-48dfe6eac16b.PNG)

**Comment by atm-maxime** [comment]
It seems to me that this is not an issue from Dolibarr but from your database. The table encoding seems to have been modified in your installation. You should contact your tech admin or a database admin to fix that.
