### ISSUE TITLE
Feature Request: Log updates/modifications done to objects (third-party, contract, invoice, etc.)

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#7819]
# Feature Request
Log updates/modifications/creations done to objects (third-party, contract, invoice, etc.) in a new tab. 
Much like the Log tab in the user card, but with actual records of the changes made and modification date.

## Use case
Many people like to keep track of the changes made to company records, to avoid false records and changes done by employees and also to allow easy reversion to the original data.

**Comment by dolibarr95** [comment]
hi
https://github.com/Dolibarr/dolibarr/issues/6847
