### ISSUE TITLE
Dolitstore

### ISSUE THREAD

**Issue by tofprod** [Dolibarr/dolibarr#7820]
Bonjour,

Je commence à avoir une flopée de modules commandés sur le store et je commence à m'y perdre.

Les modules n'apparaissent (au bas de la page) qu'en cliquant sur le numéro de commande, et il n'y aucune alerte (email par exemple) concernant les mises à jour.

Ne pourriez-vous pas créer une colonne supplémentaires avec les noms (cliquables) des modules correspondant à la commande (sur la même ligne) ? la date de dernière mise à jour (ce serait utile) avec une notif par mail ?

​Bonne journée à vous,

**Comment by atm-maxime** [comment]
Hi.
Thanks for the feedback. I recorded your request in the foundation repository because it's about Dolistore which is a foundation tool.
Cheers.

**Comment by eldy** [comment]
We are not able to say if an update is available or not as this information isbmanaged by the module provider and often not communicated.
Hiwever, you have a button in Dolibarr in setup of module page to check if updates exists. Each module check on the module provider page. However only few provider implements this.
