### ISSUE TITLE
Bug: accounting account type problem 

### ISSUE THREAD

**Issue by liqnuks** [Dolibarr/dolibarr#7821]
# Bug

On the bank module, on the main display of my french bank account I have a display problem on the accounting account type.

## Environment
- **Version**: `6.0.3`
- **OS**: `Debian GNU/Linux 8.8`
- **Web server**: `nginx, 1.6.2`
- **PHP**:` 5.6.30 (FPM)`
- **Database**: `mysql`
- **URL(s)**: `/compta/bank/card.php?id=1`

## Expected and actual behavior

When we select the accounting account type `512 - Banques`, we have `512 - Acreedores por arrendamiento financiero a corto plazo partes vinculadas`

When we select the accounting account type `512 - Banques`, we should have `512 - Banques`

## Steps to reproduce the behavior

* Create a new bank account (French configuration)
* Select on Accounting account `512 - Banques`

### Display accounting account type
![Display accounting account type](https://useless.liqnuks.info/pix/display_accounting_account_type.png)

### Edit accounting account type
![Edit accounting account type](https://useless.liqnuks.info/pix/edit_accounting_account_type.png)

**Comment by atm-maxime** [comment]
Seems fixed to me in 6.0.4 :
![image](https://user-images.githubusercontent.com/2097773/33808409-f32d9768-dde5-11e7-9689-2cf3cd3cd14b.png)
