### ISSUE TITLE
Bug: general search is not working for services

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7825]
# Bug
The main search (see screen below) is not working for services. Our version do have any product (only services). Product module is not activated. Same for API (dolibarr/htdocs/api/index.php/explorer). API for Product (and Services) only appear if the product module is activated. In our case, only the service module is activated.

![dolibarr_recherche](https://user-images.githubusercontent.com/5360027/32901905-54b5956a-caf1-11e7-80ff-14560cfb81b1.png)

## Environment
- **Version**: 6.0.1

**Comment by dolibarr95** [comment]
Hi
Doesn't work too with 6.0.0

**Comment by atm-maxime** [comment]
This has been fixed in future 6 version. Patch will be available soon.

**Comment by dolibarr95** [comment]
Tks
