### ISSUE TITLE
export quadra date amount, utf8 accent in all export

### ISSUE THREAD

**Issue by elarifr** [Dolibarr/dolibarr#7827]
# Bug
the quadra export of bookeeping 
- use date of export instead of date of each line
shoud use 
	$Tab['date_ecriture'] = dol_print_date($data->doc_date, '%d%m%y');
instead of
        //elarifr we should use dol_now function not time
	//$date_ecriture = dol_print_date(dol_now(), $conf->global->ACCOUNTING_EXPORT_DATE); // format must be ddmmyy
	//$Tab['date_ecriture'] = $date_ecriture;

- amount in export must be in cent with no decimal
        //elarifr le montant doit etre en centimes sans point decimal !
	$Tab['montant'] = str_pad(abs($data->montant*100), 12, '0', STR_PAD_LEFT); // TODO manage negative amount
instead of
         // $Tab['montant'] = str_pad(abs($data->montant), 12, '0', STR_PAD_LEFT); // TODO manage negative amount

- detail of each line should remove utf8 accent 
			$Tab['libelle_ecriture'] = str_pad(self::trunc(dol_string_unaccent($data->doc_ref) . ' ' . dol_string_unaccent($data->label_operation), 20), 20);
and
			$Tab['libelle_ecriture2'] = str_pad(self::trunc(dol_string_unaccent($data->label_operation), 30), 30);

- we need to keep valuable part of doc number / invoice
			//$Tab['num_piece3'] = str_pad(self::trunc($data->piece_num, 10), 10);
			$Tab['num_piece3'] = substr(self::trunc($data->doc_ref, 20), -10);

we have 
M9ELEONORVT000151117 FA1710-041805 SCI ElD+0000000698.4        000000     194                      194     EURVT    FA1710-041805 SCI ElÃ©onor - FA17194
while if should be
M9ELEONORVE000021017 FA1710-041805 SCI ElD+000000069840        000000     194                      194     EURVE    SCI Eleonor - FA1710-041805 -   710-041805                                                                         

## Environment
- **Version**: [*4.0 6.0 dev*]

tried to make pr but really it suck :( so i send file to darkjeff

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
