### ISSUE TITLE
Feature Request: Provide an orderd by clause in fetchObjectLinked

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#7830]
Would be nice to evolve this method to set an order by clause.

For example in contract we can link any invoice and invoice list is order by add action and not by invoice date or invoice reference.
With many linked object is not easy to check if all documents are linked.

**Comment by ATM-Marc** [comment]
Hello,

I'm working on this new feature

Best regards,
Marc.

**Comment by ATM-Marc** [comment]
PR #8547
