### ISSUE TITLE
Agregar campo marca 

### ISSUE THREAD

**Issue by gringoutnsp** [Dolibarr/dolibarr#7832]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by gringoutnsp** [comment]
Hola , cuando queremos conectar dolibarr con nuestro ecommerce , nos encontramos con el inconveniente de que dolibarr no contempla en campo marca .... es posible agregarlo ?

**Comment by gringoutnsp** [comment]
Hello, when we want to connect dolibarr with our ecommerce, we find ourselves with the inconvenience that dolibarr does not contemplate in the brand field ... is it possible to add it?

**Comment by simnandez** [comment]
For this kind of questions, use the forums: https://www.dolibarr.org/forum
