### ISSUE TITLE
Feature Request: REST API documents not generated on validation

### ISSUE THREAD

**Issue by MatthieuTexier** [Dolibarr/dolibarr#7836]
Version: 6.0.3
Hi,
When executing POST (proposals|orders|invoices)/{id}/validate the pdf documents are not generated
Is there any other way to have it generated using REST?
Regards

**Comment by eldy** [comment]
Right.
Currently, it is not possible.
We must add first a new API called 
"documents/build"   to send a request to generate a document with the template and output language.

**Comment by JonBendtsen** [comment]
I wish this could be re-opened, perhaps make it an option like notrigger in the proposalsValidateModel.
