### ISSUE TITLE
REST API cannot create/update/delete payments ?

### ISSUE THREAD

**Issue by MatthieuTexier** [Dolibarr/dolibarr#7838]
Version: 6.0.3
Payments don't seem to be manageable using REST API

**Comment by eldy** [comment]
Will be supported with 7.0

**Comment by MatthieuTexier** [comment]
Still not supported in 8.0.3

**Comment by MatthieuTexier** [comment]
We can only create a Payment with POST /invoices/{id}/payments, no way to attach sevaral invoices, no way to delete a payment etc.
