### ISSUE TITLE
[Feature Request] Supplier order information

### ISSUE THREAD

**Issue by delcroip** [Dolibarr/dolibarr#7841]
# Feature Request
Enable better handling of order 
https://www.dolibarr.org/forum/3-installation/27361-suppliers-orders-supplers-product-description
https://www.dolibarr.org/forum/3-installation/27362-suppliers-orders-our-unit-of-measure

## Use case
Want to buy item from a supplier where he expect specific information
- Quantity per Unit
- description

## Suggested implementation
add those fields per supplier price per item:
https://ide.pmpd.eu/dolibarr/htdocs/product/fournisseurs.php?id=11&action=add_price
Show them on the invoice and make sure the correct quantity is save at dolibarr

**Comment by alvin101** [comment]
this link above, mean something?  https://ide.pmpd.eu/dolibarr/htdocs/product/fournisseurs.php?id=11&action=add_price

**Comment by delcroip** [comment]
I forgot to remove the domain, but it indicate thé page where i see the modifications

dolibarr/htdocs/product/fournisseurs.php?id=11&action=add_price

**Comment by fappels** [comment]
I ref this to discussion #5217 new product supplier description.

**Comment by davidNDU** [comment]
It's an important feature. 
- Different suppliers have different package sizes. But it's the same product. How is it possible to compare prices?
- Ordering a package with e.g. 100 pieces must increase the stock by 100 pieces. The prices from the supplier is not per piece but per package.
