### ISSUE TITLE
Bug: Integrity check fail (with inventory.class.php)

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7842]
# Bug
Integrity check (/admin/system/filecheck.php) fail on new install with the distant server option (https://www.dolibarr.org/files/stable/signatures/filelist-6.0.1.xml) because of the file :

/product/inventory/class/inventory.class.php

However, I never changed this file (I tried a new install on a new machine, same result).

## Environment
- **Version**: 6.0.1

**Comment by vvnt** [comment]
Same file, same problem for Dolibarr 6.0.3.

**Comment by eldy** [comment]
I can't reproduce. Can you provide a screenshot of the page showing diff.
Which package (file) did you instance to install 6.0.3 ?

**Comment by vvnt** [comment]
I used .zip file from github (https://github.com/Dolibarr/dolibarr/archive/6.0.3.zip).

![files_integrity_check_603_from_zip](https://user-images.githubusercontent.com/5360027/33233746-1de79dea-d21b-11e7-94b0-8750fe374697.png)
