### ISSUE TITLE
Bug: no visible warning when invoice validation is refused because of warehouse below zero

### ISSUE THREAD

**Issue by annegoet** [Dolibarr/dolibarr#7846]
# Bug
Invoices could not be validated because warehouse was not allowed below zero
No warning was given, so it was hard to figure out why no invoices could be validated

## Environment
- **Version**: 6.0.3.

## Expected and actual behavior
Please show a warning message when an invoice cannot be validated and point out that the warehouse is empty or not allowed below zero

It was solved by modifying the warehouse module and allowing the warehouse to go below zero. But it would be nice to have received a warning.

**Comment by atm-maxime** [comment]
Fixed in #7941
