### ISSUE TITLE
Feature request : Add warehouse in the customer order (or customer card)

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7852]
# Warehouse
When we manage several warehouses around the word (eg :  Asia, Europe, USA).

Actually when we create an order: 

1. Create / Edit the draft (with several information, customer, lines etc)
2. Then valid this draft (chose the warehouse)

I think we could add in the first step a (non mandatory) field warehouse :

1. Create / Edit the draft (customer from Mexico so i select the warehouse USA)
2. Then valid this draft (chose / confirm the warehouse)

In this case we could also predefined a warehouse to each customer in order to decrease shipping cost / delay etc.
Also it could be great to for online shop etc.

Tks

**Anyway tks for this wonderful open and flexible tool.**

**Comment by atm-maxime** [comment]
Hi !
Thanks for your feedback. I think your idea is a good one, we could add an option to allow to define a warehouse on the customer card and it will be used as default warehouse when we must choose.
I mark this as feature request.
Cheers

**Comment by dolibarr95** [comment]
Hi !
tks a lot !!

**Comment by atm-maxime** [comment]
Field has been added in database, but not available on the customer card to be filled.

**Comment by dolibarr95** [comment]
Hello !
little up for this feature :)

**Comment by BB2A-Anthony** [comment]
> Hi !
> Thanks for your feedback. I think your idea is a good one, we could add an option to allow to define a warehouse on the customer card and it will be used as default warehouse when we must choose.
> I mark this as feature request.
> Cheers



> Field has been added in database, but not available on the customer card to be filled.

Available on the customer card to be filled.

I updated the card #17021
