### ISSUE TITLE
BUG on the products / services search from the left menu

### ISSUE THREAD

**Issue by salnaSrc** [Dolibarr/dolibarr#7855]
# Bug
*From the search option on the left the if we do a search for product / services the search is always on products*

## Environment
- **Version**: *6.0.3*

## [Attached files]
*I just modify the request on line 299 to 306, but i think it is not the best way*
![dol_contrats](https://user-images.githubusercontent.com/30660993/33130253-015ef1bc-cf93-11e7-9276-a8d0d12d87d9.png)

## Use case
*Create a service, do a search ont this service from the lelft menu, only products are requested*

## Suggested implementation
*I did a small correction on my file product/list.php directly on the SQL request, but i think there is a problem with the variable $search_type, because this variable is always  = 0 even the search is done on  a service*

**Comment by eldy** [comment]
Seems fixed for 6.0.4

**Comment by atm-maxime** [comment]
Fixed in #7758
