### ISSUE TITLE
Bug: remise partiellement prise en compte : P.U. (devise) et Total HT (devise d'origine) à 0.00

### ISSUE THREAD

**Issue by AlainRnet** [Dolibarr/dolibarr#7864]
# Bug
Le montant d'un acompte en CHF (sans changement de devise) n'est pas déduit de la facture. Ou plutôt, le Total HT est pris en compte mais pas le Total HT (devise d'origine)
Or l'acompte contient bel et bien les 2 montants (Total HT et Total HT (devise d'origine))

Dans la facture, le total est correct, mais comme les colonnes P.U. (devise) et Total HT (devise d'origine) sont à 0.00, c'est dans le PDF généré que la déduction n'est pas prise en compte dans le total malgré qu'elle soit affichée.
Ainsi, mon client m'a payé la somme totale (y compris l'acompte) et je dois maintenant lui rembourser le montant correspondant.

J'espère que c'est clair, je suis bien sûr dispo pour tout complément d'informations ou questions.
Merci d'avance de la prise en compte de ces remarques.

## Environment
- **Version**: 6.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.0.25
- **Database**: MySQL or MariaDB 5.5.5-10.0.27-MariaDB
- **URL**: /gestion/compta/facture/card.php?facid=293

**Comment by AlainRnet** [comment]
L'acompte affiche bien les 2 montants : 
![selection_008](https://user-images.githubusercontent.com/6475120/33216114-d0e53446-d132-11e7-9ced-fb731722f1e9.png)

La facture affiche partiellement la déduction de l'acompte
![selection_009](https://user-images.githubusercontent.com/6475120/33216241-5112a75c-d133-11e7-824c-f60e4ae66ab1.png)

Et dans le PDF, il y a bien la déduction de l'acompte : 
![selection_010](https://user-images.githubusercontent.com/6475120/33216300-8eed833a-d133-11e7-9e35-45a23340ea50.png)
mais le total n'en tient pas compte (1 729,85 au lieu de 1 329,85) :
![selection_011](https://user-images.githubusercontent.com/6475120/33216327-b28d3df8-d133-11e7-8bb1-95ef4d020b6c.png)

**Comment by eldy** [comment]
Peux tu reproduire le cas de test sur demo.dolibarr.org et citer la référence de la facture ?

**Comment by AlainRnet** [comment]
Volontiers. Voici : https://demo.dolibarr.org/compta/facture/card.php?facid=5885
Dans le PDF, on voit clairement un problème : le total HT est différent du total TTC (alors que la TVA est à 0).
Autrement dit le total TTC tient compte de la réduction contrairement au total HT.

**Comment by AlainRnet** [comment]
j'ai aussi essayé de reproduire le bug en activant les logs et j'ai trouvé qu’effectivement la requête envoyait un montant à 0 dans les champs multicurrency_total_ht et multicurrency_total_ttc

Extrait de /documents/dolibarr.log :

> FactureLigne::insert rang=-1
> FactureLigne::insert
> sql=INSERT INTO llx_facturedet (fk_facture, fk_parent_line, label, description, qty, vat_src_code, tva_tx, localtax1_tx, localtax2_tx, localtax1_type, localtax2_type, fk_product, product_type, remise_percent, subprice, fk_remise_except, date_start, date_end, fk_code_ventilation,  rang, special_code, fk_product_fournisseur_price, buy_price_ht, info_bits, total_ht, total_tva, total_ttc, total_localtax1, total_localtax2, situation_percent, fk_prev_id, fk_unit, fk_user_author, fk_user_modif, fk_multicurrency, multicurrency_code, multicurrency_subprice, multicurrency_total_ht, multicurrency_total_tva, multicurrency_total_ttc) VALUES (294, null, null, '(DEPOSIT)', 1, '', 0, 0, 0, '0', '0', null, 0, 0, -400, 59, null, null, 0, -1, 0, null, 0, '2', -400, 0, -400, 0, 0, 100, null, NULL, 1, 1, 0, '', 0, 0, 0, 0)

J'ai un peu regardé dans le fichier htdocs/compta/facture/class/facture.class.php sans encore trouver où les données des montants se perdent en route...

**Comment by swbraun** [comment]
I don't speak French, but whit the help of Google translate I think I have the same bug and some more insights. I just updated to 6.0.4 to see if the bug is still there.

The problem is when creating a discount/allowance (remise), it seems it isn't capable of multicurrency. After I created a discount for a customer I checked the database and all multicurrency fields contain "0".
So this seems to be used in the card view if the invoice when multicorrency is enabled and also in the calculation in the PDF output.
Disabling multicurrency and the output is correct again.

**Comment by AlainRnet** [comment]
Oui, vous avez raison, le problème est lié au module multicurrency. On le voit dans mon log ci-avant, les montant inséré sont à 0, et je ne vois pas quelles variables transmets cette information.
En effet, on peut désactiver le module multicurrency... mais pas en production :s

eldy m'a demandé davantage d'informations, je l'ai ai ajoutée, mais je ne sais pas comment retirer l'étiquette "Bug need more information" pour qu'il puisse nous aiguiller dans la recherche d'une solution.

**Comment by AlainRnet** [comment]
How to solve this bug please. Because, I cannot Disabling multicurrency...
I always have to update in phpMyAdmin with UPDATE `llx_facturedet` SET `multicurrency_subprice`=`subprice`,`multicurrency_total_ht`=`total_ht`,`multicurrency_total_tva`=`total_tva`,`multicurrency_total_ttc`=`total_ttc` WHERE `fk_facture`=XXX

**Comment by AlainRnet** [comment]
8.0.3 : le bug semble résolu. Merci!!
