### ISSUE TITLE
Feature Request: Template invoices forget Contacts/Addresses

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7866]
# Bug
When we create an invoice with a "Customer invoice contact" and then transform this invoice into "Template invoices", the recurring invoices do not remember the "Customer invoice contact".

## Environment
- **Version**: 6.0.1

**Comment by atm-arnaud** [comment]
Hello,

I'm currently working on this issue.

Regards,

**Comment by atm-arnaud** [comment]
Hello,

As i was expecting, there is no contact tabs in Template invoices. Could you modify this issue to a Feature Request ?
In other time there is a defaultcontact module on dolistore that could help you (https://www.dolistore.com/en/modules/389-Default-contact.html?search_query=contact+&results=300)
You could define default contact for all documents and customers

Regards,
