### ISSUE TITLE
Feature request: hide or change bank information on propal

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7880]
# Feature Request : hide or change bank information on propal
On the propal page, it is not possible to hide or modify banking information. Therefore, when the banking module is activated, the pdf file displays the information of the first account it finds.

It would be nice to be able to change the bank account on propales (it is possible on invoices).

**Comment by atm-maxime** [comment]
There's a hidden option named BANK_ASK_PAYMENT_BANK_DURING_PROPOSAL that allow you to define on a proposal which bank account to use. Same option exists for orders, which is documented here https://wiki.dolibarr.org/index.php/Setup_Other#Bank_module

If no bank account is defined on the proposal, this is not the first account that is used, this is the account defined in the invoice module configuration.

I'll see if this option should become visible and I let you close this issue if my answer is ok.

Cheers.

**Comment by vvnt** [comment]
Thank you. It works. Too bad we can't add this option on the wiki.
