### ISSUE TITLE
Bug: Stock, Shipment and Virtual Product Mgt

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#7881]
# Bug
Shipment and Stock are not affected by Virtual Products 

## Environment
- **Version**: 6.0.3
- **OS**: Ubuntu Server 16.0.4 LTS
- **Web server**: Apache2.4
- **PHP**: 7.0
- **Database**: MySQL 5.7
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Expected behavior: When selling a Virtual product (VP), the shipment option shows them as available in stock with the detailled components. When the shipment is done, the stock is adjusting the physical stock of the components (Virtual and Real).
Actual behavior: The VP show a stock of zero (although the individual components are show correctly). Product cannot be shipped.

## Steps to reproduce the behavior
Create a new product. Add sub products to the VP configuration.
The new product appears in the list of products although no stock physical or virtual is available (when all components are available).
When modifying manually the physical stock (add 1), you can ship the product, and the stock gets decreased by 1. However, the individual components stock does not decrease.

**Comment by eldy** [comment]
Can you provide a screenshot of the page where you defined the components inside the virtual product ?

**Comment by dom-breizh** [comment]
This is an example for a small custom PC.
In this case I no longer have all the components. But when all components are available, the product is not made available on the 'virtual stock'. Selling the virtual produst does not affect the components stock although it is marked to do so.

![2017-12-01-17-37-www solipym net](https://user-images.githubusercontent.com/5640062/33492835-8a3556f2-d6be-11e7-95c9-a15e7a7c1497.png)

**Comment by dom-breizh** [comment]
I guess it will become available with 6.0.4 ? Any release date ?
