### ISSUE TITLE
Bug: Avoir sur facture fournisseur

### ISSUE THREAD

**Issue by nicoxygen** [Dolibarr/dolibarr#7885]
dolibarr 6.0.3

Quand on veut crée une facture avoir par rapport à une facture existante la création amène sur une page blanche, quand on retrouve l'avoir créé on se rend compte que:
1: l'intitulé des produits/service est vide. ( pour les intitulés de produits rentrés manuellement )
2: Une fois l'avoir validé on ne peut pas cliquer sur "saisir remboursement" car le lien est grisé
3:Normal le montant restant à rembourser est à 0,00€

![bug-dolibarr](https://user-images.githubusercontent.com/17491075/33336258-9d164e8a-d46f-11e7-8774-f787d7306403.png)

**Comment by eldy** [comment]
Etes vous en mode "stable" ou en mode "experimental" ou "develop" ?

**Comment by nicoxygen** [comment]
je suis sous la 6.0.3 en mode stable, peux-t-on changer ce mode dans dolibarr ?

**Comment by eldy** [comment]
C'est étrange. Le mode stable ne devrait pas permettre de créer des avoirs fournisseurs (non géré, a part en saisissant des lignes négatives).
Par quel écran etes vous passé pour créer l'avoir fournisseur ?

**Comment by eldy** [comment]
Ce sera corrigé avec la 7.0

**Comment by nicoxygen** [comment]
j'ai testé la 6.0.4 apparemment c'est déjà effectif

**Comment by nicoxygen** [comment]
J'ai mis a jour dolibarr vers 6.0.4 mais l'erreur subsiste.
Je crée une facture fournisseur 01 que je règle et qui pass à payé.
ensuite je crée un facture avoir en liaison avec la précédente facture 01, je fait l'avoir qui seras automatiquement sur négatif et quand je valide la ligne reste à payé est à 0, du coup je ne peux pas saisir le remboursement, sur votre demo en 6.0.4 ça fonctionne bien.

**Comment by nicoxygen** [comment]
Dans la version 6.0.4 de test quand on clic sur facture avoir ça créé une facture standard donc ce n'est pas bon aussi.

**Comment by PMickael** [comment]
Bug toujours présent, création d'une facture standard au lieu d'une facture d'avoir en 7.0.2

**Comment by jtraulle** [comment]
Je suis également intéressé et en effet, un clic sur le bouton d'action **Créer facture avoir** redirige vers la page de création de facture fournisseur mais seules une facture standard peut être créée. Je suis en Dolibarr 7.0.2 également (mode stable).
