### ISSUE TITLE
Feature Request: Fixed delivery date in an order 

### ISSUE THREAD

**Issue by amoreira1** [Dolibarr/dolibarr#7887]
Hi All

When we fullfield an order, instead of i put manually the delivery date, i would like that the system put automaticly the delivery date .
How to do it ?
Thanks in advance

**Comment by atm-maxime** [comment]
This will need some coding. Can you explain the rules to calculate the delivery date ? Maybe this can be a generic feature. Otherwise you should look for someone to develop this for you.

**Comment by amoreira1** [comment]
Hi
Thanks for your email

Instead of we put manually the datre of delivery i «know that i will need 120 to execute all my orders, so i would like that automaticly the delivery date was the date of today + 120 days

How to make it 

Best regards
Antonio
