### ISSUE TITLE
Update Actioncomm for remove fk_element and elementtype

### ISSUE THREAD

**Issue by ayalejo** [Dolibarr/dolibarr#7889]
# Bug
I can´t update the a actioncomm and set the elementype and fk_element to false.
all possible values for null return false

The following things are considered to be empty:

"" (an empty string)
0 (0 as an integer)
0.0 (0 as a float)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
$var; (a variable declared, but without a value)

Original Code
if (! empty($this->fk_element)) $sql.= ", fk_element=".($this->fk_element?$this->fk_element:"null");
        if (! empty($this->elementtype)) $sql.= ", elementtype=".($this->elementtype?"'".$this->elementtype."'":"null");

## Environment
- **Version**: 6.0.3

## Suggested implementation
$sql.= ", fk_element=".(! empty($this->fk_element)?$this->fk_element:"NULL");
$sql.= ", elementtype=".(! empty($this->elementtype)?"'".$this->elementtype."'":"NULL");

**Comment by eldy** [comment]
What do you mean with "I can´t update the a actioncomm and set the elementype and fk_element to false"
Can you update on demo.dolibarr.org ?

**Comment by ayalejo** [comment]
Hello! When I try to put fk_element and elementtype to NULL in an action using the update function in actioncomm.class.php I can not because in the 'if' the empty function, if it has a value that false does not update those values.

Example : 
In the DB one actioncomm row has the values :
 - fk_element = 1
 - elementtype = "ticket" // custom value
I wish remove this linked element using the update function of actiomm.class.php
I set both values to NULL. When pass for the if, the empty function return false and NO update the value. 
`if (! empty($this->fk_element)) $sql.= ", fk_element=".($this->fk_element?$this->fk_element:"null");`

My problem is that cant remove the linked object using the update function.
