### ISSUE TITLE
Bug: intégrité des fichiers et erreur "Access refused by SQL/Script injection protection in ..." - Pb ckeditor

### ISSUE THREAD

**Issue by edg-photographe** [Dolibarr/dolibarr#7890]
# Bug
Bonjour,
Après mise à jour du package 6.0.3, un bug est apparu lors de la saisie de toute information dans les champs de texte enrichi. 
Dans ces champs, en cliquant sur le bouton "Source", on fait apparaitre le code par défaut qui est celui-ci : 

<br />
<style type="text/css">
</style>

Si on saisi du texte ou si on laisse ce champs vide, une erreur de type "Access refused by SQL/Script injection protection in ..." se produit systématiquement. 
Si on supprime le code HTML de ces champs avant validation, l'erreur n'apparait plus. 

Après vérifier l'intégrité des fichiers, il apparait que de nombreux fichiers sont manquants pour le dossier /includes: 
- ckeditor
- geoip
- mike42
- nusoap
-phpoffice

et pour le dossier /Public/test/

Hors nous avons réinstallé le package complet téléchargé à cette adresse https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/6.0.3/ au format ZIP. 

Est-ce que ces deux problèmes sont liés ? Sinon d'où provient le bug Access refused by SQL/Script injection protection in ... ?

## Environment
- **Version**: 6.0.3
- **OS**: SunOS localhost 5.10 Generic_150401-49 i86pc
- **Web server**: Apache/2.2.31 (Unix)
- **PHP**: cgi-fcgi 5.6.32
- **Database**: MySQL or MariaDB 5.6.37-log
- **URL**: /admin/system/filecheck.php?xmlshortfile=%2Finstall%2Ffilelist-6.0.3.xml&target=remote&xmlremote=https%3A%2F%2Fwww.dolibarr.org%2Ffiles%2Fstable%2Fsignatures%2Ffilelist-6.0.3.xml&check=V%C3%A9rifier

## Report
Cordialement
Eric

**Comment by eldy** [comment]
Si il y a des fichiers manquant, notemment ckeditor, alors le ckeditor qui tourne est peut etre celui d'une autre version qui vient d'ailleurs.
Dans le zip issu de sourceforge, on trouve bien ces répertoires dans htdocs/includes
Donc il faut en effet réinstaller pour avoir ces fichiers manquant et s'assurer que le serveur web peut les lire.

**Comment by eldy** [comment]
Le Access Refused est du à une protection.
Le post devrait passé si le contenu du html n'a pas de javascript.
