### ISSUE TITLE
Bug: user triggered in .../httpdocs/core/lib/functions.lib.php on line 3437

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#7891]
# Bug

## Environment
- **Version**: 7.0.0-alpha
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB-0+deb8u1
- **URL**: /fourn/facture/card.php?id=416

## Report
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT ec.rowid, ec.statut as statuslink, ec.fk_socpeople as id, ec.fk_c_type_contact, '-1' as socid, t.statut as statuscontact, t.login, t.photo, t.civility as civility, t.lastname as lastname, t.firstname, t.email, tc.source, tc.element, tc.code, tc.libelle FROM llx_c_type_contact tc, llx_element_contact ec LEFT JOIN llx_user t on ec.fk_socpeople = t.rowid WHERE ec.element_id = AND ec.fk_c_type_contact=tc.rowid AND tc.element='invoice_supplier' AND tc.source = 'internal' AND tc.active=1 ORDER BY t.lastname ASC
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: Erreur de syntaxe près de 'AND ec.fk_c_type_contact=tc.rowid AND tc.element='invoice_supplier' AND tc.sourc' à la ligne 1

XDebug informations:
File: /home/httpd/vhosts/fixsun.fr/domains/dolibarr.fixsun.fr/httpdocs/core/class/commonobject.class.php
Line: 940
Function: liste_contact

**Comment by atm-maxime** [comment]
Seems to me that it's fixed in beta
