### ISSUE TITLE
invoice and order pdf merge doesnt exist, dolibarr 6.0.3

### ISSUE THREAD

**Issue by gabolone** [Dolibarr/dolibarr#7894]
# Bug
when you hit the pdf merge option in a inovice or order list the page is not found, like is not there. 

## Environment
- **Version**: 6.03
- **OS**: [*Server OS type and version*]
- **Web server**: Apache/2.4.7 (Ubuntu)

--

- **PHP**: 5.5.9-1ubuntu4.7
-**Database**: MySQL or MariaDB 5.5.41-0ubuntu0.14.04.1
--

- **URL(s)**: http://localhost/commande/list.php#show_files

**Comment by eldy** [comment]
Can't reproduce.
Do you have trouble on demo.dolibarr.org ?

**Comment by gabolone** [comment]
No, i have a server version. The page is missing.

**Comment by gabolone** [comment]
I had the previous version installed, and when I update to 6.0.3 when I try to make a pdf merge of various orders or invoice the page is missing. Doesn't happend with proposals pdf merge, wich happend to work fine. Please someone help me with this I use the program for my work. thanks
