### ISSUE TITLE
Bug: the linked element is lost when modifying action

### ISSUE THREAD

**Issue by ayalejo** [Dolibarr/dolibarr#7897]
# Bug
When an action is edited, the linked element is lost

## Environment
- **Version**: 6.0.3

## Expected and actual behavior
The linked element not lost when edit the action

## Steps to reproduce the behavior
Edit one action with a linked element and save it

## Suggested implementation
Replace original code : 
`		// Object linked
		if (! empty($object->fk_element) && ! empty($object->elementtype))
		{
			include_once DOL_DOCUMENT_ROOT.'/core/lib/functions2.lib.php';
			print '<tr><td>'.$langs->trans("LinkedObject").'</td>';
			print '<td>'.dolGetElementUrl($object->fk_element,$object->elementtype,1).'</td></tr>';
		}`

with it: 

`		// Object linked
		if (! empty($object->fk_element) && ! empty($object->elementtype))
		{
			include_once DOL_DOCUMENT_ROOT.'/core/lib/functions2.lib.php';
			print '<tr><td>'.$langs->trans("LinkedObject").'</td>';
			print '<td>'.dolGetElementUrl($object->fk_element,$object->elementtype,1).'</td></tr>';
			print '<input type="hidden" value="'.$object->fk_element.'" name="fk_element">';
			print '<input type="hidden" value="'.$object->elementtype.'" name="elementtype">';
		}`

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by eldy** [comment]
About your suggestion, what is file and line nb ?

**Comment by atm-maxime** [comment]
Can't reproduce in 6.0.4, should have been fixed

**Comment by ayalejo** [comment]
The problem for me is in the comm/action/card.php when you are in edit mode and have a element linked, you lost it when save.

Suggestion is for file comm/action/card.php at line 1155

After review the problem, all is for my other bug [https://github.com/Dolibarr/dolibarr/issues/7889](url) when you edit the action with the form comm/action/card.php if you dont set a value for fk_element and elementtype it no change (that was the original code).  As I need to be able to update an action to unlink an element, I have to modify the code so that the update function of actioncomm.class.php will always modify the value of fk_element and elementtype. Now the comm/action/card.php in edit mode no set value for update the linked element.

**Comment by atm-maxime** [comment]
So if I understand, you made changes in your Dolibarr core code to allow to unlink object from action card (#7889), and this causes the issue that makes the linked object always disappear (#7897). Am I correct ?
So you should close this issue as this is not one in Dolibarr core, and the other one is not a bug because the function to unlink an object from an action card has simply not been implemented yet.

**Comment by ayalejo** [comment]
Ok, I put this thinking it was a bug because the update code in card.php file of the object does not allow you to update the linked item (you dont sent update data for fk_elemente and elementtype). I close it. Thx!
