### ISSUE TITLE
Company name can't be edited

### ISSUE THREAD

**Issue by am1github** [Dolibarr/dolibarr#7899]
# Bug
The installation proceeded successfully, without any errors.
All tables are created and seems working.
I can login and enter a company/country name, but both seems not to be saved.
Within the user-list it shows me a warning with "This user has no permissions", but it is the *SuperAdmin*?

## Environment
- **Version**: 6.0.3
- **OS**: Linux Gentoo 4.12.12
- **Web server**: nginx 1.12.1
- **PHP**: PHP 7.0.25
- **Database**: MariaDB 10.1.26

## Expected and actual behavior
Can't enter any valid company details - seems a permission problem?

## Steps to reproduce the behavior
Just make a clean installation of dolibarr 6.0.3 via the provided ZIP-file on sourceforge.

**Comment by eldy** [comment]
Hum strange. Can't reproduce.
Is your instance available online ? If yes, can you send url and login/pass to eldy@destailleur.fr ?

**Comment by jbeerbom** [comment]
I have the same problem, but my user list isn't showing the mentioned error.

- **Version:** 7.0.1
- **OS**: Ubuntu 16.04.4 LTS
- **Webserver**: nginx/1.14.0
- **PHP**: 7.0.30
- **Database**: mysql  Ver 14.14 Distrib 5.7.22

Whenever I try to change the Company settings, and especially the country, the page reloads and/or the settings are just not saved. Nothing shows up in the logs either (PHP, nginx and MySQL).
