### ISSUE TITLE
Bug: Limited access to Dolibarr features with duplicated module

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#7901]
# Bug
If there is a duplicated module (the same module in /htdocs and /htdocs/custom) the access to some features is restricted (white/blank page) e.g. User permissions, Import/Export in general tools. 

## Environment
- **Version**: 6.0.4
- **OS**: Linux 3.14.32-xxxx-grs-ipv6-64 #7 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.32
- **Database**: MySQL or MariaDB 5.5.5-10.2.11-MariaDB
- **URL(s)**: /htdocs/imports/import.php?leftmenu=import /htdocs/exports/export.php?leftmenu=export /htdocs/user/perms.php?id=1

## Fix
Removing the duplicated folder fixes the issue

**Comment by simnandez** [comment]
I think this is not a bug. The error is having a module duplicate...

**Comment by futurehousestore** [comment]
I think that having two the same modules in two different directories shouldn’t be allowed as it is in one directory. Or at least there should be some kind of information as it is in the modules setup page.
