### ISSUE TITLE
Bug: External non-admin user can edit all permissions

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#7904]
# Bug
From my main admin account, I've changed my test account from admin to normal user and reduced his permissions to a minimum. When I logged in as a test account, the view of modules (in top bar) was reduced but when I went to user settings I was able to edit all permissions for myself (test account). The details  in User card shows Administrator | No
 

## Environment
- **Version**: 7 beta
- **OS**: Linux 3.14.32-xxxx-grs-ipv6-64 #7 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.32
- **Database**: MySQL or MariaDB 5.5.5-10.2.11-MariaDB
- **URL(s)**: /htdocs/user/perms.php

## Expected and actual behavior
Expected: not to be able to change the permission as non-admin user

## Steps to reproduce the behavior
as per bug description above

**Comment by eldy** [comment]
I can't reproduce.
Can you provide a screenshot of permission of the test user ?

**Comment by futurehousestore** [comment]
![doli1](https://user-images.githubusercontent.com/28427270/33606978-48122e48-d9b7-11e7-9968-07c6ce625c0a.JPG)
![doli2](https://user-images.githubusercontent.com/28427270/33606986-4dfe2e10-d9b7-11e7-8e16-3f98c1fb996e.JPG)
![doli3](https://user-images.githubusercontent.com/28427270/33606992-52ebb2b2-d9b7-11e7-99ee-d338648a24d8.JPG)

**Comment by futurehousestore** [comment]
I had a little play around with the permissions as a test user and I disabled Users & groups for myself (test user) and that fixed the problem. So, in this case, should a non-admin user have permissions to edit the permissions or should that be restricted?
![dol4](https://user-images.githubusercontent.com/28427270/33607616-a269d70e-d9b9-11e7-85bc-4c2a328788f5.JPG)

**Comment by atm-maxime** [comment]
Management of users, groups and permissions is possible to any user having the permissions to do so. It's not only an admin right.
For example, I can have a HR person who is in charge of managing users and groups, but it's not an admin because I don't want him to go in the system setup.

**Comment by futurehousestore** [comment]
Thanks, Maxime. I fully understand that. It makes sense to me but I think that in this case (when you degrade an admin user to a non-admin user) there should be an automatic option to deactivate managing of permissions or some kind of reminder about the full permissions granted to this user. The most important permissions are at the very bottom and it is very easy to forget about them.
