### ISSUE TITLE
Bug: blockedlog prevents invoice validation

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#7905]
Invoice creation and validation is working perfectly well.
However, once the experimental blockedlog module is activated, it is not possible to validate an invoice. Dolibarr show a HTTP ERROR 500 once validation is confirmed.

## Environment
- **Version**: 7.0 beta (from github zip file)
- **URL(s)**: compta/facture/card.php?facid=40&action=confirm_valid&confirm=yes

**Comment by eldy** [comment]
Do you have errors in your apache errors.log file ?

**Comment by vvnt** [comment]
Yes.
Log :

[Wed Dec 06 00:56:50.437438 2017] [:error] [pid 885] [client 192.168.131.1:57295] PHP Fatal error:  Uncaught Error: Call to undefined function getRandomPassword() in /var/www/html/dolibarr/htdocs/blockedlog/class/blockedlog.class.php:656\nStack trace:\n#0 /var/www/html/dolibarr/htdocs/blockedlog/class/blockedlog.class.php(569): BlockedLog->getSignature()\n#1 /var/www/html/dolibarr/htdocs/blockedlog/class/blockedlog.class.php(426): BlockedLog->getPreviousHash(1)\n#2 /var/www/html/dolibarr/htdocs/core/triggers/interface_50_modBlockedlog_ActionsBlockedLog.class.php(86): BlockedLog->create(Object(User))\n#3 /var/www/html/dolibarr/htdocs/core/class/interfaces.class.php(173): InterfaceActionsBlockedLog->runTrigger('BILL_VALIDATE', Object(Facture), Object(User), Object(Translate), Object(Conf))\n#4 /var/www/html/dolibarr/htdocs/core/class/commonobject.class.php(4343): Interfaces->run_triggers('BILL_VALIDATE', Object(Facture), Object(User), Object(Translate), Object(Conf))\n#5 /var/www/html/dolibarr/htdocs/compta/facture/class/facture.class.php(2272): CommonObject->call_trigger('BILL_VALIDATE', Object(User))\n#6 /var/www/h in /var/www/html/dolibarr/htdocs/blockedlog/class/blockedlog.class.php on line 656, referer: http://192.168.131.116/dolibarr/htdocs/compta/facture/card.php?facid=230&action=valid

**Comment by vvnt** [comment]
Same error with another OS (Debian 9) and fresh install of Dolibarr 7 beta (no data migration).

**Comment by ghost** [comment]
fix by #8007

**Comment by vvnt** [comment]
Great ! Thanks a lot. :)
