### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#7906]
# Bug

## Environment
- **Version**: 6.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.32
- **Database**: MySQL or MariaDB 5.6.38
- **URL**: /fourn/commande/card.php?id=2&action=editline&lineid=3

## Report
Error HTTP 500.

**Comment by eldy** [comment]
Can you read your apache error.log file and report content ?
