### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#7907]
# Bug

## Environment
- **Version**: 6.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.32
- **Database**: MySQL or MariaDB 5.6.38
- **URL**: /compta/facture/list.php

## Report
https://erp.kreasiestetika.com/compta/facture/list.php#show_files

Cannot merge PDF

**Comment by eldy** [comment]
Can you provide a screenshot of error page ?
