### ISSUE TITLE
Feature request : Delete deprecated html attributes

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7908]
# Instructions
Replace all old attributes as align="left|right|center" with css

# See
https://www.w3.org/TR/html5/obsolete.html

**Comment by torvista** [comment]
I have been doing this as I go along, but really there should be a single, global find and replace done on all these, to change them to 
style="text-align: left|center|right".
Why bother?
All developers should be using a html validator and these attributes are deprecated in html5.
Having so many of them appear in the validator error output makes one less likely to spot and fix "real" errors of invalid html.
I know this affects 100's of files but it has to be done sometime and currently many files are being modified with minor formatting so this should be done now. It's a few seconds work!
