### ISSUE TITLE
Feature Request: REST API cannot create/update/delete thirdparties_bankaccounts ?

### ISSUE THREAD

**Issue by vincib** [Dolibarr/dolibarr#7909]
# Feature Request

It seems that the llx_societe_rib can't be edited through the API. 
We are using dolibarr on a customer control panel using pdo_query since v1.x (upgraded to 3.4.1 in 2013 and upgraded to 6.0.3 recently) and wanted to use the API instead. We migrated to 6.0.3 but this version's REST API doesn't include something like **/thirdparties/{id}/accounts/** to manage bank accounts of customers 

## Use case

automation of SEPA wire transfer requires us to fill the llx_societe_rib / thirdparty-bank-account information, get back the RUM / sepa status etc. 

## Suggested implementation

add a /thirdparties/{id}/accounts REST endpoint to get/add/update/delete customer's bank accounts.

_business footnote: we may be able to develop it (we may need a bit of help to do it well) or pay someone who knows and contribute to Dolibarr to develop it, feel free to contact me then._

**Comment by zigastegu** [comment]
![image](https://user-images.githubusercontent.com/1379063/77491543-574e5300-6e3e-11ea-84fd-1f5c38b76309.png)

**Comment by dpriskorn** [comment]
It seem like thus is now implemented.  Closing.
