### ISSUE TITLE
BUG Retard Event, Fiche Tier

### ISSUE THREAD

**Issue by Soundstriker** [Dolibarr/dolibarr#7912]
# Instructions

# Bug
Quelles que soient les versions, dans le listing évents, dans fiche TIER, même si la date de l'évent est en dehors de la période d'alerte, il apparait à côté de la date un panneau retard.

## Environment
- **Version**: 6.0.3
- **OS**:  Linux erp 2.6.32-5-xen-amd64 #1 SMP Tue May 13 18:41:58 UTC 2014 x86_64
- **Web server**: Apache/2.2.16 (Debian)
- **PHP**: 5.3.3-7+squeeze19
- **Database**: MySQL or MariaDB 5.1.73-1
- **URL(s)**: /dolibarr/societe/agenda.php?socid=1040

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![dolibarr bug event](https://user-images.githubusercontent.com/34269944/33603241-319a0e1a-d9b2-11e7-81bb-77ce469cf055.PNG)
![dolibarr bug event 2](https://user-images.githubusercontent.com/34269944/33603245-35fcf274-d9b2-11e7-985b-583cb2f6b36f.PNG)
![dolibarr bug event 3](https://user-images.githubusercontent.com/34269944/33603247-37866b34-d9b2-11e7-9506-57eef013d21c.PNG)

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by eldy** [comment]
The record seems created with an import.
Do you have same trouble if event is created manually from gui ?

**Comment by Soundstriker** [comment]
yes I have exactly the same problem if I create an event on a non imported card. :(

**Comment by atm-maxime** [comment]
Fixed in #7936. Issue was there since 5.0
