### ISSUE TITLE
Error in dynamics prices

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#7914]
# Bug
Expressions in dynamic prices do not work

## Environment
- **Version**:6.0.3
- **OS**: Linux us-imm-web76.main-hosting.eu 2.6.32-673.26.1.lve1.4.30.el6.x86_64 #1 SMP Wed Jun 21 19:37:37 EDT 2017 x86_64
- **Web server**: Apache
- **PHP**: 5.5.38
- **Database**: MySQL or MariaDB 10.1.29-MariaDB
- **URL(s)**: http://gestion-dica.is-dica.com/htdocs/product/fournisseurs.php?id=XXXX&action=add_price

## Expected and actual behavior
It is expected that after the expression of price use is created, the system makes the calculation defined. When I create the expression in the editor I save it correctly, but when I try to use the expression I get the legend: illegal character "#".

## Steps to reproduce the behavior
For example:
I use the price editor and I enter a title for the price and an expression where I calculate the price based on the weight of the article, so I insert the following expression:
price=#weight#*#supplier_min_price#
But when I try to use it when creating the price of the article, I get the error already indicated: illegal character "#"
I already try variations with the expression, alternating #, removing them, with space, without them, etc. but only a series of errors and it still does not work.
After several attempts now it is impossible for me to create expressions that insert variables since the system tells me:
Variable 'null' indefinite

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![2017-12-06](https://user-images.githubusercontent.com/28205134/33661145-36a29db0-da4c-11e7-9d84-01cae621cc4a.png)

**Comment by IonAgorria** [comment]
Occurs when you try to use a variable that has no value, for example weight when product has no weight defined

**Comment by julbroa-zz** [comment]
but if I have defined that data in the product file, and even then I get that error
![error doli](https://user-images.githubusercontent.com/28205134/33725728-9a681180-db38-11e7-9ddc-a669c1f51433.png)
