### ISSUE TITLE
Bug generating PDF

### ISSUE THREAD

**Issue by tchao57** [Dolibarr/dolibarr#7928]
# Instructions
Hi all,
I've have a bug when generating a PDF from propale or everything else.

# Bug
I open the generated PDF and Adobe Reader say me that is an error in the page. The Logo isn't there, then I think it's a logo issue. When I delete the Logo from the Dolibarr config all is good, the PDF is OK, no error.

## Environment
- **Version**: 3.8.3 (No changes made)
- **OS**: 
- **Web server**: OVH Mutualise
- **PHP**: 5.5.38
- **Database**: MySQL
- **URL(s)**: 

## Steps to reproduce the behavior
Generate PDF from propale etc.

**Comment by tchao57** [comment]
Ok, I just found the solution.
Really strange but... I put a Logo in JPG and voila. Before, I had Logo in PNG working for 2 years and today for no reason it doesn't work. Without changes...

**Comment by atm-maxime** [comment]
Strange indeed. But something must have changed, either the logo or the PDF reader... Glad you found a solution. I close the issue
