### ISSUE TITLE
Bug : PhP 7.2.0 count() warning in errorlog

### ISSUE THREAD

**Issue by Bagu** [Dolibarr/dolibarr#7932]
# Bug
With PHP 7.2.0 a warning is thrown in errorlog : count(): Parameter must be an array or an object that implements Countable in \societe\list.php on line 1055

## Environment
- **Version**: 6.0.4
- **OS**: Windows 10 64bit Pro
- **Web server**: Apache 2.4.29 64bit
- **PHP**: 7.2.0 64bits
- **Database**: MariaDB 10.2.11 64bits

**Comment by ttobsen** [comment]
See https://github.com/Dolibarr/dolibarr/issues/9074#issuecomment-411481547
