### ISSUE TITLE
BUG: Multi line address in site company is not stored correctly

### ISSUE THREAD

**Issue by jprogin** [Dolibarr/dolibarr#7947]
You can input a multi line address in the `admin/company.php` form but it will not be stored correctly

**Comment by jprogin** [comment]
Need to change line 77:
`dolibarr_set_const($db, "MAIN_INFO_SOCIETE_ADDRESS", GETPOST("address",'nohtml'),'chaine',0,'',$conf->entity);`

Replace **nohtml** with **none**

**Comment by PeterCodar** [comment]
@jprogin Your change seems to work 
(but I have no idea, what kind of side effects your change can have)

**Comment by jprogin** [comment]
No side effect observed until now: the reporting tools seem to work well with multi line company address...

**Comment by PeterCodar** [comment]
Thanks @jprogin !

It would be better anyway, if this address lines would be separated. Everything that needs a structured address (including payment slips or QR codes) would highly benefit, if we could map every addressline 1:1 including separate streetname, streetnumber etc.

**Comment by jprogin** [comment]
You agree that it is weird to have a multiline input field to input the company address if it is not stored multiline behind... The proposed fix is quick and easy, and seems to work. Why not include this fix and maybe later redesign?
