### ISSUE TITLE
[Feature] [Legal] [EU] [RGPD] Help anonymise or delete personal data.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#7948]
With regards to https://www.cnil.fr/fr/declaration/ns-048-fichiers-clients-prospects-et-vente-en-ligne and the European Regulation 2016/679 regarding the protection of personal data (GDPR, http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32016R0679), add features to Dolibarr to enable the ease of obiding by it.

The French CNIL says to:
- Anonymize or delete personal data after 3 years;
- If data must be maintained for reasons of proof (contract, etc): maintain it clearly separated from the other data.

Extract of https://www.cnil.fr/fr/declaration/ns-048-fichiers-clients-prospects-et-vente-en-ligne (fren)::

> Toutefois, les données permettant d’établir la preuve d’un droit ou d’un contrat, ou conservées au titre du respect d’une obligation légale, peuvent faire l’objet d’une politique d’archivage intermédiaire pour une durée n’excédant pas la durée nécessaire aux finalités pour lesquelles elles sont conservées, conformément aux dispositions en vigueur (notamment mais non exclusivement celles prévues par le code de commerce, le code civil et le code de la consommation). **Il convient de prévoir à cet effet une base de données d’archives dédiée ou une séparation logique dans la base de données active, après avoir opéré un tri des données pertinentes à archiver.**

Dolibarr could help to identify data that has not been updated since 3 years, suggest the fields that should be deleted or anonymised, and move or tag data that must be kept for legal reasons.  Tagged data would no longer be shown by default and only when the hidden field is clicked for instance.

Edit:
I manually verified the database and I have "fused/joined" (French: Fusion) several entries with a special Third Party that I called "ARCHIVE".  After the fusion I deleted the personal entries.  The invoices are therefore maintained in the Archive Third Party where personal data may be present in the invoices, but at least not searchable and limited to the information on the invoice.

**Comment by Alexconquer** [comment]
Indeed, it is important that dolibarr support the new European regulations.
is there any new information on this?

**Comment by mdeweerd** [comment]
I am closing this one due to #8612 which has been labeled properly.
