### ISSUE TITLE
Logs inaltérables 

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#7966]
# Bug
Le module ne s'active pas

## Environment
- **Version**:  develop (7)
- **OS**: LAMP
- **URL(s)**: /htdocs/admin/modules.php?id=3200&module_position=500&action=set&value=modBlockedLog&mode=common&search_status=&search_nature=&search_version=&page_y=2829

## Error message
stderr: PHP Fatal error:  Call to undefined function getRandomPassword() in htdocs/blockedlog/class/blockedlog.class.php on line 742, referer: htdocs/admin/modules.php?mainmenu=home

## Steps to reproduce the behavior
activer le module Logs inaltérables

**Comment by vvnt** [comment]
Same bug as #7905.
