### ISSUE TITLE
Feature Request: Would be nice to have an option for issuing a Supplier Order in either supplier's currency or in (my) company's currency

### ISSUE THREAD

**Issue by MartinHold** [Dolibarr/dolibarr#7967]
# Feature

## Environment
- **Version**: 6.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.32
- **Database**: MySQL or MariaDB 5.6.23-cll-lve
- **URL**: /ERP/fourn/commande/card.php?id=8

## Report
Feature request to allow issuing a Supplier Order in either supplier's or (my) company's currency

**Comment by atm-maxime** [comment]
Can you give some more details please ? To me while creating your supplier order you can choose the currency.
