### ISSUE TITLE
Bug : Expense reports statistics

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#7973]
## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**:expensereport/index.php

## Bug
I use a lot of predefined entries in llx_c_type_fees in order to match with our accountant. But as we can see in the screenshot the statistics picture goes wrong.

## Screenshot
![screencapture-dolibarr6-expensereport-index-php-1513671169355](https://user-images.githubusercontent.com/24292300/34147525-49c0be5c-e49e-11e7-9d24-9c54e9b34e15.png)

Tks for reading

**Comment by aljawaid** [comment]
This issue still exists in v7.0.4

**Comment by aljawaid** [comment]
#5984
