### ISSUE TITLE
BUG : Contract - Invalid reference on the document

### ISSUE THREAD

**Issue by FredSau** [Dolibarr/dolibarr#7974]
# Bug
In the PDF document from a contract, the REF properties does not contain the contract reference but "(PROVn)"

## Environment
- **Version**: 6.0.4
- **OS**: Linux
- **Web server**: Appach
- **PHP**: 7.0.24
- **Database**: MySQL or MariaDB 5.5.5-10.1.29
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
On the contract document I hope to have the contract reference but now we have "PROVn" - cfr attach
The name of the file seems to be ok.

## Steps to reproduce the behavior
Create and valid a contract, and look the generated document

## 
[*Files*]
![2017-12-19 15_10_55-contrats](https://user-images.githubusercontent.com/28922490/34160853-df08bad4-e4ce-11e7-9038-57ab1b8784cc.png)
![2017-12-19 15_10_20- prov4](https://user-images.githubusercontent.com/28922490/34160854-df21efb8-e4ce-11e7-9b00-67bc5db07042.png)

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by atm-maxime** [comment]
Ok I reproduced. This is because for now, PDF is not automatically regenerated after contract validation, unlike other elements. The file is only renamed. If you regenerate, the correct ref is in the PDF.
