### ISSUE TITLE
Warning in viewcat.php

### ISSUE THREAD

**Issue by njacquemin** [Dolibarr/dolibarr#7993]
# Bug
A warning about $events should be an array or an object that implements Countable in core/lib/ajax.lib.php on line 417, so a problem with $events in ajax_combobox.

## Environment
- **Version**: 6.0.3
- **OS**: Windows 7
- **Web server**: Apache 2.4
- **PHP**: 7.2
- **Database**: MariaDB 10
- **URL(s)**: /categories/viewcat.php?id=1&type=0

## Steps to reproduce the behavior
Well, I've started a new setup, activate modules, create products, create categories, add products to categories... Like all the previous installations I've done.

## [Attached files]
![bug_dolibarr](https://user-images.githubusercontent.com/11017930/34352539-7841beb8-ea23-11e7-9cb8-1044a7ab12a6.PNG)

**Comment by atm-maxime** [comment]
Strange, I can't reproduce... $event is null, but my PHP says that count(null) = int(0). I don't know why you have this error...

**Comment by njacquemin** [comment]
I really don't know. Never had this warning before. I'll try a new install tomorrow.

**Comment by njacquemin** [comment]
**UPDATE 2017.12.27 :** Well... New install and same warning.
