### ISSUE TITLE
DB_ERROR_1071 on initial creation of multiple llx tables

### ISSUE THREAD

**Issue by deki** [Dolibarr/dolibarr#7997]
# Bug
While doing a fresh install of dolibarr I'm still seeing several SQL errors similar to the ones previously reported in #3772.

> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_advtargetemailing.key
> Request 280 : ALTER TABLE llx_advtargetemailing ADD UNIQUE INDEX uk_advtargetemailing_name (name) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_bookmark.key
> Request 299 : ALTER TABLE llx_bookmark ADD UNIQUE uk_bookmark_url (fk_user, url) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_boxes_def.key
> Request 306 : ALTER TABLE llx_boxes_def ADD UNIQUE INDEX uk_boxes_def (file, entity, note) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_budget_lines.key
> Request 307 : ALTER TABLE llx_budget_lines ADD UNIQUE INDEX uk_budget_lines (fk_budget, fk_project_ids) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_c_email_templates.key
> Request 326 : ALTER TABLE llx_c_email_templates ADD UNIQUE INDEX uk_c_email_templates(entity, label, lang) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_c_ziptown.key
> Request 352 : ALTER TABLE llx_c_ziptown ADD UNIQUE INDEX uk_ziptown_fk_pays (zip, town, fk_pays) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_categorie.key
> Request 353 : ALTER TABLE llx_categorie ADD UNIQUE INDEX uk_categorie_ref (entity, fk_parent, label, type) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_commande_fournisseur.key
> Request 415 : ALTER TABLE llx_commande_fournisseur ADD UNIQUE INDEX uk_commande_fournisseur_ref (ref, fk_soc, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_const.key
> Request 428 : ALTER TABLE llx_const ADD UNIQUE INDEX uk_const (name, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_default_values.key
> Request 455 : ALTER TABLE llx_default_values ADD UNIQUE INDEX uk_default_values(type, entity, user_id, page, param) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_ecm_files.key
> Request 463 : ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files (filepath, filename) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_element_tag.key
> Request 472 : ALTER TABLE llx_element_tag ADD UNIQUE INDEX uk_element_tag (entity, lang, tag, fk_element, element) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_entrepot.key
> Request 473 : ALTER TABLE llx_entrepot ADD UNIQUE INDEX uk_entrepot_label (label, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_facture_fourn.key
> Request 516 : ALTER TABLE llx_facture_fourn ADD UNIQUE INDEX uk_facture_fourn_ref (ref, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_facture_fourn.key
> Request 517 : ALTER TABLE llx_facture_fourn ADD UNIQUE INDEX uk_facture_fourn_ref_supplier (ref_supplier, fk_soc, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_links.key
> Request 571 : ALTER TABLE llx_links ADD UNIQUE INDEX uk_links (objectid,label) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_menu.key
> Request 586 : ALTER TABLE llx_menu ADD UNIQUE INDEX idx_menu_uk_menu (menu_handler, fk_menu, position, url, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_product.key
> Request 623 : ALTER TABLE llx_product ADD UNIQUE INDEX uk_product_barcode (barcode, fk_barcode_type, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_product_attribute.key
> Request 629 : ALTER TABLE llx_product_attribute ADD UNIQUE INDEX uk_product_attribute_ref (ref) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_product_attribute_value.key
> Request 630 : ALTER TABLE llx_product_attribute_value ADD CONSTRAINT unique_ref UNIQUE (fk_product_attribute,ref) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_societe.key
> Request 703 : ALTER TABLE llx_societe ADD UNIQUE INDEX uk_societe_barcode (barcode, fk_barcode_type, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_user_param.key
> Request 742 : ALTER TABLE llx_user_param ADD UNIQUE INDEX uk_user_param (fk_user,param,entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Erstellen der Fremdschlüssel und Indizes für Tabelle llx_usergroup.key
> Request 746 : ALTER TABLE llx_usergroup ADD UNIQUE INDEX uk_usergroup_name (nom, entity) 	SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> 
> 

Could you please apply a similar fix for these statements?

## Environment
- **Version**: 6.0.4-4 (debian package)
- **OS**: ubuntu-xenial-16.04-amd64-server-20171026.1
- **Web server**: Apache 2.4.18
- **PHP**:  7.0.22-0ubuntu0.16.04.1
- **Database**: 10.0.31-MariaDB-0ubuntu0.16.04.2
- **URL(s)**: /dolibarr/install/step2.php

**Comment by hregis** [comment]
@deki 
change the collation of your database from utf8mb4_****  to utf8_general_ci

**Comment by deki** [comment]
Thanks for the hint but as far as I know this one should not be used. See discussion: https://stackoverflow.com/a/766996/3156607

**Comment by eldy** [comment]
Using utf8mb4 for pagecode is a very bad idea. It means chars need 4 bytes to store one byte but the minimum size of index was not increased by mysql/mariadb, still limited to 767 bytes. This means that if you use utf8mb4 you can't use char fields larger than 191 bytes, where the same database allows this field to be 250 chars long.
The only solution offered by the database engine for such need is to not use index. For this reason, usage of utf8mb4 must not be considered as a ready to use pagecode.

Until this is fixed by maria/mysql, recommended page code is utf8_unicode_ci
(We don't need the extra chars provided by utf8mb4)

**Comment by deki** [comment]
Ok I see, thanks for the detailled explanation.
