### ISSUE TITLE
Impossible to create a bank account without accounting code

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8005]
# Bug
impossible to create when advanced accounting module is on
Le champ 'Compte comptable' est obligatoire

## Environment
- **Version**: 7.0 beta
- **URL(s)**: compta/bank/card.php

## Expected and actual behavior
Should be a warning, creating account and then giving its account number

## Steps to reproduce the behavior
activate advanced accounting
create a bank account

If switching to simple accounting same problem
Why needing an accounting number ?

**Comment by atm-maxime** [comment]
I reproduced the issue. It seems right to me that if advanced accounting is enabled, bank accounting number is required. Issue is that advanced accounting seems to activate this option : MAIN_BANK_ACCOUNTANCY_CODE_ALWAYS_REQUIRED, and it's still present after module inactivation

**Comment by tiaris** [comment]
Yes it seems so.
But I think it should be a simple warning with advanced accounting, and account should be created allways.

**Comment by atm-maxime** [comment]
Is this still an issue or can we close it ?
