### ISSUE TITLE
# Bug Vers. 6.0.3 and 6.0.4 - Setup -> Display / Save Button is not available

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8015]
# Bug
In Version 6.0.3 and still 6.0.4
If you press the modify button in Setup - Display you can edit the parameter. But there is no Save Button avaulable to save the changes.

**Comment by atm-maxime** [comment]
This works for me, the 2 buttons "Save" and "Cancel" are present in "htdocs/admin/ihm.php?action=edit" at the bottom of th form. Please provide a screenshot.
