### ISSUE TITLE
Bug: Tags module is enabled but grayed out

### ISSUE THREAD

**Issue by r9guy** [Dolibarr/dolibarr#8020]
# Bug

## Environment
- **Version**: 6.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.7
- **Database**: MySQL or MariaDB 5.6.37-log
- **URL**: /erp/compta/bank/transfer.php?leftmenu=

**Comment by atm-maxime** [comment]
Works for me in 6.0.5, I can add tags to my bank account Can you check your rights and give a screenshot ?

**Comment by r9guy** [comment]
I apologies for wrong submission. it was a permission issue.
