### ISSUE TITLE
Unable to add bank entry with double quotes in Description

### ISSUE THREAD

**Issue by jeromelebleu** [Dolibarr/dolibarr#8023]
# Bug
I have the error `Field 'Label' is required` when I try to add a new bank entry with `"test" label` as **Description**.

## Environment
- **Version**: 6.0.4
- **OS**: Debian Stretch
- **Web server**: NGINX + PHP-FPM
- **PHP**: 7.0.19
- **Database**: MariaDB 10.1.26
- **URL(s)**: compta/bank/bankentries.php

## Steps to reproduce the behavior

1. Go to *Bank/Cash* and select a **Bank account**
2. Go to the **Bank entries** tab
3. Click on the **Add entry** button
4. Fill the fields and set for example `"test" label` for the **Description** field, or another value with some `"` inside
5. Click on the **Add** button

## Debugging information

When I fill the **Description** with `label "test" label`, here is the resulting field after the form submission:
```html
<input name="label" class="flat" size="24" value="label " test"="" label"="" type="text">
```
... and with `"test" label`:
```html
<input name="label" class="flat" size="24" value="" test"="" label"="" type="text">
```

It seems that the value is not escaped...

**Comment by jeromelebleu** [comment]
I take a look at `htdocs/compta/bank/bankentries.php` source code and compared it with 5.0 - since this bug doesn't exist in it - and 6.0 branch. I think this bug was introduced by the `GETPOST` function in the `$code='alpha'` check - [there](https://github.com/Dolibarr/dolibarr/blob/6.0/htdocs/core/lib/functions.lib.php#434) - since it just rejects any `"` from the string, which corresponds to the error...

As this behavior is still the same in the `develop` branch, could it be an alternative to allow `"` again in a string? Also, why not escaping it instead?

Thanks in advance!

**Comment by atm-arnaud** [comment]
Hello,

I'm currently working on this issue.

Regards,
