### ISSUE TITLE
Replace a customer invoice with discounts

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#8028]
# Instructions
* Create an invoice for a customer. (eg : _OUT15-980756_)
* Add some fix discounts on it.
* Create a replacement invoice for the invoice _OUT15-980756_
![image](https://user-images.githubusercontent.com/3658458/34600387-81d34948-f1f7-11e7-9f9b-6448ae110f80.png)

# Bug
The systems doesn't create the replacement invoice because some discounts are already used.

## Environment
- **Version**: 6.0.4, (maybe the other too)

## Solution
Actually I don't know which solution is the best one. Here some solutions:

1. We create the replacement invoice without discounts, up to the user to create new discounts and apply them.
2. We duplicate discounts and apply them on the replacement invoice.

@eldy do you have a better idea ? To which solution do you prefer to go ?
FYI : I can fix it myself

**Comment by laudeco** [comment]
@eldy on which branch am I suppose to fix it ? Develop ? 6.0 ? 

Kind regards
L.

**Comment by atm-maxime** [comment]
Has it been fixed ? Please close the issue
