### ISSUE TITLE
unable to store extrafield 

### ISSUE THREAD

**Issue by mlhostis** [Dolibarr/dolibarr#8033]
# Bug
Unable to store extra field

## Environment
- **Version**: [*5.04*]

## Expected and actual behavior
[*When we try to modify one of the extrafield, the field is not updated in one of the other extra field is mandatory and not filled. The form on dolibarr object permet to change extra field one by one*]

## Steps to reproduce the behavior
[*This issue occur only for existing object when the mandatory extra field is added*]

## Suggested implementation
add setEventMessages on SQL errors in core/commonobject.class.php

line 4336:
dol_syslog(get_class($this)."::insertExtraFields insert", LOG_DEBUG);
            $resql = $this->db->query($sql);
            if (! $resql)
            {
                $this->error=$this->db->lasterror();
                $this->db->rollback();
				setEventMessages("Modification impossible, vérifier les parametres obligatoires", null, 'errors');
                return -1;
            }

**Comment by frederic34** [comment]
This is an old version, if this subsist in recent version, please reopen issue.
