### ISSUE TITLE
Products: Double-quote character (") in Label causes truncated label in translation

### ISSUE THREAD

**Issue by hameau** [Dolibarr/dolibarr#8037]
# Bug
Updating a product translation that includes a double-quote (") character in the product label causes the product label to be truncated before the ".

## Environment
- **Version**: 6.0.5 (public demo) and earlier 6.0.x
- **OS**: Public demo
- **Web server**: Public demo
- **PHP**: Public demo
- **Database**: Public demo
- **URL(s)**: product/traduction.php?action=edit

## Expected and actual behavior
**Expected**: Updating the translation of product details should not change the existing product label(s).

**Actual**: If the existing product label contains a " character, **updating** a translation causes the label to be truncated before the " character for any existing translation.

## Steps to reproduce the behavior
1. Create or edit a product (product/card.php), such that the Label field includes a double-quote character, example:  
*HDD 3½" 500 GB*
2. Open the Translation tab (product/traduction.php) and note that the product label has not changed.
3. Click the Update button, as if to change an existing translation. Note that the example label is now truncated:  
*HDD 3½*
4. If the 'Save' button is clicked, the original product label is changed.

In the translation tab (product/traduction.php), it is possible to *add a translation* that includes a " character. It is the action of clicking the *translation Update* that causes existing product label(s) to be truncated.

**Comment by atm-quentin** [comment]
Hello,

 I'm working on this
