### ISSUE TITLE
Bug #8038 Mass delete products is limited to 982 products

### ISSUE THREAD

**Issue by c3do** [Dolibarr/dolibarr#8038]
#Bug
Hello.
I tried with 1000 products and 5000 products. In both, dolibarr asks me if i am sure i want to remove 982 products. i confirm. and only 982 products are removed. i think http Get request limit is reached, the url is too long.
Regards.

**Comment by atm-maxime** [comment]
Hello,
Based on your description, this is not a Dolibarr issue, this is related to your server limits.

**Comment by c3do** [comment]
Hello, the url lenght limit is almost the same for everyone. It is a browser limit. Please take a look at this topic: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
The GET request should be split if the limit of 2000 characters is reached.
