### ISSUE TITLE
BUG: Unable to get confirmation window for actions

### ISSUE THREAD

**Issue by RafaelBarcos** [Dolibarr/dolibarr#8039]
I have Dolibarr 6.0.3 local installed and 6.0.4 on-line on a web provider. Trying to validate an invoice, I encountered the problem that the little window asking if I'm sure to validate the invoice doesn't appear. This also happens for delete actions of quotes and invoices. I tried the same action in the local installed version and all works fine. I had in the past issues with other points and needed to import data to the SQL database so to remove any possible issue coming from that, I set an empty new database with a full new installation of the 6.0.4 version. However, the issue stays after a fresh installed system without any import. My feeling lets me think that a little hidden parameter is avoiding the window to appear. Browser is working fine locally. I don’t have a lot of experience with Dolibarr so that I can't exclude a bad configuration from my side. Thanks a lot for help.

**Comment by ghost** [comment]
This problem often occurs on JavaScript error. The pop up confirm box is Javascript (Jquery)confirm box. If you display console error with "Inspect" feature of your browser you should find some explanation of this problem.

**Comment by RafaelBarcos** [comment]
Thanks for the info. THere is a lot of Error messages, do you think one should be followed of these:

SyntaxError: missing ; before statement
[Learn More]
jquery.min.js:3:673
SyntaxError: illegal character
[Learn More]
jquery-ui.min.js:6:15251
ReferenceError: jQuery is not defined
[Learn More]
jquery.tablednd.0.6.min.js:1:183
ReferenceError: jQuery is not defined
[Learn More]
jquery.tipTip.min.js:21:2
ReferenceError: jQuery is not defined
[Learn More]
jquery.jnotify.min.js:21:2
ReferenceError: $ is not defined
[Learn More]
jnotify.js:24:1
ReferenceError: jQuery is not defined
[Learn More]
jquery.flot.min.js:7:2
ReferenceError: jQuery is not defined
[Learn More]
jquery.flot.pie.min.js:7:2
ReferenceError: jQuery is not defined
[Learn More]
jquery.flot.stack.min.js:7:2
ReferenceError: jQuery is not defined
[Learn More]
select2.min.js:21:1
ReferenceError: jQuery is not defined
[Learn More]
select2_locale.js.php:20:1
ReferenceError: jQuery is not defined
[Learn More]
lib_head.js.php:885:1
ReferenceError: $ is not defined
[Learn More]
datepicker.js.php:12:1
ReferenceError: $ is not defined
[Learn More]
card.php:91:10
ReferenceError: $ is not defined
[Learn More]
card.php:100:10
ReferenceError: jQuery is not defined
[Learn More]
card.php:232:1
ReferenceError: $ is not defined
[Learn More]
card.php:306:1
ReferenceError: $ is not defined
[Learn More]
card.php:332:10
ReferenceError: $ is not defined
[Learn More]
card.php:382:16
ReferenceError: jQuery is not defined
[Learn More]
card.php:463:2
ReferenceError: $ is not defined
[Learn More]
card.php:725:10
ReferenceError: $ is not defined
[Learn More]
card.php:735:10
ReferenceError: jQuery is not defined
[Learn More]
card.php:751:5
ReferenceError: jQuery is not defined
[Learn More]
card.php:778:1
ReferenceError: $ is not defined
[Learn More]
card.php:797:7
ReferenceError: jQuery is not defined
[Learn More]
card.php:861:14
ReferenceError: jQuery is not defined
[Learn More]
card.php:877:17
ReferenceError: jQuery is not defined
[Learn More]
card.php:888:17

**Comment by ghost** [comment]
That's it, as Jquery cannot be loaded Dolibarr cannot work correctly. How did you install Dolibarr ? Did you clone into empty directory the github repository with "git clone" command ? It is highly recommended to use this to install Dolibarr on linux server.
Into network console (always from inspect braowser feature) do you find some 404 error ?
As you said, it work locally but not on your server. It means you miss something during your deployment process of Dolibarr on your server.

**Comment by RafaelBarcos** [comment]
For the installation, I copied the Dolibarr package: https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/ and followed the installation of Dolibarr. Should I do it in another way? I don't find 404 errors, but sometimes, little errors occure. If you have a recommended installation procedure, I would be happy to try it. Thanks a lot.

**Comment by RafaelBarcos** [comment]
Please note that tall this issue is based on the files transfer that was in ASCII instead of binary. By FTP settings, please setup binary. Thanks a lot to Florian for his help
