### ISSUE TITLE
Automatica calculation in products

### ISSUE THREAD

**Issue by amoreira1** [Dolibarr/dolibarr#8042]
Hi all
I work in a rug company and it would be very simple the following when we create a new product :

we work with lenght width and price . if we could introduce each item and we have autoaticly the final price, that could be excellent ~.

Is thre anyway in extrafields we do that ?

Thanks

**Comment by amoreira1** [comment]
Hi all 
I work in a rug company and it would be very simple the following when we create a new product : 

we work with lenght width and price . if we could introduce each item and we have autoaticly the final price, that could be excellent ~.

Is thre anyway in extrafields we do that ?

Tanks

**Comment by dolibarr95** [comment]
Hi
It could be solved like this : 
create product X, price 5$/m²
Add line in the order product x quantity 27.5 (27.5m² -> 137.5)

**Comment by amoreira1** [comment]
Hi
Thanks for your reply.
I thnk that i didnt make clear in my post . 
I would like to introduce lenght in a collun then width in another collun and then price in another collun and get automaticly the total price  ( Length * Width * price )
Is there  anyways whrn we add  a complementary attibute to introduce this calculation ?
Thanks in advance

**Comment by dolibarr95** [comment]
You should post in english forum _(dolibarr.org/forum)_ or french forum _(dolibarr.fr/forum)_
to check if there is a external module or tricks to do it then post here if not.
;-)

**Comment by amoreira1** [comment]
thanks.
Unfortunally here arent in booth of them

**Comment by braito4** [comment]
Check de module: dynamic prices

**Comment by amoreira1** [comment]
Thanks for your reply .

Where can i find the module of dynamic prices

Thanks in advance 

 

De: Braito [mailto:notifications@github.com] 
Enviada: 10 de janeiro de 2018 13:36
Para: Dolibarr/dolibarr <dolibarr@noreply.github.com>
Cc: amoreira1 <antonio.manuel@moreira.pt>; Author <author@noreply.github.com>
Assunto: Re: [Dolibarr/dolibarr] Automatica calculation in products (#8042)

 

Check de module: dynamic prices

**Comment by dolibarr95** [comment]
;)
https://www.dolibarr.fr/forum/3-installation/60730-calcuk-prix-de-vente-par-un-coeficiant

**Comment by dolibarr95** [comment]
;)
https://www.dolibarr.fr/forum/15-retours-dexperiences-utilisateursintegrateurs/59600-fabrication-de-pieces-en-bois-comment-faire
