### ISSUE TITLE
Error creating Company Societe::Create fails verify Email

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8043]
# Bug
creation of third party fails if email is allready used

## Environment
- **Version**: 7.0 beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.0
- **Database**: [*Database type and version*]
- **URL(s)**: /societe/card.php

## Expected and actual behavior
When creating a third party with an email that already is in Dolibarr and the configuration that email is must be unique is not set in /societe/admin/societe.php
creation fails with message 
Societe::Create fails verify Email jean@tiaris.info est attribu&eacute; &agrave; un autre tiers (ForbiddenBySetupRules)

Of course if the email must be unique is set, this behaviour is right

## Steps to reproduce the behavior
create a third party with an email
check that configuration of email to be unique is not set
create a second third party with same email

**Comment by baudday** [comment]
Still running into this in 7.0.1 stable. Looks like the PR that was referenced as a fix for this was never merged. Any word on how to fix this?
