### ISSUE TITLE
#BUG DO NOT PERFORM POSITIVE BALANCE MANAGEMENT IN PROVIDER INVOICES

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#8044]
# Bug
THE PROVIDER INVOICES WHERE THERE IS A PAYMENT GREATER THAN THE TOTAL INVOICE, DO NOT AUTOMATICALLY GENERATE A PAYMENT AND IT IS NOT POSSIBLE TO MANAGE FUTURE INVOICES WITH THAT POSITIVE BALANCE.

## Environment
Version:6.0.3
OS: Linux us-imm-web76.main-hosting.eu 2.6.32-673.26.1.lve1.4.30.el6.x86_64 #1 SMP Wed Jun 21 19:37:37 EDT 2017 x86_64
Web server: Apache
PHP: 5.5.38
Database: MySQL or MariaDB 10.1.29-MariaDB

## Expected and actual behavior
EXPECTED:
When a supplier invoice is generated and the payment is made, if this is greater than the amount of the invoice, a positive balance is generated with which it is possible to cover future purchases or request a refund.
CURRENT:
The expected positive balance is not generated and the amount that was paid with a higher payment remains open and with a negative balance. If you try to use that balance, it is not possible to apply it as payment (this function was available, but bad memory, in version 4 of Dolibarr, where if you made a payment greater than the invoice automatically created a difference and when you want pay a new invoice the system told you that you had a difference and if you wanted to use it to pay said invoice or another method)

## Steps to reproduce the behavior
Create the invoice
apply greater payment

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![2018-01-09](https://user-images.githubusercontent.com/28205134/34747851-94a57698-f55f-11e7-91e4-80b2f00e8a16.png)

**Comment by julbroa** [comment]
![2018-01-09](https://user-images.githubusercontent.com/28205134/34747834-7f42d318-f55f-11e7-9e46-82859d4b31be.png)
