### ISSUE TITLE
#Bug Multi Language Product description

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8050]
# Bug
If a product has a translation it will be not used when creating a supplier order. The description of the standard language will be used instead. The product title correct.

## Environment
- **6.0.4
- **Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141
- **PHP**: 5.6.31
- **Database**: MySQL or MariaDB 5.5.57-MariaDB

**Comment by ghost** [comment]
Fix in 7.0

**Comment by je2f** [comment]
@atm-florian, i have the version 8.0.1 and i have this issue. I will try to update in 8.0.2 to see if it will correct it.
I will let you know soon

**Comment by je2f** [comment]
Same issue with the 8.0.2, i will check in the version 7.0
