### ISSUE TITLE
Feature Request: The use of Products in contracts

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8056]
# Feature Request
It would be important that Products can be used in contracts. It is not possible to choose products in a service contract as spareparts. And it would be possible to use contracts as a frame order contract.

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by hregis** [comment]
@FritzBrause66 
perhaps because a contract is a set of services on given dates, and the material is a component of its services and has no physical existence in a contract?

**Comment by code42fr** [comment]
@FritzBrause66 Product could used in contracts with this hidden option -> CONTRACT_SUPPORT_PRODUCTS .

Maybe you could close this issue !

**Comment by code42fr** [comment]
@FritzBrause66 you're right .

You could close this issue.
