### ISSUE TITLE
Bug: it is allowed to modify or delete the values for alerts and optimal stock desired by warehouse, to any user that can see products

### ISSUE THREAD

**Issue by nanoxp** [Dolibarr/dolibarr#8058]
# Bug
it is allowed to modify or delete the values for alerts and optimal stock desired by warehouse, to any user that can see products

## Environment
- **Version**:  version 6 to 6.04
- **OS**:  linux ubuntu
- **Web server**: apache
- **PHP**:  7.0
- **Database**:mysql 5.6
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior

No user should be able to modify the alerts information and the desired optimal stock if you do not have permission to modify

## Steps to reproduce the behavior
1- You have a user who has only read permissions of products and reading of stock
2- Let's check the stock of a product in /htdocs/dolibarr/product/stock/product.php?id=93
3- at the bottom of the page in the section "Set new limit for alert and desired optimal stock", We see that it is enabled that the user without permission to con modify or delete  the values of this section

## [Attached files](https://help.github.com/articles/issue-attachments)

![user without permission to modify](https://user-images.githubusercontent.com/24461406/34888629-97bcfaa8-f790-11e7-9ea9-a500070c8455.JPG)
![modify and delete](https://user-images.githubusercontent.com/24461406/34888634-9ab9b322-f790-11e7-8a27-7fc8709ff676.JPG)

**Comment by all3kcis** [comment]
Ok, I will send a PR to fix it tomorrow.
