### ISSUE TITLE
atal error:  require_once(): Failed opening required '/usr/s$

### ISSUE THREAD

**Issue by hugo49** [Dolibarr/dolibarr#8065]
Bonjour, 
je possède pas d'erreur. ci-joint les logs. Le module send in bleue ne veut pas fonctionner. 
Comment faire ? 

[Mon Jan 15 20:57:07.559483 2018] [:error] [pid 24315] [client mon ip:49409] PHP Fatal error:  require_once(): Failed opening required '/usr/s$
[Mon Jan 15 20:57:07.710512 2018] [:error] [pid 22421] [client mon ip:49410] PHP Warning:  require_once(/usr/share/dolibarr/htdocs/abricot/inc$
[Mon Jan 15 20:57:07.710536 2018] [:error] [pid 22421] [client mon ip:49410] PHP Fatal error:  require_once(): Failed opening required '/usr/s$
[Mon Jan 15 20:57:09.297144 2018] [:error] [pid 17988] [client mon ip:49411] PHP Warning:  require_once(/usr/share/dolibarr/htdocs/abricot/inc$
[Mon Jan 15 20:57:09.297171 2018] [:error] [pid 17988] [client mon ip:49411] PHP Fatal error:  require_once(): Failed opening required '/usr/s$
[Mon Jan 15 21:18:25.946485 2018] [:error] [pid 4578] [client mon ip:49550] PHP Warning:  require_once(/usr/share/dolibarr/htdocs/custom/sendi$
[Mon Jan 15 21:18:25.946511 2018] [:error] [pid 4578] [client mon ip:49550] PHP Fatal error:  require_once(): Failed opening required '/usr/sh$
[Mon Jan 15 21:18:28.129052 2018] [:error] [pid 20576] [client mon ip:49556] PHP Warning:  require_once(/usr/share/dolibarr/htdocs/custom/send$
[Mon Jan 15 21:18:28.129078 2018] [:error] [pid 20576] [client mon ip:49556] PHP Fatal error:  require_once(): Failed opening required '/usr/s$
[Mon Jan 15 21:18:29.381008 2018] [:error] [pid 2464] [client mon ip:49557] PHP Warning:  require_once(/usr/share/dolibarr/htdocs/custom/sendi$
[Mon Jan 15 21:18:29.381054 2018] [:error] [pid 2464] [client mon ip:49557] PHP Fatal error:  require_once(): Failed opening required '/usr/sh$
[Mon Jan 15 21:18:43.721075 2018] [:error] [pid 22421] [client mon ip:49558] PHP Warning:  require_once(/usr/share/dolibarr/htdocs/custom/send$
[Mon Jan 15 21:18:43.721101 2018] [:error] [pid 22421] [client mon ip:49558] PHP Fatal error:  require_once(): Failed opening required '/usr/s$
[Mon Jan 15 21:18:45.850296 2018] [:error] [pid 4748] [client mon ip:49559] PHP Warning:  require_once(/usr/share/dolibarr/htdocs/custom/sendi$
[Mon Jan 15 21:18:45.850330 2018] [:error] [pid 4748] [client mon ip:49559] PHP Fatal error:  require_once(): Failed opening required '/usr/sh$

7.0.22-0ubuntu0.16.04.1
Version actuelle de Dolibarr (Programs) | 6.0.4     -     Dernière version stable disponible : 6.0.4
Version dernière mise à jour (Base de données) | 6.0.4

**Comment by hugo49** [comment]
Dolibarr 6.0.4
Abricot - Sendinblue - DolimapMail - keyyo - dropbox - Courrier - Patas M - EcommerceNG - Dolical

Bug Sendinblue - dolibarr/sendinblue/admin/sendinblue_setup.php - Cette page ne fonctionne pas Impossible de traiter cette demande via si.hugoprod.fr à l'heure actuelle. HTTP ERROR 500

Bug Sendinblue - /dolibarr/sendinblue/index.php?idmenu=24017&mainmenu=sendinblue&leftmenu= / Cette page ne fonctionne pas Impossible de traiter cette demande via si.hugoprod.fr à l'heure actuelle. HTTP ERROR 500.

Bug sur contact - /dolibarr/contact/card.php?id=593 - Cette page ne fonctionne pas Impossible de traiter cette demande via si.hugoprod.fr à l'heure actuelle. HTTP ERROR 500.

Merci.

**Comment by dolibarr95** [comment]
Hi
Is is an external module ?
If yes you should contact the dev first.

**Comment by simnandez** [comment]
It is not a problem of dolibarr itself. It is a problem of an external module. Contact the developer of the module
