### ISSUE TITLE
Why limiting exec time in crontasks ?

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8070]
# Bug
Dolibarr limits a task so the module can not run long tasks (ex sending a mailing)
this is the code in cronjob class
// Increase limit of time. Works only if we are not in safe mode
		$ExecTimeLimit=600;
		if (!empty($ExecTimeLimit))
		{
			$err=error_reporting();
			error_reporting(0);     // Disable all errors
			//error_reporting(E_ALL);
			@set_time_limit($ExecTimeLimit);   // Need more than 240 on Windows 7/64
			error_reporting($err);
		}
		if (!empty($MemoryLimit))
		{
			@ini_set('memory_limit', $MemoryLimit);
		}
Cron tasks are here to run tasks that can be long 
A dolibarr scripts sets usually an execution time to 0
this code can cause problems, and it is impossible to set a limit without changing Dolibarr code, which is bad.

## Environment
- **Version**: 6.0 and 7.0
- **OS**: Linux
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
The cronscheduler (scripts/cron) should simply run tasks and avoiding running a task several times.
The excution time and limits shoumd be set in the launched scripts.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
