### ISSUE TITLE
#BUG Contracts - major tags in ODT documents are not working - Ver. 6.0.4

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8073]
# Bug
If using ODT documents for contracts, major tags will be not replaced with the related information.
For example:
{company_customercode}
{company_customeraccountancycode}
{company_vatnumber}
{object_ref_customer} 
etc.

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by ATM-Marc** [comment]
Hello,

This is fixed in 6.0.6

Regards,
Marc.
