### ISSUE TITLE
Erreur d'affichage dans les interventions

### ISSUE THREAD

**Issue by gidebe** [Dolibarr/dolibarr#8077]
# Bug
[Erreur d'affichage dans les interventions]

## Environment
- **Version**: [6.0.3]
- **OS**: [Ubuntu Server 16.04 à jour]
- **Web server**: [2.4.18-2ubuntu3.5]
- **PHP**: [php7]
- **Database**: [mysql 5.7.20]
- **URL(s)**: [?]

## Expected and actual behavior
[Lorsque je crée une intervention dans Dolibar, de plusieurs jours, en haut du fichier PDF généré dans Dolibarr, apparaît toujours Total : 1 jour ; alors que lorsque je crée une intervention qui dure par exemple 3 jours, je devrais voir apparaître dans le récapitulatif : Total : 3 jours]

## Steps to reproduce the behavior
[Le problème se reproduit pour chaque intervention qui dure un jour ou plus]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by atm-arnaud** [comment]
Bonjour,

je m'occupe actuellement de cette issue.

Cordialement,

**Comment by atm-arnaud** [comment]
Bonjour,

Le comportement du module est correct sur une version 6.0.7. Par contre il cumule les jours sur une base de 24h.

j'ai entré 33h d'intervention et il me remonte bien : 1jour et 9heures.

Cf screenshots : 
![interv_33h](https://user-images.githubusercontent.com/14542208/38556851-60311c24-3ccb-11e8-985c-2d497113e0a2.png)
![interv_33h_2](https://user-images.githubusercontent.com/14542208/38556852-60504f90-3ccb-11e8-9722-c4168bb7944e.png)

Si vous souhaitez un affichage correspondant à des plages horaires travaillées, le logiciel ne répondra pas à cette demande sans surcouche spécifique.

Cordialement,

**Comment by gidebe** [comment]
Bonjour,

ok, merci d'avoir regardé. Et qui serait en mesure de développer une telle
surcouche ? Vous ?

Cordialement,

Gilles de Bellabre
APRIAS - Immeuble Space, bât. 3
9 allée James Watt - 33700 MERIGNAC
Tel 05.67.70.29.10 - Mobile 06.50.38.33.02

**Comment by atm-arnaud** [comment]
Bonjour,

De nombreuses société peuvent faire en sorte de mettre au point ce développement. Si vous le voulez, nous pouvons vous faire une proposition dans ce sens. Dans ce cas précis, je vous laisse prendre contact avec le service commercial de ma société : ATM-Consulting.

Cordialement,

**Comment by gidebe** [comment]
OK, merci beaucoup, et surtout pour ce super CRM qui nous sert tous les
jours !
A bientôt,

Cordialement,

Gilles de Bellabre
APRIAS - Immeuble Space, bât. 3
9 allée James Watt - 33700 MERIGNAC
Tel 05.67.70.29.10 - Mobile 06.50.38.33.02

**Comment by atm-arnaud** [comment]
Mais c'est avec plaisir :)
Merci à vous de l'utiliser et de nous faire des retours

@atm-maxime Issue toclose
