### ISSUE TITLE
Remove RIB support entirely

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#8078]
# Bug
RIB is deprecated since 2014 and superseded by IBAN/SWIFT.

I think it's time to completely remove RIB support from the codebase!

**Comment by aspangaro** [comment]
+1

**Comment by altairis-agnes** [comment]
I have customers who still use rib (pour les traites, je sais pas comment on dit en anglais). They're starting to do without them, but they're still using them for some of their customers.
Maybe put it in option, don't you think?

**Comment by BebZ** [comment]
Maybe warn users before migration ?
Or «migrate» rib to iban automatically by copying datas from rib inside iban ?

**Comment by hregis** [comment]
@rdoursenaud @aspangaro @agnesrambaud @BebZ 
add an hidden constant

**Comment by mdeweerd** [comment]
If the customer's RIB is filled, but not the IBAN, make sure that the RIB information is somehow kept.
It could be either added to a text field or the IBAN could be "guessed" from the RIB information.

**Comment by ebzao** [comment]
In New Caledonia, RIB is always used. Bank system here is like France 20 years ago... and didn't evolve.
But as @mdeweerd says, we can find RIB from IBAN information if necessary.

**Comment by simnandez** [comment]
If the RIB is not necessary, you can add the hidden constant PDF_BANK_HIDE_NUMBER_SHOW_ONLY_BICIBAN, and ind pdf Keep only the IBAN/BIC info
