### ISSUE TITLE
Feature Request: Dispatch product to the warehouse, allow qty to be negative

### ISSUE THREAD

**Issue by jameszhang023** [Dolibarr/dolibarr#8080]
# Feature Request
Hi all,

Could you give me a hand?
I can't return the product to the supplier, this function is necessary to me, 
Then I try to enter a negative quantity in the order, the order is created, but when I dispatch product to the warehouse,  the command failed. Please look at the screenshot below:
![returnproduct](https://user-images.githubusercontent.com/22817906/35181432-622cbf78-fdfc-11e7-87fc-cc49d294f12e.gif)

How to do it ?
Thanks in advance

**Comment by BebZ** [comment]
Good idea. Could be really useful and simple also for waiting credit notes :)

**Comment by jameszhang023** [comment]
@BebZ  tks, How did you do that return products to your supplier? How did you do that your costomer return products to you?

**Comment by jameszhang023** [comment]
hi, @eldy ,Could you give me a hand?

**Comment by jameszhang023** [comment]
Hi, there,
Please see [here](https://github.com/JamesZhangChina/dolibarr/commit/a4532278c4f5489170b8ee4f094b6e6a9c1d7008)

**Comment by dolibarr95** [comment]
Hi
Why is this PR closed ?

**Comment by flixbustier** [comment]
Thank you @jameszhang023  ! Thanks to your post https://github.com/jameszhang023/dolibarr/commit/8d51548951601fda93eeae528899d727c2f0c840 I managed to do it on Dolibarr 10.0.6
File htdocs/fourn/commande/dispatch.php line 280
**REPLACE** if (GETPOST($qty) > 0) {
**BY** if (GETPOST($qty) != 0) {

That's apparently all that you need to do in Dolibarr 10.0.6 to allow negative quantity in dispatch. For my use I wanted to make some kind of inventory with product lots, without passing on every product to pass stock movements. So I do them all in once through a purchase order.

**Comment by jameszhang023** [comment]
@flixbustier Glad to be useful to you :-)

**Comment by eldy** [comment]
With v17, the pathc suggested here https://github.com/jameszhang023/dolibarr/commit/a4532278c4f5489170b8ee4f094b6e6a9c1d7008
has been standardized with
`if ($qty == 0 || ($qty < 0 && !getDolGlobalInt('SHIPMENT_ALLOW_NEGATIVE_QTY'))) {`
So you should have the effect by setting the experimental hidden option SHIPMENT_ALLOW_NEGATIVE_QTY to 1 in v17

Same for receptions with RECEPTION_ALLOW_NEGATIVE_QTY
