### ISSUE TITLE
#Bug: Allocated currencies are not considered when creating a quotation/order/supplier order

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8089]
# Bug
We are using the multicurrency module in Dolibarr 6.0.4
Our customers and suppliers have allocated currencies.
If we create a new quotation/order/supplier order, the currency will be not considered.
It makes no sense to allocate a specific currency and we have to change the currency manually.

**Comment by atm-maxime** [comment]
That's because for now, you have to create the proposal/order/invoice from the customer/supplier card if you want all predefined fields filled (currency, payments terms and mode, incoterms, bank, shipment mode, ...).
