### ISSUE TITLE
dolibarr multitaxe Canada Québec TPS / TVQ  REF:issue 5914 ...

### ISSUE THREAD

**Issue by jiptwo** [Dolibarr/dolibarr#8091]
Dolibarr and the option of the tps and tvq is not in the plate-form
reference issue 5914

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: [*Affected Dolibarr version(s)*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by eldy** [comment]
Hi @jiptwo 
Can you describe a use case with real data as example to provide what you get and what you expect to get ?

**Comment by jiptwo** [comment]
hi Laurent,
check this
https://www.revenuquebec.ca/en/businesses/consumption-taxes/gsthst-and-qst/collecting-gst-and-qst/calculating-the-taxes/

you can click on + for example

2018-04-17 4:39 GMT-04:00 Laurent Destailleur <notifications@github.com>:

**Comment by vdegrandpre** [comment]
Nous tavaillons actuellement à un port compatible pour les taxes TPS et TVQ, afin de rendre Dolibarr utilisable clé-en-main pour le Québec. Merci de me joindre au vincent@de-grandpre.quebec pour des spécificités à intégrer. Nous ne sommes pas en mesure, pour l'instant, de donner une date de distribution pour une version québécoise, mais on y travaille ! Merci.

**Comment by jiptwo** [comment]
Bonjour
Avez vous produit  a l'ajout de la tps et tvq
Si vous avez besoin d'autres information je ferai des recherche pour vous
Jean-Pierre Beaudoin

Le dim. 27 mai 2018 12:05, Vincent de Grandpré <notifications@github.com> a
écrit :
