### ISSUE TITLE
Invoices created in bulk action do not take payment term into account

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#8095]
When creating invoices in bulk action the payment terms are set to the same day as invoice date. Not the set payment term (e.g. two weeks) set in client card.

dolibarr 6.04

**Comment by atm-gauthier** [comment]
I'm working on this one..

**Comment by GheeEasy** [comment]
Hi, Any news on this topic, Is still not working in 9.0.2

**Comment by atm-maxime** [comment]
Hi. Isn't it the same as #11185 ?
