### ISSUE TITLE
Feature Request: Interventions registered in Agenda

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#8097]
# Feature Request
When a user creates an intervention, it should also create an event in the agenda with the date, time and duration of said intervention.
At the moment, interventions do not register any events whatsoever.

**Comment by hregis** [comment]
@ruistrecht-alt 
go to "Events/Agenda module setup" and go to "Automatic filling" tab,
and verify that event options for interventions are checked (FICHINTER_*)

**Comment by ruistrecht-alt** [comment]
You misunderstood my FR @hregis I apologize if I wasn't explicit enough.
I did not mean the current existing auto events, these only record creation, deletion and validation on the agenda. I was referring to a more complex solution. 
When a user creates an intervention, he has to register in the product/service lines the said intervention description, date and duration. Upon Intervention validation (for example), the system should automatically register  entries in the agenda of such data, intervention service/product line description, date and duration.
