### ISSUE TITLE
caractères spéciaux dans le titre de dossier GED

### ISSUE THREAD

**Issue by noelonline** [Dolibarr/dolibarr#8098]
# Bug
J'ai créé un dossier dans la partie GED
J'ai voulu en modifier le titre en insérant le caractère ascii (#25BA) en début de titre
Dans la liste ce caractère est remplacé par un underscore, le nombre de fichier (en l'occurence 0) n'apparaissait plus et lors du clic sur le dossier, l'obtenais un message d'erreur 

## Environment
Dolibarr a détecté une erreur technique.
Date: 20180126112000
Dolibarr: 6.0.4
Niveau de fonctionnalités: 2
PHP: 5.3.3
Server: Apache
OS: Linux 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Url sollicitée: /ecm/docmine.php?section=0&relativedir=_+Utilisation+GED+et+gestion+doc
Referer: /ecm/index.php?action=file_manager&mainmenu=ecm&leftmenu=ecm&idmenu=78
Gestionnaire de menu: eldy_menu.php
Message: ErrorSectionParamNotDefined

## Steps to reproduce the behavior
J'ai créé un dossier dans la partie GED
J'ai voulu en modifier le titre en insérant le caractère ascii (#25BA) en début de titre
Dans la liste ce caractère est remplacé par un underscore, le nombre de fichier (en l'occurence 0) n'apparaissait plus et lors du clic sur le dossier, l'obtenais un message d'erreur

**Comment by hregis** [comment]
@noelonline 
je n'arrive pas à reproduire le problème avec un dolibarr 6.0.6 (branche 6 à jour) !

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
