### ISSUE TITLE
Feature Request: Financial Discount

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#8099]
# Feature Request
Allow users to apply a financial discount on Invoices (Both supplier and client).
Many companies offer a financial discount on invoices, this discount is applied on the base amount excluding taxes, which means it doesn't influence the tax amount. An example:

**Invoice (no financial discount):**
Base amount: 357.28€
Tax: 82.17€
Total: 439.45€

**Invoice (with 2% financial discount)**
Base amount: 350.13€ (357.28€ with 2% tax free discount)
Tax: 82.17€ (same as above, because 2% discount is tax free)
Total: 432.30€ (total, with new tax free discount applied)

At the moment we are working around this issue with this method:
![screenshot-2018-1-26 supplier invoice - card](https://user-images.githubusercontent.com/23050598/35437026-9424db60-0288-11e8-92a7-db644084ec80.png)

**Comment by atm-maxime** [comment]
I think this already exists, take a look at the "Absolute discount" in the customer tab. Same feature is coming for suppliers in next 8.0 version.
