### ISSUE TITLE
Error DB_ERROR_1072: ALTER TABLE llx_inventory ADD INDEX idx_inventory_tms (tms)

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#8102]
# Bug
When updating from 5.0.4 to 6.0.0 get these 3 errors and proccess stops with a KO!
.
> **_I will thank any help to solve this, as I don´t know hot to solve without breaking it a little more... I´m stuck in the KO screen_**
.
- Request 182 sql='ALTER TABLE llx_inventory ADD INDEX idx_inventory_tms (tms);'

- **Error DB_ERROR_1072: ALTER TABLE llx_inventory ADD INDEX idx_inventory_tms (tms);Key column 'tms' doesn't exist in table**

- Request 183 sql='ALTER TABLE llx_inventory ADD INDEX idx_inventory_datec (datec);'
Request 184 sql='ALTER TABLE llx_inventorydet ADD INDEX idx_inventorydet_tms (tms);'

- **Error DB_ERROR_1072: ALTER TABLE llx_inventorydet ADD INDEX idx_inventorydet_tms (tms);Key column 'tms' doesn't exist in table**

- Request 185 sql='ALTER TABLE llx_inventorydet ADD INDEX idx_inventorydet_datec (datec);'

- **Error DB_ERROR_1072: ALTER TABLE llx_inventorydet ADD INDEX idx_inventorydet_datec (datec);Key column 'datec' doesn't exist in table**

## Environment
- **Version**: 5.0.4 to 6.0.0 (update proccess)
- **OS**: Nginx (Dont know what version)
- **Web server**: Plesk (Dont know what version)
- **PHP**: 5.6.7
- **Database**: MySql 5.5.52-cll-lve
--

## Expected and actual behavior
First time getting an error like that when updating Dolibarr, since V 3.

## Steps to reproduce the behavior
Just update as always before, this time from 5.0.4 to 6.0.0

## [Attached files - Heidi SQL screenshot of DB table]
![image](https://user-images.githubusercontent.com/15174724/35463552-7c3966b0-02f1-11e8-9b88-d4774dc65e8c.png)

**Comment by simnandez** [comment]
I can not reproduce the problem. Can you try updating to 6.0.5?

**Comment by PlanPc** [comment]
Thank you Juanjo for your quick answer.

Exact same result from 5.0.4 to 6.0.5.

Now, I try to update in order from actual 5.0.4 to:

5.0.5 -- OK
5.0.5 to 5.0.6 -- OK
5.0.6 to 5.0.7 -- OK
**5.0.7 to 6.0.0 -- KO**

Any idea?


![image](https://user-images.githubusercontent.com/15174724/35476665-d9d06464-03b3-11e8-9cbd-ee64e8e7b08c.png)



![image](https://user-images.githubusercontent.com/15174724/35476675-0d2c29d8-03b4-11e8-98f6-4a937bb11bed.png)

**Comment by PlanPc** [comment]
Someone can indicate how to create those columns that Dolibarr has not automatically created in update proccess?

Cant find any reference to these tables or columns, in the [Wiki](https://wiki.dolibarr.org), [Changelog,](https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog) Spanish, English and French forums, etc

Also there is no information about those tables, info seems outdated here:
[https://wiki.dolibarr.org/index.php/Category:Table_SQL](https://wiki.dolibarr.org/index.php/Category:Table_SQL)

so dont know which are the parameters to create the columns manually, If I do not solve it at some point, I will drag the problem forever, as I will use Dolibarr at least till version 750.854.

Really don´t know where the problem comes from, but I supouse if it where from a third party module, the update script would never consider it for an ALTER TABLE in the update proccess, and if those tables / columns are from Dolibarr core modules, Why has been possible to bypass their creation at some point, if we are updating Dolibarr regularly?

Very confuse to me...

Regards
