### ISSUE TITLE
Bug: Error installing with PostgreSQL. v6.0.6

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#8106]
# Bug

Conexión al servidor : localhost |  
-- | --
Versión de la base de datos | 9.6.6
Nombre de la base de datos | dolibarr
Creación de las tablas y los índices |  
Creación de las claves e índices |  
Creación de funcionesRequest 747 : DROP FUNCTION date_format(timestamp without time zone,text); | Error de SQL DB_ERROR_42883 ERROR: 42883: function date_format(timestamp without time zone, text) does not exist LOCATION: LookupFuncName, parse_func.c:1925
Creación de funcionesRequest 747 : DROP FUNCTION date_format(timestamp with time zone,text); | Error de SQL DB_ERROR_42883 ERROR: 42883: function date_format(timestamp with time zone, text) does not exist LOCATION: LookupFuncName, parse_func.c:1925
Creación de funciones |  
Carga de los datos de referencia |

**Comment by marcosgdf** [comment]
Still happening...

**Comment by lpofredc** [comment]
I confirm... still happening...
Tested on Debian Jessie with PostgreSQL 9.6.8 and PHP7.0
I could pass the issue by executing the script manually as dolibarr db user (username : dolibarr)
``
psql -p 5432 -U dolibarr -W dolibarr -f install/pgsql/functions/functions.sql
``

**Comment by marcosgdf** [comment]
Also happening in Dolibarr 7.0.6

**Comment by guillaume-uH57J9** [comment]
This affects 10.0-alpha as well. 

> Date: 20181215134408
> Dolibarr: 10.0.0-alpha
> PHP: 7.0.30-0+deb9u1
> Server: nginx/1.10.3
> OS: Linux radole 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64

This appears similar to #2853 which was fixed a few years ago. 
It's probably a regression, not a duplicate, but looking at the earlier issue might help fix this.
