### ISSUE TITLE
Feature request: Supplier module setup - Order documents models / ODT not available

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8111]
# Feature Request
It is not possible to choose ODT for order documents as in al other modules.

**Comment by atm-maxime** [comment]
How is it a bug ?

**Comment by ivancalax** [comment]
Anyone know if there is documentation about this to add the feature or support of ODT files into supplier module?

**Comment by torvista** [comment]
I also would like to see this feature extended to the supplier module.

**Comment by Tim-Otte** [comment]
If my pull request has implemented the desired feature, this issue can be closed...
