### ISSUE TITLE
BUG: Shipments - Trackin number - Link

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8112]
# Bug
If we add a UPS Tracking Number the link is always to UPS France. It should be posible to change the Country in the Module Setup

**Comment by dolibarr95** [comment]
Hi
Is it an external module ?

**Comment by frederic34** [comment]
@dolibarr95 it's in dictionnary/sending-method

**Comment by frederic34** [comment]
@FritzBrause66 did you edit sending method and link in dictionary?

**Comment by FritzBrause66** [comment]
OK, it works. Thank you
