### ISSUE TITLE
FEATURE REQUEST: Currency Exchange Rate Update

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8113]
# Feature Request
We are using the multicurrency function. It would be very helpful, if we can enter the current exchange rate once a day. For example, if you log in and the saved exchange rate is not from this day, it should ask you to enter the exchange rate, before start working. Or much better, if we can enter a link in setup-modules where the system can get automatically the exchange rate.

**Comment by absnc** [comment]
Might be related #8141

**Comment by cperrot** [comment]
+1 taking the exchange rate from European Central Bank or https://openexchangerates.org/ or any other API at a specified interval.

**Comment by cperrot** [comment]
I created a php file which you can run as cron job.
you have to create an api key at openexchangerates.org.

let me know what you think.
Cedric

[currencyUpdate.zip](https://github.com/Dolibarr/dolibarr/files/1758418/currencyUpdate.zip)

**Comment by cperrot** [comment]
one caveat it only works with the free plan of openexchangerates.org.

**Comment by cperrot** [comment]
a quick update because I realized that Dolibarr needs the exchange rate the other way around.
[currencyUpdate.zip](https://github.com/Dolibarr/dolibarr/files/1759647/currencyUpdate.zip)

**Comment by adamkcs** [comment]
Can anyone help me how can I run this as a cronjob? I was trying to add it as a PHP class and method, like put all into a class, then a function, but no matter how I set the parameters, whenever I run the script I get an HTTP 500 error.

**Comment by cperrot** [comment]
Have you called the login function before calling the function?

Send me what you have done so far.

**Comment by adamkcs** [comment]
Practically I've put the complete thing into a class, then the first part into a function. Afterwards I created the scheduled job in the dolibarr interface setting the instance for the class and the method for the function. (ofc the login details I've set)
I'm quite new in Dolibarr.

![currupdate_setup](https://user-images.githubusercontent.com/42243421/43907952-9b40c5ee-9bee-11e8-8abe-a4152367180c.JPG)
[currencyUpdate.txt](https://github.com/Dolibarr/dolibarr/files/2274674/currencyUpdate.txt)

**Comment by cperrot** [comment]
Well I see you problem now. The code you have is from the BambooInvoice OpenSource Project which uses CodeIgniter(the framework is needed). 
You want to use the BambooInvoice code inside Dolibarr. You can use the mysqli classes but the the webservice call is completely omitted. (see below)

My suspicions quickly perusing your code. 
Don't put it in a class
If the you insist on a class create a constructor
Here is a how to https://code.tutsplus.com/tutorials/managing-cron-jobs-with-php--net-19428
and make the function public.

$url = "http://openexchangerates.org/api/historical/" . $invoiceDate . ".json?app_id=" . $api_key;

        $jsonResponse = file_get_contents($url);

        if ($jsonResponse == false) {

            return 0;

        }

        $json = json_decode($jsonResponse, true);

        if ($json == null) {

            return 0;

        }

**Comment by cperrot** [comment]
Please contribute the code when finished.

**Comment by cperrot** [comment]
Did you finish your code to run as php cron job? Could you please share it.

**Comment by cperrot** [comment]
Here is the php for cron to update your Currency tables.

`<?php
//Fill our vars and run on cli
$dbname = 'xxx';
$dbuser = 'xxx';
$dbpass = 'xxx';
$dbhost = 'localhost';
$accountingCurrency = "CHF"; //or any other ISO currency code such as EUR, USD, COP, AUD and so on
//add percentage to exchange rate to match the bank exchange or credit card exchange rate
// this example 2.5% added to exchange rate
$exchangeSurplusMiddleExchange_rate = 2.5;
//openexchangerates.org api key
$api_key = "xxx";


//get exchange rate

// example "https://openexchangerates.org/api/latest.json?app_id=<api_key>"
// the free version only supports USD base, therefore we will have to do some conversion for non USD based currencies

//not the same currency now do the grunt work
//first do some sanity checks api_key not set ERGO no calculation
if ($api_key == null || empty($api_key)) {
        printf("no openexchangerates.org api key set");
        exit;
}

$url = "https://openexchangerates.org/api/latest.json?app_id=" . $api_key;
$jsonResponse = file_get_contents($url);
if ($jsonResponse == false) {
        printf("no json response from openexchangerates.org");
        exit;
}
$jsonExchangeRates = json_decode($jsonResponse, true);
if ($jsonExchangeRates == null) {
        printf("problem decoding json response  from openexchangerates.org");
        exit;
}

$timestamp = $jsonExchangeRates['timestamp'];


//get the currencies that need to be adjusted
$connect = $mysqli = new mysqli($dbhost, $dbuser, $dbpass, $dbname);
/* check connection */
if ($mysqli->connect_errno) {
        printf("Connect failed: %s\n", $mysqli->connect_error);
        exit();
}
$query = "SELECT * FROM llx_multicurrency";
$result = $mysqli->query($query);

foreach ($result as $row) {
        //check if we need to insert
        if(strcmp($row["code"], $accountingCurrency) !== 0 ){
                //do the exchange magic here
                $exchRate = calculateAccountingCurrencyExchangeRate($jsonExchangeRates, $accountingCurrency, $row["code"], $exchangeSurplusMiddleExchange_rate);
                //update the table
                $sql = "UPDATE llx_multicurrency_rate SET date_sync=FROM_UNIXTIME(". $timestamp ."), rate=" . $exchRate . " WHERE fk_multicurrency = " . $row["rowid"];
                if ($connect->query($sql) === TRUE) {
                        //echo "Record updated successfully";
                } else {
                        echo "Error: " . $sql . "<br>" . $connect->error;
                }
        }
}

/* free result set */
$result->free();

/* close connection */
$mysqli->close();

exit;
    
function calculateAccountingCurrencyExchangeRate($jsonExchangeRates, $accountingCurrency, $invoiceCurrency, $exchangeSurplusMiddleExchange_rate)
{
    if ($accountingCurrency == "" || $invoiceCurrency == "") {
        // no currencies set
        printf("no currencies set");
        return 0;
    }
    // both currencies are the same no conversion
    if ($invoiceCurrency === $accountingCurrency) {
        return 1;
    }
    //because the free version is limited to 50 requests per day 
    //(so they say, my test haven't found a limit yet)
    //we have to check whether we got something back
    try
    {
        if (!array_key_exists('rates', $jsonExchangeRates) || $jsonExchangeRates['rates'] == null || $jsonExchangeRates['rates'][$invoiceCurrency] == null) {
            return 0;
        }
        $invoiceRate = $jsonExchangeRates['rates'][$invoiceCurrency];
        $accountingRate = $jsonExchangeRates['rates'][$accountingCurrency];
    } catch (Exception $e)
    {
        //if something goes wrong accessing the variables return 0
        printf("exception occured    ");
        return 0;
    }
    if ($invoiceRate == null || $accountingRate == null) {
        return 0;
    }
    // the free version only supports USD base, therefore we will have to do some conversion.
    $conversionRate = 0;
    if ($accountingCurrency === "USD") {
        $conversionRate = $invoiceRate;
    } else {
        //convert to rate between the two currencies other than USD accounting currency
        $conversionRate = $accountingRate / $invoiceRate;
    }
    //
    return 1 / ($conversionRate / (($exchangeSurplusMiddleExchange_rate / 100) + 1));
}
?>`
