### ISSUE TITLE
Bug: Origin country and customs code disappear in propal azur in foreign languages

### ISSUE THREAD

**Issue by RafaelBarcos** [Dolibarr/dolibarr#8116]
# Bug
- When I write a propal with azur in my own language, all is fine. When I change the language, the propal don't includes for each product the origin country and customs code. Thanks for help.

## Environment
- **Version**: 6.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.26
- **Database**: MySQL or MariaDB 5.5.5-10.1.29-MariaDB
- **URL**: /htdocs/comm/propal/card.php?id=8

**Comment by atm-maxime** [comment]
Seems fixed in 6.0.6. It doesn't disappear but it stays in the user language. Maybe we should work on re-translating it.
