### ISSUE TITLE
FEATURE REQUEST: Serial Number

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8120]
# Feature Request
The current proceeding to enter serial numbers is good for single products or products in small quantities.
We sell Photo Diodes in quantities from 10 to 100 pieces. As these products are high priced (50,- to 3000,- EUR/piece) and used in high tech systems we are using serial numbers.
To enter the serial numbers it would be good to enter the serial numer from... to... 
When selling the PD's it would be a good feature if we can select the serial numbers, when creating a shipping document.

**Comment by edupulpillo** [comment]
Yes, specially in electronic products like tablets, smartphones, .... the qtys are about thousands
Also it will be great to manage in the database  "from/to" instead to generate one register for each serial number. Eaxh time a serial number can "split" a from/to, can be splited in 2 different records "from/to"
and if the movement is only one serial number from/to will have the same serial number (1 serial number only)
This is really needed to be able to manage serial numbers in Dolibarr, since only big quantities need a serial number trazability, and is not possible to do it if we must to specify one by one, all of the serial numbers

**Comment by BebZ** [comment]
I understand. But how do you know the «from» and te «to»? Namely where does the serial start and where does it end and how is the implementation made is it +1 serial after serial or from a to z at the end of serial... to have a mathematical implementation could be easy  to handle and implement... but if you receive an illogical set of batches i dont see how...

**Comment by com4WEB** [comment]
This is really a very important feature request.
I think it is necessary to separate between batches (lot) and serial numbers on the other hand.
Than, i suggest, it is easier to implement special functions for mass serialisation.

**Comment by edupulpillo** [comment]
Relating the from-to, is easy.
Usually when a batch is purchased or manufactured all the numbers are contiguous and consecutive,
For example, imagine that you produce 2000 tablets, then the serial numbers can be: A0001 to A2000.
Then you can sell 500 to one customer: 1 to 500, then in product serial numbers, you can split the record
batch1 A0001 to A2000 in 2 batches: A0001 to A0500 that are moved to the customer, and A0501 to A2000 that are still in the warehouse. If you move only 1 piece also works. For example you sell 1 pcs only, then the batch A0501 to A2000 can be splited in A0501 to A0501 and A0502 to A2000.
Then we are using for traceability only 3 records, instead using the 2000 records.
Then if is needed to locate a piece with a serial number, only is needed to search a number that belongs to a interval between the "from and to"
Do you think is a good idea?

**Comment by BebZ** [comment]
I think that's the way the "factory" module on Dolistore works, or GPAO.
I did not agree with these functions as you have to "split" everytime you want to ship something, and the batches we receive are big. Only for electronics or big machines would be useful.
Anyway i think it is better for you to handle serial by serial, one by one in stock for you to fine tune your traceability. Maybe it is possible to put a second field called "serial" with batch module or make the batch module optionnaly possible when you receive a product to have a "numbering" batch field from 0001 to 2000 with a prefix and suffix if needed... and it poupulates stock database and dispatch each unit...

**Comment by com4WEB** [comment]
> I think that's the way the "factory" module on Dolistore works, or GPAO.  

   But not every company has an inhouse production. So the factory modules are not always work for this.
  
> I did not agree with these functions as you have to "split" everytime you want to ship something, and the batches we receive are big. Only for electronics or big machines would be useful.
  
  I can't see your problem. Why you have to split always? Only if you use large serials blocks.
 But if you don't use this function, you don't have to split. 


> Anyway i think it is better for you to handle serial by serial, one by one in stock for you to fine tune your traceability. 
   Sorry, but this is not possible / not practicable. I have some customers with this issue/problem
   and some of them don't use the lot/serial module and handle this with external tools 
  and a lot of firms with interest in dolibarr then decided against the program.

Maybe it is possible to put a second field called "serial" with batch module or make the batch module optionnaly possible when you receive a product to have a "numbering" batch field from 0001 to 2000 with a prefix and suffix if needed... and it poupulates stock database and dispatch each unit...

**Comment by cfoellmann** [comment]
I am also running more and more into serial number issues.

We are testing/using the MRP module and need to track serials.
The current implementation of serial/batch is bad since it is just a batch that is called "Serial/Batch".

Everytime you need the limitations of serials you have no checks in place to prevent mistakes.
A serial number must not be used twice or it defeats the purpose.

We need to declare the current field as "batch" and add features for real "serial".

**Comment by edupulpillo** [comment]
This feature is still relevant.
and a comment for com4WEB,
handle serial by serial do not allows to manage big qauntities.
That we mean is "range of serial numbers" in the database.
Imagin that you need to trace 30000 serial numbers, only in one purchase. This means 30000 records with one unique serial number. Obviously this is not a good approach.

Using ranges in the database, can use only one record, and later each time that you do a selling or some pieces, maybe 1 piece or maybe 200 pieces , then for each sale, need only one record.

Of course in the user interface, should be able to fill only one serial number (initial value) and if the final value is empty will mean only one serial number, but in the database, will be recorded as a only one record with a range with "from value" = "last value", that means 1 only serial number.

So this way is the optimized way for both cases: using one by one, and using big quantities of serial numbers.
