### ISSUE TITLE
FEATURE REQUEST: Variants

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8121]
# Feature Request
It would be more usefull if Variants work like this:

You can define a basic product
You can assign n variant attributes
For example, you have a Product X and you can vary the Thickness (1, 2, 3,...mm), Size (5 x 5, 6 x 6mm...) a.s.o.

**Comment by julbroa-zz** [comment]
The Variants are an experimental function in Dolibarr.
Activate experimental functions:
Configuration -> several and add:
MAIN_FEATURES_LEVEL value: 2
With this module is activated a new module called "Variants"

**Comment by BebZ** [comment]
@FritzBrause66 did you try it ?
