### ISSUE TITLE
Bug: Select2-Input in Product search for barcodes shows limited results

### ISSUE THREAD

**Issue by factulas** [Dolibarr/dolibarr#8124]
# Bug
[Select2-Input in Product search for barcodes shows limited results]

## Environment
- **Version**: [6.0.4]
- **OS**: [Debian 9.1]
- **Web server**: [ Apache/2.4.25 (Debian)]
- **PHP**: [7.0.19-1]
- **Database**: [10.1.26-MariaDB-0+deb9u1 Debian 9.1]
- **URL(s)**: [*dolibarr-root*/barcode/printsheet.php]

## Expected and actual behavior
[While searching for product it should update product list in search result to results that match the search]

## Steps to reproduce the behavior
When searching for product with "Fill barcode type and value from barcode of a product. " selected, the search results show the first 20 results descending a-z. But, when a search value is inserted the results are not updated.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![image](https://user-images.githubusercontent.com/9405782/35686275-e921c924-0739-11e8-9a8a-d601706ec363.png)

# Feature Request

## Suggested implementation
Fix Select2-input class with the use of id s2id_autogen1_search

## Suggested steps
I don't know

**Comment by ATM-Marc** [comment]
Hello,

I can't reproduce this in 6.0.6,

Regards,
Marc.
