### ISSUE TITLE
Cannot set/update product price using REST API

### ISSUE THREAD

**Issue by studio-indelebil** [Dolibarr/dolibarr#8125]
Hi,

When creating/updating a product using the REST API, there is no way to set the product price or any data related to the price (price_ttc, price_min, price_min_ttc, etc).

After some investigations, it appears that this could be fixed by patching post() and put() methods in **/product/class/api_product.class.php**, adding something like :
`$this->product->updatePrice(
                $this->product->price,
                $this->product->price_base_type,
                DolibarrApiAccess::$user,
                $this->product->tva_tx,'', 0, 0, 0, 0, array(), '');`

I found this on dolibarr's forum here : https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/27554-api-rest-product-modify-does-not-update-price#32575

Another fix would be to patch the update() method in product.class.php, i don't know what is the best solution.

Anyway this is a MAJOR issue because it seems that there is no other way to setup the product price with the API.

Could a contributor have a look into this please ?

Thanks !

**Comment by eldy** [comment]
On which Dolibarr version ?
Did you try with v7, there is new API dedicated to set product prices.

**Comment by studio-indelebil** [comment]
Well as we must go in production in march we are working on the 6.0.5 version (last stable release). Do you know when is planned the v7 release ?

**Comment by sebassander** [comment]
@eldy I have the same problem in v7. 
I'm trying to update the tries but it doesn´t work what do you recomend?

@studio-indelebil Did you resolve the problem?
