### ISSUE TITLE
Bug: Non inscriptions dans journal ventes des factures avec local Taxe 1 

### ISSUE THREAD

**Issue by kloisirs** [Dolibarr/dolibarr#8127]
# Bug

## Environment
- **Version**: 6.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.27 (Ubuntu)
- **PHP**: apache2handler 7.1.11-0ubuntu0.17.10.1
- **Database**: MySQL or MariaDB 5.7.20-0ubuntu0.17.10.1
- **URL**: /dolibarr/accountancy/journal/sellsjournal.php?id_journal=1&date_startday=01&date_startmonth=01&date_startyear=2018&date_endday=31&date_endmonth=01&date_endyear=2018&in_bookeeping=

## Report

![image](https://user-images.githubusercontent.com/36068280/35724367-c27dd0d2-07fd-11e8-8b49-f245850a000d.png)
[bugventilation.docx](https://github.com/Dolibarr/dolibarr/files/1688600/bugventilation.docx)

**Comment by eldy** [comment]
Still same trouble with 7.0 ?

**Comment by iaoranamoa** [comment]
I was unable to reproduce it in 7.0
