### ISSUE TITLE
Bug: Impossible to create New Patient 

### ISSUE THREAD

**Issue by monica123m** [Dolibarr/dolibarr#8132]
# Bug

## Environment
- **Version**: 5.0.3
- **OS**: 
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.29
- **Database**: MySQL or MariaDB 5.6.33-log
- **URL**: /cabinetmed/card.php?action=create&canvas=patient@cabinetmed&idmenu=5&mainmenu=patients&leftmenu=

## Report
When i try to create a New Patient profile, by clicking on "New Patient" from the menu, this is what happens. As you can see, the canvas formula is already into the URL but is not working.

Dolibarr ha rilevato un errore tecnico.
This information can be useful for diagnostic purposes:
Data: 20180204201449
Dolibarr: 5.0.3
Livello di funzionalità: 0
PHP: 5.6.29
Server: Apache
UserAgent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Requested URL: /cabinetmed/card.php?action=create&canvas=patient@cabinetmed&idmenu=5&mainmenu=patients&leftmenu=
Referer: http://ceditmanager.altervista.org/cabinetmed/index.php?idmenu=1&mainmenu=patients&leftmenu=
Gestore dei menu: eldy_menu.php

Message: Error this page must be called for canvas pages only

**Comment by hregis** [comment]
@monica123m 
contact @eldy ! this is an external module

**Comment by eldy** [comment]
Try to use version 5.0.1 or 7 of module dolimed. Ask it to the support email of module
