### ISSUE TITLE
Several MySQL errors when updating from 6.03 to 6.04, 6.04 to 6.05 and 6.05 to 7.

### ISSUE THREAD

**Issue by MagicFab** [Dolibarr/dolibarr#8137]
I attempted upgrading from 6.03 to 6.04 using the Debian package dolibarr_6.0.4-4_all.deb. Command line installation of the package went well.

There are several errors in the upgrade script when going from Dolibarr 6.03 to 6.04, from the web interface:

```
Error DB_ERROR_1071: ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files (filepath, filename, entity);
Specified key was too long; max key length is 767 bytes
[...]
Error DB_ERROR_1071: ALTER TABLE llx_product_attribute ADD CONSTRAINT unique_ref UNIQUE 
(ref);Specified key was too long; max key length is 767 bytes
[...]
Error DB_ERROR_1071: ALTER TABLE llx_product_attribute_value ADD CONSTRAINT unique_ref UNIQUE (fk_product_attribute,ref);Specified key was too long; max key length is 767 bytes
[...]
Error DB_ERROR_1071: ALTER TABLE llx_default_values ADD UNIQUE INDEX uk_default_values(type, entity, user_id, page, param);
Specified key was too long; max key length is 767 bytes
```

I am attaching the full log in  a text file.

Full output is attached as txt file.

- **Version**: 6.0.3
- **OS**: Debian Stretch
- **Web server**: Apache 2 (2.4.25-3+deb9u3)
- **PHP**: PHP 7 (7.0.27-0+deb9u1)
- **Database**: MariaDB 10 (10.1.26-0+deb9u1 )
- **URL(s)**: http://localhost/dolibarr (when first invoked after package update)

## Expected and actual behavior

- Database update without errors.

## Steps to reproduce the behavior

- Update Debian package
- Load main dolibarr web page
- Choose option to execut script too update from 5.0 / 6.0.3 to 6.*

**Comment by MagicFab** [comment]
[dolibarr-603-604.txt](https://github.com/Dolibarr/dolibarr/files/1695887/dolibarr-603-604.txt)

**Comment by MagicFab** [comment]
I decided to ignore the errors and complete the upgrade. I then proceeded to upgrade to 6.0.5 and then 7 beta with similar errors (see attached):

- [dolibarr-604-605.txt](https://github.com/Dolibarr/dolibarr/files/1695898/dolibarr-604-605.txt)
- [dolibarr-605-to-7.txt](https://github.com/Dolibarr/dolibarr/files/1695905/dolibarr-605-to-7.txt)

**Comment by hregis** [comment]
@MagicFab 
it is due to the encoding of the database, you must have "utf8mb4" whereas it would be preferable that it is "utf8"

**Comment by eldy** [comment]
utf8mb4 is not a good choice because it needs 4 bytes to store an index and mysql is not able to have index larget than 767 bytes. So if you use utf8mb4 it means you can use index any more on char fields with 255 chars (255 * 4 > 767). 
So you must forget index (very bad) or reduce size of fields (bad too)

Once in 7.0, you can call the page
mydolibarr/install/repair.php
You have an option to set tables back to utf8 instead of utf8mb4

**Comment by MagicFab** [comment]
@eldy merci! Thanks for the detailed explanation, I understand this better now. Perhaps a note in release notes / changelog and a reference in the installation would help others coming up with this. 

Did it happen because I forgot or ignored some installation step in documentation? 

Can you elaborate on what are the implications of setting back to utf8? Is there important dataloss or other future implications? This is not a production system so I can help with other tests if needed, 

Ultimately I did invoke https://mydomain/dolibarr/install/repair.php?force_utf8_on_tables=1 which didn't throw any error, I am just not sure of what are the implications or damage (or lack thereof) now.
