### ISSUE TITLE
BUG: Multycurrency - Exchange rate

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8141]
# Bug
Dolibarr 6.0.5
Setup - Modules/Applications - Multicurrency
If I enter the exchange rate and press modify, nothing happens.

**Comment by absnc** [comment]
I just encountered this bug as well the latest release.

On my demo instance, trying to add "INR" for thirdparty "Indian SAS"

Pressing modify a second time actually performs the update though.
