### ISSUE TITLE
No more clear text password in the database

### ISSUE THREAD

**Issue by Prosouth** [Dolibarr/dolibarr#8142]
# Feature Request
Salted password in the database

## Use case
In order to improve the security, can we store salted passwords in the database instead of clear text passwords?

## Suggested implementation
Adding a salt before storing it

## Suggested steps
http://php.net/manual/en/faq.passwords.php

**Comment by hregis** [comment]
@Prosouth 
it's by default with fresh install of dolibarr 6

**Comment by eldy** [comment]
This bug seems to be fixed into last recent stable version, so I close the bug

**Comment by DanielRuf** [comment]
Not sure but I have used https://github.com/tuxgasy/docker-dolibarr and in my case the option for storing hashed passwords was not enabled by default.

So the option to hash (not encrypt, this should be renamed, encryption is not hashing) is not enabled by default? This should be the case for new setups.

> Encrypt passwords stored in database (NOT as plain-text)

https://wiki.dolibarr.org/index.php?title=Setup_Security
