### ISSUE TITLE
good evening, when i try to upload any pdf document the Software inform me that its too big, we already increase the value but it still the same error. 

### ISSUE THREAD

**Issue by RobertoGarciaRibeiro** [Dolibarr/dolibarr#8147]
# Bug

## Environment
- **Version**: 6.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.38
- **URL**: /ecm/index.php

**Comment by atm-maxime** [comment]
This is not an issue regarding the software development, it's directly related to your environnement.
However, you should check the UPLOAD_FIL_SIZE and POST_MAX_SIZE in you PHP setup (php.ini), and also check the Dolibarr setup (Home > Setup > Security > Files)
