### ISSUE TITLE
Bug sending emails with invoices, orders, budgets ... in versions 5.0.7 - 6.0.5

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#8152]
# Bug
Dear sirs, in the last days I have updated Dolibarr 4.0.6 to version 5.07 (and on the day of this email to version 6.0.5) and in both versions, 5 and 6, I have found a common error, and it is that when sending an email for a quote, order, invoice ... the following error is displayed:

"Error [120]: Ran into problems sending Mail. Response: 501 5.1.3 Bad recipient address syntax"

Investigating a little I could find what is the cause of error, in the tab Third, in the "Name of the company" if a comma appears, "," will give the error. An example

**Industries ABC, S.L.** This name of Third will give error.
**Industries ABC S.L.** This name of Third will not give error.

Sorry if the translation is wrong, and I hope you find it useful.

a greeting

Juan Brillo

## Environment
- **Version**: Dolibarr 5.0.7   and Dolibarr 6.0.5
- **OS**: OpenSuse Leap 42.3
- **Web server**: Apache 2.4.23-19.1
- **PHP**: PHP 5.5.14-91.2
- **Database**: MariaDB 10.0.32-26.1

Spanish Translation

Estimados señores, en los ultimos dias he actualizado Dolibarr 4.0.6 a la version 5.07 (y en el dia del presente correo a la version 6.0.5) y en las dos versiones, 5 y 6, he encontrado un error común, y es que a la hora de mandar un correo electronico de un presupuesto, pedido, factura... se muestra el siguiente error:

"Error [120]: Ran into problems sending Mail. Response: 501 5.1.3 Bad recipient address syntax"

Investigando un poco he podido encontrar cual es la causa de error, en la ficha Terceros, en el "Nombre de la empresa" si aparece una coma "," , dará el error. Un ejemplo

Industrias ABC, S.L.    Este nombre de Tercero dará error.
Industrias ABC S.L.     Este nombre de Tercero no dará error.

Disculpen si la traduccion es erronea, y espero que les resulte util.

Un saludo

Juan Brillo

**Comment by Conspir3D** [comment]
Can confirm this at 6.0.4
Thanks for this bug report as i stumbled on the same a couple of days ago and do the mailing manual. Now i know, how to avoid this problem but should be fixed.

**Comment by EhtuCom** [comment]
I'm having the same problem on version 7.0.0

**Comment by Telofis26200** [comment]
+1
I'm having the same problem on version 7.0.0

**Comment by danieldewenir** [comment]
Hola, en la version 7 sigue ocurriendo, se puede solucionar añadiendo este código en archivo htdocs/core/actions_sendmails.inc.php en la linea 199 justo antes de $sendto=implode(',',$tmparray);
foreach($tmparray as $key=>$value){
    $tmparray[$key] = str_replace(","," ",$value);
}
$sendto=implode(',',$tmparray);
Saludos
