### ISSUE TITLE
Bug: Bank data import not possible / unnecessary required fields

### ISSUE THREAD

**Issue by code-chicken** [Dolibarr/dolibarr#8153]
# Bug
Bank data import not possible / unnecessary required fields

## Environment
- **Version**: 6.0.5
- **OS**: Gentoo
- **Web server**: nginx 1.12.1
- **PHP**: 7.0.23
- **Database**: mariadb 10.1.24
- **URL(s)**: /imports/import.php?step=2&datatoimport=societe_3&excludefirstline=1&separator=%2C&enclosure="

## Expected and actual behavior
It should be possible to import bank data in the following situation:

- Field deskcode is empty. I don't even know what this field is good for.
- Field cle-rib (key) is empty. I don't even know what this field is good for.
- Field bankcode is empty but field BIC or field IBAN is filled
- Field bankaccountnumber is empty but field IBAN is filled

Expected: In the cases above it should be possible to import bank data.
Actual: The data will not be imported if any of the fields above have not content.

Actually, if I add bank data manually, the required fields are completely different. In that case a label field is required which is not when importing bank data.

## Steps to reproduce the behavior
Just try to import bank data with any of the four cases explained above. An example import file is attached.

## Attached files
[bankdata-example.zip](https://github.com/Dolibarr/dolibarr/files/1703170/bankdata-example.zip)

**Comment by torvista** [comment]
I am modifying this for clearer information in the example csv.
