### ISSUE TITLE
Bug: translation label for a multilanguage product are always in english on pdf

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#8156]
# Bug

## Environment
- **Version**: 7.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.33-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB-0+deb8u1
- **URL**: /product/traduction.php?id=5

**Comment by atm-maxime** [comment]
@grandoc I can't reproduce. Come see me ;)
