### ISSUE TITLE
Bug: Import does not list acceptable formats.

### ISSUE THREAD

**Issue by JBruceDawson** [Dolibarr/dolibarr#8169]
# Bug
Import does not list acceptable formats.

## Environment
- **Version**: 6.0.5
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 7.0.27-0+deb9u1
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL**: /dolibarr/imports/import.php?step=2&datatoimport=societe_1&excludefirstline=1&separator=%2C&enclosure=%22

## Report
/var/log/apache2/error.log says:

[Fri Feb 09 13:16:10.947403 2018] [mpm_prefork:notice] [pid 7734] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Fri Feb 09 13:16:10.947426 2018] [core:notice] [pid 7734] AH00094: Command line: '/usr/sbin/apache2'
[Fri Feb 09 13:20:37.792741 2018] [:error] [pid 5947] [client 192.168.56.28:53267] PHP Warning:  require_once(disabled/PHPExcel.php): failed to open stream: No such file or directory in /usr/share/dolibarr/htdocs/core/modules/import/import_xlsx.modules.php on line 83, referer: http://river.localnet/dolibarr/imports/import.php?leftmenu=import
[Fri Feb 09 13:20:37.792785 2018] [:error] [pid 5947] [client 192.168.56.28:53267] PHP Fatal error:  require_once(): Failed opening required 'disabled/PHPExcel.php' (include_path='/var/www/html/htdocs') in /usr/share/dolibarr/htdocs/core/modules/import/import_xlsx.modules.php on line 83, referer: http://river.localnet/dolibarr/imports/import.php?leftmenu=import

Symptoms:

![screenshot - 02092018 - 02 09 59 pm](https://user-images.githubusercontent.com/11779528/36045274-2b32876c-0da3-11e8-8a49-6bdf7977bd6a.png)

Notes:

I looked up PHPExcel, and it appears to be officially depreciated (https://github.com/PHPOffice/PHPExcel). Perhaps including the module with the Dolibarr distribution will fix this.

**Comment by JBruceDawson** [comment]
Uhh. Deprecated, not "depreciated".

**Comment by fappels** [comment]
Can you check if $dolibarr_lib_PHPEXCEL_PATH is set in your conf.php. When not set, PHPOffice/PHPExcel will be used. PHPOffice/PHPExcel  seems to be set deprecated 2 months ago. If correcting your conf.php solves the issue, maybe you can rename your issue to 'Feature request: Update deprecated PHPOffice/PHPExcel to PHPOffice/PhpSpreadsheet.

**Comment by JBruceDawson** [comment]
Thank you for looking into this!

In /etc/dolibarr/conf.php, there is:

$dolibarr_lib_PHPEXCEL_PATH='disabled';

So I'm assuming that means it is set.

--Bruce

**Comment by fappels** [comment]
you must put // in front of it to unset

**Comment by JBruceDawson** [comment]
Yipee! That worked. Thank you!

**Comment by fappels** [comment]
You're welcome. See you created #8172 for the deprecated lib, so you can close this one.
