### ISSUE TITLE
Feature Request: Update deprecated PHPOffice/PHPExcel to PHPOffice/PhpSpreadsheet.

### ISSUE THREAD

**Issue by JBruceDawson** [Dolibarr/dolibarr#8172]
# Feature Request
Feature Request: Update deprecated PHPOffice/PHPExcel to PHPOffice/PhpSpreadsheet.

## Use case
Trying to use the Import feature of Dolibarr results in no "Acceptable Formats" with the standard configuration. One has to comment out the "$dolibarr_lib_PHPEXCEL_PATH='disabled';" line in Dolibarr's config.php before any will show up. 

## Suggested implementation
PHPExcel has been deprecated in favor or PHPSpreadsheet according to https://github.com/PHPOffice/PHPExcel

## Suggested steps
Replace PHPExcel with PHPSpreadsheet.

**Comment by eldy** [comment]
$dolibarr_lib_PHPEXCEL_PATH='disabled' is on when using the standard debian distribution because phpexcel was not available into debian.
When making a fresh install with the debian package found on dolibarr.org site, you should have excel import supported because lib is embedded.

**Comment by Langlais115** [comment]
I'm on it.
I'm nearly there, just one last bug to fix and I'll push my PR for this feature request, by next week I guess.

**Comment by Langlais115** [comment]
1. Does anyone know which version of phpSpreadSheet are we using at the moment? I couldn't find the info. The version we have is different from the actual documentation.
2. Why does this dependency is not included into the composer.json as was phpExcel?

**Comment by eldy** [comment]
Version of phpspreadsheet is a big mystery (initial contributor did not provide information). And there is no version information anywhere.
May be first step is to upgrade library (in a separate PR) to a known version. Including reference into composer.json can be done too.

**Comment by eldy** [comment]
Goal of PR is:
Edit the file htdocs/includes/modules/import/import_xlsx.modules.php to replace all call to PHPExcel library to similare function of PHPSpreadSheet. 
The work was already done into file  htdocs/core/modules/export/export_excel2007new.modules.php ,  used for export, so we have to do it now for the file use to import xlsx files.
This is the last file that use PHPExcel, so we will be able to remove completely PHPExcel that is a deprecated library. To test it, just run any import of a xlsx file with the import assistant (menu home - tools - import).

**Comment by cfoellmann** [comment]
this is done. CLOSE
