### ISSUE TITLE
Hover contact don't show informations

### ISSUE THREAD

**Issue by PlatiScript** [Dolibarr/dolibarr#8179]
# Bug

For example in the "contacts/adresses" page in a commercial proposal when we hover the name of the contact, there is some informations (name, mail, phone address) but only the name is there and the 3 last informations are empty even if this informations are put in the contact card.

**Comment by dolibarr95** [comment]
Hi
Dolibar version ?
works for me with Dolibarr 6.0.0

**Comment by PlatiScript** [comment]
6.0.5
