### ISSUE TITLE
Bug: Do a mass stock transfer with products that don´t have stock

### ISSUE THREAD

**Issue by jmsandovalp** [Dolibarr/dolibarr#8186]
When I try to do a mass stock transfer (../product/stock/massstockmove.php) with products that don´t have stock in any warehouse, I get this error:

_Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180212180237
Dolibarr: 6.0.5
Level of features: 0
PHP: 7.0.22-0ubuntu0.16.04.1
Server: Apache/2.4.18 (Ubuntu)
OS: Linux AIMECLOUD_DESARROLLO 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

Requested URL: /itmdemaq/product/stock/massstockmove.php
Referer: http://cloud.dolibarrmexico.com:99/itmdemaq/product/stock/massstockmove.php
Menu manager: eldy_menu.php

Message: Bad value saved into sessions_

Dolibarr 6.0.5

**Comment by atm-maxime** [comment]
Seems fixed in 6.0.6 to me. I created a new product and did a mass transfert and I correctly have 2 stock movements. Of course I allowed negative stock first in the stock module setup.

**Comment by jmsandovalp** [comment]
I have tested again and the problem continues. I attach a file with the configuration of stock and the card of two products.
[MASS STOCK TRANSFER_v1.docx](https://github.com/Dolibarr/dolibarr/files/1807903/MASS.STOCK.TRANSFER_v1.docx)
