### ISSUE TITLE
Various journal do not exits

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#8190]
Dolibarr 7.0

Accountancy module
Link to Various Jounrl / A nouveau jounal go to 404 pages

**Comment by eldy** [comment]
The menu should be visible in experimental or develop mode only.
Are you with MAIN_FEATURES_LEVEL to 0 and last version of 7.0 branch ?

**Comment by aspangaro** [comment]
Various journal / miscellaneous journal / has new journal visible only with main feature 2 < Dolibarr v7.0.x

In Dolibarr 8.0.x, I have introduced a constant. ACCOUNTANCY_SHOW_DEVELOP_JOURNAL

Please close this issue.

**Comment by ghost** [comment]
All right
