### ISSUE TITLE
invoice index page do not appear proeperly when a lot of invoices/orders are to be processed

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8191]
# Bug
the invoice index page does not show and triggers a message with a jquery issue
…js/jquery.min.js?version=6.0.4:3

## Environment
- **Version**:6.0.4
- **OS**: DEBIAN
- **Web server**: APACHE
- **PHP**: 5.5
- **Database**: mysql
- **URL(s)**: compta/index.php?

## Expected and actual behavior
a proper rendering of page even with a big number of orders/invoices (> 10 000)

## [Attached files](https://help.github.com/articles/issue-attachments) 
[*Files*]
![bug_jquery_doli604](https://user-images.githubusercontent.com/919513/36167328-c27a6630-10f5-11e8-9601-6797ae43b11a.png)

**Comment by eldy** [comment]
Still same pb with 7.0 version ?

**Comment by tiaris** [comment]
It is not possible to install beta or not stabilised versions for users with > 100 000 orders, invoices....
I changed the index page removing invoice lists which are too large, so page can be shown.
Message indicates a problem with a jquery library

**Comment by hregis** [comment]
@tiaris 
en général c'est une boucle qui se crée !
as-tu augmenté le temps d'execution des scripts PHP pour éviter le timeout ?
ensuite vérifie les logs apache et dolibarr pour vérifier si c'est une boucle et d'où elle vient.

**Comment by tiaris** [comment]
Je n'ai rien trouvé dans le log dolibarr. J'ai l'impression que c'est dans l'affichage que ça se passe.
Sur un site en prod de cette taille, pas évident de faire des tests...
