### ISSUE TITLE
PHP Warning 

### ISSUE THREAD

**Issue by dolifox** [Dolibarr/dolibarr#8204]
# Bug
[*Warning error*]

## Environment
- **Version**: [*6.0.5*]
- **OS**: [*XAMPP Windows 10*]
- **Web server**: [*2.4.29*]
- **PHP**: [*4.7.7*]
- **Database**: [*10.1.30*]

Hello, I encountered errors with php 7. I looked at the other forums but the errors do not match. Can you help me ?

- When I add client "Warning: Use of undefined constant _ROWS_2 - assumed '_ROWS_2' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\dolibarr\htdocs\societe\card.php on line 1128"
![1128](https://user-images.githubusercontent.com/36580134/36347578-c8198c58-14ae-11e8-96d0-817b11919068.jpeg)

- Bank / caisse -> bank writing. "Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\dolibarr\htdocs\core\actions_massactions.inc.php on line 48
![48](https://user-images.githubusercontent.com/36580134/36347580-cda99a00-14ae-11e8-914c-0bf02899451b.jpeg)

- In "entrepôt" :
Warning: A non-numeric value encountered in C:\xampp\htdocs\dolibarr\htdocs\core\lib\functions.lib.php on line 3562
Warning: A non-numeric value encountered in C:\xampp\htdocs\dolibarr\htdocs\core\lib\functions.lib.php on line 3576
Warning: A non-numeric value encountered in C:\xampp\htdocs\dolibarr\htdocs\core\lib\functions.lib.php on line 3584

![mouvement errors](https://user-images.githubusercontent.com/36580134/36347628-f78dc188-14af-11e8-81be-c570df8e3633.png)

[functions.lib.php.zip](https://github.com/Dolibarr/dolibarr/files/1734342/functions.lib.php.zip)

Thank you,

Best regards

**Comment by inoveaconseil** [comment]
Is it still relevant ?

**Comment by dolifox** [comment]
I use now php 7.0 and not 7.1 and it's now ok
