### ISSUE TITLE
Error in new version 7.0

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#8209]
# Bug
Query selector is dissapear

## Environment
- **Version**: 7.0
- **OS**: Linux us-imm-web76.main-hosting.eu 2.6.32-773.26.1.lve1.4.35.el6.x86_64 #1 SMP Tue Sep 26 06:34:34 EDT 2017 x86_64
- **Web server**: Apache
- **PHP**: 5.6.32
- **Database**:MySQL or MariaDB 10.1.31-MariaDB
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Expected: Normal operation of the search box located in the menu on the left side, but when you want to perform a search you can not see the box where you can enter the characters of what you want to search.
Note: In another installation of the same version if the search selector works correctly

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![2018-02-20](https://user-images.githubusercontent.com/28205134/36445141-f4afcff8-1642-11e8-9702-b8eb6005d412.png)

**Comment by atm-maxime** [comment]
I think this has been fixed. Can you confirm ?
