### ISSUE TITLE
Bug : Impossible to close dispatch if more than ordered

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#8211]
# Bug
...or misunderstanding on my part

When I dispatch product of a supplier order, if I receive more than the quantity I've ordered :
I can't close  even if the check box _Close the order "All received products" automatically if all products have been received._ is checked

The only solution is to force receive in order card.

## Environment
- **Version**: 6.0.0 
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: fourn/commande/dispatch.php?id=

In fournisseur.commande.class.php we can read :
```php
$diff_array=array_diff_assoc($qtydelivered,$qtywished);
if (
count($diff_array)==0 
&& count($keysinwishednotindelivered)==0 
&& count($keysindeliverednotinwished)==0
) //No diff => mean everythings is received
```
So we only valid if the quantity received is equal and not if there is more.

## Suggestion
```php
//Example of values
$qtydelivered[10]=22;
$qtydelivered[11]=28;
$qtydelivered[15]=10;

$qtywished[10]=20;
$qtywished[11]=28;
$qtywished[15]=10;

$result = array_diff_assoc($qtydelivered, $qtywished);

$close=0;

//there are some difference betwen the two array
if($result){
	
	//scan the array of results
	foreach($result as $key => $value){
	
		//if the quantity delivered is greater or equal to wish quantity
		if($qtydelivered[$key] >= $qtywished[$key] ){
		
			$close++;
		}
		
	}
}

//all the products are received equal or more than the wished quantity
if($close == count($result)){
	$this->Livraison($user, $date_liv, 'tot', $comment); 
}


```

Tks for reading

**Comment by BebZ** [comment]
True that it could close automatically if received more

but is it the behaviour everyone wants ?

For me it is coherent, even a new status (> status products received : we
can add a status "delivered, but with a difference in the qty")

if($qtydelivered[$key] >= $qtywished[$key] ){					$close*2*++



*Hubert ANDRIOLO*
*Gérant F.M. MEDICAL et NORD HYGIENE*
Mobile: +33 (0) 6 23 10 17 31
Fax: +33 (0) 9 56 51 95 71
Site: www.fournisseur-medical.com


*FM MEDICAL - NORD HYGIENE*
*2 RUE DE LA JUSTICE *
*62410 BENIFONTAINE *
SIRET : 532 788 700 00021
N° de TVA : FR15 532 788 700

2018-02-21 10:12 GMT+01:00 dolibarr95 <notifications@github.com>:

**Comment by dolibarr95** [comment]
Hi
Tks for reply
Your idea of a new status is good.
What do you think about a new constant (eg: CLOSE_ORDER_IF_RECEVIED_MORE.....) ?

**Comment by BebZ** [comment]
yes it is right ;)

*Hubert ANDRIOLO*
*Gérant F.M. MEDICAL et NORD HYGIENE*
Mobile: +33 (0) 6 23 10 17 31
Fax: +33 (0) 9 56 51 95 71
Site: www.fournisseur-medical.com


*FM MEDICAL - NORD HYGIENE*
*2 RUE DE LA JUSTICE *
*62410 BENIFONTAINE *
SIRET : 532 788 700 00021
N° de TVA : FR15 532 788 700

2018-02-21 12:26 GMT+01:00 dolibarr95 <notifications@github.com>:

**Comment by dolibarr95** [comment]
Hi
I try a PR...

**Comment by dolibarr95** [comment]
Hi
The constant to set this hidden option is 
```
SUPPLIER_ORDER_MORE_THAN_WISHED
```
