### ISSUE TITLE
[BUG] [GRH] Issue with messages (confirmation message & email subject) when refusing holidays. 

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#8215]
# Bug
When refusing a holiday, the confirmation question asks to confirm the opposite of the action requested

## Environment
- **Version**: 6.0.4
- **URL(s)**: /holiday/card.php?id=22&action=refuse

## Expected and actual behavior

Happened in the french version;
I refuse a holiday request and the shown text is:
"Refuser la demande de congés / Êtes-vous sûr de vouloir valider la demande de congés ?"

So I am requested to validate the holiday request while I should be requested if I confirm the refusal of the holiday request.

Further on, the email says "<Company> - Accès refusé"  which means "Access refused" in the subject which is also not inline with the action.

## Suggested implementation
This is possibly just a "translation" issue.

**Comment by atm-maxime** [comment]
Ok, I just changed these 2 translations in the French language.
