### ISSUE TITLE
Create new module based in an existent

### ISSUE THREAD

**Issue by amoreira1** [Dolibarr/dolibarr#8217]
Hi All
Im not a very experient developer, but i need to create a new module .
Is it possible duplicate the module of invoice and give a different name ?
I need a module that is almost the same of module of the invoice, but i would like to give a different name .

If possible can anyone tell me how to do it step by step?
Thank you in advance

**Comment by dolibarr95** [comment]
Hi
if you're speaking french  : 
https://www.dolibarr.fr/forum/511-creation-dun-nouveau-module

You can also download a free module from dolistore and work on it.

**Comment by eldy** [comment]
Not an issue, but a question, so i close the ticket (you can try to ask on forums)
