### ISSUE TITLE
[Bug] Cloned orders keep the link to the original invoices

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#8220]
# Bug
This is an issue introduced somewhere in one of the previous updates of version 6 and it's still there in the version 7.0.0.
When cloning an order, the link to the issued invoices is kept in the new order. This is not useful, since the cloning of orders is mainly thought for duplication of orders, not for their invoices.

## Environment
- **Version**: 7.0.0
- **OS**: Linux 3.10.102 #15254 SMP Fri Jan 26 06:40:50 CST 2018 x86_64
- **Web server**: Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141
- **PHP**: 5.6.31
- **Database**: MariaDB 5.5.57
- **URL(s)**: /dolibarr/htdocs/commande/card.php?id=231&socid=196&action=clone&object=order

## Expected and actual behavior
Expected behavior is that all the properties of an order are cloned except the connection to the issued invoices of the original order.

**Comment by atm-arnaud** [comment]
Hello,

I just tried on a 7.0.0 last updated and i can't reproduce your bug.

I have try on : 

1. Proposal with invoices and orders
2. Order with proposal and invoice

And in both cases, my clone hasn't invoice or other objects linked (table is empty) Are you sure that comes not from an extra module ?

regards,

**Comment by minigitmax** [comment]
Hi Arnaud,

Sorry for my late reply. 
Did you try on suppliers' orders or clients' orders? The issue applies only to supplier orders. Give a try with them...
(No extra module loaded on orders...)

Best regards
