### ISSUE TITLE
Bug: shipment API error, sql error when weight, height, size missing

### ISSUE THREAD

**Issue by paulchui123** [Dolibarr/dolibarr#8222]
# Instructions
when i try to create shipment with API, mysql error occurred saying that the weight, height, size missing

i finally figured out that, when  weight, height, size missing the sql error will occur

#API 
http://mywebsite.com/api/index.php/shipments
request content:
{
  "socid": "1319",
  "ref_customer": "1304",
  "origin_id": 1708,
"origin_type": "commande"
 }

error message:
{
  "error": {
    "0": "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' , , , , , null, null, null, 0, '')' at line 1 - sql=INSERT INTO llx3a_expedition (ref, entity, ref_customer, ref_int, date_creation, fk_user_author, date_expedition, date_delivery, fk_soc, fk_projet, fk_address, fk_shipping_method, tracking_number, weight, size, width, height, weight_units, size_units, note_private, note_public, model_pdf, fk_incoterms, location_incoterms) VALUES ('(PROV)', 1, '1304', null, '2018-02-23 10:59:59', 1, null, null, 1319, 0, null, null, '', , , , , , , null, null, null, 0, '')",
    "code": 500,
    "message": "Internal Server Error: Error creating shipment"
  }
}

**Comment by wtfbrb** [comment]
I tried to pass static values for those as well and I still can't create a shipment...did you ever have any luck creating one from an order?
