### ISSUE TITLE
Dolibarr 7.0.0 - "External Site" module issue : "$conf->global->EXTERNAL_LABEL" displayed instead of site name

### ISSUE THREAD

**Issue by LesCarnets** [Dolibarr/dolibarr#8227]
# Bug
Dolibarr 7 - External WebSite module issue

## Environment
- **Version**: 7.0.0
- **OS (host)**: Linux 2.6.32-openvz-042stab127.2-amd64 #1 SMP Thu Jan 4 16:43:57 MSK 2018 x86_64
- **Web server**: Apache
- **PHP**: 7.0.27
- **Database**: MYSQL (MySQL or MariaDB 5.5.5-10.1.31-MariaDB-1~jessie - DRIVER: mysqli (mysqlnd 5.0.12-dev - 20150407))
- **URL(s)**: ./externalsite/frames.php?idmenu=7&mainmenu=externalsite

## Expected and actual behavior
- **Expected behavior**: If I set "HelloWorld" as name for my External site in configuration panel of the "external Web Site" module, in the menu bar on top of Dolibarr window, I am supposed to read there, after the picture "www" the name of my Site recorded from the configuration panel ("HelloWorld").
- **Actual behavior**: The display text in the menu bar is not the expected name but "$conf->global->EXTERNAL_LABEL" (instead of "HelloWorld").

## Steps to reproduce the behavior
1) Deploy a 5.04 Dolibarr
2) Deploy the moldue "Extternal Site" and configue it
3) Upgrade Dolibarr to verson 7.0.0

## Screenshot
Sorry for the Screenshot in French :
![dolibarr_7 0 0_externalsite-issue](https://user-images.githubusercontent.com/36789892/36630064-894991ce-1960-11e8-992a-c14b65a8b3cc.png)

Thank you by advance for your support on this issue :-)

Best regards,

**Comment by MkLHX** [comment]
I'm trying to find the bug, but i just started use and dev on dolibarr....not sure this is the good error..
./htdocs/externalsite/admin/externalsite.php
Line 100
```
print "<td><input type=\"text\" class=\"flat\" name=\"EXTERNALSITE_LABEL\" value=\"". (GETPOST('EXTERNALSITE_LABEL','alpha')?GETPOST('EXTERNALSITE_LABEL','alpha'):((empty($conf->global->EXTERNALSITE_LABEL) || $conf->global->EXTERNALSITE_LABEL=='ExternalSite')?'':$conf->global->EXTERNALSITE_LABEL)) . "\" size=\"12\"></td>";
```

**Comment by LesCarnets** [comment]
> I'm trying to find the bug, but i just started use and dev on dolibarr....not sure this is the good error..
./htdocs/externalsite/admin/externalsite.php
Line 100

Hi @MkLHX ,

Thank you very much for your reply. Unfortunatly, it seems this file is not defining the display in the menu but the admin part of the module (where we can set URL and label of our website)... I tried to replace externalsite/admin/externalsite.php with file from another version (5.0.4 with normal behavours for example) but it didn't solve the issue...

I would eighter go to file creating the menu bar...

Best regards,

**Comment by MkLHX** [comment]
Maybe here 
```
\htdocs\core\menu\standard
```

**Comment by LesCarnets** [comment]
Maybe...
(I don't know, I am not a developer)

**Comment by eldy** [comment]
Can you try to disable and reenable module "external website"

**Comment by MkLHX** [comment]
Yep! Done! So easy i never think it's can be this!

**Comment by javyer** [comment]
I can confirm that disabling and re-enabling module, correct the same problem for me too.
