### ISSUE TITLE
During installation, default port is 3306 instead of 5432 [PostgreSQL]

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Dolibarr/dolibarr#8236]
# Bug
When installing branch develop on a machine with PostgreSQL, the default/suggested port is 3306. It should be 5432 which is the default PostgreSQL port. 

This causes confusion. It leads to a connection error, suggesting the password might be wrong. I investigated while and looked at PostgreSQL configuration, and logs, to find issues, but none appeared on that side. 
After a while I realized Dolibarr wasn't connecting to PostgreSQL's port. 

## Environment
- **Version**: 8.0 alpha (develop) and 7.0
- **OS**: Debian 9.0
- **Web server**: nginx 1.10.3
- **PHP**: 7.0.27
- **Database**: PostgreSQL 9.6
- **URL(s)**: /install/fileconf.php?selectlang=auto

## Expected and actual behavior
Suggest port 5432 for PostgreSQL databases

## Steps to reproduce the behavior
On a machine with PostgreSQL available. 
Git clone develop branch, configure nginx to expose htdocs, and go the URL. 

[*Files*]
![dolibarr-install-pgsql-3306](https://user-images.githubusercontent.com/4953748/36644825-26f5f1d8-1a60-11e8-8ec1-f47ebbb135c8.png)

**Comment by eldy** [comment]
what happen if you switch the "Type du pilote" to another value and g back to psql ?

**Comment by guillaume-uH57J9** [comment]
@eldy psql is the only database option available, other options are greyed out. 

I will verify if installing additional php extensions / database backend on that server would allow me to select a different option

**Comment by guillaume-uH57J9** [comment]
The behavior changes after installing php-mysql. 

Without php-mysql: 
* psql is the only available option, psql is selected by default, 3306 is the port by default

With php-mysql:
* Options psql and mysql are both available, mysql is selected by default, 3306 if the default port
* When changing the selection from mysql to psql, the port is changed to 5432

To sum up, the installation page only will show the correct port if php-mysql is available and initially selected. 
But it shows the wrong port if psql is the only available option (ie php-mysql not installed). 

Keep in mind a server using psql doesn't need php-mysql, so it make sense for php-mysql NOT to be installed.

**Comment by guillaume-uH57J9** [comment]
I fetched branch 7.0 and observe it is also affected. 

Is there now enough information to triage this bug?

**Comment by marcosgdf** [comment]
I've experienced this issue long time ago, I think it is a JS issue
