### ISSUE TITLE
Installation fails due to SQL syntax error [PostgreSQL]

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Dolibarr/dolibarr#8237]
# Bug
Installing from the develop branch fails with the following SQL syntax error: 

> Erreur SQL DB_ERROR_SYNTAX ERROR: 42601: syntax error at or near "ENGINE" LINE 1: ...int DEFAULT '0', entity integer DEFAULT 1 ) ENGINE=Inn... ^ LOCATION: scanner_yyerror, scan.l:1086

This is the query Dolibarr attempted to run: 

>  Request 129 : CREATE TABLE llx_expensereport_rules ( rowid integer AUTO_INCREMENT PRIMARY KEY, datec datetime DEFAULT NULL, tms timestamp, dates datetime NOT NULL, datee datetime NOT NULL, amount double(24,8) NOT NULL, restrictive tinyint NOT NULL, fk_user integer DEFAULT NULL, fk_usergroup integer DEFAULT NULL, fk_c_type_fees integer NOT NULL, code_expense_rules_type varchar(50) NOT NULL, is_for_all tinyint DEFAULT '0', entity integer DEFAULT 1 ) ENGINE=InnoDB
> Executed query : CREATE TABLE llx_expensereport_rules ( rowid SERIAL PRIMARY KEY, datec timestamp DEFAULT NULL, tms timestamp without time zone DEFAULT now() NOT NULL, dates timestamp, datee timestamp, amount numeric(24,8) NOT NULL, restrictive smallint NOT NULL, fk_user integer DEFAULT NULL, fk_usergroup integer DEFAULT NULL, fk_c_type_fees integer NOT NULL, code_expense_rules_type varchar(50) NOT NULL, is_for_all smallint DEFAULT '0', entity integer DEFAULT 1 ) ENGINE=InnoDB 

## Environment
- **Version**: 8.0 / develop
- **OS**: Debian 9.0
- **Web server**: nginx 1.10.3
- **PHP**: 7.0.27
- **Database**: PostgreSQL 9.6
- **URL(s)**: /install/step2.php

## Expected and actual behavior
No SQL syntax error

## Steps to reproduce the behavior
Install Dolibarr using a PostgreSQL database

**Comment by guillaume-uH57J9** [comment]
Keyword ENGINE seems to be MySQL-specific based on this discussion : https://www.postgresql.org/message-id/200407252040.i6PKeA624692%40candle.pha.pa.us

**Comment by hregis** [comment]
@guillaume-uH57J9 
this is just a syntax error ! https://github.com/Dolibarr/dolibarr/pull/8239
