### ISSUE TITLE
Problem with Extrafield and type 'date Heure' 

### ISSUE THREAD

**Issue by I-Dromel** [Dolibarr/dolibarr#8240]
Extrafields avec type 'Date/heure

## Environment
- **Version**: 7.0.0
- **OS**: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.27
- **Database**: MySQL or MariaDB 5.5.59-0+deb7u1-log
- **URL**: /Dolibarr/htdocs/comm/propal/card.php

## Report
Hello,
In version 6.0.4, or in 7.0, I created 2 extrafields (date of arrival and date of departure) of type 'date / time' in the header of the propale.
When I enter the fields in the propale the hours are shifted by one hour.
If I want to set the time, she shifts again.
Example:
Date of Arrival: 26/02/2018 03:00
Date of departure: 27/02/2018 07:00

If I click on the pencil (to change) of Arrival Date the time of the arrival date changes to 04:00
the time of the departure date remains at 07:00
By clicking on "Edit" everything stays normal
Result:
Date of Arrival: 26/02/2018 03:00
Date of departure: 27/02/2018 07:00

If I click on the pencil (to change) from Start date the time of the departure date goes to 08:00
the time of the departure date remains at 03:00
By cons by clicking on "Change" the time of the arrival date goes to 04:00
Result:
Date of Arrival: 26/02/2018 04:00
Date of departure: 27/02/2018 08:00

And this error also occurs in versions 6.0.5 and 7.0
Thank you for your help.
--------------------------
Bonjour,
En version 6.0.4, ou en 7.0,  j'ai créé 2 extrafields (date d'arrivée et date de départ) de type 'date/heure' dans l'entête de la propale.
Quand je renseigne les champs dans la propale les heures se décalent d'une heure.
Si je veux remettre l'heure, elle se décale de nouveau.
Exemple:
Date d'arrivée :  26/02/2018 03:00
Date de départ: 27/02/2018 07:00

Si je clique sur le crayon (pour modifier) de Date d'arrivée l'heure de la date d'arrivée passe à 04:00
                                                                                        l'heure de la date de départ reste à 07:00
En cliquant sur "Modifier" tout reste normal
Résultat:
Date d'arrivée :  26/02/2018 03:00
Date de départ: 27/02/2018 07:00

Si je clique sur le crayon(pour modifier) de Date de départ l'heure de la date de départ passe à 08:00
                                                                                         l'heure de la date de départ reste à 03:00
Par contre en cliquant sur "Modifier"  l'heure de la date d'arrivée passe à 04:00
Résultat:
Date d'arrivée :  26/02/2018 04:00
Date de départ: 27/02/2018 08:00

Et cette erreur se produit aussi en versions 6.0.5 et 7.0
Merci de votre aide.
Belle journée.

**Comment by ATM-Nicolas** [comment]
Hello, i handle this
