### ISSUE TITLE
Add Page Title module Expense Reports

### ISSUE THREAD

**Issue by withheld** [Dolibarr/dolibarr#8241]
# Bug

Add page title to module Expense Reports. Suggested fix included

*First time posting suggestion. Please let me know if this  format is fine for 28+ more page titles.

## Environment
- **Version**: 6.0.4 ~ 7.0.0

- **URL(s)**: https://github.com/Dolibarr/dolibarr/blob/1666f371bfd421c8a556d4afa49bf0c2bbeb7a01/htdocs/admin/expensereport.php#L198

## Suggested fix
`llxHeader('',$langs->trans("ExpenseReportsSetup"));`

**Comment by inoveaconseil** [comment]
Fixed in develop

**Comment by withheld** [comment]
Thanks for the update . One question, for further suggested fixes, is the format I posted sufficient?
