### ISSUE TITLE
Feature Request:Allow negative quantity for dispatch

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#8243]
Hi!
Allow negative quantity for dispatch a supplier order in order to correct a mistake.

## Use case
The storekeeper made an error in the supplier order dispatch. He enter a quantity for a product, he hasn't received.
Actually the only way to correct are : 

Solution 1
1. In stock of product create a negative movement to restore good stock value
2. Correct in sql the llx_commande_fournisseur_dispatch line

Solution 2
1. Wait to really receive the product

It could be nice if in fourn/commande/dispatch.php page the storekeeper could enter a negative value to directly create the negative movement and "reset" the quantity dispatched value.

## Feature Request
Allow negative quantity for dispatch.

Tks

**Comment by jameszhang023** [comment]
@dolibarr95 
I have mentioned this PR, 
https://github.com/Dolibarr/dolibarr/issues/8080

Please look at my commit:
https://github.com/JamesZhangChina/dolibarr/commit/8d51548951601fda93eeae528899d727c2f0c840

Hope to help you
^_^

**Comment by dolibarr95** [comment]
Hi
Tks @JamesZhangChina, I read it.

**Comment by dolibarr95** [comment]
Hi @eldy and others :-) !

Can you please give help : 
How can we correct a wrong (too much) quantity in the Goods Receptions -> dispatch ?

Tks for reading

**Comment by dolibarr95** [comment]
Hi 
We could also on your dispatch.php patch replace
```php
$remaintodispatch = price2num($objp->qty - (( float ) $products_dispatched[$objp->rowid]), 5); // Calculation of dispatched
```
with
```php
$alreadydispatched = $products_dispatched[$objp->rowid];
if($alreadydispatched<0){
	$alreadydispatched=0;
}
$remaintodispatch = price2num($objp->qty - (( float ) $alreadydispatched), 5); // Calculation of dispatched
```
To keep the right value to dispatch.
_Eg :_
qty to dispatch 6
dispatch -1
will display to dispatch 7
with this patch it will display 6

@JamesZhangChina can you push your PR in dolibarr ?

Tks for reading
