### ISSUE TITLE
BUG: Dolibarr 7.0.0 and 6.0.5 - Multicurrency / Original Currency

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8248]
# Bug
The standard currency in our system is EUR and we use the multicurrency module. If we create a Quotaton in USD and we make an Order from that quotation. The original currency will be not transferred correctly.
Same if we create an invoice from a delivery note or order.
If we create a quotation in EUR the correct amount will be transferred to an order and invoice.

**Comment by ghost** [comment]
Hi, i can't reproduced your bug on last 6.0 version, can you provide us a complete user case for it ?

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
