### ISSUE TITLE
Bug in 7.0.0: Variants module shows "Loading..." forever

### ISSUE THREAD

**Issue by code-chicken** [Dolibarr/dolibarr#8255]
# Bug
Variants cannot be created because list of values (ex. colors: red, green, blue) is not being shown. Instead there is "loading..." forever.

## Environment
- **Version**: 7.0.0
- **OS**: Linux 4.9.34-gentoo #1 SMP x86_64
- **Web server**: nginx/1.12.1
- **PHP**: 7.0.21
- **Database**: MySQL or MariaDB 5.5.5-10.1.24-MariaDB
- **URL(s)**: /variants/combinations.php?id=1&action=add

## Expected and actual behavior
Expected: Adding new variants should show list of possible values
Actual: Shows "loading..." forever.

## Steps to reproduce the behavior
Edit product
Add variant
Select variant attribute

![image](https://user-images.githubusercontent.com/3024019/36783218-a6789aa6-1c7b-11e8-9238-e2c7a4ec7983.png)

**Comment by code-chicken** [comment]
Maybe the following information helps:
After some investigation I found out that in the developer tools window in Chrome I get the following error message in the Console window:
```
Failed to load http://erp-test/variants/ajax/get_attribute_values.php?id=3: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://erp-test.domain.com' is therefore not allowed access.
```
I replaced the real domain name with "domain.com". However: It seems, that only the host name is being used to load the JavaScript. Actually we use the FQDN in the address line in the browser. For the reason that in this case the domain name is our local domain, we were able to workaround the problem by only entering the hostname (without the local domain name) in the browsers address line.

Hope this helps for fixing the problem.

![image](https://user-images.githubusercontent.com/3024019/36786409-98df260c-1c86-11e8-9b73-4969030908e0.png)

**Comment by withheld** [comment]
Have you tried checking your Content Security Policy? *and $dolibarr_main_url_root in conf.php

**Comment by code-chicken** [comment]
Thank you, that was it! 👍
In the conf.php there was the following entry:
`$dolibarr_main_url_root='http://erp-test';`

However, in the browser we entered an URL like the following:
`http://erp-test.ourdomain.local`

Changing the conf.php entry to a FQDN like this
`$dolibarr_main_url_root='http://erp-test.ourdomain.local';`
solved the problem.

Anyway, we never had any problems concerning this URL-thing before.

Thank you again.

**Comment by withheld** [comment]
Your welcome.
