### ISSUE TITLE
Install script (bypass install webpage)

### ISSUE THREAD

**Issue by vipera7** [Dolibarr/dolibarr#8256]
# Instructions
Hey,

I would like to ask if it's possible to by pass the install web page but using command on CentOS 7 ?
My goal is to create a bash script which install dolibarr entirely.

## Environment
- 5.0.3: [*Affected Dolibarr version(s)*]
- CentOS 7 64bits: [*Server OS type and version*]
- httpd-2.4.6-67.el7.centos.6x86_64: [*Webserver type and version*]
- 7.1.14: [*PHP version*]
- MySQL 5.7.21: [*Database type and version*]

Thank you !

**Comment by eldy** [comment]
Yes, the install pages can be ran from command line.
Also if a conf file is set and correct manually, the install pages are not called.

**Comment by vipera7** [comment]
@eldy  Do you have an example of command line to install for example the version 2.5.0.

**Comment by hregis** [comment]
@vipera7 
2.5.0 ??

**Comment by vipera7** [comment]
@hregis Yes I need to know because I want too to upgrade to the version 7.0.0 for my clients.
(https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/2.5.0/)

**Comment by hregis** [comment]
@vipera7 
in my opinion it is better to do it with the GUI because there will be a lot of updating of the database, and it will be necessary to update from 2.5 to 3.0 before making 3.0 to 7.0

**Comment by vipera7** [comment]
@hregis 
Yes I Know but I want to create a script.
