### ISSUE TITLE
#Bug, 7.0, choosing date out of list results in wrong datatype

### ISSUE THREAD

**Issue by victorbw** [Dolibarr/dolibarr#8257]
# Bug
Choosing date out of list, results in wrong datatype (char instead of int).
Throws error: Field 'date' is required

## Environment
- **Version**: 7.0
- **OS**: Ubuntu 16.04.3 LTE
- **Web server**: Apache 2.4.18
- **PHP**:  7.0
- **Database**: MySQL 5.7.21
-**Dolibarr-Language**: Swiss German

## Expected and actual behavior
Expected: DD.MM.YYYY

Actual behaviour: DD.MONTHNAME.YYYY, like 23.march.2018

## Steps to reproduce the behavior
1. create holiday request
2. choose any date from graphical calendar pop-up 
3. try to save your document

## Suggested steps
Change 'month-names' automatically to 'MM'-format.

**Comment by choybe** [comment]
I can confirm same bug with any date chosen via the pop-up-calendar
result in  DD.MONTHNAME.YYYY instead  DD.MM.YYYY - But only with the the German translation, not with default en_US.
