### ISSUE TITLE
[BUG] REST API - Cannot update a Contact Birthday

### ISSUE THREAD

**Issue by Ysandor** [Dolibarr/dolibarr#8259]
# Bug
Using the REST API the birthday of a contact can be filled at creation but not during an update.

## Environment
- **Version**: 7.0.0
- **OS**: Don't know
- **Web server**: Don't know
- **PHP**: 7.0.13
- **Database**: MySQL
- **URL(s)**: /api/index.php/explorer/

## Expected and actual behavior
The birthday should be updated even when the contact already exists, not only at the creation

## Steps to reproduce the behavior
- Go to the REST explorer : /api/index.php/explorer/
- Create a contact through the API : 
    POST /contacts
    request body : {"lastname":"toto", "birthday":1519772400}
- See that it worked : /contact/perso.php?id=__ID_RETURNED_BY_THE_REQUEST__
- Try to update the contact through the API : 
    PUT /contacts/__ID_RETURNED_BY_THE_REQUEST__
    request body : {"birthday":1519599600}
- See that it doesn't work, the date din't change

**Comment by atm-greg** [comment]
I handle this

**Comment by Ysandor** [comment]
Hello,
Thanks a lot !
I'm not that familiar with Github yet, how can I find in which build this will be delivered (and maybe a schedule with the dates of the deliveries to come) ?

Thanks again !
