### ISSUE TITLE
HTTP ERROR 500 if look up bank entries 

### ISSUE THREAD

**Issue by kuehnleon** [Dolibarr/dolibarr#8260]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

## Bug
I've installed dolibarr 7.0.0 on my webspace and if I try to open the page http://mydomain.de/folder/compta/bank/bankentries_list.php?id=1 I'll get an HTTP Error 500

## Environment
- **Version**: [*7.0.0*]
- **OS**: [*Server OS type and version*]
- **Web server**: [*Localhost via UNIX socket Version: 5.5.59-0+deb8u1*]
- **PHP**: [*PHP 5*]
- **Database**: [*MySQL-Client-Version: 5.5.59*]
- **URL(s)**: [*http://mydomain.de/folder/compta/bank/bankentries_list.php?id=1*]

## Expected and actual behavior
[*I'll get an error*]

## Steps to reproduce the behavior
[*Open Link: http://mydomain.de/folder/compta/bank/bankentries_list.php?id=1*]

**Comment by eldy** [comment]
Do you have data into table llx_bank ?
Can you have a look at your apache error.log file ?

**Comment by kuehnleon** [comment]
Thank you for your reply, i don't know why, but i donwloaded Dolibarr again and overwrite the existing files and now it works.
