### ISSUE TITLE
Plus de facture en PJ pour envoi mail

### ISSUE THREAD

**Issue by Telofis26200** [Dolibarr/dolibarr#8263]
Bonjour,
Nous constatons depuis le passage à la version 7.0 que la facture ne s’incrémente plus en pièce jointe des mails comme cela était le cas auparavant, nous devons uploader facture par facture pour les rattacher aux mails avant d'envoyer. 
Merci à vous

**Comment by hregis** [comment]
@Telofis26200 
je n'arrive pas à reproduire ton problème !

**Comment by Telofis26200** [comment]
Voici un print ecran, 



Le 02-03-2018 13:20, Regis Houssin a écrit :

> @Telofis26200 [1]
> je n'arrive pas à reproduire ton problème ! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/telofis26200
[2]
https://github.com/Dolibarr/dolibarr/issues/8263#issuecomment-369906750
[3]

**Comment by hregis** [comment]
@Telofis26200 
vérifie si ce n'est pas un module externe qui créerait ce problème,
et/ou vérifie les droits d'accès de ton répertoire documents.

**Comment by Telofis26200** [comment]
ce qui est etrange, c'est que via un fournisseur la pj s’incrémente bien, contrairement à la manip sur un client ...

**Comment by Telofis26200** [comment]
Merci en tt les cas pour ton aide, pour le moment toujours ko :( coté clients et autre bug depuis une fiche tiers, si on ajoute une pj, celle ci et bien ajoutée au depart, mais est supprimée au moment de l'envoi, les mails arrivent sans pj (testé sur adresse  @hotmail, @gmail, @xxx.com

**Comment by eldy** [comment]
The invoice is added automatically only if you send email from the invoice card.
For the attachement done manually from thirdparty card, a fix was done so the attachement is correctly sent #8277
