### ISSUE TITLE
Bug: Menu déroulant modèle de mail commande fournisseur

### ISSUE THREAD

**Issue by LatolerieSas** [Dolibarr/dolibarr#8271]
Le menu déroulant modèle de mail dans commande fournisseur n’apparaît plus.

# Bug

## Environment
- **Version**: 7.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.27
- **Database**: MySQL or MariaDB 10.1.31-MariaDB
- **URL**: /dolibarrSas/index.php?mainmenu=home&leftmenu=home

**Comment by atm-maxime** [comment]
Sorry, can't reproduce in 7.0 :
![image](https://user-images.githubusercontent.com/2097773/37223052-95c38fb2-23cf-11e8-97f8-a43486704e05.png)

**Comment by LatolerieSas** [comment]
I have not "Sélectionner modèle d'email".
Best Regard

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


Cordialement

Ronald MATHY


La Tôlerie Sas
1879 route Dompierre 71470 ROMENAY
Téléphone: 06 82 33 30 11
Email: contact@latolerie.com
Web: www.latolerie.com


2018-03-09 19:26 GMT+01:00 Maxime Kohlhaas <notifications@github.com>:

**Comment by atm-maxime** [comment]
Can you provide a full screenshot ? With the little information you give, it's hard to imagine what happens...

**Comment by LatolerieSas** [comment]
Thank you for your help...

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


Cordialement

Ronald MATHY


La Tôlerie Sas
1879 route Dompierre 71470 ROMENAY
Téléphone: 06 82 33 30 11
Email: contact@latolerie.com
Web: www.latolerie.com


2018-03-10 10:50 GMT+01:00 Maxime Kohlhaas <notifications@github.com>:
