### ISSUE TITLE
Bug: we cant validad the invoice on the dolibarr 7.0

### ISSUE THREAD

**Issue by renemuller** [Dolibarr/dolibarr#8278]
# Bug

## Environment
- **Version**: 7.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.6.33
- **Database**: MySQL or MariaDB 5.5.55-0+deb7u1-log
- **URL**: /forscoerp/htdocs/fourn/facture/card.php?facid=561

**Comment by renemuller** [comment]
we cant validad the invoice on the dolibarr 7.0

**Comment by eldy** [comment]
Can you provide more information (error message, behavior)

**Comment by renemuller** [comment]
![bug-compta-facturation](https://user-images.githubusercontent.com/15734619/37103227-03de2cd4-222a-11e8-821b-6905dcfd8b8c.JPG)
ci-joint screen shot

**Comment by renemuller** [comment]
comme vous pouvez voir , je nai pas les menus dessous pour valider la facture

**Comment by vvnt** [comment]
Did you check your user rights ?

**Comment by renemuller** [comment]
Yes I'm admin and we haven't any menu , for validate, delete , clone ...

**Comment by hregis** [comment]
@renemuller 
try to disable/enable the supplier module (or customer invoice module) and check user rights again

**Comment by renemuller** [comment]
I did what you told me and nothing changed, I checked the rights they are all green

**Comment by hregis** [comment]
@renemuller 
you should check if you do not have an external module that will use the hook "addMoreActionsButtons"

**Comment by renemuller** [comment]
I do not use plugins and this is the only problem I just have with billing
![bug-compta-facturation](https://user-images.githubusercontent.com/15734619/37141193-8c87103e-22b4-11e8-93cc-96ca0f562b60.JPG)

**Comment by hregis** [comment]
@renemuller 
this is customer invoice ? not supplier invoice ?

**Comment by renemuller** [comment]
the  problem is the same customer or supplier

**Comment by hregis** [comment]
@renemuller 
can you contact me by mail ?
regis dot houssin at gmail dot com

**Comment by renemuller** [comment]
i made it

**Comment by tetus** [comment]
I have a similar problem with a fichinter (intervention card) when using an external customer. no action buttons to validate o other action.
