### ISSUE TITLE
Bug: API REST elementid and custom field not appeared V7

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#8285]
# Bug
lack of this field in API response: elementid (of elementtype link) and the custom fields

## Environment
- **Version**: 7.0.0
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Unix)
- **PHP**: fpm-fcgi 7.0.24
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB
- **URL**: /comm/action/index.php?idmenu=584154&mainmenu=agenda&leftmenu=

**Comment by eldy** [comment]
Which API (url) ?

**Comment by ptibogxiv** [comment]
the bug is in GET list or get action:
/api/index.php/agendaevents/
or 
/api/index.php/agendaevents/{id}

**Comment by ptibogxiv** [comment]
@eldy merci beaucoup pour le fix mais il manque encore le "elementid" associé à "elementtype": "agefodd_agsession" par exemple dans la réponse de l'API :'(
