### ISSUE TITLE
BUG Theoretic stock calculation when decreasing stock on invoice validation

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8289]
# Bug
When using stock decrease on invoice validation, the theoretic calculated stock value is false. It takes product quantities on orders even if the orders are invoiced (and stock movement is done).

## Environment
- **Version**: 5-0 to 7.0, but may be ALL 
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 5
- **Database**: mysql
- **URL(s)**: product/stock/product.php?id= and all warnings on stock availability, order is shippable ....

## Expected and actual behavior
As theoretic calculated stock is false, you will get lot of false warnings for unshippable orders on a lot of screens. 

## Steps to reproduce the behavior
set stock management on decrease on invoice validation
set stock on a product ( example 10) 
create and validate customer order : physical stock = 10; theoritic stock = 9 that is right no stock movement done, and product on a validated order, you can also set order to billed
invoice your order and validate invoice you get physical stock 9 (that is right because of stock movement) and theoretic stock = 8 (false should be 9)

**Comment by eldy** [comment]
Are you sure the order has the status "Closed" ?

**Comment by tiaris** [comment]
No order is still in process, not closed. In a lot of cases, invoice is made before order is processed
