### ISSUE TITLE
Unable to validate supplier credit note 

### ISSUE THREAD

**Issue by husainthangal** [Dolibarr/dolibarr#8293]
# Bug
[*We have turned on customisable mask Tulip for supplier invoice module and can't validate supplier credit note, error "Duplicate entry '3' for key 'uk_facture_fourn_ref'" once we click validate button. *]

## Environment
- **Version**: [*Dolibarr version 7.0.0*]
- **OS**: [*Ubuntu Linux 64 Bit*]
- **Web server**: [*Apache/2.4.25 (Ubuntu)*]
- **PHP**: [*7.0.22-0ubuntu0.17.04.1*]
- **Database**: [*MySQL or MariaDB 5.7.20-0ubuntu0.17.04.1*]
- **URL(s)**: [*http://192.168.0.65/DLITS/fourn/facture/card.php?id=168&action=confirm_valid&confirm=yes&idwarehouse=6*]

## Expected and actual behavior
[*Supposed to create a valid credit note upon validation*]

## Steps to reproduce the behavior
[*1- Customise supplier module and turn on tulip customisable mask feature 2- Create Credit note from existing supplier invoice 3- validate credit note*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

![screen shot 2018-03-07 at 2 14 18 pm](https://user-images.githubusercontent.com/36885413/37090751-97021fde-2216-11e8-959b-fabb90bde0af.png)
![screen shot 2018-03-07 at 2 49 10 pm](https://user-images.githubusercontent.com/36885413/37090785-c2625748-2216-11e8-8936-7afe19f1cf7d.png)

**Comment by atm-maxime** [comment]
Hello,

Thanks for the update. In 7.0 version, credit note for suppliers is experimental and not available if you are in MAIN_FEATURE_LEVEL 0.
However, this has been finished, tested and integrated in the next 8.0 version to come.
