### ISSUE TITLE
Bug: Always display first entity data dict llx_c_paiement

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#8298]
# Bug

## Environment
- **Version**: 7.0.0
- **OS**: Linux
- **Web server**: Apache/2.4.29 (Unix)
- **PHP**: fpm-fcgi 7.0.24
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB
- **URL**: /admin/dict.php?id=13

## Report
correct data save for the entity but only display the first entity data

**Comment by hregis** [comment]
@ptibogxiv 
this multicompany feature is not stable and totally refactored in develop branch, don't use this feature and remove all records in llx_c_paiement and llx_c_payment_term if entity field > 1
this feature disabled in multicompany 7.0.1

**Comment by ptibogxiv** [comment]
thank for your response
