### ISSUE TITLE
Bug : Latin character support

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#8301]
## Environment
Version 6 et 7

## Description
If we use Latin characters in the names, addresses and products, the pdf are not correct. Characters are replaced by symbols

Example that does not work: Quōvīs

**Comment by frederic34** [comment]
using another font for the pdf solves the problem

**Comment by eldy** [comment]
@philazerty Which language do you use ?

**Comment by frederic34** [comment]
@eldy 
https://www.dolibarr.fr/forum/12-howto--aide/61301-caracteres-speciaux-en-pdf

**Comment by philazerty** [comment]
You just have to use an adapted font
