### ISSUE TITLE
Feature Request : show description, tva rate and price of product when selected in invoice (Variation module update)

### ISSUE THREAD

**Issue by Vaadasch** [Dolibarr/dolibarr#8357]
# Feature Request
Show up the description, tva_tx and price_ht of selected product in invoices.
By default, when we select an already existing product, description is empty and the tva rate and price is hiddent. 

## Use case
It would be nice to have access to theses fields directly when selecting the product, no need to add THEN edit the product.

### Modification of : htdocs/core/tpl/objectline_create.tpl.php in function setforpredef()
line 787 :
```
< 	jQuery("#price_ht").val('').hide();
> 	jQuery("#price_ht").val('').show();
```

line 791 : 
```
< 	jQuery("#tva_tx").hide();
> 	jQuery("#tva_tx").show();
```

### Modification of htdocs\compta\facture\card.php  (GOOD)
Modèles : fiche-rec.php : line ~472 : 
Facture : card.php : line 1535 :
```
<	 if (GETPOST('prod_entry_mode') == 'free')
< 	{
< 		$idprod=0;
< 		$tva_tx = (GETPOST('tva_tx') ? GETPOST('tva_tx') : 0);
<	 }
< 	else
< 	{
< 		$idprod=GETPOST('idprod', 'int');
< 		$tva_tx = '';
< 	}
```
```
> 	$tva_tx = (GETPOST('tva_tx') ? GETPOST('tva_tx') : 0);
> 	GETPOST('prod_entry_mode') == 'free' ? $idprod=0 : $idprod=GETPOST('idprod', 'int');
```

Modèles : fiche-rec.php : line 549 : 
Factures : card.php : line 1632 :
```
< 	$tva_tx = get_default_tva($mysoc, $object->thirdparty, $prod->id);
> 	$tva_tx = ($tva_tx ? $tva_tx : get_default_tva($mysoc, $object->thirdparty, $prod->id));
```

Modèles : fiche-rec.php : line 643: 
Factures : card.php : line 1754:
```
< 	$desc = dol_concatdesc($desc, $product_desc);
> 	$desc = $product_desc;
```
### Modification of htdocs/core/lib/ajax.lib.php in function ajax_autocompleter :

line 133 :
```
<	return { label: label, value: item.value, id: item.key, update: update, textarea: textarea, disabled: item.disabled }
> 	return { label: label, value: item.value, id: item.key, update: update, textarea: textarea, disabled: item.disabled, tvaTx: item.tva_tx, price_ht: item.price_ht, desc: item.desc }
```

line 192 :
```
(191) : }
> 	$("#tva_tx").val(parseFloat(ui.item.tvaTx.text().replace(',', '.')));
> 	$("#price_ht").val(parseFloat(ui.item.price_ht.text().replace(',', '.')));
> 	$("#dp_desc").val(ui.item.desc);
(ex-192) : console.log("ajax_autocompleter...")
```

## Suggested steps
Check compatibility with multi-prices products.

**Comment by Vaadasch** [comment]
I am right about ajax.lib.php and objectline_create.tpl.php but i'm missing something about fiche-rec.php

**Comment by Vaadasch** [comment]
It seems there is multiple references.
The modifications in facture-rec.php are in fact in card.php :
line 472 -> 1535
line 549 -> 1632
line 643 -> 1754

**Comment by flaajimi** [comment]
Hi,
Thank you for tuto 👍 

But when I select a product predefined description, tva rate and price of product the field does not fill

Thank you

**Comment by flaajimi** [comment]
![image](https://user-images.githubusercontent.com/22789071/37592168-2f551f2e-2b6e-11e8-8f4a-336652f97652.png)

**Comment by Vaadasch** [comment]
Hi,

On which version are you ?

Can you copy / paste the modified lines of the ajax file ?

**Comment by flaajimi** [comment]
Hi,
Dolibarr V7

Modification of htdocs/core/lib/ajax.lib.php

![image](https://user-images.githubusercontent.com/22789071/37595059-9e174be0-2b77-11e8-8a57-36f4e59fd225.png)

![image](https://user-images.githubusercontent.com/22789071/37595182-215c3d6c-2b78-11e8-93a7-098a8a04fc34.png)

 Thank you

**Comment by Vaadasch** [comment]
In the first modification, line 133 :  you forgot the following :
```return { ... , disabled: item.disabled, **tvaTx:** item.tva_tx, price_ht: ... } ```

Be sure that the description (and modifications of TVA and price) are correctly taken by confirming a product then edit it. The process of it is through the card.php (ex  facture-rec.php)

**Comment by flaajimi** [comment]
Thank you 🥇 👍

**Comment by Vaadasch** [comment]
There is an error, because of the use of the parseInt function, non-integer values doesn't work.
Just need to use the parseFloat function instead in ajax.lib.php.
I've edited the first post.

**Comment by Vaadasch** [comment]
# Modification of variants (see conclusion)
Hi, just to have the same functionnality when using the variant module :
 **htdocs/core/tpl/objectline_create.tpl.php** : We create an input to store the reference price
line ~ 297
```
=   <input type="text" size="5" name="price_ht" id="price_ht" class="flat right" value="<?php echo (isset($_POST["price_ht"])?GETPOST("price_ht",'alpha',2):''); ?>">
>   # Input to store the price as reference (for percent variants)
>   <input type="text" name="ref_price_ht" id="ref_price_ht" style="display: none;" value="" >
```

We store the reference price :
**htdocs/core/lib/ajax.php** line ~194 :
```
>  $("#ref_price_ht").val(parseFloat(ui.item.price_ht));
```


**htdocs\variants\class\ProductAttributeValue.class.php** : We get the price variations
line 110 :
```
<  $sql .= 'v.fk_product_attribute, v.rowid, v.ref, v.value FROM '.MAIN_DB_PREFIX.'product_attribute_value v ';
> $sql .= 'v.fk_product_attribute, v.rowid, v.ref, v.value';
> if ($only_used) { $sql .= ', c.variation_price vp, c.variation_price_percentage vpp'; }
> $sql .= ' FROM '.MAIN_DB_PREFIX.'product_attribute_value v ';
```

line ~135 :
```
130 : while ($result = $this->db->fetch_object($query)) {
		...
		$tmp->value = $result->value;
>		if ($only_used) {
>			$tmp->vp = $result->vp;
>			$tmp->vpp = $result->vpp;
>		}
		$return[] = *tmp;
```

**htdocs/core/class/html.form.class.php** line ~1815 : We add a change function on the selection of the variant :
old : 
```var html = jQuery(document.createElement('select')).attr('name', 'combinations[' + val.id + ']').css({
	'margin-left': '15px',
	'white-space': 'pre'
}).append(
	jQuery(document.createElement('option')).val('')
);
```
new : 
```
var html = jQuery(document.createElement('select')).attr('name', 'combinations[' + val.id + ']').css({
	'margin-left': '15px',
	'white-space': 'pre'
}).change( function () {
	// If we select the first option (blank), we set the varprice to 0
	if (this.selectedIndex === 0) {
		var varprice = 0;
	}
	else { 
	// Else we calcul the price variation
		var vp = parseFloat($('option:selected', this).attr('vp'));
		var vpp = parseInt($('option:selected', this).attr('vpp'));
		var varprice = ( vpp * vp * parseFloat($("#ref_price_ht").val()) / 100) + (!vpp * vp);
	}
	// Setting the variation price
		$("#price_ht").val( parseFloat($("#price_ht").val()) + varprice - parseFloat($('option:first', this).val()) );
		// Stocking the variation price in the first option to future selections
		$('option:first', this).val(varprice);
}).append(
	jQuery(document.createElement('option')).val(0)
);
```
# Conclusion
Too bad : all of this would be working if the variant module wasn't creating new product on each variant, which doesn't work btw because it can't create MULTIPLE variations of a product, but is probably necessary to the stock module

**Comment by Vaadasch** [comment]
Updated posts

**Comment by Vaadasch** [comment]
parseFloat doen't take commas :
> 	$("#tva_tx").val(parseFloat(ui.item.tvaTx.text().replace(',', '.')));
> 	$("#price_ht").val(parseFloat(ui.item.price_ht.text().replace(',', '.')));

**Comment by Vaadasch** [comment]
parseFloat doen't take commas :
> 	$("#tva_tx").val(parseFloat(ui.item.tvaTx.text().replace(',', '.')));
> 	$("#price_ht").val(parseFloat(ui.item.price_ht.text().replace(',', '.')));

**Comment by Vaadasch** [comment]
Parsefloat can't take commas
(191) : }
> 	$("#tva_tx").val(parseFloat(ui.item.tvaTx.replace(\\',\\', \\'.\\')));
> 	$("#price_ht").val(parseFloat(ui.item.price_ht.replace(\\',\\', \\'.\\')));

ParseFloat isn't needed (anymore ?)
(191) : }
> 	$("#tva_tx").val(ui.item.tvaTx);
> 	$("#price_ht").val(ui.item.price_ht);
