### ISSUE TITLE
Project Category link path don't link back to project

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8359]
# Bug
Project Category link path don't link back to project
## Environment
- **Version**: *Dolibarr 7.0.0*
- **OS**: *Linux*
- **Web server**: *Apache*
- **PHP**: *5.6.33*
- **Database**: *MySQL*
- **URL(s)**: *categories/index.php?leftmenu=cat&type=1*] and [*categories/viewcat.php?id=1&type=project*
## Expected and actual behavior
When setting a project category to a project and then going to the category list, the tagged project is listedbut the link "/categories/viewcat.php?id=1&type=project" *] does not call the link path

forum https://www.dolibarr.de/forum/bugs-fuer-development-oder-demo-versions/52448-wiie-eine-bug-berichten-projektkategorien

**Comment by atm-arnaud** [comment]
Hello,

I'm currently working on this issue.

Regards,
