### ISSUE TITLE
Mail models Supplier order

### ISSUE THREAD

**Issue by PlatiScript** [Dolibarr/dolibarr#8360]
# Bug
There is no model when we send email from order supplier card. There is no select and no presend informations like subject or mail content or attachment.

## Environment
- **Version**:  7.0

## Suggested steps

I think there is a problem between "supplier_order_send" and "order_supplier_send" in the file html.formmail.class.php because when i swap this words, the select appair.

**Comment by atm-maxime** [comment]
Works for me in 7.0.2. Ok for you ?
