### ISSUE TITLE
No record found when clicking on a third.

### ISSUE THREAD

**Issue by saxa** [Dolibarr/dolibarr#8363]
Hi I just upgraded to 7.0.0 from the 6.0.5. Using dolibarr on Slackware64 14.2 with MariaDB-10.0.29 and php-5.6.30. All was working up to 6.0.4, upgrading it with git, but tried also the released tarball from sf.net and restarted the install scripts few times already.

When I open a proposal I do see the proposal but the third is not listed on it at all.
If I click on a Thirds icon I get the list of all thirds and if I click on any of them I get the Record not found white page.

Any ideas ?
I am attaching few screenshots.
![screenshot from 2018-03-12 10-39-29](https://user-images.githubusercontent.com/1041629/37297230-728ba7b4-261d-11e8-8043-09978e3dbc7d.png)
![screenshot from 2018-03-12 10-39-39](https://user-images.githubusercontent.com/1041629/37297216-6b630054-261d-11e8-99bd-5c58df19f637.png)
![screenshot from 2018-03-12 10-40-03](https://user-images.githubusercontent.com/1041629/37297196-63585030-261d-11e8-84fc-3784eed8d6e5.png)

**Comment by saxa** [comment]
Hi , any idea or suggestion on where to start looking for a solution ?

**Comment by saxa** [comment]
How can I check if the thirds are still in the DB ? Restarting the install process does not solve this.

**Comment by hregis** [comment]
@saxa 
in your example, check if "rowid" field with value "376" is present in llx_societe table.
if yes, have you externals modules ?

**Comment by saxa** [comment]
Hi Regis, yes it is present, and all others are there.

MariaDB [banco_dolibarr]> select rowid,nom,entity from llx_societe where rowid=376;
+-------+------------------------------------+--------+
| rowid | nom                                | entity |
+-------+------------------------------------+--------+
|   376 | A. A. RODRIGUES SOARES TRATORES ME |      1 |
+-------+------------------------------------+--------+
1 row in set (0.00 sec)

MariaDB [banco_dolibarr]>

**Comment by saxa** [comment]
I do not use any modules from outside of dolibarr source tree. Just standard modules.

**Comment by hregis** [comment]
@saxa 
contact me by mail for remote maintenance
regis dot houssin at gmail dot com

**Comment by saxa** [comment]
Ok, thanks Regis for directing me to solve out this. The solution was to upgrade the full database to 8.x develop series. But now my question is how do I go back to 7.x series and use the stable releases instead of having the 8.x database ? I will close this issue.
