### ISSUE TITLE
Payment displayed multiple time

### ISSUE THREAD

**Issue by Nocvan** [Dolibarr/dolibarr#8372]
# Bug
When adding a payment to an invoice, the record is displayed multiple time on the invoice card and on the pdf too (which is more problematic).
I check the DB with phpMyAdmin, only one payment is stored (cf screenshot).
Note that we use the multi company module, and there is 6 record as there is 6 company which use this dolibarr.

## Environment
- **Version**: 7.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.1.15
- **Database**: 5.0.12
- **URL(s)**: http://axxxxx.fr/compta/facture/card.php?facid=xxx

Thank's !

Thib

## Screenshots
![capture d ecran 2018-03-13 a 12 08 30](https://user-images.githubusercontent.com/8873259/37338564-1c72e2fc-26b8-11e8-8be5-f067122730d5.png)
![capture d ecran 2018-03-13 a 12 09 24](https://user-images.githubusercontent.com/8873259/37338565-1c8f5860-26b8-11e8-8c59-38a4fc225da6.png)
![capture d ecran 2018-03-13 a 12 08 49](https://user-images.githubusercontent.com/8873259/37338566-1ca9f300-26b8-11e8-99e0-1dce1120bc5d.png)

**Comment by hregis** [comment]
@Nocvan download again the last release of multicompany (7.0.1) and disable/enable module in dolibarr

**Comment by atm-arnaud** [comment]
Hello,

This bug is not find on a 7.0 standard version. Could you answer to @hregis  ?

Regards,

**Comment by hregis** [comment]
@Nocvan @atm-arnaud 
the last release of multicompany (7.0.1) fixed this issue

**Comment by atm-arnaud** [comment]
@hregis  thanks for the feedback. We will close this issue.

@atm-maxime Issue to close

**Comment by atm-arnaud** [comment]
This issue is already corrected since 2 years.
@eldy  issue to close ;)
