### ISSUE TITLE
Wrong path displayed when asking to set the config file to read-only

### ISSUE THREAD

**Issue by fhorlaville** [Dolibarr/dolibarr#8378]
# Bug
The path included in the "please make your config file read-only" alert is wrong - it still states htdocs/conf/conf.php where the real path is /home/username/dolibarr/conf/conf.php. This is probably a remnant of the previous versions (where there was an htdocs folder) which hasn't been updated.

## Environment
- **Version**: 7.0.0
- **OS**: Linux 3.10.0-714.10.2.lve1.5.9.el7.x86_64
- **Web server**: Apache 
- **PHP**: 7.1.14
- **Database**: Mysql 5.6.39-cll-lve

## Expected and actual behaviour

Here is the error message in French:

"Attention, votre fichier de configuration (htdocs/conf/conf.php) est accessible en écriture au serveur Web. Ceci représente une faille sérieuse de sécurité. Modifiez les permissions pour qu'il soit en lecture seule pour le compte sous lequel tourne le serveur Web et non lisible pour les autres."

## Steps to reproduce the behaviour
Just make the conf file writable and the message will appear (expected) - the only issue is the path, which is not correct. The path for the "please create an install.lock" file alert (similar) is correct, however.

Thanks!

F.

**Comment by fhorlaville** [comment]
It's actually hardcoded in the WarningConfFileMustBeReadOnly message in all languages, e.g. for French in dolibarr/htdocs/langs/fr_FR/errors.lang:

Compare this (hardcoded):
`WarningConfFileMustBeReadOnly=Attention, votre fichier de configuration (<b>htdocs/conf/conf.php</b>) est accessible en écriture au serveur Web. Ceci représente une faille sérieuse de sécurité. Modifiez les permissions pour qu'il soit en lecture seule pour le compte sous lequel tourne le serveur Web et non lisible pour les autres.<br>Si vous êtes sous Windows sur un disque dur utilisant un formatage FAT, sachez que ce système de fichier ne permet pas de protéger des fichiers et n'offre donc aucune solution pour réduire les risques de manipulation de ce fichier.`
to this (path as a parameter):
`WarningLockFileDoesNotExists=Attention, une fois l'installation terminée, les outils d'installation/migration doivent être désactivés en ajoutant un fichier <b>install.lock</b> dans le répertoire <b>%s</b>. L'absence de ce fichier représente une faille de sécurité.`

**Comment by fhorlaville** [comment]
They are indeed called differently in the index.php:

```
    // Check if install lock file is present
    $lockfile=DOL_DATA_ROOT.'/install.lock';
    if (! empty($lockfile) && ! file_exists($lockfile) && is_dir(DOL_DOCUMENT_ROOT."/install"))
    {
        $langs->load("errors");
        //if (! empty($message)) $message.='<br>';
        $message.=info_admin($langs->trans("WarningLockFileDoesNotExists",DOL_DATA_ROOT).' '.$langs->trans("WarningUntilDirRemoved", DOL_DOCUMENT_ROOT."/install"), 0, 0, '1', 'clearboth');
    }
```
vs
```
    // Conf files must be in read only mode
    if (is_writable($conffile))
    {
        $langs->load("errors");
        //$langs->load("other");
        //if (! empty($message)) $message.='<br>';
        $message.=info_admin($langs->transnoentities("WarningConfFileMustBeReadOnly").' '.$langs->trans("WarningUntilDirRemoved", DOL_DOCUMENT_ROOT."/install"), 0, 0, '1', 'clearboth');
    }
```

and the two warnings are defined differently, e.g. in dolibarr/htdocs/langs/fr_FR/errors.lang:
static path:
```
WarningConfFileMustBeReadOnly=Attention, votre fichier de configuration (<b>htdocs/conf/conf.php</b>) est accessible en écriture au serveur Web. Ceci représente une faille sérieuse de sécurité. Modifiez les permissions pour qu'il soit en lecture seule pour le compte sous lequel tourne le serveur Web et non lisible pour les autres.<br>Si vous êtes sous Windows sur un disque dur utilisant un formatage FAT, sachez que ce système de fichier ne permet pas de protéger des fichiers et n'offre donc aucune solution pour réduire les risques de manipulation de ce fichier.
```
vs parameter path:
```
WarningLockFileDoesNotExists=Attention, une fois l'installation terminée, les outils d'installation/migration doivent être désactivés en ajoutant un fichier <b>install.lock</b> dans le répertoire <b>%s</b>. L'absence de ce fichier représente une faille de sécurité.
```

**Comment by dolibarr95** [comment]
Hi
Is is the same issue ?  :
https://github.com/Dolibarr/dolibarr/issues/7632
