### ISSUE TITLE
Sql error in Accounting

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8387]
# Bug
Getting sql error in accounting
Letzter Fehlerhafter Datenbankzugriff: SELECT aa.rowid, aa.fk_pcg_version, aa.pcg_type, aa.pcg_subtype, aa.account_number, aa.account_parent , aa.label, aa.active, a2.rowid as rowid2, a2.label as label2, a2.account_number as account_number2 FROM llx_accounting_account as aa LEFT JOIN llx_accounting_system as asy ON aa.fk_pcg_version = asy.pcg_version LEFT JOIN llx_accounting_account as a2 ON a2.rowid = CAST(aa.account_parent AS UNSIGNED) WHERE asy.rowid = 5 ORDER BY aa.account_number ASC LIMIT 26
Rückgabewert des letzten fehlerhaften Datenbankzugriff: DB_ERROR_1267
Information zum letzten fehlerhaften Datenbankzugriff: Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='

## Environment
- **Version**: 7.0
- **OS**: 
- **Web server**: 
- **PHP**: 
- **Database**: 
- **URL(s)**: [*Affected URL(s)*]

## Steps to reproduce the behavior
german forum https://www.dolibarr.de/forum/bugs-mit-einer-dolibarr-stabilen-version/52438-bug-oder-mein-fehler

**Comment by atm-arnaud** [comment]
Hello,

I'm not german but i think that your probleme comes from : (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) 

Your SGBD (data sql) server try to compare two different type of table. Could you set all your tables in interclassment mode : utf8_unicode_ci

I got no errors in 7.0 standard Dolibarr Version.

Regards,

**Comment by Chris-Golle** [comment]
This error shows up on 6.0.3 hosted on dolicloud.

"Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '=' "

**Comment by atm-maxime** [comment]
I think this has been fixed since then. Can you confirm ?
