### ISSUE TITLE
Bug generating odt documents

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8388]
# Bug
[*Short description*]

Message: Error generating document for CommonObject. Error: Nothing to parse - Check that the styles.xml file is correctly formed in source file '******/documents/doctemplates/proposals/32test.odt'

## Environment
- **Version**: 7.0
- **OS**:SunOS localhost 5.10 Generic_150401-49 i86pc
- **Web server**:Apache/2.4.29 (Unix)
- **PHP**: 5.6.33
- **Database**: mysqli
- **URL(s)** : /comm/propal/card.php?id=23

## Expected and actual behavior
Full message 
Das System hat einen technischen Fehler festgestellt.
Diese Informationen können bei der Fehlersuche hilfreich sein (Hinweise können entfernt werden indem $dolibarr_main_prod auf '1' gesetzt wird):
Datum: 20180226160603
Dolibarr: 7.0.0
Funktionslevel: 0
PHP: 5.6.33
Server: Apache/2.4.29 (Unix)
OS: SunOS localhost 5.10 Generic_150401-49 i86pc
UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

Angefragte URL: /comm/propal/card.php?id=23
Referer: http://******/comm/propal/card.php?id=23
Menüverwaltung: eldy_menu.php

Datenbank Type Manager: mysqli
Letzter Fehlerhafter Datenbankzugriff: Keine Anfrage im Fehler
Rückgabewert des letzten fehlerhaften Datenbankzugriff: Keine Anfrage im Fehler
Information zum letzten fehlerhaften Datenbankzugriff: Keine Anfrage im Fehler

Message: Error generating document for CommonObject. Error: Nothing to parse - Check that the styles.xml file is correctly formed in source file '******/documents/doctemplates/proposals/32test.odt'

## Steps to reproduce the behavior
Forum dolibarr.de https://www.dolibarr.de/forum/howto-hilfe/52432-odt-templates-funktionieren-nicht

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-arnaud** [comment]
Hello,

This message informed you that an error was find in your odt doc. Could you try with an other one ?
Without style and keys.

If there is no errors. I recomand you creating an other file to try again

Regards,

**Comment by atm-maxime** [comment]
As said by @atm-arnaud this error comes from your ODT file which must have a broken variable in its structure
