### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8389]
# Bug
translation key in de_DE/admin.lang  has a false html code which makes that the whole page is a link on the wiki page https://wiki.dolibarr.org/index.php/Setup_Other#List_of_known_hidden_options

## Environment
- **Version**: 7.0
- **URL(s)**: admin/const.php?mainmenu=home

## Expected and actual behavior
just change language key ConstDesc in langs/de_DE/admin.lang

`ConstDesc= (..) target="_blank"> hier überprüfen </ </a>. `

 to  (removing false `</`

`target="_blank"> hier überprüfen </a>.`

## Steps to reproduce the behavior
set to de_DE, and click on a part of page

**Comment by atm-arnaud** [comment]
Hello,

I'm currently working on this issue.

Regards,
