### ISSUE TITLE
add Finance journals type

### ISSUE THREAD

**Issue by RANDOMLY-OBFUSCATED** [Dolibarr/dolibarr#8394]
Dolibarr 6.0.3

# Bug
Modules / Accounting (advanced) - PCG99-BASE

Can't add a type of journal.
cf: column "Nature" in Financial / Accountancy / Setup / Finance journals

It could be possible to add a line in llx_accounting_journal, it will break:
- the if test in /htdocs/accountancy/class/accountingjournal.class.php:256 (function LibType)
- the arrays in /htdocs/accountancy/admin/journals_list.php:132
- every translations
- more ?
because in this table "nature" is just a numeral value defined in these two previous files.

# Feature Request
add dictionary in setup (?)

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by eldy** [comment]
With v7, you should be able to add journal code from setup page

**Comment by RANDOMLY-OBFUSCATED** [comment]
Hello, Thanks for reply.
I need some time to update. I'm going to do it, test and give you feed back.
Best regards.

**Comment by RANDOMLY-OBFUSCATED** [comment]
Update OK ; tests ASAP.

**Comment by RANDOMLY-OBFUSCATED** [comment]
Hello,
Maybe I was not clear. It is not about adding a journal but a **type** of journal.
I don't find any thing in "configuration" (no button for advanced comptability)
nor in "journals_list.php".
