### ISSUE TITLE
Bug: No possibility to hide description for invoices

### ISSUE THREAD

**Issue by lampi87** [Dolibarr/dolibarr#8402]
# Bug
It's not possible to hide description on customer invoices

## Environment
- **Version**: 7.0.0
- **OS**: Ubuntu
- **Web server**: Apache
- **PHP**: 7.0.25

**Comment by simnandez** [comment]
Works fine, have you enabled the option to hide the description in the pdf setup?

**Comment by lampi87** [comment]
Works for me too, thanks for the hint with pdf setup option
