### ISSUE TITLE
Upgrade 6.0.2 ⇒ 7.0.0

### ISSUE THREAD

**Issue by microniko** [Dolibarr/dolibarr#8406]
I'm trying to upgrade Doliobarr to 7.0.0 but having this error :

> Request 17 sql='ALTER TABLE llx_product_attribute_value DROP INDEX unique_ref;'
> --
> Erreur  DB_ERROR_ERREUR:  2BP01: n'a pas pu supprimer index unique_ref car il  est requis par contrainte unique_ref sur table llx_product_attribute HINT:  Vous pouvez supprimer contrainte unique_ref sur table  llx_product_attribute à la place. LOCATION:  findDependentObjects, dependency.c:649: ALTER TABLE  llx_product_attribute_value DROP INDEX unique_ref;ERREUR:  2BP01:  n'a pas pu supprimer index unique_ref car il est requis par contrainte  unique_ref sur table llx_product_attribute HINT:  Vous pouvez supprimer contrainte unique_ref sur table  llx_product_attribute à la place. LOCATION:  findDependentObjects, dependency.c:649
> Request 18 sql='ALTER TABLE  llx_product_attribute_value ADD UNIQUE INDEX uk_product_attribute_value  (fk_product_attribute, ref);'

I'm using PostgreSQL 9.6.7…

Dolibarr seems work fine but I don't test all functionalities…

Thx :)

**Comment by pitchum** [comment]
I encountered quite a similar error and I fixed this by dropping the constraint by hand just before applying migration script (6.0.0 -> 7.0.0)

    ALTER TABLE llx_product_attribute DROP CONSTRAINT unique_ref;


For the record here is the error I got before applying the workaround.

```
Request 20 sql='insert into llx_c_action_trigger (code,label,description,elementtype,rang) values ('MEMBER_SUBSCRIPTION_DELETE','Member subscribtion deleted','Executed when a member subscribtion is deleted','member',24);'
Request 21 sql='ALTER TABLE llx_product_attribute_value DROP INDEX unique_ref;'
Erreur DB_ERROR_ERREUR: 2BP01: n'a pas pu supprimer index unique_ref car il est requis par contrainte unique_ref sur table llx_product_attribute HINT: Vous pouvez supprimer contrainte unique_ref sur table llx_product_attribute à la place. LOCATION: findDependentObjects, dependency.c:649: ALTER TABLE llx_product_attribute_value DROP INDEX unique_ref;
ERREUR: 2BP01: n'a pas pu supprimer index unique_ref car il est requis par contrainte unique_ref sur table llx_product_attribute HINT: Vous pouvez supprimer contrainte unique_ref sur table llx_product_attribute à la place. LOCATION: findDependentObjects, dependency.c:649
Request 22 sql='ALTER TABLE llx_product_attribute_value ADD UNIQUE INDEX uk_product_attribute_value (fk_product_attribute, ref);'
```

**Comment by marcosgdf** [comment]
Same error happening here

```
Request 21 sql='ALTER TABLE llx_product_attribute_value DROP INDEX unique_ref;'
--
Error DB_ERROR_ERROR: 2BP01: cannot drop index unique_ref because constraint unique_ref on table llx_product_attribute_value requires it
HINT: You can drop constraint unique_ref on table llx_product_attribute_value instead.
LOCATION: findDependentObjects, dependency.c:649: ALTER TABLE llx_product_attribute_value DROP INDEX unique_ref;
ERROR: 2BP01: cannot drop index unique_ref because constraint unique_ref on table llx_product_attribute_value requires it
HINT: You can drop constraint unique_ref on table llx_product_attribute_value instead.
LOCATION: findDependentObjects, dependency.c:649
```
