### ISSUE TITLE
Public & Private  note are not saved in invoice

### ISSUE THREAD

**Issue by xmillies** [Dolibarr/dolibarr#8408]
# Bug
[*Public & Private  note are not saved in invoice*]

## Environment
- **Version**: [*7.0.0*]
- **OS**: [*Linux Centos 7*]
- **Web server**: [*nginx*]
- **PHP**: [*7.x*]
- **Database**: [*Mysql 5.x]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Public & Private  note are not saved in invoice*]
The action is editnote_public and but in ./core/adctions_setnote.php the test for $action is done againt 'setnote_public'

so replace the line :

if ($action == 'setnote_public' && ! empty($permissionnote) && ! GETPOST('cancel','alpha'))

by this

if ($action == 'editnote_public' && ! empty($permissionnote) && ! GETPOST('cancel','alpha'))

solves the issue.

## Steps to reproduce the behavior
[*On a invoice edit public or private note on a invoice.*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

# Feature Request
[*Short description*]
Do correction on php files.

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by simnandez** [comment]
Works fine in 7.0.1, Please update your dolibarr
