### ISSUE TITLE
ODT: {object_payment_term}

### ISSUE THREAD

**Issue by michel-thomas** [Dolibarr/dolibarr#8414]
# Bug
``{object_payment_term}`` in ODT file is replaced by its reference and not by its content.

For example, I created in dictionnary a new entry:
- Code = "30_60_10"
- Label = "30/60/10"
- Content = "30% à la commande, 60% à la livraison et 10% après validation"

When using ``{object_payment_term}`` in ODT file, I get "30/60/10" instead of the content

## Environment
- **Version**: 6.0.4
- **OS**: Debian 9
- **Web server**: Apache 2.4
- **PHP**: 7.0
- **Database**: MariaDB

**Comment by ATM-Marc** [comment]
I'm working on it

**Comment by ATM-Marc** [comment]
PR #8544
