### ISSUE TITLE
Bug: Module ticket sup

### ISSUE THREAD

**Issue by webmasterproxy-media** [Dolibarr/dolibarr#8415]
# Bug

## Environment
- **Version**: 8.0.0-alpha
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.28
- **Database**: MySQL or MariaDB 5.5.5-10.1.31-MariaDB
- **URL**: /dolibarr88/htdocs/ticketsup/list.php?idmenu=177&mainmenu=ticketsup&leftmenu=

## Report

![create ticketlist_-_2018-03-19_11 37 50](https://user-images.githubusercontent.com/30132548/37591107-b1dd5af0-2b6a-11e8-80ed-f4f1599f346f.png)
![createticket_-_2018-03-19_11 37 25](https://user-images.githubusercontent.com/30132548/37591144-cc64a482-2b6a-11e8-8f1a-65f4013e11c9.png)

**Comment by atm-maxime** [comment]
Thanks, this was the early stages of ticket module integration
