### ISSUE TITLE
Bug: Module ticket sup

### ISSUE THREAD

**Issue by webmasterproxy-media** [Dolibarr/dolibarr#8416]
![createticket_-_2018-03-19_11 36 51](https://user-images.githubusercontent.com/30132548/37591247-2da5fc96-2b6b-11e8-88a0-914383a15eed.png)
![ticket winlist_-_2018-03-19_11 41 51](https://user-images.githubusercontent.com/30132548/37591256-30bb44d6-2b6b-11e8-942c-d02ed46fd56b.png)

# Bug

## Environment
- **Version**: 8.0.0-alpha
- **OS**: Windows NT
- **Web server**: Apache/2.4.27 (Win64) PHP/5.6.31
- **PHP**: apache2handler 5.6.31
- **Database**: MySQL or MariaDB 5.7.19
- **URL**: /github/dolibarr88/htdocs/ticketsup/index.php?idmenu=132&mainmenu=ticketsup&leftmenu=

**Comment by atm-maxime** [comment]
Thanks, this was the early stages of ticket module integration
