### ISSUE TITLE
Bug: Loose records when changing nb of records per page

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#8418]
# Bug
I have 41 records, so I change nb of records from 25 to 50, and when apply there is no more records.

## Environment
- **Version**: 8.0.0-alpha
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.15-1+0~20180306120119.15+jessie~1.gbp78327e
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB-0+deb8u1
- **URL**: /compta/bank/bankentries_list.php

**Comment by dolibarr95** [comment]
Hi !
Are you on page 1 ?

**Comment by grandoc** [comment]
Hi
Yes

**Comment by atm-gauthier** [comment]
I'm trying this..

**Comment by atm-gauthier** [comment]
Hi @grandoc, is your bug still available ?
I can't reproduce it..

**Comment by grandoc** [comment]
Hi Gauthier
may be an update has faced this issue because I can't reproduce it either

**Comment by atm-gauthier** [comment]
yes, i think so, too.
Thanks for this answer
Could you close your issue if it's ok for you ?
