### ISSUE TITLE
Feature Request:  Improve odt template with new tags

### ISSUE THREAD

**Issue by mgribaudo** [Dolibarr/dolibarr#8419]
# Feature Request

Implement tags that can be used to create odt templates for invoices
In particular they are useful:
- the tags relating to the taxable income of the various VAT rates
- tags related to our bank reported on the invoice (IBAN, ...) 

# Use case

The information listed is present in Italy in almost all invoice models. 

# Suggested implementation

I made small changes to the following two files: 

htdocs\core\class\commondocgenerator.class.php
htdocs\core\modules\facture\doc\doc_generic_invoice_odt.modules.php 

that implement the solution. 
How to report them to the community?

**Comment by rjorive** [comment]
Hi, I'm very interested. Could you tell me how to do it?

Thank you very much.
