### ISSUE TITLE
Feature Request: enhance workflow for proposals

### ISSUE THREAD

**Issue by philippe-opendsi** [Dolibarr/dolibarr#8421]
Hi
Before making any PR, I would like to have the opinion of the community. Today a proposal can only be signed or refused.
I would find very helpful to have the status "Canceled" and/or "Replaced by" (on or more other proposal) available in the core of Dolibarr.
What do you think about ?
Regards
Philippe

**Comment by hregis** [comment]
@philippe-opendsi  +1 👍

**Comment by vvnt** [comment]
"Canceled" is different from "Not signed" ? "Postponed" can be nice eventually.

**Comment by philippe-opendsi** [comment]
@vvnt Yes, I'm not sure cancelled is a good option. in fact some times you never get a answer for a proposal despite a lot of call and email :-) So Postponed is maybe a better solution.
But we need to have a "Replaced by" in case a proposal is cloned to another third party or really replaces by one or more proposals

**Comment by BebZ** [comment]
Yes, but beware, the signed status, must keep the same workfow when you activate the option to "creat draft order"
Postponed, not signed, replaced by...
are good status.
