### ISSUE TITLE
Migration Issue for invoice statistics

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8424]
# Bug
After migrating from a Dolibarr 3.3 to Dolibarr 6.0, Invoices stats are not the same in 3.3 and 6.0.
Exemple : 
in 3.3  we get   for 2013 : 402 invoices for 125000
in 6.0 we get    for 2013 : 451 invoices for 165000

## Environment
- **Version**: 3.3 / 6.0
- **OS**: Debian
- **Web server**: Linux
- **PHP**: 5.6
- **Database**: Mysql
- **URL(s)**: compta/facture/stats/index.php

## Expected and actual behavior
After a migration user expects to keep his statistics....
Problem comes from handling abandoned invoices with the sql order
in v 3.3 order is
SELECT date_format(datef,'%Y') as year, COUNT(*) as nb, SUM(total) as total, AVG(total) as avg FROM llx_facture WHERE  fk_statut > 0 AND entity = 1 AND (fk_statut <> 3 OR close_code not in ('replaced', 'abandon'))  GROUP BY year ORDER BY year DESC

in 6.0 order became
SELECT date_format(datef,'%Y') as year, COUNT(*) as nb, SUM(f.total) as total, AVG(f.total) as avg FROM llx_facture as f WHERE  f.fk_statut > 0 AND f.entity = 1 AND (f.fk_statut <> 3 OR f.close_code <> 'replaced') AND f.type IN (0,1,2,3) GROUP BY year ORDER BY year DESC

the close_code 'abandon' is no more in the query.
In code we habe this note Why should we count abandonned invoices ?
// Exclude replaced invoices as they are duplicated (we count closed invoices for other reasons)

## Steps to reproduce the behavior
have a 3.3 version with invoices in state 'abandon' open url for stat
migrate to a 6.0 open the url

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by dolibarr95** [comment]
Hi
Is is this PR ?
`getAllByYear`
https://github.com/Dolibarr/dolibarr/commit/0b7305d21a6053f3c5d57593ed16fa01f05c69e1#diff-1511a45e1b66eeee1d7e52b8c2bc082a

**Comment by tiaris** [comment]
I can submit a PR, but need more informations why the sql order has been changed before
