### ISSUE TITLE
Feature Request/Discussion: Add php-cs-fixer to composer

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#8428]
# Feature Request / Discussion
One of the big problems with developing for dolibarr is the confusing mix of code that every developer is accustomed to. By adding php-cs-fixer (http://cs.sensiolabs.org/) to composer we can create a single code standard (or use existing ones) for all .php files and update all current and new files to use this code standard.

## Use case
For example, some use:
```
if () 
{
 \\code
{
```

Others:
```
if () {
\\code
{
```

And imo the even more confusing:
`if () \\code`

By using we can convert all different implementations to a single standard. This way all code will by structurally identical, and less confusing.

**Comment by marcosgdf** [comment]
This issue has already been discussed before. Check #6186

**Comment by ruistrecht-alt** [comment]
@marcosgdf I'm sorry, I didn't find #6186 before writing this suggestion.
Closing issue, since #6186 is still open
