### ISSUE TITLE
SQL Error with LEAVES functionality

### ISSUE THREAD

**Issue by MoiCoquille** [Dolibarr/dolibarr#8436]
# Bug
When going to the "LEAVES"page via the menu of via a user, I get the following error message.  
Dolibarr has detected a technical error.  

# Error Message
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180322052811
Dolibarr: 7.0.0
Level of features: 0
PHP: 7.0.27
Server: Apache
OS: Linux jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

Requested URL: /dolibarr/holiday/list.php?mainmenu=hrm&id=2
Referer: http://127.0.0.1:8080/dolibarr/user/card.php?id=2
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT rowid, code, label, affect, delay, newByMonth FROM llx_c_holiday_types WHERE (fk_country IS NULL OR fk_country = ) AND active = 1
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND active = 1' at line 1

# Environment
  - Dolibarr 7.0.0
  - Apache 2.4.29
  - MySQL 5.7.21
  - PHP 7.0.27
  - phpMyAdmin 4.7.7

**Comment by ghost** [comment]
You have to set a country into your company (http://127.0.0.1:8080/dolibarr/admin/company.php?action=edit) and define holidays type for your country (http://127.0.0.1:8080/admin/dict.php?id=28) (if not already set).
Start using an application where there is warning picto (into left menu) to tell you that you still have to complete setting, it's not just to bother you, setting is needed to start using dolibarr
