### ISSUE TITLE
Date picker issue

### ISSUE THREAD

**Issue by borsti67** [Dolibarr/dolibarr#8440]
# Bug
The date picker returns unsuitable values, at least for German installation

## Environment
- **Version**: 7.0.0
- **OS**: Linux (hosted)
- **Web server**: nginx/1.11.10
- **PHP**: 7.1.12
- **Database**: MySQL or MariaDB 5.5.56-MariaDB

## Expected and actual behavior
Selecting a date with the date picker should insert a valid date into the field.
Instead a wrongly formatted one is returned.

## Steps to reproduce the behavior
When selecting a date with the date picker button the month is shown as text instead of number. Dolibarr unfortunately does not accept this (btw: neither is a 2-digit-year sufficient...).
So the field is filled in but on SAVE the content gets replaced by the actual date and an error message states "invalid date".
The "now"-link works as expected!

## [Attached files]
Before having entered anything:
![before](https://user-images.githubusercontent.com/6476043/37794833-01407a00-2e13-11e8-9187-bc68533edce6.jpg)
Picker is open, I choose "22":
![during](https://user-images.githubusercontent.com/6476043/37794834-015a584e-2e13-11e8-9357-9aaa5fbf1787.jpg)
Result:
![after](https://user-images.githubusercontent.com/6476043/37794832-01262baa-2e13-11e8-917f-57fde608513d.jpg)
...which should have been "22.03.2018"

**Comment by PierreKr** [comment]
You have to edit the german language file:
**/dolibarr/htdocs/langs/de_DE/main.lang**

Replace the following lines:
```
FormatDateShortJQuery=dd.MM.yy
FormatDateShortJQueryInput=dd.MM.yy
```

with
```
FormatDateShortJQuery=dd.mm.yy
FormatDateShortJQueryInput=dd.mm.yy
```

MM-> mm

**Comment by borsti67** [comment]
Thanks, works for me.
Anyway I wonder why this file was changed?

**Comment by Bolli84** [comment]
Hi,

it works partly. I'm not sure if it is the same error, but I'm not able to create a date after march. It won't take april or may as valid date. 
The debug-log shows no issues.

**Comment by Bolli84** [comment]
After some tests against the austrian file I found out, that someone should ONLY replace the lines as suggestes by PierreKr until it is the following statement:

> FormatDateShortJava=dd.MM.yyyy
> FormatDateShortJavaInput=dd.MM.yyyy
> FormatDateShortJQuery=dd.mm.yy
> FormatDateShortJQueryInput=dd.mm.yy

Touching the first two lines will lead to the strange experiment, that no bill is able to be produced in April or later. My personal learing: Keep strict to the script :-)

**Comment by eldy** [comment]
Fixed in transifex for next stable version
