### ISSUE TITLE
Document attached does not appear in log event

### ISSUE THREAD

**Issue by jlbarretoh** [Dolibarr/dolibarr#8441]
# Feature request
When you sent an email with attachment in card, the document is not save.  I have sent a document to my gmail account, attachment is there but not in log event.

![2018-03-22_14-50-24](https://user-images.githubusercontent.com/15818217/37794918-f8a3feee-2de0-11e8-99db-bfcd857c605f.png)
![2018-03-22_14-51-27](https://user-images.githubusercontent.com/15818217/37794919-f8bc7794-2de0-11e8-8ea3-51963ce5f159.png)

Add a global option to keep a copy of attached files send by email via Dolibarr in the document tab of the event generated

**Comment by BebZ** [comment]
What is your version ? 
Which module you use to send an e-mail ? (from propal module ?)
Is the propal module designed to put the attachment on the event ? 
I am not sure it was developped on 6.0, maybe you're on 7. ?

**Comment by atm-maxime** [comment]
Hello.
This is not a bug. When you send a document from Dolibarr, the PDF doc is attached to the e-mail. But the event generated by the sending does not have the attached file for duplication reasons. The PDF is still on the document card (propal, order...).
A new feature could be an option to have a copy of the email attached files in the event, but it will really increase the size of the documents folder.
