### ISSUE TITLE
SQL errors creating foreign keys

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#8451]
# Bug
A user from Germany report a bug installing Dolibarr : some sql errors when creating foreign keys and indexes.
 DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
link  https://www.dolibarr.de/forum/installation/52457-fehlermeldung-sql-1071

## Environment
- **Version**: 
- **OS**: Debian 9
- **Web server**: 
- **PHP**: 
- **Database**: 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL(s)**: install

## Expected and actual behavior
Request 280 : ALTER TABLE llx_advtargetemailing ADD UNIQUE INDEX uk_advtargetemailing_name (name) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_bookmark.key
Request 299 : ALTER TABLE llx_bookmark ADD UNIQUE uk_bookmark_url (fk_user, url) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_boxes_def.key
Request 306 : ALTER TABLE llx_boxes_def ADD UNIQUE INDEX uk_boxes_def (file, entity, note) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_budget_lines.key
Request 307 : ALTER TABLE llx_budget_lines ADD UNIQUE INDEX uk_budget_lines (fk_budget, fk_project_ids) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_c_email_templates.key
Request 326 : ALTER TABLE llx_c_email_templates ADD UNIQUE INDEX uk_c_email_templates(entity, label, lang) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_c_ziptown.key
Request 352 : ALTER TABLE llx_c_ziptown ADD UNIQUE INDEX uk_ziptown_fk_pays (zip, town, fk_pays) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_categorie.key
Request 353 : ALTER TABLE llx_categorie ADD UNIQUE INDEX uk_categorie_ref (entity, fk_parent, label, type) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_commande_fournisseur.key
Request 415 : ALTER TABLE llx_commande_fournisseur ADD UNIQUE INDEX uk_commande_fournisseur_ref (ref, fk_soc, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_const.key
Request 428 : ALTER TABLE llx_const ADD UNIQUE INDEX uk_const (name, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_default_values.key
Request 455 : ALTER TABLE llx_default_values ADD UNIQUE INDEX uk_default_values(type, entity, user_id, page, param) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_ecm_files.key
Request 463 : ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files (filepath, filename) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_element_tag.key
Request 472 : ALTER TABLE llx_element_tag ADD UNIQUE INDEX uk_element_tag (entity, lang, tag, fk_element, element) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_entrepot.key
Request 473 : ALTER TABLE llx_entrepot ADD UNIQUE INDEX uk_entrepot_label (label, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_facture_fourn.key
Request 516 : ALTER TABLE llx_facture_fourn ADD UNIQUE INDEX uk_facture_fourn_ref (ref, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_facture_fourn.key
Request 517 : ALTER TABLE llx_facture_fourn ADD UNIQUE INDEX uk_facture_fourn_ref_supplier (ref_supplier, fk_soc, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_links.key
Request 571 : ALTER TABLE llx_links ADD UNIQUE INDEX uk_links (objectid,label) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_menu.key
Request 586 : ALTER TABLE llx_menu ADD UNIQUE INDEX idx_menu_uk_menu (menu_handler, fk_menu, position, url, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_product.key
Request 623 : ALTER TABLE llx_product ADD UNIQUE INDEX uk_product_barcode (barcode, fk_barcode_type, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_product_attribute.key
Request 629 : ALTER TABLE llx_product_attribute ADD UNIQUE INDEX uk_product_attribute_ref (ref) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_product_attribute_value.key
Request 630 : ALTER TABLE llx_product_attribute_value ADD CONSTRAINT unique_ref UNIQUE (fk_product_attribute,ref) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_societe.key
Request 703 : ALTER TABLE llx_societe ADD UNIQUE INDEX uk_societe_barcode (barcode, fk_barcode_type, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_user_param.key
Request 742 : ALTER TABLE llx_user_param ADD UNIQUE INDEX uk_user_param (fk_user,param,entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
Erstellen der Fremdschlüssel und Indizes für Tabelle llx_usergroup.key
Request 746 : ALTER TABLE llx_usergroup ADD UNIQUE INDEX uk_usergroup_name (nom, entity) SQL-Fehler DB_ERROR_1071 Specified key was too long; max key length is 767 bytes

## Steps to reproduce the behavior
this can help https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes
for first query we build an index on a varchar(200) but with utf8 this seems to be too long.
Should we limit index length on varchar columns or avoid UNIQUE ?

**Comment by tiaris** [comment]
There is a limited length for indexes, so we need to be carefull with indexes on varchar columns.

**Comment by ant1d0t** [comment]
I was the person reporting that. You should definitely change your queries. because utf8mb4 is a quasi standard (shouldn't use anything else in the western world)  and utf8mb4 devides that number by 4(^^surprise.lol). And like in my case i have a managed server with no ability to configure anything to work arround. The mysql vers. is 5.3 which will always throw that error...
this should be top prio for optimization :-)

**Comment by tiaris** [comment]
Errors on a standard install on debian 9
![image](https://user-images.githubusercontent.com/919513/42220132-722509be-7ece-11e8-8a88-afcf84648e80.png)

**Comment by cebe** [comment]
related to #3647, currently you have to go with database encoding of `utf8` instead of `utf8mb4`.

**Comment by ant1d0t** [comment]
yep. That's what i did for now :-)

**Comment by sezio** [comment]
Hello, 
I have the same problem. 
Is there any risks for an eventual data loss / corruption if I use utf8 instead of utf8mb4 ? 
Thanks

**Comment by cebe** [comment]
There is no risk at all, you just can not store some of the emoij characters that use more than 3 bytes. Quite unlikely that you use a lot of emoij in Dolibar :)
