### ISSUE TITLE
Bug: Members module setup

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#8455]
# Bug
There is a bug in members module setup in miscellaneous tab (tested on Dolibarr 7.0.0 and 8.0.0 alpha) all the information are with % instead of __ as per below
%FULLNAME%
ID: %ID%
%EMAIL%
%ADDRESS%
%ZIP% %TOWN%
%COUNTRY%
Therefore, member business cards display %FULLNAME% instead of a real member's name. I assume that applies to the next tab in members module setup which is emails but I haven't tested it as I don't use subscriptions.
## Environment
- **Version**: 7 & 8
- **OS**: Linux server.turro24.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.34
- **Database**: MySQL or MariaDB 5.5.5-10.2.13-MariaDB
- **URL(s)**: /htdocs/adherents/admin/adherent.php?save_lastsearch_values=1&backtopage=%2Fhtdocs%2Fadmin%2Fmodules.php%3Fsearch_nature%3D%26search_version%3D%26search_status%3D

## Expected and actual behavior
Expected behavior is to show the real information on member business cards instead of %FULLNAME%, etc.

## Steps to reproduce the behavior
/htdocs/adherents/cartes/carte.php?leftmenu=export and generate a member business card

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
<img width="1158" alt="screen shot 2018-03-26 at 22 18 06" src="https://user-images.githubusercontent.com/28427270/37934422-137e7da8-3146-11e8-9479-b341200e6be7.png">

## Suggested steps
replace "%" with "__"

**Comment by atm-quentin** [comment]
Hello,

I work on this.
