### ISSUE TITLE
Bad currency in the file \fourn\commandes\card.php

### ISSUE THREAD

**Issue by appoloniaSrc** [Dolibarr/dolibarr#8459]
# Bug
Currency don't use the main company currency if we create a new supplier order from the left menu without using a supplier 

## Environment
- **Version**: [*7.0.0*]
- **OS**: [*Windows 10*]
- **Web server**: [*Apache last*]
- **Database**: [*MySqL*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
- From Commercial Menu
- Supplier Order
- Click on New order

## [Attached files]
![dol](https://user-images.githubusercontent.com/29565150/37959749-207b6304-31b4-11e8-903c-20160e129542.png)

## Suggested implementation
If the order is creates directly from the left menu (supplier $socid  is null) , use the main company currency to inititate **$currency_code** else the form will display the first currency in the list.

**Comment by atm-maxime** [comment]
I'm working on this issue
