### ISSUE TITLE
Prospect Status Cannot be Set to "Do Not Contact"

### ISSUE THREAD

**Issue by orielsystems** [Dolibarr/dolibarr#8470]
# Bug
When the status "Do Not Contact" is clicked, either in the list view or in the prospect card, it resets to "Never Contacted".

## Environment
- **Version**: 7.0
- **OS**: Linux DockLeaf 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:14 UTC 2018 i686
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: 7.0.28-0ubuntu0.16.04.1
- **Database**: MySQL or MariaDB 5.7.18-ndb-7.6.3
- **URL(s)**: societe/list.php?type=p&leftmenu=prospects | societe/card.php?socid=958&save_lastsearch_values=1

## Expected and actual behavior
The expected behaviour is for the prospect to be marked as "Do Not Contact".  The actual behaviour is that the prospect is marked as "Never Contacted".

## Steps to reproduce the behavior
To reproduce the behaviour of the bug, mark a prospect as "Do Not Contact" and check it.  Once refreshed, the prospect will show a status of "Never Contacted".

**Comment by atm-quentin** [comment]
Hello, i handle this

**Comment by orielsystems** [comment]
Thank you.
