### ISSUE TITLE
Personal and professional titles for users/employees

### ISSUE THREAD

**Issue by chnce** [Dolibarr/dolibarr#8472]
# Feature Request
It would be nice to have the same personal and professional titles we have for third parties (Mr., Ms., Dr., etc. )also for users/employees.
We put the employee as sender on proposals/invoices and therefore the title is needed.

**Comment by Zebedeu** [comment]
@egils-consulting , @atm-maxime Is anyone already working on it? I am interested in working on it

**Comment by atm-maxime** [comment]
You're welcome to start working on it.

**Comment by ksar-ksar** [comment]
Integrated in V13
