### ISSUE TITLE
SQL error on install 

### ISSUE THREAD

**Issue by blagoeres** [Dolibarr/dolibarr#8473]
Hi,

I get this error when installing Dolibarr on server. You can see in video what kind of error I get.

https://www.dropbox.com/s/lbi4yfzk4szep5q/err.mp4?dl=0

The stack is:

- Ubuntu 16
- MySQL 5.7.21
- NGINX
- PHP 7.0

I can proceed with the installation normally, even with this error.

**Comment by futurehousestore** [comment]
I think this error is related to server charset. Check if your DB charset is set to UTF-8 Unicode (utf8) if not then create the DB with UTF-8 Unicode (utf8) charset and run the install again.

**Comment by blagoeres** [comment]
Ok. I will try and check.

**Comment by blagoeres** [comment]
You were right! Thank you! I needed to switch to `utf8` charset.
