### ISSUE TITLE
Error adding expenses

### ISSUE THREAD

**Issue by jlbarretoh** [Dolibarr/dolibarr#8474]
# Bug
When i try to add an expense im getting an error:
**You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(19) AND cv.fk_pays = 70' at line 1**

I guess error is related with IVA tax.  If i delete rate tax it works but when i add the IVA Tax stop to work.

## Environment
Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180329010326
Dolibarr: 7.0.0
Level of features: 0
PHP: 7.0.28
Server: Microsoft-IIS/8.5
OS: Windows NT DONGEE 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Requested URL: /expensereport/card.php
Referer: .../expensereport/card.php?id=2
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT taux, localtax1, localtax2, localtax1_type, localtax2_type FROM llx_c_tva as cv WHERE cv.taux = 19(19) AND cv.fk_pays = 70
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: **You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(19) AND cv.fk_pays = 70' at line 1**

**Comment by ghost** [comment]
I deal with it
