### ISSUE TITLE
Bug: PHP Warnings in extrafields webpages

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#8478]
# Bug

( ! ) Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/dolibarr/htdocs/core/tpl/admin_extrafields_view.tpl.php on line 70
--

1 | 0.0109 | 400024 | {main}( ) | .../user_extrafields.php:0
2 | 0.3887 | 1466576 | require( '/var/www/dolibarr/htdocs/core/tpl/admin_extrafields_view.tpl.php' ) | .../user_extrafields.php:75

( ! ) Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/dolibarr/htdocs/core/tpl/admin_extrafields_view.tpl.php on line 70
--

1 | 0.0126 | 400024 | {main}( ) | .../group_extrafields.php:0
2 | 0.4285 | 1466384 | require( '/var/www/dolibarr/htdocs/core/tpl/admin_extrafields_view.tpl.php' ) | .../group_extrafields.php:76

## Environment
- **Version**: 7.0.1
- **PHP**: 7.2

**Comment by atm-gauthier** [comment]
I'm working on this one
