### ISSUE TITLE
Bug: Mobile phone icon for the login name in the user card

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#8479]
# Bug
There is a mobile phone representing the login name in the user card. Does not seem an expected behaviour. 

## Environment
- **Version**: 7.0.1
- **URL(s)**: user/card.php?id=1

![image](https://user-images.githubusercontent.com/168744/38076839-2a1b5732-3337-11e8-9732-7b167481e8d5.png)

**Comment by ATM-Marc** [comment]
I'm working on it
