### ISSUE TITLE
From lists, filter works only on the first value from a field which contain multiple values.

### ISSUE THREAD

**Issue by dov29** [Dolibarr/dolibarr#8480]
# Bug
From lists, filter works only on the first value from a field which contain multiple values.

## Environment
- **Version**: *Dolibarr 7.0.0*
- **OS**: *Ubuntu Server 16.04*
- **Web server**: *Apache/2.4.18*
- **PHP**: *PHP 7.0.28*
- **Database**: *mysql  Ver 15.1 Distrib 10.0.34-MariaDB*

## Expected and actual behavior
On the case below, a filter on "Equipier 2018" should have a result but no lines appear. It works on "Adhérent actif" so I conclude that the filter is apply only on the first value.

BTW, I experienced that is not possible a this stage to filter on multpile values either from export module or lists....

## Steps to reproduce the behavior
1. Create a complementary attributes either from companies, contacts or members modules.
2. This attributes is "checkboxes" attribute so something with multiple values
3. Apply multiple values from this attribute to a contact.
4. Apply filter on the second value (alphabetic)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

![selection_028](https://user-images.githubusercontent.com/18277497/38079896-55209240-3340-11e8-84a0-2b6781a9e39b.png)

**Comment by atm-greg** [comment]
I handle this

**Comment by dov29** [comment]
Great ! :+1:
