### ISSUE TITLE
bug : wrong march month initial letter in dasboard

### ISSUE THREAD

**Issue by glaviooz** [Dolibarr/dolibarr#8487]
Version : 7.0.1

![image](https://user-images.githubusercontent.com/37912192/38132269-ae4af368-340a-11e8-965c-a677a86c3cd9.png)

**Comment by unareil** [comment]
Bonjour, pouvez-vous me dire de quel widget, il s'agit exactement (clients ou fournisseurs), je n'arrive pas à reproduire votre bug.

**Comment by glaviooz** [comment]
résolu merci



Bonjour, pouvez-vous me dire de quel widget, il s'agit exactement (clients ou fournisseurs), je n'arrive pas à reproduire votre bug.
