### ISSUE TITLE
Bug: Datepicker wrong format

### ISSUE THREAD

**Issue by bastolino** [Dolibarr/dolibarr#8492]
# Bug
At least in German language: If picking a date with the datepicker the Date is inserted with the full name of the month (e.g. "01.April.2018") instead of the number of the name (e.g. 01.04.2018). This brings the date-verification to fail.

## Environment
- **Version**: 7.0.0, 7.0.1
- **OS**: Ubuntu 16.04.4 LTS
- **Web server**: Apache/2.4.18 (Ubuntu) 
- **PHP**: PHP 7.0.28-0ubuntu0.16.04.1
- **Database**: mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64)
- **URL(s)**: private
## Expected and actual behavior
Expected: Datepicker sets date-textfield with correctly formatted date
Actual: Date-textfield is filled with date in wrong format.

## Steps to reproduce the behavior
e.g.: (German languagepack) Create a new invoice draft and pick as invoice a date with the datepicker. The date gets selected in a wrong format. Click on Create and the verification of the fields will throw an error

## [Attached files]
Sent on request.

**Comment by futurehousestore** [comment]
Hi. Thank you for submitting your issue, please note that your issue was already reported and it is related to #8440 where you can find a solution. Regards

**Comment by bastolino** [comment]
Thanks, did not find that issue... (searched for "datepicker" instead of "date picker")
