### ISSUE TITLE
Bug: unable service creation if product module not activated

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#8506]
# Bug

With 7.0.1 version, creation of a new service is not possible (white page) when the service module is activated but not the product module. Once you activate the product module, the creation page for new services is working. Creation of a new service is working perfectly well.

## Environment
- **Version**: 7.0.1
- **OS**: Debian
- **URL** : .../dolibarr/htdocs/product/card.php?leftmenu=service&action=create&type=1

**Comment by atm-quentin** [comment]
Hello,

I just tried it on a 7.0.2 and i don't have the problem.
Try to upgrade your version to the latest 7.0.2 will probably resolve your problem.

Best regards,
Quentin.

**Comment by hregis** [comment]
@atm-quentin 
7.0.2 is not an official release for the moment
