### ISSUE TITLE
Filter not working in bankentries_list after upgrade to 7.01

### ISSUE THREAD

**Issue by eapcorreo** [Dolibarr/dolibarr#8510]
Hi all comunity (sorry my poor english)
I send bug here after compare files in v 7.00 and 7.01, with no success
on discover what is happening. I use dolibar for my personal things,
and I develop/modify actual or new modules for freelance clients.

# Bug
In bank transactions list, if a date is used to filter, you see a lot of entries
repeated. In my data, with no filter, I have 923 items, if I use one operation date to
filter, 9681 entries are reported, a lot of repeated.

## Environment
Dolibarr 7.01
Linux Mint
Lampp server
PHP 5.5.15
Apache/2.4.10 (Unix) OpenSSL/1.0.1i PHP/5.5.15 mod_perl/2.0.8-dev Perl/v5.16.3
MySQL or MariaDB 5.6.20

#URL 
... htdocs/compta/bank/bankentries_list.php

## Expected and actual behavior
list should show only entries match with filter 

## Steps to reproduce the behavior
enter URL and use a date as filter

Thanks a lot to all comunity around the world
I am from Buenos Aires, Argentina.
(next Rusia winners ...)

**Comment by eapcorreo** [comment]
Hello all.
I think find the problem in repeated lines output in bank entries.

In file bankentries_list.php:

When building SQL,  the line 458 have this:

if ($search_bid) $sql.= MAIN_DB_PREFIX."bank_class as l,";

I fixed the problem  with this change:

if ($search_bid>0) $sql.= MAIN_DB_PREFIX."bank_class as l,";

Explanation:
In all page when evaluate $search_id all times is used $search_bid>0
except in line 458.
The bad behaivor is that  bank_class table is being inluded, but is not neccesary.

Please, for the forum manager:
Please close issue if this change in code is ok for you

Hope this help
Regards
Eduardo Perez 
from Buenos Aires Argentina

**Comment by atm-greg** [comment]
Fixed in next release

**Comment by eapcorreo** [comment]
Ok thanks very much.
