### ISSUE TITLE
Security - Discovered vulnerabilities

### ISSUE THREAD

**Issue by trivettebf** [Dolibarr/dolibarr#8511]
Hi,

We discovered multiples vulnerabilities affecting version 6.0.0 up to 7.0.1. Is it possible to get a way to contact you securely to report those bugs to the team?

Thanks

**Comment by dolibarr95** [comment]
Hi !
You can send to security@dolibarr.org

**Comment by trivettebf** [comment]
Email sent. Thank you for your quick response.
