### ISSUE TITLE
Bug: Make Supplier Order event repeated on page reload

### ISSUE THREAD

**Issue by francois-opendsi** [Dolibarr/dolibarr#8512]
# Bug
When _Making_ / placing a Supplier Order, after clicking Yes to confirm, reload the page with `F5` key.
The submit event / action is repeated and order status is set to _Ordered_ once again.

## Environment
- **Versions**: 6.0, 7.0
- **OS**: Gnu/Linux
- **Web server**: Apache2
- **PHP**: PHP 7.0
- **Database**: MariaDB
- **URL(s)**: `fourn/commande/card.php?id=1&datecommande=1522879200&methode=5&comment=&action=confirm_commande&confirm=yes`

## Expected behavior
Expected to redirect URL so action is not performed again on page reload.

## Steps to reproduce the behavior
1. Create a new Supplier Order
2. Add Products to it.
3. Approve / Validate it.
4. Click the _Make Order_ button.
5. Select a method, make.
6. Click _Yes_ to confirm the action.
7. Reload the page pressing `F5` key.
8. Go to the _Events/Agenda_ tab and check the `Automatically inserted events | Supplier order PO1804-0001 submited` appears **twice**.

## Attached files
![screenshot from 2018-04-05 10-17-36](https://user-images.githubusercontent.com/32769270/38354727-e369cf7e-38ba-11e8-9fe9-8af0995fbac2.png)

![screenshot from 2018-04-05 10-18-27](https://user-images.githubusercontent.com/32769270/38354741-f3bd30a0-38ba-11e8-9262-e24348c6bea6.png)

**Comment by ATM-Nicolas** [comment]
Hello, i handle this
