### ISSUE TITLE
Creating Product categorie very slow!

### ISSUE THREAD

**Issue by klikict** [Dolibarr/dolibarr#8513]
Issue: When adding a product categorie, the system sql service spikes. Adding of just one categorie takes minutes.
PHP 5.6.3
Apache

Replication: Add product categorie
Wait for a couple of minuets

**Comment by dolibarr95** [comment]
Hi!
Externals modules ?

**Comment by klikict** [comment]
Hi,

No it happens when I want to create a Tag/Category, it takes a long time for creating it.. 




![schermafbeelding 2018-04-05 om 13 09 45](https://user-images.githubusercontent.com/29679338/38362883-ba094606-38d2-11e8-9555-f22b14642041.png)
![schermafbeelding 2018-04-05 om 13 09 52](https://user-images.githubusercontent.com/29679338/38362889-be3cfe2a-38d2-11e8-8eb2-bcca373bc6e3.png)

**Comment by futurehousestore** [comment]
Hi klikict,
Do you use InfraSSupPrice or InfraSPack? If so then download an updated version from dolistore or deactivate them as the old versions slow down the system.

**Comment by klikict** [comment]
Hi, No i am not using those addons..

**Comment by hregis** [comment]
@klikict 
dolibarr 7.0.1 ?

**Comment by klikict** [comment]
No at version 7.0.0

**Comment by hregis** [comment]
@klikict 
first try to update with 7.0.1

**Comment by klikict** [comment]
Updated, does not fix the issue at all...

**Comment by dolibarr95** [comment]
Hi
Have you tested with all externals modules disabled?
