### ISSUE TITLE
BUG : Values (here email) are truncated from contact list view 

### ISSUE THREAD

**Issue by dov29** [Dolibarr/dolibarr#8515]
# Bug
Values (here email) are truncated from list view and I didn't figure out how to show entire value.

## Environment
- **Version**: 7.0
- **OS**: Linux
- **Web server**: Apache 2
- **PHP**: PHP 7.0
- **Database**: MariaDB
- **URL(s)**: contact/list.php?leftmenu=contacts

## Expected  behavior
Show entire value

## Steps to reproduce the behavior
Select multiple fields from contact list, email value would be truncated.

## [Attached files]
![selection_012](https://user-images.githubusercontent.com/18277497/38360913-f1bd5864-38cb-11e8-9f50-0a8e60adca74.png)

**Comment by dolibarr95** [comment]
Hi!
https://doxygen.dolibarr.org/d9/d69/functions_8lib_8php_source.html#l02695

**Comment by dov29** [comment]
Hi, thanks ! 

I'm not really a good developer ! ;)

So I understand that I have to modified functions.lib.php but what do you suggest to never have a field truncated and still have a good display. Coz even if I select only email field, it still truncated...

![selection_013](https://user-images.githubusercontent.com/18277497/38361656-702a4dd6-38ce-11e8-8d79-64fb594ed168.png)

**Comment by dov29** [comment]
Ok I got it, I removed ",18" from contact/list.php in line 

      // EMail
        if (! empty($arrayfields['p.email']['checked']))
        {
                print '<td>'.dol_print_email($obj->email,$obj->rowid,$obj->socid,'AC_EMAIL',18).'</td>';
                if (! $i) $totalarray['nbfield']++;

Maybe this could be modified from Dolibarr configuration for next version...

Thanks !
