### ISSUE TITLE
Bug: Tableau de Bord

### ISSUE THREAD

**Issue by Alek85** [Dolibarr/dolibarr#8518]
# Bug Tableau de Bord

## Environment
- **Version**: 7.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.0.25
- **Database**: MySQL or MariaDB 5.5.55-0+deb7u1-log
- **URL**: /doli/htdocs/index.php?mainmenu=home&leftmenu=home

**Comment by Alek85** [comment]
Le Tableau de bord des éléments ouverts a un problème d'affichage, 

![image](https://user-images.githubusercontent.com/32295446/38408477-0b906d00-397e-11e8-9e33-7d143757b74d.png)

Comment corriger ?

**Comment by hregis** [comment]
@Alek85 
je n'arrive pas à reproduire ton problème,
tu as essayez de vider le cache de ton navigateur ?
si oui vérifie si un module externe ne crée pas ce soucis d'affichage.

**Comment by Alek85** [comment]
J'ai le même problème sous Chrome ou sous firefox
le cache a été vidé

**Comment by hregis** [comment]
@Alek85 
et en utilisant la fonction "inspecter" du navigateur, est-ce qu'il y a des erreurs ?

**Comment by Alek85** [comment]
non pas erreur : 
![image](https://user-images.githubusercontent.com/32295446/38409921-91236314-3983-11e8-856a-220d118d4143.png)

**Comment by hregis** [comment]
@Alek85 
est-ce que tu as des modules externes susceptibles de créer ce soucis ?

**Comment by Alek85** [comment]
non je  ne vois pas - avant de faire la mise à jour 7.01 cela fonctionnait sous la version 6.
il y a aussi les images Clients ou adhérents ou icônes sont trop grands, j'ai dû recharger les images pour que la taille devienne normal. 

![image](https://user-images.githubusercontent.com/32295446/38410969-4876a588-3986-11e8-86ae-ed8962995d2c.png)

**Comment by Alek85** [comment]
Sinon tout le reste semble bien fonctionner

**Comment by hregis** [comment]
@Alek85 
quand tu es sur "inspecter" tu as quoi dans les onglets "network" et "console" ?

**Comment by Alek85** [comment]
![image](https://user-images.githubusercontent.com/32295446/38412057-c5708fac-3988-11e8-8c65-7127828d3800.png)

**Comment by Alek85** [comment]
![image](https://user-images.githubusercontent.com/32295446/38412091-da908b30-3988-11e8-9d5e-7adde22811a6.png)

**Comment by hregis** [comment]
@Alek85 
oui mais recharge la page pour visualiser

**Comment by Alek85** [comment]
Ah ok :)

![image](https://user-images.githubusercontent.com/32295446/38412342-6ee98f66-3989-11e8-8e8e-cad53483ed76.png)

**Comment by Alek85** [comment]
![image](https://user-images.githubusercontent.com/32295446/38412396-920222b0-3989-11e8-9e06-e52c3fda8972.png)

**Comment by Alek85** [comment]
A propos, je suis sous OVH  aurait-il une incidence ?

**Comment by hregis** [comment]
@Alek85 
tu dois pouvoir essayer en PHP 5.6.x ou 7.1.x ?

**Comment by Alek85** [comment]
Ok j'essaie d'abord 5.6 = Même erreur

**Comment by Alek85** [comment]
Avec PHP 7.1 - j'ai une erreur
Not Implemented
POST to /doli/htdocs/index.php not supported.
Additionally, a 501 Not Implemented error was encountered while trying to use an ErrorDocument to handle the request.

Idem en PHP 7.2
je reviens en 7 qui fonctionne tout comme 5.6

**Comment by hregis** [comment]
@Alek85 
ce sera plus simple de me contacter en privé afin que je puisse regarder en direct
regis dot houssin at gmail dot com

**Comment by Alek85** [comment]
Ok
