### ISSUE TITLE
Feature to enter serial from a textfile when making receptions

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#8519]
# Bug
Improve and fix bugs on Inventory management the following elements: Product reception for multiple units, Virtual Product Management, Shipments

## Environment
- **Version**: 7.0.1
- **OS**: Ubuntu Server 16.0.4 LTS
- **Web server**: Apache2.4
- **PHP**: 7.0
- **Database**: MySQL 5.7

## Expected and actual behavior
Expected:
1. Product Reception of multiple units of the same products:
- For items with serial numbers, one line per item should be open to allow for serial number entry.
2. Shipments of Virtual Products
If all components are available in physical stock, Virtual product number should show 1 or more depending on components.
Services do not count as missing items
All individual components with serial number should display choice of available unit with available SN. 
All components should be discounted from stock and show in the shipment manifest.

Actual
1. Product Reception of multiple units of the same products:
- For items with serial numbers, only on line for serial number entry. You have to accept reception of one product, then do it all over again for the next unit... Not friendly nor practical.
2. Shipments of Virtual Products
With all components are available in physical stock, Virtual product number shows 0 and is not available in Warehouse.
No individual components with serial number. No serial number available in the shipment summary.

## Steps to reproduce the behavior
1. Receive item in multiple unit with serial number mandatory....

2. Prepare shipment of Virtual Product will all components available...

![screenshot from 2018-04-06 17-05-47](https://user-images.githubusercontent.com/5640062/38429948-32408038-39c0-11e8-849d-9aa055daed78.png)

![screenshot from 2018-04-06 17-26-08](https://user-images.githubusercontent.com/5640062/38429950-3271a5b4-39c0-11e8-8353-2a0fb56560bd.png)

**Comment by eldy** [comment]
Your text "For items with serial numbers, only on line for serial number entry."
On screen shot, we can see there is several line, one per serial number on product BX1400U.
Why don't you just enter the quantity for each lot on each line to record the shipment in one time ? 

Also in the shipment summary, you have detail of lot by putting your mouse on the link "Lot/Serial details"

**Comment by edupulpillo** [comment]
Could be possible to fill "serial number ranges"?
When a large number of goods are received is not practical to do it one by one, and much better to enter "serial number ranges" because sometimes are consecutive.
For example:  serial numbers from 000001 to 0001000 (to receive a qty of 1000 items)

**Comment by dom-breizh** [comment]
@eldy 

Sorry I did not add a screen shot for the inventory data entry part. When you receive 2 or more items of the same kind, you should be able to enter the right number of serial numbers. (or although I never tried, can you insert more than one and the program splits them in different records ?)

On the screen shot, you can indeed see several lines for the BX1400U. For that results, I had to add them in several entries during reception, meaning I said I received one, enter the serial number, validated the reception process as incomplete, returned to the reception page, entered the new serial for the new item and validated it again. That way I have all my serials in the database.

You say "Also in the shipment summary, you have detail of lot by putting your mouse on the link "Lot/Serial details"". I can't find that link. Can you please point me to the right place? However lot number is not the same as serial number. I am not looking for lot numbers.

@edupulpillo 

Serial number range could be helpfull for some users. Not in my case. I don't usually receive sequential items.

Thanks

**Comment by BebZ** [comment]
![image](https://user-images.githubusercontent.com/3694135/38845737-2c1e8c86-41f9-11e8-9f20-64d76b82186c.png)

have you tried this button to enter serial numbers on reception ?

and this other button to check what serial is in the shipment
![image](https://user-images.githubusercontent.com/3694135/38845805-7d212e0e-41f9-11e8-83e1-61798640623e.png)

**Comment by BebZ** [comment]
@eldy II agree virtual products with serials don't propose batch numbers.
Is it an evolution Dolibarr needs , or is it a better way ? already on the rails ?

**Comment by edupulpillo** [comment]
Thanks for the comments! answering:
"Serial number range could be helpfull for some users. Not in my case. I don't usually receive sequential items"

Even some users no need it, a only one serial number is a range from-to of only one serial number, so if "to" is empty is assumed only one serial number entered.
This makes pretty good to manage all the people that need to manage productions of 2000 and more products with serial numbers, and  maintain easy the people need only one by one.
Also make that the number of records in the database needed for traceability about serialnumbers decrease a lot. 
CASE:
range= 00001 to 20000 serial numbers, one record needed in DB.
if move the number 09999 then can generate 3 ranges for the DB
range1=00001 to 09998
range2=09999 to 09999
range3=10000 to 20000
with this aproach, we are using 3 records, instead maintaining 20000 records with the serial numbers.
Also the orders, shipments, etc... everything is going to be very clean, with much less "numbers" on the documents. Do not oyu think it will be a great improvement?
Thanks in advance for reading it !

**Comment by BebZ** [comment]
@dom-madrid 

did you solve you rpoble with the "button" ?
you should modify qty inside field before click on the button

**Comment by edupulpillo** [comment]
The probñem srill exist in version 11.0.3
And serial number ranges management are strongly recommended. Specially managing receptions and deliveries of 20000 products each time, obviously is not possible to input 20000 times one only serial number.

**Comment by eldy** [comment]
With v12, changing the quanty before clicking will no more be required. However this is not enough for a large number of different serial numbers.
Idea will be to add a new popup to cut and paste values of all lots from a text file to fill the reception record.

**Comment by edupulpillo** [comment]
Also for the deliveries, and also an option to show the serial numbers in the invoices.
Is very useful to control the guarantee services with the customers.

**Comment by atm-maxime** [comment]
Still relevant
