### ISSUE TITLE
dolGetFirstLastname doesn't respond to MAIN_FIRSTNAME_NAME_POSITION constant

### ISSUE THREAD

**Issue by tcarterfrance** [Dolibarr/dolibarr#8521]
# Bug
dolGetFirstLastname doesn't respond to MAIN_FIRSTNAME_NAME_POSITION constant

## Expected and actual behavior
Expected : MAIN_FIRSTNAME_NAME_POSITION=1 prints Firstname before Lastname in PDF's
Actual : MAIN_FIRSTNAME_NAME_POSITION has no effect

## Steps to reproduce the behavior
1) Make a quote. Generate the PDF with Azur, check address boxes. Should be Lastname before Firstname
2) In the config add MAIN_FIRSTNAME_NAME_POSITION=1 
3) Regenerate the PDF with Azur, check address boxes. Should now be Firstname before Lastname

## Fixe :  
/core/lib/functions/lib.php
Line : 5379, in function dolGetFirstLastname 

Replace : 
if ($nameorder < 0) $nameorder=(empty($conf->global->MAIN_FIRSTNAME_NAME_POSITION));

With : 
if ($nameorder < 0) $nameorder=$conf->global->MAIN_FIRSTNAME_NAME_POSITION;

Thanks, for great software Folks, Cheers, Thomas CARTER, CERGY INTERNET.

**Comment by atm-greg** [comment]
deal with it

**Comment by atm-greg** [comment]
i handle this

**Comment by tcarterfrance** [comment]
thanx

Cordialement
Thomas CARTER
----------------------------
CERGY INTERNET
Courrier : 16, rue Ampère, CS7001, 95307 CERGY PONTOISE CEDEX
GPS : POLE-MULTIMEDIA,16 rue Ampère, 95300 Pontoise
Mobile : 06 03 51 10 15
cergy-internet.fr, polemultimedia.fr

**Comment by withheld** [comment]
I know this was closed in Apr but since this fix was implemented in 7.0.3, the problem now occurs in en_CA/enUS and en_GB. Should I create a new issue or provide the details here?
