### ISSUE TITLE
[BUG] Not able to create a service when product module is disable

### ISSUE THREAD

**Issue by LesCarnets** [Dolibarr/dolibarr#8523]
# Bug
Not able to create a service when product module is disable

## Environment
- **Version**: 7.0.1
- **OS (host)**: Linux 2.6.32-openvz-042stab127.2-amd64 #1 SMP Thu Jan 4 16:43:57 MSK 2018 x86_64
- **Web server**: Apache
- **PHP**: 7.0.27
- **Database**: MYSQL (MySQL or MariaDB 5.5.5-10.1.31-MariaDB-1~jessie - DRIVER: mysqli (mysqlnd 5.0.12-dev - 20150407))
- **URL(s)**: ./product/card.php?leftmenu=service&action=create&type=1

## Expected and actual behavior
- **Expected behavior**: If I sell only services (no product), I expect we can deploy only the "Service" module and disable the "Product" module. In this case if I go to "Services" and "create a new service" it should work
- **Actual behavior**: If "Service" module is enable and "product" mudule is disable, in the "Service" menu, I can see the services list. I can  also see the "create new service" link but when I clik on it, I have only a blank page (even no error message)

## Steps to reproduce the behavior
1) Deploy Dolibarr 7.0.1 (I didn't test with another version: both test and prod are running the 7.0.1 for me)
2) Enable the "Services" module (and do not activate the "Products" module)
3) Go to Service
4) Try to create a new one : your are facing a blank page

Thank you very much by advance for your help !

Best regards

**Comment by hregis** [comment]
@LesCarnets 
this is fixed in the next release

**Comment by LesCarnets** [comment]
@hregis Thank you so much for this fix! Will it work with service creation from REST API as well?
When you say "next release", you mean "7.0.2", correct ? Do you know when this release is supposed to be available ?
Thank you again,
Best regards

**Comment by atm-greg** [comment]
deal with it

**Comment by atm-maxime** [comment]
I have fixed this issue here : #8499
It has been merged into upcoming 7.0.2
Don't know for REST API though...
