### ISSUE TITLE
[Bug] Layout of supplier draft orders/invoices is not correctly resized

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#8526]
# Bug
The web layout of draft (not convalidated) **supplier orders or invoices** is not correctly sized on the web page.
Since the text box assigned to the service/product description is wider than requested, the page shifts towards the right border and we need to scroll horizontally to watch the content and press the buttons in order to perform an action.
This affects only the supplier area, not that for client.

## Environment
- **Version**: 7.0.1
- **OS**: Linux 3.10.102 #15254 SMP Fri Jan 26 06:40:50 CST 2018 x86_64
- **Web server**: Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141
- **PHP**: 5.6.34
- **Database**: MariaDB 5.5.57

**Comment by atm-maxime** [comment]
Hello
Can you provide screenshots as example ?
Maybe I have a wider screen, but I can't reproduce the horizontal scroll, unless I resize my browser to a very small size.

**Comment by minigitmax** [comment]
Hi Maxime,

Thanks a lot for your reply.
Here is what happens to the sheets for a new supplier invoice as example. I've grabbed two screenshots, the first with zoom at 100%, the second with zoom at 90%. Both have resizing problems. The same behavior happens for new supplier order. 
The third screenshot is for the supplier order list layout that is not affected by wrong resizing and remains unchanged at any view size, just like any other section.

My screen resolution is 1920x1200.

![1_create_invoice_100](https://user-images.githubusercontent.com/26568957/38611086-0ce2d0d6-3d83-11e8-9892-7d4561c8f050.jpg)
![2_create_invoice_90](https://user-images.githubusercontent.com/26568957/38611087-0cf8c0c6-3d83-11e8-84fc-6dc015fed5e3.jpg)
![3_supplier_po_list_100](https://user-images.githubusercontent.com/26568957/38611088-0d113c8c-3d83-11e8-8788-663b1fd613fd.jpg)

**Comment by minigitmax** [comment]
The issue is still there after updating to 7.0.2
Checked also in different computers/environments. Currently detected in pc with screen resolution 1920x1080, at browser zoom > 80%.
