### ISSUE TITLE
Error when upgrading from 7.0.0 > 7.0.1

### ISSUE THREAD

**Issue by klikict** [Dolibarr/dolibarr#8527]
Getting this error when trying to upgrade from 7.0.0 to 7.0.1

Fatal error: Uncaught Error: Call to undefined method mysqli::get_charset() in /home/XXXX/public_html/aa/install/upgrade.php:188 Stack trace: #0 {main} thrown in /home/XXXX/public_html/aa/install/upgrade.php on line 188

**Comment by hregis** [comment]
@klikict 
what do you have on line 188 of "/install/upgrade.php" ?

**Comment by klikict** [comment]
$tmparray = $db->db->get_charset();
        	print '<tr><td>'.$langs->trans("ClientCharset").'</td>';

**Comment by hregis** [comment]
@klikict 
this function don't exists, put in comment all that : 

```
if ($db->type == 'mysqli')
        {
        	$tmparray = $db->db->get_charset();
        	print '<tr><td>'.$langs->trans("ClientCharset").'</td>';
        	print '<td align="right">'.$tmparray->charset.'</td></tr>';
        	dolibarr_install_syslog("upgrade: " . $langs->transnoentities("ClientCharset") . ": " .$tmparray->charset);
        	print '<tr><td>'.$langs->trans("ClientSortingCharset").'</td>';
        	print '<td align="right">'.$tmparray->collation.'</td></tr>';
        	dolibarr_install_syslog("upgrade: " . $langs->transnoentities("ClientCollation") . ": " .$tmparray->collation);
        }
```

**Comment by klikict** [comment]
if ($db->type == 'mysqli')
        {
        	$tmparray = $db->db->get_charset();
        	print '<tr><td>'.$langs->trans("ClientCharset").'</td>';
        	print '<td align="right">'.$tmparray->charset.'</td></tr>';
        	dolibarr_install_syslog("upgrade: " . $langs->transnoentities("ClientCharset") . ": " .$tmparray->charset);
        	print '<tr><td>'.$langs->trans("ClientSortingCharset").'</td>';
        	print '<td align="right">'.$tmparray->collation.'</td></tr>';
        	dolibarr_install_syslog("upgrade: " . $langs->transnoentities("ClientCollation") . ": " .$tmparray->collation);
        }

**Comment by hregis** [comment]
@klikict 
what is your php version ?

**Comment by klikict** [comment]
I've set the aa folder to php 7.0.29

**Comment by hregis** [comment]
@klikict 
you can try with 5.6.x or 7.1.x ?

**Comment by klikict** [comment]
Tried both version as well.. same outcome :|

**Comment by hregis** [comment]
@klikict 

comments lines : 

```
/*if ($db->type == 'mysqli')
{
    	$tmparray = $db->db->get_charset();
    	print '<tr><td>'.$langs->trans("ClientCharset").'</td>';
    	print '<td align="right">'.$tmparray->charset.'</td></tr>';
    	dolibarr_install_syslog("upgrade: " . $langs->transnoentities("ClientCharset") . ": " .$tmparray->charset);
    	print '<tr><td>'.$langs->trans("ClientSortingCharset").'</td>';
    	print '<td align="right">'.$tmparray->collation.'</td></tr>';
    	dolibarr_install_syslog("upgrade: " . $langs->transnoentities("ClientCollation") . ": " .$tmparray->collation);
}*/
```

**Comment by klikict** [comment]
Thanks that fixed it for me!
