### ISSUE TITLE
Bug: API Payment crash with Block log enabled

### ISSUE THREAD

**Issue by corentin59** [Dolibarr/dolibarr#8529]
# Bug
When calling the API: "/invoices /{id}/payments" in HTTP POST method, an error occurs. This seems to happen only with the blocked log mode. Can not reproduce the problem in normal mode (not blocked log).

## Environment
- **Version**: 7.0.0
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 5.6.33
- **Database**: MariaDB
- **URL(s)**: API /invoices /{id}/payments (POST)

## Expected and actual behavior
API respond an invalid HTTP status code, see in screenshot for more informations.

## Steps to reproduce the behavior
- Active API Rest module
- Create a API key
- Create invoice with a generated number
- Call the URI : /invoices /{invoiceID}/payments (POST), with the following payload :
`{
  "datepaye": "888888888888888",
  "closepaidinvoices": "no",
  "accountid": "1",
  "paiementid": "6",
  "comment": "Commentaire",
"amount":33.22
}`

(I think than payload is invalid, but in no blocked log mode, this payload add a payment with the amount of the invoice, If you know the good payload, please say it here :))

## [Attached files]
![dolibarr-error](https://user-images.githubusercontent.com/2035983/38522561-428ac9fe-3c49-11e8-9827-2e4ce08757f9.png)

**Comment by atm-arnaud** [comment]
@atm-maxime issue to close thanks to @hregis again

**Comment by corentin59** [comment]
Thx a lot @hregis ! Have you a JSON payload sample to perform a payment ?
