### ISSUE TITLE
bug remise de chèque

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#8559]
Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20180411092704
Dolibarr: 7.0.1
Niveau de fonctionnalités: 0
PHP: 7.0.27-0+deb9u1
Server: Apache/2.4.25 (Debian)
OS: Linux vps452769 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Url sollicitée: /compta/paiement/cheque/index.php?leftmenu=checks&mainmenu=bank
Referer: http://dolibarr.bouddhismes.net/compta/bank/list.php?mainmenu=bank&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT bc.rowid, bc.date_bordereau as db, bc.amount, bc.ref as ref, bc.statut, bc.nbcheque, ba.ref, ba.label, ba.rowid as bid, ba.number, ba.currency_code, ba.account_number, ba.accountancy_journal, aj.code FROM llx_bordereau_cheque as bc, llx_bank_account as ba LEFT JOIN llx_accounting_journal as aj ON aj.rowid = ba.fk_accountancy_journal WHERE ba.rowid = bc.fk_bank_account AND bc.entity = 1 ORDER BY bc.date_bordereau DESC, rowid DESC LIMIT 10
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'ba.accountancy_journal' in 'field list'

**Comment by eldy** [comment]
Fix will be available with 7.0.2
