### ISSUE TITLE
Dolibarr LDAP don't sync the password.

### ISSUE THREAD

**Issue by forgedata** [Dolibarr/dolibarr#8573]
Bug
Buongriono,
Quando configuro Dolibarr 7 con il modulo LDAP agganciangolo a Zentyal Linux 5 riesco a pescare gli utenti dal server ma non mi sincronizza le password.

Cosa devo fare? 

Environment
- Dolibarr 7.0.1
- Ubuntu 16.04 LTS amd64
- Apache 2.4
- PHP 7.0,7.1,7.2
- MySQL 5.9

**Comment by hregis** [comment]
@forgedata 
can you speak english please.
If you use the sync ldap -> dolibarr the passwords are not recovered in dolibarr, it is necessary to set dolibarr so that the verification of the password is done on ldap.

**Comment by forgedata** [comment]
Excuse me, how do I set up password verification in dolibarr?

**Comment by hregis** [comment]
@forgedata 
in conf.php, see conf.php.sample file

**Comment by forgedata** [comment]
In dolibarr 7.01 non c'è il file conf.php.
Nella cartella conf ci sono solo i file conf.php.pgsql e conf.php.example.

Ho provato a creare il file conf.php impostando tutto ma non cambia nulla.

**Comment by hregis** [comment]
@forgedata 
the file "conf.php" is created automatically during the first installation of dolibarr !!
then modify it according to your needs...
