### ISSUE TITLE
Alerta retraso de pedidos

### ISSUE THREAD

**Issue by carocristal** [Dolibarr/dolibarr#8578]
Hola gente..
Acabo de instalar Dolibarr 4.0.0 para ya implementarlo definitivamente en mi empresa.
y me llevo con la sorpresa que apenas creo un pedido, me figura con retraso. 
retraso.PNG
Apenas se crea el pedido entra como retrasado.
retraso.PNG (21.07 KiB) Visto 676 veces

No se si es un BUG o estoy configurando algo mal.
porque las fechas de creacion y de entrega están bien.
fecha.PNG
Fue generado con la fecha de hoy y con fecha de entrega en 5 dias.
fecha.PNG (20.26 KiB) Visto 676 veces

Incluso modifique entre en Configuracion -> Alertas, le puse todo 30 días y me sigue apareciendo retraso.

No comprendo que sucede
Saludos,
Carola

**Comment by carocristal** [comment]
Estimad@s, 
Me sugirieron plantear acá mi problema, pero no he sido escuchada.
Al menos esperaba que me dijeran, ey.. no podemos ayudar.

Gracias de todas formas.
Carola #

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
