### ISSUE TITLE
POS don't use the price level

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#8584]
# Bug
When we use the price levels in the POS (cashdesk), we get a correct price but the total is zero. POS seems to use the last price level filled.

## Environment
- **Version**: 7.0.1

Problem already reported on the french forum : https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/61023-bug-sur-le-point-de-vente-avec-differents-niveaux#92926

**Comment by RegEx20170606** [comment]
yes same problem , also don't check the qty in stock 😕

**Comment by simnandez** [comment]
It works fine with 7.0.4
