### ISSUE TITLE
Bug: Merge Thirdparty - Can't input letter in popup windows to find Thirdparty need to delete

### ISSUE THREAD

**Issue by dolivn** [Dolibarr/dolibarr#8585]
# Bug
Merge Thirdparty: 
- Can not input letters in pop-up windows for finding the thirdparty need to delete.

## Environment
- Checked on 7.0.0 & 7.0.1 (web base)

## Expected and actual behavior
- This function is very important, please help fix this bug.

**Comment by hregis** [comment]
@webteam247 
i can't reproduce your problem, do you have plugins that could create conflicts?

**Comment by dolivn** [comment]
@hregis
We tried to fix it, but we can not.

I checked by installation a fresh new dolibarr 7.0.1 too, without any plugin. No conflicts I think

**Comment by hregis** [comment]
@webteam247 
try with futur 7.0.2
https://github.com/Dolibarr/dolibarr/archive/7.0.zip

**Comment by dolivn** [comment]
@hregis 
Thank you.

We just tried upgrade to 7.0.2.
This bug is still there. Hope you can find where should fix.

We tried fix some weeks ago. But we can not find core reason make this conflicts

**Comment by hregis** [comment]
@webteam247 
it's difficult to fix a "bug" if we do not have this bug! :-) can you contact me by email to do a telemainteance to see what happens? regis dot houssin at gmail dot com

**Comment by hregis** [comment]
@webteam247 
i found a solution : https://github.com/Dolibarr/dolibarr/pull/8591
