### ISSUE TITLE
BUG: ODT {object_options_xxx} Link to an object

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#8592]
# Bug
Strange behaviour if a complementary attribute is linked to an object. I've done my tests on 8.0.0-alpha but I think it exists in other versions as well. Also reported on Dolibarr forum [https://www.dolibarr.org/forum/12-howto-help/27784-problem-with-object-options-xxx-in-odt-template](url)

## Environment
- **Version**: 8.0.0-alpha
- **OS**: Linux server.turro24.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.35
- **Database**: MySQL or MariaDB 5.5.5-10.2.13-MariaDB
- **URL(s)**: /htdocs/compta/facture/card.php

## Expected and actual behavior
**Expected behaviour** to display linked file reference properly on ODT files.
**Actual behaviour** instead of proper linked file reference e.g. "PR1605-0002" the ODT file displays just "2" or instead of "(PROV52)" it displays only "52"

## Steps to reproduce the behavior
In Invoice Module create a complementary attribute that is linked to an object then create an invoice and choose the object for the complementary attribute from a dropdown list.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
<img width="1458" alt="screen shot 2018-04-14 at 00 44 59" src="https://user-images.githubusercontent.com/28427270/38762037-a4e31f0a-3f7f-11e8-9355-e1fbf53ffb77.png">
<img width="988" alt="screen shot 2018-04-14 at 00 37 36" src="https://user-images.githubusercontent.com/28427270/38762035-a4ae6030-3f7f-11e8-9c01-9afaa8f37d38.png">
<img width="734" alt="screen shot 2018-04-14 at 00 44 33" src="https://user-images.githubusercontent.com/28427270/38762036-a4c66ee6-3f7f-11e8-95be-be90c6843369.png">
<img width="1032" alt="screen shot 2018-04-14 at 00 37 15" src="https://user-images.githubusercontent.com/28427270/38762034-a492980a-3f7f-11e8-91c9-9d7a539cdf24.png">
<img width="741" alt="screen shot 2018-04-14 at 00 56 31" src="https://user-images.githubusercontent.com/28427270/38762038-a4fef176-3f7f-11e8-8aaf-a0a13c2c33db.png">
<img width="1060" alt="screen shot 2018-04-14 at 00 57 06" src="https://user-images.githubusercontent.com/28427270/38762039-a518e7a2-3f7f-11e8-841f-a7635e417107.png">

**Comment by CoCoRiCo** [comment]
Yes, it seems that this problem continues until version 19.0.1. 
 It is a situation that greatly affects functionality and document designs. 
 For example: it does not allow creating conditions based on the option in the object option.  PHP/PDF templates bring a lot of coding and preview problems, and the flexibility of the cells according to languages ​​is not successful. 
 For this reason, this BUG should be resolved as a priority.
