### ISSUE TITLE
Add reminder features (browser popup or email) for agenda events

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#8613]
Add reminder features (browser popup or email) for agenda events

**Comment by dolibarr95** [comment]
Hi !
I've created a simple module with notification (late orders, stock alerts...)
Using https://caniuse.com/#search=notification could be nice.
Very simple to create/use

```javascript
var titre = ref;
var options = {body: corps,icon: icon ,requireInteraction: true,tag : tag};
var n = new Notification(titre,options);
  
//à l'ouverture
	n.onshow = function () { 
		//vibrate or what we want
	}
	
	//à la fermeture
    n.onclose = function () { 
	
//ajax query to set this notfication as  read

	}

/*
With a set time out function that can be adjusted
*/
```

The advantage of notifications over popups are :

- No intrusive
- No addblock
- Evenif the explorer is inactive the notification take the focus
- Works very well on mobile tablets...
- etc

Tks

**Comment by ghost** [comment]
Is it already do (for Email side) by dolibarr scedule task ActionComm->sendEmailsReminder setup in 8.0 ?

**Comment by eldy** [comment]
The script sendEmailsReminder was started but not finished.
We must modify the actioncomm/card.php file to be able to edit the date when we want the remind

The table where remind requests are stored is actioncomm_reminder (already exiting 8.0)

**Comment by novusfederico** [comment]
Someone have set the email reminder for agendo into Dolibarr 9.0.1?

I have set it but not works.

**Comment by MyBlissIT** [comment]
Hi, is this still in use? I would really like to have this feature on my Dolibarr

**Comment by MyBlissIT** [comment]
> Hi !
> I've created a simple module with notification (late orders, stock alerts...)
> Using https://caniuse.com/#search=notification could be nice.
> Very simple to create/use
> 
> ```js
> var titre = ref;
> var options = {body: corps,icon: icon ,requireInteraction: true,tag : tag};
> var n = new Notification(titre,options);
>   
> //à l'ouverture
> 	n.onshow = function () { 
> 		//vibrate or what we want
> 	}
> 	
> 	//à la fermeture
>     n.onclose = function () { 
> 	
> //ajax query to set this notfication as  read
> 
> 	}
> 
> /*
> With a set time out function that can be adjusted
> */
> ```
> 
> The advantage of notifications over popups are :
> 
> * No intrusive
> * No addblock
> * Evenif the explorer is inactive the notification take the focus
> * Works very well on mobile tablets...
> * etc
> 
> Tks

Hi @dolibarr95 can I use this on the latest Dolibarr installation and where exactly to insert this code? I am using English South Africa

**Comment by dolibarr95** [comment]
Hello
You have to create a module and create the php/javascript functions
