### ISSUE TITLE
Replace multiple $langs->load with $langs->loadLangs(array('aaa', 'bbb'...))

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#8615]
Replace multiple $langs->load with $langs->loadLangs(array('aaa', 'bbb'...));

So 
$langs->load('aaa');
$langs->load('bbb');
...
Become 
$langs->loadLangs(array('aaa', 'bbb'...));

**Comment by cherianmpaul** [comment]
Hi @eldy ,

I am new here... I thought I can take this as my first issue.
I found this issue on the below files... Can I go ahead and fix all of the below listed files?  Please let me know.

..\htdocs\comm\propal\stats\index.php
Line 68: $langs->load('propal');
Line 69: $langs->load('other');
Line 70: $langs->load("companies");

..\htdocs\fourn\facture\contact.php
Line 37: $langs->load("bills");
Line 38: $langs->load('other');
Line 39: $langs->load("companies");

...\htdocs\fourn\facture\document.php
Line 41: $langs->load('bills');
Line 42: $langs->load('other');
Line 43: $langs->load("companies");

...\htdocs\fourn\facture\impayees.php
Line 36: $langs->load("companies");
Line 37: $langs->load("bills");

...\htdocs\fourn\facture\info.php
Line 37: $langs->load('companies');
Line 38: $langs->load('bills');

...\htdocs\fourn\facture\note.php
Line 36: $langs->load('bills');
Line 37: $langs->load("companies");

...\htdocs\fourn\facture\paiement.php
Line 41: $langs->load('companies');
Line 42: $langs->load('bills');
Line 43: $langs->load('banks');
Line 44: $langs->load('compta');

...\htdocs\fourn\index.php
Line 31: $langs->load("suppliers");
Line 32: $langs->load("orders");
Line 33: $langs->load("companies");

...\htdocs\fourn\paiement\card.php
Line 35: $langs->load('bills');
Line 36: $langs->load('banks');
Line 37: $langs->load('companies');
Line 38: $langs->load("suppliers");

...\htdocs\fourn\paiement\info.php
Line 31: $langs->load("bills");
Line 32: $langs->load("suppliers");
Line 33: $langs->load("companies");

...\htdocs\ftp\admin\ftpclient.php
Line 28: $langs->load("admin");
Line 29: $langs->load("ftp");

...\htdocs\install\inc.php
Line 381: $langs->load("main");
Line 382: $langs->load("admin");
Line 383: $langs->load("install");
Line 458: $langs->load("main");
Line 459: $langs->load("other");
Line 460: $langs->load("admin");

...\htdocs\install\step1.php
Line 39: $langs->load("admin");
Line 40: $langs->load("install");
Line 41: $langs->load("errors");

...\htdocs\install\step2.php
Line 49: $langs->load("admin");
Line 50: $langs->load("install");

...\htdocs\install\step4.php
Line 38: $langs->load("admin");
Line 39: $langs->load("install");

...\htdocs\install\step5.php
Line 55: $langs->load("admin");
Line 56: $langs->load("install");

...\htdocs\install\upgrade.php
Line 69: $langs->load("admin");
Line 70: $langs->load("install");
Line 71: $langs->load("other");
Line 72: $langs->load("errors");

...\htdocs\install\upgrade2.php
Line 76: $langs->load('admin');
Line 77: $langs->load('install');
Line 78: $langs->load("bills");
Line 79: $langs->load("suppliers");

...\htdocs\margin\admin\margin.php
Line 32: $langs->load("admin");
Line 33: $langs->load("bills");
Line 34: $langs->load("margins");
Line 35: $langs->load("stocks");

...\htdocs\margin\tabs\productMargins.php
Line 29: $langs->load("companies");
Line 30: $langs->load("bills");
Line 31: $langs->load("products");
Line 32: $langs->load("margins");

...\htdocs\margin\tabs\thirdpartyMargins.php
Line 29: $langs->load("companies");
Line 30: $langs->load("bills");
Line 31: $langs->load("products");
Line 32: $langs->load("margins");

...\htdocs\projet\element.php
Line 551: $langs->load("suppliers");
Line 552: $langs->load("bills");
Line 553: $langs->load("orders");
Line 554: $langs->load("proposals");
Line 555: $langs->load("margins");

...\htdocs\public\agenda\agendaexport.php
Line 133: $langs->load("main");
Line 134: $langs->load("errors");

...\htdocs\public\cron\cron_run_jobs.php
Line 47: $langs->load("admin");
Line 48: $langs->load("cron");

...\htdocs\public\demo\index.php
Line 33: $langs->load("main");
Line 34: $langs->load("install");
Line 35: $langs->load("other");

...\htdocs\public\emailing\mailing-unsubscribe.php
Line 56: $langs->load("main");
Line 57: $langs->load("mails");

...\htdocs\public\members\public_card.php
Line 46: $langs->load("main");
Line 47: $langs->load("members");
Line 48: $langs->load("companies");
Line 49: $langs->load("other");

...\htdocs\public\members\public_list.php
Line 43: $langs->load("main");
Line 44: $langs->load("members");
Line 45: $langs->load("companies");
Line 46: $langs->load("other");

...\htdocs\public\notice.php
Line 44: $langs->load("error");
Line 45: $langs->load("other");

...\htdocs\public\onlinesign\newonlinesign.php
Line 47: $langs->load("main");
Line 48: $langs->load("other");
Line 49: $langs->load("dict");
Line 50: $langs->load("bills");
Line 51: $langs->load("companies");
Line 52: $langs->load("errors");
Line 53: $langs->load("paybox");     // File with generic data

...\htdocs\public\paybox\paymentko.php
Line 42: $langs->load("main");
Line 43: $langs->load("other");
Line 44: $langs->load("dict");
Line 45: $langs->load("bills");
Line 46: $langs->load("companies");
Line 47: $langs->load("paybox");
Line 48: $langs->load("paypal");
Line 49: $langs->load("stripe");

...\htdocs\public\paybox\paymentok.php
Line 42: $langs->load("main");
Line 43: $langs->load("other");
Line 44: $langs->load("dict");
Line 45: $langs->load("bills");
Line 46: $langs->load("companies");
Line 47: $langs->load("paybox");
Line 48: $langs->load("paypal");
Line 49: $langs->load("stripe");

...\htdocs\public\payment\paymentko.php
Line 47: $langs->load("main");
Line 48: $langs->load("other");
Line 49: $langs->load("dict");
Line 50: $langs->load("bills");
Line 51: $langs->load("companies");
Line 52: $langs->load("paybox");
Line 53: $langs->load("paypal");
Line 54: $langs->load("stripe");

...\htdocs\public\paypal\paymentko.php
Line 46: $langs->load("main");
Line 47: $langs->load("other");
Line 48: $langs->load("dict");
Line 49: $langs->load("bills");
Line 50: $langs->load("companies");
Line 51: $langs->load("paybox");
Line 52: $langs->load("paypal");
Line 53: $langs->load("stripe");

...\htdocs\public\stripe\paymentko.php
Line 39: $langs->load("main");
Line 40: $langs->load("other");
Line 41: $langs->load("dict");
Line 42: $langs->load("bills");
Line 43: $langs->load("companies");
Line 44: $langs->load("paybox");
Line 45: $langs->load("paypal");
Line 46: $langs->load("stripe");

...\htdocs\public\stripe\paymentok.php
Line 39: $langs->load("main");
Line 40: $langs->load("other");
Line 41: $langs->load("dict");
Line 42: $langs->load("bills");
Line 43: $langs->load("companies");
Line 44: $langs->load("paybox");
Line 45: $langs->load("paypal");

...\htdocs\societe\admin\contact_extrafields.php
Line 31: $langs->load("companies");
Line 32: $langs->load("admin");

...\htdocs\societe\admin\societe.php
Line 31: $langs->load("companies");
Line 32: $langs->load("admin");

...\htdocs\societe\admin\societe_extrafields.php
Line 31: $langs->load("companies");
Line 32: $langs->load("admin");
Line 33: $langs->load("members");

...\htdocs\societe\document.php
Line 35: $langs->load("companies");
Line 36: $langs->load('other');

...\htdocs\societe\notify\card.php
Line 33: $langs->load("companies");
Line 34: $langs->load("mails");
Line 35: $langs->load("admin");
Line 36: $langs->load("other");
Line 316: $langs->load("errors");
Line 317: $langs->load("other");

...\htdocs\societe\notify\index.php
Line 26: $langs->load("companies");
Line 27: $langs->load("banks");

...\htdocs\societe\price.php
Line 41: $langs->load("products");
Line 42: $langs->load("companies");
Line 43: $langs->load("bills");

...\htdocs\societe\project.php
Line 34: $langs->load("companies");
Line 35: $langs->load("projects");

...\htdocs\societe\societecontact.php
Line 35: $langs->load("orders");
Line 36: $langs->load("companies");

...\htdocs\stripe\lib\stripe.lib.php
Line 67: $langs->load("paypal");
Line 68: $langs->load("paybox");
Line 69: $langs->load("stripe");

...\htdocs\support\inc.php
Line 208: $langs->load("main");
Line 209: $langs->load("admin");
Line 247: $langs->load("main");
Line 248: $langs->load("admin");

...\htdocs\support\index.php
Line 37: $langs->load("other");
Line 38: $langs->load("help");

...\htdocs\support\online.php
Line 33: $langs->load("other");
Line 34: $langs->load("help");

...\htdocs\user\notify\card.php
Line 290: $langs->load("errors");
Line 291: $langs->load("other");

...\htdocs\variants\combinations.php
Line 28: $langs->load("products");
Line 29: $langs->load("other");

...\htdocs\variants\generator.php
Line 27: $langs->load("products");
Line 28: $langs->load('other');

Thanks,
Cherian.
