### ISSUE TITLE
Fatal Error: Commandes facturables Dolibarr 7.0.0 

### ISSUE THREAD

**Issue by highalgo** [Dolibarr/dolibarr#8618]
# Bug
Bug au niveau de la fonctionnalité commandes facturables, si on sélectionne une ou plusieurs commandes à facturer avec l'option Valider les factures = Oui on obtient l'erreur suivante:

Fatal error: Uncaught Error: Call to a member function fetch() on null in /var/www/html/TEST_TIFPRINT/htdocs/core/actions_builddoc.inc.php:45 Stack trace: #0 /var/www/html/TEST_TIFPRINT/htdocs/core/actions_massactions.inc.php(679): include() #1 /var/www/html/TEST_TIFPRINT/htdocs/commande/list.php(211): include('/var/www/html/T...') #2 {main} thrown in /var/www/html/TEST_TIFPRINT/htdocs/core/actions_builddoc.inc.php on line 44

## Environment
- **Version**: Dolibarr 7.0.0
- **OS**: ANY
- **Web server**: ANY
- **PHP**: ANY
- **Database**: MySQL 
- **URL(s)**: htdocs/core/actions_builddoc.inc.php

## Use case

Le fichier htdocs/core/actions_massactions.inc.php inclut le fichier htdocs/core/actions_builddoc.inc.php à la ligne 679.
Le fichier htdocs/core/actions_builddoc.inc.php  accède à  une variable $object non instanciée, la variable $object  est appelée $objecttmp  dans le fichier htdocs/core/actions_massactions.inc.php.

## Suggested steps
Ajouter dans le fichier htdocs/core/actions_builddoc.inc.php à la ligne 44 l'instruction $object=$objecttmp;  ou renommer $object  en $objecttmp.

**Comment by highalgo** [comment]
Bonjour,

Qu'elle est la politique de correction des bugs? est ce-qu'il y'a que eldy qui corrige les bugs?

Une erreur fatal de ce genre bloque carrément l'utilisation d'une fonctionnalité.

J'ai mentionné deux erreurs fatal ainsi que les solutions sur le forum et sur github mais malheureusement sans aucune réaction.

Cordialement.

**Comment by atm-maxime** [comment]
Hi.
Thanks for your contributions. I just tested this in 7.0.6 and it works fine. So I guess your issue has been fixed.
The development community deals with issues they spot and the ones on github but there's no "fixing policy" as the way the community works is based on volunteering.

Please keep the communication in english on github.
Thanks again for your feedbacks.
