### ISSUE TITLE
 Feature Request: Enable tags/categories for attributes in the product variants module and in the product complementary attributes

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#8630]
# Feature Request
Enable tags/categories for attributes in the product variants module and in the product complementary attributes of the module products

## Use case
Is difficult to manage the products with a lot of technical attributes, some products have around 50 attributes, some of them generating variants, and another ones only are only the technical specifications of the product. The use of tags/categories to group hierarchically the variant and complementary product attributes will help a lot to manage it.
 Example of tags/categories for attributes with smartphones products:
- Phisical attributes
     Lenght
     Widh
     Thickness
     Weight
- Environment attributes
     working temperture range
     storage temperture range
- Electronic attributes
     Ram memory
     Storage capacity
     Chipset
     CPU-frecuency
- Screen atributes
     type of screen
     angle of vision
     max brightness
... etc...
The use of tags/categories will permit to filter, and organize the technical specifications of the products

Additionally maybe that complementary attributes and variant attributes could be merged, and allow in any product attribute the possibility to be selected to allow to generate a variant or not.

## Suggested implementation
Add to the module tags/categories the feature to create tags/categories also in product/variants module that now is only available for products, customers, suppliers, contacts or members.

## Suggested steps
- Add to the module tags/categories the feature to create tags/categories also in product/variants module
- Add in product/variant module the field "generate variant" or "not generate variant"
- Add in the module products the feature to use tags/categories in the product complementary attributes

## Additional note: 
Maybe a better idea to integrate the module product/variant in the module products, and add to the complementary attributes the feature to generate or not a variant ("is_variant" property yes/no) and use tags/categories for this attributes, and then is not needed the module product-variants. Not sure. 
I mentioned this in the already merged feature request number #5533  commented on[ Jan 22 ](https://github.com/Dolibarr/dolibarr/pull/5533#issuecomment-359261943)(after the merge was performed) The use of multidimensional variants then could be implemented with the help of "tags/categories" aproach

**Comment by Eromera** [comment]
Totally agree, any update on this?
