### ISSUE TITLE
Feature Request: Allow to use in shipment card a third party as a shipping method 

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#8634]
# Feature Request
Allow to use in shipments card a third party as a shipping method and no only a value of the Shipping methods dictionary table llxzn_c_shipment_mode table

## Use case
A forwarder is a supplier third party supplying the shipping service and need a supplier card to be able to register the contact data, company name, etc.
No always the own company is in charge to perform the delivery, and is the customer or supplier who send the forwarder to pickup the goods.

## Suggested implementation
- In the field "shipping method" of the shipment card allow to use the method "third party" additionally to the existing codes of the dictionary table llxzn_c_shipment_mode. 
- The combo box of the field shipping method of the shipment card should have after the first blank item value the item value "third party", then if third party is selected a second combo box should allow to select the third party displaying a list that can be filtered by tags/categories (allows to have the category forwarders with the suppliers of delivering services)
- In the shipment card add a checkbox field "charged/managed to  our own company", to determine if is our own company who will be charged for the delivery, or if is the consignee customer/supplier/prospect who will pickup the goods and will be charged directly for the delivery service.

(NOTE: Next step will be add the default shipment methods to the 3th party card, to have the shipment methods of the customers/suppliers/prospects conveniently stored in the third party card)

**Comment by edupulpillo** [comment]
Still is a interesting feature

**Comment by atm-maxime** [comment]
You need to reopen your issue if you still want people to see it.

**Comment by edupulpillo** [comment]
Thanks atm-maxime, but i do not find the option to be able to reopen it

**Comment by edupulpillo** [comment]
Thanks for opening it.
We think still is a great feature: linking the shiping method to a third party, we can use several forwarders or couriers .

**Comment by edupulpillo** [comment]
No interest in this feature?

**Comment by edupulpillo** [comment]
@atm-maxime can you re-open it ?

**Comment by atm-maxime** [comment]
I suggest you try and use the "contact" tab to define the "carrier" of the shipment. Here you can select a third-party and a contact.
When this third-party is selected, what use do you have for ? You need to print the carrier 'ame on the shipment PDF ?
