### ISSUE TITLE
[BUG] Cloning Invoice Supplier doesn't clone line extra fields value

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#8644]
Cloning a Supplier invoice, values of line extra fields aren't cloned. I think that code to cloning extra fields is missing, mainly is missing "fetching" of extrafields value

## Environment
- **Version**: 6.0.x and 7.0.x
- **OS**: Linux
- **Web server**: Apache
- **PHP**: PHP 7
- **Database**: Mysql

## Suggested implementation
As done into Facture class, it's sufficient to insert this code into createFromClone() method into class FactureFournisseur after line

`$this->db->begin();
`
```

// get extrafields so they will be cloned
foreach($this->lines as $line) 
{
  $line->fetch_optionals($line->rowid);
}

```

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
