### ISSUE TITLE
Bug: Template invoices do not store Localtax information

### ISSUE THREAD

**Issue by dom-breizh** [Dolibarr/dolibarr#8656]
# Bug
Template invoices do not store Localtax information

## Environment
- **Version**: 7.0.1
- **OS**: Ubuntu Server 16.0.4 LTS
- **Web server**: Apache2.4
- **PHP**: 7.0
- **Database**: MySQL 5.7
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Expected: When creating a template for customers where LocalTax2 is being used, the LocalTax2 percentage and amount should be saved. 
Actual: When creating a template for customers where LocalTax2 is being used, the LocalTax2 percentage and amount are not saved rendering the template useless.

## Steps to reproduce the behavior
Using Spain as reference country, and customer with IRPF (LocalTax2), create a new invoice template. Check the new created template. Localtax2 is not stored.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
Invoice Creation: Product selection with the right VAT and LocalTax2
![bf074a16-5fca-4343-95bc-c899dc52f062](https://user-images.githubusercontent.com/5640062/39064143-acafe896-44cd-11e8-9237-e8b57c591450.png)
Invoice Creation: VAT and LocalTax2 Summary
![e538334c-4f2a-4f31-a34c-2ffa0f2072c2](https://user-images.githubusercontent.com/5640062/39064177-d85ce41c-44cd-11e8-9109-661a7f67e6e0.png)
Invoice Template
![af4dafff-91b6-4973-a406-c891c5e3c8a6](https://user-images.githubusercontent.com/5640062/39064199-e863120a-44cd-11e8-8194-838f5a4eed99.png)

**Comment by dom-breizh** [comment]
Just updated to 8.0.2 and still an issue.
Untill this is fixed the template funcionnality is not usefull for self employed in Spain, probably other countries as well
Can someone please look at a possible fix. I am willing to fund for a permanent fix in Dolibarr.

**Comment by dom-breizh** [comment]
Version 9.0.2 Still not fixed.

**Comment by dom-breizh** [comment]
Jumping to version 11.0.1 and still not working.

**Comment by ksar-ksar** [comment]
Have you tested in V13 ?

**Comment by dom-breizh** [comment]
Can say for 13... But still not working on 12.
