### ISSUE TITLE
Feature Request: Can choose no-required fields in some modules

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#8661]
Add in the admin of each module the choice of fields that must be required and those that are not.
Or have a model of conf to apply everywhere:
if (... && ! empty ($conf->global->MODULENAME_NOREQUIRED_FIELDS_NAMEOFFIELD))

If a user wants to force a required field to no longer be it must add it in the global parameters of the dolibarr configuration.

**Comment by wdammak** [comment]
I don't understand for example why when you activate the barcode module the field becomes required and blocks the product updates knowing a product can be without barcode.

**Comment by ias-ceo** [comment]
to make it generic, feature need to have an option to hide fields, or make it mandatory/un-mandatory.

in-fact, this will be better handled if the permission, access control, become on field based not transaction base. means the admin can, enable/disable field based on add/view only ,or, show/hide option, or mandatory/un-mandatory option.
