### ISSUE TITLE
Bug [TicketSup] Can not enable the module

### ISSUE THREAD

**Issue by nubo-solutions** [Dolibarr/dolibarr#8670]
# Bug
Ticket Sup module is not present in modules list. Can not enable it.

## Environment
- **Version**: 8.0.0-alpha
- **OS**: Win x64
- **Web server**: Wamp 3.1.3 x64 Apache 2.4.33
- **PHP**: PHP 5.6.35
- **Database**: MySQL 5.7.21
- **URL(s)**: /htdocs/admin/modules.php?mainmenu=home

## Expected and actual behavior
Ticketsup module is present in dolibarr8 folder but it is not visible from administrator

## Steps to reproduce the behavior
Make a new install, and try to enable ticket module.

**Comment by ptibogxiv** [comment]
Il faut mettre la constante feature level à 2 pour le voir en. Alpha.

**Comment by madmath03** [comment]
I encountered the same behavior with Dolibarr 8.0.2

@ptibogxiv could you be more specific regarding the constant you mention ? Where is it stored ?

**Comment by futurehousestore** [comment]
Tha is not a bug. TicketSup module is an Experimental module therefore to activate it you need to set number 2 in MAIN_FEATURES_LEVEL (other setup)

**Comment by librethic-code** [comment]
External module **«TicketSup »** had been forked (April 2018) into the core (v8) and renamed by **« Ticket »**: Both module can coexist on the same installation but cannot be activated at the same time.

**« TicketSup »** module is still maintained as an external module (see https://code.librethic.io/Dolibarr/modules/ticketsup) and contains features that hadn't been implemented yet by Dolibarr community.

**Comment by inoveaconseil** [comment]
TicketSup is an external module and ticket is an experimental module
