### ISSUE TITLE
Implicit limit of 100 records in REST API response

### ISSUE THREAD

**Issue by MatthieuTexier** [Dolibarr/dolibarr#8681]
# Bug
The REST API is returning a maximum of 100 records when no limit is set in query

## Environment
- **Version**: 7.0.0
- **OS**: Linux
- **Web server**: Apache 2.4.10
- **PHP**: 5.6
- **Database**: MariaDB 5.5.59

## Expected and actual behavior
When no limit parameter is set, we should get the complete record set.

## Steps to reproduce the behavior
make any request on contacts or thirdparties having more than 100 entries, for examples
curl -X GET --header 'Accept: application/json' --header 'DOLAPIKEY: xxxxxxxxx' 'http://server/api/index.php/thirdparties'

**Comment by Productivix** [comment]
BONJOUR ,  and what was the solution please to get more than 100 records ?

**Comment by Productivix** [comment]
la réponse est : mettre à la fin de la requête :
&limit=0
