### ISSUE TITLE
Expense report approval timestamp is set for 2 hours in the future

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#8685]
## Environment
- **Version**: 6.0.4

## Expected and actual behavior
When approving an expense report, the timestamp is set to 2 hours in the future. Also, if the report was previously denied, the timestamp and the reason for the denial is left remain.

Expected behaviour for approval is that the timestamp is correct, and that a previously denied request is cleared.

See the screendump. The deny was made 15:34, and the approval was made at 15:35. The deny remains, and the approval timestamp is at 17:35.

[*Files*]
![db_expense_bug](https://user-images.githubusercontent.com/11036018/39309331-019d110a-4968-11e8-8419-9e6d24ba7b91.png)

**Comment by atm-maxime** [comment]
Fixed in 7.0
![image](https://user-images.githubusercontent.com/2097773/57973050-e844da00-79a2-11e9-8ca7-656456479046.png)
