### ISSUE TITLE
BUG: Unable to find a refused proposal, the proposal record can not be found if clicked, but is listed

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#8688]
# Bug
[*BUG: Unable to find a refused proposal, the proposal record can not be found if clicked, but is listed*]

## Environment
- **Version**: [*7.0.2*]
- **OS**: [**]
- **Web server**: [*Apache 2.2.24*]
- **PHP**: [*5.3.29*]
- **Database**: [*Mysql 5.1.73-cll*]
- **URL(s)**: [*/comm/propal/list.php?leftmenu=propals*]

## Expected and actual behavior
[*in the /comm/propal/list.php?leftmenu=propals list, the line is present but missing the "status" field. Then when is selected the check box in this record, after  perform the bulk action "delete" and confirm,  the error message "Record Not Found" is displayed and the refussed proposal line still exist in the proposal list, but is not accesible.*]

**Comment by laudeco** [comment]
This is not a bug anymore in 8.0.3

Cheers
L.

**Comment by atm-maxime** [comment]
Can't reproduce in 7.0.6
