### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by awesome-rdash** [Dolibarr/dolibarr#8696]
# Bug
Url sollicitée: /dolibarr/htdocs/compta/paiement/cheque/index.php?leftmenu=checks&mainmenu=bank
Referer: http://127.0.0.1:8888/dolibarr/htdocs/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT bc.rowid, bc.date_bordereau as db, bc.amount, bc.ref as ref, bc.statut, bc.nbcheque, ba.ref, ba.label, ba.rowid as bid, ba.number, ba.currency_code, ba.account_number, ba.accountancy_journal, aj.code FROM llx_bordereau_cheque as bc, llx_bank_account as ba LEFT JOIN llx_accounting_journal as aj ON aj.rowid = ba.fk_accountancy_journal WHERE ba.rowid = bc.fk_bank_account AND bc.entity = 1 ORDER BY bc.date_bordereau DESC, rowid DESC LIMIT 10
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'ba.accountancy_journal' in 'field list'

## Environment
- **Version**: 7.0.1
- **OS**: Darwin
- **Web server**: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
- **PHP**: apache2handler 7.2.1
- **Database**: MySQL or MariaDB 5.6.38
- **URL**: /dolibarr/htdocs/compta/paiement/cheque/index.php?leftmenu=checks&mainmenu=bank

## Report
When I click on Remise de chèque

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
