### ISSUE TITLE
Bug: Invoice VAT rounded before total calculation

### ISSUE THREAD

**Issue by lampi87** [Dolibarr/dolibarr#8700]
# Bug
On an invoice the VAT is rounded and afterwards the total is calcuated. But VAT should be calcuated unrounded, total calculation should be done and rounded at the end.

## Environment
- **Version**: 7.0.1

## Steps to reproduce the behavior
Create an invoice with 3 products and 20% VAT, prices:
* 299,33€ without VAT
* 179,33€ without VAT
* 99,34€ without VAT

Expected VAT is 115,60€ but as VAT is rounded and total calcuated afterwards the result is 115,61€.

Any idea how to proceed?

**Comment by glu000** [comment]
I guess this can be fixed by changing Limits/Precision setup

What are your settings at Setup -> Limits and accuracy?

**Comment by mdeweerd** [comment]
On supplier invoices this can be selected with Mode1/Mode2 calculation.
For your own invoices, you can't set this on an individual basis - there may be a general option key for it.
At least in France, VAT can be calculated either way.
