### ISSUE TITLE
permissions issue in accounting module

### ISSUE THREAD

**Issue by katika** [Dolibarr/dolibarr#8706]
# Bug
*Permissions in accounting module are not effective*

## Environment
- **Version**: *7.0.1*
- **OS**: *Debian 9.1*
- **Web server**: *Apache 2.4.25*
- **PHP**: *PHP 7.0.19*
- **Database**: *Mariadb 10.1.23*

## Expected and actual behavior
**Expected**: *User with only permission "Read operations in Ledger" should only have read access to Ledger*
**Actual**: *User with only permission "Read operations in Ledger" can edit, modify and deleted items in Ledger*

## Steps to reproduce the behavior
*Go in "Permissions" for a given user,go  in Accounting Module, only select "Read operations in Ledger", log in with that user credentials, and verify*

**Comment by rdcongo** [comment]
You are right. and how it is even possible to modify an entry against a closed  invoice/operation?

**Comment by katika** [comment]
I really don't know...

**Comment by rdcongo** [comment]
I've posted this on the french Dolibarr forum.
looks like someone will come back to us asap.

**Comment by katika** [comment]
OK.Great.
