### ISSUE TITLE
BUG: Files attached to tasks that belongs to a project do not appears in the automatic tree in DMS/ECM

### ISSUE THREAD

**Issue by edupulpillo** [Dolibarr/dolibarr#8716]
# Bug
[*Files attached to tasks that belongs to a project do not appears in the automatic tree in DMS/ECM*]

## Environment
**Version**: [*7.0.3 to 11.0.1 all versions*]

## Expected and actual behavior
[*Actual behaviour: The files attached to tasks that belongs to a project do not appears in the automatic tree in DMS/ECM in projects automatic folder, only appear the files attached directly to the project card, but not teh files attached to the tasks card . This is because the automatic tree do not show the created folders for each project, then only the documents in the root folder of a project are displayed, and is not possible to access to the folders created for each project. 
Expected: A sub-tree in projects with folders with the name of the project, to see the documents attached for   each task. Inside tasks folders the files attached.

## Steps to reproduce the behavior
[*- Create a project and attach a file to the project card
 - Create a task inside the project and atach a file to the task card
 - Observe that only the file attached to the project appears, and that the one belonging to the task is missing in the automatic folder of the DMS/ECM *]

## Where to fix?
Maybe the source code needed to update to include the files attached to tasks in the ECM automatic tree is this one ?
https://github.com/Dolibarr/dolibarr/pull/773/commits/7881502b524b8e0178939e8fc07655733ab63d06

**Comment by alsoft10** [comment]
We are also looking for this functionality. Here is our suggestion. Inside **Documents**under the **Automatic Tree**, at the left side there will be directory called, **Tasks**. When user will click on this Tasks folder at the right hand side entire systems Tasks files should be shown. User can also search particular task file inside the Tasks directory.

**Comment by edupulpillo** [comment]
i agree with @alsoft10 Maybe the best solution as a first step, and easy to implement, since the prefix of the filenames of the files attached in the tasks, have also the name of the project that the task belongs. So a folder that contains all the files of all the tasks, maybe a nice and fast aproach.

**Comment by irefuse** [comment]
is there any update to this? bug has been open since 2018 with no resolution. if the files are attached to a task, you cannot even open the file from there either. Gives "Access denied" even on full administrator accounts.

![image](https://user-images.githubusercontent.com/2688319/138332278-40a1e6d0-adcb-45f5-a90b-c395814ed1fe.png)

**Comment by edupulpillo** [comment]
It seems still o progress in version 14.0.3, and the problem persist.
