### ISSUE TITLE
Bug: Unknown column 'fk_user_modif' in 'field list'

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#8723]
# Bug

## Environment
- **Version**: 6.0.5
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.7
- **Database**: MySQL 5.5.55
- **URL**: /fourn/paiement/card.php

## Report

When create a new note in a payment this error is shown, note is not saved:

**Unknown column 'fk_user_modif' in 'field list'**

**Comment by frederic34** [comment]
ALTER TABLE llx_paiementfourn ADD COLUMN fk_user_modif integer AFTER fk_user_author;

**Comment by PlanPc** [comment]
Thank you very much Frederic, I´ll test it

**Comment by NetLinkx** [comment]
Version: 7.0.2
Shared hosting 
URL: /fourn/paiement/card.php

Same error as reported in this thread on 6.0.5
