### ISSUE TITLE
Email template not set as default after udate to 7

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#8737]
# Bug
[*If I create a personal email template for order confirmation, invoice etc and I mark this as default the default system text is still selected and I need to manually apply my own template.*]

## Environment
- **Version**: [*7 and 7.0.1*]

**Comment by PlanPc** [comment]
Me too

**Comment by Bagu** [comment]
Here is a workaround. Set email template position to 0.

**Comment by GheeEasy** [comment]
Which? My own or the standard dolibarr

**Comment by Bagu** [comment]
Your own template.

Here is the result : 
![mailtemplate](https://user-images.githubusercontent.com/41675/40120935-a309c368-5920-11e8-962d-efaa9c4945f3.jpg)

**Comment by GheeEasy** [comment]
Thanks!
