### ISSUE TITLE
BUG: Invoice displays incorrect U.P. 

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#8739]
# Bug
The Unit Price is displayed incorrectly in Doliberr invoices not only on PDFs. U.P. on Dolibarr Invoice shows £0.45 and -75.93% discount but the actual U.P. should be £0.79. The order has been imported from Prestashop by CyberOffice and imported from eBay to Prestashop by Fastbay 1. The order is displayed correctly in Prestashop Invoice but incorrectly in Dolibarr. The selling prices in Dolibarr and Prestashop are the same but eBay prices include shipping cost, therefore, they are higher. 
I'm not sure if I should report it here or report it to eg. CyberOffice developer or maybe there is an easy fix for it somewhere in the settings? Please advice.

## Environment
- **Version**: 8.0.0-alpha
- **OS**: Linux server.turro24.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.36
- **Database**: MySQL or MariaDB 5.5.5-10.2.14-MariaDB
- **URL(s)**: /htdocs/compta/facture/card.php

## [Attached files]
![invoice](https://user-images.githubusercontent.com/28427270/39623661-48afca20-4f8e-11e8-9382-49bb06b2fd80.JPG)
![invoice2](https://user-images.githubusercontent.com/28427270/39623662-48cb0de4-4f8e-11e8-9489-ce7a5910f66c.JPG)

**Comment by simnandez** [comment]
This issue is on an alpha version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
