### ISSUE TITLE
Feature Request : Fusion PDF for Suppliers

### ISSUE THREAD

**Issue by manact** [Dolibarr/dolibarr#8773]
List suppliers by month : (eg) 11/2017
Fusion PDF is available for customers Invoices why "NOT" on suppliers?
This is requested by book holders.

**Comment by JonBendtsen** [comment]
seems to be implemented sometime between the original feature request and now

<img width="303" height="287" alt="Image" src="https://github.com/user-attachments/assets/7eb798cb-36a0-459d-8826-54dac6c1a0ae" />
