### ISSUE TITLE
[Bug] Changing Quotes / Proposal list sorting or order leads to 403 Forbidden error page

### ISSUE THREAD

**Issue by dvvita** [Dolibarr/dolibarr#8774]
# Bug
When trying to change list order by any column in the Quotes / Proposal listings an error page is displayed.

## Environment
- **Version**: Tested on versions 7.0 and 7.0.1
- **OS**: Linux
- **Web server**: VPS running Nginx
- **PHP**: 7.0.30
- **Database**: MySQL 5.5

## Expected and actual behavior
In the Quotes / Proposal listing, when clicking on the columns titles to change the sorting and order of the listing, the link will lead to a 403 Forbidden error page with this content:
```
Forbidden
You don't have permission to access /(install_root_dir)/comm/propal/list.php on this server.
```

This doesn't happen when repeating the same actions in other listings, like Billing for example.

I have noticed that the link contains &viewstatut= empty value:

`(install_root_dir)/comm/propal/list.php?sortfield=p.ref_client&sortorder=asc&begin=&viewstatut=&contextpage=proposallist&page_y=0`

When I removed it in the URL the behaviour is as expected.

## Steps to reproduce the behavior
- Click on Commercial section
- Click on Commercial proposals > List
- Click on any column title, for example the first one: Ref.
- Error is shown.

**Comment by azahraoui** [comment]
Hello,

I get also this error, this bug was signaled on 2018, any solution ?

Hello
