### ISSUE TITLE
7.0.2: mysql error on accountancy admin journal list page

### ISSUE THREAD

**Issue by loxK** [Dolibarr/dolibarr#8782]
# Instructions
- upgrade from 7.0.1 to 7.0.2 with no issue
- got to the accountancy journal list admin page (/accountancy/admin/journals_list.php?id=35&mainmenu=accountancy&leftmenu=accountancy_admin)

Notice the error:

```
Dolibarr: 7.0.2
Niveau de fonctionnalités: 0
PHP: 7.0.28-0ubuntu0.16.04.1
Serveur: nginx/1.10.3
OS: Linux compta 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64
Url sollicitée: /accountancy/admin/journals_list.php?id=35&mainmenu=accountancy&leftmenu=accountancy_admin
Referer: https://****/accountancy/index.php?leftmenu=accountancy_admin
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT a.rowid as rowid, a.code as code, a.label, a.nature, a.active FROM llx_accounting_journal as a WHERE a.entity=1 WHERE a.entity = 1 ORDER BY code ASC LIMIT 1001
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE a.entity = 1 ORDER BY code ASC LIMIT 1001' at line 1
```

## Environment
- **Version**: 7.0.2
- **OS**: ubuntu 16.04
- **Web server**: nginx/1.10.3
- **PHP**: 7.0.28-0ubuntu0.16.04.1
- **Database**: MariaDB 10.0
- **URL(s)**: /accountancy/admin/journals_list.php?id=35&mainmenu=accountancy&leftmenu=accountancy_admin

I can reproduce on three different installations.

**Comment by loxK** [comment]
I suspect [this change](https://github.com/Dolibarr/dolibarr/commit/9c68b81f595e1a0119b8fa3ea66e0e911ea6d9aa#diff-9682f4f46d414453bd0ef19efc5ed8d7R89)

As it seems that "WHERE a.entity = 1" also can be added to the query [here](https://github.com/Dolibarr/dolibarr/blob/7.0.2/htdocs/accountancy/admin/journals_list.php#L401).

**Comment by aspangaro** [comment]
7.0.3 is publish. Please close this issue
