### ISSUE TITLE
Feature Request : customer order complaint

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#8797]
# Feature Request
Add a complaint function for customer order.

## Use case
A customer receive his order, a part is missing or broken. We should be able to notice in the order the error and create an history to solve the problem and justify stock movements.

## Suggested implementation
from a delivered order : 

1. select the line(s) where the problem is (are)
2. Add comment(s)
3. create a new order form the line selected
4. keep history of (linked object etc) of the order
or else

Tks for reading

**Comment by futurehousestore** [comment]
Hi dolibarr95,
Did you have a look at AXeL's module [Product Returns](https://www.dolistore.com/en/modules/828-Product-returns.html?search_query=axel-dev&results=11)? I use it to log such a cases. It will allow you to log all product returns from customer and/or to the supplier plus do the stock movements, link objects, etc. It is a very useful module and you can test it here [Product Returns Demo](http://axel-dev.epizy.com/dolibarr/index.php?i=1)
Kind regards

**Comment by dolibarr95** [comment]
tks :-)
