### ISSUE TITLE
[Bug] 7.0.2: SQL-Error at Products/ Services > Products > Stocks > search/ filter

### ISSUE THREAD

**Issue by SmetsysOver** [Dolibarr/dolibarr#8820]
# Bug
If I search/ filter at column Ref. (Stocks) I get a SQL-Error.

## Environment
- **Version**: 7.0.2
- **OS**: Debian 9.1
- **Web server**: Apache 2.4.25
- **PHP**: 7.0.27
- **Database**: MariaDB 10.1.26
- **URL(s)**: /product/reassort.php (Products/ Services > Products > Stocks > Search)

## Expected and actual behavior
**expected:**
filter my products

**actual:**
```
Das System hat einen technischen Fehler festgestellt.
Diese Informationen können bei der Fehlersuche hilfreich sein (Hinweise können entfernt werden indem $dolibarr_main_prod auf '1' gesetzt wird):
Datum: 20180519172448
Dolibarr: 7.0.2
Funktionslevel: 0
PHP: 7.0.27-0+deb9u1
Server: Apache/2.4.25 (Debian)
OS: Linux host 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Angefragte URL: /product/reassort.php
Referer: https://host/product/reassort.php?type=0&leftmenu=
Menüverwaltung: eldy_menu.php

Datenbank Type Manager: mysqli
Letzter Fehlerhafter Datenbankzugriff: SELECT p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.tms as datem, p.duration, p.tosell as statut, p.tobuy, p.seuil_stock_alerte, p.desiredstock, SUM(s.reel) as stock_physique FROM llx_product as p LEFT JOIN llx_product_stock as s on p.rowid = s.fk_product WHERE p.entity IN (1) AND p.fk_product_type <> '1' AND () GROUP BY p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.tms, p.duration, p.tosell, p.tobuy, p.seuil_stock_alerte, p.desiredstock ORDER BY p.ref ASC LIMIT 201
Rückgabewert des letzten fehlerhaften Datenbankzugriff: DB_ERROR_SYNTAX
Information zum letzten fehlerhaften Datenbankzugriff: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_bas' at line 1
```

## Steps to reproduce the behavior
Simple do a search.   (-;

**Comment by woidi** [comment]
around line 138 in reassort.php there is a typo:
`if ($sref)     $sql.= natural_search('p.ref', $ref);`
last parameter should read $sref

**Comment by SylvainLegrand** [comment]
Hi,

Dolibarr 7.0.3
Ubuntu 16.04
mariadb 10.3.8

I can't reproduce this behavior.

**Comment by DevBossRB** [comment]
Hello,

I can reproduce this problem


**Date**: 20180729092230
**Dolibarr**: 7.0.3
Niveau de fonctionnalités: 0
PHP: 7.0.30-0ubuntu0.16.04.1
Server: Apache/2.4.18 (Ubuntu)
OS: Linux SERVRBTIQ 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

Url sollicitée: /dolibarr/product/reassort.php
Referer: https://XXX/dolibarr/product/reassort.php?type=0&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.tms as datem, p.duration, p.tosell as statut, p.tobuy, p.seuil_stock_alerte, p.desiredstock, SUM(s.reel) as stock_physique FROM llx_product as p LEFT JOIN llx_product_stock as s on p.rowid = s.fk_product WHERE p.entity IN (1) AND p.fk_product_type <> '1' AND () GROUP BY p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_base_type, p.entity, p.fk_product_type, p.tms, p.duration, p.tosell, p.tobuy, p.seuil_stock_alerte, p.desiredstock ORDER BY p.ref ASC LIMIT 26
Code retour dernier accès en base en erreur: DB_ERROR_SYNTAX
Information sur le dernier accès en base en erreur: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY p.rowid, p.ref, p.label, p.barcode, p.price, p.price_ttc, p.price_bas' at line 1

the code at line 137 in reassort.php was
`if ($sref) $sql.= natural_search('p.ref', $ref);`

I made the correction indicated by Woidi
 at line 137 in reassort.php
`if ($sref) $sql.= natural_search('p.ref', $sref);`
**and now it works**

thanks a lot

RB
