### ISSUE TITLE
Services module depends on Products module

### ISSUE THREAD

**Issue by ohreally** [Dolibarr/dolibarr#8835]
This should be fairly easy to repair.
The Services module says it does not depend on any other module, but if the Products module is deactivated, it is not possible to create new services.

**Comment by atm-maxime** [comment]
Could you give more informations ? Version ? Error message while trying to create a service ?
I just tested an could not reproduce in 6.0 and 7.0

**Comment by ohreally** [comment]
No, I'm sorry, but I can't. This was half a year ago, and I've uninstalled Dolibarr in the meantime.
