### ISSUE TITLE
Factur-x / ZUGFeRD support

### ISSUE THREAD

**Issue by camlafit** [Dolibarr/dolibarr#8836]
Could be interesting to support new Factur-x / ZUGFeRD 

- https://mpdf.github.io/what-else-can-i-do/pdf-a3-xmp-rdf.html
- http://fnfe-mpe.org/wp-content/uploads/2018/05/1.-FACTUR-X-V1-2017-12-31.pdf
- https://linuxfr.org/news/odoo-genere-la-premiere-facture-factur-x-deposee-sur-chorus-pro

On my search, actually only [mpdf](https://github.com/mpdf/mpdf/) lib can help to develop this feature.

**Comment by camlafit** [comment]
Hello

Some modules are provided on dolistore about this feature.
To note, in France, any society in 2020 should provide Factur-x in their invoice as Chorus-pro service is mandatory to send invoice to any French Administrative services.

To complete, a lib is provide to check and factur-x xml in any pdf : 
* https://github.com/atgp/factur-x

**Comment by philippe-opendsi** [comment]
Hi Camille

> should provide Factur-x in their invoice as Chorus-pro service is mandatory to send invoice

Not really. You can always upload a simple PDF to ChorusPro but in this case you have to check and enter all the informations of your invoice. But with factur-x, you don't need to do that of course.
Anyway generating factur-x may be a great add to the core function of Dolibarr. Mostly if Dolibarr is able to import factur-x :-)

**Comment by st31ny** [comment]
How is the current state on this matter? I am really interested in this, and also willing to contribute.
I have only basic understanding of Dolibarr's source code yet, so I'd need some more time (or support) to get started.

**Comment by Computences** [comment]
+1

**Comment by rycks** [comment]
Here is a solution: https://www.dolistore.com/fr/ged-gestion-electronique-de-documents/1511-FacturX.html

I'm ok to put the code into dolibarr core but i would like to earn a little bit money with the plugin before :-)

**Comment by st31ny** [comment]
> Here is a solution: https://www.dolistore.com/fr/ged-gestion-electronique-de-documents/1511-FacturX.html

Thanks a lot!

**Comment by vincowl** [comment]
@rycks Do you know if there is a dolibarr version already planned that would include your code in its core ? A huge thanks for this work and gift !

**Comment by rycks** [comment]
@vincowl i think it will not be into dolibarr core because of one good reason : factur-x is only for french-german companies ! And i think it could be a good idea to get it as an outside free module to keep dolibarr core as "light" as possible. And in addition a good idea could be to add a "very easy to install" free modules (like you can add modules in nextcloud for example). It will be native from dolibarr admin choose your free plugin, clic on "install" and "c'est tout". Whitout going to dolistore, download zip and then deploy on your dolibarr.

**Comment by vincowl** [comment]
@rycks Seems great to me ! Thus, this feature can still be considered as a "root feature" by french and german firms since it is maintained by people who need it, letting time to core developers to focus on "universal" topics. Great !!

**Comment by ultrasites** [comment]
This should be pushed to "very important"!
