### ISSUE TITLE
Bug: syntaxe error : can't create an invoice from a proposal

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#8844]
# Bug

## Environment
- **Version**: 8.0.0-alpha
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.33-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB-0+deb8u1
- **URL**: /compta/facture/card.php

## Report
Erreur de syntaxe près de ' , , 0, 0, 100, null, NULL, 1, 1, 0, 'EUR', 0, 0, 0, 0)' à la ligne 1
seems to be an issue from htdocs/core/class/commoninvoice.class.php , function getListOfPayments()
line 297 : $this->id return null.

**Comment by john-botella** [comment]
Hi,
The version 8.0.0-alpha was an alpha version. Actually de 8.0 version is stable, I invite you to install the lastest Dolibarr 8.0 version.
