### ISSUE TITLE
Bug/Issue: Can't change Company settings

### ISSUE THREAD

**Issue by jbeerbom** [Dolibarr/dolibarr#8845]
# Bug
Whenever I try to change the Company settings, and especially the country, the page reloads and/or the settings are just not saved. Nothing shows up in the logs either (PHP, nginx and MySQL).
The database is populated with, what I assume, are the default values. I would try to change these settings in the database, but I do not know which fields to change.

## Environment
- **Version:** 7.0.1
- **OS**: Ubuntu 16.04.4 LTS
- **Webserver**: nginx/1.14.0
- **PHP**: 7.0.30
- **Database**: mysql  Ver 14.14 Distrib 5.7.22

## Expected and actual behavior
The settings are saved.

## Steps to reproduce the behavior
Install Dolibarr and try to change the Company settings.

**Comment by frederic34** [comment]
Can you try with 7.0.2

**Comment by jbeerbom** [comment]
Same issue with 7.0.2

**Comment by mike-au-451** [comment]
I am trying to install dolibarr 7.0.2 with the following environment:

Ubuntu 18.04 LTS
nginx/1.14.0 (Ubuntu)
PHP 7.2.6-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jun 11 2018 15:00:28) ( NTS )
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

My understanding of the code is limited, but it appears that the selectcountry_id element's onchange is supposed to post with an "action" value of "updateedit", but the actual value posted is just "edit".

See htdocs/admin/company.php.

**Comment by mike-au-451** [comment]
After more exploration, it appears $hookmanager->executeHooks is not updating $action correctly.  Maybe there is some problem with the configuration of the hooks.

Near the top of htdocs/admin/company.php there is a line

    if ( ($action == 'update' && ! GETPOST("cancel",'alpha'))
    || ($action == 'updateedit')

Add an extra term:

    || ($_POST['action'] == 'update')

makes this bug go away.

I'm not submitting a patch because this is obviously not a proper fix.  Sorry.

**Comment by jbeerbom** [comment]
Continuing from the solution by @mike-au-451, I also changed line 307 of htdocs/admin/company.php from
 `document.form_index.action.value="updateedit"`
to
 `document.form_index.action.value="update"`
after which both values are saved.

EDIT:
Turns out it is also not possible to add Products/Services and Clients and probably anything else.
Same problem as with the company settings: the page reloads after submitting the form, and some/all of the entered data is gone.

**Comment by hrshovon** [comment]
I am having issue with creating new user. I had the company information issue which I fixed by applying the fix stated here. But user creation doesnt work at all. When I click Create user, the whole page reloads and retains the information. But new user is not listed.

**Comment by Supermanu** [comment]
I had the same issue with php7.0, mariadb, ubuntu 16.04 and dolibarr 9.0. I upgraded to php 7.2 to solve the issue.

**Comment by lawrence296** [comment]
For my case, it was a PHP & nginx configuration that get it to work. For PHP, set:
`cgi.fix_pathinfo=1`

For nginx conf:
`    location ~ [^/]\.php(/|$) {`
`        fastcgi_split_path_info ^(.+?\.php)(/.*)$;`
`        fastcgi_pass unix:/dev/shm/php-fpm.sock;`
`        fastcgi_index  index.php;`
`        fastcgi_read_timeout 180;`
`        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;`
`        fastcgi_param  PATH_INFO       $fastcgi_path_info;`
`        fastcgi_param  PATH_TRANSLATED $document_root$fastcgi_script_name;`
`        include        fastcgi_params;`
`    }`

**Comment by superlamparas** [comment]
I have changed the admin_lib.php in the htdocs/core/lib/ directory.

In the function activateModulesRequiredByCountry()
right after  the line

while (($file = readdir($handle))!==false)
{
add this...
if (!is_file($file)) continue;

That is it!

**Comment by superlamparas** [comment]
I have changed the file  admin.lib.php in the  htdocs/core/lib   dir.

In the function activateModulesRequiredByCountry($country_code)
Right after...
while (($file = readdir($handle))!==false)
{

add the following line...
    if (!is_file($file)) continue;

This avoids issues with hidden files like  .. (dot dot) in linux systems.
