### ISSUE TITLE
BUG: MISSING MAIN_MENU_HIDE_UNAUTHORIZED

### ISSUE THREAD

**Issue by raulnvrz** [Dolibarr/dolibarr#8874]
# Bug
Hiding disabled menu feature is not working in newest versions of dolibarr.

## Environment
- **Version**: 7.x
- **OS**: Linux
- **Web server**: Apache 2.4.29
- **PHP**: 7.1
- **Database**: MySQL 5.0

**Comment by inoveaconseil** [comment]
WIP

**Comment by inoveaconseil** [comment]
Corrected in 7;0.3
