### ISSUE TITLE
Automatic classification of proposals to invoiced

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#8896]
# Feature Request
From an proposal, when we create an invoice, the status could switch to "invoiced". 
## Use case
This is not the case actually (release 7.0.1), the status is still as previous, for example as "Accepted".

## Suggested implementation
When the invoice is created (validated) and that a proposal is linked to it, then switch the status of the linked proposal to "Invoiced".

**Comment by philazerty** [comment]
See and check workflow module in Automatic Classification - Commercial Proposal

**Comment by papoteur-mga** [comment]
Yes, this module seems to satisfy this feature. Thanks to point me it.
However, I don't really understand why it's an option. In this case the module workflow seems as a patch. Who consider that a proposal which has been invoiced will not be at status "Invoiced"?

**Comment by atm-maxime** [comment]
You can have several invoices on the same proposal, your workflow can need someone to check the invoice before classifying the proposal, you can consider the proposal billed once invoices are all paid, you can do this with a global review meteting where you manage your proposal, perhaps you simply don't want it automatic ...
