### ISSUE TITLE
Bug: filter bank entries list

### ISSUE THREAD

**Issue by cmfpmatik** [Dolibarr/dolibarr#8910]
# Description du bug : Dans un compte bancaire, dans l'onglet  "écritures bancaires", si on fait un trie, la même écriture est affichée à l'infini.

## Environment
- **Version**: 7.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.2.5
- **Database**: MySQL or MariaDB 5.5.60-0+deb7u1-log
- **URL**: /compta/bank/bankentries_list.php

**Comment by abraham63** [comment]
Impossible to reproduce this bug. Work fine on my own installation. Have you click on search icon, it's not dynamic reload. Else give more information.

Impossible à reproduire sur ma propre install. Avez vous bien cliquer sur l'icone rechercher (la petite loupe), ce n'est pas du rechargement automatique.

**Comment by cmfpmatik** [comment]
Si on fait, n'importe quel trie, sans choisir de Tags/catégories des transactions, la seule et même écriture est reproduite sur toutes les lignes visibles.

**Comment by aspangaro** [comment]
Sorry. Non reproductible on 7.0.2
