### ISSUE TITLE
restApi in contracts no invoices in linkedObjectsIds

### ISSUE THREAD

**Issue by mpiscaer** [Dolibarr/dolibarr#8914]
When an invoice is created from a contract, this invoice is linked in the linkedObjectsIds property.

You can get a list on invoices with: http://dolibarr.local/dolibarr/api/index.php/contracts/45

But when you do a search like http://dolibarr.local/dolibarr/api/index.php/contracts?sortfield=t.rowid&sortorder=ASC&limit=100&sqlfilters=(rowid%3A%3D%3A45) the linkedObjectsIds has no values.

I would expect that also in an query link this would give me the linked invoices.

## Environment
- **Version**: 7.0.1
- **OS**: Ubuntu 16.04.4 LTS
- **Web server**: apache2 2.4.18-2ubuntu3.8
- **PHP**: 7.0.28-0ubuntu0.16.04.1
- **Database**: mysql 5.7.22-0ubuntu0.16.04.1
- **URL(s)**: http://dolibarr.local/dolibarr/api/index.php/contracts/45  http://dolibarr.local/dolibarr/api/index.php/contracts?sortfield=t.rowid&sortorder=ASC&limit=100&sqlfilters=(rowid%3A%3D%3A45)

## Expected and actual behavior
I whould expect that with an query of the contracts, that I also get the linked invoices

**Comment by romain-neil** [comment]
Hello, the same behaviour happen in the version 16.0.1, any news on this ?

Also happen in versions 16.0.2, 16.0.3, 16.0.4, 16.0.5 and 17.0.0
