### ISSUE TITLE
Tracking field required in shipping method dictionary

### ISSUE THREAD

**Issue by code-chicken** [Dolibarr/dolibarr#8919]
# Bug
Adding new shipping methods in dictionary requires value for tracking field.

## Environment
- **Version**: 7.0.1
- **OS**: Linux vm-dolibarr-test 4.9.34-gentoo #1 SMP Fri Jul 28 13:35:16 CEST 2017 x86_64
- **Web server**: nginx/1.12.1
- **PHP**: 7.0.21
- **Database**: MySQL or MariaDB 5.5.5-10.1.24-MariaDB
- **URL(s)**: http://dolibarr-fuchshuber.starfleet.lan/admin/dict.php?id=18

## Expected and actual behavior
It should be possible to add shipping methods without a tracking url.

## Steps to reproduce the behavior
Create a new shipping method without entering a value in the Tracking field

## [Attached files]

![image](https://user-images.githubusercontent.com/3024019/40971617-8d08cdea-68be-11e8-92c5-bb6e95c37674.png)

**Comment by kevinseebach** [comment]
Easy way until  fix was done in the code : you can edit your SQL schema with PhpMyAdmin and make table c_shipment_mode column tracking possibly null. Edit your structure and and check null box to enable Null value
