### ISSUE TITLE
bug with a decimal discount of the same amount as the invoice with php5.6

### ISSUE THREAD

**Issue by Goldron** [Dolibarr/dolibarr#8928]
# Instructions
Probleme lorsqu'on applique un avoir de meme montant que la facture avec PHP 5.6.33.
seulement avec les montants décimaux.

Le message en retour dit que la remise doit être scindé en deux alors que c'est le meme montant.

un probleme de convertion de type avec php 5.6
sur php7 ca fonctionne tres bien.

## Environment
- **PHP**: 5.6.33
- **Database**: MySql
- **URL(s)**: htdocs/compta/facture/card.php

## Suggested implementation
A la ligne 404

`if ($discount->amount_ttc > $object->getRemainToPay(0))`

correction 

`if ((string)$discount->amount_ttc > $object->getRemainToPay(0))
`

**Comment by atm-maxime** [comment]
I think it has been fixed here : https://github.com/Dolibarr/dolibarr/commit/77e793267116a7cf6a4df703b9c1db5f621aec68
