### ISSUE TITLE
Payments invoices submit several times

### ISSUE THREAD

**Issue by benlo06** [Dolibarr/dolibarr#8933]
# Bug
Hello,

I do not know if you also met the problem, but I am very annoyed since the version 7 + (I am in 7.0.2), I have concerns(marigolds) when I confirm payments regularly payments are validated several times. It raises quite a lot of concerning problems counted her(it) of the company and the invoices which(who) are of this fact false.

When I look logs, the url was submited several times:
[code]
other_vhosts_access.log:172.18.0.7:80 192.168.5.109 - - [29/May/2018:15:57:03 +0200] "POST /compta/ajaxpayment.php HTTP/1.1" 200 374 "https://TOTO.FR/compta/paiement.php?facid=2605&action=create&accountid=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
other_vhosts_access.log:172.18.0.7:80 192.168.5.109 - - [29/May/2018:15:57:03 +0200] "POST /compta/ajaxpayment.php HTTP/1.1" 200 376 "https://TOTO.FR/compta/paiement.php?facid=2605&action=create&accountid=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
other_vhosts_access.log:172.18.0.7:80 192.168.5.109 - - [29/May/2018:15:57:03 +0200] "POST /compta/ajaxpayment.php HTTP/1.1" 200 377 "https://TOTO.FR/compta/paiement.php?facid=2605&action=create&accountid=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
other_vhosts_access.log:172.18.0.7:80 192.168.5.109 - - [29/May/2018:15:57:03 +0200] "POST /compta/ajaxpayment.php HTTP/1.1" 200 377 "https://TOTO.FR/compta/paiement.php?facid=2605&action=create&accountid=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
other_vhosts_access.log:172.18.0.7:80 192.168.5.109 - - [29/May/2018:15:57:04 +0200] "POST /compta/ajaxpayment.php HTTP/1.1" 200 379 "https://TOTO.FR/compta/paiement.php?facid=2605&action=create&accountid=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
other_vhosts_access.log:172.18.0.7:80 192.168.5.109 - - [29/May/2018:15:57:04 +0200] "POST /compta/ajaxpayment.php HTTP/1.1" 200 379 "https://TOTO.FR/compta/paiement.php?facid=2605&action=create&accountid=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
other_vhosts_access.log:172.18.0.7:80 192.168.5.109 - - [29/May/2018:15:57:06 +0200] "POST /compta/ajaxpayment.php HTTP/1.1" 200 379 "https://TOTO.FR/compta/paiement.php?facid=2605&action=create&accountid=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
[/code]

When I see database, payments are inserted with couple as seconds.
[code]
"2682","PAY1805-1176","1","2018-05-29 15:57:20","2018-05-29 15:57:20","2018-05-29 12:00:00","221.70000000","6",,,"2726","5",NULL,"0","0","221.70000000"
"2683","PAY1805-1177","1","2018-05-29 15:57:26","2018-05-29 15:57:27","2018-05-29 12:00:00","221.70000000","6",,,"2727","5",NULL,"0","0","221.70000000"
"2684","PAY1805-1178","1","2018-05-29 15:57:27","2018-05-29 15:57:27","2018-05-29 12:00:00","221.70000000","6",,,"2728","5",NULL,"0","0","221.70000000"
[/code]

Maybe I reproduced the problem: if I double-click on Pay button on  the yellow div in page  TITI.FR/compta/paiement.php, I have 2 paiement validated.
Is it possible to lock Pay button after the first click ?

Regards,
Benoit

## Environment
- **Version**: 7.0.2
- **OS**: [*Server OS type and version*]
- **Web server**: apache2
- **PHP**: [*PHP version*]
- **Database**: mysql

**Comment by mdeweerd** [comment]
This is similar to #7721 .
