### ISSUE TITLE
[BUG] PHP Fatal error « getNomUrl() » on null 

### ISSUE THREAD

**Issue by Ange7** [Dolibarr/dolibarr#8937]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
 PHP Fatal error:  Uncaught Error: Call to a member function getNomUrl() on null in /opt/apps/dolibarr/htdocs/comm/propal/card.php:1827
Stack trace:
    0 {main}
     thrown in /opt/bitnami/apps/dolibarr/htdocs/comm/propal/card.php on line 1827

## Environment
- **Version**: 7.0.0
- **OS**: Ubuntu 14.04.5 LTS
- **Web server**: Apache/2.4.7
- **PHP**: PHP 7.0.23
- **Database**: Ver 14.14 Distrib 5.7.19
- **URL(s)**: /comm/propal/card.php?id=x

## Expected and actual behavior
expected : display commercial offer 
actual : PHP Error

## Steps to reproduce the behavior
On commercial offer if i click on « accept / reject » and doing Yes directly without choosing anything in « Position status to » the column « fk_status » in llx_propal » table go to « -1 » and cause this error 

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

https://www.dolibarr.fr/forum/3-installation/61145-statut-de-la-propale-non-assigne

**Comment by atm-maxime** [comment]
Seems fixed to me in v7, now there's a correct error message when the field is not filled.
