### ISSUE TITLE
[Bug] Muscadet format prints double % in discount column

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#8969]
# Bug
Purchase orders (in Muscadet template) show a misformat in the discount column where a double "%" symbol appears in the PDF printed document.

## Environment
- **Version**: *7.0.2*
- **OS**: *Linux 3.10.102 #15254 SMP Fri Jan 26 06:40:50 CST 2018 x86_64*
- **Web server**: *Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141*
- **PHP**: *5.6.34*
- **Database**: *MariaDB 5.5.57*

**Comment by philazerty** [comment]
Hi,
my patch of core/modules/supplier_order/pdf on 7.0.3 (near line 500)
`// Discount on line
					$pdf->SetXY($this->posxdiscount, $curY);
					if ($object->lines[$i]->remise_percent)
					{
					    $remise_percent = pdf_getlineremisepercent($object, $i, $outputlangs, $hidedetails);
						// Update by Philazerty
						//$pdf->MultiCell($this->postotalht-$this->posxdiscount-1, 3, $remise_percent."%", 0, 'R');
						$pdf->MultiCell($this->postotalht-$this->posxdiscount-1, 3, $remise_percent, 0, 'R');
					}`

**Comment by minigitmax** [comment]
Seems your patch has been included on 8.0.1, isn't it?
Maybe this issue can be closed...
