### ISSUE TITLE
BUG Accountancy  module unabled to open accounting journals configuration

### ISSUE THREAD

**Issue by bgenere** [Dolibarr/dolibarr#9003]
# Bug
The SQL request to open accounting journals in configuration is not properly formed.
SQL request contains twice WHERE a.entity = 1.

I get this error on multiple databases.

## Environment
Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180621152134
Dolibarr: 7.0.2
Level of features: 0
PHP: 7.0.30
Server: Apache
OS: Linux chevre.o2switch.net 3.10.0-714.10.2.lve1.4.79.el7.x86_64 #1 SMP Thu Jan 4 13:30:50 EST 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

Requested URL: /accountancy/admin/journals_list.php?id=35&mainmenu=accountancy&leftmenu=accountancy_admin
Referer: https://dolibarrv7.encom1.fr/user/param_ihm.php?id=1
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT a.rowid as rowid, a.code as code, a.label, a.nature, a.active FROM llxm5_accounting_journal as a **WHERE a.entity=1 WHERE a.entity = 1** ORDER BY code ASC LIMIT 1001
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE a.entity = 1 ORDER BY code ASC LIMIT 1001' at line 1

**Comment by mwelters** [comment]
Will be already fixed in (so far unpublished) 7.0.3

Duplicate of #8806

**Comment by aspangaro** [comment]
7.0.3 is publish. Please close this issue

**Comment by bgenere** [comment]
Tested, it now works
