### ISSUE TITLE
I lost ADMIN access data

### ISSUE THREAD

**Issue by niltonfelipe** [Dolibarr/dolibarr#9004]
Hello,
How to reset the administrator password via code or database? I lost the admin data and can not log in or send the password to my email. 
Thanks.

**Comment by withheld** [comment]
Table llx_user should be rowid 1

**Comment by niltonfelipe** [comment]
The database does not have this table, only these:
lx_accountingaccount
lx_accountingdebcred
lx_accountingtransaction
lx_accounting_bookkeeping
lx_accounting_fiscalyear
lx_accounting_system
lx_actioncomm
lx_actioncomm_extrafields
lx_actioncomm_resources
lx_adherent
lx_adherent_extrafields
lx_adherent_type
lx_adherent_type_extrafields
lx_askpricesupplier
lx_askpricesupplierdet
lx_askpricesupplierdet_extrafields
lx_askpricesupplier_extrafields
lx_bank
lx_bank_account
lx_bank_account_extrafields
lx_bank_categ
lx_bank_class
lx_bank_url
lx_bookmark
lx_bordereau_cheque
lx_boxes
lx_boxes_def
lx_c_actioncomm
lx_c_action_trigger
lx_c_availability
lx_c_barcode_type
lx_c_chargesociales
lx_c_civility
lx_c_country
lx_c_currencies
lx_c_departements
lx_c_ecotaxe
lx_c_effectif
lx_c_email_templates
lx_c_field_list
lx_c_forme_juridique
lx_c_holiday_types
lx_c_incoterms
lx_c_input_method
lx_c_input_reason
lx_c_lead_status
lx_c_paiement
lx_c_paper_format
lx_c_payment_term
lx_c_price_expression

**Comment by withheld** [comment]
Is this a new installation? If no, they are not shown in the navigation menu and I'd try searching for that table. It's a new installation, you are missing a lot of tables.

**Comment by dolibarr95** [comment]
Hi
Forum : 

- www.dolibarr.fr/ (french)
- www.dolibarr.org (english)
- www.dolibarr.es (spanish)
- www.dolibarr.it (italian)
- www.dolibarr.gr (greek)

Tks.

**Comment by niltonfelipe** [comment]
Withheld, if many tables are missing, then I will redo the installation, thank you.

**Comment by vvnt** [comment]
Go to the next page. You are only looking at the first 50 tables!
