### ISSUE TITLE
Bug: Hi, I'm trying to use doli for a school. i've configured an user to be able to validate and to approve PO, but it doesn't seem to work. the list of opened PO is empty

### ISSUE THREAD

**Issue by chazkame** [Dolibarr/dolibarr#9013]
# Bug

## Environment
- **Version**: 8.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 5.6.36
- **Database**: MySQL or MariaDB 5.5.5-10.1.33-MariaDB

**Comment by dolibarr95** [comment]
Hi
Maybe a right access, use the forum : 

- www.dolibarr.fr/ (french)
- www.dolibarr.org (english)
- www.dolibarr.es (spanish)
- www.dolibarr.it (italian)
- www.dolibarr.gr (greek)

Tks.

**Comment by atm-maxime** [comment]
Not an issue, probably rights setup. Also you're using a beta version.
