### ISSUE TITLE
FEATURE REQUEST: Split product/services in cards

### ISSUE THREAD

**Issue by ruistrecht-alt** [Dolibarr/dolibarr#9030]
# Feature Request
Split product/services in cards, this would mean duplicating table code and making two forms for submitting new product/service into an objects line (one for each table).
The single sql table would stay the same, the tables would only be separated visually in object cards and documents

**Comment by hregis** [comment]
@ruistrecht-alt 
can you explain it better because I do not understand what you want to do!?

**Comment by ruistrecht-alt** [comment]
Sure. I used a Contract card has an example, but don't mind that. Imagine this on a Commercial Proposal (propale).
Behold my amazing Paint skills!

Convert the current:
![untitled](https://user-images.githubusercontent.com/23050598/42102016-ae36350a-7bbc-11e8-8901-ba73f3cee5bd.png)
 
To this:
![untitled2](https://user-images.githubusercontent.com/23050598/42102024-b3eea324-7bbc-11e8-8fbb-aeeac61331a7.png)

And after a product/service has been added, show them in two separate tables.
This can be achieved just by changing how tables are displayed, and means duplicating code.

**Comment by hregis** [comment]
@ruistrecht-alt 
why put two blocks? we can already select if it is a product and a service!

**Comment by ruistrecht-alt** [comment]
Yes we can. I was suggesting the separation because I think it is easier to read and tell them apart that way.
In the current state, when both a service and product are added the only thing distinguishing them is an icon.
What if in the future we want services to display more data? Like average daily cost/price based on duration, we would need to adapt the product lines because the columns wouldn't match anymore.

At the current release, if we mess with services we also mess with products. Maybe we should think about   that.

**Comment by ruistrecht-alt** [comment]
In my vision, the final result would be moving from the current:
![untitled5](https://user-images.githubusercontent.com/23050598/42107354-efc9805a-7bce-11e8-89eb-3c8b45387ec3.png)

To this:
![untitled4](https://user-images.githubusercontent.com/23050598/42107356-f44eb000-7bce-11e8-9d55-1d7894cf0be1.png)

Columns could vary from services to products
