### ISSUE TITLE
File not found error provided by document.php

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#9046]
# Bug
Dolibarr **document.php** file can't handle big file download. My Dolibarr has near about 1GB in size file uploaded. The big file is uploaded without any issue. But downloading the big file more than PHP's memory_limit is not working. My web server's PHP memory limit is set to 128M. So I can't download files bigger than 128 MB in size. But this is a very simple web application, so there no need to increase memory limit more than 256 MB, I think. But if a user try to download 1GB file then script fails. The apache error log shows error
**[Tue Jul 03 18:25:56.362456 2018] [:error] [pid 3986] [client 210.16.103.31:55476] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 397049856 bytes) in WEB_ROOT/public_html/document.php on line 258, referer: WEB_ROOT/ecm/index.php?idmenu=26502&mainmenu=ecm&leftmenu=**

## Environment
- **Version**: [*7.0.3*]
- **OS**: [*CentOS-7.1*]
- **Web server**: [*Apache/2.4.6*]
- **PHP**: [*7.0.26*]
- **Database**: [*MySQL 5.7.22*]
- **URL(s)**: [*WEB_ROOT/document.php?modulepart=ecm&attachment=1&file=HR+Templates%2FHR-Templates.zip*]

## Expected and actual behavior
[*PHP script should read the large file chunk wise and send it to the browser.*]

## Steps to reproduce the behavior
[*Upload a large file with size greater than PHP's memory_limit environment variable and try to download the file.*]

## Suggested implementation
[*Don't read the entire file in the Memory to transfer to client. Instead read the file chunk wise and transfer as stream to the browser. So using 128M default PHP memory settings, PHP can handle very large file download.*]

## Suggested steps
[*Don't read the entire file in the Memory to transfer to client. Instead read the file chunk wise and transfer as stream to the browser. So using 128M default PHP memory settings, PHP can handle very large file download.*]

**Comment by alsoft10** [comment]
@eldy Please see this bugs about large file download issue.

**Comment by alsoft10** [comment]
@eldy Is there any update about this bugs?

**Comment by dpriskorn** [comment]
Why do you want to store such huge files in Dolibarr? 
I don't think this is related to Dolibarr but to your setup. The ECM module is not made to support huge files. They are better served by http by some other means IMO.
If you are backing up files to Dolibarr I would suggest you find some other place to put your backups and do it with rsync over ssh or something that is made to handle huge files.
Closing this. Feel free to reopen this if you have good arguments for why this usecase should be handled by Dolibarr.

**Comment by alsoft10** [comment]
Hello @egils-consulting ,
Thank you for your reply. I think this feature is very important for Dolibarr. As the Dolibarr let user to upload large files. So it should let user to download large files too. This is not a hard task to implement. Just need to change the download script. The download script should read the file with certain amount of data, not complete file at once. Then send the file chunk wise to the browser. I need to upload large files, because I have created server resources under resource module. Under server resource i need to keep backup of the server. If you implement this, Dolibarr will be more user friendly and useful.

**Comment by dpriskorn** [comment]
Oh, thanks for the suggestion of chunked transfer that sounds like a good idea to me. 
It makes sense to either implement this or limit the possibility of uploading a size larger than the php memory limit -50mb.
Would you like to send a pull request?

**Comment by dpriskorn** [comment]
Reopening.

**Comment by alsoft10** [comment]
I don't know how to create a pull request!

**Comment by dpriskorn** [comment]
@alsoft10 see https://duckduckgo.com/?q=github+pull+request+tutorial&t=fpas&ia=web
Essentially you just navigate to the file and press the edit button (pen symbol) on the file. 
You can fll in "fixes #9046" in the description. 
Its also possible to hire anyone to implement the change for you and submit the pull request.

**Comment by alsoft10** [comment]
I am going to send pull request  for this change.
