### ISSUE TITLE
version 3.9.4, make payment fails, bad URL character whitespace

### ISSUE THREAD

**Issue by jferran95** [Dolibarr/dolibarr#9047]
https://github.com/Dolibarr/dolibarr/blob/9cc2a7422154fba8bfc152bba5d5d7613c31f25a/htdocs/fourn/facture/card.php#L2202

I've seen the button make payment sometimes fail and the bill page is reloaded. I noticed the URL parameter **action=create &amp;acountid=...** has a whitespace character after the value "create". Just removing that whitespace proved to fix the problem for me. It might be nice to verify this is really wrong.

**Comment by atm-maxime** [comment]
This has been fixed in latest version.
