### ISSUE TITLE
s.address don't appear in societe/list.php

### ISSUE THREAD

**Issue by iouston** [Dolibarr/dolibarr#9052]
# Bug
address fileld don't appear in societe/list

## Environment
- **Version**: v7.xx and older
- **URL(s)**: societe/list

# Feature Request
Please, add address field in this list

**Comment by withheld** [comment]
+1

In the meantime, if you are feeling adventurous you can search /societe/list.php for all s.town references then duplicate using s.address

**Comment by iouston** [comment]
i maked modifications on my list.php file. I'm ok for give this new file but i dont know how to use github for this. I know...shame on me :-)

**Comment by eldy** [comment]
Just go on the "Code tab" and try to edit file using the online editor.

**Comment by iouston** [comment]
"Code tab" on github ? I don't have this tab...I added the modified file in PJ. II have only changed .php to .zip
[list.zip](https://github.com/Dolibarr/dolibarr/files/2177428/list.zip)

**Comment by eldy** [comment]
Yes, the tab with the red line at bottom:
![image](https://user-images.githubusercontent.com/883887/69432295-bb022b80-0d39-11ea-9b46-95aec66c0794.png)
