### ISSUE TITLE
Payment link in emails only if a payment module is active

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#9053]
# Bug
In standard emails a direct payment link us always shown, even if no on line payment module is acitve.
The url points to a payment page wich then says "No active payment module (Paypal, Stripe, Paybox, ...)"

## Environment
- **Version**: 7.0.x
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 5.6
- **Database**: mysql
- **URL(s)**: /compta/facture/card.php  and /public/payment/newpayment.php?source=invoice

## Expected and actual behavior
The link and message should be joined on mail body by a substituition provided by a payment module (internal or external). 
The link and associated message should not be on the standard mail template in language files
Actually, user must use the email templating

## Steps to reproduce the behavior
just click on send mail on an invoice.

**Comment by eldy** [comment]
This has been fixed into 8.0
