### ISSUE TITLE
Complementary attribute "Link to an object" not working for class actioncomm

### ISSUE THREAD

**Issue by glu000** [Dolibarr/dolibarr#9071]
# Bug
Complementary attribute "Link to an object" not working for class actioncomm

## Environment
- **Version**: 7.0.x
- **OS**: not relevant
- **Web server**: not relevant
- **PHP**: not relevant
- **Database**: not relevant
- **URL(s)**: e.g. /societe/card.php

## Expected and actual behavior
Complementary attribute "Link to an object" not working for class actioncomm

Reason is, that the element `fields` is not defined in the class user. Therefore, the SQL-Query tries to fetch the field ref which is not existing in the table llx_user. See function `selectForFormsList` in file `core/class/html.form.class.php`. Also the name of the indexfield of the table llx_actioncomm is "id" instead of "rowid"

## Steps to reproduce the behavior
1. Navigate to Setup -> Modules -> ThirdParties
2. Add a new complementary attribute "link to an object"
3. Enter `ActionComm:comm/action/class/actioncomm.class.php` into the field value and fill out other mandatory fields
4. Press "Save" Button
5. Navigate to Third Party -> List
   (in the current develop version the error happens right now)
6. Open any third party
7. Edit the complementary field you have created before
   -> in V7.0.x the error happens now

## Suggested implementation
1. Add element fields to class user (`comm/action/class/actioncomm.class.php`)
2. The "clean" solution would be to rename the indexfield of the table llx_actioncomm from "id" to "rowid". Not sure, if this is feasable for 7.0.x and 8.x. Therefore I provide a "quick solution" in the function `selectForFormsList`.

````
       
if ($objecttmp->table_element == "actioncomm")
        {
            $id = "id";
        }
        else
        {
            $id = "rowid";
        }

        // Search data
        $sql = "SELECT t." . $id . ", ".$fieldstoshow." FROM ".MAIN_DB_PREFIX .$objecttmp->table_element." as t";

**Comment by atm-maxime** [comment]
I reproduce but not sure how to fix it. I tried your solution but actioncomm table doesn't contain a "ref" field either...
Furthermore, I don't see how useful it can be to have a single link to an Action card. All object in Dolibarr have an "Event" tab which diplays actioncomm...
