### ISSUE TITLE
Module Direct Debit: missing translations and Wiki entry

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9075]
branch: dolibarr-develop

Constants as used in 

\htdocs\admin\prelevement.php

ICS - Creditor Reference
END_TO_END - ?
USTRD - ?
are not defined.

There is no wiki info for this module.

**Comment by torvista** [comment]
Currently:
![clipboard01](https://user-images.githubusercontent.com/4391026/50078971-a4c62400-01e8-11e9-9ab8-71b3c0b444f5.gif)

I suggest these constants be added to 
htdocs/langs/en_US/withdrawals.lang

> ICS=Creditor Identifier CI
> END_TO_END="EndToEndId" SEPA XML tag - Unique id assigned per transaction
> USTRD="Unstructured" SEPA XML tag

To offer this:
![clipboard02](https://user-images.githubusercontent.com/4391026/50080407-4a2ec700-01ec-11e9-9c9f-d4a8db9f44f5.gif)

**Comment by atm-maxime** [comment]
I guess it has been done, I just have this on the develop branch :

![image](https://user-images.githubusercontent.com/2097773/62010490-bd79bd80-b16b-11e9-8d48-f250ed3ad414.png)

Please close if ok
