### ISSUE TITLE
admin, dictionary, units of measure not all showing translations

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9083]
Windows10, Xampp, PHP7.2.6, 0.1.33-MariaDB
- **URL(s)**: ...dolibarr-develop/htdocs/admin/dict.php?id=26
# Bug/Design Problem
When using the es_ES language in the admin, in the dictionary, the list of units of measure is only partially shown in Spanish, despite being fully translated in products.lang.
Eg.
![admin-dict-units-es-en-mixed](https://user-images.githubusercontent.com/4391026/42473324-a0cafa26-83c4-11e8-9365-aac868856998.gif)

## Steps to reproduce the behavior
Select admin language es_ES. 
List units.

There are two aspects to this bug.
1) The code in dict.php is using the column label in the database as the text string name.
` else if ($fieldlist[$field]=='label' && $tabname[$_GET["id"]]==MAIN_DB_PREFIX.'c_units') {
	                            $langs->load("products");
	                            $valuetoshow=$langs->trans($obj->{$fieldlist[$field]});
                            }`

![admin-db-units](https://user-images.githubusercontent.com/4391026/42473439-e895d3ee-83c4-11e8-9cd7-cbeac7b2a35d.gif)

And since “linear meter”, “square meter” and “piece” are not defined (in products.lang) as text string names, they do not get replaced by the selected language.

2) These labels are editable from dict.php!
So any change to any label will break the text replacement of all languages!

Suggestion (from a new user, so maybe I am missing something here).

a) An extra, uneditable db column be added for the names of the reference strings, perhaps using the text string names already present in products.lang.
Eg.
unitP=Piece
unitSET=Set
unitS=Second
unitH=Hour
unitD=Day
unitKG=Kilogram
unitG=Gram
unitM=Meter
unitLM=Linear meter
unitM2=Square meter
unitM3=Cubic meter
unitL=Liter

b)	Changes to the text strings should be done in products.lang, and not in dict.php

c)	Any required NEW units text string NAMES could be added to the db via dict.php as now, but the associated text STRING should be in products.lang.
Although really IMHO it would be better to ask users what new units they have added and add a more comprehensive list to the core install.

**Comment by bubulgum** [comment]
Hi all.
Dolibarr 15.0.1
PRODUCT_USE_UNITS - 1 (enable)

After generate PDF (proporsal or invoice) data in table “Unit” language displays only from [Dictionaries] in any language.
Using default PDF template (azur, crobe).
**How to fix this?**

I have cheked pdf.lib.php
`function pdf_getlineunit($object, $i, $outputlangs, $hidedetails = 0, $hookmanager = false)`

also in pdf.azur.modules.php
`// Unit
					if (!empty($conf->global->PRODUCT_USE_UNITS)) {
						$unit = pdf_getlineunit($object, $i, $outputlangs, $hidedetails, $hookmanager);
						$pdf->SetXY($this->posxunit, $curY);
						$pdf->MultiCell($this->posxdiscount - $this->posxunit - 0.8, 4, $unit, 0, 'L');`

in the Setup-Translations: SizeUnitm = different on each language.
Have cleared cache in browers.
`var_dump($this->posxunit);
int(163) int(163)

var_dump($unit);
string(2) "pc" string(2) "pc"`
