### ISSUE TITLE
Remove deactivated services into new invoice

### ISSUE THREAD

**Issue by titobinbin** [Dolibarr/dolibarr#9087]
# Bug
We have different services with date suscripcion end into contracts. If we deactivate a service into contract active (in exemple: 3 services and 1 not renewal) when created a new invoce for new period, this invoice are created (draft) with service deactivated and we remove this linea service to create invoice finaly.

## Environment
- **Version**: 7.0.3
- **OS**: Linux - Kernel 2.6.32-896.16.1.lve1.4.51.el6.x86_64
- **Web server**: Apache 2.2.29
- **PHP**: 5.4.38
- **Database**: 5.5.47-37.7
- **URL(s)**: 

## Steps to reproduce the behavior
1) Create a new contract
2) Into contract, create a 2 services with date start and end and activated
3) Activate contrat
4) Create an invoice (2 lines/services are showing)
5) When invoice are created, now return to contract 
6) Edit one line of service and deactivted (close this line service / end line but not contract)
7) Create a new invoice and show draft invoce. You can see active service and deactivated service to make a invoice.
8) If you create, then remove the line of service outdated or not renewal for a correct total correct without line service. 

## Suggested steps
- If any service into contract are deactivated, not show to make a invoce and show a total price not correct.

Thanks in advance

**Comment by atm-maxime** [comment]
Hi @titobinbin it's now fixed, wait for next 7.0 release.
Tell us if it's ok for you

**Comment by titobinbin** [comment]
I have now installed 8.0.2 an also have the same issue. Services into contrat are not active yet, show into new invoice.

I send you some captures to explain better.
![service-capture-1](https://user-images.githubusercontent.com/41055136/47910565-95d31e80-de93-11e8-8bf4-00ae408a99e4.jpg)
![service-capture-2](https://user-images.githubusercontent.com/41055136/47910566-95d31e80-de93-11e8-969c-a93f91cef539.jpg)
![service-capture-3](https://user-images.githubusercontent.com/41055136/47910564-953a8800-de93-11e8-98fa-9a03aa15cb28.jpg)

Thanks in advance

**Comment by atm-maxime** [comment]
That's normal, I told you to wait for next release which will include this fix.

**Comment by titobinbin** [comment]
Ok. I understood that it was solved since version 7.0
Ok. No problem, I'll wait.
Thanks

**Comment by titobinbin** [comment]
Hi,  today I updated to 8.0.3 and keep doing the same. 
Is it not into these realease? 
Thanks

**Comment by titobinbin** [comment]
Solve it!. I have tried again and I see that only remove closed services when create a draft invoce (not when clic to make invoice into contrat page)

Good job and thank you
