### ISSUE TITLE
Export/Import Third-Parties does not include company name "Alias"/db name_alias

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9091]
While I am trying to add this to the list of fields for export/import, is there any reason for it **not** to be included in core code?
It's essential for **my** customer initial mass import, as many businesses (in Spain) have a fiscal name and a different commercial name.

**Comment by torvista** [comment]
I've fixed this and am working on adding other fields for import, and correcting the import of provinces, which is currently broken as it matches first province code, which is not unique and so unrelated to correct country/region for the imported province.
The codes used for the Spanish are completely invented/non-standard so are useless as import keys.

**Comment by atm-maxime** [comment]
Hi @torvista it's fixed now, wait for next 7.0 release.
Tell us if it's ok for you

**Comment by torvista** [comment]
Thanks. Actually I have done a lot of improvements to the imports for third party and products, but have not made a pull request yet, too busy with the real world.
I will try and  do them soon.
