### ISSUE TITLE
Bug: cost price is 0 when invoice created from contract or template invoice

### ISSUE THREAD

**Issue by 1Fopresta** [Dolibarr/dolibarr#9100]
# Bug
In a new invoice, created from a contract or a template invoice with 1 or more services/products, the cost price of those services/products is set to 0

## Environment
- **Version**: 7.0.3
- **OS**: Ubuntu 14.04.5
- **Web server**: Apache 2.4.10
- **PHP**: 7.0.30
- **Database**: MySQL 5.5.60

## Steps to reproduce the behavior
- create a service (with buying price)
- create a contract or a template invoice with this service
- create an invoice from the contract or the template invoice

**Comment by simnandez** [comment]
Works fine with 7.0.4
