### ISSUE TITLE
Bug: Enter Payments  

### ISSUE THREAD

**Issue by ias-agm1** [Dolibarr/dolibarr#9102]
# Bug

## Environment
- **Version**: 7.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.1.19
- **Database**: MySQL or MariaDB 10.1.31-MariaDB-cll-lve
- **URL**: /ierp/compta/facture/card.php?facid=32

**Comment by ias-agm1** [comment]
لا تستطيع دفع الفواتير

**Comment by atm-maxime** [comment]
Could you please give description in English?

**Comment by ias-agm1** [comment]
Thanks Problem solved
