### ISSUE TITLE
AgendaEvents API : socpeopleassigned

### ISSUE THREAD

**Issue by AurelienC** [Dolibarr/dolibarr#9104]
Hello,

How use socpeopleassigned via API ? @atm-ph 

I use `contactid`, and `socpeopleassigned` (array of `int`). Event have contact into list (agenda view, for examplep) but not in event page.

Thanks !

**Comment by aconits** [comment]
Hi @AurelienC ,

Before I develop this feature, an event had only one contact assignment with the attribute `contactid`
Now we have a multi-select on the card and we can assign more than one with `socpeopleassigned` (array) and the first key is set into `contactid` if we come from card
For the API call I think you should set `contactid` manually

Here is an example of content of `socpeopleassigned` : 
`$object->socpeopleassigned = array( 12 => array('id' => 12) , 6 => array('id' => 6) );`
Only keys are used in `ActionComm` class for the `create` method
I don't remember exactly why I formated this attribute like that but it was for backward compatibility

I hope that answered your question
