### ISSUE TITLE
Bug: Function load() in translate.class add a \r simbol

### ISSUE THREAD

**Issue by prietojc** [Dolibarr/dolibarr#9105]
# Bug
When **load()** function loads translation file from an external modules, adds a \r simbol at the end of each line. 

## Environment
- **Version**: 7.0.2
- **OS**: Linux Mint
- **Web server**: Apache
- **PHP**: 5.5.9
- **Database**: MySQL
- **URL(s)**: /core/class/translate.class.php

## Expected and actual behavior
Should not happen, its unnecesary. It only can be seen in some tabs, menus or selectarray, I don't know why, but some other functions may be filtering this character.
This behavior doesn't happen in Dolibarr 5.0.2 because the load() function is older.

## Steps to reproduce the behavior
The best way to see it is debugging trans() function from an external module and look into $this->tab_translate[] array. All translated lines ends with **\r**.

## Suggested implementation
This is the current code:
https://github.com/Dolibarr/dolibarr/blob/988b6a49d26d5926aed7a8cef048686a9501a345/htdocs/core/class/translate.class.php#L282

This modification work fine:
`while ($line = fscanf($fp, "%[^= ]%*[ =]%[^\n\r]"))`

**Comment by frederic34** [comment]
which external module cause this problem?

**Comment by prietojc** [comment]
I think , I found it. My translation file ends each line with **\r\n** (0x0D, 0x0A ), I suppose it comes from DOS or Windows. If is saved as Unix this issue dissapear.
This explains why some pages are right and others not.

I don't know what happen using Dolibarr in a Windows server, it should be checked.

**Comment by aljawaid** [comment]
I have the same problem in 7.0.3.  Also randomly.

I used Sublime on Windows to edit my `.lang` files then push to the server (vps on CentOS).

Hope it helps.

**Comment by frederic34** [comment]
@prietojc I already seen that with lang files with \r\n (DOS/Windows). All lang files must have Unix (\n) carriage return.

**Comment by prietojc** [comment]
@frederic34 Ok, thanks.
But I think the suggested modification is easy and simple to avoid this unwanted behavior.
