### ISSUE TITLE
CSV Export file is ISO-8859-1 by default

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9109]
The wiki 
https://wiki.dolibarr.org/index.php/Setup_Other

says this

> EXPORT_CSV_FORCE_CHARSET => Choose the charset of file built by CSV export. By default: UTF-8. Example: EXPORT_CSV_FORCE_CHARSET=ISO-8859-1

but by default this constant does not exist, so in 
\htdocs\core\modules\export\export_csv.modules.php

`if (! empty($conf->global->EXPORT_CSV_FORCE_CHARSET))
		{
			$outputlangs->charset_output = $conf->global->EXPORT_CSV_FORCE_CHARSET;
		}
		else
		{
			$outputlangs->charset_output = 'ISO-8859-1';
		`}``
The file is produced as ISO-8859-1

I suggest the code is changed to utf-8 by default.

**Comment by eldy** [comment]
Yes, by default it is ISO because most users use csv with excel instead of OpenOffice (bouhhh...), and Excel expect csv files to be ISO.

**Comment by torvista** [comment]
Understood.

So 
a) Wiki is incorrect.

b) Since the default database charset and collation is utf-8, having the default export as 8859 is non-intuitive and not explained at any point in the export process: that's poor UI and should be corrected.

c) A default export of 8859 is used only because Excel is totally crap for working with extended character sets. I don't think Dolibarr should be making allowances for deficiencies in commercial software, however widespread it is, but should encourage the use or opensource alternatives, especially when they are far superior, as in this aspect.

Personally, I think 
1) the default export should be utf-8 as per wiki and database. 
2) The export module should show the export character set to be used on the New Export page, so the user can change it before stepping though to the end of the process.
3) Text should be added to the New Export page to recommend the use of Libre/OpenOffice for import/export. This would greatly reduce the common issues people have with mismatched characters when importing their legacy data.

Otherwise, the Wiki needs correcting.
