### ISSUE TITLE
Modules API files are not loaded correctly

### ISSUE THREAD

**Issue by kadogo** [Dolibarr/dolibarr#9116]
# Bug
I had the following error when I tried to use API for the module timebasket.

```
Unable to read api 'timebaskets' from path https://mydolibarr.be/api/index.php/explorer/resources.json/timebaskets (server returned undefined)
```

## Environment
- **Version**: 6.0.7
- **OS**: Debian 9
- **Web server**: Apache
- **PHP**: 7
- **Database**: mysql
- **URL(s)**: http://mydolibar.be/api/index.php/explorer

## Expected and actual behavior
Actually I had the following error.

```
Unable to read api 'timebaskets' from path https://mydolibarr.be/api/index.php/explorer/resources.json/timebaskets (server returned undefined)
```

After some discution with the author of timebasket we find a solution but it need to modify Dolibarr files to change the path of the modules API file when we load them.

I use the next patch to make it work.

```
--- a/index.php 2018-07-13 10:58:36.216000000 +0200
+++ b/index.php 2018-07-13 10:57:55.516000000 +0200
@@ -259,6 +259,10 @@
         if ($module == 'supplierorders')   $classfile = 'supplier_orders';
         if ($module == 'fichinters') $moduledirforclass = 'fichinter';

+        if ($module == 'timebasketconsumptions') $moduledirforclass = 'timebasket';
+        if ($module == 'timebaskets') $moduledirforclass = 'timebasket';
+
+
         $dir_part_file = dol_buildpath('/'.$moduledirforclass.'/class/api_'.$classfile.'.class.php');
         $classname=ucwords($module);
```

But I think it would be better to find another way that doesn't need to modify core files for each plugin.

## Steps to reproduce the behavior
- Install a module (example timebasket)
- Try to use the API of the module

Cheers

**Comment by eldy** [comment]
If the api file is stored into /timebaskets/class/api_timebaskets.class.php
it should be found automaticaly.
Timebasket is an external module so you should contact author to ask him to use this convention for its api (currently, 1 api file is allowed by external module, but with no limit of methods)

**Comment by librethic-code** [comment]
One external module should be able to load more than one API file (it could bring several objects so many API endpoints). Timebasket module brings API for timebasket object but also for dictionaries. 
In the first implementation of API, multiple files loading was working but you broke the detection system for "performance" issue. 

We could add a hook but it seems there is the same performance issue (whole files scan). So what can we do?
