### ISSUE TITLE
Regenerate PDF on public note update

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#9126]
# Feature Request

(Re)generate PDF on public note update

## Use case
Public notes are aimed to be displayed on the PDF, thus it seems that the PDF should be regenerated when we change them, the same way as if I change a line.

**Comment by eldy** [comment]
On which object do you experience a non rebuild of pdf ?
Which dolibarr version ?

**Comment by dbeniamine** [comment]
It happens when I edit / create public notes on propals and bills with Dolibarr `7.0.1` and `7.0.3`, If I remember well, it was all the same on `6.X`

**Comment by eldy** [comment]
Has been fixed for 9.0
