### ISSUE TITLE
Bug: Dictionary->Edit Payment Mode "Unknown column 'rowid' in 'where clause'"

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9135]
Version Develop.
1) Add a new payment type.
2) Edit it: get php error.

Cause: index in llx_c_paiement is "id" not "rowid" and mapping is incorrect in dict.php.

Fix: 

in \dolibarr-develop\htdocs\admin\dict.php

line 382
change
`$tabrowid[13]= "";`
to
`$tabrowid[13]= "id";`

**Comment by hregis** [comment]
@torvista 
no, this field is now in autoincrement 
try to restart dolibarr upgrade from 6.0.x to 7.0.x

**Comment by torvista** [comment]
Thanks for the response.

But, I am using the current development version 9alpha, and the section where I have made the change has this text at the start

> // Nom du rowid si le champ n'est pas de type autoincrement
// Example: "" if id field is "rowid" and has autoincrement on
//          "nameoffield" if id field is not "rowid" or has not autoincrement on

There are other tables that use "id" (not "rowid") and are also auto-increment, such as 
$tabrowid[6] = "id";
that uses
$tabname[6] = MAIN_DB_PREFIX."c_actioncomm";

So, I do not see that I am wrong, especially since my fix cures the error message.

**Comment by hregis** [comment]
@torvista 
sorry, you right https://github.com/Dolibarr/dolibarr/pull/9143
