### ISSUE TITLE
Invoice pdf cell height too small on other languages (doesn't scale on default Dolibarr 7.0.2)

### ISSUE THREAD

**Issue by romuva** [Dolibarr/dolibarr#9164]
Hi,
I am using Dolibarr 7.0.2 in Lithuanian language and have a bug in invoices, that in another language (not English) cell height doesn't scale in invoice. How can I fix this? Thanks.

Attached files:
![fa1807-0004 11](https://user-images.githubusercontent.com/33764676/43258733-70af8d64-90dc-11e8-81fd-62d4dc58c5cb.jpg)

**Comment by eldy** [comment]
This field were not designed initially to be scaled.
Goal was to have a translation for this field that are shortcuts. You may suggest shorter translation on transifex.com for project dolibarr or overwrite translation for your dolibarr from menu home - setup - translation
