### ISSUE TITLE
Includes debugBar

### ISSUE THREAD

**Issue by rsanjoseo** [Dolibarr/dolibarr#9170]
# Feature Request
It would be interesting to have a modern debugging tool in debug mode, such as:
https://github.com/maximebf/php-debugbar

## Use case
It shows a debug bar with information about execution, SQL queries, time consumed between strategic points and messages for debugging the code.
This bar would only be shown if LOG_DEBUG is greater than 0.

## Suggested implementation
Include the debugBar module through the composer. If LOG_DEBUG is greater than 0, place the JS and CSS code of that application on all pages, patch SQL queries and LOG messages to display them in the debug bar.

## Suggested steps
- Include degubBar in composer.
- Include the autoloader code.
- Modify the SQL queries to send the query to the SQL tab of the debug bar.
- Modify dol_syslog to send messages on the Messages tab of the debug bar.
- Include in the header and footer of each page the include of the debugBar js and css files

**Comment by librethic-code** [comment]
There is an external module for this on Dolistore : https://www.dolistore.com/en/modules/996-Debug-bar.html

**Comment by rsanjoseo** [comment]
I did not know that plugin.
I suppose that in this case, it would not be necessary to implement this change.
I thought it could be useful for developers, because for me it is.

**Comment by librethic-code** [comment]
This module is very useful and we might get bored if we have to install for each projects… 

Keep open this issue, if someone want to do it… you can also ask developper of module if he/she wants it to be included into core as there is no licence into package :(

**Comment by frederic34** [comment]
@AXeL-dev

**Comment by AXeL-dev** [comment]
Hey,
yeah sure, i just added a github repository for the module if someone wants to help improving it [debugbar](https://github.com/AXeL-dev/dolibarr-debugbar_module), & it's okay if dolibarr's team want to include it as a core module x).

**Comment by laudeco** [comment]
@rsanjoseo I guess this ticket can be closed ...
