### ISSUE TITLE
Show the author field in the commands/invoices lists

### ISSUE THREAD

**Issue by tarrsalah** [Dolibarr/dolibarr#9176]
# Feature Request
Show the author field in the list of clients/suppliers commands/invoices  lists.

## Suggested implementation

The implementation should be straightforward, if this FT is accepted, what branch should I use as a base for the PR?

**Comment by tarrsalah** [comment]
What do you think @bafbes ?

**Comment by hregis** [comment]
@tarrsalah 
in develop branch
