### ISSUE TITLE
Hidden extrafields erased at update of an object

### ISSUE THREAD

**Issue by code42fr** [Dolibarr/dolibarr#9179]
## Bug

Hidden extrafields with visibility 0 are erased during the update of an object extending commonObject class.

## Environment

* Version: 7.0.1
* OS: Ubuntu Linux
* Web server: Nginx
* PHP: 7.0
* Database: MySQL

## Expected and actual behavior

Inside societe/card.php. If we update a thirdparty, the value of hidden extrafield is erased (During an update of a commonObject, extrafields are deleted and then inserted instead of updated => function insertExtrafields() of commonObject.class.php).

## Steps to reproduce the behavior

* Add an hidden extrafield for thirdparties (visibility: 0).
* Set a value to the hidden extrafield.
* Update the thirdparty (ex: change email address).
* Value of the hidden extrafield will be erased.

**Comment by john-botella** [comment]
This bug is fixed. Update your Dolibarr to the last 7.0.X version.
