### ISSUE TITLE
activateModulesRequiredByCountry error on OVH

### ISSUE THREAD

**Issue by kevinseebach** [Dolibarr/dolibarr#9182]
# Bug
There is a bug making company information unsetable. I can select country of my company but not the name and other information. 
After some research I have found that error is due to activateModulesRequiredByCountry function on admin/company.php

I think is due to user right on server but not sure. So I ask for dev if they have more ideas and maybe work on a future correction for that if it's really a dolibarr problem.

## Environment
- **Version**: 7.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.4
- **Database**: MySQL

Edit : 
It seems to be an user rights problem on server because permissions edit page is blank too. It's doesn't scan directory of plugins.

**Comment by eldy** [comment]
If you have a blank page, you should also have detail of reason of error in the apache error.log file.
Check it.
