### ISSUE TITLE
{line_options_xxx} in ODT Shipment module not working

### ISSUE THREAD

**Issue by bartiest** [Dolibarr/dolibarr#9183]
# Instructions
I've tried to make an ODT template for the shipment module with the variable {line_options_xxx} in it.

# Bug
The {line_options_xxx} will not retrieve any values from the DB.
All works fine with ODT templates in the Customer Order module.

## Environment
- **Version**: 7.03, 8.0.0 alpha, 9.0.0. alpha
- **Web server**: Apache2
- **PHP**: 7.0, 7.2.6
- **Database**: MySQL 10.1.31-MariaDB

**Comment by ivancalax** [comment]
I'm having the same bug and i don't find documentation to fix it.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/9284

**Comment by ivancalax** [comment]
Thanks @frederic34. Can I replace this code from the original file? I am running Dolibarr 7.03.

**Comment by frederic34** [comment]
@ivancalax you can test, I made a test in a 7.0.1

**Comment by ivancalax** [comment]
Thanks for share this update @frederic34. Now the template file ODT works totally fine. 🤩🎉🎆

**Comment by bartiest** [comment]
Not working for Dolibarr 8.0.0. @frederic34 Couldn't find the corresponding line numbers. I think file has been altered in Dolibarr 8.0.0. I'm not that technical. Could you please see into the 8.0 file and make the adjustments. I've tried it my self but didn't work.

**Comment by frederic34** [comment]
@bartiest changes have been merged, you can find the result in branch 8

**Comment by bartiest** [comment]
If tried and doesn't give the result I was expecting. {line_option_XXX} still isn't working.
This is the code I use in the ODT template

[!-- BEGIN row.lines 				--]
{line_fulldesc}
{line_vatrate}
{line_up}
{line_qty}
{line_discount_percent}
{line_options_artist}
{line_options_format}
{line_price_ht}
[!-- END 				row.lines --]

**Comment by ivancalax** [comment]
Once time I tried to show the variables and then the {line_option_XXX} don't working but I fix it cleaning the code of the ODT template and replacing the code manually.

**Comment by bartiest** [comment]
I updated to 8.0.1 and now no {line_xxx} is filled.

**Comment by frederic34** [comment]
🤔

**Comment by bartiest** [comment]
I think you read it wrong. It is not working anymore at all.
Not one {line_ parameter is filled

**Comment by bartiest** [comment]
Trying to get it to work. I am on 9.0.0 beta now and still {line_options_xxx} is not working in the ODT template.

**Comment by marcominutti** [comment]
Hello, have you find the solution, I'm having the same issue, I want to display in expedition PDF the unit of the product next to the quantity.

**Comment by danloic** [comment]
Hi everyone,

I have exactly the same issue as bartiest in Dolibarr V13, when I want generat an ODT from shipment form, the extra fields not appear in the generated document.

**Comment by ksar-ksar** [comment]
Correction : #16583

**Comment by mpractic** [comment]
I think this fix isn't included in 14.0. Is it?
