### ISSUE TITLE
Bug: Error applying VAT to exempt clients

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#9189]
# Bug

## Environment
- **Version**: 5.0.7 and 7.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: apache2handler 5.5.14
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB
- **URL**: /dolibarr/htdocs/index.php?mainmenu=home

## Report
When from a customer's file (which has a VAT specified in its file) a quote, order is created ..., this specification does not work, and the default VAT of the products is applied, when, having to select a 0% VAT manually in each and every one of the products, when this should be automatic if a client has specified that he is exempt from paying VAT on his file.

This error occurs to us both in the version we use (5.0.7) and in the version for tests (7.0.3).

------------------------------------------------------------------------------------------------------------------
Spanish 

Cuando desde la ficha de un cliente (el cual tiene especificado en su ficha que no hay que aplicarle IVA) se crea un presupuesto, pedido..., dicha especificacion no funciona, y se aplica el IVA por defecto de los productos, cuando, teniendo que seleccionar un IVA al 0% manualmente en todos y cada uno de los productos, cuando esto deberia ser automatico si un cliente tiene especificado que esta exento de pagar IVA en su ficha.

Dicho error nos ocurre tanto en la version que usamos (5.0.7) como en la version para pruebas  (7.0.3).

**Comment by JuanBrillo** [comment]
Currently, in version 11.0.1, the same thing continues. You have to go one by one on all products by removing the local tax.

------

Actualmente, en la version 11.0.1, sigue pasando lo mismo. Hay que ir uno a uno en todos los productos quitando el impuesto local.

**Comment by eldy** [comment]
There is no way to specify that is client is exempt of VAT currently in Dolibarr. The field "VAT use" means this thirdparty does not apply VAT when this thirdparty makes an  invoice itself.
Currently the rule to define if a vat is applied or not is
By default when creating prospects, invoices, orders etc. the Sales Tax rate follows the active standard rule:

> If the seller is not subject to Sales tax, then Sales tax defaults to 0. End of rule.
> If the (seller's country = buyer's country), then the Sales tax by default equals the Sales tax of the product in the seller's country. End of rule.
> If the seller and buyer are both in the European Community and goods are transport-related products (haulage, shipping, airline), the default VAT is 0. This rule is dependant on the seller's country - please consult with your accountant. The VAT should be paid by the buyer to the customs office in their country and not to the seller. End of rule. (rule not implemented)
> If the seller and buyer are both in the European Community and the buyer is not a company (with a registered intra-Community VAT number) then the VAT defaults to the VAT rate of the seller's country. End of rule.
> If the seller and buyer are both in the European Community and the buyer is a company (with a registered intra-Community VAT number), then the VAT is 0 by default. End of rule.
> In any other case the proposed default is Sales tax=0. End of rule.

So there is no way to define that a customer is exempt of VAT when he buy products to you. So this may be a feature request.
