### ISSUE TITLE
On the use of SQL triggers

### ISSUE THREAD

**Issue by tarrsalah** [Dolibarr/dolibarr#9190]
Given that MySQL supports triggers for quite some time, What is the main obstacle that prevents Dolibarr from using them?

**Comment by eldy** [comment]
We just don't need them.
And to avoid to have business code conflict (for example a check in php that is different than a check in a sql trigger), we put all business code in the same level (so the php)

**Comment by tarrsalah** [comment]
Thanks @eldy!
