### ISSUE TITLE
Modification des extrafield depuis l'API Rest

### ISSUE THREAD

**Issue by splanta** [Dolibarr/dolibarr#9193]
Bonjour, 

Je rencontre un problème pour l'update des extrafields. 

Aucun souci pour un champ natif (ref_client par exemple) ou un nom d'extrafield inconnu, je les vois bien dans le retour du curl, ajouté aux array_options, mais si je mets un champ existant, l'update ne se fait pas...

Mes champs n'ont pourtant aucune contrainte et l'option "Peut toujours être édité" est bien cochée.
J'arrive bien à les modifier dans l'interface, mais aucun update possible ... (voir la capture)
![image](https://user-images.githubusercontent.com/42030444/43576696-3af5adc0-964a-11e8-90ed-2b6f2ca5c703.png)

Avez-vous une idée ?

En vous remerciant par avance pour votre aide !

**Comment by Jerome-mi** [comment]
Bonjour,
As tu un message d'erreur ?
peux tu activer le module des logs de Dolibarr et regarder ce qu'il se passe côté base de données ?

**Comment by tonio79** [comment]
Bonjour, étant à l'origine du ticket posté sur le forum, je me permets de répondre :)
Nous avons vu que la gestion des extrafields n'était pas implémentée dans la v7 en update de commande. Celle-ci a été actualisée dans la v8, mais il y a un souci assez gênant. En update on perd tous les extrafields non postés ...! (la table est vidée puis les extrafields postés sont insérés)
Je vous joins le lien vers le forum où j'explique le problème
https://www.dolibarr.fr/forum/12-howto--aide/58888-documentation-api-rest?start=90#99430

Merci !
