### ISSUE TITLE
Dolibarr factory module not working with serial numbers

### ISSUE THREAD

**Issue by vkubik** [Dolibarr/dolibarr#9206]
Hello.
I am utilized dolibarr 7.0.3 and for manufacturing I am installed 
free version of Factory Free, CAM for Dolibarr.
It is not working with serial numbers.
I am utilize BOM structure in  manufacturing.
![screenshot_1](https://user-images.githubusercontent.com/8377288/43703359-e0650de0-995c-11e8-98b9-ae1e7f6dc5c5.jpg)
For example I need to manufacure 1 product with name "Product1". This product consist of:
20 subproduct1
15 subproduct2
![screenshot_2](https://user-images.githubusercontent.com/8377288/43703372-e87df00a-995c-11e8-9ed1-d7f74a24af65.jpg)
When I create production with number of product 1 I have system message 
1 product (s) manufactured
but en physical stock I have 0 products.
![screenshot_3](https://user-images.githubusercontent.com/8377288/43703352-d6d91730-995c-11e8-983f-60a86b0d52df.jpg)
It's meen that manufacturing not working with serials numbers.
Please help to issue this problem.
Thank's.

**Comment by frederic34** [comment]
please contact @defrance for help on this external module

**Comment by eldy** [comment]
The module "Factory" is not an official module but a third party external module so you must contact this supplier for support on this module
