### ISSUE TITLE
Can´t update 7.0.2 -> 7.0.3

### ISSUE THREAD

**Issue by julbroa-zz** [Dolibarr/dolibarr#9219]
# Bug
If I try to update dolibarr from version 7.0.2 to 7.0.3, I overwrite the files (as always), the selection screen appears and when I click on start it takes and the 504 error screen appears

## Environment
- **Version**: 7.0.2
- **OS**: Linux us-imm-web76.main-hosting.eu 2.6.32-896.16.1.lve1.4.53.el6.x86_64 #1 SMP Sun Feb 18 08:20:42 EST 2018 x86_64
- **Web server**: Apache
- **PHP**: 5.6.37
- **Database**: MySQL or MariaDB 10.2.16-MariaDB
- **URL(s)**: htdocs/install/upgrade.php?action=upgrade&selectlang=es_US&versionfrom=6.0.0&versionto=7.0.0

## Expected and actual behavior
Expected: Perform the update without problems as usual.
Current: The update is interrupted and does not conclude

## Steps to reproduce the behavior
Try updating to version 7.0.3

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![2018-08-07 1](https://user-images.githubusercontent.com/28205134/43803027-3b0565a0-9a5d-11e8-8e0d-9897868fcd79.png)

**Comment by withheld** [comment]
Your image shows the web server is using OpenResty which is based around the Nginx core. Are you using a CDN/proxy?

**Comment by eldy** [comment]
You may have a slow server or a busy database.
Try to increase PHP or web server timeout.

**Comment by julbroa-zz** [comment]
I have increased PHP timeout to 1000s but still I have not been able to finish the update.
