### ISSUE TITLE
Api login error when you create a new user

### ISSUE THREAD

**Issue by raulnvrz** [Dolibarr/dolibarr#9225]
# Bug
When creating a new user and assigning the admininstrator role, the correspondant permits of the "users module" arent being created. Also, you cant activate them since you already are an administrator and the panel shows you a star like you already have them (the permits), and this is why, in the moment of logging in with the API, it returns an Error.

## Environment
- **Version**: 7.0.3
- **OS**: Ubuntu Linux 16.04.3
- **Web server**: Apache version 2.4.18
- **PHP**: 7.0
- **Database**: MySQL version 5.7.23

## [Attached files]

"code": 403,
    "message": "Forbidden: User need write permission on itself to reset its API token"

**Comment by eldy** [comment]
This is expected behaviour. 
What you can do is set the api key when you create the user. Because the login from api should be avoid. All API call should use the token to avoid to call the login method.

**Comment by tarikelbannany** [comment]
i still have the same issue in the last stable-version 12.0.3

**Comment by dotupNET** [comment]
In module api settings:

URL zum Abrufen des Tokens zur Verwendung der API (sobald das Token empfangen wurde, wird es in der Datenbankbenutzertabelle gespeichert und muss bei jedem API-Aufruf angegeben werden):
 http://localhost:8080/api/index.php/login?login=auserlogin&password=thepassword[&reset=1]

But it doesn't work

**Comment by smacz42** [comment]
If this ^^ isn't the recommended way to do this, then how is it?

Especially as an admin, I want AUTOMATION to do this for me.

**Comment by raulnvrz** [comment]
@smacz42 maybe before you create the user,  you culd generate the api token with the core function and assign them to the user object

**Comment by smacz42** [comment]
Forgive my ignorance, but what are you talking about when you say "core function"?

**Comment by raulnvrz** [comment]
When you create a user from the dolibarr portal, dolibarr has the optiom to create an api key, you could do the same action in your web service when you create a user, generate this api key with this dolibarr source and assign it to your user object and then create the user

-
![Screenshot_20211031_193616](https://user-images.githubusercontent.com/19657466/139613967-7036a570-4d71-49e2-87b3-f0f723fc716e.jpg)

**Comment by smacz42** [comment]
Thanks for the response! I'll include that in the linked issue.

**Comment by raulnvrz** [comment]
Your welcome

Best regards!
