### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by LulliHaloumi** [Dolibarr/dolibarr#9232]
Hi,

I've watched a bunch of youtube videos, I read through forums, I read the documentation and I searched good old google however I still can't get it working.

When I install Dolibarr with DoliWamp, I see an error in my browser:

This site can’t be reached
localhost refused to connect.
Search Google for localhost dolibarr install
ERR_CONNECTION_REFUSED

**Comment by philazerty** [comment]
Hi, 
See the forum : 
https://www.dolibarr.fr/forum/12-howto--aide/58707-localhost-n-autorise-pas-la-connexion-de-dolibarr#83558
https://www.dolibarr.fr/forum/3-installation/59956-problemes-pour-installer-doliwamp-sur-windows-10#88601
Sorry, it's in french...
@+
