### ISSUE TITLE
Bug:  Lots/Series in 8.0.0

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#9257]
# Bug

## Environment
- **Version**: 8.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: apache2handler 5.5.14
- **Database**: MySQL or MariaDB 5.5.5-10.0.35-MariaDB
- **URL**: /dolibarr/htdocs/product/stock/productlot_list.php?leftmenu=

## Report
By clicking on Products | Services> Products> Lots / Series a syntax error occurs, part of the message shown on the screen is as follows:

> Last database access error: SELECT t.rowid, t.entity, t.fk_product, t.batch, t.sellby, t.eatby, t.datec as date_creation, t.tms as date_update, t.fk_user_creat, t.fk_user_modif, t.import_key, p.fk_product_type as product_type, p.ref as product_ref, p.label as product_label FROM llx_product_lot as t, llx_product as p WHERE p.rowid = t.fk_product WHERE p.entity IN (1) ORDER BY t.batch ASC LIMIT 26
> Error return code for the last request to access the database: DB_ERROR_SYNTAX

> Information about the last database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE p.entity IN (1) ORDER BY t.batch ASC LIMIT 26' at line 1

**Comment by eldy** [comment]
Fixed for 8.0.1
