### ISSUE TITLE
Bug: image on the product

### ISSUE THREAD

**Issue by renemuller** [Dolibarr/dolibarr#9262]
# Bug:
I cant included picture with the product ref

René

## Environment
- **Version**: 7.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.6.36
- **Database**: MySQL or MariaDB 5.5.55-0+deb7u1-log
- **URL**: /forscoerp/htdocs/product/list.php?leftmenu=product&type=0

**Comment by atm-maxime** [comment]
Can you provide more infos ? Pictures can be added on products in the attachment tab.
