### ISSUE TITLE
Bug: All links go on a wrong propal

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#9271]
# Bug
All the links go on a wrong proposal, which is still the same for all links and with a wrong thirdparty
## Environment
- **Version**: 9.0.0-alpha
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.20-1+0~20180725103117.2+jessie~1.gbpd5b650
- **Database**: MySQL or MariaDB 5.5.5-10.0.35-MariaDB-0+deb8u1
- **URL**: /comm/propal/list.php?socid=386

**Comment by futurehousestore** [comment]
Same thing in version 8.0.1

**Comment by grandoc** [comment]
do you use some external modules ? and which one ? 
seems to be may be a hook...

**Comment by futurehousestore** [comment]
Yes, I use:
1. Purchases
2. Product Returns
3. Ultimatepdf
4. Get customer last price
5. CyberOffice
6. MyCyberOffice
7. Suppliers Prices
8. DoliCalc
9. List Export / Import
Have you manage to fix this issue in ver. 9.0.0-alpha?

**Comment by futurehousestore** [comment]
Today's github update fixed the problem ;)
