### ISSUE TITLE
Product --> Lots/Serials - Error coming

### ISSUE THREAD

**Issue by dipen10** [Dolibarr/dolibarr#9281]
**Bug**

When we click the Product --> Lots/Serials then below error is coming

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180822105244

Dolibarr: 8.0.0
Level of features: 0
PHP: 5.6.37
Server: Apache
OS: Linux s132-148-131-23.secureserver.net 2.6.32-042stab126.1 #1 SMP Wed Nov 15 20:14:46 MSK 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

Requested URL: /erp/product/stock/productlot_list.php?leftmenu=
Referer: http://afans.in/erp/product/index.php?mainmenu=products&leftmenu=
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: SELECT t.rowid, t.entity, t.fk_product, t.batch, t.sellby, t.eatby, t.datec as date_creation, t.tms as date_update, t.fk_user_creat, t.fk_user_modif, t.import_key, p.fk_product_type as product_type, p.ref as product_ref, p.label as product_label,ef.lotnumber as options_lotnumber FROM erp_product_lot as t LEFT JOIN erp_product_lot_extrafields as ef on (t.rowid = ef.fk_object), erp_product as p WHERE p.rowid = t.fk_product WHERE p.entity IN (1) ORDER BY t.batch ASC LIMIT 26
Return code for latest database access request error: DB_ERROR_SYNTAX
Information for latest database access request error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE p.entity IN (1) ORDER BY t.batch ASC LIMIT 26' at line 1

**Comment by JosQuelqu1** [comment]
Same here

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20180826170147
Dolibarr: 8.0.0
Niveau de fonctionnalités: 0
PHP: 7.2.7-0ubuntu0.18.04.2
Server: Apache/2.4.29 (Ubuntu)
OS: Linux lapp 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

URL requise: /dolibarr/product/stock/productlot_list.php?leftmenu=
Referer: http://10.0.0.7/dolibarr/product/index.php?mainmenu=products&leftmenu=
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: pgsql
Erreur de demande d'accès à la base de données la plus récente: SELECT t.rowid, t.entity, t.fk_product, t.batch, t.sellby, t.eatby, t.datec as date_creation, t.tms as date_update, t.fk_user_creat, t.fk_user_modif, t.import_key, p.fk_product_type as product_type, p.ref as product_ref, p.label as product_label FROM llx_product_lot as t, llx_product as p WHERE p.rowid = t.fk_product WHERE p.entity IN (1) ORDER BY t.batch ASC LIMIT 26
Code de retour pour la dernière erreur de demande d'accès à la base de données: DB_ERROR_SYNTAX
Informations pour la dernière erreur de demande d'accès à la base de données: ERROR: 42601: syntax error at or near "WHERE"\nLINE 1: ... t, llx_product as p WHERE p.rowid = t.fk_product WHERE p.en...\n ^\nLOCATION: scanner_yyerror, scan.l:1087

I had the same error with MySQL 5.7 on Ubuntu 18.04 and PostgreSQL 10 on CentOS 7. Now on Ubuntu 18.04 and PostgreSQL 10. PHP 7.2 on all scenarios.

**Comment by fappels** [comment]
See PR #9301

**Comment by dipen10** [comment]
Working fine for me after updating the htdocs/product/stock/productlot_list.php
