### ISSUE TITLE
Bug in Shipments > Extrafields (Complementary attributes) V 8.0 - not show

### ISSUE THREAD

**Issue by MarcoRuizMartinez** [Dolibarr/dolibarr#9283]
# Bug
Hi. Apologies for my English. I found a Bug in version 8 of Dolibarr. The problem is that it does not show the "Complementary attributes" that one creates in the Shipments module, in the creation form of a shipment or expedition. In version 7.0.3 and in general, in all versions if they appeared.
I tested it in a clean installation, where I only activate the Third Party, Customer Orders and Shipments modules.

## Environment
- **Version**: Dolibarr 8.0.0

## Expected and actual behavior
Another problem is that version 7 is the copy of the data of the "Complementary attributes"" from the order, to the shipment, but not now.
In addition, you can not create mandatory fields, why the process of creating a shipment is blocked.

## Steps to reproduce the behavior
1. In the section of the Shipments module> in the tab "Complementary attributes"> Create an additional field called "city" and that is required and with visibility 1.
2. I did exactly the same, but in the "Customer Orders" module.
3. Create a customer and create an order. In the "city" field, enter xxxx. Then validate the order.
4. In the order, I gave "CREATE SHIPMENT".
5. When the expedition / card.php page is shown, the "city" field does not appear anywhere and, as is obligatory, it does not allow me to create the shipment.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots)

![screenshot](https://user-images.githubusercontent.com/42611365/44467496-9c6a2d80-a5e8-11e8-9106-acf0393afcdb.png)

**Comment by jamshaidalipak** [comment]
Same with me.

**Comment by MarcoRuizMartinez** [comment]
With version 8.0.1 you have the same problem. Still not solved.

**Comment by minigitmax** [comment]
I confirm the same bug in 8.0.1
The effect is that shipments cannot be created if required extrafields are present in the module.

**Comment by fmarcet** [comment]
This bug was solved in 8.0.2 with this pull request #9413

**Comment by MarcoRuizMartinez** [comment]
Great. Thank you very much to the development team.
