### ISSUE TITLE
Error creating invoice (client header fields). V. 7.03

### ISSUE THREAD

**Issue by mmascarom** [Dolibarr/dolibarr#9289]
# Bug
Error creating invoice (client header fields). V. 7.03

## Environment
- **Version**: 7.03
- **OS**: Windows 10 Pro
- **Web server**: WampServer 3.0.8 64bits
- **PHP**: 7.0.10
- **Database**: MySQL 5.7.14
- **URL(s)**: erp.erpsolutions.es:8001/demo

## Expected and actual behavior
In the third party file, we have the fields PAYMENT CONDITIONS and PAYMENT METHOD predefined for the client duly completed.
In this sense, when we create a new invoice and select the customer, the PAYMENT CONDITIONS and PAYMENT METHOD fields in the header of the invoice are not filled, although in the client's file they are duly filled in, having to manually put said information in each of the new invoices created to the client.
We believe that, since in the third party file it is possible to put the default information of the payment method and the payment conditions, this should be auto-filled in each of the documents created to said third party, in order to avoid errors.
In previous versions, v.5.0 for example, this functionality was implemented, so we believe it is a bug of version 7.x of Dolibarr.

**Comment by atm-maxime** [comment]
Not implemented yet, you should go on the customer tab of the thirdparty card and create your invoice from here. As the thirdparty is already known (which is not the case when you use the left menu "New invoice"), these fields are pre-filled
