### ISSUE TITLE
Columns under "ECM filemanager -> Manual tree" are not aligned

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#9290]
The right column, showing number of files and modify button, is not aligned with the left one. The right one is dropping below by one row.

See image.

This bug can be seen in Dolibarr V6.0.4 and V7.0.3. Have not tested older versions.

![ecm_dir](https://user-images.githubusercontent.com/11036018/44518871-b4ff4400-a6cb-11e8-9fc3-73c6e5dea039.png)

**Comment by bos4711** [comment]
Issue still exists in version 10.0.

**Comment by futurehousestore** [comment]
Looks good for me in version 11. The issue can be closed.
![ecm](https://user-images.githubusercontent.com/28427270/75144046-1d2e4c00-56ee-11ea-8e73-088be4682cbe.JPG)
