### ISSUE TITLE
BUG 8.0.0 Thirdparties not showing under /societe/list.php

### ISSUE THREAD

**Issue by JavierNR** [Dolibarr/dolibarr#9299]
# Bug
I've upgraded dolibarr from 7.0.3 to 8.0.0 with no problem so far, but the mail didn't worked (Swiftmailer library throwing errors) So I've updated from PHP5.6 to PHP7.2 and now I have a problem:
The thirdparties aren't showing under /societe/list.php (well, it's showing only 5 thirdparties of 174 recorded on my system)

## Checking steps
Checked database and all the thirdparties are there.
Under Last 5 propale / thirdparties / invoices modified, the thirdparties are appearing and I can enter to his record

I'm seeing under /documents/dolibarr.log the following warning:
Deprecated use of GETPOST, called with 1st param = mode and 2nd param is '', when calling page /societe/list.php

It's possible that the problem comes from here?
Thanks in advance

## Environment
- **Version**: 8.0.0
- **OS**:  Debian GNU/Linux 9.5 (stretch)
- **Web server**:  Apache/2.4.25 (Debian)
- **PHP**: 5.6 upgraded to 7.2
- **Database**: mariadb  Ver 15.1 Distrib 10.1.26-MariaDB

**Comment by eldy** [comment]
Deprecated use of GETPOST, called with 1st param is just a warning.
Check apache error log

**Comment by JavierNR** [comment]
Hello @eldy and thanks for your response. I've checked apache error log but didn't show any problem so far (log level = warn).

I've just checked api explorer and get thirdparties showed the same 5 clients that shows under /societe/list.php , so maybe it's time to check the database to see if something is corrupted.
~~It's possible that the data was deleted during the upgrade? I'll inform you my findings~~

**EDIT**
Checked database table llx_societe and the data is there (329 rows in total).
Also creating a new client from webpage, inserts correctly under llx_societe but not showing under webpage. Do I need to check something more?

Regards

**Comment by eldy** [comment]
Try to upgrade to 8.0.1

**Comment by JavierNR** [comment]
Hello @eldy,

I've investigated further this problem. Yesterday upgraded to dolibarr 8.0.1 and problem persists. 

In order to dig a little bit more I've installed into a new server (VestaCP based) and imported sql data from my production system but still the same problem again.

Checked database table llx_societe and come to conclusion that the thirdparties showing under web or API have fk_stcomm !=0, the rest of the thirdparties have fk_stcomm to 0 and didn't show under web nor rest API. 
I think that some kind of migration didn't perform good (saw no problems when migrating) I've been upgrading the installation from 3.x and never had this problem.

It's safe to modify these rows? I'll wait till your reply before doing anything

Here is a screenshot with my thirdparties showing under web/API marked in yellow.
![thirdparties](https://user-images.githubusercontent.com/1872120/45023791-a142ce80-b037-11e8-943a-ecbb780b8218.PNG)

**Comment by JuanBrillo** [comment]
I'm in the same situation as you, third parties are not shown in either 8.0.0 or 8.0.1, have you managed to fix it? What solution can you give?

**Comment by JavierNR** [comment]
Hello @JuanBrillo I think the error will be solved changing the value of fk_stcomm for each third-party, but I'm waiting for feedback from @eldy because I don't know fk_stcomm means in the system.

**Comment by JuanBrillo** [comment]
I forgot before telling you, but in an installation of 0 (without migrations) it happens as well. It has not been an update problem or you have an error.

**Comment by JuanBrillo** [comment]
I just found that column serves, the functions of that column are in the table "llx_c_stcomm", the problem is that dolibarr creates users with "0" when you look at the records of the given table, the possible values are " -1 "," 1 "," 2 "," 3 "," 4 ". I think the solution could be in, create the value "0" in the database itself, I test it and communicate it. But I hope @eldy takes note of the error for his solution.

--------------------------------------------------
Original en Español

Acabo de encontrar para que sirve esa columna, las funciones de dicha columna estan en la tabla "llx_c_stcomm", el problema es que dolibarr crea usuarios con "0" cuando si te fijas en los registros de la tabla dada, los valores posibles son "-1","1","2","3","4". Creo que la solucion podria estar en, crear el valor "0" en la propia base de datos, lo pruebo y lo comunico. Pero espero que @eldy tome nota del error para su solucion.

**Comment by JavierNR** [comment]
Hello @JuanBrillo @eldy , I've updated to 8.0.2 and problem dissapeared (made no changes to my sql database).

So for me.. problem solved! I'll close the issue in a few days
