### ISSUE TITLE
seperate issues by releases

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#9306]
I think it would be very helpful to seperate the issues (bugs) by dolibarr releases.
Can we reactivate the version labels or the milestones?

With kind regards
Udo
com4WEB.de

**Comment by jtraulle** [comment]
I agree that it would be very helpful.
@VarCI https://var.ci/rules can be very helpful at this task by automatically putting labels based on text pattern matching of the issue. It should be considered as it is free for open source projects

**Comment by eldy** [comment]
version labels are available but it seems github does not allow users to add them without admin privileges

**Comment by jtraulle** [comment]
Thats why I bring @VarCI https://var.ci/rules :wink:

**Comment by librethic-code** [comment]
+1000 
Maybe more admins for the project?

**Comment by librethic-code** [comment]
>  Can we reactivate the version labels or the milestones?

For precision… system hadn't be disable, we just missing @rdoursenaud who did this task .

**Comment by jtraulle** [comment]
It is now possible to automatically assign labels based on Issue template.
See step 7 of https://help.github.com/articles/creating-issue-templates-for-your-repository/
