### ISSUE TITLE
File upload error with filename having two dots

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#9354]
# Bug
When uploading file in Dolibarr system, upload does not work if the filename has two dots. For example if you will upload file having name **example..pdf**, your file will not be uploaded. While in real it should upload file irrespective of the number of dots.

## Environment
- **Version**: [*7.0.3*]
- **OS**: [*CentOS-7.1*]
- **Web server**: [*Apache/2.4.6*]
- **PHP**: [*7.0.26*]
- **Database**: [*MySQL 5.7.22*]
- **URL(s)**: [*Any uploading form*]

## Expected and actual behavior
Dolibarr should able to upload file irrespective of the number of dots(periods) in the file name.

## Steps to reproduce the behavior
Just put two periods before file extension in the filename like **example..zip**. Now you will not be able to upload files.

**Comment by eldy** [comment]
Currently disallowing 2 following dots is done for security purpose.
Opening this feature may also have bad side effects.

**Comment by alsoft10** [comment]
Hi eldy,
Thank you very much for your reply. You are correct. But here is a suggestion for you. For better user experience why don't you remove one dot programmatically? This way user will not notice any error and can upload files seamlessly.

Regards,
H. Sattar

**Comment by eldy** [comment]
Why not

**Comment by dolibarr95** [comment]
Hello
But if the file name is  **example....zip** remove one dot is not sufficient.

**Comment by alsoft10** [comment]
In this case remove all dots silently without user's knowledge and only keep the **final one**. This way we can make the system more user friendly. We have to try to generate less error in the system as much as possible.

**Comment by alsoft10** [comment]
@eldy Did you fixed this problem?
