### ISSUE TITLE
Improvement, Search performance for a supplier order

### ISSUE THREAD

**Issue by McCoy78** [Dolibarr/dolibarr#9369]
# Feature Request
Search performance for a supplier order

## Use case
We notice that the search for a supplier order by its number is extremely slow, both on the production v5.0.4 and the v7.0.3 in test

_More details:_
In the search field, if we indicate the last 4 digits of a supplier order (eg 1234 for CF1603-1234), Dolibarr takes a long time to answer: unsure:
Conversely, the result is immediate for a quote search or a sales order or a customer invoice despite a larger volume.

## Suggested implementation
None

## Suggested steps
Maybe an index is missing or the SQL query should be reviewed.

**Comment by eldy** [comment]
Because the search is not done on the beginning on field, the database can't use the index. However, this is same for sales order.
Howe many supplier and sale order do you have. And what is "slow" ?

**Comment by McCoy78** [comment]
Hi,
We are speaking about 2.5K supplier orders and 4.3K customer invoices.
Concerning time, I would say less than 1s for customers invoices and more that 10 s for supplier orders. Difficult to say precisely since I did not know where to put timestamp in the code.

**Comment by McCoy78** [comment]
Hi,
It looks like this performance issue has been improved on 8.0.2 but the result set is wrong.

Here is two screen shot with 7.0.3 and 8.0.2, same data set and same search: supplier order #2434. The 7.0.3 returns something close. The 8.0.2 returns ... I do not know what ;)
Fast, but wrong ;)

![selection_230](https://user-images.githubusercontent.com/42868712/46064582-089ffa00-c170-11e8-986b-623a4bf1e773.png)
![selection_229](https://user-images.githubusercontent.com/42868712/46064586-0b9aea80-c170-11e8-8a51-6ddf46d898e1.png)

**Comment by McCoy78** [comment]
Hi,
The request is still relevant on version 10.0.4.
With 5K customer orders and 3K supplier orders, it takes about 4 s to fetch a supplier order and more that 20 s for a supplier order using the last 4 digit of the order.

**Comment by eldy** [comment]
I do not experience any trouble with 100 000 suppliers orders. Result take 0.4 s.
Can you describe which version of database you have, memory and OS ?

**Comment by McCoy78** [comment]
Hi Eldy,
Dolibarr version 10.0.4
Database: MySQL 5.5.62-0ubuntu0.14.04.1
Server: Ubuntu 14.04 LTS on OVH Cloud
Memory: 30GB
Note: the Dolibarr Database came for a 3.x version and was upgraded (5.x, 7.x and 10.x)
The strange thing is that query are responding well on the customers tables. Maybe an index problem on our configuration ?
Here is a screen shot of llx_commande_fournisseur indexes:
![Sélection_620](https://user-images.githubusercontent.com/42868712/76602605-91008f00-650b-11ea-9be7-432ede0fe933.png)
