### ISSUE TITLE
Warning with PHP 7.2

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#9371]
# Bug
Using PHP 7.2.x close a session make a warning on php log.

## Environment
- **Version**: 7.0.x, 8.0.x
- **OS**: Windows 10 pro, Ubuntu 16.04LTS
- **Web server**: Apache 2.4.34
- **PHP**: 7.2.9
- **Database**: MariaDB 10.3.9

## Expected and actual behavior
Close a session may made a php warning "session_name(): Cannot change session name when session is active in ...."

# Solution
On file ../htdocs/user/logout.php line 77 change "session_name($sessionname);" by "session_name();"

I don't know if it's a clean solution but it seems working for me.

Greetings,
Sylvain Legrand.

**Comment by eldy** [comment]
can you try to just remove the line session_name(...)
