### ISSUE TITLE
Error DB_ERROR_42803 in Billing | Payment

### ISSUE THREAD

**Issue by JosQuelqu1** [Dolibarr/dolibarr#9377]
# Bug
Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180831214617
Dolibarr: 8.0.0
Level of features: 0
PHP: 7.2.7-0ubuntu0.18.04.2
Server: Apache/2.4.29 (Ubuntu)
OS: Linux lapp 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

Requested URL: /dolibarr/compta/index.php?mainmenu=billing&leftmenu=
Referer: http://10.0.0.7/dolibarr/admin/system/phpinfo.php?mainmenu=home&leftmenu=admintools
Menu manager: eldy_menu.php

Database type manager: pgsql
Latest database access request error: SELECT sum(f.total) as tot_fht, sum(f.total_ttc) as tot_fttc, s.nom as name, s.email, s.rowid as socid, s.code_client, s.code_compta, c.rowid, c.ref, c.facture, c.fk_statut, c.total_ht, c.tva as total_tva, c.total_ttc, cc.rowid as country_id, cc.code as country_code FROM llx_societe as s LEFT JOIN llx_c_country as cc ON cc.rowid = s.fk_pays, llx_commande as c LEFT JOIN llx_element_element as el ON el.fk_source = c.rowid AND el.sourcetype = 'commande' LEFT JOIN llx_facture AS f ON el.fk_target = f.rowid AND el.targettype = 'facture' WHERE c.fk_soc = s.rowid AND c.entity = 1 AND c.fk_statut = 3 AND c.facture = 0 GROUP BY s.nom, s.rowid, s.email, s.code_client, s.code_compta, c.rowid, c.ref, c.facture, c.fk_statut, c.tva, c.total_ht, c.total_ttc
Return code for latest database access request error: DB_ERROR_42803
Information for latest database access request error: ERROR: 42803: column "cc.rowid" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: ...tut, c.total_ht, c.tva as total_tva, c.total_ttc, cc.rowid a...\n ^\nLOCATION: check_ungrouped_columns_walker, parse_agg.c:1369

## Environment
- **Version**: 8.0.0
- **OS**: Ubuntu Server 18.04 LTS 64-bit
- **Web server**: Apache v2.4.29
- **PHP**: v7.2.7
- **Database**: PostgreSQL 10.5
- **URL(s)**: /dolibarr/compta/index.php?mainmenu=billing&leftmenu=

## Steps to reproduce the behavior
Go to "Billing | Payment". The error sits under "Social/fiscal taxes to pay".

**Comment by eldy** [comment]
Fixed by 9e8485c2794fa44edb52113ba2ee5bc9fa6d80a5

**Comment by JosQuelqu1** [comment]
Thank you!
