### ISSUE TITLE
Error when try to send to email supplier invoice

### ISSUE THREAD

**Issue by JosQuelqu1** [Dolibarr/dolibarr#9378]
# Bug
Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180831214856
Dolibarr: 8.0.0
Level of features: 0
PHP: 7.2.7-0ubuntu0.18.04.2
Server: Apache/2.4.29 (Ubuntu)
OS: Linux lapp 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

Requested URL: /dolibarr/fourn/facture/card.php?id=1&action=presend&mode=init
Referer: http://10.0.0.7/dolibarr/fourn/facture/card.php?facid=1&save_lastsearch_values=1
Menu manager: eldy_menu.php

Database type manager: pgsql
Latest database access request error: No request in error
Return code for latest database access request error: No request in error
Information for latest database access request error: No request in error

## Environment
- **Version**: 8.0.0
- **OS**: Ubuntu Server 18.04 LTS 64-bit
- **Web server**: Apache v2.4.29
- **PHP**: v7.2.7
- **URL(s)**: /dolibarr/fourn/facture/card.php?id=1&action=presend&mode=init

## Steps to reproduce the behavior
Open a supplier invoice (paid or not) and click on "Send Email".

**Comment by JosQuelqu1** [comment]
Edit: Open a supplier invoice (paid or not) and click on "Send Email".

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by Telemakfr** [comment]
I have tested with 8.0.1 and the problem still exist.

**Comment by eldy** [comment]
I can't reproduce. Do you have trouble on demo.dolibarr.org ?

**Comment by Telemakfr** [comment]
Not present on demo.dolibarr.org. But still present on my install after 8.0.1 update. Nothing is showing in e-mail canvas.

![capture](https://user-images.githubusercontent.com/35594351/45021501-0693c100-b032-11e8-9a46-a47242710255.PNG)

**Comment by Telemakfr** [comment]
I'm searching for activate debug mode to send you more precise infos.

**Comment by Telemakfr** [comment]
SOLVED !
Incompatibility with the customfield module. Just removed it and e-mail canvas is visible.

**Comment by JosQuelqu1** [comment]
I have the same error after 8.0.1 upgrade + I had this error when upgrading:


Choix du script de migration | 7.0.0-8.0.0.sql
-- | --
Request 1 sql='ALTER TABLE llx_c_ziptown DROP FOREIGN KEY fk_c_ziptown_fk_pays;'
Request 2 sql='ALTER TABLE llx_c_ziptown ADD  CONSTRAINT fk_c_ziptown_fk_pays FOREIGN KEY (fk_pays) REFERENCES  llx_c_country(rowid);'
... 

https://github.com/Dolibarr/dolibarr/issues/9408

**Comment by JosQuelqu1** [comment]
> 
> 
> SOLVED !
> Incompatibility with the customfield module. Just removed it and e-mail canvas is visible.

What do you mean? Sill got this issue with 8.0.2.

**Comment by JosQuelqu1** [comment]
Still there in 8.0.4

**Comment by eoxia-jimmy** [comment]
Same on 9.0.0

**Comment by JosQuelqu1** [comment]
Works in 9.0.3
