### ISSUE TITLE
[Feature?] Can't create credit invoice for refund of deposit/garantee

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#9393]
# Bug
I need to make an invoice to reimburse an old deposit for which the invoice is not in Dolibarr.

The customer made a deposit as a garantee which is now refundedwith a final note.
hecked in version 8.0.1 (and 4.0.2).

# Observed limitations:
- Dolibarr does not allow the creation of a credit invoice without referring to a previous invoice.
- When creating a standard invoice, a negative line can be added only after adding a positive line and then modifying the line to change the amount to the negative value.
- A negative invoice can not be validated.
- Version 8.0.1 has a side effect: it proposes to convert the "extra payed amount" to a credit before validating the invoice (to try: create invoice with negative line, extra button appears below).  It then allows the creation of a credit invoice for the non confirmed invoice.

Image 1: proposal to convert the "extra payed amount (trop-perçu)":
![image](https://user-images.githubusercontent.com/1504752/44958873-4b124600-aee6-11e8-9e9b-0156bab14b91.png)

Image 2: Create credit invoice for unconfirmed invoice:
![image](https://user-images.githubusercontent.com/1504752/44958881-7a28b780-aee6-11e8-8600-b9aeff1ad52d.png)

Image 3: Unconfirmed invoice proposed for credit invoice:
![image](https://user-images.githubusercontent.com/1504752/44958897-f4f1d280-aee6-11e8-8ed1-f84a5f31472b.png)

# Preferred behaviour
- Allow the creation of a credit invoice without referring to a previous invoice - preferably with a warning popup.
- Or, allow the creation of an invoice the is negative (with a warning popup to alert about the special case).

# Request
Is there a workaround for the existing versions (global setting or other solution?)

**Comment by eldy** [comment]
With 8.0, it is not more possible to add a negative line. If you need so, juste create a discount and apply it to invoice.
Also it is not possible to create a credit note without referring source invoice because it is a legal requirement.
In your case, because original invoice is into another system, best is to make credit note into old system.
If you can't, you can try to add option FACTURE_ENABLE_NEGATIVE_LINES to 1 so you should be able to create negative line.
