### ISSUE TITLE
Fatal error 8.0.1

### ISSUE THREAD

**Issue by SylvainLegrand** [Dolibarr/dolibarr#9397]
# Bug
Backup function, database tools function, ...  doesn't work anymore.

## Environment
- **Version**: 8.0.1

## Steps to reproduce the behavior
Impossible to start an export or a backup.
Every file with "$db::LABEL" may make a error like "Uncaught Error: Undefined class constant 'LABEL' in ... "

**Comment by eldy** [comment]
Which version of PHP do you have ?

**Comment by SylvainLegrand** [comment]
Same configuration and web server as for Dolibarr 8.0.0
- PHP 7.2.9.
- MariaDB 10.3.9
- Apache 2.4.34
- OS Windows 10 pro 64bits
- Environnement Wamp 3.1.3 custom

With Dolibarr 8.0.0 = OK
With Dolibarr 8.0.1 = KO

**Comment by SylvainLegrand** [comment]
I found enough time to do more tests:

The first time, I applied the version by copying the new files in my Dolibarr folder (by overwriting old ones).

today I tested another method:

1. Sauvegrade of the original database (v8.0.0)
2. Deleting files
3. Copy new files
4. Starting Dolibarr to start the installation
5. After a new installation and a first boot without problems:
6. Deleting data from the database and then restoring the previous backup.
7. At the launch of Dolibarr an update is proposed.
8. At the end of the update procedure everything works fine!

I hope this may help someone's.

Greetings,
Sylvain Legrand

**Comment by papoteur-mga** [comment]
Hello,
I confirm the bug.
V8.0.1
Setup - Administration - Restore
I get in php logs:
PHP Fatal error:  Undefined class constant 'LABEL' in /var/www/html/dolibarr-test/htdocs/admin/tools/dolibarr_import.php on line 41, referer: http://localhost/dolibarr-test/htdocs/admin/tools/index.php?mainmenu=home&leftmenu=admintools

**Comment by atm-maxime** [comment]
Ok I found were this comes from. I had the same trouble and when I did a var_dump of the $db object, I found out that it's not a DoliDBMysqli object but a TraceableDB object. I suspect that the debugbar module overloads the $db object so it can trace all sql request done...
Unactivate debugbar and it's back to normal.
