### ISSUE TITLE
Bug: Using French version. When setting up a Tiers, it wzas earlier possible to serch department on number. So for Seine-etMarne I coudl just write 77  and the department turned up. In 8.0.1 that is not possible, I can only search on name and not on department number, I must write Seine et Marne

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#9403]
# Bug

## Environment
- **Version**: 8.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.25
- **PHP**: apache2handler 7.0.30-0+deb9u1
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL**: /azerty/htdocs/societe/card.php?action=create&leftmenu=

**Comment by eldy** [comment]
You can go into home - setup - other and add constant
MAIN_SHOW_STATE_CODE to 1
to hae number in combo list

**Comment by hasse-basse** [comment]
Great, worked fine, thanks.
