### ISSUE TITLE
Expenses reports TAX 2 and TAX 3 not showing

### ISSUE THREAD

**Issue by dipen10** [Dolibarr/dolibarr#9406]
Hey guys,

I hav enabled the TAX 2 and TAX 3. I can able to map the VAT account ( CGST and SGST) . But in  Expenses report card there is no TAX 2 and TAX 3 columns. 

Any idea to bring it up??

**Comment by eldy** [comment]
Do you have tax 2 and 3 information visible on invoices, or sale order or quotation ?

**Comment by dipen10** [comment]
yes it will show the tax 2 and tax 3 information on invoices.
![screenshot of customer invoice - card](https://user-images.githubusercontent.com/2733066/45049760-3af09700-b09d-11e8-83e5-092ff0d0a440.jpg)

**Comment by dipen10** [comment]
Hey Eldy

Any update on this??
