### ISSUE TITLE
Bug : Stock list ignores number of decimals settings

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#9415]
# Bug

On the stock page `product/reassort.php`, the real stock is displayed with an arbitrary number of decimals ignoring the main setting on decimals.

## Environment
- **Version**: 7.0.1 and up
- **OS**: Debian 9
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: 7.0.30-0+deb9u1
- **Database**: Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- **URL(s)**: product/reassort.php

## Expected and actual behavior

The stock should be displayed with a number of decimals less or equal to the one set on the display settings.

## Steps to reproduce the behavior

1. Set the number of decimals digits in display settings
2. Set the stock of a product to a number with a higher number of decimals
3. Got to product/reassort.php, the stock is not rounded

## Probable solution

There is an extract from product/reassort.php :

```php
$objp = $db->fetch_object($resql);
...
$product=new Product($db);
$product->fetch($objp->rowid);
$product->load_stock();
...
if ($objp->seuil_stock_alerte != '' && ($objp->stock_physique < $objp->seuil_stock_alerte)) print img_warning($langs->trans("StockTooLow")).' ';
print $objp->stock_physique;
```

We can see that `$objp` is the object representing the sql answer, while
`$product` is a Dolibarr product object.  Using `$product->stock_reel` instead
of `$objp->stock_physique` fixes the issue for me.

I guess that we should use `$product` for the whole page

**Comment by eldy** [comment]
$product->stock_reel and $objp->stock_physique should have same value.
What do you have in both field ?

**Comment by dbeniamine** [comment]
the same number but the first one is rounded at 3 digits as required by my settings, while the second one is not.

My guess is that either `fetch` or `load_stock` does the rounding or calls a function that does it ...
