### ISSUE TITLE
Bug: URGENT Impossible to visualize third parties in the lists, impossible to work.

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#9417]
# Bug

## Environment
- **Version**: 8.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: apache2handler 5.5.14
- **Database**: MySQL or MariaDB 5.5.5-10.0.32-MariaDB
- **URL**: /dolibarrBRILLO/htdocs/societe/list.php?leftmenu=thirdparties

## Report
I find that in Dolibarr 8.0.1 (also in the previous version) I can not see in the third-party lists NOTHING, I do not see any clients, potentials, or suppliers, you can not see anything. Neither have or not assigned a commercial ...

It is impossible to work, because even if you look for a specific client in ANY SEARCH FIELD (sidebar or the fields of the list) the result is always the same, nothing appears.

Since it is a problem of extreme gravity (since it prevents working in any way) I beg you to give an urgent solution to this error.

a greeting

------------------------------------------
Original en español
Me encuentro con que en Dolibarr 8.0.1 (tambien en la versión anterior) no puedo visualizar en los listados de terceros NADA, no me aparecen ni clientes, ni potenciales, ni proveedores, no se ve nada. Ni tengan o no asignado un comercial...

Resulta imposible trabajar, ya que aunque busques un cliente especifico en CUALQUIER CAMPO DE BUSQUEDA (barra lateral o los campos del listado) el resultado siempre es el mismo, no aparece nada.

Dado que es un problema de extrema gravedad (ya que impide trabajar de cualquier forma) ruego den una solucion urgente a dicho error.

Un saludo

**Comment by eldy** [comment]
Can you provide a screenshot of the list of thirdparties ?
And also on the section "Third Parties" of permissions of the used user.

**Comment by JuanBrillo** [comment]
Of course, no problem, thanks for the speed.

Also, comment, that the same thing happens to me in another installation of Dolibarr 8.0.0 (which I have for testing) in another completely different computer, and on the permissions, it is also in addition to the SuperAdmin (evidently, with all the permissions). It also occurs with normal users who have been given the necessary permissions.

------------------------------------------------------------------
Original en Español
Por supuesto, ningun problema, gracias por la rapidez.

Igualmente, comentarte, que me ocurre lo mismo en otra instalacion de Dolibarr 8.0.0 (que tengo para pruebas) en otro computador completamente diferente, y sobre los permisos, se trata ademas del SuperAdmin (evidentemente, con todos los permisos). Tambien ocurre con los usuarios normales a los que se ha dado los permisos necesarios.

![user permissions](https://user-images.githubusercontent.com/23519523/45095224-db869b80-b11d-11e8-8162-effeb0ebd81f.png)
![thirds bug](https://user-images.githubusercontent.com/23519523/45095225-db869b80-b11d-11e8-9198-b9c1a0f51c8d.png)

**Comment by eldy** [comment]
Can you retry the screenshot without the filter "Activo" on.
If it is still empty, check into your apache error log file.

**Comment by JuanBrillo** [comment]
I've done what you said, and it's the same. I have searched the error.log of apache, and I have not been able to see any incidence, to make sure, I have deleted all the lines of both the access.log, and the error.log of apache, to go to dolibarr and click on the list, once again I have visited the log, and the access shows that dolibarr has been accessed, and the actions that I have made. However, the apache error.log has not shown ANY incidence or error.

I have activated the dolibarr.log to see if it shows something, I attached it, in case I could see something that would solve this problem.

In it you can see the warning 

> Deprecated use of GETPOST, called with 1st param = mode and 2nd param is", when calling page /dolibarrBRILLO/htdocs/societe/list.php

--------------------------------------------------------
Original Español
He echo lo que has dicho, y sigue igual. He buscado en el error.log de apache, y no he podido ver ninguna incidencia, para asegurarme, he borrado todas las lineas tanto del access.log, como del error.log de apache,  para ir a continuacion a dolibarr y hacer click en el listado, una vez mas he vuesto al log, y el de acceso muestra que efectivamente se ha accedido a dolibarr, y las acciones que he efectuado. Sin embargo, el error.log de apache no ha mostrado NINGUNA incidencia ni error.

He activado el dolibarr.log para ver si muestra algo, se lo adjunto, por si pudiera ver algo que sirviera para resolver este problema.

En el se puede observar la advertencia "Deprecated use of GETPOST, called with 1st param = mode and 2nd param is '', when calling page /dolibarrBRILLO/htdocs/societe/list.php"

![thirds bug01](https://user-images.githubusercontent.com/23519523/45101274-66ba5e00-b12b-11e8-9925-871259827257.png)

[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/2353306/dolibarr.log)

**Comment by eapcorreo** [comment]
Hi, perhaps a user grant issue. (Español: Quiza un tema de permisos del 
usuario)

**Comment by JuanBrillo** [comment]
No, I have done it from a normal user and also from SuperAdmin (with all the permissions evidently)

------------------------------------
Original en Español

No, lo he hecho desde un usuario normal y tambien desde SuperAdmin (con todos los permisos obviamente).

**Comment by JuanBrillo** [comment]
I just found that column serves, the functions of that column are in the table "llx_c_stcomm", the problem is that dolibarr creates users with "0" when you look at the records of the given table, the possible values are " -1 "," 1 "," 2 "," 3 "," 4 ". I think the solution could be in, create the value "0" in the database itself, I test it and communicate it. But I hope @eldy takes note of the error for his solution.

--------------------------------------------------
Original en Español

Acabo de encontrar para que sirve esa columna, las funciones de dicha columna estan en la tabla "llx_c_stcomm", el problema es que dolibarr crea usuarios con "0" cuando si te fijas en los registros de la tabla dada, los valores posibles son "-1","1","2","3","4". Creo que la solucion podria estar en, crear el valor "0" en la propia base de datos, lo pruebo y lo comunico. Pero espero que @eldy tome nota del error para su solucion.

**Comment by eldy** [comment]
I pushed a change in 8.0.2 to have a left join instead of inner join so content of llx_c_stcomm will have no effect even if empty.
I recommend however to keep this entry in table
insert into llx_c_stcomm (id,code,libelle) values ( 0, 'ST_NEVER', 'Never contacted');

**Comment by eldy** [comment]
Fixed by ff05997f0aee0f13092f41e006399ac26a2c1198
