### ISSUE TITLE
[8.0.1] Unable to validate supplier credit note

### ISSUE THREAD

**Issue by hedii** [Dolibarr/dolibarr#9422]
# Bug
Unable to validate supplier credit note. Same as closed issue #8293

## Environment
- **Version**: 8.0.1
- **OS**: Linux sites1 4.9.0-7-amd64 # 1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64
- **Web server**: nginx/1.15.3
- **PHP**: 7.2.9-1+0~20180901081133.4+stretch~1.gbpdaac35
- **Database**: MySQL or MariaDB 5.5.5-10.2.17-MariaDB-10.2.17+maria~stretch-log
- **URL(s)**: /fourn/facture/card.php?id=137&action=confirm_valid&confirm=yes

## Expected and actual behavior
expected : A supplier credit is created
actual : I get the error `Duplicate entry '1' for key 'uk_facture_fourn_ref'`

## Steps to reproduce the behavior
Create a supplier credit note and validate.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
<img width="2671" alt="capture d ecran 2018-09-06 a 10 40 59" src="https://user-images.githubusercontent.com/5358048/45146317-ef380d80-b1c2-11e8-8fca-7a9ec4fe578b.png">
<img width="2388" alt="capture d ecran 2018-09-06 a 10 43 27" src="https://user-images.githubusercontent.com/5358048/45146318-ef380d80-b1c2-11e8-98f5-dac803f5bf7d.png">

**Comment by atm-maxime** [comment]
I reproduced it, but it comes from your setup. Can you check in your setup if the numbering system for supplier invoices is correctly set ? I think you are with "tulip" numbering system but didn't set a mask for credit notes.

**Comment by hedii** [comment]
@atm-maxime supplier invoice: SI{yy}{mm}{dd}{000}

There is no credit notes mask setting in the supplier module configuration.

And in the invoice module (the only one where there is a setting for credit notes), i have these settings:

<img width="936" alt="Capture d’écran 2019-03-16 à 15 56 07" src="https://user-images.githubusercontent.com/5358048/54477035-16236c00-4804-11e9-88cb-bd2558aac5f8.png">

**Comment by atm-maxime** [comment]
Sorry but if you are on the 8.0 version, there's a credit note mask setting, go on the supplier invoice tab and you'll find this :
![image](https://user-images.githubusercontent.com/2097773/54477843-fd1eb900-480b-11e9-85aa-4aace5e04b8c.png)

**Comment by hedii** [comment]
Well, I don't have these options on this page (dolibarr 8.0.2, initial version 6.0.0):

<img width="1580" alt="Capture d’écran 2019-03-16 à 17 00 53" src="https://user-images.githubusercontent.com/5358048/54477940-34419a00-480d-11e9-8836-cf099aab5a22.png">

**Comment by atm-maxime** [comment]
I double checkded this point and I confirm that in 8.0 you should have this setup available. So I think there has been an issue during your upgrade, but that's definitely not an issue from the code. Try to compare the page /admin/supplier_invoice.php from your installation and from a 8.0 package, you should se you don't have the correct file.
