### ISSUE TITLE
Proposal not showing non-predefined Product description

### ISSUE THREAD

**Issue by mwelters** [Dolibarr/dolibarr#9424]
# Bug
Proposal: non pre-defined Products (i.e. free-text Products) not showing description in Proposal Card

## Environment
- **Version**: 8.0.1
- **OS**: Linux
- **Web server**: apache2
- **PHP**: 7.2.9-1
- **Database**: MySql or 10.1.26-MariaDB-0+deb9u1 - Debian 9.1
- **URL(s)**: /comm/propal/card.php?id=23&save_lastsearch_values=1

## Expected and actual behavior
Should show Product Description. Shows only amount and price
I think the Error popped up within the last weeks. 

## Steps to reproduce the behavior
Create new Proposal, Add non-predefined Product

## [Attached files]
![image](https://user-images.githubusercontent.com/11374733/45152810-5c9f6a80-b1d2-11e8-9549-b071b19ef0b4.png)

**Comment by atm-maxime** [comment]
You are on the 9 alpha version according to your screenshot, not 8.0. Can you check that and tell us ?

**Comment by mwelters** [comment]
Yes, I am on alpha i.e. branch develop.
Error still exists in Sunday pulled source.
