### ISSUE TITLE
Bug: sending email trough SMTP exchange

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#9426]
# Bug
Ran into problems sending Mail. Response: 501 5.5.4 Invalid domain name Error

## Environment
- ALL versions

## Steps to reproduce the behavior
use of an OVH exchange mail server to send email (ex.mail.ovh.net)

## Community discutions 
https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/59285-dolibarr-5-et-email-smpt-exchange?limitstart=0#92028

A beginning of bug is quoted around the "ELHO servername " message that should not contain a final space.
**Do you have face this bug or have an idea where i can look at to solve it out ?**

Other web CMS doesn't have this issue, only Dolibarr. We need to sort it out, many of us use those kind of email accounts.

**Comment by laudeco** [comment]
That's my configuration on an OVH server ...

Méthode d'envoi des emails | SMTP/SMTPS socket library
-- | --
Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: localhost) | ssl0.ovh.net
Port du serveur SMTP/SMTPS (Par défaut dans php.ini: 25) | 465
Identifiant d'authentification SMTP si authentification SMTP requise | e-mail address created in the OVH panel
Mot de passe d'authentification SMTP si authentification SMTP requise | password defined for the e-mail
Utilisation du chiffrement TLS (SSL) | Oui
Utiliser le cryptage TTS (STARTTLS) | Non

**Comment by laudeco** [comment]
Config I'm using with an OVH sever. First you have to create an e-mail in the OVH admin panel.

Méthode d'envoi des emails | SMTP/SMTPS socket library
Nom d'hôte ou adresse IP du serveur SMTP/SMTPS (Par défaut dans php.ini: localhost) | ssl0.ovh.net
Port du serveur SMTP/SMTPS (Par défaut dans php.ini: 25) | 465
Identifiant d'authentification SMTP si authentification SMTP requise | Create e-mail address
Mot de passe d'authentification SMTP si authentification SMTP requise | password of the e-mail address
Utilisation du chiffrement TLS (SSL) | Oui
Utiliser le cryptage TTS (STARTTLS) | Non

**Comment by homer8173** [comment]
your email account is a standard OVH , not an OVH exchange ? right ?

**Comment by atm-maxime** [comment]
No news, I close the issue
