### ISSUE TITLE
Error with report by month sales tax 2

### ISSUE THREAD

**Issue by JosQuelqu1** [Dolibarr/dolibarr#9428]
# Bug

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180906190650
Dolibarr: 8.0.0
Level of features: 0
PHP: 7.2.7-0ubuntu0.18.04.2
Server: Apache/2.4.29 (Ubuntu)
OS: Linux lapp 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

Requested URL: /dolibarr/compta/localtax/quadri_detail.php?leftmenu=tax_vat&month=9&year=2018
Referer: http://10.0.0.7/dolibarr/compta/localtax/index.php?leftmenu=tax_1_vat&localTaxType=1
Menu manager: eldy_menu.php

Database type manager: pgsql
Latest database access request error: SELECT d.rowid, d.product_type as dtype, d.fk_facture as facid, d.localtax_tx as rate, d.total_ht as total_ht, d.total_ttc as total_ttc, d.total_tva as total_vat, d.description as descr, d.total_localtax1 as total_localtax1, d.total_localtax2 as total_localtax2, d.date_start as date_start, d.date_end as date_end, f.facnumber as facnum, f.type, f.total_ttc as ftotal_ttc, f.datef, s.nom as company_name, s.rowid as company_id, p.rowid as pid, p.ref as pref, p.fk_product_type as ptype, 0 as payment_id, 0 as payment_amount FROM llx_facture as f, llx_societe as s, llx_facturedet as d LEFT JOIN llx_product as p on d.fk_product = p.rowid WHERE f.entity = 1 AND f.fk_statut in (1,2) AND f.type IN (0,1,2,3,5) AND f.rowid = d.fk_facture AND s.rowid = f.fk_soc AND f.datef >= '2018-09-01 00:00:00' AND f.datef <= '2018-09-30 23:59:59' AND (d.product_type = 0 AND d.date_start is null AND d.date_end IS NULL) AND (d.localtax_tx <> 0 OR d.total_tva <> 0) ORDER BY d.rowid, d.fk_facture
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: ERROR: 42703: column d.localtax_tx does not exist\nLINE 1: ..., d.product_type as dtype, d.fk_facture as facid, d.localtax...\n ^\nHINT: Perhaps you meant to reference the column "d.localtax1_tx" or the column "d.localtax2_tx".\nLOCATION: errorMissingColumn, parse_relation.c:3311

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180906190650
Dolibarr: 8.0.0
Level of features: 0
PHP: 7.2.7-0ubuntu0.18.04.2
Server: Apache/2.4.29 (Ubuntu)
OS: Linux lapp 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

Requested URL: /dolibarr/compta/localtax/quadri_detail.php?leftmenu=tax_vat&month=9&year=2018
Referer: http://10.0.0.7/dolibarr/compta/localtax/index.php?leftmenu=tax_1_vat&localTaxType=1
Menu manager: eldy_menu.php

Database type manager: pgsql
Latest database access request error: SELECT d.rowid, d.product_type as dtype, d.fk_facture_fourn as facid, d.localtax_tx as rate, d.total_ht as total_ht, d.total_ttc as total_ttc, d.tva as total_vat, d.description as descr, d.total_localtax1 as total_localtax1, d.total_localtax2 as total_localtax2, d.date_start as date_start, d.date_end as date_end, f.ref as facnum, f.type, f.total_ttc as ftotal_ttc, f.datef, s.nom as company_name, s.rowid as company_id, p.rowid as pid, p.ref as pref, p.fk_product_type as ptype, 0 as payment_id, 0 as payment_amount FROM llx_facture_fourn as f, llx_societe as s, llx_facture_fourn_det as d LEFT JOIN llx_product as p on d.fk_product = p.rowid WHERE f.entity = 1 AND f.fk_statut in (1,2) AND f.type IN (0,1,2,3,5) AND f.rowid = d.fk_facture_fourn AND s.rowid = f.fk_soc AND f.datef >= '2018-09-01 00:00:00' AND f.datef <= '2018-09-30 23:59:59' AND (d.product_type = 0 AND d.date_start is null AND d.date_end IS NULL) AND (d.localtax_tx <> 0 OR d.tva <> 0) ORDER BY d.rowid, d.fk_facture_fourn
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: ERROR: 42703: column d.localtax_tx does not exist\nLINE 1: ...oduct_type as dtype, d.fk_facture_fourn as facid, d.localtax...\n ^\nHINT: Perhaps you meant to reference the column "d.localtax1_tx" or the column "d.localtax2_tx".\nLOCATION: errorMissingColumn, parse_relation.c:3311

## Environment
- **Version**: 8.0.0
- **OS**: Ubuntu Server 18.04 LTS 64-bit
- **Web server**: Apache v2.4.29
- **PHP**: v7.2.7
- **Database**: PostgeSQL v10.5

## Steps to reproduce the behavior
Click on "Billing | Payment". Under Special expenses click "Sales tax 2" and "Report by month". Select a month.

**Comment by JosQuelqu1** [comment]
Still have the issue with 8.0.2

**Comment by JosQuelqu1** [comment]
Still have the issue with 8.0.4

**Comment by JosQuelqu1** [comment]
I just noticed. It's saying "report tax 3". I don't have tax 3 and it should be tax 2.

**Comment by JosQuelqu1** [comment]
Still there in 9,0,3

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20190526000715
Dolibarr: 9.0.3
Level of features: 0
PHP: 7.2.17-0ubuntu0.18.04.1
Server: Apache/2.4.29 (Ubuntu)
OS: Linux lapp 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

Requested URL: /dolibarr/compta/localtax/quadri_detail.php?leftmenu=tax_vat&month=3&year=2019
Referer: http://10.0.0.7/dolibarr/compta/localtax/index.php?leftmenu=tax_1_vat&localTaxType=1
Menu manager: eldy_menu.php

Database type manager: pgsql
Latest database access request error: SELECT d.rowid, d.product_type as dtype, d.fk_facture as facid, d.localtax_tx as rate, d.total_ht as total_ht, d.total_ttc as total_ttc, d.total_tva as total_vat, d.description as descr, d.total_localtax1 as total_localtax1, d.total_localtax2 as total_localtax2, d.date_start as date_start, d.date_end as date_end, f.facnumber as facnum, f.type, f.total_ttc as ftotal_ttc, f.datef, s.nom as company_name, s.rowid as company_id, p.rowid as pid, p.ref as pref, p.fk_product_type as ptype, 0 as payment_id, 0 as payment_amount FROM llx_facture as f, llx_societe as s, llx_facturedet as d LEFT JOIN llx_product as p on d.fk_product = p.rowid WHERE f.entity = 1 AND f.fk_statut in (1,2) AND f.type IN (0,1,2,3,5) AND f.rowid = d.fk_facture AND s.rowid = f.fk_soc AND f.datef >= '2019-03-01 00:00:00' AND f.datef <= '2019-03-31 23:59:59' AND (d.product_type = 0 AND d.date_start is null AND d.date_end IS NULL) AND (d.localtax_tx <> 0 OR d.total_tva <> 0) ORDER BY d.rowid, d.fk_facture
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: ERROR: 42703: column d.localtax_tx does not exist\nLINE 1: ..., d.product_type as dtype, d.fk_facture as facid, d.localtax...\n ^\nHINT: Perhaps you meant to reference the column "d.localtax1_tx" or the column "d.localtax2_tx".\nLOCATION: errorMissingColumn, parse_relation.c:3311

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20190526000715
Dolibarr: 9.0.3
Level of features: 0
PHP: 7.2.17-0ubuntu0.18.04.1
Server: Apache/2.4.29 (Ubuntu)
OS: Linux lapp 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

Requested URL: /dolibarr/compta/localtax/quadri_detail.php?leftmenu=tax_vat&month=3&year=2019
Referer: http://10.0.0.7/dolibarr/compta/localtax/index.php?leftmenu=tax_1_vat&localTaxType=1
Menu manager: eldy_menu.php

Database type manager: pgsql
Latest database access request error: SELECT d.rowid, d.product_type as dtype, d.fk_facture_fourn as facid, d.localtax_tx as rate, d.total_ht as total_ht, d.total_ttc as total_ttc, d.tva as total_vat, d.description as descr, d.total_localtax1 as total_localtax1, d.total_localtax2 as total_localtax2, d.date_start as date_start, d.date_end as date_end, f.ref as facnum, f.type, f.total_ttc as ftotal_ttc, f.datef, s.nom as company_name, s.rowid as company_id, p.rowid as pid, p.ref as pref, p.fk_product_type as ptype, 0 as payment_id, 0 as payment_amount FROM llx_facture_fourn as f, llx_societe as s, llx_facture_fourn_det as d LEFT JOIN llx_product as p on d.fk_product = p.rowid WHERE f.entity = 1 AND f.fk_statut in (1,2) AND f.type IN (0,1,2,3,5) AND f.rowid = d.fk_facture_fourn AND s.rowid = f.fk_soc AND f.datef >= '2019-03-01 00:00:00' AND f.datef <= '2019-03-31 23:59:59' AND (d.product_type = 0 AND d.date_start is null AND d.date_end IS NULL) AND (d.localtax_tx <> 0 OR d.tva <> 0) ORDER BY d.rowid, d.fk_facture_fourn
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: ERROR: 42703: column d.localtax_tx does not exist\nLINE 1: ...oduct_type as dtype, d.fk_facture_fourn as facid, d.localtax...\n ^\nHINT: Perhaps you meant to reference the column "d.localtax1_tx" or the column "d.localtax2_tx".\nLOCATION: errorMissingColumn, parse_relation.c:3311

**Comment by JosQuelqu1** [comment]
Still there in 10.0.0

**Comment by JosQuelqu1** [comment]
Still ther in 10.0.1

**Comment by dgfmdrv** [comment]
Hello, We are using v10.0.3.
I found this bug when I click on a month or subtotal under "Financiera->Pagos especiales->IRPF->Informe por mes" (I think it's the same option: Billing->payment->Sales tax 2)
![image](https://user-images.githubusercontent.com/1451834/67899960-a9c36600-fb63-11e9-86eb-f429c2dd303b.png)

When I click on "Enero 2019" and change the url from:
```
/compta/localtax/quadri_detail.php?leftmenu=tax_vat&q=3&year=2019
```
to
```
/compta/localtax/quadri_detail.php?leftmenu=tax_2_vat&q=3&year=2019&localTaxType=2
```

Or when I clic on "Subtotal" and change url from
```
/compta/localtax/quadri_detail.php?leftmenu=tax_vat&month=1&year=2019
```
to
```
/compta/localtax/quadri_detail.php?leftmenu=tax_2_vat&month=1&year=2019&localTaxType=2 
```

The error disappears and lists something but it doesn't show quantities and total, but items look fine:
![image](https://user-images.githubusercontent.com/1451834/67900515-eb084580-fb64-11e9-8216-e643854bb019.png)

**Comment by ksar-ksar** [comment]
Hi,

Still relevant on V13 ?

**Comment by JosQuelqu1** [comment]
hi,

yes still there

I get this message 
Parameter localTaxType is missing

**Comment by ckibodeaux** [comment]
This is present in 16.0 beta.

**Comment by xasser** [comment]
still the same in 17.0.2
attached 

![Screenshot 2023-08-06 at 8 55 21 PM copy](https://github.com/Dolibarr/dolibarr/assets/5375179/25838573-9ed5-420b-a0ce-5e7bfb28483a)
![Screenshot 2023-08-06 at 8 55 58 PM copy](https://github.com/Dolibarr/dolibarr/assets/5375179/04d62dfb-276f-45cf-90c1-e879739b081a)

**Comment by elperepat** [comment]
Still there in 19.01

In compta/localtax/index.php, replace line 450 with:

`print '<td class="nowrap"><a href="'.DOL_URL_ROOT.'/compta/localtax/quadri_detail.php?leftmenu=tax_vat&month='.$m.'&year='.$y.'&localTaxType='.$localTaxType.'">'.dol_print_date(dol_mktime(0, 0, 0, $m, 1, $y), "%b %Y").'</a></td>';`

Patrick

**Comment by diogos88** [comment]
Is there a fix for this problem?

**Comment by esaumell** [comment]
Still there in 19.0.4 and 20.0.2

![image](https://github.com/user-attachments/assets/e3f23be3-2b5e-4915-badb-aa93787d3491)

@diogos88 @elperepat code seems to fix the problem
