### ISSUE TITLE
[Bug] Shipment Creation Failure if Module has Extrafields (8.0.1)

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#9431]
# Bug
Required Extrafields (Complementary Attributes) of the Shipment Module prevent a new shipment to be generated, since the field's completion is not performed in the first step but only in the detailed shipment attributes of the second section (shipment card), whose access is denied.

## Environment
- **Version**: 8.0.1
- **OS**: Linux 3.10.105 #23739 SMP Tue Jul 10 00:15:23 CST 2018 x86_64
- **Web server**: Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141
- **PHP**: 5.6.36
- **Database**: MySQL or MariaDB 5.5.59-MariaDB
- **URL(s)**: /dolibarr/htdocs/expedition/shipment.php

**Comment by fmarcet** [comment]
This bug was solved in 8.0.2 with this pull request #9413
