### ISSUE TITLE
[7.0.3] empty array_options in json on order lines

### ISSUE THREAD

**Issue by oandradesanchez** [Dolibarr/dolibarr#9434]
# Bug
When an extra field is added on order line, the respective array_options array is empty in json when calling REST api

## Environment
- **Version**: 7.0.3, 8.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7
- **Database**: MariaDB

## Expected and actual behavior
Expected : Hope i have my extra field in the array_options json array to be able to use it in my angular app.
Actual : the array_options is empty.

## Steps to reproduce the behavior
Add an extra field (text for instance) on order line. Create an order, add a line and put a value in the extra field. Call the /orders/ rest api in api explorer. The field array_optins is empty.

**Comment by rovervt** [comment]
I have the same problem. It fails posting a new order line with array_options filled, giving this error: Bad Request: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) VALUES (5,'')' at line 1. Please fix this.

**Comment by oandradesanchez** [comment]
fix in 7.0
