### ISSUE TITLE
POST /invoices REST API endpoint fails when lines array does not contain a product_type

### ISSUE THREAD

**Issue by jtraulle** [Dolibarr/dolibarr#9435]
# Bug
`POST /invoices` REST API endpoint fails when `lines` array does not contain a `product_type`

## Environment
- **Version**: 8.0.1
- **OS**: Debian GNU/Linux 9.5 (stretch) 
- **Web server**: nginx 1.10.3
- **PHP**: 7.0
- **Database**: MariaDB 10.1.26
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior

`POST /invoices` REST API endpoint should create an order with the specified lines even if no `product_type` is provided in a line by putting this field to 0.

## Steps to reproduce the behavior
POST the following body payload to /invoices REST API endpoint :
```json
{
	"id": null,
	"ref": null,
	"socid": 1,
	"date": 1536334567,
	"mode_reglement_id": 6,
	"cond_reglement_id": 6,
	"lines": [{
		"desc": null,
		"subprice": 30,
		"qty": 1,
		"tva_tx": "0.000",
		"fk_product": "5",
		"date_start": "1536140048",
		"date_end": "1567676048"
	}, {
		"desc": "Code avantage CHANCEUX (-25%)",
		"subprice": -7.5,
		"qty": 1,
		"tva_tx": "0.000",
		"fk_product": null,
		"date_start": null,
		"date_end": null
	}]
}
```

... which results in the following response
![response](https://user-images.githubusercontent.com/613615/45231892-ea13b500-b2cd-11e8-8917-146ccb92477c.png)

When digging, it appear that the generated SQL cause a SQL syntax error as the `product_type` field is omitted in the values, resulting in a double comma `( , , )` instead of `( , 0, )`.

The error is caused only on the second line because the first one includes a `fk_product` and Dolibarr gets the `product_type` from the product described by the FK.

When passing the same data to `POST /orders` endpoint, there is no problem and the order is correctly created with a `product_type` = 0.

**Comment by ATM-Marc** [comment]
See PR #11215
