### ISSUE TITLE
A thirdparty with attached llx_societe_account record cannot be deleted

### ISSUE THREAD

**Issue by jtraulle** [Dolibarr/dolibarr#9439]
# Bug
A thirdparty with attached llx_societe_account record cannot be deleted

## Environment
- **Version**: 8.0.1
- **OS**: Debian GNU/Linux 9.5 (stretch) 
- **Web server**: nginx 1.10.3
- **PHP**: 7.0
- **Database**: MariaDB 10.1.26
- **URL(s)**: /societe/card.php

## Expected and actual behavior

- When deleting a thirdparty with attached llx_societe_account record, it should delete the corresponding llx_societe_account record as well and allow the thirdparty to be deleted or, at least, provide an error message explaining why the thirdparty cannot be deleted (a child llx_societe_account row is associated with the thirdparty and thus cannot be deleted). Instead, it just show a blank page.

## Steps to reproduce the behavior
1. Enable the Stripe module and put the Stripe API credentials in module configuration
1. Create a thirdparty
1. Go to the Gateways tab in the thirdparty and create the Stripe client by clicking the button
1. Go to the first tab of the thirdparty
1. Click the delete button

**Comment by ptibogxiv** [comment]
fixed with this #9423

**Comment by jtraulle** [comment]
thx @ptibogxiv
