### ISSUE TITLE
Feature Request : Forum

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#9460]
# Instructions
I know it's not really the right place to ask this feature request but i hope it could help a little.

# Feature Request
Add a buton to mark as [Resolved] in the Dolibarr forum in order to find/sort easyly solutions.

Tks to all dev team.

**Comment by aljawaid** [comment]
Hello, I would support this too, but as an interim solution I am re-marking any obviously or confirmed as solved posts as 'SOLVED' in the subject line.

I agree the forum software needs to be updated thought to show dolibarr version numbers and also to mark as resolved.

**Comment by dolibarr95** [comment]
tks to @jtraulle ;)
