### ISSUE TITLE
Invoicing from intervention

### ISSUE THREAD

**Issue by neuvill** [Dolibarr/dolibarr#9470]
# Bug
*Creating invoice from an intervention card showing an SQL error message*

## Environment
- **Version**: Dolibarr 8.0.0
- **OS**: Ubuntu server 18.04
- **Web server**: Apache 2
- **PHP**: PHP 7.2
- **Database**: MySql 8
- **URL(s)**: */dolibarr/compta/facture/card.php?action=create&origin=fichinter&originid=7&socid=1*

## Steps to reproduce the behavior
*1- Create e new intervention*
*2- Choose the customer*
*3- Left everything blank and create the draft*
*4- In the intervention card ass the intervention description, the date and the duration*
*5- Validate the intervention*
*6- A new invoice is created with customer chosen in the intervention but the amount is fixed to 0 for all*
*7- Chose the date of the invoice and create the draft*
*8- A message in red is shown saying: 
**You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' , , 0, 0, 100, null, NULL, 1, 1, 1, 'DZD', 0, 0, 0, 0)' at line 1***

**Comment by simnandez** [comment]
Works for me in 8.0.3
