### ISSUE TITLE
Bug: php Warning:  non-numeric value in replenishorders.php

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9475]
> Warning: A non-numeric value encountered in .....\htdocs\product\stock\replenishorders.php on line 61

Line 61:
`$offset = $limit * $page;`
$page is a string.

## Environment
- **Version**: Develop
- **OS**: Windows 10
- **Web server**: Xampp 7.2.8
- **PHP**: 7.2.8
- **URL(s)**: htdocs\product\stock\replenishorders.php on line 61

## Steps to reproduce the behavior
No products in new database.
Click on Products->Replenishment->Replenishment orders to generate warning.

**Comment by torvista** [comment]
I changed this
```
$page = GETPOST("page");
if ($page < 0) $page = 0;
$offset = $limit * $page;
```
to this
```
$page = GETPOST('page','int') ? GETPOST('page','int') : 0;
if ($page < 0) $page = 0;
$offset = $limit * $page;
```

**Comment by defrance** [comment]
https://github.com/Dolibarr/dolibarr/pull/10133
