### ISSUE TITLE
AdvTargetEmailing

### ISSUE THREAD

**Issue by Larsene** [Dolibarr/dolibarr#9477]
![dolibug-advtargetmail](https://user-images.githubusercontent.com/8544729/45416676-be534f00-b680-11e8-935f-369f359b6ba7.jpg)

# Bug
Hi, i encounter a bug with the last dolibarr version (8.0.1) and the AdvTargetEmailing module

## Environment
- **Version**: 8.0.1
- **OS**: WinServer 2012 R2
- **Web server**: Wamp Server
- **PHP**: 5.6.25
- **Database**: MySQL 5.7.14
- **URL(s)**: /dolibarr/htdocs/custom/advtargetemailing/advtargetemailing/advtargetemailing.php?id=186

## Expected and actual behavior
[*Verbose description*]

( ! ) Xdebug: user triggered in   ***SENSITIVE VALUE REMOVED*** \dolibarr\htdocs\core\lib\functions.lib.php on line 3915
--
Call Stack
# | Time | Memory | Function | Location
1 | 0.0018 | 689328 | {main}( ) | ...\advtargetemailing.php:0
2 | 0.1606 | 15731328 | FormAdvTargetEmailing->select_advtargetemailing_template(   ) | ...\advtargetemailing.php:511
3 | 0.1608 | 15730624 | dol_print_error( ) | ...\html.formadvtargetemailing.class.php:490
4 | 0.1641 | 15811848 | xdebug_print_function_stack   ( ) | ...\functions.lib.php:3915

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: SELECT c.rowid, c.name, c.fk_mailing FROM llx_advtargetemailing as c ORDER BY c.name
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Champ 'c.fk_mailing' inconnu dans field list

XDebug informations:
File: *** \dolibarr\htdocs\custom\advtargetemailing\class\html.formadvtargetemailing.class.php
Line: 490
Function: select_advtargetemailing_template

## Steps to reproduce the behavior
try to select some emails with the AdvTargetEmailing module

**Comment by inoveaconseil** [comment]
It's a external module
