### ISSUE TITLE
Reset password link broken when user login contains space (or special characters)

### ISSUE THREAD

**Issue by mpellegrin** [Dolibarr/dolibarr#9480]
# Bug

When an user login contains spaces, the password reset link is broken.

## Environment
- **Version**: 8.0.1

## Expected and actual behavior

The "reset password" link should escape the extraneous characters.

## Steps to reproduce the behavior

 * Create a user with its login containing a space, for instance "test espace".
 * Ask a password reset on the "password forgotten ?" form
 * The link is diplayed as https://SITE:443/user/passwordforgotten.php?action=validatenewpassword&username=test espace&passwordhash=xxxx
instead of https://SITE:443/user/passwordforgotten.php?action=validatenewpassword&username=test+espace&passwordhash=xxxx

## Suggested implementation

Change the line in /user/class/user.class.php from
```
$url = $urlwithroot.'/user/passwordforgotten.php?action=validatenewpassword&username='.$this->login."&passwordhash=".dol_hash($password);
```
to
```
$url = $urlwithroot.'/user/passwordforgotten.php?action=validatenewpassword&username='.urlencode($this->login)."&passwordhash=".dol_hash($password);
```

**Comment by pangoSE** [comment]
Could you create the pull request here instead of in your fork?

**Comment by mpellegrin** [comment]
Done : https://github.com/Dolibarr/dolibarr/pull/10895
