### ISSUE TITLE
[Feature] Display graphs on fiscal year

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#9481]
# Feature Request
Widgets on home page display graphs from January to December. It would be nice to display them according to fiscal year instead of civil year.

# Detail

Widgets are client invoices, supplier invoices, client orders, supplier orders and proposals.
Legend could be amended to '17/18', instead of 2018 when starting in January.
Question: should this feature be the unique way, or should we include an option to have graph on civil year, even if fiscal year is different?
Remark: this can be considered also as a bug.

## Suggested implementation
Adding an optional $startmonth=0 in functions getAmountByMonthWithPrevYear and getNbByMonthWithPrevYear of core/class/stats.class.php
Adapt call to these functions to pass the startmonth of fiscal year in:
core/boxes/box_graph_orders_supplier_permonth.php
core/boxes/box_graph_orders_permonth.php
core/boxes/box_graph_invoices_permonth.php
core/boxes/box_graph_invoices_supplier_permonth.php
core/boxes/box_graph_propales_permonth.php:

**Comment by ksar-ksar** [comment]
Link to that : https://www.dolibarr.fr/forum/12-howto--aide/62414-nouvel-exercice

**Comment by frederic34** [comment]
![2018-11-15 23_27_06-configuration - firefox developer edition](https://user-images.githubusercontent.com/3624836/48585787-0ebf8500-e92e-11e8-9024-ae5bcd896fbc.png)
Something like that?
![2018-11-15 23_24_16-espace accueil - dolibarr 9 0 0-beta - firefox developer edition](https://user-images.githubusercontent.com/3624836/48585688-acff1b00-e92d-11e8-8e9b-b9d1fbf3f642.png)

**Comment by frederic34** [comment]
![2018-11-15 23_40_50-espace accueil - dolibarr 9 0 0-beta - firefox developer edition](https://user-images.githubusercontent.com/3624836/48586340-f486a680-e92f-11e8-8693-70931eaa7a33.png)

**Comment by frederic34** [comment]
![2018-11-15 23_43_29-statistiques des commandes - firefox developer edition](https://user-images.githubusercontent.com/3624836/48586466-547d4d00-e930-11e8-96ae-defbe26b90bb.png)

**Comment by papoteur-mga** [comment]
Nobody answers to this question:

> Question: should this feature be the unique way, or should we include an option to have graph on civil year, even if fiscal year is different?
Here is what I get on my side.

![image](https://user-images.githubusercontent.com/5154580/48606209-53bfd780-e97f-11e8-9766-56ff3813a04b.png)

**Comment by frederic34** [comment]
I introduce a parameter (for wiki lovers)
if (!empty($conf->global->GRAPH_USE_FISCAL_YEAR) && $conf->global->SOCIETE_FISCAL_MONTH_START>1) {

**Comment by papoteur-mga** [comment]
This is done for the home page.
#12260 is still open
