### ISSUE TITLE
No documentation for Spain tax parameters "-19:-15:-9"

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9493]
In the interests of helping others not lose so much time looking for information, it seems that the only explanation of these unique tax parameters and how to use them is here:
https://www.dolibarr.es/index.php/erp-dolibarr/ultimas-noticias-dolibarr/166-nuevo-manejo-del-irpf-para-profesionales
Please advise if this is documented elsewhere.
If not, I'll put it in the Wiki.

**Comment by simnandez** [comment]
@torvista you can put it on the wiki
