### ISSUE TITLE
Bug: error in your SQL syntax, htdocs/comm/card.php, update bank account

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9498]
# Bug

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE rowid=2145' at line 1

## Steps to reproduce the behaviour
Third party->Choose a customer with no bank account defined
Customer->Payment bank account
Click on the edit icon gives: "No active bank account defined"
Click on Modify->causes error.

## Environment
- **Version**: develop
- **OS**: windows 10
- **Web server**: xampp 7.2.8
- **PHP**: 7.2.8
- **Database**: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE rowid=2145' at line 1
- **URL(s)**: ..../htdocs/comm/card.php?socid=2145

**Comment by defrance** [comment]
wip

**Comment by defrance** [comment]
https://github.com/Dolibarr/dolibarr/pull/10132
