### ISSUE TITLE
[8.0.0] Error & warnings on external site module

### ISSUE THREAD

**Issue by AXeL-dev** [Dolibarr/dolibarr#9511]
# Bug
Weird errors & warnings once i activated the external site module

![capture du 2018-09-14 01-11-29](https://user-images.githubusercontent.com/30635693/45547902-50db2600-b81a-11e8-81cf-6625178d66f6.png)

## Environment
- **Version**: [*8.0.0*]
- **OS**: [*Linux*]
- **Web server**: [*Linux*]
- **PHP**: [*7.0.x*]

## Expected and actual behavior
Only the first error message (in red) should be shown.

## Steps to reproduce the behavior
1 - Activate external site module from module settings (module configuration should be empty).
2 - Click on 'ExternalSite' top menu.

**Comment by inoveaconseil** [comment]
WIP

**Comment by inoveaconseil** [comment]
Corrected in 8.0.1
