### ISSUE TITLE
Bug: Problems with payment form on Mac OS using Stripe

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#9515]
# Bug
The online payment form does not allow to make a payment via Stripe but it worked fine for me on Windows PC.  Please see the attached screenshot. 
Please note that happened to me on Doli ver. 8.0.1 with old and new Stripe API

## Environment
- **Version**: 8.0.2
- **OS**: Linux server.turro24.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.37
- **Database**: MySQL or MariaDB 5.5.5-10.2.17-MariaDB
- **URL(s)**: /htdocs/public/payment/newpayment.php

## Expected and actual behavior
E: The payment form should allow the customer to input card number when making a payment via Stripe on Mac OS computer
A: The payment form does not allow to input the card number when using it on Mac OS

## Steps to reproduce the behavior
Create and validate any proposal/order/invoice and use a payment form link to make a payment via Stripe on Mac OS computer

## [Attached files]
<img width="613" alt="screen shot 2018-09-14 at 17 12 36" src="https://user-images.githubusercontent.com/28427270/45562746-2ce00a80-b843-11e8-852a-caf6b35d3cdc.png">

**Comment by ptibogxiv** [comment]
with chrome ? safari ? edge ? firefox ?

**Comment by futurehousestore** [comment]
Tested on Safari and Chrome

**Comment by ptibogxiv** [comment]
can you test the stripe form here ? it's the same code than in dolibarr 

https://stripe.com/docs/stripe-js/elements/quickstart

**Comment by futurehousestore** [comment]
This works fine.
<img width="804" alt="screen shot 2018-09-15 at 15 31 21" src="https://user-images.githubusercontent.com/28427270/45587336-780a2400-b8fc-11e8-80c2-cd1c87acf712.png">

**Comment by ptibogxiv** [comment]
have you disable javascript for your dolibarr ? correct and secure stripe forme use javascript and it's the same code on dolibarr and  stripe's demo

**Comment by futurehousestore** [comment]
I did try without JavaScript and without a luck but update to 8.0.2 has fixed the problem.

**Comment by ptibogxiv** [comment]
pb with stripe api version. it was corrected with 8.0.2. I let you close this request.
