### ISSUE TITLE
Warning: key() expects parameter 1 to be array

### ISSUE THREAD

**Issue by johnjohn007** [Dolibarr/dolibarr#9552]
# Instructions
Hello, i got a error warning on back-end, this is new installation and i didnt know what happen with it.

# Bug
It say Warning: key() expects parameter 1 to be array, string given in /home/mywebsite/mydomain/core/lib/json.lib.php on line 64

## Environment
- **Version**: [*Dolibarr 8.0.1*]
- **OS**: [*linux*]
- **Web server**: [*Cpanel*]
- **PHP**: [*7.0.28*]
- **Database**: [*10.1.31-MariaDB*]
- **URL(s)**: [*localhost*]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*This error show on every Invoice module and Third party module*]

## [Attached files]

[https://www.dolibarr.org/media/kunena/attachments/22278/ErrorStringArray.jpg](url)

**Comment by johnjohn007** [comment]
I fix it.

Thanks.

**Comment by eldy** [comment]
Did you publish your fix ?
Can you paste it here ?

**Comment by johnjohn007** [comment]
Hi Eldy, thanks for your support.

Let me explain it, this New installation of 8.0.1 have an something wrong with PHP Extension, if you used PHP 7.0 set it all the extension on default.

At my really really first time i trying 8.0.1, it ask me to activate imagick and gmagick on PHP Extension.

And this error's come out. 
"It say Warning: key() expects parameter 1 to be array, string given in /home/mywebsite/mydomain/core/lib/json.lib.php on line 64"

The Solution is : Set default the PHP Extension again. 

And it's work good.

That's it.

Thank you
