### ISSUE TITLE
Bug: typing error in module pdf_crabe.modules.php

### ISSUE THREAD

**Issue by gschratzer** [Dolibarr/dolibarr#9562]
# Instructions
the typing error don't update total_ht in invoices if you are using multicurrency modul!
so if you are using multi currency you have a total from ZERO

# Bug
pdf_crabe.modules.php line 1095
mylticurrency was written ... correct is $object->multicurrency...

the same bug is copied in following modules:

core/modules/supplier_order/pdf/pdf_muscadet.modules.php:		
$total_ht = ($conf->multicurrency->enabled && $object->mylticurrency_tx != 1 ? $object->multicurrency_total_ht : $object->total_ht);

core/modules/supplier_invoice/pdf/pdf_canelle.modules.php:		
$total_ht = ($conf->multicurrency->enabled && **$object->mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

core/modules/facture/doc/pdf_crabe.modules.php:		$total_ht = ($conf->multicurrency->enabled && **$object->mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

core/modules/commande/doc/pdf_einstein.modules.php:		$total_ht = ($conf->multicurrency->enabled && $object->**mylticurrency_tx** != 1 ? $object->multicurrency_total_ht : $object->total_ht);

core/modules/propale/doc/pdf_azur.modules.php:		$total_ht = ($conf->multicurrency->enabled && $object->### mylticurrency_tx != 1 ? $object->multicurrency_total_ht : $object->total_ht);

# Feature Request
change to multicurrency

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/9565

**Comment by atm-maxime** [comment]
Fix has been merged
