### ISSUE TITLE
Bug: Fatal Error on loading additional page of previous prices log in htdocs/product/price.php

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9572]
# Bug
Fatal error: Uncaught Error: Call to a member function hasFatherOrChild() on null in ...\htdocs\core\lib\product.lib.php:84 
Stack trace: 
#0 ...v\htdocs\product\price.php(698): product_prepare_head(NULL) 
#1 {main} thrown in ...\htdocs\core\lib\product.lib.php on line 84

## Steps to reproduce the behavior
Setup->Products Module->Parameters->Rules for selling->Multiple price segments per product/service
(this may be unnecessary but it generates a lot of price changes quickly for testing)

Go to a product, change the selling prices a few times until the log shows a link to a second page.
Click on the second page link to get the error.

## Environment
- **Version**:develop
- **OS**: windows10
- **Web server**: xampp 7.2.8
- **PHP**: 7.2.8
- **Database**:10.1.34-MariaDB
- **URL(s)**: https://..../htdocs/product/price.php?page=1

**Comment by atm-maxime** [comment]
Confirmed, pagination for price log list on a product does not work (checked in 6.0)

**Comment by inoveaconseil** [comment]
WIP
