### ISSUE TITLE
Bug: ajax automplete product not set discount in Supply Invoice

### ISSUE THREAD

**Issue by catrielr** [Dolibarr/dolibarr#9577]
I have a product with a discount for minimum quantity. And when I use "autocomplete" in the text entry does not complete the discount configured for this product

**Comment by McCoy78** [comment]
@catrielr Could you be more precise ? What do you mean by autocomplete ?

**Comment by catrielr** [comment]
This is same issue, https://github.com/Dolibarr/dolibarr/issues/9592
Here describes the problem well.
This is when PRODUIT_USE_SEARCH_TO_SELECT is active

**Comment by torvista** [comment]
I have just spent hours tracking this down, it still exists in the develop version.
1) Make a product with a buying price discount.
2) in Setup->Products->"Wait until you press a key before..."->Set to Yes to activate the ajax autocomplete. PRODUIT_USE_SEARCH_TO_SELECT is the constant modified by this option.
3) Make a supplier order.
4) Select the product by typing the letter, the autocomplete popup shows the product info including discount.
5) Add the product. The discount parameter "remise_percent" is 0/not passed in the POST.

**Comment by torvista** [comment]
This is not fixed.
But this DOES fix it:

in objectline_create.tpl.php we have this:
```
		    // $senderissupplier=2 is the same as 1 but disables test on minimum qty and disable autofill qty with minimum
		    if ($senderissupplier != 2)
		    {
    			$ajaxoptions=array(
    					'update' => array('qty'=>'qty','remise_percent' => 'discount','idprod' => 'idprod'),	// html id tags that will be edited with which ajax json response key
    					'option_disabled' => 'idthatdoesnotexists',					// html id to disable once select is done
    					'warning' => $langs->trans("NoPriceDefinedForThisSupplier") // translation of an error saved into var 'warning' (for example shown we select a disabled option into combo)
    			);
    			$alsoproductwithnosupplierprice=0;
		    }
		    else
		    {
		        $ajaxoptions = array();
		        $alsoproductwithnosupplierprice=1;
		    }
```
The first clause IF $senderissupplier != 2  (actually it is 1) only allows you to select products (from the full list) which have a buying price defined for that supplier. This does pass the discount to the ajax handler.
The second clause ELSE (the default, when $senderissupplier == 2) allows you to select any product 
 from the full list. The second clause does not work.
I just put the same $ajaxoptions in the second clause and it fixed the problem.

If a developer reads this, I would like some confirmation that the comment in the first line of this snippet is actually true....that option 2 (the default) should have those items disabled???

**Comment by nicoxygen** [comment]
hello torvista can you give me code to change please

**Comment by torvista** [comment]
it's in the previous post...
