### ISSUE TITLE
Picking products for orders, free-text and associated textarea not shown together.

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9580]
# Feature Request
When picking products for orders etc. 
- the free-text option is shown first
- then the combo list of defined products
- then the text box that is associated with the free-text.
eg:
![choose product](https://user-images.githubusercontent.com/4391026/45845051-4f32c600-bd24-11e8-8e34-288c105775d8.gif)

This is not logical.
The combo should be first as that is the option mainly used.
The free-text selection and associated text area should be together.
Eg.
![choose product2](https://user-images.githubusercontent.com/4391026/45845067-5954c480-bd24-11e8-9348-9de01625e67a.gif)

That's my opinion.

**Comment by aljawaid** [comment]
I agree and it seemed fine it earlier versions.... defintely looks messed up in v7

**Comment by torvista** [comment]
After a voyage of discovery this table layout requires a lot of work to put the text field at the end and aligned with the required boxes to fill in the associated values.
Since the text box can be resized in the browser, I settled for this minimal format.
![clipboard02](https://user-images.githubusercontent.com/4391026/46539654-655d8c00-c8b7-11e8-9bcb-bb6dc13ab0d7.gif)
It is not ideal: the products combo-box should be allowed the width of the form...but that requires the whole table to be rethought.

**Comment by atm-maxime** [comment]
The textarea is not associated with free lines. It's used in both cases. Even if you select a product from the combo list, you can fill the textarea. This is the description of your line.

**Comment by torvista** [comment]
> It's used in both cases.

I never realised that! Ha ha!! 
Thanks for letting me know!
