### ISSUE TITLE
Bug: Module builder Setup link broken

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9585]
# Bug
Clicking on the Module Builder Setup icon in the module list results in a page not found: the url is missing the .php extension:

> https://..../htdocs/modulebuilder/admin/setup?save_lastsearch_values=1&backtopage=%2Fdolibarr-mv%2Fhtdocs%2Fadmin%2Fmodules.php%3Fsearch_nature%3D%26search_version%3D%26search_status%3D

## Environment
- **Version**: develop

**Comment by torvista** [comment]
...and when you do get into the setup, the link to manual development is incorrect, it points to the same page.

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/9586
