### ISSUE TITLE
Bug: decimal limit does not apply to discount in PR and FA pdf columns.

### ISSUE THREAD

**Issue by vvnt** [Dolibarr/dolibarr#9588]
Dolibarr allows administrator to limit the number of decimal (admin/limits.php?mainmenu=home) in document. However, this limitation does not work for discount columns in PR and FA pdf documents.

## Environment
- **Version**: 7.0.3.

**Comment by inoveaconseil** [comment]
I think we can not round a percentage
.

**Comment by vvnt** [comment]
Version 6 applies a format number to discount percentage on .pdf to keep the last two decimals. This format went off since version 7. Still out on version 8.
