### ISSUE TITLE
Feature Request: Client Letter Section 

### ISSUE THREAD

**Issue by Shaggs** [Dolibarr/dolibarr#9589]
Hi All, 
    I'm in the process of creating some standard letters for clients for overdue letters,  accepted credit account etc. 

Is there a way someone could add a "Generate Letter" in the client section and then the user can select a pre made letter? 

Right now I use this in the invoice area but a separate section would be handy.  All docs I've done are made as ODT template.

Thanks

**Comment by aljawaid** [comment]
I think there is an external module for that

**Comment by Shaggs** [comment]
I could not find one if there is please do show me

**Comment by aljawaid** [comment]
https://www.dolistore.com/en/modules/658-Template-letters-to-create-PDF.html

**Comment by Shaggs** [comment]
OK I guess I need to re word it. Can we get a letter section similar to invoice for sending letters to clients? Link those letters to clients similar to invoicing? At current I use the custom OTD in invoicing to send the letters.
