### ISSUE TITLE
"Price for this min. qty (w/o discount)" and "Default discount for qty" are ignored in supplier orders

### ISSUE THREAD

**Issue by McCoy78** [Dolibarr/dolibarr#9592]
# Bug
The fields "Minimum Qty", "Price for this min. qty (w/o discount)" and "Default discount for qty" are ignored on price calculation when creating a new supplier order.

## Environment
- **Version**: 7.0.3 (but bug exists from version 3.x.x)
- **OS**: Ubuntu
- **Web server**: Apache2
- **PHP**:  good ;)
- **Database**: MySQL
- **URL(s)**: /product/fournisseurs.php?id=xxx&action=add_price

## Expected and actual behavior
When creating a new supplier order, product buying price should use calculated price from values of "Minimum Qty", "Price for this min. qty (w/o discount)" and "Default discount for qty".
It is not the case.

## Steps to reproduce the behavior
Create a product with following Buying prices:
Minimum Qty: 1 
Price for this min. qty (w/o discount): 100
Default discount for qty: 20%

Save the product. The Unit price (net) stays to 100.00 It should be 80.00. However, the Best buying price is 80.00 which is good.

Now create a new supplier order with 1 unit of the product: the price stick to 100.00. It should be 80.00

Note: the behaviour is different for proposals: the buying price is good and so the margin calculation.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![selection_224](https://user-images.githubusercontent.com/42868712/45890941-89ec3b00-bdc4-11e8-92b5-2629b895b8a5.png)

![selection_225](https://user-images.githubusercontent.com/42868712/45891013-bf912400-bdc4-11e8-8f09-9a2978fead5d.png)

![selection_226](https://user-images.githubusercontent.com/42868712/45891159-30384080-bdc5-11e8-925f-e0f277392353.png)

**Comment by eldy** [comment]
Do you experience trouble with 8.0.2 ?

**Comment by McCoy78** [comment]
Do not know, we do not have 8.0.x installed at this time.
We just switch the production server to 7.0.3 version which was the stable one when starting the evaluation / test / migration / production process.
I will give a try in the following days.

**Comment by McCoy78** [comment]
Hi. Looks to be fixed on a 8.0.2. At least, a supplier order now takes the good price (aka full price with discount applied).
Too bad that it was not in the 7.0.x.

**Comment by nicoxygen** [comment]
hello i have 8.0.2 and problem persist

**Comment by McCoy78** [comment]
Sure ? I just did the test agin and it works fine. Here is the screen shot on the same product.

![selection_232](https://user-images.githubusercontent.com/42868712/46418310-d3754800-c72b-11e8-88ca-0a75495686da.png)

**Comment by nicoxygen** [comment]
if you setup buy price with professionnal and insert discount 40% on example
when you add this product in order don't take 40%
![discount](https://user-images.githubusercontent.com/17491075/46418660-86de3c80-c72c-11e8-911d-41781ce0f4f1.png)

**Comment by McCoy78** [comment]
It looks we have different result. Here is what I have:
First, setup the product with 40% discount
![selection_233](https://user-images.githubusercontent.com/42868712/46422315-5d291380-c734-11e8-9cb5-cb3fa51f456e.png)

We could say that the product is not fully configured as you can see with the red square: unit price should be the discounted price (which is the same as the best price if there is only one supplier)
![selection_234](https://user-images.githubusercontent.com/42868712/46422337-69ad6c00-c734-11e8-847f-87323c67eede.png)

But when adding the product to a supplier order, the final price looks good:
![selection_235](https://user-images.githubusercontent.com/42868712/46422501-d163b700-c734-11e8-955c-0281e701a309.png)

**Comment by nicoxygen** [comment]
ok for you but to me it's not good i was in 7.0.3 version before i had not this problem i use dolibarr to 2010 i know and on 8.0.2 discount isn't to order, i don't know why ?

**Comment by nicoxygen** [comment]
look pictures all product has 40% discount 
![discount-1](https://user-images.githubusercontent.com/17491075/46434850-23b4d000-c755-11e8-9702-5338040ae1db.png)

but after add line i have not 40%
![discount-2](https://user-images.githubusercontent.com/17491075/46434859-28798400-c755-11e8-9b65-333b22133a78.png)

**Comment by nicoxygen** [comment]
I think it's related to another problem when I'm going to search the orders or invoices suppliers I have a page 403, I think that when upgrading version 7 to version 8 it's happened something like file rights for example, could someone get me?

**Comment by nicoxygen** [comment]
ok i'm part of a fresh 7.0.3 i updated to the 8.0.2 then i imported my database and i have the same errors so it does not come from the files but either from the update is the update of the database.

**Comment by McCoy78** [comment]
I think that database should be set-up on the 7.0.3 until fully operational before staring any update.
This is how we proceed:
- we make a full copy of the production environment to the test server (base + sources)
- on the test server, we change the configuration file in order to have a fully operational dolibarr version, clone of the production version
- we launch the update process
The process in not really plug & play but after a couple of hours, we generally have an updated and functional version.

**Comment by catrielr** [comment]
same issue:
https://github.com/Dolibarr/dolibarr/issues/9577

**Comment by nicoxygen** [comment]
hello I went to version 9.0 and I still have the same concerns about the discount that is not included in the php version 7.0 command

**Comment by atm-maxime** [comment]
Hi. I just checked and it works fine in 8.0.6. Seems fixed to me. Reopen if needed.
