### ISSUE TITLE
Bug: Wrong currency displayed in supplier invoice PDF (UltimatePDF)

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#9593]
# Bug
Wrong currency symbol displayed in supplier invoice PDF. My main currency is GBP but my supplier currency is PLN. All the prices are displayed correctly just the currency symbol is wrong (I've got Polish amount but with British currency) The problem occurs when using UltimatePDF that's why it is FAO @grandoc 

## Environment
- **Version**: 8.0.2
- **OS**: Linux server.turro24.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
- **Web server**: Apache/2
- **PHP**: 5.6.38
- **Database**: MySQL or MariaDB 5.5.5-10.2.17-MariaDB
- **URL(s)**: /htdocs/fourn/facture/card.php?facid=106&save_lastsearch_values=1

## Expected and actual behavior
E: Display the correct currency symbol same as the currency chosen.

## Steps to reproduce the behavior
Create a supplier invoice from a purchase order in a different currency than the main one set up in Dolibarr

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![dol2](https://user-images.githubusercontent.com/28427270/45891602-eac44500-bdbd-11e8-81b0-ab5a98e65a89.JPG)
![dol1](https://user-images.githubusercontent.com/28427270/45891603-eac44500-bdbd-11e8-9218-7d77732a3f40.JPG)

**Comment by grandoc** [comment]
Hello Marcin
I use price function ->
function price($amount, $form=0, $outlangs='', $trunc=1, $rounding=-1, $forcerounding=-1, $currency_code='')
....
// Add symbol of currency if requested
	$cursymbolbefore=$cursymbolafter='';
	if ($currency_code)
	{
		**if ($currency_code == 'auto') $currency_code=$conf->currency;**

		$listofcurrenciesbefore=array('USD','GBP','AUD','MXN','PEN','CNY');
		if (in_array($currency_code,$listofcurrenciesbefore)) $cursymbolbefore.=$outlangs->getCurrencySymbol($currency_code);
		else
		{
			$tmpcur=$outlangs->getCurrencySymbol($currency_code);
			$cursymbolafter.=($tmpcur == $currency_code ? ' '.$tmpcur : $tmpcur);
		}
	}
and if I make a vardump($conf->currency) it returns GBD and not PLN
I can't get through...

**Comment by atm-maxime** [comment]
Issue regardind external module
