### ISSUE TITLE
Support supplier recurring invoice 

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#9598]
Support supplier recurring invoice like it is done for customer invoices

This will save a lot of time to users.
This will allow also to help to make cash flow forecasts

**Comment by akhalz** [comment]
Any chance this feature can get some attention for the next version. Was hoping it would appear in version 10.

**Comment by akhalz** [comment]
Hi, Still looking for the feature as every month I see multiple use cases for it.
What can be done to assist in order for this feature to be worked on

**Comment by jbonlinea** [comment]
After some research on that matter I ended up here, and yep :+1: for me too

**Comment by akhalz** [comment]
Upgraded to version 13, and I am still surprised that this feature has not been added.
The functionality is already available for customer recurring invoices, so cannot see why it cannot be extended to supplier invoices

Plus @eldy  came up with some good idea about cash flow forecasts.
Can I contribute some money to get this feature done?

**Comment by tommaineult** [comment]
Pleeeaaase, do it! Just like many others, I need this feature to save me many time and only have to enter supplier invoice number.. 🙏

**Comment by BebZ** [comment]
I can cash-contribute also, if neede...

**Comment by akhalz** [comment]
I feel like there is enough support for these features. Plus already a few of us a willing to contribute cash to get this done. 
How do we get the project initiated and started ?

**Comment by fxlip** [comment]
Well.. could this be a priority now?

**Comment by PEM-FR** [comment]
Hello, 

We are considering developing a plugin to do that.
It could be nice to have your needs summarized so we can also cover your needs (depending on how much time that would require compared to our own needs).

Best regards

**Comment by BebZ** [comment]
Hello, 

First step is to create a new type of supplier invoice ? 
at the moment, there are 
standard invoices, 
advance payment
credit notes, 
4th type would be "recurring invoice"

![image](https://user-images.githubusercontent.com/3694135/133028638-bba63822-98d2-400e-908c-3716870b590b.png)


But there are another type of objet that is contracts (can generate invoices ?)

contrat/card.php


to be able to record subscriptions like phone, electricity, water...
it creates one invoice for x months with x payments day y of the month ?
or it creates x draft invoices for x months (at a fixed day) 
with a fixed amount that has to be validated each month ?

Good luck for starting discussions and setting up a good specifications sheet !

**Comment by akhalz** [comment]
Is it not possible to expand the contracts module to include supplier contracts, because that is in fact what is needed.
It reminds me of setting up an automatic payment on you banking app. Specify date for transaction then number of payments or end date

**Comment by PEM-FR** [comment]
I created a slack channel to make it simpler to discuss about features.
If you want to join the channel please send us an email at ronan@tekos.net and we will invite you in.
There you will be able to add some feature requests and we can discuss about the different use cases and what makes the most sense accountancy wise.

**Comment by anashaddad** [comment]
Good to hear a progress... I send joining request email.. I hope this time it will be accoplished.

**Comment by eldy** [comment]
Done for recurring invoices, still need to manage creation from supplier contracts

**Comment by anashaddad** [comment]
Thank you Eldy.. when we will be able to use it..
