### ISSUE TITLE
"Bug"/Feature request: Multicurrency incomplete for product buying price

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9604]
# Feature Request
Supplier product prices currently (develop-version) have to be entered in the calculated-base-currency-equivalent and not the actual supplier price in the supplier currency.
As a new user preparing to use Dolibarr I find this situation incomprehensible.
How do you reconcile a supplier invoice in a second currency with a dolibarr-generated purchase order in the euro equivalent?
Reconciliation of supplier invoices should be able to update the buying prices in the supplier currency, as that is usually the first indication we get of variations in supplier prices, and the best way to update those prices. 

Supplier orders should be shown in the supplier currency.
This issue is a serious problem for me, and of all the issues I have raised (mostly without a verbal response) in my implementation of Dolibarr, I now politely request a developer response as to what the plan is to correct this situation?
While it may not be a bug, it seems very wrong indeed.
I am/WAS implementing Dolibarr to replace legacy software pre-2009, and THAT implements multicurrency correctly in this respect, so we cannot go backwards!

This is a show-stopper for me, so I must stop and await a response before I do any more work on Dolibarr. I already waited for years until multicurrency was implemented...

**Comment by torvista** [comment]
Since I take the time to contribute, answer forum questions and correct the Wiki for this project, I think I merit a response.

**Comment by torvista** [comment]
Can someone confirm or deny that this aspect of multicurrency will remain as it is, or be improved/corrected, before I proceed with my own solution?

**Comment by tiaris** [comment]
I met the same question as you. So far I know, the actual way to enter product prices in currency is to convert them in local currency.
I agree with you. I, for some users, I will also have to developp functionnality that permits inserting price in currency and calculate the equivalent localcurrency

**Comment by torvista** [comment]
Thanks for your reply, nice to know there is someone out there.
The question is still unanswered by the developers....it greatly reduces my interest in continuing to contribute.

**Comment by philippe-opendsi** [comment]
Hi, we have done this PR in the past
https://github.com/Dolibarr/dolibarr/pull/8218
It seems to answer to your request. Maybe not ?
Regards

**Comment by torvista** [comment]
Yes, this seems to address the issue I was having.
Thanks for pointing this out.
