### ISSUE TITLE
Feature Request: rework of product image link to allow bulk import with product data

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9609]
# Feature Request
Currently (develop), the product image link is contained in table llx_ecm_files.
I don't know the logic behind this, I would have thought it would form part of the base product data in the llx_product table and so be easily imported along with all the other base product data.

Consequently, it appears impossible to bulk import product image links.
While product image is a non-critical issue for me, it would be a help for employees, but if can only be entered manually, that is not feasible/practical.

So I suggest product image uses a field in the product table, to allow this link to be included with the product import/update.

**Comment by pangoSE** [comment]
What happens if I would like 2 or more images of a product? Is this proposal then still feasible?

**Comment by pangoSE** [comment]
As an aside this was [implemented proprietorially in odoo 11](https://store.webkul.com/Odoo-Product-Multi-Images.html)

**Comment by dpriskorn** [comment]
@torvista did you find a solution? You can hire me to write a simple python script for you to use instead if you want. Contact me at egils@riseup.net if you are interested.

**Comment by torvista** [comment]
My Dolibarr implementation went on the back-burner again, due to more pressing issues, and I have not touched it since.
I hope to re-start in this current lifetime....so, it's all still pending. Maybe I'll be in touch then, thanks.
