### ISSUE TITLE
[Bug] Option MAIN_DISABLE_NOTES_TAB not working, notes stay hidden

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#9611]
# Bug
The option MAIN_DISABLE_NOTES_TAB allow to display notes on the main tab instead of a separated tab. At opening, notes are hidden and a button at right allows to un-hide them.
This button is not working, it has no effect, although notes are included in the source page.
The same for order, invoice, intervention...
## Environment
- **Version**: V 7.0.2, 8.0.1
- **URL(s)**: /htdocs/comm/propal/card.php?id=185

## Expected and actual behavior
Public and private notes should be displayed when the button is pushed.

## Steps to reproduce the behavior
Set the option MAIN_DISABLE_NOTES_TAB

**Comment by papoteur-mga** [comment]
It seems that the problem is the same for the option  MAIN_DISABLE_CONTACTS_TAB

**Comment by frederic34** [comment]
@papoteur-mga can you check?

**Comment by aljawaid** [comment]
The fix from @frederic34 worked to hide the tab but no button ever existed based on: 

> allow to display notes on the main tab instead of a separated tab. At opening, notes are hidden and a button at right allows to un-hide them.
This button is not working,

Please show a screenshot of the button.

(v7.0.3)

**Comment by papoteur-mga** [comment]
![notes-button](https://user-images.githubusercontent.com/5154580/46067710-c975a700-c177-11e8-8c4f-c7d0feef01b7.png)
Completely at right

**Comment by aljawaid** [comment]
Is that on the products main tab?  I can't find it

**Comment by papoteur-mga** [comment]
No, this example is on a supplier invoice
