### ISSUE TITLE
[Bug] (Supplier) Credit Notes validation name is the rowid (8.0.*) 

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#9624]
# Bug
Credit Notes generated to correct supplier invoices, once validated, take the name of the db "rawid", so a sequential integer.
In previous versions they were named as normal supplier invoices, according to the settings of the module.
Not yet checked if this issue affects also the Customer Credit Notes...

## Environment
- **Version**: 8.0.2
- **OS**: Linux 3.10.105 #23739 SMP Tue Jul 10 00:15:23 CST 2018 x86_64
- **Web server**: Apache/2.2.34 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141
- **PHP**: 5.6.36
- **Database**: MySQL or MariaDB 5.5.59-MariaDB
- **URL(s)**: /dolibarr/htdocs/fourn/facture

## Expected and actual behavior
Credit Notes should be named as regular supplier invoices or with a different naming convention if this option were available in the module settings (as for the Customer Invoices).

**Comment by atm-maxime** [comment]
Hey, You're right, is you are using the Tulip numbering system, there's no setup available for credit notes, so the system is confused when it must validate it.

If you use the generic setup, it works :

![image](https://user-images.githubusercontent.com/2097773/46918386-f1676600-cfd1-11e8-8955-98d371b60cc2.png)

I just added the setup for the Tulip numbering system, wait for my pull request to be merged : #9744
