### ISSUE TITLE
BUG: A pagination bug and back to the list

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#9625]
This is not really fun especially when you have a long list of articles (762 page of article) and it's necessary every time to redo the navigation from the beginning to find the last page consulted and by doing hundreds of cliques ......

# Bug
Test the lit of products (Dol.V8.0.2) as follows: 
1st step - I change the display number of products per page from 25 to 50.
2nd step - I go to page number 2
3rd step - I click on an article to see details.
4th step - I decide to continue my consultation, I click on the "Return list" link.

Surprise! it sends me back to the first page and changes the number of articles per page from 50 to 25 !!

**Comment by pangoSE** [comment]
What happens if you use the browser "back" button instead?

**Comment by wdammak** [comment]
it works :) but if I browse the other tabs of the product I have to click so many times to find the page :/

**Comment by wdammak** [comment]
Many Thanks eldy!
tested and is OK!
