### ISSUE TITLE
Feature Request invoice / accounting 

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#9632]
# Feature Request
Add Preview option / Print invoice next to Save option
Add delivery form
Added the ability to modify the invoice form with a built-in text editor
Adding the ability to import an accounting system for a country (eg Excel file)
## Use case
Preview / print options make the billing process easier for the traditional user
The option of a  delivery form is essential for la Francophonie
The option to modify invoice forms via a compact text editor makes editing easier for non-experts
The accounting system import option facilitates the preparation of lists instead of the manual process

**Comment by pangoSE** [comment]
Hi, could you please split these requests up in 4 different issues and delete this one?

**Comment by atm-maxime** [comment]
I guess every 4 of your request are already existing.

The preview button is available next to the PDF file generated :
![image](https://user-images.githubusercontent.com/2097773/46919788-b4f13580-cfe4-11e8-83d6-bbe0e058cbab.png)

The delivery form is an existing module called "shipment". Process is to record a customer order, then create a shipment/delivery, then create an invoice.

I am not sure what you mean about modifyning a form with a text editor... Dolibarr provides possibility to define ODT templates to generate invoices for example, if that's what you are looking for.

As for importing an accounting system, you can do it with the standard import module.

I hope I understood you request. Tell us :)
