### ISSUE TITLE
Extrafields facture fournisseur

### ISSUE THREAD

**Issue by dieperie** [Dolibarr/dolibarr#9641]
# Bug
"Date" type extra field not working properly.

## Environment
- **Version**: 8.0.2

## Expected and actual behavior
When entering a date, the date is reset to 01/01/1970. This is since version 8.0.0

**Comment by atm-maxime** [comment]
Seems to be fixed in 8.0.3, I can't reproduce. Please check when you can and tell us

**Comment by dieperie** [comment]
8.0.3 is not yet released. Will try when published.

**Comment by atm-maxime** [comment]
Fixed in #10803 but not in 8.0 branch yet

**Comment by atm-maxime** [comment]
Coud you confirm it's fixed please ?
