### ISSUE TITLE
Expenses module

### ISSUE THREAD

**Issue by dieperie** [Dolibarr/dolibarr#9642]
# Bug
When entering extrafield content, a Dolibarr error message appears.

Requête dernier accès en base en erreur: SELECT de.rowid, de.comments, de.qty, de.value_unit, de.date, de.rang, de.0, de.fk_c_type_fees, de.fk_c_exp_tax_cat, de.fk_projet, de.tva_tx, de.total_ht, de.total_tva, de.total_ttc, ctf.code as code_type_fees, ctf.label as libelle_type_fees, p.ref as ref_projet, p.title as title_projet FROM llx_expensereport_det as de LEFT JOIN llx_c_type_fees as ctf ON de.fk_c_type_fees = ctf.id LEFT JOIN llx_projet as p ON de.fk_projet = p.rowid WHERE de.0 = 14 ORDER BY de.rang ASC, de.date ASC
Code retour dernier accès en base en erreur: DB_ERROR_NOSUCHFIELD
Information sur le dernier accès en base en erreur: Unknown column 'de.0' in 'field list'

## Environment
- **Version**: 8.0.2

## Expected and actual behavior
 This is since version 8.0.0

**Comment by atm-maxime** [comment]
Hey, I can't reproduce with 8.0.3 version. Can you check and tell us ?

**Comment by dieperie** [comment]
8.0.3 is not yet released. Will try when published.

**Comment by frederic34** [comment]
WIP
