### ISSUE TITLE
Backup / Restore

### ISSUE THREAD

**Issue by dieperie** [Dolibarr/dolibarr#9644]
# Bug
ERROR 1813 (HY000) at line 10391: Tablespace for table '`dolibarrdebian`.`llx_ticket_logs`' exists. Please DISCARD the tablespace before IMPORT

## Environment
- **Version**: 8.0.2

## Expected and actual behavior
When trying to restore a database. This is since version 8.0.0

**Comment by pangoSE** [comment]
Have you tried dropping the said table in the database and restore again?

**Comment by dieperie** [comment]
Yes, I tried before this post. Does not help. I have same symptom on two systems.

**Comment by dieperie** [comment]
I just installed v8.0.3 and I still have the same issue. I cannot backup and thereafter restore.
