### ISSUE TITLE
Bug: installer chokes on Google+ sql

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9664]
# Bug
On installation of table llx_socpeople from

\htdocs\install\mysql\tables\llx_socpeople.sql

this line
`  google+                  varchar(255),`  

causes an SQL error/aborts the install. It does not like the "+".

## Environment
- **Version**: develop
- **OS**: Windows 
- **Web server**: Xampp 7.2.8
- **PHP**: 7.2.8

**Comment by dolibarr95** [comment]
Hi!
it's done :  https://github.com/Dolibarr/dolibarr/commit/402a383c8307af0ab2f9a0df88074ff778e03d2c#diff-97ef5381448a4e6a38350798dc26bea8
you can close your issue

**Comment by torvista** [comment]
..not yet:
![clipboard01](https://user-images.githubusercontent.com/4391026/46730955-c1def380-cc89-11e8-8d36-6dc94b1e3dab.gif)

**Comment by torvista** [comment]
https://github.com/Dolibarr/dolibarr/commit/eff0e959b344eece9f996c9277a691a1fdd1d0f6
ok, now it's fixed!
