### ISSUE TITLE
absence of information on tasks and projects in arrearsBug: 

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#9667]
# Bug

## Environment
- **Version**: 8.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.38
- **Database**: MySQL or MariaDB 5.6.40
- **URL**: /auditorias/index.php?mainmenu=home&leftmenu=home

**Comment by atm-maxime** [comment]
Could you provide more info ? Screenshot ?
