### ISSUE TITLE
Email template not set as default in 8.0.1

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#9669]
Bug

[If I create a personal email template for order confirmation, invoice etc and I mark this as default the default system text is still selected and I need to manually apply my own template. Work around for this problem in 7 does not work in 8]

**Comment by pangoSE** [comment]
Have you tried upgrading?

**Comment by GheeEasy** [comment]
I am very afraid of upgrading. Alsways when I upgrade something stops working…
