### ISSUE TITLE
Sending email field not showing when module CustomFields is enabled.

### ISSUE THREAD

**Issue by GheeEasy** [Dolibarr/dolibarr#9671]
# Bug
[*After updating from dolibarr 7 to 8.0.1 the sending of emails fields below orders, shipments and invoices would not show if clicked on "send email" button. After disabling the extrernal module CustomFields (which we use a lot) the functionality was restored. *]

## Environment
- **Version**: [*8.0.1.*]
- **OS**: [*Linuxr*]
- **Web server**: [*Hosted webserver, version unknown*]

**Comment by ksar-ksar** [comment]
CustomFields is an aditional module that is not supported since Dolibar 4.0
Why do you not move to extrafield that is part of the core ?

**Comment by GheeEasy** [comment]
OK! Thank you for the tip! This will take a lot of work though!

 

Andreas
