### ISSUE TITLE
Bug: Currency fields empty [Payment page]

### ISSUE THREAD

**Issue by futurehousestore** [Dolibarr/dolibarr#9676]
# Bug

Currency fields are empty in Payment page. Multi-currency module enabled and set up. Am I missing some configuration or is that a bug?

## Environment

Version: 8.0.2 & 9.0.0-alpha
OS: Linux server.turro24.pl 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
Web server: Apache/2
PHP: 5.6.37
Database: MySQL or MariaDB 5.5.5-10.2.17-MariaDB
URL(s): /htdocs/fourn/facture/paiement.php?facid=33&action=create&accountid=1

## Expected and actual behavior

E: Currency, amount (inc. of tax) original currency, already paid original currency, etc. should display the information.
A: Currency, amount (inc. of tax) original currency, already paid original currency, etc. empty

## Steps to reproduce the behavior

Create a supplier invoice and click on "ENTER PAYMENT" button

## [Attached files]
<img width="1452" alt="screenshot 2018-10-03 at 21 51 00" src="https://user-images.githubusercontent.com/28427270/46439707-2adddd00-c759-11e8-8ef2-67b70fea27b2.png">

**Comment by alonsosdp** [comment]
It would be great to have this feature implemented!

**Comment by futurehousestore** [comment]
I can see this has been fixed/implemented in version 11 :) Thank you and well done guys! Great job!
