### ISSUE TITLE
Bug: list of last modified products, price incl. tax never shown

### ISSUE THREAD

**Issue by torvista** [Dolibarr/dolibarr#9678]
# Bug
When a product price has its base as TTC/incl. tax, this is never shown in the last modified list, it is always shown as HT/excl.tax.

## Steps to reproduce the behavior
Edit a product for price with tax.
Edit a product with a price without tax.
Compare in list.
https://.../htdocs/product/index.php?mainmenu=products&leftmenu=

## Suggested Correction
The code for this is:
htdocs/product/index.php
```
if (isset($objp->price_base_type) && $objp->price_base_type == 'TTC') print price($objp->price_ttc).' '.$langs->trans("TTC");
    			else print price($objp->price).' '.$langs->trans("HT");
```

But $objp->price_base_type and $objp->price_ttc are never set.

Suggest
```
$max=15;
$sql = "SELECT p.rowid, p.label, p.price, p.price_ttc, p.ref, p.fk_product_type, p.tosell, p.tobuy, p.tobatch, p.fk_price_expression,";
$sql.= " p.entity,";
```

is changed to 
```
$max=15;
$sql = "SELECT p.rowid, p.label, p.price, p.price_ttc, p.price_base_type, p.ref, p.fk_product_type, p.tosell, p.tobuy, p.tobatch, p.fk_price_expression,";
$sql.= " p.entity,";
```
Also, just prior to the output code block 

> if (isset($objp->price_base_type) && $objp->price_base_type == 'TTC') print price($objp->price_ttc).' '.$langs->trans("TTC");) 

is some code for price with expresssion. This may also need to be considered.

## Environment
- **Version**: Develop

**Comment by R0drig0V1** [comment]
Dear @eldy,

This has not been repaired :c
