### ISSUE TITLE
Bug: subordonates users create supplier didn't add to table societe_commerciaux

### ISSUE THREAD

**Issue by paulchui123** [Dolibarr/dolibarr#9720]
# Bug
subordonates users create supplier didn't add to table societe_commerciaux

## Environment
PHP: 5.6.33
Server: LiteSpeed
OS: Linux 3.10.0-714.10.2.lve1.4.79.el7.x86_64 #1 SMP Thu Jan 4 13:30:50 EST 2018 x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
dolibarr version: Dolibarr 8.0.2

Requested URL: /fourn/card.php?socid=3345

## Expected and actual behavior
the subordonates users create user should add a line to table societe_commerciaux, after add to the table manually, problem solved.

**Comment by paulchui123** [comment]
this bug exist from 7.0 version and still not fixed

**Comment by atm-maxime** [comment]
When you create a new thirdparty, you must fill the "Sales representatives" field, it's the one linking users to thirds.

**Comment by paulchui123** [comment]
when subordonates user account creates third parties, there's no such field as "Sales representatives"

**Comment by paulchui123** [comment]
ok, looks like i solved this issue, 'societe' should be added to check array

htdocs/core/lib/security.lib.php 

$check = array('adherent','banque','don','user','usergroup','product','produit','service','produit|service','categorie','resource',**’fournisseur’, 'societe'**); // Test on entity only (Objects with no link to company)

**Comment by paulchui123** [comment]
account created successfully but it didn't assign to user by adding a line to table societe_commerciaux, that's why users can't find the thrid party that was created

**Comment by paulchui123** [comment]
@atm-maxime

**Comment by pecreation** [comment]
@asirinelli @genezys @azawawi

**Comment by paulchui123** [comment]
@hregis

**Comment by atm-maxime** [comment]
You say _when subordonates user account creates third parties, there's no such field as "Sales representatives"_, what you call "subordonates" are users without the right "extend access to all thirds", right ?
I confirm that when you create a new third and you don't have right to see all thirds, the sales representative field is displayed and the current user is added by default.
Dolibarr version 8.0.3

**Comment by paulchui123** [comment]
@atm-maxime  the problem is the subordonates user account can't access the order which create under the account it's already created. for example the subordonates user account created a supplier call supplier A, but he can't access any order under this supplier A account. 

i figured this out because the subordonates users create user didn't add a line to table societe_commerciaux

**Comment by paulchui123** [comment]
@atm-maxime

**Comment by atm-maxime** [comment]
Sorry I am not sure to understand. To me it seems to be either a right definition issue or an issue that has been fixed because a user who creates a third is automatically added in the sales representative input if he doesn't have the right to see all thirds.
Can you provide screenshots ? Or close if it's now ok for you.
