### ISSUE TITLE
Bug when affecting a representative to a Thirdparty (8.0.2)

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#9725]
# Bug
Its impossible to affect a commercial to a thisrdpary since update to 8.0.2

## Environment
- **Version**: 8.0.2
- **OS**: all
- **Web server**: all
- **PHP**: all
- **Database**: all
- **URL(s)**: 

## Expected and actual behavior
https://www.dolibarr.de/forum/bugs-mit-einer-dolibarr-stabilen-version/52527-v8-0-2-keine-vertreterzuweisung-mehr-moeglich#56776

## Steps to reproduce the behavior
See screes on german forum

**Comment by atm-maxime** [comment]
Not a bug, in 8.0 version it's when you modify the card that you can assign sales representatives to the thirdparty. It's not a specific screen anymore.
