### ISSUE TITLE
Hide buttons for unauthorized actions ignored

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#9753]
# Bug

I have activated the display setup "Hide buttons for unauthorized actions ignored" but the unathorized buttons are still there greyed out.

## Environment
- **Version**: 8.0.2
- **OS**: Linux Debian
- **Web server**: Nginx 1.2.4
- **PHP**: Php-fpm 7.1.2
- **Database**: Mysql 5.5.48
- **URL(s)**: All

## Expected and actual behavior
Unauthorized buttons should not been shown.
They appear greyed out.

## Steps to reproduce the behavior
Go to Settings > Display
Set "Hide buttons for unauthorized actions ignored" to true

**Comment by laudeco** [comment]
On which page by exemple because I don't think I have the issue ....

**Comment by dbeniamine** [comment]
It happens on any page, for instance on the agenda or HRM parts.
I wonder if it is a problem due to the multicompany module (I use it with centralized users management).

**Comment by atm-maxime** [comment]
I don't have the issue either, buttons are correctly hidden with this option. I saw some pages were it doesn't work (eg bank account lines) but not everywere...
