### ISSUE TITLE
Bug: credit note is positive

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#9793]
# Bug

## Environment
- **Version**: 9.0.0-alpha
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.23-1+0~20181013133636.7+jessie~1.gbp9499d3
- **Database**: MySQL or MariaDB 5.5.5-10.0.36-MariaDB-0+deb8u1
- **URL**: /fourn/facture/card.php?facid=26

## Report
When you use the little icon to fill the amount to pay, the amount is positive. Not negative as it should be. If you forget to fill the minus it's false.

**Comment by atm-maxime** [comment]
I jsut tested on the 9.0-beta and it seems to me that filling the amount with positive value is logic beacause this is the amount you are refunding to your customer. But the system knows this is a refund to it records a negative payment and a debit line in bank.
The credit note is negative but a payment will always be positive. What do you think.

**Comment by atm-maxime** [comment]
No news, I close the issue
