### ISSUE TITLE
A Vendor Bill is not cloned correctly

### ISSUE THREAD

**Issue by nanoxp** [Dolibarr/dolibarr#9800]
# Bug
[A Vendor Bill is not cloned correctly]

## Environment
- **Version**: [8.0.2]
- **OS**: [Linux]
- **Web server**: [2.2.34]
- **PHP**: [5.6.30]
- **Database**: [MYSQL 5.6.32-78.1]

## Expected and actual behavior
[When you clone a supplier invoice that contains discounts on the product lines, that  discounts they are not passed on   to the new cloned invoice]

## Steps to reproduce the behavior
[1- an invoice is created with discounts on its product lines
2- the invoice is validated and a cloning is done
3- Discounts are not passed on to the cloned invoice]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/24461406/47124912-1f54e080-d246-11e8-8331-f30c7d1ae97d.png)
![image](https://user-images.githubusercontent.com/24461406/47124929-38f62800-d246-11e8-8bf3-2d895b6ace5d.png)

[*Files*]

# Feature Request
[When cloning must be a replica of the previous invoice, discounts must also be brought for the line]

**Comment by atm-maxime** [comment]
Hi @nanoxp it's fixed now. Wait for next 8.0 release.
Tell us if it's ok for you.

**Comment by nanoxp** [comment]
OK, thanks

 

 

Saludos,

Edgar R. Ruiz Alonso

 

De: Maxime Kohlhaas <notifications@github.com> 
Enviado el: jueves, 1 de noviembre de 2018 06:11 a. m.
Para: Dolibarr/dolibarr <dolibarr@noreply.github.com>
CC: Edgar Ruiz <eruiz@nesshosting.com>; Mention <mention@noreply.github.com>
Asunto: Re: [Dolibarr/dolibarr] A Vendor Bill is not cloned correctly (#9800)

 

Hi @nanoxp <https://github.com/nanoxp>  it's fixed now. Wait for next 8.0 release.
Tell us if it's ok for you.
