### ISSUE TITLE
Bug:  Issue with PHP7.2

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#9804]
# Bug

## Environment
- **Version**: 8.0.2
- **OS**: Linux
- **Web server**: Apache/2.4.25
- **PHP**: apache2handler 7.2.11-2+0~20181015120801.9+stretch~1.gbp8105e0
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL**: /azerty/htdocs/commande/card.php?action=create&leftmenu=orders

## Report

In changelog it is said that it should work with PHP7.2 but there are problems. The lines below turned up at the top of the screen when running the program

Warning: Use of undefined constant CommonObject - assumed 'CommonObject' (this will throw an Error in a future version of PHP) in /htdocs/custom/milestone/class/dao_milestone.class.php on line 25

Warning: Cannot modify header information - headers already sent by (output started at /htdocs/custom/milestone/class/dao_milestone.class.php:25) in /htdocs/main.inc.php on line 1094

Warning: Cannot modify header information - headers already sent by (output started at /htdocs/custom/milestone/class/dao_milestone.class.php:25) in /htdocs/main.inc.php on line 1097

Warning: Cannot modify header information - headers already sent by (output started at /htdocs/custom/milestone/class/dao_milestone.class.php:25) in /htdocs/main.inc.php on line 1098

**Comment by hasse-basse** [comment]
I went back to 7.1 and it all works fine so there is certainly an issue with 7.2

all the best

Hans

**Comment by ksar-ksar** [comment]
This is because of aditional module "milestone"
Remove this module and it will work fine

**Comment by laudeco** [comment]
You can always let a bug on the milestone module.

**Comment by hasse-basse** [comment]
Thanks, but it looks like the problem is solved. It turned out I had ohter problems in other softwares so I purged all php installations and reinstalled from the beinning starting with PHP7.0 and going up to 7.2 and now everything seem to work as it should.

So for the moment 8.0.2 works fine with PHP7.2 by Ondřej Surý's on surey.org installed on a Debian 9.

I'll let you know if something goes wrong.
