### ISSUE TITLE
LDAP authorization not working as expected

### ISSUE THREAD

**Issue by JensPfeifle** [Dolibarr/dolibarr#9808]
## Environment
- **Version**: 8.0.2
- **OS**: Debian GNU/Linux 9.5 (stretch)   
-**LDAP**: OpenLDAP 2.4.44

Hello,

we have been struggling the past few days to successfully integrate Dolibarr with openLDAP.
According to the LDAP log (see below), it looks like the following is happening:

- User enters uid and password into login form
- Dolibarr binds to the LDAP server with the admin DN to search for the user that is trying to log in
- One entry is returned (uid is unique)
- Dolibarr binds to the LDAP again, using the DN of the user this time
- LDAP query returns error 32 (NoSuchObject) and no entries because this user has no permissions in the LDAP database
- Login fails

So I'm wondering, why does Dolibarr bind to the LDAP sever with the user's DN? None of our other services with LDAP integration need do this. Is there any specific configuration necessary on the LDAP side to allow Dolibarr auth to function correctly? Is there any documentation on this, other than [https://wiki.dolibarr.org/index.php/Module_LDAP_En](Module_LDAP_En)?

Also, as far as I understand, solving this issue would not allow LDAP auth to work directly. We would still need to use sync_users_ldap2dolibarr.php to create the users in the dolibarr MySQL database, correct?

## [Attached files]auth

relevant part of conf.php
```
// Authentication settings
$dolibarr_main_authentication='ldap';
$dolibarr_main_auth_ldap_host='ldap';                  
$dolibarr_main_auth_ldap_port='389';                        
$dolibarr_main_auth_ldap_version='3';
$dolibarr_main_auth_ldap_servertype='openldap';                
$dolibarr_main_auth_ldap_login_attribute='uid';          $dolibarr_main_auth_ldap_dn='ou=users,dc=mydomain,dc=de';
$dolibarr_main_auth_ldap_filter = '(uid=%1%)';   
$dolibarr_main_auth_ldap_admin_login='cn=admin,dc=mydomain,dc=de';                                
$dolibarr_main_auth_ldap_admin_pass='adminpassword';                                  
$dolibarr_main_auth_ldap_debug='true';
```

Dolibarr debug output
```
DEBUG: Logging LDAP steps
DEBUG: Server:ldap, Port:389, Protocol:3, Type:openldap
DEBUG: uid/samacountname=uid, dn=ou=users,dc=mydomain,dc=de, Admin:cn=admin,dc=mydomain,dc=de, Pass:adminpassword
DEBUG: login ldap = user.name
DEBUG: UACF =
DEBUG: pwdLastSet = 31/12/1969
DEBUG: badPasswordTime = 31/12/1600
DEBUG: sid = -1
```

LDAP Access Log
```
5bc87a48 conn=1034 fd=12 ACCEPT from IP=172.19.0.9:41456 (IP=0.0.0.0:389)
5bc87a48 conn=1034 fd=12 closed (connection lost)
5bc87a48 conn=1035 fd=12 ACCEPT from IP=172.19.0.9:41458 (IP=0.0.0.0:389)
5bc87a48 conn=1035 op=0 BIND dn="cn=admin,dc=mydomain,dc=de" method=128
5bc87a48 conn=1035 op=0 BIND dn="cn=admin,dc=mydomain,dc=de" mech=SIMPLE ssf=0
5bc87a48 conn=1035 op=0 RESULT tag=97 err=0 text=
5bc87a48 conn=1035 op=1 SRCH base="ou=users,dc=mydomain,dc=de" scope=2 deref=0 filter="(uid=user.name)"
5bc87a48 conn=1035 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
5bc87a48 conn=1035 op=2 UNBIND
5bc87a48 conn=1035 fd=12 closed
5bc87a48 conn=1036 fd=12 ACCEPT from IP=172.19.0.9:41460 (IP=0.0.0.0:389)
5bc87a48 conn=1036 fd=12 closed (connection lost)
5bc87a48 conn=1037 fd=12 ACCEPT from IP=172.19.0.9:41462 (IP=0.0.0.0:389)
5bc87a48 conn=1037 op=0 BIND dn="cn=User Name,ou=users,dc=mydomain,dc=de" method=128
5bc87a48 conn=1037 op=0 BIND dn="cn=User Name,ou=users,dc=mydomain,dc=de" mech=SIMPLE ssf=0
5bc87a48 conn=1037 op=0 RESULT tag=97 err=0 text=
5bc87a48 conn=1037 op=1 SRCH base="ou=users,dc=mydomain,dc=de" scope=2 deref=0 filter="(uid=user.name)"
5bc87a48 conn=1037 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
5bc87a48 conn=1037 op=2 SRCH base="ou=users,dc=mydomain,dc=de" scope=2 deref=0 filter="(uid=user.name)"
5bc87a48 conn=1037 op=2 SRCH attr=objectsid
5bc87a48 conn=1037 op=2 SEARCH RESULT tag=101 err=32 nentries=0 text=
5bc87a48 conn=1037 op=3 UNBIND
5bc87a48 conn=1037 fd=12 closed
```

**Comment by VoidScute** [comment]
It’s look like i also have some issues with the ldap connection. Maybe it’s a miss configuration on my side.

Do you achieve a user connection with an existing, authorize, never connected to dolibarr user ? 

 And no the documentation is really really poor

**Comment by VoidScute** [comment]
I will come back soon. a new install will occurs.

**Comment by dpriskorn** [comment]
Please upgrade to a supported version (10,11 or 12) and reopen this if the problem persists.

**Comment by imrajeshs** [comment]
Still it is not working in version 18

**Comment by imrajeshs** [comment]
> Please upgrade to a supported version (10,11 or 12) and reopen this if the problem persists.

please recheck in the latest version (18)

![image](https://github.com/Dolibarr/dolibarr/assets/132876725/bc7e97e5-0420-4550-9ac4-df8516ab0df4)

**Comment by hregis** [comment]
@imrajeshs no problem for me with v18, can you show me the entire configuration of ldap in your dolibarr

**Comment by imrajeshs** [comment]
> @imrajeshs no problem for me with v18, can you show me the entire configuration of ldap in your dolibarr

Attached the configuration and tested screenshots...

![image](https://github.com/Dolibarr/dolibarr/assets/132876725/14856e0b-c186-4702-8382-74d4f594c6b6)
![image](https://github.com/Dolibarr/dolibarr/assets/132876725/508c6cd5-7feb-4361-9072-875fef0a3e88)
![image](https://github.com/Dolibarr/dolibarr/assets/132876725/e8cb45cb-ebac-4264-b8a4-36c7b49e0db2)

Thanks for your help...

**Comment by hregis** [comment]
@imrajeshs try with : 

User's DN : dc=Users,dc=mtrcmt,dc=com  (instead : ou=Users)
List of objectClass : person  (instead : user)
Search filter : `&(objectclass=person)`
Full name : cn

**Comment by hregis** [comment]
@imrajeshs or maybe : cn=Users,dc=mtrcmt,dc=com

**Comment by imrajeshs** [comment]
> @imrajeshs try with :
> 
> User's DN : dc=Users,dc=mtrcmt,dc=com (instead : ou=Users) List of objectClass : person (instead : user) Search filter : `&(objectclass=person)` Full name : cn
Tried, but still same error is coming...
![image](https://github.com/Dolibarr/dolibarr/assets/132876725/93378002-3199-42e5-ac98-ff178416b646)

This is the error

**Comment by hregis** [comment]
@imrajeshs cn=Users instead dc=Users

**Comment by imrajeshs** [comment]
> Contributor

Thanks, it seems working. But not fetching all the records!?

![image](https://github.com/Dolibarr/dolibarr/assets/132876725/4e3142dd-2d44-4e87-b6dc-6b663b4d305a)
![image](https://github.com/Dolibarr/dolibarr/assets/132876725/5ea49a9d-0bda-4df2-882a-13429c89af4e)

**Comment by imrajeshs** [comment]
Ok I got it...
I changed to OU and its name...

![image](https://github.com/Dolibarr/dolibarr/assets/132876725/35dd128a-dc69-450d-88f9-959a34148ab1)

**Comment by imrajeshs** [comment]
Thanks a lot to you...

**Comment by imrajeshs** [comment]
But how to download / sync the users to Dolibarr ??? Or automatic sync will be done? any idea

**Comment by imrajeshs** [comment]
Ok Got it, we need to add by selecting LDAP database user.

![image](https://github.com/Dolibarr/dolibarr/assets/132876725/0801755b-cf45-41b0-8f2c-a66be2e41f48)

**Comment by imrajeshs** [comment]
Thanks for the support... Is it possible use the same domain user / password by having auto sync ?

**Comment by hregis** [comment]
@imrajeshs with "ldap -> dolibarr" the password is in active directory, not in dolibarr
