### ISSUE TITLE
Feature Request: Add a Sumup module

### ISSUE THREAD

**Issue by Mavyre** [Dolibarr/dolibarr#9815]
# Feature Request
Add a Sumup module to use Sumup online payments and credit/debit card payment terminal.

## Use case
Like any other payment method (Paypal/Strip), we could pay using a web address.
We could also pay an invoice or in PoS using the SumUp payment terminal.

## Suggested implementation
Add the address of payment everywhere are Paypal and Stripe used.
A button could be added if an invoice is unpaid to trigger the Sumup application directly from Dolibarr.
The same button could be used in the PoS. If the payment is successful, the invoice (or PoS sale) is automatically set to paid.

## Suggested steps
1. Implement the Sumup web payment API (Quite easy - see http://docs.sumup.com/checkouts/#checkout-flow - it even has a fancy Card Form ready, so nothing much to do like Paypal and Strip).
2. Add a button that calls the Sumup Android app (simpler than the previous step - see https://github.com/sumup/sumup-android-api#payment-api---web) and create a callback endpoint that closes the invoice if it's successful. There should be a user right to have the button displayed.
3. (Optional but recommended) Add the same button to the PoS module.

**Comment by Hexor38** [comment]
Steel needed feature. (message to disable issue's stale state)

**Comment by Mavyre** [comment]
@Hexor38 Actually, we can close this issue. Sumup has been added to the TakePOS core by myself on PR #12512 ; still no online payment options as it requires a lot of steps to enable it on SumUp side, account by account.
You can see on the documentation the hidden options to enable Sumup in the POS.

**Comment by Syl20-G** [comment]
Hello. i ve the last version 15.0
Is it possible to have payment via sumup for  memberships fees? only paypal or stripe but i don't use them.
regards

![image](https://user-images.githubusercontent.com/48908995/156336764-c077f957-af36-4fc9-b119-c74f28d1cb6d.png)

**Comment by Mavyre** [comment]
Hello @Syl20-G,

My pull request was only to add SumUp payment with the physical card reader device and was integrated into the TakePoS core module. 

If you want to use the SumUp online payment, we should create a new payment module - like Paypal or Stripe. Feel free to contribute!
