### ISSUE TITLE
Accounting export as CSV returns an empty CSV

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#9836]
# Bug
When you try to export your book accounting, the generated CSV is empty. This problem is due to a limit applied when it should not (on line thtdocs/accountancy/class/bookkeeping.class.php:994). This limit is already applied in the query.

## Environment
- **Version**: 8.0.3
- **Database**: MYSQL
- **URL(s)**: [server]/htdocs/accountancy/bookkeeping/balance.php?mainmenu=accountancy&leftmenu=accountancy_balance

## Expected and actual behavior
The CSV should be populated by the accounting.

## Steps to reproduce the behavior
1. Go on the url
2. Click on "export (CSV)"
3. The CSV is empty

**Comment by ghost** [comment]
#10006
