### ISSUE TITLE
Bug: 7.0.4 : Searching Parameter Not Working

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#9862]
# Bug

Product Search generally works **except** it does not allow multiple searches using the **|** parameter

### Upto Dolibarr v5.0.4:
Using barcode scanner, multiple barcodes could be scanned using `|` and then select `Products/Services` in the dropdown

## In Dolibarr v7.0.0 > 7.0.4:
Using barcode scanner for single product is fine.  Searching for `12345|12345` should pause at the dropdown so I can select `Products/Services` but instead skips to the first line (`Third Parties`) and then searches the societe list instead of products.

## Environment
- **Version**: [*7.0.0 > 7.0.4*]
- **OS**: [*CentOS7*]
- **Web server**: [*Apache*]
- **PHP**: [*7.0*]
- **Database**: [*MySQL*]
- **URL(s)**: [*search feature*]

**Comment by atm-maxime** [comment]
I think nothing has changed, only thing is that using a barcode scanner sends the barcode value and the enter key. If you configure your scanner not to end with the enter key, you will be able to scan and then select "product/service" in the dropdown.

**Comment by aljawaid** [comment]
@atm-maxime Thanks for the reply.  Something definitely has changed somewhere as the issue never existed in v5.0.4.

On the first scan, it pauses until i select a menu but using the "|" parameter fails after second barcode.

**Comment by atm-maxime** [comment]
Hi.
Do you still have the issue ? I tried manually and typing 123|456 manually allows me to select "Product/Service" afterwards.
So for me it comes from your barcode scanner. I think it sends the "enter" key, but as you can see, the dropdown list refreshes itself while typing something. If your barcode scanner sends the enter key whil the dropdown is refreshing, nothing happens and you can select what you want to search. But if the enter key is send just after the dropdown has refreshed, it automatically goes on thirdparties.
So I think this might depend on the javascript reactivity for the search dropdown.
