### ISSUE TITLE
Suggestion: Potential customers WITHOUT customer code

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#9870]
Dear Sirs, I would like to recommend a change in Dolibarr, since I believe it is an "error" as a functionality is intended.

Many times people who are not customers, request a budget, not being customers, it is not worth it (since you do not know if you are going to place the order or not) assign a Client Code and an Accounting Code, since in a single year you can end up with hundreds of thousands of assigned codes to people or companies that have not bought you anything.

Taking advantage that Dolibarr has the functionality to distinguish between Client, Client / Potential Client, and Potential, it could be done, that any of the two alternatives "Client / Potential Client" or "Potential" allow to make budgets, but without assigning any code, the which will be assigned only when the state becomes "client" (which would be positive if it were automatic, when the budget was validated and the order was made).

Unfortunately, Dolibarr, when the Advanced Accounting module is activated, requires whether or not to assign a Client Code.

Unfortunately as this thought Dolibarr does not allow people who are not even customers (yet) make budgets, because if you want to make a budget (although they will not buy it) if or if they are assigned a code, which in the end, slowed down the database and the server.

I hope I have expressed myself well, and I regret the errors that Google Translator
a greeting

Juan Brillo

-------------------------
En español
Estimados Sres., quisiera recomendar un cambio en Dolibarr, ya que creo que es un "error" tal y como esta pensada una funcionalidad.

En muchas ocasiones personas que no son clientes, nos solicitan un presupuesto, al no ser clientes, no merece la pena (ya que no sabes si te va a realizar el pedido o no) asignarle un Codigo de Cliente y un Codigo Contable, ya que en un solo año puede acabar con cientos de miles de Codigos Asignados a personas o empresas que no te han comprado nada.

Aprovechando que Dolibarr tiene la funcionalidad de distinguir entre Cliente, Cliente/Cliente Potencial, y Potencial, se podria hacer, que cualquiera de las dos alternativas "Cliente/Cliente Potencial" o "Potencial" permitan realizar presupuestos, pero SIN asignar ningun codigo, el cual sera asignado unicamente cuando el estado pase a "cliente" (el cual seria positivo que fuera automatico, al validarse el presupuesto y realizarse el pedido).

Lamentablemente, Dolibarr, cuando se activa el modulo de Contabilidad Avanzada, obliga si o si a asignar un Codigo de Cliente.

Lamentablemente como esta pensado Dolibarr no permite tener personas que aunque no sean clientes (aun) hacerles presupuestos, ya que si quieres hacerles un presupuesto (aunque no lo vayan a comprar) si o si se les asigna un codigo, cosa que al final, ralentida la base de datos y el servidor.

Espero haberme expresado bien, y lamento los errores que Google Translator pueda haber cometido.

Un saludo

**Comment by JuanBrillo** [comment]
The suggestion is still active since this problem still persists in the latest versions, and I think it would be interesting to apply the suggestion, and more in order to comply with the GDPR with people who do not become customers despite asking for prices or offers.


La sugerencia sigue activa puesto que aun este inconveniente persiste en las ultimas versiones, y creo que seria interesante aplicar la sugerencia, y mas de cara a cumplir con la RGPD con personas que no llegan a ser clientes a pesar de pedir precios u ofertas.

**Comment by dpriskorn** [comment]
Is this fixed?
