### ISSUE TITLE
Bug: 7.0.4 : Expense Report Langs not loaded correctly

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#9880]
# **Bug**
Expense report fails to show the lang strings for `ExpenseReport` in the page title.  The string `LineNb` is also not in `trips.lang` but adding it has no effect.

---
_LINE 1315:_
```$title=$langs->trans("ExpenseReport") . " - " . $langs->trans("Card");```
is defined in `.trips.lang` as `ExpenseReport=Internal Expense Report` and `Card=Summary`

**BUT IN THE PAGE TITLE:**
![image](https://user-images.githubusercontent.com/10233708/47559971-d91b1380-d90e-11e8-9f9e-390b450da638.png)
---

**THE SAME HAPPENS IN THE HEADER:**
![image](https://user-images.githubusercontent.com/10233708/47560022-f819a580-d90e-11e8-8341-fc02649196a3.png)
---

**LINE NUMBER IS NOT TRANSLATED EITHER:**
Setting `LineNb=Line N°` has no effect.
![image](https://user-images.githubusercontent.com/10233708/47560194-7a09ce80-d90f-11e8-8e09-20f790afe283.png)
---

## Environment
- **Version**: [*7.0.4*]
- **OS**: [*CentOS*]
- **Web server**: [*Apache*]
- **PHP**: [*7.0*]
- **Database**: [*MySQL*]
- **URL(s)**: [*/expensereport/card.php*]

**Comment by aspangaro** [comment]
I don't see any problems with your example. Work fine in 9.0.0beta

**Comment by aljawaid** [comment]
@aspangaro 
`LineNb=Line N°` is not being translated
`ExpenseReport=Internal Expense Report` is not being translated

I have tried adding the strings in `trips.lang`
My current version is `7.0.4`

**Comment by aspangaro** [comment]
The language keys for which you look are in the file main.lang

846 ExpenseReport=Expense report
860 LineNb=Line nb

**Comment by aljawaid** [comment]
@aspangaro Thanks!  For some reason I kept looking in `trips.lang`
