### ISSUE TITLE
Bug: Trying to use the function of Credit invoices for suppliers, for the first time. 

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#9882]
# Bug

## Environment
- **Version**: 8.0.2
- **OS**: Linux
- **Web server**: Apache/2.4.25
- **PHP**: apache2handler 7.2.11-2+0~20181015120801.9+stretch~1.gbp8105e0
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL**: /azerty/htdocs/fourn/facture/card.php?id=212&action=confirm_valid&confirm=yes

## Report

1. Trying to use the function of Credit invoices for suppliers, for the first time. The first one I made was for a suppliers invoice not yet paid, and it all went well, but the second one was for a suppliers invoice already paid, and then it hangs, giving the message "Duplicate entry '1' for key 'uk_facture_fourn_ref' " and I can't go further. It must be possible to correct an already paid invoice so pls correct this because sometimes you find the misstake quite long after the invoice has been paid..

2.There is no way to make the settings to controll the serial numbers of the credit invoices. It just gave the first credit invoice the serial number 210 and I don't know were that figure comes from. Pls correct.

3. At last, but certainly not the least, there shuold be a functin where it is possible to create credit invices that are not connected to any earlier issued invoice number. Pls arrange.

**Comment by atm-maxime** [comment]
Already fixed, the module setup was not allowing a numbering mask for the credit notes.

**Comment by atm-maxime** [comment]
Fixed by #9744

**Comment by hasse-basse** [comment]
Hi

Sorry for writing in a closed thread, but as far as I can see you have only  addressed number 2, about the masking. Number 1 still remains open; I can't issue a credit note for an already paid suppliers invoice, or are you telling me it is included in the mask issue?

You didn't address my number 3, the possibility to create credit invoices without connecting them to an invoice.

And while writing, there is anohter issue as well that I forgot to mention:  When listing all suppliers invoices, it is normally possible to  click on Preview, but that button is missing on the suppliers credit invoice..
