### ISSUE TITLE
Bug: 7.0.4: Supplier Price Min Quantity Not Maintained

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#9906]
# Bug
When adding a line to the supplier order, the ajax filter shows the correct minimum quantity but when selecting, the minimum quantity always defaults to 1.

![supplier-order-min-qty](https://user-images.githubusercontent.com/10233708/47615036-63937c80-daa1-11e8-8075-93847cbf8ead.gif)

## Environment
- **Version**: [*7.0.4*]
- **OS**: [*CentOS*]
- **Web server**: [*Apache*]
- **PHP**: [*7.0.32*]
- **Database**: [*MySQL*]
- **URL(s)**: [*/fourn/commande/card.php?id=227#addline*]

## Expected and actual behavior
Minimum quantity should be pre-filled like previous versions

**Comment by aljawaid** [comment]
Not sure if it is linked to #9561 #9904

**Comment by aljawaid** [comment]
#9577

**Comment by aljawaid** [comment]
#9592

**Comment by atm-maxime** [comment]
Fixed in 8.0
