### ISSUE TITLE
Bug : 8.0.2  Payment terms in Dictionary [blocking]

### ISSUE THREAD

**Issue by VoidScute** [Dolibarr/dolibarr#9911]
# Bug
Can’t add Payment terms in Dictionary.

## Environment
- **Version**: [*8.0.2*]
- **OS**: [*Devuan Stable,Debian Testing*]
- **Web server**: [*apache2*]
- **PHP**: [*7 mpm_itk*]
- **Database**: [*postgres 9 - 10*]
- **URL(s)**: [*/admin/dict.php?id=12*]

## Expected and actual behavior
Can’t add a new Payment terms in dictionnary. It says Record already exists

## Steps to reproduce the behavior
Go to admin/dict.php?id=12 try to add 

Code                | Label           | Label on documents | No. of days | At end of month | Offset | Sort order
 PT_30303010 | 30/30/30/10 | test                            | 1 | none |  |

click to add

I think it’s the auto inc which is broken, it try to add with id 7 when i try from sql request.

**Comment by simnandez** [comment]
I can't reproduce the pb, it is possible that the llx_c_payment_term table in your database is corrupted. check it
