### ISSUE TITLE
Bug: webmail

### ISSUE THREAD

**Issue by achrefest** [Dolibarr/dolibarr#9915]
# Bug
The requested URL /dolibarr/webmail/tabs/user_webmailconf.php was not found on this server.
## Environment
- **Version**: 8.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/user/notify/card.php?id=11

**Comment by simnandez** [comment]
webmail does not exist in dolibarr, should you have a problem with an external module
