### ISSUE TITLE
Bug: tiers ajoutés depuis un utilisateur avec des droits d'accès limités

### ISSUE THREAD

**Issue by achrefest** [Dolibarr/dolibarr#9916]
# Bug tiers ajoutés depuis un utilisateur avec des droits d'accès limités
pour un utilisateur qui a comme droit de créer des tiers mais de voir que ceux qui lui sont liés, il ne peut pas voir les tiers qui'il ajoute. il doit être automatiquement configurer comme commercial pour ces tiers
merci pour votre effort, Dolibarr est miraculeux !!
## Environment
- **Version**: 8.0.2
- **OS**: Windows NT
- **Web server**: Apache/2.4.9 (Win32) PHP/5.5.12
- **PHP**: apache2handler 5.5.12
- **Database**: MySQL or MariaDB 5.0.45-community-nt
- **URL**: /dolibarr/societe/index.php?mainmenu=companies&leftmenu=

**Comment by inoveaconseil** [comment]
I don't see the bug

**Comment by atm-maxime** [comment]
Fixed
