### ISSUE TITLE
Invisible text on dark GTK+ themes

### ISSUE THREAD

**Issue by ntd** [Dolibarr/dolibarr#9917]
This is the same issue described by #4642 but I am unable to reopen that PR. The user agent is firefox, the GTK+ theme is standard Adwaita dark.

With the `md` theme the text inside any non-select2 input is invisible. With the `eldy` theme also the buttons are affected. Here is my (filled) login form:
![login](https://user-images.githubusercontent.com/160618/47699437-37980880-dc13-11e8-820c-1755cfad94b8.png)

**Comment by ntd** [comment]
Upstream mozilla bug is 18 years old: https://bugzilla.mozilla.org/show_bug.cgi?id=70315

**Comment by john-botella** [comment]
This bug corresponding to a os theme and affect all html interface view with your web-browser not necessary Dolibarr.
This issue can be clause
