### ISSUE TITLE
simple accounting does not take miscellaneous payments and loans into account

### ISSUE THREAD

**Issue by rakeshpatil1983** [Dolibarr/dolibarr#9953]
# Bug
Activating the simple accounting does not account the miscellaneous payments and loans into account

## Environment
- **Version**: [*8.0.2*]
- **OS**: [*Cent os*]
- **Web server**: [*apache*]
- **PHP**: [*any*]
- **Database**: [*mysql*]

## Expected and actual behavior
Simple accounting module must include all the entries of debit from various modules and show as expenses collectively and credit from various entries as income collectively respectively

## Steps to reproduce the behavior
Enable the simple accounting module make entries in the loan and miscellaneous payments, go to accounting and click on reporting.

# Feature Request
Simple accounting can also have a feature to add activated modules selectively to include the expenses and incomes from these modules respectively

**Comment by atm-maxime** [comment]
Hi. There has been a lot of work on the complete accountancy module lately and the basic accountancy module hasn't evolve. So you're right, loans and free bank entries are not present in the reports.
@aspangaro, did you have some feedback about this ?

**Comment by meierrom** [comment]
Hi folks,

This has been resolved.
Miscellaneous payments and loans can now be activated in the settings.

Kind regards,
Roman
