### ISSUE TITLE
Extrafield filter type "date" in command list

### ISSUE THREAD

**Issue by alexolait** [Dolibarr/dolibarr#9964]
# Bug
Filter problem with extrafield type date in command list

## Environment
- 8.0.3
- Windows 2012 standard Server
- Apache 2.4.4
- PHP 5.4.19
- MySQL 5.5.32
- URL(s): /dolibarr/commande/list.php

## Expected and actual behavior
Have a correct result when we make filter on a date with an extrafield

## Steps to reproduce the behavior
Create a date extrafield on command module.
Go on command list and make a filter with the date of your extrafiels
The filter doesn't work and display this date: 01/01/1970

## [Attached files]
![image](https://user-images.githubusercontent.com/22803868/48124872-af061180-e27d-11e8-899c-aabdab41046a.png)

**Comment by ghost** [comment]
WIP

**Comment by ghost** [comment]
Same on propal
