### ISSUE TITLE
DoliOSM acceptable in core?

### ISSUE THREAD

**Issue by pangoSE** [Dolibarr/dolibarr#9979]
Hi. 
I have a question.
Is a little module I adapted from [ZenFusion-Maps](https://www.dolistore.com/en/modules/443-ZenFusion-Maps-for-Google.html?search_query=maps&results=5) to display links to [openstreetmap.org](http://nominatim.openstreetmap.org) on addresses acceptable to put in core?

If not is there any guidelines for deciding what to reside in core and not?

**Comment by aljawaid** [comment]
That would be nice.... does it show maps and driving instructions etc?

**Comment by jfefe** [comment]
@pangoSE Go go go! Please submit your pull request with this before version freeze :)

**Comment by BebZ** [comment]
I say it too Go²Go²Goooo !! :)

**Comment by pangoSE** [comment]
> does it show maps and driving instructions etc?

No, just link from addresses. Driving instructions are available on osm.org after the link is clicked. 

> Please submit your pull request with this before version freeze :)

I have a lot on my hands right now so it will take a while before I succede in getting it uploaded.

**Comment by ChangePlaces** [comment]
Wouldn't this be better as a free module?

**Comment by aljawaid** [comment]
> 
> 
> Wouldn't this be better as a free module?

I disagree, I think it should be part of the core as users (with permissions) would find it useful to see on a map where their customers or suppliers would be located.  Very handy for customer and supplier deliveries too

**Comment by ChangePlaces** [comment]
But it relies on a third party site. What if this site goes down, what if it's hacked, what if the data collection policy is not favourable to companies etc. By including it in core, Dolibarr are stating "hey, this site is cool and it's ok to use it"

**Comment by ghost** [comment]
There is  already thirdparty application included module like PayPal or Paylib.
