### ISSUE TITLE
Product Buying price extra charges improvements

### ISSUE THREAD

**Issue by r9guy** [Dolibarr/dolibarr#9997]
# Feature Request
product buying price contains field called charges, 
make a second input field called charges input in percent %.
the system will calculate charges from the price including tax or excluding, selected by drop-down list

## Use case
items purchased internationally are subject to customs clearance, and the rate of this expenses is known in percentages.

## Suggested implementation
its similar to VAT calculation in product buying tab

**Comment by aljawaid** [comment]
https://github.com/Dolibarr/dolibarr/commit/2cd5ed65a658dec9cc94d2bb900a944554db09a8#diff-8a67280615804c0b628e61eda6618314
The original feature appears to be hidden for `v7.0` and removed in `v8.0` based on this commit so not sure what is going on there.
