### ISSUE TITLE
Bug in ODT shipments contacts address

### ISSUE THREAD

**Issue by KlaasOl** [Dolibarr/dolibarr#9999]
Bug
[Using ODT template to generate an transport-label. While having an contact-address submitted to the shipping, it uses the company address in stead of the contact-address. This while the PDF templates seems to works OK]

Environment
- **Version**:[8.0.2]
- **OS**:[Linux Ubuntu 16.04]
- **Web server**: [Apache/2.4.18 (Ubuntu)]
- **PHP**: [7.0.32-0ubuntu0.16.04.1]
- **Database**:[ MySQL or MariaDB 5.7.24-0ubuntu0.16.04.1]
- **URL(s)**: [/htdocs/expedition/card.php]

Expected and actual behavior
[Expecting the contact-address it uses the company_address]

**Comment by ghost** [comment]
WIP
